### ISSUE TITLE
storage/engine: large number of open sstables after workload

### ISSUE THREAD

**Issue by darinpp** [cockroachdb/cockroach#42317]
**Describe the problem**

I hit a problem with too many files open after a `workload init tpcc`. It was a bit surprising that `cocroach` opens that many files and that they stay open after the workload initialization is done. @ajkr seems to think too that this should not happen.

**To Reproduce**

To reproduce - just do `cockroach workload init tpcc --warehouses 3500 --data-loader IMPORT`

Here is what saw as the number of handles open:
```
-- before start
lsof |wc -l
2942

-- after cockroach started
lsof |wc -l
4310

-- ~1 min after ./cockroach workload init tpcc --warehouses 3500 --data-loader IMPORT
lsof |wc -l
27602

-- ~10 min after workload init start
lsof |wc -l
157488

-- load finished
lsof |wc -l
528719

lsof | grep 016807.sst | wc -l
46

lsof | grep 025226.sst | wc -l
46
-- cockroach terminated
lsof |wc -l
2942
```
The limit in my case was a default and set to 1024 
```
ulimit -n
1024
```
If possible, provide steps to reproduce the behavior:

**Expected behavior**
I wouldn't expect the exact same files open 46 times. 

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version [19.2.0-rc4]
 - Server OS: [Ubuntu 18.04.1]
 - Client app []

**Additional context**
What was the impact?

I got a separate message of too many open files when I was running unrelated apps on the same server.

**Comment by petermattis** [comment]
It's not clear if this is a bug or working as expected. RocksDB caches open files and we'll have to determine if the heuristic CockroachDB is using is working correctly or not. As @ajwerner points out, `lsof` lists a file once for each thread, so we probably have only ~11k open sstables. That's still a lot, but not unheard of for RocksDB.

**Comment by petermattis** [comment]
I've verified the `lsof` behavior mentioned above. I've also verified that the count of open sstables matches the count of on-disk sstables both during and after running the IMPORT mentioned above.

Note that `ulimit -n` is the soft limit. CRDB increases the limit to the hard limit at startup, as it is a file descriptor hungry process (well, RocksDB/Pebble are).
