### ISSUE TITLE
Performance issues with a specific join

### ISSUE THREAD

**Issue by Martigan88** [cockroachdb/cockroach#42328]
We are having performance issues when querying chrg_cd_vw.  We have been able to isolate the slowness to the join against fac_cst_cntr.

Here are the SQLs used to create the tables:
[chrg_cd_vw.txt](https://github.com/cockroachdb/cockroach/files/3826121/chrg_cd_vw.txt)
[chrg_cd.txt](https://github.com/cockroachdb/cockroach/files/3826125/chrg_cd.txt)
[fac_chrg.txt](https://github.com/cockroachdb/cockroach/files/3826133/fac_chrg.txt)
[ems_entity_xlate.txt](https://github.com/cockroachdb/cockroach/files/3826135/ems_entity_xlate.txt)
[chrg_cd_nte.txt](https://github.com/cockroachdb/cockroach/files/3826139/chrg_cd_nte.txt)
[spl.txt](https://github.com/cockroachdb/cockroach/files/3826140/spl.txt)
[fac_cst_cntr.txt](https://github.com/cockroachdb/cockroach/files/3826143/fac_cst_cntr.txt)
[fac_cst_cntr_alter.txt](https://github.com/cockroachdb/cockroach/files/3826144/fac_cst_cntr_alter.txt)

I will find a way to upload the debug dump later.  It is currently 181MB and can't be uploaded here...

**Comment by Martigan88** [comment]
I forgot to say this, but we are running version 19.1.3.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4074](https://cockroachdb.zendesk.com/agent/tickets/4074) has been linked to this issue.

**Comment by robert-s-lee** [comment]
replacing `LEFT JOIN` with `LEFT LOOKUP JOIN` in the view definition to forced the `lookup join` terminate early once the `limit` is satisfied.
