### ISSUE TITLE
Exceptions upon select

### ISSUE THREAD

**Issue by Martigan88** [cockroachdb/cockroach#42327]
We are seeing the following in our logs:
[exception.txt](https://github.com/cockroachdb/cockroach/files/3826174/exception.txt)

Here is the SQL we used to create the table:
[sbmt_chrg_cd_imprt.txt](https://github.com/cockroachdb/cockroach/files/3826176/sbmt_chrg_cd_imprt.txt)

I will find a way to upload the debug dump later.  It is currently 181MB and can't be uploaded here...

**Comment by jordanlewis** [comment]
What version of CockroachDB are you running? Any schema changes ongoing on the table?

**Comment by Martigan88** [comment]
Sorry about that, I thought I had included the version.
We are running 19.1.3.  There are no ongoing schema changes to the table.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4075](https://cockroachdb.zendesk.com/agent/tickets/4075) has been linked to this issue.

**Comment by robert-s-lee** [comment]
@jordanlewis the error does not seem to all of the time.  The theory there is read/update that causes this select to be retries.  The application retries that somehow triggers this.

@Martigan88 per our discussion as a workaround for now please try:
```
SET CLUSTER SETTING kv.closed_timestamp.follower_reads_enabled = true;
select *
from sbmt_chrg_cd_imprt as x AS OF SYSTEM TIME experimental_follower_read_timestamp()
order by sbmt_id DESC
limit 58 offset 0;
```

**Comment by robert-s-lee** [comment]
Believe this is the same https://github.com/cockroachdb/cockroach/issues/41630

**Comment by Martigan88** [comment]
Yup. Looks like it!
