### ISSUE TITLE
cli: improve the Cockroach CLI's fluency in CockroachSQL syntax

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#4233]
PSQL runs pg's SQL lexer while reading input at the prompt, which allows it to have a better understanding of user-provided sql and react more intelligently. See [this comment](https://github.com/cockroachdb/cockroach/pull/4210#discussion_r52126277) for context. It might be worth hooking CockroachDB's CLI up to our lexer and parser to allow us to provide a better user experience by:
- Understanding when the user is in the middle of a string literal
- Providing some degree of autocorrection
- More?

**Comment by petermattis** [comment]
Hooking up the lexer seems reasonable as the lexing rules are fairly static. Hooking up the parser is more questionable. It's easy enough to do, but it might limit the SQL dialect to what is supported when the SQL shell was compiled. Of course, you usually access the SQL shell from the exact same cockroach binary that is running your cluster, so perhaps that isn't a problem.
