### ISSUE TITLE
Enable nodelocal I/O in `cockroach demo`

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#42335]
**Is your feature request related to a problem? Please describe.**
Currently, `cockroach demo` doesn't have nodelocal storage enabled. This means you have to use `cockroach start` if you want to test or demonstrate any bulk I/O features.

**Describe the solution you'd like**
`cockroach demo` should accept the `--external-io-dir` flag in the same way that `cockroach start` does. It may even be reasonable to default the external I/O directory to the working directory in which `cockroach demo` is started.

**Comment by bdarnell** [comment]
We shouldn't default `--external-io-dir` to the current directory (which in practice is likely to be the user's home directory). The bulk-io blob service makes the contents of that directory accessible over the network (without authentication in an insecure cluster like demo).

**Comment by rolandcrosby** [comment]
Ahh, that's a good point - it should be explicit. We should also consider allowing the user to wire up multiple external-io-dirs when running multi-node demo.

**Comment by georgebuckerfield** [comment]
I had a quick look at this and got something working. I was thinking you could have a `--node-localdirs` flag (or similar) which accepts a list of directories; these could then be passed to each node in order e.g.
```
--node-localdirs=/tmp/node1,/tmp/node2
```
Is that the sort of behaviour you'd want?

**Comment by bdarnell** [comment]
A list of directories seems awkward if you're working with say a nine-node cluster. Maybe it's just one directory and we auto-create numbered per-node directories?

I think there are a few distinct use cases here - for testing import/restore, you want to just pass one (non-empty) directory and have it available on at least one node (maybe just mount it on all of them?) For backup, though, you'd rather have it create empty directories for you.

@rolandcrosby What use case did you have in mind for this? I think the import use case is probably most important so I'd lean towards supporting a single non-empty directory.

**Comment by mwang1026** [comment]
Closing as won't do, due to `userfile` being a thang
