### ISSUE TITLE
storage: Pebble test failures

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#42353]
The failures here can be reproduced with:

```
~ COCKROACH_STORAGE_ENGINE=pebble make test PKG=./storage TESTS=...
```

The failures are:

```
=== RUN   TestDecommission
...
F191110 19:09:40.925507 1129995 vendor/go.etcd.io/etcd/raft/log.go:214  [n4,s4,r1/6:{-}] applied(291) is out of range [prevApplied(0), committed(0)]
--- FAIL: TestSplitSnapshotRace_SplitWins (45.63s)
--- FAIL: TestSplitSnapshotRace_SnapshotWins (45.69s)
--- FAIL: TestConsistencyQueueRecomputeStats (2.61s)
    --- FAIL: TestConsistencyQueueRecomputeStats/hadEstimates=false (1.31s)
    --- FAIL: TestConsistencyQueueRecomputeStats/hadEstimates=true (1.30s)
--- FAIL: TestLearnerRaftConfState (1.76s)
```

Additional, several tests needed to be skipped due to never finishing:

```
--- SKIP: TestReplicateQueueRebalance (0.00s)
```

**Comment by sumeerbhola** [comment]
I am trying to debug `TestSplitSnapshotRace_SplitWins` which goes through some splits and add and remove of replicas (including the shiny new VOTER_DEMOTING).
In the RocksDB based test, which passes, after the last state transition
```
I191111 18:11:02.719717 37 storage/replica_raft.go:290  [s5,r35/4:{m-/Table/Syste…},txn=6e84a5d0] proposing SIMPLE(r2) REMOVE_REPLICA[(n2,s2):2LEARNER]: after=[(n4,s4):1 (n5,s5):4 (n6,s6):5] next=6
I191111 18:11:02.723368 1279 storage/store_remove_replica.go:129  [s2,r35/2:{m-/Table/Syste…}] removing replica r35/2
```
there is a snapshot sent from n5 to n4
```
I191111 18:11:02.775400 18643 storage/store_snapshot.go:978  [raftsnapshot,s5,r35/4:{m-/Table/Syste…}] sending RAFT snapshot eb9ea770 at applied index 38
I191111 18:11:02.776276 18643 storage/store_snapshot.go:1021  [raftsnapshot,s5,r35/4:{m-/Table/Syste…}] streamed snapshot to (n4,s4):1: kv pairs: 26, log entries: 0, rate-limit: 8.0 MiB/sec, 0.00s
I191111 18:11:02.780614 18630 storage/replica_raftstorage.go:794  [s4,r35/1:{m-/Table/Syste…}] applying RAFT snapshot [id=eb9ea770 index=38]
I191111 18:11:02.784894 18630 storage/replica_raftstorage.go:815  [s4,r35/1:{m-/Table/Syste…}] applied RAFT snapshot [total=4ms ingestion=4@4ms id=eb9ea770 index=38]
```

But this last step does not happen in the Pebble test since it gets stuck at a preceding
```
mtc.waitForValues(rightKey, []int64{0, 0, 0, 2, 5, 5})
```
with 
```
I191111 18:10:16.838472 27 storage/client_test.go:1297  SucceedsSoon: expected [0 0 0 2 5 5], got [0 2 2 2 5 5]
```

Do the first two 2's in there correspond to nodes n2 and n3 which don't even have the range? I am looking for suggestions on where to look next.

**Comment by petermattis** [comment]
That's the exact failure I see when running on Pebble. You'll want to pull in someone from KV to help understand the test itself. @andreimatei, @nvanbenschoten, or @ajwerner are all good choices.

**Comment by petermattis** [comment]
Re-opening as not all of the failures in `storage` have been fixed.

**Comment by petermattis** [comment]
`TestSystemZoneConfigs` sometimes fails with:

```
I191113 20:29:01.211218 1443506 storage/replica_raft.go:290  [n7,s7,r1/3:/{Min-System/NodeL…}] proposing SIMPLE(l10) ADD_REPLICA[(n4,s4):10LEARNER]: after=[(n5,s5):7 (n1,s1):8 (n7,s7):3 (n6,s6):4 (n2,s2):5 (n3,s3):9 (n4,s4):10LEARNER] next=11
F191113 20:29:01.212679 1411650 storage/store_create_replica.go:225  [n4,s4] found non-zero HardState.Commit on uninitialized replica [n4,s4,r1/?:{-}]. HS={Term:7 Vote:3 Commit:513 XXX_unrecognized:[]}
goroutine 1411650 [running]:
```

I've also seen this failure for `cli.TestRemoveDeadReplicas`.

Looks like we also need to whitelist marshaling of `roachpb.InternalTimeSeriesData` below Raft which can happen as part of the MVCC merge operator.

**Comment by petermattis** [comment]
I've seen the `non-zero HardState` failure with `TestDecommission`. `TestSystemZoneConfigs` also fails with:

```
I191113 21:28:02.370719 102561 storage/replica_raft.go:290  [n4,s4,r1/2:/{Min-System/NodeL…}] proposing SIMPLE(l8) ADD_REPLICA[(n6,s6):8LEARNER]: after=[(n7,s7):6 (n4,s4):2 (n5,s5):3 (n3,s3):4 (n1,s1):7 (n6,s6):8LEARNER] next=9
F191113 21:28:02.372259 86059 vendor/go.etcd.io/etcd/raft/log.go:214  [n6,s6,r1/8:{-}] applied(231) is out of range [prevApplied(0), committed(0)]
goroutine 86059 [running]:
```

There is some evidence this is related to range tombstones.

**Comment by petermattis** [comment]
I've looked at two different occurrences of this failure and they both have a similar pattern. We delete a replica from a node, and then sometime later the assertion happens:

```
I191114 16:54:54.277019 5946 storage/replica_raftstorage.go:794  [n5,s5,r2/3:{-}] applying LEARNER snapshot [id=ed950c5b index=67]
I191114 16:54:54.323052 5946 storage/replica_raftstorage.go:815  [n5,s5,r2/3:/System/NodeLiveness{-Max}] applied LEARNER snapshot [total=46ms ingestion=4@39ms id=ed950c5b index=67]
I191114 16:55:21.478025 2615 storage/store_remove_replica.go:129  [n5,s5,r2/3:/System/NodeLiveness{-Max}] removing replica r2/3
F191114 16:55:31.665928 2526 storage/store_create_replica.go:225  [n5,s5] found non-zero HardState.Commit on uninitialized replica [n5,s5,r2/?:{-}]. HS={Term:6 Vote:0 Commit:108 XXX_unrecognized:[]}
```

My understanding is that this commit can only fire if `/Local/RangeID/2/u/RaftHardState` is present. 

The above reproduction occurred when I was running the test such that the data is being written to disk and Pebble's archival file cleaner is enabled. This allows spelunking the on-disk data. 

```
COCKROACH_STORAGE_ENGINE=pebble ../../cockroach debug pebble db scan cluster/5/ --key=pretty:cockroach_comparator --value=null --comparer=cockroach_comparator --merger=cockroach_merge_operator | grep /Local/RangeID/2/
/Local/RangeID/2/u/RaftTombstone/0.000000000,0
```

This shows that the current state of the database believes that the only key that exists for `r2` is the `RaftTombstone`. My recollection is that this is the only key that should exist after a replica has been removed from a node.

Further instrumentation shows:

```
I191114 16:55:21.375575 2615 storage/replica_application_state_machine.go:799  [n5] pebbleBatch.Commit
RANGEDEL(/Local/RangeID/2"",/Local/RangeID/3/"")
I191114 16:55:21.478025 2615 storage/store_remove_replica.go:129  [n5,s5,r2/3:/System/NodeLiveness{-Max}] removing replica r2/3
```

So we removed the replica at `16:55:21.478025`. Shortly before that, on the same goroutine, we committed a batch containing a range deletion for the local range keys for `r2`. The next flush to occur on this node happens a few seconds later:

```
I191114 16:55:25.781461 12885 vendor/github.com/cockroachdb/pebble/compaction.go:1140  [n5] [JOB 102] flushing: sstable created 000179
```

Inspecting this sstable the range tombstone is present:

```
COCKROACH_STORAGE_ENGINE=pebble ../../cockroach debug pebble sstable layout cluster/5/archive/000179.sst --key=pretty:cockroach_comparator --value=null -v
...
    161999  range-del (69)
    161999    record (19 = 3 [0] + 12 + 4) [restart]
              /Local/RangeID/2""/0.000000000,0-/Local/RangeID/3""/0.000000000,0#13712,RANGEDEL
```

Shortly after `000179.sst` is created, it is involved in a compaction:

```
I191114 16:55:25.903394 12587 vendor/github.com/cockroachdb/pebble/compaction.go:990  [n5] [JOB 103] compacting L0 [000179 000174 000177 000175 000176] (168 K) + L3 [000172 000161] (108 K)
I191114 16:55:26.286227 12587 vendor/github.com/cockroachdb/pebble/compaction.go:1022  [n5] [JOB 103] compacted L0 [000179 000174 000177 000175 000176] (168 K) + L3 [000172 000161] (108 K) -> L3 [000180] (182 K)
I191114 16:55:27.476605 13173 vendor/github.com/cockroachdb/pebble/compaction.go:1528  [n5] [JOB 107] sstable deleted 000179
```

Our range tombstone is present in the new sstable (`000180.sst`):

```
COCKROACH_STORAGE_ENGINE=pebble ../../cockroach debug pebble sstable layout cluster/5/000180.sst --key=pretty:cockroach_comparator --value=null -v
...
    185387  range-del (375)
    185387    record (19 = 3 [0] + 12 + 4) [restart]
              /Local/RangeID/2""/0.000000000,0-/Local/RangeID/3""/0.000000000,0#13712,RANGEDEL
```

Note that this sstable is still live. There is only 1 live WAL, but it contains no mention of `r2`:

```
COCKROACH_STORAGE_ENGINE=pebble ../../cockroach debug pebble wal dump cluster/5/000201.log --key=pretty:cockroach_comparator --value=null | grep /Local/RangeID/2/
```

Summary: we wrote a range tombstone to disk, and later are able to read a key that is supposed to be deleted by that range tombstone. But everything appears to be copacetic on disk when we later check. I'm going to add more instrumentation when the assertion actually fires to see if I can tease out whether the problem is due to some sort of in-memory corruption or rare sequence of operations.

**Comment by petermattis** [comment]
This is fun:

```
[n3,s3] found non-zero HardState.Commit on uninitialized replica [n3,s3,r9/?:{-}]. HS={Term:6 Vote:0 Commit:244 XXX_unrecognized:[]}
[n3,s3]   /Local/RangeID/9/u/RaftTombstone/0.000000000,0 21
[n3,s3]   done: /Local/RangeID/10/r/RangeLastGC/0.000000000,0
[n3,s3] second HardState read: err=<nil>: {Term:6 Vote:0 Commit:244 XXX_unrecognized:[]}
[n3,s3] third HardState read: found=true err=<nil>: {Term:6 Vote:0 Commit:244 XXX_unrecognized:[]}
```

I added additional instrumentation before the non-zero HardState fatal error. The first line indicates that we found a non-zero HardState via `StateLoader.LoadHardState`. The next two lines are the output of iterating over all of the keys with the prefix `/Local/RangeID/9`. As we can see, the only key present is the `RaftTombstone` as expected. The `second HardState read` line corresponds to loading the hard state again with `StateLoader.LoadHardState`. And the third corresponds to `engine.MVCCGetProto` (which is what `StateLoader.LoadHardState` uses).

Why are `engine.MVCCGetProto` and `StateLoader.LoadHardState` finding a non-empty HardState when iteration doesn't? In both cases, the iterator being used is coming from an `engine.Pebble` so it isn't be cached. Perhaps pool allocation is to blame.

**Comment by petermattis** [comment]
The instrumentation above is revealing a difference between `SeekGE` and `SeekPrefixGE`. The former is respecting a range tombstone, but the latter isn't. Here is the scenario where that happens:

```
L3: 102:[a#10.RANGEDEL,d#9.DEL] 101:[f#8.SET,h#7.SET]
L4: 100:[a#5.SET,b#4.SET]
```

We have two levels, L3 and L4. Sstable 102 contains the range tombstone `[a-c)#10` and the point record `d#9.DEL`. Sstable 100 and the lower level contains the point record `a#5.SET`. What happens if we `SeekPrefixGE("a", "a")`? We'd expect the result to be that `a` is deleted as the range tombstone in L3 covers the SET in L4. But consider what happens in `levelIter.SeekPrefixGE` in L3. `levelIter.findFileGE` correctly sees that "a" is contained within the bounds of 102. It then calls `sstable.Reader.SeekPrefixGE("a", "a")` on that file which returns "not found" as the bloom filter successfully determines that the key is not present in the sstable. What happens next? The code for `levelIter.SeekPrefixGE` is fairly simple:

```
func (l *levelIter) SeekPrefixGE(prefix, key []byte) (*InternalKey, []byte) {
	if !l.loadFile(l.findFileGE(key), 1) {
		return nil, nil
	}
	if key, val := l.iter.SeekPrefixGE(prefix, key); key != nil {
		return key, val
	}
	return l.skipEmptyFileForward()
}
```

Because we couldn't find "a" in sstable 102, we consider the sstable empty and advance to the next sstable via the call to `skipEmptyFileForward`. The logic in `skipEmptyFileForward` to prevent advance to the next sstable when a range tombstone straddles the two sstables doesn't trigger because the largest key in 102 is not a range tombstone. The end result is that `mergingIter` sees L3 positioned at sstable 101 and thus desired range tombstone is not found.

I see two ways to addresss this problem. One is to create a synthetic boundary key in `levelIter.SeekPrefixGE`:

```
	if !l.loadFile(l.findFileGE(key), 1) {
		return nil, nil
	}
	if key, val := l.iter.SeekPrefixGE(prefix, key); key != nil {
		return key, val
	}
	// When SeekPrefixGE returns nil, we have not necessarily reached the end of
	// the sstable. All we know is that a key with prefix does not exist in the
	// current sstable. We know that key lies within the bounds of the table. If
	// we have a range tombstone iterator, we need to return a synthetic boundary
	// so that mergingIter can use the range tombstone iterator.
	if l.rangeDelIter != nil {
		f := &l.files[l.index]
		l.syntheticBoundary = f.Largest
		l.syntheticBoundary.SetKind(InternalKeyKindRangeDelete)
		l.boundary = &l.syntheticBoundary
		return l.boundary, nil
	}
	return l.skipEmptyFileForward()
```

The other alternative is to change `sstable.Reader.SeekPrefixGE`. I haven't fleshed out exactly what this would look like. Something along the lines of seeking to the last key in the file if the bloom filter indicates the prefix isn't present. That seems semantically odd, though. Right now I'm leaning towards the synthetic boundary key approach, and and quick prototype indicates it seems to work, at least in the scenario above.

@sumeerbhola Would appreciate your thoughts on this?
