### ISSUE TITLE
webui: ui-test flaky

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#42365]
See for example https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=1585634&_focus=1458

```
38]
[Test web UI] HeadlessChrome 78.0.3904 (Linux 0.0.0): Executed 130 of 320 SUCCESS (0 secs / 3.06 secs)
[11:56:38]
[Test web UI]  [1A [2KHeadlessChrome 78.0.3904 (Linux 0.0.0) Query Management Saga integration tests AUTO_REFRESH/STOP_AUTO_REFRESH action sets inRunning flag on reducer when query is running. FAILED
[11:56:38]
[Test web UI] 	AssertionError: expected 2 to equal 1
[11:56:38]
[Test web UI] 	    at src/redux/queryManager/saga.spec.ts:20980:34
[11:56:38]
[Test web UI] HeadlessChrome 78.0.3904 (Linux 0.0.0): Executed 131 of 320 (1 FAILED) (0 secs / 3.079 secs)
[11:56:38]
[Test web UI]  [1A [2KWARN: '[WARNING]:', 'Saga exceeded async timeout of 250ms'
[11:56:38]
[Test web UI] HeadlessChrome 78.0.3904 (Linux 0.0.0): Executed 131 of 320 (1 FAILED) (0 secs / 3.079 secs)
[11:56:39]
[Test web UI]  [1A [2KWARN: '[WARNING]:', 'Saga exceeded async timeout of 250ms'
[11:56:39]
[Test web UI] HeadlessChrome 78.0.3904 (Linux 0.0.0): Executed 131 of 320 (1 FAILED) (0 secs / 3.079 secs)
```

**Comment by tbg** [comment]
@piyush-singh I've had CI fail on this a couple of times in the last 3 working days, so I think we need to fix this soon. I don't know how to fix it, though I can skip the entirety of `make uitest` from the hot CI path if you think that's preferrable (I'd wager it's not).

**Comment by tbg** [comment]
The entirety of the `make ui-test` target is now skipped. Apologies for taking such a drastic measure, but it just failed so many builds already.

The commit that did so is in https://github.com/cockroachdb/cockroach/pull/42833.

**Comment by piyush-singh** [comment]
Apologies @tbg, looks like the PR to fix was stuck in the bors queue. Pinged the issue and will update here once it is merged and the tests are passing again (and will re-enable `make ui-test`).
