### ISSUE TITLE
sql: support RETURNING

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#4236]
We need a way to get back the id of an inserted row with a default primary key function. Postgres uses RETURNING, and we should too.

**Comment by JackKrupansky** [comment]
And if the table has no PK, will there be a way to return the rowid hidden
column?

-- Jack Krupansky

**Comment by mjibson** [comment]
Users can currently select from and insert into a hidden rowid column manually. I'm not aware of a reason they wouldn't be able to do that in a RETURNING. I'm not sure *why* they would want to do that, since the whole point of a no PK table is that you don't need to use the PK ever, but they should be able to.
