### ISSUE TITLE
sql/opt: name resolution for schemas when creating new objects should account for permissions/privileges 

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#42383]
As part of work to support temporary tables, the `system.namespace` table is being extended to include an additional `ParentSchemaID`. This is a step towards supporting additional physical schemas other than `public` (even though none can be created yet). 

Currently, the optimizer assumes that tables can only be created under the `public` schema and does no permission check. As we add the ability to scope under different schemas, a simple name check is not enough. 

Instead, there needs to be a check to see if the schema exists + the user has privileges to create an object under that schema.

**Comment by ajwerner** [comment]
I am sure that there are issues here. I'm going to close this because it's so unactionable.
