### ISSUE TITLE
the row number doesn't match the actual file

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#42403]
**Describe the problem**

using the following dataset to repro:
getting the following messages when importing the file:
gs://artem_cockroach_bucket/aka_name.csv

```
pq: gs://artem_cockroach_bucket/aka_name.csv: row 59381: expected 8 fields, got 9
pq: gs://artem_cockroach_bucket/aka_name_no_59381.csv: row 47501: expected 8 fields, got 9
pq: gs://artem_cockroach_bucket/aka_name_last_800000.csv: row 11258: expected 8 fields, got 9
```

The file ranges in number of fields, either 7 or 8.

**To Reproduce**

1. Set up 19.1.5 CockroachDB cluster
2. Connect to SQL Shell and run the following:
```
CREATE DATABASE imdbload;
DROP TABLE aka_name;
IMPORT
TABLE imdbload.aka_name (
	id integer NOT NULL PRIMARY KEY,
    person_id integer NOT NULL,
    name text NOT NULL,
    imdb_index character varying(12),
    name_pcode_cf character varying(5),
    name_pcode_nf character varying(5),
    surname_pcode character varying(5),
    md5sum character varying(32)
	)
CSV
	DATA ('gs://artem_cockroach_bucket/aka_name.csv');
```

**Expected behavior**
Import will continue until an error with record 59381 will fail.

**Environment:**
 - CockroachDB version 19.1.5
 - Server OS: Linux artem-test-0003 4.15.0-1026-gcp #27~16.04.1-Ubuntu SMP Fri Dec 7 09:59:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
 - Client app: roachprod sql

**Additional context**
Cannot Import the row in question

**Comment by spaskob** [comment]
Discussed this in the bulk-io slack thread, this looks like working as expected due to quotes being really tricky in CSV format. For more info, see https://github.com/cockroachdb/cockroach/issues/42403 and also  https://github.com/cockroachdb/cockroach/pull/41610 which introduces option `WITH strict_quotes` that requires more CSV compliant use of quotes.

**Comment by spaskob** [comment]
@dbist  Please let me know if this addresses the problem and re-assign to me if there's still work to be done.

**Comment by dbist** [comment]
this is not an issue, using `WITH strict_quotes` solves the problem. Filed https://github.com/cockroachdb/docs/issues/5851 to document the flag.
