### ISSUE TITLE
pgwire: TimeZone ParameterStatus field incorrect with offsets

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#42404]
Found in #42376. 

When using `SET TIME ZONE +3` on initialisation or after changes over pgwire, the output in `ParameterStatus` is mismatching:

```
# cockroach
{"Type":"ParameterStatus","Name":"TimeZone","Value":"6"}
# postgres
{"Type":"ParameterStatus","Name":"TimeZone","Value":"\u003c+06\u003e-06"}
```

Furthermore, adding timezones such as `-7.55` is incorrect.

See tests in `pkg/sql/pgwire/testdata/pgtest/connection_params` for more info.

**Comment by knz** [comment]
still current

**Comment by RichardJCai** [comment]
I believe this is because of timezones are formatted in the respective databases.

CRDB
```
demo@127.0.0.1:26257/movr> show timezone;
  timezone
------------
  -11.5
(1 row)
```

PG
```
rcai=# show timezone;
    TimeZone
----------------
 <-11:30>+11:30
(1 row)
```
