### ISSUE TITLE
sql: consider schema in table collection

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/cockroach#42424]
Currently the table collection cache can return incorrect results if there are two tables with the same name, one in the temp schema and one in the public schema.

**Comment by otan** [comment]
are there more precise examples of how this can come about?

**Comment by solongordon** [comment]
I believe the following is a manifestation of this issue:
```
root@127.0.0.1:54117/defaultdb> set experimental_enable_temp_tables=true;
SET

root@127.0.0.1:54117/defaultdb> create table t (public int);
CREATE TABLE

root@127.0.0.1:54117/defaultdb> create temp table t (temp int);
CREATE TABLE

root@127.0.0.1:54117/defaultdb> select * from public.t;
  public
----------
(0 rows)
```
[wait for a minute]
```
root@127.0.0.1:54117/defaultdb> select * from public.t;
  temp
--------
(0 rows)

Time: 1.812ms
```
I believe this is related to the fact that we do not take schema into account when caching table names, only database ID and table name: https://github.com/cockroachdb/cockroach/blob/73a648c4caf2d22f28ff17eeba20bbc84517e602/pkg/sql/lease.go#L1257-L1260.
