### ISSUE TITLE
schema change: DROP DATABASE still waiting for GC TTL after 25h

### ISSUE THREAD

**Issue by roncrdb** [cockroachdb/cockroach#42427]
**Describe the problem**

When user runs `show jobs` there are two schema change jobs that are `DROP DATABASE <database> CASCADE` that show up as "Waiting for GC TTL".  The schema change was started on 11/07. 

**To Reproduce**

Attached are system.descriptor, system.namespace and system.jobs as well as debug zip, all files can be dowloaded [here](https://drive.google.com/drive/folders/17tyBBokGAso_TMJzK83GLUiQ6suf5Dc_?usp=sharing). 

**Expected behavior**
These jobs should be marked as complete and no longer show up when running `SHOW JOBS`. 

**Environment:**
 - CockroachDB version 19.1.5
 - Server OS: GKE
 - Client app [e.g. `cockroach sql`, JDBC, ...]

cc @dt @pbardea

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4080](https://cockroachdb.zendesk.com/agent/tickets/4080) has been linked to this issue.

**Comment by ajwerner** [comment]
Relates to #40411.

Here's my current understanding of what might be going on. In the current logic a DROP DATABASE is decomposed into a single job with many schema changes which each drop tables. It doesn't seem like there's any mutual exclusion over dropping different tables from the same drop database job.

Instead, the way the schema changer seems to work is that nodes read the set of schema changes and then try to grab them. DROP DATABASE seems to get decomposed into its constituent tables which each end up in a map called `forGC`. There's a timer channel which sits in the main `for { select` loop kicked off by `SchemaChangeManager.Start()`. When it fires a random table which can be GC'd is chosen. 

https://github.com/cockroachdb/cockroach/blob/0045a08df7670bf95babb1fa5a1c2c2a895df8b0/pkg/sql/schema_changer.go#L2239-#L2248

Different nodes get signaled on their `gcTimer` around the same time but choose different tables. They all read the job in a transaction first. Then they grab a lease on the schema change for the table. Then they go do stuff, namely delete tables. Finally they try to update the job and table descriptors (IIUC). This can lead to failures to update the job status.

Here's an example of a schema change which failed to update the job:

```
W191108 21:35:37.812596 231 sql/schema_changer.go:386  [n3,scExec] failed to update job 501640312392515585: TransactionRetryWithProtoRefreshError: WriteTooOldError: write at timestamp 1573248934.685123606,0 too old; wrote at 1573248936.687359640,1
W191108 21:35:44.182417 242 sql/schema_changer.go:386  [n1,scExec] failed to update job 501640312392515585: TransactionRetryWithProtoRefreshError: WriteTooOldError: write at timestamp 1573248943.546665586,0 too old; wrote at 1573248943.899447227,1
```

Once all of the tables have been GC'd no new work will ever be run by the `SchemaChanger` to move the job status again.

**Comment by roncrdb** [comment]
So this seems like it's easily reproducible on a geo distributed cluster. 

Here is the roachprod command I used: 

`roachprod create $CLUSTER -n 3  --gce-zones=us-west1-a,us-central1-b,asia-southeast1-c --geo`

`roachprod stage $CLUSTER release v19.1.5`

`roachprod start $CLUSTER` 

Then I ran this python script (note you would need to [install the Faker](https://pypi.org/project/Faker/) if you decide to use this script): 

```
from faker import Faker
import psycopg2
import time

f = Faker()

conn = psycopg2.connect(
    database='defaultdb',
    user='root',
    sslmode='disable',
    port=26257,
    host='34.68.43.167'
)

conn.set_session(autocommit=True)

cur=conn.cursor()

db_create = "create database if not exists testing_drops;"
cur.execute(db_create)

use_testing = "use testing_drops;"
cur.execute(use_testing)

tables = []

for x in range(1,1000):
    #f.bban just creates random basic bank account numbers, this could be changed to randomn ints or UUID's without the dash
    new_table = "create table {} (id uuid, name string);".format(f.bban().lower())
    tables.append(new_table)

for table in tables:
    cur.execute(table)
    cur.execute("insert into {} values('{}', '{}');".format(table.split(' ')[2], f.uuid4(), f.name()))

print("tables have been created and all have one row inserted, now we alter the gc.ttl")

cur.execute("ALTER RANGE default CONFIGURE ZONE USING gc.ttlseconds = 900;")
print("gc.ttl altered, now we wait 1 minute before dropping all the tables.")
time.sleep(60)

cur.execute('DROP DATABASE testing_drops CASCADE;')
``` 

After running this script, I noticed a lot of the same errors in my [debug zip](https://drive.google.com/file/d/1gOSz0KIcqyObM6sRVRTTOJ7LNy_e-d8b/view?usp=sharing) that @ajwerner posted above: 

```
ron-droptingdatabases-0003> W191114 17:11:32.545564 179 sql/schema_changer.go:386  [n3,scExec] failed to update job 503577095517700098: TransactionRetryWithProtoRefreshError: WriteTooOldError: write at timestamp 1573751489.187861396,0 too old; wrote at 1573751492.099124973,1
ron-droptingdatabases-0001> W191114 17:11:38.903840 97 sql/schema_changer.go:386  [n1,scExec] failed to update job 503577095517700098: TransactionRetryWithProtoRefreshError: WriteTooOldError: write at timestamp 1573751498.295807242,0 too old; wrote at 1573751498.588467688,1
ron-droptingdatabases-0003> W191114 17:11:39.948355 179 sql/schema_changer.go:386  [n3,scExec] failed to update job 503577095517700098: TransactionRetryWithProtoRefreshError: WriteTooOldError: write at timestamp 1573751496.740052926,0 too old; wrote at 1573751499.321430068,1
ron-droptingdatabases-0001> W191114 17:11:48.089908 97 sql/schema_changer.go:386  [n1,scExec] failed to update job 503577095517700098: TransactionRetryWithProtoRefreshError: WriteTooOldError: write at timestamp 1573751507.481933107,0 too old; wrote at 1573751507.756978149,1
```

**Comment by ajwerner** [comment]
IIUC this should end up getting fixed in upcoming work to move logic out of the per-node SchemaChanger into jobs. @lucy-zhang is this understanding correct?

In the shorter term I think there's an open question as to whether it's safe to just manually delete the job using the following SQL:

`DELETE FROM system.jobs WHERE id = 503577095517700098;`

We should experiment with that.

**Comment by ajwerner** [comment]
Linking to https://github.com/cockroachdb/cockroach/issues/42554 which I hope should capture fixing this problem.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4102](https://cockroachdb.zendesk.com/agent/tickets/4102) has been linked to this issue.

**Comment by lucy-zhang** [comment]
These are indeed orphaned jobs where all the tables in the database (presumably) have already been dropped successfully. After #45870 this can't happen anymore.
