### ISSUE TITLE
build: Upgrade builder toolchain kernel target

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#42430]
We currently build our linux binaries against a [minimum kernel version 2.6.32](https://github.com/cockroachdb/cockroach/blob/4b037ec61934a3708b26801f73fba634e7d8de02/build/builder/x86_64-unknown-linux-gnu.defconfig#L10), because that is the version used by RHEL 6 (released in 2010). I think it's time to advance that baseline to something newer, probably RHEL 7 (kernel 3.10). We can use [this crosstool-ng sample](https://github.com/crosstool-ng/crosstool-ng/blob/master/samples/x86_64-centos7-linux-gnu/crosstool.config) as a starting point for updating the config. 

One specific behavior change that would result from this upgrade is that rocksdb would be able to use the FALLOC_FL_PUNCH_HOLE flag. This is a very minor change but there may be other things we haven't uncovered yet. 

Also note that the minimum kernel version appears in the download tarball name; that will need to be updated unless we remove it (as discussed in #42417).

Epic CRDB-10447

Jira issue: CRDB-5356

**Comment by bdarnell** [comment]
`O_TMPFILE`, mentioned in https://github.com/cockroachdb/cockroach/pull/42542#issuecomment-557225492, was introduced in kernel 3.11.

**Comment by knz** [comment]
cc @kenliu

**Comment by knz** [comment]
still relevant

**Comment by andreimatei** [comment]
The new location defining the kernel version is, I believe, [this](https://github.com/cockroachdb/cockroach/blob/74b04aafbd7b835368b5555fcc7e5b320dff78cd/build/toolchains/toolchainbuild/crosstool-ng/x86_64-unknown-linux-gnu.config#L297).

For arm64, the kernel version is `3.7`, [here](https://github.com/cockroachdb/cockroach/blob/74b04aafbd7b835368b5555fcc7e5b320dff78cd/build/toolchains/toolchainbuild/crosstool-ng/aarch64-unknown-linux-gnueabi.config#L290).

**Comment by srosenberg** [comment]
There was an independent need to bump GLIBC to support an instrumentation library; it also made sense to bump the kernel version so that both aarch64 and x86_64 are in-sync: https://github.com/cockroachdb/cockroach/issues/83750
The corresponding PR should also addresses the issue raised here.

**Comment by srosenberg** [comment]
> How did you choose the specific values in that PR? 

Educated guess :)

> Kernel 4.1 is newer than what's in RHEL 7 (3.10), which some of our largest customers currently use. This would be a disruptive break in backwards-compatibility that we don't want to make lightly. 

I wasn't aware, but I am not surprised either.

> I would prefer to stick to the kernel and glibc versions in RHEL 7 as our compatibility targets unless we have a really good reason to raise them further.

Makes sense! How about kernel version `3.10` and glibc version `2.25`, for both architectures? (Technically, glibc `2.26` requires minimum kernel version `3.2`, so we could higher if need be.)

**Comment by bdarnell** [comment]
👍 to kernel version 3.10, but it looks like RHEL7 ships with glibc 2.17 so that's what we should use there.

**Comment by srosenberg** [comment]
> 👍 to kernel version 3.10, but it looks like RHEL7 ships with glibc 2.17 so that's what we should use there.

Thanks, downgraded to glibc 2.17.
