### ISSUE TITLE
Remove quotes from type, db, and table names

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#4243]
Since the switch to the pgwire drvier, `show databases`, `show tables`, and `show columns from <table>` return db, table, and type names in quotes. `psql` doesn't quote any of these. 

```
root@:15432> show columns from cockroaches;
+----------------+----------+-------+---------+
|     Field      |   Type   | Null  | Default |
+----------------+----------+-------+---------+
| "country_code" | "STRING" | false | NULL    |
| "count"        | "INT"    | true  | NULL    |
| "date"         | "DATE"   | true  | NULL    |
+----------------+----------+-------+---------+
root@:15432> show tables;
+---------------+
|     Table     |
+---------------+
| "cockroaches" |
+---------------+
```

Related notes from Docs [PR #40](https://github.com/cockroachdb/docs/pull/40):

@petermattis says: "This occurred with the switch to the pgwire driver. We can probably get rid of them as the formatting is up to us (currently we blindly use `%q` for any `[]byte` returned)."

cc: @RaduBerinde

**Comment by petermattis** [comment]
See https://github.com/cockroachdb/cockroach/blob/master/cli/sql_util.go#L177. We should probably check to see if the `[]byte` is utf8 and if it is format it with `%s` instead of `%q`. See https://golang.org/pkg/unicode/utf8/#Valid.
