### ISSUE TITLE
importccl,cli: concurrent IMPORTs cannot be started with default --max-sql-memory limit

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#42437]
In 19.2 IMPORT started respecting the SQL memory limit to prevent OOMs -- previously its usage was not tracked / limited and we just said that you needed to ensure you had enough headroom to run it.

IMPORT requires some minimum amount of buffering memory to construct reasonable files when ingesting -- anything below that we may force us to flush too often and thus see significantly degraded ingestion performance. Rather than silently degrade too far -- in some cases becoming nearly stuck -- when there isn't enough memory to reasonably run an IMPORT, we instead preemptively reserve a minimum amount (configurable, but defaulting to 32mb) for both the row data and index data (so 64MB total by default).

With the default value of the `--max-sql-memory` flag being 128mb, this means that with defaults settings, only one concurrent IMPORT can be run -- if you want to start another one, you will need configure  `--max-sql-memory` (as mentioned in the error message) to provide sufficient memory for it to run. 

However, `workload` by default runs many (9+) concurrent IMPORTs.

This means that *a node started with all defaults (e.g. just `cockroach start`) doesn't work with `workload init --data-loader=import`.* This is bad! Especially because `data-loader=import` is much faster and we'd like to make it the default.

In practice, we believe (and document) that production users will _always_ override the default value of the `--max-sql-memory`, to use something more reasonable: our docs, cli and even logged warnings all recommend setting it to something higher (25%). However the fact remains that the current default is 128mb, so many people do end up running with that, especially when kicking the tires.

We should `workload init` work with default-configured cockroach out of the box. Do do this we need to do some combination of three things:
- a) reduce the minimum `IMPORT` resource reservations
- b) reduce the number of concurrent IMPORTs run by `workload` to fit within the budget
- c) increase the default `--max-sql-memory` budget

I'm hesitant to do (a) - the minimum reservation was explicitly _added_ because of `workload`'s concurrent IMPORTs, when we observed starvation in one IMPORT causing subsequently hard to debug performance degradation. A hard error up front explaining that the resources required to run another concurrent imports were not available was much easier to fix (realizing we'd forgotten to set the `--max-sql-mem`) than a mysteriously stuck import.

Option (b) would work too, as the defaults allow for running IMPORT, just not many at the same time. However running IMPORTs concurrently makes a big difference in loading bigger fixtures. We could potentially only do them concurrently based on a flag (ugh) or against multi-node clusters where we are likely to be loading bigger fixtures where that matters, and can more likely assume that the docs advice to properly set `--max-sql-memory` has been followed. This could be a quick fix that would make `workload` work without changing production code (and we already check the node count when planning how to chunk up the imports we're sending anyway).

The defaults in IMPORT were mostly picked based on production testing, with non-trivial workloads, while the current default value for `--max-sql-memory` is explicitly noted as _inappropriate_ for production usage. Such a small default here likely mean _any_ subsystem that uses _available_ memory to try o run faster/better/etc (joins, buffering, etc) will be worse off with this default, making running with the default (which we say not to do!) a bad way to evaluate the DB. This default was dramatically shrunk back in 2017, in conjunction with the `cache` default to limit the memory usage of very small DBs, but according to @petermattis, the "growing to consume the limit" is a behavior specifically of the cache -- SQL's budget just got picked up in the same push to lower limits.

However to me, (c) seems ideal -- for reasons beyond IMPORT as well.  Such a small default here likely mean any subsystem -- not just IMPORT -- that uses available memory to try to run faster/better/etc  like join buffering or whatever will be worse off with this default, meaning anyone who evaluates with the default gets potentially non-representative (since we say to and test with it altered) performance and behavior. 

This default was shrunk back in 2017, in conjunction with the cache default, to limit the memory usage of very small / idle nodes. According to @petermattis, the growing-to-consume-the-limit  behavior that that change fixed is specific to the cache; SQL's budget isn't actively consumed by a mostly idle cluster the way that cache is. 

Overall, I'm inclined to return `--max-sql-memory` default to `.25` for the reasons above, though this likely requires input for @jordanlewis, @petermattis and/or @bdarnell.

**Comment by petermattis** [comment]
I have no strong objection to changing the default value of `--max-sql-memory`. Perhaps @bdarnell knows of a reason for not doing so.

**Comment by bdarnell** [comment]
I'm OK with increasing the `--max-sql-memory` default to `.25`. 

The hope was that these flags would be short-lived and we'd get a single memory-budget flag that we'd then be able to subdivide internally between cache and sql memory, and that gets a little harder if the defaults don't move in unison, but given the different behavior of the two flags I think it makes sense to split them.

**Comment by dt** [comment]
Okay, if that works for 20.1 I can make that change.

I don't know if it is worth backporting a `workload` change to reduce concurrency on single-node clusters (described as (b) above) for 19.2?

**Comment by danhhz** [comment]
Thanks for writing this up David! (c) is also my preference, and it sounds like that's the growing consensus.

In 19.2 `fixtures import` is hidden and `workload init --data-loader=import` is not the default, so I'm not concerned about it. If you're using it on 19.2, it's a hint that you're loading a lot of data and so reduced concurrency is probably a pessimization.

If we did eventually do something around (b), I'd want it to be based around workload having knowledge of the budget (in the same way it knows the number of nodes), potentially exposing it though SQL if it's not already there.
