### ISSUE TITLE
sql: consider whether TEXT should be preferred over STRING as the nominal text type

### ISSUE THREAD

**Issue by JackKrupansky** [cockroachdb/cockroach#4244]
Currently, STRING is the official text type in CockroachDB, but both MySQL and Postgres use TEXT.

The user can use TEXT, but it is treated as merely an alias for STRING, and shows up as STRING for the type of a... TEXT column, such as for the SHOW COLUMNS command.

I understand that there is some non-public history for this choice, but as Beta approaches it might be good to consider if the current behavior is really the most appropriate in terms of educating and migrating users with MySQL and Postgres experience.

**Comment by knz** [comment]
@cuongdo did we have an ORM-related issue about clients complaining that the name for the string type is "String" instead of "text"? I kinda remember something like that.

**Comment by cuongdo** [comment]
I don't recall that issue. @jordanlewis do you recall?

**Comment by jordanlewis** [comment]
I don't remember anything like this in my recent investigations either.

**Comment by knz** [comment]
I was thinking about #5582, in particular the linked issue #12526.

**Comment by jordanlewis** [comment]
We now report strings as `TEXT` in all places where we're trying to mimic the Postgres API. `STRING` is still the canonical CockroachDB name for string types, however.

**Comment by spencerkimball** [comment]
Closing this after @jordanlewis's last comment.
