### ISSUE TITLE
support postgres "with (fillfactor=n)" during "create table"

### ISSUE THREAD

**Issue by timveil** [cockroachdb/cockroach#42467]
**Describe the problem**

Postgres `create table` statement/syntax allows for the use of `with (fillfactor=100)`.  Cockroach does not allow this and immediately throws an error.  Would it be possible to support this syntax or "noop" it if not relevant?  This would increase compatibility with existing tooling such as `pgbench`.

```
ERROR:  at or near "(": syntax error
DETAIL:  source SQL:
create table pgbench_tellers(tid int not null,bid int,tbalance int,filler char(84)) with (fillfactor=100)

HINT:  try \h CREATE TABLE
```

see: https://www.postgresql.org/docs/11/sql-createtable.html

**To Reproduce**

1. Install postgres locally
```
brew install postgresql
```

2. Start single node CRDB instance
```
docker run -d --name=crdb --hostname=crdb -p 26257:26257 -p 8080:8080 cockroachdb/cockroach:latest start-single-node --insecure
```

3. Create a “pgbench” database in CRDB
```
docker exec -it crdb ./cockroach sql --insecure --execute='create database pgbench;'
```

4. Execute local pgbench against CRDB docker instance
```
pgbench -i pgbench --username=root --host=localhost --port=26257
```
**Expected behavior**
`pgbench` should run against cockroachdb without dying on `with (fillfactor=x)` syntax

**Additional data / screenshots**
See related forum post: https://forum.cockroachlabs.com/t/i-use-postgres-pgbench-to-test-cockroachdb-bug-error/1052/2

**Environment:**
 - CockroachDB version 19.2
 - Postgres 11.5.1

**Additional context**
N/A

**Comment by jordanlewis** [comment]
@rafiss could you pick this one off?
