### ISSUE TITLE
storage/engine: implement Pebble.GetTickersAndHistograms

### ISSUE THREAD

**Issue by hueypark** [cockroachdb/cockroach#42479]
The title says it all. For this, we should solve https://github.com/cockroachdb/pebble/issues/49.

**Comment by petermattis** [comment]
There is currently no intention to add RocksDB-style tickers and histograms to Pebble. That functionality is only used to power the `statusServer.EngineStats` endpoint (`/_status/enginestats/`) which is stuffed into `debug zip` and available on the advanced debug page of the Admin UI.
