### ISSUE TITLE
cli: crdb client commands should support GSSAPI based authentication

### ISSUE THREAD

**Issue by keith-mcclellan** [cockroachdb/cockroach#42488]
Currently, we require SQL users to use PSQL to connect to a cockroachdb cluster using GSSAPI authentication against Kerberos.  This makes troubleshooting very difficult so Cockroach SQL should be enhanced to work properly in this context.

**Comment by BramGruneir** [comment]
@thtruo take a look at this.

**Comment by BramGruneir** [comment]
@knz I think this is now complete for 20.2 correct?  

Do we have an open issue for our workloads (both the built in and stand alone binary) to use kerberos?

**Comment by knz** [comment]
no it's only done for SQL commands.

All the RPC (or mixed RPC/SQL) commands can't do GSSAPI just yet

**Comment by thtruo** [comment]
Circling back here - @knz do you think it's worth enabling RPC commands to do GSSAPI or should we proceed with the strategy outlined here https://github.com/cockroachdb/cockroach/issues/51454 to make all commands run behind SQL (and therefore solve the `cockroach workloads` issue without needing to make RPC play with GSSAPI)?

**Comment by knz** [comment]
The latter - all over SQL.

**Comment by thtruo** [comment]
Ack - thanks @knz. Also closing this issue too since the change is addressed https://github.com/cockroachdb/cockroach/pull/51570
