### ISSUE TITLE
sql: unify span generation code

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#42517]
We currently have a zoo of code for generating spans, each with its own quirks:
 - `spansFromConstraint` (used by `execFactory.ConstructScan`)
 - `sqlbase.MakeSpanFromEncDatums` (used by `execinfra.joinReader`) 
 - `sqlbase.EncodePartialIndexKey / EncodePartialIndexSpan`

The scan and the join reader have their own separate logic for when we can split a span into column families (and these are bound to rot/diverge given the work we are doing with families in secondary indexes):
https://github.com/cockroachdb/cockroach/blob/845bd7639fe144017e81eed59cd20f449239018c/pkg/sql/execinfra/indexjoiner.go#L223
https://github.com/cockroachdb/cockroach/blob/845bd7639fe144017e81eed59cd20f449239018c/pkg/sql/execinfra/joinreader.go#L352
https://github.com/cockroachdb/cockroach/blob/7bfa8f807c4960da6daf2ea31fd3ba70a7156354/pkg/sql/opt_index_selection.go#L164

We need to come up with a single consistent well-documented interface that is used everywhere. It's ok if we have a bunch of variants (e.g. for `Datums` vs `EncDatums`) as long as they all implement the same semantics.

I think there should be a `SpanBuilder` that you initialize with the index descriptor, optionally call something like `SetNeededFamilies` (which enables splitting into families) and which you can then use repeatedly to generate spans. This would hide the logic related to reusing the key interstices. There could even be a `SpanBuilder` cache to reuse stuff across queries.

**Comment by jordanlewis** [comment]
A `SpanBuilder` is a great idea. I think I tried doing the reverse once - a `KeyDeserializer` - and was dizzied by the complexity. But I think a builder would be more possible and very useful.

**Comment by jordanlewis** [comment]
cc @solongordon @rohany
