### ISSUE TITLE
sql: flattening error objects into other errors erases telemetry data and user hints

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#42510]
I found this while looking for something else:

```go
 func NewInvalidSchemaDefinitionError(err error) error {
       return pgerror.New(pgcode.InvalidSchemaDefinition, err.Error())
 }
```

By flattening the error with `err.Error()` this constructor strips the error object of all its details, including stack traces but also **user-directed hints, links to documentation issues and telemetry data**.

Other examples (non exhaustive):
```
execute.go:                     return nil, pgerror.New(pgcode.WrongObjectType, err.Error())
export.go:                      return nil, pgerror.New(pgcode.InvalidParameterValue, err.Error())
rowexec/hashjoiner.go:                                  err = pgerror.Wrapf(addErr, pgcode.OutOfMemory, "while spilling: %v", err)
set_var.go:             return wrapSetVarError("statement_timeout", s, "%v", err)
```

There are multiple ways to fix it:

- prefer `errors.Wrap[f]` when no need to add a pg code
- use `pgerror.WithCandidateCode` when need to add a pg code if there wasn't one already to start with
- use `errors.Combine` or `errors.WithSecondaryError` to combine errors together

I am fixing the first example at the top in #42509, but the other cases remain to be fixed.

cc @cockroachdb/sql-execution

**Comment by knz** [comment]
there's at least one case remaining, so this is still current:
```
sem/tree/type_check.go:                 return nil, nil, pgerror.Newf(pgcode.DatatypeMismatch, "tuples %s are not the same type: %v", Exprs(exprs), err)
```

cc @rafiss

**Comment by rafiss** [comment]
@e-mbrown will be working in this

As one of the items, we should change `wrapSetVarError` so that it accepts an `error` as a parameter rather than just a string.
