### ISSUE TITLE
bulk-io: massive memory increase on backup

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#42527]
On v19.2.0:

Running on a single-node cluster with a single user DB and single table inside there. Table size is reported on the admin UI as ~417MB.

Starting with v19.2.0, running a full backup of the database makes the CGO memory jump permanently massive amounts.

Chronology of the VM graph below:
* 15:35: node started
* 15:36: backup run
* 15:45: another backup run

```
root@:26257/defaultdb> select description,started,finished from [show jobs] order by created desc;
                                                                                                                   description          |             started              |             finished 
+---------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+----------------------------------+
  BACKUP DATABASE roadmap TO 's3://cockroach-laughing-ladybug-backup/long-lived/roadmap/2019-11-17T15:45:09Z' AS OF SYSTEM TIME '-10s'  | 2019-11-17 15:45:26.629696+00:00 | 2019-11-17 15:45:38.215717+00:00 
  BACKUP DATABASE roadmap TO 's3://cockroach-laughing-ladybug-backup/long-lived/roadmap/2019-11-17T15:36:09Z' AS OF SYSTEM TIME '-10s'  | 2019-11-17 15:36:18.365607+00:00 | 2019-11-17 15:36:33.340904+00:00   
  BACKUP DATABASE roadmap TO 's3://cockroach-laughing-ladybug-backup/long-lived/roadmap/2019-11-17T15:32:09Z' AS OF SYSTEM TIME '-10s'  | 2019-11-17 15:33:02.193479+00:00 | 2019-11-17 15:33:13.382329+00:00 
  BACKUP DATABASE roadmap TO 's3://cockroach-laughing-ladybug-backup/long-lived/roadmap/2019-11-17T15:30:09Z' AS OF SYSTEM TIME '-10s'  | 2019-11-17 15:30:54.792326+00:00 | 2019-11-17 15:31:07.05828+00:00    
  BACKUP DATABASE roadmap TO 's3://cockroach-laughing-ladybug-backup/long-lived/roadmap/2019-11-17T15:22:09Z' AS OF SYSTEM TIME '-10s'  | 2019-11-17 15:23:08.114069+00:00 | 2019-11-17 15:23:20.941525+00:00 
```

![laughing-ladybug_mem](https://user-images.githubusercontent.com/5901480/69010218-d9dd7800-095d-11ea-837e-2f2df5263e80.png)

The 15:23 run was restarted with the env variable `COCKROACH_MEMPROF_INTERVAL=30s` and `ln -s prof:true /etc/malloc.conf` to enable jemalloc profiling.

A diff profile between before and after the 15:36 backup shows:
```
$ jeprof cockroach-v19.2.0.linux-amd64/cockroach --base jeprof.2019-11-17T15_35_49.597 jeprof.2019-11-17T15_36_49.597
(jeprof) top
Total: 847.7 MB
   612.9  72.3%  72.3%    612.9  72.3% cockroach::ToDBString (inline)
   234.4  27.6%  99.9%    234.4  27.6% rocksdb::AllocateBlock (inline)
     0.5   0.1% 100.0%      0.5   0.1% rocksdb::BlockBasedTable::PutDataBlockToCache
     0.0   0.0% 100.0%    865.8 102.1% DBExportToSst
     0.0   0.0% 100.0%    251.7  29.7% DBIncrementalIterator::next
     0.0   0.0% 100.0%      1.2   0.1% DBIncrementalIterator::seek
     0.0   0.0% 100.0%    234.1  27.6% DBIterNext
     0.0   0.0% 100.0%      1.2   0.1% DBIterSeek
```

![laughing-ladybug_jeprof](https://user-images.githubusercontent.com/5901480/69010302-a18a6980-095e-11ea-884c-04913eb249ab.png)

This is coming from [RowCounter::Count](https://github.com/cockroachdb/cockroach/blob/master/c-deps/libroach/row_counter.cc#L94) which was [migrated to C++](https://github.com/cockroachdb/cockroach/commit/33fd2d4ae2d592ad0ea9dec5a0d017c4aa2901f2#diff-52d1729601503fe4d0dcd5c713f1916f) for v19.2.0.

It seems to be overwriting the same object with a new `DBString` without freeing the previous value first. This is done for every row in an SSTable. This seems like not just temporary memory use but actual memory leak on the order of the data on disk.

**Comment by mberhault** [comment]
I'm pretty sure this is a leak. The `RowCounter` seems to be used to count the number of unique rows. It is called repeatedly:
```
// Count examines each key passed to it and increments the running count when it
// sees a key that belongs to a new row.
bool RowCounter::Count(const rocksdb::Slice& key, cockroach::roachpb::BulkOpSummary* summary) {
```

On every new row seen, it overwrites the instance variable:
```
prev_key = ToDBString(decoded_key);
```

`prev_key` is a DBString which is a complete copy of `decoded_key`:
```
// ToDBString converts a rocksdb::Slice to a DBString.
inline DBString ToDBString(const rocksdb::Slice& s) {
  DBString result;
  result.len = s.size();
  result.data = static_cast<char*>(malloc(result.len));
  memcpy(result.data, s.data(), s.size());
  return result;
}
```

Because `prev_key` is not `free`d before re-assignment, we will effectively be leaking memory corresponding to the number of row keys seen. I suspect that's all of them in the case of a full backup (haven't traced the way `RowCounter` is used).

**Comment by miretskiy** [comment]
Fixed in https://github.com/cockroachdb/cockroach/pull/42529
Backport to 19.2: https://github.com/cockroachdb/cockroach/pull/42535
