### ISSUE TITLE
UI: show --cluster-name in the UI if specified

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#42526]
19.2.0 added the [--cluster-name](https://github.com/cockroachdb/cockroach/pull/39270) to the `start` command. This flag is currently checked at `join` time and will optionally be required in certificates (19.2.x or 20.1).

Since this flag is a friendly name specified by the operators, we should display it in the admin UI. It's convenient way to distinguish between two clusters.

**Comment by AnkilP** [comment]
Hi @mberhault, can I claim this issue?

**Comment by nathanstilwell** [comment]
fixed by #43236. This feature is supported in versions 20.1 and later.
