### ISSUE TITLE
unimplemented: linter to make sure that all linked issues are still open

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#42548]
We should make a new test in `blacklist_test.go` to query GitHub to ensure that all linked issues are actually still open.

**Comment by jordanlewis** [comment]
We need to enhance this to be a linter that looks for all usages of the `unimplemented` package.

**Comment by awoods187** [comment]
I'm so excited about this work--I think it will make a huge difference for our customers.
