### ISSUE TITLE
execbuilder: can't stress execbuilder package

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#42553]
On an 8-core machine, running `make stress PKG='./pkg/sql/opt/exec/execbuilder/' STRESSFLAGS="-p=4"` makes the tests never finish. With `-p 1` they pass in ~10s.

@RaduBerinde , any idea what's going on?

**Comment by RaduBerinde** [comment]
Couldn't repro on a 6 core:
```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
3 runs so far, 0 failures, over 20s
4 runs so far, 0 failures, over 25s
4 runs so far, 0 failures, over 30s
5 runs so far, 0 failures, over 35s
```

Does it happen every time? Can you run it with `TESTTIMEOUT=1m` so we can see where it's stuck?

**Comment by RaduBerinde** [comment]
Also tried on a 12-core (he he)
```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
2 runs so far, 0 failures, over 20s
4 runs so far, 0 failures, over 25s
4 runs so far, 0 failures, over 30s
7 runs so far, 0 failures, over 35s
```

**Comment by andreimatei** [comment]
On my machine (8 core, 16 HT) it happens every time.
On my GCE worker (24 core hehe) I can't run good tests because when I stress to hard I run into #42558. 

I'm attaching the output from my machine with a 2m timeout. Feel free to close if there's nothing clear in it.

[out.txt](https://github.com/cockroachdb/cockroach/files/3861189/out.txt)
