### ISSUE TITLE
execbuilder: TestExecBuild/local/delete_range flaky because of unstable trace

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#42558]
Under load, a random test fails because the "kv trace" gets an extra heartbeat. Heartbeats are sent when a txn takes over 1s. The test hardcodes an expected kv trace.

The way I see it, this is yet another example of how this sorts of tests are very fragile. I don't know what to do other than cry myself to sleep and assign it to @knz who's refused to let me delete this sort of test in the past.

```
make stress  PKG='./pkg/sql/opt/exec/execbuilder/' STRESSFLAGS="-p=13"

        --- FAIL: TestExecBuild/local/delete_range (8.10s)
            logic.go:1662:

                testdata/delete_range:14: SELECT operation, message FROM [SHOW KV TRACE FOR SESSION]
                WHERE message LIKE '%DelRange%' OR message LIKE '%sending batch%'
                expected:
                    flow              DelRange /Table/53/1 - /Table/53/2
                    dist sender send  r24: sending batch 1 DelRng to (n1,s1):1
                    flow              DelRange /Table/53/1/601/0 - /Table/53/2
                    dist sender send  r24: sending batch 1 DelRng to (n1,s1):1
                    dist sender send  r24: sending batch 1 EndTxn to (n1,s1):1

                but found (query options: "") :
                    flow              DelRange /Table/53/1 - /Table/53/2
                    dist sender send  r24: sending batch 1 DelRng to (n1,s1):1
                    flow              DelRange /Table/53/1/601/0 - /Table/53/2
                    dist sender send  r24: sending batch 1 DelRng to (n1,s1):1
                    dist sender send  r24: sending batch 1 EndTxn to (n1,s1):1
                    dist sender send  r24: sending batch 1 HeartbeatTxn to (n1,s1):1
```

cc @jordanlewis

**Comment by knz** [comment]
well yes I certainly know what to do with this

**Comment by knz** [comment]
I went and looked into this. Are you sure your test failure is not actually revealing a bug to you? I don't see any good reason why a txn records should be heartbeated after EndTxn.

**Comment by andreimatei** [comment]
With parallel commits, the (first) `EndTxn` generally puts the transaction record in the `staging` state. The client continues to heartbeat the txn record afterwards while all the writes are verified, and then sends another `EndTxn` (not traced unfortunately) which marks the txn as `committed` and triggers cleanup.
The point of heartbeating while in the staging state is to prevent multiple would-be pushers from all attempting to verify the txn's writes. When finding a staging record that has also been heartbeated recently, these would-be pushers wait for the client to properly finish that txn rather than attempting to do it themselves.
Makes sense?

**Comment by tbg** [comment]
This also failed my merge in https://teamcity.cockroachdb.com/viewLog.html?buildId=1697318&buildTypeId=Cockroach_UnitTests.

**Comment by tbg** [comment]
Actually - no, the failure there has no heartbeat:


        --- FAIL: TestExecBuild/local/delete_range (1.08s)
            logic.go:1652: 
                 
                testdata/delete_range:14: SELECT operation, message FROM [SHOW KV TRACE FOR SESSION]
                WHERE message LIKE '%DelRange%' OR message LIKE '%sending batch%'
                expected:
                    dist sender send  r26: sending batch 1 Get to (n1,s1):1
                    flow              DelRange /Table/53/1 - /Table/53/2
                    dist sender send  r28: sending batch 1 DelRng to (n1,s1):1
                    flow              DelRange /Table/53/1/601/0 - /Table/53/2
                    dist sender send  r28: sending batch 1 DelRng to (n1,s1):1
                    dist sender send  r28: sending batch 1 EndTxn to (n1,s1):1
                    
                but found (query options: "") :
                    flow              DelRange /Table/53/1 - /Table/53/2
                    dist sender send  r28: sending batch 1 DelRng to (n1,s1):1
                    flow              DelRange /Table/53/1/601/0 - /Table/53/2
                    dist sender send  r28: sending batch 1 DelRng to (n1,s1):1
                    dist sender send  r28: sending batch 1 EndTxn to (n1,s1):1

**Comment by yuzefovich** [comment]
I've seen this failure on quite a few of my builds (e.g. https://teamcity.cockroachdb.com/viewLog.html?buildId=1702259&buildTypeId=Cockroach_UnitTests), and I would guess my code changes should not affect this test.

**Comment by nvanbenschoten** [comment]
This test was disabled by https://github.com/cockroachdb/cockroach/pull/43238.

**Comment by jordanlewis** [comment]
@knz and @andreimatei, is it important to this test to include EndTxn from dist sender send? Can we remove those lines and just assert that SQL generates the two DelRange commands?

**Comment by andreimatei** [comment]
I don't know what's important and what's not.

**Comment by nvanbenschoten** [comment]
> is it important to this test to include EndTxn from dist sender send?

I think it's very important to include the EndTxn. One of the larger questions we like to ask with these tracing tests is which statements can run as 1PC txns and which need to send their EndTxn request in a separate batch. See [`testdata/autocommit`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/opt/exec/execbuilder/testdata/autocommit) for an example of this.
