### ISSUE TITLE
pg_type incompatible with jdbc driver

### ISSUE THREAD

**Issue by marekjelen** [cockroachdb/cockroach#42568]
**Describe the problem**

PostgreSQL JDBC driver fails to interpret types in the `pg_catalog` schema.

**To Reproduce**

```shell
if [ ! -f cockroach ]; then
  curl https://binaries.cockroachdb.com/cockroach-v19.2.1.darwin-10.9-amd64.tgz | tar -xJ
  mv cockroach-*/cockroach cockroach
  rmdir cockroach-*
fi

./cockroach start \
--insecure \
--store=cockroach-data \
--listen-addr=localhost:26257 \
--http-addr=localhost:9081
```

```sql
CREATE DATABASE sample;
```

```java
ResultSet rs = this.dataSource.getConnection().prepareStatement("SELECT * FROM pg_catalog.pg_type;").executeQuery();
while(rs.next()) {
    this.logger.info("Type: {} is {}", rs.getObject("typname"), rs.getObject("typinput"));
}
```

```
org.postgresql.util.PSQLException: Bad value for type long : numeric_in
```

**Expected behavior**

Should print Type: `some name` is `numeric_in`

**Additional data / screenshots**

As well it's possible to see the problem when connected to the database in IntelliJ with the Database plug-in and running the same query. That is `42.2.5` version of the driver.

<img width="1226" alt="screen" src="https://user-images.githubusercontent.com/156068/69163058-e264b880-0aed-11ea-8d3b-10171cd52f88.png">

**Environment:**

 - CCL v19.2.1 @ 2019/11/18 23:17:47 (go1.12.12)
 - macOS
 - OpenJ9 11 with PostgreSQL JDBC driver 42.2.8

**Additional context**

Root failure was JRuby (Ruby on Rails) failing to gather required data.

**Comment by marekjelen** [comment]
Forgot to mention, versions `19.2.0` and `19.1.5` have exactly the same problem.

**Comment by jordanlewis** [comment]
Thanks for the report! @apantel would you be able to take a look at this one? See if you can reproduce it first, then we can talk about how this can be fixed.

**Comment by apantel** [comment]
I can confirm that in my environment, the `typinput` and `typoutput` columns do not display in IntelliJ.

**Comment by apantel** [comment]
Looks like the underlying issue is that some columns in pg_type have the wrong type.
