### ISSUE TITLE
CLI/UI: operator-provided "friendly node name" for display purposes.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#42589]
Most lists of nodes (Admin UI or CLI) show two unique fields for each node:
- **Node ID**: automatically generated at join-time and not operator customizable
- **Address**: based on the `--listen-addr`. When not specified, this might be an IP address. When specified, it must still be a valid DNS name or IP address for this node.

Example for a 6 node cluster:
![node_list](https://user-images.githubusercontent.com/5901480/69241900-07b1ff00-0ba0-11ea-8854-0da54172d09c.png)

There are two regions with three nodes each. We can partially tell from the IP addresses (subnets are different), but otherwise have no easy way to identify each.
Allowing the operator to pass a "friendly node name" at `cockroach start` time would allow names such as: `us-east1-0001`, `us-east1-0002`, etc... even if there is no such DNS name.

This name could be displayed in the Admin UI as well as CLI commands showing lists of nodes, as well as be included in the internal SQL tables.

One question arises: do we want to allow selection of a node based on its name (eg: in `cockroach node decommission us-east1-0001` instead of `cockroach node decommission 1`). If so: some mechanism would need to ensure "friendly name" uniqueness across the cluster. This might not be necessary.

Jira issue: CRDB-6334

**Comment by DuskEagle** [comment]
This would also be nice for Kubernetes deployments which use StatefulSets. The ordering of the pods in the StatefulSet may not match the ordering of the nodes in the AdminUI, which is confusing: 
<img width="282" alt="Screen Shot 2019-11-20 at 3 14 36 PM" src="https://user-images.githubusercontent.com/7644598/69274573-a2164080-0ba8-11ea-8461-ed0dfdb41618.png">
