### ISSUE TITLE
cli: with-load only points traffic at the first node 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#42591]
```./cockroach demo --nodes 9 --with-load```
Version: v20.1.0-alpha.20191118-183-g1c3fce73cd

It appears as if with-load only points traffic at the first node:
![image](https://user-images.githubusercontent.com/22278911/69245445-ceb06500-0b74-11ea-9f64-4d164ce60753.png)
But not any of the other nodes:
![image](https://user-images.githubusercontent.com/22278911/69245453-d3751900-0b74-11ea-996f-0b7b3d0e999a.png)

**Comment by awoods187** [comment]
@rohany or @otan for their thoughts

**Comment by otan** [comment]
When I read the code that is definitely accurate but we could change that. Personally not opposed ;)

**Comment by rohany** [comment]
When i was looking into this when using the `--global` flag, it was difficult to have the workload round robin between workers without breaking the interface barriers of the workload objects. Unless something can already do this when given a list of sql urls to connect to...

**Comment by awoods187** [comment]
Without this it makes it hard to show off the benefits of a multi-node cluster. Consider wanting to show off killing a node--if the node didnt have any traffic we can't demo much here.

**Comment by rohany** [comment]
it makes sense. It might be easier in this case -- the issue that I was facing in the global sense was trying to force all europe queries to go to the europe node etc. It could be alot easier to just round robin queries to different nodes without that kind of restriction.

**Comment by awoods187** [comment]
I tested this out today and don't see load on other nodes:
v20.1.0-alpha.20191118-663-gbeb69e089b
![image](https://user-images.githubusercontent.com/22278911/72468954-4c2ad700-37ac-11ea-80a8-f74122522f1c.png)

**Comment by awoods187** [comment]
Turns out I had a problem with my build and after fixing that this behaves as expected

**Comment by otan** [comment]
closable then? :D

**Comment by awoods187** [comment]
opps thought i did
