### ISSUE TITLE
cli: demo with-load appears to only put data on three nodes

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#42592]
```./cockroach demo --nodes 9 --with-load```
Version: v20.1.0-alpha.20191118-183-g1c3fce73cd
demo with-load appears to only put data on three nodes
![image](https://user-images.githubusercontent.com/22278911/69245648-3961a080-0b75-11ea-9adb-c6594d52b92e.png)

**Comment by awoods187** [comment]
cc @rohany or @otan

**Comment by otan** [comment]
I'm kind of thinking this is accurate and represents how it works irl and expected unless we start adding zone configurations to various schemas by default (or make bigger datasets so ranges get spread across more nodes). Wdyt of doing so?

**Comment by rohany** [comment]
^ the movr dataset being loaded right now is pretty miniscule. Using the `--geo-partitioned-replicas` flag will force data to get spread out across all 9 node though.

**Comment by awoods187** [comment]
I think we need to point load at all the nodes a user specifies. We could also increase the load too but I view that as orthogonal.

**Comment by awoods187** [comment]
Tested this out today and it looks great
