### ISSUE TITLE
lint: TestRoachLint (and the roachlint command) must constrain its memory usage

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#42594]
Today running the `TestRoachLint` linter causes the lint process (combined with its `roachlint` child process) to blow up to 12GB of memory usage.

It's not surprising as it loads and parses _all_ the go source files into RAM before running the checkers.

This is problematic in two ways:

- the memory usage will continue to grow with the number of files in the repository. Instead, the code should be re-architected to only operate on a subset of the files at a time.
- the TestRoachLint function calls `roachlint` on the entire repo and only then filters out the generated files. The `roachlint` command should be re-architected to instead take the ignore list as argument and skip those files upfront.

Given that the memory usage is causing the linter process to flake regularly, I am going to skip the test until the `roachlint` command becomes more economical.

**Comment by mjibson** [comment]
I'm fine running this nightly only. The roachlint command uses the lint stuff from the go tools repo and making changes to that is not going to happen. Are you opposed to me just closing this issue and letting roachlint live on in nightly?

**Comment by knz** [comment]
not opposed
