### ISSUE TITLE
cli: Statement page does not load with Cockroach Demo on master

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#42590]
The statement page does not load with Cockroach Demo on master.
Version: v20.1.0-alpha.20191118-183-g1c3fce73cd

```./cockroach demo --nodes 9 --with-load```

![image](https://user-images.githubusercontent.com/22278911/69244467-fdc5d700-0b72-11ea-8ed6-5a35254f64fe.png)

Traffic is served: 
![image](https://user-images.githubusercontent.com/22278911/69244504-0e764d00-0b73-11ea-9efb-d17a0e07e0eb.png)
And the nodes are healthy: 
![image](https://user-images.githubusercontent.com/22278911/69244508-13d39780-0b73-11ea-9881-74c1cbd85f06.png)

**Comment by awoods187** [comment]
@rohany or @otan may know what's going on here

**Comment by rohany** [comment]
thats pretty strange -- this used to work just fine...

**Comment by awoods187** [comment]
I think it was because of this https://github.com/cockroachdb/cockroach/pull/42577#event-2815791937 not anything demo related. I pulled master and built and can see the statements page now.

**Comment by otan** [comment]
Ah closable then :D?

**Comment by awoods187** [comment]
yup--forgot to close
