### ISSUE TITLE
On EXPERIMENTAL CHANGEFEED, ability to easily determine if provided cursor is too old

### ISSUE THREAD

**Issue by cretz** [cockroachdb/cockroach#42604]
Per [this forum post](https://forum.cockroachlabs.com/t/questions-about-experimental-changefeed-for-and-cluster-logical-timestamp/3309), in 19.1 I used the error text "replica GC threshold" to determine a `cursor` provided to `EXPERIMENTAL CHANGEFEED` was too old, however in 19.2 this just shows as "table not exist".

Please provide a way to reliably tell if the provided cursor is too old. Also, ideally I could also know (can even be in the error message) what the oldest allowed cursor is.

Epic CRDB-2365

Jira issue: CRDB-5341

**Comment by ricardocrdb** [comment]
Hey @cretz 

Thanks for creating this issue. I am tagging @danhhz as he had responded to your forum post as well.

**Comment by miretskiy** [comment]
I believe we produce correct error message when cursor is too old.
