### ISSUE TITLE
Consistent, documented resolved-timestamp format for EXPERIMENTAL CHANGEFEED

### ISSUE THREAD

**Issue by cretz** [cockroachdb/cockroach#42603]
Per [this forum post](https://forum.cockroachlabs.com/t/questions-about-experimental-changefeed-for-and-cluster-logical-timestamp/3309), I have seen (in 19.1 and I believe 19.2) resolved timestamps come across as both `{ "__crdb__": { "resolved": "someval" }}` and `{ "resolved": "someval" }`. Please strictly define and document the expected resolved timestamp format.

Jira issue: CRDB-5342

**Comment by ricardocrdb** [comment]
Hey @cretz 

As @danhhz had responded to in that forum [post](https://forum.cockroachlabs.com/t/questions-about-experimental-changefeed-for-and-cluster-logical-timestamp/3309/4) after these GH issues were created, I will paste his response here:
```In 19.1, we changed the default format for newly created changefeeds from format=row to format=wrapped. One of these feeds (the one without crdb) was created with a pre 19.1 cluster and still has format=row. If you want them to be the same, you can stop one of them and replace it with a new changefeed that explicitly specifies the other format.```

Let me know if you have any other questions.

**Comment by cretz** [comment]
@ricardocrdb - I request that this be documented please. Receiving "resolved" timestamps is important, so it's only fair that people know what format it comes in. Also, in [the docs](https://www.cockroachlabs.com/docs/stable/changefeed-for.html) I don't see anything about setting `format` to `row` or `wrapped` or anything of the sort, only `json` or `experimental_avro`.

**Comment by danhhz** [comment]
Hey @cretz. My apologies, I misspoke on the forum. It's `envelope=row` vs `envelope=wrapped`. Not `format`, which as you point out switches between avro and json.

@lnhsingh Looks like the `EXPERIMENTAL CHANGEFEED FOR` page documents `row` and `key_only` for `envelope=` and `CREATE CHANGEFEED` documents `wrapped` and `key_only`. All three options work for either, so this seems out of date.

Additionally, we called out in release notes that the default value for `envelope` changed, but given how long running changefeeds are, I can see how that would not be enough. I'm not sure how to best communicate this in our docs, but it seems worthwhile to add it somewhere.

Also cc @rolandcrosby
