### ISSUE TITLE
For EXPERIMENTAL CHANGEFEED, make clear if row is deleted even on key_only envelope

### ISSUE THREAD

**Issue by cretz** [cockroachdb/cockroach#42602]
Per a [forum post](https://forum.cockroachlabs.com/t/questions-about-experimental-changefeed-for-and-cluster-logical-timestamp/3309), when I use a normal envelope on an `EXPERIMENTAL CHANGEFEED`, I can use the absence of `after` to know it is a delete. But on a `key_only` envelope, I have no way to determine whether the record is a delete or not. Consider some approach to make whether it is a deletion visible.

Jira issue: CRDB-5343

**Comment by ricardocrdb** [comment]
Hey @cretz 

Thanks for creating the issue as requested. As the forum [post](https://forum.cockroachlabs.com/t/questions-about-experimental-changefeed-for-and-cluster-logical-timestamp/3309/4) from @danhhz requested, please include an example of how you would like it to look, and we can look into this further.

**Comment by cretz** [comment]
In the forum [post](https://forum.cockroachlabs.com/t/questions-about-experimental-changefeed-for-and-cluster-logical-timestamp/3309/5) I said:

> I think a deleted boolean in the JSON would be fine.

Here's the example:

```json
{ "deleted": true }
```

**Comment by ricardocrdb** [comment]
cc @rolandcrosby

**Comment by cretz** [comment]
Still relevant IMO
