### ISSUE TITLE
V19.2.0 arm64 compilation ended with errors

### ISSUE THREAD

**Issue by giminni** [cockroachdb/cockroach#42610]
**Is your feature request related to a problem? Please describe.**
Could not compile cockroach 19.2.0 for arm64 targets, due to different errors, like missing the right nodejs version and missing files in the compile path

**Describe the solution you'd like**
A clear description what is needed (nodejs was missing) and the minimum required version

**Additional context**
Here what I corrected to get a successful binary

- Set the right architecture
- Added missing arm64 crc32c file

```diff
--- CMakeLists.txt.org  2019-11-19 20:59:48.457978829 +0000
+++ CMakeLists.txt      2019-11-20 07:11:11.947220073 +0000
@@ -214,7 +214,7 @@
     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /arch:AVX2")
   else()
     if(NOT HAVE_POWER8)
-      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=native")
+      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=armv8-a+crc+crypto")
     endif()
   endif()
 endif()
@@ -694,6 +694,9 @@
   list(APPEND SOURCES
     util/crc32c_ppc.c
     util/crc32c_ppc_asm.S)
+else()
+    list(APPEND SOURCES
+    util/crc32c_arm64.cc)
 endif(HAVE_POWER8)

 if(WIN32)
 ```

- Hided two functions that are useless in an arm64 context.

```difff
--- crc32c.cc.org       2019-11-19 21:51:47.492962794 +0000
+++ crc32c.cc   2019-11-19 22:12:11.155534634 +0000
@@ -409,6 +409,7 @@
 // Detect if SS42 or not.
 #ifndef HAVE_POWER8

+#ifndef HAVE_ARM64_CRC
 static bool isSSE42() {
 #if defined(__GNUC__) && defined(__x86_64__) && !defined(IOS_CROSS_COMPILE)
   uint32_t c_;
@@ -422,7 +423,9 @@
   return false;
 #endif
 }
+#endif

+#ifndef HAVE_ARM64_CRC
 static bool isPCLMULQDQ() {
 #ifndef HAVE_SSE42
 // in build_detect_platform we set this macro when both SSE42 and PCLMULQDQ are
@@ -440,6 +443,7 @@
   return false;
 #endif
 }
+#endif // HAVE_ARM64_CRC

 #endif  // HAVE_POWER8
```

**Comment by JorritPosthuma** [comment]
Hi! I also tried building for arm64, but without luck. Would it be possible for you to share your binary? Or did you possibly publish it as docker image?

**Comment by alexfromapex** [comment]
Yeah it would be super helpful if there is even an unstable ARM64 binary published so we could package and use it along with the Dockerfile in this repo

**Comment by jrote1** [comment]
@alexfromapex I do have regular docker builds that target amd64 and arm64 if you are interested?

**Comment by JorritPosthuma** [comment]
Sounds awesome!

**Comment by jrote1** [comment]
@JorritPosthuma You can find the image here https://hub.docker.com/r/multiarchbuilds/cockroach
The build source is included in the description, hopefully we can get an official arm64 build of cockroachdb in the future :)

**Comment by dt** [comment]
We removed RocksDB after v20.2 so this file is no longer an issue. Cockroach currently builds without errors on arm64 (though there's some crashes in snappy compression that should be fixed shortly.)
