### ISSUE TITLE
storage: Investigate teeing engine discrepancies around iterators/MVCCGet when some tests are run as a package

### ISSUE THREAD

**Issue by itsbilal** [cockroachdb/cockroach#42656]
When run with `COCKROACH_STORAGE_ENGINE=pebble+rocksdb make test PKG=./pkg/storage/...`, these tests fail with mismatching MVCCGet values and/or iterator validities:

1. `TestTxnWaitQueueTxnSilentlyCompletes`
2. `TestCompactorThresholds/single_suggestion_over_absolute_threshold`

However, when running those tests on their own (eg. `COCKROACH_STORAGE_ENGINE=pebble+rocksdb make test PKG=./pkg/storage/... TESTS=TestTxnWaitQueueTxnSilentlyCompletes`), they succeed. Note that both these tests are run on disk, rather than with an in-mem file system, so this is probably emblematic of a discrepancy in how each engine cleans its directory up after a test.

**Comment by itsbilal** [comment]
Here's a list of all failing / flakey tests with the teeing engine (under the `storage` package):

1. `TestTxnWaitQueueTxnSilentlyCompletes`
2. `TestCompactorThresholds`
3. `TestStoreRangeMergeRaftSnapshot`
4. `TestConcurrentRaftSnapshots`

The latter two were failing due to mismatching values in MVCCGet, which on closer inspection, is okay as long as it's transient because the read is happening inside a `SucceedsSoon` along with a parallel snapshot merge / apply. Adding a time.Sleep right before the read makes the values consistent again, and the tests always pass.

The former two fail in a very similar way: they were iterating on the LocalStoreSuggestedCompaction keys right after a compaction suggestion is made, in a separate goroutine. Sometimes the values at those keys are consistent by the time the read happens, other times they're not, and cause the `Iterate` to fatal out too soon.

We could update the teeing engine to lock out all read operations while a write or batch commit is happening.  Otherwise, readers are likely to fatal out if they read a key while a write has been committed to one engine but not the other. Either way this problem is specific to the teeing engine and doesn't indicate any differences in the underlying engines.

**Comment by petermattis** [comment]
@itsbilal Should these tests be skipped if the `teeing` engine is in use? It would be unfortunate to debug the failures in these tests again/
