### ISSUE TITLE
sql: creating view over a system table in insufficient to allow less-permissioned users to view it

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/cockroach#42663]
**Describe the problem**

Currently, to view the `crdb_internal.node_statement_statistics` virtual table, the query must be issued by a root user or a user with an admin role.

A proposed workaround is to create a view on a non-system database and grant select priveledges for a sql user to query the view.

Currently, we check permissions when populating the table instead of when referencing it, which in turn throws this error: `pq: only users with the admin role are allowed to access application statistics`. 

**To Reproduce**

As root user: 
```
create view defaultdb.test_view as select node_id,key from crdb_internal.node_statement_statistics;

create user matt;

grant select on defaultdb.test_view to matt;
```

As sql user matt:
```
matt@:26257/defaultdb> select * from defaultdb.test_view;
pq: only users with the admin role are allowed to access application statistics
```

**Expected behavior**
Ability to use the view from a non-root user / non admin role.

**Environment:**
 - CockroachDB version 19.2.0
 - Client app: cockroach sql

**Additional context**

can’t use views as a workaround to expose assorted system table data

Jira issue: CRDB-5334

**Comment by mattcrdb** [comment]
cc @justinj @RaduBerinde @solongordon

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4094](https://cockroachdb.zendesk.com/agent/tickets/4094) has been linked to this issue.
