### ISSUE TITLE
security: rework security settings

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#4269]
Proposal:
* run insecure by default
* replace `--insecure` flag with something along the lines of `--security-mode`
* replace `--certs` flag with per-file flags (eg: `--ca-cert`, `--ca-key`, etc... check other system for common naming)
* put warnings in logs and on the UI when running in insecure mode

This will impact the docs quite a bit. We'll probably want a "how to enable secure mode" guide.

**Comment by bdarnell** [comment]
I think we should continue to push for secure mode by default. Maybe we can't get a reasonable amount of scripting for certificates in place by the beta and have to recommend insecure mode, but I'd rather recommend that all beta users run with `--insecure` than be insecure by default.

**Comment by petermattis** [comment]
Pushing for secure by default seems like a good way to frustrate initial users, especially with our current setup. Setting up certs is opaque and the errors are non-obvious. I think we can fix this, but perhaps not by beta. The thought behind this issue is to make the initial experience pleasant instead of frustrating. We're already ahead of the curve by having a secure mode that can be enabled.

**Comment by bdarnell** [comment]
I agree that pushing initial beta users to run in secure mode will be frustrating. I'm saying that I would prefer to ask all beta users to turn on the `--insecure` flag than to change the default. This will emphasize the temporary nature of the insecure state and will avoid complications at the point where we decide to flip the default to secure (if the `--insecure` is explicit then each user can switch to secure mode based on their own readiness).

**Comment by tschottdorf** [comment]
I agree with Ben.

**Comment by mberhault** [comment]
I do too, but I see Peter's point. Especially with sufficient warnings (especially in the admin UI), it probably isn't too risky.

Either way, the main work I want to do is rework the flags (eg: `--security-mode` and the certs file). The default value can easily be changed.

**Comment by tschottdorf** [comment]
I know you've looked at this far more than I have, but that seems like
giving up before it started. Ben's suggestion has the same outcome but
doesn't throw in the towel right away.

**Comment by JackKrupansky** [comment]
Why not link the issue of default security mode to dev vs. production - if the cluster is being run in production mode, require secure by default, while in dev mode secure is opt-in?

IOW, the concept that CockroachDB is a secure database by default is a strong selling point, as is... convenience of development.

**Comment by spencerkimball** [comment]
A conversation with a recent beta customer indicated that additional security is not desired, as they're satisfied with how the database machines are secured through the network topology. I'm not going to argue that's sound, but it seems prejudicial for us to insist that you're doing something wrong by requiring  they opt out using `--insecure`, which currently has the following explanation: `Run over plain HTTP. WARNING: this is strongly discouraged.`

I think our goal of _strongly_ discouraging insecure production deployments errs on the side of being too prescriptive. A better goal would be something like: "provide a strong, secure deployment story which is also the simplest possible (for a distributed database)."

When you couple this with making the out-of-the-box deployment story simpler by not requiring the user to think about security, I'm in favor of making securing the cluster a follow on step which is pursued when the operator is ready.

Warning in the logs and having a reasonable banner on the admin UI would help guide the user to secure their cluster when they're ready.

**Comment by bdarnell** [comment]
I'm fine with removing the pejorative language around the `--insecure` option, but I still want it to be an explicit choice on the part of the operator rather than a default.

**Comment by petermattis** [comment]
From an in-person discussion with Spencer and Ben we reached the following compromise:

* If `cockroach start` is specified then the server only listens on localhost and the server starts in insecure mode. This allows a developer running a local instance to start cockroach with no additional argument.
* If `cockroach start --insecure` is specified the server listens on all addresses and starts in insecure mode. This forces a production cockroach cluster composed of multiple nodes to explicitly specify `--insecure`.
* If `cockroach start --cert-file` is specified the server listens on all addresses and starts in secure mode.

**Comment by JackKrupansky** [comment]
I'd be more comfortable renaming --insecure to --nosecurity. Seems less
judgmental.

Having --secure as an alias for --cert-file also, for symmetry.


-- Jack Krupansky

**Comment by tschottdorf** [comment]
@petermattis I'm not really sure what that means for anything inbetween. If I don't specify `cert-file` nor `insecure` but I provide a `host`, then I get insecure on that host?

**Comment by petermattis** [comment]
I think `--host` without `--insecure` (or the `--{cert,key}-file` flags) should be an error and the user should be asked to specify `--insecure`. The idea is that running an insecure production cluster should require the user to be explicit.

**Comment by tschottdorf** [comment]
SGTM

**Comment by petermattis** [comment]
@mberhault What's the status of this? Would be good to get this done soon as it affects documentation.

**Comment by petermattis** [comment]
@mberhault Ping?

**Comment by mberhault** [comment]
yup. working on it. should be done soonish.

**Comment by mberhault** [comment]
Grr! this wasn't supposed to get closed.
`--certs` is gone, but I still need to address the default logic mentioned above. Re-opening.

**Comment by mberhault** [comment]
Now that I'm moving to changing the value of `--insecure` based on other flags, I'm thinking we don't even need it anymore.
The certificate and key flags don't have defaults, meaning secure mode can't work without those flags specified.
Instead of having `--insecure` change based on the `--host` and `--cert` flags, why don't we just remove it entirely and used whether certs are specified as a hint?

Pro:
* fewer flags. specifying certs automatically enables secure mode
* we can inherently use multiple modes: ca-verification only vs full ca+client certs

Cons:
* `--insecure` is a nice big switch, especially on the client side. you can set it to false and let the error messages tell you what else you're missing
* inferring the scheme (`https vs http` and `grpcs vs grpc`) from `--cert` might be a bit of a leap

**Comment by petermattis** [comment]
Recall our compromise: we want `--insecure` or cert flags to be required in order to listen on an external address. If the user starts without `--insecure` or cert flags we would default to insecure but only listen on localhost. This meant that users have to explicitly opt-in for insecure production deployments. If you drop the `--insecure` flag completely I don't see how to achieve that.

**Comment by mberhault** [comment]
I do see that, but as soon as `insecure == false`, you must specify all cert-related flags, which means that we'll have `--cert, --key, --ca-cert` based on the value on `--insecure`, but `--insecure` itself will have a different default based on the value of `--host`. This is just incredibly confusing.
Rather, setting the security mode from just one flag (that has to be set anyway) seems much clearer.

**Comment by bdarnell** [comment]
The `--insecure` flag is deliberately redundant: the user must explicitly opt in to insecure mode for non-localhost servers; we don't want to infer intent to use insecure mode from the absence of the cert flags. Don't think of these flags as changing each other's defaults: the use of TLS (or not) is always governed by the cert flags, not the `--insecure` flag. The only thing `--insecure` does is bypass the safety check which would otherwise prevent starting up with non-localhost and no TLS. Would renaming `--insecure` to `--allow-insecure` make things less confusing?

**Comment by jseldess** [comment]
Docs updated with already implemented cert changes (everything but the change to `--insecure`): cockroachdb/docs#117.

**Comment by jseldess** [comment]
Docs have been updated.
