### ISSUE TITLE
opt: limit not being applied to query with UNIQUE column constraint

### ISSUE THREAD

**Issue by roncrdb** [cockroachdb/cockroach#42731]
**Describe the problem**

When running the following query: 

`select * from t1 where unique_value is null and notnull_value = 2000  limit 1;` 

Two rows are returned instead of one. 

Please describe the issue you observed, and any steps we can take to reproduce it:

```
create table t1 (id serial primary key, unique_value int UNIQUE, notnull_value int not null);
CREATE TABLE

Time: 2.515ms

root@127.0.0.1:51895/movr> insert into t1(unique_value, notnull_value) VALUES
(1, 1000),
(2, 1500),
(3, 1500),
(NULL, 2000),
(NULL, 2000),
(NULL, 2500),
(NULL, 3000);
INSERT 7

Time: 3.785ms

root@127.0.0.1:51895/movr> select * from t1 where unique_value is null and notnull_value = 2000  limit 1;
          id         | unique_value | notnull_value
+--------------------+--------------+---------------+
  506665746730221569 |         NULL |          2000
  506665746730254337 |         NULL |          2000
(2 rows)

Time: 1.705ms

root@127.0.0.1:51895/movr> explain select * from t1 where unique_value is null and notnull_value = 2000  limit 1;
       tree       |    field    |      description
+-----------------+-------------+------------------------+
                  | distributed | false
                  | vectorized  | false
  filter          |             |
   │              | filter      | notnull_value = 2000
   └── index-join |             |
        │         | table       | t1@primary
        └── scan  |             |
                  | table       | t1@t1_unique_value_key
                  | spans       | /NULL-/!NULL
(9 rows)
```

**Expected behavior**
The limit should only return 1 row. 

**Additional data / screenshots**
Seems to be related to the fact that the unique_value column has a UNIQUE constraint on it and values are NULL for the `notnull_value` column

**Environment:**
 - CockroachDB version 19.2.0

**Additional context**
Issue was reported by a user in production. 

CC: @awoods187

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4136](https://cockroachdb.zendesk.com/agent/tickets/4136) has been linked to this issue.

**Comment by RaduBerinde** [comment]
```
norm
select * from t1 where unique_value is null and notnull_value = 2000 limit 1;
----
select
 ├── columns: id:1(int!null) unique_value:2(int) notnull_value:3(int!null)
 ├── cardinality: [0 - 1]
 ├── key: (1)
 ├── fd: ()-->(2,3), (2)~~>(1)
 ├── scan t1
 │    ├── columns: id:1(int!null) unique_value:2(int) notnull_value:3(int!null)
 │    ├── key: (1)
 │    └── fd: (1)-->(2,3), (2)~~>(1,3)
 └── filters
      ├── unique_value IS NULL [type=bool, outer=(2), constraints=(/2: [/NULL - /NULL]; tight), fd=()-->(2)]
      └── notnull_value = 2000 [type=bool, outer=(3), constraints=(/3: [/2000 - /2000]; tight), fd=()-->(3)]                            
```

The cardinality of 1 comes from calling `Constraint.CalculateMaxResults` on the second constraint. I don't get this code - it seems to assume that the columns in the constraint are always a unique index?

CC @rytaft

**Comment by RaduBerinde** [comment]
Oh. I see, the function is supposed to be called only when the constraint is a lax key.
In this case the FD is `key(1); ()-->(2,3), (2)~~>(1)   cols: (3)`.
And for this FD `ColsAreLaxKey(3)` returns true but that is not correct. CC @andy-kimball

**Comment by RaduBerinde** [comment]
I think this assumption here is not right:
https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/opt/props/func_dep.go#L1374
