### ISSUE TITLE
Handle default timestamps during IMPORT

### ISSUE THREAD

**Issue by randmark** [cockroachdb/cockroach#42744]
**Describe the problem**

When using the IMPORT command, it should be possible to set a timestamp so the time of import can be set. 

**To Reproduce**

The following invocation does not work. If there's no column added, the import fails, and if a blank column is added to the import file, a NULL is imported rather than triggering the default.

IMPORT TABLE PREFERENCES 
(
    id string PRIMARY KEY,
    info JSONB,
    last_updated TIMESTAMP DEFAULT now()
)
CSV DATA ('nodelocal:///data.csv')

**Expected behavior**
There should be a way to set a timestamp of the time that the line of data was imported.

**Comment by dt** [comment]
Hi @randmark! Thanks for taking the time to file this! This feature is currently being tracked over on #48253 so I'm going to close this one, but please feel free to follow that issue and/or add a 👍 to reflect your interest or comment with any detail you feel is missing.

Thanks!
