### ISSUE TITLE
webui: network diagnostic page can be confusing

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#42788]
We met with a customer today and they weren't sure how to read the network diagnostic page. This was troubling because they have a one-way network partition that they are attempting to debug. They thought it should be read top-down rather than left to right. 

In the short-term, can we provide more information on how to read these charts on the page itself? 
I know larger redesigns are in progress for the long-term that should take this feedback into account.

cc @BramGruneir & @piyush-singh

**Comment by piyush-singh** [comment]
cc @Annebirzin this is currently being worked on. Was the confusion about whether the top or the left side of the matrix is from/to? Anne - we might want to add a small note in the designs about which side is the origin vs destination.
