### ISSUE TITLE
Decommissioned nodes should expire after a period of time

### ISSUE THREAD

**Issue by keith-mcclellan** [cockroachdb/cockroach#42823]
Clusters with more elastic use-cases suffer from decommissioned node metadata build-up.  A feature that automatically removes metadata/nodes that were gracefully decommissioned after a set period of time (say, 7 days) would enable a better administrator experience.

**Comment by namibj** [comment]
Compacting down to a node-id blacklist with no further context should be enough, I guess? Because the storage for that is miniscule, and it should still prevent rejoin errors while not setting a fixed time limit for how long nodes can be dead before they can't re-join anymore.
