### ISSUE TITLE
IO error while large query

### ISSUE THREAD

**Issue by logart** [cockroachdb/cockroach#42856]
**Describe the problem**

When I do select I receive an error 
[XX000] ERROR: IO error: No space left on deviceWhile appending to file: /cockroach/cockroach-data/cockroach-temp631922860/006573.sst: No space left on device

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Create table with some structure and 331380 records in it
2. SELECT * FROM articles WHERE at > :after ORDER BY at ASC LIMIT 1000 OFFSET 5000;
3. See error

**Expected behavior**
I would like to somehow estimate how much space I need since now 40% of the storage is empty.

**Environment:**
 - CockroachDB version [v19.1.5]
 - Server OS: [alpine in kubernetes]
 - Client app [either spring boot app using java or datagrip by intellij]

Thank you for help.

**Comment by florence-crl** [comment]
Hi @logart,
I am reviewing outstanding issues. I am sorry for the delay in response.

From the error message, this may be a kubernetes problem.

Are you still experiencing this issue? If so, would you be able to send us the logs and the yaml you used to start the cluster so we could investigate further?

Regards,
Florence
Technical Support Engineer

**Comment by logart** [comment]
Thank you for response. This issue is still remain I belive. I've foxed it by changing the approach I query the db. I will send you yaml soon. Thank you.

**Comment by jordanlewis** [comment]
Closing due to age.
