### ISSUE TITLE
adminui: bad textbox for typing a metric name in the Custom Chart page 

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#42891]
It only shows a few characters and pushes the other off-screen although there's plenty space.
![Screen Shot 2019-12-02 at 2 31 16 PM](https://user-images.githubusercontent.com/377201/69988963-a891aa00-1510-11ea-84ef-82572a7c3fd1.png)

**Comment by andreimatei** [comment]
cc @dhartunian

**Comment by dhartunian** [comment]
# Testing requirements

* Screenshot in PR
