### ISSUE TITLE
sql: allow setting cluster settings from a subquery

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#42896]
When looking to automate upgrading, this is the first thing that comes to mind.

Sadly it doesn't work.

```
> SET CLUSTER SETTING cluster.preserve_downgrade_option = (select version from [show cluster setting version]);
pq: subqueries are not allowed in SET CLUSTER SETTING
```

But I don't see any reason why setting cluster settings should be not be able to have a subquery.

Jira issue: CRDB-5313

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4186](https://cockroachdb.zendesk.com/agent/tickets/4186) has been linked to this issue.

**Comment by RaduBerinde** [comment]
To support relational subqueries, the expression needs a specific optimizer operator (as opposed to using the "opaque" operator). There's some work (and code cruft) associated with each such operator, so we'd rather not add all of them without a good reason.

**Comment by RaduBerinde** [comment]
Copying the description of #48010 here:

This was possible in CockroachDB 2.x and 19.1:

```
> SET application_name = (SELECT 'a' || 'b');
SET
> SHOW  application_name;
  application_name
+------------------+
  ab
(1 row)
```

In CockroachDB 19.2, it causes an internal error:

```
pq: internal error: invalid index 1 for "(SELECT 'a' || 'b')"
/data/home/kena/src/go-c192/src/github.com/cockroachdb/cockroach/pkg/sql/subquery.go:47: EvalSubquery()
/data/home/kena/src/go-c192/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:4160: Eval()
```

In CockroachDB 20.1, it's been transformed into a typing error:

```
ERROR: invalid value for parameter "application_name": "(SELECT 'a' || 'b')"
SQLSTATE: 22023
DETAIL: subqueries are not allowed in SET
```

I don't think there's a very good reason to prevent the behavior.

### Desired resolution

- reinstate the behavior in 20.1
- backport the fix to 19.2
- mark the regression as fixed

(found by @dbist via #42909 )

**Comment by jseldess** [comment]
Documented in https://github.com/cockroachdb/docs/pull/7311.

**Comment by knz** [comment]
Generalized statement:  #95266
