### ISSUE TITLE
sql: Randomized round-trip testing of SHOW CREATE TABLE

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#42917]
When new SQL Schema features are introduced, one common mistake is to forget to include them in schema introspection output, in particular `SHOW CREATE TABLE` (and its internal counterpart that separates index/fk creation into additional ALTER statements, which is used by `dump`). The current setup is prone to such mistakes, since we can only catch what we're written tests for.

We should really have a test that can catch these kinds of things _when the new feature is introduced_ instead of hoping that the implementer or reviewer happens to remember or that someone happens to notice. 

For `SHOW CREATE TABLE` and its internal counterparts, maybe something along the lines of a) sqlsmith generate a random create statement from the grammar (maybe with a little help for be semantically correct w.r.t FKs), b) create a copy of that table using SHOW CREATE TABLE and then c) verify that the table descriptor for the original matches the copy (after blanking ID and timestamps).

**Comment by jordanlewis** [comment]
@mjibson am I crazy - didn't we already add something just like this? There's some kind of round trip parsing test, right? Maybe it doesn't go all the way deep down into table descriptors and back.

**Comment by mjibson** [comment]
Comments appear as separate statements (i.e., not in the `CREATE TABLE`) and thus don't work in the model that sqlsmith (or rsg, which would be a better fit here since it crawls the grammar). And, yes, we already do round-trip verify all statements that RSG produces, which includes a bunch of table mutations.

**Comment by ajwerner** [comment]
I think this call for randomized testing is valid. However, dump is no longer relevant. Schema would like to invest more in randomized testing, but this issue does not seem likely to be helpful to us in planning or execution of that vision. Closing.
