### ISSUE TITLE
ui: Update node list component

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#42923]
We should update our node list component in the Admin UI to match the node list style that we will use going forward across the Admin UI and CockroachCloud. For the Admin UI specifically, this is also an opportunity to revisit the columns we show in the node list. 

This should also address #32400 as the new component is a treetable with nodes grouped by their locality hierarchy.

**Comment by piyush-singh** [comment]
Design Link: https://zpl.io/aBpdB8k

**Comment by dhartunian** [comment]
Closed by #43552
