### ISSUE TITLE
pgwire invalid empty array decoding

### ISSUE THREAD

**Issue by karlseguin** [cockroachdb/cockroach#42942]
**Describe the problem**

PostgreSQL will happily decode a 0-dimensional array which does not have a dimsize and lower bound (the last 2 bytes of the array header). For example, `[0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 23]` is acceptable for an empty int4 array in postgresql. However, this fails in CockroachDB (you get an EOF error).

I couldn't figure out how to write a test to send arbitrary bytes, but I'm pretty sure the error happens because of the last two fields in the `hdr` structure and the subsequent call to `binary.Read` https://github.com/cockroachdb/cockroach/blob/2c3ade727e6db5f8eee0d6dfbe53e237d3e2437e/pkg/sql/pgwire/pgwirebase/encoding.go#L741

The solution would be to remove these two fields, and only read them if Ndims > 0

**To Reproduce**

You need a driver that generates the concise array format. I ran into this with the elixir Postgrex driver (my PR has been accepted to "fix" this on the driver side). But using a version that doesn't have this fix (v0.15.2 or before), `Postgrex.query!(pid, "select $1", [[]])` causes the error.

**Expected behavior**
Error: Get an EOF error
Expected: Parser to be consistent with postgres 

**Additional context**
Any driver that encodes an empty array using a concise binary format will be unusable

Postgrex workaround: https://github.com/elixir-ecto/postgrex/commit/d887ed813f437aa630ef9be0d047a0f20ecdd95e

**Comment by jordanlewis** [comment]
Thanks for the report! We'll fix this.
