### ISSUE TITLE
cli: sql shell prints last error, instead of first error (or first result) for a batch

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#4294]
```
root@:15432> begin transaction priority low; select * from t;insert into t(a) values (1); select * from t;
```

CLI prints something like "transaction already aborted". It should print "table t doesn't exist".
Ideally, it would print all the results + errors.

**Comment by tamird** [comment]
Possibly related to https://github.com/cockroachdb/pq/commit/de04a24934fb5fa9e4981a8246a8feb312eeb270
