### ISSUE TITLE
cli:cockroach sql command should have `-f` option to pass sql file

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#42955]
**Is your feature request related to a problem? Please describe.**
today, I only see an option of passing a sql command to cockroach sql with --execute flag. I'd like to see an option to pass a file instead. Lack of this ability forces one to do bash trickery to pass a file like so `cockroach sql --insecure --host=localhost:26257 --database="tabular_import" --execute="$(< import_statement.sql)`

**Describe the solution you'd like**
a more convenient solution is to see an option to pass a file with a switch like `-f`

**Describe alternatives you've considered**

**Additional context**

**Comment by knz** [comment]
@dbist I don't get it - do you know you can do `cockroach sql <import_statement.sql` 

what's wrong with this option?

**Comment by dbist** [comment]
@knz just validated and you're obviously correct, `cockroach sql --url 'postgresql://root@localhost:26257?sslcert=certs%2Fclient.root.crt&sslkey=certs%2Fclient.root.key&sslmode=verify-full&sslrootcert=certs%2Fca.crt' < import_statement.sql`. I think the fact this information is not readily available calls for a documentation update.

**Comment by knz** [comment]
Reopening as discussed: the `-f` flag can be provided for convenience.

**Comment by dbist** [comment]
even though ability to pass statement via unix file redirection is available and leveraging `psql` is also possible, these approaches are not widely understood and don't fall in line with UX. I propose to add a command helper `-f` and `--file` similar to [psql](https://www.postgresql.org/docs/9.3/app-psql.html) approach to add to the current `cockroach sql` arsenal of flags.
