### ISSUE TITLE
cli: allow the ability to specify which nodes (by number) are added to the debug zip

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#42953]
`cockroach debug zip` should have a parameter that accepts a selection of node numbers, similar to how roachprod works right now, and only construct the debug.zip from those. 

e.g.:

```bash
./cockroach debug zip --nodes=1,5,8
./cockroach debug zip --nodes=1-5,8-10,12
./cockroach debug zip --nodes=9
```

I'm not sure if this should be on the cli team, so please triage appropriately.

**Comment by mattcrdb** [comment]
This would benefit us in certain situations where node addresses aren't up to date and the debug process is hanging or if there is a failed node. We would have the ability to skip certain nodes.
