### ISSUE TITLE
ui: endpoints for SQL Queries needed by the frontend

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#4298]
Will fix #3348 and circumvent #3321

Here's the current list of SQL queries I use/intend to use in the admin UI. I've provided some example JSON responses that would be more convenient to use than just a list of rows.

The api should be versioned so that we can change it up later.

**Show all databases:**
```SHOW DATABASES;```

**Show permissions on a database:**
```SHOW GRANTS ON DATABASE <database>;```

**Show tables in a database:**
```SHOW TABLES FROM <database>;```

**See a table's columns, indexes, and permissions:**
```SHOW COLUMNS FROM <table>```
```SHOW INDEX FROM <table>```
```SHOW GRANTS ON TABLE <table>;```

**Show all users:**
```SELECT * FROM SYSTEM.USERS```

**Select/insert/update data stored for/by the Admin UI for a specific user**
```SELECT * FROM SYSTEM.UI WHERE username=<username>```
```INSERT INTO SYSTEM.UI (username, <key list>) VALUES (<username>, <value list>)```
```UPDATE SYSTEM.UI SET <key>=<value>... WHERE username=<username>```

**View rangelog/eventlog entries, sorted by timestamp and filtered by type/target**
```SELECT * FROM SYSTEM.RANGELOG [WHERE eventType=<type>] ORDER BY timestamp [ASC|DESC]```
```SELECT * FROM SYSTEM.EVENTLOG [WHERE eventType=<type> AND targetID=<target>] ORDER BY timestamp [ASC|DESC]```

**Comment by maxlang** [comment]
For the API, I think we might want something like the following to begin with

GET
``` /v1/databases ```
``` /v1/databases/:database/(tables|grants) ```
``` /v1/databases/:database/tables/:table/(columns|indexes|grants) ```
``` /v1/users ```
``` /v1/events?type=:type&target=:target&order=(ASC|DESC) ```
``` /v1/admin ```

POST
``` /v1/admin -d '{<key>:<value>}' ```

When we get results back we can generally return results as an array of JSON objects where the column names are keys and the rows are values.

```
+----------+--------+----------------+
| Database |  User  |   Privileges   |
+----------+--------+----------------+
| "system" | "root" | "GRANT,SELECT" |
+----------+--------+----------------+
```

might become

```json
[
  {
    "Database": "system",
    "User": "root",
    "Privileges": ["GRANT", "SELECT"],
  }
]
```

**Comment by maxlang** [comment]
For certain endpoints we might want to return a bit more info. For example, the databases endpoint could return permissions and a list of tables in addition to just the database name.

**Comment by cuongdo** [comment]
Are there specific endpoints you'd like to see first? I'd like to implement ~3 of them first and get feedback on the API before implementing the rest.

**Comment by maxlang** [comment]
@cuongdo nothing specific first. Probably easiest to start with ```/databases```
