### ISSUE TITLE
`system.namespace` followup work for 20.2

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#42997]
In 20.1, the `system.namespace` table was migrated from a 2 column primary key (parentID, name) to a 3 column primary key (parentID, parentSchemaID, name). As CRDB does not support primary key changes currently, this migration involved creating a completely new table outside the `system.config` range and transitioning to using this new table. To ensure `system.namespace` table accesses work correctly in mixed version clusters (19.2/20.1), both the tables coexist in 20.1. This issue tracks the followup work required for 20.2

1. A second migration to copy over entries from `system.namespace_deprecated` to `system.namespace`. This ensures all entries created in mixed version clusters before the cluster version is bumped continue to be accessible in 20.2 once the fallback logic is removed. 
2. `pkg/sql/sqlbase/namespace.go` abstracts all accesses to `system.namespace, including logic to fallback to `system.namespace_deprecated`. There is a long comment at the top of the file explaining these semantics and the reason for them. These accesses should be cleaned up in 20.2.
3. Investigate if settings can be removed from the TableCollection in `pkg/sql/table.go`.

**Comment by lucy-zhang** [comment]
A few updates:

- Table 2 is now `namespace` (again), and table 30 is now `namespace2`, after https://github.com/cockroachdb/cockroach/pull/47173. There's a complication in that clusters bootstrapped on an earlier 20.1 beta or that were upgraded to a beta will have the old `namespace_deprecated` (2) and `namespace` (30) names even when upgraded to 20.1.0+. We have to account for this during the 20.2 migration.
- The original namespace migration had to be moved to run after upgrade finalization (see https://github.com/cockroachdb/cockroach/pull/49099 and related issues), in a way that doesn't guarantee that the migration will have finished by the time the cluster is upgraded to 20.2. So we'll have to do this migration again for 20.2 to ensure it actually gets run, and I believe some of the fallback logic will have to stick around.

**Comment by lucy-zhang** [comment]
SQL Schema intends to attempt this for 21.1. The current thinking is that we'll run the migration for the namespace entries (which already exists) as a startup migration or long-running migration. There's some additional work to get rid of the special cases for name resolution of the namespace table itself, but maybe we can wait for 21.2 for that.

**Comment by ajwerner** [comment]
https://github.com/cockroachdb/cockroach/pull/60647 did a migration.

**Comment by postamar** [comment]
I believe there is no more any such followup work remaining to be done.
