### ISSUE TITLE
sql: Scan with limit scans too much data

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#4299]
Load 100,000 records into a table with sequential IDs.

Run the SQL:

`select id from loadgen.users where id > 10000 limit 1;`

The time it takes to return indicates a lot of data is being scanned as opposed to just the limit of 1.

**Comment by RaduBerinde** [comment]
Even in the easiest case (e.g. single span, no additional filters), it's not easy to use the result count because we don't know how many keys we may find for a row (due to schema changes).

We will be able to address this once we change scans to work in chunks (#2966).

**Comment by tschottdorf** [comment]
@petermattis's ideas about making SQL row-oriented would also help since then the SQL `LIMIT` would translate more directly to a `Scan` limit.

**Comment by RaduBerinde** [comment]
Yeah, making KV row-aware would help (but still, only when there are no other filters in play).

**Comment by RaduBerinde** [comment]
ETA is 1-2 days for a change that will help in this case (specifically single-range scans).

**Comment by RaduBerinde** [comment]
The situation should now be improved - we will read only the first chunk (10,000 key/values) instead of the entire table, as long as the scan only involves one span (it is the case for the example query).

I am working on a change to further improve on this by reducing the size of the first chunk depending on the limit.

Resolving the single-span caveat is dependent on #4696.

**Comment by RaduBerinde** [comment]
Now it should be really fast, we should read just one row worth of keys.

Leaving open until the multi-span case is addressed too.

**Comment by spencerkimball** [comment]
Cool, I've changed the photos app to use this now.

**Comment by RaduBerinde** [comment]
Fixed for multi-span case as well in #5214. Further improvements are tracked by #5267.
