### ISSUE TITLE
Ability to specify how long a node waits to transfer leases before performing a hard shut down

### ISSUE THREAD

**Issue by rkruze** [cockroachdb/cockroach#43015]
**Is your feature request related to a problem? Please describe.**
Currently, today when a node receives a SIGTERM or a `cockroach quit` command, it waits for 1 minute at max for the node to drain its leases before performing a hard shutdown.  This is hardcoded and not configurable. 

**Describe the solution you'd like**
It would be ideal to have the ability to specify how long the node can be in a draining state before a hard shutdown happens. This is important to avoid any spikes in latencies due to a leaseholder not being available for a given query while performing maintenance that requires a node to be restarted.

**Comment by knz** [comment]
cc @andy-kimball @piyush-singh @johnrk for triage

**Comment by andy-kimball** [comment]
@rkruze, from the code I'm seeing what looks like a max wait of only 5 seconds (hardcoded). Where did you get the 1 minute wait time?

**Comment by knz** [comment]
Can you link to the code you saw. The one I know about is in server/admin.go for the Drain request. There the hard timeout is 10s not 5.
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by andy-kimball** [comment]
`Store.SetDraining`:
```
if err := contextutil.RunWithTimeout(ctx, "wait for raft leadership transfer", raftLeadershipTransferWait,
```
where
```
// The maximum amount of time waited for leadership shedding before commencing
// to drain a store.
const raftLeadershipTransferWait = 5 * time.Second
```

**Comment by knz** [comment]
ok so we have:

- raft leadership transfer: 5 seconds
- hard timeout in Drain (server/admin.go): 10 seconds
- hard timeout upon SIGTERM (cli/start.go): 5 seconds

these are operating concurrently from each other

**Comment by rkruze** [comment]
I had seen this: 

https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/start.go#L967

which looks to say that after 60 seconds, a hard shutdown is issued, but it is very likely I'm missing additional context.

**Comment by knz** [comment]
yes indeed that's a 4th one.
