### ISSUE TITLE
ui: introduce pagination on the database page for when there are hundreds of tables

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#43026]
**Is your feature request related to a problem? Please describe.**
Loading the database page when database has hundreds of tables makes UI inoperable. 

**Describe the solution you'd like**
Introducing pagination with limit to 10-20 tables per page may alleviate that.

**Describe alternatives you've considered**

**Additional context**

Here's a gist with steps to reproduce the behavior: https://gist.github.com/dbist/d37705f1da3e267d42bd03d3ff746b2f

It is related to https://github.com/cockroachdb/cockroach/issues/22941

**Comment by piyush-singh** [comment]
cc @Annebirzin - this page can be expensive to render, so as we are thinking about the database treetable component, we may also want to think through pagination. For reference, I think the largest DB we've heard of so far from a customer was around 5k tables.

**Comment by dhartunian** [comment]
Picking up this commit #32219

**Comment by dhartunian** [comment]
I think a first pass on this can be done purely on the frontend. From a quick run through I see that the request to get the list of tables is quick, it's the individual requests per table that slow things down. If we can bring that down it will help a lot.

**Comment by dhartunian** [comment]
@elkmaster assigning this ticket to you, can you try adding pagination to the db page and test with 1000 tables on a single database? The script @dbist provided above can help you set it up. Just make sure you call `cockroach init` after the `cockroach start` command before you execute the python script.

Thank you @dbist for the detailed reproduction steps!

**Comment by dhartunian** [comment]
As a clarification, I am treating this issue as being specifically about too many *tables*, not databases. If we'd like to address the latter as well, we should open a separate ticket.

**Comment by dhartunian** [comment]
Further clarification @elkmaster, designs for this will be implemented separately so please don't worry about styling for this ticket. Let's get the pagination logic right first and make sure the backend requests are structure correctly, then we can move on to visual implementation.

@Annebirzin has a redesign for the db page that already includes pagination so we'll implement that as a separate ticket.

**Comment by ajwerner** [comment]
@dhartunian did you mean to reopen this with #45917?
