### ISSUE TITLE
acceptance_deploy tests broken

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#4302]
https://circleci.com/gh/cockroachdb/cockroach/12635

CircleCI builds on master run an additional `deploy` phase which builds static binaries, runs the acceptance tests again, and pushes the binaries to AWS. A) This needs to be restricted to one shard instead of running on all three. B) The tests are currently failing due to some difference between the normal acceptance environment and this one.

**Comment by bdarnell** [comment]
Or maybe it's not running on all three shards (the logs look identical including the random seed). I think it's only running once but getting reported under all three.

**Comment by petermattis** [comment]
I'm pretty sure the `deploy` step is only run on the first shard. The UI is a bit confusing about this.

**Comment by petermattis** [comment]
Is there anything to be done here? Deployment definitely only runs on shard 0. And the failure looks the same as #4316.

**Comment by bdarnell** [comment]
No, it's just a duplicate of #4316.
