### ISSUE TITLE
Schema Changes: Index creation failed 

### ISSUE THREAD

**Issue by roncrdb** [cockroachdb/cockroach#43034]
**Describe the problem**

User was creating an index using the PK and a secondary column, he was met with this error: 

`(23505): 18549129 entries, expected 18549131 violates unique constraint.`

DML was:

`CREATE INDEX IF NOT EXISTS "INDEX NAME" ON <TABLE> (reported, id)`

The code that is generating this error is: 

```
if idxLen != tableRowCount {
 	 // TODO(vivek): find the offending row and include it in the error.   
		return pgerror.Newf(
			pgcode.UniqueViolation,
			"%d entries, expected %d violates unique constraint %q",
			idxLen, tableRowCount, idx.Name,
			)
		}
```

They user has sent us over the table to try this out on our end, it can be found [here](https://cockroachlabs.sendsafely.com/receive/?recipientCode=2HhlrSFrHyvRW2jCUqcqDYNhif84zQdXt4bNgOOs70E). 

Note: please use the oncall@ to log in and download the file. 

Ultimately the user dropped the table and recreated the index on an empty table and that worked.  This happened on a test cluster they are concerned that this could happen in production.  

**Expected behavior**
Index should have been created without any issues. 

**Environment:**
 - CockroachDB version 19.2

**Additional context**
User had to drop the entire table and create the index on an empty table, this isn't a feasible workaround on a production cluster.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4211](https://cockroachdb.zendesk.com/agent/tickets/4211) has been linked to this issue.

**Comment by roncrdb** [comment]
@mwang1026 any movement on this?

**Comment by awoods187** [comment]
@lucy-zhang can you triage this?

**Comment by jordanlewis** [comment]
I can't download the table that's linked. No permissions.
