### ISSUE TITLE
bulk-io: import seems to randomly fail and then succeed on subsequent retry of the import

### ISSUE THREAD

**Issue by roncrdb** [cockroachdb/cockroach#43070]
**Describe the problem**

User is experiencing an issue when running concurrent imports where the import will fail with various errors (i.e. "unexpected EOF", "Expected x columns, found y") Then on subsequent attempts to import the same file the import succeeds without any change to the file. 

**To Reproduce**

User has provided a sample random import : 

```
IMPORT TABLE t1

(

   a string(13) PRIMARY KEY NOT NULL,

   b decimal(10,0),

   c decimal(10,5),

   d decimal(10,5),

   e string(15),

   f string(13) NOT NULL,

   g string(13) NOT NULL

) CSV DATA ('${random_data_0}','${random_data_1}')

WITH decompress = 'gzip', delimiter = '|', skip = '1', experimental_save_rejected

;
```

If possible, provide steps to reproduce the behavior:

1. Import concurrent files, user has seen this issue with a minimum of 4 concurrent imports. 
2. Wait to see if any fail. 
3. Re-run the failed imports

**Expected behavior**
Imports should either fail or succeed, errors should be deterministic if the imports do fail. 

**Additional data / screenshots**

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version 19.2 also 20.1 alpha
 - Server OS: [e.g. Linux/Distrib]
 - Client app - Pentaho client
**Additional context**

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4190](https://cockroachdb.zendesk.com/agent/tickets/4190) has been linked to this issue.
