### ISSUE TITLE
Db restore fails for user having permissions

### ISSUE THREAD

**Issue by vladdy** [cockroachdb/cockroach#43090]
Filling this out to not forget. The issue was found during db migration to CockroachCloud. More details will follow.

**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

Restore a db backup as a user having permissions to create tables. The restore will fail complaining abut insufficient permissions to create tables.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
2. Send SQL ... / CLI command ...
3. Look at UI / log file / client app ...

**Expected behavior**

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version [e.g. 2.0.x]
 - Server OS: [e.g. Linux/Distrib]
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
What was the impact?

**Comment by mwang1026** [comment]
Hi Vlad. I just tried to repro this on latest 20.1 and wasn't able to. I created a user, gave it CREATE permission to the db I was restoring into and the admin role and was able to restore into that db.

Do you know if this is still an issue?

**Comment by vladdy** [comment]
We had this issue in 19.2, so unless something was backported, there is still a problem with that release.

**Comment by mwang1026** [comment]
I just did it in 19.2.6. Created user michael, granted CREATE on the movr database and also granted admin, restored movr.promo_codes fine as michael.

**Comment by mwang1026** [comment]
closing -- couldn't repro
