### ISSUE TITLE
opt: slow query/doesn't return 

### ISSUE THREAD

**Issue by roncrdb** [cockroachdb/cockroach#43100]
**Describe the problem**

The following query runs slowly or doesn't return: 

DELETE FROM <TABLE> WHERE reported < ('2019-12-06 00:12:19.361106+00:00')::TIMESTAMPTZ LIMIT 1000;

**To Reproduce**

Attached are the explain (opt, env verbose), and histogram stats. 

[EXPLAIN](https://docs.google.com/document/d/1u0m9QM6w8Xp0NDjABUETP6sWtqxxNTspRlssn9McYV0/edit?usp=sharing)

[Statistics](https://drive.google.com/file/d/1QCtGxMzGi2XNv-IoOgZ9eQtYbN655OX1/view?usp=sharing)

**Expected behavior**
User  runs this every five minutes, and it runs it in a loop until there are no rows left that meet that criteria. This query taking a while to return could cause other issues in the cluster. 

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version 19.2

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4244](https://cockroachdb.zendesk.com/agent/tickets/4244) has been linked to this issue.

**Comment by roncrdb** [comment]
@awoods187 can someone take a look at this?

**Comment by RaduBerinde** [comment]
The optimizer plan looks great to me, I think someone from execution should take a look.

**Comment by awoods187** [comment]
@solongordon can you triage this?

**Comment by solongordon** [comment]
@roncrdb Did you get an answer from the user about whether the equivalent SELECT is as slow as the delete? If it's not, I would have them try our standard batch delete advice of first selecting the IDs to be deleted and then doing the delete in a separate statement. This can reduce contention with other queries.
```
SELECT id FROM results WHERE reported < '2020-01-27T18:27:09Z' LIMIT 100;
DELETE FROM results WHERE id IN (<list of ids>);
```

**Comment by roncrdb** [comment]
@solongordon sounds good, the select takes ~15ms so I think our standard batch delete would be the route we want to go down.

Thanks!

**Comment by solongordon** [comment]
Great. If the batch delete is still slow I think we'll want to get a trace and have someone from KV take a look.

**Comment by jordanlewis** [comment]
Closing due to lack of new info. Feel free to re-open given more data.
