### ISSUE TITLE
Allow valid domain name characters in the DB username

### ISSUE THREAD

**Issue by VinodAnandan** [cockroachdb/cockroach#43105]
**Is your feature request related to a problem? Please describe.**
Currently, there is a restriction for the database username which will limit the certificate-based authentication. It's very common to include .local (e.g.:  internal-service2.local) in the CN (Common Name) of a certificate.  The AWS Certificate Manager (ACM) won't even issue a certificate if the "dot" (.) is not present. 

**Describe the solution you'd like**
Could you please include dot (.) and hyphen (-) in the whitelist for the database username ?

Thank you,

Vinod

**Comment by VinodAnandan** [comment]
CCing @bdarnell @knz @georgebuckerfield @mberhault

**Comment by knz** [comment]
Thanks for the request! 
CockroachDB 19.2 already added support for hyphens. For the periods see #43114.

**Comment by knz** [comment]
@rolandcrosby @aaron-crl can you review this and the last few comments on #43114? 
I'd need a yes/no answer as to whether the change is desirable, and a separate yes/no on whether putting this on the docket for 20.1 is a good idea.
