### ISSUE TITLE
util/decimal: implement arbitrary-precision mathematic routines for inf.Dec

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#4311]
The final part of adding full support for the arbitrary-precision decimal type from #1618 is to recreate mathematic routines that act at an arbitrary scale. These functions are located in `util/decimal/decimal.go`, and all fit the signature pattern set forth in [`math/big`](https://golang.org/pkg/math/big/) and [`gopkg.in/inf.v0`](https://godoc.org/gopkg.in/inf.v0) of using their first parameter as a nullable receiver to assign function results to reduce allocations as much as possible.

The following implementations are needed. Contributions are very welcomed here, as each routine should be fairly self-contained.
- [x] Mod
- [x] Sqrt 
- [x] Cbrt 
- [x] Log 
- [x] Log10 
- [x] LogN 
- [x] Exp 
- [x] Pow

**Comment by bogdanbatog** [comment]
I started implementing `Cbrt` based on [Ken Turkowsk paper](http://people.freebsd.org/~lstewart/references/apple_tr_kt32_cuberoot.pdf). Is this ok, or would you rather have it call `Pow` and `Exp`?

**Comment by seiflotfy** [comment]
Working on Pow here https://github.com/cockroachdb/cockroach/pull/5972

**Comment by seiflotfy** [comment]
Done.
The last missing routine was implemented with https://github.com/cockroachdb/cockroach/pull/5972.

**Comment by nvanbenschoten** [comment]
Thanks for closing this out @seiflofty!
