### ISSUE TITLE
sql: casting with a wild card throws error "pq: unsupported comparison operator: <bytes> LIKE <bytes>"

### ISSUE THREAD

**Issue by ricardocrdb** [cockroachdb/cockroach#43120]
A user is running on 19.2.0 and attempts the following query, seeing the following error when using casts:
```
root@127.0.0.1:55676/movr> SELECT 'foobar'::BYTEA LIKE 'foo%'::BYTEA;
pq: unsupported comparison operator: <bytes> LIKE <bytes>
```
However, the following SELECT query with the same wildcard works as expected:
```
root@127.0.0.1:55676/movr> SELECT b'foobar' LIKE b'foo%';
  ?column?  
+----------+
    true    
(1 row)
```

Expected behavior is for both queries to yield the same result.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4252](https://cockroachdb.zendesk.com/agent/tickets/4252) has been linked to this issue.

**Comment by jordanlewis** [comment]
LIKE only works with string columns, so we'll close this. Future enhancements to the type system will likely help.
