### ISSUE TITLE
How to  Develop UI whithout rebuilding and relaunching the cluster for each change

### ISSUE THREAD

**Issue by mxwmwx** [cockroachdb/cockroach#43139]
First，I start a cluster,
![image](https://user-images.githubusercontent.com/37258498/70776794-18c5e880-1db9-11ea-96e1-632e8ef4026f.png)

![image](https://user-images.githubusercontent.com/37258498/70776846-3a26d480-1db9-11ea-8c6f-810e4194ba19.png)
![image](https://user-images.githubusercontent.com/37258498/70776865-4c087780-1db9-11ea-98af-40951c07291c.png)
![image](https://user-images.githubusercontent.com/37258498/70776886-5aef2a00-1db9-11ea-91b8-dac0b7b8a7c2.png)
Second, I used make ui-watch TARGET=localhost:8080
![image](https://user-images.githubusercontent.com/37258498/70776941-79552580-1db9-11ea-87e2-97cc2647e7cb.png)
And it shows this 
![image](https://user-images.githubusercontent.com/37258498/70777007-a6a1d380-1db9-11ea-92cf-cd011f036db9.png)
![image](https://user-images.githubusercontent.com/37258498/70777024-abff1e00-1db9-11ea-91ff-447a6c28816c.png)
but when I open http://localhost:3000 it shows 
![image](https://user-images.githubusercontent.com/37258498/70777115-e36dca80-1db9-11ea-888a-fe9024d47ba3.png)
Would you like to tell me how to fix it?

**Comment by jordanlewis** [comment]
This should work fine. Closing due to age.
