### ISSUE TITLE
sql: index span constraints from comparisons between types are permitted but do not work because key encodings differ

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#4313]
We currently allow comparisons between `INT`, `FLOAT`, and `DECIMAL`, which means that a comparison between the two will be allowed by the type checker. Unfortunately, this does not mean that these different types' encoded keys will compare "naturally". An effect of this is that when creating index spans based on `ComparisonExpr`s, we will encode the constant key without casting, meaning that the span comparison will not work correctly. 

```
CREATE TABLE t (x DECIMAL PRIMARY KEY);
INSERT INTO t VALUES (1.0::DECIMAL), (2.0::DECIMAL), (3.0::DECIMAL);

SELECT * FROM t WHERE x > 1;
+---+
| x |
+---+
+---+

EXPLAIN SELECT * FROM t WHERE x > 2;
+-------+------+---------------+
| Level | Type |  Description  |
+-------+------+---------------+
|     0 | scan | t@primary /2- |
+-------+------+---------------+
```

The solution to this when the constant value is the less precise value (`SELECT d (decimal) FROM ... WHERE d > 1`) is easy, upcast the constant value and encode. Things get tricky when the constant value is more precise however (`SELECT i (int) FROM ... WHERE i > -1.9::decimal`), because we would need to decide on a way to downcast the constant before encoding in such a way that it mirrored the normal upcasting comparison.

**Comment by tamird** [comment]
Also described in #3633

**Comment by nvanbenschoten** [comment]
An interesting note I just realized here is that DECIMAL and FLOAT inconsistencies would actually work correctly here because they share an encoding. Probably not worth a special case in the fix though.
