### ISSUE TITLE
sql: Integer column has become an int4 column after upgrading to 19.2

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#43146]
**Describe the problem**
Integer column has become an int4 column after upgrading to 19.2

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
2. Send SQL ... / CLI command ...
3. Look at UI / log file / client app ...

**Expected behavior**
INTEGER needs to map to INT8 not INT4.

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version 19.2.0
 - Server OS: [e.g. Linux/Distrib]
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
What was the impact?
Workaround is to recreate schema with INT8.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4078](https://cockroachdb.zendesk.com/agent/tickets/4078) has been linked to this issue.

**Comment by finnsson** [comment]
It seems like this bug is affecting columns created with Cockroach prior to 2.1.4.

**Comment by rafiss** [comment]
cc @ajwerner -- this is quite an old issue that got missed, but tagging you in case you feel there's anything we'd still like to do.

**Comment by ajwerner** [comment]
We don't support these versions any more. I'm closing this.
