### ISSUE TITLE
error: pq: unimplemented: adding a REFERENCES constraint while also adding a column via ALTER not supported

### ISSUE THREAD

**Issue by proffalken** [cockroachdb/cockroach#43140]
**Describe the problem**

When trying to deploy the latest chirpstack.io code using CockroachDB instead of Postgresql, an error is encountered about an "unimplemented" feature.  I *believe* that this should have been fixed by https://github.com/cockroachdb/cockroach/pull/34301 but as GOLANG is not my strong point, I'm not 100% sure...

**To Reproduce**

   * Configured CockroachDB cluster, confirmed working via both command line and 
webUI
   * Created user and database via the cli, confirmed working
   * Downloaded latest Chirpstack Application binary, updated config file to point to CockroachDB
   * Started the service

**Expected behavior**

The migrations should run without issue

**Additional data / screenshots**

```
[chirpstack_local_cluster]$ ./chirpstack-application-server -c as.toml 
INFO[0000] starting ChirpStack Application Server        docs="https://www.chirpstack.io/" version=3.6.1
INFO[0000] storage: setting up storage package          
INFO[0000] storage: setup metrics                       
INFO[0000] storage: setting up Redis pool               
INFO[0000] storage: connecting to PostgreSQL database   
INFO[0000] storage: applying PostgreSQL data migrations 
FATA[0000] setup storage error: storage: applying PostgreSQL data migrations error: pq: unimplemented: adding a REFERENCES constraint while also adding a column via ALTER not supported handling 0002_join_accept_params.sql 
```

**Environment:**
 CockroachDB:
```
cockroach version
Build Tag:    v19.2.1
Build Time:   2019/11/18 23:23:55
Distribution: CCL
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.12.12
C Compiler:   gcc 6.3.0
Build SHA-1:  53eef0857d14cc3af720e136ddaff4eeab026fd0
Build Type:   release
```

Server OS:
```
Arch Linux 5.4.2-arch1-1 #1 SMP PREEMPT Thu, 05 Dec 2019 12:29:40 +0000 x86_64 GNU/Linux
```

Client Software Version:
```
INFO[0000] starting ChirpStack Application Server        docs="https://www.chirpstack.io/" version=3.6.1
```

**Comment by proffalken** [comment]
Ah, actually, this looks like it's related to https://github.com/go-gorp/gorp/pull/359 - I'll see what's going on there...

**Comment by proffalken** [comment]
It tracks to [this line](https://github.com/brocaar/chirpstack-application-server/blob/master/migrations/0002_join_accept_params.sql#L9) - I'm wondering if I can refactor the relationship setup here so that the reference is split out somewhere else.

**Comment by solongordon** [comment]
The error in the subject is still an unimplemented feature tracked by #32917. The workaround is to first add the column with no constraint and then add the REFERENCES constraint in a separate query, as described in our [ADD CONSTRAINT](https://www.cockroachlabs.com/docs/stable/add-constraint.html#add-the-foreign-key-constraint-with-cascade) docs.

Note that if the table is not empty, it will be necessary to add an index on the new column before adding the constraint.

**Comment by proffalken** [comment]
Thanks, I'll close this one off and track #32917 instead.
