### ISSUE TITLE
opt: identical `WithScanExprs` can appear multiple times in the same query

### ISSUE THREAD

**Issue by savoie** [cockroachdb/cockroach#43148]
It is possible to have multiple identical `WithScanExpr` instances in a tree if they are scans on the same CTE and have no columns. This can cause a crash when attempting to assign the expressions different required physical properties, and seems likely to also be silently causing other issues.

```
WITH a AS (SELECT * FROM t)
     (SELECT 1 FROM a LIMIT 9) UNION (SELECT 1 FROM a LIMIT 10);
panic: cannot overwrite [limit hint: 9.00] /  (0.01) with [limit hint: 10.00] /  (0.01)
```
This seems like a similar issue to the one solved by https://github.com/cockroachdb/cockroach/pull/35004.

**Comment by mjibson** [comment]
Yeaaaaaaah your first sqlsmith bug. May it be the first of many.
