### ISSUE TITLE
cli: weirdness in SQL shell when printing a row

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#4315]
The SQL query output is screwy...

```
root@:15432> select commentID, userID from comments where photoID=''::bytea;
+---------------------------------------------------------+--------+
|                        commentID                        | userID |
+---------------------------------------------------------+--------+
| "\x00]\x8c8\x9f\x1fA\x82\xa5\xe6\x19\xaf\xe4\xc0Y\xac"  |  40090 |
| "\x05>4\xb9\xc6JI%\x85a\x16\"W\x12\x9a\xd4"             |   4507 |
| "\x0e\xaf^\rx\xa2D\x1b\x85;s{\xdfG\x17H"                |  38767 |
| "\x13Y:\xed\x1fLM\xa6\x96<\x8e\xcc)\u007f\xbbE"         |  28156 |
| "\x1bq\xa6\x1dAaOe\xa2\xea\xaa\xc9W\xd5\xd2c"           |   2481 |
| "\x1c\xdc3\x17hdG\xba\x811R\xeb\x0e#\x9b\x92"           |   2481 |
| "\x1d\x99\xe0鍋C\x82\xabu\xa0T\x99\xaa\xa0#"            |  30718 |
| "\x1fi<\xf5\xf9iG\xf8\xbcVt\x9f\x96TKo"                 |  28551 |
| "!\x00\x88\xa8\x04\"I1\xac\xf2K \xa0\xde8D"             |   8548 |
| "!/\xb8\xdbKG@\xf6\xba\xb1\x85{\x1b玥"                  |   2481 |
| "'\x16\x89\xfdL*E\xe8\x98pp\x95\x04\xae܈"               |   8548 |
| "*<f\ar\xdfD\v\x94+\x1b\x84\x96\xf7\xc56"               |   4507 |
| "/\x19\xff\x86YLLӽufe\x05\xff?\x86"                     |  25649 |
| "8\xd6x\xa5\xa6\xb0F\x88\xa5g\xe2\xb7\xd55L\xed"        |  38767 |
| ";\x04e\x1el'@*\x8cMdg\x87\xdea\xcd"                    |  53297 |
| ">\x8c\x03}[KI\x80\x89\t\"\xaf\x8e\x89\xbfA"            |  25649 |
| "C\x00\xa3\xba\x9b^B\xe1\x82\av\x01\xe4z\xf6U"          |  28156 |
| "F\xddT\xf5܌L\x1c\xbf=ݬD \x90{"                         |  19029 |
| "\\\xf5:\x1et6C\x9b\x8axQq\xa2Kwi"                      |  28156 |
| "b\x8f_\x89\x86hH\xf8\x888\x1b\x80\xd0}^s"              |  53297 |
| "d\xa8\xdbF\xcd-Ll\xa5\x9b\x05\x95\xf7\x9f\xbf\xd8"     |  38767 |
| "h\xafޑ\xedAOA\x9a\xf2\xff<\a\x1b\x1ad"                 |  28451 |
| "lvXc:\xb1@\xaf\x8cM\xc0\xd0$\xfd\xe9\x87"              |  19029 |
| "p\xef\xacl\x18\xedC\xb7\x87OI[y\xc7\x15\x9c"           |   8366 |
| "u\n9\x10\x9e\xafFM\xa6oԔ\xcdn\xf3z"                    |  19029 |
| "{1\xdd/n>J^\xa4\x03\f\xf7T<\x0f\x10"                   |  28451 |
| "\u007f\xa14\x83\x8d+E\xa9\x81\\\xa1\xe1\xbd¢@"         |  28551 |
| "\x86\x80y<\x83\x18EU\xaf\x05w\x0f\x9d\xf4?\xcb"        |   8366 |
| "\x8bὗV\xa5Nr\x87զ\xb56\xa17["                          |  48162 |
| "\x8e~e\xb2$\xb6DM\x91 \x84ߴ\xd09\xb1"                  |  48162 |
| "\x99\xb8\xba\x96ƑK\x80\x95\x17fv!\xef\xffa"            |  40090 |
| "\xa2y\xb7\xd28|C\x99\x87\xff_\xfb\x01@J\xf0"           |   3532 |
| "\xa5#\xce\xd1K\x9dA\x06\x98\xf8\x93\x17\xe4\xed\b\xb3" |  53297 |
| "\xa5\x83:\xd0f~Ij\xaf\xb9\xa9\xcb Q\x14\x98"           |   6434 |
| "\xa7\xcb\xdbeLmJ\x87\xbd>\x15\x1c\x99\xec\xd6B"        |   4507 |
| "\xaa{\xa4N7jM\xbb\xa8\xcd\x0e\xf0d\xea\xfaj"           |  86674 |
| "\xab\x19\xe2\x1d\xf7\x11O^\xba\fV\x8a\xe6\x047\xbb"    |  30718 |
| "\xb9r\x9e\xedW\x81DБݨ\x89\xa8?ZM"                      |  28551 |
| "\xbfM\xd6\xd9\x10\xceLf\xb0A[\xaa\xf7\x9c@\xde"        |   3532 |
| "\xc1:\x83%ĲK\xe8\xa1ȓB՚\xdc\x1d"                       |  25649 |
| "\xc9\xc8k\b\x9d6Hc\xb3\x83!\x1a\x98\xff\xc8T"          |  28451 |
| "\xce\xf7\a\xd0\x13mEk\xbc~\x87r\xe5J\xc2y"             |  48162 |
| "\xd7UmWx_Ie\x98hq\xcd)\x81$\xa4"                       |   8366 |
| "\xefy\x88 \xcagDݼ\xee\xd6h\x03\x0f\"\xc9"              |   8548 |
| "\xf8\xdb0aWSG\xe9\x8d\x15\xd0\t\x17\xb5\x92\a"         |   3532 |
+---------------------------------------------------------+--------+
```

This row in particular:

`| "'\x16\x89\xfdL*E\xe8\x98pp\x95\x04\xae܈"               |   8548 |`

Looks like there are maybe bytes there that are screwing up the TTY. You can kind of see the userID there should be `8548`, which I confirmed via:

```
root@:15432> select commentID, userID from comments where userID=8548;
+---------------------------------------------+--------+
|                  commentID                  | userID |
+---------------------------------------------+--------+
| "!\x00\x88\xa8\x04\"I1\xac\xf2K \xa0\xde8D" |   8548 |
| "'\x16\x89\xfdL*E\xe8\x98pp\x95\x04\xae܈"   |   8548 |
| "\xefy\x88 \xcagDݼ\xee\xd6h\x03\x0f\"\xc9"  |   8548 |
+---------------------------------------------+--------+
```

**Comment by tamird** [comment]
Likely introduced by https://github.com/cockroachdb/cockroach/pull/4254.

**Comment by spencerkimball** [comment]
Are you on a fix for this?

**Comment by tamird** [comment]
Nope, just wanted to alert @RaduBerinde.

**Comment by RaduBerinde** [comment]
@petermattis 
Maybe we want to be more strict and check that the strings only have simple ASCII text in them (instead of any valid UTF8)?

**Comment by bdarnell** [comment]
We should be able to print (most) valid UTF8 (but the byte strings here are not valid UTF8). For character strings, we should be able to print any non-control characters. For byte strings `%q` is probably the right thing to do but I'm not sure what control character is slipping through here. @spencerkimball , can you do `select to_hex(commentID)` for one of the affected rows?

**Comment by spencerkimball** [comment]
Unfortunately some massive memory leak caused everything to freeze up and I had to reboot. My data was in `/tmp`, so it's toast now.

**Comment by petermattis** [comment]
Hmm, maybe trying to fix this in the SQL shell was the wrong place. Why are `string` columns coming back as `[]byte`? Are we sending the wrong oid in pgwire? Looks like we send both `string` and `bytes` as `oid.T_text`.

**Comment by tamird** [comment]
AFAIK, the PG wire protocol does not distinguish between `string` and
`bytes`. See my comment in #4312.

**Comment by tamird** [comment]
@petermattis OK, after fixing #4312 in #4330 I figured out why strings on the server don't come out as strings on the client. The reason is lack of special handling in lib/pq. See https://github.com/lib/pq/pull/436.

**Comment by tamird** [comment]
[Upstream has decided it's not to be](https://go-review.googlesource.com/#/c/19439/) so we won't be able to distinguish between `string` and `[]byte`...ever?

**Comment by petermattis** [comment]
Wonder if they are going to enforce that comment or not? We returned `string` from `cockroach/sql/driver` without problem. We could certainly do so in a fork `lib/pq` as well. Or perhaps this is another argument about avoiding `database/sql` from our shell and enhancing a fork of `lib/pq` so that we can get type information about the columns to determine how to print them.

**Comment by tamird** [comment]
Yes, perhaps. https://github.com/jackc/pgx does distinguish (even via the `database/sql` interface), FWIW.

**Comment by RaduBerinde** [comment]
I would try to argue that it is a *relaxation* of a requirement which means the interface is 100% backwards compatible..

**Comment by tamird** [comment]
By all means, argue away.

**Comment by tamird** [comment]
Note that change that comment also implies having to change the behaviour of https://godoc.org/database/sql/driver#IsScanValue (no used inside the Go source tree), and that would definitely not be backwards compatible.

**Comment by tamird** [comment]
Assigning back to @RaduBerinde because my proposed fix won't be possible.

**Comment by RaduBerinde** [comment]
Looks like the problematic row *is* quoted (`%q`) so I doubt this was introduced by #4254. Making the string/byte[] distinction wouldn't have helped either (we are already treating it as a byte[]).

I think we are assuming we can display any UTF8 which is not the case. I propose using `%+q` instead of `%q`, and strengthen the check to use `%s` for strings that have only printable ASCII characters.
