### ISSUE TITLE
sql: pg_type access

### ISSUE THREAD

**Issue by karlseguin** [cockroachdb/cockroach#43177]
**Issue:**
I'm using the official Elixir PostgreSQL library. On startup, it gets data from `pg_type` to optimize encoding/decoding. Unfortunately, it seems like the only way to be able to `select` from `pg_type` is to give the user `select` on the entire database. This isn't ideal as it pretty much undermines any user-specific security you might want to apply

**Solutions**
Either ability to grant select on `pg_type`, or, if it's decided that the there's nothing secret in there, having it world-readable. (Or if there's an existing solution, better document it).

**Comment by knz** [comment]
This is indeed a current known limitation.

The way it works (currently) is that virtual tables are assumed to contain metadata that describe the current database and so the permission on the database is required.

You're making a point that some vtables are special in that they contain metadata that is cluster-wide and not specific to one database. That should use a different permission checking logic.

I agree this needs to be fixed.

**Comment by jseldess** [comment]
@knz, can you help me draft a known limitations text?

**Comment by knz** [comment]
"Access to certain virtual tables in the `pg_catalog` and `information_schema`  schemas require more privileges than otherwise required in PostgreSQL. For example, access to `pg_catalog.pg_types` require SELECT privilege on the current database whereas this privilege is not required in PostgreSQL."
