### ISSUE TITLE
backup: make basic backup/restore in open-source edition

### ISSUE THREAD

**Issue by sandstrom** [cockroachdb/cockroach#43174]
I wish you'd add vanilla backup/restore to the open-source edition. Even for personal projects few people will run a database that can't be backed up (sql dump isn't a good alternative).

There are tons of other useful features that are limited to the enterprise offering:
https://www.cockroachlabs.com/docs/stable/enterprise-licensing.html

I'd guess that if you make a poll among all your enterprise customers, few-to-none will use only the backup/restore functionality, so I don't think you'll miss out on much money.

But you are missing out on adoption by not having a reasonable backup/restore command, see e.g. [this HN comment](https://news.ycombinator.com/item?id=21517596).

An alternative would be to let people halt replication and do disk snapshots for backups, but I guess that's harder when the data is distributed across multiple nodes.

**Comment by keverw** [comment]
Looks like they've improved this! https://www.cockroachlabs.com/blog/distributed-backup-restore/

Seems a lot better than the old way, not incremental though so not sure if that's a deal breaker.  I guess that really depends on your database size, but that is a huge improvement I think! Some other things I wish CDB had unrelated to backup then it sounds like it'd be the best database on the entire planet!

**Comment by sandstrom** [comment]
Agree, this is more or less fixed now that the community edition can do basic backup/restore.

I think it's alright if incremental backups are a paid feature, as long as non-incremental backups are usable/practical under most "standard" workloads. I haven't tried, but I'll assume that's the case and close this. Can re-open if that turns of to be false.

Obviously CockroachDB has to make money from something, and breaking out some features into an enterprise plan seems reasonable. My earlier objection was that (1) this was hindering adoption in general, which would hurt their revenue more (long term) than charging money for backups and (2) no backups makes it unusable for most hobby projects, defeating the purpose of a community edition to begin with.

Thanks @dt @mwang1026
