### ISSUE TITLE
computed default for `TIMESTAMP` column errors with `TIMESTAMPTZ` type conflict

### ISSUE THREAD

**Issue by aybabtme** [cockroachdb/cockroach#43179]
**Describe the problem**

When creating a table with a column of type `TIMESTAMP` and setting a default value of `now() + interval '7d'`, the statement is rejected with a type error.

**To Reproduce**

Try to create this table:

```sql
CREATE TABLE IF NOT EXISTS sessions (
    -- elided for clarity
    expires_at TIMESTAMP NOT NULL DEFAULT now() + INTERVAL '7 days'
);
```
An error comes up:

```
pq: expected DEFAULT expression to have type timestamp, but 'now() + '7 days'' has type timestamptz
```

**Expected behavior**

I would expect the computed default to produce a `TIMESTAMP`.

**Additional data / screenshots**

```
root@:26257/loadtests> CREATE TABLE IF NOT EXISTS sessions (
    -- elided for clarity
    expires_at TIMESTAMP NOT NULL DEFAULT now() + INTERVAL '7 days'
);
pq: expected DEFAULT expression to have type timestamp, but 'now() + '7 days'' has type timestamptz
```
**Environment:**
 - CockroachDB version v19.1.4
 - Server OS: macOS Catalina 10.15.2 (19C57)
 - Client app `cockroach sql`

**Additional context**

```
Build Tag:    v19.1.4
Build Time:   2019/08/13 19:41:13
Distribution: CCL
Platform:     darwin amd64 (x86_64-apple-darwin18.6.0)
Go Version:   go1.12.7
C Compiler:   4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)
Build SHA-1:  51a6fdedf0ce1d1329d40d801a7deaf8206b6b07
Build Type:   release
```

**Comment by jordanlewis** [comment]
We don't have implicit casts in CockroachDB yet. You can solve the problem by using an explicit cast, for now. `default (now() + interval '7 days')::timestamp` should work.

**Comment by awoods187** [comment]
@jordanlewis do we have an issue tracking implicit casts?

**Comment by SWDevAngel** [comment]
Hi Antoine. Thank you for contributing to CockroachDB this year. As a token of our appreciation we would like to send you a gift. Please DM me on our [community Slack](https://cockroa.ch/slack) @lisa so I can send you a link. (If you don’t want a gift, we also have a charitable contribution choice.) All orders need to be in by December 13, so please send this asap. :)
