### ISSUE TITLE
ui: network latency follow up work

### ISSUE THREAD

**Issue by Annebirzin** [cockroachdb/cockroach#43206]
**Feedback for network latency matrix #40311**

- [x] Default to 'Region' (if available) instead of 'Cluster' for the view dropdown 

_current:_ 
<img width="410" alt="Screen Shot 2019-12-17 at 3 44 11 PM" src="https://user-images.githubusercontent.com/51920721/71032915-5641b300-20e4-11ea-9c12-580cd71583b6.png">

- [x] Tooltip readability: Update latency tool tip to display node info in 2 columns so it is easier to read

_current:_ 
<img width="1160" alt="Screen Shot 2019-12-17 at 1 21 16 PM" src="https://user-images.githubusercontent.com/51920721/71023480-cfcfa600-20d0-11ea-81b9-7ba2c83a4d05.png">

_new:_
<img width="1353" alt="Screen Shot 2019-12-17 at 1 05 04 PM" src="https://user-images.githubusercontent.com/51920721/71022206-ef190400-20cd-11ea-85b9-4c8167507f22.png">

- [x]  Add links to Node headers to click through on nodes to node detail page 

_new:_
<img width="439" alt="Screen Shot 2019-12-17 at 1 54 45 PM" src="https://user-images.githubusercontent.com/51920721/71025341-d829e000-20d4-11ea-9f3a-bfc6dadf5e4e.png">

- [x]  Make “ms” lowercase in matrix 
<img width="220" alt="Screen Shot 2019-12-17 at 1 56 23 PM" src="https://user-images.githubusercontent.com/51920721/71025461-17583100-20d5-11ea-803f-14c5e0c477bf.png">

**Style updates:**

- [ ] Match latency font in Standard Deviation legend to latency font in matrix (make bold)

_current_
<img width="493" alt="Screen Shot 2019-12-17 at 3 44 49 PM" src="https://user-images.githubusercontent.com/51920721/71032942-6194de80-20e4-11ea-852f-6b032f866478.png">

- [x]  Reduce size of network latency icon to match other icons in nav from 36px to 24px

_current:_
<img width="74" alt="Screen Shot 2019-12-17 at 1 10 29 PM" src="https://user-images.githubusercontent.com/51920721/71024975-1a9eed00-20d4-11ea-985a-6466457dd7ac.png">

- [x]  Add spacing above regions header to match spacing below

_current:_
<img width="1143" alt="Screen Shot 2019-12-17 at 1 21 05 PM" src="https://user-images.githubusercontent.com/51920721/71025061-4de17c00-20d4-11ea-98d8-5cd74d2336e2.png">

- [x]  When clicking to “no connections’ modal something flashes 

**Questions**
- Should we disable the collapse node check box when viewing group by 'Cloud' or any other grouping that doesn't show an aggregated number? 

_current:_
<img width="1180" alt="Screen Shot 2019-12-17 at 1 21 50 PM" src="https://user-images.githubusercontent.com/51920721/71024962-12df4880-20d4-11ea-8a8d-3b0640e4df64.png">

- What does scrolling look like for very large clusters? We should test

**Comment by dhartunian** [comment]
Friendly ask for whoever ends up working on this to make a separate PR for each change or at the very least separate commits for each change if separate PRs seem too heavyweight.
