### ISSUE TITLE
`has_column_privilege()` hangs when called inside a transaction that created a table

### ISSUE THREAD

**Issue by jakob** [cockroachdb/cockroach#43202]
1. Create a new CockroachDB cluster using the docker image `cockroach-stable`
2. Create a db
3. Connect to the db with psql
4. Execute the following commands:

```sql
BEGIN;
CREATE TABLE supports_hcp_test(id int primary key);
SELECT has_column_privilege('supports_hcp_test'::regclass, 1, 'SELECT');
```

**Expected behavior**
I expect the server to return the value `t` (true)

**Actual Outcome**
The server hangs and the client never receives a response.

**Additional data / screenshots**
It seems that the issue is somewhat non-deterministic. If the server was running, the query sometimes succeeds.

**Environment:**
 - CockroachDB version: CockroachDB CCL v19.2.1 (x86_64-unknown-linux-gnu, built 2019/11/18 23:23:55, go1.12.12)
 - Server OS: Docker
 - Client app: psql / libpq

**Additional context**
What was the impact?

Our regression test suite hangs.

**Comment by knz** [comment]
cc @lucy-zhang @jordanlewis  for triage

**Comment by jordanlewis** [comment]
@ajwerner is this related to the other deadlock issue we're discussing? just putting it near your radar.

**Comment by ajwerner** [comment]
Folding this in to https://github.com/cockroachdb/cockroach/issues/24885 which has the same root cause.
