### ISSUE TITLE
storage/engine: experiment with enabling "filter_deletes" in RocksDB

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#4321]
From discussion on #4196:

> Even with the restricted iterator, these 20k+ tombstones will get written to disk when a minor compaction happens (and potentially rewritten in future compactions until the system can determine they are completely obsolete). I believe that since we use bloom filters, we have a solution for this: set the filter_deletes option. This means that on delete, rocksdb will consult the bloom filter first and will only create tombstones for keys that the filter indicates may exist on disk. Keys that are created and deleted in between minor compactions can be deleted from the memtable without leaving any trace on disk. (Bigtable had the same optimization, but there wasn't a separate option for it: it was enabled whenever bloom filters were enabled)

**Comment by dt** [comment]
As I said last week, this did not look like a win. Adding `options.filter_deletes` to db.cc:
```
name                      old time/op    new time/op    delta
PgbenchQuery_Cockroach-8    2.74ms ± 7%    2.71ms ± 2%    ~           (p=0.478 n=40+16)
Insert100_Cockroach-8       3.62ms ± 3%    3.64ms ± 1%    ~           (p=0.531 n=20+19)
Insert1000_Cockroach-8      33.1ms ± 1%    33.9ms ± 2%  +2.49%        (p=0.000 n=20+19)
Update100_Cockroach-8       6.20ms ± 2%    6.32ms ± 2%  +1.90%        (p=0.000 n=17+19)
Update1000_Cockroach-8      59.0ms ±11%    58.3ms ± 3%    ~           (p=0.529 n=20+20)
Delete100_Cockroach-8       16.4ms ±15%    16.3ms ±16%    ~           (p=0.904 n=20+20)
Delete1000_Cockroach-8       157ms ± 1%     162ms ± 1%  +3.05%        (p=0.000 n=19+20)
Scan100_Cockroach-8          572µs ± 2%     569µs ± 2%    ~           (p=0.142 n=20+20)
Scan1000_Cockroach-8        3.23ms ± 1%    3.23ms ± 1%    ~           (p=0.512 n=20+20)
Scan10000_Cockroach-8       32.1ms ± 1%    32.7ms ± 1%  +1.85%          (p=0.019 n=4+6)

name                      old alloc/op   new alloc/op   delta
PgbenchQuery_Cockroach-8     219kB ±12%     213kB ± 0%  -2.66%        (p=0.027 n=40+18)
[snip no changes]

name                      old allocs/op  new allocs/op  delta
PgbenchQuery_Cockroach-8     3.93k ± 8%     3.86k ± 0%  -1.82%        (p=0.012 n=40+18)
[snip no changes]
```
I added another benchmark that would insert and delete rows before timing trying to scan one, and it didn't like it either:
```
name                 old time/op    new time/op    delta
DeleteAndScan1-8        671µs ± 3%     671µs ± 1%     ~     (p=0.684 n=10+10)
DeleteAndScan10-8      2.04ms ± 1%    2.07ms ± 1%   +1.34%   (p=0.001 n=9+10)
DeleteAndScan100-8     15.1ms ± 8%    17.1ms ±13%  +13.17%   (p=0.001 n=9+10)
DeleteAndScan1000-8     158ms ± 2%     173ms ± 8%   +9.37%  (p=0.000 n=10+10)
```

**Comment by tschottdorf** [comment]
I'm assuming there were minor compactions happening? Did the benchmarks run long enough?

**Comment by simkha** [comment]
Hi,

This info could be helpful for you. I'm was studying rocksdb sources and thought I could share this little info.

The following link points to a comment in `CompactionIterator::NextFromInput()`, the comment explains when presence of `SingleDelete` would compact out (i.e. clear) the stored key and the `SingleDelete` record. This iterator is used during memtable flush. 

https://github.com/facebook/rocksdb/blob/2fc2fd92a94dba8fbad5679fce4522c4769aab27/db/compaction_iterator.cc#L227-L260

If you can adapt your code to meet the restrictions of `SingleDelete`, then I think, it could be useful.

https://github.com/facebook/rocksdb/wiki/Single-Delete

**Comment by dt** [comment]
@simkha Thanks for the tip! Filed it under #8979 to investigate that feature further.
