### ISSUE TITLE
colexec: (probably) incorrect handling of errors by hash router

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#43217]
I believe I understand the problem with why we started seeing several queries fail on `tpchvec` roachtest. The failures started happening when we introduced memory accounting to the vectorized engine.

In particular, the culprit is hash router. When hash router reaches its memory limit, an error will be emitted and `cancelOutputs(err)` is called which tells the router outputs that they are done. It currently means that they will be returning zero length batches. So here is what's happening with TPCH query 2 (and 5, and possibly others):
1. a hash router reaches it's memory limit and cancels its outputs
2. the memory error will be propagated as metadata when the flow is being drained
3. the whole flow is not canceled when OOM occurs, so the router outputs will have pushed out some of the data that should go the output and then will be emitting zero-length batches
4. as a result, an incomplete data goes through the router output, but from the perspective of the flow, it has seen all the necessary data
5. we return the results based on incomplete data as well as the trailing metadata that contains a memory error.

However, when executing a query via CLI I'm getting the memory error correctly, but for some reason when executing it via `workload run tpch` I'm getting the partial results. Any ideas why this would be the case? cc @asubiotto @jordanlewis

**Comment by asubiotto** [comment]
That's strange, so the metadata containing the error is sent and received properly by the materializer in either case? Returning a zero-batch from an output and then draining the `hashRouter` is equivalent to having the outputs panic since an outbox automatically drains the metadata sources. This is a good find. I would probably instrument the materializer to see what is being returned in the CLI vs workload case.

**Comment by yuzefovich** [comment]
I've looked into this more, and now I think there is nothing wrong with the hash router - the error is propagated as the metadata. I’m trying to understand why an error is not returned in some cases when querying via `gosql.DB.Query` and I’m confused by the following situation: it appears to me that the error is set correctly on `DistSQLReceive`r which encompasses `commandResult`, but the client doesn’t get the error. When I execute the same query through our CLI, I’m getting the error always, as expected.

**Comment by yuzefovich** [comment]
As it turns out, the problem was incorrect usage of the driver API in `tpch` workload, so this was a false alarm.

**Comment by asubiotto** [comment]
Could you describe what the incorrect usage was for posterity?

**Comment by yuzefovich** [comment]
Sure. `tpch` workload uses `gosql.DB.Query` to execute the query on CRDB. The method returns `rows, err` (1) which is the first point at which an error from DB can be returned. Then we're doing `rows.Scan` (2) to scan all the rows until `rows.Next()` returns `false`, and `Scan` also could return an error. Finally, we do `rows.Close` to clean up, and we can check `rows.Err()` (3) whether there was any "final" errors.

The workload itself while doing the step (2) was checking whether the output matches the expected results, and if not, the workload would emit an error about "wrong results." The problem is that the server was emitting computations based on partial data (i.e. it was emitting incomplete results) and only then was emitting an error which is a valid behavior according to the protocol. That error would have been see in step (3), but because we never got to that step, we were failing the test with the wrong error.

My misunderstanding was that I thought the error would have been returned in step (1). Also, only memory limit on hash router was subject to such behavior because if a memory limit was reached by any other columnar operator, the flow would shut down, and there would be no partial results streamed back to the client. Hash router is special because it is running asynchronously.
