### ISSUE TITLE
cdc: error when provided cloud sink credentials have incorrect permissions

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#43216]
**Describe the problem**

After the migration of the registration cluster to CockroachCloud, we started fresh changefeeds on the cloud cluster. Since we were migrating the cluster and needed to restore the registration cluster backups, we decided to change the IAM credentials used to create the changefeed to match those that were used to restore the backup. Previously, the changefeed process used my credentials, but we wanted to avoid using credentials tied to a user account.

Unfortunately, the IAM creds that were swapped in did not have write permissions for the S3 bucket that was being used as the cloud sink for the changefeed process. Despite this, creating the changefeed succeed although writing out to the cloud storage sink was actually silently failing.

We noticed that the `changefeed.error_retries` metrics was steadily climbing over time as the changefeed retried over and over:

![image](https://user-images.githubusercontent.com/21692034/70951158-95163100-2030-11ea-974c-a3efd2942949.png)

Once Dan pointed us in the right direction, we also found the appropriate log messages:
```
W191216 18:01:44.344156 4864895 ccl/changefeedccl/changefeed_stmt.go:525  [n2] CHANGEFEED job 512648553917808642 encountered retryable error: retryable changefeed error: failed to put s3 object: AccessDenied: Access Denied
```

**To Reproduce**

Start a changefeed using IAM credentials without write access to the specified cloud sink.

**Expected behavior**
We should (ideally) see an error if the changefeed job is unable to actually write to the specified cloud sink. We should also add the `changefeed.error_retries` to the changefeed dashboard.

**Environment:**
 - CockroachCloud
 - CockroachDB 19.2.1

cc @danhhz since we talked about this today.

Epic CRDB-2256

Jira issue: CRDB-5289

**Comment by danhhz** [comment]
I'd be nice if we could make these restarts into warnings that the user sees but that don't fail the changefeed, but like SQL there really isn't a great place to expose that right now. It's very hard and brittle to determine which errors are retryable when they come back from s3/gcs/etc.

- [ ] Ideally, we'd have caught this permissions issue before we even created the job. We make a "canary" sink to try and catch these sorts of errors, but it looks like that doesn't actually write any data. Improving our sink canary would go a long way toward helping here.

- [ ] Secondarily, it's possible that permissions change after the canary process. This was used here to actually fix the issue we saw on reg, but it's easy to imagine the opposite happening. Unsure how we should communicate that to the user, but as I mention above, I don't see a maintainable way to distinguish between retryable vs non-retryable errors coming back from various clouds. (In fact, I'd argue that a permissions issue _should_ be retryable, given that we were able to fix it here without altering the changefeed. In some sense, the system worked, we just needed better introspection to the issue.)

I've PR'd a change to add the graph of restarts into the web ui. That would have caught this much sooner. We should probably also add the metric to the list of things to watch in our production docs.
