### ISSUE TITLE
storage: 1PC txn can completely omit out the Txn

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4324]
If we have a batch of the form

```
BeginTransaction
...
EndTransaction
```

then we currently resolve all intents and GC the txn record at commit time.
But there's no reason to ever write all of this information in the first place;
we can omit the `BeginTransaction` and `EndTransaction` call, and execute
all other commands without the transaction.

There are likely a bunch of subtleties related to different handling of Txn vs
non-Txn writes, but in principle this should be possible and lead to a performance
gain in the case of single writes via SQL which should be measurable in benchmarks.

I suggest doing the benchmark first (with a hacky version of the change) and based
on that evaluating the actual change. This isn't high priority but rather logged here
as a potential future improvement.

**Comment by bdarnell** [comment]
Done in #5966
