### ISSUE TITLE
c-deps/rocksdb: building old branches on mac os catalina

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#43254]
My new laptop has catalina on it and whatever clang I got has some new warnings that cause rocksdb to fail to compile on old release branches (certainly release-19.1 tho I suspect other ones). We have the builder, so dunno how much we care about this, but it certainly made my life harder while backporting some stuff. I found a workaround in slack that involved downgrading the xcode tools, but the one that was linked is not available for catalina.

The diff that got it to work is
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index f27f48f42..476df5540 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -250,7 +250,7 @@ if(FAIL_ON_WARNINGS)
   if(MSVC)
     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /WX")
   else() # assume GCC
-    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror")
+    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror -Wno-error=shadow -Wno-error=defaulted-function-deleted")
   endif()
 endif()
```

The shadow is one looks like we should backport https://github.com/cockroachdb/cockroach/pull/39121. The other one I got from googling to work around the following error:

```
In file included from /Users/dan/crdb/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/utilities/persistent_cache/block_cache_tier.cc:7:
/Users/dan/crdb/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/utilities/persistent_cache/block_cache_tier.h:96:15: error: explicitly defaulted move assignment operator is implicitly deleted
      [-Werror,-Wdefaulted-function-deleted]
    InsertOp& operator=(InsertOp&& rhs) = default;
              ^
/Users/dan/crdb/src/github.com/cockroachdb/cockroach/c-deps/rocksdb/utilities/persistent_cache/block_cache_tier.h:103:16: note: move assignment operator of 'InsertOp' is implicitly deleted because field 'signal_' is of
      const-qualified type 'const bool'
    const bool signal_ = false;  // signal to request processing thread to exit
               ^
```

**Comment by danhhz** [comment]
@petermattis would you route this for me, please?

**Comment by petermattis** [comment]
@ajkr Were these the errors you were running into recently?

**Comment by ajkr** [comment]
They do not look like the same ones. Mine looked like the ones fixed by https://github.com/cockroachdb/rocksdb/pull/69, which isn't on 19.1 or 2.1 branches.

**Comment by petermattis** [comment]
@danhhz Do you feel strongly we should do something here? Keeping the old branches buildable against newer toolchains will be onerous. This is pretty much would the builder image is designed for.

**Comment by danhhz** [comment]
My opinion is that for as long as a release branch is supported and getting backports, it should be buildable using the version of the os that we're recommending to engineers for development. My laptop refresh came with catalina on it and rich sent out an email the other day encouraging everyone to upgrade to catalina. But, I don't feel strongly about this opinion. I agree that keeping them working against multiple toolchains (especially the c++ parts) is a hassle.

Perhaps the right thing to do is to take it on a case by case basis? I assume that we can't merge the patch I included in the issue because it'll break the builder version. Can we conditionally pass those flags based on the version of clang being used? I guess the nuclear option here is to disable treating warnings as errors. We'd never want to do that in master, but maybe it's okay for old release branches.

**Comment by petermattis** [comment]
> Can we conditionally pass those flags based on the version of clang being used?

I'm not familiar enough with cmake to know.

Cc @bobvawter and @kenliu

**Comment by petermattis** [comment]
No longer an issue now that RocksDB support has been removed.
