### ISSUE TITLE
Clarify count vs. maxRows terminology for spans and scans

### ISSUE THREAD

**Issue by JackKrupansky** [cockroachdb/cockroach#4326]
I was trying to figure out what the count field of a span was for and then I see that scans are using something called maxRows. It looks like scan.go turns a span count into a scan maxRows.

1. It would be nice to unify the terminology.
2. It would be helpful to have a comment as to whether count/maxRows is a limit on rows to visit/check vs. limit on rows to return. I presume that it is analogous to SQL LIMIT.
3. A comment on the meaning of 0 for count/maxRows would be helpful. It doesn't appear to be initialized in a span except for the case where the grouping code sets it to 1 in select.go. I presume it means no limit, but does that really mean unlimited or some internal default limit. I didn't have time to dig that deep in the code.

**Comment by petermattis** [comment]
There are warts in any implementation, including incomplete and insufficient commenting and confusing terminology. Feel free to send a PR.
