### ISSUE TITLE
interval to float/int/decimal conversion misleading for years

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#43272]
**Describe the problem**

In postgres, `select extract(epoch from '1 year')` returns the equivalent of 365.25 days in seconds (as defined by postgres source code as the `DAYS_PER_YEAR` constant).

In cockroach, we support this cast to an int/float/double, e.g. `select interval '1 year'::integer` - but this returns 365 days in seconds exactly instead. Postgres does *not* support converting intervals to integer/float/decimal. 

This was found whilst investigating #43209.

**To Reproduce**
See above.

**Expected behavior**
This is up for debate.

We should probably match postgres behaviour to return 365.25. Alternatively, should we just remove these casts as possible?

**Additional data / screenshots**
None

**Comment by otan** [comment]
@awoods187 wdyt?

**Comment by awoods187** [comment]
I think we should match Postgres. I like having casts as extra functionality. @jordanlewis thoughts?

**Comment by knz** [comment]
The cast is fine. However converting the value to float should yield the same result as pg -- with the property that `interval::float::int == interval::int` for backward compatibility.  

I would call the mismatched output for `extract` a bug but one we'll need to call out loudly in the release notes.

**Comment by knz** [comment]
Probably worth documenting as known limitation too.
