### ISSUE TITLE
UI: Break out the SQL Connections in the Metrics > SQL page to be on a per node basis

### ISSUE THREAD

**Issue by rkruze** [cockroachdb/cockroach#43298]
**Is your feature request related to a problem? Please describe.**
Currently, today the graph for SQL Connections is an aggregate for the whole cluster. Using this graph to see if there is an imbalance of connections across the nodes, you need to use the selector to select each node individually. 

**Describe the solution you'd like**
It would be best if the graph could be a stacked area graph, which would show the connections per node along with a full aggregate. Otherwise, a good starting point would be to change the default view to be on a per-node basis vs. sum.

**Comment by piyush-singh** [comment]
We should make the change to a per-node graph immediately. We are planning some charting library updates in the future, and I can make sure we include a stacked area graph as part of the requirements when we do an RFC for the change. Will prioritize this for 20.1.

**Comment by piyush-singh** [comment]
This is done!
