### ISSUE TITLE
opt: make it possible to selectively disable histogram use

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#43308]
@RaduBerinde and I were discussing the fact that it's currently not possible for users to selectively disable histograms for certain queries or tables. It's not even easy to disable histograms temporarily at the cluster level, since a user must first set `sql.stats.histogram_collection.enabled = false`, then wait for stats to be re-collected (or trigger collection manually). If a user then wants to re-enable histograms, they must set `sql.stats.histogram_collection.enabled = true`, and again wait for stats to be re-collected.

There are a couple of possible solutions to this problem, and we may want to do both:
1. Create a cluster and/or session setting `sql.stats.histogram_use.enabled` (or something like that). If disabled, it will tell the optimizer to not use histograms even if they are available.
2. Add a flag that users can specify per-table in their query, e.g., `SELECT * FROM mytable@{HIST=false}`

cc @awoods187, @andy-kimball

**Comment by awoods187** [comment]
This seems like it will be a necessary tool akin to join or index hints. Let's think more about the right way to do this.
