### ISSUE TITLE
sql: create zone config editor grant at the database level

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#43309]
Some customers require the ability to permit users who are not root to create, edit and delete zone configurations.

This ticket tracks adding a new grant at the database level called something (`ZONECONFIG`?) and adding permission checks to all places where users can create, edit or delete zone configs.

**Comment by solongordon** [comment]
@awoods187 How should this work with respect to tables? It looks like with other privileges like SELECT, if you grant privileges to a user at the database level, the privileges are automatically inherited by any new tables which are created in the database, but not by existing tables. They can later be revoked or granted at the table level if desired. (See our documentation here: https://www.cockroachlabs.com/docs/v1.0/grant.html#supported-privileges.)

It seems like the more straightforward thing to do would be to have ZONECONFIG privileges behave the same way. But that is slightly different from what is written in the original ticket, so I wanted to double-check that this is acceptable.

**Comment by RichardJCai** [comment]
@awoods187 @solongordon Adding onto Solon's comment, CREATE privilege is currently being inherited from database to new tables. Should "ZONECONFIG" act the same as CREATE in this case (with regards to allowing the user to edit the zone config)

**Comment by awoods187** [comment]
Good questions. We should sync up with the customer requesting this feature. @nstewart and I are meeting with them Wednesday and will reply back on the issue.

**Comment by nstewart** [comment]
@solongordon did you get your question answered? Which approach did you take?

**Comment by solongordon** [comment]
We made the new ZONECONFIG privilege behave the same as all our other privileges with respect to inheritance. I'm pretty confident this will meet the requirements but I'll follow up with the customer to confirm.
