### ISSUE TITLE
Anonymized usage data to collect

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#4331]
We'd like to collect (opt-in) cluster statistics to understand how CockroachDB is being used. I'd like to flush out more specifically what data we're going to collect.

Here's a starting point:

- Cluster Info
  - Cluster UUID
  - Number of databases
  - Number of tables
  - Number of users
- Node/Store Info
  - Number of nodes
  - Number of stores
  - OS
  - Hardware
    - CPU(s)
    - Memory
  - Store type
  - Version/commit hash/build flags
  - Whether certain start parameters were present (eg --insecure/dev/port)
- UI
 - We could potentially use self-hosted analytics software (eg http://piwik.org/)

**Comment by spencerkimball** [comment]
Max, for now let's send UUID and then the NodeStatus and StoreStatus structs.

The information you're suggesting here should be added to those structs as future enhancements. You shouldn't have any extra work to do.
