### ISSUE TITLE
latest Docker image tag is not latest sometimes

### ISSUE THREAD

**Issue by tyranron** [cockroachdb/cockroach#43344]
**Describe the problem**

The `latest` Docker image suddenly downgraded to 19.1 CockroachDB version, which have broken some ours staging deployments due to absence of `start-single-node` command in 19.1 versions.

**To Reproduce**

Issue may appear sporadically. This happens because sometimes `docker build` for earlier versions finishes later and the [build script pushes `latest` tag unconditionally](https://github.com/cockroachdb/cockroach/blob/bf1c7c72bb568bf51a524429ed44169bd0203ebd/build/teamcity-publish-artifacts.sh#L34-L35).

**Expected behavior**
`latest` Docker tag should point to the latest stable release.

**Additional data / screenshots**

<img width="646" alt="scc2" src="https://user-images.githubusercontent.com/7114909/71170015-fd4c5900-2262-11ea-931a-5dc9cb1e82db.png">

**Comment by tyranron** [comment]
Please retag the `latest` Docker image.

I'd like to help with fixing this, but, unfortunately, I'm not familiar with TeamCity at all and its build configuration is quite unobvious.

**Comment by jordanlewis** [comment]
Duplicate of #41067.

Thanks for pointing it out. It should be a quick fix.
