### ISSUE TITLE
sql: improve sql safe updates message for preventing non-partitioned indexes

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#43359]
A customer recently had trouble understanding the SQL safe updates warning preventing the use of a non-partitioned secondary index. They were concerned that their actions were wrong. 

Let's iterate on this message.

**Comment by solongordon** [comment]
Let's change this from an error to a NOTICE once @otan merges support for that. And also add some clarifying language about the duplicate indexes pattern.

**Comment by otan** [comment]
what's the message right now @awoods187 ?

can definitely switch to notices (should be out soon - code is written but blocked on a dependent PR)

fwiw notices will look like this (which will be more informational):
```
root@127.0.0.1:58077/defaultdb> SET experimental_enable_temp_tables = true; CREATE TEMP TABLE temp_view_test_tbl(a int); CREATE VIEW temp_view_test AS SELECT a FROM temp_view_test_tbl;
NOTICE: view "temp_view_test" will be a temporary view
CREATE VIEW

Time: 18.699ms
```

**Comment by awoods187** [comment]
```root@127.0.0.1:63221/movr> create index on rides (rider_id, revenue);
ERROR: rejected: non-partitioned index on partitioned table (sql_safe_updates = true)
SQLSTATE: 01000```

**Comment by otan** [comment]
@awoods187 what message do we want to write instead?
