### ISSUE TITLE
ui: Upgrade React version in the admin UI

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#43361]
In preparation to share components between cockroach applications, React dependencies should be upgraded to maximize compatibility. Currently (as of 19-12-2019) CockroachCloud is on `react` version `16.8.0` and Admin UI is using version `16.3.1`. Looking at the [changelog](https://github.com/facebook/react/blob/master/CHANGELOG.md) I would guess an upgrade would not be too intrusive, but part of this task will be to evaluate that.

 dep     | admin-ui | cloud
----|------|----
react | ^16.3.1 | ^16.8.0
react-dom | 16.4.2 | ^16.8.0

Also, be aware that updating the version of `react` may effect other dependencies (`react-motion`, `react-paginate`, `react-copy-to-clipboard`, etc)

**Comment by dhartunian** [comment]
This was done in #43846
