### ISSUE TITLE
ui: Upgrade Webpack to version 4

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#43362]
The main motivation here is maintenance, but our current version of `webpack` exposes us to tech debt and potentially the inability to resolve vulnerabilities. Upgrading to `webpack` version `4.x.x` will be fairly invasive and will require a number of other dependencies to be upgraded. While undertaking this upgrade, we should also endeavor to upgrade `babel-core` from current installed version `^6.24.0`  to `^7.0.0`. CockroachCloud is currently on version `7.1.3`, but looking at the [changelog](https://github.com/babel/babel/blob/master/CHANGELOG.md) we could probably go higher (the latest is currently `7.7.7`) and upgrade CockroachCloud.

(some selected dependency differences between apps)

 dep        | admin-ui | cloud
---------|------|----
webpack  | ^3.5.6 | ~4.5.0 
babel-core    | ^6.24.0 | ^7.0.0
babel-loader | ^7.1.2 | ^8.0.0-beta.6
ts-loader | ^2.3.4 | ^5.3.1

**Comment by dhartunian** [comment]
Closed by #43685
