### ISSUE TITLE
cli: improve default logging story

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#4336]
By default, `cockroach start` logs to stderr. Rather than logging everything to stderr we should log to a directory by default (e.g. `$TMPDIR`) and reconstitute something like [`--stderrthreshold`](https://github.com/golang/glog/blob/master/glog.go#L46) so that messages at `ERROR` and above to get output to stderr.

**Comment by jseldess** [comment]
Covered in **Logging Flags** section of [Cockroach Commands](https://www.cockroachlabs.com/docs/cockroach-commands.html#logging-flags).
