### ISSUE TITLE
stats: stats job can get stuck and block all other stats jobs

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#43375]
We have seen that it is possible for an automatic statistics job to get "stuck" in the pending state, so that it remains in the jobs table indefinitely and never completes. This is a problem, because it prevents other automatic stats jobs from running.

It seems like this may be due to a limitation within the jobs infrastructure, which is that if a job is orphaned while it is in the pending state, it will not be adopted. This has actually already been fixed in master (#42880), but that change has not been backported to 19.1 or 19.2. 

I think we may want to consider backporting it (cc @spaskob), but if that's not an option, we could add some sort of orphan check for automatic stats jobs. If a job has not completed after, say, a week, we should just cancel the job. I don't think we should need the orphan check if we backport #42880.

**Comment by awoods187** [comment]
@lucy-zhang for awareness too

**Comment by rytaft** [comment]
Based on offline discussion with @spaskob, he will backport #42880.

**Comment by rytaft** [comment]
#43416 and #43421 have been merged to backport this fix. They will be included in the next patch releases for 19.1 and 19.2.
