### ISSUE TITLE
cli: improve initial `cockroach start` output

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#4337]
`cockroach start` should output a handful of terse lines when it starts (as compared to the log messages it currently produces, see #4336). The info we should be providing is:

* The logging directory.
* The store directories.
* The admin UI URL.
* The postgres URL.

Something along the lines of:

```
~ cockroach start
admin:    http://localhost:26257
postgres: postgresql://localhost:15432
logdir:   /var/tmp/foo/bar
stores:   ./cockroach-data
```

**Comment by jseldess** [comment]
Covered in `[cockroach start`](https://www.cockroachlabs.com/docs/start-a-node.html) docs and in [Start a Local Cluster](https://www.cockroachlabs.com/docs/start-a-local-cluster.html).
