### ISSUE TITLE
storage: replacing engine.NewReadOnly with engine.NewBatch causes test failures

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#43406]
See https://github.com/cockroachdb/cockroach/pull/43388. Replacing `engine.NewReadOnly` with `engine.NewBatch` in the replica read code path caused test failures. They should be equivalent for read-only operations. I'm not sure if there are existing bugs due to this behaviour.

**Comment by petermattis** [comment]
@irfansharif Not sure when we'll get to this. Do you have an example of a test that failed?

**Comment by irfansharif** [comment]
[Here](https://teamcity.cockroachdb.com/viewLog.html?buildId=1656729&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests) is the build that failed. I'm not blocked on this or anything.

Screenshot for when the link rots:

<img width="466" alt="image" src="https://user-images.githubusercontent.com/10536690/71278020-71026a80-2324-11ea-9e83-4b7973d17037.png">

**Comment by petermattis** [comment]
@irfansharif Thanks!

**Comment by petermattis** [comment]
Some of the failures are due to `rocksDBBatch` not implementing `ExportToSst`. This sounds correct: I don't think `rocksDBBatch` should implement that method. Still working through the other failures.

**Comment by petermattis** [comment]
The `Test{Txn,DB}_ReverseScan` failures are due to RocksDB batches not supporting reverse scans.

**Comment by petermattis** [comment]
The lack of reverse scans also causes GC to fail.

Fun: Pebble supports reverse scans on batches. `Test{Txn,DB}_ReverseScan` work correctly on Pebble when using batches for read-only KV operations.

**Comment by petermattis** [comment]
The `pkg/server` failures also look to be due to the lack of reverse scan support on batches. Those tests also pass on Pebble. I've looked at enough that I think these failures are all expected and fallout from semantics of RocksDB batches.
