### ISSUE TITLE
Memory leak on 3-node cluster

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#4346]
Run the examples-go/loadgen against a 3-node cluster
The memory consumption of the cluster will increase without bound

I've also seen the memory leak persist after load has stopped, with the cluster remaining mostly quiescent.

**Comment by petermattis** [comment]
A little memory profiler action while this is happening should at least reveal where the memory is going.

**Comment by nvanbenschoten** [comment]
See #4367. It looks like this issue was being caused by enormous amounts of `time.Timer` allocations. This was caused by timer creation during every iteration of a couple of tight loops. #4175 proposed a fix for the worst offender of this issue, and #4367 fixes a few other instances that were showing up during memory profiling.

**Comment by JackKrupansky** [comment]
Are these timer allocations that the Go GC would eventually have reclaimed
and you just didn't wait long enough for the GC to occur, or was there
something that was preventing Go from reclaiming the old timers or maybe GC
wasn't keeping up with the rate of creation? Just curious, trying to
understand Go better.

-- Jack Krupansky

**Comment by nvanbenschoten** [comment]
Looking more intro this, and running the example load generator with more users to create higher contention within the key space, I'm seeing a huge amount of memory (roughly 1GB per node) allocated [here](https://github.com/cockroachdb/cockroach/blob/master/storage/command_queue.go#L94). Again, this doesn't look like a memory leak, but it does look like an area where a tremendous amount of memory is being allocated, especially during high contention situations.

I'm not exactly sure what the best fix for this would be. One idea would be to [pool](https://golang.org/pkg/sync/#Pool) these pending WaitGroup slices within the CommandQueue, to avoid continually creating and extending them as contention builds and more `cmd`s are added and processed. I'm going to look into the effect of this approach, as well as look for alternative remedies.

**Comment by spencerkimball** [comment]
I'm closing this for now. Will reopen if/when I find a memory leak with quiescent cluster.
