### ISSUE TITLE
roachprod: make it possible to specify how many hosts are in each zone when creating a cluster

### ISSUE THREAD

**Issue by rkruze** [cockroachdb/cockroach#43499]
**Is your feature request related to a problem? Please describe.**
Currently, roachprod evenly distributes out the number of nodes across the zones specified at cluster creation. Sometimes this doesn't line up with what customers are deploying and it would be nice to be able to deploy a cluster into a similar fashion. 

**Describe the solution you'd like**
Ability to specify how the nodes are deployed across the zones, for at least one cloud provider.

**Comment by ajwerner** [comment]
@rkruze from https://github.com/cockroachdb/cockroach/pull/43500#issuecomment-570630348

> I do find having to list out each zone for each node to be onerous and not something that is intuitive.

I'm happy to help work through better UX for this. One issue I have with a map-like approach is that it isn't ordered. The explicit listing of the zones implies how the node ID should map to the zone. If we come up with a UX we like we can make it work on all of the providers.

**Comment by rkruze** [comment]
How about something like `roachprod create roko-test --clouds aws -n 65 --geo --aws-zones us-east-2a:15,us-east-2b:15,us-east-1a:15,us-east-1b:10,us-west-2a:10`?

**Comment by ajwerner** [comment]
> How about something like `roachprod create roko-test --clouds aws -n 65 --geo --aws-zones us-east-2a:15,us-east-2b:15,us-east-1a:15,us-east-1b:10,us-west-2a:10`?

Works for me. PR inbound.
