### ISSUE TITLE
ui: display prominent warning when cluster is unreachable

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#4349]
Start a local dev cluster using `cockroach start --dev`. Visit the admin UI page. Now kill the cluster. The UI will eventually display a whole bunch of "No Data Available" messages, but it doesn't give a strong and clear indication that the cluster is unreachable.

**Comment by maxlang** [comment]
This could probably be more "prominent" but https://github.com/cockroachdb/cockroach/pull/4952 at least adds a warning.
