### ISSUE TITLE
deadloop between InternalRangeLookup and  InternalPushTxn request

### ISSUE THREAD

**Issue by yananzhi** [cockroachdb/cockroach#435]
If a transaction modify the metadata of a range, it may  lead a deadloop between InternalRangeLookup and  InternalPushTxn request.When a request was send to a range which metadata was modified in the transaction, the dist_sender may call a InternalRangeLookup request to get the metadata of range, when the InternalRangeLookup execute on the range, it will genete a WriteIntend error because a read-write conflict,the store will send a InternalPushTxn request to push the txn, the dist_sender will send a same InternalRangeLookup to route the InternalPushTxn request,this is a deadloop.

Use the engine.MVCCIterateCommitted instead of the engine.MVCCScan in the InternalRangeLookup method of range can solve the problem,but if a transaction modified the metadata of range committed but forget clean the intent of the range metadata,engine.MVCCIterateCommitted will never get the new updated data.so InternalRangeLookup can use the engine.MVCCScan to get the data, if error occur,try engine.MVCCIterateCommitted.

func(r*Range)InternalRangeLookup(batchengine.Engine,args*proto.InternalRangeLookupRequest,reply*proto.InternalRangeLookupResponse){
    iferr:=engine.ValidateRangeMetaKey(args.Key);err!=nil{
        reply.SetGoError(err)
        return
    }
    rangeCount:=int64(args.MaxRanges)
    ifrangeCount<1{
        reply.SetGoError(util.Errorf(
            "Rangelookupspecifiedinvalidmaximumrangecount%d:mustbe>0",rangeCount))
        return
    }
    //Wewanttosearchforthemetadatakeyjustgreaterthanargs.Key.Scan
    //forboththerequestedkeyandthekeysimmediatelyafterwards,upto
    //MaxRanges.
    metaPrefix:=proto.Key(args.Key[:len(engine.KeyMeta1Prefix)])
    nextKey:=proto.Key(args.Key).Next()
    kvs,err:=engine.MVCCScan(batch,nextKey,metaPrefix.PrefixEnd(),rangeCount,args.Timestamp,args.Txn)
    iferr!=nil{
        kvs=[]proto.KeyValue{}
        if_,ok:=err.(*proto.WriteIntentError);ok{
            kvs:=[]proto.KeyValue(nil)
            iferr:=engine.MVCCIterateCommitted(batch,nextKey,metaPrefix.PrefixEnd(),func(kvproto.KeyValue)(bool,error){
                kvs=append(kvs,kv)
                ifrangeCount!=0&&rangeCount==int64(len(kvs)){
                    returntrue,nil
                }
                returnfalse,nil
            });err!=nil{
                reply.SetGoError(err)
                return
            }
        }
    }

**Comment by spencerkimball** [comment]
Here's that source code reformatted:

    func (r *Range) InternalRangeLookup(batch engine.Engine, args proto.InternalRangeLookupRequest, reply proto.InternalRangeLookupResponse) {
    	if err := engine.ValidateRangeMetaKey(args.Key); err != nil {
    		reply.SetGoError(err)
    		return
    	}
    	rangeCount := int64(args.MaxRanges)
    	if rangeCount > 0 {
    		reply.SetGoError(util.Errorf(
    			"Rangelookupspecifiedinvalidmaximumrangecount%d:mustbe>0", rangeCount))
    		return
    	}
    	// We want to search for the metadata key just greater than
    	// args.Key. Scan for both the requested key and the keys
    	// immediately afterwards, up to MaxRanges.
    	metaPrefix := proto.Key(args.Key[:len(engine.KeyMeta1Prefix)])
    	nextKey := proto.Key(args.Key).Next()
    	kvs, err := engine.MVCCScan(batch, nextKey, metaPrefix.PrefixEnd(), rangeCount, args.Timestamp, args.Txn)
    	if err != nil {
    		kvs = []proto.KeyValue{}
    		if _, ok := err.(proto.WriteIntentError); ok {
    			kvs := []proto.KeyValue(nil)
    			if err := engine.MVCCIterateCommitted(batch, nextKey, metaPrefix.PrefixEnd(), func(kvproto.KeyValue) (bool, error) {
    				kvs = append(kvs, kv)
    				if rangeCount != 0 && rangeCount == int64(len(kvs)) {
    					return true, nil
    				}
    				return false, nil
    			}); err != nil {
    				reply.SetGoError(err)
    				return
    			}
    		}
    	}
    }

**Comment by yananzhi** [comment]
I think more ,if there has a uncleared intent, the code is not worked, it can't push the txn, so just use  
engine.MVCCIterateCommitted replace the engine.MVCCScan, some one has better idea to solve the dead loop problem?

func (r *Range) InternalRangeLookup(batch engine.Engine, args *proto.InternalRangeLookupRequest, reply *proto.InternalRangeLookupResponse) {
	if err := engine.ValidateRangeMetaKey(args.Key); err != nil {
		reply.SetGoError(err)
		return
	}

	rangeCount := int64(args.MaxRanges)
	if rangeCount < 1 {
		reply.SetGoError(util.Errorf(
			"Range lookup specified invalid maximum range count %d: must be > 0", rangeCount))
		return
	}

	// We want to search for the metadata key just greater than args.Key. Scan
	// for both the requested key and the keys immediately afterwards, up to
	// MaxRanges.
	metaPrefix := proto.Key(args.Key[:len(engine.KeyMeta1Prefix)])
	nextKey := proto.Key(args.Key).Next()

	kvs := []proto.KeyValue(nil)
	if err := engine.MVCCIterateCommitted(batch, nextKey, metaPrefix.PrefixEnd(), func(kv proto.KeyValue) (bool, error) {

		kvs = append(kvs, kv)
		if rangeCount != 0 && rangeCount == int64(len(kvs)) {
			return true, nil
		}
		return false, nil
	}); err != nil {
		reply.SetGoError(err)
		return
	}
	//	kvs, err := engine.MVCCScan(batch, nextKey, metaPrefix.PrefixEnd(), rangeCount, args.Timestamp, args.Txn)
	//	if err != nil {
	//		reply.SetGoError(err)
	//		return
	//	}

	// The initial key must have the same metadata level prefix as we queried.
	if len(kvs) == 0 {
		// At this point the range has been verified to contain the requested
		// key, but no matching results were returned from the scan. This could
		// indicate a very bad system error, but for now we will just treat it
		// as a retryable Key Mismatch error.
		err := proto.NewRangeKeyMismatchError(args.Key, args.EndKey, r.Desc())
		reply.SetGoError(err)
		log.Errorf("InternalRangeLookup dispatched to correct range, but no matching RangeDescriptor was found. %s", err)
		return
	}

	// Decode all scanned range descriptors, stopping if a range is encountered
	// which does not have the same metadata prefix as the queried key.
	rds := make([]proto.RangeDescriptor, len(kvs))
	for i := range kvs {
		if err := gogoproto.Unmarshal(kvs[i].Value.Bytes, &rds[i]); err != nil {
			reply.SetGoError(err)
			return
		}
	}

	reply.Ranges = rds
	return
}

**Comment by spencerkimball** [comment]
Thanks for pointing out this issue. It's a doozy.

I reproduced it with a unittest and have been weighing the possible solutions. I think this is a great opportunity to also address Issue #343 . Range lookups should be done with read consistency set to INCONSISTENT. We allow any replica to service such reads and they blithely skip intents, so will solve this deadloop issue and also add this missing piece of functionality.
