### ISSUE TITLE
sql: `INSERT ... RETURNING` should accept qualified names

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#4351]
This test (to be added to `testdata/insert`) currently fails with `qualified name "return.a" not found`.

```
# Return a qualified name
query I
INSERT INTO return VALUES (default) RETURNING return.a
----
3
```

(The Django ORM likes to issue queries of this form)

**Comment by RaduBerinde** [comment]
@mjibson was working on this
