### ISSUE TITLE
cli: remove --dev mode

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#4352]
Once #4269 goes in, the only remaining reason for `--dev` mode is to automatically configure a memory store. I think we should encourage developers (primarily ourselves) to use a disk store instead. See also #4335. Using a disk store during ad-hoc testing is closer to how cockroach will be used in production and will possibly reveal bugs that are not present when always starting from a clean slate.

**Comment by tamird** [comment]
There is at least one other reason for `--dev` which I proposed [here](https://github.com/cockroachdb/cockroach/issues/1008#issuecomment-183461937).

**Comment by petermattis** [comment]
The discussion in #4269 proposes to make listening on only localhost the default unless `--insecure` or `--{cert,key}-file` are specified. I think that covers your proposed usage. Effectively, the lack of `--insecure` or `--{cert,key}-file` causes a server to be in dev-mode.

**Comment by tamird** [comment]
OK, I think that can work.

**Comment by petermattis** [comment]
Fixed by #4453.
