### ISSUE TITLE
colexec: incorrect type assumptions of CASE operator in some cases

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#43550]
Extracted from https://github.com/cockroachdb/cockroach/issues/43457#issuecomment-569002516

The following interaction
```
root@:26257/defaultdb> create table t(a int2 primary key);
CREATE TABLE

Time: 4.583ms

root@:26257/defaultdb> insert into t values (1);
INSERT 1

Time: 4.326ms

root@:26257/defaultdb> set vectorize_row_count_threshold=0;
SET

Time: 467µs

root@:26257/defaultdb> select case when a = 0 then a else 1:::INT8 end from t;
```
produces an internal error:
```
ERROR: internal error: unexpected error from the vectorized runtime: interface conversion: coldata.column is []int64, not []int16
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/colexec/execerror/error.go:70: func1()
runtime/panic.go:679: gopanic()
runtime/iface.go:255: panicdottypeE()
github.com/cockroachdb/cockroach/pkg/col/coldata/vec.go:194: Int16()
github.com/cockroachdb/cockroach/pkg/col/coldata/vec.eg.go:501: Copy()
github.com/cockroachdb/cockroach/pkg/sql/colexec/allocator.go:118: func1()
github.com/cockroachdb/cockroach/pkg/sql/colexec/allocator.go:90: performOperation()
github.com/cockroachdb/cockroach/pkg/sql/colexec/allocator.go:118: Copy()
github.com/cockroachdb/cockroach/pkg/sql/colexec/case.go:204: Next()
...
```
The problem here is that `CASE` operator has the output column with type `INT2`, but in `ELSE` case we explicitly asked for conversion to `INT8`. The output of `EXPLAIN (TYPES)` shows that `INT2` output type is expected.

Here is `EXPLAIN (VEC)`:
```
  └ Node 1                                
    └ *colexec.caseOp                     
      ├ *colexec.bufferOp                 
      │ └ *colexec.colBatchScan           
      ├ *colexec.projEQInt16Int64ConstOp  
      │ └ *colexec.bufferOp               
      └ *colexec.constInt64Op             
        └ *colexec.bufferOp
```

I'm actually not quite sure what is the correct way to fix this. Possibly we could plan casts to the case's output type in all `WHEN` and `ELSE` arms (when needed). cc @jordanlewis thoughts?

**Comment by jordanlewis** [comment]
Yeah, we will need to plan casts for now. Really the optimizer/typechecker should be doing this though.

In general, CASE should require that all arms have the same output type. That includes width. cc @otan - this is related to the type system overhaul. We correctly constrain CASE outputs to be the same type family, but really we need the outputs to be identical in other attributes as well, like width.
