### ISSUE TITLE
sql: Unimplemented SQL should not panic

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#4355]
It's currently trivial to kill the server by sending a SQL statement we don't implement (`ALTER TABLE tbl ADD CONSTRAINT ...`). We need to replace the `panic("TODO(pmattis): unimplemented")` in `sql.y` with a softer approach to error handling.

**Comment by petermattis** [comment]
We could comment out all of the rules which refer to `unimplemented()`. Then we'd get parse errors instead of panics. The downside is that these rules might rot, but that doesn't seem too problematic as our grammar isn't changing that quickly.
