### ISSUE TITLE
kvserver: invalid Raft truncation decision panic in cli unittests

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#43605]
I got a scary panic in the cli unittests:
```
panic: invalid truncation decision; output = 54, input: [54, 53], commit idx = 53 [recovered]
	panic: invalid truncation decision; output = 54, input: [54, 53], commit idx = 53
```
I guess what's invalid about it is that we truncate below the commit idx?

This was when I was running a `testshort` across all the packages on my laptop - so high load. I couldn't repro easily by stressing the CLI package.

Logs for the package:
https://gist.github.com/andreimatei/bd59d82032d6639951cb61724894b407

cc @nvanbenschoten @tbg @ajwerner

**Comment by nvanbenschoten** [comment]
@irfansharif do you mind taking a look at this? It likely has something to do with https://github.com/cockroachdb/cockroach/pull/43314.

**Comment by irfansharif** [comment]
Weird. Looking at `input: [54, 53]`, which is printing out `input: [input.FirstIndex, input.LastIndex]`, we see that `input.FirstIndex > input.LastIndex` (`FirstIndex` is the oldest raft entry, I keep having to re-learn this).

**Comment by irfansharif** [comment]
#43314 was a PR to the `release-2.1` branch. #43136 is what likely surfaced this, but it may be because it's no longer protecting against this particular case of malformed input.

**Comment by irfansharif** [comment]
Hm, I think I found something. When accepting snapshots, we persist them atomically [here](https://github.com/cockroachdb/cockroach/blob/e92a5b167b490daee0043dd1de63ae95d74f47e3/pkg/storage/replica_raftstorage.go#L923-L925). This includes the HardState/truncated state, which is something that gets used when computing FirstIndex during log truncations ([here](https://github.com/cockroachdb/cockroach/blob/e92a5b167b490daee0043dd1de63ae95d74f47e3/pkg/storage/replica_raftstorage.go#L324-L331)). The other piece of information needed in log truncations is the LastIndex, which we retrieve from `r.mu.lastIndex` [here](https://github.com/cockroachdb/cockroach/blob/e92a5b167b490daee0043dd1de63ae95d74f47e3/pkg/storage/raft_log_queue.go#L179). Jumping back to the snapshot application code, the update made to `r.mu.lastIndex` is not done atomically with the persisting of the HardState. See [here](https://github.com/cockroachdb/cockroach/blob/e92a5b167b490daee0043dd1de63ae95d74f47e3/pkg/storage/replica_raftstorage.go#L955-L962). 

If I'm understanding all of the above correctly, it's possible for a replica to receive a snapshot that persists a new hard state, this would be reflected in all future responses from `replica.raftFirstIndexLocked`. Before being able to update `r.mu.lastIndex` however (to reflect the applied state of the received snapshot), a log truncation decision could be made with the new `FirstIndex` and the stale `LastIndex`. This could then in turn cause the panic observed above.

**Comment by nvanbenschoten** [comment]
That theory does sound plausible. It's interesting that we'd even be trying to make a truncation decision while receiving a snapshot in the first place. I'm not aware of any reason why we'd try to prevent that though, given that the raftLogQueue doesn't require the lease (not that even that would prevent it in call cases).

I'd suggest continuing with this idea and trying to reproduce this panic. Does a well-timed call to `raftLogQueue.MaybeAdd` during snapshot ingestion hit it?

**Comment by irfansharif** [comment]
My theory is a bit more unlikely than I'd first thought (though might still be plausible?). Currently only leader replicas can make log truncation decisions. As per the theory above, a replica would have to:

a. Accept an incoming snapshot, i.e. as a follower
b. Compute a log truncation decision, i.e. as a leader

Given the small window of time (between a an b), I'm guessing it's unlikely for a full leadership election to have taken place.

**Comment by irfansharif** [comment]
Looking at `input: [54, 53]` again, `input.FirstIndex == input.LastIndex + 1`. We have an [allowance](https://github.com/cockroachdb/cockroach/blob/e92a5b167b490daee0043dd1de63ae95d74f47e3/pkg/storage/raft_log_queue.go#L466-L474) for uninitialized replicas where it's possible for `FirstIndex` to exceed `LastIndex`, and this looks awfully similar. For uninitialized replicas it's possible for there to be a `HardState` persisted and then have the replica compute a truncation decision. What's happening here is probably similar in that the replica computing the log truncation decision is doing so knowing _just_ the persisted `HardState` (i.e. no other entries were added). This would make it possible for us to have `FirstIndex == LastIndex + 1`. 

@nvanbenschoten: Is this a valid thread to pull on?

**Comment by andreimatei** [comment]
Happened to me again.
```
panic: invalid truncation decision; output = 50, input: [50, 49], commit idx = 51 [recovered]
	panic: invalid truncation decision; output = 50, input: [50, 49], commit idx = 51
```

I wasn't stressing anything, so seems reproducible.

**Comment by andreimatei** [comment]
I also got it stressing `TestReplicateQueueRebalance` on a GCE worker.

**Comment by irfansharif** [comment]
How long did it take you? No bueno for me.

```
$ make stress PKG=./pkg/storage TESTS=TestReplicateQueueRebalance
...
5893 runs so far, 0 failures, over 15m50s
5923 runs so far, 0 failures, over 15m55s
5956 runs so far, 0 failures, over 16m0s
```

**Comment by irfansharif** [comment]
Captured it once: https://gist.github.com/irfansharif/427c60e56d2e453032aa2c8d03d615bf

**Comment by ajwerner** [comment]
`make roachprod-stress` is a powerful tool.

**Comment by irfansharif** [comment]
yea, was running that too. It takes a while to repro through this particular test it seems.

**Comment by irfansharif** [comment]
Started looking at this again today. I don't have a smoking gun yet but I'm pretty sure here's what's happening.

(a) During splits, when we're initializing the RHS below, we can find ourselves looking at the truncated state (if any) to determine what `r.mu.lastIndex` should be.
 https://github.com/cockroachdb/cockroach/blob/691086cf42b5a44c2c3e8524500e818f48eec255/pkg/kv/kvserver/store_split.go#L233
https://github.com/cockroachdb/cockroach/blob/691086cf42b5a44c2c3e8524500e818f48eec255/pkg/kv/kvserver/replica_init.go#L152

(b) If the store is also concurrently receiving a snapshot for the RHS range, it uses the truncated state in the snapshot and persists it to disk.
https://github.com/cockroachdb/cockroach/blob/691086cf42b5a44c2c3e8524500e818f48eec255/pkg/kv/kvserver/replica_raftstorage.go#L851-L852

If a replica has no log entries, and only has a truncated state to refer to, it considers its first index to be truncated state index + 1 https://github.com/cockroachdb/cockroach/blob/691086cf42b5a44c2c3e8524500e818f48eec255/pkg/kv/kvserver/replica_raftstorage.go#L330

(It also considers it's last index to be just the truncated state, as linked above).

---

Looking at the panics seen:
```
panic: invalid truncation decision; output = 50, input: [50, 49], commit idx = 51 [recovered]
	panic: invalid truncation decision; output = 50, input: [50, 49], commit idx = 51
```

It seems our `input` is malformed in that first index > last index. I'm almost certain if we attempt to truncate the log of a newly formed RHS range that just so happened to be initialized following a snapshot that persisted a truncated state, we'd hit this panic. (I'm learning how surprising difficult it is to assert on what I figured would be "obvious" invariants.)

**Comment by knz** [comment]
I have a created a fairly reliable repro for this error in a roachtest.

Here's the code:
```go
// runManyRangesAcceptance attempts to create 2000 tiny ranges on a
// 4-node cluster using left-to-right splits and check the cluster is
// still live afterwards.
func runManyRangesAcceptance(ctx context.Context, t *test, c *cluster) {
        args := startArgs("--env=COCKROACH_SCAN_MAX_IDLE_TIME=5ms")
        c.Put(ctx, cockroach, "./cockroach")
        c.Start(ctx, t, args)

        // Wait for upreplication then create many ranges.
        func() {
                db := c.Conn(ctx, 1)
                defer db.Close()

                err := retry.ForDuration(30*time.Second, func() error {
                        t.l.Printf("waiting for up-replication\n")
                        row := db.QueryRowContext(ctx, `SELECT min(array_length(replicas, 1)) FROM crdb_internal.ranges_no_leases`)
                        minReplicas := 0
                        if err := row.Scan(&minReplicas); err != nil {
                                t.Fatal(err)
                        }
                        if minReplicas < 3 {
                                time.Sleep(time.Second)
                                return errors.Newf("some ranges not up-replicated yet")
                        }
                        return nil
                })
                if err != nil {
                        t.Fatalf("cluster did not up-replicate: %v", err)
                }

                const numRanges = 2000
                t.l.Printf("creating %d ranges...", numRanges)
                if _, err := db.ExecContext(ctx, fmt.Sprintf(`
CREATE TABLE t(x, PRIMARY KEY(x)) AS TABLE generate_series(1,%[1]d);
ALTER TABLE t SPLIT AT TABLE generate_series(1,%[1]d)`, numRanges)); err != nil {
                        t.Fatal(err)
                }
        }()

        for nodeID := 1; nodeID <= c.spec.NodeCount; nodeID++ {
                t.l.Printf("checking node %d is live\n", nodeID)
                func() {
                        db := c.Conn(ctx, nodeID)
                        defer db.Close()
                        if _, err := db.Exec(`SELECT 1`); err != nil {
                                t.Fatal(err)
                        }
                }()
        }
}
```

How to use:

1. add the fn to `acceptance.go` with some name (I use `many-ranges`)
2. run with `roachtest run --local --debug acceptance/many-ranges` (or the name you chose)

if you monitor the cockroach log on node 1 (which is receiving the split requests) you'll detect at some point it starts to fail connecting to one of the other nodes (grpc error) - that's because the node crashed with the bug investigated here.

If there's no error, just restart the roachtest. It fails reliably 2/3rds of the attempts on my machine.

**Comment by irfansharif** [comment]
Raphael, thanks for the fast repro! That helped me confirm my theory from earlier. Adding a bit of logging I see the following:

```
I200406 21:00:33.362381 135553 kv/kvserver/replica_raftstorage.go:780  [n3,s3,r695/2:{-}] applying RAFT snapshot [id=fe3bc918 index=18]
W200406 21:00:33.362459 135553 kv/kvserver/replica_raftstorage.go:851  [n3,s3,r695/2:{-}] persisting truncated state: index:18 term:6
I200406 21:00:33.375036 135553 kv/kvserver/replica_raftstorage.go:801  [n3,s3,r695/2:/Table/52/1/64{2-3}] applied RAFT snapshot [total=13ms ingestion=4@9ms id=fe3bc918 index=18]

...

panic: r695: invalid truncation decision; output = 19, input: [19, 18/18], commit idx = 18 [recovered]
  panic: r695: invalid truncation decision; output = 19, input: [19, 18/18], commit idx = 18
```

Which seems to line up exactly with what I described in https://github.com/cockroachdb/cockroach/issues/43605#issuecomment-607543473. We're computing the truncation decision for a range with no log entries.
