### ISSUE TITLE
sql: Consider adding `TIMESTAMP WITH TIME ZONE` type

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#4361]
In python, `datetime` objects may or may not have a time zone associated, and the postgres driver `psycopg2` will use either `TIMESTAMP` or `TIMESTAMPTZ` (an alias for `TIMESTAMP WITH TIME ZONE`) types depending on the values passed. We do not support the `WITH TIME ZONE` types, which means that python apps will have to be careful to avoid `datetime` objects with time zones (this may be doable in a few central locations, e.g. in the Django adapter I'm working on), but we'd have better out-of-the-box compatibility if we supported the `WITH TIME ZONE` types.

**Comment by dt** [comment]
Implemented by #6165
