### ISSUE TITLE
Storing index not chosen despite significant performance difference

### ISSUE THREAD

**Issue by jrupac** [cockroachdb/cockroach#43610]
**What is your situation?**

Select all that apply:

- **is there a difference between the performance you expect and the performance you observe?**
- **are you surprised by your performance results?**

I expected that using a storing index that covers the field in the `SELECT` clause would get used during query execution, but it is not. Forcing the index to be used gives a ~50x speedup. (more details below).

I think this is conceptually similar to https://github.com/cockroachdb/cockroach/issues/35451, which was closed after the user disabled CBO. I think that is no longer even an option in the latest release? 

***

**Observed performance**

What did you see? How did you measure it?

I am running on v19.2.2:

```bash
$ cockroach version
Build Tag:    v19.2.2
Build Time:   2019/12/11 01:33:43
Distribution: CCL
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.12.12
C Compiler:   gcc 6.3.0
Build SHA-1:  3cbd05602d4aeaebbccea18d66ad0fdf8db482a5
Build Type:   release
```

I have a table with the following schema:

```sql
> show create table folder;
  table_name |                                   create_statement                                     
+------------+---------------------------------------------------------------------------------------+
  folder     | CREATE TABLE folder (                                                                  
             |     userid UUID NOT NULL,                                                              
             |     id INT8 NOT NULL DEFAULT unique_rowid(),                                           
             |     name STRING NULL,                                                                  
             |     CONSTRAINT "primary" PRIMARY KEY (userid ASC, id ASC),                             
             |     CONSTRAINT fk_userid_ref_usertable FOREIGN KEY (userid) REFERENCES usertable(id),  
             |     UNIQUE INDEX folderwithid_id_key (id ASC),                                         
             |     UNIQUE INDEX folderwithid_name_key (name ASC),                                     
             |     INDEX folder_userid_idx (userid ASC) STORING (name),                               
             |     FAMILY "primary" (userid, id, name)                                                
             | ) INTERLEAVE IN PARENT usertable (userid)
```

I run a query as so:

```sql
> select name from folder where userid='bc609884-4f32-4054-bf17-dd5cbf1ca226';                  
          name          
+----------------------+
  <root>                
  Comics                
  Personal Development  
  Google                
  News                  
  Programming           
  JetBrains             
(7 rows)

Time: 75.522789ms
```
This query seems to use only the primary index:

```sql
root@:26257/goliath> explain (verbose) select name from folder where userid='bc609884-4f32-4054-bf17-dd5cbf1ca226';                  
    tree    |    field    |                                                   description                                                   |    columns     | ordering  
+-----------+-------------+-----------------------------------------------------------------------------------------------------------------+----------------+----------+
            | distributed | false                                                                                                           |                |           
            | vectorized  | false                                                                                                           |                |           
  render    |             |                                                                                                                 | (name)         |           
   │        | render 0    | name                                                                                                            |                |           
   └── scan |             |                                                                                                                 | (userid, name) |           
            | table       | folder@primary                                                                                                  |                |           
            | spans       | /"\xbc`\x98\x84O2@T\xbf\x17\xdd\\\xbf\x1c\xa2&"/#/197/1-/"\xbc`\x98\x84O2@T\xbf\x17\xdd\\\xbf\x1c\xa2&"/#/197/2 |                |           
(7 rows)

```

It does not use the manually created `folder_userid_idx` which is an index on `userid` storing `name`, despite that being exactly what is queried for. Forcing this index use gives a big speed-up, as expected:

```sql
root@:26257/goliath> select name from folder@folder_userid_idx where userid='bc609884-4f32-4054-bf17-dd5cbf1ca226';                  
          name          
+----------------------+
  <root>                
  Comics                
  Personal Development  
  Google                
  News                  
  Programming           
  JetBrains             
(7 rows)

Time: 1.984218ms
```
(Compare 75ms to 1.9ms).

Here is `EXPLAIN` on the forced index query:

```sql
root@:26257/goliath> explain (verbose) select name from folder@folder_userid_idx where userid='bc609884-4f32-4054-bf17-dd5cbf1ca226';    
    tree    |    field    |                                                description                                                |    columns     | ordering  
+-----------+-------------+-----------------------------------------------------------------------------------------------------------+----------------+----------+
            | distributed | false                                                                                                     |                |           
            | vectorized  | false                                                                                                     |                |           
  render    |             |                                                                                                           | (name)         |           
   │        | render 0    | name                                                                                                      |                |           
   └── scan |             |                                                                                                           | (userid, name) |           
            | table       | folder@folder_userid_idx                                                                                  |                |           
            | spans       | /"\xbc`\x98\x84O2@T\xbf\x17\xdd\\\xbf\x1c\xa2&"-/"\xbc`\x98\x84O2@T\xbf\x17\xdd\\\xbf\x1c\xa2&"/PrefixEnd |                |           
```

If you have already ran tests, include your test details here:

- which test code do you use?
- which SQL queries? Schema of supporting tables?
- how many clients per node?
- how many requests per client / per node?

**I don't have any tests for this, but some of this is covered by the details above.**

***

**Application profile**

Performance depends on the application. Please help us understand how you use CockroachDB before we can discuss performance.

- Have you used other databases before? Or are you considering a migration? Please list your previous/other databases here.

**This is a standalone project that was built only on CockroachDB.**

- What is the scale of the application?
  
  - how many columns per table?

**The table in question has 3 columns (two are part of the primary key, the third is unique).**

  - how many rows (approx) per table?

**The table in question has 7 rows.**

  - how much data?

**Very small, just storing a tiny amount of data per cell.**

  - how many clients? Requests / second?

**Only one client on a single node instance, but requests are sent by concurrent gorountines. It's still very small, about 1QPS maybe.**

- What is the query profile?
  - is this more a OLTP/CRUD workload? Or Analytics/OLAP? Is this hybrid/HTAP?
  - what is the ratio of reads to writes?
  - which queries are grouped together in transactions?

- What is the storage profile?
  - how many nodes?
  - how much storage?
  - how much data?
  - replication factor?

**I'll skip this section for the purposes of this issue, but happy to add more details here if requested.**

***

**Requested resolution**

When/how would you consider this issue resolved? 

**I'd like to understand more about this index selection and what I am doing incorrectly. I know I can just force the index usage to workaround this, but I'd prefer to have the right choice be made automatically.**

Select all that applies:

- **I mostly seek information: data, general advice, clarification.**

**Comment by RaduBerinde** [comment]
Hello and Happy New Year!

The primary index is on columns `userid, id` so it can be used to constrain the search space just as well as the `folder_userid_idx` index on `userid` (notice that the two plans have similar `spans`). Both indexes store all three columns (the `folder_userid_idx` implicitly has to store `id` because it's part of the PK). I see no reason why one index would be better than the other for this query.

So it's unclear why the first query would take so long. Is this repeatable if you run the query multiple times? We could use traces to get more information:
```
SET tracing = on;
select name from folder where userid='bc609884-4f32-4054-bf17-dd5cbf1ca226';
set tracing = off;
show trace for session;
```
This would return a lot of data about the execution of the query that we can look at.

I wonder if the interleaving has something to do with this, it's worth trying the same without interleaving in the other table, at least as an experiment.
