### ISSUE TITLE
sql: Partitioning for Inverted Indexes

### ISSUE THREAD

**Issue by chriscasano** [cockroachdb/cockroach#43643]
**Is your feature request related to a problem? Please describe.**
For users that have locality requirements (i.e. GDPR), some of their customer data is stored in JSONB columns which must also adhere to locality rules.  Currently, inverted indexes on these columns can not be partitioned, so the table data can be partitioned but the index can not, which breaks the data locality rules.  There is a current workaround to solve this but would be nicer to have as a supported feature to make usability simple.

**Describe the solution you'd like**

Be able to partition an inverted index just like a regular table or index. 

create inverted index custom_jsonb2 on users (city, custom) partition by list (city)
( 
PARTITION us_west VALUES IN (('seattle'), ('san francisco'), ('los angeles')), 
PARTITION us_east VALUES IN (('new york'), ('boston'), ('washington dc')), 
PARTITION europe_west VALUES IN (('amsterdam'), ('paris'), ('rome'))
)
;

**Describe alternatives you've considered**

The alternatives aren't terrible but it's more leg work that has to be done by administrators / users.  The main alternative is to create partial compute columns for a JSONB column.  The new columns have case logic to populate based on data locality or have null otherwise.  You can then create separate inverted indexes for each compute column.  

**Additional context**

There is a workaround blog post here for more context: https://chriscasano.blogspot.com/2019/12/part-pin-for-inverted-index-win.html

**Comment by awoods187** [comment]
@solongordon can you take a look here?

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[5260](https://cockroachdb.zendesk.com/agent/tickets/5260) has been linked to this issue.

**Comment by jordanlewis** [comment]
cc @rohany. This could be an interesting project.

**Comment by awoods187** [comment]
This came up today in geospatial land. We should be thinking about the intersection of these features for the future.

**Comment by awoods187** [comment]
https://github.com/cockroachdb/docs/issues/7993

**Comment by kcmvp** [comment]
Thank you very much for the amazing product. This feature is what we want!
Are there any plan to release this feature in the near release?  Right now our case is 
1:  we do a lot of sort in elasticsearch
2: those sorted fields mostly are  are numerical and date and updated frequently. (it's bad for elasticsearch)

we are going to use one column  store the search tokenization  tokes inverted Indexes return by ES to speed up query and sort.

**Comment by mgartner** [comment]
@kcmvp we're planning on adding support for partitioned inverted indexes in the next release, 21.1.
