### ISSUE TITLE
Allow for indexes to be NULL_FILTERED

### ISSUE THREAD

**Issue by gconnell** [cockroachdb/cockroach#43663]
**Is your feature request related to a problem? Please describe.**

In a table with N null-able, indexed columns, a row INSERT will require a write to N ranges, even if N-1 of them are NULL.  By allowing indexes to be NULL_FILTERED, we can dramatically reduce the number of ranges hit by an INSERT, which can greatly speed up data upload and reduce the need for large amounts of transactional overhead.  This comes with the trade-off of not being able to use the index for IS NULL queries, but that can be documented.

**Describe the solution you'd like**

Implement the Google-Spanner NULL_FILTERED option on indexes: https://cloud.google.com/spanner/docs/secondary-indexes#null-indexing-disable

**Describe alternatives you've considered**

My current method for getting around this is to have an interleaved "indexed_properties" table containing the values to index along with a single indexed column.  This works (values without the interleaved rows don't affect the indexes), but creates the need for large amounts of JOINs on filtering WHERE clauses and greatly increases the complexity of necessary SQL.

**Comment by jordanlewis** [comment]
Starting in 20.2, you should be able to use partial indexes to create this behavior!

```
CREATE INDEX ON t(attribute) WHERE attribute IS NOT NULL
```
