### ISSUE TITLE
Revisit key encoding

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#437]
Our key encoding scheme is intended to ensure that KeyLocalPrefix and KeySystemPrefix sort before any application-level keys, but this requirement was never tested and is no longer true (If it ever was. The problem predates the switch from sqlite binary encoding to the new escaping scheme). The problem is that both system/local keys and application keys are MVCC encoded before being written to the engine, and since we use the same encoding function for both we cannot distinguish between system keys and application keys that happen to start with one or more NUL bytes.

The closest thing we have to a test for this problem is range_data_iter_test, which fails if the starting point of its test range is changed from `"a"` to `KeyMin` because some of the "application" data is written into the system range.

In order to maintain this ordering property, system keys need to have encodings that are distinct from any possible application key. This means either placing constraints on application keys (i.e. disallowing embedded NUL bytes) or separating the code paths for system keys and application keys enough that we can encode them differently.

**Comment by spencerkimball** [comment]
Yeah, somehow the wires got crossed here. We definitely want a test for this.

The assumption in the code right now is that user keys do not begin with a NUL byte. I think the question we need to answer is whether it's a reasonable constraint or burdensome. If reasonable, things are simpler.

To separate the code paths for system vs. application keys we'd need new key types. Something like proto.SysKey and proto.EncSysKey. But this would massively complicate things with RPCs, where we current specify both types of keys interchangeably. A union type? Ugh.

After thinking a bit about how we might do this, I'm leaning towards restricting user keys. @petermattis is the one who didn't like that idea originally.

**Comment by bdarnell** [comment]
I think "may not contain NUL" is burdensome but "may not begin with NUL" is reasonable (especially once we have the structured API and keys will generally start with a table name/ID). The question is whether we can effectively enforce it. If a disallowed key slips through all kinds of things might happen (including e.g. split brain if some of the raft local records get clobbered). If we can correctly identify the boundaries between user space and internal space then we could call EncodeBytes on user keys just as easily as we could disallow leading NUL.

**Comment by spencerkimball** [comment]
I think it's trivial to disallow user keys starting with NUL byte. It's just done in kv/db.go. That's the gateway through which all user-generated requests must pass through. System keys are used exclusively through a node's internal KV client, which directly uses a distributed sender.

**Comment by spencerkimball** [comment]
Might be helpful to refer to this diagram: https://github.com/cockroachdb/cockroach/raw/master/resource/doc/client-architecture.png?raw=true

**Comment by bdarnell** [comment]
Hmm, yeah. I was thinking it would be non-trivial to find all the places where keys are mentioned in requests (versus the more localized CommitTrigger check), but it looks like we've been able to contain nearly all of those in the request header.

**Comment by petermattis** [comment]
The handling of keys is not straightforward to fix. Currently, `RangeDescriptor.{Start,End}Key` are considered end-user keys. But that can't be correct with the current definition of `KeyMax` as it prohibits usage of any key after `\xff\xff`. We could change `RangeDescriptor.{Start,End}Key` to be encoded keys, but that would need to be plumbed through a large swath of the system. Not impossible, but irritating.

There is also confusion with scan arguments. Are the arguments end-user keys or encoded keys? If end-user keys how do you indicate you want to scan up to `KeyMax`? If encoded keys, where does the encoding take place? On the client? Or in `kv/db.go` when the RPC is received?

We could switch back to the old definition of `KeyMax` (`strings.Repeat("\xff", 4096)`) but doing so ensures we have a 4kb key in various data structures (the meta1 index, range cache, etc). Not horrible, but ugly.

**Comment by spencerkimball** [comment]
I think it's a mistake to bring encoded keys anywhere higher level than storage/engine/mvcc.go. If scan has no final argument, it should go to KeyMax.

My vote is to go back to `KeyMax(strings.Repeat("\xff", 4096))`

**Comment by bdarnell** [comment]
If we map scans with no final argument to KeyMax, do we also need to change the definition of KeyMax? Or is it just one or the other?

**Comment by spencerkimball** [comment]
Why would we change the definition? I don't understand what you're getting at.

**Comment by bdarnell** [comment]
You just said you wanted to change the definition of KeyMax to return to `'\xff' * 4096`; I'm asking whether that is necessary if we also make a change to scan.

**Comment by petermattis** [comment]
@bdarnell there are multiple things to fix if we keep the current definition of `KeyMax`: the end-key of scans, range-descriptor start and end keys, the keys used to lookup range descriptors.

@spencerkimball note that these are not mvcc-encoded keys which would remain local to the range. This is only applying `encoding.EncodeBytes` to the keys the user supplies. I imagine bigtable and related databases must be doing this if they are using a similar encoding for the infinity key.

**Comment by spencerkimball** [comment]
It's not just on scans. We lookup up keys using a binary search which relies on EndKey. I just can't summon up the horror at having KeyMax be 4096 bytes. It's nice an explicit and only shows up on rare pieces of metadata.

**Comment by petermattis** [comment]
Is 4096 bytes the right value for max key-length? What happens if we need to bump it to 8192? With the "infinity key" definition of `KeyMax` we can just change the value. With the `strings.Repeat("\xff", 4096)` definition we're a bit stuck as the max key-length is now embedded in various data structures.

**Comment by spencerkimball** [comment]
So we bump it up. The migration for that would be trivial as the actual value of KeyMax is not part of a client's repetoire and is stored only as the suffix of two meta indexing records. What's with all the hand wringing?

**Comment by petermattis** [comment]
Hand wringing? Just seems awkward to have a known key be the max length.

Here's another thought: we currently disallow user-keys that start with `\x00`. How about we also disallow user-keys that start with `\xff\xff`? We can easily catch usage of such keys in `kv/db.go` and it isn't onerous for the user to escape such keys.

**Comment by bdarnell** [comment]
KeyMax is also stored in range descriptor records, and in raft log entries that modify those records.

**Comment by bdarnell** [comment]
If we're going to reserve more of the keyspace than `\x00`, I'd rather use a rule like "keys must start with a letter" (`\xff` is not a valid byte in utf8, so we can allow the utf8 encoding of any unicode letter and stay within these bounds).

**Comment by spencerkimball** [comment]
It's in only one range descriptor.

4096 is ample space for keys. Amazon limits theirs to 3072 for DynamoDB: http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html

Sometimes setting limits makes life simpler. The migration of it ever happens will be easy. Further limiting the choice of keys seems unnecessary and undesirable.

**Comment by spencerkimball** [comment]
Ping @bdarnell @petermattis 

We need to fix this. My preference stands: use KeyMax = "\xff" x 4096

**Comment by petermattis** [comment]
I'll revisit next week.

**Comment by tamird** [comment]
@petermattis ping

**Comment by petermattis** [comment]
Clearly I did not revisit. I believe this will get resolved as we move to the table-based API.

**Comment by petermattis** [comment]
The current state of keys:

* All system keys start with the prefix `\x00'.
* All table data keys start with the prefix `\xff`.
* `KeyMax` is defined as `\xff\xff`. This is larger than any table key because a table ID (the first portion of a table key after the table data prefix) is encoded as a varint which will have a prefix of `[\x09-\x11]`.

We could actually do away with `TableDataPrefix` as the table ID already guarantees a prefix that won't conflict with the system keys. On the other hand, 1-byte per-key is minimal overhead and makes it obvious that a key is a table data key.

With our current direction to make all user data go into tables and lock down the KV endpoints, I think this issue can be closed.

**Comment by spencerkimball** [comment]
:+1:
