### ISSUE TITLE
sql/pgwire: support restartable transactions

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#4370]
A transaction can be "aborted" for one of 3 reasons: a permanent error, an error that can be retried after an exponential backoff and an error that can be retried immediately. (The details behind the 3 conditions are beyond the scope of this issue, see the code). We currently only support returning a single error condition via `sql/pgwire` through to the client code. This is insufficient. In particular, never restarting transactions is both inefficient and can lead to starvation due to not ratcheting priorities.

We're a bit limited by what we can return through the pgwire protocol. Perhaps a structured message in a string. This can be interpreted by the client driver (`cockroach/pq`?) and transformed into an error. We should also provide any easy facility for running a closure in a loop, restarting the transaction as necessary.

**Comment by spencerkimball** [comment]
@jseldess you'll need to document the endpoint of this issue in the Develop / Transactions document section.

**Comment by jseldess** [comment]
Docs: https://www.cockroachlabs.com/docs/transactions.html
