### ISSUE TITLE
Cannot run CH-benCHmark in cockroachDB

### ISSUE THREAD

**Issue by fzhedu** [cockroachdb/cockroach#43727]
**Is your feature request related to a problem? Please describe.**
I want to run [CH-benCHmark](https://db.in.tum.de/research/projects/CHbenCHmark/?lang=en), but errors happen.

**Describe the solution you'd like**
The queries of AP run correctly, but TP queries cannot. We use ODBC to run the benchmark. The errors are as follows:

```
04:42:13 PM: -bad return:
    SQL_ERROR
    SQLSTATE: HY000
    NATIVE ERROR: 8
    MESSAGE TEXT: internal savepoint error in SendParseRequest
04:42:13 PM: -prepared statement failed
04:42:13 PM: -rollback
```
On the side of CockroachDB, there are a lot of errors shown on the Admin UI, but I do not known what are the specific errors.

**Describe alternatives you've considered**

**Additional context**

**Comment by jordanlewis** [comment]
I'm interested in helping with this but I don't know how to reproduce. Can you include instructions? Feel free to comment on this issue again, I'll close it for now.
