### ISSUE TITLE
Unnecessary rebalances in large clusters with small number of replicas

### ISSUE THREAD

**Issue by darinpp** [cockroachdb/cockroach#43749]
**Describe the problem**

One reason to rebalance replicas is to get the number of replicas handled by each node to be closer to the mean (total number of replicas divided by the number of nodes). The decision to initiate the rebalance is subject to a threshold (which seems to be 5%) so when a node has number of replicas closer to the mean (but not exact) we don't do rebalance. In case of a large cluster however and small number of replicas - the rounding of the mean number of replicas - often causes the difference to exceed 5% and initiates unnecessary (in a sense that a rebalance won't improve the distribution) rebalances.  

**To Reproduce**

Setup a large cluster (65+ nodes) and no other databases besides the default.

**Expected behavior**

I expect to see no rebalances. 

**Environment:**
 - CockroachDB version [20.1]
 - Server OS: [n/a]
 - Client app [n/a]

**Additional context**
What was the impact?

more traffic and load than necessary.

**Comment by AnkilP** [comment]
Hi @darinpp, can I claim this issue?

**Comment by darinpp** [comment]
I suspect that this may not be an issue (and should be left as is) after #43750 is addressed.
