### ISSUE TITLE
Test implementation of temp tables against ORM test suites

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#43756]
Several ORMs (like Hibernate) use temporary tables. We should test our new implementation of temporary tables against these test suites to ensure that it works as expected.

**Comment by rafiss** [comment]
I think AppDev could own or at least collaborate on this -- for Hibernate we would test this by removing the override of `getDefaultMultiTableBulkIdStrategy` in CockroachDBDialect.java

**Comment by rafiss** [comment]
This should just be a matter of enabling the `sql.defaults.experimental_temporary_tables.enabled` cluster setting before running the ORM tests

**Comment by rafiss** [comment]
More info from @solongordon 
> There are a couple of weirdnesses left with temp tables but I don’t think they would come into play. One is that if you have a temp table and normal table with the same name, you could get unpredictable results if you select from that name without qualifying which schema you’re selecting from. The other is that temp tables have the wrong schema in pg_catalog/information_schema tables. I don’t think orm tests would be likely to care about those things but it’s possible. But if you think that might break stuff we could hold off on running tests for a bit [while we fix these].

**Comment by awoods187** [comment]
@apantel or @rafiss is this done now?

**Comment by rafiss** [comment]
Yup, done.
