### ISSUE TITLE
Incorrect use of store ids instead of node ids

### ISSUE THREAD

**Issue by darinpp** [cockroachdb/cockroach#43755]
**Describe the problem**

There is a bug rendering range locality. We use store ids instead of node ids. So in case where the store ids of a node differ from the node id - the locality information is incorrect. I haven't observed however constraint violation. The issues is just with the display.

**To Reproduce**

Start multiple nodes in parallel (not sequentially) seems to be the easiest way to repro this.

**Expected behavior**
I expect to see correct information in the result of `select replicas, replica_localities from crdb_internal.ranges`

**Environment:**
 - CockroachDB version [20.1]
 - Server OS: [n/a]
 - Client app [n/a]

**Additional context**
What was the impact?

It gave the wrong impression that constraints are being violated.

**Comment by nvanbenschoten** [comment]
@darinpp this is related to https://github.com/cockroachdb/cockroach/issues/30940.
