### ISSUE TITLE
Support primary key changes on interleaved tables

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#43759]
Support primary key changes on interleaved tables, as they are currently unsupported.

**Comment by rohany** [comment]
I took some time today to think about this, and I'm worried that we are going to run into the same problem that we sidestepped with primary key changes on tables with foreign key relationships.

This is because an index descriptor holds onto the indexes that are interleaved into it as well, in particular, the index id's. 

If we try to perform some modification on both the table we are changing the primary key of and tables that depend on it, we could run into a similar situation again where some node in the cluster holds an index id of an index that doesn't exist anymore. 

The fact that this index id is mainly used in schema change operations makes it seem less frequent than foreign key operations, but it still seems like a worry.

@lucy-zhang am I missing something that could simplify this?

**Comment by solongordon** [comment]
In our RFC we specified that we would not allow primary key changes on interleaved parents, at least for the initial version of ALTER PRIMARY KEY. Does that solve your problem? We do want to support ALTER PRIMARY KEY ... INTERLEAVE IN PARENT.

**Comment by rohany** [comment]
I'm not sure that does -- when we want a primary key change on an interleaved child, we still have to update the interleaved parent when the old index primary index gets rewritten.

**Comment by solongordon** [comment]
Ah I see. Do we currently have any special handling for this when an interleaved child is dropped? Seems like the same issue would show up in that case.

**Comment by rohany** [comment]
I've been thinking about this, and I'm not really sure. There are multiple places in which we update multiple table descriptors at once, so I'm not sure why we don't have this problem in those cases.

**Comment by rohany** [comment]
Given the discussion on #44007, I think we'll be able to proceed with primary key changes on interleaved children using a `ALTER TABLE t ALTER PRIMARY KEY USING COLUMNS (...) INTERLEAVE INTO PARENT ... (...)` syntax. In addition, it feels to me like if you use `ALTER PRIMARY KEY` without the `INTERLEAVE INTO PARENT` clause on an interleaved table, this should "uninterleave the table".

The combination of these allows for a good path forward for users who want to perform primary key changes on tables that are interleaved parents. They can use `ALTER PRIMARY KEY` to either un-interleave, or move their interleaved children to other parents, and then change the primary key once they don't have any interleaved children.

**Comment by rohany** [comment]
The above workaround isn't quite ideal for tables that interleave other non primary indexes (including indexes on the same table). In these cases, I guess users would just have to drop those indexes and recreate them after the parent table's primary key has been changed.

**Comment by rohany** [comment]
This has been completed by #44075 #44038
