### ISSUE TITLE
sql: add foreign keys to features table

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#43765]
Foreign key telemetry isnt available via the features table and therefore is somewhat inaccurate from the statements table. We should add it to the features table.

**Comment by RaduBerinde** [comment]
Not quite sure what is desired here. A couple counters I can think of:
 - `sql.plan.fk.checks` - set when query with FK checks is planned by the optimizer
 - `sql.plan.fk.cascade` - set when query which involves a FK cascade is planned (using the legacy path)
- `sql.plan.fk.legacy` - set when query with FK checks or cascades is executed with the legacy path while `optimizer_foreign_keys` are turned off

**Comment by awoods187** [comment]
Right now there is now way to tell using the features table how many clusters are using foreign keys. We have this available with anonmyzed statement stats table but this is slow and error prone because it requires a %LIKE search. I think we need to add feature counters so that we can answer questions like:

- What percentage of long-running clusters use FKs? FK Cascades? The legacy code path? The Optimizer path?
- For a given cluster, how many of the tables have FKs to other tables? 
- For a given cluster, what percentage of queries use FKs vs. do not? 

And so on. Does that make sense?
