### ISSUE TITLE
cdc: updating GC TTL on watched tables does not solve replica GC threshold error

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#43772]
**Describe the problem**

When creating a new changefeed on a table, the initial "catchup" scan can take a long time on tables with large amounts of data. This is possibly related to #43103. For particularly large tables, the initial scan might take longer than the default GC TTL window in the cluster, which results in an error that looks like: 

`batch timestamp <timestamp> must be after replica GC threshold <timestamp>`

@ajwerner hypothesized that we might be able to increase the GC window on the watched tables to get around this issue. I attempted this in the Telemetry cluster by bumping the database's GC TTL to 75 hrs:

```
psingh@telemetry/registration> show zone configuration for table stmtstats;
         target         |                  raw_config_sql                   
+-----------------------+--------------------------------------------------+
  DATABASE registration | ALTER DATABASE registration CONFIGURE ZONE USING  
                        |     range_min_bytes = 16777216,                   
                        |     range_max_bytes = 67108864,                   
                        |     gc.ttlseconds = 270000,                       
                        |     num_replicas = 3,                             
                        |     constraints = '[]',                           
                        |     lease_preferences = '[]'                      
(1 row)
```
However despite this change, we still see the error above after starting the changefeed:

`batch timestamp 1576793173.840962794,0 must be after replica GC threshold 1576870074.490489034,0`

Full response:
```psingh@telemetry/registration> select * from crdb_internal.jobs where job_type='CHANGEFEED';
        job_id       |  job_type  |                                                              description                                                              | statement | user_name | descriptor_ids  | status | running_status |             created              |             started              |             finished             |             modified             | fraction_completed | high_water_timestamp |                                                              error                                                               | coordinator_id  
+--------------------+------------+---------------------------------------------------------------------------------------------------------------------------------------+-----------+-----------+-----------------+--------+----------------+----------------------------------+----------------------------------+----------------------------------+----------------------------------+--------------------+----------------------+----------------------------------------------------------------------------------------------------------------------------------+----------------+
  513549185343979521 | CHANGEFEED | CREATE CHANGEFEED FOR TABLE stmtstats INTO 'experimental-s3://register-cdc/stmtstats/' WITH updated                                   |           | joel      | {94,100}        | failed | NULL           | 2019-12-19 22:06:13.847661+00:00 | 2019-12-19 22:06:13.889793+00:00 | 2019-12-22 01:42:55.230138+00:00 | 2019-12-19 22:06:13.847661+00:00 |                  0 | NULL                 | batch timestamp 1576793173.840962794,0 must be after replica GC threshold 1576870074.490489034,0                                 |              4  
```

@danhhz suspects that the issue is the GC window on an internal/system table:
> 1576870074 is Dec 20th and it started on Dec 19th which is less than 75 hours, so sounds like the gc ttl isn't in effect somewhere. I wonder if this is the system.descriptors table which is also used by changefeeds, do you know what the gc ttl is on that table? (This all needs to be documented once we figure it out.) It sucks that this error doesn't have any info about where in the keyspace it had the gc issue.

I confirmed the system database still had the default value for GC TTL (25 hrs). 

cc @lnhsingh for any docs impact - we will probably want to warn users about this potential issue. This may be obviated by supporting compression on the JSON files sent to cloud storage.

**Comment by ajwerner** [comment]
I'm tentatively assigning myself this as I'm going to work on using protected timestamps in changefeeds to prevent these sort of GC related issues during backfills.
