### ISSUE TITLE
sql: string comparison differs from postgres

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#43774]
```
SELECT
    *
FROM
    (
        VALUES
            ('b'),
            (quote_nullable('c')),
            ('d'),
            ('''e'''),
            ('f'),
            ('"g"'),
            ('h')
    )
        AS v (a)
ORDER BY
    a;
```

In cockroach:

```
 "g"
 'c'
 'e'
 b
 d
 f
 h
```

Postgres:

```
 b
 'c'
 d
 'e'
 f
 "g"
 h
```

That is, postgres strips quotes during comparison, cockroach doesn't. Postgres 11 (but same behavior on 9.6). It's also case-insensitive.

**Comment by mjibson** [comment]
Also maybe this has something to do with some session setting? Who knows? In any case it's probably impossible to fix since it would involve changing our on-disk encoding probably? Just putting this here in case anyone wants to track down the exact postgres semantics. I looked around their docs but couldn't find anything that mentioned this.

**Comment by knz** [comment]
FYI on my machine:
```
kena@kenax ...ckroach/pkg/sql/pgwire/hba % psql
psql (11.6)
Type "help" for help.

kena=> SELECT
kena->     *
kena-> FROM
kena->     (
kena(>         VALUES
kena(>             ('b'),
kena(>             (quote_nullable('c')),
kena(>             ('d'),
kena(>             ('''e'''),
kena(>             ('f'),
kena(>             ('"g"'),
kena(>             ('h')
kena(>     )
kena->         AS v (a)
kena-> ORDER BY
kena->     a;
  a
-----
 "g"
 'c'
 'e'
 b
 d
 f
 h
(7 rows)
```

**Comment by mjibson** [comment]
```
psql (11.5 (Debian 11.5-3.pgdg90+1))
Type "help" for help.

postgres=# select * from ( values ('h'), ('d'), ('''c'''), ('b'), ('"e"'), ('f'), ('G')) as v (a) order by a;
  a  
-----
 b
 'c'
 d
 "e"
 f
 G
 h
(7 rows)
```

Well something is going on.

**Comment by knz** [comment]
Can you report the output of *show all* 
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by knz** [comment]
In particular let's look at `lc_collate` (mine is "C")

You may have set something different for the purpose of some earlier testing?

**Comment by mjibson** [comment]
Mine is `en_US.utf8`. Yeah ok so things are fine and this is just due to...the docker image (where I run the postgres server) being started in that locale, which explains why it happens in my automated testing and psql. Ok move along. I'll add locale configuration to my docker image startup which should take care of this. Thanks.
