### ISSUE TITLE
High CPU usage in whole cluster - Slow ping and high latency

### ISSUE THREAD

**Issue by diegogub** [cockroachdb/cockroach#43810]
Hello,

I created a cluster of 3 nodes to use a event store, everything was working fine until I started adding thousandths events. I did many test with millions of events before but this issue did not showed up. I moved to production, but I had to fall back few days after..

Insertions are very slow, even after I stop inserting data. I'm using SEQUENCES for each stream, not sure if that could be the issue.

Build Tag:    v19.1.5
Build Time:   2019/09/23 14:12:16
Distribution: CCL
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.11.6
C Compiler:   gcc 6.3.0
Build SHA-1:  6b14c0aa3ed1b4ba6d5f937e9352c5383afe1c37
Build Type:   release

<img width="454" alt="Screen Shot 2020-01-08 at 10 14 36 AM" src="https://user-images.githubusercontent.com/2489012/71980979-1e6bee00-3200-11ea-857d-13c01afd679a.png">

Only thing I see in log is this kind of log:

I200108 13:09:14.278408 44614 sql/lease.go:1857  released orphaned table lease: {id:6367 version:1 expiration:{Time:{wall:222699000 ext:63714077718 loc:<nil>}}}

I200108 13:15:39.078435 2960 server/status/runtime.go:500  [n3] runtime stats: 1.2 GiB RSS, 191 goroutines, 746 MiB/167 MiB/1.0 GiB GO alloc/idle/total, 130 MiB/152 MiB CGO alloc/total, 4652.2 CGO/sec, 145.9/2.8 %(u/s)time, 0.0 %gc (1x), 2.3 MiB/2.0 MiB (r/w)net

No clear error..

Thanks

**Comment by jordanlewis** [comment]
Hi, sorry for the lack of response. I'm going to close this issue due to age.

Likely sequences could be related. For workloads like this, you should use random keys like UUIDs. Or, consider our hash-sharded indexes. https://www.cockroachlabs.com/blog/hash-sharded-indexes-unlock-linear-scaling-for-sequential-workloads/
