### ISSUE TITLE
cdc: produced json fails to parse

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#43813]
**Describe the problem**
After executing a series of upsert statements, two json files get created. Jsonparser fails due to invalid json syntax on the second file.

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

1. Set up a table with schema
```
CREATE TABLE  chrg_cd (
        chrg_id UUID NOT NULL,
        cst_cntr_cd STRING NULL,
        chrg_cd_descr STRING NULL,
        automap_spl_cd STRING NULL,
        aprv_spl_cd STRING NULL,
        del_ind BOOL NOT NULL DEFAULT false,
        CONSTRAINT "primary" PRIMARY KEY (chrg_id ASC),
        INDEX descr (chrg_cd_descr ASC),
        FAMILY "primary" (chrg_id, cst_cntr_cd, chrg_cd_descr, automap_spl_cd, aprv_spl_cd, del_ind)
);
```
2. Create a changefeed on the table
```
CREATE CHANGEFEED FOR TABLE chrg_cd INTO 'experimental-s3://miniobucket/customer/folder?AWS_ACCESS_KEY_ID=dummy&AWS_SECRET_ACCESS_KEY=dummy&AWS_ENDPOINT=http://dummy:port&AWS_REGION=dummy' with updated;
```
3. Insert some data
```
UPSERT INTO chrg_cd VALUES('62b3dba1-82ce-4a69-913c-232a345752ee', 'Xodol',	'Rebel Distributors Corp',	'hydrocodone bitartrate and acetaminophen', 'Re-engineered', false);
UPSERT INTO chrg_cd VALUES('892a09c2-92d4-4f99-ae15-40f456341dbb',	'Aspirin',	'KEM Pharma LLC', 'Aspirin', 'secured line', true);
UPSERT INTO chrg_cd VALUES('edbd40da-8a42-4350-a827-5908cb3921cc',	'Treatment Set TS350533', 'Antigen Laboratories, Inc.', 'Treatment Set TS350533',	'complexity', true);
UPSERT INTO chrg_cd VALUES('dd8bcc36-6f5c-4ce1-824b-b71c48483a33',	'PAXILCR', 'Physicians Total Care, Inc.', 'paroxetine hydrochloride', 'model', false);
UPSERT INTO chrg_cd VALUES('813c40bc-46e1-4f26-87ce-18ddb58d5e44',	'Laxative Pills', 'Freds Inc', 'Sennosides', 'content-based', true);
```
You will find two files, first file will contain a single record, second file will contain four records, jsonparser will be able to parse first record of the second file but will fail on the rest.

**Expected behavior**
JSON produced by changfeed should be valid JSON.

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version 19.2.2
 - Server OS: OSX with Docker 19.03.5, build 633a0ea
 - Client app: cockroach sql

**Additional context**
What was the impact?

online json evaluator used https://jsonpath.curiousconcept.com/

This json is the first record of the second file produced by changefeed
![working](https://user-images.githubusercontent.com/461296/71989349-82da7d80-31ff-11ea-8cb3-0110023df092.png)

parsing the entire file with a java parser like json-path will fail
![not_working](https://user-images.githubusercontent.com/461296/71989410-9c7bc500-31ff-11ea-9d83-14aec737441d.png)

For the record, two files created are below

contents of the first file: `202001071819114946624050000000001-463e3361214e2733-1-30-00000000-chrg_cd-1.ndjson`

```
{"after": {"aprv_spl_cd": "Re-engineered", "automap_spl_cd": "hydrocodone bitartrate and acetaminophen", "chrg_cd_descr": "Rebel Distributors Corp", "chrg_id": "62b3dba1-82ce-4a69-913c-232a345752ee", "cst_cntr_cd": "Xodol", "del_ind": false}, "key": ["62b3dba1-82ce-4a69-913c-232a345752ee"], "updated": "1578421170196279369.0000000000"}
```

contents of the second file: `202001071819114946624050000000001-463e3361214e2733-1-30-00000001-chrg_cd-1.ndjson`

```
{"after": {"aprv_spl_cd": "secured line", "automap_spl_cd": "Aspirin", "chrg_cd_descr": "KEM Pharma LLC", "chrg_id": "892a09c2-92d4-4f99-ae15-40f456341dbb", "cst_cntr_cd": "Aspirin", "del_ind": true}, "key": ["892a09c2-92d4-4f99-ae15-40f456341dbb"], "updated": "1578421170206587163.0000000000"}
{"after": {"aprv_spl_cd": "complexity", "automap_spl_cd": "Treatment Set TS350533", "chrg_cd_descr": "Antigen Laboratories, Inc.", "chrg_id": "edbd40da-8a42-4350-a827-5908cb3921cc", "cst_cntr_cd": "Treatment Set TS350533", "del_ind": true}, "key": ["edbd40da-8a42-4350-a827-5908cb3921cc"], "updated": "1578421170210498925.0000000000"}
{"after": {"aprv_spl_cd": "model", "automap_spl_cd": "paroxetine hydrochloride", "chrg_cd_descr": "Physicians Total Care, Inc.", "chrg_id": "dd8bcc36-6f5c-4ce1-824b-b71c48483a33", "cst_cntr_cd": "PAXILCR", "del_ind": false}, "key": ["dd8bcc36-6f5c-4ce1-824b-b71c48483a33"], "updated": "1578421170214271047.0000000000"}
{"after": {"aprv_spl_cd": "content-based", "automap_spl_cd": "Sennosides", "chrg_cd_descr": "Freds Inc", "chrg_id": "813c40bc-46e1-4f26-87ce-18ddb58d5e44", "cst_cntr_cd": "Laxative Pills", "del_ind": true}, "key": ["813c40bc-46e1-4f26-87ce-18ddb58d5e44"], "updated": "1578421170218928697.0000000000"}
```

**Comment by dbist** [comment]
json can be validated with https://jsonpath.curiousconcept.com/

**Comment by ajwerner** [comment]
The output of changefeeds is newline-delimited json. Each row in the output is valid JSON. See http://ndjson.org/ for more information on this encoding format. If you found the documentation to be wanting, please open an issue in the https://github.com/cockroachdb/docs/ repo.
