### ISSUE TITLE
storage/reports: critical localities quorum consideration is naive

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#43836]
The critical localities report does `quorumCount := len(r.Replicas().Voters())/2 + 1` and compares that to the number of live nodes. I think this is incorrect since we started doing atomic rebalancing; instead we should be looking at both the "outgoing quorum" and the "incoming quorum" when we're in the joint consensus state, right @tbg ?

cc @darinpp

**Comment by andreimatei** [comment]
Note to self: I'm not sure what this says about whether `VoterIncoming` replicas should count as replicas for the purposes of the under-replicated count in the respective report. Currently they do.
But, for example, in a scenario where a range has 2 `VoterFulls`, 1 `VoterOutgoing`, 1 `VoterIncoming`, and the outgoing voter is on a dead node, should the range be counted as under-replicated? I think so, depending on the definition of under-replication, since I think in this scenario both of the `VoterFulls` are critical.

**Comment by tbg** [comment]
Yes, when in a joint state, we should look at the old and new config. If
either is {under,over}-replicated, then the joint config is, too. Or, in
other words, the joint config is only "healthy" if both of its constituents
are.
