### ISSUE TITLE
sql: GRANT mistakenly allowed on system.lease, causing deadlocks

### ISSUE THREAD

**Issue by Cynthia-Lee97** [cockroachdb/cockroach#43842]
**Describe the problem**
We all know that there are many system tables in the database.But I've found that programs get stuck when I try to grant to certain system tables

**To Reproduce**
Start the database and enter the statement:
      GRANT GRANT, SELECT, INSERT, DELETE, UPDATE on system.lease to testuser
If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster
2. Send SQL statement: GRANT GRANT, SELECT, INSERT, DELETE, UPDATE on system.lease to testuser
3. We'll find that the system is stuck

**Expected behavior**
Returns a sign of success or failure in empowerment

**Environment:**
•CockroachDB version [19.2.0]
•Server OS: [Linux]
•Client app [cockroach sql]

**Comment by knz** [comment]
GRANT on system.leases will try to bump its version number, which will cause a deadlock.

@lucy-zhang @ajwerner I propose to simply reject _any_ use of GRANT on `system` tables. If there's a need to delegate responsibility, this should come via membership on the `admin` role. WDYT?
