### ISSUE TITLE
sql: add latency info to EXPLAIN ANALYZE

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#43859]
The `EXPLAIN ANALYZE` output includes stall time for operators, but it does not include latency of the links connecting operators across nodes. It would be useful to include latency, especially to identify bottlenecks in geo-distributed clusters.

Another idea would be to include pairwise node latency separately from the `EXPLAIN ANALYZE` diagram, using node IDs that correspond to the IDs in the diagram. Locality info for the nodes would also be useful (if available).

This info will be helpful as we improve the optimizer to be aware of data distribution. It will also be helpful when debugging slow queries.

cc @awoods187

**Comment by awoods187** [comment]
this is a great idea!

**Comment by rohany** [comment]
Writing this down because I was in the area, but its possible to get node latencies by doing `params.ExecCfg().StatusServer.Nodes(params.ctx, &serverpb.NodesRequest{})`, and then using the `node.Activity` map for each node returned from the result list.

**Comment by rohany** [comment]
I'm worried about adding the exact latencies to the output of explains because we use explain plans  everywhere for testing. The latencies would have some small amount of variance between runs leading to an unstable explain URL
