### ISSUE TITLE
sql: determine proper SHOW TABLES behavior for temp tables

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/cockroach#43853]
@awoods187 noticed that temp tables are incorrectly treated as being in the `public` schema for the purposes of SHOW TABLES.

```
root@127.0.0.1:55024/defaultdb> set experimental_enable_temp_tables=true;
SET

Time: 445µs

root@127.0.0.1:55024/defaultdb> create temp table t (x int);
CREATE TABLE

Time: 2.796ms

root@127.0.0.1:55024/defaultdb> show tables;
  table_name
--------------
  t
(1 row)

Time: 1.396ms

root@127.0.0.1:55024/defaultdb> show tables from public;
  table_name
--------------
  t
(1 row)

Time: 1.316ms

root@127.0.0.1:55024/defaultdb> show tables from pg_temp;
  table_name
--------------
(0 rows)
```
This is obviously incorrect, but also we should figure out what the proper SHOW TABLES behavior should be when no schema is specified. Probably we want to include a `schema_name` column in the output now.

**Comment by solongordon** [comment]
Also make sure that temp tables don't show up in SHOW TABLES output for other sessions.

**Comment by otan** [comment]
it looks like we should actually be using a different `db_schema` named `pg_temp_3`, as opposed to `public`...

**Comment by otan** [comment]
looks like the number is allocated at runtime as `pg_temp_n`, which can be aliased with `pg_temp` -- https://www.postgresql.org/docs/current/runtime-config-client.html

the `n` is written / decided at cluster initialisation time (?): https://sourcegraph.com/github.com/postgres/postgres@a166d408eb0b35023c169e765f4664c3b114b52e/-/blob/src/backend/commands/cluster.c#L691

should we be looking at doing something similar?

**Comment by solongordon** [comment]
Ah that makes sense. There is a known outstanding work item to make the metadata tables properly reflect the schema for temporary tables.

Like Postgres, we put temporary tables in a special `pg_temp_n` schema, though in our case `n` is the session ID the table was created in. This is reflected in the `parentSchemaID` column of the `system.namespace` table. However, we have not yet updated the logic for constructing the pg_catalog and information_schema tables to reflect this. The schema columns there are still hard-coded to `public`.

I'll forward you an email with Arul's thoughts on how to implement this.
