### ISSUE TITLE
sql: investigate BenchmarkDelete100_Cockroach slowdown

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#4386]
#4384 added support for using `CommitInBatch` with delete requests which showed a very nice performance improvement for the `Delete{1,10}` benchmarks. But it resulted in a reproducible slowdown for the `Delete100` benchmark. The code in question is in `sql/delete.go:

```
        pErr = p.txn.CommitInBatch(b)
```

The slowdown can removed by replacing this with: (this was what the code was doing before #4384).

```
        pErr = p.txn.Run(b)
        if pErr == nil {
            pErr = p.txn.Commit()
        }
```

**Comment by petermattis** [comment]
Just reconfirmed this performance oddity is still present. I compared 905eb801305c9bac93ce10d4847b629d11a32a7c vs this patch applied:

```
~/Development/go/src/github.com/cockroachdb/cockroach/sql master git diff
diff --git a/sql/delete.go b/sql/delete.go
index e527657..5cb917c 100644
--- a/sql/delete.go
+++ b/sql/delete.go
@@ -131,7 +131,7 @@ func (p *planner) Delete(n *parser.Delete, autoCommit bool) (planNode, *roachpb.
                return nil, pErr
        }

-       if autoCommit {
+       if false && autoCommit {
                // An auto-txn can commit the transaction with the batch. This is an
                // optimization to avoid an extra round-trip to the transaction
                // coordinator.
```

```
name                    old time/op    new time/op    delta
Delete1_Cockroach-8        603µs ± 3%     821µs ± 4%  +36.08%  (p=0.000 n=10+10)
Delete10_Cockroach-8      1.94ms ± 1%    2.10ms ± 3%   +8.23%  (p=0.000 n=10+10)
Delete100_Cockroach-8     15.6ms ± 3%    13.9ms ± 2%  -10.46%  (p=0.000 n=10+10)
Delete1000_Cockroach-8     159ms ± 2%     153ms ± 1%   -3.27%    (p=0.003 n=4+9)

name                    old alloc/op   new alloc/op   delta
Delete1_Cockroach-8       36.2kB ± 0%    43.0kB ± 0%  +18.87%  (p=0.000 n=10+10)
Delete10_Cockroach-8       110kB ± 0%     121kB ± 0%   +9.94%   (p=0.000 n=10+9)
Delete100_Cockroach-8      827kB ± 0%     853kB ± 0%   +3.16%   (p=0.000 n=9+10)
Delete1000_Cockroach-8    7.44MB ± 0%    7.65MB ± 0%   +2.74%    (p=0.003 n=4+9)

name                    old allocs/op  new allocs/op  delta
Delete1_Cockroach-8          692 ± 0%       847 ± 0%  +22.34%  (p=0.000 n=10+10)
Delete10_Cockroach-8       1.72k ± 0%     1.91k ± 0%  +10.85%   (p=0.000 n=10+9)
Delete100_Cockroach-8      11.6k ± 0%     12.1k ± 0%   +3.95%   (p=0.000 n=9+10)
Delete1000_Cockroach-8      110k ± 0%      113k ± 0%   +2.83%    (p=0.003 n=4+9)
```

@dt can you take a look at this next week? @tschottdorf any theories. I would think that committing a transaction along with all of the writes would be strictly faster than performing the writes and then committing.

**Comment by tschottdorf** [comment]
I would first check that the batch really makes it to the replica unhindered. DistSender can sometimes break up the EndTransaction into a separate call when it looks like it would hit more than one Replica.
Easy to check with a panic assertion.

Assuming that's not it - maybe something is doing more work in the 1PC case at the replica, but I have a hard time imagining what that something might be - response cache cleanup, intent resolution, etc all look like they would be doing the same thing.

Maybe `EXPLAIN(TRACE)` can give some pointers, too. Cheap enough to look at, anyway.

**Comment by dt** [comment]
the slowdown looks like it is mostly in `MVCCResolveWriteIntentRange` running on a fresh, empty batch vs the one with lots of writes staged. short of some some complicated chunking of Batch commands, I'm not entirely sure what we can do about it.

**Comment by dt** [comment]
whoops: meant to link this https://github.com/cockroachdb/cockroach/compare/master...dt:hacks?expand=1

**Comment by petermattis** [comment]
Why is running on a batch with lots of writes staged so much slower than running on an empty batch? Are we encountering a new problem with deletion tombstones? And why is the `Delete100` benchmark affected more than the `Delete1000`?

**Comment by dt** [comment]
https://github.com/cockroachdb/cockroach/compare/master...dt:iter?expand=1 revealed that the `Seek` on a batch containing 10k deletes takes _8.5ms_. `Put`s seem fine. Oddly, if the underlying DB has has more records, even if the deletes and seeks on on the same keys, it gets faster, and if the block of deletes is offset from the ends of the base DB's populate key range it seems to as well. I think i've learned about all I can on the Go side though, so digging into WriteBatchWithIndex and its iterator on the C++ seems like the next step.

**Comment by petermattis** [comment]
Closing due to age.
