### ISSUE TITLE
Randomized testing for primary key changes

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#43877]
I wanted to add some sort of randomized testing to the logic tests for primary key changes, but I'm not sure whats the best way to do this. I have two ideas, and wanted to get some discussion.

1. After every create table, issue an alter primary key to change the table's primary key to the same primary key. (pro's -- plans won't change, cons -- doesn't test much in my opinion)
2. For each create table, remove the primary key definition, then add an alter primary key to the primary key that was intended to be the key of the table. (pro's -- covers some more cases than 1, cons: (also a con of 1) doesn't perform and rewrites of data, which is a big point of the test).

@mjibson @solongordon any thoughts?

**Comment by rohany** [comment]
Also, I'm not sure if this would be something we'd want to run as part of our normal logictests. It makes more sense to be a roachtest or something that we'd run the logic tests with a special configuration that enables this.

**Comment by mjibson** [comment]
2 seems like it would work for the logic tests. Anything more (i.e., doing a random PK change) will probably break a lot of logic tests that depend on the PK being something. But we can add a sqlsmith alter pk statement (i.e., not a mutator) that does this and will then be plugged into the general testing stuff.

**Comment by rohany** [comment]
I'm just not entirely convinced 2 is useful in any sense -- running a primary key change on empty tables doesn't test that much of the process.

**Comment by mjibson** [comment]
Ok, then just add a new sqlsmith alter statement. It's hard to generalize things such that they work in the logic tests.

**Comment by rohany** [comment]
Going to close this then in favor of a new issue.
