### ISSUE TITLE
opt: push limits into joins

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#43888]
Was working through a customer query and was thinking that we could have a rule that does something like this:
```
[PushLimitIntoJoinLeft, Normalize]
(Limit
    (InnerJoin
        $left:*
        $right:*
        $on:* & (HasAtLeastOneMatch $left $right $on)
    )
    (Const $n:*)
)
=>
(Limit
    (InnerJoin
        (Limit
            $left
            (Const $n)
        )
        $right
        $on
    )
    (Const $n)
)
```
(and the same for the right side).

Where `HasAtLeastOneMatch` uses the existence of FKs to guarantee that every row in $left has at least one match in $right. We'd have to be at least somewhat careful to ensure that this rule doesn't cycle with itself.

**Comment by DrewKimball** [comment]
This is fixed by the rules `PushLimitIntoJoinLeft` and `PushLimitIntoJoinRight` in #49802.
