### ISSUE TITLE
ui: node list follow up work

### ISSUE THREAD

**Issue by Annebirzin** [cockroachdb/cockroach#43883]
Feedback for node list follow up work on #42923

- [ ] Update header from `Live Nodes` to `Nodes`
- [ ] Update status for localities from `Ready` to `Live`

- [ ] Update the Node Id formatting to add a space between the node id and the locality and add an `N` before the node id (for example: `N2 us-east1`)
![Screen Shot 2020-01-08 at 10 57 29 AM](https://user-images.githubusercontent.com/51920721/72185417-be707580-33c0-11ea-91eb-ceecb873a4b6.png)

- [ ] Update table header fonts to:
  letter-spacing: `1.5px`;
  color: `#475872`;
  font-weight: `bold`
![Screen Shot 2020-01-10 at 3 39 39 PM](https://user-images.githubusercontent.com/51920721/72184879-700ea700-33bf-11ea-8f70-c1e1637904c9.png)

- [ ] Update node list links to be grey color: `#394455` by default. When hovering anywhere in the row, node link changes to color: `#0788ff` and style: `Underlined`

- [ ] Update locality arrow icons to match size/width of the `Hide` decommissioned nodes arrow icon
![Screen Shot 2020-01-10 at 3 50 56 PM](https://user-images.githubusercontent.com/51920721/72185534-02fc1100-33c1-11ea-984b-c48835f7c7c8.png)

- [ ] Update the `Node list / Node map` white background box to be consistently styled, using the `node map` style (same height and drop shadow) 
![Screen Shot 2020-01-10 at 4 13 06 PM](https://user-images.githubusercontent.com/51920721/72186848-2bd1d580-33c4-11ea-93bf-8cce82e7e922.png)
![Screen Shot 2020-01-10 at 4 13 13 PM](https://user-images.githubusercontent.com/51920721/72186852-2d9b9900-33c4-11ea-978e-49f51d14c6d7.png)

- [ ] In the collapsed decommissioned nodes module, align the Title and `Show` action to be vertically centered in the module 
![Screen Shot 2020-01-08 at 12 35 29 PM](https://user-images.githubusercontent.com/51920721/72185627-45255280-33c1-11ea-8731-414bdd9dbe75.png)

**Comment by dhartunian** [comment]
@koorosh can you rebase this so we can see with new sidebar?

@Annebirzin quick Q about triangle icon: should it change orientation when clicked? the designs suggest it stays the same but the implementation currently has it change which just "looks wrong" to me:

<img width="247" alt="Screen Shot 2020-02-04 at 9 42 51 AM" src="https://user-images.githubusercontent.com/986307/73754691-c22eb800-4732-11ea-8e1a-419917160c88.png">

**Comment by Annebirzin** [comment]
@dhartunian the arrow should not change orientation. thanks!
