### ISSUE TITLE
Update JSONB column: TransactionRetryWithProtoRefreshError: WriteTooOldError:

### ISSUE THREAD

**Issue by majst01** [cockroachdb/cockroach#43917]
**Describe the problem**
Parallel update of a JSONB column does not succeed with 
```
restart transaction: TransactionRetryWithProtoRefreshError: WriteTooOldError: write at timestamp 1578930228.280494338,0 too old; wrote at 1578930228.376857856,1
```
Please describe the issue you observed, and any steps we can take to reproduce it:

Update a column with JSONB format in parallel, schema:
```sql
CREATE TABLE IF NOT EXISTS prefixes (
	cidr   text PRIMARY KEY NOT NULL,
	prefix JSONB
);
```

Update statement executed with 30 goroutines:
```sql
UPDATE prefixes SET prefix=$1 WHERE cidr=$2 AND prefix->>'Version'=$3", pn, prefix.Cidr, oldVersion
```

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster with

docker run -d --name=roach1 --hostname=roach1 --net=roachnet -p 5433:26257 -p 8080:8080 cockroachdb/cockroach:v19.2.2 start-single-node --insecure --listen-addr=0.0.0.0

2. run `make test` from https://github.com/metal-pod/go-ipam/tree/cockroachdb
3. this error occurs:
```
TransactionRetryWithProtoRefreshError: WriteTooOldError: write at timestamp 1578930231.130614740,0 too old; wrote at 1578930231.130614740,2
```
**Environment:**
 - CockroachDB version 19.2.2
 - Server OS: Ubuntu
 - Client app golang 1.13.5 with pg v1.2.3

**Comment by majst01** [comment]
We solved this by using:
github.com/cockroachdb/cockroach-go/crdb
crdb.ExecuteTx

see: https://github.com/metal-pod/go-ipam/blob/cockroachdb/sql.go#L118

Took a bit for us to get to the point where we understood how to proceed, but overall congrats to the great documentation.

**Comment by ASalihov** [comment]
> We solved this by using:
> github.com/cockroachdb/cockroach-go/crdb
> crdb.ExecuteTx
> see: https://github.com/metal-pod/go-ipam/blob/cockroachdb/sql.go#L118
> Took a bit for us to get to the point where we understood how to proceed, but overall congrats to the great documentation.

your link is bitten

**Comment by majst01** [comment]
With cochroach 20.1.x we do not need to do anything special because select for update is implemented now.
Again thanks for this great product
