### ISSUE TITLE
Error from the vectorized runtime: interface conversion: coldata.column is []int32, not []int64

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/cockroach#43936]
**Problem**

Vectorized engine unexpectedly fails with an error message about integer type conversions:

```
pq: internal error: unexpected error from the vectorized runtime: interface conversion: coldata.column is []int32, not []int64
```

**To Reproduce**

Using a CRDB 19.2.1 binary, load the "employees" data set:

```sql
CREATE DATABASE IF NOT EXISTS employees;
USE employees;
IMPORT MYSQLDUMP 'https://s3-us-west-1.amazonaws.com/cockroachdb-movr/datasets/employees-db/mysqldump/employees-full.sql.gz';
```

Then issue the following query:

```sql
SELECT MAX(s.salary) FROM salaries AS s;
```

This resulted in the following error message:

```
DETAIL: stack trace:
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/execerror/error.go:70: func1()
/usr/local/go/src/runtime/panic.go:522: gopanic()
/usr/local/go/src/runtime/iface.go:248: panicdottypeE()
/go/src/github.com/cockroachdb/cockroach/pkg/col/coldata/vec.go:185: Int64()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/vec_elem_to_datum.go:51: PhysicalTypeColElemToDatum()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:168: next()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:140: nextAdapter()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/execerror/error.go:91: CatchVectorizedRuntimeError()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:177: Next()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:169: Run()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:725: Run()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:375: Run()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:372: Run()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:997: PlanAndRun()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:825: execWithDistSQLEngine()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:717: dispatchToExecutionEngine()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:416: execStmtInOpenState()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:98: execStmt()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1243: execCmd()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1172: run()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:444: ServeConn()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:584: func1()
/usr/local/go/src/runtime/asm_amd64.s:1337: goexit()
```

I searched in the issue tracker for the `pq` error message above, and did not find a report of this issue.

**Expected behavior**

I expected the query to return a result.  Interestingly, running a very similar query on another table that calls `max()` on similar values does work:

```
SELECT MAX(e.emp_no) FROM employees AS e;
   max    
+--------+
  499999  
(1 row)
```

I tried the above because I thought (based on the error message) that CRDB was unhappy because of a particular 32-bit value somewhere.  Both the `employees` and `salaries` tables use `INT4` as the data type for the numeric values I was running `max()` on.  However, one query works, and one doesn't.

```
SHOW COLUMNS FROM salaries;
  column_name | data_type | is_nullable | column_default | generation_expression |  indices  | is_hidden  
+-------------+-----------+-------------+----------------+-----------------------+-----------+-----------+
  emp_no      | INT4      |    false    | NULL           |                       | {primary} |   false    
  salary      | INT4      |    false    | NULL           |                       | {}        |   false    
  from_date   | DATE      |    false    | NULL           |                       | {primary} |   false    
  to_date     | DATE      |    false    | NULL           |                       | {}        |   false    
(4 rows)
```
```
SHOW COLUMNS FROM employees;
  column_name |  data_type  | is_nullable | column_default | generation_expression |  indices  | is_hidden  
+-------------+-------------+-------------+----------------+-----------------------+-----------+-----------+
  emp_no      | INT4        |    false    | NULL           |                       | {primary} |   false    
  birth_date  | DATE        |    false    | NULL           |                       | {}        |   false    
  first_name  | VARCHAR(14) |    false    | NULL           |                       | {}        |   false    
  last_name   | VARCHAR(16) |    false    | NULL           |                       | {}        |   false    
  gender      | STRING      |    false    | NULL           |                       | {}        |   false    
  hire_date   | DATE        |    false    | NULL           |                       | {}        |   false    
(6 rows)
```

**Environment**

CRDB version 19.2.1 running in a local 1-node cluster on a Macbook (macOS Catalina 10.15.2):

```
SELECT VERSION();
                                         version                                         
+---------------------------------------------------------------------------------------+
  CockroachDB CCL v19.2.1 (x86_64-apple-darwin14, built 2019/11/18 23:17:47, go1.12.12)  
(1 row)
```

**Comment by yuzefovich** [comment]
I took a quick look at this issue. The problem here is that when we're planning the vectorized aggregator, `execinfrapb.GetAggregateInfo` returns `types.Int` as the return type of `MAX` builtin function, regardless of what the input type is. In this case, the input type is `INT4`, so the operator works with `Int32`s and returns `Int32`s as well, but the receiver expects it to be `Int64`.

This seems somewhat similar to #43550 which we fixed by planning an explicit cast. We might want to do the same thing here. This case is more complicated because we would need to add a projection to "remove" the casted-from columns that aggregate functions output and put casted-to columns in their place. This will be very fragile though. Thoughts? cc @asubiotto 

As a side note, actually both queries that Rich mentioned produce the error, the difference must have been that the stats were not computed on the table on which the query succeeded, so the vectorized engine was not used. To disable paying attention to stats, one could do `SET vectorize_row_count_threshold=0`.

**Comment by asubiotto** [comment]
A solution for this is probably similar to what we need to do for #38845, I would probably lean to falling back to the row execution engine if the types differ for now. Why does `GetAggregateInfo` not return a type of `INT4` for `MAX` with an input type of `INT4`?

**Comment by yuzefovich** [comment]
There is `types.Scalar` (a list of "scalar" types) defined which includes only the canonical type for each family, for Int family it is `INT` = `INT8`. When looking up a builtin, we iterate over that list. (Not looking at the code right now, that's what I saw yesterday.)

I look your suggestion about not supporting such case for now.

**Comment by rmloveland** [comment]
yuzefovich <notifications@github.com> writes:

> As a side note, actually both queries that Rich mentioned produce the
> error, the difference must have been that the stats were not computed
> on the table on which the query succeeded, so the vectorized engine
> was not used. To disable paying attention to stats, one could do SET
> vectorize_row_count_threshold=0.

That workaround works for me.  Thanks Yahor!
