### ISSUE TITLE
teamcity doesn't seem to interpret test timeouts under stress right

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#43947]
Take a look at this failed build
https://teamcity.cockroachdb.com/viewLog.html?buildId=1684246&buildTypeId=Cockroach_UnitTests_Testrace&tab=buildResultsDiv

What happened is that the `TESTTIMEOUT` was hit. However, teamcity doesn't tell me that, and moreover because we use `GOTESTFLAGS=-json`, the test output is quite garbled.
Don't know what improvement I should be asking for, if any. Tobi feel free to close if there's nothing to see here.

**Comment by tbg** [comment]
The JSON output is here:

https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=1684246&_focus=773

This is a bit silly, but in general one cannot conclude from the timeout that the test failed. It just means that there was a timeout.. it is silly that the test output is not more prominently visible.

**Comment by andreimatei** [comment]
I guess what I'd like to easily see is the fact that there was a timeout and the test that was running when the timeout occurred.
I remember writing a bunch of code for one of the issue posters to create fancy reports on timeouts. I don't know how relevant that is / can be to output presented by teamcity, though.

**Comment by tbg** [comment]
> I guess what I'd like to easily see is the fact that there was a timeout and the test that was running when the timeout occurred.

I basically agree, but there's not much we can do here. It would be easier if the `-timeout` flag to `go test` applied to individual tests, but it doesn't, and so Go tooling generally treats the test that times out as an innocent causality, though that's not true. TC should surface it better, though. I will open an issue upstream, they are having issues with their tracker right now.
