### ISSUE TITLE
Improve error messaging when reader cancels the stream. 

### ISSUE THREAD

**Issue by roncrdb** [cockroachdb/cockroach#43953]
**Is your feature request related to a problem? Please describe.**
A user submitted an alert this morning because they were seeing lots of error messages spamming  their log files that read:

`context canceled: readerCtx in Inbox stream handler`

After looking through our source code I found [one hit](https://github.com/cockroachdb/cockroach/blob/cb8cd590d7ed8666ab1aac053ee0e05cfe503a3d/pkg/sql/colflow/colrpc/inbox.go#L228) for this error message: 

```
 case <-readerCtx.Done():
                // The reader canceled the stream.
                return fmt.Errorf("%s: readerCtx in Inbox stream handler (local reader canceled)", readerCtx.Err())
        case <-streamCtx.Done():
                // The client canceled the stream.
                return fmt.Errorf("%s: streamCtx in Inbox stream handler (remote client canceled)", streamCtx.Err())
```

However it is not clear what this error means.  I did learn that this occurs when a SQL query causes more data to be computed from a table than what the final result requires. I also learned that this should be an innocuous issue that leads to no degradation in cluster performance. 

**Describe the solution you'd like**
There are one be two things that we could do here:

1. We could change this from an error to an info message in the logs.
2. If we are not able to change this from an error to an info message, could we add some more clarification as to what exactly this error means and when it will happen.

**Comment by awoods187** [comment]
@asubiotto can you take a look at this?
