### ISSUE TITLE
rangefeed: missing data after merge

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#43967]
When I enable merges in the new kvnemeses test (#43565), it complains that some of the committed puts didn't come out of rangefeed. The test is still new so it's possibly an issue in the test, but the more I look into this, the more it looks like a bug in RangeFeed, so I want to get some more eyeballs on it. Here's a history with some additional logging:

A range merges at some key "77ee96b8" and both halves of the rangefeed disconnect

```
I200114 16:11:13.919750 1291 kv/dist_sender_rangefeed.go:223  [n1] WIP disconnected /Table/50/"ae4022a9"-/Table/51: retry rangefeed (REASON_RANGE_MERGED)
I200114 16:11:13.919906 1350 kv/dist_sender_rangefeed.go:223  [n1] WIP disconnected /Table/50/"77ee96b8"-/Table/50/"ae4022a9": retry rangefeed (REASON_RANGE_MERGED)
```

Both halves attempt to reconnect, the previous-rhs fails with "r29 not found on s1" but the previous-lhs succeeds. The previous-rhs is not tried again.

```
I200114 16:11:13.920050 1265 kv/dist_sender_rangefeed.go:221  [n1] WIP connecting /Table/50/"ae4022a9"-/Table/51
I200114 16:11:13.920095 1265 kv/dist_sender_rangefeed.go:223  [n1] WIP disconnected /Table/50/"ae4022a9"-/Table/51: r29 was not found on s1
I200114 16:11:13.920257 1379 kv/dist_sender_rangefeed.go:221  [n1] WIP connecting /Table/50/"77ee96b8"-/Table/50/"ae4022a9"
```

A change is not emitted because it doesn't overlap with the args.Span in the RangeFeed request (the previous-lhs), which is used in the RangeFeed registration

```
I200114 16:11:13.925278 1381 storage/rangefeed/registry.go:449  WIP key /Table/50/"de94d5bc" 1579018273.905537000,0 didn't overlap registered spans: /Table/50/"77ee96b8"-/Table/50/"ae4022a9"
```

A resolved timestamp is emitted for the entire keyspace of the new range to the RangeFeed that's only registered for the span of the previous-lhs

```
I200114 16:11:13.934671 1379 kv/dist_sender_rangefeed.go:281  WIP got resolved /Table/50/"77ee96b8"-/Max from rangefeed /Table/50/"77ee96b8"-/Table/50/"ae4022a9"
```

I think the bug here is that the resolved timestamp spans should be trimmed to the registration span they're being emitted to. I'm not sure yet why we haven't seen this in the changefeed nemeses test, but it seems to reproduce much more readily when `kv.closed_timestamp.target_duration` is set to 1ms, which we can't do in that test.

**Comment by danhhz** [comment]
Not sure if this is the best fix, but the following diff seems to fix it:

```diff
diff --git a/pkg/storage/rangefeed/registry.go b/pkg/storage/rangefeed/registry.go
index d87f337eed..d483a7f356 100644
--- a/pkg/storage/rangefeed/registry.go
+++ b/pkg/storage/rangefeed/registry.go
@@ -439,6 +439,15 @@ func (reg *registry) PublishToOverlapping(span roachpb.Span, event *roachpb.Rang
 		// Don't publish events if they are equal to or less
 		// than the registration's starting timestamp.
 		if r.catchupTimestamp.Less(minTS) {
+			switch t := event.GetValue().(type) {
+			case *roachpb.RangeFeedCheckpoint:
+				// Trim the checkpoint by the bounds of this registration.
+				event = &roachpb.RangeFeedEvent{Checkpoint: &roachpb.RangeFeedCheckpoint{
+					// TODO(dan): There's no Intersect on Span?
+					Span:       r.span,
+					ResolvedTS: t.ResolvedTS,
+				}}
+			}
 			r.publish(event)
 		}
 		return false, nil

```

**Comment by danhhz** [comment]
@nvanbenschoten Do you have any thoughts on the best fix for this?

**Comment by nvanbenschoten** [comment]
> I think the bug here is that the resolved timestamp spans should be trimmed to the registration span they're being emitted to.

Yes, I think that's exactly what we want to do. This is a case where we want to modify (customize?) the event for each registration. There's actually another case for this - when an individual registration does not have `WITH diff` enabled but someone else does. In those cases, the right thing to do would be to strip the RangeFeedValue when sending to some registrations.

I've been meaning to make the second change and I think both fit well into the same logic, so I'm happy to fix this too, if you'd like.

**Comment by danhhz** [comment]
Works for me! I'm moving my focus to long-running migrations so there's no hurry on this at all
