### ISSUE TITLE
sql: CONFIGURE ZONE USING DEFAULT doesn't behave as intended

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/cockroach#43970]
When applying zone configs, we support a special CONFIGURE ZONE USING DEFAULT syntax. It seems like the intention of this was to explicitly copy all default values into the object's zone configuration. This would mean that if the defaults changed later, the object's configuration would remain the same.

However, the actual behavior appears to be that we just apply an empty zone configuration, which is effectively the same as CONFIGURE ZONE DISCARD.

I'm not sure if this feature was always broken or was broken somewhere along the way and there weren't adequate tests to catch it. I would question if we even want to support this syntax since it seems fairly confusing and not so valuable.

Jira issue: CRDB-5265

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4408](https://cockroachdb.zendesk.com/agent/tickets/4408) has been linked to this issue.

**Comment by awoods187** [comment]
Asked for feedback from the customer on this issue.

**Comment by florence-crl** [comment]
@awoods187 The customer responded:
For our use cases, I agree that the described functionality of CONFIGURE ZONE USING DEFAULT is more confusing than helpful.
