### ISSUE TITLE
kv: verify telemetry for Follower Reads

### ISSUE THREAD

**Issue by johnrk-zz** [cockroachdb/cockroach#43973]
**Is your feature request related to a problem? Please describe.**
To track adoption of [Follower Reads](https://www.cockroachlabs.com/docs/stable/follower-reads.html) in Looker, we need to verify it records external usage of it correctly in the Registration cluster.

At the moment, we receive instances of, the following containing "follower" in the Features Table of the Registration Cluster:

- "othererror.22000.experimental_follower_read_timestamp()"
- "othererror.XXC02.experimental_follower_read_timestamp()"
- "sql.plan.builtins.experimental_follower_read_timestamp()   -> timestamptz"

**Describe the solution you'd like**
I'd like Follower Reads usage to be tracked in the Features Table of the Registration Cluster.

**Describe alternatives you've considered**
n/a

**Additional context**

- Example Looker Report of what we're going after [% of Multi-Region Long Running Clusters Using Follower Reads](https://cockroachlabs.looker.com/looks/95) (using "sql.plan.builtins.experimental_follower_read_timestamp()   -> timestamptz"). It seems low.

Jira issue: CRDB-5264

**Comment by ajwerner** [comment]
A problem with this is that users can use follower reads without invoking `experimental_follower_read_timestamp()`. If a user uses `AS OF SYSTEM TIME '-60s'` and has an enterprise license it will also utilize follower reads. We should probably create another issue to track the number of statements which end up utilizing follower reads. This isn't totally straightforward given the various layers at play. 

Another point of note is that a single or small number of invocations is not necessarily a strong indicator that they're using it regularly. It's probably worth capturing both users who have tried follower reads (invoked the function a small number of times relative to total query execution) vs who use it in production (invoke the function some percentage of the time and have executed some number of queries, maybe .01% of more than 1M queries or something).
