### ISSUE TITLE
Display Errors in SQL Client

### ISSUE THREAD

**Issue by cchhxxttxs** [cockroachdb/cockroach#43994]
**Describe the problem**
1. Chinese characters display wrong in ARRAY TYPE;
2. TIME‘s types display in the same way.

**To Reproduce**
MY SET:
cockroach start --insecure
cockroach sql --insecure

ERRORS:
e.g. SELECT ARRAY['哈哈', '呵呵', '吼吼'];
                                     array                                      
+------------------------------------------------------------------------------+
  {\345\223\210\345\223\210,\345\221\265\345\221\265,\345\220\274\345\220\274}  
(1 row)

e.g. 
SELECT '2019-03-21 21:12:12'::TIME;
            time             
+---------------------------+
  0000-01-01 21:12:12+00:00  
(1 row)
SELECT '2019-03-21 21:12:12'::DATE;
            date             
+---------------------------+
  2019-03-21 00:00:00+00:00  
(1 row)
SELECT '2019-03-21 21:12:12'::TIMESTAMP;
          timestamp          
+---------------------------+
  2019-03-21 21:12:12+00:00  
(1 row)

**Expected behavior**
1. Chinese characters in ARRAY TYPE display right ;
2. TIME‘s types display in right ways.

**Environment:**
 - CockroachDB version:  v19.1.3
 - Server OS:  Linux
 - Client app: cockroach sql --insecure

**Comment by awoods187** [comment]
@otan is this time portion fixed? Or is it the same libpq problem?

**Comment by otan** [comment]
this is lib/pq on both fronts. the underlying value in both is correct. would probably close this and move it under the pgx umbrella task

**Comment by awoods187** [comment]
Makes sense--thanks!

**Comment by knz** [comment]
We had fixed the display of times in v21.1 already. Doing the arrays in #66079.
