### ISSUE TITLE
sql: convert a timestamp to another time zone

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#44027]
Support the postgres function to convert a timestamp to another time zone.

Currently, this is unimplemented:
```SQL
SELECT timezone('America/New_York','2016-06-01 00:00');
ERROR: unknown signature: timezone(string, string)
SQLSTATE: 42883
```
It should return:
```
| timezone--------------------- 2016-06-01 03:00:00(1 row)
-- | --
```

**Comment by awoods187** [comment]
Note that we pass the timestamp as a string to the timezone() function, but PostgreSQL casts it to timestamptz implicitly. 

We could also cast a timestamp value to the timestamptz data type explicitly as the following statement:
```SQL
SELECT timezone('America/New_York','2016-06-01 00:00'::timestamptz);
```

**Comment by otan** [comment]
Not only do we not support it, we also support it backwards -- i.e. `select timezone(timestamptz, string)` works instead of `select timezone(string, timestamptz)`....

**Comment by otan** [comment]
we're also missing support for converting `SELECT time/timetz AT TIME ZONE string` AND `SELECT time/timetz/timestamp/timestamptz AT TIME ZONE interval`
