### ISSUE TITLE
build: upgrade to node 12 LTS

### ISSUE THREAD

**Issue by dhartunian** [cockroachdb/cockroach#44021]
Follow similar steps to bumping golang version documented in the build README

* [x] Adjust version in Docker image ([source](./builder/Dockerfile#L218)).
* [x] Rebuild the Docker image and bump the version in builder.sh accordingly ([source](./builder.sh#L6)).
* [x] Bump the default installed version of nodejs in bootstrap-debian.sh ([source](./bootstrap/bootstrap-debian.sh#L9)).
* [ ] Update the `builder.dockerImage` parameter in the TeamCity `Cockroach` project.

**Comment by kenliu** [comment]
I believe we might have documentation in the public wiki that needs to be updated as well

**Comment by dhartunian** [comment]
@kenliu thanks for the reminder, I bumped the version here: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/181338446/Getting+and+building+from+source

**Comment by irfansharif** [comment]
Unsolicited drive by comment: I think it might be a good idea to send out an e-mail internally telling folks to upgrade their local node version.
