### ISSUE TITLE
sql: incorrect output with FULL JOIN, order changes with selected columns

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#44029]
```
SELECT
    a IS NULL anull, a
FROM
    (VALUES (2)) AS x
    FULL JOIN (VALUES (1))
            AS y (a) ON false
ORDER BY
    a NULLS FIRST;
```

We expect the output (and it is so in postgres) to be:

```
 anull | a 
-------+---
 t     |  
 f     | 1
```

Two rows, one with a=1, the other with a=null. The ORDER BY clause specifies NULLS FIRST, so we expect the NULL row to be first. But in cockroach the order is incorrectly swapped:

```
 anull | a 
-------+---
 f     | 1
 t     |  
```

So we diligently decide, ok, let's select `b` to see what's going on here and reexecute in cockroach:

```
SELECT
    a IS NULL anull, a, b
FROM
    (VALUES (2)) AS x (b)
    FULL JOIN (VALUES (1))
            AS y (a) ON false
ORDER BY
    a NULLS FIRST;
```

```
 anull | a | b 
-------+---+---
 t     |   | 2
 f     | 1 |  
```

Wait what?! The order changed just because we are now selecting the `b` column? Spooky.

Can't reproduce the problem if we hard code the table:

```
SELECT
    a IS NULL, a
FROM
    (
        VALUES
            (1, NULL),
            (NULL, 2)
    )
        AS t (a, b)
ORDER BY
    a NULLS FIRST;
```

So it seems to be a problem related to the join?

**Comment by mjibson** [comment]
Tagging @justinj cuz this seems like it could be optimizer-related?

**Comment by yuzefovich** [comment]
I think it is optimizer-related.

**Comment by RaduBerinde** [comment]
The cardinality of the full join is incorrectly calculated as 1:
```
   ├── full-join (hash)                  
   │    ├── columns: column1:2           
   │    ├── cardinality: [1 - 1]         
   │    ├── stats: [rows=2]              
   │    ├── cost: 0.09                   
   │    ├── key: ()                      
   │    ├── fd: ()-->(2)                 
   │    ├── values                       
   │    │    ├── cardinality: [1 - 1]    
   │    │    ├── stats: [rows=1]         
   │    │    ├── cost: 0.02              
   │    │    ├── key: ()                 
   │    │    └── tuple                   
   │    ├── values                       
   │    │    ├── columns: column1:2      
   │    │    ├── cardinality: [1 - 1]    
   │    │    ├── stats: [rows=1]         
   │    │    ├── cost: 0.02              
   │    │    ├── key: ()                 
   │    │    ├── fd: ()-->(2)            
   │    │    ├── prune: (2)              
   │    │    └── (1,)                    
   │    └── filters                      
   │         └── false                   
```

**Comment by RaduBerinde** [comment]
This is coming from the FDs:
https://github.com/cockroachdb/cockroach/blob/b29e156276317eecea77a940928e420c90e8b82d/pkg/sql/opt/memo/logical_props_builder.go#L1941
This is incorrect in the case where we have an empty key. Not sure if there are other problematic cases. CC @andy-kimball maybe you can take a look and see if you can think of any.

**Comment by andy-kimball** [comment]
I thought through this case, but don't see other cases that would have this problem. It seems restricted to operator(s) where inputs have cardinality <= 1, but output has cardinality > 1. `Left`, `Right`, `Semi`, `Anti` don't have that property. `Union` has the property, but already does right thing. So I think fix is to add a special case for empty keys here, augmenting the existing special case for nullable input columns.
