### ISSUE TITLE
sql: "batch" KV operations across multiple SQL statements

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#4403]
See #4399 for the difference that performing updates to 100 rows with a single statement vs 100 statements can make. The performance benefit of using a single statement stems from the reduced read and write RPCs (1 read + 1 write vs 100 reads + 100 writes).

The difficulty with naively trying to batch KV operations across SQL statements is that it is either difficult or impossible to map errors back to the statement which caused them. We also have to be very careful if the statements have interactions. One thought is to push the worry about inter-statement interaction to the user and ask them to specify when batching should be performed (e.g. `SET TRANSACTION BATCHED`).

**Comment by tschottdorf** [comment]
Looks like the title of this issue is botched.

It doesn't seem to difficult to map an error back to the SQL command which caused it if a batch is built upfront. All that's needed is a method on, say, `Batch` which returns the number of operations in the batch:

```go
var Batch client.Batch
for _, cmd := range commands {
  cmd.MinIndex = batch.Count()
  cmd.Add(&batch)
}
// ...
if pErr != nil {
  index := pErr.Index
  // Do a binary search over commands, looking for the cmd with the leftmost one with `MinIndex >= index`.
}
```

I still believe that a lot of the parallelization work can be performed in DistSender if only the planner figures out a good way of putting more stuff in one batch (i.e. adding to a batch with a system like the above, and only running it when that's necessary).

**Comment by petermattis** [comment]
Title fixed. Sometimes I edit the title and save and it doesn't save.

**Comment by bdarnell** [comment]
If the statements are in a transaction and sent in a single batch, why does it matter which one failed? It seems like enough to simply abort the transaction.

**Comment by tschottdorf** [comment]
The issue is creating the right SQL error from the batch, the standard example being a unique constraint violation (which comes back as a `ConditionFailedError`).

**Comment by bdarnell** [comment]
Ah, right. But even then, does it need to know which statement caused the constraint violation or is it enough to know that *some* unique constraint was violated?

There is a standard SQL command `SET CONSTRAINTS ALL DEFERRED` (implemented in postgres) which delays constraint validation until the transaction commits. That could be one way for the user to signal that they don't care exactly where errors occur.

**Comment by tschottdorf** [comment]
```
root@:15432> insert into x.y values(1);
query error: pq: duplicate key value (id)=(1) violates unique constraint "primary"
```

That information is helpful. Would be sad to let it go. Also, as outlined above, seems easy enough to keep.
