### ISSUE TITLE
ui: statement list follow up work

### ISSUE THREAD

**Issue by Annebirzin** [cockroachdb/cockroach#44040]
Feedback for statement list updates #43875

- [x] Remove statement module that is triggered from the bottom of the page when clicking a statement link. Clicking the statement link should take user directly to statement detail page. (Keep tooltip on hover)

_reference image_
![Screen Shot 2020-01-15 at 1 40 08 PM](https://user-images.githubusercontent.com/51920721/72473021-ce6ac980-37b3-11ea-800e-f5221973ffe4.png)

- [x] Update empty state text and link (design updated here: zpl.io/VYneLKd)
    - [x] Headline copy: `This page helps you identify frequently executed or high latency SQL statements.`
    - [x] Description copy: `No SQL statements were executed since this page was last cleared.`
    - [x] Learn more link `https://www.cockroachlabs.com/docs/stable/admin-ui-statements-page.html`

_updated design_
![Screen Shot 2020-01-15 at 4 21 46 PM](https://user-images.githubusercontent.com/51920721/72472737-23f2a680-37b3-11ea-8475-b5321d35378f.png)

- [x] Add no results state (designs here: zpl.io/2pX1LQJ)
        - [ ] Learn more link `https://www.cockroachlabs.com/docs/stable/admin-ui-statements-page.html`

_updated design_
![Screen Shot 2020-01-15 at 4 23 37 PM](https://user-images.githubusercontent.com/51920721/72472879-7a5fe500-37b3-11ea-9020-b92240a69379.png)

- [x] Update all fonts in table EXCEPT the statement description to `SourceSansPro regular`(only statement description should be `Roboto Mono`)

- [x] Update `App` filter text to Titlecase (ie. `App: All`)

**Comment by piyush-singh** [comment]
Merged
