### ISSUE TITLE
kv: follower reads can fail due to stale cached range descriptors

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#44053]
**Describe the problem**

Follower reads relies on having an up-to-date range descriptor. Currently our mechanisms to evict range descriptors are based primarily on key mismatches or failure to find the leaseholder. Unfortunately if our cached descriptor contains the leaseholder and we have an up-to-date leaseholder cache we'll never evict from our descriptor cache.

The code which handles the `RangeNotFoundError` here notes that the failure to find the replica could be due to the replica not yet having been initialized and that eviction could lead to thrashing.

https://github.com/cockroachdb/cockroach/blob/dba32b33f6eda3af1eef4f8636fb0de592f4cd86/pkg/kv/dist_sender.go#L1717-L1720

The outcome is that sometimes follower reads will always hit a node which does not contain the range and then go on to hit the next closest follower.

**To Reproduce**

This needs reproduction steps. 

**Expected behavior**

Follower reads should eventually occur.

**Comment by ajwerner** [comment]
One approach would be to request range info on subsequent sends and then use the version from the response to decide whether the the descriptor needs to be evicted.

**Comment by ajwerner** [comment]
Other things which could be helpful are visibility into the state of the `RangeCache` and mechanisms to blow it evict from it. The visibility probably isn't controversial, exposing eviction probably is a bit.

**Comment by ajwerner** [comment]
It seems that this issue is due to two different problems. Given the fact that the range in question always had a Replica in the nearby region, I can only assume that the stale range descriptor caught the state of the range while it was in joint consensus. To mitigate this specific problem we should make ranges which are VOTER_OUTGOING or VOTER_INCOMING eligible for follower reads in the DistSender. This change should be backportable to 19.2. This is reasonable, especially for VOTER_INCOMING, because we know that that replica has already received a snapshot. 

The bigger fix is to attach a RangeDescriptor generation to the BatchRequest header and the BatchResponse header which the DistSender can use to determine whether it needs to update the cache.

**Comment by ajwerner** [comment]
It turns out we do already send to VOTER_INCOMING. It's no longer clear that there's a back-portable fix here. 

One option is to kick off a fetch of the range descriptor if we ever have a RangeNotFound error. We probably don't want to actually evict the entry as that would be disruptive. Ideally we could trigger a single-flight refresh without eviction but that's a relatively major change in itself.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[5056](https://cockroachdb.zendesk.com/agent/tickets/5056) has been linked to this issue.

**Comment by jasobrown** [comment]
Is ZD ticket #5099 related to this?

**Comment by andreimatei** [comment]
> Is ZD ticket 5099 related to this?

The relevant public issue for that is https://github.com/cockroachdb/cockroach/issues/47459. 
It's only tangentially related, I'd say. The issue there is that we keep trying to contact a decomissioned node, and the fact that we're not good at updating our range descriptor caches certainly doesn't help. So better caching would improve things, although I'm not completely sure about how the case in which we're failing to connect to a node is going to trigger a cache update. Anyway, we have a more specific fix in mind for #47459, which is to track the nodes' decomissioning state better, and generally not connect to a node that has been successfully decomissioned - even with a bad cache.

**Comment by jasobrown** [comment]
OK, that's reasonable. I heard "range descriptor cache", and tried to put the two tickets together.
