### ISSUE TITLE
sql: incorrect grouping of array with NULL

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#44079]
```
SELECT
    a, a IS NULL AS isnull
FROM
    (
        VALUES
            (NULL),
            ((NULL::TIMESTAMP || NULL::TIMESTAMP[]))
    )
        AS t (a);

SELECT
    *
FROM
    (
        VALUES
            (NULL),
            ((NULL::TIMESTAMP || NULL::TIMESTAMP[]))
    )
        AS t (a)
GROUP BY
    a;
```

In postgres:

```
   a    | isnull 
--------+--------
        | t
 {NULL} | f
(2 rows)

   a    
--------
 {NULL}
 
(2 rows)
```

Cockroach:

```
   a    | isnull 
--------+--------
        | t
 {NULL} | f
(2 rows)

 a 
---
 
(1 row)
```

It seems that we are incorrectly grouping an array with a null with a regular null.

**Comment by rohany** [comment]
cc @yuzefovich where would be the best place to first look here? I haven't looked much at the aggregators.

**Comment by yuzefovich** [comment]
Looking at `EXPLAIN`, in the second query there seems to be no aggregation, but distinct instead.

I guess I don't have any pointers to share from the top of my head though.

**Comment by rohany** [comment]
Retrying this locally I see some different output on cockroach than what is written up on the issue.

```
root@127.0.0.1:55028/movr> SELECT
    a, a IS NULL AS isnull
FROM
    (
        VALUES
            (NULL),
            ((NULL::TIMESTAMP || NULL::TIMESTAMP[]))
    )
        AS t (a);
    a    | isnull
---------+---------
  NULL   |  true
  {NULL} | false
(2 rows)

SELECT
    *
FROM
    (
        VALUES
            (NULL),
            ((NULL::TIMESTAMP || NULL::TIMESTAMP[]))
    )
        AS t (a)
GROUP BY
    a;
   a
--------
  NULL
(1 row)
```

**Comment by yuzefovich** [comment]
The second query is still incorrect. I think Matt might have modified the output of cockroach so that `NULL` is displayed in the same way as with Postgres.

**Comment by solongordon** [comment]
Yes, or he used `psql` to test against both.

**Comment by yuzefovich** [comment]
That sounds more likely :)

**Comment by rohany** [comment]
Ok, we can reproduce simpler this with (given that the explain actually generates a distinct):
```
create table t (x int[]);
insert into t values (NULL),(ARRAY[NULL]);
select distinct * from t;
   x
--------
  NULL
(1 row)
```

We'd expect both the `NULL` and `{NULL}` to show up.

**Comment by rohany** [comment]
I see the problem.

The distinct operator uses `EncodeTableKey` to create a fingerprint for datums. However, `EncodeTableKey` for arrays looks like this:
```
		for _, datum := range t.Array {
			var err error
			b, err = EncodeTableKey(b, datum, dir)
			if err != nil {
				return nil, err
			}
		}
		return b, nil
``` 
Under this encoding format, `NULL` and `ARRAY[NULL]` are encoded as exactly the same, so the distinct can't tell the difference between them.
