### ISSUE TITLE
util/tracing: All trace events should be logged after their corresponding event, not before

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#4408]
This allows the tracer to properly evaluate the time it spent for each event to complete, instead of matching each event with the duration of the previous event. With this, each tracing statement should be written in the past tense (ie. `"copied timestamp cache"` instead of `"copy timestamp cache"`).

**Comment by tamird** [comment]
This presupposes that there's a trace at each step. If there isn't, we'd
want a trace event at the start and finish of each event.

**Comment by tschottdorf** [comment]
I think it makes sense to generally log events "after the fact". For some events it could make sense to have a call before and after to get the exact duration, but I think in most cases it's overkill.

**Comment by JackKrupansky** [comment]
It can make sense for slow operations or operations which may hang, in which case you'd like to be able to look at the log and see what operation is being attempted. But this tends to be a small set of logged operations.

And for operations which may commonly fail with an exception with a stack trace it can be nice to, again, know what operation was being attempted. Although it can usually be fairly obvious from the combination of previously logged info and the stack trace.

**Comment by spencerkimball** [comment]
Add comments to util/tracing indicating the pattern to follow.

**Comment by tschottdorf** [comment]
@dt yours now since you were kind enough to take care of my tracing-related WIP (thanks again for that).

**Comment by arjunravinarayan** [comment]
This issue is no longer relevant, as tracing has improved significantly in the past two years(!!!).
