### ISSUE TITLE
engine: massage engine to work with vectorized file-based queue

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#44086]
In porting over the file-based queue prototype to the cockroach repo (https://github.com/cockroachdb/cockroach/pull/43972), I've run into a couple of kinks while trying to use the `engine.FS` interface instead of the `vfs.FS` interface used by the prototype:

1) When creating a `NewTempEngine` a `pebble.DB` instance is `Open`ed. This doesn't implement the `engine.FS` interface by itself. I could create an `engine.Pebble{}` which does implement `engine.FS`, but creating one through `NewPebble` seems like overkill and just returning `engine.Pebble{}` with the fields set when used as an `engine.FS` seems brittle.

2) In the prototype, I used `vfs.NewSyncingFile` to avoid having to implement `Sync`ing logic. This behavior doesn't seem to be exposed at the `engine` level, so something that achieves the same functionality with an `engine.FS` file is necessary.

3) It would be nice to have the ability to `Mkdir` and `Rmdir` added to the `engine.FS` so that a `Queue` can create a directory, store all of its data there, and then remove it at any time when `Close` is called.

**Comment by sumeerbhola** [comment]
> 1. When creating a `NewTempEngine` a `pebble.DB` instance is `Open`ed. This doesn't implement the `engine.FS` interface by itself. I could create an `engine.Pebble{}` which does implement `engine.FS`, but creating one through `NewPebble` seems like overkill and just returning `engine.Pebble{}` with the fields set when used as an `engine.FS` seems brittle.

Yes it would be brittle, and even now the `Pebble.CreateFile()` does a tiny bit more than forward to `Pebble.fs`. But there is a bigger issue with using `NewPebbleTempEngine`: it does not setup encryption if that is enabled, so you are getting an unencrypted Pebble. I suggest changing `pebbleTempEngine` to call `NewPebble()` and keeping the `engine.Pebble` returned and forwarding to the `engine.Pebble.db` when needed.
 
> 2. In the prototype, I used `vfs.NewSyncingFile` to avoid having to implement `Sync`ing logic. This behavior doesn't seem to be exposed at the `engine` level, so something that achieves the same functionality with an `engine.FS` file is necessary.

Would you like something like:
```
CreateFile(name string, bytesPerSync int) (File, error)
```
where a value of 0 means no sync?
This is easy to implement since we can use `SyncingFile` in the `engine.Pebble` implementation, and `rocksdb::Env::NewWritableFile()` can be passed this value in the `rocksdb::EnvOptions` parameter.

> 3. It would be nice to have the ability to `Mkdir` and `Rmdir` added to the `engine.FS` so that a `Queue` can create a directory, store all of its data there, and then remove it at any time when `Close` is called.

`rocksdb::Env` has `CreateDir(const std::string& dirname)` and `DeleteDir(const std::string& dirname)` methods so this is easy.

**Comment by sumeerbhola** [comment]
> > 1. When creating a `NewTempEngine` a `pebble.DB` instance is `Open`ed. This doesn't implement the `engine.FS` interface by itself. I could create an `engine.Pebble{}` which does implement `engine.FS`, but creating one through `NewPebble` seems like overkill and just returning `engine.Pebble{}` with the fields set when used as an `engine.FS` seems brittle.
> 
> Yes it would be brittle, and even now the `Pebble.CreateFile()` does a tiny bit more than forward to `Pebble.fs`. But there is a bigger issue with using `NewPebbleTempEngine`: it does not setup encryption if that is enabled, so you are getting an unencrypted Pebble. I suggest changing `pebbleTempEngine` to call `NewPebble()` and keeping the `engine.Pebble` returned and forwarding to the `engine.Pebble.db` when needed.

I misspoke -- one can't call `NewPebble()` multiple times since there can be only one encrypted env, which can be shared by multiple `pebble.DB` instances. I'll need to refactor that code a bit.

**Comment by asubiotto** [comment]
> > 1. In the prototype, I used `vfs.NewSyncingFile` to avoid having to implement `Sync`ing logic. This behavior doesn't seem to be exposed at the `engine` level, so something that achieves the same functionality with an `engine.FS` file is necessary.
> 
> Would you like something like:
> 
> ```
> CreateFile(name string, bytesPerSync int) (File, error)
> ```
> 
> where a value of 0 means no sync?

That would work, thanks!

> > 1. It would be nice to have the ability to `Mkdir` and `Rmdir` added to the `engine.FS` so that a `Queue` can create a directory, store all of its data there, and then remove it at any time when `Close` is called.
> 
> `rocksdb::Env` has `CreateDir(const std::string& dirname)` and `DeleteDir(const std::string& dirname)` methods so this is easy.
Great! One other thing we might need is the ability to list files in a directory (mostly to remove all directories with a given prefix). Would that also be simple to add?

**Comment by sumeerbhola** [comment]
> Great! One other thing we might need is the ability to list files in a directory (mostly to remove all directories with a given prefix). Would that also be simple to add?

There is a `Status rocksdb::Env::GetChildren(const std::string& dir, std::vector<std::string>* result)`, so yes this should be simple.
