### ISSUE TITLE
sql: newly created db get grants for root and admin, not user creating the db

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#44118]
Every new db gets privileges for the `root` user specifically and the `admin` group.

See: ` NewDefaultPrivilegeDescriptor()` in `sqlbase`

However if there are multiple users in the admin group, we probably want the user that's running the CREATE to get the grant instead of `root`.

This becomes even more important if CockroachDB is extended to enable other roles than `admin` to create databases. In that case we can't just use the same privileges for all databases.

Jira issue: CRDB-5254

**Comment by knz** [comment]
cc @solongordon

**Comment by knz** [comment]
cc @andreimatei

**Comment by knz** [comment]
this one is still relevant

**Comment by rafiss** [comment]
The `PrivilegeDescriptor` returned by `NewDefaultPrivilegeDescriptor()` now does track the `Owner`, which is defined as the user who created the object. And owners always have privileges on the object. See https://github.com/cockroachdb/cockroach/commit/0faf0a1a168105551c0d6d126eff25068e865e01

I think we want to preserve the behavior of giving privileges to root and admin.

@knz do you consider that sufficient, or is something still misisng?

**Comment by knz** [comment]
The primary req above is probably suitably addressed by the owner mechanism.

But let's take this one step further.

Why do we still grant privs on `root` and `admin` by default? Presumably, the priv check will always accept access for `admin` members (and bypass the info in the descriptor)
