### ISSUE TITLE
devinfra: label each merged PR with the earliest version that contains it

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#44122]
When dealing with customer issues, it is frequently useful to know which release contains a certain PR. You can do it manually each time but it is a bit tedious. It would be awesome if we had a script that periodically adds a tag or comment to merged PRs with the earliest released version that contains the commits in the PR.

**Comment by jlinder** [comment]
Triage notes:

Effort: low

This would be a pretty straight-forward script to write. It could be run manually during the release process (for fastest updating) or on a daily, semi-weekly or weekly basis via a cron-type mechanism.

One way for a script like this to work is:

```
Take in a set of versions to check for if the PR's commits are in
Check out the latest repository with all tags
For PRs going back X months:
  For each version to check:
    If the PR's commit is not in the version (check with `git log <version> | grep <sha>`):
      continue
    If an X.Y.0 tag that is older than version is on the PR:
      continue
    If an older patch tag for the same X.Y as the version is on the PR:
      continue
    Tag the PR with the version
```

**Comment by bobvawter** [comment]
`git tag --contains <commitId>` helps here.

**Comment by jlinder** [comment]
Additional suggestions:

- Use labels. They'll be easier to check programatically and to query for.
- For label name, how about: `earliest-release-v*`?

**Comment by jlinder** [comment]
@alan-mas asked some questions to get clarification on how the script will be run. These notes are the result:

How we'll run this script:

- via a build configuration in TeamCity as part of the release process
- manually until the build configuration is set up
- manually to populate the historical information for PRs in already released releases

The script will live at `scripts/label-prs-with-earliest-release.sh` in the cockroach repo. The build configuration in TeamCity will call it from the `build/release/teamcity-label-prs-with-earliest-release.sh` script.

The `scripts/label-prs-with-earliest-release.sh` will work as follows:

- It will take these parameters:
    - `START_REF`: A ref to the commit to start looking at.
        - In the build configuration, this will be the tag of the release that was just made. For example: `v21.1.0-rc.1`.
    - `STOP_REF`: An optional parameter of a ref to a commit to process back to.
- If `STOP_REF` is not provided, the script will go backward in history until it finds a commit with a tag and take that commit as the ref to stop at.
- The script will find all merge commits for pull requests between `START_REF` and `STOP_REF`. A merge commit PR is identified by it’s first line of the commit message starting with `Merge pull request #12345` where `12345` is the PR number.
- For each `COMMIT_SHA` that is found
    - run the `TAG=$(git tag --contains ${COMMIT_SHA})` command to find the containing tag
    - check if the `earliest-release-v${TAG}` label exists in the cockroach repo in GitHub and create it if it does not exist
    - check if a label for an earlier release on that release branch already exists. If so, `continue` to the next commit
    - add the label for `${TAG}` to the PR
