### ISSUE TITLE
Official Sequelize ORM

### ISSUE THREAD

**Issue by Salamdev** [cockroachdb/cockroach#44129]
Is there any problem or error if I use official Sequelize ORM?

**Comment by awoods187** [comment]
We recommend trying our own implementation (https://github.com/cockroachdb/sequelize-cockroachdb). You can follow docs here: https://www.cockroachlabs.com/docs/stable/build-a-nodejs-app-with-cockroachdb-sequelize.html

Let us know if you run into any issues!
