### ISSUE TITLE
roachperf: values not scaling on multiregion performance 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#44138]
The roachperf values aren't scaling on the y-axis correctly making day to day variation hard to tell. 
![image](https://user-images.githubusercontent.com/22278911/72744170-10f92100-3b7b-11ea-9bb4-6337f052ae86.png)

https://roachperf.crdb.dev/?filter=&view=tpccbench%2Fnodes%3D9%2Fcpu%3D4%2Fmulti-region&tab=gce

Jira issue: CRDB-5249

**Comment by ajwerner** [comment]
I think this is actually https://github.com/cockroachdb/cockroach/issues/41312 

For this test we're generating data from multiple workload binaries and we're not combining that for the UI.

**Comment by bobvawter** [comment]
It's a rendering bug; there's data there.

![Screen Shot 2020-01-21 at 3 41 38 PM](https://user-images.githubusercontent.com/1158548/72841521-8db3fa00-3c64-11ea-8384-67deefd1e01b.png)

**Comment by herkolategan** [comment]
The display is not working since it calculates an efficiency of 33%, although during the actual test we get:
```
2024/08/24 15:04:40 tpcc.go:1759: --- SEARCH ITER PASS: TPCC 2500 resulted in 31234.3 tpmC (99.1% of max tpmC)
```
As mentioned this is an aggregation bug, since we run a workload in each region, it needs to be aggregated.
