### ISSUE TITLE
Generated column causes query to omit a record in the result set

### ISSUE THREAD

**Issue by mrigger** [cockroachdb/cockroach#44132]
Consider the following test case:

```sql
CREATE TABLE t0(c0 BOOL UNIQUE, c1 INT AS (NULL) STORED);
INSERT INTO t0 (c0) VALUES (true);
SELECT * FROM t0 WHERE c0; -- expected: row is fetched, actual: row is not fetched
```
Unexpectedly, the query does not fetch the single row from t0. This bug seems to be caused by/related to the generated column, since the query works correctly when removing `c1`:

```sql
CREATE TABLE t0(c0 BOOL UNIQUE);
INSERT INTO t0 (c0) VALUES (true);
SELECT * FROM t0 WHERE c0; -- row is fetched
```
I found this issue in commit `3bb183403b4bc75c25fbcfc69d7d35de76d2b984` on Ubuntu 19.04.

**Comment by rohany** [comment]
The plan with the stored column uses an index-join (with no source rows?) rather than a scan (which gets planned without the stored column). Does anyone know why this is the case?

```
root@127.0.0.1:56231/movr> explain SELECT * FROM t0 WHERE c0;
     tree     |    field    | description
--------------+-------------+--------------
              | distributed | false
              | vectorized  | false
  index-join  |             |
   │          | table       | t0@primary
   │          | key columns | rowid
   └── norows |             |
```
vs
```
root@127.0.0.1:56257/movr> explain SELECT * FROM t0 WHERE c0;
  tree |    field    | description
-------+-------------+---------------
       | distributed | false
       | vectorized  | false
  scan |             |
       | table       | t0@t0_c0_key
       | spans       | /1-/2
```

**Comment by solongordon** [comment]
@RaduBerinde The plan @rohany shared looks fishy. Would you mind taking a look and kicking it back to us if it's an execution issue?

**Comment by RaduBerinde** [comment]
We add `c1 = NULL` as a filter (in the hope that it helps with span generation). This is not correct when NULLs are involved; it should be `c1 IS NOT DISTINCT FROM NULL`. CC @andy-kimball

**Comment by RaduBerinde** [comment]
Note - this bug is only on `master`.
