### ISSUE TITLE
Unexpected error when using EXPERIMENTAL SCRUB

### ISSUE THREAD

**Issue by mrigger** [cockroachdb/cockroach#44142]
Consider the following test case:

```sql
CREATE TABLE t0(c0 STRING UNIQUE, c1 STRING COLLATE en PRIMARY KEY);
EXPERIMENTAL SCRUB TABLE t0; -- ERROR: scrub-index: unsupported comparison operator: <collatedstring{en}> IS NOT DISTINCT FROM <unknown>
```

Unexpectedly, the `EXPERIMENTAL SCRUB` statement results in an error `scrub-index: unsupported comparison operator: <collatedstring{en}> IS NOT DISTINCT FROM <unknown>`. When removing the column definition of c0, the statement executes as expected.

I noticed that the statement is only [partially implemented](https://github.com/cockroachdb/cockroach/issues/10425), but this does not seem to be a documented or expected limitation.

I found this potential issue in commit `3bb183403b4bc75c25fbcfc69d7d35de76d2b984` on Ubuntu 19.04.

**Comment by otan** [comment]
this is fixed by https://github.com/cockroachdb/cockroach/pull/45260, as it now works on master.
