### ISSUE TITLE
DEFAULT value causes unexpected syntax error when executing INSERT

### ISSUE THREAD

**Issue by mrigger** [cockroachdb/cockroach#44148]
Consider the following test case:
```sql
CREATE TABLE t0(c0 BOOL DEFAULT (NULL BETWEEN ('' COLLATE en) AND ''));
INSERT INTO t0(c0) VALUES(DEFAULT); -- ERROR: at or near "collate": syntax error
```

Unexpectedly, the `INSERT` causes a syntax error:

```
ERROR: at or near "collate": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
SET ROW (NULL BETWEEN '':::STRING COLLATE en AND '':::STRING)
                                  ^
HINT: try \h SET SESSION
```
The expression seems to be valid, as demonstrated by the following `SELECT`, which executes without errors:

```sql
SELECT NULL BETWEEN ('' COLLATE en) AND ''; -- NULL
```

I found this issue in commit `3bb183403b4bc75c25fbcfc69d7d35de76d2b984` on Ubuntu 19.04.

**Comment by rohany** [comment]
There looks like multiple bugs here -- 

```
SELECT NULL BETWEEN ('' COLLATE en) AND ''; -- NULL
```
shouldn't be valid, as I don't think we can compare collated and uncollated strings (at least postgres doesn't seem to allow that.

But it should still parse.

**Comment by rohany** [comment]
Looking at our SQL grammar, the production allowed in a default statement is `DEFAULT b_expr`, where `b_expr` is a restricted expression set (basically only allowing simpler binary operators). `exp BETWEEN exp AND exp` is not allowed. We probably can't increase what is allowed within `b_expr` without introducing shift/reduce conflicts, while we can't switch default to using `a_expr` based on this comment in the code:

```
// DEFAULT expression must be b_expr not a_expr to prevent shift/reduce
// conflict on NOT (since NOT might start a subsequent NOT NULL constraint, or
// be part of a_expr NOT LIKE or similar constructs).
```

**Comment by rohany** [comment]
Closing this because my explanation for the parsing difficulty was incorrect. The only bug here was the type checking error.
