### ISSUE TITLE
Incorrect result for BETWEEN SYMMETRIC query

### ISSUE THREAD

**Issue by mrigger** [cockroachdb/cockroach#44154]
Consider the following test case:

```sql
CREATE TABLE t0(c0 BOOL UNIQUE, c1 BOOL CHECK (true));
INSERT INTO t0(c0) VALUES (true);
SELECT * FROM t0 WHERE t0.c0 AND (false NOT BETWEEN SYMMETRIC t0.c0 AND NULL AND true); -- unexpected: row is fetched
```

Unexpectedly, the query fetches a row, even though the predicate should evaluate to `NULL`:
```sql
SELECT t0.c0 AND (false NOT BETWEEN SYMMETRIC t0.c0 AND NULL AND true) FROM t0; -- NULL
```
When removing the `CHECK (true)` from `t0`, the query works correctly.

I found this bug using commit `3bb183403b4bc75c25fbcfc69d7d35de76d2b984` on Ubuntu 19.04.

**Comment by RaduBerinde** [comment]
Problem is in GenerateConstrainedScans:
```
================================================================================
GenerateConstrainedScans
  Cost: 5.12
================================================================================
  -select
  +index-join t0
    ├── columns: c0:1(bool!null) c1:2(bool)
  - ├── scan t0
  - │    ├── columns: c0:1(bool) c1:2(bool)
  - │    └── check constraint expressions
  - │         └── true [type=bool]
  - └── filters
  -      ├── variable: c0 [type=bool]
  -      └── or [type=bool]
  -           ├── not [type=bool]
  -           │    └── null [type=bool]
  -           └── and [type=bool]
  -                ├── gt [type=bool]
  -                │    ├── variable: c0 [type=bool]
  -                │    └── false [type=bool]
  -                └── lt [type=bool]
  -                     ├── variable: c0 [type=bool]
  -                     └── false [type=bool]
  + └── scan t0@t0_c0_key
  +      ├── columns: c0:1(bool!null) rowid:3(int!null)
  +      └── constraint: /1: [/true - /true]
```

**Comment by RaduBerinde** [comment]
The problem is here:
https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/opt/xform/custom_funcs.go#L321

Any filter that is not the same with an input filter is assumed to be there because we added it from check constraints or other stuff. But that's not necessarily true, in this case, the filters from which we get the constraints are:
```

-- allFilters: filters
 ├── variable: <col1> [type=bool, outer=(1), constraints=(/1: [/true - /true]; tight), fd=()-->(1)]
 ├── or [type=bool, outer=(1)]
 │    ├── not [type=bool]
 │    │    └── null [type=bool]
 │    └── and [type=bool]
 │         ├── gt [type=bool]
 │         │    ├── variable: <col1> [type=bool]
 │         │    └── false [type=bool]
 │         └── lt [type=bool]
 │              ├── variable: <col1> [type=bool]
 │              └── false [type=bool]
 └── true [type=bool]
```
and the remaining filters are:
```
-- remainingFilters: filters
 └── or [type=bool, outer=(1)]
      ├── not [type=bool]
      │    └── null [type=bool]
      └── lt [type=bool]
           ├── variable: <col1> [type=bool]
           └── false [type=bool]
```

It is partially simplified by the index constraint generator and that causes it to be removed.

By the way, it also seems wrong that int he code above we add `inBetweenRemainingFilters` to `remainingFilters` which this code would discard. Perhaps we didn't test the combination of partitioning and check constraints well enough.

I am not sure what the right fix is here..  Maybe we should only remove filters which we know are identical to a check constraint.

**Comment by RaduBerinde** [comment]
This issue also shows that we're missing a normalization rule for `NOT NULL => NULL`. If we add that, the example starts working but the underlying cause is still there. Here is an alternate query that fails regardless of that rule (note the lack of a filter on `c1` in the plan):
```
opt
SELECT * FROM t0 WHERE t0.c0 AND (c1 OR (c0 > false AND c0 < false)) 
----
scan t0
 ├── columns: c0:1(bool!null) c1:2(bool!null)
 ├── constraint: /1: [/true - /true]
 ├── cardinality: [0 - 1]
 ├── key: ()
 └── fd: ()-->(1,2)
```

**Comment by RaduBerinde** [comment]
This code is altogether very fragile. We are Unioning two constraints (one which assumes the data is only in defined partitions, and one for the "in-between" areas). Some of the remaining filters apply to only one and are invalid to keep. There is no guarantee from the index constraint builder that input filters either are removed completely or are returned as remaining filters unchanged; they could be simplified.

I've been debating several possible directions for a fix. I think the cleanest would be to extend the index constraints library a bit, and allow to specify only a subset of filters for the `RemainingFilters` call. That way we won't have to guess which remaining filters we need to filter out.
