### ISSUE TITLE
pgwire, sql: pgjdbc ResultSet.insertRow fails due to missing Table OID

### ISSUE THREAD

**Issue by jhkuperus** [cockroachdb/cockroach#44161]
**Describe the problem**

We are trying to migrate an application based on the Axon Framework. Within this framework we've configured the `JdbcTokenStore` to handle reading and creating tokens for event processing. When we run this on CockroachDB, an obscure error pops up: `ERROR: Column "" not found`.

It took us some time to figure out where the `Column ""` was coming from, but we found it. The `JdbcTokenStore` adds a token to the database by using the following snippet:

```
resultSet.moveToInsertRow();
resultSet.updateObject(schema.tokenColumn(), token == null ? null : entry.getSerializedToken().getData());
resultSet.updateString(schema.tokenTypeColumn(),
        token == null ? null : entry.getSerializedToken().getType().getName());
resultSet.updateString(schema.timestampColumn(), entry.timestampAsString());
resultSet.updateString(schema.ownerColum(), entry.getOwner());
resultSet.updateString(schema.processorNameColumn(), processorName);
resultSet.updateInt(schema.segmentColumn(), segment);
resultSet.insertRow();
```

The error occurs on the last line of the snippet. We've traced the error to the `PgResultSet` from the postgresql JDBC-driver, which actually creates the statement `INSERT INTO TokenEntry("") VALUES ($1)`. This baffled us for a bit so we went on debugging and found the following piece of code hidden inside `PgResultSetMetaData`:

```
  public String getBaseColumnName(int column) throws SQLException {
    Field field = getField(column);
    if (field.getTableOid() == 0) {
      return "";
    }
    fetchFieldMetaData();
    FieldMetadata metadata = field.getMetadata();
    return metadata == null ? "" : metadata.columnName;
  }
```

While debugging, the `field.getTableOid()` always returns `0`, causing all field names to be resolved to the empty string (`""`). This in turn cause the `HashMap<String, Object> updateValues` in `PgResultSet` to have exactly 1 entry `<"", 0>`, which is the result of the last `resultSet.updateXXX` in the snippet up on top of this issue. This then creates the invalid statement `INSERT INTO TokenEntry("") VALUES ($1)` and makes the whole thing break.

**To Reproduce**

See above.

**Expected behavior**

Apparently, the `pgjdbc`-driver expects/requires all field-metadata to include a non-zero value for Table OID when it is reading the resultset-metadata. (This happens inside `QueryExecutorImpl.receiveFields` on line 2456). 

From what I could find in the Cockroach internal schemas and `pg_*` tables, there are no OIDs assigned to tables, which is probably why this value is `0` for all tables. 

I would expect the `ResultSet.insertRow` to behave properly.

**Environment:**
 - CockroachDB version v19.2.0
 - Server OS: Official Docker container
 - Client app: JDBC using version 42.1.4 of `org.postgresql:postgresql`

**Additional context**

I have created a local fork of the Postgresql JDBC driver and removed the if-statement to see if things would work normally after this. I can confirm that database operations perform as expected when this is done. So as far as I can see, there are no other issues holding back `ResultSet.insertRow`.

**Comment by jhkuperus** [comment]
I've forked the PGJDBC-driver and "patched" the issue there so we can at least continue integrating CockroachDB into our application. If you're curious about the exact fix, you can find it in this commit: https://github.com/jhkuperus/pgjdbc/commit/1a32473b2ce3afbe0f93bdcd952e0d8af79345f9

**Comment by rafiss** [comment]
@jhkuperus Thank you for filing this issue. Could you say which tables in `pg_catalog` you have looked at that show an OID of 0 for all tables?

I looked at the `attrelid` column of `pg_catalog.pg_attribute` in a 19.2 CockroachDB cluster, and did not see any 0 OIDs. Also, the `oid` column of `pg_catalog.pg_class` does not have any zeroes.

**Comment by jhkuperus** [comment]
Well, when I take a look at those tables with the `cockroach sql` tool, I don't see any zeroes either. The problem occurs when PGJDBC is decoding the response to a query from Cockroach. This is the order of values read by PGJDBC:

```
      String columnLabel = pgStream.receiveString();
      int tableOid = pgStream.receiveInteger4();
      short positionInTable = (short) pgStream.receiveInteger2();
      int typeOid = pgStream.receiveInteger4();
      int typeLength = pgStream.receiveInteger2();
      int typeModifier = pgStream.receiveInteger4();
      int formatType = pgStream.receiveInteger2();
```

All of the values get a `0` here for `tableOid`. The query itself is not a complex one: `SELECT segment FROM TokenEntry WHERE processorName = ? ORDER BY segment ASC`.

I've been looking into the PGJDBC driver to see what this value is used for: it's used to select field metadata from the `pg_catalog` to set a series of flags like `isNullable`, `isAutoIncrement` etc. When `tableOid == 0` , it fills in just a bit of default values.

Please tell me how I can help you see/understand the issue better.  I really want to help get this resolved :)

**Comment by rafiss** [comment]
Thanks for the further details! That does help.

The relevant CockroachDB code is in the `writeRowDescription` function of pgwire/conn.go.
```
c.msgBuilder.putInt32(0) // Table OID (optional).
c.msgBuilder.putInt16(0) // Column attribute ID (optional).
```

It would be great to have this fixed! If you are interested in taking a shot at it, we always appreciate external contributions. Otherwise, we hope to get to this later.

**Comment by jhkuperus** [comment]
I'll take a look. Thanks for the pointer!

**Comment by jhkuperus** [comment]
Awesome! I had put some effort in getting a Go-workspace up and browsing the code. It was still on my personal backlog to dive into the code. I'll have a look at the merged PR to familiarise myself with the changes for future reference.

Thanks for fixing it!

**Comment by rafiss** [comment]
@jhkuperus You're welcome! Once our next release goes out, please do let me know if this works for you.

And thank you for the bug report and your interest in contributing. Once your workspace is set up, and you feel ready, I'd be happy to point you to another issue. We always are excited to have first-time contributors. :)

**Comment by jhkuperus** [comment]
@rafiss : Is the fix for this issue already in a released version? I tried it on 20.1.3, but it seems I still get the error message. I'd like to confirm I'm looking at the right versions before diving deeper into it.

**Comment by rafiss** [comment]
@jhkuperus This fix is included in 20.1.3.

Soon after fixing this bug, we discovered another issue: #49215. The issue there is that the table OID metadata is missing for responses to prepared statements.

I took a look at the source code for AxonFramework, and I believe that it is indeed running into issue #49215. See the method [`selectForUpdate` which creates a PreparedStatement](https://github.com/AxonFramework/AxonFramework/blob/777aa9eeb23536fbbc1b6b8f50afd830bf5d695e/messaging/src/main/java/org/axonframework/eventhandling/tokenstore/jdbc/JdbcTokenStore.java#L275) whose ResultSet is used in the `insertTokenEntry` method.

One bit of good news is that it appears the AxonFramework seems to have updated this code so that it no longer relies on the table OID being populated in order to make these updates. See issue https://github.com/AxonFramework/AxonFramework/issues/1165 which was addressed by this PR: https://github.com/AxonFramework/AxonFramework/pull/1166/

Would you be able to use a version of Axon Framework that includes that change?

Out of curiosity, how have you been working around the issue so far?

**Comment by jhkuperus** [comment]
Then I guess we ran into the new issue :) An update to our Axon-dependencies was planned. I will try this locally this week and see what happens with 20.1.3. 

As for our work-around. When I first found this issue, I looked at Cockroach and the pgjdbc-driver. While tracing the calls within the pgjdbc-driver, I noticed the "fallback"-code used when the Table OID was `0` raised the exception, but actually added no value whatsoever. Inquiring at the pgjdbc-driver hit a dead end, so I decided to fork the driver and comment out the fallback-clause. We've bumped several versions of the driver since then, constantly re-applying the patch and it still works just fine. You can see the "fix" here: https://github.com/jhkuperus/pgjdbc/commit/1a32473b2ce3afbe0f93bdcd952e0d8af79345f9

I'll get back to you later this week when I've tried to use a newer Axon-version.

**Comment by rafiss** [comment]
Sounds good! I look forward to hearing how it goes.

**Comment by jhkuperus** [comment]
Right. It's a bit later than "I'll get back to you this week"... Summer holiday threw a bit of a wrench in my schedule.

We've tried your suggestion to upgrade Axon and I can safely say: we are not seeing this issue anymore. At the moment we are running these versions together:

* Axon : `4.2.1`
* Cockroach : `20.1.4`
* postgresql driver : `42.2.14`

Thanks again for your assistance in this issue. We are now free from custom forks again 🎉
