### ISSUE TITLE
sql: benchmark multi-statement transaction performance

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#4416]
#4399 change the `BenchmarkUpdate*` benchmarks to use a single statement. We should re-add a multi-statement transaction benchmark, perhaps using `INSERT` or `SELECT` instead of `UPDATE`.

**Comment by dt** [comment]
We could make the existing bank benchmark multi-statement (eg more like pgbench's bank)?

**Comment by petermattis** [comment]
It would be useful to make the bank benchmark mirror pgbench, though I'm not sure if that addresses this issue. I think a multi-statement benchmark which tests 1 vs 10 vs 100 statements would more clearly highlight the current performance of multi-statement transactions.

**Comment by bdarnell** [comment]
We're moving away from go benchmarks to more real-world testing with `roachprod` and `roachperf`, so I don't think there's any reason to keep this issue open.
