### ISSUE TITLE
Users who's userID start with a number can't be granted privledges

### ISSUE THREAD

**Issue by keith-mcclellan** [cockroachdb/cockroach#44160]
**Describe the problem**

It appears that userIDs that start with a number can't be granted permissions in 19.2.2

**To Reproduce**

CREATE USER allen;
CREATE USER '84929';
CREATE DATABASE pbj;
grant all on database pbj to allen;

GRANT
 
Time: 480.043712ms
 
grant all on database pbj to 84929;

invalid syntax: statement ignored: at or near "84929": syntax error

DETAIL: source SQL:

grant all on database pbj to 84929;

                             ^

HINT: try \h GRANT

grant all on database pbj to '84929';

invalid syntax: statement ignored: at or near "84929": syntax error

DETAIL: source SQL:

grant all on database pbj to '84929'

                             ^

HINT: try \h GRANT

**Expected behavior**
A numeric userid should function the same as an alphanumeric userid/

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version 19.2.2
 - CentOS 7.x
 - CockroachDB SQL client

**Additional context**

**Comment by solongordon** [comment]
Try using double-quotes rather than single. `grant all on database pbj to "84929"`.
