### ISSUE TITLE
Kubernetes Operator Telemetry

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach#44173]
**Is your feature request related to a problem? Please describe.**
For our upcoming Operator tool, we don't have a plan for how we'll track usage in our telemetry.

**Describe the solution you'd like**
For both CockroachCloud and non-CockroachCloud deployments, we need to be able to clearly track Operator installs and usage. Per Keith's comments, we may use "an environment variable, so that the telemetry service knows that it's an operator install." 

**Describe alternatives you've considered**.
N/A

**Additional context**
Here's our Airtable issue for more context: https://airtable.com/tblD3oZPLJgGhCmch/viw5pppPOJw29NT6W/recyDZ3jhsnQxfGWw?blocks=hide

**Comment by keith-mcclellan** [comment]
from @nstewart :

Per our slack conversation, there is a "COCKROACH_CHANNEL" environment variable that you can set to ensure any operator work shows up properly in our telemetry (provided the customer is allowing telemetry to reach our reg cluster). Here's an example of how we track helm usage.

The #telemetry team on slack will be able to help you with any questions.

**Comment by johnrk** [comment]
closing this issue in favor of this new issue in the Kubernetes Operator repository: https://github.com/cockroachdb/cockroach-operator/issues/189
