### ISSUE TITLE
cockroach-rocksdb-* log severity flag

### ISSUE THREAD

**Issue by karlseguin** [cockroachdb/cockroach#44192]
This might be a documentation issue, but as far as I can tell, there's no way to control the severity logged into the cockroach-rocksdb logs.

**Comment by knz** [comment]
An update on this:

- neither RocksDB nor Pebble use logging levels
- therefore there is no filter/threshold that can be applied to select certain entries over others
- at this point, we are expecting most messages to be informational. Any "noteworthy" messages would be sent to the main crdb logs instead.

**Comment by knz** [comment]
We've looked into this. Given that the rocksdb/pebble verbose messages are not impacting log file retention for other logging targets (see #50599) we've decided not to take action on this for now.
