### ISSUE TITLE
storage: transfer leases and leadership more thoroughly on graceful shutdown

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#44204]
When we drain a server, we spent a total of at most five seconds (per store) to move leases and Raft leaders to other nodes before we continue shutting down:

https://github.com/cockroachdb/cockroach/blob/f702e9d118d5ea4daa50d7ca01549d041ee2f35c/pkg/storage/store.go#L969-L991

In large deployments, this may not be enough. We need to improve this logic; ideally it can determine with good enough accuracy when to give up (for example, a single surviving node in a three node deployment has no chance at transferring leases away), or we can justify trying "forever" (i.e. until the operator issues a hard shutdown). Ideally we don't need to introduce another knob.

**Comment by knz** [comment]
fixed by #45149
