### ISSUE TITLE
Setup Lerna in UI repo

### ISSUE THREAD

**Issue by nathanstilwell** [cockroachdb/cockroach#44210]
this is a sub-issue of #43906 (it probably belongs in the [cockroach/ui](https://github.com/cockroachdb/ui/) repo, but for visibility and inclusion in the Observability project I'm including it here)

Set up [Lerna](https://github.com/lerna/lerna#getting-started) to publish packages to npm
- [ ] run `npx lerna init`
- [ ] evaluate _Fixed/Lock_ vs _Independant_ modes to determine best use-case for packages
- [ ] (optional) Test publish a placeholder package.

**Comment by piyush-singh** [comment]
This is done! Nathan to fill in details
