### ISSUE TITLE
release-19.1: sql: at least one replica is required when using num_replicas = COPY FROM PARENT

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#44231]
There appears to have been a regression in v19.1.6 where subzones do not interact properly in all cases with COPY FROM PARENT, which can result in an unexpected error.

### Reproduction Steps

```
roachprod create local -n 4
roachprod stage local release v19.1.6
roachprod start local:1-3 --racks=3
roachprod run local:4 -- ./cockroach workload fixtures import tpcc {pgurl:1}
roachprod sql local:1
# run the following in the SQL shell 3 or more times (yes, three times or more!)
# ALTER INDEX tpcc.customer@customer_idx CONFIGURE ZONE USING num_replicas = COPY FROM PARENT, constraints = '{"+rack=1":1}', lease_preferences = '[[+rack=1]]';

pq: could not validate zone config: at least one replica is required
```

This is not present in v19.1.5 or below. It is also not present in v19.2.0 or above.

I tracked this down to only occurring with subzones because the same issue does not occur when you run:
```
ALTER TABLE tpcc.customer CONFIGURE ZONE USING num_replicas = COPY FROM PARENT, constraints = '{"+rack=1":1}', lease_preferences = '[[+rack=1]]';
```

So based on the timing and the behavior, I think it's likely that this was a result of https://github.com/cockroachdb/cockroach/pull/41699.

@rohany can I get you to take this over? I suspect you'll have additional insight into what's going wrong here. You might also know just by looking at it why this was caused by https://github.com/cockroachdb/cockroach/pull/41699. Did that change simply reveal a different bug?

**Comment by rohany** [comment]
It's pretty strange that this doesn't show up in v19.2.0 and above because the PR that was backported (https://github.com/cockroachdb/cockroach/pull/41506) was also backported onto 19.2. Maybe there's something different about how this is done in the 19.1 branch. I can investigate this further.

**Comment by rohany** [comment]
Alright, this is reproduceable in a sql shell with:

```
create table t (x int, index i (x));
alter index t@i configure zone using num_replicas=copy from parent;
alter index t@i configure zone using num_replicas=copy from parent;
alter index t@i configure zone using num_replicas=copy from parent
```

**Comment by rohany** [comment]
AH! I think I see the problem. In 19.2, we changed what identified a zone as a "subzone placeholder", which the mentioned PR might have depended on implicitly.

**Comment by rohany** [comment]
Whats weird is that after the second alter index, the index has a zone configuration with num_replicas = 0, but this isn't caught by the validator.
