### ISSUE TITLE
roachpb: add alternate Key.Next that mutates the receiver instead of copying

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#4424]
Currently, `Key.Next` creates a new copy of the key. In some inner loops this extra copy is wasteful when the receiver not going to be used. This appears as something like:

```
  key = key.Next()
```

A faster alternative is to do something like:

```
  key = append(key, 0)
```

The only challenge is what to name this method. `FastNext`? `InplaceNext`? See `MVCCResolveWriteIntentRange` for one use of `append(key, 0)` that could be replaced with this new method.

**Comment by tschottdorf** [comment]
and then fix this part in `mvcc.go`:

```
		// nextKey is already a metadata key. We append a 0 byte which is the same
		// as roachpb.Key.Next but without creating a new copy.
		keyBuf = append(keyBuf, 0)
		nextKey.Key = keyBuf

```
