### ISSUE TITLE
sql: queued schema changers are not restored on interactive txns

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#4428]
... leading to at least the synchronous path of applying schema changes not taking place.

To repro, do something like:
```
BEGIN; CREATE DATABASE x; CREATE TABLE x.t (a INT); <CR>
CREATE INDEX foo ON x.t (a);
```
I've put a log stmt in `SchemaChanger::exec()` and observed it doesn't execute.

**Comment by vivekmenezes** [comment]
You didn't call COMMIT

**Comment by vivekmenezes** [comment]
but yeah if the COMMIT came in a different request it wouldn't get applied.

I think I'd close this issue unless you think it is that important it get applied through the sync path.

**Comment by andreimatei** [comment]
yes, I wasn't clear. Meant they didn't execute after the subsequent `COMMIT
