### ISSUE TITLE
sql: telemetry needed for CONFIGURE ZONE

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach#44309]
**Is your feature request related to a problem? Please describe.**
In the Features table within the Registration Cluster, it appears we don't track CONFIGURE ZONE (https://www.cockroachlabs.com/docs/stable/configure-zone.html).

**Describe the solution you'd like**
Ideally, we are able to query in Looker customers' usage of CONFIGURE ZONE and what context they're using it in terms of variables and levels.

With CONFIGURE ZONE, having all of the possible variables being reported, such as num_replicas and constraints, informs us on how customers are operating CRDB in production. It helps to know if a variable is not being used, as it may be an opportunity for further education.

For customers configuring with Replication Zones (https://www.cockroachlabs.com/docs/stable/configure-replication-zones.html), we need to see the zone level being used as well, such as Row or Cluster level configurations.

**Describe alternatives you've considered**
I've queried the Features Table for "configure" and "zone." The Statements Table has been deprecated.

**Comment by otan** [comment]
> Ideally, we are able to query in Looker customers' usage of CONFIGURE ZONE and what context they're using it in terms of variables and levels.

i will want concrete examples of how you want these stats to look. example `CONFIGURE ZONE` to telemetry examples would be useful here.

**Comment by johnrk** [comment]
@otan, I would like these stats to capture a record and their value(s) of each time a [zone config variable](https://www.cockroachlabs.com/docs/stable/configure-zone.html#variables) is changed and the scope of those changes. The variables include:

- range_min_bytes

- range_max_byte

- gc.ttlseconds

- num_replicas

- lease_preferences

The scope of the zone config changes could include (I may be missing some):

- cluster

- database

- table

- index

- row

As an example, in the Features table, this could look like: 
--
node
timestamp
uptime
version
internal
feature: configurezone.table.num_replicas
uses

However, this type of record may not work well with Looker. 

@piyush-singh , any thoughts on how to best do this?

**Comment by piyush-singh** [comment]
Snowflake allows direct querying of properly formatted JSON columns, so if we need to we could just store the updated configs in a JSON column. Happy to work with Oliver to sort out the best arrangement.

**Comment by otan** [comment]
I don't have access to looker so it's hard to picture what you want (feedback about telemetry requests in general for me) even if you give me the looker description :)

So we don't care about the actual value, just to know that it's been changed?

**Comment by johnrk** [comment]
If we're permitted to report values, that would be helpful to have. Otherwise, each instance that the feature has been used for a given cluster id is what we're looking for. For example, using this stat in conjunction with another table, I could see us making a report that shows a trend of x% of clusters have lowered their GC TTL.

**Comment by otan** [comment]
> If we're permitted to report values, that would be helpful to have
ah, i'm not sure whether that's allowed - are there guidelines?

**Comment by piyush-singh** [comment]
The expert here is DT. The easiest place to ask for guidelines or best practice is the #telemetry slack channel. Not sure if we have documented what we are okay to collect yet (or what we should always omit for that matter).
