### ISSUE TITLE
storage/cloud: add CLI flag to disable http file access

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#44320]
Operators wish to disable making outbound HTTP requests to arbitrary URIs from IMPORT, BACKUP, RESTORE, etc, either via the HTTP storage scheme or the custom endpoint overrides to the other cloud storage implementations.

There should be a CLI flag (not a cluster setting, since it is access to the local node / env that is relevant) that disables the http ExternalStorage (and the customer endpoints for the other ones). Initially this should default to leaving these enabled to match current behavior, though a future version may choose to change that.

**Comment by miretskiy** [comment]
I think the default should be to disable all access.
The command line flag ought to enable some, or all.  WDYT?

**Comment by dt** [comment]
We can backport the addition of the flag if the default initially matches
the current behavior, and then we can determine if we want to change that
default (which would be a breaking change!) in a later commit.
