### ISSUE TITLE
sql: better support and testing for FmtExport

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#44322]
tree.FmtExport and ParseDatumStringAs are a pair of functions that are designed to round trip our datums as strings. They are tested at https://github.com/cockroachdb/cockroach/blob/c16ce06ba3388b1928db3ad86fc4e44110004383/pkg/sql/sem/tree/parse_string_test.go#L26.

We need to improve support for them.

1. FmtExport doesn't support arrays or tuples. It needs to be taught about them. ParseDatumStringAs must also be taught how to parse that format. Make sure recursive tuples and other weird things work.
2. We should improve the testing to use the randInterestingDatums (https://github.com/cockroachdb/cockroach/blob/c16ce06ba3388b1928db3ad86fc4e44110004383/pkg/sql/sqlbase/testutils.go#L364) which will verify that our edge case datums don't cause bugs.
3. randInterestingDatums should be taught about all of our datums (it currently doesn't have UUIDs, arrays, and some other stuff).
4. The randInterestingDatum func (https://github.com/cockroachdb/cockroach/blob/c16ce06ba3388b1928db3ad86fc4e44110004383/pkg/sql/sqlbase/testutils.go#L527) should panic when a datum is requested that it can't generate. This will guarantee that anytime we add new types, we must also add their edge cases to this list.
5. Maybe add arrays of arrays or tuples of tuples and other really weird stuff to the the rand datum functions (either randInterestingDatum or RandDatumWithNullChance).

Bonus points:

- Make a test function that can generate a table with one column of each type, then insert all data from the randinterestingdatum map into that table.
- Use this table to ensure that we can round trip the following things correctly:
  - cockroach dump / cockroach sql
  - BACKUP / RESTORE
  - EXPORT / IMPORT
  - CDC
  - distsql processor serialization

**Comment by rohany** [comment]
> tree.FmtExport and ParseDatumStringAs are a pair of functions that are designed to round trip our datums as strings.

Is `FmtExport` a function or just a format flag for the `FmtCtx`? I'm only finding the former.

**Comment by mjibson** [comment]
Just a flag.

**Comment by rohany** [comment]
@mjibson, why do we need to support `FmtExport` / parsing of tuples? You wouldn't be able to like store a tuple in a column or anything, so why is that applicable here?

**Comment by rohany** [comment]
I'm looking at this more, and I'm concerned if `FmtExport` is really the correct combination of flags for roundtripping strings -- 

For example, `ARRAY[NULL, "NULL"]` formats to `ARRAY[NULL,NULL]`, which is incorrect. Or, `ARRAY['"hello']` formats to `ARRAY["hello]` which doesn't parse.

Most of the various escaping done in `TestParseArray` does not seem to preserve some of the escaping in the input.

**Comment by rohany** [comment]
TODO (rohany): add a test that tests round tripping of arrays of all scalar types, or update the existing test to do so.

**Comment by rohany** [comment]
This has been completed, with extra testing moved to a new issue.
