### ISSUE TITLE
cli/demo: `cockroach demo --nodes` uses all my memory

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#44333]
`cockroach demo` currently uses the default of 25% of all physical RAM for `--max-sql-memory` in _each_ simulated node. After 3-4 nodes, any moderately large query causes the program to die with an OOM error.

The configuration must be tweaked to divvy up the RAM between the simulated nodes.

**Comment by knz** [comment]
(Arguably `--cache` should be tweaked as well but its default of 128MB will take a larger value of `--nodes` to exhauste memory.)

**Comment by awoods187** [comment]
Nice find @knz. We should clean this up for the next alpha.

**Comment by knz** [comment]
can you sync with a mgr to check whether Otan is the best person to look at this.

**Comment by otan** [comment]
i can take a look at this next week, feels like the cli team might belong in some sort of community service team at some point though haha :P
