### ISSUE TITLE
Cockroach does not shut down gracefully if not properly initialized

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#4435]
Noticed while attempting to use `supervisorctl stop cockroach` (which sends SIGTERM). 
The `cockroach` process does not end upon receiving the signal if it is not yet fully initialized or in the process of waiting for a gossip partition to resolve.

(`SIGKILL` does the trick though)

**Comment by tamird** [comment]
This is fixed by the graceful shutdown commit in
https://github.com/cockroachdb/cockroach/pull/4427.

**Comment by knz** [comment]
Oh thanks. I'll check then close this one when #4427 merges.

**Comment by knz** [comment]
Seems to work now. Thanks!
