### ISSUE TITLE
sql: add data masking or redaction 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#44363]
A few customers have requested data masking or redacted data within the db. @drewdeally to share more information. 

Jira issue: CRDB-5236

**Comment by asubiotto** [comment]
Can we add more information to this issue? Tempted to close if not.

**Comment by drewdeally** [comment]
Here is a general description

https://www.talend.com/resources/data-obfuscation/ <https://www.talend.com/resources/data-obfuscation/>

And the following are good examples

http://dasini.net/blog/2019/03/19/mysql-security-mysql-enterprise-data-masking-and-de-identification/
https://www.enterprisedb.com/blog/native-data-redaction-capability-edb-postgres-advanced-server-11
https://www.slideshare.net/EnterpriseDB/5-ways-to-make-your-postgres-gdprready
