### ISSUE TITLE
roachtest: schema test idempotency broken 

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#44371]
Both TPCC and MOVR attempt to catch error when a FK is created for a 2nd time by looking for
```
columns cannot be used by multiple foreign key constraints
```
20.1 doesn't produce such errors any more since @otan recently lifted that restriction. But for the test's purposes, creating those FKs multiple times would be bad even if it works (I don't know if it does work).
19.2 also uses a different error text since 88d5fd1dd56b92647e5605508da0cc7ada8514de

TPCC:
https://github.com/cockroachdb/cockroach/blob/02328fdd1c0832b78fc569d7145d2ea5af7918c4/pkg/workload/tpcc/tpcc.go#L331

MOVR:
https://github.com/cockroachdb/cockroach/blob/21ab1e411f036fdc68692abc009303994b1b3069/pkg/workload/movr/movr.go#L225

If we want that protection, I guess it needs to be done differently.

@nvanbenschoten @otan @jordanlewis

**Comment by otan** [comment]
>  But for the test's purposes, creating those FKs multiple times would be bad even if it works (I don't know if it does work).

it should work and i do have a test for it. should we add version gated checks for each?

**Comment by andreimatei** [comment]
I think we can just query somehow to see if the FKs exist before attempting to create them. I imagine the query would work across versions.

**Comment by nvanbenschoten** [comment]
> I think we can just query somehow to see if the FKs exist before attempting to create them. I imagine the query would work across versions.

That sounds like the right approach.
