### ISSUE TITLE
kv: "cannot merge final range"

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#44378]
The contract of AdminMerge is currently "AdminMerge merges the range containing key and the subsequent range" but this is hard to reason about in the presence of concurrent splits and merges.

I propose that we change the AdminMerge to contract to be something like "if successful, there was a point in time in between when AdminMerge was called and when it returned that this key was not a range split point". The biggest change here is to any callers that are trying to merge a range by a key in the middle of the range instead of the end point. Are there any such callers?

Context: The kvnemesis test knows places that it has split before, if it later tries to merge one of these split points, it can get "cannot merge final range" errors if this split point was already merged in the meantime. This seems surprising to me.

**Comment by danhhz** [comment]
Thoughts @nvanbenschoten @tbg?

**Comment by tbg** [comment]
You're suggesting making `Merge` a no-op if it isn't hitting a range boundary, right? That seems desirable to me. Make sure to implement this transactionally (i.e. check in the merge txn, not one-off before, as things might change out from under you if you get the info from the local desc).

**Comment by danhhz** [comment]
I thought about this more and the transition is tricky. we're currently handing merge the start key of the lhs, but if we want the contract to be "eliminate this split" then we'd be handing it the start key of the rhs

**Comment by nvanbenschoten** [comment]
Are we handing it the start key or any key in the lhs? If we're handing it any key in the lhs then I think we could make this simpler by turning "cannot merge final range" into a no-op without changing anything else in the API.

**Comment by danhhz** [comment]
I _think_ the contract is you can hand it any key in the lhs. In practice, the merge queue seems to hand it the start key of the lhs.

Anyway I've been thinking that myself. I'm suggesting the contract in OP as an eventual cleanup of the api, but there's certainly a possible immediate usability improvement in making the "cannot merge final range" into a no-op.
