### ISSUE TITLE
issue poster: validation failed

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#44370]
Check out "Validation Failed" at the end.
From https://teamcity.cockroachdb.com/repository/download/Cockroach_Nightlies_RoachtestNightlyAws/1708154:id/tpcc/headroom/n4cpu16/test.log

```
06:27:12 test_runner.go:642: [w2] failed to post issue: failed to create GitHub issue github.IssueRequest{Title:"roachtest: tpcc/headroom/n4cpu16 failed", Body:"[(roachtest).tpcc/headroom/n4cpu16 failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=1708154&tab=buildLog) on [provisional_202001231814_v20.1.0-alpha.20200123@d818f1ff64aaa725a8aea2d45c7df9dd4a42d4d3](https://github.com/cockroachdb/cockroach/commits/d818f1ff64aaa725a8aea2d45c7df9dd4a42d4d3):

```
		  - /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-1708154-1579821061-13-n4cpu16:4 -- ./workload run tpcc --warehouses=1470 --histograms=perf/stats.json  --ramp=5m0s --duration=2h0m0s {pgurl:1-3} returned:
		    stderr:
		    
		    stdout:
		           307.9     17.8     62.9     96.5    109.1 payment
		     6436.0s        0           31.0           30.8     16.3     28.3     33.6     33.6 stockLevel
		    _elapsed___errors__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
		     6437.0s        0           31.0           30.8     52.4    121.6    134.2    134.2 delivery
		     6437.0s        0          298.0          307.3     30.4     88.1    113.2    167.8 newOrder
		     6437.0s        0           34.0           30.8      4.5     11.5     18.9     18.9 orderStatus
		     6437.0s        0          326.0          307.9     19.9     79.7     96.5    192.9 payment
		     6437.0s        0           27.0           30.8     13.6     41.9     44.0     44.0 stockLevel
		     6438.0s        0           26.0           30.8     44.0    125.8    218.1    218.1 delivery
		     6438.0s        0          333.9          307.3     39.8     96.5    159.4    209.7 newOrder
		     6438.0s        0           37.0           30.8      4.1     28.3    109.1    109.1 orderStatus
		     6438.0s        0          310.9          307.9     27.3    113.2    167.8    167.8 payment
		     6438.0s        0           33.0           30.8     15.2     26.2     28.3     28.3 stockLevel
		     6439.0s        0           33.0           30.8     50.3     96.5    121.6    121.6 delivery
		     6439.0s        0          331.0          307.3     37.7     96.5    117.4    125.8 newOrder
		     6439.0s        0           30.0           30.8      4.5     44.0     44.0     44.0 orderStatus
		     6439.0s        0          300.0          307.9     26.2    109.1    125.8    167.8 payment
		     6439.0s        0           33.0           30.8     16.8     27.3     41.9     41.9 stockLevel
		     6440.0s        0           40.0           30.8     62.9    151.0    159.4    159.4 delivery
		     6440.0s        0          343.0          307.3     37.7    125.8    142.6    151.0 newOrder
		     6440.0s        0           38.0           30.8      4.7     11.5     41.9     41.9 orderStatus
		     6440.0s        0          328.0          307.9     29.4    117.4    142.6    201.3 payment
		     6440.0s        0           20.0           30.8     17.8     35.7     48.2     48.2 stockLevel
		    _elapsed___errors__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
		     6441.0s        0           24.0           30.8     52.4    134.2    151.0    151.0 delivery
		     6441.0s        0          318.9          307.4     33.6     92.3    125.8    285.2 newOrder
		     6441.0s        0           37.0           30.8      5.2     23.1     28.3     28.3 orderStatus
		     6441.0s        0          307.9          307.9     22.0     75.5    100.7    121.6 payment
		     6441.0s        0           39.0           30.8     15.2     32.5     35.7     35.7 stockLevel
		     6442.0s        0           32.0           30.8     44.0     96.5    134.2    134.2 delivery
		     6442.0s        0          312.0          307.4     28.3     83.9    142.6    151.0 newOrder
		     6442.0s        0           31.0           30.8      4.2      7.3     46.1     46.1 orderStatus
		     6442.0s        0          343.0          307.9     19.9     88.1    113.2    113.2 payment
		     6442.0s        0           27.0           30.8     16.8     60.8     62.9     62.9 stockLevel
		     6443.0s        0           31.0           30.8     56.6    100.7    125.8    125.8 delivery
		     6443.0s        0          332.1          307.4     33.6     79.7     92.3    109.1 newOrder
		     6443.0s        0           29.0           30.8      4.5     14.7     31.5     31.5 orderStatus
		     6443.0s        0          320.1          307.9     18.9     58.7     75.5     83.9 payment
		     6443.0s        0           25.0           30.8     15.7     29.4     44.0     44.0 stockLevel
		     6444.0s        0           28.0           30.8     35.7     54.5     71.3     71.3 delivery
		     6444.0s        0          266.0          307.3     18.9     71.3     96.5    100.7 newOrder
		     6444.0s        0           31.0           30.8      3.8      9.4     17.8     17.8 orderStatus
		     6444.0s        0          248.0          307.9     11.0     50.3     79.7     92.3 payment
		     6444.0s        0           29.0           30.8     13.6     22.0     22.0     22.0 stockLevel
		    Error:  exit status 255:
		  - exit status 1

```

<details><summary>More</summary><p>


Artifacts: [/tpcc/headroom/n4cpu16](https://teamcity.cockroachdb.com/viewLog.html?buildId=1708154&tab=artifacts#/tpcc/headroom/n4cpu16)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Atpcc%2Fheadroom%2Fn4cpu16.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>
", Labels:["O-robot" "C-test-failure" "C-test-failure" "branch-provisional_202001231814_v20.1.0-alpha.20200123" "O-roachtest" "release-blocker"], Assignee:"", Milestone:21}: POST https://api.github.com/repos/cockroachdb/cockroach/issues: 422 Validation Failed [{Resource:Label Field:name Code:invalid Message:}]
```

**Comment by tbg** [comment]
"branch-provisional_202001231814_v20.1.0-alpha.20200123" is >= 50 characters. Well, it looks like we should be massaging these labels anyway... @dt, that branch should get posted to `release-20.1`, right? Which is mostly master but not quite because we often end up having to branch off of master via a few critical cherry-picks. Want to make sure I'm getting it right before I get in the dirty business of figuring out equivalencies between branches :-/

**Comment by tbg** [comment]
food for thought: should `branch-master` generally be `branch-release-20.1`? After all, once a release is out, the previous master issues will really be `release-20.1` but it's not like anyone's going to know to relabel them.
