### ISSUE TITLE
kv: "merge failed: unexpected value" from AdminMerge

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#44377]
Found by kvnemesis.

AdminMerge will sometimes return an error like the following in the presence of concurrent splits and merges.

```
storage/replica_command.go:786: merge failed: unexpected value: raw_bytes:"\027\342B5\003\010\034\022\001\250\032\014\272\02239ee4347\000\001\"\006\010\001\020\001\030\001(\0020\002@\001" timestamp:<wall_time:1579900467358819000 >
```

I suspect it's coming from the CPut in conditionalGetDescValueFromDB, which doesn't seem to be caught by the retry condition: https://github.com/cockroachdb/cockroach/blob/a8f1ea237f51dc515d19ad1266c4c4d75dce50b5/pkg/storage/replica_command.go#L784

Repros easily in TestKVNemesisSingleNode when merges are turned on and "cannot merge final range" errors are ignored. Pushing a PR soon and I'll update this with a link when I do.

**Comment by danhhz** [comment]
Repro #44379. Apply the following diff and stress

```diff
diff --git a/pkg/kv/kvnemesis/validator.go b/pkg/kv/kvnemesis/validator.go
index 0f634743f2..5b914648d5 100644
--- a/pkg/kv/kvnemesis/validator.go
+++ b/pkg/kv/kvnemesis/validator.go
@@ -140,8 +140,6 @@ func (v *validator) processOp(txnID *string, op Operation) {
 			// there is no split at that key. #44378
 			//
 			// In the meantime, no-op.
-		} else if resultIsConditionFailedError(t.Result) {
-			// Pretty sure a retry loop somewhere isn't working right. No-op. #44377
 		} else {
 			v.failIfError(op, t.Result)
 		}
```

```
make stress PKG=./pkg/kv/kvnemesis TESTS=TestKVNemesisSingleNode TESTTIMEOUT=45s TESTFLAGS='-v -show-logs' STRESSFLAGS='-stderr -maxfails 1'
```

**Comment by nvanbenschoten** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/60847.
