### ISSUE TITLE
sql: add total planning and execution time to explain analyze

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#44408]
In CRDB, Explain Analyze is output as a link. This link doesn't include easy to understand total planning and total execution time. 

For example in CRDB this [link is produced.](https://cockroachdb.github.io/distsqlplan/decode.html#eJykkt9u0zAUxu95Cutcrchbk6wqm6-oRpEqlWQ0RfxTFGXOWbBI7WAfo05VH4sX4MlQkiGtKwtCXPqzP5_vd87ZgftWg4D5h-vlbBGzWTxbfvw0ZyevFuk6fbscsXS-nF-tmTRe08nzEXu9St4wq0p0wEGbEuNigw7EZwiBQwQZh8Yaic4Z28q77tGi3IIIOCjdeGrljIM0FkHsgBTVCAJic2qacQQcSqRC1d2nNwXJL-iY8dR4EqwtQr6pH0kOa5Skviu6Eyw4CwLggFuUnpTRjNQGBQt__nCQ7Tn0xvsUjooKQZzv-YOk4XDSdXFT4wqLEu04OMzbdSYvPJlc6RK3-e3XXCq6yy3e5t6hdS9_Ny9tCu0EOwUOScsRG43Aj4gn02PkyfRFMD3GvryEDqiu75GjyVlwEW6exg7_BXtWVRargowdh4fUV8m7eJ2vkvfpyegPCP8xtIuhoUUH6f-yXit0jdEOD5I_9XOwzzhgWWG_ws54K_HaGtmV6Y9J5-uEEh31t-f9YaH7qzbgQ3M4aI6GzdGgOXhkzvbPfgUAAP__YrZFhA==)

In Postgres it looks like this:
![image](https://user-images.githubusercontent.com/22278911/73205523-24723200-410f-11ea-83d1-cf2cb50d8d3f.png)

It's much easier to understand overall planning and exec time based on this output. Relates to https://github.com/cockroachdb/cockroach/issues/41459

**Comment by jordanlewis** [comment]
This is done now.

```
demo@127.0.0.1:26257/defaultdb> explain analyze select 1;
               info
-----------------------------------
  planning time: 102µs
  execution time: 309µs
  distribution: local
  vectorized: true
  maximum memory usage: 10 KiB
  network usage: 0 B (0 messages)
  regions: us-east1

  • values
    nodes: n1
    regions: us-east1
    actual row count: 1
    size: 1 column, 1 row
(13 rows)
```
