### ISSUE TITLE
clock synchronization to sensitive

### ISSUE THREAD

**Issue by Dmole** [cockroachdb/cockroach#44405]
**Describe the problem**
Clock synchronization should wait a minute and try again before error-ing out.
As a workaround I have added a 1 minute delay between installing chrony and starting cockroach

**To Reproduce**
1. start 3 VirtualBox VMs with fresh Ubuntu server + ssh.
2. apt install chrony #(ntp is fail)
3. ./cockroach start --insecure --advertise-addr=${IP} --join=${IP1},${IP2},${IP3} --background # on 3
4. ./cockroach init --insecure --host=${IP} # on one
5. 2/3 nodes fail with the below error

**Expected behavior**
CockroachDB should be hard to kill like a nest of cockroachs.

**Additional data / screenshots**

* ERROR: [n3] Reported as error 1c2099869a58405396737056777331e9
*
F200127 17:11:14.219768 189 server/server.go:268  [n3] clock synchronization error: this node is more than 500ms away from at least half of the known nodes (1 of 2 are within the offset)
goroutine 189 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc000412300, 0xc000412300, 0x0, 0xc00686a050)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1017 +0xb1
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x7514940, 0xc000000004, 0x6ccc26c, 0x10, 0x10c, 0xc000bf97a0, 0x88)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:871 +0x95b
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x4a5e5c0, 0xc000cc8de0, 0xc000000004, 0x2, 0x0, 0x0, 0xc007d67be8, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:66 +0x2cc
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x4a5e5c0, 0xc000cc8de0, 0x1, 0x4, 0x0, 0x0, 0xc007d67be8, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:69 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatal(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:189
github.com/cockroachdb/cockroach/pkg/server.NewServer.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:268 +0xc7
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).runHeartbeat.func2(0x4a5e500, 0xc000882380, 0xc0006cc510, 0x40ed98d)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:1130 +0x528
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr(0xc0006cc510, 0x4a5e500, 0xc000882380, 0x40ed98d, 0xd, 0xc007d67df0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:300 +0xeb
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).runHeartbeat(0xc000478ea0, 0xc003581140, 0xc0003aca20, 0x13, 0xc003517020, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:1058 +0x396
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).grpcDialNodeInternal.func1.1.1(0x4a5e5c0, 0xc003590660)
	/go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:994 +0x79
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc00041ea00, 0xc0006cc510, 0xc0032a54f0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xfb
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xa8

**Environment:**
 - cockroach-v19.2.2.linux-amd64
 - Server OS: Ubuntu 18.04.3 LTS
 - no Client apps

**Additional context**

Current state;
for IP in $IP1 $IP2 $IP3 ; do echo -ne "$IP\t"; A="$(ssh $IP date +%s.%N)";B="$(date +%s.%N)";echo "$B-$A" | bc; done
192.168.0.149	.006064556
192.168.0.125	.006518327
192.168.0.147	.006429213

before installing chrony the VMs can be 7.0 seconds off.

**Comment by Dmole** [comment]
Also if I suspend the host, the VMs get way out of sync

```
> for IP in $IP1 $IP2 $IP3 ; do echo -ne "$IP\t"; A="$(ssh $IP date +%s.%N)";B="$(date +%s.%N)";echo "$B-$A" | bc; done
192.168.0.149	34.880408239
192.168.0.125	45.822031774
192.168.0.147	45.799141649

> for IP in $IP1 $IP2 $IP3 ; do ssh "$IP" systemctl restart chrony; done

> for IP in $IP1 $IP2 $IP3 ; do echo -ne "$IP\t"; A="$(ssh $IP date +%s.%N)";B="$(date +%s.%N)";echo "$B-$A" | bc; done
192.168.0.149	.008045584
192.168.0.125	.006996310
192.168.0.147	.007748191
```

Sure that's sort of an OS/VM bug that the time gets messed up like that but is would be nice if cockroachdb could ask the OS to update the time, and check again in a minute instead of erroring out immediately.

**Comment by andreimatei** [comment]
Generally, the reason why we crash is because by the time we detect the clock skew, we might have already misbehaved (generally this means we might have served stale data to reads, although I think more arbitrary bad things are theoretically possible too). So, again generally speaking, being less sensitive to violations of the `--max-offset` is not a good idea.

It sounds like you care about the particular case of a node's clock being out of sync at the time of node start - basically waiting a bit in the hope that the clock sync service is also about to start up and fix things. This sounds reasonable to me in principle, although I won't promise we'll do something about it very soon.
