### ISSUE TITLE
sql: add explain to feature counter telemetry

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#44400]
We should add explain (and its permutations) to the feature counter telemetry so that we can better understand its usage and gauge customer satisfaction with query performance

**Comment by Dmole** [comment]
Also idle performance; what background jobs are eating ~6% CPU with 0 connections.

**Comment by RaduBerinde** [comment]
@Dmole please file a separate issue.

**Comment by RaduBerinde** [comment]
Last time I looked all explain variants had counters.
