### ISSUE TITLE
pq: variable sub-expressions are not allowed in CHECK

### ISSUE THREAD

**Issue by glennfawcett** [cockroachdb/cockroach#44412]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Support for...
```
ALTER TABLE mytable ADD CONSTRAINT class_fk CHECK ( EXISTS (SELECT 1 FROM doctype WHERE doctype.doc_type = mytable.doc_type ));
```

**Describe alternatives you've considered**
Code Constraint in Application

**Comment by jordanlewis** [comment]
Is this supported in Postgres?
