### ISSUE TITLE
ui: interpolating graph trendlines despite having no data

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#44415]
I was looking at these graphs earlier and was somewhat surprised by it. Note the long slopes between 00:54:30 to 1:00:30. That period of time corresponded to n3 (red) crashing where we were no longer able to collect metrics from it. Despite that, we're interpolating trendlines from recorded metrics pre-crash to our next set of recorded metrics (after restarting n3). Naively I'd expect the graphs to show gaps to indicate we have no available data for said time period, but that is not the case. Is this the behavior we want? I'm also curious how other metrics pages display the lack of available data.

![image](https://user-images.githubusercontent.com/10536690/73215632-6e184800-4122-11ea-9cb2-4ecfdcac1651.png)

Jira issue: CRDB-5227

**Comment by piyush-singh** [comment]
Andrii notes that it is not trivial to know where there are gaps in the data. We'll need API side changes to mark missing data. This might be something we pick up in the stability period, to get this in for 20.2.

David and Andrii note that other charting tools have nulls or empty values to indicate missing data. We'll likely need something similar on the server side that does something similar to fix this.
