### ISSUE TITLE
ui: timepicker UX issues

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#44422]
Looking at the timepicker modal, I’m somewhat surprised by the play button being used to represent “now” (and the media next/prev buttons used to cross time frames):

![image](https://user-images.githubusercontent.com/10536690/73217324-bd13ac80-4125-11ea-8117-7ced0839209a.png)

For another data point, google calendar uses the following:

![image](https://user-images.githubusercontent.com/10536690/73217434-e7fe0080-4125-11ea-8102-22b6edd33861.png)

Also, unrelated, the downward arrow for time frame selection points up when the selection modal is collapsed, and points down when it already has been expanded below.

<img width="486" alt="image" src="https://user-images.githubusercontent.com/10536690/73217507-0cf27380-4126-11ea-9a7c-62ddd3aefe8a.png">

<img width="485" alt="image" src="https://user-images.githubusercontent.com/10536690/73217478-02d07500-4126-11ea-909d-712fb6b4d097.png"> 

For another data point, here is how firefox does it (not visible by default, down arrow visible on hover over address box, visible with gray background on hover over arrow, persisted gray background on click while collapsible menu left open):

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10536690/73217872-c81b0c80-4126-11ea-978e-2c49441a8379.gif)

**Comment by irfansharif** [comment]
+cc @Annebirzin, @piyush-singh.

**Comment by Annebirzin** [comment]
@elkmaster updated date picker designs are here: zpl.io/VQ7dA5k 

Also, attached are the `caret-left.svg` and `caret-right.svg` if needed 

[icons.zip](https://github.com/cockroachdb/cockroach/files/4135309/icons.zip)
