### ISSUE TITLE
exportccl: exporting NULLs without a chosen token fails silently

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#44425]
Currently when exporting a table that contains `NULL`s we expect the user to provide a `nullas` flag indicating a token that should be used to represent `NULL` in the CSV (since there is no CSV representation of null). Note that the `nullas` option is optional in general since the schema may not have any `NULL`s and therefore not need a token specified.

However, if data that contains a `NULL` is exported without this option, `NULL`s are represented by empty strings and cannot be imported again. We should consider emitting a warning if we encounter a `NULL` during an export that does not have the `nullas` field specified.

**Comment by dt** [comment]
we could also just default to `NULL` -- yes, if the column is a string and contains the string "NULL" this will collide, but hey, that's why we give you the `nullas` option.
