### ISSUE TITLE
nulls don't work in export/import CSV

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#44420]
It appears that NULLs in tables that are exported to CSV's are not exported / cause an error on import.

```
> CREATE TABLE t (x INT);
INSERT INTO t VALUES (NULL);
export into csv 'nodelocal:///foo.csv' from table t;
import table test(x int) csv data ('nodelocal:///foo.csv/n1.0.csv');
select * from test;

  x
-----
(0 rows)
```
Also, 
```
> CREATE TABLE t (x INT, y INT);
INSERT INTO t VALUES (NULL, 1), (2, 3);
export into csv 'nodelocal:///foo.csv' from table t;
import table test(x int, y int) csv data ('nodelocal:///foo.csv/n1.0.csv');

ERROR: nodelocal:///foo.csv/n1.0.csv: "nodelocal:///foo.csv/n1.0.csv": row 1: expected 2 fields, got 1: []string{"1"}
SQLSTATE: 42601
```

**Comment by mwang1026** [comment]
Is this still an issue? Based on some offline conversations it seemed like we couldn't reproduce?

**Comment by rohany** [comment]
I think we might be tracking it elsewhere? The consensus though was that this isnt a bug, you need to specify the null behavior when you export/import. However, the defaults should work or throw a warning if you encounter a null and don't have the null behavior specified.

**Comment by rohany** [comment]
Yes, this is tracked in #44425.
