### ISSUE TITLE
kv: must handle idempotence for BeginTransaction

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4443]
If the first write in a txn is multi-range and fails retriably on the second range, the command will fail with an error on the first range on `BeginTransaction` (since the previous attempt was actually successful there, so we already wrote an entry).

Happens in the wild:

> pq: txn "sql/lease.go:xx LeaseStore.Acquire" id=NN key=/Table/NNN/NNN/NNN/NNN/Thu Feb NNN NNN:3NNN:5NNN UTC NNN/NNN/NNN rw=false pri=NNN.NNN iso=SERIALIZABLE stat=PENDING epo=NNN ts=NNN.NNN,NNN orig=NNN.NNN,NNN max=NNN.NNN,NNN: non-aborted transaction exists already

**Comment by vivekmenezes** [comment]
I just saw this error when I reran the new acceptance test TestNodeRestart in https://github.com/cockroachdb/cockroach/pull/4392 .

**Comment by tschottdorf** [comment]
@spencerkimball - this looks closely related to #5257 (changing `> Epoch` to `>= Epoch`). Mind taking this on?

**Comment by spencerkimball** [comment]
Fixed by #5360
