### ISSUE TITLE
Implement `DROP VIEW` as `JOB`

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#44454]
**Is your feature request related to a problem? Please describe.**
A user would like to be able to execute `DROP VIEW` in CLI and be able to monitor the result with `SHOW JOBS` or in the admin UI.

**Describe the solution you'd like**
A similar behavior to `DROP TABLE` would be preferred. Ideally, I'd like to see that functionality to be auditable too, output to a sink ala `CHANGEFEED`. Choice of sink should be left for customer.

**Describe alternatives you've considered**

**Additional context**

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4556](https://cockroachdb.zendesk.com/agent/tickets/4556) has been linked to this issue.

**Comment by dbist** [comment]
CC @awoods187

**Comment by jordanlewis** [comment]
This is done in 20.1.

![image](https://user-images.githubusercontent.com/43821/77988425-5314b080-72ea-11ea-986e-c27f5113e3a4.png)
