### ISSUE TITLE
`to_json()` results don't match Postgres

### ISSUE THREAD

**Issue by giorgosp** [cockroachdb/cockroach#44465]
For example the following query:
```sql
SELECT to_json(x.*) FROM (VALUES (1,2)) AS x(column2);
```
currently returns a "duplicate column" error. 

After #41557  is merged, CockroachDB will return
```
   to_json
------------------
  {"column2": 2}
```

but Postgres returns
```
   to_json
------------------
{"column2":1,"column2":2}
```

So, duplicate column names in the input of `to_json` need to be included as duplicate keys in the resulting JSON object.

The correct test cases have been added as a TODO comment in #41557 https://github.com/cockroachdb/cockroach/pull/41557/files#diff-e9dd4e05509f6f7fc35050a751db0ea0R327.

I am willing to tackle this issue but feel free to re-assign if needed.

**Comment by awoods187** [comment]
Thanks for filing and tackling this issue--let us know if you run into any problems.

**Comment by giorgosp** [comment]
Hi, I was looking into this and noticed that cockroachdb handles json and jsonb the same.

Copying json vs jsonb differences from [postgres 12 docs](https://www.postgresql.org/docs/12/datatype-json.html):

> Because the json type stores an exact copy of the input text, it will preserve semantically-insignificant white space between tokens, as well as the order of keys within JSON objects. Also, if a JSON object within the value contains the same key more than once, all the key/value pairs are kept. (The processing functions consider the last value as the operative one.) By contrast, jsonb does not preserve white space, does not preserve the order of object keys, and does not keep duplicate object keys. If duplicate keys are specified in the input, only the last value is kept.

Cockroachdb performs these jsonb normalizations for json too. That is why the `to_json()` and `json_object()` results differ from postgres (but are the same as `to_jsonb()` or `jsonb_object` results).

If this deviation happened on purpose, we could maybe add a comment or two in the code and close the task. Otherwise I can keep working on it.

**Comment by jordanlewis** [comment]
Ah, sorry @giorgosp for the confusion. We're not at the moment interested in providing Postgres compatibility for the `json` data type (really it's a string type). We expect `json` and `jsonb` to be aliases and work identically. We can close this out - if you're already working on it, we'll take PRs with comments that would have prevented this confusion in the first place for you.

Thanks!

**Comment by giorgosp** [comment]
Thank you @jordanlewis , added a PR #45831 with a comment and a  cleanup of the related TODO.
