### ISSUE TITLE
storage: Raft keys need to be moved out of the system-local kv-pairs for stats computations

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#4447]
Raft logs and the Raft HardState are not consistent across replicas, so we can't include these kv-pairs in the `SysBytes` and `SysCount` `MVCCStats` struct. Including these keys in statistics computations results in these structs being inconsistent between replicas, because they are not the same on each replica, and incorrect on all replicas most of the time anyway, because the stats aren't currently updated when the raft kv state changes.

**Comment by tschottdorf** [comment]
are those the only two?

**Comment by nvanbenschoten** [comment]
I think it might make sense to exclude all of the Raft keys from the system statistics. `TestPrettyPrint` makes it pretty easy to visualize all of this.

**Comment by vivekmenezes** [comment]
We should use the same exclusion filter to apply to the raft consistency checker that I'm working on. There is code to be shared here?

**Comment by tschottdorf** [comment]
We should be a little systematic about this and rearrange the system-local keyspace into things which go through Raft (so their stats can be worked with to save work during splits/merges and should be equal between replicas), and the "danger zone" which is data which is not replicated (at least not consistently, for example the Raft log).

@vivekmenezes Agreed that just looking at all replica's stats is already a pretty good poor man's consistency checker. You could just return that on top of your SHA.

**Comment by nvanbenschoten** [comment]
@tschottdorf Were you thinking adding two subsections to the current `LocalRangeIDPrefix`, one for consistently replicated data and one for not, or were you thinking splitting the `LocalRangeIDPrefix` itself into two sections. The benefit of the subsections approach is that we can still index all system-local keys when needed (like in `mergeTrigger` to delete metadata of the subsumed range), but can also be more specific when needed. The downside is that the subsections approach requires to the prefix to grow in length.

**Comment by bdarnell** [comment]
The raft log can take up a significant amount of space so it would be good to be able to account for that somewhere. Maybe we should have separate stats for the things that aren't replicated in the normal way? I think that the hard state and raft log (and really only the uncommitted tail of the raft log) are expected to vary across replicas, but everything in `LocalRangeIDPrefix` is a little bit weird.

I'd be fine with excluding all raft keys from the mvcc stats (as long as there was an alternate place to track them), but we do want most of the raft keys to be covered by the consistency checker. But I think it makes the most sense to use the same exclusion rules for the consistency checker and the stats, which means that we only want to exclude what we absolutely have to. 

We need some way to distinguish log/hardstate records from others, but that doesn't mean that there needs to be a prefix for them. The exclusion rule could just be a function of the key which could e.g. look at a suffix instead.

**Comment by tschottdorf** [comment]
I'm not against tracking the Raft log size, etc in some way but it's fundamentally different from what we should be tracking in MVCCStats: consistently raft-replicated data. If we throw anything inconsistent in there, we won't be able to do consistent arithmetic which costs performance.
