### ISSUE TITLE
sql: support storing role-level options and privileges

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/cockroach#44486]
Currently, all of our role and user privileges apply at the database or table level, so we store them directly on the relevant descriptors. However, a few of the 20.1 permissions enhancements add privileges which only make sense at the role/user level. A few examples of this are [CREATEROLE](https://github.com/cockroachdb/cockroach/issues/41858), [NOLOGIN and VALID UNTIL](41396). PostgreSQL has [other options](https://www.postgresql.org/docs/12/sql-createrole.html) we may want to support later.

To support storing such privileges, we are considering two approaches:

1. Add a new column to the `system.users` table for each new option. The new `users` schema would look like this:
```
CREATE TABLE system.users (
    username STRING PRIMARY KEY,
    hashedPassword BYTES NULL,
    isRole BOOL NOT NULL DEFAULT false,
    createrole BOOL NOT NULL DEFAULT false,
    login BOOL NOT NULL,
    validuntil TIMESTAMPTZ NULL
)
```
The main downside we can see to this approach is that every time we add a new option in the future, we will need to write a migration to add the new column.

2. Create a separate table to hold role-/user-level privileges, one per row.
```
CREATE TABLE system.role_options (
    role STRING NOT NULL,
    option STRING NOT NULL,
    value STRING,
    PRIMARY KEY (role, option)
)
```
where `role` is the name of the role or user, `option` is an option name like `CREATEROLE`, and `value` is an optional value, for options like `VALID UNTIL`. This approach is less compact than option 1 but avoids needing a migration for every new option.

A third option would be to try and store all options in a single field on `users` as an array or serialized protobuf, but it seems like this would add complexity and decrease visibility without much benefit.

**Comment by otan** [comment]
talking with @RichardJCai a bit and it was mentioned that the second option has a "value" field which sometimes may need to be an int, or a string, or a timestamptz. 

how do we feel about storing a protobuf instead, like so:
```
CREATE TABLE system.role_options (
    role STRING NOT NULL,
    option STRING NOT NULL,
    value BYTES,
    PRIMARY KEY (role, option)
)
```

if that's annoying from a readability perspective, you could store the protobuf as a json ;)

**Comment by RichardJCai** [comment]
Decided to go with option 2 mainly due to being able to avoid migrations. (Adding columns to system.users)

```
CREATE TABLE system.role_options (
    role STRING NOT NULL,
    option STRING NOT NULL,
    value STRING,
    PRIMARY KEY (role, option)
)
```
