### ISSUE TITLE
sql: add column_comment to information_schema.columns

### ISSUE THREAD

**Issue by davidsbond** [cockroachdb/cockroach#44484]
**Is your feature request related to a problem? Please describe.**
When querying columns from `information_schema.columns` the comment applied to a column does not show. If I want to be able to perform queries against column comments I have to use `SHOW COLUMNS FROM <table> WITH COMMENT;` which does not support sub-querying. For example, `SELECT comment FROM (SHOW COLUMNS FROM <table> WITH COMMENT)` results in an error

**Describe the solution you'd like**
When I run `SELECT * FROM information_schema.columns WHERE table_name = $1`, I can see a `column_comment` field.

**Additional context**
An example where we might use this is for GDPR compliance. An idea I had was to label columns as personally identifiable information. When I receive a "right of erasure" GDPR request, I can generically obfuscate fields labelled as PII based on a primary key without having to just hard delete rows and break relationships.

This can be useful as in large instances with many databases PII can be distributed across many tables

**Comment by jordanlewis** [comment]
Thanks, I think this is something we're missing.

**Comment by VenkatDatta** [comment]
Hi @rafiss , @jordanlewis 
I'm new to the community and would like to pick this up. 
Please let me know if I can work on this.

**Comment by rafiss** [comment]
@VenkatDatta welcome to the community! Yes, we'd be happy to have your contribution.

To start, take a look at [pg_catalog.pg_description](https://github.com/cockroachdb/cockroach/blob/4e6e7450afa88c877ad28ffe18e96e5c685f1065/pkg/sql/pg_catalog.go#L1221) to see how to access a column comment. And see if you can use similar logic in information_schema.go: https://github.com/cockroachdb/cockroach/blob/4e6e7450afa88c877ad28ffe18e96e5c685f1065/pkg/sql/information_schema.go#L373

I notice that PostgreSQL's information_schema does not have the `column_comment` column, but MySQL does. 

https://www.postgresql.org/docs/12/infoschema-columns.html
https://dev.mysql.com/doc/mysql-infoschema-excerpt/8.0/en/information-schema-columns-table.html

**Comment by mosquito2333** [comment]
Hi all .I have submitted a pr for this issue.
Could you help me review my code?
It's my honor to be guided by you.
Thanks!

**Comment by rafiss** [comment]
Thank you @mosquito2333! We will review it soon and we appreciate your contribution :)
