### ISSUE TITLE
sql: warn users when they do not set an explicit primary key

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#44491]
A customer recently requested that we "configure the cluster to complain if you’ve forgot to explicitly set the primary key. Right now, having our migration scripts succeed and getting the rowid column created automatically has managed to get that primary key into production."

We could either warn by default or allow this to be a cluster setting to warn for this problem.

**Comment by rohany** [comment]
I think a cluster setting to disallow the rowid pk by default makes sense
