### ISSUE TITLE
sql: always show primary key in SHOW CREATE TABLE

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#44490]
Consider the table:

```SQL
CREATE TABLE rides (
                  id UUID NOT NULL,
                  city VARCHAR NOT NULL,
                  vehicle_city VARCHAR NULL,
                 rider_id UUID NULL,
                  vehicle_id UUID NULL,
                  start_address VARCHAR NULL,
                 end_address VARCHAR NULL,
                  start_time TIMESTAMP NULL,
                  end_time TIMESTAMP NULL,
                  revenue DECIMAL(10,2) NULL
              );
```
Even though CockroachDB always creates primary keys, when you run SHOW CREATE TABLE, you cannot see the primary key:
```SQL
 show create table rides;
  table_name |                                                           create_statement
-------------+----------------------------------------------------------------------------------------------------------------------------------------
  rides      | CREATE TABLE rides (
             |     id UUID NOT NULL,
             |     city VARCHAR NOT NULL,
             |     vehicle_city VARCHAR NULL,
             |     rider_id UUID NULL,
             |     vehicle_id UUID NULL,
             |     start_address VARCHAR NULL,
             |     end_address VARCHAR NULL,
             |     start_time TIMESTAMP NULL,
             |     end_time TIMESTAMP NULL,
             |     revenue DECIMAL(10,2) NULL,
             |     FAMILY "primary" (id, city, vehicle_city, rider_id, vehicle_id, start_address, end_address, start_time, end_time, revenue, rowid)
             | )
(1 row)
Time: 367.575ms
```
This can make it confusing when consulting documentation about primary keys or when altering them in the future using `ALTER TABLE rides ALTER PRIMARY KEY USING COLUMNS (city ASC, id ASC)`.

**Comment by solongordon** [comment]
So would this mean adding this line to the output?
```
CONSTRAINT "primary" PRIMARY KEY (rowid ASC),
```
One thing I'd like to preserve if we add this behavior is that the user should be able to copy-paste the `create_statement` to recreate the table.

**Comment by awoods187** [comment]
Yeah I agree we should always be able to copy paste output

**Comment by rohany** [comment]
We have two options here -- either display the hidden rowid column as well, or output the primary key in such cases as a comment. Both cases will allow us to roundtrip the output. Any leanings?

**Comment by awoods187** [comment]
After talking with @jordanlewis, let's go with a comment.  This will keep it copyable and maintain the same exact behavior.

**Comment by solongordon** [comment]
I thought about this a bit more and I'm not convinced it will reduce confusion for users. `rowid` is basically an implementation detail which I'm not sure we need to surface in the typical case. In most cases a user can just think of the table as not having a primary key, the same way that a Postgres table might not have a primary key. Our docs should specify that when running ALTER PRIMARY KEY, users need to specify a set of columns which forms a unique key. This is true whether the table already has a primary key or not.

I guess one question is whether we want to allow users to include `rowid` in their new primary key. For instance, if they are migrating to geo-distributed, they might want to specify `(region, rowid)` as the new key, in which case we would promote `rowid` to a visible column. I think this would be straightforward to document.

**Comment by awoods187** [comment]
I talked this over further with @jordanlewis and am bought into the approach that we don't show `rowid` Instead, users altering their PK will be treated the same as users adding a logical PK for the first time. This is somewhat tricky so we should talk about how to document it @ericharmeling
