### ISSUE TITLE
sql: A 2m long 2s latency spike during online primary key changes with TPCC

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#44501]
Cluster setup for testing online primary key changes during TPC-C.
```SQL
roachprod create $CLUSTER -n 4 --clouds=aws  --aws-machine-type-ssd=c5d.4xlarge
roachprod stage $CLUSTER:1-3 cockroach
roachprod stage $CLUSTER:4 workload
roachprod start $CLUSTER:1-3
roachprod adminurl --open $CLUSTER:1
roachprod run $CLUSTER:1 -- "./cockroach workload fixtures import tpcc --warehouses=2500 --db=tpcc"
roachprod run $CLUSTER:4 "./workload run tpcc --ramp=5m --warehouses=2500 --active-warehouses=2000 --duration=15m --split --scatter {pgurl:1-3}"
```

In another window:
```SQL
set experimental_enable_primary_key_changes =true;
ALTER TABLE customer ALTER COLUMN c_city set not null;
ALTER TABLE customer ALTER PRIMARY KEY USING COLUMNS (c_city, c_w_id ASC, c_d_id ASC, c_id ASC);
```
![image](https://user-images.githubusercontent.com/22278911/73392134-38e93280-42a7-11ea-9360-513200566d1b.png)

version V20.1.0-ALPHA.20191118-1665-GABBE4BC
cluster andy-3node

**Comment by rohany** [comment]
I was able to reproduce a similar latency spike on the same workload by running 3 create index statements in a transaction (the same 3 indexes that the primary key change would write) right near the end of the schema change.

![image](https://user-images.githubusercontent.com/15331872/73682959-60694200-468f-11ea-8d40-e9ba2945cd63.png)

**Comment by awoods187** [comment]
@lucy-zhang this seems pretty high. What do you think?

**Comment by rohany** [comment]
Hmm, now I was very easily able to reproduce this. Attaching a cpu and heap profile.
![image](https://user-images.githubusercontent.com/15331872/76005723-6d20c600-5ed9-11ea-853e-1abc0d54375b.png)
![image](https://user-images.githubusercontent.com/15331872/76007342-e6211d00-5edb-11ea-9259-563c118c8dde.png)

Sorry, not sure how to download them yet. What is this [cockroach] in the profile? Is that the cgo?

**Comment by jordanlewis** [comment]
Yes that's cgo.

**Comment by rohany** [comment]
Closing in favor of https://github.com/cockroachdb/cockroach/issues/45888.
