### ISSUE TITLE
kv: allow for connection or role based setting of follower reads

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#44514]
A customer requested allowing for a connection setting in which all reads for a connection are served as follower reads. We could also explore doing them with a configurable AOST value as well that they pass during the connection string.

Another related idea would be to specify a role in which all reads of that role are follower reads.

This is super useful for reporting tooling that cannot change the queries that it issues. By using follower reads or AOST we could eliminate contention for these class of users.

**Comment by awoods187** [comment]
cc @drewdeally

**Comment by drewdeally** [comment]
another option is to have it as a session level setting instead of setting in transaction or statement.

**Comment by ajwerner** [comment]
> another option is to have it as a session level setting instead of setting in transaction or statement.

URL parameters set session variables. As far as I’m concerned if we do one we do both.

**Comment by andreimatei** [comment]
When we think about this, it's good to keep in mind that avoiding contention and follower reads are not the same thing. A read in the past is good for contention. A read in the past can be a follower read. There's reasons to want follower reads besides avoiding contention, so there's reasons to *require* follower reads. But *requiring* a follower read can also have negative consequences (consider the gateway being in the same locality with the leasehoder and all the followers being remote).

**Comment by ajwerner** [comment]
> consider the gateway being in the same locality with the leasehoder and all the followers being remote

Follower reads is a misnomer. We will choose the nearest node, even if it is the leaseholder.

**Comment by andreimatei** [comment]
Well, unless the client really wants *follower reads*, for example for load isolation concerns. So there's multiple reasonable asks here; I'm saying it'd be good if they were teased apart more.

**Comment by andreimatei** [comment]
Because I'm also thinking that, if what you want is to avoid contention, depending on your workload you might be able to make do with way less staleness than the current follower read duration target, if you want to.

**Comment by ajwerner** [comment]
> Well, unless the client really wants _follower reads_, for example for load isolation concerns. So there's multiple reasonable asks here; I'm saying it'd be good if they were teased apart more.

A follower of one range is the leaseholder of another. s/follower reads/balanced, local reads/ henceforth. 

But yeah I agree that understanding whether it’s the low latency or jist the contention avoidance that’s a goal is a good idea. Either way my expected implementation would be to take an expression which would effectively be used in the as of clause of a `SET TRANSACTION AS OF SYSTEM TIME` for every transaction (including implicit). That would additionally allow a user to set `'-1s'`

**Comment by andreimatei** [comment]
> A follower of one range is the leaseholder of another. s/follower reads/balanced, local reads/ henceforth.

Not if I control my data placement and leases enough :)

**Comment by nvanbenschoten** [comment]
Addressing this by adding a new session variable (which can be configured in the connection string) seems straightforward enough.

There seem to be two options here. We can either allow users to specify an arbitrary default AS OF SYSTEM TIME clause expression directly as a string, or we simply allow users to specify that the default AS OF SYSTEM TIME expression should be `follower_read_timestamp()`. I'm leaning towards the latter option for simplicity.

So here's a strawman. We add a new session variable called `default_transaction_use_follower_read_timestamp`, which is a simple boolean. This mirrors some of the other session variables that configure default values for session settings, like `default_transaction_isolation` and `default_transaction_priority`.

While doing this, we might as well also support `SET SESSION CHARACTERISTICS AS TRANSACTION AS OF SYSTEM TIME follower_read_timestamp()`. We actually accept this today, but it doesn't do anything.
