### ISSUE TITLE
ui: RFC collecting user information - firstname/lastname vs fullname vs company name

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#4451]
@jess-edwards @bdarnell @knz 

Discussion spurred by https://github.com/cockroachdb/cockroach/pull/4397

The email signup is something that's going to be used heavily by @jess-edwards so the requirements have been largely driven by her. We wanted a first name so we can write more casual emails, (eg "Hey Max!" vs "Hey Maxwell G Lang!") and we wanted last name because it is an easier way to sort through/dedupe/organize contacts across lists/sources.

@knz points out that "fullname" while not perfect, captures a wider variety of name situations (especially internationally) and is easier to fill in.

@bdarnell points out, for teams, company would make sense over an individual's name.

**Proposal**

For the beta I propose collecting first and last name, but not requiring them. We want to connect with individuals to get feedback, and find individual champions in companies, so it makes sense to collect slightly more personal information at this stage.

Once we're more mature, I think we can switch to something simpler.

**Comment by jess-edwards** [comment]
@maxlang and I discussed this in person, and we've concluded that we need to test the assumption that requiring name and/or company will deter people from sharing their usage stats. 

### Revised Proposal: 
For the beta, run a 90-day A/B test. For days 1-30, require first name and last name, but leave company as optional. Days 31-60, make first name & last name optional. [@maxlang I'm adding a third 30-day test] For days 61-90, make all three fields required (first name, last name, company). 

At the end of the test, analyze the opt-in conversion rates.

**Comment by petermattis** [comment]
What happens if the number or nature of users over those 3 time periods differs drastically? A better A/B test would be to put the various options in the code and selection amongst the experiments based on the cluster UUID (e.g. take last digit mod by 3). 

While I like the idea of testing, I'm not convinced we want to invest the effort to do such testing in this instance. What is the concern about making all of these fields optional for the beta? Or add some messaging that the fields are required but they should feel free to make something up (which is what I do when a required field is asking for information I don't want to give).

**Comment by maxlang** [comment]
@jess-edwards and I talked about it like an A/B test, but I was thinking more as backing off - ie try with the stricter requirement and if we don't like the numbers we're seeing back off to something less strict.

The more I think about it though, the more I want to start out with them not required - we get useful info from everyone including email, and people who are probably more open to being contacted will self-select by filling in their name.

**Comment by jess-edwards** [comment]
@maxlang I'm fine with only requiring email + stats for now. We can reopen this discussion about requiring more information after we see what the early months of opt-in data looks like.

**Comment by tamird** [comment]
@maxlang can you update this?

**Comment by jess-edwards** [comment]
@maxlang 

Of the 5 contacts we've collected so far from the Admin UI reg page, all have given their full name and three have given us company. Not bad for a data set of five.

**Comment by maxlang** [comment]
Every single registration I've seen has included firstname and lastname (except fake ones from @mberhault), so this seems to be a non-issue. We can revisit our registration process in the future if we'd like to start increasing the numbers at some point.

**Comment by spencerkimball** [comment]
Closing this as the current flow is working fine.
