### ISSUE TITLE
libroach: Inconsistent handling of seeks below lower_bound in BaseDeltaIterators

### ISSUE THREAD

**Issue by itsbilal** [cockroachdb/cockroach#44512]
Batch iterators in rocksdb are implemented as base iterators on the underlying engine, plus a delta iterator on the batch itself. If both an upper and lower bound is specified (in a `rocksDBBatch.NewIterator(...)` call), the delta iterator seems unbound, while the base iterator has its bounds set correctly.

Doing a Seek on a key lower than the specified lower bound could have the iterator return keys lower than the lower bound while remaining valid (since the delta iterator encounters those Sets), violating the iterator's contract.

This is inconsistent with how the pebble batch iterator works; it respects bounds and doing such a Seek will return the lowest key higher than the lower bound. It's probably a good idea to close this gap.

The BaseDeltaIterator is re-implemented in libroach (see `libroach/batch.cc`) and seems to only handle upper bounds in the constructor. The fix would therefore have to be in libroach.

Found with the MVCC metamorphic tests.

**Comment by petermattis** [comment]
Nice find! Do you know if this has any correctness impact?

**Comment by itsbilal** [comment]
@petermattis Don't think so - on batch iterators we always seem to `Seek` at the specified lower bound or after it. And since `SeekLT` and `Prev` aren't supported on those iterators, we can't really iterate past the lower bound.

Still worth keeping track of, at least as a point of difference with Pebble.

**Comment by petermattis** [comment]
Yep, agreed this is worth tracking. I just wanted to make sure there wasn't an urgent need for a fix. Sounds like there isn't.

**Comment by petermattis** [comment]
Given that we're moving away from RocksDB, we're unlikely to fix anything here.
