### ISSUE TITLE
Audit and fix 24:00 handling for Time/TimeTZ

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#44530]
Postgres has a unique max time of `24:00:00` for both `TimeTZ` and `Time`.

They can be stored/parsed as 24:00:00:

```

otan=# select '24:00'::time;
   time
----------
 24:00:00
(1 row)

otan=# select '24:00:00'::timetz;
   timetz
-------------
 24:00:00-08
(1 row)
```

But not "added" to '24:00:00':
```
otan=# select '23:59'::time + '1min'::interval;
 ?column?
----------
 00:00:00
(1 row)
```

Our `timeofday` library for parsing time/timetz (`timeofday.New`) or inferring time (`timeofday.FromInt`) always assumes that we should round -- but there are cases (such as `cli/dump.go`) where we should actually NOT round when doing this.

We should audit and fix all the cases where rounding is not desired.

This was caught "by accident" in https://github.com/cockroachdb/cockroach/pull/44459.

**Comment by otan** [comment]
turns out to not be a problem.

**Comment by awoods187** [comment]
Could you expand upon this further @otan ?

**Comment by otan** [comment]
The real problem is #44548
