### ISSUE TITLE
lib/pq handling of 24:00:00 is broken

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#44548]
lib/pq prints 24:00 time as `0001-01-01 00:00:00`, which is indistinguishable from '00:00'. This is because time is represented as a time.Time in lib/pq. 

```

root@127.0.0.1:51083/movr> select '24:00'::timetz;
            time
-----------------------------
  0000-01-01 00:00:00+00:00
(1 row)

Time: 320µs

root@127.0.0.1:51083/movr> select '24:00'::timetz::string;
    text
------------
  24:00:00
(1 row)

root@127.0.0.1:51083/movr> select '00:00'::timetz;
            time
-----------------------------
  0000-01-01 00:00:00+00:00
(1 row)

Time: 263µs
```

This breaks anything requiring a switch on `time.Time` to parse back into `DTimeTZ` (and `DTime`). 

I think as a result, backups for `time`/`timetz` columns are broken if someone encoded 24:00 time in the database, since backups use lib/pq formatting.

Furthermore, this prevents us from using `TestCopyRandom` for `24:00` values for Time/TimeTZ.

**Comment by knz** [comment]
Thanks for spotting this. It's high time we move away from lib/pq.

**Comment by awoods187** [comment]
@otan so what is the action here that can address this problem?

**Comment by knz** [comment]
My preference would be to remove usage of lib/pq through the SQL shell, since we have 5 other open UX issues that have the same exact root cause.

**Comment by knz** [comment]
(Removing lib/pq is still a roadmap item for the CLI project, cc @piyush-singh )

**Comment by otan** [comment]
Double checking - does removing it from the SQL shell removes lib/pq being used to handle backups as well? My hunch says yes since dump is in the cli package.

@awoods187 besides removing lib/pq from cli I don't think there's much we can do besides modifying the lib/pq library which is equally or if not more effort.

**Comment by awoods187** [comment]
thanks for the explanation--makes sense we'd want to address this sooner

**Comment by knz** [comment]
> Double checking - does removing it from the SQL shell removes lib/pq being used to handle backups as well?

Not necessarily. We can choose to combine them or keep them separate.

> My hunch says yes since dump is in the cli package.

The CLI package uses different SQL drivers for different purposes (:crying_cat_face: )

**Comment by otan** [comment]
i've discovered we also print time incorrectly over pgwire.
but making it display 24:00 time makes our cli break (see  #45387 but ignore the lib/pq change), so lib/pq needs to support it first :|
