### ISSUE TITLE
storage: SequenceCache modification should update replica stats

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#4454]
We don't currently update a replica's `MVCCStats` when its `SequenceCache` is modified (either through poisoning or a standard sequence number insertion).

**Comment by tschottdorf** [comment]
hold off on this, I'm also working on the sequence cache.

**Comment by nvanbenschoten** [comment]
I was going to start looking into rearranging the system-reserved prefixes for system-local keys. This will apply to this issue and #4447. This change shouldn't affect the sequence cache yet, but that will be a precursor to getting the system stats working correctly.

**Comment by tschottdorf** [comment]
SGTM, my PR is up. Won't make more changes.
