### ISSUE TITLE
iomad (multi-tenent moodle) support

### ISSUE THREAD

**Issue by jamiechapmanbrn** [cockroachdb/cockroach#44556]
Installation of IOMAD fails after creating tables with an error that it can't find a table that was just created.

Please describe the issue you observed, and any steps we can take to reproduce it:

The installer fails creating databases with the following stack trace:
```
sudo php install_database.php  --agree-license --adminuser=admin --adminpass=admin
-------------------------------------------------------------------------------
== Setting up database ==
-->System
Default exception handler: Table "config" does not exist Debug: 
Error code: ddltablenotexist
* line 665 of /lib/dml/moodle_database.php: dml_exception thrown
* line 1619 of /lib/dml/moodle_database.php: call to moodle_database->where_clause()
* line 1394 of /lib/moodlelib.php: call to moodle_database->get_field()
* line 1483 of /lib/upgradelib.php: call to set_config()
* line 1728 of /lib/upgradelib.php: call to upgrade_started()
* line 484 of /lib/installlib.php: call to install_core()
* line 179 of /admin/cli/install_database.php: call to install_cli_database()
```
![image](https://user-images.githubusercontent.com/14986283/73487058-415b6f00-4374-11ea-9e3d-0f0971306049.png)

If possible, provide steps to reproduce the behavior:

Create moodle database+user and grant permissions.
configure iomad config.php to use pgsql driver and correct port/user/host

**Expected behavior**
iomad installer should work correctly with cockroach db.

**Additional data / screenshots**

The mdl_config table is created with the following commands:
```
CREATE TABLE mdl_config (
    id BIGSERIAL,
    name VARCHAR(255) NOT NULL DEFAULT '',
    value TEXT NOT NULL,
CONSTRAINT mdl_conf_id_pk PRIMARY KEY (id)
)
;
COMMENT ON TABLE mdl_config IS 'Moodle configuration variables'
;
```
iomad seems to be deciding whether the table exists or not based on the following query: 
```
SELECT a.attnum, a.attname AS field, t.typname AS type,
a.attlen, a.atttypmod, a.attnotnull, a.atthasdef, d.adsrc
                  FROM pg_catalog.pg_class c
                  JOIN pg_catalog.pg_namespace as ns ON ns.oid = c.relnamespace 
                  JOIN pg_catalog.pg_attribute a ON a.attrelid = c.oid
                  JOIN pg_catalog.pg_type t ON t.oid = a.atttypid
             LEFT JOIN pg_catalog.pg_attrdef d ON (d.adrelid = c.oid AND d.adnum = a.attnum)
                 WHERE relkind = 'r' AND c.relname = 'mdl_config' AND c.reltype > 0 AND a.attnum > 0
                       AND (ns.nspname = current_schema() OR ns.oid = pg_my_temp_schema())
              ORDER BY a.attnum;
```

If I sleep the installer after it creates tables and run the query on cockroach and postgress these are the results.

cockroach:
```
  attnum | field | type | attlen | atttypmod | attnotnull | atthasdef | adsrc  
+--------+-------+------+--------+-----------+------------+-----------+-------+
(0 rows)
```

postgre11:
```
 attnum | field |  type   | attlen | atttypmod | attnotnull | atthasdef |                 adsrc                  
--------+-------+---------+--------+-----------+------------+-----------+----------------------------------------
      1 | id    | int8    |      8 |        -1 | t          | t         | nextval('mdl_config_id_seq'::regclass)
      2 | name  | varchar |     -1 |       259 | t          | t         | ''::character varying
      3 | value | text    |     -1 |        -1 | t          | f         | 
(3 rows)
```

**Environment:**
 - CockroachDB version: cockroachdb/cockroach-unstable:v20.1.0-alpha20191216, cockroachdb/cockroach:v19.2.2
 - Server OS: ubuntu 19.10/docker
 - Client app: php, iomad

**Comment by jordanlewis** [comment]
Thanks @jamiechapmanbrn, and sorry for the lack of response here. We're interested in improving compatibility for cases like these, and things might have improved in our latest 20.2 release. If you get a chance to try again, please respond on this issue.
