### ISSUE TITLE
sql: higher latency when using database name to specify table name in query

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach#44562]
**Describe the problem**
When performing a read query while explicitly stating the database name with the table name, the table descriptor cache appears to not be used.

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**
Steps:
1. cockroach demo --geo-partitioned-replicas
2. In SQL shell, select * from movr.rides limit 1; (run it multiple times to compare with step 4)
3. view latency of results
4. select * from rides limit 1; (run it multiple times to compare with step 1)
5. view latency of results. they're usually < 2ms

These repro steps were inspired from this [follower reads acceptance test (repro steps included)](https://docs.google.com/document/d/13h7Xj1IakXq9mqYcO-Coo2GmfpnjHFavw-Pif0z1gkA/edit#heading=h.yi2gf9kbsuz6). 

What did you do? Describe in your own words.
In my read query, I used "movr.rides" instead of "rides."

**Expected behavior**
I expect the latency for step 2 (select * from movr.rides limit 1;) to be the same as step 4's (select * from rides limit 1;).

**Additional data / screenshots**
<img width="1920" alt="Screen Shot 2020-01-30 at 4 25 23 PM" src="https://user-images.githubusercontent.com/1663752/73491742-483aaf80-437d-11ea-84ff-35da6c22ff19.png">

**Environment:**
Johns-MBP:cockroach johnkendall$ ./cockroach version
Build Tag:    v20.1.0-alpha.20191118-1593-g366e993d30
Build Time:   2020/01/27 18:54:40
Distribution: CCL
Platform:     darwin amd64 (x86_64-apple-darwin19.2.0)
Go Version:   go1.13.4
C Compiler:   4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.16)
Build SHA-1:  366e993d30c9997b5d3f6b50b1f3fa5be47da03a
Build Type:   development

**Comment by awoods187** [comment]
Is this related to something in how demo works? @rohany or @otan ?

**Comment by rohany** [comment]
`cockroach demo` isn't actually a multi region cluster -- its just 9 in memory cockroach nodes that have localities tagged to different parts of the world. I'm not sure small variations latency in cockroach demo are indicative of performance regressions etc.

**Comment by rohany** [comment]
I tried this on a single node cockroach cluster and the latency of executing `select * from movr.rides` vs `select * from rides` is slightly higher as well. ~600 vs ~750 micro seconds.

**Comment by rohany** [comment]
There are probably some extra steps taken to do name resolution of the database, which might account for some of the latency difference. Either way, i don't think you can just immediately hone in on "table descriptor cache isn't used" as the reason without some more evidence that it is indeed the case.

**Comment by johnrk** [comment]
> There are probably some extra steps taken to do name resolution of the database, which might account for some of the latency difference. Either way, i don't think you can just immediately hone in on "table descriptor cache isn't used" as the reason without some more evidence that it is indeed the case.

**Comment by johnrk** [comment]
@rohany , that's fair. I've updated the title of the bug to better reflect what we're seeing

**Comment by otan** [comment]
i think this is related to the fact that when we query `a.b`, it has to first resolve whether it means `<schema>.<table>`, before attempting to do `<database>.<table>`. It should be optimally fast if you run `<database>.<schema>.<table>`.

**Comment by awoods187** [comment]
@otan as in this difference is sort of inevitable and not something we could address?

**Comment by solongordon** [comment]
Can we run some benchmarks to double-check that we haven't made this worse between v19.2 and v20.1 by adding the new schema resolution logic?

**Comment by otan** [comment]
> i think this is related to the fact that when we query a.b, it has to first resolve whether it means <schema>.<table>, before attempting to do <database>.<table>. It should be optimally fast if you run <database>.<schema>.<table>.

this is indeed correct - it needs to through an extra round of reading:
https://github.com/cockroachdb/cockroach/blob/2eebbddbb133eea7102a47fbe7f5d13ec6f8f670/pkg/sql/sem/tree/name_resolution.go#L282-L306

i can also reorder to `schema.table` comes after `database.table`, but that isn't optimal in other cases.

furthermore, concurrency doesn't work because i *think* the TableCollection isn't thread safe, and if it was it'd be thrashing over the same lock anyway. thus

> @otan as in this difference is sort of inevitable and not something we could address?

i think the answer is yes.

> Can we run some benchmarks to double-check that we haven't made this worse between v19.2 and v20.1 by adding the new schema resolution logic?

i will file this as a separate task: https://github.com/cockroachdb/cockroach/issues/44733

**Comment by otan** [comment]
one other thought - we could look at benchmarking/telemetry which one is resolved more frequently (at this point it's definitely `database.table` since custom schemas are not available) and switch the order if required. but any documentation around order of precedence for schema resolution is updated, and i don't think it makes sense if `database.table` takes precedence over `schema.table`. this seems like a sad side effect of having "three level schemas".
