### ISSUE TITLE
opt: improve distinct count estimation for multi-span constraints

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#44563]
Whenever there is an open-ended span in a constraint (e.g., `[ - 5]`) and we do not have a histogram on the column, we cannot accurately estimate the distinct count. Currently, we use the heuristic that the resulting distinct count is 1/3 * (input distinct count). However, we should be able to do better in cases where there are multiple spans (e.g., `[ - 5][10 - 10][15 - 15]`). In this case, we can infer that there are *at least two* distinct values (10 and 15), and maybe more. This gives us a lower bound on the distinct count, and may allow us to make more accurate selectivity estimations for tables with a small number of rows.

**Comment by rytaft** [comment]
cc @andy-kimball

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4548](https://cockroachdb.zendesk.com/agent/tickets/4548) has been linked to this issue.
