### ISSUE TITLE
ui:provide a user-friendly message when non-admin user accesses privileged web page

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#44600]
This is related to [tech advisory](https://forum.cockroachlabs.com/t/cockroachdb-technical-alert-01-22-2020/3433). Today, in Cockroach 19.2.2 and 19.1.6, if non-admin user navigates to a priveledged page on the UI, they will be greeted with `Internal Server Error`, see image below.

![internal-server-error](https://user-images.githubusercontent.com/461296/73551734-f47ba500-4414-11ea-80fc-e8e8f497d2f5.png)

I recommend to change the default message to something less dramatic and aesthetically pleasing. 
Instead of throwing that error, it should say something like `the current user does not have rights to access this page.` and point to mitigation steps, i.e. add user to `admin` role.

**Comment by dbist** [comment]
@knz @kenliu @tim-o FYI

**Comment by piyush-singh** [comment]
We should link to the documentation that @taroface is adding.

**Comment by tim-o** [comment]
@piyush-singh is there any commitment to get this out in a future version? Users are hitting this every day.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4706](https://cockroachdb.zendesk.com/agent/tickets/4706) has been linked to this issue.

**Comment by mattcrdb** [comment]
We have seen this on the forum: https://forum.cockroachlabs.com/t/gui-is-no-longer-usable-since-update-to-v19-2-2-core/3412

On the community slack: https://cockroachdb.slack.com/archives/CP4D9LD5F/p1581577209135700

On zendesk from both core and enterprise users.

**Comment by piyush-singh** [comment]
This should be fixed by #45122
