### ISSUE TITLE
sql: populate pg_catalog.pg_aggregate table

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#44616]
According to PostgreSQL docs (https://www.postgresql.org/docs/9.4/catalog-pg-aggregate.html):

"The catalog `pg_aggregate` stores information about aggregate functions. An aggregate function is a function that operates on a set of values (typically one column from each row that matches a query condition) and returns a single value computed from all these values. Typical aggregate functions are `sum`, `count`, and `max`. Each entry in `pg_aggregate` is an extension of an entry in `pg_proc`. The `pg_proc` entry carries the aggregate's name, input and output data types, and other information that is similar to ordinary functions."

We already have incomplete (according to the comment) population of `pg_proc` though.

**Comment by solongordon** [comment]
@rkruze Do you have any more information about which tool(s) rely on this? Would help for prioritization.

**Comment by jordanlewis** [comment]
@rafiss can you and Adam take this one?

**Comment by rkruze** [comment]
@solongordon this was from Looker

**Comment by sandyleo26** [comment]
happy to take it. could someone give some pointers on where to start?

**Comment by learning-dev** [comment]
There is no info to how to get started. I have done the local setup, but I have no idea after the setup. This is first time.

**Comment by rafiss** [comment]
@sandyleo26 the place to get started is in pg_catalog.go. Take a look at how the other virtual tables are defined, and define a schema as described by the Postgres docs: https://www.postgresql.org/docs/9.6/catalog-pg-aggregate.html

A lot of the columns are foreign key references to rows of the pg_proc table, so some of the information you need to populate could came from there.

**Comment by sandyleo26** [comment]
thanks @rafiss i'm having trouble getting a clean build as [mentioned](https://github.com/cockroachdb/cockroach/issues/45848#issuecomment-597035148). will try again tmr.

**Comment by sandyleo26** [comment]
hi due to personal priorities change i no longer have time to work on this in the near future. happy if someone could take it over. thanks.

**Comment by abbccdda** [comment]
I could take this one as my starting project if no one else is looking into it :)

**Comment by jordanlewis** [comment]
Go for it! Submit a PR and we can discuss there.

**Comment by abbccdda** [comment]
@abhishek20123g Glad to see this get done! Sorry I didn't find a chance to be able to implement it :(
