### ISSUE TITLE
running into txn conflict while attempting to implement own TPC-C benchmark

### ISSUE THREAD

**Issue by GOGOYAO** [cockroachdb/cockroach#44637]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:
I want to run tpcc test on CockroachDB by BenchmarkSql. I modify some code based on the code for postgresql. I modify the sql to create table and remove `for update` statement from `select for update`. After I created all the tables succeccfully, I run `./runLoader.sh props.crdb` to load data. But it failed as follows.

```
Worker 000: Loading ITEM
Worker 001: Loading Warehouse      1
Worker 000: Loading ITEM done
Worker 001: ERROR: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_TIMESTAMP_CACHE_REJECTED_POSSIBLE_REPLAY): "sql txn" id=1c4596ad key=/Table/95/1/1/2/801/0 rw=true pri=0.01738756 stat=PENDING epo=0 ts=1580714801.074852739,19 orig=1580714801.024797344,0 min=1580714801.024797344,0 max=1580714801.074852739,18 wto=false seq=401
```

We can see `ITEM` was loaded successfully but `Warehouse` did not.

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
2. Send SQL ... / CLI command ...
3. Look at UI / log file / client app ...

**Expected behavior**

The data should be loaded successfully.

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version [e.g. 2.0.x]
 - Server OS: [e.g. Linux/Distrib]
 - Client app [e.g. `cockroach sql`, JDBC, ...]

CockroachDB version: 19.2.2
OS: centos 7.7
Client app: jdbc

**Additional context**
What was the impact?

**Comment by knz** [comment]
@shengyunyao there are more changes needed to the SQL code to make TPC-C run on CockroachDB. Additionally, your client code must use client-side retries to handle that error, as documented here: https://www.cockroachlabs.com/docs/stable/transactions.html#client-side-intervention-example

We already provide a TPC-C runner inside CockroachDB via the `cockroach workload` command. The code for this is in `pkg/workload/tpcc`. Please use that as a starting point instead of trying to re-implement from scratch.

**Comment by shengyunyao** [comment]
@knz Thank you. What I want to do is I want to use a same tpcc tool to compare Cockroach with other DBs.

**Comment by knz** [comment]
You need to implement at least a retry loop as documented here: https://www.cockroachlabs.com/docs/stable/transactions.html#client-side-intervention-example

This is necessary for every serializable database. The reason why you may not need to do it with other dbs is that TPC-C can run with a lower isolation level where retry errors do not occur. However both pg and crdb require a retry loop when using SERIALIZABLE.

**Comment by shengyunyao** [comment]
> You need to implement at least a retry loop as documented here: https://www.cockroachlabs.com/docs/stable/transactions.html#client-side-intervention-example
> 
> This is necessary for every serializable database. The reason why you may not need to do it with other dbs is that TPC-C can run with a lower isolation level where retry errors do not occur. However both pg and crdb require a retry loop when using SERIALIZABLE.

I get it. So can I use a lower isolation level in Cockroach now?

**Comment by knz** [comment]
no.

**Comment by shengyunyao** [comment]
Get it. Thank you! @knz

**Comment by rafiss** [comment]
Closing this out since the issue needs to be addressed client-side. Please let us know if there's anything else.
