### ISSUE TITLE
sql: safe to upgrade cluster query

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#44643]
In recent conversations about upgrading clusters with @lucy-zhang and others, we realized that developers don't always know when their cluster is safe to upgrade. For example, we'd want to ensure that there are no schema changes running, no dead nodes, no unavailable ranges, etc. 

In addition to piping this into the webui, it would be great if we could provide appdevs a query that lets them know if the cluster is safe to upgrade. Something like:
```SQL
show cluster upgrade status
```
It could return a boolean flag that says a cluster is ready to upgrade/not ready to upgrade.

**Comment by otan** [comment]
i feel like this ties in with the long running migrations work that is going on - cc @irfansharif / @tbg would this be something youse could have a crack at doing when it's ready?

**Comment by irfansharif** [comment]
It does tie in with that. We're going to be thinking about how to make cluster upgrades scriptable, so some form of this will come into play there.

**Comment by irfansharif** [comment]
Closing in favor of #39182.
