### ISSUE TITLE
ui: Overhaul of {Node|Store}StatusSummaries structures

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#4465]
In addition to Time Series, the metrics system currently generates routine "StatusSummary" objects for every Node and Store.  These structures can be thought of as a sort of "vertical" time series query, quickly returning the most recent value of several time series relevant to a single node or store.  This is a very efficient way to generate the data tables in our UI.

However, these fields are currently stored as protocol buffers with a sub-optimal message schema; this is not an effective structure, as it is not straightforward to expand them with additional metrics, and there is little benefit to enforcing a rigid schema on something consumed only by the UI.

My suggestions for the overhaul:
1. Remove the rigid schema of these objects; they do not need to contain descriptors or structured MVCC data at the moment, they can simply contain a set of metrics values.
2. Store these objects directly as serialized JSON. These summaries are read directly by the UI, and there is no need to perform any post-processing on the server during a query.

Out of scope for this issiue: We will not attempt to store the Summary objects in a SQL table. They are currently being stored in the KV layer, and this will suffice for the time being.

This is related to #4021

**Comment by BramGruneir** [comment]
As discussed, this approach SGTM

**Comment by mrtracy** [comment]
Some updates on this:

1. We are going to continue storing summaries as protocol buffer messages. However, we will be using a flexible message design, wherein metric values are stored as name/value pairs. These will be marshaled to JSON before being returned to the GUI; however, there are ambitions for the GUI to consume protobufs directly in the future.
2. I am moving forward under the assumption that StoreSummaries are no longer necessary as separately stored messages. Instead, we will store only NodeSummaries, and each NodeSummary will contain a set of StoreSummaries. This is consistent with our current UI and our UI plans going forward.

**Comment by BramGruneir** [comment]
Why use protocol buffers if you're just moving to a key value pair instead?  What advantage does this have over using protocol buffers as before or moving to just storing JSON directly as the original design mentioned?

**Comment by mrtracy** [comment]
I discussed this in person with @tamird.  There are two main reasons:

1. Protocol buffers still provide _some_ predictable structure to the type, even if its a flexible structure like key/value pairs. This structure also provides guidance on how the messages can be safely augmented with new information in the future.
2. It seems increasingly likely that we will be able to share protocol buffers directly with the javascript front-end in the future (without marshaling to JSON). This would be a significant win for several reasons (front-end code generation, better verification of messages, and a speed boost).

**Comment by BramGruneir** [comment]
If the second case is true, why not just define the protocol buffer in its
entirety?  Of course add a dictionary for easy expandability, but you are
defining an interface at this point.  So obviously restructure the current
proto into an updated one.  Moving all the values into a dictionary seems
like a cheat instead of just adding the values you want.

Protos are designed to be easily added to. Which is what you'll most likely
be doing in the future.  For experimentation, use the dictionary, but once
a key is going to be used going to be used in the ui, move it to the proto
proper.

**Comment by mrtracy** [comment]
Transferring the metrics, which are stored in a dictionary-like structure, onto a strongly typed protocol buffer message is a particularly nasty undertaking without an exceptional refactoring.  Perhaps it could work in the future, but its not going to be a short term thing; for now, using a `map` field in the protocol buffer is the best solution.

**Comment by BramGruneir** [comment]
I'm going to disagree.  This is a potentially public interface.  We should make these as direct as possible.  I can see external projects using the metrics endpoints to interface with other systems, so this interface might need to be documented.  Fully using protos will make this direct and easy.

Also, until your recent PR, isn't this is exactly what we were doing, so how would it require a significant refactor?

**Comment by mrtracy** [comment]
I have logged a post-beta issue #5421 to capture this.  What we are missing is a clear "contract" of what metrics we are providing - this impacts the entire metrics system, not just status summaries.

However, this is obviously not going to fit into the beta time frame.  As our code is today, it is quite nasty to extract a metric value from our registries and associate it with a statically-typed field on the protobuffer.  I know I was doing that previously, but that was a stop gap; I even prefaced a whole section with a comment to the effect of "This is a nasty hack and it will go away with #4465".

Doing a better job is going to involve a refactoring of the metric registry, which is going to require some brainstorming and design, and that is not going to fit into our beta timeframe.

**Comment by BramGruneir** [comment]
Wonderful, SGTM
