### ISSUE TITLE
cli: initialization errors should be logged to stderr in default config

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#4466]
now when starting `cockroach start` with no argument (and certs previously created) the user should get a working server. 

The problem is that if there is an initialization error -- error in gossiping, error in joining, TLS certification error -- nothing is logged to stderr, the user gets the impression the server is running, but clients will fail to connect with a TCP timeout. Since this is the default config and likely the first to be tried by users, this results in poor experience.

Possible strategies:
- Errors+warnings during initialization should be duplicated to stderr, and only start honouring "no stderr logging" after the server starts listening succesfully
- Ensure the server exits with a non-zero status if non-recoverable errors are encountered during initialization. For example a TLS error on the self-gossip interface would qualify as such.

**Comment by petermattis** [comment]
Can you give a reproducible example? We should be logging errors and fatals to stderr. See the `--log-threshold` flag (which defaults to `ERROR`).

**Comment by knz** [comment]
Sure. I run:
```
cockroach create-ca
cockroach create-node localhost ::1 127.0.0.1
cockroach create-client root
cockroach start
```

This prints:
```
admin:  https://ip-172-31-50-219:26257
sql:    postgresql://root@ip-172-31-50-219:15432?sslcert=certs%2Froot.client.crt&sslkey=certs%2Froot.client.key&sslmode=verify-full&sslrootcert=certs%2Fca.crt
logs:   /tmp
stores: ./cockroach-data
```
And the server appears to be running.

Then from a different terminal:
```
cockroach sql
```
then at the prompt:
```
create database t;
```
The command hangs silently, and there is no information about the problem, also not in the server stderr.

Now if I restart my server with `--logtostderr true` I see what's happening:
```
W0217 22:19:56.261254 10245 rpc/client.go:328  x509: certificate is valid for localhost, not ip-172-31-50-219
I0217 22:19:56.267176 10245 server.go:1934  http: TLS handshake error from 172.31.50.219:33682: remote error: bad certificate
W0217 22:19:57.134850 10245 rpc/client.go:328  x509: certificate is valid for localhost, not ip-172-31-50-219
I0217 22:19:57.139111 10245 server.go:1934  http: TLS handshake error from 172.31.50.219:33684: remote error: bad certificate
W0217 22:19:59.229982 10245 rpc/client.go:328  x509: certificate is valid for localhost, not ip-172-31-50-219
I0217 22:19:59.234184 10245 server.go:1934  http: TLS handshake error from 172.31.50.219:33686: remote error: bad certificate
```

(a side issue is that even with the error, as a beginner user I am still unsure how to fix the problem. But that's a different issue, I think duplicate of #4434 and #3792)

**Comment by petermattis** [comment]
Ah, neither of those log messages are errors (one is an INFO and the other a WARNING). We definitely need to improve this experience.

**Comment by knz** [comment]
Heads up: for the specific case of the TLS error, I made a mistake. The error *does* show up on stderr. But this is only because of #4374. When you address #4374 (which I was in the process of doing) the TLS error disappears from stderr. 

This issue remains however for other types of error, for example gossiping fails to initialize.
