### ISSUE TITLE
server,kv: enable auto-detection of locality

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#44691]
Cassandra has a nice feature that allows nodes to auto-detect and self assign localities via a snitch class: https://github.com/apache/cassandra/blob/f7431b432875e334170ccdb19934d05545d2cebd/src/java/org/apache/cassandra/locator/Ec2Snitch.java

This was an enhancement request from a customer that has had experience with operating Cassandra. They pointed out that this type of tool avoids fat finger mistakes. They also pointed out that locality assignment for their CRDB deployment is currently automated by startup scripts and reasonably safe today. Still, this would help first time operators get up and running with some features faster.

**Comment by knz** [comment]
dup #38474
