### ISSUE TITLE
sql: pg_sleep return type differs from Postgres 

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#44701]
In Postgres, the `pg_sleep` function returns `''`. In CockroachDB, it returns `True`.

This causes `test_async_callproc` to fail in the psycopg2 test suite.

**Comment by rohany** [comment]
How did you see that it returns `''`? Running `select pg_typeof(pg_sleep(1))` returns `void`. Is that what `''` means?

**Comment by rafiss** [comment]
I suppose so -- `''` is how the return value shows up in the psycopg2 test. See the last line:
```
    def test_async_callproc(self):
        cur = self.conn.cursor()
        cur.callproc("pg_sleep", (0.1, ))
        self.assertTrue(self.conn.isexecuting())

        self.wait(cur)
        self.assertFalse(self.conn.isexecuting())
        self.assertEquals(cur.fetchall()[0][0], '')
```

**Comment by yuzefovich** [comment]
I stumbled into this while talking to Raphael about `void` type over the hackathon, so I opened up #45234. I'll assign that issue to Rohan, feel free to close either if appropriate.

**Comment by otan** [comment]
I'm going to let https://github.com/cockroachdb/cockroach/issues/45234 dominate.
