### ISSUE TITLE
sql: implement functionality for client_min_messages

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#44711]
Currently the `client_min_messages` session variable is just a reserved word that does not change any functionality. 

In Postgres, it has the following behavior:
> Controls which message levels are sent to the client. Valid values are DEBUG5, DEBUG4, DEBUG3, DEBUG2, DEBUG1, LOG, NOTICE, WARNING, and ERROR. Each level includes all the levels that follow it. The later the level, the fewer messages are sent. The default is NOTICE. Note that LOG has a different rank here than in log_min_messages.

The lack of support is causing `AsyncTests.test_notices` to fail in psycopg2.

**Comment by otan** [comment]
i don't think we should mirror the debug information output from the index 

```
otan=# create table chatty (id serial primary key);
DEBUG:  CREATE TABLE will create implicit sequence "chatty_id_seq" for serial column "chatty.id"
DEBUG:  CREATE TABLE / PRIMARY KEY will create implicit index "chatty_pkey" for table "chatty"
DEBUG:  building index "chatty_pkey" on table "chatty" serially
```

as serial is very different for us. i will implement the feature but will not be able to pass the test.
