### ISSUE TITLE
sql: generate "random" data for a given schema 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#44713]
We discussed how we can make things easier for users trying out CockroachDB today. One idea is to, given a schema, generate random data to populate that schema. This could speed up the trial of CRDB. 

Then, a users steps to try CRDB look like:

1. Create schema (copy paste from their app?) ~10 seconds 
2. Use this new command to generate "random" data for X rows  ~ 30 seconds?
3. Try out their apps queries (copy paste from their app?) ~ 10 seconds

The entire trial could be on the order of minutes. 

This eliminates the need to import data into CRDB (or get clearance to do so) during the trial phase. We could also generate this data in a way thats friendly to the optimizer to show off CRDB's capabilities. 

Finally, we may be able to leverage SQLSmith for this since I think it generates data based on a defined schema.

**Comment by awoods187** [comment]
@andy-kimball @RaduBerinde @justinj @rytaft for additional thoughts here

**Comment by awoods187** [comment]
@jseldess what do you think about this? Could be great for demos and guides from docs too

**Comment by rohany** [comment]
There are a host of random datum generation functions that matt has put together. The main work here would be hooking that up to a given schema.

**Comment by jordanlewis** [comment]
`pkg/workload/rand` basically does this already - it could probably be significantly enhanced though!

**Comment by rohany** [comment]
Yeah, i just tried this out. Running `workload run rand --table <their table> --db <their db>` just populates the table with a bunch of random data.

**Comment by jseldess** [comment]
I think this is a great idea, whether using `rand` or another method. If we go with `rand`, can we build it into `cockroach workload`?

**Comment by rohany** [comment]
The above command would work when prefixed the `cockroach`

**Comment by awoods187** [comment]
I'm closing this in favor of the existing cockroach workload and this issue to add it to demo:
https://github.com/cockroachdb/cockroach/issues/46562
