### ISSUE TITLE
sql: server side transaction retries are broken for groups, subqueries

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#4472]
The various visitors that mutate expressions leak these modifications to the next retry of the transaction. We need a more robust scheme of mutating expressions.

I verified that we have a problem with subqueries - when retrying `SELECT k FROM T where k NOT IN (SELECT k from T)` we are actually running `SELECT k FROM T where k NOT IN (1, 2, 3..)`. The values we see in the table could have changed. (It's hard to actually make this return an incorrect result in on a single node though).

**Comment by RaduBerinde** [comment]
Actually I was able to produce a problem by repeatedly running `INSERT INTO TEST.T VALUES ((SELECT MAX(k+1) FROM TEST.T));` from a couple of clients in parallel. I was able to find duplicate values, caused by the fact that when we retry, we don't reevaluate the inner `SELECT`.

@knz you might be running into this problem in your Jepesen testing

**Comment by knz** [comment]
Thanks for the heads up. For now I did not run into this one yet, but perhaps the load was not high enough?
Also I didn't know we were retrying transactions automatically now, is that new? Until now (recently) if there was a retryable error I would see this pop up back in my SQL client.

**Comment by RaduBerinde** [comment]
We can retry single statement transactions (auto-transactions) on the
server side. If you are using multistatement transactions, I don't think
this would affect you.

**Comment by tschottdorf** [comment]
We retry individual statements, not explicit transactions (so we retry what
Radu posted, but not your Jepsen queries). @andreimatei is extending this
to all transactions which hold BEGIN and COMMIT in a single query (and you
can also retry the first chunk of a transaction automatically).

**Comment by knz** [comment]
I think this still doesn't apply to the jepsen tests since I am still using the CLI client with separate arguments after -e, and these are sent as separate queries.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
