### ISSUE TITLE
sql: benchmark schema resolution in 19.2 vs 20.1

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#44733]
since we added extra schema resolution steps for temp table, it would be good to double check that this doesn't adversely affect performance in 20.1

**Comment by otan** [comment]
cc @solongordon i know for a fact this will be slower for `<database>.<table>` referemces because of https://github.com/cockroachdb/cockroach/issues/44562#issuecomment-582182451 -- we previously avoided a schema lookup if the schema name was NOT public, but had to remove that to make https://github.com/cockroachdb/cockroach/pull/44325 work (and is required work for custom schemas).

However, since we can't rely on that anymore, we always do a schema lookup on two component names, which if it is `<database>.<table>`, will be slower. Is this a concern? Maybe something worth putting in the docs?

**Comment by ajwerner** [comment]
>Is this a concern?

Discussed elsewhere. The answer is a gigantic yes. Imagine you have a geo-partitioned cluster. The resolution is likely to be a WAN hop. This would destroy performance for global deployments.

**Comment by otan** [comment]
Schema change discussion moved to https://github.com/cockroachdb/cockroach/issues/44802; I'll reserve the ticket remaining to add benchmarks and compare 20.1 to 19.2, which can be used for future implementations.

**Comment by otan** [comment]
here are my results. looks like we've...improved in 20.1?! either way, doesn't seem like the upcoming release does anything bad.

master:
```
I200206 18:53:26.684172 1 rand.go:85  Random seed: -8447949488928499937
goos: darwin
goarch: amd64
pkg: github.com/cockroachdb/cockroach/pkg/bench
BenchmarkTableResolution/table-16               5834        200125 ns/op
BenchmarkTableResolution/database.table-16              6861        202945 ns/op
BenchmarkTableResolution/database.public_schema.table-16                5593        214491 ns/op
BenchmarkTableResolution/public_schema.table-16                         5979        209202 ns/op
PASS
ok      github.com/cockroachdb/cockroach/pkg/bench  8.782s
```

release-19.2:
```
I200206 19:01:25.093500 1 rand.go:85  Random seed: -5518899393321279758
goos: darwin
goarch: amd64
pkg: github.com/cockroachdb/cockroach/pkg/bench
BenchmarkTableResolution/table-16               6880        149251 ns/op
BenchmarkTableResolution/database.table-16              7514        141782 ns/op
BenchmarkTableResolution/database.public_schema.table-16                8334        142113 ns/op
BenchmarkTableResolution/public_schema.table-16                         7436        141987 ns/op
PASS
ok      github.com/cockroachdb/cockroach/pkg/bench  6.534s
```

**Comment by otan** [comment]
it seems as if querying by just single table, e.g. `select * from <table>`, is slower. investigating.

**Comment by otan** [comment]
i believe this is because it tries to query the temporary schema before the public schema if *only* table name is specified.
