### ISSUE TITLE
ui: Add "Status" column to databases list and table list pages

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#44758]
We will add a "Status" column to the databases and tables list pages. We will show some information about statuses that impact the databases or tables in question. This requires thinking about how to efficiently surface this information in the UI with some input needed on the fullstack/backend side.

Must have:
- Unavailable ranges
- Underreplicated ranges

@Annebirzin do we expect to have the range values link through to another page? If we haven't determined where to link through, we can file that as a follow on issue.

Should have:
- Ongoing Schema Changes (with a link to the appropriate job)

Link to designs: https://zpl.io/bzRmArG

**Comment by Annebirzin** [comment]
@piyush-singh good point. I think we could link them through to the problem ranges report since that is what we are planning to do on the dashboard. I can add that state to the designs.

**Comment by Annebirzin** [comment]
@piyush-singh this is probably a separate issue, but the unavailable/under-replicated range could will also show on the table detail page and link to the problem ranges report: https://zpl.io/VY77jyw
