### ISSUE TITLE
Unexpected error for aggregate functions

### ISSUE THREAD

**Issue by mrigger** [cockroachdb/cockroach#44757]
Consider the following statements:

```sql
CREATE TABLE t0(c0 INT);
SELECT MIN(1), MAX(NULL AND true) FROM t0; -- ERROR: no builtin aggregate for MAX on [{InternalType:{Family:UnknownFamily Width:0 Precision:0 ArrayDimensions:[] Locale:0x6fcee60 VisibleType:0 ArrayElemType:<nil> TupleContents:[] TupleLabels:[] Oid:705 ArrayContents:<nil> TimePrecisionIsSet:false IntervalDurationField:<nil>}}]
```
The error message of the `SELECT` seems somehow unexpected, partly because it looks like an internal one. Furthermore, when removing the `MIN(1)`, the query executes without errors. It also executes without errors when replacing `MAX(NULL and true)` by `MAX(NULL)`.

I found this potential issue based on commit `8c0234e81b9893a36b2a28e52ad361c03c2b8640`.

Jira issue: CRDB-5206

**Comment by yuzefovich** [comment]
The internal error comes from the execution, but I think the optimizer should have caught that there is no aggregate function with untyped `NULL` argument.

Interestingly, removing `MIN` from the query or doing `SELECT max(NULL AND true)` works in CockroachDB (whereas Postgres complains that explicit type casts are needed).

```
root@127.0.0.1:59678/defaultdb> select max(null);
  max
--------
  NULL
(1 row)

Time: 304µs

root@127.0.0.1:59678/defaultdb> select max(null and true);
  max
--------
  NULL
(1 row)

Time: 543µs

root@127.0.0.1:59678/defaultdb> CREATE TABLE t0(c0 INT);
SELECT MIN(1), MAX(NULL AND true) FROM t0;
CREATE TABLE

Time: 3.119ms

ERROR: no builtin aggregate for MAX on [{InternalType:{Family:UnknownFamily Width:0 Precision:0 ArrayDimensions:[] Locale:0xa3fbde0 VisibleType:0 ArrayElemType:<nil> TupleContents:[] TupleLabels:[] Oid:705 ArrayContents:<nil> TimePrecisionIsSet:false IntervalDurationField:<nil>}}]
root@127.0.0.1:59678/defaultdb> SELECT MAX(NULL AND true) FROM t0;
  max
--------
  NULL
(1 row)

Time: 696µs
```

Putting it into SQL planning project. cc @RaduBerinde @rytaft

**Comment by mgartner** [comment]
This no longer produces an error on v22.2.2:

```
defaultdb> CREATE TABLE t0(c0 INT);
CREATE TABLE

defaultdb> SELECT MIN(1), MAX(NULL AND true) FROM t0;
  min  | max
-------+-------
  NULL | NULL
(1 row)
```

Postgres returns a user error `42883: function max(boolean) does not exist`. We don't return the same error, likely because our type-checking doesn't exactly match PG's. That's a separate issue though, so I'll close this.
