### ISSUE TITLE
ui: Databases list page overhaul

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#44759]
This issue tracks the work to overhaul the database list component. Note that this new page only lists databases, and that in order to view tables, users will need to click through to a database.

Design link: https://zpl.io/bzRmArG

Note that adding in the status column is a separate issue filed here: #44758. We will need to plumb this data through, so it will require some coordination with backend work in the UI to expose the appropriate data. 

@dhartunian I don't believe we expose database or table level QPS, is this information available already in the UI? If not, please let me know and I can file a separate issue to fetch that data.

**Comment by Annebirzin** [comment]
@elkmaster fyi I've added icons to help differentiate the databases list from the table list 
- Database list: zpl.io/bJx45E3
- Table list (header and list items): zpl.io/VxXe8nE
- Table detail: zpl.io/VY77jyw


Attached are svgs if needed
[icons.zip](https://github.com/cockroachdb/cockroach/files/4182123/icons.zip)

**Comment by piyush-singh** [comment]
@dhartunian and I were just taking a look at this page. We found that there are no database level statistics exposed to the UI, and we didn't find any easy way to fetch that information in the SQL shell. This means showing this data will require computing it from the constituent tables of the database and will therefore be slow as we wait for all the data for all tables in a DB to load. We might need to revisit what this could look like without statistics if it is too expensive to fetch them.
