### ISSUE TITLE
adminui: placeholder alt text on the admin ui

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#44768]
On the statements page

![Screenshot 2020-02-05 12 27 04](https://user-images.githubusercontent.com/377201/73866531-03969480-4813-11ea-964b-791cc37b3c69.png)

**Comment by dhartunian** [comment]
@taroface can you let us know what copy should appear in the tooltip here?

**Comment by taroface** [comment]
@dhartunian How about: "Execution statistics for this statement per gateway node."
