### ISSUE TITLE
ui: Table details page "Overview"

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#44764]
Overview section of the table details page. Once a user drills into a specific table, they should be able to see the create table statement and table metadata along with values for the status column for the table (from the table list page) in a section on the right hand side.

@Annebirzin we had a brief discussion about exposing zone configurations here, does it makes sense to file that as a follow on issue/enhancement?

Design Link: https://zpl.io/aBpLEBm

**Comment by Annebirzin** [comment]
@piyush-singh I can add zone configs to the design, but might make sense to break out as a separate issue
