### ISSUE TITLE
sql,pgwire: missing ParameterStatus packets upon SET statements

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#44804]
As per pg docs: https://www.postgresql.org/docs/12/protocol-flow.html#PROTOCOL-ASYNC

> ParameterStatus messages will be generated whenever the active value changes for any of the parameters the backend believes the frontend should know about. Most commonly this occurs in response to a `SET` SQL command executed by the frontend, and this case is effectively synchronous — but it is also possible for parameter status changes to occur because the administrator changed a configuration file and then sent the SIGHUP signal to the server. Also, if a `SET LOCAL` command is rolled back, an appropriate ParameterStatus message will be generated to report the current effective value.
>
> At present there is a hard-wired set of parameters for which ParameterStatus will be generated: they are `server_version`, `server_encoding`, `client_encoding`, `application_name`, `is_superuser`, `session_authorization`, `DateStyle`, `IntervalStyle`, `TimeZone`, `integer_datetimes`, and `standard_conforming_strings`. (server_encoding, TimeZone, and integer_datetimes were not reported by releases before 8.0; standard_conforming_strings was not reported by releases before 8.1; IntervalStyle was not reported by releases before 8.4; application_name was not reported by releases before 9.0.) [...] 
>
> a frontend should simply ignore ParameterStatus for parameters that it does not understand or care about.

**Comment by knz** [comment]
A most likely symptom of this bug is an app or client not printing timestamps in the right TZ after changing the timezone parameter.

**Comment by knz** [comment]
cc @jordanlewis for triage

**Comment by otan** [comment]
thought we covered some of this: https://github.com/cockroachdb/cockroach/pull/42376

**Comment by knz** [comment]
Yes indeed it was. I had tested with 19.2 and was unaware this had been addressed already. thanks
