### ISSUE TITLE
sql: network fuzz testing

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#4483]
Need to do some fuzz testing of pgwire. Due to its implementation, it's not easily fuzz-able within the code. Instead, we could consider using a network fuzzer like [sulley](https://github.com/OpenRCE/sulley).

**Comment by xiang90** [comment]
@mjibson 

Something as simple as https://github.com/coreos/etcd/blob/master/pkg/netutil/isolate_linux.go#L23-L42 works really well for etcd network fuzz testing. We just build a control plane to keep on inject failures.

**Comment by xiang90** [comment]
If you want to implement a more generic network layer fuzz testing tool, we (etcd community) would love to collaborate.

**Comment by tamird** [comment]
Closing since I think @nvanbenschoten has already done some work here. Please reopen if I'm mistaken.

**Comment by mjibson** [comment]
We fuzzed the network code? Specifically the pgwire stuff?

**Comment by tamird** [comment]
https://github.com/cockroachdb/go-fuzz/pull/4

**Comment by nvanbenschoten** [comment]
@mjibson The work with go-fuzz was primarily focused on pgwire v3 connection logic. Your mention of sulley makes me think that your original intention here was somewhat orthogonal to this. Do you think we should reopen this issue?

**Comment by mjibson** [comment]
My original hope was that we could hook go-fuzz up to our entire SQL test corpus to get some nice multi-message stuff going. The intro stuff you did seems great for some simple connection fuzzing. I think we can close this issue for now and someone can reapproach later if they want. But more testing would fuzz test things like prepared statements and query execution.
