### ISSUE TITLE
bulk-io: importing into/ Import table throwing error when using WITH NULLIF = 'NULL'

### ISSUE THREAD

**Issue by roncrdb** [cockroachdb/cockroach#44830]
**Describe the problem**

A user was trying to import into an existing table but kept seeing the following error: 

row 1: parse "invitation_created_at" as TIMESTAMP: parsing as type timestamp: missing required date fields

I was able to replicate their issue using the exact table schema, I was not able to reproduce this issue when creating my own schema. 

I've attached the file they tried to import, as well as the schema and command they ran [here](https://drive.google.com/drive/folders/1GKKbRAUFNEc0GYhN6EmTNUV1eOycOTQ6?usp=sharing)

I created my own schema that consisted of just an ID and a column with a TIMESTAMP data type and was not able to reproduce the error. 

I tried having the logs output more verbose errors by running: 

`cockroach start --insecure --store=node1 --listen-addr=localhost:26261 --http-addr=localhost:8084 --logtostderr --vmodule=csv=3`

Then running the import, seeing it fail, and checking the logs, but nothing was output there that related to import. 

**To Reproduce**

Start a local cluster
Create the table with the attached schema
Run the command

**Expected behavior**
The table should import without throwing this error, or at least give an error that is more useful than the one we are getting

**Environment:**
 - CockroachDB version 19.2.2/Master

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4622](https://cockroachdb.zendesk.com/agent/tickets/4622) has been linked to this issue.

**Comment by roncrdb** [comment]
We can close this, there was an issue with the exported data the client provided, however the error message that we print was not very useful, so perhaps we can change the error message when imports fail to print both the column name and the input that it's getting? Currently, the error just prints the column name that is invalid, we would have arrived at a solution quicker had we known that the value that it was reading was not "NULL" but rather the number zero.
