### ISSUE TITLE
roachtest: crdb logs missing from artifacts

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#44843]
They don't get collected because:

```
[19:33:57] :	 [Step 2/2] Publishing artifacts (2s)
[19:33:57] :		 [Publishing artifacts] Collecting files to publish: [/home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/tpcc/w=100/nodes=3/chaos=true/** => tpcc/w=100/nodes=3/chaos=true]
[19:33:58] :		 [Publishing artifacts] Publishing 113 files using [ArtifactsCachePublisher]: artifacts/tpcc/w=100/nodes=3/chaos=true/** => tpcc/w=100/nodes=3/chaos=true
[19:33:58] :		 [Publishing artifacts] Publishing 113 files using [WebPublisher]: artifacts/tpcc/w=100/nodes=3/chaos=true/** => tpcc/w=100/nodes=3/chaos=true
[19:33:57]i:	 [Step 2/2] ##teamcity[publishArtifacts '/home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/tpcc/w=100/nodes=3/chaos=true/** => tpcc/w=100/nodes=3/chaos=true']
[19:33:59]W:	 [Step 2/2] Some of the artifacts cannot be published, they are either locked by external process or agent does not have permissions to read files:
/home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/tpcc/w=100/nodes=3/chaos=true/run_1/1.logs/cockroach-rocksdb.log
/home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/tpcc/w=100/nodes=3/chaos=true/run_1/1.logs/cockroach-rocksdb.teamcity-1728651-1580841091-08-n4cpu4-0001.ubuntu.2020-02-04T19_03_12Z.006755.log
/home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/tpcc/w=100/nodes=3/chaos=true/run_1/1.logs/cockroach-rocksdb.teamcity-1728651-1580841091-08-n4cpu4-0001.ubuntu.2020-02-04T19_11_31Z.007458.log
/home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/tpcc/w=100/nodes=3/chaos=true/run_1/1.logs/cockroach-rocksdb.teamcity-1728651-1580841091-08-n4cpu4-0001.ubuntu.2020-02-04T19_12_28Z.007844.log
/home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/tpcc/w=100/nodes=3/chaos=true/run_1/1.logs/cockroach-rocksdb.teamcity-1728651-1580841091-08-n4cpu4-0001.ubuntu.2020-02-04T19_13_25Z.008194.log
/home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/tpcc/w=100/nodes=3/chaos=true/run_1/1.logs/cockroach-rocksdb.teamcity-1728651-1580841091-08-n4cpu4-0001.ubuntu.2020-02-04T19_16_16Z.008712.log
/home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/tpcc/w=100/nodes=3/chaos=true/run_1/1.logs/cockroach-rocksdb.teamcity-1728651-1580841091-08-n4cpu4-0001.ubuntu.2020-02-04T19_19_07Z.009231.log
/home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/tpcc/w=100/nodes=3/chaos=true/run_1/1.logs/cockroach-rocksdb.teamcity-1728651-1580841091-08-n4cpu4-0001.ubuntu.2020-02-04T19_20_04Z.009578.log
/home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/tpcc/w=100/nodes=3/chaos=true/run_1/1.logs/cockroach-rocksdb.teamcity-1728651-1580841091-08-n4cpu4-0001.ubuntu.2020-02-04T19_25_47Z.010305.log
/home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/tpcc/w=100/nodes=3/chaos=true/run_1/1.logs/cockroach-rocksdb.teamcity-1728651-1580841091-08-n4cpu4-0001.ubuntu.2020-02-04T19_31_30Z.010976.log
/home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/tpcc/w=100/nodes=3/chaos=true/run_1/1.logs/cockroach-rocksdb.teamcity-1728651-1580841091-08-n4cpu4-0001.ubuntu.2020-02-04T19_33_24Z.011431.log
/home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/tpcc/w=100/nodes=3/chaos=true/run_1/1.logs/cockroach.log
/home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/tpcc/w=100
...
```

At first glance this suggests that the nodes are still running and that this somehow causes that problem. But this also includes all old log files, for which the process definitely isn't running.

Instead this hints at a file permission problem. Need to investigate.

This is urgent because we don't get node logs in failing roachtests.

**Comment by tbg** [comment]
```
root@gce-agent-5:/home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/tpcc/w=100/nodes=3/chaos=true/run_4/1.logs# ls -lah
total 1.1M
drwxrwxr-x 4 root root 4.0K Feb  7 10:19 .
drwxr-xr-x 6 root root 4.0K Feb  7 10:20 ..
-rw-r----- 1 root root 300K Feb  7 10:19 cockroach-rocksdb.log
-rw-r----- 1 root root 300K Feb  7 10:19 cockroach-rocksdb.teamcity-1736162-1581070194-02-n4cpu4-0001.ubuntu.2020-02-07T10_13_03Z.003459.log
-rw-r----- 1 root root 203K Feb  7 10:19 cockroach.log
-rw-r--r-- 1 root root  606 Feb  7 10:19 cockroach.stderr.log
-rw-r--r-- 1 root root    0 Feb  7 10:19 cockroach.stdout.log
-rw-r----- 1 root root 203K Feb  7 10:19 cockroach.teamcity-1736162-1581070194-02-n4cpu4-0001.ubuntu.2020-02-07T10_13_03Z.003459.log
drwxr-x--- 2 root root 4.0K Feb  7 10:19 goroutine_dump
drwxr-x--- 2 root root 4.0K Feb  7 10:19 heap_profiler
-rw-r--r-- 1 root root 5.2K Feb  7 10:19 roachprod.log
```

That explains why it won't work, but why ... why root? I'm sure I can blame Docker on this somehow. The repo itself is owned by `agent` as it should be

```
root@gce-agent-5:/home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts# ls -lah
total 16K
drwxr-xrwx  4 agent agent 4.0K Feb  7 10:12 .
drwxrwxrwt 18 agent agent 4.0K Feb  7 10:03 ..
drwxr-xr-x  3 root  root  4.0K Feb  7 10:09 _runner-logs
drwxr-xr-x  3 root  root  4.0K Feb  7 10:12 tpcc
```

**Comment by tbg** [comment]
Oh yeah TC definitely runs stuff through a docker image and I can see that `roachprod` runs as root. Ok great, so we can either stop doing that or make sure we set `o+r` on any artifact.

**Comment by tbg** [comment]
Well.. I can set extra options to `docker run` but I would have to pass the UID of the `agent` user, and that's not stable (or at least I don't want to assume it is). Feels like a problem we have to have  solved before. Anyway, for now I'm just going to make sure `scp` gives us good perms.

**Comment by tbg** [comment]
Aha! `roachprod get` preserves the umask of files it downloads. The original logs on the servers have are 540 (i.e. `rw-r-----`)

```
-rw-r----- 1 ubuntu ubuntu 104K Feb  7 10:56 cockroach.teamcity-1736186-1581071065-01-n4cpu4-0002.ubuntu.2020-02-07T10_
```

Why did this ever work?

**Comment by tbg** [comment]
Hmm, my "fix" in #44847 doesn't seem to have had an effect. I should've verified this better. Looking again.

**Comment by tbg** [comment]
Duh, I "fixed" only the local copying case. I care about scp. Ok, going to send the real patch now

**Comment by tbg** [comment]
Ugh, this is annoying. It's not clear ... why scp uses these perms? roachprod under the hood uses

```
[scp -r -C -o StrictHostKeyChecking=no -i /Users/tschottdorf/.ssh/id_rsa -i /Users/tschottdorf/.ssh/google_compute_engine ubuntu@35.202.91.16:logs logs]
```

Note how this doesn't specify `-p`. Files that have `o+r` on the remote have it locally as well. But files that are not world readable are not locally, too. So it seems `scp` is really applying `-p` for me? It's doesn't seem obvious how to stop it from doing that.

**Comment by tbg** [comment]
Ugh. When I run something in the builder locally, it's using umask 022 as I'd expect $everyone to do:

```
roach@fafeff71943c:/go/src/github.com/cockroachdb/cockroach$ touch banana
roach@fafeff71943c:/go/src/github.com/cockroachdb/cockroach$ ls -lah banana
-rw-r--r-- 1 roach roach 0 Feb  7 17:24 banana
roach@fafeff71943c:/go/src/github.com/cockroachdb/cockroach$ exit
tschottdorf@gceworker-tschottdorf:~/go/src/github.com/cockroachdb/cockroach$ ls -lah banana
-rw-r--r-- 1 tschottdorf tschottdorf 0 Feb  7 17:24 banana
tschottdorf@gceworker-tschottdorf:~/go/src/github.com/cockroachdb/cockroach$
```

Why are the log files even getting these weird perms?

**Comment by tbg** [comment]
Ah. `build/builder.sh` is chock full of workarounds. Those never replicate to the TC nightlies because they don't use the builder (they just specify some image). Gah.

**Comment by tbg** [comment]
But I still don't understand. Really if I find out who has the `002` umask then I can change that and things will work (enough). Where does this come from? CRDB creates its files using 0644. The docker invocation for the build doesn't say anything...


oh... it's probably this:

```
agent@gce-agent-27:~$ umask
0002
```

This is the user under which the `docker run` invocation is taking place. Could this be it?

**Comment by tbg** [comment]
I mean it must be... I don't see how I can easily change that. But, I can pass `-u $UID` to the docker run invocation, which should own all of these files to the `agent` user and then everything will work. Testing that now...

**Comment by tbg** [comment]
Ugh, this insta failed:

```
[17:47:14]
Running step within Docker container cockroachdb/builder:20200115-154509
[17:47:14]
Starting: /bin/sh -c ". /home/agent/temp/agentTmp/docker-wrapper-5270575096960367303.sh && docker run --rm -w /home/agent/work/.go/src/github.com/cockroachdb/cockroach --label jetbrains.teamcity.buildId=1736603 -u=1002 -v "/home/agent/lib:/home/agent/lib:ro" -v "/home/agent/tools:/home/agent/tools:ro" -v "/home/agent/plugins:/home/agent/plugins:ro" -v "/home/agent/work/.go/src/github.com/cockroachdb/cockroach:/home/agent/work/.go/src/github.com/cockroachdb/cockroach" -v "/home/agent/temp/agentTmp:/home/agent/temp/agentTmp" -v "/home/agent/temp/buildTmp:/home/agent/temp/buildTmp" -v "/home/agent/system:/home/agent/system" --env-file /home/agent/temp/agentTmp/docker-wrapper-8651824324950078011.envList --entrypoint /bin/sh "cockroachdb/builder:20200115-154509" /home/agent/temp/agentTmp/docker-shell-script-316736161429740239.sh"
[17:47:14]
in directory: /home/agent/work/.go/src/github.com/cockroachdb/cockroach
[17:47:15]
WARNING: Could not setup log file in /.config/gcloud/logs, (Error: Could not create directory [/.config/gcloud/logs/2020.02.07]: Permission denied.
[17:47:15]
[17:47:15]
Please verify that you have permissions to write to the parent directory.)
[17:47:16]
ERROR: (gcloud.auth.activate-service-account) Could not create directory [/.config/gcloud]: Permission denied.
[17:47:16]
[17:47:16]
Please verify that you have permissions to write to the parent directory.
[17:47:16]
Process exited with code 1
[17:47:16]
Process exited with code 1 (Step: Command Line)
[17:47:18]
Step Command Line failed
```

Unfortunately I have to drop the pen. This means we're not getting roachtest logs on failures. If someone else can pick this up, I would be delighted.

**Comment by tbg** [comment]
`umask` inside of the script (which is supposedly run from inside the container) returns 0022, i.e. the thing that should work if it didn't change when the crdb process runs. Sad, was hoping I could just change umask in the script and be done.

**Comment by tbg** [comment]
Ah, I'm barking up the wrong tree anyway. The problem is that on the crdb nodes we're creating these files and that the permissions carry over through `scp` (even though we're not asking it to do that). If I want to solve this, I have to figure out why `roachprod run` has a 002 umask for the cockroach process.

**Comment by tbg** [comment]
Okay!

```
$ roachprod run teamcity-1736338-1581091138-03-n4cpu4:1 umask
0002
```

This might be something I can influence.

**Comment by petermattis** [comment]
Sorry I can't pick up the pen on this, but 🍿 watching your progress.

**Comment by tbg** [comment]
Wait I'm completely on the wrong boat again. `umask` 002 corresponds to rwxrwxr-x. 022 is rwxr-xr-x. Both are fine, they both result in global `r--` on a new file. Not to repeat myself, but gah.

**Comment by tbg** [comment]
Ok, running just `./cockroach start --insecure` gives me logs in cockroach-data/logs/*.log that are not world-readable. This happens both on the roachtest machines but also locally on OSX. I would probably know why if I really knew unix. It's not inheriting from the parent, I made those all 777 and it still happens. If I `touch` some file locally or remotely, it gets `rw-r--r--` as you'd expect. But not if it's CRDB creating the logs. I must be overlooking a place where we intentionally use these modes... but I did check the logging code already.

**Comment by tbg** [comment]
```diff
index 836e238b7e..87e0fd9903 100644
--- a/pkg/util/log/file.go
+++ b/pkg/util/log/file.go
@@ -28,6 +28,7 @@ import (
        "sort"
        "strconv"
        "strings"
+       "syscall"
        "time"

        "github.com/cockroachdb/cockroach/pkg/util/syncutil"
@@ -247,6 +248,13 @@ func create(
        // Open the file os.O_APPEND|os.O_CREATE rather than use os.Create.
        // Append is almost always more efficient than O_RDRW on most modern file systems.
        f, err = os.OpenFile(fname, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
+       stat, err := f.Stat()
+       if err != nil {
+               panic(err)
+       }
+       mask := syscall.Umask(0)
+       syscall.Umask(mask)
+       fmt.Println("TBG created with mode ", stat.Mode(), "umask is", mask)
        if err == nil {
                symlink := filepath.Join(dir, link)
```

This tells me

> TBG created with mode  -rw-r----- umask is 23

(23 corresponds to 0027, which explains the resulting perms).

Okay, I assume this is intentional somehow. But where.

**Comment by tbg** [comment]
Jeez, that took me long to find.

https://github.com/cockroachdb/cockroach/blob/6cda8dca01ef6eb689eaaa15364271e1b485c7be/pkg/cli/start_unix.go#L92-L96

I had something about this in the back of my head, but it eluded me until now.

**Comment by tbg** [comment]
Honestly I'm flummoxed why this is a problem now.

At least others on the internet have stumbled about `scp` preserving file permissions despite not being asked to: https://askubuntu.com/questions/862416/scp-creates-undesired-file-permissions

I think I can "fix" this in roachprod get.

**Comment by tbg** [comment]
Looks like the currently running nightly (which picked up https://github.com/cockroachdb/cockroach/pull/44876) has the artifacts:

<img width="543" alt="image" src="https://user-images.githubusercontent.com/5076964/74082238-62008480-4a58-11ea-8178-7dbb5c211115.png">

**Comment by danhhz** [comment]
@tbg to confirm: I need to cherry-pick #44876 into both the current releases to unblock them?

**Comment by tbg** [comment]
No, roachtest is run from master, so you just need to re-run tests
