### ISSUE TITLE
Node crash while executing sql statement

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#44858]
**Describe the problem**

Executing the following (probably incorrect) sql statement causes node to crash

```
select count(*), round(sum(range_size)/(1024*1024), 2) as size_MB, lease_holder, replicas from crdb_internal.ranges where
start_pretty like '/Table/52/2/%' group by lease_holder order by lease_holder;
```
Stacktrace attached.

[cockroach.stderr.log](https://github.com/cockroachdb/cockroach/files/4171318/cockroach.stderr.log)

**Environment:**
 - CockroachDB version: master
 - Server OS: [e.g. Linux/Distrib]
 - Client app: cockroach sql

**Comment by RaduBerinde** [comment]
Heh, we actually saw this bug on Sentry and fixed it :) Closing as dup of #44659.
