### ISSUE TITLE
sql,kv: the pg error code (sqlstate) of "txn too large" error is not useful

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#44868]
Reported by customer: the error `transaction is too large to complete; try splitting into pieces` is currently reported as an internal error with code XX000.

This is not useful and also unnecessarily triggers sentry reporting. 

The correct SQLstate group is 54 - "Program Limit Exceeded" alongside `StatementTooComplex`. A new code needs to be introduced, presumably `54C01`.

**Comment by andreimatei** [comment]
note that we got rid of this error a while ago

**Comment by knz** [comment]
All right I did not know this. Thanks for noticing.
