### ISSUE TITLE
schema: alter table stuck at 0% and made no progress. 

### ISSUE THREAD

**Issue by roncrdb** [cockroachdb/cockroach#44869]
**Describe the problem**

recently a user had an issue where a schema change was showing no progress was being made.  Eventually, they canceled the and when they went to retry the schema change, they saw an error which read: 

`pq: duplicate: column "<NEW COLUMN>" in the middle of being added, not yet public`

The job now shows as cancelled, but it could still be stuck rolling back? 

I have added the debug zip, as well as the command they ran [here].(https://drive.google.com/drive/folders/1xBugbbqz6XlQkCYwSnlOBVZfpAKm_tzy?usp=sharing).

**Expected behavior**
Some visible progress should have been made, and currently, this has a user blocked since they aren't able to issue the schema change successfully. 

**Environment:**
 - CockroachDB Binary: CockroachDB CCL v19.2.2.1-1-gbde7d8835d (doesn't seem to be a standard binary) 
 - Server OS: [e.g. Linux/Distrib]
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**

**Comment by spaskob** [comment]
Ron, can you explain why are you assigning to me and what actions need to be taken? Maybe better to assign to the PM (Miachael) for triaging.

**Comment by roncrdb** [comment]
Looks like n44 was the original node that issued the schema change, I've attached some logs in files [here](https://drive.google.com/drive/folders/1xBugbbqz6XlQkCYwSnlOBVZfpAKm_tzy?usp=sharing).  It appears that the backfiller job started to run but was interrupted. Also, N44 has lots of `query execution canceled` errors right before seeing `waiting to update leases: aborted in distSender: context canceled` and there are also some stack trace errors on n44 right around the same time that n44 cancels the query that read `error with embedded safe details: key did not match descriptor`. 

N18 also had an aborded in distSender error around the same time as n44. not sure if the two are related.  There are three files in the link above of my observations.

**Comment by roncrdb** [comment]
@mwang1026, the user is blocked from running this schema change, is there anything else that is needed, or do we have enough to make some progress on this issue? Regarding the `error with embedded safe details: key did not match descriptor`, the user is aware of this error and doesn't think it's related to the schema change.  It be good to have an update or progress of them by EOD monday.

**Comment by jasobrown** [comment]
fwiw I'm looking into the `error with embedded safe details: key did not match descriptor` problem (related to #44158, but a new variant), and pretty sure it's unrelated to the main issue here. Unless, of course, the failure to perform range deletes somehow messed up the job executions, but that seems somewhat unlikely.

**Comment by lucy-zhang** [comment]
The table descriptor for `viewable` (id 82) has exactly one mutation, which would have been produced by the first ADD COLUMN attempt:
```
  14 {
    1 {
      1: "available_worldwide"
      2: 5
      3 {
        1: 0
        2: 0
        3: 0
        6: 0
        10: 16
      }
      4: 1
      5: "false"
      6: 0
    }
    3: 2
    4: 1
    5: 1
    7: 0
  }
```
`4: 1` indicates the mutation is in the `ADD` state and `7: 1` indicates this mutation isn't a rollback. So the schema change was never rolled back when the job was canceled, and the table descriptor seems to be stuck with a lingering mutation for adding a column. This explains the `duplicate: column ... in the middle of being added, not yet public` error.

It's not clear what actually happened when the job was canceled. We mark the job state as canceled in the jobs table immediately, but after that I think there are multiple ways the schema change execution can actually be canceled. It seems like we canceled a context somewhere:
```
E200205 20:50:22.873314 237701646 sql/distsql/server.go:564  [n44] query execution canceled
[...lots more of these...]
E200205 20:50:22.873517 237702041 sql/distsql/server.go:564  [n44] query execution canceled
W200205 20:50:22.873905 237690339 sql/schema_changer.go:952  [n44,client=100.77.73.16:30802,user=raphael_user,scExec] waiting to update leases: aborted in distSender: context canceled
W200205 20:50:22.873935 237690339 sql/schema_changer.go:979  [n44,client=100.77.73.16:30802,user=raphael_user,scExec] while reasing schema change lease: context canceled
W200205 20:50:22.873959 237690339 sql/exec_util.go:1134  [n44,client=100.77.73.16:30802,user=raphael_user] error executing schema change: communication error: rpc error: code = Canceled desc = context canceled
W200205 20:50:22.929877 237690339 sql/exec_util.go:1134  [n44,client=100.77.73.16:30802,user=raphael_user] error executing schema change: context canceled
```
We only get the `error executing schema change` logged error when `SchemaChanger.exec()` returns an error (note that this is in sql/exec_util.go, so we're in the synchronous path in the conn executor), which means we bypassed attempting to roll back the schema change, consistent with a total absence of anything in the logs indicating an attempted rollback. We do consider context cancellation to be a "retriable" error, but I also don't see any indication that any node in the cluster has ever attempted to run this schema change again, either in the synchronous path or the async SchemaChangeManager path.

It would be helpful to know if there's any attempted schema change activity happening. @jasobrown could you run `SELECT crdb_internal.set_vmodule('schema_changer=2,backfill=2')` on all nodes to increase log verbosity, and send us ~30 minutes' worth of logs? `SELECT crdb_internal.set_vmodule('')` resets the settings.

**Comment by jasobrown** [comment]
@lucy-zhang thanks for investigating.

I can add the verbosity flag, and get the logs updated within a few hours. I should point out that the job was canceled several days after the request to make the schema change was issued. So we were in a hung state wrt schema migration before I cancelled the job. 

Also, where do you get that table descriptor data for `viewable`? I tried grepping through the log zip i uploaded, but can't see that. 

Also, naively asking, is there a way to edit that table descriptor to cancel or rollback that failed schema change? Looking for a cheap way to unblock the user, if possible. Thanks!

**Comment by lucy-zhang** [comment]
> I should point out that the job was canceled several days after the request to make the schema change was issued. So we were in a hung state wrt schema migration before I cancelled the job.

Thanks, that's good to know.

> Also, where do you get that table descriptor data for `viewable`?

I got the table descriptor by decoding the protobuf-encoded contents of the row in `system.descriptor` (in the debug zip) with `protoc --decode_raw`. (Unfortunately doing it from the contents of debug.zip as of 19.2 is a somewhat manual process, but with access to the cluster, the most straightforward way to extract the raw bytes would be something like `select to_hex(descriptor) from system.descriptor where id=82` followed by decoding the hex string.)

> Also, naively asking, is there a way to edit that table descriptor to cancel or rollback that failed schema change?

We don't expose a way to do this. In rare cases we can replace the contents of the table descriptor if we can ensure that it's safe (in which case we'd send over a script to do it via SQL). That might end up being the best solution, but we'd first want to investigate further. The logs should help.

**Comment by jasobrown** [comment]
Ok cool. I'll get the logging going today. Also, user is ok with a replacement cluster to get unblocked, so we can work on this cluster without impacting their progress.

**Comment by roncrdb** [comment]
@lucy-zhang 

Original cluster is no longer available, can we find root cause with data we have?

**Comment by lucy-zhang** [comment]
These bugs with abandoned schema change mutations on table descriptors with no associated job and nothing running the schema change should no longer be possible in 20.1, with the new schema change jobs. I'm closing since I don't think there's more progress to be made here.
