### ISSUE TITLE
Aggregate functions section in docs populated with window funcitons

### ISSUE THREAD

**Issue by AEBilgrau** [cockroachdb/cockroach#44909]
The "aggregate functions" section is incorrectly populated in the stable (v19.2.2) documentation with "window functions". 

Compare:

https://www.cockroachlabs.com/docs/stable/functions-and-operators.html#aggregate-functions
https://www.cockroachlabs.com/docs/stable/functions-and-operators.html#window-functions

To the the expected as in earlier (v19.1) versions: 

https://www.cockroachlabs.com/docs/v19.1/functions-and-operators.html#aggregate-functions
https://www.cockroachlabs.com/docs/v19.1/functions-and-operators.html#window-functions

**Comment by jordanlewis** [comment]
This is resolved.
