### ISSUE TITLE
cli: default log directory to the first store directory

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#4492]
Rather than default the log directory to `os.TempDir` (i.e. `${TMPDIR}`) we could default it to a subdirectory of the first store directory (i.e. `./cockroach-data/logs`). This would make the logs slightly easier to access. Any concerns with doing this? Is `${TMPDIR}` preferable for some reason? One downside to `${TMPDIR}` is that logs tend to accumulate there without bound.

If there are no store directories we could fall back to using `${TMPDIR}` (e.g. for `./cockroach sql`).

**Comment by tschottdorf** [comment]
I think that makes some sense, though for a spinning disk it seems like that wouldn't be what you'd want. But then again, it's only default, and a convenient one at that.

**Comment by bdarnell** [comment]
SGTM
