### ISSUE TITLE
vec: distinct operator doesn't seem to work on decimals

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#44935]
```
create table t (x decimal);
insert into t values (1.0, 1.00);
select distinct x from t;
```
expect 1.0 or 1.00, but get both.

**Comment by yuzefovich** [comment]
The issue here is that we convert decimals to their string representation and then hashing those strings. I believe if we call `Decimal.Reduce` before converting to string, then this problem should be fixed. I'll open up a PR shortly.
