### ISSUE TITLE
storage/engine: rocksdb runs out of file descriptors

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#4493]
After running a cluster for a while and trying to print the keys using the command `./cockroach debug keys /tmp/data1`, I was presented with the following error:

```
Error: storage/engine/rocksdb.go:117: could not open rocksdb instance: IO error: /tmp/data1/000309.sst: Too many open files
```

The dump ran fine when I cleared the store, ran the cluster for less time, and ran the command again.

**Comment by bdarnell** [comment]
This isn't unique to this CLI command. RocksDB is running into the file descriptor limit, which is very low by default on OSX (256). There is a `max_open_files` option when opening the DB which will limit rocksdb to that number of descriptors. It defaults to `min(5000, current_limit)`, but it computes the current limit without leaving any room for other files in the process. I think we should either patch rocksdb to set its default max_open_files to say 80% of the hard limit or do this ourselves when opening the db. (we need a lot of network connections so we probably need to allow a wider margin than a typical rocksdb user)
