### ISSUE TITLE
workload:run in secure cluster

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#44938]
**Is your feature request related to a problem? Please describe.**
From the documentation, I cannot tell whether workload can be run against a secure cluster.

**Describe the solution you'd like**
Would be good to add option of running in secure cluster and update docs.

**Describe alternatives you've considered**

**Additional context**

**Comment by drewdeally** [comment]
example: cockroach workload init ycsb --initial-rows 10000000 'postgres://user:pass@gcp-us-east1.lucky-luwak-gcp.crdb.io:26257/ycsb?sslmode=verify-full&sslrootcert=lucky-luwak-gcp-ca-3.crt'
