### ISSUE TITLE
backup,import: primary key changes will break backup/restore/import row counts

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#44998]
The very [low-level row counter](https://github.com/cockroachdb/cockroach/blob/master/c-deps/libroach/row_counter.cc#L108) used in in the KV commands used by BACKUP, RESTORE and IMPORT counts "rows" processed as it iterates KVs, and the way it distinguishes rows from index entries is currently by extracting the index ID and comparing it to `1`, assuming that PK index ID is always 1. However after PK changes this assumption will be incorrect.

NB: there is also a go version of it used in pebble-based BACKUP and in IMPORT: https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/engine/row_counter.go#L65

**Comment by rohany** [comment]
I think these could be changed to something like this:

Remember the first index id that the counter sees. Then, increment the row counter whenever the index id scanned equals that one.

Regarding interleaved tables, we might be able to do something where we remember all the table ID's seen and try to skip as far in the key as we can to get to the actual table that the key belongs to.

**Comment by rohany** [comment]
Nah, this won't work. It seems like imports etc already separate ssts by primary index and secondary indexes.
