### ISSUE TITLE
ui, sql: statement page mean latency can be negative

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#45011]
There's a joke in here about time travel queries but I haven't had enough coffee to figure out how to make it.

@timveil pointed out that there are situations where the statements page can display negative timings for specific fingerprints. See:

![image](https://user-images.githubusercontent.com/21692034/74349161-d0f41b00-4d81-11ea-8429-56449bdc1c6a.png)

Will grab reproduction steps from Tim when possible.

**Comment by awoods187** [comment]
Is this a problem with the info passed to the webui or the presenting of that info?

**Comment by piyush-singh** [comment]
almost certainly the former, I think this is largely on the SQL side. I don't think we do any sort of calculations when display metrics, we just pull them straight from whatever is stored in memory.

**Comment by awoods187** [comment]
@rohany could you take a look here since you've been there recently?

**Comment by rohany** [comment]
I can take a look once there are some reproduction steps -- i haven't seen anything recently plumbing around that would directly point to this.

**Comment by nvanbenschoten** [comment]
This seems to have gotten a lot worse recently, which may be related in some way to https://github.com/cockroachdb/cockroach/issues/53827. This time, it looks more like an arithmetic overflow than arithmetic error.

<img width="1670" alt="Screen Shot 2020-09-07 at 11 45 27 PM" src="https://user-images.githubusercontent.com/5438456/92430946-38c9e300-f164-11ea-80e1-e2d2a253afde.png">

<img width="1692" alt="Screen Shot 2020-09-07 at 11 46 39 PM" src="https://user-images.githubusercontent.com/5438456/92431019-67e05480-f164-11ea-9f3e-f29e52993ca9.png">

I've seen this on the last couple clusters I've run, so it doesn't just seem like a one-time fluke. I'm going to mark this as a release blocker for the time being.

**Comment by nvanbenschoten** [comment]
FWIW, I do not see the issue when running 1be638cdc8d92ad3a993a935e92392b45a499cac.

**Comment by awoods187** [comment]
@solongordon can you take a look here?

**Comment by dhartunian** [comment]
I was able to repro this on a single-node running tpcc workload. And have confirmed that the backend payloads contain the large numbers (since we do quite a bit of rounding and munging of numbers in the FE)

![Screen Shot 2020-09-08 at 3 42 31 PM](https://user-images.githubusercontent.com/986307/92520663-f9de7080-f1e9-11ea-9d4a-4a11ec7f4dbc.png)

**Comment by solongordon** [comment]
If this got worse recently I strongly suspect it's related to #53846. I'll have a look.

**Comment by nvanbenschoten** [comment]
I can confirm that 1225fe88e6e3b398657356aa4cf240a4fe9167bd fixed the issue on a test cluster I've been looking at.
