### ISSUE TITLE
jobs: update debug.zip to contain jobs table, table descriptors in their physical byte representation

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#45019]
**Is your feature request related to a problem? Please describe.**
Today, information is lost / un-parsable when the jobs table and table descriptors are converted to strings and sent in the debug.zip file. This makes triage of jobs issue much, much harder.

**Describe the solution you'd like**
Instead of dumping strings, include the jobs table and table descriptors in their physical byte representation in debug.zip

**Comment by piyush-singh** [comment]
@knz do debug.zip enhancements fall under the CLI? If not, do you have a sense of who would own this?

**Comment by knz** [comment]
yes it does and I have already made a proposal to change this.

@mwang1026 supposing that we have a spectrum of solutions with alternatives A, B, C. Who is the design partner that can help us evaluate which of the alternatives to adopt?

**Comment by mwang1026** [comment]
My vote is @dt and he can delegate as needed

**Comment by knz** [comment]
ok @dt concrete question: if all the ZIP tables were exported using the hex format, would that be OK?

**Comment by dt** [comment]
hex format _for the bytes fields_ or, like, just a big hex blob of the whole thing?

**Comment by knz** [comment]
my preference would be to operate as follows:

1) for back-compat with existing versions, have the SQL query ran by `cockroach debug zip` do `to_hex()` or `::string` with `bytea_escape=hex`.

2) introduce a new "export" variant in 20.1 (or perhaps later) that exposes the raw k/v bytes. Make `cockroach debug zip` use that

3) concurrently with 2, provide a tool for our support engs (and ourselves) to import data exported with #2 into a blank cluster/table for further investigation.

**Comment by knz** [comment]
Progress has been made on this via #45721 thanks to Spas.
