### ISSUE TITLE
jobs, adminui: expose the node that's coordinating the job and last updated timestamp on the jobs page in the UI

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#45017]
**Is your feature request related to a problem? Please describe.**
For running jobs, it's hard to know if the job is stuck and where to go to check for that. By exposing the "last updated" timestamp in the UI, we let users know the last time the status and/or progress was updated and they can either have confidence it's making progress or monitor if it's stuck. Furthermore, exposing the coordinating node can give users a clue whether something is up. For example, if the jobs page says "node 3" is the coordinator and node3 is down, that's an indicator that something may be wrong / may be waiting for the coordinator to be reshuffled.

**Describe the solution you'd like**
Add two new fields to the Jobs UI where we display the "modified" timestamp and the "coordinator_id" data for each job. We can decide how we want to educate users how to use that information.

Both of these fields are already available in the SHOW JOBS command https://www.cockroachlabs.com/docs/stable/show-jobs.html

Jira issue: CRDB-5181

**Comment by Annebirzin** [comment]
@piyush-singh I've updated the jobs list and job detail page designs to add references to coordinating node and last updated timestamp. Let me know any thoughts

- [Jobs list](https://www.figma.com/file/c6BNEn0mY6iHG1t5NhoH3E/obsrv_admin-ui-jobs?node-id=1136%3A968)
- [Job detail page](https://www.figma.com/file/c6BNEn0mY6iHG1t5NhoH3E/obsrv_admin-ui-jobs?node-id=1136%3A2393)

**Comment by dhartunian** [comment]
I'll follow up in here regarding the 2 new fields. Need to reconcile what's currently being fetched via the admin jobs endpoint and the new one that's been added.

**Comment by piyush-singh** [comment]
cc @spaskob
