### ISSUE TITLE
jobs: update RunningStatus often and any time when waiting

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#45023]
**Is your feature request related to a problem? Please describe.**
This is a placeholder issue for now since we'll want to expand this once for each job. Users often have little insight into whether their job is running successfully, stalled, or waiting on some other process or resource. Ensuring that our jobs have easy to understand, representative, and MECE (mutually exclusive collectively exhaustive) statuses that we can then surface to the users will both increase confidence in our jobs framework and allow for easier debugability.

**Describe the solution you'd like**
Go through each job and make sure to add any relevant statuses and ensure they're logged to RunningStatus 

Jira issue: CRDB-5178

**Comment by spaskob** [comment]
Assigning myself to implement that for IMPORT and triage to other folks later. Anyone else feel free to help if you'd like to.

**Comment by livlobo** [comment]
Part of 22.2 Jobs observability work.
