### ISSUE TITLE
server: /health endpoint should not do authenticatication

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#45020]
Since recently, the `/health` endpoint [requires authentication](https://github.com/cockroachdb/cockroach/blob/1d76206f6b2cf18dfd7a7722cf223dfdf2d7e6ac/pkg/server/status.go#L626). That's bad because we want an unauthenticated kubernetes prober, for example, to just work (and it does seem to work for a reason I don't understand: #45018).
It's also bad because we need to keep the latency of this endpoint very predicable, and authentication generally needs to perform some queries.

**Comment by knz** [comment]
FWIW: We currently have the following:

- `/_status/details/<node>`  and goes to the `Details()` RPC. It's privileged. It also uses a KV request and thus can hang if the cluster is slow. 
- `/_admin/v1/health` goes to the `Health()` RPC. It's not privileged and explicitly opted out of authentication. Only uses in-RAM data and thus not subject to cluster load. 
- `/health` is a redirect to `/_status/details/<node>`.

The last point explains #44832. I also believe it's a mistake and it should redirect to the other thing instead. I'll issue a PR. cc @DuskEagle
