### ISSUE TITLE
Anonymized feature tracking for access logging

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#45028]
Please add anonymized usage tracking for our access logging functionality (#41378). This will help the Product team answer questions like “What % of clusters are tracking authentication events?” and improve feature usability and documentation.

Please add events for:
- [ ] conn logging  -> counters `auditing.connection.enabled` (when enabled) / `auditing.connection.disabled` (when not enabled)
- [ ] auth logging : -> counters `auditing.authentication.enabled` (when enabled) / `auditing.authentication.disabled` (when not enabled)

**Comment by knz** [comment]
Discussed with @nstewart : crdb does not yet know how to track in telemetry when a cluster setting is changed from one value to another.

Instead this feature will track the number of connections with logging either enabled or disabled.
