### ISSUE TITLE
storage: data that has met GC threshold should no longer be accessible 

### ISSUE THREAD

**Issue by roncrdb** [cockroachdb/cockroach#45037]
**Describe the problem**

Currently, if data has met the GC threshold, you can still access it until Garbage Collection actually happens, which, based on the amount of data that needs to be GC'd can be seconds, hours or even days. This can cause issues where users may wonder why some data that was accessible 5 minutes ago is no longer accessible even if they were aware that their GC.TTL window for this data had been met. 

@ajwerner proposes that we make any data that has met the gc.threshold inaccessible to users. This would effectively enforce the GC.TTL strictly.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4648](https://cockroachdb.zendesk.com/agent/tickets/4648) has been linked to this issue.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4930](https://cockroachdb.zendesk.com/agent/tickets/4930) has been linked to this issue.

**Comment by ajwerner** [comment]
Closed by #45826.
