### ISSUE TITLE
util/log: only print stack of running goroutine in log.Fatal

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#4506]
Go1.6 changed the default behavior of an uncaught `panic` such that only the stack trace of the panicing goroutine is output. See https://blog.golang.org/go1.6. We should consider a similar change for `log.Fatal`. Printing all of the goroutine stack traces can be overwhelming.

**Comment by bdarnell** [comment]
Conversely, we should probably set `GOTRACEBACK=all` in circleci; it's difficult to debug test timeouts if the only stack trace that is shown is the test monitor thread.
