### ISSUE TITLE
ui: make the node map visible to non-admin users

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/cockroach#45089]
A customer fielded a limitation on v19.2.3 where the node map on an enterprise cluster does not load.

the error that was reported was `internal server error` and the logs show `E200213 17:30:56.348929 11803 server/admin.go:1331 admin-locations: user U750901 does not have SELECT privilege on relation locations`.

the workaround is to `grant select on table system.locations to <sql_user>;`.

you can also grant the admin-role to the user using RBAC.

I believe the restriction we've introduced was unintentional and personally I think the node map should make an rpc call as the root user regardless if a sql user has any permissions. 

cc @knz

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4707](https://cockroachdb.zendesk.com/agent/tickets/4707) has been linked to this issue.

**Comment by knz** [comment]
cc @dhartunian for triage. We can look at solving this together if you're not sure.

**Comment by knz** [comment]
@piyush-singh @DuskEagle I'd like to make access to system.locations subject to an operator privilege. What do you think?
(Random users have no business knowing exactly at which geographical location their servers are hosted.)

**Comment by DuskEagle** [comment]
I don't agree with this. When running in a public cloud, most users are going to know which region(s) their cluster is running in. If you know that, the system.locations table isn't going to give you any additional info.

The system.locations table isn't even populated by default in CockroachDB. On Cockroach Cloud, we populate the table automatically, but the longitude and latitude values [are public information](https://www.cockroachlabs.com/docs/stable/enable-node-map.html#location-coordinates-for-reference).

Even when running in private datacenters, if you really wanted to obscure the location of your "regions", I don't see why you would populate the system.locations table in the first place, or why you would use more digits of precision in the latitude and longitude than you're comfortable with.
