### ISSUE TITLE
storage: node liveness is not checking disk health

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#45091]
It's trying to, there's code to perform a no-op write and flush it to disk, but when NewNodeLiveness is called in server start, it's handed `s.engines` before `s.engines` is initialized.

https://github.com/cockroachdb/cockroach/blob/03021d396b98e1ddb09056cae2dce0274d6a367e/pkg/storage/node_liveness.go#L792-L800

NewNodeLiveness is called with `s.engines` in `NewServer`

https://github.com/cockroachdb/cockroach/blob/03021d396b98e1ddb09056cae2dce0274d6a367e/pkg/server/server.go#L359-L369

But `s.engines` is set in `Server.Start`, which is called on the return value of `NewServer`

https://github.com/cockroachdb/cockroach/blob/03021d396b98e1ddb09056cae2dce0274d6a367e/pkg/server/server.go#L1333

**Comment by danhhz** [comment]
@nvanbenschoten for triage

**Comment by nvanbenschoten** [comment]
@tbg this is fixed by 5bc45a1ba1b7e09b73ddb64e669d6794b53132c0, right? If so, want to do the honors of closing this?

**Comment by tbg** [comment]
Yep!
