### ISSUE TITLE
Anonymized feature tracking for session cancelation

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#45103]
Please add anonymized usage tracking for our basic session cancelation functionality. This will help the Product team track the adoption of the second of two commands required to expire user accounts, an important use case for our enterprise customers (#41396). This will ultimately help us improve feature usability and documentation.

- [ ] CANCEL SESSION -> `sql.session.cancel_one`
- [ ] CANCEL SESSIONS -> `sql.session.cancel_query`

**Comment by jordanlewis** [comment]
@nstewart I don't understand - what's `cancel_one` mean? Maybe we just want `cancel_session` and `cancel_sessions`?

**Comment by nstewart** [comment]
I'm indifferent -- I used `cancel_query` because our docs us a select statement as input to CANCEL_SESSIONS

![image](https://user-images.githubusercontent.com/894257/75733983-bb10b080-5cc4-11ea-9126-10d3313069db.png)

I'm fine with `cancel_session` and `cancel_sessions`

I also noticed I had SESSIONS with cancel_one and SESSION with cancel_query, I fixed that in the original issue
