### ISSUE TITLE
Non-blocking import statement option

### ISSUE THREAD

**Issue by chriscasano** [cockroachdb/cockroach#45116]
**Is your feature request related to a problem? Please describe.**
This is an improvement for how we can allow multiple imports to occur.  Today each import statement is blocking in that you have to wait until the import to succeed or fail before moving to the next step in your script.  Therefore when running multiple imports, you have to run each of them in serial (one at a time).  

**Describe the solution you'd like**
Adding an option to run the Import statements asynchronous or in the background would be the option to run multiple imports.  For example, adding `--background` as an option so that the import SQL statement returns a job id and the import job runs in the background so that you can proceed to the next step in your script.

**Describe alternatives you've considered**
The alternatives to this is running multi-threading in a script to a run multiple import simultaneously.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4711](https://cockroachdb.zendesk.com/agent/tickets/4711) has been linked to this issue.

**Comment by BramGruneir** [comment]
Assigning to @mwang1026 for triage.

This seems to break normal blocking behaviour, but it does create a job which can be used for tracking.

**Comment by mwang1026** [comment]
Want to push on this a bit--what's stopping people from multi-threading scripts, like you described? Aside from the minor annoyance. Want to get a sense of whether this is "can't perform the task" or "it's annoying to do and this would make it easier" in impact

**Comment by mwang1026** [comment]
Closing this for now since it's not super urgent since there is a viable workaround -- start a new connection for each import.
