### ISSUE TITLE
Got NET::ERR_CERT_REVOKED on Chrome Browser

### ISSUE THREAD

**Issue by Olipicus** [cockroachdb/cockroach#45132]
I try to set up cockroach on my MacBook
I just follow by this doc https://www.cockroachlabs.com/docs/stable/secure-a-cluster.html
every step work fine but after I start the cluster and i try to access the web UI with chrome browser,
I got "NET::ERR_CERT_REVOKED" 

<img width="716" alt="Screen Shot 2563-02-15 at 12 52 22" src="https://user-images.githubusercontent.com/311452/74582744-28002700-4ff2-11ea-950e-c16108ef10b3.png">

**Comment by jordanlewis** [comment]
@kenliu can you route this please? Thanks!

**Comment by jordanlewis** [comment]
Closing due to age. @Olipicus if you still see this, feel free to re-open.
