### ISSUE TITLE
colexec: add a slice of Closers to vectorized flow during planning

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#45148]
This allows us to register any components that need to be closed with the flow to be able to close them on `Cleanup`, rather than hoping that they will be closed by downstream components, which has been proven brittle and doesn't work in the case when a limit is hit.

**Comment by yuzefovich** [comment]
I guess this is one of the solutions to what a problem described in #44652.

**Comment by asubiotto** [comment]
Oops, forgot that was open. We probably need to do this soon. Will add this as a comment to that.
