### ISSUE TITLE
cli: `cockroach debug zip` should use a streaming format, not zip

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#45145]
If `cockroach debug zip` is interrupted for any reason (eg Ctrl+C, out-of-memory, whatever), the output file is invalid and cannot be opened -- even if the command had already been able to retrieve useful data from the cluster.

This is becauze the Zip format can only be opened successfully when the file index is available, and that index is only included at the end. If the process terminates early, the index is not written and the file cannot be opened.

The problem would not exist if `cockroach debug zip` was creating a tar archive or any other format that is stream-oriented.

**Comment by petermattis** [comment]
Switching the format will be a bit of a lift. I wonder if we can improve the behavior in scenarios such as ctrl-C by interrupting whatever the stuck operation is and properly closing the zip file. Is that worthwhile, or are there common scenarios such as out-of-memory where recovery isn't possible?

**Comment by petermattis** [comment]
Let me clarify that switching the output format is likely not terribly difficult, but changing all of the documentation would be.

**Comment by petermattis** [comment]
An alternative to switching the format: add a flag to output the `debug` contents to a directory on disk. I think this should be very easy to do and something that could be backported. @knz what do you think?

**Comment by knz** [comment]
Yes this is a very good idea.

**Comment by knz** [comment]
(if we introduce opt-in flags, then offering an alternative to zip, e.g. tar, becomes possible too.)

**Comment by petermattis** [comment]
> (if we introduce opt-in flags, then offering an alternative to zip, e.g. tar, becomes possible too.)

Agreed, though mildly confusing to have `debug zip --tar`.

**Comment by knz** [comment]
`debug zip --not-really-zip-instead-write-files-to-directory` is just as confusing IMHO.

**Comment by irfansharif** [comment]
Seeing this issue crop up out in the wild. 

```
warning: buffering more than 10000 result rows in client - RAM usage growing, consider another formatter instead
debug/crdb_internal.jobs.txt
warning: buffering more than 10000 result rows in client - RAM usage growing, consider another formatter instead
fatal error: runtime: out of memory
```

Made it a bit difficult to make progress save for tediously constructing the debug zip by hand (like [so](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/433291265/Collecting%2Ba%2Bdebug%2Bzip%2Bmanually)).

**Comment by jordanlewis** [comment]
Oh, that warning is a clue - I bet it would just get immediately better if we stopped using the pretty-printing output writer that we use in the CLI. That has to buffer all output in memory to find the width of each row...

**Comment by jordanlewis** [comment]
@irfansharif do you still have this unhappy cluster? You could try the following diff

```
diff --git a/pkg/cli/zip.go b/pkg/cli/zip.go
index ca585cc26c..a53fdd7c2f 100644
--- a/pkg/cli/zip.go
+++ b/pkg/cli/zip.go
@@ -652,6 +652,7 @@ func dumpTableDataForZip(

        fmt.Printf("retrieving SQL data for %s... ", table)
        var buf bytes.Buffer
+       cliCtx.tableDisplayFormat = tableDisplayCSV
        err := runQueryAndFormatResults(conn, &buf, makeQuery(query))
        if err != nil {
                return z.createError(name, err)
```

**Comment by knz** [comment]
Woah nice find irfan

**Comment by knz** [comment]
(@irfansharif that being said, it really takes a _lot_ of rows (or very wide rows) to get the client to crash in that way. That particular cluster has a serious problem.)

**Comment by knz** [comment]
I have revisited this issue experimentally and found that a truncated zip archive can still be extracted with the `unzip` utility. So the issue here is not really an issue :)

But the OOM problem is still significant - fixing that separately via #47594
