### ISSUE TITLE
build crashes with: Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by tclass** [cockroachdb/cockroach#45146]
**Describe the problem**

```Undefined symbols for architecture x86_64:
  "rocksdb::NewLRUCache(unsigned long, int, bool, double, std::__1::shared_ptr<rocksdb::MemoryAllocator>, bool)", referenced from:
      _DBNewCache in libroach.a(cache.cc.o)
  "rocksdb::NewBloomFilterPolicy(int, bool)", referenced from:
      cockroach::DBMakeOptions(DBOptions) in libroach.a(options.cc.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [cockroachshort] Error 2
```

**To Reproduce**

`make build`

**Environment:**
 - CockroachDB git commit - 1674c8aa4d955738365087d33ff707525e8a2b94
 - Mac OSX Catalina (10.15)

**Additional context**
What was the impact?
build crashes
- https://github.com/cockroachdb/cockroach/issues/200 this seems to be the same or similar problem but I try to deinstall lz4 and others, but it didn't work

**Comment by jordanlewis** [comment]
RocksDB has been removed, so closing this.
