### ISSUE TITLE
sql: (temporary) Hang when dropping unique index created after ALTER PRIMARY KEY

### ISSUE THREAD

**Issue by andy-kimball** [cockroachdb/cockroach#45150]
Run the following SQL script:
```
SET experimental_enable_primary_key_changes = true;
CREATE TABLE tdup (x INT PRIMARY KEY, y INT NOT NULL, z INT NOT NULL);
INSERT INTO tdup VALUES (1, 1, 1);
ALTER TABLE tdup ALTER PRIMARY KEY USING COLUMNS (y, z);
DROP INDEX tdup_x_key CASCADE;
```
EXPECTED: This should switch the primary key to columns (y, z) and drop the unique index synthesized by the ALTER PRIMARY KEY code.

ACTUAL: The DROP INDEX statement hangs.

NOTE: This happens with and without the https://github.com/cockroachdb/cockroach/pull/45093 fix.

**Comment by andy-kimball** [comment]
Hm, it looks like after > 1 minute, it did complete. Is that expected?

**Comment by rohany** [comment]
Yes, this is expected. The current job framework is unable to spawn child jobs from a given job. To get around this, the primary key change process lets the async schema changer pick up and run the drop index jobs. The interval for these schema changers is 1 min +- some jitter, so this seems like it's working as expected. 

Lucy and I have been thinking about how to get around this blemish though.

**Comment by jordanlewis** [comment]
When @otan's NOTICE feature gets in, let's add a NOTICE that says the schema change will take a minute to kick off as a mitigation if we can't fix the issue completely.

**Comment by lucy-zhang** [comment]
https://github.com/cockroachdb/cockroach/pull/47624 implements what I described above.

**Comment by lucy-zhang** [comment]
#47624 improves the situation, but I think to really consider this problem solved, we should
1. wait to return results to the client until dropping the indexes is completed, to make the user experience more predictable; and
2. reduce the amount of redundant waiting we do for schema change jobs (https://github.com/cockroachdb/cockroach/issues/47790 covers this).

**Comment by spaskob** [comment]
I just merged https://github.com/cockroachdb/cockroach/pull/48608 which may further improve the performance for this case.

**Comment by ajwerner** [comment]
This all happens quite quickly now. I'm closing this.
