### ISSUE TITLE
Optimization for where IN (=ANY) clause with empty array

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/cockroach#45168]
**What is your situation?**

organization and id are strings, and ampuuid is a uuid. Organization is low cardinality.
We had a query with two "in" clauses: 

```
...where organization = x and (id = ANY(ARRAY[...] or ampuuid = ANY(ARRAY[...])
```

There's an index on `organization_ampuuid`, and of course on `id`. So, splitting that two clause query into two one clauses queries:

this one `...where organization = x and id = ANY(ARRAY[...])` uses the primary index, and then filters on organization, as expected.

This one `...where organization = x and ampuuid = ANY(ARRAY[...])` uses organization_ampuuid as expected. 

However, the original query with both arrays `...where organization = x and (id = ANY(ARRAY[...]) or ampuuid = ANY(ARRAY[...]))` only uses the index on organization, and then filters each row on both the list of ids and the list of ampuuids, which considering the cardinality of organization compared to the other items, is basically a table scan. It does not use both indexes for the same query- and actually doesn't use either and also does notice when one of the arrays is empty (as will be the typical case) to fall back to a preferable single clause approach.

Also noteworthy is that for small array sizes, the id lookup does not use the primary index, it uses the organization index and then filters on id, which seems backwards to me, considering id is unique, and organization is not. So in the end, I split the two clause query into two one clause queries, and hinted the primary index on the id array lookup.

Select all that apply:
- There is a difference between the performance you expect and the performance you observe.

**Observed performance**
https://drive.google.com/drive/folders/1qNb3RnRdPtSgsd0n68XkEPeyRwlk92CG?usp=sharing
This link contains the following files: 
EXPLAIN_OPT_ENV_VERBOSE.sql
node_stats.json
EXPLAIN_ANALYZE.sql
simple_scenario.sql

**Requested resolution**

When/how would you consider this issue resolved? 
- I want CockroachDB to be optimized for my use case.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4697](https://cockroachdb.zendesk.com/agent/tickets/4697) has been linked to this issue.

**Comment by RaduBerinde** [comment]
This is #2142 - we'd want to use two indexes and union the results. We will try to prioritize this work.

> when one of the arrays is empty (as will be the typical case) to fall back to a preferable single clause approach.

This seems like a different issue that we could easily fix, do you have a concrete example just to make sure I understand correctly? (please post the `EXPLAIN (OPT, ENV)` for it if you can).

> Also noteworthy is that for small array sizes, the id lookup does not use the primary index, it uses the organization index and then filters on id, which seems backwards to me, considering id is unique, and organization is not. 

Interesting, I don't think this should happen.. Is this what `simple_scenario.sql` is showing? In that example there are three `id`s and three `org`s, so actually this plan makes more sense (we scan 1 row instead of three). Can you reproduce with the original tables and statistics? If so, please post the `EXPLAIN (OPT, ENV)`.

**Comment by RaduBerinde** [comment]
> > when one of the arrays is empty (as will be the typical case) to fall back to a preferable single clause approach.

> This seems like a different issue that we could easily fix, do you have a concrete example just to make sure I understand correctly? (please post the EXPLAIN (OPT, ENV) for it if you can).

Actually, I can reproduce that quite easily, it should be a simple fix.
