### ISSUE TITLE
Out-of-order key insertion when creating databases in parallel

### ISSUE THREAD

**Issue by hendrikhofstadt** [cockroachdb/cockroach#45162]
**Describe the problem**

When creating many new databases and tables in parallel, the database deadlocks and somtimes dies with.

```
*
* ERROR: [n1,s1,r11/1:/Table/1{5-6}] Reported as error f1f431925b284bf3a8e96021816eff2e
*
F200218 11:00:38.805507 388 storage/store.go:3695  [n1,s1,r11/1:/Table/1{5-6}] while committing batch: while committing batch: Corruption: Out-of-order key insertion into table
goroutine 388 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc0000c5b00, 0xc0000c5b00, 0x53e1000, 0x10)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1020 +0xd4
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x5b6bb60, 0xc000000004, 0x53e10ad, 0x10, 0xe6f, 0xc00f634380, 0x7d)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:876 +0x965
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x3a4f280, 0xc015e66330, 0x4, 0x2, 0x32c9822, 0x6, 0xc014ccbeb0, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:85 +0x2d8
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x3a4f280, 0xc015e66330, 0x1, 0x4, 0x32c9822, 0x6, 0xc014ccbeb0, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:71 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x3a4f280, 0xc015e66330, 0x32c9822, 0x6, 0xc014ccbeb0, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:182 +0x7e
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc000dd0000, 0x3a4f280, 0xc015e66330, 0xb)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3695 +0x4f4
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc000dd6e80, 0x3a4f280, 0xc000c9a030)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:214 +0x258
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x3a4f280, 0xc000c9a030)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:165 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc0002c6250, 0xc0004f8120, 0xc0002c6240)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:200 +0xe1
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:193 +0xa8
```

**To Reproduce**

In our production payload we create a lot of databases and tables for tests.

To reproduce:

I'm running 12 threads and constantly creating databases on each of them. After creating the database I create a couple of simple tables.

The crash does not happen every time / does not reproduce reliably. Sometimes the database also deadlocks before crashing (rejecting all commits).
It's more likely to trigger if the CPU utilization is high.

**Environment:**
 - CockroachDB version: CCL v19.1.5 @ 2019/09/23 14:12:16 (go1.11.6)
 - Server OS: Fedora 31 / Podman container
 - Client app: PQ

**Comment by petermattis** [comment]
Hi @hendrikhofstadt. Thank you for the report! This assertion is capturing an impossible-this-should-never-happen condition inside RocksDB. We have anecdotal evidence this happened to a user before we added the assertion, but were never able to produce the assertion. That you've produced it is very exciting. It sounds like you've even reproduced it, which is even more exciting.

I'd be very interested in the reproduction details. Any code for reproduction that you can provide which be much appreciated.

**Comment by petermattis** [comment]
@hendrikhofstadt Did you want us to investigate further? We'll need more info in order to do so.

**Comment by hendrikhofstadt** [comment]
@petermattis The issue hasn't reappeared in the last couple of weeks, it might have been. If it happens again, I'll reopen this issue and try to publish some reproduction code.

Thanks a lot!
