### ISSUE TITLE
storage: TestLockTableConcurrentRequests fails race detector

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#45164]
```
=== RUN   TestLockTableConcurrentRequests/concurrency_2
race: limit on 8128 simultaneously alive goroutines is exceeded, dying
FAIL	github.com/cockroachdb/cockroach/pkg/storage/concurrency	1959.345s

```

Seen here: https://teamcity.cockroachdb.com//viewLog.html?buildId=1753379&buildTypeId=Cockroach_Nightlies_WorkloadNightly

**Comment by sumeerbhola** [comment]
The current structure of the randomized test allows for this possibility if a transaction stays open for a long time and holds locks that causes other transactions requests to wait. But given that is has only 8 active transactions and with 0.25 probability each request commits one of the existing transactions and starts a new one it seems very unlikely. And an instrumented version of this test running on my laptop does not exceed more than 100 active requests (each request uses a goroutine). I even tried with `-race`.
I wonder whether I am missing something about how these nightly tests are run -- do many tests get run in parallel and this goroutine limit is applied in aggregate to those parallel tests?

**Comment by tbg** [comment]
The run this is part of is essentially `make stressrace`, which means go
will have some (originally ~numcpus but I believe we've since restricted it
to something like 2 or 4) packages running at any given moment (some of
which are super heavyweight, like logictest which runs tons of clusters in
parallel). The bottom line is that you should imagine running this on a
severely overloaded machine. The goroutine limit is not applied across
these packages though.
