### ISSUE TITLE
sql: 20.1 telemetry master list

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#45210]
**AppDev**

- [ ] Drivers
- [ ] ORMS
- [ ] GUIs
- [ ] Frameworks

**SQL Vectorized**

- [x] Vectorized turned on/off cluster setting 
- [ ] Query execution time

**SQL Features**

- [ ] Session Cancelation https://github.com/cockroachdb/cockroach/issues/45103
- [x] Access logging https://github.com/cockroachdb/cockroach/issues/45028
- [x] Audit Logging https://github.com/cockroachdb/cockroach/issues/45027
- [x] RBAC https://github.com/cockroachdb/cockroach/issues/45022
- [ ] Computed column
- [ ] Partitioning 
- [ ] Zone configs 
- [ ] Number of indexes used per query
- [ ] Columns per query
- [x] ORDER BY
- [x] DISTINCT
- [x] INTERLEAVE
- [x] Window functions
- [x] Show queries
- [ ] Cancel
- [ ] Rows scanned
- [ ] Results per Query
- [ ] Capture row size
- [ ] Amount of work
- [ ] Hash sharded indexes

 

**SQL Planning**

- [x] Foreign Keys https://github.com/cockroachdb/cockroach/issues/43765
- [x] Index hint https://github.com/cockroachdb/cockroach/issues/43794
- [ ] Outer join
- [ ] Self-join
- [ ] Cross join
- [ ] Latency (zone config) used in planning by CBO
- [ ] Loop (unimplemented) 
- [ ] Soft Limits 

**SQL Schema**

- [x] SHOW CONSTRAINTS
- [ ] Inverted index 
- [x] SHOW INDEXES
- [ ] Time to complete schema change
- [ ] Age of table at time of change
- [ ] Canceled schema changes job
- [x] Show jobs
- [ ] Schema changes length (by schema change type)
- [ ] Column type changes (old type and new type)
- [ ] Schema changes in explicit transactions
- [ ] Size of Schema Change
- [ ] Ratio (Size/Time) of Schema Change
- [ ] Number of change in txn
- [x] JDBC streaming https://github.com/cockroachdb/cockroach/issues/43763

**Questions:**
Is ADD CONSTRAINT foo UNIQUE covered in ADD CONSTRAINT? Should it be separated? 
Is CREATE UNIQUE INDEX covered in CREATE INDEX? Should it be separated? 
Is DROP INDEX foo CASCADE covered in DROP INDEX? Should it be separated?

**Comment by yuzefovich** [comment]
I'm looking at adding telemetry for `DISTINCT`, and it seems to me it's already in place (under `sql.plan.opt.node.distinct-on` feature name). Are we interested in distinct aggregation here? cc @awoods187

**Comment by jordanlewis** [comment]
@awoods187, please look at this and close/open a new one for 20.2 carryover items.
