### ISSUE TITLE
jobs: easy way to generate long-running jobs for testing

### ISSUE THREAD

**Issue by dhartunian** [cockroachdb/cockroach#45218]
When testing new functionality related to jobs, it would be useful to have a way to easily trigger a long-running job that could either complete, fail, etc. for demonstration purposes.

**Describe the solution you'd like**
A CLI command that triggers a sample job ideally with some timespan it should take to complete.

**Describe alternatives you've considered**
This could be done using imports but it's cumbersome to generate giant files and difficult to control the timing.

**Additional context**
This should probably be hidden from general users since we wouldn't want it to be confused with "real" jobs.

**Comment by spaskob** [comment]
cc-ing @pbardea @dt
