### ISSUE TITLE
sql/kv: use duplicate index pattern for system tables

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#45225]
We recently discussed making system tables follow the duplicate index pattern by default. This would ensure that multi-region users receive fast reads from these tables which is a frequent access pattern. Although this would increase write performance, these tables are not frequently updated. 

cc @solongordon @danhhz

**Comment by rafiss** [comment]
This should now be done using the newer multiregion semantics -- https://github.com/cockroachdb/cockroach/issues/63365 is about making system tables GLOBAL, and replaces this issue.
