### ISSUE TITLE
ui: indicate network latencies page measure RTT

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#45221]
The network latency matrix page and tooltips are currently ambiguous about whether the listed times are one way or round trip times. We should make this clearer on the page or at the very least on hover in the tooltips.

Thank you to @irfansharif for pointing this out. cc @Annebirzin

**Comment by Annebirzin** [comment]
@piyush-singh as discussed, we can add the phrase 'roundtrip' to the tooltips to make this more clear.  Screenshot below and full designs are here: zpl.io/2Z7yq6L

![Screen Shot 2020-02-19 at 4 07 37 PM](https://user-images.githubusercontent.com/51920721/74876682-18eee100-5332-11ea-9fe1-69406a7aa442.png)
