### ISSUE TITLE
sql: add VOID type

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#45234]
Postgres has `void` type, and we don't. For example, `pg_sleep` and some of the `pg_advisory_...` builtins have it as the return type. We should add it to our type system for compatibility.

Epic: CRDB-11419

**Comment by rohany** [comment]
maybe bringing in @otan if you have an idea of what this would entail

**Comment by otan** [comment]
might be annoying considering we don't type "void" (we rely on type checked desired types and void/unknown is not really well handled) -- my guess is adding a new type but not allowing it to be stored, and type checks will need to change to account for it (but only for the "desired" type). unsure if pgwire is affected but may be as well.
