### ISSUE TITLE
ui: add link to visualize trace information outside of the admin UI

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#45248]
We would like to expose a way for users to visualize their traces. Because we will not have time to build something that does this directly in the UI in 20.1, a compromise we reached is building a tool that POSTs the relevant data to an external site or tool. 

We can stand up a simple service that simply prints the JSON to start and eventually build out an interactive tool that is not coupled to the CRDB release cycle.

This issue only tracks the creation of the link in the Admin UI.

Design Link: https://www.figma.com/file/C85d0mrz8dkNs7Nw5mcTmf/obsrv_admin-ui-statements?node-id=1236%3A2080

**Comment by tharun208** [comment]
I like to work on this
