### ISSUE TITLE
ui: jobs design follow up work 

### ISSUE THREAD

**Issue by Annebirzin** [cockroachdb/cockroach#45259]
Design follow up work related to #44681

_Note: We are switching from using Zeplin to just using Figma so I have added Figma links below. Let me know any trouble accessing_

**Jobs List Updates:** 
- [x] Update job id, users and creation time text color to `#242A35`
![Screen Shot 2020-02-20 at 4 40 34 PM](https://user-images.githubusercontent.com/51920721/74981177-c5e35f80-53ff-11ea-9ab4-4b0b62da99e6.png)

- [x] Update status styling to new 'pill' style ([designs here](https://www.figma.com/file/c6BNEn0mY6iHG1t5NhoH3E/obsrv_admin-ui-jobs?node-id=1190%3A65)): 
![Screen Shot 2020-02-20 at 12 17 17 PM](https://user-images.githubusercontent.com/51920721/74960806-fb298680-53da-11ea-911b-1b27d0cc5680.png)

- [x] Update statuses to match naming in filter (`succeeded`, `failed`, `pending`, `canceled`, `paused`)

- [x] update filters: dropdown arrows should not point up (always point down)

- [x] Update empty state: [designs here](https://www.figma.com/file/uU9C1XSleeAu26CvTWwekX/obsrv_admin-ui-empty-states?node-id=4%3A5) (Relates to this issue #45264): 
    - update copy 
    - banner height should be 192px 
    - update spacing between header, description and button to match designs
    - header font  `Source Sans Pro: regular` `20px` `#242A35`
    - description font  `Source Sans Pro: regular` `14px` `#475872`

- [x] Update no results state copy (currently shows copy from statements page): [designs here](https://www.figma.com/file/uU9C1XSleeAu26CvTWwekX/obsrv_admin-ui-empty-states?node-id=4%3A5)
![Screen Shot 2020-02-20 at 4 00 35 PM](https://user-images.githubusercontent.com/51920721/74979476-b57db580-53fc-11ea-81e7-59bd6e0d57ff.png)

**Jobs Detail Page Updates** 
- [x] Update to new [job code style](https://www.figma.com/file/c6BNEn0mY6iHG1t5NhoH3E/obsrv_admin-ui-jobs?node-id=1136%3A2393). (Matches [statement code style](https://www.figma.com/file/C85d0mrz8dkNs7Nw5mcTmf/obsrv_admin-ui-statements?node-id=1144%3A1899))
![Screen Shot 2020-02-20 at 12 23 06 PM](https://user-images.githubusercontent.com/51920721/74961301-d84ba200-53db-11ea-926c-a6f69fdd30aa.png)
- [x] Update Job ID title font to be smaller: `Source Sans Pro: regular` `20px`
![Screen Shot 2020-02-20 at 4 35 59 PM](https://user-images.githubusercontent.com/51920721/74980842-35a51a80-53ff-11ea-9c87-8f4d4cd92fa7.png)

- [x] Verify other font sizes on page: 
      - right-side panel: time stamp and user text are `Source Sans Pro: regular` `20px`
      - right-side panel: time stamp and user labels are `Source Sans Pro: regular` `14px`
      - status panel: status header is `Source Sans Pro: regular` `16px`
      - status panel: progress percentage / time is `Source Sans Pro: regular` `14px`

- [x] Update creation date format to match format on list view: `Feb 19, 2020 at 8:45PM` 

![Screen Shot 2020-02-20 at 4 36 49 PM](https://user-images.githubusercontent.com/51920721/74980895-4786bd80-53ff-11ea-9848-0dd4ccbc0c85.png)

- [x] Update status displays for `succeeded` `failed` `pending` `canceled` `paused` to new pill style ([designs here](https://www.figma.com/file/c6BNEn0mY6iHG1t5NhoH3E/obsrv_admin-ui-jobs?node-id=1149%3A1319)) 
![Screen Shot 2020-02-20 at 12 59 59 PM](https://user-images.githubusercontent.com/51920721/74964146-ecde6900-53e0-11ea-85c6-d5931cd864ef.png)

**Comment by nathanstilwell** [comment]
I want to make a comment on `pt` values for font-sizes. `pt` can be confusing when it comes to screens. `1pt` is meant to be 1/72 of an inch, which makes a lot of sense in a print medium but must be calculated differently when in the context of a screen where a retina displays mean that a "pixel" isn't really a "pixel". I'm a little out of the loop on using `pt` for digital displays, but if we are adamant about using them I would be happy to dive back in. For simplicity, I would suggest we always use pixels.

**Comment by Annebirzin** [comment]
thanks @nathanstilwell, I mean to use `px` instead of `pt`, just updated
