### ISSUE TITLE
kv: expand "server-side refresh" mechanism to non-commit batches

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#45258]
For a while, we've had a mechanism by which the server would re-evaluate batches on WriteTooOld conditions when the `CanCommitAtHigherTimestamp` was set -> indicating that there's nothing to refresh. Currently this mechanism only applies to non-txn batches and batches with an `EndTxn`.
To make it truly awesome, we ought to lift the `CanCommitAtHigherTimestamp` flag from the `EndTxn` to the batch header, allowing other requests to take advantage of it. @nvanbenschoten reports impressive performance gains to be had on contended YCSB.

**Comment by nvanbenschoten** [comment]
> @nvanbenschoten reports impressive performance gains to be had on contended YCSB.

This is especially true with the rest of the implicit SELECT FOR UPDATE and concurrency manager changes. With the three changes combined, we see extremely fair and responsive queuing. The concurrency manager ensures fair queuing once a lock is acquired and responds directly to intent resolution without any indirection through transaction records (on the happy path). Implicit SELECT FOR UPDATE eagerly acquires upgrade locks on the initial row-fetch of UPDATE statements to avoid conditions that result in transaction retries. And finally, this change ensures that the initial upgrade lock never thrashes on WriteTooOld errors.

I saw [a prototype](https://github.com/nvanbenschoten/cockroach/commit/bf031b5a435e996ef199a451db7f8eb3bfa10dac) of this change result in an additional ~40% throughput win on top of the ~80% throughput win from the SFU + concurrency manager changes referenced above. This was when running YCSB workload A without column families.

**Comment by nvanbenschoten** [comment]
This was completed in https://github.com/cockroachdb/cockroach/commit/972915d74fb560eb9c78b31504d6f984fa84f522.
