### ISSUE TITLE
kv: RETRY_COMMIT_DEADLINE_EXCEEDED on long running transactions

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#45278]
When a transaction uses a table it sets its commit deadline to the current expiration of the node's lease for that table. If the transaction's timestamp gets pushed beyond the deadline the the transaction will fail with `RETRY_COMMIT_DEADLINE_EXCEEDED`. Note that the transaction would need to be pushed. This may cause retry errors to appear on transactions which do not experience contention.

A proposed fix would be to attempt to extend the deadline of the transaction if we are able to renew the table lease.

**Comment by tim-o** [comment]
Thanks for filing - which versions would be impacted? v2.x? or was this introduced in 19.x?

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4763](https://cockroachdb.zendesk.com/agent/tickets/4763) has been linked to this issue.

**Comment by andreimatei** [comment]
dup of #36871

That one has more context.
