### ISSUE TITLE
cli: allow setting --log-dir=${TMPDIR} for `cockroach start`

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#4527]
#4505 changed the `cockroach start` command to default the log directory to the "logs" subdirectory of the first store. The implementation isn't quite correct as it looks at the log-dir flag to see if it has changed from the default of "${TMPDIR}". But this implementation means you can't actually set `--log-dir=${TMPDIR}`. The fix is straightforward, instead of default `--log-dir` to `${TMPDIR}` we should default it to some other invalid value (e.g. perhaps the actual string `${TMPDIR}`) and then in an `OnInitialize` hook set the value to `os.TempDir()` if it hasn't changed.

**Comment by bdarnell** [comment]
Why mention `${TMPDIR}` at all? It just makes the `--help` output misleading. The flag default can be an empty string which we replace with either os.TempDir or the first store depending on the command.

**Comment by petermattis** [comment]
@bdarnell The only reason is so that `cockroach --help` will show the default.

**Comment by bdarnell** [comment]
But `$TMPDIR` is no longer the default for what is arguably the most important command. Better to show nothing than something misleading.
