### ISSUE TITLE
sql: audit schema changer logs

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#45346]
I'm creating this issue as a tracking issue for improving the logging in the schema changer. Recently several issues have popped up that have been difficult to track down due to conservative logging in this module.

As schema changes are relatively rare and are important events I think that we should have more logging around them (e.g. when a schema change is attempted).

**Comment by lucy-zhang** [comment]
At this point we've added more logging. But we'll keep this issue open in hopes that the schema changer can take advantage of the new PII-free logging functionality, since logging descriptors would be useful.

**Comment by lucy-zhang** [comment]
Closing since we did add more logging and remaining work is tracked in #51239.
