### ISSUE TITLE
sql: other schema changes should be disallowed while a primary key change is in progress

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#45363]
If schema changes are allowed while a primary key change is in progress, all existing schema change setup logic needs to "understand" when a primary key change is happening and set up the target table descriptor as if the primary key change has been completed. The surface area on this task is quite large, and it would be better to disable the feature until the scope is more clear and each case is handled.

**Comment by awoods187** [comment]
This seems reasonable to me. cc @ericharmeling as this will need to be communicated clearly in the docs

**Comment by ericharmeling** [comment]
> This seems reasonable to me. cc @ericharmeling as this will need to be communicated clearly in the docs

Thanks Andy. This should be picked up during our release note issue process.
