### ISSUE TITLE
sql: primary key changes maybe should be disabled while other schema changes are executing

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#45362]
A PR recently landed to allow primary key changes to handle when indexes are being rebuilt. However, I'm worried about different cases (such as column additions) where the setup for the primary key change needs to coordinate with other in progress mutations.

We should first audit primary key changes and see interactions with other concurrent schema changes. If the scope of changes seems too large, disable primary key changes while other schema changes are executing.

**Comment by rohany** [comment]
There are three types of in progress mutations (other than primary key change):
* index mutations
* column mutations
* constraint mutations

I don't believe that the constraint mutations can affect the alter primary key steps, and the primary key changer already knows about index mutations and handles them appropriately. It might just be the case that the primary key change operation needs to also be taught about columns that are currently being added.

**Comment by awoods187** [comment]
I like this plan. OPK should be done rarely and in a "healthy" cluster state.

**Comment by rohany** [comment]
Implementing and testing support for currently added columns seems to depend on changes + bugfixes made in https://github.com/cockroachdb/cockroach/pull/45347.

**Comment by awoods187** [comment]
I like this plan. OPK should be done rarely and in a "healthy" cluster state.
