### ISSUE TITLE
ui: absolute timestamps take multiple lines in events table 

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#45402]
Now that we have switched to absolute timestamps throughout the UI (🎉), we have noticed the new timestamp takes up much more room than the previous version causing some formatting issues.

The place where this is most noticeable is on the events list on the metrics dashboards:
![image](https://user-images.githubusercontent.com/21692034/75279048-eaad4d80-57d8-11ea-9f51-6647d8add7ab.png)

cc @Annebirzin

**Comment by Annebirzin** [comment]
@piyush-singh  I'm thinking we can introduce a short date format for instances where there is limited space in the UI (see below screenshot). This could be an issue for users in other countries who use different date formats, but maybe in the future we can automatically update date formatting based on time zone? 

![Screen Shot 2020-02-26 at 1 16 52 PM](https://user-images.githubusercontent.com/51920721/75374817-ef3a3a80-589a-11ea-84cd-f5866527df4a.png)

**Comment by koorosh** [comment]
@Annebirzin , @piyush-singh , what do you think about redesigned Events list view to make more room for
both event message and date?
And limit up to 3 events in the list (instead of 10)

<img width="305" alt="Screenshot 2020-03-03 at 17 58 21" src="https://user-images.githubusercontent.com/3106437/75794155-113f2b80-5d79-11ea-8836-9d30713b9b62.png">

**Comment by Annebirzin** [comment]
@koorosh I think showing more of the text is helpful. Maybe we can just extend the event text the full width of the module and left-align the date. Maybe we limit to 5 events? Any thoughts @piyush-singh? ([designs here](https://www.figma.com/file/WK4FG2dFxTpqt96K1FZhSw/obsrv_admin-ui-metrics?node-id=1229%3A6334)) 

![Screen Shot 2020-03-03 at 12 43 14 PM](https://user-images.githubusercontent.com/51920721/75803568-a415a100-5d4c-11ea-95e3-77219011cd63.png)
