### ISSUE TITLE
ui: add txn type back into statements page

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#45405]
When updating the statements page with the new design, we removed a column that indicates the transaction type for a specific statement fingerprint. We should add this back in as it conveys important performance information about how we measure the performance of those particular statements.

Piyush to follow with Nathan on whether this is necessary after the parallel commits protocol rollout.

**Comment by Annebirzin** [comment]
@taroface fyi it looks like we will be keeping the TXN column on the statements page. I can update the designs/spreadsheet

**Comment by Annebirzin** [comment]
I've added the txn column to the statements page: [designs here](https://www.figma.com/file/C85d0mrz8dkNs7Nw5mcTmf/obsrv_admin-ui-statements?node-id=1139%3A1715)
