### ISSUE TITLE
jobs: BACKUP jobs found to have `nil` lease

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#45403]
It is possible for a backup job to have a `nil` lease on it's job payload. This means that if the job needs to be adopted again, the job registry will go into this condition and not attempt to adopt it: https://github.com/cockroachdb/cockroach/blob/master/pkg/jobs/registry.go#L915. This is causing backup jobs to hang.

**Comment by spaskob** [comment]
Closing this as it turned out the job is a schema change job for which this is expected.
