### ISSUE TITLE
IMPORT INTO does not seem to respect named column order

### ISSUE THREAD

**Issue by mqudsi** [cockroachdb/cockroach#45422]
**Describe the problem**

```sql
CREATE TABLE Foo (
    id STRING NOT NULL,
    num INT NOT NULL
);
```

and with a csv file `reversed_columns.csv` that contains the following:

```csv
17,hello
18,goodbye
```

Start a web server in the same directory as the csv file, then try to import the data but with the order of the columns reversed as compared to the DDL:

```sql
IMPORT INTO Foo (num, id) CSV DATA ('http://localhost:9001/reversed_columns.csv');
```

This results in an error that makes it clear it's trying to import the data into columns in the same order as they exist in the database rather than as named in the `IMPORT` command:

```
pq: "http://localhost:9001/test.csv": row 1: parse "num" as INT8: could not parse "hello" as type int: strconv.ParseInt: parsing "hello": invalid syntax
```

**Environment:**
 - CockroachDB version: 19.2.4
 - Server OS: Windows 10 1909
 - Client app: `cockroach sql`

**Comment by C0rWin** [comment]
PR #45713
