### ISSUE TITLE
Have nodes create a ballast file by default

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#45445]
From our [docs](https://www.cockroachlabs.com/docs/stable/operational-faqs.html#what-happens-when-a-node-runs-out-of-disk-space):

> When a node runs out of disk space, it shuts down and cannot be restarted until space is freed up. To prepare for this case, place a ballast file in each node's storage directory that can be deleted to free up enough space to be able to restart the node. If you did not create a ballast file, look for other files that can be deleted, such as log files.

We provide a cli command ([`cockroach debug ballast`](https://www.cockroachlabs.com/docs/stable/cockroach-debug-ballast.html)] to let users proactively create ballast files for their nodes, and we call out the need to [actively monitor disk space](https://www.cockroachlabs.com/docs/stable/monitoring-and-alerting.html#node-is-running-low-on-disk-space). However, multiple users have run into this issue. 

In addition to being even more explicit in the docs about how to handle this when you have not proactively used a ballast file (which files to delete, etc.), we should consider having nodes auto-create ballast files on startup, perhaps with options to change the size or disable the file creation. We should be careful to think about what this means for both local dev clusters and production clusters. 

A second request would be for the Admin UI to alert on low disk space, if/when alerting becomes possible.

cc @piyush-singh and @johnrk, as this is both about ops and observability, I think. 

Jira issue: CRDB-6329

**Comment by rkruze** [comment]
One concern with this approach is that if you are running multi nodes of cockroach locally for testing that it could end up taking up a fair bit of space.

**Comment by jordanlewis** [comment]
@rkruze that's a good point. We should definitely make sure to add an opt-out flag (and maybe env variable) so we can carry on testing activities as normal.
