### ISSUE TITLE
ui: update colors and fonts across admin ui

### ISSUE THREAD

**Issue by Annebirzin** [cockroachdb/cockroach#45471]
Update old Admin UI colors and fonts to our new design system. 
I've mapped the [color and font updates here](https://www.figma.com/file/TqjqzNz8WpGJCTy0UBFxHB/obsrv-design-components-v1?node-id=1295%3A25)

Let me know if there are any colors or fonts missing or if there is a better way to do this.

Here is the full [design system](https://www.figma.com/file/B5AtEGdRbW3VxiBdg62TB8Xw/CRDB-Design-System_V2?node-id=0%3A1) for reference 

![Frame 1](https://user-images.githubusercontent.com/51920721/75389042-e5710100-58b3-11ea-9ec8-3d9f81ee7688.png)
![Frame 2](https://user-images.githubusercontent.com/51920721/75462492-58c95000-5952-11ea-9da8-be31add2f36f.png)

**Comment by koorosh** [comment]
@Annebirzin , here is a list of colors which are used across Admin UI
in different places and they do not match to neither old nor new color palette:
Could you suggest alternatives from new designs?

$healthy-color = `#66AA26`
$adminui-grey-2    = `#5f6c87`
$adminui-blue-1-base    = `#3a7ce1`
$body-color = `#5F6C87`
$link-color = `#3A7DE1`
$tooltip-color = `#B8BBBC`
$table-border-color = `#EDEDED`
$button-border-color = `#C8CBD4`
$main-blue-color = `#3A7DE1`
$grey = `#b8bbbc`
$table-border = `#45592`

// Alert colors
$notification-alert-fill-color = `#F4D9D9`
$notification-alert-border-color = `#F2B7B7`
$notification-info-fill-color = `#F2F8EC`
$notification-info-border-color = `#C8E0AF`
$notification-warning-fill-color = `#FDF8E9`
$notification-warning-border-color = `#F9E6AF`

// Info box colors
$info-box-fill-color = `#EEF7FE`
$info-box-border-color = `#3A7DE1`
$info-box-heading-color = `#3A7DE1`

// Syntax highlight colors
$syntax-string-color = `#E4843C`
$syntax-keyword-color = `#91C8F2`

$lightgreen = `#e1f2d1`
$lightblue = `#e0f1ff`

Also some parts of application still use old designs of partially updated with custom styles.
I assume following places have to revised separately regarding to new designs.

1. **User menu** (top-right corner) has to be redesigned regarding to new designs.
<img width="255" alt="Screenshot 2020-03-11 at 10 46 07" src="https://user-images.githubusercontent.com/3106437/76398434-8caa6980-6385-11ea-8921-ccb3743a0b38.png">

2. **Network diagnostics**, badge elements (green and blue ones) have custom colors: `#b5e28b`, `#e1f2d1`, `#e0f1ff`, `#bee1ff`
<img width="728" alt="Screenshot 2020-03-11 at 10 43 07" src="https://user-images.githubusercontent.com/3106437/76398395-78666c80-6385-11ea-88a0-75c8cf9b68de.png">

3. **Page headers**. It doesn't match to new designs. Font sizes, top paddings and alignments to left sidebar do not match to designs on some pages. 
Currently we have two main modifications of headers:
- Header with a title only
- Header with title and navigation link back (above the title)
Modifications of these titles are differ from page to page and it has to be reviewed how page titles
should look and behave. After that it has to be extracted to standalone component to reuse everywhere.

4. **Login** page is full of custom styles (probably it's okay)

**Comment by Annebirzin** [comment]
@koorosh thanks very much for the detailed breakdown, this is very helpful!

Below are the color updates:

$healthy-color = #66AA26  --->   green-3 = #37A806
$adminui-grey-2 = #5f6c87   --->   neutral-6 = #475872
$adminui-blue-1-base = #3a7ce1   --->   blue-3 = #0788FF
$body-color = #5F6C87   --->   neutral-6 = #475872
$link-color = #3A7DE1   --->   blue-3 = #0788FF
$tooltip-color = #B8BBBC   --->   neutral-5 = #7E89A9
$table-border-color = #EDEDED   --->   neutral-2 = #E7ECF3
$button-border-color = #C8CBD4   --->   neutral-4 = #C0C6D9
$main-blue-color = #3A7DE1   --->   blue-3 = #0788FF
$grey = #b8bbbc   --->   neutral-5 - #7E89A9
$table-border = #45592   --->   ?
**this hex value is missing a number, can you update?**

// Alert colors
$notification-alert-fill-color = #F4D9D9   --->   red-1 = #FFE5E8
$notification-alert-border-color = #F2B7B7   --->   red-2 = #FF808C
$notification-info-fill-color = #F2F8EC   --->   blue-1 = #E0EEFB
$notification-info-border-color = #C8E0AF   --->   blue-2 = #74BDFD
$notification-warning-fill-color = #FDF8E9   --->   orange-1 = #FEF1DA
$notification-warning-border-color = #F9E6AF   --->   orange-2 = #FFD099

// Info box colors
$info-box-fill-color = #EEF7FE   --->   blue-1 = #E0EEFB
$info-box-border-color = #3A7DE1   --->   blue-3 = #0788FF
$info-box-heading-color = #3A7DE1   --->   blue-3 = #0788FF

// Syntax highlight colors
$syntax-string-color = #E4843C   --->   orange-4 = #B26000
$syntax-keyword-color = #91C8F2   --->   blue-2 = #74BDFD

$lightgreen = #e1f2d1   --->   green-1 = #B4F1AA
$lightblue = #e0f1ff   --->   blue-1 = #E0EEFB


1. I can create a separate issue for updating the user avatar. 
2. We can update the network latency colors to the following values below. Let me know if you think there will be an issue doing 50% opacity, otherwise we can just choose a custom hex value. 
![Screen Shot 2020-03-11 at 12 01 20 PM](https://user-images.githubusercontent.com/51920721/76437585-27a84100-6390-11ea-8f3f-a017ba9a903a.png)
3. I created an issue that Vlad worked on here #45447 to address headers and back arrow links. Would be great the have the two headers as stand alone components to be reused.
4. Good point about the login page. I think it's okay for now but will create a new issue and designs to update.

**Comment by koorosh** [comment]
Sorry, here is correct value, messed it while copy-pasting :)
$table-border = `#dbe1ea`

**Comment by Annebirzin** [comment]
👍thanks, I've updated the colors in my comment above

**Comment by koorosh** [comment]
> 2\. We can update the network latency colors to the following values below. Let me know if you think there will be an issue doing 50% opacity, otherwise we can just choose a custom hex value:

In this case, opacity won't be a problem.
In general I would avoid using opacity because it is safe if background color is white.

**Comment by koorosh** [comment]
> * I can create a separate issue for updating the user avatar.
> *

@Annebirzin , it will be very helpful to not forget about this!

**Comment by koorosh** [comment]
> 3. I created an issue that Vlad worked on here #45447 to address headers and back arrow links. Let me know if that covers what you are referring to. It would be great the have the two headers as stand alone components to be reused.

Yes, this issue partially covers the issue I mention (it is related for Node Details page only as I see). My main concern is about reusing this across all pages in Admin UI to ensure consistent view. It is more about technical realization as far as you've already provided all designs we need. Thank you!
