### ISSUE TITLE
ui: add pagination to statement list on table detail page 

### ISSUE THREAD

**Issue by Annebirzin** [cockroachdb/cockroach#45480]
- [x] add pagination to the statement list on table detail page (note: I also created ticket #45479 for adding the 'last cleared' timestamp)

![Databases_07](https://user-images.githubusercontent.com/51920721/75395501-92517b00-58c0-11ea-9673-1ca2b234bf5d.png)

**Comment by dhartunian** [comment]
@Annebirzin can we set this ticket aside for now?
