### ISSUE TITLE
release: Write up instructions on publishing a custom build

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#45487]

**Comment by kenliu** [comment]
noting this issue #42584

**Comment by jlinder** [comment]
I’ve written up a doc on how to create one-off builds. I plan to send an email to eng@ announcing it and would like to first have it reviewed. 

@dt @pbardea Would one of you take a look?

https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/846299518/One-Off+Builds+A+How+To

**Comment by jlinder** [comment]
This is completed and announced to eng@.
