### ISSUE TITLE
sql: add syntax for CLOSE ALL

### ISSUE THREAD

**Issue by roji** [cockroachdb/cockroach#45490]
I'm the maintainer of the Npgsql .NET driver for PostgreSQL, which people also use to connect to Cockroach. I've received an issue (https://github.com/npgsql/npgsql/issues/2867) about Npgsql sending `CLOSE ALL` under some conditions (pooled connection close), but since Cockroach doesn't support cursors, this errors.

Ideally, Cockroach would know to silently ignore this PostgreSQL command - that would promote more compatibility with PostgreSQL etc. However, I can also refrain from sending this in the driver when connected to Cockroach; but to do that, I need an "official" way to detect it, that wouldn't change in future versions. Does Cockroach announce itself in the `server_version` parameter? Should one do `SELECT version()` and look for some string in there?

**Comment by jordanlewis** [comment]
Hi @roji, yeah, we'll add no-op support for `CLOSE ALL`.

`version()` will return a string that starts with `CockroachDB`.

**Comment by roji** [comment]
Thanks @jordanlewis, I'll code the detection that way.

**Comment by rafiss** [comment]
I'll rename this issue so it covers adding the `CLOSE ALL` syntax. Open question: should we also make `CLOSE` on its own be a no-op?

**Comment by apantel** [comment]
My opinion is that `CLOSE foo` should be an error, because if you think you have a cursor to close then something has gone wrong. `CLOSE ALL` is fine as a no-op.

**Comment by roji** [comment]
That sounds right to me too - it makes sense to ignore CLOSE ALL, but CLOSE foo sounds like it should error.

**Comment by apantel** [comment]
blocked on bors, not sure why
