### ISSUE TITLE
sql: you can't create a pk-less table with a column named rowid

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#45496]
```
root@127.0.0.1:53487/defaultdb> create table foo (rowid int);
ERROR: duplicate column name: "rowid"
```

This is caused by a leaky abstraction - we make a hidden column called `rowid` when a table doesn't have a primary key. But we should instead give the hidden column a unique name to avoid this problem.

cc @timveil @awoods187 @apantel

**Comment by rohany** [comment]
Note: when this logic changes we should also update `(*TableDescriptor).IsPrimaryIndexDefaultRowID()`

**Comment by jordanlewis** [comment]
@rohany could you see how hard it would be to tackle this, since you're already looking at `rowid` stuff?
