### ISSUE TITLE
backupccl: Update backup to use protected timestamp

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#45508]
**Is your feature request related to a problem? Please describe.**
Currently, if a backup takes longer than the gcttl it will error out because it won't have captured the full snapshot of the database at the desired "AS OF TIME". This is exacerbated by FULL CLUSTER BACKUP and backing up system.jobs table, which has a default 600s gcttl. Backups should be extremely reliable in their completion.

**Describe the solution you'd like**
An option for all backup commands to include "with protected timestamp" to ensure we don't encounter the above case.

**Additional context**
If you want to take an incremental backup with revision history less frequently than 600s and/or to a previous backup whose high water mark timestamp is >600s ago, you'll have to tweak the system.jobs gcttyl

**Comment by mwang1026** [comment]
cc @dt @ajwerner

**Comment by dt** [comment]
#45859
