### ISSUE TITLE
ui: add telemetry to statements list page

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#45506]
This issue tracks which new actions we would like to record telemetry for in the Statements list page of the Admin UI.

- [x] Changing sort order (want to see which column and asc vs desc)
- [x] Search (how often is enough, we probably want to scrub out any actual search terms)
- [x] Clicking to paginate (we should track whether the user clicked next, or a specific page number)

As part of the diagnostic bundle/tracing work, we should track:
- [x] Diagnostic bundle activations (capturing high level statement performance information as part of the event is nice, e.g. latency or execution count; we should scrub the actual fingerprint)

**Comment by nathanstilwell** [comment]
@piyush-singh Since diagnostics downloads and trace link clicks don't happen on the statements page, I'm going to pick them up in #45625 (telemetry on the details page)
