### ISSUE TITLE
sql: cannot perform primary key changes while other schema changes are in progress

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#45510]
We cannot currently perform primary key changes when an in progress schema change on the same table is occuring, or when a schema change on the same table has been started earlier in the same transaction. Before we can allow this, we need to investigate the following cases and ensure that primary key changes can handle them.
- [x] preceding index creations
- [ ] preceding column creations 
- [ ] preceding constraint creation/validation
- [ ] preceding primary key changes

**Comment by lrotim** [comment]
Any news or timeline on when this feature might be implemented?

**Comment by ajwerner** [comment]
We're working on generalized transactional schema changes. That work will encompass this.

**Comment by vy-ton** [comment]
https://github.com/cockroachdb/cockroach/issues/42061 is the issue for generalized transactional schema changes

**Comment by postamar** [comment]
Reopening to track unskipping test case in TestPrimaryKeyChangeWithPrecedingIndexCreation

**Comment by SunRunAway** [comment]
Should this issue be closed?

```
defaultdb=> BEGIN;

ALTER TABLE public.status_test
ADD COLUMN id UUID DEFAULT gen_random_uuid();

ALTER TABLE public.status_test
DROP CONSTRAINT status_pk,
ADD PRIMARY KEY (id);

COMMIT;
BEGIN
ALTER TABLE
ERROR:  unimplemented: cannot perform a primary key change on status_test with other schema changes on status_test in the same transaction
提示:  You have attempted to use a feature that is not yet implemented.
See: https://go.crdb.dev/issue-v/45510/v24.1
ROLLBACK
```
