### ISSUE TITLE
telemetry: add "gauge" for telemetry

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#45518]
**Is your feature request related to a problem? Please describe.**
We currently only have `telemetry.Inc`, which gets reported to looker. This is good for answering queries such as "how many times does X happen".

However, sometimes we prefer to know how to answer questions such as "what is X at a given point in time". For example, PMs would like to know questions such as:
* how many of each data type is currently used within all the DB's schemas at a given time?
* how many different configurations for zones (using `CONFIGURE ZONE`) from the default have been used?

We currently only can answer "how many NEW types" or "how many NEW configurations" with `telemetry.Inc`. However, it'd be cool to have "how many are at a given point in time" with something such as `telemetry.Gauge` (we can use something like a background job to periodically poll and update this figure).

Note that in the `metrics` package we currently have `metrics.Gauge`, but that doesn't get posted as telemetry anywhere (instead, it's available as a timeseries graph for Admin UIs).

**Describe the solution you'd like**
Implement `telemetry.Gauge`, and make this usable with looker.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

Jira issue: CRDB-5150

**Comment by otan** [comment]
cc @awoods187 since I heard you were interested

**Comment by awoods187** [comment]
this sounds very useful. cc @nstewart for awareness

**Comment by jordanlewis** [comment]
Yeah, can we talk about this a little more?

I'm summoning @dt who understands more about the registration service than I do.

Currently we just have counters - a telemetry number that increments every time somebody performs an action. With gauges (see #45518), I think the idea would be that we'd report all schema and settings information on every metrics collection period. Question is, what would you do on the registration cluster side? You wouldn't want to replace the measurement rows, so I guess you'd append a new one for each measurement and then have queries sum the most recent rows across all users or something?

Then again, maybe that's already how things work - I just don't know. Hence the @dt ping - could you please weigh in here?

This metric type would help enormously for reporting things like #45028, or things like how common a particular column type is. You'd just send, per-cluster, whether a setting was on or off, or the number of columns total in the entire database of each type.
