### ISSUE TITLE
Cockroach db connection timeout k8s pod

### ISSUE THREAD

**Issue by devsecopsindia** [cockroachdb/cockroach#45525]
**Describe the problem**
We have running cockroach db on Kubernetes with 3 nodes. We have multiple apps running on Kubernetes which connected to cockroach database using cockroach-public IP. Everything is running perfectly. Now sometime We are getting connection timeout error from our application pod. I have check the cockroach cluster log but I didn’t found any error or load on the cluster. 

Please describe the issue you observed, and any steps we can take to reproduce it:
```
GET /user HTTP/1.1
2020/02/27 04:28:18 EOF
{"Environment":"stage","LogID":"m2ND37Ts13","Message":"user_handler.go/myapp/service/restapiv1/controllers.ShowCurrentUser:323","Params":[{"UserID":"2219662811138"}],"Request Body":null,"Request Method":"GET","Request Remote Address":"10.60.1.1","Request URL":"/user?includeSkills=true","level":"error","msg":"write tcp 10.60.1.204:44614->my-cockroachdbip:26257: write: connection timed out
```

**To Reproduce**

What did you do? Describe in your own words.
I have checked the cockroach db pod log but didn't fount any error.

**Environment:**
 - CockroachDB version [cockroachdb/cockroach:v19.2.2]
 - Server OS: [Kubernetes GCP]
 - Client app [e.g. `cockroach sql`]

**Comment by jordanlewis** [comment]
Sorry we never got to this. Closing due to age. For problems like this, it's usually better to ask on the forum or on our community slack (https://cockroa.ch/slack)
