### ISSUE TITLE
`make` in clean cockroach checkout fails sporadically before succeeding

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#45522]
Ran `git clean -ffdx vendor c-deps .` on a random working branch, and `make` to start from scratch. Had to re-run it three times before it succeeded. Captured the build log [here](https://gist.github.com/irfansharif/0caf6b28869227795106df89167efce8).

**Comment by irfansharif** [comment]
Semi-randomly assigning @dhartunian.

**Comment by dhartunian** [comment]
Possibly the same ticket #45222. Added to Observability backlog for prioritization in next sprint.

**Comment by irfansharif** [comment]
I'll gently nudge for this again, we're working on squashing roachtest failures now so doing a lot of jumping between revisions and rebuilding stuff, and I keep running into it.

**Comment by dhartunian** [comment]
@irfansharif we're quite busy with getting a bunch of work in for the stability period so the best I can promise is adding this to the 2w sprint that starts next week.

**Comment by irfansharif** [comment]
Accidentally refiled as #50100.
