### ISSUE TITLE
ui: `go generate` fails on Linux because of osx-specific dependency

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#4555]
While working on #4548 I needed to run `go generate` and encountered the following:

```
npm install --progress=false
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated object-pick@0.1.2: Deprecated as of version 0.1.2 please use object.pick instead.
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.0.7
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! System Linux 4.2.0-27-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--progress=false"
npm ERR! cwd /home/kena/go/src/github.com/cockroachdb/cockroach/ui
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code EBADPLATFORM
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0
 as soon as possible.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0
 as soon as possible.
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/kena/go/src/github.com/cockroachdb/cockroach/ui/npm-debug.log
npm ERR! not ok code 0
Makefile:102: recipe for target 'npm.installed' failed
make: *** [npm.installed] Error 1
ui/ui.go:21: running "make": exit status 2
```

**Comment by tamird** [comment]
That's odd. How come it works in CircleCI?

**Comment by knz** [comment]
After upgrading to a more recent version of `master` I run into a different issue:
```
npm install --progress=false
/usr/bin/env: node: No such file or directory
Makefile:102: recipe for target 'npm.installed' failed
```

Now I can work this issue by symlinking `/usr/bin/nodejs` to `~/bin/node` but again there's too much magic.

I do not know why it works in CI but it definitely does not work out of the box on this plain, no-frills, out-of-the-box ubuntu 15.

**Comment by tamird** [comment]
I suggest you run it inside the builder container.

**Comment by knz** [comment]
Wait what? Where is this documented?

**Comment by tamird** [comment]
I might not be specifically documented, but that's the purpose of the builder container: to provide a known environment in which our tools work. Trying to make everything resilient in the face of ever-changing distributions and user-specific setups is not an efficient use of development time.

**Comment by knz** [comment]
Look I am all right with running the acceptance tests in docker; however here you are saying that I should run `go generate` in the builder container as well? How does this work exactly? My git working directory lives outside of docker, so how can I run `go generate` inside docker and know outside docker what to commit?

**Comment by tamird** [comment]
`build/builder.sh` is a wrapper script designed to make this convenient.
You can run `build/builder.sh go generate ./...` from the repository root
to get the intended result.

**Comment by bdarnell** [comment]
The version of node that ships with ubuntu 15 (both 15.04 and 15.10) is rather old, and quirky (debian and ubuntu rename the binary from `node` (as it is everywhere else) to `nodejs` to avoid conflicts with an older package named `node`). In circleci we install nodejs from nodesource.com instead of the version that comes with ubuntu. 

We should at least document this in CONTRIBUTING.md. If it's easy, we should support the ubuntu-provided node packages as well (probably won't be practical for the old version in 15.10, but 16.04 is coming soon and will have a newer version), but we shouldn't invest too much time in this since the builder image is available.
