### ISSUE TITLE
acceptance: add chaos agents

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#4559]
- Add the ability to add chaos agents to acceptance test configs
- Ensure test that require no chaos agents use only a subset.

Related to #4015

**Comment by spencerkimball** [comment]
Bram, I'm removing 1.0 milestone and re-classifying this as an enhancement. Please re-open and prioritize using the labels or close this issue if it's not reasonably expected.

**Comment by BramGruneir** [comment]
I'll just close it.  This was more than a year ago when I was re-writing a good chunk of our testing.  We've moved away from adding more acceptance tests and instead moved to using TestCluster. A much better move.
