### ISSUE TITLE
sql: expose index usage metrics 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#45591]
A customer recently asked us for a way to identify the most used, unused, read only, written/updated only indexes.

We don't have a current way to expose this information but have discussed the need to provide this data and eventually to help make index recommendations (for adding or removing indexes) in this issue https://github.com/cockroachdb/cockroach/issues/41259.

Jira issue: CRDB-5144

**Comment by mgartner** [comment]
We don't expose this information, but are we collecting it within the cluster? If so, is there anyway to retrieve it, even if its a hack?

I think a good first step is keeping some simple statistics on index usage that can be queried by a user similar to Postgres's `pg_stat_user_indexes` table. Tracking the number of index scans (or an estimation) is a useful tool for finding unused indexes that are only consuming space and adding write overhead without providing a benefit to any SELECT queries. This came up in a recent customer inquiry, where they had multiple tables with 15-20 indexes.

**Comment by mgartner** [comment]
@maryliag I believe all these cases are now covered and we can close this. Can you confirm?

**Comment by maryliag** [comment]
Yes, we now provide this information. This issue can be closed.
