### ISSUE TITLE
cli: `cockroach demo` should start secure clusters by default

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#45606]
Today it's impossible to use `cockroach demo` to teach users about creating users, SQL privileges, admin UI login and the different visibility of data in the UI. This is because `cockroach demo` creates an insecure cluster behind the scenes.

The tool instead should be changed to use secure mode by default. Note that the TestServer infrastructure has a flag for that.

**Comment by knz** [comment]
cc @otan @rohany

**Comment by sandyleo26** [comment]
happy to take a shot at it with some guidance. Could i have some pointers on where to start?

**Comment by knz** [comment]
Rohan is already on it!

**Comment by knz** [comment]
Fixed by #45727
