### ISSUE TITLE
kv: single_key_test.go:119: expected 600, but found 599

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4560]
This happened on https://circleci.com/gh/cockroachdb/cockroach/13148 so theoretically it could have been introduced there, but that's not obviously the case.

In that test run above, one increment is missing - expected value is 600, but we get 599, so one was missing. I took a cursory look at the test code and it doesn't seem that there's an issue with the test-side increments (i.e. it looks like 600 actual increments should've been performed, not 599).

**Comment by petermattis** [comment]
I saw this failure as well: https://circleci.com/gh/petermattis/cockroach/350?utm_campaign=build-failed&utm_medium=email&utm_source=notification. That PR was definitely not the source of the problem.

**Comment by tschottdorf** [comment]
Ok. I'll start by adding more checks as the keys are written. If that
indicates that the "weird stuff" happens as the test finishes, maybe there
**is** some atomic update issue I'm overlooking (as opposed to a
consistency failure).
