### ISSUE TITLE
sql: add option to log queries resulting in full table scans

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#45616]
We have received several requests to have some way to log which queries are resulting in table scans in order to help users identify where they have missing indexes. Ideally this would function as a toggle for the slow query log, so that queries resulting in table scans appeared alongside long running statements. Note that queries resulting in full table scans would _not_ need to meet the slow query threshold in order to be logged. A related setting to set a floor on the number of rows scanned would help with avoiding tables with very few records where indexes are not necessary. 

MySQL has a similar configuration option for their slow query log. See the `log_queries_not_using_indexes` parameter [here](https://dev.mysql.com/doc/refman/5.7/en/slow-query-log.html#slow-query-log-parameters). They also offer an option to rate limit the collection of queries without indexes to avoid runaway slow query log file growth. They also mention that they distinguish between [full table scans and queries without indexes](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_log_queries_not_using_indexes). 

We have had several users request this functionality because it enables them to test new deployments and catch table scans in test environments that may have little data, resulting in relatively quick full table scans. These scans can then cause issues when deployed to larger data sets in production environments.

**Comment by benmccann** [comment]
See also https://github.com/cockroachdb/cockroach/issues/20060 and https://github.com/cockroachdb/cockroach/issues/13969

**Comment by BramGruneir** [comment]
@arulajmani, are there any more work items in this issue or can we close it?

**Comment by arulajmani** [comment]
Yeah, this can be considered close after https://github.com/cockroachdb/cockroach/pull/53164. Guess I missed tagging this issue in the commit message, thanks for flagging.
