### ISSUE TITLE
ui: release notes signup message does not permanently dismiss

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#45624]
Clicking the 'X' to remove the email signup does not permanently dismiss message. Similarly if I enter my email the prompt is still not permanently dismissed. If I close and reopen my browser, I see the same message. I believe we track the state of whether users have dismissed the message about the latest version of cockroach DB so that they will not see it if they have dismissed it once.

For insecure clusters, this may mean dismissing this notification hides it for everyone else as users are not required to log in. For users logged in, it might be nice to store whether they have dismissed the message permanently, so they are not greeted with the same message even if they have already signed up.

**Comment by koorosh** [comment]
@piyush-singh , alert message will be closed automatically after 6 seconds (as was proposed by @Annebirzin , to add transient behavior for alerts). 
Also this message will be closed when the user navigates to another page or closes Email signup panel. Would it be expected behavior?

**Comment by Annebirzin** [comment]
@piyush-singh that link doesn't seem to work for me

**Comment by dhartunian** [comment]
@koorosh I think @piyush-singh is asking for an implementation using https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/src/redux/uiData.ts which persists flags on the database itself instead of the current implementation using Local Storage.
