### ISSUE TITLE
ui: add telemetry to statement details page

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#45625]
- [x] clicks of the sub navigation (logical plans, execution stats, diagnostics)
- [x] clicks of the diagnostics activations
- [ ] downloads of the diagnostics bundle

**Comment by dhartunian** [comment]
Tracking of diagnostics bundle/trace downloads will be taken care of by me as part of #46331

**Comment by piyush-singh** [comment]
"downloads of the diagnostics bundle" is being handled in the tracing PR linked above
