### ISSUE TITLE
ui: Rendering of node names is inconsistent in the code

### ISSUE THREAD

**Issue by dhartunian** [cockroachdb/cockroach#45622]
Currently a lot of different code is responsible for rendering node names in the Admin UI. It would make sense to standardize on a single format and ensure that one place in the code is responsible. We're not too far from this since the number of code spots are few for now.

Ideally we can either change the types in the code to make it easier to use the `getDisplayName` function that already exists or modify the types we're using and the function to make them work well together.

See #45551 for examples.

**Comment by girishramnani** [comment]
My initial search in the code shows these 2 places which need the change

1 - https://github.com/cockroachdb/cockroach/blob/7860cf9fc36c67d9c810aa1db055427972d8fb7b/pkg/ui/src/views/reports/containers/network/legend/index.tsx#L101

2 - https://github.com/cockroachdb/cockroach/blob/7860cf9fc36c67d9c810aa1db055427972d8fb7b/pkg/ui/src/views/reports/containers/network/legend/index.tsx#L106

**Comment by girishramnani** [comment]
opened a PR which changes both of these places https://github.com/cockroachdb/cockroach/pull/45665

If there are any other places then I can change those too.

**Comment by girishramnani** [comment]
@dhartunian if you could assign this issue to me then that would me amazing

**Comment by girishramnani** [comment]
Thanks for the assign @nathanstilwell
