### ISSUE TITLE
opt: outer column should be treated as a constant when aggregating

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#45631]
```
CREATE TABLE ab (a int, b int);
SELECT
	(SELECT (max(b), unnest) FROM ab WHERE a = unnest)
FROM
	ROWS FROM (unnest(ARRAY[1, 2]));
```
errors out with `pq: column "unnest" must appear in the GROUP BY clause or be used in an aggregate function`.

The `unnest` column is an outer column so it should be allowed. This query works in postgres.

**Comment by rytaft** [comment]
I can't actually reproduce this. Perhaps you meant to remove GROUP BY from the subquery?

**Comment by RaduBerinde** [comment]
Indeed, edited.
