### ISSUE TITLE
bulkio: provide visibility for events in debug logs

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#45643]
Customer request: provide visibility for cluster level events in the logs. We're already recording these cluster level events in the `system.events` table, and exposing them in the UI, but the customer wants to tail logs. Their ideal is for the `system.events` rows to be replicated in every node's logs in case one or more of the nodes are down.

This doesn't really fall under any team's ownership, but I'm taking Bulk I/O because jobs are one of the more frequent creators of events.

**Comment by dt** [comment]
Interesting. We'd essentially need to... poll the eventlog table and log changes?

I was thinking about this from a slightly different angle recently which was that when bulk jobs schedule workers (distsql flow procs), those workers should log at startup and defer a log at exit, so you'd have an idea of why a given node was running a given piece of code.

**Comment by petermattis** [comment]
> Interesting. We'd essentially need to... poll the eventlog table and log changes?

That's the obvious implementation. Perhaps we can do something more clever. I'm sure @ajwerner would suggest something with range feeds.

**Comment by ajwerner** [comment]
> I'm sure @ajwerner would suggest something with range feeds.

Indeed I would.

**Comment by knz** [comment]
Can we also consider a network log sink - have our logs push to a network service.

**Comment by petermattis** [comment]
> Can we also consider a network log sink - have our logs push to a network service.

Definitely. Is there a standard one to use?

**Comment by knz** [comment]
There are a couple actually. Aaron and I were talking about making that part of the security roadmap, since there's a "problems to solve" section already for this kind of work.

**Comment by knz** [comment]
(My technical proposal would be to start an experiment using syslog - which has its own standard protocol and distributed network sinks as plug-ins - and see where that brings us.)

**Comment by knz** [comment]
I have discussed this with @petermattis today.
For context:

- the customer that motivated filing this issue does not consider this urgent. We can schedule it for 20.2.

- the original user journey is "an operator wants CLI access to a stream of cluster events for manual and automatic monitoring". 

- it's not sufficient to provide "network logging" (i.e. logging to a network sink) as a feature, there will need to be a way for an operator looking at 1 node to see events coming from the entire cluster.

- double-reporting is OK as long as there's a timestamp or ID that can be used to de-duplicate.

- under-reporting is a problem. The customer can tolerate double-reporting but not missed events.

- a changefeed-based solution, or a solution that can capitalize on one of the mechanisms already present in crdb, is preferable to the introduction of a new ad-hoc mechanism.

- an intermediate, ad-hoc solution with known deficiencies is not "palatable". In peter's words "I’d find it more palatable if it didn’t have deficiencies, but even then I wouldn’t push to get it in."
