### ISSUE TITLE
logs: review rotation/retention behavior and per-logger quotas

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#45648]
In some recent incident debugging, there were cases where it looked like logs from when a job had been run in the days prior had already been rotated. It'd be good to be able to retain logs for something significant, like job running, for longer in case it takes time for an issue to be surfaced, escalated and then investigated.

It would be good to understand where the retention quota is going: Is it the volume of other messages in main logger?  Are other loggers (like the rocksdb debug log) counted in the same quota or do we have per-logger retention?

**Comment by knz** [comment]
The answer is yes - the quota is currently shared across all loggers, and this is likely a mis-design.

The limit should probably be per logger instead.
