### ISSUE TITLE
storage/simulation: More Work

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#4566]
The simulator needs a good amount of work still.  

Revisit the simulator once the current rebalancing work is completed.  It should be a much faster way to adjust the heuristics. But it must accurately represent how a cluster behaves.

**Comment by tamird** [comment]
I can't find any TODOs in storage/simulation. What's left here?

**Comment by BramGruneir** [comment]
A good amount of rewriting I think.  Been a while since I looked at it.  I know some of the todos have been finished.  Sadly, right now, we can't rely on the simulator to accurately emulate a real cluster due to stability issues.

**Comment by tamird** [comment]
Can you add some information to this issue?

**Comment by BramGruneir** [comment]
Not at the moment.  I'll need to spend some significant time going back through the code and I'll re-asses after the current bout of work on rebalancing is finished.

**Comment by BramGruneir** [comment]
Updated this with a bit more info.

**Comment by BramGruneir** [comment]
The old simulator has been removed.
