### ISSUE TITLE
sql: error in the pretty-print code for CREATEROLE

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#45683]
Found via random syntax gen tests:

```
    rsg_test.go:750: Parse followed by Format is not idempotent: "ALTER GROUP IFNULL WITH CREATEROLE NOCREATEROLE" -> "ALTER ROLE 'ifnull' WITH NOCREATEROLE CREATEROLE" != "ALTER ROLE 'ifnull' WITH CREATEROLE NOCREATEROLE"
```

**Comment by knz** [comment]
(This is because the code to pretty-print the AST does not do the right thing. Add a new test in parse_test.go when you figure it out.)

**Comment by knz** [comment]
another example

```
Found via rsg:

```
rsg_test.go:750: Parse followed by Format is not idempotent: 
"SELECT 491 IN ( WITH RECURSIVE ident ( ZONE , IF ) AS ( ALTER ROLE 'string' WITH CREATEROLE NOCREATEROLE NOCREATEROLE ) , ident ( INTEGER ) AS ( IMPORT INTO FAMILY . ident . POSITION IFERROR DATA ( PLACEHOLDER , PLACEHOLDER ) WITH 'string' = PLACEHOLDER ) SELECT error ) ident FROM FAMILY . NOTNULL * @ INNER NUMERIC ( ROW ) WHERE EXISTS ( TABLE error ORDER BY INDEX INDEX . ident @ IF ASC ) IS TRUE"

 -> 

"SELECT 491 IN (WITH RECURSIVE ident (zone, \"if\") AS (ALTER ROLE 'string' WITH NOCREATEROLE NOCREATEROLE CREATEROLE), ident (\"integer\") AS (IMPORT INTO \"family\".ident.\"position\" IFERROR DATA ('placeholder', 'placeholder') WITH string = 'placeholder') SELECT error) AS ident FROM \"family\".\"notnull\"@inner AS \"numeric\" (\"row\") WHERE EXISTS (TABLE error ORDER BY INDEX \"index\".ident@if ASC) IS true" 

!= 

"SELECT 491 IN (WITH RECURSIVE ident (zone, \"if\") AS (ALTER ROLE 'string' WITH CREATEROLE NOCREATEROLE NOCREATEROLE), ident (\"integer\") AS (IMPORT INTO \"family\".ident.\"position\" IFERROR DATA ('placeholder', 'placeholder') WITH string = 'placeholder') SELECT error) AS ident FROM \"family\".\"notnull\"@inner AS \"numeric\" (\"row\") WHERE EXISTS (TABLE error ORDER BY INDEX \"index\".ident@if ASC) IS true"
```


Note how CREATEROLE != NOCREATEROLE

**Comment by RichardJCai** [comment]
This was fixed here:
https://github.com/cockroachdb/cockroach/pull/44968
