### ISSUE TITLE
colexec: problem with simpleProjectOp

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#45686]
Consider the following query `SELECT a, 1 FROM t` (where table was created with `CREATE TABLE t (a STRING, b FLOAT);`) and the following artificial plan (the actual plan will be different, but for the sake of example, it works well):
```
                    │
                    ├ Node 1
                    │ └ *colexec.Materializer
                    │   └ *colexec.constInt64Op
                    │     └ *colexec.simpleProjectOp
                    │       └ *colexec.ParallelUnorderedSynchronizer
                    │         ├ *colexec.colBatchScan
                    │         └ *colrpc.Inbox
                    └ Node 2
                      └ *colrpc.Outbox
                        └ *colexec.deselectorOp
                          └ *colexec.colBatchScan
```
Basically, we have data living on two nodes, `colBatchScan`s will read both columns, and the batches will be propagated to `ParallelUnorderedSynchronizer`. The synchronizer returns batches to `simpleProjectOp` which "projects out" column `b` ("projects out" is in quotes because the batch is not actually changed, only `projectionBatch` wrapper on top of it is), and then `constInt64Op` appends an `Int64` column with value of `1`.

Here is some important state of the operators for the context:
- `constInt64Op` thinks that its output column's index is 1
- `simpleProjectOp` initially is instantiated with `projection = []uint32{0}` (i.e. from the batch it receives, initially it "keeps" only the 0th column).

Let's say that the batch from the "local" `colBatchScan` gets to the synchronizer first. It contains two columns, `simpleProjectOp` stores it internally and returns `projectingBatch` wrapper around the batch to `constInt64Op`. That operator will append an `Int64` column, and now `simpleProjectOp.projection = {0, 2}`.

Next, the "remote" batch arrives, and it has the schema of `(String, Float)`. `simpleProjectOp` still has `{0, 2}` as its "projection". And this is where the problem is - a different "internal" batch came in, but we never reset/update the state of `simpleProjectOp`. When this "remote" batch gets to `constInt64Op`, that operator will check that batch's width (which should be 1, but mistakenly 2 is returned), so it will not append a column and, instead, will try to set `int64(1)` into the float vector - type mismatch panic.

I believe such issue can occur only in the flows that have an unordered synchronizer (either parallel or serial), and it is present in 19.2 release.

I encountered this problem when adding the support for multiple window functions in the same query while running logic tests with `fakedist-vec` config. I think the fix can be quite simple - we simply store `map[coldata.Batch]*projectingBatch` in `simpleProjectOp`, and when we get a batch from the input, we look up the corresponding projection batch (or create it if not present).

cc @asubiotto @jordanlewis to make sure I'm not missing something

**Comment by jordanlewis** [comment]
Nice find, I think it makes sense. It's unfortunate though. I'm nervous that there are other cases like this that we've overlooked. Mostly I think operators expect to get identically shaped batches. Perhaps it should be the responsibility of the synchronizer to always emit the same-sized batch.

**Comment by yuzefovich** [comment]
Simply returning the same-sized batch from the synchronizer doesn't seem sufficient - we need to reset `projectingBatch` inside of `simpleProjectOp` when a different (even if same-sized) batch comes from the input. Otherwise, `projectingBatch` will get confused. For example, synchronizer returns batches with two columns, then `simpleProjectOp` projects out the second, then we have to different projection operators that append two other columns. Those two columns will be added into `projection`, so `simpleProjectOp.projection = {0, 2, 3}`. When a batch from a different input of the synchronizer comes in, it will still have two columns, but downstream operators will think that that there are three (and of different types) because of the `projectingBatch`.

One possible solution is to have a special `output` batch in the unordered synchronizers - they would have to copy all the data from the inputs into that `output` and return that batch. Then, that output batch will be the only batch that downstream operators will see, so everything will work. However, the cost is that we would have to do this extra copy.

**Comment by asubiotto** [comment]
In this case, why would the projection be planned only on node 1 after the synchronizer? I would expect it to be pushed down to right above the `colBatchScan`. It does seem problematic though.

**Comment by yuzefovich** [comment]
As I said, this is artificial example, it wouldn’t have happened in real scenario, but it illustrates the problem.
