### ISSUE TITLE
sql: Set default transaction priority for session

### ISSUE THREAD

**Issue by apantel** [cockroachdb/cockroach#45756]
It is not possible to set a default transaction priority for a session. `SET SESSION CHARACTERISTICS AS TRANSACTION PRIORITY LOW;` returns an error.

**Comment by rafiss** [comment]
@apantel I tried running that query in Postgres and it also returns an error. What is it supposed to do?

**Comment by rafiss** [comment]
Also, running the query in CockroachDB actually works right now.

**Comment by knz** [comment]
The "X-anchored-telemetry" tag is only for when the issue is linked from the crdb source code. This is not the case (currently). I removed the label.

**Comment by rafiss** [comment]
Some context: https://github.com/cockroachdb/cockroach/pull/49597 adds a link to this issue, but I left a comment on there, as I'm not sure we should have this issue.

**Comment by solongordon** [comment]
As @rafiss pointed out, it looks like this statement works in CRDB but not in Postgres. I'm going to assume this issue was opened in error but please re-open if not.
