### ISSUE TITLE
sql: primary key changes seem to rebuild more indexes than necessary

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#45773]
It seems like primary key changes will always rebuild non-unique indexes even if they contain all the columns in the new primary key.

Jira issue: CRDB-5130

**Comment by awoods187** [comment]
Could you show an example? How easy would this be to fix?

**Comment by rohany** [comment]
This should be relatively easy to fix. An example is
```
table (x INT PRIMARY KEY, y INT, index i (y));
alter primary key of t using x
```
`i` would get rebuilt even though there is no need.

**Comment by awoods187** [comment]
Ah I see, I definitely think we should get this in if we can. Nice performance optimization.
