### ISSUE TITLE
sql: rollback past DDL causes deadlock

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#45793]
The check for DDL that I introduced in #43051 was broken in #45566. Try this:

1. issue `BEGIN; SELECT 1`, wait for results to ensure the auto-retry is disabled

2. issue: `SAVEPOINT foo;  CREATE TABLE t(x INT); SELECT crdb_internal.force_retry('1h');`

so far all good

3. issue: `ROLLBACK TO SAVEPOINT foo`

4. issue: `SELECT * FROM t`

**boom** - deadlock.

Expected either of the following:

1. "cannot rollback to savepoint after a transaction restart" (your other check)
2. "rollback after DDL is not yet supported" (my original check)
3. "t does not exist" (schema change properly rolled back)

**Comment by knz** [comment]
This is different from #24885 I think? Because we're looking at a savepoint past the begin of the txn.

**Comment by knz** [comment]
Also the severity is higher than the original report because once we announce savepoint support this pattern of txn is more likely to be issued by clients.

**Comment by andreimatei** [comment]
I think it is #24885. You don't need the `force_retry()` to repro, do you?
I'll try to do something about it

**Comment by andreimatei** [comment]
Closing in favor of #24885.
