### ISSUE TITLE
Does Bulk insert happen within an implicit transaction

### ISSUE THREAD

**Issue by darren-west** [cockroachdb/cockroach#45803]
Looking at the documentation it is said not to include a multi row insert within a transaction why is this?

* Is this because it is implicitly creating a transaction for you? 
* The use case I have is; if I have 2 transactions pushing batch updates to the same table and they update the same record will the second one to commit fail? 

Thanks

**Comment by jordanlewis** [comment]
Hi @darren-west, sorry this fell through the cracks. A single statement always executes within a transaction, if that is what you are asking.
