### ISSUE TITLE
cli: smartprompt message about open txns gets confused by rollback to savepoint

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#45816]
If you send a batch containing a `BEGIN`, you get a message.
```
root@:26257/defaultdb> begin; savepoint a; 
Now adding input for a multi-line SQL transaction client-side (smart_prompt enabled).
Press Enter two times to send the SQL text collected so far to the server, or Ctrl+C to cancel.
You can also use \show to display the statements entered so far.
                    -> 
```

But if you send a batch with a `begin` and a `rollback to savepoint`, you no longer get it. I guess it must be that the parser doesn't make a distinction between `rollback` and `rollback to` ?
```
root@:26257/defaultdb> begin; savepoint a; rollback to a;
ROLLBACK
```

Also Rafa remind me where you stand on getting rid of this message? I for one never want it.

**Comment by andreimatei** [comment]
We could send a notice if the app is our sql client perhaps instead of that confirmation prompt.

**Comment by knz** [comment]
I don't think you understand why this exists nor how it works :sweat_smile: 

the idea is to block the sending of SQL to the server until the user presses enter twice. The rationale for this is to create an opportunity for server-side auto-retry. Also to prevent the opening of a long-lived txn.

I think we can preserve this functionality with very little change. I'll send a PR.

**Comment by andreimatei** [comment]
I challenge you to conduct a poll of 10 people; if any single one says that they prefer the `smart_prompt` option set by default, I'll shut up. 
Btw, I'm trying to get it off by doing `./cockroach sql --set='smart_prompt=false'`, but it doesn't seem to work although the syntax inside the `--set` seems to be validated.

**Comment by knz** [comment]
I filed #46074 to remove the functionality. It's too late for 20.1 but we can consider it for 20.2. I'll look at `--set` too.
