### ISSUE TITLE
sql: SUBSTRING of bit types not supported

### ISSUE THREAD

**Issue by andy-kimball** [cockroachdb/cockroach#45848]
Repro:
```
root@:26257/defaultdb> SELECT substring('0110'::bit(4), 1, 2);
ERROR: unknown signature: substring(bit, int, int)
```
EXPECTED: No error, PG gives this:
```
template1=# SELECT substring('0110'::bit(4), 1, 2);
 substring
-----------
 01
```

**Comment by andy-kimball** [comment]
Good first issue?

**Comment by sandyleo26** [comment]
happy to take this one if no one has started on it

**Comment by jordanlewis** [comment]
Hey @sandyleo26, we would love your contribution here!

Check out the file `pkg/sql/sem/builtins/builtins.go` - that's where builtin implementations generally live, and there are already a few overloads of `substring` there to take a look at.

**Comment by sandyleo26** [comment]
that's great. thanks for the pointer. will give it a crack tmr.

**Comment by sandyleo26** [comment]
2+ hours in yet i still cannot get a clean build && passed test out of a freshly cloned repo following [this](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181338446/Getting+and+building+from+source)  😢 

i used the docker image to build. first i got this:
```
Makefile:1506: bin/execgen_out.d: No such file or directory
```
i commented out the line that caused this and fire another build. it went for quite a while until I got this:

```
ERROR in ./src/views/jobs/jobTable.tsx
Module not found: Error: Can't resolve 'oss/src/components/pagination/pagination' in '/go/src/github.com/cockroachdb/cockroach/pkg/ui/src/views/jobs'
 @ ./src/views/jobs/jobTable.tsx 34:0-79 194:31-50
 @ ./src/views/jobs/index.tsx
 @ ./src/app.tsx
 @ ./src/index.tsx
 @ multi ./src/index.tsx
Makefile:1360: recipe for target 'pkg/ui/distccl/bindata.go' failed
```
I uncomment the previous line, tried again but got the same error. and somehow during this process `git status` refuse to work giving me this:

```
fatal: not a git repository: /go/src/github.com/cockroachdb/cockroach/.git/modules/c-deps/protobuf/modules/third_party/benchmark
fatal: 'git status --porcelain=2' failed in submodule c-deps/protobuf
```

lastly i run `./build/builder.sh make test` wishfully thinking it might be bogus. after about 20m it timed out with a lot of error logs:

```
panic: test timed out after 20m0s

goroutine 453006 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1377 +0xdf
created by time.goFunc
	/usr/local/go/src/time/sleep.go:168 +0x44
......
```

but the test seems not stopped, still driving my laptop's fan crazy...

can i get some help? it's really frustrating to start contributing like this...

**Comment by andy-kimball** [comment]
@sandyleo26, I'm sorry you've had a tough starter experience. Unfortunately, you ran into a merge skew that broke the build last night (see https://github.com/cockroachdb/cockroach/pull/45937). That was the cause of the "pagination" error you saw.

I'll tag in @jordanlewis to comment on the `bin/execgen_out.d` failure.

**Comment by jordanlewis** [comment]
Hey @sandyleo26, I'll echo Andy's comments that we're sorry about this frustration. @knz can you  help out here? I believe some of this is new functionality that you added.

@sandyleo26 in the mean time, if you want to have a quicker way to chat, feel free to jump into our community slack group, in the #contributors channel: https://cockroa.ch/slack

**Comment by knz** [comment]
yes I am looking into it

**Comment by knz** [comment]
please follow #45976 for the `make` problem.

**Comment by sandyleo26** [comment]
thank you guys and @knz for the quick follow up and raising the issue. i'll try rolling back later this week and see if issue goes away.

**Comment by knz** [comment]
the `make` problem should be fixed now (you need to pull from `master` though). Let us know if you experience any other problem.

**Comment by sandyleo26** [comment]
> the `make` problem should be fixed now (you need to pull from `master` though). Let us know if you experience any other problem.

it build now. thanks!

**Comment by sandyleo26** [comment]
due to personal priorities change i don't have time to work on this anymore in the next few weeks. happy if someone could take it over.

**Comment by abhishek20123g** [comment]
happy to take this one :blush:.
