### ISSUE TITLE
sql: CREATEROLE is inconsistently implemented

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#45857]
The following works half-way:

1. `CREATE USER blah WITH CREATEROLE` -- works without error *but also without a license* (whereas `CREATE ROLE ... WITH CREATEROLE` fails with a license rror)

2. after the above succeeds, if I log in with user `blah`, then `CREATE USER foo` fails with `user blah does not have CREATEROLE privilege` (which is not true at this point)

**Comment by RichardJCai** [comment]
Oops, found the bug, the function that resolves the role memberships of the user doesn't include the user itself so it can't find the privilege - gonna fix that and add tests.

**Comment by knz** [comment]
Your reply is about point 2. What about point 1?

**Comment by RichardJCai** [comment]
@knz for point 1, do you mean CREATE ROLE doesnt work without license? Thats the intended behaviour, after some discussion with product we decided to keep CREATE ROLE syntax disabled for non-enterprise.
