### ISSUE TITLE
sql: Missing get_bit and set_bit functions

### ISSUE THREAD

**Issue by andy-kimball** [cockroachdb/cockroach#45851]
Repro:
```
root@:26257/defaultdb> SELECT get_bit(B'0101011000100', 10);
ERROR: unknown function: get_bit()
root@:26257/defaultdb> SELECT set_bit(B'0101011000100100', 15, 1);
ERROR: unknown function: set_bit()
```

**Comment by sandyleo26** [comment]
happy to take a shot at it. Could i have some pointers on where to start? thanks.

**Comment by abhishek20123g** [comment]
Hi @sandyleo26 
If haven't started working on this issue you can leave upto me as I had completed ```get_bit ``` and started working on ```set_bit```

For creating bultiin function you have to write definition in ```pkg/sql/sem/builtin/builtins.go``` here you can look into all other builtin function which were previously created.
Sorry @sandyleo26 if I caused any inconveniences.

**Comment by sandyleo26** [comment]
> Sorry @sandyleo26 if I caused any inconveniences.

no i haven't. i guess i'll wait for another chance. thanks for your pointer anyway.

**Comment by abhishek20123g** [comment]
Hii @sandyleo26 ,
   You can take look in issue #45848 and #45849 they are also alike like them

**Comment by sandyleo26** [comment]
> Hii @sandyleo26 ,
> You can take look in issue #45848 and #45849 they are also alike like them

thanks a lot. just submit my claim on them. it's pretty late here so will do them tmr.

**Comment by abhishek20123g** [comment]
Facing problem as mentioned in #45976
