### ISSUE TITLE
opt: Transform InnerJoin + Values to Project

### ISSUE THREAD

**Issue by andy-kimball** [cockroachdb/cockroach#45853]
If an `InnerJoin` or `InnerJoinApply` operator  has a cardinality 1 `Values` operator on its right-hand side, transform it to a `Project` operator. The optgen rule would look similar to:
```
(InnerJoin | InnerJoinApply
  $left:*
  $right:(Values) ^ (HasOneRow $right)
  $on:*
)
=>
(Select
  (Project
    $left
    (MakeProjectionsFromValues $right)
    (OutputCols $left)
  )
  $on
)
```
This rule would be useful for decorrelating queries like this:
```
root@:26257/defaultdb> EXPLAIN (OPT) SELECT (SELECT CASE WHEN ord.approved THEN 'Approved' ELSE '---' END) FROM (VALUES (1, true), (2, false)) ord(id, approved);
                                 text
----------------------------------------------------------------------
  project
   ├── inner-join-apply
   │    ├── values
   │    │    ├── (true,)
   │    │    └── (false,)
   │    ├── values
   │    │    └── (CASE WHEN column2 THEN 'Approved' ELSE '---' END,)
   │    └── filters (true)
   └── projections
        └── case
```

**Comment by andy-kimball** [comment]
Another good starter issue.

**Comment by il9ue** [comment]
Hi, 
I am new here but may I take a look into this one? 
If so, could you share some of the code lines or materials I could refer to, if possible? 

Thanks

**Comment by RaduBerinde** [comment]
Hi @il9ue, sure! I would start by trying to understand how an existing normalization rule works (e.g. one in `sql/opt/norm/rules/join.opt`). You can find the corresponding generated code by grepping for the rule name in `opt/norm/factory.og.go` (after running `make build`), and all rules should have corresponding testcases in `norm/testdata/rules` (those can be helpful to visualize the resulting expressions).

Some general documentation on the optimizer is [here](https://github.com/cockroachdb/cockroach/blob/ec8ee4f2bf8b35de82b32b2aec6b85a5ada33295/pkg/sql/opt/doc.go#L12)
