### ISSUE TITLE
sql: Support unqualified table refs that return tuples of column values

### ISSUE THREAD

**Issue by andy-kimball** [cockroachdb/cockroach#45854]
Repro:
```
root@:26257/defaultdb> SELECT t FROM (VALUES (1,2), (3,4)) t(x, y);
ERROR: column "t" does not exist
```
EXPECTED: An unqualified table name should return a tuple of column values. Here is PG output:
```
template1=# SELECT t FROM (VALUES (1,2), (3,4)) t(x, y);
   t
-------
 (1,2)
 (3,4)
```

**Comment by knz** [comment]
FWIW this is already supported in crdb: `SELECT (t.*) FROM ....` and produces the result.

**Comment by andy-kimball** [comment]
I stumbled upon that syntax. However, I found that it behaves differently than PG does. Here is CRDB:
```
root@:26257/defaultdb> SELECT (t.*) FROM (VALUES (1,2), (3,4)) t(x, y);
  ?column?
------------
  (1,2)
  (3,4)
```
And PG:
```
template1=# SELECT (t.*) FROM (VALUES (1,2), (3,4)) t(x, y);
 x | y
---+---
 1 | 2
 3 | 4
```

**Comment by knz** [comment]
Ouch that doesn't seem right...

**Comment by RaduBerinde** [comment]
PG ignores the paren in that case. We differ a bit from PG with regard to interpreting parens as tuples, specifically we interpret them as tuples in cases where PG does not. Note that you can always add `ROW` to force the latter, in this case (in PG):
```
radu=> SELECT ROW (t.*) FROM (VALUES (1,2), (3,4)) t(x, y);
  row  
-------
 (1,2)
 (3,4)
(2 rows)
```

Unfortunately, using `ROW` here in cockroachdb is apparently not a no-op (this seems wrong):
```
root@127.0.0.1:33429/defaultdb> SELECT (t.*) FROM (VALUES (1,2), (3,4)) t(x, y);
  ?column?
------------
  (1,2)
  (3,4)
(2 rows)

Time: 355.624µs

root@127.0.0.1:33429/defaultdb> SELECT ROW (t.*) FROM (VALUES (1,2), (3,4)) t(x, y);
     row
-------------
  ("(1,2)")
  ("(3,4)")
(2 rows)
```

Also, it looks like a reference to is resolved to a "bare" table only when there is no alternative, even if it's from a higher scope, e.g.:
```sql
create table ab (a int, b int);
create table a (x int);
select * from ab where (select a from a) = 2;
```
Here `a` is an outer column reference from `ab`. This is a departure from our resolution logic which always tries to bind something to the lowest scope.
