### ISSUE TITLE
cli: SIGQUIT does not dump stack any more

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#45875]
You can't `CTRL+\` (SIGQUIT) the cockroach process any more to get a stack trace. I thought this used to work, and I think this ought to work.

It's easy enough to fix (we grab the signal handler, so we override the default behavior) but I wanted to see if I'm missing context first.

**Comment by knz** [comment]
I went to check:

- client commands support SIGQUIT as usual
- `cockroach start` has blocked SIGQUIT from behaving in this way (and let it behave like a regular shutdown) ever since v1.0

I would see some wisdom in making a SIGQUIT handler that dumps the stacks to the log, but I'm not sure we want to reproduce the native Go behavior? (SIGQUIT forces the process to stop abruptly)

**Comment by tbg** [comment]
Oh, didn't know this was like that all the way back. I think it's reasonable to keep the graceful shutdown, but we should write the stacks to the log. Should I make that change?

For context, I noticed this when trying to improve roachtest by sending SIGQUIT to everything running on the machine in case of a test timeout, but then I realized this wasn't doing what I wanted, so now I have to send SIGSEGV which is not the canonical way we dump stacks and thus might confuse folks who look at the logs into thinking that there was an actual segfault.

**Comment by petermattis** [comment]
> I think it's reasonable to keep the graceful shutdown, but we should write the stacks to the log. Should I make that change?

I'm thumbs up on this proposal. I've noticed in the past that SIGQUIT didn't dump goroutines stacks and found that behavior surprising but didn't take the time to investigate what could be done about it.

**Comment by knz** [comment]
@tbg can you remind me why you did not like #36378 which was achieving _exactly_ this?

**Comment by tbg** [comment]
#36378 does not stop the binary. I think ideally we'd have left SIGQUIT alone way back in v1.0, but now it seems to late to restore the stock Go runtime behavior, so the next best thing is to dump the stack to the log and then continue graceful quit.

**Comment by knz** [comment]
all right let's do that then. You or me?
