### ISSUE TITLE
sql: strftime nano and microseconds notation

### ISSUE THREAD

**Issue by chriscasano** [cockroachdb/cockroach#45881]
Minor issue.  For %f notation of strftime using experimental_strftime(), we output nano seconds instead of microseconds which doesn't match python documentation here: https://strftime.org/

```
root@:26257/defaultdb> select experimental_strftime(now(), '%Y-%m-%d %I:%M:%S.%f');
      experimental_strftime
+-------------------------------+
  2020-03-09 01:29:15.580861000
```

I think it's good that we output more rather than less.  A nice to have would be to follow python document and use %f to output microseconds and use a different notation for nano, although python doesn't support nano seconds.  Current workaround is to use 

`select left(experimental_strftime(now(), '%Y-%m-%d %I:%M:%S.%f'),-3);`

which is bit wonky.

**Comment by otan** [comment]
`%f` isn't official in the POSIX standard (https://metacpan.org/pod/POSIX::strftime::GNU).

sounds like we can do whatever we want here....
