### ISSUE TITLE
tracing: support a sample rate for tracers

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#45891]
**Is your feature request related to a problem? Please describe.**

Currently cockroach supports external tracing services using the zipkin or lightstep protocols. When these features are enabled, 100% of all requests are traced. This leads to serious overhead both inside of Cockroach and in the trace collection infrastructure. Tracing can provide value even at very low sampling rates. Furthermore, with new features to enable tracing on-demand for certain statement fingerprints, users could gain additional value out of an existing trace collection infrastructure.

**Describe the solution you'd like**

Add a cluster setting to control the sampling rate for trace collection.

**Additional context**

See this discussion for the original conversation https://github.com/cockroachdb/cockroach/issues/45578#issuecomment-594222605.

**Comment by TylerJGabb** [comment]
I'd like to start working on this. Should I just submit a pull request?

**Comment by ajwerner** [comment]
Just this comment is good enough. A pull request would be great.  In general we haven't had actual contention with community contributions competing to fix the same issue. I don't anticipate that here. If somebody internally were to be working on it, it would get assigned.

If you run in to any trouble or want any pointers on how to approach it, let me know.

**Comment by jayshrivastava** [comment]
The observability team decided that we are not going to take this approach for optimizing shadow tracing.
