### ISSUE TITLE
sql: don't accept X.0 values for bucket_count 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#45890]
We don't except any values other than positive integers:
```SQL
ALTER TABLE events6 ALTER PRIMARY KEY USING COLUMNS (product_id ASC, owner ASC, serial_number ASC) USING HASH WITH BUCKET_COUNT = "7";
ERROR: BUCKET_COUNT must be a strictly positive integer value
SQLSTATE: 22023
```
or
```SQL
 ALTER TABLE events6 ALTER PRIMARY KEY USING COLUMNS (product_id ASC, owner ASC, serial_number ASC) USING HASH WITH BUCKET_COUNT = 7.1;
ERROR: BUCKET_COUNT must be a strictly positive integer value: cannot represent numeric constant as an int
SQLSTATE: 22003
```
But we do accept .0.
```SQL
ALTER TABLE events6 ALTER PRIMARY KEY USING COLUMNS (product_id ASC, owner ASC, serial_number ASC) USING HASH WITH BUCKET_COUNT = 7.0;
NOTICE: primary key changes spawn async cleanup jobs. Future schema changes on "events6" may be delayed as these jobs finish
ALTER TABLE
```
```SQL
CREATE TABLE events7 (
    product_id
        INT8,
    owner
        UUID,
    serial_number
        VARCHAR,
    event_id
        UUID,
    ts
        TIMESTAMP,
    data
        JSONB,
    -- Creates a primary index on (shard, product_id, owner, serial_number)
    -- with a check constraint for `shard in (0...7)`
    PRIMARY KEY (product_id, owner, serial_number) USING HASH WITH BUCKET_COUNT=8.0
);
CREATE TABLE
```

I think we should not accept x.0 for both create and alter, or, we should accept x.0 for create and alter but be able to tell that 7=7.0 (for buket_count) and error out so that we don't incur the costly primary key change.

**Comment by jordanlewis** [comment]
Is this important to fix? @rohany do we no-op primary key changes if the output primary key is the same, normally?

**Comment by rohany** [comment]
> Is this important to fix?

Not sure, its a small thing andy found.

> @rohany do we no-op primary key changes if the output primary key is the same, normally?

not currently

**Comment by jordanlewis** [comment]
Okay. I think this issue should be closed, because the underlying problem here is not no-opping primary key changes if the output primary key is the same. If that were fixed, Andy's theoretical problem would also be fixed - having a decimal here wouldn't matter.

@rohany would you mind creating an issue around no-opping primary key changes when nothing changes?
