### ISSUE TITLE
sql: TestLogic/fakedist-disk/aggregate/string_agg is flaky

### ISSUE THREAD

**Issue by lucy-zhang** [cockroachdb/cockroach#45905]
Running `make stress TESTS='TestLogic' PKG=./pkg/sql/logictest TESTFLAGS='-config fakedist-disk -d testdata/logic_test/aggregate'` on c783185e39c3046e114e54ebe7df56da2291edfb produces:
```
            --- FAIL: TestLogic/fakedist-disk/aggregate/string_agg (0.61s)
                logic.go:1706:
                    testdata/logic_test/aggregate:2080: SELECT a, b, count(*) FROM ab RIGHT JOIN tab ON b=col2 GROUP BY a
                    expected:
                        NULL  NULL  4
                        4     7     2
                    but found (query options: "rowsort" -> ignore the following ordering of rows) :
                        NULL  NULL  2
                        NULL  NULL  2
                        4     7     2
```

**Comment by jordanlewis** [comment]
@asubiotto @yuzefovich PTAL

**Comment by yuzefovich** [comment]
I'll take a look.

**Comment by RaduBerinde** [comment]
FWIW I reproed with `COCKROACH_DISTSQL_LOG_PLAN=1`and the distsql plan [seems fine](https://cockroachdb.github.io/distsqlplan/decode.html#eJzMVWFr4kAQ_X6_YplPeqzobrS2gYK9YluLTUqMHOUIsjF7KthsbrPCleJ_P4wFG-vtJhfx-lGzb-fNzntvXiH9tQQbRv1h_9pHDKMQo6lYxar2tY5uPPcBsRB5g9s7H927AwcpFiLXQSG6RFOxpOjWc8eP6NsTYoAhFhF32DNPwf4BBDBQwGBBgCGRYsrTVMjNp9fs4CD6DXYLwyJOVmrzd4BhKiQH-xXUQi052OCzcMk9ziIumy3AEHHFFsvs-kQunpl86SkWAoZRwuLURo1mgyAWR4gioeZcpoDBXSkb9SgEawxipd6K7WqEL2jO0nn-9h6BYB1gSBWbcbDJGv8baesw6TznPcrliNIcUfpXort7VrGQEZc8yt0UbJCmIwe6vWPp_F4sYi6bnTw1_yXhNhr2b3zkjv2-lwkIMCz5T1XrkfqlXMzmqtaj9d2UcM_a63_Xm1VmCFezmeQzpoRsnn8YLYYr52niuP7EGQ-HGy6A4dodO_7Ec7-PavUPJ2i9kn7aFcaib46QYt2Nxg-TgeO_vXb-gLUbAME9C38wy66RznEbcURDJE3S3lfiwdpnudqkuAlJgeRoNkgji5jjxwU5rQvPTulCwxTeCfXis7mw3FgMLqT_0YW0uBNoESeQRnbu-EYoQbRt3psZz2xzku3mPOLipKe1bPeUljVM4b2qW5_Ns-XmYujO-iSb8wBNj6eJiFNeaC-2No3yaMa3r5KKlZzyRymmWZntTzfDZaEX8VRtv9Ltj0G8_bQhWBzcrQImhtKkBG9aDtytAiaG0nQf3XqPtnLg1j7Y0pZu619MD76oAiaG0m1t0x09uKMFk47-yc6q6FsPNuhbDzbpu6vt-lzf9HkVnejBBp3owSadXFTRCakUZQa0YdYGtDHMqqVZtTirlmdEH2jEkGikUqQZ0AatGtAmsZJyqRasv_wJAAD__1xwOcs).

**Comment by yuzefovich** [comment]
The issue seems to be reproducible only with `-disk` configs, so it's either `HashRouter` or `externalHashJoiner` to blame here.

**Comment by yuzefovich** [comment]
Actually, `colexec.hashAggregator` seems to be the culprit (if I comment out enabling hash aggregator with `auto` setting, then this issue doesn't repro). cc @Azhng
