### ISSUE TITLE
sql: improve data type coverage for Npgsql

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#45909]
**Is your feature request related to a problem? Please describe.**
Today, `Npgsql` supports a very limited set of types in CockroachDB. Aside from `INT8`, I was unable to find data types that work. Most of the time, I get the following error 
```
# https://www.npgsql.org/doc/faq.html
# Exception calling "GetValue" with "1" argument(s): "The field 'city' has a
# type currently unknown to Npgsql (OID 25). You can retrieve it as a string by
# marking it as unknown, please see the FAQ."
```
This is on the movr rides table where city is of type `VARCHAR`.

**Describe the solution you'd like**
Expand data type coverage.

**Describe alternatives you've considered**
There's another driver I was able to find `SimplySql` but it's too simplistic and adoption may be low.

**Additional context**

**Comment by jordanlewis** [comment]
OID 25 is the `TEXT` datatype. How could `npgsql` not support `TEXT`?

**Comment by dbist** [comment]
this is no longer valid
