### ISSUE TITLE
pq: restart transaction: TransactionRetryWithProtoRefreshError

### ISSUE THREAD

**Issue by lunny** [cockroachdb/cockroach#45921]
**Describe the problem**
When running tests on xorm for cockroach, ci ref: https://drone.gitea.com/xorm/xorm/806/1/18
It returns some errors here.

pq: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE): "sql txn" id=eaff4515 key=/Table/SystemConfigSpan/Start rw=true pri=0.03926172 stat=PENDING epo=0 ts=1583807082.585279592,1 orig=1583807082.304401305,0 min=1583807082.304401305,0 max=1583807082.304401305,0 wto=false seq=151

**To Reproduce**

What did you do? Describe in your own words.

I restarted the ci tests and it's gone.

If possible, provide steps to reproduce the behavior:

It seems it's randomly.

**Environment:**
 - CockroachDB version: docker cockroachdb/cockroach:v19.2.4
 - Server OS: CentOS / k8s / drone
 - Client app: xorm

**Additional context**
What was the impact?

**Comment by hazcod** [comment]
I see the same issue when encountering heavy db loads.

**Comment by jordanlewis** [comment]
These are expected and must be handled by the client. Take a look at our documentation on this: https://www.cockroachlabs.com/docs/stable/transactions.html#transaction-retries

Thanks!
