### ISSUE TITLE
make build error: cannot use result (type _Ctype_struct___1) as type _Ctype_struct___0 in argument to cSliceToUnsafeGoBytes

### ISSUE THREAD

**Issue by heidawei** [cockroachdb/cockroach#45922]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:
make build error: 

```
github.com/cockroachdb/cockroach/pkg/storage/engine
# github.com/cockroachdb/cockroach/pkg/storage/engine
pkg/storage/engine/rocksdb.go:2778:32: cannot use result (type _Ctype_struct___1) as type _Ctype_struct___0 in argument to cSliceToUnsafeGoBytes
make: *** [cockroach] Error 2
```

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
2. Send SQL ... / CLI command ...
3. Look at UI / log file / client app ...

**Expected behavior**

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version v19.2
 - Server OS: macos
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
What was the impact?
```
func cSliceToUnsafeGoBytes(s C.DBSlice) []byte {
	if s.data == nil {
		return nil
	}
	// Interpret the C pointer as a pointer to a Go array, then slice.
	return (*[MaxArrayLen]byte)(unsafe.Pointer(s.data))[:s.len:s.len]
}
......


func dbGetProto(
	rdb *C.DBEngine, key MVCCKey, msg protoutil.Message,
) (ok bool, keyBytes, valBytes int64, err error) {
	if len(key.Key) == 0 {
		err = emptyKeyError()
		return
	}
	var result C.DBString
	/*......................*/
	if msg != nil {
		// Make a byte slice that is backed by result.data. This slice
		// cannot live past the lifetime of this method, but we're only
		// using it to unmarshal the roachpb.
		data := cSliceToUnsafeGoBytes(result)
		err = protoutil.Unmarshal(data, msg)
	}
	C.free(unsafe.Pointer(result.data))
	keyBytes = int64(key.EncodedSize())
	valBytes = int64(result.len)
	return
}
```
In the func dbGetProto, the result is C.DBString not C.DBSlice !!!!

**Comment by heidawei** [comment]
golang env version is 1.14

**Comment by heidawei** [comment]
I use new function cStringToUnsafeGoBytes replace the cSliceToUnsafeGoBytes in dbGetProto
```
func cStringToUnsafeGoBytes(s C.DBString) []byte {
	if s.data == nil {
		return nil
	}
	// Interpret the C pointer as a pointer to a Go array, then slice.
	return (*[MaxArrayLen]byte)(unsafe.Pointer(s.data))[:s.len:s.len]
}
```
then make build successful

**Comment by petermattis** [comment]
New versions of Go can break existing releases of CRDB in both subtle and obvious ways. The breakage you are reporting is obvious. We're not aware of any other breakage with go1.14, but I would encourage you to build v19.2 with go1.13 especially if you are building binaries for production.

The specific problem you mentioned has already been fixed on master in https://github.com/cockroachdb/cockroach/pull/45560. We should probably backport the fix to 19.2 for developer convenience, but please strongly consider the advice above.

**Comment by petermattis** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/45967.

**Comment by irfansharif** [comment]
Peter, I ran into this in trying to git bisect a bug. Go versions breaking builds across SHAs makes me think we should be more diligent/particular about asserting that a specific version of Go is being used to compile a specific SHA. Is that a reasonable ask? I don't want to have to think about what version an external dependency is, on the host I'm building on, and Go itself is a dependency.

I'll file separately if you think it merits discussion.

**Comment by petermattis** [comment]
> Peter, I ran into this in trying to git bisect a bug. Go versions breaking builds across SHAs makes me think we should be more diligent/particular about asserting that a specific version of Go is being used to compile a specific SHA. Is that a reasonable ask? I don't want to have to think about what version an external dependency is, on the host I'm building on, and Go itself is a dependency.

We're reasonably good about adjusting the minimum go version in `build/go-version-check.sh` when we change something that requires a newer version of Go. We have no facility for a maximum version which would have been required here (new version of Go broke building old code). Do you have a thought on how that would work?

**Comment by irfansharif** [comment]
Why not just do the same in build/go-version-check.sh but for max versions? We already have IGNORE_GOVERS for folks looking to jump ahead. (Aside, I should probably invest in some setup to quickly change go versions on the fly on whatever host I'm on.)

**Comment by petermattis** [comment]
> Why not just do the same in build/go-version-check.sh but for max versions? We already have IGNORE_GOVERS for folks looking to jump ahead. (Aside, I should probably invest in some setup to quickly change go versions on the fly on whatever host I'm on.)

I think we had that at some point and then removed it. I can't recall the reason why, though it is probably recorded in git history somewhere.

**Comment by petermattis** [comment]
Pro-tip: I install different versions of go in `~/Development/go<vers>`. You can select between the versions using `make GO=~/Development/go<vers>/bin/go`.

**Comment by petermattis** [comment]
@irfansharif See https://github.com/cockroachdb/cockroach/pull/21426.
