### ISSUE TITLE
sql: support placeholders for identifiers

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#4597]
Example from #4582: `SHOW GRANTS ON DATABASE %s; SHOW TABLES FROM %s`

**Comment by knz** [comment]
It's a bit more complicated than that. Right not the entire infrastructure for placeholders assume they appear in the place of a constant SQL value. What you're requesting here is a placeholder that can take the place of arbitrary identifiers in non-expression contexts.  Are there real-world tools or ORMs that expect this to work?

cc @nvanbenschoten

**Comment by bdarnell** [comment]
The only tool I'm personally aware of that needs this is our own admin UI (as introduced in #4582) - we're currently relying on manual client-side escaping of database and table names. 

I think it would actually be good to make these identifiers more like real expressions (why not allow `SHOW GRANTS ON TABLE $1 || '.' || $2`?), but it's low priority if that's not easy to do or if it conflicts with the support for unquoted table names. 

When/if we support INFORMATION_SCHEMA, that would give us a way to use placeholders for this kind of thing, since INFORMATION_SCHEMA is accessed with ordinary select statements.

**Comment by spencerkimball** [comment]
@bdarnell I'm closing this in favor of #8270. If there's something missing there, captured here (I couldn't tell from a quick read), could you augment #8270, or else reopen this and clarify.
