### ISSUE TITLE
Move RBAC into the BSL

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#45980]
After discussing the issue with eng, docs, and sales, let's [RBAC](https://www.cockroachlabs.com/docs/stable/roles.html), in its entirety, into the BSL for 20.1. However, all functionality designed to integrate CockroachDB with SSO systems like Active Directory (via GSSAPI or LDAP) will be enterprise. 

The main driver for our push to make RBAC BSL was Postgres compatibility, which will make CockroachDB work with more tooling and patterns that developers have come to expect. 

cc @jordanlewis @knz @Amruta-Ranade @piyush-singh

**Comment by awoods187** [comment]
@nstewart could you share more detail about how this improves Postgres compatibility? Maybe an example or two?

**Comment by knz** [comment]
@awoods187 the change for pg compat is already done in 20.1 (ROLE and USER equivalence); Nate's request is about dropping the assymetric license requirement between CREATE ROLE and CREATE USER, which are now equivalent.

**Comment by knz** [comment]
@RichardJCai I think that's for you

**Comment by nstewart** [comment]
```The SQL standard defines the concepts of users and roles, but it regards them as distinct concepts and leaves all commands defining users to be specified by each database implementation. In PostgreSQL we have chosen to unify users and roles into a single kind of entity. Roles therefore have many more optional attributes than they do in the standard.```

https://www.postgresql.org/docs/8.1/sql-createrole.html

By having some interactions blocked behind the CCL, roles and users are no longer identical, and not compatible @awoods187
