### ISSUE TITLE
sql: allow floor function to operate on ints

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#45999]
In Postgres, we see this (the input is int, and the output seems to be decimal:
```
postgres> select floor(2);
+---------+
| floor   |
|---------|
| 2.0     |
+---------+
```
In CockroachDB we see this:
```
> select floor(2);
ERROR: unknown signature: floor(int)
SQLSTATE: 42883
```

**Comment by otan** [comment]
Another case for implicit casts!

We should make this work for now with float8 and int. Tagging as good first issue.

**Comment by abhishek20123g** [comment]
Like to take it shot. If no one else is working
