### ISSUE TITLE
sql: statement doesn't show up correctly in Sentry

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#45995]
I haven't been seeing the statement in Sentry issues lately. It either does not show up at all or it's some bogus `BEGIN TRANSACTION`. Here's an example (https://sentry.io/organizations/cockroach-labs/issues/1558608653/?project=164528&referrer=webhooks_plugin):
![image](https://user-images.githubusercontent.com/16544120/76445779-2e7c8700-6383-11ea-92d3-820856db6f97.png)
The stack trace for this issue clearly shows that we are running a non-trivial statement and not `BEGIN TRANSACTION`.

**Comment by jordanlewis** [comment]
I think this got fixed recently right?
