### ISSUE TITLE
Odd gob helper funcs.

### ISSUE THREAD

**Issue by sbunce** [cockroachdb/cockroach#460]
https://github.com/cockroachdb/cockroach/blob/master/util/encoding/encoding.go#L37

gob encoders are very expensive to create. In the intended use case (streaming) this doesn't matter much because it's only done once.  However, when making a new encoder per message the performance will be extremely poor.

I'd recommend removing these gob helper funcs. No one is depending on them yet.

**Comment by tschottdorf** [comment]
I think they're legacy code for the most part. Suggest to remove all of those that aren't used anywhere.

**Comment by petermattis** [comment]
I think the gossip code was using these functions. Agreed that they should be removed and that this was an inappropriate use of gob.
