### ISSUE TITLE
Cockroach DB should be robust to leap seconds.

### ISSUE THREAD

**Issue by wbl** [cockroachdb/cockroach#46011]
**Is your feature request related to a problem? Please describe.**

I run a public time service. As a result all our machines are synchronized to UTC. Unfortunately Cockroach DB doesn't handle leap seconds well, despite the possibility of using adjtimex to see what the TAI-UTC offset is even during a leap second. This makes running Cockroach DB on the machines difficult. We need to use the same machines for architectural reasons.

**Describe the solution you'd like**

Cockroach DB works correctly on machines synchronized with UTC, even during leap seconds, by reading the time through adjtimex, and basing the HLC on TAI.

**Describe alternatives you've considered**
https://xkcd.com/2266/ should explain why having public time services smear is controversial.

**Additional context**
The go trunk now exposes the return value from adjtimex, enabling detection of leapseconds.

Jira issue: CRDB-5109

**Comment by awoods187** [comment]
@otan what is your thought here?

**Comment by otan** [comment]
since the ask is on the HLCs, I'd defer this to KV.

**Comment by wbl** [comment]
An even easier approach is to use clock_gettime with CLOCK_TAI. I can configure that to be correctly set, and this avoids leapseconds entirely.
