### ISSUE TITLE
backup: avoid starvation by long-running queries

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#46016]
BACKUPs are usually run as periodic background tasks. Ideally, they don't interfere with foreground traffic, and foreground traffic doesn't interfere with them. One mechanism of interference is transaction conflicts. We typically advice running backups (which are read-only) slightly backdated (~10s) to avoid conflicting with any active transactions but we also say that it is _probably OK_ if you don't do this, since even if the BACKUP does hit some transactions and they slow it down, once the backup has been running for 10s, it'll be then be reading in the past.

We however where this doesn't work is when the cluster has very long running queries. If a mutation is running for a long time, it _will_ interfere with periodic BACKUPs which need to read after it started. This was recently observed in on a customer cluster that had been running a DELETE query for 5 days (!) and their daily backups started getting stuck.

As a background job, BACKUP would _usually_ prefer to wait an extra few seconds rather than interfere with foreground traffic but it is also very important that it does eventually complete. One option here could be to send BACKUP's ExportRequests initially with their current priority but add a timeout, and then re-send them with a higher priority if they do not initially complete.

**Comment by pbardea** [comment]
Addressed in https://github.com/cockroachdb/cockroach/pull/51624
