### ISSUE TITLE
sql: provide transaction start time and ID in SHOW QUERIES

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#46055]
**Is your feature request related to a problem? Please describe.**
It is often useful to discover long-running transactions. `SHOW QUERIES` will show running statements. It shows when that statement started. It would be valuable to additionally have the transaction ID and start time for the current statement.

**Comment by knz** [comment]
cc @rohany since you were working in that area recently

**Comment by rohany** [comment]
Sure, let me take a look.

**Comment by rohany** [comment]
@ajwerner just to double check, is the query ID displayed in the result right now not the transaction ID you mention here?

**Comment by rohany** [comment]
The start time is also already present in the output of `SHOW QUERIES` currently

**Comment by knz** [comment]
session id != query ID. I think we want both in SHOW QUERIES.

**Comment by ajwerner** [comment]
> The start time is also already present in the output of SHOW QUERIES currently

The start time is the statement start time I believe. This issue is about the transaction start time.

I believe the ID is also something different. It's generated here:

https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/conn_executor_exec.go#L73-L74

**Comment by ajwerner** [comment]
Not only is session id != query id. Session id != transaction id.
