### ISSUE TITLE
sql: make sqlmagic compatible with cockroachdb

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#46083]
**Describe the problem**
sqlmagic is a popular Jupyter extension allowing database access to Python via SqlAlchemy. 

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

1. Set up CockroachDB cluster in secure mode
2. Set up Jupyter Notebook or Jupyter Lab, on OSX `pip3 install jupyterlab`

```python
!pip3 install sqlalchemy cockroachdb pandas psycopg2-binary matplotlib
```

    Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.7/site-packages (1.3.15)
    Requirement already satisfied: cockroachdb in /usr/local/lib/python3.7/site-packages (0.3.3)
    Requirement already satisfied: pandas in /usr/local/lib/python3.7/site-packages (1.0.1)
    Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.7/site-packages (2.8.4)
    Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/site-packages (3.2.0)
    Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.7/site-packages (from pandas) (2.8.0)
    Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.7/site-packages (from pandas) (1.17.4)
    Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/site-packages (from pandas) (2019.3)
    Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/site-packages (from matplotlib) (1.1.0)
    Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/site-packages (from matplotlib) (2.4.5)
    Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/site-packages (from matplotlib) (0.10.0)
    Requirement already satisfied: six>=1.5 in /Users/artem/Library/Python/3.7/lib/python/site-packages (from python-dateutil>=2.6.1->pandas) (1.13.0)
    Requirement already satisfied: setuptools in /usr/local/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib) (42.0.2)

```python
import pandas as pd
from sqlalchemy.engine import create_engine
```

```python
# postgresql://root@Artems-MacBook-Pro.local:26257?sslcert=certs%2Fclient.root.crt&sslkey=certs%2Fclient.root.key&sslmode=verify-full&sslrootcert=certs%2Fca.crt
# https://raw.githubusercontent.com/cockroachdb/docs/master/_includes/v19.2/app/sqlalchemy-basic-sample.py
```

```python
secure_cluster = True           # Set to False for insecure clusters
connect_args = {}

if secure_cluster:
    connect_args = {
        'sslmode': 'require',
        'sslrootcert': '/Users/artem/Downloads/cockroach/certs/ca.crt',
        'sslkey': '/Users/artem/Downloads/cockroach/certs/client.root.key',
        'sslcert': '/Users/artem/Downloads/cockroach/certs/client.root.crt'
    }
else:
    connect_args = {'sslmode': 'disable'}

engine = create_engine(
    'cockroachdb://root@Artems-MacBook-Pro.local:26257/movr',
    connect_args=connect_args,
    echo=True                   # Log SQL queries to stdout
)
```

```python
df = pd.read_sql('select count(*) from vehicles', engine) 
```

    2020-03-13 11:57:48,675 INFO sqlalchemy.engine.base.Engine select current_schema()
    2020-03-13 11:57:48,675 INFO sqlalchemy.engine.base.Engine {}
    2020-03-13 11:57:48,678 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
    2020-03-13 11:57:48,679 INFO sqlalchemy.engine.base.Engine {}
    2020-03-13 11:57:48,680 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
    2020-03-13 11:57:48,680 INFO sqlalchemy.engine.base.Engine {}
    2020-03-13 11:57:48,681 INFO sqlalchemy.engine.base.Engine select version()
    2020-03-13 11:57:48,682 INFO sqlalchemy.engine.base.Engine {}
    2020-03-13 11:57:48,684 INFO sqlalchemy.engine.base.Engine SELECT table_name FROM information_schema.tables WHERE table_schema=%s
    2020-03-13 11:57:48,684 INFO sqlalchemy.engine.base.Engine ('public',)
    2020-03-13 11:57:48,687 INFO sqlalchemy.engine.base.Engine select count(*) from vehicles
    2020-03-13 11:57:48,687 INFO sqlalchemy.engine.base.Engine {}

```python
df.head()
```

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>count</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>15</td>
    </tr>
  </tbody>
</table>
</div>

```python
df = pd.read_sql('select city, count(city) from vehicles group by city', engine)
print(df)

```

    2020-03-13 11:57:58,472 INFO sqlalchemy.engine.base.Engine SELECT table_name FROM information_schema.tables WHERE table_schema=%s
    2020-03-13 11:57:58,473 INFO sqlalchemy.engine.base.Engine ('public',)
    2020-03-13 11:57:58,475 INFO sqlalchemy.engine.base.Engine select city, count(city) from vehicles group by city
    2020-03-13 11:57:58,476 INFO sqlalchemy.engine.base.Engine {}
                city  count
    0      amsterdam      2
    1         boston      2
    2    los angeles      1
    3       new york      2
    4          paris      2
    5           rome      1
    6  san francisco      2
    7        seattle      2
    8  washington dc      1

```python
#### Trying to make sqlmagic work with cockroach
```

```python
!pip3 install ipython-sql
```

    Requirement already satisfied: ipython-sql in /usr/local/lib/python3.7/site-packages (0.3.9)
    Requirement already satisfied: ipython>=1.0 in /usr/local/lib/python3.7/site-packages (from ipython-sql) (7.13.0)
    Requirement already satisfied: sqlparse in /usr/local/lib/python3.7/site-packages (from ipython-sql) (0.2.4)
    Requirement already satisfied: prettytable in /usr/local/lib/python3.7/site-packages (from ipython-sql) (0.7.2)
    Requirement already satisfied: sqlalchemy>=0.6.7 in /usr/local/lib/python3.7/site-packages (from ipython-sql) (1.3.15)
    Requirement already satisfied: ipython-genutils>=0.1.0 in /usr/local/lib/python3.7/site-packages (from ipython-sql) (0.2.0)
    Requirement already satisfied: six in /Users/artem/Library/Python/3.7/lib/python/site-packages (from ipython-sql) (1.13.0)
    Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (2.0.10)
    Requirement already satisfied: jedi>=0.10 in /usr/local/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (0.16.0)
    Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (4.3.3)
    Requirement already satisfied: pygments in /usr/local/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (2.5.2)
    Requirement already satisfied: pexpect; sys_platform != "win32" in /usr/local/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (4.8.0)
    Requirement already satisfied: decorator in /usr/local/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (4.4.2)
    Requirement already satisfied: backcall in /usr/local/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (0.1.0)
    Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (42.0.2)
    Requirement already satisfied: appnope; sys_platform == "darwin" in /usr/local/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (0.1.0)
    Requirement already satisfied: pickleshare in /usr/local/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (0.7.5)
    Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=1.0->ipython-sql) (0.1.7)
    Requirement already satisfied: parso>=0.5.2 in /usr/local/lib/python3.7/site-packages (from jedi>=0.10->ipython>=1.0->ipython-sql) (0.6.2)
    Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.7/site-packages (from pexpect; sys_platform != "win32"->ipython>=1.0->ipython-sql) (0.6.0)

```python
%lsmagic
```

    Available line magics:
    %alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode
    
    Available cell magics:
    %%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python  %%python2  %%python3  %%ruby  %%script  %%sh  %%svg  %%sx  %%system  %%time  %%timeit  %%writefile
    
    Automagic is ON, % prefix IS NOT needed for line magics.

```python
%load_ext sql
```

```python
# %sql $DATABASE_URL, connection_string
```

```python
%sql cockroachdb://maxroach:maxroach@Artems-MacBook-Pro.local:26257/movr, connect_args
```

    (psycopg2.errors.InvalidCatalogName) database "movr," does not exist
    
    (Background on this error at: http://sqlalche.me/e/f405)
    Connection info needed in SQLAlchemy format, example:
                   postgresql://username:password@hostname/dbname
                   or an existing connection: dict_keys([])

```python
print(connect_args)
```

    {'sslmode': 'require', 'sslrootcert': '/Users/artem/Downloads/cockroach/certs/ca.crt', 'sslkey': '/Users/artem/Downloads/cockroach/certs/client.root.key', 'sslcert': '/Users/artem/Downloads/cockroach/certs/client.root.crt'}

```python
# connect to cockroach using maxroach user
```

```python
secure_cluster = True           # Set to False for insecure clusters
connect_args = {}

if secure_cluster:
    connect_args = {
        'sslmode': 'verify-full',
        'sslrootcert': '/Users/artem/Downloads/cockroach/certs/ca.crt',
        'sslkey': '/Users/artem/Downloads/cockroach/certs/client.maxroach.key',
        'sslcert': '/Users/artem/Downloads/cockroach/certs/client.maxroach.crt'
    }
else:
    connect_args = {'sslmode': 'disable'}

engine = create_engine(
    'cockroachdb://maxroach@Artems-MacBook-Pro.local:26257/movr',
    connect_args=connect_args,
    echo=True                   # Log SQL queries to stdout
)
```

```python
# %sql cockroachdb://maxroach:maxroach@Artems-MacBook-Pro.local:26257/movr, connect_args
```

```python
%sql cockroachdb://maxroach:maxroach@Artems-MacBook-Pro.local:26257/movr, connect_args
```

    (psycopg2.errors.InvalidCatalogName) database "movr," does not exist
    
    (Background on this error at: http://sqlalche.me/e/f405)
    Connection info needed in SQLAlchemy format, example:
                   postgresql://username:password@hostname/dbname
                   or an existing connection: dict_keys([])

```python
print(connect_args)
```

    {'sslmode': 'verify-full', 'sslrootcert': '/Users/artem/Downloads/cockroach/certs/ca.crt', 'sslkey': '/Users/artem/Downloads/cockroach/certs/client.maxroach.key', 'sslcert': '/Users/artem/Downloads/cockroach/certs/client.maxroach.crt'}

```python
secure_cluster = True           # Set to False for insecure clusters
connect_args = {}

if secure_cluster:
    connect_args = {
        'sslmode': 'verify-full',
        'sslrootcert': '/Users/artem/Downloads/cockroach/certs/ca.crt',
        'sslkey': '/Users/artem/Downloads/cockroach/certs/client.maxroach.key',
        'sslcert': '/Users/artem/Downloads/cockroach/certs/client.maxroach.crt'
    }
else:
    connect_args = {'sslmode': 'disable'}

engine = create_engine(
    'postgresql+psycopg2://maxroach:maxroach@Artems-MacBook-Pro.local:26257/movr',
    connect_args=connect_args,
    echo=True                   # Log SQL queries to stdout
)
```

```python
%sql postgresql://maxroach@Artems-MacBook-Pro.local, engine 
```

    (psycopg2.OperationalError) could not connect to server: Connection refused
    	Is the server running on host "Artems-MacBook-Pro.local" (::1) and accepting
    	TCP/IP connections on port 5432?
    could not connect to server: Connection refused
    	Is the server running on host "Artems-MacBook-Pro.local" (127.0.0.1) and accepting
    	TCP/IP connections on port 5432?
    could not connect to server: Connection refused
    	Is the server running on host "Artems-MacBook-Pro.local" (fe80::1) and accepting
    	TCP/IP connections on port 5432?
    could not connect to server: Connection refused
    	Is the server running on host "Artems-MacBook-Pro.local" (10.0.4.89) and accepting
    	TCP/IP connections on port 5432?
    could not connect to server: Connection refused
    	Is the server running on host "Artems-MacBook-Pro.local" (fe80::10f5:42a1:1e1d:c40) and accepting
    	TCP/IP connections on port 5432?
    could not connect to server: No such file or directory
    	Is the server running locally and accepting
    	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
    
    (Background on this error at: http://sqlalche.me/e/e3q8)
    Connection info needed in SQLAlchemy format, example:
                   postgresql://username:password@hostname/dbname
                   or an existing connection: dict_keys([])

```python
%sql postgresql+psycopg2://user:password@host:port/dbname[user='maxroach'&password='maxroach'&host='Artems-MacBook-Pro.local'&port=26257&database='movr'&sslmode='require'&sslrootcert='/Users/artem/Downloads/cockroach/certs/ca.crt'&sslkey='/Users/artem/Downloads/cockroach/certs/client.maxroach.key'&sslcert='/Users/artem/Downloads/cockroach/certs/client.maxroach.crt']

```

    Connection info needed in SQLAlchemy format, example:
                   postgresql://username:password@hostname/dbname
                   or an existing connection: dict_keys([])
    invalid literal for int() with base 10: 'port'
    Connection info needed in SQLAlchemy format, example:
                   postgresql://username:password@hostname/dbname
                   or an existing connection: dict_keys([])

```python
%sql postgresql+psycopg2://user:password@host:port/dbname[?user='maxroach'&password='maxroach'&host='Artems-MacBook-Pro.local'&port=26257&database='movr'], engine

```

    Connection info needed in SQLAlchemy format, example:
                   postgresql://username:password@hostname/dbname
                   or an existing connection: dict_keys([])
    invalid literal for int() with base 10: 'port'
    Connection info needed in SQLAlchemy format, example:
                   postgresql://username:password@hostname/dbname
                   or an existing connection: dict_keys([])

```python

```

**Expected behavior**
ipython-sql aka sqlmagic should recognize cockroachdb as a valid postgres url and connect.

**Environment:**
 - CockroachDB version 19.2.4
 - Server OS: OSX Catalina
 - Client app [e.g. `cockroach sql`, jupyterlab]

**Additional context**
Customer is relying on this capability to edit their sql, fallback is relying on pandas dataframes.

Here's a quick [walk-through](https://blog.ervits.com/2020/02/running-cockroachdb-and-jupyter.html) with dataframes and set up scenario in insecure mode.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4922](https://cockroachdb.zendesk.com/agent/tickets/4922) has been linked to this issue.

**Comment by dbist** [comment]
Issue is invalid, it works with the following

```
%sql cockroachdb://maxroach:maxroach@Artems-MacBook-Pro.local:26257/movr?sslmode=verify-full&sslrootcert=/Users/artem/Downloads/cockroach/certs/ca.crt&sslkey=/Users/artem/Downloads/cockroach/certs/client.maxroach.key&sslcert=/Users/artem/Downloads/cockroach/certs/client.maxroach.crt
```
