### ISSUE TITLE
cli: `debug zip analyze` commands

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#46104]
We do a few repeated motions when scanning through a debug zip. We should expand it to incorporate some of them. One thing that comes top of mind is visualizing lease transfers through the system. We have the information at hand through recorded lease histories. Visualizing the raw data would make it easier to diagnose issues as they crop up.

Jira issue: CRDB-6327

**Comment by knz** [comment]
Related: #57710

**Comment by maryliag** [comment]
No longer a priority
