### ISSUE TITLE
kv: visualize timeseries dumps obtained from customers

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#46103]
Or something equivalent to that. It's time consuming to go back and forth with users asking for screenshots of specific charts over specific time ranges.

Epic CRDB-9295

Jira issue: CRDB-6328

**Comment by mattcrdb** [comment]
This would be super useful! One way I'd like to utilize this is ingest a dump of timeseries data and then recreate a UI that represents the customers timeseries data. That way I can infer things without relying on the customer to take the correct screenshots / half missing information.

**Comment by ajwerner** [comment]
The entire dump of timeseries data is almost certainly too big. That being said, I see no reason why we shouldn't capture downsampled data like would appear in the admin UI. Agree that it would be extremely useful. From there we could add some code to render the charts.

**Comment by bobvawter** [comment]
We're working a problem for an enterprise customer where their admin UI is very locked down.  This would be a super-helpful feature if we could get the graphs downsampled to present the last-minute, -hour, -day, and -week views after the fact.

**Comment by irfansharif** [comment]
@tbg has this wip branch attempting to do the same: https://github.com/cockroachdb/cockroach/pull/50432. Perhaps it's something we can prioritize during stability period @lunevalex.

**Comment by tbg** [comment]
Yes, I hope that I (or anyone really!) can push some version of this over the finish line. The idea is to include a snapshot of metrics in debug zip and to then use https://github.com/cockroachdb/cockroach/pull/50702 to visualize the metrics locally. To make this "really smooth", we'll want to auto-generate grafana dashboard .json's from `./pkg/ts/catalog`. With that, we're also in a really good place to help customers get set up with Grafana monitoring, as we'll have a programmatically maintained, linted, dashboard they can simply import.

There's a further thread I'm pulling here with aggregate metrics (the thing we introduced for multi-tenancy), where we can expose more fine-grained metrics than those that make it into internal timeseries on the prometheus endpoint. If we add useful new metrics her (stuff per app name, or client conn, etc) we can add a snap of that to debug zip as well and visualize it all the same. But it's less clear that there's a slam dunk here, it's interesting to think about though.

**Comment by awoods187** [comment]
I'm a heavy +1 on this. I watched a customer debug a problem yesterday. When they couldn't solve it, and our support couldn't immediately help them, it was painstaking to instruct them to capture these screenshots. It would have been way easier to say run debug.zip and have the confidence that we had everything needed to help them without making them manually capture this information. We need to invest in our tooling to efficiently handle escalation as our customers increase given that L2 won't be able to join every call.

**Comment by tbg** [comment]
Repurposing this issue to focus on locally browsing customer timeseries data.

My preferred approach for this is improving the [localmetrics](https://github.com/cockroachdb/cockroach/blob/master/scripts/localmetrics/README.md) setup by auto-generating dashboards from our timeseries catalog. (Lots of synergy with https://github.com/cockroachdb/cockroach/issues/46103, too).
We can also try to load this data into a local CRDB instance and then use the AdminUI. I think that is ultimately a worse approach since there's no synergy and there are lots of questions about how exactly this would work (plus, it's not relevant for production ever, rather there's potential for abuse).

**Comment by tbg** [comment]
@lunevalex pointed me at https://m3db.io/docs/quickstart/docker/, which at first glance seems to support ingesting a bunch of historical timeseries data ([prometheus does not](https://github.com/kube-reporting/metering-operator/issues/640)). This is prometheus compatible, so we could dockerize that plus a Grafana dashboard that could match that used by our SREs internally (ultimately I still think we ought to auto generate that from our metrics catalog, but that's a lower priority work item)
