### ISSUE TITLE
cli/demo: regression: `-e` is broken when used with `--empty`

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#46117]
On my machine:

```
% ./cockroach demo --empty -e 'select 1'
  ?column?
------------
         1
(1 row)
ERROR: dial tcp 127.0.0.1:27176: connect: connection refused
Failed running "demo"
```

This is a regression - it used to work properly in 19.2.

(With `sql -e`, there is no error)

cc @rohany @otan

**Comment by rohany** [comment]
The error looks like its coming from here -- https://github.com/cockroachdb/cockroach/blob/79c470b349a6a240e1ba0dc88b1d71d3bf18fdd2/pkg/cli/demo.go#L631

I think the database is being shut down with `-e` before the asynchronous license application gets to run, so it errors out when it cannot connect to the cluster.

We could
* not get a license when running with `-e`
* not error out when license application errors out
* ensure that license acquisition runs before cluster teardown

opinions?

**Comment by knz** [comment]
Intuitively, `-e` should process SQL as if it was typed on the prompt. In particular it feels a bit out-of-place to me that I can run licensed statements with the interactive prompt but not `-e`.

Maybe pull license acquisition before `-e` somehow?

**Comment by rohany** [comment]
Perhaps if the shell is not interactive then we run license acquisition synchronously?

**Comment by knz** [comment]
something like that, yes.

Maybe also with a CLI flag to disable license acquisition? I know we have an env var, but it's not readily available with `--help`. A flag would make it obvious that the feature is opt-out.
