### ISSUE TITLE
sql/pgwire: unit tests should check db name qualification

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#4612]
Found while investigating #4550.

Currently all Go acceptance tests connect without a db name (so no default db in session) and qualify the db name in all test queries. 

There should be some tests in here that connect with a test database pre-populated in the session and then check that queries with unqualified table names succeed.

**Comment by tamird** [comment]
Does this need to be an acceptance test? Seems like a unit test would
suffice.

**Comment by petermattis** [comment]
@dt Didn't you just fix this bug? Is the test coverage now sufficient?

**Comment by dt** [comment]
`TestPGWireDBName` checks that an unqualified table name is qualified using the db name that was used when connecting, so yeah.
