### ISSUE TITLE
ui: time dropdown on metrics page reverts to 6h randomly

### ISSUE THREAD

**Issue by dhartunian** [cockroachdb/cockroach#46145]
**Describe the problem**

When using the time dropdown on the metrics page, sometimes clicking on "10m" switches it to "6h". 

**To Reproduce**

A cluster was set up on roachprod with multiple nodes.
A dashboard was loaded with a timescale of "10m".
The URL was changed to point to a different node which preloaded the timescale dropdown to "10m" with the explicit times listed. Then when "10m" is selected from the dropdown again, the dropdown changes to say "6h".

**Expected behavior**
On the last step, the dropdown should just say "10m".

**Comment by knz** [comment]
Is this possibly related to #45127?

**Comment by dhartunian** [comment]
@knz don't think so. I think this is code that we recently added to infer the value of the dropdown from the URL instead of defaulting to 10m on page reload. The dropdown was also redesigned so a bunch of code changed.

**Comment by dhartunian** [comment]
@piyush-singh the solution that @elkmaster has implemented in his PR removes some functionality where a default timescale was set based on the age of the oldest node in the cluster. This was causing some issues with other code we had added to set the timescale based on query params in the URL.

Just want to confirm that we're good to ship with a 10m default timescale for all use cases instead of inferring from the oldest node.
