### ISSUE TITLE
distsql: tableReader is deciding stats collection too early

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#46164]
The `TableReader` decides whether to enable stats collection at construction time, based on a random context it find inside the `EvalCtx`. It'd be much better to decide at `Start()` time, based on the `ctx` passed to `Start()`. That's the context that the processor is supposed to be running in.
The code used to be fine, but then the decision of whether to collect stats changed in #26637; as far as I can tell there wasn't a good reason. I yelled about it at the time, but 
 nobody minded me: https://github.com/cockroachdb/cockroach/pull/26637#pullrequestreview-151565613
I want to yell again, because this thing has already caused problems; see #46132. I think in the meantime the pattern has spread to other procs.
It's just too fragile to rely on the `EvalCtx`, particularly before `Start().`

Jira issue: CRDB-5102

**Comment by RaduBerinde** [comment]
I agree that using the context in EvalCtx to drive the decision of collecting stats is bad. I am having a hard time making query diagnostics work correctly, especially when there are subqueries (#46132).
