### ISSUE TITLE
perf: Investigate TimestampCache growth

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#4616]
The `TimestampCache` is a central component in a `Replica` that maintains an `IntervalCache` of key ranges and the timestamps at which they were most recently read or written. Because of this, the cache is expected to grow fairly large as the replica services requests. With this said, the `TimestampCache` currently grows to account for about **50%** of in-use memory for a CockroachDB node at any given time, and the memory does not seem to clean up even in periods of inactivity. We should investigate this cache and look for areas where the memory footprint could be reduced, either by reducing allocations altogether or reducing the lifetime of allocated memory.

**Comment by nvanbenschoten** [comment]
In addition to the PR I just submitted, one interesting note about the `TimestampCache` (and all caches inheriting from `baseCache`) is that they evict lazily. This means that if any of these caches are grown to a large size and then suddenly become inactive completely, they will never shrink (even when most of their keys could be evicted) until they become active again. This explains why the `TimestampCache`'s memory does not seem to cleanup when cut off from all load. 

To test this, we can grow the `TimestampCache` to a large size by hitting it with a large number of queries for a while. Then, cut off all load from the system. The cache size will remain large indefinitely. If we then hit the system with even a single query (after the 10 second `MinTSCacheWindow `), the cache will immediately evict most/all of its keys and drop in size tremendously. 

Two possible remedy to this issue are to:
- evict "expired" items from the cache eagerly and asynchronously using a timer
- run a worker routine to periodically clean up the cache

Both of these solutions would fix the issue, but would also introduce overhead that doesn't seem worth it. In a real system, there will rarely to never be times when zero load is put on the `TimestampCache` so that it isn't forced to lazily cleanup. Furthermore, if there actually is a situation like this, I would argue that it doesn't really matter how much memory the `TimestampCache` is using, because it's not affecting anything anyway (especially at the much smaller size that #4699 promises to reduce the cache to).

**Comment by tschottdorf** [comment]
> run a worker routine to periodically clean up the cache

we already run a bunch of regular works, seems reasonable that one of them would do that as a kind of hygiene (and perhaps to save the next query from having to pay the overhead of a large cleanup).
