### ISSUE TITLE
experimental_enable_hash_sharded_indexes takes incorrect values

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/cockroach#46161]
**Describe the problem**

The `experimental_enable_hash_sharded_indexes` session variable only takes boolean values. When you set `true`, it shows `on`, and when you set `false`, it shows `off`. 

You should be able to set `on` and `off` directly.

```
root@127.0.0.1:59143/movr> SET experimental_enable_hash_sharded_indexes=on;
ERROR: parameter "experimental_enable_hash_sharded_indexes" requires a Boolean value
SQLSTATE: 22023
DETAIL: 'on' is a string
```

```
root@127.0.0.1:59143/movr> SET experimental_enable_hash_sharded_indexes=true;
SET

Time: 225µs
```
```
root@127.0.0.1:59143/movr> SHOW experimental_enable_hash_sharded_indexes;
  experimental_enable_hash_sharded_indexes
--------------------------------------------
  on
(1 row)

Time: 488µs
```

```
root@127.0.0.1:59143/movr> SET experimental_enable_hash_sharded_indexes=off;
ERROR: parameter "experimental_enable_hash_sharded_indexes" requires a Boolean value
SQLSTATE: 22023
DETAIL: 'off' is a string
```

```
root@127.0.0.1:59143/movr> SET experimental_enable_hash_sharded_indexes=false;
SET

Time: 232µs
```

```
root@127.0.0.1:59143/movr> SHOW experimental_enable_hash_sharded_indexes;
  experimental_enable_hash_sharded_indexes
--------------------------------------------
  off
(1 row)
```

**Environment:**
 - CockroachDB version : [CockroachDB OSS v20.1.0-beta.2-846-ga94dfeb42c (x86_64-apple-darwin19.3.0, built 2020/03/16 18:08:45, go1.13.4)
 - Server OS: macOS
 - Client app: cockroach demo

**Comment by rohany** [comment]
This seems to affect `experimental_enable_temp_tables` as well.

**Comment by rohany** [comment]
Actually,  this is the case with nearly all of our cluster setttings!

**Comment by ericharmeling** [comment]
> Actually, this is the case with nearly all of our cluster setttings!

Ah. You're right. Never mind then. Closing this.
