### ISSUE TITLE
ui: statements page columns only sort per page

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#46173]
When sorting the statements page by any column, only the statements on the page are sorted. Instead, I expect all statements to be sorted by that column, including statements on other pages.

In a test cluster, sorting in descending order by latency, I can see the following on the first page:
<img width="1443" alt="image" src="https://user-images.githubusercontent.com/21692034/76806371-94b83e00-67b7-11ea-93b0-0ddd9ef16b84.png">

And on the second page, I can see latencies are still sorted, but the first value is a higher latency than the first value on the first page:

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/21692034/76806403-aef21c00-67b7-11ea-807b-c5f9d93c683d.png">

We should change this so that clicking a column header instead sorts globally on all statements.

**Comment by awoods187** [comment]
Nice find!
