### ISSUE TITLE
sql: hash join not present in telemetry 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#46188]
We don't have telemetry for hash joins (although we do have merge and lookup). We should add this for 20.1.

**Comment by RaduBerinde** [comment]
@awoods187 can you expand on this? We currently have telemetry for usage of hints (hash / merge/ lookup), e.g. `sql.plan.hints.hash-join`. I don't see anything else for merge/lookup.

**Comment by awoods187** [comment]
In the features table I can see:

1 | sql.plan.hints.hash-join
-- | --
2 | sql.plan.hints.lookup-join
3 | sql.plan.hints.merge-join
4 | sql.plan.interleaved-table-join
5 | sql.plan.lateral-join
6 | sql.plan.opt.node.anti-join
7 | sql.plan.opt.node.anti-join-apply
8 | sql.plan.opt.node.full-join
9 | sql.plan.opt.node.inner-join
10 | sql.plan.opt.node.inner-join-apply
11 | sql.plan.opt.node.left-join
12 | sql.plan.opt.node.left-join-apply
13 | sql.plan.opt.node.leftjoin
14 | sql.plan.opt.node.lookup-join
15 | sql.plan.opt.node.merge-join
16 | sql.plan.opt.node.right-join
17 | sql.plan.opt.node.semi-join
18 | sql.plan.opt.node.semi-join-apply
19 | sql.plan.opt.node.zigzag-join
20 | sql.plan.reorder-joins.set-limit-0
21 | sql.plan.reorder-joins.set-limit-10
22 | sql.plan.reorder-joins.set-limit-4

We have the hints telemetry but we don't have the basic usage telemetry for hash joins (and we do for merge and lookup)

**Comment by RaduBerinde** [comment]
Oh.. these are derived from the optimizer operator names. The hash join is `inner-join`.

**Comment by RaduBerinde** [comment]
This data is hard to work with though. The nodes for lookup and merge include outer joins, but for hash joins these are separated into `inner-join`, `left-join`, `right-join`, `full-join`.
Maybe we want to synthesize a more useful set of hints? We could have a set of counters for the algorithm (hash/merge/lookup/cross) and a set of counters for type (inner, left, anti, etc).

**Comment by awoods187** [comment]
yeah i like separating the counters into algorithm and type. I actually had thought they were already set up this way.

**Comment by RaduBerinde** [comment]
If I add those, I'd remove the `sql.plan.opt.node` counters for join nodes (I don't want to set too many such counters for perf reasons). Is that ok?
