### ISSUE TITLE
VALUES table expression malfunctions with MAX

### ISSUE THREAD

**Issue by mrigger** [cockroachdb/cockroach#46196]
Consider the following test case:
```sql
SELECT MAX(t0.c0) FROM (VALUES (NULL), (NULL)) t0(c0); -- expected: {NULL}, actual: {NULL, NULL}
```
Unexpectedly, the query returns two rows, rather than one. This bug seems to occur only when a VALUES expression contains `NULL` values only.

**Comment by andy-kimball** [comment]
Looking at optsteps, I think this may be an optbuilder agg issue.
