### ISSUE TITLE
util/hlc: support VM node to node migration

### ISSUE THREAD

**Issue by darinpp** [cockroachdb/cockroach#46199]
A desirable feature of a CockroachDB running in a VM is to support migration of the VM from one node to another. When that happens however the clock of the VM at resume continue from the point at which the VM was suspended. This causes the VM's clock to lag from the wall clock by the amount of time that it takes to migrate the VM from one node to another. This makes the VM clock an inferior source of time. 

A better solution and the one that we will try to implement is to be able to access the physical host clock from the VM and use that as a source. 

There are several possible solutions. One is to increase the max offset between clocks on different nodes. This is currently set at 500ms. This however has undesirable performance effects in case of contented loads. 
Another possible solution is to limit the migrations to the cases where you can migrate the VM quickly. This will limit the cases when a VM can be migrated. It may also require a larger effort on the VM migration side.

**Comment by darinpp** [comment]
Here is a test of the performance comparison between using the regular `time.Now()` and accessing the PTP device that gives us access to the host clock.

```
[root@vs7-crdb-db-1 ~]# ./ptp_eval
Time per now() call 51ns
Time per walltime() call 23ns, nsec diff: 23
Time per nanotime() call 23ns, nsec diff: 23
Opened /dev/ptp0 with fd 3, mod_fd ffffffffffffffe3
CGO C.clock_gettime(/dev/ptp0) call 90ns, nsec diff: 90
Syscall gettime(/dev/ptp0) call 220ns, nsec diff: 220
CGO C.clock_gettime(CLOCK_REALTIME) call 90ns, nsec diff: 90
Syscall gettime(CLOCK_REALTIME) call 221ns, nsec diff: 221
CGO C.clock_gettime(CLOCK_MONOTONIC) call 90ns, nsec diff: 90
Syscall gettime(CLOCK_MONOTONIC) call 220ns, nsec diff: 220
```

**Comment by darinpp** [comment]
Fixed some issues with `clock_gettime` not reporting error when there is on. The time that it takes to access the `/dev/ptp0` is now correct and is 1.21us
```
[root@vs7-crdb-db-1 ~]# ./ptp_eval
Time per now() call 51ns
Time per walltime() call 23ns, nsec diff: 23
Time per nanotime() call 23ns, nsec diff: 23
Opened /dev/ptp0 with fd 3, mod_fd ffffffffffffffe3
CGO C.clock_gettime(/dev/ptp0) call 1.211µs, end now: 2020-03-19 16:14:07.074158454 -0400 EDT m=+6.549734352, end get time: 2020-03-19 16:14:07.074157391 -0400 EDT, nsec diff: 1211
CGO C.clock_gettime(CLOCK_REALTIME) call 91ns, end now: 2020-03-19 16:14:07.533420421 -0400 EDT m=+7.008996270, end get time: 2020-03-19 16:14:07.533420316 -0400 EDT, nsec diff: 91
CGO C.clock_gettime(CLOCK_MONOTONIC) call 90ns, end now: 2020-03-19 16:14:07.984919435 -0400 EDT m=+7.460495277, end get time: 1969-12-31 19:45:06.961970394 -0500 EST, nsec diff: 90
now is 2020-03-19 16:14:07.9849299 -0400 EDT m=+7.460505731

```

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[4841](https://cockroachdb.zendesk.com/agent/tickets/4841) has been linked to this issue.
