### ISSUE TITLE
sql: performance testing for temp tables

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#46213]
Edit KV to create a temp table on every transactions. Run for 5 minutes and see what happens.

**Comment by otan** [comment]
Used https://github.com/otan-cockroach/otan-scripts/tree/master/46213 to benchmark.

I created 10000 temp tables in each transaction, creating and destroying the temporary table each time. (results https://github.com/otan-cockroach/otan-scripts/blob/master/46213/output_10000_runs.txt). *Creating tables went from 180-190ms to ~240-310ms (pretty up and down) after 10000 tables.* (including RT to the server)

Is this what we expected @jordanlewis? If so, I'll consider this closed.

**Comment by otan** [comment]
as discussed in standup, this is expected. improvements come in 20.2, hopefully!
