### ISSUE TITLE
sql: `nodelocal upload` needs to require admin user

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#46222]
`upload` allows writing to arbitrary paths in the external io dir, and while that is "external", it is still shared between users, and allowing any SQL user to write to files that may be in use by another user could pose a problem in many deployments. Requiring admin privileges to write to the external io dir should mitigate this until we have some form of proper first-glass, non-external blob storage (which could have proper first-class for users).

**Comment by miretskiy** [comment]
export already verifies that the user belongs to the admin role:

pkg/sql/opt/optbuilder/export.go:22:    if err := b.catalog.RequireAdminRole(b.ctx, "EXPORT"); err != nil {
