### ISSUE TITLE
storage: replication error when not enough nodes to meet target

### ISSUE THREAD

**Issue by Linicks** [cockroachdb/cockroach#4623]
All,
  I have been getting some log errors when running the server with the --insecure switch.  I'm assuming the replication validation should be turned off when in this mode, or at least recognize that a single node without replication is valid.  Here are some details:

./cockroach start --stores=/data1 --insecure &

 build:     alpha.v1-362-g723805f @ 2016/02/24 18:32:31 (go1.6)

---------------------------- Errors Printed To Standard Out ---------------------------------------------
E0224 15:31:09.352275 6268 storage/queue.go:143  [replicate] 4 replicas failing with "no target store with any attributes matching  available, are you running enough nodes?"
E0224 15:41:09.351867 6268 storage/queue.go:143  [replicate] 4 replicas failing with "no target store with any attributes matching  available, are you running enough nodes?"
E0224 15:51:09.351733 6268 storage/queue.go:143  [replicate] 4 replicas failing with "no target store with any attributes matching  available, are you running enough nodes?"
E0224 16:01:09.351981 6268 storage/queue.go:143  [replicate] 4 replicas failing with "no target store with any attributes matching  available, are you running enough nodes?"
E0224 16:11:09.351463 6268 storage/queue.go:143  [replicate] 4 replicas failing with "no target store with any attributes matching  available, are you running enough nodes?"
E0224 16:21:09.351526 6268 storage/queue.go:143  [replicate] 4 replicas failing with "no target store with any attributes matching  available, are you running enough nodes?"
E0224 16:31:09.351814 6268 storage/queue.go:143  [replicate] 4 replicas failing with "no target store with any attributes matching  available, are you running enough nodes?"
E0224 16:41:09.351829 6268 storage/queue.go:143  [replicate] 4 replicas failing with "no target store with any attributes matching  available, are you running enough nodes?"
E0224 16:51:09.351441 6268 storage/queue.go:143  [replicate] 4 replicas failing with "no target store with any attributes matching  available, are you running enough nodes?"
E0224 17:01:09.351511 6268 storage/queue.go:143  [replicate] 4 replicas failing with "no target store with any attributes matching  available, are you running enough nodes?"
E0224 17:11:09.351756 6268 storage/queue.go:143  [replicate] 4 replicas failing with "no target store with any attributes matching  available, are you running enough nodes?"
E0224 17:21:09.351685 6268 storage/queue.go:143  [replicate] 4 replicas failing with "no target store with any attributes matching  available, are you running enough nodes?"
E0224 17:31:09.351459 6268 storage/queue.go:143  [replicate] 4 replicas failing with "no target store with any attributes matching  available, are you running enough nodes?"
E0224 17:41:09.351731 6268 storage/queue.go:143  [replicate] 4 replicas failing with "no target store with any attributes matching  available, are you running enough nodes?"
E0224 17:51:09.351454 6268 storage/queue.go:143  [replicate] 4 replicas failing with "no target store with any attributes matching  available, are you running enough nodes?"
E0224 18:01:09.351679 6268 storage/queue.go:143  [replicate] 4 replicas failing with "no target store with any attributes matching  available, are you running enough nodes?"

**Comment by petermattis** [comment]
This is an expected error. By default cockroach tries to replica ranges 3x, but you're only running a single node. We know how many nodes there are in the system though, we could either clarify the error or downgrade it to a warning when there are insufficient nodes in the system.

**Comment by bdarnell** [comment]
It's still a pretty severe error. If you had started three nodes but they couldn't talk to each other for some reason (firewalls, TLS certs, etc), this is how you would know. It probably doesn't need to be logged every 10 seconds, but just because this node hasn't been able to talk to anyone else doesn't mean that it's intended to be a single-node system. I'd still like to use an explicit command-line flag (`--dev`?) to disable this message instead of trying to guess that no other nodes are coming.

**Comment by petermattis** [comment]
Yeah, perhaps downgrading to a warning isn't wise. But it certainly looks possible to clarify the error: `unable to replicate range because there is only 1 node in the cluster`.

**Comment by Linicks** [comment]
"I'd still like to use an explicit command-line flag (--dev?) to disable this message instead of trying to guess that no other nodes are coming."

This would would be great when you just want to spin up a Cockroachdb instance to develop against, which is what I'm doing.  I wounder if it would be more clear to add a (--singlenode) option that would suppress the replication warnings, etc,  for this use case.  I like the the idea that (--singlenode) is self describing, and would be an explicit startup option that would prevent the server from being in an error state.

**Comment by petermattis** [comment]
I'd like the error to indicate how many candidates there were. Something like:

```
0 of %d stores with any attributes matching []
```
