### ISSUE TITLE
application_name does not get honored with lib/pq in go

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#46266]
**Describe the problem**
`application_name` session property can be passed to url string and monitor the app-specific statements in the admin UI. Doing the same in go app results in `APP: (UNSET)` on the statements page. 

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

1. Set up CockroachDB cluster, my setup was secure.
2. `cockroach sql --url 'postgresql://maxroach@localhost:26257/bank?application_name=newapp&ssl=true&sslmode=require&sslrootcert=certs/ca.crt&sslkey=certs/client.maxroach.key&sslcert=certs/client.maxroach.crt'` will produce an app context called newapp, we can monitor it on the statements page.

![newapp](https://user-images.githubusercontent.com/461296/77006829-86922b00-6939-11ea-9fd0-25b5996fd85b.png)

3. Run a sample go app and notice the statements page to display the app name as unset, while we expect `fromgo`.

```
package main

import (
	"database/sql"
	"fmt"
	"log"

	_ "github.com/lib/pq"
)

func main() {
	// Connect to the "bank" database.
	db, err := sql.Open("postgres",
		"postgresql://maxroach@localhost:26257/bank?application_name=fromgo&ssl=true&sslmode=require&sslrootcert=certs/ca.crt&sslkey=certs/client.maxroach.key&sslcert=certs/client.maxroach.crt")
	if err != nil {
		log.Fatal("error connecting to the database: ", err)
	}
	defer db.Close()

	// Create the "accounts" table.
	if _, err := db.Exec(
		"CREATE TABLE IF NOT EXISTS accounts (id INT PRIMARY KEY, balance INT)"); err != nil {
		log.Fatal(err)
	}

	// Insert two rows into the "accounts" table.
	if _, err := db.Exec(
		"INSERT INTO accounts (id, balance) VALUES (1, 1000), (2, 250)"); err != nil {
		log.Fatal(err)
	}

	// Print out the balances.
	rows, err := db.Query("SELECT id, balance FROM accounts")
	if err != nil {
		log.Fatal(err)
	}
	defer rows.Close()
	fmt.Println("Initial balances:")
	for rows.Next() {
		var id, balance int
		if err := rows.Scan(&id, &balance); err != nil {
			log.Fatal(err)
		}
		fmt.Printf("%d %d\n", id, balance)
	}
}
```

Look back at the image and see `(UNSET)` where `fromgo` should be present.

**Expected behavior**
A go application should produce a `fromgo` context.

**Environment:**
 - CockroachDB version 19.2.4
 - Server OS: OSX Catalina 10.15.3
 - Client app [e.g. `cockroach sql` and a go app]

**Additional context**
customer impact

**Comment by dbist** [comment]
@jordanlewis @awoods187 FYI

**Comment by dbist** [comment]
additionally, it'd be good to document `fallback_application_name` as well as `lib/pq` has that [documented](https://godoc.org/github.com/lib/pq) and ironically `application_name` is not. Though, application_name does work with `cockroach sql --url 'postgresql://maxroach@localhost:26257/bank?application_name=cli_new&ssl=true&sslmode=require&sslrootcert=certs/ca.crt&sslkey=certs/client.maxroach.key&sslcert=certs/client.maxroach.crt'` and `fallback_application_name` does not.
`cockroach sql --url 'postgresql://maxroach@localhost:26257/bank?fallback_application_name=fallback&ssl=true&sslmode=require&sslrootcert=certs/ca.crt&sslkey=certs/client.maxroach.key&sslcert=certs/client.maxroach.crt'`

**Comment by otan** [comment]
have you looked at doing the things suggested in https://stackoverflow.com/questions/42791005/how-to-set-application-name-in-golang-lib-pq-postgresql-driver ?

**Comment by otan** [comment]
you will need to patch lib/pq to fix this: https://github.com/lib/pq/blob/9eb3fc897d6fd97dd4aad3d0404b54e2f7cc56be/url.go#L32

**Comment by otan** [comment]
interesting, running the modified with the latest master gives me the correct application_name

```
 ✘ ⚙ otan@otan-cockroach-mbp  ~/go/src/test  go run .
fromgo
 ⚙ otan@otan-cockroach-mbp  ~/go/src/test  cat a.go
package main

import (
	"database/sql"
	"fmt"
	"log"

	_ "github.com/lib/pq"
)

func main() {
	// Connect to the "bank" database.
	db, err := sql.Open("postgres",
		"postgresql://root@localhost:26257/defaultdb?application_name=fromgo&sslmode=disable")
	if err != nil {
		log.Fatal("error connecting to the database: ", err)
	}
	defer db.Close()

	rows, err := db.Query("SELECT current_setting('application_name')")
	if err != nil {
		log.Fatal(err)
	}
	defer rows.Close()
	for rows.Next() {
		var setting string
		if err := rows.Scan(&setting); err != nil {
			log.Fatal(err)
		}
		fmt.Printf("%s\n", setting)
	}
}
```

which i also see here:

![image](https://user-images.githubusercontent.com/3646147/77010405-f0550980-6926-11ea-939e-5b18f9c8abd3.png)

**Comment by dbist** [comment]
@otan, actually your code produces the same result on 19.2.4. 

```
09:54 $ go run basic-sample-otan.go
fromgootan
```

`fallback_application_name` however is not recognized in CLI or GO.

```
2020/03/19 09:53:01 pq: current_setting(): unrecognized configuration parameter "fallback_application_name"
exit status 1
```
```
root@:26257/defaultdb> SELECT current_setting('fallback_application_name');
pq: current_setting(): unrecognized configuration parameter "fallback_application_name"
```

**Comment by dbist** [comment]
closing the issue as it works.

**Comment by dbist** [comment]
I investigated this and can't explain why `application_name` wouldn't propagate before. I rebuilt a cluster and retried again, the only difference is the order in which I've executed the following steps

```sql
CREATE USER IF NOT EXISTS maxroach WITH PASSWORD 'maxroach';
```
```sql
INSERT INTO system.role_members (role, member, "isAdmin") VALUES ('admin', 'maxroach', true);
```

So I wonder if client connection parameters do not propagate to statements page unless the user has admin rights? @knz @otan @robert-s-lee 

Also explains that @otan was able to make it work round 1 as he was running insecure. I was solely testing with secure cluster.

**Comment by knz** [comment]
> So I wonder if client connection parameters do not propagate to statements page unless the user has admin rights?

can you re-explain what the issue is from this angle?
If my reading is correct you're seeing 1) `application_name` **is properly honored** in the sql connection however 2) you don't see it back in the admin UI

is that correct? Can you detail what you see a bit more?

**Comment by dbist** [comment]
@knz the property is honored if I set up a secure cluster, add maxroach user with password, add him to isAdmin and then execute the code above. it also works with cockroach cli. My question is whether a non-admin user trying to execute a go program, cannot propagate an application_name client connection parameter. I will test my hypothesis.

**Comment by dbist** [comment]
my hypothesis is invalid, it works even for non-admin user.
