### ISSUE TITLE
sql: Investigate high retry rates in parallel pgbench benchmark

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#4631]
With [a small change to print](https://github.com/cockroachdb/cockroach/compare/master...dt:retryrate?expand=1
) attempt/success/failure counts in the parallel pgbench query test, it looks like we're retrying far more than expected. 
With `-cpu 2`:
```
total / success (%) / fail (%):	334	300 (89.82)	34 (10.18)
```
With `-cpu 8`:
```
total / success (%) / fail (%):	185	100 (54.05)	85 (45.95)
total / success (%) / fail (%):	606	300 (49.50)	306 (50.50)
```
and `-cpu 4`:
```
total / success (%) / fail (%):	141	100 (70.92)	41 (29.08)
total / success (%) / fail (%):	759	500 (65.88)	259 (34.12)
```

**Comment by dt** [comment]
Spotted in discussion of #4629.

**Comment by dt** [comment]
Oh, right: pgbench is a multi-table benchmark: there are 20k accounts, but only 10 teller rows and 1 branch row, and every batch hits a teller and a branch, so contention there is going to be high. Will be interesting to see how it ends up with more server-side retries though.

**Comment by tamird** [comment]
Aren't the tellers and branch immutable?

**Comment by petermattis** [comment]
This is the query that is being run:

```
BEGIN;
UPDATE pgbench_accounts SET abalance = abalance + %[1]d WHERE aid = %[2]d;
SELECT abalance FROM pgbench_accounts WHERE aid = %[2]d;
UPDATE pgbench_tellers SET tbalance = tbalance + %[1]d WHERE tid = %[3]d;
UPDATE pgbench_branches SET bbalance = bbalance + %[1]d WHERE bid = %[4]d;
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (%[3]d, %[4]d, %[2]d, %[1]d, CURRENT_TIMESTAMP);
COMMIT;
```

`tid` is in the range `[0,10)` and `bid` is always `1`.

**Comment by tamird** [comment]
ah, they have balances.
