### ISSUE TITLE
ui: add placeholder info to Network Latency page 

### ISSUE THREAD

**Issue by taroface** [cockroachdb/cockroach#46327]
The Network Latency page is blank when testing e.g. a local multi-node cluster. Ideally there would be an info box or other placeholder content here, linking to the docs page: https://www.cockroachlabs.com/docs/v20.1/admin-ui-network-latency-page.html

Note: This docs page covers the new Network Latency page and only exists for 20.1.

**Comment by piyush-singh** [comment]
cc @Annebirzin for visibility

**Comment by dhartunian** [comment]
# Testing Requirements

* Unit Tests
** A unit test with different renderings of the sidebar will be enough here
* Storybook
* Cypress
* Manual/Acceptance Testing

One concern I have about this feature is that this could put us in a situation where we have to wait for a payload from the backend before rendering the nav which might be a bad idea. Or in cases where info is unable to be fetched or malformed, the sidebar fails to load or be functional. A solution here should take that into account.

This solution may be more trouble than its worth even though it appears like a simple implementation on the surface. Rendering a blank page might end up being a better idea.

Up to the implementer to provide feedback regarding ☝️

**Comment by koorosh** [comment]
As an option, navigation sidebar can be rendered, and then hide "Network latency" menu in case there is only one Node in the cluster. The drawback is the flickering of navigation sidebar only for single node cluster.

@Annebirzin , what do you think about the following behavior?

Would it be more consistent to disable Network Latency menu instead of hiding it? and showing tooltip with an explanation of why it is disabled.

![out](https://user-images.githubusercontent.com/3106437/84775088-6bda5b80-afe7-11ea-9dce-884918bf1e60.gif)

**Comment by Annebirzin** [comment]
@koorosh @dhartunian I think hiding the network latency tab it is better than disabling. If there is still concern about errors when loading the menu, we could go with an empty state like this instead:

**Comment by koorosh** [comment]
My concern is about usability and UI. Hiding navigation menu cannot be done immediately on page load (as mentioned David, we need to wait for data from backend) and there are two options available:
- do not display Navigation sidebar until data from the backend is available. It will affect all users where sidebar appears with some delay.
- display all menu items initially and then hide 'Network Latency' menu if only one node in the cluster. It will affect only users with a single node but then menu appears and blicks once when menu item is hidden.

**Comment by Annebirzin** [comment]
I see, in that case I like the second option since it would would impact fewer users (and hopeful a 1 node setup is an edge case)

**Comment by koorosh** [comment]
Gotcha! Thanks @Annebirzin
