### ISSUE TITLE
ui: statement diagnostics should allow downloading of bundle

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#46331]
Currently the statement diagnostics page only allows downloading of the trace. I think it should download the bundle instead (which contains the trace). Bundles are already set up to be downloaded from  `/_admin/v1/stmtbundle/<statement diagnostics id>`.

**Comment by RaduBerinde** [comment]
Also a note that when this is working, these instructions to the user should be fixed to match the reality: https://github.com/cockroachdb/cockroach/blob/93cb2eb7cac9a8e918721b5f5cbdb0f4a0823f45/pkg/sql/explain_bundle.go#L74

**Comment by dhartunian** [comment]
@RaduBerinde one thought that came up as I was working was whether this download endpoint should require any authentication. I assume nothing in the bundle is anonymized so should we require some sort of login for download even via the SQL link? I can ensure that calls from the Admin UI pass through the auth token just as all other calls but I'm not sure what can be done in the SQL CLI.

**Comment by RaduBerinde** [comment]
I think it needs to be authenticated.. I was kind of hoping it was already, I'm not very familiar with the infrastructure. I had asked about this [here](https://github.com/cockroachdb/cockroach/pull/45735#issuecomment-594960958) when I introduced it.

**Comment by RaduBerinde** [comment]
FWIW I see a "a valid authentication cookie is required" if I just try to use a bundle link. Once I log into the UI it works. So maybe everything is good there?

**Comment by dhartunian** [comment]
Ahh seems obvious now, I hadn't tried it on a secure cluster. Thankyou!

**Comment by dhartunian** [comment]
@Annebirzin I tagged you on the Figma design for the second download button.

Here's an example of what I have on my end if that helps:
![Screen Shot 2020-03-31 at 10 03 26 AM](https://user-images.githubusercontent.com/986307/78035373-06a39200-7337-11ea-95c2-1058b40ae94b.png)

cc @piyush-singh

**Comment by Annebirzin** [comment]
@dhartunian to shorten the button names I think we could go with `Trace.json` and `Debug Bundle.zip`
[Figma link here](https://www.figma.com/file/C85d0mrz8dkNs7Nw5mcTmf/obsrv_admin-ui-statements?node-id=1236%3A2080)

Let me know if you think that works

**Comment by dhartunian** [comment]
@RaduBerinde @andreimatei any opinions on the naming of the links? This is what we've settled on for now.

![Screen Shot 2020-03-31 at 2 32 35 PM](https://user-images.githubusercontent.com/986307/78062324-855ef600-735c-11ea-9c4f-dad6542cb5af.png)

**Comment by piyush-singh** [comment]
There is an existing command `cockroach debug zip` which generates a file called `debug.zip`, we might want to go with something like `diagnostics.zip` to avoid confusion

**Comment by RaduBerinde** [comment]
I would consider making it `Bundle` instead of `Debug`. Looks great to me otherwise.

The filename when downloaded is something like `stmt-bundle-123456.zip`.

**Comment by andreimatei** [comment]
I think we should keep only the `Debug (.zip)` link, and get rid of the trace one. This is because the JSON is quite unreadable, and I'm gonna include another, more readable format in the bundle.

Btw, if the downloaded zip name would contain some prefix of the fingerprint and some date, I think it'd be great.

**Comment by piyush-singh** [comment]
I was just testing this on a roachprod instance of David's branch here and I was surprised to see a link to the JSON to download it when it is included in the bundle already. I'd be in favor of removing that link as well

**Comment by RaduBerinde** [comment]
> Btw, if the downloaded zip name would contain some prefix of the fingerprint and some date, I think it'd be great.

Filed #46880.

**Comment by dhartunian** [comment]
@anne really sorry for the churn on this but just want to give you a heads up that I'm reverting to the single-button layout that we had before. No rush on designs since we'll just have the older look w/ different button label. I assume single button should be flush right.

**Comment by dhartunian** [comment]
![Screen Shot 2020-04-02 at 11 49 42 AM](https://user-images.githubusercontent.com/986307/78269793-0c84a900-74d8-11ea-84dd-a2b8c4b0adfb.png)

![Screen Shot 2020-04-02 at 11 49 37 AM](https://user-images.githubusercontent.com/986307/78269805-10b0c680-74d8-11ea-9581-e47136a30957.png)

**Comment by Annebirzin** [comment]
@dhartunian no problem. Yep button can site flush right and looks good to me
