### ISSUE TITLE
ui: EXPLAIN ANALYZE (DEBUG) results don't show up

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#46330]
When a diagnostics bundle is generated with EXPLAIN BUNDLE (and not via a diagnostics request), the bundle does not show up in the "statement diagnostics history". Either
 - we should change the API to return all diagnostics in the `system_diagnostics` table
 - or I can change the EXPLAIN ANALYZE (DEBUG) code to also insert a "fake" request in the other table. @andreimatei what do you think about this?

To reproduce, just run `EXPLAIN ANALYZE (DEBUG) SELECT 1`.

**Comment by RaduBerinde** [comment]
I will give the second option a try since that won't involve changing the APIs.

**Comment by dhartunian** [comment]
@RaduBerinde I'll put up what I have on the server-side so far for you to take a look. I added an endpoint to get the diagnostics list by fingerprint.

**Comment by dhartunian** [comment]
@RaduBerinde please see #46754

**Comment by RaduBerinde** [comment]
@dhartunian sounds like there would need to be extra work on top of the API to make it work right? Adding the corresponding request is very easy from my side and if it makes the APIs and UI logic simpler I think we should do that. Opened #46759.

**Comment by dhartunian** [comment]
👍 sounds good, I will take a look.
