### ISSUE TITLE
opt: transform `unnest(ARRAY` to tuple

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#46357]
Currently, when a query contains an `unnest(ARRAY[])`, it seems like we keep it that way. I believe we could transform these cases to a tuple, which could result in more efficient plans. Consider the following (running 37640ca03c):
```
root@127.0.0.1:61987/movr> SHOW CREATE TABLE test;
  table_name |               create_statement
-------------+------------------------------------------------
  test       | CREATE TABLE test (
             |     x INT8 NOT NULL,
             |     CONSTRAINT "primary" PRIMARY KEY (x ASC),
             |     FAMILY "primary" (x)
             | )
(1 row)

Time: 85.472ms

root@127.0.0.1:61987/movr> EXPLAIN SELECT * FROM test WHERE x IN (SELECT unnest(ARRAY[1,2]));
              tree             |         field         |  description
-------------------------------+-----------------------+-----------------
                               | distributed           | true
                               | vectorized            | false
  render                       |                       |
   └── lookup-join             |                       |
        │                      | table                 | test@primary
        │                      | type                  | inner
        │                      | equality              | (unnest) = (x)
        │                      | equality cols are key |
        │                      | parallel              |
        └── distinct           |                       |
             │                 | distinct on           | unnest
             └── project set   |                       |
                  └── emptyrow |                       |
(13 rows)

Time: 2.955ms

root@127.0.0.1:61987/movr> EXPLAIN SELECT * FROM test WHERE x IN (1,2);
  tree |    field    | description
-------+-------------+---------------
       | distributed | false
       | vectorized  | false
  scan |             |
       | table       | test@primary
       | spans       | /1-/2/#
       | parallel    |
(6 rows)

Time: 556µs
```
The second query is more efficient because the `SELECT` is reduced to point lookups (which are also executed in parallel).

**Comment by asubiotto** [comment]
This has been seen in the wild.

**Comment by RaduBerinde** [comment]
This kind of transformation would be useful for TPCC - when inserting or updating multiple rows you could pass each column as an `ARRAY` (with the value being passed as an argument).

In this example, while I agree that the second plan is simpler and more efficient from a planning perspective, the execution should be very similar no? The lookup join should issue the lookups in parallel (because `equality cols are key`).

**Comment by andy-kimball** [comment]
I think a more general way of handling this is to map `unnest` of a constant array into a `VALUES` operator. Then the `IN` operator + `VALUES` operator would automatically be folded, even with today's rules.

**Comment by RaduBerinde** [comment]
Agreed, that's what I had in mind. That would also work with multiple columns, allowing you to specify a VALUES "matrix" by passing <numCols> arrays to the query.

**Comment by asubiotto** [comment]
> In this example, while I agree that the second plan is simpler and more efficient from a planning perspective, the execution should be very similar no? The lookup join should issue the lookups in parallel (because equality cols are key).

Yes, it should be. I didn't actually measure the execution performance of the plans in this example. The scenario which made me create this issue was a full table scan with the `unnest` applied as a filter afterwards. This was `v2.1.x` however, so maybe the current worst-case isn't so bad.

**Comment by RaduBerinde** [comment]
CC @DrewKimball - another possible project.
