### ISSUE TITLE
sql,bulk: missing memory accounting in stable releases

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#46367]
In many recent cases we've discovered edge cases where we do not have memory accounting and limiting in place which can lead to OOMs. Other than the obvious "use less memory", the usual fix for such cases is to instrument the code with memory usage accounting and then limit that usage, returning an error instead of crashing if we believe we'd exceed our configured limit.

However, currently significant amounts of our memory usage are unaccounted for -- i.e. we recommend --max-sql-mem and --cache set to 25% each, implying that other usage is nearly 50%. If/when we move any of that untracked usage into tracked and limited usage, that's potentially breaking behavior change: something that _was working_  may _stop working_: before because it simply used whatever memory it wanted, but because it now respects a limit, it fails (and requires a higher limit setting).

This makes adding accounting to stable releases in backports risky: we run the risk of something that users on that release had tested and qualified suddenly breaking, which is exactly the the opposite of what a stable release branch is supposed to to. This feels particularly true for our cloud users where our policy is to automatically deploy and run the latest patch release of their chosen stable release version -- if they choose e.g. 19.2 instead of 20.1 because that is what they tested with and know works for their usage patterns, that's a good indicated that they do _not_ want it to suddenly change behavior (i.e. a query that used to work start returning a "exceeded memory budget error").

On the other hand, every untracked and unlimited allocation is a potential OOM waiting to happen, and a potential crash is a serious bug. For a user whose usage of a feature which includes untracked/unlimited allocations does trigger OOMs, it'd *obviously* be far superior to start returning an error, rather than crashing.

This leaves us in a somewhat difficult position: if we identify untracked allocations that can lead to OOMs, we obviously _want_ to add tracking and limiting to prevent crashes, but doing so could change behavior for users who were using it happily as it was.

cc @joshimhoff @jordanlewis

**Comment by dt** [comment]
In discussing this earlier week, something that seemed significant to me is that _if we are about to crash due to an OOM_, then we _obviously_ would prefer to return an error instead, even if that is a behavior change. So while erring immediately on just exceeding the budget _where we previously didn't_ isn't always obviously right, it is if we think we'll OOM otherwise.

Maybe we could add a `--max-rss` or something flag that informs us of what the total mem usage of the process can be before we think we're likely to OOM, and then _when code is changed_ in a stable release to track allocations, it can choose to ignore new "budget exceeded" errors if the process RSS isn't near the limit. cc @jordanlewis for thoughts?

**Comment by petermattis** [comment]
> However, currently significant amounts of our memory usage are unaccounted for -- i.e. we recommend --max-sql-mem and --cache set to 25% each, implying that other usage is nearly 50%.

I think these recommendations reflect that inability for these settings to precisely control memory. The `--cache` setting is much more rigorous than the `--max-sql-mem` setting, yet even there I expect an overage. For the `--max-sql-mem` setting you have the added challenge of the Go GC. 

> This makes adding accounting to stable releases in backports risky: we run the risk of something that users on that release had tested and qualified suddenly breaking, which is exactly the the opposite of what a stable release branch is supposed to to.

Have we actually seen this happen in practice. I'm hesitant to add complexity for a theoretical problem. If the problem is not theoretical, but has been observed, it would be interesting to see the specifics.

> Maybe we could add a --max-rss or something flag that informs us of what the total mem usage of the process can be before we think we're likely to OOM, and then when code is changed in a stable release to track allocations, it can choose to ignore new "budget exceeded" errors if the process RSS isn't near the limit. cc @jordanlewis for thoughts?

My first response is this scares me. It feels like another fragile mechanism on top of an existing fragile mechanism. I haven't thought about this as much as you have, though. Perhaps I just need a bit more time to get comfortable.

**Comment by dt** [comment]
>Have we actually seen this happen in practice. 

IMPORT is pretty memory hungry and was originally untracked. When we added tracking (which we did _not_ do on a backport, but in a major release), it caught a lot of internal users off guard when something that _worked before_ stopped working (and required they change their memory limits). I

**Comment by jordanlewis** [comment]
I agree with Peter. I don't want to add any more tricky flags to memory accounting. It's just so easy to get wrong. We're better off slowly improving our estimates over time, IMO.

**Comment by dt** [comment]
To be clear, I completely agree with improving over time -- my concern is about _backporting_ those improvements, and causing behavior changes where something that previously "just worked" (as nearly half our memory usage does) stops working. CC has been vocal about wanting OOMs eliminated even in stable released branches, but moving everything into hard-limited accounting would be a significant behavior change.

**Comment by joshimhoff** [comment]
> CC has been vocal about wanting OOMs eliminated even in stable released branches, but moving everything into hard-limited accounting would be a significant behavior change.
 
Yup, if we can't fix OOMs via minor releases, I just don't see how running CC is going to stay sustainable, especially as the customer base grows.

**Comment by petermattis** [comment]
> To be clear, I completely agree with improving over time -- my concern is about backporting those improvements, and causing behavior changes in a release branch where something that previously "just worked" (as nearly half our memory usage does) stops working. That is a big no-no, and will make people distrust or avoid patch releases, defeating the whole point of stable release branches. CC has been vocal about wanting OOMs eliminated, even in stable released branches, but moving everything into hard-limited accounting would be a significant behavior change.

This is an interesting point. I don't have a good answer yet.

**Comment by knz** [comment]
xref #48595

anything that uses the SQL "internal executor" (SQL queries inside cockroachdb) currently systematically under-accounts. This is probably a big chunk of the missing usage attribution. I'd suggest poking at this.

**Comment by dt** [comment]
I think the answer here is that we'll add accounting to new releases and stable releases just are what they are.
