### ISSUE TITLE
server: simplify/rationalize the Drain API

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#46388]
Found while investigating  #45149.

- [Background information](#Background-information)
- [Description of the problem](#Description-of-the-problem)
- [Proposal](#Proposal)

<a name="Background-information">

### Background information

Currently the Drain API is a bit complicated. It takes 3 arguments:

- a shutdown bit to stop the process - this is trivial to understand (true: stop the process; false: keep the process running)

- a "on" list of "drain modes"
- a "off" list of "drain modes".

The word "drain mode" is really a misnomer. The better word is really "services".  
There are two possible "services": CLIENT (SQL clients) and LEASES (range leaseholders).

The semantics of the Drain RPC is:

1. for each service in the off list, restart the service.
2. for each service in the on list, stop the service.
3. if shutdown is requested, stop the process.

That looks deceptively simple, but the issue under discussion here is that it's really much too complicated. There is a **lot of flexibility in the RPC which has never been tested** nor exercised.

For context, the `cockroach quit` command (the *only* command using the Drain RPC to this date) sends 2 successive requests: 

1) `{shutdown:false, on:[], off:[]}`
2) `{shutdown:true, on:[CLIENT, LEASES], off:[]}`

(in that order).
What this does, according to the list above is:

- the first request checks that the server is able to accept RPCs. The Drain API gets a request with no arguments - it thus has nothing to do.
- the second request causes the API to 1) stop CLIENT 2) stop LEASES 3) stop the process, in that order.

Of note:

- `cockroach quit` never uses the `off` list. In fact, no crdb CLI command has ever used the off list.
- `cockroach quit` never uses a different `on` list. 

<a name="Description-of-the-problem">

### Description of the problem

We really don't know "what it means" to pass on:[CLIENT] without LEASES in DrainRequest. 

Neither on:[LEASES] without CLIENT. 

Or on:[CLIENT, CLIENT]. Or other combinations. There are no tests that exercise these combinations

We also have no idea whether it ever makes sense to pass an `off` list. Nobody's done it before and there are also no tests. 

It's likely some of these don't make sense, and it's more than likely that some of them would cause unwanted behavior.

<a name="Proposal">

### Proposal

1. remove the "Off" parameter in DrainRequest
2. conceptually remove the "On" parameter in DrainRequest, so that the Drain RPC endpoint only considers whether is empty vs non-empty (We need the latter for backward compatibility with `cockroach quit` from previous versions). *Always consider that a non-empty On list is equivalent to [CLIENT,LEASES]*.
3. if we ever want to do partial drains, e.g. a RPC to start refusing SQL clients but keep the distsql processors able to uses leases, propose that feature via a different RPC from Drain.

**Comment by knz** [comment]
cc @ajwerner @tbg @andreimatei @nvanbenschoten

**Comment by tbg** [comment]
I agree that none of this extra functionality deserves being kept around. Thanks for tackling this.

**Comment by knz** [comment]
Fixing this with an extra commit in #45149.

**Comment by andreimatei** [comment]
At first I liked the idea of getting rid of the `off` modes, cause they're indeed unused.
But now that I've got draining on my mind too, I'm thinking about the proposed multi-tenant architecture where we scale up and down the SQL gateways. In this architecture, it seems that we'll have situations where we started draining a gateway, but while draining the situation changes and we need a gateway again. In particular in the case of going from 1 gateway to 0 and then to 1 again. In such a case, it seems desirable to "undrain" the original gateway rather than spin another one up while the original one is draining. At least if it's not "too late".
So, I dunno, maybe at the SQL level at least there is a case for undraining. What do you think?

**Comment by knz** [comment]
What I think:

1) your way of thinking about this is not yet fully mature. You don't even know yet exactly what you need and how it would work. I would recommend you iterate a few times with some toy implementation and determine what you need.

2) *in the meantime* I am pretty sure that the implementation of the "off" modes in the Drain RPC is very wrong, and can get a node deadlocked (this is what happened when I tried it, and the reason why I filed this issue.)

3) *additionally*, if/when there is a new need for an "undrain" API, this should become a separate RPC instead of piggy-backing the Drain() entry point.

Therefore, I will proceed with #45149 which removes the "off" parameter to Drain() and you can separately experiment with _new_ code that does the right thing in a new Undrain() RPC. Note that I am not removing much code in #45149 so you'll wont see all your "building blocks" disappearing under you.

**Comment by tbg** [comment]
What Raphael said. We can introduce it when we find a need, but for now what we have was a liability and we're better off without it.
