### ISSUE TITLE
sql: UPSERT causes a decoding error in collated string column

### ISSUE THREAD

**Issue by mrigger** [cockroachdb/cockroach#46394]
Consider the following test case:

```sql
CREATE TABLE t0(c0 BOOL, c1 STRING COLLATE en);
CREATE INDEX ON t0(rowid, c1 DESC);
INSERT INTO t0(c1, rowid) VALUES('' COLLATE en, 0);
UPSERT INTO t0(rowid) VALUES (0), (1); -- error decoding 11 bytes: did not find marker 0x12 in buffer 0x13ff00ff00ff00ff00fffe
```
Unexpectedly, the `UPSERT` results in an error `error decoding 11 bytes: did not find marker 0x12 in buffer 0x13ff00ff00ff00ff00fffe`. When, for example, dropping column `c0`, the error does not occur.

I found this issue based on commit `322f83364bc0807c3147af0631cb7317c584ce43`.

**Comment by knz** [comment]
@mrigger can you provide the output of `cockroach version`? Thanks

cc @asubiotto @jordanlewis for triage.

**Comment by mrigger** [comment]
Here is the output of `cockroach version`:

```
Build Tag:    v20.1.0-beta.2-988-g322f83364b
Build Time:   2020/03/21 09:45:52
Distribution: CCL
Platform:     linux amd64 (x86_64-linux-gnu)
Go Version:   go1.13.4
C Compiler:   gcc 8.3.0
Build SHA-1:  322f83364bc0807c3147af0631cb7317c584ce43
Build Type:   development
```

**Comment by asubiotto** [comment]
@rohany could you take a look at this given your encoding/decoding expertise?
