### ISSUE TITLE
sql: INSERT ... DO NOTHING results in an error "UPSERT or INSERT...ON CONFLICT command cannot affect row a second time"

### ISSUE THREAD

**Issue by mrigger** [cockroachdb/cockroach#46395]
Consider the following test case:
```sql
CREATE TABLE t0(c0 INT UNIQUE DEFAULT 0);
INSERT INTO t0(rowid) VALUES (0), (1) ON CONFLICT (c0) DO NOTHING; -- UPSERT or INSERT...ON CONFLICT command cannot affect row a second time
```
Unexpectedly, the `INSERT` results in an error. When not relying on the `DEFAULT` value for `c0`, but explicitly inserting `0`, the statements work as expected:
```sql
CREATE TABLE t0(c0 INT UNIQUE);
INSERT INTO t0(c0, rowid) VALUES (0, 0), (0, 1) ON CONFLICT (c0) DO NOTHING; -- no error
```
The following, mostly equivalent statements result in the aforementioned error for CockroachDB, but execute without an error in PostgreSQL:

```sql
CREATE TABLE t0(c0 INT UNIQUE DEFAULT 0, c1 INT);
INSERT INTO t0(c1) VALUES (0), (1) ON CONFLICT (c0) DO NOTHING; -- UPSERT or INSERT...ON CONFLICT command cannot affect row a second time
```
I found this potential issue based on commit `322f83364bc0807c3147af0631cb7317c584ce43`.

**Comment by knz** [comment]
@mrigger can you provide the result of `cockroach version`? Thanks

@RaduBerinde  @andy-kimball this looks like the issue that was resolved recently. Can you confirm?

**Comment by mrigger** [comment]
Here is the output of `cockroach version`:

```
If am not mistaken, it should be the latest commit on `master`, and was also linked by GitHub. Here is the output of `cockroach version`:

Build Tag:    v20.1.0-beta.2-988-g322f83364b
Build Time:   2020/03/21 09:45:52
Distribution: CCL
Platform:     linux amd64 (x86_64-linux-gnu)
Go Version:   go1.13.4
C Compiler:   gcc 8.3.0
Build SHA-1:  322f83364bc0807c3147af0631cb7317c584ce43
Build Type:   development
```

**Comment by andy-kimball** [comment]
I did fix the first scenario. But I missed the third scenario. I'll put out a fix for that one as well.
