### ISSUE TITLE
NATURAL JOIN fails with "duplicate column name" on view

### ISSUE THREAD

**Issue by mrigger** [cockroachdb/cockroach#46403]
Consider the following statements:

```sql
CREATE TABLE t0(c0 INT);
CREATE VIEW v0(c0, c1) AS SELECT DISTINCT c0, c0 FROM t0;
SELECT * FROM v0 NATURAL JOIN t0; -- duplicate column name: "c1"
```

Unexpectedly, the `SELECT` results in an error. This bug seems to affect views that compute identical values. The statements execute without errors using PostgreSQL.

I found this bug based on commit 322f83364bc0807c3147af0631cb7317c584ce43.

**Comment by andy-kimball** [comment]
CC @RaduBerinde, this looks like an optbuilder issue
