### ISSUE TITLE
SCRUB fails for table that has a FOREIGN KEY constraint on a rowid column

### ISSUE THREAD

**Issue by mrigger** [cockroachdb/cockroach#46401]
Consider the following statements:

```sql
CREATE TABLE t0(c0 INT);
CREATE TABLE t1(c0 INT UNIQUE, FOREIGN KEY (c0) REFERENCES t0(rowid));
EXPERIMENTAL SCRUB table t1; -- scrub-fk: column "t.rowid" does not exist
```
Unexpectedly, the `SCRUB` command causes an error. I found this issue based on commit `322f83364bc0807c3147af0631cb7317c584ce43`.

Jira issue: CRDB-5090

**Comment by postamar** [comment]
Closing, can't reproduce.
