### ISSUE TITLE
ui: "Transactions" page over a "Statements" page

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#46429]
Because we aggregate metrics by statement fingerprints (as opposed to "transaction fingerprints", which is not a thing today), we destroy associated transaction metadata per statement. Since this is what's powering our UI, we have a "Statements" page with no way of relating individual statements to associated transactions (and therefore the other statements in said transaction). 

Naively this seems to be the wrong thing to be aggregating by. I would expect to find "Transactions" as a top level primitive, not "Statements". I expect users to think of statements as part of transactions, and be more interested in how a transaction is performing in aggregate, drilling down to a specific statement performance if needed. By having "Statements" as the top level, users can now only perform statement analysis across all transaction types in their app, which is kind of surprising to me.

**Comment by irfansharif** [comment]
Leaving it to Piyush to triage (or ignore).

**Comment by piyush-singh** [comment]
cc @awoods187 don't think we had an issue filed for this yet, but Irfan brought this up again today. Keeping this to track work going forward

**Comment by jordanlewis** [comment]
We did it! 🎉
