### ISSUE TITLE
ui: statements page default sort by time column not visible

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#46427]
It seems the UI page sorts by recency by default. It's not obvious that this is what's being sorted by, and if I change the sort order I'm not sure if I can reconstruct what was there before (short of relying on #45404 being yet unsolved). I'm also not sure that makes sense as a default to sort by, for any reasonable application the statements page is going to show a random assortment of queries at the point in time of the request. That doesn't seem entirely useful to me.

**Comment by irfansharif** [comment]
Assigning Piyush for triage.

**Comment by piyush-singh** [comment]
The sort behavior did change here as I don't think we display the old "time" column any more (which was execution count * mean latency, so total execution time). I'd prefer us to sort using an existing column on the page, latency seems like the next most obvious choice. cc @Annebirzin

**Comment by irfansharif** [comment]
Uneducated opinion but I think execution count could be a sane default.
It's the probably surfaces the "most likely" statement anyone is looking
for.

**Comment by piyush-singh** [comment]
Let's go with execution count here to Irfan's point. Adding to release blockers because default sort behavior is not obvious at all today
