### ISSUE TITLE
ui,server: enable pain-free test-on-own-laptop user journey

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#46420]
Today it's hard to set up a secure cluster on a local machine for testing.

It is hard because a localhost-only server would present a localhost-only TLS cert, and [some OS/browser combinations have become very agressive at preventing dubious TLS certs](https://github.com/cockroachdb/docs/issues/6946) for good reasons.

In order to smoothen out the user journey for "testing on your own laptop", this issue proposes to introduce a new command-line flag, for example `--unencrypted-localhost-http` (but also see discussion below)

which, to summarize, enables the user to point their browser to `http://localhost:8080` (note `http://` and not `https://`) and get UI access without cert-related headaches.

This change is a sub-set of the more general approach described by #44842; the subset would be appropriate to back-port to 19.2.

### Discussion

We can approach this either:

1) by making `--unencrypted-localhost-http` **imply** `--http-addr=localhost` and disabling TLS for the http connection.

   In that approach:

   - pros: there's a single URL for all the HTTP endpoints (UI, debug, health etc)
   - cons: *all* the HTTP endpoints (incl debug, health etc) will have no TLS, so *scripts may need to be customized*
   - cons: it's not possible to access the UI from other machines

2) by making `--unencrypted-localhost-http` cause a **second listener** on `localhost`, *in addition* to the main TLS-enabled listener configured by `--http-addr`, using (presumably) a different TCP port.

   In that approach:

   - pros: the debug/health/status etc endpoints continue to use TLS as previously, which preserves compatibility with automation
   - cons: there's a separate URL to point the browser to, separate from that used by automation tools using debug/health etc). The UI URL would still be printed as `webui: http://localhost:xxxx` upon `cockroach start`. The "main" httpS URL would then be printed alongside as `http API: https://something:yyyy` alongside `webui:`.
   - cons: still not possible to access the UI from other machines

3) do not introduce a new flag, instead extend `--http-addr` to become a comma-delimited list: `--http-addr=localhost:8080,localhost:8081:notls` (**notice the localhost:8080:notls** at the end).

   In the first implementation, we'd support a maximum of 2 listeners (= either 1 or 2).
 
   In that approach:

   - pros: it's possible to have a single URL for both UI and APIs
   - pros: it's possible to have both TLS on non-localhost, and TLS on localhost, or both on localhost - with a suitable config, we get *both* browser happiness  and script happiness
   - pros: it's one of the 3 steps needed to complete #44842 so it moves our 20.2 roadmap further
   - cons: more complex implementation than the above
   - cons: (possibly) we need to explain why `--http-addr` supports this feature and not the other listen flags.

**Comment by knz** [comment]
@irfansharif that's the issue I'd like to rubber duck with you, if you want to look at it before we chat

@aaron-crl can you look at the proposed 3 alternative implementations and provide opinion

**Comment by knz** [comment]
@jseldess maybe you can also look at the various alternatives and provide feedback based on your understanding of UX.

**Comment by aaron-crl** [comment]
I favor (1) as it is least likely to lead to initial user confusion and between it and option (2) don't see a significant security delta. It's also most consistent with what I've experienced with other technologies getting started workflows where I expect everything lumped together to start with but services break out when deploying to prod.

(3) Feels like it adds far too much complexity for uncertain value.

**Comment by irfansharif** [comment]
I think (1) makes sense to me too.  "it's not possible to access the UI from other machines" is not a real concern I think for the "test-on-your-own-laptop" journey. Ditto for script corrections, given we'd only be advising this for a quick (light) first touch journey.

**Comment by jseldess** [comment]
(1) seems best to me as well. But I have a few questions:

- You mention `--listen-http-addr`. That flag doesn't exist. We have `--listen-addr` and `--http-addr`. Are you suggestion creating a new `--listen-http-addr` as well? Hope not, but just want to be sure. 
- I'd like to understand if the limitations you list matter to a typical user running a secure local cluster. We're optimizing for a quick first experience with this change, but I wonder if we'll be confusing a developer's local development experience. Do we think they run secure local clusters while building out the full range of their services, including integrations with those other HTTPs endpoints? Perhaps it'd be good to get a few perspectives from the field. @rkruze, @robert-s-lee, perhaps?
- In our Kubernetes deployment tutorials, we tell users to [port-forward from the local machine to one of the pods](https://www.cockroachlabs.com/docs/stable/orchestrate-cockroachdb-with-kubernetes.html#step-4-access-the-admin-ui). Will this change impact this workflow and, if so, how?

**Comment by knz** [comment]
> You mention --listen-http-addr. That flag doesn't exist. We have --listen-addr and --http-addr. 

I meant `--http-addr`.

> Do we think they run secure local clusters while building out the full range of their services, including integrations with those other HTTPs endpoints?

I don't know, but now that you phrase it this way it seems unlikely. I would imagine that someone developing a real apps will want to set up some cheap instance in the cloud whose network config is close to their eventual deployments. Probably that a laptop-only experiment is going to be just for a quick client compatibility test rather than operational deployment.

> we tell users to port-forward from the local machine to one of the pods. Will this change impact this workflow and, if so, how?

No that would not be impacted - a k8s deployment should probably not use the new flag and in that case the TLS config should remain as previously: the TLS certs must announce the public hostname of the k8s-hosted cluster.

**Comment by jseldess** [comment]
Thanks, @knz. I'll test a secure Kubernetes deployment real quick to confirm. Thanks also for your insights into broader impact on local dev experience. I still think it'd be good to hear from someone in the field on that, though.

**Comment by jseldess** [comment]
Confirming that our secure Kubernetes instructions work fine.

**Comment by jordanlewis** [comment]
@knz this broke the web ui for demo clusters :/ See #46550.

I think we should flip this - let's make `--insecure` the default but make sure `--secure` works.

**Comment by knz** [comment]
the bug is interesting but it means the problem is larger than just `cockroach demo`. "reverting the default" is not going to help anyone here :)

**Comment by knz** [comment]
fix is over here: #46577
