### ISSUE TITLE
sql: give users a way to wait for their schema changes to fully apply and expose errors

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#4646]
We run schema changes through two async steps: `SchemaChanger` callbacks that do backfills, and gossip which propagates new versions of the system config to nodes. Currently the user doesn't have a good way to wait for either of these to be completed, or to get errors from them. In some cases we block returning results to the user for a txn until the backfills have finished. This only works when all the statements in a txn doing a schema change are sent to the server in one batch. It will probably not work when we address #3274 and chunk backfills into multiple txns.

On the gossip side, there's a mechanism through which tests wait for gossip to have propagated a change back to the same node that's running the schema change (see `testingWaitForMetadata`). Again this mechanism only works when the txn is fully sent in one batch. No similar mechanism is exposed to clients.

We need to improve the story here.

Related issues:
- [x] #2985 
- [x] #4428
- [x] #3274
- [x] #3000
- [x] #2991

**Comment by vivekmenezes** [comment]
We now do have a jobs table that exposes errors from schema changes. If there are problems with what is visible on the jobs table we can open up separate issues for those.
