### ISSUE TITLE
Nodelocal: /self/ syntax no longer works after a failed IMPORT that references file with /self/ syntax

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#46513]
**Describe the problem**
If you use the `/self/` nodelocal syntax with an `IMPORT` command but your `IMPORT` command throws an error, subsequent attempts to use the `/self/` syntax to access the same file on that same connection errors out, but referencing the explicit node ID works fine

**To Reproduce**
1. Run an import referencing a file on `/self/` but make sure the command has an error (syntax, or having a null datapoint for a not null column)
2. Try that import command with the error fixed for the same file using the `/self/` syntax (it should error)
3. Try that import command with the node ID syntax for the same file (it should work)

**Expected behavior**
/self/ reference should continue to work despite the `IMPORT` error

**Environment:**
20.1 latest build

**Comment by adityamaru** [comment]
@mwang1026 I can't seem to reproduce this locally. I tried the following with a test-1.csv file containing `content,,`

```
cockroach nodelocal upload test.csv test/test-1.csv --insecure

root@:26257/defaultdb> import table test (id string primary key, name string NOT NULL) CSV DATA ('nodelocal://self/test/test-1.csv') with nullif='';
ERROR: nodelocal://self/test/test-1.csv: error parsing row 1: generate insert row: null value in column "name" violates not-null constraint (row: "[content ]")

root@:26257/defaultdb> import table test (id string primary key, name string) CSV DATA ('nodelocal://self/test/test-1.csv') with nullif='';
        job_id       |  status   | fraction_completed | rows | index_entries | bytes
---------------------+-----------+--------------------+------+---------------+--------
  563021538817966081 | succeeded |                  1 |    1 |             0 |    18
(1 row)

Time: 208.469ms

root@:26257/defaultdb> select * from test;
    id    | name
----------+-------
  content | NULL
(1 row)

Time: 17.02ms
```

I even tried it with a syntax error and it seems to be succeeding on the second correct import attempt. Let me know if I am missing something!

**Comment by mwang1026** [comment]
Ya. I think we might be able to close this one. David mentioned this this may just be something with the load balancer that AWS uses that isn't something we should necessarily solve for.
