### ISSUE TITLE
Quit not shutting down the server

### ISSUE THREAD

**Issue by Linicks** [cockroachdb/cockroach#4652]
All,
  When trying to use quit to stop the server I get the following error:

./cockroach quit
Error: shutdown node error: client/admin.go:144: failed to initialize https client: base/context.go:121: error setting up client TLS config: open certs/root.client.crt: no such file or directory
Failed running "quit"

The server was started with the following command:
./cockroach start --stores=/data1 --insecure &

**Comment by cuongdo** [comment]
Hi Nick,

Have you tried running the following?

./cockroach quit --insecure

(Note the --insecure parameter for the quit command)

**Comment by tamird** [comment]
You need to use `--insecure` when sending the quit.

**Comment by Linicks** [comment]
Tried it with the --insecure switch and it worked as expected.  Thanks for the clarification!  Since this doesn't seem to be a bug; I wounder if the error message should include something like "If running in insecure mode, use --insecure".  Of course the docs and help should also reflect this requirement when the time comes :)

**Comment by jseldess** [comment]
Added to docs with https://github.com/cockroachdb/docs/pull/85.

See https://www.cockroachlabs.com/docs/stop-a-node.html

**Comment by tamird** [comment]
I guess this is good to close.
