### ISSUE TITLE
ui: Statement diagnostics history, link to statement details page

### ISSUE THREAD

**Issue by Annebirzin** [cockroachdb/cockroach#46559]
- [ ] On the Statement Diagnostics History page, the statement description should link to the respective statement detail page

![Screen Shot 2020-03-24 at 12 54 15 PM](https://user-images.githubusercontent.com/51920721/77550945-0ebb8780-6e88-11ea-86da-95cf21dd6ab7.png)

**Comment by koorosh** [comment]
@Annebirzin , statements are periodically cleared as I understand (as `Last cleared` label states on Statements page) and they're not present in statements list.
But we preserve diagnostics for those statements. It means that we cannot navigate to cleared statements. Should we display these diagnostics at all or to display them without link?
What do you think?

**Comment by Annebirzin** [comment]
Ah yes that makes sense. In that case I think we should continue to display those diagnostics so users can still access the bundle, but the statement will not link to a details page. 

Question, do we display a tooltip on hover that shows the full statement fingerprint? Thinking that would be useful for the user to at least identify the statement. 

@piyush-singh

**Comment by koorosh** [comment]
> Question, do we display a tooltip on hover that shows the full statement fingerprint? Thinking that would be useful for the user to at least identify the statement.

Good point, will add tooltips as well! Thank you.

FYI: Linked PR has gif animation with first implementation:
https://github.com/cockroachdb/cockroach/pull/46923#issue-397584199
