### ISSUE TITLE
security: login to the webui does not work with cockroach demo

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#46550]
Now that Cockroach Demo runs in secure mode by default, I cannot login to the webui.
```SQL
./cockroach demo --nodes 3 --with-load
CREATE USER craig WITH PASSWORD 'cockroach';
CREATE USER jpointsman WITH PASSWORD 'Q7gc8rEdS';
root@127.0.0.1:59377/movr> show users;
   username  |  options   | member_of
-------------+------------+------------
  admin      | CREATEROLE | {}
  craig      |            | {}
  jpointsman |            | {}
  root       | CREATEROLE | {admin}
(4 rows)

Time: 64.55ms
```
However, I cannot log in to the webui:
![image](https://user-images.githubusercontent.com/22278911/77538473-31dd3b80-6e76-11ea-93f9-4a06d9af936b.png)

I see a brief flash (<0.5s) in which I can see the webui before it returns to the login page.

Build Tag:    v20.1.0-beta.2-1072-g6c3c5d4a9a
Build Time:   2020/03/25 12:43:24
Distribution: CCL
Platform:     darwin amd64 (x86_64-apple-darwin19.3.0)
Go Version:   go1.13.4
C Compiler:   4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.17)
Build SHA-1:  6c3c5d4a9a0b837538a558fa22dcd4ff712fd8f5
Build Type:   development

**Comment by knz** [comment]
woops thanks for finding this out (and yet another proof that our UI testing story is lacking)

**Comment by knz** [comment]
I found the problem, it's not specific to demo
