### ISSUE TITLE
sql: show tables doesn't show temp tables

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#46553]
Show tables doesn't show temp tables:
```SQL
./cockroach demo --nodes 3 --with-load --insecure
SET experimental_enable_temp_tables = 'on';
CREATE TEMP TABLE mytemp(c INT);
show tables;
          table_name
------------------------------
  promo_codes
  rides
  user_promo_codes
  users
  vehicle_location_histories
  vehicles
(6 rows)

select * from mytemp;
  c
-----
(0 rows)

Time: 8.394ms
```
I think we should show both the permanent and temporary tables in this view with a specification of the temp table (in case there is a permanent and temporary table with the same name).

Note, you can see temp tables if you specify pg_temp:
```SQL
show tables from pg_temp;
  table_name
--------------
  mytemp
(1 row)

Time: 2.755ms
```
Build Tag:    v20.1.0-beta.2-1072-g6c3c5d4a9a
Build Time:   2020/03/25 12:43:24
Distribution: CCL
Platform:     darwin amd64 (x86_64-apple-darwin19.3.0)
Go Version:   go1.13.4
C Compiler:   4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.17)
Build SHA-1:  6c3c5d4a9a0b837538a558fa22dcd4ff712fd8f5
Build Type:   development

**Comment by otan** [comment]
So the danger here is that public schemas and temp schemas can have the same table name, and being in both seems confusing. I think the correct thing to do is copy what the equivalent of SHOW TABLES does in psql / MySQL, and show the schema name too:

```
otan=# \d
                  List of relations
  Schema   |         Name         |   Type   | Owner
-----------+----------------------+----------+-------
 pg_temp_3 | a                    | table    | otan
 public    | ab_view              | view     | otan
 public    | ba_test              | table    | otan
 public    | geo_example          | table    | otan
 public    | geography_columns    | view     | otan
 public    | geometry_columns     | view     | otan
 public    | lobby                | table    | otan
 public    | nyc_streets          | table    | otan
 public    | nyc_streets2_gid_seq | sequence | otan
 public    | spatial_ref_sys      | table    | otan
 public    | time_comparison      | table    | otan
 public    | timetz_example       | table    | otan
 public    | view_test            | table    | otan
 public    | view_view_test       | view     | otan
```

this is pretty big for 20.1, so let's do this in 20.2. unassigning for now (unless you feel strongly that they should all display here)

**Comment by otan** [comment]
Intended fix: https://github.com/cockroachdb/cockroach/pull/46598

Reassigning to myself.
