### ISSUE TITLE
cli/sql: add run rand to cockroach demo and cockroach workload

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#46562]
Cockroach Demo nor Cockroach Workload can take advantage of the random data generator present in workload `workload run rand --table <their table> --db <their db>`. 

For example:
```SQL
andrewwoods@MacBook-Pro-3:~/go/src/github.com/cockroachdb/cockroach$ ./cockroach workload run --help
[experimental] run a workload's operations against a cluster

Usage:
  cockroach workload run [flags]
  cockroach workload run [command]

Available Commands:
  bank        [experimental] Bank models a set of accounts with currency balances
  kv          [experimental] KV reads and writes to keys spread randomly across the cluster.
  movr        [experimental] MovR is a fictional vehicle sharing company
  tpcc        [experimental] TPC-C simulates a transaction processing workload using a rich schema of multiple tables
  ycsb        [experimental] YCSB is the Yahoo! Cloud Serving Benchmark

Flags:
  -h, --help   help for run

Global Flags:
      --logtostderr Severity[=DEFAULT]   logs at or above this threshold go to stderr (default NONE)
      --no-color                         disable standard error log colorization
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging (significantly hurts performance)

Use "cockroach workload run [command] --help" for more information about a command.
```
We should add these capabilities to both demo and cockroach workload. 
Related to https://github.com/cockroachdb/cockroach/issues/44713

Jira issue: CRDB-5079

**Comment by rohany** [comment]
It might be interesting to hook this up as a command in demo -- 

```
root@127.0.0.1:52629/movr> \rand_fill_table <tablename> <num_rows>
```

**Comment by awoods187** [comment]
Yeah i like that idea a lot. My ideal workflow would look something like:
1. start demo
2. create a table
3. call a function that adds random data to the table using its schema
4. run queries/profit

**Comment by rohany** [comment]
Yeah, thats what I had in mind. I don't think adding workload rand run to demo would be useful, because you don't actually have tables to populate when starting the demo command with workload run.

**Comment by knz** [comment]
ok that's for 20.2 right?

**Comment by awoods187** [comment]
yeah i think so unless its trivially easy and super low risk.

**Comment by rohany** [comment]
Adding the demo command seems easy/low risk to me -- i'll put up a PR and see what people think.
