### ISSUE TITLE
ui: [bug] clicking "Activate" on a statement in statements page causes it to go to end of list

### ISSUE THREAD

**Issue by dhartunian** [cockroachdb/cockroach#46571]
When I click "activate" on a statement in the statements page it gets sorted to the bottom of the current page.

This should not happen and the statement should stay exactly where it is in the sorted order with the new status of "waiting for query".

Before clicking:
![Screen Shot 2020-03-25 at 11 44 05 AM](https://user-images.githubusercontent.com/986307/77555887-2bf35480-6e8e-11ea-90fb-f180ce5e7458.png)

After:
![Screen Shot 2020-03-25 at 11 44 11 AM](https://user-images.githubusercontent.com/986307/77555918-3281cc00-6e8e-11ea-8e10-0bdfadaa53c5.png)

(scroll to bottom)
![Screen Shot 2020-03-25 at 11 44 14 AM](https://user-images.githubusercontent.com/986307/77555955-3a417080-6e8e-11ea-8fd1-c356ac209924.png)

**Comment by koorosh** [comment]
@dhartunian , it looks like you have set sorting by `Diagnostics` column (with Activate buttons). That's is why it is get sorted after status is changed.

**Comment by dhartunian** [comment]
wow 🤦‍♂ . Thank you @koorosh! That makes a lot more sense.
