### ISSUE TITLE
V20.1.0-BETA.3 database page incorrectly filtering out statements

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#46584]
This statement:
![image](https://user-images.githubusercontent.com/894257/77578998-e2b3fc80-6eaf-11ea-9a69-cfeb32bda6c5.png)

Should show up here:
![image](https://user-images.githubusercontent.com/894257/77579013-ee072800-6eaf-11ea-9d8f-3f1d0f038d25.png)

**Comment by piyush-singh** [comment]
Adding in @knz's comment:

```

**Comment by dhartunian** [comment]
Closing this. Fixed by reverting the statements tab on the db page since we can't achieve clarity here. 20.2 will bring the server-side additions needed to make this possible.
