### ISSUE TITLE
sql: inserted data appears not being inserted after all

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#4660]
So here's the scenario:
```sql
create table mono (val int, sts bigint, node int, tb int)
insert into mono (val, sts, node, tb) values (-1, 0, -1, -1)
-- do 10 times:
   begin
      v := select max(val) from mono
      select * from mono where val = v
      n := select now()
      insert into mono (val, sts, node, tb) values (1 + v, n, 0, 0)
   commit
-- then at the end:
begin
select * from mono
commit
``` 

the INSERTs appear to work properly because I see `v` increase in value during the loop.
However the final SELECT always returns an empty set. I also observe an empty table if I query it from another client while this test is running.

Full network trace attached:  [error.txt](https://github.com/cockroachdb/cockroach/files/147223/error.txt)
Client and server running on same machine. You can see that all statements are first prepared and that insert uses RETURNING.  Not sure that's relevant.

**Comment by andreimatei** [comment]
multi-node? Are you doing the finals `SELECT` on a different connection? Skewed clocks?

**Comment by knz** [comment]
Nope, all on the same server, only 1 node in "cluster"

**Comment by knz** [comment]
Clarification: if I run the same test using the CLI client with `sql -e`, ie only execute without prepare (and simpler syntax, no RETURNING), the test works as expected.

**Comment by knz** [comment]
How to reproduce:
1. check out github.com/knz/jepsen
2. `cd jepsen/cockroachdb`
3. have a 1+ cluster ready somewhere in a VM as per the `README` in that dir (will not be used, but the test needs it to run)
4. edit `src/jepsen/cockroach.clj` and change `jdbc-mode` to `:cdb-local`. Optionally set `insecure` to `true` if you don't have certs set up (doesnt change test result)
5. (optionally) edit `test/jepsen/cockroach_test.clj` and reduce the number of nodes to make the test faster (note: the cluster is only set up for this test but not used; with `jdbc-mode` at `:cdb-local` only your local server is usde)
6. start a local server
7. run `lein test :only jepsen.cockroach-test/monotonic-test`

**Comment by knz** [comment]
NB: can't repro any more for now, blocked on https://github.com/cockroachdb/cockroach/issues/4656

**Comment by knz** [comment]
As suggested by @andreimatei I changed the test to:
```sql
create table mono (val int, sts bigint, node int, tb int)
insert into mono (val, sts, node, tb) values (-1, 0, -1, -1)
-- do 10 times:
   begin
      v := select max(val) from mono
      select * from mono where val = v
      n := select now()
      insert into mono (val, sts, node, tb) values (1 + v, n, 0, 0)
      select * from mono  --- THIS IS NEW
   commit
-- then at the end:
begin
      v := select max(val) from mono    -- NEW
      select * from mono where val = v      -- NEW
      n := select now()      -- NEW
      insert into mono (val, sts, node, tb) values (1 + v, n, 0, 0)       -- NEW
      select * from mono  -- as previously
commit
``` 

During the loop I see the table growing as a result of `select *`, as expected.
However the final transaction fails as the server crashes with the same panic trace as #4656 .

What is different between the last transactions and the 10 transactions before? There's a pause of 2 seconds between the end of the loop and the last transaction. Perhaps this pause is sufficient to trigger #4656?

**Comment by knz** [comment]
(all this while looking at #4036 )

**Comment by knz** [comment]
Cannot reproduce the error after upgrading to the latest master revision.
