### ISSUE TITLE
sql: TestNextRowInterleaved fails with small FastIntSet cutoff

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#46600]
Before every release, I run `make test` with a change to FastIntSet that forces most usage into the "large set mode". This catches bugs where the structure isn't used correctly - typically unwanted aliasing due to missing `Copy()` calls.

To repro, apply this diff:
```
--- a/pkg/util/fast_int_set.go
+++ b/pkg/util/fast_int_set.go
@@ -39,7 +39,7 @@ func MakeFastIntSet(vals ...int) FastIntSet {
 
 // We store bits for values smaller than this cutoff.
 // Note: this can be set to a smaller value, e.g. for testing.
-const smallCutoff = 64
+const smallCutoff = 2
```

```
--- FAIL: TestNextRowInterleaved (9.46s)
    --- FAIL: TestNextRowInterleaved/parent1-parent2-child1-grandchild1-grandgrandchild1-child2-ggc1_unique_idx-parent3 (0.00s)
        fetcher_test.go:986: for table grandgrandchild1@ expected 5 non-NULL values, got 4
    --- FAIL: TestNextRowInterleaved/parent1-child1-grandchild1-grandgrandchild1-child2-ggc1_unique_idx-parent3 (0.00s)
        fetcher_test.go:986: for table grandgrandchild1@ expected 5 non-NULL values, got 4
    --- FAIL: TestNextRowInterleaved/parent2-child1-grandchild1-grandgrandchild1-child2-ggc1_unique_idx-parent3 (0.00s)
        fetcher_test.go:986: for table grandgrandchild1@ expected 5 non-NULL values, got 4
    --- FAIL: TestNextRowInterleaved/parent1-parent2-grandchild1-grandgrandchild1-child2-ggc1_unique_idx-parent3 (0.00s)
        fetcher_test.go:986: for table grandgrandchild1@ expected 5 non-NULL values, got 4
    --- FAIL: TestNextRowInterleaved/parent1-grandchild1-grandgrandchild1-child2-ggc1_unique_idx-parent3 (0.00s)
        fetcher_test.go:986: for table grandgrandchild1@ expected 5 non-NULL values, got 4
    --- FAIL: TestNextRowInterleaved/parent2-grandchild1-grandgrandchild1-child2-ggc1_unique_idx-parent3 (0.00s)
...
```

**Comment by nvanbenschoten** [comment]
> Before every release, I run make test with a change to FastIntSet that forces most usage into the "large set mode". This catches bugs where the structure isn't used correctly - typically unwanted aliasing due to missing Copy() calls.

Is this something we should test more regularly? Perhaps we could use a different value for `smallCutoff` in race builds (`// +build race`)?

**Comment by RaduBerinde** [comment]
That's not a bad idea. I wish we had another test mode with extra checks that isn't race (which is terribly slow).

**Comment by petermattis** [comment]
Pebble uses an invariants mode for this, enabled by -tags invariants.
Slower than normal builds, much faster than race.

**Comment by RaduBerinde** [comment]
What is being run with that flag in CI? How about in nightlies?

**Comment by petermattis** [comment]
> What is being run with that flag in CI? How about in nightlies?

In Pebble, [`make test`](https://github.com/cockroachdb/pebble/blob/master/Makefile#L20) runs with the invariants build tag. In CI, we run `make test` both with and without the invariants flag. Pebble doesn't have nightly tests. We don't actually enable this build tag for any of the CRDB tests.

**Comment by nvanbenschoten** [comment]
If this is just about accidental aliasing due to value copying of `FastIntSet`, you might also want to look into whether we can mark the type with `util.NoCopy` and let static analysis handle all of this. I haven't looked at the uses of this type, so this may not be possible.

**Comment by RaduBerinde** [comment]
@jordanlewis I think we should investigate this ASAP in case it's something we really must fix for 20.1. Should be `git bisect`able.

**Comment by jordanlewis** [comment]
Thanks... I agree

**Comment by jordanlewis** [comment]
Ok, so this was broken even at `git merge-base master release-19.2`.

**Comment by jordanlewis** [comment]
@RaduBerinde do you have any tips for tracking down a problem like this? I'm struggling. I changed `FastIntSet` to have a `cutoff` member variable that you can set, so I can go around setting cutoffs individually on sets until I find one that triggers the problem, but I'm not able to find the right one...

**Comment by jordanlewis** [comment]
Nevermind, I figured it out. It was a problem with the test.
