### ISSUE TITLE
Setting SESSION AUTHORIZATION throws error

### ISSUE THREAD

**Issue by rishabhgupta131** [cockroachdb/cockroach#46601]
**Is your feature request related to a problem? Please describe.**
We are connecting to cockroachDB from our application using the one superuser all the times but we are also passing the logged in user to the DB to check for authorization. Now once we establish the connection using the superuser, we want to change the session user to the logged in user(in the application) so that all the queries getting performed, gets checked for the authorization of that particular user.

**Describe the solution you'd like**
We want something similar to postgres in terms of changing user authorizations in between a session.
Postgres reference: https://www.postgresql.org/docs/10/sql-set-session-authorization.html

**Describe alternatives you've considered**
SET SESSION AUTHORIZATION DEFAULT works but we dont want the authorization to be reset to root user. We want it to be changed to any specific user other than root.

**Additional context**
Support request thread: https://support.cockroachlabs.com/hc/en-us/requests/4974

**Comment by ajwerner** [comment]
duplicates https://github.com/cockroachdb/cockroach/issues/40283
