### ISSUE TITLE
sql: add unimplemented error for create index concurrently 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#46616]
As discussed in https://github.com/cockroachdb/cockroach/issues/46615, Postgres has a syntax for create index concurrently. We should add unimplemented errors with links to GitHub for this feature. We should also add a notice that hints that these schema migrations can be run without that syntax.
```SQL
CREATE INDEX CONCURRENTLY rides_vehicle ON rides (vehicle_city);
invalid syntax: statement ignored: at or near "rides_vehicle": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
CREATE INDEX CONCURRENTLY rides_vehicle ON rides (vehicle_city)
                          ^
HINT: try \h CREATE INDEX
```

**Comment by rohany** [comment]
Why do we want to throw an unimplemented here? Don't we support this behavior already?

**Comment by ajwerner** [comment]
Yeah agreed this should instead not error and just no-op. Our implementations are concurrent 😉

**Comment by awoods187** [comment]
This is a backup in case we don't make it a no-op as is described in (https://github.com/cockroachdb/cockroach/issues/46615).
