### ISSUE TITLE
sql: add unimplemented feature for INCLUDE

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#46618]
As discussed in https://github.com/cockroachdb/cockroach/issues/46617, Postgres has a syntax for INCLUDE. We should add unimplemented errors with links to GitHub for this feature. 
```SQL
CREATE UNIQUE INDEX rides_id ON rides (id) INCLUDE (rider_id);
invalid syntax: statement ignored: at or near "include": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
CREATE UNIQUE INDEX rides_id ON rides (id) INCLUDE (rider_id)
```

**Comment by rohany** [comment]
It seems like it would be easy to parse include as storing
