### ISSUE TITLE
kv: kvnemesis can thrash and livelock on multiple concurrent Range merges

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#46639]
When stressing `TestKVNemesisSingleNode` with a short timeout (2-5 minutes), it's easy to see the test time out. This appears to be due to thrashing within the Range merge transaction.

The Range merge transaction does not use the standard transaction retry mechanism (i.e. epochs). Instead, it uses [a completely separate transaction](https://github.com/cockroachdb/cockroach/blob/8fbad6ef84119a57c83376675dcc5c5a35eb590d/pkg/kv/kvserver/replica_command.go#L755) when restarting due to retry errors. This leaves room for thrashing and livelock if multiple transactions keep stepping on each other's toes.

```
make roachprod-stress PKG=./pkg/kv/kvnemesis TESTS=TestKVNemesisSingleNode TESTTIMEOUT=2m TESTFLAGS='-v -show-logs' STRESSFLAGS='-stderr -maxfails 1' CLUSTER=<cluster-name>
```

**Comment by nvanbenschoten** [comment]
I've seen two different sources of this thrashing: the [read](https://github.com/cockroachdb/cockroach/blob/b5abb6e7860ff79f0665e4092f8b6a5e0c1471a0/pkg/kv/kvserver/replica_command.go#L596)-modify-[write](https://github.com/cockroachdb/cockroach/blob/b5abb6e7860ff79f0665e4092f8b6a5e0c1471a0/pkg/kv/kvserver/replica_command.go#L672) operation on the LHS range descriptor key and the [read](https://github.com/cockroachdb/cockroach/blob/b5abb6e7860ff79f0665e4092f8b6a5e0c1471a0/pkg/kv/kvserver/replica_command.go#L614)-modify-[write](https://github.com/cockroachdb/cockroach/blob/b5abb6e7860ff79f0665e4092f8b6a5e0c1471a0/pkg/kv/kvserver/replica_command.go#L702) operation on the RHS range descriptor key.

In the presence of concurrent Range merges, the write of either of these range descriptors by one txn can be pushed into the future by the concurrent read of the descriptor by another txn. The AdminMerge txn [cannot tolerate](https://github.com/cockroachdb/cockroach/blob/b5abb6e7860ff79f0665e4092f8b6a5e0c1471a0/pkg/kv/kvserver/replica_command.go#L573) being pushed, so if this happens, it is forced to restart.

There are two ways we can address this. I have tested that both succeed in removing this as a source of test timeouts for `TestKVNemesisSingleNode`.
1. add a jittered delay before each txn retry. This probabilistically breaks the livelock scenario and eventually ensures that one of the merge txns is able to perform its read-modify-write operations without any other txn disrupting it.
2. use [locking reads](https://github.com/cockroachdb/cockroach/blob/f02101c18dbdfb0ae3337533d08eafb3a104299a/pkg/kv/txn.go#L471) on the range descriptor keys. Just like with SQL's `SELECT FOR UPDATE`, pessimistically acquiring locks during the reads ensures that other txns can't invalidate the read before the update is issued. We'd have to be careful when making this change because the AdminMerge txn is [deliberate](https://github.com/cockroachdb/cockroach/blob/b5abb6e7860ff79f0665e4092f8b6a5e0c1471a0/pkg/kv/kvserver/replica_command.go#L665) about where it places its txn record, but as things stand today, the record will end up in the correct place even with locking reads.

My current opinion on this is that we should go with option 1 for now because we're currently in the v20.1 release stability period. This option is more fragile and only helps up to a point (i.e. we'll still probably see livelock with 100s of concurrent txns), but it's also much less risky in the short term.

We should then switch to option 2 for all admin requests early in the v20.2 release cycle. This will fix the problem "for good" and will probably also benefit other admin requests. Waiting for option 2 also has the benefit of letting us avoid the question of mixed-version clusters.

A third option that hasn't been vetted is to do something completely different like https://github.com/cockroachdb/cockroach/issues/41392. Or maybe we could avoid that change if we switched to more aggressive locking during reads (option 2).

**Comment by nvanbenschoten** [comment]
@danhhz the other option to consider here is doing nothing for this release and, instead, limiting the concurrency of merges in kvnemesis. Do you have any thoughts about this?

**Comment by danhhz** [comment]
I think my ranked preference is 1) jitter 2) kvnemesis 3) locking reads. I agree that it's pretty late in the cycle to be making the locking reads change. I have jitter above kvnemesis because this is an issue that a customer theoretically could hit, even if it seems somewhat unlikely.

That said, I think I see a nice way to limit merge concurrency in kvnemesis. At one point, I had the workers hand back the Step they just performed into the Generator when getting the next one. This will also be necessary for later adding something like AddSSTable which needs guarantees that the keyspace is not concurrently being used, so it wouldn't just be for merges.

**Comment by nvanbenschoten** [comment]
> That said, I think I see a nice way to limit merge concurrency in kvnemesis. At one point, I had the workers hand back the Step they just performed into the Generator when getting the next one. This will also be necessary for later adding something like AddSSTable which needs guarantees that the keyspace is not concurrently being used, so it wouldn't just be for merges.

Do you mind spelling out this option in a little more detail? How would this help limit merge concurrency? Are you picturing using the Generator as a sort of semaphore for each of its operation types?

**Comment by danhhz** [comment]
> Are you picturing using the Generator as a sort of semaphore for each of its operation types?

Yes, exactly. The generator would keep an internal count of how many merge requests are outstanding. This would be incremented when it returns a merge operation, the applier would then execute this, then hand it back to RandStep as an argument when getting the next thing to execute. This would allow the Generator to decrement its outstanding merge count. If the number of outstanding merge requests is greater than some threshold, then merges will not be added to the allowed slice, preventing them from being selected.

**Comment by nvanbenschoten** [comment]
CI just hit this in https://github.com/cockroachdb/cockroach/issues/47672.

**Comment by sumeerbhola** [comment]
A testrace run of this timed out.
https://teamcity.cockroachdb.com/viewLog.html?buildId=2525419&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_Testrace

**Comment by nvanbenschoten** [comment]
I'm still seeing this occasionally. Now that `SELECT FOR UPDATE` has been around for a while, I think we should go with option 2 from https://github.com/cockroachdb/cockroach/issues/46639#issuecomment-604710827.

**Comment by nvanbenschoten** [comment]
Not yet fixed.
