### ISSUE TITLE
*: better debugging tools for OOMs

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#46654]
We periodically write out heap profiles based on some heuristics already but in practice, we often find that when a process is OOMKilled or OOMs itself, the most recent profile is too stale to "catch it in the act". Is there anything we can do better here?

How cheaply can we poll RSS or the cgroup memory pressure or OOM score or whatever? Is it feasible to have something polling often enough to catch a process on the path to an OOM before it is too late? Are there any fancy linux features we can use to hook into the OOM event? I have no idea what is possible here so just filing this in the hopes it nerdsnipes someone who does.

@ajwerner @vladdy

**Comment by petermattis** [comment]
Polling RSS is a system call. There is probably a proc file to poll system or cgroup memory pressure. https://askubuntu.com/questions/234292/warning-when-available-ram-approaches-zero suggests using `free`.

**Comment by petermattis** [comment]
Cgroups seem to have a memory pressure notification facility. https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt

```
11. Memory Pressure
...
The file memory.pressure_level is only used to setup an eventfd. To
register a notification, an application must:

- create an eventfd using eventfd(2);
- open memory.pressure_level;
- write string as "<event_fd> <fd of memory.pressure_level> <level[,mode]>"
  to cgroup.event_control.

Application will be notified through eventfd when memory pressure is at
the specific level (or higher). Read/write operations to
memory.pressure_level are no implemented.
```
