### ISSUE TITLE
storage:  replica_gc_queue cause the raft_enqueued_pending_queue blocked, making the cluster unavailable

### ISSUE THREAD

**Issue by llllash** [cockroachdb/cockroach#46665]
Cluster Info:
Nodes  28
Total Ranges 560000+

At some point, the cluster becomes unavailable.  After we set the 
"COCKROACH_SCAN_INTERVAL=60m" and "COCKROACH_SCAN_MIN_IDLE_TIME=1s" , the cluster available again after restart.  And then we reproduce the case in our test enviroment,
we found that: if the number of range is very large, after we restart the node. the replica_gc_queue cause the raft_enqueued_pending greatly increased and then cluster became unavalible.  

we trace the code:

```
pkg/storage/queue.go
func (bq *baseQueue) maybeAdd(ctx context.Context.....){
    ....

    if bq.needsRaftInitialized {
	repl.maybeInitializeRaftGroup(ctx)
    }
   ....
}
```

the function maybeInitializeRaftGroup() cause the problem if the number of range is very large. only the replicate_gc_queue needsRaftInitialized,
it maybe try to init many raft group and cause the some raft request can't be processed.

we try to change that make all the replica go to the replicate_gc_queue, and 
 determine if we need to handle it at replicate_gc_queue's 'process function'.

```
pkg/storage/replica_gc_queue.go
// process performs a consistent lookup on the range descriptor to see if we are
// still a member of the range.
func (rgcq *replicaGCQueue) process(
	ctx context.Context, repl *Replica, _ config.SystemConfig,
) error {

	if bq.needsRaftInitialized {
		repl.maybeInitializeRaftGroup(ctx)
	}

	if raftStatus := repl.RaftStatus(); raftStatus != nil {
		isCandidate = (raftStatus.SoftState.RaftState == raft.StateCandidate ||
			raftStatus.SoftState.RaftState == raft.StatePreCandidate)
		if isCandidate {
			...
		}
	} else {
		....
	}
```

i think this can control the spacing of Range InitializeRaftGroup which solves the problem above.

Is that right？
I don't understand why we InitializeRaftGroup before  function maybeAdd(). https://github.com/cockroachdb/cockroach/pull/32845

**Comment by llllash** [comment]
@tbg  could u tell me am I doing this right？  thanks !!!

**Comment by llllash** [comment]
@tbg @yuzefovich

**Comment by llllash** [comment]
https://forum.cockroachlabs.com/t/cluster-is-broken-after-upgrade-attempt-to-2-1-4/2429
https://github.com/cockroachdb/cockroach/issues/35063  

Other related cases

**Comment by knz** [comment]
@llllash thanks for your report. Unfortunately there's much too little information here to make progress. Before we can help you, you need to do the standard homework (we ask this from all our users):

1. what exact crdb version are you running
2. timeline of recent operator events on the cluster (upgrades, node restarts, node adds etc)
3. result of `cockroach debug zip` - we recommend that you run the `cockroach debug zip` using a binary executable from a recent version (e.g. 19.2 or 20.1 beta) even if your cluster is running an older version.

   Note that the `debug.zip` may contain some sensitive information in log files so if you prefer you can send this to us securely (ping me if needed)

Regardless of what you think about (3) we'll need a sample of the logs somehow, to find out what got stuck and when.

**Comment by tbg** [comment]
Cross-ref https://github.com/cockroachdb/cockroach/issues/35063

**Comment by lunevalex** [comment]
@llllash thank you for reporting this issue, we are cleaning up our github issues list and I am going to close this in favor of tracking this problem in #35063.
