### ISSUE TITLE
sql: wrong implementation of NULL predicate for row value expressions

### ISSUE THREAD

**Issue by lukaseder** [cockroachdb/cockroach#46675]
**Describe the problem**

It appears that the NULL predicate is not implemented correctly (or not at all?) for row value expressions.

**To Reproduce**

Run this query:

```sql
select a, b, 
  (a, b) is null, 
  (a, b) is not null,
  not ((a, b) is null),
  not ((a, b) is not null)
from (
  values (1, 1), (1, null), (null, 1), (null, null)
) as t (a, b)
```

And get the following, wrong result:

```
a|b|?column?|?column?|?column?|?column?|
-|-|--------|--------|--------|--------|
1|1|false   |true    |true    |false   |
1| |false   |true    |true    |false   |
 |1|false   |true    |true    |false   |
 | |false   |true    |true    |false   |
```

**Expected behavior**

It should either work as in the SQL standard (ISO/IEC 9075-2:2016(E)
8.8 &lt;null predicate>) / PostgreSQL:

```
a|b|?column?|?column?|?column?|?column?|
-|-|--------|--------|--------|--------|
1|1|false   |true    |true    |false   |
1| |false   |false   |true    |true    |
 |1|false   |false   |true    |true    |
 | |true    |false   |false   |true    |
```

Or raise an error

**Environment:**
 - CockroachDB version: CockroachDB CCL v19.2.5 (x86_64-unknown-linux-gnu, built 2020/03/16 18:27:12, go1.12.12)
 - Server OS: See above (using docker)
 - Client app: JDBC

**Comment by jordanlewis** [comment]
Thanks @lukaseder for the report - definitely a bug here.

**Comment by yuzefovich** [comment]
As it turns out, this seems not that easy to fix. The root of the problem, AFAIU, is that `IS NULL` behaves differently from `IS NOT DISTINCT FROM NULL` when the argument is a tuple [postgres docs](https://www.postgresql.org/docs/8.3/functions-comparison.html):
```
Note: If the expression is row-valued, then IS NULL is true when the row
expression itself is null or when all the row's fields are null, while IS NOT
NULL is true when the row expression itself is non-null and all the row's
fields are non-null.
```
However, in our comparison resolution we transform `IS` into `IS NOT DISTINCT FROM` and `IS NOT` into `IS DISTINCT FROM` which is incorrect for this particular case.

**Comment by lukaseder** [comment]
Yes, it behaves differently. As per ISO/IEC 9075-2:2016(E)
8.8 &lt;null predicate>

![image](https://user-images.githubusercontent.com/734593/78225295-451d8600-74ca-11ea-8891-e0027bb2c54f.png)

**Comment by yuzefovich** [comment]
By the way, we have an old issue (#12022) with the last known reproduction being exactly this bug. I have a feeling that that issue describes a bigger set of bugs, so I'm not closing that one as duplicate, but it'd be great to see whether that issue is, in fact, a superset of this issue.
