### ISSUE TITLE
Data distribution page isn't tying out with SHOW RANGES (V20.1.0-BETA.3)

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#46682]
**Describe the problem**
This is the data distribution page:
![image](https://user-images.githubusercontent.com/894257/77774625-c768fe80-7021-11ea-8ec4-2f89cb4f1857.png)

This is the output of SHOW RANGES for the rides table:
![image](https://user-images.githubusercontent.com/894257/77774662-d354c080-7021-11ea-9f48-85b5cafd4b92.png)

I don't see how these two tie out. The replicas in the rides table in the command line are from 1-9, but the distribution matrix shows 11, 14, and 15.

Not sure if this is a bug or I'm just reading the chart wrong.

**Comment by irfansharif** [comment]
The replicas column in the `SHOW RANGES` output lists the nodes the replicas are placed on. so n1-9. The distribution matrix is returning a count of the replicas per node.

**Comment by irfansharif** [comment]
It looks like we document how to read the `SHOW RANGES` view on https://www.cockroachlabs.com/docs/dev/show-ranges.html. The data distribution matrix, because it's an advanced debug page, doesn't seem to have been documented.

**Comment by nstewart** [comment]
I don't see how the count of replicas is so high for rides then. How do we get 14 replicas on n3 when according to show ranges there are should only be 4 replicas on node 3?

**Comment by irfansharif** [comment]
What was your `cockroach demo` setup? I can try looking into it.

**Comment by irfansharif** [comment]
Ok I tried `cockroach demo --geo-partitioned-replicas` (pretty useful, we should add other topologies too), the higher count for the debug page is including count of the indexes on the `rides` table as well. `SHOW RANGES FROM TABLE` only shows you the range layout for the table `rides`, not the indexes. Checkout `SHOW RANGES FROM INDEX rides_auto_index_fk_city_ref_users` if you want those.

**Comment by irfansharif** [comment]
Feel free to close this out if that answers your question. I would ask users to be looking at the Tables page (#/databases/tables) to get a range count (which does show the range count for not just the table, but the included indexes), not the advanced debug page. We should definitely surface this level of useful detail in the tables page, but I believe @piyush-singh is already tracking that elsewhere.

As for the confusing SHOW RANGES out, it wasn't clear to me at first either that it doesn't include data for the corresponding indexes. Perhaps that's a docs issue to call out. +cc @jseldess, @rmloveland.

**Comment by jseldess** [comment]
I _think_ the [`SHOW RANGES`](https://www.cockroachlabs.com/docs/v19.2/show-ranges.html#show-ranges-for-a-database) doc is actually pretty clear that it applies to a single index (primary by default). It would be ideal if there were a single command to show the ranges for all indexes of a table. Is that a reasonable request, @irfansharif? If so, I can open an issue.

In any case, we do need to document this UI page. However, in the past, this page did not represent partition-level distribution. For that, you needed to use SQL. Is that no longer the case?

**Comment by irfansharif** [comment]
>  It would be ideal if there were a single command to show the ranges for all indexes of a table. Is that a reasonable request, @irfansharif? If so, I can open an issue.

I do think this is a reasonable ask. It's good UX, users think of indexes as part of tables, not separate entities (even if that's how we store them internally.)

While I have you here, what do you think of `SHOW RANGES FOR`? I keep thinking that's what the command is, but it's FROM, and reads weird. Is this common elsewhere? I think we just cargo culted FROM from `SELECT [...] FROM [...]`. 

> In any case, we do need to document this UI page. However, in the past, this page did not represent partition-level distribution. For that, you needed to use SQL. Is that no longer the case?

It does represent partition-level distribution (and I think it has for some time now). It's also an advanced debug page, so I wasn't sure if it's something we typically documented (as they change without notice).

**Comment by jseldess** [comment]
Oh, it didn't show partitions in 19.2, I'm fairly certain, because I was going through this demo and tutorial several times and really want to be able to use it but couldn't: https://www.cockroachlabs.com/docs/v19.2/demo-low-latency-multi-region-deployment.html

Hmm, I think it's `SHOW RANGES FROM <TABLE> FOR <row>`, no?

**Comment by irfansharif** [comment]
> Hmm, I think it's SHOW RANGES FROM <TABLE> FOR <row>, no?

It is, but I was thinking out loud if whether the grammar in our SQL code be changed to so it is `SHOW RANGES _FOR_ <TABLE>` instead. It's not relevant to the rest of the discussion here, so ignore.

**Comment by nstewart** [comment]
Thank you for clarifying, @irfansharif !! 

Jesse if you are all set, feel free to close
