### ISSUE TITLE
kv: rangelog range should not be backpressurable

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#46683]
The rangelog table (`RangeEventTableID`, `/Table/13`) is [updated](https://github.com/cockroachdb/cockroach/blob/c395c442a2d35adeac695263781e7bdce45b6d98/pkg/kv/kvserver/replica_command.go#L209) when performing range splits. This means that splits depend on being able to write into the rangelog - even splits of the rangelog's own ranges. Because of this cyclical dependency, we should not be backpressuring writes to the rangelog's ranges, even if they exceed the backpressure size limit. If we did, we might get into a state where the rangelog is stuck and cannot split.

**Comment by irfansharif** [comment]
@TheSamHuang can't seem to assign this to you, I think it's got to do with adding you as a contributor to the crdb repo (onboarding should do that tomorrow).

--- 

We were thinking this would be a good place to start and get your feet wet. From elsewhere: 

> We have this keyspace used to record information about range boundaries. Because we treat it like any other range in the system, it’s subject to back pressure when there are too many writes. Typically when there are too many writes on a range, we split it, and record that information in the rangelog. When the rangelog itself splits, that too is recorded in the rangelog. Because of this circular dependency, and because the rangelog itself can be backpressured, it’s possible for us to get into a state where we’re attempting to split because there are too many writes per range, yet are unable to do so because we’re being backpressured.

Some code markers: we log place split events [here](https://github.com/cockroachdb/cockroach/blob/c84759be7cc799b80dd785e473e6e23f7dd50ea1/pkg/kv/kvserver/replica_command.go#L224-L227), more specifically [here](https://github.com/cockroachdb/cockroach/blob/c84759be7cc799b80dd785e473e6e23f7dd50ea1/pkg/kv/kvserver/log.go#L42). If you look at where that `system.rangelog` table is defined, you'll find the constructing key `keys.RangeEventTableID` (we'll come back to what to do with this in a bit): https://github.com/cockroachdb/cockroach/blob/c84759be7cc799b80dd785e473e6e23f7dd50ea1/pkg/sql/catalog/systemschema/system.go#L756-L757

To see where our code that knows about what to backpressure, and what not to, see:
https://github.com/cockroachdb/cockroach/blob/c84759be7cc799b80dd785e473e6e23f7dd50ea1/pkg/kv/kvserver/replica_backpressure.go#L74-L107

I think what we ultimately want here is to add a check to see if a given batch request's key span (accessed via `req.Header().Span()`) overlaps with the keyspan encompassing the rangelog table. To get a handle on the latter, we may want to expose that through the `pkg/keys` package. This is one relevant example of where we've done the same for another system table (I think we'd want to do the same but for `RangeEventTableID`): https://github.com/cockroachdb/cockroach/blob/c84759be7cc799b80dd785e473e6e23f7dd50ea1/pkg/keys/constants.go#L281-L285

That should let us avoid backpressuring writes to the rangelog table.

**Comment by TheSamHuang** [comment]
Got it - thanks, Irfan. I'll keep you posted on how things go!

**Comment by TheSamHuang** [comment]
Determined that not backpressuring the rangelog range is already handled by the `if ba.Txn != nil && ba.Txn.Name == splitTxnName` condition so no changes were necessary. See #54625 for more info.
