### ISSUE TITLE
server: rewrite telemetry tests

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#46730]
The telemetry tests in `pkg/server/updates_test.go` are very hard to work with which limits the testing area. These should be rewritten using a datadriven approach. We can separate the mock recorder in a package and use it to output a list of counters that changed; the actual tests could then be moved to more appropriate packages (e.g. sqltelemetry).

**Comment by otan** [comment]
<chime>
i was looking at doing something like kvtrace and SELECT the feature counts before/after a statement was executed from the crdb_internal.feature_counts table, and comparing that and giving the deltas, e.g.

```
query TD telemetrytrace(sql.schema.something, sql.schema.something_else)
CREATE TABLE a (a int)
----
sql.schema.something 1
sql.schema.something_else 2
# note other telemetry increment targets are ignored
````

your solution of having an entry point into a mock recorder sounds more clean though
</chime>

**Comment by RaduBerinde** [comment]
We converted part of the tests, I don't think there are any plans for work here any time soon.
