### ISSUE TITLE
kv: ranged intent resolution is not batched, regresses performance on TPC-C

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#46752]
Over the past few weeks, we've been tracking a performance regression in TPC-C of 4-5% that occurs when implicit SELECT FOR UPDATE is enabled (see `enable_implicit_select_for_update`).

One thing that became clear early in the investigation was that the total number of batches sent in the system rose by about 25% when running TPC-C with implicit SELECT FOR UPDATE enabled. This was surprising, as implicit SELECT FOR UPDATE is not supposed to cause the system to perform any extra work - we built it to only activate opportunistically when a scan was already going to be visiting a leaseholder to perform the row-fetch for an upcoming mutation. Using https://github.com/cockroachdb/cockroach/pull/46747, I was able to track down this increase in RPCs to a switch from `ResolveIntent` requests to `ResolveIntentRange` requests when implicit SELECT FOR UPDATE is in use. Remember that because SQL only currently issues ranged `Scan` requests and never point `Get` requests, implicit SFU is always acquiring ranged upgrade locks that overlap the point exclusive locks acquired by the following mutation, so we must release these with `ResolveIntentRange` requests.

The following graph demonstrates this effect:

<img width="744" alt="Screen Shot 2020-03-30 at 5 11 56 PM" src="https://user-images.githubusercontent.com/5438456/77962611-e5e12b00-72a9-11ea-9dfe-417b25e46ede.png">

The graph shows two runs of TPC-C, first with `sql.defaults.implicit_select_for_update.enabled` set to true (the default) and second with `sql.defaults.implicit_select_for_update.enabled` set to false. The top graph shows what we had already been seeing - with implicit SFU, we issue about 25% more batches (21k vs. 16k). The bottom graph is more interesting. It shows that with implicit SFU, we issue about 11k `ResolveIntent` requests and about 5k `ResolveIntentRange` requests. Without implicit SFU, we issue about 20k `ResolveIntent` requests and no `ResolveIntentRange` requests.

So aren't we issuing more batches without implicit SFU? The answer is no, because `ResolveIntent` requests are [batched together](https://github.com/cockroachdb/cockroach/blob/93cb2eb7cac9a8e918721b5f5cbdb0f4a0823f45/pkg/kv/kvserver/intentresolver/intent_resolver.go#L823) by the `IntentResolver`. So even though we actually issue more requests, these requests are issued in [batches of 100](https://github.com/cockroachdb/cockroach/blob/93cb2eb7cac9a8e918721b5f5cbdb0f4a0823f45/pkg/kv/kvserver/intentresolver/intent_resolver.go#L64). However, `ResolveIntentRange` requests are not batched together (see below), so each request is a separate batch. So these 5k `ResolveIntentRange` requests are exactly the missing 5k extra RPCs that we see with implicit SFU enabled.
 https://github.com/cockroachdb/cockroach/blob/93cb2eb7cac9a8e918721b5f5cbdb0f4a0823f45/pkg/kv/kvserver/intentresolver/intent_resolver.go#L839-L841

This explains the modest regression in TPC-C performance and indicates that if we can lift this restriction on intent resolution batching, we should be able to close the gap.

**Comment by ajwerner** [comment]
@nvanbenschoten are you planning on addressing this?

**Comment by nvanbenschoten** [comment]
Yes, I'm going to look into addressing it. I'm putting together a WIP fix now and I'd be interested in running it by you to see whether you like it. The high-level idea is to:
- make the BatchRequest.Header used by `requestbatcher.Batcher` configurable
- update `requestbatcher.Batcher` to support paginated results
- give `IntentResolver` a separate `requestbatcher.Batcher` to use for `ResolveIntentRange` requests

Does that line up with what you were thinking? I'm hoping to be able to verify that the fix does in fact resolve the regression in the next hour or so 🤞

**Comment by ajwerner** [comment]
I think the high-level pitch is reasonable. 

Can you help me understand the header bits a bit better. Does ResolveIntentRange use a transaction in a header? If so would we only be batching resolution for a single transaction?

Most of the time we won't actually be paginating, we just need to support it for correctness, right?

If a batch ends up needing to be send again to another range then we'll have to deal with that? How much of the pagination does the DistSender deal with today?

**Comment by nvanbenschoten** [comment]
> Can you help me understand the header bits a bit better. Does ResolveIntentRange use a transaction in a header? If so would we only be batching resolution for a single transaction?

No, it's just used to set a `MaxSpanRequestKeys`. So we could either let the batch header be set to an arbitrary value or expose a knob specifically to configure the setting of this field on BatchRequest headers sent by the batcher.

> Most of the time we won't actually be paginating, we just need to support it for correctness, right?

Right, although there are cases that certainly will lead to pagination, like large DeleteRange requests.

> If a batch ends up needing to be send again to another range then we'll have to deal with that? How much of the pagination does the DistSender deal with today?

This DistSender handles all of the pagination necessary for sending to ranges one-by-one when a limit is set. However, it only proceeds until `MaxSpanRequestKeys` is hit. So we need another loop above this to send another BatchRequests when the previous one has exhausted its limit.

**Comment by ajwerner** [comment]
Makes sense, thanks.

Would it be better to put the loop to finish the pagination in the `Batcher` or back in the client? My instinct is the former.

Would we want to set the value of `MaxSpanRequestKeys` differently for different batches or should it just be a knob or option on the `Batcher`?

**Comment by nvanbenschoten** [comment]
Good news, I was just able to confirm that fixing this issue does address the regression in TPC-C. I had a small scare due to a goroutine leak that I introduced in my WIP patch, but with that fixed, things look a lot better.

> Would it be better to put the loop to finish the pagination in the Batcher or back in the client? My instinct is the former.

I agree, I think it belongs in the `Batcher`. That's how I have it implemented in the WIP branch.

> Would we want to set the value of MaxSpanRequestKeys differently for different batches or should it just be a knob or option on the Batcher?

I think it can just be an option on the `Batcher`. I have the entire `Header` configurable right now, but that seems too heavyweight and possibly unsafe.

I'm hoping to clean up what I have and to put something out for this tomorrow.
