### ISSUE TITLE
sql: error message when trying to write to system database

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#4676]
When you try to `CREATE/DROP/INSERT/DELETE/UPDATE` on the `system` database as the `root` user or any other user, you get a potentially misleading error message:

```
root@:26257> create table test(a int, b string);
query error: pq: user root does not have CREATE privilege on database system
```

This error implies that write privileges CAN be granted on the `system` database. For everything but `SELECT`, I'd suggest changing to something like:

`system database is read-only`
OR
`privilege on system database is limited to SELECT` 

If the user tries SELECT but doesn't have that privilege, we could stick with what we have:
 
`query error: pq: user jseldess does not have SELECT privilege on table lease`

**Comment by dt** [comment]
fwiw, `root` _does_ have `UPDATE`, `INSERT` and `DELETE` on the system tables, just not the DDLs like `CREATE`.

**Comment by mberhault** [comment]
yup. this is intentional. we don't want the tables to be dropped or their schema modified, or bad things will happen.
an error will also occur if trying to grant `CREATE` privilege on system tables.

**Comment by dt** [comment]
re: discussion on #4865: decided we don't need this.
