### ISSUE TITLE
sql: improve the schema change job descriptions that aren't tied to statements

### ISSUE THREAD

**Issue by lucy-zhang** [cockroachdb/cockroach#46769]
In some cases, during schema changes, we start schema change jobs for table descriptor updates that are auxiliary to the main schema change job, such as updating foreign key backreferences, or that don't have a statement tied to them for some reason. These jobs currently have very vague descriptions which may be confusing or unhelpful. See #46757, where the job description in this case is just `updating privileges`. These strings could at least be updated with table IDs, etc.

**Comment by jordanlewis** [comment]
The `updating privileges` description is used even in the case of a `GRANT`, though, to my testing. That at least should be fixed, I think.
