### ISSUE TITLE
raft: why the raft log does not use a separate rocksdb instance?

### ISSUE THREAD

**Issue by jiadexin** [cockroachdb/cockroach#46773]
**Is your feature request related to a problem? Please describe.**
why the raft log does not use a separate rocksdb instance?

**Describe the solution you'd like**
The current raft log instance and the kv data instance both share the same rocksdb. I wonder why the raft log does not use a separate rocksdb instance? I think this performance should be better.

**Describe alternatives you've considered**
The raft log use a separate rocksdb instance

**Comment by irfansharif** [comment]
We are actually looking to separate out our raft storage from the shared rocksdb/pebble instance, we're just not quite all the way there yet. The current next step is https://github.com/cockroachdb/cockroach/issues/39182, and something I'm currently working, before we can fully flesh out the work that'd go into separating out raft storage in its own storage device.
