### ISSUE TITLE
sql: convert forEachTableDesc to use the virtual table iterator model

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#46828]
Currently, all of the major virtual catalog tables that produce data about tables and indexes use the `forEachTableDesc` family of helper functions. These functions eagerly load all tables and run a function once per table.

Now that `virtualSchemaTable` has the `generate` member, which exposes an iterator model for constructing virtual tables, we should convert `forEachTableDesc` to work within that model. The outcome of this work should be that the tables that currently implement `populate` with `forEachTableDesc` should instead implement `generate` with a new method.

This also opens the door to paginating the actual fetch of the table descriptors, which is currently not done.

**Comment by rohany** [comment]
Done in #47440
