### ISSUE TITLE
roachprod: rename DEAD_ROACH_PROBLEM

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#46851]
It's not specific to Cockroach processes - it seems that any process run via `roachprod run` will trigger this exit status. This has caused some confusion because it indicates that a server node crashed when it was really a client command, such as here:

```
Error: DEAD_ROACH_PROBLEM:
  - error with user detail: Node 1. Command with error:
    ```
    ./workload run tpch --concurrency=1 --db=tpch --max-ops=1 --queries=2 --vectorize=on {pgurl:1-3}
    ```
  - exit status 1
```

Maybe we can simply rename to PROCESS_EXITED.

Epic CRDB-10428

Jira issue: CRDB-5059

**Comment by jordanlewis** [comment]
Bummer - I liked DEAD_ROACH_PROBLEM : )

**Comment by jlinder** [comment]
Would this be safe enough?

- If commands from `roachprod run` that contain `cockroach` in the command string then DEAD_ROACH_PROBLEM would be used
- if they don't contain that text, then an alternate error would be used

**Comment by tbg** [comment]
Honestly I think the less complicated this gets the better. The error is that the command that is mentioned later in the error returned nonzero (as opposed to the SSH session running that command dying).

Besides `./cockroach start` is almost always run through `c.Start()` and it uses the `--background` flag, which means that if cockroach crashes, there isn't anything on `c.Run` that would get the DEAD_ROACH_PROBLEM. Instead, the monitor will detect the dead node (if one is running in the test).

**Comment by jlinder** [comment]
Thank you for pinpointing the monitoring error as one that should be `DEAD_ROACH_PROBLEM`. We'll get that one corrected.

For the `roachprod run` command errors, the big question I have is:

- Is `roachprod run` called with some commands that should be classified as infra problems and other commands that should be classified as non-infra problems?

If that is the case, then I see one of two solutions:

- make roachprod classify its exit code and error messages according to the type of command it sees (probably through a regex applied to the command to determine which type it is)
- make `roachprod` always exit with `COMMAND_PROBLEM` for `roachprod run` and have `roachtest` be more distinguishing on how it handles that exit code given the command it ran.

Thoughts?

**Comment by tbg** [comment]
I will gently push back against `roachprod` trying to sniff the command type. `roachprod run` is the generic workhorse for running literally anything against a remote cluster. What roachprod should do is help us find out whether the thing the user tried to run resulted in an error, or whether some ssh/network/vm taken down/user context cancelled problem caused the command to never run to completion. The error prominently displays the command that was run today, which is more than enough for anyone looking to get the info they need.

Where we can do better indeed is around monitoring running CRDB processes. Unfortunately, changing `roachprod run` isn't going to be of much help here. We generally learn of down nodes via `roachprod monitor` (called from roachtest after teardown) which tells us if nodes are down. 

The big thing to improve here would be to include the final log message (saving the hop to the artifacts to see if there's a panic or fatal at the end). Unfortunately, roachprod monitor doesn't really know where to find the logs. In the short term, I'd be comfortable making that an educated guess (`/mnt/data1/cockroach`) as all other options are unwieldy.

**Comment by tbg** [comment]
Actually, `monitor` does know where the logs are! So what I classified as a hack is actually perfectly fine code. See https://github.com/cockroachdb/cockroach/blob/56ecea3182917216a780a4e82a00bf241d562596/pkg/cmd/roachprod/install/cluster_synced.go#L362

We just need to add

```
				Store:       Cockroach{}.NodeDir(c, nodes[i]),

**Comment by jlinder** [comment]
> I will gently push back against `roachprod` trying to sniff the command type. `roachprod run` is the generic workhorse for running literally anything against a remote cluster. What roachprod should do is help us find out whether the thing the user tried to run resulted in an error, or whether some ssh/network/vm taken down/user context cancelled problem caused the command to never run to completion. The error prominently displays the command that was run today already, which is more than enough for anyone looking to get the info they need once they know whether or not the command actually resulted in the error. 

👍  Your answer matches my thoughts on which to choose (though I didn't say them when asking the question).

> The big thing to improve here would be to include the final log message (saving the hop to the artifacts to see if there's a panic or fatal at the end). 

Cool. I'll take a look.

**Comment by tbg** [comment]
Regarding grabbing the pertinent logs, this works well:

```
tac ~/Downloads/cockroach.log | grep -m 1 -B 30 -E '^[IWEF]' | tac
```

It should be easy to put this in the output once you know the right file to `tac`. I *think* it is always called `cockroach.log`, so you should be able to do something like

```
log="{{.LogDir}}/cockroach.log"
if [ -f "${log}" ]; then tac "${log}" | grep -m 1 -B 30 -E '^[IWEF]' | tac; fi
```

**Comment by tbg** [comment]
> I think it is always called cockroach.log, so you should be able to do something like

Nope it is not. It's binaryname.log (i.e. ./cockroach-foo produces cockroach-foo.log).

**Comment by kenliu-crl** [comment]
see also https://github.com/cockroachdb/cockroach/pull/51314

**Comment by srosenberg** [comment]
This was resolved via https://github.com/cockroachdb/cockroach/pull/47207
