### ISSUE TITLE
backupccl: RESTORE and BACKUP to http sinks fails

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#46878]
```
root@:26257/defaultdb> RESTORE tpch.* FROM 'https://storage.googleapis.com/cockroach-fixtures/workload/tpch/scalefactor=1/backup' WITH into_db = tpch;
ERROR: reading previous backup layers: http storage does not support listing files
```

This is because the new automatically appended incremental backup UX requires looking for any appended incremental backups in subdirectories, but HTTP does not, as the error mentions, support listing.

I think the easy fix here is to not try looking for incremental via HTTP, meaning you would interact with, and only with, the base backup at the specified path. 

This would be a little weird however if that backup _did have_ incremental additions append to it in subdirectories, but writing those would be impossible via HTTP as well so that's a pretty obscure edge case. Additionally, running SHOW BACKUP on that location would only show the base too so it would be consistent? I don't have any better ideas.

**Comment by mwang1026** [comment]
Is there anything in the BACKUP file that could tell you on the `restore` that there are subdirectories created by appendable backup and we could throw an error/warning? What I think we want to avoid is people thinking they're restoring to a certain point but in fact are restoring to a different point.

Agreed wonky / not ideal here

**Comment by dt** [comment]
No, we decided to go with an listing-based approach to determining if there are existing layers and what they are. This means you can move or delete them with basic file tools (e.g. to fix the narrowing problem we talked about before) and we avoid some issues with race conditions and consistency, but the flip side of that is there is no one file that we can read to avoid listing.

**Comment by mwang1026** [comment]
Got it. Well at least a documentation update that we don't support HTTP for append-able backup/restore is required cc @lnhsingh 

So if I understand correctly:
* Backup will error if you try to append with http--maybe an error message update?
* We'll need to update Restore's behavior and the only obvious candidate is to only look for the base bucket data (either full or incremental). If that's the case we should at LEAST show some warning about the behavior--something along the lines of "Restoring from an http sink will only reference the base bucket. Any subdirectories are ignored. If you have additional incremental backups to restore from, explicitly list out those subdirectories". I'd want to futz with that final language but that's all I can think of for now.
