### ISSUE TITLE
adminui: blurb about waiting to collect diagnostics persists across tabs

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#46884]
After requesting diagnostics and switching the tab, the tip is still there.

![Screenshot 2020-04-01 17 14 54](https://user-images.githubusercontent.com/377201/78187436-6172e180-743c-11ea-96ff-8bfb8359f8aa.png)

Btw, is the diagnostics tab supposed to notice whether the request was satisfied and refresh itself somehow?

**Comment by dhartunian** [comment]
The tooltip issue should be fixed with #46854.

The cache for that data is set to 5m at the moment since its retrieving the entire list. Could set it to shorter or add polling for the individual unfulfilled requests.
