### ISSUE TITLE
adminui: sorting in statements page only affects the data set from the respective page

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#46882]
It appears to me that, if you click on one of the column headers on the statements page to sort by that column, you're only sorting the subset of the data that you were already looking at, not all the data across all the possibly-multiple pages. This seems like not what one wants. I'd like to sort by, say, latency and see the slowest statements across all the statements.

**Comment by dhartunian** [comment]
This should have been fixed by #46416 which was merged today. Let me know if your experience was on a commit after this change.

**Comment by andreimatei** [comment]
Probably, thanks!
