### ISSUE TITLE
opt: add rule to push down agg DISTINCT to input

### ISSUE THREAD

**Issue by andy-kimball** [cockroachdb/cockroach#46899]
We should add a rule to the optimizer which rewrites queries like this:
```
CREATE TABLE xy (x INT PRIMARY KEY, y INT, INDEX (y));
INSERT INTO xy SELECT x, x % 100 FROM generate_series(1,100000) t(x);
SELECT COUNT(DISTINCT y) FROM xy;
```
to this:
```
SELECT COUNT(*) FROM (SELECT DISTINCT y FROM xy);
```
The first runs in ~80ms on my laptop. The second runs in ~55ms. The biggest reason for the drop is that the second formulation can take advantage of our streaming group-by execution operator, since the `y` index can be used.

**Comment by jordanlewis** [comment]
I think this is only possible when the query has no grouping columns, and all of the aggregates functions are distinct on the same column (or there's just one distinct aggregate function).

If the query has grouping columns, the distinct has to come after the grouping. And if the query has more than one aggregation function, and the functions aren't all distinct on the same column, each function would need to see a different subset of the input - so you couldn't just distinctify the whole input stream.

**Comment by andy-kimball** [comment]
Right this only applies for the `ScalarGroupBy` operator, which always has exactly 1 group (i.e. grouping column set is empty).
