### ISSUE TITLE
demo: let's print the SQL port on startup

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#46901]
When starting a demo cluster, I'd like to have the SQL port, or connection string, printed out (like we do for the admin ui).
And in a multi-node demo, I'd like to see all of them.

**Comment by awoods187** [comment]
+1 

I always end up needing to `select * from crdb_internal.gossip_nodes`and then parse it to find the right set of numbers to add to the other connection string `./cockroach sql --url postgresql://127.0.0.1:59797
#`
