### ISSUE TITLE
Investigate tpcc performance slowdown

### ISSUE THREAD

**Issue by darinpp** [cockroachdb/cockroach#46931]
Further investigate the reason for #41163

- load the dataset for 1350 warehouses
- run the load for ~30 minutes to let the cluster balance and stabilize
- kill the load and measure the latency of each of the statements in pkg/sql/opt/xform/testdata/external/tpcc. Store this in a spreadsheet or something
- run the load for ~3 days, until latencies get up to ~10s p50 for NewOrder
- kill the load and measure the latency of each of the statements in pkg/sql/opt/xform/testdata/external/tpcc again. Store this in the spreadsheet
- determine whether any queries got significantly slower

**Comment by jordanlewis** [comment]
No longer relevant, right darin?
