### ISSUE TITLE
sql: COPY missing from exec, stat and audit logs

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#46958]
The COPY statement does not use the regular execution path and is thus not picked up by any of our logging subsystems:

- not in vmodule exec_log=2
- not in the audit log even though it touches tables that may be currently be audited (could be considered as a security problem)
- not in the exec log
- not in the statement stats

Found by @robert-s-lee 

cc @jordanlewis for triage

Jira issue: CRDB-5052

**Comment by knz** [comment]
still relevant

**Comment by knz** [comment]
cc @otan is this still actual?

**Comment by otan** [comment]
Should be there now
