### ISSUE TITLE
sql: improve span gen when the constraint columns are physically in-between indexed columns

### ISSUE THREAD

**Issue by idubrov** [cockroachdb/cockroach#46951]
I have the following table structure:

```sql
create table test(key1 string, key2 string, value1 string, value2 string, primary key (key1, key2));
create index idx1 on test(value1, value2, key1);
create index idx2 on test(value1, key1, value2);
```

Then I have the following two statements. Note that they both are the same, I just force two different indices.

```
explain select key1, key2 from test@idx1 where value1 = 'hello' AND value2 = 'bye' AND (key1, key2) > ('abc', 'xyz') GROUP BY key1, key2 ORDER BY key1, key2;
explain select key1, key2 from test@idx2 where value1 = 'hello' AND value2 = 'bye' AND (key1, key2) > ('abc', 'xyz') GROUP BY key1, key2 ORDER BY key1, key2;
```

The first one yields this plan:
```
root@:26257/bend> explain select key1, key2 from test@idx1 where value1 = 'hello' AND value2 = 'bye' AND (key1, key2) > ('abc', 'xyz') GROUP BY key1, key2 ORDER BY key1, key2;

    tree    |    field    |                       description                        
+-----------+-------------+---------------------------------------------------------+
            | distributed | false                                                    
            | vectorized  | false                                                    
  render    |             |                                                          
   └── scan |             |                                                          
            | table       | test@idx1                                                
            | spans       | /"hello"/"bye"/"abc"/"xyz\x00"-/"hello"/"bye"/PrefixEnd  
(6 rows)

Time: 720µs
```

The index key is effectively `(value1, value2, key1, key2)`. I could have omitted `key1` from the index, I don't think it makes any difference as `(key1, key2)` is primary key and it will be a suffix of index key anyways.

We are searching for fixed value1 and value2, with "offset" starting from a pair of ('abc', 'xyz'). So, CockroachDB is able to do a direct index scan starting from a specified range, which is very efficient.

Let's look at the second plan:

```
root@:26257/bend> explain select key1, key2 from test@idx2 where value1 = 'hello' AND value2 = 'bye' AND (key1, key2) > ('abc', 'xyz') GROUP BY key1, key2 ORDER BY key1, key2;

    tree    |    field    |                     description                       
+-----------+-------------+------------------------------------------------------+
            | distributed | true                                                  
            | vectorized  | false                                                 
  render    |             |                                                       
   └── scan |             |                                                       
            | table       | test@idx2                                             
            | spans       | /"hello"/"abc"/"bye"-/"hello"/PrefixEnd               
            | filter      | (value2 = 'bye') AND ((key1, key2) > ('abc', 'xyz'))  
(7 rows)

Time: 1.942ms
```

The index ordering, I believe, used internally by CockroachDB will be `(value1, key1, value2, key2)` (basically, secondary index colums + all missing primary key columns added as a suffix).

This plan is much worse -- CockroachDB does not use `key2` for index scan. So, if we have many rows with the same `key1`, it will be very inefficient.

I believe that even in this case, it could have scanned the following span:

```
            | spans       | /"hello"/"abc"/"bye"/"xyz"-/"hello"/PrefixEnd               
```

As it is guaranteed that every value we are looking for should be greater than this prefix. Either `key1` will be larger than "abc" (in which case it will be strictly greater than this prefix) or `key1` is "abc" and then key2 will be larger than "xyz" (as per our ordering).

Jira issue: CRDB-5053

**Comment by yuzefovich** [comment]
@RaduBerinde I think this would fall on the optimizer team, right?

**Comment by RaduBerinde** [comment]
Thanks for the detailed description. I agree with your assessment. Just a hard case to implement, with the other constant column "in-between" the columns in the tuple inequality.

Note that in general the difference would be fairly small, we are only "refining" how much we scan "inside" the 'abc' value; we will still scan everything under larger `key1` values. Perhaps for this case we'd want to do an "index skip scan" where we read one row to find the next `key1` value, then jump to the 'bye' value under that, and repeat. We don't currently support that though.

**Comment by idubrov** [comment]
In our case _I think_ it would make a big difference as we try to use this as "pagination": client calls multiple times, every time getting at most some fixed amount of rows. For one specific key1, we have many different key2 and I think what happens is that we keep rescanning these many key for multiple requests (say  first request is with range `(key1, key2) > ("abc", "0000")`, then  second request is `(key1, key2) > ("abc", "1000")`, etc).

**Comment by RaduBerinde** [comment]
I see, so in your case there is also a LIMIT involved somewhere, correct?

**Comment by idubrov** [comment]
Exactly.

**Comment by RaduBerinde** [comment]
Note that as a workaround (assuming you have direct control over the queries), you could use `where value1 = 'hello' AND value2 = 'bye' AND (key1, value2, key2) > ('abc', 'bye', 'xyz');`

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[5037](https://cockroachdb.zendesk.com/agent/tickets/5037) has been linked to this issue.
