### ISSUE TITLE
CREATE STATISTICS on table with ARRAY column

### ISSUE THREAD

**Issue by mrigger** [cockroachdb/cockroach#46964]
Consider the following statements:

```sql
CREATE TABLE t0(c0 STRING[]);
INSERT INTO t0(c0) VALUES(ARRAY[]);
CREATE STATISTICS s0 ON c0 FROM t0; -- ERROR: unable to encode table key: *tree.DArray
```
Unexpectedly, the `CREATE STATISTICS` results in an error `unable to encode table key: *tree.DArray`. I found this bug based on commit 0c1b121315e246e3e51fc6f7aa613f77de6b6527.

**Comment by rytaft** [comment]
Taking a look now - thanks for the report!
