### ISSUE TITLE
kv: add per-batch limit KV batch operations

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#4696]
The ask is to enhance the KV API to allow setting a *per-batch* limit on the number of returned keys. These would be the first `X` keys that would be returned from the regular request (in the same order).

The use case is implementing #2966 - we currently read all table data in one operation and we want to break it up in chunks. Reading table data may involve have multiple scans (one for each "span") and we can't know ahead of time how many keys there will be in each span.

@tschottdorf said this should be doable since the scans within a batch happen in order.

**Comment by RaduBerinde** [comment]
I looked at how we could add this. Adding a `maxScanRows` parameter to `Batch`/`BatchRequest` seems a bit hacky and it will result in having to plumb this value through a lot of the `client/db.go` infrastructure.

An alternative that might be cleaner would be to add a `SetScanLimit` "request". When called, it limits the total number of KVs returned by all subsequent `Scan`/`ReverseScan` requests in that batch. We would just need to keep a bit of state in `executeBatch` and pass it to `executeCmd`.

What do you think @tschottdorf?

**Comment by tschottdorf** [comment]
Honestly the latter seems much hackier. If we want that functionality, and it seems that we do, we should introduce it properly.

**Comment by vivekmenezes** [comment]
+1

**Comment by RaduBerinde** [comment]
Ok, will add it to `BatchRequest` then. Thanks!
