### ISSUE TITLE
CAST to INT2 yields an incorrect/inconsistent result

### ISSUE THREAD

**Issue by mrigger** [cockroachdb/cockroach#46970]
Consider the following statements:

```sql
CREATE TABLE t0(c0 INT);
INSERT INTO t0 VALUES(-1292691042);
SELECT t0.c0::SMALLINT FROM t0; -- expected: {6558}, actual: {-1292691042}
```
Interestingly, the expected result is computed when the vectorizer is on:
```sql
SET vectorize=on;
CREATE TABLE t0(c0 INT);
INSERT INTO t0 VALUES(-1292691042);
SELECT t0.c0::SMALLINT FROM t0; -- expected {6558}
```
I initially found this bug since a `MAX()` query nondeterministically returned one of the two values. I found this bug based on commit 0c1b121315e246e3e51fc6f7aa613f77de6b6527.

**Comment by yuzefovich** [comment]
Seems related to #46940.
