### ISSUE TITLE
roachprod does not work with AWS CLI version 2

### ISSUE THREAD

**Issue by spaskob** [cockroachdb/cockroach#47022]
**Describe the problem**

`roachprod sync` fails when using AWS CLI version 2.

**To Reproduce**

1. Install AWS CLI version 2
2. In a terminal run `roachprod sync`
3. Command fails with
```
Error: exit status 255
failed to run: aws ec2 import-key-pair --region eu-west-1 --key-name <$USER-$HASH> --public-key-material <your_public_key>
```

**Comment by bobvawter** [comment]
@spaskob I'm unable to reproduce this locally using the `aws2` client.  What does the output of `aws --version` return for you?

**Comment by spaskob** [comment]
I already downgraded to version 1. I am on Mac btw if this makes a
difference. It's possible there's something exotic about my setup but it
does work flawlessly now with version 1.
