### ISSUE TITLE
TRUNCATE on temporary table results in "unexpected value: <nil>"

### ISSUE THREAD

**Issue by mrigger** [cockroachdb/cockroach#47030]
Consider the following statements:

```sql
SET experimental_enable_temp_tables = 'on';
CREATE TEMP TABLE t0(c0 INT);
TRUNCATE t0; -- ERROR: unexpected value: <nil>
```

I would expect the statements to be equivalent to the following, which executes without an error:
```sql
SET experimental_enable_temp_tables = 'on';
CREATE TEMP TABLE t0(c0 INT);
DELETE FROM t0 WHERE TRUE;
```
I assume it is unexpected that the `TRUNCATE` does not (yet) work, since it is neither described at https://github.com/cockroachdb/cockroach/issues/46260, nor at https://www.cockroachlabs.com/docs/dev/temporary-tables.html.

**Comment by yuzefovich** [comment]
Seems like another missed case. cc @otan @rohany
