### ISSUE TITLE
sql: TestPrimaryKeyChangeWithCancel takes 60s

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#47038]
This test consistently seems to take exactly 60s. Is that expected/desired? I definitely hope it's not desired :P
If it is expected, can we speed it up somehow (testing knobs maybe?).

**Comment by andreimatei** [comment]
Skipping on short - #47039

**Comment by rohany** [comment]
I see the problem, the job adoption interval wasn't set to a smaller value, opening a PR. Takes 3 seconds now.
