### ISSUE TITLE
backupccl: Incremental backup fails with error `ERROR: invalid previous backups (a new full backup may be required if a table has been created, dropped or truncated): no backup covers time [1586054134.368267700,0,1586054324.310442218,0) for range [/Table/2/1,/Table/2/2) (or backups out of order)`

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#47050]
**Describe the problem**
When using the new "Automatic appending incremental backup" UX, backing up full cluster, in two different scenarios, run into the error `ERROR: invalid previous backups (a new full backup may be required if a table has been created, dropped or truncated): no backup covers time [1586054134.368267700,0,1586054324.310442218,0) for range [/Table/2/1,/Table/2/2) (or backups out of order)` which is weird because that's not a table that's backed up by full cluster restore

**To Reproduce**
Two scenarios, both running on the same roachprod cluster in AWS on the latest edge binary as of April4 8pmMT

1. Ran `./cockroach workload init tpcc --warehouses=1000 --db=tpcc`
2. Took 1 full and 2 incremental backups before init finished, waiting for init to finish
3. Tried to take another backup after init finished and ran into the error (init finishes with a bunch of additions of foreign keys)

Second scenario, same cluster, after init has finished
1. take full backup
2. run tpcc workload `./cockroach workload run tpcc --duration=10m`
3. take 2 incremental backups
4. create database (temp)
5. create table (temp.a)
6. drop table (temp.a)
7. attempt another incremental backup--fails
8. workload finishes running

**Comment by pbardea** [comment]
Adding a couple of notes clarifying repro steps:
- The error only appears when the backups were `WITH revision_history`
- At least one incremental backup must be taken during the workload init
- (It can also be reproduced with 10 warehouses, so the size of the imported data does not matter)
