### ISSUE TITLE
sql: WITH HASH hash column is not null but formula can return NULL

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#47055]
```
create table t (x int);
CREATE INDEX ON t(x) USING HASH WITH BUCKET_COUNT = 10;
```

This is what the optimizer sees through the catalog:
```
root@127.0.0.1:43341/defaultdb> explain (opt, catalog) select * from t;
                                                                      text
-------------------------------------------------------------------------------------------------------------------------------------------------
  TABLE t
   ├── x int
   ├── rowid int not null default (unique_rowid()) [hidden]
   ├── crdb_internal_x_shard_10 int4 not null as (mod(fnv32(CAST(x AS STRING)), 10)) stored [hidden]
   ├── CHECK (crdb_internal_x_shard_10 IN (0:::INT8, 1:::INT8, 2:::INT8, 3:::INT8, 4:::INT8, 5:::INT8, 6:::INT8, 7:::INT8, 8:::INT8, 9:::INT8))
   ├── INDEX primary
   │    └── rowid int not null default (unique_rowid()) [hidden]
   └── INDEX t_crdb_internal_x_shard_10_x_idx
        ├── crdb_internal_x_shard_10 int4 not null as (mod(fnv32(CAST(x AS STRING)), 10)) stored [hidden]
        ├── x int
        └── rowid int not null default (unique_rowid()) [hidden]
  scan t
   ├── check constraint expressions
   │    └── crdb_internal_x_shard_10 IN (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)
   └── computed column expressions
        └── crdb_internal_x_shard_10
             └── mod(fnv32(x::STRING), 10)
```

The `crdb_internal_x_shard_10` column is defined as `not null` with the formula `mod(fnv32(CAST(x AS STRING)), 10)`. But this formula returns NULL when x is NULL.

This means that we can't insert NULL values, and index creation will fail if there are null values:
```
ERROR: null value in column "crdb_internal_x_shard_10" violates not-null constraint
```

We should either:
 - allow NULL values and make sure they map to bucket 0, or
 - require the hash column to be marked as non-null, or
 - automatically mark the hash column as non-null when creating index.

**Comment by ajwerner** [comment]
I'm thinking we should do some variant of:

```
1) allow NULL values and make sure they map to bucket 0 
```

I think it might make more sense to instead of mapping to bucket 0 for null values to instead map each null to a zero value when plugging it into the formula.

**Comment by RaduBerinde** [comment]
Maybe we can add a variant of `fnv32` that does that.

**Comment by ajwerner** [comment]
That sounds straightforward. Any suggestions on what to call this? `fnv32_null`? 

Another potential challenge here is that old hash sharded indexes from beta will be susceptible. I think the experimental flag means we're okay not fixing those with a migration.

**Comment by RaduBerinde** [comment]
> Another potential challenge here is that old hash sharded indexes from beta will be susceptible

If a hash sharded index exists, there will be no NULLs in the table (the user would have hit the error I pasted in the description).

**Comment by ajwerner** [comment]
>> Another potential challenge here is that old hash sharded indexes from beta will be susceptible
>
> If a hash sharded index exists, there will be no NULLs in the table (the user would have hit the error I pasted in the description).

Sure but that table will be in a bad state.

**Comment by RaduBerinde** [comment]
> Sure but that table will be in a bad state.

I don't understand in what way, can you be more specific?

**Comment by RaduBerinde** [comment]
Talked offline with @ajwerner - I missed that if we fix this by changing the computed column expression, existing indexes will still have the old expressions so they will still be in this state (specifically, of not being able to insert NULLs). I think that's fine (especially since there is a workaround of removing the index and recreating it).

**Comment by ajwerner** [comment]
I'm thinking that I'm not going to create a new function as I don't think I'd feel comfortable backporting that new function.
