### ISSUE TITLE
colexec: fix spillingQueue

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#47062]
Currently, `spillingQueue` is simply holding on to the enqueued batches when those were kept in memory. This is problematic because the caller should not be limited in that it needs to allocate new working batch (because the modification of the already enqueued batch might lead to the corruption). `spillingQueue` should be actually copying the passed-in batches and should be performing the coalescing behavior (filling all of its internal batches up to `coldata.BatchSize`), which is currently done by `routerOutputOp`. Additionally, when enqueueing a batch to disk, we should be checking whether the batch has a selection vector, and if so, we should be deselecting it (because `diskQueue` ignores the selection vectors).

**Comment by asubiotto** [comment]
I have a branch up for this, but I need to get around to updating it and creating a PR.
