### ISSUE TITLE
sql: improve explain analyze (debug) folder names

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#47069]
When using the explain analyze (debug) feature, the file names for the queries generated as follows:

```SQL
root@127.0.0.1:59684/movr> explain analyze (debug)  select * from rides;
                                      text
--------------------------------------------------------------------------------
  Statement diagnostics bundle generated. Download from the Admin UI (Advanced
  Debug -> Statement Diagnostics History) or use the direct link below.
  Admin UI: http://127.0.0.1:59682
  Direct link: http://127.0.0.1:59682/_admin/v1/stmtbundle/544312969443082241
(4 rows)

Time: 257.556ms
```
Which then outputs this name:
`stmt-bundle-544312969443082241`

We should consider adding the following:

CockroachDB as a prefix
Naming it Explain Analyze (debug) 
Numbers tied to the number of explain analyze (debug) used in a given session

I'm imagining a final product as something human-readable like:
CockroachDB Explain Analyze (debug) 1
CockroachDB Explain Analyze (debug) 2

**Comment by awoods187** [comment]
Testing adding the zip to an issue:
[stmt-bundle-544312969443082241.zip](https://github.com/cockroachdb/cockroach/files/4438816/stmt-bundle-544312969443082241.zip)

**Comment by RaduBerinde** [comment]
I also have #46880 with a different suggestion. Note that the same bundle can be triggered via diagnostics from the UI, so I don't think the naming should be specific to "explain analyze debug". I also don't think the filename should contain spaces or parens (or even capitalization), these are very annoying in file names.

**Comment by awoods187** [comment]
I'll close this and travel over to #46880
