### ISSUE TITLE
webui: bundle doesn't show without hovering in advanced debug

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#47074]
The debug.zip for bundle/explain analyze (debug) isn't visible unless you hover over it:
![image](https://user-images.githubusercontent.com/22278911/78573669-fbe57300-77f6-11ea-9b05-506bb785b061.png)
With hovering:
![image](https://user-images.githubusercontent.com/22278911/78573744-11f33380-77f7-11ea-89e6-cf9855d6ef45.png)

We should make this always visible rather than reactive to hovering. It's already within the advanced debug pages--I don't think we run the risk of it being run frequently (which we would be worried about given its expense).

**Comment by RaduBerinde** [comment]
Dup of #46340, please add your +1 in there.
