### ISSUE TITLE
cli: TestZipSpecialNames failed

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#47088]
During CI [build](https://teamcity.cockroachdb.com/viewLog.html?buildId=1856040&buildTypeId=Cockroach_UnitTests) of seemingly unrelated PR, `TestZipSpecialNames` failed with 
```
+  ^- resulted in operation "requesting table details for defaultdb.SYSTEM.JOBS"
timed out after 10s: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```
Possibly it is a flake, but it's worth investigating it further.

**Comment by spaskob** [comment]
Hey Yahor, should we keep this one open?

**Comment by yuzefovich** [comment]
I don't know, I haven't seen other failures of this test. Feel free to close it if you think it was a flake.
