### ISSUE TITLE
SHOW BACKUP: Update \h to include `WITH PRIVILEGES` syntax

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#47081]
**Is your feature request related to a problem? Please describe.**
We recently added `WITH PRIVILEGES` as an option for `SHOW BACKUP` but \h isn't updated

**Describe the solution you'd like**
Quick update to the `Syntax` section for \h to include `[WITH PRIVILEGES]`

Jira issue: CRDB-5043

**Comment by dt** [comment]
I think we might need some guidance from cli and education teams about what options we do or do not document in CLI help. I don't think of the CLI help as a replacement for the online docs, but rather just a quick reference for the simple/base-case, so it typically would not include obscure options like this, but I don't know what the official guidance is here.

**Comment by mwang1026** [comment]
No strong feelings here whether we pick this up now vs. later vs. ever. Just wanted to flag this as a missing piece of the CLI help.

**Comment by dt** [comment]
Right, my point was that it might not be "missing" so much as "not intended to be there", depending on the line between cli and the online docs
