### ISSUE TITLE
changefeed telemetry: Telemetry on active running changefeeds, changefeed throughput

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#47080]
Today, we only capture telemetry around changefeeds on changefeed creation. What we don't have is changefeed cancel, failed, paused, resumed, etc. We would / could use statement stats for that, but the problem is that there isn't a `pause changefeed` statement--it uses the Jobs pause/resume/cancel and there's no way for us to know what statement is cancelling a changefeed vs another job. We also don't know the amount of data being passed through changefeeds.

** Requests **
- Telemetry to be able to know how many changefeeds are running. Suggestions include (1) adding pause/resume/cancel telemetry for changefeeds and we can cobble together what changefeeds are running [this is tedious and error prone] (2) some kind of regular (daily?) "ping" to know what changefeeds are running and how many tables they cover [preferred but a bit fuzzier in how it'd work]
- Whether a changefeed was CORE or ENTERPRISE changefeeds

** Nice to have **
- Haven't thought through it in depth but a way to know how much data is being passed through changefeeds. This is another way to know something about whether changefeeds are running, but I think requires a bit more thought about how / what value looking at this provides.

**Comment by amruss** [comment]
Closing: we're working with the new data team to figure out how to get these and other insights out of changefeed telemetry under the new data paradigm, but it will be a little while before changes are implemented.
