### ISSUE TITLE
running workload/schemachange causes 19.2 node in mixed version cluster to crash

### ISSUE THREAD

**Issue by spaskob** [cockroachdb/cockroach#47110]
**Describe the problem**

When running the following workload on a mixed version cluster that has been upgraded to `20.1` and then downgraded (1 node) to `19.2.5`. The downgraded node crashes.

**To Reproduce**

1. Start a 3-node `19.2.5` cluster.
Note: prevent the cluster from finalizing the upgrade by:
`SET CLUSTER SETTING cluster.preserve_downgrade_option = '19.2';

2. Upgrade each node to `20.1`.

3. Downgrade node 3 to `19.2.5`.

4. Run this workload:
`roachprod run $CLUSTER:4 -- ./workload run schemachange --init --concurrency=2 --verbose=true --max-ops=300 "{pgurl:1-3}"`

5. Node 3 crashes with
```
E200407 02:02:45.722783 4883 sql/conn_executor.go:717  [n3,client=10.142.0.41:45994,user=root] a SQL panic has occurred while executing "SELECT column_name FROM [SHOW COLUMNS FROM table488] ORDER BY random() LIMIT 1": unexpected Family: 19
E200407 02:02:45.722870 4883 util/log/crash_reporting.go:207  [n3,client=10.142.0.41:45994,user=root] a panic has occurred!
panic: unexpected Family: 19 [recovered]
	panic: panic while executing 1 statements: SELECT _ FROM [SHOW COLUMNS FROM _] ORDER BY random() LIMIT _; caused by unexpected Family: 19
```

I will be adding more details tomorrow.

**Comment by tbg** [comment]
Nice find!

**Comment by lucy-zhang** [comment]
Is this a release blocker? If someone's rolling back to the prior version while upgrading, it's presumably because something has already gone wrong, so this would be a terrible experience overall.

**Comment by lucy-zhang** [comment]
@otan Seems like the unexpected family is `TimeTZFamily Family = 19`. Is this supposed to work in the mixed version state?
