### ISSUE TITLE
sql: cannot perform other schema changes concurrently with alter column type

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#47137]
Currently, ALTER COLUMN TYPE cannot be performed concurrently with other schema changes.

For example you cannot add a column while an alter column type is occuring, you cannot alter primary key while alter column type is occuring. 

Jira issue: CRDB-5036

Epic CRDB-25314

**Comment by RichardJCai** [comment]
#49351 covers this

**Comment by rafiss** [comment]
re-opening, since this is referenced here:

https://github.com/cockroachdb/cockroach/blob/4b8a9c7b133c28d9fef7156b151d3ac8c63a36cf/pkg/sql/alter_column_type.go#L220

**Comment by ajwerner** [comment]
I feel like this isn't really about wanting the operations to occur concurrently, it's about wanting them to be ordered.

**Comment by ddelange** [comment]
> CockroachDB executes `ALTER COLUMN` queries asynchronously which is at
     odds with Django's assumption that the database is altered before the next
     migration operation begins. CockroachDB will give an error like
     `unimplemented: table <...> is currently undergoing a schema change` if a
     later operation tries to modify the table before the asynchronous query
     finishes. A future version of CockroachDB [may fix this](https://github.com/cockroachdb/cockroach/issues/47137).

ref https://github.com/cockroachdb/django-cockroachdb/blob/5.1/README.md cc @timgraham

is there a possibility to await the change / make the query block until the change finishes?

**Comment by ajwerner** [comment]
I thought the asynchronous part was fixed such that the statement doesn’t now return until the alter is complete. That comment may be stale. Is it something you see on later cockroach versions?

**Comment by ddelange** [comment]
we are in research phase, and this looked like a blocker if we want to move to cockroachdb. can this issue be closed and the django-cockroachdb README amended?

**Comment by timgraham** [comment]
I believe [the stable CockroachDB docs](https://www.cockroachlabs.com/docs/stable/known-limitations#alter-column-limitations) still state this restriction: 

> Note: Most ALTER COLUMN TYPE changes are finalized asynchronously. Schema changes on the table with the altered column may be restricted, and writes to the altered column may be rejected until the schema change is finalized.

**Comment by ajwerner** [comment]
@rafiss is it true? My recollection is that the the alter job waits on the job it creates and has for years.

**Comment by timgraham** [comment]
For context, we saw an intermittent failure in Django with CockroachDB 21.1 (https://github.com/cockroachdb/cockroach/issues/65691). Since then the test has been on the skip list.

**Comment by ddelange** [comment]
hi all 👋

did you happen to discuss this internally in the meantime?

this would be a hard blocker to migrate our django project over from vanilla postgres

**Comment by spilchen** [comment]
Closing this out. The work underway for 25.1 reimplements the ALTER COLUMN TYPE operation in the Declarative Schema Changer. With the new implementation, the "unimplemented: table <...> is currently undergoing a schema change" error will no longer occur.

**Comment by ddelange** [comment]
I also saw in [What's New in v25.1](https://www.cockroachlabs.com/docs/releases/v25.1#v25-1-0-rc-1-backward-incompatible-changes):

> The default value of the `autocommit_before_ddl` session variable is now `true`. This will cause any schema change statement that is sent during a transaction to make the current transaction commit before executing the schema change in a separate transaction.

That sounds like this has implications for django migrations - whether set to true or false -, because a single migration can contain multiple schema changes, which is wrapped in a single atomic transaction.

Could you outline best practices here, or even better update the [README for django-cockroachdb](https://github.com/cockroachdb/django-cockroachdb/blob/5.1/README.md) cc @timgraham ?

**Comment by timgraham** [comment]
The change to `autocommit_before_ddl` doesn't affect django-cockroachdb. This backend has [`DatabaseFeatures.can_rollback_ddl = False`](https://github.com/cockroachdb/django-cockroachdb/blob/00c9e2a13adb00a6f89d0eda725d675238e4611e/django_cockroachdb/features.py#L20-L22), which means Django doesn't wrap schema changes in a transaction.  CockroachDB still has some limitations with regard to executing schema changes in transactions, such as #49351.
