### ISSUE TITLE
zigzag join queries are taking ~50s to execute under certain circumstances

### ISSUE THREAD

**Issue by lopezator** [cockroachdb/cockroach#47179]
**Describe the problem**

Queries involving zigzag joins sometimes take about 50s to execute.

Related issue:

https://github.com/ory/hydra/issues/1755

**Please describe the issue you observed, and any steps we can take to reproduce it:**

It seems that the issue might be related with zigzag join hitting multiple regions.

**Expected behavior**

I don't expect some SELECT statements to take 50 seconds.

**Additional data / screenshots**

You will find a lot of additional data inside ticket 4917. The solution provided was to simply disable zigzag joins for the whole cluster or for the session. I suppose this wasn't intended to be a definitive solution, so I opened this issue. I hope this can be investigated further and help other users that could hit the same problem.

Thanks for the support btw!

**Additional context**

After reading https://github.com/cockroachdb/cockroach/issues/23520#issue-302972941 I am going to add a double index in order to avoid the zigzag join, but I the issue could be reproduced with other queries also I suppose.

Jira issue: CRDB-5032

**Comment by lopezator** [comment]
CC/ @jordanlewis

**Comment by msirek** [comment]
Fixed by #89261
