### ISSUE TITLE
TestScannerTiming is flaky

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#472]
The following test appears to have failed:

[#896](https://circleci.com/gh/cockroachdb/cockroach/896):

```
=== RUN TestScannerTiming
I0325 16:25:21.028464     266 scanner_test.go:239] 0: average scan: 5.498453ms
I0325 16:25:21.079861     266 scanner_test.go:239] 1: average scan: 23.017947ms
--- FAIL: TestScannerTiming (0.10s)
	scanner_test.go:242: expected 12.5ms, got 23.017947ms: exceeds max error of 7.5ms

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment]
We're already allowing for an error of 7.5ms (compared to an expected value of 12.5ms), so I think the only way to fix the flakiness here is to allow the tests to run for longer.
