### ISSUE TITLE
colexec: diskqueue nil pointer dereference 

### ISSUE THREAD

**Issue by Azhng** [cockroachdb/cockroach#47203]
DiskQueue runs into nil pointer dereference error when running the sqlite logic test in [`select4.test`][1]

Using the tables created in `select4.test` , following query causes nil pointer dereference error:

```
SELECT e8, d7+959, a5*693, e2, e6*447, b1+778
  FROM t1, t6, t7, t5, t8, t2
 WHERE c5 in (489,250,927,855,697,130,856)
   AND (180=e8 OR 333=e8 OR e8=38)
   AND e7=462
   AND b2=b1
```

Error stack trace: 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5be6121]

goroutine 3154 [running]:
github.com/cockroachdb/cockroach/pkg/col/colserde.(*countingWriter).Write(...)
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/col/colserde/file.go:329
github.com/cockroachdb/cockroach/pkg/col/colserde.(*FileSerializer).Finish(0xc0054f3980, 0x0, 0x0)
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/col/colserde/file.go:139 +0x131
github.com/cockroachdb/cockroach/pkg/sql/colcontainer.(*diskQueue).writeFooterAndFlush(0xc004052480, 0x7f0dd20, 0xc003889400, 0xc00226dc10, 0x400855f)
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/sql/colcontainer/diskqueue.go:481 +0x36
github.com/cockroachdb/cockroach/pkg/sql/colcontainer.(*diskQueue).Close(0xc004052480, 0x7f0dd20, 0xc003889400, 0xc00226dcc8, 0x404252f)
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/sql/colcontainer/diskqueue.go:399 +0x36c
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*spillingQueue).close(0xc00328cc00, 0x7f0dd20, 0xc003889400, 0x4, 0xc003a29e60)
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/spilling_queue.go:271 +0x65
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*routerOutputOp).closeLocked(0xc0021f99e0, 0x7f0dd20, 0xc003889400)
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/routers.go:225 +0x4b
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*routerOutputOp).cancel(0xc0021f99e0, 0x7f0dd20, 0xc003889400)
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/routers.go:238 +0x58
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*HashRouter).Run.func1(0x7e9e3e0, 0xc005892b70)
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/routers.go:457 +0xa3
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*HashRouter).Run(0xc0021f9b00, 0x7f0dd20, 0xc003889400)
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/routers.go:497 +0x1b6
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreator).setupRouter.func1(0x7f0dd20, 0xc003889400, 0xc001ce1450)
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:676 +0xa5
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreatorHelper).accumulateAsyncComponent.func1.1(0xc003a6e1a0, 0x7f0dd20, 0xc003889400, 0xc001ce1450, 0xc004052f70)
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1171 +0x44
created by github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreatorHelper).accumulateAsyncComponent.func1
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1170 +0x6f


```

[1]: https://github.com/cockroachdb/sqllogictest/blob/master/test/select4.test

**Comment by Azhng** [comment]
Another behaviour of this query: further attempt to simplify the query result int `memory budget exceeded` error instead of nil pointer exception.

**Comment by Azhng** [comment]
Query plan: https://cockroachdb.github.io/distsqlplan/decode.html#eJzUV9tu20YTvv-fYrBXkrGGd_a8Agww-OMgLlI7tQ20QOAL2drGAhTRJWmgQZB3L0RaFCUe1qvCUXpHLjk738x8c_pG8r8WZEKuzz6c_f8GnrIFvLu6_BU-nf3x8cOb8wsYvT2_vrn-7cMYnn_xlsLMUJgqOALtBAXPKXgNRyCloXCH1Q0FUig0hcJQKBSFwlIoOPz-_uzqDEaj0b2C1fXSOgpcMQqOGwpWKQraGQoo2OpVj8fw5uLtSgItg1PwdgyXVzASQlRv1au3cArCjte_ewOnIDVfv99xOIU7HN8SSpbpzF9Mv_icTD4RJJRwQokgt5Q8Zum9z_M0W336Vv54PvubTBgl8-XjU7E6vqXkPs08mXwjxbxYeDIhN9O7hb_y05nPTlb3zXwxnS_K6x-z-Zdp9jUpVjquH6fLfAInSkrHrLNOOYVcGBTHmzPHtELL0BBKLp-KCSScJorcfqckfSo2IPJi-tmTCX6n-wFVPUBNF1BuDRPWGdMAKo3gyimOMF3OwEJaPPgsJ5S8my8Kn00gUVUMJpPJ-cWNre2RQ_bwXns2Zjwt02zmMz_bMuF2JRn6pcMp76f5wy_pfOmzE73tkwou0lUEBE1kL2ixbxBMTxDUJggNj2sUDBWTlcex8njT4aLMKRTs2eVlatXP0rr6WTtTP1ulGs-6fnZ8_c-4jh3SRPS6Qe7rBuQ9frBdZNTGKec0NsnouEapmXSla0SbjKNRSUe0a39UdaM8FEKsD5untmV9P23VIWmLYoC3vZD1QSHL4VSjiaKJponphW_2Jltf0unOEo2GO7ddopWzVjmuVUk2tSFbiCX2oC63L3Q5TeyOBZv77r7CwzR_2L4pQVIqf7bS7RsZznoig509SSNaxbhqREYowRhzGrsjw_-VXcgOGT6-UyMX_s9ilOD4NJt_fiifCCVXfjkrO4GhkAgKiTrSTtQVPeEUEnsk5ab4J65_tOifLfYy5iI9Th9PuNr1TLfy7UEAX86iPhLxzp5aj2A7PTV69IpAKMKjVwMhZ5ppx59bm3mVOSsCvAuPLGvsjhmGK986cfzTjikRpmMftWxn4FYDibDcVNTSB55JYuzs2w10p51ScyGNMaa0k-_bDiMA8r4tq7NR1E2hiVlJi4jC7CbVKzQK_MGNQh64UfCIQMZsy_VmfLwpMEwaJ6Vhap-SHQFURm3L64p93LFBv2IVj7DHvryKN_bOhj3GCGdQKvOf2EUjPIN9taVzF61r_FY9ZEoq9Vxb1IHrfozpOmYzqsv-cce2VJou920FMZj75hHsHqbWS8NuT36Fus9_cN0XP9GC0AH1yueP6TL3Lxr_2cpYP_vsK-fl6VN27z9m6X2ppnq9LOXKg5nPi-orr17Ol-WnEmBTGCOE-a4wHxTWw5rFoLAaFpYRwi3YKgJ2S1gPCtth2CZCuKXZ7gpjUxjZsOphaR7wd0B3wGwXg7xl97A0DwQ7oDvgcxxOLsRAdgXSa5trrCU-nGCh1B7OsEBuY0yKtXUP51ggZhiTZG3pVpZF0S0gHuJbSHsIfCvT4gjXonsMY3hMK2l3g2GyBxjDh7ke8Dof5nrA6bzF9SjGBMRDjAlpD4EfTrUWY26__--fAAAA__9Ex3Q8

**Comment by Azhng** [comment]
The stacktrace above is actually misleading. 

We catch the runtime error inside hash router [here][1] and attempt to cancel all `routerOutputOp` the router is attached to. However at this point the nil pointer dereference has already happened. The stack trace above comes from the attempt by hash router to cancel operations. 

More accurate stack trace: 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x5be4f6a]

goroutine 3128 [running]:
github.com/cockroachdb/cockroach/pkg/col/colserde.(*FileSerializer).AppendBatch(0xc0032b53e0, 0x7f75f40, 0xc0029d51c0, 0x5bf900b, 0xc0029d51c0)
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/col/colserde/file.go:108 +0x2a
github.com/cockroachdb/cockroach/pkg/sql/colcontainer.(*diskQueue).Enqueue(0xc0034fa000, 0x7f0cce0, 0xc002532580, 0x7f75f40, 0xc0029d51c0, 0xc0029d53c0, 0xc0028e0870)
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/sql/colcontainer/diskqueue.go:541 +0x29a
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*spillingQueue).enqueue(0xc000e58f00, 0x7f0cce0, 0xc002532580, 0x7f75f40, 0xc0029d51c0, 0x7f75f40, 0xc0029d51c0)
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/spilling_queue.go:144 +0x166
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*routerOutputOp).addBatch(0xc0035ff5f0, 0x7f0cce0, 0xc002532580, 0x7f75f40, 0xc003203280, 0xc001259bc8, 0x1, 0x1, 0xc0020fc400)
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/routers.go:313 +0x3db
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*HashRouter).processNextBatch(0xc0035ff9e0, 0x7f0cce0, 0xc002532580, 0x73a4500)
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/routers.go:527 +0x2ca
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*HashRouter).Run.func2(...)
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/routers.go:462
github.com/cockroachdb/cockroach/pkg/sql/colexec.(*HashRouter).Run(0xc0035ff9e0, 0x7f0cce0, 0xc002532580)
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/routers.go:496 +0x111
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreator).setupRouter.func1(0x7f0cce0, 0xc002532580, 0xc0025b83f0)
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:676 +0xa5
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreatorHelper).accumulateAsyncComponent.func1.1(0xc0033605e0, 0x7f0cce0, 0xc002532580, 0xc0025b83f0, 0xc0007128b0)
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1171 +0x44
created by github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlowCreatorHelper).accumulateAsyncComponent.func1
	/Users/azhng/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:1170 +0x6f


```

[1]: https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/colexec/routers.go#L496

**Comment by yuzefovich** [comment]
After some debugging I saw that we actually are hitting a memory budget error for disk storage (note that the tests run with in-memory storage engine that has 100MB limit), so the expected behavior (without changing that constant) is hitting a memory error.

I believe this issue actually exposes three problems:
1. `diskQueue` somehow ends up in a state that causes `nil` pointer crash. First commit from #47238 addresses that.
2. we didn't wrap the cancellation of hash router's outputs with a panic-catcher, and second commit addresses that.
3. if we increase the batch size from 1 (with which we hit memory limit error) to a slightly larger size (say 3), the query finishes but returns wrong number of rows. I don't know what's up with this yet.

**Comment by yuzefovich** [comment]
Oh, actually randomizing the batch size doesn't matter for the correctness of the output - even if we keep it at `1024`, the number of rows in the output is still incorrect.

**Comment by yuzefovich** [comment]
So the error in point 3 above is `expected 18432 results, but found 25344`, and the problem is that the query asks for 8 columns, but somehow 11 are hashed (the query returns 2304 rows). I remember seeing a similar issue before, like a year ago, with the big test.

**Comment by yuzefovich** [comment]
This problem appears on all of the configurations, and it seems like an issue with the test harness:
```
    --- PASS: TestLogic/local (0.00s)
    --- FAIL: TestLogic/local-vec-off (0.00s)
        --- FAIL: TestLogic/local-vec-off/temp (2.35s)
            logic.go:1858: 
                 
                testdata/logic_test/temp:3095: expected 18432 results, but found 25344
    --- PASS: TestLogic/local-v1.1@v1.0-noupgrade (0.00s)
    --- FAIL: TestLogic/local-vec (0.00s)
        --- FAIL: TestLogic/local-vec/temp (0.73s)
            logic.go:1276: randomize batchSize to 1024
                
            logic.go:1858: 
                 
                testdata/logic_test/temp:3095: expected 18432 results, but found 25344
    --- PASS: TestLogic/fakedist (0.00s)
    --- PASS: TestLogic/local-mixed-19.2-20.1 (0.00s)
    --- FAIL: TestLogic/fakedist-vec-off (0.00s)
        --- FAIL: TestLogic/fakedist-vec-off/temp (2.38s)
            logic.go:1858: 
                 
                testdata/logic_test/temp:3095: expected 18432 results, but found 25344
    --- FAIL: TestLogic/fakedist-vec (0.00s)
        --- FAIL: TestLogic/fakedist-vec/temp (1.29s)
            logic.go:1276: randomize batchSize to 1024
                
            logic.go:1858: 
                 
                testdata/logic_test/temp:3095: expected 18432 results, but found 25344
    --- FAIL: TestLogic/fakedist-vec-disk (0.00s)
        --- FAIL: TestLogic/fakedist-vec-disk/temp (1.88s)
            logic.go:1276: randomize batchSize to 1024
                
            logic.go:1858: 
                 
                testdata/logic_test/temp:3095: expected 18432 results, but found 25344
```
I'll try to find the discussion that we had about this column number mismatch previously.

**Comment by yuzefovich** [comment]
Oh yeah, found it: https://cockroachlabs.slack.com/archives/C04U1BTF8/p1568045969165400

The tl;dr is that sqllite logic tests should not be run with just `make testlogic` as regular (our own) logic tests are run.
