### ISSUE TITLE
jobs,bulk,*: Provide more visibility into job status

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#47212]
Better per-processor status reporting -- what is throughput, where is it blocked, what is _recent_ throughput, are we encountering underlying errors / retrying / etc. More visibility into what jobs are _doing_ in general. TODO(dt, bulk): brainstorm and write out some specific sub-goals here.

**Comment by mwang1026** [comment]
- Debugging endpoint--be able to get there and see status of every goroutine and processor working on behalf of this job
- Ideally throughput on processor and node level--immediately see where throughput is lowest
- Revising milestones as we start using this more

---

- (?) Job progress table?

---

- Getting onto jobs page is a bit more work

**Comment by mwang1026** [comment]
PRs coming soon

**Comment by livlobo** [comment]
Closing in favor of other tracing work here: https://github.com/cockroachdb/cockroach/issues/64992
