### ISSUE TITLE
backupccl: Backup/Restore are too slow

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#47221]

**Comment by pbardea** [comment]
Going to close this until we have more concrete goals describing what we want to accomplish with perf here.

I will mention that refactoring restore to use distsql to distribute work should have helped with restore's ability to scale to many nodes. These are the times it took for restore2TB to run on a cluster with 3, 6, 12, and 24 nodes.
3	- reached 55% when 6 nodes finished (it eventually ran out of disk space 😢)
6	- 2:12:04
12	- 1:15:57
24	- 0:38:46

**Comment by Heoric** [comment]
@pbardea  Do I need to adjust any parameters? Why is the speed of my test restore so slow?

**Comment by piao88** [comment]
Hi,@pbardea
I have to say that crdb is a great database, our company is considering to pay to use your database, but we are concerned about the restore speed of cockroachdb, we restore 480GB data with 20 nodes after parameter tuning
(
set cluster setting `kv.bulk_sst.sync_size`='8MiB';   
set cluster setting `kv.bulk_io_write.concurrent_import_requests`=10;   
set cluster setting `kv.bulk_io_write.concurrent_addsstable_requests`=10;
),
 the result is more than 3 hours, far from your test results, do you know how this is?
