### ISSUE TITLE
Feature: security hardening improvements

### ISSUE THREAD

**Issue by hazcod** [cockroachdb/cockroach#47249]
I've reworked the Dockerfile and docker.compose file to a hardened format, from a security perspective. https://github.com/ironPeakServices/iron-cockroachdb

Would be nice if this would flow back to the project.

Jira issue: CRDB-5020

**Comment by jordanlewis** [comment]
cc @aaron-crl

**Comment by knz** [comment]
@catj-cockroach is there something useful for us to salvage here? Or perhaps @rail ?

**Comment by rail** [comment]
@hazcod Thanks for your ideas!

Using an unprivileged user is something we are going to look at ASAP.

I'm not sure if `FROM scratch` is going to work for us for a few reason:
* I've heard some consumers want some basic system tools installed in the image to simplify debugging.
* We use the Red Hat UBI image now as our base to unify our image with our Redshift/Red Hat connect images.

Thank you again!
