### ISSUE TITLE
sql,kv: failure to gossip system config due can orphan table descriptor leases

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#47304]
**Describe the problem**

Table descriptors are leased in order to provide a coherent cache. The online schema change mechanism ensures that at most the two most recent versions of a table are leased. The execution of transactions which change table descriptor versions wait for the newly published version to be the only leased version of the table (either directly or indirectly by waiting for a job). 

Nodes get notified of the need to drop leases on older versions via gossip. Transactions which touch table descriptors set a special trigger on their transaction that leads to the leaseholder for the system config span to *attempt* to gossip the updated data. The *attempt* is important. As we can see in the below code, the gossip will not occur if there are outstanding intents on the range.

https://github.com/cockroachdb/cockroach/blob/cc7ce806b4711b69c04560a393ccfbdcd6eb97a0/pkg/kv/kvserver/replica_gossip.go#L96-L97

This behavior feels like it might be reasonable. If there are intents, the data doesn't necessarily represent a consistent snapshot. In a sense, the logic seems to assume that those intents are going to become writes and will lead to an even newer value being gossiped in the future. Unfortunately this has a bad interaction with the way that some schema changes interact with leasing. In particular, when a schema change fails to verify that lease invariant is upheld, that schema change will sit in a retry loop waiting for there to be leases on just one version of the table. 

https://github.com/cockroachdb/cockroach/blob/5f1536f6bfb6943ce44217fcb4b81a7eec983612/pkg/sql/conn_executor_exec.go#L567-L577

The problem of course is if the transaction that fails in the above code had laid down an intent prior to the committing of the transaction which ultimately will lead to its failure, then no notification will ever be sent and the lease its waiting to drop won't get dropped because no notification was sent.

The same problem can befall the waiting inside of the schema changer due to multi-step schema changes (the repro below will deal with these cases). 

https://github.com/cockroachdb/cockroach/blob/5f1536f6bfb6943ce44217fcb4b81a7eec983612/pkg/sql/lease.go#L305-L311

**To Reproduce**

`(conn A)`
```
CREATE TABLE bar (i INT PRIMARY KEY);
INSERT INTO bar VALUES (1);
```
`(conn B)`
```
BEGIN; 
CREATE TABLE foo (i INT PRIMARY KEY);  -- lay down an intent on the system config span
```
`(conn A)`
```
BEGIN;
ALTER TABLE bar ADD COLUMN j INT NOT NULL DEFAULT 1;
COMMIT; -- will hang for ~5 minutes
```
`(conn B)`
```
ROLLBACK; -- if we committed here then there would be a gossip event
```

**Expected behavior**

The schema change in `(conn A)` completes in a timely manner.

**Additional context**
This problem is likely to go away in 20.2 as we adopt rangefeeds as the mechanism to notify nodes of changes to table descriptors. That being said, this is a real problem today and deserves to be fixed.

**Potential Solutions**

This one is a tricky given the above context. We want something that isn't too invasive and can get backported. This is made trickier because the gossip hook happens underneath the raft in the kv layer. There are a few classes of solutions which occur to me:

1) Detect the failure to gossip due to intents in the kvserver and starts a process there to wait for no intents to exist and does the gossip.

This seems sort of okay, we spin off at most one loop with a retrier that checks some conditions, namely that there are no intents and that the replica is still the leaseholder and we haven't gossipped since kicking off the loop. The risk here is that the intent checking is awkward and potentially expensive. I'm more worried about the awkwardness than the cost given the cost of doing the gossip in the first place. Even still there's an open question about how we'd force the gossip anyway. The cleanest way seems to be to do some no-op write with the trigger set. This all feels pretty gross.

A possible benefit of this solution is it doesn't involve changing any logic underneath raft.

2) Detect the failure to gossip due to intents in the kvserver and provide information to maybe gossip the system config when aborting a transaction which has set the system config trigger and try to gossip if the last time we tried to gossip we failed because of intents. 

I think this is my preferred approach. It's pretty straight-forward and it feels safe. The downside is that it's going to add more replica state and it's going to add some more logic underneath raft. 

A sketch of this is:

a) Add a boolean (maybe something more?) under Replica.mu which is like `failureToGossipSystemConfig`
b) Set the boolean when failing to gossip due to an intent, clear it on a successful gossip or if you ever lose the lease
c) Add a local result trigger boolean like `LocalResult.MaybeGossipSystemConfig`, perhaps `MaybeGossipSystemConfigIfHaveFailure` that is set if the trigger is set and the `EndTxn` command is moving the transaction to `ABORTED`
d) Call `MaybeGossipSystemConfig` if the replica has `failureToGossipSystemConfig` set.

3) Try to force an update from within the various retry loops that keep failing.

This would be the least invasive but probably least principled solution to this problem. We could imagine that in `WaitForOneVersion` we look at the local copy of the system config and see if the table descriptor version is older than the version we know to exist from our examination of the leases table. If we see that it is, we run a no-op txn with the system config trigger set to try to tickle gossip. We could rate limit this. Furthermore we could ensure that the gossip network is live. 

**Proposal**

Given the fact that any dependence on the reliability of gossip is going away very soon, and with it, maybe too the `SystemConfigTrigger`, or at least any real dependency on the reliability of gossip, I'm tempted to suggest pursuing 3). That being said, 3) feels gross and I suspect we'll continue to use this trigger for a while yet. especially for cluster settings. Given that, I'd like to propose moving forward with 2).

**Comment by ajwerner** [comment]
@nvanbenschoten or @tbg I'm curious to hear if y'all have thoughts on this before I go off and type up a fix.

**Comment by tbg** [comment]
Hmm, interesting. One more reason to be glad gossip isn't going to be used here. 2) sounds like a reasonable choice. We will be stuck with gossiped settings for a bit I'm afraid.

**Comment by nvanbenschoten** [comment]
Number 2 also sounds reasonable to me, although it does seem to contain a lot of moving parts, especially for a backport.

How much do we benefit from being selective about calls to `MaybeGossipSystemConfig`? Did you consider setting `MaybeGossipSystemConfig` non-discriminately on rollbacks of transaction records on the system config range? Are there cases where we expect this to be common? Are you concerned about system config gossiping being expensive in cases where transactions are frequently rolling back? Is that concerning enough to justify the complexity of `MaybeGossipSystemConfigIfHaveFailure` and `failureToGossipSystemConfig`?

**Comment by ajwerner** [comment]
>  Are you concerned about system config gossiping being expensive in cases where transactions are frequently rolling back? 

That had been the thought. Every time we call `MaybeGossipSystemConfig` we do a scan of the whole thing. Upon reflection, it seems reasonable to do it for every rollback as they should only be common in pathological cases. It's possible that that might have provided good back-pressure in all of those cases of the touch write to the table descriptor to grab the table lease that then got aborted in a loop. 

I'm open to the idea of simplifying this commit dramatically and just adding a `MaybeGossipSystemConfig` trigger where currently I add the new trigger. On the whole I didn't find the change to be so huge as to scare me away from backporting it but at the same time I see the value in the simplicity of your suggestion. Shall we discuss on https://github.com/cockroachdb/cockroach/pull/47462?
