### ISSUE TITLE
sql: errors during schema change rollback are getting swallowed

### ISSUE THREAD

**Issue by lucy-zhang** [cockroachdb/cockroach#47324]
If an error occurs while executing a schema change rollback (i.e., while running the reversed schema change), we log it and swallow it, causing the job to end up in a terminal state. See #47323 for an example. The problem is here:
https://github.com/cockroachdb/cockroach/blob/28473ec279d6b3ccd4b1c2ad04acb52b505e49c0/pkg/sql/schema_changer.go#L659-L673
This was carried over from 19.2, when the async schema changer would retry the reversed schema change. To preserve the same behavior in 20.1, though, the intention when porting schema changes to jobs was that we'd have to keep the job in the `reverting` state so that it could keep retrying. The retry handling is in `OnFailOrCancel`, but I didn't realize we were swallowing these errors before they even bubble up to `OnFailOrCancel`.

**Comment by knz** [comment]
Previously:

https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20190318_error_handling.md#unexpected-errors-encountered-while-handling-other-errors
