### ISSUE TITLE
log spam on loading the geos module

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#47332]
Every invocation of the `cockroach` binary spams my log with:

```
I200410 15:15:45.809058 1 geo/geos/geos_unix.go:91  cannot load GEOS from /data/home/kena/cockroach/lib/libgeos_c.so: Undefined symbol "_nss_cache_cycle_prevention_function"
```

There are a few problems with this:

1) this tells me the logging is taking place from an `init()` function somewhere, which is violating the initialization protocol of the `util/log` package. It is important that no log calls take place before the log subsystem has been initialized.

2) this tells me that the loading is occurring regardless of which `cockroach` sub-command is being run. The geos stuff should only be loaded for `cockroach start` and `cockroach demo`.

3) the "Undefined symbol" error above is worrying. What does it mean?

**Comment by petermattis** [comment]
`_nss_cache_cycle_prevention_function` is a FreeBSD-ism: https://stackoverflow.com/questions/3559147/dlerror-undefined-symbol-nss-cache-cycle-prevention-function-on-freebsd-7-2. I haven't wrapped my head around what it is telling us.

@otan We should refactor the geos initialization out of the `init()` function and into a function that is explicitly called from server start.

**Comment by petermattis** [comment]
The link above suggests that we're calling `dlerror()` inappropriately on FreeBSD and it gives advice for the correct way to call `dlerror()`.
