### ISSUE TITLE
sql: Parenthetical SELECTs throw away ORDER BY

### ISSUE THREAD

**Issue by paperstreet** [cockroachdb/cockroach#4734]
repro: https://github.com/paperstreet/cockroach/commits/parenselect_order

    testdata/order_by:136 root: (SELECT a FROM t) ORDER BY a DESC
    --- FAIL: TestLogic (0.06s)
      logic_test.go:659: testdata/order_by:136: expected:
        "5"
        "4"
        "3"
        "2"
        "1"
        but found:
        "1"
        "2"
        "3"
        "4"
        "5"

**Comment by petermattis** [comment]
I imagine there is some silly oversight in the code. Definitely would be a good intro to the code to track down what is going on. Let us know if you need any guidance.

**Comment by paperstreet** [comment]
Ah, I should have mentioned that I did actually find the bug, was going to take a look at fixing it today

**Comment by paperstreet** [comment]
Oops, wrong button : - /

**Comment by tamird** [comment]
You can probably keep this issue open until the bug is fixed.
