### ISSUE TITLE
vendor: dependencies that become unused are left over

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#47363]
If the last import of a vendored dependency goes away, nothing forces the commit in question to remove the dependency from the vendored repo. Worse, the next sucker who runs `dep ensure` to muck with some other dependency will have the surprise of seeing the useless dependency removed at that point, unexpectedly. Which is very confusing, and a pain to figure out why and how.

We have a check that TC is supposed to do to ensure that the vendored repo is copacetic, but it fails to catch this case. The check in question only runs when dependencies change, not when our imports change:
https://github.com/cockroachdb/cockroach/blob/275e620bafc71bbb6227f722c4e0a1804e8eed7d/pkg/cmd/github-pull-request-make/main.go#L220

This has just happened when @otan deleted some imports [here](https://github.com/cockroachdb/cockroach/pull/47171/commits/812d20acc12f543e2bf623b42e3608a25ed0f7f0#diff-e6666b0044cf6611934e1f894e2438fd). @dt helped me figure it out.

I think we should run a `dep ensure` nightly to catch this.

Epic CRDB-10447

Jira issue: CRDB-5015

**Comment by bobvawter** [comment]
This would be obviated by switching the build to go modules per #38824

**Comment by rickystewart** [comment]
This should be resolved by `go mod tidy`, etc.
