### ISSUE TITLE
Common Table Expression parsing error

### ISSUE THREAD

**Issue by cainiaokan** [cockroachdb/cockroach#47374]
---
name: Bug report
about: Common Table Expression parsing error

---

**Describe the problem**

CTE parseing error.  sql parser complains: no data source matches prefix: ranges

**To Reproduce**

1. Send SQL as below:
`
WITH ranges AS (
  SELECT
    pg_range.rngtypid,
    pg_type.typname AS rngtypname,                                                                                             
    pg_type.typarray AS rngtyparray,
    pg_range.rngsubtype
  FROM pg_range LEFT OUTER JOIN pg_type
  ON pg_type.oid = pg_range.rngtypid
)
SELECT rngtypname, rngtypid, ranges.rngtyparray from ranges;
`

2. See error 

> no data source matches prefix: ranges

**Expected behavior**
sql execution success

**Additional data / screenshots**

**Environment:**
 - CockroachDB version 19.1.0
 - Server OS: x86_64-unknown-linux-gnu
 - Client app cockroach client for macOS

**Additional context**

**Comment by cainiaokan** [comment]
---
name: Bug report
about: Common Table Expression parsing error

---

**Describe the problem**

CTE parseing error.  sql parser complains: no data source matches prefix: ranges

**To Reproduce**

1. Send SQL as below:
WITH ranges AS (SELECT pg_range.rngtypid, pg_type.typname AS rngtypname,                                                                                                   pg_type.typarray AS rngtyparray, pg_range.rngsubtype                                                                                           FROM pg_range LEFT OUTER JOIN pg_type ON pg_type.oid = pg_range.rngtypid                                                                        ) SELECT rngtypname, rngtypid, ranges.rngtyparray from ranges;

2. See error 

> no data source matches prefix: ranges

**Expected behavior**
sql execution success

**Additional data / screenshots**

**Environment:**
 - CockroachDB version 19.1.0
 - Server OS: x86_64-unknown-linux-gnu
 - Client app cockroach client for macOS

**Additional context**

**Comment by cainiaokan** [comment]
By the way, cockroachdb version 19.2.1 doesn't have this problem.

**Comment by RaduBerinde** [comment]
So it was fixed in 19.2 right? Do you need the fix in 19.1.x or can you upgrade to 19.2?

**Comment by cainiaokan** [comment]
> So it was fixed in 19.2 right? Do you need the fix in 19.1.x or can you upgrade to 19.2?

Yes, I can confirm this was fixed in 19.2. I've upgrade to 19.2 now.

**Comment by RaduBerinde** [comment]
Thanks! Closing this then.
