### ISSUE TITLE
c-deps/rocksdb: RocksDB sstable ingestion has an expensive O(num-sstables) factor

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#47375]
Running a large IMPORT on a cluster with large disks shows the IMPORT slowing down over time:

![Screen Shot 2020-04-11 at 7 19 48 AM](https://user-images.githubusercontent.com/6201335/79045604-fe224580-7bd9-11ea-9681-60eb21909bc1.png)

The slowdown corresponds to an increasing number of sstables in the cluster:

![Screen Shot 2020-04-11 at 7 20 44 AM](https://user-images.githubusercontent.com/6201335/79045610-07abad80-7bda-11ea-8220-612b4e88f6f4.png)

The IMPORT primarily consists of sstable ingest operations, which should be O(1) to commit. Yet we can see that commit latency is increasing significantly over time:

![Screen Shot 2020-04-11 at 7 20 08 AM](https://user-images.githubusercontent.com/6201335/79045630-21e58b80-7bda-11ea-813f-a50e3e782a96.png)

A flamegraph profile shows significant CPU time being spent in ingestion. (See #47330 for why `DBStats` is so slow):

![Screen Shot 2020-04-11 at 7 21 46 AM](https://user-images.githubusercontent.com/6201335/79045662-3b86d300-7bda-11ea-8f2f-48a6b2e601e1.png)

The `web` profile shows that the major component of ingestion CPU usage is in `FileIndexer::UpdateIndex`:

![Screen Shot 2020-04-10 at 6 41 19 PM](https://user-images.githubusercontent.com/6201335/79045689-5f4a1900-7bda-11ea-8236-0ca028a8fd99.png)

The index structure maintained by `FileIndexer` is used to accelerate `rocksdb::DB::Get` operations using [fractional cascading](https://rocksdb.org/blog/2014/04/21/indexing-sst-files-for-better-lookup-performance.html). Unfortunately, that index seems to be rebuilt every time the LSM changes, such as on every ingestion operation. Even more unfortunately, CockroachDB never performs `Get` operations (it always uses iterators), so maintenance of this index is purely wasted work. There appears to be no way to disable the `FileIndexer` cleanly. While it seems possible that the indexing could be optimized, it may be better to simply recommend using Pebble on large disks as Pebble does not have a similar indexing operation, and if we ever add it we'll be careful to make the index maintenance efficient.

Cc @ajwerner, @andy-kimball, @johnrk

**Comment by andy-kimball** [comment]
Do either of these issues (FileIndexer or DBStats) affect regular read/write scenarios where no import is in progress?

**Comment by petermattis** [comment]
> Do either of these issues (FileIndexer or DBStats) affect regular read/write scenarios where no import is in progress?

They would affect heavy write workloads with a large amount of data per node. There is likely little impact on heavy read workloads with a large amount of data per node. The `DBStats` problem will cause a small CPU blip every time we record store metrics (every 10s). The consistency checker queue pacing (https://github.com/cockroachdb/cockroach/issues/47290) is a bigger problem than either the `FileIndexer` or `DBStats` issues for normal workloads on large per node data sizes. Luckily, that one is completely under our control and should be straightforward to fix.

**Comment by petermattis** [comment]
We're moving away from RocksDB, so this is unlikely to be fixed (and unnecessary).
