### ISSUE TITLE
opt: eliminate INNER JOIN when FK present and columns not referenced

### ISSUE THREAD

**Issue by andy-kimball** [cockroachdb/cockroach#47391]
This is a common case when using views:
```
root@:26257/defaultdb> CREATE TABLE cust (c_id INT PRIMARY KEY, c_name STRING);

root@:26257/defaultdb> CREATE TABLE ord (o_id INT PRIMARY KEY, o_cust_id INT NOT NULL REFERENCES cust (c_id));

root@:26257/defaultdb> CREATE VIEW cust_ord AS SELECT c_id, c_name, o_id, o_cust_id FROM cust INNER JOIN ord ON c_id=o_cust_id;

root@:26257/defaultdb> EXPLAIN (opt) SELECT o_id, o_cust_id FROM cust_ord WHERE o_id=100;
                      text
------------------------------------------------
  project
   └── inner-join (lookup cust)
        ├── lookup columns are key
        ├── scan defaultdb.public.ord
        │    └── constraint: /3: [/100 - /100]
        └── filters (true)
```
Here, the `cust` lookup can be eliminated. This is because the FK guarantees that for every order, there will be exactly one corresponding customer. And since no customer columns are projected, there's no reason to perform the join.

NOTE: Elimination is only possible when the FK columns are not null. Also, see `JoinFiltersMatchAllLeftRows`, since there is overlap and possible opportunities for shared functions.

**Comment by andy-kimball** [comment]
One other comment: The NULL case can be taken care of by adding an explicit `IS NOT NULL` check to the result for each FK column. For example, if the `o_cust_id` column was nullable in the example above, then:
```
SELECT o_id, o_cust_id FROM cust_ord WHERE o_id=100;
```
could be mapped to:
```
SELECT o_id, o_cust_id FROM ord WHERE o_id=100 AND o_cust_id IS NOT NULL;
```

**Comment by andy-kimball** [comment]
I believe this rule can also be applied to `SemiJoin`:
```
root@:26257/defaultdb> explain (opt) select * from ord where exists(select * from cust where c_id=o_cust_id);
             text
------------------------------
  semi-join (hash)
   ├── scan ord
   ├── scan cust
   └── filters
        └── c_id = o_cust_id
```
The semi-join can be eliminated in this case.

**Comment by RaduBerinde** [comment]
@DrewKimball I think your recent improvements addressed this, right? (even the semi-join case?)

**Comment by DrewKimball** [comment]
Actually, I haven't handled the semi-join case; I'll have to extend the JoinMultiplicity code for that. While it won't be too difficult, I'm not sure it makes a lot of sense to talk about whether rows from the right side of a semi-join are duplicated or preserved. It's kind of similar to the UnfilteredCols issue...

I'm wondering if it might be a good idea after all to have the Multiplicity struct model the theoretical inner join properties that result from the filters, and then just store the join operator type as well. For example, the 'inner join properties' of a LeftJoin operator might not preserve left rows even though the concrete operator does. Doing this might be more intuitive for the slightly more exotic join types.

**Comment by RaduBerinde** [comment]
Yes, that makes a lot of sense to me. We can have helper functions that also take in the type of join to answer questions about the particular join operation. We discussed this before here: https://reviewable.io/reviews/cockroachdb/cockroach/49475#-M81l2x29rtHMM4Sm4L5
