### ISSUE TITLE
opt: map NOT bool_col to bool_col=FALSE so that lookup join can be used

### ISSUE THREAD

**Issue by andy-kimball** [cockroachdb/cockroach#47396]
Add a rule to map `NOT bool_col` to `bool_col=FALSE`. Something like:
```
(Not $input:*)
=>
(Eq $input (False))
```
Adding this rule would enable lookup joins in cases like this (including a case in the `trading` test):
```
root@:26257/defaultdb> CREATE TABLE vals (optional BOOL, val INT, PRIMARY KEY (optional, val));
root@:26257/defaultdb> EXPLAIN (opt) SELECT * FROM (VALUES (100,false), (200,true)) v(x,y) INNER JOIN vals ON val=x AND NOT optional;
                      text
-------------------------------------------------
  inner-join (hash)
   ├── scan vals
   │    └── constraint: /3/4: [/false - /false]
   ├── values
   │    ├── (100, false)
   │    └── (200, true)
   └── filters
        └── val = column1
```
EXPECTED: This should use a lookup join rather than a hash join. It uses a lookup join when manually updating `NOT optional` to be `optional=False`.

**Comment by RaduBerinde** [comment]
I am not sure about the rule, it might conflict with other Not rules. We should be able to extract the same equality from `optional` or `NOT optional` just as well though. Actually, we have this TODO here:
https://github.com/cockroachdb/cockroach/blob/4994d4a9b48870424790b3a24968db3ead051fc4/pkg/sql/opt/memo/extract.go#L329

I will look at addressing the TODO. We shoudl already have the constraint in the FiltersItem scalar props.
