### ISSUE TITLE
sql: support interleaved tables with hash sharded indexes

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#47421]
**Is your feature request related to a problem? Please describe.**

Today's experimental implementation of hash sharded indexes does not work with interleaved tables.

Tables which are hash sharded are a likely use case for interleaving as they are utilized in cases where developers are thinking about access patterns. Put differently, they are advanced features which ought to combine nicely but today is disallowed.

**Comment by awoods187** [comment]
I'm closing this issue since we intend to deprecate interleaving tables.
