### ISSUE TITLE
ui: new tooltips for storage metrics

### ISSUE THREAD

**Issue by taroface** [cockroachdb/cockroach#47429]
Many of the tooltips defined in [Storage Metrics](https://docs.google.com/document/d/1fn_MZH0YNhBY3Uirh-Icp5Psgkz_7uXwiStaDArMHaI/edit) require the creation of new tooltip elements in the UI rather than editing existing tooltips. In the doc, these are indicated in bold.

Sections in document that require tooltip changes:

# Cluster Overview Page
- [ ] Capacity Usage
- [ ] Node List
- [ ] Node Detail
- [ ] Node Map

# Metrics Page
- [ ] Sidebar
- [ ] Overview dashboard: capacity map
- [ ] Hardware dashboard: available disk capacity map
- [ ] Storage dashboard: capacity graph
- [ ] Storage dashboard: live bytes graph
- [ ] Replication dashboard: logical bytes per store graph

# Databases page
- [ ] Databases page
- [ ] Non-table Cluster Data Sizes
- [ ] Tables & Table Details

**Comment by dhartunian** [comment]
@dhartunian add checklist of all tooltips TBD in this issue.

**Comment by elkmaster** [comment]
@dhartunian, this pr contains tooltips from `Storage dashboard` section of that [doc](https://docs.google.com/document/d/1fn_MZH0YNhBY3Uirh-Icp5Psgkz_7uXwiStaDArMHaI/edit). Except chart legend elements. They can't contain tooltip.

**Comment by dhartunian** [comment]
> @dhartunian add checklist of all tooltips TBD in this issue.

This is done above. I will link with PRs as they're created.
