### ISSUE TITLE
opt: filter pushdown from check constraints doesn't happen for non-predicate columns

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#47426]
**Describe the problem**

The issue in the title may not capture the problem. I'll put examples here.
In https://github.com/cockroachdb/cockroach/pull/37616 we added support to push constraints into queries. This provided the basic building-block to utilize hash-sharded indexes. In that case we primarily considered predicates which use columns other than the column involved in the constraint.

**To Reproduce**

Imagine the following table:

```
CREATE TABLE users (
    user_id text,
    shard_id
        INT8
        AS (fnv32(
                 user_id::STRING
                 )
            % 8) STORED
        CHECK (shard_id IN (0, 1, 2, 3, 4, 5, 6, 7)),
    last_active_at int,
    PRIMARY KEY (user_id),
    INDEX (shard_id, last_active_at, user_id) -- same applies even if user_id is not here
);
```

Now imagine that we want to find a value based on `last_active_id`. I'd expect that we'd be able to constraint the spans:

```
root@127.0.0.1:36513/defaultdb> EXPLAIN select * from users where last_active_at = 399780 ;                                                                                                                       
  tree |    field    |       description
-------+-------------+--------------------------
       | distributed | true
       | vectorized  | true
  scan |             |
       | table       | users@primary
       | spans       | FULL SCAN
       | filter      | last_active_at = 399780
(6 rows)

Time: 2.085426ms

root@127.0.0.1:36513/defaultdb> EXPLAIN select * from users where last_active_at = 399780 AND shard_id IN (0, 1, 2, 3, 4, 5, 6, 7);
  tree |    field    |                                                                           description
-------+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------
       | distributed | false
       | vectorized  | false
  scan |             |
       | table       | users@users_shard_id_last_active_at_idx
       | spans       | /0/399780-/0/399781 /1/399780-/1/399781 /2/399780-/2/399781 /3/399780-/3/399781 /4/399780-/4/399781 /5/399780-/5/399781 /6/399780-/6/399781 /7/399780-/7/399781
(5 rows)

Time: 734.414µs
```

**Expected behavior**

The filter should be pushed down automatically.

**Environment:**

The issue was originally raised on 19.2.5 but exists on master.

**Comment by rytaft** [comment]
cc @RaduBerinde

**Comment by RaduBerinde** [comment]
It doesn't seem related.

**Comment by RaduBerinde** [comment]
Ah. You can't in general  push down check constraints that could evaluate to NULL. That is because a null check constraint is considered to "pass" whereas a null filter is not. If the shard_id column was NOT NULL this would work.

**Comment by ajwerner** [comment]
Aha! Awesome. I'll report back to the user and I think we can close this issue.

**Comment by andy-kimball** [comment]
Theoretically, this check constraint will never evaluate to NULL, since user_id is NOT NULL. There is room to improve our NOT NULL inference logic.

**Comment by RaduBerinde** [comment]
Yeah, there are two things that are missing:
 - we need to know that `fnv32` never returns NULL for not-NULL input
 - the fact that the computed column formula is never NULL has to somehow "transfer" to marking the table column as not-null.
