### ISSUE TITLE
Categorize all validation errors in `sqlbase`

### ISSUE THREAD

**Issue by spaskob** [cockroachdb/cockroach#47430]
`structured.go` has a few validate functions that return uncategorized pg errors. i.e code `XXUUU`. We should categorize them with the appropriate pg error.

**Comment by ajwerner** [comment]
Today these unclassified errors are coming out of table validation in sqlbase/structured.go . We have this tendency to not check whether something makes sense up-front, try it, and then see if the outcome is invalid.

There are two approaches to fixing this. One is to return the appropriate errors during that validation (probably the easier approach). The other is to leave the unclassified errors in place but try to add higher level validation with the right code before constructing an invalid descriptor. That way we get some defence in depth with a signal when we do something wrong. Then we could make the system more loud when we hit a validation error.

I have a preference for the second approach. An example of the second approach is https://github.com/cockroachdb/cockroach/pull/47090

**Comment by spaskob** [comment]
I am going to start with this `DROP INDEX` error: `ERROR: index "primary" is in use as unique constraint (use CASCADE if you really want to drop it) (SQLSTATE XXUUU)`.

Here is a repro:
```
CREATE TABLE tbl (col1 int, col2 int);
ALTER TABLE tbl ADD CONSTRAINT col2_unq UNIQUE(col2);
DROP INDEX col2_unq;
ERROR: index "col2_unq" is in use as unique constraint (use CASCADE if you really want to drop it) (SQLSTATE XXUUU)
```

In contrast here is the error in postgres:
```
ERROR:  2BP01: cannot drop index col2_unq because constraint col2_unq on table tbl requires it
HINT:  You can drop constraint col2_unq on table tbl instead.
```
From `pkg/sql/pgwire/pgcode/codes.go` `DependentObjectsStillExist              = "2BP01"`

So the error code seems to fit this error well.

**Comment by spaskob** [comment]
A philosophical question: how much do we care about difference between our error messages and postgres' for the same sql statement?

**Comment by otan** [comment]
I think the wording should be the same or better, but error codes should almost always match.
in the case above, i think the separation of hint and error is better and we should do that instead so being more postgres-esque might be a good thing. but "the same or better" is subjective :)

**Comment by spaskob** [comment]
To add some more color, this is how you can actually drop this constraint:
```
spas=> ALTER TABLE tbl DROP CONSTRAINT col2_unq ;
ALTER TABLE
```

In cockroach this returns:
```
ALTER TABLE tbl DROP CONSTRAINT col2_unq ;
ERROR: unimplemented: cannot drop UNIQUE constraint "col2_unq" using ALTER TABLE DROP CONSTRAINT, use DROP INDEX CASCADE instead
SQLSTATE: 0A000
HINT: You have attempted to use a feature that is not yet implemented.
```
So I guess in this case the different error messages make sense.

**Comment by spaskob** [comment]
Thanks @otan 
To recap: the error codes should match.
Ideally our hints and error messages should be at least as useful as postgres.

**Comment by awoods187** [comment]
I'm really excited about this work.

**Comment by otan** [comment]
AFAICT, we can remove --tolerate-errors after https://github.com/cockroachdb/cockroach/pull/54228 merges.

**Comment by otan** [comment]
looks like

```
create table t (a int);
drop index t@c;
```

is uncategorised.

somehow only gets triggered on randomload. reproable on `bin/workload run schemachange --init --concurrency 5 --max-ops 10000 --verbose 2 --tolerate-errors=false`

not sure why this issue is assigned to me however.

**Comment by lucy-zhang** [comment]
We're close enough to this and have turned `--tolerate-errors` off in #55417 so I think we can close this.
