### ISSUE TITLE
*: remove 19.x cluster versions and version gates

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#47447]
[edit from @lucy-zhang] We're lagging behind on cleaning up cluster versions. We would like to have this test pass with only the last 2 major cluster versions permitted, as originally intended:

https://github.com/cockroachdb/cockroach/blob/7a330177a0625f956cdfff32a405640998e13649/pkg/clusterversion/keyed_versions.go#L79-L110

**Comment by lucy-zhang** [comment]
Here are all the versions we need to clean up in 21.1:

- [ ] introduced in 19.2: Version19_1
- [ ] introduced in 19.2: VersionStart19_2
- [ ] introduced in 19.2: VersionLearnerReplicas
- [ ] introduced in 19.2: VersionTopLevelForeignKeys
- [ ] introduced in 19.2: VersionAtomicChangeReplicasTrigger
- [ ] introduced in 19.2: VersionAtomicChangeReplicas
- [ ] introduced in 19.2: VersionTableDescModificationTimeFromMVCC
- [ ] introduced in 19.2: VersionPartitionedBackup
- [ ] introduced in 20.1: Version19_2
- [ ] introduced in 20.1: VersionStart20_1
- [ ] introduced in 20.1: VersionContainsEstimatesCounter
- [ ] introduced in 20.1: VersionChangeReplicasDemotion
- [ ] introduced in 20.1: VersionSecondaryIndexColumnFamilies
- [ ] introduced in 20.1: VersionNamespaceTableWithSchemas
- [ ] introduced in 20.1: VersionProtectedTimestamps
- [ ] introduced in 20.1: VersionPrimaryKeyChanges
- [ ] introduced in 20.1: VersionAuthLocalAndTrustRejectMethods
- [ ] introduced in 20.1: VersionPrimaryKeyColumnsOutOfFamilyZero
- [ ] introduced in 20.1: VersionRootPassword
- [ ] introduced in 20.1: VersionNoExplicitForeignKeyIndexIDs
- [ ] introduced in 20.1: VersionHashShardedIndexes
- [ ] introduced in 20.1: VersionCreateRolePrivilege
- [ ] introduced in 20.1: VersionStatementDiagnosticsSystemTables
- [ ] introduced in 20.1: VersionSchemaChangeJob
- [ ] introduced in 20.1: VersionSavepoints
- [ ] introduced in 20.1: VersionTimeTZType
- [ ] introduced in 20.1: VersionTimePrecision

**Comment by knz** [comment]
I'm ok doing those assigned to me but this would work somewhat better if my "package of work" was a separate issue
