### ISSUE TITLE
sql: Populate pg_cast table

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#47498]
See the documentation on this catalog table here: https://www.postgresql.org/docs/12/catalog-pg-cast.html

This is currently used by ActiveRecord, though we are exploring if there is a workaround.

ActiveRecord is running this query:

```
              SELECT exists(
                SELECT * FROM pg_proc
                WHERE proname = 'lower'
                  AND proargtypes = ARRAY[#{quote column.sql_type}::regtype]::oidvector
              ) OR exists(
                SELECT * FROM pg_proc
                INNER JOIN pg_cast
                  ON ARRAY[casttarget]::oidvector = proargtypes
                WHERE proname = 'lower'
                  AND castsource = #{quote column.sql_type}::regtype
              )
```

Jira issue: CRDB-4404

**Comment by awoods187** [comment]
@rafiss does AR expect this table to properly working like Postgres or could we implement it and keep it empty?

**Comment by rafiss** [comment]
The table already exists and is empty -- so yeah right now ActiveRecord is relying on the information in it to be correct. I'm trying to determine if a workaround is possible.

**Comment by vy-ton** [comment]
@rafiss Did we find a workaround for this?

**Comment by rafiss** [comment]
@vy-ton We did not. The impact on ActiveRecord is that right now the `case_sensitive=false` flag does not work when specifying a unique constraint. See: https://guides.rubyonrails.org/active_record_validations.html#uniqueness

**Comment by mgartner** [comment]
`pg_cast` has 6 columns: `oid`, `castsource`, `casttarget`, `castfun`, `castcontext`, and `castmethod`. We should be able to populate `castsource`, `casttarget`, and `castcontext` with the information in `pkg/sql/sem/tree/cast.go`. I think this would be sufficient to support this ActiveRecord query.
