### ISSUE TITLE
create/drop table (with/without foreign key) take too long

### ISSUE THREAD

**Issue by kocoten1992** [cockroachdb/cockroach#47512]
**Describe the problem**

I've open #46869, but doesn't have concrete example, allowed me to recreate this with clear example and close the old one.

**To Reproduce**

```
root@:5432/defaultdb> CREATE DATABASE test_database;
CREATE DATABASE

Time: 78.922975ms
```

```
USE test_database;
SET

Time: 1.104456ms
```

```
root@:5432/test_database> CREATE TABLE buyers (
    id UUID PRIMARY KEY
);
CREATE TABLE

Time: 33.952167ms
```

```
root@:5432/test_database> CREATE TABLE cars (
    id UUID PRIMARY KEY,
    preferred_buyer_id UUID,
    CONSTRAINT cars_preferred_buyer_id_fkey FOREIGN KEY (preferred_buyer_id) REFERENCES buyers (id)
);
CREATE TABLE

Time: 6.709753419s
```

```
root@:5432/test_database> DROP TABLE cars CASCADE;
DROP TABLE

Time: 7.105337403s
```

```
root@:5432/test_database> DROP TABLE buyers CASCADE;
DROP TABLE

Time: 6.990172606s
```

```
use defaultdb;
root@:5432/defaultdb> drop database test_database;
DROP DATABASE

Time: 6.794767354s
```

**Expected behavior**
Some operation take almost 7s to run, something is wrong with:
- create table with foreign key
- drop table
- drop database

There is no reason I'd need to wait 6s to create/drop (I'm using ```single-node-cluster```, but even for real cluster, 7s would be too slow)

**Environment:**
 - CockroachDB version: master
 - Server OS: [e.g. Linux/Distrib]
 - Client app `cockroach sql`

**Additional context**
What was the impact? Unable integrate testing application with database

**Comment by ajwerner** [comment]
What version are you using? I am not able to reproduce this locally.

**Comment by kocoten1992** [comment]
Hi @ajwerner , I'm also unable to reproduce this newly compiled cockroach.

But issue still exist on my jenkins, is there any flags/debug mode/documents to see what it been spending time ?

**Comment by ajwerner** [comment]
I continue to find this to be fast with a small number of rows. How much data is there?  Can I ask again which version?

**Comment by kocoten1992** [comment]
@ajwerner, sorry for misunderstanding, my version is:

```
Build Tag:    82294d1
Build Time:   2020/04/15 01:47:13
Distribution: CCL
Platform:     linux amd64 (x86_64-pc-linux-gnu)
Go Version:   go1.13.9
C Compiler:   4.2.1 Compatible Clang 3.8.0 (tags/RELEASE_380/final)
Build SHA-1:  82294d100ad1cb26b488f53e7241242d474d58d7
Build Type:   development
```

Number of rows isn't important, my workload is **constantly** keep dropping table and recreate them, at first it fast (postgres comparable), after a few circles it gotten worse and worse (100ms -> 3s -> ... -> 7s).

Let me first not wasting your time, I'm will wrote a script to reproduce it.

**Comment by kocoten1992** [comment]
possible related https://github.com/cockroachdb/cockroach/issues/38111

**Comment by kocoten1992** [comment]
Woa! I just build master and test again,

Before my whole migration database take well over a minute (sometimes 2)

Now it much better, it consistently take ~20s

(on fun side note, pg only take ~1s, but this is really good enough :100:)

**Comment by ajwerner** [comment]
Happy to hear it!

**Comment by kocoten1992** [comment]
It down to 6-7s with `CockroachDB CCL v20.2.0`, it going great, thank you very much!
