### ISSUE TITLE
Importing using IMPORT INTO broken when a columns is a reserved keyword 

### ISSUE THREAD

**Issue by onno-vos-dev** [cockroachdb/cockroach#47525]
**Describe the problem**

It is currently not possible to use `IMPORT INTO` for importing data into a table which uses a reserved keyword as a column name. [reserved keywords](https://github.com/AnanthaRajuCprojects/Reserved-Key-Words-list-of-various-programming-languages/blob/master/PostgreSQL%207.3.21%20Reserved%20Words.md)

**To Reproduce**
1. Set up CockroachDB node
2. Create a table with a reserved keyword
```sql
 create table test ("group" integer, "value" text);
```

3. Import the csv example from below using:
```sql
root@:26257/kred> IMPORT INTO test ("group", "value") CSV DATA ('nodelocal:///cockroach/csv/test.csv') WITH skip='1';
```

4. Observe the following error: `pq: verifying target columns: column "\"group\"" does not exist`

**test.csv:**
```csv
"group", "value"
1,"test"
2,"test"
3,"test"
```
**Expected behavior**

**Environment:**
 - CockroachDB version 19.2.0
 - Server OS: Linux (Ubuntu 18.04)
 - Client app: `cockroach sql` 

**Additional context**
What was the impact?
I'm trying to convert a non-SQL database into cockroach so the current database is not restricted by using sql reserved keywords, hence certain tables will end up containing reserved keywords. A possible migration of these values will be easier later than prior to importing due to the current database architecture.

**Comment by lucy-zhang** [comment]
I will let Bulk IO take this one.

**Comment by dt** [comment]
This is already fixed by #45944 for 20.1, though I guess maybe we should backport that to 19.2.x.

**Comment by onno-vos-dev** [comment]
@dt I'm happy to take a stab at it over the weekend but it'd be nice to have it backported for both myself and others that may not want to upgrade to a dev-version yet are still affected by this bug.

**Comment by dt** [comment]
I started it over on https://github.com/cockroachdb/cockroach/pull/47796 but haven't had a chance to dig into the CI flake there yet, but hope to do so tomorrow.

**Comment by dt** [comment]
#47796
