### ISSUE TITLE
sql: cannot perform ALTER TABLE t ALTER COLUMN TYPE in after CREATE TABLE t in the same txn

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#47537]
Currently, creating a table and altering the data type of that table in the same txn is unsupported.

Reason being is `runSchemaChangesInTxn` in sql/backfill.go doesn't support mutations that create other mutations. 

In the current implementation - ALTER COLUMN TYPE consists of 3 mutations, add column, swap columns and drop column. However `runSchemaChangesInTxn` will only call the backfill for the add column not knowing that a drop column is queued up afterwards (in the ComputedColumnSwap mutation). The backfiller is never run for the drop column since `columnBackfillInTxn` is called before drop column mutation is created. Moreover `columnBackfillInTxn` expects to backfill all mutation columns in one call and does not be expected to be called again for the mutation, this works when a mutation does not queue up new mutations but for the case of ALTER COLUMN TYPE, it does.

**Comment by RichardJCai** [comment]
#49351 is a broader issue that covers this

**Comment by MomoTHG** [comment]
SET enable_experimental_alter_column_type_general = true;

ALTER TABLE public."TABLENAME" ALTER COLUMN field TYPE VARCHAR(16) USING (field::VARCHAR(16));

SET enable_experimental_alter_column_type_general = false;
