### ISSUE TITLE
sql: add absolute value unary operator (@)

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#47543]
In PostgreSQL, @ is a unary operator that returns the absolute value of a number. For example:

```
jordan=# select @ -5.0;
 ?column?
----------
      5.0
(1 row)
```

CockroachDB is missing such a unary operator.

Jira issue: CRDB-4400

**Comment by naivcit** [comment]
Can I take this up too ?

**Comment by rohany** [comment]
@abhishek20123g was looking into this, and I think that it is going to be difficult to implement this. Because we support column references in expressions (e.g. "@1::INT"), this is going to be ambiguous with trying to parse `'@' expr` as a function call.
