### ISSUE TITLE
builtins: implement missing trig builtins

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#47545]
Postgres supports a few trig builtin variants that CockroachDB is missing: namely, the hyperbolic trig variants, as well as variants that act on degrees instead of radians.

See: https://www.postgresql.org/docs/12/functions-math.html

- [ ] sinh
- [ ] cosh
- [ ] tanh
- [ ] asinh
- [ ] acosh
- [ ] atanh
- [ ] sind
- [ ] cosd
- [ ] cotd
- [ ] tand
- [ ] acosd
- [ ] asind
- [ ] atand
- [ ] atan2d

**Comment by jordanlewis** [comment]
These should be added to `pkg/sql/sem/tree/builtins/builtins.go`, next to their friends. As a bonus, perhaps we should break them out into a new file, `math_builtins.go`, to cut down the size of `builtins.go` which has grown quite massive.

**Comment by lancerutkin** [comment]
I'm new here, but would like to take a crack at this. Looks like this may be a good issue to start on. Maybe first step just getting the functions implemented, then moving to breaking out into a new file?

**Comment by jordanlewis** [comment]
Hi @lancerutkin, that sounds like a great plan! Let me know if you need assistance.

Tests for your new builtins should go in a file `pkg/sql/sem/tree/testdata/eval/trig`. You can follow the pattern of other files in that same directory to figure out how the tests are written - it's a simple, text-based way of specifying inputs and outputs. I'm realizing we don't have tests for the other trig functions (yikes! I guess the thought was that we're just delegating to Go's well-tested trig library here, but not great) but you can at least start by adding tests for yours.

To run these files as a test, you can use the invocation:

```
make test PKG=./pkg/sql/sem/tree TESTS=TestEval
```
