### ISSUE TITLE
cli: Remove unnecessary command line flags

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#4754]
Let's remove command line flags which operators will not have any use for changing. Easier to add these later if they become necessary; harder to remove.

```
--memtable-budget
--metrics-frequency
--scan-interval
--scan-max-idle-time
--time-until-store-dead
```

**Comment by petermattis** [comment]
I think `--linearizable` and `--max-offset` fall into this category as well. Rather than remove this configuration completely, I think we should create a `system.settings` table and place it in the `SystemConfigSpan` so that it is gossiped to all nodes.

**Comment by jseldess** [comment]
I'll leave all of these, plus `linearizable` and `max-offset` out of the docs for now. Will update based on what happens with this ticket.

**Comment by spencerkimball** [comment]
The working suggestion here is to "hide" these flags as environment variables for beta.

**Comment by BramGruneir** [comment]
max-results, should this move to an env variable as well?

**Comment by bdarnell** [comment]
`--max-results` is fine to leave in, because it's only defined on `debug kv` subcommands so you won't see it unless you're looking at that section of the docs. The flags we want to get rid of are the ones that show up in the global flags or on major commands like `start`.

**Comment by jseldess** [comment]
Added `cache` to `cockroach start` docs. Left all others unmentioned for now. If we want to mention environment variables in the docs, please let me know.
