### ISSUE TITLE
roachprod: shorten the connection timeout for ssh connections to remote hosts

### ISSUE THREAD

**Issue by jlinder** [cockroachdb/cockroach#47567]
Sometimes the standard connection timeout length is to long and the calling program kills the roachprod process before it returns an error. Change roachprod so ssh connections time out after 5 or 10 seconds instead of the minute+ default timeout.

[Related thread](https://cockroachlabs.slack.com/archives/CJ0H8Q97C/p1585814965093900?thread_ts=1585751196.082500&cid=CJ0H8Q97C).

**Comment by alan-mas** [comment]
I am closing this issue as the the changes inside `session.go` that impact directly the ssh connection timeout are already merged (please refer to this [pull request](https://github.com/cockroachdb/cockroach/pull/63607) for more information).

Also, there is still more changes needed related to `cassandra.go` removing and `ssh.go` refactor, but those will be taking care in a separate issues.
