### ISSUE TITLE
Incorrect log size and "Raft log too large"

### ISSUE THREAD

**Issue by darinpp** [cockroachdb/cockroach#47569]
**Describe the problem**

When `LogSizeTrusted=false` the raft log size can't be trusted. We currently provide no indication that this is the case in the admin ui. We also don't ignore the log sizes when showing the problems for a range. So we show `Raft log too large` which is incorrect.

**Expected behavior**

We should gray out the actual raft log size when LogSizetrusted is false. And we should also not display `Raft log too large` in this case.

**Additional context**

This cases confusion when a customer looks at admin ui. It falsely shows as if there is a problem.

addresses https://github.com/cockroachlabs/support/issues/410

**Comment by andreimatei** [comment]
@tbg can you remind me what's the point where `LogSizetrusted` is reset?

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[5079](https://cockroachdb.zendesk.com/agent/tickets/5079) has been linked to this issue.
