### ISSUE TITLE
sqlmigrations: schema change job migration for table GC can't handle tables whose descriptors have already been deleted

### ISSUE THREAD

**Issue by lucy-zhang** [cockroachdb/cockroach#47576]
Start a 19.2 cluster and create a database with some tables, set one of the tables to have a very short `gc.ttlseconds`, and drop the database:
```
root@:26257/defaultdb> create database db; create table db.t1(); create table db.t2();
CREATE TABLE

Time: 9.418ms

root@:26257/defaultdb> alter table db.t1 configure zone using gc.ttlseconds=1;
CONFIGURE ZONE 1

Time: 4.653ms

root@:26257/defaultdb> drop database db cascade;
DROP DATABASE

Time: 89.865ms

```
Wait for the async schema changer to GC table `t1` (the final step of which is deleting the table descriptor), then shut down the cluster and upgrade to 20.1. The migration for the `DROP DATABASE` job will fail because it can't find the table descriptor for `t1`. This shows up in the logs:
```
error attempting running schema change job migration, will retry: descriptor not found
```
To fix this, we can just have the migration exclude tables which are in the list of tables to GC but for which the descriptor no longer exists.

**Comment by ajwerner** [comment]
Closed by #51176.
