### ISSUE TITLE
Feature: FOR UPDATE

### ISSUE THREAD

**Issue by hazcod** [cockroachdb/cockroach#47599]
**Is your feature request related to a problem? Please describe.**
I am trying to setup Uber's Cadence project with cockroachdb, since it offers PostgreSQL.

**Describe the solution you'd like**
Being able to swap postgresql with cockroachdb.

**Additional context**
```sql
SELECT notification_version FROM domain_metadata FOR UPDATE
```

**Comment by knz** [comment]
it's already there in 20.1

**Comment by hazcod** [comment]
@knz ah apologies, that's not on docker hub yet: https://hub.docker.com/r/cockroachdb/cockroach/tags

**Comment by knz** [comment]
20.1 will be released later this month or early in May

**Comment by knz** [comment]
you can download a beta / rc from the doc web site though

**Comment by hazcod** [comment]
Hmm, I need it in a docker setup, so I will have to wait I suppose.

**Comment by awoods187** [comment]
cockroachdb/cockroach-unstable:v20.1.0-rc.2 from https://www.cockroachlabs.com/docs/releases/#docker

As @knz mentioned our official 20.1 release is coming soon but we expect this release candidate to be very similar to it.
