### ISSUE TITLE
Cannot connect to `cockroachdb-public.<namespace>` with TLS

### ISSUE THREAD

**Issue by pjediny** [cockroachdb/cockroach#47613]
**Describe the problem**

Default k8s manifests don't generate node certs with `cockroachdb-public.<namespace>` address

**To Reproduce**

1. Set up CockroachDB secure cluster with k8s manifests
2. Try to connect to `cockroachdb-public.<namespace>` address with TLS enabled
3. See error, certs don't have the `cockroachdb-public.<namespace>` address included

**Expected behavior**
Node certs should have the `cockroachdb-public.<namespace>` address included

**Environment:**
 - CockroachDB version `v19.2.6`
 - Server OS: `GKE`

**Comment by knz** [comment]
This may be a use case for the new feature `--cert-principal-map` in v20.1.

**Comment by knz** [comment]
@pjediny could you check out the change in #48591 and see if that fixes your problem? Thanks

**Comment by knz** [comment]
nvm I saw you already have a PR out, which I'll gladly accept.

I have a remaining question though: what is your process to fetch the k8s configs from CockroachDB? do you always check out the `master` branch from this repository, or do you expect the yaml files to be updated inside our release archives? 

(I need to know this to determine whether to backport your fix to a release branch)

Thanks in advance

**Comment by knz** [comment]
@pjediny I would be interested in your answer to the question above even though the issue is now closed. Thanks

**Comment by pjediny** [comment]
I'm not sure if this answers you question, but I usually do an equivalent of `git checkout tag` on your repository and compare/back-port the changes to the manifests we maintain internally. We don't use `helm`. I know that your documentation is using `curl` to `master` branch, but we just want to be extra sure, that we will not break the deployments accidentally. We had a small initial confusion caused by the deployment manifests in your documentation not being versioned.

So I would prefer the changes to be back-ported to the older releases, but in this case it is not critical, as this change would need the manual intervention to regenerate node certs anyway and would impact new installation only.

**Comment by pjediny** [comment]
Well, thinking about it, there could be a small confusion when using the new manifest on existing deployment and scaling up the replica count, the new nodes would have the new SANs in the certs and old ones only the old SANs. This is a problem for operation team to solve, but the regenerating node certs with k8s ca is currently not very well documented.
