### ISSUE TITLE
concurrent update and read blocked when run on different gateways

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#47622]
**Describe the problem**

when upsert and select on a same row at the same time are run
- from the same gateway, the read is not blocked.  
- from two different gateways, the read is blocked

Is this expected?

**To Reproduce**

run 3 node local cockroach

- terminal 2 *WILL* block until terminal 1 commits

terminal 1
```
cockroach sql --insecure
create table fact (key int primary key, value float);
upsert into fact values (1,1.0);
begin; 
upsert into fact values (1,2.0);
-- start terminal2
```

terminal 2
```
cockroach sql --insecure --port 26259
select * from fact where key=1; 
-- this will block until terminal 1 finishes
```

- terminal 2 will *NOT* block 
  
terminal 1
```
cockroach sql --insecure
create table fact (key int primary key, value float);
upsert into fact values (1,1.0);
begin; 
upsert into fact values (1,2.0);
-- start terminal2
```

terminal 2
```
cockroach sql --insecure 
select * from fact where key=1; 
-- completes
```

**Expected behavior**

the read should not be blocked in both cases

**Additional data / screenshots**

**Environment:**
 - CockroachDB version 20.1 beta 4, 19.2.4
 - Server OS: [osx and linux]
 - Client app [`cockroach sql`]

**Additional context**

**Comment by nvanbenschoten** [comment]
@robert-s-lee have you ever seen the read block in the two gateway case? You say that the expected behavior is that "the read should not be blocked in both cases", but this is not correct. If the read transaction is assigned a higher timestamp than the write transaction then we do expect it to block. So I'm wondering whether the two gateways have divergent clocks that could lead to the read being given a lower timestamp than the write in the second case.

**Comment by nvanbenschoten** [comment]
Actually, it's the multi-gateway case that you're seeing block. That's more surprising to me.

**Comment by nvanbenschoten** [comment]
@robert-s-lee I am not able to reproduce this when running with a local cluster. In both cases, I'm seeing the scan block, which is expected given our current transaction model.

**Comment by robert-s-lee** [comment]
user error and did not press enter.   both cases are consistent.
