### ISSUE TITLE
opt: add rule to convert a count to a count_rows if input column is not-null

### ISSUE THREAD

**Issue by DrewKimball** [cockroachdb/cockroach#47637]
@RaduBerinde suggested that we add a rule to the optimizer that rewrites queries like this:
```
CREATE TABLE t (x INT PRIMARY KEY);
INSERT INTO t SELECT x FROM generate_series(1,100000) t(x);
SELECT count(x) FROM t;
```
to this:
```
SELECT count(*) FROM t
```
The first runs in ~55ms on my laptop. The second runs in ~40ms.

**Comment by andy-kimball** [comment]
I'm curious as to why `count(*)` runs so much faster than `count(col)`. I expected some speed-up, but 20%+ is pretty dramatic. @yuzefovich, any ideas why? No need to spend time investigating, I'm just curious if you happen to have a theory.

**Comment by RaduBerinde** [comment]
Most likely it's the decoding of the value and storing it in memory. There are also some specialized fastpaths for `COUNT(*)` (at least in the non-vectorized execution).

**Comment by yuzefovich** [comment]
Yes, we have an optimized row-by-row processor as well as vectorized operator for `count(*)` whereas `count(col)` will be performing aggregation.

This can be easily seen in `EXPLAIN (vec)`:
```
root@127.0.0.1:56238/movr> explain (vec) SELECT count(x) FROM t;
                text
-------------------------------------
  │
  └ Node 1
    └ *colexec.orderedAggregator
      └ *colexec.oneShotOp
        └ *colexec.distinctChainOps
          └ *colexec.colBatchScan
(6 rows)

Time: 2.696ms

root@127.0.0.1:56238/movr> explain (vec) SELECT count(*) FROM t;
             text
-------------------------------
  │
  └ Node 1
    └ *colexec.countOp
      └ *colexec.colBatchScan
(4 rows)

Time: 4.317ms
```
