### ISSUE TITLE
replication dashboard: some information tooltips more useful than others

### ISSUE THREAD

**Issue by ghost** [cockroachdb/cockroach#47645]
**Is your feature request related to a problem? Please describe.**

Some of the information boxes ((i) icons) are helpful. others are simply repeats of the title text to the left of them.

While there are regions without "i" icons (quiescence is a good example, how do I interpret that graph?), some regions have an "i" icon that just repeats what's already been said.

similar to how in #17670 where the problem was that some pieces /don't/ have tooltips.
**Describe the solution you'd like**
**Describe alternatives you've considered**
**Additional context**
## examples

"Replicas per Store": "the number of replicas on each store"

"Logical Bytes per Store": "the number of logical bytes per store"

vs:

"Leaseholders per store": "the number of leaseholder replicas per store. a leaseholder replica is one that coordinates all reads and write requests for the range"

"Average Queries per Store": "exponentially weighted moving average of the number of KV batch requests processed by leaseholder replicas on each store per second. Tracks roughly the last 30 minutes of requests. Used for load-based rebalancing decisions."

**Comment by cwhitingwy** [comment]
well then... blathers is rather dumb... can we swap templates to use "# titles" (that don't need to be changed) so that users don't unintentionally remove things blathers is expecting?

e.g.:
```
# section title
<!-- your description of the problem -->
```
