### ISSUE TITLE
Incorrect row mentioned in UNIQUE constraint violation message

### ISSUE THREAD

**Issue by andymans** [cockroachdb/cockroach#47661]
Occurs on - cockroach-v19.2.6.darwin-10.9-amd64

When executing multiple inserts using the form:

INSERT INTO MY_TABLE VALUES
(id, name),
(id, name),
(id, name)
etc.,

When the 'name' column is UNIQUE and a duplicate value for the 'name' column exists at e.g. item 50 in the set of values to insert, an error is thrown that references the incorrect item e.g. item 20 in the set of values to insert (where item 20 is NOT a duplicate and does not violate the unique key).

Steps to reproduce:

1. Create a table with a PK col and a 'name' col, specifying that the 'name' col shd be UNIQUE
2. Generate an insert statement to insert say 200 rows using the bulk insert syntax.
3. Ensure that a few of the rows at say, index 160, will break the unique constraint.
4. Verify that the row mentioned in the constraint violation error is not the row(s) that actually violate the constraint.

**Comment by jordanlewis** [comment]
Can't repro, so closing this. @andymans if you do experience this again, please provide concrete repro steps and we'll take a look.
