### ISSUE TITLE
opt: decorrelate Max1Row operator using DistinctOn with ErrorOnDup=true

### ISSUE THREAD

**Issue by andy-kimball** [cockroachdb/cockroach#47667]
Currently we are not able to decorrelate joins that have a `Max1Row` as their right input, as in this case:
```
root@:26257/defaultdb> CREATE TABLE ab (a INT PRIMARY KEY, b INT);
CREATE TABLE

root@:26257/defaultdb> CREATE TABLE xy (x INT PRIMARY KEY, y INT);
CREATE TABLE

root@:26257/defaultdb> EXPLAIN (OPT) SELECT (SELECT b FROM ab WHERE b=x) FROM xy;
                text
-------------------------------------
  project
   ├── left-join-apply
   │    ├── scan xy
   │    ├── max1-row
   │    │    └── select
   │    │         ├── scan ab
   │    │         └── filters
   │    │              └── ab.b = x
   │    └── filters (true)
   └── projections
        └── ab.b
```
We should add a `TryDecorrelateMax1Row` rule that pulls the `Max1Row` operator above the `LeftJoinApply` operator as a `DistinctOn` with `ErrorOnDup=true`:
```
(DistinctOn
  (LeftJoinApply (Values ...) (Select ...) (True))
  [GroupingCols=(x), ErrorOnDup=true]
)
```
The `ErrorOnDup=true` option will cause `DistinctOn` to raise an error if it detects duplicates in the `x` column. Since `x` was a key in the join's left input, a duplicate value in that column indicates more than one row from the right input matched that value. That's equivalent to the semantics of `Max1Row`.

**Comment by andy-kimball** [comment]
Note that fixing this could result in dramatic speedups for "virtual table" queries like this one used by `pgadmin`:
```
SELECT
    pid AS "PID",
    username AS "User",
    datname AS "Database",
    backend_start AS "Backend start",
    CASE
    WHEN client_hostname IS NOT NULL
    AND client_hostname != ''
    THEN client_hostname::STRING
    || ':'
    || client_port::STRING
    WHEN client_addr IS NOT NULL
    AND client_addr::STRING != ''
    THEN client_addr::STRING || ':' || client_port::STRING
    WHEN client_port = -1 THEN 'local pipe'
    ELSE 'localhost:' || client_port::STRING
    END
        AS "Client",
    application_name AS "Application",
    query AS "Query",
    query_start AS "Query start",
    xact_start AS "Xact start"
FROM
    pg_stat_activity AS sa
WHERE
    (
        SELECT
            r.rolsuper OR r.oid = sa.usesysid
        FROM
            pg_roles AS r
        WHERE
            r.rolname = current_user()
    )
```
This query cannot currently be decorrelated because of the `pg_roles` subquery that requires a `max1-row` check. This in turn means that we fall back on `ApplyJoin` execution, and re-run the subquery for every row in `pg_stat_activity`.

It's true that `pg_stat_activity` probably returns 0 rows in CRDB, and so this query would still appear "fast", but this is just an example. Some virtual tables return hundreds of rows, and a query like this will cause an N**2 blowup, with the "inner" virtual table being recalculated once for each outer row.

CC @jordanlewis

**Comment by andy-kimball** [comment]
CC @DrewKimball

**Comment by andy-kimball** [comment]
Discussion item: if we allow decorrelation in this case, other rules can then "push down" filters into the subquery. That in turn can cause the error not to be raised, since the extra rows that would have triggered the error were removed by the filter. As an example:
```
CREATE TABLE xy (x INT PRIMARY KEY, y INT, INDEX (y));
INSERT INTO xy VALUES (1, 2), (2, 2), (3, 3);
SELECT a FROM (VALUES (0), (0)) v(a) WHERE (SELECT y FROM xy WHERE x<>a)=3;
```
Without the decorrelation rule, the query plan would be:
```
root@:26257/defaultdb> EXPLAIN (opt) SELECT a FROM (VALUES (0), (0)) v(a) WHERE (SELECT y FROM xy WHERE x<>a)=3;
                     text
----------------------------------------------
  project
   └── inner-join-apply
        ├── values
        │    ├── (0,)
        │    └── (0,)
        ├── max1-row
        │    └── project
        │         └── select
        │              ├── scan xy
        │              └── filters
        │                   └── x != column1
        └── filters
             └── y = 3
```
However, once the `max-1-row` is decorrelated, the equality condition is pushed down, allowing the `xy@secondary` index to be used. There is no reason to even read `y=2` rows in that case, and so no duplicates are detected, and no error is raised. Here is the plan:
```
root@:26257/defaultdb> EXPLAIN (opt) SELECT a FROM (VALUES (0), (0)) v(a) WHERE (SELECT y FROM xy WHERE x<>a)=3;
                       text
---------------------------------------------------
  project
   └── distinct-on
        ├── inner-join (cross)
        │    ├── scan xy@xy_y_idx
        │    │    └── constraint: /3/2: [/3 - /3]
        │    ├── ordinality
        │    │    └── values
        │    │         ├── (0,)
        │    │         └── (0,)
        │    └── filters
        │         └── x > column1
        └── aggregations
             └── const-agg
                  └── column1
```
The question is, can we do this? There are **big** performance wins to having this rule, and it would fire in some common and very useful cases. But on the other hand, it would violate intuition that an error should be raised in a case like this, and also might be considered a violation of the SQL spec (I'm still trying to find language in the SQL spec that would allow or disallow this kind of transformation).

CC @RaduBerinde for you opinion.

**Comment by andy-kimball** [comment]
+@knz and @jordanlewis in case you want to weigh in.

**Comment by RaduBerinde** [comment]
I would guess it's not ok. I could see wanting the the subquery to fail as a "fail-safe".

I think we should not allow pushing filters through `DistinctOn` when `ErrorOnDup=true` (which seems incorrect). Or maybe push only filters that use just the grouping columns? (strictly speaking that's not semantically equivalent but perhaps we don't care about duplicates for groups which we don't care about?)

For this rule, even if the apply-join has an on condition, we would pull it up as a `Select` on top of `DistinctOn`. Of course, with these tweaks we probably won't get as much of a benefit in many cases.

**Comment by RaduBerinde** [comment]
> Or maybe push only filters that use just the grouping columns?

Ah, that's what we do currently.

**Comment by jordanlewis** [comment]
I think the spec bans it. It's interesting, this was my first time really "spec-diving" - the spec is structured as grammar rules, and doesn't seem like it lets expressions reference their context.

 "Scalar subqueries" must return an error if they have more than 1 result, and I could trace my way up from scalar subquery to "value expression". I couldn't directly show that "value expressions" are usable in comparison operators. But I think it's pretty clear that the spec doesn't really like it...

![image](https://user-images.githubusercontent.com/43821/79816724-e07b7b80-8351-11ea-9823-0481eb6f6256.png)

![image](https://user-images.githubusercontent.com/43821/79817438-824f9800-8353-11ea-95b9-f9ef19104d02.png)

**Comment by knz** [comment]
No comment from me other than what Jordan already wrote.
