### ISSUE TITLE
sql: missing telemetry for types 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#47682]
I'm exploring the telemetry data types added in https://github.com/cockroachdb/cockroach/issues/45215 which include a backport to 19.2 in February, but I only see data from January (from before this fix). 

Is there a bug in our data collection?

**Comment by otan** [comment]
i don't have perms to see looker, but they appear in tests so my guess is pipeline related because "January" seems weird and there should be some versions out there populating this. Do they not appear under `sql.schema.new_column_type.%`, where % is a wildcard?

**Comment by awoods187** [comment]
oh i was looking at `sql.schema.create.column_type` I thought `sql.schema.new_column_type.%` was about changing a column type
