### ISSUE TITLE
memory leak 

### ISSUE THREAD

**Issue by yangxuanjia** [cockroachdb/cockroach#47686]
**Describe the problem**
set max_range_bytes=512M
set min_range_bytes=128M
memory leak seems happened. often happen oom.

**To Reproduce**
set max_range_bytes=512M
set min_range_bytes=128M
write 1T data per node.
about 23k ranges per node.
total 16G memory per node.

/cockroach/cockroach --advertise-host=11.34.67.77 --store=path=/export/node,attrs=SAS,rocksdb=write_buffer_size=134217728;compression_per_level=kNoCompression:kNoCompression:kSnappyCompression:kSnappyCompression:kSnappyCompression:kSnappyCompression:kSnappyCompression;max_background_flushes=3;max_background_compactions=6 --http-addr 0.0.0.0:80 --locality country=zh,region=zh,datacenter=ht,rack=14-403-C-10,node=11.3.99.72 start --logtostderr --insecure --cache=25% --max-sql-memory=25% --join=cdb.cdb-mysql-kwtest15.svc.htdb.n.jd.local:26257

 **Expected behavior**
memory use normal.

**Additional data / screenshots**
looks cgo use too much memory.
 
![Screenshot from 2020-04-20 11-43-54](https://user-images.githubusercontent.com/2627712/79713493-81d9e180-8300-11ea-8243-75f8dd263a27.png)
![Screenshot from 2020-04-20 11-44-10](https://user-images.githubusercontent.com/2627712/79713494-83a3a500-8300-11ea-8f3c-49507e5175f4.png)

**Environment:**
 - CockroachDB version [19.1]
 - Server OS: [Centos7.2]
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
instability

**Comment by yangxuanjia** [comment]
#46660

**Comment by dcadevil** [comment]
![image](https://user-images.githubusercontent.com/14159754/79735871-8b2c7380-832b-11ea-96e6-c8ade3b48991.png)

**Comment by dcadevil** [comment]
![image](https://user-images.githubusercontent.com/14159754/79735966-adbe8c80-832b-11ea-989d-80013653e89d.png)

**Comment by petermattis** [comment]
It is possible that the automatic memory detection has fouled up, and `--cache=25%` is setting a much larger cache size than expected. When Cockroach starts up, it outputs a line containing `cache size             x GiB` to the log. Can you share what that line says? If the cache size is much larger than expected, you can specify an absolute value using something like `--cache=8GiB` rather than relying on the automatic memory detection.

CRDB's configuration of RocksDB pins index and filter blocks in the cache. This shows up in the `rocksdb.table-readers-mem-estimate` which you can graph from the "Advanced Debug" page using a custom chart. What does that metric show? If it shows the majority of the memory usage, then we can disable the pinning of index and filter blocks in the cache by specifying `-store="path=<cockroach-data>,rocksdb=block_based_table_factory={cache_index_and_filter_blocks=true}"` (replace `<cockroach-data>` with your store directory. This will have a modest impact on performance, but that is usually preferable to running out of memory.

**Comment by yangxuanjia** [comment]
I200422 16:52:36.846698 1 server/config.go:386  system total memory: 15 GiB
I200422 16:52:36.846747 1 server/config.go:388  server configuration:
max offset             500000000
cache size             3.7 GiB
SQL memory pool size   3.7 GiB
scan interval          10m0s
scan min idle time     10ms
scan max idle time     1s
event log enabled      true

**Comment by yangxuanjia** [comment]
![Screenshot from 2020-04-23 10-37-12](https://user-images.githubusercontent.com/2627712/80052990-7da30380-854e-11ea-9fb4-cce50605ff99.png)
![Screenshot from 2020-04-23 10-37-20](https://user-images.githubusercontent.com/2627712/80052994-7ed43080-854e-11ea-8bb0-2489a0d48273.png)
![Screenshot from 2020-04-23 10-37-30](https://user-images.githubusercontent.com/2627712/80052997-7f6cc700-854e-11ea-965b-c77e366bfd14.png)
![Screenshot from 2020-04-23 10-37-40](https://user-images.githubusercontent.com/2627712/80053001-80055d80-854e-11ea-8211-23639716cc8d.png)

**Comment by yangxuanjia** [comment]
this is kwtest16 cluster: it looks weird, node1, node3, node5 use 600K memory,  but node2 and node4 use 10G memory. 
![Screenshot from 2020-04-23 10-45-13](https://user-images.githubusercontent.com/2627712/80053496-ad9ed680-854f-11ea-92f5-4827d6fcb9d8.png)
![Screenshot from 2020-04-23 10-45-25](https://user-images.githubusercontent.com/2627712/80053499-aed00380-854f-11ea-909f-efc6c2f44feb.png)
![Screenshot from 2020-04-23 10-45-34](https://user-images.githubusercontent.com/2627712/80053502-af689a00-854f-11ea-8c6e-4b123d37cec9.png)
![Screenshot from 2020-04-23 10-45-44](https://user-images.githubusercontent.com/2627712/80053503-b0013080-854f-11ea-8878-b3cf99c0a767.png)
![Screenshot from 2020-04-23 10-45-52](https://user-images.githubusercontent.com/2627712/80053507-b099c700-854f-11ea-9e7c-1aea8d959999.png)
![Screenshot from 2020-04-23 10-46-00](https://user-images.githubusercontent.com/2627712/80053508-b1325d80-854f-11ea-95bf-aeb239da9beb.png)

**Comment by yangxuanjia** [comment]
@petermattis  @ajwerner 
we set -store="path=<cockroach-data>,rocksdb=block_based_table_factory={cache_index_and_filter_blocks=true}", it looks useful, memory can limit by this paramter.
cgo allocated can hold always 3.8G, cgo total can hold nearly 4.9G.
This very excellent for us. We can do further test for big range.
![Screenshot from 2020-04-23 16-14-05](https://user-images.githubusercontent.com/2627712/80075858-e655a480-857d-11ea-9434-1ac930b50980.png)
