### ISSUE TITLE
sql: add telemetry for explain analyze (debug)

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#47683]
We have explain telemetry:
```SQL

sql.plan.explain
--
11 | sql.plan.explain-analyze
12 | sql.plan.explain-distsql
13 | sql.plan.explain-opt
14 | sql.plan.explain-opt-verbose
15 | sql.plan.explain-vec
```
But we dont yet have anything for explain analyze (debug). We should also be able to track both WebUI and SQL shell use separately.

**Comment by RaduBerinde** [comment]
We already have this (see #47053).
