### ISSUE TITLE
ui: cypress dependency should be optional to prevent build breaks on unsupported platforms

### ISSUE THREAD

**Issue by dhartunian** [cockroachdb/cockroach#47694]
As mentioned in #47666, the cypress dependency blocked the build from continuing on FreeBSD and was also downloading a dependency at build time.

Neither of these things should happen.

This revert was necessary to fix the issue: #47688.

**Comment by knz** [comment]
@dhartunian I can hold off merging #47688 if there's a strategy to fix #47666 - I am ok holding the revert in my working directory.

**Comment by dhartunian** [comment]
@koorosh can you take a look at this when you're back tomorrow? I'd like to either make the download of cypress optional if we can easily configure that or put it into its own directory (`pkg/ui/cypress` or `pkg/ui/e2e`) with its own `package.json`. Then whoever wants to run it can take the step of downloading the dependency but it won't interfere with the usual `yarn` commands on the `pkg/ui` directory.
