### ISSUE TITLE
Multiple primary keys for table "databasechangelog" are not allowed

### ISSUE THREAD

**Issue by toddrosner** [cockroachdb/cockroach#47699]
We're currently using CockroachDB Core v19.2.5.

We have a migration tool that uses Liquibase for migrations. The tool connects to the database and dumps a SQL file, which then updates the database on a subsequent run.

During the database update, the databasechangelog, and databasechangeloglock tables are created, but then the following error happens:

`ERROR: multiple primary keys for table "databasechangelog" are not allowed`

The error takes place at the following SQL statement from the migrations file:

`ALTER TABLE "public".notary_request_log ADD CONSTRAINT request_log_pkey PRIMARY KEY (id);`

I see that CockroachDB is **not** mentioned as a supported database here https://www.liquibase.org/databases.html, but that there should be a work around for some limitations including primary keys. I've tried the base creation SQL, but still got the same error with the Liquibase migration tool.

I do also see other mentions in Github issues about the current standing of Liquibase and CockroachDB...but they are somewhat dated. So what should we expect when using Liquibase with CockroachDB 19.2.5...should this work properly out of the box? Are there special ways to get Liquibase and CockroachDB to work? Or should this not reliably work at all at this time?

**Comment by jordanlewis** [comment]
Hi Todd, in CockroachDB 19.2, changing the primary key of a table was not possible. This error is a symptom of that issue.

Primary key change will be possible in our upcoming 20.1 release, which will be available very soon. You can try out the 20.1 RC here: https://www.cockroachlabs.com/docs/dev/install-cockroachdb-linux.html

**Comment by jordanlewis** [comment]
I'll close this issue for now as we expect its resolution in 20.1, but we'll be monitoring it - if you still have a problem, feel free to re-open. Thanks!
