### ISSUE TITLE
sql: ALTER COLUMN TYPE USING EXPRESSION not supported

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#47706]
Currently, doing an ALTER TABLE ... ALTER COLUMN ... [SET] TYPE USING <EXPR>  is not supported.

To support this - need to disable writes into the new column while the old column still exists and is a computed column of the new one.

This stems from the problem of having two possible TableDescriptor versions once the column with the new type is swapped with the column of the old type - we need to ensure the old column is also written to in case a read happens from the old TableDescriptor. If an expression was used to generate the new column, we cannot invert the expression to use as a computed expression for the old column. Thus we have have to disable writes until the old column is dropped.

**Comment by jordanlewis** [comment]
What does this do? You should add some details, and label the issue according to convention as well.
