### ISSUE TITLE
opt: add normalization rule to simplify x=x

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#47717]
Consider the following:
```
root@127.0.0.1:65336/movr> create table t(x int primary key);
CREATE TABLE

Time: 3.294ms

root@127.0.0.1:65336/movr> explain (opt) select * from t where x=x;
       text
-------------------
  select
   ├── scan t
   └── filters
        └── x = x
(4 rows)
```

Since `x` is never NULL, we should be able to replace the filter `x=x` with true. We should also be able to create similar rules to convert `x <= x` to true and `x < x` to false, etc.

**Comment by RaduBerinde** [comment]
In general I think we should convert a `x=x` filter with `x IS NOT NULL` (and other rules can remove that if the column is not nullable)

**Comment by mjibson** [comment]
```
> SELECT
	i,
	i = i AS eq,
	i IS NOT NULL AS isnotnull,
	i IS NOT NULL OR NULL AS notoris
FROM
	(VALUES (1), (NULL)) AS t (i);

   i   |  eq  | isnotnull | notoris
-------+------+-----------+----------
     1 | true |   true    |  true
  NULL | NULL |   false   |  NULL

```

This suggests that `x=x` can't be converted either to `true` or `IS NOT NULL`, but `IS NOT NULL OR NULL` appears to work?

**Comment by RaduBerinde** [comment]
Inside a "top level" filer (`memo.FiltersExpr`), `NULL` and `false` are the same. This rule could "match" on `Filters`
