### ISSUE TITLE
sql: concurrent schema changes appear to deadlock

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#47725]
The RSG tests have been [failing](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RandomSyntaxTests/1884694?mode=branches) with statement timeouts, which happen when a statement doesn't finish executing in a while **and** doesn't respond to the network being disconnected and the associated context cancellation.

In that linked log, the timedout statement was:

```
ALTER TABLE ident.ident ALTER EXTRACT_DURATION DROP NOT NULL
```

With notes that the following were also executing at the same time (since it runs things in parallel):

```
ALTER TABLE ident.ident ADD COLUMN IF NOT EXISTS OPTION CHAR VARYING ( 1 ) [ ];
ALTER TABLE ident.ident ADD IF NOT EXISTS ident DECIMAL ARRAY;
ALTER TABLE ident.ident ALTER COLUMN ident SET NOT NULL;
ALTER TABLE ident.ident ALTER EXTRACT_DURATION DROP NOT NULL;
ALTER TABLE ident.ident DROP COLUMN POLYGON RESTRICT;
ALTER TABLE ident.ident DROP COLUMN REAL;
ALTER TABLE ident.ident DROP IF EXISTS ABORT;
```

**Comment by lucy-zhang** [comment]
I took a cursory look at the goroutine dump. It looks like there are no stack traces from the schema change job, only from the retry loop inside `Registry.Run()` which is called from the `connExecutor` post-transaction to wait for the schema change job to finish, e.g.,
```
goroutine 7930816 [select]:
github.com/cockroachdb/cockroach/pkg/util/retry.(*Retry).Next(0xc002e7d228, 0xc000000003)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/retry/retry.go:116 +0x185
github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).Run(0xc0025faf70, 0x4ba0f00, 0xc003cc5440, 0x4be3960, 0xc0084fb7a0, 0xc00d6eec58, 0x1, 0x1, 0x7259220, 0x3df4300)
        /go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:310 +0x4c2
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).txnStateTransitionsApplyWrapper(0xc002ddd000, 0x4b1c180, 0x7259220, 0x3df4300, 0xc00368f770, 0x14a22d887340, 0xc008af5c80, 0xdf8, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2155 +0xa49
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc002ddd000, 0x4ba0f00, 0xc00bf01280, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1497 +0x952
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc002ddd000, 0x4ba0f00, 0xc003cc5440, 0xc00e01ec40, 0x5400, 0x15000, 0xc00e01ecd8, 0xc006954450, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1297 +0x1f2
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc001b62100, 0x4ba0f00, 0xc003cc5440, 0xc002ddd000, 0x5400, 0x15000, 0xc00e01ecd8, 0xc006954450, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:476 +0x104
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc00a1e7e4d, 0xc00c3f06a0, 0x4ba0f00, 0xc003cc5440, 0xc006954450, 0xc001b62100, 0xc008af5600, 0x4bc4e80, 0xc0008d0e40, 0xc0079bf1a0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:594 +0x2e8
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:526 +0x17e
```
I wonder if we're somehow not handling context cancellation correctly.

**Comment by jordanlewis** [comment]
@spaskob, would you be able to take a look at this?

**Comment by spaskob** [comment]
@ajwerner do you think your deadlock fix for `workload/schemachange` applies here?

**Comment by spaskob** [comment]
@mjibson have these tests being failing recently for the same reason?

**Comment by mjibson** [comment]
I'm not able to say yes or no because those tests are failing for new other reasons. Ping me in a few days and I'll check again.

**Comment by spaskob** [comment]
Hey Matt, pining you here. I strongly suspect that there may be a deadlock bug in pgx conn-pool.go that is causing this.

**Comment by ajwerner** [comment]
@spaskob Do you have any other data about the deadlock? Are there stack traces that demonstrate what's going on?

**Comment by mjibson** [comment]
The RSG tests use lib/pq, not pgx. The problem above has been happening for years in RSG tests, and only with schema changes.

**Comment by spaskob** [comment]
@mjibson have you observed this problem in recent runs?

**Comment by ajwerner** [comment]
I'm closing this as unactionable.
