### ISSUE TITLE
node kill + restart blocks query execution

### ISSUE THREAD

**Issue by heidawei** [cockroachdb/cockroach#47743]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:
A cluster of 16 nodes（64 cores CPU， 200GB RAM， 3.8TB STAT disk）, kill a node, and add a new node. At this time, it is found that some queries are blocked. This query is a get operation, not an scan operation.

**To Reproduce**
kill a node, and add a new node to the cluster.

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
2. Send SQL ... / CLI command ...
3. Look at UI / log file / client app ...

**Expected behavior**

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version [ V19.2.4]
 - Server OS: [Centos7.2]
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
What was the impact?

**Comment by heidawei** [comment]
At the same time, the UI is partially unavailable, and some runtime and other monitoring indicators cannot be viewed。
![image](https://user-images.githubusercontent.com/11207613/79842097-fab56800-83ea-11ea-97a8-e1afa7d39ea7.png)

**Comment by knz** [comment]
Hi @heidawei 
Sorry for the late answer.

There is not enough information here to help you.

- it is not clear what you mean with "kill a node"
- you need to specify how long the issue is lasting - does the cluster eventually recover?
- what do the log files indicate?
- we'll want to look at the output of `cockroach debug zip`.

**Comment by heidawei** [comment]
@knz
This issue is related to another [issue 48085](https://github.com/cockroachdb/cockroach/issues/48085) I submitted. Because the disk IO is full, it cannot respond to external requests.

**Comment by mwang1026** [comment]
Close due to inactivity. Feel free to open if you see it again / have new evidence to share. Thanks
