### ISSUE TITLE
cli/demo: make --empty defaultable via an env var

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#47757]
I find myself adding `--empty` all the time to `cockroach demo`.

Discussed with @jordanlewis @awoods187  - maybe it's OK if we pre-load `movr` for community adopters, but it's really counter-productive to CRL engineers who use the `demo` shell to do feature development and testing.

A possible compromise would be to make `--empty` configurable via an env var so we don't have to add the flag all the time.

**Comment by knz** [comment]
cc @rohany

**Comment by tharun208** [comment]
@knz, I like to work on this

**Comment by knz** [comment]
@tharun208 thanks for your interest.

I noticed that you created a PR *and even a doc change* before I could even answer your question.
Since we are not in the same time zone, I would recommend that you let at least 24 hours between the moment you ask for direction on the issue and the moment you start working on a solution.

**Comment by tharun208** [comment]
sure @knz
