### ISSUE TITLE
kv: Telemetry for Protected Timestamps

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach#47793]
**Is your feature request related to a problem? Please describe.**
Today, internally, we are unable to track % of clusters with Protected timestamps enabled.

**Describe the solution you'd like**
In the Features table, I'd like to be able to query % of clusters using protected timestamps. It's possible for customers to disable it.

**Describe alternatives you've considered**
n/a

**Additional context**
Here is an example Looker Look of % of Clusters using Follower Reads: https://cockroachlabs.looker.com/looks/95
If you don't have access to Looker, reach out to @katedoebler

**Comment by ajwerner** [comment]
I'm not really sure I understand what metric you're looking for. Protected timestamps isn't a feature a use "uses". It has no direct user-facing interface. It is used to fix "bugs" or UX fails in other features where garbage collection would either render a table in a bad state or would lead to operation failure.

Bugs: Canceled `IMPORT INTO`
Bad experience: `CHANGFEEDS`, `BACKUPS`

It's hard to say what we mean by usage.

**Comment by johnrk** [comment]
It can't be configured in cluster settings?

**Comment by ajwerner** [comment]
No
