### ISSUE TITLE
misc: log spam when a node is dead

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#4784]
On a real cluster, one of the nodes died (and stays dead: auto-restart is not enabled).
All other nodes log the following approximately once second:

```
I160302 21:03:25.753699 /go/src/google.golang.org/grpc/clientconn.go:463  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 172.31.58.172:26257: getsockopt: connection refused"; Reconnecting to "ip-172-31-58-172:26257"
I160302 21:03:25.754801 /go/src/google.golang.org/grpc/clientconn.go:318  Failed to dial ip-172-31-58-172:26257: grpc: timed out trying to connect; please retry.
```

We have a few options:
- do nothing
- log at a higher verbosity level when we've been failing for a while (logging change only)
- backoff retries more (behavior change)

**Comment by tamird** [comment]
Note that these retries are up in grpc.

**Comment by petermattis** [comment]
@tamird Is there nothing that can be done here?

**Comment by tamird** [comment]
We can (and should) `Close` the grpc connection. We need to plumb knowledge
of the node's downedness back to the RPC context for this, and currently,
we do not.

**Comment by mberhault** [comment]
dup of #14564
