### ISSUE TITLE
rpc: inter-tenant connections

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#47899]
Past phase 2 of the multi-tenancy proposal, we may start looking at running more than one SQL tenant server (per tenant). Various features require communication between tenant processes, for example distSQL or SHOW QUERIES.
They all will have a need for a liveness and RPC layer, involving only the running SQL servers for the given tenant.

Epic: CRDB-26687
Jira issue: CRDB-4379

**Comment by knz** [comment]
@dhartunian can you cross-ref this issue with the "cross-pod" project's issues?
We can't close this one (47899) because there are references to it inside the source code (label X-anchored-telemetry)

**Comment by knz** [comment]
We've solved this issue through the summer, thanks to work by @dhartunian .

**Comment by knz** [comment]
Actually we still have 4 crdb_internal tables that refer to this issue. We still need to complete the work for those.

**Comment by knz** [comment]
this has been solved
