### ISSUE TITLE
bulkio: backup/restore tenant awareness

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#47896]
[See here for background](https://docs.google.com/document/d/1EI8T-3N77g0OOlALwzRC0ddji1_4rH2xZvG9GbAa6D0/edit?ts=5e7a83b4#)

Cluster-wide backup and restore needs to be aware of the tenant keyspace and must be able to both store and restore it (wholesale, into a new cluster).

Note that enabling tenants to take backups of only their data (or restore it) is explicitly out of scope for phase 2, though it will ultimately be required at some point in the future.

Jira issue: CRDB-4380

**Comment by tbg** [comment]
Now that tenants are already supported on master (rather, all of the code that bulk i/o needs to care about is there):

```
select crdb_internal.create_tenant(5);
  crdb_internal.create_tenant
-------------------------------
                            5
(1 row)

Time: 4.697ms

root@127.0.0.1:61346/movr> select * from system.tenants;
  id | active | info
-----+--------+-------
   5 |  true  | NULL
(1 row)

Time: 7.301ms
```

here are some more impl notes.

There is a system.tenants table. For each entry in that table, there is a /Tenant/<tenantID>  key prefix containing that tenant’s logical cluster (with no ties to the outside world). However, backup/restore doesn't really need to care about the per-tenant prefix. It just needs to grab a consistent MVCC snapshot (consistent with the backup's timestamp) over the span containing all tenants, pseudo code: `TenantSpan := Span{Key: /Tenant EndKey: /Tenant.PrefixEnd()}`

There is also a system-wide zone config for that entire span only and nothing finer-grained  (i.e. nothing on a per-tenant basis).

So I think it should be relatively easy: the system tables and zone configs will already be included in the cluster-wide backup of the system tenant (or should be trivial to ad them). The tenant key span will have to be added to the backup, and it will have to be restored with the RESTORE.

**Comment by nvanbenschoten** [comment]
It will also be instructive to look at each use of `keys.TODOSQLCodec` in `pkg/ccl/backupccl`. These indicate the places that we're assuming that we are backing up the system tenant.

**Comment by nvanbenschoten** [comment]
@dt do you mind posting an update here when you get a chance? https://github.com/cockroachdb/cockroach/pull/50967 got us a lot of the way, but it backs up a single tenant, not every tenant in the cluster, right? We'll still want a way to back up every tenant in the cluster.

On that note, what happens today with the `system.tenants` table with BACKUP today?

**Comment by dt** [comment]
#50967  introduced `BACKUP TENANT x` and `RESTORE TENANT x`.

For an MVP, that alone could be enough -- we could run a script like ```for i in `SELECT id FROM system.tenants`; do BACKUP TENANT $i TO 'path/$i'; done;``` to backup all the tenants. Indeed, this might even be a preferred way to do it for some deployments, if it lets us spread the load over more time or give different tenants different backup SLAs, or avoid generating one giant mega backup if we had millions of tenants.

But it obviously would also be useful to have `BACKUP TO x` (aka cluster backup) automatically include all tenants since they are part of "the cluster", and I think explicitly specifying multiple tenants would be nice to have too, e.g. `BACKUP TENANTS x, y, y` or even `BACKUP TENANTS BETWEEN x AND y` or whatever. Our current plan is to revisit those once we've gotten more of our big-rock 20.2 commitments into acceptance testing, so we can have time to polish if needed before stability, given that the tenancy work isn't linked to the 20.2 schedule.

**Comment by tbg** [comment]
> On that note, what happens today with the system.tenants table with BACKUP today?

@dt what was the answer here? Nathan and I were wondering if this table got backed up, but without any of the tenants. (Of course you know my favorite solution: back up all of the tenants as well :-) )

I already mentioned this non-publicly, but multi-tenant MVP is essentially on the 20.2 schedule. We'll only deploy release-20.2 or a short-lived variation of it (i.e. we might push out a patch for testing before we ship it to release-20.2), and we're also scheduled to launch at a similar time.

**Comment by tbg** [comment]
I'm working through this with @dt over in https://github.com/cockroachdb/cockroach/pull/52096. The goal is to be able to include all tenants in incremental, no-revision-history full cluster backups. (Pending confirmation that this will be enough to get MVP off the ground).

**Comment by tbg** [comment]
As of #52096, tenants are included in full cluster backup with revision history (and can be restored).
cc @chrisseto please confirm that this is workable for CC for the initial launch.

I removed this from the blockers list. Originally I was hoping to add `WITH REVISION HISTORY` as well (there didn't seem any hard blockers) but since the story around tenant deletion hasn't moved much and I have to work on some other items, realistically it won't happen unless it rises to blocker status again.
