### ISSUE TITLE
sql: harden SQL endpoint

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#47908]
[Background](https://docs.google.com/document/d/1EI8T-3N77g0OOlALwzRC0ddji1_4rH2xZvG9GbAa6D0/edit?ts=5e7a83b4#heading=h.4vc8e8rw3cvq)

SQL servers that are exposed to the public internet need to be hardened in (at least) the following ways:

- rate limit brute force attempts (for obvious reasons, but also our use of bcrypt and KV lookups makes these very expensive internally) while at the same time continuing to service legitimate logins
- additional security audit pass

@knz anything else? And apologies if I'm double-posting, but I couldn't find an issue about this yet.

**Comment by knz** [comment]
Dup https://github.com/cockroachdb/cockroach/projects/19#card-36491797
