### ISSUE TITLE
kv: consider lower number of splits inside of a tenant's prefix

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#47907]
See [this doc](https://docs.google.com/document/d/1EI8T-3N77g0OOlALwzRC0ddji1_4rH2xZvG9GbAa6D0/edit?ts=5e7a83b4#heading=h.4vc8e8rw3cvq).

At the time of writing, a tenant is initialized with dozens of splits which are mostly useless since the adjacent ranges are mostly inactive/empty and share a zone config.

If the number of replicas per node ever becomes an issue (i.e. if thousands of tenants share a small cluster) we should consider omitting these unused splits. Instead, a split should only happen by load, size, or zone config (the latter of which the tenant is unlikely to ever be handed free reigns over).

**Comment by tbg** [comment]
@nvanbenschoten this can be closed, right?

**Comment by nvanbenschoten** [comment]
Yes, we currently don't create any mandatory splits inside of a tenant prefix.
