### ISSUE TITLE
sql: tenant deletion

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#47904]
Add a builtin creating/deleting the keyspace for a given tenant ID as outlined in the [design doc](
https://docs.google.com/document/d/1EI8T-3N77g0OOlALwzRC0ddji1_4rH2xZvG9GbAa6D0/edit?ts=5e7a83b4#heading=h.4vc8e8rw3cvq) as well as an internal (zero-tenant) metadata table that keeps track of which tenants exist.

**Comment by tbg** [comment]
What's left here is tenant deletion, right?

**Comment by nvanbenschoten** [comment]
Yes. I marked https://github.com/cockroachdb/cockroach/issues/48775 as a blocker and am folding this into it.
