### ISSUE TITLE
protectedts: disable/don't use on SQL tenants

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#47914]
[Background here](https://docs.google.com/document/d/1EI8T-3N77g0OOlALwzRC0ddji1_4rH2xZvG9GbAa6D0/edit?ts=5e7a83b4#heading=h.4vc8e8rw3cvq)

Protected timestamps will be disabled in phase 2. To the best of my knowledge, the only use of them that is required for correctness is `IMPORT INTO`, which will be disabled in phase 2 anyway (https://github.com/cockroachdb/cockroach/issues/47913). The other uses are advisory and should be skipped on tenants (easy to detect after https://github.com/cockroachdb/cockroach/issues/47903).

**Comment by nvanbenschoten** [comment]
@tbg can we close this? Is the remainder of this tracked in https://github.com/cockroachdb/cockroach/issues/47915?
