### ISSUE TITLE
protectedts: rework design for multi-tenancy

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#47915]
[Background here](https://docs.google.com/document/d/1EI8T-3N77g0OOlALwzRC0ddji1_4rH2xZvG9GbAa6D0/edit?ts=5e7a83b4#heading=h.4vc8e8rw3cvq)

Protected timestamps will be disabled in phase 2. Post that, we may want to find a way to enable them again, which needs some design work.

cc @ajwerner who originally built protectedts.

**Comment by nvanbenschoten** [comment]
Closing in favor of https://github.com/cockroachdb/cockroach/issues/67271.
