### ISSUE TITLE
cdc: disable on sql tenant servers

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#47916]
Same as https://github.com/cockroachdb/cockroach/issues/47913 but for CDC (which can also be told to talk to arbitrary endpoints).

CDC won't work without DistSQL, and DistSQL will be off initially, but it will still be good to properly disable CDC for tenants.

Epic CRDB-2608

**Comment by stevendanna** [comment]
Hrm, I'm not sure we want to do this anymore  We separately have a flag to enable or disable external io.
