### ISSUE TITLE
value type string doesn't match type STRING[] 

### ISSUE THREAD

**Issue by hazcod** [cockroachdb/cockroach#47956]
**Describe the problem**

CockRoachDB returns `value type string doesn't match type STRING[]` when inserting an Array.
This is generated by `go-pg/pg` and works on PostgreSQL (12).

**To Reproduce**

```sql
CREATE TABLE server_os (
    sro_cpes          text[]
);

INSERT INTO "server_os" ("sro_cpes")
VALUES ('{"","cpe:/h:hp:jetdirect_170x"}');
```

**Expected behavior**
Insert the array as it works on postgresql: https://www.db-fiddle.com/f/gqh6eXFc6zBEBy5YdHcDgC/1

**Additional data / screenshots**
pq: value type string doesn't match type STRING[] of column "sro_cpes"

**Environment:**
 - CockroachDB version: 19.1.5
 - Server OS: docker
 - Client app: cli + go-pg/pg

**Comment by jordanlewis** [comment]
Hi @hazcod, this works in version 19.2 and higher, but not 19.1. Sorry about that. As a workaround, you'd need to use the `ARRAY` constructor method like `ARRAY['foo']`.

```
# Server version: CockroachDB CCL v19.2.0 (x86_64-apple-darwin14, built 2019/11/12 05:07:10, go1.12.12) (same version as client)
# Cluster ID: 65e554a1-edec-4f79-a6a0-b9745cdded14
# Organization: Cockroach Demo
#
# Enter \? for a brief introduction.
#
root@127.0.0.1:53019/movr> CREATE TABLE server_os (
    sro_cpes          text[]
);

INSERT INTO "server_os" ("sro_cpes")
VALUES ('{"","cpe:/h:hp:jetdirect_170x"}');
CREATE TABLE

Time: 2.565ms

INSERT 1

Time: 2.642ms
```

**Comment by hazcod** [comment]
Thanks for the headsup, will anxiously await the next stable release.

**Comment by jordanlewis** [comment]
Hi @hazcod, 19.2 already has this feature and has been out for 6 months! It's a stable release as well. https://www.cockroachlabs.com/docs/stable/install-cockroachdb-linux.html

**Comment by hazcod** [comment]
Ah, not present on docker hub.

**Comment by jordanlewis** [comment]
It isn't? I see this: https://hub.docker.com/layers/cockroachdb/cockroach/v19.2.6/images/sha256-6a2e37b0b4d358b1676874ca6ad32f4ea4d33fd15b495dcd5123b5c4b73c254f?context=explore

**Comment by hazcod** [comment]
D'oh, apologies, dependabot wasn't keeping my repo up-to-date with that one: https://github.com/ironPeakServices/iron-cockroachdb/packages/45315
