### ISSUE TITLE
bulkio: BACKUP/RESTORE/IMPORT for use by tenants

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#47970]
[Background](https://docs.google.com/document/d/1EI8T-3N77g0OOlALwzRC0ddji1_4rH2xZvG9GbAa6D0/edit?ts=5e7a83b4#)

At some point in the (non-near term) future, we'll want tenants to be able to back up, restore, and import into their virtual cluster.

**Comment by pbardea** [comment]
Adding a bit more context on this issue. Breaking it down by bulk IO feature:
- [x] Import
       - Completed by https://github.com/cockroachdb/cockroach/pull/57258
- [x] Backup
       - Completed by https://github.com/cockroachdb/cockroach/pull/57317 and https://github.com/cockroachdb/cockroach/pull/57641
- [ ] Restore
       - To be addressed in https://github.com/cockroachdb/cockroach/pull/58908

**Comment by mwang1026** [comment]
From offline conversation, an expectation of the RESTORE work is rekeying to facilitate:
* Restore tenant backup into tenant with different tenant ID
* Restore tenant backup into a "dedicated" cluster
* Restore a "dedicated" backup into a tenant cluster
