### ISSUE TITLE
cli: `cockroach demo` and `cockroach start` use inconsistent terminology

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#47977]
The two sub-commands `demo` and `start` / `start-single-node` both report server connection strings on the terminal.

However they do so using different words: "console" vs "webui", "sql" vs "sql/tcp", generally the look & feel is different.

We can make the UX more consistent and regular by sharing the terminology between the two.

(Reported by @jseldess )

**Comment by tharun208** [comment]
@knz, I like to work on this , so, before starting what are the words we are going to use ?. I think `webui` and `sql` is more easy to understand.
