### ISSUE TITLE
[Feature Request] Pre-filter hook just before gossip consensus

### ISSUE THREAD

**Issue by diyism** [cockroachdb/cockroach#48007]
I want use CockroachDB to build an alliance database service,
for example,  there are 50 developers in my mesh network, the developer's nodes work as Raft consensus nodes, and there are 10000 users, the user's nodes work as readonly replication nodes.

By default, all developer node have full write access to the CockroachDB, but I want to apply some business logic to the write access to prevent some unwanted data enter the DB, and I even want to prevent these invalid data changes gossip to be rebroadcast to the whole mesh network.

I know I can remove the evil node/developer from my mesh network after I found the evil behaviors,
but I want to prevent the illegal data enter the DB, because this is a transparent data service for my 10000 end users, the end users should not see the illegal data for a second.

So, I want a method to inject the gossip receiving step to filter illegal data changes,
maybe CockroachDB could add a data filter hook option to enable us call callback function to prevent illegal data to be relayed and to prevent illegal data to enter the DB.

Relative issue: https://github.com/cockroachdb/cockroach/issues/38159

**Comment by diyism** [comment]
@tim-o , @tbg ,  @awoods187 ,  may anybody give a comment?
I think if we can add Data Entry Hook feature into CockroachDB, then CockroachDB  will replace the blockchain technology in future.

**Comment by diyism** [comment]
YugabyteDB support Stored procedures and Triggers, 
but it does not support Pre-filter (just before gossip consensus) 
and it is not a real distributed database, 
while CockroachDB is a real distributed DB. 
Because even only 3 live nodes left in the cockroachDB mesh network, the leader/master will automatically elected but YugabyteDB needs pre-set master nodes. 

If CockroachDB can support Pre-filter(before gossip consensus) hook, it will became a real perfect distributed database.

**Comment by diyism** [comment]
https://wiki.hyperledger.org/display/INTERN/Enabling+CockroachDB+as+a+State+Database+for+Hyperledger+Fabric

someone want to modify CockroachDB to make it a blockchain database for Hyperledger Fabric

I think that they maybe will add a gossip hook or gossip pre-validator to CockroachDB.

**Comment by diyism** [comment]
I've tried the command "build/builder.sh mkrelease arm64-linux" and got an arm64 version of CockroachDB right now.
Cool, if we can realize the "pre-consensus trigger" or "pre-consensus data validator/filter" in this issue, we can deploy CockroachDB blockchain into so many cheap single-board-computers such as Pine64, Raspberry Pi, Banana Pi etc.
The poor people's blockchain.

**Comment by diyism** [comment]
![Screenshot_2020-07-17 cockroachdb_2017 pdf](https://user-images.githubusercontent.com/1744399/87705527-99761880-c7d0-11ea-858d-9fa98c7b069a.png)

https://cs.ulb.ac.be/public/_media/teaching/cockroachdb_2017.pdf
1.sql layer(entry node to translate client sql query to kv operations)
2.transactional layer(package kv operations as a batch)
3.distribution layer(routing batch of kv operations to raft consensus leader)
4.replication layer(consensus algorithm forms a quorum and finalize batch requests into relevant storage range nodes)
5.storage layeer

After reading the document, I think that the "pre-consensus data validator" only possible be build on the "4.replication layer",
but on this layer, the datas are in kv operations state that are difficult for business logic to parse them and validate them.

**Comment by diyism** [comment]
![Screenshot_2020-07-17 Raft](https://user-images.githubusercontent.com/1744399/87768835-54dd9200-c84f-11ea-82d6-5572d8cbde35.png)

In the 4th layer of replications layer,  if the leader node is malicious node, the most of other nodes won't approve the commit of kv wirite.

**Comment by irfansharif** [comment]
@diyism Thanks for posting here! Reading through this, I'll say that we don't currently expose any CRDB internal primitives to our end users (Gossip being one of them), and are thus unlikely to extend our internal primitives in such ways either. That being said, I don't quite follow why the kind of validation you're describing needs to exist at the level of the database. I don't know that I quite understand what you're looking to do, but we're currently (and probably for a long time going forward) going to be focused on CRDB's usability as a "simple" SQL database, and this seems a lot more exotic than that. I'm going to close out this issue on that basis alone. 

All that being said, isn't it possible to do what you're doing at the application level? Why does it need to be at the database level?

**Comment by diyism** [comment]
> All that being said, isn't it possible to do what you're doing at the application level? Why does it need to be at the database level?

@irfansharif  I'm tring build a distributed database on an open mesh network(over wireguard), anyone can join the network through vote by current members, so maybe there's one or two malicious nodes in the mesh network, and I want there's a Hook/Filter feature in CrDB to validate/filter the illegal (ie. break the my community rules or business logics) sql statements(or kv operations) in the Replication layer(or Raft consensus layer) of CockroachDB.

**Comment by irfansharif** [comment]
I see. Hm, I'm not sure that that's the sort of topology that we're looking to support in the near term (it's all too byzantine for our tastes). We'll be sure to re-visit this issue should that change.

**Comment by diyism** [comment]
rqlite support sql-level consensus, but rqlite doesn't support to split data into ranges automatically.
