### ISSUE TITLE
storage: TestStoreRangeSystemSplits is too fragile (needs rewrite)

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#4800]
`TestStoreRangeSystemSplits` tests that splits are based on the contents of the `SystemConfig`. It does this in a fragile manner by taking the initial SQL metadata keys and creating additional descriptor entries derived from those keys/values in order to force splits. We could much more directly create tables and verify the split points rather than the current shenanigans.

**Comment by tschottdorf** [comment]
Unlikely to ever be acted upon.
