### ISSUE TITLE
sql: respect jsonb_path_ops when creating inverted indexes using gin syntax

### ISSUE THREAD

**Issue by jfinity** [cockroachdb/cockroach#48002]
I'm interested in storing many string values in a jsonb column that need not be indexed and I'd like to keep a GIN index on that column from growing unnecessarily.

My plan is to structure the data along these lines:

```json
{
  "key_to_index": "value_to_index",
  "very_long_string_value_I_do_not_want_indexed": {},
  "more_long_string_values_can_opt_out_of_indexing_as_well": {},
  "etc": {}
}
```

Following #23888, it sounds like currently all GIN indexes implicitly behave as though `jsonb_path_ops` was passed (so a query for `@> '{"key_to_index": "value_to_index"}'::jsonb` would be "fast" while the inverted index would remain "small"), but there appears to be no clear guarantee anywhere that this behavior [will endure](https://github.com/cockroachdb/cockroach/issues/23888#issuecomment-373430914) (even if `jsonb_path_ops` were specified explicitly):

> I don't think this is a serious problem. Our index representation will permit us to index on the operators missing from `jsonb_path_ops` over time. As a reminder, here are the missing operators:

If `jsonb_path_ops` _is_ present when creating a GIN index, will the existing/expected behavior be guaranteed in future releases (and if not, can it be)?

---

I'm relatively new to SQL, so please forgive me if I'm misunderstanding how `jsonb_path_ops` indexing works.  My reference -- https://www.postgresql.org/docs/9.4/datatype-json.html -- states that:

> A disadvantage of the jsonb_path_ops approach is that it produces no index entries for JSON structures not containing any values, such as {"a": {}}.

(For my purposes, I don't consider this behavior to be as "disadvantageous" as the docs suggest!)

Jira issue: CRDB-4365

**Comment by jordanlewis** [comment]
Currently, we do in fact store index entries for values that terminate in empty collections. We don't support these kinds of index modifiers yet, either - there's just 1 kind of json inverted index we support, with this behavior.

I think your idea is interesting and not yet possible in CockroachDB. Though, we're working on adding partial computed indexes in the medium term - this might help, because you'd be able to specify just some paths to index in your JSON documents, like:

```
CREATE INDEX ON t USING GIN (j->"key_to_index")
```

Would that satisfy your use case?

**Comment by jfinity** [comment]
Thanks for the swift reply!

Unfortunately the partial index doesn't seem like a good fit for my json structures as planned... I simplified my example a bit -- the keys I want to index will be numerous, unstructured, and nested.  More realistic queries would look like `@> '{"deeply", {"nested": {"object": { "key_to_index": "value_to_match" }}}}'::jsonb`, where the path to the value to be matched is not known at schema definition time (and there may be multiple value paths I want to match against at query time).  The value paths I want indexed will have (nested) sibling keys that I *don't* want indexed.

My backup plan right now is to have 2 different jsonb columns -- one indexed and the other unindexed -- that have the same key-path shape ...I was just hoping not to have to duplicate s bunch of data.

**Comment by jfinity** [comment]
Follow-up question, it doesn't look like (syntactically) you cannot have `STORING` columns on `INVERTED` ... but how about when are `USING GIN`?
