### ISSUE TITLE
regression: sql: unable to use subqueries in SET, SET CLUSTER SETTINGS etc

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#48010]
This was possible in CockroachDB 2.x and 19.1:

```
> SET application_name = (SELECT 'a' || 'b');
SET
> SHOW  application_name;
  application_name
+------------------+
  ab
(1 row)
```

In CockroachDB 19.2, it causes an internal error:

```
pq: internal error: invalid index 1 for "(SELECT 'a' || 'b')"
/data/home/kena/src/go-c192/src/github.com/cockroachdb/cockroach/pkg/sql/subquery.go:47: EvalSubquery()
/data/home/kena/src/go-c192/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:4160: Eval()
```

In CockroachDB 20.1, it's been transformed into a typing error:

```
ERROR: invalid value for parameter "application_name": "(SELECT 'a' || 'b')"
SQLSTATE: 22023
DETAIL: subqueries are not allowed in SET
```

I don't think there's a very good reason to prevent the behavior.

### Desired resolution

- reinstate the behavior in 20.1
- backport the fix to 19.2
- mark the regression as fixed

(found by @dbist via #42909 )

**Comment by knz** [comment]
cc @RaduBerinde @rohany for triage.

**Comment by RaduBerinde** [comment]
Dup of #42896. Thanks for investigating the behavior in various versions, I copied your description in that issue.
