### ISSUE TITLE
cli: make `debug zip` skip over known deco+dead nodes

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#48021]
The code for `cockroach gen haproxy` already does this. `debug zip` should do the same.

Requested by @jasobrown

**Comment by jasobrown** [comment]
Having to wait for `debug zip` to skip over decommissioned nodes is a huge problem when trying to grab logs from production clusters that are having problems. It's guaranteed block time for operators who need to investigate a troubled cluster. Would love to see this resolved quickly.
