### ISSUE TITLE
storage: evaluate perf impact of RocksDB's cache_index_and_filter_blocks

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#48039]
RocksDB's `cache_index_and_filter_blocks` option causes index and filter blocks to not be pinned in memory, but to instead be placed in the cache which allows them to be subject to eviction. Placing these blocks in cache "fixes" an apparent memory leak when the size of these blocks is large. See #47686 for an example.

We've avoided setting `cache_index_and_filter_blocks` to true by default because there is a performance overhead to doing so. This issue is about quantifying that overhead to inform whether we should revisit that decision. Even if we don't change the default, we'll be able to provide guidance on what impact changing this option has on standard workloads. The intention is to examine `kv{0,95}`, `ycsb/*`, `sysbench`, and `tpcc`. 

Also, for posterity, this RocksDB option can be set on the command line: `--store="<path>=,rocksdb=block_based_table_factory={cache_index_and_filter_blocks=true}"`

See also #7576 and #10050.

**Comment by petermattis** [comment]
Below old is current master (29cead1bcb4fa50eecf8cb528e25f4f963c8d2a9) and new is the same SHA with the following diff applied:

```
diff --git a/c-deps/libroach/options.cc b/c-deps/libroach/options.cc
index 366c141e73..77b2869493 100644
--- a/c-deps/libroach/options.cc
+++ b/c-deps/libroach/options.cc
@@ -351,6 +351,7 @@ rocksdb::Options DBMakeOptions(DBOptions db_opts) {
   // the "whole key", doubling the size of our bloom filters. This is
   // used to speed up Get operations which we don't use.
   table_options.whole_key_filtering = false;
+  table_options.cache_index_and_filter_blocks = true;
   options.table_factory.reset(rocksdb::NewBlockBasedTableFactory(table_options));
   return options;
 }
```

```
~ benchstat out.normal out.cache_index_and_filter_blocks
name                                                    old ops/sec  new ops/sec  delta
kv0/enc=false/nodes=1                                    17.5k ± 0%   17.2k ± 0%   -1.41%  (p=0.000 n=8+9)
kv0/enc=false/nodes=3                                    20.7k ± 5%   20.8k ± 5%     ~     (p=0.529 n=10+10)
kv95/enc=false/nodes=1                                   26.7k ± 1%   26.3k ± 1%   -1.80%  (p=0.000 n=10+10)
kv95/enc=false/nodes=3                                   46.3k ± 3%   46.0k ± 4%     ~     (p=0.579 n=10+10)
ycsb/A/nodes=3                                           21.2k ± 3%   21.2k ± 3%     ~     (p=0.905 n=9+10)
ycsb/B/nodes=3                                           38.9k ± 4%   38.5k ± 4%     ~     (p=0.436 n=10+10)
ycsb/C/nodes=3                                           54.7k ± 2%   54.5k ± 3%     ~     (p=0.720 n=9+10)
ycsb/D/nodes=3                                           43.7k ± 2%   44.0k ± 1%     ~     (p=0.068 n=10+8)
ycsb/E/nodes=3                                           6.00k ± 1%   6.00k ± 1%     ~     (p=0.529 n=10+10)
ycsb/F/nodes=3                                           9.47k ± 4%   9.26k ± 3%   -2.20%  (p=0.028 n=9+10)
sysbench/oltp_delete/nodes=3/cpu=32/conc=128             56.8k ±11%   54.2k ± 9%     ~     (p=0.190 n=10+10)
sysbench/oltp_insert/nodes=3/cpu=32/conc=128             24.8k ± 2%   22.1k ± 8%  -10.96%  (p=0.000 n=8+9)
sysbench/oltp_point_select/nodes=3/cpu=32/conc=128        103k ± 5%    106k ± 1%   +2.90%  (p=0.002 n=10+9)
sysbench/oltp_read_only/nodes=3/cpu=32/conc=128          94.3k ± 2%   94.6k ± 1%     ~     (p=0.356 n=9+10)
sysbench/oltp_read_write/nodes=3/cpu=32/conc=128         61.5k ±13%   58.6k ± 8%   -4.68%  (p=0.035 n=10+10)
sysbench/oltp_update_index/nodes=3/cpu=32/conc=128       18.3k ± 9%   17.0k ± 3%   -6.83%  (p=0.008 n=10+9)
sysbench/oltp_update_non_index/nodes=3/cpu=32/conc=128   37.8k ±26%   35.6k ±31%     ~     (p=0.247 n=10+10)
sysbench/oltp_write_only/nodes=3/cpu=32/conc=128         35.4k ± 8%   32.5k ± 9%   -8.10%  (p=0.002 n=10+10)

name                                                    old p50      new p50      delta
kv0/enc=false/nodes=1                                     3.40 ± 0%    3.40 ± 0%     ~     (all equal)
kv0/enc=false/nodes=3                                     6.80 ± 0%    6.70 ± 6%     ~     (p=0.125 n=10+10)
kv95/enc=false/nodes=1                                    2.10 ± 0%    2.16 ± 3%   +2.86%  (p=0.011 n=10+10)
kv95/enc=false/nodes=3                                    3.00 ± 0%    3.00 ± 0%     ~     (all equal)
ycsb/A/nodes=3                                            2.70 ± 7%    2.70 ± 7%     ~     (p=0.928 n=9+10)
ycsb/B/nodes=3                                            2.55 ± 2%    2.53 ± 5%     ~     (p=0.599 n=10+9)
ycsb/C/nodes=3                                            2.40 ± 0%    2.43 ± 3%     ~     (p=0.211 n=10+10)
ycsb/D/nodes=3                                            1.77 ± 4%    1.77 ± 4%     ~     (p=1.000 n=10+10)
ycsb/E/nodes=3                                            11.0 ± 0%    10.7 ± 3%   -2.73%  (p=0.006 n=9+10)
ycsb/F/nodes=3                                            6.32 ± 8%    6.26 ± 7%     ~     (p=0.582 n=9+10)

name                                                    old p95      new p95      delta
kv0/enc=false/nodes=1                                     6.30 ± 0%    6.60 ± 0%   +4.76%  (p=0.000 n=10+9)
kv0/enc=false/nodes=3                                     26.4 ± 5%    26.2 ± 0%     ~     (p=0.625 n=10+8)
kv95/enc=false/nodes=1                                    4.41 ± 5%    4.50 ± 0%     ~     (p=0.211 n=10+10)
kv95/enc=false/nodes=3                                    13.6 ± 0%    13.8 ± 3%     ~     (p=0.353 n=7+10)
ycsb/A/nodes=3                                            13.9 ± 2%    13.8 ± 3%     ~     (p=0.230 n=9+10)
ycsb/B/nodes=3                                            12.4 ± 6%    12.5 ± 5%     ~     (p=0.577 n=10+10)
ycsb/C/nodes=3                                            6.80 ± 0%    6.89 ± 3%     ~     (p=0.248 n=9+10)
ycsb/D/nodes=3                                            6.39 ± 3%    6.30 ± 0%     ~     (p=0.137 n=10+8)
ycsb/E/nodes=3                                            49.0 ± 3%    49.5 ± 3%     ~     (p=0.656 n=10+10)
ycsb/F/nodes=3                                            31.6 ± 4%    32.7 ± 4%   +3.36%  (p=0.027 n=9+8)
sysbench/oltp_delete/nodes=3/cpu=32/conc=128              8.05 ± 8%    8.42 ± 5%     ~     (p=0.074 n=10+10)
sysbench/oltp_insert/nodes=3/cpu=32/conc=128              12.5 ± 1%    14.2 ± 2%  +13.99%  (p=0.000 n=8+7)
sysbench/oltp_point_select/nodes=3/cpu=32/conc=128        1.84 ± 4%    1.79 ± 1%   -2.74%  (p=0.008 n=10+7)
sysbench/oltp_read_only/nodes=3/cpu=32/conc=128           29.3 ± 3%    29.2 ± 0%     ~     (p=0.711 n=10+8)
sysbench/oltp_read_write/nodes=3/cpu=32/conc=128          68.7 ±40%    77.3 ±22%     ~     (p=0.071 n=10+10)
sysbench/oltp_update_index/nodes=3/cpu=32/conc=128        16.1 ±14%    16.8 ± 7%     ~     (p=0.282 n=10+9)
sysbench/oltp_update_non_index/nodes=3/cpu=32/conc=128    8.52 ±20%    8.84 ±22%     ~     (p=0.626 n=10+10)
sysbench/oltp_write_only/nodes=3/cpu=32/conc=128          39.6 ±26%    44.7 ±23%     ~     (p=0.127 n=10+10)

name                                                    old p99      new p99      delta
kv0/enc=false/nodes=1                                     14.2 ± 0%    14.2 ± 0%     ~     (all equal)
kv0/enc=false/nodes=3                                     38.3 ± 9%    38.3 ± 7%     ~     (p=1.000 n=10+10)
kv95/enc=false/nodes=1                                    11.0 ± 0%    11.0 ± 0%     ~     (all equal)
kv95/enc=false/nodes=3                                    23.1 ± 0%    23.1 ± 0%     ~     (all equal)
ycsb/A/nodes=3                                            32.5 ±29%    32.2 ±30%     ~     (p=0.854 n=9+10)
ycsb/B/nodes=3                                            23.5 ±16%    23.8 ±10%     ~     (p=0.461 n=10+10)
ycsb/C/nodes=3                                            11.5 ± 0%    11.7 ± 7%     ~     (p=0.248 n=9+10)
ycsb/D/nodes=3                                            11.5 ± 0%    11.1 ± 3%   -3.04%  (p=0.001 n=8+10)
ycsb/E/nodes=3                                            85.6 ± 7%    88.1 ± 0%     ~     (p=0.081 n=10+7)
ycsb/F/nodes=3                                            75.0 ±40%    75.0 ±34%     ~     (p=0.991 n=9+9)
```

The perf impact of `cache_index_and_filter_blocks` is less than I was expecting. I suspect the `sysbench` benchmarks are more affected because they preload a dataset rather than starting from empty. That is just a suspicion, though. Will compare `tpccbench` next which will be more representative of real dataset sizes.

**Comment by petermattis** [comment]
Running `tpccbench/nodes=3/cpu=16`. With `cache_index_and_filter_blocks=false` (the current default), the `rocksdb.table-readers-mem-estimate` indicates the memory pinned by index and filter blocks:

![Screen Shot 2020-04-26 at 11 41 44 AM](https://user-images.githubusercontent.com/6201335/80312519-89dbca80-87b3-11ea-86fe-f9c39780b4a1.png)

With `cache_index_and_filter_blocks=true`, that metric is flatlined at 0. A side benefit of setting `cache_index_and_filter_blocks=true` is that we could stop collecting `rocksdb.table-readers-mem-estimate` which is somewhat expensive to do. See https://github.com/cockroachdb/cockroach/issues/47330.

**Comment by petermattis** [comment]
Derp! `tpccbench/nodes=3/cpu=16` maxed out at 2499 warehouses in both configurations (this was on AWS). Cc @nvanbenschoten. We should probably bump the warehouse values for this test, though only on 20.1 and later.

**Comment by petermattis** [comment]
I changed `tpccbench/nodes=3/cpu=16` to use a max-warehouses of 3000 and an estimated-warehouses of 2500. Old is with `cache_index_and_filter_blocks=false` and new is `cache_index_and_filter_blocks=true`:

```
name                      old warehouses  new warehouses  delta
tpccbench/nodes=3/cpu=16      2.74k ± 5%      2.56k ± 4%  -6.54%  (p=0.001 n=9+10)
```

So we see an ~6% perf hit from enabling this option. There is another option to fiddle with here: `cache_index_and_filter_blocks_with_high_priority`. I'm going to run another experiment with that option set to `true`.

**Comment by petermattis** [comment]
The perf hit is a little bit smaller if both `cache_index_and_filter_blocks=true` and `cache_index_and_filter_blocks_with_high_priority=true` are specified (this is `new` below):

```
name                      old warehouses  new warehouses  delta
tpccbench/nodes=3/cpu=16      2.74k ± 5%      2.64k ± 6%   ~     (p=0.062 n=9+10)
```

The default delta test indicates no statistical difference in the perf, yet visually there appears to be a 3.5% hit (this is what `benchstat -delta-test ttest` reveals). 

I realized while running this test that I haven't been doing an apples-to-apples comparison. With `cache_index_and_filter_blocks=false`, the index and filter blocks are not accounted for in the cache. As we saw above, these blocks accounted for ~1GB of memory across the 3 nodes, or ~330MB/node. So the cache is effectively 4.5% larger with `cache_index_and_filter_blocks=false` than with that option set to true. Not sure if this matters, though. The cache hit rate is pretty close to 99% (we're essentially never touching disk in this workload).

**Comment by nvanbenschoten** [comment]
Interesting tests! Does pebble expose the same knob?

> We should probably bump the warehouse values for this test, though only on 20.1 and later.

We've loaded up to 3000 warehouses in the past on this test but were occasionally running into disk space limits due to a combination of:
1. imbalanced imports
2. multiple, small SSDs on AWS
3. an inability to rebalance between multiple stores on the same node: https://github.com/cockroachdb/cockroach/issues/6782

I was hoping to wait out https://github.com/cockroachdb/cockroach/issues/6782, but we haven't managed to work that into our roadmap. The hope was for it to be an intern project. At some point, we were RAID striping these smaller SSDs to give us more disk space without using multiple stores, but doing so proved to hurt fsync performance. 

I'm going to try bumping the limit back up to 3000. Bason on [EC2's docs](https://aws.amazon.com/blogs/aws/ec2-instance-update-c5-instances-with-local-nvme-storage-c5d/),  `c5d.4xlarge` instances are given a single 400 GB SSD. While this does not match my memory at all, I suspect that it will be sufficiently large enough to support a 3000 warehouse import.

> The default delta test indicates no statistical difference in the perf, yet visually there appears to be a 3.5% hit (this is what benchstat -delta-test ttest reveals).

You are right above p=0.5, which is benchstat's default t-test alpha value. I'm sure you're aware, but you can pass an `--alpha` flag to change the p-value cutoff in cases where you'd prefer to get some output.

**Comment by petermattis** [comment]
> Interesting tests! Does pebble expose the same knob?

It does not. Pebble supports [weak cache handles](https://github.com/cockroachdb/pebble/blob/master/internal/cache/clockpro.go#L85) which gives many of the benefits of the pinned caching while not actually pinning. I want to experiment with Pebble further in this area.

> I'm going to try bumping the limit back up to 3000. Bason on EC2's docs, c5d.4xlarge instances are given a single 400 GB SSD. While this does not match my memory at all, I suspect that it will be sufficiently large enough to support a 3000 warehouse import.

I ran with 3000 max-warehouses without problems. From the above, on AWS we hit 2750 warehouses.

**Comment by petermattis** [comment]
Given that we're moving away from RocksDB, we're unlikely to make any adjustments to the RocksDB configuration.
