### ISSUE TITLE
ui: standard time selector ranges have disappeared

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#48049]
This is on master (29cead1bcb4fa50eecf8cb528e25f4f963c8d2a9). The standard time selector ranges such as "past 1 hour" have disappeared from the drop down menu.

![Screen Shot 2020-04-26 at 11 42 24 AM](https://user-images.githubusercontent.com/6201335/80312443-41bca800-87b3-11ea-97fd-e7f68730bf44.png)

**Comment by ajwerner** [comment]
Does this also capture the fact that the UI seems to no longer auto-update? Seems like https://github.com/cockroachdb/cockroach/issues/45364 might still be a problem.
