### ISSUE TITLE
ui: enhance Node Overview page

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#4804]
- Make the nodes table (which displays storage stats and range stats for each node) much narrower.
  - [x] Keep live bytes and omit or hide by default key bytes, value bytes, intent bytes, and system bytes.
  - [x] Keep available ranges and either omit or hide by default other range stats. 
- [x] Get rid of error calls, since it was originally but in for testing purposes.
- [x] Remove events tab and replace with aggregated node-level graphs (e.g. SQL queries across all nodes, transaction stats across all nodes). Maybe these aggregated graphs should be stacked, to help identify anomalous node behavior.
- [x] combine SQL reads & writes into single graph
- [x] rename "data" graph to "SQL traffic" or something else that's clearer
- [x] make all Y-axes for graphs start at 0, unless negative values make sense for that graph

**Comment by maxlang** [comment]
The main thing that remains here after #5243 is filling out the graphs tab.
