### ISSUE TITLE
ui: node count should use correct pluralization

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#4805]
A 1-node cluster, while a degenerate case, should be shown as "1 Node." See:

https://www.dropbox.com/s/7itr2k74ioi3ned/Screenshot%202016-03-02%2022.07.29.png?dl=0

**Comment by maxlang** [comment]
Probably not worth fixing, since I intend to make the node count more similar to this:
<img width="323" alt="screen shot 2016-03-08 at 2 33 00 am" src="https://cloud.githubusercontent.com/assets/3691886/13595003/29843a3e-e4d6-11e5-8a6c-05bf81451555.png">

**Comment by mrtracy** [comment]
Assigning to @maxlang, close it if you think this isn't worth fixing for beta, assign it back to me if you think we need it as a stopgap.

**Comment by maxlang** [comment]
Spoke to Andrew and I think it's worth fixing.
