### ISSUE TITLE
builtins: unable to perform DDLs using InternalExecutor from builtins

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#48061]
Consider https://github.com/cockroachdb/cockroach/compare/master...otan-cockroach:add_geometry_column.

In that commit, we are trying to implement [AddGeometryColumn](https://postgis.net/docs/AddGeometryColumn.html). However, when performing the DDL for ADD COLUMN, we don't see the column come about until another DDL is performed:

```
root@127.0.0.1:55945/movr> create table test_table(a int);
CREATE TABLE
root@127.0.0.1:55945/movr> select addgeometrycolumn('test_table', 'geom2', 4326, 'GEOMETRY', 2);
ALTER TABLE test_table ADD COLUMN geom2 GEOMETRY(GEOMETRY,4326)
  addgeometrycolumn
---------------------
root@127.0.0.1:55945/movr> \d test_table
  column_name | data_type | is_nullable | column_default | generation_expression |  indices  | is_hidden
--------------+-----------+-------------+----------------+-----------------------+-----------+------------
  a           | INT8      |    true     | NULL           |                       | {}        |   false
  rowid       | INT8      |    false    | unique_rowid() |                       | {primary} |   true
(2 rows)
root@127.0.0.1:55945/movr> select addgeometrycolumn('test_table', 'geom2', 4326, 'GEOMETRY', 2);
ERROR: addgeometrycolumn(): addgeometrycolumn: duplicate: column "geom2" in the middle of being added, not yet public
root@127.0.0.1:55945/movr> create table a (a int);
CREATE TABLE
root@127.0.0.1:55945/movr> select addgeometrycolumn('test_table', 'geom2', 4326, 'GEOMETRY', 2); -- NOW it exists.
ERROR: addgeometrycolumn(): addgeometrycolumn: duplicate column name: "geom2"
root@127.0.0.1:55945/movr>
```

According to @ajwerner 

> Yeah so I think the problem is that the extra txn state isn't propagating from the internal executor back to the user's transaction here
> I think we're going to need to find a way to rewrite that query at planning time to make infrastructure work correctly
> You can't just run it in the internal executor 

From looking at the pg_proc table after importing PostGIS, we can see that `AddGeometryColumn` is implemented as a user defined function that calls `ALTER TABLE` underneath, so it makes sense to me that we should be able to perform DDLs from any builtin at some time in the future.

Another @ajwerner quote:

> on a very high level I think I might agree with you that we'll need to find a way to support that functionality but the answer does not need to be that it needs to use the internal executor

**Comment by otan** [comment]
cc @RaduBerinde / @rytaft curious if you have thoughts based on rewriting the query at planning time.

**Comment by RaduBerinde** [comment]
@andreimatei is the InternalExecutor expert.

These functions are very strange. I get that they're convenient but making them work in general would be a pain. Can we at least assume that you'd only use them in a top-level SELECT with no FROM? If that's the case, we could have some special optbuilder code (or a normalization rule) that recognizes this and generates an ALTER TABLE statement (we can help with writing this code). In the rest of the cases, the built-in's Fn would just emit an error.

**Comment by otan** [comment]
> Can we at least assume that you'd only use them in a top-level SELECT with no FROM?

potentially, yes. have not seen enough PostGIS tools to make a definitive statement though.

(before mentioning not supporting this -- unfortunately some commonly used PostGIS tools output this so I can't say we can ignore it :()

**Comment by ajwerner** [comment]
@jordanlewis raising this for visibility as it seems like quite a pickle. 

I'm not sure how to properly address this. My sense is that hoisting support for DDLs into the `InternalExecutor` is both expensive (would require the engineering to properly lift the relevant planner state into the internal executor) and a bad idea in the short-medium term. We assume currently that the execution of a statement cannot move the state machine of the conn executor. The execution of a DDLs interacts with that state-machine pretty directly. 

I'm supportive of the approach @RaduBerinde is suggesting. If the arguments to this function are constant, then maybe we can hoist it above the rest of the statement and execute it independently.

**Comment by RaduBerinde** [comment]
Hoisting it sounds like a great idea. We could build it so it's always a separate subquery. We would still need to be able to execute the DDL statement as a subquery (I think that works already), and of course we need a corresponding DDL statement that actually returns what the function is supposed to return (what is it supposed to return by the way?)

**Comment by jordanlewis** [comment]
Based on very cursory searches on GitHub, I only have seen simple selects for the `addGeometryColumn` example so far. https://github.com/search?p=4&q=addgeometrycolumn&type=Code

I think it would be fine to do a really simple rewrite and see how far that gets us. I don't think we have a great need to start improving the rules to work for constants etc just yet...

**Comment by otan** [comment]
It returns

```

	return tree.NewDString(
		fmt.Sprintf("%s.%s SRID:%d TYPE:%s DIMS:%d", un.String(), columnName, srid, strings.ToUpper(shape), dimension),
	), nil
```

e.g. `schemname.tablename.columname SRID:1234 TYPE:POINT DIMS2`. can make a builtin do this if you wanted to (i.e. execute the DDL and then return the results of crdb_internal.addgeometrycolumn)
