### ISSUE TITLE
kv: telemetry for all cluster settings

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach#48060]
**Is your feature request related to a problem? Please describe.**
We don't have a system for collecting telemetry for all cluster settings. We need to be able to understand how customers are using Cockroach. For example, Follower the Workload, Parallel Commits, and Follower Reads can be disabled via cluster settings. It's imperative that we track adoption and cases of customers disabling those types of features.

**Describe the solution you'd like**
Ideally, we have a system that automatically updates the cluster settings telemetry when settings are added or removed. Based on conversations with @nvanbenschoten , this would be more efficient and reliable than creating one-off telemetry changes for each cluster-setting-based feature that's added or removed.

**Describe alternatives you've considered**
I've previously queried the registration table for cluster settings, and I've requested one-off telemetry items for features such as Follower the workload, Parallele Commits, Follower Reads, and Load based splitting.

**Additional context**
If we added these cluster settings to the Features Table in the Registration cluster, we could generate reports that say % of Clusters using Feature X. For example, % of Long-Running Clusters using Follower Reads: https://cockroachlabs.looker.com/looks/95

If you don't have access to Looker, reach out to @katedoebler

**Comment by andy-kimball** [comment]
CC @darinpp, who will be taking a look at this.

**Comment by andy-kimball** [comment]
@nvanbenschoten, @darinpp will reach out to you to get your ideas on how this should be done, since it seems you have something in mind.
