### ISSUE TITLE
cli/start: don't do hard shutdown on 2nd SIGTERM

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#48070]
Today we handle double SIGINT (Ctrl+C) and double SIGTERM the same way: the first initiates a soft shutdown, the second one initiates a hard shutdown.

For SIGINT, the UX is justified: the user is calling `start` interactively, and pressing Ctrl+C twice means "I know what I'm doing, go away faster".

Not so with SIGTERM. This is the signal sent by a process manager. Under normal operation, a process manager would issue
- SIGTERM first,
- wait for a bit
- issue SIGKILL if the process did not shut down on their own.

There is no need to give special meaning to a 2nd SIGTERM to be a hard shutdown. In fact, it's counter productive: if two operators concurrently (perhaps mistakenly) issue a shutdown order to their orchestration tool, we don't want the 2nd order to transform the 1st one in a hard shutdown which the 1st operator did not expect.

So the code should be changed to only handle a double SIGINT as hard shutdown, and ignore a 2nd SIGTERM (and perhaps SIGQUIT) once the graceful shutdown has been initiated.

**Comment by knz** [comment]
@bdarnell can you check my reasoning?

**Comment by bdarnell** [comment]
A process manager performing this sequence must be stateful (so it can remember to issue the SIGKILL at the end of the timeout), so it should know enough not to send a second SIGTERM. I don't feel strongly about it, but I would lean towards treating SIGTERM and SIGINT equivalently.

**Comment by knz** [comment]
The reason why this came up was your suggestion of node advertising `cockroach node drain` and instead recommending SIGTERM as the single and universal way to do graceful shutdown.

The reason why this does not sit well with me is that `node drain` provides visual feedback over the progress of the drain. I am afraid that a user would be tempted to send multiple SIGTERMs in a row if the first one does not appear to provide progress indicators in log, because "maybe it didn't work the first time".

**Comment by bdarnell** [comment]
If the user gets impatient and sends a second SIGTERM, isn't that an indication that they'd rather have the process go away now than shut down gracefully? It may be a little confusing that it takes two tries, but it doesn't seem that bad to me. It seems better than SIGTERM appearing to be ineffective even on repeated attempts. 

That said, if the status quo worked as you are suggesting here, I wouldn't be lobbying for a double SIGTERM to kill the process immediately, so I could go either way on this.

**Comment by knz** [comment]
Ok I'll let this sleep for a little bit to let thoughts percolate and sediment. then we'll see what we do.
