### ISSUE TITLE
ui: jobs/statements hover text is difficult to read

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#48075]
![Screen Shot 2020-04-27 at 5 20 31 PM](https://user-images.githubusercontent.com/6201335/80422070-7ca20700-88ab-11ea-8bcc-e28660b0b0d1.png)

The dark text color on a dark background makes the hover text difficult to read. This occurs both on the jobs page and the statements page. The above is using Chrome on Mac OS X from a recent master build.

**Comment by piyush-singh** [comment]
Yahor notedd this is also happening on the statements page. Seems to be an issue with our global styles for tooltips. Cc @Annebirzin not sure if this was a known issue tackled in our follow on work already.

**Comment by Annebirzin** [comment]
@piyush-singh this is not a known issue on my end and I don't think it was addressed in any of the follow up issues yet

**Comment by dhartunian** [comment]
#46626
