### ISSUE TITLE
Time labels in Admin UI not usable by IT Operations

### ISSUE THREAD

**Issue by a-entin** [cockroachdb/cockroach#48079]
Time labels in UI, as marked in the attached screenshot, don't provide information with meaningful granularity required by IT operations.  
![Screenshot](https://user-images.githubusercontent.com/55302400/80428617-44ed8c00-88b8-11ea-9973-64dff536196e.png)

Actual timestamps are needed to be able to investigate / act on operational issues.
This applies to events, jobs and metrics.

Further, need means to view events/jobs/metrics within a specified time window.
E.g. to be able to input a start date / time and end date / time and see metrics, events and jobs between the two.

In a real world example, an IT engineer had to identify jobs and events around 11:45 on Wed 3 days ago. Was trying to view information in the UI for the 10 minutes timespan, but 10 minutes 3 days ago. Could not use the Admin UI for the task.

**Environment:**
 - CockroachDB version [e.g. 19.1]
 - Server OS: RH7

Jira issue: CRDB-4359

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[5265](https://cockroachdb.zendesk.com/agent/tickets/5265) has been linked to this issue.
