### ISSUE TITLE
rocksDB options print in log is the initial value at the server start

### ISSUE THREAD

**Issue by heidawei** [cockroachdb/cockroach#48084]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:
I find the rocksDB options print in the cockroach-rocksdb.log is the initial value, not the real options value for rocksDB.

**To Reproduce**
./cockroach start --insecure --advertise-addr={host ip} --cache=0.05  --store=path={data path},rocksdb="block_based_table_factory={cache_index_and_filter_blocks=true;pin_l0_filter_and_index_blocks_in_cache=true}",attrs=ssd --background

I reset the some rocksDB options, but I see nothing changed in the log.

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
2. Send SQL ... / CLI command ...
3. Look at UI / log file / client app ...

**Expected behavior**

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version: V19.2.4
 - Server OS: Linux, MacOS
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
What was the impact?

**Comment by petermattis** [comment]
> I reset the some rocksDB options, but I see nothing changed in the log.

@heidawei Huh, that's strange. I see the options printed several times to `cockroach-rocksdb.log`, with the last set containing the changed options. Note that `cockroach-rocksdb.log` is output by RocksDB, so there isn't much we can do about its contents from CockroachDB. I personally never look at the options in that log file, but instead look at the `OPTIONS-*` file.

**Comment by heidawei** [comment]
Thank you very much.
