### ISSUE TITLE
A field in a structure is sometimes protected by Mutex, but sometimes unprotected.

### ISSUE THREAD

**Issue by BurtonQin** [cockroachdb/cockroach#48097]
**Describe the problem**

A field in a structure is sometimes protected by Mutex, but sometimes unprotected.
This may lead to data race.

`s.mu` is protected by the Mutex in itself in 21 cases, but there are two cases without protection.
- [ ] The field `qCancels` in `s.mu` is not protected by the Mutex in `s.mu`.
https://github.com/cockroachdb/cockroach/blob/8eb6a3f8cbe7af3e8160b1b256bab2ee50276865/pkg/util/stop/stopper.go#L224-L225
- [ ] The field `sCancels` in `s.mu` is not protected by the Mutex in `s.mu`.
https://github.com/cockroachdb/cockroach/blob/8eb6a3f8cbe7af3e8160b1b256bab2ee50276865/pkg/util/stop/stopper.go#L234-L235
I think this may lead to data race when `qCancels`/`sCancels` are changed by another thread before passing to `s.withCancel()`.

**Expected behavior**
Data race

**Environment:**
master branch, commit 8eb6a3f8cbe7af3e8160b1b256bab2ee50276865

**Comment by ajwerner** [comment]
All of the mutations to those maps happens under the mutex. The code is structured this way to avoid duplication. 

Can you provide an example of how this data race actually occurs?

**Comment by ajwerner** [comment]
I'm going to go out on a limb and suggest that static analysis revealed this. It didn't work in this case.
