### ISSUE TITLE
sql: add stddev_pop and var_pop aggregates

### ISSUE THREAD

**Issue by timgraham** [cockroachdb/cockroach#48103]
They are used by Django (https://github.com/cockroachdb/django-cockroachdb/issues/25).

https://github.com/cockroachdb/cockroach/issues/41274 is a similar issue for other aggregates that may help guide the implementation.

**Comment by xuhui-lu** [comment]
@rohany hey rohan, I am interested in working on this issue. Could I get the chance to be assigned with this issue? I just finished going through the architecture docs, and can start soon.

**Comment by rohany** [comment]
Hey @xuhui-lu, we don't "assign" issues to external contributors -- usually folks will just leave a comment on the issue saying they will take it on. Go ahead and work on it! You can tag me once you create a PR.

**Comment by yuzefovich** [comment]
Hey @rohany, I actually have been assigning easy issues to external contributors - I think this way it's easier to see that someone is actively working on the issue, and it doesn't show up in some of the searches.

**Comment by rohany** [comment]
Oh ok -- i wasn't sure we had a policy about doing this or not
