### ISSUE TITLE
sql: Add var_samp alias for variance aggregate builtin 

### ISSUE THREAD

**Issue by timgraham** [cockroachdb/cockroach#48101]
b5dd33fdbbf478a70bc60c27384be453edd3af91 (https://github.com/cockroachdb/cockroach/pull/46279) added stddev_samp alias for stddev. The same should be done for var_samp / variance.

(addresses part of https://github.com/cockroachdb/django-cockroachdb/issues/25)

**Comment by divbhasin** [comment]
New contributor here. I can take a stab at this, if that is okay.

**Comment by timgraham** [comment]
Sure, go ahead.
