### ISSUE TITLE
Support indexing more than one column with an inverted index

### ISSUE THREAD

**Issue by spaskob** [cockroachdb/cockroach#48100]
Currently we support only one column for creation of inverted index.

We could consider the multiple columns case to be one json object with multiple fields when creating the inverted index.

**Comment by mgartner** [comment]
We're currently working on multi-column inverted indexes. However, they require that all columns but the last are non-inverted types. For example, this is valid:

```sql
CREATE TABLE t (
  i INT,
  j JSON,
  INVERTED INDEX (i, j)
)
```

But this is not:

```sql
CREATE TABLE t (
  j1 JSON,
  j2 JSON,
  INVERTED INDEX (j1, j2)
)
```

I think it's unlikely we'd support this specific of an indexing option. However, with the addition of expression-based indexes and virtual columns (which are currently a work in progress), equivalent functionality should be possible. For example:

```sql
CREATE TABLE t (
  j1 JSON,
  j2 JSON,
  j3 JSON AS (j1 || j2) VIRTUAL,
  INVERTED INDEX (j3)
)
```

The advantage I see in this is that it makes no assumptions about how a user might want to combine two JSON columns. They could get very creative:

```sql
CREATE TABLE t (
  j1 JSON,
  j2 JSON,
  j3 JSON AS ((j1->'a' || j2) - 'b') VIRTUAL,
  INVERTED INDEX (j3)
)
```

I'm going to close this, assuming this alternative is suitable, but let me know if there are use-cases where this wouldn't work.
