### ISSUE TITLE
rowexec: improve disk spilling in the lookup joiner

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#48118]
The lookup joiner spills to disk if the results from a lookup take up more than the allowed work memory (default `64MiB`). Note that we reorder the lookup spans for the kv layer, so the results are received in a different order. However, since we want to preserve the ordering of the input, we use an `IndexedRowContainer` that allows the caller to `Get` a row based on its index in the row container and maintain a mapping from the index of the lookup rows to the list of index matches.

We then iterate over each lookup row in order and output its matches which results in random accesses and is very bad for performance. Tracing one of these cases shows that the `IndexedRowContainer` misses its cache a lot. @yuzefovich recommends turning off this cache and seeing how the performance changes. Another option is to add an extra column to the results that contain the index of the corresponding lookup row. The row container can be switched to a `SortableRowContainer` that maintains an ordering on this index column, so the emit stage uses sequential instead of random reads at the expense of having to maintain this ordering.

The nice thing is that in-memory cases would not be affected since the sorting is lazy so we could avoid calling `Sort` in this case and just do a linear pass to construct the output.

**Comment by sumeerbhola** [comment]
> Another option is to add an extra column to the results that contain the index of the corresponding lookup row. The row container can be switched to a SortableRowContainer that maintains an ordering on this index column, so the emit stage uses sequential instead of random reads at the expense of having to maintain this ordering.

I don't quite understand this: the row container is already maintaining things in order of the `lookedUpRow`. The problem seems to be that the slice corresponding to one `inputRowIdxToLookedUpRowIdx[inputRowIdx]` does not bear any relationship to the slice corresponding to `inputRowIdx+1`, so one may need to rewind the iterator (within each slide, the looked up row indexes are also increasing). When the output needs to be ordered, which is the only place this will be used in light of #48439, how can one do better? If each slice had a single lookedup row index and there was no duplication of these indexes, one could reorder these indexes -- e.g. something like
```
inputRowIdx      LookedUpRowIdx
0                          3
1                          1
2                          2
3                          0
```
could allow us to reorder the 3, 1, 2, 0 by reassigning the looked up row indexes, and making them 0, 1, 2, 3
But something like the following is harder. The looked up row 0 is needed by both input row 0 and 3.
```
inputRowIdx      LookedUpRowIdx
0                          0, 3
1                          1
2                          2, 3
3                          0, 1
```
Am I missing something?

**Comment by asubiotto** [comment]
> I don't quite understand this: the row container is already maintaining things in order of the lookedUpRow

Sorry, the terminology I used is confusing: when I wrote "lookup row" I meant "input row".

You're right about the index duplication... I hadn't thought hard about this. One option would be to "materialize" the looked up rows as many times as there are matches in the input side. So in your example:
```
inputRowIdx      LookedUpRowIdx
0                          0, 3
1                          1
2                          2, 3
3                          0, 1
```
Would become:
```
inputRowIdx      LookedUpRowIdx
0                          0, 3
                            0, 1
1                          1
                            0, 1
2                          2, 3
3                          0, 3
                            2, 3
```
Where a looked up row idx pair uniquely describes a looked up row but multiple ocurrences have the associated `inputRowIdx` in a column, making it unique. The ordering would be on an `inputrowIdx` added to the looked up row. The performance implications are less clear here though.

**Comment by asubiotto** [comment]
@sumeerbhola I assume you're planning on updating the `joinReader` to use the `DiskBackedNumberedRowContainer`. I think that we can close this issue once that's done.

**Comment by sumeerbhola** [comment]
Yes, I'll make some changes to the `joinReader` benchmark and then integrate.
