### ISSUE TITLE
sql/kv: hide tenant ID from user of multi-tenant cluster

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#48119]
As a general rule to avoid breaking the desired multitenancy abstraction, tenant IDs should not be exposed to non-system tenants. Specifically, a tenant should not be able to determine its own tenant ID.

To start, this means that we should not expose SQL builtins to introspect a tenant's ID.

However, there are also areas where this rule has more subtle implications. For instance, https://github.com/cockroachdb/cockroach/pull/47999 introduces a tenant ID into the KV keyspace. Each tenant in a multi-tenant cluster is nested under its tenant ID's key prefix. To avoid leaking the tenant ID to tenant SQL instances, we'll need to avoid printing keys with their tenant prefix.

We should be aware of this principle as we work on multi-tenancy. Note that this is not a security concern, so ensuring this property is not a hard blocker. Instead, it should be viewed as a UX concern.

Jira issue: CRDB-4357

**Comment by knz** [comment]
With the benefit of hindsight, it appears that this concern needs less attention than we thought back then.

While tenant IDs are not fully hidden from the tenants themselves (they show e.g. in traces, contention events, range lists and can pop up in error messages), we've been generally disciplined at not exposing tenant IDs as part of the semantics of the SQL UX presented to clients.

So we're going to close this for now. If there's a more specific UX concern we need to work on, we can open an issue for that when the time comes.
