### ISSUE TITLE
ui: events panel and node list terminology are inconsistent on node decommissioning

### ISSUE THREAD

**Issue by taroface** [cockroachdb/cockroach#48129]
**Describe the problem**

While decommissioning nodes, the Node List and `cockroach node status --decommission` show the nodes (4 and 5) to be decommissioning (`is_decommissioning=true`). 

<img width="1322" alt="Screen Shot 2020-04-28 at 5 00 58 PM" src="https://user-images.githubusercontent.com/8740013/80537619-5abf8780-8972-11ea-94a0-507820f60ca9.png">

```
Ryans-MBP:logs ryankuo$ cockroach node status --decommission --insecure --host=localhost:26260
  id |     address     |   sql_address   |             build              |            started_at            |            updated_at            | locality | is_available | is_live | gossiped_replicas | is_decommissioning | is_draining
-----+-----------------+-----------------+--------------------------------+----------------------------------+----------------------------------+----------+--------------+---------+-------------------+--------------------+--------------
   1 | localhost:26257 | localhost:26257 | v20.1.0-beta.4-589-g3967538f10 | 2020-04-28 19:53:08.582937+00:00 | 2020-04-28 20:59:58.1827+00:00   |          | true         | true    |                62 | false              | false
   2 | localhost:26258 | localhost:26258 | v20.1.0-beta.4-589-g3967538f10 | 2020-04-28 19:53:19.324723+00:00 | 2020-04-28 20:59:55.397989+00:00 |          | true         | true    |                62 | false              | false
   3 | localhost:26259 | localhost:26259 | v20.1.0-beta.4-589-g3967538f10 | 2020-04-28 19:53:22.847294+00:00 | 2020-04-28 20:59:54.407677+00:00 |          | true         | true    |                62 | false              | false
   4 | localhost:26260 | localhost:26260 | v20.1.0-beta.4-589-g3967538f10 | 2020-04-28 19:55:17.276025+00:00 | 2020-04-28 20:59:56.307582+00:00 |          | true         | true    |                 0 | true               | false
   5 | localhost:26261 | localhost:26261 | v20.1.0-beta.4-589-g3967538f10 | 2020-04-28 20:52:32.298294+00:00 | 2020-04-28 20:59:57.81616+00:00  |          | true         | true    |                 0 | true               | false
(5 rows)
```

At the same time, the Events panel on the Metrics page states that each node "was decommissioned".

However, the node status displayed in the Cluster Overview is not yet `DECOMMISSIONED` and the node is not showing in the Recently Decommissioned list. This should happen when I run `cockroach quit` to stop the node.

<img width="333" alt="Screen Shot 2020-04-28 at 5 00 51 PM" src="https://user-images.githubusercontent.com/8740013/80537640-6317c280-8972-11ea-9a41-553dbda5f6ab.png">

It seems there is a difference of "decommissioning/decommissioned" semantics between the events log and node status. 

- The Node List considers the node "decommissioning" when `cockroach node decommission` is run, and "decommissioned" when `cockroach quit` is run. 
- The Events panel considers the node to be "decommissioned" as soon as `cockroach node decommission` is either run or successfully completes. It possibly has no concept of "decommissioning"?

**To Reproduce**

1. Set up local insecure CockroachDB cluster with 4 nodes.
2. Use `cockroach node decommission` to decommission node 4.
3. Wait for Node 4 decommissioning to complete (`is_decommissioning`=true and `replicas=0`).
4. Check Events panel on Metrics page.

**Expected behavior**

Either:

- Events panel indicates that nodes are still actively (?) "decommissioning" and not imply that decommissioning is complete.
- Node List status changes from "decommissioning" to "decommissioned" once `replicas=0` on the node. (While node still hasn't been moved to "Recently decommissioned" list - this is potentially confusing).
- Some other terminology change.

**Environment:**
 - CockroachDB version V20.1.0-BETA.4-589-G3967538F10

Jira issue: CRDB-4355

**Comment by irfansharif** [comment]
The noted discrepancy between the output of `cockroach node status`/the event log and the cluster overview page is indeed a real one. @piyush-singh, this would be another thing that would be made less confusing with #50707.
