### ISSUE TITLE
UI: Non-admin users will see 500s and loading states on Databases and Events

### ISSUE THREAD

**Issue by chrisseto** [cockroachdb/cockroach#48152]
**Describe the problem**

When visiting the "Databases" and "Events" pages of the admin UI as a user that is not part of the admin role they appear broken. 

**To Reproduce**

1. Set up secure CockroachDB cluster
2. Create a normal user `CREATE USER blah WITH PASSWORD ...`
3. Log into the Admin UI as the created user
4. Navigate to either the "Databases" or "Events" page
5. See error

**Expected behavior**
I would expect to see a banner stating that my user does not have access to the requested data.
I would also expect to see 403 responses rather than 500s.
![Screen Shot 2020-04-29 at 9 30 17 AM](https://user-images.githubusercontent.com/5532905/80602024-9bfc7980-89fc-11ea-988e-6628c8333b62.png)

**Additional data / screenshots**
The events page returns a 500.
<img width="1142" alt="Screen Shot 2020-04-29 at 9 16 08 AM" src="https://user-images.githubusercontent.com/5532905/80602006-94d56b80-89fc-11ea-8245-88d8f49bbda2.png">
The Databases page correctly returns a 403 but does not handle it.
<img width="1314" alt="Screen Shot 2020-04-29 at 9 15 28 AM" src="https://user-images.githubusercontent.com/5532905/80602018-9868f280-89fc-11ea-8960-9d549b6a3e73.png">

**Environment:**
 - CockroachDB version 19.2.x, V20.1.0-RC.2

**Additional context**
While debugging issues with a production cluster I noticed certain pages of the admin UI where not loading and 500s coming back from the server.
This lead me to believe that something was extremely wrong.
Another SRE was unable to reproduce the problem with an admin user which led us to the conclusion that non-admin users may be problematic.
Nothing is particularly dangerous but it is quite the red herring if a cluster is already misbehaving.

**Comment by piyush-singh** [comment]
We should definitely change these over to 403 errors, we did a sweep of pages in the past, but looks like we missed a few. This should be backported to 19.1.x and 19.2.x when we pick this up.

Open question on how best to handle these errors on the page - probably a question for @dhartunian.

**Comment by piyush-singh** [comment]
This is also happening on the node map. See #50360

**Comment by piyush-singh** [comment]
As @florence-crl mentioned from a customer issue, this is also happening on the data distribution page.

**Comment by Annebirzin** [comment]
@piyush-singh @dhartunian adding figma link for [permission states](https://www.figma.com/file/wLjM816v8wwesuIDkar9oN/obsrv_admin-ui-permissions?node-id=1%3A10) in the Admin UI. (Below is a screenshot for the data distribution and events)

![DataDistribution_001](https://user-images.githubusercontent.com/51920721/86150977-211f1000-bacc-11ea-97d7-1ec352f302ad.png)
![Events_001](https://user-images.githubusercontent.com/51920721/86150979-211f1000-bacc-11ea-8d18-965891f595c1.png)

**Comment by koorosh** [comment]
@Annebirzin , thanks for the provided designs! Want to clarify a general question about error messages on forms. Currently, we don't distinguish if it's permission error or something else when rendering them on the page. It is used the same template for messages across the entire app. 
What do you think of reusing new provided design for all kinds of errors, not only permissions?

For example, we might receive an error on failed request like this:
<img width="1207" alt="Screenshot 2020-07-01 at 17 03 01" src="https://user-images.githubusercontent.com/3106437/86255925-66246e80-bbc0-11ea-9b48-9e52fabd8238.png">

**Comment by Annebirzin** [comment]
@koorosh, would it be possible to make the error messages red (for failure) and the permission messages blue (for informative)? Reasoning here is that the permission message might be an expected behavior that the user defined, while the other errors are not expected.

Not sure if it's possible but the multiple error messages could look like this:
![Screen Shot 2020-07-01 at 12 13 08 PM](https://user-images.githubusercontent.com/51920721/86267232-673fa680-bb94-11ea-8735-b1c973634e66.png)

If there are permission issues _and_ errors it could look like this:
![Screen Shot 2020-07-01 at 12 13 43 PM](https://user-images.githubusercontent.com/51920721/86267290-79214980-bb94-11ea-923e-d14a4778b0b7.png)

**Comment by koorosh** [comment]
@Annebirzin , it really makes sense to have info and error messages with different colors! 
Thank you for your suggestion!
