### ISSUE TITLE
storage: TestRestoreReplicas sometimes panics with: "gossip infostore's NodeID is 0"

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#4815]
Example failed build: https://circleci.com/gh/cockroachdb/cockroach/13696

Easy to reproduce locally with `make stressrace PKG=./storage` - 20% failures. Tried at a hash from a few days ago and the failure is there too.

**Comment by tamird** [comment]
Which tests fail specifically? This is a misuse of gossip's SetNodeID that
was turned into a panic in 0866ceb0.

**Comment by andreimatei** [comment]
Unclear which test inside that package, cause with the new Go you just get
a stack trace from the goroutine that panics. I'm not sure why the log
doesn't have "=== RUN <test name>" lines for the tests before the panic.

**Comment by tamird** [comment]
You can set GOTRACEBACK to change the stack trace printing behaviour.

**Comment by spencerkimball** [comment]
Is this still failing after Ben's fixes in #4926?

**Comment by vivekmenezes** [comment]
Im pretty sure I saw this once yesterday

**Comment by tamird** [comment]
My guess is that this is good to close.

**Comment by bdarnell** [comment]
#4926 should fix it, but that PR isn't merged yet and I'm still working on some test failures there.
