### ISSUE TITLE
kv: adding more hints to "result is amiguous" (SQLSTATE 40003) error message

### ISSUE THREAD

**Issue by ricardocrdb** [cockroachdb/cockroach#48168]
When running an example TPCC workload, we ran into the follow message.
`Error: error in payment: ERROR: result is ambiguous (error=rpc error: code = Unavailable desc = transport is closing [propagate]) (SQLSTATE 40003)`

While the ambiguous error is understood to be a possible outcome of distributed systems, the information around what caused the error itself could be expanded further, given the scenario of an environmental factor at play (network drop, timouts, etc).

Jira issue: CRDB-4351

**Comment by ricardocrdb** [comment]
cc @andreimatei @darinpp

**Comment by lunevalex** [comment]
Comment from @andreimatei, we could in theory include some information about which nodes failed to communicate with each other.
