### ISSUE TITLE
Code-sign and notarize darwin binaries in our build pipeline

### ISSUE THREAD

**Issue by jlinder** [cockroachdb/cockroach#48169]
See [this slack thread](https://cockroachlabs.slack.com/archives/C0HM2DZ34/p1587654992403000) for background.

![image](https://user-images.githubusercontent.com/21692034/80137989-24e56200-8572-11ea-8499-28123077039f.png)

MacOS Catalina now requires binaries to be signed and notarized to avoid requiring users to go the their preferences to allow the binary to execute. We'll need to investigate what is required to avoid this less than ideal first time user experience. David mentioned that:
> I believe we need to add mac build agents to our pipeline to run the signing and notarizing steps for darwin binaries. Hashicorp’s ceo wrote a little tool to automate most of the actual steps.

cc @aaron-crl

[related docs issue](https://github.com/cockroachdb/docs/issues/6380)

Epic DEVINF-247

**Comment by jlinder** [comment]
See https://github.com/cockroachdb/dev-inf/issues/87 for the original issue.

**Comment by jseldess** [comment]
@jlinder, is this still a need? When I download the macOS binary for 20.2, I no longer get this message...

**Comment by jlinder** [comment]
Yes. It's likely that you have "Anywhere" selected in System Preferences. By default, "App store and identified developers" is selected.

<img width="672" alt="Screen Shot 2020-11-22 at 10 15 43 PM" src="https://user-images.githubusercontent.com/224132/99926832-06666580-2d11-11eb-9b5c-7fb4dbea3525.png">

**Comment by jseldess** [comment]
Ah, right. Do we have any updated plans to get the macOS binary notarized? If not, we should probably have a tip in our docs.

**Comment by jlinder** [comment]
We should definitely have a tip in the docs. This is currently in the dev inf + release engineering team backlogs, but it's not in any of our planned work.

This fell off the radar back in August or September. We were working on getting some local machines for building binaries. I think there was strong discouragement on that approach from @richd-cockroachlabs and encouragement to find a cloud hosted solution, though I'm not certain. 

cc @kenliu @dt

**Comment by bdarnell** [comment]
For whenever we're ready to pick this back up, we have a macstadium account now that we could use for signing.

**Comment by rail** [comment]
This is done for the ARM platform. We decided to postpone signing of the Intel binaries, because it creates more headaches, similar to https://github.com/cockroachdb/cockroach/issues/91573. I'm going to file another issue to address Intel signing.
