### ISSUE TITLE
DROP COLUMN unknown column

### ISSUE THREAD

**Issue by spaskob** [cockroachdb/cockroach#48176]
The bug was discovered running the `schemachange` workload
```
bin/workload run schemachange --init --concurrency=50 --max-ops=1000 --verbose=1
```
Note that it may take a few runs to recreate it. Here is the actual txn that produced the error

```
BEGIN
  CREATE VIEW "view4187" AS SELECT rowid FROM "table2058";
  ALTER TABLE "table1635" DROP COLUMN "col1636_0";
ROLLBACK;
ALTER TABLE "table1635" DROP COLUMN "col1636_0" failed: ERROR: index "table1635_col1636_0_key" contains unknown column "col1636_0" (SQLSTATE XXUUU)
```

Full schema change ops are attached.
[sc-ops.zip](https://github.com/cockroachdb/cockroach/files/4554155/sc-ops.zip)

[crdb-logs.zip](https://github.com/cockroachdb/cockroach/files/4554598/crdb-logs.zip)

**Comment by ajwerner** [comment]
whatever this is, it no longer exists, closing.
