### ISSUE TITLE
opt: tuple star expansion is incorrect for unnamed tuples

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#48179]
The following two queries are equivalent except for the fact that the first one involves unnamed tuple elements, while the second one has named elements. However, the plans are different:
```
root@127.0.0.1:50033/movr> explain (opt) select (b).* from (values (((1, 2)))) as a(b);
           text
--------------------------
  project
   ├── values
   │    └── ((1, 2),)
   └── projections
        └── (column1).@1
(5 rows)

root@127.0.0.1:50033/movr> explain (opt) select (b).* from (values (((1, 2) as x,y))) as a(b);
              text
---------------------------------
  project
   ├── values
   │    └── (((1, 2) AS x, y),)
   └── projections
        ├── (column1).x
        └── (column1).y
(6 rows)
```
Notice that the first plan only projects the first element of the tuple, not the second. As a result, executing that plan produces the following erroneous output:
```
root@127.0.0.1:50033/movr>  select (b).* from (values (((1, 2)))) as a(b);
  ?column? | ?column?
-----------+-----------
         1 |        1
(1 row)
```
The second plan with named tuple elements works as expected:
```
root@127.0.0.1:50033/movr> select (b).* from (values (((1, 2) as x,y))) as a(b);
  x | y
----+----
  1 | 2
(1 row)
```

**Comment by DrewKimball** [comment]
Changing line 88 in pkg/sql/opt/optbuilder/util.go from this:
```
aliases = append(aliases, "?column?")
```
to this:
```
aliases = append(aliases, fmt.Sprintf("%s.@%d", "?column?", i+1))
```
seems to fix the issue. The problem is that when a tuple has no labels, every tuple field is assigned the same alias. All the new ColumnAccess expressions end up pointing to the first tuple field.

**Comment by rytaft** [comment]
Nice find! But looking closer here I think the problem is that `NewTypedColumnAccessExpr` expects `colName` to be empty when there is no name and it should be accessed by index.  So I think we might actually want to move the line `aliases = append(aliases, "?column?")` down below the call to `NewTypedColumnAccessExpr`. Feel free to submit a PR to fix it or I can get to it tomorrow. Thanks!

**Comment by rytaft** [comment]
@DrewKimball I went ahead an opened a PR since I'm not sure I described the fix very well. Thanks for helping debug this!
