### ISSUE TITLE
sql: references to SystemConfigSpan should be prefixed by tenant ID

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#48184]
Each tenant will have its own system config span.

It's possible that https://github.com/cockroachdb/cockroach/issues/47150 will remove the uses of the SystemConfigSpan entirely.

**Comment by tbg** [comment]
Is there much work expected with this issue? Does it rise to blocker status?

**Comment by tbg** [comment]
Easy fix: when tenants EndTransaction with a trigger, don't run the trigger. (Need this for security anyway)
