### ISSUE TITLE
acceptance: mock clock offsets, test node death

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4818]
shouldn't be too hard. We'll have to mock `time.Now()` but then we're in full control.
Mucking with clocks manually isn't a thing on Docker.

**Comment by knz** [comment]
There's this library https://github.com/wolfcw/libfaketime used by Jepsen. It intercepts the syscall to fake a different time. Perhaps we can use that?

**Comment by tschottdorf** [comment]
I was thinking of going the simpler route, which is not using `time.Now()`
but enforcing use of a mockable substitute throughout the code base. Easy
to lint for, and works out-of-the box.

**Comment by tschottdorf** [comment]
Afterthought: not quite that trivial since we need to activate this for a running Docker container, but I think still the most viable alternative. Easy enough to add a way for that behind a build tag. We'll see when this becomes current.

**Comment by petermattis** [comment]
Does `libfaketime` work on Go binaries? AFAICT, it is intercepting libc calls, not system calls.

**Comment by tamird** [comment]
A facility for this was added in #5019. Reassigning to @tschottdorf

**Comment by tschottdorf** [comment]
Not working on this at the moment, unassigning.

**Comment by spencerkimball** [comment]
@tamird we are unittesting this now with #5512? I'm removing 1.0 milestone. Could you close this issue if it's no longer something we need to track?

**Comment by tamird** [comment]
This issue is about testing "real" node death in an acceptance scenario. You could say this is covered by jepsen, so I think it's OK to close this.
