### ISSUE TITLE
sql: rename on temporary table promotes it to a persistent table

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#48233]
To repro, create a temporary table, and then rename it. Then, look into system.namespace, and you'll see that the namespace entry for the table has been changed to be moved into the public schema.

A side effect of this is that name collisions between two temporary tables in rename are not detected correctly.

**Comment by jordanlewis** [comment]
Ha... nice find. Do we need to support temp table renames?

**Comment by rohany** [comment]
I'm not sure -- i think renaming lets you move a table around between databases and schemas, which seems like something that we don't want to allow with temporary tables.
