### ISSUE TITLE
server: don't signal readiness before settings are initialized

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#48273]
Discussed in #48005 by @tbg

> The settings are not persisted on the node, so we're always running with the default settings for a little bit of time even after signaling readiness.

> Something we could do here is to wait until a system config has been ingested before returning from `.Start` (in the non-init case). But we're also phasing out this use of Gossip, so this will rot quickly, and the new system will use higher-level primitives. For now, seems best to add a retry or sleep to the test.

Jira issue: CRDB-4341

**Comment by knz** [comment]
Continuing the discussion from https://github.com/cockroachdb/cockroach/issues/49652#issuecomment-639497614

@tbg  is there a guarantee that a gossip update for settings contains a value for *all* settings?

**Comment by tbg** [comment]
Yes, I think so. This comes from the system config which is always gossiped as a single blob.

**Comment by knz** [comment]
we have fixed this.
