### ISSUE TITLE
cdc: support multi-tenancy

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#48274]
We're disabling this in Phase 2 (#48008), mostly due to the DistSQL dependency. Eventually, we may want to allow tenants to run change feeds. We will need to control which external endpoints these feeds can be pointed at.

Epic CRDB-2608

Jira issue: CRDB-4340

**Comment by miretskiy** [comment]
@amruss  -- not sure what the current state is.
I thought we do allow tenants to run changefeeds; though I'm pretty sure we don't
require external connection endpoints (yet).
I assume this issue should stay open? If not, and the remaining work is being
tracked elsewhere, can you please close this issue?
