### ISSUE TITLE
opt: allow hinting lookup joins for FK checks

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#48281]
There are cases when doing anything other than a lookup join for FK checks is a bad idea. There is no way for a user to hint a lookup join for the foreign key checks. One example that recently came up is described in #48280. Other cases are where we want to avoid contention with updates for unrelated rows.

Some ideas of how we could do this:
 - a setting that adds a big cost penalty for a full scan in any FK check query
 - a per-table scan penalty which increases the per-row scan cost of a given table by a factor. This is a more generally useful approach, but there are practical difficulties around implementing it.

**Comment by awoods187** [comment]
Will this be potentially mitigated with the improved lookup join performance/recosting of lookup join with improved performance that @asubiotto is working on?

I assume that the settings above could have some FK check's that are slower by forcing lookup joins for all checks?

**Comment by RaduBerinde** [comment]
> Will this be potentially mitigated with the improved lookup join performance/recosting of lookup join with improved performance that @asubiotto is working on?

Not in all cases, I don't think it would have helped for #48286 

> I assume that the settings above could have some FK check's that are slower by forcing lookup joins for all checks?

Correct (though note that this is what 19.2 does all the time).

**Comment by RaduBerinde** [comment]
Spanner has a `@{hint} <query>` syntax for query hints. If we supported that kind of syntax, we could have an option to force lookup joins for FKs.

**Comment by RaduBerinde** [comment]
A session and cluster setting has been added in #53838.
