### ISSUE TITLE
acceptance: Test more language versions

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#48293]
We have discovered an incompatibility between CockroachDB 20.1 and many versions of Java (including versions of Java 11 and 13 from before April 2020): https://github.com/cockroachdb/docs/issues/7258. We didn't discover this until very late because our internal acceptance testing [uses Java 8](https://github.com/cockroachdb/cockroach/blob/18b429c934266809ab9eb8142b3c7851e21760b0/pkg/acceptance/testdata/Dockerfile#L42). (Java 8 and 11 are the current LTS releases; 13 and 14 are the current supported non-LTS releases). 

We should expand our test coverage to cover more versions of environments we support. It had seemed unlikely that this would matter, but we now have evidence that it does. 

The specific issue in this case was the fact that CockroachDB 20.1 is the first release to use TLS 1.3 by default (thanks to an upgraded version of Go since 19.2). It's probably too late to do this before the 20.1 release, but we should ensure that we test a version of each supported language that uses TLS 1.3. 

Jira issue: CRDB-4337

**Comment by bdarnell** [comment]
See also https://github.com/cockroachdb/cockroach/issues/17244, about another gap in our acceptance test coverage of TLS features.

**Comment by rafiss** [comment]
Just commenting to say that our nightly ORM testing is also using java 8 right now (and in general, each test is fixed to one specific language version). For example:
https://github.com/cockroachdb/cockroach/blob/63a60d3ee06e136b6c0d7abd7a1863a8a8f38061/pkg/cmd/roachtest/hibernate.go#L65-L73

And same for Examples-ORMs, which is run in CI:
https://github.com/cockroachdb/examples-orms/blob/77a49de55de870129d928430f3a2649e45c46266/Dockerfile#L1

(Perhaps we should file separate issues for these?)
