### ISSUE TITLE
release: latest tag for cockroachdb/cockroach-unstable points to old version

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#48309]
https://hub.docker.com/r/cockroachdb/cockroach-unstable/tags

Currently the `latest` tag points to the `v19.2.4-gctwooff` image. As of the time of writing this, it should actually be pointing to the `v20.1.0-rc.2` image.

**Comment by rafiss** [comment]
It seems like the issue must be related to how the "Bless provisional artifacts" job works. 

```
image=docker.io/cockroachdb/cockroach-unstable
if [[ "$release_version" != *-* ]]; then
  image=docker.io/cockroachdb/cockroach
fi

cp cockroach build/deploy/cockroach
docker build --no-cache --tag=$image:{latest,"$release_version"} build/deploy

# Only push the "latest" tag for our most recent release branch.
# We assume that VERSION_TO_TAG_AS_LATEST looks like "19.2", and then
# perform a glob match.
# https://github.com/cockroachdb/cockroach/issues/41067
if [[ "$release_version" == v$VERSION_TO_TAG_AS_LATEST.* ]]; then
  docker push "$image:latest"
fi
docker push "$image:$release_version"
```

https://teamcity.cockroachdb.com/admin/editRunType.html?id=buildType:Cockroach_BlessProvisionalArtifacts&runnerId=RUNNER_53&cameFromUrl=%2Fadmin%2FeditBuildRunners.html%3Fid%3DbuildType%253ACockroach_BlessProvisionalArtifacts%26init%3D1&cameFromTitle=

**Comment by otan** [comment]
it looks like we should change the env variable to 20.1 for unstable to be pushed correctly.

also smells like we may want `latest` to point to stables as well, when 20.1 is out, i.e. change the build script to:
```
cp cockroach build/deploy/cockroach
docker build --no-cache --tag=docker.io/cockroachdb/cockroach-unstable:{latest,"$release_version"} build/deploy
if [[ "$release_version" != *-* ]]; then
   docker build --no-cache --tag=docker.io/cockroachdb/cockroach:{latest,"$release_version"} build/deploy
fi
```

**Comment by rafiss** [comment]
Is the issue with that part, or with the `docker push` commands?

This could relate to this other idea too: https://github.com/cockroachdb/dev-inf/issues/41

**Comment by jlinder** [comment]
🎉
