### ISSUE TITLE
[bug: v20.1.0-rc.2] diagnostics sql reporting statistics max interval misleading or wrongly calculated

### ISSUE THREAD

**Issue by onno-vos-dev** [cockroachdb/cockroach#48337]
**Describe the problem**
`diagnostics.forced_sql_stat_reset.interval` and `diagnostics.sql_stat_reset.interval` are supposed to have a max value of `24h` however setting `24h` results in: `cannot set diagnostics.forced_sql_stat_reset.interval to a value larger than24h0m0s`. 

```shell
root@***:26257/defaultdb> set cluster setting diagnostics.forced_sql_stat_reset.interval  to '24h';
ERROR: cannot set diagnostics.forced_sql_stat_reset.interval to a value larger than 24h0m0s

root@***:26257/defaultdb> set cluster setting diagnostics.sql_stat_reset.interval to '24h';
ERROR: cannot set diagnostics.sql_stat_reset.interval to a value larger than 24h0m0s
```

**To Reproduce**
Start cockroach and try and set the above value to `24h`

**Expected behavior**
I'd argue that `24h` falls within the value of `24h0m0s`. If the intention is to be a max value of `23h59m59s` than the documentation should reflect this instead.

**Environment:**
```
Build Tag:    v20.1.0-rc.2
Build Time:   2020/04/17 19:22:16
Distribution: CCL
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.13.9
C Compiler:   gcc 6.3.0
Build SHA-1:  c0f00d2a156295a1cb79ed960940c167cb03ccbc
Build Type:   release
```

**Comment by otan** [comment]
Apologies, I have a fix out.
