### ISSUE TITLE
sql: add estimated rows scanned to EXPLAIN

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#48420]
Similar to https://github.com/cockroachdb/cockroach/issues/34723, we should add estimated rows scanned to Explain by promoting it up and out of EXPLAIN (OPT, VERBOSE). This is a key piece of information needed for query debugging. 

Current explain:
![image](https://user-images.githubusercontent.com/22278911/81031666-ffeacc00-8e5a-11ea-9c51-1fd1621c70c3.png)

EXPLAIN (OPT, VERBOSE)
![image](https://user-images.githubusercontent.com/22278911/81031697-198c1380-8e5b-11ea-89fa-752c2aadd8fe.png)

**Comment by awoods187** [comment]
It would also be great to denote estimated % of total rows that will be scanned

**Comment by awoods187** [comment]
The first part of this is done. @RaduBerinde what do you think about adding the % of total rows to be scanned? i could also close this and open a separate issue

**Comment by RaduBerinde** [comment]
Can you expand on this metric? Is it % of the total rows estimated to be scanned by the entire query? So if we have a join and we do two scans, we'd have e.g. 40% and 60%? How would we represent this in the output so that it's clear what it is?

**Comment by awoods187** [comment]
I was actually thinking it would be estimated rows scanned per operator/estimate rows in that table rather than the % of rows for the total query done per operator.  We could ask @Annebirzin  but I was thinking something like this:
```SQL
root@127.0.0.1:26257/movr> explain SELECT
    name, count(rides.id) AS sum
FROM
    users JOIN rides ON users.id = rides.rider_id
WHERE
    rides.start_time BETWEEN '2018-12-31 00:00:00' AND '2020-01-01 00:00:00'
GROUP BY
    name
ORDER BY
    sum DESC
LIMIT
    10;
                                                    info
-------------------------------------------------------------------------------------------------------------
  distribution: full
  vectorized: true

  • limit
  │ count: 10
  │
  └── • sort
      │ order: -count_rows
      │
      └── • group
          │ group by: name
          │
          └── • hash join
              │ equality: (id) = (rider_id)
              │
              ├── • scan
              │     estimated row count: 50 (5% of users rows) 
              │     table: users@primary
              │     spans: FULL SCAN
              │
              └── • filter
                  │ filter: (start_time >= '2018-12-31 00:00:00') AND (start_time <= '2020-01-01 00:00:00')
                  │
                  └── • scan
                        estimated row count: 500 (30% of rides rows)
                        table: rides@primary
                        spans: FULL SCAN
(27 rows)

Time: 2ms total (execution 1ms / network 0ms)

```

**Comment by RaduBerinde** [comment]
Oh, that makes more sense. It will be a bit hacky but it can be done.
