### ISSUE TITLE
ui: downsampling does not happen when sticky large time range is selected

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#48445]
**Describe the problem**

Similar to https://github.com/cockroachdb/cockroach/issues/44836. In the existing date-picker you can select a large time range. This large time range ends up being sticky, even when it is no longer in the URL (say because you click from the charts, back to overview, and then into charts again). When that happens, you will still have the long time interval, but there won't be any down-sampling.

I also see it when I just zoom out sometimes. I am not sure the source of the bug but it makes the charts pretty unusable. It also seems like even when it downsamples, it's pulling the other data too? 

**To Reproduce**

Just zoom out and then try using the admin UI.

**Expected behavior**
It is fast and downsamples appropriately. 

**Additional data / screenshots**

I have a screencast. Please ask. 

**Environment:**
 - CockroachDB version b8ecf62deb88da45a344912f721b0609b5df2187
 - Linux

Jira issue: CRDB-4322

**Comment by elkmaster** [comment]
@ajwerner, hi! could you provide screencast?

**Comment by dhartunian** [comment]
@ajwerner how long of a time period were you looking at? We're looking at good ways to generate test data for the time series so we can fix issues like this and I want to know how much to generate.

**Comment by ajwerner** [comment]
I was looking back at least 24 hours but generally 48h. I feel like we need to go back to a world where there’s a cluster that is long-running and always has the nightly.
