### ISSUE TITLE
make fail due to generated file `bindata.go` missing import clause

### ISSUE THREAD

**Issue by lysu** [cockroachdb/cockroach#48469]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. `git checkout master`
2. `make` to build 
3. see build failure

```
# github.com/cockroachdb/cockroach/pkg/ui/distccl
pkg/ui/distccl/bindata.go:1088:15: undefined: ui
```

**Expected behavior**

it seems generated file `bindata.go` miss import "github.com/cockroachdb/cockroach/pkg/ui"

add `import "github.com/cockroachdb/cockroach/pkg/ui"` then it can works

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version - current master (2020.05.06)
 - Server OS: Manjaro 20.0 Lysia / x86_64 Linux 5.6.8-1-MANJARO
 - Client app: n/a just build problem

**Additional context**
What was the impact?

new user need add an import to compile success everytime

Jira issue: CRDB-4319

**Comment by knz** [comment]
@dhartunian I think this one is for you?

**Comment by stevendanna** [comment]
I'm going to close this one out given the age and the large number of changes to the build system since it was reported.
