### ISSUE TITLE
pkg/util: conflicting lock order between stop and clog

### ISSUE THREAD

**Issue by BurtonQin** [cockroachdb/cockroach#48470]
**Describe the problem**

Similar to #48447.
A conflicting lock order happens between `Stopper.mu.Lock()`  in pkg/util/stop/stopper.go and `loggerT.mu.Lock()` in pkg/util/log/clog.go, which may lead to deadlock.
`Stopper.mu.Lock()`:
https://github.com/cockroachdb/cockroach/blob/cb60e7536f81c0c3eae854e4774c66a01a4f691c/pkg/util/stop/stopper.go#L114-L115
`loggerT.mu.Lock()`:
https://github.com/cockroachdb/cockroach/blob/cb60e7536f81c0c3eae854e4774c66a01a4f691c/pkg/util/log/clog.go#L57-L58

1. **`Stopper.mu.Lock()` -> `loggerT.mu.Lock()`**
`Stopper.mu.Lock()`, `log.Infof()`:
https://github.com/cockroachdb/cockroach/blob/683f0d561bf9b73902edb27d681bca5333bdad60/pkg/util/stop/stopper.go#L531-L539
`log.Depth()`:
https://github.com/cockroachdb/cockroach/blob/cb60e7536f81c0c3eae854e4774c66a01a4f691c/pkg/util/log/log.go#L74-L76
`addStructured()`:
https://github.com/cockroachdb/cockroach/blob/cb60e7536f81c0c3eae854e4774c66a01a4f691c/pkg/util/log/log.go#L42-L45
`mainLog.outputLogEntry`:
https://github.com/cockroachdb/cockroach/blob/cb60e7536f81c0c3eae854e4774c66a01a4f691c/pkg/util/log/structured.go#L66
`loggerT.mu.Lock()`:
https://github.com/cockroachdb/cockroach/blob/cb60e7536f81c0c3eae854e4774c66a01a4f691c/pkg/util/log/clog.go#L201

2. **`loggerT.mu.Lock()` -> `Stopper.mu.Lock()`**
`loggerT.mu.Lock()` in `outputLogEntry()`:
https://github.com/cockroachdb/cockroach/blob/cb60e7536f81c0c3eae854e4774c66a01a4f691c/pkg/util/log/clog.go#L201
`l.outputToStderr()`:
https://github.com/cockroachdb/cockroach/blob/cb60e7536f81c0c3eae854e4774c66a01a4f691c/pkg/util/log/clog.go#L265-L275
`l.exitLocked()`:
https://github.com/cockroachdb/cockroach/blob/cb60e7536f81c0c3eae854e4774c66a01a4f691c/pkg/util/log/clog.go#L340-L345
`f(2, err)` in `exitLocked()`:
https://github.com/cockroachdb/cockroach/blob/cb60e7536f81c0c3eae854e4774c66a01a4f691c/pkg/util/log/exit_override.go#L78-L82
`f` is set to an anonymous func containing `f(x)` by `SetExitFunc()`:
https://github.com/cockroachdb/cockroach/blob/cb60e7536f81c0c3eae854e4774c66a01a4f691c/pkg/util/log/exit_override.go#L25-L30
`SetExitFunc()` calls `SetExitFuncErr()`:
https://github.com/cockroachdb/cockroach/blob/cb60e7536f81c0c3eae854e4774c66a01a4f691c/pkg/util/log/exit_override.go#L34-L40
The anonymous func will be set to call `c.Close()` by `main()`:
https://github.com/cockroachdb/cockroach/blob/cb60e7536f81c0c3eae854e4774c66a01a4f691c/pkg/cmd/zerosum/main.go#L440-L443
`c.stopper.Stop()`:
https://github.com/cockroachdb/cockroach/blob/cb60e7536f81c0c3eae854e4774c66a01a4f691c/pkg/acceptance/localcluster/cluster.go#L218-L222
`Stopper.mu.Lock()`
https://github.com/cockroachdb/cockroach/blob/cb60e7536f81c0c3eae854e4774c66a01a4f691c/pkg/util/stop/stopper.go#L448-L449

Based on #48447 and this issue, I think a possible solution is to unlock `loggerT.mu` before calling `c.Close()`. Maybe a better place is before calling `f(2, err)`?

**To Reproduce**
--

**Expected behavior**
Deadlock

**Additional data / screenshots**
--

**Environment:**
master branch, commit cb60e7536f81c0c3eae854e4774c66a01a4f691c

**Additional context**
--

**Comment by lunevalex** [comment]
This was fixed in #48471, closing.
