### ISSUE TITLE
sql: begin analysis of DDL roundtrips

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#48498]
We should analyze existing DDL statements to understand the roundtrips that they perform. Doing so may uncover patterns to make systematic improvements to DDL statement performance.

Tasks:
- [x] Figure out how to parse traces for roundtrips
- [x] Create a datadriven test that counts roundtrips for a query
- [x] Add a test for each DDL statement

**Comment by awoods187** [comment]
I'm super excited for this work!

**Comment by RichardJCai** [comment]
Done as a benchmark test here https://github.com/cockroachdb/cockroach/pull/50953
