### ISSUE TITLE
ui: Use real protocol buffers when communicating with the server

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#4849]
Currently, all information requested by the UI from the server is returned as marshalled JSON objects.  However, it is now possible for javascript to consume protocol buffer messages directly (javascript generation is possible directly from protoc).

This is not a trivial change, but it will give several advantages in terms of speed, error detection and maintaining a correct API.

**Comment by petermattis** [comment]
How does this interact with the move to JSON admin endpoints? Are you proposing we have those endpoints return protos instead? I suppose that is possible given that the endpoints are defined in `.proto` files.

**Comment by tamird** [comment]
#4844 gets us pretty close. What's missing is protobuf-over-HTTP support - as far as I can tell, grpc-gateway doesn't provide it, but it should be pretty easy to add (we have prior art in cockroach where we switch on the request's content type).

Maybe something to do on a Friday after #4844 is in.

**Comment by tamird** [comment]
Filed https://github.com/gengo/grpc-gateway/issues/124 upstream.

**Comment by maxlang** [comment]
I already have a working version with the current proto stuff here:https://github.com/cockroachdb/cockroach/blob/master/ui/scripts/jsClientDemo.js

The only reason it isn't in the client is that we'd have to bypass/fix mithril's request function to prevent corrupting the binary data.

**Comment by maxlang** [comment]
I think we can consider this closed thanks to @tamird

**Comment by tamird** [comment]
For posterity, this was fixed in #7178.
