### ISSUE TITLE
Unexpected broadening of database level BACKUP

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#48502]
**Describe the problem**
I expected if your full backup is `BACKUP DATABASE db1 ...` then an incremental on that full backup that is `BACKUP DATABASE db1,db2 ...` to fail. That is not the case if `db2` does not have any tables.

**To Reproduce**

1. Spin up a cluster. Create `db1` and `db2`. Add table `db1.table1` to `db1`. Add row to `db1.table1`
2. `BACKUP DATABASE db1 TO 'nodelocal://1/backup'`
3. `BACKUP DATABASE db1,db2 TO 'nodelocal://1/backup'` -->expected to fail but it works
4. Create db2.table2 (do not add data)
5. `BACKUP DATABASE db1,db2 TO 'nodelocal://1/backup'` --> also works
6. Add row to db2.table2
7. `BACKUP DATABASE db1,db2 TO 'nodelocal://1/backup'` --> also works

In current state of db1.table1 and db2.table2 having data
1. `BACKUP DATABASE db1 TO 'nodelocal://1/backup'`
2. `BACKUP DATABASE db1,db2 TO 'nodelocal://1/backup'` --> fails with `ERROR: previous backup does not contain table "table2"`

**Additional data / screenshots**
`root@localhost:26257/defaultdb> show backup 'nodelocal://1/backup1';
  database_name | table_name |            start_time            |             end_time             | size_bytes | rows | is_full_cluster
----------------+------------+----------------------------------+----------------------------------+------------+------+------------------
  db1           | table1     | NULL                             | 2020-05-06 19:37:19.829094+00:00 |         19 |    1 |      false
  db1           | table1     | 2020-05-06 19:37:19.829094+00:00 | 2020-05-06 19:37:31.518943+00:00 |          0 |    0 |      false
  db1           | table1     | 2020-05-06 19:37:31.518943+00:00 | 2020-05-06 19:40:10.564531+00:00 |          0 |    0 |      false
  db2           | table2     | 2020-05-06 19:37:31.518943+00:00 | 2020-05-06 19:40:10.564531+00:00 |          0 |    0 |      false
  db1           | table1     | 2020-05-06 19:40:10.564531+00:00 | 2020-05-06 19:40:33.522033+00:00 |          0 |    0 |      false
  db2           | table2     | 2020-05-06 19:40:10.564531+00:00 | 2020-05-06 19:40:33.522033+00:00 |         19 |    1 |      false
(6 rows)`

**Environment:**
 - v20.1.0-beta.4-1340-geb644088fd

**Comment by pbardea** [comment]
I looked into this and from what I can tell this won't cause any issues. In particular, the reason that we don't allow adding a new database in an incremental backup is because we're not sure that we have the history of the table - but going through this song and dance actually ensures that we don't run into this issue.

That being said, we should address this in the name of UX consistency.
