### ISSUE TITLE
sql: Revoke privilege myself

### ISSUE THREAD

**Issue by mxwmwx** [cockroachdb/cockroach#48524]
version: v19.1 
mode: insecure
description:
First  as root , create a table t and a user "yhq" and then grant select on table t to yhq with grant option.
Second, login as yhq
Third, Revoke select myself
it shows :
![image](https://user-images.githubusercontent.com/37258498/81272895-b54a9900-9080-11ea-8953-37c4cd9777ac.png)
the message "REVOKE" means that sucess , but actually , failed.

**Comment by otan** [comment]
@RichardJCai ?

**Comment by RichardJCai** [comment]
> @RichardJCai ?

Looking into it

**Comment by jordanlewis** [comment]
@mxwmwx, if you open a new session, this will work properly. Going to close, but feel free to ask more questions here. Thank you!

**Comment by mxwmwx** [comment]
> if you open a new session, this will work properly. Going to close, but feel free to ask more questions here. Thank you
![image](https://user-images.githubusercontent.com/37258498/83004958-d3cdff80-a042-11ea-8dc0-f724ae1f0fcb.png)

sorry to bother you again, I tried, but actualiy, can't revoke privilege myself. As is shown above
