### ISSUE TITLE
sql, kv: Allow optional scrubbing of PII from EXPLAIN ANALYZE (DEBUG)

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#48594]
Our SE team mentioned that several customers might not be willing to share the output of `EXPLAIN ANALYZE (DEBUG)` due to the sensitive information contained in the zip file. Specifically, table statistics and trace files contain keys from tables. We should consider an alternate version of this tool that allows collection of as much information as possible while avoiding collecting any sensitive information.

cc @awoods187, @RaduBerinde, and @andreimatei 

Jira issue: CRDB-4312

**Comment by piyush-singh** [comment]
A user noted that while we do not have the option to remove PII collection here, a way to disable the button for this collection to avoid issues with PII might be a nice short-term solution.

**Comment by yuzefovich** [comment]
closing as a dup of #68570 which has been mostly addressed
