### ISSUE TITLE
ui: table details page reporting incorrect replica counts

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#48599]
While investigating an issue (that I caused) on the registration cluster, we noted that the table details page is reporting incorrect replica counts on the cluster:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/21692034/81436379-66136f80-9137-11ea-84d9-8ea7f56c8218.png">

```
psingh@<redacted>:26257/registration> show zone configuration for table stmtstats;
         target         |                  raw_config_sql                   
+-----------------------+--------------------------------------------------+
  DATABASE registration | ALTER DATABASE registration CONFIGURE ZONE USING  
                        |     range_min_bytes = 16777216,                   
                        |     range_max_bytes = 67108864,                   
                        |     gc.ttlseconds = 270000,                       
                        |     num_replicas = 3,                             
                        |     constraints = '[]',                           
                        |     lease_preferences = '[]'                      
(1 row)

Time: 50.763ms
```
Given the cluster has 0 underreplicated ranges, we expect the replica count for this table to be 3 in accordance with its zone configurations. We should investigate this mismatch.

**Comment by piyush-singh** [comment]
Tim V suspects the label for indexes was accidentally changed to replicas here, we should confirm which metric we are displaying and label appropriately.

**Comment by dhartunian** [comment]
note to self: make sure to take a look at possibly Data Distribution & Zone Configs debug page at #/data-distribution (via @taroface)
