### ISSUE TITLE
keys: ReportingTableID should not be in SystemConfigSpan

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#4859]
`keys.ReportingTableID` currently places the reporting table in the `SystemConfigSpan` which means the reporting table will be gossiped to all nodes. This isn't necessary. We need to `s/ReportingTableID = 6/ReportingTableID = 14/g` and handle any fallout in tests. More importantly, the comments (which I thought were clear) in `keys/constants.go` need to be enhanced to avoid making a similar mistake in the future.

**Comment by cuongdo** [comment]
This table is being replaced as part of PR #4844. I'll address this as part
of that PR.
