### ISSUE TITLE
sql: missing memory accounting for internal executor (+crash w/ crdb_internal.jobs)

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#48595]
(NB: this issue is both applicable to the 20.1 tree which materializes the vtables lazily, and the previous approach)

**Describe the problem**

In PR #45758 new code was added to account for memory of the materialized rows in crdb_internal.jobs.

However the calls to the memory monitor API is performed _after_ all the rows have been loaded in RAM already.

If there was not enough RAM to start with, the node crashes with an OOM error before the point where the monitor API is called. 

This issue affects all uses of the internal executor, not just crdb_internal.jobs.

This is why the OOM crashes upon large system jobs tables are still happening despite #45758  being merged.

**Expected resolution**

The proper approach is to enhance the InternalExecutor to ~use a SQL memory monitor when filling its bufferedCommandResult~ stream results to its caller, which is not done currently.

**Comment by knz** [comment]
cc @jordanlewis for triage

cc @andreimatei: maybe you can make an architectural suggestion as to where to find a good monitorin inside `(r *bufferedCommandResult) AddRow()`

**Comment by andreimatei** [comment]
What I would encourage would be making the `InternalExecutor` stream its results back instead of buffering them (in that `bufferedCommandResult`). Like, stream them out on a channel, perhaps with the channel's buffering controlled by the caller, or even through actually implementing a tiny database/sql driver and then using the standard go `Rows` object.
I know @spaskob was looking at using a channel somehow a while ago.

**Comment by knz** [comment]
Ok a channel is also good. In any case, this fix must be lightweight enough as to be backportable, so I wouldn't recommend a large architectural change.

**Comment by knz** [comment]
@dt and I had a separate discussion, and because of the discussion in #46367 it would be good if the solution was not based on memory accounting, and instead use streaming as suggested by Andrei. This ensures that we don't force more memory errors onto users when the solution to this gets backported.

**Comment by ajwerner** [comment]
Your expected resolution: memory accounting in the internal executor would be great. It just didn't seem easy at the time. Not only are the results handed back from the `InternalExecutor` neither bufferred nor memory-accounted, the execution of the `InternalExecutor` isn't memory accounted at all. 

We knew that the memory accounting was bogus when we added #45758. The idea was that it was a modest improvement for two reasons. At the time we also buffered deserialized copies of the data in RAM, additionally, the hope was that if we got to that point, at least we might prevent a different, concurrent request from pushing us over the limit. It was not a great patch but the hope was that it was better than nothing.

**Comment by knz** [comment]
>  It was not a great patch but the hope was that it was better than nothing.

I saw your comment in the code. I agree the patch was better than nothing. Unfortunately our CC SREs also discovered it was not sufficient. Hence this followup.

**Comment by spaskob** [comment]
This is the current state on my work on this: https://github.com/cockroachdb/cockroach/pull/48615
It turned out to be a lot of work so I have abandoned it for quite some in favor of 20.1 release work.
Let me know if it is worth revisiting.

**Comment by knz** [comment]
Yes I appreciate that it is a lot of work and the problem is somewhat complex to solve. However, the impact is high and would be a time/money server for CC. This is definitely worth the investment. I encourage you to discuss this with other TLs/PMs to ensure it gets budgeted/scheduled appropriately.
