### ISSUE TITLE
sql: support the ALTER TYPE SET SCHEMA command

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#48671]
See https://www.postgresql.org/docs/9.1/sql-altertype.html.

**Comment by RichardJCai** [comment]
Useful blurb from PG
```You must own the type to use ALTER TYPE. To change the schema of a type, you must also have CREATE privilege on the new schema. To alter the owner, you must also be a direct or indirect member of the new owning role, and that role must have CREATE privilege on the type's schema. (These restrictions enforce that altering the owner doesn't do anything you couldn't do by dropping and recreating the type. However, a superuser can alter ownership of any type anyway.)```
