### ISSUE TITLE
[Bug] the feature of blank directory (--log-dir="") disables logging  failed in cockroach-v19.2.6

### ISSUE THREAD

**Issue by diyism** [cockroachdb/cockroach#48686]
**Describe the problem**
replace cockroach 19.1.1 with cockroach 19.2.6 in /usr/local/bin/

then run:
`cockroach start --listen-addr=127.0.0.1 --insecure --store=/var/cockroach8 --port 26258 --http-port 8088`
everything is ok

run:
`cockroach start --listen-addr=127.0.0.1 --insecure --store=/var/cockroach8 --port 26258 --http-port 8088 --log-dir=""`
show error: F200511 17:39:02.104238 13 server/server.go:2055  [n2] could not create goroutine dump dir: mkdir goroutine_dump: permission denied

**Expected behavior**
start the server without error just like  old version of cockroach
there is this sentence "Setting --log-dir to a blank directory (--log-dir="") disables logging to files."
in the doc page: https://www.cockroachlabs.com/docs/v19.2/cockroach-start.html#logging

By the way how to disable the log file  /var/cockroach8/000019.log,  even in cockroach 19.1.1 I can disable /var/cockroach8/logs with --log-dir="" but I can't disable /var/cockroach8/000019.log, this file become very big finally.

**Comment by otan** [comment]
this looks recently fixed by  444e72beef2da8df82cf58420511b4a0dc74d248, just have to wait for the upcoming release.

**Comment by diyism** [comment]
> this looks recently fixed by [444e72b](https://github.com/cockroachdb/cockroach/commit/444e72beef2da8df82cf58420511b4a0dc74d248), just have to wait for the upcoming release.

Thanks, I'll wait for the upcoming release. 

By the way, could you do me a favor to tell me some information about: /var/cockroach8/000019.log ?
this log file always exists in /var/cockroach8 while other log files exist in /var/cockroach8/logs directory.

**Comment by otan** [comment]
sounds like a different issue to file :)

not sure, what is inside it, if you don't mind sharing?

**Comment by diyism** [comment]
> sounds like a different issue to file :)
> 
> not sure, what is inside it, if you don't mind sharing?

the size of /var/cockroach8/000019.log is now 60MB,    run "tail 000019.log"  it shows:
```
1tsdcr.node.sql.mem.sql.session.current����1 (2#��������ȯ�%"�:
                                                                                                                           ��������)tsdcr.node.sql.mem.sql.max-max����1 (2#��������ȯ�%"�:
                                                                                                                                                                                        ��������-tsdcr.node.sql.mem.sql.max-p99.999����1 (2#��������ȯ�%"�:
                                                           ��������,tsdcr.node.sql.mem.sql.max-p99.99����1 (2#��������ȯ�%"�:
                                                                                                                           ��������+tsdcr.node.sql.mem.sql.max-p99.9����1 (2#��������ȯ�%"�:
                                                                                                                                                                                          ��������)tsdcr.node.sql.mem.sql.max-p99����1 (2#��������ȯ�%"�:
                                                         ��������)tsdcr.node.sql.mem.sql.max-p90����1 (2#��������ȯ�%"�:
                                                                                                                      ��������)tsdcr.node.sql.mem.sql.max-p75����1 (2#��������ȯ�%"�:
                                                                                                                                                                                   ��������)tsdcr.node.sql.mem.sql.max-p50����1 (2#��������ȯ�%"�:
                                                  ��������)tsdcr.node.sql.mem.sql.current����1 (2#��������ȯ�%"�:
                                                                                                               ��������1tsdcr.node.sql.mem.sql.session.max-max����1 (2#��������ȯ�%"�:
                                                                                                                                                                                    ��������1tsdcr.node.sql.mem.sql.session.current����1 (2#��������ȯ�%"�:

```

**Comment by diyism** [comment]
I guess that 
the log files in /var/cockroach8 are ordered logs for consensus,
the log files in /var/cockroach8/logs are database date change logs.
