### ISSUE TITLE
backupccl: move table stats out of manifest

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#48719]
When TableStatistics were added to `BACKUP`, they were originally thought to be small - however it has become clear that with histograms and for many tables there is actually a significant overhead to the backup manifest files.

For context, they were added to the backup manifest proto rather than backing up their SSTs to simplify the tableID remapping that RESTORE would perform. The encoding of the table statistics should be revised and should at least be moved to a separate file in order to decouple downloading table statistics data with other metadata about the backup (e.g. start and end time of the backup).

**Comment by Anzoteh96** [comment]
The `TableStatistics` field is an array of `TableStatisticsProto` objects, so when moving this field out to store in a separate file we're faced with the following decision: whether to store the whole array of stats in one file, or have each `TableStatisticsProto` object stored in a separate file. 

Pros of storing everything in the same file: reduced overhead when retrieving files. This is especially helpful when we have many stats object in the array, each of which is small. 

Cons: A huge file might OOM the node. Also comparatively harder to implement as the `protoutil.Marshal` (and `Unmarshal`) method can be applied directly to the `TableStatisticsProto` object but not the whole array, which makes the alternative solution (storing each object separately) convenient.

**Comment by pbardea** [comment]
So the problematic case here is when there are a lot of table descriptors. I think in general it would be useful for the backup manifest to store a mapping between table IDs and files which store the stats for that table. I think this is nice because it would allow us to try both file partitioning schemes mentioned and leave us open in the future to potentially implement a middle-ground solution. @dt mentioned that it would be nice if we could chunk the size of these files so we can avoid making tons of tiny files (the case where each descriptor has their own stats file) and also avoid one giant file (where all the stats are written to the same file).

If we go with the idea of keeping this map between ID and file names, I think that it doesn't particularly matter which of the previously mentioned solutions we'd go with. I'd probably recommend writing them all to the same file, since this sounds like it'd be the quickest to implement and would be strictly better than what we have today. We could iterate from there.
