### ISSUE TITLE
pg_catalog.pg_opclass not implemented

### ISSUE THREAD

**Issue by roji** [cockroachdb/cockroach#48729]
As part of Npgsql's EF Core scaffolding, the pg_opclass table is loaded - this fails on Cockroach:

```
0A000: unimplemented: virtual schema table not implemented: pg_catalog.pg_opclass
```

[The specific query](https://github.com/npgsql/efcore.pg/blob/dev/src/EFCore.PG/Scaffolding/Internal/NpgsqlDatabaseModelFactory.cs#L451) being executed is `SELECT oid, opcname, opcdefault FROM pg_opclass`.

The provider can be changed not to load operator classes if the query fails.

See #47420

**Comment by rafiss** [comment]
We don't support operator classes right now, but we will improve compatibility by making this table and leaving it empty.

cc @mnovelodou
