### ISSUE TITLE
sql: `VALUES (1), (2) ORDER BY 3*4` is unsupported

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#4873]
Right now, it parses but the ORDER BY clause is dropped. After https://github.com/cockroachdb/cockroach/pull/4862 is merged, it will be rejected as unsupported.

**Comment by tamird** [comment]
Triage: this now errors as follows:

```
root@:26257> VALUES (1), (2) ORDER BY 3*4;
pq: invalid column index: 12 not in range [1, 1]
```

In postgres:
```
test=# VALUES (1), (2) ORDER BY 3*4;
 column1
---------
       1
       2
(2 rows)
```

**Comment by knz** [comment]
FWIW I think that pg's behavior is in error (neither 3, 4 nor 12 are valid ordinal column references). @paperstreet what do you think?

**Comment by paperstreet** [comment]
My opinion is that using anything but a constant for ordinal column refs would be surprising, but I also have never used a sql database in production, so I probably don't have a good sense of what the community would find surprising

**Comment by spencerkimball** [comment]
@knz this is clearly not a 1.0 milestone (so removing). I'm adding the `known-limitation` tag. Should this be assigned to someone?

**Comment by knz** [comment]
I addressed this issue back in December in the context of another issue filed in the same area. Nothing to be done here.
