### ISSUE TITLE
ui: Network Latency page has incorrect labels for std deviations

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#48742]
<img width="730" alt="image" src="https://user-images.githubusercontent.com/21692034/81736285-4eecbe80-9464-11ea-8b91-d94643b66742.png">

The +1 and -1 labels both have less than signs ("<"). The positive numbers should instead be greater than ">". @Annebirzin and @taroface - thoughts on best labeling practices here? It might be clearer to simply say `+1 std dev` or `+1σ`

**Comment by taroface** [comment]
I'm a fan of `+1 std dev` as it is the most direct description. I think this also matches how most usually refer to standard deviations.

**Comment by Annebirzin** [comment]
`+1 std dev` works for me

**Comment by Annebirzin** [comment]
Maybe the the middle one can just stay as `mean` since `mean std dev` might be too long

**Comment by dhartunian** [comment]
# Testing requirements

* Screenshot in PR is adequate here

**Comment by koorosh** [comment]
@Annebirzin adding `+1 std dev` makes it less readable.

<img width="731" alt="Screenshot 2020-06-16 at 17 17 45" src="https://user-images.githubusercontent.com/3106437/84786421-6c79ee80-aff5-11ea-98dd-0cb262a40ef1.png">

**Comment by taroface** [comment]
Looking at this again, would it be clear enough to simply use `-2`, `-1`, `MEAN`, `+1`, `+2`? Or are the `<` and `>` signs necessary?

**Comment by Annebirzin** [comment]
I'm open to removing the  `<` `>` to simplify. 

We could also update the fonts/colors to make it more readable:
