### ISSUE TITLE
Consistency Checker stuck (unable to dial n2: breaker open) - v19.2.6

### ISSUE THREAD

**Issue by dendon** [cockroachdb/cockroach#48761]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

The Consistency Checker is stuck because it can't connect to itself over external IP because of iptables (I only added 127.0.0.1 in iptables).

**To Reproduce**

What did you do? Describe in your own words.

```
iptables -A INPUT -p tcp -s 127.0.0.1 --dport 26257 -j ACCEPT
iptables -A INPUT -p tcp -s 0.0.0.0/0 --dport 26257 -j DROP
```

If possible, provide steps to reproduce the behavior:

Run the iptables commands and see consistency checker queue run full.

**Expected behavior**

This might be expected behaviour, however it gets confusing considering I wasn't expecting the node to talk to itself over the external IP.

**Additional data / screenshots**

```
W200512 23:53:47.624846 13730740167 vendor/google.golang.org/grpc/clientconn.go:1206  grpc: addrConn.createTransport failed to connect to {db-02:26257 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp [2a01:___]:26257: connect: connection timed out". Reconnecting...
E200512 23:53:48.584588 13730774196 storage/consistency_queue.go:134  [n2,consistencyChecker,s2,r165252/2:/Table/123/1/5336582{29…-60…}] computing own checksum: could not dial node ID 2: failed to connect to n2 at db-02:26257: initial connection heartbeat failed: operation "rpc heartbeat" timed out after 6s: rpc error: code = DeadlineExceeded desc = context deadline exceeded
E200512 23:53:48.584611 13730774196 storage/queue.go:1088  [n2,consistencyChecker,s2,r165252/2:/Table/123/1/5336582{29…-60…}] computing own checksum: could not dial node ID 2: failed to connect to n2 at db-02:26257: initial connection heartbeat failed: operation "rpc heartbeat" timed out after 6s: rpc error: code = DeadlineExceeded desc = context deadline exceeded
W200512 23:53:48.625063 13730740167 vendor/google.golang.org/grpc/clientconn.go:1206  grpc: addrConn.createTransport failed to connect to {db-02:26257 0  <nil>}. Err :connection error: desc = "transport: Error while dialing cannot reuse client connection". Reconnecting...
E200512 23:53:49.833295 13730780803 storage/consistency_queue.go:134  [n2,consistencyChecker,s2,r176670/2:/Table/123/1/5346705{06…-38…}] computing own checksum: could not dial node ID 2: unable to dial n2: breaker open
E200512 23:53:49.833318 13730780803 storage/queue.go:1088  [n2,consistencyChecker,s2,r176670/2:/Table/123/1/5346705{06…-38…}] computing own checksum: could not dial node ID 2: unable to dial n2: breaker open
```

**Environment:**
 - CockroachDB version: v19.2.6
 - Server OS: Ubuntu 18.04 64bit

**Additional context**
What was the impact?

Consistency Checker got stuck

**Comment by ajwerner** [comment]
Nodes need to be able to connect to themselves. This is also a requirement for range merging. The address used to dial itself is the advertise addr. If this is a single node cluster and you want the node to talk to itself at 127.0.0.1.

I sense that there is an issue to keep open here, and it's possible that it relates to https://github.com/cockroachdb/cockroach/issues/42741. Perhaps there is a workaround to utilize `locality-advertise-addr` where you give each node a locality for just that node and then set the locality-advertise-addr for that node to 127.0.0.1 then it might work but no promises. @knz I didn't understand the limitation in #42741 very well, is there a problem with what I suggested here?

**Comment by dendon** [comment]
Correct, it's a single node cluster.
However that port is actually avabilable over external to other servers that connect to the database (I just excluded the iptables commands for simplicity).

I was assuming that each node would run it's own consistency checker and merger in that regard, so that it would be fine to only allow 127.0.0.1 to connect and not the external IP of the node and that it simply would go over 127.0.0.1 and not over the external.
Like I said, it might be expected behavior, still confusing in a single node cluster.

**Comment by ajwerner** [comment]
>  Like I said, it might be expected behavior, still confusing in a single node cluster. 

Fair enough. One thing I'll note is that we have a special start command for starting a single node cluster: `cockroach start-single-node`. That command will set up networking to use `localhost` for self connections. That is additionally the preferred mechanism to start single-node clusters because it will set the replication factors to one.

https://www.cockroachlabs.com/docs/stable/cockroach-start-single-node.html

For multi-node clusters, we expect the advertise-addr to be routable for all nodes. Fair enough. @rmloveland think it's worth more explicitly calling out that all nodes, including the local node needs to be able to talk to itself over localhost. I'm going to close this issue as I think `start-single-node` is a pretty good answer here.

**Comment by dendon** [comment]
> Fair enough. One thing I'll note is that we have a special start command for starting a single node cluster: cockroach start-single-node. That command will set up networking to use localhost for self connections. That is additionally the preferred mechanism to start single-node clusters because it will set the replication factors to one.

I am aware of that, and this is how the node is started.

```
cockroach-server/cockroach start-single-node --insecure --cache=.25 --max-sql-memory=.25 --store=path=cockroach-data,rocksdb=soft_pending_compaction_bytes_limit=8313349076924:hard_pending_compaction_bytes_limit=8313349076924
```

```
head -n10 cockroach-data/logs/cockroach.log
I200512 18:39:40.182087 843 util/log/clog.go:1094  [config] file created at: 2020/05/12 18:39:40
I200512 18:39:40.182087 843 util/log/clog.go:1094  [config] running on machine: db-02
I200512 18:39:40.182087 843 util/log/clog.go:1094  [config] binary: CockroachDB CCL v19.2.6 (x86_64-unknown-linux-gnu, built 2020/04/06 18:05:31, go1.12.12)
I200512 18:39:40.182087 843 util/log/clog.go:1094  [config] arguments: [cockroach-server/cockroach start-single-node --insecure --cache=.25 --max-sql-memory=.25 --store=path=cockroach-data,rocksdb=soft_pending_compaction_bytes_limit=8313349076924:hard_pending_compaction_bytes_limit=8313349076924]
I200512 18:39:40.182087 843 util/log/clog.go:1094  [config] clusterID: 9b1873ae-___
I200512 18:39:40.182087 843 util/log/clog.go:1094  line format: [IWEF]yymmdd hh:mm:ss.uuuuuu goid file:line msg utf8=✓
I200512 18:39:40.182083 843 server/status/runtime.go:498  [n2] runtime stats: 176 GiB RSS, 16228 goroutines, 2.5 GiB/10 GiB/6.1 GiB GO alloc/idle/total, 132 GiB/172 GiB CGO alloc/total, 194931.1 CGO/sec, 1093.7/0.0 %(u/s)time, 0.0 %gc (3x), 5.8 MiB/42 MiB (r/w)net
E200512 18:39:43.183696 13652818764 storage/consistency_queue.go:134  [n2,consistencyChecker,s2,r151404/2:/Table/123/1/532975{144…-218…}] computing own checksum: could not dial node ID 2: failed to connect to n2 at db-02:26257: initial connection heartbeat failed: operation "rpc heartbeat" timed out after 6s: rpc error: code = DeadlineExceeded desc = context deadline exceeded
E200512 18:39:43.183721 13652818764 storage/queue.go:1088  [n2,consistencyChecker,s2,r151404/2:/Table/123/1/532975{144…-218…}] computing own checksum: could not dial node ID 2: failed to connect to n2 at db-02:26257: initial connection heartbeat failed: operation "rpc heartbeat" timed out after 6s: rpc error: code = DeadlineExceeded desc = context deadline exceeded
E200512 18:39:43.185425 13652836794 storage/consistency_queue.go:134  [n2,consistencyChecker,s2,r13274/2:/Table/56/1/4715{4417…-6992…}] computing own checksum: could not dial node ID 2: unable to dial n2: breaker open
```

```
SHOW ZONE CONFIGURATIONS;
             target            |                     raw_config_sql
+------------------------------+---------------------------------------------------------+
  RANGE default                | ALTER RANGE default CONFIGURE ZONE USING
                               |     range_min_bytes = 16777216,
                               |     range_max_bytes = 67108864,
                               |     gc.ttlseconds = 90000,
                               |     num_replicas = 1,
                               |     constraints = '[]',
                               |     lease_preferences = '[]'
```
