### ISSUE TITLE
jobs: destroy tenant keyspaces asynchronously

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#48775]
As part of #47904, we'll be introducing tenant destruction. It's tempting to make this is a synchronous operation that blows away all data in a tenant's keyspace immediately. This would probably work for the scale we're originally intending to support, but it's not a great solution in the long run.

We expect tenants to grow to arbitrarily large sizes, so we'll likely want to schedule tenant destruction as a long-running GC job in the system-tenants keyspace.

**Comment by nvanbenschoten** [comment]
Another option is to simply kick off a blocking ClearRange operation after the transaction that deletes a tenant has committed. This would probably be simpler.

**Comment by dt** [comment]
I'd suggest changing `active` from a bool to an enum (ideally soon, before we need to do a migration) so it can be extended to capture more detail about the state, e.g. off the top of my head I think it would make sense to have at least 4 states: `active`, `inactive`, `adding`, and `dropped`. This could e.g. make it easier to identify tenants who have been destroyed but whose key-span has not been cleared, if we see a record in state `dropped`. The current bool's coarseness makes it impossible to tell a tenant that is restoring from but is not yet active from one that is dropping.
