### ISSUE TITLE
sqlmigration: create system.tenants table

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#48779]
We introduced a `system.tenants` table in #48778. We don't have any pressing concerns about supporting multi-tenancy in old clusters that have been migrated to `master`, but when we eventually do, we'll need to add a (cluster-wide) SQL migration like [this one](https://github.com/cockroachdb/cockroach/blob/d80bc2f36a0ae87f5bdaa7829fece2f8d732b6de/pkg/sqlmigrations/migrations.go#L1254) to add this table to existing clusters that have been upgraded from v20.1.

**Comment by tbg** [comment]
I might end up doing this as part of #52096. @nvanbenschoten you added the blocker label, mind adding a comment as to why?

**Comment by nvanbenschoten** [comment]
I think I marked it as a blocker after a discussion with you about https://github.com/cockroachdb/cockroach/pull/52096. If BACKUP is going to consult the table, it better be there. I guess you could add some conditional logic to look for the table, but if you're going to have to do that, we might as well just address this issue instead.
