### ISSUE TITLE
jobs: Make system.jobs load aware

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#48825]
Add some sort of admission control to system.jobs to prevent starting new jobs
if the cluster load is too high.

* A simple version might restrict the total number of running jobs in a cluster.
* A better version might look at more load metricts, and even apply scheduling
decisions based on job type

* Bonus: pause the job if the load in the cluster is too high

Jira issue: CRDB-4297

**Comment by mwang1026** [comment]
cc @vy-ton moved over to Schema as part of cleanup. Interesting overlap with Admission Control, so I'm also curious about your thoughts on this overall re: admission control and jobs.

**Comment by ajwerner** [comment]
Also, noting that while at some level the need for this definitely exists, this issue is a speculative placeholder that is not driven by any urgent need or demand.
