### ISSUE TITLE
log: ISO formatted dates

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#48824]
Currently our logs use this date format.  
`3:47:17.247698`

For compatibility and readability, using ISO 8601 format would make more sense and include more details in the timestamp so you don't need to know the filename to understand when it occurred.  

Assigning to @knz for triage.  Wasn't sure who to send this to.

**Comment by BramGruneir** [comment]
If we make this change, a cluster setting or flag might make sense to allow the original format so it doesn't break system people have already built on top of the logs.

**Comment by knz** [comment]
The *time* format you listed above is already in ISO 8601.

I agree the *data* format is not. However, the mapping is trivial (can be done with e.g. awk, tr, sed etc).

> a cluster setting or flag might make sense

yes agree, I could live with that

**Comment by BramGruneir** [comment]
Ah, yes, you are correct.  But when munging a bunch of files together, having the full date/time in the line would help.

**Comment by bdarnell** [comment]
If we're going to change our log format, is there a widely-used format we could adopt instead? Our current format is based on google's glog library (with some modifications), but if there were something better supported by tools out of the box that would be better. Or if we just want to make some ad-hoc tweaks, I'd like to move that `I/W/E/F` character out of the first position so lines are sorted (and so it doesn't look like the letter+date is an error code)

**Comment by knz** [comment]
My first reaction here is to try a syslog sink as next step and see how much mileage we get with that.
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by irfansharif** [comment]
(bump for #44755)

**Comment by knz** [comment]
This work was completed, you can now log to fluent and ask fluent to format dates in any way you want.

Cc @thtruo @taroface if you're interested to document this use case
