### ISSUE TITLE
backupccl: improve performance for many incremental backups

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#48835]
As we're seeing more and more frequent incremental backups we should develop test coverage for these types of workloads as well as invest in performance improvements in backup and restore to handle backup history chains with many (hundreds) incremental backups.

Epic: CRDB-10127

Jira issue: CRDB-4296

**Comment by mwang1026** [comment]
Stress test frequent incremental backups with gzip and table stats out of manifest

**Comment by pbardea** [comment]
Adding as a note that we should be mindful of the performance of `SHOW BACKUP` as we move towards a world where incremental backups are taken more aggressively.

**Comment by shermanCRL** [comment]
Closing this general tracking issue as we’ve implemented many individual improvements. For future improvements, we’ll create a separate issue. cc @livlobo
