### ISSUE TITLE
sql: select json{,b}_agg(null) need to return an empty array and not [null]

### ISSUE THREAD

**Issue by C0rWin** [cockroachdb/cockroach#48840]
**Describe the problem**

For aggregate queries with `json{,b}_agg` builtin function in case it has null it has to skip it, while instead it's being counted. As a consequence for query where expected an empty array, query resulted with `[null]`, which is not really expected by default. 

Therefore it should be fixed and skip null values instead of aggregating them.

/cc @jordanlewis

**Comment by C0rWin** [comment]
If no objections and issues is confirmed I'd like to also fix it :)

**Comment by jordanlewis** [comment]
Hmm, I believe this is expected behavior. Aggregating no rows produces NULL (not [NULL]).

Example from Postgres:

```
jordan=# create table a (a jsonb);
CREATE TABLE
jordan=# select jsonb_agg(a) from a;
 jsonb_agg
-----------

(1 row)

jordan=# select jsonb_agg(a) is null from a;
 ?column?
----------
 t
(1 row)
```

CRDB:

```
root@127.0.0.1:62427/defaultdb> create table a (a jsonb);
CREATE TABLE

Time: 6.49ms

root@127.0.0.1:62427/defaultdb> select jsonb_agg(a) from a;
  jsonb_agg
-------------
  NULL
(1 row)

Time: 4.969ms
```

Closing, but feel free to keep posting on this if you disagree!

**Comment by C0rWin** [comment]
I think  I might be missing something, here is my example:

```
create table empty_arr(id int, val string);
insert into empty_arr values (1, null), (2, 'a'), (3, null);
```

results in

```
root@:26257/defaultdb> select json_agg(val) from empty_arr where val is null;
    json_agg
----------------
  [null, null]
(1 row)
```

Where I think I would expect `[]` instead.

**Comment by jordanlewis** [comment]
No, this is also correct. I agree it's weird, but jsonb_agg is defined to return nulls. https://www.postgresql.org/docs/current/functions-aggregate.html
