### ISSUE TITLE
sql: json builtin object functions allows duplicate keys

### ISSUE THREAD

**Issue by C0rWin** [cockroachdb/cockroach#48841]
**Describe the problem**

JSON built in functions to create JSON objects succeed to create object even if two similar keys are introduced.

**To Reproduce**

```
select json_build_object('k1', 'v1', 'k1', 'v2')
```

results with 

```
{k1: "v2"}
```

while I would expect to get an error instead since input obviously is not correct.

/cc @jordanlewis

**Comment by C0rWin** [comment]
If confirmed I'd like to take care and fix the issue.

**Comment by jordanlewis** [comment]
This looks like correct behavior. PostgreSQL does the same thing, and we need to model ourselves after their behavior for builtins like these.

```
jordan=# select jsonb_build_object('k1', 'v1', 'k1', 'v2');
 jsonb_build_object
--------------------
 {"k1": "v2"}
(1 row)
```

**Comment by jordanlewis** [comment]
I'll close this, but thanks for filing and checking carefully the behavior for things like this!

**Comment by C0rWin** [comment]
@jordanlewis thanks for taking look, and yes I realized that this must be the reason :)

**Comment by C0rWin** [comment]
@jordanlewis I've just tested with psql version `psql (12.3 (Debian 12.3-1.pgdg100+1))` and this is what I've got:

```
postgres=# select json_build_object('k1', 'v1', 'k1', 'v2');
     json_build_object
----------------------------
 {"k1" : "v1", "k1" : "v2"}
(1 row)
```

Seems it keeps both now.

**Comment by jordanlewis** [comment]
Use `jsonb_build_object`, in Postgres the `json` ones aren't semantic json, just a text format. We emulate the `jsonb` ones as the `json` type is not really that useful in Postgres.
