### ISSUE TITLE
server: add authentication to the debug endpoints

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#48858]
The debug endpoints are currently non authenticated.

It's somewhat ok wrt security because they are also not open beyond `localhost` access by default. But it's still a problem:

- there can be adversaries using a compromised service on the same machine to "bounce" a connection so that it appears to originate from `localhost`

- support sometimes encourages users to change the debug endpoint configuration to open it to the network and the user forgets to set it back aftewards.

So instead we want authentication.

Meanwhile, we would like the debug endpoints not to use KV reads for authentication, so they can be used when system ranges are unavailable.

Therefore, the auth should be based on a non-KV solution, for example the proposal in the [always-available users RFC](#44134)

cc @aaron-crl for triage

**Comment by piyush-singh** [comment]
cc @dhartunian as a heads up

**Comment by aaron-crl** [comment]
cc @thtruo for tracking.

**Comment by bdarnell** [comment]
#50483 applied our existing auth system to all `/debug/` endpoints.
