### ISSUE TITLE
kv: raft log's oldest index is less than the first index for range

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4890]
saw this check fail in `getTruncatableIndexes`:

``` go
    if oldestIndex < firstIndex {
        return 0, 0, util.Errorf("raft log's oldest index is less than the first index for range %d", rangeID)
    }
```

in https://circle-artifacts.com/gh/cockroachdb/cockroach/13890/artifacts/0/tmp/circle-artifacts.MR6IXjE/acceptance/TestDockerPHP/roach0.local/stderr.2016-03-05T23_39_14Z.log

Likely this is racy so this check may fail occasionally, but is it expected in that situation?

**Comment by tschottdorf** [comment]
#6046 has this too:

```
W160413 13:06:47.698470 storage/raft_log_queue.go:116  storage/raft_log_queue.go:101: raft log's oldest index (0) is less than the first index (129733) for range 44
```

Seems to be happening a lot. If this is an expected race (and expected with that frequency) we should hide this warning (and maybe replace it with a warning about long raft logs instead). I'm not familiar enough with the circumstances of this occurrence to judge.

**Comment by bdarnell** [comment]
An oldest index of 0 is probably harmless and should not be logged: it's a normal occurrence when a new replica has been added to the range and hasn't processed its first snapshot yet. I'm surprised, though, how often this is happening so it may point to some other issue, especially if the message is repeated for the same range.

**Comment by tamird** [comment]
Visiting for triage: has this been seen since #7040?

**Comment by tschottdorf** [comment]
Yes, this is a very frequent log entry still, and not only with zero
(though probably mostly on overloaded clusters, where multiple conflicting
truncations might be issued). Still, I'm seeing this a bit more often than
I'm comfortable with.

On Fri, Jul 1, 2016 at 8:21 PM Tamir Duberstein <notifications@github.com>
wrote:

> Visiting for triage: has this been seen since #7040
> <https://github.com/cockroachdb/cockroach/pull/7040>?
>
> —
> You are receiving this because you authored the thread.
>
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/4890#issuecomment-230072408>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE135Aq-Fta5LT0K3El48rRCp4_SXwQUks5qRa8NgaJpZM4HqIV_>
> .
>
-- 

-- Tobias

**Comment by BramGruneir** [comment]
Yeah.  I'm going to be adding some new tracing for this as well.

**Comment by tschottdorf** [comment]
Closing as too stale.
