### ISSUE TITLE
testing: provide integration testing story for external projects

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#4897]
External projects which are using CockroachDB need an easy mechanism for testing against a CockroachDB cluster on continuous build systems such as Travis and CircleCI. Building a cockroach binary from source is not acceptable: it takes too long unless complex caching is set up. Prebuilt linux binaries might be sufficient if we make the retrieval, caching an running trivial, perhaps via a wrapper script.

**Comment by spencerkimball** [comment]
https://github.com/cockroachdb/cockroach-go/pull/1
