### ISSUE TITLE
geo/geomfn: implement ST_MinimumBoundingRadius({geometry})

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#48988]
Implement `ST_MinimumBoundingRadius` on arguments {geometry}, which should adopt [PostGIS behaviour](https://postgis.net/docs/ST_MinimumBoundingRadius.html).

*Observers: Please react to this issue if you need this functionality.*

For Geometry builtins, please do the following:
* Ideally add a relevant helper function in [`pkg/geo/geomfn`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo/geomfn) (parse and output related functions can go in [`pkg/geo`](https://github.com/cockroachdb/cockroach/tree/master/pkg/geo)). Add exhaustive unit tests here - you can run through example test cases and make sure that PostGIS and CRDB return the same result within a degree of accuracy (1cm for geography).
  * When using GEOS, you can reference the [C API](https://github.com/libgeos/geos/blob/master/capi/geos_c.h.in) for which functions are available. Unfortunately, Windows is not currently supported when using GEOS.
* Create a new builtin that references this function in [`pkg/sql/sem/builtins/geo_builtins.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/geo_builtins.go). Note that we currently do not support optional arguments, so we define functions that have optional arguments once without the optional argument (using the default value in the optional position), and once with the optional argument.
* Modify the tests in [`pkg/sql/logictest/testdata/logic_test/geospatial`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/geospatial) to call this functionality at least once. You can call `make testbaselogic FILES='geospatial' TESTFLAGS='-rewrite'` to regenerate the output. Tests here should just ensure the builtin is linked end to end (your exhaustive unit tests go the above mentioned packages!).
* Ensure the documentation is regenerated by calling `make buildshort`. You can also play with it by calling `./cockroach demo --empty` afterwards.
* Submit your PR - make sure to follow the guidelines from [creating your first PR](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR]).

You can follow #48552 for an example PR.

The following additional guidance has been issued on implementing this function:

Implemented by GEOS.

<sub>:robot: This issue was synced with a spreadsheet by [gsheets-to-github-issues](https://github.com/cockroachlabs/gsheet-to-github-issues) by [otan](https://github.com/otan) on 2020-08-30T17:39:33Z. Changes to titles, body and labels may be overwritten.</sub>

**Comment by C0rWin** [comment]
Based on [documentation](https://postgis.net/docs/ST_MinimumBoundingRadius.html) this function has to return a record or set of two columns: one for the center of the circle and the second one for its radius. 

It seems that currently, the only option would be to return a tuple, cause based on my understanding there is no support to return records from the built-in function. 

Are there any suggestions on how to proceed with this?

**Comment by otan** [comment]
use a generator built-in. The tuple type is a record. You should be able to
use a named tuple.

**Comment by C0rWin** [comment]
> use a generator built-in. The tuple type is a record. You should be able to use a named tuple.

can you give an example?

**Comment by otan** [comment]
yes -- try `aclexplode`.

https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/generator_builtins.go#L94

this returns multiple columns.

**Comment by otan** [comment]
`unnest` also does this:

```

demo@127.0.0.1:61265/defaultdb> select * from unnest(ARRAY[1,2], ARRAY['foo','bar','baz']) as x(a,b) ;
   a   |  b
-------+------
     1 | foo
     2 | bar
  NULL | baz
(3 rows)

Time: 1ms total (execution 0ms / network 0ms)

```
