### ISSUE TITLE
backupccl: restore jobs restarting while running stats collection re-split table

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#49084]
**Describe the problem**

I have a cluster in which I performed a relatively large restore, ~500GiB. The restore got to a point where it said that it was `95%` complete. At this point the restored table was usable, so I started to use it. At some point I ascertained that the restore job was running stats collection. Several days later, the job remained at `95%`. At some point I restarted the nodes of the cluster leading to the job restarting. At that point I noticed a large amount of split activity. After grabbing a stack trace, I noticed the source of the splits to be the restore job:

```

goroutine 11622 [semacquire, 16 minutes]:
sync.runtime_Semacquire(0xc007ab19c0)
	/usr/local/go/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc007ab19b8)
	/usr/local/go/src/sync/waitgroup.go:130 +0x64
github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup.(*Group).Wait(0xc007ab19b0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:40 +0x31
github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.Wait(0xc007ab19b0, 0x4bb83c0, 0xc005dda2c0, 0xc009e362a0, 0x20)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:142 +0x57
github.com/cockroachdb/cockroach/pkg/ccl/backupccl.splitAndScatter(0x4bb83c0, 0xc018f77200, 0xc0004faa80, 0xc0004e1f00, 0xc0075f5fc0, 0x3, 0xc0194ce000, 0x3b6, 0x444, 0xc0080a77a0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_job.go:421 +0x6a3
github.com/cockroachdb/cockroach/pkg/ccl/backupccl.restore.func2(0x4bb83c0, 0xc018f77200, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/backupccl/restore_job.go:669 +0x12f
github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx.func1(0xc00511bf68, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:166 +0x3a
github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0192a73b0, 0xc0192a73e0)
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x64
created by github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup.(*Group).Go
	/go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66
```

**Expected behavior**

We don't resplit the table after we've run the whole restore already.

**Environment:**
 - 20.1.0
 - Server OS: Linux

Epic CRDB-8816

Jira issue: CRDB-4257

**Comment by ajwerner** [comment]
Amazingly, after the splitting concluded, the job moved to `SUCCEEDED`

**Comment by dt** [comment]
Ah, I think there are two issues here: the first is that it got stuck in stats. 

The second is that on "...I  restarted the nodes ... a large amount of split activity ... [but]  expected ... don't resplit the table" -- This is interesting, since the spans we hand to splitAndScatter on resume should just be what's left to do. `makeImportSpans` takes the progress highwatermark, so on resume we're supposed to just do what's left.
