### ISSUE TITLE
sql: tables created in mixed 19.2-20.1 state after namespace migration is run won't get moved to namespace2

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#49090]
## Problem

When the first 20.1 node joins a 19.2 cluster, the `migrateSystemNamespace` migration will run, which copies all entries from descriptor 2 (the old `system.namespace`) to descriptor 30 (`system.namespace2`).

In a mixed-version state, new tables and databases are added only to descriptor 2 (`system.namespace`).

Since `migrateSystemNamespace` only gets run once, those new tables and databases from the mixed-version state will never automatically get upgraded to the 20.1 format.

## Consequences:

There are no known user-visible errors from this issue.

1. We can't get rid of the fallback namespace table logic until 20.2.
2. Tables that were created in the mixed-version state will always require 2 namespace lookups, since the first one will fail.

## Resolution:

1. We should add another migration that runs `migrateSystemNamespace` in 20.1.1, so that customers upgrading from 20.1.0 to 20.1.1 will repair their namespace2 (descriptor 30) table.
2. We should add an invocation of `migrateSystemNamespace` to the finalized-version hook in 20.1.1 so that customers upgrading from 19.2.x to 20.1.1 will not have this problem.

## Note:

Because of this problem, we can't remove the fallback logic for searching system.namespace (descriptor 2) until 21.1. (cc @nvanbenschoten, since I think you were looking at removing something like this recently).

**Comment by nvanbenschoten** [comment]
> Because of this problem, we can't remove the fallback logic for searching system.namespace (descriptor 2) until 21.1.

You're saying that we can't remove it until 21.1 because a user might upgrade straight from 20.1.0 to 20.2, so 20.2 nodes will still need to be able to read from `system.namespace`? Is this because the SQL migrations themselves need to be able to read from `system.namespace`, so we need to wait an extra release to remove the fallback logic?
