### ISSUE TITLE
storage/cloud: revise file existance guarantees in `ExternalStorage` interface

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#49093]
This issue summarizes a discussion between @miretskiy and me about the `ExternalStorage` interface and possible improvements.

Backup currently uses the `ReadFile` method of the `ExternalStorage` interface to check if a file exists. This method currently supplies the caller a reader for a requested name. The current expectation is that `ReadFile` will return an error if the file does not exist. This at the very least should be enforced with tests. However, we should revise if we think that this is the best API to check for the presence of a file. Some possibilities include:
- Using the existing `Size` method
- Add an `Stat`/`Attrs` method. Similar to the existing `Size` method, and `stat` is sometimes used in Linux systems to check for file existence. In addition, it may provide useful information such as file checksums.
- Document and test that `ReadFile` does always return an error in the case the named file does not exist.

**Comment by adityamaru** [comment]
@pbardea @miretskiy reopening this discussion. I had a chance to look over some of the `ReadFile` usages and wanted your opinion on which solution is most appropriate.

In my opinion, we should have every `ReadFile` implementation check for the existence of the file and wrap/tag the "does not exist" error into a generalized error type (thereby allowing narrower error handling than `err != nil`). In scenarios where we solely want to check for the existence of a file, this might be a less explicit method call, but in other places where the reader is used to extract data, we get this existence check without the user having to make an additional `Stat/Size` call prior to `ReadFile`. The generalized error type should also help increase readability in places where we only want an existence check.

**Comment by pbardea** [comment]
I'm 👍 with enforcing that `ReadFile` should return a sentinel file not found error as long as it's documented and tested.

**Comment by pbardea** [comment]
Closed by #49913.
