### ISSUE TITLE
sql: dropping tables or databases on the 19.2 binary in a 19.2-20.1 mixed cluster orphans system.namespace2 entries

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#49092]
## Repro:

1. Start up a 19.2 cluster.
2. Open a SQL shell to one of the nodes. Run `CREATE DATABASE foo`.
3. Replace one of the 19.2 nodes with a 20.1 node.
4. Run `DROP DATABASE foo` on the first SQL shell (running 19.2).
5. Open a SQL shell to the 20.1 node. Run `SHOW DATABASES`.

```
root@localhost:26258/defaultdb> show databases;
ERROR: internal error: "" is not a database
SQLSTATE: XX000
DETAIL: stack trace:
/go/src/github.com/cockroachdb/cockroach/pkg/sql/table.go:788: getDatabaseDescriptorsFromIDs()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/table.go:745: getAllDatabaseDescriptors()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:1475: forEachDatabaseDesc()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:967: func71()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:274: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt_exec_factory.go:143: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/delayed.go:48: startExec()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:395: func2()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:144: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:721: visitInternal()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:111: visit()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:75: walkPlan()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:398: startExec()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:117: Start()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/distinct.go:153: Start()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowexec/sorter.go:283: Start()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:748: Run()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:370: Run()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:405: Run()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1019: PlanAndRun()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:883: execWithDistSQLEngine()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:776: dispatchToExecutionEngine()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:481: execStmtInOpenState()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:96: execStmt()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1368: execCmd()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1297: run()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:476: ServeConn()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:590: func1()
/usr/local/go/src/runtime/asm_amd64.s:1357: goexit()
```

The cause symptom of this error is an orphaned row in the system.descriptor2 table containing the `foo` database.

If you were to do this same process with a table instead of a database, you'd get an orphaned table row that causes the following symptom:

```
root@:26257/defaultdb> create table a (a int);
ERROR: relation "a" already exists
SQLSTATE: 42P07
root@:26257/defaultdb> drop table a;
ERROR: relation "a" does not exist
SQLSTATE: 42P01
```

## Cause

When the first 20.1 node joins the cluster, it copies all `system.namespace` (descriptor 2) entries to `system.namespace2` (descriptor 30).

When a 19.2 node drops a table or database, it deletes the corresponding row from `system.namespace`, but not from `system.namespace2`, since it doesn't know that `system.namespace2` exists.

The 20.1 node will then experience an orphaned namespace entry when it searches for something.

Note that this sequence is only possible if the `DROP` occurs on the 19.2 binary. It cannot occur on the 20.1 binary before the upgrade is finalized, and once the upgrade is finalized, only 20.1 nodes can be in the cluster, and 20.1 nodes always delete from both the `namespace` and `namespace2` tables during drops.

## Mitigation for users that had this problem

We have to advise users to manually remove the orphaned rows from `system.namespace`.

## Prevention for 20.1.1+

We need to ideally move this migration so that it only happens post-finalization, so that dropping objects on the 19.2 binary in a mixed state doesn't orphan anything in the new namespace table.

If we made this change for 20.1.1, along with #49090, users who migrate from 19.2 to 20.1.1+ would have no chance of running into this issue.

**Comment by jordanlewis** [comment]
@jseldess, can we add a note in the upgrade section of the docs about this? Should be something like:

When upgrading from 19.2 to 20.1.0, you shouldn't drop or rename tables or databases on the 19.2 nodes, or you could risk getting into a bad state.

If you do get into the bad state (see #49092 for what that would look like), you can resolve it by manually deleting the orphaned rows from the namespace table, like this (run on the 20.1 node):

```
# Select all orphaned namespace rows.
SELECT id, name FROM system.namespace2 WHERE id != 29 AND id NOT IN (SELECT id FROM system.descriptor);
# Manually verify that each of these ids correspond to tables or databases that no longer exist.
# Grant node-level permissions to root.
INSERT INTO system.users VALUES ('node', '', true);
GRANT node TO root;
# Delete the orphaned namespace rows. Do this for each id returned from the first query. Be careful!
DELETE FROM system.namespace2 WHERE id = ?
# Revoke node-level permissions.
REVOKE node FROM root;
```

Hopefully, we'll resolve this issue for 20.1.1.

**Comment by lucy-zhang** [comment]
In addition to dropping/renaming, I think truncating tables also causes this problem, right?

**Comment by jordanlewis** [comment]
Yes, good point.

**Comment by lucy-zhang** [comment]
Now that we've had a user test out these steps: One annoying thing is that `GRANT`/`REVOKE` count as schema changes and therefore can't be run on 20.1 nodes pre-finalization. I think the only good way to do this is to roll back a node to 19.2 (if necessary) and run the schema changes when connected to that node.

**Comment by jseldess** [comment]
@lucy-zhang, @jordanlewis, Lucy's last comment confuses me a bit. We already document the grant/revoke limitations here: https://www.cockroachlabs.com/docs/stable/upgrade-cockroach-version.html#review-temporary-limitations. How does this relate to this new limitation around drop, rename, or truncate tables, views, sequences or database?

**Comment by lucy-zhang** [comment]
Jordan's script above contains a step to `GRANT` and then `REVOKE` privileges, which is necessary to be able to write to a system table (but otherwise unrelated to this bug).

**Comment by jseldess** [comment]
Thanks, @lucy-zhang. So are you saying that, if a user gets in this bad state, the solution is to:

1. Roll back a node to 19.2.
2. Run Jordan's steps, including the revoke, on that node.
3. Upgrade the node again. 

Is that right?

Also, can you provide any insight into how this will change for 20.1.1?

**Comment by lucy-zhang** [comment]
Yeah, although they only need to take the step of rolling back a node to 19.2 if they haven't finalized the upgrade to 20.1.0. Otherwise they can just run the script as-is.

> Also, can you provide any insight into how this will change for 20.1.1?

At the very least, we're getting rid of the faulty pre-finalization migration in 20.1.1. So if a user upgrades from 19.2.x directly to 20.1.1 (or later), _and_ no node running any earlier 20.1 release (i.e., 20.1.0, or any alpha/beta/RC) has ever joined the cluster, then they shouldn't have any problems.

There's the separate question of whether we can fix the broken state automatically, upon upgrading to 20.1.1 from an earlier 20.1, so that users don't even have to manually intervene. That I'm not sure about, but @jordanlewis has been thinking about it.
