### ISSUE TITLE
sql: end-to-end test drivers with SQL tenant servers

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#49109]
We need to set up automated testing that verifies that a suitable set of drivers+orms can connect to and use a SQL tenant server.
This should initially operate against the standalone SQL server (#49104) but ultimately also involve the tenant proxy (#49107).

This should be straightforward to do with modifications only to how the test server process is set up:

https://github.com/cockroachdb/examples-orms/blob/ec2c8e47e2786d7c0bc74467efebc7d7c76aa28e/vendor/github.com/cockroachdb/cockroach-go/testserver/testserver.go#L158

However, everything here is unencrypted. We're going to want to run this with TLS on, which something that will need to be added to the test harness as well.

Then there's also the blacklist roachtest:

https://github.com/cockroachdb/cockroach/blob/6467ba95e69d8738c03829bc5069f53d240c9005/pkg/cmd/roachtest/blacklist_test.go#L29

which deserves some attention as well. The hope is that the tenant setup would result in the same as the corresponding single-tenant one.

cc @rafiss, am I missing anything?

**Comment by tbg** [comment]
We're not quite ready to spin up dedicated tenant processes today, but something we should do ASAP is to make examples-orms use TLS to get it to parity with production use.

**Comment by rafiss** [comment]
Setting up TLS for examples-orms sounds good to me. And I think those tests are the place to start for making sure ORMs work.

That blacklist_test isn't the right thing to look at in the roachtests -- this test just aggregates blacklists that are defined in other tests. I think what we'd want to do is figure out how to get tests like `pgjdbc.go` and `pgx.go` (etc) running against tenant servers. These are the things that actually run the ORM/driver test suite, and verify that the failures are the ones that we have explicitly marked as expected failures in our blacklist.

**Comment by asubiotto** [comment]
Closed by https://github.com/cockroachdb/examples-orms/pull/108
