### ISSUE TITLE
sql: the statement stats "retry counter" was misdesigned

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#49128]
The problem is that the counter is counting retries, not retry errors.

As we push users away from using `SAVEPOINT cockroach_restart` (and let them retry txns entirely), there is no way inside cockroachdb to identify "retry attempts" from plain "a second iteration of the same txn because that's what the app logic needs".

This came up in https://github.com/cockroachdb/docs/issues/7223 because users are increasingly observing a discrepancy between the counter and their experience.

The current code should be scrapped entirely and replaced by:

- a counter of how many *retry errors* have been produced by cockroachdb to the client on that statement key (i.e. count the errors, not the retries)
- how many internal retries were performed

Jira issue: CRDB-4254

**Comment by knz** [comment]
NB: I was the one who mis-designed this originally (FWIW there was no real design evaluation when this was done, someone wanted "a retry counter" and I provided. We didn't properly understand that not every client uses the savepoint restart protocol.)

**Comment by asubiotto** [comment]
Putting this on the features team since they're working on other observability-related things

**Comment by jordanlewis** [comment]
@solongordon did we make progress here? I think we did...

**Comment by rafiss** [comment]
Adding to SQL Observability for them to decide how to handle this.
