### ISSUE TITLE
what is wrong with make build command ?

### ISSUE THREAD

**Issue by mohammadMghi** [cockroachdb/cockroach#49168]
this error or not ?
In file included from /home/ramtin/cockroach-v20.1.0/src/github.com/cockroachdb/cockroach/c-deps/cryptopp/default.cpp:13:0:
/home/ramtin/cockroach-v20.1.0/src/github.com/cockroachdb/cockroach/c-deps/cryptopp/default.h:57:7: note: declared here
 class DefaultDecryptor : public ProxyFilter
       ^~~~~~~~~~~~~~~~
[ 23%] Building CXX object CMakeFiles/cryptopp-object.dir/des.cpp.o
[ 24%] Building CXX object CMakeFiles/cryptopp-object.dir/dessp.cpp.o
[ 24%] Building CXX object CMakeFiles/cryptopp-object.dir/dh.cpp.o
[ 25%] Building CXX object CMakeFiles/cryptopp-object.dir/dh2.cpp.o
[ 26%] Building CXX object CMakeFiles/cryptopp-object.dir/dll.cpp.o
[ 27%] Building CXX object CMakeFiles/cryptopp-object.dir/dsa.cpp.o
[ 27%] Building CXX object CMakeFiles/cryptopp-object.dir/eax.cpp.o
[ 28%] Building CXX object CMakeFiles/cryptopp-object.dir/ec2n.cpp.o
[ 29%] Building CXX object CMakeFiles/cryptopp-object.dir/eccrypto.cpp.o
[ 30%] Building CXX object CMakeFiles/cryptopp-object.dir/ecp.cpp.o
[ 30%] Building CXX object CMakeFiles/cryptopp-object.dir/elgamal.cpp.o
[ 31%] Building CXX object CMakeFiles/cryptopp-object.dir/emsa2.cpp.o
[ 32%] Building CXX object CMakeFiles/cryptopp-object.dir/eprecomp.cpp.o
[ 32%] Building CXX object CMakeFiles/cryptopp-object.dir/esign.cpp.o
[ 34%] Building CXX object CMakeFiles/cryptopp-object.dir/files.cpp.o
[ 35%] Building CXX object CMakeFiles/cryptopp-object.dir/filters.cpp.o
[ 36%] Building CXX object CMakeFiles/cryptopp-object.dir/fips140.cpp.o
[ 36%] Building CXX object CMakeFiles/cryptopp-object.dir/gcm.cpp.o
[ 37%] Building CXX object CMakeFiles/cryptopp-object.dir/gf256.cpp.o
[ 38%] Building CXX object CMakeFiles/cryptopp-object.dir/gf2_32.cpp.o
[ 39%] Building CXX object CMakeFiles/cryptopp-object.dir/gf2n.cpp.o
[ 39%] Building CXX object CMakeFiles/cryptopp-object.dir/gfpcrypt.cpp.o
[ 40%] Building CXX object CMakeFiles/cryptopp-object.dir/gost.cpp.o
[ 41%] Building CXX object CMakeFiles/cryptopp-object.dir/gzip.cpp.o
[ 42%] Building CXX object CMakeFiles/cryptopp-object.dir/hex.cpp.o
[ 42%] Building CXX object CMakeFiles/cryptopp-object.dir/hmac.cpp.o
[ 43%] Building CXX object CMakeFiles/cryptopp-object.dir/hrtimer.cpp.o
[ 45%] Building CXX object CMakeFiles/cryptopp-object.dir/ida.cpp.o
[ 46%] Building CXX object CMakeFiles/cryptopp-object.dir/idea.cpp.o
[ 46%] Building CXX object CMakeFiles/cryptopp-object.dir/iterhash.cpp.o
[ 47%] Building CXX object CMakeFiles/cryptopp-object.dir/keccak.cpp.o
[ 48%] Building CXX object CMakeFiles/cryptopp-object.dir/luc.cpp.o
[ 48%] Building CXX object CMakeFiles/cryptopp-object.dir/mars.cpp.o
[ 49%] Building CXX object CMakeFiles/cryptopp-object.dir/marss.cpp.o
[ 50%] Building CXX object CMakeFiles/cryptopp-object.dir/md2.cpp.o
[ 51%] Building CXX object CMakeFiles/cryptopp-object.dir/md4.cpp.o
[ 51%] Building CXX object CMakeFiles/cryptopp-object.dir/md5.cpp.o
[ 52%] Building CXX object CMakeFiles/cryptopp-object.dir/misc.cpp.o
[ 53%] Building CXX object CMakeFiles/cryptopp-object.dir/modes.cpp.o
[ 54%] Building CXX object CMakeFiles/cryptopp-object.dir/mqueue.cpp.o
[ 54%] Building CXX object CMakeFiles/cryptopp-object.dir/mqv.cpp.o
[ 56%] Building CXX object CMakeFiles/cryptopp-object.dir/nbtheory.cpp.o
[ 57%] Building CXX object CMakeFiles/cryptopp-object.dir/network.cpp.o
[ 58%] Building CXX object CMakeFiles/cryptopp-object.dir/oaep.cpp.o
[ 58%] Building CXX object CMakeFiles/cryptopp-object.dir/osrng.cpp.o
[ 59%] Building CXX object CMakeFiles/cryptopp-object.dir/panama.cpp.o
[ 60%] Building CXX object CMakeFiles/cryptopp-object.dir/pkcspad.cpp.o
[ 60%] Building CXX object CMakeFiles/cryptopp-object.dir/polynomi.cpp.o
[ 61%] Building CXX object CMakeFiles/cryptopp-object.dir/pssr.cpp.o
[ 62%] Building CXX object CMakeFiles/cryptopp-object.dir/pubkey.cpp.o
[ 63%] Building CXX object CMakeFiles/cryptopp-object.dir/queue.cpp.o
[ 63%] Building CXX object CMakeFiles/cryptopp-object.dir/rabin.cpp.o
[ 64%] Building CXX object CMakeFiles/cryptopp-object.dir/randpool.cpp.o
[ 65%] Building CXX object CMakeFiles/cryptopp-object.dir/rc2.cpp.o
[ 67%] Building CXX object CMakeFiles/cryptopp-object.dir/rc5.cpp.o
[ 67%] Building CXX object CMakeFiles/cryptopp-object.dir/rc6.cpp.o
[ 68%] Building CXX object CMakeFiles/cryptopp-object.dir/rdrand.cpp.o
[ 69%] Building CXX object CMakeFiles/cryptopp-object.dir/rdtables.cpp.o
[ 70%] Building CXX object CMakeFiles/cryptopp-object.dir/rijndael.cpp.o
[ 70%] Building CXX object CMakeFiles/cryptopp-object.dir/ripemd.cpp.o
[ 71%] Building CXX object CMakeFiles/cryptopp-object.dir/rng.cpp.o
[ 72%] Building CXX object CMakeFiles/cryptopp-object.dir/rsa.cpp.o
[ 73%] Building CXX object CMakeFiles/cryptopp-object.dir/rw.cpp.o
[ 73%] Building CXX object CMakeFiles/cryptopp-object.dir/safer.cpp.o
[ 74%] Building CXX object CMakeFiles/cryptopp-object.dir/salsa.cpp.o
[ 75%] Building CXX object CMakeFiles/cryptopp-object.dir/seal.cpp.o
[ 75%] Building CXX object CMakeFiles/cryptopp-object.dir/seed.cpp.o
[ 76%] Building CXX object CMakeFiles/cryptopp-object.dir/serpent.cpp.o
[ 78%] Building CXX object CMakeFiles/cryptopp-object.dir/sha.cpp.o
[ 79%] Building CXX object CMakeFiles/cryptopp-object.dir/sha3.cpp.o
[ 79%] Building CXX object CMakeFiles/cryptopp-object.dir/shacal2.cpp.o
[ 80%] Building CXX object CMakeFiles/cryptopp-object.dir/shark.cpp.o
[ 81%] Building CXX object CMakeFiles/cryptopp-object.dir/sharkbox.cpp.o
[ 82%] Building CXX object CMakeFiles/cryptopp-object.dir/skipjack.cpp.o
[ 82%] Building CXX object CMakeFiles/cryptopp-object.dir/socketft.cpp.o
[ 83%] Building CXX object CMakeFiles/cryptopp-object.dir/sosemanuk.cpp.o
[ 84%] Building CXX object CMakeFiles/cryptopp-object.dir/square.cpp.o
[ 85%] Building CXX object CMakeFiles/cryptopp-object.dir/squaretb.cpp.o
[ 85%] Building CXX object CMakeFiles/cryptopp-object.dir/strciphr.cpp.o
[ 86%] Building CXX object CMakeFiles/cryptopp-object.dir/tea.cpp.o
[ 87%] Building CXX object CMakeFiles/cryptopp-object.dir/tftables.cpp.o
[ 87%] Building CXX object CMakeFiles/cryptopp-object.dir/tiger.cpp.o
[ 89%] Building CXX object CMakeFiles/cryptopp-object.dir/tigertab.cpp.o
[ 90%] Building CXX object CMakeFiles/cryptopp-object.dir/trdlocal.cpp.o
[ 91%] Building CXX object CMakeFiles/cryptopp-object.dir/ttmac.cpp.o
[ 91%] Building CXX object CMakeFiles/cryptopp-object.dir/twofish.cpp.o
[ 92%] Building CXX object CMakeFiles/cryptopp-object.dir/vmac.cpp.o
[ 93%] Building CXX object CMakeFiles/cryptopp-object.dir/wait.cpp.o
[ 94%] Building CXX object CMakeFiles/cryptopp-object.dir/wake.cpp.o
[ 94%] Building CXX object CMakeFiles/cryptopp-object.dir/whrlpool.cpp.o
[ 95%] Building CXX object CMakeFiles/cryptopp-object.dir/xtr.cpp.o
[ 96%] Building CXX object CMakeFiles/cryptopp-object.dir/xtrcrypt.cpp.o
[ 97%] Building CXX object CMakeFiles/cryptopp-object.dir/zdeflate.cpp.o
[ 97%] Building CXX object CMakeFiles/cryptopp-object.dir/zinflate.cpp.o
[ 98%] Building CXX object CMakeFiles/cryptopp-object.dir/zlib.cpp.o
Scanning dependencies of target cryptopp-static
[100%] Linking CXX static library libcryptopp.a
**Scanning dependencies of target static
make[1]: Leaving directory '/home/ramtin/cockroach-v20.1.0/src/github.com/cockroachdb/cockroach'
Makefile:6: recipe for target 'build' failed
make: *** [build] Error 2**

................................
I install all requirement for make build command (you can see here): 
https://www.cockroachlabs.com/docs/stable/install-cockroachdb-linux.html#build-from-source

but when run make build command i get above error ! but i can run project project with : 
     $ cockroach start --background --insecure
     $ cockroach sql --insecure
     $ cockroach quit --insecure

Did you think is that an error or not ? OR  just report of end make build command !?

I run this on linux Ubuntu 18.04.2 LTS .

**Comment by kocoten1992** [comment]
It look like an error, a few last line of success build:

```
...
github.com/cockroachdb/cockroach/pkg/ccl/importccl
github.com/cockroachdb/cockroach/pkg/cli
github.com/cockroachdb/cockroach/pkg/ccl/cliccl
github.com/cockroachdb/cockroach/pkg/ccl
github.com/cockroachdb/cockroach/pkg/cmd/cockroach
Running make with -j4
GOPATH set to /go
mkdir -p lib
ln -sf /go/native/x86_64-pc-linux-gnu/geos/lib/lib{geos,geos_c}.so lib
GOFLAGS= go build -o cockroach -v  -tags ' gss make x86_64_pc_linux_gnu' -ldflags '-X github.com/cockroachdb/cockroach/pkg/build.typ=development -extldflags "" -X "github.com/cockroachdb/cockroach/pkg/build.tag=409d0dd" -X "github.com/cockroachdb/cockroach/pkg/build.rev=409d0dd100b3ec585f574297963b7007c50e3c37" -X "github.com/cockroachdb/cockroach/pkg/build.cgoTargetTriple=x86_64-pc-linux-gnu"   -X "github.com/cockroachdb/cockroach/pkg/build.utcTime=2020/05/12 23:42:09"' ./pkg/cmd/cockroach
```

What you seeing is in middle of the build, about 60% until success:

```
[ 39%] Building CXX object CMakeFiles/geos.dir/src/index/quadtree/DoubleBits.cpp.o
[ 39%] Building CXX object CMakeFiles/geos.dir/src/index/quadtree/IntervalSize.cpp.o
[ 84%] Building CXX object CMakeFiles/cryptopp-object.dir/square.cpp.o
[ 79%] Building CXX object CMakeFiles/roach.dir/protos/util/unresolved_addr.pb.cc.o
[ 39%] Building CXX object CMakeFiles/geos.dir/src/index/quadtree/Key.cpp.o
# Add comment recognized by reviewable.
echo '// GENERATED FILE DO NOT EDIT' > pkg/ui/src/js/protos.js
build/node-run.sh pkg/ui/node_modules/.bin/pbjs -t static-module -w es6 --strict-long --keep-case --path pkg --path ./vendor/github.com --path ./vendor/github.com/gogo/protobuf --path ./vendor/github.com/cockroachdb/errors --path ./vendor/go.etcd.io --path ./vendor/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis ./pkg/server/serverpb/admin.proto ./pkg/server/serverpb/status.proto ./pkg/server/serverpb/authentication.proto ./pkg/ts/tspb/timeseries.proto >> pkg/ui/src/js/protos.js
[ 85%] Building CXX object CMakeFiles/cryptopp-object.dir/squaretb.cpp.o
[ 39%] Building CXX object CMakeFiles/geos.dir/src/index/quadtree/Node.cpp.o
[ 85%] Building CXX object CMakeFiles/cryptopp-object.dir/strciphr.cpp.o
[ 40%] Building CXX object CMakeFiles/geos.dir/src/index/quadtree/NodeBase.cpp.o
[ 81%] Building CXX object CMakeFiles/roach.dir/rocksdbutils/env_encryption.cc.o
...
```

I use docker to build in this guide https://wiki.crdb.io/wiki/spaces/CRDB/pages/181338446/Getting%2Band%2Bbuilding%2Bfrom%2Bsource 

(It has a few bug with chmod permission, you need to fix that - but still better than fighting with dependencies)
