### ISSUE TITLE
webui: logical plan hierarchy broken in the webui

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#49173]
In the statements page, after clicking on a particular query, you cannot tell the hierarchy of the logical plan:
Sample query:
```SQL
SELECT
	r.revenue, v.owner_id
FROM
	rides AS r JOIN vehicles AS v ON r.vehicle_id = v.id
WHERE
	r.city = 'new york'
	AND (r.end_time - r.start_time)::INT8 > 30
	AND r.vehicle_city = 'new york'
	AND r.rider_id != v.id
	AND extract('month', r.end_time) = 12
	AND v.city = 'new york'
GROUP BY
	r.revenue, v.owner_id
ORDER BY
	max(r.revenue) DESC
LIMIT
	5;

```
![image](https://user-images.githubusercontent.com/22278911/82165196-1e50be80-9882-11ea-8e92-3068c28e1ad2.png)
Compare this with the SQL explain plan:
![image](https://user-images.githubusercontent.com/22278911/82165212-2a3c8080-9882-11ea-9889-af7335b6df3e.png)

Jira issue: CRDB-4250

**Comment by knz** [comment]
cc @piyush-singh for triage

**Comment by jordanlewis** [comment]
We've redone this completely
