### ISSUE TITLE
cli: generated man pages say to use dash delimiter for subcommands' man pages

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#4917]
When using the generated `man cockroach` command, it says:

```
SEE ALSO
       cockroach-cert(1), cockroach-debug(1), ...
```

In reality, the files are stored using an underscore delimiter (ie. `cockroach_cert.1`), so the actual command to see subcommand man pages is `man cockroach_cert`. I'm not sure what the standard is, but ideally this discrepancy could be fixed one way or another so that the docs agree with actual usage.

**Comment by knz** [comment]
This is an upstream issue: https://github.com/spf13/cobra/issues/342

**Comment by anthonyfok** [comment]
Thank you @knz for your contribution to Cobra!  I have merged your PR spf13/cobra#343, so spf13/cobra#342 is closed now.  Hope this solves your issue here at cockcroachdb!  :-)

**Comment by knz** [comment]
@dt I want to update this dependency. I tried `cd vendor/github.com/spf13/cobra && git checkout master; git pull origin master` but this updated my entire `vendor` tree instead and now I'm confused.

What should I do?
