### ISSUE TITLE
sql: shorten URL for EXPLAIN ANALYZE

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#49177]
Shorten the URL length for EXPLAIN ANALYZE:
![image](https://user-images.githubusercontent.com/22278911/82167801-dda97300-988a-11ea-84e4-c22017fe5083.png)

https://cockroachdb.github.io/distsqlplan/decode.html#eJyclf9u4kYQx__vU0z3n4C0GP8kZKVI5i7clatjp8CplzYR8uEJ5wZ76XpNQFEeqy_QJ6t2DQkkwdcc_-3MfMczn9lZ7knx95ww0v9yEfQGIfTCXnD5Rx8aZ4PRePRb0IRRP-i_H4MwBC4xL5HC0uB3OYpJmsCHYXQOIk2wgN4IBHyKBiEs8Vs6nVemJUQhCGNjUpJTWBppAr__0h_2oaF-wpimcg2ncJTjHay5uD1qQi88A-XCPJnINENogTAKGQupj03GBuG4C1elaToIjtncSJ6-9TLpY4iqWNf_c1XN1oMrKeKpbBxlPJffjig8fb8Jp2DZ28DlayV_HEafL-Dd5QFW0fCsP1TuLF41HkOacNYfvYdgcD4Yg0coyXmCYZxhQdifxCKUOOSakoXgUywKLpT5XgcNkhVhJiVpviilMl9TMuUCCbsnMpVzJIyEvMUXbZU2QRmncx32QAkv5ZOokPEMCes80J3EVn3icfx1jkOMExRtcy892Y5_EpeST9I8wdXk5laPYyLwZlIWKAp_G0UoGS3ivGDQviJbmFektXdqXwi8SVf9PCGUDDFPUDCNXpNnjI3Gw0H4kb5q8y0Kvk3Bdwklgt8VIDBOGNhEtz6fg5ovA_fE_vcfVc_XtcRtkNV14R05hMx6C7JPPM03xKx9YnqBnuHavcUa2xaYr6MJJQHnt-UC_uJpDjxnqk_fob5qKyolA79D_WPqd6lvmdrjUt_7DgKzIqCrgJ1Ar_No3Y0_sSwlOITH_kE89j6ehUizWKwPN25TXxGNQvWe-FYHWuBb3osnglWGzQr7lqXW33cPLP_eDepU62-oHB-CqDfuNh8xW8fUP97nqnHtgrIM0_ayt6D1DLOrFIfYOm9h25vNBM5iyUXb2WerLo3C3QsvJ2E0noSfg6DhW80XJluZzntfNs6dBtyTZ812DNd0dbNZvIIMMy7WUBaYMHBM-DU9vE_uW5oacSFRtN1nDTmtp8lUvQVplkp4dvVd70XVXqfzetVWfdXeXtXfeZGHWCx4XuD_epLNh2tKMJlh9eoXvBRTvBB8qj9THSOt04YEC1l5O9VhkFcuVeCu2KoV2_Viu1bs1IudWrFbL3ZrxV692KsVm_tiPQE9jM2_QYG5ZOA4m4tw_fDTfwEAAP__E7zokQ==

I thought this existed as an issue but I can't seem to find it.

**Comment by awoods187** [comment]
@RaduBerinde i think we can safely close this with the updated explain analyze. If we go back to a diagram we can explore this further. Thoughts?

**Comment by RaduBerinde** [comment]
Yes, agreed. The diagram should now be used only in exceptional cases.
