### ISSUE TITLE
sql: canceled client conn causes internal error and sentry report in colexec

### ISSUE THREAD

**Issue by kalman5** [cockroachdb/cockroach#49170]
testdb=> create table test2 (a integer, b integer);
CREATE TABLE
testdb=> insert into test2 (a,b) values (2,3),(4,5),(6,7);
INSERT 0 3
testdb=> insert into test2 select * from test2;
INSERT 0 3
testdb=> insert into test2 select * from test2;
INSERT 0 6
testdb=> insert into test2 select * from test2;
INSERT 0 12
testdb=> insert into test2 select * from test2;
INSERT 0 24
testdb=> insert into test2 select * from test2;
INSERT 0 48
testdb=> insert into test2 select * from test2;
INSERT 0 96
testdb=> insert into test2 select * from test2;
INSERT 0 192
testdb=> insert into test2 select * from test2;
INSERT 0 384
testdb=> insert into test2 select * from test2;
INSERT 0 768
testdb=> insert into test2 select * from test2;
INSERT 0 1536
testdb=> insert into test2 select * from test2;
INSERT 0 3072

At this point insert 9 milion rows in one shot
testdb=> insert into test2 select t1.* from test2 t1, test2 test2;
After a while kill the client (psql in this case), connect back and perform a select on it:

testdb=> select count(*) from test2;

this did hang for several minutes, then I got:

*
* ERROR: [n4,client=192.168.26.157:46786,hostnossl,user=kalman] Reported as error 3439f4f93f8c4b26883db2959d31f415
*
ERROR:  internal error: unexpected error from the vectorized runtime: rpc error: code = Canceled desc = context canceled
DETAIL:  stack trace:
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/execerror/error.go:92: func1()
/usr/local/go/src/runtime/panic.go:679: gopanic()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/execerror/error.go:192: VectorizedInternalPanic()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc/inbox.go:274: func2()
/usr/local/go/src/runtime/panic.go:679: gopanic()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/execerror/error.go:192: VectorizedInternalPanic()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/colrpc/inbox.go:309: Next()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/parallel_unordered_synchronizer.go:136: 1()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/execerror/error.go:95: CatchVectorizedRuntimeError()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/colexec/parallel_unordered_synchronizer.go:156: func2()
/usr/local/go/src/runtime/asm_amd64.s:1357: goexit()

HINT:  You have encountered an unexpected error.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.

We appreciate your feedback.

I'm on CRDB v20.1.0, 6 nodes cluster with a zone configuration with replica = 5, the table had a replica factor = 3

Jira issue: CRDB-4252

**Comment by knz** [comment]
cc @yuzefovich for triage

The problem here is that a context.Canceled, when issued legimitately by pgwire due to the client closing the connection, should not be treated as an internal error.

**Comment by asubiotto** [comment]
Hi @kalman5, 

The context canceled error is not unexpected and this has now been changed for later versions of 20.1. This just mean that something happened that triggered that query to be canceled. Did you try to cancel the `SELECT COUNT(*)` query?

The reason that it appears to hang is that it's attempting to clean up all the intents left behind by the big "INSERT" transaction, which is expected.

**Comment by yuzefovich** [comment]
Fixed by #86160.
