### ISSUE TITLE
Can not cancel DELETE query as query ID changes

### ISSUE THREAD

**Issue by korpa** [cockroachdb/cockroach#49171]
I have a  big table with 500,000 rows, which I want to copy to another table. As a "INSERT ... SELECT" with no LIMIT gets stuck forever, I tried to copy batches of 1000 rows.
Therefore I run `INSERT INTO new_table SELECT * FROM old_table ORDER BY id LIMIT 1000` and after this `DELETE FROM old_table ORDER BY id LIMIT 1000`. I do this until no transaction is left in 'old_table'. Normally this works really great. But from time to time the DELETE query gets stuck.

My idea was to cancel that stuck DELETE query. But this doesn't work with a very strange behavior:

In 'cockroach sql' I run
```sql
SELECT * FROM [SHOW CLUSTER QUERIES]
      WHERE application_name != '$ cockroach sql';
```
as described on https://www.cockroachlabs.com/docs/stable/manage-long-running-queries.html
It shows the stuck DELETE query. When I now try to cancel the query with `CANCEL QUERY [id]` it tells me, that the id could not be canceled as the query is not found:

`ERROR: could not cancel query 160fe7cc6525bcbf0000000000000002: query ID 160fe7cc6525bcbf0000000000000002 not found`

When I run 
```sql
SELECT * FROM [SHOW CLUSTER QUERIES]
      WHERE application_name != '$ cockroach sql';
```
again. The query id for the DELETE query changed:

![image](https://user-images.githubusercontent.com/2982785/82158371-be5d1680-9887-11ea-959e-7d58feea6101.png)

```
Build Tag:    v20.1.0
Build Time:   2020/05/05 00:07:18
Distribution: CCL
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.13.9
C Compiler:   gcc 6.3.0
Build SHA-1:  9d456b9ec82cbf9a740a092c0d9f56da48779689
Build Type:   release
```

**Comment by mattcrdb** [comment]
Hi Korpa,

Can you provide instructions to reproduce the stuck delete query?

How large is old_table?

Thanks,
Matt
