### ISSUE TITLE
webui: Differentiate ddl vs dml statements on the statements page

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#49178]
@timveil pointed out that it would be nice to be able to differentiate between DDL and DML statements on the WebUI to better focus in on the types of queries an application developer is attempting to debug/learn more about. 

@piyush-singh pointed out that while we did add search functionality in v20.1, it might not be enough. 

@timveil pointed out that right after he deploys an app the statements page is cluttered with nothing but create/alter statements so it becomes a needle/haystack  problem

**Comment by maryliag** [comment]
This would be a new column?
I assume this applies not only to DDL and DML, but also DCL and TCL, correct? Or those 2 other types don't show on this page?

**Comment by awoods187** [comment]
We discussed this in the meeting but we don't want to add a new column. Instead, we want to add a new filter. Adding a column clutters up the already crowded space.

**Comment by Annebirzin** [comment]
@maryliag I added design states for the DML/DDL/DCL filter [here](https://www.figma.com/file/MoSPFkEyJfGipCmQvvLg1a/obsrv-query-performance?node-id=2187%3A17914)

![Screen Shot 2021-03-17 at 5 28 23 PM](https://user-images.githubusercontent.com/51920721/111540951-3913ee00-8746-11eb-9716-d56f795b1ec5.png)

There are designs for single select and multi-select. I don't think we have a multi-select component built anywhere yet, so thinking it would probably be okay to start with single select filter. cc @awoods187

**Comment by awoods187** [comment]
Multi-select is definitely slick and preferable but we as you noted not needed for v1. This is great!

**Comment by maryliag** [comment]
I can see on the designs that this filter was also added to the Transactions page. Does that make sense? 
If the transaction is a group of several statements of different types, how we can define the transaction type?
Or will the filter apply if you have any statement with that type on it?

**Comment by awoods187** [comment]
As discussed in standup, I think we can skip the transactions page for now

**Comment by Annebirzin** [comment]
👍 I removed the DDL/DML filter from the transaction page in the figma designs

**Comment by maryliag** [comment]
Changes on CRDB delivered: https://github.com/cockroachdb/cockroach/pull/62989
Working on the ui changes
