### ISSUE TITLE
cli: give example of where to store cockroach.bash autocompletion script

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#4918]
It was really helpful to include the `For example, to install man pages globally on
many Unix-like systems, use "--path=/usr/local/share/man/man1` sentence in the `gen man` command's usage statement. 

I'm not sure if autocompletion scripts have a standard location as well, but they all seem to be in `/usr/local/etc/bash_completion.d` on my Mac. If this location is standard, it would be nice to add this location to the `gen autocomplete` command's usage statement as well.

**Comment by petermattis** [comment]
I'm not aware of a standard location for autocompletion scripts. The idea behind the manpage and autocompletion generation is that per-system installation scripts could install them to the correct location. For instance, our brew recipe should be installing these (and currently isn't).

**Comment by knz** [comment]
I don't think this is a product issue but rather a doc issue. Perhaps we ought to close this issue here and open an issue in the docs repo instead. What do you think?

**Comment by nvanbenschoten** [comment]
I think this can be closed without opening a doc issue, as the original issue was focusing on the help commands of `gen man` and `gen autocomplete`. Like Peter mentioned, if there are system-specific locations for these scripts (instead of a standard system-independent location like for man pages), it's probably better to deal with them at the package manager/installation script level.
