### ISSUE TITLE
sql: create array types for new user defined types

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#49197]
See this excerpt from the postgres create type docs (https://www.postgresql.org/docs/9.5/sql-createtype.html):

Whenever a user-defined type is created, PostgreSQL automatically creates an associated array type, whose name consists of the element type's name prepended with an underscore, and truncated if necessary to keep it less than NAMEDATALEN bytes long. (If the name so generated collides with an existing type name, the process is repeated until a non-colliding name is found.) This implicitly-created array type is variable length and uses the built-in input and output functions array_in and array_out. The array type tracks any changes in its element type's owner or schema, and is dropped if the element type is.

You might reasonably ask why there is an ELEMENT option, if the system makes the correct array type automatically. The only case where it's useful to use ELEMENT is when you are making a fixed-length type that happens to be internally an array of a number of identical things, and you want to allow these things to be accessed directly by subscripting, in addition to whatever operations you plan to provide for the type as a whole. For example, type point is represented as just two floating-point numbers, which can be accessed using point[0] and point[1]. Note that this facility only works for fixed-length types whose internal form is exactly a sequence of identical fixed-length fields. A subscriptable variable-length type must have the generalized internal representation used by array_in and array_out. For historical reasons (i.e., this is clearly wrong but it's far too late to change it), subscripting of fixed-length array types starts from zero, rather than from one as for variable-length arrays.

**Comment by rohany** [comment]
One annoying aspect of this is that once this implicit type is created, newly created tables and types with the same name can move it out of the way! For example,

```
create type t as enum ();
// Implicit array type _t is created.
create table _t (x t);
// Succeeds!
// _t is renamed to __t.
```

**Comment by jordanlewis** [comment]
It doesn't seem necessary to me to do the type renaming as tables are created. We don't store types per table, and if we did, we'd have to change more than just this, so it feels safe to ignore this constraint for now.
