### ISSUE TITLE
create role "with login" support - pg_catalog

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/cockroach#49207]
fielded from [this forum post](https://forum.cockroachlabs.com/t/create-role-with-login/3710)

testdb=> create role role_test with LOGIN;
CREATE ROLE
testdb=> select rolcanlogin from pg_roles where rolname = ‘role_test’;
rolcanlogin
f
(1 row)

$ psql -h 192.168.26.157 -p 26257 testdb -U role_test
psql (10.6 (Ubuntu 10.6-0ubuntu0.18.04.1), server 9.5.0)
Type “help” for help.

testdb=>

so looks like the “with login” is honored but pg_roles doesn’t reflect it

**Comment by rohany** [comment]
@RichardJCai you should take a look here when you get a chance.

**Comment by RichardJCai** [comment]
> @RichardJCai you should take a look here when you get a chance.

Yep will do.

**Comment by kalman5** [comment]
The ideal would be to support "SUPERUSER" as in PG:

ALTER USER .... WITH SUPERUSER;
