### ISSUE TITLE
sql: add a virtual index on the OID column of `pg_catalog.pg_type`

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#49208]
A virtual index should be added to `pg_catalog.pg_type` so that users can perform efficient lookup of types by OID.

**Comment by kevinliao3** [comment]
Hi, I'd like to try my hand at this bug!

**Comment by rohany** [comment]
Go ahead! Some things to look at: the definition of the `pg_type` table in `pkg/sql/pg_catalog.go`, and the interface for a virtual index in `pkg/sql/virtual_schema.go:65`.

**Comment by kevinliao3** [comment]
Oh, also if anyone else is interested in working on this, don't hesitate, I am still learning CockroachDB's code base.

**Comment by kevinliao3** [comment]
@rohany Is the solution that we are aiming for enabling essentially a binary search on the oid column? Essentially ordering the oid but doing it virtually?

**Comment by rohany** [comment]
Not quite -- we have to implement a virtual index for that table, which is providing a function that takes in an oid column value and returns all the rows that have the requested oid value.

**Comment by kevinliao3** [comment]
Ah ok, what will the differences for the user be between that and a Select from where oid = x?

**Comment by kevinliao3** [comment]
Sorry, I just realized I think its so that the entire table does not need to generated and then filtered, instead just the corresponding rows generated?

**Comment by rohany** [comment]
yeah exactly -- our catalog tables are "virtual", in that we generate the rows for them when the user requests. The virtual indexes allow us to generate only the desired rows
