### ISSUE TITLE
Big inserts trigger error "placeholder index must be between 1 and 65536"

### ISSUE THREAD

**Issue by flaviolivolsi** [cockroachdb/cockroach#49256]
I get the error `placeholder index must be between 1 and 65536` whenever I try to insert tens of thousands of rows in a statement. Given that CockroachDB doesn't seem to support the `COPY` command, is there any way I can insert such amounts of data in a single statement?

**Comment by jordanlewis** [comment]
Hi @flaviolivolsi, Postgres and CockroachDB both have a hard-coded limit of 65536 placeholders in a statement. We do support the COPY command, but not via `cockroach sql`. You will have to use `psql`. You can also look at using `IMPORT`: https://www.cockroachlabs.com/docs/stable/import.html

Feel free to respond on this issue if you have more questions - thanks!
