### ISSUE TITLE
sql: `SHOW CREATE` panics when a table contains a user defined type

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#49300]
This is caused by some lower level descriptor access not hydrating descriptors properly.

**Comment by yuzefovich** [comment]
I ran into missing hydration while working on #48422, so I'm wondering whether it makes sense to reevaluate the decision to have this hydration instead of not stripping of the metadata and actually sending fully valid types across the wire. Thoughts?

**Comment by rohany** [comment]
Sending types across the wire wouldn't help in this particular issue I think. I think there are only a few more places where it actually needs to get done, and we are finishing them up now. I thought about this more, and I think that it might not be as big of a benefit as I thought. The metadata that we would be able to serialize is the types for our table descriptors. However, I think that we'd still have to do hydration for types found in expressions that are sent over to remote nodes ( I don't know if this affects vectorized or not). Either way, the current approach doesn't lock us out of doing this other approach at all, so I'm content to wait a few weeks and see how this settles down.

**Comment by yuzefovich** [comment]
Cool, sounds good to me. Exciting stuff!
