### ISSUE TITLE
sql: adding a new index to a non-empty table takes a long time to return

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#4930]
The online schema change machinery doesn't seem to be operating properly.

Repro steps:

1. Start up a single node `./cockroach start --insecure`
2. Comment out the creation of the `photosByUserID` index in `examples-go/photos/db.go`
3. Run photos app for a few minutes (from `examples-go/photos`): `go build && ./photos`
4. Stop photos app, uncomment index creation, rerun photos: `go build && ./photos`

Notice that the DDL statement to create the photos database schema blocks for a long time and only eventually returns.

**Comment by petermattis** [comment]
Can you quantify "blocks for a long time". The DDL statement doesn't return until the index has been backfilled. I would expect that to take a similar amount of time to how long you had been running the photos app. Even though the DDL statement doesn't return, the index is being added asynchronously.

**Comment by spencerkimball** [comment]
Ah, I didn't realize that was the case. Then this isn't a bug.
