### ISSUE TITLE
sql: ALTER TABLE statement issued by tenant cannot find relation

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#49318]
Modifying the logic test harness to set an explicit tenant ID:
```
diff --git a/pkg/server/testserver.go b/pkg/server/testserver.go
index 67d805b16f..9a7490c1a7 100644
--- a/pkg/server/testserver.go
+++ b/pkg/server/testserver.go
@@ -527,7 +527,14 @@ func testSQLServerArgs(ts *TestServer) sqlServerArgs {
 // StartTenant starts a SQL tenant communicating with this TestServer.
 func (ts *TestServer) StartTenant() (addr string, _ error) {
        ctx := context.Background()
+       if _, err := ts.InternalExecutor().(*sql.InternalExecutor).Exec(
+               ctx, "testserver-create-tenant", nil /* txn */, "SELECT crdb_internal.create_tenant(10)",
+       ); err != nil {
+               return "", err
+       }
+
        args := testSQLServerArgs(ts)
+       args.tenantID = roachpb.MakeTenantID(10)
```

And running the following test:
```
# LogicTest: 3node-tenant

statement ok
CREATE TABLE x (x int)

statement ok
INSERT INTO x VALUES (1)

query I
SELECT * FROM x
----
1

statement error operation is unsupported
ALTER TABLE x CONFIGURE ZONE USING num_replicas = 123
```

Fails on the `ALTER TABLE` statement.
```
        expected:
        operation is unsupported
        got:
        pq: relation "x" does not exist
```

cc @tbg @nvanbenschoten

**Comment by tbg** [comment]
You bring up an interesting point. We should be running the logic tests as a non-system tenant. (The standard run is basically how we will use the system tenant - built into KV).

Would you mind making that change? I think we'd pass a tenant id into `StartTenant` (and `testSQLServerArgs` and then use pretty much your code. The logic test usage could just hard-code 10.

**Comment by tbg** [comment]
I don't know how it explains this particular error but I think the problem will be similar to the use of the SystemCodec here:

https://github.com/cockroachdb/cockroach/blob/15c73715c3f975ac6a01cdd26c66390518783d59/pkg/sql/zone_config.go#L60

I'm pretty sure you can have this code called if you're not the system tenant, in which case the lookup will currently work (but not quite right) and in the future it will fail as the KV layer will reject it.

**Comment by tbg** [comment]
Ah it's probably here

https://github.com/cockroachdb/cockroach/blob/15c73715c3f975ac6a01cdd26c66390518783d59/pkg/sql/zone_config.go#L90

**Comment by asubiotto** [comment]
Just a note that a lot of logic tests are failing due to this so I'll hold off on triaging them until this is fixed.
