### ISSUE TITLE
sql: Support "indexes" keyword in addition to "index" on SHOW

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#4932]
MySQL supports both `SHOW INDEXES FROM <table>` and `SHOW INDEX FROM <table>`. Most web searches yield results mentioning `INDEXES`. We should probably support both, as `INDEX` (what we currently support) doesn't make as much sense in most contexts.

**Comment by jseldess** [comment]
Docs: https://www.cockroachlabs.com/docs/show-index.html
