### ISSUE TITLE
select for update lock row even without for share

### ISSUE THREAD

**Issue by kocoten1992** [cockroachdb/cockroach#49337]
**Describe the problem**
`select for update` is not behave correctly, and it is important

**To Reproduce**
```sql
CREATE TABLE test_table (
  key integer NOT NULL,
  value integer NOT NULL,
  PRIMARY KEY (key)
);

INSERT INTO test_table (key, value) values (1, 2);
INSERT INTO test_table (key, value) values (3, 4);
```
Now we open 2 cockroach shell (`cockroach sql`)

on shell 1:
```sql
begin;
select * from test_table where key = 1 for update;
# don't commit, just switch to shell 2
```
on shell 2:
```sql
select * from test_table where key = 1;
# on cockroachdb this will hang
# on postgres it can be selected - which is right
```

version
```
Build Tag:    a40921b
Build Time:   2020/05/19 09:24:38
Distribution: CCL
Platform:     linux amd64 (x86_64-pc-linux-gnu)
Go Version:   go1.13.9
C Compiler:   4.2.1 Compatible Clang 3.8.0 (tags/RELEASE_380/final)
Build SHA-1:  a40921bd0c91790c5769314b74147142361fb374
Build Type:   development
```

What was the impact?
With postgres implementation: `select for update`, `select for share` interact with each other but do not care about normal select operation.

For example: a website could use select serving users, while doing some mutex operation (`select for update`) without blocking the whole website, with our current implement, there are no way to do that - user gonna have to wait mutex operation finish on that row.

cc @nvanbenschoten

**Comment by nvanbenschoten** [comment]
Hi @kocoten1992, thanks for filing this issue. The behavior you described is somewhere between a known limitation and a known divergence from PG in the current implementation of SELECT FOR UPDATE in CockroachDB. We do not currently support the concept of an Upgrade lock, as defined here:
https://github.com/cockroachdb/cockroach/blob/5b2cf155257805b7220c0afd6565a638305394b5/pkg/kv/kvserver/concurrency/lock/locking.proto#L90

So for the time being, all SELECT FOR UPDATE locks are handled as Exclusive locks. In some senses, this divergence from Postgres extends beyond SELECT FOR UPDATE. In Postgres, all read-only queries are non-blocking. So the following will also not block:
```
in shell 1:

begin;
insert into test_table values (1, 2)
# don't commit, just switch to shell 2

in shell 2:

select * from test_table where key = 1;
# on cockroachdb this will hang
# on postgres it can be selected
```

However, this will block in CockroachDB by default.

The reason for this difference is that the non-blocking behavior exhibited in Postgres requires more coordination between transactions and is therefore significantly more expensive in a distributed environment. It is also a source of transaction retries when running under Serializable isolation. So for the foreseeable future, this probably isn't going to change as the default behavior.

That said, CockroachDB does provide the ability to modify transaction priorities (see https://www.cockroachlabs.com/docs/stable/set-transaction.html#set-priority), which has an impact on contention handling. Specifically, if you run the read-only query as high-priority, you should get something that looks like what you want.

> For example: a website could use select serving users, while doing some mutex operation (select for update) without blocking the whole website, with our current implement, there are no way to do that - user gonna have to wait mutex operation finish on that row.

I'm interested to hear more about this use case of select for update. What are you trying to accomplish with the mutex operation? Are you trying to coordinate across different services using a CockroachDB transaction as a coordination point?

**Comment by kocoten1992** [comment]
Thanks you for throughout answer! Transaction priority is indeed what I want.

One could even argue that cockroachdb behavior is correct and postgres is `wrong` (postgres have no concept of transaction priority anw).

This is like picking a different battle, I guess every database chosing different strategy when it come to row locking, https://bugs.mysql.com/bug.php?id=97089

A few of my usage are:

1. - An "advanced" queue, with ```producer --write-to--> cockroachdb <--read-from-- consumer```
consumer process don't `coordinate` with each others (as they could living in different machine), as the number of consumers grow, the chance of they are getting the same row increase:
```
1. begin a transaction;

2. from application level code, try select a task that deem fit
(select ... where1 .. where2 ..) // if this return null then continue select
(select ... where3 .. where4 ..) // if still null then keep continue select
(select ... where4 .. where5 ..) // etc
...
(until find a task or nothing)

3. update that queue_job it have consumer

// transaction could have gone wrong when commit step 3. (as mutiple consumers try to select 2.)
// result in many transactions got abort.
// select for update can solve it
```

2. - Another usage, the main reason this issue and is an interesting one, so I'm building an internet filesystem on top of cockroachdb, using transportation layer as shell command `ssh`, `scp`, `curl` and ssh `proxycommand` feature.
    - yes, you could write a long shell command on A for doing the following ```A --ssh--> B --ssh--> C (then scp pick up a file) --ssh--> D --ssh--> E (then drop the file here)```, the result you have to deploy anything on B, C, D, E (who would deploy ssh and scp!)
    - cockroachdb will save file metadata (size, md5sum..) and where it live (on Earth). When user ask for a file, it will query to see where the file closest to user (user ip address), and if network capability still available, it will serve.
    - sometimes I would want to lock a record for race condition operation (like copy and remove), but doesn't block the ability on normal query.

Let me try out this new model concurrency. Before I go, was just thinking, should we provide a `select .. priority high` as well ?
