### ISSUE TITLE
sql: sqlstats is missing on v20.1.0

### ISSUE THREAD

**Issue by DuskEagle** [cockroachdb/cockroach#49388]
**Describe the problem**

SQL stats are being reported on v20.1 clusters. The sqlstats appear as an empty list even when stats should be present.

**To Reproduce**

Visit the the `/_status/diagnostics/local` page of a v20.1 cluster, and view the `sqlStats` entry.

**Expected behavior**
SQL stats appear in the sqlStats entry on `/_status/diagnostics/local`. This is the behaviour on versions of CockroachDB <= v19.2.

**Additional context**
This affects all telemetry collection of SQL statements on v20.1 clusters. We have no stats on what types of queries are being run on v20.1 until this is fixed.

**Comment by emily-horing** [comment]
@DuskEagle / @rohany I see a PR was merged for this, does that mean we are collecting stats again? Can we backfill the missed dates or no? Thanks :)

**Comment by rohany** [comment]
We'll have to wait for 20.1.2 to go out with this fix before we start getting stats again. Sadly I don't think we can backfill the missing dates.

**Comment by knz** [comment]
this issue is fixed by #49392 isn't it?

**Comment by rohany** [comment]
I think so, but I'd like to wait for a 20.1.2 rc that I know works before closing.
