### ISSUE TITLE
cockroach demo can't restart a node

### ISSUE THREAD

**Issue by chriscasano** [cockroachdb/cockroach#49381]
Cockroach demo throws a cert error if you shutdown a node and try to restart it on 20.1.0.  Details below.

Chriss-MBP-2:roachprod chriscasano$ cockroach demo --geo-partitioned-replicas --with-load

...
 Server version: CockroachDB CCL v20.1.0 (x86_64-apple-darwin14, built 2020/05/05 00:01:50, go1.13.9) (same version as client)
 Cluster ID: d062e923-6f82-4835-a060-2f4cb3ea42e6
 Organization: Cockroach Demo

 Enter \? for a brief introduction.

root@127.0.0.1:60736/movr> \demo shutdown 3
node 3 has been shutdown
root@127.0.0.1:60736/movr> \demo restart 3
internal server error: problem with CA certificate: not found
root@127.0.0.1:60736/movr>

**Comment by rohany** [comment]
cc @otan

**Comment by otan** [comment]
something must have changed with security settings. @knz do you know what's up?
(can we re-enable https://github.com/cockroachdb/cockroach/blob/35d12cae4d5926a4a6fd9a865e74c775f2304ef7/pkg/cli/interactive_tests/test_demo_node_cmds.tcl.disabled now that TLS 1.3 is off?)

**Comment by otan** [comment]
nvm found it!
