### ISSUE TITLE
kv: follower reads pollute the leaseholder cache

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#49391]
A successful follower read will wrongly overwrite the DistSender's leaseholder cache, erroneously reasoning that the successful request must have been served by the leaseholder:
https://github.com/cockroachdb/cockroach/blob/8a9b3b4a9ad0a23a8fb402943f0bb39bc7d132f2/pkg/kv/kvclient/kvcoord/dist_sender.go#L1781-L1789

**Comment by ajwerner** [comment]
nit: RangeDescCache and leaseHolderCache are different data structures.

**Comment by ajwerner** [comment]
This one seems straightforward, just change that condition to also call `&& CanSendToFollower(...)` and then optimize that further if it feels too expensive.

**Comment by andreimatei** [comment]
I'm doing something like that for 19.2 and 20.1.
For 20.2 I was already working on a more principled way to update cache after RPCs to replicas that doesn't rely on fragile reasoning like "this RPC succeeded, therefore the lease must ...".
