### ISSUE TITLE
log,sql: enhance sentry reports for cockroachdb

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#49421]
This is a long tail of needed improvements

1) SDK upgrade

   - [x] https://github.com/cockroachlabs/registration/pull/235 update https://github.com/cockroachlabs/registration/blob/master/proxy-endpoints.go to route the new sentry SDK API
   - [x] complete #49321 to pick up the above and kick raven-go out

2) report quality 

   - [x] finish merging https://github.com/cockroachdb/errors/pull/34
   - [x] bump the dep in cockroachdb repo

3) to be discussed: would it make sense to migrate the current SQL statement in the context of a reported error, from a "Sentry tag" into an "Additional data" payload?

   - pros: Additional data has a larger size limit (many bytes) than a tag (200 bytes)
   - cons: Sentry tags are indexed, it makes it possible to "Search sentry reports by statement key (Q: who uses this search feature?)

   Notes:

     - *currently* the statement is only reported as tag, truncated to 200/500 chars (bug #49393 notwithstanding)
     - once #49321 is merged, the statement is reported both:
       - as a tag, truncated to 200 chars
       - as an "additional data" payload, truncated to 10000 characters
     - the proposal here is thus to remove the tag as it is becoming redundant with the "safe data" payload

cc @cockroachdb/sql for discussion

**Comment by yuzefovich** [comment]
Hey @knz, what do you think SQL Execution should do/discuss about this issue? The point 3 from above? Are there any other concerns?

**Comment by knz** [comment]
The question is whether it's acceptable to use an additional data payload instead of a tag, with the understanding that sentry has a search index for tags but not additional data. Do y'all search sentry reports by statement?

**Comment by asubiotto** [comment]
I have never searched sentry reports by statement. Anecdotally, we've thrown our hands up and decided not to do anything about some reports because the statement was missing or truncated, so it make sense to put it in the payload vs tag.

**Comment by knz** [comment]
ok thanks

**Comment by knz** [comment]
This has been addressed by the latest round of sentry changes
