### ISSUE TITLE
sql: EXPLAIN ANALYZE: improve understanding of stall times with "fused" processors

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#49455]
The "stall time" in EXPLAIN ANALYZE is extremely useful. It helps pinpoint the processors where most time is spent.

Unfortunately, these times don't make a lot of sense when processors are "fused" in a single goroutine. In that case, the "stall time" of a processor downstream will not include the times where we were stalled somewhere earlier in the pipeline. There is absolutely no indication of how processors are fused either so you can at best guess when this is happening.

Could we calculate the times that we would have seen if there was no fusing? Seems like if we added all the stall times of all fused processors upstream, we would get a much more useful number (even if not perfect).

Jira issue: CRDB-4227

Epic CRDB-14510

**Comment by asubiotto** [comment]
Could you provide an example plan of this happening? This is surprising to me since we calculate stall time as:
```
	start := timeutil.Now()
	row, meta := isc.RowSource.Next()
	if row != nil {
		isc.NumRows++
	}
	isc.StallTime += timeutil.Since(start)
```
So a downstream processor should count the time spent in any upstream processor if it's fused.

**Comment by RaduBerinde** [comment]
See the "explain analyze" in this (private) issue: https://github.com/cockroachlabs/support/issues/439

The JoinReader comes after a sorter with 38ms stall time (which we know doesn't produce any rows until the end) but it only has stall time 0.3ms.

Another one here: https://github.com/cockroachlabs/support/issues/443. On node 4, the table reader has 250ms stall time but everything that comes after has <1ms.

**Comment by jordanlewis** [comment]
This stall time has been removed and in general reworked.
