### ISSUE TITLE
colexec: add support for remaining binary operators

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#49463]
This issue tracks adding support for the remaining binary expressions in the vectorized engine. Here is what's left:
- [x] Pow #49465
- [x] Concat #49466
- [x] LShift #49467
- [x] RShift #49468
- [x] JSONFetchVal #49469
- [x] JSONFetchText #49470
- [x] JSONFetchValPath #49471
- [x] JSONFetchTextPath #49472
- [ ] Concat of string and other non-array type #55841 

The second commit from #49761 can serve as a guideline. Here is a rough outline of what's needed to do for each:
- update `execgen.BinaryOpName` to introduce the binary operator
- register the output type of newly supported binary operator in `registerBinOpOutputTypes`
- modify `getBinOpAssignFunc` method of appropriate type customizers to support new `tree.BinaryOperator` type. This step is the most involved and requires translating the code we have in `tree/eval.go` to a similar code to be included in the generated code for the vectorized engine. Note that some types (like `types.Int`) are represented "natively" (i.e. with `int64`) whereas others (like `types.Jsonb`) are represented via datum-backed vectors (i.e. with `tree.Datum`).
- add some tests to `logic_test/vectorize_overloads`.

To provide some context on what's happening behind the scenes for the curious: we have defined template files that are used in conjunction with these type customizers in order to generate type-specific code (similar to what generics are for in other languages). If you take a look at `_SET_SINGLE_TUPLE_PROJECTION` in `proj_non_const_opt_tmpl.go`, this is where `_ASSIGN` (which is a "templated function call") will be replaced by the template code that needs to be added in `getBinOpAssignFunc`. One could look at `proj_non_const_ops.eg.go` (once `cockroach` is built) and at the `_tmpl` file to get some more insight.

Jira issue: CRDB-4225

**Comment by tancredosouza** [comment]
Hi there! Thanks for giving a guideline for how one could approach this.

I had some trouble finding the aforementioned `populateBinOpOutputTypes`. Should that be `registerBinOpOutputTypes` instead? 

Since this is my first time looking at the source code, I'm still getting familiar with where things are.

Thanks! Kind regards,
Tan.

**Comment by yuzefovich** [comment]
> I had some trouble finding the aforementioned populateBinOpOutputTypes. Should that be registerBinOpOutputTypes instead?

Yes, it should be, my apologies. Thanks for pointing this out!
