### ISSUE TITLE
colexec: add support for JSONFetchTextPath binary operator

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#49472]
Add support for `JSONFetchTextPath` binary operator. For more details, see #49463.

Blocked by #49780.

**Comment by Ramez-** [comment]
I would like to work on this one if nobody is working on it.

**Comment by yuzefovich** [comment]
Thanks for the interest, @Ramez-! I'll assign the issue to you.

**Comment by NupurThakur27** [comment]
@yuzefovich and @Ramez- Is anyone working on this issue?
If not I would like to take this one and would like to start with my first contribution here.

**Comment by Ramez-** [comment]
@NupurThakur27  I am working on it

**Comment by haseth** [comment]
I would like to work on this. I am trying to understand the issue and code, will start working on it. I might ask help on Slack channel, if required.

**Comment by yuzefovich** [comment]
@haseth sounds good, I'll assign the issue to you.

**Comment by yuzefovich** [comment]
I think it is currently pretty hard to implement due to some infrastructure limitations between the interactions of datum-backed arguments and non-datum-backed result, so I'm removing "good first issue" label and making the issue unassigned. Apologies for mis-triaging the issue initially.
