### ISSUE TITLE
colexec: add support for JSONFetchValPath binary operator

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#49471]
Add support for `JSONFetchValPath` binary operator. For more details, see #49463.

**Comment by manhhiep92** [comment]
Hi @yuzefovich i would like to look into this issue if no one is working on it. Thanks!

**Comment by yuzefovich** [comment]
@manhhiep92 thanks for the interest, yes, please! I'll assign the issue to you.

**Comment by haseth** [comment]
can you assign this issue to me @yuzefovich? I would like to try my hands on this one.

**Comment by yuzefovich** [comment]
Of course, thanks for taking this on!

**Comment by haseth** [comment]
Hello, this is blocked by #49780. As `JSONFetchValPath` has left operand as `DatumVec` and 2nd operand `DatumVec` as well. 
```
JSONFetchValPath: {
		&BinOp{
			LeftType:   types.Jsonb,
			RightType:  types.MakeArray(types.String),
			ReturnType: types.Jsonb,
			Fn: func(_ *EvalContext, left Datum, right Datum) (Datum, error) {
				return getJSONPath(*left.(*DJSON), *MustBeDArray(right))
			},
			Volatility: VolatilityImmutable,
		},
	},
```

**Comment by yuzefovich** [comment]
@haseth I think you're misunderstanding the limitation described by #49780. Currently we are not able to support a case of `binFn(datumVec, datumVec) = <native type>`, and in this case we have `binFn(datumVec, datumVec) = datumVec` because both `types.Jsonb` and array of strings are represented via a `datumVec`. I believe this issue can be resolved in a manner very similar to how `JSONFetchVal` is supported.
