### ISSUE TITLE
zip: liveness is retrieved twice

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#49520]
A while ago I added a patch to `cockroach debug zip` to ignore decommissioned nodes. For this the command needed to retrieve the liveness data.

I did not see that liveness is already being retrieved earlier in the code.

The result is that `zip` currently retrieves liveness twice, and also populates the liveness JSON twice in the output zip file.

(This is relatively innocuous but wasteful)

The fix is to remove the first retrieval and only keep the second one.

**Comment by cargillb** [comment]
Still very new to Go and cockroachDB but I think I can tackle this (first time contributor). After looking over the code and the diff on what I think is your commit (https://github.com/cockroachdb/cockroach/commit/97812879b0e42f05a9aa4374ce3de9363c8a8c16#diff-f4fdf5d150c8162fc5a1578b91eb6d64), I think it's just removing lines 309-314 from the function runDebugZip? Just hoping to verify before sending the pull request.
![image](https://user-images.githubusercontent.com/65872733/83043590-0e1ea900-a011-11ea-8ac7-394dbf04cc71.png)

**Comment by knz** [comment]
Yes it might be as simple as that - assuming that you ensure that the zip utility still works after that.

**Comment by cargillb** [comment]
I'll do some testing now to see if I can confirm. Thanks for the quick reply.
