### ISSUE TITLE
ui: reorganize table on Nodes page

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#4956]
The table on the Nodes page should have only the following information:

* live bytes + system bytes + intent bytes (just call this “bytes”)
* started at becomes uptime, which is humanized
* total ranges
* client connections
* capacity
* load/CPU (small graph, 10 minutes)
* memory (small graph, 10 minutes)

We're removing a bunch of stuff like node ID and intent bytes and adding a few stats to highlight the most important metrics for a user of the admin UI.

**Comment by mrtracy** [comment]
Assigning to myself: I will get to this immediately after #4465, which is required before fixing this bug properly.
