### ISSUE TITLE
opt: fix estimation of number of values within a histogram bucket range

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#49568]
From https://github.com/cockroachdb/cockroach/pull/48580#issuecomment-632444075:
> How come it's not possible to estimate the number of values within an arbitrary range for string/UUID? Say a bucket looked like this:
> 
> ```
> start: 'bear'
> end: 'bobcat'
> count: 100
> ```
> 
> And the range is ['bluejay' - 'boar'].
> 
> If the string were encoded as sorted key bytes (i.e. the CRDB key representation), then think about each byte as a base(16) number that's zero extended to be the same number of bytes (or treated as a fraction), with common bit prefixes dropped and only, say, 4 total bytes retained (since we don't need a ton of precision).
> 
> ```
> bear    = 62 65 61 72          = 0x62656172000000 = 0x56172000
> bobcat  = 62 6f 62 63 61 74    = 0x626f6263617400 = 0xf6263617
> bluejay = 62 6c 75 65 6a 61 79 = 0x626c75656a6179 = 0xc75656a6
> boar    = 62 6f 61 72          = 0x626f6172000000 = 0xf6172000
> ```
> 
> Then, you can estimate the number of values in the range ['beaver' - 'bee']:
> 
> ```
> (boar - bluejay + 1) / (bobcat - bear + 1) = (0xf6172000 - 0xc75656a6 + 1) / (0xf6263617 - 0x56172000 + 1) = 29.2% = 29.2 rows
> ```
> 
> I haven't considered each data type, but this method would probably work pretty well for many (maybe most/all?) of them, since we've already done the hard work of putting them into a sortable byte format, and most/all types that are uniformly distributed across their domain will also be uniformly distributed across their byte representation.
> 

This issue should cover the work to investigate and implement the above idea. cc @andy-kimball.

**Comment by ArjunM98** [comment]
Hi @rytaft, I’d love to take this on! 

I have a few questions about the implementation of this issue. 

1. For putting the data types in their sortable byte format, can I leverage the functions in [pkg/util/encoding/encoding.go](https://github.com/cockroachdb/cockroach/blob/master/pkg/util/encoding/encoding.go)
2. Is [this](https://www.cockroachlabs.com/docs/stable/data-types.html) the comprehensive list of datatypes I need to incorporate/investigate the effectiveness of this method on? There are a few other data types like the Geography Family, which aren’t listed in the link.

**Comment by rytaft** [comment]
Hi @ArjunM98,
Glad to hear you're interested in working on this!
1. I think you can probably just use `EncodeTableKey` in [pkg/sql/rowenc/column_type_encoding.go](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/rowenc/column_type_encoding.go), which calls the functions in `encoding.go`
2. I would just focus on the types in that function, `EncodeTableKey`. We don't yet allow geography/geometry, json or array to be used in non-inverted indexes, so those are lower priority.

**Comment by ArjunM98** [comment]
Hi @rytaft, 

I had another quick follow up question. In terms of testing, I put all my unit tests into [pkg/sql/opt/props/histogram_test.go](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/opt/props/histogram_test.go). I was looking into the end-to-end testing, and noticed the file: [pkg/sql/opt/memo/testdata/stats/select](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/opt/memo/testdata/stats/select). However, I was having a little trouble deciphering the output outlined below. This is the query that generated the output: `SELECT * FROM data WHERE user_id = '679d3e56-b985-63d2-5442-e4ba7a8479e3'`

```
select
 ├── columns: user_id:1(uuid!null) name:2(varchar) created:3(timestamptz)
 ├── stats: [rows=10.0160321, distinct(1)=1, null(1)=0]
 │   histogram(1)=  0                  10.016
 │                <--- '679d3e56-b985-63d2-5442-e4ba7a8479e3'
 ├── fd: ()-->(1)
 ├── scan data
 │    ├── columns: user_id:1(uuid!null) name:2(varchar) created:3(timestamptz)
 │    └── stats: [rows=10000, distinct(1)=1000, null(1)=0]
 │        histogram(1)=  0                    1                     4998                    1                     4999                    1
 │                     <--- '3b57b3e4-a68a-9b47-2752-e365d7d8954e' ------ '6b49a786-387b-d5a2-6582-4e963eb4d537' ------ 'd9739a48-d5be-9a62-e752-34d877e56ba5'
 └── filters
      └── user_id:1 = '679d3e56-b985-63d2-5442-e4ba7a8479e3' [type=bool, outer=(1), constraints=(/1: [/'679d3e56-b985-63d2-5442-e4ba7a8479e3' - /'679d3e56-b985-63d2-5442-e4ba7a8479e3']; tight), fd=()-->(1)]
```

I was wondering if there is any documentation I could reference to better understand the output above. Specifically, I was confused about the values found in these 2 rows: 

```
├── stats: [rows=10.0160321, distinct(1)=1, null(1)=0]
```
```
 │    └── stats: [rows=10000, distinct(1)=1000, null(1)=0]
```

**Comment by rytaft** [comment]
Hi @ArjunM98, unfortunately I don't think we have documentation that explains that format. But I can just tell you here (feel free to also write comments in the code to improve our documentation!).

The `stats` output you mentioned shows the estimated statistics over the output rows of each relational expression in the query plan. `rows` corresponds to the estimated number of rows. `distinct`, `null` and `histogram` correspond to individual columns or sets of columns, and the numbers correspond to the column ID assigned by the optimizer, which is also printed in the output (see below for more details). So in the example above, we estimate that there are 10000 rows returned by the scan, and ~10 rows returned by the select. `distinct(1)` corresponds to the estimated number of distinct values of the column with id 1, which is `user_id`. `null(1)` is the estimated number of null values of `user_id`, and `histogram(1)` shows a histogram of the non-null values in `user_id`. After the scan, there are 1000 distinct values of `user_id`, and after the select, there is exactly one distinct value, which is `'679d3e56-b985-63d2-5442-e4ba7a8479e3'`.

To find info about the columns, notice the line ` │    ├── columns: user_id:1(uuid!null) name:2(varchar) created:3(timestamptz)`, which shows the columns output by the relational expression, in the format `<column name>:<column ID>(type)`. The type might also include `!null` if we know that the values in that column can never be null. Note that the column ID is assigned by the optimizer on a per-query basis and is unrelated to the column's ID in the database (also note that if a table appears twice in a query, each of the columns will have different IDs in each scan).
