### ISSUE TITLE
cli: make `cockroach node decommission` derive the target node ID from --host

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#49583]
Today `node decommission` requires an explicit list of node IDs on the command line.

It would be good if the command, like `cockroach node drain` and others, when provided no node ID explicitly, would automatically target the node that it's connected to (via `--host`).

**Comment by a-robinson** [comment]
+1 to this, I was gonna open the same request. How to grab the local process's ID in an automated fashion is surprisingly non-obvious. It'd be nice if both `decommission` and `recommission` offered an easy way to target just the process being connected to.

**Comment by ddseanc** [comment]
Could this just be changed to add a `--self` flag that will target the local node ID?  Right now `node decommission` requires a list of node IDs:

```
cockroach node decommission <node IDs> <flags>
```

but it'd be really nice if you could call:

```
cockroach node decommission --self <flags>
```

and have this be a valid invocation that way a node can self-decommission when a shutdown signal is received for a given instance.

**Comment by knz** [comment]
My remaining question is whether an explicit `--self` argument is required.

It seems to me that the _absence_ of any node IDs on the command line would be sufficient signal that the "self" behavior is requested. What do you think?

**Comment by irfansharif** [comment]
(Uneducated) preference for an explicit `--self`, makes it harder to get it wrong. I can imagine unintentionally not setting node IDs in bash scripts or the like, which would then go do something unintended.

**Comment by knz** [comment]
gotcha, makes sense.
