### ISSUE TITLE
explain analyze not showing rows read from computed column full table scan

### ISSUE THREAD

**Issue by SpicyThrow** [cockroachdb/cockroach#49609]
I have a table that includes the following columns: id and JSON
I create a computed column from the JSON column called Serial_Number and cast it as an INT.
I query on the new column for Serials between 10,500 and 11,000
```
select id, serial_number from vehicles where serial_number <= 11000 and serial_number
> 10500;
```
When I use explain on this query it notes a full table scan:
```
 tree |    field    |                     description
+------+-------------+------------------------------------------------------+
       | distributed | true
       | vectorized  | true
  scan |             |
       | table       | vehicles@primary
       | spans       | FULL SCAN
       | filter      | (serial_number <= 11000) AND (serial_number > 10500)
(6 rows)
```
When I use explain analyze on this query I get the following output, image attached.
It's not clear from the explain-analyze that a full table scan is happening. 
![Screen Shot 2020-05-26 at 3 25 04 PM](https://user-images.githubusercontent.com/58006978/83065704-ea1f8f80-a031-11ea-964c-d924baf7c8f9.png)
It does say "Spans" which apparently infers a full table scan, but there's no clear full row count.

**Comment by RaduBerinde** [comment]
I thought we showed the number of table rows read, is this no longer the case with vectorized?

**Comment by yuzefovich** [comment]
Yeah, the vectorized engine wasn't showing that info, thanks for pointing this out! I've actually just merged a statistic for number of bytes read to the diagrams from the vectorized engine and will open up a PR to add the number of rows read shortly as well.
