### ISSUE TITLE
stats: potential stats job crashes when coordinating with schema changes

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#49608]
The SQL stats collector jobs store the table descriptor that the job was started with in the job details. This could potentially lead to problems during stats job execution, but only under seemingly rare circumstances. What I imagine is as follows:
* A stats job starts on a node, and wants to collect stats on table `t`, columns (`a` and `b`).
* The node the job is running on dies, and the job is picked up by another node.
* In the time that the job is not running, a schema change on `t` deletes `b`.
* The stats job starts up again, but thinks the table still has column `b`, and throws some sort of error while reading table data.

Jira issue: CRDB-4214

**Comment by rohany** [comment]
cc @rytaft

**Comment by rytaft** [comment]
I haven't seen this happen in practice. Closing.
