### ISSUE TITLE
sql: add tracing to sql/executor to capture retries

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#4962]

**Comment by mjibson** [comment]
@dt should this be closed now since the PR got merged?

**Comment by tschottdorf** [comment]
I don't think tracing captures retries yet. It sits inside debugNode but needs to be lifted above into executor.

**Comment by petermattis** [comment]
@andreimatei Is there anything else to do here?

**Comment by andreimatei** [comment]
We have fixed this - there's now root spans that contain all the retries.
