### ISSUE TITLE
sql: column padding not preserved like in postgres

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#49639]
tldr: postgres preserves the right-padding of padded columns in some cases, CockroachDB does not.

Start with the following SQL

```
> CREATE TABLE t(x CHAR(8));
> INSERT INTO t(x) VALUES ('hello');
```

The run `SELECT x FROM t` in crdb and pg.

PostgreSQL:

```
{"Type":"DataRow","Values":[{"text":"hello   "}]}
```

CockroachDB:

```
{"Type":"DataRow","Values":[{"text":"hello"}]}
```

(I found this discrepancy when running the `row_description` pgtest in both crdb and pg)

It's hard to see in a SQL shell because the whitespace does not show on the screen, but still.

Interestingly, the following query behaves differently:

```
SELECT ':' || x || ':' FROM t
```

This returns both a short `:hello:` in both pg and crdb.

**Comment by jordanlewis** [comment]
Postgres CHAR types have fixed-width display: https://www.postgresql.org/docs/9.1/datatype-character.html

This could be a good welcome-back issue for @arulajmani.

**Comment by smahable** [comment]
postgres 13.4 on aws aurora is having this problem.  

column is 30 char. using length shows actual length 
also   '['||c||']' shows no right padded string ...

**Comment by knz** [comment]
@smahable can you explain more? What problem still exists?
