### ISSUE TITLE
Provide a deployment Docker image based on RedHat UBI

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/cockroach#49643]
This is a follow-on to #41390.  Right now, we ship a Debian-based image.  It would be helpful for some operators to also supply a UBI-based docker image to DockerHub.

**Comment by bobvawter** [comment]
See also comments from Ben in https://github.com/cockroachdb/cockroach/pull/49593#issuecomment-634823368

**Comment by bdarnell** [comment]
Not "also" - the redhat UBI image should *replace* the debian-based one; there's no reason to offer two.
