### ISSUE TITLE
Unexpected transaction behavior

### ISSUE THREAD

**Issue by steeling** [cockroachdb/cockroach#49673]
```
var storeURI = flag.String("store-uri", "postgresql://root@localhost:26257?sslmode=disable", "URI pointing to a Cockroach node")
var db *sql.DB

type queryable interface {
    QueryRowContext(ctx context.Context, query string, args ...interface{}) *sql.Row
    QueryContext(ctx context.Context, query string, args ...interface{}) (*sql.Rows, error)
    ExecContext(ctx context.Context, query string, args ...interface{}) (sql.Result, error)
}

func mustBootstrap(ctx context.Context) {
    var err error
    db, err = sql.Open("postgres", *storeURI)
    if err != nil {
        panic(err)
    }
    fmt.Println("uri: ", *storeURI)

    db.ExecContext(ctx, `DROP TABLE fake_table;`)
    _, err = db.ExecContext(ctx, `CREATE TABLE fake_table (id VARCHAR PRIMARY KEY);`)
    if err != nil {
        panic(err)
    }
}

func mustInsert(ctx context.Context, q queryable, id string) {
    _, err := q.ExecContext(ctx, fmt.Sprintf("INSERT INTO fake_table (id) VALUES ('%s')", id))
    if err != nil {
        panic(err)
    }
}

func mustSearch(ctx context.Context, q queryable) int {
    row := q.QueryRowContext(ctx, `SELECT COUNT(*) FROM fake_table`)
    var ret int
    err := row.Scan(&ret)
    if err != nil {
        panic(err)
    }
    return ret
}

func main() {
    ctx, cancel := context.WithTimeout(context.Background(), time.Second)
    defer cancel()
    mustBootstrap(ctx)
    tx, err := db.Begin()
    if err != nil {
        panic(err)
    }
    mustInsert(ctx, tx, "first") //#1
    mustInsert(ctx, db, "second") //#2

    count := mustSearch(ctx, tx) //#3
    fmt.Println(count)

    if err := tx.Commit(); err != nil { //#4
        panic(err)
    }

    count = mustSearch(ctx, db)
    fmt.Println(count)
}
```

The above code inserts:

1. Inserts a row in a txn
2. Inserts a row outside of the txn
3. Queries for all rows inside the txn.
4. Commit the transaction

Either #3 should return the results of both 1 & 2, or either #2 should fail or #4 should fail.

Doing the same on postgres does the former. Is there a transaction setting I'm missing here? 

How are we supposed to do things like limit the number of rows belonging to a user? Typically I would do:

BEGIN;
SELECT COUNT(*) FROM <table> WHERE user = $USER;
in code: if count > max_allowed return error
INSERT INTO <table> ....
COMMIT

The above code example shows that this does not work.

Jira issue: CRDB-4210

**Comment by steeling** [comment]
Additionally, it looks like CRDB hangs when doing the same with 2 txn's:


```

func main() {
    ctx, cancel := context.WithTimeout(context.Background(), time.Second)
    defer cancel()
    mustBootstrap(ctx)
    var count int
    tx1, err := db.Begin()
    if err != nil {
        panic(err)
    }

    tx2, err := db.Begin()
    if err != nil {
        panic(err)
    }

    mustInsert(ctx, tx1, "first")
    mustInsert(ctx, tx2, "second")

    count = mustSearch(ctx, tx1)
    fmt.Println(count)

    count = mustSearch(ctx, tx2)
    fmt.Println(count)

    if err := tx1.Commit(); err != nil {
        panic(err)
    }

    if err := tx2.Commit(); err != nil {
        panic(err)
    }
    count = mustSearch(ctx, db)
    fmt.Println("final", count)
}
```

**Comment by lucy-zhang** [comment]
Moving this to appdev in case this is a driver issue, cc @rafiss for triage.

@steeling Would you mind reporting exactly what the unexpected behavior is? It's unlikely we'll be able to run this code in a way that reproduces what you're seeing.

**Comment by steeling** [comment]
re: the second comment it looks like the hanging was a transient issue. I got it to work while using 2 transactions, and I see the corresponding txn retry error.

I'm still concerned with the first comment, since CRDB says that even individual statements run in an implicit txn, I would expect the code to have a conflict, but it succeeds and even prints a value I wouldn't expect.

**Comment by lucy-zhang** [comment]
> I would expect the code to have a conflict, but it succeeds and even prints a value I wouldn't expect.

What value did you expect, and what value did you get? Based on looking at the code, I'd probably expect the result of `select count(*)` to be 1. The first open transaction isn't guaranteed to see the result of the second concurrent transaction, and ultimately the transactions are serialized such that the second transaction commits at a higher timestamp than the first. https://www.cockroachlabs.com/docs/stable/transactions.html and https://www.cockroachlabs.com/docs/stable/demo-serializable.html might be helpful.

> How are we supposed to do things like limit the number of rows belonging to a user?

If you want to ensure that every write preserves the invariant, you'll have to do `if count > max_allowed return error` in every write transaction.
