### ISSUE TITLE
database: lose gossiped system config dep in Cache

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#49692]
@ajwerner you probably have this tracked somewhere more generally in avoiding the system config gossip altogether, if so please close this issue but make sure you have A-multitenancy-blocker on the other one. Thanks!

**Comment by ajwerner** [comment]
This should be resolved as fallout of #47149 `sql: general descriptor leasing` though may require an additional PR to gate the construction of the database.Cache on the cluster version. Discussed this with @lucy-zhang offline this morning. If we need something more pressing, please note it here.

**Comment by ajwerner** [comment]
As I understand it this is actively in progress by @lucy-zhang. The goal is to make it such that we can start the server without gossip if the cluster version is sufficiently high.

**Comment by nvanbenschoten** [comment]
This is still in progress, but @ajwerner said that we can simply disable the database cache for secondary tenants even before the cache itself is removed for the system tenant.

**Comment by tbg** [comment]
Removing blocker label since now it's only the system tenant that uses gossip.

**Comment by lucy-zhang** [comment]
Closed by #52975.
