### ISSUE TITLE
schema: lose gossiped system config dep in schemaChangeGCResumer

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#49691]
@ajwerner you probably have this tracked somewhere more generally in avoiding the system config gossip altogether, if so please close this issue but make sure you have A-multitenancy-blocker on the other one. Thanks!

**Comment by ajwerner** [comment]
This in many ways duplicates https://github.com/cockroachdb/cockroach/issues/49445.

**Comment by nvanbenschoten** [comment]
> This in many ways duplicates #49445.

Yes, it's a duplicate. I'm going to close this one to avoid the noise.
