### ISSUE TITLE
changefeedccl: Introspection into errors we're retrying on, control over alerting behavior

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#49708]
**Is your feature request related to a problem? Please describe.**
Today, our changefeeds effectively retry forever on retriable errors, without any alerting. Furthermore, when they fail, they fail silently (e.g. no alerts sent anywhere). This is bad if the Kafka sink dies or there are network issues--they could retry forever until someone else noticed something was wrong.

**Describe the solution you'd like**
Some combination of:
- Alerting when a changefeed fails / falls behind / can't connect to sink/registry for X time/retries
- Thresholds for retries before failing
- Introspection into the type of error that's occurring -- some way to inspect Changefeed specific errors through UI, `SHOW`, other command

Epic CRDB-2365

Jira issue: CRDB-4205

**Comment by mwang1026** [comment]
We actually have a Prometheus counter for `changefeed_error_retries`

What we don't have is, if you don't have SSH access / access to logs, introspection into that error. This can happen if you're using a service like Cockroach Cloud.

Reframing this to be introspection about those errors.

**Comment by miretskiy** [comment]
retry behavior changed recently; we export retry counters, per changefeed even; plus @jayshrivastava is adding monitoring on paused jobs.  The combination of the above addresses this issue.
