### ISSUE TITLE
Running IMPORT best practices doc

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#49702]
We need to create a doc describing best practices on running IMPORTs into CockroachDB
faster.

I have started a doc to put in things our users should consider doing in order to have
decent performance when running imports.
https://docs.google.com/document/d/1P9kQwMUOZT1mb_LLdqR2pGIDmKNOA0Cm_LNeUu8hiVY/edit#

**Comment by lnhsingh** [comment]
Closing this issue in favor of https://github.com/cockroachdb/docs/issues/7447!
