### ISSUE TITLE
TPC-C benchmark with 10k warehouses does not work

### ISSUE THREAD

**Issue by y-sira** [cockroachdb/cockroach#49718]
**TPC-C benchmark with 10k warehouses does not work**

When I tried to reproduce the TPC-C benchmark results with a 10k warehouse on the GCP Compute Engine according to the official documentation, CockroachDB faced an overload and the benchmark program stopped working.

**To Reproduce**

Create 15 of N2 custom instances with 16 vCPUs, 32 GB memory,  and 100 GB SSD.
Then follow the official document.

https://www.cockroachlabs.com/docs/stable/performance-benchmarking-with-tpc-c-10k-warehouses.html

**Expected behavior**

In Step 5, I got:

```
$ ulimit -n 20500 && ./workload run tpcc --partitions 5 --warehouses 10000 --duration 1m --ramp 1ms "postgres://root@n2-1:26257?sslmode=disable"
Initializing 20000 connections...
Error: read tcp XXX.XXX.XXX.XXX:56059->XXX.XXX.XXX.XXX:26257: read: connection reset by peer
```

**Additional data / screenshots**

We discuss on Cockroach's community Slack.
Jordan suggests me to use a load balancer and I tried to use it.
However, I got a problem...

```
$ ./workload run tpcc --partitions 5 --warehouses 10000 --duration 1m --ramp 1ms $(cat ad
drs)
Initializing 20000 connections...
Initializing 100000 workers and preparing statements...                          
_elapsed___errors__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
...
Error: error in payment: ERROR: result is ambiguous (intent missing and record aborted) (SQLSTATE 40003)
```

I notice that the Replication Queue does not get to 0 after waiting for 20 minutes.

<img width="984" alt="Screen Shot 2020-05-30 at 6 08 45" src="https://user-images.githubusercontent.com/1114146/83305670-245c7d00-a23c-11ea-8f33-909014e57316.png">

According to the official document, this will likely take 10s of minutes.

**Environment:**
 - CockroachDB version: 20.1.0
 - Server OS: Ubuntu 20.04
 - Client app: `cockroach workload`

**Additional context**

**Comment by irfansharif** [comment]
+cc @jordanlewis, seems you've looked a bit at this earlier.

> Error: error in payment: ERROR: result is ambiguous (intent missing and record aborted) (SQLSTATE 40003)

@y-sira: We should update our docs around this, but typically you want to run `workload run tpcc` with the `--tolerate-errors` flag. That particular error (at a quick glance) is an expected one when running in distributed environments.

**Comment by ajwerner** [comment]
I might start by running the workload with a smaller warehouse count to try to differentiate between a resource exhaustion problem vs some other configuration issue. 

Consider setting the ‘active-warehouses` flag to something like 1k and then 5k. If those both work then there may be a resources problem.

**Comment by knz** [comment]
@y-sira have you tried running with `--tolerate-errors`? I filed #49865 to enhance the `workload` program to tolerate these errors automatically, but until then you can add this flag manually.

Also did you see the comment by @ajwerner ? What are your findings since then?

**Comment by irfansharif** [comment]
@knz: this discussion was carried over in slack, and looks like it's still active. I'm going to (timidly) close this out given that what was preventing the 10k run was understood.
