### ISSUE TITLE
changefeedccl: cope better with slow sinks and high flush rates

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#49720]
When no `resolved` parameter is passed to a changefeed, the changefeed defaults to flushing the sink every `200ms` (PollInterval/5) [[1]]. We anticipate that this was a bad choice, at least for the HTTP sink. This can be especially problematic if flushing the sink takes, on average, more than this interval. Forgetting the bad default above, a client may request a high frequency of flushes with the `resolved` parameter. If the sink can't keep up, we'll slowly fall behind. 

We should do something to realize we're falling behind or are quite behind and swallow some of the checkpoints from forcing a flush. 

[1]: https://github.com/cockroachdb/cockroach/blob/6123c0c73ff0eea223cfd25e1e557648413126f8/pkg/ccl/changefeedccl/changefeed.go#L313-L337

Please describe the issue you observed, and any steps we can take to reproduce it:

Jira issue: CRDB-4202

**Comment by ajwerner** [comment]
This issue is dramatically exacerbated by large numbers of ranges. Each range will independently send checkpoints at a frequency which is roughly a function of `kv.closed_timestamp.target_duration` * `kv.closed_timestamp.close_fraction` which, by default, is 600ms. The situation is even worse if transaction durations start to sneak above that `target_duration` as we'll emit checkpoints whenever the resolved timestamp moves which can happen upon intent resolution.

In short, even if we do a better job not flushing when we're falling behind (this issue) and use higher `resolved` intervals leading to these checkpoints no-oping (https://github.com/cockroachdb/cockroach/pull/49770), we're still going to potentially produce and process a very large number of these checkpoints in normal operation. Maybe that's okay but I suspect we need to study it. One potentially good idea is to rate limit the production of such checkpoints in one form or another. There are tradeoffs to different rate-limiting approaches. Something simple like not sending them more rapidly than the closed interval makes sense but even then, with large numbers of ranges, we could produce serious volume. 160k checkpoints/s is a lot to process if you have, say 100k ranges and the default settings. One option to ensure that the whole thing can scale would be to rate limit the production of resolved timestamps globally for a node. It means that if you'd produce too many checkpoint events then your resolved timestamps will get more spread out than you might have liked but I think this is a pretty reasonable approach. Probably we don't want any node sending more than something like 10k checkpoints on all rangefeeds combined per second.

The above suggestion wouldn't solve the problem of sinks falling behind at all, it just might mitigate one of the reasons why sinks fall behind. 

I think these two suggestions, taken together would be a solution:

1) Cap the rate at which rangefeeds globally can emit checkpoints

The implementation will need to take care to ensure that if the rate is exceeded the checkpoints become further spaced out in time and cover longer time intervals

2) Ignore flushing due to frontier moving if the movement is not catching up to real time. 

More notes:

I've created a table with a relatively small amount of data but installed 100k manual splits. I then attempt to create a changefeed over that and it just gets totally hosed. Perhaps this is extreme but we should be able to create changefeeds over very large idle tables. The fact that we need more than one goroutine per range is relatively problematic too. Doing something better there however is pretty hard to think about. gRPC mandates a goroutine per API call as I understand it. That'd mean we'd need to multiplex multiple rangefeeds over a single stream which seems pretty, well, painful. I'm going to just encourage us to not have more than 10s of thousands of ranges per node.

I have in the past argued that if we ever implement low-latency changefeeds where there are many changefeeds over the same range that there could be some value in having a join protocol to join rangefeeds over the same data but that's a whole different discussion and is only worth talking about once we have sub-table changefeeds with low latency emit times (then you could imagine utilizing changefeeds for real-time events).

**Comment by miretskiy** [comment]
This is pretty stale; closing for now, but feel free to reopen.
