### ISSUE TITLE
sql: vectorized EXPLAIN ANALYZE diagram should show number of table rows read

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#49760]
The EXPLAIN ANALYZE diagram shows the number of rows output by every processor. But if we have a TableReader with a filter, there is no way of knowing how many rows we actually had to read before filtering. We should include that information.

**Comment by RaduBerinde** [comment]
Ah, I notice a `selectivity` field, maybe that is useful to determine this? (even if it is, I believe it only shows up when vectorizing)

**Comment by asubiotto** [comment]
> The EXPLAIN ANALYZE diagram shows the number of rows output by every processor

Only with vectorized. In row execution, we only show the number of rows read. `selectivity` is sort of useful in determining this, but tuples might have been selected out by prior stages and there is no way of knowing.

Agreed that we should add this information.

**Comment by asubiotto** [comment]
@helenmhe a good starting point is to look at `NewVectorizedStatsCollector` which is what we use to collect stats in vectorized flows.
