### ISSUE TITLE
ui: how to denote access to some, but not all, data on Databases page?

### ISSUE THREAD

**Issue by celiala** [cockroachdb/cockroach#49782]
**Problem Statement**

While implementing #48152, we realized that on the Databases page we want to update the user experience for users that have access to some, but not all, data.

Specifically, admin users see all data, and all other users currently see an "insufficient rights to view this resource" message:

<img width="550" src="https://user-images.githubusercontent.com/3051672/83472593-a673be00-a455-11ea-906a-1ee922f215d8.png">

While this message makes sense if a user has no privileges, if a non-admin user has access to _some_ data, it might be confusing for them to see their database data, but also see the generic "insufficient rights" message:

<img width="550" src="https://user-images.githubusercontent.com/3051672/83472561-8f34d080-a455-11ea-8b64-bd2cf9c581ac.png">

**Proposal**

For users with _some_ privileges, we may want to update these states so it doesn’t make the user feel like they did something wrong (visual and wording), while telling the user there is some data they don’t have access to.

**Additional notes**

* Design/messaging should be implemented for both the table and grants views, since both are restricted from accessing.
* Summarized from [Slack thread](https://cockroachlabs.slack.com/archives/GNDPH06E9/p1591048638020700?thread_ts=1591026634.003500&cid=GNDPH06E9)

gz#5104

Jira issue: CRDB-4196

**Comment by celiala** [comment]
Hi @Annebirzin - created an issue to capture our Slack thread. Feel free to tweak/correct as needed!

**Comment by Annebirzin** [comment]
@celiala I've created designs for the following permission states. ([Figma file here](https://www.figma.com/file/wLjM816v8wwesuIDkar9oN/obsrv_admin-ui-permissions?node-id=1%3A10) and screenshots below)

- user has **some** access to tables
- user has **some** access to grants
- user has **no** access to tables
- user has **no** access to grants 

cc @taroface for any feedback on the messaging for these states, and @piyush-singh. Let me know any feedback.

![Databases_001](https://user-images.githubusercontent.com/51920721/86139933-4dcc2b00-babe-11ea-9db2-8ee7a50e451e.png)
![Databases_002](https://user-images.githubusercontent.com/51920721/86139935-4e64c180-babe-11ea-80f7-2720bf68af46.png)
![Databases_003](https://user-images.githubusercontent.com/51920721/86139937-4e64c180-babe-11ea-8fb7-abcde9451981.png)
![Databases_004](https://user-images.githubusercontent.com/51920721/86139938-4e64c180-babe-11ea-9ae1-dcdbba5710c4.png)

**Comment by taroface** [comment]
Copy looks good! See https://github.com/cockroachdb/cockroach/issues/50360#issuecomment-652565756
