### ISSUE TITLE
colexec/opt: pull decision to vectorize out of the execution engine

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#49795]
Currently, the decision of whether or not to vectorize happens at execution time. The gateway node does a check to see if each node's flow is supported: https://github.com/cockroachdb/cockroach/blob/1be1ec0618ec0db42bd633517ad7e16cc32225f8/pkg/sql/distsql_running.go#L171 and sends it out if so. This succeeds even if we don't support an operator in the strictest sense of the word: the row execution processor gets wrapped instead. The only failure that happens due to an unsupported component is if we encounter non-streaming operators with `vectorize=201auto`, otherwise it is due to incorrect plan setup.

We need to figure out how to lift this decision up to the optimizer to be able to make better decisions about whether it makes sense to vectorize a plan or not.

Jira issue: CRDB-4191

**Comment by yuzefovich** [comment]
We have chosen a somewhat different approach - ensuring that the overhead of the vectorized engine is low enough that it's not worse than the row-by-row engine even for the queries that process few rows, thus, I don't think that we'll be pulling out this decision from the execution into the optimizer.
