### ISSUE TITLE
Grant read-only teamcity access to Keith Hughes (SRE contractor)

### ISSUE THREAD

**Issue by joshimhoff** [cockroachdb/cockroach#49803]
GitHub ID: https://github.com/kmhughes. Let me know if you need anything else. This person needs read-only access to CC teamcity also, but IIUC that's the same as CRDB teamcity.

**Comment by jlinder** [comment]
It is indeed the same TeamCity instance as CRDB. 

I added him to a new group `Managed Service Read Only` with `Project viewer` capabilities to the `Internal / Managed Service` project and sub-projects. He should be good to go. Please confirm he has the needed access.

**Comment by joshimhoff** [comment]
Looks good thx!
