### ISSUE TITLE
CDC sink: Apache Pulsar

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#49805]
**Is your feature request related to a problem? Please describe.**
Apache Pulsar is an open-source distributed pub-sub messaging system originally created at Yahoo and now part of the Apache Software Foundation. CRDB doesn't support this sink natively.

**Describe the solution you'd like**
Native support for publishing to Apache Pulsar

Jira issue: CRDB-4189

**Comment by tspannhw** [comment]
If anyone needs testing, I am at StreamNative and can provide some testing.
