### ISSUE TITLE
sql: allow for altering column families of existing columns

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#49817]
John asked if a default (1 column family) table be altered to have multiple column families after creation as the only examples we provide in the docs are when adding columns to a table. 

Related question: Can a column be moved from one family to another in the table?

I think we want to support a syntax along the lines of:

For adding to a new family:
```SQL
ALTER TABLE test ALTER COLUMN data2 BYTES CREATE FAMILY f3;
```
For adding to an existing family
```SQL
ALTER TABLE test ALTER COLUMN name STRING FAMILY f1;
```

Jira issue: CRDB-4187

**Comment by rohany** [comment]
This seems like another application of the computed column swap we have been doing.

**Comment by jordanlewis** [comment]
cc @lucy-zhang @ajwerner - here's another example of this kind of thing that we could use a more robust base for.
