### ISSUE TITLE
sql: UNSPLIT ALL does not work on tenants

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#49828]
It relies on `crdb_internal.ranges_no_leases` which will likely never be made available to tenants. It's a globally broadcasting expensive RPC. If we want to restore this functionality on tenants, we need a more direct way to read the range descriptors for this tenant and to act on them. Shouldn't be too hard.

https://github.com/cockroachdb/cockroach/blob/f618c80c2fde4e2d7ff3715f3753801919f16ef6/pkg/sql/unsplit.go#L93

cc @asubiotto

Jira issue: CRDB-4185

Epic CRDB-16746

**Comment by tbg** [comment]
Oh actually `ranges_no_leases` just scans the meta kvs, so it's fine (it will still fail, but can be fixed by inserting the tenant's bounds, which is easy). So less to do here yet than I thought.

**Comment by ecwall** [comment]
Completed in https://github.com/cockroachdb/cockroach/pull/97717
