### ISSUE TITLE
sql: selecting ID from `system.descriptor` fails

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#49846]
Due to the way that `system.descriptor` is managed, selecting just the ID column from `system.descriptor` will fail:

```
root@127.0.0.1:63116/movr> select id from system.descriptor where id > 50;
  id
------
  51
  52
  53
  54
  55
  56
  57
  58
(8 rows)
Time: 1.019ms
root@127.0.0.1:63116/movr>
```

```
root@127.0.0.1:63116/movr> select id from system.descriptor where id = 51;
  id
------
(0 rows)
Time: 803µs
root@127.0.0.1:63116/movr>
```

The cause of the problem is the limited column family scanning logic. This becomes more clear when we see an explain, which shows us only scanning the first family of the table.
```
root@127.0.0.1:63116/movr> explain select id from system.descriptor where id = 51;
  tree |    field    |    description
-------+-------------+---------------------
       | distributed | false
       | vectorized  | false
  scan |             |
       | table       | descriptor@primary
       | spans       | /51/0-/51/1
(5 rows)
Time: 759µs
root@127.0.0.1:63116/movr>
```

This is a problem for `system.descriptor`, because the sentinel k/v for family 0 is never written! This can be observed in the write paths for when descriptors are written to disk. The `system.descriptor` table is treated as a pure k/v table internally, so these sentinel keys that are needed are never written. This is only a problem when selecting the ID by itself -- once the other column is requested, a full scan of the row is performed.

Jira issue: CRDB-4182

**Comment by yuzefovich** [comment]
fixed by #58659
