### ISSUE TITLE
config: rework zone configs structure for multi-tenancy

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#49854]
https://github.com/cockroachdb/cockroach/pull/49784 collapsed all zone configs for secondary tenants down to a single pseudo "tenants" config. This is a short term solution to get zone configs and their interaction with SQL working for now. In the long-term, we'll need a new way for tenants to configure their data placement / retention policies. This will likely require us to rethink the zone config data model.

**Comment by vy-ton** [comment]
cc @ajstorm @awoods187 for multi-region triage

**Comment by irfansharif** [comment]
Closing in favor of #67679.
