### ISSUE TITLE
ERROR: proto: wrong wireType = 0 for field UDTMetadata

### ISSUE THREAD

**Issue by kocoten1992** [cockroachdb/cockroach#49856]
**Describe the problem**

Got this error when running a query
`ERROR: proto: wrong wireType = 0 for field UDTMetadata`

**To Reproduce**

```
root@:26257/mydatabase> select * from accounts;
ERROR: proto: wrong wireType = 0 for field UDTMetadata
```

What I did was using latest binary (build from master), stop and start cockroachdb, then I notice this error.
I've try to change back to old binary file, but it said version are not compatible anymore.
My guess is the data somehow.. got corrupted ?

**Environment:**
```
Build Tag:    fd1bccf
Build Time:   2020/06/03 23:00:03
Distribution: CCL
Platform:     linux amd64 (x86_64-pc-linux-gnu)
Go Version:   go1.13.9
C Compiler:   4.2.1 Compatible Clang 3.8.0 (tags/RELEASE_380/final)
Build SHA-1:  fd1bccfd20a06c40ec04a893ff6837c3905bf86a
Build Type:   development
```

I do have backup, but if is there any other way..

P/s: hi @rohany , saw a few commit related to UDT

**Comment by rohany** [comment]
Hi @kocoten1992, we have been changing around some protobuf representations of structs in the last few weeks (see https://github.com/cockroachdb/cockroach/pull/49678#discussion_r432803494), as we don't offer any guarantees about backwards compatibility between different builds of master between releases. It's possible that you had some data that was serialized with a slightly different internal representation that was changed. I'm not sure there is much you can do other than restoring from your back up.

Did you have any tables with user defined types (enum types)? Even if not, I think it is possible for persisted data before some protobuf changes to throw errors when used with a build after those changes have landed.
