### ISSUE TITLE
workload: should tolerate 40003 ambiguous error without `--tolerate-errors`

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#49865]
It's expected that CockroachDB returns 40003 sometimes - ambiguous errors are a staple of distributed systems.

However today this error causes the `workload` program to stop completely.
It's only possible to overcome if `--tolerate-errors` is passed.

Arguably `workload` should be able to proceed even when it encounters 40003 errors.

@nvanbenschoten do you agree?

**Comment by nvanbenschoten** [comment]
When we talked about this before, I believe the conclusion was that we should add a second flag to `workload` to ignore only ambiguous errors. There are certainly cases where we expect these ambiguous errors, but I don't think we should ignore them in the cases that we don't. For instance, we probably shouldn't swallow them when not performing chaos.

So concretely, the idea was to add a `--tolerate-ambiguous-errors` flag to `workload`.

How does that sound to you?

**Comment by irfansharif** [comment]
#50873 is another test being plagued by this. `--tolerate-ambiguous-errors` sounds fine to me.

**Comment by knz** [comment]
@nvanbenschoten when we discussed this earlier you wrote "we probably shouldn't swallow them when not performing chaos."

Now I've added the flag in #52555 and I was looking into adding it to the relevant tests. I'm hitting two roadblocks:

1. I see that the `tpcc ... chaos=true` test already runs with `--tolerate-errors`. This means that regardless of #52555 we should not be hitting ambiguous errors in that test. Yet, it fails (#51272). How to explain that?

2. the other tests that have failed with ambiguous commit errors have been `alterpk-tpcc`, `drop/tpcc` and `tpcc/{mixed-,}headroom`. None of them are running chaos restarts, so I'd argue that none of them are expecting ambiguous commit errors (by your previous argument). What do we do about those?

It seems to me that the two situations are radically different.

Situation (1) would suggest a problem in the test runner, that the flag `--tolerate-errors` is not passed when it should or not taken into account.

Situation (2) would suggest that ambiguous commit errors are more prevalent than we thought and would occur "under normal circumstances", not just chaos. I am not exactly surprised by this (after all, any test cluster could legitimately experience a network blip) but we still need to decide what we want to do with it. What do you think?

**Comment by nvanbenschoten** [comment]
> Situation (1) would suggest a problem in the test runner, that the flag --tolerate-errors is not passed when it should or not taken into account.

Agreed. We shouldn't be seeing ambiguous errors at all when passing `--tolerate-errors`. Thee's something to investigate here. I'd suggest locating the error propagation path. It might be off the path that this `--tolerate-errors` flag is applied to.

> Situation (2) would suggest that ambiguous commit errors are more prevalent than we thought and would occur "under normal circumstances", not just chaos. I am not exactly surprised by this (after all, any test cluster could legitimately experience a network blip) but we still need to decide what we want to do with it. What do you think?

Two of the three of those are "intent missing and record aborted" ambiguous errors. Those can happen under "normal" circumstances (with a little overload) so they are expected to some degree. However, we know how to eliminate them, which is being tracked in https://github.com/cockroachdb/cockroach/issues/52566 and may see some attention from @andreimatei soon.

In general, I'd like to try hard to avoid ignoring errors in these tests and instead dig into why we're seeing errors when they do pop up. We've learned over the past few years that regardless of how justified an error is, it will confuse users and turn into a support escalation if ends up in a client application, so we should have a high bar for any errors that we permit in our own testing.

**Comment by andreimatei** [comment]
#53156 tries to address the some the cases Nathan was saying above that we can handle better. That might change the calculus on whether we want the `workload` tool to ever swallow ambiguous errors.

**Comment by knz** [comment]
Closing as per this comment by Nathan.

https://github.com/cockroachdb/cockroach/pull/52555#issuecomment-671402994
