### ISSUE TITLE
ui: Add simple dropdown for graph time interval

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#4986]
Let's have a global value for time intervals and control it via a dropdown. I think it makes sense to supply the following intervals:

Last 10 minutes (default)
Last hour
Last day
Last week
Last month
All time

**Comment by spencerkimball** [comment]
Is this done?

**Comment by maxlang** [comment]
The timescale selector was added, but it's still slow for longer periods of time, so we're still missing 1 week+.

We could close this and open a more specific issue - I'm not sure which you prefer.

**Comment by maxlang** [comment]
For the record, this is blocked on #4986.

**Comment by tamird** [comment]
This is blocked on itself?

**Comment by maxlang** [comment]
Whoops, I meant #7100

**Comment by mrtracy** [comment]
This is completed.
