### ISSUE TITLE
testing: stop auto-filing github issues on every test failure

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#49881]
Discussed with @petermattis today; based on my review of 200-300 issues from the past few months the large majority of auto-filed issues are either:

- duplicate of each others
- accidental infra misconfigs
- "the internet is broken today" - an external service is misbehaving
- cloud resource shortage

I think we have too much noise and accordingly spend too much time triaging.

Instead I propose tracking test failures differently. 

The first step is to ensure that we keep a history of all the results for each test on each release branch. (I believe Teamcity already tracks this for us, but I don't know where. We need that as first step.)

Then apply the following heuristics at the end of every test period (daily or every 6 hours for CI tests; weekly for daily tests), in order:

1. if there's an upsurge in the number of test failures occurring simultaneously (in the same run) compared to the previous period, like 20% or more tests failing at once that didn't fail before:
 
   - file a single issue to investigate this as "Major regression - possible infrastructure error". 
   - assign to the dev inf team for triage. 
   - then exclude all the tests marked in this way from the next heuristics.

2. if multiple (one or more) tests in the same go package have failed two or more times *consecutively* during the period, and they always failed "together", and they hadn't failed in the previous period:

   - file a single issue with title "test failed" /label C-test-failure for the entire group.
   - assign to the project corresponding to that package + ping the team
   - then exclude the tests from the next heuristics. 

   Note that this heuristic can apply to groups formed of just 1 test in a package.

3. if a single test has failed two or more times *with intermediate successes* (ie. it flakes), 

   - file an issue with title "flake" / label C-test-flake
   - assign to the project corresponding to the test's package + ping the team
   - Then exclude it from the next heuristics.

4. if a test has failed once, then has succeeded forever since (with at least two successes until the end of the period), then
 
   - file an issue with title/label "odd failure" and C-investigation
   - assign to the project corresponding to the test's package + ping the team

I'm expecting step (1) to shield us from 90% of failures and duplicates already.

Then step (2) will shield us from most the remaining duplicates.

Then steps (3) and (4) will allow us to prioritize triaging / fixing the different types of failures differently.

Epic CRDB-10439

Jira issue: CRDB-4176

**Comment by otan** [comment]
> The first step is to ensure that we keep a history of all the results for each test on each release branch. (I believe Teamcity already tracks this for us, but I don't know where. We need that as first step.)

In my ideal world, TC's test failures can be tracked by test in graph form in grafana.

Something that looks like this: 
![image](https://user-images.githubusercontent.com/3646147/83807764-6fc1c180-a668-11ea-8f6d-c5f1f6e0d539.png)

When we find the endpoints, we should export this information there.

> if there's an upsurge in the number of test failures occurring simultaneously (in the same run) compared to the previous period, like 20% or more tests failing at once that didn't fail before:

In my eyes, as soon as there is a flaky test in master, open an issue if one has not be opened already. Each file should have an OWNER, and the owning team (not dev inf) is in charge of triaging this). The test should ideally be quarantined ASAP to avoid bors poison. 

----

I will post my vision for this later, but as a sneek peek, this is where I want my final state to be: https://dropbox.tech/infrastructure/athena-our-automated-build-health-management-system. -- tl;dr flaky tests get automatically quarantined with issues generated and an urgent onus on the oncall to fix it. It's what I hope the test community service team can start working - at least the slog of getting a) ownership of tests and b) quarantined test infrastructure.

**Comment by kenliu** [comment]
@jordanlewis is this something that the test comm svc team wants to work on? if so then we will put this in a different backlog for planning

**Comment by jordanlewis** [comment]
cc @srosenberg for triage
