### ISSUE TITLE
Backup stuck in last stage for 12 hours

### ISSUE THREAD

**Issue by drewdeally** [cockroachdb/cockroach#49889]
Created a 3 node cluster with a 1.9 TB database and backup has been running for over 12 hours at the last 7m 

![image](https://user-images.githubusercontent.com/39496073/83820212-0490e300-a69a-11ea-9545-87cbf606fa82.png)

debug zip posted internal

https://drive.google.com/file/d/16fWv1ei7OuPAI1uA-ws6MMhbDJy3KXn-/view?usp=sharing

**Comment by drewdeally** [comment]
additional info

show backup 'gs://tse-bucket/oltpbenchmark-db-oltp-tpcc25k';
  database_name | table_name | start_time |             end_time             |  size_bytes  |    rows    | is_full_cluster
----------------+------------+------------+----------------------------------+--------------+------------+------------------
  tpcc          | warehouse  | NULL       | 2020-06-04 12:29:57.678888+00:00 |      1363823 |      25000 |      false
  tpcc          | item       | NULL       | 2020-06-04 12:29:57.678888+00:00 |      8153874 |     100000 |      false
  tpcc          | history    | NULL       | 2020-06-04 12:29:57.678888+00:00 | 115137561751 |  750000000 |      false
  tpcc          | order_line | NULL       | 2020-06-04 12:29:57.678888+00:00 | 625943681389 | 7500060171 |      false
  tpcc          | customer   | NULL       | 2020-06-04 12:29:57.678888+00:00 | 463375293221 |  750000000 |      false
  tpcc          | stock      | NULL       | 2020-06-04 12:29:57.678888+00:00 | 842648838955 | 2500000000 |      false
  tpcc          | district   | NULL       | 2020-06-04 12:29:57.678888+00:00 |     25839142 |     250000 |      false
  tpcc          | new_order  | NULL       | 2020-06-04 12:29:57.678888+00:00 |   3371706000 |  225000000 |      false
  tpcc          | order      | NULL       | 2020-06-04 12:29:57.678888+00:00 |  42344290000 |  750000000 |      false
(9 rows)

Time: 4.693951041s


and 2 other parallel backups completed

root@:26257/defaultdb> BACKUP table tpcc.order TO 'gs://tse-bucket/order';;  
        job_id       |  status   | fraction_completed |   rows    | index_entries |    bytes
---------------------+-----------+--------------------+-----------+---------------+--------------
  561131449785778177 | succeeded |                  1 | 752940929 |     752940929 | 42512740625

root@:26257/defaultdb> BACKUP table tpcc.warehouse TO 'gs://tse-bucket/warehouse'                    
                    -> ;
        job_id       |  status   | fraction_completed | rows  | index_entries |  bytes
---------------------+-----------+--------------------+-------+---------------+----------
  561131331347087361 | succeeded |                  1 | 25000 |             0 | 1363823
(1 row)

Time: 4.047304133s

**Comment by drewdeally** [comment]
it appears even after being in a stuck state from UI and jobs command, after cancelling the job I ran a restore which appears to have completed

![image](https://user-images.githubusercontent.com/39496073/83946475-26e04900-a7df-11ea-9e28-04f41cf7b5d3.png)

**Comment by mwang1026** [comment]
@drewdeally does the bucket still exist? could we get access to it?

**Comment by drewdeally** [comment]
I will not post the oath2 here.  Will send it with another secure method.

**Comment by dt** [comment]
I think something went wrong with that cluster. The debug zip is missing the jobs table, which makes me suspect that something might be up that caused both that to fail and the UI not to update the job status. I'd be interesting to see what the actual job looked like -- i'm _guessing_ it was succeeded and it was just failing to update in the ui, but I can't really confirm that without the jobs table.

**Comment by mwang1026** [comment]
Nothing we can do without cluster and/or copy of the jobs table. Closing for now but next time your encounter ping us while the cluster is up. Thanks @drewdeally
