### ISSUE TITLE
ux/zip: debug zip mistakenly uses short advertised hostnames

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/cockroach#49926]
**Describe the problem**
The user's 19.2.2 cluster is healthy. However, when they ran `cockroach debug zip` with the 19.2.7 binary (which has `debug zip` fixes), the `*.zip` had many files called `*.txt.err.txt` with the message:
```
dial tcp: lookup cockroachdb-2: no such host
```
Why would this error appear when that machines `cockroachdb-2` is available?

**To Reproduce**
generate a debug.zip using 19.2.7 binary against a 19.2.2 cluster with a node started with flag `--advertise-addr=cockroachdb-2`

**Expected behavior**
`*.zip` should contain files with actual data not `*.txt.err.txt` files with error message

**Additional data / screenshots**
as per @knz 
> the error message says that DNS lookup fails for the name "cockroachdb-2". This is a combination of two separate factors:
> - they probably started their nodes with flags `--listen-addr=cockroachdb-2` or `--advertise-addr=cockroachdb-2` without a fully qualified domain name
> - their local name resolver  service does not know about short names (probably because they are using their default cloud DNS which only knows about long names)
> There are two options: either start the server with a long name, or run `cockroach debug zip` with `/etc/hosts` populated with the short names. (We recommend the former)

**Environment:**
 - CockroachDB version 19.2.2/19.2.7

**Additional context**
What was the impact?
Had to manually get the data we need using sql queries.

slack discussion here: https://cockroachlabs.slack.com/archives/CA8H95NUU/p1591381742065500

Jira issue: CRDB-6317

**Comment by knz** [comment]
thanks florence!

**Comment by jtsiros** [comment]
cc: @thtruo / @nkodali for triage. This was a straggler outside of the items I gave you.
