### ISSUE TITLE
sql: add data format version number to TableDescriptor

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#4994]
See #4499. The format of the SQL to KV mapping needs to be stored in the `TableDescriptor`. Old software should refuse to read table data that has a version it doesn't support. New software should be able to read old versions and ensure it is writing out the correct format. We don't need any of the mechanism to handle different data formats at this point, just the version number and a check in the code that the value matches the only supported version we have at this point.

**Comment by paperstreet** [comment]
I'm still looking through all the usages to make sure I caught them all and I'd like to write a test, but something like https://github.com/paperstreet/cockroach/pull/3?
