### ISSUE TITLE
release: 20.1.2

### ISSUE THREAD

**Issue by nathanstilwell** [cockroachdb/cockroach#49968]
Candidate SHA: 92670dd72acad03bd9de54a197d66ef423a90183.
Deployment status: Preparing.
Qualification Suite: ([Build](https://teamcity.cockroachdb.com/viewLog.html?buildId=2000736&buildTypeId=Cockroach_ReleaseQualification)).
Nightly Suite: [~#2138~](https://teamcity.cockroachdb.com/viewLog.html?buildId=2000756&buildTypeId=Cockroach_Nightlies_NightlySuite) [~2146~](https://teamcity.cockroachdb.com/viewLog.html?buildId=2003309&buildTypeId=Cockroach_Nightlies_NightlySuite) [2150](https://teamcity.cockroachdb.com/viewLog.html?buildId=2006209&buildTypeId=Cockroach_Nightlies_NightlySuite).
 
Admin UI for Qualification Clusters:
- Old Version: [nathanstilwell-release-v2011-6123c0c7-0001](http://nathanstilwell-release-v2011-6123c0c7-0001.roachprod.crdb.io:26258/#/overview/list)
- New Version: [nathanstilwell-release-v2012-92670dd7-0001](http://nathanstilwell-release-v2012-92670dd7-0001.roachprod.crdb.io:26258/)
 
[Release process checklist](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process)
 
Prep date: `09 JUN`
- [x] [Pick a SHA](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-PickingaSHA)
  - [x] fill in `Candidate SHA` above
  - [x] email thread on releases@
- [x] [Tag the provisional SHA](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-TagtheprovisionalSHA) ([provisional_202006091546_v20.1.2](https://github.com/cockroachdb/cockroach/releases/tag/provisional_202006091546_v20.1.2))
- [x] [Publish provisional binaries](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Publishtheprovisionalbinaries)([build](https://teamcity.cockroachdb.com/viewLog.html?buildId=2000357&buildTypeId=Cockroach_PublishProvisionalArtifacts))
- [x] Ack security@ on the generated Stackdriver Alert to confirm these writes were part of a planned release (Just reply on the email received alert email acking that this was part of the release process)
 
Release Qualification
- [x] [Check binaries](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Checkbinaries) ([PR](https://github.com/cockroachdb/bincheck/pull/195))
- [x] [Verify node crash reports](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Verifynodecrashreportsappearinsentry.io) ([sentry error](https://sentry.io/organizations/cockroach-labs/issues/1605608280/?project=164528))
- [x] [Deploy to test clusters](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-DeploytoTestClusters)
- [x] [Start release qualification suite](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-RuntheSuiteofNightlyRoachtests)
- [x] [Start nightly suite](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-RuntheSuiteofNightlyRoachtests)
- [x] fill in all WIP elements above (Nightly Suite, Admin UI, etc.)
 
One day after prep date:
- [x] [Get signoff on roachtest failures](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-RoachtestFailureSignoff)
 
- [x] [Keep an eye on clusters](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification#Monitoring-the-Qualification-Clusters) until release date. Do not proceed below until the release date.
 
Release date: `17 JUN`
- [x] [Check cluster status](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification#Monitoring-the-Qualification-Clusters)
- [x] [Tag release](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Tagtherelease) 
- [x] [Bless provisional binaries](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Blesstheprovisionalbinaries)
- [x] If applicable, [update the map that roachtests use to map a version to a previous version, to reference the newly tagged version](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/test_runner.go#L1145) ([PR](https://github.com/cockroachdb/cockroach/pull/50353))
 
- For production or stable releases in the latest major release series
  - [x] Update the [Homebrew Formula](https://github.com/cockroachdb/homebrew-tap/blob/master/Formula/cockroach.rb) ([PR](https://github.com/cockroachdb/homebrew-tap/pull/44))
  - [x] Update the image tag in our [Orchestrator configurations](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Orchestratorconfigurations) ([PR](https://github.com/cockroachdb/cockroach/pull/50357))
  - [ ] ~Update the image tag in Helm's [Orchestrator configurations](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Orchestratorconfigurations)~ (this looks deprecated and may need to be removed from the process?)
 
- For production or stable releases
  - [x] Announce version to the [registration cluster](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-AnnounceVersionToRegCluster)
 
- [x] Update docs
- [x] External communications for release
- [x] Clean up provisional tag from repository

**Comment by nathanstilwell** [comment]
# Test Failures

## Roachtest GCE

Failures: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_WorkloadNightly/2003284

### [kv]

- [ ] acceptance/multitenant
- [ ] tpcc/w=100/nodes=3/chaos=true
- [ ] clock/monotonic/persistent
- [ ] jobs/mixed-versions
- [ ] version/namespace-upgrade

### [appdev]

- [ ] hibernate

### [bulkio]

- [ ] import/tpch/nodes=8

## Random Syntax Tests

Failures: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RandomSyntaxTests/2003285

### [sql]

- [ ] TestRandomSyntaxGeneration
- [ ] TestRandomSyntaxFunctions

## Lint URLs

Failures: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_LintURLs/2003268

### [docs] (?)

- [ ] `Process exited with code 2 (Step: Command Line)`

## SQLite Logic Test High VModule Nightly

Failures: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_SqlLogicTestHighVModuleNightly/2003283

### [sql]

- [ ] `Process exited with code 1 (Step: make testlogic TESTFLAGS='--vmodule=*=10 -show-sql -test.v' (Command Line))`

**Comment by nathanstilwell** [comment]
Please note, I linked test failures to the wrong issue. For test failures for `v20.2.0-alpha.1` click [here](https://github.com/cockroachdb/cockroach/issues/49853#issuecomment-642803063).

**Comment by miretskiy** [comment]
Signing off on jobs/mixed_versions: known issue, tracked in #48315

**Comment by rafiss** [comment]
Signed off on Hibernate -- we just fixed that and it was a testing issue.

**Comment by nathanstilwell** [comment]
# Test Failures

## Roachtest GCE

Failures: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_WorkloadNightly/2006206


### [kv]

- [ ] tpccbench/nodes=9/cpu=4/multi-region

### [sql-exec]

- [ ] cancel/tpcc/distsql/w=10,nodes=3


### [appdev]

- [ ] django
- [ ] lib/pq
- [ ] pgx
- [ ] psycopg


## Random Syntax Tests

Failures: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RandomSyntaxTests/2003285

### [sql]

- [ ] TestRandomSyntaxSchemaChangeColumn

## SQLite Logic Test High VModule Nightly

Failures: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_SqlLogicTestHighVModuleNightly/2006205

### [sql]

- [ ] `Process exited with code 1 (Step: make testlogic TESTFLAGS='--vmodule=*=10 -show-sql -test.v' (Command Line))`

**Comment by yuzefovich** [comment]
Signing off on
- `cancel/tpcc/distsql/w=10,nodes=3` because this test is flake and has been failing for like a year or more (I think Jordan will be looking into improving it soon)
- `SQLite Logic Test High VModule Nightly` because there is a problem with parsing test output

**Comment by ajwerner** [comment]
Signing off on `TestRandomSyntaxSchemaChangeColumn` as it seems like a vanilla timeout and nothing seems hung. We probably should increase timeouts or something, especially if we see this again.

**Comment by rafiss** [comment]
Signed off on the appdev ORM tests. We are in the process of updating the expected fail lists, and then pinning the test versions to avoid new unexpected fails.

**Comment by tbg** [comment]
Signed off on  tpccbench/nodes=9/cpu=4/multi-region, clock sync error
