### ISSUE TITLE
sql: views containing enums need to use the stable enum representation

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#49962]
They currently don't, which will lead to problems when altering types is possible.

**Comment by rohany** [comment]
We don't have the infrastructure right now to "walk" a query like we do expressions. So we can't really fix this issue right now. This issue could manifest in real world problems where a user uses an enum value in a query and if they rename the enum value the view query doesn't work anymore. However, this can be fixed by just dropping the view and recreating it.

**Comment by rafiss** [comment]
Putting this on the Schema board since it looks like the Schema team made some progress on this, but let me know if SQL Experience should take this now

**Comment by jordanlewis** [comment]
Thanks, makes sense. I think we can merge Eric's PR soon.
