### ISSUE TITLE
sql: investigate interaction between user defined types and different IMPORT/EXPORT varieties

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#49971]
Look into
* CSV
* avro
* (are there others?)

**Comment by pbardea** [comment]
Just wanted to confirm that we're not planning on supporting user defined types in normal `IMPORT` (as opposed to `IMPORT INTO`)? For example, PG DUMP files that may contain user defined types.

**Comment by rohany** [comment]
I haven't looked into user defined types as part of PG DUMPs yet. The restriction with standard import was just that we aren't going to be looking into the database state to construct any anything.
