### ISSUE TITLE
ui,kv: track pairwise node latencies historically, and with percentiles

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#49970]
Our network diagnostics page only takes a current sample of intra-node network latencies. It's also just a `mean`, looking at the code (which is, I think dubious, given that these are latencies). This then makes the network page only really useful for a static view of the topology (how far are my nodes _physically_ from one another), and does not capture intermittent degraded network conditions/partial network failures (n3's outbound network links are acting up, and the system as a whole is degraded as a result). It would've been nice to have this view of things when diagnosing something like https://github.com/cockroachlabs/support/issues/476. 

For the "feature request", it would be nice to have the following:
(a) a percentile based view of pairwise latencies (p99.99 between nodeX and nodeY)
(b) historical views of pairwise network latencies (what were the p99s wrt network distance between nodeX and nodeY)

Jira issue: CRDB-4169

**Comment by irfansharif** [comment]
+cc @piyush-singh for triage.

**Comment by andreimatei** [comment]
The timeseries infrastructure is not really suitable for dynamic timeseries (or, equivalently, metrics with additional dimensions). It's awkward for timeseries to appear and disappear with nodes coming and going.

**Comment by piyush-singh** [comment]
This was our conclusion in the past - we similarly investigated storing time series metrics to track latencies per statement fingerprint. We have seen customer requests for historical pairwise latencies though, so perhaps it is time to investigate some alternative solution. Will use this issue to track going forward

**Comment by bdarnell** [comment]
> The timeseries infrastructure is not really suitable for dynamic timeseries

Additionally, anything based on node pairs creates a *lot* of timeseries. One way to mitigate that is that if we have more than X nodes, record things based on locality pairs instead of node pairs (at whichever level of locality reduces the number of timeseries enough).

But this seems like a big wheel to be reinventing. Are there not off-the-shelf network monitoring tools that can do this?
