### ISSUE TITLE
bulkio: error from ingestKvs causes deadlock

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#49989]
Running with https://github.com/cockroachdb/cockroach/pull/49979, I'm still seeing the stall that the change was hoping to fix.

Here's a dump of the goroutines: https://gist.github.com/nvanbenschoten/3cffff71d9847e09e366bfaeed0f15b4.

Notably, we still have a collection of `importWorker`s all stuck in `(*DatumRowConverter).SendBatch`. However, we have no one pulling from this channel. After reading through this code a bit, I believe this channel is supposed to be consumed by this goroutine:
https://github.com/cockroachdb/cockroach/blob/0dd70cab3f1970a06358f8b478e18de0cc99dbc3/pkg/ccl/importccl/read_import_base.go#L90-L104

That goroutine is not in the stacktrace. `runImport` is pretty suspicious. It links together two `ctxgroup` instances here:
https://github.com/cockroachdb/cockroach/blob/0dd70cab3f1970a06358f8b478e18de0cc99dbc3/pkg/ccl/importccl/read_import_base.go#L80-L85

However, it only seems to care about `producerGroup` hitting an error before `group` (`consumerGroup`), not the other way around. If `ingestKvs` throws an error, I don't see anything that would stop this from deadlocking.

**Comment by miretskiy** [comment]
The import was in CSV format?

**Comment by nvanbenschoten** [comment]
Yes. I'm testing now to see if I can see what (if any) error gets returned from `ingestKvs`.

**Comment by nvanbenschoten** [comment]
Yes, this is exactly what's going on. I get a `duplicate key in index: duplicate key: /Table/57/2/43000495766/"DSPGPRB-e"/2006-02-24T13:43:57.852Z/0` error from `ingestKvs` and then the rest of the import deadlocks.

**Comment by miretskiy** [comment]
We "might" have more bugs to squash.  Though, at this point, I'm not sure if I've missed something in  #49979, or we're dealing with something different.

**Comment by miretskiy** [comment]
Definitely a bug, just like you described.  Definitely different from the above one.
I'll play a bit to try to setup testing scenario.
