### ISSUE TITLE
Email notification for job completion with job's metadata.

### ISSUE THREAD

**Issue by rishabhgupta131** [cockroachdb/cockroach#50008]
In our production cluster we will have some very frequent backups running. As per our plan we will have a backup running after every 4 hours to create an incremental backup and every week to create a full backup.
Considering the frequent backups, we would like to know if there is any automated process through which we can send the job statistics(generated and printed in the console when the job completes) to any designated email address. This way it will be easy to monitor the backup process for any failure or blockers.

Jira issue: CRDB-4164

**Comment by rishabhgupta131** [comment]
The feature request does not need lots of details. That is why i avoided the template. Even the title  itself makes the feature clear. 
Please let me know if you people have any doubts regarding the feature being requested. 

I am also in contact with one of the support team members(Matthew Vardi) and came to know this functionality is being planned to be rolled out with 20.2. So I was encouraged to create an issue here as well to track the feature request.

**Comment by mattcrdb** [comment]
cc @mwang1026

**Comment by mwang1026** [comment]
Thanks @rishabhgupta131 . We're not planning to create emails but are planning on endpoints that you can pull alerts and/or messages from that would signal completion / failure etc. Would that be sufficient? We don't have any plans to add an email server to our CRDB binary so exposing those endpoints is our preferred solution.

**Comment by mwang1026** [comment]
Another option we're considering is allowing you to specify a location where we would write a "completion file" with relevant metadata. Is that something that is satisfactory as an option?

So for example, you could specify something like `backup_metadata_location = 's3://mybucket/backup_metadata'` and we'd write a file there once the backup succeeded or failed with relevant data

**Comment by mwang1026** [comment]
Hi @rishabhgupta131 wondering if you had any thoughts on the above. If you are running backup schedules with cron as well, you should be able to hook in with a `MAILTO` option to send out an email upon completion (since `BACKUP` is blocking it'll send once `BACKUP` is complete)
