### ISSUE TITLE
Multiregion movr workload performance discrepancies after primary key change

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#50019]
The demos here https://github.com/cockroachlabs/scripted-demos/tree/movr-20.1 set up the movr workload in 2 ways:
* Create the tables from the get go in a multi region fashion with partitions and zone configs
* Start the application in single region mode, and transition the schema to multi region using primary key changes.

There have been reported performance differences between the two -- p90, p99 latencies are 10-20 ms higher in the post primary key change state. We need to investigate what is causing the regression.

**Comment by rohany** [comment]
cc @awoods187

**Comment by awoods187** [comment]
Looks like everything is merged--can we try it out now?

**Comment by nvanbenschoten** [comment]
Let's wait until https://github.com/cockroachdb/cockroach/pull/50173 is merged and backported (if you're running straight off `release-20.1`).

**Comment by nvanbenschoten** [comment]
That patch is now merged on master. The backport is here: https://github.com/cockroachdb/cockroach/pull/50216.

**Comment by rohany** [comment]
I reran these demos with these changes and could not replicate the performance differences with the related kv changes.
