### ISSUE TITLE
disk budget exceeded: 1048576 bytes requested, 0 currently allocated, 0 bytes in budget

### ISSUE THREAD

**Issue by karlbohlmark** [cockroachdb/cockroach#50017]
**Describe the problem**

For the query mentioned below I get the error: `this query requires additional disk space: temp disk storage: disk budget exceeded: 1048576 bytes requested, 0 currently allocated, 0 bytes in budget` (code 53100). I haven't found any documentation about this error or how the disk budget works and is configured.

**To Reproduce**

I have around 80000 rows in my `audit_log` table with the schema shown below.

When executing the query `select id, entity, entity_name, entity_id, operation, username, user_id, execution_time_ms, created_at, count(*) OVER() AS total_count from audit_log   order by id desc limit 10` I get the error `this query requires additional disk space: temp disk storage: disk budget exceeded: 1048576 bytes requested, 0 currently allocated, 0 bytes in budget`

**Expected behavior**
I expected to get the 10 rows I asked for in the query

**Additional data / screenshots**
```
     column_name    |  data_type  | is_nullable |          column_default           | generation_expression |              indices               | is_hidden
+-------------------+-------------+-------------+-----------------------------------+-----------------------+------------------------------------+-----------+
  id                | INT8        |    false    | NULL                              |                       | {primary,audit_log_created_at_idx} |   false
  method            | STRING      |    false    | NULL                              |                       | {}                                 |   false
  pathname          | STRING      |    false    | NULL                              |                       | {}                                 |   false
  user_id           | STRING      |    true     | NULL                              |                       | {}                                 |   false
  username          | STRING      |    true     | NULL                              |                       | {}                                 |   false
  query             | STRING      |    true     | NULL                              |                       | {}                                 |   false
  request           | STRING      |    true     | NULL                              |                       | {}                                 |   false
  response          | STRING      |    true     | NULL                              |                       | {}                                 |   false
  error             | STRING      |    true     | NULL                              |                       | {}                                 |   false
  execution_time_ms | INT8        |    true     | NULL                              |                       | {}                                 |   false
  created_at        | TIMESTAMPTZ |    false    | current_timestamp():::TIMESTAMPTZ |                       | {audit_log_created_at_idx}         |   false
  updated_at        | TIMESTAMPTZ |    true     | NULL                              |                       | {}                                 |   false
  authtoken         | STRING      |    true     | NULL                              |                       | {}                                 |   false
  entity            | STRING      |    true     | NULL                              |                       | {}                                 |   false
  entity_id         | STRING      |    true     | NULL                              |                       | {}                                 |   false
  entity_name       | STRING      |    true     | NULL                              |                       | {}                                 |   false
  operation         | STRING      |    true     | NULL                              |                       | {}                                 |   false
  affiliate         | STRING      |    true     | NULL                              |                       | {}                                 |   false
```
**Environment:**
 - CockroachDB 20.1.1
 - Linux
 - pg (node-postgres)

**Additional context**
The size of the audit_log table according to the Cockroach UI is 49.0 MiB.
I'm running a 3 node cluster with  `cache: '512Mi'` and `max-sql-memory: '512Mi'`

**Comment by mattcrdb** [comment]
cc @rohany

**Comment by rohany** [comment]
This looks like an @yuzefovich question

**Comment by yuzefovich** [comment]
The error messages indicates that for some reason there are 0 bytes allocated for the temporary disk storage. @karlbohlmark what is the command that you used to start up the nodes? Do the nodes use in-memory only storage (I think we allow such option)?

An unrelated question: I see that you're using a window function, is it possible to refactor the query to avoid it and still get the output that you want? (The context is that window functions are expensive, and in this particular case we buffer all rows that you have in the table. There is `sql.distsql.temp_storage.workmem` cluster setting that determines how much memory a single processor can use, by default it is 64MiB, and it is likely that the limit is reached by the window functions processor, so it has to spill to disk. You could try increasing that limit and possibly we won't have to spill to disk, and then the budget error won't occur.)

**Comment by karlbohlmark** [comment]
Thanks!

I'm running cockroach in k8s using helm and I now found  `max-disk-temp-storage: 0` in the default values file for cockroach https://github.com/helm/charts/blob/master/stable/cockroachdb/values.yaml#L81

I've now verified that changing this setting to `256MiB` solves the problem. However, according to your suggestion I have rewritten the pagination queries to use a `union select count(*) ...` instead of a window function which also cuts down the execution time.

**Comment by yuzefovich** [comment]
> I've now verified that changing this setting to 256MiB solves the problem.

Great!

> which also cuts down the execution time

Even better :)

I also raised the question internally on why the default value for temp storage size is set to 0, so I'll keep this issue open until we change the helm config by either updating the default value or at least leaving a comment explaining the choice of 0 as the default.

**Comment by jimethn** [comment]
Also interested in why 0 is the default in the helm chart, when 32Gi is the default in CDB itself.

**Comment by yuzefovich** [comment]
A quick update on this: I've raised this question again internally, and it does appear to be a bug in configuration (it was introduced in https://github.com/helm/charts/pull/18993), we're currently looking in what the default should be in there.

**Comment by yuzefovich** [comment]
I'll assign it @johnrk to be the owner since it seems to fall under Operator Experience umbrella.

**Comment by jordanlewis** [comment]
Closing as RCA was about k8s configuration.
