### ISSUE TITLE
distsql: FlowScheduler.ScheduleFlow is source of significant mutex contention

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#50022]
In an instance of TPC-E, I'm seeing that the mutex locking in `FlowScheduler.ScheduleFlow` [here](https://github.com/cockroachdb/cockroach/blob/54a923b26c0d8481e9e523c97e6fc016dfabb4b8/pkg/sql/flowinfra/flow_scheduler.go#L117) is the single largest source of mutex contention in the system, at a little over 15% of total mutex contention delay. This makes some sense, as TPC-E makes heavy use of DistSQL and this appears to be a serialization point between all DistSQL flows scheduled on a machine.

I don't know this code, so I'm hoping to bring this to the attention of those that do (@asubiotto, @yuzefovich). Are there any easy wins here? Do we need to serialize the call to `Flow.Start` across all flows on a node? Does this call need to be protected by the mutex at all? If not, is the mutex only protecting `fs.mu.numRunning`? Can we manipulate this counter using atomics to avoid blocking in the happy path where `fs.canRunFlow(f) == true`?

**Comment by asubiotto** [comment]
Good catch, we definitely don't need to lock the mutex for the happy case. In fact, I think we should probably rework the flow scheduler to remove any queueing behavior which would remove the need for the mutex (https://github.com/cockroachdb/cockroach/pull/34430) but it just hasn't been high priority.
