### ISSUE TITLE
Errors you may encounter when upgrading these dependencies

### ISSUE THREAD

**Issue by KateGo520** [cockroachdb/cockroach#50036]
### 1. github.com/spf13/cobra  
-Version: V1.0.0   (Latest commit a684a6d on 11 Apr)
-Where did you use it: 
https://github.com/cockroachdb/cockroach/search?l=Go&q=github.com%2Fspf13%2Fcobra
https://github.com/cockroachdb/cockroach/blob/976280b4965d4a371809a24adc3aeacc3ffec3bf/pkg/cli/gen.go#L26
-Detail: 
>>[github.com/spf13/cobra/go.mod](https://github.com/spf13/cobra/blob/v1.0.0/go.mod#L6)
```
module github.com/spf13/cobra
go 1.12
require (
	github.com/cpuguy83/go-md2man/v2 v2.0.0
	github.com/inconshreveable/mousetrap v1.0.0
	github.com/mitchellh/go-homedir v1.1.0
	github.com/spf13/pflag v1.0.3
	github.com/spf13/viper v1.4.0
	gopkg.in/yaml.v2 v2.2.2
)
```

>>[github.com/spf13/cobra/doc/man_docs.go](https://github.com/spf13/cobra/blob/v1.0.0/doc/man_docs.go#L27)
```
package doc
import (
	"github.com/cpuguy83/go-md2man/v2/md2man"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)
```
If you try to get this version, you will get an error: no package exists at "github.com/cpuguy83/go-md2man/v2/md2man"

### 2. github.com/jackc/pgx  
-Version: V4.6.0   (Latest commit 0446492 on 31 Mar)
-Where did you use it: 
https://github.com/cockroachdb/cockroach/search?q=jackc%2Fpgx&unscoped_q=jackc%2Fpgx
-Detail: 
>>[github.com/jackc/pgx/go.mod](https://github.com/jackc/pgx/blob/v4.6.0/go.mod#L10)
```
module github.com/jackc/pgx/v4
go 1.12
require (
	github.com/jackc/pgproto3/v2 v2.0.1
	github.com/jackc/pgtype v1.3.0
	…
)
```

>>[github.com/jackc/pgx/conn.go](https://github.com/jackc/pgx/blob/v4.6.0/conn.go#L15)
```
package pgx

import (
	"github.com/jackc/pgproto3/v2"
	"github.com/jackc/pgtype"
	"github.com/jackc/pgx/v4/internal/sanitize"
	…
)
```
If you try to get this version, you will get an error: no package exists at "github.com/jackc/pgproto3/v2"  and  "github.com/jackc/pgx/v4"

### 3. github.com/cockroachdb/apd  
-Version: V2.0.1   (Latest commit 5307578 on 15 Feb 2019)
-Where did you use it: 
https://github.com/cockroachdb/cockroach/search?l=Go&q=cockroachdb%2Fapd
-Detail: 
>>[github.com/cockroachdb/apd/go.mod](https://github.com/cockroachdb/apd/blob/v2.0.1/go.mod#L1)
```
module github.com/cockroachdb/apd/v2
require github.com/pkg/errors v0.8.0
```

>>[github.com/jackc/pgx/conn.go](https://github.com/jackc/pgx/blob/v4.6.0/conn.go#L15)
```
package apd_test
import (
	"github.com/cockroachdb/apd/v2"
) 
```
If you try to get this version, you will get an error: no package exists at " github.com/cockroachdb/apd/v2"

## Why?
1.	These dependencies all added [Go modules](https://github.com/golang/go/wiki/Modules) in the last version.
2.	They all comply with the specification of "Releasing Modules for v2 or higher" available in the Modules documentation. Quoting the specification:
> A package that has opted in to modules _must_ include the major version in the import path to import any v2+ modules. Such as: Repo github.com/my/module opted in to Modules on version v3.x.y. Then the import statements within the module to also use /v3 (e.g., import `"github.com/my/module/v3/mypkg"`).

3.	This "github.com/my/module/v3/mypkg" is not the `physical path`. So earlier versions of Go (including those that don't have minimal module awareness) plus all tooling(like dep, glide, govendor, etc) don't have `minimal module awareness` as of now and therefore don't handle import paths correctly See [golang/dep#1962](https://github.com/golang/dep/issues/1962), [golang/dep#2139](https://github.com/golang/dep/issues/2139).
> Note: creating a new branch is not required. If instead you have been previously releasing on master and would prefer to tag v3.0.0 on master, that is a viable option. (However, be aware that introducing an incompatible API change in master can cause issues for non-modules users who issue a go get -u given the go tool is not aware of semver prior to Go 1.11 or when module mode is not enabled in Go 1.11+).
> Pre-existing dependency management solutions such as dep currently can have problems consuming a v2+ module created in this way. See for example dep#1962.
https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

### 1. Migrate to Go Modules.
Go Modules is the future, If you want a better upgrade package experience, you can opt into Go Modules.

### 2. Keep using the dependencies manage tool(like dep, glide, govendor, etc).
If you insist on using the dependencies manage tool(like dep, glide, govendor, etc), you would better see how `github.com/moby/moby` does it.
https://github.com/moby/moby/blob/master/VENDORING.md
https://github.com/moby/moby/blob/master/vendor.conf
In the vendor directory, `github.com/moby/moby` adds the /vN subdirectory in the corresponding dependencies.
This will help downstream module users make better use of your package, or they will be stuck in github.com/jackc/pgx v3.6.2， github.com/cockroachdb/apd v1.1.0 and github.com/spf13/cobra v1.0.0.
```
module gomodproject
go 1.13
require (
	github.com/cockroachdb/apd v1.1.0 // indirect
	github.com/cockroachdb/circuitbreaker v2.2.1+incompatible // indirect
	github.com/cockroachdb/cockroach v20.1.1+incompatible
	github.com/jackc/pgx v3.6.2+incompatible // indirect
	github.com/spf13/cobra v1.0.0 // indirect
…
)
```
Because the modular mechanism and the non-modular mechanism understand paths differently. 

* https://github.com/golang/go/wiki/Modules#semantic-import-versioning
* https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning
* https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher
* https://github.com/golang/dep/issues/1962
* https://github.com/golang-migrate/migrate/issues/103

**If this report helps you a little, please let me know**

**Comment by otan** [comment]
we've been trying :) https://github.com/cockroachdb/cockroach/pull/49447
coming soon, hopefully.

**Comment by KateGo520** [comment]
@otan Thank you for your contribution!
