### ISSUE TITLE
Retrive full revision history of tables and query RocksDb

### ISSUE THREAD

**Issue by AmitKawad** [cockroachdb/cockroach#50038]
1. I want to be able to retrieve a full revision history of a table and what modifications have taken place over every update or delete. _Trace session_ or _activating diagnostic_ does not seem to be very helpful in this case.

2. Since CockroachDB uses RocksDB as storage engine and translates the native sql calls to RocksDB specefic calls like Seek or scan. Is there any way that I can directly access and query the RocksDB bypassing the CockroachDB sql?

**Comment by andreimatei** [comment]
> I want to be able to retrieve a full revision history of a table and what modifications have taken place over every update or delete.

Have you considered [CDC](https://www.cockroachlabs.com/docs/stable/change-data-capture.html)?
We've considered allowing you to query the historical versions of a row that haven't been GCed yet, but there's no such feature currently.

> Since CockroachDB uses RocksDB as storage engine and translates the native sql calls to RocksDB specefic calls like Seek or scan. Is there any way that I can directly access and query the RocksDB bypassing the CockroachDB sql?

Not any way that CRDB offers. You can use RocksDB debug tools to get low level access to the data (but first you need to figure out which node has the data you're looking for). Also note that we're moving away from RocksDB as a storage engine in favor of Pebble.
