### ISSUE TITLE
ui: `make` fails due yarn installation errors

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#50100]
Keep running into this: [build.log](https://gist.github.com/irfansharif/e5325c294ac7273aa7cc376e3b98d6b1). Unsure what's happening, or what has changed recently.

**Comment by irfansharif** [comment]
Retrying no-op `make build` runs into the following:
```
$ make build
Running make with -j16
GOPATH set to /Users/irfansharif/Software
build/node-run.sh -C pkg/ui yarn install --offline
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
mkdir -p lib
ln -sf /Users/irfansharif/Software/native/x86_64-apple-darwin19.5.0/geos/lib/lib{geos,geos_c}.dylib lib
success Already up-to-date.
Done in 0.66s.
# Prevent ProtobufJS from trying to install its own packages because a) the
# the feature is buggy, and b) it introduces an unnecessary dependency on NPM.
# See: https://github.com/dcodeIO/protobuf.js/issues/716.
# We additionally pin the dependencies by linking in a lock file for
# reproducable builds.
build/node-run.sh pkg/ui/bin/gen-protobuf-cli-deps.js > pkg/ui/node_modules/protobufjs/cli/package.json
ln -sf ../../../yarn.protobufjs-cli.lock pkg/ui/node_modules/protobufjs/cli/yarn.lock
build/node-run.sh -C pkg/ui/node_modules/protobufjs/cli yarn install --offline
yarn install v1.21.1
error An unexpected error occurred: "/Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/cli/package.json: Unexpected end of JSON input".
info If you think this is a bug, please open a bug report with the information provided in "/Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/pkg/ui/node_modules/protobufjs/cli/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
make: *** [pkg/ui/yarn.installed] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by irfansharif** [comment]
Looks like the same thing as https://github.com/cockroachdb/cockroach/issues/45522 from earlier, sorry for the noise. Closing the other in favor of this one. David, perhaps we could rope in @jlinder into this, I'm unsure who rightly "owns" our makefile anymore.

**Comment by dhartunian** [comment]
I have an idea for why this might happen:

In the makefile we run this task:
https://github.com/cockroachdb/cockroach/blob/fd42b5b13cb754527841247c7df5d310b395d2ee/Makefile#L334-L350

In particular this line is setting up the protobuf package file in question:
https://github.com/cockroachdb/cockroach/blob/fd42b5b13cb754527841247c7df5d310b395d2ee/Makefile#L343

It's possible that somehow the file isn't finished writing or can't be correctly written to and causes the script to fail.

**Comment by jlinder** [comment]
@irfansharif Are you still hitting this issue? What do you get when you run `build/node-run.sh pkg/ui/bin/gen-protobuf-cli-deps.js` ?

I ran the following locally with master at 82538176c897591e8241fa258895e42b9a3226a4 and didn't get this problem:

```
make clean
make ui-clean
make build
```

**Comment by irfansharif** [comment]
What I've seen historically with our makefile related issues, is that they're usually race conditions. The issues above are likely the same, and only get triggered if Make is incorrectly building artifacts out of order (due to unspecified dependencies). I think if you were to run `make clean; make build` repeatedly you're likely to run into the specific failures posted above.

**Comment by irfansharif** [comment]
(I can try repro-ing if you don't beat me to it.)
