### ISSUE TITLE
sql: internal retries cause wacky statement timings

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/cockroach#50108]
Internal retries appear to screw up our accounting for statement timings. It seems like the total latency is attributed to all of the retries (or something along these lines), which can result in a large "Overhead" bucket and an absurdly large "Total Time" value. For example, this was the result of running `SELECT crdb_internal.force_retry('5s')` a single time.

<img width="517" alt="Screen Shot 2020-06-11 at 1 05 31 PM" src="https://user-images.githubusercontent.com/679246/84417880-44008780-abe4-11ea-8bd0-684a6333ab49.png">
<img width="928" alt="Screen Shot 2020-06-11 at 1 05 02 PM" src="https://user-images.githubusercontent.com/679246/84417868-41059700-abe4-11ea-9476-f90072572091.png">

@piyush-singh, do you have any thoughts about how internal retries should be accounted for in statement timings? It feels to me like this example should have been counted as only one execution of the statement, with the internal retry time categorized into its own bucket. Though I'm not sure how tricky it is to determine what time should count as "retry time".

**Comment by piyush-singh** [comment]
>It feels to me like this example should have been counted as only one execution of the statement, with the internal retry time categorized into its own bucket.

That would make sense to me. These internal retries happen transparently to the end user, and the end user probably only cares about how long it took to execute the statement once.
