### ISSUE TITLE
clusterversion: reword and fix the version setting

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#50114]
The wording on the cluster setting `version` is now outdated.

End users should no longer ever set this, so we should update the comment to reflect that.

"The current cluster version in the following format ..." or something like that

Also, if possible, we should restrict end users from adjusting this setting and the manual process of setting it on upgrades is now deprecated.

Jira issue: CRDB-4152

**Comment by BramGruneir** [comment]
@irfansharif, I didn't know where to file this, so assigned to your for triage as you did a lot of work in this area recently.

**Comment by irfansharif** [comment]
I've had to use this setting manually recently to get around the limitation in https://github.com/cockroachdb/cockroach/issues/53515. I don't know that CRDB is quite equipped to completely hide away this cluster setting as yet. Our recommended upgrade procedure seems to work with the setting and resetting of the `cluster.preserve_downgrade_option` cluster setting, so perhaps it _would_ be a good idea to remove this setting entirely (or make it read-only).

**Comment by knz** [comment]
we've established that setting the version setting manually has several valid use cases. So not doing this.
