### ISSUE TITLE
perf: avoid common allocations in TPC-C to reduce GC impact

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#50117]
This is the 2020 remake of https://github.com/cockroachdb/cockroach/issues/30512. Brief recap of the kinds of samples we're interested in:

>   1. reduce `alloc_space`: We'd like to reduce the total memory size of garbage that we allocate to reduce the frequency of GCs. This should also reduce the amount that goroutines get in "debt" and are forced to assist the GC while it's running concurrently.
>  2. reduce `alloc_objects`: We'd like to reduce the total object count of garbage that we allocate to speed up the GC mark and sweep phases. This should also reduce the impact that the GC has while running concurrently (i.e. decrease GC assist pauses, both while marking and sweeping) because it should make it less common that a goroutine allocates during this period.

---

Pulled up a four node roachprod cluster, imported TPCC-1k and ran `workload run tpcc` against it. Experiments were on a recent master, https://github.com/cockroachdb/cockroach/commit/49339fef48f4165a4e7471290b.

```sh
# On gceworker
build/builder.sh make build
build/builder.sh make bin/workload
make bin/roachprod
bin/roachprod create irfansharif-pprof -n 4
bin/roachprod put irfansharif-pprof:1-4 cockroach ./cockroach
bin/roachprod put irfansharif-pprof:4 bin.docker_amd64/workload ./workload
bin/roachprod start --encrypt=false irfansharif-pprof:1-3

# Going to take ~15-20m. Good time to take a break.
bin/roachprod run irfansharif-pprof:4 './cockroach workload fixtures import tpcc --warehouses=1000 --scatter --checks=false {pgurl:1}'
bin/roachprod run irfansharif-pprof:4 './workload run tpcc --warehouses=1000 --workers=1000 --max-rate=1000 --wait=false --duration=30m --scatter --tolerate-errors {pgurl:1-3}'
```

---

Here a few of the worst offenders looking at `alloc_objects`:

- [ ] `sqlbase.DecodeUntaggedEnum`: 15.39% of all allocated objects (!)

Looking at the alloc count, I think we're allocating when converting between the byte buffer `data` and `tree.DString`, which quickly glancing at https://github.com/golang/go/issues/25484, looks to be problematic.

```
 Total:     2126197    2662867 (flat, cum)  15.39%
    507            .          .           	case types.IntFamily: 
    508            .          .           		b, i, err := encoding.DecodeUntaggedIntValue(buf) 
    509            .          .           		if err != nil { 
    510            .          .           			return nil, b, err 
    511            .          .           		} 
    512            .      36867           		return a.NewDInt(tree.DInt(i)), b, nil 
    513            .          .           	case types.StringFamily: 
    514            .          .           		b, data, err := encoding.DecodeUntaggedBytesValue(buf) 
    515            .          .           		if err != nil { 
    516            .          .           			return nil, b, err 
    517            .          .           		} 
    518      2126197    2318755           		return a.NewDString(tree.DString(data)), b, nil 
    519            .          .           	case types.CollatedStringFamily: 
    520            .          .           		b, data, err := encoding.DecodeUntaggedBytesValue(buf)
```

- [ ] `roachpb.(*Value).ensureRawBytes`: 16.88% of all allocated objects (!). It's not immediately clear to me how to go about reducing this. We allocate `roachpb.(*Value)`s all over, and I don't see us using `sync.Pool`s or the like to reduce this pressure. Probably worth investigating what codepath is causing this many allocations, and controlling it accordingly.

---

Here a few of the worst offenders looking at `alloc_space`:

- [ ] `roachpb.(*Value).ensureRawBytes`: 4.05% of allocated space. See above.
- [ ] `hyperloglog.newCompressedList`: 6.37% of allocated space. Looks it's something used within `rowexec/sampler.go`. We could check to see if possible to reuse these objects when possible.
- [ ] `sqlbase.DecodeUntaggedEnum`: 3.22% of all allocated space. See above.
- [ ] `RaftRequestMessageBatch.{Marshal,Unmarshal}`: 1.51% and 1.11% respectively. Haven't looked deeply into whether it's possible to reduce this given how it's generated code. Could investigate. Same true for `raftpb.(*Entry).Unmarshal`, with 1.33%. Saw the same for `ReplicaEvalResult_AddSSTable.Unmarshal` which is at 2.67%.
- [ ] `SpanSet.AddMVCC`: 1.57% of allocated space. Could probably use some pre-allocation? Or maybe not as clear given we already make use of `SpanSet.Reserve`. 

```
  Total:         2GB        2GB (flat, cum)  1.57%
    134            .          .           	if keys.IsLocal(span.Key) { 
    135            .          .           		scope = SpanLocal 
    136            .          .           		timestamp = hlc.Timestamp{} 
    137            .          .           	} 
    138            .          .            
    139          2GB        2GB           	s.spans[access][scope] = append(s.spans[access][scope], Span{Span: span, Timestamp: timestamp}) 
    140            .          .           } 
    141            .          .            
    142            .          .           // Merge merges all spans in s2 into s. s2 is not modified. 
    143            .          .           func (s *SpanSet) Merge(s2 *SpanSet) { 
    144            .          .           	for sa := SpanAccess(0); sa < NumSpanAccess; sa++ { 
```

---

Hm, after having typed it all out, I don't know that there's much low hanging fruit within KV (that's a good thing I suppose).

**Comment by irfansharif** [comment]
+cc @jordanlewis for the SQL related ones I don't know much about, @nvanbenschoten for the rest.

**Comment by nvanbenschoten** [comment]
Thanks for running this experiment! I also don't see a ton of low hanging fruit. However, the `sqlbase.DecodeUntaggedEnum` allocation looks promising!

You're correct that casting from a `[]byte` to a `tree.DString` is allocating because strings are meant to be immutable byte the caller still has the potential to mutate the existing byte slice after the cast. However, I'm pretty sure we guarantee that the input buffer provided to `DecodeUntaggedDatum` is immutable. If we didn't, the handling of `types.BytesFamily` would be unsafe. Hm, actually, that's not true – `tree.DBytes` is also backed by a `string`. I think it would be worth looking into whether `DecodeUntaggedDatum` assumes exclusive ownership over its provided byte slice. Maybe @jordanlewis knows. If it does, we can look into performing an unsafe `[]byte->string` cast like we do in a few other places. That should eliminate all 15.39% of those allocated objects, which might provide a measurable win.

**Comment by jordanlewis** [comment]
Good question. I think in the main codepath, nobody else will use that input buffer, so it would be safe to do this unsafe cast. But I can't speak for all codepaths...

@asubiotto do you know?

@irfansharif if you're interested in poking here, I think it would be worthwhile to try out making that an unsafe cast using `encoding.DecodeUnsafeStringAscending` (although that variant might not be quite right - you might have to make a new one that uses `unsafeString` in that same file) and see what happens.

**Comment by irfansharif** [comment]
I could do that, but it'd also be a fun mini-friday project for one of our SQL interns. Wanna run it by someone else first?

**Comment by asubiotto** [comment]
Nice catch. I think that this case is explicitly handled by the column execution engine before calling `DecodeUntaggedDatum` to avoid making a new `DString` since we only need the underlying bytes. In the main codepath, I think that this shouldn't be a problem either, but the only way to tell is to try it out.

**Comment by jordanlewis** [comment]
@helenmhe this is a total change from what you were looking at so far, but to Irfan's point, I do think it would be an interesting performance-related "side gig". Interested?

**Comment by jordanlewis** [comment]
@helenmhe said she'll take a gander at this issue on Fridays.
