### ISSUE TITLE
/_status/vars is world readable

### ISSUE THREAD

**Issue by korpa** [cockroachdb/cockroach#50126]
**Describe the problem**

Spin up a secure cluster with cli parameters
* --certs-dir= 
* --advertise-addr=
* --join=
* --cache=
* --max-sql-memory=

**To Reproduce**

goto https://[ip]:8080/_status/vars

**Expected behavior**

* Endpoint is only accessable via authentication like basic-auth
or
* A cli parameter e.g. --activate-status-vars=true is needed to activate it
or
* At least a warning on https://www.cockroachlabs.com/docs/stable/security-overview.html that this endpoint is exposed to the world and a http proxy to secure this endpoint is needed.

**Additional data / screenshots**

**Environment:**
 - CockroachDB version 20.1

**Additional context**

**Comment by solongordon** [comment]
@knz Sending this your way since I know you addressed similar security concerns in v20.1. Was this endpoint ever discussed during that work?

**Comment by knz** [comment]
Yes it was considered that the information exposed this way was not sensitive.

@korpa FYI there are multiple HTTP endpoints that are similarly world-readable. We always recommend suitable proxying / firewalling for best security.

**Comment by korpa** [comment]
@knz Ok. Thank you very much.

But then it should be mentioned on https://www.cockroachlabs.com/docs/stable/security-overview.html and maybe on https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html

**Comment by knz** [comment]
@taroface can you lift this issue into a doc project?

**Comment by knz** [comment]
Superseded by  #50472
