### ISSUE TITLE
kvserver: TestReplicaRangefeedNudgeSlowClosedTimestamp times out in testrace

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#50152]
This test started failing more often failing on the master branch because it times out. This has been preventing the `Publish Bleeding Edge` build from working.

Example failure: https://teamcity.cockroachdb.com/viewLog.html?buildId=2009092&buildTypeId=Cockroach_MergeToMaster

Test stats: https://teamcity.cockroachdb.com/project.html?projectId=Cockroach_UnitTests&testNameId=-4991270908105557738&tab=testDetails It seems like this timeout has been happening sporadically for a while, but it looks to be more frequent in the past few days.

**Comment by andreimatei** [comment]
Looks the same as #50091

**Comment by tbg** [comment]
Closing for #50091
