### ISSUE TITLE
v20.1.1 Regression: Grant on all tables is Very Slow

### ISSUE THREAD

**Issue by oliverisaac** [cockroachdb/cockroach#50165]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

When running a statement like: `grant all on * to "test";` it takes nearly 1 minute to execute on a cluster with 6 nodes.

**To Reproduce**

I wrote a script to test this use case. It spins up 9 nodes, creates 100 tables, and then runs a grant command. If you run it with 19.1.1 or 19.2.2 the grant takes about 400ms. On 20.1.1 it takes 4 seconds.

To use, save the script somewhere then call it with `bash /tmp/script.sh 20.1.1` (or `19.2.2` to see the difference.)

```bash
#!/usr/bin/env bash

set -e -o pipefail -u

version="${1:-20.1.1}"

dir=$( mktemp -d )
cd "$dir"

function cockroach(){
    if ! [[ -x /tmp/cockroach-v$version.darwin-10.9-amd64/cockroach ]]; then
        (
            cd /tmp/;
            curl https://binaries.cockroachdb.com/cockroach-v$version.darwin-10.9-amd64.tgz | tar -xz
        )
    fi
    command /tmp/cockroach-v$version.darwin-10.9-amd64/cockroach "${@}"
}

cockroach version

num_nodes=9
num_tables=100
startsqlport=26257
starthttpport=8080

join=""
for (( i=0; i<9; i++ )); do
    join="$join,localhost:$(( startsqlport + i ))"
done

join="${join#,}"
pids=()

for (( i=0; i<num_nodes; i++ )); do
    cockroach start \
    --insecure \
    --store="node$i" \
    --listen-addr=localhost:$(( $startsqlport + $i )) \
    --http-addr=localhost:$(( $starthttpport + $i )) \
    --join="$join" \
    --background
done

until cockroach init --insecure --host localhost:$startsqlport || echo "select 1;" | cockroach sql --insecure --host localhost:$startsqlport; do 
    sleep 1
done

command=()
command+=( "create user if not exists test;" )
for (( i=0; i<num_tables; i++ )); do
    command+=( "create table if not exists test$i ();" )
done
command+=( "grant all on * to test;" )

printf "%s\n" "${command[@]}" | cockroach sql --insecure --host localhost:$startsqlport

for (( i=0; i<num_nodes; i++ )); do
    args=()
    if [[ $version == 20.1.1 ]]; then
        args+=( "--drain-wait" "5s" )
    fi
    cockroach quit "${args[@]}" --insecure --host localhost:$(( $startsqlport + $i )) &
done

wait

rm -r "$dir"
```

**Expected behavior**
Grants should happen quickly.

**Environment:**
 - CockroachDB version: 20.1.1
 - Server OS: Linux running in GKE across 2 or 3 regions.
- The test script (above) I run on MacOS 10.14.5

**Comment by rohany** [comment]
Cc @RichardJCai

**Comment by RichardJCai** [comment]
> Cc @RichardJCai

I think we might uncover why this is slow from the DDL analysis work. I checked the difference between 19.2 and 20.1 and we do have some extra checks when doing a Grant. We have an extra CheckPrivileges to only allow Granting the privilege if the granter has the privilege. Although CheckPrivileges should only perform a query on the system table when the role memberships are updated but it shouldn't be in this case. Not sure if the extra CheckPrivileges calls would make up for this time difference though. Will have to keep investigating.

**Comment by solongordon** [comment]
This is just a guess but I wonder if the additional latency could be due to #45697.

**Comment by RichardJCai** [comment]
> This is just a guess but I wonder if the additional latency could be due to #45697.

Yeah I thought so as well, thats where these extra CheckPrivileges are coming from.

**Comment by RichardJCai** [comment]
> > This is just a guess but I wonder if the additional latency could be due to #45697.
> 
> Yeah I thought so as well, thats where these extra CheckPrivileges are coming from.

I just checked this, it shouldn't be that, I checked removed those checks and it didn't get any better.

https://github.com/cockroachdb/cockroach/commit/e340ca981262c764c48d290194c737ebf4637684

I think it might be this change here, if we can batch this job I think it would improve the speed a lot.

**Comment by rohany** [comment]
Are you saying that because a new job is spawned for each table, it's taking a long time to execute all of them?

cc @lucy-zhang

**Comment by RichardJCai** [comment]
> Are you saying that because a new job is spawned for each table, it's taking a long time to execute all of them?
> 
> cc @lucy-zhang

Yeah I think so. I'm still not sure why the time seems to increase exponentially with the number of tables though.

**Comment by lucy-zhang** [comment]
Yeah, in 20.1 we create a separate job for every table and wait for all of them to finish. The jobs don't have any dependencies on each other, but we still have to wait for each of them to get adopted, etc.

Furthermore, the only thing these jobs do is wait for old leases to drain, so this is an extreme case of item 4 in https://github.com/cockroachdb/cockroach/issues/47790.

I'd rather fix this by getting rid of these jobs entirely and waiting for leases in some other way than by adding a special case to wait for all the leases in a single job. But the latter is a little easier to backport.

**Comment by RichardJCai** [comment]
> Yeah, in 20.1 we create a separate job for every table and wait for all of them to finish. The jobs don't have any dependencies on each other, but we still have to wait for each of them to get adopted, etc.
> 
> Furthermore, the only thing these jobs do is wait for old leases to drain, so this is an extreme case of item 4 in #47790.
> 
> I'd rather fix this by getting rid of these jobs entirely and waiting for leases in some other way than by adding a special case to wait for all the leases in a single job. But the latter is a little easier to backport.

Do you know why the time it takes seems to be increasing exponentially with the number of tables?

**Comment by lucy-zhang** [comment]
> Do you know why the time it takes seems to be increasing exponentially with the number of tables?

What do you mean by exponentially? Do you have more data on the dependence between the number of tables and the time taken? I haven't tried running the script myself, but I would have expected the dependence to be more or less linear, since the jobs run independently of each other and we adopt some constant number of jobs simultaneously per node, but maybe it's much worse for some reason I'm not seeing.

**Comment by RichardJCai** [comment]
> > Do you know why the time it takes seems to be increasing exponentially with the number of tables?
> 
> What do you mean by exponentially? Do you have more data on the dependence between the number of tables and the time taken? I haven't tried running the script myself, but I would have expected the dependence to be more or less linear, since the jobs run independently of each other and we adopt some constant number of jobs simultaneously per node, but maybe it's much worse for some reason I'm not seeing.

I tried running GRANT * with varying number of tables and heres the results I got.

10 tables: 161.168ms
50 tables: 1.102255s
100 tables: 4.285835s
200 tables: 15.850779s
300 tables: 26.900821s
400 tables: 54.534966s
500 tables: 1m31.138571s

**Comment by lucy-zhang** [comment]
Thanks, that's good to know.

**Comment by RichardJCai** [comment]
Related issue, this issue details the root cause #50783
