### ISSUE TITLE
Kubernetes Error FailedAttachVolume after running cluster config process

### ISSUE THREAD

**Issue by drewdeally** [cockroachdb/cockroach#50163]
**Following steps at https://www.cockroachlabs.com/docs/stable/orchestrate-cockroachdb-with-kubernetes.html cluster fails after roughly after 30-45 minutes with** 

Events:
  Type     Reason              Age                 From                                                 Message
  ----     ------              ----                ----                                                 -------
  Warning  FailedMount         64s                 kubelet, gke-cockroachdb-default-pool-bdc3f8a3-2r8j  Unable to mount volumes for pod "cockroachdb-4_default(69cfb341-acee-11ea-a127-42010a8e0005)": timeout expired waiting for volumes to attach or mount for pod "default"/"cockroachdb-4". list of unmounted volumes=[datadir]. list of unattached volumes=[datadir default-token-v7fzp]
  Warning  FailedAttachVolume  55s (x9 over 3m8s)  attachdetach-controller                              AttachVolume.Attach failed for volume "pvc-69ccfb67-acee-11ea-a127-42010a8e0005" : GCE persistent disk not found: diskName="gke-cockroachdb-968ae1-pvc-69ccfb67-acee-11ea-a127-42010a8e0005" zone="us-east1-c"
M

  Warning  FailedMount         66s (x9 over 19m)   kubelet, gke-cockroachdb-default-pool-4f8d9a47-dhkk  Unable to mount volumes for pod "cockroachdb-3_default(69c9f500-acee-11ea-a127-42010a8e0005)": timeout expired waiting for volumes to attach or mount for pod "default"/"cockroachdb-3". list of unmounted volumes=[datadir]. list of unattached volumes=[datadir default-token-v7fzp]
  Warning  FailedAttachVolume  50s (x18 over 21m)  attachdetach-controller                              AttachVolume.Attach failed for volume "pvc-69c71d36-acee-11ea-a127-42010a8e0005" : GCE persistent disk not found: diskName="gke-cockroachdb-968ae1-pvc-69c71d36-acee-11ea-a127-42010a8e0005" zone="us-east1-b"

Events:
  Type     Reason              Age                  From                                                 Message
  ----     ------              ----                 ----                                                 -------
  Warning  FailedAttachVolume  107s (x18 over 22m)  attachdetach-controller                              AttachVolume.Attach failed for volume "pvc-0e380511-acee-11ea-a127-42010a8e0005" : GCE persistent disk not found: diskName="gke-cockroachdb-968ae1-pvc-0e380511-acee-11ea-a127-42010a8e0005" zone="us-east1-d"
  Warning  FailedMount         18s (x10 over 20m)   kubelet, gke-cockroachdb-default-pool-6b1ab706-bjv9  Unable to mount volumes for pod "cockroachdb-2_default(0e40f3ab-acee-11ea-a127-42010a8e0005)": timeout expired waiting for volumes to attach or mount for pod "default"/"cockroachdb-2". list of unmounted volumes=[datadir]. list of unattached volumes=[datadir default-token-v7fzp]
M

vents:
  Type     Reason              Age                 From                                                 Message
  ----     ------              ----                ----                                                 -------
  Warning  FailedScheduling    21m (x2 over 21m)   default-scheduler                                    0/8 nodes are available: 1 node(s) had volume node affinity conflict, 7 node(s) had taints that the pod didn't tolerate.
  Warning  FailedScheduling    21m                 default-scheduler                                    0/7 nodes are available: 1 node(s) had volume node affinity conflict, 6 node(s) had taints that the pod didn't tolerate.
  Normal   Scheduled           21m                 default-scheduler                                    Successfully assigned default/cockroachdb-1 to gke-cockroachdb-default-pool-bdc3f8a3-2r8j
  Warning  FailedMount         88s (x9 over 19m)   kubelet, gke-cockroachdb-default-pool-bdc3f8a3-2r8j  Unable to mount volumes for pod "cockroachdb-1_default(73581202-acf8-11ea-a127-42010a8e0005)": timeout expired waiting for volumes to attach or mount for pod "default"/"cockroachdb-1". list of unmounted volumes=[datadir]. list of unattached volumes=[datadir default-token-v7fzp]
  Warning  FailedAttachVolume  64s (x18 over 21m)  attachdetach-controller                              AttachVolume.Attach failed for volume "pvc-0e2dbc8e-acee-11ea-a127-42010a8e0005" : GCE persistent disk not found: diskName="gke-cockroachdb-968ae1-pvc-0e2dbc8e-acee-11ea-a127-42010a8e0005" zone="us-east1-c"
Mac

Events:
  Type     Reason              Age                 From                                                 Message
  ----     ------              ----                ----                                                 -------
  Warning  FailedMount         102s (x9 over 19m)  kubelet, gke-cockroachdb-default-pool-4f8d9a47-1wjh  Unable to mount volumes for pod "cockroachdb-0_default(0e29181d-acee-11ea-a127-42010a8e0005)": timeout expired waiting for volumes to attach or mount for pod "default"/"cockroachdb-0". list of unmounted volumes=[datadir]. list of unattached volumes=[datadir default-token-v7fzp]
  Warning  FailedAttachVolume  89s (x18 over 22m)  attachdetach-controller                              AttachVolume.Attach failed for volume "pvc-0e247f9e-acee-11ea-a127-42010a8e0005" : GCE persistent disk not found: diskName="gke-cockroachdb-968ae1-pvc-0e247f9e-acee-11ea-a127-42010a8e0005" zone="us-east1-b"
MacBook-Air:k8 andrewdeally$ 

kubectl get pods
NAME                 READY   STATUS              RESTARTS   AGE
cluster-init-6b79n   0/1     Completed           0          96m
cockroachdb-0        0/1     ContainerCreating   0          97m
cockroachdb-1        0/1     ContainerCreating   0          22m
cockroachdb-2        0/1     ContainerCreating   0          97m
cockroachdb-3        0/1     ContainerCreating   0          94m
cockroachdb-4        0/1     ContainerCreating   0          94m
kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                           STORAGECLASS   REASON   AGE
pvc-0e247f9e-acee-11ea-a127-42010a8e0005   100Gi      RWO            Delete           Bound    default/datadir-cockroachdb-0   standard                97m
pvc-0e2dbc8e-acee-11ea-a127-42010a8e0005   100Gi      RWO            Delete           Bound    default/datadir-cockroachdb-1   standard                97m
pvc-0e380511-acee-11ea-a127-42010a8e0005   100Gi      RWO            Delete           Bound    default/datadir-cockroachdb-2   standard                97m
pvc-69c71d36-acee-11ea-a127-42010a8e0005   100Gi      RWO            Delete           Bound    default/datadir-cockroachdb-3   standard                94m
pvc-69ccfb67-acee-11ea-a127-42010a8e0005   100Gi      RWO            Delete           Bound    default/datadir-cockroachdb-4   standard                94m

kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.36", GitCommit:"34a615f32e9a0c9e97cdb9f749adb392758349a6", GitTreeState:"clean", BuildDate:"2020-04-06T16:33:17Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

**Volumes appear to be present in the console

also prior received the following error**

33
 Warning  FailedMount         58s (x16 over 35m)  kubelet, gke-cockroachdb-default-pool-954ad68b-470b  Unable to mount volumes for pod "cockroachdb-1_default(1ba7f765-ac01-11ea-97f5-42010a960096)": timeout expired waiting for volumes to attach or mount for pod "default"/"cockroachdb-1". list of unmounted volumes=[datadir]. list of unattached volumes=[datadir certs cockroachdb-token-m556k]
  Warning  FailedAttachVolume  10s (x26 over 37m)  attachdetach-controller                              AttachVolume.Attach failed for volume "pvc-1ba13188-ac01-11ea-97f5-42010a960096" : GCE persistent disk not found: diskName="gke-cockroachdb-6210e9-pvc-1ba13188-ac01-11ea-97f5-42010a960096" zone="us-east4-c"

 Warning  FailedAttachVolume  11m                  attachdetach-controller                              Multi-Attach error for volume "pvc-689054aa-acb0-11ea-a478-42010a960097" Volume is already exclusively attached to one node and can't be attached to another

Jira issue: CRDB-4149

**Comment by jordanlewis** [comment]
Stale, please open a new issue if you're still seeing problems here
