### ISSUE TITLE
log: log lines collected by debug.zip seem to be truncated to 65K

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#50166]
It seems that log entries can be arbitrarily large, but when they're collected by the debug.zip (and I assume by the UI) through [this RPC](https://github.com/cockroachdb/cockroach/blob/ef7ab9bc810fd4be7755ebf8880e36ace9453f4b/pkg/cli/zip.go#L573) something seems to truncate them to 65KB each.
This is particularly unfortunate for query traces, which are a single entry (with many lines).

**Comment by andreimatei** [comment]
@knz The linked PR talks about a new log format, but the issue here was the log collection endpoint which does the truncation. Did this collection change?

**Comment by knz** [comment]
The linked pr ensures that no entry is larger than approx 1kb.
