### ISSUE TITLE
compaction queue remains unchanged for a long time

### ISSUE THREAD

**Issue by heidawei** [cockroachdb/cockroach#50174]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:
CRDB cluster has 6 nodes， USED CAPACITY  800GB， total CAPACITY 26TB

![image](https://user-images.githubusercontent.com/11207613/84557683-c2356900-ad5f-11ea-9544-2fc94e8503cf.png)

I want import 100GB data to cluster, so I add 3 nodes to cluster, I see the compaction status:

![image](https://user-images.githubusercontent.com/11207613/84557586-1ee45400-ad5f-11ea-82c9-d63cdef3e8c9.png)

12hours ago, the compaction queue remains unchanged for a long time, the bytes compaction/sec is 0B !!!!  
![image](https://user-images.githubusercontent.com/11207613/84557748-26582d00-ad60-11ea-8033-c05f85c6f747.png)

![image](https://user-images.githubusercontent.com/11207613/84557787-7505c700-ad60-11ea-8a70-8ef988730be4.png)

I do not known why??

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
2. Send SQL ... / CLI command ...
3. Look at UI / log file / client app ...

**Expected behavior**

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version [e.g. 2.0.x]
   V 19.2.4 release
 - Server OS: [e.g. Linux/Distrib]
   CentOS 7.6
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
What was the impact?

Jira issue: CRDB-4148

**Comment by jbowens** [comment]
The compaction queue no longer exists.
