### ISSUE TITLE
sql/opt: add implicit SELECT FOR UPDATE support for DELETE statements

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#50181]
Address this TODO:

https://github.com/cockroachdb/cockroach/blob/01a780bdc380d428611348a08aff301ae7c1938b/pkg/sql/opt/exec/execbuilder/mutation.go#L991-L999

Similar to https://github.com/cockroachdb/cockroach/issues/50180, but likely lower priority because sustained contending DELETEs don't seem to be as common, probably because once a row is deleted, it stays deleted and can't be deleted again.

Jira issue: CRDB-4147

**Comment by rytaft** [comment]
Is this a priority for 22.2?

**Comment by michae2** [comment]
This might be a good one for @wenyihu6 if interested.
