### ISSUE TITLE
storage: investigate whether facebook/rocksdb#6843 should be backported

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#50183]
https://github.com/facebook/rocksdb/pull/6843. See also https://github.com/facebook/rocksdb/pull/6882. There is a possible corruption bug when doing reverse iteration in RocksDB. @itsbilal did some initial work and we might unintentionally be safe from this bug due to the MVCC timestamp suffix we place on keys.

**Comment by mwang1026** [comment]
Closing since no supported version uses RockDB anymore
