### ISSUE TITLE
crash: disk stall detected: unable to sync log files within 30s

### ISSUE THREAD

**Issue by heidawei** [cockroachdb/cockroach#50196]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:
A node crash！！！
insert to CRDB. 
Why crash node when log write to disk timeout?

> F200615 06:38:02.091361 1702358741 util/log/clog.go:1279  disk stall detected: unable to sync log files within 30s
goroutine 1702358741 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc00007e500, 0xc00007e540, 0x0, 0x3e20700)
        /home/kdb_staging/kedis/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1024 +0xb8
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x6c4d7a0, 0xc000000004, 0x6427756, 0x10, 0x4ff, 0xc0382c36c0, 0x38)
        /home/kdb_staging/kedis/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:871 +0xa21
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x46a2020, 0xc000076070, 0x4, 0x2, 0x0, 0x0, 0xc0076e8fb0, 0x1, 0x1)
        /home/kdb_staging/kedis/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:66 +0x2c9
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x46a2020, 0xc000076070, 0x1, 0x4, 0x0, 0x0, 0xc0076e8fb0, 0x1, 0x1)
        /home/kdb_staging/kedis/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:69 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Shout(0x46a2020, 0xc000076070, 0xc000000004, 0xc0076e8fb0, 0x1, 0x1)
        /home/kdb_staging/kedis/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:87 +0xbf
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).flushAndSync.func1()
        /home/kdb_staging/kedis/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1279 +0x104
created by time.goFunc
        /usr/local/go/src/time/sleep.go:168 +0x44

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
2. Send SQL ... / CLI command ...
3. Look at UI / log file / client app ...

**Expected behavior**

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version [e.g. 2.0.x]
    V 19.2.4
 - Server OS: [e.g. Linux/Distrib]
    Centos 7.6
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
What was the impact?

Jira issue: CRDB-4144

**Comment by heidawei** [comment]
This bug appears again. In a cluster of five nodes, the read and write traffic is very low, and the TPS is only 50. Now a node suddenly causes the process to exit because of this exception. Dmesg does not get any meaningful information. The disk check proves that there is no problem. I restart the node and it can work normally.

**Comment by heidawei** [comment]
Add some logs
>  I200809 02:11:23.331354 659 gossip/gossip.go:566  [n2] gossip status (ok, 5 nodes)
gossip client (1/3 cur/max conns)
  3: 10.34.58.150:26257 (159h27m10s: infos 2029529/2720545 sent/received, bytes 372044144B/547374234B sent/received)
gossip server (0/3 cur/max conns, infos 4437439/6108831 sent/received, bytes 819081212B/1207781484B sent/received)
W200809 02:12:21.768805 144 gossip/gossip.go:1520  [n2] first range unavailable; resolvers exhausted
I200809 02:12:21.769293 28609803 gossip/client.go:124  [n2] started gossip client to 10.34.61.157:26257
log: exiting because of error: write /dev/stderr: input/output error
F200809 02:12:21.769426 28610362 util/log/clog.go:1279  disk stall detected: unable to sync log files within 30s
goroutine 28610362 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc0005d6300, 0xc0005d6300, 0x0, 0x7f52a24460d8)
        /home/kdb_staging/kedis/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1024 +0xb8
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x6d4a740, 0xc000000004, 0x6523a48, 0x10, 0x4ff, 0xc00db260c0, 0x38)
        /home/kdb_staging/kedis/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:871 +0xa21
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x4742960, 0xc000078090, 0x4, 0x2, 0x0, 0x0, 0xc0006b3fb0, 0x1, 0x1)
        /home/kdb_staging/kedis/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:66 +0x2c9
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x4742960, 0xc000078090, 0x1, 0x4, 0x0, 0x0, 0xc0006b3fb0, 0x1, 0x1)
        /home/kdb_staging/kedis/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:69 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Shout(0x4742960, 0xc000078090, 0xc000000004, 0xc0006b3fb0, 0x1, 0x1)
        /home/kdb_staging/kedis/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:87 +0xbf
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).flushAndSync.func1()
        /home/kdb_staging/kedis/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1279 +0x104
created by time.goFunc
        /usr/local/go/src/time/sleep.go:168 +0x44


****************************************************************************

This node experienced a fatal error (printed above), and as a result the
process is terminating.

**Comment by heidawei** [comment]
Can the discard command of SSD disk be the culprit ？

**Comment by heidawei** [comment]
![image](https://user-images.githubusercontent.com/11207613/89888833-2dd27000-dc03-11ea-8a02-a2d2af819d59.png)

![image](https://user-images.githubusercontent.com/11207613/89888881-4cd10200-dc03-11ea-98ab-3359e6d9b9c4.png)

may be rocksDB compaction is the culprit？？

**Comment by heidawei** [comment]
![image](https://user-images.githubusercontent.com/11207613/89890655-4abc7280-dc06-11ea-8ca6-768003a7f963.png)

disk dfa support Discard

**Comment by petermattis** [comment]
@itsbilal A disk stall case detected in the wild. Can you take a closer look? The information @heidawei has provided indicates there is a correlation with sstable deletions.

**Comment by itsbilal** [comment]
Thanks for attaching so much information on this!

Interesting that the log file sync timeout of 30s was hit, instead of the 10s one for the engine write-ahead log. Does grepping the Cockroach log for `disk stall detected: unable to write to` show anything before the other `disk stall` error that caused the node crash?

Perhaps the log flush stall should not fatal the process, and instead we should rely on checks elsewhere.

There's a chance the discard command is to blame here. Since I'd like to try reproducing this, can we get a bit more info on the sort of system you're running this on: specifically, the OS, file system, and any relevant disk details (bare metal SSDs or cloud instances with SSD TRIM support)? That'd be helpful - thanks!

**Comment by heidawei** [comment]
The log before node crash:

> I200809 02:10:02.792211 663 server/status/runtime.go:498  [n2] runtime stats: 12 GiB RSS, 723 goroutines, 239 MiB/157 MiB/432 MiB GO alloc/idle/total, 9.5 GiB/12 GiB C
GO alloc/total, 196.3 CGO/sec, 4.0/0.7 %(u/s)time, 0.0 %gc (0x), 1.8 MiB/1.6 MiB (r/w)net
I200809 02:10:12.792765 663 server/status/runtime.go:498  [n2] runtime stats: 12 GiB RSS, 723 goroutines, 272 MiB/133 MiB/432 MiB GO alloc/idle/total, 9.5 GiB/12 GiB C
GO alloc/total, 182.2 CGO/sec, 3.6/0.6 %(u/s)time, 0.0 %gc (0x), 1.5 MiB/2.1 MiB (r/w)net
I200809 02:10:22.792160 663 server/status/runtime.go:498  [n2] runtime stats: 12 GiB RSS, 723 goroutines, 304 MiB/109 MiB/432 MiB GO alloc/idle/total, 9.5 GiB/12 GiB C
GO alloc/total, 183.1 CGO/sec, 3.7/0.8 %(u/s)time, 0.0 %gc (0x), 1.7 MiB/2.1 MiB (r/w)net
I200809 02:10:23.326255 659 gossip/gossip.go:566  [n2] gossip status (ok, 5 nodes)
gossip client (1/3 cur/max conns)
  3: 10.34.58.150:26257 (159h26m10s: infos 2029417/2720249 sent/received, bytes 372027605B/547323392B sent/received)
gossip server (0/3 cur/max conns, infos 4437327/6108535 sent/received, bytes 819064673B/1207730642B sent/received)
W200809 02:10:24.254556 28608153 vendor/google.golang.org/grpc/server.go:703  grpc: Server.Serve failed to create ServerTransport: connection error: desc = "transport:
 http2Server.HandleStreams failed to receive the preface from client: EOF"
I200809 02:10:32.792704 663 server/status/runtime.go:498  [n2] runtime stats: 12 GiB RSS, 722 goroutines, 337 MiB/82 MiB/432 MiB GO alloc/idle/total, 9.5 GiB/12 GiB CG
O alloc/total, 200.1 CGO/sec, 3.7/0.7 %(u/s)time, 0.0 %gc (0x), 1.6 MiB/1.5 MiB (r/w)net
I200809 02:10:42.793255 663 server/status/runtime.go:498  [n2] runtime stats: 12 GiB RSS, 722 goroutines, 210 MiB/176 MiB/432 MiB GO alloc/idle/total, 9.4 GiB/12 GiB C
GO alloc/total, 216.0 CGO/sec, 7.1/0.9 %(u/s)time, 0.0 %gc (1x), 1.7 MiB/1.6 MiB (r/w)net
I200809 02:10:43.328339 642 storage/store.go:2445  [n2,s2] sstables (read amplification = 3):
0 [   1M   1 ]: 1M
5 [  61M  18 ]: 4M[14] 2M 1M 485K 346K
6 [ 418M 132 ]: 4M[96] 3M[5] 2M[5] 1M[2] 941K 918K 634K 461K 399K 318K 198K 147K 133K 120K 109K 102K 95K 84K 79K 75K 62K 58K 56K 47K 26K 24K 7K 2K
I200809 02:10:43.328455 642 storage/store.go:2446  [n2,s2]
** Compaction Stats [default] **
Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn Key
Drop
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
-----
  

>  L0      1/0    1.32 MB   0.5      0.0     0.0      0.0       1.9      1.9       0.0   1.0      0.0      5.6    358.13            353.30      1498    0.239       0 0
 L5     18/0   60.94 MB   1.0     46.5     1.9     44.5      45.9      1.4       0.0  23.7     82.1     81.1    580.06            569.39       749    0.774    265M  6 287K
 L6    132/0   417.80 MB   0.0     75.0     1.4     73.6      73.6      0.0       0.0  52.5     84.4     82.8    910.38            895.12       809    1.125    312M 79M
 Sum    151/0   480.06 MB   0.0    121.5     3.3    118.1     121.5      3.4       0.0  62.6     67.3     67.3   1848.57           1817.80      3056    0.605    577M 85M
 Int      0/0    0.00 KB   0.0      0.2     0.0      0.2       0.2      0.0       0.0  61.6     68.3     68.5      2.42              2.38         4    0.604    729K 115K

> ** Compaction Stats [default] **
Priority    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 

> Low      0/0    0.00 KB   0.0    121.5     3.3    118.1     119.6      1.4       0.0   0.0     83.5     82.1   1490.44           1464.50      1558    0.957    577M    85M
High      0/0    0.00 KB   0.0      0.0     0.0      0.0       1.9      1.9       0.0   0.0      0.0      5.6    358.12            353.30      1497    0.239       0      0
User      0/0    0.00 KB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0     23.7      0.01              0.00         1    0.014       0      0
Uptime(secs): 665420.6 total, 600.0 interval
Flush(GB): cumulative 1.941, interval 0.003
AddFile(GB): cumulative 0.000, interval 0.000
AddFile(Total Files): cumulative 0, interval 0
AddFile(L0 Files): cumulative 0, interval 0
AddFile(Keys): cumulative 0, interval 0
Cumulative compaction: 121.51 GB write, 0.19 MB/s write, 121.49 GB read, 0.19 MB/s read, 1848.6 seconds
Interval compaction: 0.16 GB write, 0.28 MB/s write, 0.16 GB read, 0.28 MB/s read, 2.4 seconds
Stalls(count): 0 level0_slowdown, 0 level0_slowdown_with_compaction, 0 level0_numfiles, 0 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 0 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 0 total count
estimated_pending_compaction_bytes: 0 B
I200809 02:10:52.793013 663 server/status/runtime.go:498  [n2] runtime stats: 12 GiB RSS, 722 goroutines, 242 MiB/155 MiB/432 MiB GO alloc/idle/total, 9.4 GiB/12 GiB CGO alloc/total, 225.1 CGO/sec, 3.5/0.8 %(u/s)time, 0.0 %gc (0x), 1.6 MiB/1.5 MiB (r/w)net
I200809 02:11:02.793153 663 server/status/runtime.go:498  [n2] runtime stats: 12 GiB RSS, 723 goroutines, 274 MiB/133 MiB/432 MiB GO alloc/idle/total, 9.4 GiB/12 GiB CGO alloc/total, 244.8 CGO/sec, 3.8/0.7 %(u/s)time, 0.0 %gc (0x), 1.7 MiB/1.6 MiB (r/w)net
I200809 02:11:12.793634 663 server/status/runtime.go:498  [n2] runtime stats: 12 GiB RSS, 723 goroutines, 307 MiB/106 MiB/432 MiB GO alloc/idle/total, 9.4 GiB/12 GiB CGO alloc/total, 223.8 CGO/sec, 3.8/0.6 %(u/s)time, 0.0 %gc (0x), 1.6 MiB/2.1 MiB (r/w)net
I200809 02:11:22.793177 663 server/status/runtime.go:498  [n2] runtime stats: 12 GiB RSS, 723 goroutines, 341 MiB/75 MiB/432 MiB GO alloc/idle/total, 9.4 GiB/12 GiB CGO alloc/total, 215.2 CGO/sec, 3.8/0.9 %(u/s)time, 0.0 %gc (0x), 1.7 MiB/2.1 MiB (r/w)net
I200809 02:11:23.331354 659 gossip/gossip.go:566  [n2] gossip status (ok, 5 nodes)
gossip client (1/3 cur/max conns)
  3: 10.34.58.150:26257 (159h27m10s: infos 2029529/2720545 sent/received, bytes 372044144B/547374234B sent/received)
gossip server (0/3 cur/max conns, infos 4437439/6108831 sent/received, bytes 819081212B/1207781484B sent/received)
W200809 02:12:21.768805 144 gossip/gossip.go:1520  [n2] first range unavailable; resolvers exhausted
I200809 02:12:21.769293 28609803 gossip/client.go:124  [n2] started gossip client to 10.34.61.157:26257
log: exiting because of error: write /dev/stderr: input/output error
F200809 02:12:21.769426 28610362 util/log/clog.go:1279  disk stall detected: unable to sync log files within 30s
goroutine 28610362 [running]:

and the system info:
cat /proc/version
Linux version 3.10.0-1.0.1.el7.x86_64 (root@bjfk-rs10690.yz02) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Thu Dec 13 10:57:52 CST 2018

df -aT
/dev/dfa                                 xfs           3123474124        754460    3122719664    1% /media/dfa

cat /sys/block/dfa/queue/rotational
0

cat /sys/block/dfa/queue/discard_granularity
4096

> RedHat Enterprise Linux 6.3 and earlier, only ext4 file system fully supports discard. Since RedHat Enterprise Linux 6.4, ext4 and XFS have fully supported discard.

Is the RedHat version helpful for this issue？

**Comment by heidawei** [comment]
@itsbilal  Hi, Similar phenomenon appears again, but this time without panic, we have more monitoring data in case of accidents.

![image](https://user-images.githubusercontent.com/11207613/90716310-3d2a7b00-e2df-11ea-9903-c44e7825a1db.png)

![image](https://user-images.githubusercontent.com/11207613/90716363-5df2d080-e2df-11ea-824c-a1a8d1699daa.png)

![image](https://user-images.githubusercontent.com/11207613/90716429-87abf780-e2df-11ea-8d4b-d58b6b0b2ec0.png)

![image](https://user-images.githubusercontent.com/11207613/90716499-a9a57a00-e2df-11ea-924b-1c4781891a4c.png)

![image](https://user-images.githubusercontent.com/11207613/90716520-ba55f000-e2df-11ea-9f1e-179fb6586934.png)

![image](https://user-images.githubusercontent.com/11207613/90716560-d6f22800-e2df-11ea-82f9-d910446c75ea.png)

![image](https://user-images.githubusercontent.com/11207613/90716613-f5f0ba00-e2df-11ea-9120-e02259748ed7.png)

![image](https://user-images.githubusercontent.com/11207613/90716645-0acd4d80-e2e0-11ea-9318-ac57786853d7.png)

**Comment by heidawei** [comment]
![image](https://user-images.githubusercontent.com/11207613/90729577-635d1480-e2f9-11ea-8e6e-f2a885ae473a.png)

**Comment by heidawei** [comment]
@itsbilal  @petermattis  I can now stably reproduce this problem. When I use the deleterange to delete a large range of data blocks, this bug will be triggered. I start cockroachdb on my Mac computer, and then import 2.9GB of data. Then I modify part of the code appropriately, so that I can directly call deleterange, and then the bug reappears, combined with the previous monitoring and In the recent [issue 53192](https://github.com/cockroachdb/cockroach/issues/53192), I think these two problems are actually the same, that is, delete range delete a large range of data. At present, we can see that prunetime series will be called in cockroachdb, and it has also been confirmed at the log level.

**Comment by itsbilal** [comment]
@heidawei Interesting, thanks for laying out the steps you took! Just confirming, when you say "modify part of the code appropriate, so you can directly call deleterange" you're referring to the DeleteRange call right into RocksDB / the storage engine, right? Not `MVCCDeleteRange`?

And you were also able to reproduce this on a Mac? I'll see if I'm able to reproduce spiking disk latency after a lot of discarded blocks as well.

Out of curiosity, did you try out the deletion pacing patch I mentioned in the last comment to see if it made a difference?

**Comment by heidawei** [comment]
@itsbilal  I call  batch.DeleteRange which will can MVCCDeleteRange to simulate GC time series.
 I'm very sorry, I haven't had the chance to verify your patch yet.

I recently tried to adjust the GC parameters of time series, and now it seems that the effect is obvious. So far, I haven't seen a large GC pause delay

> set cluster setting timeseries.storage.resolution_10s.ttl='72h';

> set cluster setting timeseries.storage.resolution_30m.ttl='240h';
