### ISSUE TITLE
sql: add option to remove internal queries from slow query log

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#50201]
The new slow query log allows developers to log all queries that take longer that an user specified time threshold. For example, you could set the threshold to 100ms:
`SET CLUSTER SETTING sql.log.slow_query.latency_threshold = '100ms';`

These queries are then logged in the slow query log `cockroach-sql-slow.log`

Today, both internal and user-specified queries are logged. This is good because both queries can impact cluster performance. However, users have limited ability to influence internal queries and will need to report them to CRDB to improve upon them. Further, it can be hard for the user to find their own queries if many internal queries show up. Look at this gist of the 500+ queries that show up when restoring tpc-c data with 100ms threshold set https://gist.github.com/awoods187/e0362023029b3ed509cb6cefcf6024ea (note this is only halfway through the restore).

I think we should seek out a solution that makes it easier to see user (and not internal) queries. We could:

1. Make an additional log that only shows internal queries and removes them from the slow log. Something like `cockroach-sql-slow-internal-only.log`
2. Add an additional field specifying if its internal or not that allows for filtering 
3. Add a cluster setting to add internal queries to the log (or one to remove). Something like ``SET CLUSTER SETTING sql.log.slow_query.internal = 'true';`

**Comment by rohany** [comment]
The log tag of `exec` or `exec-internal` is a filter that currently exists for #2.
