### ISSUE TITLE
server: heap profile dumper probably fails on loaded nodes

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#50234]
Investigated a customer cluster which was seeing a lot of allocations per second (and thus presumably a lot of Go GC pressure).
Despite steadily increasing RAM usage over multiple minutes, no heap profiler dumps were collected.

I went to investigate the code and found this:

```go
        // We read the heap stats on another goroutine and give up after 1s.
        // This is necessary because as of Go 1.12, runtime.ReadMemStats()
        // "stops the world" and that requires first waiting for any current GC
        // run to finish. With a large heap and under extreme conditions, a
        // single GC run may take longer than the default sampling period of
        // 10s. Under normal operations and with more recent versions of Go,
        // this hasn't been observed to be a problem.
        statsCollected := make(chan struct{})
        if atomic.CompareAndSwapInt32(&collectingMemStats, 0, 1) {
          if err := s.stopper.RunAsyncTask(ctx, "get-mem-stats", func(ctx context.Context) {
            var ms status.GoMemStats
            runtime.ReadMemStats(&ms.MemStats)
            ms.Collected = timeutil.Now()
            log.VEventf(ctx, 2, "memstats: %+v", ms)

            goMemStats.Store(&ms)
            atomic.StoreInt32(&collectingMemStats, 0)
            close(statsCollected)
          }); err != nil {
            close(statsCollected)
          }
        }

        select {
        case <-statsCollected:
          // Good; we managed to read the Go memory stats quickly enough.
        case <-time.After(time.Second):
        }

        curStats := goMemStats.Load().(*status.GoMemStats)
```

If my reading is right, if `runtime.ReadMemStats` fails to complete within 1 second, the dumper will proceed with an empty set of metrics.

Should we not give it a bit more breathing room than thus 1 second?

**Comment by knz** [comment]
This is concerning because MaybeTakeProfile has this:

```go
  takeProfile ≔ curHeap > o.highwaterMarkBytes
  if ¬takeProfile {
    return
  }
```

cc @bdarnell @tbg for advice

**Comment by knz** [comment]
I think a better way forward is to change the code as follows:

- *if the metric was sampled successfully*, then check curHeap > high water mark
- *if the metric was NOT sampled* take the heap dump in any case

**Comment by andreimatei** [comment]
> If my reading is right, if runtime.ReadMemStats fails to complete within 1 second, the dumper will proceed with an empty set of metrics.

Empty metrics, or the last collected metrics?

**Comment by knz** [comment]
> Empty metrics, or the last collected metrics?

doesn't matter - if it's the last, the threshold `curHeap > o.highwaterMarkBytes` will be false

**Comment by knz** [comment]
Discussed with Ben: even though today's GC doesn't incur *pause* times larger than 1s any more, it's possible that GC runnin asynchronously still incurs long wait times in `runtime.ReadMemStats()`.

This would explain why we don't get heap profiler dumps in loaded cluster epsecially when they're close to OOM.

**Comment by knz** [comment]
Ok Ben points out that the stats are collected all right, because `SampleEnvironment` emits log lines regularly.

**Comment by tbg** [comment]
Btw if the stats are not ready within 1s we print so something like [stale]
in the runtime stats log line, were you seeing this in the instance that
prompted this finding?

**Comment by knz** [comment]
nope, all this is a red herring. I found the cause it's not here.

**Comment by knz** [comment]
saga continues here: #50237
