### ISSUE TITLE
sql: provide explicit mechanism for users to modify system tables

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#50302]
**Is your feature request related to a problem? Please describe.**

In rare repair scenarios it is often necessary to repair data in system tables in response to a bug. Today we work around not having a condoned approach by hacking access to the "node" user into the users table and granting it to "root".

**Describe the solution you'd like**
Ideally we could provide a session-bound option to grant these capabilities to just a "root" SQL session that will not live beyond the life of that session.

**Describe alternatives you've considered**

We've considered more drastic approaches like requiring some secret minted by cockroach labs or something like that.

**Comment by knz** [comment]
cc @thtruo @aaron-crl to put on the security radar.

**Comment by ajwerner** [comment]
See https://github.com/cockroachdb/cockroach/issues/50948 and its comments for thinking about how to support the desired functionality explicitly. Today's hack of mucking with the `system.users` table is almost certainly worse.

**Comment by knz** [comment]
@ajwerner how would you feel about granting SELECT/INSERT/UPDATE on the `system` db to another role than `admin` for this purpose?

@solongordon this may be another use case for having db-level privs inherited for objects inside the db.

**Comment by ajwerner** [comment]
I'm going to close this with #55699.
