### ISSUE TITLE
sql: `CREATE USER VALID UNTIL 'infinity'` misinterpreted

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#50301]
**Describe the problem**

Postgres supports `CREATE USER ... VALID UNTIL 'infinity'`. CockroachDB interprets this as a date in the distant past, resulting in a user that is immediately invalid. 

**To Reproduce**

```
# Server version: CockroachDB CCL v20.1.1 (x86_64-apple-darwin14, built 2020/05/19 14:40:33, go1.13.9) (same version as client)
# Cluster ID: 7e309b0e-c4aa-412d-a3e2-935af6dd2f5c
# Organization: Cockroach Demo
#
# Enter \? for a brief introduction.
#
root@127.0.0.1:52275/movr> create user foo valid until 'infinity';
CREATE ROLE

Time: 5.722ms

root@127.0.0.1:52275/movr> show users;
  username |                        options                        | member_of
-----------+-------------------------------------------------------+------------
  admin    | CREATEROLE                                            | {}
  foo      | VALID UNTIL=-292277022365-05-08 08:17:07.854776+00:00 | {}
  root     | CREATEROLE                                            | {admin}
(3 rows)
```

**Expected behavior**

`VALID UNTIL inifinity` should result in a user that never expires (just as if the VALID UNTIL clause were omitted), instead of one that is already expired. (Or at least it should be an error instead of silently producing the wrong results)

**Comment by rohany** [comment]
cc @RichardJCai or @otan

**Comment by RichardJCai** [comment]
It seems like CRDB doesn't support casting infinity to TIMESTAMPTZ.

```
root@127.0.0.1:53332/movr> select 'infinity'::timestamptz;
ERROR: timestamp "-292277022365-05-08T08:17:07Z" exceeds supported timestamp bounds
```

**Comment by otan** [comment]
the change to infinity is available in 20.2.
for 20.1, #41564 still exists. i'll leave that for @RichardJCai to solve :)

**Comment by otan** [comment]
actually, whoa, rereading #41564 looks like we need to handle timestamps being infinity o_o

**Comment by otan** [comment]
folding this into #41564
