### ISSUE TITLE
webui: add survey to statements page

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#50313]
We are currently working on investing a large amount of work in improving the statements page as a part of improving the overall user journeys around slow query identification and slow query debugging. We have collected feedback from customers opportunistically, but it would be great if we could collect more feedback from customers on a regular cadence. 

The docs team currently employs a survey on every page--why can't we do this on the webui?
![image](https://user-images.githubusercontent.com/22278911/84834582-b8ca2c00-afff-11ea-836c-adbfb33554df.png)
![image](https://user-images.githubusercontent.com/22278911/84834572-b2d44b00-afff-11ea-9bfb-f6e2db8b4c46.png)

I think we should ask these questions on the webui for each page. As an mvp, we can start with just the statements page. 

1. How helpful was this page to you on a scale of 1 to 10? 
2. What could be done to improve the usefulness of this page?
3. Share your email for additional support (optional)

Jira issue: CRDB-4134

**Comment by awoods187** [comment]
@Annebirzin what do you think of this?

**Comment by Annebirzin** [comment]
@awoods187 I like the idea of capturing customer feedback this way. This might a good opportunity to leverage AppCues (which we use in CockroachCloud). I think it has survey modules like this built in.

**Comment by awoods187** [comment]
Can I convince you that we should try this out in an upcoming milestone? What would it take for us to prototype it out?

**Comment by Annebirzin** [comment]
Yep, I think it would be great to try out. I can work on creating a prototype 

I'm not sure what it will take to get Appcues running in the Admin UI (this is something we'd like to add for onboarding in the Admin UI). @dhartunian any input on what it might take to use Appcues in the Admin UI?

**Comment by Annebirzin** [comment]
@awoods187 I created a quick prototype in Appcues to simulate what this could looks like (the radio button component wasn't working in the second step)

![Kapture 2020-06-23 at 12 11 52](https://user-images.githubusercontent.com/51920721/85428358-10f6b600-b54b-11ea-9b06-fad5c0a2a8e1.gif)

**Comment by awoods187** [comment]
this is really cool!

**Comment by dhartunian** [comment]
I *love* this idea! I think it could result in a lot of great actionable feedback. I think it could be rolled into a sprint next month. Ideally we would add an endpoint to the registration server to grab this info or pipe it into Segment as an event with some metadata.

I think the biggest obstacles will be:
1. Ensuring extra data isn't collected (AppCues probably won't fly unless we do explicit opt-in or something. It loads via. its own JS)
2. Providing an easy way to disable for "pro" customers. Already have a ticket to do this for the release notes signup

**Comment by awoods187** [comment]
awesome! let me know if i can help or what's needed but this would be so cool to fit into the next sprint.

**Comment by dhartunian** [comment]
@awoods187 after discussion with @piyush-singh we think this is a feature better suited to CC once we get the statements page up and running in there.

I think since CC targets developers, this kind of messaging is easier to deploy in there rather than with on-prem customers where it's more costly to build something that's easily disable-able and unintrusive. on CC it's much easier to enable/disable this for customers and use third party tools like AppCues to deploy the questionnaire.

**Comment by awoods187** [comment]
Stripe does something similar >This philosophy comes through in the Stripe dashboard. A button that reads “Feedback about this page?” stands prominently in the top right corner of every page of the dashboard
https://subvert.substack.com/p/stripe-building-a-developer-cult

**Comment by jordanlewis** [comment]
Closing, this is best managed in CC world now.
