### ISSUE TITLE
backupccl: streamline cluster restore in a "non-fresh" cluster

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#50338]
We are more frequently seeing use cases where cluster restore is performed into a "non-fresh" cluster, that is a cluster with user data. The current way to do this is to ensure that all user created databases/tables are dropped and GC'd. This is currently a clunky user experience.

We have floated a couple of possibilities:
1. Add a flag to the KV options of `RESTORE` which indicates the restore should wipe any existing user data.
2. Add a separate superuser command which performs this destructive wiping operation, which can be run before a cluster restore.

Jira issue: CRDB-4132

**Comment by mwang1026** [comment]
Is there a world where we can full cluster restore into a cluster and just ignore the fact that there is data there? What are the risks therein?

**Comment by pbardea** [comment]
We chatted yesterday, but for now since full cluster restore should not do any re-keying we'll need to remove the old data before restoring. We also want to eventually get rid of old data to free up the space.
