### ISSUE TITLE
sql: create/drop type doc links break the nightly builds

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#50331]
Found while investigating #50281: nightly CI runs on the `master` branch fail deterministically, choking on the following non-existent doc pages:

- https://www.cockroachlabs.com/docs/v20.2/drop-type.html
- https://www.cockroachlabs.com/docs/v20.2/create-type.html

This is expected (the doc doesn't exist yet).

I think there's a process adjustment necessary here: **the PR that adds the doc links  in sql.y should not be merged before the doc pages are up.**

As an intermediate corrective action here, I suggest to temporarily disable these doc links (until the corresponding doc project completes), then revert that to put them back in.

**Comment by knz** [comment]
cc @jseldess to see if you have a better solution about process

**Comment by jseldess** [comment]
@knz, should we consider empowering the docs writer to be the one to add docs links in sql.y as part of the documentation process? I'm worried this will be hard to coordinate otherwise. Perhaps not, if the team has an explicit planning/sprint process. @awoods187, for PM input.

**Comment by knz** [comment]
It makes sense to me that doc writers adjust these links.

**Comment by jseldess** [comment]
Thanks, @knz. I think we need to figure out how to document that process so writers can do this. Might as well start with one of the two new sql statements mentioned above. Since @ericharmeling would be documenting those, can you walk him through the process, @knz? @ericharmeling, it'd be great if you could then help document that process and share with the rest of the docs team.

**Comment by knz** [comment]
No problem at all, I'm glad to explain. Pick any time that works for you.

**Comment by ericharmeling** [comment]
@knz 
Happy to help unblock things here.

> As an intermediate corrective action here, I suggest to temporarily disable these doc links (until the corresponding doc project completes), then revert that to put them back in.

I agree with taking this course of action. 

I don't think we want to make documentation a blocker on merging anything to `cockroachdb`, especially testing release PRs. Happy to discuss further offline.
