### ISSUE TITLE
pgwire: improve error messaging for large requests in prepared statements

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#50330]
A customer recently tried to complete a large transaction and ran into the hard limit of 16MB with this error message:
```SQL
Error message:
invalid syntax: statement ignored: unexpected error: write tcp 127.0.0.1:47362->127.0.0.1:26257: write: connection reset by peer
warning: error retrieving the transaction status: driver: bad connection
warning: connection lost!
opening new connection: all session settings will be lost
```
This error message is fairly opaque and hard to understand. We should try to improve this error message so that customers can understand that this is our limit. 

We could also add hints that encourage the customer to break this into smaller transactions.

**Comment by awoods187** [comment]
cc @kai-niemi

**Comment by awoods187** [comment]
@bdarnell or @knz what do you think of this? How involved would updating this message be?

**Comment by knz** [comment]
This a pgwire issue. It's possible to improve this - we could ignore all the bytes until the end of the input stream, then respond with a proper pg error, instead of closing the connection.

**Comment by bdarnell** [comment]
Consuming and ignoring excess bytes also has a cost. We should see whether we could respond with an error message and close the connection without consuming everything else. (of course this is possible on our side; the question is whether clients would actually display the error instead of "bad connection").

**Comment by knz** [comment]
> Consuming and ignoring excess bytes also has a cost.

What cost would that be?

**Comment by bdarnell** [comment]
It's small - just a bit of CPU and holding the file descriptor open for as long as it takes for the data to come in. But if someone comes along and sends a header for a 4GB query, do we really want to slurp in the whole thing before telling them "no"?

**Comment by knz** [comment]
1) I don't mind about slurping 4gb

2) if we decide to make it a concern, we could have two limits. the low one slurps and reports an error (eg up to 100MB) and close the conn beyond that

**Comment by otan** [comment]
Prototype here: https://github.com/cockroachdb/cockroach/pull/53701

Lessons learnt:
* Client won't read errors until it sees the `Sync` command, so we need to write the error on pgwire and ignore everything else up to `Sync`.
* The TODO jordan wrote to consider ignoring errors until `Sync` for prepared statements is required here to make this clean, i believe.

I think this is dangerous for a stability period, might as well wait and re-write this properly later...

**Comment by awoods187** [comment]
Let's discuss tomorrow. I think we need to include this message.

**Comment by otan** [comment]
done for 20.2, putting in the backlog for 21.1 (needs reworking of the loop for prepared statements)

**Comment by recursionbane** [comment]
Does this mean the largest single write to a row or field is 16MiB?

**Comment by otan** [comment]
not necessarily, this is just the size to allocate a buffer when reading in a SQL query. you can increase this - `SET CLUSTER SETTING sql.conn.max_read_buffer_message_size = '32 KiB'`.

**Comment by recursionbane** [comment]
If I set that cluster setting to a large number (say, 2GB), will I be able to actually set a field value to a string that large?

**Comment by otan** [comment]
i think you'll run into limits on range sizes (see https://www.cockroachlabs.com/docs/v20.2/architecture/distribution-layer.html), which you can also increase. also some types have size limits built-in. you may also hit memory capabilities per query. YMMV, but you should get an error message when you hit some sort of limit.

**Comment by knz** [comment]
It's actually possible for the cluster to become unhealthy due to large values before you get any clear error message about it.

We recommend keeping individual stored values inside a row cell under a few megabytes for a reason.
