### ISSUE TITLE
ui: node map produces 500 error with unprivileged user

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#50360]
Repro:

1. Start a cluster of any size
2. Create a new user:

```root@127.0.0.1:53473/defaultdb> create user foo;
CREATE ROLE

Time: 2.583ms

root@127.0.0.1:53473/defaultdb> alter user foo with password 'foo';
ALTER ROLE

Time: 60.572ms
```

3. Log into the web ui, go to the node map:

![image](https://user-images.githubusercontent.com/43821/84936992-1e262780-b0a9-11ea-8c80-aa9bdc552b9c.png)

Jira issue: CRDB-4130

**Comment by jordanlewis** [comment]
@dhartunian is there a Project issues like this should be assigned to? I think I'm not up to date with how to file bugs like this.

**Comment by jordanlewis** [comment]
Oh it looks like this is a known issue / expected outcome:

https://www.cockroachlabs.com/docs/v20.1/admin-ui-overview.html#admin-ui-access

I guess the only complaint is that it's a 500 and not a `Forbidden` message, then.

**Comment by dhartunian** [comment]
Admin UI issues can go into "Observability" project triage bucket. Piyush and I review that regularly.

We are in the middle of revising error messages for some of these so thanks for filing!

**Comment by Annebirzin** [comment]
@piyush-singh @dhartunian Here is a figma link to designs for [permission states](https://www.figma.com/file/wLjM816v8wwesuIDkar9oN/obsrv_admin-ui-permissions?node-id=1%3A10) in the Admin UI. (Below are screenshots for the data distribution page, events page and node map)

The figma file also includes designs for database page permissions for ticket #49782 that @celiala opened. 

cc @taroface for feedback on permission messaging. I kept it very generic so it could be used across pages:  
`You do not have permission to view this information. Learn more`

![DataDistribution_001](https://user-images.githubusercontent.com/51920721/86149914-a1447600-baca-11ea-96e2-f72acd98082a.png)
![Events_001](https://user-images.githubusercontent.com/51920721/86149917-a1dd0c80-baca-11ea-9253-12b11cd5e92d.png)
![NodeMap_001](https://user-images.githubusercontent.com/51920721/86149919-a1dd0c80-baca-11ea-9e20-f0947ef62c11.png)

**Comment by taroface** [comment]
@Annebirzin Looks good to me. Does/can the link point to a version-specific https://www.cockroachlabs.com/docs/v20.1/admin-ui-overview.html#admin-ui-access ?

**Comment by Annebirzin** [comment]
@koorosh do you know if the 'learn more' links on these error messages currently point to a version specific article? (see ryan's comment above)

**Comment by koorosh** [comment]
@Annebirzin , @taroface , 
yes, it points to the version-specific doc page as Ryan mentioned.
```
https://www.cockroachlabs.com/docs/v20.2/admin-ui-overview.html#admin-ui-access
```

**Comment by nkodali** [comment]
Resolved by https://github.com/cockroachdb/cockroach/pull/50869. Closing issue.
