### ISSUE TITLE
ui: `HEALTH` status refreshing label flickers for a brief moment

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#5036]
It's distracting...it keeps flickering because it's only on screen for a brief split second. I'd argue that we don't show it until it's been refreshing for 1s already, and then make sure it stays up for at least 1s afterwards, even if the refreshing finishes before then.

**Comment by maxlang** [comment]
This is being temporarily removed by #4975 for now and we can come up with a better solution later.

**Comment by maxlang** [comment]
Gone as of #4975
