### ISSUE TITLE
kv: improve abort span GC behavior

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#50376]
We've recently (#40815) seen issues where the abort span got too large, and the
GC process attempting to clean it up continually timed out (the abort span GC
didn't paginate keys back then). We were then effectively stuck with this huge
abort span, and had to send the user over a custom binary that paginated the
deletion of the abort span entries. This pagination was merged into CRDB in
#45444, but there's a bit of leftover work here to improve our story around
abort span GC.

1. We don't currently track the abort span keys in MVCCStats (#27055), so it
   doesn't get factored in for GC decisions. What this means is that if there
   was a rapid build up of abort span entries, users would have to manually
   plumb the faulty replica the GC queue. 
   (a) Lets start tracking the abort span size in MVCCStats.
   (b) If that doesn't work, we can heuristically run GC if we detect sysbytes
    exceeding a 64MB threshold.

2. The local key ranges (which the abort span keys are a part of) are processed
  after the user key ranges. Even if no user keys are GC'able, all of it has to
  be scanned regardless (to arrive at that conclusion). With a large enough
  range size (which is potentially a more likely problem now given our default
  range sizes are 512 MB), this scan could theoretically consume the entirety
  of the time budget (in which case we're back to never being able to GC abort
  span entries, or doing it far too slowly)
  (a) Instead of having a hard limit for the GC timeout, if it was a scaled as
    function of the range size, that would mitigate this issue.
  (b) We could default to GC-ing local key ranges first.
  (c) We could do both.

---

(Mostly a top-level tracking issue, copying discussions whatever is linked 
below. Also of interest: #45573)

**Comment by ajwerner** [comment]
> (b) If that doesn't work, we can heuristically run GC if we detect sysbytes
exceeding a 64MB threshold.

I'd augment this with some logic that refers to the last GC time. Like, if the sysbytes exceeds 64MB and we haven't run GC in an hour. 

> (a) Instead of having a hard limit for the GC timeout, if it was a scaled as
function of the range size, that would mitigate this issue.

This is really easy to do, we have the technology. See: https://github.com/cockroachdb/cockroach/blob/f8821feab1b21b7c60d55b37c7a050282986d77a/pkg/kv/kvserver/queue.go#L313-L314 and for implementation inspiration: https://github.com/cockroachdb/cockroach/blob/f8821feab1b21b7c60d55b37c7a050282986d77a/pkg/kv/kvserver/queue.go#L68-L74

> (c) We could do both.

:+1:

**Comment by tbg** [comment]
We're already doing 1b):

https://github.com/cockroachdb/cockroach/blob/47a3b687cbd016f1e6d828337549e1b88c9bedc0/pkg/kv/kvserver/gc_queue.go#L346-L350

I also like 2c).

Thanks for writing this up!
