### ISSUE TITLE
Produce statement diagnostics from CLI

### ISSUE THREAD

**Issue by chriscasano** [cockroachdb/cockroach#50403]
In 20.1, we introduced producing statement diagnostics from the statements page which creates a bundle of terrific query data points to investigate.  It would be terrific to produce this same output from the CLI from administrators.  Some enterprise customers may not use the admin UI and would need to resort to the CLI to produce this type of output as well.  Additionally supporting admin users authenticating through the GSSAPI should be considered too.

**Comment by awoods187** [comment]
You can access this from the SQL shell `EXPLAIN ANALYZE (debug)` but I think you are asking to be able to do this without opening up the webui at all which is covered in this issue https://github.com/cockroachdb/cockroach/issues/48597#issuecomment-625933917.

I'm going to close this as a dup but let me know if I missed anything here.
