### ISSUE TITLE
testing: create out-of-band skip list

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#50412]
Currently, skipping a flaky test requires adding a `t.Skip` line to the test in question, committing it, and merging the PR. This can take at least 1 hour end to end, because of the latency of merging a PR.

Proposal: implement an out-of-band skip list that is injected into TeamCity tests. When running tests, the skip list can consult the out-of-band skip list to determine whether to skip a test. We can hook into the leaktest annotation that's already added to every test and enforced via the linter.

Jira issue: CRDB-4126

**Comment by otan** [comment]
Is leaktest really added to every test though? Thought it was only certain packages.
