### ISSUE TITLE
'SHOW RANGE FOR ROW' is tedious and has a documentation bug

### ISSUE THREAD

**Issue by riking** [cockroachdb/cockroach#50420]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

What did you do? Describe in your own words.

Attempt to see range information about a TwitchRunsCockroachDB table.

If possible, provide steps to reproduce the behavior:

`show range from table fillup_keyed for row (0.473978965894414, '000042b8-919e-4242-b8b1-3baca5af520d'::uuid, '9810ed7c-2fdb-4fe0-bed6-266d594fa188'::uuid,'6998db75-b8c6-49bb-b973-a54988e0d93a'::uuid, '96bdd0ca-bdb7-49b1-9b88-761f6ed04191'::uuid,'a9e1df35-f7a5-4d5b-9d79-87642d501abd'::uuid, '4f922bad-739b-45da-97ca-d9f377da03b9'::uuid)`

returns

> only users with the admin role are allowed to read crdb_internal.ranges_no_leases

**Expected behavior**

Get range information. Additionally, get range information without typing out entire rows.

The documentation states that SHOW RANGE FOR ROW is available if you have SELECT on the table: https://www.cockroachlabs.com/docs/v20.1/show-range-for-row.html

Typing out the entire row content is extremely tedious. It would be better if SHOW RANGE FOR ROW allowed you to sub-SELECT a single row using other criteria.

**Additional data / screenshots**

https://clips.twitch.tv/BlueBlindingBearTooSpicy

**Environment:**
 - CockroachDB version https://www.twitch.tv/twitchrunscockroachdb

**Additional context**
What was the impact?

No insight into table splitting of TwitchRunsCockroachDB.

This is the kind of problem I imagine you want to get in an alpha of a statement.

**Comment by rohany** [comment]
Hi @riking, thanks for the feedback! We have plans to improve the usability of `SHOW RANGE FOR ROW` -- see (https://github.com/cockroachdb/cockroach/issues/41421, https://github.com/cockroachdb/cockroach/issues/41422). There is also an issue #48312 to track the permissions discrepancy.
