### ISSUE TITLE
kv: TestStoreRangeMergeStats' EndTransaction resolves intent twice

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5042]
Saw this debugging #5031 with @dt and exposed a bug. While it shouldn't hurt to have an intent multiple times in `EndTransaction`s intent list, it hints at something going wrong; should investigate.

**Comment by tschottdorf** [comment]
should have been fixed in #5128, but a test would be nice. Should be easy to add one using `TestIntentResolution` (and writing to the same key & key range before and on commit).

**Comment by RaduBerinde** [comment]
Are these the kind of `TestIntentResolution` testcases that we are looking for?
```
		// Test writing the same key both outside of and inside the final batch
		// (#5042).
		{
			keys:   []string{"a", "b", "s", "x", "a", "b", "s", "x", "a", "b", "s", "x"},
			ranges: nil,
			exp:    []string{"s", "x"},
		},
		{
			keys:   []string{"a", "b", "s", "x", "a", "b", "s", "x", "a", "b", "s", "x"},
			ranges: [][2]string{{"b", "x"}, {"a", "s"}, {"b", "t"}, {"a", "s"}, {"b", "x"}},
			exp:    []string{`"s"-"x\x00"`},
		},
```


```
I160320 14:26:57.572398 server/intent_test.go:141  0: a: local: false
I160320 14:26:57.573804 server/intent_test.go:141  1: b: local: true
I160320 14:26:57.574038 server/intent_test.go:141  2: s: local: true
I160320 14:26:57.574165 server/intent_test.go:141  3: x: local: false
I160320 14:26:57.575779 storage/replica_command.go:1306  range 6: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405138h26m58.57536279s
I160320 14:26:57.576846 server/intent_test.go:141  4: a: local: false
I160320 14:26:57.578055 server/intent_test.go:141  5: b: local: true
I160320 14:26:57.578168 server/intent_test.go:141  6: s: local: false
I160320 14:26:57.578981 server/intent_test.go:141  7: x: local: false
I160320 14:26:57.579825 server/intent_test.go:141  8: a: local: true
I160320 14:26:57.580163 server/intent_test.go:141  9: b: local: true
I160320 14:26:57.580251 server/intent_test.go:141  10: s: local: false
I160320 14:26:57.580889 server/intent_test.go:141  11: x: local: false
I160320 14:26:57.585060 server/intent_test.go:115  got s
I160320 14:26:57.585578 server/intent_test.go:115  got x
...
I160320 14:26:57.627515 server/intent_test.go:141  0: a: local: false
I160320 14:26:57.628054 server/intent_test.go:141  1: b: local: true
I160320 14:26:57.628129 server/intent_test.go:141  2: s: local: true
I160320 14:26:57.628137 server/intent_test.go:141  3: x: local: false
I160320 14:26:57.628825 storage/replica_command.go:1306  range 6: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405138h26m58.648072216s
I160320 14:26:57.629137 server/intent_test.go:141  4: a: local: false
I160320 14:26:57.629324 server/intent_test.go:141  5: b: local: true
I160320 14:26:57.629374 server/intent_test.go:141  6: s: local: true
I160320 14:26:57.629382 server/intent_test.go:141  7: x: local: true
I160320 14:26:57.629388 server/intent_test.go:141  8: a: local: true
I160320 14:26:57.629394 server/intent_test.go:141  9: b: local: true
I160320 14:26:57.629400 server/intent_test.go:141  10: s: local: false
I160320 14:26:57.629679 server/intent_test.go:141  11: x: local: false
I160320 14:26:57.629971 server/intent_test.go:151  5: [b,x): local: false
I160320 14:26:57.630466 server/intent_test.go:151  5: [a,s): local: true
I160320 14:26:57.630479 server/intent_test.go:151  5: [b,t): local: true
I160320 14:26:57.630486 server/intent_test.go:151  5: [a,s): local: false
I160320 14:26:57.630727 server/intent_test.go:151  5: [b,x): local: true
I160320 14:26:57.632291 server/intent_test.go:115  got "s"-"x\x00"
--- PASS: TestIntentResolution (0.59s)
```

**Comment by tschottdorf** [comment]
yep. That test currently swallows double-resolution silently (since it can happen naturally during Raft replays) but if we use the replay protection that @andreimatei added the other day, the test can simply aggregate all resolves (ok, theoretically someone else could run into the intents and also try to resolve them, but if that happens we can deal with that as well).

**Comment by tschottdorf** [comment]
but on second thought, it'll be much more focused to just have a unit test in `kv/dist_sender_test.go`.

**Comment by RaduBerinde** [comment]
Ok, any pointers how I can go about doing that - specifically how to verify that the duplicate intents get resolved correctly? (would I still use TestingCommandFilter to look at `ResolveIntentRequest`s?)

**Comment by tschottdorf** [comment]
There shouldn't be any duplicate intents any more (that was only an issue when TxnCoordSender would simply append stuff to the `EndTransactionRequest.IntentSpans`; it's not doing that any more).

I think starting a txn, writing one key range and one key (and one extra key) and then committing in a batch with the same key range and the same key (and a distinct extra key) should be enough. You don't actually run a server, you only check that the EndTransactionRequest has the right `IntentSpans` set (the key range and key, as well as both extra keys) - that's what wasn't the case previously.

**Comment by RaduBerinde** [comment]
Isn't the txn coordinator the one that attaches the intent spans to EndTransaction? Wouldn't it have to be a `txn_coord_sender_test` and not a `dist_sender_test`?

**Comment by tschottdorf** [comment]
Sorry, yes, that's the one.
