### ISSUE TITLE
storage: sstable checksum failure

### ISSUE THREAD

**Issue by nagylzs** [cockroachdb/cockroach#50445]
**Log messages**
```

Jun 20 14:34:38 www systemd[1]: Starting Cockroach Database cluster node...
Jun 20 14:34:54 www roach[2921]: F200620 12:34:54.476402 122 server/node_engine_health.go:79  [n?] Corruption: block checksum mismatch: expected 2970216129, got 2024209899  in /var/lib/cockroach/cockroach-data/043516.sst offset 460153 size 3132
Jun 20 14:34:54 www roach[2921]: goroutine 122 [running]:
Jun 20 14:34:54 www roach[2921]: github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x7507000, 0xed67ff96e, 0x0, 0x774619)
Jun 20 14:34:54 www roach[2921]: #011/go/src/github.com/cockroachdb/cockroach/pkg/util/log/get_stacks.go:25 +0xb8
Jun 20 14:34:54 www roach[2921]: github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0x7503c60, 0xc000000004, 0x6a46199, 0x1c, 0x4f, 0xc000afc140, 0x96)
Jun 20 14:34:54 www roach[2921]: #011/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:210 +0xa29
Jun 20 14:34:54 www roach[2921]: github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x4bb8480, 0xc000c66030, 0xc000000004, 0x2, 0x0, 0x0, 0xc000d02dd0, 0x1, 0x1)
Jun 20 14:34:54 www roach[2921]: #011/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:66 +0x2c9
Jun 20 14:34:54 www roach[2921]: github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x4bb8480, 0xc000c66030, 0x1, 0xc000000004, 0x0, 0x0, 0xc000d02dd0, 0x1, 0x1)
Jun 20 14:34:54 www roach[2921]: #011/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:44 +0x8c
Jun 20 14:34:54 www roach[2921]: github.com/cockroachdb/cockroach/pkg/util/log.Fatal(...)
Jun 20 14:34:54 www roach[2921]: #011/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:164
Jun 20 14:34:54 www roach[2921]: github.com/cockroachdb/cockroach/pkg/server.(*Node).assertEngineHealth.func1(0x2540be400, 0xc000dbc000, 0xc0000a7b90, 0x4bb8480, 0xc000c66030)
Jun 20 14:34:54 www roach[2921]: #011/go/src/github.com/cockroachdb/cockroach/pkg/server/node_engine_health.go:79 +0x19c
Jun 20 14:34:54 www roach[2921]: github.com/cockroachdb/cockroach/pkg/server.(*Node).assertEngineHealth(0xc000dbc000, 0x4bb8480, 0xc000c66030, 0xc0002986f0, 0x1, 0x1, 0x2540be400)
Jun 20 14:34:54 www roach[2921]: #011/go/src/github.com/cockroachdb/cockroach/pkg/server/node_engine_health.go:81 +0xb8
Jun 20 14:34:54 www roach[2921]: github.com/cockroachdb/cockroach/pkg/server.(*Node).startAssertEngineHealth.func1(0x4bb8480, 0xc000c66030)
Jun 20 14:34:54 www roach[2921]: #011/go/src/github.com/cockroachdb/cockroach/pkg/server/node_engine_health.go:47 +0xf6
Jun 20 14:34:54 www roach[2921]: github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc0002987f0, 0xc000018750, 0xc000b47bf0)
Jun 20 14:34:54 www roach[2921]: #011/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:198 +0x13e
Jun 20 14:34:54 www roach[2921]: created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
Jun 20 14:34:54 www roach[2921]: #011/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:191 +0xa8
Jun 20 14:34:54 www roach[2921]: ****************************************************************************
Jun 20 14:34:54 www roach[2921]: This node experienced a fatal error (printed above), and as a result the
Jun 20 14:34:54 www roach[2921]: process is terminating.
Jun 20 14:34:54 www roach[2921]: Fatal errors can occur due to faulty hardware (disks, memory, clocks) or a
Jun 20 14:34:54 www roach[2921]: problem in CockroachDB. With your help, the support team at Cockroach Labs
Jun 20 14:34:54 www roach[2921]: will try to determine the root cause, recommend next steps, and we can
Jun 20 14:34:54 www roach[2921]: improve CockroachDB based on your report.
Jun 20 14:34:54 www roach[2921]: Please submit a crash report by following the instructions here:
Jun 20 14:34:54 www roach[2921]:     https://github.com/cockroachdb/cockroach/issues/new/choose
Jun 20 14:34:54 www roach[2921]: If you would rather not post publicly, please contact us directly at:
Jun 20 14:34:54 www roach[2921]:     support@cockroachlabs.com
Jun 20 14:34:54 www roach[2921]: The Cockroach Labs team appreciates your feedback.
Jun 20 14:34:54 www systemd[1]: cockroachdb.service: Main process exited, code=exited, status=255/EXCEPTION
Jun 20 14:34:54 www systemd[1]: cockroachdb.service: Failed with result 'exit-code'.
Jun 20 14:34:54 www systemd[1]: Failed to start Cockroach Database cluster node.
Jun 20 14:35:04 www systemd[1]: cockroachdb.service: Scheduled restart job, restart counter is at 22.


```

**To Reproduce**

I'm not sure, but this is not the first time. I was operating a cocroachdb v20.1.0 cluster on 5 machines. Server OS: Ubuntu LTS 18.04 and LTS 20.04.

Client app: none, this cluster was just running empty for weeks. The db server did not start after an OS upgrade (e.g. kernel update and reboot).

Jira issue: CRDB-4120

**Comment by nagylzs** [comment]
Only one node crashed out of five. When it happened the last time, it happened on a different node. Seems to be random.

**Comment by petermattis** [comment]
@itsbilal Can you take a look at this? Looks like sstable checksum corruption. That could be a bug, or it could be a hardware problem.

**Comment by nagylzs** [comment]
I can send you the whole log directory, if needed. In fact, I can give you access to the cluster if you want to. It is almost empty and not used for anything. All nodes are VMs running on server grade hardware with ECC memory and redundant disks (probably ceph).

**Comment by petermattis** [comment]
@nagylzs Can you create a tar ball of the store directory on the affected node? We currently don't have a surgical tool for recovering from sstable corruption. You'll have to wipe the node in order to bring it back into service. Can you check through the system logs (dmesg, /var/log/messages) to see if there are any indications of hardware problems?

**Comment by nagylzs** [comment]
I have sent you that in an e-mail.

**Comment by itsbilal** [comment]
I took a look into this. While the start of the block and its trailer looks okay, and the CRC bits are most probably accurate, I wasn't able to trace it down to a particular byte of corruption in the block itself, as snappy decompression gets in the way and it's a bit of a black box. If I bypass the CRC check, snappy just says it's a corrupted block. The timing of the corruption (most probably around 00:25 on 2020-06-20) also doesn't line up with any interesting dmesg or cockroach log messages.

@petermattis any other pointers you could think of, or any other way to demystify what's going wrong on the snappy end?

**Comment by petermattis** [comment]
> @petermattis any other pointers you could think of, or any other way to demystify what's going wrong on the snappy end?

I had forgotten about snappy compression. Yeah, that will foul up trying to make more progress, though I suppose you could try instrument snappy to see at which byte it complains. Snappy is trying to decode the block and probably encountering some value (an offset or length or something) which is violating an invariant. If you can identify a specific byte as the problem, you could write a program to try all 256 possible values for that byte to see if one causes the computed checksum to match the expected checksum.

**Comment by itsbilal** [comment]
@petermattis The decoded length seems to be within bounds. It's something else fouling it up, and the snappy implementation we use [is in assembly](https://github.com/golang/snappy/blob/master/decode_amd64.s). Might take the entire block and try decompressing it in a snappy implementation in a different language and see what's happening.

@nagylzs You said that this happened on another node as well, right? Did that have the same kind of error message?

**Comment by petermattis** [comment]
@itsbilal There is a pure Go implementation of snappy decode: https://github.com/golang/snappy/blob/master/decode_other.go#L14. You just have to adjust the build tags so that it is the one that is used.

**Comment by nagylzs** [comment]
@itsbilal It happened at two other nodes before, but I'm not sure if the error message was the same or not. It happened some weeks ago and I have already deleted and reinstalled those nodes.

But I can try to reproduce this problem exactly the same way as I did before.

**Comment by nagylzs** [comment]
I have upgraded all nodes to v20.1.2. Then I started rolling OS update on all of them. All of the nodes are running Ubuntu 20.04 LTS. Each of them was upgraded with:

    apt update && apt upgrade -y && apt autoremove -y && reboot

This was executed sequentially on the nodes. This time it succeeded without errors, but there was no kernel update. I'm going to try this again later (a few times). Maybe the error will occur again.

**Comment by itsbilal** [comment]
I tried all combinations of bytes in a 5 byte stretch at the start of the snappy block, which is where the decoding-time corruption error is being triggered. It isn't enough to make the snappy decoding succeed; it just fails again somewhere further down the block for all of them. There's more than just one corrupted byte, or more than one corrupted uint32 at the start (which is what I tried next).

**Comment by itsbilal** [comment]
I tried all combinations of bytes in a 5 byte stretch at the start of the snappy block, which is where the decoding-time corruption error is being triggered. It isn't enough to make the snappy decoding succeed; it just fails again somewhere further down the block for all of them. There's more than just one corrupted byte, or more than one corrupted uint32 at the start (which is what I tried next).

More examples of this happening could probably give more pointers. But something's really off with that one block it seems.

**Comment by nagylzs** [comment]
It happened again. I was on a holiday so I can only post this now.
```

# systemctl status cockroachdb.service                                                                   1 ↵
● cockroachdb.service - Cockroach Database cluster node
     Loaded: loaded (/etc/systemd/system/cockroachdb.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Fri 2020-07-24 09:01:59 CEST; 7s ago
    Process: 4377 ExecStart=/usr/local/bin/cockroach start --certs-dir=certs --advertise-addr=95.111.237.11 --join=1.1.1.1,2.2.2.2,3.3.3.3,4.4.4.4 --cache=.25 --max-sql-memory=.25 ->
   Main PID: 4377 (code=exited, status=255/EXCEPTION)

```
This is from the startup log:
```

júl 24 09:05:14 www roach[4941]: F200724 07:05:14.312536 1 cli/start.go:496  From /var/lib/cockroach/cockroach-data/auxiliary/_CRITICAL_ALERT.txt:
júl 24 09:05:14 www roach[4941]: ATTENTION:
júl 24 09:05:14 www roach[4941]: this node is terminating because a replica inconsistency was detected between [n6,s6,r116/6:/System/tsd/cr.node.sql.…]
júl 24 09:05:14 www roach[4941]: and its other replicas. Please check your cluster-wide log files for more
júl 24 09:05:14 www roach[4941]: information and contact the CockroachDB support team. It is not necessarily safe
júl 24 09:05:14 www roach[4941]: to replace this node; cluster data may still be at risk of corruption.
```

Should I compress and send you the data directory again?

**Comment by petermattis** [comment]
> Should I compress and send you the data directory again?

Yes please. @itsbilal is out of the office this week and my week is slammed, so it might be a few days before we can analyze it.

**Comment by mwang1026** [comment]
Since we weren't able to root cause and it's gone stale (i.e. we probably don't have logs or data anymore :) )closing for now. Please re-open if you want to keep investigating here.
