### ISSUE TITLE
Be able to drop all tables

### ISSUE THREAD

**Issue by hazcod** [cockroachdb/cockroach#50462]
**Is your feature request related to a problem? Please describe.**
During integration testing, each test should start with a clean database.
It is not always possible to only use transactions. (e.g. `pg.Tx`)

**Describe the solution you'd like**
Since `DROP SCHEMA` does not work, a solution for emptying the database.

**Describe alternatives you've considered**
`DROP SCHEMA`.

**Comment by jordanlewis** [comment]
@hazcod, can you use `DROP DATABASE`?

**Comment by solongordon** [comment]
I'm closing this but please reopen if `DROP DATABASE` is insufficient.
