### ISSUE TITLE
sql: program panic due to failure in parsing

### ISSUE THREAD

**Issue by yongyanglai** [cockroachdb/cockroach#50463]
https://github.com/cockroachdb/cockroach/blob/f0cfa7866f1d9cab837aa83f140fbe9e2d1569dd/pkg/sql/sem/tree/parse_string.go#L53-L55
If `ParseAndRequireString` fails to parse string as Oid type, it should return an error. Current implementation cause panic.

**Comment by jordanlewis** [comment]
Are you encountering a runtime issue, or are you speculating? The code you linked does return an error and does not panic. I'm closing this but I'll monitor if you respond again - thank you!

**Comment by yongyanglai** [comment]
Sorry for unclear statement. I encounter the nil pointer dereference panic at this place. I think it is caused by direct dereference of `i` here. Maybe it should check error returned by ParseDInt(s) first?

**Comment by jordanlewis** [comment]
@yongyanglai oh I see what you mean, you are right. I see you've contributed before - would you make a PR?

**Comment by yongyanglai** [comment]
Ok, I can help fix it
