### ISSUE TITLE
build: at least teamcity-test.sh fails to collect artifacts

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#50507]
(I believe this issue exists ever since the scripts were converted/improved to use JSON. I had noticed this already months ago. Wasn't sure before today)

Symptom: my Go unit tests fails after they create temporary artifacts in their $TMPDIR, however the "Artifacts" tabs in TeamCity remains empty.

Example here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_Test/2029726?buildTab=overview

(In contrast, roachtest failures do get their artifacts populated)

Compare:

- run `make test ... TESTFLAGS=-v` locally, see that the test creates temporary files/directories in $TMPDIR

- same failing test in CI: no artifacts collected

I am surprised because I seem to read in the scripts that TMPDIR is set to a sub-directory of `artifacts` which is mounted in the docker image? 

(But then maybe that directory just exists but does not get copied to the place TeamCity looks for artifacts?)

**Comment by knz** [comment]
cc @tbg for triage

**Comment by tbg** [comment]
Is there some expectation that `TMPDIR` gets put into artifacts? I didn't think so and I haven't seen this spelled out anywhere. As far as I can tell, artifacts always go to `./artifacts`. In fact, in `teamcity-*.sh` we usually `export TMPDIR=$PWD/artifacts/x`.

But, that being the case, I shouldn't be seeing this in your test run:

```
--- FAIL: TestUnavailableZip (9.30s)
test_log_scope.go:77: test logs captured to: /tmp/logTestUnavailableZip871213965
```

Clearly `TMPDIR` isn't overridden here. Actually there's even a second level of override in `builder.sh`:

https://github.com/cockroachdb/cockroach/blob/8b0e347176defe948b67b47c8d7d52e95aa732a3/build/builder.sh#L61

So doubly you should not land in `/tmp` here.

> (In contrast, roachtest failures do get their artifacts populated)

They don't use `TMPDIR` but the `--artifacts` variable which defaults to `./artifacts`.

**Comment by knz** [comment]
> Is there some expectation that TMPDIR gets put into artifacts? 

It was my expectation, yes.

1)  When tests generate temporary data (e.g. bulk i/o, reference files etc) and the test fails, we definitely want that data into the artifacts.

2) Separately, I want TestLogScope log files to go to artifacts too. Today TestLogScope uses TMPDIR, but if we're not happy about that we can make it go somewhere else. In the end though I want htem in artifacts.

> Clearly TMPDIR isn't overridden here. Actually there's even a second level of override in builder.sh:
> So doubly you should not land in /tmp here.

Yes I have read the scripts and observe the same. So for clarity:

1. if I override TMPDIR in my test locally then it gets taken into account
2. however, when ran via these scripts in TeamCity the override does not work.

Why does it not work?

**Comment by tbg** [comment]
> Why does it not work?

That's where I ended up. Nobody knows, more elbow grease needed.

**Comment by tbg** [comment]
Narrowed it down to `autouseradd` which we use as the entry point to the docker image. If I omit that, the TMPDIR gets passed through. Filed an issue [upstream](https://github.com/benesch/autouseradd/issues/2), maybe @benesch knows just why that is. In the meantime we should be able to put in a hotfix.
