### ISSUE TITLE
Cockroach DB - Unable to start a single node in windows 10.

### ISSUE THREAD

**Issue by kinkums** [cockroachdb/cockroach#50549]
A summary of the issue.
I am unable to start a single node of cockroachDB in my windows system.

The steps to reproduce the issue.
PS C:\tz> cockroach start-single-node
*
* ERROR: ERROR: failed to initialize node: unable to load named timezones
* HINT: See: https://github.com/cockroachdb/cockroach/issues/36864
* --
* Check that the time zone database is installed on your system, or
* set the ZONEINFO environment variable to a Go time zone .zip archive.
*
ERROR: failed to initialize node: unable to load named timezones
HINT: See: https://github.com/cockroachdb/cockroach/issues/36864
--
Check that the time zone database is installed on your system, or
set the ZONEINFO environment variable to a Go time zone .zip archive.
Failed running "start-single-node"

The result you expected.
Node to be started

The result that actually occurred
Failed running "start-single-node"

The current time zone being shows is correct.
Found zoneinfo env: true, location:'C:\zoneinfo.zip' .
-------------------------
2020-06-23T20:25:53.6545+05:30

**Comment by knz** [comment]
The environment variable is `ZONEINFO` in capitals, not `zoneinfo` in small letters.

**Comment by kinkums** [comment]
Hi,

Environment variable is already mentioned in Capitals... See the below
screen shot for reference.

[image: image.png]

Regards
Kiran.

**Comment by knz** [comment]
Please attach the image on github?

**Comment by kinkums** [comment]
https://user-images.githubusercontent.com/32684400/85423034-d9602c00-b593-11ea-8ffd-d175aae354d3.PNG

**Comment by knz** [comment]
Thanks. Can you remind us which version of crdb you're attempting to run?

**Comment by kinkums** [comment]
The relevant details are below -
Build Tag:    v20.1.2
Build Time:   2020/06/09 16:21:19
Distribution: CCL
Platform:     windows amd64 (x86_64-w64-mingw32)
Go Version:   go1.13.9
C Compiler:   gcc 6.3.0
Build SHA-1:  92670dd72acad03bd9de54a197d66ef423a90183
Build Type:   release

**Comment by knz** [comment]
Thank you. This situation is surprising, it is not expected. We've tested the workaround before and it should work.

The remaining possibility is that the zip file is either unreadable or has the wrong format. Did you check the permissions on the file, and also that the .zip files comes from the same version of Go?

**Comment by kinkums** [comment]
It Worked, Thank You.... There was a difference in go version... CockroachDB was using go1.13.9 and the GO in my system was go1.9... I have updated the GO in my system and all is Well...

Many Thanks Again
