### ISSUE TITLE
bulk-io: add options to EXPORT to that appends the jobid to the filename

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#50580]
Currently, if you run EXPORT, it will overwrite the files there for multiple runs.  
This can become problematic if you want to run an export job multiple times and perhaps a node is missing.  Then that node's file won't be overwritten, which can be even more dangerous.

So two independent suggestions to fix this:
1) 
  a) add an overwrite option that has to be enabled to ensure you don't overwrite any exiting files or
  b) add a clear option that deletes all previous files in the bucket (not a big fan of this, it can have dangerous side effects)

2) add the jobid or a timestamp (or both) in the output filename so it will never overwrite existing files.  It might even make sense to prepend the filenames with the jobid.  Or consider always outputting to a sub bucket with the jobid or timestamp.

**Comment by BramGruneir** [comment]
assigned to @dt for triage

**Comment by shermanCRL** [comment]
The commit and PR summarize this change, feedback welcome.

Another possibility is for the export ID to be a new directory instead of file name.

Pro: a single export is naturally grouped in a directory, easier to browse and manage, inconsistent files are never siblings. Since the QueryID is derived from a timestamp, it _should_ sort lexically (yes?).

Con: we’ve create a new directory, so a subsequent import would require the importer to figure out what it is. Maybe the export statement could return the directory name/URI? Or, the importer could select the most recent export directory, inferred from the ID?

**Comment by shermanCRL** [comment]
@mwang1026 Any thoughts on the user experience here? These file names are gonna get long.

What’s your opinion on creating a unique directory per export run? Pros and cons are above.

**Comment by dt** [comment]
counter-point: if the user wanted the output in a subdirectory of the destination, why didn't they just supply that as the destination instead?

**Comment by shermanCRL** [comment]
Fair. Well, do users understand/expect that their export will be multiple files? And, are they likely to anticipate the issue of sibling files representing inconsistent data?

We have two possible surprising outcomes:

- “That’s not the directory I specified” vs
- “My folder of export data might be inconsistent”

We’ll have to decide which is more surprising.

Oh, and for my own edification: Do users generally recognize that they should be supplying a destination _directory_, not file name?

**Comment by mwang1026** [comment]
If users don't understand that it's a directory that's our bad -- we should make that clear.

Users often script these exports to be ingested down the line somewhere. If we write subdirectories my sense is that it'd be more work for the script to find the folder and then all the files vs. just finding files with date > X -- although not impossible -- or they just have some way to autodetect new files and ingest. My sense is filename is fine (and what the original user who requested it suggested).

**Comment by shermanCRL** [comment]
Great, we’ll leave it as is (file name prepend). Agree that creating a new directory would be a breaking change for current setups.

**Comment by shermanCRL** [comment]
@BramGruneir This has been merged to master, you can try it out if you like.

**Comment by mwang1026** [comment]
Looks like PR was merged. Closing.
