### ISSUE TITLE
sql: dropping column with FK relies on FK origin indexes

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#50592]
I was taking a first step toward removing the requirement for origin FK indexes, namely to allow dropping these indexes without error. I tried the simple diff below. With this change, a seemingly unrelated thing fails: dropping a column that has a foreign key. See exeample: https://gist.github.com/RaduBerinde/8eef2aa04627ee18a2ca3a12d9d4d870

My guess is that we are not directly dropping any foreign keys involving the column, instead it happens indirectly through deleting all indexes. Unfortunately I'm not familiar with this code at all, I wouldn't know where to begin to fix this.

```diff
diff --git a/pkg/sql/drop_index.go b/pkg/sql/drop_index.go
index 25bd598b13..30a809e49a 100644
--- a/pkg/sql/drop_index.go
+++ b/pkg/sql/drop_index.go
@@ -356,29 +356,7 @@ func (p *planner) dropIndexByName(
 		return err
 	}
 
-	// Index for updating the FK slices in place when removing FKs.
 	sliceIdx := 0
-	for i := range tableDesc.OutboundFKs {
-		tableDesc.OutboundFKs[sliceIdx] = tableDesc.OutboundFKs[i]
-		sliceIdx++
-		fk := &tableDesc.OutboundFKs[i]
-		canReplace := func(idx *sqlbase.IndexDescriptor) bool {
-			return idx.IsValidOriginIndex(fk.OriginColumnIDs)
-		}
-		// The index being deleted could be used as the origin index for this foreign key.
-		if idx.IsValidOriginIndex(fk.OriginColumnIDs) && !indexHasReplacementCandidate(canReplace) {
-			if behavior != tree.DropCascade && constraintBehavior != ignoreIdxConstraint {
-				return errors.Errorf("index %q is in use as a foreign key constraint", idx.Name)
-			}
-			sliceIdx--
-			if err := p.removeFKBackReference(ctx, tableDesc, fk); err != nil {
-				return err
-			}
-		}
-	}
-	tableDesc.OutboundFKs = tableDesc.OutboundFKs[:sliceIdx]
-
-	sliceIdx = 0
 	for i := range tableDesc.InboundFKs {
 		tableDesc.InboundFKs[sliceIdx] = tableDesc.InboundFKs[i]
 		sliceIdx++
diff --git a/pkg/sql/logictest/testdata/logic_test/drop_index b/pkg/sql/logictest/testdata/logic_test/drop_index
```

**Comment by lucy-zhang** [comment]
> My guess is that we are not directly dropping any foreign keys involving the column, instead it happens indirectly through deleting all indexes.

Yeah, I think this is it. In fact, we left ourselves a comment: https://github.com/cockroachdb/cockroach/blob/0715b9c/pkg/sql/alter_table.go#L459-L462
