### ISSUE TITLE
storage: allow specifying arbitrary Pebble options

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#50600]
We can pass arbitrary options through to RocksDB using the `--store=path=<path>,rocksdb=key1=val1;key2=val2` syntax. We should generalize this option setting to allow specifying arbitrary Pebble options. The RocksDB syntax is frequently confusing as it doesn't map cleanly to the OPTIONS format. For Pebble, I propose we use the OPTIONS format exactly with the extension that we translate `;` to `\n`. For example, in order to change `L0CompactionThreshold` and `L0StopWritesThreshold` you would specify:

```
--store=path=<path>,pebble=[Options];l0_compaction_threshold=2;l0_stop_writes_threshold=10
```

Parsing this would involve a `strings.Replace(..., ";", "\n")` before calling `pebble.Options.Parse`. 

Alternately, we could use the syntax `<section>.<key>=<value>` syntax. This would involve a slight repetition on the command line, but is possibly more natural:

```
--store=path=<path>,pebble=Options.l0_compaction_threshold=2;Options.l0_stop_writes_threshold=10
```

**Comment by jbowens** [comment]
@itsbilal Am I recalling correctly that you brought up some reason we avoided using a `;` delimiter for RocksDB?

Would it be too crazy to use the OPTIONS file notation verbatim, and just let usages use Heredoc notation? Or maybe a relaxed version that allows spaces in place of newlines? It would probably require a little less trivial parsing than a `strings.Replace` to handle level headers (`[Level "0"]`).

**Comment by petermattis** [comment]
> @itsbilal Am I recalling correctly that you brought up some reason we avoided using a ; delimiter for RocksDB?

I believe we're constrained by how the store specific options fit within the `--store` flag. I don't recall offhand what restrictions that implies.

> Would it be too crazy to use the OPTIONS file notation verbatim, and just let usages use Heredoc notation?

Can you elaborate on what this would look like? Are you referring to shell-script heredoc's?

> Or maybe a relaxed version that allows spaces in place of newlines?

Can a value contain whitespace? Right now we allow it, though I'm not sure any value does contain whitespace.

**Comment by jbowens** [comment]
> I believe we're constrained by how the store specific options fit within the `--store` flag. I don't recall offhand what restrictions that implies.

I just read `NewStoreSpec` and it looks like there's just a top-level split on `,`. I can't remember what Bilal's comment was now, but maybe it was suggesting `:` as a delimiter because that's what store [`attrs`](https://github.com/cockroachdb/cockroach/blob/2c6d0d2317767809a3f5139e8dca9709b486779a/pkg/base/store_spec.go#L303) uses.

> Can you elaborate on what this would look like? Are you referring to shell-script heredoc's?

Yeah. I was thinking usages like:
```
PEBBLE_OPTIONS=$(cat <<EOF
[Options]
  l0_compaction_threshold=2
  l0_stop_writes_threshold=10
EOF
)
cockroach ... --store="path=<path>,pebble=$PEBBLE_OPTIONS"
```
It would allow for setting options from a whole, fully-specified `OPTIONS` file

```
cockroach ... --store="path=<path>,pebble=$(cat <options-path>)"
```

> Can a value contain whitespace? Right now we allow it, though I'm not sure any value does contain whitespace.

AFAICT, none of _our_ values contain whitespace. If we were to blanket disallow value whitespace in Pebble, it would break non-Cockroach Pebble users who included whitespace in merger, comparer, filter or table property collector names.

With or without newlines, it's worth noting that within a shell the `[` in `[Options]` will require escaping or quoting, which might confuse some users.

**Comment by petermattis** [comment]
> AFAICT, none of our values contain whitespace. If we were to blanket disallow value whitespace in Pebble, it would break non-Cockroach Pebble users who included whitespace in merger, comparer, filter or table property collector names.

Good point, though the merger and comparer are options that are essentially never changed except programmatically. So perhaps we could allow whitespace as a delimiter only when parsing from the command line.

> With or without newlines, it's worth noting that within a shell the [ in [Options] will require escaping or quoting, which might confuse some users.

Can you elaborate? `echo "[Options]"` works just fine. I think I'm misunderstanding your point here.

**Comment by jbowens** [comment]
> Can you elaborate? `echo "[Options]"` works just fine. I think I'm misunderstanding your point here.

Ah, I just meant that it does require those quotes ^. On second thought, that's the case with the `;` and whitespace delimiters as well. If we used `:` as a delimiter like in the attrs option, there would be no need to escape or surround the argument in quotes, eg:

```
--store=path=/mnt/data1/cockroach,pebble=Options.l0_compaction_threshold=2:Options.l0_stop_writes_threshold=10
```
vs
```
--store="path=/mnt/data1/cockroach,pebble=Options.l0_compaction_threshold=2;Options.l0_stop_writes_threshold=10"
```

It's not a big deal at all, but it would be minor convenience if the encoding avoided any [characters that may require escaping](https://unix.stackexchange.com/questions/270977/what-characters-are-required-to-be-escaped-in-command-line-arguments).

**Comment by petermattis** [comment]
> Ah, I just meant that it does require those quotes ^. On second thought, that's the case with the ; and whitespace delimiters as well. If we used : as a delimiter like in the attrs option, there would be no need to escape or surround the argument in quotes, eg

Ah, got it. I don't think it is particularly onerous or unexpected to require enclosing the `--store` flag value in quotes.

**Comment by itsbilal** [comment]
> @itsbilal Am I recalling correctly that you brought up some reason we avoided using a `;` delimiter for RocksDB?

Peter basically covered the same point; we had to avoid using `,` not `;` in cmd arg RocksDB options as they need to be embeddable within store options, which are delimeted with `,`.
