### ISSUE TITLE
storage: super-bug: initial splits getting stuck (making everything else flaky as well)

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#5060]
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/e9f364bea3014b627b66e8dddcc79a4f3cbcfaad

Stress build found a failed test:

```
=== RUN   TestNodeStatus
E160310 03:34:06.585171 client/txn.go:346  failure aborting transaction: kv/txn_coord_sender.go:383: transaction is already committed or aborted; abort caused by: node unavailable; try another peer
E160310 03:34:06.585465 storage/queue.go:441  [split] range=1 [/Min-/Table/11): error: storage/split_queue.go:100: unable to split range=1 [/Min-/Table/11) at key "/Table/13/0": storage/replica_command.go:1379: split at key /Table/13 failed: node unavailable; try another peer
F160310 03:34:06.585689 cli/cli_test.go:64  Could not start server: server/testserver.go:273: had 3 ranges at startup, expected 5
goroutine 127 [running]:
github.com/cockroachdb/cockroach/util/log.getStacks(0xece72e200, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:868 +0xb8
github.com/cockroachdb/cockroach/util/log.(*loggingT).outputLogEntry(0x26473a0, 0x3, 0x1fd4f64, 0xf, 0x40, 0xc820a5f020, 0x55)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:732 +0x178
github.com/cockroachdb/cockroach/util/log.addStructured(0x0, 0x0, 0x3, 0x2, 0x191cf20, 0x1a, 0xc820a69c98, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/structured.go:57 +0xfc
github.com/cockroachdb/cockroach/util/log.logDepth(0x0, 0x0, 0x1, 0x3, 0x191cf20, 0x1a, 0xc820a69c98, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/log.go:73 +0x7b
github.com/cockroachdb/cockroach/util/log.Fatalf(0x191cf20, 0x1a, 0xc820a69c98, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/log.go:179 +0x66
github.com/cockroachdb/cockroach/cli.newCLITest(0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/cli/cli_test.go:64 +0x313
github.com/cockroachdb/cockroach/cli.TestNodeStatus(0xc82073a000)
	/go/src/github.com/cockroachdb/cockroach/cli/cli_test.go:754 +0xd4
testing.tRunner(0xc82073a000, 0x22e9d70)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892


ERROR: exit status 255
```

Run Details:

```
6 runs so far, 0 failures, over 5s
14 runs so far, 0 failures, over 10s
21 runs so far, 0 failures, over 15s
29 runs so far, 0 failures, over 20s
38 runs so far, 0 failures, over 25s
45 runs so far, 0 failures, over 30s
47 runs completed, 1 failures, over 30s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment]
dupe #5043

**Comment by tamird** [comment]
opening this one over #5043 because it includes the stress output

**Comment by tschottdorf** [comment]
@nvanbenschoten pushing this your way to free up my queue - let me know if that's an issue.

We should investigate what went wrong with the pre-#5118 code. Should be easy enough: revert #5118, change all the errors in `kv.truncate` to panics (in particular `return false, emptySpan, util.Errorf("local key range must not span ranges")`), run `TestNodeStatus` and let happiness ensue. Then log the original key range before truncation and figure out what's going on. It's definitely a range-local one-element key range that did it.

**Comment by tschottdorf** [comment]
After that, something we ought to be looking at is why this intent was never resolved - other readers which encounter it should get it out of the way. That is, intentionally let that resolution fail (or maybe even easier, all resolutions during the initial splits) and see what prevents us from making progress.
By "letting resolutions fail" I mean not attaching the collected intent spans to `EndTransaction` in `DistSender`.

This is somewhat orthogonal to the above fix, but also important - we need to be pretty solid on getting intents out of the way even if the optimistic resolution fails.

**Comment by nvanbenschoten** [comment]
The original issue here seems to have stabilized. I just ran 20,000 iterations of the `TestNodeStatus` without issue. Closing for now.

**Comment by tschottdorf** [comment]
Just curious, also with end transaction not resolving intents?

On Wed, Apr 6, 2016, 19:59 Nathan VanBenschoten <notifications@github.com>
wrote:

> The original issue here seems to have stabilized. I just ran 20,000
> iterations of the TestNodeStatus without issue. Closing for now.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/5060#issuecomment-206488701>
>
-- 

-- Tobias

**Comment by nvanbenschoten** [comment]
@tschottdorf Yes and no. If all we do is omit adding collected intent spans to the `EndTransaction` in `TxnCoordSender`, then the splits are never successful. The reason for this is the [auto GC optimization](https://github.com/cockroachdb/cockroach/blob/master/storage/replica_command.go#L530) we perform when applying an `EndTransaction` command. If no intents are added to this command, then we will simply delete the transaction record immediately instead of marking it as committed. This means that when the intents are eventually found and pushed, they have no corresponding transaction record and will all be aborted.

However, if we omit adding collected intent spans to the `EndTransaction` but also make sure not to perform this auto GC optimization (instead always committing the transaction record), then the intent push touches will all correctly resolve their intents and the splits will all eventually go through as expected.

**Comment by tschottdorf** [comment]
Great, that's what I wanted to hear. Thanks for investigating :)

On Wed, Apr 6, 2016, 20:49 Nathan VanBenschoten <notifications@github.com>
wrote:

> @tschottdorf <https://github.com/tschottdorf> Yes and no. If all we do is
> omit adding collected intent spans to the EndTransaction in TxnCoordSender,
> then the splits are never successful. The reason for this is the auto GC
> optimization
> <https://github.com/cockroachdb/cockroach/blob/master/storage/replica_command.go#L530>
> we perform when applying an EndTransaction command. If no intents are
> added to this command, then we will simply delete the transaction record
> immediately instead of marking it as committed. This means that when the
> intents are eventually found and pushed, they have no corresponding
> transaction record and will all be aborted.
>
> However, if we omit adding collected intent spans to the EndTransaction
> but also make sure not to perform this auto GC optimization (instead always
> committing the transaction record), then the intent push touches will all
> correctly resolve their intents and the splits will all eventually go
> through as expected.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/5060#issuecomment-206510923>
>
-- 

-- Tobias
