### ISSUE TITLE
Makefile: `make -k vendor_rebuild` runs execgen

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#50609]
`make vendor_rebuild` runs `execgen`, which is undesirable in cases where we want to run vendor updates without having generated files necessary compile. To force this to work, one must run `make -k vendor_rebuild`.

Not sure why this is (given the dependency doesn't seem to be there).

**Comment by jordanlewis** [comment]
This is now going to be fixed also due to #50636.
