### ISSUE TITLE
build: helm chart needs to be updated to point to 20.1.x

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#50603]
The CRDB helm chart currently uses 19.2.5. See https://github.com/helm/charts/tree/master/stable/cockroachdb. This needs to be updated to use 20.1.x. And we need to figure out the process failure which caused us to miss updating this for the past month.

**Comment by dt** [comment]
There is a PR upstream here: https://github.com/helm/charts/pull/22536

However CI flakes upstream so far have prevented getting it merged, see: https://github.com/helm/charts/pull/22536#issuecomment-634716402

**Comment by jlinder** [comment]
The CRDB helm chart has been moved to its own repository at https://github.com/cockroachdb/helm-charts and has been updated to 20.1.3.
