### ISSUE TITLE
roachtest: non-obviously failing to run all nightly tests

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#50618]
I noticed that the two most recent roachtest nightly runs did not run all the tests.

[This run](https://teamcity.cockroachdb.com/viewLog.html?buildId=2034317&buildTypeId=Cockroach_Nightlies_WorkloadNightly&tab=testsInfo&branch_Cockroach_Nightlies=%3Cdefault%3E) is from June 24, and has 148 total tests.

While [this run](https://teamcity.cockroachdb.com/viewLog.html?buildId=2025369&buildTypeId=Cockroach_Nightlies_WorkloadNightly&tab=testsInfo&branch_Cockroach_Nightlies=%3Cdefault%3E) is from June 20, and has 285 total tests.

The danger with this is that the job could, for example, end up running a small subset of tests each night, and it might only choose tests that are passing. An important test might be failing and we wouldn't ever know if it's not getting run.

I think the job should complain more loudly if it sees that the number of tests is incorrect.

Jira issue: CRDB-4111

**Comment by jordanlewis** [comment]
Some observations:

If roachtest crashes, not all of the tests will be marked as "run" in the UI.

That being said, the jepsen tests were run in just one, and not the other.

**Comment by jordanlewis** [comment]
@rafiss is this still happening?

**Comment by rafiss** [comment]
As far as I know, the tests have been running.

But that's the issue I am trying to highlight here -- we could currently be in a state where not all of the tests are running and no one would really know since it's not obvious when that happens.
