### ISSUE TITLE
Unskip TestRegistryGC 

### ISSUE THREAD

**Issue by spaskob** [cockroachdb/cockroach#50619]
This test is creating jobs in various states and checking that they get GC'ed properly.  If it is possible to disable the job registry from adopting jobs and remove references to dropJobID (since that's no longer used in 20.1), the test should mostly work as is.

https://github.com/cockroachdb/cockroach/blob/master/pkg/jobs/registry_test.go#L195

**Comment by postamar** [comment]
This has been done.
