### ISSUE TITLE
telemetry: Cluster location coordinates 

### ISSUE THREAD

**Issue by katedoebler** [cockroachdb/cockroach#50645]
**Describe the problem**

The telemetry reporting for cluster location geo-coordinates does not appear to be consistently accurate. 

**To Reproduce**

We investigated the actual physical locations for a couple clusters and found that the geo coordinates for the clusters were not all accurate. 

**Expected behavior**

**Additional data / screenshots**

**Environment:**

**Additional context**
Geoclusters reporting accuracy suffers 

Jira issue: CRDB-4107

**Comment by katedoebler** [comment]
@emily-horing FYI -- do you have the details on the test you ran?

**Comment by yuzefovich** [comment]
I don't know who is the owner of this issue. cc @awoods187

**Comment by emily-horing** [comment]
Details:
Used a Cloud customer cluster as an example (CRDB ID 5b0c418a-8069-41b0-9d22-299f2dcdeab2). They have 3 nodes in 4 regions according to the [creation ticket.](https://github.com/cockroachlabs/managed-service/issues/1847) These regions include Oregon, Los Angeles, Virginia, and North Carolina.

However, the reported locations of this cluster's nodes do not match up (none are anywhere near the west coast):
```
LAT	LONG
39.04	-77.49
0	0
40.74	-73.98
40.74	-74.17
40.55	-74.46
45.52	-122.68
```
query: `select lat, long from updates where cluster = '5b0c418a-8069-41b0-9d22-299f2dcdeab2' group by lat, long;`
