### ISSUE TITLE
sql: figure out what is needed to enable inverted types in PKs

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#50659]
Inverted types might be able to be in PKs, but opt and exec teams need to sign off first. Here's some kinds of problems we need to think through before enabling them:

1. Should the optimizer generate forward and inverted histograms?
2. What happens in the executor when scanning inverted columns that are also in the PK? Does their column id appear twice? Are there other unintended things?

There may be others.

See #50656

Jira issue: CRDB-4104

**Comment by jordanlewis** [comment]
This has been finished since we added support for inverted indexes on strings for trigram indexes. Woohoo!
