### ISSUE TITLE
autocommit can't be disabled in the cockroach sql "cli"

### ISSUE THREAD

**Issue by glennfawcett** [cockroachdb/cockroach#50667]
**Is your feature request related to a problem? Please describe.**
Autocommit is always on within the CockroachDB CLI.  I tried the following and it appears to not work as expected.

```
cockroach sql --url "postgres://root@127.0.0.1:26257/defaultdb?sslmode=disable&autocommit=true"
```

**Describe the solution you'd like**
Support `\set autocommit off;`

**Describe alternatives you've considered**
I have used the `psql` cli and it works as expected.

**Additional context**
This is for connivence when testing and deploying CockroachDB.

**Comment by BramGruneir** [comment]
assigning to @jordanlewis for triage

**Comment by jordanlewis** [comment]
@glennfawcett there's no notion of autocommit in the CLI. To make a transaction, you can write `BEGIN TRANSACTION`. Is this a problem for you?
