### ISSUE TITLE
Support CREATE DATABASE...WITH OWNER syntax

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/cockroach#50676]
**Describe the problem**

A customer was trying to apply [this workaround](https://github.com/terraform-providers/terraform-provider-postgresql/issues/91#issuecomment-567952112) when using the Postgres Terraform provider. The workaround allows for successful connection but then this error happens.

```
Returns: Error: Error creating database "terradb": pq: at or near "owner": syntax error

A quick look at the source shows that the provider always wants to include OWNER in the CREATE DATABASE statement but this is not supported by CockroachDB.
```

**To Reproduce**

With Postgres,
```
postgres=# create user vy;
CREATE ROLE
postgres=# create database foo with owner=vy;
CREATE DATABASE
```

With CockroachDB,
```
root@127.0.0.1:65372/movr> create user vy;
CREATE ROLE

Time: 3.197ms

root@127.0.0.1:65372/movr> create database foo with owner=vy;
invalid syntax: statement ignored: at or near "owner": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
create database foo with owner=vy
```

**Expected behavior**
Support the `CREATE DATABASE...WITH OWNER` syntax for Postgres compatability.

**Comment by solongordon** [comment]
Looks like this is already covered by #30875. I'll add a note there about Terraform.
