### ISSUE TITLE
opt: change the key column of inverted indexes to use a new column id and type

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#50695]
Currently, the inverted key column of an inverted index uses the same column ID and type as the original table column it indexes. This is a problem if the column needs to be passed between several operators, because the execution engine expects a column with a certain type (e.g., Geometry), but receives a different type (e.g., int). It also makes several things awkward in the optimizer, and requires special handling of the inverted key column.

The solution is to create a new column for the inverted key column, with a new column ID and type corresponding to the real type stored in the inverted index. This issue tracks the work to make that change in the optimizer.

**Comment by RaduBerinde** [comment]
This was done in #52658. We still have outstanding tasks around setting the correct type for the column.
