### ISSUE TITLE
sql: implement idle_in_session_timeout variable

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#50706]
It's a common ask to have a way to kill connections that have been idle in their sessions for too long. This variable would be an extension of the existing `statement_timeout` and `idle_in_transaction_session_timeout` variables.

The semantics would be that, if an open session exceeds the duration of the variable, the server closes the session.

I think we should probably also have a `sql.defaults.idle_in_session_timeout` cluster setting, so administrators can configure this property on a cluster-wide basis as well.

cc @sheaffej @awoods187 @solongordon

**Comment by solongordon** [comment]
I'm wondering if this should be a cluster-level setting rather than session. If it's a session setting then there's nothing to stop users from increasing the timeout for their own setting. Is this desirable? @awoods187 @jordanlewis
