### ISSUE TITLE
bulkio/import: bug when mixing existing and new tables?

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#50733]
I was casually skimming over the code trying to understand #50731 and stumbled upon this block of code:

https://github.com/cockroachdb/cockroach/blob/8f768ad14cfb3f514db6d40465b2dd60ee1f2890/pkg/ccl/importccl/import_stmt.go#L1011-L1023

I couldn't make sense of it, and I now think it's a bug. Specifically, I think the indexing is wrong here, as it doesn't handle the case where `len(newTableDescs) < len(importDetails.Tables)` correctly. Looking up, we see an unused map `newTableDescToIdx`, which is exactly what we want here. So I think we're just forgetting to use this map. I think we want something like `i := newTableDescToIdx[i]` in the loop over `res`.

I don't know if this is actually possible to hit as a user, as I believe IMPORT only allows new tables and IMPORT INTO only allows existing tables.

**Comment by adityamaru** [comment]
Thanks for flagging, looking into it.
