### ISSUE TITLE
DBeaver driver for CockroachDB doesn't work with DBeaver v7.1.1

### ISSUE THREAD

**Issue by cork** [cockroachdb/cockroach#50747]
DBeaver 7.1.1 seams to not work with the CockroachDB driver. What ever column i try to update it gives me the error `Column [column name] is read-only: No corresponding table column`. Downgrading DBeaver to v7.1.0 and the same edits starts working again.

STR:
1. Open a table in the DBeaver table view
2. Double click an existing cell to edit it

**Expected behavior**
Field should be editable.

**Actual behavior**
A red X is shown in the action bar in the bottom with the text `Column [column name] is read-only: No corresponding table column`.

**Environment:**
 - CockroachDB version 20.1.1
 - Server OS: archlinux
 - Client app DBeaver 7.1.1

**Additional context**
CockroachDB is view only in DBeaver 7.1.1

**Comment by rafiss** [comment]
@cork are you still having this issue? If it works in DBeaver 7.1.0 but not in 7.1.1, then I would recommend filing an issue in the DBeaver issue tracker: https://github.com/dbeaver/dbeaver/issues

**Comment by cork** [comment]
Isn't using it anymore, but tried it now and it works fine.
