### ISSUE TITLE
adminui: node diagnostics report doesn't say anything about dead/decommissioned nodes

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#50761]
The `/reports/nodes` seems to make an RPC to the liveness endpoint, but its results don't seem to be used for anything. Decommissioned nodes show up in the report, and moreover the report doesn't indicate their funky status in any way. Filing on behalf of surprised user.

gz#5688

Jira issue: CRDB-4091

**Comment by thtruo** [comment]
Closing this issue as node diagnostic reports now include dead/decommissioned nodes. Also see related issue https://github.com/cockroachdb/cockroach/issues/77333
