### ISSUE TITLE
backup: put actual options in the grammar instead of opaque string kv_options

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#50762]
The current `kv_options` in the grammar has many drawbacks:
- The grammar doesn't enumerate the options so they don't show up in generated help, diagrams, or auto-complete.
- Options can be specified more than once with conflicting values. gross.
- Validation of well-formed input in SQL is usually during parsing, but these are currently not checked until execution. gross.
- Two ASTs with different options don't show up as different for caching or prepare-vs-execute. Gross.

This was a hack to avoid needing to edit the grammar when iterating on early backup/restore but it has long outlived that period. We should instead behave like any other SQL statement and just define our options in the grammar.

**Comment by miretskiy** [comment]
fixed
