### ISSUE TITLE
Refactor the ExternalStorage machinery to decouple all packages from cloudimpl

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#50788]
Adding the new FileTable ExternalStorage has exposed a pain point in the way our current ExternalStorage code is setup. 

> `server.go` depends on `storage/cloudimpl` because it injects the concrete factory method implementations.

All packages should only depend on `storage/cloud`. While this is true for most places after (#50644), the current design forces the server to depend on it. This leads to issues such as test files in `storage/cloudimpl` not being able to start TestServers because of a `server -> cloudimpl -> server` dependency cycle. The current design of having two factory methods plumbed throughout the code also seems "unwieldy".

Below is a rough outline of the new approach:
- Introduce an `ExternalStorageEnvironment` interface in `storage/cloud` which will encapsulate all the state needed by ExternalStorage from the server. The server will have a `prodExternalStorageEnvironment` implementation which will be plumbed to all the jobs and processors which create ES instances. Tests can implement their own flavour of these server state getters.

- Add a register mechanism to `storage/cloud` where `storage/cloudimpl` on `init()` can register factory methods for every type of ExternalStorage. The various jobs/processors can then invoke the wrapper methods in `storage/cloud` (which will, in turn, invoke the registered implementations) and will get back interface types (`cloud.ExternalStorage`/`roachpb.ExternalStorage`) thereby remaining independent of `storage/cloudimpl`.
This allows us to delete the closures from `server.go`.

**Comment by adityamaru** [comment]
@miretskiy please let me know if there are further improvements we had discussed and I have missed.

cc @dt

**Comment by miretskiy** [comment]
I think it's a very good summary of why we run into the issues.
The genesis of this discussion was https://github.com/cockroachdb/cockroach/pull/50755

There are few other issues that may indicate that some refactoring is overdue:
   * The fact that we have to touch 50+ files to make a single change
   * We have to pass in the same arguments throughout those files, even though only 1 implementation
     may care about that information (e.g. block client factory only pertains to nodelocal)
   * And, of course, the circular dependency issue you mentioned.
