### ISSUE TITLE
sql,metrics: ROLLBACK after RELEASE cockroach_restart misclassified in metrics

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#50780]
`BEGIN; SAVEPOINT cockroach_restart; ...; RELEASE SAVEPOINT cockroach_restart; ROLLBACK;` currently increments the following four metrics:
```
sql.txn.begin.count
sql.restart_savepoint.count
sql.restart_savepoint.release.count
sql.txn.rollback.count
```
This last metric is incorrect. We should be incrementing the `sql.txn.commit.count` metric instead, because the transaction has committed.

The fix for this will be to update `StatementCounters.incrementCount` with condition logic in the `tree.RollbackTransaction` case that consults the session's state.

**Comment by knz** [comment]
@solongordon can you triage this?
