### ISSUE TITLE
shp2pgsql generates slow sql query imports

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#50827]
Applying the [shp2pgsql](https://manpages.debian.org/stretch/postgis/shp2pgsql.1.en.html) tool to the nyc_census_blocks PostGIS tutorial examples generates this [SQL file]( 
https://gist.github.com/5aba009ddbba9682f553994749b18878) which we can import to CRDB.

The GIST is really slow to import - starting out in 10 microseconds per INSERT before finishing the 30000 row insert at about 10ms per INSERT. I'm guessing it's because of INSERT statements being on multiple lines, and everything being done in a transaction makes it super slow.

We'll probably have to modify or create an equivalent tool to avoid this class of problem.

**Comment by mjibson** [comment]
Maybe I want to do this? Who knows?

**Comment by mjibson** [comment]
Also part of that slowness is because incrementing a SERIAL happens in its own transaction, so each INSERT has to complete a txn.
