### ISSUE TITLE
ui: previous diagnostic bundle activations will prevent new triggers on statements list page

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#50824]
When a user activates a diagnostic bundle collection, they will see any fingerprints with collected bundles marked as "Ready":

![image](https://user-images.githubusercontent.com/21692034/86141015-8b7d8380-babf-11ea-8cd8-ca480c6b7e32.png)

This "Ready" indicator prevents users from triggering another bundle from the statements list page. Because bundles are never cleared today, this means that once a user has activated bundle collection once, they will never be able to trigger another activation from the statements list page again. Because bundles are persisted indefinitely, this state will persist even after the statement statistics are purged. 

@Annebirzin - thoughts on a good way to resolve this? Perhaps we could both indicate that there are existing bundles separately from the ability to trigger a new one. I think that would result in only two states:

- "Activate" the user has not told the cluster to collect a trace for this fingerprint - independent of if traces/bundles exist
- "Waiting for Query" - we still need to let the user know if they have already triggered a bundle collection and prevent them from attempting to collect a new one.

The "Ready" status would be eliminated an instead replaced with a link to past bundles if we detect that any have been collected.

cc @florence-crl who mentioned this during our last Support sync.

**Comment by Annebirzin** [comment]
@piyush-singh I agree we could remove the 'ready' status on the statement list, but thinking we would still want to keep it on the statement detail page where the bundles are listed out. 

For the statement list, I think there could be 3 states:
