### ISSUE TITLE
sql: DROP DATABASE CASCADE not working in the 3node-tenant configuration

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#50840]
While trying to add a logictest, I discovered the following doesn't work under the 3node-tenant configuration:

```
statement
CREATE DATABASE db

statement ok
CREATE TABLE db.t(a int)

statement ok
DROP DATABASE db CASCADE
```

cc @asubiotto @nvanbenschoten

**Comment by asubiotto** [comment]
I think this is the same issue as #50048. Feel free to blacklist that config and point to that issue (i.e. `# LogicTest: !3node-tenant(50048)`
