### ISSUE TITLE
builtins: age returns unnormalized intervals

### ISSUE THREAD

**Issue by qinzl1** [cockroachdb/cockroach#50856]
![image](https://user-images.githubusercontent.com/20242930/86198163-90a70500-bb89-11ea-9050-0f39220e8be4.png)

----

otan edit:

`select age('2017-12-10'::timestamptz, '2017-12-01'::timestamptz)` returns 216 hours instead of 9 days. The age function should follow what Postgres does in normalizing intervals here:

https://github.com/postgres/postgres/blob/324435eb14e4f41cd430f96c9b13ad9b160e45e4/src/backend/utils/adt/timestamp.c#L3696-L3791

**Comment by yuzefovich** [comment]
cc @otan

**Comment by otan** [comment]
this is because `age('2017-12-10'::timestamptz, '2017-12-01'::timestamptz)` returns 216 hours instead of 9 days.
we don't seem to normalise intervals correctly (Postgres overflows hours to days, etc inva rious places).

**Comment by intech** [comment]
up! version 20.1.4 - 20.1.7
![](https://user-images.githubusercontent.com/451306/95915655-228cf380-0db0-11eb-87da-85e61e269ec2.png)
