### ISSUE TITLE
sql: downgrade follower read error to a notice

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#50890]
Users wonder about what will happen if they use follower reads in their codebase and then disable the enterprise features. Will their code still work?

Today, this will generate an error:
```
Use of follower reads requires an enterprise license. see https://cockroachlabs.com/pricing?cluster=2be49876-1acd-4784-8ca3-75f24dcf43c7 for details on how to enable enterprise features
```
We should downgrade this to a notice so that the code will continue to run and we should hardcode the time to AOST '-4.8s'.

**Comment by awoods187** [comment]
@solongordon thoughts on adding this notice?

**Comment by solongordon** [comment]
Are you talking about the error thrown by `experimental_follower_read_timestamp()` when enterprise is not enabled? So is the desired behavior that this built-in will continue to work (and return a notice) but `AS OF SYSTEM TIME` queries will no longer use follower reads?

**Comment by solongordon** [comment]
Followed up with @awoods187 and the desired behavior I described above is correct.

**Comment by otan** [comment]
`AS OF SYSTEM TIME queries will no longer use follower reads?`

seems different to

`We should downgrade this to a notice so that the code will continue to run and we should hardcode the time to AOST '-4.8s'`

I presume we just want `now()` instead of `-4.8s`? does setting it to `-4.8s` make it a follower read?

**Comment by awoods187** [comment]
If you are using follower reads today, you can use both a cluster setting and a specific function `SELECT ... FROM ... AS OF SYSTEM TIME experimental_follower_read_timestamp();`. If you go from the enterprise version of CRDB to the non-enterprise version, the cluster setting will no longer serve follower reads automatically. However, any query in your application you've modified to use `experimental_follower_read_timestamp();` will fail. Downgrading from enterprise shouldn't break your application. In the event of a downgrade, we want this query to still work, however, it can no longer serve a follower read. Instead, we should have it serve a query using `AS OF SYSTEM TIME` with a hardcoded value sufficiently far in the past to avoid breaking the app. Now would be a change in behavior by moving the query to the present and increasing contention when the user is likely trying to avoid contention.
