### ISSUE TITLE
log: provide option to redact PII and confidential data from logs

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#50905]
**Context**
Currently, users do not have a way to obfuscate _Personally Identifiable Information (PII)_ that could inevitably show up in logs. Customers have requested this ability in order to protect confidentiality. 

**Solution**
PII in CockroachDB’s log files will now be demarcated so that a redacted version can be easily generated. CockroachDB will continue to store all information in log files on disk, but will provide tools to generate a redacted version to share with Cockroach Labs' support or engineering teams in order to troubleshoot issues.

There will be a new server option `--redactable-logs` and new client option for debug zip `--redact-logs.

**Comment by thtruo** [comment]
FYI @knz this is a tracking issue for [PR 48076](https://github.com/cockroachdb/cockroach/pull/48076) you already have in place

**Comment by dbist** [comment]
In the future, it'd be a welcome feature to pass a regex string for a more flexible redaction, along with functions for typical predicates (IP, FQDN, etc).

**Comment by knz** [comment]
Addressed in the latest code.
