### ISSUE TITLE
storage: RangeStatsKey is not being replicated properly

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#5090]
When I filter out the stats key from the replica checksum computation and turn on the checksum verification  panic all the acceptance tests pass.

```diff
diff --git a/storage/replica_command.go b/storage/replica_command.go
index 423ce06..ff8c390 100644
--- a/storage/replica_command.go
+++ b/storage/replica_command.go
@@ -1422,10 +1422,18 @@ func (r *Replica) sha512(desc roachpb.RangeDescriptor, snap engine.Engine) ([]by
        hasher := sha512.New()
        // Iterate over all the data in the range.
        iter := newReplicaDataIterator(&desc, snap, true /* replicatedOnly */)
+       // stats key to be ignored for now.
+       statsKey := keys.RangeStatsKey(r.Desc().RangeID)
        defer iter.Close()
        for ; iter.Valid(); iter.Next() {
                key := iter.Key()
                value := iter.Value()
+
+               // Ignore the stats key because it's not replicated.
+               if bytes.Equal(key.Key, statsKey) {
+                       continue
+               }
+
                // Encode the length of the key and value.
                if err := binary.Write(hasher, binary.LittleEndian, int64(len(key.Key))); err != nil {
                        return nil, err
@@ -1494,7 +1502,7 @@ func (r *Replica) VerifyChecksum(batch engine.Engine, ms *engine.MVCCStats, h ro
                                        p()
                                } else {
                                        // TODO(.*): see #5051.
-                                       log.Errorf("checksums: e = %v, v = %v", args.Checksum, c.checksum)
+                                       panic(fmt.Sprintf("checksums: e = %v, v = %v", args.Checksum, c.checksum))
                                }
                        }
                } else {
```

**Comment by vivekmenezes** [comment]
On inspection it does looks like the range stats are being modified locally. This is the intent right? In which case I should change the key to not be a replicated one. Thoughts?

**Comment by tschottdorf** [comment]
If I remember correctly (@nvanbenschoten will know for sure), the stats key has a component which tracks the unreplicated data. It takes that into account correctly for stats, but it will break on hashing.

**Comment by bdarnell** [comment]
The range stats are only supposed to include replicated data, so they should be consistent across replicas. However, that hasn't been true in the past. Nathan has been making improvements in this area.

**Comment by vivekmenezes** [comment]
I got that by unmarshaling the value into &roachpb.Value{} and unmarshalling Value.RawBytes into &engine.MVCCStats{}

**Comment by vivekmenezes** [comment]
The stats were not being zeroed out as suggested in the earlier comments. I observed inconsistencies in the value of LastUpdateNanos for which I'm about to merge a fix.

**Comment by vivekmenezes** [comment]
This seems to still be a problem. Investigating.

**Comment by nvanbenschoten** [comment]
One thing to verify is `AdminSplits`. I got normal splitting to work correctly in a previous PR, but I seem to remember something with the data bytes being messed up with synthetic admin splits in particular (when sending the `cockroach debug range split` command).

Also, with the consistency checker, are we just looking to make sure the stats are consistent across replicas, or are we recomputing them (using something like `ComputeStatsForRange`) and making sure this recomputation is consistent with all replicas? If we're only doing the former, we might want to consider adding the latter as another step in the consistency verification.

**Comment by vivekmenezes** [comment]
Turns out the consistency check is failing even without including the range
stats. So we definitely have another bug elsewhere. I'll leave this open
for now.

We are not recomputing the stats as part of the consistency check.

**Comment by vivekmenezes** [comment]
We still have consistency issues with RangeStats and I've uncovered consistency issues with the transaction proto stored at a key like:

`/Local/Range/"\xba"/Transaction/addrKey:/id:"6977e321-9070-48f7-90d9-2497c828b68e"`

I think I know where the RangeStats are getting messed up. Will investigate the transaction proto stuff as well. I'm not sure if this is the end of it :-)

**Comment by vivekmenezes** [comment]
https://github.com/cockroachdb/cockroach/pull/5245

**Comment by vivekmenezes** [comment]
The problem with roachpb.Transaction is that it uses a `map<>` for observed_timestamps, and unfortunately you cannot depend on the on disk format for maps to be the same on all nodes. An iteration through a map can be in any order, and thus affects marshaling a map.

I'll fix this and also look at the other maps we use.

**Comment by petermattis** [comment]
Oh, nice find!
