### ISSUE TITLE
tpcc: update fixtures, tests, and workload with some removed origin indexes

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#50911]
Now that #50769 has landed and #50771 is on the way, we need to update our tests and fixtures to remove some of the origin indexes that we have strictly for foreign keys.

Some testing on a 3 node, 4 CPU cluster in GCE showed around a 10% improvement (635 WH -> 705 WH) in max supported warehouses when removing the indexes `history_customer_fk_idx`, `history_district_fk_idx` and `order_line_stock_fk_idx`. ~~I'm still testing to see if we can remove the `stock_item_fk_idx` or not~~. Performance is slightly worse without the `stock_item_fk_idx.`

So, we should remove these 3 indexes from our fixtures, tests and setup. The things that I think need to be done:
- [x] Update the TPCC workload fixtures (I'm not sure how to do this)
- [x] Update the workload tool to stop creating these indexes
- [x] Update existing logictest schemas to not have these indexes

**Comment by rohany** [comment]
cc @nvanbenschoten @RaduBerinde, let me know if I'm missing anything here

cc @awoods187 for prioritization

**Comment by RaduBerinde** [comment]
The list looks good. Unfortunately, the updated fixtures won't work on older versions so we should keep the old ones around.

I will take care of updating the optimizer tests (I need to update the test catalog to stop creating the FK indexes).

**Comment by awoods187** [comment]
This is great research--I'm excited we can pass this along to our customers in 20.2!

**Comment by nvanbenschoten** [comment]
> Performance is slightly worse without the stock_item_fk_idx.

Did we figure out why this was? It looks like the index is only used in a [single place](https://github.com/cockroachdb/cockroach/blob/e590a6e5bce892f3183f1e9c1e81a67f18aabe67/pkg/sql/opt/xform/testdata/external/tpcc#L406-L407), and I don't think it's the only index we could choose from there.

How many times did you run tpccbench for each of these variants? It's best to run 3-5 times to eliminate variance before drawing too strong of conclusions from the results.

**Comment by rohany** [comment]
I ran it twice for each variant. No, I didn't know why this was the case, but it does look like the primary index could be used instead in that query.
