### ISSUE TITLE
allow introspection of computed column in pg_catalog

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#50929]
**Is your feature request related to a problem? Please describe.**

`workload rand` is used to generate synthetic data.  It reads schema and produces data to match the schema.  It needs to skip auto-generated and computed columns without user intervention.  These skipped columns are identified by looking at `pg_catalog`  

**Describe the solution you'd like**

Using `pg_catalog`,  below is a hack for `rand`.  Is there another way to get using pg_catalog the presence of a hidden column of non-updatable columns?
```
SELECT attname, atttypid, adsrc, NOT attnotnull as isNullable, CASE WHEN conname IS NULL THEN true ELSE false END as isUpdatable
FROM pg_catalog.pg_attribute
LEFT JOIN pg_catalog.pg_attrdef ON attrelid=adrelid AND attnum=adnum
LEFT JOIN pg_catalog.pg_constraint ON conrelid=attrelid AND conname=('check_' || attname)
WHERE attrelid=$1`
```

**A clear and concise description of what you want to happen.**
What is a recommended method to identify that a column is a computed column using `pg_catalog`?  The recommended method will be incorporated in https://github.com/cockroachdb/cockroach/issues/50907

**Describe alternatives you've considered**
Using `informaton_schema` the hidden column shows up easily. 
```
select column_name,is_updatable,is_hidden from information_schema.columns where table_catalog=current_catalog and table_schema=current_schema and table_nam
e='test';
             column_name            | is_updatable | is_hidden
------------------------------------+--------------+------------
  id                                | YES          | NO
  crdb_internal_updated_at_shard_12 | NO           | YES
```

**Additional context**
[postgres 12](https://www.postgresql.org/docs/12/ddl-generated-columns.html) has generated column.  would make sense to follow that convention to preserve compatibility.

**Comment by ajwerner** [comment]
@robert-s-lee you can look at the `is_generated` column and the `generation_expression`.

**Comment by ajwerner** [comment]
Ah yeah, you noted that. I guess one question that I have is how to think about `pg_catalog` vs `information_schema`.

**Comment by rohany** [comment]
@robert-s-lee the `pg_catalog.pg_attribute` table contains the `attgenerated` column, which is set to `s` if the column is computed, and `` otherwise.
