### ISSUE TITLE
Using AWS KMS for encrypted backups

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#50937]
This issue serves as a knowledge dump of our exploration into using AWS Key Management System (KMS) for encrypted BACKUP and RESTORE.

AWS provides extensive documentation on KMS but below are some key concepts before we explain the design:
- **Customer Master Keys (CMK)**
 This is the master key generated by AWS KMS and it never leaves the KMS. It contains key-related metadata and key material to encrypt/decrypt other data. The key material can never be exported, deleted, or extracted. The CMK can be configured to be symmetric (256 bit), asymmetric (RSA) or an ECC key pair.
There are three kinds of CMK but for full control over rotation, grants, IAM policies we recommend using "Customer managed CMKs" which are tied to the user's AWS account.

- **Data Keys**
These are the keys that are generated for the purpose of encrypting/decrypting large amounts of data. CMK cannot be used directly as it has a 4Kb limit on the amount of data it can encrypt/decrypt at a time. Data keys live outside of the KMS, and are managed where they are used. The above-mentioned CMK is used to generate each of these data keys by the KMS. Data keys can also be symmetric or asymmetric. The latter is usually used when you have multiple entities trying to encrypt data, and a single entity trying to decrypt. This does not fit the BACKUP story and so we shall stick to symmetric data keys.

**Encrypted BACKUP story:**
We already support encrypted backups using a passphrase (https://www.cockroachlabs.com/docs/stable/backup-and-restore-advanced-options.html#encrypted-backup-and-restore) and so we are able to piggyback on most of the infrastructure and simply swap out how we generate our key.

On BACKUP if we cannot infer the encrypted data key from a previous backup manifest then we trigger the regeneration flow which is as follows:

- **Setup an AWS session using user-specified credentials.**
These credentials can either be "implied" which loads in credentials from the environment as detailed in https://docs.aws.amazon.com/sdk-for-go/api/aws/session/, or they can be "specified" via a URL scheme. To support this we would add a `kms_uri` option to the BACKUP/RESTORE statements which would look something like `vault://my.vault.host/key-to-use?vault-cred=some-cred`. This would allow the user to specify the AUTH scheme they wish to use and the required credentials. This is similar to how we interact with the S3 external storage buckets, and if possible we would like to design KMS support similarly so that we can support various providers in the future.
It is important to note that the URI scheme will be stored in the jobs proto so that restarted/scheduled jobs can use this information to interact with the KMS. We already do this for interaction with S3 storage and so are not increasing the security surface area.

- **Create a KMS client and generate CMK.**
This is the stage at which we can configure the CMK. The tunable parameters can be found at https://docs.aws.amazon.com/kms/latest/APIReference/API_CreateKey.html and need to be discussed with the security team.

- **Generate and pass around an encrypted DataKey (for the most part).**
This will give us access to an encrypted version of the DataKey. This encrypted version will be stored in the jobs proto, we are okay with this because the key is enveloped by the CMK. The processors performing the BACKUP will interact with the KMS to decrypt this stored DataKey before storing its plaintext version in the `ExportRequest` RPC. We do not want the KV layer (which will process this `ExportRequest` RPC) to interact with external services and so we must provide it with a ready-to-use DataKey. We can justify storing the plaintext DataKey in the `ExportRequest` because our communication lines are encrypted and we trust the user of this key.

- **Use plaintext DataKey to encrypt all BACKUP manifests and data files.**

Technically this does not seem too much of a commitment. A prototype can be found at https://github.com/cockroachdb/cockroach/pull/50068
Please let me know if there are any suggestions or knowledge gaps!

**Comment by mwang1026** [comment]
- Any node can talk to any KMS supplied; We won't handle "certain nodes encrypt certain data with certain KMS by locality" in this initial version
- Incremental needs to supply at least one KMS from the initial full backup; does mean you can't WIDEN the set of KMS -- would be bad if we tried to rewrite encryption_info and failed in the middle of truncate; future project to support this
- If originally encrypted KeyA, KeyB, KeyC and try to incremental with KeyA, KeyB, and KeyF, error because we don't want to make the user think that KeyF is now valid

q: When you rotate the key does the ARN change? What is effect of key rotation on the KMS? Need to somehow know if

**Comment by adityamaru** [comment]
Going to close this issue since the KMS implementation has been checked in.
