### ISSUE TITLE
sql: writing new descriptors to `system.descriptor` from SQL is not possible

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#50948]
**Describe the problem**

The `system.descriptor` table contains two column families. It has the following structure:

```sql
         table_name        |                create_statement
---------------------------+-------------------------------------------------
  system.public.descriptor | CREATE TABLE descriptor (
                           |     id INT8 NOT NULL,
                           |     descriptor BYTES NULL,
                           |     CONSTRAINT "primary" PRIMARY KEY (id ASC),
                           |     FAMILY "primary" (id),
                           |     FAMILY fam_2_descriptor (descriptor)
                           | )
```

The problem, however, is that we only ever write to this table by writing values into the second column family `fam_2_descriptor`. 
All over the place we anticipate only ever finding entries for the second column family. If you blindly attempt to insert into this table, you will write to the first column family and ultimately corrupt everything. For example:

```
root@localhost:26257/defaultdb> INSERT INTO system.descriptor VALUES (57, decode('121f0a046a756e6b10391a150a090a0561646d696e10020a080a04726f6f741002', 'hex'));
INSERT 1

root@localhost:26257/defaultdb> SHOW TABLES;
ERROR: value type is not BYTES: TUPLE
```

**Expected behavior**

We should be able to create new descriptors in the descriptors table from SQL in emergency situations.

**Comment by ajwerner** [comment]
I propose that we add new `crdb_internal.unsafe_` builtins to interact with the namespace and descriptors tables. We really should stop doing this `node` user as a granted role hack.

*  `crdb_internal.unsafe_upsert_descriptor(id INT8, hex_encoded_desc STRING)`
*  `crdb_internal.unsafe_delete_descriptor(id INT8)`
* `crdb_internal.unsafe_upsert_namespace_entry(parent_id INT8, parent_schema_id INT8, name STRING, id INT8)`
* `crdb_internal.unsafe_delete_namespace_entry(parent_id INT8, parent_schema_id INT8, name STRING, id INT8)`

I believe these functions would get us out of a number of binds. They will only be availble under root. Perhaps there should also be a session setting gating them. Thoughts?

**Comment by knz** [comment]
cc @thtruo @aaron-crl for sec triage and prioritization

**Comment by ajwerner** [comment]
FWIW I intend to implement the above functions this milestone. We've had lots of issues lately requiring manual repair and having these would be handy.

**Comment by knz** [comment]
> They will only be availble under root.

I assume you mean `admin`

**Comment by ajwerner** [comment]
> > They will only be availble under root.
> 
> I assume you mean `admin`

I meant `root`, I was intending to use this function for permissions checking:
https://github.com/cockroachdb/cockroach/blob/f03e6c6cf27552088b4479500b85b1fe7829c4a9/pkg/sql/sem/builtins/builtins.go#L5941-L5946

**Comment by knz** [comment]
This function is bad and should not exist. :)

I think it exists because the builtins package doesn't have access to the logic for privilege checks? Or something like that? Historically that is, because now it could (We have various Accessor gateways to the SQL engine in the EvalContext).

**Comment by ajwerner** [comment]
This should definitely have some synergy with #52248.

**Comment by ajwerner** [comment]
This all ends up being due to this odd special case in table construction for system tables:
https://github.com/cockroachdb/cockroach/blob/e049fda6bd2f9222788a78daf67f6ff492408db5/pkg/sql/sqlbase/structured.go#L1404-L1407

This is tech debt that we'll be carrying around for quite some time if we don't do anything about it. Unfortunately doing something about it somewhat sucks. We're going to need to look at what system tables are out there and how they are used.
