### ISSUE TITLE
security: Separate log directories by function 

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#50999]
**Is your feature request related to a problem? Please describe.**
Today, logs are being aggregated in the same directory whether they emit typical metrics for monitoring or security related audit logs. Based on organizational function and role, it would be beneficial to have ability to separate logs into multiple directories and make it flexible per log. That way a slow query log would be separated from an audit log based on the audience and provided filesystem privileges obfuscates the permission model away from the database.

**Describe the solution you'd like**
An ops user should be able to access logs for general Cockroach Logs. A security auditor should be able to access audit logs but not the ops logs. A DBA should be able to access slow query logs and ops logs but not the audit logs. Each log location should be flexible to a separate disk, directory, filesystem permission.

**Describe alternatives you've considered**
N/A

**Additional context**
Requested by a customer

**Comment by knz** [comment]
The audit log directory is separately configurable already, via `--sql-audit-dir`

What else needs to be configured?

**Comment by dbist** [comment]
based on the conversation in https://cockroachlabs.slack.com/archives/CGV7QUH1T/p1593726270019400, it is already configurable. closing..
