### ISSUE TITLE
ui: time picker does not use UTC like all time series metrics

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#51013]
As @koorosh pointed out in [45939](https://github.com/cockroachdb/cockroach/issues/45939#issuecomment-654237119) our time picker drop down's custom time option does not use UTC correctly. This causes UX issues when combined with the input validation that resets the custom time selection.

**Comment by koorosh** [comment]
To make it clear that time picker uses UTC - 'UTC' prefix is added to the time formating.
@Annebirzin , what do you think about the following change? Does it look proper or need some adjustments?
<img width="1025" alt="Screenshot 2020-07-07 at 12 20 12 PM" src="https://user-images.githubusercontent.com/3106437/86774537-4f1dca80-c05f-11ea-813f-d83b0701a792.png">

**Comment by Annebirzin** [comment]
@koorosh LGTM, thanks!
