### ISSUE TITLE
Audit External IO access during backup planning

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#51038]
Recent changes made it possible to run BACKUP under transaction.
This has the unfortunate side effect: we write external file (s.a. encryption file) during backup
planning.  If the transaction is rolled back, the file stays around.

This is unfortunate and probably wrong.
In general, we should avoid doing IO in planning phase, particularly write IO.

**Comment by adityamaru** [comment]
Going to wait on the refactor in #53060. The modularization of some of the encryption logic can then be moved into the Resume() handler of the BACKUP job.
