### ISSUE TITLE
backup: DETACHED backups don't protect timestamp

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#51067]
We need to protect in this branch too -- currently it is only done below, after the job creation. We can even do it in same txn used to plan the backup when doing DETACHED.

**Comment by miretskiy** [comment]
Yikes -- good find.

**Comment by adityamaru** [comment]
taking this over @dt, unless you have a fix in the pipeline?

**Comment by miretskiy** [comment]
I thought this was fixed?
