### ISSUE TITLE
jobs: tracing context is dropped when creating resumer

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#51104]
While using tracing to debug an issue with statistics collection, we noticed that the tracing spans from the execution of statistics collection were missing. The reason seems to be that the tracing context is lost when `Registry.CreateStartableJobWithTxn` creates the `resumerCtx`, which is passed to `createStatsResumer.Resume`.

Although we may want the `resumerCtx` to be detached from its parent for the purposes of context cancelation, we should still make sure that the tracing spans are linked.

cc @RaduBerinde 

Note: I added this to Bulk I/O Backlog since I'm not sure who officially owns the jobs infrastructure, but feel free to reassign.

**Comment by dt** [comment]
re: bulk-io backlog: Jobs common infra is mostly under the stewardship of schema, but bulk-io still is biggest consumer of and contributor to a lot of it and this might well be something we'd want for our use as well, so keeping it on our backlog as well as schema's for now.
