### ISSUE TITLE
sql: consistency check query doesn't get cancelled when context is cancelled

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#51132]
See https://github.com/cockroachdb/cockroach/pull/51130

The following query was observed to hang indefinitely (or at least for well above 3m):

https://github.com/cockroachdb/cockroach/blob/58875533d668b9297df72d8fef3e0a345c93abe8/pkg/cmd/roachtest/cluster.go#L1551-L1561

This means that the stmt_timeout did not seem to work.

**Comment by jordanlewis** [comment]
@tbg to make the details more obvious in the subject of this issue, please.

**Comment by jordanlewis** [comment]
Hypothesis: does the `check_consistency` builtin check its context? If not, it won't be canceled.

**Comment by tbg** [comment]
It probably does not, but shouldn't it pass the context down to distsender?
Maybe this is as silly as using context.Background() erroneously
