### ISSUE TITLE
sql: create a sql data consistency checker tool

### ISSUE THREAD

**Issue by spaskob** [cockroachdb/cockroach#51153]
**Is your feature request related to a problem? Please describe.**
Recently we have observed several production tickets related to inconsistent sql table metadata. The most common one being a table descriptor pointing to a missing parent database id.

Here is full list:

Triggered only by schema changes:
https://github.com/cockroachdb/cockroach/issues/38733
https://github.com/cockroachdb/cockroach/issues/45399
https://github.com/cockroachdb/cockroach/issues/48176
https://github.com/cockroachdb/cockroach/issues/50587
https://github.com/cockroachdb/cockroach/issues/50649
https://github.com/cockroachdb/cockroach/issues/50997

Drop database introducing missing parentID:
https://github.com/cockroachdb/cockroach/issues/50997

**Describe the solution you'd like**
Enumerate all invariants that hold for SQL metadata and create an on-demand tool that verifies their consistency.
Some ideas:

For system table invariants check that
  - all "default" descriptors have the correct ID
  - descriptors. are well formed
  - no orphaned namespaces / descriptors in the system.namespace table

For sql invariants check that
  - all FKs have a valid forward and backward reference
  - constraints/FKs are enforced correctly on each table / database

Based on the findings, audit the code locations where the metadata is updated and ensure that the invariants are preserved where feasible. The on-demand tool will eventually morph into a daemon that runs on all clusters.

Furthermore we may consider converting some of the mutation operations to self-healing. For example when dropping a table descriptor and the database id is missing, we could fix that on table drop.

A user can now also run a verifier on their database at any time. It can even be included in the debug.zip.

**Additional context**
@otan has created a great summary of his thoughts on the subject based on his work while at DropBox:
https://docs.google.com/document/d/1T3BMrhIDZnrVmiXS3flY48CDdJJ8UdNWERSL4LfsWq8/edit#heading=h.cai02giekzj3

**Comment by jordanlewis** [comment]
Thanks for filing this.

Several of these invariants are checked in the `Validate` methods on `TableDescriptor` and the like - see #50854. IMO, we should add as many invariants as possible to those methods.

I think a reasonable first step for this tool would be to run `Validate` over all `TableDescriptors` in the system, and report the errors it finds to the logs and potentially to Sentry.

**Comment by spaskob** [comment]
The first version of the tool will implement https://github.com/cockroachdb/cockroach/issues/52077.

At first we are only validating the system descriptors but later we will add checks for the consistency of running schema change jobs and other system invariants like all table descriptors that are not being dropped should be exactly the descriptor IDs in `system.namespace`.

I will follow with implementations that read the `system.tables` from a live cluster or a backup.

**Comment by spaskob** [comment]
The tool will run on the client side to facilitate quick deployment of new checks and so that the tool can be run by users without having to upgrade to the latest cockroach version.

The design of the tool will very likely go through significant changes as it evolves and more system tables need to be ingested
in order to implement more sophisticated checks.

**Comment by spaskob** [comment]
The MVP which is almost ready will check for three things:
- all table descriptors validate
- namespace entries correspond to valid descriptors
- schema change GC jobs refer to table descriptors that still exist (otherwise the job will get stuck)
