### ISSUE TITLE
sqlmigrations: migrate and clean up all 19.2 schema change jobs in 20.2

### ISSUE THREAD

**Issue by lucy-zhang** [cockroachdb/cockroach#51181]
In 20.1, we implemented an async migration to run in the background to upgrade all 19.2 schema change jobs into jobs that can be run by the new job resumer. There's no guarantee that this migration will complete successfully by the time a cluster is upgraded to 20.2. Furthermore, in the current implementation, there's no good provision for what to do if the migration fails due to finding persisted state it can't handle. If this happens, the migration will retry forever (and users are unlikely to notice in the logs and report this unless there's something obviously wrong).

Ideally, we'd run the migration as a startup migration in 20.2. But this is risky as-is because the migration is complex and we can't see whether the async migration is failing on actual clusters. #51176 adds Sentry reporting, which will hopefully give us more insight.

I think the options are:

- Write a startup migration that's similar to the existing async migration, but that always marks 19.2 jobs as failed if we can't migrate them for some reason and they're not already in a terminal state.
- Have the startup migration just unconditionally mark all 19.2 jobs as failed if they're already not in a terminal state, and tell users that they need to wait for all their 19.2 schema changes to finish first.

In practice, I think it's extremely unlikely that anyone will have actual schema changes they're waiting on that are left over from 19.2, but it's not unlikely that they'll have 19.2 jobs/tables stuck in a way that we can't automatically fix (and that the migration fails to deal with), so taking the latter option probably wouldn't make things more broken than they already are.

**Comment by jordanlewis** [comment]
Request: can we make sure to include some copious logs when this migration modifies jobs? On the off chance that we get into some bizarre, confusing state on a customer cluster, it seems like adding logs for the things that we edited would go a long way to giving us the forensic info we need to figure out what hapened.

**Comment by lucy-zhang** [comment]
We already have a fair bit of logging in the migration, including job IDs for all modified/created jobs, table and mutation IDs, and what we did to the jobs at a high level. It's hard to anticipate what else would help (in part because I don't believe we've ever actually seen an issue related to the migration in the wild). I suppose we could log full job details and redact appropriately.

**Comment by lucy-zhang** [comment]
>  I don't believe we've ever actually seen an issue related to the migration in the wild

This isn't true, since we did see the quite bad crash-looping bug that produced a Sentry report. What I meant was that we haven't had an issue where we had to use the logs to track down what happened to a job, which is probably because the migration does nothing nontrivial on most upgrades.

**Comment by lucy-zhang** [comment]
We're going with this option:

> Have the startup migration just unconditionally mark all 19.2 jobs as failed if they're already not in a terminal state, and tell users that they need to wait for all their 19.2 schema changes to finish first.
