### ISSUE TITLE
sql: improve sequence performance by implementing `cache` sequence modifier 

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#51259]
**Is your feature request related to a problem? Please describe.**

CockroachDB offers sql `SEQUENCE`s and supports using sequences to back the `SERIAL` datatype (with the `serial_normalization` setting). SQL sequences are perferrable to `unique_rowid()` in particular when an application would like to ensure that the IDs fall within some numerical range and are roughly increasing by small integer quantities. This is especially common when migrating existing applications. The integer values from `unique_rowid()` will be large and utilize roughly all 64 bits of the datatype.

The way sequences are implemented today can be unfortunate for scalability and throughput and especially unfortunate in geo-distributed topologies. Each time the `nextval` function is invoked, it performs a distributed operation against the key-value store to increment a key. This increment is somewhat unfortunate in that it creates a new version of the key due to the MVCC nature of the kv. When used at high throughput, sequences can lead to excessively large numbers of versions which can cause problems with gc (https://github.com/cockroachdb/cockroach/issues/42531, https://github.com/cockroachdb/cockroach/issues/50194). Furthermore, the sequence can become a serialization point within the system which hinders throughput.

Despite these problems with sequences as they are implemented, there continues to be demand and seemingly increasing usage. Perhaps instead of trying to push users towards more distributed-first approaches like `unique_rowid()` we could offer an implementation of sequence which may meet the needs of some users at the cost of some philosophical purity.

**Describe the solution you'd like**

This proposal here is to implement postgres's `CACHE` clause for sequences in a distributed manner. Postgres allows the creation of a sequence with a cache like:

```sql
postgres=# CREATE SEQUENCE cached_seq CACHE 100;
CREATE SEQUENCE
```

From the [postgres docs](https://www.postgresql.org/docs/12/sql-altersequence.html):

> The clause CACHE cache enables sequence numbers to be preallocated and stored in memory for faster access. The minimum value is 1 (only one value can be generated at a time, i.e., no cache). If unspecified, the old cache value will be maintained.

In the cockroach implementation we'd allow each gateway node to cache up to the number specified by cache less 1. So if the cache setting were 1, we'd use no cache. If the cache setting were 2, we'd allow each node to cache 1 value. This opt-in optimization could have huge benefits in global clusters, amortizing the cost to allocate an ID. 

This proposal also suggests we should offer a `serial_normalization` which defaults to a sequence with a cache of some reasonable value, maybe 64 or 256. 

It's worth noting that if we have a large cache, we can increment the sequence in increments of the cache size, dramatically reducing the number of MVCC versions created.

**Describe alternatives you've considered**

One thing which has been discussed in the context of reducing the cost of sequences on the KV has been around not using an MVCC operations. That would only further benefit this solution though it is possible that this proposal alleviates the pressure for that approach in some cases.

**Comment by ajwerner** [comment]
@arulajmani you may be interested in this after you finish up the other sequence dependency stuff.

**Comment by arulajmani** [comment]
I'm getting nerd sniped! There's still a couple of sequence dependency tasks on my plate, but I'll work on this after those are done if no one picks this up until then.
