### ISSUE TITLE
sql: add DROP DATABASE CASCADE test mode to logic tests

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#51254]
We've seen a few issues caused by `DROP DATABASE CASCADE` creating invalid descriptors, especially after the GC TTL ends.

We should add a test mode to the logic test suite that runs `DROP DATABASE CASCADE` at the end of tests, waits the GC TTL, and then runs `validate` on all table descriptors (or triggers the `validate` loop proposed in #51153. Hopefully, that would catch issues like #50712, #50997, #49940 and so on.

**Comment by ajwerner** [comment]
Closed by https://github.com/cockroachdb/cockroach/pull/53810
