### ISSUE TITLE
SQL Allow  foreign key constraints on computed columns

### ISSUE THREAD

**Issue by drewdeally** [cockroachdb/cockroach#51296]
features enhancement to allow computed columns to be used as a foreign key reference 

https://www.cockroachlabs.com/docs/stable/computed-columns.html#considerations

including columns computed from JSONB

https://www.cockroachlabs.com/docs/stable/computed-columns.html#create-a-table-with-a-jsonb-column-and-a-computed-column

**Comment by RaduBerinde** [comment]
Let's track this in #46672.
