### ISSUE TITLE
Release: add monitor to check the latest docker image contains the expected version of cockroachdb and alert when it differs

### ISSUE THREAD

**Issue by jlinder** [cockroachdb/cockroach#51297]
**The problem**

The `cockroachdb/cockroach:latest` image in dockerhub has mistakenly been deployed as _not_ the latest cockroach version and we didn't know that happened.

**What we want**

We want something monitor when the docker images change and alert the release engineering team when the latest image is not the expected image.

Epic RE-227
Jira issue: CRDB-4062

**Comment by kenliu-crl** [comment]
This is already done.
