### ISSUE TITLE
pebble: no space left on device results in quiet exit

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#51301]
I've stared for a long time at a roachtest failure where the roachprod monitor detected a dead node, but the node's logs did not indicate anything about the crash.
https://github.com/cockroachdb/cockroach/issues/51285

Eventually I found "no space left on device" messages in the Pebble log - which had been going on for minutes. The Pebble log itself seems to be truncated (last line is incomplete) - presumably because of space issues.
```
I200710 09:39:45.747824 51427 vendor/github.com/cockroachdb/pebble/compaction.go:1302  [n3] [JOB 1771] compaction to L3 error: write /mnt/data1/cockroach/007479.sst: no space left on device
I200710 09:39:45.747867 51427 vendor/github.com/cockroachdb/pebble/compaction.go:1227  [n3] background error: write /mnt/data1/cockroach/007479.sst: no space left on device
I200710 09:39:45.748663 51428 vendor/github.com/cockroachdb/pebble/compaction.go:1125  [n3] [JOB 1772] flush error: write /mnt/data1/cockroach/007480.sst: no space left on device
I200710 09:39:45.748683 51428 vendor/github.com/cockroachdb/pebble/compaction.go:1023  [n3] background error: write /mnt/data1/cockroach/007480.sst: no space left on device
...
```

I don't know how the process eventually died. It might not be Pebble that killed it. Maybe there should have been something in crdb's log, but perhaps we couldn't flush that log either.

Not knowing why crdb died is very frustrating. I think we should find a way for Pebble to crash as soon as a no-space issue is detected, and to make sure that the crash is reflected in cockroach's log.

@petermattis can I pass this to you?

Unrelated, this is the 3rd out of space I'm seeing today in last night's roachtests. Something is rotten.

Jira issue: CRDB-4061

**Comment by petermattis** [comment]
I don't think we changed anything in this area. @itsbilal can you take a look, both at the cause of the out of space and if we can surface that error better? Seems like we should make `EventListener.BackgroundError` log to the main CRDB log as well.
