### ISSUE TITLE
opt: investigate clean-up of special column handling

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#51323]
Currently, some table columns are special (e.g. write-only, delete-only). These special columns are arranged in a certain way in `cat.Table` (regular columns first, then writable columns, etc). ColumnCount has multiple variants used to get the boundaries.

This arrangement makes optimizer code error-prone, because special columns can easily be ignored; and it makes adding new types of columns harder (eg #50519).

This issue tracks investigating an alternative where `cat.Table` has a method `ColumnKind(ordinal int)` which returns an enum. No assumptions would be made about the order of the columns in the table. This will force all code to check the column kind, rather than implicitly ignoring certain kinds of columns depending on which `Count` method is used.

Note that putting this method in `cat.Column` is problematic because currently the implementor of that interface is `*ColumnDescriptor` where don't have enough information.

**Comment by andy-kimball** [comment]
Another variation: we have a method called Column(kinds Kind), where Kind is defined something like:
```
type Kind int
const (
  AllCols Kind = 0
  NotHidden = (1 << iota)
  NotSystem
  NotWritable
  NotDeletable
  NotMutation = (NotWritable | NotDeletable)
)
```
This way, callers get all columns by default, and have to explicitly list which columns they _don't_ want, which makes it more likely they'll think through each case.

**Comment by RaduBerinde** [comment]
What does `Columns(kinds)` return?
