### ISSUE TITLE
Accelerate queries using eager predicate evaluation

### ISSUE THREAD

**Issue by xinyuliu12** [cockroachdb/cockroach#51361]
Hello everyone!

First off, I am sorry for *gestures vaguely* all of this. Second, I think we have found a performance bug related to join queries wherein the predicate is false.

Here’s a TPC-H query that exhibits this behavior:

```
SELECT o_orderpriority
FROM   orders
WHERE  (SELECT n_comment
        FROM   nation
        ORDER  BY n_comment
        LIMIT  1) IS NOT DISTINCT FROM 'random string';
```

**Actual Behavior**
This query takes ~8.3 seconds on v20.1.3.
With the generated query execution plan, the database system scans the large orders table (7500000 rows), even when the predicate on the nation table can be evaluated within a few milliseconds. (only 25 rows).

**Expected Behavior**
This query could be executed in tens of milliseconds. As a reference point,  PostgreSQL executes it in ~1 millisecond.
Here are the steps for reproducing our observations:

**Test environment**

* Ubuntu 20.04 machine "Linux panda 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux"
* Cockroachdb v20.1.3
* Database: TPC-H benchmark (with scale factor 5)

**Reproduce Bug**

1. Install cockroachdb v20.1.3     

```
    $ wget -qO- https://binaries.cockroachdb.com/cockroach-v20.1.3.src.tgz | tar  xvz        
    $ cd cockroach-v20.1.3
    $ make build
    $ sudo make install
```

* start a cockroachdb node in your preferred working directory
```
    $ cockroach start --insecure --store=node1 --listen-addr=localhost:26257 --http-addr=localhost:8080 --join=localhost:26257,localhost:26258,localhost:26259 --background
    $ cockroach init --insecure --host=localhost:26257
```

2. Set up TPC-H test benchmark (if you already have a TPC-H benchmark set up, you can skip step2; starting from step2, all commands should run in the directory ./tpch5 after downloading and extracting it)

* Download TPC-H (scale factor of 5) and extract it
    Download the dataset from the link: https://drive.google.com/file/d/1fYHVvxWKsCjUVFu0D2LZeZNklH090YI9/view?usp=sharing
```
    $ tar xzvf tpch5.tar.gz
    $ cd tpch5
    $ chmod +x setup.sh
```

* Create DB and TPC-H schema
`   $ cockroach sql --insecure --host=localhost:26257`    
    In CockroachDB's built-in SQL client to create database:
```
    $ create database tpch5;
    $ exit
```
* Create TPC-H Schema
   `    $ cockroach sql --insecure --host=localhost:26257 -d tpch5 < dss.ddl
`
* Import benchmark
`   $ ./setup.sh
`
3. Test SQL query that exhibits performance issue

* Execute the queries 
`    $ cockroach sql --insecure --host=localhost:26257 -d tpch5 < query.sql
`

**Comment by RaduBerinde** [comment]
Dup of #51820.
