### ISSUE TITLE
Importing into a DB where a user has DB level privileges would fail

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#51371]
The following sequence of SQL queries fails with a CPUT error due to a mismatch between the privileges written to KV and published after import.
```
CREATE DATABASE b;
USE b;
CREATE USER foo;
GRANT ALL ON DATABASE b TO foo;

// Upload a CSV file to ExternalIODir/test.csv
IMPORT TABLE bar (id INT, name STRING) CSV DATA ('nodelocal://0/test.csv')
```

**Comment by mwang1026** [comment]
We should backport this

**Comment by adityamaru** [comment]
Turns out this bug was introduced after the 20.1 release. In 20.1 we don't take a copy of the TableDescriptors and wrap them in MutableTableDescriptors, and so there is no disconnect between the descriptors written to KV and published on IMPORT completion.
