### ISSUE TITLE
Large upserts can hit up against kv.raft.command.max_size

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#51391]
This was from a customer:

```sql
UPSERT
  INTO dest (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u)
       (
		SELECT a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u
		  FROM source
		 WHERE v IN ('value1, 'value2')
       );
```

The original table is only 34MiB.

And it get this error:
`[XXUUU] ERROR: command is too large: 258209243 bytes (max: 67108864)`

We should be limiting the batch size in an upsert and doing the splitting internally.

* `IMPORT INTO` won't work, because it will lock the destination table.  And requires writing to a disk then back.
* `CREATE TABLE AS` won't work, because it's not a new table.

**Comment by BramGruneir** [comment]
This should be batching at 10k - maxUpdateBatchSize.

Not sure why it doesn't.

**Comment by BramGruneir** [comment]
Assigning to @nvanbenschoten for triage.

**Comment by nvanbenschoten** [comment]
> Not sure why it doesn't.

There's not a definitive indication that it's not. My guess is that they have a large number of secondary indexes on this table.

**Comment by BramGruneir** [comment]
Oh, I should add this is on 19.2.5

**Comment by nvanbenschoten** [comment]
Any update on this @BramGruneir?

**Comment by yuzefovich** [comment]
I looked into the upsert behavior, and although I think I might have found a bug with pagination on master, the code was changed in 20.1.0 and later, and on 19.2 branch I don't see a problem. (Granted, this is pretty much the first time I'm looking carefully at the code, so I might be missing something.)

**Comment by BramGruneir** [comment]
They have updated to 20.1.3 and are still experiencing the same behaviour.

**Comment by yuzefovich** [comment]
I think the same bug is present on 19.2 branch - the code has been changed, so it was harder to spot it. I believe it was introduced in 19.1 release cycle when we added support for UPSERT by the optimizer.

**Comment by BramGruneir** [comment]
@yuzefovich is this change backportable to 20.1?

**Comment by BramGruneir** [comment]
Ah just noticed that you're backporting to 19.2, awesome.  Thanks!
