### ISSUE TITLE
backup: backups blocked by long-running transactions

### ISSUE THREAD

**Issue by DuskEagle** [cockroachdb/cockroach#51414]
Long running transactions can block backups from finishing until the transaction finishes. We have observed this when a cluster was running a 8+ hour `ALTER TABLE x DROP CONSTRAINT y` query. Our backups of the database containing table `x` become blocked until the query finished.

We attempt to take backups every hour as long as a backup is not currently running. If we are unable to successfully finish a backup for too many hours, we receive a page. As a result of this issue, we have adjusted our paging thresholds to avoid getting paged as often, but we are still unable to offer any SLA on the frequency of backups as long as backups can be blocked indefinitely by long-running transactions.

**Comment by DuskEagle** [comment]
This seems related to https://github.com/cockroachlabs/support/issues/365. In that ticket, @dt said,

>In 20.2+, when sending backup requests to ranges, BACKUP will default to asking KV not to block forever on transactions and instead fail quickly. That way the backup process can put those ranges on the back-burner and move on to the rest of the backup, in the hopes those transactions may clear on their own in the meantime, then come back to retry those ranges at the end. Once the time at which the backup is reading is far enough in the past, those retries will stop setting the fail-fast flag and instead be run with high priority to push the other txns. So BACKUP should be less likely to be blocked by long-running transactions, hopefully without being too disruptive thanks to the grace period before invoking that priority.

**Comment by dt** [comment]
https://github.com/cockroachdb/cockroach/pull/51624
