### ISSUE TITLE
sql,lease: `Publish`/`PublishMultiple` are bad APIs which can cause bugs

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#51417]
**Describe the problem**

The `lease.Manager` contains a method [`PublishMultiple`](https://godoc.org/github.com/cockroachdb/cockroach/pkg/sql/catalog/lease#Manager.PublishMultiple) which takes a set of IDs to modify and a closure to modify them and encapsulates creating an transaction and running retry loops. This method is utilized in schema changes (and in some cases in imports and restores).

One observation is that this method doesn't utilize anything interesting about the `Manager` object on which it resides. Worse yet is that this API takes a static set of IDs with no mechanism to update that set upon retry. 

In the case of schema changes, this set of IDs can refer to tables referenced as foreign keys, or, more recently, referenced types. A hazardous race which can occur is that the table becomes dropped while the schema change is operating. If this happens, there is no longer an invariant that the referenced tables exist. In practice, due to the fact that tables wait some time for GC, this hazard is unlikely to come up in reference to fk relationships. With types however there is no such waiting period.

What this all points out is that the PublishMultiple interface is bad. It probably should not live in the lease package, or at least, should not be a method, and it should not be responsible for creating a transaction.

**Describe the solution you'd like**
The main solution I'd like to see is that we either nix `Publish`/`PublishMultiple` entirely, or we have them take a transaction and a set of read descriptors from that transaction rather than a set of IDs.

**Comment by ajwerner** [comment]
`Publish` isn't actually known to be problematic. It's just not obvious why we want this API to be creating a transaction on our behalf. It is the case that waiting for leases can lead to an error which needs to be retried but it seems okay and clearer to bubble the retry responsibility up to the caller.

**Comment by ajwerner** [comment]
The current thinking here is that we should force all mutable descriptor access to go through a `descs.Collection` which is tied to the lifetime of a transaction.

**Comment by lucy-zhang** [comment]
Marking this as a release blocker to cover the RESTORE use case (#53727)
