### ISSUE TITLE
backup: smoke-test descriptors when backing up

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#51423]
Observed error during restore where 
MutationJobs field was not synchronized with  with the Mutations field on that table descriptor.

```
RESTORE FROM 'gs://cockroach-managed-staging-backup-long-lived/cluster/soc2test?AUTH=implicit';

ERROR: could not find mutation 0 on table ip_whitelist_names (151) while restoring
```

We should detect this (and probably other erroneous) condition and return an error during the backup.

Epic CRDB-7779

Jira issue: CRDB-4050

**Comment by dt** [comment]
This ties in I think with what @jordanlewis has been trying to do with improving schema validation methods, so we can catch badness right away before it spreads and starts having spooky effects on systems far removed from it (like, say, RESTORE)
