### ISSUE TITLE
sql: review postgres features and add unimplemented errors

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#51424]
Postgres has added a number of features since version 9 that are users are interested in CockroachDB supporting, for example Trigrams (https://github.com/cockroachdb/cockroach/issues/51137). Unfortunately, we don't have unimplemented errors for these features so we return syntax errors to users which can be confusing. Further, we don't collect telemetry to inform us of where we should next spend our time. Let's spend some time auditing the difference and adding important unimplemented errors.

**Comment by otan** [comment]
Basing off comparing https://www.postgresql.org/about/featurematrix/ and 9.6.

# PostgreSQL 10

* macaddr8 data type
* table data partitioning (https://www.postgresql.org/docs/10/ddl-partitioning.html#ddl-partitioning-declarative)
* SCRAM-SHA-256 Authentication

# PostgreSQL 11
Nothing we don't already have (STORED in indexes)

# PostgreSQL 12
* SQL/JSON Path language (https://www.postgresql.org/docs/current/functions-json.html#FUNCTIONS-SQLJSON-PATH)
* CREATE ACCESS METHOD
* REINDEX CONCURRENTLY
* Stored Generated Columns (https://www.postgresql.org/docs/current/ddl-generated-columns.html)
* Foreign Key references for partitioned tables
* COPY FROM .. WHERE (https://www.postgresql.org/about/featurematrix/detail/330/)
* GSSAPI client and server-side encryption
* LDAP server discovery
* Multifactor authentication via valid client SSL/TLS certificate

**Comment by otan** [comment]
some of these sound like we want to no-op, some we want to support and some we want to alias. i think i'd go insane if it was just me doing this, so i'd rather we do this list as a group ^

**Comment by vy-ton** [comment]
@otan I dont think this issue was about making a decision for any of these features. Rather, we would just add unimplemented errors across the board. Is that also difficult/insane?

If not I'm happy to sit down and work through this list.

**Comment by otan** [comment]
some are (potentially) no-ops / we may not ever support it / already implemented. also unimplemented means we file an issue for each one.

some i think we already support just with different syntax. 🤔 ill knock a few obvious ones out tomorrow and leave solon to deal with the rest next week :P

**Comment by otan** [comment]
alright knocked out a few (and growing weary of reading sql.y errors) -- back to solon whilst I go on PTO
