### ISSUE TITLE
backup: use BACKUP to add to collection of backups

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#51448]
When BACKUP was introduced, we asked you to tell us where to backup to, and optionally from what incremental bases that backup should be. If you backed up to A yesterday and wanted to backup what had changed today, you had to say `BACKUP TO B INCREMENTAL FROM A`. If tomorrow you again wanted to back up what changed, you had to say `BACKUP TO B INCREMENTAL FROM A, B`. To append to this chain you needed to provide the chain so far. To restore it, you needed to provide the whole chain.

While this works, many users found it cumbersome. Needing to keep track of which backups were where and which ones were chains in order to append to the chain was difficult. Some just skipped incremental, while others always did incremental from the original location, creating many chains, each with just one added link, but with that one link getting longer each time (and more expensive to produce, re-backing up what had been backed up in prior chains).

In 20.1 we started trying to address this cumbersome UX with what we have been referring to as "appending" to a backup: You can say `BACKUP TO x` and then say `BACKUP TO x` again with the same x and instead of saying "no, x already contains a backup", 20.1 instead looks at the backup in x and _automatically_ creates an incremental backup from it, writing to a new path under x. The next time it finds that one as its incremental base. The result is the chain is automatically tracked under x, with appending to it or restoring to any point on it requiring the user only point us at the base location and we find the rest within it.

While we believe this was a big improvement over what we had before for ease of use, we still require that, if a user wants to create a _non_-incremental backup, they need to point to a new destination `y`. But like explicit incremental chains prior to 20.1, this still puts the burden on them to keep track of the locations x, y, z... that they've put such backups in, which one they're currently appending changes to, etc.

Ideally, we'd handle all of this for you: you just tell us where you want your backups let us figure out where the next backup should go within that folder, regardless of whether it is a full or incremental backup. This is especially true as we soon expect that not all users running BACKUP will also have access to incremental backup. Briefly ignoring the append behavior added in 20.1, you could imagine something like just running `BACKUP TO s3://my_backups` whenever you want to backup, be that weekly or daily or hourly. Each time it is run, it creates a new backup in my_backups. If you wanted to incrementally backup just the changes since your last backup, you could do `BACKUP TO LATEST IN s3://my_backups`.

Unfortunately this would be backwards incompatible with the behavior introduced in 20.1, where the second run of ``BACKUP TO s3://my_backups` is expected to be incremental from the first, and thus must be run within the incremental window, requires access to the incremental feature, etc. Changing it to only be incremental with the addition of the `TO LATEST IN` modifier would be backwards-incompatible.

To get around this, we can instead add a distinct statement, a variation of `BACKUP TO`  that uses these new semantics, without breaking the old ones. We've bikeshed'ed several options here, from `BACKUP TO COLLECTION x` + `BACKUP TO LATEST IN COLLECTION x` or `BACKUP TO NEW IN x` + `BACKUP TO LATEST IN x`, or even keeping `BACKUP TO x` meaning as is and making non-incremental backups opt-_out_ with something like `INCREMENTAL FROM NOTHING`.

Our bikeshed conclusion however was to simply switch `TO` to `INTO` -- still short and sweet (unlike "COLLECTION"), but conveys the subtle difference of picking a path within the collection of backups at x. Thus this new syntax would look like this:
```
BACKUP INTO s3://my_bucket # each day/week, when you want to make a full backup
BACKUP INTO LATEST IN s3://my_bucket # hourly/daily, to capture incremental changes
```
`BACKUP INTO x` is exactly like `BACKUP TO x` except that if x already contains a backup, it doesn't automatically become implicitly incremental from that backup - it just _always_ means to put a (full) backup at a path under x.
`BACKUP INTO LATEST IN x` takes the place of `BACKUP TO x` repeat-run appends, finding the latest full backup under x and appending changes to it like today's `BACKUP TO` does.

Given that there is nothing BACKUP TO can do that BACKUP INTO can't we'd likely then deprecate the `BACKUP ... TO` syntax and emit notices when it is used suggesting `INTO`.

**Comment by pbardea** [comment]
@dt It seems like this can be closed out, correct? Also, did we want to start deprecating the `TO` syntax in 20.2?

**Comment by mwang1026** [comment]
Closing with https://github.com/cockroachdb/cockroach/pull/52329. Deprecation I think we punted to 21.1
