### ISSUE TITLE
ui: allow zoom on timeseries

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#51456]
Cleaning up #13752. A common request from users is to enable a simple method for zooming the time scale on our time series charts in the Admin UI. We should consider two methods to allow zooming:

- Using a mouse scroll wheel
- Clicking and dragging the cursor

**Comment by petermattis** [comment]
@piyush-singh see https://cockroachdb.github.io/pebble/ for example user interaction which does this. Scroll wheel and double-click to zoom. Click and drag to pan.
