### ISSUE TITLE
sql: parse followed by format is not idempotent for EXPLAIN ANALYZE (PLAN)

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#51473]
found by the RSG tests:

Parse followed by Format is not idempotent: "EXPLAIN ANALYZE ( PLAN ) ALTER SEQUENCE HOUR RENAME TO FAMILY . LEAST . GREATEST" -> "EXPLAIN ANALYZE ALTER SEQUENCE hour RENAME TO \"family\".least.greatest" != "EXPLAIN ANALYZE (DISTSQL) ALTER SEQUENCE hour RENAME TO \"family\".least.greatest"

**Comment by RaduBerinde** [comment]
`EXPLAIN ANALYZE (PLAN)` is invalid and should error out.

**Comment by RaduBerinde** [comment]
@rohany can you clarify exactly what RSG is doing? Is it actually using the `tree` code directly to Parse and Format?

**Comment by RaduBerinde** [comment]
I think that won't work in general, various statements have multiple forms that get normalized. My guess is that it's generating a statement, parsing it, dumping it, then parsing it again, then dumping it again, and cross-checking the two dumps.

**Comment by rohany** [comment]
The relevant code is in `pkg/sql/tests/rsg_test.go:55`
