### ISSUE TITLE
GC for DROP INDEX running indefinitely

### ISSUE THREAD

**Issue by kocoten1992** [cockroachdb/cockroach#51582]
**Describe the problem**
Drop index and job GC been running for two days (database is very small), progress said at 0.0%

**To Reproduce**

Create several indexes then drop several indexes (I was experimenting with the most optimal index for several queries), then I got to this situation

```
GC for DROP INDEX samehada.public.tasks@tasks_executor_retry_count_debug_type_status_biseq_piece_id_prio_created_at_idx
```

After one day, I knew something was happen, tried to cancel job but it said:

`ERROR: job 573282833283547137: not cancelable`

Job could be paused and resume, but not cancelable, it look like will hang indefinitely :(.

```
Build Tag:    v20.1.3
Build Time:   2020/06/23 08:44:08
Distribution: CCL
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.13.9
C Compiler:   gcc 6.3.0
Build SHA-1:  7fd454f880f386cdd0eda6b21b12f6532c14f0db
Build Type:   release
```

**Expected behavior**
GC job for index should finish.

**Additional data / screenshots**
![image](https://user-images.githubusercontent.com/7130705/87861847-7d12e100-c974-11ea-8a11-17f18f845469.png)

**Comment by kocoten1992** [comment]
just want to update, it finished when I last check, not sure why it would take that long, sorry for the fuss :sweat:

**Comment by lucy-zhang** [comment]
The GC job waits around for however long your configured GC TTL (`gc.ttlseconds`) is for that index before actually doing GC. If that's not consistent with what you saw (i.e., the job took much longer to finish), let us know.
