### ISSUE TITLE
colexec: add optimized support of "contains" LIKE match

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#51584]
We currently have optimized support of LIKE matching for "prefix" match (`test%`) and "suffix" match (`%test`). We could also easily add support for "contains" match (`%test%`) using `bytes.Contains` function.

This will require the following:
1. updating `execgen/like_ops_gen.go` to introduce the new "overload" for LIKE operator to be generated (you'll need to run `make execgen` to regenerate the code)
2. updating `colexec/like_ops.go` to support new "contains" `likeOpType`
3. updating `GetLikeOperator` and `GetLikeProjectionOperator` methods accordingly
4. adding some tests in `logic_test/vectorize`.

**Comment by clucle** [comment]
Hi @yuzefovich I'd like to work this issue if no one is working on it.

**Comment by clucle** [comment]
Should I add  `BenchmarkLikeOps` in `execgen/like_ops_test.go` for "contains"?

**Comment by yuzefovich** [comment]
Hi @clucle, thanks for the interest! I'll assign the issue to you.

In terms of benchmarks, you should adjust `BenchmarkLikeOps` in `colexec/like_ops_test.go` to include the "contains" pattern. Also, it'd be nice to add a couple of unit test cases in `TestLikeOperators`.

**Comment by clucle** [comment]
https://github.com/cockroachdb/cockroach/blob/276dd82713a37572a565acd4c282780e2a627d44/pkg/sql/colexec/like_ops_test.go#L82-L92

In my opinion, it seems that `TestLikeOperators` already contain the test, so I didn't reflect it.

Should I add a test case?

**Comment by clucle** [comment]
@yuzefovich 

I don't know how to add a reviewer( #51598 ) because this is my first contribution to this project.

Help me plz 😄

**Comment by yuzefovich** [comment]
> In my opinion, it seems that `TestLikeOperators` already contain the test, so I didn't reflect it.

Oh yeah, I didn't see it. No need for extra test case then.

**Comment by yuzefovich** [comment]
This issue has been addressed by #51636.
