### ISSUE TITLE
changefeed not work, and resovled timestamp is 0

### ISSUE THREAD

**Issue by wqc200** [cockroachdb/cockroach#51597]
cockroach version: 19.1
file: pkg/ccl/changefeedccl/changefeed_processors.go
func: noteResolvedSpan
code: frontierChanged := cf.sf.Forward(resolved.Span, resolved.Timestamp)

when i test change feed, i found resolved.Span and resolved.Timestamp is both 0, so emit resolved timestamp failed!

**Comment by jordanlewis** [comment]
Sorry, you'll need to provide more details on your test setup for us to be of help here.

**Comment by dt** [comment]
@wqc200 Thanks for digging into this a bit and tracking it to that line. However as mentioned above, to look into this further we'd need a few more things:
 - exact version (19.1 has had many fixes released in patch releases).
 - steps to reproduce: what kind of table and data, what's the SQL workload running against that table, and, most importantly, what's the changefeed command being used? is this a SQL feed or is it using a sink?

Thanks again for getting in touch!
