### ISSUE TITLE
schedules: Schedule Control

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#51600]
Implement schedule control statements.

Informs #28266

Similar to how operators can control jobs (PAUSE JOB, RESUME JOB), we need a way to
control schedules.

Schedule control statements look like:
`<COMMAND> SCHEDULE(s) <schedule_selector> WITH <job_command> JOBS`

Command: is one of PAUSE or RESUME.  
schedule_selector: same as jobs selector -- either a list of schedule ids, or a select statement returning schedule ids.
The `WITH <job_command>` specifies the job command for the jobs managed by this schedule.

`PAUSE SCHEDULE 213 WITH CANCEL JOBS`
`RESUME SCHEDULES SELECT schedule_id FROM system.scheduled_jobs WHERE owner='blah'`

It's not clear (yet) if we should support `CANCEL SCHEDULES`.  Is cancel == delete?  Then, just delete the schedule.
On the other hand, what if we want  to cancel jobs before we delete the schedule?  @dt @mwang1026

**Comment by mwang1026** [comment]
Is the `WITH <job_command>` part mandatory? If not what is the default?

If we don't support `CANCEL SCHEDULES` how would one "remove" the schedule?

Do we have a row TTL on the schedules table a-la-Jobs table?

**Comment by miretskiy** [comment]
No, WITH job_command is optional, and the default is do nothing.  If there are running jobs, they will continue running.

Removal can be done simply with `DELETE FROM`

No ttl on schedules

**Comment by mwang1026** [comment]
Makes sense re: default -- we just need to know what to doc.

re: `DELETE FROM` I don't think we should expect users to much around with system tables and that we should have a SQL command. For example, we don't ask people to delete from JOBS table today. Thoughts?

**Comment by miretskiy** [comment]
I don't know ... re delete.
I'm looking at e.g. PAUSE JOBS.  Users are expected to specify a query -- so, we are expecting them to specify regular
sql query -- we don't offer syntactic sugar for finding jobs to paus.

PAUSE JOBS SELECT job_id FROM [SHOW JOBS WHERE]....
Why should we provide syntactic sugar for delete then?

Or, alternatively, do we want a more restrictive API where the users can only work on 1 schedule at a time and they have to specify schedule id?

**Comment by dt** [comment]
I think we should offer `DROP SCHEDULE` or `DELETE SCHEDULE` (i prefer `drop` for symmetry with `create`) -- we shouldn't encourage users to mutate system tables directly.

**Comment by miretskiy** [comment]
I was just chatting re `DROP SCHEDULE` w/ @mwang1026 .

Should we offer `DROP SCHEDULES` as well, as in `DROP SCHEDULES SELECT ...`?
On one hand -- yes, there is a symmetry.

On the other hand -- looking at job control, these statements return # of rows effected (not the actual rows) -- which 
makes it a bit hard to know if what you're pausing/cancelling is really what you meant to pause/cancel.

**Comment by miretskiy** [comment]
Yes, I plan on supporting same thing as we support for job control
So, drop schedules select is supported.

**Comment by miretskiy** [comment]
Yeah -- I wish job control didn't do it and returned actual rows.

However, if you think of job control stuff as just update statement of sort, then it makes sense that we only return
rows effected.

**Comment by miretskiy** [comment]
I'm going to hold off on implement `WITH` modifiers.  There are some issues wrt to statement semantics
(what's the meaning of number of rows modified).  Ideally, we would return rows from these statements, but that
was also proving to be more challenging.

For now -- going to support basic PAUSE/RESUME/DROP only.

**Comment by mwang1026** [comment]
IMO I think that's sufficient. Users can cancel jobs on their own if need be for v1. IMO there's higher impact work elsewhere to do rn. Thanks for the hard work / thinking here.

**Comment by mwang1026** [comment]
Also encapsulates jobs control `FOR SCHEDULE`

example: `PAUSE JOB FOR SCHEDULE xyz`
