### ISSUE TITLE
sql: `DROP DATABASE CASCADE` hangs under the 3node-tenant logictest config

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#51606]
I haven't investigated this very much, but from what I can tell the `DROP DATABASE` schema change job completes and returns to the conn_exector, so something else outside of that execution path is going wrong.

Can reproduce by removing the config comment at the top of `drop_database` logictest, and using this command:

```
make test PKG=./pkg/ccl/logictestccl/ TESTS=TestTenantLogic TESTFLAGS="-show-sql -test.v -d ../../sql/logictest/testdata/logic_test/drop_database"
```

**Comment by rohany** [comment]
Closing, sorry I didn't realize this was a duplicate.

**Comment by nvanbenschoten** [comment]
For continuity, closed in favor of https://github.com/cockroachdb/cockroach/issues/50048.
