### ISSUE TITLE
Changefeed fails with pq: descriptor not found

### ISSUE THREAD

**Issue by fracasula** [cockroachdb/cockroach#51639]
Hello, I'm unable to start an experimental changefeed with the following command:

```
kubectl -n my-namespace exec -it crdb-cockroachdb-1 -- ./cockroach sql --insecure --format csv -d my-database -e "EXPERIMENTAL CHANGEFEED FOR table1,table2,table3 WITH updated, resolved='300s'"
```

The tables are all there, I checked with a `SHOW TABLES;`.

I did some tests and I'm able to start the changefeed if I remove some tables (e.g. `table2`). In fact, if I try to start a changefeed just on `table2` for example, the changefeed errors.

```
table,key,value
table1,[1584813962],"{""after"": {""dirty"": false, ""version"": 1584813962}, ""updated"": ""1595334598812559965.0000000000""}"
(error encountered after some results were delivered)
ERROR: descriptor not found
Failed running "sql"
command terminated with exit code 1
```

**Environment:**
Server version: CockroachDB CCL v20.1.3 (x86_64-unknown-linux-gnu, built 2020/06/23 08:44:08, go1.13.9) (same version as client)

Jira issue: CRDB-4023

**Comment by ajwerner** [comment]
This will be the case for some amount of time after the table is dropped. It should not however be all that long. How long after the table dropping are you seeing this behavior?

**Comment by fracasula** [comment]
> This will be the case for some amount of time after the table is dropped. It should not however be all that long. How long after the table dropping are you seeing this behavior?

@ajwerner We cleaned up the database completely the 16th of July around 10am UTC. Before doing the cleanup we scaled down all pods in Kubernetes to make sure nobody was really reading or writing from/to the database. The cleanup script truncates the tables though, it doesn't drop them. Here's an excerpt:


```
DATABASES=$(echo 'SHOW DATABASES;' | kc --context staging --namespace my-namespace exec -i crdb-cockroachdb-0 -- ./cockroach sql --insecure --format raw | grep -v '^#')

for DATABASE in ${DATABASES}; do
    [[ $DATABASE == postgres ]] && continue
    [[ $DATABASE == system ]] && continue

    TABLES=$(echo 'SHOW TABLES;' | kc --context staging --namespace my-namespace exec -i crdb-cockroachdb-0 -- ./cockroach sql --insecure --format raw --database "${DATABASE}" | grep -v '^#')

    for TABLE in ${TABLES}; do
        [[ $TABLE == schema_lock ]] && continue
        [[ $TABLE == schema_migrations ]] && continue

        echo "TRUNCATE TABLE ${TABLE} CASCADE;" | kc --context staging --namespace my-namespace exec -i crdb-cockroachdb-0 -- ./cockroach sql --insecure --format raw --database "${DATABASE}" --echo-sql
    done
done
```

**Comment by ajwerner** [comment]
Ah yeah truncate interacts poorly with `CHANGEFEED`. A `TRUNCATE` statement will kill the changefeed. Truncate is implemented in cockroach as drop the old table, create a new table with the same structure and same name. I will rework this issue to be about that bad interaction.

**Comment by fracasula** [comment]
> Ah yeah truncate interacts poorly with `CHANGEFEED`. A `TRUNCATE` statement will kill the changefeed. Truncate is implemented in cockroach as drop the old table, create a new table with the same structure and same name. I will rework this issue to be about that bad interaction.

Thanks for the insights @ajwerner. Any suggestions on how we could make it work for now? We tried stopping and restarting the changefeed of course but it keeps on dying.

**Comment by ajwerner** [comment]
What is your use-case that you keep truncating the table? Is there a way to instead delete everything from the table?

**Comment by fracasula** [comment]
> What is your use-case that you keep truncating the table? Is there a way to instead delete everything from the table?

Now that we know that `TRUNCATE TABLE` has issues we'll definitely try to avoid it and work around the problem (e.g. use something else). My question is about how we recover from the current situation given that the changefeed keeps on dying due to the old `TRUNCATE`. Do we have to create a whole new table and migrate all the data - that was written in the old one after the `TRUNCATE` - into the new one?

**Comment by ajwerner** [comment]
Hmm there may be a deeper problem at play here. What happens when you just select from that table? Does it work?

Perhaps this is related to https://github.com/cockroachdb/cockroach/issues/50587

**Comment by fracasula** [comment]
> Hmm there may be a deeper problem at play here. What happens when you just select from that table? Does it work?
> 
> Perhaps this is related to #50587

Yes, it's the first thing I tried just to see if the table may have gotten corrupted or something. So yeah, selecting works fine.

**Comment by ajwerner** [comment]
Is this testing data or production data? Would you be willing to collect a debug zip and share it with me (potentially out-of-band)? I'd like to help you get to the bottom of this.

**Comment by fracasula** [comment]
> Is this testing data or production data? Would you be willing to collect a debug zip and share it with me (potentially out-of-band)? I'd like to help you get to the bottom of this.

It's in our staging environment, haven't touched it since then to see if we could find a way to recover from this in case it were to happen in production so yeah, I'm more than willing to collect a debug zip and share it privately :+1: 

How do I collect it and where do I send it @ajwerner? Thanks!

**Comment by ajwerner** [comment]
https://www.cockroachlabs.com/docs/stable/cockroach-debug-zip.html.

I’m ajwerner@cockroachlabs.com if you want to use google drive. If that’s not available to you I can figure out how to give you an upload link using our customer support portal.

**Comment by miretskiy** [comment]
@ajwerner Did you receive debug.zip? Any updates on this issue?

**Comment by fracasula** [comment]
@ajwerner any progress on this? It's been more than a year. On staging we're now running `v21.1.10` but for that database we still get the usual error:

```json
{"time":"2021-11-02T13:46:03.047809982Z","level":"error","severity":"ERROR","message":"Feed error","svc":"cloud-crdb-cdc-streamer-service-0-5ccd5987d4-w4wqf","http-port":8082,"db-name":"spaceroom","dsn":"postgres://root@crdb-cockroachdb-public.infra:26257/spaceroom?sslmode=disable","blacklisted-tables":"schema_lock","gcp-project-id":"netdata-cloud-stg-200202","gcp-credentials-file":"/secrets/service-account.json","feed-max-buffer":1000,"feed-max-delay":5,"handler-max-delay":60,"table-monitor-interval":60,"resolved-interval":300,"error":"could not get row: pq: descriptor not found"}
```

Is there really no possible way to just tell the CDC to reset or something without having to recreate the whole database from scratch?

**Comment by ajwerner** [comment]
I'm so sorry I let this sit. Did you ever try upgrading? I never really got around to analyzing that zip in any depth. My guess is that one of those tables is somehow busted. I imagine you've never been able to recreate this. Did you attempt to just rename the tables and move the data to new tables? We've fixed lots of bugs in the interceding two years.

**Comment by ajwerner** [comment]
I'm inclined to close this now as stale. I really am sorry for how I handled it.
