### ISSUE TITLE
cli: move node cmds to gRPC

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#5163]
The `--http-port` flag is required on `start` to define the address and port for http requests from the admin ui. Currently, it's also required on `quit`. @petermattis suggested it doesn't need to be.

**Comment by mberhault** [comment]
sure it does. that's how `quit` works, it hits the `/quit` endpoint on a given node.
technically, the one that's not required there is `--port`

**Comment by tamird** [comment]
Can you help me understand this issue? The `--http-port` has a default and so is optoinal for both `start` and `quit`.

**Comment by petermattis** [comment]
I was thinking the admin endpoints could communicate over gRPC now that the grpc-gateway stuff is present. Somewhat irritating to have some client commands communicate over the http-port while others communicate over the grpc port.

**Comment by tamird** [comment]
OK. That's not a flags issue.

**Comment by jseldess** [comment]
Well, would that mean removing the `--http-port` flag and using `--port` instead?

**Comment by mberhault** [comment]
@petermattis: I'm all for it, I like having `http-port` be purely for the admin UI (although we may still want a /quit endpoint there to hit from the admin UI)
However, this is not the case right now.

**Comment by tamird** [comment]
https://github.com/cockroachdb/cockroach/blob/1a5f743/server/admin.go#L133

**Comment by mberhault** [comment]
I think we'll still need the `http` ones regardless, unless the admin UI can talk grpc.

**Comment by petermattis** [comment]
@tamird Understood. That TODO shouldn't be difficult.

@mberhault With grpc-gateway, there would still be an http `/quit` endpoint, but you would also be able to access it via grpc.

**Comment by mberhault** [comment]
@petermattis got it. Once that's in place, then yes, I think it would make sense for all commands to use the grpc port.

**Comment by tamird** [comment]
Note that the node commands also use the http port. I believe that can be addressed entirely on the client side.

**Comment by jseldess** [comment]
One other slight change to add to this issue: If I understand this right, the help text for `--http-port` should be changed from "The host:port to bind for HTTP requests." to "The port to bind for HTTP requests".

**Comment by tamird** [comment]
I misspoke - node commands also do not support grpc currently.

**Comment by tamird** [comment]
@jseldess 5165

**Comment by jseldess** [comment]
@tamird, @mberhault, @petermattis, is there any reason to leave this issue open? Or maybe it needs to be renamed?

**Comment by petermattis** [comment]
@jseldess The issue title seems appropriate right now. We should move the quit and health endpoints to gRPC. This probably won't happen before beta, but that's ok.

**Comment by jseldess** [comment]
@petermattis, Tamir changed it following that last comment of mine.

**Comment by tamird** [comment]
Closed by #6806.

**Comment by jseldess** [comment]
Docs updated with https://github.com/cockroachdb/docs/pull/337
