### ISSUE TITLE
*: improve issue assignment process

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#51653]
We currently have facilities baked in to auto-assign roachtest failures based on recent commit history around the surrounding text of the roachtest/roachprod. Given @andreimatei's not-so-recent refactor of roachprod/roachtest, for all KV-issues (and beyond) they get [auto assigned to him](https://github.com/cockroachdb/cockroach/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+assignee%3Aandreimatei). For now I'm just going to strip away the auto-assignment altogether, but it'd be nice if we had a more structured way to funnel in auto-filed issues into specific teams. We have some semblance of roachtest ownership, but at first glance it doesn't seem possible to auto-route issues to specific projects through the github API.

Jira issue: CRDB-4019

**Comment by irfansharif** [comment]
> but at first glance it doesn't seem possible to auto-route issues to specific projects through the github API.

Woops, I was wrong, it's possible. https://developer.github.com/v3/projects/cards/#create-a-project-card. https://github.com/google/go-github/blob/e881974953e6ab6d1a6a1610e98ed6401a3aa1ba/github/projects.go#L382-L385

**Comment by otan** [comment]
Note we do this with blathers: https://github.com/cockroachlabs/blathers-bot/blob/master/github_issue.go#L168

**Comment by otan** [comment]
(I should probably try put blathers in `pkg/internal`

**Comment by jordanlewis** [comment]
I added a commit to Irfan's PR to do this. It relies on hardcoded column ids 😄

**Comment by irfansharif** [comment]
The changes to roachprod tests were done in #51660, the rest of it should be covered by whatever #52053 ends up looking like.
