### ISSUE TITLE
IMPORT MYSQLDUMP doesn't like all-zeroes date format

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/cockroach#51654]
It looks like it's valid for a mysql dump to contain timestamp values with zeroes in every field.  This is not a valid value in our SQL dialect and the import will fail.  It can be worked around with a simple find-and-replace to replace the day and year with `1970-01-01`.

```
  `foobar` timestamp(3) NOT NULL DEFAULT '0000-00-00 00:00:00.000',
```

Epic CRDB-8825

Jira issue: CRDB-4018

**Comment by dikshant** [comment]
With IMPORT MYSQLDUMP being deprecated: #93660 and [Schema Conversion Tool](https://www.cockroachlabs.com/docs/cockroachcloud/migrations-page) being better for schema migrations this is no longer needed and can now be closed.
