### ISSUE TITLE
IMPORT MYSQLDUMP doesn't recreate views

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/cockroach#51651]
The dump format wraps the view operations in minimum-version comments like the following.  These don't appear to be processed by `IMPORT MYSQLDUMP`.

```
/*!50001 DROP VIEW IF EXISTS `foobar`*/;
SET @saved_cs_client     = @@character_set_client;
SET character_set_client = utf8;
/*!50001 CREATE VIEW `foobar` AS SELECT
  .....
 1 AS `xyzzy`*/;
```

Epic CRDB-8825

Jira issue: CRDB-4021

**Comment by dikshant** [comment]
With IMPORT MYSQLDUMP being deprecated: https://github.com/cockroachdb/cockroach/issues/93660 and [Schema Conversion Tool](https://www.cockroachlabs.com/docs/cockroachcloud/migrations-page) being better for schema migrations this is no longer needed and can now be closed.
