### ISSUE TITLE
cli: Error message for missing certs flags is confusing / poor

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#5179]
Running a fresh cluster with `cockroach start`:

```
$ ./cockroach start
Error: failed to start Cockroach server: .../cockroach/base/context.go:152: --insecure=false, but --certs is empty. We need a certs directory
```

The message says "--certs is empty" and then "we need a directory". This suggest using `--certs <dir>` where `<dir>` is the location of the various certificates. However when the user does so they get:

```
$ ./cockroach start --certs certs
Error: unknown flag: --certs
```

This is unfortunate and a poor first time experience.

Suggested fix:

1. Explain better using e.g. "server is starting up in secure mode (--insecure=false) but no certificate details were provided  - use --help for details"
2. provide an example command-line in the --help text.

**Comment by knz** [comment]
Also the "Example" command line at the start of --help is wrong; it shows `--certs` but this flag doesn't exist any more.

**Comment by mberhault** [comment]
usage mention of `--certs` removal was just merged. Still have a few things here and there that need fixing, I'm going through them one by one.
