### ISSUE TITLE
importccl: TestImportWorkerFailure is skipped

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#51793]
As of 10/31/19, 8b2a1fd: `	t.Skip("flaky due to undetected kinds of failures when the node is shutdown")`

**Comment by adityamaru** [comment]
This is no longer skipped - https://github.com/cockroachdb/cockroach/blob/04c6a251b12e72168b79f9e06d3e8206f6665424/pkg/ccl/importccl/import_stmt_test.go#L4889.
