### ISSUE TITLE
lease: TestLeaseAcquireAndReleaseConcurrencly is skipped

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#51798]
As of 12/1/17 (374413f): 

```
	t.Skip("fails in the presence of migrations requiring backfill, but cannot import sqlmigrations")
```

Jira issue: CRDB-4011

**Comment by andreimatei** [comment]
Why was this closed? The test is still skipped and references this issue: https://github.com/cockroachdb/cockroach/blob/2675c7c0481bb33eb9f43f1c2b52c152fca3ae2d/pkg/sql/catalog/lease/lease_internal_test.go#L836

The code says:
```
	skip.WithIssue(t, 51798, "fails in the presence of migrations requiring backfill, "+
		"but cannot import startupmigrations")
```
Migrations requiring backfill in the way that this test means are gone. The startupmigrations package is also about to be gone. But the test crashes if unskipped, so it must have rotted somehow.

**Comment by andreimatei** [comment]
cc @ajwerner
