### ISSUE TITLE
rpc: TestGRPCKeepaliveFailureFailsInflightRPCs is skipped

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#51800]
As of 7/24/19 (03aac64): 

```
	t.Skip("Takes too long given https://github.com/grpc/grpc-go/pull/2642")
```

@ajwerner what team should this live on?

Jira issue: CRDB-4010

**Comment by spaskob** [comment]
Ping @ajwerner please to a project tracker.

**Comment by nvanbenschoten** [comment]
What should we do with this test? It doesn't look like the [`KeepaliveMinPingTime` of 10s](https://github.com/grpc/grpc-go/blob/c93e472777b9d2963eff865ff4ee9f0895876b43/internal/internal.go#L38-L40) is going to change any time soon, and there's no clear way to circumvent [the limit enforcement](https://github.com/grpc/grpc-go/blob/c93e472777b9d2963eff865ff4ee9f0895876b43/dialoptions.go#L437-L440).

We are missing a fair bit of test coverage with this test being skipped, as it is packing 13 subtests exercising our gRPC configuration's behavior under different forms of network partitions into this 21 seconds. At this point, should we just unskip the test and pay the test latency? We can continue to `skip.UnderShort(t)`.

**Comment by andrewbaptist** [comment]
I'm looking through skipped tests and noticed this test. This would be good for stressing some of the recent changes made to rpc/context. I'd like to see if we can unskip it at least `UnderShort`. Do you remember any context about why we didn't do that?
