### ISSUE TITLE
cli: Suprising / confusing handling of command-line certs flags

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#5181]
Following up on #5179, trying the following:

```
 ./cockroach start  --verbosity 1 --ca-cert=certs/ca.crt --cert=certs/node.server.crt
```

This fails with:
```
Error: failed to start Cockroach server: .../cockroach/base/context.go:149: error setting up client TLS config: open : no such file or directory
```

Note how the file name in the error message is missing; and so is any indication as to why the command line was wrong.

(nb: --help only suggests using --ca-cert and --cert).

**Comment by mberhault** [comment]
`--key` is also needed. I'm going through and fixing up docs/error messages.

**Comment by mberhault** [comment]
I believe this is done.
