### ISSUE TITLE
importccl: TestImportData is skipped

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#51811]
As of 8/23/19 (05dbe09): `	t.Skipf("failing on teamcity with testrace")`

Note that this is unconditionally skipped, not just skipped under testrace, despite what the message says.

**Comment by otan** [comment]
i tried making this non-testrace only, but a lot of tests are failing.

**Comment by otan** [comment]
This has missed a regression: https://github.com/cockroachdb/cockroach/pull/53807

**Comment by otan** [comment]
Two regressions: #53809

**Comment by pbardea** [comment]
Planning on tackling the rest of the ones here not unskipped by https://github.com/cockroachdb/cockroach/pull/53808 this aft.
