### ISSUE TITLE
The README example about certificates doesn't work any more

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#5182]
The commands to initialize certificates listed in https://github.com/cockroachdb/cockroach#running-a-multi-node-cluster do not work any more:

```
$ ./cockroach cert create-ca
...
Error: missing or invalid parameters
$ ./cockroach cert create-node ...
...
Error: missing or invalid parameters
$ ./cockroach cert create-client root
...
Error: missing or invalid parameters
```

**Comment by developerworks** [comment]
CA create command in the docs show errors like this:

```
Error: missing or invalid parameters
Failed running "cert"
```

I create certificates and keys with the following commands, i down known if it's correct ?
```
mkdir cert
./cockroach cert create-ca --ca-cert=./cert/ca.cert --ca-key=./cert/ca.key
./cockroach cert create-node --ca-cert=./cert/ca.cert --ca-key=./cert/ca.key --cert=./cert/node.server.crt --key=./cert/node.server.key localhost
./cockroach cert create-client --ca-cert=./cert/ca.cert --ca-key=./cert/ca.key --cert=./cert/node.client.crt --key=./cert/node.client.key root
```

**Comment by mberhault** [comment]
These just changed a day ago, I just need to clarify the README and update the docs (and a few error messages here and there).

You almost had it to create certs. Specifically, the `create-client` probably shouldn't use `node` in the filename since the cert being generated is for `root`. But since you're providing the filenames at every step, you can name them anything you like.

So here's an example of how to create CA/node/user certs and use them:
```
$ ./cockroach cert create-ca --ca-cert=ca.cert --ca-key=ca.key
$ ./cockroach cert create-node --ca-cert=ca.cert --ca-key=ca.key --cert=node.crt --key=node.key localhost
$ ./cockroach cert create-client --ca-cert=ca.crt --ca-key=ca.key --cert=root.crt --key=root.key
# Start the server
$ ./cockroach start <standard options> --ca-cert=ca.crt --cert=node.crt --key=node.key
# Talk to the server as root
$ ./cockroach sql <standard options> --user=root --cert=root.crt --key=root.key
```

**Comment by mberhault** [comment]
@jseldess: should we drop that section of the README and instead point to the actual docs?

**Comment by jseldess** [comment]
@mberhault, I have an issue to refresh the entire readme, but I'm not going to get to that in the next few days. Above, and in another ticket, you mention refreshing the readme. Are you doing that now? If not, I'm happy to.

**Comment by petermattis** [comment]
@mberhault, @jseldess I think we should massively trim down the README and use it for a brief overview of cockroach and point to the docs regarding installation and basic usage. Let's touch base about this next week.

**Comment by mberhault** [comment]
I concur. The issue I mentioned the README in was to fix up the certs-related deployment.
Since we have detailed instructions in the docs for those, the README should just point to that part.
eg: I would imagine some README sections to just links to `install cockroach`, `deploy cockroach`, etc..

**Comment by jseldess** [comment]
Readme has been cleaned up.
