### ISSUE TITLE
backupccl: schedule status, jobs for specific schedule's status, etc.

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#51850]
A user who sets up a schedule needs to be able to inspect, and debug, the status of the schedule and of the jobs that the schedule kicked off. 

** Deliverables **
- Reference schedule by name or by ID
- ability to run `SHOW` type commands to see schedule status, and of jobs associated with that schedule
- Relevant logs / status indicators to help user triage any issues with the schedule (why skipped? why failed? when paused?)

** Future scope **
- Admin UI pages to see the same information

**Comment by miretskiy** [comment]
Going to close this issue for now; Future work can be handled w/ future feature requests.
