### ISSUE TITLE
backupccl: don't fail if schema relations in a different database are corrupt

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#51866]
**Describe the problem**

We've recently seen that certain bugs can leave orphaned tables or corrupted descriptors (https://github.com/cockroachdb/cockroach/issues/50997 as an example). This sort of corruption proves to be rather problematic for backups. Backups perform their own planning and set up a complete view of descriptors and their relationships. This can lead to errors that look like:

```
ERROR: table "..." has unknown ParentID 666
```

Ideally, backups would only fail if the corrupted descriptors were in the database being backed up. Backups are a key part of maintaining a production environment. The risk of having a bug which impacts a testing database prevent backups of a production database seems quite high and has occurred in practice. 

Epic CRDB-8816

Jira issue: CRDB-3998

**Comment by dt** [comment]
> Ideally, backups would only fail if the corrupted descriptors were in the database being backed up. 

I think it is unlikely that we'll make a change to do this any time soon for a few reasons. One is that databases aren't containment in cockroach, so we still need to find related descriptors in other DBs in some cases. In theory we could chase pointers and then only fail if the built-closure contained anything invalid, but in fact we actually need to load *all* descriptors over the backup time-span (for revision history) to see if modified descs have a parent ID in the set of DBs we're backing up. Thus we _rely_ on the the parent ID of every desc being correct -- an incorrect ID would mean we cannot be sure we're actually backing up the right things.
