### ISSUE TITLE
sql: no spans generated for filters with OR

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#5189]
We currently don't generate any spans if the filter is a disjunction, e.g. `WHERE a < 5 OR a > 10`

The current code can be used to generate constrains for each OR branch; we can generate separate spans for each branch and then merge them.

Targeting beta for now; this can be deferred if need be.

**Comment by petermattis** [comment]
I thought there was an existing issue for this enhancement, but I can't find it now. We do have a `TODO` in the code about this: https://github.com/cockroachdb/cockroach/blob/master/sql/select.go#L724

I haven't thought about this in a while, but I recall thinking this was complex to do. I'd defer this until after beta.

**Comment by RaduBerinde** [comment]
I see. That TODO talks about performing index selection independently for each disjunct which sounds quite complex.

What I had in mind (at least in the short term) was simpler - still consider one index at a time and generate the constraints for all disjuncts for that index. Later generate all the span sets (one for each disjunct) and merge them. Of course, if one disjunct doesn't result in any constraints that "kills" all constraints so it won't help for things like `a > 1 OR b > 1`. But it would work for things like `a < 5 OR a > 10` or `(a >= 2 AND a <= 5) OR (a >= 10 AND a <= 20)`

Maybe I'm missing something - I will try to take a closer look and if it seems doable I can work on it in the background.

**Comment by petermattis** [comment]
You've had your nose in this code more recently than I have, so I'll defer to your judgement.
