### ISSUE TITLE
ui: "Logs" link in UI doesn't work

### ISSUE THREAD

**Issue by alex** [cockroachdb/cockroach#5195]
Link is in the bottom right:

![screen shot 2016-03-12 at 12 12 10 pm](https://cloud.githubusercontent.com/assets/772/13724195/b0bf4750-e84b-11e5-802d-7f87550dc0b5.png)

Clicking that link takes me to the "Home" cluster page.

**Comment by maxlang** [comment]
Should be fixed via #4975

**Comment by Linicks** [comment]
@maxlang 

In build:

---------------------------

Build Vers:  go1.6
Build Tag:   alpha.v1-1501-g1a17919
Build Time:  2016/03/28 22:13:38

-----------------------------

The logs link in the /#/nodes/overview list doesn't point to the nodes log, but to the cluster overview. Additionally, once I get to a nodes log UI  (/#/nodes/2/logs) and select the severity drop down box, it indicates the number of entries, but doesn't reliably list them.  Some times it will show the entries, and other times it will not.  The version of Chrome that I'm using is (49.0.2623.110 (64-bit))
 
-- Nick
