### ISSUE TITLE
webui: expose metrics for reads from cache

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#51961]
In this [issue](https://github.com/timveil-cockroach/kubernetes-examples/issues/3) it was observed that we don't expose metrics for the caching layer. This can be problematic as sometimes reads are served from the "cache" and do not hit the underlying disk. We should improve the metrics/UI to surface cache interactions to the end user.

Jira issue: CRDB-3994

**Comment by petermattis** [comment]
Which caching layer are you referring to? We have metrics for `rocksdb.block.cache.{hits,misses}`, though they aren't currently exposed on any Admin UI dashboard.

**Comment by awoods187** [comment]
That may be sufficient. I filed this ticket on behalf of @timveil so perhaps he can weigh in more on what he'd like to see.
