### ISSUE TITLE
support Kafka message format version 0.10.0

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#51998]
**Is your feature request related to a problem? Please describe.**

Trying to change the Kafka consumer offset using [`KafkaConsumer.offsetsForTimes(Map<TopicPartition,Long> timestampsToSearch)`](
https://kafka.apache.org/25/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#offsetsForTimes-java.util.Map-) doesn't work because the message format version published by CRDB is 0.8.2, as of CRDB v20.1.2.

> If the message format version in a partition is before 0.10.0, i.e. the messages do not have timestamps, null will be returned for that partition.

**Additional context**

It appears that CRDB using the samara library and does not set the Kafka version.
https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/changefeedccl/sink.go#L337-L415

If the version is not set, samara defaults to 0.8.2:
https://github.com/Shopify/sarama/blob/master/config.go#L489
https://github.com/Shopify/sarama/blob/master/utils.go#L191

gz#5924

Epic CRDB-8665

**Comment by mwang1026** [comment]
This came a bit late so don't expect it'll make our next release (v20.2) but we'll consider it for our next release as we go through planning

**Comment by miretskiy** [comment]
@stevendanna wasn't this one fixed?

**Comment by stevendanna** [comment]
Yes, we now default to a newer kafka version (1.0), with the option to change that default via sink configuration (https://github.com/cockroachdb/cockroach/pull/66314)
