### ISSUE TITLE
metrics: Expose active sessions metric

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#52005]
It would be useful to expose a new metric in the Prometheus endpoint that tracks the number of currently active SQL sessions for troubleshooting and alerting purposes.

**Comment by glennfawcett** [comment]
I couldn't agree more... It would also be helpful to add some categorization by database and/or "application_name" like in the statements page.  This would allow users look at the database name or specify the "application_name" on the connect string to filter out sessions by **micro-services**.

**Comment by fabiog1901** [comment]
**Zendesk**: [6072](https://cockroachdb.zendesk.com/agent/tickets/6072)

**Comment by jordanlewis** [comment]
We're discussing this with @a-entin.

There are 2 current metrics, and 1 new one that are related.

Current:
`sql.distsql.queries.active` is a gauge of all currently active SQL queries
`sql.conns` is a gauge of all open SQL connections

New (#57477):
`sql.txns.active` is a gauge of all currently open SQL transactions

Is this sufficient for your needs? If so, I'll close this one.

**Comment by a-entin** [comment]
`sql.txns.active` is the best proxy gauging the level of the cluster utilization by users. It is also actionable, enabling a user to reconcile workload vs cluster size (increase/decrease one or another). Having this gives means to stop cluster overloads we see in customer environments. It's critically important and urgent to have this metric for some current customer situations.

I understand this metric shows user transactions, which is perfect. For completeness, it would also be very helpful to also see an internal transaction counter. Not sure if this should be tracked separately, a very nice to have tho not critical.

I totally see and support @glennfawcett 's point re filtering by app, yet it's a separate "very nice to have" and hope it doesn't delay having this barebone counter in the product asap to help stop overload situations we need means to resolve.
