### ISSUE TITLE
geoserver: support geoserver

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#52013]
Known blockers:

* [x] Bounding Box comparisons
* [ ] ST_Simplify (#49037)
* [x] ST_AsTWKB (#48886)
* [x] ST_EstimatedExtent

**Comment by keith-mcclellan** [comment]
As {customer_redacted} continues to review the new geospatial capabilities developed by Cockroach Labs, our testing teams have noted a common theme regarding the need for the Cockroach database to operate with GeoServer.
Having the database utilize and operate with GeoServer will enable {customer_redacted} to find the desired use case scenarios within our {customer_redacted} more easily.
A more detailed description of GeoServer and our test team’s comments are listed below:
GeoServer and CockroachDB
GeoServer is an open-source program that, given a connection to a spatial data store (i.e., PostGIS), can process data and then serve the data using OGC services WMS.i, WFSii, WCSiii and with extension WMTSiv, and WPSv. These OGC services are used by both Web Mapping and GIS systems. NGA uses WMS, WFS, and WCS constantly. For example, {customer_redacted}'s web ELT application uses WMS and WFS services as served by GeoServer. GIS systems like ArcGIS and QGIS also leverage WMS, WMTS, WFS, and WCS.
CockroachDB, with its spatial functions and PostgreSQL compatibility, would be a natural connection to GeoServer as a PostGIS database. However, currently, CockroachDB has not implemented some of the PostGIS functions needed to allow for GeoServer compatibility. {customer_redacted} would find CockroachDB much more helpful if it used GeoServer to provide these OGC services. {customer_redacted} asks that Cockroach Labs make CockroachDB compatible with GeoServer for WMS, WFS, and WCS.
cc: @awoods187 @mgoddard

**Comment by otan** [comment]
this will work on v21.1.1 (note not v21.1.0).
