### ISSUE TITLE
opt: add normalization rule to convert ST_Distance(...) < x to ST_DWithin(...)

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#52028]
Queries that use `ST_DWithin` in the `WHERE` or `ON` clause can take advantage of an inverted index for acceleration, while  queries that use `ST_Distance` cannot. However, in cases where `ST_Distance` is used as part of an inequality condition, it should be possible to convert it to an equivalent condition with `ST_DWithin`. We should create a normalization rule to perform this conversion so that such queries can take advantage of index acceleration if a suitable inverted index is available.

**Comment by otan** [comment]
heads up that `ST_Distance(a, b) <= x` == `ST_DWithin(a, b, x)`, but `ST_Distance(a, b) < x` == `ST_DWithin(a, b, x-SmallestNonzeroFloat64)`, most likely.

**Comment by DrewKimball** [comment]
Would we want to perform this transformation in all cases, or only in cases where an inverted index scan might be possible? I'm asking because it looks to me like in order for an inverted index scan to be generated, one of the st_distance arguments must be a constant, and the value on the right side of the <= comparison must also be constant.

**Comment by otan** [comment]
i think this is applicable in all cases

**Comment by DrewKimball** [comment]
Doing something like `x-SmallestNonzeroFloat64` runs into a problem where it gets simplified to just `x`. One alternative could be to make the replacement: `ST_Distance(a, b) < x` == `ST_DWithin(a, b, x) AND ST_DISTANCE(a, b) != x`. The `ST_DWithin` function could then be used to generate an inverted index scan, and the other conjunct would remove the extra rows.

**Comment by otan** [comment]
We want to avoid calculating ST_Distance as it is more expensive than it's counterpart ST_DWithin which has early exit functionality. Why does it get simplified to just x?

**Comment by DrewKimball** [comment]
It wouldn't happen if `x` was a variable, but if `x` is a constant, constant folding rules fire and we lose precision.

**Comment by DrewKimball** [comment]
How expensive is `st_equals`?

**Comment by DrewKimball** [comment]
Easiest thing for that case might be to add another function, `ST_DWithinExclusive` (or something) with the same early-exit behavior as `ST_DWithin` but which is equivalent to `ST_Distance(a, b) < x`.

**Comment by otan** [comment]
> but if x is a constant, constant folding rules fire and we lose precision

it wouldn't fold, say, 100 to 99.999999?

> Easiest thing for that case might be to add another function, ST_DWithinExclusive (or something) with the same early-exit behavior as ST_DWithin but which is equivalent to ST_Distance(a, b) < x.

works for me if you're willing

**Comment by DrewKimball** [comment]
Unfortunately not. There's also the problem of what to do if `x` is already the minimum value. Yeah, I'll try adding a new function.
