### ISSUE TITLE
sql: unsupported binary operator: <string> -> <string> (desired <jsonb>) regression in 20.2 alpha 2

### ISSUE THREAD

**Issue by timgraham** [cockroachdb/cockroach#52043]
**Describe the problem**

A query in Django's test suite crashes in CockroachDB 20.2 alpha 2. It worked in 20.2 alpha 1 and earlier versions.

**To Reproduce**

In CockroachDB 20.2 alpha 1 and earlier:

```sql
CREATE TABLE jsontest (value jsonb);
INSERT INTO jsontest VALUES ('{"foo": "bar"}');
SELECT * FROM jsontest WHERE ("value" -> 'foo') = (('{"x": "bar"}') -> 'x');
      value
------------------
  {"foo": "bar"}
(1 row)
```

In 20.2 alpha 2, the select query crashes:
```
ERROR: unsupported binary operator: <string> -> <string> (desired <jsonb>)
SQLSTATE: 22023
```

**Environment:**
 - CockroachDB version: 20.2 alpha 2

**Comment by solongordon** [comment]
This bit seems to be the problem:
```
root@127.0.0.1:61783/movr> select ('{"x": "bar"}') -> 'x';
ERROR: unsupported binary operator: <string> -> <string>
```
Works without the parens:
```
root@127.0.0.1:61783/movr> select '{"x": "bar"}' -> 'x';
  ?column?
------------
  "bar"
```
@otan I think you have been in this general area recently. Do you have any insight here?

**Comment by otan** [comment]
Not anything that jumps out unfortunately, probably needs a bisect to find the underlying issue ...

**Comment by otan** [comment]
maybe something also disappeared with optimizer folding? hmm

**Comment by otan** [comment]
caused by d182c734e727e1a8deca606ebb1375c3c942145e, cc @RaduBerinde

**Comment by solongordon** [comment]
Thanks for tracking that down! Sending to Optimizer triage.

**Comment by RaduBerinde** [comment]
This is a problem with our typing system. We don't support an implicit string-to-jsonb cast. We don't even seem to try to type-check the first argument as a Jsonb..

We support directly interpreting the string constant literal as a jsonb, which is why the non-paren case works. I will try to add something for this case, but it will be a crutch..

**Comment by otan** [comment]
https://github.com/cockroachdb/cockroach/pull/45199 one day.....
did the folding thing used to do something that make this work?

**Comment by RaduBerinde** [comment]
Yeah, the folding happened before type-checking and effectively removed the ParenExpr, essentially converting in the other case (where the special constant literal logic kicks in).

I found a way to improve the overload heuristics to fix this particular case.
