### ISSUE TITLE
sql: improve debugging information on failed queries

### ISSUE THREAD

**Issue by chriscasano** [cockroachdb/cockroach#52051]
**Is your feature request related to a problem? Please describe.**
The idea is to provide the user more insight into why their query is failing at it's being developed.  Many times, a query can have multiple joins, predicates, functions, etc and the Error codes are not enough for describing where the issue in the query resides.  It would be nice to return to the user which line number and offset where the issue occured, as well as and tables / field that are involved in the failure.

**Describe the solution you'd like**

For an example... this is an actual error code:

ERROR: unsupported comparison operator: <int2> = <bool>
SQLSTATE: 22023

It would be nice to see something more like this:

ERROR: unsupported comparison operator: <int2> = <bool>
SQLSTATE: 22023
----
Line 5, Offset 13
"where a.col1 = b.col2"
                         ^
This would at least instruct the developer where to look for the problem.  If there are multiple joins in a query, the generic error message here doesn't help a ton because you have to now inspect alot of columns / data types to find the issue.

**Describe alternatives you've considered**
We don't necessarily need a stack trace here.  Just better information to direct the user to where the problem is.

**Additional context**
This is important for when developers are migrating applications and they need to rewrite the syntax of their queries.  This can take some time but if the error messaging was a little more descriptive, the migration process can become smoother for developers..

Jira issue: CRDB-3986

**Comment by solongordon** [comment]
Example PostgreSQL output for comparison:
```
solon=# select * from t where x = y;
ERROR:  operator does not exist: integer = text
LINE 1: select * from t where x = y;
                                ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
```

**Comment by solongordon** [comment]
This would be really helpful but a large project. We need more information at the AST level in order to trace errors back to the source.
