### ISSUE TITLE
kvserver: expose range-level information on contention

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#52073]
**Is your feature request related to a problem? Please describe.**

Issues involving contention today are notoriously difficult to debug. The addition of the statement bundle and `crdb_internal.cluster_transactions` in v20.1 have been immensely helpful but there's much more that we can do. One problem when contention arises is that it shows up in the statements page quite visibly as retries and high latency. A question which often arises is how is this contention spread over the cluster. 

**Describe the solution you'd like**
The proposal in this issue is to track per-range contention metrics. These metrics might track such things as:

* Number of intents requiring push
* Average number of waiters for these intents
* Maximum number of waiters
* Duration waiting
* Number of keys involved in contention
* Something about waiting at the txn_wait_queue

All of these we probably would want to collect over a trailing time window. Just determining what to collect isn't totally obvious.

The hope is that such information might be combined with statement stats to highlight, given a query plan, where contention might be taking place. This might allow us to visualize contention affecting a plan as well as contention spread over the cluster.

In terms of technical details, I envision that we'd track this similarly to how the load is tracked for the hot ranges; each replica maintains some stats and then in the server we iterate the ranges and collect those stats.

**Describe alternatives you've considered**
Another complementary approach which may be fruitful here is to gain further insights from the tracing platform we've built. Today's statement tracing infrastructure is good to grab a single trace of a statement. A more powerful tool might be to sample tracing random queries and maintain stats over those samples as well as some number of complete traces. In cases with contention it may be easy to pick out the interesting traces. Systems like LightStep try to keep a single sample for each bucket in the histogram. Something l like that, or perhaps 2-3 samples per a more coarse-grained bcuket might go a long way. 

**Additional context**

Contention fairness has improved dramatically in 20.1 relative to other releases. Perhaps the unfairness of the earlier versions in contended cases will become a less acute issue moving forward.

We probably want to also augment our regular metrics pertaining to contention. For example, a simple gauge of the number of keys which have waiters in the txn_wait_queue might itself have been helpful. I'm hopeful that if we build more fine-grained, replica-level metrics we'll be prodded into building timeseries metrics in aggregate too. 

Jira issue: CRDB-3983

**Comment by awoods187** [comment]
Is it difficult for us to collect these metrics? Could we do something simple and make them debug pages for 20.2?

**Comment by ajwerner** [comment]
Some are easier than others. I think we could ship some in 20.2. The raw metrics work feels like it could easily slip into an early stabilization period change. Aggregating ranges in a useful way to show contention on indexes affecting a table feels like a bit more of a lift given the UI work that would need to go into it. In short, I think it's quite reasonable to try to get some counters in the KV layer both at a replica level and at a store level into the contention going on.

I anticipate that they way these will be surfaced is in timeseries at the store level and in range reports at the replica level.

**Comment by lunevalex** [comment]
@jordanlewis @tbg how much of this done in 21.1 for tracing and contention tracking? Is this still relevant given that work?

**Comment by ajwerner** [comment]
I don't think any of this was done in 21.1 in the way this issue was asking for it. In 21.1 we added request level information about contention. i.e. each request gets to learn about what contention it encountered. The idea here was that the range would keep track of stats about this stuff in aggregate. This would enable creating views that show you, say, where in the keyspace you're experiencing a lot of contention.
