### ISSUE TITLE
sql: overloading in 2-part table/type names and cross-DB queries could cause unexpected changes in name resolution

### ISSUE THREAD

**Issue by lucy-zhang** [cockroachdb/cockroach#52070]
With the advent of user-defined schemas, suppose we have

* databases `foo`, `bar`,
* the schema `bar.foo`, and
* the table `foo.public.tbl`.

Then if we create the table `bar.foo.tbl`,  while connected to the database `bar`, the name `foo.tbl` in queries will now start being resolved to the new table `bar.foo.tbl` instead of the preexisting table `foo.public.tbl`.

It's hard to think of a case where it's desirable to cut over to an entirely new table with no guarantees about when any particular gateway node sees the change. We may want to detect cases like this when creating tables and types, and forbid them when `sql_safe_updates` is off.

Similar problems can happen when renaming and dropping tables and types as well as schemas. One difference in renaming and dropping, compared to creating descriptors in most cases, is that there's a draining names interval. During that interval, when trying and failing name resolution with the old name, we should return an error about the descriptor not existing instead of trying the schema name as a database name.

Epic: CRDB-2454

Jira issue: CRDB-3985

**Comment by ajwerner** [comment]
This has not proven to be a problem. Closing.
