### ISSUE TITLE
sql: Interval does not return correct year

### ISSUE THREAD

**Issue by chriscasano** [cockroachdb/cockroach#52135]
When running the interval function, the wrong year is return.  See example below where a 1 year interval returns 2 years.

root@:26257/defaultdb> select current_date, current_date() - INTERVAL ‘1-0 0 0:0:0’ YEAR as “1YrAgo”, current_date() - INTERVAL ‘1’ YEAR as “1YrAgo2";
        current_date        |          1YrAgo           |          1YrAgo2
----------------------------+---------------------------+----------------------------
  2020-07-30 00:00:00+00:00 | 2018-07-30 00:00:00+00:00 | 2018-07-30 00:00:00+00:00

This also occurs as well:

root@127.0.0.1:65028/defaultdb> select now() - '.6 years'::interval;
              ?column?
------------------------------------
  2018-12-24 13:36:26.664877+00:00

**Comment by otan** [comment]
This is broken here:

https://github.com/cockroachdb/cockroach/blob/master/pkg/util/duration/duration.go#L423

So it looks wrong for any dates >= 28th of each month:

```
root@127.0.0.1:62205/defaultdb> select '2020-07-28 00:00:00+00:00'::date - INTERVAL '1-0 0 0:0:0' YEAR;
          ?column?
-----------------------------
  2019-07-28 00:00:00+00:00
(1 row)

Time: 393µs

root@127.0.0.1:62205/defaultdb> select '2020-07-29 00:00:00+00:00'::date - INTERVAL '1-0 0 0:0:0' YEAR;
          ?column?
-----------------------------
  2018-07-30 00:00:00+00:00
(1 row)

Time: 369µs

root@127.0.0.1:62205/defaultdb> select '2020-07-30 00:00:00+00:00'::date - INTERVAL '1-0 0 0:0:0' YEAR;
          ?column?
-----------------------------
  2018-07-30 00:00:00+00:00
(1 row)

Time: 333µs
```

from:
https://github.com/otan-cockroach/cockroach/blob/713c52c20405057d931a8becef8e82f74286e817/pkg/sql/sem/tree/eval.go#L1074

I don't understand the logic here and not sure why `AddDate` won't work.

**Comment by jordanlewis** [comment]
`TimeOfDay.Add(d duration.Duration)` seems to also be broken - it adds `d.Nanos()` to a `TimeOfDay` without checking the duration's Days or Months? But maybe it's not the same issue.

**Comment by otan** [comment]
> it adds d.Nanos() to a TimeOfDay without checking the duration's Days or Months? But maybe it's not the same issue.

d.Nanos() is the non-day/month component of the date so it's ok. the root of the issue is more... Go just gotcha.
