### ISSUE TITLE
sql: temp table cleanup on shutdown has issues

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#52147]
Repro:

1. Start one-node cluster
2. In one window, run:

```
SET experimental_enable_temp_tables = 'on';
BEGIN;
create temporary table a (a int);
```
Now hit control c, terminating the connection

3. In another window, run anything that touches system.namespace and you'll get either deadlocks or very slow accesses:

```
root@:26257/defaultdb> show tables;
  schema_name | table_name | type
--------------+------------+--------
  public      | a          | table
(1 row)

Time: 9.176214s
```

The theoretical root cause (h.t. @ajwerner @andreimatei) is that the session cleanup happens inside of the user transaction, not outside of it.

**Comment by jordanlewis** [comment]
I tested moving the temp table cleanup after the txn shutdown and the issue resolved, so I'll just post a PR with this and we can debate further.

**Comment by andreimatei** [comment]
You did manage to produce a deadlock?

**Comment by jordanlewis** [comment]
@andreimatei not a deadlock, but very slow queries - look at the description, I put an exmaple.

**Comment by andreimatei** [comment]
Right, but I'd like to understand this slowness; is it the same as the deadlock we saw? I can't think of what would cause the 9s query. The theory was that we get a deadlock because deleting the table is waiting on the creating txn, and the waiting txn is waiting on the cleanup (the second part being invisible to the deadlock detector). But, surprisingly to me, you're not seeing the deadlock.

**Comment by jordanlewis** [comment]
Yeah, I don't know. Each query takes 9 seconds after I close the connection. It does not "reset" until the server is restarted, seemingly.

**Comment by ajwerner** [comment]
If you just do a select from the second connection it ends up being okay (for reason I don't think I understand but that's okay I guess). Here's a scenario that really creates a deadlock:


```sql
-- conn A
SET experimental_enable_temp_tables = 'on';
BEGIN;
CREATE TABLE bar();
CREATE TEMPORARY TABLE foo();
```
```sql
-- conn B
CREATE TABLE bar(); -- blocks
```
now disconnect `conn A` and `conn B` will block forever.

**Comment by ajwerner** [comment]
I don't think the contention point needs to be a table. I think that any write-write conflict between `conn A` and `conn B` will hit this. It's not totally clear to me why a write-read conflict is more okay.
