### ISSUE TITLE
opt: normalize LIKE 'forest%' to `x >= 'forest' AND x < 'foresu'`

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#52153]
Index constraint generation currently supports constraints from LIKE expressions, but the opt statistics code does not. A simple improvement would be to handle the case where the expression is exactly equivalent to a range of values.

Note that such a rule would need to handle escaping correctly (which the index constraints code currently does not, see #44123).

**Comment by xuhui-lu** [comment]
hey @RaduBerinde , is this ticket assigned? If not, can I take it? I am glad to do some work on it.

**Comment by RaduBerinde** [comment]
Sure, thanks!

**Comment by ipugh** [comment]
Hey @xuhui-lu are you still working on this? If not I'd like to give it a go.

**Comment by RaduBerinde** [comment]
Turns out there is not much benefit to this, we can create constraints from `LIKE` just the same.
