### ISSUE TITLE
Include the database name and schema name in node_statement_statistics and jobs tables.

### ISSUE THREAD

**Issue by pxlogan** [cockroachdb/cockroach#52185]
**Is your feature request related to a problem? Please describe.**
When querying the node statement statistics table on the crdb_internal schema its impossible to tell which database or schema the query was run against easily.  By adding the database and schema name to this table it would make it easier

**Describe the solution you'd like**
Addition of columns detailing the database and schema the query is running against

**Describe alternatives you've considered**
A very manual exercise that is not always correct

**Additional context**
Raised by a customer

gz#5970

Jira issue: CRDB-3974

**Comment by pxlogan** [comment]
Any update on the progress of this request?

**Comment by BramGruneir** [comment]
@thtruo This issue has kind of gotten lost, but should be about observeability.  Assigning to you for triage.

**Comment by thtruo** [comment]
cc @kevin-v-ngo as it relates to SQL Observability / SQL Queries since this request is about making changes to node_statement_statistics

I'll assign to you for triage. Let me know if this ownership makes sense!

**Comment by kevin-v-ngo** [comment]
The next release will include the database name. This is the default database specified when [connecting to cockroachdb](https://www.cockroachlabs.com/docs/v21.1/connection-parameters#connect-using-a-url). Here's the [change](https://github.com/cockroachdb/cockroach/pull/65782/files). 

@pxlogan, is this what you're looking for? As for schema, can you clarify the behavior you're looking for? If there is a query touching multiple schemas, what do you expect the behavior to be?

**Comment by pxlogan** [comment]
@kevin-v-ngo I dont think so, what I want in this probably displayed in either the first or second column is the name of the database in the cluster that the query was ran against.  So that users can see which database is the busiest.  This may not be the one they connect to necessarily.

**Comment by kevin-v-ngo** [comment]
Thanks. What about cross-database queries? For instance, a single query returning results from 2 databases. Which database do you expect to be displayed for the query?

**Comment by pxlogan** [comment]
@kevin-v-ngo an excellent question, I think if it is not possible to show multiple databases it should the database that the first table in the from clause of the query is located in.
