### ISSUE TITLE
webui: add a SESSIONS page

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#52193]
@jordanlewis came up with an excellent idea to add a sessions page. This page will show all active sessions and allow for filtering on session time, transaction time, query time, current memory usage, current active query, etc.

It may also allow for filtering but will most likely ship as an MVP with sorting only. This page will allow for linking to a sessions detail page with more information about a particular session. It will also link the current active query to its query fingerprint on the statements page.

Ideally, we would also allow users to cancel the session directly from this page. Barring that, they should be able to obtain the session id so that they can cancel it manually.

cc @Annebirzin for thinking on the design front

**Comment by awoods187** [comment]
Related to but separate from https://github.com/cockroachdb/cockroach/issues/46429

**Comment by Annebirzin** [comment]
I've added designs for the [sessions list page](https://www.figma.com/file/MoSPFkEyJfGipCmQvvLg1a/obsrv_admin-ui-query-performance?node-id=559%3A14386) and [sessions detail page](https://www.figma.com/file/MoSPFkEyJfGipCmQvvLg1a/obsrv_admin-ui-query-performance?node-id=568%3A16036) based on Jordan's prototype 

![Screen Shot 2020-07-31 at 2 04 45 PM](https://user-images.githubusercontent.com/51920721/89063823-df85bd00-d336-11ea-9fa0-8e7f6d194c60.png)

![Screen Shot 2020-07-31 at 2 04 17 PM](https://user-images.githubusercontent.com/51920721/89063836-e6accb00-d336-11ea-9d2b-550ae4f88833.png)

**Comment by jordanlewis** [comment]
Awesome! I will incorporate this into the prototype. I like the look of the detail page
