### ISSUE TITLE
Allow users to set locality hierarchy on Node list

### ISSUE THREAD

**Issue by Annebirzin** [cockroachdb/cockroach#52197]
**Problem**
On the node list, users cannot control which locality tier to group nodes by in the table hierarchy.

We originally defaulted to grouping by region ([#45041](https://github.com/cockroachdb/cockroach/pull/45041))

In issue [#44919](https://github.com/cockroachdb/cockroach/issues/44919) we updated the node hierarchy to display the lowest tier locality. 

Users want flexibility to be able to choose the locality level to group nodes.

**Possible solutions:**
- Include a dropdown above the node list that allows users to select which locality tier to group by (similar to the network latency page)

- Add a settings page to the admin ui to allow users to configure elements of the UI (ie. toggle the 'new release' widget or the 'release notes' widget, show nodes by 'X' locality tier etc.) 

**Customer notes:** 
Our customer wants to be able to group by region which is not their lowest level locality. 

Darin Peshev: `customer was trying to organize their cluster’s nodes to show grouped by region in the Nodes list in the UI. That would’ve been possible before when the grouping was based on region. After https://github.com/cockroachdb/cockroach/issues/44919 it seems the only option is the last tier from the locality. The locality is used by the allocator for placing replicas in the correct zones and placement groups so they are not very flexible. They did try to add a last tier in the locality that has what they want the grouping to be by but with the change that we did - we actually group by the full locality string and only show the last tier of it.`

customer:
`It looks like even if I set the last component of the --locality flag to be us-west-2a, I'm still seeing 6x rows, not 3x rows (i.e. I'm seeing two per AZ and not one row per AZ).`
![image-3](https://user-images.githubusercontent.com/51920721/89064822-af3f1e00-d338-11ea-87fd-88d475cbd85d.png)

customer:
`it'd be nice if there were a system catalog to configure the UI on some level
I want to disable the banner up top and set the key(s) to do the UX grouping by for localities`

Jira issue: CRDB-6309

**Comment by ddseanc** [comment]
> ```
> it'd be nice if there were a system catalog to configure the UI on some level I want to disable the banner up top and set the key(s) to do the UX grouping by for localities
> ```

This would be nice.  The UI is an important part of the crdb experience.  In an ideal world, there would be a cluster-wide set of defaults and a per-ROLE setting.  For example:

* Removing the email notification banner when you first log in: I don't need to see this for every cluster.
* Grouping of locality: this is a cluster-specific setting that everyone should see correctly

As time passes, I think there can/will be more of these and it would be convenient to have a single way to manage all of this over time.

```sql
SELECT * FROM pg_catalog.crdb_ui_settings;
```

**Comment by Annebirzin** [comment]
Following up on this issue, I've added wip designs for 
1. [group by any locality tier in the node list](https://www.figma.com/file/OzoUuhNk05nFuaZB6UNVBx/obsrv_admin-ui-node-list?node-id=315%3A5881)
2. [Admin UI settings](https://www.figma.com/file/OzoUuhNk05nFuaZB6UNVBx/obsrv_admin-ui-node-list?node-id=315%3A5886)

_screenshots_
![Screen Shot 2020-08-03 at 6 12 35 PM](https://user-images.githubusercontent.com/51920721/89338444-97360a00-d66a-11ea-9d4e-c4e35e528919.png)
![Screen Shot 2020-08-03 at 6 12 48 PM](https://user-images.githubusercontent.com/51920721/89338446-97cea080-d66a-11ea-8c3c-409350be7a98.png)

**Comment by andreimatei** [comment]
I couldn't find information on *why* we changed the grouping from the top tier locality to the bottom one. It seems like the wrong way to go to me...
In particular in 21.1 with regions being a first class concept, one definitely expects the regions to show up on this page. Look at how `cockroach demo --nodes=9 --global` looks - similarly named AZs are displayed multiple times for max confusion.

I'm slapping a release blocked on this, but feel free to remove if you don't agree.
