### ISSUE TITLE
Please allow deployment of cockroach with ACL through github

### ISSUE THREAD

**Issue by timcash** [cockroachdb/cockroach#52228]
Deployment of cockroach directly through github would save so much development and maintenance time. Integrate management of secret keys, access control, and connections to data pipeline components like Kafka, NATS.io as both sources and sinks. I would pay money for this service.

**Comment by jordanlewis** [comment]
Hi @timcash, what do you mean by deployment through GitHub? I'm not sure what that would look like. Can you point me to some examples of this in the wild?

In the meantime, please consider using Cockroach Cloud! https://cockroachlabs.cloud/signup
