### ISSUE TITLE
sql: set max statement time on a per query basis

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#52240]
We now have a statement_timeout and a idle_in_session_timeout (introduced in 20.2). In #5924 we plan to add a idle_in_transaction_session_timeout. We should also add a per-query timeout (instead of a session variable/cluster setting). This is analogous to an INDEX or JOIN hint in that we are instructing specific behavior for an individual query.

In [MariaDB](https://mariadb.com/kb/en/aborting-statements/), they offer this via `max_statement_time`
```SQL
SET STATEMENT max_statement_time=100 FOR 
  SELECT field1 FROM table_name ORDER BY field1;
```

I couldn't find an example in Postgres (I believe it only allows for the connection or session settings). 

Jira issue: CRDB-3972

**Comment by jordanlewis** [comment]
Thumbs down for making this a priority, if only because no existing Postgres driver will have built-in support for this syntax.

**Comment by vy-ton** [comment]
@rafiss fyi

**Comment by rafiss** [comment]
The PGJDBC `setQueryTimeout` method actually is just a client-side timeout. It starts a timer in the client, and after the time is elapsed, it issues a pgwire Cancel message (see #41335).

**Comment by jordanlewis** [comment]
Okay, so are we good to close this?

**Comment by awoods187** [comment]
No, I don't think so. We don't have this option available in all drivers.
