### ISSUE TITLE
sql: improve ENUM comparison error message

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#52297]
I was testing ENUMs from the [PG docs.](https://www.postgresql.org/docs/9.1/datatype-enum.html). It's important to note that you can't compare ENUMs but our error message looks like we don't support it.

In CRDB it looks like:
```SQL
root@127.0.0.1:51592/movr> INSERT INTO holidays(num_weeks,happiness) VALUES (2, 'sad');
ERROR: invalid input value for enum happiness: "sad"
SQLSTATE: 22P02
root@127.0.0.1:51592/movr> SELECT person.name, holidays.num_weeks FROM person, holidays
  WHERE person.current_mood = holidays.happiness;
ERROR: unsupported comparison operator: <mood> = <happiness>
SQLSTATE: 22023
```
In PG it looks like:
```SQL
SELECT person.name, holidays.num_weeks FROM person, holidays
  WHERE person.current_mood = holidays.happiness;
ERROR:  operator does not exist: mood = happiness
```

I think we should update our text because the error isn't unsupported but impossible to compare. Maybe something like: 
```ERROR: invalid comparison between operator <mood> = <happiness>. ENUM types are separate and cannot be compared```

**Comment by vy-ton** [comment]
In Postgres 12.3, I also get the following hint
```
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
```
