### ISSUE TITLE
sql: improve NOT NULL constraint violation message on insert

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#52299]
In MySQL you can insert ENUM data even if you don't specify not null:
```SQL
 CREATE TYPE priority AS ENUM ('Low', 'Medium', 'High');
 CREATE TABLE tickets (
    id INT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    priority PRIORITY NOT NULL
);
INSERT INTO tickets(id, title)
VALUES('3','Refresh the computer of Ms. Lily');
```
This isn't supported in PG but there is a nice error message with DETAIL:
```SQL
postgres-# VALUES('3','Refresh the computer of Ms. Lily');
ERROR:  null value in column "priority" violates not-null constraint
DETAIL:  Failing row contains (3, Refresh the computer of Ms. Lily, null).
```
In CRDB:
```
INSERT INTO tickets(id,title)
VALUES('3','Refresh the computer of Ms. Lily');
ERROR: null value in column "priority" violates not-null constraint
SQLSTATE: 23502
```
It'd be nice to add this DETAIL. 

Jira issue: CRDB-3967

**Comment by rohany** [comment]
I don't think this is really applicable to us (looks this is the MySQL syntax). As with any other column type, you need to provide a value for it in the insert if it is not null and doesn't have a default value.

**Comment by awoods187** [comment]
While it's true MySQL assumes a default value (and adds it if its not specified) that isn't really germane to our error message. I think we correctly don't follow MySQL (and instead follow PG). We both have the same error, however, PG has an extra detail that we don't support. This extra detail is nice and helps direct the user to the exact place the null occurs. It's also true that with any column type you need to provide a value and i'd support generalizing this accordingly to make it blindingly obvious and easy to find and fix the mistakenly null value.
