### ISSUE TITLE
sql: Show Index does not show implicit columns

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#5230]
It can get confusing which index will be selected for a given select because it is not always clear what implicit columns are included in an index. The SHOW INDEX command should identify implicit indexes on columns (preferably distinguished from explicit columns). Additionally, EXPLAIN SELECT should include these implicit indexes on its pretty printed spans.

**Comment by tamird** [comment]
Related #4191, #3548.

**Comment by knz** [comment]
Could you suggest an example output you would like to see for this?

**Comment by nvanbenschoten** [comment]
#12801 is what I had in mind. We already output a new row for each column in an index, so adding a new column in a similar fashion to the "storing" column, marked with an "implicit" flag, seemed logical.

Once this issue closes I'll open a new one to address the secondary EXPLAIN SELECT mentioned above.
