### ISSUE TITLE
sql: dropping multiple roles who have privileges should only show error for one role

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#52314]
When dropping multiple roles that have privileges, if there is a conflict ie a user has privileges on an object, PG only shows the error for the first conflict. Currently we show the errors for all the roles at once, this can be hard to process.

We should also combine the error messages for both having a privilege on an object and owning an object.

PG EXAMPLE
```
bench=# drop user hello1, hello2;
ERROR:  role "hello1" cannot be dropped because some objects depend on it
DETAIL:  owner of table t22
bench=# drop user hello2, hello1;
ERROR:  role "hello2" cannot be dropped because some objects depend on it
DETAIL:  privileges for table t3
owner of database d2
owner of table t23
```

**Comment by rafiss** [comment]
We'll leave the error handling as is unless we hear of a need to change it.
