### ISSUE TITLE
server: should expose Stopper.{NumTasks,RunningTasks}

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5231]
`(*stop.Stopper)` has methods `NumTasks` and `RunningTasks`. The first if self-explanatory and the second prints a map whose keys are `file:line` and the value a count.
Should be helpful for debugging. Maybe `/debug/stopper`?

**Comment by petermattis** [comment]
Let's leave this until after Beta.

**Comment by tschottdorf** [comment]
I'm asking for this because I wish I had this right now.

**Comment by petermattis** [comment]
We have no (graphical) design for this, though. Adding to the ui at this stage is asking for trouble. If you simply want it for debugging, then exposing it via an admin JSON endpoint sounds reasonable. And then we could provide a simple interface for retrieving it via a `cockroach debug` command.

**Comment by tschottdorf** [comment]
oh, yeah, that's what I was asking. I guess that's not really ui then. I just want something that sits next to pprof.
