### ISSUE TITLE
sql: user root does not have DELETE privilege on pg_enum

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#52325]
In CRDB you can't delete an ENUM value:
```SQL
DELETE FROM pg_enum
 WHERE enumtypid = 100063
   AND enumlabel = 'purple';
ERROR: user root does not have DELETE privilege on relation pg_enum
SQLSTATE: 42501
```

But in PG you can do this:
```SQL
DELETE FROM pg_enum
 WHERE enumtypid = 18205
   AND enumlabel = 'purple';
DELETE 1
```

**Comment by rohany** [comment]
This should not be done. It is unsafe to delete a member from an enum (pg doesn't expose a way to do this), and writing to catalog tables isn't a way to emulate that behavior (not that writing to catalog tables would ever work for us). I wonder what happens if you add that enum into a table, delete the entry from pg_enum, and then select from the table. I imagine something would go wrong.

**Comment by awoods187** [comment]
Interestingly, PG does let you delete the value but it does brick the table. 
```SQL
postgres=# select * from cars;
    brand     |   model   | color
--------------+-----------+-------
 ferari       | testarosa | red
 aston martin | db2       | blue
 bentley      | mulsanne  | gray
 ford         | T         | black
(4 rows)

postgres=# select * from pg_enum;
  oid  | enumtypid | enumsortorder | enumlabel
-------+-----------+---------------+-----------
 18236 |     18234 |             1 | blue
 18238 |     18234 |             2 | red
 18240 |     18234 |             3 | gray
 18242 |     18234 |             4 | black
(7 rows)

postgres=# DELETE FROM pg_enum
 WHERE enumtypid = 18234
   AND enumlabel = 'red';
DELETE 1
postgres=# select * from cars;
ERROR:  invalid internal value for enum: 18238
```
You can't even put it back because its a new value:
```
postgres=# ALTER TYPE color_t add value 'red';
ALTER TYPE
postgres=# select * from cars;
ERROR:  invalid internal value for enum: 18238
```

I'm on board with us disallowing the deletion altogether because it is superior user experience. However, I think we need to change the error. It currently says:
```
ERROR: user root does not have DELETE privilege on relation pg_enum
SQLSTATE: 42501
```
This implies that someone could have the privilege to do this. Instead, we should say something like:
```
Deletes from pg_enum are not allowed as ENUM values cannot be deleted. To delete a value from an ENUM type, you must first DROP TYPE before using CREATE TYPE.```

**Comment by rohany** [comment]
> Interestingly, PG does let you delete the value but it does brick the table.

I don't think that this is "pq letting you delete the value". the root user is allowed to do whatever it wants, but I don't think anyone should ever be writing to catalog tables.

**Comment by solongordon** [comment]
Per @rohany, it would be nice to add a HINT in this case to explain why it's not allowed.

**Comment by ajwerner** [comment]
Closing because please don't ever try deleting from pg_catalog tables in a postgres cluster unless you like pain.
