### ISSUE TITLE
QPS drop to zero when there is a network partition

### ISSUE THREAD

**Issue by zhouqiang-cl** [cockroachdb/cockroach#52330]
Hi, I am [Chaos Mesh](https://github.com/chaos-mesh/chaos-mesh) maintainer.
Today I using [Chaos Mesh](https://github.com/chaos-mesh/chaos-mesh) to test CRDB, when there is a network partition between two node. The QPS drops to zero when running TPCC, is this normal?

<img width="971" alt="截屏2020-08-04 上午11 51 42" src="https://user-images.githubusercontent.com/23521459/89251685-38f92f00-d64a-11ea-93d6-31f6feae5140.png">

<img width="1476" alt="截屏2020-08-04 上午11 52 22" src="https://user-images.githubusercontent.com/23521459/89251715-4dd5c280-d64a-11ea-9468-6e48a53c8466.png">

The topologic is 
```
zhouqiang@MacBook-Pro-3 ~ % kubectl get pods -n crdb-chaos
NAME                 READY   STATUS    RESTARTS   AGE
crdb-cockroachdb-0   1/1     Running   0          13m
crdb-cockroachdb-1   1/1     Running   0          25m
crdb-cockroachdb-2   1/1     Running   0          28m
```

**Comment by jordanlewis** [comment]
Sorry for the slow response. This is an interesting experiment, and thank you for running it.

I think it makes sense that, in a 3-node cluster, a single network partition will cause unavailability. @nvanbenschoten could you confirm (and close)?

**Comment by nvanbenschoten** [comment]
It depends on how the load is being run. If queries are being run in a round-robin fashion then eventually everything will get stuck waiting on the partitioned node.

@zhouqiang-cl this is a very cool experiment. Do you mind providing more detail about how it was run?

**Comment by mwang1026** [comment]
Closing the issue since we can't do anything without more detail. If you run this again would love for you to re-open and share more. Thanks!
