### ISSUE TITLE
sqlsmith: use table and column IDs in queries

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#52353]
Cockroach supports specifying table and column IDs in queries. Teach sqlsmith about these such that it

1) sometimes chooses the table/column id when generating queries instead of specifying names
2) sometimes chooses a random table/column id when generating table or column references

Jira issue: CRDB-3959

**Comment by mjibson** [comment]
@RichardJCai you might be interested in doing this?

**Comment by RichardJCai** [comment]
> @RichardJCai you might be interested in doing this?

Sure I'll give it a shot.
