### ISSUE TITLE
sql: 20.2 regression: foreign key constraint should not show schema name if schema is in search_path

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#52356]
**Describe the problem**

The SQLAlchemy test `test/dialect/test_suite.py::ComponentReflectionTest::test_get_foreign_keys` started failing. It fails because CockroachDB started including unexpected schema information when describing foreign key constraints. The cause of the failure is the change in PR #50889.

In Postgres, if you do `SELECT pg_catalog.pg_get_constraintdef(<constraintOid>, true)`, it will not include the schema name if the schema is in the `search_path`. However, that PR makes the schema always be included in the result.

**To Reproduce**

Setup:
```
> create table a (a int primary key);
> create table b(a int primary key, aa int references a(a));
```

In Postgres:
```
> SELECT r.conname,
                 pg_catalog.pg_get_constraintdef(r.oid, true) as condef,
                 n.nspname as conschema
           FROM  pg_catalog.pg_constraint r,
                 pg_namespace n,
                 pg_class c
           WHERE c.relname = 'a' AND
                 r.contype = 'f' AND
                 c.oid = confrelid AND
                 n.oid = c.relnamespace
           ORDER BY 1
+-----------+----------------------------------+-------------+
| conname   | condef                           | conschema   |
|-----------+----------------------------------+-------------|
| b_aa_fkey | FOREIGN KEY (aa) REFERENCES a(a) | public      |
+-----------+----------------------------------+-------------+
```

In CockroachDB
```
> SELECT r.conname,
                 pg_catalog.pg_get_constraintdef(r.oid, true) as condef,
                 n.nspname as conschema
           FROM  pg_catalog.pg_constraint r,
                 pg_namespace n,
                 pg_class c
           WHERE c.relname = 'a' AND
                 r.contype = 'f' AND
                 c.oid = confrelid AND
                 n.oid = c.relnamespace
           ORDER BY 1;

    conname   |                 condef                  | conschema
--------------+-----------------------------------------+------------
  fk_aa_ref_a | FOREIGN KEY (aa) REFERENCES public.a(a) | public
```

**Expected behavior**
If the schema name is in `search_path`, then do not include the schema name in the foreign key definition returned by `pg_get_constraintdef`.

**Comment by rafiss** [comment]
I talked about this with @rohany on Slack. If this doesn't seem like a good approach, then we could instead account for this in the `sqlalchemy-cockroachdb` dialect. That isn't my first choice, since it's possible that other tools also expect the behavior described in the ticket.

Rohan's pointer for a fix in the database:
> i think it would be not bad to just update the virtual table to do this check
> you'd have to update the function in `showForeignKeyConstraint` in `show_create_clauses.go`

**Comment by solongordon** [comment]
@rafiss apparently made a fix for this on the sqlalchemy side. Putting this in the backlog but let's see if this issue comes up for any other drivers.
