### ISSUE TITLE
importccl: enable support for IMPORT INTO ... DELIMITED

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#52405]
Since we support IMPORT INTO ... CSV and AVRO, we should be able to support IMPORT INTO ... DELIMITED without much extra work. This ticket is here to mostly track adding it to the set of supported formats as well as adding tests for this format.

**Comment by Anzoteh96** [comment]
A cursory glance yields that we _might_ be able to get PGCOPY supported too since the test files we have are also in the (some character)-separated values format instead of dump file format.
