### ISSUE TITLE
sql: add dummy sql proxy to 3node-tenant and Examples-ORMs

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#52413]
When https://github.com/cockroachdb/cockroach/pull/50647 was first posted, it contained a command that would start a simple incarnation of the SQL proxy. Due to time constraints, this was dropped from the final results.

We still want to run the 3node-tenant logictests through such a proxy, but more importantly, Examples-ORMs (to rule out driver incompatibilities around the tenantID embedding scheme).

**Comment by asubiotto** [comment]
@tbg per our last standup, are you going to take this on as part of the other work you wanted to do in `Examples-ORMs`?

**Comment by tbg** [comment]
Yep!

**Comment by tbg** [comment]
cockroach-go now allows spinning up a tenant with a proxy. Unfortunately, we never ran Examples-ORMs against secure CRDB in the first place, so about half the ORMs don't even manage that. Some more fiddling will be needed to straighten them all out.
