### ISSUE TITLE
Webui: click on Databases craches the node running the webui

### ISSUE THREAD

**Issue by HeavyHorst** [cockroachdb/cockroach#52422]
**Describe the problem**

I upgraded my cluster to Version v20.1.4.
Now whenever I click on "Databases" the node with the webui crashes.
Restarting the node is no problem.

**To Reproduce**

Not sure.
I had previously this problem: https://github.com/cockroachdb/cockroach/issues/51983
and did the described steps to fix it.
I updated to v 20.1.4 before removing the temp-Databases.

**Expected behavior**
I think the node should not crash.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

**Environment:**
 - CockroachDB version [v20.1.4]
Server OS: [Linux/Ubuntu 20.04 LTS]
Client app [webui]

Should I open another Ticket at https://support.cockroachlabs.com
and send the content of /var/lib/cockroach/cockroach-data/logs?

**Comment by lucy-zhang** [comment]
Hi @HeavyHorst. Yes, could you open a ticket and send us the logs, as well as a debug.zip?

**Comment by HeavyHorst** [comment]
Sure: https://support.cockroachlabs.com/hc/en-us/requests/6058

**Comment by HeavyHorst** [comment]
Not sure how usefull the debug.zip is.

The node crashes at this point:
```
retrieving SQL data for crdb_internal.zones... writing: debug/crdb_internal.zones.txt
writing: debug/crdb_internal.zones.txt.err.txt
  ^- resulted in driver: bad connection
```

**Comment by spaskob** [comment]
Ok there is a `NULL` in the `system.namespace` table:
`95	29	incloud	NULL`

It was introduced from the fix for the missing parent ID from #51983 which does not work entirely because of #50948.
Good news is that we can delete this row and be fine.

**Comment by spaskob** [comment]
Here are the steps for the fix:

1) Grant privileges to `system` table hack:

```sql
-- must be done as root, cannot be done as any other user
INSERT INTO system.users VALUES ('node', NULL, true);
GRANT node TO root;
```

2) Delete the `NULL` value:
`DELETE FROM system.namespace WHERE id IS NULL`

**Comment by mattcrdb** [comment]
Hi @HeavyHorst have you had a chance to see the fix above??

**Comment by HeavyHorst** [comment]
That worked great. Thanks!

**Comment by mattcrdb** [comment]
Awesome! glad to hear.
