### ISSUE TITLE
sql: prefer order-matching index when there is a limit

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#5246]
There is a tradeoff between selecting a non-covering index that has the desired ordering vs using a covering index that doesn't. However, when we have a limit the latter has the potential of reading much more data so we should prefer the order-matching index.

See https://github.com/cockroachdb/cockroach/issues/4925#issuecomment-196513251 for an example.

**Comment by tschottdorf** [comment]
to govern that "tradeoff", maybe taking into account the "average" (or otherwise characteristic) size of result sets which need to be handled for both possible options. Something like an "adaptive query planner". That must be a thing already in literature.

**Comment by petermattis** [comment]
"Cost based query optimization".

**Comment by tschottdorf** [comment]
I was more asking about particular techniques/impls in distributed systems. I know Postgres uses all sorts of stats on the data size to guess how much it's going to get back, but we won't have a lot of those luxuries. Are you aware of anything on that subsubject in particular?

**Comment by RaduBerinde** [comment]
Absolutely, you can be smarter if you have some kind of statistics available. We will definitely need to build some infrastructure around that.

Until then we can make a simple change to give a "bonus" that offsets the non-covering index penalty when an index satisfies the desired ordering completely AND there is a limit.

**Comment by petermattis** [comment]
I think we can do a decent job with table and index size statistics by using the range meta keys to determine how many ranges a particular range of keys spans.
