### ISSUE TITLE
adminui: clean up naming/restructure databases/grants page

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/cockroach#52474]
A customer running 20.1 was doing an audit on database users and identified a SQL user called "admin" on the grants tab when viewing databases via the Admin UI.

In 20.1 we made users and roles synonymous and this caused confusion for this customer.

You can distinguish between the users and roles via the SQL cli but the admin UI doesn't allow for that.

![image (1)](https://user-images.githubusercontent.com/51930844/89549860-e13bfe80-d7d6-11ea-8079-3455aa4689d2.png)

Jira issue: CRDB-3945

**Comment by dhartunian** [comment]
@elkmaster I'm not sure what info we have available on the user/role distinction from the DB but can you take a look and see what's possible here. Ideally we can distinguish between a user and a role.

**Comment by elkmaster** [comment]
@dhartunian , DB details do not contain use roles info, need changes to api.
![Screenshot 2020-11-30 at 16 40 52](https://user-images.githubusercontent.com/12850886/100623525-f52de200-332a-11eb-9506-9e44d5c809fe.png)

**Comment by dhartunian** [comment]
Thanks @elkmaster.

This ticket will require backend API changes. Moving back to TODO for now.
