### ISSUE TITLE
kv: eliminate BACKOFF transaction retries

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#5249]
When sql encounters an error with `TransactionRestart_BACKOFF`, we should figure out a way to propagate a suggestion about the backoff to the client

**Comment by andreimatei** [comment]
Upon various conversations, it seems more likely that we'll do away with `BACKOFF` retries altogether, replacing them with a signaling mechanism in the store for when the respective txn is able to make progress.

**Comment by bdarnell** [comment]
Retitling and reopening this because it's linked from the code (`sql/session.go`) and as far as I can see we don't have an issue tracking the plan to eliminate `BACKOFF` retries.
