### ISSUE TITLE
sql: `<col>_auto_not_null` validation fails inside a transaction

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#52501]
Consider the following queries:

```
begin;
create table a (a int);
alter table a alter column a set not null;
commit
```

This fails with:
```
ERROR: check "a_auto_not_null" does not exist
```

Seems unintended?

**Comment by otan** [comment]
cc @lucy-zhang as you seem to have a TODO very close to this validator.

**Comment by otan** [comment]
should this be a release blocker?

**Comment by jordanlewis** [comment]
Probably not a release blocker unless it's a regression.

**Comment by otan** [comment]
It is. This worked in 20.1.
