### ISSUE TITLE
storage: GC queue tuning

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5252]
The GC queue currently runs at regular intervals but doesn't actually get to delete much data. We should tune the threshold at which a replica is queued for GC (which is currently at one normalized units; too low).

To observe this, run the photos app for a while (single node is fine), then let the cluster idle and observe regular CPU spikes and the [gc queue's event log](http://macts.local:26258/debug/events?fam=queue&b=0&exp=1).

**Comment by spencerkimball** [comment]
Closing for age and lack of actionable or pressing next steps.
