### ISSUE TITLE
sql: failure to COMMIT schema changes with expressions with UDTs

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#52539]
**Error:**

The following error occurs sporadically when creating a computed column with a UDT in the expression in a transaction.

```
(40001) restart transaction: TransactionRetryWithProtoRefreshError: cannot publish new versions for descriptors: [{enum 53 3} {_enum 54 3}], old versions still in use
```

Could this be related to https://github.com/cockroachdb/cockroach/issues/40200?

**To Reproduce**

The failure should reproduce within a few minutes of stressing.

Run:

```
 make stress PKG='./pkg/sql/logictest' TESTS='TestLogic/fakedist/__test'
```

With the contents of `__test` as:

```
statement ok
SET experimental_partial_indexes = true;
SET experimental_enable_enums = true;

statement ok
CREATE TYPE enum AS ENUM ('foo', 'bar', 'baz')

statement ok
CREATE TABLE s (a enum)

statement ok
INSERT INTO s VALUES ('foo'), ('bar')

statement ok
ALTER TABLE s ADD COLUMN b enum AS (a) STORED;

query TT rowsort
SELECT * FROM s
----
foo  foo
bar  bar

statement ok
BEGIN

statement ok
CREATE TABLE t (a enum)

statement ok
INSERT INTO t VALUES ('foo'), ('bar')

statement ok
ALTER TABLE t ADD COLUMN b enum AS (a) STORED;

statement ok
COMMIT

query TT rowsort
SELECT * FROM t
----
foo  foo
bar  bar
```

It also reproduces when backfilling partial indexes in #52213, with the below test:

```
statement ok
SET experimental_partial_indexes = true;
SET experimental_enable_enums = true;

statement ok
CREATE TYPE enum AS ENUM ('foo', 'bar', 'baz')

statement ok
CREATE TABLE h (a INT, b enum)

statement ok
INSERT INTO h VALUES (1, 'foo'), (2, 'bar')

statement ok
CREATE INDEX a_b_foo_idx ON h (a) WHERE b = 'foo'

query IT rowsort
SELECT * FROM h@a_b_foo_idx WHERE b = 'foo'
----
1  foo

statement ok
BEGIN

statement ok
CREATE TABLE t (a INT, b enum)

statement ok
INSERT INTO t VALUES (1, 'foo'), (2, 'bar')

# CREATE INDEX i ON t (a) WHERE b = 'foo'
statement ok
CREATE INDEX i ON t (a) WHERE b = 'foo'

statement ok
COMMIT

query IT rowsort
SELECT * FROM t@i WHERE b = 'foo'
----
1  foo
```

**Environment:**

```
Build Tag:        v20.2.0-alpha.1-1917-g09804ffcfb
Build Time:       2020/08/08 16:04:17
Distribution:     CCL
Platform:         darwin amd64 (x86_64-apple-darwin19.6.0)
Go Version:       go1.14.4
C Compiler:       4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.17)
Build Commit ID:  09804ffcfbd511d2ce8d745a5eca2586bc6c96de
Build Type:       development
```

**Comment by rohany** [comment]
Just to be clear, it's the COMMIT of the transaction that adds the computed column thats failing?

**Comment by mgartner** [comment]
Yes, it’s the commit.

**Comment by rohany** [comment]
Hmm, this is worrying. In the "run schema changes in txn" path, we don't have the TypeResolverFactory, we are just using the planner's semaCtx. The planner should be cleaning up after itself in terms of descriptors accessed.

**Comment by mgartner** [comment]
I found this potentially??? related issue: https://github.com/cockroachdb/cockroach/issues/40200

**Comment by rohany** [comment]
It seems related. Also, I'm not sure what's special about the fakedist config that causes the failure. A test `TestTwoVersionInvariantRetryError` seems to be related, but makes it look like the error should only occur if there were concurrent operations going on.

**Comment by rohany** [comment]
Importantly, I can't seem to get a repro if the schema change outside of the transaction that involves the enum types before is not there. So that schema change might not be releasing its leases.

**Comment by rohany** [comment]
It also seems like the second schema change needs to be in a transaction for the error to occur.

**Comment by rohany** [comment]
So I updated the `DistSQLTypeResolver` not acquire any leases
```
@@ -1248,18 +1253,20 @@ func (dt *DistSQLTypeResolver) ResolveTypeByID(ctx context.Context, id uint32) (
 func (dt *DistSQLTypeResolver) GetTypeDescriptor(
        ctx context.Context, id descpb.ID,
 ) (tree.TypeName, sqlbase.TypeDescriptor, error) {
-       desc, err := dt.descriptors.getDescriptorVersionByID(
-               ctx,
-               dt.txn,
-               id,
-               tree.ObjectLookupFlagsWithRequired(),
-               false, /* setTxnDeadline */
-       )
-       if err != nil {
-               return tree.TypeName{}, nil, err
-       }
-       name := tree.MakeUnqualifiedTypeName(tree.Name(desc.GetName()))
-       return name, desc.(*sqlbase.ImmutableTypeDescriptor), nil
+       return resolver.ResolveTypeDescByID(ctx, dt.txn, dt.descriptors.codec(), id, tree.ObjectLookupFlagsWithRequired())
+       //log.Infof(ctx, "getting descriptor %d", id)
+       //desc, err := dt.descriptors.getDescriptorVersionByID(
+       //      ctx,
+       //      dt.txn,
+       //      id,
+       //      tree.ObjectLookupFlagsWithRequired(),
+       //      false, /* setTxnDeadline */
+       //)
+       //if err != nil {
+       //      return tree.TypeName{}, nil, err
+       //}
+       //name := tree.MakeUnqualifiedTypeName(tree.Name(desc.GetName()))
+       //return name, desc.(*sqlbase.ImmutableTypeDescriptor), nil
 }
```
and can still reproduce this error, so I'm pretty confused now. This seems to imply that this isn't caused by a backfill process holding onto a lease.

**Comment by mgartner** [comment]
Perhaps the issue is only reproducible with the fakedist config, and not something that could happen in real-world usage? If this has the same root cause as #40200, then I'm curious to know why that ticket has been open for about a year without causing major problems.

**Comment by rohany** [comment]
Well fakedist just puts spans on different nodes so that queries are distributed. It's a reasonable approximation of the real world. I'm not sure how related it is to #40200 given that it only pops up once user defined types are in play. But then again, maybe it is, given that we need the schema change to occur within the transaction. Either way, I think we're gonna need @lucy-zhang and @ajwerner's help to debug this one.

**Comment by awoods187** [comment]
Let's make sure we review this one soon

**Comment by mgartner** [comment]
I put up https://github.com/cockroachdb/cockroach/pull/54480 which uncomments the test that previously failed.
