### ISSUE TITLE
Subquery doesn't get resolved in lookup join

### ISSUE THREAD

**Issue by georgysavva** [cockroachdb/cockroach#52557]
**Is your feature request related to a problem? Please describe.**
Subqueries via `IN` filter, don't get resolved in a lookup join that is the most efficient option. If I rewrite the query to explicit `JOIN` then crdb chooses the right lookup join algorithm. 
Here is the query with subquery and `IN` filter:
```sql
SELECT *
FROM messages AS m
WHERE m.chat_id IN (SELECT uc.chat_id FROM user_chats AS uc WHERE uc.user_id = '2e3affd6-96e9-4e8b-ba43-d18e9397fc98');
```
It results in plan with a merge join: 
```
text
semi-join (merge)
 ├── scan m
 ├── scan uc
 │    └── constraint: /5/6: [/'2e3affd6-96e9-4e8b-ba43-d18e9397fc98' - /'2e3affd6-96e9-4e8b-ba43-d18e9397fc98']
 └── filters (true)
```

Here is the query with explicit join:
```sql
SELECT *
FROM messages AS m
         JOIN user_chats AS uc ON m.chat_id = uc.chat_id
WHERE uc.user_id = '2e3affd6-96e9-4e8b-ba43-d18e9397fc98'
```
It results in efficient plan with a lookup join:
```
text
inner-join (lookup messages)
 ├── scan uc
 │    └── constraint: /5/6: [/'2e3affd6-96e9-4e8b-ba43-d18e9397fc98' - /'2e3affd6-96e9-4e8b-ba43-d18e9397fc98']
 └── filters (true)
```
**Describe the solution you'd like**
Queries with subquery and `IN` filter should be resolved in the lookup join when it's the most efficient algorithm

**Additional context**
Schema: 
```sql
CREATE TABLE users (
    id   UUID PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE chats (
    id         UUID PRIMARY KEY,
    created_at TIMESTAMP NOT NULL
);

BEGIN;
SAVEPOINT cockroach_restart;


CREATE TABLE user_chats (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    chat_id UUID NOT NULL,
    PRIMARY KEY (user_id, chat_id)
);

CREATE INDEX ON user_chats(chat_id) INTERLEAVE IN PARENT chats (chat_id);
ALTER TABLE user_chats
    ADD CONSTRAINT fk_chat_id_ref_chats FOREIGN KEY (chat_id) REFERENCES chats(id) ON DELETE CASCADE;

RELEASE SAVEPOINT cockroach_restart;
COMMIT;

CREATE TABLE messages (
    chat_id    UUID      NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
    message_id INTEGER   NOT NULL,
    user_id    UUID      NULL REFERENCES users(id) ON DELETE SET NULL,
    PRIMARY KEY (chat_id, message_id)
);
```
It might be related with https://github.com/cockroachdb/cockroach/issues/43198

**Comment by RaduBerinde** [comment]
Thanks for filing!

The two queries are not quite equivalent, the second one returns more rows if there are duplicate chat_ids. We don't implement a lookup semi-join where we are looking up into the *left* side. We do have a rule that transforms from a semi join to an inner join with a group-by (added in #39411). I tried this on `master` and we do get the lookup join plan:
```
root@127.0.0.1:40549/defaultdb> explain (opt) SELECT *
FROM messages AS m
WHERE m.chat_id IN (SELECT uc.chat_id FROM user_chats AS uc WHERE uc.user_id = '2e3affd6-96e9-4e8b-ba43-d18e9397fc98');
                                                            text
-----------------------------------------------------------------------------------------------------------------------------
  project
   └── project
        └── inner-join (lookup messages)
             ├── scan uc
             │    └── constraint: /5/6: [/'2e3affd6-96e9-4e8b-ba43-d18e9397fc98' - /'2e3affd6-96e9-4e8b-ba43-d18e9397fc98']
             └── filters (true)
```

What version are you using? Can you post the output of `EXPLAIN (OPT, ENV, VERBOSE)` for the query?

**Comment by georgysavva** [comment]
My version is 20.1.4
Actually, I ran my query again and both `EXPLAIN (OPT, ENV, VERBOSE)` and just `EXPLAIN` now show the proper lookup join. 
The output of `EXPLAIN (OPT, ENV, VERBOSE)`: [here](https://cockroachdb.github.io/text/decode.html#eJzkmu9um0oWwD9fP8VRvtTeAJkZhoGhm5WoQ3e96ziRTbu3iiJEbOxwY4PFn9umq5Wu-gz9uE_XJ1mBsY0T29ewKdfV-kNL5sw5w_zOmcNwGFGE924YeYGvQzsYPoSBM7y_eAPtdhd-JUjCEoXmJ43ZjIrOfD51xZETfvR8TAW4S7xpDAQRdIbUM8KBEF3BukIEmARYwrLEW42GKELoBuHIDe1fAs-P7Kk382K4dyKI710YuWMnmcbwqzNNXB1o2t_1nbupa3_2Jp-dSaa1q3vgp_2DeezNvM9uaI-D0PUmvv3gPkZ7dBrtvmlYJljGm64JMzeKnIkbQbPx0_DeiW1vBO_edS6gd2VB7123KzR-yvukok7P0oqiyPVj24nB6lyaA8u4vC4Kk8gN1_YWbe2r3sDqG52eBSfz0Js54eMJXPc7l0b_A_zD_ADN5V0Yg7YAhaGNQbu1aWD8YOed7dAdZ9cRvL3qm52_9jZstaBvvjX7Zq9tDiDr1kwbr3pwYXZNy4S2MWgbF-Yz8_kMMvPp9RPzuXjDfNbtifmBuWLS6V2YP6-o204SB7bnj9xP9tbhlkMsZ__WuOx0PxTQLadYRCVA7hYBlnfYaL1uNIyuZfZzv8-nzuMkDBJ_JM2Tu6k3lFaR0On93WxbMLAMqzOwOu0BvLppAAD8K_s3_Z0Mg2ky86MTHW5WjZkgH_Bk1XorFLRC14ndke3EJzqcpItHRJqIOGCiK0xHSCIYaZp2ipCO0ElBc-RFsecPY3sYJH6qjXFBeu9FcWAPg6kdP87d1HYackV935ll7faCuL0hS6bTlV1UEITBx1U7UTGRqZIJ_y0cjGPtlO9PhHEka_JeLMeAJI_N786DMI6JrB09j3wBf__44P8HS4brSJEY1xRED0GiEU1FtMYQ0RRGFV4WSfWkWpJH3RFSDUf1DFIOB9EoUVmdGbUaj-oZpGR41J5Bao0PWUeKjrEkKxrl7AAeMsZIpqi--JAxJRTJNcVHaR61x0dFHhXTaXkePwaO6g_c0kQIxkhTa9yT1b1iKNMJkois0qNcMAqinCNc24IpiePHoPG_rJdyQGTOVQ0r9S2XikQqP3DL4VCQSjVZPXocFbIHRoAVnXAdMYlgolDloPRB6l0wDCGOUB2vL9V41Jw_KuKolj8qEaGcqBzV-LytiKRCAqnEgyFMEf2jeDRuX71-Un7PlsaicN18WjBfF9J3FeZ_v5heKB8LUKisP6-kv1Cpe1cl_cUL9YtC-prfagRv9GnjI0ILOj3L7HdN470JnR5cG32zZ0EOfTnw1tp6PukVuUPK6AWP_hGFdKRTqsuKRDSNE3yESRNzrabdeHkUfH9mOAYW1cOC67IqaSrSNPUQFvvLXi-OgjJWX1iUQ0EZO3oWlcNCwRkLrh1WAdxfK3_5NzSV1BYV5Ugoas177wooqgcF1ymWNE41TA76jFIvCq7VVSIvjYJr_OhZVH8do7qiSbKqIPUQFvL-yvjLfy3AvMZX9XIsSP3fTlY0Fq8d5s_XXaPTg-bVtSXAe7P_5mpgCmD23rdgYHbTjeqf4G3_6nJ9JMgYwAz--Tezb8JMWu6oUxN5_2S4as0UC1tfYwDJMNdN8k2xN4JzeEVc2RmPR0zkzOUidbU78c6hsjjCmstlro6HXHvVet0QRVFszMPgF3cYN-Db1_98-_rbt6-_Qe5Kfbkn13Hh5ItOlkdfdHl59kWnRfUoduJIh5sw-Bidy5hwJnGCuQBLlzVx6xwLkDJOL9Ht5uBRrANTVEolhhVelD24jzo0sUBaxdbxKG8Uxb80ZYFuCOdh4rs6NIm4aP-6as-nnf22zH3ljt2zn0mr-RccpbNnRncQud0y-mLyVMYSk5n6rMOCABFY65noGQYBUrrnTZZesfQKr7WWHDzfd0MxOwPXnAbBQzJfBWeruI5fhNDyD2UbruczXQ91w27hHG7w7fa-pSOuIGFrCVvE4vZJLxyDsSYxRVV23vOmd7a5KPOPknnnMGc9nezQ8SEZbgq_7PDRgdCfqftRHDqeH-twppwxHW7ODssqIMKBPW_33sGGR3HBXcraXUoZR35Z_5c9GSahM0stACDY8sM7tTd-fxZF8cB8-zvA0_DCElL2dlvE19Po-rI7yPZ2XKbGHfbWGSJ2QzeFPIHsnK3nTyIdmqeKcMpa0DxlwunTkZa6Y28aZ2cs4zBxW43_BgAA__873k9_)

Apparently something was preventing `EXPLAIN` from figuring out the best plan before, and now it can do it, sorry for bothering.

**Comment by RaduBerinde** [comment]
Thanks, closing. Note that if the tables are very small, the optimizer chooses merge join (#41701).
