### ISSUE TITLE
sql: batch sql insert KV operations within a transaction

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#5259]
See #3304. The scenario is a user doing:

```
BEGIN;
INSERT INTO table-user-order (four indexes);
INSERT INTO table-order-log;
INSERT INTO table-product-info;
INSERT INTO table-gift (x indexes);
.....
COMMIT;
```

Currently, each of the insert statements is executing a separate KV-layer batch. If the inserts are "simple" (i.e. they aren't using a `SELECT` to retrieve values), then a single KV batch could be performed. This can be seen as an extension to the batching that takes places inside a single `INSERT`. For example, the following 2 sets of statements are equivalent, but the first is much faster:

```
INSERT INTO foo VALUES (1), (2);
```

```
BEGIN;
INSERT INTO foo VALUES (1);
INSERT INTO foo VALUES (2);
COMMIT;
```

There are complexities if we try to perform this batching when the statements come in separate requests. As a starting point, I think we should aim to only performing batching of statements within a single request.

**Comment by tschottdorf** [comment]
Not an issue here, but the corresponding batching for reads could be
complicated by the fact that we introduced a batch-global scan limit
recently (so when adding to a batch, must check that there's no limit set,
and no limit must be set on an existing batch). Just a heads up in case
that comes up.

**Comment by paperstreet** [comment]
I'm probably not going to be working on this anytime soon, so unassigning for now in case someone wants to pick it up.

**Comment by spencerkimball** [comment]
Closing in favor of #10057
