### ISSUE TITLE
sql: unique partial indexes do not work correctly with INSERT ON CONFLICT

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#52603]
Below, the second row should be inserted because there is no conflict possible when `b` is `0`.

```
root@127.0.0.1:53772/defaultdb> create table t (a int, b int, s string, unique index (a) where b > 0);
CREATE TABLE

Time: 6.058ms

root@127.0.0.1:53772/defaultdb> insert into t values (1, 1, 'foo') on conflict (a) do update set s = 'conflict';
INSERT 1

Time: 1.82ms

root@127.0.0.1:53772/defaultdb> select * from t;
  a | b |  s
----+---+------
  1 | 1 | foo
(1 row)

Time: 613µs

root@127.0.0.1:53772/defaultdb> insert into t values (1, 0, 'foo2') on conflict (a) do update set s = 'conflict';
INSERT 1

Time: 1.85ms

root@127.0.0.1:53772/defaultdb> select * from t;
  a | b |    s
----+---+-----------
  1 | 1 | conflict
(1 row)

Time: 599µs
```

**Comment by mgartner** [comment]
The query plan below reveals the issue:

```
exec-ddl
CREATE TABLE t (a INT, b INT, s STRING, UNIQUE INDEX (a) WHERE b > 0)
----

opt
INSERT INTO t VALUES (1, 0, 'bar') ON CONFLICT (a) DO UPDATE SET s = 'conflict'
----
upsert t
 ├── columns: <none>
 ├── canary column: 13
 ├── fetch columns: a:10 b:11 s:12 rowid:13
 ├── insert-mapping:
 │    ├── column1:6 => a:1
 │    ├── column2:7 => b:2
 │    ├── column3:8 => s:3
 │    └── column9:9 => rowid:4
 ├── update-mapping:
 │    └── upsert_s:19 => s:3
 ├── partial index put columns: column21:21
 ├── partial index del columns: column15:15
 └── project
      ├── columns: column21:21 upsert_s:19!null column15:15 column1:6!null column2:7!null column3:8!null column9:9 a:10 b:11 s:12 rowid:13
      ├── left-join (cross)
      │    ├── columns: column1:6!null column2:7!null column3:8!null column9:9 a:10 b:11 s:12 rowid:13
      │    ├── values
      │    │    ├── columns: column1:6!null column2:7!null column3:8!null column9:9
      │    │    └── (1, 0, 'bar', unique_rowid())
      │    ├── select
      │    │    ├── columns: a:10!null b:11 s:12 rowid:13!null
      │    │    ├── scan t
      │    │    │    ├── columns: a:10 b:11 s:12 rowid:13!null
      │    │    │    └── partial index predicates
      │    │    │         └── secondary: filters
      │    │    │              └── b:11 > 0
      │    │    └── filters
      │    │         └── a:10 = 1
      │    └── filters (true)
      └── projections
           ├── CASE WHEN rowid:13 IS NULL THEN column2:7 ELSE b:11 END > 0 [as=column21:21]
           ├── CASE WHEN rowid:13 IS NULL THEN column3:8 ELSE 'conflict' END [as=upsert_s:19]
           └── b:11 > 0 [as=column15:15]
```

The row is updated rather than inserted in the original test case because the canary column is simply the `rowid` of all rows in the table. Therefore, any conflicting value of `a` will trigger an update.

**In order to make `INSERT ON CONFLICT` work correctly with unique partial indexes, we'll need to do the following:**

1. Add additional syntax (like Postgres) that allows a `WHERE` clause after `ON CONFLICT`. This allows the user to "specify" which uniqueness constraint they are referring to. This is necessary in the event that there are two partial unique indexes on the same column. We must have the user specify which one they are concerned about conflicts on.
2. `mutationBuilder.ensureUniqueConflictCols` must check the `WHERE` clause of the `INSERT ON CONFLICT` statement against unique partial indexes. If the clause implies the partial index's predicate expression (using `partialidx.Implicator`), the scan operator for fetching the canary column must have the partial index's predicate applied as a filter. This should filter out any conflicting columns that do not exist in the partial index. It should also allow the optimizer to use the partial index to perform the scan.

**However, support for this opens up a can of worms.**

1. Without support for constrained partial index scans or left-joins on partial indexes, this could make these `INSERT ON CONFLICTS` VERY slow. They are fast for non-partial unique indexes currently because the unique index is used to search for conflicts quickly. With only unconstrained partial index scans, each insert could scan the entire partial index.
2. Somehow Postgres is able to determine the least restrictive partial index to check for conflicts:

```
marcus=# create table t (a int, b int);
CREATE TABLE
marcus=# create unique index i on t (a) where b > 10;
CREATE INDEX
marcus=# create unique index i2 on t (a) where b > 0;
CREATE INDEX
marcus=# insert into t values (1, 1) on conflict (a) where b > 10 do update set b = 100;
INSERT 0 1
marcus=# select * from t;
 a | b
---+---
 1 | 1
(1 row)

marcus=# insert into t values (1, 2) on conflict (a) where b > 10 do update set b = 100;
INSERT 0 1
marcus=# select * from t;
 a |  b
---+-----
 1 | 100
(1 row)
```

Another short term option is to not support `INSERT ON CONFLICT` for unique partial indexes for the time being, and returning the error we currently return when there is no uniqueness constraint on the specified column: `ERROR: there is no unique or exclusion constraint matching the ON CONFLICT specification`.

**Comment by mgartner** [comment]
> Somehow Postgres is able to determine the least restrictive partial index to check for conflicts:

Thinking about this more, I think this would require us to include separate scans for all partial indexes for which the predicate is implied. For arbitrarily complex predicates, there is no perfect way to determine the least restrictive one. In fact, I think it is guaranteed to be impossible when you compare two columns. Imagine unique partial indexes where `a > b` and `a > 10`—you have to check both indexes for potential duplicates.

**Comment by mgartner** [comment]
Hmm, I'm actually not sure what the WHERE syntax is for. It seems to be that they ALWAYS check for uniqueness of all partial indexes? In this case, the `b > 10` in the INSERT does not imply `a > b`, but yet the insert fails regardless for the duplicate key in `i2`.

```
marcus=# create table t (a int, b int);
CREATE TABLE
marcus=# create unique index i on t (a) where b > 10;
CREATE INDEX
marcus=# create unique index i on t (a) where a > b;
ERROR:  relation "i" already exists
marcus=# create unique index i2 on t (a) where a > b;
CREATE INDEX
marcus=# insert into t values (20, 1) on conflict (a) do update set b = 1000;
ERROR:  there is no unique or exclusion constraint matching the ON CONFLICT specification
marcus=# insert into t values (20, 1) on conflict (a) where b > 10 do update set b = 1000;
INSERT 0 1
marcus=# select * from t;
 a  | b
----+---
 20 | 1
(1 row)

marcus=# insert into t values (20, 1) on conflict (a) where b > 10 do update set b = 1000;
ERROR:  duplicate key value violates unique constraint "i2"
DETAIL:  Key (a)=(20) already exists.
```

**Comment by RaduBerinde** [comment]
> Hmm, I'm actually not sure what the WHERE syntax is for.

The pg [docs](https://www.postgresql.org/docs/12/sql-insert.html) are pretty good:

> conflict_target can perform unique index inference. When performing inference, it consists of one or more index_column_name columns and/or index_expression expressions, and an optional index_predicate. All table_name unique indexes that, without regard to order, contain exactly the conflict_target-specified columns/expressions are inferred (chosen) as arbiter indexes. If an index_predicate is specified, it must, as a further requirement for inference, satisfy arbiter indexes. Note that this means a non-partial unique index (a unique index without a predicate) will be inferred (and thus used by ON CONFLICT) if such an index satisfying every other criteria is available. If an attempt at inference is unsuccessful, an error is raised.

In your example above, the partial index with a>b is not an "arbiter index" and is not "covered" by the ON CONFLICT clause; the insert errors out as if there was no ON CONFLICT clause.

**Comment by mgartner** [comment]
> In your example above, the partial index with a>b is not an "arbiter index" and is not "covered" by the ON CONFLICT clause; the insert errors out as if there was no ON CONFLICT clause.

Ah I got confused. You're absolutely right.

So in the case that there are multiple implied arbiter indexes, we'd need to construct a scan for each one.

**Comment by RaduBerinde** [comment]
> So in the case that there are multiple implied arbiter indexes, we'd need to construct a scan for each one.

I believe we can construct a single scan with a filter that is the OR of all the predicates of the indexes we are interested in. That would tell us if a conflicting row exists in any of the indexes, without necessarily scanning all the indexes.

**Comment by mgartner** [comment]
I suppose the `SplitDisjunction` rule could split that scan up into multiple scans. But I think we'd want a way to ensure that multiple indexes are used—if they are not, it could lead to a full table scan:

```
CREATE TABLE t (a INT, b INT, UNIQUE INDEX (a) WHERE a > b, UNIQUE INDEX (a) b > 0)

INSERT INTO t VALUES (1, 1) ON CONFLICT (a) WHERE a > b AND b > 0 DO UPDATE SET b = 5;
```

If the uniqueness check is `SELECT rowid FROM t WHERE a = 1 AND (a > b OR b > 0)` the only way to efficiently answer that is a constrained scan of both indexes. We cannot have an `INSERT ON CONFLICT` performing full table scans to check for uniqueness—that's why uniqueness constraints require unique indexes.

**Comment by RaduBerinde** [comment]
Sure, but ideally we should ensure that it happens as part of the optimizer's regular decision process. Then we can take advantage of other optimizations. For example, we may have duplicate indexes in multiple locations (we'd want to choose the local one); or, if one index predicate implies the other, the filter would get simplified and we'd automatically get a better plan (using just one index).
