### ISSUE TITLE
logictest: 3node-tenant failures meta issue

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#52617]
This is a tracking issue for all logictests that currently block the 3node-tenant configuration. The issues are organized as MVP (meaning they should be addressed sooner rather than later), MVP Lower Priority (nice to have, probably easy fixes) and Later (meaning they are expected failures for the MVP).

## MVP
- [x] #52567 
    - privileges_database
    - rename_table
    - namespace
    - rename_database
    - drop_type
    - sequences
    - database
    - drop_database
    - drop_view
    - owner
- [x] #50049 
    - ~owner~
    - ~enums~
    - table
- [x] #52558 
    - alter_primary_key
- [x] #53040
    - cascade

## MVP Lower Priority
- [x] #49582
    - lookup_join
    - select_index

## Later
- [x] #47895
    - run_control
- [x] #47899
    - sqlsmith
- [x] #49854
    - schema_change_in_txn
    - zone_config
    - system
    - interleaved
    - builtin_function
    - fk
    - enums
- [x] #50047
    - event_log
    - distsql_event_log
- [ ] #52763 
    - statement_statistics

Jira issue: CRDB-3932

**Comment by stevendanna** [comment]
@rafiss Yup, my plan is to catalog the remaining failures this week and update this issue accordingly.

**Comment by knz** [comment]
This is now reduced to just https://github.com/cockroachdb/cockroach/issues/52763.
