### ISSUE TITLE
sql: data types DATE, INTERVAL, TIMESTAMP lack precision

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#5266]
Fixing #4393 required the following observation: in order to guarantee distinct timestamps in different transactions one needs to use sub-nanosecond resolution. 

The problem is that the width of the SQL types does not allow this: they use Go's `time.Time` which has 64 bits for seconds and 32 bits for nanoseconds. The sub-nanosecond `Logical` field of CockroachDB clocks which is necessary to disambiguate timestamps comes at an additional 32 bits on top of this. 

We can't simply trade `time.Time` for `roachpb.Timestamp` because the latter only uses 64 bits for combined nanoseconds and seconds, so it has a smaller time range than the current SQL type (which is thus likely unacceptable for some users).

To extend the SQL types with the necessary precision would imply increasing the size of the various time-related types, including their size on disk. 

Thus the questions:
- should we increase the resolution of SQL time-related types, or are users satisfied with disambiguating using `transaction_timestamp_unique()` (introduced by #5037)?
- if we want to increase the resolution of SQL type, do we do this by taking bits away from the seconds field (and thus keep the current size at 96 bits) or increase the number of bits? (to 128)

**Comment by JackKrupansky** [comment]
Time resolution at the SQL level should relate to the user's model of time and not some internal, implementation detail/consideration/artifact. Even microsecond resolution is much more than any real user can make use of for any real-world application. And I would argue that the max time delta between nodes for replication limits the useful resolution of any time stamp even if a user did try to submit requests on some super-fine time resolution.

Postgres and MySQL use microsecond resolution. Oracle defaults to 6 digits of precision (microsecond), but allows up to 9 (nanosecond.) That seems sufficient for the forseeable future, especially for distributed databases. If anything, CockroachDB should fuzz the timestamp at the KV level to assure that KV events don't get a real (as opposed to logical) value of resolution finer than a microsecond (or even max time between node clocks). I mean, given the importance of replication and the physical limitation of the speed of light to get between physical machines, there is no need to have the timestamp for the transaction be any finer than roughly the average of the timestamps of the replicas, and how likely is it that one node could initiate a replication on another node and have that operation complete in less than a microsecond?

**Comment by tschottdorf** [comment]
Transactions can get the same physical timestamps for as long as the clock offset (this happens if one node's HLC is updated from a higher timestamp; until that node's clock has caught up with that timestamp, only the logical portion will tick). I think `transaction_timestamp_unique()` makes sense for everyone who knows about it, what we need to make sure is that its existence is clearly documented ("On time in CockroachDB").

**Comment by bdarnell** [comment]
+1 to making the "logical" portion of the timestamp available via a separate function for those that really need it but leaving the regular time types alone.

**Comment by knz** [comment]
The problem was resolved via `cluster_logical_timestamp()` in #5805.
