### ISSUE TITLE
sql: suggest case alternates after finding a name lookup error

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#52678]
We have had users coming to us saying that " `SELECT * FROM myTableWithMixedCase`  does not work"

The real situation is that they used some ORM or UI tool which secretely under the hood issued `CREATE TABLE "myTableWithMixedCase"` to preserve the case in the catalog. So every further use of that table must use quoting too.

This is a common pitfalls for users who are not yet aware of postgresql's identifier case semantics.

To alleviate the user's experience, we can fix this as follows: **on the error path after a lookup error** look through the namespace and if there's an identifier that equivalent when ignoring case, report it as a suggestion in the error message. For example:

```
# SELECT * FROM myTableWithMixedCase
ERROR:  42P01: relation "mytablewithmixedcase" does not exist
HINT: another relation with name myTableWithMixedCase exists. Try quoting the name in the statement.
```

It's not exactly trivial to do this because of PostgreSQL's `search_path`: there are likely multiple namespaces where the name could have been found. The last schema in `search_path` (usually, `pg_catalog`) is likely not the one where the other-cased name was to be found (usually, `public`).

Perhaps another strategy to construct the alternative is to re-launch the lookup with a bool flag `tryHarder = true` and `tryHarder` would use a more complex algorithm than strict string equality. The advantage of this route is that we could also do spelling corrections in addition to case insensitivity.

**Of course because these alternate lookups are considerably more expensive, they should only be done after the first lookup has reached an error situation already.** This way we don't pay extra in performance in the common case where there is no lookup error.

Jira issue: CRDB-6307

**Comment by awoods187** [comment]
I love this idea--i'm generally pro improving our error message story to a degree that someone would never need to leave the shell.
