### ISSUE TITLE
jobs: use enum for system.tenants.active

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#52691]
https://github.com/cockroachdb/cockroach/issues/48775#issuecomment-655215813

From @dt:

> I'd suggest changing active from a bool to an enum (ideally soon, before we need to do a migration) so it can be extended to capture more detail about the state, e.g. off the top of my head I think it would make sense to have at least 4 states: active, inactive, adding, and dropped. This could e.g. make it easier to identify tenants who have been destroyed but whose key-span has not been cleared, if we see a record in state dropped. The current bool's coarseness makes it impossible to tell a tenant that is restoring but is not yet active from one that is dropping.

We'll want to do this even if we don't immediately implement the job that performs the hard delete and moves a tenant from "dropping" to "dropped".

**Comment by nvanbenschoten** [comment]
@dt I actually don’t think “dropped” is a useful state. The idea was for a deletion of the row to indicate that a tenant is fully removed. So then the question is whether we need to distinguish between “adding” and “dropping” or whether a single “inactive” is sufficient. I think we'll want to distinguish the two states because a tenant in the "dropping" state will indicate to the jobs framework that its data should be deleted and removed while a tenant in the "adding" state will indicate that a tenant is being restored into and should not be deleted.

So then the concrete proposal would be to change the data type of the `status` field to a `STRING` with a `CHECK (status IN ('adding', 'active', 'dropping'))` constraint. The relevant state transitions would be:
- `crdb_internal.create_tenant`: creates empty tenant with an `'active'` status.
- `crdb_internal.destroy_tenant`: moves tenant to `'dropping'` status.
- `tenant gc job` (after #48775): finds tenants with a `'dropping'` status. Destroy their data. Deletes row in `system.tenants` table.
- `BACKUP`: backs up all tenants.
- `BACKUP TENANT x`: verifies that tenant X has `'active'` status, backs up if so.
- `RESTORE`: verifies that tenant row does not exist. Creates row with `'adding'` status. Restores tenant data. Moves row to `'active'` status.

@dt does this all check out?

**Comment by tbg** [comment]
When we introduce per-tenant settings for rate limits, etc, we would likely also put them in this table, right? Would we add a new column or would we rather have just one column backed by a protobuf? If the latter, we should introduce a protobuf instead.
The reason I suspect we might like just one column is that it makes it easier for the KV layer to pull the info it needs out of the raw system config gossip data, but I have never touched that so I'm not sure what our best practice is here.

**Comment by nvanbenschoten** [comment]
I'm also not sure what our best practices are around this either, but I do know that others have relatively strong opinions, though I can't remember what those opinions are. @ajwerner what do you think? How do we feel these days about stuffing protobufs into SQL columns? Does the idea of a `TenantDescriptor` fill you with hope or dread? It appears like things have improved now that we have SQL builtins to manipulate protos.

If you prefer that approach, maybe we drop the `active` column and repurpose the `info` column to hold this descriptor proto?

**Comment by dt** [comment]
one bytes column with a big protobuf is easiest to extend later, but it isn't _great_ for inspection/retrieval in SQL -- I could see wanting find tenants by status for example -- so I'd probably keep status in a separate column and add your big protobuf of settings in a different column later, but I don't have very strong feelings on it. maybe schema folks do? cc @lucy-zhang and @ajwerner

**Comment by ajwerner** [comment]
We've gotten much better at introspecting protos from SQL. I'm increasingly on board with doing more of it.
