### ISSUE TITLE
rowexec: implement RowSource in sampleAggregator/samplerProcessor

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#52700]
Both processors implement the `Processor` interface, which exposes a `Run` method meant to be run in a goroutine. The upside of this model is that processors get their own goroutine, the downside is unbounded parallelism and worse performance due to the use of channels to communicate between goroutines.

The alternative for better performance is to implement a `RowSource` interface, which allows for processors to be fused into a single goroutine and pull data from each other in a volcano execution model. The other downside of not implementing the `RowSource` interface is that processors may not be allowed to use some shared resources concurrently. An example of this is the `RootTxn` which is used when a whole execution flow is local.

Recently, I came across an issue regarding the `samplerAggregator` and `samplerProcessor` with respect to the `RootTxn`. Distsql refuses to run this flow since there is parallelism and it assume the `RootTxn` will be touched concurrently. In https://github.com/cockroachdb/cockroach/pull/52621, I make this check more lenient, since these processors do not touch the `RootTxn`, but I think it would be good to have these processors implement the `RowSource` interface so that they can be fused into a single goroutine.

Jira issue: CRDB-3928

**Comment by rytaft** [comment]
Just to confirm, this isn't needed for the 20.2 release, correct? It seems like this will be a non-trivial change, so I'd rather wait until after the stability period if possible...

**Comment by asubiotto** [comment]
> Just to confirm, this isn't needed for the 20.2 release, correct?

That's correct. #52621 works around the planning limitation for 20.2.

**Comment by rytaft** [comment]
I think this is probably not worth doing since it would be better to just implement vectorized stats processors as described in https://github.com/cockroachdb/cockroach/issues/41203. Closing.
