### ISSUE TITLE
sql: show timezone displays incorrect values

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#52709]
SHOW TIMEZONE displays incorrect values:
In PG:
```SQL
postgres=# show timezone;
     TimeZone
------------------
 America/New_York
(1 row)
```
In CRDB:
```SQL
root@127.0.0.1:64512/movr> show timezone;
  timezone
------------
  UTC
(1 row)

Time: 910µs
```

**Comment by himanshuchawla009** [comment]
I was going through docs and  i think it is intentional to leave the default time zone as UTC, this is also given in docs to convert the timezone values on client side.
https://www.cockroachlabs.com/docs/v20.1/set-vars#set-time-zone

**Comment by awoods187** [comment]
While different than PG, it is client side behavior that can be overwritten as demonstrated in the blog post above. Will close.
