### ISSUE TITLE
sql: pgx TestConnCopyFromLarge encounters EOF prematurely

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#52722]
In `pgx` copy_from_test.go, `TestConnCopyFromLarge` fails. The error is:
```
    copy_from_test.go:99: Unexpected error for CopyFrom: ERROR: read binary tuple: EOF (SQLSTATE XXUUU)
```

Here's the relevant part of the test
```
        mustExec(t, conn, `create temporary table foo(
                a int2,
                b int4,
                c int8,
                d varchar,
                e text,
                f date,
                g timestamptz,
                h bytea
        )`)

        tzedTime := time.Date(2010, 2, 3, 4, 5, 6, 0, time.Local)

        inputRows := [][]interface{}{}

        for i := 0; i < 10000; i++ {
                inputRows = append(inputRows, []interface{}{int16(0), int32(1), int64(2), "abc", "efg", time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC), tzedTime, []byte{111, 111, 111, 111}})
        }

        copyCount, err := conn.CopyFrom(context.Background(), pgx.Identifier{"foo"}, []string{"a", "b", "c", "d", "e", "f", "g", "h"}, pgx.CopyFromRows(inputRows))
        if err != nil {
                t.Errorf("Unexpected error for CopyFrom: %v", err)
        }
```

The test passes if the number of `inputRows` is decreased to 1000.

Deliverable for this ticket: Determine why the test is failing.

Jira issue: CRDB-3925

**Comment by mniewrzal** [comment]
I encounter this issue while using `CopyFrom` for migrating large amount of data in single execution (500 entries). When I tried to reduce numer of rows (50 entries) to sent I had a different error `read binary tuple: partial copy data row (SQLSTATE XXUUU)`. I was able to use `CopyFrom` when I reduced batch size to 15.

**Comment by rafiss** [comment]
I wonder if this relates to https://github.com/cockroachdb/cockroach/issues/58069 -- CockroachDB has an incorrect binary encoding for tuples. But I don't see why changing the batch size would affect things.

**Comment by rafiss** [comment]
This passes now
