### ISSUE TITLE
sql/pgwire: PG 'date' type insert error 

### ISSUE THREAD

**Issue by Linicks** [cockroachdb/cockroach#5272]
All,
  I think that I discovered another SQL quirk.  I know all the SQL stuff is being worked on, but wanted to add this to the Que of things to look at.  

Added a column to a company table:

>ALTER TABLE company ADD join_date DATE;
ALTER TABLE

Then tried to insert a record:

>INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY,JOIN_DATE) VALUES (1, 'Mead', 42, 'Wyoming', 90000.00 ,'2011-01-11');
pq: value type string doesn't match type DATE of column "join_date"

./cockroach version
Build Vers:  go1.6
Build Tag:   alpha.v1-1064-g1ed2983
Build Time:  2016/03/15 16:46:04

Thanks!
-- Nick

**Comment by JackKrupansky** [comment]
You can use an explicit cast of the string constant - CAST '2011-01-11' AS
DATE.

-- Jack Krupansky

**Comment by petermattis** [comment]
@nvanbenschoten Is this fixed now?

**Comment by nvanbenschoten** [comment]
Yes, the query is supported now.
