### ISSUE TITLE
opt: TestCreateStatsProgress flaky

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#52782]
@yuzefovich saw a failure of this test on 19.2.

There is also a record of a failure on master here: https://github.com/cockroachdb/cockroach/issues/43564#issuecomment-670988572

**Comment by yuzefovich** [comment]
Saw it one more time here https://teamcity.cockroachdb.com/viewLog.html?buildId=2183887&buildTypeId=Cockroach_UnitTests.

**Comment by jbowens** [comment]
https://teamcity.cockroachdb.com/viewLog.html?buildId=2187601&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_Test
