### ISSUE TITLE
sql: open transactions cause user changes to be blocked until the leases expire

### ISSUE THREAD

**Issue by imjching** [cockroachdb/cockroach#52792]
We noticed that a production cluster had a ton of transactions that were not closed. This effectively causes all user changes to wait until the leases on the `role_members` table expire because any table that is using permissions will hold open a lease to that table. The expiration for the leases is 5 minutes and we refresh it once a minute. This results in behaviors such as waiting up to 5 minutes for a `DROP USER` query to return (even though the changes have already been applied). 

@ajwerner thinks that we should re-think this for how the `role_members` table is going to work.

Jira issue: CRDB-3920

Epic CRDB-22371

**Comment by ajwerner** [comment]
I think the question here should be about what it means for a change to role membership to return to the user. Currently it means that all transactions which succeed after the `GRANT`/`REVOKE`/`DROP USER` returns will observe that outcome, even concurrent operations.

We could easily change this to say, all statements which occur after the operation returns will observe the outcome. This would be a little bit bizarre in the context of serializability but not *too* crazy. 

To implement the above protocol, we'd acquire the lease on `system.role_membership` when checking permissions like we do today, but we'd drop that lease immediately after the check. This would allow later statements to see a later version of the table (and thus the cache). 

cc @aaron-crl , @knz , @thtruo

**Comment by aaron-crl** [comment]
cc @piyush-singh

**Comment by knz** [comment]
I don't have skin in this game, I think both approaches are fine.

However, it's the ORMs and 3rd party compatibility we need to care about here. If we introduce alternate behavior, we'll want to do so in a way that keeps Hibernate's test suite happy (and the like)

**Comment by knz** [comment]
A note to whomever picks this up: be careful to ensure that the structured logging event for the priv change gets logged when the statement takes effect.

Today this logging occurs at the end of the txn because the change is transactional. If we change that, we need to change the logging too.

**Comment by massimocGH** [comment]
@ajwerner , do you think we should add a note to the docs that describe the implications with running grant operations within an explicit transaction? Pretty much like what is described for general schema changes (provided it all applies):
```
Limited support for schema changes within transactions
Schema changes keep your data consistent at all times, but they do not run inside transactions in the general case. Making schema changes transactional would mean requiring a given schema change to propagate across all the nodes of a cluster. This would block all user-initiated transactions being run by your application, since the schema change would have to commit before any other transactions could make progress. This would prevent the cluster from servicing reads and writes during the schema change, requiring application downtime.
```

**Comment by ajwerner** [comment]
> Today this logging occurs at the end of the txn because the change is transactional. If we change that, we need to change the logging too.

I don't think this is right at all. Today the logging happens after the KV transaction which published the new version commits, but that event will be in `system.eventlog` and get logged to the logging system before we wait for the leases to drain. I don't think we can get worse here.
