### ISSUE TITLE
metrics: Expose timeseries that tracks days until license expiry

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#52794]
We have customers that would like to define alerts that trigger when their enterprise license keys are about to expire. We should expose a new timeseries that tracks the number of days remaining until the license key in a cluster expires. We should also update our alert definitions to give an example alert that tracks time until license expiry with a warning 30 days before expiration.

Open questions:
- What should the value of this timeseries be for a core cluster without a license key? Want to avoid users taking our alerts file as written and suddenly seeing alerts for license expiration on a core cluster.

**Comment by piyush-singh** [comment]
Follow up request from the customer: they would also like to expose a few additional methods to check if their licenses are valid:
- an HTTP endpoint
- a SQL query to an internal table

We will want to reach out to a few customers to see how we should structure an HTTP endpoint (or at least gather feedback on our proposed structure).

**Comment by BramGruneir** [comment]
Here's another feature request for this:  https://cockroachdb.zendesk.com/agent/tickets/6330

It seems relatively easy and I think we try to get it into 20.2, but if not, it should be easy for 21.1.
