### ISSUE TITLE
scheduled backups: references/dependencies between two schedules created by same `CREATE` command

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#52791]
If you create a schedule that has FULL and INCREMENTAL backups, it creates two schedules. Weird behaviors
- Pause one but not the other
- Cancel one but not the other
- SHOW SCHEDULEs for one ID doesn't the other
- SHOW JOBS for SCHEDULE etc.

**Comment by adityamaru** [comment]
@miretskiy for the "schedule group" commands did you have something like this in mind in terms of the rules, or do we want to introduce a "GROUP" keyword somewhere? My thinking is that currently the keyword `SCHEDULES` supports select statements, but we could teach it to take an `a_expr` which would be the schedule group name you are adding?

`SHOW SCHEDULES *schedule_group_name*`
`SHOW JOBS FOR SCHEDULES *schedule_group_name*`
`PAUSE SCHEDULES *schedule_group_name*`
`RESUME SCHEDULES *schedule_group_name*`
`DROP SCHEDULES *schedule_group_name*`
`CANCEL JOBS FOR SCHEDULES *schedule_group_name*`

**Comment by miretskiy** [comment]
The more I think about this feature.. the more I'm not sure we actually need it.
The way it's implemented now (with select statement) -- user can select 1 or more schedules to pause.
not sure we need to make it more complex than that.

**Comment by mwang1026** [comment]
Chatted offline. Conclusion was to do https://github.com/cockroachdb/cockroach/issues/52930 instead. Closing.
