### ISSUE TITLE
cdc: primary key changes don't work with changefeeds

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#52796]
**Describe the problem**

Changefeeds do not properly detect and deal with primary key changes. It's not super obvious what the right behavior would be.

See https://github.com/cockroachdb/cockroach/pull/52235#pullrequestreview-467017877

Jira issue: CRDB-3918

**Comment by amruss** [comment]
Closing, this has been fixed for ahwile

**Comment by jayshrivastava** [comment]
Possibly fixed by https://github.com/cockroachdb/cockroach/commit/e6cf9084c8740320fe12b391a66d9f37d355ef7e.
