### ISSUE TITLE
Periodically collect and retain CPU profiles, and include them in the debug zip

### ISSUE THREAD

**Issue by tim-o** [cockroachdb/cockroach#52839]
**Is your feature request related to a problem? Please describe.**
This is a complement to #52815 and #52814. Collecting CPU profiles at a set interval, retaining them for a period, and including them in the debug zip would drastically cut down on the amount of time we need to spend troubleshooting intermittent problems.

The alternative is waiting for an issue to recur, and then collecting a profile live while the problem is happening. This isn't always practical or easy for clients to do.

Jira issue: CRDB-3907

**Comment by yuzefovich** [comment]
This has been addressed.
