### ISSUE TITLE
sql: statement_timeout should not be reset after implicit transaction retries

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#52845]
**Describe the problem**

`statement_timeout` is a session variable that is meant to place an upper bound on how long a query can execute. However, if a query is an implicit transaction and it retries automatically, then the `statement_timeout` is reset. This means that there is no way to limit how much time the database will spend on automatically retrying a query.

**To Reproduce**

```
root@:26257/defaultdb> select crdb_internal.force_retry('5s');
  crdb_internal.force_retry
-----------------------------
                          0
(1 row)
Time: 5.001589s

root@:26257/defaultdb> set statement_timeout = '1s';
SET
Time: 290µs

root@:26257/defaultdb> select crdb_internal.force_retry('5s');
ERROR: query execution canceled due to statement timeout
SQLSTATE: 57014
```

Although the last query returned with a timeout error, this result was not received until after 5 seconds elapsed -- that is, the duration specified in the `force_retry` function.

**Expected behavior**

The timeout error in the example above should be returned after 1 second.

**Additional context**
If there are problematic queries that are retried a lot (thousands of times), then the lack of a `statement_timeout` means that these queries could starve other normal queries.

**Comment by awoods187** [comment]
What a nice find Rafi! This seems like quite the surprise to the user that we would not respect the timeout. cc @solongordon for seeing if we can address this soon.
