### ISSUE TITLE
sql: resolve temporary schemas in ResolveSchemaByID

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#52904]
Right now, we don't have the means to figure out if a schema id corresponds to a temporary schema.
To do this, we'll have to something like storing temporary schema ids in the user's session data to be used for lookups later.

`ResolveSchemaByID` will panic if a temp schema id is being looked up currently.

**Comment by ajwerner** [comment]
https://github.com/cockroachdb/cockroach/blob/5202e581ade072831c31734931dda9dab3a2a59c/pkg/sql/catalog/resolver/resolver.go#L308-L312
