### ISSUE TITLE
jobs: rename `name` to `label` on schedules

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#52930]
"name" implies uniqueness but this is not currently true. 

User feedback also suggested users _do_ want a name they can use to control schedules. However this gets a bit weird when we create multiple schedules to do the requested task e.g. in BACKUP where we create a full and an incremental schedule: which one gets the user's supplied name? which one thus gets controlled if they later use that name?

Reframing the field as label removes the connotation of uniqueness which was incorrect and confusing, and thus gives us the option of applying the _same label_ to more than one schedule, such as in the full-and-incremental case above, so that a pause-by-label would pause both.

**Comment by mwang1026** [comment]
@dt i'm testing and it looks like this merged. good to close?

**Comment by dt** [comment]
yep
