### ISSUE TITLE
server: use registration endpoint from cockroach nodes

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#5295]
The node which is the leader of the first range should check for updates on the registration server once per 24 hour interval and output an upgrade warning to the logs.

The first range leader should also gossip a boolean indicating whether the cluster has been registered. Each node should then separately check the registration boolean in gossip and send node and store updates once per 24 hour interval to the registration service.

@petermattis assign this accordingly

**Comment by dt** [comment]
i'm tempted to add a call in `maybeGossipFirstRange` where we've already done the determination that we are the leader of the first range, but that violates separation of concerns a little. anyone have strong feelings?

**Comment by bdarnell** [comment]
I'd be fine with renaming `maybeGossipFirstRange` to something broader like `maybeRunFirstRangeTasks`, but I'd prefer to keep the registration logic itself out of the storage package. Maybe there should be a callback function in the `StoreContext`?

**Comment by dt** [comment]
over lunch last week, @tamird suggested we leave first range leader and gossip out of it and just use a CPut to ensure at-most-one node checks for updates -- any opinions?

**Comment by bdarnell** [comment]
Doing it with CPut sounds fine to me.
