### ISSUE TITLE
roachprod error "Invalid base64: "ssh-rsa AAAAB..."

### ISSUE THREAD

**Issue by mgoddard** [cockroachdb/cockroach#52989]
While using **roachprod** to set up a cluster, I encountered the error message shown above.  I realize that I had installed version 2.x of the AWS CLI, and that caused the issue but, after applying the change shown below, I was able to get the cluster running and finish my demo.

```
diff --git a/pkg/cmd/roachprod/vm/aws/keys.go b/pkg/cmd/roachprod/vm/aws/keys.go
index 59fb9d128e..e02678c3ce 100644
--- a/pkg/cmd/roachprod/vm/aws/keys.go
+++ b/pkg/cmd/roachprod/vm/aws/keys.go
@@ -65,7 +65,7 @@ func (p *Provider) sshKeyImport(keyName string, region string) error {
                "ec2", "import-key-pair",
                "--region", region,
                "--key-name", keyName,
-               "--public-key-material", string(keyBytes),
+               "--public-key-material", base64.StdEncoding.EncodeToString(keyBytes),
        }
        err = p.runJSONCommand(args, &data)
        // If two roachprod instances run at the same time with the same key, they may
```

I just wanted to record this somewhere in case it's helpful down the road.  I imagine there are other reasons why version 1.x of the AWS CLI is recommended, but I haven't yet encountered any of them.

**Comment by rail** [comment]
I believe this is fixed in v2 now. I used it recently and it worked fine.

The current help shows this now:

>        --public-key-material (blob)
>           The public key. For API calls, the text must be base64-encoded.  For
>           command line tools, base64 encoding is performed for you.
> 

So it should be automatically base64 encoded.

Please reopen if you see this again.

**Comment by rail** [comment]
Looks like we need to reopen this.
``` shell
 $ aws ec2 import-key-pair --region us-east-1 --key-name test-2 --public-key-material "$(cat ~/.ssh/id_rsa.pub)"
Invalid base64: SNIP

$ aws ec2 import-key-pair --region us-east-1 --key-name test-2 --public-key-material "$(cat ~/.ssh/id_rsa.pub | base64)"
{
    "KeyFingerprint": ".....",
    "KeyName": "....",
    "KeyPairId": "...."
}
```
