### ISSUE TITLE
ui: make the cluster health status more accurate

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#5303]
If two nodes in a 3-node cluster are down, no new stats can be committed to the time-series DB. At best, the admin UI can operate in a degraded mode with stale stats.

When the UI is in this degraded state, the health status in the UI header always says "healthy" with a green check mark. We should make this more accurate.

There are at least two approaches:
1. Update the `/_admin/v1/health` endpoint to return "degraded" or something similar.
2. In the UI, show a degraded state if the last updated time for its stats is before some cutoff, like 20 or 30 seconds ago.

**Comment by maxlang** [comment]
Note that the green checkmark is currently removed, partially for this reason.

This is similar to #3726

**Comment by mrtracy** [comment]
We can use the node liveness API for this information; that API gives the entire liveness table, which can be used to infer a cluster status.

**Comment by mrtracy** [comment]
@kuanluo This is the issue where I am trying to create a "breakout" table for the Node Totals on the cluster graphs page - that is, instead of just displaying "Total Nodes", we can give more detail when some nodes are suspect or down

**Comment by kuanluo** [comment]
@mrtracy 

Breakout | Breakout + Health indicator
----------|------------------
![image](https://cloud.githubusercontent.com/assets/1486483/24214003/9baf5846-0f0a-11e7-8909-69960deed9c6.png) | ![image](https://cloud.githubusercontent.com/assets/1486483/24214319/7d94eb7c-0f0b-11e7-8464-d7b1a1d15a7c.png)

Is the left image what you were thinking about? It'd be cool to know the overall health of the cluster when nodes go down. The light gives a sense of overall sense of security when something might be  wrong. I remember us talking about the "fuzziness" of the healthy state, perhaps it's worth a discussion on how we approach this.

**Comment by spencerkimball** [comment]
@mrtracy is this done now? Could you close the issue?
