### ISSUE TITLE
ui: don't access SQL event log on every page hit

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#5304]
It looks like `/_admin/v1/events` is being hit for every admin UI page. It should only be hit when you view the events page.

Aside from generating unnecessary load, this causes 2-second delays with every page hit when 2 nodes in a 3-node cluster are down. While I'm modifying the KV operations to return potentially stale data, I don't yet have a way to do the same with the event log (all SQL operations hang when we don't have a quorum).

Along with my KV changes, removing the constant hits to the event log will make user experience in a degraded cluster as good as it can be with our current technical constraints.

**Comment by maxlang** [comment]
Already fixed by @cuongdo in #5519
