### ISSUE TITLE
kvserver: historical reads after clearrange incorrect

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#53047]
ClearRange destroys history so a historical read after a ClearRange is incorrect. ClearRange's API comment says that it bumps the GCThreshold to prevent such incorrect reads and it did indeed do so when it was added, but it looks like that may have gotten lost in subsequent changes.

**Comment by mwang1026** [comment]
Still an issue? And what calls ClearRange where this would be an issue?

**Comment by ajwerner** [comment]
This is still an issue but I think it's duplicated. I don't believe that ClearRange has bumped the GCThreshold since range merges became a thing.

**Comment by ajwerner** [comment]
Duplicates https://github.com/cockroachdb/cockroach/issues/31563.
