### ISSUE TITLE
ui: mirror event log entries to a log file

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#5306]
If we have loss of quorum (e.g. 2 nodes in a 3 node cluster are down), there's no way to view the event log. That's unfortunate, because the event log could hold clues that would help bring the downed nodes back up.

Event log entries are likely to be low frequency. So, when we insert into `EventLog`, we should also mirror that information into a local log file.

**Comment by mrtracy** [comment]
Is it appropriate to dump this to the console log, or does it need to be a separate log?  The only concern I could see is PII.
