### ISSUE TITLE
sql:  Intervals don't have the nanosecond unit defined

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#53079]
I've been playing around with timestamps and intervals and came upon this while suggesting an update to our docs:

```sql
# Convert milliseconds since epoch to timestamp if it's a string
SELECT TIMESTAMP 'epoch' + ('1597868048960'::float/1000)::interval;
SELECT TIMESTAMP 'epoch' + ('1597868048960'::INT8) * '1 ms'::interval;
SELECT TIMESTAMP 'epoch' + ('1597868048960'::INT8) * '1 millisecond'::interval;
SELECT TIMESTAMP 'epoch' + ('1597868048960' || 'ms')::interval;
SELECT TIMESTAMP 'epoch' + ('1597868048960' || 'milliseconds')::interval;

# Convert microseconds since epoch to timestamp if it's a string
SELECT TIMESTAMP 'epoch' + ('1597868402212060'::INT8) * '1 μs'::interval;
SELECT TIMESTAMP 'epoch' + ('1597868402212060'::INT8) * '1 microsecond'::interval;
SELECT TIMESTAMP 'epoch' + ('1597868402212060' || ' μs')::interval;
SELECT TIMESTAMP 'epoch' + ('1597868402212060' || ' microseconds')::interval;
SELECT TIMESTAMP 'epoch' + ('1597868402212060'::float/1000000)::interval;
 
# Convert nanoseconds since epoch to timestamp if it's a string
SELECT TIMESTAMP 'epoch' + ('1597867950921292032'::INT8) * '1 ns'::interval; -- unknown unit "ns"
SELECT TIMESTAMP 'epoch' + ('1597867950921292032'::INT8) * '1 nanosecond'::interval; --  unknown unit "nanosecond"
SELECT TIMESTAMP 'epoch' + ('1597867950921292032' || ' ns')::interval;  -- unknown unit "ns"
SELECT TIMESTAMP 'epoch' + ('1597867950921292032' || ' nanoseconds')::interval; -- unknown unit "nanoseconds"
SELECT TIMESTAMP 'epoch' + ('1597867950921292032'::float/1000000000)::interval;
```

We should add nanoseconds into our casting from string into intervals.

**Comment by BramGruneir** [comment]
@solongordon for triage

**Comment by otan** [comment]
nanosecond resolution is not support in any time types (in both PSQL/CockroachDB)
microseconds is the max resolution.

**Comment by BramGruneir** [comment]
Ah, I see, we cut it off:

```sql
root@127.0.0.1:56504/defaultdb> SELECT TIMESTAMP 'epoch' + ('1597867950921292032'::float/1000000000)::interval;
              ?column?
------------------------------------
  2021-05-14 20:12:30.921292+00:00
(1 row)

Time: 521µs
```

A shame.  Seems strange considering we do a ton of work in ns internally.  

Maybe we should consider adding it.

**Comment by otan** [comment]
i think we'd run into some ORM compat problems pretty quickly there.
AFAICT, it was there in 19.1-ish but we got rid of it towards a later release.

**Comment by otan** [comment]
also some times would need an encoding change, and so this change would be pretty gnarly.

**Comment by BramGruneir** [comment]
If we leave the default at Timestamp(6) but allow one to specify
timestamp(9), I don't think it would be that gnarly.

And yes, you are correct, it was in 19.1.  It's just a shame that we can't
represent our internal timestamps as a sql timestamp data type.  But then
again, it's probably best to make a new type that includes the logical part
too.

**Comment by solongordon** [comment]
I'm closing this for now due to the Postgres incompatibility.
