### ISSUE TITLE
jepsen test failed

### ISSUE THREAD

**Issue by logic-jin** [cockroachdb/cockroach#53108]
when take the jepsen consistency test, cockroach is failed.
I read the paper in (https://www.cockroachlabs.com/blog/cockroachdb-beta-passes-jepsen-testing/). The Paper claims that CockroachDB Beta Passes Jepsen Testing.

**Observed performance**
the _comments_ test is failed, running at least ten jepsen _commetns_ tests.

**environment**
cockroachDB's version is cockroach-v20.1.4.linux-amd64 and cockroach-v19.2.9.linux-amd64
jepsen's version is the master branch of (https://github.com/jepsen-io/jepsen/tree/master)
Server OS: Linux/Ubuntu16.04

**jepsen test script**
 Jepsen full.sh script context is the following :

lein do clean, run test \
  --tarball file:///home/vagrant/cockroach.tgz \
  --username vagrant \
  --password vagrant \
  --nodes-file ./nodes \
  --test comments \
  --nemesis none \
  --test-count 10 \
  --time-limit 600 \
  --concurrency 30 \
  --recovery-time 25 \
  --os ubuntu

**Requested resolution**

I want to know the reason why I can't pass the comments test, because of HLC？
The CockroachDB amount of clock offset that can be tolerated is configurable. If it was set 250ms, does the probability of error decrease?

Select all that applies:

- I mostly seek information: clarification.

**Comment by jordanlewis** [comment]
Not enough info here to help. Please provide concrete repro steps, what you expect, and what you got.
