### ISSUE TITLE
stability: restarted node spits complaints about replicaID moving backwards

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#5314]
build sha: 4839bab

scenario:
* 4 nodes with 4 photos apps
* node 0 segfaulted (not the point of this issue, this is #5311)
* stopped nodes 1-3 manually. node 3 was the last one so was shutdown after reaching the hard shutdown time
* restarted all 4 nodes
* nodes 0-2 were mostly happy
* node 3 started complaining about replicaID moving backwards.

log for node 3 after restart:
```
I160316 19:08:34.288592 cli/start.go:133  [build] alpha.v1-1086-g4839bab @ 2016/03/16 13:05:23 (go1.6)
I160316 19:08:34.288662 server/context.go:265  1 storage engine initialized
I160316 19:08:34.288707 cli/start.go:147  starting cockroach node
W160316 19:08:34.290895 gossip/gossip.go:898  not connected to cluster; use --join to specify a connected node
I160316 19:08:34.294412 storage/engine/rocksdb.go:118  opening rocksdb instance at "/mnt/data"
I160316 19:08:34.296515 gossip/gossip.go:924  starting client to ec2-54-209-133-121.compute-1.amazonaws.com:26257
I160316 19:08:35.298487 gossip/gossip.go:924  starting client to ec2-54-209-69-52.compute-1.amazonaws.com:26257
I160316 19:08:37.006046 gossip/client.go:84  closing client to node 2 (ec2-54-209-69-52.compute-1.amazonaws.com:26257): gossip/client.go:182: stopping outgoing client to node 2 (ec2-54-209-69-52.compute-1.amazonaws.com:26257); already have incoming
I160316 19:08:37.674764 server/node.go:363  initialized store store=4:4 ([]=/mnt/data): {Capacity:31564754944 Available:29116641280 RangeCount:0}
I160316 19:08:37.677836 server/node.go:279  node ID 4 initialized
I160316 19:08:37.678229 storage/stores.go:282  read 3 node addresses from persistent storage
I160316 19:08:37.678737 server/node.go:483  connecting to gossip network to verify cluster ID...
I160316 19:08:37.678971 server/node.go:504  node connected via gossip and verified as part of cluster "f071ce6a-75ea-4096-ae66-a79c164f924d"
I160316 19:08:37.679251 server/node.go:328  [node=4] Started node with [[]=/mnt/data] engine(s) and attributes []
I160316 19:08:37.679533 server/server.go:330  starting https server at ip-172-31-49-146:8080
I160316 19:08:37.680781 server/server.go:331  starting grpc/postgres server at ip-172-31-49-146:26257
I160316 19:08:37.693258 server/status/runtime.go:140  runtime stats: 61 goroutines, 5.42MiB active, 0.00cgo/sec, 0.00/0.00 %(u/s)time, 0.00 %gc (3x)
E160316 19:08:38.113455 storage/store.go:1814  error handling raft message: storage/replica.go:304: replicaID cannot move backwards
E160316 19:08:38.113565 storage/store.go:1814  error handling raft message: storage/replica.go:304: replicaID cannot move backwards
E160316 19:08:40.212993 storage/store.go:1814  error handling raft message: storage/replica.go:304: replicaID cannot move backwards
E160316 19:08:40.213673 storage/store.go:1814  error handling raft message: storage/replica.go:304: replicaID cannot move backwards
E160316 19:08:41.812878 storage/store.go:1814  error handling raft message: storage/replica.go:304: replicaID cannot move backwards
E160316 19:08:41.813643 storage/store.go:1814  error handling raft message: storage/replica.go:304: replicaID cannot move backwards
E160316 19:08:43.512285 storage/store.go:1814  error handling raft message: storage/replica.go:304: replicaID cannot move backwards
```

Full logs for all nodes: (searching for `[build]` is a good way to find the start time of the process)
[node0.log.parse.txt](https://github.com/cockroachdb/cockroach/files/176716/node0.log.parse.txt)
[node1.log.parse.txt](https://github.com/cockroachdb/cockroach/files/176717/node1.log.parse.txt)
[node2.log.parse.txt](https://github.com/cockroachdb/cockroach/files/176719/node2.log.parse.txt)
[node3.log.parse.txt](https://github.com/cockroachdb/cockroach/files/176718/node3.log.parse.txt)

**Comment by mberhault** [comment]
nodes are currently shutdown with `/mnt/data` intact.
I can backup the rocksdb storage before wiping them, but I'll wait a few hours before doing that anyway

**Comment by mberhault** [comment]
data and logs backed up on each node.
naming scheme: `/mnt/data.5314` and `~/logs.5314` after the issue number.

**Comment by tschottdorf** [comment]
The log indicates that this node is receiving Raft messages from an out-of-date replica. I'll check the logs to find out more. I don't think they're heartbeats (because we would drop them earlier without the error), so likely those were appends (though we should do a better job at logging them; at least the group that they're for).

**Comment by tschottdorf** [comment]
Was this one you (from node0.log.parsed)?

```
icit: false" id=680cb62f key=/Table/53/2/""/Wed Mar 16 18:15:46 UTC 2016/0 rw=true pri=0.02010991 iso=SERIALIZABLE stat=ABORTED epo=2 ts=1458152146.244746273,1 orig=1458152146.244746273,1 max=1458152146.236913335,1 failed; record not present
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x6d1446]

        ??:0 +0x6d
github.com/cockroachdb/cockroach/storage/engine.(*rocksDBIterator).Seek(0xc8465534a0, 0xc82996fd80, 0x10, 0x20, 0x0, 0xc800000000)
        /go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:634 +0x421
github.com/cockroachdb/cockroach/storage/engine.MVCCIterate(0x7f15818a6400, 0xc82028bd40, 0xc82996fd80, 0x10, 0x20, 0xc82996fda0, 0x10, 0x20, 0x0, 0x0, ...)
```

**Comment by tschottdorf** [comment]
maybe I'm wrong about the heartbeats - we're not actually filtering them out if we have a replica and the replicaID is stale as far as I can tell. We got 2 of them every 2 seconds, but only for ~20s because then the server was shut down. The cluster was also relatively troubled before - I don't know the specifics, but the Raft queues were bursting for a while before the node was shut down. The other nodes don't have much interesting news - node0 wasn't restarted (had panick'ed before, see above), node1 seems happy, same for node2, and we know about node3 (it's raft queue fills up to the brink).
Possible we just had an old Raft group sitting around on one of the other nodes which heartbeat us. I'm adding some more logging.

**Comment by mberhault** [comment]
the earlier crash was from #5311. I didn't wipe in-between. The node that segfaulted (0) is different from the one that complained about backwards replicaID. doesn't mean there's no correlation though.

**Comment by tschottdorf** [comment]
Ok, let's see whether this happens again, https://github.com/cockroachdb/cockroach/pull/5334.
