### ISSUE TITLE
telemetry: multi-tenant awareness

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#53188]
**Describe the problem**

Standalone SQL servers do not report telemetry. Even if they did, the backend
collecting telemetry has no notion of tenancy, so it would lump all tenants on
a physical cluster together.

**Expected behavior**

In a standalone SQL server, all telemetry should be reported with a reference
to the tenant ID (in addition to the cluster ID). The collector infrastructure
should record this telemetry and use it to disambiguate accordingly.

Jira issue: CRDB-3892

**Comment by tbg** [comment]
Please refer to https://github.com/cockroachdb/cockroach/issues/53188 instead, which has more details.

**Comment by tbg** [comment]
There's CRDB work and work in our telemetry collector infra that is necessary here. I'll be brief on the latter: incoming payloads will start having a tenantID in them and this needs to be properly understood and saved by the telemetry collector.

On the CRDB side, the code that collects the reporting info is

https://github.com/cockroachdb/cockroach/blob/94a429b124c953285a69c948c7d9666252089a04/pkg/server/updates.go#L280-L282

and it is sent out in

https://github.com/cockroachdb/cockroach/blob/94a429b124c953285a69c948c7d9666252089a04/pkg/server/updates.go#L418-L464

which in turn is called periodically from `maybeReportDiagnostics`:

https://github.com/cockroachdb/cockroach/blob/94a429b124c953285a69c948c7d9666252089a04/pkg/server/updates.go#L80-L111

There is unfortunately quite a bit of refactoring necessary. All of this sits on `*Server` and assumes both access to a `*Node` (which the tenant does not have) and the sql server (which the tenant does have). The reporting loop is driven from the main update loop (which the tenant should not have); in short, the existing code is already fairly ad-hoc and thus does not lend itself easily to porting over.

There are two possible approaches here:

1. We decide that the problem is that the tenant sql server is not starting a `*Server`, and so we make it possible for it to start one
2. We decide that the problem is that the reporting code isn't reusable enough, refactor it, and add a reporting loop to the tenant start code.

I believe that the second option is more realistic and, ultimately, more beneficial in the short term. `*Server` is historically the combined SQL and KV server with little regard for clean separation. A degree of separation was achieved when we had to allow for a stand-alone SQL server, but it would be larger project requiring expert attention. I think we would want to extract a `kvserver.Server` which houses many of the [fields that clearly don't apply to SQL](https://github.com/cockroachdb/cockroach/blob/32307340f401a2449d2d98f6f89a4efff6f20172/pkg/server/server.go#L118-L165) and then take all of the auxiliary ingredients to starting a node (elaborate logging, certificate, join sequence management, the UI) and make them cleanly optional for the case of a SQL node. There would be many additional design considerations if we wanted to do so and, without getting into more detail, I think it would leave us with two bad options, which is either working on this for quite some time until telemetry appears on sql servers, or doing a crappy job duct taping it all together. So I advise against option 1 at this point.

Instead, with option 2, we basically improve the telemetry collection code and make it reusable by both the existing `*Server` and the start-sql code. This is something we want anyway, so it can be seen as paying down some tech debt while we have to touch the code anyway. The way this could look like is the following:

```go
package diagnostics

type Source interface {
  Populate(*diagnosticspb.DiagnosticsReport)
  OnSent() // allows sources to clear counters
}

type Reporter {
  sources []Source
} 

func NewReporter(sources ...Source) *Reporter {
  return &Reporter{sources: sources}
}

// Run populates a diagnostics report from its sources and sends it.
// If sending is successful, OnSent() will be invoked on all sources.
func (r *Reporter) Run(ctx) {
  var report DiagnosticsReport
  for _, source := range sources {
    Populate(&report)
  }
  send(r) // TODO
}
```

There's a bit more work too. The reporting is based on the cluster ID, which I don't think tenants know, though they can easily obtain it from the kv connector (with changes to said connector to pass through the cluster ID). Alternatively we could provide a "cluster identity" via the environment; that's up to us to decide.

Either way, with this tool added to the library, we can use it from `*Server` and then also add a simple loop to the start-sql code near

https://github.com/cockroachdb/cockroach/blob/57fd55b00d935440c8b8064e4980a70be3833253/pkg/server/testserver.go#L736

**Comment by andy-kimball** [comment]
@knz, do you have any comments on the approaches that Tobias suggested? I'm going to need to find someone to do this work for our January release, so hopefully we find an approach that is not too obtrusive or difficult.

**Comment by knz** [comment]
yes the approach Tobias mentions is realistic and feasible within the time frame.

**Comment by andy-kimball** [comment]
1. What is the "kv connector" and how do we get the cluster ID from it? Which KV node would it connect to?
2. Do you think we should still fill out `diagnosticspb.NodeInfo` for tenant nodes where we can (e.g. Hardware, Os, etc)? However, I don't think we have a way to get `Locality`. I assume `NodeID`, `Bytes`, `KeyCount`, etc. would all be zero.

[Here is a WIP branch](https://github.com/cockroachdb/cockroach/compare/master...andy-kimball:reporter) where I factor out the diagnostics reporting code, so that I could see what kinds of dependencies it has. What's your initial reaction to that approach? What kinds of tricky problems am I likely to face if I go with something like that?

**Comment by tbg** [comment]
> What is the "kv connector" and how do we get the cluster ID from it? Which KV node would it connect to?

1. kvtenant.Connector and it basically uses the `--kv-addr` flag.
2. that depends, is there anything in there we care about? HardwareInfo, OSInfo, BuildInfo, Uptime are the only fields I see that we could potentially populate, but would we care until we have external multi-tenancy deployments? https://github.com/cockroachdb/cockroach/blob/ab161ab87a814449e683a5af770e6ebabb9f1d22/pkg/server/diagnosticspb/diagnostics.pb.go#L73-L85
    Feels that we should populate it if it falls into place naturally, but not bend over backwards. What seems more important is to work towards a split between SQL and KV telemetry, in which case it would make sense to strip down NodeInfo and introduce an extension of it, KVNodeInfo (and, if ever necessary, SQLNodeInfo). None of that seems pressing right now.
3. Maybe I don't understand the question correctly, but I think `Reporter` is intended as a long-lived object. I have never touched any of this code but it looks like `Reporter` mainly holds on to references into a bunch of subsystems which it uses to populate diagnostics on an interval. I looked at your WIP branch and it looks like the same is true for your refactored `Reporter`.

I don't anticipate any tricky problems here, just that it will take a bit of elbow grease.

**Comment by vy-ton** [comment]
Is this still a valid issue? The product telemetry tables all have a tenant id field and we can distinguish between tenant and host clusters.

**Comment by tbg** [comment]
I'm not sure, sounds like it has been addressed then but I'm not in the loop.
