### ISSUE TITLE
sql: "last error" field in statement stats is lost from telemetry

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#53191]
**Describe the problem**

The "last error" payload of statement statistics is mistakenly and unhelpfully always scrubbed away from telemetry, which negates its usefulness.

The resulting string is always "`<redacted>`" no matter how much error payload was actually suitable for reporting.

**This is a regression** - the code originally properly redacted errors and enabled more details to be reportable, and this logic was lost during a refactor.

**Details***

Background: The statement stats collect the last error encountered on a given statement fingerprint, in the "last error" field of some data structures.

1. Originally when this mechanism was introduced in #14181, the raw error string was stored in the struct, but was not reported to telemetry. (field `last_error` in `roachpb.StatementStatistics`)
2. When statement stats initially were reported to telemetry in #22693, code was added to split the error string in two **at the time it is initially stored**: in-clear for display in the UI, and redacted for telemetry.  (2nd field `last_error_redacted` in `roachpb.StatementStatistics`)

   **The redaction must be performed upfront** because it is done by looking at the internal structure of the `error` object to distinguish sensitive and non-sensitive data.

3. Later during a refactoring in #33020, the authors did not appreciate that **the redaction must be performed upfront** and  instead "simplified" the code to only store 1 error string in the struct (`last_error` in `roachpb.SensitiveInfo`), and only during telemetry reporting apply the `errors.Redact()` function **to the string**. 

   Alas, there is no information left in a string to distinguish sensitive and non-sensitive data, so `errors.Redact()` must conservatively consider the entire string as sensitive, and always produces the result `<redacted>` regardless of input.

**Solution**

The proper way forward is to restore the original logic: store a different field side-by-side with the "full error", containing the redacted bit (or redactable, as per the new `redact` package). Then use that during telemetry reporting.

Jira issue: CRDB-3891

**Comment by jordanlewis** [comment]
@awoods187 does the product team need the information?

**Comment by solongordon** [comment]
Per @awoods187 this would be nice to know but not urgent.
