### ISSUE TITLE
Node unavailable due to GC pause

### ISSUE THREAD

**Issue by heidawei** [cockroachdb/cockroach#53192]
**Is your feature request related to a problem? Please describe.**
My CockroachDB cluster has five nodes, the TPS is very low, only 50~100 TPS. but one CRDB node unavailable due to GC pause, It's very weird, After repeated research, I think I found the problem。
TS server pruneTimeSeries, It will call delete range, However, when the scope to be deleted involves several gigabytes of data, the go's GC pressure will increase sharply, resulting in a long-term process pause, which will lead to load balancing of other nodes. At the same time, a lot of empty ranges are generated due to large-scale deletion of data, which triggers range merge, which in turn triggers the compaction of RocksDB, because clear range will trigger this active comparison process.

![image](https://user-images.githubusercontent.com/11207613/90890316-4fdea600-e3ec-11ea-9ba3-f25f1ac0bb0a.png)

![image](https://user-images.githubusercontent.com/11207613/90890359-6553d000-e3ec-11ea-8a81-300d24223288.png)

![image](https://user-images.githubusercontent.com/11207613/90890449-9f24d680-e3ec-11ea-9b53-5c7cd8d6fe6b.png)

![image](https://user-images.githubusercontent.com/11207613/90890462-a5b34e00-e3ec-11ea-8f1e-8d250bff8025.png)

Careful analysis of my own business logic will not generate a large number of memory objects that can affect GC pause in a short period of time. I analyzed the code and log that triggered the comparison and confirmed that the deletion of monitoring information caused the accident。

![image](https://user-images.githubusercontent.com/11207613/90890718-1a868800-e3ed-11ea-8fce-e6a391cbe9f4.png)

**Describe the solution you'd like**

I think the key to the problem lies in the API delete range, which requires that deleted keys be returned. In this way, when there are many keys involved in the scope to be deleted, it will occupy golang to create a large number of objects. In fact, we don't need it to return the deleted key at any time. For example, we can clean up the monitoring data. In this way, we can avoid creating a large number of objects and improve this situation.

Or we can limit the maximum amount of data to be deleted each time, and batch completion of this work should also delay the pressure on GC

**Describe alternatives you've considered**

**Additional context**

**Comment by heidawei** [comment]
@petermattis  Yes，DeleteRangeRequest.ReturnKeys = false, I noticed this detail later， From the perspective of monitoring, it is cyclical。
![image](https://user-images.githubusercontent.com/11207613/90995169-b979d280-e5ed-11ea-836a-f36b844af936.png)

These comparison queues are absolutely not generated by the business, and the traffic and logic of the business will not cause such problems。

Although DeleteRangeRequest.ReturnKeys = false, I still need to do golang escape analysis on deleteRange to confirm that MVCCScan will apply for a large number of objects on the heap。

**Comment by heidawei** [comment]
@petermattis  I write a very sample code to do golang escape analysis.
`type KeyValue struct {`
`	Key    []byte`
`	Value  []byte`
`}`
`
type Key  []byte`
`
func MVCCScan() []KeyValue {`
`	const l = 1024`
`	data := make([]byte, l)`
`       for i := 0; i < l/16; i ++ {`
`		kvs[i] = KeyValue{`
`			Key:   data[offset: offset+8],`
`			Value: data[offset+8:offset+16],`
`		}`
`		offset += 16`
`	}`
`	return kvs`
`}`

`func DeleteRange(returnKeys bool) ([]Key, int64) {`
`	kvs := MVCCScan()`
`	var keys []Key`
`	if returnKeys {`
`		keys = make([]Key, len(kvs))`
`		for i := 0; i < len(kvs); i++ {`
`			keys[i] = kvs[i].Key`
`		}`
`	}`
`	return keys, int64(len(kvs))`
`}`

`func main() {`
`	keys, _ := DeleteRange(false)`
`	fmt.Println(keys)`
`}`

>  go build -gcflags '-m -l'           

> # test/golangEscape

> ./main.go:14:14: make([]byte, l) escapes to heap

> **./main.go:15:13: make([]KeyValue, l / 16) escapes to heap**

> ./main.go:31:14: make([]Key, len(kvs)) escapes to heap

> ./main.go:41:13: ... argument does not escape

> ./main.go:41:13: keys escapes to heap

**Comment by heidawei** [comment]
@petermattis  Now，I try to modify the TS GC params like this:
set cluster setting timeseries.storage.resolution_10s.ttl='72h';
set cluster setting timeseries.storage.resolution_30m.ttl='720h';

I will continue to observe the various indicators of the system after the TS GC threshold is modified

**Comment by petermattis** [comment]
@heidawei Ah, I see your point about `MVCCDeleteRange` internally making heap allocations. I've filed https://github.com/cockroachdb/cockroach/issues/53315 which notes three heap allocation inefficiencies in `MVCCDeleteRange`.

**Comment by heidawei** [comment]
@petermattis  After a week of continuous observation, there was no large GC pause, and the monitoring data of each node remained stable。

**Comment by mwang1026** [comment]
Closing since we're tracking on #53315
