### ISSUE TITLE
sql: return postgres error codes for some sql errors

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#5329]
E.g. allow user to recognized duplicate key errors, or other constraint violations.
There's a TODO in the code about it. Right now we always send one code, internal error: `XX0020`.
https://github.com/cockroachdb/cockroach/blob/e341de5cb433d91c29273c5f03e81f5111f41460/sql/pgwire/v3.go#L589

Probably the first error codes will be sent for #5328

**Comment by petermattis** [comment]
@nvanbenschoten I know you were doing work in this area. Is this done?

**Comment by nvanbenschoten** [comment]
Full Postgres error compatibility is far from being supported, but I don't think that was the goal here. For now, we have all of the [pgerrcodes](https://github.com/cockroachdb/cockroach/blob/master/sql/pgwire/pgerror/codes.go) in a generated Go file, and have a common pattern for using them. Certain codes are in-use to support situations where error compatibility was required for correct client-side behavior in the past, and if we run into future areas where we need specific error codes, the necessary changes are straightforward. I expect this will be the case for certain ORMs like [Hibernate](https://github.com/hibernate/hibernate-orm/blob/ec4f20a5fba79444dbd704f1305f961c339dd7d1/hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQL81Dialect.java#L399), which have more to learn from errors than the raw drivers do.

**Comment by spencerkimball** [comment]
@andreimatei iIs this still open? Could you close if necessary? I'm also removing this from the 1.0 milestone.

**Comment by andreimatei** [comment]
I guess enough has been done that this issue doesn't serve a purpose any more. There's definitely more error codes that we should be returning instead of the internal-error code though.
