### ISSUE TITLE
backupccl: shorten GC TTL of temporary system table used during cluster restore

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#53300]
Currently, cluster restore creates a temporary system table, and then drops it at the end of the restore. Before dropping the zone config of this temporary table should be reduced so that it can be quickly dropped.

Epic CRDB-8816

Jira issue: CRDB-3879

**Comment by stevendanna** [comment]
Fixed in https://github.com/cockroachdb/cockroach/pull/67936
