### ISSUE TITLE
cli: the sql shell should recognize the retryable txn status tag and display it to the user

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#5330]
Each response we send through pgwire has a txnStatus character. We introduced `'R'`, meaning that the txn is in state `RETRY_WAIT`. Our cli should understand this and change the prompt somehow, to indicate to the user that it's not business as usual. 
The prompt should probably understand the other codes too.

**Comment by spencerkimball** [comment]
Removing 1.0 milestone. @andreimatei could you update this with a priority label and any comments which further clarify in light of push txn queue, which lessens the probability of restarts? If you have an intention to get this done by 1.0, please assign it and re-add the 1.0 milestone.

**Comment by andreimatei** [comment]
This has been done; our prompt now displays the transaction status.
However that's done by issuing a `SHOW TRANSACTION STATUS` query, not by using the status code that's reported with pgwire messages. I wonder if there's a reason for that. @knz?

**Comment by knz** [comment]
The reason is that libpq swallows the codes and also we want to show the txn status also for the other states (error, notxn) where there's no pgwire code.
