### ISSUE TITLE
kv: re-enable time-bound iterators for KV requests

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#53348]
`EndTxnRequest`, `RefreshRangeRequest`, and `ResolveIntentRangeRequest` are all good use cases for time-bound iterators. In fact, at one point, all three requests applied min and max timestamp hints to their iterators. However, due to concerns about correctness, TBIs were disabled for these request types in https://github.com/cockroachdb/cockroach/pull/32313/commits/1eb3b2a62470bd3c3ee3f64f6c4118900961ec9f.

Since then, time-bounder iterators have been re-enabled in important bulk operations like ExportToSST (https://github.com/cockroachdb/cockroach/issues/43799) by pairing them with a normal iterator to resolve ambiguity related to MVCC metadata keys. This pairing is packaged up in the `MVCCIncrementalIterator` abstraction.

We should explore the use of `MVCCIncrementalIterator` for some of these request types again. When doing so, we'll need to keep in mind that `MVCCIncrementalIterator` may pessimize performance of scans that have a high intent/value ratio, so this may be more appropriate for some request types (e.g. `RefreshRangeRequest`) than others (e.g. `EndTxnRequest`).

**Comment by ajwerner** [comment]
I wonder to what extent this relates to #62585, at least in terms of the `MVCCIncrementalIterator` vs. the time-bound iterator (without the "sanity" iterator). IIRC the safety considerations related to ClearRange operations and potentially see a key which was shadowed by it and thus should not be visible. If the MVCC layer knew that there were no ClearRange operations which might be above any of the data being read, then it could avoid the sanity iterator, or perhaps, use that to decide whether or not to use a TBI.
