### ISSUE TITLE
update grafana-dashboards json files to match what is used by Cockroach Cloud

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/cockroach#53424]
**Describe the problem**

The *.json files for grafana-dashboards were last updated 2 years ago and may be out-of-date: 
https://github.com/cockroachdb/cockroach/tree/master/monitoring/grafana-dashboards
<img width="785" alt="Screen Shot 2020-08-25 at 2 40 09 PM" src="https://user-images.githubusercontent.com/58752716/91214409-05597400-e6e1-11ea-8c97-1216e8dd9eab.png">

They need to be compared to the ones currently being used by the SRE team for Cockroach Cloud and updated accordingly.

**Comment by notetook** [comment]
Are there any updates? I've requested this issue through portal of cockroach labs.

**Comment by thtruo** [comment]
We've updated our Grafana dashboard templates with an accompanying README to set up Grafana, so we'll go ahead and close this issue
https://github.com/cockroachdb/cockroach/tree/master/monitoring
