### ISSUE TITLE
bulkio: Telemetry for Changefeeds

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#53429]
We have very little telemetry on changefeeds today. It would be nice to have a better understanding of a few things:
- When and why they fail
- Throughput
- Lifetime of the changefeed

That way we can understand the difficulty of use and extent of use of the feature (we know when they are created, but nothing else really). Using telemetry, I feel like this is actually pretty hard unless we have each cluster send a daily "hi I'm here" and we can "count" active changefeeds. I'm very open to how we do that, but ultimately I just want to know how many are running at a given time, on what clusters, with what throughput.

Suggested metrics:
- Core vs. enterprise...?
- Failed changefeed (and reason)
- Canceled changefeed
- A "hi I'm alive" daily signal? Maybe we can send uptime and throughput for the day?
- Changefeed uptime -- is there a way to report this, say, every week OR when it's stopped? Or hits a milestone?
- Throughput (can we do this before a changefeed completes?)

**Comment by miretskiy** [comment]
I'm not a telemetry expert.. But, adding throughput, lifetime and probably anything time related is the domain of prometheus.  I'm going to add counters for start/fail/cancel for core and enterprise.

**Comment by mwang1026** [comment]
Thanks. And if you could check on what `create` actually tracks that'd be helpful. Per our conversation in slack it seems to be really really really high for what we think it might do (9000 changefeeds created per week across 11 clusters seems off)

**Comment by mwang1026** [comment]
@miretskiy thanks for merging. Can we get a 20.2 backport on this? Then I think we can close. Thanks
