### ISSUE TITLE
unique_rowid function for postgres?

### ISSUE THREAD

**Issue by jet10000** [cockroachdb/cockroach#53426]
I want to use cockroach's unique_rowid in postgres. Is there an open source implementation here?

**Comment by jordanlewis** [comment]
@jet10000, the implementation begins here: https://github.com/cockroachdb/cockroach/blob/2032f53cc5a7c0797c38984e315b2bf67835265c/pkg/sql/sem/builtins/builtins.go#L1731

You're free to use CockroachDB source code in ways that are permissible under our [LICENSE](https://www.cockroachlabs.com/docs/stable/licensing-faqs.html).
