### ISSUE TITLE
ui: statement diagnostic page blank on safari

### ISSUE THREAD

**Issue by sheaffej** [cockroachdb/cockroach#53425]
**Describe the problem**

When navigating to the diagnostics sub-tab on a statement from the Statements section, the "Activate Statement Diagnostics" content box w/ button appears for a fraction of a second, then disappears. This occurs on Safari version 13.1.2 (15609.3.5.1.3) on Mac 10.15.6, at least. And on both a 20.1.1 and 20.1.4 cluster. It was observed while working with a customer on a screen share.

**To Reproduce**

1. Using the latest Safari on a Mac, visit 20.1.x cluster's admin UI.
2. Navigate to the Statements page, and select any statement
3. Click on the Diagnostics sub-tab
4. Observe that the "Activate Statement Diagnostics" content is not visible, or is briefly visible then disappears
5. Repeat the steps above on Chrome, and observe the content is visible as expected.

**Expected behavior**
Same behavior between Chrome and Safari

**Environment:**
 - CockroachDB version: both 20.1.1 or 20.1.4
 - Client app Safari on Mac 13.1.2

**Additional context**
Customer cannot use their preferred browser on Mac.

Jira issue: CRDB-3866

**Comment by jordanlewis** [comment]
Sorry this never got looked at, if it's still a thing (I hope not!) please re-open
