### ISSUE TITLE
bulkio: File storage telemetry

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#53431]
It would be nice to know what types of file storage users interact with on our features, especially as we're adding `userfile`. This would also help us validate the userfile user story -- that people want an easy way to get data the cluster can use.

Suggested metrics:
- userfile upload
- userfile list
- userfile delete
- IMPORT from userfile (and while we're at it, which file storage they use)
- BACKUP / RESTORE file storage usage

Ideally, we could tie that into issues they run into as well -- for example we've heard customers struggle with setting up NFS.

**Comment by adityamaru** [comment]
We decided to just add userfile telemetry for now as we are interested in adopters of the new feature. Should we close this @mwang1026?

**Comment by mwang1026** [comment]
Yup! Thanks. Closing per above PR
