### ISSUE TITLE
acceptance: add repair test

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#5345]
This test should do the following:
1 - start up a 4 node cluster, run the bank test against it the whole time and turn on the consistency checker
2 - kill the oldest node
3 - wait until all ranges are repaired
4 - start a new node 
5 - goto step 2

**Comment by jordanlewis** [comment]
This seems to be done? c.f. #6277

**Comment by petermattis** [comment]
We have a larger number of tests around rebalancing and up-replication as well as cluster-level testing. I don't think there is anything specifically actionable here.
