### ISSUE TITLE
sql: benchmark interleaved tables

### ISSUE THREAD

**Issue by lucy-zhang** [cockroachdb/cockroach#53455]
#52009 is a proposal to deprecate and disable interleaved tables. To determine whether to move forward with this, we need to investigate the performance impact of the migration for workloads that supposedly take advantage of interleaving (i.e., using interleaved joins or fast-path deletes).

In the short term, for 20.2, the first step in the potential deprecation process is to add a cluster setting to disable interleaving (#52731). We need to prioritize this investigation to determine whether we should start this deprecation process.

**Comment by asubiotto** [comment]
Jordan says:

The plan should be that we need to benchmark two major things:
1) Interleaved table join versus just an arbitrary join when the tables are not interleaved which presumably would be a merge join.
2) Delete cascade. The idea is that if you have a row that exists across multiple interleaved tables, there is a fast path that is used when you delete cascade. Compare that versus ordinary deletes that do not have the fast path available.
    - Customer C has a tool that they use to benchmark these fast-path deletes that might be interesting to use.

You'll probably want a string type to vary the size of the column.

[Bram's suggestions](https://cockroachlabs.slack.com/archives/CC5CX8EKE/p1597412218328900?thread_ts=1597365170.328400&cid=CC5CX8EKE)

**Comment by yuzefovich** [comment]
The performance of single row DELETEs from the outermost tables (old is with interleaved, new is without interleaved):
```
name                          old ops/s  new ops/s  delta
deletebench-100-2-throughput   208 ± 0%   225 ± 0%   ~     (p=1.000 n=1+1)

name                          old ms/s   new ms/s   delta
deletebench-100-2-P50         6.30 ± 0%  6.80 ± 0%   ~     (p=1.000 n=1+1)
deletebench-100-2-Avg         4.70 ± 0%  4.20 ± 0%   ~     (p=1.000 n=1+1)


name                          old ops/s  new ops/s  delta
deletebench-100-3-throughput  5.20 ±10%  2.38 ± 5%   -54.33%  (p=0.000 n=9+8)

name                          old ms/s   new ms/s   delta
deletebench-100-3-P50          246 ± 9%  1097 ±16%  +345.90%  (p=0.000 n=9+10)
deletebench-100-3-Avg          189 ± 7%   257 ±11%   +35.98%  (p=0.000 n=9+9)


name                           old ops/s  new ops/s  delta
deletebench-1000-2-throughput  50.1 ± 0%  47.1 ± 0%   ~     (p=1.000 n=1+1)

name                           old ms/s   new ms/s   delta
deletebench-1000-2-P50         30.4 ± 0%  31.5 ± 0%   ~     (p=1.000 n=1+1)
deletebench-1000-2-Avg         18.9 ± 0%  19.9 ± 0%   ~     (p=1.000 n=1+1)


name                           old ops/s   new ops/s   delta
deletebench-1000-3-throughput   0.00        0.00        ~     (all equal)

name                           old ms/s    new ms/s    delta
deletebench-1000-3-P50         29.0k ± 0%  31.1k ± 0%   ~     (p=1.000 n=1+1)
deletebench-1000-3-Avg         22.5k ± 0%  25.8k ± 0%   ~     (p=1.000 n=1+1)


name                           old ops/s  new ops/s   delta
deletebench-5000-2-throughput  10.7 ± 0%    9.9 ± 0%   ~     (p=1.000 n=1+1)

name                           old ms/s   new ms/s    delta
deletebench-5000-2-P50          122 ± 0%    126 ± 0%   ~     (p=1.000 n=1+1)
deletebench-5000-2-Avg         92.3 ± 0%  100.7 ± 0%   ~     (p=1.000 n=1+1)
```
How to read this: first number is the ratio between the levels (i.e. for each parent row there are 100 child rows), second number is the number of levels. In these runs I had 100 rows in the outermost tables, and all of them were deleted (meaning the whole hierarchy of tables is cleared), and there was no concurrency.

**Comment by yuzefovich** [comment]
Here are the benchmarks of interleaved join (old) against merge join (new):
```
name                     old ops/s  new ops/s  delta
join-2-1-0.1-throughput   361 ± 0%   414 ± 5%  +14.82%  (p=0.008 n=5+5)

name                     old ms/s   new ms/s   delta
join-2-1-0.1-P50         3.40 ± 0%  2.90 ± 0%  -14.71%  (p=0.000 n=5+4)
join-2-1-0.1-Avg         2.60 ± 0%  2.40 ± 0%   -7.69%  (p=0.000 n=5+4)


name                     old ops/s  new ops/s  delta
join-2-1-0.5-throughput   150 ± 2%   187 ± 2%  +24.98%  (p=0.008 n=5+5)

name                     old ms/s   new ms/s   delta
join-2-1-0.5-P50         8.44 ± 5%  6.80 ± 0%  -19.43%  (p=0.016 n=5+4)
join-2-1-0.5-Avg         6.56 ± 4%  5.00 ± 0%  -23.78%  (p=0.000 n=5+4)


name                     old ops/s  new ops/s   delta
join-3-1-0.1-throughput  14.4 ± 0%  442.6 ± 4%  +2973.89%  (p=0.016 n=4+5)

name                     old ms/s   new ms/s    delta
join-3-1-0.1-P50         88.1 ± 0%    2.7 ± 6%    -96.89%  (p=0.008 n=5+5)
join-3-1-0.1-Avg         65.0 ± 0%    2.2 ± 3%    -96.68%  (p=0.008 n=5+5)


name                     old ops/s  new ops/s    delta
join-3-1-0.5-throughput  3.20 ± 0%  214.62 ± 1%  +6606.87%  (p=0.016 n=4+5)

name                     old ms/s   new ms/s     delta
join-3-1-0.5-P50          359 ± 3%       6 ± 0%    -98.33%  (p=0.000 n=5+4)
join-3-1-0.5-Avg          319 ± 0%       4 ± 0%    -98.68%  (p=0.008 n=5+5)


name                     old ops/s  new ops/s  delta
join-3-2-0.1-throughput  8.20 ± 0%  6.76 ± 1%  -17.56%  (p=0.008 n=5+5)

name                     old ms/s   new ms/s   delta
join-3-2-0.1-P50          143 ± 0%   168 ± 0%  +17.67%  (p=0.016 n=4+5)
join-3-2-0.1-Avg          117 ± 0%   151 ± 0%  +28.62%  (p=0.008 n=5+5)


name                     old ops/s  new ops/s  delta
join-3-2-0.5-throughput  1.80 ± 0%  1.50 ± 0%  -16.67%  (p=0.008 n=5+5)

name                     old ms/s   new ms/s   delta
join-3-2-0.5-P50          604 ± 0%   705 ± 0%  +16.66%  (p=0.008 n=5+5)
join-3-2-0.5-Avg          570 ± 0%   671 ± 0%  +17.65%  (p=0.016 n=5+4)
```
How to read this:
- the first number is the number of levels (2 means we have `parent` and `child` tables, 3 means we have `parent`, `child`, and `grandchild` tables)
- the second number is the level of the table from the right side of the join (on the left we always use `parent`)
- the third number is the fraction of rows from `parent` table that are selected by the filter (that is pushed into the scan).

**Comment by yuzefovich** [comment]
We decided to simulate a “fake cascade” operator which, rather than relying on the behavior of CASCADE action of the foreign keys, would issue separate DELETE queries. Namely, if we have 3 levels, than, instead of having just
```
DELETE FROM parent WHERE pid = $1;
```
and letting the cascades delete the rows from the child, we modify the schema to remove the foreign key constraint and issue two queries
```
DELETE FROM child WHERE pid = $1;
DELETE FROM parent WHERE pid = $1;
```
With this fake cascade operator, the performance of non-interleaved deletes seems to be on par with the interleaved fast-path. A more comprehensive writeup is [here](https://docs.google.com/document/d/1-a7sIVwD56bq1z2OUIl47-tmcQsIKrpL9xXyGbtOT9Q/edit?usp=sharing).

**Comment by saurik** [comment]
I am sadly unable to see any of the comprehensive write-ups, but I am curious if any thought was put into why you were able to make a benchmark that didn't improve performance when incentivized to show no improvement, but when the feature was added there were also benchmarks done and they showed improvement (and clearly enough to justify @richardwu building and including the feature).

https://www.richardwu.ca/papers/interleaved-table-joins.pdf

I feel like any comprehensive analysis here would have to start from an attempt to not only do some new benchmarks but come to a cohesive understanding of why prior benchmarks were flawed. (Maybe this was done and discussed in a meeting, or maybe it was part of the aforementioned comprehensive write-ups I am unable to access, but it just seems strange that this discrepancy wasn't mentioned here.)
