### ISSUE TITLE
util/metric: should use the server's HLC instead of `time` directly

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#5346]
See `var now = timeutil.Now` in `util/metric/metric.go` for a starting point.

**Comment by tschottdorf** [comment]
What's this about? The HLC isn't about ticking regularly, so if anything it should use the same physical clock the HLC does, but even then I don't see this making a lot of sense - seems fine the way it is now, using `timeutil.Now()`. Might be missing something.

**Comment by tamird** [comment]
This is from discussion in https://github.com/cockroachdb/cockroach/pull/5260. Yes, the intention was to use the same physical clock as the HLC, not the logical part. Sorry about the confusion.

**Comment by tschottdorf** [comment]
Oh, I see. I'd like to get rid of the globals, but it's going to be awkward.

**Comment by seiflotfy** [comment]
Would something like
```go
func physicalTime() time.Time {
	t := hlc.NewClock(hlc.UnixNano).PhysicalNow()
	return time.Time{}.Add(time.Duration(t))
}
```
do the trick?

**Comment by seiflotfy** [comment]
Wait to get the server's clock i'd have to pass it to functions such as NewHistogram, NewGauge etc...
right?

**Comment by tamird** [comment]
Yes, there is some plumbing required.

**Comment by seiflotfy** [comment]
Got it! On it then! Can I assign this to myself?

**Comment by tamird** [comment]
@seiflotfy unassigning since this seems to have fallen off your plate.

**Comment by Succo** [comment]
@tamird Hey I'd like to take a stab at this. I'm not sure I fully understand the issue, is there anything else to do than remplacing
```
var now = timeutil.Now
```
per 
```
var clock = hlc.NewClock(hlc.UnixNano)
var now = clock.PhysicalTime
```

**Comment by tamird** [comment]
@Succo unfortunately it's not so simple. See https://github.com/cockroachdb/cockroach/pull/6919#issuecomment-221872036

**Comment by Succo** [comment]
Ok, I see. I'll try to make it work then.

**Comment by Succo** [comment]
@tamird I have something that is working, by passing references to the global clock to `NewRate` and `NewHistogram`, I updated the functions calls in the whole code base, but I'm not sure how to implement that in gossip, where it uses rates but doesn't have any references to the global clock.

**Comment by tamird** [comment]
cc @d4l3k

**Comment by tamird** [comment]
@Succo ouch, I seem to have missed your last comment. You would have to pass a reference to the HLC into gossip's constructor.

**Comment by Succo** [comment]
@tamird thanks.

I've had it working (or at least building and passing test), but my branch got way too far from master since I started it so long ago... I'm looking into restarting from master, either cherry picking or starting from scratch.

**Comment by spencerkimball** [comment]
This is a lot of sound and fury for one unittest which is no longer flaky. I'm closing this. If anyone disagrees, please resurrect and assign.

**Comment by tamird** [comment]
I think we should still do this; we've seen clocks be quite unreliable, and it'd be good to get rid of the global.

The tags on this issue are already correct - it would be a reasonable starter project for an experienced Go programmer who is otherwise unfamiliar with CRDB.

**Comment by seiflotfy** [comment]
I will pick this up again then :D

**Comment by petermattis** [comment]
@tamird How would plumbing the clock to use down into the metrics package fix unreliable clocks? 

Given the lack of activity on this minor issue, I'd prefer to close.
