### ISSUE TITLE
kvserver: add delete range, intent resolution to rate limiters

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#53476]
DeleteRange should record the keys returned as writes (as they were written as part of the deletion, possibly via NumBytes)

ResolveIntent{,Range} should record the request keys as writes (via NumBytes).

Jira issue: CRDB-3861

**Comment by andy-kimball** [comment]
@RaduBerinde, how do we handle deletions in the cost model, including range deletions? What about intent resolution? Do you think we have any holes or possible issues with KV operations other than read/write?

**Comment by RaduBerinde** [comment]
Looking at the code, a delete is costed like a write request, with write size equal to the key length. I don't think we handle delete range, which I believe it means it is charged as a 0-sized write (1 RU).

We don't handle Intent resolution either, but I don't think it should cost anything (the write that created the intent was already paid for). Note that when we talk about the host-side limit (recently 20% of the node) as opposed to tenant charges, the former is concerned with node load and not with cost so it would make sense to include it there (unfortunately, that will make the two subsystems diverge as they currently use the same cost model).

**Comment by knz** [comment]
Re-opening: the improvement in behavior in KV will not be complete _and_ unconditional in v22.2
This means that CC Serverless will need some mitigation measure to be implemented, unless we complete the migration of the users of DelRange.

@erikgrinaker explains:

> MVCC range tombstones are planned to ship in 22.2. These will be constant-time. However, they are opt-in via a UseRangeTombstone parameter, and cannot be used in transactions.
> The old linear-time implementation will still be available. I don't know which callers use this, and whether they can all be migrated to UseRangeTombstone, so we need to audit this if necessary. There will also be a variant for IMPORT cancellation that will use heuristics to switch between linear-time point tombstones and constant-time range tombstones depending on the size of key runs to delete.

> So it seems like we have two options:
> 1. Audit all DeleteRange callers and determine if these operations can/should be migrated, and if not, whether it's important for us to meter them.
> 2. Add appropriate costing for DeleteRange without UseRangeTombstone to make sure they're covered.

**Comment by knz** [comment]
One use case that gives us pause is the following:

1. user inserts 1TB of data in a slow pace (e.g. over the course of 1 month)
2. user then deletes this data in 1GB increments at a fast rate

Currently this scenario could cause major disruption in our CC infrastructure due to the lack of rate limiting.

**Comment by andy-kimball** [comment]
Why would that cause a major disruption? Shouldn't admission control keep it reasonably fair if multiple tenants are running on the same KV node?
