### ISSUE TITLE
security: add telemetry for OCSP certificate revocation

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#53473]
We currently have no tracking when OCSP certificate revocation is used. This is a placeholder GH issue. @bdarnell @knz could one of you add more details to this issue?

**Comment by knz** [comment]
There are two kinds of telemetry we'll likely want:

- when the cluster settings are changed (`pkg/sql/set_cluster_Setting.go`)
- when a cert revocation request is actually issued (counter increment)

**Comment by knz** [comment]
wokring on it #53607

**Comment by knz** [comment]
Actually no need for #53607 to get OCSP telemetry.
Turns out as @dt explained to me we already have telemetry for cluster setting changes. So no need to add it.

**Comment by knz** [comment]
scratch that we also want to count uses
