### ISSUE TITLE
kvserver: make rate limits configurable per tenant

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#53477]
We will likely find that we

a) want to adjust the rate limits for a given tenant
b) disable a given tenant

The proposal that @ajwerner and @nvanbenschoten have discussed is to use the `system.tenants` data table to store a protobuf that can override the default settings. (Protobuf manipulation has recently become well-tooled in SQL).

This table is already gossiped, so it is available at the KV nodes. Setting the rate limits to zero can effectively disable the tenant.

**Comment by tbg** [comment]
See also https://github.com/cockroachdb/cockroach/issues/55114 about how we're actually going to express the rate limit. This will affect what we put in the TenantInfo here.

**Comment by andy-kimball** [comment]
This is complete, now that we have the `crdb_internal.update_tenant_resource_limits` SQL builtin function.
