### ISSUE TITLE
acceptance: add rebalance test

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#5347]
This test should do the following:
1 - Startup a 9 node cluster, with 3 small nodes and 3 medium nodes and 3 large nodes, with the put test active and consistency checker running.
2 - Turn off all of the 3 medium and 3 large nodes.
3 - turn on the next smallest node
4 - wait and confirm rebalancing has occurred.
5 - goto 3 until all nodes are active

**Comment by JackKrupansky** [comment]
3 + 3 + 3 = 6?

**Comment by BramGruneir** [comment]
Thanks!  Fixed.

**Comment by tamird** [comment]
This seems to be fixed in spirit by #7315. Feel free to reopen if I've misunderstood.
