### ISSUE TITLE
sql: role option inheritance works differently from postgres

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/cockroach#53480]
I just realized that Postgres does not support inheritance for role options. For example if a role has the CREATEROLE privilege, users with that role do not inherit that privilege. It needs to be granted explicitly on each user.

This is different from how we implemented role options in CockroachDB in 20.1. We assumed that role options were inherited the same way that privileges on database objects are. So if any role that a user is part of has CREATEROLE privilege, the user will have that privilege too.

We should decide whether to match the Postgres behavior for 20.2.

Pros:
- Postgres compatibility
- More explicit. Right now it's a bit confusing that if you run `ALTER USER bob NOCREATEROLE`, the user will still have CREATEROLE permission if they belong to a role which has it.
- We already don't apply the inheritance to some options (LOGIN, NOLOGIN, VALID UNTIL) because it doesn't make sense.

Cons:
- Harder to apply a collection of options to a group of users. For instance in CockroachCloud we would not be able to make an "operator" role which could be used to easily grant all of the admin-like options to users.
- Need to consider backward compatibility since we already have one such option in v20.1 (CREATEROLE). Possibly we'd want to write a migration to grant CREATEROLE to any users which are inheriting it right now.

Unless someone can come up with a stronger "con", I would say we should change our behavior to match Postgres.

cc @knz @thtruo

**Comment by knz** [comment]
Can we add a column to the role options table "inheritable"
And then make the ALTER ROLE WITH statement choose the value for that column

then:

- back-fill the column to "true" (previous behavior)
- make "inheritable" be false by default from now on

**Comment by solongordon** [comment]
That's an interesting option. The main thing that worries me is the added user-facing complexity. Are you proposing that we would allow users to set this "inheritable" bit as well or reserve it for our own use?

**Comment by knz** [comment]
maybe in a first phase only for our own use, until we explore what users need

**Comment by angelapwen** [comment]
My bad... accidentally clicked 'close issue', moving back to original spot on project board

**Comment by awoods187** [comment]
I think without significant outsized value we need to bias towards pg compatibility. I'm skeptical this meets the threshold of value to justify different behavior than Postgres.

**Comment by solongordon** [comment]
I just put up #55292 to make this match the Postgres behavior. I think the idea of the "inheritable" column is a clever solution to the backward compatibility issue but ultimately I'm worried about introducing this hidden complexity so I opted not to include it.

This does mean there is some risk that this cause issues for a customer who is relying on the inheritance behavior. But it can be easily resolved by applying the CREATEROLE privilege at the user level, so I feel this is a reasonable risk to take on.
