### ISSUE TITLE
ui: does not show tables in user-defined schemas under the "Databases" page

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/cockroach#53486]
Tables created in a user-defined schema do not show up under Databases>Tables page

![image](https://user-images.githubusercontent.com/13694532/91337221-0c47bb80-e7a1-11ea-9792-b1dccdbad8dd.png)

```
root@127.0.0.1:63916/vy> show tables
                      -> ;
  schema_name | table_name | type  | estimated_row_count
--------------+------------+-------+----------------------
  public      | users      | table |                   0
  schema1     | users      | table |                   0
(2 rows)
```

**Comment by jordanlewis** [comment]
We'll start by just returning all tables from all user defined schemas, but there's a worse problem which is that the UI doesn't accommodate user-defined schemas at all.

cc @dhartunian
