### ISSUE TITLE
bulkio: Better error message returned when job is canceled

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#53490]
`root@localhost:26257/defaultdb> BACKUP INTO 's3://bucket/path?AUTH=implicit';`
`ERROR: job 584569210350043137: node liveness error: restarting in background`

Would be much better if it could let the user know the job was canceled! Or at least disambiguate between failed and canceled, since it's hard to tell if that error is legit or because of user canceling.

Epic CRDB-7909

Jira issue: CRDB-3858

**Comment by adityamaru** [comment]
@ajwerner there is a TODO regarding this at https://github.com/cockroachdb/cockroach/blob/master/pkg/jobs/registry.go#L1084 so just wanted your opinion.

I guess the challenging part is disambiguating where the context cancellation was triggered to be able to provide a more contextual error message?
