### ISSUE TITLE
ui: misc visual fixes

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#5352]
`Databases:` link is not styled

Tabled data sits too high on the label and too low on the values.  Look at `Table` and `blocks`

![screen shot 2016-03-17 at 13 26 41](https://cloud.githubusercontent.com/assets/1614265/13854892/1d83192e-ec44-11e5-9c0c-927c1287f3f2.png)

**Comment by tamird** [comment]
Closing as stale.
