### ISSUE TITLE
ui: databases view is not responsive

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#5353]
Ick...

![screen shot 2016-03-17 at 13 28 33](https://cloud.githubusercontent.com/assets/1614265/13854914/3b658b16-ec44-11e5-8aef-214e2531ddeb.png)

**Comment by maxlang** [comment]
The wrapping doesn't appear to still be an issue.

<img width="401" alt="screen shot 2016-07-26 at 12 45 19 pm" src="https://cloud.githubusercontent.com/assets/3691886/17147037/d9a7d38c-532e-11e6-814e-693d84e862e1.png">
