### ISSUE TITLE
sql: Flakiness in prepared statements 

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#5355]
The following sequence of queries may or may not fail (non-deterministically), found while investigating #5340:

```sql
 CREATE TABLE d.ts (a TIMESTAMP, b DATE);
 INSERT INTO d.ts VALUES(TIMESTAMP '2001-01-02 03:04:05', DATE '2006-07-08');
 SELECT DISTINCT 1 FROM d.ts LIMIT 1+EXTRACT(DAYS FROM NOW())
```

The symptom is that the last select either returns 0 or 1 row depending on the run, where 1 row is expected always.

The expression behind LIMIT may or may not be consequential (not tested further at this point).

**Comment by knz** [comment]
See #5357 for an example test (commented out) that illustrates this.

**Comment by petermattis** [comment]
Is this still happening? I failed at reproducing using the example test in #5357.

**Comment by knz** [comment]
I have tried to reproduce this (and the others) without success. Closing for now.
