### ISSUE TITLE
sql: support UPDATE ONLY syntax

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#53552]
In Postgres, you can write a query like `UPDATE ONLY tablename ...`. Here's what the docs say:

>  If ONLY is specified before the table name, matching rows are updated in the named table only. If ONLY is not specified, matching rows are also updated in any tables inheriting from the named table. Optionally, * can be specified after the table name to explicitly indicate that descendant tables are included.

https://www.postgresql.org/docs/10/sql-update.html

I've only encountered this in one test case from the PGJDBC test suite.

Perhaps this would be a candidate for "good first issue" -- I'm adding to the SQL Features triage board so someone with more knowledge can decide to add that label.

**Comment by rohany** [comment]
It seems like we'd want to just add parsing support for this. We don't support table inheritance (nor have any plans to), so that would be about it.

**Comment by solongordon** [comment]
+1, let's only add syntax support and treat it as a no-op.

**Comment by propainter** [comment]
would like to pick this, please guide

**Comment by adzimzf** [comment]
Hi, I interested to work on it, 
but this's my first-time work on the CockroachDB, so maybe it'll take a little bit longer

**Comment by otan** [comment]
hey @propainter, unfortunately saw this too late and we're looking at doing this now.
they are some very well guided issues available in https://github.com/cockroachdb/cockroach/issues/49203
