### ISSUE TITLE
sql: various `SHOW` commands should include owner

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#53566]
Show commands like `SHOW TABLES`, `SHOW DATABASES` etc should also display the owner of the object.

- [ ] `SHOW DATABASES`
- [ ] `SHOW SCHEMAS`
- [ ] `SHOW TABLES`
- [ ] `SHOW ENUMS`

**Comment by ajstorm** [comment]
Addressed with https://github.com/cockroachdb/cockroach/pull/54708

**Comment by otan** [comment]
are we looking to backport this to v20.2?

**Comment by ajstorm** [comment]
Doesn't seem like it would meet the "release blocker" criteria, but interested in other opinions.  @solongordon thoughts?
