### ISSUE TITLE
builtins: add crdb_internal.validate_descriptors() builtin

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#53571]
This builtin should collect all descriptors and run Validate against them, reporting any errors that it finds.

**Comment by otan** [comment]
would it be might be nicer with syntax, e.g. `VALIDATE ALL` / `VALIDATE DATABASE d`?

**Comment by jordanlewis** [comment]
We can always add dedicated syntax for it later, but the primary intent is to provide developers with a knob into the validate system. Adding top level syntax is hard to revoke.
