### ISSUE TITLE
ui: Statements page table header should always be visible

### ISSUE THREAD

**Issue by sheaffej** [cockroachdb/cockroach#53580]
Please consider making the table header on the Statements page always visible, as the page is scrolled down.

On multiple occasions, I've seen both customer and CRL employees (in addition to myself) mistake the values in the Execution Count, and Rows Affected columns when looking a statements further down in the list that causes the table header to scroll off the screen. Keeping the header visible as the table is scrolled would avoid this confusion. 

Impact:
Digging into a 7.6 second query that is executed 1 time and returns 62,000 rows is not a good use of time. But thinking a query runs 7.6s and is executed 67,000 times and returns 1 row certainly is cause for concern . When the columns are mis-interpreted, users spend time digging into the wrong queries.

Statement table at the top (header visible)
<img width="1015" alt="header" src="https://user-images.githubusercontent.com/5922798/91500921-5a2ff280-e879-11ea-993e-f0a36f6b48ed.png">

Statement table after scrolling down (header not visible)
<img width="1019" alt="noheader" src="https://user-images.githubusercontent.com/5922798/91500974-72077680-e879-11ea-97f0-d479ce4f31f4.png">

Jira issue: CRDB-3855

**Comment by piyush-singh** [comment]
cc @Annebirzin
