### ISSUE TITLE
geo: SpatialObjectToWKT() omits empty shapes in collections 

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#53632]
**Describe the problem**

While implementing `ST_ForceCollection`, I have a test case which generates a geometry collection with an empty point. However, calling `geo.SpatialObjectToWKT` omits the empty point from the output.

**To Reproduce**

```go
func TestEmptyPointWKT(t *testing.T) {
	gc := geom.NewGeometryCollection().SetSRID(int(geopb.DefaultGeographySRID))
	gc.MustPush(geom.NewPointEmpty(geom.XY))
	g, err := geo.MakeGeographyFromGeomT(gc)
	require.NoError(t, err)
	wkt, err := geo.SpatialObjectToWKT(g.SpatialObject(), 0)
	require.NoError(t, err)
	require.EqualValues(t, "GEOMETRYCOLLECTION (POINT EMPTY)", wkt)
}
```

This yields a test failure:

```
Not equal: 
expected: string("GEOMETRYCOLLECTION (POINT EMPTY)")
actual  : geopb.WKT("GEOMETRYCOLLECTION EMPTY")
```

PostGIS can represent this just fine:

```
postgis=# select st_astext(st_forcecollection('POINT EMPTY'));
            st_astext            
---------------------------------
 GEOMETRYCOLLECTION(POINT EMPTY)
(1 row)
```

**Environment:**
 - CockroachDB version: `master` at `8b91062f93`
 - Server OS: macOS
 - Client app: `cockroach demo`

CC @otan

**Comment by otan** [comment]
It's this if condition in go-geom -- https://github.com/twpayne/go-geom/blob/master/encoding/wkt/encode.go#L96

Feel free to change it, if not I'll get to it on Monday.

**Comment by erikgrinaker** [comment]
Opened a go-geom PR here: https://github.com/twpayne/go-geom/pull/184
