### ISSUE TITLE
geo: geos WKT cannot handle POINT EMPTY inside of collections

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#53631]
**Describe the problem**

`st_astext()` is unable to handle empty points in geometry collections.

**To Reproduce**

CockroachDB:

```
> select st_astext('GEOMETRYCOLLECTION (POINT EMPTY)');
ERROR: st_astext(): geos error: IllegalArgumentException: Empty Points cannot be represented in WKB
```

PostGIS:

```
# select st_astext('GEOMETRYCOLLECTION (POINT EMPTY)');
            st_astext            
---------------------------------
 GEOMETRYCOLLECTION(POINT EMPTY)
(1 row)
```

**Environment:**
 - CockroachDB version: `master` at `8b91062f93`
 - Server OS: macOS
 - Client app: `cockroach demo`

CC @otan

**Comment by otan** [comment]
This won't really get resolved until we write our own WKT parser, or GEOS upgrades :( 
We basically need some variant of https://github.com/libgeos/geos/commit/466cff135c8e504632ae38b79a1348dbadb390f1
