### ISSUE TITLE
OPT: Query planner chooses a suboptimal plan for case statement evaluation

### ISSUE THREAD

**Issue by xinyuliu12** [cockroachdb/cockroach#53653]
Hello everyone!

First off, I am sorry for *gestures vaguely* all of this. Second, I think we have found a performance bug related to a suboptimal plan selection when evaluating a case statement that always returns the same value.

Here is a pair of TPC-H queries that exhibit this behavior.

```
SELECT   s_phone AS c0, 
         CASE 
                  WHEN Count(*) OVER ( partition BY s_address ORDER BY s_nationkey, s_nationkey ) <= s_suppkey THEN s_nationkey
                  ELSE s_nationkey 
         END AS c1 
FROM     supplier 
WHERE    s_phone IS distinct 
FROM     'random string';

SELECT s_phone     AS c0, 
       s_nationkey AS c1 
FROM   supplier 
WHERE  s_phone IS distinct 
FROM   'random string';

```

**Actual Behavior**
The first query takes ~260 milliseconds on the latest release v20.2.0-beta.1, while the second query only takes ~40 milliseconds.
For the first query, the database system projects column s_phone and naively executes the case statement, which returns column s_nationkey for both conditions. Its "EXPLAIN ANALYZE" result is [here](https://cockroachdb.github.io/distsqlplan/decode.html#eJyUUtFu00AQfOcrVvvSBI7WdpJSTkJymrhgKbWLbSgFouhqr1qrts_cndVGVf4d2Q4lRaLQx53d2Z0dzT3qHwVy9L6cLaZ-ANNgurj46sFg7sdJ_HExhNhbeLME9Kq-lhXBNIbUYjCbxh6cf_ACSGVTmcHLIYSfvQgGZ9Mo8RM_DOD4AvRKZJkirSGM5l7UQ5UwuaxuaM12iyF8byxrlL4DvdJNXd_QGpJ2_84MeIvYewwE806RDSdReAotschJtcoi70GzH0P7jh_Mkn5uT4kqkyVoo_Lqag8ZVjKjQJSkkX9DG5cMayVT0lqqFrrvBvzsDrnFMK_qxrTwkmEqFSG_R5ObgpBjIi4LikhkpA4sZJiREXnRrf2lzq1VXgq1RoZxLSrN4TUyPMkLQ4qDO_mnXs55nER-8B4Zho3h4NrMHTF3zNwJMrwUJr0mDbIxddudHCFD09TFLmZZVivPD8HkJXEYj_edN06pcblh2E9tP9RGXBFye8P-34XzvMrkLakD-7EFu-ng4DrIcBZ-CpJVFJ7HgyEMHnLijl4NkWFEVda5Mu4z10bOnWyj4tptQtxRGwt35AVzZKjkrQZFIvv9ozaiKLZvTg73jxy71MiwFHdQUinVGhpNGQd7BKf58TMNpDtKmzaO2wOOc7Q_Onz7hJHOc4yMSNey0vTIxr9ttjZLhpRdUR9ZLRuV0pmSaXemL8OO1wEZadN37b7wq77VCtwl20-SnT_Iy82LnwEAAP__OJVcOg==).
For the second query, the database system projects columns s_nationkey and s_phone. Its "EXPLAIN ANALYZE" result is [here](https://cockroachdb.github.io/distsqlplan/decode.html#eJyMkF-L1DAUxd_9FJfzsgpRO64LmqcZ1q4Gxs7aFvxHWbLtZTbYJjFJwWXod5e2Kvog-nh_956Tc3JC_NpDIv9wvd-pgnbFbv_xU04PX6mqrt7tH1GV7_PLmuKNv3OWaVdRmwmKN1Yn4-wXvl_Qhq7Kw1uKo_e94UDv3-Rl_kukKpr9VHFZr3dnQdvODRRTMPZ4BgHrOi70wBHyMzZoBHxwLcfowoxOy4HqvkFmAsb6Mc24EWhdYMgTkkk9Q6LWtz2XrDsOTzMIdJy06Rfbn-m2PphBh3sIVF7bKOkxBK5MnzhI2l78M6-UsqpLVbyGwGFMs0Zsn0PgVqf2jiO5MfmZX7yAQBp9_zvLsmwOpg6UzMCSnr18kp2fDxHNJLBe_egWkz4y5GYS_9-_5OidjfxH9b85Z1MjwN2R1z-ObgwtXwfXLs-s42HRLaDjmNbtZh2UXVdTMz34HgAA__9WiLsJ).

**Expected Behavior**
I would have expected the database system run these two queries with similar execution time, given that they both have the same semantics. To this end, for the first query, the optimizer should bail out the evaluation of the case statement since both conditions return the same value. 
Here are the steps for reproducing our observations:

**Test environment**

* Ubuntu 20.04 machine "Linux panda 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux"
* Cockroachdb v20.2.0-beta.1
* Database: TPC-H benchmark (with scale factor 5)

**Reproduce Bug**

1. Install cockroachdb v20.2.0-beta.1     

```
    $ mkdir -p $(go env GOPATH)/src/github.com/cockroachdb
    $ cd $(go env GOPATH)/src/github.com/cockroachdb
    $ git clone https://github.com/cockroachdb/cockroach
    $ cd cockroach
    $ git checkout eaa939c
    $ make build
    $ sudo make install
```

* start a cockroachdb node in your preferred working directory
```
    $ cockroach start --insecure --store=node1 --listen-addr=localhost:26257 --http-addr=localhost:8080 --join=localhost:26257,localhost:26258,localhost:26259 --background
    $ cockroach init --insecure --host=localhost:26257
```

2. Set up TPC-H test benchmark (if you already have a TPC-H benchmark set up, you can skip step2; starting from step2, all commands should run in the directory ./tpch5 after downloading and extracting it)

* Download TPC-H (scale factor of 5) and extract it
    Download the dataset from the link: https://drive.google.com/file/d/1MLVFPKdRQhlRgmeRIumyIj8NBMRSQ3um/view?usp=sharing
```
    $ tar xzvf tpch5_setup.tar.gz
    $ cd tpch5
    $ chmod +x setup.sh
```

* Create DB and TPC-H schema
`   $ cockroach sql --insecure --host=localhost:26257`    
    In CockroachDB's built-in SQL client to create database:
```
    $ create database tpch5;
    $ exit
```
* Create TPC-H Schema
   `    $ cockroach sql --insecure --host=localhost:26257 -d tpch5 < dss.ddl
`
* Set up benchmark
```  
    $ ./setup.sh
    $ cockroach sql --insecure --host=localhost:26257 -d tpch5 < dss.ri

```
3. Test SQL query that exhibits performance issue
* Download the query from the link: https://drive.google.com/file/d/1OWkk9dLaWK3_x7SjcQ_3DCuHvNKsAyq8/view?usp=sharing
* Execute the queries 
`    $ cockroach sql --insecure --host=localhost:26257 -d tpch5 < query.sql
`

**Comment by RaduBerinde** [comment]
This is the same root cause as #51820 (not reoptimizing with results of scalar subqueries). Closing this and making the other one more general.

**Comment by xinyuliu12** [comment]
Hi! Thank you so much for your quick reply!

Would you feel comfortable to explain why this is the same root cause as #51820 ? 
I am wondering if the case statement here has a subquery that is necessary to be executed.
I would like to propose an alternative to improve this issue. Is it practical to improve the parser to translate a case statement into a simpler expression (e.g., in this example, a column projection), when the parser can decide `THEN` and `ELSE` have the same (or semantically equivalent) expression?

**Comment by RaduBerinde** [comment]
Ah, I probably misread - I thought there was a subquery involved. I don't understand what the problem is. In the first query, you know that the end result happens to be the same on both branches, but how is the optimizer supposed to know? It needs to calculate the window function (which involves keeping track of partitions) and compare it to `s_suppkey`. That's where the extra overhead comes from.

**Comment by xinyuliu12** [comment]
Thank you so much for your clarification! Your feedback is very important to help us improve our fuzzing technique to test DBMS!
