### ISSUE TITLE
telemetry: track which role options are assigned to SQL users

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#53664]
**Request**
Given the new role options being introduced in 20.2 https://github.com/cockroachdb/cockroach/issues/52575, it will be helpful to track which (if any) role options are being utilized by customers who are managing and configuring permissions for their database users. We currently do not track this in TELEMETRY.STMTSTATS - getting optics into this will help us understand RBAC adoption in general.

**Context**
The lack of optics also impacts our ability to gather data and to design a sufficient UX for CockroachCloud workflows. Customers prefer to create SQL users with lesser-privileges, so that they are not leaking admin access than intended. Ideally, **customers want explicit control and flexibility around defining a SQL user’s privileges to match their actual workflows**. This is non-existent in CockroachCloud today.  

cc @knz @solongordon for awareness

**Comment by thtruo** [comment]
Updated the description to explicitly call out adding explicit tracking to account for the new role options coming in 20.2

**Comment by knz** [comment]
@solongordon can you help route this? Thanks

**Comment by solongordon** [comment]
@RichardJCai Would you please add a feature counter for each time a role option is assigned to a user?

**Comment by RichardJCai** [comment]
> @RichardJCai Would you please add a feature counter for each time a role option is assigned to a user?

Only cause you asked so politely

**Comment by RichardJCai** [comment]
Looking into this, I realized we do already track which role options are assigned, even for the new role options.

Every time a CREATE ROLE or ALTER ROLE is done, the corresponding role options are tracked.

Examples:
```
CREATE ROLE testuser CONTROLJOB
increments 
iam.roles.create.controljob
iam.roles.create.nologin
iam.roles.create.role

ALTER ROLE testuser CREATEDB
increments
iam.roles.alter.createdb
iam.roles.alter.role
```

Is this sufficient? @solongordon @thtruo

**Comment by vy-ton** [comment]
cc @piyush-singh since he's now covering Security. Can you weigh in on Richard's question above?

**Comment by thtruo** [comment]
Perhaps this is more for Piyush, but I did just take a look and can confirm that those appear in our FEATURES table, including new role options. Unless @piyush-singh had other feedback, it seems that whatever is currently available seems sufficient. Thanks for checking Richard.

**Comment by piyush-singh** [comment]
I think this should cover our needs for now, if we need anything else I can file a separate issue with detailed requirements.
