### ISSUE TITLE
sql: implement the `information_schema.sql_features` table

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#53675]
This table contains information about what features from the SQL standard are supported. See the docs here: https://www.postgresql.org/docs/9.1/infoschema-sql-features.html

Jira issue: CRDB-3848

**Comment by rohany** [comment]
The actual data seems to be populatable from these two tables: https://www.postgresql.org/docs/9.1/features-sql-standard.html and https://www.postgresql.org/docs/9.1/unsupported-features-sql-standard.html

**Comment by solongordon** [comment]
Not clear if any ORMs rely on this data or not. It would still be nice to have and we could consider populating docs based on this data.
