### ISSUE TITLE
roachtest: do not request log redaction for pre-20.2 nodes

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#53690]
Today `roachtest` issues `debug merge-log --redact` even when running pre-20.2.

The `--redact` code will:

- fail entirely with an error if run with a pre-20.2 *client* binary
-  redact every log message out if the *server* runs pre-20.2

I think it may be worth not enabling `--redact` for mixed-version or pre-20.2 tests entirely.

cc @tbg for triage.

**Comment by tbg** [comment]
Since we have the unredacted logs available in the artifacts, and 20.2 is not a primary development target any more, I'm closing this out.
