### ISSUE TITLE
Include ranges 1 to 6 in SHOW RANGES of system DB  and add output to debug.zip

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/cockroach#53710]
**Is your feature request related to a problem? Please describe.**
To help troubleshoot issues with system ranges

**Describe the solution you'd like**
 add ranges 1 to 6 to SHOW RANGES

Currently, the output of the statement below does not include ranges 1 to 6. 

```
SELECT * FROM [SHOW RANGES FROM DATABASE system] ORDER BY range_id;
```

Once the output of the above includes ranges 1 to 6, add the output to a file in the debug.zip.

Jira issue: CRDB-3845

**Comment by rimadeodhar** [comment]
I investigated this recently and the ranges with ids 1-6 do not show up in the output of the SHOW RANGES statement for the system database as they don't belong to the system database. They are essentially ranges that don't belong to a database and are used internally by cockroach. So the behavior above is expected. 
The range information for these queries can be seen by querying the crdb_internal.ranges view but not through the SHOW RANGES statement which filters on db/table name.
At this point, I think we need to determine if we want these ranges to be queryable in some other way but that would be more of a product decision, cc @thtruo for further inputs.

**Comment by thtruo** [comment]
Ack, thanks @rimadeodhar for the context. @florence-crl could you share additional background on what type of problem you're trying to solve by having knowledge of ranges 1 - 6? Is this still a relevant ask from your perspective given Rima's previous comment?
