### ISSUE TITLE
changefeedccl: remove `experimental` from storage scheme, avro format

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#53716]
Given that we feel like the storage sinks are now stable, we want to remove `experimental` from the scheme so that users know that it's safe to use / vetted. We should also work toward removing `experimental` from avro output formats.

One thing to think about is backward compatibility -- if a user has a running changefeed and upgrades versions, how will it work that the scheme is now `s3://` vs. `experimental-s3://`? Would love to hear some options in the comments.

**Comment by mwang1026** [comment]
We probably want to still include `experimental-s3` as an alias for `s3` but just don't doc it for backward compat reasons.

**Comment by amruss** [comment]
Closing this since we split these into two issues: https://github.com/cockroachdb/cockroach/issues/69069
https://github.com/cockroachdb/cockroach/issues/65761
