### ISSUE TITLE
sql: add memory accounting for the transactions metric collection struct

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#53749]
We currently don't have memory accounting for the in memory struct that collects transaction statistics, but we should add this as it can get unboundedly large based on user query patterns.

**Comment by rafiss** [comment]
cc @jordanlewis i'm sticking this on the radar of SQL Observability since the new time might benefit from getting familiar with memory accounting in this area. It also remains on the SQL Experience backlog as a low priority.

**Comment by jordanlewis** [comment]
Hey @arulajmani what's the state of the PR that you have open for this? Do you want to take it over the finish line, or is it out of date, or should we take over?

**Comment by rafiss** [comment]
@Azhng I noticed that you closed out https://github.com/cockroachdb/cockroach/issues/64742 -- can this issue be closed as well?

**Comment by Azhng** [comment]
Ah, I wasn't aware this issue existed. I think we can close this issue since #65172 effectively addressed the problem.

**Comment by rafiss** [comment]
Awesome! Thanks for fixing the problem!! unbounded memory usage is super important to address

**Comment by Azhng** [comment]
Happy it helped :D !
