### ISSUE TITLE
kvserver: informative transaction retry errors

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#53746]
Transaction retry errors as they currently render are made by KV engineers for KV engineers. However, they are user facing. Transaction retries are one of the main new phenomena encountered by users interacting with CockroachDB. As such, they need to be user-friendly and translate their content into a language suitable for an application developer.

**Describe the solution you'd like**

As a stretch goal, make https://www.cockroachlabs.com/docs/stable/common-errors.html#restart-transaction redundant. Instead of

> pq: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE): "sql txn" meta={id=1c6b273b key=/Table/18125/1/"\x80\x00\x00\a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"/0 pri=0.04025176 epo=0 ts=1598054224.597738000,2 min=1598054224.597738000,0 seq=17} lock=true stat=PENDING rts=1598054224.597738000,0 wto=false max=1598054224.597738000,0

It could read (strawman) something like this

>
pq: transaction was restarted after running for 0.52s due to a contending read at row `(foo, bar)` of `mydb.mytable`
>
See https://crdb.io/faq/20.2/txn-restarts

**Comment by nvanbenschoten** [comment]
@tbg how should we think of this issue's relation to https://github.com/cockroachdb/cockroach/issues/41057? Are they redundant?

**Comment by mwang1026** [comment]
closing in favor of #41057
