### ISSUE TITLE
descs: immutable descriptor read path should accept either a transaction or a timestamp

### ISSUE THREAD

**Issue by rohany** [cockroachdb/cockroach#53751]
In the immutable descriptor access path, the `descs.Collection` accepts a `*kv.Txn`, but only uses this `*kv.Txn` to get its `ReadTimestamp()` or when the `avoidCache` flag is passed. This is problematic for use cases that have a read timestamp (changefeeds, distsql type resolving) but have to thread through a transaction or create one to just access a descriptor. 

An option for us is to change the immutable descriptor access path to accept a struct like 
```
type TxnOrTs struct {
  txn *kv.Txn
  ts hlc.Timestamp
}
func (t TxnOrTs) ReadTimestamp() hlc.Timestamp {
  if t.ts != (hlc.Timestamp{}) {
    return t.ts
  }
  return t.txn.ReadTimestamp()
}
```

I attempted this, but ran into a problem: in a state where some nodes are still using the `DatabaseCache`, access to databases and schemas require the `*kv.Txn`, which means that we can't resolve tables and types without txns.

Jira issue: CRDB-3835

**Comment by postamar** [comment]
Closing because this seems to have been implemented via `maxTimestampBoundDeadlineHolder`.
