### ISSUE TITLE
sql: TestDropDatabaseWithForeignKeys failed on release-20.1

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#53769]
On release-20.1 branch with an unrelated PR I saw `TestDropDatabaseWithForeignKeys` fail: [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=2238555&buildTypeId=Cockroach_UnitTests). Seems like a flake, but I thought I'd mention it.

**Comment by ajwerner** [comment]
Meh this is due to `W200901 16:20:58.582528 269113 kv/kvserver/node_liveness.go:563  [n1,s1,r3/1:/System/{NodeLive…-tsd}] slow heartbeat took 35.7s` - we need to be live to run schema changes and the `SucceedsSoon` is 45s. I'm inclined to close this for now as it's not really related to this test
