### ISSUE TITLE
ui: improper grouping of nodes by node addresses

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#53773]
Reported privately in https://github.com/cockroachlabs/support/issues/584.

> Hm, they're running into a real admin UI bug I think. Like mentioned above, n14 was originally running at the same address as n9, and the admin UI seems to be treating n14 as healthy seeing as how n9 is found to be healthy. That's weird, and we shouldn't do it. As for the "1 dead node", that part is technically correct but it's clear that the information used to populate that too is not the same thing powering `cockroach node status`, which I think we should change. I hope we that we can address both of these by addressing cockroachdb/cockroach#50707, which adds some more parity between what cockroach internally sees and what's shown in the Admin UI.

> [...] in our UI we seem to have crossed our wires because we saw an instance of two separate nodes (as understood by CRDB non-UI code) being treated as one by the CRDB UI code. Specifically: n14 was down, but because it had used the same address as n9, it showed it as being alive an healthy in the UI (which is confusing).

We've seen instances in our admin UI where we seem to be grouping nodes by their node addresses, instead of disambiguating between nodes in the same way crdb does internally (as exposed by `cockroach node status`). Given we're looking to improve our story our rolling restarts/node repaving, we're more likely to have nodes come up sharing the same address as an earlier node. We'll need to ensure that our admin UI knows to disambiguate between separate nodes that happen to share the same address. See the private issue for screenshots from when we end up confusing ourselves.

+cc @piyush-singh, @johnrk.

Jira issue: CRDB-3833

**Comment by farah** [comment]
hey @irfansharif, any chance you could post the screenshots?

**Comment by irfansharif** [comment]
Unfortunately the screenshot contained data private to the customer (their node addresses specifically, which was the subject of interest).
