### ISSUE TITLE
ui: statement details page does not load for certain statements

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/cockroach#53835]
I noticed this while testing a different fix. It looks like the Statement Details page errors out for certain statements. To reproduce:

1. Run `SELECT crdb_internal.force_retry('1s');`
2. Go to the Statements page.
3. Click the row for `SELECT crdb_internal.force_retry(_)`
Result: A blank page and an error in the console: `Uncaught TypeError: Cannot read property 'mean' of undefined`

This seems to have been broken recently since I recall the same statement working a month or two ago.

**Comment by nvanbenschoten** [comment]
Also tracked in https://github.com/cockroachdb/cockroach/issues/53827.

**Comment by dhartunian** [comment]
#53827 has been resolved so closing this as well.
