### ISSUE TITLE
ui: Test web UI failed

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#53832]
The [Publish Bleeding Edge](https://teamcity.cockroachdb.com//viewLog.html?buildId=2240054&buildTypeId=Cockroach_MergeToMaster) build failed yesterday, with lint failing due to "Ensure dependencies are up-to-date". The specific error was in Test web UI due to:
```
 	 <TimeScaleDropdown>
19:02:18 ✖ getTimeRangeTitle must return custom Title
19:02:18 HeadlessChrome 84.0.4147 (Linux 0.0.0)
19:02:18 AssertionError: expected 'Sep 01, 11:52PM -  12:02AM (UTC)' to equal ' 11:52PM -  12:02AM (UTC)'
19:02:18 at Context.eval (webpack-internal:///./src/views/cluster/containers/timescale/timescale.spec.tsx:105:50)
```

**Comment by RaduBerinde** [comment]
Hit the same in a bors run:

https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=2273538

**Comment by dhartunian** [comment]
@koorosh Can you spend some time tomorrow seeing if you can reproduce this? Let's cap at 1h for now and see if we can find a quick fix.

**Comment by koorosh** [comment]
This state could be reproduced only at midnight (as shown in logs `AssertionError: expected 'Sep 01, 11:52PM -  12:02AM (UTC)'`. Tests depend on the current date heavily and the expected result was supposed to get `start` and `end` dates of range within the same day.  CI triggered tests right at 11:52 PM and it caused 10 min date rage spread across two days.
