### ISSUE TITLE
colexec: remove vectorize_row_count_thresold session variable

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#53893]
By default, the vectorized execution engine is only used to execute a query if the query's row count estimate is larger than the `vectorize_row_count_threshold`. This was because there was a non-negligible allocation overhead.

Since dynamic batches were introduced, the allocations were minimized and the vectorized execution engine demonstrates a 10% speedup on a point lookup workload (kv95), which is a worst-case scenario for the engine.

We should:
1) Remove the `vectorize_row_count_threshold` since it is not useful anymore.
2) Create an optimizer cost model to take into account the fact that vectorized execution will now be unconditionally used if set (this will be the default). This is a lot easier than what we wanted to do previously, which was make the optimizer decide whether vectorized execution would be beneficial.

**Comment by asubiotto** [comment]
2. is likely out of scope for the immediate 21.1 release.

I think the main work item here is benchmarking other execution operations with a small number of rows (e.g. hash joins, aggregations) to offer more data points on the performance difference in the worst case for the vectorized engine.

**Comment by yuzefovich** [comment]
On a related note, do we want to remove `vectorize=201auto` setting as well? As a reminder, it means that only streaming queries will run via the vectorized engine when the threshold is met; we're removing the second condition, and I'm thinking that "streaming" concept is no longer useful differentiator as well because we have disk-spilling in all cases when the row engine has it. Thoughts? cc @jordanlewis

**Comment by asubiotto** [comment]
Yes, I think `201auto` only makes sense in `20.2`

**Comment by yuzefovich** [comment]
Posting the last results we observed in #55713 for convenience:

----
**KV95**

- 1 min ramp, 5 min duration
  - GCE: **+3.68%**
  - AWS: **-3.84%**
- 2 min ramp, 10 min duration
  - GCE: **-2.84%**
  - AWS: **-1.10%**
- 3 min ramp, 15 min duration
  - GCE: **+3.58%**
  - AWS: **-3.70%**
- 5 min ramp, 30 min duration
  - GCE: **-2.51%**
  - AWS: **-0.66%**
- 10 min ramp, 60 min duration
  - GCE: **+1.37%**
  - AWS: **-1.87%**
----
**MOVR** (with these parameters `--num-histories 10000 --num-promo-codes 10000 --num-rides 5000     --num-users 500 --num-vehicles 150`)
- 1 min ramp, 5 min duration
  - GCE:
    - old: `300.0s        0          88306          294.4      3.4      1.2     12.1     44.0     96.5`
    - new: `300.0s        0          86214          287.4      3.5      1.4     11.5     41.9     60.8`
    - **-2.37%** in throughput
  - AWS:
    - old: `300.0s        0         153160          510.5      2.0      0.9      6.8     22.0    226.5`
    - new: `300.0s        0         147820          492.7      2.0      0.9      6.8     22.0    226.5`
    - **-3.49%** in throughput
- 3 min ramp, 15 min duration
  - GCE:
    - old: `900.0s        0         260376          289.3      3.5      1.4     11.5     41.9     67.1`
    - new: `900.0s        0         254317          282.6      3.5      1.4     13.1     41.9     60.8`
    - **-2.33%** in throughput
  - AWS:
    - old: `900.0s        0         435143          483.5      2.1      1.0      6.6     22.0    226.5`
    - new: `900.0s        0         417249          463.6      2.2      1.0      7.1     22.0    469.8`
    - **-4.11%** in throughput
- 10 min ramp, 60 min duration
  - GCE:
    - old: `3600.0s        0        1077971          299.4      3.3      1.6     10.0     37.7    209.7`
    - new: `3600.0s        0        1055800          293.3      3.4      1.7     10.0     37.7     58.7`
    - **-2.06%** in throughput
  - AWS:
    - old: `3600.0s        0        1488654          413.5      2.4      1.4      6.8     22.0    436.2`
    - new: `3600.0s        0        1418218          393.9      2.5      1.4      7.6     23.1    436.2`
    - **-4.73%** in throughput
----
I'll rerun KV95 and MOVR on 4989436ec960db78bdb403373db5a95fe0b0dfc8. I'll also quickly confirm that there is still no regression on TPCC.

**Comment by yuzefovich** [comment]
New numbers.

**KV95**

- 1 min ramp, 5 min duration
  - GCE: **-2.1%**
  - AWS: **-2.3%**
- 2 min ramp, 10 min duration
  - GCE: **-2.8%**
  - AWS: **-2.9%**
- 3 min ramp, 15 min duration
  - GCE: **-2.2%**
  - AWS: **-3.0%**
----
**MOVR** (with these parameters `--num-histories 10000 --num-promo-codes 10000 --num-rides 5000     --num-users 500 --num-vehicles 150`)
- 1 min ramp, 5 min duration
  - GCE: **-3.7%**
  - AWS: **-4.8%**
- 2 min ramp, 10 min duration
  - GCE: **-0.0%**
  - AWS: **-4.4%**
- 3 min ramp, 15 min duration
  - GCE: **-5.2%**
  - AWS: **-6.5%**
----
TPCC still shows no significant difference.

**Comment by yuzefovich** [comment]
Comparison of **20.2.5** against **21.1.0.alpha3** with all default settings (`vectorize_row_count_threshold=1000` for the former and `0` for the latter). All tests were run once on a 3 node roachprod cluster with the load coming from the fourth node.

----

**KV95**

- 1 min ramp, 5 min duration
  - GCE: **+1.5%**
  - AWS: **+1.3%**
- 2 min ramp, 10 min duration
  - GCE: **+2.1%**
  - AWS: **-0.4%**
- 3 min ramp, 15 min duration
  - GCE: **+2.1%**
  - AWS: **-2.7%**

----

**TPCC 100 warehouses**

- 1 min ramp, 5 min duration
  - GCE: **+2.9%**
  - AWS: **-0.2%**
- 2 min ramp, 10 min duration
  - GCE: **-0.2%**
  - AWS: **-0.1%**
- 3 min ramp, 15 min duration
  - GCE: **+0.0%**
  - AWS: **-0.3%**

----

**MOVR** (with these parameters `--num-histories 10000 --num-promo-codes 10000 --num-rides 5000     --num-users 500 --num-vehicles 150`)
- 1 min ramp, 5 min duration
  - GCE: **-0.0%**
  - AWS: **-0.7%**
- 2 min ramp, 10 min duration
  - GCE: **-3.2%**
  - AWS: **-4.2%**
- 3 min ramp, 15 min duration
  - GCE: **-4.4%**
  - AWS: **-1.0%**

**Comment by asubiotto** [comment]
OK. These look good to me cc @jordanlewis @awoods187 . Let's socialize it in your email thread?

**Comment by awoods187** [comment]
Why is there such a large variance across clouds? Is this a small sample size problem? Could we get one test, how about the hypothesized worst test, and run it 10 times to reduce randomness?

**Comment by yuzefovich** [comment]
Yes, I'm pretty sure the variance is due to having only a single run. I'll kick off 10 runs of KV95 3 min ramp 15 min duration to reduce the noise.

**Comment by yuzefovich** [comment]
Here is the info from 10 runs of KV95:

- 3 min ramp, 15 min duration
  - GCE:
    - 20.2.5: avg throughput 9685.81
    - 21.1.0.alpha3 threshold=1000: avg throughput 10017.62
    - 21.1.0.alpha3 threshold=0: avg throughput 9746.22
    - 20.2.5 vs 21.1.0.alpha3 threshold=0: **+0.6%**
    - 21.1.0.alpha3 (threshold 1000) vs 21.1.0.alpha3 (threshold 0): **-3.7%**
  - AWS:
    - 20.2.5: avg throughput 10260.21
    - 21.1.0.alpha3 threshold=1000: avg throughput 10589.77
    - 21.1.0.alpha3 threshold=0: avg throughput 10349.99
    - 20.2.5 vs 21.1.0.alpha3 threshold=0: **+0.9%**
    - 21.1.0.alpha3 (threshold 1000) vs 21.1.0.alpha3 (threshold 0): **-2.3%**

**Comment by yuzefovich** [comment]
It looks like there wasn't any pushback on our decision, so I think the issue of "choosing 0 as the default" can be closed.

Now the question is, do we want to remove the setting entirely in 21.1 release? I think we probably should lean on the safer side - keep the setting and remove it in 21.2 release. This will allow us to have a more fine-grained escape hatch that `vectorize=off`. Thoughts?

Another question is do we want to force all clusters to use the new default once they upgrade to 21.1? For some context, if the user has previously explicitly set the cluster setting to any value (including the previous default), that value will be kept after an upgrade.

**Comment by asubiotto** [comment]
Yeah, let's be safe and remove it in the 21.1 release. I think we shouldn't force clusters to use the new vectorized setting if they set it explicitly.

**Comment by yuzefovich** [comment]
Cool, that was my thinking as well. I'll open up a PR to remove the setting on master and will not backport it to 21.1.
