### ISSUE TITLE
sql: flaky alter_primary_key logictest

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#53915]
Hit this error locally (at 71a85a4b564b47d4b610849e36c13af17035acbb):
```
                    testdata/logic_test/alter_primary_key:1082: 
                    expected success, but found
                    (40001) restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_CLIENT_REJECT): "sql txn" meta={id=71677d48 key=/Table/SystemConfigSpan/Start pri=0.00911430 epo=0 ts=1599152572.462395199,2 min=1599152564.630070545,0 seq=32} lock=true stat=PENDING rts=1599152564.630070545,0 wto=false max=1599152565.130070545,0
                logic.go:1660: 
                     pq: restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_CLIENT_REJECT): "sql txn" meta={id=71677d48 key=/Table/SystemConfigSpan/Start pri=0.00911430 epo=0 ts=1599152572.462395199,2 min=1599152564.630070545,0 seq=32} lock=true stat=PENDING rts=1599152564.630070545,0 wto=false max=1599152565.130070545,0
```

**Comment by asubiotto** [comment]
Handing off to schema because they were thinking about retry errors in logic tests.

**Comment by ajwerner** [comment]
@RaduBerinde any chance anybody has any more details on this? I'm having a hard time reproducing it under roachprod-stress on 10 nodes for 30 minutes at the commit listed. I also ran it for 10 or so minutes on master. I'd expect this error to happen if the transaction record does not get heartbeated before it expires. Is it possible that there was a hardware problem on that test run?

**Comment by RaduBerinde** [comment]
Not that I know of, but I'm not sure what else might have been running at the time. What is the expiration period?

**Comment by ajwerner** [comment]
> Not that I know of, but I'm not sure what else might have been running at the time. What is the expiration period?

I think it's 5s.

**Comment by RaduBerinde** [comment]
I see, that's pretty small. It is conceivable that things got delayed by a few seconds due to the load (this is in a VirtualBox VM as well). We can close this since it's not reproducible. Thanks!
