### ISSUE TITLE
sql: perform fast-path point (not ranged) key-value deletes

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#53939]
Similar to https://github.com/cockroachdb/cockroach/issues/46758, but more important in the places where it is applicable.

`deleteRangeNode` is an optimization of `deleteNode` for executing DELETE statements in a single pass. It avoids a `ScanRequest` followed by a `DeleteRequest`, opting instead for a `DeleteRangeRequest` with the `ReturnKeys` option enabled. This is a nice win.

However, it conflates the idea of a single-pass write operation with that of a ranged write operation, probably because `DeleteRequest` itself does not have a `ReturnKeys` option or any other way to indicate whether it deleted an existing row or not. As a result, it comes with more trade-offs than strictly necessary. These trade-offs include everything discussed in https://github.com/cockroachdb/cockroach/issues/46758. They also include two other even more serious negatives:
- ranged KV writes (`DeleteRangeRequest`) cannot be pipelined because an enumeration of the intents that they will leave cannot be known ahead of time. They must therefore perform evaluation and replication synchronously.
- ranged KV writes (`DeleteRangeRequest`) result in ranged intent resolution, which is less efficient, especially until we [re-enable time-bound iterators](https://github.com/cockroachdb/cockroach/issues/53348).

We should explore issuing point `DeleteRequest` operations with a similar fast-path to the one `deleteRangeNode` contains in cases where the set of keys to be deleted is enumerable. To support this, `DeleteResponse` will need to indicate whether the specified key was deleted or not.

This comes up in TPC-C's `delivery` transaction, which issues a statement like the following. In traces, we see that the inability to pipeline these writes slows down the entire `delivery` transaction substantially.

```
DELETE FROM new_order
      WHERE no_w_id = 0
        AND (no_d_id, no_o_id)
            IN (
                    (3:::INT8, 2484:::INT8),
                    (5:::INT8, 2484:::INT8),
                    (4:::INT8, 2484:::INT8),
                    (8:::INT8, 2484:::INT8),
                    (9:::INT8, 2484:::INT8),
                    (1:::INT8, 2484:::INT8),
                    (10:::INT8, 2484:::INT8),
                    (2:::INT8, 2484:::INT8),
                    (6:::INT8, 2484:::INT8),
                    (7:::INT8, 2484:::INT8)
                );
```

Jira issue: CRDB-3818

**Comment by nvanbenschoten** [comment]
One interesting point that has come out of recent CDC discussions is that this change may impact the semantics of a DELETE of a non-existent row from the perspective of CDC consumer. This is because the change would lead to us writing MVCC tombstones on previously empty keys, where previously a `DeleteRangeRequest` would have not written anything at all. To a standard KV read of a non-existent row after it is DELETEd, this distinction is meaningless, because either way, the row will not be returned. However, to CDC, this may look strange, because an event will be emitted that a row was set to an empty value when the row did not previously exist. Even stranger, if CDC is using the `WITH diff` option, it will see an event that looks like `{"key": "a", "before": null, "after": null}`.

I'm not sure whether this is a problem or not. @stevendanna @HonoreDB do either of you two have thoughts about this? If this does break CDC semantics, we could potentially detect this condition at the rangefeed level and filter out these updates.

It's worth noting that while on the surface, it may seem like we could easily avoid this by _not_ writing an MVCC tombstone when a `DeleteRequest` finds a non-existent key, things aren't quite this simple. First, if it was to do so, it would then need to bump the timestamp cache instead, which adds some complexity. But more importantly, this would prevent `DeleteRequests` from being pipelined, which is one of the original motivations of this change.

**Comment by HonoreDB** [comment]
We discussed this recently and the consensus was that it's acceptable for the CDC behavior to be undefined on delete of a nonexistent row. We added a bit in the docs that you won't see an insert or non-null previous value, but *may* see a delete, to allow for optimizations. This seems easy to handle clientside, and you can already get the weird "before: null" message by inserting and deleting a row within a single transaction.

**Comment by andreimatei** [comment]
> It's worth noting that while on the surface, it may seem like we could easily avoid this by not writing an MVCC tombstone when a DeleteRequest finds a non-existent key, things aren't quite this simple. First, if it was to do so, it would then need to bump the timestamp cache instead, which adds some complexity. But more importantly, this would prevent DeleteRequests from being pipelined, which is one of the original motivations of this change.

Why exactly is it that `DeleteRequests` couldn't be pipelined if they don't write the respective intent? Is it because the `DeleteResponse` doesn't carry information about whether the intent was written or not? Cause we could add that to the response, couldn't we?

**Comment by nvanbenschoten** [comment]
> Is it because the DeleteResponse doesn't carry information about whether the intent was written or not? Cause we could add that to the response, couldn't we?

Kind of. As in https://github.com/cockroachdb/cockroach/issues/64723, we could use information from the response to permit evaluation-time pipelining even if we couldn't predict the set of keys the DeleteResponse would write an intent on. However, as in https://github.com/cockroachdb/cockroach/issues/64723, this would not allow us to permit commit-time pipelining (i.e. concurrent with parallel commit).

If we were only concerned about concurrent replication during a parallel commit and did not care about parallelizing the gateway<->leaseholder hops, then we could split up a BatchRequest containing `DeleteRequest`s and `EndTxn` requests in the client and issue the deletes with AsyncConsensus to mimic "evaluation-time pipelining".
