### ISSUE TITLE
import: CSV import does not work with collated strings

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#53957]
The following test in TestImpotData is failing:

https://github.com/cockroachdb/cockroach/blob/942b938f86fc933beb9ce1ac3d2e53007ed129b4/pkg/ccl/importccl/import_stmt_test.go#L257-L264

The error is: ` error parsing row 1: insert row: mismatched type "int" vs "CollatedStringFamily" for column "s" (row: "[1]")`

Epic CRDB-8816

**Comment by pbardea** [comment]
Not a release blocker, since it's not a regression from the previous version.

**Comment by adityamaru** [comment]
IMPORT will work with collated string columns if the CSV file has an explicit collation cast in front of every string that corresponds to a collated column in the table schema.

 For example, for a table with schema:

```
CREATE TABLE foo (a STRING COLLATE en_US_u_ks_level2);
```

We can import a CSV file with:
```
'dog' COLLATE en_US_u_ks_level2
```

This is in keeping with CRDBs treatment of operations on collated string types, as mentioned here - https://www.cockroachlabs.com/docs/stable/collate.html#details. Specifically, that non-collated strings cannot be used when interacting with a collated string column.

Note, CRDBs EXPORT feature to dump table data to CSV - https://www.cockroachlabs.com/docs/stable/export.html will write collated column values with the `COLLATE` cast, thereby making it roundtrippable.
