### ISSUE TITLE
import: PGDUMP imports do not suport ALTER SEQUENCE ... OWNED BY ...

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#53958]
The following TestImportData subtest is failing:

https://github.com/cockroachdb/cockroach/blob/942b938f86fc933beb9ce1ac3d2e53007ed129b4/pkg/ccl/importccl/import_stmt_test.go#L931-L948

**Comment by pbardea** [comment]
I'd say this isn't a release blocker, but it would be nice to fix. We would previously silently ignore this.

**Comment by otan** [comment]
This is a regression on v20.1 -- so I would argue it isn't great...
I guess users can delete these statements, but seems iffy.
