### ISSUE TITLE
wkt: unable to parse empty multipoint elements

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#53997]
**Describe the problem**

CockroachDB:

```
> select 'MULTIPOINT(1 1, EMPTY, 2 2)'::geometry;
ERROR: could not parse geometry: geos error: ParseException: Expected number but encountered word: 'EMPTY'
```

PostGIS:

```
# select 'MULTIPOINT(1 1, EMPTY, 2 2)'::geometry;
                                                                     geometry                                                                     
--------------------------------------------------------------------------------------------------------------------------------------------------
 0104000000030000000101000000000000000000F03F000000000000F03F0101000000000000000000F87F000000000000F87F010100000000000000000000400000000000000040
```

CC @otan

**Environment:**
 - CockroachDB version: `master` at `bc0e443cd9`
 - Server OS: macOS
 - Client app: `cockroach demo`

**Comment by otan** [comment]
another GEOS bug, it would seem.
do you mind filing an issue on GEOS and leaving a link here?
https://trac.osgeo.org/geos/ticket/1047 has an example WKB program I could compile with `g++ -o geos geos.cc -lgeos -lgeos_c -std=c++11` -- if not, I can get to it.
(alternatively, you can submit a PR if you felt game!)
