### ISSUE TITLE
Incremental BACKUPs to gs don't resolve previous incremental BACKUP folders correctly

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#54010]
While root causing #53932 I realized that the `findPriorBackupLocations` might not be returning the correct results for google storage as well.
The above-mentioned method is supposed to find any BACKUP sub-directories which match the glob `[0-9]*/[0-9]*.[0-9][0-9]/`. It does this by calling the ExternalStorage targets' `ListFiles` method. Both userfile and gs `ListFiles` method use a similar pattern where they find all filepaths with prefixes == the external storage path prior to the glob pattern, and then further filters it using `path.Match(match, globPattern)`. `path.Match` does not match prefixes as seen in - https://play.golang.org/p/QchOeN31vcv and so we are always returned an empty match.

This can be reproduced as follows:
```
CREATE TABLE foo (id INT);
BACKUP TABLE foo TO 'gs://cockroach-tmp/aditya-test/' AS OF SYSTEM TIME '-10s';
INSERT INTO foo VALUES (1);
BACKUP TABLE foo TO 'gs://cockroach-tmp/aditya-test/' AS OF SYSTEM TIME '-10s';
INSERT INTO foo VALUES (2);
BACKUP TABLE foo TO 'gs://cockroach-tmp/aditya-test/' AS OF SYSTEM TIME '-10s';

DROP TABLE foo;
RESTORE TABLE foo FROM  'gs://cockroach-tmp/aditya-test/';

ERROR: making import requests for 3 backups: no backup covers time [1599494189.257411000,0,1599494163.075177000,0) for range [/Table/52/1,/Table/52/2) or backups listed out of order (mismatched start time)
```

Switching to using `nodelocal` instead will make the above set of statements pass correctly, reason being nodelocal ListFiles uses `glob.Match()` which matches directory hierarchies and so we return the appropriate subdir where a previous backup was found.

**Comment by adityamaru** [comment]
cc: @pbardea just to make sure this is not caused by something I am inputting/understanding incorrectly.

**Comment by mwang1026** [comment]
Backport!

**Comment by adityamaru** [comment]
We don't need to backport this to 20.1 because we always looked for glob+backupManifestName in that version. This seems to have been a regression introduced after 20.1.
