### ISSUE TITLE
server: introduce versioning and pagination in the HTTP APIs

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#54022]
Today the HTTP APis are not versioned and not paginated:

- not versioned makes it hard to introduce or change functionality even with crdb's own internal client, because the APIs must behave well in mixed-version environments.

  By introducing versioning (e.g .in the URL) we make it easier to extend, substitute and deprecate functionality across multiple releases. IT also helps maintaining backward-compatibility by 3rd party tooling built by users.

- not paginated causes nodes to crash with OOM errors when the underlying resource is large, e.g. when retrieving log files, range/event logs, jobs tables etc.

**Comment by tbg** [comment]
re: the buffering, our HTTP APIs are generally derived from our proto API via grpc-gateway. Are these the ones you mean? Are there more specific problems you're aware of? Is the issue generally shared with the corresponding proto endpoint (i.e. we're just returning one giant response instead of a stream?

**Comment by knz** [comment]
yes and yes the issue is shared

**Comment by onno-vos-dev** [comment]
![Screenshot at 2020-09-16 10-11-51](https://user-images.githubusercontent.com/11063313/93310638-556db700-f805-11ea-8d8d-f82331a5e713.png)
@knz @tbg sorry to jump in on this ticket but could this issue be related to this ticket? I'm unable to view the `statements` page as of now as apparently my grpc payload is too big.

**Comment by knz** [comment]
@onno-vos-dev thanks for submitting the screenshot. The screenshot reports 5GB (!!) of payload, which I believe is not true -- i.e. there must be a bug in the way the error message was generated.

This looks like a separate issue which I will file for you.

**Comment by onno-vos-dev** [comment]
@knz Thank you! :+1: Let me know if you need any more information, happy to provide more if needed :+1: (And feel free to ping me in the issue so I can follow it)

**Comment by knz** [comment]
here #54439

**Comment by knz** [comment]
@itsbilal has achieved this.
