### ISSUE TITLE
build: Email release team when Publish Cockroach Release starts.

### ISSUE THREAD

**Issue by jlinder** [cockroachdb/cockroach#54055]
The release team wants to monitor when releases happen. We get emails for writes to S3 already, but we want to hear earlier in the process.

Make the Publish Cockroach Release build configuration email the release team when it starts so we can get an early alert that it is happening.

Epic DEVINF-156

Jira issue: CRDB-7996

**Comment by celiala** [comment]
The "Publish Cockroach Release" job posts details to the #release-ops Slack channel (started/completed), which solves for the intent of this ticket. Marking as done.
