### ISSUE TITLE
cli: Allow non-root users to generate a debug zip

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#54057]
Currently we only allow the root user to generate a debug.zip.  This should be extended to allow any user with the correct privileged to generate one.  

If you try to pass in the username, it seems like the only option is to use the --url parameter, but that give you this warning:
```
./cockroach debug zip debug.zip --url postgresql://bram@localhost
warning: --url specifies user/password, but command "zip" does not accept user/password details - details ignored
```

Many organizations are, for obvious reasons, averse to ever using a root user, even one in a db.

For now, I think requiring the user to be an Admin is fine.

**Comment by BramGruneir** [comment]
Assigning to @knz for triage.

**Comment by knz** [comment]
The issue right now is that the RPC authn code doesn't have access to SQL. This gets resolved when `debug zip` operates only using SQL.

**Comment by knz** [comment]
Debug zip is now able to use any admin client cert for authentication.
