### ISSUE TITLE
bulkio: add backup/restore mode to logic tests

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#54060]
The SQL Logic Tests test may interesting SQL use cases that backup/restore could leverage to dramatically increase test coverage of backing up and restoring a cluster in different environments.

The proposed idea here is that we could run the logic tests in a mode where at random points in the test, we backup the cluster and restore it into a new test cluster. We then continue running the logic tests and check that the results still hold. This would not only dramatically increase the coverage of backup/restore, but would also allow for integration issues with backup/restore to be raised earlier when implementing new SQL features.

The extent of the randomization of backup/restore testing is its integration with SQL smith. Backup/restore in SQL smith only checks that the command has run successfully. However, we could also imagine tests where every time a restore happens, we maintain 2 clusters and tee the commands to both clusters and ensure that both timelines (the restored cluster, and the backed up cluster) produce the same results.

**Some considerations/open questions:**
- We might want to dramatically increase the likelihood of triggering a backup/restore when logic tests are run on specific files
-  Can we ensure that the data distribution will be the same on the restored cluster? This might affect tests which examine the particular ranges? A short term solution here might be to ignore files that do these types of assertions.

Epic CRDB-7779

Jira issue: CRDB-3803

**Comment by awoods187** [comment]
@mwang1026 i'm a fan of this work and think we should continue to build it out. Tests will always trump process and this way we can't accidentally leave you in the lurch.
