### ISSUE TITLE
geo: add ST_S2Covering builtin

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#54070]
It would be super useful for debugging and visualisation if we had an `ST_S2Covering` builtin.

It may be so good, we'd want it in for v20.2.

I imagine it working like so:
```
SELECT
   ST_S2Covering(geom), -- default config
   ST_S2Covering(geom, 'min_s2_level = 5, other index settings...') -- use settings using the index WITH parameters.
```

And same for geography settings.

**Comment by otan** [comment]
cc @sumeerbhola d'ya reckon we should try get it into the v20.2 release?

**Comment by sumeerbhola** [comment]
I don't know if a user will bother with this. But it would be useful for us if the user is willing to share the output with us -- currently I just modify the code to add instrumentation but that isn't a viable option. It seems low-risk, so 20.2 would be good.
