### ISSUE TITLE
server: print restart history on startup

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#54102]
**Is your feature request related to a problem? Please describe.**
Overloaded clusters often restart in rapid succession, either due to out-of-memory errors or due to the orchestrator (k8s) restarting the process due to health probe failure. The history of restarts is, in principle, obtainable from the logs but in practice, you have to look to find it. Also, we have observed users being unaware of these restarts thanks to the miracle of orchestration.

We feel that a "recap" of recent restarts at the beginning of each process' logs will be instructive. This is similar in spirit to https://github.com/cockroachdb/cockroach/issues/27058. Cycling nodes can easily be spotted that way.

**Describe the solution you'd like**
On process start, node persists a current timestamp, retaining all such timestamps over the last (say) 24h.
Whenever multiple timestamps are found in the 24h window, log the most recent (say) 10.

We could also similarly persist graceful shutdowns (along with the signal) to complete the history.

**Describe alternatives you've considered**

**Additional context**

**Comment by tbg** [comment]
For implementation, it might be helpful to look at https://github.com/cockroachdb/cockroach/pull/55166 which also creates a new store-local key span.

We could also just stick to one key, so we could only log the most recent restart if it's recent. That might provide most of the benefit with much less work. It could follow the "last up" timestamp, https://github.com/cockroachdb/cockroach/blob/0fb876b0d241bf9376d249e52cd7b7134c11a49a/pkg/kv/kvserver/store.go#L2082-L2097, which is a key that is updated every time a node manages to heartbeat.

**Comment by cameronnunez** [comment]
After some discussion with @tbg and @bdarnell, we have determined that nothing needs to be done here. Node restarts are already logged as structured events, so they are not too difficult to find and probably are not important enough to be treated as a special case to be forced to the top of the logs.
