### ISSUE TITLE
tla-plus: to_check doesn't decrease during StageWritesAndRecordLoop

### ISSUE THREAD

**Issue by y-taka-23** [cockroachdb/cockroach#54130]
**Describe the problem**

In `StageWritesAndRecordLoop`, the `committer` process picks a key from pipelined `to_check` set one-by-one, then queries the state of the corresponding intent. Thus, the line:

```
to_check := to_check \union {key}
```

should be:

```
to_check := to_check \ {key}
```

**Comment by nvanbenschoten** [comment]
Hi @y-taka-23, thanks for the report and good spot! That line does look incorrect. Would you like to submit a PR to fix it?

Also, I'd love to hear about how you found this? I stumbled upon https://speakerdeck.com/ytaka23/cloudnative-days-tokyo-2020 on Twitter earlier today and was very impressed.

**Comment by y-taka-23** [comment]
> Would you like to submit a PR to fix it?

Of course yes! I'm going to do within this week.

> I'd love to hear about how you found this?

Actually just by chance. For demonstrating TLA+'s semantics, I tried to show "If the committer couldn't fail, `ImplicitCommitLeadsToExplicitCommit` holds without the recovery procedure". Concretely speaking:

* Make the committer process `fair`
* Delete the skip clause of "unsuccessful consensus" in `PipelineWrites`
* Delete the preventers

Against my expectation, TLC reported a temporary property violation with `QueryPipelinedWrite`-`StageWritesAndRecordLoop`  infinite loop.
