### ISSUE TITLE
server: tame down the verbose logs generated by background tasks

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#54131]
The logspy facility can be very useful to debug various issues. Unfortunately when it is enabled, there are a ton of verbose logs just from background work.

Here are the logs emitted in less than 18 seconds on an empty `cockroach demo` instance: https://gist.github.com/RaduBerinde/4c3d571b8227a3810b624c17e8a9d8ba

Feels like we could tame down some of these, e.g.
 * omit the "canceling context" stack trace if cancellation happens through an expected internal path
 * `[n1,s1] MaybeAdd` is very frequent and doesn't seem useful
 * `evaluated Merge command header` is also very frequent, though not sure if it is important to keep

**Comment by lucy-zhang** [comment]
@RaduBerinde would you mind clarifying why you put this on the SQL Schema board? We're definitely open to looking at our logging, just wasn't sure if you had anything specific in mind. I don't see anything that stands out from the output you posted.

**Comment by RaduBerinde** [comment]
Ah, I'm not sure, I might have thought the `context canceled` query is for a descriptor/schema operation. These logs show what these queries are for:
```
I200909 16:54:08.471940 3185 sql/txn_state.go:231  [n1,intExec=stmt-diag-poll] canceling context:
I200909 16:54:08.485136 3259 sql/flowinfra/flow.go:453  [intExec=expire-sessions] canceling context
I200909 16:54:08.503813 3268 sql/flowinfra/flow.go:453  [n1,intExec=update-session] canceling context:
I200909 16:54:08.487334 3260 sql/txn_state.go:273  [intExec=cancel/pause-requested] canceling context:
```

**Comment by knz** [comment]
We have successfully tamed down logspy already. Also it doesn't enable vmodule for all by default any more.
