### ISSUE TITLE
OPT: different execution plan selected when result tables are the same

### ISSUE THREAD

**Issue by xinyuliu12** [cockroachdb/cockroach#54169]
Hello everyone!

First off, I am sorry for gestures vaguely all of this. Second, I think we may have found a performance bug related to a suboptimal plan selection.

Here is a pair of TPC-H queries that exhibit this behavior.

```
SELECT    t12.o_orderdate 
FROM      ( 
                     SELECT     * 
                     FROM       "orders"   AS "orders3" 
                     RIGHT JOIN "lineitem" AS "lineitem1" 
                     ON         true) AS "t9" 
LEFT JOIN 
          ( 
                 SELECT "o_orderdate" 
                 FROM   "orders" offset 4 rowsFETCH next 1 rows only) AS "t12" 
ON        true FETCH next 40 rows only;


SELECT    * 
FROM      ( 
                     SELECT     * 
                     FROM       "orders"   AS "orders3" 
                     RIGHT JOIN "lineitem" AS "lineitem1" 
                     ON         true) AS "t9" 
LEFT JOIN 
          ( 
                 SELECT "o_orderdate" 
                 FROM   "orders" offset 4 rowsFETCH next 1 rows only) AS "t12" 
ON        true FETCH next 40 rows only;



```

**Actual Behavior**
The first query takes 5 seconds on the latest release v20.2.0-beta.1, while the second query only takes 18  millisecond.
The first query's "EXPLAIN ANALYZE" result is [here](https://cockroachdb.github.io/distsqlplan/decode.html#eJzEVNtu2kwQvv-fYjRXyS-XeO0lgK9CW2icEpyCK_UgVDl4kqxke93dtZoo4rH6An2yyjYECIeK9KK-8s7MN4dvvt1H1N8T9LD36WrQ9YfQHXYHn7_04OitPw7HHwbHMO4Nem9CMMxpyG9SxaTiyBD0R8ElHM2d_9fHyquhO57_uTDy352HcBH4Q0hERsJQWroX_wyCIRhV0HFpNR0Y9Prz8EXqjZrzIgP_0g-BQdDvj3sh8DoDcxYZ5wHcRgszGdMwSkmj9xUZTizMlZyS1lKVpscqwI_v0bMtFFlemNI8sXAqFaH3iEaYhNDDMLpOaERRTOqkTByTiURSpV2MdJYrkUbqAS0c51GmPXiFFgaF8WAoM0ILryMzvSMNsjB5aWZooSny5JnJD8CIlDxwGsxupxonMwvrgHl32kS3hB6bWS-bgK1PUBN7eP8t1-WbI7SadvmtD9Lhp51Wa_cozs5RlhMUWdUoxWvdT0rkn0K28HEe6bsLKTJSJ846HasjD0QqTK2lhG4MKPlDg6IorldV2bSJkmS5MpZqtFCJ27u18CUttWsV5Tbajt12Spw2UlEMWsTkQRW5hfjTTdarFumepoURMlt24_A257t5d18qIfdACZ01n9hkENzcaDLAX3AnWMPh--4E_5dC4uukhA85efXLFnwMe6PqfXsihG3R1FJoq_JoNuyW2-FbZcW2Coo1nE4z3dBTmRktTKN7SCmV6gEKTWUSG96L138hNOawXz93L6V5iMpGpHOZaXq-nK2Z7XIjFN9SvWEtCzWlKyWnVZn6GFS4yhCTNrXXqQ9-Vrmql3QVzA4AO8_Bzl4w31_ZPQC8UZnvBTfXwPZsMvvvdwAAAP__ikaVNw==).
The second query's "EXPLAIN ANALYZE" result is [here](https://cockroachdb.github.io/distsqlplan/decode.html#eJzEVN1um0gUvt-nGJ2rZHXWYQbsxFyNd9feEDkma1OpP7IqAicJEjCUGaqkkR-rL9AnqwC7qZ3ErZ1KvWPOfN93-M7P3IP-kIILw9cX44E3YYPJYPzm7ZAd_OvNgtn_40M2G46H_wTsTzaa-ufsYP2oyphKzQaz5ZfNpt5_pwE7870JS5OcEkNZfb365syfMFNWdFhHTZ-Nh6MlfCWt3jdacWhoLcnYO_cCxpk_Gs2GAXNaBS5WikuAYwFCrmKahBlpcN8BhzlCUaqItFZlHbpvAF58C66FkORFZerwHCFSJYF7DyYxKYELQXiZ0pTCmMqjWjgmEyZpI9v-lizKJAvLO0CYFWGuXfYXIPiVcZnkKAVKG6WDsouyh_IY5QnKPiBchia6Ic1UZYoazAHBVEW6EfJ8ZpKMXOZ0eradaZgvEFrA8o-1Ca8JXL7A_VzxdVerRu3lCyW3UHKOkguU3EbJHZS8i5L3AGGcZIlpG7Rpv_fYfoP75p93eL-_xb941v-D7SpvekbxmuV5zfwR5Ikinob65kwlOZVHYr2GL6gSSn6Mkp-g5H2UwkIpah2BUtgohYNSdLdX8olBanB0S1FlEpWvCmr1v3zWgJCFt-wjRUaVySeKWUaZKu9YmKYqCg3FLrM7FjtP_n629Pa-o2fvulAP1jnzr640GebssUu8Yzvbdsn5nbPkrBcluCvIbV9J_1UwnDZv5cs28WdmDKXovWC4nN4vmq3uLrM1JV2oXNNmS55Utuo-UHxNbV-1qsqILkoVNWnao9_wmkBM2rS3oj14eXPVvLvfk_kOZLFJFlvJzvbM9g7kR5mdreTuGtlazBd_fA0AAP__RlWMMQ==)

**Expected Behavior**
I would have expected the database system run these two queries with similar execution time, given that they compute the same result tables (the first query project only 1 column of the result table). 
Here are the steps for reproducing our observations:

**Test environment**

* Ubuntu 20.04 machine "Linux panda 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux"
* Cockroachdb v20.2.0-beta.1
* Database: TPC-H benchmark (with scale factor 5)

**Reproduce Bug**

1. Install cockroachdb v20.2.0-beta.1     

```
    $ mkdir -p $(go env GOPATH)/src/github.com/cockroachdb
    $ cd $(go env GOPATH)/src/github.com/cockroachdb
    $ git clone https://github.com/cockroachdb/cockroach
    $ cd cockroach
    $ git checkout eaa939c
    $ make build
    $ sudo make install
```

* start a cockroachdb node in your preferred working directory
```
    $ cockroach start --insecure --store=node1 --listen-addr=localhost:26257 --http-addr=localhost:8080 --join=localhost:26257,localhost:26258,localhost:26259 --background
    $ cockroach init --insecure --host=localhost:26257
```

2. Set up TPC-H test benchmark (if you already have a TPC-H benchmark set up, you can skip step2; starting from step2, all commands should run in the directory ./tpch5 after downloading and extracting it)

* Download TPC-H (scale factor of 5) and extract it
    Download the dataset from the link: https://drive.google.com/file/d/1MLVFPKdRQhlRgmeRIumyIj8NBMRSQ3um/view?usp=sharing
```
    $ tar xzvf tpch5_setup.tar.gz
    $ cd tpch5
    $ chmod +x setup.sh
```

* Create DB and TPC-H schema
`   $ cockroach sql --insecure --host=localhost:26257`    
    In CockroachDB's built-in SQL client to create database:
```
    $ create database tpch5;
    $ exit
```
* Create TPC-H Schema
   `    $ cockroach sql --insecure --host=localhost:26257 -d tpch5 < dss.ddl
`
* Set up benchmark
```  
    $ ./setup.sh
    $ cockroach sql --insecure --host=localhost:26257 -d tpch5 < dss.ri

```
3. Test SQL query that exhibits performance issue
* Execute the queries after logging to the testing benchmark using the following command
`    $ cockroach sql --insecure --host=localhost:26257 -d tpch5
`

Jira issue: CRDB-3791

**Comment by solongordon** [comment]
cc @RaduBerinde

**Comment by RaduBerinde** [comment]
Interesting, thanks for the report! In the second query, we pushed down a limit of 40 into the lineitem scan; in the first query we didn't. That is one thing to investigate.

The larger problem, however, is that the optimizer doesn't take into account that the hash joiner will not consume all of its left input (because of the limit). That is tracked under https://github.com/cockroachdb/cockroach/issues/43438

@xinyuliu12 could you attach the bundle generated by `EXPLAIN ANALYZE (DEBUG)` for each query? That is the preferred information when filing issues, as it contains much more information (including the optimizer plans).

**Comment by RaduBerinde** [comment]
The limit of 40 doesn't get propagated in the first case because the joined tables don't have any columns and that prevents some of the join multiplicity logic from firing. I'm not sure it's worth trying to fix it for such an unrealistic case.

In any case, propagating soft limit hints should address the problem.

**Comment by xinyuliu12** [comment]
Thanks for taking a look at! Would you feel comfortable to clarify why the joined tables don't have any columns? I don't understand what tables you are referring to.
We also have another issue to report so we want to make make sure it will not be a duplicate of this one.

**Comment by RaduBerinde** [comment]
In the first query, we aren't selecting any columns from `orders3` and `lineitem1`, so we end up doing a join between "tables" of empty rows (I'm not referring to the base tables, but to the conceptual tables that are joined).

From plan.txt in the bundle (the `()` are the columns produced by that node):
```
 │    └── cross join (inner)                                         ()
 │         │                  estimated row count  224998462500000
 │         ├── scan                                                  ()
 │         │                  estimated row count  29999795
 │         │                  table                lineitem@primary
 │         │                  spans                FULL SCAN
 │         └── scan                                                  ()
 │                            estimated row count  7500000
 │                            table                orders@primary
 │                            spans                FULL SCAN
```

**Comment by xinyuliu12** [comment]
Thank you so much for your explanation!
