### ISSUE TITLE
catalog: auto-generate grafana dashboards [deprecated]

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#54178]
**Is your feature request related to a problem? Please describe.**
We over-rely on our built-in AdminUI. Production users are supposed to use Prometheus or one of its siblings (Graphite, etc). But - we have no good dashboards to give them other than what CC uses at any given point in time (and that we don't distributed proactively).
This makes for a poor story.

**Describe the solution you'd like**

We should use the catalog:

https://github.com/cockroachdb/cockroach/blob/e43acc9b020fa117d5ca10249f6108602061e346/pkg/ts/catalog/chart_catalog.go#L32

to auto-generate Grafana dashboards.

**Describe alternatives you've considered**
I don't see an obvious better alternative. We can continue doing little, but it seems sub par.

**Additional context**
Lots of great synergy here with https://github.com/cockroachdb/cockroach/issues/46103, which also relies on Grafana. We look at timeseries quite a lot during debugging, and I'm sure this would see use and would help us dog food the catalog's organization to make sure it's helpful.

Epic: CRDB-25656
Jira issue: CRDB-3789

**Comment by tbg** [comment]
@piyush-singh I'm not sure which project to put this into. Mind lending a hand?

**Comment by tbg** [comment]
Cross-posting from https://github.com/cockroachdb/cockroach/issues/16584#issuecomment-704927971 since I'm closing that issue:

No, nothing we're actively working on due to bandwidth constraints. However - the combination of the WIPs https://github.com/cockroachdb/cockroach/pull/50728 and https://github.com/cockroachdb/cockroach/pull/50432 would give us raw timeseries data in `debug.zip`. We already have a "baby setup" to visualize this dump locally:

https://github.com/cockroachdb/cockroach/blob/master/scripts/localmetrics/README.md

However, this doesn't just give you the timeseries to explore, you have to set each one up individually - not ergonomical. So we'd also want this:
https://github.com/cockroachdb/cockroach/issues/46103
which is basically
https://github.com/cockroachdb/cockroach/issues/54178.

I'm happy to advise here - but as said, unlikely that the KV team will be picking this up. It's possibly a good area that we could contract out, though I have no experience on how well that works in general.

**Comment by joshimhoff** [comment]
I'm +1 on this. Was thinking about doing something similar to just manage duplication in existing CC grafana config. I like the convergence between grafana & admin UI this gets us. FWIW, SRE leans on grafana much more than admin UI metrics; we barely look at admin UI metrics (we look at admin UI often but time-series metrics in admin UI rarely). Grafana is a much more fully featured time-series metric visualizer in my opinion.

One thing I worry about a bit is that grafana is more flexible than admin UI (this is more an impression than something I've thought a lot about concretely). If we do this, I think we need to find ways to express grafana "stuff" even if not available in admin UI. One way of making sure we kinda hit this "requirement" is getting the proposed code to generate CC's current grafana configs. 

Another thing to think about is making the abstact-dashboard-to-grafana-config logic decoupled enough from the CRDB codebase that we can use it to manage CC grafana config that is CC specific (e.g. the SQL prober dashboard page). Seems like a waste of effort to not do this. There will be grafana config that is CC specific, I think.

**Comment by piyush-singh** [comment]
cc @thtruo - I know you are having conversations with David and Nam about future projects on the Observability team. I think this is a particularly good one that I'd like to put back onto the team's radar. It will benefit L2 engineering support, customer support, the SRE team, and our customers. We publish grafana configs in our repo that we point customers to when they inquire about monitoring and alerting - it would be great to keep this in sync with both the admin UI and the dashboards our SRE team uses to monitor Cloud.

We discussed this as part of problems to solve, but we held off on this in favor of other work we had already started. Since we may revisit our prioritization, it is probably worth raising this with the team.

**Comment by awoods187** [comment]
I'm a +1 on this too. I have notes forthcoming but many customers just want to put everything in grafana and we should help them do this easily.

**Comment by dhartunian** [comment]
Recent discussion with additional context: https://cockroachlabs.slack.com/archives/CHVV403F0/p1669034436924239

**Comment by tbg** [comment]
Moved this to [CRDB-25656](https://cockroachlabs.atlassian.net/browse/CRDB-25656) for clean-up. I think there has been some evidence that encoding the dashboard in internal-tsdb code is too cumbersome. I now favor building Grafana/prom dashboards and having some (manual, probably) process to periodically update the DBConsole dashboards from them. Velocity and expressiveness in Grafana is orders of magnitude better and we ought to be taking use of that.
