### ISSUE TITLE
server: properly secure /debug/{events,requests}

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#5419]
The `/debug/{events,requests}` endpoints are currently accessible to anyone and sensitive information (e.g. SQL statements) are visible to anyone accessing them from localhost. We should restrict access to "root" users and the user who made the request.

**Comment by spencerkimball** [comment]
Changing the milestone to `Later`. This also is subsumed by #6307.

**Comment by bdarnell** [comment]
> visible to anyone accessing them from localhost.

It's not even restricted to localhost now. I think we need to do something about this for 1.0 (even if it's just a flag to disable the `/debug` pages)

**Comment by spencerkimball** [comment]
It would be pretty inconvenient if it were limited to localhost for our debugging. I like the idea of a flag, though it seems better to have this **enabled** via a flag instead of disabled. We need volunteers for this.

**Comment by petermattis** [comment]
We have `COCKROACH_DISABLE_SQL_EVENT_LOG` (`/debug/events`) and `COCKROACH_DISABLE_TRACING` (`/debug/requests`). When the settings table arrives, we could place the controls there instead. I think @bdarnell has suggested we should default these to disabled.

**Comment by tamird** [comment]
localhost is not that inconvenient. If you own the machine, you can set up
a tunnel.
