### ISSUE TITLE
*: avoid direct syscalls on darwin

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/cockroach#54193]
Support for direct syscalls was dropped from the golang.org/x/sys package: https://github.com/golang/sys/commit/6fcdbc0bbc04dcd9e7dc145879ceaf9bf1c6ff03#diff-4913a9178621eadcdf191db17915fbcb

This causes compilation failures when `go get` pulls in the current version of sys.

```
# github.com/docker/docker/pkg/term
vendor/github.com/docker/docker/pkg/term/tc.go:13:28: undefined: unix.SYS_IOCTL
vendor/github.com/docker/docker/pkg/term/tc.go:18:28: undefined: unix.SYS_IOCTL
vendor/github.com/docker/docker/pkg/term/termios_bsd.go:24:31: undefined: unix.SYS_IOCTL
vendor/github.com/docker/docker/pkg/term/termios_bsd.go:37:31: undefined: unix.SYS_IOCTL
# github.com/cockroachdb/cockroach/pkg/util/log [github.com/cockroachdb/cockroach/pkg/util/timeutil.test]
pkg/util/log/stderr_redirect_unix.go:35:32: undefined: unix.SYS_FCNTL
# github.com/cockroachdb/cockroach/pkg/util/log [github.com/cockroachdb/cockroach/pkg/util/caller.test]
pkg/util/log/stderr_redirect_unix.go:35:32: undefined: unix.SYS_FCNTL
# github.com/cockroachdb/cockroach/pkg/util/log
pkg/util/log/stderr_redirect_unix.go:35:32: undefined: unix.SYS_FCNTL
# github.com/cockroachdb/cockroach/pkg/util/log [github.com/cockroachdb/cockroach/pkg/util/log.test]
pkg/util/log/stderr_redirect_unix.go:35:32: undefined: unix.SYS_FCNTL
```

Go 1.11 release notes:
>   On macOS and iOS, the runtime now uses libSystem.dylib
>    instead of calling the kernel directly. This should make
>    Go binaries more compatible with future versions of
>    macOS and iOS. The syscall package still makes direct
>    system calls; fixing this is planned for a
>    future release.

Jira issue: CRDB-3788

**Comment by jbowens** [comment]
A docker dependency moby/term#15 also needs to be updated to use the `unix.Ioctl*` wrappers.

**Comment by knz** [comment]
So now we have two issues on our hands:

- `docker/docker` renamed to `moby/moby`
- the `moby/term` dependency is borked, whereby `go get -u` does not work because of some case insensitive import

I'll send a draft PR but that will need some help.

**Comment by knz** [comment]
still relevant

**Comment by knz** [comment]
actuall not relevant any more
