### ISSUE TITLE
ui: Clear contract for metrics provided by CockroachDB

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#5421]
We should provide a clear contract for the metrics provided by CockroachDB. 

In current code, metrics are constructed ad-hoc inside of our various components by adding them into a metrics registry. In turn, time series and status summaries are recorded by iterating over the metrics contained in the registries.

However, there is no clear contract describing which metrics are recorded; this will make it difficult for them to be consumed by any third-party product.

A strategy should be developed for maintaining a clear "contract" of metrics - this includes knowledge of what each metric represents, and how each metric can be queried. It should be possible to verify that a cockroach build is meeting the contract; it would also be nice for this contract to inform our documentation.

**Comment by cuongdo** [comment]
I think that in terms of code, having named metrics with types is a great
starting point. The documentation could also be part of the contract, since
those describe semantics.

For example, I've spent a lot of time with these MySQL docs in the past
(and can attest to their helpfulness):

http://dev.mysql.com/doc/refman/5.7/en/server-status-variables.html

**Comment by spencerkimball** [comment]
@mberhault, from a practical perspective, can this issue be closed with our Prometheus configs and the point-in-time stats page to query all of our metrics?

**Comment by mberhault** [comment]
I think the main actionable item here is to make sure that all metrics have clear names and useful descriptions. This is currently far from being the case.

**Comment by spencerkimball** [comment]
If you expect this to be done for 1.0, please set the milestone.

**Comment by mberhault** [comment]
`later` is fine for this.

**Comment by mberhault** [comment]
@mrtracy: This has been sitting around for a while. Do you have further thoughts?

**Comment by mrtracy** [comment]
@mberhault: I think the work @sploiselle is doing will satisfy this.  Sean, do you have a github issue you're updating for your current metrics work? This bug could likely be closed as a duplicate of that issue, if it exists.

**Comment by mberhault** [comment]
@piyush-singh: reassigning for triage.
