### ISSUE TITLE
ui: Commit to a state container for our website

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#5422]
It's clear at this point that our website desperately needs a state container.  Mithril's "controller/component" model offers almost no meaningful organization of model data, and what has resulted is a jumbled and nearly unmanageable mess.  It still works, but I think it is dangerously close to crippling the efficacy of our UI development.

I am proposing that, in very early post-beta work, we re-write our typescript model code to make use of a specific javascript state container: [Redux](http://redux.js.org/index.html).  It is extremely popular, well documented, and in general very compelling.  It is certainly better than our current solution for managing model data, which is essentially _nothing_.

We do not have to rewrite completely away from mithril to implement this; mithril can still serve as the view layer of our application, with redux taking over responsibility for our data model.

**Comment by cuongdo** [comment]
This would be a useful effort for sure. The interactions between our
controllers and models are ad-hoc, to the detriment of the readability of
our UI code. Let's discuss frameworks a bit before committing to a
framework. The UI code is currently small enough that putting something
like Redux in wouldn't take too long. That won't always be the case, so
changing our minds again later will be significantly more costly.

**Comment by maxlang** [comment]
It appears we've already settled on a rewrite with react/redux. @mrtracy are you ok closing this?

**Comment by mrtracy** [comment]
Yes, this should be closed.
