### ISSUE TITLE
rpc: gRPC dial timeout can be set to 0 when not blocking

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#5423]
See https://github.com/cockroachdb/cockroach/pull/5420#issuecomment-199056169.

If RPCs are bounded by a `context.WithCancel` and not blocking on dialing, we don't need to set a dial timeout.

**Comment by tamird** [comment]
The only place that `grpc.WithTimeout` is used is in server/server.go when bootstrapping grpc-gateway and this usage is documented. All previous usages were removed in #7249, so I suppose that PR fixed this issue.
