### ISSUE TITLE
sql: support CONNECTION LIMIT for CREATE DATABASE

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#54241]
PostgreSQL supports a CONNECTION LIMIT for CREATE DATABASE.

We currently support -1, but nothing else.

Epic CRDB-13333

Jira issue: CRDB-3784

**Comment by rafiss** [comment]
related "connection limit" things: https://github.com/cockroachdb/cockroach/issues/47969 https://github.com/cockroachdb/cockroach/issues/47602

just to make sure similar problems don't get solved in disagreeable ways.
