### ISSUE TITLE
sql: ALTER RELOCATE not supported in multi-tenant mode

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#54250]
the ALTER ... RELOCATE statement doesn't work in multi-tenant mode because it needs gossip.

Jira issue: CRDB-3781

Epic CRDB-18503

**Comment by knz** [comment]
cc @asubiotto for triage

**Comment by asubiotto** [comment]
Do we want tenants to be able to issue `ALTER RELOCATE` statements successfully? Maybe in a distant future (cc @tbg). In any case, I think this belongs with the team that owns `ALTER RELOCATE` which I think might be schema? I'll circle back on this.

**Comment by tbg** [comment]
I don't think there are any plans here currently and nothing needs to be done.

**Comment by asubiotto** [comment]
Moving this to the SQL Features board since multitenancy is a horizontal concern and they are the `ALTER RELOCATE` owner. This issue can probably just be moved to a backlog.
