### ISSUE TITLE
sql: INT range overflows not reported as such

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#5429]
As far as I understand, all accepted int types (`int`, `integer`, `smallint`, `int64`, `bigint`) are treated as 64-bit signed integers, with a range from -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807. When you insert a column with a value above or below this range, you get an incorrect error message:

```
root@:26257> create table ints (a int, b bigint, c integer);
CREATE TABLE

root@:26257> show columns from ints;
+-------+------+-------+----------------+
| Field | Type | Null  |    Default     |
+-------+------+-------+----------------+
| a     | INT  | true  | NULL           |
| b     | INT  | true  | NULL           |
| c     | INT  | true  | NULL           |
| rowid | INT  | false | unique_rowid() |
+-------+------+-------+----------------+

root@:26257> insert into ints values (9223372036854775809, 2, -10348);
pq: value type float doesn't match type INT of column "a"

root@:26257> insert into ints values (-9223372036854775809, 2, -10348);
pq: value type float doesn't match type INT of column "a"
```

I'd suggest an error message like: `for type INT, value must be between -9223372036854775807 and 9223372036854775808`

**Comment by knz** [comment]
Thanks to the new type system now at least the two cases report the same error (can't assign DECIMAL to INT column.) 

@jseldess  I think it may be ok to explain in our docs that values get automatically promoted to decimal whenever they dont fit the limits of INT.

@nvanbenschoten is there any way we could improve the error message?

**Comment by jseldess** [comment]
@knz, I'm not seeing that behavior. I still get an error, but now with `decimal` instead of `float`. Any ideas?

```
root@:26257> create table int (a serial primary key, b int, c decimal);
CREATE TABLE

root@:26257> insert into int (b, c) values (1, 2.3);
INSERT 1

root@:26257> insert into int (b, c) values (9223372036854775809, 2.3);
pq: value type decimal doesn't match type INT of column "b"
```

**Comment by spencerkimball** [comment]
Assigning this to @nvanbenschoten and adding the `known-limitation` label. @nvanbenschoten if you think this can't be done for 1.0, please adjust the milestone.

**Comment by nvanbenschoten** [comment]
I'll be able to get this fixed within the next week, so we can leave the 1.0 milestone.
