### ISSUE TITLE
transaction failed because of heartbeat delaying to send 

### ISSUE THREAD

**Issue by logic-jin** [cockroachdb/cockroach#54298]
**Describe the problem**
In a normal case, it should success. but throw error,
error:pq: restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_CLIENT_REJECT)ta={id=eb2d75fd key=/Table/60/1/1/0 pri=0.00029518 epo=0 ts=1596250119.822271003,2 min=1596250094.757497608,0 seq=1=ABORTED rts=1596250094.757497608,0 wto=false max=1596250095.257497608,0

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. create table t1 (a int);
2.insert into t1 values (111);
3.there are two transactions:
![image](https://user-images.githubusercontent.com/69946834/92985902-71154c80-f4e9-11ea-9df5-08ab794f348e.png)

export Transaction1 execute success,but find error:
pq: restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_CLIENT_REJECT)

**Expected behavior**
Transaction2 's statement that is select * from t1, should be waitting until Transaction1 is committed.

**Environment:**
 - CockroachDB version [2.1.4]
 - Server OS: [Linux]
 - Client app [`cockroach sql`]

**Comment by asubiotto** [comment]
Hi @logic-jin,

This looks like a transaction retry error. You should handle these in your client app as specified [here](https://www.cockroachlabs.com/docs/v20.2/transactions#client-side-intervention). The specific meaning of your retry error can be found [here](https://www.cockroachlabs.com/docs/v20.2/transaction-retry-error-reference.html#abort_reason_aborted_record_found)
