### ISSUE TITLE
create database permission less??

### ISSUE THREAD

**Issue by yuchao86** [cockroachdb/cockroach#5433]
```
┌─[yuchao@YuChaodeMacBookPro] - [~/Lab/cockroach10.9] - [一  3 21, 05:54]
└─[$] <> ./cockroach sql
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
root@:26257> create database bank;
pq: Private key file has group or world access. Permissions should be u=rw (0600) or less.
root@:26257>
```

**Comment by yuchao86** [comment]
one moment later 

root@:26257> E160321 17:56:34.964522 storage/queue.go:509  [replicate] 5 replicas failing with "0 of 1 store with an attribute matching []"
root@:26257> ^D
Failed running "sql"

**Comment by knz** [comment]
So here the two things you are seeing are unrelated from each other.

The first message indicates that the certificate key you have created is not protected by the right permissions. You can adjust this using `chmod`. 

The second message is related to cluster replication. It might be expected. Before we answer that, just to clarify: did you start the database server (`cockroach start`) in the same terminal, or was it a different terminal?

**Comment by nvanbenschoten** [comment]
@knz, It seems that there are some issues with the `--database` flag when using the string given on cluster startup, even with the correct file perms. It looks like something's getting messed up [here](https://github.com/lib/pq/blob/fde2b33cb1c820fbd3ff19eb9414be2d86b1bd12/conn.go#L1083). That said, specifying the certs separately with `--ca-cert=certs/ca.cert --cert=certs/node.cert --key=certs/node.key` works fine.

**Comment by nvanbenschoten** [comment]
It looks like the permission error is actually the result of not correctly specifying the certs in the sql flags (as I did using the `--database` flag instead of the `--url` flag). For instance, the error shows up when `./cockroach sql` is run with no flags. I'll make this throw a more obvious error.

**Comment by yuchao86** [comment]
i got , thanks all gays.

**Comment by yuchao86** [comment]
I come from Beijing, how many company deploy this cockroach databases to product systems?

**Comment by nvanbenschoten** [comment]
@yuchao86, CockroachDB is still currently in alpha release cycle, so at the time being we have been discouraging companies from using the system in production. That will change soon though... stay tuned for our beta!

**Comment by yuchao86** [comment]
@nvanbenschoten ,Thank you, right now , we using Mysql as database. 
how many different transfer ability of data from Mysql to Cockroach ?
