### ISSUE TITLE
sql: include session remote execution memory usage in sessions page

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#54339]
#25395 added memory usage information to `SHOW SESSIONS` so that operators could see how much memory a given session was using/its high watermark. However, this only took into account gateway memory usage. This issue tracks adding remote execution information. We'll probably simply want to `sum(current_memory_usage on each node), max(max_memory_usage on each node)`.

Jira issue: CRDB-3772

**Comment by knz** [comment]
> We'll probably simply want to sum(current_memory_usage on each node), max(max_memory_usage on each node).

I don't know that's true. If we sum, then we will lose the ability to compute memory usage as a % of total RAM on each node.

I think we need to report the memory usage separately for each node that participated in a query.

**Comment by awoods187** [comment]
We will probably want both the memory used in total for the session and a per-node usage for % of ram used per node. Especially as we move serverless the latter will be a less useful metric.

**Comment by knz** [comment]
> as we move serverless the latter will be a less useful metric.

it may be less useful for the end-user, but it's very important for troubleshooting memory usage issues. If the memory usage spikes on just 1 node and the others are "quiet" it may appear in the sum to be equivalent to another query that has a more even memory usage. However the spike is problematic. We need to keep a way to detect that for troubleshooting purposes.

**Comment by maryliag** [comment]
No longer a priority
