### ISSUE TITLE
execstats: collect maximum flow memory usage

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#54340]
Memory monitors can report a high watermark of memory usage. We should think about how to return/display maximum memory usage of a query.

**Comment by asubiotto** [comment]
I think exposing this in the statements page is going to be extremely useful because it'll allow users to sort by max memory used cc @jordanlewis

**Comment by jordanlewis** [comment]
I agree. FYI, We already have it in the sessions page:

![image](https://user-images.githubusercontent.com/43821/94812209-6e10cc00-03c4-11eb-87ad-e4b5eda751fc.png)

**Comment by awoods187** [comment]
This is a great idea!

**Comment by cathymw** [comment]
The approach I'm currently using to get query max memory usage is to take the MaxAllocatedMem of all processors on a node, and then taking the max from all the nodes. But during my chat with @jordanlewis today he mentioned that we may have cases where we want to sum the allocated memory of processors in a flow, and that perhaps we can get the appropriate value from the parent memory monitor (which updates the allocated memory for the flow). We were wondering if you either of you had any thoughts on this? @asubiotto @yuzefovich

**Comment by yuzefovich** [comment]
I think we are actually mostly interested in the aggregated memory usage of the whole flow and not the individual processor/operator maximum, so I agree with Jordan. My thinking is that the aggregated memory is a better representation for a query's memory footprint and providing more detailed view into which processors use the most out of the aggregated usage could be shown as a finer detail that is hidden by default.

In order to get that info you could access the "flow" monitor (instantiated in `ServerImpl.setupFlow`) which is also the one that `evalCtx.Mon` is pointing to. (A side note that sometimes that monitor might be replaced with "txn" monitor, but both should work well for this use case.)

**Comment by asubiotto** [comment]
That's a good point, if you have 10 processors that are each using a max of 500mb, you can't just say the flow used 500mb if all processors hold on to that buffered data simultaneously (e.g. left and right side of a merge join are sorts). Summing the memory might not be correct, because the memory usage of two processors might happen at two independent points in time (so summing them doesn't give you useful data), but what would be correct is getting the higher-level flow memory usage, since that is a parent monitor to all processors.

We'll have to attach this data to the trace somehow. I think the flow has a high-level span, but it gets finished in `Cleanup`, which will happen after the last outbox has exited. Since we need to send this data back to the gateway somehow, we'll probably have to get the last outbox to send over the recording of this span, or attach these stats somewhere else in the trace.

**Comment by awoods187** [comment]
In some waysm it would be nice to know the max memory used at any point in the query in addition to the total used and the total per operator. I think as a first pass, total used in the query, whether in parallel or not, is the most important.

**Comment by asubiotto** [comment]
> it would be nice to know the max memory used at any point in the query

I think this is the most important part because it lets users understand query memory usage and compare it with their expectation and how much memory is available to cockroach. Total used memory (sum of each processor's memory usage) doesn't seem useful to me.
