### ISSUE TITLE
sql/multitenancy: make `SHOW CLUSTER QUERIES` return an error

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#54342]
#53211 added support for `SHOW QUERIES` for tenants. Since tenants are limited to a single SQL pod, the implementation only returns the local queries/sessions when `SHOW CLUSTER QUERIES` is run. Once tenants have multiple SQL pods, this will be incorrect, since queries in the session registries of other nodes will not be reported.

We need to change `SHOW CLUSTER QUERIES` to return an error until it can be implemented properly. For now, there isn't an immediate problem.

**Comment by kevin-v-ngo** [comment]
Closing, this should be handled with pod-to-pod communication
