### ISSUE TITLE
sql: add connection limit syntax

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#54400]
In this [issue](https://github.com/cockroachdb/cockroach/issues/54116), we plan to support `CONNECTION LIMIT = -1` as a no-op. This issue tracks a general purpose implementation of `CONNECTION LIMIT = foo` on a per database limit.

**Comment by rafiss** [comment]
duplicate of https://github.com/cockroachdb/cockroach/issues/54241
