### ISSUE TITLE
backupccl: fix drop behavior for public descriptors on RESTORE fail/cancel

### ISSUE THREAD

**Issue by thoszhang** [cockroachdb/cockroach#54403]
Currently, the restore job makes all newly added descriptors public only after the user table data has been restored. However, this precedes restoring system tables, and `OnFailOrCancel` can invoked in a state where all user descriptors are already public.

In this case, we need to queue drop jobs for all the descriptors instead of simply deleting them. Deleting descriptors without passing through the dropped state first can cause prior leased descriptors to not be released until expiration.

A related problem is that we don't currently check whether schemas have had any children added in the interval when they became public. This could lead to orphaned descriptors. This is much less of a risk now that for long-running restore jobs, the schemas will be in the offline state for most of the duration of the job, but it's still possible.

Epic CRDB-8816

Jira issue: CRDB-3766

**Comment by lucy-zhang** [comment]
This isn't a release blocker for 20.2 but we'd like to get it in if possible. I'll update statuses elsewhere once the process becomes more clear.

**Comment by lucy-zhang** [comment]
This change is large enough that in the interests of stabilizing 20.2.0, we'll aim for 20.2.1 for this change.

**Comment by lucy-zhang** [comment]
#55157 fixes the potential orphaned descriptor issue when cleaning up restored schemas. The remaining work, to drop descriptors in a schema change job if they're already public, is more involved and not especially high-impact. We'll push it to 21.1.
