### ISSUE TITLE
server: redactable logs flips bits when printing pointers

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#54424]
This on the face of it will seem completely bizarre, but I believe I am not a crackpot.
When running with `--redactable-logs` (the default), some of the pointers printed with `%p` appear to be slightly mangled. I am printing two pointers that I have just assigned to one another, and the values printed differ slightly. This does not happen with `--redactable-logs=false`. 

I'm printing the two pointers here:
https://github.com/andreimatei/cockroach/blob/45fa1e25bd6f091fae31b3e96f8766f12bf3c01e/pkg/kv/kvclient/kvcoord/range_cache.go#L399
The two variables should be equal, and in fact I check their equality and panic just below.

The values that I get printed are consistently different when running with redactable logs. The values differ sometimes by 32, sometimes by 64, sometimes by two low bits.
Here's an example:
```
[andrei:~/work/src/github.com/cockroachdb/cockroach] debug.restore2tb+ ± rg -a 'about to insert' ~/local/1/logs/
/Users/andrei/local/1/logs/cockroach.Andreis-MacBook-Pro.andrei.2020-09-15T21_38_07Z.080839.log
206:I200915 21:38:13.173154 412 kv/kvclient/kvcoord/range_cache.go:399 ⋮ [n1,liveness-hb,range-lookup=‹/Meta2/System/NodeLiveness/1/NULL›] !!! updating lease: about to insert: ‹desc:r1:/{Min-System/NodeLiveness} [(n1,s1):1, (n5,s5):2, (n2,s2):3, (n3,s3):4, (n4,s4):5, next=6, gen=8], lease:repl=(n5,s5):2 seq=7 start=1600205870.049366000,1 exp=1600205902.004983000,0 pro=1600205893.004991000,0› (0xc00232d000 = 0xc00232d020)
662:I200915 21:38:17.490875 207 kv/kvclient/kvcoord/range_cache.go:399 ⋮ [n1,intExec=‹log-event›,txn=‹8091ce14›] !!! updating lease: about to insert: ‹desc:r8:/Table/1{2-3} [(n1,s1):1, (n5,s5):2, (n2,s2):3, (n4,s4):4, (n3,s3):5, next=6, gen=8], lease:repl=(n5,s5):2 seq=5 start=1600205897.291520000,0 epo=4 pro=1600205897.291528000,0› (0xc00201b680 = 0xc00201b6a0)
734:I200915 21:38:17.548535 559 kv/kvclient/kvcoord/range_cache.go:399 ⋮ [n1,intExec=‹insert-session›,txn=‹976bebe2›] !!! updating lease: about to insert: ‹desc:r35:/Table/{39-53} [(n1,s1):1, (n5,s5):2, (n4,s4):3, (n2,s2):4, (n3,s3):5, next=6, gen=9], lease:repl=(n5,s5):2 seq=6 start=1600205897.288771000,0 epo=4 pro=1600205897.288778000,0› (0xc00243c540 = 0xc00243c560)
896:I200915 21:38:18.505330 1352 kv/kvclient/kvcoord/range_cache.go:399 ⋮ [intExec=‹expire-sessions›,n1,txn=‹61182e54›] !!! updating lease: about to insert: ‹desc:r11:/Table/1{5-6} [(n1,s1):1, (n4,s4):2, (n3,s3):3, (n5,s5):4, (n2,s2):5, next=6, gen=8], lease:repl=(n5,s5):4 seq=5 start=1600205898.136825000,0 epo=4 pro=1600205898.136888000,0› (0xc0029f0840 = 0xc0029f0860)
```

I dug through the formatting code copied from the stdlib and didn't find anything, but when I tried to dig a 2nd time I got lost.
@knz what do you make of this?

**Comment by knz** [comment]
The code certainly does not preserve pointer values through printing. I did not know this was a requirement. If you need that please file an issue on the redact repo thanks.
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by andreimatei** [comment]
Here you go. https://github.com/cockroachdb/redact/issues/8
So what are we printing instead of the right pointer? Are we printing the address of some other stack variable allocated around the invocation of the logging statement? Cause that'd explain the offsets I've been seeing.

This made some logs for some crap I was debugging really confusing for a couple of days.

**Comment by knz** [comment]
> Are we printing the address of some other stack variable allocated around the invocation of the logging statement? 

Yes
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by knz** [comment]
https://github.com/cockroachdb/redact/pull/9

**Comment by knz** [comment]
fixes
