### ISSUE TITLE
Large import causes nodes to fail.

### ISSUE THREAD

**Issue by merimus** [cockroachdb/cockroach#54445]
**Describe the problem**

During long import nodes start going to UNHEALTHY, DEAD, and back to HEALTHY.

**To Reproduce**

Disclaimer, I am doing something weird.

Running on 6x RaspberryPi 4, 8GB ram, using 128GB usb thumb drives for storage.
Each node has a spinning drive which is mounted across the cluster through glusterfs.

/gluster/cockroach-v20.1.4/src/github.com/cockroachdb/cockroach/cockroach start --advertise-addr={{ ansible_default_ipv4.address }} --insecure --store=/data/cock --listen-addr=0.0.0.0:26257 --http-addr=0.0.0.0:8080 --join=192.168.1.3:26257,192.168.1.4:26257,192.168.1.5:26257 --external-io-dir=/gluster --storage-engine=pebble --background

Data is here: https://drive.google.com/file/d/1Mv79jS3L2F7US3RaohnaC5mGcrQJgqE8/view?usp=sharing
This is some of the rapid7 sonar data converted to csv.
https://opendata.rapid7.com/sonar.fdns_v2/

$ cockroach init --insecure
$ cockroach sql --insecure -e "create table fdns (timestamp timestamp, name text, type text, value text);"
$ cockroach sql --insecure -e "import into fdns csv data('nodelocal://self/*.csv');"

After some time (4ish hours).
Status on Jobs page resets to 0%.
Sometime after 4 hours nodes start becoming UNHEALTHY, DEAD, or back to HEALTHY.
CPU and Memory usage of one node becomes much higher than the others.
CPU about 60% whereas all others were like 15%.
Memory usage of 3.5GB whereas all others were like 2GB.

**Environment:**
 - CockroachDB version 20.1.4
 - Server OS: Ubuntu aarch64
 - Client app `cockroach sql`

**Additional context**
No impact, this is a personal project to develop resources for highschool students. 

Epic CRDB-8816

Jira issue: CRDB-3760

**Comment by miretskiy** [comment]
Thanks for filing this issue.

**Comment by merimus** [comment]
Datapoint:
Started a single node instance on a big machine and attempted the import.

ERROR: nodelocal://0/xcl.csv: error parsing row 1171968: expected 4 fields, got 5 (row: "2020-07-26 05:55:24, bryggan.rlh.se, cname, runmaro.runmaro.se,.rlh.se")
Failed running "sql"

Perhaps it is hitting this error, and either failing to report the issue, or is handling it badly?

**Comment by merimus** [comment]
Datapoint:
Fixed errors in CSV files, successfully imported on laptop.
Still shows issues on raspi cluster.
