### ISSUE TITLE
sql: UPSERTs of more than 10k rows don't work correctly on 20.1.4 and 20.1.5

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#54456]
This is a public issue that was originally reported by a prospect (https://github.com/cockroachlabs/support/issues/598).

CockroachDB in 20.1.4 and 20.1.5 releases finishes UPSERT operation without RETURNING clause too early - namely, it would correctly insert only up to 10000 rows and ignoring the rest.

**Comment by knz** [comment]
Does this affect 20.2?

**Comment by yuzefovich** [comment]
No, only 20.1.4 and 20.1.5 are affected. The root cause of this bug is that the original PR (#51631) did a lot more (fixed another bug and cleaned up the code) and I incorrectly extracted the fix in #51944.

**Comment by yuzefovich** [comment]
Fixed by #54418.

**Comment by jordanlewis** [comment]
The failure isn't totally silent. The count of returned rows will not match the expected count in these cases:

```
root@127.0.0.1:55751/movr> upsert into a select * from generate_series(1,10002);
INSERT 0

Time: 119.37ms

root@127.0.0.1:55751/movr> upsert into a select * from generate_series(1,9999);
INSERT 9999

Time: 78.744ms
```

**Comment by jordanlewis** [comment]
Also, note that this also is broken for the upsert-equivalent form of insert on conflict:

```
root@127.0.0.1:55751/movr> insert into a select * from generate_series(1,10001) on conflict(a) do update set a = excluded.a;
INSERT 0

Time: 156.725ms
```
