### ISSUE TITLE
sql: add EXPLAIN (STATS) that runs query and shows statistics

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#5445]
See discussion in #4925. We would want something that doesn't spew all the information `EXPLAIN (DEBUG)` does but that returns some stats for a query e.g. number of keys/rows received and emitted by each layer in EXPLAIN, memory, CPU, time used etc.

**Comment by knz** [comment]
See the 1st commit in #6057 for a starting point.

**Comment by spencerkimball** [comment]
Addressed in #14080, #14092, #14181. @knz can this be closed yet?

**Comment by knz** [comment]
This is a different feature. This issue refers to the collection of stats per stage of the query plan. We want that but it's not done yet.

**Comment by dianasaur323** [comment]
FYI upgrading to 1.2

**Comment by asubiotto** [comment]
Closing this issue as `EXPLAIN ANALYZE (DISTSQL)` has been added, tracking issue for further information: https://github.com/cockroachdb/cockroach/issues/19476
