### ISSUE TITLE
changefeeds: Assignable Kafka Partition Key

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#54461]
When changefeeds are output to Kafka right now, we use the primary key as the partition key as the primary key.   This is quite limiting and it makes sense to help define the partitions based on another value.  

Partitions are designed for the grouping of messages and are a fundamental part of the Kafka infrastucture.  More details here: [partition](https://www.instaclustr.com/the-power-of-kafka-partitions-how-to-get-the-most-out-of-your-kafka-cluster/#:~:text=Partitions%20are%20spread%20across%20the,Kafka%20is%20per%20partition%20only.&text=Partitions%20can%20have%20copies%20to,with%20the%20leader%20partition%20fails.)
 
The cleanest way in which this could be implemented would be using another column from the table.  It could be specified as a parameter in the changefeed command.

Here's the ticket with the original request [6096](https://cockroachdb.zendesk.com/agent/tickets/6096), there are more details there.

Jira issue: CRDB-3758

Epic CRDB-11684

**Comment by BramGruneir** [comment]
There's the further issue of the ordering of the outputs in the partition key.  I think we need to dig into that requirement more.

**Comment by mwang1026** [comment]
I've talked to several folks about this and it's just really complicated to both change the partition AND guarantee ordering. Transactions in cockroach don't have a total order and we don't have a mechanism that provides a total order for some set of rows, so it's not as straight forward as "use this index".

The outbox pattern IMO is actually a pretty good way to get around this. It's a bit of application complexity but it works. Another is, if latency isn't a concern but ordering is, partition on desired values, send to Kafka twice and re-order with a buffer in between.

We'd have to think a lot more if we were to provide arbitrary partition choice with ordering guarantees.

cc @ajwerner @miretskiy

**Comment by BramGruneir** [comment]
Yeah, I see the ordering guarantees as the big issue and seems like a way to hack around our data consistency model.  I do like the idea of defining partitions as another column, even without the ordering.

The only practical way I can see of doing that would be to use a composite key as the primary key in the table:
`PRIMARY KEY (partition_key, id)`

For any crud operation, use 
```sql
SELECT * FROM table WHERE partition_key = pk FOR UPDATE;
INSERT INTO table VALUES (pk, id, ...)
```

Then you can guarantee ordering.  It would force the producers to slow down, but it would be quite efficient otherwise.

**Comment by ajwerner** [comment]
> Then you can guarantee ordering. It would force the producers to slow down, but it would be quite efficient otherwise.

That won't guarantee ordering. `FOR UPDATE` locks aren't durable, they're best-effort. It would however be pretty likely to order the writes.

**Comment by BramGruneir** [comment]
Why wouldn't it guarantee ordering?  We make it sounds like they are in our docs.

**Comment by ajwerner** [comment]
> Why wouldn't it guarantee ordering? We make it sounds like they are in our docs.

Where?

**Comment by amruss** [comment]
@BramGruneir @ajwerner were there any conclusions reached here on whether using a composite key would guarantee ordering?

**Comment by miretskiy** [comment]
This issue is old.  Like very old.  We have plans to support some mechanism to change partition keys
via expressions; we currently do not have any plans on total ordering.
I'm closing this issue because we definitely will not be working on the above in the context of this issue.

**Comment by amruss** [comment]
This was delivered in 23.1
