### ISSUE TITLE
mis-matched mvcc stats from getStatusSummaries vs ComputeMVCCStatsTest

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#5448]
While working on tests for #5295, I got tripped up when I got different numbers for `KeyCount` from `GetStatusSummaries` versus visiting stores myself and calling `ComputeMVCCStatsTest`.

Reproduced here: https://github.com/cockroachdb/cockroach/compare/master...dt:stats?expand=1

**Comment by mrtracy** [comment]
I thought this was another stat synchronization error akin to #5040, but after investigating, this is a manifestation of our time series system.  Specifically, the `MVCCMerge` method used to store time series is only able to _estimate_ the impact of a merge on MVCCStats. Part of this means that KeyCount and KeyBytes are _never_ incremented in response to a merge.

When a server is running, it seems that the in-memory key counts will vary from on-disk counts by a small, constant factor, approximately equal to the number of time series we are recording.
