### ISSUE TITLE
scheduled backup bug: error messages showing up in state about transaction retries

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#54484]
Occasionally, you will see error messages in the `state` field of `SHOW SCHEDULES` to the effect of:

`reschedule: failed to create job for schedule 590471771591639041: err=TransactionRetryWithProtoRefreshError: WriteTooOldError: write at timestamp 1600269667.377547474,0 too old; wrote at 1600269667.396809113,3`

There're are some theories around why that's happening but we don't know for sure. We also observed but weren't able to repro a scenario where we tried to run `PAUSE SCHEDULE` and it didn't actually pause the schedule. When we ran `SHOW SCHEDULES` right after the attempted pause it showed `ACTIVE` status with an error like the above in `state`

If they aren't related, we'll create separate bug about pausing the schedule

**Comment by miretskiy** [comment]
I believe I know exactly where the problem lies; I do think that it is a release blocker since incorrect rollbacks could likely produce the behavior described in this ticket.  PR to fix should be coming in today/tomorrow,

**Comment by miretskiy** [comment]
The #22615 describes txn api deficiency that explain how these "retryable errors" get written to status.
And the bug we have is around swallowing txn error and no propagating it to DB.Txn.
