### ISSUE TITLE
IMPORT: improve PGDUMP compatibility

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#54504]
This is a meta-issue for various improvements to pgdump IMPORT. The goal of IMPORT from SQL dump files is that Cockroach does the work of figuring out how to migrate your data in for you -- you just provide the dump and we do the rest. Today we hear from users that they provide their dump file but encounter an error, edit it, try again, encounter another error, etc. While we'll not yet a perfect drop-in replacement for every bit of Postgres functionality, we should aim to have most dumpfiles IMPORT on the first attempt without error, and provide flags/options to IMPORT s.t. those that aren't compatible out of the box can be imported without modification fo the file itself. In particular, we should fix cases where compatible SQL features have been added since IMPORT was written but IMPORT does not yet leverage it.

TODO: Link to corpus of pgdump files.

TODO: List individual causes of incompatibility.

**Comment by pbardea** [comment]
Linking tracking issue the breaks down particular improvements to be made:

**Comment by mwang1026** [comment]
Closing in favor of https://github.com/cockroachdb/cockroach/issues/56659
