### ISSUE TITLE
jobs: refactor job storage

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#54527]
The one-row-per-job jobs table is easy to reason about, but has caused increasing issues as clusters have grown larger and started to run more jobs, and as more things like schema changes start to rely on jobs more. Currently this one row serves two, or actually three, purposes:
  1) act as the set of jobs that the cluster should be running, displaying, etc
  2) define the details of a given job, how to run it, what arguments go into running it, etc
  3) store the execution state of that job (i.e. progress and status) as it changes while the job runs to allow status inspection or resumption from where it left off after a pause/crash.

We previously hit issues where 3's desire to be be updated often conflicted with 2's tendency to be large: rewriting the whole job definition every time the job made progress wrote too much garbage. Splitting 2 and 3 into separate column families mitigated this to some extent -- it let us rewrite progress without rewriting definition. However we're now seeing 2's size become an issue w.r.t 1 -- that some operations want to inspect the set of jobs, without scanning over all the details of every job. Currently the details about the job itself -- when t was started, finished, its type, etc -- that are needed for general job enumeration/display are combined in one-big-proto with job definition and the job-specific arguments used by the executor of that job. When those arguments include, say, 10000 table descriptors this makes an operation like showing what time all the jobs finished iterate over a massive amount of data.

Ideally, our jobs system would provide these things separately. The system.jobs table should just be the what is needed to enumerate and control jobs -- the job IDs, their status (runnable/paused/etc), their start/end times, owner, etc, i.e. anything that might be read when iterating over multiple jobs. 

Along side this, either in a separate column family or separate table, jobs should be able to store their details -- job specific information that is only needed to execute that job, and can thus be only loaded during execution of that specific job. The could be a separate column family in the jobs table, or a separate table entirely with an on-delete-cascade.  A separate table could allow suffixing the job ID with an additional detail type, so jobs could store multiple kinds of details separately (e.g. the table descs, or the stats, or whatever, in separate KVs).

Finally, progress and status update information should be stored as multiple rows per job, rather than as one oft-updated row. This would play nicer with ranges as splits between revisions of a row are not allowed while splits between rows are, so it is generally bad to expect thousands of revisions to a row in-place. Additionally we could reduce contention if statuses from separate subprocesses within a job could be recorded separately and then aggregated only when needed for display.

**Comment by spaskob** [comment]
@dt thanks for this proposal - I can't agree more!

**Comment by ajwerner** [comment]
We'll likely need to fix https://github.com/cockroachdb/cockroach/issues/57531 before we start adding lots of new tables for job state.

**Comment by dt** [comment]
I think with #57565 the urgency of this has dropped -- backups can use their s3 bucket or whatever to store state outside their job record. Other jobs (looking at import and backfill progress) would still benefit from somewhere-not-the-job-row to record execution state/progress, but with the big offender that was BackupManifests handled elsewhere, I think we're probably not allocating roadmap time to this in the immediate term (though @miretskiy and I may or may not allocate a friday to play with it -- we'll see)

**Comment by ajwerner** [comment]
@mwang1026 I'm not super inclined to do this. I'm more inclined to close this. Re-open if you would like.
