### ISSUE TITLE
jobs: refactor jobs results API

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#54525]
Currently job execution can produce results as they execute to be returned to the SQL statement that spawned the job, for example listing the tables backed up or the number of rows imported. 

However the way this is done with a channel requires that execution (of the coordinator) be the in-process, function-call to StartJob. If the job is executed elsewhere (which is an explicit design goal of persisted jobs) that does not work, so we see cases like "liveness error; restarting job in background" return to the client. Additionally we incur complexity around ensuring that when there is a client we return results but when there isn't, we complete without blocking on that channel but have seen bugs in both directions here: clients that got no results when they expected them and jobs that hung forever trying to send results to a client that disconnected.

Overall, this API is brittle and err prone. Instead, we should be able to synthesize a summary of what a job did from its persisted state/progress _after execution has finished_, regardless of where that execution took place. Then the statements which want to return results summarizing what a job did can simple 1) run the job and then 2) get the job's summary and return it, eliminating this troublesome channel.

**Comment by ajwerner** [comment]
I don't see us doing more here. We cleaned up some of the StartableJob stuff in 21.1 but if jobs want to write their results somewhere, they can do that. Maybe, one day, there will be some team who views their role as actually making a jobs platform as opposed to maintaining the one we have.
