### ISSUE TITLE
doc: mismatch of workload command flags to actions 

### ISSUE THREAD

**Issue by a-entin** [cockroachdb/cockroach#54524]
The workload command for YCSB test has 2 apparent mismatches. It says:

`--request-distribution` applies to commands: `init` or `run`. In actuality applies to `run` only. The current inaccuracy forces a user to needlessly regenerate an initial dataset which takes [many] hours.

`--splits` is also documented to be applicable to commands: `init` or `run`. Yet it seems to be `init` only. This may lead to skewed test results.

Ditto for `--families` flag, it's `init` only... doc says `init` and `run`

Not sure if there are other potential mismatches; we really need a holistic pass over all flags to ensure accuracy.

Jira issue: CRDB-3746

**Comment by Swastyy** [comment]
Hi @a-entin Can I work on this issue?
