### ISSUE TITLE
Serializability violation during network partition

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#5453]
Found by this Jepsen test: http://52.91.194.28/cgi-bin/display.py?entry=20160321T223424#20160321T223424

The test inserts `MAX(v) + 1` in the same table repeatedly. At the end all values for `v` should be unique, however in this test's results one duplicate value is found. This is a serializability violation.

A few noteworthy points:
- during this test, a nemesis disconnects nodes randomly from others, then reconnects them later
- nodes 3 and 5 commit suicide with "can't determine clock offset", although this test does not impact clocks whatsoever
- node 2 complains about ```heartbeat to "/mnt/kena/go/src/github.com/cockroachdb/cockroach/sql/executor.go:548 sql txn ... failed: /mnt/kena/go/src/github.com/cockroachdb/cockroach/storage/store.go:1533: rejecting command with timestamp in the future: 1458599718897271366 (28.359640279s ahead)```  although the node clocks are synchronized properly, followed by many instances of ```remote wall time is too far ahead (31.803151722s) to be trustworthy```

Idea about an explanation:  a heartbeat message is delayed in-flight during the network partition and its timestamp processed incorrectly when the partition resolves?

**Comment by knz** [comment]
noteworthy: I've been running this test quite often over the past month, and this is the first time it fails. Couldn't reproduce yet.

**Comment by tschottdorf** [comment]
I'm not sure what's going on with the clocks there, but with 31s I would expect some stale reads. If that happens again, can you keep the cluster up and take a look at what the individual nodes claim they're operating at? Any sudden clock jumps in log messages?

**Comment by knz** [comment]
I am re-synchronizing with NTP before each test is started. I don't see how a difference of 30s is at all possible.

**Comment by tschottdorf** [comment]
Try going through the logs, matching up events which you expect to have happened in all of them near-simultaneously. That should help ruling out a 30s clock jump if there really wasn't one.

**Comment by knz** [comment]
Ok you were right, there was a backward clock jump in here. Actually this was an error in the test, the clock was improperly reset in between tests. So this issue actually goes away when the test is fixed.

**Comment by tschottdorf** [comment]
Great, glad to hear. Thanks for checking.
