### ISSUE TITLE
backup: use protected timestamps to preserve MVCC between incremental scheduled backups

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#54530]
When we introduced BACKUPs, we set the default TTL to 25h with the intent that that would be good enough for most operators out of the box to allow daily incremental backups, but this is a crude/blunt instrument: it makes all clusters and all tables retrain 25h of history even if not doing backups or doing them on a different cadence.

Instead, now that we have _scheduled_ backups, we can instead set a lower default TTL and then, when a schedule is active, have it use protected timestamps to preserve just the mvcc history it needs, by setting a protected ts for the backup end time after finishing a backup and leaving it there until the next backup.

**Comment by adityamaru** [comment]
Closing this in favour of https://github.com/cockroachdb/cockroach/issues/67282. I think it encapsulates everything written here.
