### ISSUE TITLE
Create a non-root user for cockroach demo

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#54557]
Today, when you start `cockroach demo`, we start the interactive SQL session for `root` and the connection strings printed in the demo welcome text are customized for `root`. Instead, it would be great to:

1. Auto-create a non-`root` user and password
2. Log into the SQL shell with that user
3. Customize the connection strings for that user

The connection strings in particular would encourage the best practice of using non-`root` users for app connections to the db. 

I'm not certain about #2, however. It might be important for the auto-logged in user to have admin privileges, for example, to create new databases, grant privileges to other users, etc.

**Comment by knz** [comment]
Maybe the new user can be auto configured with the admin role?

**Comment by jseldess** [comment]
Yes, that would be great, @knz!
