### ISSUE TITLE
Backup and restore: abort if cannot protect timestamp.

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#54572]
If an error is returned by protect timestamp call during backup (and restore) planning, instead
of bailing out execution, we proceed to call sj.Run() (`backup_planning.go:973-998`)

This results in the following error being produced:
 `ERROR: cannot resume *backupccl.backupResumer job which is not committed`

There are few issues that need to be addressed:
  1. We cannot call Run if we failed to start a job (we need to bail out).
  2. We should also report the original error (and not throw it away when we try to cleanup).

**Comment by adityamaru** [comment]
Should we mark this as a `release-blocker`?

**Comment by DuskEagle** [comment]
We are observing this same issue on a Cockroach Cloud v20.1.5 cluster. https://github.com/cockroachdb/cockroach/pull/54577 already has a v20.1 backport label, which is great :+1:.
