### ISSUE TITLE
Possible serializability violation during network partition (majority rings)

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#5457]
This issue is similar to, but different from, #5453 that was just filed.

Found via this Jepsen test: http://52.91.194.28/cgi-bin/display.py?entry=20160321T230210#20160321T230210

The test inserts MAX(v) + 1 in the same table repeatedly, each time with a copy of `transaction_timestamp()` concatenated with `transaction_timestamp_unique()` (the latter returns the txn timestamp's `Logical` field) and the ID of the sql gateway used for the insert. At the end all timestamps should be unique, however in this test's results one duplicate timestamp is found: two transactions have committed with the same timestamp and logical counter, from 2 different sql gateways.

A few noteworthy points:

-  during this test, a nemesis disconnects nodes randomly from others, then reconnects them later; during each partition, each nodes sees a majority of neighbors but each nodes also see a different majority from all other nodes.
- nodes 2 and 5 report this strange heartbeat error: ```heartbeat to "/mnt/kena/go/src/github.com/cockroachdb/cockroach/sql/executor.go:548 sql txn ... failed: /mnt/kena/go/src/github.com/cockroachdb/cockroach/storage/replica_command.go:865: heartbeat for transaction "/mnt/kena/go/src/github.com/cockroachdb/cockroach/sql/executor.go:548 sql txn ... failed; record not present```
- nodes 4 and 5 complain with: ```failure aborting transaction: retry txn "/mnt/kena/go/src/github.com/cockroachdb/cockroach/sql/executor.go:548 sql txn ...; abort caused by: retry txn "/mnt/kena/go/src/github.com/cockroachdb/cockroach/sql/executor.go:548 sql txn ...```

Before marking this as a bug, a sanity check: is it possible that 2 distinct transactions on different sql gateways commit with exactly the same txn timestamp?

**Comment by tschottdorf** [comment]
> Before marking this as a bug, a sanity check: is it possible that 2 distinct transactions on different sql gateways commit with exactly the same txn timestamp?

Yes and we discussed this before: https://github.com/cockroachdb/cockroach/pull/5305#issuecomment-197455014

What did the transactions commit with? Do you basically get

```
m       ts1,lg1
m+1   ts1,lg2
```

or something else? This seems like it should be possible - two transactions can start with the same timestamp, and the only thing that would prevent that is if optimistic concurrency establishes an explicit ordering between them. Here, both transactions scan the whole span looking for the maximum, and I think that **should** order them: the scans populate the read timestamp cache with their read timestamp and own txn id, which should force the other guy's write higher, but apparently this hasn't happened.

One way in which that could happen (depending on what the implementation does) is that txn1 scans and writes first. When txn2 scans (at the same timestamp), the timestamp cache already has an entry for that timestamp tagged for txn1 (the tagging is what allowed txn1 to write at the same timestamp at which it read). If now, by some accident, txn2 manages to tag the entry at this timestamp for itself - it too could write and we would see this behavior.

This should be verifiable/revokable/testable easily by taking a look at what `(*storage.TimestampCache).Add()` does with `readOnly=true`.

**Comment by knz** [comment]
Yes I am aware that you can see the same value of `transaction_timestamp()`, but that's why I'm adding the logical field. And here I see (to keep your notation):

```
m      ts1, lg1
m+1    ts1, lg1   # too!
```

How can both transaction suse the same timestamp cache since they are issued from different sql gateways? Is it because they end up resolved at the same range leader?

Regarding what `TimesampCache.Add` does:

```go
        // Only add to the cache if the timestamp is more recent than the
        // low water mark.
        if tc.lowWater.Less(timestamp) {
                cache := tc.wCache
                if readOnly {
                        cache = tc.rCache
                }

                addRange := func(r interval.Range) {
                        value := cacheValue{timestamp: timestamp, txnID: txnID}
                        key := cache.MakeKey(r.Start, r.End)
                        entry := makeCacheEntry(key, value)
                        cache.AddEntry(entry)
                }
                r := interval.Range{
                        Start: interval.Comparable(start),
                        End:   interval.Comparable(end),
                }

                // Check existing, overlapping entries and truncate/split/remove if
                // superseded and in the past. If existing entries are in the future,
                // subtract from the range/ranges that need to be added to cache.
                for _, o := range cache.GetOverlaps(r.Start, r.End) {
               ...
```

So it looks like we are using different caches depending on the value of `readOnly`. Also I do not understa nd how this is relevant to the discussion since both transactions in this example are writing.

**Comment by tschottdorf** [comment]
> Yes I am aware that you can see the same value of transaction_timestamp(), but that's why I'm adding the logical field. And here I see (to keep your notation):

I was talking about the full HLC timestamp.

>  How can both transaction suse the same timestamp cache since they are issued from different sql gateways? Is it because they end up resolved at the same range leader?

The timestamp cache sits on the Replica. This is nothing that happens on the gateway.

> Also I do not understa nd how this is relevant to the discussion since both transactions in this example are writing.

If the write goes through for both at the same timestamp, problem. The write is pushed after the read, unless the read is from the same txn. That's why I'm talking about the read timestamp cache - in the scenario I picture above, we replace a read timestamp cache entry from another txn with our own, which would allow us to write at the same timestamp another transaction read at.

**Comment by knz** [comment]
Regarding this:

On 03/21/2016 09:25 PM, Tobias Schottdorf wrote:
> If the write goes through for both at the same timestamp, problem. The
> write is pushed after the read, unless the read is from the same txn.
> That's why I'm talking about the read timestamp cache - in the scenario
> I picture above, we replace a read timestamp cache entry from another
> txn with our own, which would allow us to write at the same timestamp
> another transaction read at.

Agreed, but again here in both cases we are talking about  two
transactions that read then write. So even if what you say happens, ie
txn B's write timestamp pushes A's read timestamp forward, later when A
tries to update its write timestamp it should conflict with B's and move
forward too, so we shouldn't see two times the same txn timestamp at the
end. Unless I am missing something?


-- 
Raphael 'kena' Poss

**Comment by tschottdorf** [comment]
> ie txn B's write timestamp pushes A's read timestamp forward

This statement doesn't make sense - what do you mean? I can't really parse the rest either, but note that the writes don't go to the same key, so the interactions you see come from the second transaction's read seeing the first transaction's write. Can you elaborate on our text above?

**Comment by knz** [comment]
I think it's clearer now.
Especially in the light of your comment https://github.com/cockroachdb/cockroach/issues/5479#issue-142755605 I believe we can close this now.
