### ISSUE TITLE
Query performance, when grouping and joining tables

### ISSUE THREAD

**Issue by jrote1** [cockroachdb/cockroach#54597]
When I run the following query it takes ~500ms 
```
------------------------------------------------------------

SELECT
  b.id,
  b.biosample_name,
  round(sum(ll.dataset_yield_bp) / 1000 / 1000 / 1000, 2)
    AS yield,
  count(ll.biosample_id) AS lanes
FROM
  biosamples AS b
  JOIN lane_libraries AS ll ON b.id = ll.biosample_id
GROUP BY
  b.id, ll.biosample_id, ll.library_id
ORDER BY
  ll.biosample_id DESC
LIMIT
  10;
```
Explain output:
```
               tree              |       field       |                        description
---------------------------------+-------------------+------------------------------------------------------------
                                 | distributed       | true
                                 | vectorized        | false
  render                         |                   |
   └── limit                     |                   |
        │                        | count             | 10
        └── sort                 |                   |
             │                   | order             | -any_not_null
             └── group           |                   |
                  │              | aggregate 0       | biosample_id
                  │              | aggregate 1       | library_id
                  │              | aggregate 2       | sum(dataset_yield_bp)
                  │              | aggregate 3       | count(biosample_id)
                  │              | aggregate 4       | any_not_null(id)
                  │              | aggregate 5       | any_not_null(biosample_name)
                  │              | group by          | biosample_id, library_id
                  │              | ordered           | +biosample_id
                  └── merge-join |                   |
                       │         | type              | inner
                       │         | equality          | (id) = (biosample_id)
                       │         | left cols are key |
                       │         | mergeJoinOrder    | +"(id=biosample_id)"
                       ├── scan  |                   |
                       │         | table             | biosamples@biosamples_id_name
                       │         | spans             | FULL SCAN
                       └── scan  |                   |
                                 | table             | lane_libraries@lane_libraries_biosample_id_library_id_idx
                                 | spans             | FULL SCAN
(27 rows)
```
But if I run the following query which produces the same output it takes ~17ms, a massive performance saving
```
SELECT
  yields.biosample_id,
  b.biosample_name,
  yields.yield,
  yields.lanes
FROM
  (
    SELECT
      ll.biosample_id,
      round(
        sum(ll.dataset_yield_bp) / 1000 / 1000 / 1000,
        2
      )
        AS yield,
      count(ll.biosample_id) AS lanes
    FROM
      lane_libraries AS ll
    GROUP BY
      ll.biosample_id, ll.library_id
  )
    AS yields
  JOIN biosamples AS b ON yields.biosample_id = b.id
ORDER BY
  yields.biosample_id DESC
LIMIT
  10;
```
Explain output
```

                tree               |         field         |                        description
-----------------------------------+-----------------------+------------------------------------------------------------
                                   | distributed           | true
                                   | vectorized            | false
  render                           |                       |
   └── limit                       |                       |
        │                          | count                 | 10
        └── lookup-join            |                       |
             │                     | table                 | biosamples@biosamples_id_name
             │                     | type                  | inner
             │                     | equality              | (biosample_id) = (id)
             │                     | equality cols are key |
             │                     | parallel              |
             └── render            |                       |
                  └── group        |                       |
                       │           | aggregate 0           | biosample_id
                       │           | aggregate 1           | library_id
                       │           | aggregate 2           | sum(dataset_yield_bp)
                       │           | aggregate 3           | count(biosample_id)
                       │           | group by              | biosample_id, library_id
                       │           | ordered               | -biosample_id
                       └── revscan |                       |
                                   | table                 | lane_libraries@lane_libraries_biosample_id_library_id_idx
                                   | spans                 | FULL SCAN
(22 rows)
```
Why does the first query perform so badly? Did I write the query wrong, or is the query plan optimiser getting confused?

**Comment by yuzefovich** [comment]
@jrote1 which version are you using? Do you mind sharing `EXPLAIN (OPT, ENV, VERBOSE)` output on both queries? It seems like either an exploration rule is missing or we're miscalculating the plan costs.

Moving it to the optimizer project. cc @RaduBerinde

**Comment by jrote1** [comment]
Thanks for the quick reply
I am using the latest version v20.1.5
[Slow query](https://cockroachdb.github.io/text/decode.html#eJzsfW1zW7ex_-vqU2D8ptKEVLGL3QXA_t2pojAd9e_IuZLSacaT4dASrbChSQ9JtXHvvZ3O_Qx-eT9dPsmdwwcsDkVKPKSkyLLzIjpLLBbAD4unH_Yc1-vmL53hqDvoN8zh4Pyn4aB9_uNXX5rDwxfm72j3YZ_N7s9BWkL1q_5P_cE_-vVet3_1c_2yf1Uzr6-6vbFBi_Z3NvwOyUBsMDZsqJnLAeyD2497Ozv1uhl2BsOLzrD1t0G3P2r1um-7Y_Nje2TGP3bMRedN-6o3Nn9v9646DUOFfqffft3rtP7Zvfxn-3KSa5X6oF_oD96Nu2-7_-wMW28Gw073st_6qfN-dEOencOT5sFZ05wdfPmiaV53B6P223e9zsjs7vyme2GOjs-COX55Zo6_e_GitvObpNDqt992zOnZydHxn-aJF-1xp_V2cNF90-1cmLOjb5qnZwfffFtKPh922uNlqaNxe3w1WrDYa79uLU04H_TH7W6_M1xWD018Nxh1x91Bf0Hh3XDwt875uJUaOP358OXx6dnJwdHxmXn2bth92x6-f2a-PTn65uDke_P_m9-b3e6FOTg93Kvt_Oa746P_-K5pjo6_av41g61VBqhA3-wugDazcC1rr_161tbdrN2rtLsXU2vzOpnTs5eTNi4UV2T--uCboxffZ43a7V7UTFmvZkrdNxNn3VUz09rUjNasZsqdkMtz3GtGod7b2fv9zs7Bi7Pmydzb2qPO6F37vLP_7up1r3u-n7nf0fGfm4dn5vTs4Ozo9Ozo8NT89tWOMcb85-T_xX_Pzge9q7f90bOGeZV-nCR0L56lH36oZRmmrWm1x88a5lkxXOs21sEb4AaEhoV9G0QifmFtw9pnWc6L7mjc7Z-PW-eDq36R2zmEmCn82B2NB63zQa81fv-uU5gvPCs3UWBU_N5qta_Gg1arlHbV6yXTNksYDv6hRWIEnCT9d21tKMqdfP-wYHTuRlimI_HXB0Yd-d5BCR8FIKXhf--YICHxjbg8EkRmbb5_QCz5R47HAw0XeuQwlJe9e4dD5B78gizfDyTzlf_eYYmPHxXd-9w_GvcwaMA5wLvEYxMc0DYs7qO3YvnztmxjWD6JbVlFUD6JbVlFTJ7-tqwqIE93W1YRiae-LasIx6eyLasIyxPflj0CNPwd78q2ggMblvetiMN1dqnAcB_b1LvFY-utWTVMPpGtWTVQPo2tWTVMPoat2QPMIR_LCe-BRsqT35VVg-OT2ZVVg-Uj2JVteaqrOJc-_lNdxak0GAgNZxtO9q0wRXhCU-kWO7KNYHnqO7JNQHnqO7JNMCl2ZDePn0eCyCbT6kaAPP5p9YGGyxPelm0CxyewLdsElo9gW7YhO7QJGiCPfdRUBgFdg2LDhX1wBPHzlmxTVJ7-jqwyJh_Hhmzj6aMyHo9_9thiK1YZjae6E6sMxGN3iq02YpXR-CT2YZVR-Qi2YdscbKtPHr_auXbnh9_-fuGVlF6732n1uq-H7WF3-lrK5Jcb301ZeK9jmvv9sjzDq_6i9kV73B51xq333U7vovX6XSlx6csot783Mq_ywelhzWTVmb3ckRl481Mrb0dr2HnTyl6L-PrlSfPoT8dTq7ninjlpft08aR4fNk-z10R2i5SXx-ar5ovmWdMcHpweHnzVvFakVmlSoMJdKk-1SqUl7TULm2I-KWh41V8oY5pYsl8orTQ9fS-m7CRTR-z2Lzo_t27Bs4Rh-V2bG22uBGz3eu-uYW4RkhkMKy28T38nXnqtVH0ZaNGbV1aohFLWvO7Fz9dRuubENxd4_f2j2YDIX0IqJLVaM1MIJu8hlQzO30Va432ihbljq3eKZjWuegr2DScN5_Y5WkZZZ_J1jDefde78BAjIHuzmR8AHQAUCEH4MqKgHPwAm0d18CnwkmExH8r3j4ax9YOpkMzgWJ7T7dxRwHB7wOLgZLJsx89W95LHjsPFCw7bhaJ8cg9A6C40Hf_Pp-O7Hiws-uIddaCqiAjH4h15-N0Jlm4WmqqcAsv0YMNl0oamIh6NbaJRHAsf2C03VwYMMXh5wgt0Ilk0Xmqpe8jRxCA2ghuN9cFbCY8NBkP0Wd1mbXHJWRAPR0c0j5O4nj41Q2Xx9qY4JBffQh7vNMNlsa1Z9yGCEj8JJtl1hKiMDxOIeMAp-M1g224dUBoPA3wzFI_GSzYYNugZJw_l9Jia3VuAmoX3oE42P7OQBV5zqqCD7W94beSSobLzibIBJcP6hV5yNMNloJqmOBxE-NHW2ERxbrjfVgQEBjA-5g90Ilo1DKSrOr48dh40XGvYNF_eBnQ3u80KzISqfxEJTFZOnvtBUxOPTWWgqAvO0F5qq8-uvg8M0-qj5129fHBwdm92X357VzF-aJ1--PG3WTPP4L3vmtPmieXhmXu9PQhf2F7-gOhxc9S92d3dHV293e739a6EQ5ncGrLWLf2sG98zBqZno1cykakX-cnzPwekkZGNkvj55-U3-pd6DU_Pa_Pnl0fFirFSRo2deHk_qa56bBZPmTycvv_vWfPn9rD0LyZMfsjCPlydfNU8K7UUzXzVPD82Lo2-OzgzY3-_U6_X6zizud8f88uF_f_nw718-_NvMnKphuhcNWPj4bAOnjW9AmDayAd6YVz92Ly46_UYpSKQB8EPJbHt40e23e93x-4Z5ZU3dgC0pFD47aphXw8E_Rs8X0s4Ho_FkkiaCfYqYp725aJhd2KvX_7CLezWzi3v_-tcfdqF4hL3nz3dh-jh93stzTj7x3O1fNkx9F_4LYM-8ap-Pr9q9hqmXK_9ueNXvFMXUsAZQA1-DUDLV7Y87w04xPC6T2VHD7NbLJU4-JF388D-FI6-N-QKuWfhNA9CMrt42QKbu2AC_xPykdv12r36txcvqsqqjFvSW9de1ZmXdhgGXqPzUeV_gCjXAZZWp1rm1uaVCf9JXUgO_zO7tXb8MwtUdvIjNYJh388P09o39A45C3KeamU_iM6SylGIenv9a6s6behU8rtZc0bn33MebdvVCvtlH37v9ccOA3bd2tWpperilOqsc6QuA2heAe8XTMrQ-zPJfDgdX7-qv3y9qmIfzsYWiJjUqmpPKvNH6LdaWzFVfXJurlmW8Y3-_hufE6clZln0hukX9Js83D-D-pqqDLuuFyl56zUi_M6xP_jGE3bed4WVnVYa7nB8XN3MNWNVXi-O982acTRZfwHrZht3LH8v51sxY9tfJ9jb31r3n03P6zE33ntuSLy8kX0vfxNeXz_POIsN-iOtlqr4bu93mtZlAZ_Avrs_gy23MRwDWAGtAa5a8ehgUIwBr07_rjInFzj9v983rP17_dyJuzl5poFQyVfLGyZseZWec_ZSc8RbYsz-Tg-HlsP22yGeMLVJc8T8QeFTPn4XPwmfhs_BZ-Cx8sgJ9Fm4TPksPKa29zyz99__q9boRBA6mXp88ExDNn9k5O38WGzE9k0-_e-fn-h6Q_PwZ1Y53SG7-HBB59hzQhrnNiIBzHbDWybwAAAIPcwEFZV5VcACek0AYYhIYbcrjirrMBQKn5RAjJGtMCJKEiJjyCGNM1jxDAgICIKSUaEHVoqCdW0Mr6FSIiHMDiIA0byk6wDCvGxJgAhCDxzCvqLPoYN5sR8QqMLCdG3AeyM0BccF6lwwEpASIC4FoXjcXLXsVwIMKRD5ZizG6eUvJWkiFkrWc1Mha7zAJYKOoQDKvNQEHn9QKsEEFCVaFiKrmA0QVYlRrQd2F0HLqLHIUggpsvVOBEojkWDEgJxSSNec5-RuRF20cBbaaErxEFSKnFLY2DShiq45EbCV4FbLGMZEWyl5SzxF7L6miHAicCkJqIAbtLLE2uSWJZZdMC3ByMRJmTnXzQNGpIAIqBKcpiNpZHj14FSKrmvOkamTTwCBPzmsezpodLGt7YgyKQYwxqbF16khsSVIvsCNhSYL4NB2x89Z6FVBQBUJNCSFTi5iGDBdYpXIoSAKRiyRKAjMnAywcMsEnp2AOkpyPOZaEKKnWYm20KnBM5QjkAlrMBKeNE8oKleAp1dpno559NkOzR9GWeoxRBefVtKeAaoAhsAqeVRCwmkdiGo0cMk_kwJLWCw4cbGpP8MGqWrBpsuMQUAsNQVjVoo45DtFRJvi0YnCIMS1kHK16L0fQdYEjSpqrOGJI85tYkmRArOhYEOtjmmrEBp_6VICFIQlBqyPIEtKaTFZ7TpglDU0RJ2lSlcA-oeMtqDVvvU-u7IspSQXvE1Seos6Wnq0Os4AS0swXmEJyiuARUkWDx-hUcBHmtQ4FVPNaR-tjGmbRgU2DNhLFtALG3P1jcFHXemvFJkjBQrE-JgmzCQasBBvTem89g1cr3gNkaRF0n2GD1UUJbECwkkk6Z4ANjJBLzqtmtEAukxxkEutoKCTUjQ1YgLQtKCTdlBUSaQngJNu1gBOyKhFCWskKyaXFtJDIZ5qMaSwBsAPRungLcgvDvZQdd4QY9rlSztnd0C1M8Zq8eiUj699urL7gXK_ED-sT6BUI817vj-t_DWUzJv2OL5eq3fncdquDe8-ngYqzdFx-6zOzW-XOZzlfnwh78EV6mFAFjifPPhpNqCRsYWDGVVQysGae1WqVCmV3N7VeE7eS6SXlrC50C0C2rkElrLfGbWthzRqsxmBrD1mW5z7ac1dYk6vQ0lv9YLW1rTG4zRPXLPSuxtxt1jaZAtY0vaylJeCnpj2sMl1KKeWZlYPTP1HVwE4NzP7E6t24rJw1h0wlqLbw-EqjfobBFKoZohO1GU3vPapQws1P_gDydQMTtaUpMzsxE0p1WyZMW1rq01njSqanaqVybjW9iVCqzm1qs4qW8ixx8mWmV-cpYZD7TrmHy8bLrvCYpXIb1knbjLKfcvYelCIPUbl5AAGXk-JR2W6bkeKMGas-IYrmgtjs6BuC5kEble1GBCVZ0IsedJ31zirXbCUdO12wPtE8LhRn80wIGT_N6UjtIiir4WL0id1yMQZRfjpmPKvNeVZrKSjxbDlkKeIzGjv4zEBkzUPkEi8JQiWymjNBcsFjyIREixBITOThhMbmTPCZEEULDWBtJmT8NIV0VidH0WU0tk3sCTmGxPCRY9LGOebEVJETJfnJ-YwQpkBCKnDIqG_tEqIQfCZETrWmaEX5aZuR72xBy2Gb3QVwzrezlyyPzyh2Dk7L4cCkapFFTUeviHIMnKlF7TmxDBlDLqApyJLz4BmnDT4qKZ6RruRRJBOU_yTvvE1N8IQ-I8VJr0B84ESPUYzCmRDQqhCV_7RWxw9bYqVWHQnlQlROW0QywWfUt0SXC6ml7LxVHtx565VvL9qtAgUtNKJyzRQkKsFNQrmQGD5mZi20eFZB9IZpQpdrnhi0cRz1goiLPlUiHTImXiA4VUNS4llyWl6CT_cU7MGnYcYeorLDHgWVVcegLLR3Pt3IsKeQmFH2RSNUkIx8Z6-19uwpY9WDMv5esguI4LLGBScZd-4k-U4huFxN8hRtaeDsCiT47N4lBCtqOoDLBCU5OQQB5eijjZmAGZUfOTMdleDmEIM6RbRB7w8iIChhj8Gn62xLehUmVjwlVt36jHy3wceMiVfuvBj0aSxMZgDJBMpTOBckV_O5kFbNQoiZ4G2m5vWWwIHeYEgx8SUhohfl9TPvLYTUjYUQspSYpjRPFNOdgy9mVRWiunLwqOtP8Kg328GjXmcE75zVuwAX9aLfk02DNlpr0wVRIaT5oBDSNFgICZ3owCaniOxs8uvILiZ4I7NNk3f0CJKFFIjNmHl0Vrc_VgCs3iB4DxovYIOljJkPVnLun_W-Y8L2i94nROuyO4PIkAbchN93ysVbgOS8E34_Y-ZdfmcATjCLi3BCWRoxZDcB7CDTFEJef7eZEZu4QGxOT6PXn68RnrfoT57zk8A6-quet6ea7pZcXcYdbE6u3mptyYltC3K1dDa9I2rmrqizSlTT_dftPui2rdtzV9W52yGzSaGbMKAlD1lCxK326_tvwpK6beKJW3TJbWN7a7--R0a3Gok7bUKJKP31r0eqNWH1cL6N87_V-e6o1sscaevLsCUVrUbZbz1xLUF0WXU296o1p4B7XCTuwPQ23CWBJeWPMpqKQQPMRI8cYq0ezoL1GpYEifTwAolbKTbwc_0AoOcYgnR6C1F_jwE0UMa5LL7XZcGkQJKlMGZBOeyANXTYYQqKBAElt0AI0okGJN-vi2Sxx-JBo5skgIbmSNAAayhOf0raRkcaogxZILKXTM17TCGJ4L3TWvuYHUl8zGhjHx1rwDOiywSXztYQkEhTKCs0MGYphQUVnEIVIqYQZYiohBjELAUt5LHUoAbQIrJy1U5rgJZyA4yJrUCbnagQMhYBi6amFPSYWGwkUX4bybtE3yBnZz5kdIn_QUZKh3NkVM4VmVwmiAKPLC6o6ay3UTgrVAQTk4IinLgcFO8ScYDeOm22B7Il8j7lCeiSx2Mo2poEl5UT2Om9QHQuUYwYvUsHeoyeNLw9ekqnZYzRWb0xEJeYIWc9YS6kMedsdMl7HVCWB9jp9QFafSWhGItpnDp0GlTsHKv7Fw3IUnwWEu98nsdzmpUKATUO37nksI68htq6wvvTDQhnHIFjodQ_joPyDI4jpWBEJ-wSKeh8zNApxpwG8rNGgLsglMX757UOgZxeyESyMRPSQC8ExS1ETn3qYtS3B8hCFqYNlliD8iFTQ6BEWBZCmt8IhZS8xwxrQs_Z1QZQGqfkiLEUoa8XGD67pnCloHzgNO8QgWjcOiFrRDs5zlKcQJai9HQh6GUEMWuAPQVOLClRzAplmzV7EpGugvL1xJJF27PkKVHf7iCxlEYjiWV9AUKQEvNN4knfupCY3Y14yC5XfEYxkifOg_JFr568Z-1G7zmotaAuRsFmL00EyC6LotcmsFg1wGK1S1iYlegNpO88cPCi1HkEbTZHyLjqGPTlDLGsryyIjRkfXCyOkgnK00LQcgSCz4heK2kiFgyS-kccZuSwQ59ocHFZIL-46PXtKRdDcn8hrwH2xTyuJHTIYrYlFgt8EkgS-y-R9U5JotegfG-9Xh8UPZ-uRz2yvhnkiw5KeQLrzZ4vpoN5ocFySNNT0b_JWkCvb4SEYq5JapN3I-aC2JC6JIgPoVpk8DSmGCKCdftcLbS0whdIVgX3wlrfxlg7wnf9r2LMbb3p9sad4cjsjodXKz8WM1duX14OO5ftcXfQHy1VNeVmjq7emlft0fPpx41qZnA17gyf7wLtLY-NXV7FdSOAzWLPXvXHk-LnH1XSCkClCiwEKK9XeH80rrcvLycVKLJp4ZXKLrLepP5haYGL3yVJheNNhZtVzb72cZO5Cky-0PUhefXky4ZT71gwln3_sQFy09cei_rPv3iooMneDzv_FwAA__9CmBSJ)
[Fast Query](https://cockroachdb.github.io/text/decode.html#eJzsXN1u28a2vq6fYuCbyoikzv8Pe1JUcZRCPY6cYylFAyMQaItxWNOUQUlt3LN3UfQZcrmfrk-yQYqaGVK_pCxFtpuLyB9nzZo136y1ZokaslYDP3nR0B-EDjgeXF5HA_fy48sX4Pj4BPyKYR3VGah8krzHaW0cXoeD38Ja4IfjT7WrcFwFF2M_GAEMMfwGym8wBUg5DDtQVsHVANURqaujg4NaDUTeIOp7Ue-XgR8Oe4F_44_AR3cIRh890Pc-uONgBH51g7HnABrLe6F7EXi93_2r392rpNci8UEYyw9uR_6N_7sX9T4MIs-_CnvX3t1wSZ-D47Nmo9sE3caLkyYI3NDrBf5F5Ea-NwSVg6-SK34ftNpdCdqnXdB-e3JSPfjqwh8M3ZvbwGqcNEx6383rE43DvHTfHblDb9S7872g37u4zTQOR-5oPASd7lmr_cP04vFpu9M9a7TaXXB4G_k3bnR3CN6ctV43zt6B_22-A5WpyY3OcRVY5jQ6x0dZBR-ue_Y8epH3wVwYglenZ83WD-2JVlvwCJw1XzXPmu3jZgeYDpW45bQNXjZPmt0mOG50jhsvmzNDGpOSAQ3dmfGMVGY0Lb3mYBPOk4GicZgbY9KY0R8LLVTdar9s_pxzkp47Hg16ftj3PvVW8JnhcLoca-hcSFhldnXXUJenJKVhoYY7_Zl46cyooNM9TTy0kvfmhQZlWLKm5_c_zbI048TLB3zVeN06eWcFxzQgqsDWbGutggkFVZBXWAWTIDw6OPr24KBx0m2epaniwh16w1v30qvfji8C_7Keyx2t9o_N4y7odBvdVqfbOu6Ar88PAADg_5P_43-Hl4NgfBMODx1wri8mDanFh_rq-6rVK_LckdfvuaNDBxzGSbcGVQ1JgIRDuENInSnIMH8GoQPhodWz7w9Hfng56l0OxmHcGxOGiSXw0R-OBr3LQdAb3d16sfo4H9kqQvcmud6bOFUv0zYOAq0aWg3R4Dd9HWEmEEza_l1dmxB75bbOCpKI4ofAivHgHXCiiHwInEwieet8EAjVQ6Ajn9C27yiIMCmWUrMHtEyy-va9ZN95KL3RMOgQWqeEIU7X2WgEEnTH8UKkkGS3G01BVpCSYtfbbylWNtloinoKwgw-BE7KbjQF-SCUL8-me0LH5htN0eDBDAm-wwRbipayG01RL3mcPEgHUYewOiKQy33jgWMm8C73l8JsYEzo8gi5_-RRipXy-0txTqgku_5yV46TcqVZ8ZDBCj0IJ9l0hynMDKKME7bvGaVcHVKYDIrEcir2xEvKhQ0mDuUOEXVGGSVorboMw11_oxGKEb7DHac4K5gJums3KcVK6R2nBCeSiF3vOKU4KZVJivNBKd71rbNSdGy43xQnBnGE1S4r2FK0lKrkS-TXfeeh9EbDhENUHTECJflnoynJypPYaIpy8tg3moJ8PJ2NpiAxj3ujKZpfvwwPB--__jZ3-sg-KnLw1dJDR7EpuYNBfXfk9W4Gff-D7_VBt_W62ek2Xr_JNKe0zbbOPWoUuBe9uQ2Xg3Dk-qEXzbPDNN4Ohv7IH4Q5gdto8It3OcofhVp9sMmcUXnbbv3f2yaYnC0xtPWyBPWuvTv7OElibOaUi9U1cC_SuVaseS-S9vsTbZWZIynZ4eYfSMmeRYnlkpMnZvlSmC7X9BBKFRjLqiC7CDae8l4Fhuo1DrBY7rfR4ZWCmV0AxBwkHYjqUHKu8DoxSzDacWonWKEN7vYm42-dFqzI8nQ2icQvT4xx5K2TsvzUyr4Qkgn_rXOCKV5RPe8JI-mct08IpDs8s1KKjx2Fy_Kvml-ehuy2t3U6-Ipf30sRQiHbDiXTnX_rtKj9Z8XUPttnYwtBgwhB-D75KMMDhg7EdSwgh-yfsqw0LU-iLCtIypMoywpy8vjLsqKEPN6yrCATj70sK0jHUynLCtLyyMuyPWBD3HNVthEd2IGsDjkneJ0qFTG0jTL1fvnYuDQrxskTKc2KkfI0SrNinDyE0mwHOeShfMPbUaQ8-qqsGB1PpiorRssDqMo2_FZXMJfu_7e6MgeqCXQIr0POqFrrgNsDSaUbVGSlaHnsFVkZUh57RVaGk7giWx4_e8JImbRaipD9T6s7CpdHXJaVoeMJlGVlaHkAZVnJu0Nl2EB836Om1KMpyiGyjghF6p-SrCwrj78iK8zJwyjISqePwnzsf_bYoBQrzMZjrcQKE7HvTrFRIVaYjSdRhxVm5QGUYZt8sS2ePL7Y99rJIynNn9-cNFptUDl9062Cn5pnL047zSpotn86Ap3mSfO4C5IHlYb17Os0L-r5RxpSseRDo8ANvSF4dXb6GlRSdUGQUxUNxmG_UqkMxzeVIKjPvOUTfAMQhDD_WQX4CDQ6IB0wmWElpzwRsGzIvbUzbgzAD2enb9-AF-9mLQuCuv1i2ulgQ_DjaattP8DT6IALcNqeRxV4Di7qfh-cnr1snsWjzJN52ewcg5PW61YXIPjtQa1Wqx2k2_kB-Pvzf_7-_Offn_8Eqcs6mVebOjj3dImD0GQQR03m7siMEjfq-6Eb-KM7B5xDUAMIvrcF4s1i6IDzaPDb8Hmu7XIwHDkAE8GgqkOWUfyh74AKQkd__PFdBR9VQQUf1WrfxVdsqeSN0H545YAatq_fRuPQc0AFV2VVVXOd_HDkRV4cOldawdABlRpOxD6nYskbplPHX81a4jGO1Fz5fQfBWS5n9CXGhG5Qs6ZSwf9C8Gh26Plc56RmCZ-ZgWZd1hWVMwIT6uGU76peBwQnC_H8efongvHfeNbUmcmAc_dyNHaDeKFmTVq6IjOyoRfVktd5V4LB4Hp8a8XO97PPWRkNf21nJXNqr707o_ocvwfPwbm9DDnxdAppD-BGXqxhkXR2cZNHAqtgug3EKzN5thnE6TuG0GqNF8tujvFiuzJeIolcJLeBs_xVymfy_E3eA--HIwcgWIdwkeA0JeiEMF9skSs-w0eg8iy2qvIMoeozO0BnRkpzbbZ5kftN_Wy-G67QsolDyCPdI2mW8_xhgVtwBWld4lXmZfPzUtHsQs5byQULmuT4mcVYf1lX9LyKBuPb2sVMSK5Y1dxqmp3fIWA4vnHEigWeZ0Vs_DoDrKfyvl3H7lwlOYHkykLvWuBkhCBah2pNiq69u8QbyKIVnZe5YvE4dYmqXLPbGi5d1rPX9tnqMxLnoXVnOrx0QxAE36__Jv1q5P26XHcZv88X4w4rNMYmDlvSI62P5LvUVeTexKoBgAAAJOJmyREAgLDkb6GAaSgENlCQGFBQwZp9FosVGpSR-7F6Td4yqueMs3jQDQjZ2IJCXG_M28ZgTQsWc7Cxh8zrs4353BfXlBSY6Uo_WKxtYw5WeeKag95XzK3SViYFrKl63kwzxE9UC7RIdaYl0ycdB08-lBFDcKIg_VDFl3HeOGuGTCGqNvD4QlGfcjChKmU0EUMp_QIbkOFNJB8Is1kFidjcllSPskDGtnlgMtPMmqaTy6ieiGXGWam6DMiYs0osNTTTZ46Tz1O9uE-GA9t3siucVZ51hX1G2Tms07Z2pZn59z-1Wg0IRDgEtfgfkAoqnP6NEEeETQGhWJEpoBBDNAUMI2EAx1Ar4BBxOQVSmj4YKow0wAjL6ThYcCJ4CggUBE4VEAm5RAYIQTTAFNpAmj6Y8ak5RCHOmQZKKGqA5NwAxaZiFEJIoAFUcgOYtFq45oBCKIWlQDHTh1IipgBxKrABjFmA20BgaQFJDVBUq0ZCImYBYQHFzaASQWgBzTUlVBJlgNJLTwmDlBqAqDSAmskRxqgeh3AqjDbB9JJQKimnBjCJDTBLQqmUwgKKaaupgny62pRBKCyAzDgMSkMvE8wQwgS3-gjBtaFMEjMOk4waMcW4Ua2EYZQpySwxZVaOQ4a4ARyZFszMFATizAJCaUcSGGJqAOcWEMZHBRFQT0FQLKABFBttkmFttVKcWUBiaIDSfsAgNPHDIGWaN0YopzZQQgPOuQUEtoAiNtAzZURA7cox0L7DSDxvA6g0gyqsPZFRyZUWY5RTG0itjTFmBo3_NoALomfKFDcWMCXN5FicHaYgXlNtDkdMCgMkMWKYYgMk1zHHuBRC9xFI6DBjAilsAOY6BTCBJTOACKKnIKhEUIN4EgZwHWZxKBirBROUGSCVGZRzHUxxXJjJScIhtYD2nRgQW4zbLWamksX10RQIpUOTSQm5US0RsQAxVkvJkV6feM-yAIbGasUs1Yoro0BJ4xQKSr1nMYUw0rYpLMVUG4eUU6UBFxRpIIQOZw6l0ONwxIQ2Jw56HQtJBuAWoHYLswG3xYQN9K4ZA2UBAS0xofcFThDXvsPjxKeBwoJP5yOg5b0x0MsYA2m1KJ3SBKWKaQVxVjVAGVeWApv9RwqMtaFSYKUNlYIQndKkIAqbFgp10CoIIeYW0PkgBjoNxkCzowiC2ikUI1D7tWJEaXoVY1AnbyUw0guMIORQzxtBTKApfyBHCOqaCQqBENVIQmpqIygh15NHUDIkLck4O2qkIMFmBMWQDrgYYZ0AEIIIaeeNEcGmmCMQ6YSNEOFYr2qMqNVGmSkLEGIEWZKcYrZesZm7344JJarOVt1vL30_fOHvN6TKVtzJTj8-39ed8aki9-oq8q7ckT8Ih8t6gKzpw_ENOHeHz5MfcqpgMB550fMKO1p6NxnMtaDYPXGQ7Zz8hJRYkv6YpG3Ba9iSU5a9c7-g9-fsb5wLecvptk7lOGLZEZx4LukPonouYnYuU70f_GDkRUNQGUVj65f-aTOCB_8NAAD__8cijjs=)

**Comment by RaduBerinde** [comment]
Thanks for reporting the issue. Indeed, we have not yet implemented transformations to push group-by into joins. This is tracked by #47393. I will close this one, but I left a pointer to this issue so that we can verify any fix covers this particular example.

**Comment by SWDevAngel** [comment]
@jrote1 Hi Jake. Thank you for contributing to CockroachDB this year. As a token of our appreciation we would like to send you a gift. Please DM me on our [community Slack](https://cockroa.ch/slack) `@lisa` so I can send you a link. (If you don’t want a gift, we also have a charitable contribution choice.) All orders need to be in by December 13, so please send this asap. :)
