### ISSUE TITLE
sql: create a mechanism to control/protect system from statements

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#54624]
**Is your feature request related to a problem? Please describe.**

Sometimes a cluster becomes unstable due to bad properties of a single statement or a large volume of concurrent instances of such a statement. It would be highly valuable in these situations to have a mechanism to contain the damage caused by such a statement.

**Describe the solution you'd like**

In cases where the cluster is unstable due to a high query rate, it'd be great to have a mechanism to rate-limit how quickly a gateway will serve a given statement that might cause problems. 

I envision this looks something like a pattern matching language over queries with certain actions like rate limiting and transaction cancellation. I'd think we'd want to match over:

* Statement fingerprint
* Application name
* Placeholder values

This would be an extremely valuable tool to help mitigate production outages.

**Describe alternatives you've considered**

More generalized admission control https://github.com/cockroachdb/cockroach/pull/39768

Jira issue: CRDB-3734

**Comment by rafiss** [comment]
A lot of this is discussed in #51643
