### ISSUE TITLE
sql: drop schema doesn't perform a privilege check

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#54637]
Currently, even if a user has DROP privileges over a schema they can't drop it (if they're not the admin or owner) because https://github.com/cockroachdb/cockroach/blob/87e6f811a3ab9b0b66bb2b0962be196306ea00c8/pkg/sql/drop_schema.go#L75 doesn't perform a privilege check as it should.

**Comment by solongordon** [comment]
Can you say more here? I believe we intentionally do not support DROP privileges on schemas and only the owner or an admin can drop it. This matches Postgres behavior.

**Comment by arulajmani** [comment]
Now that I look at the set of schema privileges, turns out `DROP` isn't a part of the set of schema privileges, so this seems by design. FWIW, I do find the following behavior slightly surprising: 


```
user root

statement ok
CREATE DATABASE db;
USE db

statement ok
GRANT DROP ON DATABASE db TO testuser

statement ok
CREATE TABLE test_table(a INT)

statement ok
CREATE SCHEMA sc

user testuser

statement ok
use db

statement ok
DROP TABLE test_table

// This fails.
statement ok
DROP SCHEMA sc
```
