### ISSUE TITLE
sql: add max active transactions 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#54652]
We should add a cluster setting and session variable that allows users to set a `MAX ACTIVE TRANSACTIONS.` This can help provide rough protection to the database from excessive workload. The value would default to infinite and be configurable to users. If a transaction would be sent to the database that exceeds the number of active max transactions, we would return a unique error to the clients. 

Jira issue: CRDB-3732

**Comment by asubiotto** [comment]
If we have a max open connection limit, what does this max active transactions limit give us that max open connections doesn't?

**Comment by awoods187** [comment]
You likely want to set the max open connections much higher than the max transactions so that your application can have many connections to choose from. Limiting the max transactions effectively limits the active connections and ensures that you can't have too many database activities ongoing.  cc @jordanlewis in case i missed something

**Comment by yuzefovich** [comment]
Seems to have been addressed by #118781
