### ISSUE TITLE
debug.zip an option to limit what logs files are included

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#54654]
**Is your feature request related to a problem? Please describe.**

an option to not grab all of the log files that would reduce the size would facilitate troubleshooting exchange with customers.  It is common to see 1GB to 10GB debug zip files in the field.  Uploading this on Zendesk, GitHub or other methods requires hours and often fails due to the sheer size.  The typical config that results in the large debug.zip are:
 
- [default log rentetion](https://www.cockroachlabs.com/docs/v20.1/debug-and-error-logs) increased to a larger size to retain more historical log for troubleshooting
- a large number of nodes (more than a dozen)

**Describe the solution you'd like**

An option to limit what logs files are included (perhaps with more recent logs)

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by florence-crl** [comment]
cc: @piyush-singh

**Comment by knz** [comment]
I have analyzed this issue further. We want to restrict also goroutine dumps and heap profiles, not just log files.
