### ISSUE TITLE
SQL: add max open connections

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#54653]
Similarly to https://github.com/cockroachdb/cockroach/issues/54652, we should add a cluster setting and session variable that allows users to set a MAX OPEN CONNECTIONS. This can help provide rough protection to the database from excessive opened connections. The value would default to infinite and be configurable to users. If a connection would be opened against the database that exceeds the number of max connections, we would return a unique error to the clients.

**Comment by knz** [comment]
dup 35428
