### ISSUE TITLE
sql: allow UUID[] literals to be written as '{uuid-..., uuid-...}'

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#54672]
Postgres emits UUIDs in this format when using pg_dump, and allows users to enter this format in the SQL shell. We should support it too.

Currently, this errors in CockroachDB

```
root@:26257/defaultdb> create table t (a int primary key, b uuid[]);
CREATE TABLE

root@:26257/defaultdb> insert into t values (1, '{18e7b17e-4ead-4e27-bfd5-bb6d11261bb6, 18e7b17e-4ead-4e27-bfd5-bb6d11261bb7}');
ERROR: value type string doesn't match type uuid[] of column "b"
SQLSTATE: 42804
HINT: you will need to rewrite or cast the expression
```

**Comment by rafiss** [comment]
Removing the good first issue label since I'll be pairing up on this issue with a new hire

**Comment by z0mb1ek** [comment]
HI. When will it be released?

**Comment by rafiss** [comment]
This is released in v20.2.0 already

**Comment by z0mb1ek** [comment]
I use 20.2.2 and it not working

**Comment by rafiss** [comment]
Thanks for the details. This issue only addressed INSERT/UPDATE functionality. For IMPORT PGDUMP, there remains more work to be done: https://github.com/cockroachdb/cockroach/issues/29043 and https://github.com/cockroachdb/cockroach/issues/56593

**Comment by z0mb1ek** [comment]
it strange but i see 
```
ERROR:  at or near "{": syntax error
DETAIL:  source SQL:
INSERT INTO "public"."video_meta" ("video_id", "associated_ids") VALUES ('000c7502-b2f1-428e-98f3-45c9afded2e1', {a9b61bcd-86c9-423c-89fe-a0a38344129f})
```

**Comment by rafiss** [comment]
If you are writing an INSERT statement, the array must be in single-quotes. See the initial PR description. (This is the same in PostgreSQL too)

**Comment by z0mb1ek** [comment]
thx!!! it is TablePlus bug
