### ISSUE TITLE
SQL parse fails on dollar-quoted strings with digits in their delimiters

### ISSUE THREAD

**Issue by travigd** [cockroachdb/cockroach#54676]
**Describe the problem**

This is only an issue for delimiters with digits.

Minimal repro:
```
SELECT $foo1$foo$foo1$;
ERROR:  at or near "$": syntax error
DETAIL:  source SQL:
SELECT $foo1$foo$foo1$;
       ^
HINT:  try \h SELECT
```

**Expected behavior**
This should return the string `foo`.

**Comment by solongordon** [comment]
Could be a good first issue for an external contributor. See #44130 for PR which originally added dollar-quoted string support. Also cc @damienhollis in case you would like to come back and make another contribution 😉 .

**Comment by adzimzf** [comment]
Hi, I'll work on this
