### ISSUE TITLE
sql: statement IDs included in transaction stats may not be recorded in statement stats 

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#54697]
If the `sql.metrics.statement_details.threshold` cluster setting is set, statements will only be recorded if the statement meets the specified threshold. When transaction statistics are recorded, the list of statement IDs that comprise the transaction always includes all statement IDs (regardless of the individual statement execution times). This can result in scenarios where a statement ID has been recorded in the `txnStats`but does not have a corresponding `stmtStats` entry for it.

**Comment by solongordon** [comment]
We should also disable transaction stats collection if statement stats are disabled.

**Comment by solongordon** [comment]
We discussed this in the SQL UI Weekly. It seems like this setting is very rarely if ever used, so the decision was to disable transaction stats collection if `sql.metrics.statement_details.threshold` is set. We will also remove that setting entirely on `master` and see if anyone complains.
