### ISSUE TITLE
server: re-add support for unix sockets

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#5469]
This would be particularly helpful for the "real binary as test server". We could use a temp file as the unix socket, removing the need to parse stdout for the dynamically-allocated port.
Main issue I can think of is that `--host` is used for both the grpc and status servers. Some ways to get around that would be to disable the status server, or split the `--host` flag.

**Comment by bdarnell** [comment]
This would be pretty easy to do if we listen on a unix socket *in addition to* the tcp socket. That way gossip/distsender/etc could remain tcp-only (on a kernel-assigned port) and we'd have a unix socket just for the local client connection. (If cmux is a problem here we could make the unix socket pgwire-only)

**Comment by tamird** [comment]
cmux shouldn't care.

**Comment by mberhault** [comment]
there's still a question of how to handle the different ports, and there are multiple ways to do this:
1. additional unix socket just for rpc
2. disable http server when serving on unix socket
3. provide a separate `--host` for http server
4. http server listens on default (localhost) when unix socket is specified

1) is good if we want to support unix sockets in general (as opposed to just for testing)
2) works until we need to have a more dynamic setting for http-port (same reason we need sockets now)
3) feels overkill (except when using unix sockets, `--http-host` would just default to `--host`)
4) feels like a weird case

**Comment by tamird** [comment]
For your use case you just need 1. - you could then start the server with `--port=0 --http-port=0 --sockfile=...`

I wouldn't get bogged down in the general solution for now since we're still likely to ditch http-port soon.

**Comment by mberhault** [comment]
Sounds good. I'll add the extra flag. Shouldn't be too tricky.

**Comment by mberhault** [comment]
Well crap. Turns out the socket path in postgres is a directory.
The actual file ends up being (from go libpq): `path.Join(host, ".s.PGSQL."+o.Get("port"))`

For example, the default psql socket is really: `/var/run/postgresql/.s.PGSQL.5432`

Which means that this really doesn't help with dynamic ports since you still need to know it when going through libpq (although we could `ls` the directory).

**Comment by mberhault** [comment]
or, we could tell the cockroach server to use whatever we give it (eg: `/tmp/.s.PGSQL.1234`) and specify that fake port to libpq in the connection string. not pretty though.

**Comment by tamird** [comment]
Yeah, that seems fine. Doesn't rank high on the list of worst hacks in our
code :)

**Comment by mberhault** [comment]
ok. fair enough. uniqueness is not a problem since we already have a temp directory, so I can just put that in there and pick some arbitrary number.

**Comment by mberhault** [comment]
Sample invocation:
```
$ ./cockroach start --insecure --logtostderr --socket=/tmp/.s.PGSQL.12345
build:     alpha.v1-1329-g5da83ab-dirty @ 2016/03/23 19:17:18 (go1.6)
admin:     http://fishmonger:8080
sql:       postgresql://root@fishmonger:26257?sslmode=disable
socket:    /tmp/.s.PGSQL.12345
logs:      cockroach-data/logs
store[0]:  path=cockroach-data
$ ./cockroach sql --url=postgresql://:12345/?host=%2Ftmp%2F --insecure
```

Turns out libpq doesn't like paths in the host-part of the URL, but the above works.

**Comment by tamird** [comment]
LGTM. I think you can use paths if you url-escape them.

**Comment by mberhault** [comment]
nope, tried that:
```
$ ./cockroach sql --url=postgresql://%2Ftmp:12345 --insecure --execute "select 1"
parse postgresql://%2Ftmp:12345: invalid URL escape "%2F"
```

**Comment by tamird** [comment]
:(
