### ISSUE TITLE
Rancher: bring updating the rancher helm chart into the release process

### ISSUE THREAD

**Issue by jlinder** [cockroachdb/cockroach#54704]
Rancher has its own set of helm charts separate from the normal places for helm charts. A helm chart was [added there a year ago](https://github.com/rancher/charts/pull/324) and hasn't been updated since. A [PR](https://github.com/rancher/charts/pull/654) was put in to remove the chart when it was discovered the chart existed.

Figure out what we want to do with this. Questions to answer:

- Do we want to maintain this helm chart or have them point at our primary helm chart location?
- If we decide to remove it as the PR indicates, how do we want to message that change?

[Conversation in which this was discovered](https://cockroachlabs.slack.com/archives/C4A9ALLRL/p1600274194235500).

Epic RE-227
Jira issue: CRDB-3724

**Comment by kenliu-crl** [comment]
REA team triaged this today and decided to close.
