### ISSUE TITLE
opt: per-span cost causes regression on TPC-C

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#54702]
We saw a drop in TPC-C performance [on September 4th](https://roachperf.crdb.dev/?filter=&view=tpccbench%2Fnodes%3D3%2Fcpu%3D4&tab=gce). I was able to reproduce this fairly easily (before = 11a82264044ed8edc7d1fca2b912296d6f576a1a, after = 9fae2abb48a00c26ac0344f35cd100df7faa2aec):
```
name  old warehouses  new warehouses  delta
tpcc        625 ± 4%        530 ±18%  -15.20%  (p=0.008 n=5+5)
```
I bisected this to https://github.com/cockroachdb/cockroach/commit/8755d9afe9af5cf3a742904732c72be70cd43a22. It appears that something in that PR is causing issues for TPC-C.

Interestingly, we do see a change in one of the Delivery transaction's queries [here](https://github.com/cockroachdb/cockroach/commit/8755d9afe9af5cf3a742904732c72be70cd43a22#diff-29cc6326af864b8f79f7d40ee12bf42fL832). The plan moves from a scan of 10 precise spans to an imprecise scan over a secondary index, a filter, and an index join. This change seems strictly worse to me. This is supported by the fact that the plan does not change in the case where we have perfectly accurate stats.

So it appears that we have a regression here in some capacity. We should have reasonably accurate stats in TPC-C, so I'd be surprised if we were using the no-stats plan, but we should confirm. Even if not, something else is going on with that PR.

Assigning the `release-blocker` tag to this for now, until it's better understood.

**Comment by RaduBerinde** [comment]
@rytaft mentioned that our index join costing is not in line with the lookup join, that probably contributes

**Comment by RaduBerinde** [comment]
Hm.. I don't think a change in `tpcc-no-stats` is relevant, we probably estimate that very few rows (less than 10) would pass that filter. We need to see what plans change, and why our "with stats" testcases do not reflect that change.

**Comment by RaduBerinde** [comment]
I reproduced that plan, and it's because there were no stats. It looks like it is taking a while for table stats to be generated. I used `workload fixtures`. @rytaft I thought that would populate stats automatically too, no? Maybe we regenerated the fixtures for the FK changes and that broke it?

**Comment by RaduBerinde** [comment]
> This change seems strictly worse to me.

I looked at the details of how we get that plan, and it's not crazy. The optimizer estimates that only one row will make it to the index join. Scanning a single contiguous span (estimated to return 9 rows), running a filter on 9 rows, and index-joining one row does seem cheaper than scanning ten disjoint spans.. I don't think we should try to revert this plan, we should focus on making sure the fixtures have stats.

**Comment by RaduBerinde** [comment]
We discovered that a PR inadvertently removed the stats that we were supposed to inject for this table (and a few others) when importing fixtures: https://github.com/cockroachdb/cockroach/pull/35349/files

It's likely that until now, the "no stats" versions of the queries involving these tables were just fine (this would explain why we didn't notice this until now).

**Comment by RaduBerinde** [comment]
The fixture backups have the same problem, presumably they were created by first using `workload import`.

**Comment by nvanbenschoten** [comment]
Wow, nice find! Thanks @RaduBerinde and @rytaft.

**Comment by RaduBerinde** [comment]
Let me reopen until we regenerate the backup fixtures as well.

**Comment by RaduBerinde** [comment]
Last two runs look good (600 and 655).
