### ISSUE TITLE
sql: add support for session variable set transaction_priority=high;

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#54720]
We support setting individual transactions with a high priority:

```SQL
BEGIN;
SET TRANSACTION PRIORITY HIGH;
```
However, you can't do this at the session level:
```SQL
set transaction_priority=high;
ERROR: parameter "transaction_priority" cannot be changed
SQLSTATE: 55P02
```
We should let sessions be noted as HIGH (e.g., mission-critical transactions) or LOW (e.g., business analytics) rather than requiring manual setting on a per transaction basis.

cc @glennfawcett

**Comment by jordanlewis** [comment]
I think this is supported - use `set default_transaction_priority` to set the transaction priority for the next transaction to be opened. `transaction_priority` is an introspection variable that lets you see the current transaction priority. See #47641

**Comment by awoods187** [comment]
I'm going to convert this to a docs issue. The transaction_priority is meant to be used with show:
```SQL
root@127.0.0.1:57215/movr> show transaction_priority;
  transaction_priority
------------------------
  high
(1 row)

Time: 0.001s total (exec 29.8% / net 17.9% / other 52.3%)
```

**Comment by awoods187** [comment]
https://github.com/cockroachdb/docs/issues/8462
