### ISSUE TITLE
tests: time monotonicity checker reports many small backward jumps during tests

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#5473]
As reported by @BramGruneir:

```
W160322 12:03:23.842712 util/timeutil/time.go:86  backward time jump detected: previously 2016-03-22 12:03:23.842682277 -0400 EDT, now 2016-03-22 12:03:23.842682 -0400 EDT (offset -277ns)
W160322 12:03:23.850452 util/timeutil/time.go:86  backward time jump detected: previously 2016-03-22 12:03:23.850428043 -0400 EDT, now 2016-03-22 12:03:23.850428 -0400 EDT (offset -43ns)
W160322 12:03:23.875664 util/timeutil/time.go:86  backward time jump detected: previously 2016-03-22 12:03:23.875625178 -0400 EDT, now 2016-03-22 12:03:23.875625 -0400 EDT (offset -178ns)
W160322 12:03:23.918923 util/timeutil/time.go:86  backward time jump detected: previously 2016-03-22 12:03:23.918893554 -0400 EDT, now 2016-03-22 12:03:23.918893 -0400 EDT (offset -554ns)
W160322 12:03:23.935255 util/timeutil/time.go:86  backward time jump detected: previously 2016-03-22 12:03:23.935228182 -0400 EDT, now 2016-03-22 12:03:23.935228 -0400 EDT (offset -182ns)
W160322 12:03:23.948704 util/timeutil/time.go:86  backward time jump detected: previously 2016-03-22 12:03:23.948676377 -0400 EDT, now 2016-03-22 12:03:23.948676 -0400 EDT (offset -377ns)
W160322 12:03:23.950356 util/timeutil/time.go:86  backward time jump detected: previously 2016-03-22 12:03:23.950331067 -0400 EDT, now 2016-03-22 12:03:23.950331 -0400 EDT (offset -67ns)
W160322 12:03:23.966214 util/timeutil/time.go:86  backward time jump detected: previously 2016-03-22 12:03:23.966170214 -0400 EDT, now 2016-03-22 12:03:23.96617 -0400 EDT (offset -214ns)
W160322 12:03:23.981213 util/timeutil/time.go:86  backward time jump detected: previously 2016-03-22 12:03:23.981191448 -0400 EDT, now 2016-03-22 12:03:23.981191 -0400 EDT (offset -448ns)
W160322 12:03:24.018844 util/timeutil/time.go:86  backward time jump detected: previously 2016-03-22 12:03:24.018820367 -0400 EDT, now 2016-03-22 12:03:24.01882 -0400 EDT (offset -367ns)
W160322 12:03:24.050488 util/timeutil/time.go:86  backward time jump detected: previously 2016-03-22 12:03:24.050468479 -0400 EDT, now 2016-03-22 12:03:24.050468 -0400 EDT (offset -479ns)
```

@petermattis suggests that this is worthwhile investigating further, as negative clock increases, however insignificant, are undesirable and may underline an improper underlying implementation of time.Now().

@BramGruneir care to confirm this was ran on OS X?

**Comment by knz** [comment]
NB the followup here is to determine the root cause of the small backward jumps, not to change CockroachDB (see also #5472)

**Comment by BramGruneir** [comment]
Yes, I can confirm this was on OS X.  But you don't even need to run the db to repro this.  Just create a test that starts up a bunch of goroutines that call timeunil.Now().  

I have observed this from while running a single instance of the db with the blockwriter providing load locally.

Have we done any benchmarking with monotonicityCheckEnabled enabled or disabled?

**Comment by knz** [comment]
Yes I have ran some benchmarking and did not observe significant performance decreases. Also @tschottdorf suggested keeping the checker enabled by default only during Beta, as it will help us troubleshoot issues for the time being; we could disable it later.

**Comment by tamird** [comment]
The best way to prove this point is to check in said benchmarks.

**Comment by knz** [comment]
Status update: since #5476 #5522 and #5805 the monotonicity checker is not on the critical path any more, and only reports negative skews in excess of 10% of MaxOffset (thus 25ms in the default configuration). 

@petermattis found a discussion of the limitations of the clock source here: https://groups.google.com/forum/#!topic/golang-dev/DboHw1eCiSc This suggests that on OSX the time function is partially computed in userspace, thus presumably per thread. This would explain the divergence.

I would motion to close this issue as I have a feeling we are now sufficiently aware of the cause of the issue and that there is not much more we can do on our side than what the previous PRs have addressed already.

**Comment by BramGruneir** [comment]
sgtm
