### ISSUE TITLE
ui: add mirror pruning packages to yarn config

### ISSUE THREAD

**Issue by koorosh** [cockroachdb/cockroach#54735]
`yarn-vendor` is used as an offline mirror for third-party packages. 
Currently, it doesn't remove unused packages so it grows constantly.
Yarn provides the ability to clean up it automatically with [`yarn-offline-mirror-pruning`](https://classic.yarnpkg.com/en/docs/yarnrc/#toc-yarn-offline-mirror-pruning) config in `.yarnrc` file.

Make sure it doesn't break the build for main package and `ui/opt`.

**Comment by dhartunian** [comment]
Given the fact that the protobuf js client installation process *also* uses the `yarn-vendored` directory, we can't properly prune it via the `/pkg/ui/package.json` file alone. Closing this for now since the issue is a bit more complex and requires that we clean up the protobuf js install first.
