### ISSUE TITLE
server: back-connect after node join fails with mismatched node ID

### ISSUE THREAD

**Issue by charlie-pisuraj** [cockroachdb/cockroach#54762]
Hey folks,
Currently we have an existing cluster, and would like to add additional nodes to the cluster.
The new node was able to establish connection with node n0 and joined the gossip network
`node connected via gossip and verified as part of cluster "xxxxxx-xxxxxxx-xxxxxx"`.
However when the new node is trying to connect to the next node we see the following error:
`initial connection heartbeat failed: rpc error: code = Unknown desc = client requested node ID 2 doesn't match server node ID 1`.
Could you please explain what the error means. What didn't match, and how can we fix this issue?

Thanks in advance.

**To Reproduce**

We created a cluster running secure mode. We made sure that all nodes had the same ca.crt as well as making sure that any previous data directories that the new node could read from was deleted, ensuring that it didn't have metadata of any other clusters. The node boots up, joins the gossip network but fails to join the next node then spams the same error.

**Expected behavior**
We have created other clusters with no issue, and we expected this to just work

**Environment:**
 - CockroachDB version 20.1.1
 - Server OS: GKE's Container Optimized OS

**Additional context**
https://cockroachdb.slack.com/archives/CP4D9LD5F/p1600975349012100

Epic: CRDB-8500

Jira issue: CRDB-3720

**Comment by irfansharif** [comment]
One thing of interest to us would be to see the start up command (including the join flags) used to start each node already in the cluster, and the new node you're looking to add. You'll find this in the logs for each node, at the very top. See "LOOK HERE" below:

```
I200924 19:58:03.973542 1 util/log/sync_buffer.go:195 ⋮ [config] file created at: 2020/09/24 19:58:03
I200924 19:58:03.973552 1 util/log/sync_buffer.go:195 ⋮ [config] running on machine: ‹Irfans-MacBook-Pro›
I200924 19:58:03.973557 1 util/log/sync_buffer.go:195 ⋮ [config] binary: CockroachDB CCL v20.2.0-alpha.3-1423-g2f5c96fba1-dirty (x86_64-apple-darwin19.6.0, built , go1.13.15)
I200924 19:58:03.973561 1 util/log/sync_buffer.go:195 ⋮ [config] arguments: LOOK HERE
I200924 19:58:03.973570 1 util/log/sync_buffer.go:195 ⋮ [config] line format: [IWEF]yymmdd hh:mm:ss.uuuuuu goid file:line msg utf8=✓
```

**Comment by charlie-pisuraj** [comment]
The initial cluster is running on EKS with 3 replicas and started with the following command:
`/bin/bash -ecx exec /cockroach/cockroach start --advertise-addr=${HOSTNAME##*-}-db.xxxxxxx.xxx --cache=25% --certs-dir=/cockroach/cockroach-certs --http-addr=0.0.0.0 --join=cockroachdb-0.cockroachdb --locality=zone=xxxx_xxxxxxxx --locality-advertise-addr=zone=xxxx_xxxxxxxx@$(hostname -f) --logtostderr=true --max-sql-memory=25%`

The new joining nodes are running on GKE and started with the following command:
`exec /cockroach/cockroach start --advertise-addr=${HOSTNAME##*-}.db.yyyyyyyyy.yyy --cache=25% --certs-dir=/cockroach/cockroach-certs --http-addr=0.0.0.0 --join=cockroachdb-0.cockroachdb,0-db.xxxxxxx.xxx --locality=zone=yyyy_yyyyyyyy --locality-advertise-addr=zone=yyyy_yyyyyyyy@$(hostname -f) --logtostderr=true --max-sql-memory=25%`

**Comment by irfansharif** [comment]
+cc @knz, who added the error, so might know more about it. Nothing about the startup commands jump out to me. @charlie-pisuraj, are you seeing this same error for every node addition attempt? Or did it come up just once in your initial attempt to add this new node?

**Comment by charlie-pisuraj** [comment]
I tried to scale up the Statefulset, and see this error in all subsequent nodes that are trying to join the cluster.

**Comment by knz** [comment]
Hi Charlie,

the error message indicates that the advertised address of the new node does not resolve to the actual IP address of the new node -- specifically, a node advertises another node's address instead of its own.

A couple of possible reasons come to mind:

- the most likely is that the name you pass via `--advertise-addr` does not resolve to the proper IP address. 

- the second most likely is that the name configured via `--locality-advertise-addr`  does not resolve properly.

I'm not sure about the exact solution since I do not know your network configuration; however as a starting step (to debug) I could suggest you try using numeric IP addresses in the advertise flags first, check that works properly, then upgrade piecewise to use hostnames until you find the exact problem.

Does this help?

**Comment by charlie-pisuraj** [comment]
Hey @knz thanks for responding.

I verified that the `--advertise-addr` does resolved to a proper IP address so I moved on to the next one with `--locality-advertise-addr`
I found an additional piece of log that I thought was not important
`invalid bootstrap address: &{typ:tcp addr:cockroachdb-0.cockroachdb:26257}, lookup cockroachdb-0.cockroachdb on 10.52.0.10:53: no such host`

I ran nslookup on my cluster's dns and cockroachdb-0.cockroachdb does resolve correctly to the Pod.

I'll give your suggestion a go, Thanks for the help.

**Comment by charlie-pisuraj** [comment]
Hey @knz @irfansharif 

We found the issue. It was one of the old nodes in the existing cluster. The public DNS was misconfigured with N2 was pointing to N1. It was able to form a local cluster within EKS because it was using the cluster's DNS to properly resolve the local address.

The new node in GKE did not have any issue once the above problem was fixed, the new nodes joined correctly.

Could we request that error message be updated with more details? At the moment we really don't know what it means, what the server is seeing so we could compare to what we expect.

Thank you again for your help

**Comment by irfansharif** [comment]
I'm glad that you were able to get to the bottom of it. Thank you for trying CRDB out, and posting publicly. Hopefully it helps future users running into the same.

I'll leave it to @knz to decide what to do with the error message, but naively I suspect with networking configs and DNS setups there are infinitely many ways to shoot yourself in the foot, where we can never hope to generate sufficient error messaging to point to exactly where the problem lies. But maybe I'm missing some obvious suggestion here if this is a common enough problem. I'll close this issue out, but Rafa may have better ideas.

**Comment by charlie-pisuraj** [comment]
Maybe better wording? Something along the lines of 
`client request node ID 2 at <advertised address> but does not match information from server node ID 1, <and information that it got from node ID 1>`

I understand that there are so many ways to get it wrong with networking, but we could make the message contain more information. The entire time we were convinced it was the new node that was the issue, turns out it's the one that was already working.

**Comment by knz** [comment]
I think the request is reasonable.

**Comment by charlie-pisuraj** [comment]
Thank you @knz

**Comment by knz** [comment]
There are two different aspect to this issue:

- the existing log message should be extended to include the address used for the outgoing connection.
- the new node should attempt to establish a RPC connection to every other node very early on. This is separate issur #70111.

**Comment by knz** [comment]
this has been done ( in 23.2)
