### ISSUE TITLE
import: support import with default next_val columns

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#54797]
A lot of good discussion https://github.com/cockroachdb/cockroach/issues/48253

We started knocking off IMPORT of default expressions but didn't get to next_val for 20.2. Tracking issue to continue this work.

**Comment by Anzoteh96** [comment]
Would be happy to hear how things turn out in the end! There's some partial work / outline from #52910 (hmm...close that maybe?), which hopefully can be helpful for anyone who continues this later. :)

**Comment by mwang1026** [comment]
@adityamaru is this done with https://github.com/cockroachdb/cockroach/pull/56473? If so can you close?
