### ISSUE TITLE
colexec: implement vectorized table statistics collection

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#54803]
Statistics from the tables are currently collected using a combination of row-execution `sampler` and `sampleAggregator` processors which have been introduced before we began implementing the vectorized engine. I believe that stats collection will benefit noticeably from the vectorized approach (similar benefits as in the other use cases - faster execution, better memory management). In particular, I'm hoping that it will alleviate issues like #54670.

**Comment by asubiotto** [comment]
@RaduBerinde I think the optimizer team needs to prioritize this for 21.1 given that #54670 is an easily reproducible OOM and we've seen a lot of OOMs related to wide rows lately. We're happy to offer guidance here.

**Comment by RaduBerinde** [comment]
@rytaft I thought we had hit OOMs with large rows before and had a workaround in place, do you remember the details? I think it was around dynamically adjusting the batch size or something along those lines

**Comment by rytaft** [comment]
Maybe you're thinking of https://github.com/cockroachdb/cockroach/pull/40850? I didn't end up merging that PR since there were some performance issues identified. Seems like we should just switch to vectorized to fix this.

**Comment by RaduBerinde** [comment]
I see. Let's use the existing #41203 to track this.
