### ISSUE TITLE
acceptance: remove all docker and aws 

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#5482]
Acceptance tests should just run in multiple processes on the same machine.

**Comment by tamird** [comment]
Sounds like a huge yack shave to me. Making this hermetic is going to be
pretty unpleasant, I think.

**Comment by bdarnell** [comment]
I agree that docker has been far more trouble than it's worth for our tests so far, but we're just starting to do things with it that would be difficult or impossible to do without containers (e.g. #4712, although that isn't working yet), so I wouldn't be so quick to rip it out.

**Comment by tamird** [comment]
Closing this for now; the state of affairs today is pretty good.
