### ISSUE TITLE
sql: dropping a table doesn't make it unusable immediately

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#5483]
Observe:

```
root@:26257> create table bank.accounts (id INT PRIMARY KEY, balance DECIMAL);
CREATE TABLE
root@:26257> select * from bank.accounts;
+----+---------+
| id | balance |
+----+---------+
+----+---------+
root@:26257> drop table bank.accounts;
DROP TABLE
root@:26257> select * from bank.accounts;
+----+---------+
| id | balance |
+----+---------+
+----+---------+
root@:26257> select * from bank.accounts;
pq: sql/table.go:302: table "accounts" does not exist
```

The problem is probably about a lease on the `accounts` table persisting for too long.

Leases are released in:
- `acquire()` releases old versions: https://github.com/cockroachdb/cockroach/blob/fa47ebe/sql/lease.go#L473
- the planner releases leases after transactions:
https://github.com/cockroachdb/cockroach/blob/fa47ebed933d0bb9a9493e1c1b272a54499d9127/sql/plan.go#L377
- when hearing about new leases through gossip, leases on old versions of descriptors are refreshed:
https://github.com/cockroachdb/cockroach/blob/fa47ebed933d0bb9a9493e1c1b272a54499d9127/sql/lease.go#L642

It seems that the refresh does not apply to descriptors that have been deleted, which means that a node might keep using a lease for such a descriptor until either its `refCount` goes to 0 or its time expires. This seems wrong.

**Comment by dt** [comment]
Hmm, I think this might still be happening based on the test I added in #6381

**Comment by andreimatei** [comment]
Well the problem now is different: we have this cache of table names that's updated through gossip (so async, not tied to the descriptor leases). And this cache keeps resolving a name to the old descriptor id, which is now gone.
Unfortunately we can't just get rid of the cache because we want a txn that started using table ID `1` with name `A` to keep using ID `1` even if the table is renamed to `B`. So we need some sort of per-txn caching. I think I can use the list of leases a `planner`'s maintaining and look for the name through those leases. @vivekmenezes what do you think?

**Comment by vivekmenezes** [comment]
This looks like a bug to me. I see no outstanding transaction on the table.

**Comment by vivekmenezes** [comment]
I see your comment in 

https://github.com/cockroachdb/cockroach/blob/master/sql/table.go#L350

I agree that we need to move the db-id/name -> table-id map into the lease manager and not depend on the system config. That way the mapping expires when tableState expires.

**Comment by andreimatei** [comment]
well I don't think it can be all inside the LeaseManager. Or at least not
unless we make rename also be a schema change. I think we need to ensure
that a transaction can continue to use a name once it started using, and it
needs to keep referring to the same table. I think the LeaseManager can
have leases for two different tables with the same name at one time.

**Comment by tschottdorf** [comment]
Is it expected that I keep getting "pq: descriptor deleted" messages minutes after having had the drop-create race? I thought once the racing had stopped, I would be able to use the new table (given a little bit of time).

**Comment by tschottdorf** [comment]
Ok, a few more minutes in and I was able to create the table again (and subsequently use it).
This is a fairly annoying bug in practice and I seem to be able to trigger it very reliably.
