### ISSUE TITLE
ALTER COLUMN TYPE to lower integer range (Ex int8 to int2) should fail

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/cockroach#54844]
**Steps to reproduce**
```
root@127.0.0.1:55511/defaultdb> create table foo (i int8);
CREATE TABLE

root@127.0.0.1:55511/defaultdb> insert into foo values (-9223372036854775807);
INSERT 1

root@127.0.0.1:55511/defaultdb> SET enable_experimental_alter_column_type_general = true;

root@127.0.0.1:55511/defaultdb> alter table foo alter column i type int2;
NOTICE: ALTER COLUMN TYPE changes are finalized asynchronously; further schema changes on this table may be restricted until the job completes; some writes to the altered column may be rejected until the schema change is finalized
ALTER TABLE

root@127.0.0.1:55511/defaultdb> show create foo;
  table_name |        create_statement
-------------+----------------------------------
  foo        | CREATE TABLE public.foo (
             |     i INT2 NULL,
             |     FAMILY "primary" (i, rowid)
             | )
(1 row)
```

**Desired behavior**
Our [docs](https://www.cockroachlabs.com/docs/v20.1/alter-column.html#altering-column-types) indicate that only increasing precision is allowed and that the existing data must remain valid. This `ALTER COLUMN TYPE` violates that.

I realized I was looking at 20.1 docs, but there's no mention in [20.2 docs](https://www.cockroachlabs.com/docs/dev/alter-column.html#altering-column-data-types) that this would be valid.

In PG,
```
vy=# alter table foo alter column i type int2;
ERROR:  smallint out of range
```

**Comment by otan** [comment]
hehe, yeah it's broken because....

```

demo@127.0.0.1:58266/defaultdb> select '-9223372036854775807'::int::smallint;
          int2
------------------------
  -9223372036854775807
(1 row)
```

**Comment by otan** [comment]
cc @solongordon i think this may be a release blocker as it puts invalid data into the table.
i have a fix in https://github.com/cockroachdb/cockroach/pull/55095.

**Comment by solongordon** [comment]
As discussed separately, we deemed @otan's fix too risky for 20.2 and would like to disable such ALTER operations in 20.2.1. @otan, would you please make this change? Then on master, we can merge the fix and re-enable these operations.

**Comment by z0mb1ek** [comment]
Hi. In what version it will be enable once again?

**Comment by vy-ton** [comment]
@z0mb1ek This will be enabled in 21.1. You can check out the [latest 21.1 beta release](https://www.cockroachlabs.com/docs/releases/#testing-releases) or wait for GA release which is coming very soon
