### ISSUE TITLE
sql: old descriptor ID used for dropped table because we don't wait for the new one to propagate through gossip

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#5484]
After recreating a table, future statements (INSERT and first SELECT below) use the old descriptor ID. After a while (2nd SELECT) the new descriptor ID is used. This means that the data inserted can never be referenced again. Observe this bizarre behavior:
```
root@:26257> drop database bank; create database bank; create table bank.accounts (id INT PRIMARY KEY, balance DECIMAL); INSERT INTO bank.accounts (id, balance) VALUES (1, DECIMAL '100'); select * from bank.accounts;
+----+---------+
| id | balance |
+----+---------+
|  1 |     100 |
+----+---------+
root@:26257> select * from bank.accounts;
+----+---------+
| id | balance |
+----+---------+
+----+————+
```

The problem is that `DROP` directly deletes the descriptor from the DB, and doesn't wait for anybody to ack this deletion. Therefore, commands in the same batch will continue to resolve `accounts` to the same descriptor (and same table ID) as before the deletion.
Future batches of statements get the new descriptor for the new incarnation of the `accounts` table (at least usually they do, see #5483), because they acquire new leases (and the leasing goes to the database and gets the newest version).

The plan for the fix discussed with @vivekmenezes seems to be:
1.  Add a `deleted` field on the table descriptor proto. This will be set synchronously, together with `up_version` when executing the `DROP` statement. It's semantics are that deleted descriptors cannot be leased.
2. Enqueue an asynchronous schema change operation that will actually do the truncation and the deletion (after `Publish`ing the descriptor change and thus ensuring that nobody has a lease on the table any more and so nobody's modifying it any more).
3. Have the `LeaseManager` respect this `deleted` field and not hand out leases.

There's similar problems with table renames that need to be thought through. An extra difficulty there is protecting against different nodes resolving the same name differently in a scenario like `RENAME A->B; CREATE A;`. We probably need to have RENAME leave behind the record for the original mapping of A<->desc id, so that the CREATE fails until all nodes ack the disappearance of A.

A question that came up during debugging is what the point of the `Executor.systemConfig` field is. I hear it used to serve as a cache for descriptors, but we don't do that any more other than through the `LeaseManager`. Except some people still seem to use it as a cache (https://github.com/cockroachdb/cockroach/blob/8df5343e2f07f040b93349ef050294a264d55db1/sql/table.go#L292). Maybe some cleanup is in order.

**Comment by andreimatei** [comment]
depends on #5483

**Comment by vivekmenezes** [comment]
For rename you can
1. create new name for the table, keep old name as valid and add it to a list of old names in the table descriptor. Set upversion to true.
2. lease manager is modified to not hand out new leases to names in the old names list.
2. The schema changer publishes the new version of the table guaranteeing that no one is using an old lease on the table.
3. Delete all reference from old name to the descriptor and delete the name from the old names list.

What do we do when Rename A -> B; Rename B -> A; ?
