### ISSUE TITLE
Slow update (Mean service 88.4 s)

### ISSUE THREAD

**Issue by luiscosio** [cockroachdb/cockroach#54842]
**Describe the problem**

We are experiencing an enormous amount of delay since upgrading from 2.1.11. Our database consists of 6 beefy nodes (64vCPUs and 64GB of RAM) and it is around 3.7 TB

![image](https://user-images.githubusercontent.com/1666/94353692-a2d5f980-0039-11eb-8f26-b3683b19a73f.png)

**To Reproduce**

Here is the diagnostic:

[stmt-bundle-593226799923298309.zip](https://github.com/cockroachdb/cockroach/files/5287595/stmt-bundle-593226799923298309.zip)

**Environment:**
- CockroachDB 20.1.6
- Fedora 7

The cluster works just fine but sporadically ends up eating all the resources of the whole cluster when that query runs and our application crashes.

**Comment by jordanlewis** [comment]
Sorry for the long delay. Are you still experiencing this? It looks like there are FK checks to do, which has a different implementation in 20.1 than 2.1. You can try running the updates in batches as an idea. The diagnostic bundle you sent looks fine - there isn't a long execution.
