### ISSUE TITLE
geo: WKT writing not working with GEOS bundled with CockroachDB

### ISSUE THREAD

**Issue by timgraham** [cockroachdb/cockroach#54841]
**Describe the problem**

Django's `WKTWriter.write()` doesn't work with the GEOS library bundled with CockroachDB.

**To Reproduce**

```python
> from django.contrib.gis.geos import GEOSGeometry, WKTWriter
> wkt_w = WKTWriter()
> ref = GEOSGeometry('POINT (5 23)')
> wkt_w.write(ref).decode())
POINT ( )
```
**Expected behavior**

Ouput of: `POINT (5.0000000000000000 23.0000000000000000)`.

The expected behavior happens with GEOS 3.8.1 compiled from source but not with the GEOS 3.8.1 included with CockroachDB.

**Additional information**

Here's Django's interface to [GEOSWKTWriter_write](https://github.com/django/django/blob/793bd24db6dac863ca4fb4166137f349d15f3c1c/django/contrib/gis/geos/prototypes/io.py#L48-L50).

If no one has any idea what the cause may be, I can investigate further. I'm not intimately familiar with how this all works.

**Environment:**
 - CockroachDB version 20.2 beta 2

Jira issue: CRDB-3710

**Comment by otan** [comment]
the WKT unit tests work, so I'm not sure how this came about.

**Comment by timgraham** [comment]
Could you point to how `libgeos.so` and `libgeos_c.so` are generated? Maybe inspecting that would reveal something. I've been looking more closely at the Python side but I haven't come across anything suspicious.

Incidentally, is it possible to make it so that `patchelf --set-rpath '/usr/local/lib/cockroach/' /usr/local/lib/cockroach/libgeos_c.so` isn't required? Also `sudo ln -s /usr/local/lib/cockroach/libgeos.so /usr/local/lib/cockroach/libgeos.so.3.8.1`? (For anyone else reading, we discussed these things at https://github.com/cockroachdb/cockroach/issues/54429#issuecomment-693731840.)

**Comment by otan** [comment]
> Could you point to how libgeos.so and libgeos_c.so are generated? Maybe inspecting that would reveal something. I've been looking more closely at the Python side but I haven't come across anything suspicious.

https://github.com/cockroachdb/cockroach/blob/master/Makefile#L798

You can try fudge with this if you are willing -- `./build/builder.sh mkrelease linux` will build the binary and libs will be in `lib.docker_amd64/`

> Incidentally, is it possible to make it so that patchelf --set-rpath '/usr/local/lib/cockroach/' /usr/local/lib/cockroach/libgeos_c.so isn't required? Also sudo ln -s /usr/local/lib/cockroach/libgeos.so /usr/local/lib/cockroach/libgeos.so.3.8.1? (For anyone else reading, we discussed these things at #54429 (comment).)

I took a look at this and it was quite complicated with our build setup, and we're revamping that in the upcoming release anyway (the issue in particular is that `cmake` and specifying `rpath` does not work when cross compiling).

Note we already special case mac because of this, but the patchelf tool was not available in the builder.

**Comment by timgraham** [comment]
Yes. I ran those commands from `/usr/local/lib/cockroach/` and `libgeos_c.so` is in that directory so I omitted `lib/`.

**Comment by timgraham** [comment]
I ruled out issues with the Cockroach GEOS fork by [compiling it from source](https://github.com/cockroachdb/geos/blob/9a297a2981d599a472ea1c81a94cf8e81c23a18c/INSTALL#L13-L27). All Django tests pass with that `libgeos_c.so`.

Perhaps it's best to wait and see if the revamp to the build process that you mentioned happens to fix this issue.

**Comment by timgraham** [comment]
I confirmed Django works without creating a symlink and modifying the libgeos files in Cockroach 21.1 beta 1. The strange WKT writing issues described here still remain.

**Comment by timgraham** [comment]
This started working in v22.1 alpha 4. `libgeos_c.so` and `libgeos.so` there are different than those in the alpha 3.
