### ISSUE TITLE
backup: Exclude specific tables from BACKUP DATABASE

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/cockroach#54878]
It would be useful if the `BACKUP DATABASE` could take a list of tables to exclude.  The use-case from a customer is that they have a single table within their database that's used for application-level locking/leasing.  They would like for it to have a minimal `gc.ttl_seconds` value of 60 seconds, while their `BACKUP` uses `AS OF SYSTEM TIME '-30m'` in order to avoid contending with long-running queries.

**Comment by mwang1026** [comment]
Related to https://github.com/cockroachdb/cockroach/issues/57386

**Comment by mwang1026** [comment]
Closing in favor of https://github.com/cockroachdb/cockroach/issues/57386
