### ISSUE TITLE
cli/demo: facilitate usage of the web UI with a secure session

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#54877]
Today the user must manually copy-paste the username/password combination from the output of `cockroach demo` into the web browser login page.

This is cumbersome, and becomes especially cumbersome if the password is different every time (the user cannot memorize it).

To minimize friction, it is desirable instead to make the URL automatically log the user in, for example by embedding the auth token in the URL.

**Comment by awoods187** [comment]
This is definitely needed to improve the UX of cockroach demo since without it the UX has regressed from earlier versions.
