### ISSUE TITLE
backup: Unclear error message when backing up below TTL

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/cockroach#54882]
The following error message trying to run a `BACKUP` command is hard for the novice user to understand or take action on:

`ERROR: exporting 1234 ranges: exporting /Table/1234/1/......: start timestamp 1601061411.226447920,0 must be after replica GC threshold 1601085664.733228480,0`

"Start timestamp" of what? The range of time that the backup is reading from, an MVCC range?

A message more like the following would be easier to take action on:

`ERROR: exporting 1234 ranges: exporting /Table/1234/1/.....: the earliest available MVCC data for this range is <<TIMESTAMP>>, but received a request for data starting at <<TIMESTAMP>>`

**Comment by mwang1026** [comment]
duplicates https://github.com/cockroachdb/cockroach/issues/47105
