### ISSUE TITLE
roachpb: condense output of various proto go structs

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#5493]
- `BatchRequest`
- `BatchResponse`
- `Transaction`: in particular, find a way to indicate very precisely but _briefly_ the difference between `OrigTimestamp`, `Timestamp`, & `MaxTimestamp`

There are others.

**Comment by petermattis** [comment]
@spencerkimball Is there anything else to do here? We have `BatchRequest.Summary()` and `Transaction.String()` prints a condensed representation.

**Comment by spencerkimball** [comment]
No this has definitely been addressed.
