### ISSUE TITLE
cli: `cockroach doctor` does not respect the `--timeout` flag

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#54931]
See this code in `cli/flags.go`:
```go
   timeoutCmds ≔ []*cobra.Command{
     statusNodeCmd,
     lsNodesCmd,
     debugZipCmd,
     doctorClusterCmd,
     // If you add something here, make sure the actual implementation
     // of the command uses `cmdTimeoutContext(.)` or it will ignore
     // the timeout.
   }
```

Look at the comment.

Unfortunately, the `cockroach doctor` code does not use `cliCtx.cmdTimeout`.

This should be modified according to the other commands, or the doctor command removed from the `timeoutCmds` list.

**Comment by spaskob** [comment]
Thanks for filing - I don't remember why I added the command in this list. It looks like it is unnecessary - I will send a PR to remove the doctor entries.
