### ISSUE TITLE
roachpb: use cockroachdb/errors.EncodedError inside of internalError

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#54939]
**Is your feature request related to a problem? Please describe.**

roachpb.Error is a wrapper around a number of concrete error types important for the cockroach transactional model. The object can be constructed from any go error. Go errors which are themselves implementations of the relevant concrete errors are properly wrapper for serialization. All other errors, however, are captured as just a string inside of the `roachpb.internalError` struct. The problem with this error is that it represents the errors used to construct it as a string, throwing away all structured information. This further means that any structured information will not be transmitted over the network.

This is not obviously a big problem today. The most important errors to detect programtically (in my opinion) which are today lost are `context.Canceled` and `context.DeadlineExceeded`. However, it may not be so important to detect these errors coming from remote procedure calls as the errors should be reproduced on the client-side as most of these deadlines and cancelations should flow from the client anyway. Unfortunately, there is no gaurantee that the context error will always be checked or that it will be preferred over the returned error from the RPC. In fact, we generally go out of our way to prefer the error being propagated from the call path.

**Describe the solution you'd like**

I'd like to see the `roachpb.internalError` adopt the `cockroachdb/errors.EncodedError` for its representation of the error used to construct it (when not a roachpb defined error). This would allow structure to be preserved.

**Additional context**

This approach was utilized for `execinfrapb.Error` in https://github.com/cockroachdb/cockroach/pull/37121.

**Comment by knz** [comment]
cc @tbg for triage and prioritization

**Comment by tbg** [comment]
I also just ran into a snag with this over in https://github.com/cockroachdb/cockroach/pull/54746. The whole `*internalError` setup is just unfortunate.

**Comment by tbg** [comment]
The bear poked me, so I will poke back. In the context of decommissioned nodes, we need a way for the KV API to return a general error from the RPC layer that we can sniff out as meaning that access to the cluster has been revoked. I don't want to shoehorn this through an error detail, so will take a look at migrating Error to use EncodedError.

**Comment by tbg** [comment]
Started cleaning up around Error a little bit (https://github.com/cockroachdb/cockroach/pull/56581), though haven't touched this issue yet. Planning on doing so tomorrow.
