### ISSUE TITLE
sql: add jsonb_exists_any operator

### ISSUE THREAD

**Issue by z0mb1ek** [cockroachdb/cockroach#54941]
`jsonb_exists_any` is a builtin function that does the same thing as `?|` in Postgres. See the documentation here: https://www.postgresql.org/docs/current/functions-json.html

**Comment by adzimzf** [comment]
Hi, I'd like to work with this.

**Comment by DeathWofl** [comment]
Hi, you could describe it better

**Comment by palcodes** [comment]
Hey, if the issue can be elaborated upon, I'd like to contribute.
Seems like need to add a SQL ANY operator for jsonb, but considering it's a big project, would love more description. 
@jordanlewis @yuzefovich

**Comment by yuzefovich** [comment]
I'll assign the issue to @adzimzf since he asked to work on it first and seems to be making progress based on the activity in `contributors` channel in [CockroachDB slack](https://cockroa.ch/slack).

**Comment by haseth** [comment]
Hey @adzimzf, I was working on it too but it is assigned to you now, I was referring to some of the links. Just check if any thing helps you. 
1. Exists Operator: 
     https://www.sqlservertutorial.net/sql-server-basics/sql-server-exists/
2. jsonb_exists_any operator:
    https://www.postgresql.org/docs/current/functions-json.html
3. Cockroach db docs has a readme’s for adding sql-functions. (It's a nice doc)
`00-sql-function.md`
