### ISSUE TITLE
backfill: tracks the fallout from introducing memory accounting to the index backfiller

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#54953]
This issue serves as a meta issue to track the fallout from adding memory accounting to the index backfiller in #54156.

**Comment by adityamaru** [comment]
Currently failing roachtests:
#54930
#54928
#54780
#54913
#54935
#54937

**Comment by yuzefovich** [comment]
I think the issue is that in #54156 we're only growing the memory account and never shrinking it even after we have written down all the entries, right?

**Comment by jordanlewis** [comment]
Yes, I agree with Yahor - we never seem to Shrink/Resize the memory accounts, so unless we Close them as soon as each chunk is finished with, we haven't gotten things quite right yet.

**Comment by adityamaru** [comment]
Fixed nad backported #55092
