### ISSUE TITLE
Is telemetry for sql.uds.reparent.database getting triggered?

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/cockroach#54958]
This [PR](https://github.com/cockroachdb/cockroach/blame/aa9a0e8b730491b620eaadcd26bcc89a636f61c3/pkg/sql/testdata/telemetry/user_defined_schemas) added telemetry for `sql.uds.reparent.database`. However, features telemetry is missing this metric.

**Comment by otan** [comment]
I think the problem is you are looking for `sql.uds.reparent.database`, but the value is `sql.uds.reparent_database`.

**Comment by vy-ton** [comment]
That's my error writing the issue. I actually searched telemetry for the sql.uds* prefix and that's when I didn't find any telemetry for reparent

**Comment by otan** [comment]
Hmm, it's definitely there. Which commands are you running to trigger it?

**Comment by solongordon** [comment]
Looks like @otan was able to verify this telemetry was there. @vy-ton would you please re-open if it's still not showing up for you?
