### ISSUE TITLE
sql,ui: Database Details does not include grants on user-defined schemas

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#54964]
The backend code to fetch database details only includes grants in the `public` schema. It should also handle user-defined schemas

See: https://github.com/cockroachdb/cockroach/blob/991893b41e254f2ea5738e4cf4c5cf712c9a4e1e/pkg/server/admin.go#L297-L304

**Comment by solongordon** [comment]
How is this reflected in the Web UI?

**Comment by rafiss** [comment]
If a user is granted permissions on a user-defined schema in a database, they will not show up on the grants page (http://localhost:8081/#/databases/grants). It is the analog to this issue: https://github.com/cockroachdb/cockroach/issues/53486

**Comment by otan** [comment]
> If a user is granted permissions on a user-defined schema in a database, they will not show up on the grants page (http://localhost:8081/#/databases/grants)

wonder if this is intentional as "database grants" supposedly means "grants on the database" as opposed to "grants on each table". In the case here, we're returning the correct thing as public schema inherits from the database.
