### ISSUE TITLE
sql: crdb_internal.tables always shows schema_name of `public`

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#54976]
```
root@:26257/defaultdb> create schema my_schema;
CREATE SCHEMA

Time: 150ms total (execution 49ms / network 101ms)

root@:26257/defaultdb> create table my_schema.tab(a int primary key);
CREATE TABLE

Time: 120ms total (execution 55ms / network 65ms)

root@:26257/defaultdb> select * from [show tables] where table_name = 'tab';
  schema_name | table_name | type  | estimated_row_count
--------------+------------+-------+----------------------
  my_schema   | tab        | table |                   0
(1 row)

Time: 24ms total (execution 24ms / network 0ms)

root@:26257/defaultdb> select database_name, schema_name, name from crdb_internal.tables where name = 'tab';
  database_name | schema_name | name
----------------+-------------+-------
  defaultdb     | public      | tab
(1 row)

Time: 8ms total (execution 8ms / network 0ms)
```

The `schema_name` in this case should be `my_schema`.

When fixing this, watch out for #54966 and make sure auto stats collection is working correctly.

**Comment by otan** [comment]
is this a release blocker, cc @solongordon ?

**Comment by solongordon** [comment]
It seems that way to me too. Just to be clear, what would the consequence of not backporting this be (aside from the incorrect data in crdb_internal.tables)? Does it break stats collection?

**Comment by rafiss** [comment]
luckily stats collection wasn't broken (the query previously used by the stats collector ignores user-defined schemas, but thanks to this bug, the results included tables from all schemas). This PR fixes both the query used by the stats collector and the underlying bug in the results.
