### ISSUE TITLE
kv: introduce an out-of-band mechanism to transfer a lease between replicas

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#54971]
**Is your feature request related to a problem? Please describe.**

The need to transfer a lease for a specific range from a given node to another is frequent occurrence during support calls. If a lease is currently situated on a "bad" node, we'd like the ability to transfer it out of band. There are currently two workarounds we use to do such a thing, neither of which are particularly desirable.

- We have this [`EXPERIMENTAL_RELOCATE LEASE`](https://www.cockroachlabs.com/docs/stable/experimental-features.html#relocate-leases-and-replicas) utility, which at first glance, seems like the thing we want. Except it requires the operator to specify a SQL key contained in the range. This is pretty cumbersome to retrieve, especially during on-call. Often support has context about know bad ranges, and the corresponding range IDs, so we should have something similar to EXPERIMENTAL_RELOCATE that works using just that information.

- We have this `ALTER TABLE SCATTER` utility that scatters all leases and replicas for a given table. Like the name suggests, this is a pretty nuclear option and very disruptive to customer workloads. Yet this is what we often reach for when looking to bounce ranges around. It's also not presently documented: https://github.com/cockroachdb/docs/issues/3786.

**Describe the solution you'd like**

```sql
ALTER TABLE t RELOCATE LEASE FOR <range id> TO <store id>
```

Or the equivalent (I just pulled the grammar out of thin air). Should probably be accessible through our Advanced Debug Page as well.

**Describe alternatives you've considered**

Included above.

**Additional context**

N/A

**Comment by knz** [comment]
@tbg possibly a good starter project?

**Comment by erikgrinaker** [comment]
We should decouple this from SQL concepts entirely, e.g. by using `ALTER RANGE` instead of `ALTER TABLE`. @knz has some thoughts in https://github.com/cockroachdb/cockroach/issues/69854#issuecomment-914206209.

**Comment by irfansharif** [comment]
Imagine if we had crdb_internal style hooks that exposed access to a `*kv.DB` or the local node's `*kvserver.Store`. Then it'd be super trivial to add built-ins like this one, and possibly much more. What would it take to plumb in a kv.DB or the local store up into our existing builtins? Is there something preventing us?

**Comment by erikgrinaker** [comment]
I've been thinking the same thing, but from a slightly different angle: how easy would it be to write/generate CLI commands for all `*kv.DB` methods? Not sure if we want this in SQL or as a separate CLI -- SQL sure is convenient though.

**Comment by irfansharif** [comment]
Everything in SQL is automatically part of the CLI (`cockroach sql --insecure -e 'select crdb_internal.relocate_range(r23, s45);'`) 😛

**Comment by knz** [comment]
yes the SQL approach is the better one. We want fewer CLI commands, not more.
