### ISSUE TITLE
server: make CGO profiles accessible

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#5504]
OOM issues have moved into CGO territory.

Restarting a node with @cuongdo's change to dump mallinfo shows the following after a couple of minutes (no external activity, but the cluster does have quite a bit of data on it):
```
I160323 15:21:41.183328 server/status/runtime.go:144  runtime stats: 115 goroutines, 12.04MiB active, 84897.97cgo/sec, 0
.31/0.03 %(u/s)time, 0.00 %gc (47x)
I160323 15:21:41.183848 server/status/linuxstats.go:56  mallinfo stats: ordblks=1.6 KiB, smblks=176 B, hblks=0 B, hblkhd
=0 B, usmblks=0 B, fsmblks=10 KiB, uordblks=980 MiB, fordblks=109 MiB, keepcost=10 KiB
```

This means 12MB active in Go's heap, and 980MB allocated in the main C arena.
The standard heap profile shows nothing, so we're left mostly blind. We need to add the ability to grab and dump C profiles.

**Comment by cuongdo** [comment]
Do any of the RocksDB graphs show anything weird? Specifically, the "block cache size" graph.

Also, do any of the byte values from this command look large enough to significantly contribute to that 980 MB?

`curl -s http://NODE:PORT/_status/metrics/NODEID | grep rocksdb | egrep 'usage|total-size'`

**Comment by mberhault** [comment]
metrics dump for node 1:
```
  "stores": {
    "1": {
      "capacity": 31564754944,
      "capacity.available": 22189780992,
      "gcbytesage": 20190270937448,
      "intentage": 525638031,
      "intentbytes": 1583418,
      "intentcount": 10284,
      "keybytes": 452738865,
      "keycount": 9353046,
      "lastupdatenanos": 1458748113822151114,
      "livebytes": 1268754940,
      "livecount": 8827213,
      "ranges.available": 0,
      "ranges.leader": 1,
      "ranges.replicated": 1,
      "replicas": 41,
      "rocksdb.block.cache.hits": 8312534,
      "rocksdb.block.cache.misses": 622755,
      "rocksdb.block.cache.pinned-usage": 0,
      "rocksdb.block.cache.usage": 1367402884,
      "rocksdb.bloom.filter.prefix.checked": 591637,
      "rocksdb.bloom.filter.prefix.useful": 152915,
      "rocksdb.compactions": 2,
      "rocksdb.flushes": 1,
      "rocksdb.memtable.hits": 0,
      "rocksdb.memtable.misses": 0,
      "rocksdb.memtable.total-size": 246027071,
      "rocksdb.table-readers-mem-estimate": 88665480,
      "sysbytes": 65316510,
      "syscount": 683456,
      "valbytes": 1248032045,
      "valcount": 13362415
    }
  }
```

btw: these are reachable at https://beta.cockroachdb.com:8080/

**Comment by mberhault** [comment]
and a recent log line:
```
I160323 15:49:41.191033 server/status/runtime.go:144  runtime stats: 263 goroutines, 39.58MiB active, 161820.24cgo/sec, 0.81/0.01 %(u/s)time, 0.00 %gc (18x)
I160323 15:49:41.193392 server/status/linuxstats.go:56  mallinfo stats: ordblks=19 KiB, smblks=176 B, hblks=0 B, hblkhd=0 B, usmblks=0 B, fsmblks=9.8 KiB, uordblks=1.7 GiB, fordblks=82 MiB, keepcost=9.8 KiB
```

**Comment by cuongdo** [comment]
The RocksDB stats show that 1.27 GiB is being used for the block cache. That's by far the biggest culprit in RocksDB-land. Poking around around RocksDB wrapper to see if I can spot a culprit.

**Comment by cuongdo** [comment]
Our RocksDB wrapper allows RocksDB to use 8 GiB for its block cache, so this (1.27 GiB) is well within that limit. However, it is surprising that we use that much memory with no external activity. Are there range splits, etc. happening?

**Comment by tschottdorf** [comment]
We allow 8 gigs? That's at or above what the node has available. That would
explain why it'd just OOM after a while, right?

**Comment by cuongdo** [comment]
That's on my dev machine, which has 16 GB of memory.

By default, if no "--cache" parameter is specified, we use 1/2 of the total
server memory for the RocksDB block cache. The code is here:

https://github.com/cockroachdb/cockroach/blob/master/cli/start.go#L99

**Comment by mberhault** [comment]
running at v=3 on the aws machines, the rocksdb preamble shows:
`  block_cache_size: 3921668096`

**Comment by tschottdorf** [comment]
That does look like half the memory.

**Comment by mberhault** [comment]
uh. that doesn't seem right:
```
I160323 18:27:21.112587 server/status/linuxstats.go:56  mallinfo stats: ordblks=6.8 KiB, smblks=166 B, hblks=0 B, hblkhd=0 B, usmblks=0 B, fsmblks=9.0 KiB, uordblks=16 EiB, fordblks=112 MiB, keepcost=9.0 KiB
```

I don't think we're using 16 exabytes though, most likely a uint64 overflow/cast problem somewhere.

**Comment by mberhault** [comment]
yup: loops like we overflowed int32:
```
I160323 17:21:31.149404 server/status/linuxstats.go:56  mallinfo stats: ordblks=6.2 KiB, smblks=147 B, hblks=0 B, hblkhd
=0 B, usmblks=0 B, fsmblks=7.3 KiB, uordblks=2.0 GiB, fordblks=84 MiB, keepcost=7.3 KiB
I160323 17:21:41.113270 server/status/linuxstats.go:56  mallinfo stats: ordblks=6.5 KiB, smblks=138 B, hblks=0 B, hblkhd=0 B, usmblks=0 B, fsmblks=6.8 KiB, uordblks=16 EiB, fordblks=84 MiB, keepcost=6.8 KiB
I160323 17:21:51.112766 server/status/linuxstats.go:56  mallinfo stats: ordblks=6.5 KiB, smblks=118 B, hblks=0 B, hblkhd=0 B, usmblks=0 B, fsmblks=5.7 KiB, uordblks=16 EiB, fordblks=84 MiB, keepcost=5.7 KiB
```

**Comment by cuongdo** [comment]
Yes, mallinfo is not 64-bit safe. Doh!

**Comment by mberhault** [comment]
yup. and there doesn't seem to be a good replacement. I've seen people recommend we use `malloc_stats`, but all that does it print GCC memory stats to stderr.

**Comment by cuongdo** [comment]
malloc__info seems to be the way to go. That prints XML to a stream, which
can then be parsed. Would that be helpful?

**Comment by bdarnell** [comment]
We now report RSS instead of `mallinfo` or `malloc_info`. We have some experimental work using `jemalloc` which gets us more detail but I'm not sure if we're ready to merge that in. Is there anything else to do here or can this issue be closed?

**Comment by mberhault** [comment]
I think that's about it for now. I don't feel particularly confident using jemalloc by default, but we know we can built with it if need be. I'll close this for now.
