### ISSUE TITLE
sql: GRANT PRIVILEGES doesn't exactly match Postgres syntax

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#55049]
**Syntax of GRANT PRIVILEGES doesn't allow PRIVILEGES keyword **

Postgres allows statements of the form [GRANT ALL **PRIVILEGES**](https://www.postgresql.org/docs/8.3/sql-grant.html) ..., wheres CRDB only supports [GRANT ALL](https://www.cockroachlabs.com/docs/stable/grant.html) ...

This issue should add the ability to optionally specify the PRIVILEGES keyword.

**Comment by lober-io** [comment]
The same occurs at [REVOKE](https://www.postgresql.org/docs/9.1/sql-revoke.html)

**Comment by ajwerner** [comment]
See https://github.com/cockroachdb/cockroach/issues/16790 which captures this problem and more.

**Comment by ajwerner** [comment]
This captures the work item discussed under `Glob patterns vs explicit statements` in https://github.com/cockroachdb/cockroach/issues/16790#issuecomment-661843232.
