### ISSUE TITLE
telemetry: add telemetry to measure time to first client connection

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#55059]
We currently have no optics into the time-to-first-connection for a given cluster. 

The product team wants to measure the time between the moment a cluster is created and the moment at which a user successfully connects to that cluster for the first time.

This telemetry will help us fill in the gap in our understanding of the user funnel from cluster creation to first cluster connection to first query.

cc @knz as we discussed offline

**Comment by knz** [comment]
@thtruo is there telemetry for first query already?

This issue is about adding telemetry to 1st connection, but if that connection is idle that won't tell us much.

**Comment by thtruo** [comment]
Yes, I believe there is telemetry for first query already cc @emily-horing 

> This issue is about adding telemetry to 1st connection, but if that connection is idle that won't tell us much.
While the first connection was the primary motivator for this request, I'd generalize it and say we should be able to query for whenever a cluster has connected at all. We're currently blind to connections made to clusters, and don't know what's happening between a cluster being created and a query being run. And we don't know how soon or late a customer is connecting to their cluster (is it within a day, a week, etc?).  Even if a connection were idle, the fact that nothing else happened afterwards is telling - is there UX friction blocking them from moving forward, something else?

**Comment by emily-horing** [comment]
Just to clarify @thtruo you want to know what time the connection opened? As in we assume there is a potentially significant time difference between the first query and the connection starting?

**Comment by knz** [comment]
From the engineer perspective, I want to know exactly what is the problem to solve, what telemetry has already been implemented in the past in this area (I don't actually know) and what is missing from what is already implemented.

**Comment by thtruo** [comment]
My mental model - I like to simplify this into a broad funnel. A user in CockroachCloud will: 
1. Create a cluster
2. Connect to said cluster
3. Issue a query after connection

The problem is that we have no optics into step 2 today, which means we don't have a good way to diagnose where the funnel breaks down for our customers. We are unable to query across the board to understand the rate at which customers are able to connect to their clusters. While this ask was originally motivated by the need to understand _CockroachCloud_ customer engagement, this applies to the self-hosted side as well.

Outside of emitting connections and auth sessions in authentication logs (https://github.com/cockroachdb/cockroach/pull/45193), I'm not aware of any connection tracking happening in our TELEMETRY tables.   

My proposal is that we track a set of connection events such that we can answer the following:
- What cluster was connected to?
- When was that connection made?
- When did that connection end?
- Which SQL user or IP address was used to connect to a particular cluster (there's a PII concern here, could we just rely on using a UUID for a given SQL user or IP address)?
- Which connection parameter was used (e.g. sslmode is disable, allow, prefer, require, disable, verify-ca, or verify-full)?

Thoughts @knz? 

Re your question @emily-horing 
> Just to clarify @thtruo you want to know what time the connection opened? As in we assume there is a potentially significant time difference between the first query and the connection starting?

Yep, I'd like to know the time a connection was opened. I honestly don't know if there is a significant time difference between first query and the starting connection, but that's why measuring that will help us know for sure!

**Comment by knz** [comment]
I am removing this issue from the server/cli project and adding it to the Telemetry project.
It's unclear what needs to be achieved exactly and even moreso how to achieve it.

**Comment by thtruo** [comment]
Closing given this is stale and that the security-related key result has already been modified in its latest reincarnation
