### ISSUE TITLE
acceptance: refactor chaos test

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#5506]
- split the chaos test into the collection of smaller tests that it 
- refactor the bank load into load.go and use the dynamic client
- refactor the chaos monkey that restarts into a chaos agent

**Comment by spencerkimball** [comment]
@BramGruneir should this be closed, similar to #4559?

**Comment by petermattis** [comment]
Closing this as I don't anticipate significant additions to the current chaos acceptance test.
