### ISSUE TITLE
sql: Add global REASSIGN OWNED BY functionality

### ISSUE THREAD

**Issue by angelapwen** [cockroachdb/cockroach#55079]
**Is your feature request related to a problem? Please describe.**
Postgres implements the REASSIGN OWNED BY command per database, reassigning ownership of database objects within only the current database from 1 to many old roles to a new role. Generally the purpose of this command is to prepare to DROP the old role(s) immediately afterwards. 

We expect that it would be more convenient and useful to our users to be able to reassign ownership across all databases, considering we have the mechanism to do so easily. To maintain Postgres compatibility we have implemented REASSIGN OWNED BY for just the current database (#54594) but would like to introduce the opportunity to reassign across all databases. 

**Describe the solution you'd like**
Perhaps a GLOBAL keyword to indicate that descriptors from all databases, not just the current one, should be surfaced.

Jira issue: CRDB-3697

**Comment by ajwerner** [comment]
@rafiss, unlike the drops which we've got fully implemented in the declarative schema changer and feel some expertise around, ownership and privileges have been an area of split responsibility. I'm going to put this in the backlog for Schema. If that doesn't align with product goals, we'll have to figure something out.

**Comment by ajwerner** [comment]
The catalog pieces do definitely line up though

**Comment by rafiss** [comment]
That sounds fine. Whereas DROP OWNED BY has been requested a few times, this "global REASSIGN OWNED BY" issue has not, and was just added to this epic opportunistically. We already have normal REASSIGN OWNED BY in pkg/sql/reassign_owned_by.go
