### ISSUE TITLE
kv: (*Replica).mu.desc has unclear semantics

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5509]
`r.Desc()` returns `r.mu.desc`, which means that even when holding the lock, `*dest` must never be modified (the only allowed operation is `r.mu.desc = newDesc` under lock).

This isn't clear at all from looking at the `mu` struct.

**Comment by RaduBerinde** [comment]
@tschottdorf, does this boil down to just documenting this in the `mu` struct definition?

**Comment by tschottdorf** [comment]
I suppose so, though the pattern is fragile. If I have a field inside a
`mu` and I hold the write lock, I don't expect to have to know anything
more about the semantics of the contained fields.

**Comment by RaduBerinde** [comment]
The alternative is to return a copy and/or add more specialized functionality based on what the callers need it for.

But even then, you still need to know the semantics of the fields (even if you have the write lock).. E.g. it looks like at least for some updates of `desc`, `processRangeDescriptorUpdateLocked` needs to run and the pattern here seems to be to go through `setDesc*` functions.
