### ISSUE TITLE
storage: support backups

### ISSUE THREAD

**Issue by treeder** [cockroachdb/cockroach#551]
Has this been hashed out yet?

**Comment by spencerkimball** [comment]
Not yet. But it's on our roadmap for Q3 of this year.

**Comment by karthik-gorthi** [comment]
It would be ideal if the backups output is SQL. That'll leave a good rollback option, back to Postgres/MySQL. 

We're waiting for this feature to push one of our less critical system onto cockroach.

**Comment by dianasaur323** [comment]
@treeder @karthikg001 check out our current implementation of backup / restore here https://www.cockroachlabs.com/docs/back-up-and-restore-data.html 

You can dump multiple tables at the same time. Closing this issue!

**Comment by tlvenn** [comment]
Well you can even dump an entire database, something which was not obvious from your comment or from the release note itself, which is far more valuable than multiple tables ;)

**Comment by dianasaur323** [comment]
Awesome! We like exceeding expectations :)
