### ISSUE TITLE
debug: add capability to "force" a load-based split

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#55116]
**Is your feature request related to a problem? Please describe.**
When a user has a range that they wish to split to better distribute load (for example during a crisis situation), but load-based splitting does not do the job, the user has to manually construct a split key for use with `ALTER TABLE ... SPLIT`.

**Describe the solution you'd like**
Either via the UI or SQL, "force" a load-based split, meaning that the range will split based on the leader's best guess.

**Describe alternatives you've considered**
An alternative is to set the cluster setting that controls load-based split aggressiveness. However, this is a highly non-local solution that may cause many unrelated and possibly detrimental splits.

Jira issue: CRDB-3693

**Comment by lunevalex** [comment]
@tbg  I was thinking about the proposal and based on my observations from #72305 I think the best option would be to extend the `ALTER RANGE` syntax to support this, I think we can offer the following syntax to meet the proposed use cases `ALTER RANGE 10 SPLIT` and `ALTER RANGE SPLIT FOR (SELECT range_id from crdb_internal_ranges where table_name = 'foo'`

**Comment by ajwerner** [comment]
A different approach to this problem is to move the thresholds for load-based splitting into zone/span configs. That's not to take anything away from the more precise statements @lunevalex is proposing. Both seem valuable. Increasingly, I think more and more KV allocator decisions should be configured on a per-span basis.
