### ISSUE TITLE
kvserver: distributed tenant cost control

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#55115]
**Is your feature request related to a problem? Please describe.**
Tenant rate limits are currently per-node. They should be per-cluster.

**Describe the solution you'd like**
Tenants should have a quota (replenishing at a set rate) that they can spend on reads or writes via compute units (see #55114).
Assuming we are happy with the solution outlined in #55114 mod the fact that it is non-distributed, we can make the `tokenBucket` mentioned there *distributed*, meaning that nodes acquire a buffer of compute units from a replicated location as indicated by their local spend.

There are multiple questions here.

1. where to store the distributed token? The obvious first place to look is `system.tenants`, but it's a bad choice due to the high frequency of updates and the need to avoid a cluster-wide hotspot. Instead, it seems better to have a per-tenant replicated key that lives in the tenant's keyspace (but can not be mutated by the tenant, which we can enforce easily as long as the key is hard-coded).
2. how to store the distributed token. A token bucket is roughly a number of tokens, a rate at which it replenishes, a bucket size (i.e. the max number of tokens it can hold) and the timestamp at which it was last updated (i.e. the timestamp to which the number of currently available tokens corresponds). The rate and max bucket size are presumably global cluster settings, so they don't need to be stored. This leaves the number of tokens and timestamp to be stored. This is straightforward (as a proto), though a read-modify-write cycle would be necessary to update them naively, which behaves poorly under contention. FOR UPDATE locks might be enough to avoid this, though keeping acquisition latency to a minimum seems very important as well. So, we may find the need to introduce a custom KV operation (similar to a souped up `Increment`) that allows us to acquire quota in a single replicated round-trip.
3. When to acquire tokens. In the simplest (but impractical) model, a node acquires tokens when they're needed, meaning that each client request will have to wait for the distributed acquisition. This is obviously a non-starter. Instead, each node (that has ranges for a tenant) should, in idle state, have a small amount of quota available, enough to serve occasional small requests. There are various ways in which we could achieve this. The most idiomatic has each node acquire this quota from the distributed pool, and release it when the tenant's ranges move elsewhere. We could also consider holding the quota "locally" without acquiring it, and requesting it from the pool only when it is used up. This may push the token bucket into negative territory (which means no more quota will be handed out until the bucket is in the green again). This second option could perform better because a) it allows us to use a much bigger burst, and thus hopefully better UX, and b) negative tokens are already used for the bursts in today's non-distributed rate limiters, so this may not require new concepts internally, and c) it means less traffic on the distributed bucket. A slight negative, the main point of distrbuted limits is to control spend. We could be overspending slightly in one time interval and as a result force an underspend in the next time interval to break even (while recovering from negative buckets). I don't think this is a real concern given sensibly chosen values, but still worth pointing out.
4. How many tokens to acquire. I think the answer here is simple: measuring the current consumption and requesting tokens that should last ~N seconds at the current rate of consumption.
5. When to release unused tokens. Same answer as above. When the (suitably averaged) consumption indicates that we won't use the tokens within, say, `2N` (same N as before), release quota so that the new quota held corresponds to that in 4) for the new, lower, average. 4) and 5) are likely to be expressable as one and the same computation.

**Describe alternatives you've considered**
Alternatives were discussed in an internal document but to the best of my knowledge all participants are now in favor of some variation of the above proposal.

**Additional context**
One goal (possibly *the* goal) we're solving here is cost control. A tenant should be able to configure the cluster to not spend more than x compute units per time interval on KV requests.

Epic CC-2908

**Comment by tbg** [comment]
cc @andy-kimball @ajwerner @nvanbenschoten for thoughts

**Comment by tbg** [comment]
Another approach is motivated by https://github.com/cockroachdb/cockroach/issues/55114#issuecomment-759295662. Essentially, part of the reason why the KV layer does this rate limiting is currently that it also protects the KV layer from a rogue tenant. If we assume that we have a solid admission control mechanism in place in the KV layer instead (our current tenant rate limiting could double as that, if we loosen the limits somewhat), this motivation goes away and we can consider a design in which the rate limiting occurs on the SQL gateways and is only mediated by the KV layer. Roughly this could work as follows:

1. we have a replenishing quota bucket in a replicated per-tenant key (like in the above proposal) that the SQL tenants can access
2. when a SQL node starts up, it acquires a small initial amount of quota
3. for each request sent, the SQL gateway deducts the approximate quota used for the request (caveats below)
4. responses contain the actual quota spent, which is then taken into account
5. the gateway replenishes (and releases) quota using the KV endpoint as necessary for the current levels of spend
6. the gateway will not block on quota for internal operations that are necessary for its basic functions or which it knows will release data. ("deletes are free"). These simply put the bucket in the red if need be.
7. billing remains driven by the kv metrics, not the tenant's view of usage. That is, a rogue tenant will be able to violate their own set rate limit, but all that means is that they will spend more money than they configured.

The more I think about it, the more the approach seems right. Letting SQL do the limiting is more powerful since SQL can pick the statements it wants to put first in the queue when it runs out of quota, and it also knows better which operations are essential to its inner workings (KV has to bend over backwards to find out). Plus, this naturally leads to cost awareness in SQL, which can be exposed to users via traces; statement pages; analyze statements.

The above approach has some parallels to [breakwater](https://www.usenix.org/system/files/osdi20-cho.pdf) (h/t @ajwerner) in that "clients" (sql tenants) need explicit permission from the "server" (kv layer) to send requests. It is different in that we have the luxury of a predefined rate limit (since we're not doing overload protection here, but spend control). Another difference is that we use a pull model (sql pulls quota from KV based on its expected usage) whereas breakwater would put that on the KV side (the breakwater paper targets us-scale RPCs which it assumes are uniform in cost).

Caveats and notes:

The quota for a request is not necessarily known upfront. We [currently use](https://github.com/cockroachdb/cockroach/blob/4c9110f7040b1d911e5d02760fe7ceacc24413ca/pkg/kv/kvserver/tenantrate/limiter.go#L24-L66)

- bytes written
- bytes read 
- number of read requests
- number of write requests

"bytes read" is not known upfront and the way we handle this is to assume it is 1 when we admit the request, but then when the response comes in we add the rest (which may well put the limiter in debt). This means the system is not perfect, but this seems fine - an individual read is unlikely to provide a large enough aberration from the cost target to matter, and we can always undercharge. The steps above lead to the same behavior in the SQL-side design.

The second, bigger, caveat is that we want to maintain performance while running right at the limit. Transactions that consist of multiple statements in that setting are likely to get caught up on the rate limiter and intents that they already laid down may cause severe contention:

- txn1 inserts `row1`
- txn2 inserts `row2`
- txn2 tries to read `row1`, blocks on txn1
- txn1 tries to write `row3`, gets blocked on the quota pool for some time
- txn2 blocks for far longer than user expects

It's thus advisable to not block transactions that already have laid down an intent on the quota acquisition. Instead, they are allowed to acquire more quota (driving the local bucket deeper into the red; we may need some special rules here for long-running txns which should probably get cancelled before they cost too much), and blocking new txns from beginning (or read-only txns from commencing). These considerations go back to @ajwerner in the context of admission control.

The token bucket (in KV) itself should have sane semantics. It starts out empty and replenishes at the rate that corresponds to spending at most $100 an hour. It tops out at $100, and whatever is in there the tenant can spend. In the sketch below, a $100/hour limit is configured. The solid line is an idle state - the bucket fills up, and stays full. The squiggly line has a constant homogeneous workload that stays well below the $100/hour target, so the bucket fills up (slower) but then stays close to full.
The dashed line starts out with the tenant trying to exceed their limits (perhaps they're overwhelmed and just put the limit into place as a safeguard). The quota bucket hovers near empty. 90 minutes in though, the load drops to zero and the bucket fills up completely. A little later, the load continues and the bucket quickly gets depleted, at which point the workload becomes throttled again towards the $100/hour target. (The dashed workload would cost $100/hour).

![image](https://user-images.githubusercontent.com/5076964/104436417-dc515700-558d-11eb-9a0d-3800a5e68b6e.png)

I think we'd store the bucket size (corresponds to max spend) in `system.tenants` (gossiped) and the individual kv pair per tenant `/Tenant/N/Allowance` roughly is a `var allowance struct { lastUpdatedSeconds int64, available int32 }` and requests to it supply a `var req struct{nowSeconds int64, requested int64}` and will basically result in `allowance.available += max(allowance.lastUpdatedSeconds.Sub(req.nowSeconds), 0)*quota_per_second - req.requested` (mod handling of negative results, etc, where we'll return the quota we have and tell the caller when to retry, etc).

Clearly when running at the limit, service will not be as good as it would be without rate limiting, but that is hard to avoid. At least, with the limiter living in the SQL layer, SQL can pick which transactions to allow and it could in principle do so based on a user-supplied priority, or based on past cost, or past frequency.

Another upshot of the SQL-side model is that the SQL layer gets to see the cost of queries "by design", meaning that it can be exposed to users as part of traces or explain statements. (This could be achieved in different ways too, but it's easier this way). In particular, since the optimizer can, in principle, reason about the expected size of results, it should be able to approximate a ($) cost without actually running the query.

**Comment by ajwerner** [comment]
> it should be able to approximate a ($) cost without actually running the query. 

This isn't a hard and fast rule. Users issuing different queries in an interactive session may prove very challenging for the optimizer. Also, the cost model in the optimizer is not generally something that intentionally maps to usable units IIUC. My sense is that when it comes to billing for KV usage, we'll want to collect that information from the KV layer. However, I am totally on board with the idea that decision making about how to do rate limiting should occur in the SQL layer. Otherwise we'll leave requests hanging around and generally waste work. Perhaps the kv proxy can deal with interacting with the rate limiting infrastructure on behalf of the tenant SQL layer and merely pass information back up to it.

**Comment by tbg** [comment]
Yes, I wasn't suggesting that this would be used for anything authoritative. It seemed like a nice little trick for informational purposes if users could make a query plan, and from the indexes and spans read in them + statistics we could give them an idea of what the spend could be. But Andy already let me know that we could be wildly off here, and I don't think this functionality is at all important. I do point out that billing is always done from KV data (see 7 above).

> Perhaps the kv proxy can deal with interacting with the rate limiting infrastructure on behalf of the tenant SQL layer and merely pass information back up to it.

I was thinking that the kv client (on the sql server) has a quota component (which for tenants we would set up to draw quota from the distributed bucket k/v pair for the tenant) and it is thus mostly transparent to the SQL server, though the SQL server can look at the component to make decisions. That way, at a first approximation, we're not "polluting" SQL with this rate limiting but it is there whenever the moment comes at which SQL wants to do any fancy decision making.

**Comment by sumeerbhola** [comment]
I'm having a hard time teasing apart design ideas from requirements etc. in the discussion here and in its companion issue. 
I think it is important to separate (a) system self-protection and (b) customer metering and customer requested cost controls.

(b) is conceptually centralized for each customer, and the aggregate cost controls across all customers may far exceed the system capacity. Additionally, our actual system is distributed and we need to protect individual nodes from hotspots (as part of (a)) which may not be the fault of any customer. Customer billing typically also requires durable recording of events (typically logs) that caused those costs to be incurred, and may be disputed if such records are not kept. For instance, we may not be able to charge for queries that didn't actually complete, or completed with an unacceptable latency, for no fault of the customer, say because the system was protecting itself. So decrementing customer tokens at the KV layer without any record of which query caused those decrements is probably insufficient (those costs could be aggregated at the SQL layer and logged periodically, and at query completion time, so we could charge for an expensive query that did not complete, and all queries that did complete). These logs typically get batch processed for billing. Cost controls need realtime enforcement, and as long as they are an upper bound on the actual bill, should be done in a lightweight manner. Token buckets, as outlined above seem fine, though I'm wary of involving database reads/writes to update tokens.

System self protection (a), on the other hand, needs to work in a very light weight distributed manner and not degrade if the system is overloaded. So I don't think it should be relying on doing read/writes to a database. Also, I'm not sure of the value of customer quotas in this space other than as gross abuse prevention -- if we have capacity, and a customer is under their cost controls, we should serve them and charge them.

**Comment by tbg** [comment]
I think the current thinking is fairly aligned with what you are saying. Apologies that the issue didn't make it clearer, I was mostly focused on the cost control aspect here.

Protecting the system must be lightweight and in particular should not use any distributed bucket. As first pass, we are considering a per-KV-node rate limiter that has to be configured manually (not an issue when we host the deployment) and a per-SQL instance rate limiter that relies on signals from subsystems (such as KV, CPU, etc) to decide when to queue incoming statements. Metering, based on the distributed bucket (with appropriate prefetching of quota, etc) would provide another signal to this mechanism. The goal for the KV limiter is to not kick in under regular circumstances, as queuing at the KV layer exacerbates contention and so is likely to break SLAs.

> For instance, we may not be able to charge for queries that didn't actually complete, or completed with an unacceptable latency, for no fault of the customer, say because the system was protecting itself. 

That's an interesting thought. My intuition had been to let the KV layer's metrics drive the billing is we must always expect a customer to gain control of one of their SQL pods which would then allow them to manipulate billing. But that may be a lesser concern. It seems desirable in principle to exclude queries which don't conform with an SLA to be discounted or exempted from billing. I think in practice we have our architecture doesn't constrain us much - we likely will include the consumption from the KV layer to the SQL layer in responses anyway (as an admission control signal), so we can decide to drive billing from SQL or KV or a combination of both anyway.

> Also, I'm not sure of the value of customer quotas in this space other than as gross abuse prevention -- if we have capacity, and a customer is under their cost controls, we should serve them and charge them.

I'm not sure I understand this comment correctly, but just to confirm, it is the intention that customers can go "fast" as long as they have money available. The intention is not to throttle them throughout, this would only happen as they approach their cost control, whence traffic would be slowed down to match the desired cost rate.

**Comment by ajwerner** [comment]
Why is this assigned to @jordanlewis? @RaduBerinde this feels like it's yours and that you're close to closing it. Maybe we just mark it as having been subsumed by https://github.com/cockroachdb/cockroach/pull/66436 and friends?

**Comment by RaduBerinde** [comment]
Right, closing. The tasklist for remaining items for tenant cost control is in #68479.
