### ISSUE TITLE
Recent change to add owners to various SHOW commands should be reflected in the docs

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#55122]
Issue #53566 added owner information to various SHOW commands (DATABASES, TABLES, SCHEMAS, ENUMS).  This change should be reflected in the docs wherever we're showing sample output from one of these commands.  For example, the following places would need to be updated (not an exhaustive list):

https://www.cockroachlabs.com/docs/stable/show-databases.html
https://www.cockroachlabs.com/docs/v20.1/show-tables.html
https://www.cockroachlabs.com/docs/v20.1/show-schemas.html
https://www.cockroachlabs.com/docs/v20.2/show-enums.html

**Comment by otan** [comment]
docs should automatically pick this up from the release notes you have provided. this gets automatically filed in the docs repo.

**Comment by ajstorm** [comment]
Interesting.  I'll close this one.
