### ISSUE TITLE
sql: INT(n) and BIT(n) not implemented properly

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#5514]
@bdarnell tells me that `INT(5)` is supposed to be a 5-digit number (up to 99999), while `BIT(5)` is a 5-bit number (up to 31). 

But when you define a column as `BIT(n)`, it gets converted to `INT(n)` and then the length limit is not enforced. For example:

```
root@:26257> create table bits (a bit(5), b bit, c int);
CREATE TABLE
root@:26257> show columns from bits;
+-------+--------+-------+----------------+
| Field |  Type  | Null  |    Default     |
+-------+--------+-------+----------------+
| a     | INT(5) | true  | NULL           |
| b     | INT    | true  | NULL           |
| c     | INT    | true  | NULL           |
| rowid | INT    | false | unique_rowid() |
+-------+--------+-------+----------------+
root@:26257> insert into bits values (123456, 1, 2);
INSERT 1
root@:26257> select * from bits;
+--------+---+---+
|   a    | b | c |
+--------+---+---+
| 123456 | 1 | 2 |
+--------+---+---+
```

**Comment by JackKrupansky** [comment]
There is no INT(5) or INTEGER(5) at the SQL level - it's DEC(5), DECIMAL(5), NUM(5) or NUMERIC(5), or just INT, INTEGER, SMALLINT, BIGINT, or INT64, all of which are 64-bit signed integers.

But, yes, BIT(n) is the same as BIT(64) and is simply a synonym for INTEGER, which is a signed 64-bit integer.

Whether BIT remains partially implemented as an integer as it is today is an open question.

**Comment by bdarnell** [comment]
Mysql supports `INT(5)`, but it is only used for display and not to control what values can be stored: http://dev.mysql.com/doc/refman/5.5/en/numeric-type-attributes.html

If this mysql extension is the only place where `INT(n)` is used then we probably shouldn't support it either.

**Comment by knz** [comment]
We've restricted this for a while now:
```
root@:26257> insert into bits values (123456, 1, 2);
pq: bit string too long for type BIT(5) (column "a")
```

@jseldess can you check whether the problem has been adequately addressed and perhaps close the issue?

**Comment by jseldess** [comment]
Yep, looks good now.

**Comment by jseldess** [comment]
Found one minor residual `bit` issue, @knz: https://github.com/cockroachdb/cockroach/issues/13791
