### ISSUE TITLE
storage: used capacity is 0 B

### ISSUE THREAD

**Issue by heidawei** [cockroachdb/cockroach#55151]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

One cluster has five nodes, and I add five nodes, then decommissioning the original five nodes，I see:

![image](https://user-images.githubusercontent.com/11207613/94885647-56f4db80-04a3-11eb-87d6-9b7c2efa52f4.png)

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
2. Send SQL ... / CLI command ...
3. Look at UI / log file / client app ...

**Expected behavior**

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version [e.g. 2.0.x]
   V19.2.4
 - Server OS: [e.g. Linux/Distrib]
   Centos 7.6
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
What was the impact?

**Comment by heidawei** [comment]
I found the cause of the problem. The problem is that the specified store path when starting cockroach is a soft link, which causes logic problems when filepath walk. The simplest way to fix this problem is to end the store path with a '/' or make additional checks in the code like this:
![image](https://user-images.githubusercontent.com/11207613/94896884-1b690a00-04c1-11eb-8d9f-f0070d05540c.png)

**Comment by petermattis** [comment]
@heidawei Thanks for the report and tracking down where the problem lies. I think `filepath.EvalSymlinks` could also fix this issue. Care to send a PR?

**Comment by heidawei** [comment]
@petermattis ` filepath.EvalSymlinks `is better. I send my first PR for cockroach.
