### ISSUE TITLE
tests: jepsen-test linearizabile monotonic timestamps

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#5517]
Found via this Jepsen test: http://jepsen.cockroachdb.com/cgi-bin/display.py?entry=20160323T194931#20160323T194931

The problem: despite the database running linearizable, there is one anomalous ordering observed at the end of the test.

The test creates two tables table1 / table2 both with schema `(v INT, ts TIMESTAMP, id INT)` and performs the following transaction repeatedly from different clients:

```
    mu.Lock()  -- local lock to ensure atomicity around the shared counter
    v := global_counter++
    X := randint(2)
    BEGIN
        INSERT INTO 'table'+X  VALUES (v, NOW(), clientID)
    END
    mu.Unlock()
```

Meanwhile, a nemesis randomly causes network partitions and time skews of +/- 100ms.

(The detailed implementation is to be found here: https://github.com/knz/jepsen/blob/e5f96e2a81b6ecb429e953432df552dacfd7611e/cockroachdb/src/jepsen/cockroach.clj#L783-L939 )

At the end we expect `v` and `ts` to evolve in the same order irrespective of clientID when the db is linearizable, and the test's results suggest this is not so in practice.

Noteworthy, the anomaly is not (yet?) detected without the nemesis, other nemeses or "simpler" nemeses that only use clock skews or network partitions.

**Comment by aphyr** [comment]
This result might be spurious: a client mutex does not ensure the *database* applies the updates emitted at the same time. Consider clients A and B:

A locks
A sends `1`
A times out
A unlocks
B locks
B sends `2`
DB processes 2
DB processes 1

**Comment by spencerkimball** [comment]
The linearizable mode is somewhat fanciful at this point and not intended for use. It's enabled by an undocumented environment variable and has no documentation. I'm removing the 1.0 milestone for this.
