### ISSUE TITLE
ui: endless error loop with "databases" tab on a just-initialized instance

### ISSUE THREAD

**Issue by bshi** [cockroachdb/cockroach#5520]
![screen shot 2016-03-23 at 2 15 13 pm](https://cloud.githubusercontent.com/assets/15159/14001365/a5e14058-f102-11e5-8872-f83888f2cfde.png)

**Comment by cuongdo** [comment]
I can't reproduce this. Could you give me the exact steps need for me to
reproduce this, such as any command-lines you used to start CockroachDB?

**Comment by bshi** [comment]
Sorry about the oversight:

```
$ git show
commit 88909f50e21d533b99a4fc62b8480d39ca80d3bf
Merge: c209e40 9162ff9
Author: Tobias Schottdorf <tobias.schottdorf@gmail.com>
Date:   Wed Mar 23 16:11:13 2016 -0400

    Merge pull request #5510 from tschottdorf/splitkey

    mvcc: always fail when SplitKey = StartKey

$ make build

...

$ ./cockroach cert create-ca --ca-cert ca.cert --ca-key ca.key
$ ls -l ca.*
-rw-r--r--  1 bo  staff  1111 Mar 23 13:47 ca.cert
-rw-------  1 bo  staff  1679 Mar 23 13:47 ca.key

$ ./cockroach cert create-node --ca-cert ca.cert --ca-key ca.key --cert node.cert --key node.key 127.0.0.1 ::1 localhost
$ ls -l node.*
-rw-r--r--  1 bo  staff  1176 Mar 23 13:57 node.cert
-rw-------  1 bo  staff  1679 Mar 23 13:57 node.key

$ ./cockroach cert create-client --ca-cert ca.cert --ca-key=ca.key --cert client.cert --key client.key root
$ ls -l client.*
-rw-r--r--  1 bo  staff  1103 Mar 23 14:01 client.cert
-rw-------  1 bo  staff  1675 Mar 23 14:01 client.key

$ mkdir /tmp/cdbdat

$ ./cockroach start --ca-cert ca.cert --cert node.cert --key node.key --store /tmp/cdbdat
build:     alpha.v1-1335-g88909f5 @ 2016/03/23 20:42:31 (go1.6)
admin:     https://dee2nuts.local:8080
sql:       postgresql://root@dee2nuts.local:26257?sslcert=%2FUsers%2Fbo%2Fgows%2Fsrc%2Fgithub.com%2Fcockroachdb%2Fcockroach%2Fnode.cert&sslkey=%2FUsers%2Fbo%2Fgows%2Fsrc%2Fgithub.com%2Fcockroachdb%2Fcockroach%2Fnode.key&sslmode=verify-full&sslrootcert=%2FUsers%2Fbo%2Fgows%2Fsrc%2Fgithub.com%2Fcockroachdb%2Fcockroach%2Fca.cert
logs:      /tmp/cdbdat/logs
store[0]:  path=/tmp/cdbdat
```

**Comment by cuongdo** [comment]
Sorry for taking so long to get back to you. I've just reproduced this and am investigating now.

**Comment by cuongdo** [comment]
Instead of this:

`./cockroach cert create-node --ca-cert ca.cert --ca-key ca.key --cert node.cert --key node.key 127.0.0.1 ::1 localhost`

You can do this:

`./cockroach cert create-node --ca-cert ca.cert --ca-key ca.key --cert node.cert --key node.key 127.0.0.1 ::1 $(hostname)`

Basically, the problem is that the SSL cert needs to have your hostname in it, not `localhost`.

**Comment by cuongdo** [comment]
@jseldess: this seems like it could be a common issue, since for test purposes, people often use `localhost` when asked for a hostname... is there a place to document this?

**Comment by jseldess** [comment]
Thanks for the mention, @cuongdo. I'll flag this for follow-up.

**Comment by bshi** [comment]
Given this has been categorized as pilot error, it would be helpful if the "cockroach cert create-node" command issued either an error or a warning on encountering "localhost".

**Comment by tamird** [comment]
"localhost" is not always a bogus value, so blindly emitting that warning would not be correct.
