### ISSUE TITLE
Share the code between implementation of doctor tool and `crdb_internal.invalid_objects`

### ISSUE THREAD

**Issue by spaskob** [cockroachdb/cockroach#55219]
**Describe the problem**

Recently we have introduced two tools for detecting sql internal data inconsistencies: [`cockroach debug doctor`](https://github.com/cockroachdb/cockroach/pull/52622) and [`crdb_internal.invalid_objects`](https://github.com/cockroachdb/cockroach/pull/54017). This is a meta-issue that describes future ideas for improving these tools and more specifically how to share code between them.

***Background***

The doctor tool performs consistency checks on the client side (either reading from a live cluster or a debug zip). This is handy for fast development and deployment of new checks and for supporting old cockroach releases. Its main drawback is that it is cumbersome to use for internal sever-side checks or in tests or logic tests.

The internal table so far detects invalid objects only via the descriptor `Validate` function. The table is very useful for checking the consistency of internal objects using a sql expression and these checks can easily be embedded in tests. The table is also automatically included in debug zips which means that as old releases are phased out it will duplicate most of the doctor tool checks.

***Future plans***

The main idea is that new checks will be first implemented and perfected via the doctor tool and eventually will find their way in the `crdb_internal.invalid_objects` table or other internal tables - one can imagine a similar table for troublesome jobs.

To that end it is important to share as much error checking code between the two tools. Currently only the implementation of table validation is shared.

***Proposals***

* [x] 1. Develop interface similar to `catalog.DescGetter` for querying the state of the namespace mapping.

* We should also consider adding some cheap namespace checks to descriptor validation.

* [x] 2. Refactor function `doctor.ExamineDescriptors` to use descriptor and namespace getters instead of the raw contents of the descriptor and namespace tables. 
 
* This will require adding ability to iterate over all descriptors in `DescGetter`.

*  [x] 3. Add namespace invalid objects to `crdb_internal.invalid_objects` that are currently only detected in `doctor.ExamineDescriptors`.

* Descriptors ids pointed to in the namespace map that no longer exist.
* Draining names entries in the descriptor table.

* [x] 4. Add descriptor ids that are pointed to from jobs but no longer exist to `crdb_internal.invalid_objects`.
* This check is currently implemented only in `doctor.ExamineJobs`.

**Comment by jordanlewis** [comment]
@postamar to triage and close this after creating child issues.

**Comment by ajwerner** [comment]
@postamar I think we should close this now that we use the namespace validation logic in the catalog. What do you think?

**Comment by postamar** [comment]
On the one hand, I agree that most of this issue has already been addressed, but on the other hand I feel that the `invalid_objects` table could do with a bit of love. I sense this is a low hanging fruit,  I'll see if I can whip up something today. This would address item number 3.

I also feel that item number 4 might be interesting and worth thinking about in conjunction with https://github.com/cockroachdb/cockroach/pull/62620#discussion_r603293491
In fact instead of a diagnostic function, perhaps have an internal table instead? Something that lists all dangling descriptor IDs, in a sense.

**Comment by postamar** [comment]
Regarding item number 4 I am loath to add to `invalid_objects` errors that pertain to nonexistent descriptors, so I think I'll leave it at what's in my PR.
