### ISSUE TITLE
doctor: more fine grained namespace checks for namespace and namespace2 table

### ISSUE THREAD

**Issue by spaskob** [cockroachdb/cockroach#55237]
When migrating from 19.2 to 20.1 release certain inconsistencies are introduced in the namespace table for tables `namespace` and `namespace2`. These are expected and should only be warnings in the doctor too. Unfortunately these state transitions are hard to detect and currently we don't mark as errors any inconsistencies regarding table `namespace`.

We should enumerate all the possible non-20.1 possibilities and emit a warning if one of those states is encountered without returning a nonzero exit status and fail otherwise.

**Comment by vy-ton** [comment]
@ajwerner @postamar Is this still valuable todo? Or do the new schema validation errors mean we should close this?

**Comment by postamar** [comment]
We should indeed close this.
