### ISSUE TITLE
Clusterwide version of crdb_internal.node_statement_statistics via sql

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/cockroach#55245]
**Is your feature request related to a problem? Please describe.**
I am unable to get clusterwide statement statistics via sql. The only way to get this information is via the AdminUI Statements page. 

**Describe the solution you'd like**
Create a table that is similar to crdb_internal.node_statement_statistics that provides clusterwide information.

**Describe alternatives you've considered**

**Additional context**
requested by customer in [zendesk ticket 6456](https://cockroachdb.zendesk.com/agent/tickets/6456)

**Comment by piyush-singh** [comment]
@florence-crl can we clarify what is meant by "cluster-wide" stats? Aggregated across nodes? The admin UI statements page is powered by the crdb_internal virtual table, so we should be able to recreate what this customer is asking for using a query

**Comment by florence-crl** [comment]
@piyush-singh By "cluster-wide", I understand it to be "aggregated across nodes". Currently when you log into a node using a sql shell and query crdb_internal.node_statement_statistics, the results only include statement run on that give node. While in the AdminUI, you get data "aggregated across nodes".

For example, I ran our demo application movr workload against the 3 nodes of my local cluster:

```
./cockroach-v20.1.6 workload init movr 'postgresql://root@localhost:26257?sslmode=disable'
./cockroach-v20.1.6 workload run movr --duration=1m 'postgresql://root@localhost:26257?sslmode=disable'
./cockroach-v20.1.6 workload run movr --duration=1m 'postgresql://root@localhost:26258?sslmode=disable'
./cockroach-v20.1.6 workload run movr --duration=1m 'postgresql://root@localhost:26259?sslmode=disable'
```

When I ran this query logged into each node, I only get the count and avg_time for that node:

```
Florences-MacBook-Pro:20.1.6 florencemorris$ ./cockroach-v20.1.6 sql --insecure --host=localhost:26257
root@localhost:26257/defaultdb> select key as sqlstmt, count AS executions, service_lat_avg AS avg_time FROM crdb_internal.node_statement_statistics WHERE count > 3600 AND application_name = 'movr' ORDER by 2 DESC;
                                 sqlstmt                                | executions |       avg_time
------------------------------------------------------------------------+------------+------------------------
  SELECT city, id FROM vehicles WHERE city = $1                         |      36829 | 0.0003929228868554664
  UPSERT INTO vehicle_location_histories VALUES ($1, $2, now(), $3, $4) |      18418 | 0.0009324729069388653

Florences-MacBook-Pro:20.1.6 florencemorris$ ./cockroach-v20.1.6 sql --insecure --host=localhost:26258
root@localhost:26258/defaultdb> select key as sqlstmt, count AS executions, service_lat_avg AS avg_time FROM crdb_internal.node_statement_statistics WHERE count > 3600 AND application_name = 'movr' ORDER by 2 DESC;
                                 sqlstmt                                | executions |        avg_time
------------------------------------------------------------------------+------------+-------------------------
  SELECT city, id FROM vehicles WHERE city = $1                         |      35697 | 0.00024113625794884675
  UPSERT INTO vehicle_location_histories VALUES ($1, $2, now(), $3, $4) |      17938 |   0.001126322053740662

Florences-MacBook-Pro:20.1.6 florencemorris$ ./cockroach-v20.1.6 sql --insecure --host=localhost:26259
root@localhost:26259/defaultdb> select key as sqlstmt, count AS executions, service_lat_avg AS avg_time FROM crdb_internal.node_statement_statistics WHERE count > 3600 AND  application_name = 'movr' ORDER by 2 DESC;
                                 sqlstmt                                | executions |       avg_time
------------------------------------------------------------------------+------------+------------------------
  SELECT city, id FROM vehicles WHERE city = $1                         |      31277 | 0.0004961764235700355
  UPSERT INTO vehicle_location_histories VALUES ($1, $2, now(), $3, $4) |      15821 |  0.001046095442765937
```

When I go to the AdminUI Statements page, I get the `EXECUTION COUNT` and `LATENCY` across all 3 nodes:
![image](https://user-images.githubusercontent.com/58752716/95241372-a7d63e00-07db-11eb-8688-d617c44ac476.png)

**Comment by piyush-singh** [comment]
cc @awoods187 and @jordanlewis

**Comment by BramGruneir** [comment]
@piyush-singh, any update on this?

**Comment by piyush-singh** [comment]
reassigning this to Andy as I think this is more related to SQL Observability

**Comment by Azhng** [comment]
@kevin-v-ngo can we close this issue?

**Comment by kevin-v-ngo** [comment]
> @kevin-v-ngo can we close this issue?

Yes, closing as this is being tracked here with persisted stats: https://github.com/cockroachdb/cockroach/issues/64743
