### ISSUE TITLE
bulkio: SHOW BACKUP returns a 404 error message

### ISSUE THREAD

**Issue by fabiog1901** [cockroachdb/cockroach#55266]
The default behavior of `SHOW BACKUP` returns a 404 error message for the S3 bucket stating file doesn't exist when there are sub directories. 

It would be nice if the traversal happened here (request #55265) or a message stated that it was the parent directory and that the end user needs to supply the sub directories to view the backups.

Assign @dt and @mwang1026 for triage

gz#6471

Epic CRDB-7909

Jira issue: CRDB-3684

**Comment by BramGruneir** [comment]
Here's the customer request for context: https://cockroachdb.zendesk.com/agent/tickets/6471

**Comment by BramGruneir** [comment]
@mwang1026 any updates on this?

**Comment by mwang1026** [comment]
No plans here. Maybe an update to the error message but we can't know what the error is -- are you pointing to something that doesn't actually have a backup?

**Comment by commatter** [comment]
@mwang1026, the issue this ticket is trying to resolve is that, if you have nested some backups inside a directory, you will receive a 404. 

So yes, there is backups, but the issue is that they are trying to restore the parent directory.

**Comment by adityamaru** [comment]
Tracking work over https://github.com/cockroachdb/cockroach/issues/69568, we will close both out once there is a fix merged.
