### ISSUE TITLE
sql: possibly update `crdb_internal.node_transaction_statistics` schema to have int ID fields instead of string

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#55284]
Internally, the transactionID and statementIDs moved from being saved as strings to uint64s. `crdb_internal.node_transaction_statistics`, the internal table that inspects them, still includes them as strings in its schema. This is slightly complicated because these IDs are unsigned, so casting them to integers would make their value negative, which might be weird UX. Additionally, this would also mean that we see different values for these IDs in the admin UI as compared to `crdb_internal`. 

cc @knz

**Comment by Azhng** [comment]
Closing this issue: see [context](https://github.com/cockroachdb/cockroach/pull/64076#pullrequestreview-642578979)
