### ISSUE TITLE
sql: refactor appStats to have a RWMutex instead of a Mutex

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#55285]
There are various places in the code where appStats can benefit from acquiring a read lock (such as https://github.com/cockroachdb/cockroach/blob/5965426b8823d60345bb8a5b29503b009777691f/pkg/sql/app_stats.go#L251). We should refactor appStats to start using a RWMutex and acquire read locks wherever appropriate. 

Jira issue: CRDB-3680

**Comment by rafiss** [comment]
@arulajmani Are you planning to do this? I was interested in taking a stab unless you already have something
