### ISSUE TITLE
sql: "refreshing descriptor: 4294867296" error from from uninitialized OID

### ISSUE THREAD

**Issue by lucy-zhang** [cockroachdb/cockroach#55290]
We've been seeing these in the logs for roachtests:

```
I201007 12:20:23.504036 77953 sql/catalog/lease/lease.go:2053 ⋮ [n1] refreshing descriptor: 4294867296 lease failed: descriptor not found
```

This one is from `kv/gracefuldraining/nodes=3`. I've also seen this on some of the tpcc schema change roachtests. We should figure out what's going on here.

**Comment by lucy-zhang** [comment]
4294867296 is equal to 2^32-100000 (and it's always that value across multiple roachtests where I've seen this happen). Since `oidext.CockroachPredefinedOIDMax` is 100000, I'm going to guess that we're unintentionally subtracting that value from a zero `tree.ID`/`descpb.ID` (which is a uint32). Probably here? https://github.com/cockroachdb/cockroach/blob/1e5a610/pkg/sql/catalog/typedesc/type_desc.go#L148-L152

**Comment by knz** [comment]
Then looks like a UDT OID is unset or set to zero, and then passed as argument to this function?

I know little of UDTs in fact. That would be more a question for @solongordon or @arulajmani perhaps?

**Comment by arulajmani** [comment]
Not very familiar with UDTs either, but I recently @otan and I had to deal with something similar where the parentSchemaID was unset, around here: https://github.com/cockroachdb/cockroach/blob/1e5a610195b5e92871df50463f08bae2e25d722c/pkg/sql/catalog/typedesc/type_desc.go#L52
Seems like this would check out, as it sets the ID to 0 here.

**Comment by lucy-zhang** [comment]
But that sets the actual descriptor ID to 0, not the OID, right?

In any case I don't understand how this would have made it into the set of leased table IDs.

**Comment by otan** [comment]
it would be more helpful if `descriptor not found` actually had a stack trace.
i've spent too many days getting that stuff debugged :P

**Comment by otan** [comment]
my guess is some type is not being hydrated at some place we're trying to acquire the lease.

**Comment by lucy-zhang** [comment]
@rafiss does anyone from SQL Experience have time to investigate this? It seems unlikely that leasing is actually the root cause of this. If it turns out to be a schema problem we'll start looking at it again.

**Comment by yuzefovich** [comment]
I've also been seeing the log message when running `tpcdsvec` roachtest when running on 76935fd62c5a76f88b754cd3f9a5bfb3ccf1d8c2.
