### ISSUE TITLE
unknown function: pg_tablespace_location

### ISSUE THREAD

**Issue by domnulnopcea** [cockroachdb/cockroach#55322]
using dbeaver to create a a new db in a cockroachdb cluster I get the following error

SQL Error [42883]: ERROR: unknown function: pg_tablespace_location()
ERROR: unknown function: pg_tablespace_location()
ERROR: unknown function: pg_tablespace_location()

**Comment by rafiss** [comment]
@domnulnopcea You should be following the instructions here: https://www.cockroachlabs.com/docs/stable/dbeaver.html DBeaver has logic to skip this functionality when using CockroachDB.

If the issue persists, you should file an issue on the DBeaver repo: https://github.com/dbeaver/dbeaver
