### ISSUE TITLE
ERROR: unknown function: pg_catalog.pg_relation_size()

### ISSUE THREAD

**Issue by domnulnopcea** [cockroachdb/cockroach#55328]
when using dbeaver to navigate over the existing indexes i get the error

ERROR: unknown function: pg_catalog.pg_relation_size()

**Comment by rafiss** [comment]
@domnulnopcea You should be following the instructions here: https://www.cockroachlabs.com/docs/stable/dbeaver.html DBeaver has logic to skip this functionality when using CockroachDB.

If the issue persists, you should file an issue on the DBeaver repo: https://github.com/dbeaver/dbeaver
