### ISSUE TITLE
ERROR: unknown function: pg_get_ruledef()

### ISSUE THREAD

**Issue by domnulnopcea** [cockroachdb/cockroach#55333]
when using dbeaver I get the following error

ERROR: unknown function: pg_get_ruledef()

**Comment by rafiss** [comment]
@domnulnopcea You should be following the instructions here: https://www.cockroachlabs.com/docs/stable/dbeaver.html DBeaver has logic to skip this functionality when using CockroachDB.

If the issue persists, you should file an issue on the DBeaver repo: https://github.com/dbeaver/dbeaver
