### ISSUE TITLE
sql: remove testing settings in favor of build tags

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#55348]
We have introduced several cluster settings and session variables in order to expose some testing knobs:
- [x] `sql.testing.vectorize.batch_size`
- [x] `sql.testing.mutations.max_batch_size`
- [ ] `testing_vectorize_inject_panics`
- [ ] maybe `testing.system_namespace_migration.enabled` and some others

Such settings/variables are exposed to the users which is not an ideal scenario. Additionally, we have encountered some issues with the speed of propagation of the cluster settings (#51156) which could lead to rare test flakes.

We should change our approach without losing the test coverage. One idea was discussed is using the build tags to enable certain code paths (prototyped in #55223) which we should probably implement and remove the settings/variables approach.

**Comment by asubiotto** [comment]
related to #55223

**Comment by yuzefovich** [comment]
`testing_vectorize_inject_panics` cannot be easily replaced with a build tag (for example, it is used in the `sqlsmith` roachtest, and we need to have an ability to run some setup queries before enabling the panic injection).

`testing.system_namespace_migration.enabled` is a special setting used only in one test, and it's better not to touch it.

So I'll close this issue as addressed by #57483.
