### ISSUE TITLE
pgdate: M/D/Y date format not supported

### ISSUE THREAD

**Issue by vlolla** [cockroachdb/cockroach#55349]
Currently the M/D/Y format for time does not parse:

```
demo@127.0.0.1:61487/defaultdb> select '12/4/2011 15:03'::timestamptz;
ERROR: parsing as type timestamp: field day value 2011 is out of range
SQLSTATE: 22008
```

On psql, this parses successfully, which we should look to imitate:

```
otan=# select '12/4/2011 15:03'::timestamptz;
      timestamptz
------------------------
 2011-12-04 15:03:00-08
(1 row)
```

#50011 provides an example of where to mess around when it comes to parsing time.

----

(original problem report)

**Describe the problem**

Unable to import data into a CRDB table from csv file with “TIMESTAMP” field when there is a Primary Key defined for the table however, when we try to the same without a Primary Key we can successfully import the data from csv.

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

What did you do? Describe in your own words.

**Case 1: No PK. Data gets imported successfully.**
Script:
 
CREATE TABLE public.ppmo_cmn_captions_nls_without_PK (
ID INT NOT NULL,
TABLE_NAME VARCHAR(30) NOT NULL,
PK_ID INT NOT NULL,
LANGUAGE_CODE VARCHAR(30) NOT NULL,
NAME VARCHAR(2100) NOT NULL,
DESCRIPTION VARCHAR(2100),
CREATED_DATE TIMESTAMP NOT NULL,
CREATED_BY INT NOT NULL,
LAST_UPDATED_DATE TIMESTAMP  NOT NULL,
LAST_UPDATED_BY INT NOT NULL,
ATTRIBUTE1 VARCHAR(1000),
ATTRIBUTE2 VARCHAR(1000),
ATTRIBUTE3 VARCHAR(1000),
ATTRIBUTE4 VARCHAR(1000),
ATTRIBUTE5 VARCHAR(1000)
--,PK VARCHAR(300) PRIMARY KEY
);
 
IMPORT INTO  public.ppmo_cmn_captions_nls_without_PK
CSV DATA
('s3://ppmo-initial-load/Test/CMN_CAPTIONS_NLS_without_PK.csv?Bucket=ppmo-initial-load&AWS_ACCESS_KEY_ID=*********&AWS_SECRET_ACCESS_KEY=**********&AWS_ENDPOINT=**************')
WITH skip = '1',  nullif='';
 
Description: In this table, there is no PK defined. The import runs successfully.
 

**Case 2: With PK. Data import fails.**

Script:
CREATE TABLE public.ppmo_cmn_captions_nls_with_PK (
ID INT NOT NULL,
TABLE_NAME VARCHAR(30) NOT NULL,
PK_ID INT NOT NULL,
LANGUAGE_CODE VARCHAR(30) NOT NULL,
NAME VARCHAR(2100) NOT NULL,
DESCRIPTION VARCHAR(2100),
CREATED_DATE TIMESTAMP NOT NULL,
CREATED_BY INT NOT NULL,
LAST_UPDATED_DATE TIMESTAMP  NOT NULL,
LAST_UPDATED_BY INT NOT NULL,
ATTRIBUTE1 VARCHAR(1000),
ATTRIBUTE2 VARCHAR(1000),
ATTRIBUTE3 VARCHAR(1000),
ATTRIBUTE4 VARCHAR(1000),
ATTRIBUTE5 VARCHAR(1000),
PK VARCHAR(300) PRIMARY KEY
);
 
IMPORT INTO  public.ppmo_cmn_captions_nls_with_PK
CSV DATA
('s3://ppmo-initial-load/Test/CMN_CAPTIONS_NLS_with_PK.csv?Bucket=ppmo-initial-load&AWS_ACCESS_KEY_ID=***************&AWS_SECRET_ACCESS_KEY=**************&AWS_ENDPOINT=***************')
WITH skip = '1',  nullif='';
 
Description: In this table, there is a PK defined. The import fails.

**Expected behavior**
SHOULD LOAD ALL THE DATA INTO TABLE

**Additional data / screenshots**

**Environment:**
 - CockroachDB version [v20.1.3] three node cluster
 - Server OS: [VM/Linus]
 - Client app [import from DB viewer.]

**Additional context**
What was the impact?

Unable to migrate data from Oracle to CockroachDB as part of initial load process

**Comment by mwang1026** [comment]
Hi there. Thanks for filing this. Do you mind posting the error? My hypothesis is that your file contains a duplicate entry of the same primary key, which our IMPORT fails on today and an error would confirm that.

The reason the same import would succeed without a primary key is that the uniqueness constraint wouldn't be violated.

**Comment by ssabnam** [comment]
Hi,
We are getting thr below issue:

SQL Error [XXUUU]: ERROR: s3://ppmo-initial-load/Test/CMN_CAPTIONS_NLS_with_PK.csv?Bucket=ppmo-initial-load&AWS_ACCESS_KEY_ID=CLP8QIUpGvxuyya5e0cD&AWS_SECRET_ACCESS_KEY=1kst3P2Tgmzm0GSBOa39k2xa5PSWKuNqlTjEtHUO&AWS_ENDPOINT=s3api-core.uhc.com: error parsing row 2: parse "created_date" as TIMESTAMP: parsing as type timestamp: field day value 2011 is out of range (row: "17515680,ODF_VIEW_ATTRIBUTES,5015111,en,Created By Resource,,12/4/2011 15:03,1,12/4/2011 15:03,1,,,,,,ODF_VIEW_ATTRIBUTES1")

**Comment by ssabnam** [comment]
We are getting the below error:

SQL Error [XXUUU]: ERROR: s3://ppmo-initial-load/Test/CMN_CAPTIONS_NLS_with_PK.csv?Bucket=ppmo-initial-load&AWS_ACCESS_KEY_ID=************&AWS_SECRET_ACCESS_KEY=***********&AWS_ENDPOINT=s3api-core.uhc.com: error parsing row 2: parse "created_date" as TIMESTAMP: parsing as type timestamp: field day value 2011 is out of range (row: "17515680,ODF_VIEW_ATTRIBUTES,5015111,en,Created By Resource,,12/4/2011 15:03,1,12/4/2011 15:03,1,,,,,,ODF_VIEW_ATTRIBUTES1")

**Comment by otan** [comment]
looks like the M/D/Y format `12/4/2011 15:03` is not currently supported. can you format your dates differently?

**Comment by otan** [comment]
i've rephrased this issue as the core of the problem @ssabnam in the meantime you can get around this by reformatting your dates to be `YYYY-MM-DD HH:MM`.

**Comment by jhatcher9999** [comment]
@ssabnam and @vlolla, there is an example of having Oracle use this date format on export here: https://www.cockroachlabs.com/docs/stable/migrate-from-oracle.html#step-3-export-table-data

**Comment by otan** [comment]
that's great if oracle has a workaround!
we should be able to support the format too -- which is why i've added this as an issue.

**Comment by haribhatt34** [comment]
Hi, I would like to give it a try, although I am new to open source and go, so might take more time than required.

**Comment by vlolla** [comment]
Thank you for accepting this as an issue. This format accepted when we load data with no primary key, this is not supported when there is no primary key. Probably issue needs to be debug and fix

**Comment by yasoobh** [comment]
Hi, I was trying to debug the core problem of 'M/D/Y HH:MM' format not being supported in parsing. But upon debugging, I found that the parser actually does support this format. In fact, timeutil/pgdate/parsing_test.go has test cases already for this and accepts this particular format, although only when the mode in FieldExtract is ParseModeMDY.

> demo@127.0.0.1:61487/defaultdb> select '12/4/2011 15:03'::timestamptz;

And the error is coming in this case because in ParseDTimestampTZ we are hardcoding the mode as ParseModeYMD.

Here: https://github.com/cockroachdb/cockroach/blob/e82749a3660d112b6639e9fe3aa710e9577600d3/pkg/sql/sem/tree/datum.go#L2419

One possible solution would be to that in case of error, we try again in ParseDTimestampTZ with different `ParseMode`s.

```
t, dependsOnContext, err := pgdate.ParseTimestamp(now, pgdate.ParseModeYMD, s)
if err != nil {
	// check for parsemodemdy and return accordingly
}
```

Please let me know if I'm going in the right direction or correct me if I'm wrong.

**Comment by otan** [comment]
@yasoobh looks like we have a lead!

I think this means we need to implement the DateStyle session variable (https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-DATESTYLE) and use that instead.

Reading through https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/vars.go#L248, it looks like we do MDY by default. So I guess the question there is why the ParseMode is YMD. What breaks if we use MDY instead?

**Comment by otan** [comment]
It may be useful to understand what we're doing differently to Postgres's timestamptz_in before going forwards: https://github.com/postgres/postgres/blob/970c050/src/backend/utils/adt/timestamp.c#L401 -- seems like MDY is the default there as well, so how does it know YMD vs DMY / MDY?

**Comment by yasoobh** [comment]
So in PostgreSQL, although MDY format works (because MDY is default), if we try a DMY format timestamp, the query fails.

```
> select '18/4/2011 15:37'::timestamptz;

ERROR:  date/time field value out of range: "18/4/2011 15:37"
LINE 2: select '18/4/2011 15:37'::timestamptz;
               ^
HINT:  Perhaps you need a different "datestyle" setting.
SQL state: 22008
Character: 31
```

Setting the session variable `datestyle` works.

```
> set datestyle = 'dmy';
> select '18/4/2011 15:37'::timestamptz;

2011-04-18 15:37:00+05:30
```

In roach:

```
root@localhost:26257/defaultdb> show datestyle;
  datestyle
-------------
  ISO, MDY
(1 row)

Time: 1ms total (execution 1ms / network 0ms)
```
```
root@localhost:26257/defaultdb> set datestyle = 'YMD';
ERROR: invalid value for parameter "DateStyle": "ymd"
SQLSTATE: 22023
DETAIL: this parameter is currently recognized only for compatibility and has no effect in CockroachDB.
HINT: Available values: ISO,ISO, MDY

```

In Roach docs as well, the `datestyle` session variable is marked as reserved. https://www.cockroachlabs.com/docs/stable/set-vars.html#supported-variables. Not sure what this means though.

So now I'm assuming that we can't use the session variable. So second option is to use MDY as default when parsing as that is what we are communicating as default in `datestyle` session variable anyway.

Updating that and running tests in datum_test.go, none of the existing tests break.

Sample existing tests:

```
testData := []struct {
	str              string
	expected         time.Time
	expectedDepOnCtx bool
}{
	{"2001-02-03", time.Date(2001, time.February, 3, 0, 0, 0, 0, local), true},
	{"2001-02-03 04:05:06", time.Date(2001, time.February, 3, 4, 5, 6, 0, local), true},
	{"2001-02-03 04:05:06.000001", time.Date(2001, time.February, 3, 4, 5, 6, 1000, local), true},
}
```

But that is just because the test strings are of a format where year is explicit because it has 4 digits.

Adding these new tests gives a clearer picture:

These new tests pass with MDY as default mode.

```
	{"2011/12/18", time.Date(2011, time.December, 18, 0, 0, 0, 0, local), true},
	{"2011/12/18 04:05:06", time.Date(2011, time.December, 18, 4, 5, 6, 0, local), true},
	{"2011/12/18 04:05:06.000001", time.Date(2011, time.December, 18, 4, 5, 6, 1000, local), true},
	{"12/18/2011", time.Date(2011, time.December, 18, 0, 0, 0, 0, local), true},
	{"12/18/2011 04:05:06", time.Date(2011, time.December, 18, 4, 5, 6, 0, local), true},
	{"12/18/2011 04:05:06.000001", time.Date(2011, time.December, 18, 4, 5, 6, 1000, local), true},
```

These tests fail however:

```
	{"11/12/18", time.Date(2011, time.December, 18, 0, 0, 0, 0, local), true},
	{"11/12/18 04:05:06", time.Date(2011, time.December, 18, 4, 5, 6, 0, local), true},
	{"11/12/18 04:05:06.000001", time.Date(2011, time.December, 18, 4, 5, 6, 1000, local), true},
```

So changing the default mode from YMD to MDY would break these last set of queries.

How should I proceed?

**Comment by otan** [comment]
Thank you for the thorough investigation! This is a weekend, so this was a quick research bit -- hopefully it's enough to keep you going.

"reserved" means we only support MDY, for now. so in theory, we never expect D/M/Y to work

> {"11/12/18", time.Date(2011, time.December, 18, 0, 0, 0, 0, local), true},
> 11/12/18 04:05:06", time.Date(2011, time.December, 18, 4, 5, 6, 0, local), true},
> 11/12/18 04:05:06.000001", time.Date(2011, time.December, 18, 4, 5, 6, 1000, local), true},

these return year as 2018 on PostgresSQL, which is not in line with your expected cases. 

I see some logic in https://github.com/postgres/postgres/blob/master/src/backend/utils/adt/datetime.c#L2503 which translates dates to 2018 in this case, but I'm not entirely sure when Postgres decides Y is last or first despite being in MDY mode.

I will reiterate it may be worth digging through the Postgres timestamptz_in functionality https://github.com/postgres/postgres/blob/970c050/src/backend/utils/adt/timestamp.c#L401  to determine where exactly our implementations misalign.

**Comment by rafiss** [comment]
Linking up our other issue for supporting DateStyle: #41773

**Comment by rafiss** [comment]
It seems like our `ParseModeMDY` is actually capable of handling `YYYY-MM-DD` dates as well. So I think we can just change to use `ParseModeMDY`. This will also align closer with Postgres:

Postgres:
```
rafiss@127:postgres>  select '11-12-04'::timestamptz;
+------------------------+
| timestamptz            |
|------------------------|
| 2004-11-12 00:00:00-05 |
+------------------------+
```

CockroachDB 20.2:
```
root@:26257/defaultdb> select '11-12-04'::timestamptz;
          timestamptz
--------------------------------
  2011-12-04 00:00:00+00:00:00
```

I think it would be better if CockroachDB matched the PG behavior.
