### ISSUE TITLE
sql: support the ALTER TYPE DROP VALUE command

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#55358]
Parallels https://github.com/cockroachdb/cockroach/issues/48670, but is not supported by PostgreSQL.

We currently support the ability to add new values to an enum type, but not to remove existing values from an enum type. This is because removing existing values from a type needs extra validation to ensure that no existing rows in any of the tables that use the type are now in violation of the more restrictive constraints imposed by the enumeration. We don't need this for `ALTER TYPE ADD VALUE` because such an operation makes the enumeration strictly more permissive.

So removing a value from an enum type is more expensive than adding one, which is why it isn't supported. But the workaround to this is even more expensive - the only way to remove a variant from an enum is to create a new enum and replace the type for each user, which requires a full table revalidation instead of just validating that the value being removed is unused.

This leaves something to be desired, especially when the enum column is indexed. In such cases, the validation step for dropping a variant could be heavily optimized by the SQL optimizer by running a statement along the lines of:
```
SELECT EXISTS (SELECT * FROM table WHERE enum_col = dropping_value LIMIT 1);
```
For indexed tables, this turns an `O(num_rows_in_table)` operation (i.e. using a new type and re-validating) into roughly an `O(1)` operation.

There is a little bit of complexity here around coordinating the schema change and performing the validation that no existing rows use the value, but that seems workable. We would first place the value being dropped into a "read only" state, just [like we do](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20200331_enums.md#changing-enum-definitions) when adding values. Once that's in place, we would perform the validation. Finally, if validation succeeded, we would remove the value from the enum entirely.

**Comment by rohany** [comment]
Another difficulty with this is that many tables could contain the enum, so the schema change would need to be coordinated across them. Also, table expressions could contain the enum value being dropped, like a computed column or a view. In these cases it's unclear what to do.

**Comment by ajwerner** [comment]
>  so the schema change would need to be coordinated across them.

Multi-table schema changes is something the schema team is working on this release (21.1) which should help enable this. 

> In these cases it's unclear what to do.

Good point. Seems surmountable but annoying to deal with.

**Comment by nvanbenschoten** [comment]
> Also, table expressions could contain the enum value being dropped, like a computed column or a view. In these cases it's unclear what to do.

This is a really good point. I'm also curious how we'd want to treat this.

Are enum value literals in table expressions considered instances of those enum values or instances of string literals that are cast to the enum type? I ask because there does seem to be an analog to this question in PG. 

```
nathan=# create type enum_type as enum ('variant1');
CREATE TYPE
nathan=# create view v1 as select 'variant1'::enum_type;
CREATE VIEW
nathan=# create view v2 as select 'variant1'::text::enum_type;
CREATE VIEW
nathan=# select * from v1;
 enum_type
-----------
 variant1
(1 row)

nathan=# select * from v2;
 enum_type
-----------
 variant1
(1 row)

nathan=# alter type enum_type rename value 'variant1' to 'variant2';
ALTER TYPE

nathan=# select * from v1;
 enum_type
-----------
 variant2
(1 row)

nathan=# select * from v2;
ERROR:  invalid input value for enum enum_type: "variant1"
```

This is also analogous in some regard to dropping a column in a table that is referenced by a view. In that case, we're able to reject the drop column statement because we track the ColumnID set in the `TableDescriptor_Reference` backreference.

**Comment by rohany** [comment]
As for as I understand, enum values are stored as their internal "datum" representation in PG, not as a cast from a string value. This allows them to "survive" changes to the enum's string form when stored in views or computed columns etc.

**Comment by nvanbenschoten** [comment]
It looks like CRDB handles this differently, more the like the cast from a string value approach:
```
demo@127.0.0.1:50254/movr> create type enum_type as enum ('variant1');
CREATE TYPE

demo@127.0.0.1:50254/movr> create view v1 as select 'variant1'::enum_type;
CREATE VIEW

demo@127.0.0.1:50254/movr> create view v2 as select 'variant1'::text::enum_type;
CREATE VIEW

demo@127.0.0.1:50254/movr> select * from v1;
  enum_type
-------------
  variant1
(1 row)

demo@127.0.0.1:50254/movr> select * from v2;
  enum_type
-------------
  variant1
(1 row)

demo@127.0.0.1:50254/movr> alter type enum_type rename value 'variant1' to 'variant2';
ALTER TYPE

demo@127.0.0.1:50254/movr> select * from v1;
ERROR: invalid input value for enum enum_type: "variant1"
SQLSTATE: 22P02

demo@127.0.0.1:50254/movr> select * from v2;
ERROR: invalid input value for enum enum_type: "variant1"
SQLSTATE: 22P02
```
So given that behavior of views storing a "shallow reference" to enum values, it seems reasonable for DROP VALUE to follow suit and ignore table expressions that reference the dropped value and let them return errors going forward. Unless we don't like this behavior and intend to fix it.

**Comment by rohany** [comment]
This is a bug, not a feature -- https://github.com/cockroachdb/cockroach/issues/49962

**Comment by nvanbenschoten** [comment]
Thanks for the link, I wasn't aware of that. Then at a minimum, this means that we're going to need to introduce some form of table expression validation/rewriting for schema changes on enums, so the need for one here is less of a problem on its own. And it seems a little more palatable to add support for DROP VALUE without immediately polishing off that rough edge since we're already susceptible to that class of problem elsewhere.

For context on all of this, we think enums could have a very important role to play in our reimagined multi-region story.

**Comment by rohany** [comment]
Individual rewrites of expressions / the expressions in a table isn't bad -- the walking infrastructure present can do this. The thing that isn't present is walking of query AST's, which is needed for views.

> For context on all of this, we think enums could have a very important role to play in our reimagined multi-region story.

Very cool -- hyped to see what this ends up looking like

**Comment by aayushshah15** [comment]
It seems like most uses of `ALTER TYPE some_enum DROP VALUE x` would require the user to have already updated/deleted rows that use `x` before, so I wonder if the proposed syntax should just support this (something to the effect of: `ALTER TYPE some_enum DROP VALUE x [DELETE | REPLACE_WITH y]`), which allows us to skip the (likely redundant) validation.

**Comment by nvanbenschoten** [comment]
I think those extensions make a lot of sense. The `DELETE` behavior aligns with the `CASCADE` clause we see with a number of other schema operations. The behavior we've discussed so far on this issue aligns with a `RESTRICT` clause.

The `REPLACE WITH` option has less precedence (i.e. it's not part of the `opt_drop_behavior` rule), but it does seem like it would be useful. Is there any existing syntax that we can draw inspiration from for this?
