### ISSUE TITLE
ui: users/roles with the NOLOGIN option are allowed to log in via OIDC

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#55370]
The OIDC flow does not check the NOLOGIN role option properly.

This allows users without the LOGIN bit to access the UI via OIDC. This is incorrect.

cc @dhartunian

**Comment by knz** [comment]
@dhartunian I'll send a PR out today

**Comment by dhartunian** [comment]
Thanks for looking into this @knz. Let me know if I can help.

**Comment by knz** [comment]
you can help by reviewing #55371
