### ISSUE TITLE
sql/tree: the schema names and role/user names are not properly anonymized

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#55385]
The AST uses the Go type `string` to represent:

- schema names in `tree.CreateSchema`
- role names and role list names in various "Owner" fields for REASSIGN TO / AUTHORIZATION fields.

This is incorrect: only `tree.Name` is equipped to automatically and properly anonymize the identifiers when constructing telemetry data. 

With the current code, the telemetry leaks (potentially sensitive) schema names and role names.

cc @solongordon @arulajmani

**Comment by knz** [comment]
The code must be changed to use `Name` and `NameList` as appropriate instead.

Related (but not identical to) #54696

**Comment by solongordon** [comment]
This applies to ENUM values as well. I'll resolve this in the same PR.
