### ISSUE TITLE
sql: all the owner syntax mishandles CURRENT_USER and SESSION_USER

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#55382]
Observe:

```
demo@127.0.0.1:44808/defaultdb> alter database defaultdb owner to session_user;
ERROR: role/user "session_user" does not exist
SQLSTATE: 42704
```

The expected error is `role/user "demo" does not exist`

The problem here is that **the parser should recognize when CURRENT_USER/SESSION_USER is used as a special case and the planning code should expand this to the current session's username**.

Beware of the following special case:

```
ATLER DATABASE defaultdb OWNER TO "session_user"
```

In that case the client does intend to use a user/role name called "session_user", not the built-in variable SESSION_USER.

Therefore the type in the AST should probably not be "string".

cc @solongordon

**Comment by knz** [comment]
I discovered that the DROP ROLE logic already knows how to evaluate the strings properly. Maybe this logic can get reused.

**Comment by solongordon** [comment]
Thanks, this is being tracked in #54696.
