### ISSUE TITLE
Admin UI page is empty after default installation.

### ISSUE THREAD

**Issue by tchoulihan** [cockroachdb/cockroach#5544]
I set up a 3 node local cluster using the quickstart guide, and `http://localhost:8080` is available, and returning some html, but there is no content, and its entirely empty.

**Comment by tchoulihan** [comment]
I tested it on chrome, and it seemed to work. Why no firefox support?

**Comment by dt** [comment]
I think this is probably the same issue as #5464.

**Comment by dt** [comment]
Fixed by #5548
