### ISSUE TITLE
sql: support pg_catalog pg_stat_all_tables and pg_statio_all_tables

### ISSUE THREAD

**Issue by jhatcher9999** [cockroachdb/cockroach#55512]
I opened this ticket in the sequelize-cockroachdb repo: https://github.com/cockroachdb/sequelize-cockroachdb/issues/45

However, the issues mentioned in that "fix" are probably features that should also be supported in CRDB since they are valid in PostgreSQL.

Issue 1: concatenating a string with a non-string
You can see that this is supported in latest Postgres: https://www.postgresql.org/docs/current/functions-string.html

To make this work in CRDB, you have to wrap the non-string in a CAST, i.e., 'abc' || CAST(12 AS VARCHAR) -> 'abc12'

Issue 2: use of the system schema view pg_stat_all_tables
Supported here: https://www.postgresql.org/docs/current/monitoring-stats.html#MONITORING-PG-STAT-ALL-TABLES-VIEW

Epic CRDB-2462

**Comment by solongordon** [comment]
Thanks @jhatcher9999. I believe the first issue is being tracked in #34404, so let's use this issue to track `pg_stat_all_tables` support.

**Comment by rafiss** [comment]
These tables will be in v21.2
