### ISSUE TITLE
how to remove elements in a json array

### ISSUE THREAD

**Issue by carr123** [cockroachdb/cockroach#55546]
create table t (id int, post jsonb)

one demo record:   1, {"addr":"la", "friends" : [{"name":"jack", “age”:20}, {"name":"kate", "age":19}] } 

I want to remove a friend in friends array if friend's name='jack', 
how to write the SQL clause, 

thanks.

**Comment by otan** [comment]
you should investigate using the `json_remove_path`.

we generally reserve issues for bugs or feature requests -- come join us on http://cockroa.ch/slack for any SQL questions!
