### ISSUE TITLE
bulkio: s3 throwing error when using temporary session token credentials

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#55564]
Running `CockroachDB CCL v20.2.0-alpha.1-3983-g95c0724bfd (x86_64-apple-darwin19.6.0, built 2020/10/12 20:20:53, go1.13.14)`

I created a temporary session token with `aws sts get-session-token`. I then tried to hit an s3 bucket (SHOW BACKUP in this case) that I have access to with the resulting credentials with format `s3://bucket/directory/file?AWS_ACCESS_KEY_ID=redacted&AWS_SECRET_ACCESS_KEY=redacted&AWS_SESSION_TOKEN=redacted` and it threw me an error of `InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.`

I checked for errant spaces and whatnot and no dice. I can pair to show how to repro as needed

**Comment by pbardea** [comment]
While debugging another issue, I tried this out on `44c559022bc5cfdda8f8a1b4bac7b6763dd090f6` and it seemed to work. I did need to escape the token and secret access key, just checking that you also did that?

**Comment by mwang1026** [comment]
I did not escape. I'll give that a shot.

**Comment by mwang1026** [comment]
Closing. Escaping did the trick.
