### ISSUE TITLE
server: cluster info api endpoint

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#5556]
We need a way to report some aggregate info on the cluster. The main information I'd like is:
- [x] Cluster ID
- [ ] earliest build on any node
- [ ] latest build on any node

**Comment by cuongdo** [comment]
#5619 or some variant of it will restrict the versions, so that the whole cluster will need to be upgraded at once for beta. So, I'll hold off on earliest/latest build for now.

I'll work on cluster ID now though.

**Comment by cuongdo** [comment]
Moving back to 1.0, now that the part needed for beta (Cluster ID) has been implemented.

**Comment by spencerkimball** [comment]
@cuongdo as far as I know, this is complete because we're certainly able to report whether different nodes in the cluster are running different releases. I'm closing this, but please re-open if you believe there is still pending work.
