### ISSUE TITLE
concurrency: produce tracing metadata

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#55583]
**Is your feature request related to a problem? Please describe.**
In the context of always-on tracing, we want to emit structured metadata describing contention events. These will, among others, be consumed by https://github.com/cockroachdb/cockroach/issues/55243 for inclusion in the statements page. They will also figure prominently in SQL session tracing.

**Describe the solution you'd like**
Introduce a protobuf that is emitted whenever a transaction conflicts with another transaction during replica evaluation. The guiding principle here should be that given the information in the protobuf, the SQL layer can construct an explanation of the conflict instructive to the average app developer. This definitely needs to include

1. the key at which the conflict occurred
2. when the conflict was first detected
3. the conflicting transaction (after resolution)

NB: since the metadata is emitted right when the conflict ends, the duration of the conflict is implicitly known.

The action will take place in the lock table waiter, which manages a single conflict here:

https://github.com/cockroachdb/cockroach/blob/1682c401838c3ac734d4df25bad1bb28845210e8/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L156-L399

We'll want to create the protobuf at the top of the method, register it with the registry of inflight operations (also part of the always-on work) and emit it to the trace span (if any) when the conflict has been handled.

Note that the concurrency manager also has a second path that is taken for conflict resolution, via write intent errors. This also has a subcase that needs to emit an event, though it is not thought to be commonly hit (~only when the lock table grows too large).

https://github.com/cockroachdb/cockroach/blob/4ab98a047988b12600c98ad1df49b5fa857a249a/pkg/kv/kvserver/concurrency/concurrency_manager.go#L279-L287

The existing testing in the concurrency package should lend itself very well to verifying that the correct events are emitted. The datadriven tests should be updated to automatically print out any events that are emitted, which means that the existing tests will already give us good coverage.

**Describe alternatives you've considered**

**Additional context**

**Comment by tbg** [comment]
Additional context will follow, but as a starting point, consumers of this can roughly expect to get handed a slice of (protobuf)

```go
type ContentionEvent struct {
  Key roachpb.Key
  Txn roachpb.Transaction // pushee at the end of conflict resolution
  Duration time.Duration // time spent contending on the key against that txn in that one instance
  Outcome enum // pushed?
}
```

**Comment by jordanlewis** [comment]
@tbg, is the `Txn` in this contention event the transaction that was contended with, or the transaction that is contending? In other words, if I'm a transaction and I get this event, is the `Txn` my same transaction or another transaction?

**Comment by tbg** [comment]
The other transaction. My expectation is that the "own transaction" is separately available, but if this turns out not to be the case for some unexpected reason (or the exact snapshot of the transaction at the moment of the conflict matters) it's not a problem to include it in the event as well.

**Comment by tbg** [comment]
#58444 will address the bulk of the work here, sans the outcome. As far as I can tell (just talked this through with Nathan) the outcome is either

- some unknown hard error occurred (not much to do with those)
- WriteIntentError if WaitPolicy_ERROR was used
- the contending transaction was taken care of, i.e. it no longer is in the way via an intent or in-mem lock (though its writes may lead to our txn requiring a restart later)

Leaving this issue open to add the outcome enum later.

**Comment by tbg** [comment]
We produce metadata and while I said earlier that I wanted to leave the issue open to track improvements, I no longer consider that valuable. We can file new issues as we ship the current contention metadata and determine steps to improve them.
