### ISSUE TITLE
build  cockroachdb error ! 

### ISSUE THREAD

**Issue by triump2020** [cockroachdb/cockroach#55601]
Hi  all ,  when i follow this link :  [https://wiki.crdb.io/wiki/spaces/CRDB/pages/181338446/Getting+and+building+from+source](url)
to build source code ,  there is a error : 
![image](https://user-images.githubusercontent.com/63033222/96136627-6f96d400-0f2e-11eb-8c3d-a43e77745d03.png)

can anyone help me please ?

**Comment by jordanlewis** [comment]
What version of Go are you on? Come chat on the community slack if you still have issues.
