### ISSUE TITLE
cli: support for \connect to a different DB

### ISSUE THREAD

**Issue by ricardocrdb** [cockroachdb/cockroach#55613]
Requesting to add support for `\connect database` similar to `psql` format, to be used in addition to how `USE database` is currently used in CRDB.

**Comment by mneverov** [comment]
is this ticket about introducing an alias for `SET` (like `USE`) or should the full support of the \connect command be implemented?
```
\c or \connect [ -reuse-previous=on|off ] [ dbname [ username ] [ host ] [ port ] | conninfo ]
```

**Comment by adzimzf** [comment]
Hi, I'll to work on this,

**Comment by jordanlewis** [comment]
@mneverov, we can start just with an alias for `USE`. Changing the connection to a different host and port could be interesting, but I think it's used far less frequently than the simple alias.
