### ISSUE TITLE
sql: cockroach demo is less functional with secure mode

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#55632]
Cockroach Demo is meant to give developers and operators quick access to trying out cockroachdb. Now, on master, this is not the case. 

First, you need to create a log-in with a SQL user:
```SQL
CREATE USER craig WITH PASSWORD 'cockroach';
```
And now several pages will not work because you do not have admin access:
statements:
![image](https://user-images.githubusercontent.com/22278911/96262187-743fa480-0f8f-11eb-9688-3a84e0de016c.png)

Databases:
![image](https://user-images.githubusercontent.com/22278911/96262219-81f52a00-0f8f-11eb-9402-b143d219506b.png)

This reduces the effective nature of Cockroach Demo. 

If you pass the --insecure flag you get a warning about this being deprecated but everything works. 
```
Flag --insecure has been deprecated, to start a test server without any security, run start-single-node --insecure
For details, see: https://go.crdb.dev/issue-v/53404/v20.2
```
This warning doesn't really explain how to use demo and instead takes you to an overwhelming page that isn't relevant to trying out CockroachDB.

**Comment by knz** [comment]
@piyush-singh @awoods187 this is a side-effect of the "fine grained privilege", a.k.a "finer grained role options" work that went into 20.2. 

With this work in place, *any new non-admin user* (not just in `cockroach demo`) needs some of the new role options to have access to certain UI screens.

As per (upcoming) documentation, you can address that by either granting the `admin` role, or granting the finer-grained options, when creating the new user.

I would thus say the current behavior is working as specified.

For the purpose of `cockroach demo` the question could be -- do we want a demo-specific alternate behavior?

- on the one hand, I don't think it's realistic that demo users will run CREATE USER *at all*. So we may not need to care about this.
- on the second hand, if they do it's probably under guidance of our documentation. Our doc will tell them that they need special roles to access certain UI features. So in fact the current behavior is good for teaching.
- on the third hand (yes I have 3 hands here), Andy got surprised. If Andy got surprised maybe someone else will get surprised too? It would be good if @awoods187 could explain the origin of the surprise.

**Comment by knz** [comment]
I can also see you tried `CREATE USER craig`.

Was this pasted from the docs site? Maybe we need to update the doc examples that use `CREATE USER` inside `cockroach demo`. 

Is that a topic for @Amruta-Ranade?

**Comment by knz** [comment]
Related: #54877

**Comment by knz** [comment]
This has been addressed by having a `demo` user with admin privileges.
