### ISSUE TITLE
ui: opt-in banner confusion

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#5563]
Currently the opt-in banner says: `Check for updates and help us improve`. Why would the user want to opt-out of checking for updates? I can see why the user should need/want to opt-in to helping us improve, but checking for updates feels like it should be mandatory. In particular, if we discover an egregious security or data loss bug we will want the ability to notify them via the admin UI which will require a periodic check for updates from the admin UI.

I propose we simplify the opt-in banner text to: `Help us improve CockroachDB`. And the implementation should change so that we always check for updates, but only send cluster info if the user has opted-in.

**Comment by cuongdo** [comment]
Correct me if I'm wrong, @dt.

I believe the server implementation always checks for updates but only sends cluster info if the UI checkbox is checked. So, the bug here is only in the UI.

**Comment by dt** [comment]
That is correct -- currently every cluster checks for updates once per 24h
and, if it finds any, emits to `log.Warning` -- we should tie that in to
the UI though.

**Comment by maxlang** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/5569
