### ISSUE TITLE
ui: sessions and transactions pages not reporting permissions errors correctly

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#55631]
On master (V20.2.0-ALPHA.1-4118-GBB6C84F14D), using Cockroach Demo `./cockroach demo --nodes 9 --with-load` and launching of the webui:

The transactions page appears to be broken:
![image](https://user-images.githubusercontent.com/22278911/96261751-d64bda00-0f8e-11eb-88ba-02ee7745905e.png)

Sessions page also doesn't show up even with an explicit `BEGIN`:
![image](https://user-images.githubusercontent.com/22278911/96261793-e5328c80-0f8e-11eb-92e8-b5f57f063867.png)

**Comment by awoods187** [comment]
It looks like this could be in part related to https://github.com/cockroachdb/cockroach/issues/55632 as passing the --insecure flag shows each of these pages working

**Comment by knz** [comment]
it is indeed a dup of #55632

**Comment by awoods187** [comment]
Well it shouldn't look like this to non-admin users though. That's bad UX. It at least needs error messages like the other pages have: 
![image](https://user-images.githubusercontent.com/22278911/96296761-cdbec800-0fbd-11eb-825c-8b91b7bf0272.png)

**Comment by knz** [comment]
@piyush-singh that may be an observability issue then.  Ensuring that the right error pops up.

**Comment by knz** [comment]
cc @thtruo

**Comment by piyush-singh** [comment]
cc @dhartunian

Confirmed this in cockroach demo - the page does not load if I create a new user with:

`create user test with password test;`

But immediately shows up when I run:

`alter user test with viewactivity;`

**Comment by jordanlewis** [comment]
We think this might be done - @maryliag to check and close or fix.

**Comment by maryliag** [comment]
No longer an issue. There is the correct error message when the user doesn't have the permission
<img width="605" alt="Screen Shot 2021-04-08 at 12 06 06 PM" src="https://user-images.githubusercontent.com/1017486/114059962-e7511600-9862-11eb-8d50-6da10c739242.png">
