### ISSUE TITLE
Restores in 20.1: Restoring tables into cluster with different privileges may fail

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#55642]
Re https://github.com/cockroachlabs/support/issues/627

Restores fail due to inability to transition from OFFLINE to ONLINE state after restore runs almost to completion.
The purpose of this (high priority) issue is to figure out:

* potential impact on 20.1 customers.
* why we're seeing RESTOREs fail more than once.  Is the transaction issue very likely to occur?  Why?
* whether or not a fix can be backported to 20.1.

I think it has been fixed by https://github.com/cockroachdb/cockroach/commit/3423bb900f43e1cf1e54cf3589e574a72f7e798a, but still need to confirm root cause and from there determine potential impact.

**Comment by miretskiy** [comment]
20.1 is effected: If we restore table into a cluster that has a different set of privileges, and the restore itself
gets restarted (for whatever reason: node restart, etc), the restore job may fail due to inconsistency between
an inmemory descriptor representation and the KV one.

**Comment by dt** [comment]
we don't think 20.2 is affected
