### ISSUE TITLE
xform: cost for sort appears to mistreat constant factor

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#55650]
The cost definition for sort appears to include the estimated constant cost of the sort in the number of rows being processed, for multiplication with an estimated per-row cost, rather than a constant factor outside of that multiplication.

This seems unintended, but I'm not entirely sure.

https://github.com/cockroachdb/cockroach/blob/b3574ed2bc462f2c6eb5f316c9b209b38adde5b9/pkg/sql/opt/xform/coster.go#L547

**Comment by RaduBerinde** [comment]
Looks like it's intended, but it's a fairly sketchy formula. I'll send out a PR to clean it up.
