### ISSUE TITLE
gossip: why gossip update nodeDescs cache skip its own nodeDesc?

### ISSUE THREAD

**Issue by tusoft7** [cockroachdb/cockroach#5567]
In file cockroach/gossip/gossip.go, the fuanction updateNodeAddress,there is a code section:
// Skip if the node has already been seen or it's our own address.
	if _, ok := g.nodeDescs[desc.NodeID]; ok || desc.Address == g.is.NodeAddr {
		return
	}

I try to delete the filter,and let its own nodeDesc in.Then the benchmark test result showed obvious promote in performance,and I test other things,i have not found any mistake.
So my question is why it skip  its own address. I want to find out the logic behind it.

**Comment by tamird** [comment]
Can you post the benchmark results? Seems dubious to me that making this
method do more work can improve performance.

**Comment by tusoft7** [comment]
The test environment contains 9 cockroach nodes,and each node has 6 stores.My test command is very simple:
./cockroach benchmark txn --host=192.168.188.159 --port=9088 --ca-cert=ca.crt --cert=node.crt --key=node.key

this is the result berfore I remove the filter:
=================================
succeed commit Txns:           14466
failed Txns:            30
totol time(seconds):    20.022054
average lantency(ms):   27.672381
tps:                    722.503284
=================================
this is the result after I remove the filter:
=================================
succeed commit Txns:           16298
failed Txns:            0
totol time(seconds):    20.011222
average lantency(ms):   24.551320
tps:                    814.443017
=================================
the failed Txns also fall.

**Comment by tamird** [comment]
How many times did you run each benchmark? Was the cluster completely fresh
in both cases?

**Comment by tusoft7** [comment]
I run each case for many times.
And I restart the whole cluster and clean the store everytime.

**Comment by tusoft7** [comment]
Maybe I should expain my thought more clearly.
Also in file cockroach/gossip/gossip.go, in the other function getNodeDescriptorLocked,there is a code section:
if desc, ok := g.nodeDescs[nodeID]; ok {
		return desc, nil
	}
I think the nodeDescs cahe is used for promote performance.But if it refuse its own nodeDesc,the performance maybe fall.

**Comment by tamird** [comment]
Ah, seems you are right. Can you open a PR?

**Comment by bdarnell** [comment]
I think it's fine if the node adds its own address to `nodeDescs` in `updateNodeAddress`, but we still want to skip the rest of that method (`maybeAddResolver` and `maybeAddBootstrapAddress`).

**Comment by tusoft7** [comment]
I have open a PR "Fix gossip skip its own nodeDesc when updating nodeDescs cache #5791",please review.I'm looking forward your suggestion.
