### ISSUE TITLE
opt: table statistics should include information about the size of rows

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#55697]
Currently, the optimizer's statistics collector tracks the number of rows in a table, and histograms about the table's data distribution, but does not include information about the size of rows in a table.

This is troublesome for both costing and execution, because a row count estimate as exported by the optimizer is insufficient to make guesses about the amount of memory that a query might use, since rows are variably sized. The optimizer should collect, at minimum, an average data size per column as well, so that the coster and execution engine can make a guess at the amount of disk bytes that will be read by a query, and at the amount of memory that might need to be allocated for different parts of the query's execution.

There's a separate issue tracking optimizer changes: #72332

Epic: CRDB-10034

**Comment by RaduBerinde** [comment]
#46560 is one example where this would be very useful.

**Comment by RaduBerinde** [comment]
I think the issue tracks also using these values in the optimizer (if not, we should open an issue for that).

**Comment by rharding6373** [comment]
There's a separate issue tracking optimizer changes: https://github.com/cockroachdb/cockroach/issues/72332

**Comment by RaduBerinde** [comment]
Ah, thanks!
