### ISSUE TITLE
util: binfetcher can't handle lib directory

### ISSUE THREAD

**Issue by lucy-zhang** [cockroachdb/cockroach#55706]
`binfetcher` currently can't handle the `lib` directory included in our most recent release tarballs and will return an error `archive contains more than one file`.

This is currently blocking us from being able to run any of the mixed-version roachtests (which need to download a binary for the previous release), which itself is blocking us from being able to add a v21.1.0 tag, etc.

**Comment by jordanlewis** [comment]
@kenliu and @jlinder, this is an urgent problem. Not having mixed-version roachtests is a serious, blocking issue for the whole organization. Would you be able to get this done this week?

**Comment by lucy-zhang** [comment]
To be clear, when I said "any of the mixed-version roachtests" I meant for 20.2/21.1. All our release branches will be fine, and `master` is fine for now. But since `master` still counts as "20.2," we're likely going to start having problems with our existing mixed-version tests once we start introducing changes in 21.1 that are not compatible with 20.1.

**Comment by jordanlewis** [comment]
Thanks, Lucy. I think this problem is still severe, and needs attention - if we drop it now, it'll come back soon enough. Ken and James, do you have room to take this on?

**Comment by kenliu** [comment]
@jordanlewis If this is an urgent problem that blocks an upcoming release then we will give it a high priority to fix. Who else has the knowledge to assist with this if needed?

**Comment by jordanlewis** [comment]
Great! Lucy has recent context on the problem. Binfetcher is a very short program that was written by Tobi in 2017 judging from git blame.

**Comment by jordanlewis** [comment]
It lives in `pkg/util/binfetcher/binfetcher.go` in the CockroachDB repo.

**Comment by lucy-zhang** [comment]
I thought about this a bit more, and I don't think it's a good idea to have binfetcher handle this by just indiscriminately copying the `lib` directory wherever we put the cockroach binary (like I was originally thinking), since for mixed-version tests we might clobber the libraries for whatever current version we staged, among other potential issues.

@otan I figure you might have thoughts about how to handle this. What's the best way to download an earlier version of cockroach with the libraries so we can use it in the mixed-version tests? Could we just use `roachprod stage` (and make sure we preserve the contents of `lib` for each version)? Maybe I should ask that last question to a wider audience.

**Comment by lucy-zhang** [comment]
@otan and I discussed offline. It seems like we should be able to just use `roachprod stage release` into a separate directory to preserve each version's `lib` directory.

**Comment by kenliu** [comment]
thanks Lucy!

**Comment by jlinder** [comment]
> thanks Lucy!

➕
