### ISSUE TITLE
sql: renaming into a different database is supported for tables; but types, sequences, or schemas

### ISSUE THREAD

**Issue by jayshrivastava** [cockroachdb/cockroach#55712]
We can rename tables into different databases:
```
root@:26257/defaultdb> create database otherdb;
CREATE DATABASE

root@:26257/defaultdb> create table t1(i int PRIMARY KEY);
CREATE TABLE

root@:26257/defaultdb> alter table t1 rename to otherdb.public.t1;
NOTICE: renaming tables with a qualification is deprecated
HINT: use ALTER TABLE t1 RENAME TO t1 instead
RENAME TABLE
```

The issue is that there is inconsistency since we do not support renaming types, sequences, or schemas into other databases.

**Expected behavior**
We need to decide what renaming behaviour is desired and make it consistent when renaming tables, types, sequences, & schemas.

**Environment:**
 - CockroachDB version [e.g. 20.2]

**Comment by jayshrivastava** [comment]
Linking to https://github.com/cockroachdb/cockroach/issues/55712

**Comment by lucy-zhang** [comment]
Per #51445 I think the way we'll resolve this is by removing the ability to rename tables into a different database entirely. So I'm closing as a duplicate.
