### ISSUE TITLE
Casting backwards and forwards between ints and timestamps isin't symmetric

### ISSUE THREAD

**Issue by rhysmdnz** [cockroachdb/cockroach#55726]
**Describe the problem**

Casting backwards and forwards between ints and timestamps isin't symmetric

**To Reproduce**

What did you do? Describe in your own words.

```

root@:26257/thing> SELECT CAST(31536000 as INTERVAL);
    interval
-----------------
  1 year 5 days
(1 row)

Time: 242.949µs
root@:26257/thing> SELECT CAST(INTERVAL '1 year' as INT);
    int8
------------
  31557600
(1 row)

Time: 286.063µs

root@:26257/tiaki> SELECT CAST(CAST(31536000 as INTERVAL) as INT);
    int8
------------
  31989600
(1 row)

Time: 292.869µs
```

**Expected behavior**
The first interval should be slightly under one year (365 days in seconds)

In general casting backwards and forwards between a number of seconds as an INT and an interval should end up with the same periods if time.

**Environment:**
 - CockroachDB version 20.1.7

Jira issue: CRDB-3641

**Comment by solongordon** [comment]
Note that Postgres doesn't support casts between INT and INTERVAL. But we should investigate why this isn't round-tripping.

**Comment by arctica** [comment]
The core issue causing this I believe is #57876

**Comment by otan** [comment]
indeed, closing as duplicate
