### ISSUE TITLE
sql: expose always-on tracing inflight registry using vtable and builtins

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#55733]
**Is your feature request related to a problem? Please describe.**
As part of always-on tracing, a node-local registry of inflight operations will be introduced (#55592). This registry would be most useful if it could be queried from SQL.

This would improve our troubleshooting story as we could filter on long-running KV trace spans in that table to easily detect hanging operations (unavailable range, heavy contention) in a self-service fashion.

**Describe the solution you'd like**
Introduce a virtual table `crdb_internal.tracing_inflight` (big question mark on the name) that pulls the node-local registry from all nodes in the cluster.

Add a view on that table that also translate (where possible) KV txn id -> SQL txn ID to allow filtering efficiently.

**Describe alternatives you've considered**

**Additional context**

**Comment by tbg** [comment]
For starters, we should probably align closely with the schema of `crdb_internal.session_tracing`:

https://github.com/cockroachdb/cockroach/blob/f4b475a97618755284e6a70d8626c8266ce145fd/pkg/sql/crdb_internal.go#L1103-L1132

However, since all spans are unfinished, we will want the duration column to be populated with `time.Since(spanStart)`. This might mean that we need to change `(Span).GetRecording()`; I believe at the moment `duration` is returned as `-1` for unfinished `Span`s.

**Comment by tbg** [comment]
Discussed in pod: we'll go with a vtable that lists only the spans + some of their metadata (not their recordings) that in particular allows identifying a span as long-running, and then add a builtin that renders a session tracing like table for a particular traceID.

**Comment by tbg** [comment]
https://github.com/cockroachdb/cockroach/pull/59370 shows that there is value in adding a check on this vtable to roachtest. We'd fail the test if the vtable shows any long-running local root spans that have children attached to them.

**Comment by irfansharif** [comment]
For posterity, what's remaining here are built-ins that:
1. get the traceid/spanid of the currently open txn (if any)
2. renders the payloads (just payloads) given a traceid/spanid

**Comment by angelapwen** [comment]
Status update here:

@tbg added a builtin that retrieves the current trace ID as part of #59992.
We are holding off on adding a builtin that retrieves the current span ID until we see a use case for it.

I added a builtin that, given a span ID, displays a table representing all its payloads with columns for payload type and entire payload as JSONB #60784 

What's left is adding functionality (via a SQL query delegate mechanism) to display a table representing all payloads for a given trace ID as that will be easier to use.

**Comment by angelapwen** [comment]
The builtin displaying all payloads for a given trace ID has been added (#60992) and logic test improved as part of the same PR. Closing out this issue for now 🎉
