### ISSUE TITLE
CDC: enable CDC to emit data only for specific geo-partition

### ISSUE THREAD

**Issue by mikeczabator** [cockroachdb/cockroach#55741]
**Is your feature request related to a problem? Please describe.**
Customer wants to emit data from CDC for specific geo-regions. 

**Describe the solution you'd like**
emit data from CDC for each geo region

**Additional context**
As per customer:

Can we somehow separate the data emitted by CDC per geo-location, for example? Possibly to different Kafka clusters, one per geo-location?

Jira issue: CRDB-3637

**Comment by mikeczabator** [comment]
Link back to Zendesk ticket: https://cockroachdb.zendesk.com/agent/tickets/6577

**Comment by mwang1026** [comment]
Rescoping this to be just to *filter* the changefeed to just emit data for a specified *partition*

**Comment by miretskiy** [comment]
Closing -- supported by changefeed expressions.
