### ISSUE TITLE
sql: create event log entry for schema events

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#55744]
**Is your feature request related to a problem? Please describe.**
There is likely a broader issue around systematically ensuring that we event log entries for all of the relevant events. Specifically I notice that these are missing.

**Comment by jordanlewis** [comment]
Hey @neeral, I closed the other general issue as it was quite old and out of date at this point. But, I think that user-defined schemas and types are also missing these events. Would you be interested in doing a follow-up PR to your last one that adds events for schema and type events?

@ajwerner would you fill in details about which events we need to add here, thanks!

**Comment by neeral** [comment]
Sure @jordanlewis , I'd be happy to help further. I'll wait for @ajwerner to fill out the details of the remaining events.

**Comment by ajwerner** [comment]
It seems we do have the type events. The needed schema events are:

* `CREATE SCHEMA`
* `DROP SCHEMA`
* `ALTER SCHEMA`

Outside of schemas I notice we're missing some other events. Let's start with the schema events

* `ALTER DATABASE`
* `CREATE ROLE
* `DROP ROLE`
* `ALTER ROLE`
