### ISSUE TITLE
backup: full cluster restore is difficult to use on clusters which previously contained data

### ISSUE THREAD

**Issue by DuskEagle** [cockroachdb/cockroach#55743]
Full cluster restore is difficult to use on existing clusters today in a couple of situations:

* If a database `foo` exists on the cluster, before performing a restore you must first `DROP DATABASE foo`. However, you will still not be able to restore to the cluster until the GC TTL on the zone of the dropped database has elapsed. So before dropping the database, you must `ALTER DATABASE foo CONFIGURE ZONE USING gc.ttlseconds=10`, to cause the TTL to elapse quickly. If you forget to do this before dropping the database, there is no easy way to change the TTL afterwards. This means you may have to wait up to 25 hours (assuming a default value for `gc.ttlseconds`) before attempting a full cluster restore on the cluster.
* If a previous full cluster restore failed, it is very difficult to attempt another full restore on the same cluster. You may have to wait up to 25 hours for the GC to run on all zones, and in addition, you have to make sure the previous failed restore did not leave behind any tables/databases.

In practice, this means that we often find ourselves having to wipe the disks of a cluster before we restore. This is inconvenient because we then have to rerun the `cockroach init` command, generate a new license key, create certain SQL users, apply cluster settings, etc. (A playbook for this op is located at https://github.com/cockroachlabs/production/wiki/Wipe-a-cluster).

It would be very nice if full cluster restores were easier to start on existing clusters. As a strawman, a full cluster restore could be allowed if all databases had been dropped from a cluster, regardless of whether the GC TTL had run. In the case of a failed restore, clearer instructions on how to get the cluster into a state where a second restore could be attempted would be very helpful.

**Comment by mwang1026** [comment]
@DuskEagle in the future for Bulk IO stuff can you flag in the `Bulk I/O Backlog` project rather than assigning to me? That way our whole team sees it.

Also, we have https://github.com/cockroachdb/cockroach/issues/54505 planned for 21.1 to address this exact issue. Does that solve the problem in your eyes?

**Comment by DuskEagle** [comment]
> @DuskEagle in the future for Bulk IO stuff can you flag in the Bulk I/O Backlog project rather than assigning to me? That way our whole team sees it.

Absolutely, I'll do that in the future.

#54505 looks perfect to solve the problem. I tried to find if there was an existing issue for this, but missed that issue. I think we can mark this issue as a duplicate.
