### ISSUE TITLE
Schema change GC jobs should not fail silently

### ISSUE THREAD

**Issue by spaskob** [cockroachdb/cockroach#55740]
Schema change that fail silently leave data that is not garbage collected.  We should investigate how many schema change jobs fail in the wild and act accordingly by perhaps examining return paths that return errors that may be transient and retry instead.

Jira issue: CRDB-3638

**Comment by spaskob** [comment]
Perhaps we should collect events any time a GC job has failed or canceled by adding reporting code in `OnFailOrCancel`.

**Comment by lucy-zhang** [comment]
The current thinking is that we should just always retry in GC jobs and err on the side of futilely retrying forever rather than give up. Or we could use the permanent/retriable error classification in the schema change job as a starting point.

**Comment by postamar** [comment]
Correct me if I'm wrong but since they're now always being retried, this issue is no longer relevant. Closing.
