### ISSUE TITLE
cli: movr demo has no table statistics initially

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#55757]
When running `cockroach demo`, we have the `movr` dataset preloaded. But there are no table statistics preloaded. This can lead to unexpected query plans. In 20.2 onward, EXPLAIN will show "missing stats" for any scans, which will raise questions for users.

The auto stats do kick in, but it takes a minute or two. It would be great if we could preload (inject) statistics, or run `CREATE STATISTICS` for all tables as part of initialization.

Jira issue: CRDB-3635

**Comment by RaduBerinde** [comment]
As a datapoint, #55752 was filed by a user looking at EXPLAIN on the movr demo.

**Comment by awoods187** [comment]
Heavy +1 on adding this functionality.

**Comment by tharun208** [comment]
@RaduBerinde I like to work on this.
