### ISSUE TITLE
stability: stability issues (queue.go:444, context.go:168,store.go:1864)

### ISSUE THREAD

**Issue by Linicks** [cockroachdb/cockroach#5576]
All,
  I just wanted to share that I've had a hard time keeping my test cluster(s) up for over 24 hours at a time.  I know that things are under heavy development, so I haven't shared the failures previously, but felt that this little bit of information may be helpful in resolving the issues.  Here is the basic information:  

------------------------------------------------

Build Vers:  go1.6
Build Tag:   alpha.v1-1379-g20d21c1
Build Time:  2016/03/24 19:30:54

------------------------------------------------

E160325 00:36:08.116008 storage/queue.go:444  [split] range=21 [/System/"tsd\x12cr.node.exec.error-count\x00\x01\x89\xf8\x06.\xf81"-/System/"update-report"): error: storage/replica_command.go:1694: split at key /System/"update-report" failed: unexpected value: raw_bytes:"l!E\317\003\010\000\020\007\030\307\367\001\"\376\t\000/\213\333\263J5\246(\010\001\022\006\010\003\020\003\030\003\032\350\t\n;\n\014\010\367\234\365\265\324\204\277\237\024\020\000\022\006\010\003\020\003\030\003\030\001!\000\000\000\000\000\000\000\0000\000:\024\010\300\304\353\356\367\301\313\255D\020\366\332\274\222\204\211\210\271s@\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022i\222\001f\n5\0323\004tsd\022cr.node.clock-offset.lower-bound-nanos\000\001\211\370\006.\3742\022-\n%\000\000\000\000d\010\200\200\366\223\316\305\276\237\024\020\200\310\257\240%\032\016\010\330\0010\0019\000\000\000\360u\320\255\301\022\004\010\000\020\000\022i\222\001f\n5\0323\004tsd\022cr.node.clock-offset.upper-bound-nanos\000\001\211\370\006.\3742\022-\n%\000\000\000\000d\010\200\200\366\223\316\305\276\237\024\020\200\310\257\240%\032\016\010\330\0010\0019\000\000\000\234o\321\255A\022\004\010\000\020\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022Y\222\001V\n%\032#\004tsd\022cr.node.exec.error-10m\000\001\211\370\006.\3742\022-\n%\000\000\000\000d\010\200\200\366\223\316\305\276\237\024\020\200\310\257\240%\032\016\010\330\0010\0019p\377\343\3362a\262?\022\004\010\000\020\000\022\003\312\001\000\022X\222\001U\n$\032\"\004tsd\022cr.node.exec.error-1m\000\001\211\370\006.\3742\022-\n%\000\000\000\000d\010\200\200\366\223\316\305\276\237\024\020\200\310\257\240%\032\016\010\330\0010\0019\330s\303\035.X\343?\022\004\010\000\020\000\022X\222\001U\n$\032\"\004tsd\022cr.node.exec.error-1h\000\001\211\370\006.\3742\022-\n%\000\000\000\000d\010\200\200\366\223\316\305\276\237\024\020\200\310\257\240%\032\016\010\330\0010\0019\205\313\330\\\302;\217?\022\004\010\000\020\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000\022\003\312\001\000" timestamp:<wall_time:0 logical:0 > 
E160325 00:36:08.818485 storage/queue.go:444  [split] range=21 [/System/"tsd\x12cr.node.exec.error-count\x00\x01\x89\xf8\x06.\xf81"-/System/"update-report"): error: storage/replica_command.go:1694: split at key /System/"update-report" failed: unexpected value: raw_bytes:"s\370\030\022\003\010\025\022%\004tsd\022cr.node.exec.error-count\000\001\211\370\006.\3701\032\016\004update-report\"\006\010\001\020\001\030\001\"\006\010\002\020\002\030\002\"\006\010\003\020\003\030\003(\004" timestamp:<wall_time:1458880474113983387 logical:0 > 
E160325 00:37:13.618901 rpc/context.go:168  rpc error: code = 4 desc = "context deadline exceeded"
E160325 00:37:16.980731 rpc/context.go:168  rpc error: code = 4 desc = "context deadline exceeded"
E160325 00:37:16.570320 rpc/context.go:168  rpc error: code = 4 desc = "context deadline exceeded"
E160325 00:37:17.995858 rpc/context.go:168  rpc error: code = 4 desc = "context deadline exceeded"
E160325 00:37:18.633531 rpc/context.go:168  rpc error: code = 4 desc = "context deadline exceeded"
E160325 00:37:18.760815 rpc/context.go:168  rpc error: code = 4 desc = "context deadline exceeded"
E160325 00:37:18.871739 rpc/context.go:168  rpc error: code = 4 desc = "context deadline exceeded"
E160325 00:37:18.880992 rpc/context.go:168  rpc error: code = 4 desc = "context deadline exceeded"
E160325 00:37:19.467491 rpc/context.go:168  rpc error: code = 4 desc = "context deadline exceeded"
E160325 00:37:20.138803 rpc/context.go:168  rpc error: code = 4 desc = "context deadline exceeded"
E160325 00:37:26.757380 rpc/context.go:168  rpc error: code = 4 desc = "context deadline exceeded"
E160325 00:37:27.840317 rpc/context.go:168  rpc error: code = 4 desc = "context deadline exceeded"
E160325 00:37:29.827495 rpc/context.go:168  rpc error: code = 4 desc = "context deadline exceeded"
E160325 00:41:50.585076 storage/store.go:1864  error handling raft message: raft: cannot step as peer not found
E160325 00:41:50.597865 storage/store.go:1864  error handling raft message: raft: cannot step as peer not found
E160325 00:41:50.614541 storage/store.go:1864  error handling raft message: raft: cannot step as peer not found
E160325 00:41:50.628991 storage/store.go:1864  error handling raft message: raft: cannot step as peer not found
E160325 05:45:57.378568 storage/raft_transport.go:246  rpc error: code = 13 desc = "transport: write tcp 127.0.0.1:54918->127.0.1.1:26258: write: connection reset by peer"

-- Nick

**Comment by tamird** [comment]
@Linicks be aware that we have been breaking the on-disk format in this pre-beta period. Some of those errors look like you're running new code against old data, and it can't deal.

Please be sure to clear your on-disk data each time you upgrade CockroachDB (at least until we announce beta).

**Comment by Linicks** [comment]
@tamird, I've observed the on-disk changes while working with the pre-beta code and reading the changelog.  Because of the regular disk format changes, I've adopted the practice of completely removing all of Cockroachdbs source, binaries, stores, etc, every time I do a new build.  I will typically do a new build every one to two days, depending on what I'm working on.  Then I just follow the Quick Start in the Read me, and go from there.

**Comment by tamird** [comment]
@Linicks could you provide some additional information? How many nodes were you running, what kind of load was applied, how long did it take for these errors to appear, was the cluster still responsive during this time?

**Comment by Linicks** [comment]
@tamird I've removed and replaced the build that I originally posted this issue with, but have continued to have stability issues with a newer build.  With both of these builds I was running a three node cluster on the same host with the insecure option, as described in the Quick Start in the read me.  The builds are responsive for several hours after the build and initial startup, then seem to self destruct after idling for some time.  I left my last build after work on Friday, and it died sometime during the weekend.  Upon seeing this update to the issue I  attempted to restart the cluster and noticed some memory related issues.  When I started the cluster for the first time, I didn't have any memory errors, and it worked just fine for several hours while working to get the Elixir/Prostgrex driver to work.  Now I'm getting runtime/memory errors.  I'm going to do a clean rebuild from today's current master and see if I continue see the memory issues.  

Here are some of the details from my last build:

--------------------------

 build:     alpha.v1-1423-ga8c1cb4 @ 2016/03/25 18:03:44 (go1.6)

--------------------------
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily

--------------------------
4.2.0-34-generic #39-Ubuntu SMP Thu Mar 10 22:13:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

--------------------------

E160328 17:24:53.101413 rpc/context.go:168  rpc error: code = 4 desc = "context deadline exceeded"
E160328 17:25:03.563133 rpc/context.go:168  rpc error: code = 4 desc = "context deadline exceeded"
E160328 17:25:03.756093 rpc/context.go:168  rpc error: code = 4 desc = "context deadline exceeded"

---------------------------

cat /proc/meminfo 
MemTotal:        1016740 kB
MemFree:          690656 kB
MemAvailable:     740296 kB

----------------------------

fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x18779a0, 0x16)
	/root/.gvm/gos/go1.6/src/runtime/panic.go:530 +0x90
runtime.sysMap(0xc83fee0000, 0x92e0000, 0x0, 0x25364b8)
	/root/.gvm/gos/go1.6/src/runtime/mem_linux.go:206 +0x9b
runtime.(*mheap).sysAlloc(0x2512520, 0x92e0000, 0x2839ee7660)
	/root/.gvm/gos/go1.6/src/runtime/malloc.go:429 +0x191
runtime.(*mheap).grow(0x2512520, 0x4970, 0x0)
	/root/.gvm/gos/go1.6/src/runtime/mheap.go:651 +0x63
runtime.(*mheap).allocSpanLocked(0x2512520, 0x4970, 0x1e)
	/root/.gvm/gos/go1.6/src/runtime/mheap.go:553 +0x4f6
runtime.(*mheap).alloc_m(0x2512520, 0x4970, 0x100000000, 0x139baa0)
	/root/.gvm/gos/go1.6/src/runtime/mheap.go:437 +0x119
runtime.(*mheap).alloc.func1()
	/root/.gvm/gos/go1.6/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0x7fff39ee7770)
	/root/.gvm/gos/go1.6/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x2512520, 0x4970, 0x10100000000, 0xc82001e000)
	/root/.gvm/gos/go1.6/src/runtime/mheap.go:503 +0x63
runtime.largeAlloc(0x92dfff0, 0xc800000000, 0x61c300)
	/root/.gvm/gos/go1.6/src/runtime/malloc.go:766 +0xb3
runtime.mallocgc.func3()
	/root/.gvm/gos/go1.6/src/runtime/malloc.go:664 +0x33
runtime.systemstack(0x250a200)
	/root/.gvm/gos/go1.6/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/root/.gvm/gos/go1.6/src/runtime/proc.go:1048

goroutine 63 [running]:
runtime.systemstack_switch()
	/root/.gvm/gos/go1.6/src/runtime/asm_amd64.s:245 fp=0xc820108610 sp=0xc820108608
runtime.mallocgc(0x92dfff0, 0x169ffe0, 0x0, 0x80)
	/root/.gvm/gos/go1.6/src/runtime/malloc.go:665 +0x9eb fp=0xc8201086e8 sp=0xc820108610
runtime.newarray(0x169ffe0, 0x20a38e, 0x0)
	/root/.gvm/gos/go1.6/src/runtime/malloc.go:798 +0xc9 fp=0xc820108728 sp=0xc8201086e8
runtime.growslice(0x13c2da0, 0xc838960000, 0x1a1c71, 0x1a1c71, 0x1a1c72, 0x0, 0x0, 0x0)
	/root/.gvm/gos/go1.6/src/runtime/slice.go:100 +0x2c1 fp=0xc820108798 sp=0xc820108728
github.com/cockroachdb/cockroach/storage.(*Replica).entries.func1(0xc831485f70, 0x10, 0x10, 0xc8314a2480, 0x7b, 0x80, 0x0, 0x0, 0xc800000000, 0x0, ...)
	/root/.gvm/pkgsets/go1.6/global/src/github.com/cockroachdb/cockroach/storage/replica_raftstorage.go:110 +0x235 fp=0xc820108858 sp=0xc820108798
github.com/cockroachdb/cockroach/storage/engine.MVCCIterate(0x7f0462e5f580, 0xc8202aaa80, 0xc82014b2e0, 0x10, 0x20, 0xc82014b300, 0x10, 0x20, 0x0, 0x0, ...)
	/root/.gvm/pkgsets/go1.6/global/src/github.com/cockroachdb/cockroach/storage/engine/mvcc.go:1337 +0xaee fp=0xc820108cb8 sp=0xc820108858
github.com/cockroachdb/cockroach/storage.(*Replica).entries(0xc8200c1ea0, 0x7f0462e5f580, 0xc8202aaa80, 0xf2b, 0x1efb17, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, ...)
	/root/.gvm/pkgsets/go1.6/global/src/github.com/cockroachdb/cockroach/storage/replica_raftstorage.go:120 +0x436 fp=0xc820108ec0 sp=0xc820108cb8
github.com/cockroachdb/cockroach/storage.(*Replica).Entries(0xc8200c1ea0, 0xf2b, 0x1efb17, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.6/global/src/github.com/cockroachdb/cockroach/storage/replica_raftstorage.go:86 +0xa7 fp=0xc820108f30 sp=0xc820108ec0
github.com/coreos/etcd/raft.(*raftLog).slice(0xc8201d89a0, 0xf2b, 0x1efb17, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.6/global/src/github.com/coreos/etcd/raft/log.go:307 +0x195 fp=0xc820109070 sp=0xc820108f30
github.com/coreos/etcd/raft.(*raftLog).entries(0xc8201d89a0, 0xf2b, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.6/global/src/github.com/coreos/etcd/raft/log.go:248 +0xbf fp=0xc8201090c0 sp=0xc820109070
github.com/coreos/etcd/raft.(*raft).becomeLeader(0xc820242900)
	/root/.gvm/pkgsets/go1.6/global/src/github.com/coreos/etcd/raft/raft.go:485 +0x152 fp=0xc820109270 sp=0xc8201090c0
github.com/coreos/etcd/raft.stepCandidate(0xc820242900, 0x6, 0x3, 0x1, 0x2b, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/.gvm/pkgsets/go1.6/global/src/github.com/coreos/etcd/raft/raft.go:712 +0xc0e fp=0xc820109600 sp=0xc820109270
github.com/coreos/etcd/raft.(*raft).Step(0xc820242900, 0x6, 0x3, 0x1, 0x2b, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/.gvm/pkgsets/go1.6/global/src/github.com/coreos/etcd/raft/raft.go:564 +0x3e0 fp=0xc820109750 sp=0xc820109600
github.com/coreos/etcd/raft.(*RawNode).Step(0xc82027a380, 0x6, 0x3, 0x1, 0x2b, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/.gvm/pkgsets/go1.6/global/src/github.com/coreos/etcd/raft/rawnode.go:175 +0x19d fp=0xc820109a70 sp=0xc820109750
github.com/cockroachdb/cockroach/storage.(*Store).handleRaftMessage(0xc820350900, 0xc8205a05a0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.6/global/src/github.com/cockroachdb/cockroach/storage/store.go:1811 +0x575 fp=0xc820109c48 sp=0xc820109a70
github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1()
	/root/.gvm/pkgsets/go1.6/global/src/github.com/cockroachdb/cockroach/storage/store.go:1868 +0x525 fp=0xc820109f60 sp=0xc820109c48
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82029d500, 0xc820280940)
	/root/.gvm/pkgsets/go1.6/global/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52 fp=0xc820109f80 sp=0xc820109f60
runtime.goexit()
	/root/.gvm/gos/go1.6/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820109f88 sp=0xc820109f80
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/root/.gvm/pkgsets/go1.6/global/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 1 [select]:
github.com/cockroachdb/cockroach/cli.runStart(0x2230280, 0xc8202a8500, 0x0, 0x5, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.6/global/src/github.com/cockroachdb/cockroach/cli/start.go:190 +0x2167
github.com/spf13/cobra.(*Command).execute(0x2230280, 0xc8202a84b0, 0x5, 0x5, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.6/global/src/github.com/spf13/cobra/command.go:565 +0x62c
github.com/spf13/cobra.(*Command).ExecuteC(0x222ce80, 0x2230280, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.6/global/src/github.com/spf13/cobra/command.go:656 +0x55c
github.com/spf13/cobra.(*Command).Execute(0x222ce80, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.6/global/src/github.com/spf13/cobra/command.go:615 +0x2d
github.com/cockroachdb/cockroach/cli.Run(0xc82000a0f0, 0x6, 0x6, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.6/global/src/github.com/cockroachdb/cockroach/cli/cli.go:81 +0x7c
main.main()
	/root/.gvm/pkgsets/go1.6/global/src/github.com/cockroachdb/cockroach/main

..... The errors continue for more go-routines..

-- Nick

**Comment by tamird** [comment]
Thanks, @Linicks. Consider using https://github.com/maruel/panicparse to produce a more readable crash summary.

There have been a few OOM bugs fixed in the past week - let us know if this comes back.

**Comment by mberhault** [comment]
@Linicks: Peter just tweaked the memory settings for rocksdb to be much lower (#5637 and #5641). Before that, an active node by itself could easily fill up a single machine's memory. The memtable and block cache have been reduced a lot and should let a single node be happy for much longer (with manual reduction through the `--cache` flag, I'm at a few days with heavy load).

Be aware that some of those settings (especially the block cache size) are based on the machine's memory capacity, so running more than one node may still go OOM.

You can further limit the block cache size by setting `--cache` on the cockroach binary. Other settings are not so easily modifyable. I would recommend setting `--cache` to a quarter of the memory you want a single process to take, so if you're running three of them: `(available_memory / 4) / 3`

**Comment by Linicks** [comment]
@tamird, Thanks for pointing me to panicparse, I will try it next time I have a crash.

@mberhault,  The build that I started based on the March 28 master branch build has been stable under a very low load to idle conditions for a full 24hrs.  I started each node with the --cache option and calculated it's size  with the (available_memory / 4) / 3 method.  I'm going to do a new build, and test again.   Here's this build and cache details:

---------------------------------------------

Build Vers:  go1.6
Build Tag:   alpha.v1-1501-g1a17919
Build Time:  2016/03/28 22:13:38

--------------------------------------------

Example Start command with cache option:

./cockroach start --insecure --cache=79790 --store=cockroach-data2 --port=26258 --http-port=8081 --join=localhost:26257 &

**Comment by Linicks** [comment]
All,
  Here is an error printed to standard out from my last build.  It targets storage/queue.go:446 and storage/replica_command.go:1731.  I realize that these errors are out of the scope of the original report, but I don't want to add a new issue for each crash/error that I get when testing.  I just want to report my findings as I work with Cockroachdb. Please let me know if you want me change this practice.  

Thanks!
-- Nick

--------------------------------------------------

Build Vers:  go1.6
Build Tag:   beta-20160328-4-g30636bb
Build Time:  2016/03/29 22:34:07


--------------------------------------------------

E160330 13:39:15.700690 storage/queue.go:446  [split] range=1 [/Min-/System/"tsd\x12cr.node.txn.durations-1h-max\x00\x01\x89\xf8\x06/w2"): error: storage/replica_command.go:1731: split at key /System/"tsd\x12cr.node.txn.durations-1h-max\x00\x01\x89\xf8\x06/w2" failed: unexpected value: raw_bytes:"\tP\375\246\003\010\001\022\000\032)\004tsd\022cr.node.txn.durations-1h-max\000\001\211\370\006/w2\"\006\010\001\020\001\030\001\"\006\010\002\020\002\030\002\"\006\010\003\020\003\030\003(\004" timestamp:<wall_time:1459359548005986598 logical:0 >

**Comment by tamird** [comment]
Tracked in #5629.

**Comment by tamird** [comment]
Doesn't look like there's anything actionable here at this time.
