### ISSUE TITLE
opt: update test output to convert `inverted-lookup` join to `inverted` join

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#55765]
In most places the join is simply referred to as an "inverted" join, but in the datadriven test output it is referred to as inverted-lookup. This output should be updated to be consistent with the rest of the code.

**Comment by mneverov** [comment]
hi, i'd like to work on this

**Comment by rytaft** [comment]
Thanks, @mneverov! I've just approved your PR. Thank you for contributing!
