### ISSUE TITLE
changefeedccl: support SCRAM-SHA-256 and SCRAM-SHA-512 sasl authentication mechanisms

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#55788]
**Is your feature request related to a problem? Please describe.**

The Confluent Platform (see [here](https://docs.confluent.io/current/kafka/authentication_sasl/authentication_sasl_scram.html#sasl-scram-overview)) and MKS (see [here](https://aws.amazon.com/msk/faqs/)) support SASL authentication using a [SCRAM](https://tools.ietf.org/html/rfc5802) protocol. We currently only support the `PLAIN` SASL mechanism. On MKS, it appears that password authentication requires this mechanism.  

**Describe the solution you'd like**

We should support a new `sasl_mechansim` which would allow the client to specify an alternative to `PLAIN`. 

**Describe alternatives you've considered**

Both MKS and Confluent Platform support certificate based authentication. That can be utilized to build secure authentication but may not be advisable for practical reasons or other issues regarding key management and revocation.

**Comment by amruss** [comment]
Closing due to https://github.com/cockroachdb/cockroach/pull/60150

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/scram-xmpp/info/issues/1
- https://github.com/cockroachdb/cockroach/issues/42519
- https://github.com/cockroachdb/cockroach/issues/55788
- https://github.com/cockroachdb/cockroach/pull/60150
- https://github.com/cockroachdb/cockroach/issues/74300
- https://github.com/cockroachdb/cockroach/pull/74301
