### ISSUE TITLE
SQL syntax error when using column alias on raw string data

### ISSUE THREAD

**Issue by ronan696** [cockroachdb/cockroach#55826]
**Describe the problem**

Having a column alias for a raw string data returns an SQL syntax error when the _as_ keyword is not used. Works as expected when _as_ keyword is used.

**To Reproduce**

1. Run CockroachDb single cluster using `cockroach start-single-node --insecure`
2. Connect to Db using `cockroach sql --insecure`
3. Run query `select 1 id, 100 amount, 'new' status;`
4. Following is the error seen
```
invalid syntax: statement ignored: at or near "status": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
select 1 id, 100 amount, 'new' status
                               ^
```

**Expected behaviour**
Following is expected outcome (which can be obtained by with query `select 1 id, 100 amount, 'new' as status;`)
```
  id | amount | status
-----+--------+---------
   1 |    100 | new
(1 row)

Time: 1.292187ms
```

**Additional data / screenshots**
![Screenshot from 2020-10-21 23-28-32](https://user-images.githubusercontent.com/13074003/96759151-488c4680-13f5-11eb-91e8-31131d3c27e2.png)

**Environment:**
 - CockroachDB version: v20.1.7
 - Server OS: Ubuntu 20.04
 - Client app: cockroach sql

**Comment by mattcrdb** [comment]
cc @solongordon

**Comment by rafiss** [comment]
Looked into this further. The problem is not that raw string data can't be aliased this way. The issue was with the `status` alias. `STATUS` is a special word in our grammar, so it can't be used this way.

Workarounds are:

```
root@:26257/defaultdb> select 1 id, 100 amount, 'new' my_status;
  id | amount | my_status
-----+--------+------------
   1 |    100 | new
```

Or as you already mentioned:

```
root@:26257/defaultdb> select 1 id, 100 amount, 'new' as status;
  id | amount | status
-----+--------+---------
   1 |    100 | new
```

**Comment by ronan696** [comment]
@rafiss, Thanks for sharing this info.
