### ISSUE TITLE
sql: incorrect physical planning of aggregation functions when some of them have DISTINCT clause

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#55837]
In some cases, we can incorrectly perform a distinct local stage that will discard tuples that are needed by other aggregate functions.
```
# LogicTest: 5node

statement ok
CREATE TABLE t55837 (
  i  int primary key,
  y  float,
  x  float
);
INSERT INTO t55837 (i, y, x) VALUES
  (1, 1.0,   1),
  (2, 1.0,   1),
  (3, 2.0,   3),
  (4, 3.0,   3);
ALTER TABLE t55837 SPLIT AT VALUES (3);
ALTER TABLE t55837 EXPERIMENTAL_RELOCATE VALUES (ARRAY[3], 2);
SELECT * FROM t55837 -- make sure that the range cache is populated

query FI
SELECT corr(DISTINCT y, x), count(y) FROM t55837
----
0.866025403784439 4
```
This bug has been present since forever.

**Comment by jordanlewis** [comment]
@yuzefovich nice find, what is the expected behavior here?

**Comment by yuzefovich** [comment]
The issue is that we mistakenly plan a "local" stage of distinct processors, and as a result `count` aggregate might not see all of the necessary tuples - in effect, we mistakenly apply `DISTINCT y, x` clause to `count` function as well which doesn't have the DISTINCT.

The problem is because of this loop https://github.com/cockroachdb/cockroach/blob/2385a186778293a6b9e89b9e1edb74077d8f4eae/pkg/sql/distsql_physical_planner.go#L1447-L1461
namely because of `break` in case of a function that cannot be computed in a distributed manner. We exit the loop too early without correctly computing `allDistinct` variable.
