### ISSUE TITLE
ui: rename active sessions page to sessions

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#55868]
After some discussion ([context](https://cockroachlabs.slack.com/archives/C0159JK877C/p1600208662030600)) we agreed that we should rename the active session page to sessions to avoid confusion about whether the page shows session without transaction that are currently executing.

Creating this issue to track this request from Alex E.

cc @taroface

**Comment by awoods187** [comment]
I mentioned this on Slack but I think we should merge this ASAP and put it in the first possible release (either the next RC or 20.2.1).
