### ISSUE TITLE
Option to replicate a small table across all nodes

### ISSUE THREAD

**Issue by mgoldgeier** [cockroachdb/cockroach#55898]
**Is your feature request related to a problem? Please describe.**
Our schema is such that we have a few very large tables that we query on and almost always will want to join on a smaller metadata table. The large tables of course span many ranges, but the metadata table only falls into 1 or 2 ranges unless I split it manually. While I'm currently looking at splitting it manually to more evenly distribute load, it seems like a useful configuration option would be to allow such small (and infrequently updated) tables to be replicated in full across all nodes. In this case, it might reduce the need to hop to retrieve data from other nodes and improve performance. While possible to manually set the data to replicate to the node count, that is fragile if cluster size changes.

**Describe the solution you'd like**
A configurable option on a table to tell the cluster to replicate this table across all nodes.

**Describe alternatives you've considered**
Alternative solutions to improve performance are: Use split at command to distribute the load, but that doesn't really solve the problem. As noted, can also manually set the replication factor to force the table to replicate across all nodes, but doing that manually is fragile.

**Additional context**

**Comment by rafiss** [comment]
@mgoldgeier Thanks for the issue. Could you describe more about the problem you are hoping to solve? I would be curious to know if you are seeing unacceptably high latencies. Perhaps if you could provide an example cluster topology, database DDL, and query along with expected latencies we could help you determine the best way to address the problem.

Adding a feature to set replication factor to "ALL" might have other implications, so we want to fully understand your issue before deciding how to solve it.

**Comment by rafiss** [comment]
It sounds like `GLOBAL` tables as part of our v21.1 release addresses the use case here. See https://www.cockroachlabs.com/docs/v21.1/multiregion-overview#global-tables

I hope that works for you!
