### ISSUE TITLE
sql: cache ImmutableTableDescriptor

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#55960]
Extracting the second observation from #42770:

2. We always construct a new `ImmutableTableDescriptor`. These things are meant to be cached. I'm not sure how best to plumb a cache (or which one).

cc @ajwerner as I think you've been thinking about this and possibly there already exists a better issue.

Jira issue: CRDB-3608

**Comment by ajwerner** [comment]
I started to hack on this in https://github.com/cockroachdb/cockroach/pull/53747. I'll work to get that over the finish line. I think that that should enable us to cache even more inside the `ImmutableTableDescriptor`.

**Comment by postamar** [comment]
We now do effectively cache these in the descriptors collection. The exception to the rule are the table descriptors based on the protos in the distsql specs, which ultimately could be replaced by an (ID,Version) pair used to look them up in the descriptors collection.
