### ISSUE TITLE
doctor: detect orphaned schema change jobs

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#55978]
**Is your feature request related to a problem? Please describe.**

The doctor tool should be able to look at the jobs in `MutationJobIDs` and determine if any of them are in a terminal state.

**Comment by ajwerner** [comment]
This would detect the problem caused by https://github.com/cockroachdb/cockroach/issues/55978.

**Comment by vy-ton** [comment]
@jordanlewis is it worth bumping this up in January with the recent users hitting this?

**Comment by tim-o** [comment]
@vy-ton @jordanlewis I think this is worth bumping - it'd be really help to have this in a binary so we can scan cloud for these cases. We just got paged over the weekend with a prod cluster unable to make progress on an index creation due to an orphaned job.
