### ISSUE TITLE
client: `Txn.ReverseScan` is unused/untested

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#5599]
We should add a simple test.

**Comment by prideloki** [comment]
Hi @petermattis, i will add a test for it

**Comment by petermattis** [comment]
@prideloki Go for it!

**Comment by prideloki** [comment]
@petermattis 
I tried with the following code and i got empty from the ReverseScan

```
func TestTxn_ReverseScan(t *testing.T) {
	defer leaktest.AfterTest(t)()

	db := NewDB(newTestSender(func(ba roachpb.BatchRequest) (*roachpb.BatchResponse, *roachpb.Error) {
		return ba.CreateReply(), nil
	}, nil))
	if err := db.Txn(func(txn *Txn) error {
		b := txn.NewBatch()
		b.Put("aa", "1")
		b.Put("ab", "2")
		return txn.CommitInBatch(b)

	}); err != nil {
		t.Errorf("unexpected error on commit: %s", err)
	}
	txn := NewTxn(context.Background(), *db)
	rows, _ := txn.ReverseScan("ab", "c", 100)
	fmt.Printf("%+v", rows)

}
```
=== RUN   TestTxn_ReverseScan
[]--- PASS: TestTxn_ReverseScan (0.01s)

I also noticed that there is no test case for Txn.Scan as well
could you advise me where to start so i can write a test case for?

**Comment by petermattis** [comment]
@prideloki Your `NewDB` statement is not actually creating a server. That is, there is no database backing your `*client.DB`. The existing tests in `txn_test.go` use this pattern to test bits of the transaction machinery, but that's not what you're trying to do here. Take a look at some of the other `client` tests such as `TestClientBatch` for how to start a test server and construct a `*client.DB` from it.

PS you should be checking the error from `txn.ReverseScan`.

**Comment by prideloki** [comment]
@petermattis  thank you very much, i'm quite new to the project and OSS 
but here is the PR https://github.com/cockroachdb/cockroach/pull/6842
