### ISSUE TITLE
build: bazel build cockroach-short fails on BSD

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#56013]
Running

```
bazel build //pkg/cmd/cockroach-short |& tee failure.log
```

produces [this failure log](https://github.com/cockroachdb/cockroach/files/5444247/failure.log)

Then:
```
bazel build //pkg/cmd/cockroach-short --verbose_failures |& tee failure-verbose.log
```

produces [this verbose log](https://github.com/cockroachdb/cockroach/files/5444249/failure-verbose.log)

Attached [copy of bazel-out/.../libroach/logs/CMake.log](https://github.com/cockroachdb/cockroach/files/5444251/CMake.log)

Futher instructions needed?

**Comment by irfansharif** [comment]
```
ln: illegal option -- t
usage: ln [-s [-F] | -L | -P] [-f | -i] [-hnv] source_file [target_file]
       ln [-s [-F] | -L | -P] [-f | -i] [-hnv] source_file ... target_dir
       link source_file target_file
```

Looks like the bazel internal linking scripts seem to use an illegal option.
```
...
_____ BEGIN BUILD SCRIPT _____
#!/usr/bin/env bash
function symlink_to_dir() {
local target="$2"
mkdir -p "$target"
if [[ -f "$1" ]]; then
ln -s -f -t "$target" "$1"
```

**Comment by knz** [comment]
It's very odd because if `$target` already exists and is a directory (it is here! thanks to `mkdir` just before) then `-t` is not needed: `ln -s` will already do the right thing.

**Comment by knz** [comment]
can we just have that remove the `-t` flag?

**Comment by irfansharif** [comment]
Probably, but it's not part of our bazel we've yet touched by hand. Would need further investigation (bazel on non-darwin systems generally still do). Mind sharing for posterity the machine/distro you're running it on? Because it's not an issue I'm seeing on my box.

**Comment by knz** [comment]
BSD.

BSD `ln` does not support `-t`.

**Comment by otan** [comment]
We'd need to change something in here: https://sourcegraph.com/search?q=repo:%5Egithub.com/bazelbuild/rules_foreign_cc%24+ln+-s+&patternType=literal

Once grafted on, this needs to be placed on top of https://github.com/cockroachdb/cockroach/blob/master/WORKSPACE#L68.

**Comment by knz** [comment]
FWIW docker doesn't work on BSD systems (even macOS has problems). Native builds are a pre

**Comment by otan** [comment]
https://github.com/bazelbuild/rules_foreign_cc/pull/387

this would fix it. but there's no love from the maintainers :(
