### ISSUE TITLE
sql: alias the uuid generator as  `uuid_generate_v4()`

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#56014]
Discussed in [this comment](https://github.com/cockroachdb/cockroach/pull/19729#issuecomment-341259422)

CockroachDB provides a function called `gen_random_uuid()` which returns a UUID value generated randomly.

However the pg name for this  function is `uuid_generate_v4()`

See [this doc](https://www.postgresqltutorial.com/postgresql-uuid/)

We also probably need to recognize `CREATE EXTENSION "uuid-ossp"` as a no-op and support the other UUID versions.  (Beware: the code needed to generate v1-v3 UUIDs is not the same as v4)

----

Expected changes:
* Modularise and add an entry for uuid_generate_v4 here: https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/builtins.go#L551-L565
* Add a logic test here: https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/impure#L20 -- you can regenerate output by running `make testbaselogic FILES='impure' -rewrite` and checking the diff output to make sure it is expected.
* Submit a PR!

**Comment by knz** [comment]
cc @solongordon @otan   for triage

**Comment by hazcod** [comment]
Thank you for creating @knz

**Comment by otan** [comment]
uuid-oosp sounds like a good separate issue and also a good first issue to me.

**Comment by basanthjenuhb** [comment]
Can I take this up

**Comment by knz** [comment]
There's an update about this here: https://github.com/cockroachdb/cockroach/pull/19729#issuecomment-717560690

@otan can you check that? This may need to be discussed with product. Unsure we can keep the label "good first issue" until we're clear about what we want.

**Comment by otan** [comment]
> @otan can you check that?

Looks like `gen_random_uuid` is a new PG13 function, which behaves similarly to `uuid-ossp`'s `uuid_generate_v4`.

**Comment by gjaldon** [comment]
Hi @knz @otan! I'm looking into working on this issue but need to verify if this is still needed. Basing on:

> @hazcod This is not quite true anymore. In PG 13 they added gen_random_uuid() so Postgres became compatible with CockroachDB with the built-in function before CRDB did with Postgres. 🤷‍♂️

> https://www.postgresql.org/docs/13/functions-uuid.html

Looks like adding `uuid_generate_v4` would still be good for CRDB compatibility with versions of PG prior to PG 13.

**Comment by otan** [comment]
Sure is!

**Comment by gjaldon** [comment]
@otan @knz I'm working on this now!
