### ISSUE TITLE
sql: introduce "connect" privilege for databases

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#56020]
**Is your feature request related to a problem? Please describe.**
CockroachDB has privileges for SELECT, CREATE, INSERT, and others which are all concerned with reading or manipulating data. There is no separate notion of a privilege to simply connect to a database and view the _metadata_ (e.g. table names) in it.

**Describe the solution you'd like**
Postgres offers a [`CONNECT` privilege](https://www.postgresql.org/docs/10/sql-grant.html) that is used to determine if a user can connect to a given database. CockroachDB should have this too.

When adding it, also update the `has_database_privilege` builtin to check for this new privilege here: https://github.com/cockroachdb/cockroach/blob/c18a8d3fdc9828ca154ab95634b2c7f0c2fe0477/pkg/sql/sem/builtins/pg_builtins.go#L1320 (In order to achieve this, the code may need to start looking at crdb_internal.cluster_database_privileges instead of information_schema.schema_privilieges.)

**Additional context**
This also relates to Postgres compatibility. A general rule of Postgres is that if you can CONNECT to a database, then you can view the names of the objects in it. CockroachDB seems to be using SELECT privileges to decide if you can see the names of objects in it. For example, #49313 is about the schema names in pg_namespace being visible. Also see implementation discussion here: https://github.com/cockroachdb/cockroach/pull/51213#issuecomment-680188683

There has also been some confusion about name visibility here: #37443

**Comment by vy-ton** [comment]
Since we allow cross-database queries with fully qualified names, would you need the `CONNECT` privilege for these queries?

**Comment by knz** [comment]
Vy that is an excellent question.

I would say that yes, as long as we allow cross-database queries we would need to check CONNECT on all related databases.

An alternative would be to prevent cross-database queries and references altogether.

**Comment by vy-ton** [comment]
> An alternative would be to prevent cross-database queries and references altogether.

There are plans to remove cross-database references but cross-database queries will still be allowed

**Comment by rafiss** [comment]
Here is a forum user who ran into some confusion around this https://forum.cockroachlabs.com/t/user-defined-schemas-broken-with-spring-boot-and-liquibase/4136/3

**Comment by rafiss** [comment]
There are follow-up issues to make full use of the CONNECT privilege: #59875  #59827
