### ISSUE TITLE
release: fix build/release/teamcity-publish-release.sh to publish latest cockroachdb/cockroach-unstable

### ISSUE THREAD

**Issue by jlinder** [cockroachdb/cockroach#56033]
The new build process doesn't update the `cockroachdb/cockroach-unstable:latest` image when publishing new unstable builds. Fix the `build/release/teamcity-publish-release.sh` script to update that tag appropriately.

Epic RE-227
Jira issue: CRDB-3598

**Comment by rail** [comment]
This is [done](https://github.com/cockroachdb/cockroach/blob/d9cc084baa9892e28fb7211bf715e086170344f5/build/teamcity/internal/release/process/publish-cockroach-release.sh#L207-L217) and you  can see the `latest` tag in https://hub.docker.com/r/cockroachdb/cockroach-unstable/tags.
