### ISSUE TITLE
build: Pin the c++ toolchain versions for libroach (bazel)

### ISSUE THREAD

**Issue by jlinder** [cockroachdb/cockroach#56056]
Do so while keeping the ability to pick up a C/C++ compiler for that specific version from outside of the bazel build tree, for example the C/C++ toolchain installed by an OS' package distribution. See conversation [here](https://cockroachlabs.slack.com/archives/C019A8NANH0/p1603731441391500).

**Comment by rickystewart** [comment]
#62739
