### ISSUE TITLE
build: Pin/assert bazel version in use

### ISSUE THREAD

**Issue by jlinder** [cockroachdb/cockroach#56059]
We use 3.7.0 in our builder docker image. We can probably support an earlier version (like 3.5+).

**Comment by irfansharif** [comment]
We should explore using https://github.com/bazelbuild/bazelisk and a `.bazelversion` file to pin the specific bazel version in use. Ref: https://github.com/cockroachdb/cockroach/pull/55687#pullrequestreview-523338763.
