### ISSUE TITLE
ui: when values in CPU graph don't line up, no graphs show up

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#5605]
Unsure how to force a repro, but if you delete a value here https://github.com/cockroachdb/cockroach/blob/master/ui/ts/components/metrics.ts#L170 you should be able to reproduce it.

**Comment by tamird** [comment]
is this still an issue?

**Comment by maxlang** [comment]
I can't seem to repro this. Closing for now.

**Comment by maxlang** [comment]
This is happening when new metrics are added and then added to a graph with existing metrics. Also when metrics are slightly out of sync.

**Comment by maxlang** [comment]
I believe it was part of the cause of #9211
