### ISSUE TITLE
build: Pin the go toolchain version (bazel)

### ISSUE THREAD

**Issue by jlinder** [cockroachdb/cockroach#56060]
Do so while keeping the ability to pick up a go compiler for that specific version from outside of the bazel build tree, for example the go toolchain installed by an OS' package distribution. This appears to be possible by setting the "kind" parameter to "_go_host_sdk_", see [this link](https://github.com/bazelbuild/rules_go/blob/master/go/private/sdk.bzl#L241).  The top level build rules should provide a shorthand to give access to this option. See conversation [here](https://cockroachlabs.slack.com/archives/C019A8NANH0/p1603731441391500).

**Comment by otan** [comment]
can't do pre-1.14 until we fix the builder image to permission .cache correctly, or upgrade past go 1.15: https://github.com/bazelbuild/bazel-gazelle/pull/767

**Comment by jlinder** [comment]
@otan Is this still in progress? (for the bazel migration board)

**Comment by otan** [comment]
Yes. gazelle needs to be upgraded as the version of Go we will use (Go 1.15.5) is not in the current version we pinned in WORKSPACE.
