### ISSUE TITLE
build: Bazelize the generated SQL parser files

### ISSUE THREAD

**Issue by jlinder** [cockroachdb/cockroach#56061]
Bazelize the generated SQL parser files: the awk/goyacc/goimports invocations and placing the generated files in the proper 3 directories (otherwise it's not possible to run exclusively with bazel, and a make invocation is first needed).

**Comment by alan-mas** [comment]
Working on it!

**Comment by alan-mas** [comment]
Hi!
I was digging inside `Makefile` code to find something related to `goimports` and sql parser files and found some tmp files logic creation, so I do want to confirm if we are refering to the same part of the code that should be moved to bazel (or make it work) or I might be missing something.

From [Line 1417 - 1506](https://github.com/cockroachdb/cockroach/blob/master/Makefile#L1417-L506) I can see instructions related to `pkg/sql/parser`which seems to be related to sql parser files.

But only from [Line 1417 - 1447 ](https://github.com/cockroachdb/cockroach/blob/master/Makefile#L1417-L1447) are the ones that seems to be related to `pkg/sql/parser/gen/sql.go.tmp` the file that was created using [goyacc](https://godoc.org/golang.org/x/tools/cmd/goyacc) and also using command `goimports` and doing [some parsing with a regular expression](https://github.com/cockroachdb/cockroach/blob/master/Makefile#L1445)

So not sure if I am missing something or do you have any more deep information on which instructions should be moved @jlinder? or any other important info related to this.

Thanks!

**Comment by irfansharif** [comment]
@alan-mas: We already have a genrule to generate sql.go. You'll find it here: 
https://github.com/cockroachdb/cockroach/blob/9806c1c0db4390e65e60e41fbe35405afefc88ff/pkg/sql/parser/BUILD.bazel#L75-L93

For the full list of sql parser targets that we'd want to generate, you'll find them here:
https://github.com/cockroachdb/cockroach/blob/9806c1c0db4390e65e60e41fbe35405afefc88ff/Makefile#L814-L820

Within pkg/parser, we're missing `pkg/sql/parser/helpmap_test.go` and `pkg/sql/parser/help_messages.go`. For now we've pinned them in the BUILD file, but we'd want genrules similar to sql.go above.
https://github.com/cockroachdb/cockroach/blob/9806c1c0db4390e65e60e41fbe35405afefc88ff/pkg/sql/parser/BUILD.bazel#L11

and https://github.com/cockroachdb/cockroach/blob/9806c1c0db4390e65e60e41fbe35405afefc88ff/pkg/sql/parser/BUILD.bazel#L45

For where they get generated in our Makefile, look at https://github.com/cockroachdb/cockroach/blob/9806c1c0db4390e65e60e41fbe35405afefc88ff/Makefile#L1507-L1515.

We'll need to do the same for `pkg/sql/lex/tokens.go` and `pkg/sql/lex/keywords.go`, which we've also just pinned from now.

https://github.com/cockroachdb/cockroach/blob/9806c1c0db4390e65e60e41fbe35405afefc88ff/pkg/sql/lex/BUILD.bazel#L8-L9

The relevant bits in our Makefile: https://github.com/cockroachdb/cockroach/blob/9806c1c0db4390e65e60e41fbe35405afefc88ff/Makefile#L1434-L1445

(we'll need to do it for `pkg/sql/lexbase/reserved_keywords.go`)

**Comment by alan-mas** [comment]
Hey @irfansharif 
I can see that `sql.go`is getting created inside `bazel-out/darwin-fastbuild/bin/pkg/sql/parser/` 
I was able to create with a new  Bazel `genrule` the `helpmap_test.go`and that one is getting created inside the same path as the `sql.go`
I am just confirming if this is expected from your side, I am already working in the other files. Next `pkg/sql/parser/help_messages.go`

**Comment by irfansharif** [comment]
@alan-mas, yup, we do expect it to get placed in the same path as the bazel generated `sql.go`.
