### ISSUE TITLE
build: Get built UI to bindata (bazel)

### ISSUE THREAD

**Issue by jlinder** [cockroachdb/cockroach#56069]
Epic CRDB-2589

**Comment by koorosh** [comment]
@jlinder , would it be an option to get rid of `go-bindata` in favor of go's `embed` directive (https://golang.org/pkg/embed/) to embed JS assets into GO binaries? It might simplify the build process.

**Comment by koorosh** [comment]
Following PR contains changes required to build JS assets which then have to be embedded into binary: WIP. ui: bazel build for pkg/ui by koorosh · Pull Request #67066 · cockroachdb/cockroach 

Command to build JS assets: bazel build //pkg/ui/workspaces/db-console:db_console_webpack

Makefile target pkg/ui/distccl/bindata.go runs formatting and appends code into auto-generated files. To avoid such file edits, it is suggested to refactor pkg/ui/distccl/distccl.go file to include intit func which was appended by Makefile (see following commit with this change: 7207d1bda438b014af86bbf60f6e318a82436e4b , it is in draft and probably has to be improved)

**Comment by koorosh** [comment]
Go embed is used in favor of `gobindata` so it is not actual anymore.
