### ISSUE TITLE
build: Make bazel auto-generate pkg/sql/lexbase/reserved_keywords.go in the bazel sandbox

### ISSUE THREAD

**Issue by jlinder** [cockroachdb/cockroach#56062]
Needed for bazel to build without first requiring a make invocation. ([ref PR](https://github.com/cockroachdb/cockroach/pull/56019), [slack conversation](https://cockroachlabs.slack.com/archives/C019A8NANH0/p1603820386455100?thread_ts=1603818077.450100&cid=C019A8NANH0))

**Comment by kenliu** [comment]
see related issue #56019

**Comment by irfansharif** [comment]
Fixed in #57705.
