### ISSUE TITLE
build: Make bazel able to cross compile between linux, windows, osx, arm

### ISSUE THREAD

**Issue by jlinder** [cockroachdb/cockroach#56072]
Also ARM and soon S390x (see #55617 )

Epic CRDB-8306

**Comment by rickystewart** [comment]
Is cross-compilation "between Linux, Windows, and macOS" desired in any direction (e.g. Windows -> Linux, macOS -> Windows), or just from Linux to the other platforms, or...?

**Comment by jlinder** [comment]
This issue is specifically for CI to be able to build all the needed binaries, which means Linux x86 -> other platforms. 

I expect we'll want to add support for Linux ARM and Mac OS X ARM before too long as well as targets.

**Comment by rickystewart** [comment]
*phew*
