### ISSUE TITLE
build: Ensure there are bazel shorthand test targets

### ISSUE THREAD

**Issue by jlinder** [cockroachdb/cockroach#56073]
- [ ] To run a test selection in a package (with regexp)
   - [ ] With stress
   - [ ] With race
   - [ ] With stressrace
- [ ] To run an entire package
- [ ] For logic tests:
   - [ ] With separate targets for "base" logic tests and "ccl" logic tests
   - [ ] Selecting just a subset of the input files
   - [ ] Selecting just one test configuration

**Comment by irfansharif** [comment]
Should happen under the context of #56965.

**Comment by irfansharif** [comment]
This is better tracked in https://github.com/cockroachdb/dev. I think stress/race/stressrace work. Ditto for entire packages. Logic tests are still unimplemented.
