### ISSUE TITLE
Geoserver Rest API GWC Seed

### ISSUE THREAD

**Issue by px6652586** [cockroachdb/cockroach#56108]
Does anyone know that the data obtained by GeoServer calling seed for map slicing is incomplete? A lot of slicing is missing. Is it a bug or something else?

**Comment by px6652586** [comment]
Question 1: how to fill in the interface parameter seed?

Question 2: when the amount of data is large, the slicing results are incomplete

thanks！！！！！

**Comment by awoods187** [comment]
cc @otan

**Comment by otan** [comment]
Can you describe what you are trying to do.

GeoServer is not fully supported yet -- see https://github.com/cockroachdb/cockroach/issues/52013.

**Comment by rafiss** [comment]
We'll close this issue for now, but please re-open if you can provide more information or have found a bug.
