### ISSUE TITLE
Technical Advisory: Incorrect timezone calculations with "slim" zoneinfo format

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/cockroach#56116]
# Description
All currently-released versions of the Go runtime [incorrectly interpret](https://github.com/golang/go/issues/42138) the daylight-savings flag in "slim" versions of zoneinfo that are used by some OS distributions. This can result in incorrect local date-time calculations for any version of CockroachDB that is running on an OS image that distributes "slim" zoneinfo files.

Users of official CockroachDB Docker images are not affected.

Users of our reference Kubernetes configurations are not affected.

Users of Cockroach Cloud are not affected.

# Statement
This public issue is tracked as https://github.com/cockroachdb/cockroach/issues/56116.

# Mitigation
Execute the following SQL statement to determine if your cluster is affected:

```sql
SET TIME ZONE UTC; -- The default for cockroach sql
SELECT '2020-10-29 15:30'::TIMESTAMPTZ AT TIME ZONE 'Europe/Berlin' AT TIME ZONE 'UTC';
```

If a value other than `2020-10-29 16:30:00+00:00` is returned, you are affected by this technical advisory and should perform the following remediation:
* Download [zoneinfo.zip 2020a](https://github.com/golang/go/tree/5c9a8c0761ae643828a4526db764ac7a50a1a24d/lib/time) from the golang development tree to each CockroachDB node.
* Perform a rolling restart of all CockroachDB processes, setting the ZONEINFO environment variable to the path of the zoneinfo.zip file.
* Confirm the fix by executing the above SQL statement.

# Impact
Any clusters impacted by this issue may produce incorrect results when performing date/time calculations that involve values in timezones and time periods for which daylight-savings are in effect.

Jira issue: CRDB-3578

**Comment by mikeCRL** [comment]
If this changes at any point, we will need to update the technical advisory https://www.cockroachlabs.com/docs/advisories/ https://www.cockroachlabs.com/docs/advisories/a56116 which states that all versions are affected.

@bobvawter Is there any need to confirm whether this is still affecting all versions of CockroachDB?

**Comment by bobvawter** [comment]
It's going to affect any version of CockroachDB built with go 1.15.3 or earlier.  As far as I know, we only rarely bump the golang version in the release branches to avoid surprising regressions.
