### ISSUE TITLE
import: syntax error in message and handle precision with bit data type

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#56122]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

execute an import using `BIT` column type

What did you do? Describe in your own words.

create a test file

```sql
DROP TABLE IF EXISTS Test;
CREATE TABLE Test (
  `Active` bit(1) DEFAULT NULL);
```

import using mysqldump

```sql
IMPORT MYSQLDUMP 'http://localhost:8000/1st_issue.sql' WITH skip_foreign_keys;
```
error

```sql
root@:26257/test> IMPORT MYSQLDUMP 'http://localhost:8000/1st_issue.sql' WITH skip_foreign_keys;
ERROR: unimplemented: cannot improt BIT columns at this time
SQLSTATE: 0A000
HINT: You have attempted to use a feature that is not yet implemented.
See: https://go.crdb.dev/issue-v/32561/v20.1
--
try converting the column to a 64-bit integer before import
```
If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
2. Send SQL ... / CLI command ...
3. Look at UI / log file / client app ...

**Expected behavior**

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version [e.g. 2.0.x]
 - Server OS: [e.g. Linux/Distrib]
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
What was the impact?

Epic CRDB-8825

Jira issue: CRDB-3575

**Comment by dbist** [comment]
as a workaround, removing precision for Bit fixes the issue

```sql
DROP TABLE IF EXISTS Test;
CREATE TABLE Test (
  `Active` bit DEFAULT NULL);
```

**Comment by dbist** [comment]
just FYI, import is misspelled in the error message `improt`

**Comment by dikshant** [comment]
With IMPORT MYSQLDUMP being deprecated: https://github.com/cockroachdb/cockroach/issues/93660 and [Schema Conversion Tool](https://www.cockroachlabs.com/docs/cockroachcloud/migrations-page) being better for schema migrations this is no longer needed and can now be closed.
