### ISSUE TITLE
import: mysqldump support precision argument to current_timestamp()

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#56121]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

Create a schema sql file

```sql
CREATE TABLE TEST ( `UpdatedAt` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6));
```

execute a mysqldump import using

```sql
IMPORT MYSQLDUMP 'http://localhost:8000/test.sql' WITH skip_foreign_keys;
```

```sql
root@:26257/test> IMPORT MYSQLDUMP 'http://localhost:8000/test.sql' WITH skip_foreign_keys;
ERROR: mysql parse error: syntax error at position 78 near '6'
```

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
2. Send SQL ... / CLI command ...
3. Look at UI / log file / client app ...

**Expected behavior**

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version 20.1.8
 - Server OS: OSX
 - Client app `cockroach sql`

**Additional context**
What was the impact?

Epic CRDB-8825

Jira issue: CRDB-3576

**Comment by dbist** [comment]
as a workaround, removing precision from `CURRENT_TIMESTAMP(6)` will fix the issue

```sql
CREATE TABLE TEST ( `UpdatedAt` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP());
```

**Comment by dikshant** [comment]
With IMPORT MYSQLDUMP being deprecated: https://github.com/cockroachdb/cockroach/issues/93660 and [Schema Conversion Tool](https://www.cockroachlabs.com/docs/cockroachcloud/migrations-page) being better for schema migrations this is no longer needed and can now be closed.
