### ISSUE TITLE
sql: pgwire timestamp parsing

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#5612]
[`cockroachdb/pq.formatTs`](https://github.com/cockroachdb/pq/blob/master/encode.go#L436) formats timestamps for the wire using `time.RFC3339Nano`. But [`cockroachdb/pq.ParseTimestamp`](https://github.com/cockroachdb/pq/blob/master/encode.go#L339) cannot parse such timestamps. We need to figure out why the discrepancy. Does postgres send back non-RFC3339 timestamps on the wire?

**Comment by petermattis** [comment]
A little googling reveals that postgres (when using `ISO` datestyle) expects ISO 8061 formatted dates/times. These are almost the same as RFC3339 formatted dates/times, except the ISO 8061 formatting allows the `T` separating the date and time to be replaced with a space.

**Comment by paperstreet** [comment]
I just tracked it down in the source, and postgres, in fact, uses a space and not a `T` when sending a timestamp back with datestyle ISO (which is the default). I think we should match that. @petermattis  sgty?

Regardless, we should be able to parse either a space or a T there. I'll make that change

**Comment by petermattis** [comment]
Yep, sounds good to me.
