### ISSUE TITLE
logging: create new debugging log cockroach.debug.log

### ISSUE THREAD

**Issue by fabiog1901** [cockroachdb/cockroach#56148]
Create new log `cockroach.debug.log` for debugging purpose, similar in the content to the current `cockroach-sql-exec.log`.

The logging should be disabled by default.
This is intended as a "catch all" log file.

Linked to #56156

**Comment by knz** [comment]
The "catch all" file is already there, it's named `cockroach.log`.

Starting in 21.1 users can choose the name. The "catch all" logging channel will be DEV.
