### ISSUE TITLE
logging: restrict cockroach-sql-exec.log to *users* SQL statements that have been so GRANTed

### ISSUE THREAD

**Issue by fabiog1901** [cockroachdb/cockroach#56149]
The current form of `cockroach-sql-exec.log` is too verbose and includes system stmts. 

The request is to:
- rename it to `cockroach.sql.log`;
- restrict the log to only store SQL statements (DML, DQL, TCL) initiated by users only;
- enabled on a per role/table/schema/database/system, for example, via a GRANT statement.

Linked to #56156

**Comment by knz** [comment]
As of #57737  the DDL, user management and privilege changes are now emitted as structured events on their respective logging channel.
