### ISSUE TITLE
logging: log all Events into a new cockroach.events.log file

### ISSUE THREAD

**Issue by fabiog1901** [cockroachdb/cockroach#56151]
The request is to have a log file called `cockroach.events.log` that is an exact replica of the `system.eventlog` table.

The logging should be enabled/disabled via a cluster setting; enabled by default

Linked to #56156

**Comment by knz** [comment]
As of #57737 and subsequent PRs, the structured events are copied to dedicated logging channels. They are not all logged together: they are now grouped per category into different logging channels. Users can configure what they see and where it gets written.
