### ISSUE TITLE
Error Importing TSV file uploaded to GCS with -Z (gzip at rest) option set

### ISSUE THREAD

**Issue by kjlubick** [cockroachdb/cockroach#56152]
**Describe the problem**
When importing TSV files from GCS that were stored using `gsutil cp -Z`, the files sometimes fail to load with errors indicating truncation `error parsing row 677999: expected 3 fields, got 2`

**To Reproduce**

I found this while working with randomly-produced data, so I've left it publicly available on GCS.

If possible, provide steps to reproduce the behavior:

1. I am running a cluster with 5 nodes in GCS using the recommended k8s config.
2. Create a new database and attach to it via an SQL shell.
3. Try to run the following import statement.

```
IMPORT TABLE PrimaryBranchParams (
  commit_id INT4 NOT NULL,
  key STRING NOT NULL,
  value STRING NOT NULL,
  PRIMARY KEY (commit_id, key, value)
) CSV DATA (
'gs://skia-gold-benchmark-data/schemaV1/params/params_1317938261346792849.tsv',
'gs://skia-gold-benchmark-data/schemaV1/params/params_3344400709634359273.tsv',
'gs://skia-gold-benchmark-data/schemaV1/params/params_3794156622884343106.tsv',
'gs://skia-gold-benchmark-data/schemaV1/params/params_3344400709634359273.tsv',
'gs://skia-gold-benchmark-data/schemaV1/params/params_4244378414963744339.tsv',
'gs://skia-gold-benchmark-data/schemaV1/params/params_4883954964158297154.tsv',
'gs://skia-gold-benchmark-data/schemaV1/params/params_5529620708038318579.tsv',
'gs://skia-gold-benchmark-data/schemaV1/params/params_6092797839052470063.tsv',
'gs://skia-gold-benchmark-data/schemaV1/params/params_6893293523575469822.tsv',
'gs://skia-gold-benchmark-data/schemaV1/params/params_772841964638661580.tsv'
)
 WITH delimiter = e'\t';
```
These files contain about 700k rows each (5.1 million unique rows total). These files were uploaded to GCS using the command
`gsutil -m cp -Z tsvfiles/* [bucket]`

4. I tried this several times and saw one of two errors fairly consistently: 
```
ERROR: gs://skia-gold-benchmark-data/schemaV1/params/params_4883954964158297154.tsv: error parsing row 677999: expected 3 fields, got 2 (row: "40999\topt_Wyomi")
ERROR: gs://skia-gold-benchmark-data/schemaV1/params/params_6092797839052470063.tsv: error parsing row 672986: expected 3 fields, got 2 (row: "40999\top")

```
**Expected behavior**
As above, if you run almost the same command, but with V2 (the same files, but not compressed using gzip at rest),

```
IMPORT TABLE PrimaryBranchParams (
  commit_id INT4 NOT NULL,
  key STRING NOT NULL,
  value STRING NOT NULL,
  PRIMARY KEY (commit_id, key, value)
) CSV DATA (
'gs://skia-gold-benchmark-data/schemaV2/params/params_1317938261346792849.tsv',
'gs://skia-gold-benchmark-data/schemaV2/params/params_3344400709634359273.tsv',
'gs://skia-gold-benchmark-data/schemaV2/params/params_3794156622884343106.tsv',
'gs://skia-gold-benchmark-data/schemaV2/params/params_3344400709634359273.tsv',
'gs://skia-gold-benchmark-data/schemaV2/params/params_4244378414963744339.tsv',
'gs://skia-gold-benchmark-data/schemaV2/params/params_4883954964158297154.tsv',
'gs://skia-gold-benchmark-data/schemaV2/params/params_5529620708038318579.tsv',
'gs://skia-gold-benchmark-data/schemaV2/params/params_6092797839052470063.tsv',
'gs://skia-gold-benchmark-data/schemaV2/params/params_6893293523575469822.tsv',
'gs://skia-gold-benchmark-data/schemaV2/params/params_772841964638661580.tsv'
)
 WITH delimiter = e'\t';
```
It will succeed in a bit under 30 seconds.
As mentioned above, these files were the same as the failing case, just uploaded without -Z
`gsutil -m cp  tsvfiles/* [bucket]`

**Environment:**
 - CockroachDB version 20.1.8 (also saw this on 20.1.4, but then updated to see if it was fixed)
 - Server OS: docker image cockroachdb/cockroach:v20.1.8 using y'alls kubernetes yaml files.
 - Client app `cockroach sql`

**Additional context**
What was the impact?

Will try gzipping the content explicitly before uploading to hopefully work around this.

**Comment by dt** [comment]
@kjlubick Thanks for reporting this! I dug a bit and was able to confirm that a) if I download both files with gsutil, I get the same bytes / hash but b) if I download the files with our internal google storage client, the compressed one is missing the last few kb. I tracked it down to a bug in how we handled end-of-file when it is returned a bit differently by the google client when handling a compressed vs uncompressed file, and just prepared a patch over in #57745. Thanks again for the report, and especially for including the files used to reproduce the issue -- that made it very easy to debug!
