### ISSUE TITLE
logging: log Jobs into separate log file

### ISSUE THREAD

**Issue by fabiog1901** [cockroachdb/cockroach#56153]
The request is to create a new log file `cockroach.jobs.log` to log information on:

Automation logs, scheduled tasks
  - backups, restores,
  - backup status (job_id, size, target location, what was backed up, etc..) 
  - imports, exports
  - any scheduled task
  - the same information found in `SHOW JOBS;`
  - Let's consider a one off run of backup a single instance of a scheduled task
 
Enabled/disabled via a cluster setting, off by default   

Linked to #56156

**Comment by knz** [comment]
dup #57575
