### ISSUE TITLE
build: unable to inject temporary changes to the Go stdlib

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#56178]
When troubleshooting issues, I often find myself modifying files in the Go stdlib, for example in the `fmt`, `io` or `os` packages.

I expect these temporary changes to be automatically picked up by the Go compiler when I build my `cockroach` executable.

Prior to the introduction of `bazel` this would “just work”. However now `bazel` is embarking its own copy of the Go tree in the sandbox and refuses to consider my changes.

I would like a (tested) solution to this and a documentation for it in the wiki.

cc @jlinder @otan 

Epic CRDB-10447

Jira issue: CRDB-7994

**Comment by irfansharif** [comment]
Documented how to do it in https://github.com/cockroachdb/cockroach/pull/77345.
