### ISSUE TITLE
sql/dbconsole: the left hand navigation is out of order 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#56244]
On maste (and 20.2) the left hand navigation shows Sessions -> Statements -> Transactions:
<img width="1611" alt="Screen Shot 2020-11-03 at 11 06 31 AM" src="https://user-images.githubusercontent.com/22278911/98010530-cde40380-1dc4-11eb-8f5b-d12bbb295292.png">

Instead, we want this to display Sessions -> Transactions -> Statements to reflect the logical hierarchy.

**Comment by awoods187** [comment]
@dhartunian any update here? I want to take screen shots with this in the right order for various blog posts

**Comment by dhartunian** [comment]
This is now merged and backported here: https://github.com/cockroachdb/cockroach/pull/56652
