### ISSUE TITLE
sql: alias SHOW STATEMENTS to SHOW QUERIES

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#56240]
As we seek to make replicate functionality between the db console and the SQL shell we should seek consistency in terminology as well.

In the db console we offer Sessions, Transactions, and Statements pages. 
We mirror this in the SQL shell with `SHOW SESSIONS`, `SHOW TRANSACTIONS`, and `SHOW QUERIES.` (although these only show active sessions, transactions, and queries as opposed to the db consoles historical information). 

SHOW QUERIES and Statements are not consistent. Let's alias `SHOW STATEMENTS` to be the same as `SHOW QUERIES` so that we can demonstrate consistency. We don't need to retire `SHOW QUERIES` since its already in use but we should gradually emphasize it in the docs in favor of the new `SHOW STATEMENTS` for consistency.  

```SQL
root@127.0.0.1:57627/movr> show statements;
ERROR: unrecognized configuration parameter "statements"
SQLSTATE: 42704
```

**Comment by ivern** [comment]
I could do this if still needed. I have some questions, though:

1. Should `CANCEL STATEMENTS` be aliased to `CANCEL QUERIES` as well?
2. Should `Format` / `StatementTag` return the `STATEMENTS` form, rather than `QUERIES`, regardless of how the statement was written?

**Comment by rafiss** [comment]
Thanks @ivern ! Good question. I'll find out and get an answer when I can, but may take longer than normal since we are in a holiday period.

**Comment by rafiss** [comment]
@ivern I checked in and an alias for `CANCEL QUERY/QUERIES` to use `STATEMENT/STATEMENTS` would also be nice to have. If you do work on that, feel free to refer to this issue number still.

**Comment by ivern** [comment]
@rafiss Thanks, I can make that change as well. I'll submit a PR later this week when I have some time.
