### ISSUE TITLE
import: support for GENERATED ALWAYS AS in mysqldump

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#56241]
**Describe the problem**

**To Reproduce**

```sql
DROP TABLE IF EXISTS `cards_short`;
CREATE TABLE `cards_short` (
  `CardHash` char(255) DEFAULT NULL,
  `CardStatus` varchar(30) DEFAULT NULL,
  `Tracking` varchar(50) DEFAULT NULL,
  `Type` varchar(40) DEFAULT NULL,
  `ToEmboss` boolean GENERATED ALWAYS AS (
        if(
            (
                (CardHash is not null)
                and (Tracking is null)
                and (CardStatus = 'CREATED')
                and (Type = 'PLASTIC')
            ),
            TRUE,
            FALSE
        )
    ) STORED NOT NULL,
) ENGINE=InnoDB AUTO_INCREMENT=5270959 DEFAULT CHARSET=latin1;
```

```sql
IMPORT MYSQLDUMP 'http://host.docker.internal:8000/cards_short.sql' WITH skip_foreign_keys;
```

```sql
ERROR: mysql parse error: syntax error at position 238 near 'boolean'
```

**Expected behavior**

IMPORT WORKS OOTB

**Environment:**
 - CockroachDB version 20.2.0.rc4
 - Server OS: Docker
 - Client app `cockroach sql`

**Additional context**
What was the impact?

IMPORT cannot proceed without a rewrite

Epic CRDB-8825

Jira issue: CRDB-2961

**Comment by dikshant** [comment]
With IMPORT MYSQLDUMP being deprecated: https://github.com/cockroachdb/cockroach/issues/93660 and [Schema Conversion Tool](https://www.cockroachlabs.com/docs/cockroachcloud/migrations-page) being better for schema migrations this is no longer needed and can now be closed.
