### ISSUE TITLE
ui: Transactions Page tooltips are incorrect

### ISSUE THREAD

**Issue by taroface** [cockroachdb/cockroach#56266]
The tooltips in the Transaction table are currently reusing the tooltips from the Statements page. They should be:

**Transactions:** Transaction.<br><br>To view the transaction fingerprint and details, click this to open the Transaction Details.

**Statements:** Number of SQL statements in the transaction.

**Retries:** Cumulative number of retries of this transaction within the last hour or specified time interval.

**Execution Count:** Cumulative number of executions of this transaction within the last hour or specified time interval. <br><br>The bar indicates the ratio of runtime success (gray) to retries (red) for the transaction.

**Rows Affected:** Average number of rows returned while executing this transaction within the last hour or specified time interval. <br><br>The gray bar indicates the mean number of rows returned. The blue bar indicates one standard deviation from the mean.

**Latency:** Average service latency of this transaction within the last hour or specified time interval. This includes the total time the transaction remains open. <br><br>The gray bar indicates the mean latency. The blue bar indicates one standard deviation from the mean.

cc @dhartunian 

Jira issue: CRDB-2957

**Comment by awoods187** [comment]
@Annebirzin can you evaluate these and see what if any are not addressed with the work you, @asubiotto, and @ianjevans are doing?

**Comment by Annebirzin** [comment]
@awoods187 @ianjevans I've updated the [tooltip copy in figma](https://www.figma.com/file/MoSPFkEyJfGipCmQvvLg1a/obsrv-query-performance?node-id=1834%3A2895) to align with this copy.

Note that the 'Rows Affected' and 'Latency' tooltips do not apply to the updated columns for 21.1

@taroface can you also verify if there should be links in any of those tooltips and what the URL would be?
