### ISSUE TITLE
CockroachDB as a drop-in postgres replacement and use as Confluence backend ?

### ISSUE THREAD

**Issue by bodleytunes** [cockroachdb/cockroach#56285]
Hi All,

I was just testing CockroachDB in a k3s install and wondered if it would work as an alternative to postgres for a confluence instance.
However, every time I try and install confluence using cockroach as a backend, it fails to connect.

The following error(s) occurred:

Configuring database failed
**org.postgresql.util.PSQLException: The connection attempt failed.**

This doesn't make sense because it initially tests as okay.

I'm wondering if its a driver issue leading to some incompatibility.

Any ideas?  or is this never going to work?

Cheers,
Jon.

![image](https://user-images.githubusercontent.com/619239/98159245-22c26f80-1ed4-11eb-862b-b1ac9ef90f06.png)
![image](https://user-images.githubusercontent.com/619239/98159259-2950e700-1ed4-11eb-944f-ba894c78a30f.png)

**Comment by jordanlewis** [comment]
You'll have to give us some more details, but Confluence likely at minimum uses Full Text Search which we don't support yet.

Hard for us to help with this without any more logs or details, so I'm going to close the issue - but feel free to keep posting on it if you have some logs containing statements that failed, or any more details.

Thanks!
