### ISSUE TITLE
storage: the message for range split conflicts should be improved

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#5629]
Reported by @yznming on Gitter:

```
E160325 20:14:13.922965 storage/queue.go:444  [split] range=23 [/Table/51/1/2360159016-/Table/51/1/2725786584): error: storage/replica_command.go:1664: split at key /Table/51/1/2725788664 failed: unexpected value: raw_bytes:"(\016J\035\003\010\027\022\007\273\211\371\214\255+(\032\007\273\211\371\242x3\330\"\006\010\001\020\001\030\001\"\006\010\004\020\004\030\002\"\006\010\007\020\007\030\003(\004" timestamp:<wall_time:1458908049375339590 logical:1 >
```

As suggested below by Tobias this message indicates a conflict during a range split. However the text of the message does not convey this information clearly. The message should be improved.

**Comment by yznming** [comment]
here is the full log
[log.tar.gz](https://github.com/cockroachdb/cockroach/files/191629/log.tar.gz)

**Comment by tschottdorf** [comment]
This message occurs when two splits race and ours loses. We should improve
the error message in this case.
