### ISSUE TITLE
Cluster dies after couple of hours not reaching 1B keys / 1TB a node

### ISSUE THREAD

**Issue by sitano** [cockroachdb/cockroach#56362]
**Describe the problem**

I have tried twice to load into the CockroachDB cluster of 3 AWS machines 1B keys with https://github.com/brianfrankcooper/YCSB and PostgreNoSQL binding and it died both times. By died I mean went completely unresponsive with insane latencies consume some CPU doing no one knows what.   

**To Reproduce**

YCSB 1, 1B keys, workload A
I3en.4xlarge x3 cluster, 8 vCPU
C5.4xlarge loader x1

3 machines cluster, 3 replication factor = 3 * 16 = 48 vCPU

    $ terraform apply -var-file=.vars
    $ ansible-playbook -i ./.inv ./playbook-example.yaml

CockroachDB version https://binaries.cockroachdb.com/cockroach-v20.1.6.linux-amd64.tgz
Overall cluster capacity 10.4TiB

Init

    $ cockroach sql --host $HOST1 --insecure

    CREATE DATABASE ycsb;
    USE ycsb;
    CREATE TABLE usertable (YCSB_KEY VARCHAR(255) PRIMARY KEY not NULL, YCSB_VALUE JSONB not NULL);

Single process load

    $ /opt/ycsb/bin/ycsb load postgrenosql -threads 1 -P /opt/ycsb/workloads/workloada -p measurementtype=hdrhistogram -p insertstart=0 -p insertcount=1000000000 -p recordcount=1000000000 -s -p insertorder=ordered -p zeropadding=12 -p postgrenosql.url=jdbc:postgresql://10.0.0.58:26257/ycsb -p postgrenosql.user=root -p postgrenosql.passwd= -p postgrenosql.autocommit=true -p fieldcount=10 -p fieldlength=128

It will take 6-12 hours and they suddenly stop progressing. I saw a stop around 6-8M per loader process, and 1TiB at the main node. It stops progressing because CRDB stops processing requests.

**Expected behavior**

1. Throughput must not decrease
2. Cluster must not go unresponsive
3. No scary errors must be found in the logs
4. All 1B keys must be loaded

**Additional data / screenshots**

![f2020-10-13-scylla-crdb-a-original-1](https://user-images.githubusercontent.com/564610/98381864-22041780-2053-11eb-9b0b-9c064b33d6c1.png)
![f2020-10-13-scylla-crdb-a-original-2](https://user-images.githubusercontent.com/564610/98381867-229cae00-2053-11eb-9ab3-287949765291.png)
![f2020-10-13-scylla-crdb-a-original-3](https://user-images.githubusercontent.com/564610/98381868-23354480-2053-11eb-8157-b94ff19cf8c6.png)
![f2020-10-13-scylla-crdb-a-original-4](https://user-images.githubusercontent.com/564610/98381871-23354480-2053-11eb-9edf-e6ce1f861e2a.png)
![f2020-10-13-scylla-crdb-a-original-5](https://user-images.githubusercontent.com/564610/98381872-23cddb00-2053-11eb-9f19-ed7fce47b1e2.png)
![f2020-10-13-scylla-crdb-a-original-6](https://user-images.githubusercontent.com/564610/98381874-23cddb00-2053-11eb-9374-5a2940d0a858.png)
![f2020-10-13-scylla-crdb-a-original-7](https://user-images.githubusercontent.com/564610/98381875-24667180-2053-11eb-973a-806d7301055f.png)
![f2020-10-13-scylla-crdb-a-original-8](https://user-images.githubusercontent.com/564610/98381878-24667180-2053-11eb-8673-6dfaa5ed3258.png)
![f2020-10-13-scylla-crdb-a-original-9](https://user-images.githubusercontent.com/564610/98381879-24ff0800-2053-11eb-860a-2fa8a63e8973.png)
![f2020-10-13-scylla-crdb-a-original-10](https://user-images.githubusercontent.com/564610/98381881-24ff0800-2053-11eb-8c21-cf00d50a8312.png)
![f2020-10-13-scylla-crdb-a-original-11](https://user-images.githubusercontent.com/564610/98381883-25979e80-2053-11eb-99b9-facdf3988882.png)
![f2020-10-13-scylla-crdb-a-original-12](https://user-images.githubusercontent.com/564610/98381884-25979e80-2053-11eb-91f9-2467f78af00f.png)
![f2020-10-13-scylla-crdb-a-original-13](https://user-images.githubusercontent.com/564610/98381886-26303500-2053-11eb-9bad-fa5d778d6ef2.png)
![f2020-10-13-scylla-crdb-a-original-14](https://user-images.githubusercontent.com/564610/98381887-26303500-2053-11eb-9734-bd74e606dbcb.png)
![f2020-10-13-scylla-crdb-a-original-15](https://user-images.githubusercontent.com/564610/98381889-26c8cb80-2053-11eb-939f-a4628c314364.png)
![f2020-10-13-scylla-crdb-a-original-16](https://user-images.githubusercontent.com/564610/98381890-26c8cb80-2053-11eb-9022-3f67ab0cc6de.png)
![f2020-10-13-scylla-crdb-a-original-17](https://user-images.githubusercontent.com/564610/98381892-27616200-2053-11eb-8f45-3e4099e4de68.png)
![f2020-10-13-scylla-crdb-a-original-18](https://user-images.githubusercontent.com/564610/98381893-27616200-2053-11eb-80c0-4aeff27c6289.png)
![f2020-10-13-scylla-crdb-a-original-19](https://user-images.githubusercontent.com/564610/98381895-27f9f880-2053-11eb-9bb4-ef7154f844fd.png)
![f2020-10-13-scylla-crdb-a-original-20](https://user-images.githubusercontent.com/564610/98381897-28928f00-2053-11eb-91ba-59e7303d26ce.png)
![f2020-10-13-scylla-crdb-a-original-21](https://user-images.githubusercontent.com/564610/98381900-28928f00-2053-11eb-9a84-211424258763.png)
![f2020-10-13-scylla-crdb-a-original-22](https://user-images.githubusercontent.com/564610/98381904-28928f00-2053-11eb-9c40-cec538f9f2c3.png)
![f2020-10-13-scylla-crdb-a-original-23](https://user-images.githubusercontent.com/564610/98381907-292b2580-2053-11eb-87e4-38a20057df05.png)
![f2020-10-13-scylla-crdb-a-original-24](https://user-images.githubusercontent.com/564610/98381908-29c3bc00-2053-11eb-858a-55f1800893f8.png)

[crdb_log_n1.zip](https://github.com/cockroachdb/cockroach/files/5501926/crdb_log_n1.zip)
[crdb_log_n2.zip](https://github.com/cockroachdb/cockroach/files/5501928/crdb_log_n2.zip)
[crdb_log_n3.zip](https://github.com/cockroachdb/cockroach/files/5501929/crdb_log_n3.zip)

**Environment:**
 - CockroachDB version [v20.1.6.linux-amd64]
 - Server OS: [I3en.4xlarge, amazon linux]
 - Client app [https://github.com/brianfrankcooper/YCSB]

**Comment by sitano** [comment]
Logs contain a lot of scary errors.

**Comment by jordanlewis** [comment]
Interesting, could you send us a [debug zip](https://www.cockroachlabs.com/docs/v20.2/cockroach-debug-zip)?

**Comment by jordanlewis** [comment]
Also, what kind of disks have you used in your test?

**Comment by sitano** [comment]
@jordanlewis I use 2 x NVMe 1.9TB via md0 raid0 that are in i3.4xlarge. I don't have debug.zip for this but I shared node logs. This time I have faced another issue with CPU 100% and latch acq timeouts with the v20.2.0. I have debug.zip for that case.

**Comment by mwang1026** [comment]
Sorry it's been a while since a response! There's been a lot of performance and stability improvements in 21.1. If you're still interested in, do you mind trying it out on the latest 21.1 release and re-opening if you continue to run into issues? Thanks
