### ISSUE TITLE
sqlproxyccl: TestFailedConnection has different error messages on Go 1.15

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#56377]
Some connection error messages can be different with the upgrade.

Looks like some of the sqlproxyccl error messages have changed (https://teamcity.cockroachdb.com/viewLog.html?buildId=2423317&buildTypeId=Cockroach_UnitTests)
```

=== RUN   TestFailedConnection/defaultdb_29?sslmode=verify-full&sslrootcert=testserver.crt
I201106 16:15:32.668491 40 ccl/sqlproxyccl/server.go:148  handling client 127.0.0.1:54432
I201106 16:15:32.668544 40 ccl/sqlproxyccl/server.go:150  client 127.0.0.1:54432 disconnected after 0.00s: <nil>
I201106 16:15:32.676866 69 ccl/sqlproxyccl/server.go:148  handling client 127.0.0.1:54434
    proxy_test.go:119: 
        	Error Trace:	proxy_test.go:119
        	Error:      	"failed to connect to `host=localhost user=unused database=defaultdb_29`: dial error (dial tcp [::1]:43363: connect: cannot assign requested address)" does not contain "unable to reach backend SQL server"
        	Test:       	TestFailedConnection/defaultdb_29?sslmode=verify-full&sslrootcert=testserver.crt
    --- FAIL: TestFailedConnection/defaultdb_29?sslmode=verify-full&sslrootcert=testserver.crt (0.02s)
```

PR: https://github.com/cockroachdb/cockroach/pull/56363

**Comment by spaskob** [comment]
This issue seems relevant https://github.com/golang/go/issues/39568

**Comment by spaskob** [comment]
We can make the test pass with `export GODEBUG='x509ignoreCN=0` but this may be a symptom of a bigger problem.

**Comment by tbg** [comment]
I would errors.Wrapf the messages from the stdlib and in the tests assert on the fmt string of our wrapf to become independent of errors returned from the stdlib.

**Comment by spaskob** [comment]
I don't follow how this would fix the test.

**Comment by spaskob** [comment]
IMO the proper fix would be to regenerate the test server certificate to include SAN.

**Comment by otan** [comment]
I think the test can be fixed by regenerating the certificate (https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/sqlproxyccl/testserver.crt)

**Comment by spaskob** [comment]
What are the steps to regenerate it?

**Comment by otan** [comment]
can probably use https://www.cockroachlabs.com/docs/v20.1/cockroach-cert.html

**Comment by tbg** [comment]
Sorry, hadn't understood the issue when I last responded.
Regenerating sounds right. I thought I left an openssl incantation in a
comment in this pkg somewhere but I could be wrong. (On phone, sorry)

**Comment by spaskob** [comment]
No worries thanks for you help!
```
$ git grep openssl pkg/ccl/sqlproxyccl/
pkg/ccl/sqlproxyccl/proxy_test.go:32:openssl genrsa -out testserver.key 2048
pkg/ccl/sqlproxyccl/proxy_test.go:34:openssl req -new -x509 -sha256 -key testserver.key -out testserver.crt -days 3650
```
