### ISSUE TITLE
inconsistent display of table name with EXPLAIN and EXPLAIN ANALYZE

### ISSUE THREAD

**Issue by gliptak** [cockroachdb/cockroach#56372]
**Describe the problem**

Inconsistent display of table name with EXPLAIN and EXPLAIN ANALYZE

**To Reproduce**

```
CREATE TABLE authors (
    id INT PRIMARY KEY, 
    name STRING);

INSERT INTO authors VALUES (1, 'Toni Morrison'),
                           (2, 'James Tiptree'),
                           (3, 'Richard Wright');

root@:26257/movr> EXPLAIN SELECT name FROM authors WHERE id=2;
    tree    |    field    |   description
------------+-------------+------------------
            | distributed | false
            | vectorized  | false
  render    |             |
   └── scan |             |
            | table       | authors@primary
            | spans       | /2-/2/#
(6 rows)

Time: 895.2µs

root@:26257/movr> EXPLAIN ANALYZE SELECT name FROM authors WHERE id=2;
  automatic |

                                                                         url
------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    false   | https://cockroachdb.github.io/distsqlplan/decode.html#eJyMkE9Lw0AQxe9-imG8KKymCSqyILRqxEBsa1LwHzlss0MNJNm4s0FLyXeXJIp4EDzOm_fe_nZ2yG8lSgwfl_EsmsNsPoufnkM4uI7SVXofH0IaxuHVCmpVEdwkiztQrXs1luHhNkxCKDRcQIACa6NpripilC_oYyawsSYnZmN7aTcYIv2BciKwqJvW9XImMDeWUO7QFa4klLhS65ISUpqsN0GBmpwqyqG2sUWl7Hb6hYAC00bVLMELjrzA20eBi9ZJmPZA1rwzWFJago8C2amyBFdUJME_Pjs9r_r8euvo23USwCVmnUDTuh88dmpDKP1O_P8LCXFjaqZf9H81T7pMIOkNjWdi09qcltbkwzPjuBhyg6CJ3bj1xyGqx1WXdXufAQAA__9N75LN
(1 row)

Time: 3.267ms
```
authors@primary

vs

primary@authors

![image](https://user-images.githubusercontent.com/50109/98394353-9d040880-2028-11eb-8544-fc7912a06cf8.png)

**Expected behavior**

Table name displayed consistently

**Environment:**
 - CockroachDB version v20.1.6
 - Server OS: Linux
 - Client app [e.g. `cockroach sql`

**Comment by andreimatei** [comment]
I think we should change the distsql diagram to read `authors@primary`.

**Comment by awoods187** [comment]
Thanks for the feedback. This is timely as we are updating our representation of EXPLAIN ANALYZE cc @RaduBerinde @Annebirzin

**Comment by yuzefovich** [comment]
We have actually already fixed this inconsistency on 20.2 branch (#52085), so I'll close this issue.

**Comment by yuzefovich** [comment]
I'll backport that PR to 20.1 branch.

**Comment by SWDevAngel** [comment]
@gliptak Thank you for contributing to CockroachDB this year. As a token of our appreciation we would like to send you a gift. Please DM me on our [community Slack](https://cockroa.ch/slack) `@lisa` so I can send you a link. (If you don’t want a gift, we also have a charitable contribution choice.) All orders need to be in by December 13, so please send this asap. :)
