### ISSUE TITLE
build: auto-generate BUILD files after every commit

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#56383]
We'll want to provide a way for developers to auto-generate BUILD files after each commit. BUILD files get updated when files are renamed/deleted, and when the set of dependencies in a package changes. Currently this shows up in CI when asserting on a clean work state, but it's pretty annoying to find out that way. It's also annoying to remember to run `bazel run //:gazelle` after each commit in a multi-commit PR.

Jira issue: CRDB-2944

**Comment by otan** [comment]
This "goes away" when we actually use bazel and people are forced to generate files to run bazel commands.

I'm not opposed to an auto generate on commit thing, but due to its speed I'd like for it to be opt in.
