### ISSUE TITLE
storage: move sequence cache usage out of critical path

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#5639]
Right now we only increase the sequence number on each batch request. However, if we make sure there's a sequence number of every item in the batch request, we will be able to do away with putting sequence cache entries for everything except the case where we push (don't really need this one) or abort a txn and poison the cache.

We could do this by moving the txn sequence number into the TxnMeta and comparing on MVCC put ops. A smaller or equal sequence number would mean a replay. I thought about the various combinations of delete range and conditional put and don't see any holes in it. The performance improvements would be relatively good (see below). The biggest issue is a bit more complexity with the sequence numbers.
```
benchmark                           old ns/op     new ns/op     delta
BenchmarkInsert1_Cockroach-4        447854        360615        -19.48%
BenchmarkInsert10_Cockroach-4       760230        675234        -11.18%
BenchmarkInsert100_Cockroach-4      3468452       3019973       -12.93%
BenchmarkInsert1000_Cockroach-4     31689628      28952029      -8.64%
BenchmarkUpdate1_Cockroach-4        656763        588049        -10.46%
BenchmarkUpdate10_Cockroach-4       1243524       1117886       -10.10%
BenchmarkUpdate100_Cockroach-4      6959819       6205097       -10.84%
BenchmarkUpdate1000_Cockroach-4     60140772      54035557      -10.15%
BenchmarkDelete1_Cockroach-4        633106        569684        -10.02%
BenchmarkDelete10_Cockroach-4       1530912       1300266       -15.07%
BenchmarkDelete100_Cockroach-4      11397325      10149334      -10.95%
BenchmarkDelete1000_Cockroach-4     116230583     105597876     -9.15%
```

Photos app against a live cluster seems to do about 5-10% better as well, so this might be a pretty significant improvement. Also less garbage to clean up.

**Comment by spencerkimball** [comment]
From Tobias:

> Ok. Would've been nice to also get rid of the read in the synchronous path, but this looks like a significant improvement (I'd go as far as calling it a "pretty sweet deal").
Btw, for GC'ing the remaining abort-poison entries without recourse to the transaction table, we can simply take a (large enough, like 5) multiple of the heartbeat timeout and make sure that TxnCoordSender will not allow new requests for a transaction it hasn't managed to heartbeat in (say) 2x HeartbeatInterval. That guarantees that by the time we delete those sequence cache entries, the transaction has indeed terminated (i.e. there's no client going around not reading what it wrote).

> Your PR #5626 also makes more sense in this context because sequence cache hits are actually really rare with the above.

> As for the sequence numbers, I think that one desirable property is not to make it harder for future versions of DistSender (or whatever might take its place) to parallelize requests. Ideally, there would be one request number per batch chunk sent, and sending to multiple ranges would simply give incrementing IDs (btw, the split-mismatch-erroneous-restart phenomenon disappears as well!) and be free to send in parallel (with unrelated constraints, of course). The problem is that a) we increment sequence numbers in the Store retry loop and b) we kind of want incrementing sequence numbers in each batch while we execute it or we must deal with self-overlap again.
>
> My initial take:
>
> * reserve some lower bits for the Store retries and the upper bits for Coordinator retries (if the Store runs out of its local bits, the transaction needs to restart - should be very unlikely unless it's doomed anyway). If Sequence were a 64bit-int, we'd definitely have enough room.
> * If we give ourselves enough Store bits, we could use allocate a number for each request (i.e. use increments of `len(ba.Requests)` in `(*Store).Send`). Since this is all Store-local, I think it's fair to use the context.Context (#5255) to avoid passing around another parameter anywhere (but that can be discussed).
> * Or we try to use the same one and keep overlap information via a `RangeGroup`. Probably only an interesting option if we do find that that has other unrelated upshots.

**Comment by spencerkimball** [comment]
@tschottdorf I think the read in the synchronous path will be meaningless. Since this will only include poisonings on abort, each range's sequence cache will not be more than a block or so, so I'd expect this to all be served out of RocksDB block cache for an active range. I'll test that. If those reads are still part of the critical path, we could always just cache the sequence cache ourselves, but I doubt it will come to that.

**Comment by tschottdorf** [comment]
@spencerkimball looks like you got that one good, no?

**Comment by spencerkimball** [comment]
Yep, this should be closed.
