### ISSUE TITLE
sql: virtual index range scans cause panic

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#56440]
Running queries with `pgadmin` currently causes a node crash, with the following stack trace:

```
panic: mutation disallowed

goroutine 156 [running]:
github.com/cockroachdb/cockroach/pkg/sql/opt/constraint.(*Spans).Truncate(0xc0020520c0, 0x1)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/constraint/spans.go:81 +0x11c
github.com/cockroachdb/cockroach/pkg/sql.virtualDefEntry.makeConstrainedRowsGenerator.func1(0x9437580, 0xc001fe6860, 0x2, 0x1)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:604 +0x4ec
github.com/cockroachdb/cockroach/pkg/sql.setupGenerator.func2(0x94d74e0, 0xc001fec480, 0xc00188a1e0, 0xc0009be690, 0xc001fe6860)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:115 +0x109
created by github.com/cockroachdb/cockroach/pkg/sql.setupGenerator
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:104 +0xf7
```

This ticket tracks fixing the immediate bug, as well as making sure that panics from the virtual table row pusher don't crash the server and are instead forwarded to the main SQL execution goroutine.

**Comment by joshimhoff** [comment]
From the log lines, I couldn't tell if this crashed the server or was caught. Does it crash the server? Sounds like yes.

Also IIUC the log statement was INFO level. If it crashes the server, it should be FATAL level.

**Comment by jordanlewis** [comment]
There's no log line for this - it's getting printed by Go's runtime, due to an unhandled panic. I agree it should be FATAL, but this goroutine didn't have any special handling for panics - in those cases, the runtime crashes the whole program.

It crashes the server, yes. We normally have handlers that prevent these situations in SQL. The bug, besides the bug itself, is that this goroutine does not.

**Comment by joshimhoff** [comment]
Ack thanks for the color.

**Comment by jordanlewis** [comment]
So far, I don't think this is reproducible on 20.1. Here is a query that will reproduce the panic on 20.2:

```
demo@127.0.0.1:64504/movr> select * from pg_catalog.pg_class where oid > 100 and oid < 200;
panic: mutation disallowed

goroutine 5825 [running]:
github.com/cockroachdb/cockroach/pkg/sql/opt/constraint.(*Spans).Truncate(0xc001c74ac0, 0x1)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/constraint/spans.go:81 +0x11c
github.com/cockroachdb/cockroach/pkg/sql.virtualDefEntry.makeConstrainedRowsGenerator.func1(0x9437580, 0xc0021ae960, 0x2, 0x1)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:604 +0x4ec
github.com/cockroachdb/cockroach/pkg/sql.setupGenerator.func2(0x94d74e0, 0xc00312dfc0, 0xc001d17560, 0xc0031383c0, 0xc0021ae960)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:115 +0x109
created by github.com/cockroachdb/cockroach/pkg/sql.setupGenerator
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:104 +0xf7
```

**Comment by joshimhoff** [comment]
Could we mitigate this bug without a patch upgrade with a SQL deny list?

**Comment by jordanlewis** [comment]
Probably not with the current thinking on deny lists - you'd need to prevent range scans on all virtual catalog tables that happen to have virtual indexes on them. But determining range scans isn't as easy as a regex, since the optimizer does stuff like coalescing adjacent point scans into a range scan (`select * from t where t = 3 or t = 4` becomes `select * from t where t >=3 and t <= 4`. And, even if we could write such a regex, the regex would have to include a very specific subset of tables, which seems a bit odd and error prone.

**Comment by joshimhoff** [comment]
^^ Sounds liken interesting info to consider when building a SQL deny list.
