### ISSUE TITLE
ui: count of transaction graph not showing commits when retrying

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#5644]
the photos app running against the beta cluster was just upgraded to a version that uses https://github.com/cockroachdb/cockroach-go/blob/master/crdb/tx.go to retry transactions.

As soon as that happened, the SQL transaction graph dropped to zero for Commits:
https://beta.cockroachdb.com:8080/#/nodes/graphs 

The KV transactions graph looks ok though.

**Comment by mberhault** [comment]
We should also see if we can get a graph of transaction retries in there somewhere.

**Comment by cuongdo** [comment]
It seems like the SQL retry mechanism isn't updating stats correctly. That's a bug introduced by the retry functionality, so reassigning to @andreimatei.
