### ISSUE TITLE
auth: support multi-region configuration for OIDC

### ISSUE THREAD

**Issue by dhartunian** [cockroachdb/cockroach#56517]
Previously, the `redirect_url` parameter used in the OIDC flow was set as a static string by the user. This made supporting multiple OIDC flow origins difficult since a customer could have a complex and changing multi-region configuration with many hosts. In addition, supporting both node-specific logins and load balancer logins was challenging as they had different URLs themselves.

This feature eliminates the need for a `redirect_url` parameter set by the user altogether. By extracting information available in the initial OIDC login request we can construct what is a likely valid callback URL automatically.

The callback URL is composed of 3 elements: scheme, host, and path. Here’s how they will be automatically chosen:

Scheme is always “https”. This is a requirement for OIDC authentication already.

Host is read from the `Host` HTTP header on the initial login request. This will contain the host and port that the request is served for. It is assumed that the callback URL will be at this same host. Any CRDB instance that serves the login route can always serve the callback route as well.

Path is the login path with “oidc/v1/login” replaced by “oidc/v1/callback”. This will capture any path prefix that a load balancer imposes.

For example, if the original login URL is:

https://crdb.region-us-west-2.example.com:8080/node0/oidc/v1/login

The computed `redirect_url` is:

https://crdb.region-us-west-2.example.com:8080/node0/oidc/v1/callback

(If we assume that the `Host` header is “crdb.region-us-west-2.example.com:8080” and the path is “node0/oidc/v1/login”)

*Updated Sequence Diagram*

![bPDHJzim4CVV-obEuGKqQBOn8Irg8w1CR1BR41jlaS1rBerLr-viXuvllxETMI70fBr4jkFxtz-_kpkrZXdNRUJatEYTHGD79InkBiuBM4Z1rw0LP5Tw9HJiX6lX-vUBHJPHsY58R5m1bvz-Ggv5pVE7Txdq5olrMLlwC_CouDVb92oJyYKgD8ma35Erti0Q7m_1Ed_Yz1hLb2IORUCcvgKhj8MjqNN7-sjVpnOZuLcZbGEk](https://user-images.githubusercontent.com/986307/102238247-87a1ba00-3ec3-11eb-977e-9d39f5fc888a.png)

**Comment by fabiog1901** [comment]
Zendesk [6731](https://cockroachdb.zendesk.com/agent/tickets/6731)
