### ISSUE TITLE
bulkio: temporary tables with duplicate names prevent database/table backup/restore

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#56511]
Consider a database with 2 temporary tables created with the same name in the same database (on different connections). When this happens, all non-cluster backups are blocked:

```
> backup d1.t to 'nodelocal://1/table';
ERROR: duplicate table name: "defaultdb"."my_default_temp_table" used for ID 55 and 53
```

Cluster backups in this state succeed. However, performing a non-cluster restore of one of these cluster backups results in the same error:
```
restore database d1 from 'nodelocal://1/cluster';
ERROR: duplicate table name: "defaultdb"."my_default_temp_table" used for ID 55 and 53
```

Cluster restores fail differently, but for similar reasons:
```
> restore from 'nodelocal://1/cluster';
ERROR: restoring 0 TableDescriptors from 2 databases: restoring table desc and namespace entries: table already exists
SQLSTATE: 42710
```

**Comment by pbardea** [comment]
This is partially addressed (for the non-cluster backup/restores cases) by https://github.com/cockroachdb/cockroach/pull/56475.

Still actively investigating fixes for the cluster restore case.

**Comment by adityamaru** [comment]
Closed by https://github.com/cockroachdb/cockroach/pull/56956, backported to 20.2 and 20.1.
