### ISSUE TITLE
ui: too many internal statements are shown in Transactions page

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#56590]
Many statements appear in the Transactions page that do not appear in the Statements page. These statements seem to all be internal statement.

Repro:

Open up `cockroach demo`.

Go to the web ui.

Statements page:

![image](https://user-images.githubusercontent.com/43821/98872757-18105900-2445-11eb-92a8-e6b557b958f6.png)

Transactions page:

![image](https://user-images.githubusercontent.com/43821/98872778-2494b180-2445-11eb-85fe-516b74f29223.png)

Notice that there are many more transactions than statements, and many statements within each transaction that are internal and do not correspond to statements in the statements page.

Jira issue: CRDB-2923

**Comment by robert-s-lee** [comment]
it looks like the filtering definition of statement page `All`  `(Internal)`  `(unset)` is different from the transactions page

**Comment by solongordon** [comment]
@arulajmani Would you please investigate whether this should be addressed on the database side or the frontend?

**Comment by arulajmani** [comment]
@robert-s-lee is correct -- the statements page doesn't show internal statements in the `All` option, where as the transactions page does. If you filter by `$cockroach demo`, you'll the results will be in tune with the `All` option on the statements page. Additionally, you'll see the internal statements as seen in the transactions page above if you select the `(internal)` app on the statements page. Therefore, I think this will require a change on the frontend side.
