### ISSUE TITLE
storage: calculating capacity is O(# sstables)

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/cockroach#56620]
`kvserver.(*Store).Capacity` occupied ~15% of a 30-second CPU profile and was responsible for 7.5% of allocated objects during a 18 TiB import.
![Screen Shot 2020-11-12 at 12 28 25 PM](https://user-images.githubusercontent.com/867352/98975675-658fd300-24e4-11eb-9dd8-259a644d07b7.png)

`storage.computeCapacity` walks the entire data directory.

https://github.com/cockroachdb/cockroach/blob/64592c3b218f69dba805bb760a190af996b71d55/pkg/storage/mvcc.go#L3764-L3849

**Comment by petermattis** [comment]
I think we could avoid the bulk of the filesystem walk by using the Pebble aggregate metrics. We'd want to incorporate the metrics from the temporary store directory, and from the `auxiliary` directory (which I think contains side-loaded data).

**Comment by jbowens** [comment]
I think we also need to update Pebble metrics to include aggregate size of obsolete files. We already include the size of zombie tables, but not obsolete files waiting to be deleted. Large DROPs and deletion pacing could make that a nontrivial amount.

**Comment by petermattis** [comment]
> I think we also need to update Pebble metrics to include aggregate size of obsolete files. We already include the size of zombie tables, but not obsolete files waiting to be deleted. Large DROPs and deletion pacing could make that a nontrivial amount.

@itsbilal has added that in https://github.com/cockroachdb/pebble/pull/981.

**Comment by jbowens** [comment]
It looks like there are a handful of other disk usage sites that we're currently missing from `pebble.Metrics`:

- `Metrics.WAL.Size` may underreport if WALs are recycled. Ideally, we'd have a `Metrics.WAL.PhysicalSize` that reports the max length of the log file over its lifetime.
- Obsolete WALs sitting in the logRecycler are unreported.
- The size of the `MANIFEST`, or the `OPTIONS` file, isn't available. The `OPTIONS` file isn't going to be significant but the `MANIFEST` is fairly large.
