### ISSUE TITLE
BulkIO: Use multiple characters for a delimiter on an input file

### ISSUE THREAD

**Issue by fabiog1901** [cockroachdb/cockroach#56650]
Currently for data file imports we accept only 1 char as delimiter (default = ',') and this request is to allow for multiple chars, as for example ';;'.

Example:

```
$ cat c.csv
1;;a
2;;b
3;;c
```

At the SQL prompt:

```
root@:26257/defaultdb> IMPORT TABLE customers (
        id INT8 PRIMARY KEY,
        name STRING,
        INDEX name_idx (name)
)
CSV DATA ('nodelocal://1/c.csv') with delimiter = ';;'
;
ERROR: invalid comma value: must be only one character
SQLSTATE: 42601
```

**Zendesk:** [6771](https://cockroachdb.zendesk.com/agent/tickets/6771)

**Comment by mwang1026** [comment]
I'm going to close this for now. We don't have plans to do this anytime soon since there is a workaround (albeit no ideal) which is to preprocess the file. It's a pretty big change (maybe a rewrite) to our parser so a bit big to commit to for relative value.
