### ISSUE TITLE
enum: add IF NOT EXISTS option

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#56651]
**Is your feature request related to a problem? Please describe.**
Trying to handle case where ENUM already exists

**Describe the solution you'd like**
Add `IF NOT EXISTS` clause

**Describe alternatives you've considered**
dropping and recreating an ENUM type is an option.

**Additional context**

```sql
CREATE TYPE "zone" IF NOT EXISTS AS ENUM ('us', 'anz', 'eu');
```

```sql
root@localhost:26257/idagent> CREATE TYPE "zone" IF NOT EXISTS AS ENUM ('us', 'anz', 'eu');
invalid syntax: statement ignored: at or near "if": syntax error: unimplemented: this syntax
SQLSTATE: 0A000
DETAIL: source SQL:
CREATE TYPE "zone" IF NOT EXISTS AS ENUM ('us', 'anz', 'eu')
                   ^
HINT: You have attempted to use a feature that is not yet implemented.
See: https://go.crdb.dev/issue-v/27793/v20.2
```

**Comment by dbist** [comment]
surprisingly, `IF EXISTS` works

```sql
DROP TYPE IF EXISTS type;
```

```sql
root@localhost:26257/idagent> DROP TYPE IF EXISTS type;
DROP TYPE

Time: 299ms total (execution 56ms / network 243ms)
```

**Comment by teddylear** [comment]
I can take a look into this.

**Comment by rafiss** [comment]
@teddylear thank you! i'd recommend referring to another PR like this to get an idea of what you need to change https://github.com/cockroachdb/cockroach/pull/52936

**Comment by teddylear** [comment]
@rafiss Ah sorry misread the labels on the issue, I'm not too familiar with C/C++ and looking to help with any golang contributions. Someone else should feel free to pick up this issue.

**Comment by rafiss** [comment]
@teddylear No problem! But just to clarify, resolving this issue does not require any C/C++ knowledge. It requires a small modification to the YACC grammar file, and some Golang modifications to make the `tree.CreateType` struct have an `IfNotExists` flag.

**Comment by teddylear** [comment]
Ohhhh then let me review the other PR and see if I can make the change

**Comment by naivcit** [comment]
Hey @teddylear just wanted to follow up if you are working on this one ,just in case  I have already made the required changes for this issue and would love to submit a PR for the same .

**Comment by teddylear** [comment]
@naivcit nope, all yours!
