### ISSUE TITLE
build: upgrade Go version in builder image to Go 1.15.5

### ISSUE THREAD

**Issue by DuskEagle** [cockroachdb/cockroach#56664]
The Go version in our builder image was [recently bumped](https://github.com/cockroachdb/cockroach/commit/18b6937745c339264314413de61500e58253d9ee#diff-ce0204744a50127c828f7be8c74492542188e2868f9bbc6758326c8ba5f61601) from 1.13.14 to 1.15.4. We should bump the Go version to 1.15.5, which was recently released. 

CockroachDB v20.2 and below were built on Go 1.13 or less, so this change does not need to be backported.

**Comment by otan** [comment]
Done: https://github.com/cockroachdb/cockroach/pull/56786
