### ISSUE TITLE
sql: high memory usage in logictests in newSpillingQueue

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#56701]
This doesn't happen every time, but many times when I run logictests, they start using a ton of memory. I narrowed it down to the fakedist-spec-planning configs (though I'm not certain it doesn't happen in other configs too). I run:

```
make test PKG=./pkg/sql/logictest 'TESTS=Test(Planner|)Logic$$/^^fakedist-spec-planning$$/' TESTFLAGS= TESTTIMEOUT=20m
```

And I see the processes (GOMAXPROCS=8) take more and more memory over time, up to 27+GB.

I managed to get an interesting memory profile using this diff:
```
diff --git a/pkg/sql/logictest/logic.go b/pkg/sql/logictest/logic.go
index 5b78f9d7b2..ee0a58e5f9 100644
--- a/pkg/sql/logictest/logic.go
+++ b/pkg/sql/logictest/logic.go
@@ -27,7 +27,9 @@ import (
 	"path/filepath"
 	"reflect"
 	"regexp"
+	"runtime"
 	"runtime/debug"
+	"runtime/pprof"
 	"runtime/trace"
 	"sort"
 	"strconv"
@@ -2950,6 +2952,23 @@ func RunLogicTestWithDefaultConfig(
 	runCCLConfigs bool,
 	globs ...string,
 ) {
+	{
+
+		f, err := os.Create("woo.out")
+		if err != nil {
+			t.Fatalf("could not create memory profile: %s", err)
+		}
+		go func() {
+			time.Sleep(30 * time.Second)
+			runtime.GC() // get up-to-date statistics
+			if err := pprof.WriteHeapProfile(f); err != nil {
+				panic(fmt.Sprintf("could not write memory profile: %s", err))
+			}
+			f.Close()
+		}()
+
+	}
+
 	// Note: there is special code in teamcity-trigger/main.go to run this package
 	// with less concurrency in the nightly stress runs. If you see problems
 	// please make adjustments there.
```

The profile shows the memory is in `colexec.newSpillingQueue`.
![image](https://user-images.githubusercontent.com/16544120/99166576-d7217a00-26ba-11eb-979f-4ee704ffd752.png)

**Comment by RaduBerinde** [comment]
Attached profile.
[profile.zip](https://github.com/cockroachdb/cockroach/files/5541867/profile.zip)

**Comment by RaduBerinde** [comment]
It's possible this has to do with the `coldata.BatchSize` randomization. It might just be something insanely inefficient when it is set to 1.

**Comment by RaduBerinde** [comment]
I ran more tests and it's not specific to `fakedist-spec-planning`. It happens with `fakedist` as well. If I set BatchSize to always be 1, it seems to happen every time. If I let it be the default value, it doesn't happen. Looking at the code, it makes sense - we are allocating a huge slice of items when BatchSize is 1.

**Comment by RaduBerinde** [comment]
I tried accounting for the items slice and that helped a bit, but it still uses a lot (~16GB down from 27GB). Since the usage keeps growing as the test continues, it still feels like there's a leak.

```diff
-	itemsLen := memoryLimit / int64(colmem.EstimateBatchSizeBytes(typs, coldata.BatchSize()))
+	perItemMem := int64(colmem.EstimateBatchSizeBytes(typs, coldata.BatchSize()))
+	perItemMem += int64(unsafe.Sizeof(coldata.Batch(nil)))
+	itemsLen := memoryLimit / perItemMem
```

**Comment by yuzefovich** [comment]
Thanks for filing the issue Radu. I looked over the code, and I don't think there is a memory leak, rather GC is slow to reclaim no longer used spilling queues (those are created by the hash routers and merge joins). I think in addition for more accounting as you added in the diff above we also want to have a cap so that in the edge cases we don't create slices with millions of items. I'll open up a PR.
