### ISSUE TITLE
release v20.2.2

### ISSUE THREAD

**Issue by nathanstilwell** [cockroachdb/cockroach#56757]
# This is now obsolete since we picked a new SHA on 2020-11-24. See the new comment below.

~Candidate SHA: `36822fee607976556f265c683da0eaffcfdfec8b`~
~Deployment status: `Preparing`~
~Make and Publish Build: [#478](https://teamcity.cockroachdb.com/buildConfiguration/Internal_Release_MakeAndPublishBuild/2445385?buildTab=overview)~
~Build ID: `v20.2.0-180-g36822fee60`~
~Qualify Build: [#266](https://teamcity.cockroachdb.com/buildConfiguration/Internal_Release_Qualify/2445391)~

## Restarting release

Due to [an issue](https://github.com/cockroachdb/cockroach/issues/56804), this release was restarted

### Release details
Candidate SHA: `4aabe9625bcaf74d6c25bfc3c88cfe7662cb2d80`
Deployment status: `Preparing`
Make and Publish Build: [#494](https://teamcity.cockroachdb.com/buildConfiguration/Internal_Release_MakeAndPublishBuild/2454848?buildTab=overview)
Build ID: `v20.2.0-216-g4aabe9625b`
Qualify Build: [#275](https://teamcity.cockroachdb.com/buildConfiguration/Internal_Release_Qualify/2454884)
Publish Cockroach Release: -----

 
CC Clusters Running the Build:
[perilous-python](https://cockroachlabs.cloud/cluster/2f668548-e9b9-49d2-a47f-600058ca1c91/overview?cluster-type=custom) in [CockroachCloud](https://cockroachlabs.cloud)
 
[Release process checklist](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process)
 
Prep date: `Wednesday 18 NOV`
- [x] [Pick a SHA](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-2.PickaSHA)
- [x] fill in `Candidate SHA` above
- [x] fill in `Build ID` above
- [x] fill in `Make and Publish Build` above
- [x] fill in `Qualify Build` above
- [x] [Announce the release to releases@](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-3.Announcethereleasetoreleases@)
- [x] [4. Ask SRE to run the build on some CC clusters](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-4.AskSREtorunthebuildonsomeCCclusters)
 
5-8: Qualify the Release. See [Release Qualification](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification)
- Short-running Checks:
- [x] [5. Verify node crash reports](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification#Verify-node-crash-reports-appear-in-sentry.io) ([report](https://sentry.io/organizations/cockroach-labs/issues/1971445883/events/?environment=v20.2.0-180-g36822fee60&project=164528&statsPeriod=14d))

_for `v20.2.x` releases we are foregoing the practice of running `roachprod` qualifications clusters and solely relying on CockroachCloud qualification clusters instead_
 
**Do not proceed below until the release date.**
 
Release date: `WIP fill in date: usually Monday WIP`
- [ ] [7 continued: Check cluster status](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification#Monitoring-the-Qualification-Clusters)
- [ ] 8. Destroy clusters
- [ ] [9. Publish Cockroach Release](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-9.PublishTheRelease)
- [ ] Acked security@ and release-engineering-team@ on the generated AWS S3 bucket write alert to confirm these writes were part of a planned release (See [Publish Cockroach Release](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-9.PublishTheRelease) for details).
- [ ] [10. Remove staging branch / tags from repository](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-10.Removestagingbranch/tags)
- [ ] [11. Check binaries](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-11.CheckBinaries)
- [ ] [12. Check docker image](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-12.Checkthedockerimage)
- [ ] [13.Announce the release is cut to releases@](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-13.Announcethereleaseiscuttoreleases@)
- [ ] [14. Update version numbers](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-14.Updateversionnumbers)
- For production or stable releases in the latest major release series only (in August 2020, this is the v20.1 series):
- [ ] Update [Brew Recipe](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Brewrecipe)
- [ ] Update [Orchestrator configurations:CRDB](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Orchestratorconfigurations:CRDB)
- [ ] Update [Orchestrator configurations:Helm Charts](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Orchestratorconfigurations:HelmCharts)
- For all production or stable releases:
- [ ] [Announce version to registration cluster](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-AnnounceVersionToRegCluster)
- [ ] [Update version map in bin/roachtest and regenerate test fixtures](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Updateversionmapinroachtestandregeneratetestfixtures)
- [ ] 15. Update docs (handled by Docs team)
- [ ] 16. External communications for release (handled by Marketing eam)
 
Cleanup:
 
- [ ] Remove staging branch / tags from repository
- [ ] Destroy roachprod clusters

**Comment by lucy-zhang** [comment]
We're cherry-picking https://github.com/cockroachdb/cockroach/commit/a3063889b89770d9ecca6d7b83f19998de5bfc7a on top of the previous candidate SHA.

**Comment by lucy-zhang** [comment]
# New v20.2.2 candidate SHA:

Candidate SHA: `WIP EDIT ME WIP.`
Deployment status: `WIP EDIT ME WIP.`
Make and Publish Build: WIP EDIT ME WIP.
Qualify Build: WIP EDIT ME WIP.
Publish Cockroach Release: WIP EDIT ME WIP.
 
CC Clusters Running the Build:
- WIP EDIT ME WIP.
 
Admin UI for Qualification Clusters:
- Old Version: WIP EDIT ME WIP.
- New Version: WIP EDIT ME WIP.
 
Working Tags:
- Build ID: `WIP EDIT ME WIP.`
- `staging-*` tag: `WIP EDIT ME WIP.`
 
[Release process checklist](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process)
 
Prep date: `WIP fill in date to roll out: usually Monday, a week before the release WIP`
- [ ] [2. Pick a SHA](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-2.PickaSHA)
- [ ] fill in `Candidate SHA` above
- [ ] fill in `staging-* Tag` above
- [ ] fill in `Build ID` above
- [ ] fill in `Make and Publish Build` above
- [ ] fill in `Qualify Build` above
- [ ] email thread on releases@
 
- [ ] [3. Announce the release to releases@](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-3.Announcethereleasetoreleases@)
- [ ] [4. Ask SRE to run the build on some CC clusters](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-4.AskSREtorunthebuildonsomeCCclusters)
 
5-8: Qualify the Release. See [Release Qualification](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification)
- Short-running Checks:
- [ ] [5. Verify node crash reports](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification#Verify-node-crash-reports-appear-in-sentry.io)
- Qualification Clusters:
- [ ] [6. Setup Qualification Clusters](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification#Setup-Qualification-Clusters)
- [ ] fill in all WIP elements above (Admin UI, etc.)
 
 
Monitoring the Qualification Clusters (ideally one day after creation, halfway through the week, and before the release):
 
- [ ] [7. Keep an eye on clusters](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification#Monitoring-the-Qualification-Clusters) until release date.
 
**Do not proceed below until the release date.**
 
Release date: `WIP fill in date: usually Monday WIP`
- [ ] [7 continued: Check cluster status](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification#Monitoring-the-Qualification-Clusters)
- [ ] 8. Destroy clusters
- [ ] [9. Publish Cockroach Release](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-9.PublishTheRelease)
- [ ] Acked security@ and release-engineering-team@ on the generated AWS S3 bucket write alert to confirm these writes were part of a planned release (See [Publish Cockroach Release](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-9.PublishTheRelease) for details).
- [ ] [10. Remove staging branch / tags from repository](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-10.Removestagingbranch/tags)
- [ ] [11. Check binaries](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-11.CheckBinaries)
- [ ] [12. Check docker image](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-12.Checkthedockerimage)
- [ ] [13.Announce the release is cut to releases@](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-13.Announcethereleaseiscuttoreleases@)
- [ ] [14. Update version numbers](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-14.Updateversionnumbers)
- For production or stable releases in the latest major release series only (in August 2020, this is the v20.1 series):
- [ ] Update [Brew Recipe](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Brewrecipe)
- [ ] Update [Orchestrator configurations:CRDB](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Orchestratorconfigurations:CRDB)
- [ ] Update [Orchestrator configurations:Helm Charts](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Orchestratorconfigurations:HelmCharts)
- For all production or stable releases:
- [ ] [Announce version to registration cluster](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-AnnounceVersionToRegCluster)
- [ ] [Update version map in bin/roachtest and regenerate test fixtures](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Updateversionmapinroachtestandregeneratetestfixtures)
- [ ] 15. Update docs (handled by Docs team)
- [ ] 16. External communications for release (handled by Marketing eam)
 
Cleanup:
 
- [ ] Remove staging branch / tags from repository
- [ ] Destroy roachprod clusters

**Comment by lucy-zhang** [comment]
Travis for Linux is backlogged again, so I ran the Linux check on my gceworker:

```
lucy@gceworker-lucy2:~/bincheck$ ./test-linux
Downloaded https://binaries.cockroachdb.com/cockroach-v20.2.2.linux-amd64.tgz
ssh: connect to host localhost port 2222: Connection refused
VM not yet available; sleeping for 1 seconds
vvfat mnt chs 1024,16,63
qemu-system-x86_64: -drive file=fat:mnt,format=raw: Opening non-rw vvfat images without an explicit read-only=on option is deprecated. Future versions will refuse to open the image instead of automatically marking the image read-only.
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
Warning: Permanently added '[localhost]:2222' (ECDSA) to the list of known hosts.
Warning: Permanently added '[localhost]:2222' (ECDSA) to the list of known hosts.

Build Tag:        v20.2.2
Build Time:       2020/11/25 14:45:44
Distribution:     CCL
Platform:         linux amd64 (x86_64-unknown-linux-gnu)
Go Version:       go1.13.14
C Compiler:       gcc 6.3.0
Build Commit ID:  92d94952060fd24400906dc06e392d7a7419b392
Build Type:       release

Generating encryption key:
successfully created AES-128 key: aes-128.key

server not yet available; sleeping for 1 seconds
server not yet available; sleeping for 2 seconds
*
* WARNING: ALL SECURITY CONTROLS HAVE BEEN DISABLED!
*
* This mode is intended for non-production testing only.
*
* In this mode:
* - Your cluster is open to any client that can access any of your IP addresses.
* - Intruders with access to your machine or network can observe client-server traffic.
* - Intruders can log in without password and read or write any data in the cluster.
* - Intruders can consume all your server's resources and cause unavailability.
*
*
* INFO: To start a secure server without mandating TLS for clients,
* consider --accept-sql-without-tls instead. For other options, see:
*
* - https://go.crdb.dev/issue-v/53404/v20.2
* - https://www.cockroachlabs.com/docs/v20.2/secure-a-cluster.html
*
*
* WARNING: unable to load named timezones
* HINT: See: https://go.crdb.dev/issue-v/36864/v20.2
* --
* Check that the time zone database is installed on your system, or
* set the ZONEINFO environment variable to a Go time zone .zip archive.
*
*
* WARNING: neither --listen-addr nor --advertise-addr was specified.
* The server will advertise "buildroot" to other nodes, is this routable?
*
* Consider using:
* - for local-only servers:  --listen-addr=localhost
* - for multi-node clusters: --advertise-addr=<host/IP addr>
*
*
CREATE DATABASE
CREATE TABLE
INSERT 1
*
* INFO: Replication was disabled for this cluster.
* When/if adding nodes in the future, update zone configurations to increase the replication factor.
*
CockroachDB node starting at 2020-11-25 16:12:56.209789238 +0000 UTC (took 9.1s)
build:               CCL v20.2.2 @ 2020/11/25 14:45:44 (go1.13.14)
webui:               http://buildroot:8080
sql:                 postgresql://root@buildroot:26257?sslmode=disable
RPC client flags:    /bincheck/cockroach <client cmd> --host=buildroot:26257 --insecure
logs:                /root/cockroach-data/logs
temp dir:            /root/cockroach-data/cockroach-temp215473438
external I/O path:   /root/cockroach-data/extern
store[0]:            path=/root/cockroach-data
storage engine:      pebble
status:              initialized new cluster
clusterID:           051f04fa-eee7-4ce6-bcf9-517524f4ccde
nodeID:              1
Command "quit" is deprecated, see 'cockroach node drain' instead to drain a
server without terminating the server process (which can in turn be done using
an orchestration layer or a process manager, or by sending a termination signal
directly).
node is draining... remaining: 8
node is draining... remaining: 0 (complete)
ok
```
Same as https://github.com/cockroachdb/bincheck/pull/232. I'll document this somewhere later.

**Comment by jordanlewis** [comment]
This release has completed. https://www.cockroachlabs.com/docs/releases/v20.2.2

**Comment by lucy-zhang** [comment]
We still need to update the new versions in the latest major release series everywhere, so I'm reopening this. This was originally suspended while we thought we might soon have a v20.2.3, but that's not the case anymore.
