### ISSUE TITLE
opt: normalize @> operator to false with array containing NULLs

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#56799]
The contains operator (`@>`) always returns `false` when called with an array on the right-hand side that contains any null elements. For example, any predicate of the form `x @> ARRAY[..., NULL, ...]` can be normalized to `false`. This will be useful since it may unlock other types of optimizations that wouldn't be possible otherwise.

**Comment by mneverov** [comment]
hi, I'd like to work on this

**Comment by rytaft** [comment]
Great! It's all yours, @mneverov. Let us know if you need any pointers about where to make changes.
