### ISSUE TITLE
adding node to an existing 1-node cluster under load not graceful

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#5686]
Steps to reproduce (I used `roachdemo` for launch the `cockroach` instances):
1. Start a single-node cluster: `cockroach start --insecure --port=26257 --http-port=26258 --store=cockroach-data/1`
2. Run `./block_writer postgresql://root@localhost:26257?sslmode=disable`
3. Let `block_writer` run for 3 minutes
4. Add a second node to the cluster: `cockroach start --insecure --port=26259 --http-port=26260 --store=cockroach-data/2 --join=localhost:26257`

`block_writer` throughput immediately drops to 0, and admin UI and most other operations are really slow.

Log files:
[node1-stderr.txt](https://github.com/cockroachdb/cockroach/files/194221/node1-stderr.txt): the end of this log file has some stack traces I generated by sending `SIGABRT` to the cockroach process
[node2-stderr.txt](https://github.com/cockroachdb/cockroach/files/194219/node2-stderr.txt)

**Comment by bdarnell** [comment]
To some extent, this is expected: once there are two nodes, a single node is no longer a quorum, so everything must freeze until everything is replicated. We could make this less disruptive by making the replication/repair queue aware of the number of replications in flight so it doesn't ry to replicate everything at once.

Do you have the full logs? stderr doesn't include the info messages and doesn't give us a lot to go on.

The processRaft goroutine was generating a snapshot when it was killed. There were 140 snapshot-related error messages in the log. It's possible that it was regenerating snapshots for the same ranges repeatedly, in which case #5721 will help.

**Comment by cuongdo** [comment]
I didn't keep the logs, though it was easy to reproduce last night. I'll
try again after #5721 is merged in.

**Comment by cuongdo** [comment]
Looks like #5721 makes this significantly better. Before, the cluster would never be able to service even a single extra operation from block_writer. Now, it recovers pretty quickly.

Nice!
