### ISSUE TITLE
opt: ensure statistics builder correctly estimates selectivity of b @> '[]' and b @> '{}'

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#56870]
Prior to #56732, queries like `SELECT * from d where b @> '[]';` and `SELECT * from d where b @> '{}';` would cause a full scan of the primary index, even if there was an inverted index on column `b`.

After #56732, the optimizer now plans an inverted index scan for these queries followed by an inverted filter. This is a very bad plan, however, because `b @> '[]'` and `b @> '{}'` cause a full scan of the inverted index. The statistics builder should be taught that this is the case so that the optimizer will never choose an inverted index scan with these predicates.

**Comment by mgartner** [comment]
If there are many rows where `b` is a number, string, boolean, or null, for the `b @> '[]` filter it could be advantageous to scan the inverted index for all arrays; something like `/b: [/Arr - /Arr] [/[] - /[]]`. It's probably not a super common case though. And I'm not sure we could do the same for `b @> '{}'`.

**Comment by rytaft** [comment]
Good point! Hopefully our histograms will be able to give us a good idea about how selective these filters actually are for a given dataset. In some cases it might make sense to use the index.
