### ISSUE TITLE
sql: move the multi-region enum out of the public schema into a separate internal schema

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#56877]
#### Background

As of https://github.com/cockroachdb/cockroach/pull/56628, we plan to introduce a new kind of type descriptor for multi region enums. This type descriptor will be called `region` and will be created once for every multi region database. In the patch above, this type is created in the public schema. This is not ideal, because users may already have an object named `region` in their database which would prevent the creation of this type. 

####  Alternative 1:
We create a new internal schema `_crdb_internal` and place the enum inside this schema. Ideally, we'd have used `crdb_internal`, but we need something new here because that is a virtual schema. This schema would be introduced as a migration from 20.2 -> 21.1 for all existing databases. For all databases created 21.1 and beyond, this schema would be created by default. Additionally, we can reserve a special ID for this schema just like we do for `public` today to reduce an extra namespace lookup during resolution. A generic crdb internal schema is more desirable to a multi region specific one because it allows us to decouple name conflicts that arise outside the context of multi-region. Also, an internal physical schema that we have full control over may prove useful in the future. 

#### Alternative 2:
We create a multi region specific schema `crdb_internal_multi_region` and place the enum inside this schema. This will be created the first time a region is added to the database. When the last region is removed from the database, and therefore it is no longer "multi-region", we'll remove the schema in addition to removing the enum. 

I'm personally more inclined towards alternative 1, albeit slightly. cc @nvanbenschoten @ajwerner @otan

**Comment by otan** [comment]
Option 3: use the public schema.
This is what postgres extensions have to do. We do this atm for certain spatial types already.

Personally leaning towards alternative 1 atm, if we have more to add. i don't know if i enjoy the `crdb_internal` name though. maybe `crdb_system`? hehe....

**Comment by jordanlewis** [comment]
We shouldn't proliferate any more schemas if we can help it. If we can't figure out how to add it to `crdb_internal`, I'd prefer naming the enum `crdb_internal_regions` and leaving it in `public`.

**Comment by ajwerner** [comment]
I don't want to entertain the idea of making `crdb_internal` a real schema in each database. The virtual stuff is pretty self-contained. I guess we could do something crazy like making crdb_internal first resolve to the virtual schema and then fall through to a real physical schema but I wouldn't be happy about it.

I'm cool with option 3. On a different level, how does everybody feel about disallowing creation of *any* schema element in cockroach with the prefix `crdb_internal` -- no columns, no indexes, no indexes, no constraints, no views, no schemas, no types, nothing. Then we could stop talking about this. How many applications out there are we going to break? I'd hope none and if there are some, they are trolls.

**Comment by nvanbenschoten** [comment]
> I'd prefer naming the enum crdb_internal_regions and leaving it in public.

This option sounds good to me as well.

In #56628, this type is created only for multi-region databases. Will we delete it if a database removes all regions?

**Comment by arulajmani** [comment]
> I don't want to entertain the idea of making crdb_internal a real schema in each database.
Just for the sake of completion, I have to point out that that wasn't my suggestion. I was proposing creating a `_crdb_internal` (or any other reasonable name) which lived along side and orthogonal to the `crdb_internal` virtual schema. 

> How many applications out there are we going to break? I'd hope none and if there are some, they are trolls.
I'm okay with this stance as well. Hopefully no one is calling their schema elements `crdb_internal_regions`, and if they are they'll have to rename that object before they can add a region to their database. Considering the likelihood of this, it isn't unreasonable. We can even show a nice error message to them! 

> Will we delete it if a database removes all regions?
That was the tentative plan @otan and I were considering, though we can reconsider if you see any pitfalls here.

**Comment by arulajmani** [comment]
Just saw the comments here, yeah, that issue is closed -- I'll send out a cleanup PR shortly.
