### ISSUE TITLE
server: log pollution about the type of the 'version' cluster setting

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#56895]
I am seeing my server logs in unit tests spammed with the following warning:

```
W201119 10:31:03.986995 91 server/settingsworker.go:107  [n1] setting "version" to "\x12\b\b\x14\x10\x02\x18\x00 \x02" failed: setting 'version' defined as type m, not v
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/settings.updater.Set
  |     /go/src/github.com/cockroachdb/cockroach/pkg/settings/updater.go:87
  | github.com/cockroachdb/cockroach/pkg/server.processSystemConfigKVs.func1
  |     /go/src/github.com/cockroachdb/cockroach/pkg/server/settingsworker.go:106
  | github.com/cockroachdb/cockroach/pkg/server.processSystemConfigKVs
  |     /go/src/github.com/cockroachdb/cockroach/pkg/server/settingsworker.go:112
  | github.com/cockroachdb/cockroach/pkg/server.(*Server).refreshSettings.func1
  |     /go/src/github.com/cockroachdb/cockroach/pkg/server/settingsworker.go:141
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1
  |     /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:221
  | runtime.goexit
  |     /usr/local/go/src/runtime/asm_amd64.s:1374
Wraps: (2) setting 'version' defined as type m, not v
Error types: (1) *withstack.withStack (2) *errutil.leafError
```

Is that intended?

**Comment by tbg** [comment]
have a repro branch? This should not happen, we recently reverted the change from `m` to `v`  on master. It could happen if you're running on an old store dir from earlier master but sounds like you're running tests.

**Comment by knz** [comment]
This was on CI for #56865 prior to the latest rebase.
Example here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_Test/2458630

**Comment by tbg** [comment]
That run was based off of 8481e03e2b41d3543947ccf9c6b3e69b43d6e7d2, which has 516b807aac4e0382e1a713ded2279e0a06d6c094.

@irfansharif this sounds like the setting does return `m`, but somehow the updater is told to expect `v`.

**Comment by tbg** [comment]
uh oh, it surely would be this:

https://github.com/cockroachdb/cockroach/blob/600657ca8918979efc5f5df88a6454d074f65aae/pkg/sqlmigrations/migrations.go#L1109
