### ISSUE TITLE
storage: MVCCStats migration story for future changes

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#5690]
@tamird brought up a concern about `MVCCStats` and their migration path. Because `MVCCStats` are continuously accumulated and never recomputed, a migration that adds or removes a field will result in a partially incorrect stats object. We should determine the best way to handle the circumstance where the stats object provided in a snapshot is not fully compatible with the current version. The idea that seems best right now is to drop the provided stats on the floor and recompute. The question then becomes how can we detect when the stats are incompatible with a given replica version.

**Comment by tschottdorf** [comment]
Any migration which changes the on-disk format can recompute the stats
synchronously when the corresponding Store starts.

**Comment by tschottdorf** [comment]
Assuming, of course, we have a version on the existing on-disk state.

**Comment by tamird** [comment]
Another option: always recompute on bootstrap.

**Comment by spencerkimball** [comment]
I would be tempted to version the MVCCStats object and recompute during consistency checks, which must scan over all of the data in each range anyway. This would leave an extant cluster with potentially incorrect stats for the consistency check interval, but that seems more acceptable than a very slow startup process.

This is definitely not 1.0. Removing that milestone and adding the `enhancement` label.

**Comment by bdarnell** [comment]
This is done; the consistency checker is now able to recompute the MVCC stats.
