### ISSUE TITLE
sql: vectorized stats collectors can finish prematurely

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#56928]
I am working on aggregating row counts for EXPLAIN ANALYZE (PLAN) and ran into some flaky plans. I traced it down to some vectorized stat collectors being finished (i.e. `OutputStats()` being called) early.

I managed to figure out a repro using this [patch](https://gist.github.com/RaduBerinde/ae123b97d2afce9da7c8b34255a4bf9d) (repro instructions in there too).

In an instance of the repro, we have this [plan](https://cockroachdb.github.io/distsqlplan/decode.html#eJy8k19vmzAUxd_3Kaz71E6OwIY2E1IlpKnTUm1hSvs28eCEu4BKMbNNtCrKd5-ASRmI8kdseTT27_icc_ER9M8UPHi8_3L_8Ym8J582wVfyfCAPwWpNxJYEa3Igd0QAhUxGuBYvqMH7DgwocKDgQEghV3KHWktVbh2rg6voF3g2hSTLC1N-DinspELwjmASkyJ48CS2KW5QRKisUi9CI5K0kn8--LlKXoR6BQqPuci0Ryy2sDiEJwqyMH9Uz2LbVxILHTdl_PJ8SEEbsUfw2Im-4e6sU2RSRagwaiiFJTl0pCPiZ6HjB5lkqKybprUUf5grn1_fqWQfmyufXQOFoDAe8Rn1OfUd6ruttOckzowkHTbXciFza9mO3Hm127iajR8xHzFivrDaoeeMmF12xLf_b8R8fM_2cM8LixGRRYQRaWJU_7DxCT6dpqzYdvic6Iw1nPE3nV3gX3Av89w7TGxQ5zLTOOo122UMjPZY16JloXb4TclddU29DCquek0RalPvLuvFKqu3SoPjYTYHdvth1obtv2HeD_Ne-EMDttuwM6ewfnigsH54oDB3TmE3czL3wwOZ--GBzLcTbPNpMJsDu_3wctKowtO73wEAAP__KfM-Jw==).

According to various printf sprinkled around the code, I saw that the collector for TableReader/2 is called before we even emit a batch from that processor. The issue is that the collectors for `TableReader/2` and `HashJoiner/6` are in the same  `finishVectorizedStatsCollectors` list and will finish together. In this case, it's possible that `TableReader/3` finished without producing any rows that go to `HashJoiner/6` which caused that processor to finish execution.

**Comment by yuzefovich** [comment]
I think I'm running into this problem with the first commit of #62126, so I'll look into this today.
