### ISSUE TITLE
logs: log redaction broken

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#56936]
At master, `98fc9b3c760b56dcd4324ecb1da6aadb3d794f39`, no matter how I set `--redactable-logs`, the log files contain unredactable messages. If I use `--logtostderr`, stderr gets redactable messages.
I think this broken @ https://github.com/cockroachdb/cockroach/pull/56336; before it seems to work.

Another thing I observed, both on master and before the patch above, is that the stderr logs are redactable no matter the value of `--redactable-logs={true,false}`. Is that expected?

**Comment by knz** [comment]
> no matter how I set --redactable-logs, the log files contain unredactable messages. 

Good catch - fixing in #56897 

> both on master and before the patch above, is that the stderr logs are redactable no matter the value of --redactable-logs={true,false}. Is that expected?

yes -- the idea is to more strongly promote redaction markers in test logs.

That being said, another PR I have in the works will make this configurable for users who don't like it.
