### ISSUE TITLE
is this example code wrong ?

### ISSUE THREAD

**Issue by carr123** [cockroachdb/cockroach#56945]
https://www.cockroachlabs.com/docs/v20.2/delete#batch-delete-on-a-non-indexed-column

while True:
  with conn:
    with conn.cursor() as cur:
        if lastrow:
            filter = lastrow[0]  # here, should it be lastrow[-1] to select the minimal item of this batch ?
        query = psycopg2.sql.SQL("DELETE FROM new_order WHERE no_w_id <= %s ORDER BY no_w_id DESC LIMIT 5000 RETURNING no_w_id")
        cur.execute(query, (filter,))
        print(cur.statusmessage)
        if cur.rowcount == 0:
            break
        lastrow = cur.fetchone()

conn.close()

**Comment by jordanlewis** [comment]
No - the `[0]` is indexing into the row, not the batch. The loop fetches 1 row at a time.
