### ISSUE TITLE
CDC: Support Filters for Changefeeds

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#56949]
A way to syntactically specify a filter on what is emitted in a changefeed, ensuring we can support filtering by partition, and only the partitioned data is emitted in a changefeed. 

UX tbd. Alternatively, we could allow a more broad set of filters.

Changefeed should fail when partitions are changed.

gz#7834

Jira issue: CRDB-2889

**Comment by bobvawter** [comment]
Did get a request from a CEA customer to allow filtering based in part on the SQL user that was responsible for the change.  Might also be nice to have the SQL application name available as a predicate, too.

**Comment by bryanhuntesl** [comment]
@amruss - very interested in this

**Comment by amruss** [comment]
Hi @bryanhuntesl this ended up just under the cutline for 21.2, so we probably won't have something comprehensive here for the next release. That being said we're going to do scoping/validation here over the next few months. What does the use case look like for you?

**Comment by chudel** [comment]
Hi - curious about a status for this?  As a customer with regulated data (PCI, PII), it's super beneficial to have columns filtered right at the start when using CDC to populate a downstream pipeline.

**Comment by HonoreDB** [comment]
This is now available in preview. https://www.cockroachlabs.com/docs/dev/cdc-transformations.html

**Comment by binarytemple** [comment]
Haha no way! Thanks for implementing this!

**Comment by amruss** [comment]
Planned for removing the preview label in 23.1 coming out in a few months!
