### ISSUE TITLE
build: automate building and pushing of new `build/builder*` images

### ISSUE THREAD

**Issue by jlinder** [cockroachdb/cockroach#56987]
The current process for building and pushing a new builder image (`build/builder*`) requires the engineer making the changes to manually push the image to DockerHub. Instead, we want to put that capability into a TeamCity build configuration.

The workflow for this might look like:

- Develop the changes to the `build/builder/Dockerfile` locally
- Once satisfied with the changes, make a PR with the changes
- Go to the new TeamCity build configuration and run it for the PR. It will output the new builder image tag.
- Add the new builder image tag to the PR and link to the TeamCity run where it was pushed.
- Follow the rest of the steps in rolling out the new image.

**Comment by rickystewart** [comment]
This is implemented as `Internal / Release / Build and Push New Builder Image`.

**Comment by jlinder** [comment]
I noticed I forgot a step for updating the documentation. Can you also update the related docs [here](https://github.com/cockroachdb/cockroach/blob/master/build/README.md#upgrading--extending-the-docker-image) to reflect the new workflow?

And I'm curious, what is the workflow you envisioned with this implementation? I imagine the workflow would be something like this:

1. Develop and test the changes locally
2. Push them to a PR
3. Get review of the PR (minus the new version number, which gets added later)
4. Ask someone with access to use the new build configuration to build and push the image using the PR's branch (people with access would currently be any developer; in the future this may be just dev inf folks who can also review the PR before running the build config; the access part don't necessarily need to be added to the docs right now)
5. Update the PR with the new version tag in `build/builder.sh`

**Comment by rickystewart** [comment]
Yes, that's essentially the shape of the workflow that I imagined. I've submitted a pull request to update the docs accordingly (#59861).
