### ISSUE TITLE
jobs: stray `log.ReportOrPanic` in adopt.go

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#56999]
This:

```go
       default:
        logcrash.ReportOrPanic(⋄, ∅, "unexpected job status")
```

Has two shortcomings:

- should probably `return errors.AssertionFailedf(...)` instead
- should include more details (e.g. the actual observed status and possibly some anonymized payload fields) to ease troubleshooting

**Comment by dt** [comment]
@knz is there anything specific to a particular bulk operation you wanted the bulk io team to look at here?
