### ISSUE TITLE
sql: update age to duration, txn to transaction

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#57047]
We[ discussed previously ](https://cockroachlabs.slack.com/archives/C0159JK877C/p1600208662030600)a few small changes to the names on the Sessions page. Specifically, we proposed replacing Session Age with Session Duration (and making that same change for all uses of age). We also need to replace the abbreviated TXN with transactions to be consistent with our other uses throughout the DB Console.

It would be great if we could make these changes and backport them to the next 20.2.x release.

**Comment by awoods187** [comment]
@dhartunian do you mind picking this up?

**Comment by dhartunian** [comment]
@awoods187 this sounds like purely a copy change, correct? If so, we can grab it.

cc @thtruo for prioritization. We can try and add this to the next sprint.

**Comment by thtruo** [comment]
Nice - in the meantime I'm tracking this internally [CRDB-1744](https://cockroachlabs.atlassian.net/browse/CRDB-1744)
