### ISSUE TITLE
backupccl: option to upload exported SSTs from processor

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#57058]
Currently BACKUP sends ExportRequests that instruct the KV range to directly export its data to the destination and return just the names for the files it wrote.

Instead, we could have the range export the data into a file that is included in the response, and let the sender handle uploading it to the ultimate destination. This incurs an extra copy, using more network and memory resources in the cluster so it isn't ideal in all situations, but particularly in multi-tenancy deployments, where KV nodes are shared between tenants, having the tenants' own SQL processors do their uploading is desirable e.g. to limit where we connect to external network resources, or required for e.g. `userfile`.

While ExportRequest already has a flag to simply return an SST, this isn't _quite_ enough as-is, as we likely want to include pagination and ResumeSpans as well to avoid massive replies. 

- [ ] https://github.com/cockroachdb/cockroach/issues/57227 Add ResumeSpan / Pagination to ExportRequest / BackupProcessor
- [ ] https://github.com/cockroachdb/cockroach/issues/57229 Optionally have BackupProcessor set the flag to get SSTs returned and handle uploading them itself.

**Comment by pbardea** [comment]
Closed by https://github.com/cockroachdb/cockroach/pull/57641 and https://github.com/cockroachdb/cockroach/pull/57317
