### ISSUE TITLE
querycache: unhook EvalContext from CachedData memo  

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#57059]
**Describe the problem**

When a query plan which is not fully optimized is cached, it retains a pointer to the `*tree.EvalContext` via the `logicalPropBuilder`. This retained reference can manifest as a relatively severe memory leak when those cached values end up retaining different `SystemConfig`s which can end up being rather large. 

**Environment:**

This issue affects at least v20.1.x and v20.2.x. Ideally a fix would be available for backport.

**Comment by RaduBerinde** [comment]
Thanks for finding this. Yes it is wrong as a principle to hang on to the original EvalCtx. Definitely a bad idea to use the old one when we are reoptimizing - there might be a correctness issue here too, I'll see if I can find one.

**Comment by RaduBerinde** [comment]
Thinking about it more, I don't think there is a correctness issue - that EvalCtx would never be used.
