### ISSUE TITLE
protectedts: better error message if we can't protect

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#57064]
Right now a failure to protect a timestamp that has already been GC'ed produces an error like `failed to verify protection` with an opaque UUID, a proto printed with some span bytes, and a wall-time. However this isn't very clear to an end-user why it failed. Ideally we'd change this error message to be both friendlier, i.e. with more prose explanation and less proto and span bytes. But even more importantly we should include the two timestamps -- what we tried to protect, and what had already been GC'ed -- like the old error did on an attempt to read below GC time, which is what a user would have seen before we added TS protection to historical reads.

**Comment by mwang1026** [comment]
Also should address tests for gcttl and backup

**Comment by adityamaru** [comment]
Closed by #62412.
