### ISSUE TITLE
Support vendor/ directories for vendoring code?

### ISSUE THREAD

**Issue by mqliang** [cockroachdb/cockroach#5706]
Go 1.5 introduced experimental support for vendor directories that are enabled via an environment variable. In Go 1.6, it will be enabled by default, but you can turn it off. In Go 1.7, you will no longer be able to turn it off.

http://tip.golang.org/cmd/go/#hdr-Vendor_Directories

**Comment by tschottdorf** [comment]
Hi @mqliang, thanks for the suggestion.
We're already tracking this under #4182 and had a concrete attempt at migrating which we discarded for the time being (#4620).
