### ISSUE TITLE
Add time-series metrics that track certain ways the DB scales (or, even better, doesn't scale)

### ISSUE THREAD

**Issue by joshimhoff** [cockroachdb/cockroach#57065]
Here is a strawman set of gauges to add:

1. Number of DBs
1. Number of tables
1. Number of indexes
1. Number of columns (max number of columns per table? avg number of columns per table?)

As suggest by the term "strawman", I'm not at all sure those are the right metrics to add. My hypothesis based on observing DB oncallers work is that a cause of some production issues can be a very large number of DBs for example. 

For example, there was this theory when `SHOW DATABASES` become unavailable on a CC cluster (it wasn't actually the problem in the end). A time-series metric allows eliminating that theory much quicker. Considered alone, this is a small detail but making many such (small) changes lead to noticeable improvements in our collective efficiency. Adding time-series metrics improves the chances SRE / support will see something ahead of escalating to DB eng.

Who could help me determine a set of time-series metrics to add given the goal? Maybe @bdarnell has thoughts.

Jira issue: CRDB-2873

**Comment by awoods187** [comment]
This is an interesting idea--thanks for filing
