### ISSUE TITLE
logging: log all events into cockroach.log

### ISSUE THREAD

**Issue by fabiog1901** [cockroachdb/cockroach#57067]
Following on #56156, we require a quick fix for **v20.2.x** specific for redirecting all events that go into table `system.eventslog` to log file `cockroach.log`. 

The goal is to avoid enabling `cockroach-sql-exec.log`.

**Zendesk**: [6850](https://cockroachdb.zendesk.com/agent/tickets/6850)

**Comment by thtruo** [comment]
cc @knz

**Comment by knz** [comment]
FYI event log etnries are already in the logs, for example

```
I201202 15:01:15.395116 2048 sql/event_log.go:190  [n1,client=‹127.0.0.1:38980›,hostssl,user=‹demo›] Event: "create_table", target: 52, info: {TableName:defaultdb.public.t Statement:CREATE TABLE t (x INT8) User:demo}
```

after CREATE TABLE

**Comment by thtruo** [comment]
I spot checked `cockroach.log` on my end as well. I can verify that DDL event log entries do show up in logs (on a 20.2.0 cluster). Here's an example test `CREATE TABLE`: 
```
{
      "severity": 1,
      "time": "1606924513916317000",
      "goroutine": "15838063",
      "file": "sql/event_log.go",
      "line": "146",
      "message": "Event: \"create_table\", target: 59, info: {TableName:bank.public.test1 Statement:CREATE TABLE test1 (id UUID PRIMARY KEY, city STRING, name STRING, address STRING) User:tommy}",
      "tags": "n1,client=XXX,hostssl,user=tommy",
      "counter": "0",
      "redactable": false
}
```

FYI @fabiog1901 @BramGruneir - any other concerns? If not, perhaps we can close out this issue?
