### ISSUE TITLE
TestShowCreateView/3 fails under race

### ISSUE THREAD

**Issue by darinpp** [cockroachdb/cockroach#57090]
**Describe the problem**
running on my GCE worker
`make testrace TESTFLAGS="-v  -timeout 15m -count 1000 -p 8" PKG=./pkg/sql TESTS=TestShowCreateView/3`
fails consistently

(it will repro with `-timeout 3m` as well)

**To Reproduce**

Got latest master and type the line above

**Expected behavior**
I expect it to not fail.

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version: latest master
 - Server OS: Linux

Jira issue: CRDB-2870

**Comment by jordanlewis** [comment]
We should try to bisect this.

**Comment by yuzefovich** [comment]
I don't think we've seen this test fail in the CI in a long while, closing as stale.
