### ISSUE TITLE
Materialized view creation fails with a not-null constraint violation

### ISSUE THREAD

**Issue by dchenk** [cockroachdb/cockroach#57108]
**Describe the problem**

I tried to create a materialized view with just an inner join but got the error `ERROR: generate insert row: null value in column "<redacted column name>" violates not-null constraint`. The query to define the view was pretty simple, and I'm not sure what the root cause is.

**To Reproduce**

A minimal example that encounters the same bug:
_Setup_:
```
create table a (
  id int primary key
);

create table b (
  id int primary key
);

create table c (
  id int primary key,
  a_id int references a (id),
  b_id int references b (id)
);

insert into a values (1), (2), (3);
insert into b values (5), (15);
insert into c values (1, null, 5), (2, null, 5), (3, null, 15);
```
_Try creating a materialized view_:
```
create materialized view b_c as
select c.id, c.a_id, array_agg(b.id) as b_ids
from c
inner join b on b.id = c.b_id
group by c.id;
```
You get: `ERROR: generate insert row: null value in column "a_id" violates not-null constraint`

Note that the query that's being used for the MV works by itself:
```
select c.id, c.a_id, array_agg(b.id) as b_ids
from c
inner join b on b.id = c.b_id
group by c.id;
```

And a plain (non-materialized) view can be created:
```
create view b_c as
select c.id, c.a_id, array_agg(b.id) as b_ids
from c
inner join b on b.id = c.b_id
group by c.id;
```

**Expected behavior**
The MV should get created.

**Environment:**
 - CockroachDB version: 20.2.0
 - Server OS: macOS
 - Client app: `cockroach sql`

**Comment by rafiss** [comment]
Hmm, seems like we don't allow any null values in materialized views at all. For example:

```
root@:26257/defaultdb> create table d (
  id int primary key, d int
);
CREATE TABLE

Time: 58ms total (execution 57ms / network 0ms)

root@:26257/defaultdb> insert into d values (1,1),(2,null);
INSERT 2

Time: 10ms total (execution 10ms / network 0ms)

root@:26257/defaultdb> create materialized view d_v as select d.d from d;
ERROR: generate insert row: null value in column "d" violates not-null constraint
SQLSTATE: 23502
```

It seems like nullability info is lost when making the column descriptor for the materialized view: https://github.com/cockroachdb/cockroach/blob/21beeeb045d0430c5d3c16323d10bf4e8f46e902/pkg/sql/catalog/tabledesc/table.go#L73-L75
