### ISSUE TITLE
"Orderby" does not work in subquery

### ISSUE THREAD

**Issue by chaiyi123** [cockroachdb/cockroach#57163]
execute:
create table t(a int, b int);
insert into t values(1,1),(3,3),(2,2);
when execute 'select * from (select * from t order by a,b) limit 2'
got:
  a | b
----+----
  1 | 1
  3 | 3
(2 rows)
when execute 'select * from (select * from t order by a,b limit 2) '
got:
  a | b
----+----
  1 | 1
  2 | 2
(2 rows)
Two queries got different results
It may be because the sort operation was ignored during buildselect

**Comment by knz** [comment]
@chaiyi123 thanks for your question.

The behavior you observe is intended. Only ORDER BY clauses at the top level of a query, or those under a LIMIT/OFFSET clause, have an impact on the results. This is documented here:

https://www.cockroachlabs.com/docs/stable/query-order.html#order-preservation

Please reach out on the community slack if you have more questions about how to learn CockroachDB SQL.

Cheers
