### ISSUE TITLE
security,server:  SPIFFE/SPIRE integration for TLS authentication (both node-node and client-node)

### ISSUE THREAD

**Issue by aybabtme** [cockroachdb/cockroach#57204]
**Is your feature request related to a problem? Please describe.**
A good story for Cockroach DB to integrate with SPIFFE/SPIRE.

**Describe the solution you'd like**
The ideal outcome would be for Cockroach DB to be SPIFFE aware.

**Describe alternatives you've considered**
Spire/SPIFFE has ways to ["help" processes onboard with SPIFFE-made TLS certs](https://github.com/spiffe/spiffe-helper).

**Additional context**

I've been using SPIFFE/SPIRE both at work and personally on side-projects. In these side projects, I'm also trialing Cockroach DB. I'm currently dealing with two TLS infrastructures: that used by CockroachDB and the one used by all my components/services, managed by Spire. Spire/SPIFFE has ways to ["help" processes onboard with SPIFFE-made TLS certs](https://github.com/spiffe/spiffe-helper) but I was wondering if there's a recommended way to make the DB integrate more ~natively with Spire. In particular, if there'd be some way to leverage spiffe IDs to create DB users, so services can automatically be given valid TLS client certs that attach to a user in the DB.

Jira issue: CRDB-2854

**Comment by rafiss** [comment]
cc @aaron-crl in case you want to investigate

**Comment by aybabtme** [comment]
BTW a similar story with Hashicorp Vault would be even more valuable :)

**Comment by pawalt** [comment]
Hey folks, here's an example of how to do a SPIRE/Cockroach integration:
https://github.com/pawalt/spire-cockroach

The primary blocker in using SPIFFE with Cockroach is the lack of URI SAN support in Cockroach at the moment. Right now, all certificate validation uses the CN/DNS SANs for user mapping. In the demo I linked, I'm getting around that by using the `-dns` flag when registering entries, but there are some security concerns when using this method with multiple clusters. See bottom of README for more details.

A more SPIFFE-friendly approach would be to keep a map of SPIFFE ID -> DB user, but that's a non-trivial addition to the auth system.

**Comment by knz** [comment]
The mapping idea is good and we are interested in it: #47196

**Comment by knz** [comment]
cc @jtsiros for triage
