### ISSUE TITLE
kv: typo in TestApplyPaginatedCommittedEntries

### ISSUE THREAD

**Issue by benlatern** [cockroachdb/cockroach#57213]
**Describe the problem**
found a bug in pkg/kv/kvserver/replica_test  
line 9368
Please describe the issue you observed, and any steps we can take to reproduce it:
`ch, _, _, pErr = repl.evalAndPropose(ctx, &ba, allSpansGuard(), &exLease)`

To Fix:
replace 'ba' with 'ba2'
The Final code:
'ch, _, _, pErr = repl.evalAndPropose(ctx, &ba2, allSpansGuard(), &exLease)'

**Comment by nvanbenschoten** [comment]
Nice find! It does look like this is a mistake. The test passes either way, but mostly just by pure chance. `ba` and `ba2` are both `PutRequests` to the same key and `RaftMaxCommittedSizePerReady` was already configured so low for this test that the rest of https://github.com/cockroachdb/cockroach/commit/38b4827f969709402b52c833cfee571d8d155daf was still necessary for the test to pass.

Would you like to send a PR to make the fix?
