### ISSUE TITLE
jobs: unskip jobs/mixed-version roachtest

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#57230]
This test was frequently failing since it was attempting to run an IMPORT in a mixed version cluster, which is known to not be supported. It was failing often enough that it was no longer giving us good signal.

The test should be updated to use a job that supports being run in a mixed-version cluster.

Epic CRDB-7776

**Comment by ajwerner** [comment]
for better or for worse, this would have caught https://github.com/cockroachdb/cockroach/issues/62415
