### ISSUE TITLE
security: EXPORT as capability/option role

### ISSUE THREAD

**Issue by fabiog1901** [cockroachdb/cockroach#57259]
This request is to enable `EXPORT` as capability/option role, so that also non-admin user are allowed to perform exports.

**Zendesk**: [6898](https://cockroachdb.zendesk.com/agent/tickets/6898)

**Comment by dt** [comment]
do we even need a specific role or is just SELECT on the table enough?

**Comment by fabiog1901** [comment]
The customer has not provided the specifics, they are happy with how IMPORT is implemented, which does not have any special role. So I'd say SELECT/USAGE should be enough, or ownership of the db objects, or what is currently checked to allow a non-admin to perform a BACKUP.

**Comment by dt** [comment]
I think SELECT to run the query being exported, plus rights to use external storage, should be enough. If/when there's a job for export, we might want job control too.
