### ISSUE TITLE
Avoid throwing errors that are irrelevant to the target table in IMPORT TABLE

### ISSUE THREAD

**Issue by mokaixu** [cockroachdb/cockroach#57257]
**Is your feature request related to a problem? Please describe.**

Consider the following dump file:

```
CREATE TABLE public.t (
    a integer
);

COPY public.t (a) FROM stdin;
1
2
3
\.

CREATE VIEW public.v AS
 SELECT t.a
   FROM public.t
  WHERE (t.a > 1);
```

If we were to run `IMPORT TABLE t FROM PGDUMP "something://something"` the import would fail because a CREATE VIEW statement is not supported for pgdump imports. However, the CREATE VIEW statement is independent of the creation/population of table t (the table we are importing).

Value proposition: targeted imports should not fail if there is no reason for them to fail

**Describe the solution you'd like**
We should avoid throwing errors (such as the existence of unknown postgres statements) irrelevant to the target table we want to import.

**Describe alternatives you've considered**
Maybe we can do some sort of filtering or if check?

**Comment by mwang1026** [comment]
Done with the work we did in 21.1 re: `ignore`
