### ISSUE TITLE
ui: "clock offset" and "gc pause time" graphs are confusing on nodes page

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#5728]
The "clock offset" and "gc pause times" appear to be summing the values from the individual nodes. That isn't very useful. Can they display median and max across the nodes?

**Comment by maxlang** [comment]
I'll make this average and max across nodes for now.

**Comment by maxlang** [comment]
After speaking with @cuongdo apparently the clock offset graph is broken currently.

**Comment by maxlang** [comment]
Median is blocked on #6202, but we could do Max and Avg.
