### ISSUE TITLE
sql: pg compatibility with "char" type

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/cockroach#57301]
A user ran into a postgres compatibility issue when inspecting the type of a `char`

When they ran SELECT pg_typeof(typtype) FROM pg_type they get  "char" on Postgres and `bpchar` on CockroachDB. This caused some compatibility issues with the postgres library they are using. 

They are on v20.2.1

cc @rafiss

**Comment by ArsileLuci** [comment]
As @mattcrdb said:
I'm using CockroachDB (v20.2.1) with `tokio-postgres` for Rust.

When I've been playing around with enums, I encountered an error:
```
cannot convert between the Rust type `i8` and the Postgres type `bpchar`
```

this sort of error produced by `accepts(...)` method, which checks is it ok to convert between Rust and Postgres type. In `tokio-postgres` docs there is only one allowed conversion for `i8`, to `"char"` from Postgres.

But the query contained only one column, with my ENUM. After some investigation I've found out that if `tokio-postgres` meets user-defined type it tries to get metadata of this type with another query to `pg_type`
```rust
const TYPEINFO_QUERY: &str = "\
SELECT t.typname, t.typtype, t.typelem, r.rngsubtype, t.typbasetype, n.nspname, t.typrelid
FROM pg_catalog.pg_type t
LEFT OUTER JOIN pg_catalog.pg_range r ON r.rngtypid = t.oid
INNER JOIN pg_catalog.pg_namespace n ON t.typnamespace = n.oid
WHERE t.oid = $1
";
```

Error fires [here in `tokio-postgres/prepare.rs` on line 149](https://github.com/sfackler/rust-postgres/blob/master/tokio-postgres/src/prepare.rs#L129-L181) when trying to read `t.typtype` column. 
In Postgres this column has `"char"` type. But in CockroachDB it has `bpchar`.
