### ISSUE TITLE
kv: return information about number of keys/bytes processed

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#57322]
We have had various situations in which a scan did not return a lot of rows but was very slow, and the reason was because there were a lot of "invisible" keys with older MVCC values. Currently, there is no way for the SQL layer to obtain information about this (and show it with EXPLAIN ANALYZE).

I propose that KV returns (in `ScanResponse`) information about the number of underlying keys (and total bytes) that had to be processed to satisfy a `ScanRequest`. If collecting this information comes with performance overhead, we can add a flag in `ScanRequest` to only request it when necessary. This may apply to `Get` as well.

CC @asubiotto 

Jira issue: CRDB-2835

**Comment by asubiotto** [comment]
+1 cc @tbg I think there was some talk that this might be added this release

**Comment by tbg** [comment]
We didn't commit to it, but this is something that would be reasonably easy with always-on tracing in place and that is how I thought we would implement it. All we need to do is to make a proto, populate the proto (when there's a threshold of tombstones skipped, or some other condition is met that avoids this happening in the hot path), and add it to the trace. The SQL layer can fish it out.

Btw, we had this in the RocksDB days using their perf counters. It was dirt slow for some reason, and probably that reason has gone away now.

**Comment by jordanlewis** [comment]
From @tbg:

We can do this now.

1. set verbose tracing on for the statement (I guess that is implicit if you EXPLAIN it)
2. write pebble code that triggers a callback when seeing lots of tombstones
3. set the callback to add a payload to the span (sp.LogRecord)
4. make sure these show in the analyze output, very similar to how SQL ingests ContentionEvent

**Comment by mwang1026** [comment]
hey @jordanlewis doing some Friday triage and noticed you have an active PR for this so moved it over to SQL Queries. Let us know if you need more input from us and we can move it back / collab

**Comment by jordanlewis** [comment]
Hey @mwang1026 I'm moving it back to KV - I do have a PR open about it but it's the observability side for steps/seeks, which Sumeer provided on behalf of storage. We still would need information from KV about the number of keys/bytes processed to display that information.
