### ISSUE TITLE
OPT: different execution plans selected for queries consist of aggregate and join

### ISSUE THREAD

**Issue by xinyuliu12** [cockroachdb/cockroach#57330]
Hello everyone!

First off, I am sorry for gestures vaguely all of this. Second, I think we may have found a performance bug related to a suboptimal plan selection.

Here is a pair of TPC-H queries that exhibit this behavior.

```
SELECT "region"."r_regionkey", 
       "supplier"."s_address" 
FROM   "region" 
       LEFT JOIN "supplier" 
              ON true 
GROUP  BY "region"."r_regionkey", 
          "supplier"."s_address" 
LIMIT  30; 

SELECT * 
FROM   (SELECT "r_regionkey" 
        FROM   "region") AS "t2" 
       LEFT JOIN (SELECT "s_address" 
                  FROM   "supplier" 
                  GROUP  BY "s_address") AS "t3" 
              ON true 
LIMIT  30; 
```

**Actual Behavior**
The first query takes 121 milliseconds on the latest release v20.2.0-alpha.1, while the second query only takes 30 milliseconds.
The first query's `EXPLAIN ANALYZE (DEBUG)` result is 
[stmt-bundle-first-query.zip](https://github.com/cockroachdb/cockroach/files/5625689/stmt-bundle-first-query.zip)

The second query's `EXPLAIN ANALYZE (DEBUG)` result is 
[stmt-bundle-second-query.zip](https://github.com/cockroachdb/cockroach/files/5625690/stmt-bundle-second-query.zip)

**Expected Behavior**
I would have expected the database system run these two queries with similar execution time, given that they compute the same result tables. 
Here are the steps for reproducing our observations:

**Test environment**

* Ubuntu 20.04 machine "Linux panda 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux"
* Cockroachdb v20.2.0-alpha.1
* Database: TPC-H benchmark (with scale factor 5)

**Reproduce Bug**

1. Install cockroachdb v20.2.0-alpha.1     

```
    $ mkdir -p $(go env GOPATH)/src/github.com/cockroachdb
    $ cd $(go env GOPATH)/src/github.com/cockroachdb
    $ git clone https://github.com/cockroachdb/cockroach
    $ cd cockroach
    $ git checkout eaa939c
    $ make build
    $ sudo make install
```

* start a cockroachdb node in your preferred working directory
```
    $ cockroach start --insecure --store=node1 --listen-addr=localhost:26257 --http-addr=localhost:8080 --join=localhost:26257,localhost:26258,localhost:26259 --background
    $ cockroach init --insecure --host=localhost:26257
```

2. Set up TPC-H test benchmark (if you already have a TPC-H benchmark set up, you can skip step2; starting from step2, all commands should run in the directory ./tpch5 after downloading and extracting it)

* Download TPC-H (scale factor of 5) and extract it
    Download the dataset from the link: https://drive.google.com/file/d/1MLVFPKdRQhlRgmeRIumyIj8NBMRSQ3um/view?usp=sharing
```
    $ tar xzvf tpch5_setup.tar.gz
    $ cd tpch5
    $ chmod +x setup.sh
```

* Create DB and TPC-H schema
`   $ cockroach sql --insecure --host=localhost:26257`    
    In CockroachDB's built-in SQL client to create database:
```
    $ create database tpch5;
    $ exit
```
* Create TPC-H Schema
   `    $ cockroach sql --insecure --host=localhost:26257 -d tpch5 < dss.ddl
`
* Set up benchmark
```  
    $ ./setup.sh
    $ cockroach sql --insecure --host=localhost:26257 -d tpch5 < dss.ri

```
3. Test SQL query that exhibits performance issue
* Execute the queries after logging to the testing benchmark using the following command
`    $ cockroach sql --insecure --host=localhost:26257 -d tpch5
`

Jira issue: CRDB-2834

**Comment by rafiss** [comment]
cc @RaduBerinde for triage

**Comment by RaduBerinde** [comment]
This is an example of a larger area of pushing aggregations through joins, which we don't do currently. This particular case wouldn't be hard to implement though.
