### ISSUE TITLE
kvserver: prevent startup after fatal errors in raft pipeline

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#57369]
**Is your feature request related to a problem? Please describe.**
When a CockroachDB node fatals as a result of a fatal error involving durable state (such as a corrupted LSM, or missing sideloaded file), the node often manages to restart. This makes it harder to ultimately debug the corrupted state, since it will be mutated and possibly clues deleted.

**Describe the solution you'd like**
On errors that are likely irrecoverable corruptions of durable state, prevent node startup. We already have a mechanism for this, see

https://github.com/cockroachdb/cockroach/blob/028ca9e2854aa64c9bddc1572083cf7c86124d4c/pkg/kv/kvserver/replica_corruption.go#L48-L78

With a bit of refactoring, that method could become the general workhorse for exiting the process and preventing it from restarting. Its current parameter, `ReplicaCorruptionError`, doesn't support proper redaction and besides, it is never persisted (as far as I can tell), so we can use a generic `error` here which can benefit from the existing redactability features.

**Describe alternatives you've considered**
None

**Additional context**
This came up in https://github.com/cockroachdb/cockroach/pull/56532.

Jira issue: CRDB-3555

**Comment by neeral** [comment]
I'd like to work on this and am trying to understand it better. My understanding is that this issue requests to generalise the type of the error parameter in the `setCorruptRaftMuLocked` method. I probably have an incomplete/incorrect understanding though so I've created a draft PR to help share my thoughts and solicit feedback: https://github.com/cockroachdb/cockroach/pull/57861

**Comment by tbg** [comment]
Hi Neeral, I think the first step here is to make `setCorruptRaftMuLocked` take an `error`.
