### ISSUE TITLE
Need some more functions support for array column

### ISSUE THREAD

**Issue by rishabhguptaimaginea** [cockroachdb/cockroach#57371]
**Is your feature request related to a problem? Please describe.**
We are working with some array columns and as a part of our operations on these columns we want a few functions to be available.

**Describe the solution you'd like**
1. Need a function which can combine two array column by selecting only the distinct values.
Ex: array[1,2,3,4] + array[2,3,6,7]  => array[1,2,3,4,6,7] is the expected output instead of array[1,2,3,4,1,2,3,4,6,7]

2. As of now there is array_remove function which removes only one element at a time. But we want some function that can remove multiple elements from array column in a single query.
Ex: array_remove(array[1,2,3,4,5], array[1,2,3])  =>  array[4,5] 

**Describe alternatives you've considered**
Alternate approach for both of the mentioned functions will require multiple queries on db for a single operation. As per our requirement, we want to minimise the number of db hits to increase our throughput hence hitting the db multiple times for a single operation will be a costly operation for us.

**Additional context**

**Comment by rafiss** [comment]
Hi @rishabhguptaimaginea !

For these types of array operations, you might be able to achieve this using `array_agg` and `unnest`. For example:

combine two array column by including only the distinct values:
```
> select array_agg(distinct a) from unnest('{1,2,3}'::int[] || '{2,3,4}'::int[]) as t(a);
  array_agg
-------------
  {1,2,3,4}
```

remove multiple elements from array:
```
> select array_agg(a) from unnest('{1,2,3,4,5}'::int[]) as t(a) where a != all('{1,2,3}'::int[]);
  array_agg
-------------
  {4,5}
```

**Comment by rafiss** [comment]
Closing for now. Let us know if this doesn't satisfy your use case!

**Comment by rafiss** [comment]
Closing for now. Let us know if this doesn't satisfy your use case!
