### ISSUE TITLE
sql: Support pgwire flush clientMessageType

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#5739]
The [node.js Postgres driver](https://github.com/brianc/node-postgres) expects support for the [flush](https://github.com/brianc/node-postgres/blob/eabbebaea8dc9140547b1c662b7f6999b559e276/lib/connection.js#L286) client message. Adding support for this would enable placeholder support for the driver when talking to CockroachDB.

**Comment by tamird** [comment]
I think we can make this a no-op.

**Comment by nvanbenschoten** [comment]
Yeah, it doesn't look flush translates to any action on our end.
