### ISSUE TITLE
kvserver: Raft propagation of closed timestamps

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#57396]
[The closed timestamps v2 RFC](#56675) wants closed timestamp information to be carried to follower on Raft entries, under the `RangeAppliedStateKey`.

A prototype from @nvanbenschoten in https://github.com/nvanbenschoten/cockroach/commit/abd907f293b62afb9a210c98e7e2e6a7b6047aa3

Lease requests are a special case in that the lease start time acts as a closed ts.

**Comment by nvanbenschoten** [comment]
Fixed by #59566.
