### ISSUE TITLE
streaming: ingestion jobs should be able to transition between stream "generations"

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#57406]
The streaming ingestion job should be able to transition to reading from a new generation when a new one advertises itself.

A stream may be composed of several generations. A generation is defined by a start-time which indicates the time at which changes started being emitted  to that particular generation. A stream might periodically produce a new generation (when a new generation is created, it will eventually stop writing to the old one).

Upon notification of a new generation, the ingestion job should plan a new flow for the new generation and pickup ingesting the stream.

**Comment by miretskiy** [comment]
@dt 
Is this still applicable given updated design https://docs.google.com/document/d/1i7x6ce0SGMbJ3KEszeRVjRS0LaPhxulcUbi029nVy7c/edit#

**Comment by amruss** [comment]
Closing - feel free to reopen if this issue is still applicable
