### ISSUE TITLE
kvserver: simplify closed ts management for splits

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#57405]
Currently, we forward closed timestamps coming from the `Provider` to `maxClosed.Forward(r.mu.initialMaxClosed)`. Once we get log-driver closed timestamps, we can get rid of tracking this `initialMaxClosed`, and instead we should have the `SplitTrigger` copy the LHS's closed ts to the RHS's `RangeStateApplyKey`.

**Comment by nvanbenschoten** [comment]
> Once we get log-driver closed timestamps, we can get rid of tracking this initialMaxClosed, and instead we should have the SplitTrigger copy the LHS's closed ts to the RHS's RangeStateApplyKey.

After a conversation with @miretskiy about physical backups and recovery from a global closed timestamp (lower-bound across all ranges) yesterday, I'm starting to reconsider this.

@andreimatei you had originally suggested that we push the LHS's closed ts to the RHS below raft (in addition to what's listed here). The benefit of that, which I hadn't seen before, is that it means that the closed timestamp on the RHS will never regress after the split. If we only grab the closed timestamp above Raft, it's possible that the LHS's closed timestamp increases between the split trigger's evaluation and application, and so the RHS's closed timestamp would actually regress. If we allow these kinds of regressions, then the lower bound closed timestamp across the entire cluster can regress. That seems unfortunate, as a number of recovery operations would like to be able to rely on a monotonic cluster-wide closed timestamp.

**Comment by andreimatei** [comment]
#57405 initializes the RHS with the split command's closed timestamp (i.e. below Raft).
Leaving this issue open to track the removal of `initialMaxClosed` once the old closed ts mechanism is deleted.

**Comment by nvanbenschoten** [comment]
Fixed by #59566.
