### ISSUE TITLE
kvserver: simplify the management of merges with log-drives closed timestamps

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#57408]
Currently the merge code does something real' funky for preventing closed timestamps from advancing on a subsumed range (i.e. a RHS in the process of being merged). We feed the tracker a bogus command at a future LAI, which is expected to never come in case the merge succeeds.
With log-drives closed timestamps, this will no longer be necessary. The only thing we need to take care of is to exclude a subsumed range from the side transport for inactive ranges.

**Comment by nvanbenschoten** [comment]
Resolved by https://github.com/cockroachdb/cockroach/pull/61221 and https://github.com/cockroachdb/cockroach/pull/61137.
