### ISSUE TITLE
streaming: track ingested timestamp in ingestion job

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#57400]
The cluster stream ingestion job (https://github.com/cockroachdb/cockroach/issues/57399) needs to be able to track the ingested timestamp across all of it's partition ingestion processors.

Each partition will need to report back to the job the latest timestamp at which:
a) it has received a resolved timestamp event for
b) it has flushed

The job will then also need to keep track of the earliest of these timestamps across all of its stream ingestion processors.

**Comment by adityamaru** [comment]
Going to mark this as closed with the frontier checked in.
