### ISSUE TITLE
streaming: add support for consuming stream outbox service in stream client

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#57426]
The stream client used in cluster-to-cluster streaming, should be able to consume a "partition" of the stream that is produced by another cluster and is exposed by the cluster's stream outbox service (https://github.com/cockroachdb/cockroach/issues/57425).

Epic CRDB-7077

**Comment by amruss** [comment]
Closing due to new design: https://docs.google.com/document/d/1i7x6ce0SGMbJ3KEszeRVjRS0LaPhxulcUbi029nVy7c/edit#
