### ISSUE TITLE
streaming: add gRPC stream outbox service and outbox DistSQL processors to producer

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#57425]
The producer in a cluster-to-cluster streaming setup needs to be able to buffer its stream in some outbox to buffer where the standby cluster can consume the events from. 

This issue tracks the addition of these outbox processors that will facilitate an outbox streaming service which can be consumed by the stream client on another cluster.

Epic CRDB-7077

**Comment by miretskiy** [comment]
Going to close this issue.  It does not appear we will be implementing any special grpcs for this.
