### ISSUE TITLE
streaming: create a stream of encoded KV output for a span

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#57422]
As a first step towards a producer of a stream for cluster-to-cluster streaming, a variant for core changefeeds needs to be created. The primary difference between core changreeds and this stream is that for cluster streaming, we want the changed rows to be emitted as encoded key values (`roachpb.KeyValue`).

**Comment by pbardea** [comment]
Concretely I think this looks like:
1. Partitioning the span that needs to be watched with `PartitionSpans` (optional to start, we can make it all 1 partition).
2. Creating a KVFeed for each of those partitions.
3. Emitting the KVFeed events (`roachpb.KeyValue` and periodic checkpoint events with an `hlc.Timestamp`) to the SQL client as an initial version (a la core changefeeds)

The first implementation of the stream client can open up a SQL connection and read the events over it.

**Comment by amruss** [comment]
Closing this due to https://github.com/cockroachdb/cockroach/pull/60483
