### ISSUE TITLE
server: create "recovery tenant"

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#57432]
The idea for a boot-tenant was originally thought of in the context of cluster-to-cluster streaming. In order to ingest an entire cluster (ie non-tenant keyspace), we need some portion of the key-space that we can avoid overwriting and can act as a "recovery tenant" to facilitate running the stream ingestion job.

To enable whole-cluster to cluster streaming, we first need to support booting a cluster with a non-empty tenant in all of the nodes' SQL servers and KV nodes. This "recovery tenant" will enable us to populate the system tenant's keyspan using usual cluster to cluster replication methods, when the cluster is started in a special "offline mode".

**Comment by livlobo** [comment]
Closed due to focus on migrating everything to tenant architecture.
