### ISSUE TITLE
streaming: support whole-cluster to cluster streaming

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#57433]
Once a recovery tenant becomes available (https://github.com/cockroachdb/cockroach/issues/57432), we should be able to support streaming the system tenant from one cluster to another. The stream can be ingested with the recovery tenant, and the cluster would have to be booted in such an "offline mode".

There is 2 phases to supporting this:
- [ ] Start streaming the entire keyspan in the primary cluster
- [ ] On the secondary cluster, run in offline mode and ingest into the system keyspace

Jira issue: CRDB-3536

**Comment by yonj1e** [comment]
Is this scheme available? Is there a tutorial on how to use it?
