### ISSUE TITLE
streaming: make cluster-to-cluster streaming observable

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#57430]
This is a parent issue that tracks discussion and progress on implementing metrics and observability tooling around cluster streaming.

- [x] [@pbardea] Update job progress payload to contain a map of per-progress partition information (resolved timestamp, most recent error, etc) (https://github.com/cockroachdb/cockroach/pull/68338)
- [ ] Expose builtin that exposes per-partition information via SQL
- [x] Add Prometheus metrics (https://github.com/cockroachdb/cockroach/pull/68982)

Jira issue: CRDB-3538

Epic CRDB-6403

**Comment by adityamaru** [comment]
Some rough notes about `ingestion` observability:

- Track how far ahead a partition is with respect to the frontier. This will give us an estimate of how much data is buffered and needs to be rolled back during cut-over.

- Strawman idea of having a running checksum on the data that has been ingested into the destination cluster, and matching it against the data produced by the source cluster, to guarantee a consistent state.

Things to consider while computing and comparing the checksum:
     - Checksum needs to be calculated on the data which has been ingested rather than the data being ingested, since C2C streaming only offers atleast-once semantics and so we might see duplicate KVs during ingestion.
     - The checksum needs to be calculated as of a particular resolved timestamp so that we can say something along the lines of "at timestamp x, source and destination cluster are identical".
     - The checksum produced by the source cluster needs to represent the state of the **entire** cluster at a global resolved ts, as opposed to on a per partition basis. Since the destination cluster has a processor per partition, we might need to introduce a "default" processor that emits an event stating that this is the checksum of the entire source cluster at ts x. The ingestion job would then use this to compare its own checksum at ts x against.
