### ISSUE TITLE
schema: create a "golden descriptor" upgrade test

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#57435]
The issue we saw in #57032 would have been averted had we had a test that upgraded a descriptor from version 19.1 with foreign keys all the way up to 20.2.

We've been discussing a test framework that can provide such testing.

The test framework should allow the creation of a schema corpus that is pinned to a version.

For each corpus, for each version, the test should upgrade the corpus through each of the versions to the present.

@ajwerner added something similar in #57066. Maybe this is all we need? What else would we need besides that set of tests to feel like we can catch more problems of this nature?

Jira issue: CRDB-3535

**Comment by postamar** [comment]
Today this fits neatly inside the broader problem of properly testing descriptor upgrades (via `RunPostDeserializationChanges` and `RunRestoreChanges`) when RESTOREing old backups. I'm concerned that our corpus of backups just isn't very large and is constrained by what can be checked in the cockroachdb git repo. 

This testing story is a story which we're stakeholders in but which we do not own, so I'm closing this issue.
