### ISSUE TITLE
Control Auto Stats Creation

### ISSUE THREAD

**Issue by pxlogan** [cockroachdb/cockroach#57453]
**Is your feature request related to a problem? Please describe.**
Currently, table statistics are automatically generated based on the amount of the table that has been modified. It would be desirable to be able to disable this during certain timeframes or control the frequency of checking for modifications.

**Comment by awoods187** [comment]
Could you describe how the current controls are insufficient? https://www.cockroachlabs.com/docs/v20.2/cost-based-optimizer.html#controlling-automatic-statistics

**Comment by rytaft** [comment]
I think the settings that @awoods187 mentioned above should be sufficient. Please feel free to reopen this if not.
