### ISSUE TITLE
sql: setting zone configs for non-materialized views should be forbidden

### ISSUE THREAD

**Issue by postamar** [cockroachdb/cockroach#57478]
> isn't it a bug that we even allow setting zone configs on (non-materialized) views in the first place? Is there any point to this? 

_Originally posted by @lucy-zhang in https://github.com/cockroachdb/cockroach/issues/57147#issuecomment-736109675_

Description: It's currently possible to run `ALTER TABLE ... CONFIGURE ZONE` statements on views. Considering that zone configs are meant to describe the physical layout of the data in a table, it doesn't make sense to me either that executing such a statement be possible on a non-physical table.

To reproduce:
```
demo@127.0.0.1:26257/movr> CREATE VIEW v AS SELECT 1; ALTER TABLE v CONFIGURE ZONE USING gc.ttlseconds = 100000;
CONFIGURE ZONE 1
```
I would instead expect an error like this:
```
ERROR: "v" is not a table
SQLSTATE: 42809
```

Looking at https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/set_zone_config.go nothing is there to indicate that this behaviour is allowed for a good reason so I'm tentatively filing this as a bug despite having only a superficial understanding of things. If it turns out that it's not a bug then perhaps adding a comment to that effect in that source file might be helpful.

**Comment by naivcit** [comment]
Hi @rafiss can I take this one ?

**Comment by jyz0309** [comment]
hi,@naivcit have you already started working on this? May I take it?

**Comment by naivcit** [comment]
Hey @jyz0309 yeah I am already working on this , sorry, will post a PR soon .
