### ISSUE TITLE
sql: descriptor is being dropped (SQLSTATE XXUUU)

### ISSUE THREAD

**Issue by jayshrivastava** [cockroachdb/cockroach#57487]
**Describe the problem**

In the following roachtests, sometimes DDLs cause a "descriptor is being dropped" error. Ex:
```
CREATE TYPE schema1.enum113 AS ENUM ('fd', 'sfd');
***FAIL; Expected no errors, but got ERROR: descriptor is being dropped (SQLSTATE XXUUU)
```

**Repros (roachtest)**
https://github.com/cockroachdb/cockroach/issues/56230#issuecomment-721579414
https://github.com/cockroachdb/cockroach/issues/56230#issuecomment-725274377
https://github.com/cockroachdb/cockroach/issues/56230#issuecomment-727164606
https://github.com/cockroachdb/cockroach/issues/56230#issuecomment-727533844
https://github.com/cockroachdb/cockroach/issues/56235#issuecomment-731108894
https://github.com/cockroachdb/cockroach/issues/56235#issuecomment-725370083
https://github.com/cockroachdb/cockroach/issues/56230#issuecomment-748576939
https://github.com/cockroachdb/cockroach/issues/56230#issuecomment-748439425

**Expected Behaviour**
There should not be an error.

**Comment by jordanlewis** [comment]
This will be closed by #59635.
