### ISSUE TITLE
sql: Create crdb_internal.third_party_tooling() built-in function 

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/cockroach#57480]
For third-party tools that allow arbitrary SQL statements to be issued on startup, we could issue a built-in function (Ex. `crdb_internal.third_party.tooling()`) that accepts a JSON argument with at least tool name. Tool version would also be useful. We could then hash the input for telemetry

**Comment by knz** [comment]
Before this gets released as a customer-facing feature, kind request to consider a new namespace besides (in replacement to) `crdb_internal` -- we want to remove `crdb_internal` from our set of user-facing feature.

We actually have a couple built-in functions without a namespace prefix yet. Maybe this could be a good candidate for this? `register_third_party_tooling()` without a prefix?

**Comment by awoods187** [comment]
This is a great idea--excited to see how it progresses.

**Comment by vy-ton** [comment]
cc @solongordon

**Comment by vy-ton** [comment]
@solongordon Will the built-in allow us to distinguish between tool versions? For example, Active Record 5 adapter vs 6 adapter.

**Comment by solongordon** [comment]
The current plan is to have the built-in accept an arbitrary string, which
would allow for including versions.

**Comment by solongordon** [comment]
Resolved by #59768
