### ISSUE TITLE
sql: add time of last updated stats to explain analyze

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#57517]
One big source of potential slow queries is out of date statistics in the CBO. We aim to refresh these sufficiently often to provide good plans without impacting the cluster too much. However, sometimes, this isn't frequent enough. It can be tricky for developers to think to look at the last time statistics were refreshed. If they do, `CREATE STATISTICS` is an easy enough solution. We should consider making the last time statistics were updated more discoverable. One place to put this would be in `explain analyze` as it is a user trigger that this query may be underperforming and it can help clue them on the need to update statistics.

**Comment by awoods187** [comment]
@mgartner points out we can also do this in EXPLAIN too.

**Comment by RaduBerinde** [comment]
Adding this to EXPLAIN is not hard but it makes the EXPLAIN output non-deterministic which messes up our tests. Trying to figure out a way around it.
