### ISSUE TITLE
telemetry: add tenant-id to telemetry sent to registration server

### ISSUE THREAD

**Issue by andy-kimball** [cockroachdb/cockroach#57523]
Today, telemetry updates are not tagged with the `tenant-id`, when the CRDB cluster is a multi-tenant host cluster. This means that telemetry from all tenants are mixed together on the registration server, with no ability to distinguish between tenants.

Fixing this will require the (at least) the following steps:

1. Update the diagnostics reporting code in `pkg/server/updates.go` / `pkg/server/diagnosticspb/diagnostics.go` to tag telemetry updates with the current `tenant-id` (if running as a tenant). See the `addInfoToURL` method.

2. Update the registration server to have new tenant_id field(s) in the appropriate tables.

3. Change the registration server code to grab the `tenant_id` from the HTTP request and store it in the appropriate table.

Work with the Product team to determine which tables need to include this information.

**Comment by tbg** [comment]
Closing for https://github.com/cockroachdb/cockroach/issues/53188. I'm adding more information there.
