### ISSUE TITLE
kv: TestReplicateAfterTruncation is flaky

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#57537]
https://teamcity.cockroachdb.com/viewLog.html?buildId=2494903&buildTypeId=Cockroach_UnitTests

**Comment by irfansharif** [comment]
+cc @adityamaru, who's test infra on-call. Ran into this in https://github.com/cockroachdb/cockroach/pull/57830 as well.

**Comment by adityamaru** [comment]
Oops, looks like our slackbots are lagging - skipping.
