### ISSUE TITLE
sql/catalog: allow creating system tables with dynamic IDs

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#57531]
Today system tables are created with hard-coded IDs. This is problematic because we only reserved up to ID 50 and we're coming up on it. As of writing, we're at 39. This also tends to discourage creating system tables, which has also proven to be a mistake and forced us to shove more data into tables rather than designing subsystems as we might using the full power of the relational model.

**Proposed Solution**

Only a small number of system tables required for bootstrapping the cluster actually need to have a fixed ID. We'll have to assume that we already have all of the ones we need. Other system tables should be interacted with just like any other table.

A bit of a snag here has been that we haven't had great APIs around descriptor retrieval and management. Hopefully upcoming work will allow us to abstract descriptor retreival and management in rather low-dependency interface packages and gain wide adoption throughout the codebase.

Epic: CRDB-10772

**Comment by ajwerner** [comment]
This is starting to get pressing. In fact, I was going to go so far as to suggest in the recent stats tables PR that we consider creating a new database for use there so we can save the reserved IDs. There’s nothing but privileges and expectations on setting them that make a lot of SQL-level system tables special. Some system tables really benefit from having constant IDs for bootstrapping. One benefit of keeping them all in the system database is that the zone configs will apply uniformly. 

As of writing, we're at 41. We also have a couple of IDs which we could recycle if we had to. Nevertheless, we're going to feel sadness if we don't retain at least a handful of these for bootstrap tables.

The special cases around system tables are:

1) Avoiding the namespace table for ID lookups here:

https://github.com/cockroachdb/cockroach/blob/8be5c15b07800e15a13c83209993617ff3f0723b/pkg/sql/catalog/descs/kv_descriptors.go#L157-L158

2) Synthesizing the system database here:

https://github.com/cockroachdb/cockroach/blob/8be5c15b07800e15a13c83209993617ff3f0723b/pkg/sql/catalog/descs/database.go#L67-L77 

3) Avoiding caching of some system descriptors (only when acquired by name 😕 ) here. I'm pretty sure that this only needs to be far fewer descriptors than it currently is. 

https://github.com/cockroachdb/cockroach/blob/8be5c15b07800e15a13c83209993617ff3f0723b/pkg/sql/catalog/descs/object.go#L111-L132

I think that if we added some node level cache on 2 that never evicted then everything would "just work". The avoiding caching in 3 is to prevent bootstrapping problems and I think can be diminished to only include `lease`, `descriptor`, `namespace`, and `rangelog`.

**Comment by RichardJCai** [comment]
> 2. Synthesizing the system database here:
> 
> https://github.com/cockroachdb/cockroach/blob/8be5c15b07800e15a13c83209993617ff3f0723b/pkg/sql/catalog/descs/database.go#L67-L77

Can you clarify point 2? Not sure what synthesizing means in this context or what exactly has to be done here.

**Comment by ajwerner** [comment]
Point 2 isn't about system tables at all, it's about the system database. I was just pointing out places where the system database and its members are weird. We never read the descriptor for the system database; we always use the in-memory structure. I guess point 2 is sort of irrelevant. It does mean that if you ever changed anything about the system database then I don't think it would propagate. 

Related to that. I feel like for the tables we never cache, we also interact with them via the KV API which has hard-coded assumptions about their structure. It seems to me like, given that, instead of avoiding caching on those tables, we should just serve the in-memory copy of those descriptors. The only place where it would matter is if we want to allow changing privileges for SQL access. I don't see that happening for those 4 tables.

**Comment by adityamaru** [comment]
Another thing to fix once system tables are allowed to have dynamic IDs is cluster restore. During a cluster restore we have special case handling for descriptors with ID < 51: https://github.com/cockroachdb/cockroach/blob/401629778b81f4aced80953cf5b4dcd093e290c4/pkg/ccl/backupccl/restore_planning.go#L907.
If backed up system tables no longer have this property we will not handle this correctly.

On a similar note, is there any scope of making system-created descriptors egs: `defaultdb` and `postgres` also have dynamic IDs? Cluster restore has a song-and-dance around these databases that are created on node startup and relies on both the backup and restore containing the same static ID. This has led to fragility if the user accidentally drops these databases on the backing up cluster or restoring cluster. 

From what I gather there is nothing special about these databases so if we decide to treat them as regular user created databases, we would require a wipe before cluster restore. 

Alternatively,  https://cockroachlabs.slack.com/archives/CARM0PTK4/p1592315262060200 has some discussions around adding an `IsSystemCreated` flag to all descriptors that would help us differentiate between system and user created descriptors without relying on static IDs.
