### ISSUE TITLE
sql/catalog: use in-memory immutable descriptors instead of ResolvedSchema for descriptorless schemas?

### ISSUE THREAD

**Issue by lucy-zhang** [cockroachdb/cockroach#57538]
Temporary, virtual, and (for now) `public` schemas don't have on-disk schema descriptors. We currently return them from the descriptor access and name resolution APIs as `catalog.ResolvedSchema`. Perhaps we should just put them behind an immutable schema descriptor interface instead. It may be ideal to not support mutable access.

This would have the advantage of making all the descriptor APIs consistent.

Epic: CRDB-2454

Jira issue: CRDB-3522

**Comment by lucy-zhang** [comment]
I was considering having `ResolvedSchema` implement `catalog.SchemaDescriptor` and un-exporting it as a first step, but got nervous about having to return zero values for all the leasing metadata accessors, etc., to say nothing of the problems with mutable access. Then again, we do already have a precedent for in-memory descriptors that shouldn't be written, leased, etc. (type aliases), so maybe it's fine. This will also all look different, and better, once we only interact with immutable descriptors through an interface.

I think the real problem to be solved is that we need to first resolve _something_ during, e.g., `ALTER SCHEMA`, which will indicate that we can't attempt to mutate the schema and that we should abort. Maybe the thing to do is to always resolve an immutable descriptor as the first step and check that it corresponds to a physical descriptor, and only then perform mutable resolution. It's still a single round-trip since we'd cache the descriptor the first time (in `uncommittedDescriptors`, if there is one.

Having said that, I learned that just we return a user-facing error from `LogicalSchemaAccessor.GetObjectDesc` for mutable resolution of virtual tables, which would probably also work.

**Comment by lucy-zhang** [comment]
I think something I could live with is to have `GetImmutableSchema...` return a synthesized in-memory `*schemadesc.Immutable` (which should be replaced with some alternate implementation, basically an unexported `ResolvedSchema`, as soon as we start using interfaces for immutable descriptors everywhere), and to have `GetMutableSchema...` return some non-user-facing error that we check for. (Or it could be user-facing.) Ideally we'd follow the same pattern for virtual tables.

**Comment by postamar** [comment]
I believe that this has been done.
