### ISSUE TITLE
docs: client drivers to investigate

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#5754]
Comments on Hacker news suggested we list a Scala driver and an alternate Go driver on our [Install Client Drivers](https://www.cockroachlabs.com/docs/install-client-drivers.html) page. We should test them.

Here are the full comments:

"Been watching this DB for a while. Glad to see it enter beta. I recommend including https://github.com/mauricio/postgresql-async on https://www.cockroachlabs.com/docs/install-client-drivers.html (it's my favorite Postgres client, it's very fast)."

"Oh, and the client drivers page should probably also list pgx (https://github.com/jackc/pgx), which is a nice, fast PostgreSQL client that doesn't use the not-as-nice database/sql package."

**Comment by tamird** [comment]
Should this issue be in the docs repo?

**Comment by petermattis** [comment]
@jseldess Is there anything left to do here?

**Comment by jseldess** [comment]
@petermattis, I put this here because I figured we might want to test additional drivers before recommending them, like we've done for psycop2 and others here: https://github.com/cockroachdb/cockroach/tree/e1ef4ec96659ef27ff29d923014f416070a982b6/pkg/acceptance.

If we don't plan to test additional drivers, feel free to close this.

**Comment by jseldess** [comment]
Actually, I'm just noticing that we don't have tests for all recommended drivers listed here: https://www.cockroachlabs.com/docs/install-client-drivers.html. Looks like rust and clojure are missing. Should we have tests for those?

**Comment by mberhault** [comment]
This is probably sufficiently covered by issues in the docs repo. @jseldess?

**Comment by jseldess** [comment]
Yeah, I think if it's just about identifying/documenting drivers, the docs repo is fine. However, if we want to make this about testing drivers, it might make sense to retitle this and keep it open. Your call.

**Comment by mberhault** [comment]
This seemed more about identifying drivers. I'll just close this.
