### ISSUE TITLE
sql: missing backport to 20.2 related to "char" 

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#57559]
In 20.2:

```
root@127.0.0.1:58180/defaultdb> select '"char"'::regtype;
   regtype
-------------
  character
(1 row)
```

On `master` and `psql`:

```
demo@127.0.0.1:26257/defaultdb> select '"char"'::regtype;
  regtype
-----------
  "char"
(1 row)
```

There was a PR that fixed that but it's not backported yet. Found while working on #57558.

**Comment by rafiss** [comment]
Thanks for finding this. I haven't looked at the code yet, but pretty sure it's this: #55607. also, #56298 happened recently and might be related but is a bigger change. @otan i think #55607 can be backported but not sure about #56298 -- what do you think?

**Comment by otan** [comment]
Yeah they need some backports which I wasn't looking to do in 20.2 since they're mildly risky...

**Comment by otan** [comment]
i'm closing this because this is a longstanding bug, which i don't think is urgent enough to backport to 20.2.
