### ISSUE TITLE
docs: add information about the image to the docker hub page

### ISSUE THREAD

**Issue by jayfk** [cockroachdb/cockroach#5756]
The cockroachdb/cockroachdb page on docker hub lacks basic details about the image: https://hub.docker.com/r/cockroachdb/cockroach/

**Comment by mberhault** [comment]
@jseldess: you may want to chime in.
In the full description, we should have shell commands to run a local cluster using docker.

Whether we put it in the actual description or simply put a link to the docs is tbd. However, we don't have an example of how to run multiple nodes using docker. I realize ports are mess, but we should try to sort it out. If not, we should recommend single-node only for local docker clusters.

**Comment by jseldess** [comment]
@mberhault: Suggested, approximate text:

To install CockroachDB using Docker, see [Install CockroachDB](https://www.cockroachlabs.com/docs/install-cockroachdb.html).

To run a single- or multi-node cluster within a single Docker container, see [Start a Cluster](https://www.cockroachlabs.com/docs/start-a-local-cluster.html). Be sure to execute all commands from within the container.

Instructions on running a multi-node cluster across multiple Docker containers coming soon.

**Comment by jseldess** [comment]
@mberhault, was just discussing with @bdarnell that we should see if we can figure out how to tag things so that the default pull command points to the latest beta instead of the latest development build.

**Comment by bdarnell** [comment]
The last comment is in reference to the fact that `docker pull cockroachdb/cockroach` appears in the right-hand side of the hub page and it doesn't look like we can specify a tag to be used there. We want the default to be the latest beta, not the latest master build.

**Comment by mberhault** [comment]
I don't think there's a way, we would have to stop building the master
builds under that name. By the way, that may not be a bad thing.

**Comment by bdarnell** [comment]
Yeah. Now that we're publishing regular beta builds, is anyone using the every-commit docker images? We may be able to just drop that step completely.

**Comment by mberhault** [comment]
One issue is that they are being used for the acceptance tests, although I
think we can build it and not push it.

**Comment by a-robinson** [comment]
Moving the alpha builds elsewhere may not be a bad idea. There currently isn't even a single beta image displayed on our docker hub page because it's been so long since the last beta release.

**Comment by ckeeney** [comment]
Can someone explain how the [installation instructions for docker](https://www.cockroachlabs.com/docs/install-cockroachdb.html#use-docker-linux) are 

`$ sudo docker pull cockroachdb/cockroach:beta-20160728`

but the [docker hub page](https://hub.docker.com/r/cockroachdb/cockroach/tags/) does not have that tag?

I tried pulling the tag and surprisingly, it worked.  I just don't understand how.

**Comment by tamird** [comment]
Seems like the list of tags on docker hub is truncated.

**Comment by ckeeney** [comment]
I'd like to suggest just not tagging `alpha` builds with the `latest`.  Retag the latest `beta` as latest and moving forward, `docker pull cockroachdb/cockroach` will pull the latest `beta` (or `stable` eventually) image.

Technically, the `alpha` builds are "latest", but "latest" tag should refer to the latest stable build.

**Comment by spencerkimball** [comment]
@mberhault could you comment on this? Is this a 1.0 milestone?

**Comment by mberhault** [comment]
Yup. We need a few things here:
* flesh out the docs on docker hub (https://hub.docker.com/r/cockroachdb/cockroach/)
* only apply `latest` tag to what we consider the stable releases (for now, it's `beta`, but will be proper releases later one). Is this possible?
* add `alpha`, `beta` tags

@jseldess: any ideas for the docker hub description? Maybe a one sentence summary and a link to our docs?
For the tags, is that even how they work? or is latest applied to whatever was last uploaded? Maybe @tamird knows?

**Comment by ckeeney** [comment]
Latest is just the default tag when you pull.  It is not automatically applied to the latest uploaded image.

**Comment by jseldess** [comment]
@mberhault, I agree that we should keep this short and link to our docs. I like how rethink and aerospike do it.

For the short description, we could go with:

> CockroachDB is an open source, survivable, strongly consistent, scale-out SQL database.

For the full description, we could have three subsections:

- **Supported tags and respective `Dockerfiles` links** - Could you help with this?
- **What is CockroachDB** - I can get a longer description.
- **Using this image** - Here we could probably link to our install docs?

**Comment by a-robinson** [comment]
> - **Supported tags and respective `Dockerfiles` links** - Could you help with this?

It looks like to get the nice setup that rethink and aerospike have, we'd want to get into Docker's "Official Images" library:
https://github.com/docker-library/official-images
https://github.com/docker-library/repo-info

I'm not sure how much benefit there is to being included there, but it seems likely we'd meet the requirements for addition if we're up for putting in the required effort (https://github.com/docker-library/official-images/blob/master/NEW-IMAGE-CHECKLIST.md).

> - **Using this image** - Here we could probably link to our install docs?

Yeah, I'd link to our various docs pages for using Docker images -- i.e. our single-node Docker instructions, our Swarm instructions, and our Kubernetes instructions.

**Comment by mberhault** [comment]
Updated short/long descriptions to:
```
Short Description
CockroachDB is an open source, survivable, strongly consistent, scale-out SQL database.
```
```
Full Description
To install CockroachDB using Docker, see Install CockroachDB.

To run a single- or multi-node cluster within a single Docker container, see Start a Cluster. Be sure to execute all commands from within the container.

Instructions on running a multi-node cluster across multiple Docker containers coming soon.
```

@jess-edwards, @jseldess: I'm happy to modify that.
For now, dropping 1.0 due date.

**Comment by jseldess** [comment]
Thanks, @mberhault. Just a few changes:

- The **Start a Cluster** link should point to `https://www.cockroachlabs.com/docs/start-a-local-cluster-in-docker.html`.
- We have orchestration docs, so let's change the last line to:
  `To run a multi-node cluster across multiple Docker containers, see our docs on using orchestration tools like [Kubernetes](https://www.cockroachlabs.com/docs/orchestrate-cockroachdb-with-kubernetes.html) and [Docker Swarm](https://www.cockroachlabs.com/docs/orchestrate-cockroachdb-with-docker-swarm.html).`

**Comment by mberhault** [comment]
Done. thank you.

I think this is it for this issue.
@a-robinson, was there anything left tag-related?

**Comment by a-robinson** [comment]
Nope, the tags have been looking good since #14755 went in. We will have to change that logic slightly to only mark official release builds as latest once we have our tooling for tagging official release builds, so it might be worth opening a separate 1.0 issue for that?

**Comment by ckeeney** [comment]
If possible and if nobody needs them, maybe stop pushing alpha builds to Docker Hub?  They still pollute the tag listing and push all beta/latest tags way down.

**Comment by tamird** [comment]
@ckeeney no more alpha builds as of #15410.

**Comment by a-robinson** [comment]
I see nothing left to do here now that alpha builds don't get pushed at all.
