### ISSUE TITLE
kvserver: properly sequence replication changes

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#57563]
**Is your feature request related to a problem? Please describe.**
Manual and automatic replication changes often clash. This is particularly true in testing, but also in production.
A particular danger is learners erroneously getting rolled back. This happened in production (https://github.com/cockroachdb/cockroach/issues/57129) and is also the standard symptom in testing.

Since replication changes are often multi-step operations, we should have an
advisory lock mechanism that can serialize them. I took a quick stab at this
but realized that the entry points are quite different and even given a locking
building block, it's not trivial to start using it due to re-entrancy issues.

For example, the StoreRebalancer calls `AdminRelocateRange`, which then sends multiple
`AdminChangeReplicas` requests which ultimately become calls to `(*Replica).ChangeReplicas`.

This means `AdminChangeReplicas` should take the lock, but we also want `ChangeReplicas` to
take the lock because it is also called directly. So it can only take the lock optionally,
if the caller doesn't already have it.

**Describe the solution you'd like**
Determine which locking mechanism to use and employ it. Most of the work is probably going to be refactoring the various entry points into descriptor changes and make them more organized, perhaps to the point at which re-entrancy is no longer necessary.

**Describe alternatives you've considered**
We don't like our current replica placements mechanism and would prefer replacing them with something more centralized. It is possible that this could solve the above problem "for free". But, we're not doing that work right now and it will be a large undertaking.

We could also mandate that everything goes through the leaseholder and put the locking mechanism on the leaseholder. But this doesn't work with the code structure today, where operations are often sent through the `*kv.DB`. But, it looks like we need to clean this up either way and when we're done, the existing lease might be a cheap mechanism.

**Additional context**

I tested this diff on aa69b42032f89d1bb777986ff7a8d4f753b71d83 with the flaky test:

```
make stress PKG='./pkg/kv/kvserver' TESTS=TestChangeReplicasDescriptorInvariant TESTFLAGS='-show-logs --vmodule=replicate_queue=4'
```

and the flake disappeared. This doesn't prove much but illustrates the approach.

```diff
diff --git a/pkg/keys/constants.go b/pkg/keys/constants.go
index 96c23bc917..3286cd3dc6 100644
--- a/pkg/keys/constants.go
+++ b/pkg/keys/constants.go
@@ -139,6 +139,8 @@ var (
 	// LocalRangeDescriptorSuffix is the suffix for keys storing
 	// range descriptors. The value is a struct of type RangeDescriptor.
 	LocalRangeDescriptorSuffix = roachpb.RKey("rdsc")
+	// LocalRangeDescriptorLockSuffix TODO.
+	LocalRangeDescriptorLockSuffix = roachpb.RKey("rdsl")
 	// LocalTransactionSuffix specifies the key suffix for
 	// transaction records. The additional detail is the transaction id.
 	LocalTransactionSuffix = roachpb.RKey("txn-")
diff --git a/pkg/keys/keys.go b/pkg/keys/keys.go
index bc5cab2699..26e067115b 100644
--- a/pkg/keys/keys.go
+++ b/pkg/keys/keys.go
@@ -390,6 +390,11 @@ func RangeDescriptorKey(key roachpb.RKey) roachpb.Key {
 	return MakeRangeKey(key, LocalRangeDescriptorSuffix, nil)
 }
 
+// RangeDescriptorLockKey TODO.
+func RangeDescriptorLockKey(key roachpb.RKey) roachpb.Key {
+	return MakeRangeKey(key, LocalRangeDescriptorLockSuffix, nil)
+}
+
 // TransactionKey returns a transaction key based on the provided
 // transaction key and ID. The base key is encoded in order to
 // guarantee that all transaction records for a range sort together.
diff --git a/pkg/kv/kvserver/replica_command.go b/pkg/kv/kvserver/replica_command.go
index 1717447bc5..3185de2db3 100644
--- a/pkg/kv/kvserver/replica_command.go
+++ b/pkg/kv/kvserver/replica_command.go
@@ -267,6 +267,28 @@ func splitTxnStickyUpdateAttempt(
 	return txn.Run(ctx, b)
 }
 
+type rangeLock struct {
+	desc *roachpb.RangeDescriptor
+	txn  *kv.Txn
+}
+
+func newRangeLock(desc *roachpb.RangeDescriptor) *rangeLock {
+	return &rangeLock{desc: desc}
+}
+
+func (rl *rangeLock) Lock(ctx context.Context, db *kv.DB) error {
+	key := keys.RangeDescriptorLockKey(rl.desc.StartKey)
+	// TODO(tbg): don't block here on other intents indefinitely. Perhaps use
+	// the wait policy and a retry loop for now?
+	rl.txn = db.NewTxn(ctx, "")
+	return rl.txn.Put(ctx, key, "range desc lock")
+}
+
+func (rl *rangeLock) Unlock(ctx context.Context) {
+	// TODO(tbg): can we leverage savepoints?
+	_ = rl.txn.Rollback(ctx)
+}
+
 // adminSplitWithDescriptor divides the range into into two ranges, using
 // either args.SplitKey (if provided) or an internally computed key that aims
 // to roughly equipartition the range by size. The split is done inside of a
@@ -292,6 +314,11 @@ func (r *Replica) adminSplitWithDescriptor(
 	delayable bool,
 	reason string,
 ) (roachpb.AdminSplitResponse, error) {
+	rl := newRangeLock(desc)
+	if err := rl.Lock(ctx, r.store.DB()); err != nil {
+		return roachpb.AdminSplitResponse{}, err
+	}
+	defer rl.Unlock(ctx)
 	var err error
 	// The split queue doesn't care about the set of replicas, so if we somehow
 	// are being handed one that's in a joint state, finalize that before
@@ -956,6 +983,12 @@ func (r *Replica) changeReplicasImpl(
 	details string,
 	chgs roachpb.ReplicationChanges,
 ) (updatedDesc *roachpb.RangeDescriptor, _ error) {
+	rl := newRangeLock(desc)
+	if err := rl.Lock(ctx, r.store.DB()); err != nil {
+		return nil, err
+	}
+	defer rl.Unlock(ctx)
+
 	var err error
 	// If in a joint config, clean up. The assumption here is that the caller
 	// of ChangeReplicas didn't even realize that they were holding on to a
diff --git a/pkg/kv/kvserver/replicate_queue.go b/pkg/kv/kvserver/replicate_queue.go
index 03e6b054fc..a719c1bbc4 100644
--- a/pkg/kv/kvserver/replicate_queue.go
+++ b/pkg/kv/kvserver/replicate_queue.go
@@ -321,6 +321,12 @@ func (rq *replicateQueue) processOneChange(
 
 	desc, zone := repl.DescAndZone()
 
+	rl := newRangeLock(desc)
+	if err := rl.Lock(ctx, repl.store.DB()); err != nil {
+		return false, err
+	}
+	defer rl.Unlock(ctx)
+
 	// Avoid taking action if the range has too many dead replicas to make
 	// quorum. Note that this is checked again at a lower-level, in execChangeReplicasTxn.
 	// However, retaining the additional check here helps paper over the races between the

```

Jira issue: CRDB-3518

**Comment by ajwerner** [comment]
Relates directly to https://github.com/cockroachdb/cockroach/issues/41392.

**Comment by tbg** [comment]
Thanks! I knew there was an issue somewhere but my github-fu wasn't good
enough.

**Comment by andreimatei** [comment]
For the particular case of voters being removed - do you understand exactly how it happens? What's the logic for removing a learner? Does the replication queue remove all the voters it sees?
Have you considered attaching a creation timestamp to a voter and giving each a grace period during which nobody is allowed to remove it?
