### ISSUE TITLE
sql: migration to verify that interleaved tables have been removed while finalizing the upgrade to 21.2

### ISSUE THREAD

**Issue by lucy-zhang** [cockroachdb/cockroach#57569]
As part of the process to deprecate interleaved tables (#52009), we need to prohibit upgrading to 21.2 if any interleaved tables exist on the cluster. The plan is to implement a long-running migration using the new framework which repeatedly scans all table descriptors (either by polling or by listening for changes), and only terminates successfully when no more interleaved table descriptors exist. We'd probably want to implement this in the same migration as for #55791.

Epic: CRDB-1582

**Comment by jordanlewis** [comment]
We may choose to postpone this until 22.1.

**Comment by ajwerner** [comment]
We added tables to detect that these relations exist. We want to use those tables.

**Comment by fqazi** [comment]
Fixed via https://github.com/cockroachdb/cockroach/pull/68074
