### ISSUE TITLE
sql: missing event log entries for privilege changes in `crdb_internal.unsafe_xxx`

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#57573]
When a user uses one of the `crdb_internal.unsafe_xxx` functions to overwrite a descriptor, that can incur owner and privilege changes.

Our users expect all owner and privilege changes to be reported in the event log.
This does not occur for these statements. Instead the "unsafe change" event is reported in the event log with an opaque hexadecimal representation of the new descriptor.

The code should evolve to emit discrete events about privilege changes, extracted from the new version of the descriptor.

cc @aaron-crl @thtruo @piyush-singh

**Comment by ajwerner** [comment]
Okay, the main event which changes ownership is `crdb_internal.upsert_descriptor`. What should the format of the events look like? I imagine we'll want to calculate the change between the old and new version of the descriptor with regards to privileges.

Are there specific asks regarding events for deleting descriptors?

**Comment by knz** [comment]
we have already `grant` and `revoke` event types in `event_log.go` I suppose we can continue to reuse those.

For description deletion we have `drop` event types which I suppose could be used here.

**Comment by knz** [comment]
Discussed with @aaron-crl : lower priority. The fact that the unsafe edit event gets logged is already good for our short-term CC security goals. Would be good for 21.1 though.

**Comment by ajwerner** [comment]
@the-ericwang35 I think we can make some progress here. Namely, when we perform `crdb_internal.unsafe_upsert_descriptor` and the previous descriptor also exists, we should construct a set of changes to privileges and owner and populate that in the event. I think that would be sufficient for this issue.

**Comment by knz** [comment]
> and populate that in the event.

... and populate events with that.

(the abstraction is 1 event per change)
