### ISSUE TITLE
build: replace uses of `make` in teamcity scripts by bazel

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#57586]
The TC scripts eg `build/teamcity-test.sh` invoke `make`.

We'll want to transition to use `bazel` eventually.

To consider: 

Today the scripts invoke make then apply some extra processing on the output of `go test -json`  - in particular we have a utility `testfilter` that fixes brokenness in the go test runner. (see `teamcity-support.sh`)

It's important that we continue to apply these processing steps.

(e.g. teamcity-test.sh does `run_json_test build/builder.sh make ...`  and `teamcity-support.sh` contains the definition of run_json_test to do the things explained above)

So I could imagine e.g. that the `teamcity-XXX.sh`  scripts would continue to exist, and simply invoke a bazel command "under" `run_json_test`

Epic CRDB-8306

**Comment by rickystewart** [comment]
Closing this issue in favor of the issues blocking CRDB-8306
