### ISSUE TITLE
Instability Issue: DB doesn't answer queries

### ISSUE THREAD

**Issue by peymanh** [cockroachdb/cockroach#57604]
Hi. We use dockerized cockroachdb on 3 nodes. We've recently face a problem that the DB does not respond to our queries from time to time. We detect this problem by asking some queries periodically by a Prometheus job and visualizing the response. 

By adding the official Cockroach dashboards in Grafana, we see some strange behavior in some parts of the DB.

We've recently deleted a big percentage of data from database by removing some of our tables. Not sure if this is related to our problem since we had this problem even before the deletion.

We even upgraded the Docker image version from v20.1.1 to v20.2.2 But the problem still remains.

**screenshots**
Here is a screenshot of charts in grafana:

![photo_2020-12-05_13-02-07](https://user-images.githubusercontent.com/5622410/101239181-be751480-36fa-11eb-91e8-233cb44a3bc0.jpg)

As you see in the first chart, we have some empty spots, showing that the DB does not answers the query.

**Environment:**
 - CockroachDB version [20.2.2]
 - Server OS: Ubuntu
 - Docker version: 19.03.12

**Comment by peymanh** [comment]
Somehow surprised that after deleting the service and its volume and then re-deploying and restoring the backup, system is kinda healed!

As the charts below show, Number of replicas are decreased and system is almost stable. But maybe It's temporary and we should see whether it stays stable in long terms or not.

![photo_2020-12-05_18-01-06](https://user-images.githubusercontent.com/5622410/101245702-de6cfe00-3723-11eb-9d88-79c81300ac36.jpg)

**Comment by rafiss** [comment]
Are there any logs that show up when the query is not answered? Logs from either the Prometheus side or the CockroachDB would be helpful.

**Comment by peymanh** [comment]
@rafiss 
As you see in the first chart of my second message, it's clear that the db does not respond to our queries. Unfortunately in this case  no log is in hand.

**Comment by rafiss** [comment]
Hmm I'm not sure if we will be able to determine why the database was not answering queries without more information. I was hoping the logs would have some error messages or anything that would say what the database was doing at the time.

Since the issue seems resolved, I will close this issue. If it reoccurs, please reopen the issue and try to provide that information. For example, it would also be helpful to know which queries are issued periodically by the Prometheus job.
