### ISSUE TITLE
sql: support VIRTUAL computed columns

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#57608]
This issue tracks implementing virtual computed columns (using `VIRTUAL` instead of `STORED`). This is closely related to #9682 - the expression-based index columns will be implemented as virtual columns internally. It is also related to hash shared indexes where we would like the bucket column to be virtual.

Running checklist:
 - [x] parser support
 - [x] test catalog support
 - [x] descriptors and catalog support
 - [x] support querying tables with virtual columns
 - [x] mutations of tables with virtual columns (with or without indexes on virtual columns)
   - [x] INSERT
   - [x] DELETE
   - [x] UPDATE
   - [x] UPSERT
     - [x] Add rules for lookup joins with projections to fix plans for UPSERT
 - [x] disallow PK on virtual columns
 - [x] disallow indexes STORING virtual columns
 - [x] disallow FKs on virtual columns
 - [x] disallow computed/virtual columns depending on other virtual columns (already disallowed for all computed columns)
 - [x] support virtual columns in partial index predicates
 - [x] support adding / removing virtual columns
 - [x] support adding / removing indexes on virtual columns
 - [x] disallow or support virtual columns in check constraints
 - [x] support or disallow inverted indexes on virtual columns
 - [x] support unique (and partial unique) indexes on virtual columns
 - [x] support virtual column as leading column on a multi-column inverted index
 - [x] support partial indexes on virtual columns
 - [x] support virtual columns in unique constraints without index
 - [x] teach SQLsmith about virtual columns
 - [x] inline virtual column projections into filters (allowing use of indexes on virtual columns more cases)
 - [x] add backup/restore test with table with virtual columns

Non-critical items:

 - [ ] figure out how to prove implication for cases like:
```
CREATE TABLE t (
  k INT PRIMARY KEY,
  a INT,
  b INT,
  c INT AS (b + 10) VIRTUAL,
  INDEX (a) WHERE c IN (10, 20, 30)
)

SELECT k FROM t WHERE c = 20
```
(filed separate issue #61565).
- [ ] handle numeric references case where we specify a virtual column but not a dependent one (applies to stored computed columns as well); filed separate issue #61563.
- [ ] teach `indexConstraintCtx.simplifyFilter` to remove the redundant filters like the `b:2 = 3` below:
```
exec-ddl
CREATE TABLE tmp (
  a INT,
  b INT,
  v INT AS (b + 10) VIRTUAL,
  INDEX idx (v)
)
----

opt
SELECT * FROM tmp WHERE v = 13
----
  project
   ├── columns: a:1 b:2!null v:3!null
   ├── immutable
   ├── fd: ()-->(2,3)
   ├── select
   │    ├── columns: a:1 b:2!null
   │    ├── fd: ()-->(2)
   │    ├── index-join tmp
   │    │    ├── columns: a:1 b:2
   │    │    └── scan tmp@idx
   │    │         ├── columns: rowid:4!null
   │    │         ├── constraint: /3/4: [/13 - /13]
   │    │         └── key: (4)
   │    └── filters
   │         └── b:2 = 3 [outer=(2), constraints=(/2: [/3 - /3]; tight), fd=()-->(2)]
   └── projections
        └── b:2 + 10 [as=v:3, outer=(2), immutable]
```
(filed separate issue #61566).

21.2 items:
- [ ] use virtual column for hash shared indexes (filed separate issue #61564).

**Comment by ajwerner** [comment]
>  disallow indexes STORING virtual columns

Why this restriction? The virtual columns are going to end up as index keys, why not let them end up as index values?

**Comment by RaduBerinde** [comment]
No strong reason - just trying to limit the initial work. Something we can allow later for sure.

**Comment by RaduBerinde** [comment]
Outstanding items (none of which are critical) have been filed as separate issues; closing this.
