### ISSUE TITLE
sql: privilege inquiry functions don't take role into account

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#57621]
**Describe the problem**

The privilege inquiry functions (e.g. `has_schema_privilege`) check if a user has a privilege on the given schema. It can be called in two ways:
- `has_schema_privilege(user, schema_name, privilege_type)`
- `has_schema_privilege(schema_name, privilege_type)`

In the second way, the user is assumed to be the current user. However, the implementation only checks for the privileges assigned to the _user_, and not the roles that the user belongs to.

**To Reproduce**

```
# Start a fresh cluster and connect as root.

root@:26257/defaultdb> create database my_db;
CREATE DATABASE

root@:26257/defaultdb> CREATE USER my_user;
CREATE ROLE

root@:26257/defaultdb> CREATE ROLE my_role;
CREATE ROLE

root@:26257/defaultdb> GRANT ALL ON DATABASE my_db TO my_role;
GRANT

root@:26257/defaultdb> GRANT my_role TO my_user;
GRANT

# Disconnect, then reconnect with my_user to my_db.
# ./cockroach sql --insecure -u my_user -d my_db

my_user@:26257/my_db> select has_schema_privilege('my_role', 'public', 'usage');
  has_schema_privilege
------------------------
          true

my_user@:26257/my_db> select has_schema_privilege('public', 'usage');
  has_schema_privilege
------------------------
         false
```

**Expected behavior**
`select has_schema_privilege('public', 'usage');` should return `true`.

**Environment:**
Affects version 20.2

**Comment by solongordon** [comment]
Note that there are a number of other `has_x_privilege` built-ins with the same problem: `has_database_privilege`, `has_table_privilege`, etc.
