### ISSUE TITLE
sql: extra schema change jobs are created in ALTER TABLE ... ADD FOREIGN KEY

### ISSUE THREAD

**Issue by lucy-zhang** [cockroachdb/cockroach#57624]
When adding foreign keys to an existing table, `sql.ResolveFK` populates a map of all referenced tables. The problem is that we then indiscriminately queue a schema change job in the user transaction, though we don't update the referenced tables until later in the job:

https://github.com/cockroachdb/cockroach/blob/1ed669de1c3b77798fade7ad9f056edc0bf27c36/pkg/sql/alter_table.go#L314-L320

This shouldn't cause any correctness problems, but it is pointless.

Jira issue: CRDB-3510

**Comment by postamar** [comment]
I don't think we'll do anything about this any time soon.
