### ISSUE TITLE
logging: redact enterprise.license in cockroach.log

### ISSUE THREAD

**Issue by fabiog1901** [cockroachdb/cockroach#57640]
This is a request to redact the enterprise license from the `cockroach.log` file. Using v20.2.2.

```
root@:26257/defaultdb> SET CLUSTER SETTING enterprise.license = 'crl-xxxxxyyyyyzzzz;
SET CLUSTER SETTING

Time: 43ms total (execution 41ms / network 2ms)
```

```
[root@roach-newyork-1 logs]# grep license cockroach.log 
I201207 13:16:38.822304 1569 sql/event_log.go:146 ⋮ [n1,client=‹172.28.0.5:47326›,hostnossl,user=root] Event: ‹"set_cluster_setting"›, target: 0, info: ‹{SettingName:enterprise.license Value:crl-xxxxxyyyyyzzzzz User:root}›
```

**Comment by thtruo** [comment]
cc @knz as it relates to redaction

**Comment by knz** [comment]
The value is already enclosed inside redaction marker. If they extract their logs with redaction (e.g. `cockroach debug --redact-logs` or `cockroach debug merge-logs --redact-logs`), the value would be stripped. What else do they want?
