### ISSUE TITLE
cli: Auto-detection of --locality when running on a public cloud

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#57646]
The --locality flag is currently used to specify tiering of failure domains for optimal replica placement by the allocator (and further customization by user via zone configs).  When running on a public cloud however, there are APIs which can be called when spawning nodes to reveal its locality.  

It would be nice if we could automatically deduce the locality when not provided by users running in a public cloud.

**Comment by knz** [comment]
dup #38474
