### ISSUE TITLE
kvserver: Implement zone configuration changes for multi-region simplification

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#57663]
While the code is stubbed in right now, we will need to make more thorough zone configuration changes as part of the multi-region simplification for 20.2.  This is a placeholder issue which we can use to complete the work.

**Comment by aayushshah15** [comment]
@ajstorm, is this meant to supplement #57505 or did you miss that issue?

**Comment by ajstorm** [comment]
I was thinking it would supplement it, but feel free to handle any way you want.  I looked at #57505 before I created this, and it seemed to focus on the kv aspects of modifying zone config semantics.  This issue is meant to fill in the zone config stubs that @otan created in his initial work, as the full 21.1 zone config implementation wasn't yet ready.
