### ISSUE TITLE
tests: verify raft command compatibility

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#5769]
(this is related to #5677 and was discussed in #5753)

The output of a raft command must be deterministic across all replicas. We have some tests for this with the `CheckConsistency` method, but one place where inconsistencies may be introduced is during the upgrade process. We need some sort of testing framework that can execute a raft command with the current code and ensure that its output is identical with the output of some previous reference version.

A specific case to watch out for: adding a non-nullable proto field changes the marshal output, so it must not be allowed for any proto written by a raft command.

**Comment by tamird** [comment]
This is partially addressed by #6038.

**Comment by spencerkimball** [comment]
@bdarnell, I'm closing this due to imminent proposer-evaluated KV. Seems unlikely we will do anything else here.
