### ISSUE TITLE
sql: add SHOW CREATE DATABASE

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#57692]
With the introduction of additional database information like regions and survival goals, we should also introduce a new round-trippable SHOW CREATE DATABASE that offers the same kind of behavior as SHOW CREATE TABLE. This will allow others to see the primary region, regions, and survival goals for a DB and copy it to use in test environments or other use cases.

**Comment by pawalt** [comment]
Closed by #66033

https://github.com/cockroachdb/cockroach/pull/66033
