### ISSUE TITLE
AdminUI TLS handshake defaulting to AES128 with TLS 1.2 instead of AES256 with TLS 1.3

### ISSUE THREAD

**Issue by keith-mcclellan** [cockroachdb/cockroach#57701]
**Describe the problem**

The webserver for the AdminUI supports a hard-coded list of cypher suites (see lines 174-189 in https://github.com/cockroachdb/cockroach/blob/810eba5adf6552647e1b117cb8713932406d5e2f/pkg/security/tls.go) in priority order, defaulting to AES-128 and not providing an override option.  Even in a scenario where the cert itself is an AES-256 cert the database will do the handshake using a 128 bit cypher.  Ideally this should be configurable, but at the very least this should default to using the most secure cypher suite mutually available to the client and the server.
![Screen Shot 2020-12-07 at 7 41 58 PM](https://user-images.githubusercontent.com/4730669/101498663-5b71c080-393a-11eb-9b22-3ad669a94e0e.png)
![Screen Shot 2020-12-07 at 7 40 41 PM](https://user-images.githubusercontent.com/4730669/101498673-5dd41a80-393a-11eb-8287-20aea3c99707.png)

We are also not defaulting to use TLS 1.3 by default, this also has to be forced on the client side.

**To Reproduce**

Set up a secure cluster using an AES-256 TLS cert for the ui.crt file
Sign into the AdminUI and check the handshake.  You can do this easily in firefox by clicking on the "lock" next to the URL, click into 'Secure Connection', Click more information, and go to the 'Security' Tab.

**Expected behavior**
Web server should either default to the more secure algorithm or be configurable to disable the less secure algorithm.

**Additional data / screenshots**
If I disable the weaker algorithms in Firefox I can force the desired behavior.

![image002](https://user-images.githubusercontent.com/4730669/101499384-33369180-393b-11eb-8fe6-9b9bc618929d.png)
![image001 (1)](https://user-images.githubusercontent.com/4730669/101499393-3467be80-393b-11eb-9ee7-332b91926220.png)

**Additional context**
Security conscious customers

**Comment by awoods187** [comment]
cc @bdarnell

**Comment by aaron-crl** [comment]
Related issues:
* security: Option to configure TLS version and ciphers #48294
* security: add an environment variable to require TLS 1.3 #39746
* 20.2: Document Java TLS error #7820
* release-20.1: security: Disable TLS 1.3 #48365

**Comment by keith-mcclellan** [comment]
This is potentially urgent due to some customer obligations so if we could get this triaged I would appreciate it.

**Comment by bdarnell** [comment]
> The webserver for the AdminUI supports a hard-coded list of cypher suites (see lines 174-189 in https://github.com/cockroachdb/cockroach/blob/810eba5adf6552647e1b117cb8713932406d5e2f/pkg/security/tls.go) in priority order

This list is only used for TLS 1.2. For TLS 1.3 it is ignored (and a [different non-configurable list buried in the go runtime](https://github.com/golang/go/blob/5627a4dc3013fed02c4b8097413643b682cac276/src/crypto/tls/cipher_suites.go#L223-L227) is used instead). 

But the result is the same: a Go server will default to AES-128 unless the client insists on AES-256. The go developers [argue here](https://github.com/golang/go/issues/29349#issuecomment-612122717) that there's no good reason to choose AES-256 over AES-128. (I'm not saying we agree with that, but it is technically very difficult for us to override that decision within CockroachDB)

> We are also not defaulting to use TLS 1.3 by default

I cannot reproduce this. When I connect to CRDB 20.2.1 with a fresh install of firefox I get TLS 1.3.  

> Set up a secure cluster using an AES-256 TLS cert for the ui.crt file

What's an AES-256 TLS cert? The streaming cipher is chosen independently of the cert (which may be RSA or ECC; I don't think there's AES involved anywhere in the cert itself).

**Comment by keith-mcclellan** [comment]
We can close this out, I was able to resolve the conflict with the customer and they accepted the default behavior. Thanks!
