### ISSUE TITLE
sql: support syntactic sugar for `UNIQUE WITHOUT INDEX` in `REGIONAL BY ROW` tables

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#57718]
In addition to adding a hidden region column to all indexes in `REGIONAL BY ROW` tables, we also need to add a hidden `UNIQUE WITHOUT INDEX` constraint for all unique indexes where the region is not explicitly specified. For example, `UNIQUE (col)` should be syntactic sugar for `UNIQUE (region, col), UNIQUE WITHOUT INDEX (col)`, and `PRIMARY KEY (col)` should be syntactic sugar for `PRIMARY KEY (region, col), UNIQUE WITHOUT INDEX (col)`. Note that this does *not* apply to tables with no specified primary key. We should not create a `UNIQUE WITHOUT INDEX` constraint on `rowid`.

#57666 adds a slice `UniqueWithoutIndexConstraints` to the table descriptor, which is a slice of `UniqueWithoutIndexConstraint` objects, each representing a `UNIQUE WITHOUT INDEX` constraint specified in the schema. The syntactic sugar described in this issue should add constraints by appending to that slice. In order to support the hidden aspect of the constraint, we'll probably need to update the `UniqueWithoutIndexConstraint` object to include a `Hidden` field, indicating that the constraint should not show up in `SHOW CREATE TABLE`. We may also want to include an `IndexID` field to track the provenance of the constraint. Provenance will be important for handling the following scenarios:
- If a user drops a `UNIQUE` index in a `REGIONAL BY ROW` table, that should also drop the corresponding `UNIQUE WITHOUT INDEX` constraint.
- If a user alters the index to make the region column explicit, that should also cause the `UNIQUE WITHOUT INDEX` constraint to be dropped.
- If a user tries to drop a hidden `UNIQUE WITHOUT INDEX` constraint directly, we should return an error with a hint referencing the docs and explaining how to remove the constraint: by either dropping the parent index or by altering the index to make the region column explicit.

I think this feature should probably be implemented by the SQL Experience team, but if y'all don't have the bandwidth let me know... cc @ajstorm @otan @arulajmani

**Comment by nvanbenschoten** [comment]
> Note that this does not apply to tables with no specified primary key. We should not create a UNIQUE WITHOUT INDEX constraint on rowid.

@otan do you think we should open a separate issue to track this special case?

**Comment by otan** [comment]
I think anything UNIQUE WITHOUT INDEX related is definitely on the backburner at the moment for the current release.

> @otan do you think we should open a separate issue to track this special case?

It sounds like if we decide to support it yes, but this should be closed as it is no longer required for RBR...

**Comment by rytaft** [comment]
Yea, this issue as a whole has been superseded by implicit partitioning. But the `rowid` case does seem worth considering, at least for the future.

**Comment by nvanbenschoten** [comment]
I pulled this part out into https://github.com/cockroachdb/cockroach/issues/61030 so we can track it separately.
