### ISSUE TITLE
import: mysqldump tracking issue

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#57716]
https://github.com/cockroachdb/cockroach/issues/56241
https://github.com/cockroachdb/cockroach/issues/39401
https://github.com/cockroachdb/cockroach/issues/29305
https://github.com/cockroachdb/cockroach/issues/56121
https://github.com/cockroachdb/cockroach/issues/51654
https://github.com/cockroachdb/cockroach/issues/51651

Epic CRDB-8825

Jira issue: CRDB-3494

**Comment by dikshant** [comment]
With IMPORT MYSQLDUMP and IMPORT PGDUMP being deprecated: #93660 and [Schema Conversion Tool](https://www.cockroachlabs.com/docs/cockroachcloud/migrations-page) being better for schema migrations this is no longer needed and can now be closed.
