### ISSUE TITLE
sql: missing event log entry for CREATE STATISTICS statement

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#57739]
I ran the following:

```
CREATE TABLE t(x) AS SELECT generate_series(1,10000);
CREATE STATISTICS foo FROM TABLE t;
```

After this I don't see an entry in `system.eventlog`.

This is strange, because the file `create_stats.go` does contain some call to `InsertEventRecord()`, but I think it's only done when a create stats job is "resumed". Maybe a direct CREATE STATS statement does not "resume" a job and that is why not event log entry is filed.

**Comment by knz** [comment]
cc @thtruo this makes DDL logging incomplete

**Comment by thtruo** [comment]
cc @awoods187 putting this on your radar for SQL Execution / SQL Optimizer. This is a bug Raphael identified while standardizing `system.eventlog`
