### ISSUE TITLE
sql: event log entries for DROP TABLE,INDEX CASCADE + ALTER TABLE do not properly include the fully qualified names for dropped views

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#57735]
See in system.eventlog:

```
 drop_table          |       55 |           1 | {"TableName":"defaultdb.public.x","Statement":"DROP TABLE x CASCADE","User":"demo","CascadeDroppedViews":["y"]}

 drop_index           |       59 |           1 | {"TableName":"defaultdb.public.u","IndexName":"u_x_key","Statement":"DROP INDEX defaultdb.public.u@u_x_key CASCADE","User":"demo","MutationID":1,"CascadeDroppedViews":["v"]}
```

The `CascadeDroppedViews` field is populated with the "short" names of the views; this makes it impossible to determine from which logical schema or database they were dropped from.

Note: there is also a "dropped view" payload for `ALTER TABLE`, but I was not able to construct the example. The code path is the same though so it has the same bug.

**Comment by knz** [comment]
cc @thtruo - this is needed to properly productionize our DDL logging. Can you chase that up with the SQL teams?

**Comment by thtruo** [comment]
cc @vy-ton putting this on your radar for SQL schema. This is a bug Raphael identified while standardizing `system.eventlog`
