### ISSUE TITLE
sql: figure out how PARTITION BY with REGIONAL BY ROW works

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#57731]
Are we allowing users who have already partitioned their data to also partition with REGIONAL BY ROW? How will that look?

If not, we should block it nicely. We need to think of a good migration path, however.

**Comment by nvanbenschoten** [comment]
We decided that we would block this.

> We need to think of a good migration path, however.

What kind of migration are you thinking? If we don't support ALTER TABLE SET LOCALITY REGIONAL BY ROW then there's not much to support. If we do, is a descriptive error message enough?

**Comment by otan** [comment]
If a user who used to partition manually decides to use our multi-region framework, what's the upgrade path?

**Comment by otan** [comment]
(this was a place holder issue for an unimplemented error)

**Comment by otan** [comment]
We decided against this:

Nathan: > I don’t think there’s a strong reason to support it. We already won’t allow users to configure (most of the) zone configs for these tables, so partitioning doesn’t provide too much value.
Andy: > I vote no
