### ISSUE TITLE
sql: event log entries for ALTER/DROP TYPE do not properly include the fully qualified type name

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#57734]
Compare in system.eventlog:

```
 drop_table          |       54 |           1 | {"TableName":"defaultdb.public.t","Statement":"DROP TABLE t","User":"demo","CascadeDroppedViews":null}

 drop_type           |       52 |           1 | {"TypeName":"t","Statement":"DROP TYPE defaultdb.public.t","User":"demo"}

 alter_type           |       58 |           1 | {"TypeName":"g","Statement":"ALTER TYPE defaultdb.public.f RENAME TO g","User":"demo"}

```

The `TypeName` field is incompletely populated.

All the while, the field for CREATE TYPE is in fact properly populated.

For information, the call to ` p.ResolveMutableTypeDescriptor()` in `drop_type.go` modifies its `name` argument in-place to produce the fully qualified name. It is thus possible to use the resulting `name` as argument in the event log.

However this solution is incomplete, because that only gives the name for the "main" type. The FQ name for the associated array type cannot be obtained this way.

**Comment by knz** [comment]
cc @thtruo  - this is needed to properly productionize our DDL logging. Can you chase that up with the SQL teams?

**Comment by thtruo** [comment]
cc @vy-ton putting this on your radar for SQL schema. This is a bug Raphael identified while standardizing `system.eventlog`

**Comment by knz** [comment]
Discussed with @aaron-crl : lower priority.
