### ISSUE TITLE
sql: missing event log entries for ALTER .. SET SCHEMA statements

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#57741]
We have event log entries for table/views/sequence renames, however no event log entry is generated for SET SCHEMA.

This is inconsistent, as SET SCHEMA definitely changes the way that objects are named.

(Also arguably ALTER TYPE RENAME should also have a separate event log type)

Found while working on #57737

**Comment by knz** [comment]
cc @thtruo this is needed for proper DDL logging

**Comment by thtruo** [comment]
cc @vy-ton putting this on your radar for SQL schema. This is a bug Raphael identified while standardizing `system.eventlog`

**Comment by knz** [comment]
Discussed with @aaron-crl : lower priority for the immediate CC free tier security goals, but we wish this to be available in v21.1.

**Comment by jordanlewis** [comment]
cc @the-ericwang35
