### ISSUE TITLE
sql: event log entry for COMMENT ON INDEX,COLUMN does not properly qualify its TableName payload

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#57740]
See:

```
 comment_on_index    |       52 |           1 | {"TableName":"t","IndexName":"primary","Statement":"COMMENT ON INDEX t@primary IS 'foo'","User":"demo","Comment":"foo"}

comment_on_column   |       52 |           1 | {"TableName":"t","ColumnName":"x","Statement":"COMMENT ON COLUMN t.x IS 'foo'","User":"demo","Comment":"foo"}
```

The `TableName` field is improperly qualified. For reference, `COMMENT ON TABLE` qualifies it properly.

**Comment by knz** [comment]
cc @thtruo this is needed for proper DDL logging

**Comment by thtruo** [comment]
cc @vy-ton putting this on your radar for SQL schema. This is a bug Raphael identified while standardizing `system.eventlog`

**Comment by knz** [comment]
Discussed with @aaron-crl : lower priority.
