### ISSUE TITLE
sql: audit all information in the DB Console and ensure end points exist

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#57763]
Many customers do not want to use the DB Console because they want to centralize all of their metrics (e.g, application, database, infrastructure) into one tool. Popular tools include Grafana, Prometheus, etc. 

We should audit all of the existing metrics and make sure we have endpoints that can be exported to grafana. 

This is related to https://github.com/cockroachdb/cockroach/issues/54178 but different in that we are auditing existing functionality. All new items added to the DB Console should also come with endpoints. 

Jira issue: CRDB-3489

**Comment by asubiotto** [comment]
@asubiotto possibly to work on this in the February timeframe. Need to get done for 21.2 for adequate planning.
