### ISSUE TITLE
sql: evaluate methods to hold query plans constant

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#57767]
Changing query plans (due to new statistics etc.) can lead to unpredictable performance. Other databases offer methods to trade of potential query plan improvements for consistent performance by holding query plans constant.

Potential ideas to explore:

- Pinning query plans and not changing them until the user "approves" the new plan
- Offer multiple versions of the CBO (e.g., 19.2 CBO, 20.1 CBO, 20.2 CBO) so that users can hold onto semantics they understand
- Expand hinting 

Jira issue: CRDB-3486

**Comment by yuzefovich** [comment]
dup of #121502
