### ISSUE TITLE
docs: support basic and advanced SQL grammar doc generation

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#5777]
I was thinking that, especially as we add more complexities to the SQL grammar (e.g. #5762), it would be cool if we had a "basic vs full" toggle on the SQL doc pages. The idea would be to hide various parts of the grammar when browsing with the "basic" setting.

One way in which we could achieve this without much pain would be to use a preprocessor (e.g. gpp, gnu-m4) and add preprocessor conditionals around the advanced parts of the grammar in `sql.y`. Then, depending how we run the preprocessor we could generate either one. I can look into the preprocessor part if we think this is doable from the doc perspective. @jseldess @mjibson 

Jira issue: CRDB-6195

**Comment by jseldess** [comment]
Sounds worthwhile to me, @RaduBerinde. Thanks! Would this be just for the full grammar or also for statement-specific diagrams, e.g., https://www.cockroachlabs.com/docs/alter-table.html?

**Comment by RaduBerinde** [comment]
I think they are being generated form the same data, if so it would include those.

**Comment by RaduBerinde** [comment]
We already use "SKIP DOC" as a way to hide certain parts from documentation. We could add a separate "ADVANCED DOC" to conditionally include certain parts.

https://github.com/cockroachdb/docs/blob/a300652b77888f9e664aad9c3ed5e8960b476d85/generate/extract/extract.go#L84

**Comment by petermattis** [comment]
Marking as Later for now. @jseldess Is there anything we're planning to do here for 1.0?

**Comment by jseldess** [comment]
I don't think we'll have the bandwidth to handle this for 1.0. Instead, based on user feedback, we've tried to foreground the statement-specific docs and diagrams over the full grammar. 

Definitely worth revisiting this later, though.

**Comment by jseldess** [comment]
@tbg, I don't think it makes sense to transfer this to the docs repo because the work would have to happen here in the code. That said, I also don't know of a docs project in this repo that would work. Would you mind creating a new docs project for code changes that relate to docs (auto-generated content, etc.)?

**Comment by tbg** [comment]
A docs project here SGTM. Just create one for yourself: https://github.com/cockroachdb/cockroach/projects/
