### ISSUE TITLE
kv: test failures with `attempting to send snapshot that does not contain the recipient` error

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#57785]
We've recently begun seeing test failures with errors like:
```
attempting to send snapshot that does not contain the recipient as a replica; snapshot type: LEARNER_INITIAL, recipient: s(n2,s2):2LEARNER, desc: r1:/M{in-ax} [(n1,s1):1, next=3, gen=2]
```
The earliest instance of this was on https://github.com/cockroachdb/cockroach/commits/aa69b42032f89d1bb777986ff7a8d4f753b71d83.

Instances:
#57626
#57549
#57545

The most likely suspects to have caused this are https://github.com/cockroachdb/cockroach/pull/56735 and https://github.com/cockroachdb/cockroach/pull/56594.

**Comment by ajwerner** [comment]
I *think* https://github.com/cockroachdb/cockroach/pull/56596 is the culprit. cc @andreimatei

**Comment by nvanbenschoten** [comment]
I just hit this while stressing `TestKVNemesisMultiNode` as well. @tbg is the proper fix for this to mark [the error](https://github.com/cockroachdb/cockroach/blob/690c12210061a5675e92117f5c9812ee88709d65/pkg/kv/kvserver/replica_command.go#L2034) with an `errMarkSnapshotError` so that it is caught by `isSnapshotError`/`IsRetriableReplicationChangeError`?
