### ISSUE TITLE
sql: reject index on REGIONAL BY ROW table with non-prefix use of crdb_region column

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#57788]
As described in https://github.com/cockroachdb/cockroach/issues/57718, we will allow users to create unique/non-unique primary/secondary indexes that include the `crdb_region` column. This can be used to avoid global uniqueness in cases where it is not needed.

However, this is only possible if we reject indexes that use the `crdb_region` column in a non-prefix position.

**Comment by ajstorm** [comment]
@otan can you please confirm whether or not you've addressed all of this?  I think it's done, but wanted confirmation before closing.

**Comment by otan** [comment]
not requiring PARTITION BY means we no longer needs to do this
