### ISSUE TITLE
*: instances of //go:generate should be bazelified

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#57787]
We have generated files with `//go:generate` that need be rewritten in the sandbox provided that any depending files have changed: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/cockroachdb/cockroach%24+//go:generate&patternType=literal

These need to replaced with a bazel `genrule`.  When using something like `stringer`, we may need https://github.com/kubernetes/repo-infra/blob/master/defs/go.bzl#L108 to do so such that `go` can run `stringer`.

This can be broken down into several streams:
* `//go:generate stringer` (try send only doing this for one PR for one before going through the rest. break this up for ease of review! try look and see of the kubernetes repo already handles this)
* `//go:generate langgen`
* `//go:generate go run ...` (anything that has a go run as a prefix) # note we may need to put this into a separate package if it runs something in the same package. 

These are non-high priority:
* Anything that is roachprod / test related (but doing it is a definite bonus). You can determine this by checking if the package is depended on by `cockroach-short` by running `bazel query 'rdeps(pkg/cmd/cockroach-short, //pkg/util/cache:cache)'`
* `//go:generate ../util/leaktest/add-leaktest.sh` // this is only for tests - happy to let this slide until the CI stage

**Comment by alan-mas** [comment]
I am going to split this into several PR as well as different issues.

First issue will be related to:
//go:generate stringer (try send only doing this for one PR for one before going through the rest. break this up for ease of review! try look and see of the kubernetes repo already handles this)

**Comment by alan-mas** [comment]
Hey @otan !

After checking the `cockroachdb` repository with the help of the `ag` you shared with me:
`ag 'go:generate (?!stringer)' pkg  -l --ignore '*_test.go'`

Avoiding all the `main_test.go` as _main_test.go is a test file, i.e. it behaves the same as sql_test.go for example -- it does not impact the cockroach-short binary at all_

I got this list below:
```
pkg/cmd/roachprod/vm/aws/config.go
-pkg/cmd/roachprod/vm/aws/BUILD.bazel

pkg/kv/kvserver/concurrency/lock_table.go
-pkg/kv/kvserver/concurrency/BUILD.bazel

pkg/kv/kvserver/spanlatch/manager.go
-pkg/kv/kvserver/spanlatch/BUILD.bazel

pkg/util/timeutil/zoneinfo.go
-pkg/util/timeutil/BUILD.bazel

pkg/util/interval/generic/example_t.go
-pkg/util/interval/generic/BUILD.bazel

pkg/util/interval/generic/doc.go
-pkg/util/interval/generic/BUILD.bazel

pkg/util/log/channels.go
-pkg/util/log/BUILD.bazel

pkg/security/securitytest/securitytest.go
-pkg/security/securitytest/BUILD.bazel

pkg/roachpb/batch.go
-pkg/roachpb/BUILD.bazel

pkg/sql/conn_fsm.go
-pkg/sql/BUILD.bazel

pkg/sql/opt/optgen/lang/expr.go
-pkg/sql/opt/optgen/lang/BUILD.bazel
```

Checked one by one all of those files and could see that all of them have the `//go:generate stringer` file inside main `go_library` and without any `# keep` flag, so that seems to me tht are handled by `gazzelle`.

That seems correct to you? or I am missing something?

**Comment by otan** [comment]
> Checked one by one all of those files and could see that all of them have the //go:generate stringer file inside main go_library and without any # keep flag, so that seems to me tht are handled by gazzelle.

I don't think that's true. I don't gazelle is smart enough to run https://github.com/cockroachdb/cockroach/blob/master/pkg/util/timeutil/zoneinfo.go#L20 for example in `pkg/util/timeutil/zoneinfo.go`

You will need to do something similar to https://github.com/cockroachdb/cockroach/pull/57705

**Comment by alan-mas** [comment]
> > Checked one by one all of those files and could see that all of them have the //go:generate stringer file inside main go_library and without any # keep flag, so that seems to me that are handled by gazzelle.
> 
> I don't think that's true. I don't gazelle is smart enough to run https://github.com/cockroachdb/cockroach/blob/master/pkg/util/timeutil/zoneinfo.go#L20 for example in `pkg/util/timeutil/zoneinfo.go`
> 
> You will need to do something similar to #57705

OHHHHH I GOT YOUR POINT!

My confusion was because on that example you shared with me #57705

All the bazel files had the `# keep` flag so I assumed that this files as well will have that `# keep` flag (as `gazzelle` was not taking or counting with them)

For example this one:
```
        "encode.go",
        "experimental_keywords.go",
       -- "keywords.go",  # keep
       --  "tokens.go",  # keep
       ++  ":gen-keywords",  # keep
       ++ ":gen-tokens",  # keep
```
`keywords.go` got replaced with `:gen-keywords` but `keywords.go` got already that `# keep` flag so I was expecting all the new `.go` files to have it. Sorry for that confusion.

So no matter if they have the `# keep` flag we need to replace them with a bazel `genrule` to create the files within the sandbox, right?

**Comment by otan** [comment]
Hey alan -- I haven't been looking at stringer closely at the moment to know the whole truth, I've been trusting what you have been saying. If you want me to make sure let me know and I can dig deeper than right now.

> As it has no # keep flag I assumed it was already handled by gazzelle is that correct? if that statement is not correct, then we will need to create those files as well inside bazel sanbox using a gen-rule per each.

Not necessarily. `# keep` just forces gazelle to not delete or re-add the `srcs` key if it detects the file disappears. You only really want this if you add a file in that disappears when `gazelle` runs, and it disappears. It has no bearing on whether anything is automatically generated.

> if I run bazel build //pkg/kv/kvclient/kvcoord:kvcoord is working but inside bazel sandbox bazel-bin is only creating pkg/kv/kvclient/kvcoord/kvcoord.a and pkg/kv/kvclient/kvcoord/kvcoord.x also needs to create txn_coord_sender.go as well?

Did you run it with `--sandbox-debug`? That persists the `.go` file in the sandbox.

This should generate a new file `txnstate_string.go` which is the output of stringer based on `//go:generate stringer -type=txnState`. A good way of testing if gazelle actually works with `stringer` automatically is to add a string and use it without running `make buildshort`. If it compiles using `bazel build ...`, then gazelle automatically includes the stringer. If not, you'll need to handle it like the code below.

> I checked some stringer code handled before like in rule_name_stringer.go or that scenario is different?

I've been trusting your research on this, let me know if you want me to independently verify this. Based on what you linked, it seems like you would need to do this kind of thing for each `stringer` rule.

**Comment by otan** [comment]
@alan-mas i think we should start getting the code down for some of this by doing a few of the non-stringer items.

We can look into whether gazelle automatically does stringer later - at the moment I'm not sure it does, can you give some evidence of this? `#keep` is unfortunately not evidence gazelle does that.

**Comment by alan-mas** [comment]
> Did you run it with `--sandbox-debug`? That persists the `.go` file in the sandbox from experience.

Yeap I tried with and without `--sandbox_debug` and there's no more files inside bazel sandbox than `pkg/kv/kvclient/kvcoord/kvcoord.a` and `pkg/kv/kvclient/kvcoord/kvcoord.x`

> can you give some evidence of this? `#keep` is unfortunately not evidence gazelle does that.

No, as you said "#keep is unfortunately not evidence gazelle does that." so my assumptions were totally incorrect. And also there is no `txnstate_string.go` file created inside bazel sandbox, that seems another prove that, as you said, `gazzelle` is not taking care of them.

**Comment by alan-mas** [comment]
Hey!
For `//go:generate langgen` I can see only this 2 files:
```
go:generate langgen -out expr.og.go exprs lang.opt
go:generate langgen -out operator.og.go ops lang.opt
```
We are already handling those 2 files within 'bazel`sandbox in [pkg/sql/opt/optgen/lang/BUILD.bazel](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/opt/optgen/lang/BUILD.bazel#L62-L81)

So I will start checking now 3rd part:
`//go:generate go run ...`

**Comment by alan-mas** [comment]
To keep on track on the effort for the 3rd part `//go:generate go run ...` these are the files that we are moving into bazel sandbox we've got them using this query `ag 'go:generate (?!stringer)' pkg  -l --ignore '*_test.go'`:
```
pkg/cmd/roachprod/vm/aws/config.go
//go:generate terraformgen -o terraform/main.tf
//go:generate go-bindata -mode 0600 -modtime 1400000000 -pkg aws -o embedded.go config.json old.json

pkg/kv/kvserver/concurrency/lock_table.go
//go:generate ../../../util/interval/generic/gen.sh *lockState concurrency

pkg/kv/kvserver/spanlatch/manager.go
//go:generate ../../../util/interval/generic/gen.sh *latch spanlatch

pkg/util/timeutil/zoneinfo.go
//go:generate go run generate_lowercase_timezones.go

pkg/util/interval/generic/example_t.go
//go:generate ./gen.sh *example generic

pkg/util/interval/generic/doc.go
//go:generate ../../util/interval/generic/gen.sh *latch spanlatch

pkg/util/log/channels.go
//go:generate go run ./gen.go logpb/log.proto logging.md ../../../docs/generated/logging.md
//go:generate go run ./gen.go logpb/log.proto severity.go severity/severity_generated.go
//go:generate go run ./gen.go logpb/log.proto channel.go channel/channel_generated.go
//go:generate go run ./gen.go logpb/log.proto log_channels.go log_channels_generated.go

pkg/security/securitytest/securitytest.go
//go:generate go-bindata -mode 0600 -modtime 1400000000 -pkg securitytest -o embedded.go -ignore README.md -ignore regenerate.sh test_certs
//go:generate gofmt -s -w embedded.go
//go:generate goimports -w embedded.go

pkg/roachpb/batch.go
//go:generate go run -tags gen-batch gen_batch.go

pkg/sql/conn_fsm.go
//go:generate ../util/fsm/gen/reports.sh TxnStateTransitions stateNoTxn
```

**Comment by alan-mas** [comment]
New 3 go generate files got added within [this commit](https://github.com/cockroachdb/cockroach/commit/957b1c8be9239f6b5e59cb462e13c532f80d9f89#diff-c246f3f771ac36e62ad8b777880a77808f4f3d1e9d4ace2e327cb7441141c6e5):
```
pkg/sql/schemachanger/scop/mutation.go
pkg/sql/schemachanger/scop/backfill.go
pkg/sql/schemachanger/scop/validation.go
```

**Comment by alan-mas** [comment]
Just as an update, by running: `ag 'go:generate stringer' pkg -l` we've got below `stringer` file list as of today,
all that are already taken care inside `bazel sandbox` are marked.
**PLEASE NOTE**: that there is still no process that ensures no new stringer files are taking care by `bazel`, so in the meantime of this implementation we might need to re run `ag` command from time to time.

- [ ] source: pkg/kv/kvclient/kvcoord/txn_coord_sender.go
autogenerated file: txnstate_string.go
- [ ] source: pkg/kv/kvserver/replica_raft.go
autogenerated file: refreshraftreason_string.go
- [ ] source: pkg/util/timeutil/pgdate/fields.go
autogenerated file: field_string.go
- [ ] source: pkg/util/timeutil/pgdate/parsing.go
autogenerated file: parsemode_string.go
- [ ] source: pkg/util/encoding/encoding.go
autogenerated file: type_string.go
- [ ] source: pkg/clusterversion/cockroach_versions.go
autogenerated file: key_string.go
- [ ] source: pkg/roachpb/method.go
autogenerated file: method_string.go
- [ ] source: pkg/roachpb/errors.go
autogenerated file: errordetailtype_string.go
- [ ] source: pkg/ccl/sqlproxyccl/error.go
autogenerated file: errorcode_string.go
- [ ] source: pkg/cli/flags_util.go
autogenerated file: keytype_string.go
- [ ] source: pkg/workload/schemachange/schemachange.go
autogenerated file: txstatus_string.go
- [ ] source: pkg/workload/schemachange/operation_generator.go
autogenerated file: optype_string.go
- [ ] source: pkg/base/test_server_args.go
autogenerated file: testclusterreplicationmode_string.go
- [ ] source: pkg/sql/roleoption/role_option.go
autogenerated file: option_string.go
- [ ] source: pkg/sql/privilege/privilege.go
autogenerated file: kind_string.go
- [ ] source: pkg/sql/sem/tree/create.go
autogenerated file: createtypevariety_string.go
- [ ] source: pkg/sql/sem/tree/stmt.go
autogenerated file: statementtype_string.go
- [ ] source: pkg/sql/catalog/descpb/privilege.go
autogenerated file: privilegedescversion_string.go
- [ ] source: pkg/sql/catalog/descpb/structured.go
autogenerated file: formatversion_string.go
- [ ] source: pkg/sql/colfetcher/cfetcher.go
autogenerated file: fetcherstate_string.go
- [ ] source: pkg/sql/schemachanger/scop/ops.go
autogenerated file: type_string.go
- [ ] source: pkg/sql/opt/optgen/lang/scanner.go
autogenerated file: token_string.go
- [ ] source: pkg/sql/opt/optgen/lang/expr.go (uses operator.og.go)
autogenerated file: operator_string.go
- [ ] source: pkg/sql/schemachange/alter_column_type.go
autogenerated file: columnconversionkind_string.go
- [ ] source: pkg/sql/execinfra/processorsbase.go
autogenerated file: procstate_string.go
- [ ] source: pkg/sql/execinfra/base.go
autogenerated file: consumerstatus_string.go
- [ ] source: pkg/sql/txn_state.go
autogenerated file: txnevent_string.go
autogenerated file: txntype_string.go
autogenerated file: advancecode_string.go
- [ ] source: pkg/sql/distsql_physical_planner.go
autogenerated file: nodestatus_string.go
- [ ] source: pkg/sql/pgwire/pgwirebase/encoding.go
autogenerated file: pgnumericsign_string.go
autogenerated file: formatcode_string.go
- [ ] source: pkg/sql/pgwire/pgwirebase/msg.go
autogenerated file: clientmessagetype_string.go
autogenerated file: servererrfieldtype_string
autogenerated file: servermessagetype_string.go
autogenerated file: preparetype_string.go

**Comment by alan-mas** [comment]
GO RUN
Just as an update, by running: `ag 'go:generate (?!stringer)' pkg -l --ignore '*_test.go'` we've got below `go run` file list as of today, all that are already taken care inside bazel sandbox are marked.

- source: pkg/cmd/roachprod/vm/aws/config.go
> - [ ] autogenerated file: pkg/cmd/roachprod/vm/aws/terraform/main.tf (missing to run with bazel build short)
> - [ ] autogenerated file: pkg/cmd/roachprod/vm/aws/embedded.go -- done

- source: pkg/kv/kvserver/concurrency/lock_table.go
> - [ ] autogenerated file: pkg/kv/kvserver/concurrency/lockstate_interval_btree.go
> - [ ] autogenerated file: pkg/kv/kvserver/concurrency/lockstate_interval_btree_test.go

- source: pkg/kv/kvserver/spanlatch/manager.go
> - [ ] autogenerated file: pkg/kv/kvserver/spanlatch/latch_interval_btree.go
> - [ ] autogenerated file: pkg/kv/kvserver/spanlatch/latch_interval_btree_test.go

- source: pkg/util/timeutil/zoneinfo.go
> - [ ] autogenerated file: pkg/util/timeutil/generate_lowercase_timezones.go --done

- source: pkg/util/interval/generic/example_t.go
> - [ ] autogenerated file: pkg/util/interval/generic/example_interval_btree.go
> - [ ] autogenerated file: pkg/util/interval/generic/example_interval_btree_test.go

- source: pkg/util/interval/generic/doc.go
> - [ ] autogenerated file: pkg/util/interval/generic/example_interval_btree.go
> - [ ] autogenerated file: pkg/util/interval/generic/example_interval_btree_test.go

- source: pkg/util/log/channels.go
> - [ ] autogenerated file: docs/generated/logging.md (missing to run with bazel build short)
> - [ ] autogenerated file: pkg/util/log/severity/severity_generated.go -- done
> - [ ] autogenerated file: pkg/util/log/channel/channel_generated.go -- done
> - [ ] autogenerated file: pkg/util/log/log_channels_generated.go --done

- source: pkg/security/securitytest/securitytest.go
> - [ ] autogenerated file: pkg/security/securitytest/embedded.go --done

- source: pkg/roachpb/batch.go
> - [ ] autogenerated file: pkg/roachpb/batch_generated.go --done

- source: pkg/sql/conn_fsm.go
> - [ ] autogenerated file: pkg/sql/txnstatetransitions_diagram.gv
> - [ ] autogenerated file: pkg/sql/txnstatetransitions_diagram.png
> - [ ] autogenerated file: pkg/sql/txnstatetransitions_report.txt

- source: pkg/sql/schemachanger/scop/mutation.go
> - [ ] autogenerated file: pkg/sql/mutation_visitor_generated.go

- source: pkg/sql/schemachanger/scop/backfill.go
> - [ ] autogenerated file: pkg/sql/backfill_visitor_generated

- source: pkg/sql/schemachanger/scop/validation.go
> - [ ] autogenerated file: pkg/sql/validation_visitor_generated

**Comment by rickystewart** [comment]
What about the files `*_test.go`? Would be helpful to start keeping track of that stuff.

**Comment by alan-mas** [comment]
I think yes, but in the last tracking Olive suggested to ignore them based on:
_main_test.go is a test file, i.e. it behaves the same as sql_test.go for example -- it does not impact the cockroach-short binary at all_
that is why we are not tracking them (yet)

**Comment by rickystewart** [comment]
Found the following two `stringer` files that aren't Bazelfied:

```
pkg/kv/kvserver/closedts/sidetransport/cantclosereason_string.go
pkg/sql/sem/tree/statementtype_string.go
```

**Comment by rickystewart** [comment]
> PLEASE NOTE: that there is still no process that ensures no new stringer files are taking care by bazel, so in the meantime of this implementation we might need to re run ag command from time to time.

#64241 for this.

**Comment by rickystewart** [comment]
These 3 files have `go:generate`s that are unhandled:

```
pkg/ccl/sqlproxyccl/tenant/directory.go
pkg/security/certmgr/cert.go
pkg/server/api_v2.go
```

**Comment by rickystewart** [comment]
The `go:generate swagger` in `pkg/server/api_v2.go` isn't actually used for anything, so this is actually already done :)
