### ISSUE TITLE
sql: Link to deprecation docs when returning ERROR for cross-database references

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/cockroach#57782]
Received feedback that the below error message for cross databases should link to the [Github issue for removal](https://github.com/cockroachdb/cockroach/issues/55791) so that users can provide feedback. We can also link to [deprecation docs](https://www.cockroachlabs.com/docs/releases/v20.2.0.html#deprecations)

```
ERROR: the view cannot refer to other databases; (see the 'sql.cross_db_views.enabled' cluster setting)
```

**Comment by vy-ton** [comment]
@ericharmeling for input on the error message wording

**Comment by ericharmeling** [comment]
In the case of views, I'd make the text read something like:

```
ERROR: views cannot refer to objects in other databases. By default, cross-database references are disabled for views with the sql.cross_db_views.enabled cluster setting.
Note that cross-database references will be deprecated in a future release. For details, see https://www.cockroachlabs.com/docs/releases/v20.2.0.html#deprecations.
```

The first two sentences of the message depend on the referencing object, but the two sentences after the newline should be the same for FKs, sequences, and UDTs. We link to the tracking issue from the doc, so I'm not sure we need both URLs.

**Comment by vy-ton** [comment]
@ericharmeling Thoughts on `Note that cross-database references will be removed in a future release` since the current status is already deprecation?

**Comment by ericharmeling** [comment]
> @ericharmeling Thoughts on `Note that cross-database references will be removed in a future release` since the current status is already deprecation?

Sorry for the late response. Are cross-database references officially deprecated in v20.2? I can update the docs if yes.

**Comment by arulajmani** [comment]
> Sorry for the late response. Are cross-database references officially deprecated in v20.2? I can update the docs if yes.

Yeah, they are. Aren't the docs already updated at: https://www.cockroachlabs.com/docs/releases/v20.2.0.html#deprecations?

**Comment by ericharmeling** [comment]
> > Sorry for the late response. Are cross-database references officially deprecated in v20.2? I can update the docs if yes.
> 
> Yeah, they are. Aren't the docs already updated at: https://www.cockroachlabs.com/docs/releases/v20.2.0.html#deprecations?

Yes. I just updated this page.

**Comment by ericharmeling** [comment]
https://github.com/cockroachdb/docs/pull/9492
