### ISSUE TITLE
lease: leases are not retained after IMPORT INTO

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#57834]
**Describe the problem**

IMPORT INTO takes a table offline. When the lease manager notices that a table is offline, it marks the table as dropped. When the table comes back online the table, the dropped annotation is never removed. This leads to the lease always being dropped upon dereferencing.

**To Reproduce**

Run `IMPORT INTO` on a table and then try to interact with it. With vmodule logging you can see that the lease will get released upon dereference.

**Expected behavior**

Leases would be retained once the table is back online.

**Additional context**

Restarting the nodes after the `IMPORT INTO` will resolve the problem as the invalid state is just in memory.

**Comment by jordanlewis** [comment]
Andrew, what is the user-visible consequence of this issue?

**Comment by jordanlewis** [comment]
Is it that all queries need to query descriptor/namespace on these tables, for every query?

**Comment by ajwerner** [comment]
> Is it that all queries need to query descriptor/namespace on these tables, for every query?

Exactly. Unless the nodes is restarted.
