### ISSUE TITLE
release-20.1: `SHOW TABLES` don't show temp tables created in the same session

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#57843]
**Describe the problem**
```
set experimental_enable_temp_tables=true;

create temp table foo (id INT);

show tables;

root@:26257/defaultdb> show tables;
  table_name
--------------
(0 rows)

Time: 1.405ms
```

show schemas has the pg_temp schema.

This is on release-20.1.

**Comment by rafiss** [comment]
We aren't prioritizing this since it only affects 20.1 and it's an experimental feature. Please let us know if it is more important to fix.

**Comment by rafiss** [comment]
closing since there are no more planned 20.1 releases.
