### ISSUE TITLE
Upgrade OpenTracing interfaces used in CRDB

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#57908]
[OpenTracing](https://opentracing.io/) merged with OpenCensus to form [OpenTelemetry](https://opentelemetry.io/). Creating this ticket to track the work to upgrade OpenTracing interfaces currently linked in CRDB.

**Comment by thtruo** [comment]
cc @andreimatei

**Comment by knz** [comment]
cc @tbg I think that's more for your radar's than andrei's.

**Comment by tbg** [comment]
I had looked a while back and I don't think it'll pay off to be proactive here. Everything seemed in-flux. I think when we see jaeger or zipkin start nudging us towards the new interfaces is when we can reasonably start looking into this.

**Comment by andreimatei** [comment]
I've been working on moving us to OpenTelemetry. It's nice that they've pretty much standardized on a single tracer implementation, and they provide a collector for those traces that can then be configured to send them out to any number of services. This all allows us to simplify the code a bunch. I should have a PR soon.

**Comment by andreimatei** [comment]
The OpenTelemetry libraries have protos compiled with a newer gogoproto compiler and so want a newer gogoproto than we have, but the upgrade is not so easy because of #56378.

**Comment by andreimatei** [comment]
I've got the integration working in a branch. It's a beaut - traces go from CRDB to the OpenTelemetry Collector and from there to Jaeger (and presumably also to every other trace collector system on the planet).

**Comment by Lukens4242** [comment]
FYI, I have a customer that is also looking to integrate with OpenTelemetry.

**Comment by thtruo** [comment]
Checking in @andreimatei - saw that PRs and a commit was referencing this issue. Do you anticipate that this will be part of the 21.2 release?

**Comment by andreimatei** [comment]
Definitely not 21.2; that door has closed. But I am working on it at the moment, so I think it'll be on master in a few days.

**Comment by thtruo** [comment]
Ack. I'm curious is this a type of change where we're comfortable backporting to 21.2? Or, as I'm currently assuming, it's a big enough change that it will only be made available for the next major release?

**Comment by andreimatei** [comment]
It's pretty big. I wouldn't backport it...

**Comment by thtruo** [comment]
Got it, I had that same hunch. Appreciate the confirmation Andrei!

**Comment by Lukens4242** [comment]
Thank you for the information.

David Lukens
Cockroach Labs - Enterprise Architect
Mobile: (614) 420-5371
ITILv3 - Expert
***@***.***
