### ISSUE TITLE
backupccl: version of SHOW BACKUP that gives ownership data

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#57906]
When users RESTORE we set the ownership of the restored object to the user running the RESTORE. That user then has the option to move ownership later on, but they don't have a way to see who the original owner was. We have `SHOW BACKUP...WITH PRIVILEGES` but that doesn't include `owner` information.

The goal here is to either extend `WITH PRIVILEGES` to include ownership, have a separate option for seeing ownership or having ownership as a column we show by default. For API stability reasons, we might want to hide it behind a flag but I'm open to suggesting.

** Alternative **
- An option on RESTORE to restore with ownership retained. If there's a collision of ownership (e.g. user no longer exists) we should think through options. Options include ERROR, default to the user running restore, explicitly defined default, etc.

**Comment by kittydoor** [comment]
For my usecase, a way to restore users first, and then restore individual databases with ownership and grants preserved (with errors if something goes wrong) would be the best option. I can imagine there are different usecases too though.

**Comment by pbardea** [comment]
With respect to the `SHOW BACKUP` changes, I think adding another column behind the `WITH PRIVILEGES` option makes the most sense to me.
