### ISSUE TITLE
ui: invalid duration for successful jobs

### ISSUE THREAD

**Issue by dhartunian** [cockroachdb/cockroach#57903]
Jobs page in the UI has a bug where the duration for Successful jobs is displayed `aN:aN:aN`

![Screen Shot 2020-12-14 at 11 48 39 AM](https://user-images.githubusercontent.com/986307/102109742-6200ac00-3e02-11eb-9e5a-17867a812c6d.png)

gz#7027

Epic CRDB-8313

**Comment by elkmaster** [comment]
@dhartunian, did you saw this problem lately? I couldn't recreate it in any relevant release (20.2, 21.1, 21.2).
