### ISSUE TITLE
sql: notable (structured) event missing for ALTER TABLE OWNER TO 

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#57901]
Ownership changes to databases, schema and types are currently properly loggged with different event types.

However, table/view/sequence ownership changes are now logged at all. This is important to have a full security log.

cc @thtruo for triage.

(nb: PR #51987 might contain a fix for this)

**Comment by thtruo** [comment]
Ack - thanks for the heads up @knz. In your original comment, do you mean to say that ownership changes are _not_ logged currently? Will keep an eye on PR #51987 to see if the new PRIVILEGES channel reports ownership changes

**Comment by knz** [comment]
databases, schemas and types _are_ logged currently.

Tables/views/sequences are the odd ones missing an event.

**Comment by knz** [comment]
This has been fixed already.
