### ISSUE TITLE
opt: should restrict aggregates in with recursive

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#57946]
From Postgres' test suite:

```
WITH RECURSIVE x(n) AS (SELECT 1 UNION ALL SELECT sum(n) FROM x)
  SELECT * FROM x;
ERROR:  aggregate functions are not allowed in a recursive query's recursive term
LINE 1: WITH RECURSIVE x(n) AS (SELECT 1 UNION ALL SELECT sum(n) FRO...
```

We serve this query no problem. I'm not sure if this is a real problem or not but we might as well not serve such a ridiculous query?

**Comment by RaduBerinde** [comment]
I don't really understand the restriction. Why not allow aggregations? It seems pretty arbitrary, if I had to guess it's a consequence of internal pg details. This example is silly but I bet you could come up with reasonable uses (especially if you GROUP BY something).

**Comment by jordanlewis** [comment]
I think you're right
