### ISSUE TITLE
sql: ALTER VIEW/SEQUENCE .. OWNER TO is not implemented

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#57965]
This is implemented in postgres.

Also, postgres allows using `ALTER TABLE ... OWNER TO` to change the ownership of a view or sequence -- it's not restricted to tables. In CockroachDB, this currently produces an error.

**Comment by knz** [comment]
cc @piyush-singh @vy-ton @solongordon for triage

**Comment by knz** [comment]
Also obviously this is also missing structured event logging. cc @thtruo

**Comment by knz** [comment]
FWIW this does not have an immediate security impact, but we may want to prioritize this for the sake of consistent UX.

**Comment by solongordon** [comment]
Thanks @knz, looks like it could be a good "welcome back" starter project for @RichardJCai next week.
