### ISSUE TITLE
log: suppressing logs with -logtostderr=false no longer works in benchmarks

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#57979]
As of #57134 passing `-logtostderr=false` as a TESTFLAG in benchmarks errs: `flag provided but not defined: -logtostderr`. This flag was useful for suppressing logs from stdout (I'm confused why the flag was named `-logtostderr`) while running benchmarks so that only the benchmark output was written.

cc @knz

**Comment by knz** [comment]
Hi Marcus,

the "new normal" is to have `defer log.Scope(t).Close(t)` at the top of your test/benchmark.

This will remove the output by default

and then you can enable it explicitly with `-show-logs` instead.

Would that work for you?

**Comment by mgartner** [comment]
Thank you, @knz. This works well for [one offending benchmark](https://github.com/cockroachdb/cockroach/blob/f62055c1239a8c101b26565828649c6d00e53043/pkg/sql/opt/bench/bench_test.go#L321), but causes the errors below for [another noisy benchmark](https://github.com/cockroachdb/cockroach/blob/f62055c1239a8c101b26565828649c6d00e53043/pkg/sql/opt/bench/fk_test.go#L55). Let me know if you have any ideas.

```
E210106 23:45:35.256367 1683 kv/kvclient/kvcoord/txn_interceptor_committer.go:449  making txn commit explicit failed for "sql txn" meta={id=675c53d8 pri=0.00032736 epo=0 ts=1609976735.255694000,0 min=1609976735.255694000,0 seq=3} lock=true stat=STAGING rts=1609976735.255694000,0 wto=false max=1609976735.255694000,0 int=1 ifw=1: result is ambiguous (server shutdown)
E210106 23:51:21.558998 3866 kv/kvserver/queue.go:1087  [n1,raftlog,s1,r36/1:/Table/52{-/2}] failed to send RPC: sending to all replicas failed; last error: node unavailable; try
 another peer
```

**Comment by knz** [comment]
I don't understand your feedback. None of the two links you give use `log.Scope`. What am I supposed to see?

**Comment by mgartner** [comment]
I was just pointing to two benchmarks, one where your suggestion worked, and one were it made the benchmark err. I didn't include the changes because they are trivial, but here they are: https://github.com/mgartner/cockroach/commit/cc79b39d361fe44e6feaacc17004c672956432c5

The benchmark in `pkg/sql/opt/bench/fk_test.go` is the problematic one. It's not obvious to me what sets this benchmark apart from the other such that this log suppression would cause issues.

**Comment by knz** [comment]
Are you sure that the test/benchmark fails? Is it possible that you see error messages but they are otherwise innocuous?

**Comment by mgartner** [comment]
Ah, thanks for pointing this out. I see now that [TestLogScope does not suppress errors](https://github.com/cockroachdb/cockroach/blob/c8873836399f5d63ff2f3d19f5970377cf3d2295/pkg/util/log/test_log_scope.go#L151-L153). I'm fine with them being written to stderr, but when I run either `go test ./pkg/sql/opt/bench -bench='BenchmarkFKInsert'` or `make bench PKG='./pkg/sql/opt/bench' BENCHES='BenchmarkFKInsert'` they appear to wind up in stdout.

**Comment by knz** [comment]
The benchstat tool ignores output that doesn't have the right format, if that matters?

**Comment by mgartner** [comment]
Yes this is a gift, but also a curse in this case because the error logs can be inserted in the middle of a single benchmark's output:

```
BenchmarkFKInsert/SingleRow/None-16    	E210108 23:57:15.355266 3867 kv/kvserver/queue.go:1087  [n1,raftlog,s1,r36/1:/Table/52{-/2}] failed to send RPC: sending to all replicas failed; last error: node unavailable; try another peer
E210108 23:57:15.355424 3878 kv/kvclient/kvcoord/txn_interceptor_committer.go:449  making txn commit explicit failed for "sql txn" meta={id=38e08a84 pri=0.00300999 epo=0 ts=1610150235.354656000,0 min=1610150235.354656000,0 seq=3} lock=true stat=STAGING rts=1610150235.354656000,0 wto=false max=1610150235.354656000,0 int=1 ifw=1: result is ambiguous (server shutdown)
E210108 23:57:16.697765 17640 kv/kvclient/kvcoord/txn_interceptor_committer.go:449  making txn commit explicit failed for "sql txn" meta={id=77aa1554 pri=0.03519105 epo=0 ts=1610150236.697104000,0 min=1610150236.697104000,0 seq=3} lock=true stat=STAGING rts=1610150236.697104000,0 wto=false max=1610150236.697104000,0 int=1 ifw=1: result is ambiguous (server shutdown)
    2961	    407311 ns/op
```

When you run `benchstat` on a file with these lines, it ignores the benchmark.

Would you be open to me adding a function in `test_log_scope.go` similar to `ScopeWithoutShowLogs` but that suppresses error-level logs? Something like `ScopeWithoutShowAndErrorLogs`? I'm open to any other suggestions, if you have them.

**Comment by knz** [comment]
I think you have a compelling case to ensure log scopes don't report anything on ardour, not even errors.

**Comment by knz** [comment]
On stdout I mean damn autocorrect

**Comment by irfansharif** [comment]
> the "new normal" is to have defer log.Scope(t).Close(t) at the top of your test/benchmark.

Would it perhaps make sense to lint against benchmarks/tests that don't have this already? Is there a reason we wouldn't always want to have this behaviour?

**Comment by knz** [comment]
>  Is there a reason we wouldn't always want to have this behaviour?

I'd argue we only need it for tests that run a server. The amount of logging otherwise is too small.

But I agree on a linter. That makes sense. Can you suggests what rule could help us detect when we need it?

**Comment by mgartner** [comment]
> I think you have a compelling case to ensure log scopes don't report anything on stdout, not even errors.

I'm confused why the line in `test_log_scope` `cfg.Sinks.Stderr.Filter = severity.ERROR` configures errors to be reported on `stdout`. Is this intended despite the name of the field `Stderr`?

**Comment by knz** [comment]
What you are observing is the usual brain damage by the developers of the go team. Another complete mess in `go test` where someone very ~arrogant~ clever thought it would help the user to redirect stderr writes by tests to stdout.

**Comment by irfansharif** [comment]
> Can you suggests what rule could help us detect when we need it?

I was thinking something similar to our linters that check for `defer leaktest.AfterTest(t)()`, but maybe that's all overkill. Perhaps if we have enough of these, we could wrap it all within some other helper and lint against that being used instead.

**Comment by knz** [comment]
I asked around and there is a technical solution for this

![image](https://user-images.githubusercontent.com/642886/104631526-a6e75f00-569c-11eb-915a-1e70147f77cd.png)

So we can change `log.Scope` to completely kill the logging output within a benchmarking context. while keeping it active otherwise.
