### ISSUE TITLE
sql: finagle-postgres (scala) explodes when querying timestamp column

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5797]
See https://github.com/tschottdorf/pgexample for the example.
Not clear to me whether this is a bug on our or their end.

tl;dr:

```
// select * from system.lease;
[error] (run-main-0) java.lang.IllegalArgumentException: Timestamp format must be yyyy-mm-dd hh:mm:ss[.fffffffff]
java.lang.IllegalArgumentException: Timestamp format must be yyyy-mm-dd hh:mm:ss[.fffffffff]
```

**Comment by petermattis** [comment]
I wonder if it is asking for a date style we don't support. Currently we
only support ISO. Adding other date formats would be easy if this is the
problem.

**Comment by tschottdorf** [comment]
Here's another thing I'm not sure is ours or theirs (simply replace contents of `pgtest.scala` and run both options)

```
import scala.concurrent._
import scala.concurrent.duration._

//import com.twitter.conversions.time._
//import com.twitter.util.Awaitable._
import com.twitter.finagle.postgres._;
import com.twitter.finagle.postgres.codec.ServerError

object PGExample {
  def main(args: Array[String]) = {
    val client = Client("localhost:26257", "root", null, "bank")
    println("running")
    val brokenUpdate = "UPDATE stuffthaterrorsout SET nofield = 123"
    // Works (i.e returns with an exception):
    // val fut = client.executeUpdate(brokenUpdate)
    // Does not work (gets stuck forever):
    val fut = client.prepareAndExecute(brokenUpdate)

    val res = fut.get()
    println("never getting here")
  }
}
```

Hard to say without knowing what goes over the wire. I also don't know scala.

**Comment by tschottdorf** [comment]
or just check out https://github.com/tschottdorf/pgexample/commits/future_fail

**Comment by tschottdorf** [comment]
Edit: happens against postgres as well. I think this is a bug in the client. Ditto for the last post.

And one more, https://github.com/tschottdorf/pgexample/commits/fail_savepoint

Essentially, adding `SAVEPOINT cockroach_restart` (after `BEGIN`) into the bank example query throws

```
[error] (run-main-0) com.twitter.finagle.ChannelWriteException: com.twitter.finagle.UnknownChannelException: Unknown event com.twitter.finagle.postgres.messages.Sync$@32f0b05e for state ExecutePreparedStatement at remote address: localhost/127.0.0.1:26257 from service: client
com.twitter.finagle.ChannelWriteException: com.twitter.finagle.UnknownChannelException: Unknown event com.twitter.finagle.postgres.messages.Sync$@32f0b05e for state ExecutePreparedStatement at remote address: localhost/127.0.0.1:26257 from service: client
```

**Comment by dt** [comment]
@tschottdorf the getting stuck forever you're seeing is them not sending Sync requests in extended mode and thus server not flushing. My recent change to always flush errors might help, but certainly a big on their side -- the spec says they must send a sync if they want a reply.

**Comment by tschottdorf** [comment]
OK. Can you find upstream? Also pr'ing the fixes from our fork would be
good.

On Thu, Apr 7, 2016, 14:08 David Taylor <notifications@github.com> wrote:

> @tschottdorf <https://github.com/tschottdorf> the getting stuck forever
> you're seeing is them not sending Sync requests in extended mode and thus
> server not flushing. My recent change to always flush errors might help,
> but certainly a big on their side -- the spec says they must send a sync if
> they want a reply.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/5797#issuecomment-206840594>
>
-- 

-- Tobias

**Comment by tschottdorf** [comment]
*file

On Thu, Apr 7, 2016, 14:12 Tobias Schottdorf <tobias@cockroachlabs.com>
wrote:

> OK. Can you find upstream? Also pr'ing the fixes from our fork would be
> good.
>
> On Thu, Apr 7, 2016, 14:08 David Taylor <notifications@github.com> wrote:
>
>> @tschottdorf <https://github.com/tschottdorf> the getting stuck forever
>> you're seeing is them not sending Sync requests in extended mode and thus
>> server not flushing. My recent change to always flush errors might help,
>> but certainly a big on their side -- the spec says they must send a sync if
>> they want a reply.
>>
>> —
>> You are receiving this because you were mentioned.
>>
>>
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cockroachdb/cockroach/issues/5797#issuecomment-206840594>
>>
> --
>
> -- Tobias
>
-- 

-- Tobias

**Comment by dt** [comment]
I didn't isolate the sync thing yet, but as far as fixes https://github.com/finagle/finagle-postgres/pulls

**Comment by tschottdorf** [comment]
Cool. Though that unmerged year old PR lowers my expectations.

On Thu, Apr 7, 2016, 14:16 David Taylor <notifications@github.com> wrote:

> I didn't isolate the sync thing yet, but as far as fixes
> https://github.com/finagle/finagle-postgres/pulls
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/5797#issuecomment-206845769>
>
-- 

-- Tobias
