### ISSUE TITLE
Password login for a secure cluster.

### ISSUE THREAD

**Issue by leomkkwan** [cockroachdb/cockroach#58002]
On 20.1, I am able to login by using password; however, when I upgrade to v20.2, I go the following error

root@cockroach-01:/cockroach# ./cockroach sql -u leo
ERROR: cannot load certificates.
Check your certificate settings, set --certs-dir, or use --insecure for insecure clusters.

problem using security settings: no certificates found; does certs dir exist?
Failed running "sql"

This is not the expected behavior described on this page

https://www.cockroachlabs.com/docs/v20.2/cluster-setup-troubleshooting.html

``While connecting to a secure cluster as a user, CockroachDB first checks if the client certificate exists in the cert directory. If the client certificate doesn’t exist, it prompts for a password.``

**Comment by knz** [comment]
Hi @leomkkwan sorry for the very late answer.

To make this work, you need to provide a connection URL, for example `cockroach sql --url postgres://leo@localhost:26257`

Can you check this and see if your situation improves?

**Comment by leomkkwan** [comment]
Hi,

I treid again on v20.2.4, same message. The problem is if I did not provide the cert. dir, is that suppose to give me a password prompt? As that's described in the doc. 

````
root@cockroach-01:/cockroach# ./cockroach sql --url postgres://leo@localhost:262657
ERROR: cannot load certificates.
Check your certificate settings, set --certs-dir, or use --insecure for insecure clusters.

problem using security settings: no certificates found; does certs dir exist?
Failed running "sql"
root@cockroach-01:/cockroach#

**Comment by knz** [comment]
Sorry my example above was incomplete, you still need to decide in the URL whether you want to use TLS or not, and how.

You have 4 choices:

- `?sslmode=disable`  - no TLS
- `?sslmode=require`  - establish TLS transport, no server authentication, password-based client authentication
- `?sslmode=verify-ca&sslrootcert=path/to/ca.crt` (or `verify-full`) - establish TLS transport, verify server identity via CA or cert, password-based client authentication
- `?sslmode=verify-ca&sslrootcert=...&sslcert=...&sslkey=...` (or `verify-full`) - establish TLS transport, verify server identity, identify client using TLS client certificate

(This is explained in our docs)

So the first question is whether your server uses TLS or not; 2nd question is whether you want to verify the server identity or not; then you have a URL to test.

**Comment by leomkkwan** [comment]
Thanks you so much for the clearificaition! It's working now.
