### ISSUE TITLE
build: introduce mechanism to implant generated code from the bazel sandbox back into the source tree

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#58018]
For bazel generated files, especially pb.go ones once we make that happen (#56067), we’ll want a way for it to exist outside the sandbox and in the source tree. The reason being that IDEs would want to know where certain definitions exist, and it’s difficult to reach individual IDEs/editors to look within the sandbox. (Related: https://github.com/bazelbuild/rules_go/issues/512)

See https://github.com/dropbox/dbx_build_tools, the folks over at dropbox have a way to explicitly pull out bazel generated files out of the sandbox and into the working directory for what I think is this exact reason.

Epic CRDB-8036

**Comment by irfansharif** [comment]
I believe this mechanism should be folded into https://github.com/cockroachdb/cockroach/pull/56965.

**Comment by rickystewart** [comment]
quoth irfan who poked at this during breather week:

this is too difficult so I’ll give up. the basic version through dev where it searches through bazel to find all generated pb.go files is easy enough, but I don’t think it’s the right approach. It doesn’t take advantage of any sort of lazy evaluation (“don’t copy any files if nothing’s changed”), and to generate the proto files, we’d basically have to re-build the entire source tree (there’s no easy way to bazel build a go_proto_library target).
I think the right approach would be adding a rule, that can depend on go_proto_library targets, use the [rules api](https://github.com/bazelbuild/examples/tree/master/rules) to determine the right dependencies, run the specific GoProtocGen action to generate the right go_generated_src file, and copy that over in the right path. when expressed as a rule that depends on bazel targets, we’d get the right kind of lazy evaluation and transitive ordering.

**Comment by irfansharif** [comment]
Some relevant links: https://github.com/bazelbuild/rules_go/issues/2111, https://pkg.go.dev/golang.org/x/tools/go/packages?utm_source=godoc. I think the long-term strategy the bazel/rules_go folks are thinking about with `GOPACKAGESDRIVER` (https://github.com/bazelbuild/rules_go/issues/512, https://pkg.go.dev/golang.org/x/tools/go/packages?utm_source=godoc), though cool, is probably too much magic for me for the short-term. I also suspect the path to adoption for IDEs might be slow: https://youtrack.jetbrains.com/issue/GO-8753. I still think copying over the generated files (either in the dumb out-of-band manner, or in a smarter, rules-driven manner) is the way to go.

**Comment by irfansharif** [comment]
I haven't studied the https://github.com/dropbox/dbx_build_tools too closely. @otan or @AlexTalks, by any chance do you know where this "copy over generated files" code lives? Or know a friend who knows?

**Comment by otan** [comment]
gazel was done here: https://github.com/dropbox/dbx_build_tools/blob/master/build_tools/bzl_lib/gazel.py
and BUILD.bzl -> BUILD.bazel is done here: https://github.com/dropbox/dbx_build_tools/blob/master/build_tools/bzl_lib/gen_build_go.py#L75

note we didn't really allow go directives (e.g. `go:generate ...`), so we'll have to make our own story for that.

**Comment by rickystewart** [comment]
boom baby

**Comment by otan** [comment]
noiceee
