### ISSUE TITLE
logging,jobs: issue periodic events on the HEALTH channel about the fact jobs are being executed

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#58024]
The HEALTH channel is intended to report on resource usage and background tasks.

Today it contains a log message every 10 seconds to report on cpu/memory/disk IOPS.

We also would like it to report on the fact that jobs are ongoing on the background.

The information to convey is "N background tasks currently ongoing of the following types: A, B, C", possibly with job IDs. The specific progress on each job is less important (the user can then cross check with the job table to assess progress), what is important is to give the reader of log events an intuition that there exist background jobs that participate in overall CPU / memory / disk load.

Discussed with @ajwerner : there is presumably a callback invoked from the job runners to "update the progress field", where presumably one could add a suitable logging call (e.g. `log.Every()`). I could volunteer to solve this issue provided more specific code pointers.

Jira issue: CRDB-3447

**Comment by knz** [comment]
Note that we want these events to occur on every node that are currently performing work on behalf of jobs, not just  on the node that issued the job or is controlling it.

**Comment by knz** [comment]
Some notes by @dt 

> I don't think we should use job progress updates to trigger it, log.Every or not: we're moving towards jobs choosing when/how/where to persist their own execution state. However when a moves to a new life-cycle phase (e.g. runnable, paused, completed, etc), that is done in the central jobs place, and is in fact what might actually change the number being logged, so i'd probably do it there?
> that is Registry.stepThroughStateMachine
> that said, that might not get you every 10s, but for that matter, neither would progress. If you want the regular pings,  you'd want to jump in the adoption loop i think
> the adoption loop currently queries all jobs to see which to start running, stop running, etc
> i think you could sneak a count* in there
> do you want this per-node? if so, you actually already have in-memory the set of jobs this node is responsible for running (i.e. the "coordinator")  in the map
> i think in that case `len(registry.mu.adoptedJobs)` is "number of jobs for which i'm coordinator"
> some of those may be running, some may be failing, but if you just want jobs that are in some way active, that's your set
> so for purposes of "is this node doing work" i think anything in the map counts
> note: almost all jobs have a coordinator (that's in the map), but then also use distsql to ask other nodes to do work. Currently there's no visibility into the fact a node is doing work on behalf of a job being coordinated elsewhere

We probably need to investigate what's really needed, if we just want to count "this node is coordinating jobs" vs "this node is doing work towards jobs"

**Comment by dt** [comment]
this is old and we haven't heard more demand for it, compared to timeseries metrics which we did add and most operators now use. Closing for now but can re-open if/when we change our mind.
