### ISSUE TITLE
console: node rejoin events access undefined property

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#58026]
**Describe the problem**

The event log shown on the console home page does not render node rejoin events properly: "Node undefined rejoined the cluster".

**To Reproduce**

Start a cluster, restart a node. Or probably just starting is enough.

**Expected behavior**

**Additional data / screenshots**

**Environment:**
`master` at time of writing

**Additional context**

**Comment by knz** [comment]
This was discussed with @bdarnell  - as part of the eventlog modernization project, certain field names have been changed (and their semantics too).

I have modified the code in `events.tsx` to recognize the _new_ events, but that means that the code is unable to understand the fields in the old events that were already stored.

Maybe we can make the tsx code recognize both field names side-by-side? However I don't know how to do that.

@dhartunian maybe you can advise?

**Comment by knz** [comment]
@thtruo that's for you to prioritize too

**Comment by thtruo** [comment]
I wasn't able to reproduce on v22.2, v22.1, and v21.2 so closing this issue in the meantime
