### ISSUE TITLE
rpc: intra-node latencies improperly maintained during partial network failures

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#58033]
**Describe the problem**

In https://github.com/cockroachlabs/support/issues/738 the user was testing partial network failures by dropping packets between two datacenters. They observed that our latency matrix page did not surface the fact that there was a partial network outage. Taking a (very cursory) look myself at the API powering these latencies, I think we're using:
https://github.com/cockroachdb/cockroach/blob/66f4f5da8a206914d4be678b406d69a8177b670c/pkg/server/status/recorder.go#L369-L373

We're sampling from the last set of recorded latencies, populated here: https://github.com/cockroachdb/cockroach/blob/66f4f5da8a206914d4be678b406d69a8177b670c/pkg/rpc/clock_offset.go#L129-L141

Looking through the two callers, it seems we're only updating these recordings on successful ping requests (both on the caller and the receiver). 
https://github.com/cockroachdb/cockroach/blob/66f4f5da8a206914d4be678b406d69a8177b670c/pkg/rpc/context.go#L1205 
https://github.com/cockroachdb/cockroach/blob/66f4f5da8a206914d4be678b406d69a8177b670c/pkg/rpc/heartbeat.go#L167

That doesn't sound right. I think doing it the way we're currently doing it would surface the last know intra-node latency and mask the ongoing network breakdown.

**To Reproduce**

See above.

**Expected behavior**

The network latency matrix would show what nodes can no longer speak to one another.

+cc @piyush-singh for triage.

Jira issue: CRDB-3444

Epic CRDB-21710

**Comment by dhartunian** [comment]
Thanks for the investigation @irfansharif. The UI code has some functions that are supposed to incorporate the Liveness status of the nodes to mark them as "unavailable".

https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/src/views/reports/containers/network/index.tsx#L304-L309

Currently that appears to use `LivenessStatus.NODE_STATUS_UNAVAILABLE`. Maybe that's what requires revision.

**Comment by tbg** [comment]
The entire measuring of these latencies is pretty confused. The measurements ultimately come from the rpc heartbeat goroutine, but all of the "metrics" are buried in the clock offset monitor here

https://github.com/cockroachdb/cockroach/blob/295689b2d2202141da2d17a7dfb53a45bc6e8af1/pkg/rpc/context.go#L1281-L1294

and that is only ever reached by successful requests. I think we can significantly dumb this down - the offset monitor should do its offset monitoring but otherwise not be in charge of anything related to metrics, i.e. in particular we lift this histogram out of it:

https://github.com/cockroachdb/cockroach/blob/8b8bdb509c984e6030afd29fada4f06905783825/pkg/rpc/clock_offset.go#L176

**Comment by koorosh** [comment]
Network Latency page relies on following APIs:
- `NodeLiveness.GetLivenessesFromKV` to get nodes statuses. It indicates whether node is unavailable or not. It means that Latency matrix will show only cases when node cannot be reached from any other nodes. Current implementation doesn't allow to show network partition between two particular nodes.
- `systemStatusServer.NodesUI` that calls `getNodeStatuses` which in turn scans `node-` key space to get node statuses.

Additionally, Network latency page refreshes statuses rarely enough (every 10 minutes) so temporary network partitions cannot be observed here.

It looks like here's several issues that can be treated separately:
- Buggy behaivor of Network Latency page in Db Console. Revise APIs it uses to fetch nodes connectivity with each other and source of truth for latency metric;
- Proper measuring latencies mentioned by @tbg (https://github.com/cockroachdb/cockroach/issues/58033#issuecomment-935692884)
- track historical data of inter-node latencies (https://github.com/cockroachdb/cockroach/issues/71193);

**Comment by koorosh** [comment]
Following PR https://github.com/cockroachdb/cockroach/pull/99191 includes major improvements on tracking
latencies between nodes (per peer connection) that also resolve current issue.
Suggesting to close this issue as fixed.
