### ISSUE TITLE
sql: renamed or dropped column remains visible to introspection commands in the same transaction

### ISSUE THREAD

**Issue by jayshrivastava** [cockroachdb/cockroach#58067]
**Describe the problem**

It is possible to drop/rename a column in a transaction and have it remain visible.
**To Reproduce**

```
root@localhost:26257/defaultdb> begin;

root@localhost:26257/defaultdb  OPEN> create index idx on t (i asc);

root@localhost:26257/defaultdb  OPEN> alter table t rename column i to j;

root@localhost:26257/defaultdb  OPEN> show columns from t;
  column_name | data_type | is_nullable | column_default | generation_expression |  indices  | is_hidden
--------------+-----------+-------------+----------------+-----------------------+-----------+------------
  j           | INT8      |    true     | NULL           |                       | {}        |   false
  rowid       | INT8      |    false    | unique_rowid() |                       | {primary} |   true

root@localhost:26257/defaultdb  OPEN> alter table t rename column j to i;

root@localhost:26257/defaultdb  OPEN> show columns from t;
  column_name | data_type | is_nullable | column_default | generation_expression |  indices  | is_hidden
--------------+-----------+-------------+----------------+-----------------------+-----------+------------
  j           | INT8      |    true     | NULL           |                       | {}        |   false
  rowid       | INT8      |    false    | unique_rowid() |                       | {primary} |   true

root@localhost:26257/defaultdb  OPEN> commit;

```

**Expected behavior**
Upon renaming the column from `j` back to `i`, the column `j` should not be visible. 

**Additional Info**
This problem showed up in [this](https://github.com/cockroachdb/cockroach/issues/56230#issuecomment-745129333) schemachange roachtest failure.

**Comment by jordanlewis** [comment]
@jayshrivastava, you've verified that this is only the case for introspection commands, right? We'd expect that SQL (e.g. an `INSERT`) that references `j` would fail and SQL that references `i` would fail.

**Comment by jayshrivastava** [comment]
@jordanlewis Yes it's for introspection only. After renaming to `i`, an insert referencing `j` will fail, and an insert referencing `i` will succeed.

**Comment by postamar** [comment]
I tried to repro and the column correctly shows up as `i` in the output of the second `show columns` statement, so I'll tentatively close this issue.
