### ISSUE TITLE
workload/schemachange: handle rollback to savepoint after transaction restart

### ISSUE THREAD

**Issue by jayshrivastava** [cockroachdb/cockroach#58068]
**Describe the problem**

If there is a retry error on statement execution, the default behaviour of the workload is to rollback the transaction. However, if there are any savepoints in the transaction (which might occur due to op generation failures), then
we observe a `ERROR: restart transaction: TransactionRetryWithProtoRefreshError: cannot rollback to savepoint after a transaction restart (SQLSTATE 40001)`.

**Expected behavior**
The workload can expect this error by keeping track of if savepoints have been set in the txn so that it does not fail due to an unexpected error. Alternatively, we can add some logic to create a new txn instead of rolling back when retry errors are seen. 

**Additional Notes**
This issue was observed in these roachtest failures: 
- https://github.com/cockroachdb/cockroach/issues/56230#issuecomment-747934710
- https://github.com/cockroachdb/cockroach/issues/56235#issuecomment-748465031
- https://github.com/cockroachdb/cockroach/issues/56235#issuecomment-748597815

**Comment by ajwerner** [comment]
This behavior has been removed.
