### ISSUE TITLE
sql: test and support Rust sqlx library

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#58074]
**Is your feature request related to a problem? Please describe.**
https://github.com/launchbadge/sqlx
This is a Rust tool that a user requested in https://github.com/cockroachdb/cockroach/issues/57411

I was able to run the tests with:
```
cargo test --tests --all-targets --features 'runtime-async-std-rustls,postgres,macros'
```

Note that by default, it stops running other test files as soon as one test file does not work.

**Describe the solution you'd like**
Run the test in our nightly test suite.

If it works well, then document support for it.

Jira issue: CRDB-61090

**Comment by dvtkrlbs** [comment]
Are there any updates on this. I can't use sqlx macros feature at all it just gives me an error saying `error: error returned from database: at or near "json": syntax error`.

**Comment by kernfeld-cockroach** [comment]
Hi @dvtkrlbs, thanks for checking in. We still don't have full sqlx support but last week I was actually working with some people who got a sqlx prototype running with CockroachDB. Would you mind filing a separate GitHub issue that includes steps we can take to reproduce your problem? It might be possible to fix your issue even if we don't have full support for sqlx.
