### ISSUE TITLE
Alert user to failed sink credentials for changefeeds

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#58077]
See in screenshot - when a user creates a changefeed into an S3 bucket with wrong credentials, there is no alert to let the user know that the changefeed could not connect to the sink. We should check to make sure that the changefeed job isn't running, and alert the user that their credentials were wrong and they should try again.

<img width="667" alt="Screen Shot 2020-12-18 at 1 29 43 PM" src="https://user-images.githubusercontent.com/13264141/102653813-254ff000-4135-11eb-9fbf-fe29241e4577.png">

Jira issue: CRDB-3435

**Comment by miretskiy** [comment]
Closing as a dup of [#60178](https://github.com/cockroachdb/cockroach/issues/60178)
