### ISSUE TITLE
sql/catalog: store descriptors for prefix inside descriptors

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#58073]
**Is your feature request related to a problem? Please describe.**

Every time we resolve a descriptor, we end up resolving its parent. It's a shame to need to re-resolve and it makes things like serializing a fully qualified name pretty awful. Objects (types, tables) should hold on to their parent schema and database. Schemas should hold onto their parent database.

Epic: CRDB-2454

Jira issue: CRDB-3437

**Comment by jordanlewis** [comment]
Maybe a @postamar thing?

**Comment by ajwerner** [comment]
Yes, probably. There's some nuance on how exactly to get the construction correct in all of the places.

**Comment by postamar** [comment]
Is this still relevant? Looking up the parent by ID in the descriptors collection should cost next to nothing and I'd rather not have to deal with problems related to different descriptor versions if I can avoid it.

**Comment by ajwerner** [comment]
Fair enough. This is certainly speculative. I sort of see it both ways. Namely, if we generalize hydration to deal with composing related descriptors and always having them handy, then we could extend that concept here. I think there's something to it. It's often awkward to need to go get a fully qualified name when you've got a table or type descriptor.

**Comment by ajwerner** [comment]
I suspect this story will matter less when there's so much less imperative code related to descriptors

**Comment by ajwerner** [comment]
This is too speculative to be useful, closing.
