### ISSUE TITLE
Precision of timestamptz(6) falls off in case it's zero

### ISSUE THREAD

**Issue by Freeaqingme** [cockroachdb/cockroach#58095]
**Describe the problem**

I have a column defined as TIMESTAMPTZ(6) NOT NULL. This works fine. However, if an event happened at 00:00:00.000000 the precision is left out, and it's reduced to 00:00:00.

**To Reproduce**

```
> update user_account set deleted_at = '3000-01-01 00:00:00.000001Z';
> select deleted_at from user_account;
  3000-01-01 00:00:00.000001+00:00

> update user_account set deleted_at = '3000-01-01 00:00:00.000000Z';
> select deleted_at from user_account;
  3000-01-01 00:00:00+00:00
```

**Expected behavior**
In the second query, I'd expect to see:
```
> update user_account set deleted_at = '3000-01-01 00:00:00.000000Z';
> select deleted_at from user_account;
  3000-01-01 00:00:00.000000+00:00
```

**Environment:**
CRDB CCL v20.2.0 @ 2020/11/09 16:01:45 (go1.13.14)

**Additional context**
This is a problem because when trying to parse the datetime format, I need to specify the format it is in (in PHP). I specify:
```PHP
<?php
// Parses fine
$dateTime = DateTimeImmutable::createFromFormat('Y-m-d H:i:s.uO',  '3000-01-01 00:00:00.000000+00:00');

// Doesn't parse, $dateTime is false
$dateTime = DateTimeImmutable::createFromFormat('Y-m-d H:i:s.uO',  '3000-01-01 00:00:00+00:00');

// Does parse, because of a different format string
$dateTime = DateTimeImmutable::createFromFormat('Y-m-d H:i:sO',  '3000-01-01 00:00:00+00:00');
```

Of course, one could just build in some kind of if statement. However, frameworks like Doctrine ORM (#19337) associate a single format with a single timestamp type, which does make sense to me.

From a more theoretical point of view it's also a bit problematic. I.e. 1E6 is different from 1.000.000, because the latter is way more significant.

**Comment by rafiss** [comment]
@Freeaqingme Thank you for creating this issue!

I'm not sure if we will change the behavior here, since we want to try to keep timestamp formatting as close to PostgreSQL as we can. When I run the following in PostgreSQL, I see behavior that matches what you describe:

```
rafiss@127:postgres> create table ts(a timestamptz(6) not null);
CREATE TABLE

rafiss@127:postgres> insert into ts values ('3000-01-01 00:00:00.000001Z'), ('3000-01-01 00:00:00.000000Z')
INSERT 0 2

rafiss@127:postgres> select * from ts;
+-------------------------------+
| a                             |
|-------------------------------|
| 3000-01-01 00:00:00.000001+00 |
| 3000-01-01 00:00:00+00        |
+-------------------------------+
SELECT 2
```

I agree with you that this isn't necessarily the most intuitive, but I would be concerned with negatively affecting other tools/libraries if we change this.

Does your program work with PostgreSQL?

**Comment by Freeaqingme** [comment]
@rafiss thanks for taking a look, especially during the weekend :)

I realize many things are modeled after postgres. However, I'm writing a custom app, and basing that off CRDB. So I couldn't tell you if I got the same behavior on Postgres. But I'll happily take it for granted based on your snippet.

Having said that, of course some differences do exist between the two. In this case, I'd argue it could be worth considering to change the behavior here a little (I'm inclined to consider it a bug in Postgres). I find it hard to imagine that there'd be actual breakage - but that's no more than a hypothesis.

**Comment by rafiss** [comment]
@Freeaqingme Sorry for taking a while to get back to you. I've discussed this with the team, and this isn't an area where we will diverge from PG.

Though after re-reading your issue, I'm not sure why you need to call `DateTimeImmutable::createFromFormat()`. Doesn't that mean you are turning a string into a DateTime? You should already be getting back a DateTime object from CockroachDB. If not, then that would need to be fixed at the level of the PHP driver.

**Comment by otan** [comment]
I'm closing this due to time. If it is a problem, please feel free to comment.
