### ISSUE TITLE
ui: statement diagnostic icon broken

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#58109]
CockroachDB sha: 75efa1f

<img width="1576" alt="Screen Shot 2020-12-20 at 11 50 45 AM" src="https://user-images.githubusercontent.com/5438456/102723389-8a424c00-42d5-11eb-9cf4-4e37d8da835e.png">

**Comment by piyush-singh** [comment]
cc @dhartunian

**Comment by thtruo** [comment]
cc @dhartunian @nkodali . Tracking internally https://cockroachlabs.atlassian.net/browse/CC-3358 and worth triaging when we come back after New Years.

**Comment by koorosh** [comment]
Duplicate issue https://github.com/cockroachdb/cockroach/issues/57698
and it's fixed with PR: https://github.com/cockroachdb/cockroach/pull/57776
