### ISSUE TITLE
ui: app name filter on transactions page works differently than on statements page

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#58108]
CockroachDB sha: 75efa1f

On the statements page, the app name drop-down results in filtering on an exact match. On the transactions page, it results in a prefix match. These should be consistent, and ideally, both result in an exact match.

Jira issue: CRDB-3431

**Comment by thtruo** [comment]
Tangentially related, I noticed a weird filter name parsing behavior under Transactions 
![image](https://user-images.githubusercontent.com/1474303/102923788-5fcfca80-445e-11eb-94e7-d6449ddab835.png)

Tracking internally at https://cockroachlabs.atlassian.net/browse/CC-3359 cc @nkodali @dhartunian for triage

cc @taroface for awareness. Either https://www.cockroachlabs.com/docs/v20.2/ui-statements-page or https://www.cockroachlabs.com/docs/stable/ui-transactions-page.html would require copy changes when we standardize the filtering behavior.
