### ISSUE TITLE
ui: back button on transactions page works differently than on statements page

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#58107]
CockroachDB sha: 75efa1fe6f

Statements on the statement page link to a new URL. This allows users link to a specific statement and to use browser navigation to jump back to the statements page. This doesn't seem to be the case for the transactions page. Transactions don't have a stable URL and browser navigation is broken when looking at a specific transaction. The only way to jump back to the transaction list is it click the "All transactions" button.

Jira issue: CRDB-3432

**Comment by thtruo** [comment]
Looks like the _Transactions Page_ is the only page which doesn't provide stable URLs for specific transactions. This makes it inconsistent with Statements, Sessions, Databases, etc. 

We should standardize the behavior and ensure that a specific transaction detail gets its own URL like `localhost:8080/#/transactions/<transaction_id>`. This would also help make the browser back button experience less jarring for a user. 

cc @nkodali @dhartunian a good one to consider triaging when we return from break. Tracking internally here https://cockroachlabs.atlassian.net/browse/CC-3357
