### ISSUE TITLE
sql: DECIMAL not decoded properly on null internal bytes

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#5812]
From today's master:

```sql
create table b(x decimal);
insert into b values(1000000000::decimal);
update b set x = x + 0.0000000001::decimal;
select * from b;
+---------------------------+
|             x             |
+---------------------------+
| 0.00000000152587890625000 |
+---------------------------+
```

I would expect either the correct value (no rounding) or 1000000000 (funky rounding to float), definitely not the one observed.

**Comment by nvanbenschoten** [comment]
Fully expected (unfortunately :disappointed:). See https://github.com/cockroachdb/cockroach/issues/4026. Try the `DECIMAL '123.456'` syntax instead to cast from a string and avoid float truncation.

The good news is that it should be fixed by Morty!

**Comment by knz** [comment]
oshit I had totally forgotten that :(
Thanks!

**Comment by nvanbenschoten** [comment]
Actually, that addition seems strange. Let me investigate more.

**Comment by knz** [comment]
Indeed: 
```sql
insert into b values (decimal '1000000000');
update b set x = x + decimal '0.0000000001';
select * from b;
+---------------------------+
|             x             |
+---------------------------+
| 0.00000000152587890625000 |
+---------------------------+
```

**Comment by knz** [comment]
Worse yet:
```sql
create table b (x decimal);
insert into b values (decimal '1459540804256286309.0000000000');
select * from b;
+-------------------------------+
|               x               |
+-------------------------------+
| 0.000000001459540804256286309 |
+-------------------------------+
```

**Comment by JackKrupansky** [comment]
Does the final solution accept existing encodings correctly, or do people have to recreate their databases?

I mean, the pull request does say "this is a breaking change", but I was hoping that would not be the case. Please confirm.

Signed, The Guy Who Likes To Comment On Closed Issues.

**Comment by nvanbenschoten** [comment]
@JackKrupansky, unfortunately yes this is a breaking change and anyone using DECIMAL at this point will need to recreate their databases. This will all be discussed in the next (first?) batch of release notes.

**Comment by JackKrupansky** [comment]
Is it only DECIMAL that was broken? I vaguely recall discussion of wanting to encode float and decimal the same way, but then there was also discussion of encoding FLOAT as raw 64-bit int... so I just wanted to confirm. IOW, in which subset of cases the user will be forced to recreate their databases and for which cases they do not need to do so.

**Comment by nvanbenschoten** [comment]
The FLOAT and DECIMAL encodings diverged in https://github.com/cockroachdb/cockroach/pull/5337, which also introduced the issue that this PR just fixed. Users using FLOATs are fine, it's only users using DECIMAL that had a chance of being affected and therefore will need to recreate their databases.
