### ISSUE TITLE
bulkio: preserve database/table zone configs upon restore

### ISSUE THREAD

**Issue by mattcrdb** [cockroachdb/cockroach#58129]
Certain users have requirements for the locality of their data, today in order to restore a collection into a new cluster and have it respect the zone configurations for the original cluster, there is a manual step or pausing the restore job, restoring the system zones from the original cluster and then resuming the restore.

This process can increases compliance risk caused by human error and can be tricky when users are restoring their own customers data.

This is an enhancement request for preserving that information automatically and not requiring a manual process.

**Comment by dt** [comment]
I think this is covered in #48518 and #44990 ? feel free to reopen if you think it isn't covered by those though.
