### ISSUE TITLE
migration: utilize jobs for long-running migrations

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#58183]
Utilizing jobs for long-running migrations comes with benefits. Namely you can pause them. You get visibility into the fact that they are running. You also get other niceties that come with jobs like stats, the file to stop adoption, etc. This issue is a placeholder for work to update https://github.com/cockroachdb/cockroach/pull/57694 to utilize jobs for individual migrations.

**Comment by ajwerner** [comment]
The work to do this is on https://github.com/irfansharif/cockroach/pull/2. It skewed with the branch from which I did the refactor.

**Comment by tbg** [comment]
What's the next step here?

**Comment by ajwerner** [comment]
Circling back on this, I'm going to deal with the skew on master and make a PR.
