### ISSUE TITLE
OPT: suboptimal behavior of order by clause

### ISSUE THREAD

**Issue by xinyuliu12** [cockroachdb/cockroach#58216]
Hello everyone!

First off, I am sorry for gestures vaguely all of this. Second, I think we may have found a suboptimal behavior related to the order by clause.

Here is a pair of TPC-H queries that exhibit this behavior.

```
SELECT "supplier"."s_name", 
       "supplier"."s_nationkey", 
       "supplier"."s_address" 
FROM   "nation" 
       LEFT JOIN "supplier" 
              ON true 
ORDER  BY "supplier"."s_nationkey" ;

SELECT "t1"."s_name", 
       "t1"."s_nationkey", 
       "t1"."s_address" 
FROM   (SELECT "nation0"."n_nationkey", 
               "nation0"."n_name", 
               "nation0"."n_regionkey", 
               "nation0"."n_comment", 
               "supplier0"."s_suppkey", 
               "supplier0"."s_name", 
               "supplier0"."s_address", 
               "supplier0"."s_nationkey", 
               "supplier0"."s_phone", 
               "supplier0"."s_acctbal", 
               "supplier0"."s_comment" 
        FROM   "nation" AS "nation0" 
               LEFT JOIN "supplier" AS "supplier0" 
                      ON true 
        ORDER  BY "supplier0"."s_nationkey") AS "t1"; 


```

**Actual Behavior**
The first query takes 5 seconds on the v20.2.0-alpha.1, while the second query only takes 579 millisecond.
The first query's "EXPLAIN ANALYZE (DEBUG)" result is 
[stmt-bundle-firstquery.zip](https://github.com/cockroachdb/cockroach/files/5732275/stmt-bundle-firstquery.zip)

The second query's "EXPLAIN ANALYZE (DEBUG)" result is 
[stmt-bundle-secondquery.zip](https://github.com/cockroachdb/cockroach/files/5732276/stmt-bundle-secondquery.zip)

**Expected Behavior**
I would have expected the database system run these two queries within similar execution time. 
Based on their execution plans, it looks to me that the reason why the second query is much faster is because it does not perform the sort operation on the result of the cross join. It would be helpful if you could comment on why the DBMS does not perform the sort operation on the second query. Thank you!

Here are the steps for reproducing our observations:

**Test environment**

* Ubuntu 20.04 machine "Linux panda 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux"
* Cockroachdb v20.2.0-alpha.1
* Database: TPC-H benchmark (with scale factor 5)

**Reproduce Bug**

1. Install cockroachdb v20.2.0-alpha.1     

```
    $ mkdir -p $(go env GOPATH)/src/github.com/cockroachdb
    $ cd $(go env GOPATH)/src/github.com/cockroachdb
    $ git clone https://github.com/cockroachdb/cockroach
    $ cd cockroach
    $ git checkout eaa939c
    $ make build
    $ sudo make install
```

* start a cockroachdb node in your preferred working directory
```
    $ cockroach start --insecure --store=node1 --listen-addr=localhost:26257 --http-addr=localhost:8080 --join=localhost:26257,localhost:26258,localhost:26259 --background
    $ cockroach init --insecure --host=localhost:26257
```

2. Set up TPC-H test benchmark (if you already have a TPC-H benchmark set up, you can skip step2; starting from step2, all commands should run in the directory ./tpch5 after downloading and extracting it)

* Download TPC-H (scale factor of 5) and extract it
    Download the dataset from the link: https://drive.google.com/file/d/1MLVFPKdRQhlRgmeRIumyIj8NBMRSQ3um/view?usp=sharing
```
    $ tar xzvf tpch5_setup.tar.gz
    $ cd tpch5
    $ chmod +x setup.sh
```

* Create DB and TPC-H schema
`   $ cockroach sql --insecure --host=localhost:26257`    
    In CockroachDB's built-in SQL client to create database:
```
    $ create database tpch5;
    $ exit
```
* Create TPC-H Schema
   `    $ cockroach sql --insecure --host=localhost:26257 -d tpch5 < dss.ddl
`
* Set up benchmark
```  
    $ ./setup.sh
    $ cockroach sql --insecure --host=localhost:26257 -d tpch5 < dss.ri

```
3. Test SQL query that exhibits performance issue
* Execute the queries after logging to the testing benchmark using the following command
`    $ cockroach sql --insecure --host=localhost:26257 -d tpch5
`

**Comment by DrewKimball** [comment]
It looks like the `ORDER BY` clause in the second query only applies to the inner `SELECT` clause (look at the parentheses). This means the top-level `SELECT` is unordered. So really, they're different queries.

**Comment by xinyuliu12** [comment]
Thank you so much for your reply! 
The reason why I previously thought they should fetch the same result is because I assume that for the second query the top-level `SELECT` is asking to project columns from the derived table `t1` (which should be ordered).
I also tried to run both queries on the PostgreSQL and both queries return the same and ordered results.
Does this pair of queries makes a case for the dialect difference between these the CockroachDB and PostgreSQL? 
Thanks!

**Comment by DrewKimball** [comment]
To my knowledge, PostgreSQL doesn't guarantee that the ordering will be preserved in the outer query either - it just turns out that way in this case.

**Comment by xinyuliu12** [comment]
Thank you so much for your explanation!
