### ISSUE TITLE
storage/replica.go:1405 group 24 on store 1 failed to send message to 2: storage/raft_transport.go:292: queue for node 2 is full

### ISSUE THREAD

**Issue by ukd1** [cockroachdb/cockroach#5823]
## node 1
1. What version of CockroachDB are you using (`cockroach version`)?

Build Tag:   beta-20160331-38-gfd0f1cb
Build Time:  2016/04/01 08:41:18
Platform:    darwin amd64
Go Version:  go1.6
C Compiler:  4.2.1 Compatible Ubuntu Clang 3.7.0 (tags/RELEASE_370/final)

2. What operating system and processor architecture are you using?

os x, intel x86

3. What flags/environment variables did you pass to `cockroach start`?

```
./cockroach.darwin-amd64.fd0f1cbdca513522e2e4f7cf0d72887d38e3af33 start --store=/usr/local/var/cockroach --logtostderr --host 10.251.251.104 --insecure
```
## node 2
1. What version of CockroachDB are you using (`cockroach version`)?

Build Tag:   beta-20160331-38-gfd0f1cb
Build Time:  2016/04/01 08:31:45
Platform:    linux amd64
Go Version:  go1.6
C Compiler:  gcc 4.9.2

2. What operating system and processor architecture are you using?

linux, intel x86

3. What flags/environment variables did you pass to `cockroach start`?

```
./cockroach.fd0f1cbdca513522e2e4f7cf0d72887d38e3af33 start --host=10.251.251.100 --logtostderr --store=~/cockroach --join=10.251.251.104 --insecure
```
Please describe the issue you observed:

1. What did you do?

insert a bunch of things - 400 connections bluk loading stuff to a single node

2. What did you expect to see?

not that

3. What did you see instead?

> W160402 12:55:23.145146 storage/replica.go:1405 group 24 on store 1 failed to send message to 2: storage/raft_transport.go:292: queue for node 2 is full

repeatedly

**Comment by ukd1** [comment]
I'm also getting this doing things other than "bulk loading"

**Comment by tamird** [comment]
This is indicative of congestion on the outgoing raft queues, which is generally not harmful - those messages will be retried.

This may be significantly improved by #7534, so I'm going to close this for now. Please let me know if it should be reopened.
