### ISSUE TITLE
sql: accept units for CONFIGURE ZONE range_max_bytes and range_min_bytes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#5828]
The `range_max_bytes` and `range_min_bytes` fields in a zone config accept only straight bytes. It would be nice for them to accept other bytes-based units as well (MB, etc.), just as the `--cache` flag for `cockroach start` and other flags do.

**Comment by petermattis** [comment]
This is difficult given how we currently parse the input yaml directly into a `ZoneConfig` proto.

**Comment by jseldess** [comment]
@petermattis, reported this just as a nice-to-have, but it's very minor, so feel free to close if it's not likely to get attention.

**Comment by knz** [comment]
Now that this is handled at the level of SQL, we could have a SQL parser to do this in the CONFIGURE ZONE code.

**Comment by knz** [comment]
cc @jordanlewis for triage

**Comment by irfansharif** [comment]
I think it's unlikely we'll do much about this anytime soon. With MR, we're generally moving away from wanting to expose raw zone configs to users/tenants, in favor of MR abstractions. For more "raw usage", this seems ok as a UX annoyance.
