### ISSUE TITLE
colexec: suboptimal behavior related to unsupported vectorized cast

### ISSUE THREAD

**Issue by xinyuliu12** [cockroachdb/cockroach#58284]
Hello everyone!

First off, I am sorry for gestures vaguely all of this. Second, I think we may have found a suboptimal behavior related to an unsupported vectorized cast.

Here is a pair of TPC-H queries that exhibit this behavior.

```
SELECT "o_orderkey", 
       "o_orderpriority", 
       "o_orderdate", 
       "o_clerk", 
       Cast(' foxes. pending accounts at the pending, silent asymptot' AS VARCHAR) AS "o_comment" 
FROM   "orders" 
WHERE  "o_orderpriority" = '5-LOW          ' IS NOT true 
AND    "o_comment" = ' foxes. pending accounts at the pending, silent asymptot' FETCH next 19 rows only;

SELECT "o_orderkey", 
       "o_orderpriority", 
       "o_orderdate", 
       "o_clerk", 
       "o_comment" 
FROM   "orders" 
WHERE  "o_orderpriority" = '5-LOW          ' IS NOT true 
AND    "o_comment" = ' foxes. pending accounts at the pending, silent asymptot' FETCH next 19 rows only;
```

**Actual Behavior**
The first query takes 12.7 seconds on the v20.2.0-alpha.1, while the second query only takes 6.3 seconds.
The first query's `EXPLAIN ANALYZE (DEBUG)` result is 
[stmt-bundle-firstquery.zip](https://github.com/cockroachdb/cockroach/files/5744040/stmt-bundle-firstquery.zip)

The second query's `EXPLAIN ANALYZE (DEBUG)` result is 
[stmt-bundle-secondquery.zip](https://github.com/cockroachdb/cockroach/files/5744041/stmt-bundle-secondquery.zip)

**Expected Behavior**
I would have expected the database system run these two queries with similar execution time, given that they compute the same result tables. 
It looks to me that the first query executes slower is because that the DBMS falls back to row-execution engine due to a type mismatch: `expected [int char date char varchar]	actual [int char date char string] .` 
This behavior seems similar to another issue #57566, where exists another type mismatch: `expected [int char int char int decimal]	actual [int char int string int decimal]`

**Test environment**

* Ubuntu 20.04 machine "Linux panda 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux"
* Cockroachdb v20.2.0-alpha.1
* Database: TPC-H benchmark (with scale factor 5)

**Reproduce Bug**

1. Install cockroachdb v20.2.0-alpha.1     

```
    $ mkdir -p $(go env GOPATH)/src/github.com/cockroachdb
    $ cd $(go env GOPATH)/src/github.com/cockroachdb
    $ git clone https://github.com/cockroachdb/cockroach
    $ cd cockroach
    $ git checkout eaa939c
    $ make build
    $ sudo make install
```

* start a cockroachdb node in your preferred working directory
```
    $ cockroach start --insecure --store=node1 --listen-addr=localhost:26257 --http-addr=localhost:8080 --join=localhost:26257,localhost:26258,localhost:26259 --background
    $ cockroach init --insecure --host=localhost:26257
```

2. Set up TPC-H test benchmark (if you already have a TPC-H benchmark set up, you can skip step2; starting from step2, all commands should run in the directory ./tpch5 after downloading and extracting it)

* Download TPC-H (scale factor of 5) and extract it
    Download the dataset from the link: https://drive.google.com/file/d/1MLVFPKdRQhlRgmeRIumyIj8NBMRSQ3um/view?usp=sharing
```
    $ tar xzvf tpch5_setup.tar.gz
    $ cd tpch5
    $ chmod +x setup.sh
```

* Create DB and TPC-H schema
`   $ cockroach sql --insecure --host=localhost:26257`    
    In CockroachDB's built-in SQL client to create database:
```
    $ create database tpch5;
    $ exit
```
* Create TPC-H Schema
   `    $ cockroach sql --insecure --host=localhost:26257 -d tpch5 < dss.ddl
`
* Set up benchmark
```  
    $ ./setup.sh
    $ cockroach sql --insecure --host=localhost:26257 -d tpch5 < dss.ri

```
3. Test SQL query that exhibits performance issue
* Execute the queries after logging to the testing benchmark using the following command
`    $ cockroach sql --insecure --host=localhost:26257 -d tpch5
`

**Comment by yuzefovich** [comment]
Thanks for the report @xinyuliu12! I believe you are correct that the difference in the execution times is only because the row engine is used for the slow query and the vectorized engine is used for the faster one and that the vectorized engine couldn't be used for the former due to type mismatch problem you mentioned.

However, that issue has already been fixed on master branch, and backporting the fix is probably not worth it. I'd also encourage you to use later versions of CockroachDB when playing around with it (either the latest stable 20.2.x or the alpha for 21.1).
