### ISSUE TITLE
Allow multiple changefeed jobs to emit to the same topic

### ISSUE THREAD

**Issue by kevinkokomani** [cockroachdb/cockroach#58302]
**Is your feature request related to a problem? Please describe.**
Currently, when you [create a changefeed job](https://www.cockroachlabs.com/docs/v20.2/stream-data-out-of-cockroachdb-using-changefeeds.html#configure-a-changefeed-enterprise) for a table, the job will publish to a topic named after the table. If a database has N tables, you will need to create N Kafka topics, which can be an annoyance.

**Describe the solution you'd like**
Ideally, you would be able to tell multiple change feed jobs to emit to the same topic, so you can have one topic per database (and every change feed will emit to that database topic).

**Describe alternatives you've considered**
There don't appear to be any alternatives to the current flow.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[7116](https://cockroachdb.zendesk.com/agent/tickets/7116) has been linked to this issue.

**Comment by mwang1026** [comment]
I think we should be careful about implementing it as described. Do they have thoughts on how they might disambiguate data between tables? Does it need to be separate changefeeds to the same topic vs just one changefeed that writes to a single topic?

Long way of saying, we've had a number of requests lately about output formats (which is great!) but we should be mindful of thinking about the UX as a whole. Having some clarification about the above (as well as why it's less of an operational than having to parse different table data out from a single topic) would be helpful for prioritization and UX design.

**Comment by eliancss** [comment]
Hi, initially we don't have a specific preference on number of changefeeds, what is more important is reducing the number of topics, 1 per DB (or make it configurable) would be ideal.

Thank you!

**Comment by amruss** [comment]
Hi @eliancss could you give us more context into what output you're looking for here? 

Could this be solved by creating one changefeed job for all of the tables in your DB?

**Comment by eliancss** [comment]
Yes! @amruss as long as that job outputs to a single (the same) kafka topic. Currently we require 1 job per table (and that job needs a new topic too).

thanks!

**Comment by amruss** [comment]
Hi @eliancss you should be able to create a changefeed to one kafka topic across multiple tables by using a comma seperated list as the table_name parameter
