### ISSUE TITLE
build: `make bazel-generate` on the `master` branch generates a huge diff

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#58312]
I just checked out `master` today, and running `make bazel-generate` causes the following giant diff to appear:

https://gist.github.com/knz/af9d464f8b4d28eba01f4dcc14967634

A checkout from just two weeks ago did not have this problem.

**Comment by knz** [comment]
cc @rickystewart for tracking

**Comment by rickystewart** [comment]
I can trivially reproduce this. I can submit a PR to squash the diffs, but I wonder why this wasn't caught by CI.
