### ISSUE TITLE
pgwire: make it possible for a SQL proxy to report additional details about the end-user connection

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#58346]
The proximate problem to solve here is to report the remote client IP address of SQL clients when a SQL proxy is involved. In the code currently, the IP address of the SQL proxy is reported in logs instead (the code uses the remote IP address of the TCP connection directly).

To achieve this, we can have the SQL proxy deliver the "real" remote IP address as an additional pgwire-level "server status parameter" when the SQL connection is established. The postgres protocol allows a server to recognize arbitrarily many additional parameters than those described by the pg docs.

More generally, there is additional context we're considering in a SQL proxy about the end connection, which is not directly visible within cockroachdb:

- the client IP address
- distributed trace and span IDs
- the authentication method that was used, if/when the SQL proxy takes over authentication (NB: the username is already included in the client-server protocol)
- the age of the session, the session ID and other session-level state, in case the SQL proxy closes the server-side connection for idle session.

We can thus consider a pgwire extension that supports an entire namespace of additional server status parameters beyond the client remote IP, creating an avenue for future extensions.

**Comment by andy-kimball** [comment]
I believe pgwire already has a way to pass arbitrary key/value pairs, as part of the StartupMessage:
```
type StartupMessage struct {
	ProtocolVersion uint32
	Parameters      map[string]string
}
```
See the code in `pkg/sql/pgwire/server.go` that handles this message on the CRDB side:
```
// parseClientProvidedSessionParameters reads the incoming k/v pairs
// in the startup message into a sql.SessionArgs struct.
func parseClientProvidedSessionParameters(
	ctx context.Context, sv *settings.Values, buf *pgwirebase.ReadBuffer,
) (sql.SessionArgs, error) {
```

**Comment by knz** [comment]
Yes I am aware of this code (I wrote it), but we need to add the handling code for the newly recognized keys, and ensure that future changes are done in a principled manner (i.e. enforce a namespace for new keys)

**Comment by andy-kimball** [comment]
Let's keep it as stripped down as possible for 20.2 back-porting. I'd propose adding a single new key called `crdb:source_ip` (or an equivalent that's short and simple).
