### ISSUE TITLE
physicalplan: add support for multi-stage execution of aggregate functions

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#58347]
Most aggregate functions support multi-stage distributed execution in which on every node we perform a local aggregation, then we route all the intermediate results to all of the nodes (according to the grouping columns), and then we perform a final aggregation that gives us the result. For some aggregate functions the decomposition into local and final stages is trivial - e.g. in order to calculate `sum` we need to perform local `sum` and then the final `sum`; for other functions it is a bit more involved - e.g. in order to compute `avg` we calculate partial `sum` and `count` locally, then we finalize `sum` and `count` at the final stage and we render the result as `final_sum / final_count`.

(I believe Postgres calls the multi-stage execution a [partial mode](https://www.postgresql.org/docs/current/functions-aggregate.html).)

The decomposition of supported functions is defined here https://github.com/cockroachdb/cockroach/blob/9f678e75988bb4b19a0a7aeeb86fbfcdff046d60/pkg/sql/physicalplan/aggregator_funcs.go#L87

We are currently missing the following functions:
- [ ] `sqrdiff` (I think it should be possible to decompose it)
- [ ] `corr`
- [x] `var_pop`
- [x] `stddev_pop`
- [x] `covar_pop`
- [ ] `covar_samp`
- [x] `regr_intercept`
- [x] `regr_r2`
- [x] `regr_slope`
- [x] `regr_sxx`
- [x] `regr_syy`
- [x] `regr_sxy`
- [ ] `regr_count`
- [x] `regr_avgx`
- [x] `regr_avgy`

`avg` and `variance` are good examples of how more complicated decompositions are handled.

cc @mneverov in case you're interested

**Comment by mneverov** [comment]
@yuzefovich, definitely, that would  be awesome to work on this, thanks!
Although, from [the conversation](https://github.com/cockroachdb/cockroach/pull/56822#pullrequestreview-535947836):

> This doesn't look right. I think this entire thing only makes sense for single-arg operators anyway, 

I got the impression that it is impossible to have `merge` operation for multi-arg operators.

I'll take a look next year, so if anyone can start working immediately - please go ahead.

**Comment by yuzefovich** [comment]
I think that conversation is not directly applicable to this issue since here we are deciding on how to execute a particular logical plan (meaning after the optimizer has already chosen the plan) whereas that convo was about some "transformations" of the logical plan in order to get an equivalent one that has supposedly less cost.

Possibly, my usage of a word "decomposition" is a bit misleading since `AggregatesCanMerge` also talks about "decomposition".

**Comment by mneverov** [comment]
Ok, need to dig into the code :).

**Comment by piao88** [comment]
Hi @yuzefovich 
I'm new to the community and would like to pick this up.

**Comment by mneverov** [comment]
hi @piao88, have you already started working on this? May I take it?

**Comment by piao88** [comment]
hi @mneverov , I have already started.

**Comment by yuzefovich** [comment]
@piao88 @mneverov I think this issue is big enough for both of you to work on it, just make sure to communicate which functions you are working on.

**Comment by piao88** [comment]
hi @mneverov @yuzefovich I have already finished `var_pop` and `stddev_pop` and I 'm working on `covar_pop` and `covar_samp`.

**Comment by piao88** [comment]
hi @mneverov @yuzefovich I have already finished `var_pop` and `stddev_pop`

**Comment by henrjan** [comment]
hi, is this issue still ongoing? can i work on this?

**Comment by yuzefovich** [comment]
Hi @henrjan, thanks for the interest! Let's check in with @piao88 who have already opened up a PR (#59174) that addresses this issue.

@piao88 are you still interested in pushing #59174 forward or would you be ok if someone took over this issue and possibly your PR?

**Comment by piao88** [comment]
Hi@henrjan ,Of course you can .

**Comment by alimoosavi** [comment]
@yuzefovich 
I am new to cockroachdb project and this issue seems attractive to me , please assign this issue to me.

**Comment by yuzefovich** [comment]
@mneverov are you still interested in working on this issue? Looks like @piao88 made some progress in #59174, but that PR seems abandoned, so I'd assign the issue to @mneverov if they are still interested.

**Comment by piao88** [comment]
@yuzefovich Sorry, I am no longer interested in this issue, you can give it to someone else.

**Comment by mneverov** [comment]
thanks @yuzefovich , i'll take a look
