### ISSUE TITLE
Create user friendly error message for incremental BACKUP / GC collisions  

### ISSUE THREAD

**Issue by mikeczabator** [cockroachdb/cockroach#58370]
The below error can occur when an incremental backup is attempting to backup data that has already been gc'd.  This can result from a low `gc.ttl` value or from not running incremental backups often enough.  

This is a very easy error to hit, but the error message is cryptic to the average user.  The error message should be human readable explaining what issue was hit, and perhaps include a link to a description on how to fix.  

```failed to verify protection id:960dcb73-c9cd-4375-8020-9d3d5ea12f07 timestamp:<wall_time:1608544270268319000 > meta_type:"jobs" meta:"618017638092832775" spans:<key:"\214\211" end_key:"\214\212" > spans:<key:"\215\211" end_key:"\215\212" > spans:<key:"\216\211" end_key:"\216\212" > spans:<key:"\226\211" end_key:"\226\212" > spans:<key:"\227\211" end_key:"\227\214" > spans:<key:"\235\211" end_key:"\235\212" > spans:<key:"\237\211" end_key:"\237\214" > spans:<key:"\240\211" end_key:"\240\212" > spans:<key:"\251\211" end_key:"\251\212" > spans:<key:"\255\211" end_key:"\255\213" > spans:<key:"\276\231" end_key:"\276\237" > spans:<key:"\277\215" end_key:"\277\217" > spans:<key:"\300\211" end_key:"\300\212" > spans:<key:"\301\211" end_key:"\301\212" > spans:<key:"\303\211" end_key:"\303\217" > spans:<key:"\305\211" end_key:"\305\212" > spans:<key:"\276\232" end_key:"\276\233" > spans:<key:"\276\233" end_key:"\276\234" > spans:<key:"\276\234" end_key:"\276\235" > spans:<key:"\276\235" end_key:"\276\236" > spans:<key:"\276\236" end_key:"\276\237" > spans:<key:"\277\215" end_key:"\277\216" > spans:<key:"\277\216" end_key:"\277\217" > spans:<key:"\300\211" end_key:"\300\212" > spans:<key:"\301\211" end_key:"\301\212" > spans:<key:"\303\211" end_key:"\303\212" > spans:<key:"\303\212" end_key:"\303\213" > spans:<key:"\303\213" end_key:"\303\214" > spans:<key:"\303\214" end_key:"\303\215" > spans:<key:"\303\215" end_key:"\303\216" > spans:<key:"\303\216" end_key:"\303\217" > spans:<key:"\305\211" end_key:"\305\212" > on [r6:/Table/{SystemConfigSpan/Start-11} [(n10,s10):8, (n7,s7):14, (n11,s11):10, (n12,s12):13, (n13,s13):16, next=17, gen=50] r6:/Table/{SystemConfigSpan/Start-11} [(n10,s10):8, (n7,s7):14, (n11,s11):10, (n12,s12):13, (n13,s13):16, next=17, gen=50] r6:/Table/{SystemConfigSpan/Start-11} [(n10,s10):8, (n7,s7):14, (n11,s11):10, (n12,s12):13, (n13,s13):16, next=17, gen=50]]```

**Comment by adityamaru** [comment]
Closed by https://github.com/cockroachdb/cockroach/pull/61610.
