### ISSUE TITLE
release 21.1.0-alpha.2

### ISSUE THREAD

**Issue by alyshanjahani-crl** [cockroachdb/cockroach#58375]
Candidate SHA: 21432ccf9a6e2c7f8da29fbedf5a7e9cc1ded5a7
Deployment status: Qualifying on CC Cluster
Make and Publish Build: [Build Overview](https://teamcity.cockroachdb.com/buildConfiguration/Internal_Release_MakeAndPublishBuild/2620024).
Qualify Build: [Build Overview](https://teamcity.cockroachdb.com/buildConfiguration/Internal_Release_Qualify/2620030).
Publish Cockroach Release: WIP EDIT ME WIP.
 
CC Clusters Running the Build:
- [Issue Link](https://cockroachlabs.atlassian.net/secure/RapidBoard.jspa?rapidView=55&projectKey=SREOPS&modal=detail&selectedIssue=SREOPS-993)

 
Working Tags:
- Build ID: `v21.1.0-alpha.1-1340-g21432ccf9a`
- `staging-*` tag: `staging-v21.1.0-alpha.2`
 
[Release process checklist](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process)
 
Prep date: `WIP fill in date to roll out: usually Monday, a week before the release WIP`
- [x] [2. Pick a SHA](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-2.PickaSHA)
- [x] fill in `Candidate SHA` above
- [x] fill in `staging-* Tag` above
- [x] fill in `Build ID` above
- [x] fill in `Make and Publish Build` above
- [x] fill in `Qualify Build` above
 
- [x] [3. Announce the release to releases@](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-3.Announcethereleasetoreleases@)
- [x] [4. Ask SRE to run the build on some CC clusters](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-4.AskSREtorunthebuildonsomeCCclusters)
 
5-8: Qualify the Release. See [Release Qualification](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification)
- Short-running Checks:
- [x] [5. Verify node crash reports](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification#Verify-node-crash-reports-appear-in-sentry.io)
- Qualification Clusters:
- ~[6. Setup Qualification Clusters](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification#Setup-Qualification-Clusters)~ (N/A)
 
**Do not proceed below until the release date.**
 
Release date: `2/1/2021`
- ~[7 continued: Check cluster status](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification#Monitoring-the-Qualification-Clusters)~
- ~8. Destroy clusters~
- [x] [9. Publish Cockroach Release](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-9.PublishTheRelease)
- [x] Acked security@ and release-engineering-team@ on the generated AWS S3 bucket write alert to confirm these writes were part of a planned release (See [Publish Cockroach Release](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-9.PublishTheRelease) for details).
- [x] [10. Remove staging branch / tags from repository](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-10.Removestagingbranch/tags)
- [x] [11. Check binaries](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-11.CheckBinaries): [PR link](https://github.com/cockroachdb/bincheck/pull/251)
- [x] [12. Check docker image](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-12.Checkthedockerimage)
- [x] [13.Announce the release is cut to releases@](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-13.Announcethereleaseiscuttoreleases@)
- For all production or stable releases:
- ~[Announce version to registration cluster](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-AnnounceVersionToRegCluster)~ N/A, this is an alpha release
- ~[Update version map in bin/roachtest and regenerate test fixtures](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Updateversionmapinroachtestandregeneratetestfixtures)~ N/A, this is an alpha release
- [x] 15. Update docs (handled by Docs team)
- [x] 16. External communications for release (handled by Marketing eam)
 
Cleanup:
 
- [x] Remove staging branch / tags from repository

**Comment by asubiotto** [comment]
Taking this release over. Picking sha is still waiting on release blockers: https://github.com/cockroachdb/cockroach/issues?q=is%3Aopen+is%3Aissue+label%3Arelease-blocker+label%3Abranch-master

**Comment by asubiotto** [comment]
Restarting with 7bd8a7c41ec748e0211e8f7d09d2235d4fe571be cherry-picked.
