### ISSUE TITLE
OPT: suboptimal behavior related to UNION

### ISSUE THREAD

**Issue by xinyuliu12** [cockroachdb/cockroach#58383]
Hello everyone!

First off, I am sorry for gestures vaguely all of this. Second, I think we may have found a suboptimal behavior related to the `UNION` operator.

Here is a pair of TPC-H queries that exhibit this behavior.

```
SELECT "s_nationkey", 
       "s_comment" 
FROM   "supplier" 
UNION 
SELECT "s_suppkey", 
       "s_comment" 
FROM   "supplier"FETCH next 38 rows only;

SELECT   "s_nationkey", 
         "s_comment" 
FROM     ( 
                SELECT "s_nationkey", 
                       "s_comment" 
                FROM   "supplier" 
                UNION ALL 
                SELECT "s_suppkey", 
                       "s_comment" 
                FROM   "supplier"FETCH next 38 rows only) AS "t16" 
GROUP BY "s_nationkey", 
         "s_comment"
```

**Actual Behavior**
The first query takes 92.6 milliseconds on v20.2.0-alpha.1, while the second query only takes 2 milliseconds.
The first query's `EXPLAIN ANALYZE (DEBUG)` result is 
[stmt-bundle-firstquery.zip](https://github.com/cockroachdb/cockroach/files/5755671/stmt-bundle-firstquery.zip)

The second query's `EXPLAIN ANALYZE (DEBUG)` result is 
[stmt-bundle-secondquery.zip](https://github.com/cockroachdb/cockroach/files/5755672/stmt-bundle-secondquery.zip)

**Expected Behavior**
I would have expected the database system run these two queries with similar execution time, given that they compute the same result tables. It looks to me in this case that the cost of `UNION` operation outweighs the cost of performing a `UNION ALL` operation followed by a `DISTINCT` operation.
Here are the steps for reproducing our observations:

**Test environment**

* Ubuntu 20.04 machine "Linux panda 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux"
* Cockroachdb v20.2.0-alpha.1
* Database: TPC-H benchmark (with scale factor 5)

**Reproduce Bug**

1. Install cockroachdb v20.2.0-alpha.1     

```
    $ mkdir -p $(go env GOPATH)/src/github.com/cockroachdb
    $ cd $(go env GOPATH)/src/github.com/cockroachdb
    $ git clone https://github.com/cockroachdb/cockroach
    $ cd cockroach
    $ git checkout eaa939c
    $ make build
    $ sudo make install
```

* start a cockroachdb node in your preferred working directory
```
    $ cockroach start --insecure --store=node1 --listen-addr=localhost:26257 --http-addr=localhost:8080 --join=localhost:26257,localhost:26258,localhost:26259 --background
    $ cockroach init --insecure --host=localhost:26257
```

2. Set up TPC-H test benchmark (if you already have a TPC-H benchmark set up, you can skip step2; starting from step2, all commands should run in the directory ./tpch5 after downloading and extracting it)

* Download TPC-H (scale factor of 5) and extract it
    Download the dataset from the link: https://drive.google.com/file/d/1MLVFPKdRQhlRgmeRIumyIj8NBMRSQ3um/view?usp=sharing
```
    $ tar xzvf tpch5_setup.tar.gz
    $ cd tpch5
    $ chmod +x setup.sh
```

* Create DB and TPC-H schema
`   $ cockroach sql --insecure --host=localhost:26257`    
    In CockroachDB's built-in SQL client to create database:
```
    $ create database tpch5;
    $ exit
```
* Create TPC-H Schema
   `    $ cockroach sql --insecure --host=localhost:26257 -d tpch5 < dss.ddl
`
* Set up benchmark
```  
    $ ./setup.sh
    $ cockroach sql --insecure --host=localhost:26257 -d tpch5 < dss.ri

```
3. Test SQL query that exhibits performance issue
* Execute the queries after logging to the testing benchmark using the following command
`    $ cockroach sql --insecure --host=localhost:26257 -d tpch5
`

**Comment by DrewKimball** [comment]
I think these two queries are not equivalent, actually - it isn't correct to push a limit into a grouping / distinct operator. (Or as the case here, to convert a union into a `Distinct` on top of a `UnionAll` and then push the limit under the `Distinct`.)

The results actually end up being the same here between the two queries, but that's only because it turns out the first 38 rows are all distinct. You can see this by replacing `s_nationkey` in the two queries with `s_suppkey` so that the left and right union inputs have duplicates. The first query then returns 38 rows, but the second only returns 19.

**Comment by xinyuliu12** [comment]
Thank you so much for your feedback! 
I agree with you that push the limit through `Distinct` breaks the semantic equivalence, and also contributes to the significant time difference.
The logic behind converting a `UNION` into a combination of `UNION ALL` and `DISTINCT` is that we are curious to see whether the optimizer exists this transformation and whether these two alternatives have different costs in some cases.
Would you feel comfortable to comment on whether such a transformation exists and whether this could be a useful enhancement to the existing query optimizer (e.g., better query runtime and less expensive for a distributed setup)?

**Comment by DrewKimball** [comment]
Ah, I see. With regard to distributed execution, I believe a `UNION` is actually executed just like a `UNION ALL` followed by a `DISTINCT` on all columns, so I don't think it would be beneficial from that perspective. 
However, there are certain cases when we can prove that the `UNION` doesn't need to de-duplicate on all columns, in which case we can do a `DISTINCT` on only the necessary ones. When the columns are wide, this can result in significant time savings. Funnily enough, I've actually got a rule like that in-progress right now - see #64976

**Comment by xinyuliu12** [comment]
Thank you so much! It's good to know that this transformation is indeed useful in some cases!
