### ISSUE TITLE
backupccl: more gracefully handle job restoration in cluster restore

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#58418]
Today, when performing a cluster restore all running jobs from the original cluster will be restored and brought into the same state they were when they were backed up.

This might be problematic for certain types of jobs which communicate with external systems. For example, consider a schedule that writes backups to a certain folder, it is not desireable to have the restoring cluster start writing its own backups to the same folder. _We can't assume that the original cluster is no longer running._

One proposed solution here is to pause all restored jobs during cluster restore. This would give control to the user to resume or cancel any jobs as the situation demands.

Epic CRDB-8965

Jira issue: CRDB-3394

**Comment by pbardea** [comment]
Summarizing some offline conversations, the best way forward here is to:
- Schema changes should not be reverted, as reverting these jobs produces a schema change in the opposite direction. This is particularly scare with a long running DROP column for example. See https://github.com/cockroachdb/cockroach/issues/46541.
- All other jobs should be put into reverting as many jobs write non-transactionally and we cannot guarantee that those non-transactional writes were seen by backup.

**Comment by stevendanna** [comment]
As of https://github.com/cockroachdb/cockroach/pull/84886 we no longer restoring jobs.
