### ISSUE TITLE
userfile upload gives error when there exists an admin user with hyphens in name

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/cockroach#58430]
**Describe the problem**

`userfile upload` gives an error when there exists an admin user with hyphens in the name. This prevents uploads in Cockroach Cloud because there exists a default admin user `managed-service`.

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up secure CockroachDB version 20.2.2 cluster locally
2. Send SQL as root
 
```
CREATE USER "crl-support-florence" WITH PASSWORD cockroach;
GRANT admin to "crl-support-florence";
CREATE USER "florence" WITH PASSWORD cockroach;
GRANT admin to "florence";
```
3. Download and rename file to .csv
[promo_codes.csv.txt](https://github.com/cockroachdb/cockroach/files/5766795/promo_codes.csv.txt)

4. Send CLI

```
cockroach cert create-client florence --certs-dir=certs --ca-key=my-safe-directory/ca.key
cockroach userfile upload /Users/florencemorris/promo_codes.csv --url 'postgresql://florence@localhost:26257?sslcert=certs%2Fclient.florence.crt&sslkey=certs%2Fclient.florence.key&sslmode=verify-full&sslrootcert=certs%2Fca.crt'
```

5. See error

``` 
E210104 20:38:01.890538 1 cli/error.go:398  pq: failed to revoke privileges: revoke-user-privileges: at or near "-": syntax error
ERROR: failed to revoke privileges: revoke-user-privileges: at or near "-": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
REVOKE ALL ON TABLE defaultdb.public.userfiles_florence_upload_files, defaultdb.public.userfiles_florence_upload_payload FROM crl-support-florence
                                                                                                                                 ^
Failed running "userfile upload"
```

**Expected behavior**

```
successfully uploaded to userfile://defaultdb.public.userfiles_florence/promo_codes.csv
```

**Additional data / screenshots**

**Environment:**
 - CockroachDB version [e.g. 2.0.x] 20.2.2
 - Server OS: [e.g. Linux/Distrib] Mac, Cockroach Cloud
 - Client app [e.g. `cockroach sql`, JDBC, ...] cockroach sql

**Additional context**
What was the impact?
`userfile upload` functionality is not available in Cockroach Cloud Dedicated.

In Free Tier, the error is different (is it correct?):

```
cockroach userfile upload /Users/florencemorris/promo_codes.csv --url 'postgres://florence@free-tier.gcp-us-central1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&sslrootcert=cc-ca.crt&options=--cluster=weary-jaguar-23'
warning: --url specifies database "defaultdb", but command "upload" does not accept a database name - database name ignored
Enter password:
E210104 23:22:42.075296 1 cli/error.go:398  pq: external uri storage is not available to secondary tenants
ERROR: external uri storage is not available to secondary tenants
Failed running "userfile upload"
```

**Comment by florence-crl** [comment]
@adityamaru, please let me know if I should create a separate issue for the Free Tier error since it is different.

**Comment by adityamaru** [comment]
Cloed by #60020.
