### ISSUE TITLE
server: "NodeID must not be zero" errors after startup

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#5844]
build sha: multiple, up to and including 636e1b9

scenario: 5-node beta cluster running with different versions over 3 days.
when restarting nodes, I often see "NodeID must not be zero" errors for a few minutes after startup (not on all nodes though).

eg:
```
E160404 15:31:44.193962 storage/queue.go:446  [replicate] range=576 [/System/"tsd\x12cr.node.exec.error-10m\x00\x01\x89\xf8\x06/\xc62"-/System/"tsd\x12cr.node.exec.error-1h\x00\x01\x89\xf8\x06/\xb61"): error: storage/replica_command.go:2211: change replicas of 576 failed: roachpb/metadata.go:136: replica 3 is invalid: roachpb/metadata.go:153: NodeID must not be zero
```

I'm guessing some partially-filled request?

Full log for the latest restart of `ec2-54-209-133-121.compute-1.amazonaws.com`:
[node0.log.txt](https://github.com/cockroachdb/cockroach/files/202767/node0.log.txt)

**Comment by bdarnell** [comment]
There's a bug in `StorePool` (which tracks store health for the replication queue): for the first several minutes after startup, we consider stores that we have incomplete information about to be "alive", so we don't start the repair process prematurely. But if they're alive, the allocator may try to treat them as a replication target, leading to this error. We need to recognize this as a third state, eligible for neither adds nor removes.

How long were the nodes down when you restarted them? All at once or one at a time? Assuming all the other nodes are up it shouldn't take this long for them to transition from this uncertain state to known-good. There may be another problem with gossip here (possibly the same issue underlying #5826).

**Comment by mberhault** [comment]
I tend to do rolling restarts, either restarting node `N+1` as soon as node `N` is up and running, or waiting a few minutes between each. Not sure what I did in that particular case, but I've seen the message a few times.
I'll see if I can grab better information next time I see it.
