### ISSUE TITLE
roachtest: add at-scale test for long-running migrations

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#58455]
The kvserver code for long-running migrations (#48843) is present and we have a
first long-running migration (#58088), but no at-scale testing. Problems that
could arise here are high resource utilization; infinite retry loops; problems
with long-running txns used as part of the migrations; etc.

We need to add a roachtest that a) loads a large-scale cluster (2TB sounds
about right) at the predecessor version, then performs a rolling upgrade
into the new version, and verifies that the migrations complete within a
reasonable timeframe and without affecting cluster performance.

That last point - cluster performance - is currently difficult to assess, so we
may have to compromise or improve our tooling.

Jira issue: CRDB-3391

**Comment by tbg** [comment]
Idea: there should be version of this with an exponential-backoff chaos monkey here:

- sleep 10s
- restart a subset of the cluster
- sleep 10*1.3s
- restart a subset of the cluster
- sleep 10*1.3^2s
- ...

In this mode of course we wouldn't expect workload qps to hold steady.

**Comment by irfansharif** [comment]
Are we planning on adding a chaos variant here? (#59369 will close out this issue, without doing so.)

**Comment by tbg** [comment]
I would like to, and we can throw a few restarts in there, but realistically useful things are really difficult/onerous to orchestrate with roachtest. Whenever we restart nodes, we have to handle the errors that arrive at the gateway we are running the upgrade on. If we exclude the gateway from the chaos, that significantly reduces our coverage. We'd also have to space out the chaos events more and more as outlined above, but then what is the chaos testing? It's difficult to assess, from roachtest and also for operators generally, whether the system is healthy. Looking for ideas to get value out of this.
