### ISSUE TITLE
GC resulting in nodes becoming suspect

### ISSUE THREAD

**Issue by mikeczabator** [cockroachdb/cockroach#58458]
The GC from a large truncate command caused nodes to fail to update their liveness, and thus become suspect. This results in operational alerts being sent to the customer. The issue righted itself before intervention was needed.

truncate is a commonly used feature in this workload - and should not result in instability. GC should be throttled so as not to affect the node liveness.

https://cockroachdb.zendesk.com/agent/tickets/7155
https://cockroachlabs.atlassian.net/browse/CRDB-2269

**Comment by ajwerner** [comment]
This is certainly not @cockroachdb/sql-execution. The truncate leads to clear range requests being sent. Those, IIUC, lay down range deletion tombstones. It is then the range deletion tombstones which seem to starve foreground traffic (I assume). More information are all going to be important to understand the dynamics of this situation. 

* version
* hardware configuration
* cluster topology
* size of the tables being truncated
* rate of truncation
* other workload information

This feels like it's going to end up being @cockroachdb/storage.

**Comment by jbowens** [comment]
It would also be helpful to know which storage engine was in use (if a 20.1.x or 20.2.x release). This instability while handling broad range deletions tombstones is something we've seen a lot of on RocksDB. There were considerable improvements in the handling of range tombstones in Pebble in 20.2, with fast-path deletion-only compactions to remove sstables wholly covered by range tombstones. These 20.2 changes avoid a lot of unnecessary CPU and read IO cost, but deleting many gigabytes of data still produces a lot of write IO that may starve other writers. I'm not sure we've seen liveness issues from it on pebble 20.2, but it seems possible with sufficiently large drops.

@itsbilal added [deletion pacing](https://github.com/cockroachdb/pebble/commit/62f2e316b532ee5dcc57535e25ebcf9ca7c828d9#diff-c839f7b8d42ad3e5a36ad9bfac1b3101227a8261fd3b2a1a9556e56b5d5b34d3) for 21.1 that should smooth out the write IO associated with large truncates/drops.

**Comment by ajwerner** [comment]
The ZenDesk issue indicates v20.2.3.

**Comment by lunevalex** [comment]
Dupe #62672
