### ISSUE TITLE
sql: drop type internal error

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#58461]
```
demo@127.0.0.1:26257/defaultdb> create type ident as enum('foo');
CREATE TYPE

Time: 3ms total (execution 3ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> EXPLAIN ANALYSE DROP TYPE if exists ident, zoop;
ERROR: internal error: unexpected error from the vectorized engine: runtime error: invalid memory address or nil pointer dereference
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/colexecbase/colexecerror/error.go:90: func1()
runtime/panic.go:969: gopanic()
runtime/panic.go:212: panicmem()
runtime/signal_unix.go:742: sigpanic()
github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_name.go:45: Format()
github.com/cockroachdb/cockroach/pkg/sql/sem/tree/object_name.go:188: Format()
github.com/cockroachdb/cockroach/pkg/sql/sem/tree/hide_constants.go:43: formatNodeOrHideConstants()
github.com/cockroachdb/cockroach/pkg/sql/sem/tree/format.go:371: FormatNode()
github.com/cockroachdb/cockroach/pkg/sql/sem/tree/drop.go:191: Format()
github.com/cockroachdb/cockroach/pkg/sql/sem/tree/hide_constants.go:43: formatNodeOrHideConstants()
github.com/cockroachdb/cockroach/pkg/sql/sem/tree/format.go:371: FormatNode()
github.com/cockroachdb/cockroach/pkg/sql/sem/tree/format.go:413: AsStringWithFQNames()
github.com/cockroachdb/cockroach/pkg/sql/drop_type.go:155: startExec()
github.com/cockroachdb/cockroach/pkg/sql/plan.go:498: func2()
github.com/cockroachdb/cockroach/pkg/sql/walk.go:119: func1()
github.com/cockroachdb/cockroach/pkg/sql/walk.go:286: visitInternal()
github.com/cockroachdb/cockroach/pkg/sql/walk.go:86: visit()
github.com/cockroachdb/cockroach/pkg/sql/walk.go:50: walkPlan()
github.com/cockroachdb/cockroach/pkg/sql/plan.go:501: startExec()
github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:126: Start()
github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:133: Init()
github.com/cockroachdb/cockroach/pkg/sql/colexecbase/colexecerror/error.go:93: CatchVectorizedRuntimeError()
github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:242: Start()
github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:764: Run()
github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:380: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:366: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:959: PlanAndRun()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1007: execWithDistSQLEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:886: dispatchToExecutionEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:641: execStmtInOpenState()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:119: execStmt()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1445: func1()

HINT: You have encountered an unexpected error.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.

We appreciate your feedback.
```

This is a pretty weird one. I'll assign @solongordon for triage for Experience, but feel free to push back if this ends up being wrong.

**Comment by jordanlewis** [comment]
This was found via RSG, by the way. (cc @postamar regarding our earlier conversation)

https://teamcity.cockroachdb.com//viewLog.html?buildId=2558316&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests

**Comment by jordanlewis** [comment]
BTW, this is an example of the vectorized panic catcher saving non-vectorized stuff from panics... perhaps we don't have to do much more on that front, since soon everything will go through the vectorized engine? cc @yuzefovich @petermattis

**Comment by rafiss** [comment]
clarification on bug: the `explain analyze` isn't needed to reproduce it. `DROP TYPE IF EXISTS ident, zoop;` reproduces.

without `IF EXISTS` works correctly
```
> DROP TYPE  ident, zoop;
ERROR: type "zoop" does not exist
SQLSTATE: 42704
```

**Comment by rafiss** [comment]
the error happens when formatting the original statement, which is used as the description for the job that drops the type. the statement is formatted with `tree.AsStringWithFQNames`, so we try to resolve the non-existent type. the logic here is meant to handle this: https://github.com/cockroachdb/cockroach/blob/898fe2a409d46226a3669b40edca841cdc77146d/pkg/sql/sem/tree/object_name.go#L164-L169

but it doesn't work because `u.Resolved(ctx.ann)` returns an `interface{}` which has a (*tree.TableName)(nil)`, and therefore comparing to `nil` returns false. (More info in [this SO answer](https://stackoverflow.com/a/29138676/3642359).) This means later we call `Format` on a nil pointer: https://github.com/cockroachdb/cockroach/blob/898fe2a409d46226a3669b40edca841cdc77146d/pkg/sql/sem/tree/object_name.go#L186-L188

Probably the desired fix here is to not use an `interface{}` but a quicker fix could be to just change the code so it doesn't use the formatted SQL statement as the job description. removing my assignment for now since i'm not going to be working on the fix

**Comment by ajwerner** [comment]
> Probably the desired fix here is to not use an interface{} but a quicker fix could be to just change the code so it doesn't use the formatted SQL statement as the job description. removing my assignment for now since i'm not going to be working on the fix

I don't think the fix is either of these things directly. Instead we should make the thing that is returning `(*tree.TableName)(nil)` to be more careful and to return `nil`.
