### ISSUE TITLE
tree: formatting of `TableIndexName` seems wrong

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#58496]
**Describe the problem**

A table index name with no table specified will end up being formatted like:

`""."".<index name>` when using the `FQName` flag for formatting. That is bogus and doesn't refer to an index. There's also logic for formatting the prefix in this bogus is we have a schema, but it's not clear when that can happen. 

See the below code:
https://github.com/cockroachdb/cockroach/blob/c08088d4cc4556ac82ef29451d53278c12970c5b/pkg/sql/sem/tree/table_name.go#L191-L195. 

**Preferred Solution**

Ideally we'd annotate the `TableIndexName` tree node as at some point during planning we do end up resolving this index to a real table. If we had proper annotations then in the event log context which motivated this issue we'd be able to properly format the name. On the way to that solution, we should stop writing this bogus format which will be interpreted as an object name for an index. 

**Additional context**

This arose in the context of #58472 to fix  #57740.

**Comment by ajwerner** [comment]
cc @knz

**Comment by knz** [comment]
How is this a logging issue and not a sql experience issue?

**Comment by ajwerner** [comment]
> How is this a logging issue and not a sql experience issue?

Updated. Offline we confirmed that the existing logic when the table is missing is totally bogus. I'm inclined to fix the bug before following through on the annotation as that is somewhat more involved.

**Comment by knz** [comment]
yes that would be nice

**Comment by rafiss** [comment]
@ajwerner @the-ericwang35 just curious -- are there plans to fix the FQName formatting in time for 21.1?

**Comment by ajwerner** [comment]
Hmm this feels like a good thing for @fqazi to pick up. I’m going to tentatively assign him.
