### ISSUE TITLE
Drain Not draining due to single lease - backport to v20.2

### ISSUE THREAD

**Issue by fabiog1901** [cockroachdb/cockroach#58505]
We see the issue happening where a node takes over 10 minutes trying to drain, and has to be killed. This is a request for the fix to be back-ported for v20.2.

Linked to #53760 

**ZD ticket**: [6855](https://cockroachdb.zendesk.com/agent/tickets/6855)

**Comment by fabiog1901** [comment]
@knz for triage

**Comment by knz** [comment]
@fabiog1901 I assume you are confused? The linked issue #53760 is in no way related to the zendesk ticket.

I do not know what is the github issue for the particular symptom from the ZD ticket. Is there one already? That may be an issue that @andreimatei worked on in November, but I am not sure.

It makes no sense to talk about "backporting the fix of #53760   to 20.2" in the context of this ZD ticket. You need a better issue and a link to the proper PR to be backported.
