### ISSUE TITLE
rocksdb: audit and tweak options.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#5852]
build sha: 636e1b9

1100 sst files taking up approx 2GB.

full file list: 
[filelist.txt](https://github.com/cockroachdb/cockroach/files/203147/filelist.txt)

openfd ulimit is 1024.

Logs/data/binary backed up on host `ec2-52-91-234-29.compute-1.amazonaws.com` in `/mnt/data.5852, ~/logs.5852, ~/cockroach.5852`

**Comment by bdarnell** [comment]
Rocksdb has a `max_open_files` limit that we should be setting (see my comment in #4493).

There are also other settings that control the file size. The default for `target_file_size_base` is 2MB, which is way too small for a DB that aims to consume the entire disk. I think we also want to increase `target_file_size_multiplier` from the default of 1 to 10 (which is used in all the docs and is consistent with `max_bytes_for_level_multiplier`)

**Comment by mberhault** [comment]
Renaming this entirely. I'll start by checking basic file count/size options.

**Comment by tamird** [comment]
Closing as @petermattis has spent considerable time here recently.
