### ISSUE TITLE
 INT (or DECIMAL or FLOAT)  cast to timestamp error

### ISSUE THREAD

**Issue by qinzl1** [cockroachdb/cockroach#58520]
- CockroachDB version 20.1.8

The right time is ‘2020-12-25 15:59:59’

>  SELECT CAST(cast(1608911999781/1000 as int) AS TIMESTAMP) ;
          timestamp
  2020-12-25 16:00:00+00:00
(1 row)

![image](https://user-images.githubusercontent.com/20242930/103845554-458d2200-50d7-11eb-9751-9ebb251ed10f.png)

**Comment by rafiss** [comment]
@qinzl1  The underlying issue here is with the cast to `INT`.

In cockroachdb, the `/` operator returns a decimal, and casting that to INT will actually round up. If you want to do integer floor-division, you'd need the `//` operator.
```
root@:26257/defaultdb> select cast(1608911999781/1000 as int);
     int4
--------------
  1608912000
(1 row)

root@:26257/defaultdb> select 1608911999781/1000;
     ?column?
------------------
  1608911999.781
(1 row)

root@:26257/defaultdb> select 1608911999781//1000;
   ?column?
--------------
  1608911999
(1 row)

root@:26257/defaultdb> SELECT CAST(cast(1608911999781//1000 as int) AS timestamp) ;
          timestamp
-----------------------------
  2020-12-25 15:59:59+00:00
(1 row)
```

**Comment by rafiss** [comment]
Closing since this falls under https://github.com/cockroachdb/cockroach/issues/41448
