### ISSUE TITLE
stability: raft panic: requested entry at index is unavailable

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#5857]
build sha: 5ea8fde

5-node beta cluster that hasn't been wiped for 4 days or so (restarted multiple times with newer binaries, so this may be an odd condition).
node 4 (`ec2-54-209-150-36.compute-1.amazonaws.com`) had recently crashed on OOM (also in logs). Was restarted with same binary and two minutes later (after a decent amount of activity), crashed with:
```
panic: requested entry at index is unavailable

goroutine 57 [running]:
panic(0x163d660, 0xc8201c7ed0)
  /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/coreos/etcd/raft.(*raft).sendAppend(0xc822cdce40, 0x6)
  /go/src/github.com/coreos/etcd/raft/raft.go:299 +0x997
github.com/coreos/etcd/raft.stepLeader(0xc822cdce40, 0x4, 0x5, 0x6, 0xf1b, 0x0, 0x2177, 0x0, 0x0, 0x0, ...)
  /go/src/github.com/coreos/etcd/raft/raft.go:629 +0x964
github.com/coreos/etcd/raft.(*raft).Step(0xc822cdce40, 0x4, 0x5, 0x6, 0xf1b, 0x0, 0x2177, 0x0, 0x0, 0x0, ...)
  /go/src/github.com/coreos/etcd/raft/raft.go:564 +0x3e0
github.com/coreos/etcd/raft.(*RawNode).Step(0xc823031ec0, 0x4, 0x5, 0x6, 0xf1b, 0x0, 0x2177, 0x0, 0x0, 0x0, ...)
  /go/src/github.com/coreos/etcd/raft/rawnode.go:175 +0x19d
github.com/cockroachdb/cockroach/storage.(*Store).handleRaftMessage(0xc8200c0000, 0xc821e37200, 0x0, 0x0)
  /go/src/github.com/cockroachdb/cockroach/storage/store.go:1823 +0x575
github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1()
  /go/src/github.com/cockroachdb/cockroach/storage/store.go:1880 +0x54f
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820306070, 0xc820b95630)
  /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
  /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62
```

Machine is still down, copy of data/logs/binary with `.5857` suffix.

Full log:
[node3.log.txt](https://github.com/cockroachdb/cockroach/files/203420/node3.log.txt)

**Comment by bdarnell** [comment]
We should set `GOTRACEBACK=all` on these machines so we get more than the one stack trace.

This is raft panicking on an error we returned from `Replica.Snapshot`. It could be caused by the same race as #4890.

**Comment by mberhault** [comment]
Ran into it again, this time with `GOTRACEBACK` enabled.
Note: this occurred 3 minutes after restart. The node had previously died of OOM.

Full log, including the previous run.
[cockroach.stderr.txt](https://github.com/cockroachdb/cockroach/files/206414/cockroach.stderr.txt)

**Comment by mberhault** [comment]
backed up on `ec2-52-91-234-29.compute-1.amazonaws.com` with suffix `.5857.2`

**Comment by mberhault** [comment]
again on `ec2-54-209-69-52.compute-1.amazonaws.com`
everything copied with `.5857` suffix.
