### ISSUE TITLE
ForestDB store

### ISSUE THREAD

**Issue by pyros2097** [cockroachdb/cockroach#586]
How about using [forestdb](https://github.com/couchbase/forestdb) as a backend store as it seems to be faster than rocksdb and has transactions inbuilt?

**Comment by spencerkimball** [comment]
We may want to use a different backend store, or allow them to be swapped. But it's not on the near term roadmap. Whatever kinds of transactions which the backend store more or may not provide would be mostly irrelevant to the distributed transactions which cockroach provides at a higher level.

Also, I seriously doubt forestdb is much faster in the general case, though as with anything, various benchmarks may show a marked difference in certain circumstances.
