### ISSUE TITLE
cli: include active trace spans in debug.zip

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#58608]
**Is your feature request related to a problem? Please describe.**
Now that we have a way to observe long-running trace spans, we should also include them in debug.zip:

https://github.com/cockroachdb/cockroach/issues/55592

**Describe the solution you'd like**
Either dump (a suitably filtered) select on https://github.com/cockroachdb/cockroach/issues/55733 or add and hit an API endpoint straight into the registry.

The latter might be preferrable if we want Jaeger-compatible output.

**Describe alternatives you've considered**

**Additional context**

**Comment by tbg** [comment]
Note that this motivates https://github.com/cockroachdb/cockroach/issues/58610

**Comment by angelapwen** [comment]
Just noticed this issue: have already included a select into debug.zip for the long-running trace spans vtable in #59492 but we can leave this open if we want the Jaeger-compatible output.

**Comment by tbg** [comment]
To close this issue, we should also include the payloads for all of the long-running trace spans via https://github.com/cockroachdb/cockroach/pull/60922.
