### ISSUE TITLE
tracing: make all ways to associate data with a Span redactable

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#58610]
**Is your feature request related to a problem? Please describe.**
Tracing information can be sent to the SQL root user, debug.zip, and external tracers. It is desirable to apply our budding redactability best practices here as well.

**Describe the solution you'd like**
Make all ways to associated data with a Span redactable. This primarily includes free-form text messages (`log.Event` and co) as well as structured payloads attached to a Span. The former should get the treatment our regular logging APIs have already received, and the latter should be required to implement `SafeFormatter`.

Other data associated with spans are the operation name, tags, log tags, and baggage items. Tags in particular tend to contain PII and thus need redaction.

**Describe alternatives you've considered**

**Additional context**

Jira issue: CRDB-3379

**Comment by knz** [comment]
I understand this was considered to fall under obs infra.
cc @maryliag

**Comment by tbg** [comment]
This has popped up on my radar again in the context of https://github.com/cockroachdb/cockroach/pull/70406. I don't know how urgent it is, but at some point I suspect the serverless UX will require redacted traces so that a) we can be sure we don't leak PII to SQL tenants and b) we can continue to rely on tracing to troubleshoot problems.
It's unclear (to me) what weight b) carries. Users generally don't use the KV-level details in verbose traces very much (I think) and if so, then only in conjunction with our support teams. However, if our support term generally has to "impersonate" a tenant to get a trace for an operation it is having trouble with, and that trace is completely clipped (as in #70406), then the traces will not provide they value they do today for on-prem clusters. In other words, whatever tools we use to make customers successful, they should work on Serverless. This one, as of #70406, is lagging behind.
cc @andy-kimball do decide on what timelines changes need to be implemented here.

**Comment by andy-kimball** [comment]
I'm not sure what you mean by "decide on what timeline changes need to be implemented here"?

**Comment by tbg** [comment]
Discussed privately on [Slack](https://cockroachlabs.slack.com/archives/C02EYMB6QKG) with @aaron-crl:

- we'll patch free tier via regular scheduled upgrade
- paid tier needs to pick up a beta that has the fix (hopefully beta.2, but perhaps beta.3)

I'll prioritize getting #70406 merged and backported to release-21.2 branch.

**Comment by tbg** [comment]
I'm going to go ahead with https://github.com/cockroachdb/cockroach/pull/70562. After that PR is merged, we still have to develop a story for structured payloads. At the time of writing, `(*Span).RecordStructured` has dozens of callers. Unfortunately, the problem is not as easy as mandating that all payloads implement `redact.SafeFormatter`. For example, the key in a `ContentionEvent` are expected to reach the tenant to enable its SQL Observability features centered around contention, but redaction would prevent that. This either means some complication in what we ask of redaction - for example, the redaction step could be aware of the tenantID and would know to leave keys owned by this tenant intact - or a reworking of the upstream consumer features to work with redacted data. (Note that keys can be partially redacted, we can keep the descriptor and index IDs intact, stripping just the row-level data).

**Comment by tbg** [comment]
An additional question that came up in the PR is around redaction when logging to external opentracing tracers. As of #70562, no redaction is performed for these backends, but ultimately we may want some. This seems of lower priority though, lest we start wanting to do that in Serverless.

**Comment by tbg** [comment]
I opened https://github.com/cockroachdb/cockroach/pull/70758 to document the non-redactable payloads. It's worse than I thought, I didn't realize we had started putting `fmt.Sprintf(...)` type payloads into the strings.

I'm marking this issue as a release blocker and will transfer ownership to obs-inf as well as bulk I/O, which seems to own most of the problematic cases.

**Comment by adityamaru** [comment]
Thanks for opening #70758. I went with Sprinting in structured payloads because we wanted to be able to fetch inflight job traces without switching verbose tracing on. If a job is stuck, we ideally want to have it configured with a root span that has been collecting traces so that we don't have to cancel + retry the job. I completely agree that once we have always-on tracing if an event does not have a structured proto it should be logged instead. I'll fill in the stub methods in that PR and send out a patch for the time being.

**Comment by adityamaru** [comment]
ahh I didn't realize adding SafeFormat to the structured payloads isn't going to be enough. I should've read your previous comment carefully. I don't have as much confidence in my understanding of the scope, so maybe we should vet the payloads and StringValue usages for the time being, and then work on a wider fix once this is no longer blocking the release?

**Comment by tbg** [comment]
Yes that would be my preference. My first question here would be, *can* tenants even pull the JOBS tracing data, i.e. is there an endpoint available to them? If they can't, and if that's all the uses of `types.StringValue`, then we're in the clear.

**Comment by adityamaru** [comment]
The only way to pull job traces is via `./cockroach debug job-trace` or  inspecting `crdb_internal.node_inflight_trace_spans`. Are these available to tenants? I'm a bit out of my depth here.

**Comment by tbg** [comment]
`crdb_internal.node_inflight_trace_spans` is available. The question is really if whichever KV host cluster endpoints jobs on the tenant hit return trace data to the tenant. If so, tenants are likely to receive the `StringValue`s.

**Comment by tbg** [comment]
Btw, all of the tracing uses that occur on the tenant are automatically fine! What happens on the tenant stays on a tenant. Taking a look at it that might be most of them.

**Comment by tbg** [comment]
Something like

https://github.com/cockroachdb/cockroach/blob/3b607bb6bfd8c60826900392e0ea0dc1b1427017/pkg/kv/kvserver/batcheval/cmd_export.go#L87-L95

is fine and not fine. It's not fine in the sense that it prints a key into the trace while on the KV host cluster, and then returns that to the tenant later (presumably). But it is fine in the sense that the tenant certainly owns `args.{Key,EndKey}` anyway and so we're not telling them anything sensitive here. We are leaking the KV node's NodeID, which I assume we are fine with - that is marked as a SafeValue anyway which means it wouldn't be redacted either way.

**Comment by tbg** [comment]
re: "is fine and not fine", this is why I'm looping in obs-inf - the old world in which we say "X is always sensitive" breaks down a bit with multi-tenancy. We have "X is sensitive if you are not the owner of X", which is a more complex model that we don't have the infrastructure for employing in code.

**Comment by adityamaru** [comment]
Thanks for the explanation, that makes sense. The only other BulkIO tracing events that happen outside the tenant are:

- https://github.com/cockroachdb/cockroach/blob/master/pkg/util/limit/limiter.go#L57
- https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvserver/batcheval/cmd_add_sstable.go#L185

The rest are all in SQL land. Both these recordings don't leak PII as they are only logging the size and length of data. So from my point of view `cmd_export.go` printing the span is the only controversial trace. If obs-infra feels strongly about this given tbgs' explanation above, I'm okay removing those trace recordings till we have a better model.

**Comment by dhartunian** [comment]
Just removed the `release-blocker` label since https://github.com/cockroachdb/cockroach/pull/70774 has been approved.
