### ISSUE TITLE
sql/pgwire: Finagle-postgres `prepareAndQuery` with incorrect arg count times out

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#5862]
1. What did you do?
`prepareAndQuery('SELECT $1, $2', "hello")`
2. What did you expect to see?
An error.
3. What did you see instead?
A timeout.

Looks like finagle-postgres doesn't `sync` after `bind`, so the server isn't forced flush the error. The client then blocks forever waiting for a `BindResponse`. Probably a bug on their side, but works against postgres.

**Comment by tschottdorf** [comment]
Ran into that too. Quite annoying.

**Comment by tamird** [comment]
Is it that postgres flushes on any error? The docs are pretty explicit about the client _having_ to `flush` if it wants any intermediate state during extended query.

**Comment by mjibson** [comment]
I'll fix this if you post some repro code.
