### ISSUE TITLE
sql: support `TIMESTAMP WITH(OUT) TIME ZONE`

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#5863]
## The spec says:

>          6) If the data type of CR is TIME or TIMESTAMP, then the implicit
>             time zone of the data is the current default time zone for the
>             SQL-session.
> 
>          7) If the data type of CR is TIME WITH TIME ZONE or TIMESTAMP WITH
>             TIME ZONE, then the time zone of the data is the time zone rep-
>             resented in the value of CR.

## When inserting a timestamp / parsing a value:
`WITHOUT ZONE` (or no modifier) does not consider the session offset.
Open Question: should it even accept a ts that has an explicit offset? If so, what should it do? (postgres does, and silently ignores it(!))

 `WITH ZONE` should use supplied offset if present to calculate UTC time and insert UTC, and should otherwise use the session offset to calculate UTC and insert that.

## When returning a timestamp:
`WITHOUT ZONE` (or no modifier) should *not* include an offset (we currently do). The session offset isn't considered and no shift is required.
`WITH ZONE` *should* include an offset when returned, and it should ideally be the session offset, thus the timestamp should be shifted as needed, since the stored time is UTC.

**Comment by petermattis** [comment]
When parsing, if an offset is present I think it should be used. Silently ignoring it sounds wrong.

**Comment by dt** [comment]
agreed, though an alternative would be to error if an offset is included in a `timestamp (without time zone)`

**Comment by dt** [comment]
After a some more discussion with @paperstreet it seems there are two high-level options: one is we add a parameter to our current `DTimestamp` type and such that changes whether we include the offset when rendering, parsing etc. The other is that we introduce a new, disparate timestamp type. 

The first seems like less work and less code duplication -- since the only difference in behavior is during parsing and rendering, adding a flag could easily support that.
That said, semantically, it looks safer to be explicitly disparate types and require explicit conversions. Even though both just store a time.Time internally, a comparison is arguable meaningless: in one that time is in UTC, in the other it is zoneless, so assuming a zone (even of UTC) to make a comparison introduces ambitious behavior.

Erring on the side of requiring explicit choice of behavior, I'm leaning towards introducing a new type (and probably renaming the existing so we have `TimestampWithZone` and `TimestampWithoutZone` internally) and proving explicit conversion functions from one to the other, but never making an implicit conversion.

**Comment by vivekmenezes** [comment]
I probably missed this, why would someone not be happy with the timestamp
type we offer today? Is this issue still about TIMESTAMP WITH TIMEZONE, or
do you see two issues here?

**Comment by bdarnell** [comment]
It's unclear to me why the world needs two timestamp types that differ in this way (it would make more sense if `WITH TIME ZONE` actually stored a time zone in addition to the timestamp as converted to UTC), but this was actually one of the sticking points when I was working on cockroachdb/cockroach-python#15. SQLAlchemy's test suite expects there to be both `WITH` and `WITHOUT TIME ZONE` types that are distinguishable on the wire.

**Comment by dt** [comment]
The SQL spec is pretty clear about the behavior of `TIMESTAMP WITH TIME ZONE` and `TIMESTAMP WITHOUT TIME ZONE`. Our current `TIMESTAMP` behavior is actually pretty close to `WITH TIME ZONE` version, however the spec stipulates that `TIMESTAMP` with no modifiers should be the same as `TIMESTAMP WITHOUT TIME ZONE` (and thus should not contain an offset) and it looks like strict clients, like jdbc, choke when we incorrectly include an offset in a `TIMESTAMP` type.

**Comment by dt** [comment]
I suspect we need to support both `WITH TIME ZONE` and `WITHOUT TIME ZONE`. Personally I think that the `WITHOUT TIME ZONE` behavior is much harder for an application to use correctly and should be avoided, but violating the spec seems likely to cause even more confusion.

**Comment by vivekmenezes** [comment]
I think we should worry less about the spec in this regard. How does this all compare to postgres? it will be valuable to discuss what's broken. Thanks

**Comment by petermattis** [comment]
@vivekmenezes Postgres implements the spec. `TIMESTAMP` is shorthand for `TIMESTAMP WITHOUT TIME ZONE`. `TIMESTAMPTZ` is shorthand for `TIMESTAMP WITH TIME ZONE`.

When is `TIMESTAMP WITHOUT TIME ZONE` actually useful? Supporting it only for test suites seems burdensome.

**Comment by dt** [comment]
What's broken is that clients expect `TIMESTAMP` to return a timestamp string without an offset, and choke when we include one. They're correct in their assumption however because the spec explicitly says that it does not include an offset, unless you specify `WITH TIME ZONE`. Postges obeys the spec.

**Comment by petermattis** [comment]
Can we have `TIMESTAMP` return a string without an offset because the time zone is always UTC? Or will that break these clients as well.

**Comment by dt** [comment]
@petermattis for `WITHOUT TIME ZONE` the behavior is to return what's stored, without an offset, but whether or not that is UTC is up to the client that wrote it, since the write will be without an offset too.

**Comment by petermattis** [comment]
@dt Right. What I'm proposing is we keep all of the existing time zone logic (i.e. we normalize timestamps to UTC for storage) and then for `TIMESTAMP WITHOUT TIME ZONE` we return that UTC normalized timestamp. This differs from the Postgres behavior in that an offset in a timestamp string would be honored during parsing.

**Comment by dt** [comment]
That's what I was thinking originally, but I'm not sure we can normalize to UTC for `WITHOUT TIME ZONE`.

Here's what postgres does:
```
david=# CREATE TABLE test1 (t timestamp);
david=# SET TIME ZONE 0; INSERT INTO test1 VALUES('2015-05-01 12:00:00');
david=# SET TIME ZONE 5; INSERT INTO test1 VALUES('2015-05-01 12:00:00');
david=# SET TIME ZONE 0; SELECT * FROM test1;
 2015-05-01 12:00:00
 2015-05-01 12:00:00
david=# SET TIME ZONE -1; SELECT * FROM test1;
 2015-05-01 12:00:00
 2015-05-01 12:00:00
```
So, it looks like `WITHOUT TIME ZONE` never uses the session offset and will always return exactly what was supplied, regardless of any changes to the session zone in the interim. 

The same setup but with `WITH TIME ZONE`:
```
david=# CREATE TABLE test1 (t timestamp with time zone);
david=# SET TIME ZONE 0; INSERT INTO test1 VALUES('2015-05-01 12:00:00');
david=# SET TIME ZONE 0; INSERT INTO test1 VALUES('2015-05-01 12:00:00-03:00');
david=# SET TIME ZONE 5; INSERT INTO test1 VALUES('2015-05-01 12:00:00');
david=# SET TIME ZONE 5; INSERT INTO test1 VALUES('2015-05-01 12:00:00-03:00');
david=# SET TIME ZONE 0; SELECT * FROM test1;
 2015-05-01 12:00:00+00
 2015-05-01 15:00:00+00
 2015-05-01 07:00:00+00
 2015-05-01 15:00:00+00
david=# SET TIME ZONE -1; SELECT * FROM test1;
 2015-05-01 11:00:00-01
 2015-05-01 14:00:00-01
 2015-05-01 06:00:00-01
 2015-05-01 14:00:00-01
```
So we see `WITH TIME ZONE` is corrected to UTC, using the supplied offset if present or the session offset if not, and is always rendered in the session offset.

My read, looking at this, is that stored values of `without time zone` are basically zoneless in the eyes of the DB and thus we don't actually know the concrete UTC time they correspond to, so we can't, eg, compare a `timestamp with time zone` to a `timestamp without time zone`.  We can compare two with, or two without, but not to each other, unless we're given an explicit conversion.

**Comment by petermattis** [comment]
I was thinking that a `TIMESTAMP` literal without an explicit offset would be treated as UTC and that we'd ignore the session `TIME ZONE` setting. A `TIMESTAMP` literal with an explicit offset would be normalized to UTC and we'd ignore the `TIME ZONE` setting when returning values. So all timestamp values be stored in UTC making their values comparable. When returning a value, `TIMESTAMP` values would always be returned in UTC and `TIMESTAMP WITH TIME ZONE` values would be returned in the session `TIME ZONE`. 

The difference from Postgres is that we don't silently ignore the offset in `TIMESTAMP` literals. I'm sure there is some subtlety that would prevent the above from working. What is it?

**Comment by dt** [comment]
The assumption of UTC when no offset is provided is where I worry that we'd introduce surprises, eg in an example like this:
```
CREATE TABLE test (t1 timestamp, t2 timestamp with time zone);
SET TIME ZONE -1;
INSERT INTO test ('2015-05-01 12:00:00', '2015-05-01 12:00:00');
SELECT * FROM test WHERE t1 == t2;
```

**Comment by petermattis** [comment]
@dt Agreed, that is mildly surprising, yet I think the difference between `TIMESTAMP WITHOUT TIME ZONE` and `TIMESTAMP WITH TIME ZONE` would be intuitive: the `WITHOUT TIME ZONE` variant would ignore the setting of the the session `TIME ZONE` while the `WITH TIME ZONE` variant would obey it.
