### ISSUE TITLE
stability: OOM on raft.Unmarshal

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#5864]
build sha: e4cdd45

beta cluster: two nodes died overnights of OOM.
Upon restart, crashed shortly after (within 30s), again of OOM.

We don't have a lot of stats printed out (not enough time), but we do get some:
```
Node 1:
I160405 12:44:15.750571 server/status/runtime.go:160  runtime stats: 4.7 GiB RSS, 141 goroutines, 2.4 GiB active, 0.00cgo/sec, 0.00/0.00 %(u/s)time, 0.00 %gc (27x)
Node 2:
I160405 12:44:21.018006 server/status/runtime.go:160  runtime stats: 5.0 GiB RSS, 139 goroutines, 3.0 GiB active, 0.00cgo/sec, 0.00/0.00 %(u/s)time, 0.00 %gc (31x)
```

Heap profile for one of those shows:
```
Showing top 10 nodes out of 17 (cum >= 1453.04MB)
      flat  flat%   sum%        cum   cum%
 1437.90MB 98.24% 98.24%  1437.90MB 98.24%  github.com/coreos/etcd/raft/raftpb.(*Entry).Unmarshal
    0.91MB 0.062% 98.30%  1451.02MB 99.14%  github.com/cockroachdb/cockroach/storage.(*Replica).Snapshot
    0.55MB 0.038% 98.34%  1438.45MB 98.28%  github.com/cockroachdb/cockroach/storage.(*Replica).entries.func1
         0     0% 98.34%  1437.90MB 98.24%  github.com/cockroachdb/cockroach/roachpb.Value.GetProto
         0     0% 98.34%  1444.08MB 98.66%  github.com/cockroachdb/cockroach/storage.(*Replica).entries
         0     0% 98.34%  1453.04MB 99.27%  github.com/cockroachdb/cockroach/storage.(*Store).handleRaftMessage
         0     0% 98.34%  1456.05MB 99.48%  github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1
         0     0% 98.34%  1446.60MB 98.83%  github.com/cockroachdb/cockroach/storage/engine.MVCCIterate
         0     0% 98.34%  1456.58MB 99.52%  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1
         0     0% 98.34%  1453.04MB 99.27%  github.com/coreos/etcd/raft.(*RawNode).Step
```

I can try to grab more heaps and get as close to the crash as possible, but my guess is it's going to be more of the same.

Heap graphs for both nodes:
[heap1.pdf](https://github.com/cockroachdb/cockroach/files/204473/heap1.pdf)
[heap2.pdf](https://github.com/cockroachdb/cockroach/files/204474/heap2.pdf)

Full logs for both:
[cockroach.stderr.1.txt.gz](https://github.com/cockroachdb/cockroach/files/204476/cockroach.stderr.1.txt.gz)
[cockroach.stderr.2.txt.gz](https://github.com/cockroachdb/cockroach/files/204477/cockroach.stderr.2.txt.gz)

**Comment by mberhault** [comment]
data/logs/binaries copied with `.5864` suffix on:
```
1: ec2-54-209-69-52.compute-1.amazonaws.com
2: ec2-54-208-199-194.compute-1.amazonaws.com
```

**Comment by bdarnell** [comment]
For unmarshal failures, we could do some things to handle huge snapshots more gracefully, but the root cause is going to be on the nodes that are sending the giant snapashots, not the ones that are crashing while receiving them. Can you save the logs and data on all nodes, not just the crashing ones?

**Comment by tschottdorf** [comment]
We could also log some information on snapshots sent to the log. Shouldn't
be too noisy at INFO, at least not for now, right?

**Comment by bdarnell** [comment]
Yeah, adding logging to both `Snapshot` and `applySnapshot` is part of my plan for tracking these issues down.

**Comment by mberhault** [comment]
if it's likely to be too large, we can always hide the logging behind an env variable.

**Comment by tamird** [comment]
There have been recent improvements in this area: #7118, #7040, #7125. Doesn't look like there's more mileage to be had from this issue.
