### ISSUE TITLE
sql: support `timestamptz` type as alias for `timestamp`?

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#5865]

**Comment by dt** [comment]
cc @paperstreet who has been looking at related things lately.

**Comment by petermattis** [comment]
cc @bdarnell, @vivekmenezes who might remember more about the details of our current support. From experimentation right now, it seems that our `timestamp` type is more like the postgres `timestamptz` type. That is, timestamps are always stored in UTC but then converted to whatever the session time zone is returned to the user. It looks like this last bit isn't working correctly, we always display timestamps in UTC. Perhaps it was broken when we switched to `pgwire`.

**Comment by vivekmenezes** [comment]
I think it is fine to make timestamptz an alias of timestamp. I think we
should always parse the offset when provided (opposing the SQL standard)
even when using the timestamp type.
We should use the session time zone to present the timestamp to the user
(the time zone provided is effectively forgotten by the database).

**Comment by bdarnell** [comment]
I don't remember the original discussions about this but on reviewing the docs it does look like our timestamp type is more like the postgres `WITH TIME ZONE` type (I think we were initially discouraged from implementing the `WITH TIME ZONE` type by a misreading of the postgres docs, which pointed out that `TIME WITH TIME ZONE` is nonsensical without date information. `TIMESTAMP WITH TIME ZONE` is fine, though). 

Assuming the behavior is the same I'd be fine with adding `timestamptz`/`WITH TIME ZONE` aliases for our timestamp type. I'd be skeptical of adding a without-time-zone variant that does what postgresql's does.

**Comment by dt** [comment]
sounds like everyone is okay with aliasing `timestamptz` to our current `timestamp` since it conforms to that behavior. I filed a separate issue for `TIMESTAMP WITH TIME ZONE` since that is different (a column type that actually stores the zone supplied) #5863

**Comment by bdarnell** [comment]
Is `TIMESTAMP WITH TIME ZONE` really different? I can't find anything in the docs about what exactly `timestamptz` does, but postgres appears to treat them as equivalent at least in its introspection routines:
```
postgres=# create table timestamp_test (a timestamptz, b timestamp with time zone);
CREATE TABLE
postgres=# \d timestamp_test;
         Table "public.timestamp_test"
 Column |           Type           | Modifiers 
--------+--------------------------+-----------
 a      | timestamp with time zone | 
 b      | timestamp with time zone | 
```

According to the docs both `TIMESTAMP` and `TIMESTAMP WITH TIME ZONE` are both 8 bytes and have the same range, so there doesn't appear to be room for a timestamp to actually be stored anywhere.

**Comment by paperstreet** [comment]
Fascinating. There is a difference in storage size between TIME and TIME WITH TIME ZONE but not for TIMESTAMP: http://www.postgresql.org/docs/9.5/static/datatype-datetime.html

**Comment by dt** [comment]
Just to clarify, I meant that adding just the data type we can cast to/from named `timestamptz` was a different question than adding the `WITH TIME ZONE` support to the column type, not that column types `timestamptz` and `timestamp with time zone` were different -- agreed those appear identical.
