### ISSUE TITLE
sql: add rows/bytes written flow statistics

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#58655]
Add a new statistic that parallels `RowsRead` and `BytesRead`, called `RowsWritten` and `BytesWritten`, that is emitted by the various mutation `planNode`s.

This might be slightly less than straightforward because `planNode` has no builtin mechanism to return distsql metadata, which is the way that the statistics are propagated.

**Comment by jordanlewis** [comment]
Could be good for Barry.

**Comment by maryliag** [comment]
Addressed on https://github.com/cockroachdb/cockroach/pull/70593
