### ISSUE TITLE
CLI: Demo's link to the DB console doesn't work in with --insecure

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#58661]
If you use demo with --insecure on master `~/go/src/github.com/cockroachdb/cockroach$ ./cockroach demo movr --nodes 9 --insecure --with-load` you cannot access the DB Console:
<img width="688" alt="Screen Shot 2021-01-08 at 1 18 10 PM" src="https://user-images.githubusercontent.com/22278911/104050049-fa950c80-51b3-11eb-897e-541194636c3e.png">
<img width="878" alt="Screen Shot 2021-01-08 at 1 18 03 PM" src="https://user-images.githubusercontent.com/22278911/104050051-fa950c80-51b3-11eb-9fa5-c2088567ec68.png">

However, if you remove the --insecure, you can access the db console.

**Comment by knz** [comment]
The `--insecure` flag being discouraged / deprecated, I think this is low priority
