### ISSUE TITLE
descpb: move `privilege.Kind` to a proto enum to solidify value immutability

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#58675]
**Describe the problem**

The values of `privilege.Kind` really must never change. They become bit masks and are really important to not change. It's too easy to just add a new value. We should map the current values into `descpb`.

https://github.com/cockroachdb/cockroach/blob/5b0e79fc630df644592f0a72a112443d1bf78cea/pkg/sql/privilege/privilege.go#L25-L43

**Comment by RichardJCai** [comment]
I did a search through the code, I think roleoptions is the only other case where a go enum is actually encoded as a bitfield.

Created issue here: https://github.com/cockroachdb/cockroach/issues/65147

**Comment by ajwerner** [comment]
@sajjadrizvi had the fine idea of just assigning the values in the cost block and nixing `iota`. I'm cool with that too.

**Comment by RichardJCai** [comment]
> @sajjadrizvi had the fine idea of just assigning the values in the cost block and nixing `iota`. I'm cool with that too.

Oops should have considered this before https://github.com/cockroachdb/cockroach/pull/65145/files 
I don't see much value in having the proto enum over the golang enum with assigning values so I'll just do that instead unless you think otherwise.

**Comment by ajwerner** [comment]
> > @sajjadrizvi had the fine idea of just assigning the values in the cost block and nixing `iota`. I'm cool with that too.
> 
> Oops should have considered this before https://github.com/cockroachdb/cockroach/pull/65145/files
> I don't see much value in having the proto enum over the golang enum with assigning values so I'll just do that instead unless you think otherwise.

SGTM
