### ISSUE TITLE
CHANGES.txt would be nice for new features and bug fixes

### ISSUE THREAD

**Issue by JackKrupansky** [cockroachdb/cockroach#5869]
Now that CockroachDB has reached some level of stability and an actual public (Beta) release, it would be nice to have a traditional CHANGES.txt file to alert people to the specifics of new features and bug fixes since the previous formal release.

Or maybe this could be queried dynamically from GitHub somehow, presuming that issues could be tagged as to bug fix vs. new feature, improvement, performance optimization, etc.

**Comment by petermattis** [comment]
My current plan is to put the release notes on https://github.com/cockroachdb/cockroach/releases. Using a `CHANGES.txt` file feels very old school.

**Comment by ddorian** [comment]
You could use something like https://pypi.python.org/pypi/gitchangelog to generate the changes.txt.

**Comment by petermattis** [comment]
For the time being we're going with manually generated release notes: https://www.cockroachlabs.com/docs/beta-20160407.html.
