### ISSUE TITLE
Implemention of Redis Like Datastructures

### ISSUE THREAD

**Issue by pyros2097** [cockroachdb/cockroach#587]
Any ideas on how I can implement redis datastructures like llist, zset, set, hash over cockroach like [nodb](https://github.com/lunny/nodb) which is implemented over rocksdb?

Should I directly use the package storage or storage/engine or would it be better to use the http/ protobuf/json layer to do this?

Any any tips on creating a nodejs client would also be helpful.

**Comment by spencerkimball** [comment]
You'd use the cockroach client, which provides access to the underlying transactional key value store. So given a cockroach client, you'd implement them in exactly the same way nodb does it.

We were just discussing a redis API for Cockroach. Redis data structures really have a high impedance match for application developers.

We are planning to implement a nodejs client in the near term.

**Comment by mjibson** [comment]
I've been working on implementing the Redis protocol in Cockroach:

https://github.com/mjibson/cockroach/tree/redis

zset is the next big feature it'll get, I believe.

**Comment by pyros2097** [comment]
Nice! Now I can haz highly scalable and consistent leaderboards. Right now we are doing it in sql.

**Comment by mjibson** [comment]
If you are waiting on support for a specific command, please open an issue in that repo (https://github.com/mjibson/cockroach/issues) and I'll update it when added.

**Comment by pyros2097** [comment]
It seems https://github.com/tidwall/summitdb has implemented the Redis protocol with strong consistency. Since my main need to implement this in Cockroach was for strong consistency I've decided to use that instead.

**Comment by tschottdorf** [comment]
@pyros2097 regarding correctness, you may want to subscribe to https://github.com/tidwall/summitdb/issues/5 (though perhaps it's all being handled and I just didn't see it).
