### ISSUE TITLE
*: spans that are never explicitly Finish()-ed

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#58721]
Consider the following two examples (there may be others, will need to audit more thoroughly):
 https://github.com/cockroachdb/cockroach/blob/91a0898eab3946f8c1fcd4c1f30c1bb5965430d2/pkg/sql/conn_executor_exec.go#L633-L639

https://github.com/cockroachdb/cockroach/blob/91a0898eab3946f8c1fcd4c1f30c1bb5965430d2/pkg/sql/colflow/vectorized_flow.go#L949

The created spans are never explicitly Finish()-ed. This may pose to be a problem with always-on tracing (https://github.com/cockroachdb/cockroach/issues/55592), where un-Finish()-ed spans take up room in an in-memory registry of active spans (https://github.com/cockroachdb/cockroach/pull/58490). This is a tracking issue to refer to as we fix these.

**Comment by tbg** [comment]
I'm not sure they aren't explicitly finished, but it's possible. In some of the SQL code it isn't obvious when the spans are closed as they are tied to the connection. That said - I'd be surprised if there weren't any leaks. We should be able to find them easily after @angelapwen's starter project https://github.com/cockroachdb/cockroach/issues/55733.

**Comment by tbg** [comment]
https://github.com/cockroachdb/cockroach/issues/34313 is related. @irfansharif is fixing these (SQL) spans on our plate? I would have assumed SQL execution.

**Comment by asubiotto** [comment]
Is this different from #59315?

**Comment by irfansharif** [comment]
#59315 should be the last of it I think. The only other issue I'm aware of was https://github.com/cockroachdb/cockroach/pull/61279, but there's a PR out there already. I'll close it out.
