### ISSUE TITLE
sql: Add telemetry for pg_catalog queries

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/cockroach#58732]
Today, we have unimplemented telemetry for missing `pg_catalog` tables. After #58001, missing tables will be created as empty tables. Therefore, unimplemented telemetry will no longer capture access to `pg_catalog` tables that are empty and unsupported.

We need to add features telemetry for when `pg_catalog` tables are queried to replace the unimplemented telemetry and help with future implementation prioritization. Ideally, these metrics could use a shared prefix Ex. `pg_catalog`

**Comment by rafiss** [comment]
@vy-ton the telemetry will be under names like ` sql.schema.get_virtual_table.pg_catalog.pg_cast` (sql.schema.get_virtual_table.SCHEMA.TABLE)

**Comment by vy-ton** [comment]
@rafiss We discussed that this covers `information_schema`. Does it also include `crdb_internal`?

**Comment by mnovelodou** [comment]
> @rafiss We discussed that this covers `information_schema`. Does it also include `crdb_internal`?

@vy-ton this only covers pg_catalog and information_schema, but we can discuss if we add crdb_internal
