### ISSUE TITLE
lastval(): lastval is not yet defined in this session, but it should be!

### ISSUE THREAD

**Issue by fiatjaf** [cockroachdb/cockroach#58751]
**Describe the problem**

After entering a row in a table with a `SERIAL` or `BIGSERIAL` columns, I can't get `SELECT lastval()`.

**To Reproduce**

1. Start a local database for testing with 
    ```
    cockroach start-single-node -store=node1/ --insecure --http-addr=localhost:22600
    ```
2. Connect with `psql`:
    ```
    psql 'postgresql://root@localhost:26257?sslmode=disable'
    ```
3. Run these:
    ```
    psql (12.3, server 9.5.0)

    root=# create database test;
    CREATE DATABASE
    root=# \c test
    psql (12.3, server 9.5.0)
    You are now connected to database "test" as user "root".
    test=# create table t ( id bigserial, note text );
    CREATE TABLE
    test=# insert into t (note) values ('lalala');
    INSERT 0 1
    test=# select lastval();
    ERROR:  lastval(): lastval is not yet defined in this session
    ```

**Expected behavior**

It should return a the `id` for the newly inserted row.

**Environment:**
 - CockroachDB: CCL v20.2.3 @ 2020/12/14 18:33:39 (go1.13.14)
 - Server OS: Archlinux
 - Client app: psql

**Comment by rafiss** [comment]
@fiatjaf It looks like you found an answer in the forum: https://forum.cockroachlabs.com/t/lastval-lastval-is-not-yet-defined-in-this-session-but-it-should-be/4202

So I'll close this. Let us know if there's anything else!
