### ISSUE TITLE
kv: Investigate not specifying RangeID on post-split requests

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#5880]
The `Stores` struct currently supports the ability to [lookup a replica](https://github.com/cockroachdb/cockroach/blob/master/storage/stores.go#L184) for a given key when a RangeID is [not included](https://github.com/cockroachdb/cockroach/blob/master/storage/stores.go#L132) in a `BatchRequest`. However, this is currently only ever used in tests. 

We should look into if we can take advantage of this behavior when a split is detected. In practice, this would mean that `DistSender` would not specify a RangeID on `BatchRequest` where an initial range miss is inferred as a split. Instead it should send to the same `Node` as the missed `Range` and have the store discover the correct new `Range`, which it will include in the `BatchResponse` so that the `RangeCache` could be corrected. This is possible because a replica will split in-place, so there is a very high likelyhood that when a split is detected, the new range will be on the same store as the old range.

An alternative would be for `Store` to "catch" `RangeKeyMismatchError`s and perform a best-effort RangeLookup before returning the error.

**Comment by tschottdorf** [comment]
My initial suggestion was actually to look at `RangeKeyMismatchError` in `*Stores` and to re-send the request to the correct (post-split) range if it is entirely contained. That should be much easier.

**Comment by bdarnell** [comment]
I've never liked `Stores.lookupReplica` as a test-only hack. I've been inclined to get rid of it and require that tests always fill in the `RangeID` just like real requests, although going the other direction and using it in prod could work too. 

If we do this, then the `RangeID` in the request header is really just a hint/optimization and we could even consider removing it. (it's probably worth including it but we may want to try a benchmark where we always look up the replica by key).

One way to mitigate the problem of stale replicas without adding a creation timestamp and heuristics would be to only return the range descriptor if we know the leader for that range.
