### ISSUE TITLE
sql,server: cache password hashes and user info using a leasing protocol

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#58869]
**Is your feature request related to a problem? Please describe.**

Today, authenticating a new connection requires reading the password hash (and performing hashing). In global clusters this requires at least one RTT on average. See `GetUserHashedPassword`, which reads from both `system.users` and `system.role_options`.

**Describe the solution you'd like**

For role membership, we currently utilize a cache. The way this cache works is that changes to role memberships increment the version of that table descriptor. Those changes then wait for the old version to drain. This is a critical performance improvement. We could do exactly the same thing for password hashes. 

**Describe alternatives you've considered**

https://github.com/cockroachdb/cockroach/issues/58497 proposed using follower reads which both does not guarantee a local read and exposes weird stale reads.

Epic CRDB-7217

**Comment by rafiss** [comment]
seems related to #36160

**Comment by knz** [comment]
More general proposal: #44134

the issue with a node-local cache is that a node that hasn't seen a SQL user yet will block even if another node has a cached entry.

**Comment by ajwerner** [comment]
https://github.com/cockroachdb/cockroach/pull/44134 has different tradeoffs. It provides increased availability at operational cost. I see both as valuable.

**Comment by knz** [comment]
Agreed both are valuable

**Comment by lunevalex** [comment]
Could switching these queries to use follower reads help prevent this? We would have to do this #57992 but it seems plausible.

**Comment by lunevalex** [comment]
Looks like this was discussed here #58497, ignore my comment.
