### ISSUE TITLE
sql: Add SQL command to view existing interleaved and cross database reference usage

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/cockroach#58867]
Before interleaved tables/indexes and cross-database references are no longer supported, users should be able to query for existing usage from SQL in 21.1. This can be a new `SHOW` command

**Comment by vy-ton** [comment]
@jordanlewis @lucy-zhang Can we get this for 21.1?

**Comment by vy-ton** [comment]
Thinking more, I think a crdb_internal table makes more sense than a `SHOW` command.

**Comment by lucy-zhang** [comment]
How do you see this table being used? Any thoughts on what its schema should be and how structured the data should be? I know we've talked about this being displayed in the DB console, but is the output primarily meant to be read by human operators or processed in some automated way?

If it's meant to be read by human operators, on one end of the spectrum I could imagine having a `crdb_internal` table for deprecation warnings in general, where we just display textual error messages and maybe have a column for a list of descriptor IDs. If we have more structure in the table schema, we'll end up with new virtual tables that are extremely specific to this one deprecation cycle, but maybe that's fine.

**Comment by vy-ton** [comment]
We won't have DB console integration for 21.1, so the output should be human-readable.

> I could imagine having a crdb_internal table for deprecation warnings in general

This could make sense since we have multiple deprecations. On the other hand, these feature removals have a deadline, so a specific table schema that we eventually remove is where I'm leaning. Also might allow us to display richer info specific to each feature being deprecated (Ex. for cross-database refs the referenced db not just the descriptor ID)

**Comment by vy-ton** [comment]
For interleaved tables, `crdb_internal` table should include

- `schema_name`
- `table_name`
- `parent_table`

For interleave indexes, `crdb_internal` table should include

- `table_name`
- `index_name`
- `parent_index`

For cross-database references, `crdb_internal` table should include

- `object_name` - qualified name with database and schema
- `referenced_object_name` - qualified name with database and schema
- `cross_database_reference_description`
