### ISSUE TITLE
Roachprod dns sync failure

### ISSUE THREAD

**Issue by chriscasano** [cockroachdb/cockroach#58905]
Roachprod doesn't appear to be sync'ing DNS entries properly.  I built it from master today after getting this error with an older build.  I still get the same issue.  I checked and roachprod is not creating the dns.bind115033230 file in my local .roachprod directory to kick off this `glcoud dns record-sets` command.  Below is the error I'm getting and noticed others in our slack `#dev-inf` channel are getting it as well. 

```
22:31 $ roachprod sync
Syncing...
Refreshing DNS entries...
failed to update roachprod.crdb.io DNS: Command: gcloud [--project cockroach-shared dns record-sets import -z roachprod --delete-all-existing --zone-file-format /Users/chriscasano/.roachprod/dns.bind115033230]
Output: ERROR: gcloud crashed (AttributeError): 'SyntaxError' object has no attribute 'message'
If you would like to report this issue, please run the following command:
  gcloud feedback
To check gcloud for common problems, please run the following command:
  gcloud info --run-diagnostics
```

**Comment by jlinder** [comment]
Note, this was also reported [in slack](also reported in #dev-inf https://cockroachlabs.slack.com/archives/CJ0H8Q97C/p1610468215005100)

**Comment by rail** [comment]
@chriscasano I've been poking around this issue, but still unable to reproduce this. Do you have any idea when this happens?

>I checked and roachprod is not creating the dns.bind115033230 file in my local .roachprod directory to kick off this `glcoud dns record-sets` command.

`roachprod` tries hard to delete that file after the command above is ran. Maybe the case is that you just don't see it left there.

> Output: ERROR: gcloud crashed (AttributeError): 'SyntaxError' object has no attribute 'message'

Can you report the version of `gcloud` you use? `gcloud --version` should be enough. 

Something tells me that `roachprod` generates a zone file with some issues, that throws that `SytaxError` exception. We can add additional logging to make debugging easier.

Thank you in advance!

**Comment by chriscasano** [comment]
i can’t reproduce it either now.  eventually the problem went away.  i didn’t use roachprod for a few days, came back and tried running roachprod sync and it worked.  i wonder if something was off with gcloud dns file creation.  Even if i deleted the .bind file, I think it was recreating it with the same error.  Here are some of the outputs you requested:

✔ ~/Repos/cockroach-demo [master|✚ 5…88]
10:12 $ roachprod sync
Syncing...
Refreshing DNS entries...
✔ ~/Repos/cockroach-demo [master|✚ 5…88]
21:24 $ gcloud --version
Google Cloud SDK 323.0.0
beta 2021.01.08
bq 2.0.64
core 2021.01.08
gsutil 4.57

Thanks for looking into it.  Althought its no longer a problem for me.

**Comment by rail** [comment]
I wonder if for some reason it generated a bad zone file and that caused the failure. Let me play with a fake file and see how it behaves.

Also pasting another error message from slack:
```
Creating cluster chrisc-test with 6 nodes
Syncing...
Refreshing DNS entries...
failed to update roachprod.crdb.io DNS: Command: gcloud [--project cockroach-shared dns record-sets import -z roachprod --delete-all-existing --zone-file-format /Users/chriscasano/.roachprod/dns.bind566615204]
Output: ERROR: (gcloud.dns.record-sets.import) Unable to read record-sets from specified records-file [/Users/chriscasano/.roachprod/dns.bind566615204] because [<file>:22: expecting an identifier]: exit status 1
```

**Comment by rail** [comment]
I played with the zone file and managed to get the `SyntaxError` exception \o/. It sounds like in some cases `roachprod` generates a bad zone file. I'm going to add the generated file contents to the error, so we can track down the case, when this happens.

**Comment by rail** [comment]
FTR, #59800 should give us more information about the failure in the future. I putting this issue on hold until this happens. It would be also useful to get the output of `roachprod list`.

**Comment by rail** [comment]
Looks like I found the issue. Thanks [Andrew Werner](https://cockroachlabs.slack.com/archives/CJ0H8Q97C/p1613687899199700)!

In some cases we generate malformed DNS zone files because some VMs don't have a public IP assigned yet (being created or destroyed). Let's skip them!
