### ISSUE TITLE
kvserver: diskSideloadedStorage.TruncateTo can cause spurious errors

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#58948]
**Describe the problem**

We [saw](https://cockroachlabs.slack.com/archives/C0KB9Q03D/p1610484229007200) the following errors in logs during `make bench`:

```
E210112 19:54:19.158760 38559 kv/kvserver/queue.go:1087  [n2,raftlog,s2,r56/2:/Table/54/{2/"dataâ€¦-3}] recomputing raft log size: while purging "auxiliary/sideloading/r0XXXX/r56": file already exists
E210112 19:54:19.292477 38653 kv/kvserver/queue.go:1087  [n2,raftlog,s2,r56/2:/Table/54/{2/"dataâ€¦-3}] recomputing raft log size: while purging "auxiliary/sideloading/r0XXXX/r56": file already exists
E210112 19:54:19.691621 6955 kv/kvserver/replica_application_result.go:282  [n2,s2,r42/2:/{Table/54/3-Max}] while removing sideloaded files during log truncation: while purging "auxiliary/sideloading/r0XXXX/r42": file already exists
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*diskSideloadStorage).TruncateTo
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_sideload_disk.go:241
[...]
```

This indicates an error from `eng.RemoveDir` here:

https://github.com/cockroachdb/cockroach/blob/19951d2ad7a8eb3c20c38c6e55e1414549d1850f/pkg/kv/kvserver/replica_sideload_disk.go#L236-L243

The error message is misleading due to a bug in pebble that was fixed today. The error is really that the directory is not empty.

The code attempts to invoke `RemoveDir` only if it believes that it has deleted all files (there is no concurrent access to the directory here since access always happens under `raftMu`). However, this isn't true: note how

https://github.com/cockroachdb/cockroach/blob/19951d2ad7a8eb3c20c38c6e55e1414549d1850f/pkg/kv/kvserver/replica_sideload_disk.go#L247-L270

globs for files matching a pattern. Perhaps we are writing files that do not match this pattern in some cases. In that case, we could erroneously see no files (the raft log size case above passes `firstIndex==0` and so would definitely not try to delete the directory if any sideloaded SST was present)

However, the only other write to these directories that I am aware of is here:

https://github.com/cockroachdb/cockroach/blob/ef645191867f2ba4d80083f1dae0b9ba1b805277/pkg/kv/kvserver/replica_proposal.go#L509-L516

and it looks like it should be handled correctly (exactly like the file without the .ingested suffix).

**To Reproduce**

Run `BenchmarkUserfileImport` (presumably). If the error is reproducible, we should dump a listing of the directory with the error to understand what the unexpected file is.

**Expected behavior**

The sideloaded storage should have the full authority over the directory. No other files should be placed in it, and so this (harmless) error should not occur.

**Additional data / screenshots**

**Environment:**

**Additional context**

**Comment by RaduBerinde** [comment]
I think https://github.com/cockroachdb/cockroach/issues/59126 might be the same issue. I see repeated CI failures due to timeouts in this benchmark.
