### ISSUE TITLE
sql: pg_catalog.pg_index has bad indoption values for indexes with implicit columns

### ISSUE THREAD

**Issue by postamar** [cockroachdb/cockroach#58945]
**Describe the problem**

I've noticed quite coincidentally that the `pgCatalogIndexTable` appeared to use the wrong offset when looking up the index column direction here: https://github.com/cockroachdb/cockroach/blob/5ebf991785db473d78e8d96e54f761486f99e93b/pkg/sql/pg_catalog.go#L1476
This is specifically the case when `i` does not begin looping at `0` here: https://github.com/cockroachdb/cockroach/blob/5ebf991785db473d78e8d96e54f761486f99e93b/pkg/sql/pg_catalog.go#L1451

**To Reproduce**

This can be reproduced in a logic test.
```diff
diff --git a/pkg/sql/logictest/testdata/logic_test/pg_catalog b/pkg/sql/logictest/testdata/logic_test/pg_catalog
index 5e64a21e20..d4557bc38c 100644
--- a/pkg/sql/logictest/testdata/logic_test/pg_catalog
+++ b/pkg/sql/logictest/testdata/logic_test/pg_catalog
@@ -2932,3 +2932,22 @@ SELECT tablename FROM pg_catalog.pg_tables
 
 statement ok
 SET DATABASE = test;
+
+subtest indoption_bug
+
+statement ok
+SET experimental_enable_hash_sharded_indexes = true
+
+statement ok
+CREATE TABLE t_hash (a INT);
+
+statement ok
+CREATE INDEX a_hash ON t_hash (a DESC) USING HASH WITH BUCKET_COUNT=8;
+
+query T colnames
+SELECT indoption
+FROM pg_catalog.pg_index
+WHERE indexrelid IN (SELECT crdb_oid FROM pg_catalog.pg_indexes WHERE indexname = 'a_hash')
+----
+indoption
+1
```

**Additional context**

Not sure what the impact is here but this does seem quite minor. From what I could tell from the postgres documentation [1] the values in this column in pg_catalog depend on the 'index access method' which I take it means whatever we say it means.

[1] https://www.postgresql.org/docs/current/catalog-pg-index.html

**Comment by rafiss** [comment]
@postamar Nice find! Yeah the PG docs are kinda opaque, but these columns do get used by ORMs and other tools.

A better description of what the values are is here: #42343 and #42175

> The LSB is set if the column is in descending order in the index, and the 2nd-most-LSB is set if the column has nulls appearing first in the index.
> 
> Because of the current lack of support for custom null ordering, this means the only two valid values of this bitfield are 0b10 and 0b01.
