### ISSUE TITLE
server: debug zip contains duplicate file?

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#58969]
<img width="490" alt="Screen Shot 2021-01-13 at 3 48 21 PM" src="https://user-images.githubusercontent.com/15615/104508809-c4da9400-55b6-11eb-86ce-7ec51ab451c2.png">

```
$ unzip 3rq-1610498679-debug.zip
Archive:  3rq-1610498679-debug.zip
  inflating: debug/events.json
  inflating: debug/rangelog.json
  inflating: debug/liveness.json
  inflating: debug/settings.json
  inflating: debug/reports/problemranges.json
  inflating: debug/crdb_internal.cluster_queries.txt
  inflating: debug/crdb_internal.cluster_sessions.txt
  inflating: debug/crdb_internal.cluster_settings.txt
  inflating: debug/crdb_internal.cluster_transactions.txt
  inflating: debug/crdb_internal.jobs.txt
  inflating: debug/system.jobs.txt
  inflating: debug/system.descriptor.txt
  inflating: debug/system.namespace.txt
  inflating: debug/system.namespace2.txt
  inflating: debug/crdb_internal.kv_node_status.txt
  inflating: debug/crdb_internal.kv_store_status.txt
  inflating: debug/crdb_internal.schema_changes.txt
  inflating: debug/crdb_internal.partitions.txt
  inflating: debug/crdb_internal.zones.txt
  inflating: debug/nodes.json
replace debug/liveness.json? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
```

**Comment by knz** [comment]
Fixed by #50621 I think

@dt which version did you encounter this with?  Which `cockroach` executable version was used to generate the zip file?

**Comment by dt** [comment]
Just got a debug.zip from cockroach cloud that still exhibits this. looks like the node was v20.1.12. cc @joshimhoff I don't know what client version was used to collect it.

**Comment by knz** [comment]
This was fixed in 20.2 but I'm not sure if was back ported to 20.1.

Anyway we should be clear that it's always ok to use next version of the client to generate the zip. The 20.2 executable would not have had this problem

**Comment by joshimhoff** [comment]
If the way the take zip automation works is we exec into a CRDB pod to take it, then the client version used is the server version. CC @chrisseto who wrote the take zip automation.

**Comment by knz** [comment]
I think it's fine. Anyway the duplicate file is not a big issue. The `unzip` command in a terminal session would work fine even if OSX's Finder gets confused.

I suggest we close this issue unless @dt you find the inconvenience so large that you'd be interested to issue the backport for the relevant PR.
