### ISSUE TITLE
sql: add follower reads to EXPLAIN/EXPLAIN ANALYZE

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#58963]
Currently, follower reads are serviced via a cluster setting and a function. In an upcoming release, we will allow for certain connections to entirely serve follower reads. In those connections, it's not possible to tell if the read was executed as a follower read other than be inferring it via the latency. We should add if a statement was served as a follower read to EXPLAIN/EXPLAIN ANALYZE. 

cc @nvanbenschoten and @RaduBerinde 

Epic CRDB-9025

Jira issue: CRDB-3352

**Comment by awoods187** [comment]
@Annebirzin also we will need to add this to the statement details page so someone can tell if it a statement was executed as a follower read or not

**Comment by asubiotto** [comment]
We need to figure out how hard this would be. If it's easy, would be a high value thing to add during stability period.

**Comment by maryliag** [comment]
No longer a priority
