### ISSUE TITLE
multi-region: Build multi-region test plan for SQL Experience

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#58977]
Build a comprehensive test plan for the multi-region simplification work.

**Comment by awoods187** [comment]
We should also include clusters that start in 20.2 with and without geo-partitioning, duplicate indexes, and the other existing patterns. We likely will want to gate all changes until the cluster is finalized but we should definitely introduce schema changes before the upgrade, during the upgrade, and after as well.

**Comment by ajstorm** [comment]
Out for review: https://docs.google.com/document/d/1q3i5B7GawoPVel6OBoJcDLNZRY0UaGDo6dKWrrkJE7I/edit
