### ISSUE TITLE
sql/parser: consider removing Datum.IsMax and Datum.IsMin

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#5897]
Then make HasNext and HasPrev depend on the value of the datum (not just the type as is currently the case) and use them to indicate whether Next and Prev can be called.

The motivation for this is DInterval, which always returns false for HasNext and HasPrev, but wouldn't need to with this change. All the other Datum types have one "band" in which IsMax and IsMin indicate whether Next and Prev may be called, but DInterval has many (though only one min and max).

**Comment by paperstreet** [comment]
cc @RaduBerinde

**Comment by jordanlewis** [comment]
I'm going to close this 2 year old issue, unless @danhhz objects. I'm not sure how badly this is biting us but it doesn't seem that big of a deal.

**Comment by danhhz** [comment]
No objection
