### ISSUE TITLE
sql: users can alter table/schema/database owner to current owner without privileges

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#58975]
This is a super minor issue but we moved some logic around causing users without privilege to ALTER OWNER to the current owner. Doesn't actually do anything since they can only change the owner to the current owner but nevertheless a small inconsistency.

In alter_table.go, we don't do the check privileges if the current owner is the same.

```
// If the owner we want to set to is the current owner, do a no-op.
if newOwner == privs.Owner() {
return nil
}

if err := p.checkCanAlterSchemaAndSetNewOwner(ctx, scDesc, newOwner); err != nil {
return err
}
```

In PG this scenario fails whereas in CRDB right now it passes.

On user1
```
rcai=# create table t();
```

On user2
```
rcai=> alter table t owner to user;
ERROR:  must be owner of table t
```

**Comment by adzimzf** [comment]
Hi,
I'd like to try work on this

**Comment by RichardJCai** [comment]
> Hi,
> I'd like to try work on this

Absolutely, go ahead!

**Comment by adzimzf** [comment]
Hi @RichardJCai ,
is this issue still valid? I tried it and it already works as psql (without any changes), or do I miss something how to test it?

**Comment by RichardJCai** [comment]
> Hi @RichardJCai ,
> is this issue still valid? I tried it and it already works as psql (without any changes), or do I miss something how to test it?

Yep this is still valid, see this example:

```
➜  cockroach git:(master) ✗ ./cockroach sql --insecure --host=localhost:26257 --user test
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
# Server version: CockroachDB CCL v21.1.0-alpha.1-1196-g81b3bb9ae1 (x86_64-apple-darwin19.6.0, built 2021/01/26 16:05:49, go1.15.6) (same version as client)
# Cluster ID: b0217203-d848-4e43-bb89-72f2a75f30d0
#
# Enter \? for a brief introduction.
#
test@localhost:26257/defaultdb> alter table t owner to test;
ERROR: must be owner of table t
SQLSTATE: 42501
test@localhost:26257/defaultdb> alter table t owner to root;
ALTER TABLE OWNER

Time: 1ms total (execution 1ms / network 0ms)

test@localhost:26257/defaultdb>
```

test should not have privilege to alter the table which is correctly reflected in the first statement.
However, when altering the owner to the current owner (which in this case is root), there is no error.

**Comment by mneverov** [comment]
Hi @adzimzf are you working on it? May I take a look?
