### ISSUE TITLE
logging: avoid severity-based filtering of structured events

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#58993]
This issue stems from UX surprise in #58970, where a user was surprised to see that a severity filter on unstructured entries was also applied to structured events, and preventing them altogether.

(This is because today structured entries are emitted at severity INFO and then filtering applies to them in the same way as unstructured entries)

A possible way to improve UX here could be either of these options:

1. state that the "severity" field only applies to unstructured entries, and therefore that severity-based filtering is only relevant to unstructured entries
2. change the filtering feature to only apply to unstructured entries

These two choices seem similar to each other but really are not. Choice (1) essentially says that *structured entries have no severity*.  This would entail ensuring that the first character of each log line for a structured entry gets a new character besides I/W/E/F, for example "S"?

In contrast in choice (2)  we keep the severity but always include structured entries in log sinks regardless of severity. In that choice, we probably want to accompany the change with another way to filter structured entries; see #57878 for a suggestion.

It makes sense though, because the severity field is really a way to "add structure" to the payloads that are otherwise unstructured. Since structured payloads already have structure, it's not so clear we need to add more via the severity field.

**Comment by knz** [comment]
cc @thtruo @piyush-singh for evaluation & triage

**Comment by knz** [comment]
Related to issue #57878

**Comment by knz** [comment]
A counterpoint to this entire discussion, a possible choice (3) 

3. remove filtering options entirely from the log configuration, so that log sinks always include all severity levels. If a user wants to filter things, they can use Fluent and add filtering in their Fluent configuration.

**Comment by piyush-singh** [comment]
I am actually happy with how the functionality works now - to me it makes sense that both sets of events would be filtered. It was purely user error on my part that led to me accidentally filtering INFO level events from the SESSIONS and USER_ADMIN channels. I'd be okay closing this issue - will defer to Tommy on the UX though

**Comment by thtruo** [comment]
+1. As a user, it makes sense that both types of events get filtered for severity levels. 

My concern with either option 1 or 2 is that now users need to consider in their mental model whether they care about unstructured or structured events. It's simpler to treat them as just events. Option 3 is something we can vet with other users. 

For now, I'm okay closing this issue as well.
