### ISSUE TITLE
Admin App Selector on Statement page overflows

### ISSUE THREAD

**Issue by bladefist** [cockroachdb/cockroach#59000]
On this app selector/dropdown, we have many, so it overflows and doesn't scroll, meaning you can't select apps not visible.  Also would be nice if it was sorted alphabetically.  

![image](https://user-images.githubusercontent.com/1520456/104612475-da4dcd80-564b-11eb-95c8-229d48bb4b7e.png)

**Comment by awoods187** [comment]
This is related to https://github.com/cockroachdb/cockroach/issues/59001 cc @thtruo

**Comment by nathanstilwell** [comment]
fixed by #59603
