### ISSUE TITLE
ui: truncate long statements throughout the db console

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#59001]
Some SQL statements are longer than others. In the DB console, we are inconsistent in truncating long SQL statements making it hard for developers to use various pages. We should audit the pages which contain SQL statements and make sure that their length does not change the components or visual display. This includes the sessions, transactions, statements, statement details, and plan pages among others. 

cc @Annebirzin  we talked about this yesterday for statement details but it applies across the board

**Comment by awoods187** [comment]
cc @thtruo who i believe @timveil has talked to about this previously

**Comment by timveil** [comment]
want to note that this should not only apply to places where we display statements in table columns but also where we display statements in widgets like tooltips.  The only place where a statement should be displayed in all its glory is a dedicated page that has the real-estate to present it in a clean, well formatted manner.

**Comment by thtruo** [comment]
ack. tim did discuss and share his thoughts. the Observability team will address this in our upcoming sprint (starting next week). fyi we're tracking internally here ([jira](https://cockroachlabs.atlassian.net/browse/CRDB-2271))

**Comment by awoods187** [comment]
In addition to SQL statements, this also involves app name which can extend beyond the filter box.

**Comment by thtruo** [comment]
Ack - noted.

**Comment by awoods187** [comment]
Here's another example in the transactions page:
<img width="641" alt="Screen Shot 2021-02-08 at 9 58 49 AM" src="https://user-images.githubusercontent.com/22278911/107237063-54c40000-69f4-11eb-98a8-42338168f90a.png">
<img width="814" alt="Screen Shot 2021-02-08 at 9 58 37 AM" src="https://user-images.githubusercontent.com/22278911/107237071-57bef080-69f4-11eb-90d2-bc02cc2d37b2.png">

**Comment by thtruo** [comment]
heads up @timveil the team has merged in a fix (see https://github.com/cockroachdb/ui/pull/179 and https://github.com/cockroachdb/cockroach/pull/59603)

do you have any input on which version to backport this fix to? we could perhaps go back to the version a specific customer was on that ran into this issue. if so, mind sharing which version that was?

**Comment by timveil** [comment]
I don't believe a back port is required.  At least not based on my interactions.  I'd just get this out in the next latest patch.

**Comment by nathanstilwell** [comment]
fixed by #59603 and by cockroachdb/ui#179
