### ISSUE TITLE
sql: user defined type references in expressions are not tracked

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#59019]
**Describe the problem**

Cockroach tracks backreferences for user-defined types when they appear as the type for columns (or used in array or alias types). We do not, however, track them when they occur inside of expressions or view statements. For example:

Postgres:
```
postgres=# CREATE TYPE typ as ENUM ('a');
CREATE TYPE
postgres=# CREATE VIEW v AS (SELECT 'a'::typ < 'a'::typ);
CREATE VIEW
postgres=# SELECT * FROM v;
 ?column? 
----------
 f
(1 row)

postgres=# DROP TYPE typ CASCADE;
NOTICE:  drop cascades to view v
DROP TYPE
postgres=# SELECT * FROM v;
ERROR:  relation "v" does not exist
```

Cockroach:
```
demo@127.0.0.1:26257/db> CREATE TYPE typ AS ENUM('a');
CREATE TYPE
demo@127.0.0.1:26257/db> CREATE VIEW v AS (SELECT 'a'::typ < 'a'::typ);
CREATE VIEW
demo@127.0.0.1:26257/db> SELECT * FROM v;
  ?column?
------------
   false
(1 row)
demo@127.0.0.1:26257/db> DROP TYPE typ CASCADE;
ERROR: unimplemented: DROP TYPE CASCADE is not yet supported
SQLSTATE: 0A000
HINT: You have attempted to use a feature that is not yet implemented.
See: https://go.crdb.dev/issue-v/51480/v21.1
demo@127.0.0.1:26257/db> DROP TYPE typ RESTRICT;
DROP TYPE
demo@127.0.0.1:26257/db> SELECT * FROM v;
ERROR: type "sc.typ" does not exist
SQLSTATE: 42704
```

Relates to #51480.

**Comment by lucy-zhang** [comment]
Part of the problem here is that we seem to set the backreferences in some cases, but not all of them, right? This view with a different expression works correctly, unlike the above example:

```
demo@127.0.0.1:26257/defaultdb> CREATE TYPE typ AS ENUM('a');
CREATE TYPE
demo@127.0.0.1:26257/defaultdb> CREATE VIEW v AS SELECT 'a'::typ;
CREATE VIEW
demo@127.0.0.1:26257/defaultdb> SELECT * FROM v;
  typ
-------
  a
(1 row)
demo@127.0.0.1:26257/defaultdb> DROP TYPE typ;
ERROR: cannot drop type "typ" because other objects ([defaultdb.public.v]) still depend on it
SQLSTATE: 2BP01
```

**Comment by ajwerner** [comment]
Yeah, we add back references when any columns carry the type value of the enum. We don't add back references when the type is used in casts in exprs for columns or views.

**Comment by ajwerner** [comment]
@the-ericwang35 I'm thinking this may be a good project.

**Comment by vy-ton** [comment]
> Cockroach tracks backreferences for user-defined types when they appear as the type for columns (or used in array or alias types)

@ajwerner or @arulajmani What's an example of a UDT used in an alias type?
