### ISSUE TITLE
sql: DROP SCHEMA CASCADE breaks cross-schema TypeDescriptor references

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#59021]
**Describe the problem**

Currently, CRDB does not support `DROP TYPE CASCADE`, but we don't check for dependencies when the type is being dropped as part of a `DROP SCHEMA CASCADE`. This is problematic when the type is involved in a cross schema reference.

**To Reproduce**

```
demo@127.0.0.1:26257/movr> create schema sc;
CREATE SCHEMA

Time: 31ms total (execution 9ms / network 22ms)

demo@127.0.0.1:26257/movr> create type sc.abc as enum ('a', 'b', 'c');
CREATE TYPE

Time: 8ms total (execution 8ms / network 0ms)

demo@127.0.0.1:26257/movr> create table t(k INT PRIMARY KEY, a sc.abc);
CREATE TABLE

Time: 59ms total (execution 8ms / network 52ms)

demo@127.0.0.1:26257/movr> DROP SCHEMA sc;
ERROR: schema "sc" is not empty and CASCADE was not specified
SQLSTATE: 2BP01
demo@127.0.0.1:26257/movr> DROP SCHEMA sc CASCADE;
DROP SCHEMA

Time: 34ms total (execution 11ms / network 23ms)

demo@127.0.0.1:26257/movr> Insert into t values(1, 'a');
ERROR: type with ID 60 does not exist
SQLSTATE: 42704
```

**Expected behavior**
Similar to `DROP TYPE CASCADE`, the column that uses the enum being dropped should be dropped.

**Additional data / screenshots**
In the short term, when dropping a schema which contains types, we should ascertain that none of the types have cross schema references. If they exist, we should fail the `DROP SCHEMA CASCADE`, until the user manually removes the columns that use that type. 
In the long term, we should really be supporting `DROP TYPE CASCADE` : https://github.com/cockroachdb/cockroach/issues/51480

Related to: https://github.com/cockroachdb/cockroach/issues/51889

**Comment by jordanlewis** [comment]
Can we prevent `DROP SCHEMA CASCADE` for now if there are any user defined types in the schema at all, and force people to drop types themselves?

**Comment by ajwerner** [comment]
Wish I had seen this earlier. This seems very bad. I'll make a PR.
