### ISSUE TITLE
gossip: resolver.IsExhausted check is fragile

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#5902]
When trying to initially connect to the gossip network we loop over the bootstrap addresses and try to connect to each once. If we can't connect to one of the bootstrap addresses, we never retry. But this means a temporary situation, such as a connection timeout, will become a permanent failure to connect to the gossip network. Once #5901 goes on, this fragility can be seen in `make stress PKG=./gossip TESTS=TestConvergence`.

What is the purpose of `IsExhausted`? It isn't documented and its usage seems problematic.

**Comment by petermattis** [comment]
This fragility can easily be replicated on the command line. Start up a 2-node cluster by first starting up the second (non-bootstrap) node specifying the not-yet started first node for the `--join` flag. Wait for gossip to fail to connect then start the bootstrap node. The second node will never connect.

```
./cockroach start --store=cockroach-data/2 --join=localhost:26257 --port=26258 --http-port=8081 --logtostderr
```

Wait a few seconds and in another terminal:

```
./cockroach start --store=cockroach-data/1 --logtostderr
```

**Comment by spencerkimball** [comment]
`IsExhausted` is no longer necessary. https://github.com/petermattis/cockroach/commit/b6af9f4979a94befdd6fd8750add45ea8800275d should close this issue.
