### ISSUE TITLE
build/bazel: Revisit colexec implementation in Bazel

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#59053]
`pkg/sql/colexec/COLEXEC.bzl` looks a little janky, as evidenced by this comment:

```
            # `$@` lets us substitute in the output path[1]. The symlink below
            # is frowned upon for genrules[2]. That said, when testing
            # pkg/sql/colexec through bazel it expects to find the template
            # files in a path other than what SRCS would suggest. We haven't
            # really investigated why. For now lets just symlink the relevant
            # files into the "right" path within the bazel sandbox[3].
```

We should either arrive at a crisp understanding of why this hack doesn't matter, and why it won't interfere with any long-term goals (like remote execution), or we should fix the implementation so hacks like this aren't necessary. (I think that a better, more rigorous description of these rules and their dependencies is probably in order.

**Comment by irfansharif** [comment]
Done in https://github.com/cockroachdb/cockroach/pull/60702.
