### ISSUE TITLE
SHOW TABLES is failing in descriptor validation

### ISSUE THREAD

**Issue by glerchundi** [cockroachdb/cockroach#59050]
**Describe the problem**

Switch to a database that was supposed to be working and a `SHOW TABLES` statement failed:

```
root@:26257/mydb> SHOW TABLES;
ERROR: internal error: missing fk forward reference "installation_fk" to "installations" from "users"
SQLSTATE: XX000
DETAIL: stack trace:
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/structured.go:1519: validateCrossReferences()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/structured.go:1440: Validate()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/catalogkv/catalogkv.go:298: unwrapDescriptor()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/catalogkv/catalogkv.go:390: GetAllDescriptors()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:1545: GetAllDescriptors()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:1864: forEachTableDescWithTableLookupInternal()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:1825: forEachTableDescWithTableLookup()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/pg_catalog.go:1072: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:492: 1()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:115: func2()
/usr/local/go/src/runtime/asm_amd64.s:1357: goexit()

HINT: You have encountered an unexpected error.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.

We appreciate your feedback.
```

**To Reproduce**

TBD. I need to curate the database and its table schemas. I want to send this one early.

**Expected behavior**

`SHOW TABLES` failed, queries against specific or known tables still work but development flow was broken as we automatically generate the code from table definitions. As the `SHOW TABLES` fails our database design tool wasn't able to discover & show tables.

**Environment:**
 - CockroachDB version [e.g. 2.0.x]

```
$ cockroach sql --insecure
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
# Client version: CockroachDB CCL v20.2.3 (x86_64-apple-darwin14, built 2020/12/14 18:37:58, go1.13.14)
# Server version: CockroachDB CCL v20.2.1 (x86_64-apple-darwin14, built 2020/11/20 18:37:02, go1.13.14)
```

 - Server OS: [e.g. Linux/Distrib] **macOS**
 - Client app [e.g. `cockroach sql`, JDBC, ...] `cockroach` cli but seems to be failing in any other tool like TablePlus.

**Additional context**
What was the impact?

A broken development experience.

**Comment by rafiss** [comment]
cc @lucy-zhang

**Comment by lucy-zhang** [comment]
This is a bug that affects tables created in earlier versions of CRDB upon upgrading to 20.2, and was fixed by https://github.com/cockroachdb/cockroach/pull/57133 in v20.2.3. I see you're on client version v20.2.1, so upgrading should resolve the problem. I'll close this issue, but if you see further problems, let us know.

**Comment by glerchundi** [comment]
Thanks @lucy-zhang for the pointer, that was an easy one to solve! `brew update && brew upgrade`.
