### ISSUE TITLE
bazel: introduce a `bazel build` target in CI

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#59063]
All it could do is `bazel build //pkg/cmd/cockroach-short`. It would have helped catch regressions like #59052. (I'm not sure we can do this just yet, I'm not sure if we're able to build using bazel on linux).

**Comment by rickystewart** [comment]
Done (you'll see this now as "Github CI (Optional)").

**Comment by irfansharif** [comment]
Sweet! Thanks Ricky.

**Comment by rickystewart** [comment]
Not so fast. :p 

I had to turn this off. This is broken by #59224. I can adjust the build configuration to perform a `build/builder.sh bazel clean --expunge` as a cleanup step after the build, which does appear to fix it, but that seems risky to me... if that line of code doesn't get run for any reason or if we move to a different version of Bazel with slightly different behavior, then the Bazel build will start poisoning build agents again. I'll take the evening to think about it, I guess. Updating `build/builder.sh` in some way is probably the right solution, though I'm not immediately sure what change needs to be made.

**Comment by rickystewart** [comment]
Turned back on as of last Friday and no issues observed so far.
