### ISSUE TITLE
opt: exponential blow-up with join reordering and CommuteSemiJoin rule

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#59076]
The query in the test file below takes seconds to be optimized. We generate and reorder a lot of joins. If I disable the CommuteSemiJoin rule, the query is optimized in tens of ms.

We should investigate if we can incorporate CommuteSemiJoin into the join reordering algorithm, or disable reordering on the InnerJoin created by that rule.

Notably, if we replace the three inner-most LEFT JOIN with INNER JOIN, it runs much faster.

```
exec-ddl
CREATE TABLE a (
  a_id UUID PRIMARY KEY
);
----

exec-ddl
CREATE TABLE b (
  b_id UUID PRIMARY KEY
);
----


exec-ddl
CREATE TABLE c (
  c_id UUID PRIMARY KEY,
  a_id UUID NOT NULL
);
----


exec-ddl
CREATE TABLE d (
  d_id UUID PRIMARY KEY,
  c_id UUID NULL
);
----

exec-ddl
CREATE TABLE e (
  e_id UUID PRIMARY KEY,
  b_id UUID NULL,
  c_id UUID NULL
);
----

exec-ddl
CREATE TABLE f (
  f_id UUID PRIMARY KEY,
  b_id UUID NULL
);
----

exec-ddl
CREATE TABLE g (
  g_id UUID PRIMARY KEY,
  e_id UUID NULL
);
----

opt format=hide-all
SELECT * FROM
  c AS o
  LEFT JOIN d AS o0 ON o.c_id = o0.c_id
  INNER JOIN a AS c ON o.a_id = c.a_id
  LEFT JOIN (
      SELECT *
      FROM
        e AS o1
        LEFT JOIN b AS p ON o1.b_id = p.b_id
        LEFT JOIN f AS e ON p.b_id = e.b_id
        LEFT JOIN g AS o2 ON o1.e_id = o2.e_id
    )
      AS t ON o.c_id = t.c_id
WHERE
  (
    (
      (
        NOT
            EXISTS(
              SELECT 1 FROM
                e AS o3
              WHERE
                o.c_id = o3.c_id
            )
      )
      AND EXISTS(
          SELECT 1 FROM
            e AS o4 LEFT JOIN b AS p0 ON o4.b_id = p0.b_id
          WHERE
            o.c_id = o4.c_id
        )
    )
    AND EXISTS(
        SELECT 1 FROM
          e AS o5 LEFT JOIN b AS p1 ON o5.b_id = p1.b_id
        WHERE
          o.c_id = o5.c_id
      )
  )
  AND EXISTS(
      SELECT 1 FROM
        e AS o6 LEFT JOIN b AS p2 ON o6.b_id = p2.b_id
      WHERE
        o.c_id = o6.c_id
    )
----
```

**Comment by DrewKimball** [comment]
@RaduBerinde With regard to disabling reordering on the generated inner join, there's already a flag on JoinPrivate to prevent duplicate reordering. Having CommuteSemiJoin set the `WasReordered` flag seems to solve the problem (opt executes in ~15 ms). I can probably write up a patch to do this later today, but you're welcome to do it instead if you like.

**Comment by andy-kimball** [comment]
@DrewKimball, if that flag is set, would we possibly miss reorderings that we care about?

**Comment by DrewKimball** [comment]
That's a good question. Now that you mention it, it could miss possible orderings, particularly in the case when the `DistinctOn` added by `CommuteSemiJoin` can be removed.

**Comment by DrewKimball** [comment]
With regard to the query running faster when the left joins are replace by inner joins, it's because they are in the right input of a left join. A left join in the right input of a left join is associative, but the same is not true for an inner join. So, replacing with an inner join 'isolates' those three joins.
If you replace the fourth left join with an inner join too, the time increases even beyond that of the original query, since an inner join tree is permissible of more orderings.

**Comment by DrewKimball** [comment]
There's definitely something fishy going on here; when `CommuteSemiJoin` is disabled, `ReorderJoins` applies 16 times. When it's not disabled, `ReorderJoins` applies 1700 times, and 600 of those are at the limit of 8 joins...

**Comment by DrewKimball** [comment]
I'm pretty sure what's happening is this: first, `ReorderJoins` applies and creates a bunch of memo groups with semi joins. Then, `CommuteSemiJoin` applies on each semi join, creating new inner join memo groups on each application. Then, `ReorderJoins` applies to all the new inner join groups.

**Comment by andy-kimball** [comment]
But how come the new inner join expressions are not interned, and therefore only need to be explored once?

**Comment by DrewKimball** [comment]
Looks like the interner hashes the `WasReordered` flag. I'm now wondering whether that's the behavior we want. Also, I've found that preventing `CommuteSemiJoin` from matching when the `WasReordered` flag is set causes `ReorderJoins` to match a much more reasonable 20 times, which is in line with my earlier theory.

**Comment by andy-kimball** [comment]
Maybe we should instead have a `wasReordered` set in the shared `JoinOrderBuilder` where we keep track of whether a particular expression needs reordering, so we can sidestep any interning issues.

That said, I can see why interning of the `WasReordered` flag might cause some slowdown, but I don't see why it'd cause exponential blowup.

**Comment by DrewKimball** [comment]
Right, I don't think the interning is itself causing the blowup, though it might be contributing to the severity.

The process is this (I believe):
1) New joins are added to the semi join group during reordering. The 'JoinOrderBuilder' doesn't set the 'WasReordered' flag when it adds to a group, since it only ever matches on the first expression of a group.
2) `CommuteSemiJoin` matches on any new semi joins, and produces a new inner join group with the same join private (which still doesn't have the flag set).
3) Each new inner join group is reordered.

So, the solution might be to have `JoinOrderBuilder` set the flag when it is adding to a group as well. This would also prevent similar blowups from other rules beside `CommuteSemiJoin` that produce new join groups with the same private. I don't think this would miss orderings, since the new groups of the original semi joins would still be reordered as well. I suppose I'll want to find a smaller test case to verify this, since `memo` is pretty much unreadable with so many expressions.

**Comment by andy-kimball** [comment]
So the `SemiJoin` operator is added to an existing group in an exponential relationship to the number of Semi joins:
```
1: 28
2: 310
3: 5,800
4: 83,000
```

Here's a simpler repro that still shows the exponential behavior, and should be easier to inspect with our usual tools:
```
SELECT * FROM c
WHERE
  EXISTS(SELECT 1 FROM e WHERE e.c_id = c.c_id)
```

To see the exponential blowup, copy and past the EXISTS clause repeatedly, for example:
```
SELECT * FROM c
WHERE
  EXISTS(SELECT 1 FROM e WHERE e.c_id = c.c_id)
  AND EXISTS(SELECT 1 FROM e WHERE e.c_id = c.c_id)
  AND EXISTS(SELECT 1 FROM e WHERE e.c_id = c.c_id)
```

If N=# EXISTS, here is how the size of the memo grows:
```
1: 19
2: 26
3: 59
4: 328
5: 3411
```
Setting `WasReordered` when adding semi-joins to an existing group prevents the exponential memo blowup.

**Comment by andy-kimball** [comment]
I hacked in a `wasReordered` map into `JoinOrderBuilder` to avoid all the interning issues. For the original scenario, that dropped planning time on my laptop from 4.2s => 1.5s. That's good, but it also shows that the true issues aren't with `wasReordered`.

**Comment by andy-kimball** [comment]
I think the problem is that we need to reorder joins for a large number of combinations of `inner-join` and `semi-join`. To see this, run this command:
```
reorderjoins format=hide-all
SELECT * FROM c
WHERE
  EXISTS(SELECT 1 FROM e WHERE e.c_id = c.c_id)
  AND EXISTS(SELECT 1 FROM f WHERE f.b_id = c.c_id)
  AND EXISTS(SELECT 1 FROM d WHERE d.c_id = c.c_id)
----
```

Notice that we're analyzing the following combinations of 3 joins (where I = INNER and S = SEMI):
```
SSS
ISS (3 different combos)
IIS (3 different combos)
III (3 different combos)
```
As the number of joins rises, the possible combinations explode.

I wonder if it'd be somehow possible to incorporate the near-equivalence between SEMI and INNER joins into the `JoinOrderBuilder`.

**Comment by DrewKimball** [comment]
All the solution needs to do is prevent `ReorderJoins` from matching on the groups constructed by _reordered_ semi joins - we probably still want to reorder both the originals and the inner join groups they spawn.

Here's a branch where I've implemented the fix I mentioned earlier: https://github.com/DrewKimball/cockroach/tree/semi-join-order

**Comment by andy-kimball** [comment]
That solution can miss valid reorderings. Consider the output of:
```
reorderjoins format=hide-all
SELECT * FROM c
WHERE
  EXISTS(SELECT 1 FROM e WHERE e.c_id = c.c_id)
  AND EXISTS(SELECT 1 FROM f WHERE f.b_id = c.c_id)
----
```
On `master`, the following plan is found:
```
project
 └── project
      └── inner-join (lookup c)
           ├── lookup columns are key
           ├── inner-join (hash)
           │    ├── distinct-on
           │    │    └── scan e
           │    ├── distinct-on
           │    │    └── scan f
           │    └── filters
           │         └── e.c_id = f.b_id
           └── filters (true)
```

However, the branch cannot find this plan, and instead comes up with this:
```
semi-join (hash)
 ├── project
 │    └── inner-join (lookup c)
 │         ├── lookup columns are key
 │         ├── distinct-on
 │         │    └── scan f
 │         └── filters (true)
 ├── scan e
 └── filters
      └── e.c_id = c.c_id
```

The reason is that the branch never considers the case of 2 inner joins (`II`), but only looks at `SS` and `IS`. `master` looks at those two, plus `II`. When looking at `II`, the `JoinOrderBuilder` is able to compute the transitive equality closure and deduce that `e.c_id = f.b_id`, thus allowing it to find the plan that first joins `e` and `f` with one another.

**Comment by andy-kimball** [comment]
I think we can treat `semi-join` edges like `inner-join` edges for the purpose of computing the transitive equality closure. In turn, that should enable the `JoinOrderBuilder` to find all valid orderings from just `SS`, without needing to also evaluate `II`. Then, I _think_ your suggested solution would find all possible orderings.

**Comment by DrewKimball** [comment]
I think you might be right about the transitive closure calculation, at least in the particular case when the `semi-join` in question is the root of the current join tree. It will definitely demand some thought to ensure that it is correct, though.

**Comment by DrewKimball** [comment]
Hmm, actually, just using transitive closure when the `semi-join` is at the root doesn't work, I see what you mean. The problem with adding the `e.c_id = f.b_id` edge is that `f` is in the right input of the `semi-join`, and so we can't add an edge that references it. I'm starting to think that the only way to do this without missing some orderings is to pull the `CommuteSemiJoin` logic into `JoinOrderBuilder` after all.

**Comment by andy-kimball** [comment]
Another important hole in the paper.

**Comment by DrewKimball** [comment]
For our purposes, yes. Keep in mind that the paper in question was one of the first of its kind. Also relevant is that this problem with treating conjuncts as separate stems from disallowing cross joins - if cross joins were allowed, filter-pushdown rules could potentially produce the plans we're looking for. So, the complexity stems from the requirements that (1) we do not introduce any plans with new cross joins, and (2) we produce the same plans as if we did allow cross joins, applied filter pushdown, and then removed the cross join plans.

**Comment by DrewKimball** [comment]
How urgent is this exponential blowup problem? If it needs to be patched quickly, I think the best route would be to merge something along the lines what I implemented on that branch earlier, and then work on expanding the plans considered by `JoinOrderBuilder`. It seems to me that the plans that we'd miss this way are relatively rare.

**Comment by RaduBerinde** [comment]
We definitely need some kind of patch for 20.2 to alleviate the issue. I would be weary of backporting a big change to the `JoinOrderBuilder`, so I'm on board with a simpler change first (even if we miss out on some plans).

**Comment by DrewKimball** [comment]
A problem to consider with regard to unifying the `CommuteSemiJoin` logic with the `JoinOrderBuilder` is that any future rules which match on a join and produce a new join group would face this same problem. `ConvertSemiToInnerJoin` is similar enough that I can probably refactor it as well, but other rules may not be.

**Comment by DrewKimball** [comment]
I'm tempted to make the join reordering an intermediate step that happens after normalization and before exploration. That would prevent any unexpected interaction between rules like we're getting here. It would also reduce duplicate work and, significantly, we wouldn't need the `WasReordered` flag.
