### ISSUE TITLE
Timezone() function not working properly for timestamp fields

### ISSUE THREAD

**Issue by dwaynebradley** [cockroachdb/cockroach#59089]
**Describe the problem**

Using the `timezone()` function to compute the timestamp for a local timezone is giving incorrect results. It actually appears to be ignoring the +/- setting for the offset of the selected timezone.

**To Reproduce**
Run the following:
```
select
   localtime() as localtime_utc,
   timezone('EST', localtime()) as localtime_est,
   localtimestamp() as localtimestamp_utc,
   timezone('EST', localtimestamp()) as localtimestamp_est
```

When I just ran the above locally, the results came back as follows for the 4 columns:

```
           localtime_utc           |          localtime_est           |        localtimestamp_utc        |        localtimestamp_est
-----------------------------------+----------------------------------+----------------------------------+-----------------------------------
  0000-01-01 00:53:10.962435+00:00 | 0000-01-01 19:53:10.962435-05:00 | 2021-01-17 00:53:10.962435+00:00 | 2021-01-17 05:53:10.962435+00:00
```

As you can see in the above results, the `localtimestamp_est` column ADDED 5 hours instead of substracting like it does for the `localtime_est` column.

**Expected behavior**
Would expect the `timezone()` function to correctly compute offsets for `timestamp` columns like it does for `time` columns.

**Additional data / screenshots**

**Environment:**
```
$> cockroach version
Build Tag:        v20.2.3
Build Time:       2020/12/14 18:33:39
Distribution:     CCL
Platform:         linux amd64 (x86_64-unknown-linux-gnu)
Go Version:       go1.13.14
C Compiler:       gcc 6.3.0
Build Commit ID:  89dd2d14c29787378c434ed54937757ef5d9877c
Build Type:       release

$> cat /etc/os-release
NAME="Ubuntu"
VERSION="20.10 (Groovy Gorilla)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.10"
VERSION_ID="20.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
```

**Additional context**
Unable to display timestamp columns columns correctly in a local timezone.

**Comment by rafiss** [comment]
cc @otan does this relate to the weird inverted offset thing mentioned in https://github.com/cockroachdb/cockroach/pull/46510

**Comment by otan** [comment]
this is behaving as expected, as least comparing the results to pgsql:

```
otan=# select
   localtime as localtime_utc,
   timezone('EST', localtime) as localtime_est,
   localtimestamp as localtimestamp_utc,
   timezone('EST', localtimestamp) as localtimestamp_est;
  localtime_utc  |   localtime_est    |     localtimestamp_utc     |      localtimestamp_est
-----------------+--------------------+----------------------------+-------------------------------
 21:28:49.336868 | 16:28:49.336868-05 | 2021-01-21 21:28:49.336868 | 2021-01-22 02:28:49.336868+00
(1 row)
```

> As you can see in the above results, the localtimestamp_est column ADDED 5 hours instead of substracting like it does for the localtime_est column.

This is a brain teaser. Have a read of https://www.cockroachlabs.com/blog/time-data-types-postgresql/ - I'll try give a tl;dr here:

`timezone` is the same as `AT TIME ZONE` translates a TIME to TIMETZ and a TIMESTAMP to a TIMESTAMPTZ.

TIMETZ behaves specially. It encodes timezones, and store it in the datum. As such, 21:28:49.336868 shows up with the encoded timezone correctly as 16:28:49.336868-05

However, `timezone` behaves differently for TIMESTAMP -> TIMESTAMPTZ. TIMESTAMPTZ does not encode time zone data, so it displays differently based on `SET TIME ZONE` -- the value of 2021-01-22 02:28:49.336868+00 (since your time zone is set to UTC when opening a CRDB shell) is the same as ` 2021-01-21 21:28:49.336868-05`. If you set the session time zone to EST, the result looks correct (in both psql and cockroachdb):

```
otan=# set time zone 'est';
SET
otan=# select
otan-#    localtime as localtime_utc,
otan-#    timezone('EST', localtime) as localtime_est,
otan-#    localtimestamp as localtimestamp_utc,
otan-#    timezone('EST', localtimestamp) as localtimestamp_est;
  localtime_utc  |   localtime_est    |     localtimestamp_utc     |      localtimestamp_est
-----------------+--------------------+----------------------------+-------------------------------
 16:39:52.804743 | 16:39:52.804743-05 | 2021-01-21 16:39:52.804743 | 2021-01-21 16:39:52.804743-05
(1 row)

```

**Comment by dwaynebradley** [comment]
Wow...that is good to know. Thanks @otan. That one was really messing with my head :-)
