### ISSUE TITLE
importccl benchshort times out

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#59126]
I've seen this CI failure a few times. Full log in build artifacts https://teamcity.cockroachdb.com/viewLog.html?buildId=2591863&buildTypeId=Cockroach_UnitTests_Bench&tab=buildResultsDiv

```
*** Test killed with quit: ran too long (6m0s).
exit status 2
FAIL	github.com/cockroachdb/cockroach/pkg/ccl/importccl	360.203s
```

**Comment by RaduBerinde** [comment]
Another one: 
https://teamcity.cockroachdb.com/viewLog.html?buildId=2593493&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_Bench

**Comment by RaduBerinde** [comment]
Logs suggest that the problematic benchmark `BenchmarkUserfileImport`. Maybe the same issue as https://github.com/cockroachdb/cockroach/issues/58948 (I see the same error in the log).

**Comment by RaduBerinde** [comment]
https://teamcity.cockroachdb.com/viewLog.html?buildId=2590368&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_Bench

**Comment by jordanlewis** [comment]
I've gotten this too, but in normal unit tests...

https://teamcity.cockroachdb.com/viewLog.html?buildId=2602625&buildTypeId=Cockroach_UnitTests

**Comment by adityamaru** [comment]
I've run this ~20 times and each run averages ~13s. Going to unskip this under the assumption that the above fix has mitigated this since I can't reproduce the timeout.
