### ISSUE TITLE
tracing: need separate API for clearing payload vs verbose logs

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#59145]
See https://github.com/cockroachdb/cockroach/pull/59103#pullrequestreview-570390893

We want to add a bool to `(*Span).Structured` that, if true, removes any visited payloads from their surrounding `Span` (thereby consuming them).
We also want an explicit `(*Span).ResetRecording()` that resets the `Span`'s childrens. It should also reset the payloads, since by removing children it's already doing so at least partially.
Finally, `enableRecording` shouldn't clear anything any more.

Worth noting that while this is accommodating a usage pattern in SQL land that I consider problematic, namely that of reusing a span repeatedly, we are bound to have similar issues to do the fact that we use the local machine itself as the storage provider for the trace. Long-running traces can amass arbitrary amounts of data, and at some point data needs to be aged out. While ideally we will ultimately learn to budget properly (i.e, expire old data as new data comes in), this is a few steps out.

**Comment by irfansharif** [comment]
Dumping the conversation here for posterity (mostly for @asubiotto's consumption):

> Irfan: this consumption of recordings issue (https://github.com/cockroachdb/cockroach/issues/59145) is kind of ugly. our visitor pattern is currently applied to a “captured” or “materialized” recording (something we got out of “span.GetRecording”). To consume from that seems fragile, if somehow that materialized view lets you mutate/consume the span it was derived from. 
> We can “consume” it at the point where we grab the recording itself, which I think makes it easier to reason about the lifecycle if individual structured events that were shoved into the span. but before I go do that, would that work with how sql does things?

> Tobi: Yeah, that’s a good point. We need to consume while getting the recording. I think this works, though it means we’ll have to pass options to GetRecording that specify whether to consume only the structured payloads, everything, or nothing
>
> I think this should work with SQL. The span is currently reset as a side product of starting to record, so we can just plop a wiping GetRecording call there. Then Alfonso will add the “clear payloads only” call in the “other” places when he adds them
Though wait, that’s also bad. We do want the recordings to stay in the verbose spans even though they were already handled :thinking_face: Otherwise they disappear from the verbose view or are never shown in the first place. Ugh
>
> So maybe we’re really looking at tracking an index up to which the payloads have been consumed in the Span?
>
> then the three things possible to do become
> - purely read
> - read payloads and mark as consumed
> - wipe the recording (all data gets nil’ed)

> Irfan: in an ideal world (I know we don’t have time for it in 21.1) we’d not have these long lived spans, and hold onto recordings. and the components that need to hold on to them (the SessionTracer guy, and similar things) don’t hold onto them indirectly through a span.

> Tobi: The Span thing is not ideal, but what you’re suggesting is just “let everyone else worry about how they propagate the recordings around”, and that is also not a great solution
>
> And long-lived spans are natural to some degree. It’s just at odds with our approach of storing data in that span
>
> Once you make spans use ring buffers and some kind of memory accounting, or even have them store stuff in a per-node registry, it becomes more natural while largely looking the same to the consumers

> Irfan: maybe rafa’s suggestion around centralizing around the point of storage is more appealing. you can have your long lived spans, with recordings accessible only through this storage medium (+ span ID), and then consumption/holding onto recordings is much clearer, and not tied to the lifecycle of the span those events originated from.

**Comment by tbg** [comment]
Now that I understand this a little better (thanks @andreimatei) we don't have to do much here. If we are session tracing, then the lifetime of the span is that of the session trace. We hold on to the last recorded session trace, but this is fine - already happens that way today. If we're not session tracing, we get a new recording root span for each txn, so payloads only accrue within the txn, which is fine.

Additionally, payloads are ingested by the SQL gateway in `(DistSQLReceiver).Push`, i.e. at a level below the txn-level recording span, so we don't have to worry about them getting consumed twice, and that is also independent of session tracing getting flipped on/off in the meantime.
