### ISSUE TITLE
TLS Cert signing in Kubernetes

### ISSUE THREAD

**Issue by keith-mcclellan** [cockroachdb/cockroach#59156]
**Describe the problem**

Kubernetes has deprecated and is removing the ability for us to use CSRs to issue node certs in an upcoming release.  This is going to break almost all of our install patterns except 'config file with custom ca' including the helm chart and the operator.  This is already disabled in EKS and only has limited functionality in OpenShift and Tanzu.  This will likely drive both engineering work and docs updates.

ref: https://github.com/cockroachdb/cockroach-operator/issues/291

Jira issue: CRDB-3326

**Comment by taroface** [comment]
Will this also impact the security changes that @aaron-crl is introducing?

**Comment by aaron-crl** [comment]
This should not, we are not depending on Kubernetes APIs for certificate management in that RFC.

**Comment by knz** [comment]
cc @jtsiros for triage
