### ISSUE TITLE
kv: lease extensions can be rejected due to raft follower status

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#59179]
Currently, the `propBuf` can reject extensions of an existing lease because the current leaseholder is not the raft leader. This was not the intention of the rejection logic in the `propBuf` and should be avoided.

This motivates a change like https://github.com/nvanbenschoten/cockroach/commit/b43772261af1bd515c66b84e4667313fc1faffd6.

**Comment by tbg** [comment]
@erikgrinaker since it's looking like you're running out of queue soon, would you take this on? The change is trivial, most of the work is to write a test, for which you can look to `replica_proposal_buf_test.go`.
