### ISSUE TITLE
tracing: memory budgeting

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#59188]
**Is your feature request related to a problem? Please describe.**
Verbose trace spans collect possibly large amounts of data in memory, which can present a stability risk. With always-on tracing, the same holds for the structured payloads (though with a small factor, since a lot less data is collected).

**Describe the solution you'd like**
Heuristically count the number of bytes held in a Span's own recording (i.e. not traversing into the children). New data enters via these methods:

https://github.com/cockroachdb/cockroach/blob/a01689bd2dffee460838294950384989d6ef398d/pkg/util/tracing/span.go#L324-L366

As a set max size (per span) is exceeded or the root account runs out of quota, drop old messages every time a new message is added. Also set a flag on the span that indicates that the recording is incomplete, perhaps by retaining the most recent timestamp for which events were dropped. We should drop verbose messages first, then structured payloads.

Note that the opentracing and net/trace spans use a cardinality based limit:

https://github.com/cockroachdb/cockroach/blob/513b01ba1fbd34dd202024df54bb37c206a2e34a/pkg/util/tracing/tracer.go#L343
https://github.com/cockroachdb/cockroach/blob/e9e1f2b0587e8732059f6c357433ea8301e8a872/pkg/util/tracing/shadow.go#L107-L112

I think for net/trace we may want to remove the limit and instead, upon first exceeding the memory budget for any given span, print a message to net/trace explaining that no more logs will be relayed there.

**Describe alternatives you've considered**

We could also try to attach a memory budget and use all of the infrastructure we already have in SQL, by attaching

https://github.com/cockroachdb/cockroach/blob/94a429b124c953285a69c948c7d9666252089a04/pkg/util/mon/bytes_usage.go#L30-L35

to the Tracer

https://github.com/cockroachdb/cockroach/blob/513b01ba1fbd34dd202024df54bb37c206a2e34a/pkg/util/tracing/tracer.go#L114-L132

and use that to guide the decisions. This might actually be my favorite, assuming that the `mon` package is in good standing (I'm not familiar with it). Some notes:

- this will likely require refactoring of the `mon` package, since the tracing package can not depend on `util/log` due to import cycles, which is fine.
- we need to clear the recording in `Span.Finish()` and we need to prevent new recording data from entering a `Finish`'ed span (for otherwise it will allocate from the monitor, but never release back).
- this is more brittle in the sense that a failure to return bytes to the monitor correctly will cause problems. However, we can add assertions that are active through large swathes of our test suite which should give us good confidence that this is not happening.
- we need to determine where to take the bytes from. We could hang it off the sql memory monitor, or use a separate, fixed-size monitor.

**Additional context**

We will want some kind of basic safeguard in place for 21.1, even if it just extends the `maxLogsPerSpan` mechanism to also apply to payloads.

Jira issue: CRDB-3323

**Comment by irfansharif** [comment]
yup, just got a bit side-tracked with other stability issues on my plate.

**Comment by jordanlewis** [comment]
I'm a little scared of attaching this work to SQL monitors. In particular, lifespan bugs in monitors are often hard to track down and debug. I think it could mean that tracing lifespan bugs would have a larger blast radius than they would otherwise.

I think the monitor package is probably suitable, it's just we'd need to be quite careful about how we use it.

**Comment by tbg** [comment]
As of https://github.com/cockroachdb/cockroach/pull/61359, each Span individually limits the bytes in payloads and the bytes in verbose messages (both use a FIFO ring buffer).

We should apply something similar to these two slices:

https://github.com/cockroachdb/cockroach/blob/6c3b89d3f24c853dac704f9e93aa8b289cdb8b4a/pkg/util/tracing/crdbspan.go#L68-L71

As we can easily see unbounded growth in them, see for example https://github.com/cockroachdb/cockroach/issues/59560.

**Comment by irfansharif** [comment]
@abarganier the last PR I had for memory budgeting was #61714, that I'm not finding the time to get to. Mind if I throw the ball over to you? I don't think this is very pressing, that PR was mostly out of an abundance of caution. But still, would be nice to have as a safeguard.

**Comment by abarganier** [comment]
@irfansharif SGTM, I think this would fit nicely into the tracing library handoff. Just to clarify, you closed the PR because you don't have the time, not because the solution is invalid, correct? I'd be happy to work on driving it home.

**Comment by irfansharif** [comment]
Yup, just don't have the bandwidth for the small bit of polish+shepherding needed. That PR is pretty tiny though, and I'm happy to rubber stamp another attempt at it.

**Comment by abarganier** [comment]
Cool sounds good, I'll get this scheduled on our end and tag you as a reviewer. I've updated the owning team accordingly. It might have to wait until a bit later in the month given other work on our plates, but I will keep you updated.
