### ISSUE TITLE
TestMigrationPurgeOutdatedReplicas: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#59180]
https://teamcity.cockroachdb.com/viewLog.html?buildId=2596743&buildTypeId=Cockroach_UnitTests

**Comment by irfansharif** [comment]
I'm not sure how to find the stack trace. Pretty sure this is the same thing as https://github.com/cockroachdb/cockroach/issues/58523#issuecomment-760388487 (+cc @tbg). Maybe as a stop gap, I'll send a PR out (tomorrow) to temporarily check for the ReplicaState being nil. This test isn't the only that that'll be affected by it, it could be pretty much any and every test.

**Comment by tbg** [comment]
Yes, that's a good idea. Fixing the root cause is unfortunately not a one
liner and I haven't even started.

**Comment by irfansharif** [comment]
Unskipping in #59194, same underlying bug as #58523.
