### ISSUE TITLE
opt: ensure that implicitly partitioned unique partial indexes behave correctly

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#59195]
Currently, the optimizer assumes that unique constraints created with `UNIQUE WITHOUT INDEX` do not have a predicate. However, the optimizer will need to handle unique constraints with a predicate once implicitly partitioned unique partial indexes are supported. To ensure that this works, it might be worth allowing `UNIQUE WITHOUT INDEX` constraints to have a predicate. Regardless of whether we support predicates with `UNIQUE WITHOUT INDEX`, we will need to add tests with partitioned unique partial indexes as well.

cc @otan

**Comment by mgartner** [comment]
This work was completed via a handful of PRs.
