### ISSUE TITLE
tracing: wrongly emitting trace events for session's first txn

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#59203]
See #59193. We bisected a failure in `TestExecBuild/local/autocommit_nonmetamorphic` to #58897, which simply enabled always-on tracing. We're now doubly emitting trace data when we shouldn't be.

**Comment by irfansharif** [comment]
I don't think we're double emitting trace events. I think it's more that we're not resetting trace events in a span correctly. We used to expect the following data driven output for the following query:
```
statement ok
SET TRACING=ON;
  WITH cte AS (INSERT INTO ab VALUES (3, 3), (4, 4) RETURNING a, b)
  INSERT INTO ab (SELECT a*10, b*10 FROM cte);
SET TRACING=OFF

query TT
SELECT operation, message FROM [SHOW KV TRACE FOR SESSION]
WHERE message       LIKE '%r$rangeid: sending batch%'
  AND message   NOT LIKE '%PushTxn%'
  AND message   NOT LIKE '%QueryTxn%'
  AND operation NOT LIKE '%async%'
----
dist sender send  r35: sending batch 2 CPut to (n1,s1):1
dist sender send  r35: sending batch 2 CPut to (n1,s1):1
dist sender send  r35: sending batch 1 EndTxn to (n1,s1):1
```

Which fails with:
```
testdata/autocommit_nonmetamorphic:797: SELECT operation, message FROM [SHOW KV TRACE FOR SESSION]
WHERE message       LIKE '%r35: sending batch%'
  AND message   NOT LIKE '%PushTxn%'
  AND message   NOT LIKE '%QueryTxn%'
  AND operation NOT LIKE '%async%'
expected:
    dist sender send  r35: sending batch 2 CPut to (n1,s1):1
    dist sender send  r35: sending batch 2 CPut to (n1,s1):1
    dist sender send  r35: sending batch 1 EndTxn to (n1,s1):1
but found (query options: "") :
    dist sender send  r35: sending batch 1 DelRng to (n1,s1):1
    dist sender send  r35: sending batch 2 CPut to (n1,s1):1
    dist sender send  r35: sending batch 2 CPut to (n1,s1):1
    dist sender send  r35: sending batch 1 EndTxn to (n1,s1):1
```

Where's the DelRng coming from? Probably some previous trace.

**Comment by irfansharif** [comment]
I think it's got to do with how we expect traces to behave with `ROLLBACK`.
```
# LogicTest: local !metamorphic

statement ok
CREATE TABLE ab (a INT PRIMARY KEY, b INT, FAMILY f1 (a, b))

# Get the range id.
let $rangeid
SELECT range_id FROM [ SHOW RANGES FROM TABLE ab ]

# Populate table descriptor cache.
query II
SELECT * FROM ab
----

# No auto-commit inside a transaction.
statement ok
BEGIN

statement ok
SET TRACING=ON;
  INSERT INTO ab VALUES (4, 4), (5, 5);
SET TRACING=OFF

query TT
SELECT operation, message FROM [SHOW KV TRACE FOR SESSION]
WHERE message     LIKE '%r$rangeid: sending batch%'
  AND message NOT LIKE '%PushTxn%'
  AND message NOT LIKE '%QueryTxn%'
----
dist sender send  r35: sending batch 2 CPut to (n1,s1):1

statement ok
ROLLBACK

statement ok
SET TRACING=ON;
  INSERT INTO ab VALUES (6, 6), (7, 7) RETURNING a, b;
SET TRACING=OFF

query TT
SELECT operation, message FROM [SHOW KV TRACE FOR SESSION]
WHERE message     LIKE '%r$rangeid: sending batch%'
  AND message NOT LIKE '%PushTxn%'
  AND message NOT LIKE '%QueryTxn%'
----
dist sender send  r35: sending batch 2 CPut, 1 EndTxn to (n1,s1):1
```

This is what I expect to behave like, but it doesn't, the "dist sender send  r35: sending batch 2 CPut to (n1,s1):1" recording from the rolled back statement still shows up in future traces.

**Comment by irfansharif** [comment]
I see that we're grabbing onto the first txn's span in the session here: https://github.com/cockroachdb/cockroach/blob/854246a5f4a486ed1bbaa1e20ce04223280d01d8/pkg/sql/exec_util.go#L1483-L1485

And since we're not really ever "consuming" span data from the aborted txn, it'll show up in future traces. We've had this behaviour for a while, and not sure if it's a sensible default.

**Comment by irfansharif** [comment]
yo @asubiotto, I think this is in your ballpark. I don't know if we'll have time to do anything about it, or if it's worthwhile for 21.1, but I do think it's a "bug".

**Comment by asubiotto** [comment]
Hmm, thanks for raising this. We'll hopefully get to trace-related fixes during the stability period.

**Comment by irfansharif** [comment]
Are we still planning on addressing this?

**Comment by asubiotto** [comment]
It's a nice to have for 21.1 so not certain we'll definitely have it done for 21.1. We'll take a look at addressing it once we've completed higher-priority items.

**Comment by irfansharif** [comment]
I'm having to get into the weeds of this SessionTracer guy to work through the implications of https://github.com/cockroachdb/cockroach/pull/61777. Specifically, if we're not creating real spans unless absolutely needed, we can't rely on the assumptions of this code:

https://github.com/cockroachdb/cockroach/blob/a86cf540219a82234187db11434ab664fe335f17/pkg/sql/exec_util.go#L1645-L1656

I think we'll want to hijack the txn's span + context in the same manner we do for the conn below. Does that sound right to you? +cc @cockroachdb/kv-east.

**Comment by asubiotto** [comment]
That sounds reasonable to me, but this code is new to me too.
