### ISSUE TITLE
client: move the MinInitialTimestamp to the client.Txn instead of ExecOptions

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#5920]
Requested by @andreimatei in https://github.com/cockroachdb/cockroach/pull/5776#issuecomment-204081324

**Comment by knz** [comment]
(@knz) Not planning to work on this in the near future.

**Comment by petermattis** [comment]
@andreimatei, @knz `MinInitialTimestamp` no longer exists. Is there anything left to do here?

**Comment by knz** [comment]
Actually this already has been addressed when MattJ implemented time travel queries. Thanks for noticing.
