### ISSUE TITLE
sql/ui: unset as an app name isn't available in the transactions page

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#59217]
In the UI, on the statements and transactions pages, you can filter by app name. However, on the statements page you can have an unset value. This same value isn't available on the transactions page. If a statement should be set on unset on the transactions page it can cause the page to error out.

@timveil found this when testing around this issue https://github.com/cockroachlabs/support/issues/793

Jira issue: CRDB-3316

**Comment by awoods187** [comment]
@timveil do you have a screenshot of this at all?

**Comment by timveil** [comment]
No but I could recreate pretty easily

**Comment by nathanstilwell** [comment]
@timveil I would appreciate some screenshots.
