### ISSUE TITLE
ui: Transactions page shows TXN TYPE as explicit even for implicit transactions

### ISSUE THREAD

**Issue by sheaffej** [cockroachdb/cockroach#59210]
The Transactions page in the 20.2 DB console shows implicit transactions as explicit in the Transaction Details page.

This is an example of a transaction that was issued as an implicit transaction. Rollback statements used just to illustrate that an explicit transaction was not in progress.
```
root@snow:26257/defaultdb> rollback;
ERROR: there is no transaction in progress

root@snow:26257/defaultdb> insert into foo values (5);
INSERT 1
Time: 5ms total (execution 5ms / network 1ms)

root@snow:26257/defaultdb> rollback;
ERROR: there is no transaction in progress

root@snow:26257/defaultdb>
```

![image](https://user-images.githubusercontent.com/5922798/105226526-f1416380-5b14-11eb-9f3a-b907a4d160bd.png)

**Repro:**
1. Start a single node
2. Issue a simple implicit statement
3. View the Transactions page in the DB Console
4. View the Transaction Details page for the transaction
5. Notice the statement is listed as Explicit

**Comment by awoods187** [comment]
Nice find. This looks like a bug. cc @solongordon @asubiotto

**Comment by jordanlewis** [comment]
Interestingly, this works fine on the statements page.

**Comment by jordanlewis** [comment]
Seems like we just hardcode `explicit` for all statements inside of the txns page:

```
export const aggregateStatements = (
  statements: Statement[],
): AggregateStatistics[] =>
  statements.map((s: Statement) => ({
    label: s.key.key_data.query,
    implicitTxn: false,
    stats: s.stats,
  }));
```

@solongordon is this fixable or should we just remove the explicit/implicit column from the txns page?

**Comment by solongordon** [comment]
Yeah, the column should just be removed since we do not distinguish between implicit and explicit transactions for the purpose of transaction statistics. Looks like @asubiotto already did this in https://github.com/cockroachdb/ui/pull/222.

**Comment by rafiss** [comment]
Re-opening and moving to SQL Observability since it it seems like implicit is still hardcoded here (on master): https://github.com/cockroachdb/ui/blob/3e168d09d9a6c2515ae6a9fb5f7635ca6ee17974/packages/cluster-ui/src/transactionsPage/utils.ts#L41-L49
