### ISSUE TITLE
metrics page in console cannot get data when the time isn't the same between machines browser running on and server running on in secure mode

### ISSUE THREAD

**Issue by eiDear** [cockroachdb/cockroach#59241]
**Describe the problem**
step1: start a secure cluster with 3 nodes on the same virtual machine, but use different ports.
step2: open chrome on local PC。login the console, switch the page on metrics cluster or specify a node, overview. And the dashboard can not get data and are always waiting.
<img width="359" alt="1" src="https://user-images.githubusercontent.com/6024149/105276061-89098500-5bdb-11eb-969c-a44ed380d4dc.png">

I try my best to find reasons.
(1) I read the log but I fount the error:
`http: TLS handshake error from 192.168.56.1:52951: remote error: tls: unknown certificate `
(2）I debug the Chrome and found the reponsed err message : 'cannot query time series in the future (start time 116xxxxx was greater than current clock 116xxxxx'
 then I sync the virtual machine timezone and time with   local PC, and the problem resolve.

**Environment:**
 - CockroachDB 19.1.5
 - Server OS: [e.g. Linux/centos]

**Comment by rafiss** [comment]
Thanks for this issue @eiDear! 

Unfortunately v19.1 has reached the end of its support cycle: https://www.cockroachlabs.com/docs/releases/release-support-policy.html#support-cycle

Do you still see this problem in a newer version?

**Comment by eiDear** [comment]
OK. I will try the new version to check wheather this issue is still retained.
