### ISSUE TITLE
console: average queries per store doesn't take into consideration multiple disk per node (separate stores on separate disks per node)

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#59262]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

avg queries per store graph will show per node queries not individual stores per node.

**Expected behavior**

Would be good to emphasize each store file or store disk individually rather than treat a store as node.

**Environment:**
 - CockroachDB version 20.2.3 and 20.2.4
 - Server OS:Ubuntu 16.04
 - Client app: DB Console

**Additional context**
What was the impact?

Jira issue: CRDB-3309

**Comment by thtruo** [comment]
@dbist Could you shed some light and educate me on why you want to emphasize avg queries for each store?
