### ISSUE TITLE
The Serializable Transaction behaves differently on Macbook  

### ISSUE THREAD

**Issue by lin-crl** [cockroachdb/cockroach#59278]
**Describe the problem**
The Serializable Transaction behaves differently on Macbook  

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**
Run Cockroach v20.2.3 using docker or K8 on MacBook V10.15.7 (macOS Cataline). Follow the Cockroach scenario in this doc  https://www.cockroachlabs.com/docs/stable/demo-serializable.html 

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster via minikube
2. start two docker to run sql and follow the doc to create tables and insert data
3. Start explicit transactions in two sessions
4. The first session(Doctor 1) complete successful while the second session (Doctor 2) had the error. 

**Expected behavior**
According to the doc, The first session(Doctor 1) would fail while the second session (Doctor 2) would succeed. 

**Additional data / screenshots**
This is the same for single docker container or 3-node K8 cluster. I've tested the scenario on gcp using roachprod. And it behaves the same as the doc described. Wonder if it might be caused by macOS.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version: v20.2.3
 - Server OS: MacBook
 - Client app: cockroach sql

**Additional context**
What was the impact?

Jira issue: CRDB-3308

**Comment by jordanlewis** [comment]
Please re-open with more details if you're still seeing this, thanks!
