### ISSUE TITLE
sql: implement the EXPLAIN ANALYZE stats statement overview page

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#59296]
This issue tracks adding the following stats to the statement overview page:
![image](https://user-images.githubusercontent.com/10560359/105485201-d0ac1180-5cac-11eb-8c07-174347014468.png)

Contended transactions are out of scope for this first pass as they require #57114.

The important part is adding the stats, not necessarily displaying them as shown (although that would be nice).

**Comment by asubiotto** [comment]
This is the version without the bar so that we can iterate quicker:
![image](https://user-images.githubusercontent.com/10560359/108195073-a288e880-7117-11eb-91a3-a1051e1a7942.png)

**Comment by awoods187** [comment]
This looks great!
