### ISSUE TITLE
logs: place a `channel` key in our logging payload

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#59325]
This is a request that came up from a conversation with @logston 

**Describe the problem**

When users are working with multiple logs in their external log aggregator of choice, one rough edge is differentiating between log types or log sources. 

**Suggestion / solution**

One way to improve the quality of life for operators who need to parse through various Cockroach logs is to do something like placing a `channel` key in the log's JSON payload (e.g. `"channel": "SESSIONS"`).

**Comment by thtruo** [comment]
cc @knz

**Comment by knz** [comment]
That is already implemented (for v21.1)
