### ISSUE TITLE
sql: SAVEPOINT-based retries are slower than naive/plain retries

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#5935]
cc @andreimatei.

I was trying to apply the transaction retrry protocol to the jepsen tests and ran into serious performance issues. In short using the proposed protocol with or without a back-off delay causes transactions to retry / timeout much more than a full/plain rollback-then-retry.

For example:
- full/plain retry: http://52.91.194.28/cockroachdb-monotonic:blank/20160407T201547.000Z/latency-raw.png
- retry with intents: http://52.91.194.28/cockroachdb-monotonic:blank/20160407T191020.000Z/latency-raw.png

This is a performance anomaly that needs further investigation.

Jira issue: CRDB-6192

**Comment by knz** [comment]
(@knz) this performance anomaly did not show up much recently. Closing this since I do not plan to look into it. Let's reopen if ever applicable.

**Comment by knz** [comment]
Investigated while working on #7912 and https://github.com/cockroachdb/docs/issues/646.

There is an anomaly - the retry protocol doesn't seem advantageous.
See attachment:
[Perfcompare.pdf](https://github.com/cockroachdb/cockroach/files/587448/Perfcompare.pdf)

**Comment by aphyr** [comment]
Heyo! Yes, to confirm, I did remove retries from most of the tests for performance reasons--but there's another, more subtle reason: they make it harder to detect concurrency errors, by broadening the window of concurrency for any given operation.

**Comment by knz** [comment]
So the issue is still very much visible. A client that does BEGIN...COMMIT and then retries with an exponential back-off upon a retry error it going to commit more txns successfully per second than one using our SAVEPOINT-based protocol, if the system is contended.

**Comment by knz** [comment]
cc @nvanbenschoten for triage and prioritization.

**Comment by sploiselle** [comment]
@nvanbenschoten Do you have any sense if this is still a known limitation?

**Comment by nvanbenschoten** [comment]
No I don't, as I haven't been able to reproduce it. I wouldn't document anything until it's confirmed that this was and still is an issue, at which point we should look into fixing it. A lot has changed around txn retries in the past 2 years.

**Comment by awoods187** [comment]
@nvanbenschoten what would it take to benchmark this? It would help inform some questions we have regarding our use of savepoints and if the (current) hassle of this feature is worth it.

**Comment by nvanbenschoten** [comment]
We could disable savepoints in tpcc and ignore errors the retryable errors on the client. I would be very (very) surprised if doing so improved performance. In fact, I would be surprised if it didn't completely tank performance.

**Comment by knz** [comment]
back in the days when I was trying this, I found that a tight retry loop would not be better without savepoints, however a retry loop with exponential back-off was successful. The average latency under contention would go up but the tail latency would not be as extreme.

**Comment by bdarnell** [comment]
> We could disable savepoints in tpcc and ignore errors the retryable errors on the client

Those are two separate things: the benchmark we want here is to not use savepoints, but still handle retryable errors (with each attempt as a fully independent transaction)

**Comment by jseldess** [comment]
@bdarnell, thoughts on whether we should add this to known limitations or not?

**Comment by bdarnell** [comment]
I wouldn't document it until we can confirm that it's still an issue and have some sense of the impact. Especially since we're no longer emphasizing SAVEPOINT retries it's not something that most users would be affected by.

**Comment by ericharmeling** [comment]
@bdarnell @knz Any objections to removing the "docs-known-limitation" label here?

**Comment by bdarnell** [comment]
Fine with me.
