### ISSUE TITLE
index selection

### ISSUE THREAD

**Issue by carr123** [cockroachdb/cockroach#59367]
sorry, i can't visit cockroach forum, so i post a question here.

I have a table 'users',  'orgid' is an indexed column.
i insert many records into the table time and time again.

i evaluate the SQL statement as following after every insertion:
explain select count(*) from users where orgid in ('2c3f38ff-4436-4a84-8cf0-2d381b350ff2','2c3f38ff-4436-4a84-8cf0-2d381b350ff3','2c3f38ff-4436-4a84-8cf0-2d381b350ff4');

the result shows that the execute egine sometimes use index, sometimes use full table scan. 
it seems the database can cleverly chose how to execute the sql clause.
could you please explain this behaviour ?

**Comment by solongordon** [comment]
Hi @carr123! Please visit the [docs on our cost-based optimizer](https://www.cockroachlabs.com/docs/stable/cost-based-optimizer.html) to see they answer your question. Our Slack channel is also a good resource for informal questions like this.
