### ISSUE TITLE
sql: Add ddl_analysis/bench test for connection attempts

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#59393]
The tests in ddl_analysis only inspect the roundtrips performed by an indivdual SQL query. They can be greatly improved if the test infra were modified to allow capturing the total number of lookups provided by any function invocation. Specifically, due to the bug in https://github.com/cockroachdb/cockroach/pull/58671 we'd like to benchmark how many roundtrips occur during a connection attempt.

**Comment by solongordon** [comment]
It actually doesn't seem like ddl_analysis is the appropriate tool here, at least without significant refactoring, because it doesn't have any insight into making connections, only executing queries. Closing this in favor of #59394.
