### ISSUE TITLE
sql/pgwire: set options based on "options" url parameter

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#59404]
The PGJDBC docs describe how one can include a URL parameter of `options` in order to set session variables: https://jdbc.postgresql.org/documentation/head/connect.html#connection-parameters

This is important because PGJDBC does not allow one to set session variables directly in the URL. That is, you need to specify like this:

```
postgresql://user@host:port/database?options=-c%20serial_normalization=virtual_sequence
```

and not this

```
postgresql://user@host:port/database?serial_normalization=virtual_sequence
```

However, CockroachDB only recognizes the latter right now. The connection initialization in [parseClientProvidedSessionParameters
](https://github.com/cockroachdb/cockroach/blob/cc5bd9c49800030e7c1be28d9ba7e73f055fc22a/pkg/sql/pgwire/server.go#L681) needs to be updated to look for the `options` key.

---

here's an example that can be used to repro and write a test. the test for this can go in pkg/sql/pgwire/conn_test.go. The test `TestConnMessageTooBig` has better examples that show how to use pgx and the test/assertion libraries.

```
    config, err := pgx.ParseConnectionString("postgresql://root@localhost:26257/defaultdb?sslmode=disable&options=-c%20serial_normalization=virtual_sequence")
    if err != nil {
        log.Fatal("error configuring the database: ", err)
    }

    conn, err := pgx.Connect(config)
    if err != nil {
        log.Fatal("error connecting to the database: ", err)
    }
    defer conn.Close(context.Background())

    row, err := conn.QueryRow(context.Background(), "SHOW serial_normalization")
    if err != nil {
        log.Fatal(err)
    }

    var s string
    if err := rows.Scan(&s); err != nil {
        log.Fatal(err)
    }
    // assert s == "virtual_sequence" here
    fmt.Printf("%s \n", s)
```

**Comment by mneverov** [comment]
hi, I'd like to work on this.

**Comment by rafiss** [comment]
@mneverov thanks for your interest! please go ahead. the issue description should have enough pointers to get started :)
