### ISSUE TITLE
Type Mismatch when upserting with unnest 

### ISSUE THREAD

**Issue by israellot** [cockroachdb/cockroach#59427]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

```
create table test(id string primary key, a jsonb)

upsert into test(id,a) values ('1','{"a":"b"}')

upsert into test(id,a) 
	select * from unnest(array['1','2'],array['{"a":"b"}','{"c":"d"}']) as d
```

The first upsert works well, string is converted to jsonb
The second upsert fails with type mismatch error 

`SQL Error [42804]: ERROR: value type string doesn't match type jsonb of column "a"`

**Environment:**
 - CockroachDB version 20.1.8

This is just an example, my interest is on bulk loading data using unnest and passing array parameters , such as 
`upsert into test(id,a)  select * from unnest(@p1,@p2) `

**Comment by rafiss** [comment]
I think this is because we don't have support for arrays of JSON elements. https://github.com/cockroachdb/cockroach/issues/23468

**Comment by ajwerner** [comment]
I think it may also be related to https://github.com/cockroachdb/cockroach/issues/38965 though could be wrong. It feels like even if we did support those arrays, I'm not sure we'd automatically figure out that we need to interpret that array as a JSONB array and not a string array.

**Comment by rafiss** [comment]
I'll go ahead and close this in favor of the two linked issues.

thanks for the report @israellot ! Feel free to comment on the other issues if you have more details to share.
