### ISSUE TITLE
sql: allow UPDATE to modify primary key columns

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#5943]
`UPDATE` currently disallows modifications to the primary key columns. There is no strong reason for this restriction. A modification to a primary key column would need to delete and rewrite any existing column data for the row and for associated indexes which reference the primary key, but these keys and values can be derived from the data available to `UPDATE`.

**Comment by JackKrupansky** [comment]
No objection to the feature, but curious about the ramifications.

For example, change to a PK column could "move" the row to a different range. Sounds like some fun testing there!

And things like write intents - would they get written to the new row location? (I presume so, but...)

And how about competing transactions that are trying to move the same row to different ranges?

Or competing transactions that are trying to move two distinct rows from different ranges to the same PK values in a third range.

Or a single transaction that swaps two rows - changes PK A to PK B and PK B to PK A.

And two competing transactions that attempt the same swap: App 1 changes PK A to PK B and App 2 changes PK B to PK A.

I'm not suggesting that this won't work, just that the testing will be... interesting.

**Comment by petermattis** [comment]
@JackKrupansky This will all "just work". The KV transaction layer handles all of these scenarios without difficulty.
