### ISSUE TITLE
kv,replication: replication report in `system.replication_critical_localities` reports healthy ranges as "at risk"

### ISSUE THREAD

**Issue by fabiog1901** [cockroachdb/cockroach#59480]
On a newly initialized cluster with v20.2.2, pulling a [Replication Report](https://www.cockroachlabs.com/docs/stable/query-replication-reports.html#find-out-which-databases-and-tables-have-ranges-in-critical-localities) returns below values.

```
root@localhost:26257/defaultdb> 
WITH at_risk_zones AS (
    SELECT
        zone_id,
        locality,
        at_risk_ranges
    FROM
        system.replication_critical_localities
    WHERE
        at_risk_ranges > 0
),
report AS (
    SELECT
        crdb_internal.zones.zone_id,
        target,
        database_name,
        table_name,
        index_name,
        at_risk_zones.at_risk_ranges
    FROM
        crdb_internal.zones,
        at_risk_zones
    WHERE
        crdb_internal.zones.zone_id = at_risk_zones.zone_id
)
SELECT DISTINCT * FROM report;

  zone_id |     target      | database_name | table_name | index_name | at_risk_ranges
----------+-----------------+---------------+------------+------------+-----------------
        0 | RANGE default   | NULL          | NULL       | NULL       |              1
        1 | DATABASE system | system        | NULL       | NULL       |             30
       16 | RANGE meta      | NULL          | NULL       | NULL       |              1
       17 | RANGE system    | NULL          | NULL       | NULL       |              2
       22 | RANGE liveness  | NULL          | NULL       | NULL       |              1
(5 rows)

Time: 519ms total (execution 519ms / network 0ms)
```

**Zendesk** : [7370](https://cockroachdb.zendesk.com/agent/tickets/7370)

gz#7370

**Comment by knz** [comment]
cc @darinpp @andreimatei do you have some idea about what is going on here?

NB: I already have informed support that we're expecting little bumps around this code, and that there should be a public issue (this one) so we can consider bug fixes and polish as part of our product roadmap. However the customer would appreciate some explanation about what happened.

cc @mwang1026 for triage and prioritization (should be part of "problems to solve" for v21.2)

**Comment by andreimatei** [comment]
I think maybe there's confusion about what "at risk" means. A range by itself is not "at risk" or "not at risk".  The determination is done on a range in conjunction with a locality. An entry from `system.replication_critical_localities` tells you whether a particular locality is critical for a range. *Some* locality is commonly critical for any range. For example, if you're only running in a single region, that region is critical *for everything*, and that's cool.

I believe you query is broken since the CTE can return multiple rows for the same `zone_id`, which I'm guessing is not what you want.

Does this help?

If you still think something is not working right, then you gotta tell me your `--locality's` and the output of `system.replication_critical_localities`.

**Comment by fabiog1901** [comment]
```
roachprod create `whoami`-geo -c gce -n 3 --gce-zones us-east4-b,us-west1-b,us-east1-b
roachprod stage `whoami`-geo release v20.2.2
roachprod start `whoami`-geo
```

Then connected to each node individually:

```
roachprod sql `whoami`-geo:1 | 2 | 3

> show locality;
                  locality
---------------------------------------------
  cloud=gce,region=us-east4,zone=us-east4-b
---------------------------------------------
  cloud=gce,region=us-west1,zone=us-west1-b
---------------------------------------------
  cloud=gce,region=us-east1,zone=us-east1-b
```

```
root@localhost:26257/defaultdb> WITH at_risk_zones AS (
    SELECT
        zone_id,
        locality,
        at_risk_ranges
    FROM
        system.replication_critical_localities
    WHERE
        at_risk_ranges > 0
),
report AS (
    SELECT
        crdb_internal.zones.zone_id,
        target,
        database_name,
        table_name,
        index_name,
        at_risk_zones.at_risk_ranges
    FROM
        crdb_internal.zones,
        at_risk_zones
    WHERE
        crdb_internal.zones.zone_id = at_risk_zones.zone_id
)
SELECT DISTINCT * FROM report;
  zone_id |     target      | database_name | table_name | index_name | at_risk_ranges
----------+-----------------+---------------+------------+------------+-----------------
        0 | RANGE default   | NULL          | NULL       | NULL       |              1
        1 | DATABASE system | system        | NULL       | NULL       |             30
       16 | RANGE meta      | NULL          | NULL       | NULL       |              1
       17 | RANGE system    | NULL          | NULL       | NULL       |              2
       22 | RANGE liveness  | NULL          | NULL       | NULL       |              1
(5 rows)

root@localhost:26257/defaultdb> select * from  system.replication_critical_localities;
  zone_id | subzone_id | locality  | report_id | at_risk_ranges
----------+------------+-----------+-----------+-----------------
        0 |          0 | cloud=gce |         2 |              1
        1 |          0 | cloud=gce |         2 |             30
       16 |          0 | cloud=gce |         2 |              1
       17 |          0 | cloud=gce |         2 |              2
       22 |          0 | cloud=gce |         2 |              1
(5 rows)
```

I think I understand what you're saying: in this case, the top hierarchy is `cloud` and that's the same value for all node, so as you said that looks like a "single region".

>  if you're only running in a single region, that region is critical for everything, and that's cool.

**Comment by andreimatei** [comment]
Did you want to close this issue?
Please file a bug against the respective docs page if you think something ought to have been clearer.

**Comment by fabiog1901** [comment]
Andrei, thank you for the clarification, indeed I will raise it to the docs team to clarify the expected output
