### ISSUE TITLE
sql: report accurate execution and network duration for schema changes in SHOW LAST QUERY STATS

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#59484]
**Describe the problem**

Altering PK on a large table returns with incorrect timing for execution of the change.

**To Reproduce**

Run a schema change on a large table and diagnose CLI output

```bash
NOTICE: primary key changes are finalized asynchronously; further schema changes on this table may be restricted until the job completes
ALTER TABLE
Time: 799.771s total (execution 0.063s / network 799.708s)
```

In my example, the output suggests network penalty of 800s and execution of 0.063s but in speaking with engineering, the opposite is true. 

**Expected behavior**

Provide clear metrics on execution and network latency.

**Environment:**
 - CockroachDB version 20.2.3
 - Server OS: CC managed cluster
 - Client app `cockroach sql`

**Additional context**

this leads to misleading information. CC @knz @arulajmani

**Comment by knz** [comment]
cc @rafiss for triage

**Comment by rafiss** [comment]
there's also a high network latency reported on `COMMIT` when doing the schema change inside a transaction:

```
root@:26257/defaultdb> begin;
BEGIN

Time: 146µs total (parse 12µs / plan 0s / exec 0s / other 198µs / network 146µs)

root@:26257/defaultdb  OPEN> alter table p alter primary key using columns (a,b);
ALTER TABLE

Time: 3.809ms total (parse 26µs / plan 845µs / exec 2.736ms / other 56µs / network 146µs)

root@:26257/defaultdb  OPEN> commit;
COMMIT

Time: 1.052941s total (parse 4µs / plan 0s / exec 0s / other 30.086ms / network 1.022851s)
```

@arulajmani @lucy-zhang do you know any details about how completion of a schema change job is communicated to the client? The network latency is computed here, and the `completedHook` is called in the CLI which happens after there are no more results to render: https://github.com/cockroachdb/cockroach/blob/8297ccd33a090ca75b1924c8df1d42eae15782d1/pkg/cli/sql_util.go#L926-L931

**Comment by rafiss** [comment]
comment from @arulajmani :
> the bulk of the work happens asynchronously, which doesn’t contribute towards the “execution latency” of the user transaction. The client waits until the schema change job completes and isn’t smart enough to account for this — so the client naively attributes it to network latency.

The polling for job completion happens inside of the call to `JobRegistry.Run()`: https://github.com/cockroachdb/cockroach/blob/3bae09b5d473e65479c68a221c05d3260cb31f4b/pkg/sql/conn_executor.go#L2352

**Comment by rafiss** [comment]
@arulajmani will give a quick look to see if there's a way to improve this.
