### ISSUE TITLE
sql: decimal columns don't enforce their scale when input is given in scientific notation with positive exponent equal to that scale

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#59489]
**Describe the problem**

Inserting a whole number written in scientific notation, such as `6E2`, into a decimal column with a fixed scale equal to the exponent (such as `DECIMAL(4,2)`), bypasses the normal casting/rounding/validation, resulting in an invalid value being stored. This can cause serialization issues later.

**To Reproduce**

```
root@:26257/defaultdb> create table width_example (id int primary key, val decimal(12,3));
CREATE TABLE

root@:26257/defaultdb> insert into width_example values (0, 6000) returning val;
val
6000.000

root@:26257/defaultdb> insert into width_example values (1, 6e3) returning val;
val
6E+3 (expected 6000.000)
```

Or

```
root@:26257/defaultdb> create table max_precision_bypass (id int primary key, val decimal(4,2));
CREATE TABLE

root@:26257/defaultdb> insert into max_precision_bypass values (0, 600);
ERROR: type DECIMAL(4,2) (column "val"): value with precision 4, scale 2 must round to an absolute value less than 10^2

root@:26257/defaultdb> insert into max_precision_bypass values (0, 6e2);
INSERT 1 (expected the same error)
```

**Expected behavior**

I think values input in this form should be subject to the same behavior as those input as decimals, or in scientific notation with any other exponent: rounding when they exceed the fixed width, padding when their width is smaller, and an error if the padding would cause them to exceed the maximum precision.

**Additional context**

This has led to errors when trying to encode the resulting values into Avro for changefeeds--the distinction between `6e2` and `600.00` would not survive being serialized into and then deserialized from the Avro encoding for decimals. See https://github.com/cockroachdb/cockroach/issues/38058 .

**Comment by rafiss** [comment]
From team discussion:
- we should be able to block the invalid insertions going forward.
- but dealing with existing data that has been stored when it shouldn't might be tricky.
  - can we return a notice or hint that the user has to update the data?
  - can we add a new builtin that can detect all invalid data in the tables? it would be expensive to run.

**Comment by ajwerner** [comment]
This feels like something which could be handled with a long running migration, maybe, but we'd want to be careful about the ux.

**Comment by otan** [comment]
what's interesting is that the direct casts hit this error message:

```
demo@127.0.0.1:26257/defaultdb> select 6e2::decimal(4,2);
ERROR: value with precision 4, scale 2 must round to an absolute value less than 10^2
SQLSTATE: 22003
demo@127.0.0.1:26257/defaultdb> select 6e3::decimal(12,3);
  numeric
------------
  6000.000
(1 row)
```

for the latter case, this statement breaks as this precondition is hit: https://github.com/cockroachdb/cockroach/blob/7d93e04308b5881c85a077a708dddafc136311a0/pkg/sql/sem/tree/casts.go#L598-L601 so it is inserted as 6e3.

**Comment by mgartner** [comment]
> which means something is doing the translating for us.

It's like optbuilder injecting the `crdb_internal.round_decimal_values` function: https://github.com/cockroachdb/cockroach/blob/b08b7cb2e0a557168eb33c717dc42aa5b2dfbdee/pkg/sql/opt/optbuilder/testdata/insert#L1187

This was added to try to conform to PG's decimal rounding behavior during INSERTs and UPDATEs. It was a very specialized solution at a time when we weren't aware that "assignment casts" exist.

This special handling for rounding decimals should be gutted once assignment casts are implemented. Related: #67083.

**Comment by mgartner** [comment]
Implementing assignment casts fixed this issue. I'll close this and add some regression tests in a PR.
