### ISSUE TITLE
cannot execute CREATE VIEW in a read-only transaction for temp view

### ISSUE THREAD

**Issue by wzrdtales** [cockroachdb/cockroach#59483]
When working with temp views, we want to use as of system time to avoid any locking on the table. If encapsulated in a transaction create temp view returns `cannot execute CREATE VIEW in a read-only transaction`. In my opinion this should not be the case for a temp view which is bound to that transaction.

**Comment by rafiss** [comment]
Hi @wzrdtales ! I don't think this is so simple since creating the view does cause some writes -- we need to create descriptors for that view.

cc @lucy-zhang who may know more in case this overlaps with Schema stuff

**Comment by lucy-zhang** [comment]
`CREATE VIEW` itself, like all other DDL statements, involve writing metadata and therefore can't be used with `AS OF SYSTEM TIME`. It sounds like you want `AS OF SYSTEM TIME` in the view query. This is being tracked in #50753. I'll close this issue, but please feel free to follow up in #50753 with details about your use case.
