### ISSUE TITLE
sql: Support (some) column type changes

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#5950]
Some aspects of a column's type can be changed after creation. For example, the length of a `VARCHAR(n)` can be changed (increasing the limit is easy; decreasing it requires a backfill to enforce the new limit). We should identify which type changes are feasible and support them.

This feature request is motivated by the Django ORM. One of the migration steps that it performs as a part of setting up a new database is the following statement:
`ALTER TABLE "auth_permission" ALTER COLUMN "name" TYPE varchar(255) USING "name"::varchar(255)`
(the previous type of the column is `varchar(50)`)

The `USING` clause is a postgres extension which apparently allows for arbitrary transformations to be done as a part of the schema change. I doubt we want to support the general form of that but we could either recognize the trivial cases or configure django not to use this extension (it doesn't look like django ever uses it in non-trivial ways).

**Comment by seiflotfy** [comment]
When enforcing a decrease from VARCHAR(n) to VARCHAR(n-x) do you just dismiss the last x?

**Comment by bdarnell** [comment]
I think it should be an error if any existing value is longer than the new limit. This matches the way that `ALTER TABLE t ADD CONSTRAINT foo UNIQUE (b)` will abort if it turns out that column `b` has duplicated values.

**Comment by wzrdtales** [comment]
Just stumbled upon this today while writing some migrations. It seems that currently no type changes are possible at all? Or is it just not documented?

**Comment by wzrdtales** [comment]
Especially asking as I am about to create a task that would handle this issue for my migration framework. If you don't plan to support data types I will add a routine that creates a new column copies over data removes the old and renames the new one. Which probably is quite zero downtime unfriendly as DDL and data manipulations cannot happen in the same transaction.

**Comment by bdarnell** [comment]
Currently, no type changes are supported and the only workaround is to add a new column and drop the old one. We would like to support type changes but have no definite plans to implement it at this time.

**Comment by wzrdtales** [comment]
@bdarnell Thanks for the response, good to know :)

**Comment by bobvawter** [comment]
Working on an RFC to support changing a column type: https://github.com/cockroachdb/cockroach/pull/24703

**Comment by bobvawter** [comment]
Closing this issue since #25777 has landed.  Will use #9851 to track fully-generalized column type changes.
