### ISSUE TITLE
sql: make schema change jobs to drop tables non-cancelable

### ISSUE THREAD

**Issue by lucy-zhang** [cockroachdb/cockroach#59545]
We saw in #59415 that it's currently possible for schema change jobs which drop descriptors to end up in the reverting state. But we don't have any good way of rolling back these jobs, so there's no point in letting them be cancelable (although they can still fail for other reasons, if our filtering for errors to retry on isn't perfect).

The effect of this is that cancelling a DROP TABLE at a certain point will render the table "dropped but not GC'd", the name exists and you can't drop it, and there are other subtleties. This might be recoverable via another schema change. But it's confusing for users.

We may even want to extend this to all schema change jobs without mutation IDs.

gz#8630

**Comment by lucy-zhang** [comment]
#61210 does this for schemas and databases. Tables could use the same treatment, since canceling those jobs is just as dangerous if done before draining names has completed.

**Comment by ajwerner** [comment]
@fqazi want to take this one and then, while you're at it, think about how this fits in to the `schemachanger`?
