### ISSUE TITLE
tracing: enable tracing in Honeycomb.io 

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#59559]
A customer expressed a desire to trace transactions end-to-end in Honeycomb. In order to do this they need two things added to statement traces:
* Zipkin B3 header propagation
* 128-bit trace IDs

Jira issue: CRDB-3272

**Comment by thtruo** [comment]
cc @andreimatei for awareness and input. According to the customer, even if they were to use https://github.com/honeycombio/honeycomb-opentracing-proxy they'd still need the Zipkin B3 header propagation and 128-bit trace IDs to proceed.

**Comment by andreimatei** [comment]
I'm not sure what this means. Have you tried this proxy thing?
When configured accordingly, we use the Zipkin opentracing client, so my guess is that we should work.
My guess is that they're interested in propagating a trace id from the client into crdb? We don't support that, independent of the trace collector.
