### ISSUE TITLE
sql: support placeholders in LIMIT clauses

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#5955]
`SELECT ... LIMIT $1` currently fails with `argument of LIMIT must not contain variables`. This is due to `parser.ContainsVars` returning true if the expression contains a `ValArg` or `DValArg` (i.e. a placeholder). In some contexts those nodes are considered "variable", but they shouldn't be in this one.

**Comment by RaduBerinde** [comment]
Even if that ContainsVars call doesn't fail, the following code which attempts to evaluate to a DInt value will. There is a bunch of machinery that is missing to make placeholders work in limits, I'm looking into it.
