### ISSUE TITLE
bulk: round out userfile functionality with userfile get

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#59564]
To use `userfile` as a standalone, true "storage" alternative, we need to implement userfile get. This would enable export and backup to use `userfile` as storage.

Minimum scope is to do just `userfile get` of one file. A user would then have to do something like
```
LOOP OVER cockroach userfile list --url='connection' --> cockroach userfile get
```

*Alternative solutions*
Ideally we could do `cockroach userfile get 'userfile:///backups/2020/01/30/*' with wildcard and get multiple files.

**Comment by dt** [comment]
#60490
