### ISSUE TITLE
[suggestion] inline transaction priority for a single sql

### ISSUE THREAD

**Issue by kocoten1992** [cockroachdb/cockroach#59577]
**Is your feature request related to a problem? Please describe.**
I've notice we have transaction priority - https://www.cockroachlabs.com/docs/stable/begin-transaction.html

The problem is, in order to use we must issue a `begin` clause (that take up a round trip to database), and then `commit` (another round trip), think that might be a bit excessive.

**Describe the solution you'd like**
I don't have clear idea for this, but for example we could do this to eliminate the round trip:
```sql
update databases set ranking = 1 where name = 'cockroachdb' priority high;
```

Or any syntax that allowed us to set priority inline.

For extra context: I'm come from mysql, where we don't have the luxury of `RETURNING` clause.

Before I know that clause:
```
// before
begin;
select ...;
update...;
commit;

// after
update ... returning;
```

Since I discover that clause combined with CTE/subquery, combined with serialize transaction autocommit, I've eliminate so many sql query in our application - by combine it together. (the extreme case where combine 10 queries into a single query - and it very efficient).

Now I'm looking to eliminate the triple round trip if I need to use transaction priority.

Thanks!

Jira issue: CRDB-3268

**Comment by otan** [comment]
not sure where transaction priorities land, i'm guessing KV as SELECT FOR UPDATE was mostly at that layer, but if i'm wrong feel free to rearrange

**Comment by mwang1026** [comment]
@otan looks like it's failing on syntax parsing, so SQL would need to fix parsing first. We *think* on KV that we have everything to get it to work. Could SQL look into whether that's the case?

**Comment by mwang1026** [comment]
If it turns out KV doesn't allow it we'll dive further

**Comment by rafiss** [comment]
We already support this since we have the `default_transaction_priority` session variable.

If you'd like to configure that to have a different value per database, you could use `ALTER DATABASE db SET default_transaction_priority = 'value';`. You can also set it explicitly using `SET default_transaction_priority = 'value';`.

**Comment by kocoten1992** [comment]
Hello, just to be clear, using `default_transaction_priority` is meant to be 2 queries:
1. set `default_transaction_priority`
2. query

What suggested above is a single query only, 2 queries mean send 2 times, wait for 2 network round trip.

I could do `SET default_transaction_priority = 'value'; SELECT 1`, but then this query is no longer able to use prepared statement, and if I use asynchronous pg driver, it is also a new of challenge...

**Comment by kocoten1992** [comment]
```
customize that per-user instead of per-database
```
I think this work, but what I mean is per-query granular control, but that would open another can of worm when using it with mixed transaction priority level, eg:

```
with a as (select name where id = `1` for update low priority), b as (select name where id = `1` for update high priority) select 1;
```

I'm happy to have this issue closed though, just a thought.
