### ISSUE TITLE
SQL pods should serve basic obserability routes on an HTTP serverr

### ISSUE THREAD

**Issue by joshimhoff** [cockroachdb/cockroach#59585]
**Is your feature request related to a problem? Please describe.**

@knz points out that the SQL pods serve a minimum of stuff over HTTP. In particular, they don't serve the obserability routes that operators need to troubleshoot. A basic thing we believe is missing is pprof, which is hugely useful. In a sense though this is a broad feature request. What other obserability routes do we want in the stateless SQL pods? Needs thought / discussion.

@knz says:

"""
ok, I stand corrected. There is a HTTP server in there. IT's completely dumbed down to the essentials and serves only /health and the prometheus vars
"""

**Additional context**
I expect this is a known issue or at least that there has been other convos about SQL pod obserability / admin UI. As free-tier is about to launch to prod, getting some basic stuff in place such as pprof is important!

Epic: CRDB-8505

CC @mwang1026 and @thtruo as Raphael suggests bringing this to your "desks" :)

**Comment by knz** [comment]
cc @tbg for milestone E

**Comment by knz** [comment]
This was achieved via #75852
