### ISSUE TITLE
SQL pod health check should check that SQL is ready to serve connections, possibly other things

### ISSUE THREAD

**Issue by joshimhoff** [cockroachdb/cockroach#59584]
**Is your feature request related to a problem? Please describe.**

@knz points out that the SQL pod health check is minimal. It doesn't check anything; it just returns healthy. This adds some value in that is shows the pod is at least able to serve HTTP. We should also check that the pod is ready to serve SQL connections. Possibly there are additional things to check too, but checking that the pod can serve SQL is a good start.

CC @mwang1026 and @thtruo as Raphael suggests bringing this to your "desks" :)

Epic: CRDB-8501

Jira issue: CRDB-6290

**Comment by knz** [comment]
cc @tbg for milestone E

**Comment by knz** [comment]
we have fixed this in 23.1.
