### ISSUE TITLE
sql: secondary indexes should include implicit partitioning columns of primary index

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#59583]
For implicitly partitioned tables, including `REGIONAL BY ROW` tables, all indexes are implicitly partitioned by the same columns. Therefore, if an index join is required, all values of the implicit partitioning columns are available from the secondary index. However, this is not the case for implicitly partitioned indexes. Consider the following example, where the primary index is implicitly partitioned, but the secondary index is not. Notice what happens when we try to execute a query that requires an index join:
```
demo@127.0.0.1:26257/movr> SET experimental_enable_implicit_column_partitioning = true;
SET

Time: 1ms total (execution 0ms / network 0ms)

demo@127.0.0.1:26257/movr> CREATE TABLE t (
  r INT,
  x INT PRIMARY KEY,
  y INT,
  z INT,
  INDEX (y)
) PARTITION BY LIST (r) (
    PARTITION p1 VALUES IN (1)
);
NOTICE: creating non-partitioned index on partitioned table may not be performant
HINT: Consider modifying the index such that it is also partitioned.
CREATE TABLE

Time: 3ms total (execution 3ms / network 0ms)

demo@127.0.0.1:26257/movr> show create table t;
  table_name |                      create_statement
-------------+-------------------------------------------------------------
  t          | CREATE TABLE public.t (
             |     r INT8 NULL,
             |     x INT8 NOT NULL,
             |     y INT8 NULL,
             |     z INT8 NULL,
             |     CONSTRAINT "primary" PRIMARY KEY (x ASC),
             |     INDEX t_y_idx (y ASC),
             |     FAMILY "primary" (r, x, y, z)
             | ) PARTITION BY LIST (r) (
             |     PARTITION p1 VALUES IN ((1))
             | )
             | -- Warning: Partitioned table with no zone configurations.
(1 row)

Time: 6ms total (execution 5ms / network 0ms)

demo@127.0.0.1:26257/movr> explain (verbose) select * from t@t_y_idx;
                        info
----------------------------------------------------
  distribution: full
  vectorized: true

  • index join
  │ columns: (r, x, y, z)
  │ estimated row count: 1,000 (missing stats)
  │ table: t@primary
  │ key columns: r, x
  │
  └── • scan
        columns: (r, x, y)
        estimated row count: 1,000 (missing stats)
        table: t@t_y_idx
        spans: FULL SCAN
(14 rows)

Time: 3ms total (execution 2ms / network 0ms)

demo@127.0.0.1:26257/movr> select * from t@t_y_idx;
ERROR: unable to vectorize execution plan: requested column r not in index
```
The optimizer currently assumes that the secondary index `t_y_idx` contains the key columns `r` and `x` needed to perform the index join as shown in the explain plan. But as shown by the error at the bottom, `t_y_idx` doesn't actually contain `r`. We could change the optimizer to not include `r` in the scan of `t_y_idx`, but then there would be no way to perform an index join with the primary index. This seems extremely suboptimal.

This would be fixed if we change the index creation logic to automatically include all implicit partitioning columns of the primary index along with the primary key columns in every index if they aren't already present.

cc @otan

**Comment by otan** [comment]
hmm, i thought indexes always pointed back to the primary key, and it should follow the same rules since we're storing the same `ColumnIDs`.

do you know where the code to do this is? can take a look at this when i wake up tomorrow.

**Comment by otan** [comment]
ah i see, it is encoded in `extra_column_ids
