### ISSUE TITLE
The show table command stuck 

### ISSUE THREAD

**Issue by yanjh007** [cockroachdb/cockroach#59587]
**Describe the problem**

After connect cockroachdb cluster with root account and cockroach sql, change the database, and input the show tables command , it's stuck and reponse nothing for a long time until I control-c it to quit.

**To Reproduce**
1. the root user login login is OK.
2. show tables in the default database is ok.
3. switch database is ok 
4. select some data from a table is ok ...
5. show tables command is not .....ok , the world stoped
6. In the admin ui , the tables shows as normal 

**Expected behavior**
of cause show the table list

**Comment by yanjh007** [comment]
It's sames recovery, but it's absolutely some wrong within it.
 
![屏幕截图 2021-01-30 113100](https://user-images.githubusercontent.com/8425475/106346003-cadaaf80-62ee-11eb-8144-6f8515048b21.png)

what should I do next?

**Comment by jordanlewis** [comment]
I'm assuming this situation resolved itself, so I'll close it. Please open a new issue if you find a bug, or open a discussion in https://forum.cockroachlabs.com or https://cockroa.ch/slack if you have general discussion topics or need help from the community.
