### ISSUE TITLE
workload: add new 21.1 DDL syntax to schemachange workload

### ISSUE THREAD

**Issue by thoszhang** [cockroachdb/cockroach#59595]
- [ ] `UNIQUE WITHOUT INDEX` constraints
- [x] `ALTER TYPE ... DROP VALUE` #59197
- [ ] virtual computed columns
- [ ] multi-region
  - [ ] `ADD/DROP REGION`
  - ...

List is incomplete right now.

Jira issue: CRDB-3265

Epic CRDB-19168

**Comment by postamar** [comment]
Re-triaging. Is there any 21.2 syntax we need to support? I'm guessing no, but there is some for 22.1.
