### ISSUE TITLE
Cannot insert or query in new table

### ISSUE THREAD

**Issue by yanjh007** [cockroachdb/cockroach#59618]
**Describe the problem**

I create a new table in crdb, but I cannot insert any data, even query from the empty table

**To Reproduce**

here is my steps:

1. My crdb has a show table and connection issue before
2. But I still connect with cockroach sql and root user, and executed the show tables command, and go to sleep
3. When i waked up, I found the command finished, it toke 9 hours, so I think the cluster was recovered.
4. I take some data update as usually , it sames fine
5. And I tried to import a new table use dbeaver, it was hunged ...
6. I connected cluster with cockroach sql agian, and create a table, and insert a test record, it also stucked.
7. I waited for a other night. it not finished insert process
8. In other table query and update sames OK

**Expected behavior**
Of cause I should create a new table and insert data into it.

**Additional data / screenshots**
![屏幕截图 2021-01-31 114432](https://user-images.githubusercontent.com/8425475/106373971-cf1fcf00-63b9-11eb-890d-3a3a604f32c2.png)

**Environment:**
 - CockroachDB version [20.2.4]
 - Server OS: [Linux/Debian9]
 - Client app [ `cockroach sql`, dbeaver]

**Additional context**
In the AdminUI, the nodes are all live, no replicating and unavailable range. 
But the Sessions, Transactions and Statements page cannot open with error promise timeout.

**Comment by jordanlewis** [comment]
If you can make reproduction steps for this case, we would be very interested to see it. Unfortunately, we cannot reproduce this on our side.
