### ISSUE TITLE
teamcity: PR merge failed because of failure in "Essential CI" but with all dependencies green

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#59641]
Observed in:
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/2632724?buildTab=dependencies&mode=chain&selectedBuildId=2632723

All the CI dependencies are satisfied (green everywhere)

However the connecting dependency "Essential CI" is red and caused the entire build to fail.

This is surprising because "Essential CI" does not have rules of its own. So there is literally nothing (that I know of) that it can fail on.

So what caused this failure and prevented the entire CI run from succeeding?

cc @jlinder for triage

**Comment by jlinder** [comment]
Somehow "Essential CI" is reporting that "... Unit Tests / test" failed with one test failure. :scratches_head: on how or why that could happen when the related run of "Unit Tests / test" ran successfully...

<img width="745" alt="Screen Shot 2021-02-01 at 10 56 11 AM" src="https://user-images.githubusercontent.com/224132/106483577-add3e700-647c-11eb-88e4-4ee7a4c78ada.png">

**Comment by jlinder** [comment]
The time of that failure is 4:53:55. But the [logs](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_Test/2632725?showLog=2632725) on the "Unit Tests / test" run show it _started_ running at 5:08:37.

<img width="1046" alt="Screen Shot 2021-02-01 at 11 02 52 AM" src="https://user-images.githubusercontent.com/224132/106484057-39e60e80-647d-11eb-989c-8dfbaae97916.png">

**Comment by jlinder** [comment]
This is a head scratcher.

**Comment by knz** [comment]
I think we use preemptable instances for tests nowadays? Is it possible there was a race condition and a preemption was mistakenly picked up by TC as an unrecoverable failure?

**Comment by jlinder** [comment]
I'd expect that, if a run of "Unit Tests / test" was preempted then that should be the run that is linked in the dependency graph. Maybe there is a possibility of a race condition. Perhaps early in the job start process where an agent was told to run the job and it gets killed before it can report any info back to the leader?

I checked all the other jobs that ran as part of the build. Everything else that was a left-most leaf started their run at the same minute that the entire job started running. It's definitely odd that "Unit Tests / test" started 26 minutes later.

**Comment by knz** [comment]
>  It's definitely odd that "Unit Tests / test" started 26 minutes later.

That's my experience of what is reported in the test results when instances get preempted.

What would be a good "next action" here? I'm ok with "living with it" but I believe it would be good to document this behavior. Do we have TC docs on the wiki already?

**Comment by jlinder** [comment]
> > It's definitely odd that "Unit Tests / test" started 26 minutes later.
> 
> That's my experience of what is reported in the test results when instances get preempted.

Interesting. The experience I've usually seen is that a host gets shut down in the middle of a run and it shows in the logs. I haven't seen it get killed before the job starts and then causes the one build config's run to not start for so long.

> What would be a good "next action" here? I'm ok with "living with it" but I believe it would be good to document this behavior. Do we have TC docs on the wiki already?

I think the next action is "document this behavior, that we'd like it reported if someone sees this again, and move on". We do have some TC docs in the wiki [here](https://cockroachlabs.atlassian.net/wiki/spaces/devinf/pages/140312691/TeamCity) which embeds [this page](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73105870/TeamCity+Continuous+Integration) on the public wiki.

**Comment by knz** [comment]
> I haven't seen it get killed before the job starts and then causes the one build config's run to not start for so long.

Another possibility is that there was simply no agent available for so long. But that wouldn't explain the error in the "CI" target in the end.

> We do have some TC docs in the wiki here which embeds this page on the public wiki.

Ok then let's add a few sentences in there.

**Comment by knz** [comment]
I added this on the public wiki:
![image](https://user-images.githubusercontent.com/642886/107493716-3bef5200-6b8e-11eb-9776-8420012d64c0.png)
