### ISSUE TITLE
Strange results when DECIMAL precision = scale

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#5965]
Currently, a `DECIMAL` column's `precision` can equal its `scale`. I'm not sure when that ever makes sense, but in any case, it currently produces some weirdness:

```
root@:26257> create table decimals (a DECIMAL(5,5));
CREATE TABLE

root@:26257> show columns from decimals;
+-------+--------------+-------+----------------+
| Field |     Type     | Null  |    Default     |
+-------+--------------+-------+----------------+
| a     | DECIMAL(5,5) | true  | NULL           |
| rowid | INT          | false | unique_rowid() |
+-------+--------------+-------+----------------+

root@:26257> insert into decimals values (DECIMAL '0.12345');
INSERT 1

root@:26257> select * from decimals;
+--------+
|   a    |
+--------+
| 1234.5 |
+--------+

root@:26257> insert into decimals values (DECIMAL '1.2345');
pq: too many digits for type DECIMAL(5,5) (column "a")

root@:26257> insert into decimals values (DECIMAL '1.235');
pq: too many digits for type DECIMAL(5,5) (column "a")
``` 

cc @nvanbenschoten, who mentioned wanting to look into this.

**Comment by JackKrupansky** [comment]
Just to be clear about what is really happening, a scale of 5 means maintaining 5 digits to the right of the decimal, so the insert of 1.2345 is really treated as 1.23450, but then there are six digits when the maximum precision is only 5.

Limit yourself to only fractional values when precision equals scale - the number of digits to the left of the decimal must be no more than precision minus scale. IOW, when precision equals scale, the value must be less than 1.0.

FWIW, if I try SELECT DECIMAL(5,5) '1.2345' with Postgres in SQLZoo, I get this error: "numeric field overflow DETAIL: A field with precision 5, scale 5 must round to an absolute value less than 1"

**Comment by seiflotfy** [comment]
@jseldess try https://github.com/cockroachdb/cockroach/pull/5975 ?
