### ISSUE TITLE
log: want better docs on --log

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#59674]
A few days ago I wanted to set the logs dir for a node and I was at a loss about what the new way of doing that is.
The description on --log say "see the docs". Which docs? Perhaps they haven't been written yet; please don't forget to add a link when they are.
But regardless of any docs, it'd be great if the flag description would give me a couple of examples for simple things. And for not so simple things, perhaps people can sometimes extrapolate from these few examples. Getting everything to a dir should be such an example.
Also it'd be cool if the `--log-dir` deprecation message also gave an example about how to replace it.

**Comment by knz** [comment]
> Which docs? Perhaps they haven't been written yet; please don't forget to add a link when they are.

They have not been written yet indeed; @mikeCRL is working on it.

Until then, you can find the reference doc with examples [in the RFC here](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20200728_log_modernization.md#configuration---command-line-and-yaml-format)

Also example of the default config with `cockroach debug check-log-config`.



>  Also it'd be cool if the --log-dir deprecation message also gave an example about how to replace it.

That is already the case.

**Comment by andreimatei** [comment]
> > Also it'd be cool if the --log-dir deprecation message also gave an example about how to replace it.

> That is already the case.

Are you calling me dumb or lazy? :)
The message says "Flag --log-dir has been deprecated, use --log instead to specify file-defaults.dir." What am I supposed to do with that?
```
./cockroach start --insecure --log=file-defaults.dir=/home/andrei/lll
ERROR: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `filedef...` into logconfig.Config
Failed running "start"
```
Also tried 'file-defaults:{dir:/home/andrei/lll}'. 

I think you considering that the message for --log-dir is just fine exemplifies the disconnect between us. I would challenge you to pick one random person and ask them to use this flag to set the log dir. Watch over their shoulder. If they succeed, I will shut up. FWIW, I was trying with Nathan standing next to me. We simply failed. Even now with more time, I'm still failing. Even reading the RFC, I'm still failing. (5 minutes later - ah I need some damn spaces in there).
Once we decide to make a flag take json (quite the controversial decision in my opinion... Writing json in your terminal is not really a thing...) we *have to* go out of our way to put snippets that people can copy-paste. Nobody can type this stuff; copy-pasting is the only possible hope. There need to be examples after examples after examples in a form that I can literally paste into my terminal.

Other suggestions:
- Reference  `cockroach debug check-log-config` in the description of the log file.
- Make --log able to take its input from a file. If it already does, talk about it in the description of the log file.

**Comment by mikeCRL** [comment]
@taroface is covering the docs for this feature, for future reference (and as an FYI to him, in case this thread might still inspire any further ideas for doc content).
