### ISSUE TITLE
server: SQL explorer leaks server-side traces

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5969]
Reproduce:
- start a single-node
- open the UI and poke around in the system database (or just show the databases; ought to be enough)
- close the browser window
- go to http://localhost:8080/debug/requests?fam=sql.root&b=-1&exp=1 and see that there are some active traces which belong to the backend logic in the ui clicks

**Comment by tschottdorf** [comment]
Ah, just saw now that there's a limit for 100 trace entries, so we should be good. That wasn't obvious from looking at the trace endpoint because I'm running a lot of statements in each batch. We should consider truncating what we log into the traces.

**Comment by spencerkimball** [comment]
Not reproducible.
