### ISSUE TITLE
More detail on Explain Plans

### ISSUE THREAD

**Issue by pxlogan** [cockroachdb/cockroach#59701]
**Is your feature request related to a problem? Please describe.**
I'm trying to do three things:
1. Capture explain plans so that I can compare explain plans from new versions of the code with the current version
2. Generate flamegraphs, like https://github.com/mgartner/pg_flame (also needs https://cockroachlabs.atlassian.net/browse/CRDB-1580)
3. Provide more intuitive views of the explain plan, like https://explain.depesz.com or http://tatiyants.com/postgres-query-plan-visualization/

The text versions of explain analyze plans do not contain times, tuple counts or row counts, data read volumes, etc. To see this, you need to use the decode.html tool, but I don't want to do that, because I can't scrape the generated page, I can only look at it.

The Jaeger trace, trace.txt and trace.json do contain timings, but it's really not obvious how to tie them back to steps in the explain plan.

**Describe the solution you'd like**
Absolute first prize would be something that was a) identical in format to PostgreSQL and b) allowed JSON output

However, I guess that some fairly fundamental aspects of your explain plans don't map onto PostgreSQL. Ideally, I'd like it to be as close as possible to this, though.

**Describe alternatives you've considered**
The Jaeger trace and trace.txt

**Additional context**

gz#7292

**Comment by awoods187** [comment]
Many of the points in here will be addressed in 21.1 however a few more remain. Issues like this that contain many different points should be broken up into smaller issues that can be addressed independently. I'm going to close this issue but link to a few remaining open issues given the progress in 21.1. Persisting explain plan change https://github.com/cockroachdb/cockroach/issues/60462, json format https://github.com/cockroachdb/cockroach/issues/60464
