### ISSUE TITLE
opt: select cost is incorrect when there is a limit hint

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#59713]
Consider the following example:
```
SET CLUSTER SETTING sql.stats.automatic_collection.enabled = false;

CREATE TABLE tab (
	id INT PRIMARY KEY,
	geog GEOGRAPHY,
	INVERTED INDEX (geog)
);

ALTER TABLE tab INJECT STATISTICS '[
    {
        "columns": [
            "id"
        ],
        "created_at": "2021-01-01 00:00:00",
        "distinct_count": 500000,
        "name": "__auto__",
        "row_count": 500000
    }
]';

EXPLAIN (OPT, VERBOSE) SELECT id FROM tab@primary
WHERE st_dwithin(geog, st_makepoint(1.0, 1.0)::geography, 200)
LIMIT 10;
                                                                            info
------------------------------------------------------------------------------------------------------------------------------------------------------------
  project
   ├── columns: id:1
   ├── cardinality: [0 - 10]
   ├── immutable
   ├── stats: [rows=10]
   ├── cost: 505200.624
   ├── key: (1)
   ├── prune: (1)
   └── limit
        ├── columns: id:1 geog:2
        ├── cardinality: [0 - 10]
        ├── immutable
        ├── stats: [rows=10]
        ├── cost: 505200.514
        ├── key: (1)
        ├── fd: (1)-->(2)
        ├── select
        │    ├── columns: id:1 geog:2
        │    ├── immutable
        │    ├── stats: [rows=55000, distinct(2)=50000, null(2)=0]
        │    ├── cost: 505200.404
        │    ├── key: (1)
        │    ├── fd: (1)-->(2)
        │    ├── limit hint: 10.00
        │    ├── prune: (1)
        │    ├── scan tab
        │    │    ├── columns: id:1 geog:2
        │    │    ├── flags: force-index=primary
        │    │    ├── stats: [rows=500000, distinct(1)=500000, null(1)=0, distinct(2)=50000, null(2)=5000]
        │    │    ├── cost: 200.383636
        │    │    ├── key: (1)
        │    │    ├── fd: (1)-->(2)
        │    │    ├── limit hint: 90.91
        │    │    └── prune: (1,2)
        │    └── filters
        │         └── st_dwithin(geog:2, '0101000020E6100000000000000000F03F000000000000F03F', 200.0) [outer=(2), immutable, constraints=(/2: (/NULL - ])]
        └── 10
(37 rows)
```
Notice that the cost of the scan is relatively small (~200), which is due to the limit hint. The cost of the select, however, is over 500,000, because it is not taking the limit hint into account. The predicate `st_dwithin` is relatively expensive to execute, so the assumption that it must be executed on 500,000 rows (the number of input rows ignoring the limit hint) results in a significantly higher cost than if the limit hint were taken into account and an estimate of ~90 rows were used instead.

**Comment by mgartner** [comment]
Limit hints are part of `physical.Required` which are build top-to-bottom, so I don't see a way to make `Select` take it's input's limit hint (90.91 in this case) into account.

In this case, the limit hint of the Scan is calculated as the limit hint of the Select multiplied by the ratio of the Selects input rows to output rows, `10 * (500000/55000) = 90.91`, [here](https://github.com/cockroachdb/cockroach/blob/e3c1d32b3f045a960635fa6bd6737d969d554108/pkg/sql/opt/xform/physical_props.go#L128-L131). We could duplicate this arithmetic in `computeSelectCost`, but that seems less than ideal. I'm open to better ideas if you have any, @radu @rytaft.

**Comment by RaduBerinde** [comment]
Yeah, we'd need to do the same arithmetic. We might be able to just use the `Selectivity` field of the `Stats` directly, e.g. `inputRowCount = math.Min(inputRowCount, LimitHint / Stats.Selectivity)`.
