### ISSUE TITLE
sql: prohibit PARTITION [ALL] BY for multiregion tables

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#59719]
A lot of code at the moment assumes vanilla PARTITION BY statements. If the user defines their own PARTITION BY on these tables, what should we do? Block them? Allow them but promise nothing when altering between locality configs?

**Comment by ajstorm** [comment]
Is this issue also meant to block moving to multi-region tables if there are zone configs present (at the database or table level)?  If not, is there another issue for that?

**Comment by otan** [comment]
yeah this is the blanket issue
