### ISSUE TITLE
bazel: ensure all `go test`s are runnable via Bazel

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#59724]
This is a tracking issue for testing CockroachDB code with `bazel test`.

- [ ] Investigate test types and identify special tests that we think will require particular attention to get working in the Bazel sandbox. This especially applies to E2E tests.
- [ ] Improve test infrastructure in CI so TeamCity is just as informative when running tests using Bazel as when running without.
- [ ] For all tests, ensure they work w/ `bazel test`, and make sure they get run on a regular basis in CI so they don't break.

Epic CRDB-8036

**Comment by rickystewart** [comment]
Update: today, all CRDB unit tests are runnable via Bazel. The main remaining work under the umbrella of this tracking issue is #59446.

**Comment by jlinder** [comment]
Closing in favor of https://github.com/cockroachdb/cockroach/issues/59446 since only the acceptance tests are left.
