### ISSUE TITLE
sql/sem/tree: parse ISO8601 format with decimal places for interval types

### ISSUE THREAD

**Issue by keithdoggett** [cockroachdb/cockroach#59720]
We do not parse `SELECT INTERVAL 'P1Y2M3DT4H5M6.235S';` correctly on CockroachDB, but this successfully parses in Postgres:

```
psql (13.1)
Type "help" for help.

otan=# SELECT INTERVAL 'P1Y2M3DT4H5M6.235S';
             interval
-----------------------------------
 1 year 2 mons 3 days 04:05:06.235
(1 row)

```

Changes should be made in https://github.com/cockroachdb/cockroach/blob/3699ce67835301e580bace3976bb6c2f3e0a32bf/pkg/sql/sem/tree/interval.go#L188

With unit tests added here:
https://github.com/cockroachdb/cockroach/blob/3699ce67835301e580bace3976bb6c2f3e0a32bf/pkg/sql/sem/tree/interval_test.go#L46

----

Original:

There are two errors coming from the `PostgresqlIntervalTest` (`test/cases/adapters/postgesql/interval_test.rb`) in ActiveRecord.

```
Error:
PostgresqlIntervalTest#test_interval_type:
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  error in argument for $2: could not parse string "P1Y2M3DT4H5M6.235S" as interval
```

```
Error:
PostgresqlIntervalTest#test_interval_type_cast_from_numeric:
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  error in argument for $1: could not parse string "PT36000.000S" as interval
```

Running `SELECT INTERVAL 'P1Y2M3DT4H5M6.235S';` in a SQL shell gives the following response:

```
ERROR: could not parse "P1Y2M3DT4H5M6.235S" as type interval: interval: unknown unit . in ISO-8601 duration P1Y2M3DT4H5M6.235S
```

This indicates that using a decimal for seconds is causing the error.

**Comment by rafiss** [comment]
Looks like https://github.com/senseyeio/duration/blob/7c2a214ada46/duration.go#L31 is a reasonable reference we could use. just a simple regex

**Comment by shikamaru404** [comment]
hi @keithdoggett @rafiss 
im new to the community
this seems so great to be my first issue!
If nobody is working on it, I would like to try

**Comment by rafiss** [comment]
@shikamaru404 welcome! thank you for your interest! please go ahead and try it out. when you submit a PR, please add @otan and me as reviewers.

**Comment by shikamaru404** [comment]
hi @rafiss 
Should the changes be in function `sqlStdToDuration` (`cockroach/pkg/sql/sem/tree/interval.go`)?
Seems that function `iso8601ToDuration` (`cockroach/pkg/sql/sem/tree/interval.go`) is responsible for parsing iso8601.

**Comment by otan** [comment]
@shikamaru404 seems like you're right :)
