### ISSUE TITLE
sql: User-friendly syntax to opt-out of non-voting replicas

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#59756]
Currently, if customers want to opt-out of using non-voting replicas, they need to directly modify zone configurations directly.  It would be a better UX if users could issue higher level SQL commands to opt-out.  

Epic CRDB-1552

Jira issue: CRDB-3240

**Comment by awoods187** [comment]
I think this should track the more generalizable ability to add/remove non-voting replicas via SQL.

**Comment by ajstorm** [comment]
Epic CRDB-1552
