### ISSUE TITLE
sql: update show create tables command to show schema_name and add semi colons

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#59772]
The goal is to make the format for `SHOW CREATE TABLE` and `SHOW CREATE TABLES` the same.

Follow up from https://github.com/cockroachdb/cockroach/pull/59412

**Comment by vy-ton** [comment]
@RichardJCai I hadn't thought about the confusion between `TABLE` vs `TABLES`

Should we make the multiple table version `SHOW CREATE TABLE t1, t2` and avoid introducing `TABLES` altogether?

**Comment by RichardJCai** [comment]
Not applicable anymore with https://github.com/cockroachdb/cockroach/pull/59412#issuecomment-778423545 being closed.

Will reopen if we ever find it necessary.
