### ISSUE TITLE
sql/schemachanger: prerequisites to setting schema changer "on" by default

### ISSUE THREAD

**Issue by lucy-zhang** [cockroachdb/cockroach#59788]
- [x] GC dropped indexes.
- [x] Disable the new schema changer for computed columns. See #59149.
- [x] Ensure that only one "new" schema change can be running on a table at a time, by restarting transactions that would initiate new schema changes (either from the old or the new schema changer) until there are no preexisting mutations on the table.
- [x] Support reverting schema changes on failure or job cancelation.
- [x] Properly checkpoint and read job progress for the index backfill.

Epic: CRDB-2356

Jira issue: CRDB-3234

**Comment by ajwerner** [comment]
Discussion about errors, reverting, and cancellation to likely be split out into another issue:

* Once a schema change has reached a state where elements being dropped have entered `DELETE_ONLY`, they can't ever go back to `PUBLIC` and thus the schema change can't really be reverted.
* At this point, we'd want to mark the job as uncancelable.
* Given that, it's important to think about how errors during schema change execution interact with the job state.
* Ideally, all of the failures which are permanent would be understood and explicitly marked and everything else would be retryable. Unfortunately, that's not the case; we really don't know what the set of all permanent errors. 
    * In the case where it's still safe to revert, that's fine.
    * The state where it's not safe to revert, it's a lot less fine, but that state space is quite a bit smaller.
* The proposal of the moment is to treat all errors as retryable during execution once we reach the `uncancelable` state.
    * This may not be desirable.
    * We may end up in an infinite loop.
    * #44594 would probably help and this situation is much less scary because we know that the work which must be done in this state is not going to be expensive. 
    * With #44594, I'd feel comfortable retrying these forever.
* Another tangentially related question is what to do if we hit an error during `OnFailOrCancel`.
    * Even with #44594, retrying these forever is scary.
    * In https://github.com/cockroachdb/cockroach/issues/46541 we decided to just have the job permanently fail.
    * This decision had the unfortunate property that usually when somebody notices that the table is in a bad state, the job is gone.
        * One idea to cope with this is a new terminal state for jobs that we won't ever delete.
        * That has its own risks but they are lower then just running the job forever
    * One reason to retry forever would be that a point release might fix the bug and allow progress to occur.
         * If we were super adventurous we might try to suspect execution of the job until an upgrade occurs.

**Comment by postamar** [comment]
We've done all of this, closing.
