### ISSUE TITLE
Update CDC roachtest

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#59808]
There are few issues with the existing cdc roachtest:
  * It relies heavily on GCE.  It does not work on any other cloud.
  * It requires existence of world writable buckets.  These assumptions break when e.g. security locks down those permissions.  We don't know about that until the test starts failing.
  * Existence of writable external buckets also makes the test non-hermetic.
  * The test is unique in that it depends on the existence of large external binaries (kafka) that it needs to stage.  This, in turn, makes the test less test-focused, and adds a lot of infrastructure and setup complexity.  Perhaps the staging of large binaries could be moved to e.g. roachprod.

Jira issue: CRDB-3230

**Comment by stevendanna** [comment]
An additional issue:

- The tests use confluent 4.0. In confluent 4, the schema-registry will only start on sufficiently old versions of Java because it depends on javax packages that have been removed in more recent versions.

**Comment by miretskiy** [comment]
stale.
