### ISSUE TITLE
sql: dropping enum values used in view/default/computed expressions may corrupt them

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#59807]
**Describe the problem**

Type descriptors only track dependencies based on the type of the column. We don't track dependencies if an enum value is used in a cast expression if the type of the expression doesn't resolve to that of the enum. Additionally, we only track dependencies at a type descriptor level -- not an enum label level. This means when we drop an enum value, we can't validate if the enum label being dropped is being used in a cast expression of the form above or the default value of a table column. This may lead to the corruption of view/default/computed expressions after an enum drop. Ideally, we should be tracking these dependencies and disallowing the enum value drop. 

It is worth noting that if a default expr is corrupted, inserts that override the default value continue to work. 

**To Reproduce**

What did you do? Describe in your own words.
```
demo@127.0.0.1:26257/movr> CREATE TYPE abc AS ENUM ('a', 'b', 'c');
CREATE TYPE

Time: 4ms total (execution 4ms / network 0ms)

demo@127.0.0.1:26257/movr> CREATE TABLE t(k INT PRIMARY KEY, v abc DEFAULT 'a');
CREATE TABLE

Time: 23ms total (execution 9ms / network 13ms)

demo@127.0.0.1:26257/movr> ALTER TYPE abc DROP VALUE 'a';
ALTER TYPE

Time: 41ms total (execution 6ms / network 35ms)

demo@127.0.0.1:26257/movr> INSERT INTO t VALUES(1);
ERROR: could not find [64] in enum "public.abc" representation PhysicalReps: [[128] [192]]; LogicalReps: [b c]
demo@127.0.0.1:26257/movr> INSERT INTO t VALUES(2, 'b');
INSERT 1

Time: 1ms total (execution 1ms / network 0ms)

```

**Expected behavior**
You shouldn't be allowed to drop an enum label used in a default/computed/view expression.

Related to: https://github.com/cockroachdb/cockroach/issues/59019

**Comment by solongordon** [comment]
@arulajmani What is the urgency here? Are we allowing dropping ENUM values (outside of multi-region) in 21.1?

**Comment by arulajmani** [comment]
> Are we allowing dropping ENUM values (outside of multi-region) in 21.1?

Yeah, we are exposing an `ALTER TYPE ... DROP VALUE` statement that works on general Enums. It's gated behind `sql_safe_updates`, with an error message explaining this specific limitation. 

As for the urgency, I don't think this will be fixed in this release. As per the original discussion on the [PR](https://github.com/cockroachdb/cockroach/pull/58688), we're okay living with this temporarily as long as the post-hoc errors are helpful and getting out of this situation is possible. There's testing in the original patch to this effect.

**Comment by solongordon** [comment]
Thanks for the details, will move to the backlog for now.

**Comment by the-ericwang35** [comment]
Fixed for default/computed columns, still need https://github.com/cockroachdb/cockroach/pull/62736 for views.

**Comment by vy-ton** [comment]
Will this be fully fixed for default/computed/view in 21.1? This known issue was why `ALTER TYPE...DROP VALUE` is currently marked as experimental for 21.1

**Comment by the-ericwang35** [comment]
> Will this be fully fixed for default/computed/view in 21.1? This known issue was why `ALTER TYPE...DROP VALUE` is currently marked as experimental for 21.1

This will be fixed for computed columns and default expressions but not for views. The PR for views (https://github.com/cockroachdb/cockroach/pull/62736) needs a version gate and is waiting for the latest version to be on master before being merged.

**Comment by vy-ton** [comment]
Does the version gate mean the fix for views will only be in 21.2?

**Comment by the-ericwang35** [comment]
Yes, that's correct.

**Comment by vy-ton** [comment]
@ajwerner I assume @ericharmeling fix for views will be unsafe to backport to 21.1? Looks like the default/computed column expression fix will be backported.

**Comment by jordanlewis** [comment]
@fqazi will look at rebasing Eric's almost-complete PR for this.

**Comment by fqazi** [comment]
Fixed via pull request https://github.com/cockroachdb/cockroach/pull/64882
