### ISSUE TITLE
sql, bulkio: importing tables into a multi-region database should get the default locality config

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#59803]
When you import a table into a multi-region enabled database, it should be a regional by table table homed in the primary region of the database. As such, the locality config on the table descriptor should reflect this.

**Comment by arulajmani** [comment]
Followup issue from the discussion with @dt @pbardea and @ajstorm yesterday.

**Comment by ajstorm** [comment]
This issue should also test exporting of REGIONAL BY ROW tables to see if the export includes the crdb_region column.
