### ISSUE TITLE
Support Apache Parquet format for cloud storage sinks

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#59819]
**Describe the solution you'd like**
We have a user request to support the [parquet output format](https://databricks.com/glossary/what-is-parquet) for changefeeds into S3 buckets

**Additional context**
Apache Parquet needs to wait for blocks to get finished, therefore we will need to micro-batch changes before sending through the changefeed. Ideally we would include an option to give control over the size/timing of microbatch transmissions.

Specifically we may want to limit this to initial_scan=only as we did with CSV

Jira issue: CRDB-3227

Epic CRDB-15071

**Comment by lancel66** [comment]
Re-upping this: 2 large customers have asked for this feature as they make heavy use of it within their organizations.
