### ISSUE TITLE
UPDATE privilege requires explicitly granting SELECT privilege

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#5982]
Currently, you must grant a user both `UPDATE` and `SELECT` privileges in order for the user to update a table. If you don't explicitly grant `SELECT`, the user can't execute an update. 

Instead, would it be reasonable to implicitly grant `SELECT` when granting `UPDATE`?

**Steps to reproduce:**

1. As the `root` user, grant the `UPDATE` privilege to the user `updater`.
   ```
   JESSEs-MacBook-Pro:cockroach jesseseldess$ ./cockroach sql

   root@:26257> grant update on test1.table1 to updater;
   GRANT
   ```
2. As the user `updater`, try to update `table1`.
   ```
   JESSEs-MacBook-Pro:cockroach jesseseldess$ ./cockroach sql --user=updater

   updater@:26257> update test1.table1 set a = 2;
   pq: user updater does not have SELECT privilege on table table1
   ```

**Comment by mberhault** [comment]
I believe this is the same as https://github.com/cockroachdb/cockroach/issues/2004
`SELECT` should only be needed when reading a column in the `WHERE` clause.

We currently check for `UPDATE`, but I think we go into the scan code anyway which triggers a check for `SELECT`. This should not be needed when we don't actually need to read any values.

The same goes for `DELETE`. You don't need other permissions when doing something like `DELETE * FROM mytable`, but we should require `SELECT` when doing `DELETE * FROM mytable WHERE a=2`

**Comment by jseldess** [comment]
Got it. Yep, this is a duplicate, so I'll close.
