### ISSUE TITLE
Update doc links on DockerHub 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#59823]
The dock links on our dockerhub overview are broken. We have put in place redirects on our side (https://github.com/cockroachdb/docs/pull/9712), but we should also just fix the links themselves:

https://hub.docker.com/r/cockroachdb/cockroach

Correct links to use:
- Install CockroachDB: https://www.cockroachlabs.com/docs/stable/install-cockroachdb.html
- Start a Cluster: https://www.cockroachlabs.com/docs/v20.2/start-a-local-cluster-in-docker-linux.html
- Kubernetes: https://www.cockroachlabs.com/docs/stable/orchestrate-cockroachdb-with-kubernetes.html
- Docker Swarm: https://www.cockroachlabs.com/docs/stable/orchestrate-cockroachdb-with-docker-swarm.html

**Comment by kenliu** [comment]
@jseldess I fixed these on DockerHub, please confirm these are okay. BTW for "start a cluster" I used `/stable`, if you really want it to be `/v20.2` I can change.

**Comment by jseldess** [comment]
Thanks, @kenliu! You're right, `/stable` is better. But for start a local cluster, can you make that `https://www.cockroachlabs.com/docs/stable/start-a-local-cluster-in-docker-linux.html`? Note the `-linux.html` at the end.

**Comment by kenliu** [comment]
good catch, fixed

**Comment by jseldess** [comment]
Thanks!
