### ISSUE TITLE
sql: only connect privilege should be checked to see if a user can see a descriptor (for vtables)

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#59827]
CONNECT privilege is being added in this PR: https://github.com/cockroachdb/cockroach/pull/59676

However we still will check if the user has ANY privilege in `userCanSeeDescriptor` to determine if they can see the descriptor.

`canSeeDescriptor := p.CheckAnyPrivilege(ctx, desc) == nil`

We may want to deprecate this behaviour of allowing the object in vtables (pg_catalog/information_schema) to be seen if the user has any privilege on the descriptor and only allow users to see the object if they have connect privilege on the database.

Jira issue: CRDB-3226

**Comment by rafiss** [comment]
One corollary to this is that we would need to do a privilege migration so that existing users who have other privileges would inherit the CONNECT privilege.

We won't get to this as single item -- it would be part of a larger rethink of privilege refactor.
