### ISSUE TITLE
Allow CLI to accept query on standard input

### ISSUE THREAD

**Issue by archiecobbs** [cockroachdb/cockroach#5983]
stable 20160330, HEAD, Mac OS 10.10.5.

The `cockroach sql` CLI does not accept queries via standard input. This would be a nice alternative to the `-e` flag and is especially useful when writing shell scripts that want to execute prepared SQL scripts.

    $ echo "select COUNT(*) from MYTABLE" | cockroach sql -d mydatabase
    # Welcome to the cockroach SQL interface.
    # All statements must be terminated by a semicolon.
    # To exit: CTRL + D.
    $ 

Obviously this is low priority but it's here for the record (more generally, any generic feature supported by the `mysql` CLI utility is worth considering for eventual addition to `cockroach sql`).

**Comment by mberhault** [comment]
this should already work:
```
$ echo "show databases;" | ./cockroach sql
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
+----------+
| Database |
+----------+
| system   |
+----------+
```

it does need a terminating `;` though.

**Comment by tschottdorf** [comment]
Yeah, this works. See #5981, for example. Probably really only the terminating `;`, and ideally the sql client should complain if EOF is read when there's an open buffer.

**Comment by bdarnell** [comment]
We should also not print that welcome message when stdin is not a tty.

**Comment by archiecobbs** [comment]
D'oh! Sorry.

Yes I suppose if the syntax is invalid, then (a) there should have been an error reported and (b) an exit value other than zero should have been returned.

**Comment by mberhault** [comment]
thanks for pointing it out, there is indeed something to fix here.

I'll do the following:
* consider EOF as an end of statement
* detect input type and skip message
* make sure errors are properly returned on incomplete statements (will probably be taken care of by EOF handling)

**Comment by andreimatei** [comment]
We probably don't want to consider EOF as an end of statement when the
input is a tty? You want CTRL-D to quite without executing anything.

**Comment by mberhault** [comment]
indeed, the EOF goes hand-in-hand with non-interactive statements. Otherwise, it should still be an error.

**Comment by mberhault** [comment]
Merged https://github.com/cockroachdb/cockroach/pull/5988 which does the following:

when not in interactive mode (stdin or stdout are not TTYs):
* don't display intro text
* execute last built-up command on EOF
* don't load/save history

So your original example now outputs:
```
$ echo "select COUNT(*) from descriptor" | ./cockroach sql -d system
+----------+
| COUNT(*) |
+----------+
|        9 |
+----------+
```
