### ISSUE TITLE
sql: creating new system tables with `sqlmigrations` is not possible

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#59850]
**Describe the problem**

I think we may have very badly shot ourselves in the foot in a way I would not have anticipated. I'm feeling sad about it. We added validation all over the place in 20.2, as we well know. One of the key places where we added this validation was in virtual tables. One interesting thing that happens in validation is [here](https://github.com/cockroachdb/cockroach/blob/f6e1a343ef3c392749a2254497769c347cba7c4c/pkg/sql/catalog/descpb/privilege.go#L274-L278). We check that the system tables have some privileges in some map. Unfortunately, that means that when adding new system tables, in the mixed version state, they will fail validation. This is a tough nut to crack. It means that, at least for 21.1, we can't add new system tables during `sqlmigrations`. I can work around this for my current use case but this is really unfortunate in general. I'm not sure how best to test this sort of thing. 

**To Reproduce**

Attempt to add a new system table and then in the mixed version state, run `SHOW TABLES` or something like it.

**Expected behavior**

We can create new system tables and the mixed-version state will work.

**Additional Context**

Maybe this isn't actually too terrible. In 21.1 we have long-running migrations which only run after all nodes are on the new version. That means we can safely add tables there. The only really awkward part is the migration to bootstrap the infrastructure for long-running migrations.

**Comment by ajwerner** [comment]
I've reworked https://github.com/cockroachdb/cockroach/pull/59760 around this. You can create system tables inside of long-running migrations which we now have. I've gotten to the point that I think this should be the last release for the `sqlmigrations` package. I'm intending to delete it when 21.2 opens unless somebody can convince me of a reason for its continued existence.

**Comment by postamar** [comment]
It seems like this should be closed.
