### ISSUE TITLE
I am not able to compile Cockroachdb as shown in the docs

### ISSUE THREAD

**Issue by Amazeryogo** [cockroachdb/cockroach#59852]
**Describe the problem**
So I have been trying to compile cockroach DB for myself, I am trying to do for about a month now, but I neither found a proper doc/issue regarding this so I thought to raise an issue.

Now the problem is, whenever I `make clean`, I get this error:

make -C src/github.com/cockroachdb/cockroach clean
make[1]: Entering directory '/home/ubuntu/cockroach-v20.2.4/src/github.com/cockroachdb/cockroach'
Running make with -j4
GOPATH set to /home/ubuntu/cockroach-v20.2.4
fatal: not a git repository (or any of the parent directories): .git
rm -rf bin/.go_protobuf_sources bin/.gw_protobuf_sources
rm -rf /home/ubuntu/cockroach-v20.2.4/native/aarch64-linux-gnu/cryptopp
go clean  -tags 'gss make aarch64_linux_gnu' -ldflags '-X github.com/cockroachdb/cockroach/pkg/build.typ=development -extldflags ""' -i github.com/cockroachdb/cockroach...
rm -rf /home/ubuntu/cockroach-v20.2.4/native/aarch64-linux-gnu/jemalloc
rm -rf /home/ubuntu/cockroach-v20.2.4/native/aarch64-linux-gnu/protobuf
rm -rf /home/ubuntu/cockroach-v20.2.4/native/aarch64-linux-gnu/rocksdb
rm -rf /home/ubuntu/cockroach-v20.2.4/native/aarch64-linux-gnu/snappy
rm -rf /home/ubuntu/cockroach-v20.2.4/native/aarch64-linux-gnu/geos
rm -rf /home/ubuntu/cockroach-v20.2.4/native/aarch64-linux-gnu/proj
rm -rf /home/ubuntu/cockroach-v20.2.4/native/aarch64-linux-gnu/libroach
rm -rf /home/ubuntu/cockroach-v20.2.4/native/aarch64-linux-gnu/krb5
warning: ignoring symlink /home/ubuntu/cockroach-v20.2.4/src/github.com/cockroachdb/cockroach/c-deps/libedit/include/editline
warning: ignoring symlink /home/ubuntu/cockroach-v20.2.4/src/github.com/cockroachdb/cockroach/c-deps/libedit/include/editline
find ./pkg -name node_modules -prune -o -type f -name '*.test' -exec rm {} +
for f in cockroach*; do if [ -f "$f" ]; then rm "$f"; fi; done
rm -rf cockroach.src.tgz pkg/sql/parser/gen
rm -rf bin/.cpp_protobuf_sources build/defs.mk*
go clean  -mod=vendor -tags 'gss make aarch64_linux_gnu' -ldflags '-X github.com/cockroachdb/cockroach/pkg/build.typ=development -extldflags ""' -i -cache github.com/cockroachdb/cockroach...
go: inconsistent vendoring in /home/ubuntu/cockroach-v20.2.4/src/github.com/cockroachdb/cockroach:
        github.com/PuerkitoBio/goquery@v1.5.1: is explicitly required in go.mod, but vendor/modules.txt indicates github.com/PuerkitoBio/goquery@v1.5.0
run 'go mod vendor' to sync, or use -mod=mod or -mod=readonly to ignore the vendor directory
make[1]: [Makefile:1693: clean] Error 1 (ignored)
find ./pkg -name node_modules -prune -o -type f -name 'zcgo_flags*.go' -exec rm {} +
rm -rf artifacts bin
make[1]: Leaving directory '/home/ubuntu/cockroach-v20.2.4/src/github.com/cockroachdb/cockroach'

`run 'go mod vendor' to sync, or use -mod=mod or -mod=readonly to ignore the vendor directory`

Now what should I do with this error, I tried reinstalling Go, cockroach DB repo and even the OS itself but I couldn't get rid of this error

**To Reproduce**
source of instructions: [https://www.cockroachlabs.com/docs/v20.2/install-cockroachdb-linux](https://www.cockroachlabs.com/docs/v20.2/install-cockroachdb-linux)

If possible, provide steps to reproduce the behaviour:
`wget -qO- https://binaries.cockroachdb.com/cockroach-v20.2.4.src.tgz | tar xvz`
`make build`

**Expected behavior**
It should just be compiled (in about an hour)

**Environment:**
 - CockroachDB version v20.2.4
 - Server OS: Ubuntu Server 20.10
 - Client app: NONE

**Additional context**
THIS COMPILE WAS PERFORMED ON RASPBERRY PI 3B (1 GB RAM) and 4B (4GB RAM)

I just was flabbergasted that there were no discussions regarding the error.

(PS, if this issue is a duplicate, please let me know, I am really sorry but I couldn't find any issues regarding this).

Thanks in advance

**Comment by Amazeryogo** [comment]
one thing though, when I try to run `go mod vendor` it gives this output:

`go: cannot find main module; see 'go help modules'`

**Comment by stevendanna** [comment]
@Amazeryogo It looks to me like the `clean` make target is calling `go clean` which is mutating the go.mod file such that the incompatibility is created.

Starting from a freshly unpacked directory, I'm able to work around this with the `-mod=readonly` go flag. For instance, the following appears to work for me:

```
make build
make clean GOFLAGS=-mod=readonly
make build
```

We likely want to take a look at fixing the Makefile such that it works out of the box, but purpose the above workaround will allow you to make progress with the existing release tarball.

**Comment by Amazeryogo** [comment]
@stevendanna  I tried `make clean` with the Goflags and got no errors here are the logs:

make -C src/github.com/cockroachdb/cockroach clean
make[1]: Entering directory '/home/ubuntu/go/src/github.com/cockroachdb/cockroach/src/github.com/cockroachdb/cockroach'
GOPATH set to /home/ubuntu/go/src/github.com/cockroachdb/cockroach
fatal: not a git repository (or any of the parent directories): .git
Detected change in build system. Rebooting make.
Running make with -j4
GOPATH set to /home/ubuntu/go/src/github.com/cockroachdb/cockroach
fatal: not a git repository (or any of the parent directories): .git
rm -rf bin/.go_protobuf_sources bin/.gw_protobuf_sources
rm -rf /home/ubuntu/go/src/github.com/cockroachdb/cockroach/native/aarch64-linux-gnu/cryptopp
go clean -mod=readonly -tags 'gss make aarch64_linux_gnu' -ldflags '-X github.com/cockroachdb/cockroach/pkg/build.typ=development -extldflags ""' -i github.com/cockroachdb/cockroach...
rm -rf /home/ubuntu/go/src/github.com/cockroachdb/cockroach/native/aarch64-linux-gnu/jemalloc
rm -rf /home/ubuntu/go/src/github.com/cockroachdb/cockroach/native/aarch64-linux-gnu/protobuf
rm -rf /home/ubuntu/go/src/github.com/cockroachdb/cockroach/native/aarch64-linux-gnu/rocksdb
rm -rf /home/ubuntu/go/src/github.com/cockroachdb/cockroach/native/aarch64-linux-gnu/snappy
rm -rf /home/ubuntu/go/src/github.com/cockroachdb/cockroach/native/aarch64-linux-gnu/geos
rm -rf /home/ubuntu/go/src/github.com/cockroachdb/cockroach/native/aarch64-linux-gnu/proj
rm -rf /home/ubuntu/go/src/github.com/cockroachdb/cockroach/native/aarch64-linux-gnu/libroach
rm -rf /home/ubuntu/go/src/github.com/cockroachdb/cockroach/native/aarch64-linux-gnu/krb5
warning: ignoring symlink /home/ubuntu/go/src/github.com/cockroachdb/cockroach/src/github.com/cockroachdb/cockroach/c-deps/libedit/include/editline
warning: ignoring symlink /home/ubuntu/go/src/github.com/cockroachdb/cockroach/src/github.com/cockroachdb/cockroach/c-deps/libedit/include/editline
find ./pkg -name node_modules -prune -o -type f -name '*.test' -exec rm {} +
for f in cockroach*; do if [ -f "$f" ]; then rm "$f"; fi; done
rm -rf cockroach.src.tgz pkg/sql/parser/gen
rm -rf bin/.cpp_protobuf_sources build/defs.mk*
go clean -mod=readonly -mod=vendor -tags 'gss make aarch64_linux_gnu' -ldflags '-X github.com/cockroachdb/cockroach/pkg/build.typ=development -extldflags ""' -i -cache github.com/cockroachdb/cockroach...
warning: ignoring symlink /home/ubuntu/go/src/github.com/cockroachdb/cockroach/src/github.com/cockroachdb/cockroach/c-deps/libedit/include/editline
warning: ignoring symlink /home/ubuntu/go/src/github.com/cockroachdb/cockroach/src/github.com/cockroachdb/cockroach/c-deps/libedit/include/editline
find ./pkg -name node_modules -prune -o -type f -name 'zcgo_flags*.go' -exec rm {} +
rm -rf artifacts bin
make[1]: Leaving directory '/home/ubuntu/go/src/github.com/cockroachdb/cockroach/src/github.com/cockroachdb/cockroach'

But When I compile it I get  `make: *** [Makefile:6: build] Error 2`

I can give you the log, here is a part of the log attached:

[ 96%] Building CXX object CMakeFiles/rocksdb.dir/utilities/write_batch_with_index/write_batch_with_index_internal.cc.o
[ 96%] Building CXX object CMakeFiles/rocksdb.dir/util/crc32c_arm64.cc.o
[ 96%] Building CXX object CMakeFiles/rocksdb.dir/port/port_posix.cc.o
[100%] Building CXX object CMakeFiles/rocksdb.dir/env/env_posix.cc.o
[100%] Building CXX object CMakeFiles/rocksdb.dir/env/io_posix.cc.o
[100%] Linking CXX static library librocksdb.a
make[1]: Leaving directory '/home/ubuntu/go/src/github.com/cockroachdb/cockroach/src/github.com/cockroachdb/cockroach'
make: *** [Makefile:6: build] Error 2

**Comment by stevendanna** [comment]
Unfortunately, I don't think that the part of the build log your provided contains the error.

**Comment by Amazeryogo** [comment]
ok, I'll give you the full log

**Comment by mneverov** [comment]
@Amazeryogo , I [had the same problem ](https://cockroachdb.slack.com/archives/CPCR73YL9/p1602677867064200) and the reason was go version. What go version do you use?

**Comment by Amazeryogo** [comment]
I use go v1.15.7

**Comment by Amazeryogo** [comment]
hey @stevendanna  just found the source of error, here you go:

**Comment by Amazeryogo** [comment]
Hey @stevendanna  found the source of error:

**Comment by Amazeryogo** [comment]
../../util/ss/mk_cmds /home/suvid/cockroach-v20.2.4/src/github.com/cockroachdb/cockroach/c-deps/krb5/src/kadmin/cli/kadmin_ct.ct
gcc -DHAVE_CONFIG_H  -I../../include -I/home/suvid/cockroach-v20.2.4/src/github.com/cockroachdb/cockroach/c-deps/krb5/src/include -I/home/suvid/cockroach-v20.2.4/src/github.com/cockroachdb/cockroach/c-deps/krb5/src/kadmin/cli -DKRB5_DEPRECATED=1 -DKRB5_PRIVATE  -g -O2 -Wall -Wcast-align -Wshadow -Wmissing-prototypes -Wno-format-zero-length -Woverflow -Wstrict-overflow -Wmissing-format-attribute -Wmissing-prototypes -Wreturn-type -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wunused-label -Wunused-variable -Wunused-value -Wunknown-pragmas -Wsign-compare -Werror=uninitialized -Wno-maybe-uninitialized -Werror=pointer-arith -Werror=int-conversion -Werror=incompatible-pointer-types -Werror=discarded-qualifiers -Werror=implicit-int -Werror=declaration-after-statement -Werror-implicit-function-declaration -pthread  -c /home/suvid/cockroach-v20.2.4/src/github.com/cockroachdb/cockroach/c-deps/krb5/src/kadmin/cli/ss_wrapper.c
yacc  /home/suvid/cockroach-v20.2.4/src/github.com/cockroachdb/cockroach/c-deps/krb5/src/kadmin/cli/getdate.y 
make[4]: yacc: No such file or directory
make[4]: *** [<builtin>: getdate.c] Error 127
make[3]: *** [Makefile:853: all-recurse] Error 1
make[2]: *** [Makefile:1533: all-recurse] Error 1
make[1]: *** [Makefile:819: /home/suvid/cockroach-v20.2.4/native/aarch64-linux-gnu/krb5/lib/libgssapi_krb5.a] Error 2
make[1]: *** Deleting file '/home/suvid/cockroach-v20.2.4/native/aarch64-linux-gnu/krb5/lib/libgssapi_krb5.a'
make[1]: *** Waiting for unfinished jobs....

**Comment by Amazeryogo** [comment]
new update
I installed yacc and make build again and i got this error

gcc -L../../lib -Wl,--enable-new-dtags -Wl,-rpath -Wl,/usr/local/lib -g -O2   -o kdb5_util kdb5_util.o kdb5_create.o kadm5_create.o kdb5_destroy.o kdb5_stash.o import_err.o strtok.o dump.o ovload.o kdb5_mkey.o tabdump.o tdumputil.o ../cli/getdate.o -lkadm5srv_mit  -lkdb5 -lkrb5_db2 -lkadm5srv_mit -lgssrpc -lgssapi_krb5 -lgssrpc -lgssapi_krb5 -ldl -pthread  -lkrb5 -lk5crypto -lcom_err -lkrb5support  -lresolv  -ldl
/usr/bin/ld: ../../lib/libkadm5srv_mit.a(server_kdb.o):/home/ubuntu/cockroach-v20.2.4/src/github.com/cockroachdb/cockroach/c-deps/krb5/src/lib/kadm5/srv/server_kdb.c:18: multiple definition of `master_keyblock'; kdb5_util.o:/home/ubuntu/cockroach-v20.2.4/src/github.com/cockroachdb/cockroach/c-deps/krb5/src/kadmin/dbutil/kdb5_util.c:109: first defined here
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:663: kdb5_util] Error 1
make[3]: *** [Makefile:853: all-recurse] Error 1
make[2]: *** [Makefile:1533: all-recurse] Error 1
mkdir -p lib
make[1]: *** [Makefile:819: /home/ubuntu/cockroach-v20.2.4/native/aarch64-linux-gnu/krb5/lib/libgssapi_krb5.a] Error 2
make[1]: *** Deleting file '/home/ubuntu/cockroach-v20.2.4/native/aarch64-linux-gnu/krb5/lib/libgssapi_krb5.a'
make[1]: *** Waiting for unfinished jobs....
rm -f lib/lib{geos,geos_c}.so
cp -L /home/ubuntu/cockroach-v20.2.4/native/aarch64-linux-gnu/geos/lib/lib{geos,geos_c}.so lib
make[1]: Leaving directory '/home/ubuntu/cockroach-v20.2.4/src/github.com/cockroachdb/cockroach'
make: *** [Makefile:6: build] Error 2

**Comment by stevendanna** [comment]
@Amazeryogo It looks like you might be hitting https://github.com/cockroachdb/cockroach/issues/49734 which was fixed in https://github.com/cockroachdb/cockroach/pull/58895

The best way to proceed likely depends on what your goals/constraints are.  One option would be to use the docker builder image which would pin you to particular versions of the various toolchains needed to complete the build:

```
cd src/github.com/cockroachdb/cockroach/
build/builder.sh make build
```

Another option is to apply a similar change to the Makefile as was applied in #58895.

**Comment by Amazeryogo** [comment]
hey @stevendanna  I found out that tzdata was not installed properly in my distro, I reinstalled it and it has compiled successfully, thanks a lot @stevendanna  @gpaul  @alex  @mneverov !
