### ISSUE TITLE
opt: add node and region information to explain

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#59860]
Distributed SQL allows for queries to be distributed across multiple nodes, and, potentially multiple regions. Furthermore, as we enhance our support for multi-region, some data may not be located in every region. Developers will need to be able to write queries that go cross-node and even cross-region. We want to minimize cross-region queries wherever possible because of the expensive cross-region network hop that can dramatically increase latency. By adding regions involved in the query to EXPLAIN, developers can identify costly cross-region queries and take corrective action. 

Cross-node queries are somewhat more complex as it is not always advantageous for a query to use multiple nodes. Sometimes using multiple nodes enhances query performance by sharing resources, and sometimes it increases latency due to the distance between nodes.  

We need to include this information on a per-operator basis because otherwise developers would not be able to identify the problematic part of the query that travels cross-node or cross-region usage. 

New Field | Information Details | Example
-- | -- | --
Regions involved in query | List of all regions | us-east, us-west
Regions involved per operator | List of all regions | us-east, us-west
Nodes involved in query | List of all nodes | n1, n2, n3
Nodes involved per operator | List of all nodes | n1, n2, n3

Epic: CRDB-9025

Jira issue: CRDB-3220

**Comment by awoods187** [comment]
@RaduBerinde  could you update here why we only added this to explain analyze?

**Comment by RaduBerinde** [comment]
#60550 added per-operator node information for EXPLAIN ANALYZE. Adding this info to the regular EXPLAIN is currently difficult, because we don't generate the distsql plan directly. This will be easier once we do (with the distsql factory).

**Comment by jordanlewis** [comment]
The work that @RaduBerinde is mentioning is tracked here: #47473
