### ISSUE TITLE
tracing, sql: add more robust testing for inflight trace spans vtable

### ISSUE THREAD

**Issue by angelapwen** [cockroachdb/cockroach#59873]
The `crdb_internal.node_inflight_trace_spans` virtual table added in #59492 could use additional testing on whether the table populates correctly. At the moment its schema is tested in `crdb_internal` SQL logic tests and most of the information being accessed is unit tested in `util/tracing/tracer_test`, but there is no testing of the virtual table itself in action.

Simply writing a logic test for this vtable seems like it would result in brittle tests, because I am not certain that the result of querying the vtable is stable across runs. Perhaps looking at the way [`crdb_internal.session_trace` is tested in `sql/trace_test` ](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/trace_test.go#L76) would be a good starting point. 

cc @irfansharif who suggested this 🥇

**Comment by tbg** [comment]
Ideas:

- open txn, check that own trace id has at least one entry in vtable, copy those entries to tmp table
- commit txn, check that all the trace/span things are gone from tmp table
