### ISSUE TITLE
cli: running cockroach with libeatmydata immediately exits

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5992]
Installed libeatmydata as per [these instructions](https://stackoverflow.com/questions/8217621/eatmydata-on-os-x).
```
DYLD_INSERT_LIBRARIES=/Users/tschottdorf/libeatmydata/.libs/libeatmydata.dylib DYLD_FORCE_FLAT_NAMESPACE=1 ./cockroach start
✘-1
```

Same for even just `./cockroach help`.

This is obviously super low-priority, but I was curious how benchmarks/throughput would change and thought I would post it just in case anyone knows exactly what's going on there already.

**Comment by petermattis** [comment]
I would guess that libeatmydata doesn't work with go binaries. I think RocksDB has an option to disable fsync.
