### ISSUE TITLE
ui: add region and node information to the statement details page

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#59979]
Add region and node information to the statement details page
<img width="772" alt="Screen Shot 2021-02-07 at 10 33 44 PM" src="https://user-images.githubusercontent.com/22278911/107172913-8c02c480-6994-11eb-8592-24b65706432b.png">

Related to https://github.com/cockroachdb/cockroach/issues/59860

**Comment by maryliag** [comment]
@Annebirzin the nodes look like links. Are they suppose to be clickable? And if yes, where it's redirected to?

**Comment by Annebirzin** [comment]
@maryliag The node links would link to the node detail pages (same node pages that can be accessed from the node links on the db console overview page) 
<img width="1628" alt="Screen Shot 2021-03-15 at 9 02 07 PM" src="https://user-images.githubusercontent.com/51920721/115792378-32594600-a398-11eb-8974-d1aa64fa7ca3.png">
