### ISSUE TITLE
sql: updated workload (e.g., tpc-c, movr) to use new multi-region enhancements 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#59988]
Cockroach sample workloads like TPC-C and MovR, itself designed to showcase partitioning, do not use the new multi-region abstractions. This makes it difficult to demo the new functionality to customers and to help them prepare their own applications for multi-region. It also means that users have no method to introspect and observe the benefits of our multi-region application.

Jira issue: CRDB-3205

**Comment by ajstorm** [comment]
@awoods187 With the [work Oliver did on TPC-C](https://github.com/cockroachdb/cockroach/pull/65600), is this now complete?

**Comment by awoods187** [comment]
Did we update MovR in workload? I know we updated it in its own repo but we should make sure workload matches.

**Comment by ajstorm** [comment]
Good question.  Who did the "MovR in its own repo" work?  Was that you who
merged it?

**Comment by awoods187** [comment]
I started it but @ericharmeling finished it. Typically its eng that owns workload though
