### ISSUE TITLE
OOM caused by backup

### ISSUE THREAD

**Issue by nick-jones** [cockroachdb/cockroach#59999]
**Describe the problem**

We run a number of cockroachdb clusters in kubernetes, and on a not so infrequent basis see backups fail with the following error:

```
communication error: rpc error: code = Canceled desc = context canceled
```

This coincides with a particular cockroachdb node being OOM killed because it has tried to request more memory than it has available to it:

```
Reason:       OOMKilled
Exit Code:    137
```

We don't believe it to be a coincidence that this occurs just after the backup has started, and we've seen it occur numerous times now.

**To Reproduce**

Unfortunately the exact conditions for this happening are not clear.

Backups are run with the following schedule:

```
CREATE SCHEDULE cluster_backup
  FOR BACKUP INTO '$BACKUP_DESTINATION_URL'
  RECURRING '$BACKUP_SCHEDULE'
  FULL BACKUP ALWAYS
  WITH SCHEDULE OPTIONS ignore_existing_backups;
```

**Expected behavior**

Backup to succeed.

**Additional data / screenshots**

```
root@cockroachdb-proxy:26257/defaultdb> SHOW JOBS;
        job_id       | job_type |                                                                                     description                                                                                     | statement | user_name | status | running_status |             created              |             started              |             finished             |             modified             | fraction_completed |                                  error                                  | coordinator_id
---------------------+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+-----------+--------+----------------+----------------------------------+----------------------------------+----------------------------------+----------------------------------+--------------------+-------------------------------------------------------------------------+-----------------
  631489241270878211 | BACKUP   | BACKUP INTO '/2021/02/08-120000.00' IN 's3://*************************/********************/***********/?AUTH=implicit' AS OF SYSTEM TIME '2021-02-08 12:00:00+00:00' WITH detached |           | root      | failed | NULL           | 2021-02-08 12:00:21.824811+00:00 | 2021-02-08 12:00:30.848965+00:00 | 2021-02-08 12:00:44.068508+00:00 | 2021-02-08 12:00:31.925958+00:00 |             0.0625 | communication error: rpc error: code = Canceled desc = context canceled |              0
(1 row)
```

```
State:          Running
  Started:      Mon, 08 Feb 2021 12:00:36 +0000
Last State:     Terminated
  Reason:       OOMKilled
  Exit Code:    137
  Started:      Fri, 29 Jan 2021 22:45:39 +0000
  Finished:     Mon, 08 Feb 2021 12:00:36 +0000
Ready:          True
Restart Count:  1
```

**Environment:**
 - CockroachDB version: v20.2.4
 - Server OS: Linux

```
root@cockroachdb-proxy:26257/defaultdb> SELECT VERSION();
                                          version
--------------------------------------------------------------------------------------------
  CockroachDB CCL v20.2.4 (x86_64-unknown-linux-gnu, built 2021/01/21 00:08:24, go1.13.14)
(1 row)

Time: 1ms total (execution 0ms / network 1ms)
```

Jira issue: CRDB-3202

**Comment by dt** [comment]
Hi @nick-jones, thanks for reporting this!

Do you know how much memory the pods are being given and how much they're typically using before the BACKUP starts and then when it is running, prior to OOM'ing? 

BACKUP is expected to use somewhere around between 100-200mb of memory on each node that contains data that needs to be backed up, and maybe a little more on the node that is coordinating the backup job as well. 

If you have plenty of headroom though, it's possible there's something using more than expected. If you're able to observe the memory usage during a BACKUP and do indeed see a node showing elevated usage, it would be very helpful to collect a heap profile to show what is using the excess memory. The easiest way to do that is to enable the debugging endpoints with `SET CLUSTER SETTING server.remote_debugging.mode = 'any'` then open/login to the web console and navigate to `/debug/pprof/heap`. You can manually trigger a backup, instead of waiting for the schedule, by running `BACKUP INTO '$BACKUP_DESTINATION_URL'`.

**Comment by nick-jones** [comment]
> Hi @nick-jones, thanks for reporting this!
> 
> Do you know how much memory the pods are being given and how much they're typically using before the BACKUP starts and then when it is running, prior to OOM'ing?

I'll check closer to when the backup is taken, but at the moment the UI is reporting the cockroachdb nodes are at 71%, 42% and 67% memory usage. The memory limit we currently have set is 1GB.

> 
> BACKUP is expected to use somewhere around between 100-200mb of memory on each node that contains data that needs to be backed up, and maybe a little more on the node that is coordinating the backup job as well.
> 
> If you have plenty of headroom though, it's possible there's something using more than expected. If you're able to observe the memory usage during a BACKUP and do indeed see a node showing elevated usage, it would be very helpful to collect a heap profile to show what is using the excess memory. The easiest way to do that is to enable the debugging endpoints with `SET CLUSTER SETTING server.remote_debugging.mode = 'any'` then open/login to the web console and navigate to `/debug/pprof/heap`. You can manually trigger a backup, instead of waiting for the schedule, by running `BACKUP INTO '$BACKUP_DESTINATION_URL'`.
> 
> (depending on your network setup, you can also `server.remote_debugging.mode = 'local'` to only open access to requests from localhost and instead ssh in and use curl, in which case `cockroach auth-session login` can provide the required curl parameters for making authenticated requests if it is TLS-secured cluster).

To be honest I suspect we don't think we do have enough headroom. But shouldn't cockroachdb spill to disk if it doesn't have enough memory available to allocate? I understand that would come at a cost in terms of speed, but triggering an OOM killer hardly feels any better.

**Comment by dt** [comment]
> The memory limit we currently have set is 1GB.

Yeah, unfortunately I think BACKUP probably wants at least a quarter of that to itself, so if storage cache, other traffic, etc is using memory too, that is probably a little tight. 

> shouldn't cockroachdb spill to disk

Indeed it should. Many SQL operations that could use unbounded memory, like certain types of joins, sorts or aggregations already do in fact, but BACKUP sadly doesn't today. It asks each node to export 64-128mb of data at a time into memory, compresses it and then uploads it to the destination URI. In our next development cycle we're planning on making it do a more stream-based export/compress/upload vs the current 64-128mb batches which should allow reducing the memory requirements to <16mb/node/backup running, but for now it just assumes it has the headroom to run.

You could try tuning the size of batch it exports, using  `SET CLUSTER SETTING  kv.bulk_sst.target_size = '16Mib'` or something to see if that helps, but may just need to run with a little more headroom if not.

**Comment by nick-jones** [comment]
We're no longer experiencing this issue, so I'm closing for the time being.
