### ISSUE TITLE
Improve buffering of resolved spans

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#60006]
From the discussion on: https://github.com/cockroachdb/cockroach/pull/59770

@ajwerner  indicated that 
```
This is pretty horrible that we hold onto all of these intermediate resolved spans. It feels like we should add a TODO to 
compress this. Alternatively, we could just emit the current frontier timestamp for just the set of spans that this change 
aggregator is tracking. We don't do checkpointing of anything less than the entire changefeed currently so doing that
 wouldn't break anything. I have a feeling that this would greatly aid in overall scalability of the changefeed when there are a
 large number of ranges. Imagine we have a rate of resolved checkpoints of ranges * 600ms but then we have a resolved 
timestamp of 5s. If we have 10k ranges underneath this aggreagtor, we're going to buffer 83k resolved timestamps :/
```

Basically, changefeed_processor buffers resolved spans until it is time to flush.  That means, as indicated above, that we might be buffering 10s of thousands of those spans -- for no reason.

**Comment by ajwerner** [comment]
Likely relates pretty closely to https://github.com/cockroachdb/cockroach/issues/49720. If we did a better job not forwarding checkpoints up to the ChangeFrontier, vast quantities of them would probably matter a good bit less.

**Comment by miretskiy** [comment]
This has been fixed.  We now use span frontier to coalesce updated spans together.
