### ISSUE TITLE
sql/ui: update latency to statement and transaction time; remove txn type

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#60001]
After reviewing the updates in 21.1, we found a few small additional changes to be made. We discussed in our prototypes changing latency to statement/transaction time as well as removing the txn column from the statements page to conserve space (we will add it to statement details page).

- [x] update `latency` to `statement` and `transaction time.`
- [x] remove `txn type` 
- [x] No mean and standard deviation bars (mentioned in tooltips) on transactions page
- [x] Default sort on transaction page should be execution count (not bytes)
- [x] Different units on planning time and execution time
- [x] Statement and transaction detail pages - resource panel needs same units

cc @Annebirzin and @asubiotto

**Comment by asubiotto** [comment]
Re mean and standard deviation, I tried to repro by deleting all rows in `vehicle_location_histories` in `movr` and it looks fine:
![image](https://user-images.githubusercontent.com/10560359/108905531-ceabda00-75ed-11eb-8628-ed655146415f.png)

**Comment by asubiotto** [comment]
> Different units on planning time and execution time

Isn't that expected?
![image](https://user-images.githubusercontent.com/10560359/108914868-0587ed00-75fa-11eb-996d-587db340b323.png)

We currently show different units in `Execution Stats` too:
![image](https://user-images.githubusercontent.com/10560359/108914928-1a648080-75fa-11eb-9b21-a6b9b44d791f.png)

**Comment by asubiotto** [comment]
> Statement and transaction detail pages - resource panel needs same units

I disagree. If we put everything in `KiB` for example you'll have very large numbers that are hard to understand. The opposite is true if we put everything in `GiB`. Happy to talk more about this, but I think it's a lot more readable this way.

**Comment by asubiotto** [comment]
Heads up that a lot of these style changes I will not have the expertise for. I'll work on what I can and see if I can get help from cc-observability on the rest.

**Comment by asubiotto** [comment]
@awoods187 going to close this as the functional changes are done and opened https://github.com/cockroachdb/cockroach/issues/61343 to track UI fixes.
