### ISSUE TITLE
uuid: Parsing behaves differently than Postgres

### ISSUE THREAD

**Issue by keithdoggett** [cockroachdb/cockroach#60011]
**Describe the problem**

UUID validation is different in CockroachDB than in Postgres.

**To Reproduce**

The problematic UUID `abcd-0123-4567-89ef-dead-beef-0101-1010` appears in the ActiveRecord test suite:

https://github.com/rails/rails/blob/eeb5baa86f672021f18b59903a2090df407ab065/activerecord/test/cases/adapters/postgresql/uuid_test.rb#L123-L127

It is successfully parsed in Postgres
```
keith=# SELECT 'abcd-0123-4567-89ef-dead-beef-0101-1010'::UUID;
                 uuid                 
--------------------------------------
 abcd0123-4567-89ef-dead-beef01011010
(1 row)
```

But not CockroachDB
```
root@:26257/defaultdb> SELECT 'abcd-0123-4567-89ef-dead-beef-0101-1010'::UUID;
ERROR: could not parse "abcd-0123-4567-89ef-dead-beef-0101-1010" as type uuid: uuid: incorrect UUID length: abcd-0123-4567-89ef-dead-beef-0101-1010
SQLSTATE: 22P02
```

It looks like Postgres removes extra dashes if the UUID is too long.

**Environment:**
 - CockroachDB version 20.2

---

## Instructions to fix

* Update logic in https://github.com/cockroachdb/cockroach/blob/9e31dd824b18337a8a7658b0634280cdfd0d7f8a/pkg/util/uuid/codec.go#L101-L113
* Make sure the new parsing logic passes all existing cases.
* Additionally, it should allow any UUID where the hyphens are placed at multiples of 4 characters apart.
* For example: `'abcd-0123-4567-89ef-dead-beef0101-1010'`, `'abcd0123-4567-89efdead-beef0101-1010'`, `'abcd-01234567-89efdeadbeef01011010'`, `'abcd-01234567-89ef-deadbeef0101-1010'`
* Add test cases to `pkg/util/uuid/codec_test.go` `TestFromString`
* Run `BenchmarkFromString` in codec_test.go both before and after the changes, and use [benchstat](https://pkg.go.dev/golang.org/x/perf/cmd/benchstat) to verify that performance did not worsen.
* Submit a PR following [the guidelines](https://wiki.crdb.io/wiki/spaces/CRDB/pages/181633464/Your+first+CockroachDB+PR) and add @rafiss as a reviewer.

**Comment by rafiss** [comment]
thanks for filing this! the parsing logic currently is too specific about the length of the uuid string: https://github.com/cockroachdb/cockroach/blob/9e31dd824b18337a8a7658b0634280cdfd0d7f8a/pkg/util/uuid/codec.go#L101-L113

it's because we support different formarts like URNs and braced-uuids. we'd have to change this parsing function to not rely on string length to determine how to parse the string.

**Comment by neel229** [comment]
I think I may be able to work on this issue.

**Comment by techytoes** [comment]
Hey @neel229 , are you still working on this?

**Comment by neel229** [comment]
Yup, I'm still working on it but you may also give a try.
