### ISSUE TITLE
kv: investigate why "failed to invoke" warning is seen when TestRaceWithBackfill runs on CI

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#6005]
When running TestRaceWithBackfill on CI I see this warning always logged

https://github.com/cockroachdb/cockroach/blob/master/kv/dist_sender.go#L708

**Comment by tschottdorf** [comment]
This issue is 1000x more useful if you copy-paste the actual log line in the output.

**Comment by tamird** [comment]
Closing this as stale. The line in question is https://github.com/cockroachdb/cockroach/blob/42f2b91c975db2f57c8b0aace8f3c9135039051e/kv/dist_sender.go#L728, but without any specific log line its not possible determine which RPC is failing.
