### ISSUE TITLE
util/decimal: Investigate EricLagergren/decimal package

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#6009]
This [library](https://godoc.org/github.com/EricLagergren/decimal) looks really good, and could be a justifiable alternative to our current `inf/dec` library.

Specially, reasons to consider switching libraries are that this new package:
- stores small integers inside a compact `int64`, speeding up operations and potentially avoiding allocations
- includes support for a larger number of arithmetic methods (`Log`, `Exp`, etc.)
  so we could remove our custom implementations
- uses a `Context` to define how arithmetic operations react (common in a lot of other languages)
- even comes with a [`FizzBuz`](https://godoc.org/github.com/EricLagergren/decimal#FizzBuzz) function!

Either way, we should continue to monitor https://github.com/golang/go/issues/12127.

**Comment by EricLagergren** [comment]
Hey! Just noticed this. Feel free to ask about anything you want. :)

**Comment by tamird** [comment]
Also, our current decimal library appears not to handle scientific notation, while PG does. EricLagergren/decimal also handles scientific notation, which is good.

**Comment by tamird** [comment]
@EricLagergren it seems that you don't have an equivalent of https://godoc.org/gopkg.in/inf.v0#Dec.UnscaledBig, which we need for our serialization of decimals.

**Comment by EricLagergren** [comment]
@tamird That could easily be added. Unless the decimal spec (http://speleotrove.com/decimal/decarith.html) has a name for the method, I'd probably lean towards a `Mantissa` method or something like that. But, yeah, could be easily added.

**Comment by tamird** [comment]
I haven't read the spec, but `Mantissa` SGTM.

**Comment by tamird** [comment]
Note: there are some optimizations in https://github.com/cockroachdb/cockroach/pull/8680/commits/72a5c197c66699edcbfbecc44a4308635bc57deb which are baked into github.com/EricLagergren/decimal and should be removed when this is implemented.

**Comment by nvanbenschoten** [comment]
[apd](https://github.com/cockroachdb/apd) is CockroachDB's new Arbitrary-precision decimal library. The library fully replaced `inf.Dec` in #13551, and will be the decimal package we use going forward.

**Comment by TamalSaha** [comment]
@nvanbenschoten, do you mind elaborating why write a new library? I am trying to find a big.Decimal lib for some financial calculation. So, I am curious.

**Comment by ericlagergren** [comment]
@TamalSaha from a reddit thread: https://www.reddit.com/r/golang/comments/5zkzrq/apd_an_arbitraryprecision_decimal_package/dezaw3v/

**Comment by nvanbenschoten** [comment]
@TamalSaha the reddit thread and blog post Eric linked to does a pretty good job explaining our rationale. The decision had less to do with specific shortcomings in other libraries and more to do with independent requirements for our use case, like panic-free operation and configurable precision.
