### ISSUE TITLE
Cannot create enum types with user root on database system

### ISSUE THREAD

**Issue by lukaseder** [cockroachdb/cockroach#60143]
**Describe the problem**

I can't create enum types on the system database with user root, only on other databases.

**To Reproduce**

I'm using CockroachDB version 20.2.4 to try out the `ENUM` type support. I created the docker container like this on Windows (see details below):

```
docker run -d --name=COCKROACHDB --hostname=localhost --net=roachnet -p 26257:26257 -p 8080:8080 -v "//c/data/cockroach" cockroachdb/cockroach start-single-node --insecure
```

Then with user `root`, I'm trying:

```sql
CREATE TYPE status AS ENUM ('open', 'closed', 'inactive');
```

Only to get:

```
SQL Error [42501]: ERROR: user root does not have CREATE privilege on database system
```

With user `root`, I cannot seem to give myself this grant:

```sql
grant create on database system to root;
```

**Expected behavior**

I don't see why this particular statement shouldn't work in the `system` database's `public` schema. Everything else works in this schema, and I can go and create a new database with an enum like this:

```sql
create database db;
use db;
create type status as enum ('open', 'closed', 'inactive');
```

**Environment:**
 - CockroachDB version: CockroachDB CCL v20.2.4 (x86_64-unknown-linux-gnu, built 2021/01/21 00:08:24, go1.13.14)
 - Server OS: Docker on Windows [Version 10.0.19042.746]
 - Client app: Dbeaver (JDBC)

**Comment by ajwerner** [comment]
Why are you trying to do anything to the `system` database? The problem here is that the `system` database is very special and users can't do anything to it. This is working as designed but I'll leave this open to understand what you're trying to do and why.

**Comment by ajwerner** [comment]
>Everything else works in this schema

What else works in `system.public` schema?

**Comment by lukaseder** [comment]
> > Everything else works in this schema
> 
> What else works in `system.public` schema?

Interesting. I must have been mistaken. I don't recall having set up any separate database in the past, and after some upgrade it seems my JDBC connection has automatically connected to the system database.

Feel free to close this on account of me not knowing what I was doing :)
