### ISSUE TITLE
stress: failed test in cockroach/cli/cli.test: TestQuit

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6023]
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/08d664015764b5b04fc09946d0588e16f8651cca

Stress build found a failed test:

```
=== RUN   TestQuit


ERROR: exit status 255
```

Run Details:

```
0 runs so far, 0 failures, over 5s
8 runs so far, 0 failures, over 10s
12 runs completed, 1 failures, over 11s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
Nondescript failure.
