### ISSUE TITLE
server: TestSecureHTTPRedirect: socket is not connected

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#6029]
Happened once on #5882:
`make stress PKG=./server TESTS=TestSecureHTTPRedirect`
```
--- FAIL: TestSecureHTTPRedirect (0.29s)
	server_test.go:151: Post http://127.0.0.1:51742: write tcp 127.0.0.1:51807->127.0.0.1:51742: write: socket is not connected
```

Tried to repro on master, no dice (5k iters), tried again on my WIP, no dice (5k iters).

Probably a rare breed.

**Comment by tamird** [comment]
Closing as inactionable.
