### ISSUE TITLE
gcs: add deprecation warning to the cluster setting used for `default` AUTH

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#60433]
We would like to deprecate, and eventually, remove the AUTH=default option for interaction with GCS ExternalStorage. Add a warning to the cluster setting description that is read from when using the AUTH=default option. This will be coupled with a docs callout to give users a cycle to change their usage patterns.

**Comment by adityamaru** [comment]
@lnhsingh @mwang1026 we had discussed accompanying this with a docs callout. Would you like me to create a separate docs issue?

**Comment by lnhsingh** [comment]
@adityamaru yes please!

**Comment by adityamaru** [comment]
https://github.com/cockroachdb/docs/issues/9822 docs issue.
