### ISSUE TITLE
sql: only allow updates to zone configurations of a multi-region database under sql_safe_updates 

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#60447]
Related to https://github.com/cockroachdb/cockroach/issues/57668

**Comment by arulajmani** [comment]
@aayushshah15 says:

We don't need to guard this behind sql_safe_updates necessarily, we could make the user add a keyword (such as `FORCE`) to their query itself. As an example, something like: `ALTER TABLE foo CONFIGURE ZONE USING num_replicas = 7 WITH (FORCE)`

FWIW I think this is a good idea, as `sql_safe_updates` can be quite deceptive. For one, it is off by default for non-interactive sessions. It's also not much of a lift compared to the `sql_safe_updates` solution, if we agree to go down this path. If we do this though, we should have a consistent solution for both tables and databases.

**Comment by aayushshah15** [comment]
> As an example, something like: ALTER TABLE foo CONFIGURE ZONE USING num_replicas = 7 WITH (FORCE)

This syntax borrows from Postgres, see: https://www.postgresql.org/docs/13/sql-dropdatabase.html
