### ISSUE TITLE
ui: statement details URL scheme should use an ID to identify the statement

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#60454]
The url in the statement details page corresponds directly to the SQL statement:
```SQL
ALTER TABLE rides SCATTER FROM (_, _) TO (_, _)
```
<img width="1116" alt="Screen Shot 2021-02-10 at 6 26 48 PM" src="https://user-images.githubusercontent.com/22278911/107586253-8ba13e00-6bcd-11eb-9652-7618f26142cb.png">
If you change the SQL URL, it changes the page:
<img width="1101" alt="Screen Shot 2021-02-10 at 6 27 31 PM" src="https://user-images.githubusercontent.com/22278911/107586304-a673b280-6bcd-11eb-827e-dc4dd2619d36.png">
This can give the appearance that the pages aren't static and can raise quality concerns. Raised by @timveil 

Jira issue: CRDB-3190

**Comment by dhartunian** [comment]
Instead of using the entire statement fingerprint as a path param, we should use its ID instead to make the URL easier to read and copy/paste and to prevent odd modifications like the one described above.
