### ISSUE TITLE
sql: add support for a JSON explain plan output

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#60464]
Some customers want to export explain plans and use JSON as a method to parse them (as opposed to today's human readable optimized format). 

Jira issue: CRDB-3188

**Comment by awoods187** [comment]
Postgres supports `EXPLAIN (FORMAT JSON) SELECT * FROM foo;` with FORMAT taking the values of TEXT, XML, JSON, or YAML and defaulting to TEXT.

**Comment by awoods187** [comment]
This is useful because they can then automate comparisons between query plans after they change.

**Comment by altanozlu** [comment]
Hello everyone we use sqlx heavily and sqlx's compile-time checked queries requires `EXPLAIN (VERBOSE, FORMAT JSON) ` so we can't use compile-time checked queries with cockroachdb
