### ISSUE TITLE
sql: provide a plan id as part of the key in statement_statistics

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#60462]
Many users want to be able to tell if an EXPLAIN plan changed recently and in particular, be able to correlate that with cluster or statement performance changes. I think we should an increment counter per statement fingerprint that records a timestamp every time the plan changes for that fingerprint. This way we could see when it last changed as well as correlate it to historical records. 

Storing plans would be an altogether bigger undertaking and something I think best tackled in a separate issue. 

Epic CRDB-6564

Jira issue: CRDB-3189

**Comment by maryliag** [comment]
This was solved with the usage of plan gists, and how we show historical plans per fingerprint on the statement fingerprint details page.
