### ISSUE TITLE
server: better logging of failed client connections

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#60478]
When there is an error connecting to the database, we should log the full details of the connection string and other info like the ip.

Here's a real case of a user using GSSAPI tried to connect with an invalid version.

This is the error message that showed up:
`E210112 05:02:43.419657 118035622 server/server.go:1863 [n1,client=IP:51898] unknown protocol version 80877104`

This isn't really helpful.  If the full connection string and the ip was also logged, it would be a meaningful and actionable error message.  The user has 100 odd microservices connecting and was unable to pinpoint which was the offending one.

This incident was specific to a user trying to connect via GSSAPI, but would be useful for all failed client connections.

**Comment by BramGruneir** [comment]
@knz just assigned this to you for a quick triage, I'm not sure exactly where it should fit

**Comment by BramGruneir** [comment]
Seems to me, we should be logging all of these details from both successful and failed connections

**Comment by knz** [comment]
@BramGruneir which version is this? We worked in that area for v21.1 and it's possible a fix was back-ported to 20.2 already?

**Comment by BramGruneir** [comment]
https://cockroachdb.zendesk.com/agent/tickets/7293
Looks like back in 19.2

**Comment by knz** [comment]
Can you check the behavior in v20.2 / v21.1 and report if there's an improvement?

**Comment by BramGruneir** [comment]
Will try.

**Comment by knz** [comment]
I checked this again and unfortunately even if we wanted to do something that's not allowed by the pgwire protocol: the error reported here occurs very early during the connection handshake and by that time nothing else is known about the client other than its IP address/port pair (which is logged already)

Closing this as unactionable.
