### ISSUE TITLE
IN and OR query on multi-region table hang during region failure

### ISSUE THREAD

**Issue by lin-crl** [cockroachdb/cockroach#60493]
**Describe the problem**
On geo-partition replica tables, when a region fails, a query using IN or OR operator on available regions hangs.

**To Reproduce**
1. create geo clusters
export CLUSTER="${USER:0:6}-test"
export NODES=9
export CNODES=$(($NODES-1))

### Create
roachprod create ${CLUSTER} -n ${NODES} -c gce --geo
roachprod stage ${CLUSTER} workload
roachprod stage ${CLUSTER} release v20.2.3
roachprod start ${CLUSTER}

2. create table and partitions
```
create table t (pk int, region string, primary key(region, pk));

alter table t partition by list (region)
(
partition useast values in ('useast'),
partition uswest values in ('uswest'),
partition europe values in ('europe')
);

alter partition useast of index t@* configure zone USING
num_replicas = 3,
constraints = '{+region=us-east1: 3}',
lease_preferences = '[[+region=us-east1]]';

alter partition uswest of index t@* configure zone USING
num_replicas = 3,
constraints = '{+region=us-west1: 3}',
lease_preferences = '[[+region=us-west1]]';

alter partition europe of index t@* configure zone USING
num_replicas = 3,
constraints = '{+region=europe-west2: 3}',
lease_preferences = '[[+region=europe-west2]]';


insert into t values (1,'useast');
insert into t values (2,'uswest');
insert into t values (3,'europe');


  root@localhost:26257/defaultdb> show ranges from table
  t;
         start_key      |       end_key       | range_id | range_size_mb | lease_holder |               lease_holder_locality               | replicas |                                                                      replica_localities
  ----------------------+---------------------+----------+---------------+--------------+---------------------------------------------------+----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------
    NULL                | /"europe"           |       36 |             0 |            5 | cloud=gce,region=us-west1,zone=us-west1-b         | {1,5,7}  | {"cloud=gce,region=us-east1,zone=us-east1-b","cloud=gce,region=us-west1,zone=us-west1-b","cloud=gce,region=europe-west2,zone=europe-west2-b"}
    /"europe"           | /"europe"/PrefixEnd |       41 |      0.000031 |            9 | cloud=gce,region=europe-west2,zone=europe-west2-b | {7,8,9}  | {"cloud=gce,region=europe-west2,zone=europe-west2-b","cloud=gce,region=europe-west2,zone=europe-west2-b","cloud=gce,region=europe-west2,zone=europe-west2-b"}
    /"europe"/PrefixEnd | /"useast"           |       42 |             0 |            3 | cloud=gce,region=us-east1,zone=us-east1-b         | {3,5,7}  | {"cloud=gce,region=us-east1,zone=us-east1-b","cloud=gce,region=us-west1,zone=us-west1-b","cloud=gce,region=europe-west2,zone=europe-west2-b"}
    /"useast"           | /"useast"/PrefixEnd |       37 |      0.000031 |            2 | cloud=gce,region=us-east1,zone=us-east1-b         | {1,2,3}  | {"cloud=gce,region=us-east1,zone=us-east1-b","cloud=gce,region=us-east1,zone=us-east1-b","cloud=gce,region=us-east1,zone=us-east1-b"}
    /"useast"/PrefixEnd | /"uswest"           |       38 |             0 |            2 | cloud=gce,region=us-east1,zone=us-east1-b         | {2,4,9}  | {"cloud=gce,region=us-east1,zone=us-east1-b","cloud=gce,region=us-west1,zone=us-west1-b","cloud=gce,region=europe-west2,zone=europe-west2-b"}
    /"uswest"           | /"uswest"/PrefixEnd |       39 |      0.000031 |            4 | cloud=gce,region=us-west1,zone=us-west1-b         | {4,5,6}  | {"cloud=gce,region=us-west1,zone=us-west1-b","cloud=gce,region=us-west1,zone=us-west1-b","cloud=gce,region=us-west1,zone=us-west1-b"}
    /"uswest"/PrefixEnd | NULL                |       40 |             0 |            7 | cloud=gce,region=europe-west2,zone=europe-west2-b | {1,4,7}  | {"cloud=gce,region=us-east1,zone=us-east1-b","cloud=gce,region=us-west1,zone=us-west1-b","cloud=gce,region=europe-west2,zone=europe-west2-b"}
  (7 rows)

  Time: 2.022s total (execution 2.022s / network 0.000s)

```

3. login in node 7,8,9 in europe region and kill the cockroach process
4. execute sql
--Following queries fail
SELECT * FROM t WHERE region in ('useast', 'uswest');
SELECT * FROM t WHERE region ='useast' or region= 'uswest';
--this query succeed
SELECT * FROM t WHERE region in ('useast')
union 
SELECT * FROM t WHERE region in ('uswest');

**Expected behavior**
Customer expects the IN and OR query succeeds. Using UNION is a work-around but not ideal for development productivity.

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version: v20.2.3
 - Server OS: Ubuntu
 - Client app: cockroach sql

**Additional context**
What was the impact?

gz#7549

**Comment by lin-crl** [comment]
explain SELECT * FROM t WHERE region
in ('useast')
union
SELECT * FROM t WHERE region in ('uswest')
limit 10;
       tree      |        field        |       description
-----------------+---------------------+--------------------------
                 | distribution        | local
                 | vectorized          | true
  limit          |                     |
   │             | count               | 10
   └── union     |                     |
        ├── scan |                     |
        │        | estimated row count | 1019401
        │        | table               | t@primary
        │        | spans               | [/'useast' - /'useast']
        └── scan |                     |
                 | estimated row count | 984301
                 | table               | t@primary
                 | spans               | [/'uswest' - /'uswest']
(13 rows)

Time: 1ms total (execution 1ms / network 0ms)

explain SELECT * FROM t WHERE region
in ('useast','uswest') limit 10;
  tree |        field        |                   description
-------+---------------------+--------------------------------------------------
       | distribution        | local
       | vectorized          | false
  scan |                     |
       | estimated row count | 10
       | table               | t@primary
       | spans               | [/'useast' - /'useast'] [/'uswest' - /'uswest']
       | limit               | 10
(7 rows)

Time: 1ms total (execution 1ms / network 0ms)

-- explain analyze (debug) doesn't work after regional failure because it tries to run the query.
--I'm attaching the results before failure
explain analyze (debug)  SELECT * FROM t WHERE region in ('useast', 'uswest');

[stmt-bundle-632404545759739905.zip](https://github.com/cockroachdb/cockroach/files/5967792/stmt-bundle-632404545759739905.zip)

**Comment by rytaft** [comment]
Hi @lin-crl thanks for providing these details. Since the plan shows that the optimizer has constrained the scan to two spans -- one for `'useast'` and one for `'uswest'` -- I don't think there's anything else we can do on the optimizer side to fix this. This seems like something that the SQL Execution team might have some insight into, but they'd probably need the `EXPLAIN (DISTSQL)` output. @lin-crl, could you please get that output from the customer for each of the plans you printed above?

cc @jordanlewis as the current SQL execution L2 on call

**Comment by lin-crl** [comment]
Thanks @rytaft 
Not sure if it's very helpful, but here's the results of `EXPLAIN (DISTSQL) SELECT * FROM t WHERE region in ('useast', 'uswest');` 
[https://cockroachdb.github.io/distsqlplan/decode.html#eJyMUE1L60AU3b9fcTmbvD7m0RZ3s1I0YqC2NSko2CzGzLUG0pk4d4KVkv8uTRbqQnA352POOdwj5LWBRvqwXlxkS_p7lRWb4m4xoSJdpJcb-kfX-eqWIt3fpHlKgXe1d3RyJp2wkZgoSjp5Y4nJBArOW16aPQv0I85QKrTBVyziw4k6DobMHqBnCrVru3iiS4XKB4Y-ItaxYWhszFPDORvLYTqDguVo6maIjedtqPcmvEOhaI0TTdMtxjlb_P_ynq4DP9eH1FkyztKcfHzhgLJX8F38LJdodgw979XvB-YsrXfC37b9lDzrSwW2Ox6PIL4LFa-Dr4aaEa6GfwNhWeKozkeQuVHqy_7PRwAAAP__176NWA==](url)

and `EXPLAIN (DISTSQL) SELECT * FROM t WHERE region ='useast' or region='uswest';`
[https://cockroachdb.github.io/distsqlplan/decode.html#eJyMkMFL-zAcxe-_v-LLu2z7EdmGt4CgaMXC3GY7UHA9xObrLHRJTVKcjP7v0uagOwje8j4vee-RI_x7DYnkab24Spc0vknzTf6wmFCeLJLrDf2n22x1T4Ee75IsobHjXWUNXdCo9ax8GE1olZ3iD-4xBIzVvFR79pDPOEch0DhbsvfW9eg4XEj1AXImUJmmDT0uBErrGPKIUIWaIbFRLzVnrDS76QwCmoOq6iE2XDau2iv3CYG8UcZLmm4Rt21x9uM8XTt-rQ6J0aSMpjnZ8MYORSdg2_Bd7oPaMeS8E38fmLFvrPF8su235FlXCLDecfwEb1tX8trZcqiJcjW8G4BmH6I7jyI10eqK7t9XAAAA___u-5Dl](url)

**Comment by rytaft** [comment]
This is odd -- it's showing that both spans are located on node 3. Did the node that was down recover? Or did they change the zone configs for some of the partitions? I would have expected to see at least 2 nodes in the DISTSQL plan.

**Comment by rytaft** [comment]
It would also be helpful to see the DISTSQL plan of the query that you said ran successfully (i.e., the UNION query)

**Comment by lin-crl** [comment]
Node 3 was the gateway node I connected to. So is the node 9 in the explain plan below.
Both are ran when all regions are up.

Here's the result for `EXPLAIN  (DISTSQL) SELECT * FROM t WHERE region in ('useast')
union
SELECT * FROM t WHERE region in ('uswest');`
[https://cockroachdb.github.io/distsqlplan/decode.html#eJykkc1O4zAQgO_7FNZcul15lZ-eNqeuaBCRSlqSIpBoDiYeKkupHWxHFFV5dxRHqC1qUYGb5-eb-TLZgnmuIIL4fj79n6Tk9yTJF_nNdEjyeBpfLMgfcpnNrokld1dxFhONK6Ek6ToHjUFm7IAOyW2azNKziBd0BFCQimPK1mggeoB_UFCotSrRGKW71NY1JHwDkU9ByLqxXbqgUCqNEG3BClshRLBgjxVmyDhqzwcKHC0TlRtrx7UWa6ZfgUJeM2ki4i2h917C3723N9f4JDax5FC0FFRjdwuNZSuEKGjp96SC86S607xL9e8zpMKTUjuXRirNUSM_8CjaI9oTYayQpfXCQ-dxQMfhSYnRVy6ToamVNPhB5vhkv5NEvsL-i4xqdIlzrUq3pg9njnMJjsb21bAPEulK7tftw8FP4PBTeHQA-23R_noLAAD__-lXGwo=](url)

**Comment by jordanlewis** [comment]
This is a very strange one - there should be no difference here.

The actual difference is that the UNION plan has two scans, each with no limit, on the individual span. They are connected by a union node.

The failing plans both have a single scan, with a limit of 10, on both spans at once.

@lin-crl would you be able to get a [trace](https://www.cockroachlabs.com/docs/stable/show-trace.html) of the failing query? Using session tracing should produce information even if the query doesn't complete by the time that you cancel it.

**Comment by lin-crl** [comment]
@jordanlewis  please see trace attached for both successful and failed query.
I didn't get all on failed query but hopefully it's enough of it

[trace_successfulquery.txt](https://github.com/cockroachdb/cockroach/files/5993221/trace_successfulquery.txt) 
[trace_failedquery.txt](https://github.com/cockroachdb/cockroach/files/5993220/trace_failedquery.txt)

**Comment by jordanlewis** [comment]
It's interesting, the trace has a lot of failed to connect errors - it seems like there is some kind of retry loop that's evicting range descriptors and refetching them, that ultimately concludes in failure. I think this is probably something going wrong in the dist_sender.

**Comment by jordanlewis** [comment]
I've been working with @lin-crl to try to reproduce this. We're having an issue finding a tight-span plan for the in tuple case. I think given the full table scan plan, it makes sense that we'd see a hang, because the europe data will be completely inaccessible.

```

root@35.196.10.222:26257/defaultdb> explain SELECT * FROM t WHERE region in ('useast') ;
  tree |        field        |       description
-------+---------------------+--------------------------
       | distribution        | local
       | vectorized          | false
  scan |                     |
       | estimated row count | 1
       | table               | t@primary
       | spans               | [/'useast' - /'useast']
(6 rows)

Time: 30ms total (execution 0ms / network 30ms)

root@35.196.10.222:26257/defaultdb> explain SELECT * FROM t WHERE region in ('useast', 'uswest') ;
    tree    |        field        |          description
------------+---------------------+---------------------------------
            | distribution        | full
            | vectorized          | false
  filter    |                     |
   │        | filter              | region IN ('useast', 'uswest')
   └── scan |                     |
            | estimated row count | 3
            | table               | t@primary
            | spans               | FULL SCAN
(8 rows)

```

@rytaft any ideas why the 1-filter case would produce an index span but the 2-filter case would produce a scan with filter? Do we need to add more data to the test table?

I believe that things *should* work as expected if the optimizer is producing the good, two-span plan that was included up-thread. I would like to be able to reproduce this issue - if there is actually a bug here it is probably somewhere fairly deep in the distsender/dialer/network land.

**Comment by rytaft** [comment]
> Do we need to add more data to the test table?

Yea, I would try adding at least 10 rows, then run `ANALYZE t`, so that the estimated cost of a constrained scan is less than the cost of a full scan.

If that doesn't work, could you possibly get a bundle (`explain analyze (debug)`) for that query? It's difficult to speculate about what's going on without seeing the stats.

**Comment by lin-crl** [comment]
Let me do a larger batch insert and get back to you two

**Comment by lin-crl** [comment]
@rytaft you're right now the plan is updated @jordanlewis 
I extended the cluster for another 24 hrs if you plan to work on it tomorrow 

`root@localhost:26257/defaultdb> insert into t select generate_series(2,1000000), 'useast';
insert into t select generate_series(1000000,2000000), 'uswest';
insert into t select generate_series(2000000,3000000), 'europe';


INSERT 999999

Time: 9.730s total (execution 9.730s / network 0.000s)

INSERT 1000001

Time: 19.369s total (execution 19.369s / network 0.000s)

INSERT 1000001

Time: 22.030s total (execution 22.030s / network 0.000s)

root@localhost:26257/defaultdb> 
root@localhost:26257/defaultdb> analyze t;
ANALYZE

Time: 21.946s total (execution 21.946s / network 0.000s)

root@localhost:26257/defaultdb> EXPLAIN SELECT * FROM t WHERE region in ('useast', 'uswest');

  tree |        field        |                   description
-------+---------------------+--------------------------------------------------
       | distribution        | local
       | vectorized          | true
  scan |                     |
       | estimated row count | 1992903
       | table               | t@primary
       | spans               | [/'useast' - /'useast'] [/'uswest' - /'uswest']
(6 rows)

Time: 1ms total (execution 1ms / network 0ms)`

**Comment by jordanlewis** [comment]
Worked with @lin-crl on reproing this again today and can't - when the plans are correct, queries return as expected.

**Comment by jordanlewis** [comment]
Though, there is definitely an interesting hazard here. If the optimizer sees that the number of rows in the table is small, it will generate the full table scan plan. This is highly unoptimal in this case, where the index is partitioned and pinned to regions, since a single region failing will render the full table scan plan useless under region failure.

@rytaft do we have any way to do better here? Could/should the optimizer increase the cost of full table scans when the table is geopartitioned? I'm not sure what the exact heuristic would be.

**Comment by rytaft** [comment]
Ideally we would always constrain the scan in this case (but especially due to the geodistributed nature). Could you possibly get a bundle from the case where the optimizer is not constraining the scan? It will help me to investigate where we're going wrong in the stats and/or cost model.

**Comment by lin-crl** [comment]
Please see the bundle attached @rytaft  Thanks for looking into it
[stmt-bundle-635644682133209089.zip](https://github.com/cockroachdb/cockroach/files/6026785/stmt-bundle-635644682133209089.zip)

**Comment by rytaft** [comment]
Hi @lin-crl, just an update here:

I've opened #61063 to fix this issue on master and #61069 to backport the fix to the 20.2 branch. The fix improves the optimizer's cost estimation of index scans that must visit multiple partitions. 

It should be included in the next 20.2.x release, which is scheduled for release on March 8th.

**Comment by rytaft** [comment]
Both of the PRs mentioned above have merged now. Can I go ahead and close this issue?

**Comment by lin-crl** [comment]
Thank you @rytaft  Look forward to the new release.
