### ISSUE TITLE
sql: block_writer tries to violate uniqueness constraint when its gateway is killed and a load balancer is used

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#6053]
Please answer these questions **for each node in your cluster**:

1. What version of CockroachDB are you using (`cockroach version`)?

 ```
$ cockroach version
Build Tag:   beta-20160407-175-g3710172
Build Time:  2016/04/13 22:38:31
Platform:    darwin amd64
Go Version:  go1.6
C Compiler:  4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.29)
```
2. What operating system and processor architecture are you using?

 ```
$ uname -a
Darwin Tamirs-MacBook-Pro.local 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64
```
3. What flags/environment variables did you pass to `cockroach start`?

 ```
$ roachdemo
2016/04/13 18:30:30 process 47868 started: ./cockroach start --insecure --port=26257 --http-port=26258 --store=cockroach-data/1
2016/04/13 18:30:30 process 47869 started: ./cockroach start --insecure --port=26259 --http-port=26260 --store=cockroach-data/2 --join=localhost:26257
2016/04/13 18:30:30 process 47870 started: ./cockroach start --insecure --port=26261 --http-port=26262 --store=cockroach-data/3 --join=localhost:26257
```

Please describe the issue you observed:

1. What did you do?
I was running nginx with the following config:
 ```
stream {
  upstream cockroachRPC {
    server localhost:26257;
    server localhost:26259;
    server localhost:26261;
  }
  upstream cockroachHTTP {
    server localhost:26258;
    server localhost:26260;
    server localhost:26262;
  }

  server {
    listen 4040;
    proxy_pass cockroachRPC;
  }
  server {
    listen 8080;
    proxy_pass cockroachHTTP;
  }
}
```
Then I ran block_writer via nginx, and then I killed node 1 via roachdemo's UI:
 ```
$ block_writer postgresql://root@localhost:4040?sslmode=disable
    1s:  869.2/sec
    2s:  602.0/sec
    3s:  551.0/sec
    4s:  482.2/sec
    5s:  279.1/sec
    6s:  379.3/sec
    7s:  308.0/sec
    8s:  448.3/sec
    9s:  414.3/sec
   10s:  327.9/sec
   11s:  363.3/sec
2016/04/13 18:32:36 error running blockwriter 7da09e4e-d4b9-470c-9452-cf0c0bc41c63: pq: duplicate key value (block_id,writer_id,block_num)=(2014691597753416701,'7da09e4e-d4b9-470c-9452-cf0c0bc41c63',1658) violates unique constraint "primary"
```
2. What did you expect to see?
block_writer continues to run normally.

3. What did you see instead?
block_writer fails with a uniqueness constraint violation, suggesting that an insert was retried when it shouldn't have been. This is bad!

**Comment by tschottdorf** [comment]
Isn't this unavoidable? In a normal shutdown scenario, you'd drain the node first (we should probably work on doing that as opposed to the "ok let's just drop everything and die" we do now).

**Comment by bdarnell** [comment]
In the pgwire protocol, it is unavoidable that some transactions will complete with an ambiguous status (cleanly draining the node will reduce the frequency but not eliminate this case). But it's still up to the application whether the transaction is retried in this case; there shouldn't be anything that retries automatically. 

It sounds like in this case the gateway survived while the leader of this table's range restarted, and it retried its (1PC) transaction on the new leader. Our current replay protection ensures that such a transaction cannot succeed, but it looks like the replay is getting further than it's supposed to. In this case it happens to generate an error but in a table without a primary key the same scenario would result in duplicate rows getting inserted.

**Comment by tschottdorf** [comment]
I don't think that's true. The replay catches a `WriteTooOldError`, but that is deferred until commit time (it sets `txn.WriteTooOld=true`), and intents are laid down (based on an increased timestamp). That means that any other error that happens before (attempted) commit takes precedence, such as the `ConditionFailedError` which we're seeing here.

On a higher level, as you point out a client transaction receiving an error on `COMMIT` can't really be sure what has happened. In this case, I think you're right that the kv gateway retried the 1PC txn. But even if we somehow caught this (maybe we'd bubble up a retry to the client in the event of certain errors) most likely the client would (or at least should) retry it (maybe in a new txn, but usually with the same data, though the block writer wouldn't), and get the same error again. If there's a SQL error code for "maybe this committed but it's hard to say" we could leverage that, but I doubt it, and even if so, the client logic to handle them would be nontrivial.

This ambiguity is the price we pay for our (extremely cheap) replay protection. I'm not surewe can improve here by much.

**Comment by bdarnell** [comment]
> most likely the client would (or at least should) retry it

Yes, the client will probably retry, and unless it's clever it will hit the same error. But at least the client will know it retried and can infer that the original attempt succeeded. The problem with retrying this transaction at the KV gateway level is that it hides the fact that the retry happened at all - it reports to the client as if it failed on the first attempt.

**Comment by aquarat** [comment]
What version of CockroachDB are you using (cockroach version)?

```
$ cockroach version
Build Tag:   beta-20160519
Build Time:  2016/05/19 21:52:10
Platform:    linux amd64
Go Version:  go1.6
C Compiler:  gcc 4.9.2
(both nodes - using the same executable)
```
What operating system and processor architecture are you using?

```
Both nodes : Ubuntu 15.10 "Wily"

Node 1 : (local) (received most if not all writes)
Linux sqlrat 3.19.0-43-generic #49-Ubuntu SMP Sun Dec 27 19:43:07 UTC 2015 x86_64 x86_64 
x86_64 GNU/Linux 

Node 2 : (remote) (saw few/no writes)
Linux parirat 4.2.0-25-generic #30-Ubuntu SMP Mon Jan 18 12:31:50 UTC 2016 x86_64 x86_64 
x86_64 GNU/Linux

```
What flags/environment variables did you pass to cockroach start?

```
Node 1
$ ./cockroach start --insecure --port=25267 --join=127.0.0.1:25268 --alsologtostderr
Node 2
$ ./cockroach start --join=127.0.0.1:25267 --port=25268 --insecure --alsologtostderr --http-port=65530

Nodes are linked via SSH tunnelling (they're on different machines; one in France, the other in South Africa). Both machines are NTP synchronised.

ssh -NCL 25268:127.0.0.1:25268 -R 25267:127.0.0.1:25267 user@host -p 60022 -i mykey
```

Please describe the issue you observed:
```
2016/05/23 19:57:57 pq: context deadline exceeded
2016/05/23 20:00:24 pq: duplicate key value (rowid)=(144035022173011969) violates unique constraint "primary"
2016/05/23 20:00:24 pq: duplicate key value (rowid)=(144035021942947841) violates unique constraint "primary"

Initially the message "context deadline exceeded" was repeated many hundreds of times, a failure rate 
of around 1% across ~ 1 million records, towards the end of the "copy" process the second type of 
message was repeated hundreds of times.
```
What did you do?

```
I created and ran a Go application with the intention of using it to duplicate a table from
a Postgres database to a local CockroachDB node by selecting from the Postgres instance 
and inserting received records into the CockroachDB node. Initially this application was 
single-threaded but CockroachDB responded slowly to inserts, so I modified the 
application to execute inserts concurrently using a set of goroutines. I increased the number
of goroutine workers until I started to see more than 20% CPU usage on the CockroachDB
instance. My code is linked below... it was a very quick and dirty creation, apologies in advance. 
CockroachDB indicated 107 connections during the "copy" process. During this time no
write transactions were executed on the second node, but the occasional 
SELECT was executed, usually SELECT COUNT and SELECT * ... LIMIT 1;

Application performing the copy : https://play.golang.org/p/hhGzhNtmHL

The table structure in CockroachDB :
CREATE TABLE log (id INT, data STRING, entered TIMESTAMP, channel STRING);
(implying the creation of the rowid column)

```
What did you expect to see?
```
Limited or no error messages; I was copying an existing table and the table structure
in CockroachDB I was inserting into had a managed primary key (hidden rowid), so I
wasn't expecting any key conflicts.
```
What did you see instead?
```
Initially the odd "context deadline exceeded" and then towards the end of the process
(after about 600k rows were inserted)  errors indicating a duplicate key violation on the
rowid column. Both messages were repeated many times (in excess of 1000).
```
