### ISSUE TITLE
sql: support json_extract_path_text and jsonb_extract_path_text

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#60569]
The Golang ORM GORM generates queries that use this function when dealing with a JSON column. We already have `json_extract_path` and the `#>>` operator, so we should be able to add this too. See https://www.postgresql.org/docs/current/functions-json.html

---

## Instructions

* Refer to the commit that added `json_extract_path`: https://github.com/cockroachdb/cockroach/pull/20520/commits/66ca0ae0185ec06e45e3bac98dd52c010d37787a. The change here will be fairly similar.
* Modify `pkg/sql/sem/builtins/builtins.go` and add `json_extract_path_text` and `jsonb_extract_path_text`. Reuse the existing code for `json_extract_path`. The only difference should be the return type.
* Add tests in `pkg/sql/logictest/testdata/logic_test/pg_catalog ` and `pkg/sql/logictest/testdata/logic_test/json_builtins`. The tests should be identical to all the `json_extract_path` tests.

**Comment by naivcit** [comment]
@rafiss I would like to work on this

**Comment by rafiss** [comment]
@naivcit glad you're interested! please go ahead and let me know if you need anything.

**Comment by parsaakbari1209** [comment]
Hey @naivcit are you already working on this? If not I can give it a try.

**Comment by naivcit** [comment]
Hey @parsaakbari1209 , yeah man sorry , have already started working on this one .

**Comment by kakshay21** [comment]
Hey @naivcit, are you still working on this?

**Comment by naivcit** [comment]
Hey @kakshay21 I had started working on it but got occupied elsewhere , I think I won't be able to resume work on this  soon , you can take it up if u want .
