### ISSUE TITLE
sql: statuspb.Session does not properly report memory usage across all nodes

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#60586]
The fields `alloc_bytes` and `max_alloc_bytes` in `statuspb.Session` (`status.proto`) are currently populated only from monitor data on the gateway node. When queries are distributed, they incorrectly miss out on memory usage incurred on other nodes.

Arguably the fields are not properly defined, instead of single fields we should have an array, one for every node, or some similar interface which enables the client to distinguish which nodes was incurred which memory usage.

cc @jordanlewis @asubiotto

**Comment by asubiotto** [comment]
This is a known issue #54339.
