### ISSUE TITLE
Queries with large WHERE clauses taking a long time

### ISSUE THREAD

**Issue by keithdoggett** [cockroachdb/cockroach#60602]
**Describe the problem**

While running the ActiveRecord test suite against CockroachDB, we noticed one query takes a very long time (>2 hours). The test is found here: https://github.com/rails/rails/blob/291a3d2ef29a3842d1156ada7526f4ee60dd2b59/activerecord/test/cases/relation/or_test.rb#L180-L190. It queries against the `citations` table with the following schema:

```
  column_name | data_type | is_nullable | column_default | generation_expression |  indices  | is_hidden
--------------+-----------+-------------+----------------+-----------------------+-----------+------------
  id          | INT8      |    false    | NULL           |                       | {primary} |   false
  book_id     | INT8      |    true     | NULL           |                       | {}        |   false
  book2_id    | INT8      |    true     | NULL           |                       | {}        |   false
  citation_id | INT8      |    true     | NULL           |                       | {}        |   false
```

In the test, the table is seeded with 65535 entries where `id` is `i` and `book2_id` is `i^2` with `i` as `0..65535`, `book_id` and `citation_id` are `NULL`.

The query run against the table has the following form:

```
SELECT \"citations\".* FROM \"citations\" WHERE (\"citations\".\"id\" = 0 AND \"citations\".\"book2_id\" = 0 OR \"citations\".\"id\" = 1 AND \"citations\".\"book2_id\" = 1 OR \"citations\".\"id\" = 2 AND \"citations\".\"book2_id\" = 4 OR \"citations\".\"id\" = 3 AND \"citations\".\"book2_id\" = 9 OR \"citations\".\"id\" = 4 AND \"citations\".\"book2_id\" = 16 OR \"citations\".\"id\" = 5 AND \"citations\".\"book2_id\" = 25 OR \"citations\".\"id\" = 6 AND \"citations\".\"book2_id\" = 36 OR \"citations\".\"id\" = 7 AND \"citations\".\"book2_id\" = 49 OR \"citations\".\"id\" = 8 AND \"citations\".\"book2_id\" = 64 OR \"citations\".\"id\" = 9 AND \"citations\".\"book2_id\" = 81)
```

except that it does this 6000 times, so in the last OR clause, `id` = 5999 and `book2_id` = 35988001.

**To Reproduce**

[too_many_ors_issue.zip](https://github.com/cockroachdb/cockroach/files/5985074/too_many_ors_issue.zip)
I've attached a zip archive containing two files: `seed_citations.sql` and `query.sql`. The first creates the table and seeds the 65535 entries and the second contains the full query from the example.

1. Unzip too_man_ors_issue.zip
2. Run `cockroach sql < seed_citations.sql`
3. Run `cockroach sql < query.sql`
4. Wait a long time

**Environment:**
 - Version 20.2.4

**Comment by otan** [comment]
i think this would be a sql queries issue, so putting exec/opt on it.

**Comment by rafiss** [comment]
EXPLAIN output from the smaller query. 

```
   info
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • filter
  │ filter: ((((((((((id = 0) AND (book2_id = 0)) OR ((id = 1) AND (book2_id = 1))) OR ((id = 2) AND (book2_id = 4))) OR ((id = 3) AND (book2_id = 9))) OR ((id = 4) AND (book2_id = 16))) OR ((id = 5) AND (book2_id = 25))) OR ((id = 6) AND (book2_id = 36))) OR ((id = 7) AND (book2_id = 49))) OR ((id = 8) AND (book2_id = 64))) OR ((id = 9) AND (book2_id = 81))
  │
  └── • scan
        estimated row count: 10
        table: citations@primary
        spans: [/0 - /9]
(10 rows)
```

cc @RaduBerinde @asubiotto for triage.

**Comment by RaduBerinde** [comment]
I can reproduce with `EXPLAIN (OPT)` in front, so it looks like an optimizer issue.

**Comment by RaduBerinde** [comment]
Put the query in an xform test: https://gist.github.com/RaduBerinde/31fa88c4b6f47bcf61c1e89a3625ff5d

From smaller versions in this query, it doesn't look like we are applying many exploration rules, only around 4. It looks like we spend a lot of the time in `GenerateConstrainedScans` (`makeSpansForExpr` takes most of the time).

**Comment by RaduBerinde** [comment]
Normalization of the query takes ~6 seconds, most of the time here is also spent on building constraints.
