### ISSUE TITLE
kvserver: reconsider reproposal strategies

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#60617]
**Describe the problem**

We currently repropose inflight entries if they haven't popped out of the raft log within a "reasonable amount of time" (X ticks).
Under overload conditions, this can lead to adding more work to an already overloaded system.

This came out of the same investigation as https://github.com/cockroachdb/cockroach/issues/60612.

**Comment by lunevalex** [comment]
@tbg do we actually need to do anything here if we implement #33007?

**Comment by tbg** [comment]
I suspect not. The base layer of protection here is https://github.com/cockroachdb/cockroach/blob/f8e1c90779792bd4de5c7ac17d0ca4ca9eaf0939/pkg/kv/kvserver/store.go#L239, which limits how much in uncommitted entries we allow in the raft log. However, this resets on term changes, so offers no protection across terms (which are likely happening at least at some rate in broken clusters). Assuming we add a reasonable circuit breaker at the replica level, and that circuit breaker clears out all inflight proposals (as it should), it would address the problem this issue is pointing out.
