### ISSUE TITLE
sql/ui: add a cpu used per statement/transaction/session 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#60628]
In 21.1, we’ve made some progress in allowing the transactions and statements page to be sorted by rows and bytes read, memory, and network resource usage but we also lack information on CPU.

Jira issue: CRDB-3168

**Comment by awoods187** [comment]
Related to https://github.com/cockroachdb/cockroach/pull/60508 https://github.com/cockroachdb/cockroach/pull/60588

**Comment by jordanlewis** [comment]
Closing this in favor of #87213
