### ISSUE TITLE
sql: bug in latency measurement for vectorized flow

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#60621]
https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/colflow/vectorized_flow.go#L813

>             latency, err := s.nodeDialer.Latency(inputStream.TargetNodeID)
Here `TargetNodeID` is this node, so this doesn't make sense. Simply replacing with `OriginNodeID` might work in most cases, but is problematic in that we may have not dialed that node recently.

**Comment by asubiotto** [comment]
Good catch. We look up the latency in the nodeDialer's `RemoteClocks` which measures clocks, so I believe it doesn't matter if we dialed the node or not in distsql flows (I'm assuming this is what you mean).
