### ISSUE TITLE
sql: pgx TestConnSendBatchMany is 1000x slower on CockroachDB compared to PostgreSQL

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#60651]
The pgx test [TestConnSendBatchMany](https://github.com/jackc/pgx/blob/927a15124e6a579327ea56b478e4ba7dac6e45a6/batch_test.go#L141) creates a table then inserts 1000 rows into it using one batch statement. 

In PostgreSQL 13, this takes 0.03 seconds, but in CockroachDB v20.2 this takes ~30 seconds. The code to reproduce is below.

For this ticket, we should determine if this amount of slowness is expected, and if not, identify why.

cc @jackc 

```
func mustConnectString(t testing.TB, connString string) *pgx.Conn {
	conn, err := pgx.Connect(context.Background(), connString)
	if err != nil {
		t.Fatalf("Unable to establish connection: %v", err)
	}
	return conn
}

func closeConn(t testing.TB, conn *pgx.Conn) {
	err := conn.Close(context.Background())
	if err != nil {
		t.Fatalf("conn.Close unexpectedly failed: %v", err)
	}
}

func mustExec(t testing.TB, conn *pgx.Conn, sql string, arguments ...interface{}) (commandTag pgconn.CommandTag) {
	var err error
	if commandTag, err = conn.Exec(context.Background(), sql, arguments...); err != nil {
		t.Fatalf("Exec unexpectedly failed with %v: %v", sql, err)
	}
	return
}

func TestConnSendBatchMany(t *testing.T) {
	conn := mustConnectString(t, "postgresql://root:@localhost:26257/defaultdb")
	defer closeConn(t, conn)

	sql := `create table ledger(
	  id serial primary key,
	  description varchar not null,
	  amount int not null
	);`
	mustExec(t, conn, sql)

	batch := &pgx.Batch{}

	numInserts := 1000

	for i := 0; i < numInserts; i++ {
		batch.Queue("insert into ledger(description, amount) values($1, $2)", "q1", 1)
	}
	batch.Queue("select count(*) from ledger")

	br := conn.SendBatch(context.Background(), batch)

	for i := 0; i < numInserts; i++ {
		ct, err := br.Exec()
		assert.NoError(t, err)
		assert.EqualValues(t, 1, ct.RowsAffected())
	}

	var actualInserts int
	err := br.QueryRow().Scan(&actualInserts)
	assert.NoError(t, err)
	assert.EqualValues(t, numInserts, actualInserts)

	err = br.Close()
	require.NoError(t, err)
}
```

Jira issue: CRDB-3165

**Comment by asubiotto** [comment]
@yuzefovich to try to repro and do some initial investigation

**Comment by rafiss** [comment]
I modified the test to do one big batch INSERT statement, and that is still slower than running the original test against PostgreSQL. 

```
        insertSql := `insert into ledger(description, amount) values('q1', 1)`
        for i := 0; i < numInserts-1; i++ {
            insertSql += `, ('q1', 1)`
        }
        mustExec(t, conn, insertSql)
```

CockroachDB, original test: ~30 seconds
CockroachDB, modified test: ~1.2 seconds
PostgreSQL, original test: ~0.03 seconds
PostgreSQL, modified test: ~0.06 seconds

**Comment by yuzefovich** [comment]
I looked into the original test, and I can easily see that it takes 30 seconds to run. I converted it to benchmark and run it with `TESTFLAGS='-test.cpuprofile=cpu.out'`, and interestingly the cpu profile only accounts for 50ms (the snippet below is the whole thing):
```
(pprof) top
Showing nodes accounting for 40ms, 100% of 40ms total
Showing top 10 nodes out of 13
      flat  flat%   sum%        cum   cum%
      30ms 75.00% 75.00%       30ms 75.00%  runtime.pthread_cond_wait
      10ms 25.00%   100%       10ms 25.00%  runtime.nanotime1
         0     0%   100%       30ms 75.00%  runtime.findrunnable
         0     0%   100%       30ms 75.00%  runtime.mcall
         0     0%   100%       10ms 25.00%  runtime.mstart
         0     0%   100%       10ms 25.00%  runtime.mstart1
         0     0%   100%       10ms 25.00%  runtime.nanotime (inline)
         0     0%   100%       30ms 75.00%  runtime.notesleep
         0     0%   100%       30ms 75.00%  runtime.park_m
         0     0%   100%       30ms 75.00%  runtime.schedule
```
I collected the profile from the running CockroachDB node, and it also only shows like 0.5s spent in the execution of a couple of statements, so I don't know where this time is going.

My best guess is that it has something to do with the internals of `pgx`, possibly something about establishing a connection to CRDB, how pgx executes its "batch" of statements, etc. I'll move it to SQL Experience for further investigation.

**Comment by rafiss** [comment]
I can take over more investigation, but I think it's unlikely that the time is spent within pgx, since it runs very quickly against PostgreSQL.

**Comment by rimadeodhar** [comment]
We should check if #52071 resolves this issue.

**Comment by rafiss** [comment]
I tested locally and it takes 2 seconds now.

In the [pgx CI environment](https://github.com/jackc/pgx/actions/runs/5606561065/job/15188983617?pr=1693), which tests against v23.1.3, it's fast too:
```
=== RUN   TestConnSendBatchMany/exec
=== RUN   TestConnSendBatchMany/simple_protocol
--- PASS: TestConnSendBatchMany (2.83s)
    --- PASS: TestConnSendBatchMany/cache_statement (0.67s)
    --- PASS: TestConnSendBatchMany/cache_describe (0.52s)
    --- PASS: TestConnSendBatchMany/describe_exec (0.78s)
    --- PASS: TestConnSendBatchMany/exec (0.48s)
    --- PASS: TestConnSendBatchMany/simple_protocol (0.37s)
```
