### ISSUE TITLE
Wrong defaults in log flag help

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#6066]
With [PR 5979](https://github.com/cockroachdb/cockroach/pull/5979), logs are no longer written to stderr by default. 

However, the default values for `--alsologtostderr` and `--logtostderr` in command `help` seem out of sync with this change:

```
Flags:
      --alsologtostderr value[=INFO]   logs at or above this threshold go to stderr
      --log-backtrace-at value         when logging hits line file:N, emit a stack trace (default :0)
      --log-dir value                  if non-empty, write log files in this directory
      --logtostderr value[=true]       log to standard error instead of files
      --no-color value                 disable standard error log colorization
      --verbosity value                log level for V logs
      --vmodule value                  comma-separated list of pattern=N settings for file-filtered logging
```

If logs are no longer written to stderr by default, I would expect `--alsologtostderr value[=NONE]` and `--logtostderr value[=false]`.

@petermattis, @tschottdorf

**Comment by petermattis** [comment]
The display is slightly confusing, but it is correct. The `[=NONE]` and `[=true]` indicate what value will be set if you specify `--alsologtostderr` or `--logtostderr` without a parameter. That is, `--alsologotstderr` by itself causes logging to stderr to be turned on for `INFO` and above.

**Comment by petermattis** [comment]
PS We can't easily change this display as it comes as part of the flag package we use.

**Comment by tschottdorf** [comment]
It might be correct, but it's unintuitive and should become more intuitive.

**Comment by petermattis** [comment]
@tschottdorf Do you have a suggestion how?

**Comment by bdarnell** [comment]
We should fix it upstream if we have to; this presentation is confusing and unconventional for CLI help.

**Comment by jseldess** [comment]
Thanks for the clarification, Peter. Makes sense now, but I agree with Toby that it's hard to intuit this from the help. 

Would it be better to list defaults like we do for other flags? For example:

```
--alsologtosdtder value
  Logs at or above this threshold go to stderr.
  (default "NONE")
--logtostderr value
  Log to standard error instead of files.
  (default "false")
```

**Comment by bdarnell** [comment]
Why does `--logstderr` have `[=true]` when the other boolean flags don't? We should be able to fix that one without patching upstream.

For `--alsologtostderr`, maybe we should just remove the weird pseudo-boolean behavior completely and require the level to be given if the flag is used. Or we split `--alsologtostderr` back into a boolean flag and a `--stderrthreshold` as in glog.

**Comment by petermattis** [comment]
Seems like there is some issue with the `atomicBool` struct we use for `--logtostderr`.
