### ISSUE TITLE
sql,tracing: harmonize span/traceID representation

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#60668]
**Describe the problem**

In SQL, traceIDs/spanIDs are currently represented using DInt, which is an int64-backed type. The tracing package uses uint64s. While this isn't a technical issue, it might be confusing to see `int64(x)` via SQL and `uint64(x)` in logs.

**Expected behavior**
SQL and tracing should agree. Either we use BIGINT in SQL or uint64 in tracing. If we do the latter, we have to be a little careful about the migration (we have to stick to uint64 on the wire, in `(*Tracer).InjectX/ExtractX`).

**Additional data / screenshots**
Discussed on https://reviewable.io/reviews/cockroachdb/cockroach/59992

Jira issue: CRDB-3163

**Comment by knz** [comment]
> we use BIGINT in SQL 

That is not a thing. SQL BIGINT = signed int64

You may mean DECIMAL or BIT, but these come with obnoxious heap allocation overheads.
