### ISSUE TITLE
sql: the JSON strings used to access fields are not properly anonymized under FmtAnonymize

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#60673]
Found while investigating #60676

This statement:

```
SELECT (a->'x')->>'y'
```

should become

```
SELECT (_->'_')->>'_'
```

under the FmtAnonymize flag, because 'x' and 'y' are sensitive data.

Currently because of this bug, the column/field names inside the JSON queries are not deanonymized when reported in crash reports and telemetry.

**Comment by knz** [comment]
cc @vy-ton @rafiss for triage. NB: this is somewhat high priority because it constitutes a confidentiality breach.

**Comment by rafiss** [comment]
I wonder if it would be possible to fix this in the `BinaryExpr` Format function?

Also a question: what about functions like `json_extract_path`, where one of the arguments is a JSON key/path? From what I saw in the initial PR, string function arguments are not redacted as identifiers.

**Comment by knz** [comment]
I don't know 100% how to think about this. Truth be told I am a bit too removed from SQL now and I also never really learned how JSON SQL works.

I think a good first next step here is to look at crash and telemetry reports where these JSON operations are used, to find out how to think about it. Maybe FmtAnonymize is always used in combination with FmtHideConstants? In that case we may be in luck.

**Comment by knz** [comment]
Ok so as discussed in #60676 this one is not an issue because the telemetry cosntructs payloads with both FmtAnonymize and FmtHideConstants, and the latter takes care of removing these paths.
