### ISSUE TITLE
sql: the names of custom SQL types are not properly anonymized

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#60674]
Found while investigating #60676

The following statement:

```
SELECT 1::schem.typ
```

must render as

```
SELECT 1::_._
```

under FmtAnonymize

otherwise we are reporting potentially sensitive customer data through telemetry and crash reports.

**Comment by knz** [comment]
cc @vy-ton @rafiss for triage. NB: this is somewhat high priority because it constitutes a confidentiality breach.

**Comment by rafiss** [comment]
It seems the Fmt context is lost here: https://github.com/cockroachdb/cockroach/blob/22e343ccd94e824e23dcfe5482f58fe3da142112/pkg/sql/sem/tree/type_name.go#L197

Using `ref.SQLString()` ignores the context, and instead just uses `FmtBareIdentifiers`. 

We could could use a cast `Name(ref.SQLString())` and call `ctx.FormatNode` on the resulting `Name` but then this would cause _all_ type names to be redacted, which would be a little sad.

**Comment by knz** [comment]
`Name(ref.SQLString()` - I don't think that's valid if the name contains a period e.g. if it hangs off a user defined schema.

**Comment by knz** [comment]
Can we not have a `Format` method on the types?

**Comment by rafiss** [comment]
`types.T` is in a separate package, and cannot have a dependency on `tree`, so therefore it cannot implement `func (t *T) Format(ctx *FmtCtx)`

**Comment by rafiss** [comment]
`types.T` is in a separate package, and cannot have a dependency on `tree`, so therefore it cannot implement `func (t *T) Format(ctx *FmtCtx)`. i'm pretty sure this is why `func (ctx *FmtCtx) FormatTypeReference(ref ResolvableTypeReference)` exists in the first place, so i think we'll have to apply the redaction logic in there for user-defined types when FmtAnonymize is used.

**Comment by rafiss** [comment]
this is a draft of what i had in mind https://github.com/cockroachdb/cockroach/pull/60806
