### ISSUE TITLE
bulkio,cdc: add debugging tools to help debug ExternalStorage interface issues

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#60687]
A common issue that users run into are connection errors (to S3, HTTPS, Kafka, etc...) when running operations such as backup/restore/import/cdc. It is not always clear if the issue connecting with these external services lie within the operation itself, or in the configuration/connection to these services. Therefore, it would be nice to have a command that would allow users to check that the connection to these services are healthy.

This could be especially useful for Kafka since CDC jobs are long-running and we've seen a lot more failures in that area.

Jira issue: CRDB-3158

Epic CRDB-18268

**Comment by mwang1026** [comment]
With tracing, is the thing to do here trying something again or bumping the cloud storage logging level or something else?

**Comment by msbutler** [comment]
relates to https://github.com/cockroachdb/cockroach/issues/81825

**Comment by miretskiy** [comment]
I feel like this issue should be closed -- it's not concrete enough, and we have some mechanisms (tracing, external connection checking, etc) already in place.
