### ISSUE TITLE
sentry events not created for panics in cockroach demo

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#60706]
**Describe the problem**

I discovered #60699 while running `cockroach demo`. After the error occurred, I expected to see it reported in Sentry, along with a corresponding Github issue. As far as I can tell, no Sentry event was triggered.

**Environment:**

```
Build Tag:        v20.2.4
Build Time:       2021/01/21 00:12:56
Distribution:     CCL
Platform:         darwin amd64 (x86_64-apple-darwin14)
Go Version:       go1.13.14
C Compiler:       4.2.1 Compatible Clang 3.8.0 (tags/RELEASE_380/final)
Build Commit ID:  eda2309728392593162e962a61182eab6ab003ff
Build Type:       release
```

cc @knz @otan

**Comment by knz** [comment]
This message:

```
* ERROR: [n1,client=127.0.0.1:50156,hostssl,user=root] Queued as error a83d84364a2f453388b87b97469952e7
```

is proof that _something_ was sent to Sentry.

**Comment by mgartner** [comment]
Perhaps I'm just incapable of finding the event in Sentry. In the [Issues](https://sentry.io/organizations/cockroach-labs/issues/?project=164528&statsPeriod=14d) page with the filter set to "Unresolved" I see no events since 2 days ago.

**Comment by knz** [comment]
yes I agree I cannot find it either. Maybe our sentry proxy has an issue. I am currently fishing up the direct sentry URL to test manually.

**Comment by knz** [comment]
Moving discussion here https://github.com/cockroachlabs/registration/issues/266
