### ISSUE TITLE
sql: BACKUP option encryption_passphrase does not hide when FmtShowPasswords is not specified

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#60703]
Found while investigating #60676

This statement:

```
BACKUP foo TO 'bar' WITH OPTIONS (ENCRYPTION_PASSPHRASE = 'secret')
```

should render as

```
BACKUP foo TO 'bar' WITH OPTIONS (encryption_passphrase = '*****')
```

unless the FmtShowPassword formatting option is specified

@dt unless this was intended? I can fix in #60676 if desired.

**Comment by dt** [comment]
As long as it doesn't render as `secret` in anonymized printing I'm fine with it either way.

**Comment by knz** [comment]
ok cool so you can just review the other PR and that will fix it
