### ISSUE TITLE
schema: DROP and CREATE view within transaction drops the view

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/cockroach#60737]
**Describe the problem**
Dropping and recreating a view within a transaction just drops the view.

**To Reproduce**
```
CREATE TABLE foo (a TEXT, b TEXT);
CREATE VIEW foo_view AS SELECT a FROM foo;
BEGIN;
    DROP VIEW IF EXISTS foo_view;
    CREATE VIEW IF NOT EXISTS foo_view AS SELECT a, b FROM foo;
COMMIT;

SELECT * FROM foo_view;
-- ERROR: relation "foo_view" does not exist
-- SQLSTATE: 42P01
```
**Expected behavior**
The view should be replaced, with the same behavior as a single `CREATE OR REPLACE VIEW...` statement.

**Environment:**
 - CockroachDB version 20.2.4

**Comment by jbowens** [comment]
This was observed in a managed-service migration. cc @petermattis

**Comment by ajwerner** [comment]
This is related to https://github.com/cockroachdb/cockroach/issues/54562 combined with a bad interpretation of IF NOT EXISTS. In the short term, we should return an error here.

**Comment by jordanlewis** [comment]
The theory here is that the `IF NOT EXISTS` code doesn't pay attention to descriptors that are in the dropping state. The proposal is to detect descriptors that are in the dropping state, and return an error instead of doing nothing.

**Comment by lucy-zhang** [comment]
This also happens with database and schemas (and, as was pointed out in #61135, all table descriptors). For types we get the same behavior as without the `IF NOT EXISTS` as described in #54562.

```
demo@127.0.0.1:26257/defaultdb> create type typ as enum('foo');
CREATE TYPE
demo@127.0.0.1:26257/defaultdb> begin;
BEGIN
demo@127.0.0.1:26257/defaultdb  OPEN> drop type typ;
DROP TYPE
demo@127.0.0.1:26257/defaultdb  OPEN> create type if not exists typ as enum('foo');
ERROR: type "typ" already exists
SQLSTATE: 42710
demo@127.0.0.1:26257/? ERROR> rollback;
ROLLBACK
```

```
demo@127.0.0.1:26257/defaultdb> create schema sc;
CREATE SCHEMA
demo@127.0.0.1:26257/defaultdb> begin;
BEGIN
demo@127.0.0.1:26257/defaultdb  OPEN> drop schema sc;
DROP SCHEMA
demo@127.0.0.1:26257/defaultdb  OPEN> create schema if not exists sc;
CREATE SCHEMA
demo@127.0.0.1:26257/defaultdb  OPEN> commit;
COMMIT
demo@127.0.0.1:26257/defaultdb> show schemas;
     schema_name     | owner
---------------------+--------
  crdb_internal      | NULL
  information_schema | NULL
  pg_catalog         | NULL
  pg_extension       | NULL
  public             | admin
(5 rows)
```

```
demo@127.0.0.1:26257/defaultdb> create database db;
CREATE DATABASE
demo@127.0.0.1:26257/defaultdb> begin;
BEGIN
demo@127.0.0.1:26257/defaultdb  OPEN> drop database db;
DROP DATABASE
demo@127.0.0.1:26257/defaultdb  OPEN> create database if not exists db;
CREATE DATABASE
demo@127.0.0.1:26257/defaultdb  OPEN> commit;
COMMIT
demo@127.0.0.1:26257/defaultdb> show databases;
  database_name | owner | primary_region | regions | survival_goal
----------------+-------+----------------+---------+----------------
  defaultdb     | root  | NULL           | {}      | NULL
  postgres      | root  | NULL           | {}      | NULL
  system        | node  | NULL           | {}      | NULL
(3 rows)
```

**Comment by fqazi** [comment]
Should break off other types into a different issue? Or just do in the current one? Those cases won't have shared code.

**Comment by ajwerner** [comment]
> Should break off other types into a different issue? Or just do in the current one? Those cases won't have shared code.

Separate PR at the very least. I'll split off issues now.

**Comment by ajwerner** [comment]
https://github.com/cockroachdb/cockroach/issues/61149
https://github.com/cockroachdb/cockroach/issues/61150
