### ISSUE TITLE
invalid parameter set calculated for prepared statement for nested text arrays

### ISSUE THREAD

**Issue by jdabrowski** [cockroachdb/cockroach#60732]
**Describe the problem**

When creating prepared statement and letting server calculate parameter types based on sql query it returns TEXT instead of TEXT_ARRAY for nested arrays.

Details:
I'm migrating from Postgres to CockroachDB. I'm using vertx platform with vertx pg client. When creating prepared statement it relies on response from server:

https://github.com/eclipse-vertx/vertx-sql-client/blob/3.9/vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/PgEncoder.java#L328

I have a query:

`UPDATE users SET customers = array(select unnest(customers::text[]) except select unnest($2::text[]) union select unnest($3::text[])),modified_date = $1 WHERE uuid = $4`

where "customers" is TEXT[]. When I run this trough pgcli as simple query it works fine. Example:

`UPDATE users SET customers = array(select unnest(customers::text[]) except select unnest('{aaa, bbb}'::text[]) union select unnest('{aaa}'::text[])),modified_date = '20210218091011Z' WHERE uuid = '9f940d58-4d4a-4b6a-9c21-a0977a1e6216';`

But when I run it through pg-client from vertx it fails with:
`io.vertx.core.impl.NoStackTraceThrowable: Parameter at position[1] with class = [[Ljava.lang.String;] and value = [[Ljava.lang.String;@ec63b82] can not be coerced to the expected class = [java.lang.String] for encoding.`

I did some more digging and found out that when I have Postgres (11.5) the response from it for parameter set is:
25,1009,1009,25 - meaning TEXT, TEXT_ARRAY, TEXT_ARRAY, TEXT
but from CockroachDB (latest stable and latest instable):
25,25,25,25 - meaning TEXT, TEXT, TEXT, TEXT

**To Reproduce**

1. Set up CockroachDB cluster
2. Send above sql to analyze parameters for prepared statement
3. Desired response should be 25,1009,1009,25 like for Postgres, but 25,25,25,25 is returned

**Expected behavior**
It should return 25,1009,1009,25  same as Postgres

**Environment:**
 - CockroachDB version - newest official docker (20.2.4)
 - Server OS: macOS 11
 - Client app - vertx based app with vertx-pg-client

**Comment by rafiss** [comment]
This appears to be another instance of this bug: https://github.com/cockroachdb/cockroach/issues/60907

**Comment by jdabrowski** [comment]
Yep, I'll track #60907, thanks
