### ISSUE TITLE
Support experimental-userfile sink

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#60743]
Tiny change to make changefeeds work with userfile://
(we already support nodelocal -- so  this change is trivial)

**Comment by abid1998** [comment]
I can work on this issue if someone can explain it to me. I am a new contributor.

**Comment by lucasnorman** [comment]
@miretskiy would you please link https://github.com/cockroachdb/cockroach/pull/63778 and/or assign the issue to me?
