### ISSUE TITLE
sql/catalog: type backreferences capture both direct and indirect references

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#60741]
**Describe the problem**

In general, we'd like our backreference accounting on descriptors to only contain direct references. Otherwise, the validating of these back-references may exploring a potentially unbounded graph (as would be the case if we permitted structural user-defined types). Today we only have enum which statically only have a static alias and array type defined. Given the static nature of the relationship between arrays and their array and alias types, it's okay-ish. The biggest thorn relates to validating tables and their backreferences. Namely, we'd like it to be the case that when a table validates its cross-references that it has a complete set of checks (i.e. there aren't any references that it did not check). That means when validating a table we'll want to enumerate and validate the type backreferences for types directly referenced and then go fetch any types referenced via arrays or aliases and validate those. 

**Solutions**

One thing we could do is make a migration to change the type back-references to only be direct references. This would be a somewhat involved migration but it wouldn't be too terrible. 

Another thing we could do is just more completely specify that we're going to keep these indirect references for these alias and array for enum cases and make it so other types which refer to other types more generally don't have the same policy. For now this is the direction we should go. 

Jira issue: CRDB-3147

**Comment by postamar** [comment]
Subsumed by #63161
