### ISSUE TITLE
sql: ensure multi-region assertion failed errors are scrubbed of sensitive data

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#60768]
Assertion errors are reported as telemetry and should be scrubbed before being reported to us. As part of the recent multi-region efforts we've been adding bunch of assertion errors, but we haven't been principled about ensuring no region/identifier name information leaks. One example I found in code was this: 
https://github.com/cockroachdb/cockroach/blob/0c413d3c7d1372e1454b813709ac7437db3e5282/pkg/sql/alter_database.go#L427

but I'm sure there may be other places where things have slipped through the cracks. This issue is to validate and fix any places where things may have leaked.

**Comment by otan** [comment]
i thought errors.AssertionFailedf would redact any format strings.
is there evidence of the contrary?
it ends up down here in the end: https://github.com/cockroachdb/errors/blob/4c1636886a764323efed240d738357ea251908bb/errutil/utilities.go#L77

**Comment by ajstorm** [comment]
Based on the above, this issue should scrub all of our `AssertionFailedf` calls to ensure that all of them are using the proper primitives, and none of them are directly encoding with a `fmt.Sprintf`.

**Comment by otan** [comment]
i think we're fine based on

```
 ✘ ⚙ otan@otan-mbp  ~/go/src/github.com/cockroachdb/cockroach   telemetry_baby  ag -multiline 'AssertionFailedf.*fmt'
 ✘ ⚙ otan@otan-mbp  ~/go/src/github.com/cockroachdb/cockroach   telemetry_baby  ag -multiline 'AssertionFailedf\n.*fmt'
 ✘ ⚙ otan@otan-mbp  ~/go/src/github.com/cockroachdb/cockroach   telemetry_baby  ag -multiline 'AssertionFailedf\n.*\+'
 ✘ ⚙ otan@otan-mbp  ~/go/src/github.com/cockroachdb/cockroach   telemetry_baby  ag -multiline 'AssertionFailedf.*\+'
```
