### ISSUE TITLE
tree: enforce correct use of FmtCtx with a better interface or linting

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#60797]
This is in reference to @knz's work on #60676 and his message below, in which he identified how easy it is to accidentally forget to apply the proper FmtCtx.

> a casual exchange on Slack made me suspect that we had far-reaching, thorough and critical brokenness in our SQL AST pretty-printing code, and after investigation it appears that I was right (unfortunately).
> 
> For context, after parsing the AST of SQL trees gets pretty-printed in various contexts. The two things of interest today are:
> 
> - the "literal removed" mode, used to construct statement keys in stats. This is important because it allows us to "group" two similar-looking statements under the same stats bucket.
> 
> - the "identifiers removed", a.k.a. "anonymized" mode, used to produce crash reports and telemetry.
> 
> This last one is absolutely, absolutely critical to get right.
> 
> Anonymization is foundational to the trust that our customers place in us to not leak their sensitive data. Identifiers are part of customer's intellectual property and is to be treated with utmost care. We must be very careful to not include this customer-sensitive data in the telemetry and crash reports that are sent automatically to CRL.
> 
> 
> And it turns out, there was a slew of cases where the code was not right and we were including sensitive identifiers in supposedly-anonymized payloads.
> 
> Here are some examples:
> 
> SHOW SYNTAX .. -- the string was not anonymized
> 
> ALTER TABLE SET REGIONAL BY TABLE IN .. -- the region information was not anonymized
> 
> RESUME JOBS FOR SCHEDULES ...  -- everything after SCHEDULES was not anonymized
> 
> SHOW SCHEDULE ... -- everything in the schedule was not anonymized
> 
> 
> To get this right is relatively easy: when implementing a Format(ctx) method for a new AST node, call `ctx.FormatNode(child)` on the children nodes. Don't use 'child.Format(ctx)`. The latter causes the data to be wrongly de-anonymized.
> 
> Also whatever you do do not format with e.g. `ctx.WriteString(child.String())` , that is the worst of all.
> 
> 
> The reason why we did not catch this earlier is that the place this is tested does not invite more tests: the location of the test was in `sql/sem/tree`, whereas all our test code for new AST nodes is primarily in `sql/parser`. So it's just natural that folk forgot to add the tests.
> 
> I am attempting to correct this in this PR: https://github.com/cockroachdb/cockroach/pull/60676
> 
> However there are still some technical shortcomings, because we didn't think about this properly when designing JSON expressions and custom SQL types:
> 
> https://github.com/cockroachdb/cockroach/issues/60673
> 
> https://github.com/cockroachdb/cockroach/issues/60674
> 
> 
> I would invite the team to help think about how to make this better and be mindful of anonymization in the future.
> 
> Also it may be worth looking into a linter to prevent the mistake from happening in the first place, even in the absence of tests.

Jira issue: CRDB-3139

**Comment by RaduBerinde** [comment]
One suggestion is to rename Format to something like FormatImpl and add a linter which checks that nobody (other than FormatNode) calls that.

**Comment by knz** [comment]
we've done this in the new version of the parser tests
