### ISSUE TITLE
acceptance: run test of compatibility with reference binary in deploy tests

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#6086]
Verification of on-disk compatibility is currently skipped during the _deploy-time_ acceptance test runs.

Deploy-time tests run the acceptance tests with a real cockroach docker image, rather than a bound binary in the builder image as in other acceptance test runs, but the reference binary test relies on the bound binary, as it invokes the different binaries in the same container. Although more complex and likely slower, rewriting that test to spin up separate containers would allow running against the image in deploy tests, as well as using a published image for the reference image.

**Comment by dt** [comment]
(un-assigning for now since I'm not actively doing this at the moment)

**Comment by spencerkimball** [comment]
@dt is this something required for 1.0? I'm assuming not, and removing that milestone. Please re-add if you believe this must be resolved for 1.0.

**Comment by dt** [comment]
yeah, we can probably even just close this issue entirely.
