### ISSUE TITLE
sql: incorrect ParameterDescription for prepared statement

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#60907]
**Describe the problem**

Creating a prepared statement that uses a placeholder argument for a function parameter causes CockroachDB to incorrectly infer the type of the placeholder. This means that some drivers (such as pgx) error out when using prepared statements like this.

**To Reproduce**

Run the pgx test: [TestConnSendBatchWithPreparedStatement](https://github.com/jackc/pgx/blob/ac2918b9a32454f04833395a7be31d1e136782f8/batch_test.go#L182). Clone the pgx repo at tag `v4.10.1` and then run: 

```
PGX_TEST_DATABASE='postgresql://root:@localhost:26257/defaultdb' go test -v -run TestConnSendBatchWithPreparedStatement
```

It tries to prepare the statement: `select n from generate_series(0,$1::int) n`.

CockroachDB returns a ParameterDescription that says the OID is 25 (text), which causes the test to fail. 

**Expected behavior**
CockroachDB should say that the OID is for an integer type.

**Environment:**
 - CockroachDB version v20.2.2
 - pgx v4.10.1

**Additional context**
Also reported in https://github.com/cockroachdb/cockroach/issues/60732 

This can also be reproduced with the following datadriven [pgtest](https://github.com/cockroachdb/cockroach/blob/894efb0215580cddc285e21b1232326b375d391c/pkg/sql/pgwire/pgtest_test.go#L31)

```
send
Parse {"Name": "s1", "Query": "select n from generate_series(0,$1::int) n"}
Describe {"ObjectType": 83, "Name": "s1"}
Bind {"DestinationPortal": "p", "PreparedStatement": "s1", "ParameterFormatCodes": [0], "Parameters": [[50]]}
Execute {"Portal": "p"}
Sync
----

until
ReadyForQuery
----
{"Type":"ParseComplete"}
{"Type":"ParameterDescription","ParameterOIDs":[23]}
{"Type":"RowDescription","Fields":[{"Name":"n","TableOID":0,"TableAttributeNumber":0,"DataTypeOID":23,"DataTypeSize":4,"TypeModifier":-1,"Format":0}]}
{"Type":"BindComplete"}
{"Type":"DataRow","Values":[{"text":"0"}]}
{"Type":"DataRow","Values":[{"text":"1"}]}
{"Type":"DataRow","Values":[{"text":"2"}]}
{"Type":"CommandComplete","CommandTag":"SELECT 3"}
{"Type":"ReadyForQuery","TxStatus":"I"}
```

**Comment by rafiss** [comment]
I'm not sure if this relates to https://github.com/cockroachdb/cockroach/issues/41558

**Comment by rafiss** [comment]
I tracked this down to https://github.com/cockroachdb/cockroach/blob/0392845ac2ace1984b1da1468d1bf0e51f6c6f81/pkg/sql/sem/tree/type_check.go#L467-L472

We are intentionally setting the type to `string` in some cases when a placeholder is used as a function argument.

I will investigate how we can do better here.

**Comment by jdabrowski** [comment]
Awesome. 
I tested it locally and it resolved my issue from #60732 

What version (release) it has a chance to fit?

**Comment by rafiss** [comment]
@jdabrowski Glad it worked! Your example was also helpful for testing this. This fix will be in v21.1.0, which will come out soon. There will also be an alpha version of v21.1 that should be available in a week or two.

**Comment by onthegit** [comment]
Does it fix #jackc/pgx/issues/944 ?  I think it is related to  #41558  but still marked as open?

**Comment by rafiss** [comment]
It should fix the query in [this comment](https://github.com/jackc/pgx/issues/944#issuecomment-782920674)

The query in [the other comment](https://github.com/jackc/pgx/issues/944#issue-812936822) is not working because of a separate issue (https://github.com/cockroachdb/cockroach/issues/41558)

**Comment by onthegit** [comment]
@rafiss  ok, thanks!
