### ISSUE TITLE
build: Support 32-bit ARM

### ISSUE THREAD

**Issue by linuxerwang** [cockroachdb/cockroach#6091]
1. What version of CockroachDB are you using (`cockroach version`)?

Build Tag: beta-20160414
Build Time:  2016/04/16 06:25:06
Platform:    linux arm
Go Version:  go1.6
C Compiler:  gcc 4.8.4
1. What operating system and processor architecture are you using?

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:        14.04
Codename:       trusty

$ uname -a
Linux firefly 3.10.0 #95 SMP PREEMPT Thu Dec 3 17:55:31 CST 2015 armv7l armv7l armv7l GNU/Linux
1. What flags/environment variables did you pass to `cockroach start`?

No flags, only "cockroach start".

Please describe the issue you observed:
1. What did you do?

I compiled the latest cockroach release src code, and compiled it on a ARM hf 32 bits Linux box. I had to do the following change in this file github.com/cockroachdb/c-rocksdb/cgo_flags.go:

-// #cgo CXXFLAGS: -std=c++11 -fno-omit-frame-pointer -momit-leaf-frame-pointer
+// #cgo CXXFLAGS: -std=c++11 -fno-omit-frame-pointer

otherwise it complained it doesn't know "momit-leaf-frame-pointer".

Other than that, the compilation is smooth.
1. What did you expect to see?

Cockroach can be started.
1. What did you see instead?

I tried command "./cockroach start", but it failed to start with the following errors:

build:      @ 2016/04/16 06:25:06 (go1.6)
admin:     http://localhost:8080
sql:       postgresql://root@localhost:26257?sslmode=disable
logs:      cockroach-data/logs
store[0]:  path=cockroach-data
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x4 pc=0x2870dc]

goroutine 55 [running]:
panic(0xf53000, 0x96d3e030)
    /usr/share/go-golang/src/runtime/panic.go:464 +0x330
sync/atomic.storeUint64(0x96fec854, 0xeaefc82, 0x1445c41c)
    /usr/share/go-golang/src/sync/atomic/64bit_arm.go:20 +0x40
github.com/cockroachdb/cockroach/kv.(_txnMetadata).setLastUpdate(0x96fec7e0, 0xeaefc82, 0x1445c41c)
    /home/linuxerwang/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:104 +0x48
github.com/cockroachdb/cockroach/kv.(_TxnCoordSender).updateState(0x97034dc0, 0xc6092b5, 0x1445c41c, 0x8534d3f8, 0x96e95d00, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /home/linuxerwang/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:867 +0x568
github.com/cockroachdb/cockroach/kv.(_TxnCoordSender).Send(0x97034dc0, 0x8534d3f8, 0x96e95d00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /home/linuxerwang/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:416 +0xb8c
github.com/cockroachdb/cockroach/client.(_txnSender).Send(0x96feac30, 0x8534cd28, 0x96dd1a2c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /home/linuxerwang/go/src/github.com/cockroachdb/cockroach/client/txn.go:59 +0xa8
github.com/cockroachdb/cockroach/client.(_DB).send(0x96feac30, 0x0, 0x0, 0x0, 0x97297dd0, 0x6, 0x6, 0x5, 0x96cfa14b)
    /home/linuxerwang/go/src/github.com/cockroachdb/cockroach/client/db.go:474 +0x340
github.com/cockroachdb/cockroach/client.(_Txn).send(0x96feac30, 0x0, 0x0, 0x0, 0x97297dd0, 0x6, 0x6, 0x51b348, 0x5)
    /home/linuxerwang/go/src/github.com/cockroachdb/cockroach/client/txn.go:649 +0x8c8
github.com/cockroachdb/cockroach/client.(_Txn).(github.com/cockroachdb/cockroach/client.send)-fm(0x0, 0x0, 0x0, 0x96ef6b80, 0x5, 0x8, 0x97271104, 0x51b328)
    /home/linuxerwang/go/src/github.com/cockroachdb/cockroach/client/txn.go:361 +0x5c
github.com/cockroachdb/cockroach/client.sendAndFill(0x97271110, 0x96d90e00, 0x0, 0x0)
    /home/linuxerwang/go/src/github.com/cockroachdb/cockroach/client/db.go:386 +0x60
github.com/cockroachdb/cockroach/client.(_Txn).RunWithResponse(0x96feac30, 0x96d90e00, 0x0, 0x0)
    /home/linuxerwang/go/src/github.com/cockroachdb/cockroach/client/txn.go:361 +0xa8
github.com/cockroachdb/cockroach/client.(_Txn).Run(0x96feac30, 0x96d90e00, 0x0)
    /home/linuxerwang/go/src/github.com/cockroachdb/cockroach/client/txn.go:349 +0x28
github.com/cockroachdb/cockroach/sql.(_planner).Insert(0x96e72e00, 0x9702df00, 0xe984f100, 0x0, 0x0, 0x72e874)
    /home/linuxerwang/go/src/github.com/cockroachdb/cockroach/sql/insert.go:304 +0x2820
github.com/cockroachdb/cockroach/sql.(_planner).makePlan(0x96e72e00, 0x8534d7f8, 0x9702df00, 0x96fff900, 0x0, 0x0, 0x0)
    /home/linuxerwang/go/src/github.com/cockroachdb/cockroach/sql/plan.go:225 +0x12bc
github.com/cockroachdb/cockroach/sql.(_planner).query(0x96e72e00, 0x12f8068, 0x74, 0x96fd9380, 0x5, 0x5, 0x0, 0x0, 0x400)
    /home/linuxerwang/go/src/github.com/cockroachdb/cockroach/sql/plan.go:320 +0x158
github.com/cockroachdb/cockroach/sql.(_planner).exec(0x96e72e00, 0x12f8068, 0x74, 0x96fd9380, 0x5, 0x5, 0x86bd7258, 0x0)
    /home/linuxerwang/go/src/github.com/cockroachdb/cockroach/sql/plan.go:345 +0x4c
github.com/cockroachdb/cockroach/sql.InternalExecutor.ExecuteStatementInTransaction(0x97036c80, 0x96feac30, 0x12f8068, 0x74, 0x96fd9380, 0x5, 0x5, 0x1968cf0, 0x0)
    /home/linuxerwang/go/src/github.com/cockroachdb/cockroach/sql/internal.go:44 +0x190
github.com/cockroachdb/cockroach/sql.EventLogger.InsertEventRecord(0x97036c80, 0x96feac30, 0x107ecd8, 0xc, 0x1, 0x1, 0xf63278, 0x97021080, 0x97271b94)
    /home/linuxerwang/go/src/github.com/cockroachdb/cockroach/sql/event_log.go:106 +0x340
github.com/cockroachdb/cockroach/server.(_Node).recordJoinEvent.func1.1(0x96feac30, 0x97271b00)
    /home/linuxerwang/go/src/github.com/cockroachdb/cockroach/server/node.go:663 +0x104
github.com/cockroachdb/cockroach/client.(_DB).Txn.func1(0x96feac30, 0x96ffee60, 0x10)
    /home/linuxerwang/go/src/github.com/cockroachdb/cockroach/client/db.go:438 +0x2c
github.com/cockroachdb/cockroach/client.(_Txn).Exec(0x96feac30, 0x13f0101, 0x0, 0x0, 0x0, 0x97271d84, 0x0)
    /home/linuxerwang/go/src/github.com/cockroachdb/cockroach/client/txn.go:531 +0x304
github.com/cockroachdb/cockroach/client.(_DB).Txn(0x97034e00, 0x97271e94, 0x0)
    /home/linuxerwang/go/src/github.com/cockroachdb/cockroach/client/db.go:436 +0x244
github.com/cockroachdb/cockroach/server.(_Node).recordJoinEvent.func1()
    /home/linuxerwang/go/src/github.com/cockroachdb/cockroach/server/node.go:653 +0x1f4
github.com/cockroachdb/cockroach/util/stop.(_Stopper).RunWorker.func1(0x97034540, 0x96eee2a0)
    /home/linuxerwang/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x68
created by github.com/cockroachdb/cockroach/util/stop.(_Stopper).RunWorker
    /home/linuxerwang/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x64

**Comment by tschottdorf** [comment]
Thanks @linuxerwang. I think what we're seeing here is https://github.com/coreos/etcd/issues/2308, so likely it can be fixed by shuffling some field definitions around. We should look into that (though it's kind of horrible that something like that would matter).

**Comment by linuxerwang** [comment]
Seems like the problem has been fixed in 2015, maybe cockroach has old deps copy?

I agree it's bad to rely on field shuffling.

Thanks for the help.

**Comment by linuxerwang** [comment]
I misunderstood. After rereading the etcd issue, I moved the two int64 fields in txnMetadata up to top, and everything works now.

It's good to see it working, but sad having to do this.

**Comment by bdarnell** [comment]
The bug in the go compiler is golang/go#599.

There's a note in `CONTRIBUTING.md` that says we only support 64-bit builds, but we've forgotten why. This was probably the reason (or at least one of the reasons: i thought there was something related to rocksdb as well).

**Comment by knz** [comment]
hi @linuxerwang to follow up on this we got some success running CockroachDB on ARM, using the raspberry pi. We wrote a few notes about this process: https://github.com/cockroachdb/cockroach/wiki/Running-CockroachDB-on-a-Raspberry-Pi

Do you mind looking at this and checking whether these build notes apply to you as well and could help you run CockroachDB?

**Comment by linuxerwang** [comment]
Sure, will find some time on it this week. Thanks!

**Comment by knz** [comment]
Moving forward we will probably prioritize 64-bit arm. The blog post linked above can cover the 32 bit case.
