### ISSUE TITLE
kv/kvnemesis: rare resolved timestamp violation

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#60929]
After about 45 minutes of running kvnemesis, I often see an error like:

```
make roachprod-stress PKG=./pkg/kv/kvnemesis TESTS=TestKVNemesisMultiNode TESTTIMEOUT=2m CLUSTER=nathan-stress
```

```
        panic: resolved timestamp 1613982715.406343041,0 equal to or above timestamp of operation {<nil> txn_id:2a60432a-fa66-408c-9160-7ff86c54f2b9 txn_key:"\272\0220b2e8742\000\001" txn_min_timestamp:<wall_time:1613982715404791290 > timestamp:<wall_time:1613982715404791290 >  <nil> <nil> <nil> <nil>}

goroutine 2815 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc000914380, 0x5118be0, 0xc004067e30)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:233 +0x126
panic(0x3bca140, 0xc0045ff4c0)
        /usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*resolvedTimestamp).assertOpAboveRTS(0xc004dfcfd8, 0x0, 0xc003334780, 0x0, 0x0, 0x0, 0x0, 0x166604ba7952adfa, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/resolved_timestamp.go:251 +0x165
github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*resolvedTimestamp).consumeLogicalOp(0xc004dfcfd8, 0x0, 0xc003334780, 0x0, 0x0, 0x0, 0x0, 0xc0032b6060)
        /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/resolved_timestamp.go:146 +0x296
github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*resolvedTimestamp).ConsumeLogicalOp(0xc004dfcfd8, 0x0, 0xc003334780, 0x0, 0x0, 0x0, 0x0, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/resolved_timestamp.go:132 +0x4d
github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*Processor).consumeLogicalOps(0xc004dfcf20, 0x5118b20, 0xc003ef8b00, 0xc0042d2990, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/processor.go:591 +0x227
github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*Processor).consumeEvent(0xc004dfcf20, 0x5118b20, 0xc003ef8b00, 0xc003518230)
        /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/processor.go:540 +0x294
github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*Processor).run(0xc004dfcf20, 0x5118be0, 0xc004067e30, 0xc0042b3820, 0xc000914380)
        /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/processor.go:286 +0xb7a
github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*Processor).Start.func1(0x5118be0, 0xc004067e30)
        /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/processor.go:196 +0x50
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc000914380, 0x5118be0, 0xc004067e30, 0x0, 0xc0042b3840)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:351 +0xb9
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:346 +0xfc
```
At first, I figured that this was fallout from https://github.com/cockroachdb/cockroach/pull/59566, but I've managed to reproduce with that change disabled. This is an `MVCCWriteIntentOp` below a range's resolved timestamp, which should never be allowed.

**Comment by knz** [comment]
Presumably fixed by #60992. Please reopen if not.

**Comment by knz** [comment]
Andrei says it's different so leaving this one open

**Comment by nvanbenschoten** [comment]
I think I see the problem here. We consider a range's lease start time to be closed (see explanation in 7037b54), but this can be violated by a write to the subsumed keyspace after a range merge causes a range to grow. In such cases, we [bump the leaseholder's timestamp cache](https://github.com/cockroachdb/cockroach/blob/f3c8f6ed74494f93bd1eb01b1d7569127f127906/pkg/kv/kvserver/store_merge.go#L103) over the subsumed keyspace to the freeze time, but this may still lag behind the LHS range's lease start time. This allows a write to land on the subsumed side of the range below the lease start time. Unless I'm missing something, we'll either want to bump the subsumed keyspace to the lease start time during a merge or stop considering the lease start time as a contributor to the closed timestamp (which we may want to do anyway, see https://github.com/cockroachdb/cockroach/issues/61989).

There might be more to this story, as I'm also seeing evidence that a leaseholder has a clock below its lease start time. I wouldn't expect this to be possible, but I'm also now second-guessing that we properly prevent it. We do set the `Timestamp` on lease requests [here](https://github.com/cockroachdb/cockroach/blob/f3c8f6ed74494f93bd1eb01b1d7569127f127906/pkg/kv/kvserver/replica_range_lease.go#L418), but the resulting lease can end up with a higher timestamp (as of https://github.com/cockroachdb/cockroach/commit/c44b35772592f70c836628495a2e2babcff97556):
https://github.com/cockroachdb/cockroach/blob/e09b93fe62541c3a94f32a723778660b528a0792/pkg/kv/kvserver/batcheval/cmd_lease_transfer.go#L71-L77

It's unclear whether this is contributing to the issue, merely making it more likely, or unrelated.

cc. @andreimatei you might have thoughts here.

**Comment by andreimatei** [comment]
>  but this can be violated by a write to the subsumed keyspace after a range merge causes a range to grow

Can you spell this out for me? Isn't a write to the subsumed keyspace after a merge bumped above the merged lease? And what does it mean for it to "cause a range to grow"?

**Comment by nvanbenschoten** [comment]
> Isn't a write to the subsumed keyspace after a merge bumped above the merged lease?

That's the problem - what enforces this? In the usual case, a new lease bumps the timestamp cache across a range's keyspace to the lease start time. But if the range then grows because it merges in its RHS neighbor, the timestamp cache for this newly added keyspace isn't guaranteed to be above the LHS's lease start time. So the LHS can serve writes below its lease start time, violating its reported closed timestamp.

**Comment by andreimatei** [comment]
Yeah, this seems like a bug. Like you're saying, it doesn't seem like the lease start time should be particularly tied to the closed timestamp. Particularly in 21.1, where a lease change doesn't cause a regression in any replica's info about what closed timestamp applies.
