### ISSUE TITLE
kvserver: check that raft leadership following lease works well in cases where leaseholder cannot win election

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#60924]
Periodically (during raft ticks), we check whether the current replica holds the lease. If not, and if it is the raft leader, we attempt to transfer raft leadership to the leaseholder.

In the aftermath of a recent customer incident the question arose whether this mechanism works correctly in the rare case in which the leaseholder cannot win a Raft election. The behavior in that scenario should be investigated and documented.

**Comment by nvanbenschoten** [comment]
@tbg is there anything more to this issue? Do you have anything you can link to to provide more context? What are the hazards ("whether this mechanism works correctly") that were called into question?

**Comment by tbg** [comment]
I wasn't able to find the missing backreference in our support repo (I looked through [these](https://github.com/cockroachlabs/support/issues?q=is%3Aissue+after%3A2021-02-01+before%3A2021-02-23+involves%3Atbg+sort%3Acreated-asc+))
