### ISSUE TITLE
sql: RETURNING does not uses table aliases

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#6092]
With:

``` sql
UPDATE foo AS x SET ... RETURNING x.blah
```

we get the error:

```
pq: qualified name "xx.blah" not found
```

even when table `foo` has a column `blah`.

**Comment by knz** [comment]
Should wait until #5903 lands.

**Comment by tamird** [comment]
#5903 is in; does this need to be reexamined?

**Comment by knz** [comment]
Yes it does. And it's not trivial either...

**Comment by spencerkimball** [comment]
@knz, I'm moving this from 1.0 milestone. This really doesn't feel like it should hold up the release. Please assign and add 1.0 milestone if you disagree.
