### ISSUE TITLE
Add table name in error message

### ISSUE THREAD

**Issue by douglasselias** [cockroachdb/cockroach#60920]
**Is your feature request related to a problem? Please describe.**

Cockroach doesn't return the table name on the error message when trying to drop a contraint.

**Describe the solution you'd like**

Cockroach should return the table name like Postgres does.

For example: this query `ALTER TABLE "users" DROP CONSTRAINT "unknown__constraint__name";` on Postgres returns this error: `ERROR: constraint "unknown__constraint__name" of relation "users" does not exist` but in Cockroach returns this error: `ERROR: constraint "unknown__constraint__name" does not exist`

**Comment by ajwerner** [comment]
Thanks for reporting this! Error consistency in this sort of schema validation error is something on our roadmap to address for the next release (v21.2). I'll track this so we do something about it.
