### ISSUE TITLE
Update sequences to be stored by ID when doing backup/restore

### ISSUE THREAD

**Issue by the-ericwang35** [cockroachdb/cockroach#60942]
**Describe the problem**

There now exists functionality for newly created sequences to be renamed, since we are now storing references to sequences via their IDs. Currently, if we backup sequences in earlier versions (before this renaming functionality) and then restore them in newer versions (that do support sequence renaming), these restored sequences still behave like old sequence. This means that they are still stored via their names, and they cannot be renamed.

**Expected behavior**
We want restored sequences to behave like sequences created in newer versions. That is, restored sequences should be stored by ID and have the ability to be renamed. This means we'll have to update the existing tests as well (see https://github.com/cockroachdb/cockroach/pull/60957)

Jira issue: CRDB-3097

**Comment by adityamaru** [comment]
This will be addressed in 21.2 once we get the green light from sql-schema and potentially after we address the bigger issue of restore and migrations as detailed in - https://github.com/cockroachdb/cockroach/issues/58611.

**Comment by ajwerner** [comment]
This seems important and like a rather bad bug involving `ON UPDATE`. I'd even consider backporting this.
