### ISSUE TITLE
sql:SHOW CONSTRAINTS displays the wrong default primary key constraint name

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/cockroach#60966]
**Actual behavior**
The default primary key constraint name is `"primary"`. However, we omit the `""` when listing constraints
```
demo@127.0.0.1:26257/movr> CREATE TABLE logon (
    login_id INT PRIMARY KEY
  );
demo@127.0.0.1:26257/movr> show constraints from logon;
  table_name | constraint_name | constraint_type |          details           | validated
-------------+-----------------+-----------------+----------------------------+------------
  logon      | primary         | PRIMARY KEY     | PRIMARY KEY (login_id ASC) |   true
demo@127.0.0.1:26257/movr> alter table logon rename constraint primary to pk;
invalid syntax: statement ignored: at or near "primary": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
alter table logon rename constraint primary to pk
                                    ^
HINT: try \h ALTER TABLE
demo@127.0.0.1:26257/movr> alter table logon rename constraint "primary" to pk;
ALTER TABLE
```

**Expected behavior**
`SHOW CONSTRAINTS` should list the name as `"primary"`, so that users are not confused during introspection or rename.

**Comment by ajwerner** [comment]
Huh, I mean, it's safe to just double quote literally everything. We can do that if it makes you happy. The thing is that reserved keywords need to be double quoted. Primary is a reserved keyword. This ends up being a formatting thing.

**Comment by vy-ton** [comment]
I hadn't considered the overlap with reserved keywords. In which case I'm good with closing this
