### ISSUE TITLE
bazel: come up with substitute logic for  non-reproducible stuff in build

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#60963]
In the `Makefile`, we [tag every build](https://github.com/cockroachdb/cockroach/blob/23a4e63daac63bb9207cc0d73c9d44aec7ca60a6/Makefile#L972) with the time the build occurred. This is obviously non-hermetic/non-reproducible behavior. Similarly, there's `build.rev`, `build.tag`, ` build.channel` -- all stuff that Bazel wouldn't allow by default.

Either come up with substitute logic that allows us to implement the same stuff in Bazel, or come up with a plan for moving us away from this non-reproducible design.

Epic CRDB-8035

**Comment by otan** [comment]
shower thought: i wonder if we should have these off by default, and on only for generating release binaries.

**Comment by rickystewart** [comment]
https://kchodorow.com/2017/03/27/stamping-your-builds/

Yes, I think that having all of this stuff off for everything except for release binaries (where we can leverage the stamping functionality described here) would solve this.

**Comment by rickystewart** [comment]
Closing in favor of #66853 which is a duplicate
