### ISSUE TITLE
sql/ui: add a last executed time on statement details page

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#60974]
There have been some customer requests for a last executed time on the statement details page so that folks can understand the last time a statement was executed to better understand performance. This would be more useful when developing than in production but it still valuable. Note, this doesn't apply to the statements page because its a fingerprint which is a collection of statements. This is somewhat related to historical persistence and comparing over time as well https://github.com/cockroachdb/cockroach/issues/40245 https://github.com/cockroachdb/cockroach/issues/56219

**Comment by maryliag** [comment]
@Annebirzin where should I add this field on the details page?

**Comment by maryliag** [comment]
<img width="536" alt="Screen Shot 2021-04-12 at 5 16 46 PM" src="https://user-images.githubusercontent.com/1017486/114463805-ec8bc900-9bb2-11eb-9066-dc8f3264a855.png">

**Comment by Annebirzin** [comment]
@maryliag that works for me, let's just update the label to `Last execution time`. (at some point we may want to re-organize this panel, but will hold off for now as we may be adding more metrics)

Also related to https://github.com/cockroachdb/cockroach/issues/33316: as Andy mentioned I think we'll want to add the databases to the statement detail page as well. I've updated the designs here to include both those fields:  https://www.figma.com/file/MoSPFkEyJfGipCmQvvLg1a/21.1_SQL-obsrv_query-performance?node-id=1888%3A68852

**Comment by awoods187** [comment]
This looks good to me! Thanks @Annebirzin and @maryliag

**Comment by kenliu-crl** [comment]
test comment, please ignore.
