### ISSUE TITLE
Multiraft performance degradation with increasing node count

### ISSUE THREAD

**Issue by Frank-Jin** [cockroachdb/cockroach#610]
I create about six hundred ranges in a node, and system will become slower and slower. I find the bottleneck may be the process of raft's tick that includes the access of rocksdb.

coreos/etcd/raft/multinode.go:
```go
case <-mn.tickc:
			// TODO(bdarnell): instead of calling every group on every tick,
			// we should have a priority queue of groups based on their next
			// time-based event.
			for _, g := range groups {
				g.raft.tick()
				rd := g.newReady()
				if rd.containsUpdates() {
					rds[g.id] = rd
				}
			}
```
I find newReady need use MVCCGetProto to access the persistent storage, the call path is newReady->r.raftLog.nextEnts()->....->r.raftTruncatedState()->engine.MVCCGetProto().

If the timer of mn.tickc is initialized as 10ms, the process of mn.tickc will occupy all the time of go routine, because every range group need be processed and persistent storage will be accessed every time.

Please take a look at this problem.

**Comment by bdarnell** [comment]
The biggest part of this issue has been addressed by adding a cache to `raftTruncatedState`. The issue noted in the TODO still stands (even though this code has been moved elsewhere), but the number of ranges required to trigger it is much higher. I'm going to close this with the expectation that we'll open a new issue when our testing and profiling shows the tick loop to be a problem.
