### ISSUE TITLE
kv: investigate brown-out while scaling up under load

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#61005]
**Describe the problem**

It has been reported [here](https://cockroachlabs.slack.com/archives/C0KB9Q03D/p1614090690025400) (internal link) that scaling up under load results in a period of 0 qps.

**To Reproduce**

Try to reproduce this in a roachtest. Apparently this has happened under multiple workloads, so that kv50 seems like a good starting point.

**Expected behavior**

We expect to see a reproduction! QPS dropping to zero for a time is the symptom that was reported.

**Additional data / screenshots**

The slack link above contains a link to recording where this occurs in a customer environment.

The slack thread also mentions a possible connection to https://github.com/cockroachdb/cockroach/issues/37906. This is unsubstantiated (since we're purely scaling up) but it should be kept in mind while investigating. #37904, at the time of writing, is not backported to 20.2 (or rather, it was un-backported due to a subtle bug).

**Environment:**

20.2.x (probably .4)

**Additional context**

**Comment by mikeczabator-doordasher** [comment]
![image](https://user-images.githubusercontent.com/73661528/108870551-3817f280-75c6-11eb-9835-1371c1a1cc57.png)
![image](https://user-images.githubusercontent.com/73661528/108870576-3ea66a00-75c6-11eb-985b-76cf5d2c1f9d.png)
![image](https://user-images.githubusercontent.com/73661528/108870609-436b1e00-75c6-11eb-824d-a619a410ee3a.png)
![image](https://user-images.githubusercontent.com/73661528/108870645-4960ff00-75c6-11eb-9ee4-3184b7a6480c.png)

**Comment by mikeczabator-doordasher** [comment]
link to recording of scaling event (internal link) : https://cockroachlabs.slack.com/files/U0191RCPVNW/F01NYU50RM3/zoom_0.mp4

**Comment by mikeczabator-doordasher** [comment]
I should also note that this is currently running 20.2.5, but we have also seen this behavior in 20.2.3 and 20.2.4.

**Comment by mikeczabator** [comment]
![image](https://user-images.githubusercontent.com/35580719/108895303-6951ec00-75e1-11eb-8a00-e9157ce0641f.png)
![image](https://user-images.githubusercontent.com/35580719/108895349-74a51780-75e1-11eb-9713-3ae4c8a2912e.png)
![image](https://user-images.githubusercontent.com/35580719/108895355-78389e80-75e1-11eb-84f3-933c494dc7df.png)
![image](https://user-images.githubusercontent.com/35580719/108895368-7c64bc00-75e1-11eb-8f5f-b181dc08db63.png)

**Comment by mikeczabator** [comment]
Note, this is occurring in 20.2.5, but we also saw it in 20.2.3 and 20.2.4.

**Comment by mikeczabator** [comment]
More food for thought.  When we scale the cluster up, you see the `Leaseholders per Store` start shuffling all over the place.  Leases immediately start shuffling around across many nodes.  Perhaps this could be correlated as all of this happens so quickly.

![image](https://user-images.githubusercontent.com/35580719/108922182-ada2b380-7604-11eb-9c89-b706a6491cda.png)

**Comment by ajwerner** [comment]
This lease transfer behavior feels intimately related to https://github.com/cockroachdb/cockroach/issues/51867.

**Comment by ajwerner** [comment]
The related PR was not backported to 20.2. I wonder if it would help. I suspect it might.

**Comment by mwang1026** [comment]
closing in favor of https://github.com/cockroachdb/cockroach/issues/67740
