### ISSUE TITLE
Reporting potential performance problems

### ISSUE THREAD

**Issue by jinhojun** [cockroachdb/cockroach#61002]
# Performance issues discovered from differential test

Hello. We are studying DBMS from GeorgiaTech and reporting interesting queries that potentially show performance problems.

To discover such cases, we used the following procedures:

* Install four DBMSs with the latest version (PostgreSQL, SQLite, MySQL, CockroachDB)
* Import TPCC-C benchmark for each DBMS
* Generate random query (and translate the query to handle different dialects)
* Run the query and measure the query execution time
  * Remove `LIMIT` to prevent any non-deterministic behaviors
  * Discard the test case if any DBMS returned an error
  * Some DBMS does not show the actual query execution time. In this case, query the `current time` before and after the actual query, and then we calculate the elapsed time.

In this report, we attached a few queries. We believe that there are many duplicated or false-positive cases. It would be great if we can get feedback about the reported queries. Once we know the root cause of the problem or false positive, we will make a follow-up report after we remove them all.

* Query files:
```sh
wget https://gts3.org/~jjung/report1/cr.tar.gz
```

* Execution result (execution time (second))

| Filename | Postgres |   Mysql  | Cockroachdb |  Sqlite  |   Ratio  |
|---------:|---------:|---------:|------------:|---------:|---------:|
|     1128 |  0.00374 |    0.071 |     1.74702 |    0.006 |   467.62 |
|     3651 |  1.34554 |    1.115 |     4.36074 |    0.805 |     5.42 |
|      868 |  0.05989 |    0.162 |     2.29392 |    0.035 |    65.54 |
|     2196 |  0.01595 |    0.021 |     2.01884 |    0.009 |   224.32 |
|     2889 |  0.00119 |   0.0009 |     2.07283 |    0.001 |  2303.15 |
|      321 |  0.05237 |    0.154 |     1.51231 |    0.027 |    56.01 |
|     4489 |  0.00179 |    0.028 |     2.83246 |    0.009 |  1578.14 |
|     1093 |   0.0228 |    0.078 |     2.69152 |    0.011 |   244.69 |
|     1079 |  0.00357 |    0.193 |     1.69093 |    0.013 |   474.05 |
|     2452 |  0.01166 |    0.306 |     2.61947 |    0.016 |   224.58 |
|      508 |  0.00166 |    0.001 |     1.83182 |    0.029 |  1831.95 |
|      949 |  0.00451 |    0.218 |      2.2885 |    0.022 |   507.19 |
|     3280 |  0.07771 |    0.125 |     8.87185 |    0.013 |   682.45 |
|     1050 |  0.01604 |    0.022 |     2.30498 |     0.01 |   230.50 |
|     3408 |  0.00122 |   0.0009 |     2.38761 |   0.0009 |  2652.90 |
|     2269 |  0.06294 |    0.001 |     2.80169 |    0.032 |  2801.90 |
|      725 |  0.88562 |    1.443 |     3.59864 |    0.426 |     8.45 |
|     1475 |  0.00143 |    0.001 |     2.00642 |    0.239 |  2006.56 |
|     3037 |   0.0175 |    0.027 |     2.65337 |    0.009 |   294.82 |
|     3077 |  0.00152 |    0.001 |      2.3624 |   0.0009 |  2624.88 |
|     2534 |  0.00145 |    0.001 |      1.5344 |    0.001 |  1534.51 |
|     4276 |  0.04515 |    0.026 |     3.19972 |    0.007 |   457.09 |
|     1884 |   0.0189 |   0.0009 |     2.52622 |    0.024 |  2806.91 |
|     4722 |  0.00122 |    0.001 |     1.06432 |   0.0009 |  1182.58 |
|     2725 |  0.25871 |   0.0009 |     1.41153 |    0.249 |  1568.37 |
|     2803 |  0.17569 |    0.318 |     1.38281 |    0.127 |    10.89 |
|     1504 |  0.54594 |    0.771 |      2.3998 |     0.32 |     7.50 |
|     4810 |  0.01245 |   0.0009 |     1.28935 |    1.012 |  1432.62 |
|     4677 |  0.15945 |    0.001 |     1.28426 |     0.12 |  1284.35 |

# Reproduce: install DBMSs, import TPCC benchmark, run query

### Cockroach (from binary)

```sh
# install DBMS
wget https://binaries.cockroachdb.com/cockroach-v20.2.5.linux-amd64.tgz
tar xzvf cockroach-v20.2.5.linux-amd64.tgz
sudo cp -i cockroach-v20.2.5.linux-amd64/cockroach /usr/local/bin/cockroach20

sudo mkdir -p /usr/local/lib/cockroach
sudo cp -i cockroach-v20.2.5.linux-amd64/lib/libgeos.so /usr/local/lib/cockroach/
sudo cp -i cockroach-v20.2.5.linux-amd64/lib/libgeos_c.so /usr/local/lib/cockroach/

# test
which cockroach20
cockroach20 demo

# start the DBMS (to make initial node files)
cockroach20 start-single-node --insecure --store=node20 --listen-addr=localhost:26259 --http-port=28080 --max-sql-memory=1GB --background
# quit
cockroach20 quit --insecure --host=localhost:26259

# import DB
mkdir -p node20/extern
wget https://gts3.org/~jjung/tpcc-perf/tpcc_cr.tar.gz
tar xzvf tpcc_cr.tar.gz
cp tpcc_cr.sql node20/tpcc.sql

# start the DBMS again and createdb
cockroach20 sql --insecure --host=localhost:26259 --execute="CREATE DATABASE IF NOT EXISTS cockroachdb;"
--cockroach20 sql --insecure --host=localhost:26259 --execute="DROP DATABASE cockroachdb;"

cockroach20 sql --insecure --host=localhost:26259 --database=cockroachdb --execute="IMPORT PGDUMP 'nodelocal://self/tpcc.sql';"

# test
cockroach20 sql --insecure --host=localhost:26259 --database=cockroachdb --execute="explain analyze select count(*) from order_line;"

# run query
cockroach20 sql --insecure --host=localhost --port=26259 --database=cockroachdb < query.sql
```

### Mysql (from package manager)

```sh
# install DBMS
sudo apt install mysql-server
sudo mysql_secure_installation

sudo su
mysql
 SHOW VARIABLES LIKE 'validate_password%';
 SET GLOBAL validate_password_length=4;
 SET GLOBAL validate_password_policy = 0;
 CREATE USER 'mysql'@'localhost' IDENTIFIED BY 'mysql';
 alter user 'root'@'localhost' identified by 'mysql';

# modify the conf (should add "skip-grant-tables" under [mysqld])
sudo vim /etc/mysql/mysql.conf.d

# import DB
wget https://gts3.org/~jjung/tpcc-perf/tpcc_my.tar.gz
tar xzvf tpcc_my.tar.gz
mysql -u mysql -pmysql -e "create database mysqldb"
mysql -u mysql -pmysql mysqldb < tpcc_my.sql

# test
mysql -u mysql -pmysql mysqldb -e "show tables"
mysql -u mysql -pmysql mysqldb -e "select * from customer"

# run query
mysql -u mysql -pmysql mysqldb < query.sql
```

### Postgre (from SRC)

```sh
# build latest postgres
git clone https://github.com/postgres/postgres.git
mkdir bld
cd bld
../configure
make -j 20

# install DBMS
sudo su
make install
adduser postgres
rm -rf /usr/local/pgsql/data
mkdir /usr/local/pgsql/data
chown -R postgres /usr/local/pgsql/data
su - postgres
/usr/local/pgsql/bin/initdb -D /usr/local/pgsql/data
/usr/local/pgsql/bin/pg_ctl -D /usr/local/pgsql/data -l logfile start
/usr/local/pgsql/bin/createdb postgresdb
/usr/local/pgsql/bin/psql postgresdb

/usr/local/pgsql/bin/createuser -s {username}
/usr/local/pgsql/bin/createdb {username}
/usr/local/pgsql/bin/psql

=# alter {username} with superuser

# import DB
wget https://gts3.org/~jjung/tpcc-perf/tpcc_pg.tar.gz
tar xzvf tpcc_pg.tar.gz
/usr/local/pgsql/bin/psql -p 5432 -d postgresdb -f tpcc_pg.sql

# test
/usr/local/pgsql/bin/psql -p 5432 -d postgresdb -c "select * from warehouse"

# run query
/usr/local/pgsql/bin/psql -p 5432 -d postgresdb -f query.sql
```

### Sqlite (from SRC)

```sh
# build latest sqlite from src
git clone https://github.com/sqlite/sqlite.git
cd sqlite
mkdir bld
cd bld
../configure
make -j 20

# install DBMS
sudo make install

# import DB
wget https://gts3.org/~jjung/tpcc-perf/tpcc_sq.tar.gz
tar xzvf tpcc_sq.tar.gz

# test
sqlite3 tpcc_sq.db
sqlite> select * from warehouse;

# run query
sqlite3 tpcc_sq.db < query.sql
```

# Evaluation environment

* Server: Ubuntu 18.04 (64bit)
* CockroachDB: v20.2.5
* PostgreSQL: latest commit (21 Feb, 2021)
* MySQL: v5.7.33
* SQLite: latest commit (21 Feb, 2021)

**Comment by ajwerner** [comment]
I wonder if this is a stats or index problem. We should look into this.

**Comment by jordanlewis** [comment]
@cockroachdb/bulk-io - does IMPORT PGDUMP add stats at the end of its run?

@jinhojun, could you try waiting for some time after the import to make sure statistics are collected?

**Comment by dt** [comment]
> @cockroachdb/bulk-io - does IMPORT PGDUMP add stats at the end of its run?

We inform stats that there has been a change to all the rows after import: https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/importccl/import_stmt.go#L1762

**Comment by jinhojun** [comment]
> @cockroachdb/bulk-io - does IMPORT PGDUMP add stats at the end of its run?
> 
> @jinhojun, could you try waiting for some time after the import to make sure statistics are collected?

I did this test two days after the initial data import process.

**Comment by jinhojun** [comment]
It would be great if you can guide us to remove any false positive reports. (e.g., waiting for some time after the import to make sure stats are collected, &c)

**Comment by andreimatei** [comment]
Thanks for the report @jinhojun. It's unclear when anybody here will be able to look at this, but it's on the list.
Perhaps you could check yourself if what you're reporting here meshes with what we report in https://www.cockroachlabs.com/docs/stable/performance-benchmarking-with-tpcc-large.html

**Comment by jinhojun** [comment]
Thanks Andrei, 

It seems the link guides us good way to tune the cockroachDB. We will take a look at the link and re-run all reported queries.

**Comment by rafiss** [comment]
Closing this, but please re-open or feel free to file a new issue if you are able to re-run this with that guidance.
