### ISSUE TITLE
convert Examples in client/db_test.go to regular tests

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#6101]
Peter Mattis said, "We should change all of these Example tests to regular tests. Using examples was useful when this was a public api, but less so now that it is internal. Example-style tests seem to be slower than regular tests."

**Comment by prideloki** [comment]
Hi, @vivekmenezes  i will work on this

**Comment by vivekmenezes** [comment]
Awesome! Thanks for taking it on

**Comment by prideloki** [comment]
@vivekmenezes I have opened the PR in https://github.com/cockroachdb/cockroach/pull/6666

**Comment by vivekmenezes** [comment]
Wow you got a lucky number. Ill take a look tonight

**Comment by seiflotfy** [comment]
Great job @prideloki  :)
LGTM! But I only get to state my opinion!
