### ISSUE TITLE
Migrate old sequences to be referenced by ID

### ISSUE THREAD

**Issue by the-ericwang35** [cockroachdb/cockroach#61017]
**Describe the problem**

Now that new sequences are referenced by ID and thus can be renamed, we want to migrate old (existing) sequences to be the same (stored by ID). 

Jira issue: CRDB-3084

**Comment by postamar** [comment]
@ajwerner we need to rebase Eric's PR and add support for ON UPDATE. This seems to have dropped off our radar, which is unfortunate.

**Comment by ajwerner** [comment]
It's a good issue for early 22.2. Maybe for @Xiang-Gu?

**Comment by ajwerner** [comment]
Relates to https://github.com/cockroachdb/cockroach/issues/60942.

**Comment by Xiang-Gu** [comment]
Credit: my recent PR (#81583) referred @the-ericwang35's PR (#62607).
