### ISSUE TITLE
sql: fill information_schema.columns.is_identity correctly

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#61011]
**Describe the problem**

Currently, `information_schema.columns.is_identity` is hard-coded as `DNull`. Instead, we should fill it correctly with either "yes" or "no" .

**Comment by rafiss** [comment]
I think based on these docs, this column might specifically refer to identity columns as created by this syntax: https://github.com/cockroachdb/cockroach/issues/48532 (which we don't support yet). In which case, maybe we just always return false? We should confirm.

https://www.postgresql.org/docs/current/infoschema-columns.html

**Comment by rafiss** [comment]
Confirmed that in PostgreSQL, only `GENERATED .. AS IDENTITY` columns show true for this:

```
rafiss@127:postgres> create table ts (a serial primary key, b int);
CREATE TABLE

rafiss@127:postgres> create table t_identity (a int generated always as identity, b int);
CREATE TABLE

rafiss@127:postgres> select column_name, is_identity from information_schema.columns where table_name = 'ts';
+---------------+---------------+
| column_name   | is_identity   |
|---------------+---------------|
| a             | NO            |
| b             | NO            |
+---------------+---------------+

rafiss@127:postgres> select column_name, is_identity from information_schema.columns where table_name = 't_identity';
+---------------+---------------+
| column_name   | is_identity   |
|---------------+---------------|
| a             | YES           |
| b             | NO            |
+---------------+---------------+
```

So for now, we should always return false in CockroachDB. Leave a TODO comment in the code with a link to https://github.com/cockroachdb/cockroach/issues/48532
