### ISSUE TITLE
sql/catalog: add namespace validation

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#61010]
**Is your feature request related to a problem? Please describe.**

Descriptor validation does not currently validate the structure of namespace. This leaves room for bugs in the implementation of various schema changes.

**Additional context**

There are short and long-term risks with adding this validation.

A risk are that we uncover old bugs which have left the namespace table in an invalid state which prohibit certain activities. Previous additions of validation have prevented common behaviors like `SHOW TABLES` and `BACKUP` from working until the corruption is resolved (see https://github.com/cockroachdb/cockroach/issues/56810 among others). The addition of `crdb_internal.unsafe_(upsert|delete)_namespace_entry` should help -- but those functions are not perfect. Regardless, they are hard to use and need some expert consultation.

A mitigation to this risk is to find ways to suppress this new validation (or perhaps all validation?) in specific scenarios. There are clear tradeoffs either way on that front. Probably `SHOW TABLES` should remain rather resilient. `BACKUP` is more nuanced. `DROP` is also an interesting case (see https://github.com/cockroachdb/cockroach/issues/50651). How exactly the code interfaces would look for this is also unclear. Two approaches are to utilize sentinal errors and filter them at the appropriate levels or to provide flags to suppress the error that will be terminated at a lower level. The problem with the latter approach is that we aren't principled about our flags or the layers at the present moment. If we wait a bit to refactor that code then that may be a more tenable approach. 

Another consideration is the extra namespace lookups incurring extra round-trips. This can be mitigated with batching the namespace lookups with descriptor lookups. 

One proposal to mitigate the short term risk would be to suppress this additional validation from bubbling up in general in this release and instead have it fire off sentry reports. That approach is not free from the namespace lookup issues.

There is a WIP PR to add this validation [here](https://github.com/cockroachdb/cockroach/pull/61009)

**Comment by ajwerner** [comment]
This also relates to https://github.com/cockroachdb/cockroach/issues/55219 -- if we had namespace validation then we could remove the bespoke validation performed by the doctor code. 

This issue feels like it may involve a namespace corruption: https://github.com/cockroachdb/cockroach/issues/59672

**Comment by jordanlewis** [comment]
Idea here is that we would like to avoid user-bubbled errors here and prefer to log/sentry these issues.
