### ISSUE TITLE
Database console graphs reload constantly when scrolling

### ISSUE THREAD

**Issue by mikeczabator** [cockroachdb/cockroach#61021]
DBConsole graphs refresh constantly when scrolling.  See the attached video.  This occurs on 20.2.5.  

https://cockroachlabs.slack.com/files/U0191RCPVNW/F01P82635LL/screen_recording_2021-02-23_at_10.20.42_am.mov

Epic CC-5280

Jira issue: CRDB-3083

**Comment by dhartunian** [comment]
Possibly related to https://github.com/cockroachdb/cockroach/issues/48445
