### ISSUE TITLE
kvserver: allow forced replicaGC without tombstone as recovery tool

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#61055]
**Is your feature request related to a problem? Please describe.**
Currently a replica is only removed as a result of replicaGC (or observing a newer MinReplicaID). As part of this removal, a tombstone is written that prevents the replica from being recreated.

It turns out that it can be useful to remove a replica in-place without writing that tombstone and without carrying out a replication change:

1. If a replica is corrupted, today we crash the node. Instead, we could forcibly replicaGC that replica in-place, i.e. make it disappear. (We take an LSM snapshot, so the debug data remains available).
2. If a replica is stuck for reasons that are difficult to fix (see https://github.com/cockroachdb/cockroach/issues/60612 for an example of that), forced replicaGC can help. For example, in the linked issue above, we were dealing with large uncommitted raft log tails that were probed very slowly. We could have replicaGC'ed the follower replicas one by one, which would have resulted in them being repopulated from a Raft snapshot which contains no raft log and thus wouldn't have required probing.

Note that this endpoint could cause loss of data since it removes committed commands. However, as long as at least one up-to-date replica survives, no actual data loss would occur, as the replicas are available (can vote and can be caught up via a snapshot from the survivor).

**Describe the solution you'd like**
Add a debug endpoint that allows carrying out the operation above.

**Describe alternatives you've considered**
Not doing this!

**Additional context**

Jira issue: CRDB-6282

**Comment by lunevalex** [comment]
cc: @itsbilal
