### ISSUE TITLE
Scope job status 

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#61080]
Currently in SHOW JOBS we show changefeeds as running even when they are not running due to an error+restart. We should surface a "restarting due to error" status to make it clear when this is occuring.

Scope: look into what is feasible here, can we do something similar to the "last error" in the SHOW SCHEDULES table?

**Comment by miretskiy** [comment]
For the stability period, we will only record/update job running status.
Further enhancement in terms of observability will have to happen in the upcoming release.
