### ISSUE TITLE
cli: sql does not render second select in single-stmt txn

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#61114]
**Describe the problem**

psql (run against same CRDB demo instance as below):

```
demo=> begin;select 1; select * from (select 1 as foo) where foo = 2;commit
BEGIN
 ?column? 
----------
        1
(1 row)

 foo 
-----
(0 rows)
```

crdb:

```
$ ./cockroach demo -e "begin;select 1; select * from (select 1 as foo) where foo = 2;commit"  ?column?
------------
         1
(1 row)

COMMIT
```

**To Reproduce**

`./cockroach demo` on master

**Expected behavior**

I was expecting the `./cockroach demo -e` invocation to also render a zero-row result for the second select.

**Additional data / screenshots**

Removing the begin and commit fixes it:

```
$ ./cockroach demo -e "select 1; select * from (select 1 as foo) where foo = 2"
  ?column?
------------
         1
(1 row)

Time: 0ms

  foo
-------
(0 rows)

Time: 1ms
```

Leaving the txn in but making the second query return a result fixes it:

```
$ ./cockroach demo -e "begin;select 1; select * from (select 1 as foo) where foo = 1;commit;"  ?column?
------------
         1
(1 row)

  foo
-------
    1
(1 row)
```

Removing the first query fixes it:

```
$ ./cockroach demo -e "begin; select * from (select 1 as foo) where foo = 2;commit;"
  foo
-------
(0 rows)
```

Opening the txn separately does *not* fix it. Opening the txn & running the first select and then running the rest separately *does* fix it.

My reading from all of this is that when in an explicitly opened txn, a multi-select stmt will erroneously omit rendering an empty result set for all but the first query.

**Environment:**
master at time of issue creation

**Additional context**
I was confused :-)

Jira issue: CRDB-6281

**Comment by knz** [comment]
cc @rafiss for triage

**Comment by knz** [comment]
might be worth trying with `psql` too to compare -- if the same occurs with psql the problem may be inside pgwire.

**Comment by tbg** [comment]
See the post, it does confirm that the issue is not present with psql.

**Comment by knz** [comment]
My apologies for not paying enough attention

**Comment by rafiss** [comment]
I think it could be the same as https://github.com/cockroachdb/cockroach/issues/55234
