### ISSUE TITLE
Show cluster settings with non-default values

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/cockroach#61142]
When we're debugging "legacy" clusters that date back to the 2.X or 19.X releases, we sometimes encounter cases where the default values of cluster settings in newer releases have been changed from previous releases.  It would be nice to have a way to show cluster settings that are set to non-default values.

Something along the lines of `SHOW [ALL] ALTERED CLUSTER SETTINGS` to show both the default and effective value for the non-default settings.

**Comment by knz** [comment]
gotcha! This issue is actually a dup of #59673 which we have on the radar.

FYI you can already get an idea of what was customized by looking at the system table `system.settings`.
