### ISSUE TITLE
sql: support IntervalStyle session parameter

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#61167]
We should add support for the IntervalStyle session parameter, which describes how an `interval` type is formatted in output.

See official docs here: https://www.postgresql.org/docs/9.4/datatype-datetime.html#INTERVAL-STYLE-OUTPUT-TABLE
See a tutorial here: https://www.postgresqltutorial.com/postgresql-interval/

Epic CRDB-2508

**Comment by mneverov** [comment]
hi, i'd like to work on this
