### ISSUE TITLE
Some old tables that never get garbage collected 

### ISSUE THREAD

**Issue by HeavyHorst** [cockroachdb/cockroach#61188]
**Describe the problem**

I have some old tables that never gets garbage collected.

This doesn’t seem to be a real problem as everything works wonderfully and I have never experienced such a problem since then. Nevertheless, I would like to remove them if it is possible.

Also see: https://forum.cockroachlabs.com/t/some-old-tables-that-never-get-garbage-collected/4302

**To Reproduce**

I don't know because it only happened once.
I already had some consinstency problems at that time: 
#51983, #52422

possibly it is related to one of these problems.
**Expected behavior**

The tables should be garbage collected and dissapear.

**Additional data / screenshots**

![Bildschirmfoto von 2021-02-26 14-13-13](https://user-images.githubusercontent.com/16866547/109314953-41b18c80-784a-11eb-8c10-115f83402abd.png)

I've already created the debug.zip.
What is the preferred way to transfer it privately?

Jira issue: CRDB-3053

**Comment by ajwerner** [comment]
> I don't know because it only happened once.
> I already had some consinstency problems at that time:
> #51983, #52422

If this is the same cluster as those, I'm not totally surprised to hear that we've got some cleanup to do. Please share the debug zip with `ajwerner@cockroachlabs.com` via either email or google drive if that's convenient. If it is not convenient, I'm sure I can work out a private upload link to give you out of band. Email me either way.

**Comment by HeavyHorst** [comment]
I shared the file with gdrive.

**Comment by ajwerner** [comment]
One question: how willing are you to upgrade to 20.2? We have added tools in 20.2 to make repair much more robust and much simpler - it can be done in sql without the need for some low level hacks. It's possible in 20.1, but certainly less pleasant.

**Comment by HeavyHorst** [comment]
That sounds great.
I am running 20.2.5 already.

**Comment by ajwerner** [comment]
Cool, I'll cook something up. Out of curiosity, does SHOW TABLES work or does it currently give you an error?

**Comment by HeavyHorst** [comment]
SHOW TABLES works on all databases SHOW DATABASES shows.

**Comment by ajwerner** [comment]
We added functions to remove these tables and their data with `crdb_internal.unsafe_delete_descriptor` and `crdb_internal. force_delete_table_data`. Sorry I didn't deal with this in a more timely manner.

**Comment by HeavyHorst** [comment]
Great news, thank you very much! 
Is there any documentation on how to run these commands?
