### ISSUE TITLE
AdminUI: Statements page doesn't load - js error

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#61196]
On master (#9902ea9c2e), the Statements page doesn't load and says the following

![Screenshot from 2021-02-26 12-55-10](https://user-images.githubusercontent.com/377201/109336866-fdb28d80-7831-11eb-853c-8cfa8f54e3bb.png)

**Comment by nkodali** [comment]
https://github.com/cockroachdb/cockroach/pull/61177 has been merged so this should be resolved now. Closing.
