### ISSUE TITLE
backupccl: make BACKUPs more defensive on stats collection failures

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#61199]
We should not be failing the BACKUP if we run into an error computing table stats right at the end of job execution. More likely than not, the customer would like their data to be backed up, and are okay with an expensive stats recomputation on RESTORE. We should log a warning instead.

**Comment by shermanCRL** [comment]
Agree that the default behavior should be to continue on failure of ‘optional’ data like stats -- with logging of course.

Is there such thing as ‘partial’ stats? If a particular stat fails, can we restore other stats?
