### ISSUE TITLE
Rewrite sequence expressions in views

### ISSUE THREAD

**Issue by the-ericwang35** [cockroachdb/cockroach#61205]
**Describe the problem**
After https://github.com/cockroachdb/cockroach/pull/59864, we're now rewriting DEFAULT expressions to reference sequences via their IDs. This results in the ability for sequences used in default expressions to be renamed. However, we don't perform this rewrite for views that reference sequences. As a result, we still cannot rename sequences used in views.

**To Reproduce**

```
CREATE SEQUENCE s;
CREATE VIEW v AS SELECT nextval('s');
ALTER SEQUENCE s RENAME TO s2;  // ERROR: cannot rename relation "s" because view "v" depends on it
```

**Expected behavior**
We should rewrite sequence expressions in views to also reference sequences by ID. This will allow us to rename sequences that are used in views.

**Comment by ajwerner** [comment]
Must precede #61017.
