### ISSUE TITLE
sql: ::regtype casts don't work for user defined types

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#61216]
Currently, trying to cast from a type id to a type name via `::regtype` does not work if the type is user-defined.

Repro:

```
demo@127.0.0.1:26257/defaultdb> create type t as enum('a', 'b');
CREATE TYPE

Time: 6ms total (execution 6ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> select oid::regtype from pg_type where typname = 't';
   oid
----------
  100052
(1 row)

Time: 5ms total (execution 4ms / network 0ms)

demo@127.0.0.1:26257/defaultdb>
```

This should return `t`, not `100052`.

**Comment by ajwerner** [comment]
Yeah first this should behave like regclass and tables. Then we should make both of them behave more like postgres (namely with regards to going from the int back to the string).

**Comment by jordanlewis** [comment]
What do you mean by behave more like postgres here? We implement the bidirectional thing correctly here in all cases except for UDTs.

**Comment by ajwerner** [comment]
cockroach:
```
andrew@free-tier.gcp-us-central1.crdb.io:26257/test> SELECT 't'::regclass,  't'::regclass::int, 65::regclass, 65::regclass::string;
  regclass | int8 | regclass | text
-----------+------+----------+-------
  t        |   65 | t        | t
(1 row)
```
postgres:
![Screenshot 2021-02-26 at 7 35 01 PM](https://user-images.githubusercontent.com/1839234/109369349-07f07e00-786a-11eb-99da-5598c6a25a86.png)

Yes, I am using both of our serverless products.

**Comment by ajwerner** [comment]
It is very close:

cockroach:
```
andrew@free-tier.gcp-us-central1.crdb.io:26257/test> SELECT 't'::regclass,  't'::regclass::int, 65::regclass, 65::regclass::string;
  regclass | int8 | regclass | text
-----------+------+----------+-------
  t        |   65 | t        | t
(1 row)
```
postgres:
![Screenshot 2021-02-26 at 7 35 01 PM](https://user-images.githubusercontent.com/1839234/109369349-07f07e00-786a-11eb-99da-5598c6a25a86.png)

now for where they differ:
```
andrew@free-tier.gcp-us-central1.crdb.io:26257/test> SELECT 65::regclass::string;
  text
--------
  65

andrew@free-tier.gcp-us-central1.crdb.io:26257/test> SELECT 65::regclass;
  text
--------
  65
```
Where postgres would give me `t` for both of these.

----

Yes, I am using both of our serverless products.

**Comment by jordanlewis** [comment]
If you do 65::oid::regclass it works properly. This will be closed by #61211 thanks to @rafiss noticing an issue with code duplication.

**Comment by rafiss** [comment]
related to https://github.com/cockroachdb/cockroach/issues/60008

**Comment by rafiss** [comment]
I created https://github.com/cockroachdb/cockroach/issues/62205 to track the `int::regclass` issue
