### ISSUE TITLE
sql: privileges for DROP database

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#6122]
To drop a database, a user currently needs the `DROP` privilege on both the database and all included tables. Is this intentional? It seems like having `DROP` on the db would suffice. 

I'm not sure what's conventional here. Postgres doesn't have a `DROP` privilege. Rather, their docs say:

"The right to drop an object, or to alter its definition in any way, is not treated as a grantable privilege; it is inherent in the owner, and cannot be granted or revoked."

**Example:**

Connect as root user, create a database, create a table, grant drop privilege on db to the jseldess user.

```
./cockroach sql
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.

root@:26257> create database todrop;
CREATE DATABASE

root@:26257> create table todrop.todrop (a int);
CREATE TABLE

root@:26257> grant drop on database todrop to jseldess;
GRANT
```

Connect as the jseldess user and try to drop the database.

```
JESSEs-MacBook-Pro:cockroach jesseseldess$ ./cockroach sql --user=jseldess
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.

jseldess@:26257> drop database todrop;
pq: user jseldess does not have DROP privilege on table todrop
```

**Comment by mberhault** [comment]
our implementation of `DROP DATABASE <db>` internally calls `DROP <table>` on every table, so that triggers the table checks.
I'm in favor of keeping this behavior since `DROP DATABASE` is such a heavy-handed operation. However, I could be convinced to change it.

**Comment by jseldess** [comment]
I agree that it does make it harder to drop a whole database, which may be a good thing. For now, I'll just make sure the docs explain that drop is required at both levels. 

If we stick with the current behavior, though, we might want to update the comment here to mention that drop on table is also required: https://github.com/cockroachdb/cockroach/blob/master/sql/drop.go#L29

**Comment by knz** [comment]
@jseldess once #12777 is merged, should we keep this issue open? It seems to me that if the permissions are properly documented then this "works as expected" until a user requests otherwise.

**Comment by jseldess** [comment]
Yep, @knz, feel free to close this. The `DROP DATABASE` docs already say that the user must have `DROP` on the db and all tables in the db.
