### ISSUE TITLE
sql/ui: statements page doesn't load 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#61252]
The statements page doesn't load on master:
https://drive.google.com/file/d/1l4i1ynt-hbQxD8NdQTlB5Af3jf5OYXfb/view?usp=sharing

To repro:
Build from master
```./cockroach demo movr --nodes 9```

CockroachDB CCL v21.1.0-alpha.3-940-gfdadd514b5

**Comment by asubiotto** [comment]
Looking into it

**Comment by asubiotto** [comment]
https://github.com/cockroachdb/cockroach/pull/61177 should fix this

**Comment by awoods187** [comment]
Confirmed https://github.com/cockroachdb/cockroach/pull/61177 fixes this.
