### ISSUE TITLE
Include tar in Docker container release build so that kubectl cp will work.

### ISSUE THREAD

**Issue by lancel66** [cockroachdb/cockroach#61273]
**Is your feature request related to a problem? Please describe.**
Include tar in Docker container release build so that kubectl cp will work. Currently, a custom Docker container needs to be built which takes extra cycles.

**Describe the solution you'd like**
Include tar in Docker container release build so that kubectl cp will work.

**Describe alternatives you've considered**
Build custom Docker container.

gz#7711

**Comment by jlinder** [comment]
Hi @lancel66 , thanks for this request. We already had the fix for this on the master branch. I've opened a backport PR (https://github.com/cockroachdb/cockroach/pull/61403) for the 20.2 release series.

**Comment by jlinder** [comment]
Hi @lancel66, following up on the PR. It has been merged and the next 20.2 version (v20.2.6) will contain the fix.

**Comment by andreimatei** [comment]
@jlinder we can close, right?
