### ISSUE TITLE
sql/catalog: error validation can silently swallow meaningful transaction errors

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#61303]
**Describe the problem**
In https://github.com/cockroachdb/cockroach/pull/60775 we added logic to allow descriptor validation to report a collection of errors. Unfortunately this change has the side-effect that if an error which was reported is in fact due to a transaction problem, then it may be swallowed. In practice this may well not be a big deal because if some other error got reported then probably the whole transaction should get torn down. Furthermore, after you hit a retry error, it seems like subsequent read operations on that transaction don't see any problems. I'm sure that swallowing the restart error violates some contract somewhere. What would it even mean to have two of them!?!

**Proposed Solution**

The errors we want to collect are errors we know are created right there (or at least we know are not created in a context where an RPC error may actually occur, thing `partitionccl` validation). Given that, I think we should, in addition to keeping our error accumulator, add an error return which is for errors fetching things like descriptors. 

**Additional context**

In a slightly more distant future, perhaps we could unhook the validating of the structure of a descriptor relative to its direct associations and instead flip that script such that we fetch everything, hook it up, and then do structural validation. Some of that is discussed in the `Additional Context` section of https://github.com/cockroachdb/cockroach/issues/61302. That feels not immediately actionable.

This issue motivated https://github.com/cockroachdb/errors/issues/62.

**Comment by knz** [comment]
I responded on the linked issue. You need something different from `CombineErrors` that is crdb-specific.
