### ISSUE TITLE
execinfra: check whether planned follower reads are mistakenly counted as misplanned ranges

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#61313]
In #61244 Nathan made the following observation:
```
This code is also making me wonder: do we count DistSQL flows that are
intentionally planned on followers to execute follower reads using the
ClosestOracle as "misplanned"?
```
and upon quick code inspection I think that we mistakenly count planned follower reads as misplanned ranges. We should look into this and fix it if that's the case.

Jira issue: CRDB-3040

**Comment by michae2** [comment]
Here is the plan that @andreimatei suggested to me: instead of setting `tableReader.ignoreMisplannedRanges` for planned follower reads, add a set of `ClientRangeInfo` to the `TableReaderSpec` and use this to decide whether to add each range cache entry to the `misplannedRanges` list. This should roughly match `maybeAddRangeInfoToResponse` and should fix the follower read case as well as more edge cases with partially-stale range info.

**Comment by tbg** [comment]
We also saw something possibly related when running tpc-e against 22.2, full thread [here](https://cockroachlabs.slack.com/archives/C04QZ9Z1QR1/p1681369702103659). Not many follower reads there.

Nathan says:

> I think I saw something like this before during the TPC-E scale test, but there was so much else going wrong that I never fully pinned this part down. It had to do with false positives in execinfra.MisplannedRanges. DistSQL would consider a flow to have been misplanned in cases where it was not. When it did, it would ship new descriptors back to the gateway node and cause this kind of range cache churn. I think it may have had to do with memory and key limited scans, but I can’t recall. We are tracking a related issue about follower reads (https://github.com/cockroachdb/cockroach/issues/61313), but this cluster is running very few follower reads. This feels worthwhile to dig into while we’re hitting it.

![image](https://user-images.githubusercontent.com/5076964/231809846-b57ebd57-7315-4892-897d-08d3230ff350.png)

**Comment by yuzefovich** [comment]
I believe the range cache churn we observed on the test cluster when running TPCE was different (#101471) and has already been addressed. I'll remove the O-testcluster label.
