### ISSUE TITLE
sql/ui: add tooltips to new statement/transaction pages in DB Console

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#61346]
This issue tracks adding tooltips to the new statement/transaction pages. These are outlined in @Annebirzin's figma design.

**Comment by Annebirzin** [comment]
Adding the figma link to the tooltips here: https://www.figma.com/file/MoSPFkEyJfGipCmQvvLg1a/obsrv-query-performance?node-id=1834%3A2895 

Also, I mentioned it in issue https://github.com/cockroachdb/cockroach/issues/61343, but wanted to call out that ideally these tooltips will include the '?' component (tooltip would only appear when hovering over ‘?’ icon, not on column header text)

For reference, we currently use this '?' tooltip component in CockroachCloud in the Connect modal next to the 'Region' label
![Screen Shot 2021-03-02 at 1 57 23 PM](https://user-images.githubusercontent.com/51920721/109700652-096ac080-7b60-11eb-90dd-37c35029ebdc.png)

**Comment by tharun208** [comment]
@asubiotto , I can pick this up

**Comment by asubiotto** [comment]
Looks like extracting the "?" component is non-trivial so we'll do a first pass by just updating the current tooltips (show info on hover).
