### ISSUE TITLE
sql/ui: DB Console UI fixes

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#61343]
The new DB Console pages need some UI love. Here are some things @awoods187 has noticed:
- [ ] Statement detail - page width and layout needs adjustment
- [ ] Transaction detail sql panel should be a fixed height
- [ ] Statement and Transaction list views (general table updates)
- [ ] Diagnostic Column Doesn’t line up with other columns

@awoods187, would you mind providing screenshots of each of these points so that it's clear what exactly is unexpected?

Jira issue: CRDB-3033

**Comment by Annebirzin** [comment]
@asubiotto I see that you have a task for 'Transaction detail sql panel should be a fixed height' and I just wanted to note this should also apply to the statement details page

Also, here are screenshots and additional notes for these issues from the [acceptance testing doc](https://docs.google.com/document/d/1FD1wByGTqB_r2FrH_dSbxCqQtqzUjsKGwLZtIP0TQEA/edit#)

**1. Statement detail - page width and layout needs adjustment**

- The sql panel and stats panels should expand the width of the page (as long as the tab bar divider line)
- Statement time and Resource usage panels can be 2x wider than statement details panel
- SQL panel should be a fixed height (~185px) and scroll within panel if content is longer

production
![Screen Shot 2021-03-02 at 1 04 25 PM](https://user-images.githubusercontent.com/51920721/109698334-4e412800-7b5d-11eb-8fe4-3088480894bb.png)

designs
![Screen Shot 2021-03-02 at 1 04 36 PM](https://user-images.githubusercontent.com/51920721/109698348-50a38200-7b5d-11eb-8473-e28fcda344e3.png)

**2.  Transaction *and statement* detail sql panel should be a fixed height**

- statement sql panel should be around 185px height
- txn sql panel should be around 300 px (same height as resource usage panel to the right of it)

![Screen Shot 2021-03-02 at 1 46 50 PM](https://user-images.githubusercontent.com/51920721/109698791-c871ac80-7b5d-11eb-9761-ac4d53d73f23.png)

**3.  Statement and Transaction list views (general table updates)**

- Column shifting is still an issue when sorting table data (statement/txn SQL changes width of column). The Statements/txn SQL column should be a fixed width 
![column_shifting](https://user-images.githubusercontent.com/51920721/109698969-fc4cd200-7b5d-11eb-96da-70f5f5f48eec.gif)

- Tooltips are distracting when trying to sort columns. Introduce ‘?’ icon for tooltips in column headers 
(tooltip would only appear when hovering over ‘?’  icon, not on column header text)
![Screen Shot 2021-03-02 at 1 48 59 PM](https://user-images.githubusercontent.com/51920721/109699088-20101800-7b5e-11eb-8846-f483105db3ac.png)

*note: we currently use this '?' tooltip component in CockroachCloud in the Connect modal next to the 'Region' label
![Screen Shot 2021-03-02 at 12 41 27 PM](https://user-images.githubusercontent.com/51920721/109699170-3cac5000-7b5e-11eb-8591-431bf64b44e4.png)


**4.  Diagnostic Column Doesn’t line up with other columns**
-  Looks like the table bleeds outside the white background causing a mis-alignment  in white background 
![Screen Shot 2021-03-02 at 1 51 35 PM](https://user-images.githubusercontent.com/51920721/109699320-6c5b5800-7b5e-11eb-8ada-054ce900d3f2.png)

**Comment by asubiotto** [comment]
Thanks!
