### ISSUE TITLE
sql: add time series metrics for disk spilling

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#61363]
We currently lack some metrics for disk spilling. Add the following metrics:

1. A counter that tracks the number of times queries have spilled to disk
2. A counter that tracks the number of bytes written to temporary disk storage as a result of spilling
3. A counter that tracks the number of bytes read from temporary disk storage as a result of spilling

**Comment by asubiotto** [comment]
cc @yuzefovich

**Comment by barryhe2000** [comment]
cc @asubiotto @jordanlewis @awoods187 

For metric 1, do we want to allow for a query to add towards the number of times spilled to disk more than once (i.e. if a query uses 2 external sort operators, that would mean 2 separate occasions of spilling to disk, do we add 1 or 2 in this case)?

For metric 2, does the CurDiskBytesCount field in execinfra/metrics.go already account for this?

For metric 3, what do we think of the relevancy of this metric/are there good user use cases? Also if 2 is already implemented (through CurDiskBytesCount), it seems that 3 would be done through a file system approach in diskqueue.go, and I'm wondering if that would result in confusing/different numbers than expected. In general should the number of bytes read from temp disk be similar to bytes written?

**Comment by awoods187** [comment]
For metric 1 I think counting the query twice is incorrect but we should count the total bytes/written read each time a query spills to disk.

**Comment by asubiotto** [comment]
Agree with @awoods187 re metric 1, a query should only count once.

For metric 2, I believe `CurDiskBytesCount` actually already does this cc @yuzefovich 

For metric 3, I'd like to also get a deeper explanation as to why we think it's useful. All bytes written are read.

**Comment by yuzefovich** [comment]
For metric 1, I was thinking there might be some utility in incrementing a counter every time the spilling occurs (in addition to a separate counter incremented once per query), but implementing only the latter sounds good to me too.

For metric 3, the only case when "bytes read" is different from "bytes written" that I can think of is the query has a LIMIT, yet it required to spill to disk. I agree that having metric 3 doesn't seem that useful to me.

**Comment by jordanlewis** [comment]
Metric 1: I disagree that it's boolean. The value should be equal to the number of times the query spilled. This is more information without being more confusing - 0 is the good case, and anything else is bad, and the higher it gets the worse it is. In the UI, we can always turn it into a boolean if we want to later.

Metric 2: `CurDiskBytesCount` does not account for this. That tracks the *current* byte count stored on disk. This number might go down. To produce the correct value, you need to have a metric that is monotonically increasing.

Metric 3: It might seem like it's mostly the same, but I think it's important to track nonetheless, because it's important to have a holistic picture of bytes read and written for every query.

**Comment by asubiotto** [comment]
> Metric 2: `CurDiskBytesCount` does not account for this. That tracks the _current_ byte count stored on disk. This number might go down. To produce the correct value, you need to have a metric that is monotonically increasing.

You're right. `MaxDiskBytesHist` does track the high watermark but I struggle to see how it's useful for this case. We should probably introduce a count alongside the cur disk bytes gauge that doesn't get decremented. I guess the usefulness of this will be seeing the average count over a rolling period?

**Comment by barryhe2000** [comment]
Following today's discussion after the weekly meeting, metric 1 will be treated as boolean and will be a counter tracking if the query spilled or not, and will not double count for multiple spills in one query.
