### ISSUE TITLE
sql: rename SHOW CREATE ALL TABLES to DUMP OBJECTS FROM DATABASE

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#61369]
After some discussion with @vy-ton the plan is to rename `SHOW CREATE ALL TABLES` to `DUMP OBJECTS FROM database`

Some followup work open for discussion is, should we include user defined schemas to `DUMP OBJECTS FROM database`

If UDS are not considered an object, we can create a similar command `DUMP DATABASE` to dump schemas/relations/udts

**Comment by rafiss** [comment]
We've decided to leave the name as is for now. The name can be changed in 21.2 if we do add support for other objects in this command.
