### ISSUE TITLE
"ERROR: command is too large" message on UPDATE statements

### ISSUE THREAD

**Issue by jhatcher9999** [cockroachdb/cockroach#61385]
**Describe the problem**
When updating a table with a value that is larger than `kv.raft.command.max_size`, an error is thrown (for example: `ERROR: command is too large: 4194398 bytes (max: 4194304)`) instead of streaming/paginating the results.

**To Reproduce**
```SQL
CREATE TABLE source ( id INT, clob TEXT, PRIMARY KEY ( id ) );
CREATE TABLE dest ( id INT, clob TEXT, PRIMARY KEY ( id ) );
INSERT INTO source ( id, clob ) VALUES ( 1, '' );
INSERT INTO dest ( id, clob ) VALUES ( 1, '' );

--minimum is 4.0MiB, so let's set it a little bigger so we can create our source data
--if you don't do this, you hit the same error just trying to setup the source data
SET CLUSTER SETTING kv.raft.command.max_size = '5MiB';

UPDATE source SET clob = REPEAT('x', 4194304) WHERE id = 1;	

--set this to the minimum (4.0MiB) so we can repro the issue
SET CLUSTER SETTING kv.raft.command.max_size = '4MiB';

UPDATE dest
SET clob = s.clob
FROM dest d
INNER JOIN source s
ON d.id = s.id
WHERE 1 = 1;
```
This will return the following error:
```SQL
ERROR: command is too large: 4194398 bytes (max: 4194304)
```

**Expected behavior**
According to similar issues (https://github.com/cockroachdb/cockroach/issues/51391), I believe that CockroachDB should paginate through the update stream at `maxUpsertBatchSize`

**Additional data / screenshots**
**Environment:**
 - Cockroach 20.2.5
 - Server OS: macOS
 - Client app `cockroach sql`

**Additional context**

**Comment by yuzefovich** [comment]
I believe this is the expected behavior. The pagination only kicks in to have a "window" between multiple rows; however, in this example we're building a single huge row. There is no pagination at SQL layer (and probably in KV too, thus, the error) for such cases.
