### ISSUE TITLE
Bazel build requires you to have `autoconf`, `make`, etc. installed and in your `PATH`

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#61405]
This is particularly troublesome on systems where Bash isn't the default shell and there's a distinction between the `~/*_profile` of the different shells, e.g. https://cockroachlabs.slack.com/archives/C019A8NANH0/p1614781808025700

This is unlikely to change in the near future, so we should wherever possible make the user experience seamless here (maybe add a `dev doctor` to automatically detect this and recommend a fix?)

**Comment by jlinder** [comment]
This is fixed.
