### ISSUE TITLE
Pebble performance with v20.2.5 

### ISSUE THREAD

**Issue by harchu** [cockroachdb/cockroach#61436]
**Describe the problem**

We observed some performance issues when running load tests against the new cockroachdb cluster on version 20.2.5 using the default pebble storage engine. 

**To Reproduce**

1. Set up 2 separate CockroachDB clusters running in AWS on 6 c5d.xlarge nodes (each) - one on v20.2.5 with the default pebble storage engine and the other on v20.1.3 with the default rocksdb storage engine.
2. Run cockroach kv workload against both the clusters
```
cockroach workload init kv $COCKROACH_URL --splits 12
cockroach workload run kv $COCKROACH_URL --read-percent 0 --concurrency 8 --duration 120s
cockroach workload run kv $COCKROACH_URL --read-percent 0 --concurrency 512 --duration 120s
```

**Expected behavior**
Similar or better performance on v20.2.5

**Additional data / screenshots**
`
cockroach workload run kv $COCKROACH_URL --read-percent 0 --concurrency 8 --duration 120s`

v20.2.5 with pebble (concurrency 8)
```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
  600.0s        0        1891875         3153.1      2.5      2.4      4.1      7.6    218.1
```
v20.2.5 with pebble (concurrency 512)
```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
  600.0s        0       10554510        17590.8     29.1     22.0     79.7    113.2    402.7
```
v20.1.3 with rocksdb (concurrency 8)
```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
  600.0s        0        2102160         3503.6      2.3      2.2      3.4      4.7     75.5
```
v20.1.3 with rocksdb (concurrency 512)
```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
  600.0s        0       14655784        24426.2     21.0     15.2     58.7     92.3    302.0
```
I can provide more metrics if required. But i did notice higher disk write ops on the latest version compared to v20.1.3. Is there any tuning we can do to achieve on-par results?

v20.1.3 (concurrency 512)
<img width="970" alt="v20 1 3-512" src="https://user-images.githubusercontent.com/794381/109885985-430cfb80-7c34-11eb-9310-4f7ee7d0c629.png">

v20.2.5 (concurrency 512)
<img width="968" alt="v20 2 5-512" src="https://user-images.githubusercontent.com/794381/109885976-40aaa180-7c34-11eb-9966-e53395d4babe.png">

**Comment by andreimatei** [comment]
@sumeerbhola are you surprised?

**Comment by sumeerbhola** [comment]
> @sumeerbhola are you surprised?

yes. @itsbilal is planning to investigate

**Comment by itsbilal** [comment]
Looked into this in detail. The short summary of the difference is that RocksDB is more write-friendly in that it prefers to compact less during this workload, while Pebble tries to compact more aggressively. Compactions help improve read performance, so versions of the kv workload that have a majority or high `--read-percentage`, such as `--read-percentage 95`, tend to do better on Pebble.

Here's a benchstat comparison of the kv workload with 3 nodes,  `--read-percentage=95`, on 3 c5d.4xlarges. Old is RocksDB on 20.2, new is Pebble:

```
name                    old ops/sec  new ops/sec  delta
kv95/enc=false/nodes=3   43.3k ± 4%   45.6k ± 6%  +5.26%  (p=0.000 n=14+15)

name                    old p50      new p50      delta
kv95/enc=false/nodes=3    3.19 ± 7%    3.01 ± 4%  -5.44%  (p=0.000 n=15+15)

name                    old p95      new p95      delta
kv95/enc=false/nodes=3    14.6 ±10%    14.0 ± 5%  -4.11%  (p=0.003 n=15+13)

name                    old p99      new p99      delta
kv95/enc=false/nodes=3    23.8 ± 8%    23.2 ± 5%  -2.84%  (p=0.030 n=15+13)
```

As you can see, Pebble slightly edges out RocksDB above. The story is reversed when `--read-percentage=0` but everything else is the same:

```
name                   old ops/sec  new ops/sec  delta
kv0/enc=false/nodes=3   21.6k ± 3%   20.0k ± 6%   -7.35%  (p=0.008 n=5+5)

name                   old p50      new p50      delta
kv0/enc=false/nodes=3    6.30 ± 5%    7.54 ± 5%  +19.68%  (p=0.008 n=5+5)

name                   old p95      new p95      delta
kv0/enc=false/nodes=3    25.6 ± 2%    27.3 ± 8%   +6.56%  (p=0.048 n=5+5)

name                   old p99      new p99      delta
kv0/enc=false/nodes=3    37.7 ± 0%    37.7 ± 0%     ~     (all equal)
```

The other thing to note is that the balance falls even further in Pebble's favour when the values are larger. I set `--min-block-bytes` and `--max-block-bytes` to 128kb and noticed that Pebble started edging out RocksDB at `--read-percentage=50` too, in addition to at `--read-percentage=95` where pebble is always faster. The default value size is just 1 byte, which is too small to really fill up the LSM or to surface benefits of a more compact LSM.

Given Cockroach is a general-purpose db that needs to serve workloads with all combinations of reads and writes, I'm sufficiently satisfied to see that Pebble is performing better on mixed workloads. We could discuss ways in which we could slow down / pace or score compactions differently if a workload is just writes, but at least there isn't a major 20.1 -> 20.2 regression at hand over here. I'll also mention that TPC-C, which is a pretty mixed, SQL-heavy workload, tends to perform better on 20.2 with pebble than on 20.1 with rocksdb or even 20.2 with rocksdb.

I also looked into some of the manifests from these runs, and nothing stood out to me as obviously inefficient in either engine's state(s) at any point.
