### ISSUE TITLE
opt: index accelerate JSON filters in the form j->'a' @> '1'

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#61430]
It should be possible to use an inverted index to satisfy a query filter in the form `j->'a' @> '1'`. Ideally, we can index accelerate these filters when the right-side of the `@>` operator is a boolean, string, number, array, or object.

**Comment by angelazxu** [comment]
Helloo @mgartner, probably going to take on this issue next so I want to clarify a couple things :)
- Besides booleans, strings, numbers, arrays, or objects being on the right side, will we also support nulls? Not sure it's just not listed or if you had a specific reason in mind to not include them.
- I have a very general idea of how to approach this: basically we would make whatever is on the right side of `->` into a key prefix, then append it to all keys for the spans of the right side of the `@>` operator. For example - for something like `j->'a' @> '1'`, we would get the key prefix for `'a'` and add it to the containing spans for `'1'`. Just wanted to ask if you had other ideas in mind already, or if there's anything else I should know!

**Comment by mgartner** [comment]
Cool!

* I don't remember any specific reason I left out `null`. That being said, `null`s are always tricky, so we'll want some robust tests to make sure they behave as they should.
* That plans sounds good to me. Ideally we can support chained `->` operators too, like `j->'a'->'b' @> '1'`, if that's possible.

**Comment by Bessonov** [comment]
@angelazxu thank you very much!

**Comment by Bessonov** [comment]
Is https://github.com/cockroachdb/cockroach/issues/55318 a dupe?
