### ISSUE TITLE
sql: flaky TestReacquireLeaseOnRestart

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#61443]
Test flaked on https://teamcity.cockroachdb.com//viewLog.html?buildId=2742299&buildTypeId=Cockroach_MergeToMaster&tab=buildResultsDiv with 

```
closed timestamp above lease expiration (1614812915.443527468,1 vs 1614812915.443527468,0): EndTxn(commit:true) [â€¹/Table/11/1/52/1/2021-03-03T23:13:19.204141Z/1/0â€º], [txn: 101a62eb]
```

**Comment by andreimatei** [comment]
This says that a replica believes to have a closed timestamp above its lease expiration. Only the logical part differs, so hopefully this doesn't indicate anything too bad.

cc @nvanbenschoten

**Comment by andreimatei** [comment]
This assertion is on flaky ground, particularly in relation with closing out future times. But it's unclear how it fails today.
The test that failed is conspicuously named `sql.TestReacquireLeaseOnRestart`.

**Comment by andreimatei** [comment]
Figured it out. Will fix.

**Comment by andreimatei** [comment]
reopened to wait for backport

**Comment by andreimatei** [comment]
backported in #61666
