### ISSUE TITLE
This "is_live" status maybe confused.

### ISSUE THREAD

**Issue by Accords2021** [cockroachdb/cockroach#61447]
**Describe the problem**

I found that in the "crdb_internal.go" file, there is a  variable named "is_live". The status of it maybe confused by only judging the verification of client's message. 

![ef533dd3377cac4ecd1a02abcd1f03b](https://user-images.githubusercontent.com/80017918/109905153-50c88c80-7cd9-11eb-971f-e2829c36dee0.png)

![178a73880ce42df64b87ae38c387e85](https://user-images.githubusercontent.com/80017918/109905205-65a52000-7cd9-11eb-96a9-7a9b3721cabf.png)

![ef8cd2038fcabf43d3c4cd4aef0b941](https://user-images.githubusercontent.com/80017918/109905405-b0bf3300-7cd9-11eb-9c84-b90448987fa5.png)
 
Because I think that the live status of the node is related to the healthy or the liveness status, as the "kv/kvserver/liveness/livenesspb/liveness.go" shown.
![image](https://user-images.githubusercontent.com/80017918/109906362-52934f80-7cdb-11eb-812a-5d9ba1e70389.png)

I wonder that we cannot use the different explainations to define the only live status for node, it is may not strict.

**To Reproduce**
I advised that if you can also use the liveness status to mark if the node is live or dead in this situation. For example, you can find the liveness contents from gossip, and verify it is normal or unormal as usual. The client's key is used for us to get the connectivity of nodes not for insteading node's heartbeat, Isn't it?

**Environment:**
The latest release: v21.1

I think it's a bug for code, I hope you can adopt my opinion. Thank you.

**Comment by andreimatei** [comment]
You're referring to the `is_live` column in the `crdb_internal.gossip_nodes` table. One shouldn't read too much into the meaning of fields in these internal tables. It's customary for the `gossip_*` ones to directly publish the state from our gossip network, without interpreting it too much. In this context, `is_alive` just means that the node is connected to the gossip network.
Note that there's also the `crdb_internal.gossip_liveness` table, which exposes the liveness that you want.

We're unlikely to change anything here, so I'm closing. But feel free to reopen if you disagree.

**Comment by Accords2021** [comment]
Thanks a lot. What I recomand you is you may renamed is_alive to is_connected, I think it maybe better. Thank you again for your explaination.
