### ISSUE TITLE
kvserver: add UseClearRange option to GCRequest_GCKey

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#61455]
There is an open PR by @ajwerner that would need dedicated attention to land. It (dramatically) improves the ease with which we can GC large version histories of a key.

The reason the PR is held up is uncertainty about the possible negative impact of many range deletion tombstones. This is a concern that needs to be investigated.

This issue tracks the future of that PR, a job previously done by (now closed) https://github.com/cockroachdb/cockroach/issues/50194.

https://github.com/cockroachdb/cockroach/pull/51230

Jira issue: CRDB-3015

**Comment by tbg** [comment]
Note that we also have a more far-reaching proposal on the table, which is moving GC to the storage layer: https://github.com/cockroachdb/cockroach/issues/57260

Using ClearRange in "today's GC" might be useful as an interim step. We discussed perf impact on GC recently within KV and were unsure how "bad" GC is at the moment. That is, we had no good intuition of whether it is currently responsible for performance blips, etc, in the wild. We do have the `queue.gc.processingnanos` metric, so we should in theory be able to make such links.

**Comment by ajwerner** [comment]
I've never really understood how #57260 interacts with mvcc stats. Is the idea that we still read the data to evaluate the stats impact but then lay down some tombstone which will apply lazily to reclaim space?

**Comment by tbg** [comment]
The stats are indeed the "hard" part there. In a world without stats, I think the solution would simply be that we determine a GCThreshold, and bump that. And we say that versions covered by the GCThreshold cease to be part of the replicated state, i.e. they get omitted by snapshots and it's pebble jobs to remove them from any replica they linger on over time. But of course then a) we have to recompute stats when sending snapshots b) pebble has to somehow.. emit stats updates to us when it compacts.. and the stats are nonlocal (can't determine stats contributions of a single KV pair, you need to know whether it covers something, or is itself live, etc). #57260 essentially says "do something entirely new" or "recompute stats after GC". I'm not sure what that "entirely new" would be, exactly. Maybe it is what you're saying.

**Comment by sumeerbhola** [comment]
> The reason the PR is held up is uncertainty about the possible negative impact of many range deletion tombstones. This is a concern that needs to be investigated.

https://github.com/cockroachdb/pebble/issues/1295 should probably be a prerequisite.

**Comment by erikgrinaker** [comment]
#51230 uses a clearrange to remove many versions of a key. However, we also need a variant that uses clearrange to remove a long run of keys with no visible versions that all fell below the GC threshold at the same time. Typically because of a DeleteRange or something, especially with MVCC range tombstones (#70414).

**Comment by ajwerner** [comment]
>However, we also need a variant that uses clearrange to remove a long run of keys with no visible versions that all fell below the GC threshold at the same time. Typically because of a DeleteRange or something, especially with MVCC range tombstones (https://github.com/cockroachdb/cockroach/issues/70414).

This seems hard in that it'll run afoul of all the efforts to make MVCC GC latchless. We may need a new primitive which provides a to ensure that new writes don't accidentally get caught under this `ClearRange` when considering removing more than one key's versions.

**Comment by erikgrinaker** [comment]
Fixed by #90830.
