### ISSUE TITLE
sql/ui: reintroduce a total time metric

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#61475]
Previously, we had a `Total Time Metric` on the Statements Page. We removed this metric because customers found it confusing. 

The metric measured the total time used for the entire query fingerprint over the reporting period whereas statement time is the average time used for an individual time the statement occurred within the fingerprint.

Naming was a big part of why this was unclear to users. Whenever mockups were presented to end users, they immediately assumed that the total time metric was actually execution time and were immediately alarmed by the massive times they were seeing. We also considered "impact" as a column name on Ben's suggestion, but I don't think that was much clearer. Most users were also not intuiting what this metric was actually measuring, even after we pointed out that the statement time column had the avg exec latency they were looking for. 

We need to address:

- How to avoid end users confusing total time for mean statement time- I think a combination of naming (strawman: "Cumulative Exec Latency"), column placement (lead with avg statement time and have total time metric closer to the right hand side of the table), and default sort behavior (sort by avg statement time because that is largely what users expect instead of total time) may go a long way towards helping with this
- How to explain what Total time is actually measuring - we could add tooltips and links to documentation that explain this concept more clearly. I think the fastest way I was able to explain this metric is that total time = mean exec latency * exec count. That usually clicked immediately for end users.

Related to https://support.cockroachlabs.com/access/unauthenticated?return_to=https%3A%2F%2Fcockroachdb.zendesk.com%2Fagent%2Ftickets%2F5967

Thank to @piyush-singh for the historical context and suggestions above,

**Comment by maryliag** [comment]
@awoods187 you mentioned adding a link to documentation, does the documentation regarding this metric already exists or is it something that needs to be created too?

**Comment by awoods187** [comment]
We'd need documentation for this too. Luckily we can get help from @ianjevans as our docs team member.

**Comment by maryliag** [comment]
I added the value back using:

Name of the column: Cumulative Average Runtime
Tooltip: Cumulative of the average runtime (planning and execution) spent servicing all occurrences of statements with this fingerprint within the last hour or specified time interval.

Maybe it would make sense to use `Average Runtime` instead of `Statement Time` on the other column, so the meaning is clearer

Missing: 
- link on the tooltip for the documentation
- do I need a design of the details page with this value added or can I add it myself?

**Comment by maryliag** [comment]
cc @ianjevans @Annebirzin

**Comment by Annebirzin** [comment]
I think we could either go with:
-  `mean statement time` and `cumulative statement time` 
- Or as @maryliag suggested, `mean runtime` and `cumulative runtime` (if we go with `runtime`, we should update across detail pages and transaction pages as well for consistency) 

 @ianjevans thoughts?
 
 The tooltip copy looks good to me

**Comment by awoods187** [comment]
I don't like `runtime` personally. I think `cumulative statement time` may still be confusing. 

I do think we will need to do some discovery on the two specific names with customers. Something like what do you think `mean statement time` measures? `cumulative statement time`? how are they different? Do you have a different name?

**Comment by maryliag** [comment]
We won't add the `cumulative statement time` anymore, but `% of all runtime` instead.

@Annebirzin @ianjevans  can you validate the new tooltip:

% of runtime all occurrences of statements with this fingerprint represents compared to the cumulative runtime of all queries within the last hour or specified time interval.


all occurrences of statements with this fingerprint within the last hour or specified time interval.

**Comment by awoods187** [comment]
Nice update @maryliag! Would love a demo--maybe at team meeting next week?

**Comment by ianjevans** [comment]
> `% of runtime all occurrences of statements with this fingerprint represents compared to the cumulative runtime of all queries within the last hour or specified time interval.`

```
% of runtime all statements with this fingerprint represent, compared to the cumulative runtime of all queries within the last hour or specified time interval.
```

**Comment by maryliag** [comment]
@awoods187 absolutely! I can do that!

**Comment by maryliag** [comment]
Changes merged on https://github.com/cockroachdb/ui/pull/252
