### ISSUE TITLE
sql: add estimated rows per operator to explain

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#61479]
EXPLAIN (verbose) contains the estimated rows per operator but recent customer interviews have highlighted the need to add this to EXPLAIN directly.

@RaduBerinde do you think we can add this to this release?

**Comment by RaduBerinde** [comment]
It's already done, this is a dup of https://github.com/cockroachdb/cockroach/issues/61310 :)

**Comment by awoods187** [comment]
Lol i forgot i filed that thanks! So speedy!
