### ISSUE TITLE
sql,kv: add range information to EXPLAIN ANALYZE (Verbose)

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#61502]
Ideally, we hope customers can interface with SQL directly without interfacing with ranges or specifically hot ranges. This isn't always possible and we should provide a way to see which ranges are involved with a particular query under a verbose (non-default setting). 

Epic CRDB-6567

Jira issue: CRDB-3008

**Comment by Azhng** [comment]
Putting this work on pause for now. 

Feedback from the KV team suggested that there has been no precedence for the KV layer to expose detailed range information to the SQL layer. Doing so in the KV layer would an anti-pattern. 

We should take a step back and think about the right way to communicate this information.
