### ISSUE TITLE
ui: audit the DB Console and provide reference links throughout

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#61511]
The DB Console has many good pieces of information that are not connected together. We should audit the DB Console and provide referential links throughout to better connect all of the already existing and available data.

Jira issue: CRDB-3005

**Comment by thtruo** [comment]
cc @Annebirzin for awareness, related to our discussions and your Figma exploration around linking things together within the DB Console

**Comment by Annebirzin** [comment]
WIP designs for potential ways to link information together in the DB Console: https://miro.com/app/board/o9J_lLdjH3A=/
