### ISSUE TITLE
sql: gate `ALTER TYPE ... DROP VALUE` behind a feature flag

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#61519]
**Is your feature request related to a problem? Please describe.**

Currently, `ALTER TYPE ... DROP VALUE` is gated behind `sql_safe_updates`. This is misleading, as `sql_safe_updates` could imply an anti-pattern or not the best practice operation. This is not the case however. The only reason to gate this operation is that there are some (small) limitations in our current limitation, which are captured in https://github.com/cockroachdb/cockroach/issues/59807. We should therefore gate this operation behind a feature flag instead, say something like `enable_experimental_drop_enum_value` as a strawman proposal. cc @vy-ton

**Comment by vy-ton** [comment]
The setting can just be `enable_drop_enum_value`. We're moving away from using `experimental` and will be referring to this as an alpha feature.

The setting description should indicate that `ALTER TYPE...DROP VALUE` is an alpha feature

**Comment by arulajmani** [comment]
Thanks for getting back to me about the current thinking around this `experimental` stuff. I'll push out something to this effect 👍

**Comment by vy-ton** [comment]
Let's also consult @ericharmeling on the error message
**Actual**
```
demo@127.0.0.1:26257/defaultdb> alter type foo drop value 'b';
ERROR: rejected (sql_safe_updates = true): DROP VALUE may cause view/default/computed expressions to stop working if the enum value is used inside them
SQLSTATE: 01000
```

**Proposal**
```
ERROR: DROP VALUE is an alpha feature since view, default, or computed expressions will stop working if they reference the ENUM value. To enable, set enable_drop_enum_value=true.
```

**Comment by ericharmeling** [comment]
Should the message be preceded by `rejected (enable_drop_enum_value = false):`? Not sure what the convention is, or if that prefix helps with exception handling. Also, not sure what labeling the feature as "alpha" adds to the information given here (do we define what an "alpha feature" is somewhere)?

Suggestion:
> ERROR: rejected (enable_drop_enum_value = false): Dropping the ENUM value will cause view, default, or computed expressions that reference the value to stop working. To enable DROP VALUE, set enable_drop_enum_value=true.

**Comment by vy-ton** [comment]
>  Not sure what the convention is, or if that prefix helps with exception handling.

@arulajmani Is there a convention? Personally, the prefix confused me too and I favor removing itit. I read the original error as `sql_safe_updates = true` is why the SQL failed

**Comment by arulajmani** [comment]
My understanding is that this rejected prefix is only a thing for `sql_safe_updates` and not other types of feature gating. FWIW I find the `rejected sql_safe_updates = true` rather annoying -- I've found myself copy pasting that thing numerous times only to realize it was telling me that was the issue, not the fix. 

Instead, I'm much happier seeing `SET enable_drop_enum_value=true` as @vy-ton suggested above.
