### ISSUE TITLE
cli: unexpected interaction between PG notices and result rows

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#61516]
**Context** 
We want to send a pg notice from the coordinator node running a RESTORE statement if it is unable to find the table stats file in the backup location since this could impact query performance after RESTORE until the stats are recomputed.

**Approach**
We use the `BufferClientNotice` helper on the planner to buffer this notice as other statements like `CREATE INDEX CONCURRENTLY` appear to do.

**Issue**
The notice is getting flushed at a point that causes it to appear interleaved with the statement execution times.
<img width="1487" alt="Screen Shot 2021-03-04 at 9 31 34 AM" src="https://user-images.githubusercontent.com/13837382/110000443-48744f80-7ce1-11eb-999c-aca3cf0409df.png">

**Potential Root Cause**
RESTORE sends back a row with a summary of stats about the restore job. During the planning phase it also buffers a notice using the `BufferClientNotice` helper. Some debugging has led me to believe that the row with the completed jobs statistics is processed first, which we print as an asciiTable and set `delayNotices` to true - https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/sql_util.go#L629

The next row we process results in `handleNotice` being invoked, but since `delayNotices` is true, we don't flush it - https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/sql_util.go#L130

Once we have processed the rows, we invoke `maybeShowTimes` https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/sql_util.go#L940 that leads us to `getLastQueryStatistics`. This method notably calls `rows.Close()` on the internal query it issues - https://github.com/cockroachdb/cockroach/blob/a5a59be87d690ea28394a7213c20190d9c6616a0/pkg/cli/sql_util.go#L389 which triggers a flush of the notice we have buffered. I _think_ this explains the interleaved nature of the notice in the screenshot above,  when coming from restore.

**Comment by adityamaru** [comment]
@knz do you have any recommendations here, I'm running into this when trying to add a notice to the import job. One solution could be flushing the notices before we attempt to collect and print timings - https://github.com/cockroachdb/cockroach/blob/79935a612b1b271b0bcfb2e10323bbe4a21d38f1/pkg/cli/sql_util.go#L929?

**Comment by knz** [comment]
Yes the solution is to combine the print statements for the timings into one.

@arulajmani  can assist I think.

**Comment by knz** [comment]
I'll do it
