### ISSUE TITLE
ui: provide a default grafana view that mirrors the DB Console

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#61510]
We should provide a default Grafana template the mirrors our DB Console for those folks seeking to export metrics.

**Comment by sergeyshaykhullin** [comment]
Now i am using this dashboards https://grafana.com/grafana/dashboards?search=Cockroach

Do you mean to add official support?

**Comment by thtruo** [comment]
We've updated our Grafana dashboard templates with an accompanying README to set up Grafana, so we'll go ahead and close this issue
https://github.com/cockroachdb/cockroach/tree/master/monitoring

**Comment by sergeyshaykhullin** [comment]
@thtruo Can you please share your scrape_config generated by prometheus operator for cockroachdb job?

It will be useful for non-prometheus operator metrics deployments e.g. Cortex+grafana agent or VictoriaMetrics+VictoriaMetrics Agent

**Comment by thtruo** [comment]
@sergeyshaykhullin Sure thing, you can find them here at https://github.com/cockroachdb/cockroach/blob/4d987b3f0788c98fa358715b336a1c55e254ee50/monitoring/prometheus.yml and https://github.com/cockroachdb/cockroach/blob/085b05d69f67124a0c378e0c83c775df2e647a87/monitoring/demo/config/prometheus.yml

**Comment by sergeyshaykhullin** [comment]
Thanks)
