### ISSUE TITLE
roachperf: add ability to annotate time axis

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#61542]
**Is your feature request related to a problem? Please describe.**

[roachperf](https://roachperf.crdb.dev/) ([src](https://github.com/cockroachdb/roachperf)) graphs sometimes show noticeable drops that need to be investigated, such as here:

![image](https://user-images.githubusercontent.com/5076964/110101478-dc0e5480-7da3-11eb-9808-57b0e8f867b0.png)

Often, this investigation does take place, but there is no way to leave a trail for the next person to look at the graph.

Pebble has solved this via annotations in their [graphs](https://cockroachdb.github.io/pebble/):

![image](https://user-images.githubusercontent.com/5076964/110101620-137d0100-7da4-11eb-8792-9a20913f5815.png)

**Describe the solution you'd like**
We should add a similar mechanism to `roachperf`. @petermattis gave some details on how the pebble annotations work [here](https://cockroachlabs.slack.com/archives/C0HM2DZ34/p1614875715188300?thread_ts=1614874251.186600&cid=C0HM2DZ34) (internal link), and in particular pointed at the [code](https://github.com/cockroachdb/pebble/blob/639dfcee1d232e38ddc2d86ab5bf3ee6934878ba/docs/js/app.js#L213-L225) that renders the actual annotation.

**Describe alternatives you've considered**

**Additional context**

**Comment by stevendanna** [comment]
Fixed in https://github.com/cockroachdb/roachperf/pull/49 we could eventually enhance that to make it easier to add annotations directly in this repository, but hopefully the rate of annotations makes the current process OK for now.
