### ISSUE TITLE
bazel: add way to run lints w/ bazel-built binaries

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#61555]

**Comment by rickystewart** [comment]
I have a draft commit for this: https://github.com/rickystewart/cockroach/commit/f8f36b727655acc6c670b0fe1288ef33ad8195ad

Two problems with this:

1. `go vet` tries to compile a bunch of the source code, but it balks at the `cgo` commands to link in the native libraries:

```
        /usr/bin/ld: cannot find -lroach
        collect2: error: ld returned 1 exit status
        /usr/bin/ld: cannot find -lproj
        collect2: error: ld returned 1 exit status
        /usr/bin/ld: cannot find -ledit
        collect2: error: ld returned 1 exit status
        /usr/bin/ld: cannot find -lproj
        collect2: error: ld returned 1 exit status
        /usr/bin/ld: cannot find -lroach
        collect2: error: ld returned 1 exit status
        /usr/bin/ld: cannot find -lroach
        collect2: error: ld returned 1 exit status
```

The problem here is that we haven't appropriately set `LDFLAGS` to specify where these libraries live. So we need to update this code such that 1) we build `libproj`, `libroach`, and `libedit`, 2) we capture them in the `data` for the command, and 3) we update `LDFLAGS` appropriately in the script. Step (1) is the issue here, because I can't capture this stuff in the `data` for some reason.

2. `TestGCAssert` throws up hundreds of lines of spurious failures like this:

```
        ../../sql/colexec/sort.eg.go:436:	s.sortCol.Get(s.order[i]): call was not inlined
        ../../sql/colexec/sort.eg.go:437:	s.sortCol.Get(s.order[j]): call was not inlined
        ../../sql/colexec/sort.eg.go:514:	s.sortCol.Get(s.order[i]): call was not inlined
        ../../sql/colexec/sort.eg.go:515:	s.sortCol.Get(s.order[j]): call was not inlined
        ../../sql/colexec/sort.eg.go:584:	s.sortCol.Get(s.order[i]): call was not inlined
        ../../sql/colexec/sort.eg.go:585:	s.sortCol.Get(s.order[j]): call was not inlined
        ../../sql/colexec/sort.eg.go:654:	s.sortCol.Get(s.order[i]): call was not inlined
```

Not sure why. We've already determined the `go` version in use isn't bad.

**Comment by jordanlewis** [comment]
For point 2, it's either that the lint is working correctly and the compiler is no longer inlining the calls, which would be bad, or that the lint is somehow too fragile with the code paths that it's matching on. I'm guessing it's the latter, since the Bazel sandbox presumably does weird stuff to the paths of generated code.

Here's the code that does the path matching: https://github.com/jordanlewis/gcassert/blob/master/gcassert.go

Ricky, I'll try to dig into this soon, but realistically it might not be until Friday. Maybe we could poke at it together on a screenshare?

**Comment by rickystewart** [comment]
Hey Jordan -- sure, I'm back in office now, so whenever is fine :)

**Comment by rickystewart** [comment]
filed https://github.com/bazelbuild/rules_foreign_cc/issues/619 for issues arising from (1).

**Comment by rickystewart** [comment]
My understanding is https://github.com/bazelbuild/rules_go/pull/2858 (will probably be merged soon) helps with (2), and probably various other Bazel issues as well.

**Comment by rickystewart** [comment]
#65485 for the `TestGCAssert` thing

**Comment by rickystewart** [comment]
#65517 for remaining issues with `TestRoachVet`
