### ISSUE TITLE
sql: warning in demo on `use system` - CONNECT privilege

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#61560]
One way or another, I don't think demo should be telling me this (or pehaps the real question is what's gonna happen when I do this in "future release") ?

```
demo@127.0.0.1:26257/movr> use system;
NOTICE: CONNECT privilege will be required to connect to databases in a future release
HINT: See: https://go.crdb.dev/issue-v/59875/v21.1
SET
```

**Comment by rafiss** [comment]
Is the `demo` user an admin? @RichardJCai I think we'd want to give the demo user this privilege, or maybe make sure that the `admin` role has it?

Or we could just remove that message since we decided we won't be requiring this any time soon.

**Comment by RichardJCai** [comment]
> Is the `demo` user an admin? @RichardJCai I think we'd want to give the demo user this privilege, or maybe make sure that the `admin` role has it?
> 
> Or we could just remove that message since we decided we won't be requiring this any time soon.

Yeah by default we use root user for demo. This looks like it's specific to system db, haven't dug in yet. We can also remove the message.

**Comment by rafiss** [comment]
BTW, there's a different non-root demo user: https://github.com/cockroachdb/cockroach/pull/54749

**Comment by rafiss** [comment]
So yeah I think we should remove the message but also make sure ADMIN has the new privilege.
