### ISSUE TITLE
sql: add migration for connect privilege on system database for admin

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#61577]
When the system database is created, by default we only give it `SELECT`/`GRANT` (read only) compared to `ALL` on other databases.

We should add a migration for adding `CONNECT` privilege to admin as well.

Edit: This is not immediately necessary / urgent as `CONNECT` is currently only used for viewing table metadata and `admin` can already see metadata regardless.

**Comment by rafiss** [comment]
We'll close this until we see that it's necessary
