### ISSUE TITLE
sql: add telemetry counters by schema change type

### ISSUE THREAD

**Issue by fqazi** [cockroachdb/cockroach#61570]
We have telemetry counters by job type inside #59711. We should also have counters per-schema change type.

Jira issue: CRDB-2990

**Comment by vy-ton** [comment]
@fqazi Was this issue also going to cover distinguishing failed schema change by user input error vs. database error?

**Comment by ajwerner** [comment]
Can we spell out what counters this issue is asking for? What do we mean by type? What are the motivating questions here?

**Comment by vy-ton** [comment]
Motivating questions:

- Did a schema change fail because of user error (constraint violation) or internal database error?
- Whats the succeeded, failed, and cancelled number based on types of schema changes?

**Comment by postamar** [comment]
Should we restrict this to the declarative schema changer? This would simplify the ask a lot, at the expense of immediate usefulness of course.

**Comment by vy-ton** [comment]
@devadvocado and I will come back with requirements as we work through the schema data questions. likely we could restrict to the declarative schema changer
