### ISSUE TITLE
sql/ui: replace 0 values for sampled execution stats with a "sampling off" tooltip

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#61607]
If `sql.txn_stats.sample_rate` is not 1, it is likely that we have not collected execution stats for some statements. In this case, it would be confusing to show a zero value for stats such as network/max memory/contention since it wouldn't be true. Instead we should explain that no stats have been sampled, following this design:
![image](https://user-images.githubusercontent.com/10560359/110326292-778f0780-7fe6-11eb-86a4-7eef9d97a025.png)

**Comment by asubiotto** [comment]
The message should be more like "hasn't been sampled yet" cc @Annebirzin / @ianjevans  because we might have statement that has not been sampled even thought the cluster setting was set to a nonzero value.

**Comment by Annebirzin** [comment]
@asubiotto maybe we can change the label to `no samples` and then update the tooltip to something like 

`Either the statement sample rate is set to 0 or statements have not yet been sampled. You can update your cluster settings to turn on sampling and enable this metric.`

Thoughts @ianjevans ?

**Comment by ianjevans** [comment]
+1 to `no samples`.

> Either the statement sample rate is set to 0, disabling sampling, or statements have not yet been sampled. To [enable sampling](https://www.cockroachlabs.com/docs/stable/cluster-settings.html), set `sql.txn_stats.sample_rate` to 1.

**Comment by asubiotto** [comment]
I'm going to remove the "to 1" and change to "a nonzero value less than or equal to 1". Does that make sense? @ianjevans
