### ISSUE TITLE
Manual GC command

### ISSUE THREAD

**Issue by cubuzz** [cockroachdb/cockroach#61671]
**Is your feature request related to a problem? Please describe.**
Please view #61669

**Describe the solution you'd like**
A subcommand for the cockroach binary that manually gcs all files and deletes everything non-critical.
`cockroach gc --store=/path/to/store --include-time-series`

**Describe alternatives you've considered**
Another idea would be to add this feature to the dashboard. I think both would do good.

**Comment by andreimatei** [comment]
What data would you like this command to delete?
You know about how TTL is configured and works in CRDB, right?

FWIW, there's `cockroach debug compact` which needs to be run offline, and can save some space by compacting the storage engine. Also check out `cockroach debug balast` for a safety-net against running out of space.

**Comment by cubuzz** [comment]
I'll give those two a shot 👍 
I don't know why, but in my case cockroach says the node itself consumes 70MB of data, but the folders themselves are 450MB and so is stated on the main dashboard.

**Comment by cubuzz** [comment]
I did some more digging, seems that everything seems to be working except for what I said in #61669 with TimeSeries only compacting, not getting deleted. Closing.
