### ISSUE TITLE
sql: rewrite the CHECK expressions on column rename

### ISSUE THREAD

**Issue by seiflotfy** [cockroachdb/cockroach#6169]
Currently when renaming a column the CHECK constraint is unchanged and inserts fail with
```sql
statement error pq: qualified name "b" not found
```

A unit test for this can be found here https://github.com/cockroachdb/cockroach/blob/master/sql/testdata/check_constraints#L37

**Comment by dt** [comment]
@seiflotfy do you think we should add a warning about renaming columns used in CHECKs to the docs for now?

**Comment by seiflotfy** [comment]
@dt it wouldn't hurt. I will try to finish by next friday latest! :)

**Comment by jseldess** [comment]
Adding this note: 

> Do not rename a column that has a check constraint. Due to a current bug, if you rename such a column, you will not be able to insert or alter rows in the table.

With link to this issue.
