### ISSUE TITLE
cdc: configurable flush frequency

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#61700]
The "flush" frequency in the changefeed aggregator is how often `Flush()` will be called on the underlying sink.  Right now, the only way to control how often that flush happens is via the `resolved` option, which also tells CDC to emit resolved timestamps.

For some sinks, it would be nice to be able to control the flush frequency separate from the resolved timestamp frequency.

Jira issue: CRDB-2742

**Comment by amruss** [comment]
Closing due to https://github.com/cockroachdb/cockroach/issues/69161

**Comment by miretskiy** [comment]
Now, really closing.
