### ISSUE TITLE
sql: invalid session param in connection string should not cause connection to fail

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#61721]
**Describe the problem**

If you connect to CockroachDB with an invalid setting in the session parameters, the connection fails completely.

**To Reproduce**

Start a local database, then run:
```
 ./cockroach sql --url 'postgresql://root@localhost:26257/defaultdb?sslmode=disable&datestyle=MDY, ISO'
 ```
The command fails with:
```
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
ERROR: setting datestyle must be absent or ISO, MDY; got MDY, ISO
Failed running "sql"
```

**Expected behavior**
It should connect, and show a warning/error about the invalid session setting without closing the connection.

**Additional context**
Some tools try to connect to CRDB like this, and because the connection fails, it is a showstopper for compatibility.

However, PostgreSQL DOES error and close the connection if you try to connect with an unsupported session variable in the connection string. Completing this issue would be diverging from that behavior, but with the goal of allowing more tools to connect.

**Comment by bdarnell** [comment]
> ERROR: setting datestyle must be absent or ISO, MDY; got MDY, ISO

These two forms are equivalent in postgres - we could accept the options in either order without causing any problems. But accepting other options (such as "iso, ymd" which was mentioned in #41773) would be a bad idea since we'd silently misinterpret any date inputs.

**Comment by vy-ton** [comment]
I'm not in favor of doing this since invalid connection URLs would succeed silently. This would mean that if you misspell a valid connection parameter, you would get the same behavior.

**Comment by vy-ton** [comment]
Created #62026 to reflect Ben's suggestion. Closing this issue as we don't want to ignore invalid connection parameters
