### ISSUE TITLE
cli: the command history is not read back upon start-up

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#6172]
When the SQL shell is stopped the history is saved properly to ~/.cockroach_history. However when you start it again it is not possible to recall commands entered in the previous shell. This is a regression, this was possible prior to commit 198faa30309f080d34d2c782c18395b82339cc4b / 517aad9dbe3a1e5f7529f6253ae2ef82fe0ad05d.

cc @chzyer @guanqun.

**Comment by knz** [comment]
Apparently `readline.SetHistoryPath` does not cause the history to be re-read. @chzyer, comments?

**Comment by chzyer** [comment]
@knz, I pulled the commit 234e58042d2413b3ca151c6759f3bf8770b6106e, but everything goes well, including `~/.cockroach_history`. So I can't reproduce the bug.
Is the content of `~/.cockroach_history` is correct in your case?

**Comment by knz** [comment]
See attachment:  [repro.zip](https://github.com/cockroachdb/cockroach/files/228161/repro.zip)

**Comment by chzyer** [comment]
@knz , would you mind to check this pr can fix the problem?
