### ISSUE TITLE
ui: Summary pane on metrics dashboards flashes every few seconds

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#61729]
<img width="331" alt="Screen Shot 2021-03-09 at 12 42 40 PM" src="https://user-images.githubusercontent.com/5438456/110514256-1e51d180-80d5-11eb-804c-c5c370326ff1.png">

When running a cluster, I see the "Summary" pane flashing while re-loading every 5-10 seconds. This seems to happen whenever the `/_status/nodes` url is polled.

**Comment by kernfeld-cockroach** [comment]
This issue was just [mentioned](https://cockroachdb.slack.com/archives/CP4D9LD5F/p1623191547258200) by a user on our community Slack.

**Comment by thtruo** [comment]
Thanks for the ping Paul. @BramGruneir mentioned this yesterday as well. Assigning it to the Cluster UI team
