### ISSUE TITLE
sql: SHOW search_path does not properly quote $user

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#61730]
**Describe the problem**

Postgres: 

```
search_path  
----------------
 "$user", public
 ```
 
 Cockroach:
```
  search_path
----------------
 $user,public
 ```

This seems to break some Flyway things.

Should be extremely easy to fix. Probably just here: https://github.com/cockroachdb/cockroach/blob/16d0f7b7ccec222945f6bed858944b07e0d14834/pkg/sql/sessiondata/search_path.go#L244

I don't know whether you can put `$` into anything but perhaps we should just use our normal quoting rules for references?

**Comment by ajwerner** [comment]
cc @rafiss

**Comment by ajwerner** [comment]
Also we should string separate when we join them.

**Comment by istanfield09** [comment]
Is it cool if I take this one?

**Comment by ajwerner** [comment]
> Is it cool if I take this one?

Definitely! The function you should use to quote the strings properly is `tree.NameString()`. Then join them with `", "` .

**Comment by istanfield09** [comment]
> > Is it cool if I take this one?
> 
> Definitely! The function you should use to quote the strings properly is `tree.NameString()`. Then join them with `", "` .

Thanks! I will check it out this evening. 👍

**Comment by istanfield09** [comment]
Hello @ajwerner. Do you have any advice on how to get around the circular dependency created when importing `tree` into `sessiondata`? Sorry, I am a bit of a Golang newbie. Thanks in advance. 😓
