### ISSUE TITLE
sql/cli: make `cockroach dump --dump-mode=schema` delegate to SHOW CREATE ALL TABLES

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#61756]
We want to make sure the use case described in https://github.com/cockroachdb/cockroach/issues/53488 is not broken.

In 21.2, we should remove the `dump` CLI command entirely.

cc  @RichardJCai that means you don't need to add anything to `master` -- just the `release-21.1` branch.

**Comment by RichardJCai** [comment]
Closed via https://github.com/cockroachdb/cockroach/pull/61871
