### ISSUE TITLE
sql: Add sql.udts.alter_enum.add_value and sql.udts.alter_enum.drop_value telemetry counters

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/cockroach#61765]
In 20.2, we added a telemetry counter for `sql.udts.alter_enum`.

Since 21.1 supports `ALTER TYPE...DROP VALUE`, we should introduce more granular counters for `sql.udts.alter_enum.add_value` and `sql.udts.alter_enum.drop_value`

**Comment by rafiss** [comment]
@vy-ton is this needed in time for the initial 21.1.0 release?

**Comment by vy-ton** [comment]
Yes, would be great to get it in during stability

**Comment by arulajmani** [comment]
@vy-ton turns out we have telemetry for `ALTER TYPE ... ADD VALUE`  under `sql.schema.alter_type.add_value`. Do you still want `sql.udts.alter_enum.add_value`? 

Alternatively, I propose we add telemetry for DROP VALUE under `sql.schema.alter_type.drop_value` instead. Wdyt?

**Comment by vy-ton** [comment]
`sql.schema.alter_type.drop_value` works for me

Should `sql.udts.alter_enum` be deleted?

**Comment by arulajmani** [comment]
> Should sql.udts.alter_enum be deleted? Did it track the same thing as sql.schema.alter_type.add_value
 
 It also seems to track other alter statements, such as `RENAME VALUE`,  `RENAME TYPE` etc. but isn't granular about it.
