### ISSUE TITLE
sql: bizarre interaction between virtual computed columns and CREATE TABLE AS

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#61768]
**Describe the problem**

Something involving type checking:

```sql
CREATE TABLE t (
    k TIMESTAMPTZ NOT NULL,
    v STRING AS (IF(k IS NULL, NULL, NULL)) VIRTUAL NOT NULL,
    CONSTRAINT "primary" PRIMARY KEY (k ASC),
    FAMILY "primary" (k)
);
CREATE TABLE t2 AS SELECT v FROM t;
```
```
ERROR: value type unknown cannot be used for table columns
SQLSTATE: 42P16
```

Somehow we type check `v` into `UNKNOWN`.

**Additional Context**

Randomized testing is fun.

**Comment by ajwerner** [comment]
This is a sort of bogus case. The table is never allowed to have any rows. It's not clear exactly what to do here. We've got an expr that will always be NULL but we have a NOT NULL constraint. I think we need this have the type `STRING`.

**Comment by RaduBerinde** [comment]
The NOT NULL doesn't matter. The problem is that `v` in `SELECT v` has type Unknown. We are not requiring the column type when type-checking the computed column expression.
