### ISSUE TITLE
sql: Add third-party tool telemetry using SQL builtin function

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/cockroach#61766]
After https://github.com/cockroachdb/activerecord-cockroachdb-adapter/issues/169 has a working roundtrip for third-party tool telemetry, we should do the same for all our ORM adapters in priority order

- Django (https://github.com/cockroachdb/django-cockroachdb/issues/214) -- will be done by Tim
- SQLAlchemy (https://github.com/cockroachdb/sqlalchemy-cockroachdb/issues/139)
- Sequelize

Epic CRDB-1358

**Comment by vy-ton** [comment]
cc @solongordon This is the priority list

**Comment by RichardJCai** [comment]
@vy-ton 

Do we only want to add these to the latest versions?

**Comment by vy-ton** [comment]
@RichardJCai No, we should add it to all `1.3.x` versions so we can see the distribution of what users are using.

**Comment by vy-ton** [comment]
@RichardJCai For Sequelize, we should make sure that we have telemetry in place before the GA release of v6 and v5 against 20.2.

**Comment by RichardJCai** [comment]
Closed by https://github.com/cockroachdb/sqlalchemy-cockroachdb/pull/150
https://github.com/cockroachdb/sequelize-cockroachdb/pull/119
