### ISSUE TITLE
ui: When downsampling metrics using MAX or MIN, keep the node id for each datapoint

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#6177]
When the frontend queries timeseries metrics using the max or min downsampler across nodes, the value being returned corresponds to (at least) one specific node. I'm proposing that we include the node_id with the result.

The main goal would be that when users are looking at a graph that's downsampled in this way, they would be able to answer the question, for any specific datapoint, "which node exactly did this come from?"

The corresponding JSON would look something like:

``` json
  "datapoints": [
        {
          "timestamp_nanos": ...,
          "value": 300,
          "node_id": 1
        },
        {
          "timestamp_nanos": ...,
          "value": 350,
          "node_id": 3
        },
...
```

**Comment by maxlang** [comment]
@tschottdorf suggests a Top-k style downsampler as well here: https://github.com/cockroachdb/cockroach/pull/6161#issuecomment-212276513

> For that issue (don't see it yet): or the top3 (NodeID, Value) pairs along (to have some more relevant information to display).

**Comment by couchand** [comment]
This is an interesting idea, but seems too speculative to keep open.
