### ISSUE TITLE
sqlsmith: crashes in makeCreateTable

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#61775]
See run here: https://teamcity.cockroachdb.com/viewLog.html?buildId=2757388&tab=buildResultsDiv&buildTypeId=Cockroach_Nightlies_WorkloadNightly

It looks like `makeCreateTable` can panic if there are no schemas in the loaded smither. Perhaps this happens if we drop all the schemas?

@fqazi would you be able to take a look at this one?

**Comment by fqazi** [comment]
I'll take a look
