### ISSUE TITLE
telemetry: missing data for feature counter `monitoring.prometheus.vars` in v20.2.x clusters 

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#61778]
**Describe the problem**

It appears we have a telemetry issue where the feature counter `monitoring.prometheus.vars` has stopped firing for clusters prefixed with version `v20.2.x` since October. 

**To Reproduce**

Here is a [Looker](https://cockroachlabs.looker.com/explore/cockroach_analytics/cdc_features?qid=m10B7uH4Bjd36nhZkvN4Wf&origin_space=9&toggle=fil,vis) report that shows that we are missing data for 20.2.x clusters. 

<img width="815" alt="Image 2021-03-10 at 11 23 43 AM" src="https://user-images.githubusercontent.com/1474303/110662374-6fc09600-8193-11eb-8938-4b7cd5c99dab.png">

**Additional context**
Impact: Unfortunately our key result measuring _the % of long running clusters using programmatic monitoring_ has been undercounted and inaccurate for understanding the usage and value of this feature.

**Comment by thtruo** [comment]
cc @piyush-singh and @knz for triage recommendations. is there a particular team that should take this on, or does it live in Server?

**Comment by knz** [comment]
Is there a definition of what this counter is _supposed_ to be monitoring?

IMHO since there was no definition nor test in the code to catch this I am not surprised the counting disappeared by accident. In general, all the counters being added throughout the code without spec / testing will undergo the same fate (or worse: they may be inadvertently changed to start counting something unrelated entirely, without the PM realizing).

**Comment by knz** [comment]
In fact, I looked in the code and as far as I can see the feature counter is still being incremented in the right place!

**Comment by piyush-singh** [comment]
This counter tracks the number of hits to the HTTP endpoint for our prometheus metrics. I actually checked in a 20.2 cluster and was able to see this in the diagnostics endpoint:

![image](https://user-images.githubusercontent.com/21692034/111359093-7783ad00-8661-11eb-991d-31ef484b2c02.png)

So it does look like this feature is being incremented properly like @knz points out. Is this an issue with some part of the data pipeline downstream? @thtruo it may be a good idea to see if we can pull any of this data in Snowflake directly. We can work backwards to see where this data is falling out of our telemetry.

**Comment by thtruo** [comment]
Ack - thank you both for verifying that. I'll work with our data/BI team ([BI-102](https://cockroachlabs.atlassian.net/servicedesk/customer/portal/4/BI-102?created=true) in JIRA) to identify the issue in our data pipeline. FWIW I can pull the data in Snowflake, so my hunch is the issue is coming from Looker.

I'll close this issue in the meantime
