### ISSUE TITLE
kv: 1pc transactions send all intents in EndTransactionRequest

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#6179]
The `EndTransactionRequest` contains all of the intents created in the transaction. For 1pc transactions this seems excessive as all of the intents can be derived from the other requests in the `BatchRequest`. And with the fast-path for 1pc transactions in `Replica`, often no intents are being created at all.

**Comment by tschottdorf** [comment]
I agree that that's excessive. It's unfortunately a little tricky: We don't know for sure that something is going to be 1PC unless it hits the Replica. We could make `DistSender` drop the intents from the request immediately before dispatching to a single range. A Replica would then have to inspect the batches and recreate the intents for EndTransaction in the slow path (which would presumably almost never be taken). I wonder if it's worth the complexity - 1PC transactions will typically not have many intents, so the extra payload isn't that large - so the main motivation for this change is probably improved benchmarking against Postgres.

I ran a quick comparison ("new" is just dropping the intents in DistSender for requests that look reasonably 1PC; I did check that it fired during the benchmarks). Careful, ran those on my laptop.

```
07:09 $ benchstat old new
name                           old time/op    new time/op    delta
Insert1_Cockroach-8               296µs ± 7%     281µs ± 3%  -4.90%   (p=0.006 n=9+10)
Insert10_Cockroach-8              494µs ± 3%     488µs ± 2%  -1.24%  (p=0.035 n=10+10)
Insert100_Cockroach-8            1.88ms ± 5%    1.85ms ± 0%    ~      (p=0.696 n=10+8)
Insert1000_Cockroach-8           15.8ms ± 2%    15.6ms ± 7%    ~     (p=0.190 n=10+10)
InsertDistinct1_Cockroach-8      2.09ms ± 1%    2.09ms ± 1%    ~     (p=0.912 n=10+10)
InsertDistinct10_Cockroach-8     1.59ms ± 1%    1.61ms ± 5%    ~     (p=0.247 n=10+10)
InsertDistinct100_Cockroach-8    2.39ms ±10%    2.32ms ± 3%    ~      (p=0.400 n=9+10)

name                           old alloc/op   new alloc/op   delta
Insert1_Cockroach-8              22.8kB ± 0%    22.7kB ± 0%  -0.56%  (p=0.000 n=10+10)
Insert10_Cockroach-8             65.9kB ± 0%    63.8kB ± 0%  -3.20%  (p=0.000 n=10+10)
Insert100_Cockroach-8             440kB ± 0%     425kB ± 0%  -3.56%   (p=0.000 n=9+10)
Insert1000_Cockroach-8           3.90MB ± 0%    3.71MB ± 0%  -4.84%    (p=0.000 n=9+9)
InsertDistinct1_Cockroach-8       270kB ± 0%     255kB ± 0%  -5.32%  (p=0.000 n=10+10)
InsertDistinct10_Cockroach-8      288kB ± 0%     274kB ± 0%  -4.96%   (p=0.000 n=10+8)
InsertDistinct100_Cockroach-8     600kB ± 1%     585kB ± 0%  -2.51%    (p=0.000 n=9+9)

name                           old allocs/op  new allocs/op  delta
Insert1_Cockroach-8                 285 ± 0%       283 ± 0%  -0.70%  (p=0.000 n=10+10)
Insert10_Cockroach-8                573 ± 0%       558 ± 0%  -2.62%   (p=0.002 n=8+10)
Insert100_Cockroach-8             3.30k ± 0%     3.19k ± 0%  -3.30%    (p=0.019 n=6+8)
Insert1000_Cockroach-8            30.4k ± 0%     29.4k ± 0%  -3.33%    (p=0.000 n=9+9)
InsertDistinct1_Cockroach-8       2.60k ± 0%     2.54k ± 0%  -2.22%   (p=0.000 n=10+7)
InsertDistinct10_Cockroach-8      2.75k ± 0%     2.70k ± 0%  -2.08%   (p=0.000 n=10+9)
InsertDistinct100_Cockroach-8     5.46k ± 1%     5.39k ± 0%  -1.21%    (p=0.000 n=9+9)
```

Unless there's anything else I should be looking at, this is a bit of a high-hanging fruit right now, but should keep it on the radar.

**Comment by petermattis** [comment]
The bigger win from not sending the intents is not computing them at all. The `IntentSpanIterate` and `collectIntentSpans` calls in `TxnCoordSender.Send` show up in cpu and memory profiles. I did a quick hack to optimize intent generation for 1pc requests (by not using a `RangeTree`) and saw a ~5 speedup. I'm going to take a look at moving the code to add intents to the `EndTransactionRequest` to "underneath" `DistSender`. At first glance, this doesn't look too bad if I have `TxnCoordSender` hook into `DistSender.rpcSend`. One complexity is that `TxnCoordSender` isn't always used with a `DistSender` (e.g. in test situations), but I think that is manageable.

**Comment by tschottdorf** [comment]
What's a ~5 speedup? Percent? Could you post it? If moving the code down is unproblematic, why not.

**Comment by petermattis** [comment]
Heh, 5%. Like a fool, I deleted the code and data a while ago, but it was a simple change that I've just reconstituted.

```diff
diff --git a/kv/txn_coord_sender.go b/kv/txn_coord_sender.go
index 534514d..199172a 100644
--- a/kv/txn_coord_sender.go
+++ b/kv/txn_coord_sender.go
@@ -366,16 +366,20 @@ func (tc *TxnCoordSender) Send(ctx context.Context, ba roachpb.BatchRequest) (*r

                        // Populate et.IntentSpans, taking into account both any existing
                        // and new writes, and taking care to perform proper deduplication.
-                       var keys interval.RangeGroup
                        if txnMeta, metaOK := tc.txns[*ba.Txn.ID]; metaOK {
-                               keys = txnMeta.keys
+                               keys := txnMeta.keys
+                               ba.IntentSpanIterate(func(key, endKey roachpb.Key) {
+                                       addKeyRange(keys, key, endKey)
+                               })
+                               et.IntentSpans = collectIntentSpans(keys)
                        } else {
-                               keys = interval.NewRangeTree()
+                               ba.IntentSpanIterate(func(key, endKey roachpb.Key) {
+                                       et.IntentSpans = append(et.IntentSpans, roachpb.Span{
+                                               Key:    key,
+                                               EndKey: endKey,
+                                       })
+                               })
                        }
-                       ba.IntentSpanIterate(func(key, endKey roachpb.Key) {
-                               addKeyRange(keys, key, endKey)
-                       })
-                       et.IntentSpans = collectIntentSpans(keys)
                        if len(et.IntentSpans) == 0 {
                                // If there aren't any intents, then there's factually no
                                // transaction to end. Read-only txns have all of their state
```

And the numbers:

```
name                 old time/op    new time/op    delta
KVInsert1_SQL-8         253µs ± 1%     252µs ± 1%    ~     (p=0.421 n=5+5)
KVInsert10_SQL-8        543µs ± 0%     536µs ± 2%    ~     (p=0.151 n=5+5)
KVInsert100_SQL-8      2.73ms ± 1%    2.56ms ± 1%  -5.92%  (p=0.008 n=5+5)
KVInsert1000_SQL-8     25.9ms ± 1%    24.0ms ± 2%  -7.28%  (p=0.008 n=5+5)
KVInsert10000_SQL-8     296ms ± 4%     269ms ± 4%  -8.99%  (p=0.008 n=5+5)

name                 old alloc/op   new alloc/op   delta
KVInsert1_SQL-8        25.0kB ± 0%    24.6kB ± 0%  -1.40%  (p=0.008 n=5+5)
KVInsert10_SQL-8        112kB ± 0%     110kB ± 0%  -1.14%  (p=0.008 n=5+5)
KVInsert100_SQL-8       836kB ± 0%     818kB ± 0%  -2.16%  (p=0.008 n=5+5)
KVInsert1000_SQL-8     9.30MB ± 0%    9.23MB ± 0%  -0.70%  (p=0.008 n=5+5)
KVInsert10000_SQL-8     119MB ± 0%     120MB ± 0%  +0.95%  (p=0.008 n=5+5)

name                 old allocs/op  new allocs/op  delta
KVInsert1_SQL-8           295 ± 0%       289 ± 0%  -2.03%  (p=0.008 n=5+5)
KVInsert10_SQL-8          768 ± 0%       730 ± 0%  -4.95%  (p=0.008 n=5+5)
KVInsert100_SQL-8       5.30k ± 0%     4.91k ± 0%  -7.46%  (p=0.008 n=5+5)
KVInsert1000_SQL-8      50.6k ± 0%     46.6k ± 0%  -7.86%  (p=0.008 n=5+5)
KVInsert10000_SQL-8      518k ± 0%      478k ± 0%  -7.72%  (p=0.008 n=5+5)
```

**Comment by tschottdorf** [comment]
OK. I haven't checked (am in transit) but sendChunk might be another good
(better if it works out) home for this.

On Thu, May 5, 2016, 14:43 Peter Mattis <notifications@github.com> wrote:

> Heh, 5%. Like a fool, I deleted the code and data a while ago, but it was
> a simple change that I've just reconstituted.
>
> diff --git a/kv/txn_coord_sender.go b/kv/txn_coord_sender.go
> index 534514d..199172a 100644--- a/kv/txn_coord_sender.go+++ b/kv/txn_coord_sender.go@@ -366,16 +366,20 @@ func (tc *TxnCoordSender) Send(ctx context.Context, ba roachpb.BatchRequest) (*r
>
>                         // Populate et.IntentSpans, taking into account both any existing
>                         // and new writes, and taking care to perform proper deduplication.-                       var keys interval.RangeGroup
>                         if txnMeta, metaOK := tc.txns[*ba.Txn.ID]; metaOK {-                               keys = txnMeta.keys+                               keys := txnMeta.keys+                               ba.IntentSpanIterate(func(key, endKey roachpb.Key) {+                                       addKeyRange(keys, key, endKey)+                               })+                               et.IntentSpans = collectIntentSpans(keys)
>                         } else {-                               keys = interval.NewRangeTree()+                               ba.IntentSpanIterate(func(key, endKey roachpb.Key) {+                                       et.IntentSpans = append(et.IntentSpans, roachpb.Span{+                                               Key:    key,+                                               EndKey: endKey,+                                       })+                               })
>                         }-                       ba.IntentSpanIterate(func(key, endKey roachpb.Key) {-                               addKeyRange(keys, key, endKey)-                       })-                       et.IntentSpans = collectIntentSpans(keys)
>                         if len(et.IntentSpans) == 0 {
>                                 // If there aren't any intents, then there's factually no
>                                 // transaction to end. Read-only txns have all of their state
>
> And the numbers:
>
> name                 old time/op    new time/op    delta
> KVInsert1_SQL-8         253µs ± 1%     252µs ± 1%    ~     (p=0.421 n=5+5)
> KVInsert10_SQL-8        543µs ± 0%     536µs ± 2%    ~     (p=0.151 n=5+5)
> KVInsert100_SQL-8      2.73ms ± 1%    2.56ms ± 1%  -5.92%  (p=0.008 n=5+5)
> KVInsert1000_SQL-8     25.9ms ± 1%    24.0ms ± 2%  -7.28%  (p=0.008 n=5+5)
> KVInsert10000_SQL-8     296ms ± 4%     269ms ± 4%  -8.99%  (p=0.008 n=5+5)
>
> name                 old alloc/op   new alloc/op   delta
> KVInsert1_SQL-8        25.0kB ± 0%    24.6kB ± 0%  -1.40%  (p=0.008 n=5+5)
> KVInsert10_SQL-8        112kB ± 0%     110kB ± 0%  -1.14%  (p=0.008 n=5+5)
> KVInsert100_SQL-8       836kB ± 0%     818kB ± 0%  -2.16%  (p=0.008 n=5+5)
> KVInsert1000_SQL-8     9.30MB ± 0%    9.23MB ± 0%  -0.70%  (p=0.008 n=5+5)
> KVInsert10000_SQL-8     119MB ± 0%     120MB ± 0%  +0.95%  (p=0.008 n=5+5)
>
> name                 old allocs/op  new allocs/op  delta
> KVInsert1_SQL-8           295 ± 0%       289 ± 0%  -2.03%  (p=0.008 n=5+5)
> KVInsert10_SQL-8          768 ± 0%       730 ± 0%  -4.95%  (p=0.008 n=5+5)
> KVInsert100_SQL-8       5.30k ± 0%     4.91k ± 0%  -7.46%  (p=0.008 n=5+5)
> KVInsert1000_SQL-8      50.6k ± 0%     46.6k ± 0%  -7.86%  (p=0.008 n=5+5)
> KVInsert10000_SQL-8      518k ± 0%      478k ± 0%  -7.72%  (p=0.008 n=5+5)
>
> —
> You are receiving this because you were assigned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/6179#issuecomment-217157586>
>
-- 

-- Tobias

**Comment by tschottdorf** [comment]
Besides (and somewhat unrelated), I'm wondering what your thoughts on
cutoffs for worthwhile low level optimizations are - I still see this one
as a bit higher up in the tree, and that this complexity we put in now
could backfire (for example making refactors harder) or simple become
obsolete. Where should we draw the line?

On Thu, May 5, 2016, 15:02 Tobias Schottdorf <tobias@cockroachlabs.com>
wrote:

> OK. I haven't checked (am in transit) but sendChunk might be another good
> (better if it works out) home for this.
>
> On Thu, May 5, 2016, 14:43 Peter Mattis <notifications@github.com> wrote:
>
>> Heh, 5%. Like a fool, I deleted the code and data a while ago, but it was
>> a simple change that I've just reconstituted.
>>
>> diff --git a/kv/txn_coord_sender.go b/kv/txn_coord_sender.go
>> index 534514d..199172a 100644--- a/kv/txn_coord_sender.go+++ b/kv/txn_coord_sender.go@@ -366,16 +366,20 @@ func (tc *TxnCoordSender) Send(ctx context.Context, ba roachpb.BatchRequest) (*r
>>
>>                         // Populate et.IntentSpans, taking into account both any existing
>>                         // and new writes, and taking care to perform proper deduplication.-                       var keys interval.RangeGroup
>>                         if txnMeta, metaOK := tc.txns[*ba.Txn.ID]; metaOK {-                               keys = txnMeta.keys+                               keys := txnMeta.keys+                               ba.IntentSpanIterate(func(key, endKey roachpb.Key) {+                                       addKeyRange(keys, key, endKey)+                               })+                               et.IntentSpans = collectIntentSpans(keys)
>>                         } else {-                               keys = interval.NewRangeTree()+                               ba.IntentSpanIterate(func(key, endKey roachpb.Key) {+                                       et.IntentSpans = append(et.IntentSpans, roachpb.Span{+                                               Key:    key,+                                               EndKey: endKey,+                                       })+                               })
>>                         }-                       ba.IntentSpanIterate(func(key, endKey roachpb.Key) {-                               addKeyRange(keys, key, endKey)-                       })-                       et.IntentSpans = collectIntentSpans(keys)
>>                         if len(et.IntentSpans) == 0 {
>>                                 // If there aren't any intents, then there's factually no
>>                                 // transaction to end. Read-only txns have all of their state
>>
>> And the numbers:
>>
>> name                 old time/op    new time/op    delta
>> KVInsert1_SQL-8         253µs ± 1%     252µs ± 1%    ~     (p=0.421 n=5+5)
>> KVInsert10_SQL-8        543µs ± 0%     536µs ± 2%    ~     (p=0.151 n=5+5)
>> KVInsert100_SQL-8      2.73ms ± 1%    2.56ms ± 1%  -5.92%  (p=0.008 n=5+5)
>> KVInsert1000_SQL-8     25.9ms ± 1%    24.0ms ± 2%  -7.28%  (p=0.008 n=5+5)
>> KVInsert10000_SQL-8     296ms ± 4%     269ms ± 4%  -8.99%  (p=0.008 n=5+5)
>>
>> name                 old alloc/op   new alloc/op   delta
>> KVInsert1_SQL-8        25.0kB ± 0%    24.6kB ± 0%  -1.40%  (p=0.008 n=5+5)
>> KVInsert10_SQL-8        112kB ± 0%     110kB ± 0%  -1.14%  (p=0.008 n=5+5)
>> KVInsert100_SQL-8       836kB ± 0%     818kB ± 0%  -2.16%  (p=0.008 n=5+5)
>> KVInsert1000_SQL-8     9.30MB ± 0%    9.23MB ± 0%  -0.70%  (p=0.008 n=5+5)
>> KVInsert10000_SQL-8     119MB ± 0%     120MB ± 0%  +0.95%  (p=0.008 n=5+5)
>>
>> name                 old allocs/op  new allocs/op  delta
>> KVInsert1_SQL-8           295 ± 0%       289 ± 0%  -2.03%  (p=0.008 n=5+5)
>> KVInsert10_SQL-8          768 ± 0%       730 ± 0%  -4.95%  (p=0.008 n=5+5)
>> KVInsert100_SQL-8       5.30k ± 0%     4.91k ± 0%  -7.46%  (p=0.008 n=5+5)
>> KVInsert1000_SQL-8      50.6k ± 0%     46.6k ± 0%  -7.86%  (p=0.008 n=5+5)
>> KVInsert10000_SQL-8      518k ± 0%      478k ± 0%  -7.72%  (p=0.008 n=5+5)
>>
>> —
>> You are receiving this because you were assigned.
>>
>>
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cockroachdb/cockroach/issues/6179#issuecomment-217157586>
>>
> --
>
> -- Tobias
>
-- 

-- Tobias

**Comment by petermattis** [comment]
Paraphrasing Justice Potter Stewart: I'm not sure where we should draw the line, but I'll know it when I see it.

**Comment by bdarnell** [comment]
I'm currently working in the `DistSender` code and while I don't love the current division between `TxnCoordSender` and `DistSender`, I think it's one of the things keeping the `kv` package manageable. A 5% speedup is not enough of a win for me to feel comfortable mixing those layers. I'd be open to refactorings (even radical ones) that improve clarity here (and may in the process provide this performance benefit), but if it comes at the expense of clarity then we have much higher priorities than a 5% speedup.

**Comment by petermattis** [comment]
The win from not generating the intents for 1pc transactions looks closer to 10-12% for bulk insert benchmarks. Not sure it is worth it. I don't particularly love the separation of code between `TxnCoordSender` and `DistSender`. Feels somewhat artificial.

**Comment by tschottdorf** [comment]
I can share Ben's reservations. Having worked in that code so much, it's
one of the more complicated corners of our codebase. Maybe what we should
do instead of putting this in right now is to think about what we want
TxnCoordSender+DistSender to be to enable the constraints that we have (in
particular, parallelization, but also avoiding nearly all overhead in the
1PC case). We can always reap these performance benefits close to OKR
closing time if we get desperate (though getting desperate for such goals
is likely a bad idea).

On Thu, May 5, 2016 at 8:13 PM Peter Mattis <notifications@github.com>
wrote:

> The win from not generating the intents for 1pc transactions looks closer
> to 10-12% for bulk insert benchmarks. Not sure it is worth it. I don't
> particularly love the separation of code between TxnCoordSender and
> DistSender. Feels somewhat artificial.
>
> —
> You are receiving this because you were assigned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/6179#issuecomment-217315543>
>
-- 

-- Tobias

**Comment by tschottdorf** [comment]
Unassigning because not planning to work on this in the near future.
