### ISSUE TITLE
sql: Disable interleaved tables by default in cockroach demo

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/cockroach#61809]
**Actual behavior**
```
demo@127.0.0.1:26257/defaultdb> show cluster setting sql.defaults.interleaved_tables.enabled;
  sql.defaults.interleaved_tables.enabled
-------------------------------------------
                   true
```

**Expected behavior**
In 21.1, we wanted `sql.defaults.interleaved_tables.enabled=false` by default. 

Jira issue: CRDB-2731

**Comment by jordanlewis** [comment]
Hm, we did this work in #59248. I wonder what happened.

**Comment by jordanlewis** [comment]
Ah, did you check via `cockroach demo`? It looks like `cockroach demo` has it set to true because it uses a test server, which has it enabled by default for test cases.

**Comment by jordanlewis** [comment]
No, that's okay. I'll re-open this and change it to be about `cockroach demo`

**Comment by jordanlewis** [comment]
This is done
