### ISSUE TITLE
follower-reads availability

### ISSUE THREAD

**Issue by lamontgr** [cockroachdb/cockroach#61824]
**Is your feature request related to a problem? Please describe.**
For our workload, high read-availability is critical. In a multi-region CockroachDB cluster deployment, when a region is detached from the rest of the cluster, read-queries to this region fails to return data even if replicas and leaseholders are present on the nodes (ex. duplicate indexes topology)

We would like to request a feature to have read-only replicas available in a region that has been detached from quorum 

**Describe the solution you'd like**
For example, in a 3-region deployment:
- 1 region becomes detached from the other two

It would be beneficial to have an option for read-only availability for the detached region.This scenario will help in workloads where availability of low-latency reads are critical, whereas availability of writes is much less critical.

Stale reads are acceptable in this case where the region has been isolated from all others

Jira issue: CRDB-2728

**Comment by lamontgr** [comment]
Some additional information on acceptable options:
- It would acceptable for Follower Reads to provide stale data.  There would need to be a helper function that would indicate the latest data available in the local region.  The local cluster nodes would need to remain available for reads when disconnected from the other DCs.
- It would be acceptable for the entire cluster to drop into read-only mode (all 3 DC).  This was the initial understanding of how duplicate indexes would work (each DC would elect a leaseholder and could always serve reads, writes would require talking across mutliple DCs and could fail if all DCs were not available)
- It would also be acceptable to provide an inter-cluster replication mechanism that would allow a read-only replica cluster to synchronously (preferred) or asynchronously (acceptable) replicate with the master cluster.

**Comment by andreimatei** [comment]
We're considering some options here for the 21.2 releases.

**Comment by andreimatei** [comment]
closing as dupe of #6150

**Comment by a-entin** [comment]
Re-opening per prior conversation w/ Andrei to include these requirements in the design considerations.
Also useful to track the feature request: will close when the feature is available.
