### ISSUE TITLE
kvcoord: should propagate failing refresh key to txn retry err

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#61838]
**Is your feature request related to a problem? Please describe.**

Consider the following real-world retry error (v20.2.4):

> TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh): \"sql txn\" meta={id=c26a8fb9 key=/Table/63/1/\"92e908fc-adaf-468a-a8e8-f2a821780d11\"/0 pri=0.00640126 epo=0 ts=1615316252.646058725,1 min=1615316252.626338609,0 seq=4} lock=true stat=PENDING rts=1615316252.626338609,0 wto=false max=1615316253.126338609,0

It's emitted around here:

https://github.com/cockroachdb/cockroach/blob/a61da063be526c6b72dc4252103fd53e42fcb08e/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go#L480-L484

This error is a failed refresh, but it's not telling us which span the txn was unable to refresh. This information is in principle available where the error is created, as it is contained in this error:

https://github.com/cockroachdb/cockroach/blob/a61da063be526c6b72dc4252103fd53e42fcb08e/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go#L565-L569

**Describe the solution you'd like**

> TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh **of span [/foo, /bar)**): \"sql txn\" meta={id=c26a8fb9 key=/Table/63/1/\"92e908fc-adaf-468a-a8e8-f2a821780d11\"/0 pri=0.00640126 epo=0 ts=1615316252.646058725,1 min=1615316252.626338609,0 seq=4} lock=true stat=PENDING rts=1615316252.626338609,0 wto=false max=1615316253.126338609,0

**Describe alternatives you've considered**

**Additional context**

This is a concrete improvement we can make for https://github.com/cockroachdb/cockroach/issues/53746.

**Comment by tbg** [comment]
@nvanbenschoten this seems relatively easy + valuable, think it's worthwhile for one of our newer team members to pick up?

**Comment by nvanbenschoten** [comment]
I agree. This would be a nice improvement and it dovetails nicely with https://github.com/cockroachdb/cockroach/issues/41057 / https://github.com/cockroachdb/cockroach/issues/53746.
