### ISSUE TITLE
Cluster level equivalents of idle_in_session_timeout and idle_in_transaction_session_timeout

### ISSUE THREAD

**Issue by cjireland** [cockroachdb/cockroach#61839]
The above variables can only currently be set at the session level.

Rather than rely on individual applications to set them on their connections a client would like to be able to set them at the cluster level. This will allow them to prevent sessions holding on to resources such as database locks unnecessarily and for a long time.

If an application then needs longer they can override these settings on a per session basis.

As a general point it may be worth reviewing all the session level settings with a view to creating cluster level settings so particular database usage patterns/rules can be created per customer at a cluster level.

**Comment by yuzefovich** [comment]
We do have `sql.defaults.idle_in_session_timeout` cluster setting which is the equivalent of session variable `idle_in_session_timeout`. Note that the cluster setting is not marked as "public" (meaning it won't show up in `SHOW CLUSTER SETTINGS ALL`).

**Comment by cjireland** [comment]
@yuzefovich , thank you. 
I can't show the other setting so I guess that's not available at the cluster level? I guess also that a review of session v cluster for all settings would still be useful.

**Comment by rafiss** [comment]
@solongordon @vy-ton do we want these two cluster settings to be `public`?

**Comment by cjireland** [comment]
Please can someone confirm in which version of CRDB this change will be deployed?

Is there a plan to review other session level settings to determine whether we have cluster level equivalents?

Thanks.

**Comment by rafiss** [comment]
@cjireland We can backport this into v20.2.7, and it will be in v21.1.0 as well.

Here is an issue to check for other session settings that could use cluster equivalents: https://github.com/cockroachdb/cockroach/issues/62174 We will schedule that work soon.

**Comment by cjireland** [comment]
@rafiss , perfect thanks!
