### ISSUE TITLE
CRDB cluster failure: No progress, leaseholders crash?

### ISSUE THREAD

**Issue by roy-work** [cockroachdb/cockroach#61867]
**Describe the problem**

One of our (production) CRDB clusters somehow wedged itself: queries to the cluster were timing out, even incredibly simple ones. No appreciable work was happening.

Our outage/incident starts at ~3:00p. At that time, the logs show a large number of entries like,

* `failed node liveness heartbeat: operation "node liveness heartbeat" timed out after 4.5s`
* `slow heartbeat took 4.5s` (or 5s, or 60s, etc.) (we logged ~23k of these in ~5 minutes(!) at the start of the outage, across our cluster.)
* slow lease acquisition finished after 1m0.110768471s with error [NotLeaseHolderError]

and a few,

* user lookup for "[redact]" failed: operation "get-user-timeout" timed out after 10s: error looking up user [redact]: get-hashed-pwd: context deadline
  (the user here is a service user, and it seems to be the client trying to re-connect. Even simple `SHOW USERS;` in `cockroach sql` fail.)

During the outage, we tested the network using `ping` from one node, to all other nodes in the cluster; ping times were generally <1ms. The only thing we did to correct the outage was to remove most load, restart the database, and then gradually re-add load. But given that we've been bitten twice, I don't see what's to prevent it from happening again.

"Slow" heartbeats:

![image](https://user-images.githubusercontent.com/53838718/110845988-3f532780-8279-11eb-83b4-3ada2a43dfd9.png)
(The y-axis is seconds; max per 1-minute buckets. The flat second is 60s for reference; I have no idea what the spike is, but it's more the lower plateau at 60s that concerns me, than the spike.)

We see the number of goroutines explode on most nodes. The worst hit (our "-3" node), was 10x:
![image](https://user-images.githubusercontent.com/53838718/110846206-817c6900-8279-11eb-8506-7102f1a3b0c4.png)

But we don't see CPU usage move at all. If anything, it goes down:
![image](https://user-images.githubusercontent.com/53838718/110846527-dc15c500-8279-11eb-8eff-f1a481c2c384.png)
(This graph sums user+system+iowait CPU, for the same VM as used above, the "-3" node. But the story is the same across the cluster.)

We don't think we were overtaxing the system with I/O, either, as that crashes during the outage:
![image](https://user-images.githubusercontent.com/53838718/110846819-39aa1180-827a-11eb-9f59-1facec0dd8ec.png)
(Disk read on this host)

One of the things we paid attention to during the recovery was replicas with leaders & leaseholders. Leaseholders (which I only barely understand) crashes right at the start of the outage.

![image](https://user-images.githubusercontent.com/53838718/110847346-d1a7fb00-827a-11eb-8122-93c5d0403ab2.png)

and it took a long while to recover. Replica "quiescence" acted similarly: crash to 0, and a long, long recover.

We're looking for anything that might help us understand this failure mode, as it results in a complete outage of the DB, essentially.

**To Reproduce**

This is part of the problem: we've wedged this particular DB twice thus far, and are yet no closer to understanding why, or how. It seems possible that it is load-related, but load doesn't seem sufficient to explain the symptoms. The logs don't really contain (to me, as a user of the database) enough information to really piece together whatever it is we're doing wrong.

**Environment:**
 - CockroachDB version [e.g. 2.0.x] v20.1.5-742a96f9ac2c5965
 - Server OS: Linux; Azure AKS VM.
 - Client app [e.g. `cockroach sql`, JDBC, ...] `cockroach sql` + a Rust client (not sure which library)

**Comment by rafiss** [comment]
@roy-work this will be a bit tricky to figure out without a reliable way to reproduce the issue (and I know reproducing it is not easy), but we'll keep this report in mind.

Just for your information, the DB console has a network latency page that shows the latency between nodes (https://www.cockroachlabs.com/docs/v20.2/ui-network-latency-page). If it happens again, I'd be curious to know if that page agrees with your manual `ping` test.

**Comment by roy-work** [comment]
This is the statistic that we recorded as `cockroachdb.round_trip.latency`:
![image](https://user-images.githubusercontent.com/53838718/112061314-b10e5980-8b34-11eb-8186-20eace034535.png)
(That there is a spike right about at the start of my outage is a bit curious, but I'm still unsure if it is related.)

**Comment by lunevalex** [comment]
@roy-work there have been a number of improvements in this area of the DB, so upgrading to the latest point release of at least 20.2 or 21.1 would be a good idea.
