### ISSUE TITLE
build,bazel: gather some data on how long certain build tasks take

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#61875]
This should include:

1) A fully clean build, i.e., after `make clean`, clearing out build caches, etc.
2) A no-op build
3) A couple scripted incremental builds, e.g., after making a small change to a `.go` or `.proto` file

Gathering data for both `cockroach` and `cockroach-short` is probably a good move. To whatever extent possible, gathering the same info for the Bazel build is a good idea.

Context: Our current build telemetry is lacking, and we'd like to get a baseline for build performance that we can weigh Bazel against moving forward.

Epic CRDB-8350

Jira issue: CRDB-2720

**Comment by knz** [comment]
For tracking https://docs.google.com/spreadsheets/d/1Ehww3mYXxgK1hrsnVZqk9j-NRT0vhgXXWNvkcNlttqk/edit

**Comment by rickystewart** [comment]
Closing stale item, we collected this data at the beginning of last year as we were comparing Bazel to `make`.
