### ISSUE TITLE
cli: Command to retrieve the http-port of a running node.

### ISSUE THREAD

**Issue by uptimeDBA** [cockroachdb/cockroach#6188]
Using beta-20160414 on Linux 64 with a 3 node cluster running in insecure mode on a single host.

There doesn’t seem to be a command to retrieve the http-port of a running node. 

Neither the `status` or the `ls` options of the `cockroach node` command shows this information. The `ps -ef | grep cockroach` command will show the http-port argument if originally supplied however.

Maybe add the port number to the `cockroach node ls` command?

**Comment by petermattis** [comment]
@uptimeDBA Thanks for the report. You're correct that there is not currently a mechanism to determine to retrieve the http-port of a running node. But adding this to `cockroach node ls` may not be appropriate. For one, `cockroach node ls

**Comment by petermattis** [comment]
Oops, sent too soon. Let me edit that.

**Comment by uptimeDBA** [comment]
Thanks @petermattis No point in trying to improve a temporary situation. I'll keep an eye out for the eventual solution. I'll close this.
