### ISSUE TITLE
sql: broken tests in Bazel

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#61919]
We are making a lot of progress in the migration from make to Bazel. Before we can complete our migration, we need to make sure that all tests in-tree continue to pass when run inside of the Bazel sandbox. The following tests are broken when run in the Bazel sandbox:

    pkg/sql/opt/memo:memo_test
    pkg/sql/opt/norm:norm_test
    pkg/sql/opt/xform:xform_test

Please help us by doing the following:

* Reproduce the failure locally; for example, with `bazel test pkg/sql/opt/xform:xform_test`, and consult the test logs to see what went wrong
* Identify the root cause of the failure
* If you are able, repair the failure such that the test passes, and submit a PR removing the `broken_in_bazel` tag from the test (see the linked documentation below)
* If not, take your findings to #bazel in Slack, and we’ll work with you to figure out how we can get the tests working

Helpful documentation:
* [How to ensure your tests can run in the Bazel sandbox (consider starting here!)](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/1553172016/How+to+ensure+your+tests+can+run+in+the+Bazel+sandbox)
* [How to ensure your code builds with Bazel](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/1380090083/How+to+ensure+your+code+builds+with+Bazel)
* [A user's guide to Bazel](https://docs.bazel.build/versions/4.0.0/guide.html)

**Comment by RaduBerinde** [comment]
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //pkg/sql/opt/xform:xform_test
-----------------------------------------------------------------------------
I210312 19:29:22.191994 1 (gostd) rand.go:92  [-] 1  random seed: -539133880944181066
--- FAIL: TestExternal (0.18s)
    test_log_scope.go:73: test logs captured to: /tmp/logTestExternal363374037
    test_log_scope.go:74: use -show-logs to present logs inline
    --- FAIL: TestExternal/postgis-tutorial (0.00s)
        opt_tester.go:1331: open pkg/sql/opt/testutils/opttester/testfixtures/postgis_tutorial_schema: no such file or directory
    --- FAIL: TestExternal/postgis-tutorial-idx (0.00s)
        opt_tester.go:1331: open pkg/sql/opt/testutils/opttester/testfixtures/postgis_tutorial_schema_indexes: no such file or directory
    --- FAIL: TestExternal/tpcc (0.00s)
        opt_tester.go:1331: open pkg/sql/opt/testutils/opttester/testfixtures/tpcc_schema: no such file or directory
    --- FAIL: TestExternal/tpcc-later-stats (0.00s)
        opt_tester.go:1331: open pkg/sql/opt/testutils/opttester/testfixtures/tpcc_schema: no such file or directory
    --- FAIL: TestExternal/tpcc-no-stats (0.00s)
        opt_tester.go:1331: open pkg/sql/opt/testutils/opttester/testfixtures/tpcc_schema: no such file or directory
    --- FAIL: TestExternal/tpce (0.00s)
        opt_tester.go:1331: open pkg/sql/opt/testutils/opttester/testfixtures/tpce_schema: no such file or directory
    --- FAIL: TestExternal/tpce-no-stats (0.00s)
        opt_tester.go:1331: open pkg/sql/opt/testutils/opttester/testfixtures/tpce_schema: no such file or directory
    --- FAIL: TestExternal/tpch (0.00s)
        opt_tester.go:1331: open pkg/sql/opt/testutils/opttester/testfixtures/tpch_schema: no such file or directory
    --- FAIL: TestExternal/tpch-no-stats (0.00s)
        opt_tester.go:1331: open pkg/sql/opt/testutils/opttester/testfixtures/tpch_schema: no such file or directory
    --- FAIL: TestExternal/ycsb (0.00s)
        opt_tester.go:1331: open pkg/sql/opt/testutils/opttester/testfixtures/ycsb_schema: no such file or directory
    optimizer_test.go:219: -- test log scope end --
FAIL
```

Will follow the docs to add the missing deps.

**Comment by RaduBerinde** [comment]
Adding the files still doesn't work. I think it's because of how we come up with the path:
https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/opt/testutils/opttester/opt_tester.go#L1325

**Comment by RaduBerinde** [comment]
Any suggestions for how a test can open a test fixture file from another package? How can we come up with the correct path?

**Comment by rickystewart** [comment]
If you give me a little more context about exactly what you need to do (which files you need to access, etc.), I can give you more specific advice, but generally you want to make sure that file's included in the `data` for your test. You can call into `bazel.Runfile()` to get the path to the file.

Commit `3457f760c496449016be8655524ec86f23e5be40` is an example of this (it's linked in that documentation).

**Comment by RaduBerinde** [comment]
Ah, that's exactly what I needed, thanks!
