### ISSUE TITLE
kvserver: broken tests in Bazel

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#61914]
We are making a lot of progress in the migration from make to Bazel. Before we can complete our migration, we need to make sure that all tests in-tree continue to pass when run inside of the Bazel sandbox. The following tests are broken when run in the Bazel sandbox:

    pkg/base:base_test
    pkg/internal/codeowners:codeowners_test
    pkg/internal/team:team_test
    pkg/kv/kvserver:kvserver_test
    pkg/server:server_test
    pkg/server/debug/goroutineui:goroutineui_test
    

Please help us by doing the following:

* Reproduce the failure locally; for example, with bazel test `bazel test pkg/base:base_test`, and consult the test logs to see what went wrong
* Identify the root cause of the failure
* If you are able, repair the failure such that the test passes, and submit a PR removing the `broken_in_bazel` tag from the test (see the linked documentation below)
* If not, take your findings to #bazel in Slack, and we’ll work with you to figure out how we can get the tests working

Helpful documentation:
* [How to ensure your tests can run in the Bazel sandbox (consider starting here!)](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/1553172016/How+to+ensure+your+tests+can+run+in+the+Bazel+sandbox)
* [How to ensure your code builds with Bazel](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/1380090083/How+to+ensure+your+code+builds+with+Bazel)
* [A user's guide to Bazel](https://docs.bazel.build/versions/4.0.0/guide.html)

**Comment by erikgrinaker** [comment]
Some of these failed with Protobuf C++ build errors. Ignoring `/usr/local` in the sandbox fixed the initial build errors, but now seems to fail on a linker error. Appears related to #61938.

```
$ bazel test pkg/base:base_test --sandbox_block_path=/usr/local
dyld: Symbol not found: __ZN6google8protobuf8compiler16GeneratorContext34OpenForInsertWithGeneratedCodeInfoERKNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEESB_RKNS0_17GeneratedCodeInfoE
  Referenced from: /private/var/tmp/_bazel_erik/c667c1907e11b48a9f931e987da29e9b/sandbox/darwin-sandbox/1065/execroot/cockroach/bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/protoc
  Expected in: flat namespace
 in /private/var/tmp/_bazel_erik/c667c1907e11b48a9f931e987da29e9b/sandbox/darwin-sandbox/1065/execroot/cockroach/bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/protoc
```

**Comment by tbg** [comment]
FWIW `bazel test pkg/base:base_test` works on my (linux) machine.

**Comment by tbg** [comment]
and then for kvserver here's my [old friend](https://github.com/cockroachdb/dev-inf/issues/307) again (I am using ccache again, maybe that's why)

```
$ bazel test pkg/kv/kvserver:kvserver_test
ERROR: /home/tobias/go/src/github.com/cockroachdb/cockroach/pkg/geo/geoproj/BUILD.bazel:3:11: in go_library rule //pkg/geo/geoproj:geoproj: 
Traceback (most recent call last):
	File "/home/tobias/.cache/bazel/_bazel_tobias/6e5ce29cb3e014d96edb4813c6e15043/external/io_bazel_rules_go/go/private/rules/library.bzl", line 38, column 25, in _go_library_impl
		archive = go.archive(go, source)
	File "/home/tobias/.cache/bazel/_bazel_tobias/6e5ce29cb3e014d96edb4813c6e15043/external/io_bazel_rules_go/go/private/actions/archive.bzl", line 82, column 28, in emit_archive
		cgo = cgo_configure(
	File "/home/tobias/.cache/bazel/_bazel_tobias/6e5ce29cb3e014d96edb4813c6e15043/external/io_bazel_rules_go/go/private/rules/cgo.bzl", line 112, column 31, in cgo_configure
		cc_libs = _cc_libs(d)
	File "/home/tobias/.cache/bazel/_bazel_tobias/6e5ce29cb3e014d96edb4813c6e15043/external/io_bazel_rules_go/go/private/rules/cgo.bzl", line 191, column 67, in _cc_libs
		libraries_to_link = as_iterable(target[CcInfo].linking_context.libraries_to_link)
Error: 'LinkingContext' value has no field or method 'libraries_to_link'
ERROR: Analysis of target '//pkg/kv/kvserver:kvserver_test' failed; build aborted: Analysis of target '//pkg/geo/geoproj:geoproj' failed
INFO: Elapsed time: 0.100s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    Fetching @com_github_elastic_gosigar; fetching
    Fetching @go_googleapis; fetching
    Fetching @com_github_axiomhq_hyperloglog; fetching
```

**Comment by erikgrinaker** [comment]
Good call, will try running them with the `cockroachdb/bazel` Docker image.

**Comment by erikgrinaker** [comment]
Works in Docker, and I get the actual test failure now. 👍 Will fix.

```
--- FAIL: TestValidateAddrs (5.14s)
    --- FAIL: TestValidateAddrs/5/{:postgresql__:http__:postgresql_} (0.00s)
        addr_validation_test.go:169: expected error "", got invalid --advertise-addr: address tcp/postgresql: unknown port
```

**Comment by rickystewart** [comment]
Manifests a little differently on my Macbook, FWIW:

```
=== RUN   TestValidateAddrs
    addr_validation_test.go:47: lookup RickyS’s-MacBook-Pro: no such host
```

(What "matters" for this bug is what happens in the Docker container, so you can focus on that for now, but just throwing it out there in case it's useful.)

**Comment by erikgrinaker** [comment]
Yeah, it was just `/etc/services` missing -- needs the `netbase` package in the Docker image. I'll submit a PR shortly, just have the `kvserver` test left.
