### ISSUE TITLE
Logical OR is too slow for JSONB field

### ISSUE THREAD

**Issue by kovalit** [cockroachdb/cockroach#61943]
JSONB field indexing does not work for logical OR operation
```
SELECT id FROM products WHERE properties->'width' = '100' OR properties->'width' = '200'
```
execution time: 108s

However,

```
SELECT id FROM products Where properties->'width' = '200'
UNION
SELECT id FROM products Where properties->'width' = '100'
```
execution time: 20ms

```
SELECT id FROM products WHERE properties->'width' = '100' AND  properties->'width' = '200'
```
execution time: 20ms

   
Table: products
id, name, properties 

1, product1, {"width": 100}
2, product2, {"width": 200}
...

**Environment:**
Cockroach: v20.2.2

**Comment by jordanlewis** [comment]
Hi @kovalit,

In 20.2, we didn't support efficient disjunction of constraints on inverted indexes. This will be supported in 21.1, and we expect that this type of query will become much faster as a result.

If you like, you can test your use case out on our development/alpha branch. You can download that here: https://www.cockroachlabs.com/docs/dev/install-cockroachdb-linux.html 

I'll close this for now, but please don't hesitate to comment again if you have more questions.
