### ISSUE TITLE
cli: remove `exterminate`

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#6197]
`./cockroach exterminate` is broken (or at least racy):

```
node drained and shutdown: ok

Error: cli/start.go:284: unable to destroy store []=cockroach-data: IO error: lock cockroach-data/LOCK: Resource temporarily unavailable
Failed running "exterminate"
```

We should rip it out for now and replace it with a more sophisticated command for decommissioning a node (see #6198).

**Comment by BramGruneir** [comment]
I was hoping to use `exterminate` in the acceptance tests.  Specifically in a test for repairing that I'm in the middle of working on.
