### ISSUE TITLE
changefeed: An option to exclude deletes from being emitted

### ISSUE THREAD

**Issue by chriscasano** [cockroachdb/cockroach#61971]
This feature request is for ignoring deletes from being emitted in a changefeed.  If a table is being used as a queue for in a workload such as an outbox pattern, these delete records will be abundant and unnecessary for the workload.  Here’s s a better description of the use case:

“A microservice writes a transaction to two tables (state and outbox). The state table persists the state of the data (insert, update, delete), while the outbox is an insert only queue that is used to ACK the transaction back to the originating service. The changefeed is utilized for sending back acknowledgment from the outbox table. Once acknowledged, the outbox record is deleted for good.”

Jira issue: CRDB-2706

**Comment by shermanCRL** [comment]
I might go a little further here, something like `WITH deletes='yes|no|only'`

`yes` = default, the status quo. Deletes are included.
`no` = deletes are filtered out of the changefeed
`only` = the changefeed _only_ emits deletes

cc @cockroachdb/cdc

**Comment by ajwerner** [comment]
We could push this option down into the KV-level rangefeed API (and ought to).

**Comment by shermanCRL** [comment]
Chatted with the team bit, it appears that filtering deletes vs inserts vs updates are approximately the same effort. Is that accurate @ajwerner @miretskiy @HonoreDB?

If so, we might generalize this to be something like:

`WITH omit='insert|update|delete'`

...and just cover all the bases while we are in the neighborhood.

**Comment by ajwerner** [comment]
Filtering deletes can be done very cheaply but filtering inserts or updates will necessitate expensive work because you need the previous values. The delete filtering could be pushed all the way into the rangefeed cheaply.

**Comment by shermanCRL** [comment]
> Filtering deletes can be done very cheaply but filtering inserts or updates will necessitate expensive work because you need the previous values. The delete filtering could be pushed all the way into the rangefeed cheaply.

Cool, helpful. We might decide that the expense is worth it to support insert & delete, would be a product call.

I wonder if such support would degrade the _default_ experience (i.e. no omissions). My intuition says a naive implication might, but a little thinking could make it “free if you’re not using it”.

**Comment by miretskiy** [comment]
We probably should push as much as we can to rangefeed -- if it's cheap (i.e. deletes); anything more than that -- I would err on the side of changefeed doing the filtering.  Basically, anything that requires interpretation of key/values -- something that KV server does not do, would probably be a more difficult proposition.

**Comment by ajwerner** [comment]
Deletion is a property only of the new value whereas insert and update is a property of both the old and new value.

**Comment by shermanCRL** [comment]
See also https://github.com/cockroachdb/cockroach/issues/78340

**Comment by amruss** [comment]
https://github.com/cockroachdb/cockroach/pull/82562
