### ISSUE TITLE
./cockroach node ls doesn't list all nodes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#6199]
Running `./cockroach node ls` is supposed to return the IDs of all nodes in the cluster. Currently, it always returns just the ID of the first node, at least on a local cluster:

**1. Start first node of local cluster:**
```
JESSEs-MBP:cockroach jesseseldess$ ./cockroach start
build:     beta-20160407-313-g234e580 @ 2016/04/20 15:12:51 (go1.6)
admin:     http://localhost:8080
sql:       postgresql://root@localhost:26257?sslmode=disable
logs:      cockroach-data/logs
store[0]:  path=cockroach-data
```

**2. Start second node:**
```
JESSEs-MBP:cockroach jesseseldess$ ./cockroach start --store=cockroach-data1 --port=26258 --http-port=8081 join=localhost:26257
build:     beta-20160407-313-g234e580 @ 2016/04/20 15:12:51 (go1.6)
admin:     http://localhost:8081
sql:       postgresql://root@localhost:26258?sslmode=disable
logs:      cockroach-data1/logs
store[0]:  path=cockroach-data1
```

**3. Try to get node IDs:**
```
JESSEs-MBP:cockroach jesseseldess$ ./cockroach node ls
+----+
| id |
+----+
|  1 |
+----+
```

**Comment by cuongdo** [comment]
The command line for the second node is missing the `--` before the `join=localhost:26257`. This is certainly a usability bug. Mind filing another issue for that or morphing this issue into that?

**Comment by jseldess** [comment]
Thanks for catching that, @cuongdo. `./cockroach node ls` does in fact work when adding nodes correctly ;). I'll close this and open another issue about returning an error when someone makes this type of common mistake.
