### ISSUE TITLE
Rebalance range replica. Only fully-replicated ranges may be rebalanced.

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#620]
Keep a rebalance queue in memory. Range replicas are added to the queue from a store during range scan according to certain conditions:

* Replica not matching zone config. When zone config changes happen, all ranges are scanned by each store and any mismatched replicas are added to the queue.

* Store is overweight in terms of size or range count.

* Rebalance away from stores finding themselves in top N space utilized, taking care to account for fewer than N stores in cluster. Only stores finding themselves in the top N space utilized set may have rebalances in effect.

**Comment by spencerkimball** [comment]
@mrtracy, would you care to create a follow on issue, or issues, for what else needs to be done for beta. Perhaps improvements to the heuristics, as necessary.
