### ISSUE TITLE
release-20.2: sql: ALTER DATABASE ... OWNER TO broken if name requires quoting

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#62012]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

```sql
CREATE DATABASE "order";
CREATE ROLE ajwerner;
ALTER DATABASE "order" OWNER TO ajwerner;
```

```
ERROR: database "\"order\"" does not exist
SQLSTATE: 3D000
```

Reproduced on 20.2.5. Does not seem to happen on master.

**Comment by rafiss** [comment]
We'll track down when this got fixed and backport it if possible.

**Comment by otan** [comment]
fixed by https://github.com/cockroachdb/cockroach/commit/5cc6900b486
