### ISSUE TITLE
cli: no error message when incorrectly joining node to existing cluster

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#6201]
When you try to add a node to a cluster, if you use `join` instead of `--join`, you start up a new cluster rather than join to the existing cluster. In such a case, it would be helpful to the user to return an error about the `--join` flag.

**1. Start first node of cluster:**

```
JESSEs-MBP:cockroach jesseseldess$ ./cockroach start
build:     beta-20160407-313-g234e580 @ 2016/04/20 15:12:51 (go1.6)
admin:     http://localhost:8080
sql:       postgresql://root@localhost:26257?sslmode=disable
logs:      cockroach-data/logs
store[0]:  path=cockroach-data
```

**2. Start second node:**

```
JESSEs-MBP:cockroach jesseseldess$ ./cockroach start --store=cockroach-data1 --port=26258 --http-port=8081 join=localhost:26257
build:     beta-20160407-313-g234e580 @ 2016/04/20 15:12:51 (go1.6)
admin:     http://localhost:8081
sql:       postgresql://root@localhost:26258?sslmode=disable
logs:      cockroach-data1/logs
store[0]:  path=cockroach-data1
```

Second node is started, but you might not be aware that it's not connected to the exiting cluster, which is obviously the intention when using `--join`.

**Comment by knz** [comment]
Fixed via  #12901.
