### ISSUE TITLE
kv: Better tooling for performing range/replica-level actions manually

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#62014]
**Is your feature request related to a problem? Please describe.**
If a cluster is in a bad state and the user knows an action that would help with that state (move a replica, transfer the lease, split, merge, inhibit Raft campaigning) we should have tools that the person triaging the issue can use to take those actions in a SAFE manner.

And example is a hot node, where moving a replica off that node and/or transferring he lease could spread the load out.

**Describe the solution you'd like**
* De-experimentalize the replica moving tool
* More tools to do the above

**Describe alternatives you've considered**
* UI based solution where you could select a range / replica and take N action on it
* We should also think through how we enforce safety of the tools -- either we say unsafe, we disallow unsafe operations, or we have some sort of automated check

**Additional context**
* Need to figure out the right UX here and what tools we want. Each tool can / should be its own project.

Jira issue: CRDB-2694

**Comment by lunevalex** [comment]
Relates to #54971 and
