### ISSUE TITLE
sql: Drop zone configurations on indexes that will be GCed, to avoid problems in the GC path

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#62029]
#61751 identified an issue where indexes which were queued for GC (in that case, because of a PK change) would still have their zone configs intact.  This caused a problem in the index GC code as the necessary infrastructure wasn't in-place to drop the zone configurations at GC time and a panic ensued.  #61751 addressed this problem, specifically for REGIONAL BY ROW tables, by cleaning up the zone configurations as part of the schema change job which queued up the index for GC.  

We need a more general fix however, for tables which can get into this state organically (i.e. not through the use of the new MR abstractions).  

Since this issue has the potential to bring down a node in the index GC job, I'm marking it as a 21.1 GA blocker.

**Comment by ajwerner** [comment]
This is a newly important bug because we did not support partitioning by user-defined types in 20.2.
