### ISSUE TITLE
server, ui: add a median/%-ile timeseries aggregator

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#6202]
Mentioned here: #5728 and also mentioned in conversation by @dt 

It might be useful to get the 50th or 95th percentile for a particular value when aggregating over nodes.

Especially as clusters grow in size, this could be useful for identifying problems without allowing single misbehaving nodes to dominate the metrics.

Median itself is nicer than average in that it's less volatile and (for odd numbers of nodes) the value will be a real node value and could have an associated node id for reference.

See also #6177 and the suggestion for a top-k aggregator, and associating node ids with values.

Jira issue: CRDB-6187

**Comment by tschottdorf** [comment]
It's probably obvious, but will never get tired of pointing out that the maximum is really the one that must always pop up prominently.

> identifying problems without allowing single misbehaving nodes to dominate the metrics.

The single misbehaving node *should* dominate the metrics, but it shouldn't make it impossible to find out how the other nodes are doing (hence the suggestions in #6177).

**Comment by knz** [comment]
@piyush-singh @dhartunian is this issue still current?
