### ISSUE TITLE
roachtest: version-upgrade tests pull binaries from s3 and cause failures when s3 is not available

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#62069]
The `version-upgrade` tests fetch multiple cockroach version binaries from S3.

If S3 has a transient problem, this causes the roachtest to fail (e.g. #61859) .

We should either put the binaries on a caching server "closer" to the CI agent (i.e. a variant of https://github.com/cockroachdb/dev-inf/issues/39 ) 

or properly interpret a failure to download the binaries with a server error 5xx (not 4xx!) as a skipped test, with a warning to the test maintainer to do something if the error persists.

cc @tbg @rickystewart for triage

Epic DEVINF-109

Jira issue: CRDB-2686

**Comment by srosenberg** [comment]
The binaries are now served via a CDN backed by a gcs bucket, closing.
