### ISSUE TITLE
sql: support tuple comparisons

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#6206]
Postgres supports comparing between tuples (semantically it's a lexicographical ordering):

```sql
SELECT * FROM t;
 k | a | b | c 
---+---+---+---
 1 | 1 | 2 | 3
 2 | 1 | 2 | 4
 3 | 1 | 3 | 0
 4 | 2 | 1 | 0
(4 rows)

SELECT * FROM t WHERE (a,b,c) > (1,2,3);
 k | a | b | c 
---+---+---+---
 2 | 1 | 2 | 4
 3 | 1 | 3 | 0
 4 | 2 | 1 | 0
(3 rows)
```

This can be useful for example when reading parts of a multi-column index. We don't support this (`pq: unsupported comparison operator: <tuple> < <tuple>`). To get the same behavior, the expression needs to be tediously rewritten:
```sql
SELECT * FROM t WHERE a > 1 OR (a = 1 AND (b > 2 OR (b = 2 AND c > 3)));
+---+---+---+---+
| k | a | b | c |
+---+---+---+---+
| 2 | 1 | 2 | 4 |
| 3 | 1 | 3 | 0 |
| 4 | 2 | 1 | 0 |
+---+---+---+---+
```

Note that we do support tuple equality/inequality.

**Comment by RaduBerinde** [comment]
IMO we should keep it open until we support generating the indexConstratints correctly as well.

**Comment by RaduBerinde** [comment]
@mjibson can you write down the missing things in an issue so we don't forget? you can assign to me

**Comment by mjibson** [comment]
@RaduBerinde missing things? As in, missing from the tuple index work like prefixes and multidirectional indexes?

**Comment by RaduBerinde** [comment]
Yes. https://reviewable.io/reviews/cockroachdb/cockroach/6332#-KGJIIp1oTsVDBQBBxbu:-KGMldgac0G5vDqit-YU:-1177103587
