### ISSUE TITLE
sql: CREATE TYPE IF NOT EXISTS should return a SQL Notice if the table already exists

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#62074]
**Describe the problem**

Currently, when creating a type with the IF NOT EXISTS option, the operation simply no-ops if the type already exists. Postgres doesn't offer an IF NOT EXISTS variant for CREATE TYPE, but for the CREATE TABLE version the operation returns a notice acknowledging the no-op -- we should do the same for CREATE TYPE IF NOT EXISTS, and return a notice if the type already exits.

**To Reproduce**

```
demo@127.0.0.1:26257/movr> CREATE TYPE typ AS ENUM();
CREATE TYPE

Time: 4ms total (execution 4ms / network 0ms)

demo@127.0.0.1:26257/movr> CREATE TYPE IF NOT EXISTS typ AS ENUM();
CREATE TYPE

Time: 1ms total (execution 1ms / network 0ms)

demo@127.0.0.1:26257/movr>
```

**Comment by mneverov** [comment]
hi, i'd like to work on this
