### ISSUE TITLE
import: pgdump import fail with error `reference table "public.film" not found in tables being imported`

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#62090]
Latest 21.1 branch SHA `4a47e0e305cbdabf963f896c1cb571a28b34e63d`, importing a file that:
* Creates the table names "public.film"
* But then we get error later on `referenced table "public.film" not found in tables being imported`

From slack this is a FK constraint issue, but the table creation is in the dump file above where FKs are created. 

Asks here:
* Not have this happen in the first place, if it is truly a bug
* Better error message in general for FK violations in IMPORT -- ideally we point to the exact statement it's failing on. At the very least we should mention it's a FK Constraint statement it's failing on

Jira issue: CRDB-2678

**Comment by adityamaru** [comment]
i can't recall if this was looked at or not, but the repro steps in the issue description don't have enough information to piece together what was being discussed back then. Sorry Michael 😢 but if something like this comes up again it should go to @cockroachdb/sql-foundations
