### ISSUE TITLE
all: Limit file descriptor usage

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#6210]
It's currently pretty easy to DoS the server by making it run out of file descriptors, which results in a panic. We have three areas that can consume significant numbers of file descriptors: network servers, network clients, and rocksdb. 

RocksDB has a configurable limit on file descriptors, although it defaults to using 100% of the limit provided by the system and leaves no room for anything else. We should configure it to use a more reasonable limit (the lion's share should go to network connections).

For network operations, we should block rather than call `Accept` or `Dial` if doing so would put us too close to the limit (it's not ideal and we should complain loudly when we get into this state, but blocking is better than panicking). We should look into culling idle connections on both client and server side (this may need to live inside grpc, and may already be there).

Our docs should also recommend a high FD ulimit for production deployment (cockroachdb/docs#53); the defaults tend to be way too low for real servers. But it's good that we're running with a low ulimit on the beta clusters to uncover growth in FD usage.

**Comment by tamird** [comment]
This is probably worse now that #7562 is in. Culling connections will be helped by #7494.

**Comment by petermattis** [comment]
We should check for file descriptor limits and point to documentation on how to increase them.

**Comment by spencerkimball** [comment]
@bdarnell ping... I think we've addressed everything in this issue. Could you close if so and assign if not / remove the 1.0 milestone.
