### ISSUE TITLE
server: disable update check on circleci

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#6212]
Our registration stats are being skewed by the "clusters" run in our CI test suite. It looks like 10-12 tests run long enough to complete a registration in a typical run. We should disable this by either special-casing circleci or delaying the first ping until the cluster has been up for a few minutes.

**Comment by dt** [comment]
I think we should try to check as close to startup as possible, since that maximizes the chance the "new version available" message is actually seen. Skipping based on a env var seems reasonable though?

**Comment by bdarnell** [comment]
Yeah, an env var SGTM.
