### ISSUE TITLE
kv: gradual kv95 performance regression since December 1st

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#62156]
Several roachperf tests have shown a gradual performance decrease of about 10% since December 1st, e.g.: https://roachperf.crdb.dev/?filter=&view=kv95%2Fenc%3Dfalse%2Fnodes%3D1%2Fcpu%3D32&tab=gce

**Comment by erikgrinaker** [comment]
The majority of the performance drop happened between December 1st and January 1st, so I focused on this period. The drop followed an increase in performance between November 11-15, bringing it back to the previous baseline, so it's not too concerning but still indicative of possible performance gains.

I reran `kv95/enc=false/nodes=1/cpu=32` using CRDB `master` commits across December, at ~7 day intervals with 5 runs each. The median results show a gradual drop in performance of ~5.4%:

| Commit | Date | Ops/s | 
|--|--|--|
|ae509ad041|2020-12-01|83,185|
|0d1ae9cbc4|2020-12-08|81,173|
|cea9423745|2020-12-15|80,460|
|f0c7d6e154|2020-12-24|78,272|
|d7bbe00605|2021-01-01|78,719|

I then ran 3 CPU profiles about 1 minute into benchmark runs on each of these dates, and verified that all 3 profiles were equivalent. Below are flame graphs of the runs for 2020-12-01 and 2020-12-24:

<img width="1044" alt="2020-12-01" src="https://user-images.githubusercontent.com/644420/111881007-d40f0100-89ae-11eb-9170-1a6071117b53.png">

<img width="1052" alt="2020-12-24" src="https://user-images.githubusercontent.com/644420/111881011-d83b1e80-89ae-11eb-8ef5-0fad50ba8034.png">

The circled areas show the main difference, which grew gradually over the period. These are rooted in `connExecutor`, using `colexec.Materializer.Next`, and ending up mostly in `storage.MVCCScanToBytes`. Since these are not rooted in `pgwire`, I suspect these may possibly be internal non-client calls, but that's just a guess. `colexec.Materializer` is part of the new vectorized execution engine, which was enabled by default for all queries in #55713 on December 3rd.

Profiles:

* [kv95-2020-12-01.pprof.gz](https://github.com/cockroachdb/cockroach/files/6176145/kv95-2020-12-01.pprof.gz)
* [kv95-2020-12-08.pprof.gz](https://github.com/cockroachdb/cockroach/files/6176146/kv95-2020-12-08.pprof.gz)
* [kv95-2020-12-15.pprof.gz](https://github.com/cockroachdb/cockroach/files/6176147/kv95-2020-12-15.pprof.gz)
* [kv95-2020-12-24.pprof.gz](https://github.com/cockroachdb/cockroach/files/6176148/kv95-2020-12-24.pprof.gz)
* [kv95-2021-01-01.pprof.gz](https://github.com/cockroachdb/cockroach/files/6176149/kv95-2021-01-01.pprof.gz)

@yuzefovich @asubiotto This isn't very actionable, but is there anything that jumps out at you here? If not, we can hope that the optimizations for #62198 and #62078 will address this, and do another comparison of 20.2 and 21.1 when they land.

**Comment by yuzefovich** [comment]
Another somewhat notable change is on December 16th - 999533fa13cf7374eff61abce30464c63a16e4ae - this made it possible to run the mutations through the vectorized engine too. This could explain partially why we started seeing `colexec.Materializer` show up more frequently.

**Comment by erikgrinaker** [comment]
Thanks @yuzefovich, that'd make sense -- I saw a bunch of `upsertNode` entries in the traces. Will have a closer look.

**Comment by erikgrinaker** [comment]
I've looked into this again, and the difference shown in the flame graphs was introduced with #55713. This is one of the last significant differences between 20.2 and `master` for kv95 so it'd be worth exploring optimizations here.

From what I can tell, this is caused by `colexec.Materializer` generally being somewhat slower than `row.Fetcher` for single-row reads. Another significant difference is that `execinfra.Run` only took 1.7% cumulative CPU time before #55713 but 20.62% afterwards, although this is likely just caused by the code being structured differently.

I'm going to dig into this a little bit and see if I find anything, but would appreciate if someone from the SQL team could have a look as well.

Profiles:

* [profile-55713-pre.pprof.gz](https://github.com/cockroachdb/cockroach/files/6204854/profile-55713-pre.pprof.gz)
* [profile-55713-post.pprof.gz](https://github.com/cockroachdb/cockroach/files/6204853/profile-55713-post.pprof.gz)

**Comment by yuzefovich** [comment]
What is the current performance difference between 20.2 and master? With #55713 we do expect to see some slowdown (on the order of 2-3%) which we decided was acceptable. The slowdown comes from the fact that the vectorized engine does allocate a few more object (e.g. instead of a single `TableReader` it will create `Materializer -> ColBatchScan -> cFetcher`), and both the flow setup and the actual run become a bit slower; additional allocations will put a bit more pressure on the GC too. We tried to optimize the code as best we can (mostly by using `sync.Pool`s) to reuse the objects as much as possible, but we were unable to fully remove the perf hit.

I looked into the profiles for a bit, and nothing really stands out to me. On the graph `execinfra.Run` in both cases looks similar. I do see where your observation is coming from (on "pre"):
```
ROUTINE ======================== github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBase).Run in /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go
      20ms     24.63s (flat, cum) 23.17% of Total
         .          .    759:	//}
         .          .    760:	return outRow
         .          .    761:}
         .          .    762:
         .          .    763:// OutputTypes is part of the processor interface.
      20ms     22.82s    764:func (pb *ProcessorBase) OutputTypes() []*types.T {
         .      1.81s    765:	return pb.Out.OutputTypes
         .          .    766:}
         .          .    767:
         .          .    768:// Run is part of the processor interface.
         .          .    769:func (pb *ProcessorBase) Run(ctx context.Context) {
         .          .    770:	if pb.Out.output == nil {
ROUTINE ======================== github.com/cockroachdb/cockroach/pkg/sql/execinfra.Run in /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go
      40ms      1.81s (flat, cum)  1.70% of Total
         .          .    164:
         .          .    165:// Run reads records from the source and outputs them to the receiver, properly
         .          .    166:// draining the source of metadata and closing both the source and receiver.
         .          .    167://
         .          .    168:// src needs to have been Start()ed before calling this.
      10ms       10ms    169:func Run(ctx context.Context, src RowSource, dst RowReceiver) {
         .          .    170:	for {
         .      930ms    171:		row, meta := src.Next()
...
```
however, this is likely the code misalignment. Note how supposedly expensive `OutputTypes` is, this is definitely not the case.

I am concerned a bit about the some extra spans in the flame graph that you pointed out in the comment above in the image, but I don't have a good explanation for those, yet they seem reasonable, not like a waste or something. I'd guess they are likely due to different structure of the code, possibly because the way we propagate errors in the vectorized engine (via a panic-catch mechanism, that's why we have `CatchVectorizedRuntimeError`).

**Comment by erikgrinaker** [comment]
The current diff is 76,018 ops/s (20.2) vs 70,149 ops/s (master). However, there are a few other known slowdowns as well, e.g. from separated intents, tracing, and Pebble -- we're looking into those too.

I did a couple of kv95 runs before and after #55713, and they give basically the same result, so I think this is a red herring -- the difference in the profile is likely just due to structural changes. I guess we've picked all the low-hanging fruit, I'll follow up on a few other leads. Thanks for the input!

**Comment by tbg** [comment]
https://github.com/cockroachdb/cockroach/issues/62078#issuecomment-809315932 summarizes how master without locktable and without tracing is tracking closely with release-20.2, so there are diminishing returns beyond the already identified issues and we've decided to call it a day.
