### ISSUE TITLE
kv: want debugging tool able to send custom KV requests to range(s)

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#62169]
This came up in the context of needing to delete a troublesome large row from a table.
Generally, for poking, we should have a way to send arbitrary hand-crafted requests.

cc @lunevalex @sumeerbhola 

Jira issue: CRDB-2830

**Comment by ajwerner** [comment]
It would be utterly and completely terrifying on one level but ridiculously powerful on a different level to be able to construct a batch request and send it using a sql builtin. The `crdb_internal.pb_to_json` makes this feel very easy to accomplish. Just terrifying.

**Comment by sumeerbhola** [comment]
> It would be utterly and completely terrifying on one level but ridiculously powerful on a different level

In the context of table surgery, where this came up, any requests that can mutate state would be locked down under admin ACLs, and probably read requests would also require elevated privileges.

**Comment by ajwerner** [comment]
Sure. It should definitely be locked down to admins. I might go one further and lock it down to some other role that an admin can grant to itself but doesn't have by default. My concern is that some customers will think they know what they are doing and then create some bizarre situation which will be painful to debug later. I can see adding a separate system table that gets written to before doing one of these requests and also a loud log message as a way to keep a paper trail. 

There's a risk with any gating or writing before issuing the request that you'll render the feature useless in some cases.

**Comment by lunevalex** [comment]
It looks like this was implemented here #72732, closing.
