### ISSUE TITLE
release: Break-up/re-order production of a release artifact to reduce time-to-binary

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#62161]
If/when we want customers to use a custom binary or nightly to get out of an emergency, we want them to use a CI-build binary. Currently however our CI has a reputation of being slow, for a mixture of reasons. One big one though is the it both builds and runs tests, which are themselves slow, and also may flake, requiring a complete re-run, but the built binary isn't published anywhere until they all pass. When we urgently need a binary for a customer, this is a problem. In a recent incident, it was clocked at 3 hours from merge to binary available to customer. The fact that tests were usually run on the PR pre-merge adds to the frustration (though PR tests are not always the same).

Ideally we'd break this up so we first build and publish somewhere, then test, then update the publish to make it "latest" for the branch or whatever, but that that first step runs and completes before any tests so we could provide a URL at that point if needed. 

Down the line, Basel/caching might even get that first step into single digit minutes.

Epic DEVINF-156

Jira issue: CRDB-2833

**Comment by jlinder** [comment]
This has been completed. See RE-51.
