### ISSUE TITLE
sql: make all `sql.defaults` cluster settings public

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#62174]
**Describe the problem**

Currently, it seems that whether a cluster setting should be public (and therefore have docs associated with it) is rather arbitrary. Some examples of cluster settings that are currently not public, but I see no reason to stay as such, are:

```
sql.defaults.experimental_implicit_column_partitioning.enabled
sql.defaults.drop_enum_value.enabled
sql.defaults.experimental_hash_sharded_indexes.enabled
sql.defaults.locality_optimized_partitioned_index_scan.enabled
```

A bunch of these cluster settings seemed to be defined here: https://github.com/cockroachdb/cockroach/blob/054169b0f8ceee2a48cc08cdf8b58547ac23f427/pkg/sql/exec_util.go#L214

cc @vy-ton @rafiss 

Epic CRDB-2507

**Comment by m-Bilal** [comment]
Hi, I would like to work on this issue. As I understand, to make settings public, I need to capitalize the variable names, as
`var requireExplicitPrimaryKeysClusterMode` would be changed to `var RequireExplicitPrimaryKeysClusterMode`, for all settings variables. Is this correct and is there anything else that needs to be done? Thanks in advance!
