### ISSUE TITLE
Change key / end key in request to a more flexible list of key intervals

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#622]
Change key / end key in request to a more flexible list of key intervals to properly account for batch requests. This data is used for command queue, timestamp cache and response cache. Currently, key/end key is the union interval of all sub requests in a batch request, meaning there's less allowable concurrency in cases where keys affected by the batch are widely separated.

**Comment by tschottdorf** [comment]
this has been done as part of the batch refactors.
