### ISSUE TITLE
sql: valuesNode executes on creation, failing if preparing with placeholders

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#6225]
I must be missing something because this seems like it would have been caught a while ago. Currently a statement like `INSERT INTO d.T VALUES ($1::INT)` in `TestPGPreparedQuery` will fail because immediately after TypeChecking the values clause during the pgwire prepare phase, it will attempt to [execute](https://github.com/cockroachdb/cockroach/blob/master/sql/values.go#L73) the values expression without the populated placeholder. Without populated placeholders, evaluation of expressions will cause errors/panics for just about anything other than a single placeholder by itself. 

@RaduBerinde @knz is this a recent regression? If not, maybe its time to give `valuesNode` the same treatment as #5903.

**Comment by knz** [comment]
Probably a regression caused by #5309. Will look into it.
