### ISSUE TITLE
import: hangs with no feedback when cloud storage permissions are not correct

### ISSUE THREAD

**Issue by sheaffej** [cockroachdb/cockroach#62284]
When attempting to import a file from cloud storage, if the permissions are not correct to allow accessing the source files(s) the import statement hangs with no feedback.

Example with insufficient privileges:
```
j4@j4-demo-89p.gcp-us-west2.cockroachlabs.cloud:26257/defaultdb> import pgdump 'gs://crdb-backup-ase2/mydbdump.sql';

<hangs>
```

Example with sufficient privileges added to the cluster setting `cloudstorage.gs.defeault.key`:
```
j4@j4-demo-89p.gcp-us-west2.cockroachlabs.cloud:26257/defaultdb> import pgdump 'gs://crdb-backup-ase2/mydbdump.sql';
        job_id       |  status   | fraction_completed | rows  | index_entries |  bytes
---------------------+-----------+--------------------+-------+---------------+----------
  642666741816852483 | succeeded |                  1 | 59285 |             0 | 4207528
(1 row)

Time: 5.516s total (execution 5.489s / network 0.027s)
```

There is an error if the file does not exist.
```
j4@j4-demo-89p.gcp-us-west2.cockroachlabs.cloud:26257/defaultdb> import pgdump 'gs://crdb-backup-ase2/mydbdump_wrong_file.sql';
ERROR: gcs object does not exist: storage: object doesn't exist: external_storage: file doesn't exist
```

Epic CRDB-71

**Comment by adityamaru** [comment]
@sheaffej what version did you observe this behavior on?

**Comment by sheaffej** [comment]
@adityamaru I repro'd this on a CockroachCloud cluster, so on that date it would have been running 20.2.x. Do you need the minor version?

**Comment by DuskEagle** [comment]
Depending on the time of day that this behaviour was observed, the cluster would've been on either `v20.2.5` or `v20.2.6`. It was upgraded from `.5` to `.6` at 2021-03-19 17:11 UTC.

**Comment by adityamaru** [comment]
I tried this on `cockroach demo` v20.2.6 and it does seem to return an error if I don't have the cluster setting `cloudstorage.gs.default.key` set to anything. Could this be something specific to CockroachCloud?

```
root@127.0.0.1:63043/movr> import pgdump 'gs://crdb-backup-ase2/mydbdump.sql';
ERROR: googleapi: got HTTP response code 403 with body: <?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>adityamaru-cockroachlabs@cockroach-adityamaru.iam.gserviceaccount.com does not have storage.objects.get access to the Google Cloud Storage object.</Details></Error>
```

**Comment by sheaffej** [comment]
Perhaps. The customer for which I filed this on behalf is also on CockroachCloud.

**Comment by adityamaru** [comment]
Are we still seeing this? I'm inclined to close the issue if it is not reproducible?

**Comment by sheaffej** [comment]
@adityamaru I just tried this on my same demo cluster, which is now on version 21.1.9 and I do now receive a proper error when the bucket does not have the correct permissions. So it is not reproducing on the same cluster, upgraded to 21.1.9.

```
j4@j4-demo-89p.gcp-us-west2.cockroachlabs.cloud:26257/defaultdb> import pgdump 'gs://j4-demo-cc-storage/amp_ddl.crdb.sql';
ERROR: googleapi: got HTTP response code 403 with body: <?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>cockroachdb@cockroach-j4.iam.gserviceaccount.com does not have storage.objects.get access to the Google Cloud Storage object.</Details></Error>

j4@j4-demo-89p.gcp-us-west2.cockroachlabs.cloud:26257/defaultdb> select version();
                                          version
--------------------------------------------------------------------------------------------
  CockroachDB CCL v21.1.9 (x86_64-unknown-linux-gnu, built 2021/09/20 21:47:27, go1.15.14)
(1 row)

```

**Comment by adityamaru** [comment]
Awesome, thanks for trying it out. I'm closing this, for now, if we see it again then we can reopen and investigate.
