### ISSUE TITLE
*: CCL packages imported from test non-CCL packages

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#62327]
Test packages in pkg/ should not depend on pkg/ccl/...

The following packages are culprits (found using `bazel query "rdeps(//pkg/..., //pkg/ccl/...,1)"`). I've tried to assign owners where I can...

- [x] //pkg/workload/schemachange:schemachange_test (https://github.com/cockroachdb/cockroach/pull/62238/commits)
- [ ] //pkg/sql/tests:tests_test, //pkg/internal/sqlsmith:sqlsmith_test (these two have the same root cause, BACKUP/RESTORE support in `sqlsmith`)
- [ ] //pkg/sql:sql_test (`TestTelemetry`), @cockroachdb/sql-experience 
- [x] //pkg/server/diagnostics:diagnostics_test (@andy-kimball i think you introduced it but let me know if i should tag someone else) (https://github.com/cockroachdb/cockroach/pull/70132)

We should remove this dependency, then add a BUILD.bazel visibility rule to ensure the `ccl` package doesn't get imported outside of `pkg/ccl`. Diff:
```
diff --git a/pkg/ccl/BUILD.bazel b/pkg/ccl/BUILD.bazel
index c802b884a9..3f3ba78aac 100644
--- a/pkg/ccl/BUILD.bazel
+++ b/pkg/ccl/BUILD.bazel
@@ -4,7 +4,7 @@ go_library(
     name = "ccl",
     srcs = ["ccl_init.go"],
     importpath = "github.com/cockroachdb/cockroach/pkg/ccl",
-    visibility = ["//visibility:public"],
+    visibility = ["//pkg/ccl:__subpackages__"],
     deps = [
         "//pkg/ccl/backupccl",
         "//pkg/ccl/buildccl",
```

Jira issue: CRDB-2802

**Comment by yuzefovich** [comment]
@adityamaru, @pbardea could someone from BulkIO take a look at `//pkg/sql/tests:tests_test, //pkg/internal/sqlsmith:sqlsmith_test`? `sqlsmith` code calls `utilccl.TestingEnableEnterprise` in order to be able to support BACKUP/RESTORE in randomly generated queries, but I wonder whether with recent changes to our license (moving something into the Open Core) we still need it.

**Comment by knz** [comment]
this one: `//pkg/server/diagnostics:diagnostics_test`
is for observability infra, not server.
cc @dhartunian for triage.

**Comment by dhartunian** [comment]
Thx for the ping @knz I pushed up a PR to resolve.

**Comment by knz** [comment]
we've turned the page on this, see [internal discussion](https://cockroachlabs.slack.com/archives/C0366GQV668/p1693583288389899?thread_ts=1693583162.359029&cid=C0366GQV668).

It's still important to prevent CCL imports from non-test code though.
