### ISSUE TITLE
sql: add more functionality around TableDescriptor

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#6233]
There are a set of things we do frequently that could be moved in a structure around `TableDescriptor`:
- creating a map of `ColumnIDs` to table column index (e.g. `scanNode`, `rowFetcher`)
- creating a map of PK columns to be able to tell if a column is in the PK

See https://reviewable.io/reviews/cockroachdb/cockroach/6043#-KFFtzPggMv9faRheZUh

**Comment by vivekmenezes** [comment]
closing in favor of #22275
