### ISSUE TITLE
teamcity: possible http cookie / CSP misconfiguration

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#62333]
I was investigating why the TC home page did not load this morning (unrelated problem) and I saw this in my browser console:

![image](https://user-images.githubusercontent.com/642886/111968660-b13d3380-8af9-11eb-8d6b-c71ddcf4522c.png)
```
Cookie “spbce059749d61c1c247c303d0118d0d53” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite -3735697654665077295.js:16:223
```

and

```
Content Security Policy: The page’s settings blocked the loading of a resource at data: (“default-src”).
```

Is that something that we can configure on our end?

cc @jlinder for triage

Epic DEVINF-228

Jira issue: CRDB-2801

**Comment by rickystewart** [comment]
Upgrading TC would probably be the next step, and that's going to happen around May. Adding this to the backlog since no one is blocked, and we don't have a timeline on when Firefox will start rejecting the cookie.

**Comment by knz** [comment]
not encountered this again
