### ISSUE TITLE
Custom time range for specific panel

### ISSUE THREAD

**Issue by asieroyan** [cockroachdb/cockroach#62334]
Hello,

I have a custom Graph panel which takes the data from the PostgreSQL datasource and processes it in an external server before plotting it. The new data is from the future, and I would like to have a dashboard with a graph filled with the actual data with the dashboard time range (now - now-90d) and my custom graph with a future time range (i.e. now - now+30d).

Possible solutions I've already tried:
**1. Add a relative time in the PostgreSQL Datasource query options**: This solution seemed to be the one, but I need to take past data from the DB, so although the custom graph was correctly showing the future time range, no data was being queried and therefore no data was being processed.

**2. Editing graph.ts and module.ts in custom graph plugin**: I've been trying to set a manual time range in the code in order to get it set in the custom graph, but every change I've been making in methods buildFlotOptions(), addTimeAxis() and addXSeriesAxis() have no effect in the plot, it still takes the dashboard time range.

**3. Longer dashboard time range**: Setting the dashboard time range to now-90d - now+30d shows all the data I want, but the last 30d of the first graph and the first 90d of the second one are empty.

now-90d - now+30d time range display:
![github-request](https://user-images.githubusercontent.com/48553789/111974611-dd5bb300-8aff-11eb-8d23-cb4c6bc3cea7.png)

I also think it would be a great feature for Grafana being able to set custom time ranges natively for panels, so it can be easier to show a larger variety of data in the same dashboard.

Thank you for your help.

**Comment by dhartunian** [comment]
Hi @asieroyan it sounds like your issue might be meant for the Grafana project, not for CockroachDB. Can you confirm? Perhaps I'm missing something.
