### ISSUE TITLE
backupccl,importccl: job cleanup can fail on transient errors

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#62351]
Today, if job cleanup hits a transient error (e.g. temporary node unavailability) the job may fail in a state that requires manual cleanuup (since the automatic cleanup did not succeed). We have 2 options here:

- We can PAUSE the job on these failures (resumption should go back to REVERTing)
- We can retry the job cleanup automatically if we are certain that the failure is transient

Epic CRDB-8816

**Comment by adityamaru** [comment]
I believe this has been solved now that we always retry a job that fails during revert - https://github.com/cockroachdb/cockroach/pull/69300
