### ISSUE TITLE
kv: investigate kv95 performance after Feb 18

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#62359]
`kv95` performance dropped significantly on Feb 18, as seen here: https://roachperf.crdb.dev/?filter=&view=kv95%2Fenc%3Dfalse%2Fnodes%3D1%2Fcpu%3D32&tab=gce

The initial drop was investigated in #62148, and was due to tracing. This was solved by #61777 (verified by cherry-picking onto the culprit PR #59992), but performance did not fully recover, so there were other performance regressions in the period following Feb 18. We need to figure out what these are and get back to the pre-Feb 18 baseline.

**Comment by erikgrinaker** [comment]
I took some 30-second CPU profiles of `kv95/enc=false/nodes=1/cpu=32` at about 1 minute in, spaced at ~1 week intervals (except 2020-02-19 since we had a particularly large drop then). Used the last commit before the date.

* [profile-2021-02-14.pprof.gz](https://github.com/cockroachdb/cockroach/files/6189354/profile-2021-02-14.pprof.gz) @ 9969862335
* [profile-2021-02-19.pprof.gz](https://github.com/cockroachdb/cockroach/files/6189355/profile-2021-02-19.pprof.gz) @ 40a35fe78a
* [profile-2021-03-01.pprof.gz](https://github.com/cockroachdb/cockroach/files/6189356/profile-2021-03-01.pprof.gz) @ 8591a292d4
* [profile-2021-03-08.pprof.gz](https://github.com/cockroachdb/cockroach/files/6189357/profile-2021-03-08.pprof.gz) @ a69e6549a7
* [profile-2021-03-15.pprof.gz](https://github.com/cockroachdb/cockroach/files/6189358/profile-2021-03-15.pprof.gz) @ e09b93fe62
* [profile-2021-03-22.pprof.gz](https://github.com/cockroachdb/cockroach/files/6189359/profile-2021-03-22.pprof.gz) @ 893643b63e

View with e.g. `go tool pprof -http localhost:8000 <file>` → View → Flame Graph.

A few clear offenders stand out to me:

* 2021-02-19: `tracing.Span.GetRecording` (mostly gone again in next profile)
* 2021-02-19: `kvfollowerreadsccl.canSendToFollower` (under `DistSender`)
* 2021-03-15: `colbuilder.NewColOperator` → `tabledesc.NewBuilder` → protoutil.Clone`
* 2021-03-15: `colflow.batchInfoCollector.Next` with `kvfollowerreadsccl.canSendToFollower` again

Except for tracing, these all remain in the final profile, and we should be able to get some significant gains by addressing them.

**Comment by jordanlewis** [comment]
cc @postamar

**Comment by postamar** [comment]
Hi @erikgrinaker, I strongly suspect my offending change is responsible for a large of the performance deterioration, to the point where I recommend rerunning the benchmarks once https://github.com/cockroachdb/cockroach/pull/62388 is merged and backported, which should be soon.

**Comment by angelapwen** [comment]
@postamar We came to the same conclusion ourselves a bit ago (thanks to @stevendanna). Thank you and @jordanlewis for looking out!

**Comment by erikgrinaker** [comment]
#62465 and #62388 got us back to Feb 17-levels on kv95.

**Comment by jordanlewis** [comment]
Awesome, great job everyone!!
