### ISSUE TITLE
Backup mechanism taking infinite space and time

### ISSUE THREAD

**Issue by mescudi21** [cockroachdb/cockroach#62367]
**Problem**
We upgraded our CockroachDB to 20.2.5 version and use it inside k8s cluster. Main reason for upgrading to a new version was a backup mechanism in community version of Cockroach. Backup schedules worked perfectly, but at 16th of March it took full space at 2 nodes of db (we used nodelocal storage). After reading logs it was clear that backup was almost 150Gb, whilst our database takes only 6-7Gb. I contacted support@cockroachdb.zendesk.com and support said they couldn't reproduce the problem and gave advice to create an issue.

**To Reproduce**
We don't know how to reproduce it yet, but database metrics was fine except a burst at network and resources usage that time.

**Expected behavior**
It worked fine before 16th of March and backups took 5-6Gb of space. When tried to re-run backups manually with S3 compatible storage, we were expecting it would take exactly the space took by database, but it ran infinitely long and took ~200Gb when we decided to stop it.

**Additional data / screenshots**
Metrics output:
[cockroach-distributed-06.03-20.03.zip](https://github.com/cockroachdb/cockroach/files/6184210/cockroach-distributed-06.03-20.03.zip)
[cockroach-hardware-06.03-20.03.zip](https://github.com/cockroachdb/cockroach/files/6184211/cockroach-hardware-06.03-20.03.zip)
[cockroach-overview-06.03-20.03.zip](https://github.com/cockroachdb/cockroach/files/6184214/cockroach-overview-06.03-20.03.zip)

Screenshots of today's backup run:
<img width="1206" alt="Снимок экрана 2021-03-22 в 21 26 08" src="https://user-images.githubusercontent.com/17045632/112033828-07e15680-8b68-11eb-8325-4ed94935f08a.png">
<img width="1280" alt="Снимок экрана 2021-03-22 в 21 29 40" src="https://user-images.githubusercontent.com/17045632/112033833-09128380-8b68-11eb-80f2-bd7fc8c54f9d.png">
<img width="1277" alt="Снимок экрана 2021-03-22 в 21 36 34" src="https://user-images.githubusercontent.com/17045632/112033838-0a43b080-8b68-11eb-8d85-bbed582acfdd.png">
<img width="243" alt="Снимок экрана 2021-03-22 в 21 37 13" src="https://user-images.githubusercontent.com/17045632/112033846-0b74dd80-8b68-11eb-80b8-9ef332bcecaf.png">
<img width="243" alt="Снимок экрана 2021-03-22 в 21 40 42" src="https://user-images.githubusercontent.com/17045632/112033850-0c0d7400-8b68-11eb-9c22-3dfc4cbfbe94.png">
<img width="199" alt="Снимок экрана 2021-03-22 в 21 41 25" src="https://user-images.githubusercontent.com/17045632/112033853-0c0d7400-8b68-11eb-8a30-188358306222.png">

**Environment:**
 - CockroachDB version: 20.2.5
 - Server OS: AWS EKS EC2 machines/Amazon Linux 2
 - Client app: cockroach sql, golang based applications

**Additional context**
Backup mechanism is broken and we can't dump database to manipulate or alter tables bescause of risks. To stop backups from taking whole n-terabytes of data we cancel jobs. Also, `SHOW JOBS;` always runs very slowly, that's why we suspect that something is corrupted inside jobs engine.

gz#7891

Epic CRDB-8816

Jira issue: CRDB-2797

**Comment by dt** [comment]
Hi mescudi21, thanks for filing this.

This is very interesting: typically backups are _smaller_ than the stored data thanks to only backing up the current version, doing so in key-order and thus compressing very well, so something odd is going on here. One possible explanation is that it is writing some data to the destination, then hitting an error and trying again, leaving some orphaned data behind each time. I'd be interesting to look in the logs for repeated lines emitted by storageccl/export.go, particularly if they're repeating with the same keys. 

Another thing we could check, that would answer for sure if we're writing extra, orphaned files, would be to compare the listing of *.sst files in that bucket with what's recorded in the backup manifest checkpoint. If we observe that many of the files in the directory are not in the checkpoint manifest, we'd have our answer as to what is happening, if not why.

The manifest contains some metadata about the data being backed up, so if this is real production data, I would not share it here. If you want you could email me directly at david@cockroachlabs, or if you prefer to do this analysis yourself, here's the steps I'd follow:
a) copy the file `BACKUP-CHECKPOINT` to some other path in that s3 bucket, for example /testing and rename it to BACKUP_MANIFEST 
b) run `select path from [show backup files 's3://path/to/testing']` (note that we don't include "BACKUP_MANIFEST" -- it'll automatically look for that within the supplied path)
c) `aws s3 ls s3://path/to/backup | grep .sst`
If these look _close_ to the same, I'm not sure what's going on, but if the listing is much larger than the `show backup files` on the renamed checkpoint, then that's good indication it is errors and retries leading to orphaned files and tells us to look for what's causing retries.

**Comment by mescudi21** [comment]
Hello David.

I reproduced all the steps from a to c, and here's what I got: `show backup
files` command fails with weird error that S3 object does not exist. Also,
I didn't cancel yesterday's backup job and it took 954Gb of data at S3
bucket, so I think it would run forever if I didn't notice it. I copied the
BACKUP-CHECKPOINT files to the BACKUP_MANIFEST directory but it didn't help
in clarifying the cause of this issue. By the way, I discovered an
interesting thing that after moving BACKUP-CHECKPOINT files to
BACKUP_MANIFEST backup mechanism created new ones at the same root
directory of the bucket. I really appreciate the fact that I can send you
compressed BACKUP_MANIFEST and you'll help us solve this problem.

Thanks for your fast response and help. Here is a screenshot of the error
returned by `show backup files` and `s3 ls` output.

**Comment by daniel-crlabs** [comment]
The customer replied to us via the ticket, so I am adding this here for completeness. It seems they were able to create the backup, however, it seems a large table is causing this problem. Is this expected? See client's comments below I received via the ticket:

>I forgot to share a screen of some temp dir with ambiguous internal files and directories, can it affect a backup mechanism?
>Tried to test a backup mechanism on single table and seems like it works.
>We tried to backup each table inside our database to check if backup mechanism works on single tables. By the time we reached our biggest table, backup of table took 15 minutes and we stopped it because the process overlapped actual size of table (5.6Gb) and the size of backup was 15Gb. After dropping and re-creating that table backup of a whole database worked well and we accomplished couple backups with a 750Mb size, when the database is 2Gb. Now, backup mechanism works, but a question of "why a table with ~11kk~ size broke the whole backup mechanism?". Thank you for your fast responses and communication in order to resolve this issue. Issue can be closed, it seems like a problem was in an enormous size of table.

**Comment by dt** [comment]
Thanks @mescudi21 for sharing the backup manifest with me privately. With the help of @pbardea we were able to determine it listed fewer than 200 files. Meanwhile you showed in that screenshot that the bucket listed about 20k files! This makes me think my prior theory might explain this: we're exporting a file, but getting some sort of error and then retrying -- leaving the old file behind -- in a loop. Unfortunately I don't think the logs include the reason for retries by default, but we _do_ typically log `export [/Table...,/Table...)` from export.go each time we start exporting some range to a file. If you still have the logs it'd be interesting to count how many `export.go` lines you see -- i.e. is it anything like the 20k files you saw. If so, it's also be interesting to look at a tail of the logs to see if the majority of repeated lines mentioned the same `/Table/....` span being exported. Unfortunately I don't think we log _why_ we retry but we could at least get an idea of what level we were retrying at.
