### ISSUE TITLE
Allow atomic update batches to replace transactions where possible

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#624]
This means batching up BeginTransaction request with first batch via TxnSender. In the event BeginTransaction is the first request in the batch and EndTransaction is the last, we want to let the DistSender determine whether all are on the same range and if so, execute entire batch as a single batch command to the range. In all other cases, we split batch request at DistSender into individual requests.

In this context, revisit the handling of (potentially) range-spanning operations such as Scan, DeleteRange, InternalResolveIntent. Currently, these are wrapped in a txn in txn_coord_sender and re-sent using a one-off client.KV unless already in transactional context. This could be more transparently implemented by

* auto-wrapping all such operations in a Txn which is (usually) optimized away unless the cmd actually spans ranges
* carrying out InternalResolveIntent across ranges without a txn, which might be okay since resolving intents is best-effort and does not require transactional semantics (in fact, might be better off without)

**Comment by tschottdorf** [comment]
we have this except for some smaller TODOs which I'll track separately.
See #2141, #2406.
