### ISSUE TITLE
sql: MAX unable to derive type for parameter

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#6241]
(forking off the work on #6225)

the following query fails to prepare:

```sql
INSERT INTO t VALUES(MAX(42, $1))
```

with `prepare error: pq: unknown signature for MAX: MAX(int, parameter)`

cc @nvanbenschoten

**Comment by nvanbenschoten** [comment]
I believe this is a current limitation of our type system, and not actually related to the bug seen in #6225 (although when the typing system improves, #6225 would then be an issue). A better example that should currently trigger a panic because of that issue would be `INSERT INTO t VALUES(~$1)`.

**Comment by nvanbenschoten** [comment]
So after coming back to this it hit me that MAX is an aggregate function, so this was giving the right error. Still, I added a test in #6762 to verify that placeholders within variadic functions work correctly.
