### ISSUE TITLE
kvfollowerreadsccl: excessive overhead in canSendToFollower

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#62447]
As seen in #62359, `kvfollowerreadsccl.canSendToFollower` started using a significant amount of resources in the week before Feb 19. The following flame graph shows that this was via `DistSender.sendToReplicas`, with the majority of the time spent in `pgerror.Newf` via `checkEnterpriseEnabled`.

<img width="1413" alt="Screenshot 2021-03-23 at 13 45 06" src="https://user-images.githubusercontent.com/644420/112148385-1cf8cc80-8bde-11eb-913b-cfc361c825f5.png">

The offending PR was #59571, `kv95` benchmarks show a drop from 60712 ops/s to 55565 ops/s (median over 5 runs) for this commit.

**Comment by erikgrinaker** [comment]
Assigning this to @nvanbenschoten for now, since he submitted the original PR, but might pick this up myself when I have time.

**Comment by nvanbenschoten** [comment]
Nice find! I think what happened here is that we lifted the call to `checkEnterpriseEnabled` from after checking for a sufficient staleness to before, so we now hit it on all requests. My instinct is that we should both a) re-order the call to `checkEnterpriseEnabled` and b) make `checkEnterpriseEnabled` cheaper by avoiding heap allocations.
