### ISSUE TITLE
Warn users when they create a backup with interleaved tables or restore from a backup with interleaved 

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/cockroach#62466]
With the future removal of interleaved tables and indexes, backups with interleaved tables/indexes cannot be restored to a CockroachDB version where the interleaved feature is removed (planned for 21.2). To give users ample warning, we should warn users when they take a backup or restore a backup with interleaved usage prior to 21.2.

**Comment by vy-ton** [comment]
cc @mwang1026 @jordanlewis from the technical enablement feedbakc

**Comment by dt** [comment]
#63501
