### ISSUE TITLE
cockroach import: the `--log-ignored-statements="'location://badlog'"` statement requires weird quoting

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#62464]
for the `cockroach import pgdump` CLI command and the `--log-ignored-statements` option I had to use weird quoting to make it work. Just double quotes or just single quotes didn't work. I had to next single quotes within double quotes.

Maybe this is OK for now since we can document it but it's definitely not intuitive for the user.

Example: `--log-ignored-statements="'location://badlog'"`

**Comment by annezhu98** [comment]
By running tests on a local cluster, I believe the issue has already been resolved through some past PR, hence we will not open a new one.

**Comment by annezhu98** [comment]
By running tests on a local cluster, I believe the issue has already been resolved through some past PR, hence we will not open a new one.
