### ISSUE TITLE
kv: Break dependency from `kv` to `storage`

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#6246]
`kv` is not meant to depend on `storage`, but it currently does. This sometimes leads to import-cycle problems which are worked around by changes like #6223. 

The only thing in `kv` that needs `storage` is `LocalTestCluster` and one constant which could easily be moved to `base`. `LocalTestCluster` should either be deprecated in favor of `server.TestServer` or moved out of `kv` (probably to something like `testutils/localtestcluster`). It's public in the `kv` package because it's used in the `ts` package's tests. Porting those tests to `TestServer` is not trivial because they use the `Engine` which `LocalTestCluster` exposes but `TestServer` does not.

**Comment by RaduBerinde** [comment]
In my first iteration for #6459 I tried moving `LocalTestCluster` but there were quite a few dependencies on unexported `kv` stuff..

It is really unfortunate that go provides no facility for test-only code in one package to depend on test-only exports/code from another.

**Comment by RaduBerinde** [comment]
Ah no, I tried again and there was another problem - if we move it, the kv tests can't use it anymore:
```
package github.com/cockroachdb/cockroach/kv (test)
	imports github.com/cockroachdb/cockroach/testutils/localtestcluster
	imports github.com/cockroachdb/cockroach/kv
```
