### ISSUE TITLE
kvserver: investigate conformance to leaseholder preferences

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#62485]
**Describe the problem**

In a recent customer issue, a user was running the following topology:

region=us,dc=west:  n1, n2 
region=us,dc=east: n3, n4
region=eu,dc=central: n5, n6

The constraints specify one replica in a US region, and as well a leaseholder preference, meaning that n1-n4 were expected to hold all leases.

This was typically true, but during a maintenance event in us/west (where the region was taken offline) it was observed that leases would migrate to `eu`, which is unexpected as they could have moved to `us/east` instead, except if there hadn't been a replica in `us/east`, which is unexpected as well as you expect the replicas to spread out over the three regions.

Furthermore, once `us/west` came back online, the leases stayed in `eu`. The nodes in `eu` had to be restarted to reestablish the lease preferences.

**To Reproduce**

No reproduction - we should make one, following the script above.

**Expected behavior**
When `us/west` goes down, leases move to `us/east` in the long run. In the short run, leases may move to `eu` (since ranges don't necessarily have a replica in `us/east`, though they would once the stores in `us/west` are declared dead and rebalancing is initiated).

When `us/west` returns, in due time, no more leases should be held by nodes in `eu`.

**Additional data / screenshots**

Internal issue: https://github.com/cockroachlabs/support/issues/893

This occurred on 20.1.10, though the lease preference code remains largely unchanged in 21.1.

**Environment:**
 - CockroachDB version 20.1.10
 - Server OS: linux

**Additional context**

**Comment by lunevalex** [comment]
I spent sometime reproducing this and now have a pretty good picture of what happens. 
1. Nodes in us/west die
2. Nodes in both eu and us/east detect that us/west has died and will attempt to steal the lease. This would typically happen here https://github.com/cockroachdb/cockroach/blob/674140583b409cd0088cdfeb4943ebd66d03b248/pkg/kv/kvserver/replicate_queue.go#L355. 
3. Once either eu or us/east steal the lease they would put the replica through the replication queue, which results us going through the replace dead voter code path https://github.com/cockroachdb/cockroach/blob/674140583b409cd0088cdfeb4943ebd66d03b248/pkg/kv/kvserver/replicate_queue.go#L409. 
4. Once a replication is complete the replicate_queue will ask for a reenqueue
5. On this iteration the queue will try to do a rebalance, which will end up moving the lease back into preferences. https://github.com/cockroachdb/cockroach/blob/674140583b409cd0088cdfeb4943ebd66d03b248/pkg/kv/kvserver/replicate_queue.go#L1155

The cluster where this was observed first had 64MB ranges and 2MB/s recovery/snapshot rates and 47k replicas. This means that we would have to upreplicate somewhere between 500GB-1TB of data (47/3*64~1TB). With 4 nodes left at 2MB/S it means best case scenario the data was moving at 8MB/S through the cluster, which means it would take  17-34 hours to complete.

**Comment by lunevalex** [comment]
Leaseholder preferences are restored within one cycle of replication, so there is not much left to do here. The system makes the right trade off restoring availability first before transferring leases, and we are unlikely to change that.
