### ISSUE TITLE
sql: improve client.Batch creation on INSERT/DELETE/UPDATE

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#6248]
We currently perform a lot of allocations when constructing a `client.Batch` during INSERT/DELETE/UPDATE. For example, `Batch.CPut` performs allocations while marshaling values (via `client.marshalValue`), but those could be avoided if the caller marshaled directly into a `roachpb.Value`. We could also use chunk allocation to minimize the allocations necessary for `roachpb.Value.RawBytes`. `Batch.CPut` also performs ~3 allocations to create the `*roachpb.ConditionalPutRequest`, fill in the expected value (silliness is causing this to always be heap allocated) and to create the `client.KeyValue` for the result.

None of these should be too difficult to fix, though we need to coordinate any surgery with work such as #6211.

**Comment by petermattis** [comment]
We should check to see if this is still worthwhile.

**Comment by jordanlewis** [comment]
This is still a thing, though I think the number of allocations caused by this are still few compared to other sources.
