### ISSUE TITLE
utilccl: improve CheckEnterpriseEnabled performance

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#62489]
In #59571, `utilccl.CheckEnterpriseEnabled` was called much more often in the read path, via `kvfollowerreadsccl.canSendToFollower`. However, `CheckEnterpriseEnabled` has a couple of performance issues:

1. We're instantiating a `pgerror.Newf()` in `utilccl.check()` when enterprise features are unavailable -- this is often necessary because we include cluster-specific info in the error message, but is expensive. However, in this specific case the caller just needs to know if there was an error, not the actual error message, so we should provide a variant using a generic, static error message.

2. We're decoding the license (if any) on each call, see:

https://github.com/cockroachdb/cockroach/blob/c834bd84e974293fa5324d1a92cf00d8ab9f9141/pkg/ccl/utilccl/license_check.go#L120-L127

**Comment by nvanbenschoten** [comment]
Did we mean to label this as a GA-blocker? The performance of `CheckEnterpriseEnabled` did not regress in this release, did it? If not, then a fix for this will not qualify for a backport.

**Comment by erikgrinaker** [comment]
>Did we mean to label this as a GA-blocker?The performance of `CheckEnterpriseEnabled` did not regress in this release, did it?

I initially thought much of this code was new, but then realized it was present in 20.2 and earlier -- forgot to update the labels. However, I'd imagine follower reads might get pretty expensive because of this.

> If not, then a fix for this will not qualify for a backport.

Got it, thanks for the heads-up.
