### ISSUE TITLE
sql/pgwire: Erlang Connection Issues - epgsql connection issues

### ISSUE THREAD

**Issue by leonardb** [cockroachdb/cockroach#6249]
1. What version of CockroachDB are you using (`cockroach version`)?
   Build Tag:   beta-20160421
   Build Time:  2016/04/21 16:17:17
   Platform:    linux amd64
   Go Version:  go1.6
   C Compiler:  gcc 4.9.2
2. What operating system and processor architecture are you using?
   Ubuntu 14.04.4 LTS
   64-bit
3. What flags/environment variables did you pass to `cockroach start`?
   none

Please describe the issue you observed:
Initial connection is established, but server response does not include parameters used by the client.
1. What did you do?
   attempted to establish a connection
2. What did you expect to see?
   A valid connection
3. What did you see instead?

```
14:25:49.897 [error] gen_server <0.760.0> terminated with reason: no case clause matching false in pgsql_connection:initializing/2 line 207
14:25:50.156 [error] CRASH REPORT Process <0.760.0> with 0 neighbours exited with reason: no case clause matching false in pgsql_connection:initializing/2 line 207 in gen_server:terminate/7 line 804
14:25:50.394 [error] CRASH REPORT Process <0.758.0> with 0 neighbours exited with reason: {{{case_clause,false},[{pgsql_connection,initializing,2,[{file,"src/pgsql_connection.erl"},{line,207}]},{gen_fsm,handle_msg,7,[{file,"gen_fsm.erl"},{line,503}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_fsm,sync_send_event,[<0.759.0>,{connect,{127,0,0,1},"mydbuser","mypass",[{database,"testdb"},{host,{127,0,0,1}},{password,"mypass"},{port,26257},{timeout,20000},{username,"myuser"}]},infinity]}} in gen_server:init_it/6 line 330
```

At the above point, the epgsql client is extract variables from server response in order to determine which module to use for handling datetime, specifically the "integer_datetimes" key.

Standard Postgres 9.4 server returns:

```
       [{<<"application_name">>,<<>>},
         {<<"client_encoding">>,<<"UTF8">>},
         {<<"DateStyle">>,<<"ISO, MDY">>},
         {<<"integer_datetimes">>,<<"on">>},
         {<<"IntervalStyle">>,<<"postgres">>},
         {<<"is_superuser">>,<<"off">>},
         {<<"server_encoding">>,<<"UTF8">>},
         {<<"server_version">>,<<"9.4.7">>},
         {<<"session_authorization">>,<<"testdb">>},
         {<<"standard_conforming_strings">>,<<"on">>},
         {<<"TimeZone">>,<<"localtime">>}]
```

Connection to cockroachdb returns:

```
        [{<<"client_encoding">>,<<"UTF8">>},
         {<<"DateStyle">>,<<"ISO">>},
         {<<"server_version">>,<<"9.5.0">>}]
```

**Comment by bdarnell** [comment]
Thanks for the report. To help us test a fix for this (since I don't think anyone on the team speaks erlang), could you provide a simple "hello world" program to connect to a database and perform a query?

**Comment by leonardb** [comment]
Hi Ben,

A "simple" way to replicate.

https://github.com/SiftLogic/crdb

Requires Erlang installed and rebar3 (https://www.rebar3.org/)

It's about as simple as I can make it for a non-erlang user.

Requires:
1. A test database named 'test' with a single table
2. A user (with password) with read/write access to the database and table 
```
    CREATE TABLE test (test_id integer PRIMARY KEY, test_value text);
```

Build:

    $ rebar3 compile
    $ rebar3 escriptize
    
The build will create a single executable at _build/default/bin/crdb
based on the code in apps/crdb/src/crdb.erl which should be simple enough to follow.
    
    Example Usage:
    
    _build/default/bin/crdb --host=localhost --port=26258 --db=test --user=testuser --pass=testpass
    
    
```
Expected results (after hacking library to assume 'integer_datetimes' as 'on'):

INSERT: {ok,1}
SELECT: Columns: [{column,<<"test_id">>,int8,8,0,0},
              {column,<<"test_value">>,text,-1,0,0}] Values: [{<<"1">>,
                                                               <<"TEST">>}]
COUNT: Cols: [{column,<<"COUNT(*)">>,int8,8,0,0}] Values: [{<<"1">>}]
DELETE: {ok,1}
```

   Actual results:

```
$ _build/default/bin/crdb --host=localhost --port=26258 --db=test --user=testuser --pass=testpass
{"init terminating in do_boot",{{case_clause,false},[{pgsql_connection,initializing,2,[{file,"/opt/crdb/_build/default/lib/epgsql/src/pgsql_connection.erl"},{line,207}]},{gen_fsm,handle_msg,7,[{file,"gen_fsm.erl"},{line,503}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}}

```

The above error is being caused by the library requiring environment information from the connection which cockroachdb does not supply.

I have no idea if any other postgres clients require any of the supplied values.

From what I can gather these of from PQconninfo.

**Comment by petermattis** [comment]
Marking as Later because Erlang support isn't on the 1.0 roadmap. @leonardb It is possible this has been fixed with other ORM compatibility work.

**Comment by leonardb** [comment]
Hi Peter, I'll have a look when I have some time.

ORM Support may not be the correct tag though, as the crash was caused when the connection was not returning the same connection details a std psql connection would. This would affect any pgclient inspecting the return and expecting certain values.

**Comment by leonardb** [comment]
Just noticed 1.0 was released.

Built and retested. Issue is not longer there. Closing
