### ISSUE TITLE
storage: investigate YCSB/A regression starting Dec

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#62523]
**Describe the problem**

The ycsb/A/node=3 benchmark shows a performance regressions starting on December 23rd.  This regression coincides with an update of pebble to cockroachdb/pebble@f614b5ad0faa88f794548581b80ad05f99e044ba in cockroachdb/cockroach@4865d3068bfdae94dda3d8dd0127b448b12cd5e7:

https://roachperf.crdb.dev/?filter=&view=ycsb%2FA%2Fnodes%3D3&tab=gce

We've further manually run this benchmark on the commit directly proceeding the merge and the merge commit. The following is the median seen in that benchmark over 4 runs on each of the commits:

commit | read op/sec | write op/sec | total op/sec 
--------|-------------|-------------|-------------
7f0b87fe0d9e41de838ffa97c29d8f5976f20ed5 |8340.45 | 8338.7 | 16679.2
4865d3068bfdae94dda3d8dd0127b448b12cd5e7 |6925.85 | 6920.4 | 13846.25

**To Reproduce**

1. Build a cockroach binary on the relevant commit
2. Run roachtest with a command similar to: `bin/roachtest run 'ycsb/A/nodes=3$' --user danna --count 2 --cpu-quota 320 --cockroach ./cockroach-linux-2.6.32-gnu-amd64-7f0b87fe0d --workload bin.docker_amd64/workload`
3. See the workload logs in the artifacts folder.

**Comment by erikgrinaker** [comment]
This is likely caused by read compactions cockroachdb/pebble#1032. It may well be a reasonable tradeoff, but would like to get the Pebble team's take on it.
