### ISSUE TITLE
testing: run TPCC with PGBouncer

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#62529]
Configure PGBouncer to use CockroachDB as a backend, then make the workload connect to PGBouncer instead of CRDB directly.

Run PGBouncer in Transaction pooling mode: https://www.pgbouncer.org/features.html

The PGBouncer process can either be run on a CRDB node or on a separate node.

Some questions:
* Is there overhead in latency?
* Does it reduce functionality of some features or cause errors?

**Comment by RichardJCai** [comment]
https://github.com/RichardJCai/crdb-pgbouncer/blob/main/README.md wrote up tutorial on using PGBouncer with CRDB

Created docs issue here: https://github.com/cockroachdb/docs/issues/10222

Also to summarize TPCC performance testing. On a 3 node roachprod cluster, I found that using PGBouncer with HAProxy vs just using HAProxy alone made very little difference in the performance.  Tested TPCC with 1-10 warehouses.

In addition, testing with up to 10000 idle connections also saw no difference.

Connection pool sizes of 100 and 200 for PGBouncer were tested.
