### ISSUE TITLE
testing: analyze heap dump and resource usage of idle connection test

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#62525]
We will report the overhead of idle connections in terms of mem/cpu usage per connection (approximately).

We need to first understand the behavior we are seeing where idle connections use memory, but the memory usage doesn't go down after closing them, and then the memory usage *also* does not increase when recreating more connections later.

During the testing, also test with different numbers of prepared statements on each connection, to see how that affects memory usage.

**Comment by RichardJCai** [comment]
Following up on the memory usage seemingly not going down after the connections are killed, seems like a go issue.
https://github.com/golang/go/issues/42330

We can analyze memory according to the go profile.

**Comment by rafiss** [comment]
Should we file an issue for the docs team to add more details here: https://www.cockroachlabs.com/docs/v20.2/ui-hardware-dashboard#memory-usage

And maybe even link to that golang issue

**Comment by RichardJCai** [comment]
> Should we file an issue for the docs team to add more details here: https://www.cockroachlabs.com/docs/v20.2/ui-hardware-dashboard#memory-usage
> 
> And maybe even link to that golang issue

https://github.com/cockroachdb/docs/issues/10192
Created issue here.

**Comment by RichardJCai** [comment]
Also created repo sharing scripts / steps for connection testing.

https://github.com/RichardJCai/crdb_connection_testing/

**Comment by RichardJCai** [comment]
Closing this with a rough summary here:

## Resources used by idle connection:
### Memory: 
#### On v20.2.6
28000 is the limit for socket connections on the VM.
According to go’s heap profile, the overhead of ~28000 connections uses 590mb. (heap profile reports 650mb used total when the connections are created, 60mb used total after the connections are shut down).

Node 1 with 28230 connections reports 650mb used in the profile, node 3 with no connections reports ~60mbs used (quite different from trial 2).

Connections: 28230

This roughly gives us 590mb/28230 = 0.02107142857 mb per connection 
**= 21071.42857 bytes per connection.**

Trial 2:
Node 3 with no connections: 22104.25kb 
Node 1 with 28230 connections: 666.84mbs.

666.84mbs/28230 = 0.02362167906 mb per connection 
**= 23621.67906 per connection**

On v21.1.0.beta-1
Node 3 with 0 connections spunup reports 20119.94kB used.
Node 1 with 28230 connections reports 802.24MB total.

802.24MB/28230 = 0.02841799504 mb per connection 
**= 28417.99504 bytes per connection**

Trial 2
Node 3 with no connections: 26427.18kb 
Node 1 with 28230 connections: 809.12MB

809.12/28230 = 0.0286617074 mb per connection
**= 28661.7074 bytes per connection**

## Resources used for “active” connections 
Active connection means connection with transaction open:
##### On v20.2.6 
Trial 1:
Node 3 with no connections: 23129.33kb
Node 1 with 28230 connections: 919.65mb

0.03257704569 mb per connection
**32577.04569 bytes per connection**

Trial 2:
Node 3 with no connections: 25573.81kb
Node 1 with 28230 connections: 924.17mb

On v21.1.0.beta-1

Trial 1:
Node 3 with no connections: 30007.70kb
Node 1 with 28230 connections: 1068.22 mbs.

0.03783988664 mb per conn
**37839.88664 bytes per conn**

Trial 2:
Node 3 with no connections: 23323.96kb
Node 1 with 28230 connections: 956.49 mb
