### ISSUE TITLE
roachtest: add flag to control number of connections; idle and active

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#62526]
Add a flag to the TPCC workload to control the number of connections. Currently it just uses a connection pool with a hardcoded number (50) connections per pool, and one pool per node.

Making this more configurable can help us come up with an estimate for optimal number of active connections with respect to cluster core count.

**Comment by RichardJCai** [comment]
Closed via https://github.com/cockroachdb/cockroach/pull/62740
