### ISSUE TITLE
backupccl: warn on restore if any incremental layer has any non-public spans

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#62565]
As described in https://github.com/cockroachdb/cockroach/issues/62564, an incremental backup of non-public spans (e.g. an index that was being added) may miss historical writes.

On the restoration of backups that include non-public spans in the incremental chain, we should producing a warning.

**Comment by mwang1026** [comment]
Should be any offline descriptor -- IMPORT, RESTORE, index backfill

**Comment by mwang1026** [comment]
Just confirming that when we say `non-public spans in the incremental chain` that includes the full backup as well.

Full backups alone are fine, even in the state where they backed up non-public spans.

Once there's *any* incremental taken to create or add to an existing chain where ANY of the backups in that chain has non-public index or table can get you into the bad state.

**Comment by dt** [comment]
Closing as done by #62701. We don't handle importing tables with that but there's nothing to validate them against. Also, with the fixes to backup backported, this is a thing of the past anyway.
