### ISSUE TITLE
core changefeed doesn't work

### ISSUE THREAD

**Issue by carr123** [cockroachdb/cockroach#62583]
cockroach verison 20.2.6 linux amd64.
3 nodes cluster. NOT enterprise edition.

i do the followind thing,  but receive no feeds,
i issued insert, update commands on another console, no feeds received.
but when i truncate the table, feeds arrived.

SET CLUSTER SETTING kv.rangefeed.enabled = true;
CREATE TABLE foo (a INT PRIMARY KEY);
INSERT INTO foo VALUES (0);
EXPERIMENTAL CHANGEFEED FOR foo; (after this, console blocked).

does core changefeed not work on 3 nodes cluster ?

**Comment by mwang1026** [comment]
Just confirming -- when you started your SQL client did you have the `--format=csv` option?

https://www.cockroachlabs.com/docs/v20.2/changefeed-for.html#create-a-changefeed (See the note after scrolling down a bit from this link)

**Comment by carr123** [comment]
thanks
