### ISSUE TITLE
Export/Import SQL Script doesn't work

### ISSUE THREAD

**Issue by ThomasLohmann** [cockroachdb/cockroach#62593]
Hi everyone, 

we exported our whole database via "cockroach dump" to get a SQL Script which we then want to import into dbdiagram.io. But we get multiple errors which we need to refactor manually. That's quite time-consuming. Any idea how we can create a clean SQL Script out of CockroachDB which can then be imported into any DBDesigner without errors? So far, we tried Cockroach Dump, DBeaver and PgAdmin to export the SQL Script and we tried dbdiagram.io and dbdesigner.net to import the SQL Script. Maybe Liquibase or Flyway could be another option.

[https://photos.app.goo.gl/ngJYEBu6LrffhYCq5](url)

Best regards,
Thomas

**Comment by rafiss** [comment]
Hi @ThomasLohmann! I see that you have been discussing this here too https://cockroachdb.slack.com/archives/CP4D9LD5F/p1616671915122300

I would agree with the discussion from that thread -- I recommend contacting dbdiagram.io or DBDesigner or whichever other visualization tool you try and asking them if they can support the syntax that CockroachDB is returning. Unfortunately, I don't have a good recommendation for a different alternative you could try, but I'll keep your use case in mind!

**Comment by ThomasLohmann** [comment]
@rafiss, it would be great if you can also check some other db designer tools. Because it might be helpful for all users of CockroachDB to export a SQL Script and import it to have a clean database design. I tested dbdigram.io and dbdesigner.net so far. Both provide errors. Maybe you have some other tools in mind which support CockroachDB with any errors?

Best regards,
Thomas

**Comment by rafiss** [comment]
I'm going to close this, since there isn't any work within CockroachDB for this, but I invite further discussion in the community Slack.
