### ISSUE TITLE
jobs: job page in DB Console didn't render when the jobs table was in a bad state

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#62666]
In https://github.com/cockroachlabs/support/issues/900 we had a very degenerate jobs table - there were single rows taking whole ranges (one was 1.5GB). There were also some 2500 jobs in total.
Under these conditions, the jobs page failed to render when it was needed most. I'm not sure how it was failing exactly as I wasn't seeing the screen - presumably timing out.

In such cases, any information instead of a timeout would be an improvement.

Jira issue: CRDB-2750

**Comment by ajwerner** [comment]
I wonder to what extent this (and other pages like it) would be a good candidates for some of the weaker-consistency reads we've been thinking about lately.

**Comment by ajwerner** [comment]
One note here is that loading an individual job currently requires scanning the entire jobs table. That's madness.

**Comment by amruss** [comment]
Is the problem here with the jobs table needing to be more queryable or with the queries the UI does needing to be more efficient?

**Comment by ajwerner** [comment]
> Is the problem here with the jobs table needing to be more queryable or with the queries the UI does needing to be more efficient?

Somewhere in the middle :/ 

I think the problem here is that the queries the UI uses leverage `crdb_internal.jobs` which does not expose the indexing features of the underlying table. I have a prototype to add a virtual index somewhere.

**Comment by ajwerner** [comment]
I think on some level we could benefit from multi-level virtual indexes.

**Comment by knz** [comment]
This issue has been addressed by rearchitecturing the job table to not do in-place writes (and use job_info instead).
