### ISSUE TITLE
ui: want alert on the front page about "stuck" jobs

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#62670]
In an incident yesterday it took too long to figure out that a backup had been running for ten days. One way or another, I think the front page of the console should loudly announce such a condition.

Related: #44895

Epic CRDB-915

Jira issue: CRDB-2748

**Comment by thtruo** [comment]
thanks @andreimatei!

cc @Annebirzin for awareness. this fits into our broader theme around surfacing more information within the DB Console for the 21.2 release cycle. it would be worthwhile for us to consider this alongside other general low hanging fruit usability improvements 

cc @nkodali and @nathanstilwell for Cluster UI visibility
