### ISSUE TITLE
Implement caching for Admin UI JS

### ISSUE THREAD

**Issue by jordan-thoms** [cockroachdb/cockroach#62708]
**Is your feature request related to a problem? Please describe.**
Loading the admin UI is frequently very slow for me. This is because the files are served with no-cache headers, which means that the browser will frequently have to download the entire JS bundle:
<img width="1078" alt="Screen Shot 2021-03-29 at 6 25 38 PM" src="https://user-images.githubusercontent.com/403810/112790693-69e81180-90bc-11eb-8224-e450f03b5e8c.png">

The connection to the cockroachdb admin from my local machine isn't super fast, however even on fast connections loading 25MB of JS is not going to be speedy.

**Describe the solution you'd like**
Pass cache-control headers which allow for long lived caching of the file, and cache bust using a query param or new filename when using a new version of cockroachdb. Also, why does the admin panel need 25MB of javascript - from a quick look at the generated bundles it looks like there's a lot of code which may not be needed.

**Additional context**
We're an enterprise customer.

Epic CC-5280

Jira issue: CRDB-2645

**Comment by dhartunian** [comment]
Thanks for filing this issue @jordan-thoms. Appreciate the detail and the screenshot!

We're in the midst of planning our next release at the moment and will be tackling some build issues in our UI. This might be a good issue to tackle as part of that effort.

**Comment by bryanhuntesl** [comment]
Also same issue here, slow connection, downloading 20MB of Javascript is crazy for something that needs to be operationally available. I cannot gain access to the admin GUI. Remote running cluster, slow wifi and VPN in play, pretty typical for corporate deployments. This Javascript needs to be solved. Still can't access it.


<img width="1646" alt="Screenshot 2021-05-05 at 15 41 31" src="https://user-images.githubusercontent.com/31992054/117160161-cbd12080-adb8-11eb-8d3c-14afbf65ecb5.png">

**Comment by jordan-thoms** [comment]
Yeah, if you are on a connection which imposes a timeout of e.g. 30s for file loads (which BTW seems to be the case for the documented way of accessing kubernetes-hosted deployments using `kubectl port-forward`) then this essentially makes the admin UI impossible to use.
