### ISSUE TITLE
Request related to Distsqlplan

### ISSUE THREAD

**Issue by nadirdbit** [cockroachdb/cockroach#62729]
When one runs an "explain analyze ...", link on external website is obtained like "https://cockroachdb.github.io/distsqlplan/decode.html#..."

It will assist in being able to view that output locally instead of accessing the internet to review this content.

Thank you.

Nadir Doctor

Jira issue: CRDB-2641

**Comment by RaduBerinde** [comment]
In the upcoming 21.1 release, explain analyze will show text output in addition to the link.

**Comment by nadirdbit** [comment]
Hi Radu, 

Appreciate the update - when is that estimated to be available?

This was noted in current build:
Build Tag:        v20.2.6
Build Time:       2021/03/15 18:07:11

Thank you.

Nadir Doctor

**Comment by RaduBerinde** [comment]
I think in about a month or so.

In the meantime, would having a local copy of the html and js files help? (you can just download them or I can put them in an archive). You would have to adjust the URLs you get to point to the local file.

Note that the plan data in the URL never leaves your browser (it is all processed locally).

**Comment by nadirdbit** [comment]
Hi Radu,

The reason for input of this enhancement request is that often database servers on-premise have firewall rules setup so that they can't directly access the internet due to stricter security safeguards. So having the explain analyze in HTML/XML output available locally will definitely assist here.

In case SQL statements utilize some hard-coded values in filter criteria instead of supplying them via parameters, then it will help in not being placed on an external website for better data privacy.

Thank you.

Nadir Doctor

**Comment by RaduBerinde** [comment]
> In case SQL statements utilize some hard-coded values in filter criteria instead of supplying them via parameters, then it will help in not being placed on an external website for better data privacy.

Note that the data in the URL is in the [URL fragment](https://en.wikipedia.org/wiki/URI_fragment) and won't be sent to the server. It is all processed locally in the browser.
