### ISSUE TITLE
prod: could not enter the Admin UI

### ISSUE THREAD

**Issue by jjzcru** [cockroachdb/cockroach#6273]
Please follow the steps below to help us help you.
1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. On most unix-based systems
   running with defaults, this boils down to the output of
   
    grep -F '[config]' cockroach-data/logs/cockroach.INFO
   
   When log files are not available, supply the output of `cockroach version`
   and all flags/environment variables passed to `cockroach start` instead.
2. Please describe the issue you observed:
- What did you do?
  I follow the tutorial on the website to install cockroach in docker, and execute the command start, but when i try to enter, it return ERR_CONNECTION_REFUSED.
- What did you expect to see?
  The webadmin
- What did you see instead?
  The Connection refuse message

**Comment by petermattis** [comment]
@JJzcru Which tutorial for installing cockroach using docker did you follow? The one on the [Install CockroachDB](https://www.cockroachlabs.com/docs/install-cockroachdb.html) page? Those instructions just deal with downloading the cockroachdb image. It would be helpful to send a transcript of what you typed in your terminal.

@jseldess The docker installation instructions are a bit confusing. The first command is:

```
$ docker pull cockroachdb/cockroach:beta-20160421
```

This will download the cockroachdb beta image. The second command is:

```
$ docker run -t -i cockroachdb/cockroach shell
```

This will download the `latest` image and run the `shell` command. I think it could be confusing to users that might expect this second command to have actually started a cockroach cluster. I think these instructions should make it clearer what the purpose of that second command is (or perhaps get rid of it) and to indicate that a cockroach cluster is not running at  this point.

**Comment by jseldess** [comment]
@petermattis, thanks for adding me. I'll rework the docker instructions as soon as I'm back in the office (next week).

**Comment by knz** [comment]
Hi @JJzcru, have you been able to alleviate the issue using peter's suggestion? Let us know if you see any changes with the beta version released since you first filed this issue.

**Comment by mrtracy** [comment]
@jseldess is this still relevant?  Seems like this is no longer active; if you aren't using this for your tracking go ahead and close it.

**Comment by jseldess** [comment]
Yeah, I updated that particular step so it's focused only on verifying that cockroachdb installed successfully. We have plenty of other issues to document better relating to docker, but this particular issue seems resolved.
