### ISSUE TITLE
roachtest: acceptance/bank/zerosum-splits failed [skipped]

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#62749]
Unclear why it's skipped; there's a tumultuous history for the test. Last failure I think was #53829 and the test was most recently skipped in #53833.

**Comment by andreimatei** [comment]
See #62751 for the skipped sibling `bank/zerosum-restart`.

**Comment by tbg** [comment]
Should we delete this test? kvnemesis does splits, checks invariants (and at a deeper level), and more.
