### ISSUE TITLE
acceptance: TestRepair is disabled

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#6277]
The following test appears to have failed:

[#16767](https://circleci.com/gh/cockroachdb/cockroach/16767):

```
I160425 12:08:09.470436 acceptance/dynamic_client.go:61  closing connection to 127.0.0.1:32870
I160425 12:08:09.472465 acceptance/dynamic_client.go:61  closing connection to 127.0.0.1:32866
I160425 12:08:09.573076 acceptance/cluster/localcluster.go:654  stopping
I160425 12:08:09.573318 acceptance/cluster/localcluster.go:552  event stream done, resetting...: net/http: request canceled
I160425 12:08:09.573340 acceptance/cluster/localcluster.go:575  events monitor exits
--- FAIL: TestRepair (13.02s)
    load.go:60: pq: context deadline exceeded
    load.go:60: pq: context deadline exceeded
=== RUN   TestDockerRuby
I160425 12:08:12.239890 acceptance/cluster/localcluster.go:289  Initializing Cluster ruby:
{"name":"ruby","nodes":[{"count":1,"stores":[{"count":1,"max_ranges":0}]}],"duration":5000000000}
I160425 12:08:12.242036 acceptance/cluster/docker.go:105  ImagePull cockroachdb/builder:20160305-182433 already exists
I160425 12:08:12.834232 acceptance/cluster/localcluster.go:586  creating certs (1024bit) in: /home/ubuntu/cockroach/.localcluster.certs.608664914
I160425 12:08:12.916363 acceptance/cluster/localcluster.go:537  events monitor starts
I160425 12:08:13.481800 acceptance/cluster/localcluster.go:485  *** started roach0 ***
  ui:        https://127.0.0.1:32871
--
--- SKIP: TestBuildBabyCluster (0.00s)
    terraform_test.go:30: only enabled during testing
=== RUN   TestFiveNodesAndWriters
--- SKIP: TestFiveNodesAndWriters (0.00s)
    util_test.go:68: running in docker mode
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```

Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment]
@BramGruneir, this is failing a lot - could you do something about it pass this on to someone?

**Comment by BramGruneir** [comment]
I'll disable it tonight and look at it next week.

**Comment by tamird** [comment]
This has been disabled for 3 months. It'd be good to prioritize it soon.

**Comment by tamird** [comment]
This issue is nearly 6 months old. @BramGruneir what's going on?

**Comment by BramGruneir** [comment]
I work on it in my spare time.  It was how I discovered the create table issue. a month and a bit ago.  I'll change the milestone.

**Comment by tamird** [comment]
No, please prioritize this or delete the test.

**Comment by BramGruneir** [comment]
This has been around way too long.  The test is clearly not needed.  I'll send a PR out to remove it.

**Comment by tamird** [comment]
How does this demonstrate that the test is not needed?

**Comment by BramGruneir** [comment]
It doesn't.  But this test isn't needed as we now have the testcluster which can perform the functions which were intended, at the time, to be performed within the acceptance tests.

**Comment by bdarnell** [comment]
The TestCluster gives us the infrastructure to do these tests, but do we actually have an equivalent for TestRepair anywhere? 

Also, the acceptance tests are not just for tests that can't be done anywhere else - they're also to verify that things work in the real world of multiple processes and real TCP connections, and we're not being fooled by a quirk of our in-process test environment. For example, in an acceptance test we can verify what happens when a server is killed abruptly by `SIGKILL`, which we can't really test with TestCluster. It may or may not be worthwhile to build that test and make it robust, of course.

**Comment by BramGruneir** [comment]
As it stands currently TestRepair was never completed.  When I originally wrote it, I had overly ambitious plans to add collections of loads and chaos agents to our acceptance tests and to generate a suite of tests.  This first test, with only a basic load and no chaos agent rarely worked correctly and became cumbersome to maintain.  

I do agree that it's still a good idea to add more to our suite of longer running acceptance tests, similar to the rebalance ones.  But I think a more direct approach is more prudent.  Isolate specific cases we're looking to test and build direct tests to handle them.
