### ISSUE TITLE
sql: multiregion validation does not check partition zone configs

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#62790]
In the `validateZoneConfigForMultiRegionTable(WasNotModifiedByUser)` function, we do not currently check that partitions have the correct zone configuration. We should probably do so.

**Comment by ajstorm** [comment]
Do you mean table partitions?  I thought that we had checking in place for index partitions.

**Comment by otan** [comment]
we had code, it wasn't tested and so...didn't work :P
