### ISSUE TITLE
storage: Freeze/Unfreeze stop-the-world Raft migrations

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#6284]
This is the first step of #6166.

Implement the `Freeze`/`Unfreeze` Raft commands suggested by @bdarnell in
\#5985: everything proposed between `Freeze` and `Unfreeze` applies as a
non-retryable error (and in particular, does not change state).

This opens the following (Raft) migration path:

* **apply** `Freeze` on all Replicas (`./cockroach drain --for-update`)
* stop all nodes
* replace the binary
* start all nodes (which applies `Unfreeze` on all Replicas).

Since the replaced binary will not have to apply Raft log entries proposed by
the previous binary (due to the active freeze), all is well.

This is implemented as a special drain mode (think `./cockroach drain
--for-update`) which carries out the no-client, passive mode drain described in
\#6283 and then has one task left: making sure that all Replicas in the cluster
have the `Freeze` command applied (at which point it announces that to the
command line and exits).

The user must execute the above command on all nodes in the cluster. Once all
nodes have successfully carried it out, the nodes can be terminated normally
(`./cockroach quit`).

Leader leases are not acquired for `Freeze`/`Unfreeze` commands. Raft
proposal forwarding will lead to proposing multiple copies of the command, but
that isn't an issue (a `Freeze` when frozen is a noop like all other commands;
an `Unfreeze` when not frozen is by definition a no-op. And since any starting
node unfreezes all of its replicas, recovery from any situation is
straightforward).

A process which boots up will unfreeze all ranges. This makes restarting the
cluster after the update simple. It does introduce the potential for user
error: A user might restart a new binary before shutting down the old nodes,
and that binary would then participate in the old (still running) Raft group.
However, in light of the more sophisticated RFC #6166 which will allow proper
online migrations for many changes, this seems acceptable.
We can also safe-guard against this by adding the proposing binary's version
number to `Unfreeze` which would cause those replicas running an old version to
panic.

**Comment by bdarnell** [comment]
I think the `Freeze` operation may need to be performed in stages: first on all the regular data ranges, then the meta2 ranges, and finally on the first range. If we lose the addressing information too soon we may not be able to finish the process.

**Comment by JackKrupansky** [comment]
Will the admin UI have visibility on the state of freeze for each node?

**Comment by JackKrupansky** [comment]
Once the restart of migrated nodes starts, is there something that prevents a

**Comment by tschottdorf** [comment]
@bdarnell Do we really need that? I agree that the Raft transport needs to resolve `nodeIDs` but I thought that was done through Gossip (which in turn means that we want to keep node info and first range gossipped). Can we get away with allowing leader lease acquisition for gossip purposes on the node that last held it? If there's something that actually needs the metadata, things are going to be more complicated because the current proposal gets away without synchronization between the nodes (all nodes simply try to freeze everything).

**Comment by bdarnell** [comment]
I don't think we want to allow leases to work after a freeze, so we need to at least keep the first node unfrozen until everything else is so it can gossip. I'm not sure if meta2 is necessary or not but it's the best listing we have of all the ranges that exist so I would expect we'd want to do a scan over meta2 to make sure that we've frozen all ranges.

**Comment by tschottdorf** [comment]
The node doesn't need the lease to gossip, we just make it get one to make sure we don't get all replicas chattering. If in that shutdown mode we just let the latest lease holder gossip, we should be alright.
Orchestrating shutdown like you suggest seems very tedious because you force nodes to shutdown in a certain order. My suggestion is to keep gossip alive (last-leader-gossips) and freezing all ranges. When that has completed on all nodes (as the operator checks manually) they can shut down the cluster and reboot with the new binary.

**Comment by bdarnell** [comment]
It seems simpler to me to iterate over the meta ranges and freeze range-by-range instead of a two-level system where you issue a drain command to every node and then a freeze command to every range on that node. We could even leverage the `DistSender` like we do for the consistency checker.

**Comment by tschottdorf** [comment]
Yeah, that may be true. I'll see what's there for the consistency checker and go from there.

**Comment by spencerkimball** [comment]
I'm unclear why this stop-the-world drain mode would be necessary with the changes proposed to move the bulk of command execution upstream of Raft. Care to color in a few motivating examples?

**Comment by bdarnell** [comment]
We need this to get to the new scheme. We may also need it in the future if we make any more changes downstream of raft (they'll be rare but still possible)

**Comment by tschottdorf** [comment]
What @bdarnell said. We'll hopefully not need this often (definitely for
(un)intentionally breaking version changes) with the RFC in, but that RFC
is a big chunk of work we shouldn't have to wait for (especially during
beta).

On Wed, Apr 27, 2016 at 1:51 PM Ben Darnell <notifications@github.com>
wrote:

> We need this to get to the new scheme. We may also need it in the future
> if we make any more changes downstream of raft (they'll be rare but still
> possible)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/6284#issuecomment-215169487>
>
-- 

-- Tobias

**Comment by tschottdorf** [comment]
We now have Freeze/Unfreeze implemented. What's lacking is a method which guarantees that all Replicas have applied the freeze - the current code guarantees that all Replicas have acknowledged it, which is sort of close, but not sufficient. Some options come to mind:

* Polling (from the ClusterFreeze admin command): This would have to reach out to all Stores (via all Nodes) and confirm that they're frozen (for example by obtaining the count of frozen vs unfrozen ranges).
* A better frozenWaitTrigger: The current trigger is the one described above and falls short of the guarantees. We could poll the other replicas from the trigger, for example by addressing them directly through an inconsistent read (which should fail given that they're frozen), or (but this is likely not going to happen) by augmenting Raft to record more information (i.e. `RaftStatus.Applied` for each follower).

Given the semantics of the freeze trigger, though, if the initial wait fails, a second round of Freeze will be a no-op (and so the trigger will not run again), inviting erroneously assuming that everything is a-ok. It's likely not hard to add code to the cluster command that performs a few round of RPCs to all (gossiped) nodes which waits for the number of unfrozen replicas to drop to zero. Do we need to worry about nodes flaking in and out of Gossip and making this check pass erroneously, though?

**Comment by bdarnell** [comment]
I prefer polling from the admin command to adding more logic in `frozenWaitTrigger`. It'll be more efficient (O(stores) instead of O(ranges)), and while we'll have to introduce new ways to address RPCs to stores/nodes, that work is also needed for rebalancing.

Additionally, this polling RPC can serve as a signal to the node that it's time to freeze, and it can do things that are unrelated to individual ranges (or it can act on "dead" ranges: maybe any unfrozen ranges should be handed to the `replicaGCQueue`, since they won't otherwise be touched by the freeze process. We might need to do this to ensure that there are no dead and unmigrated replicas left behind). 

We could avoid gossip flakiness by including the set of all required node/store IDs in `ChangeFreezeResponse`. Each range knows its replica locations (and this won't change again after the freeze).

**Comment by tschottdorf** [comment]
I think with #6598 in, we're ready on the technical side. Next up:

* shell out the actual user story. A button in the UI or a cli command or both? It's a fairly dramatic command, so whatever it is, it should have a safeguard.
* document that solution.
* @mberhault, can you use this from now on? Hit one node with this:
  ```
  curl -d '{"freeze": true}' http://localhost:8080/_admin/v1/cluster/freeze
  ```
  it should come back with a success telling you the number of affected ranges. If it comes back with an error, let me know. On error, you can try to recover with `"freeze": false` or just restart the cluster (but try to show me the messed up status first).

**Comment by bdarnell** [comment]
Potentially-destructive actions should for now only be in the CLI, not the UI - we don't have authentication worked out for the UI yet.

**Comment by tschottdorf** [comment]
Agreed. Can we fold this into the `quit` command?

* Rename quit -> shutdown
* Add `./cockroach shutdown --all-nodes`

I don't see the need for making explicit in the flag that this is a special mode for updates; the documentation should simply instruct users to explicitly use that mode. Or is that too risky (for people who don't follow that tutorial but instead expect the flags to be self-explanatory)? We could saveguard against that by augmenting the VERSION file (don't allow starting another version, unless overridden, when the VERSION file indicates that the last running version wasn't the same; the clean shutdown would remove the running version accordingly so that the next invocation wouldn't assert).
We could also name the flag `--prepare-update`, but I like highlighting that we're shutting down *all nodes* more than emphasizing that it's for an update.

Somewhat related, we will also want to expose the "drained mode" (in which the process keeps running and Raft works, but leadership is lost and SQL clients are refused). We can work `--drain` in there, but `shutdown --undrain` looks weird. Maybe that is best kept as a command, I just wanted to bring it up in case it inspires a good interface.

**Comment by bdarnell** [comment]
I don't think we can rely on `cockroach shutdown` for this. Real deployments will likely be running cockroach under some sort of process manager that will restart it if it fails, so the instructions have to be to freeze the cluster, then separately use your process manager to stop the nodes (`cockroach quit/shutdown` can be an option if you don't have a process manager) and perform the rest of the upgrade.

I'm also reluctant to make freezing a part of the standard upgrade procedure. Hopefully once we have leader-proposed raft we won't need to go through this process often (remember that the goal is online rolling upgrades).

**Comment by tschottdorf** [comment]
> I'm also reluctant to make freezing a part of the standard upgrade
procedure. Hopefully once we have leader-proposed raft we won't need to go
through this process often (remember that the goal is online rolling
upgrades).

Well, I mean standard for now. But I see what you're saying - should we
just add `./cockroach freeze-cluster` for now (which just hits the
endpoint)?


On Thu, May 12, 2016 at 2:19 PM Ben Darnell <notifications@github.com>
wrote:

> I don't think we can rely on cockroach shutdown for this. Real
> deployments will likely be running cockroach under some sort of process
> manager that will restart it if it fails, so the instructions have to be to
> freeze the cluster, then separately use your process manager to stop the
> nodes (cockroach quit/shutdown can be an option if you don't have a
> process manager) and perform the rest of the upgrade.
>
> I'm also reluctant to make freezing a part of the standard upgrade
> procedure. Hopefully once we have leader-proposed raft we won't need to go
> through this process often (remember that the goal is online rolling
> upgrades).
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/6284#issuecomment-218841857>
>
-- 

-- Tobias

**Comment by bdarnell** [comment]
Yeah, I think I'd just make an explicit freeze command for now.

**Comment by tschottdorf** [comment]
See #6675.

On Thu, May 12, 2016 at 4:06 PM Ben Darnell <notifications@github.com>
wrote:

> Yeah, I think I'd just make an explicit freeze command for now.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/6284#issuecomment-218870140>
>
-- 

-- Tobias

**Comment by tschottdorf** [comment]
Everything's there, closing. Note that we're not using this in our docs yet - looks like we want to mention it only when an update explicitly requires it.
