### ISSUE TITLE
sql: TRUNCATE and ongoing index builds are broken

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#62842]
**Describe the problem**

In 20.2 we changed the implementation of TRUNCATE to create all new indexes instead of creating a new table (https://github.com/cockroachdb/cockroach/pull/52235). This was wonderful in that it made table IDs stable. Unfortunately, it appears that that PR had some severe logic bugs in the face of concurrent index builds. 

The logic has two bugs around https://github.com/cockroachdb/cockroach/blob/d145e9fc02064a8b6b4179b5af7da5238b192f74/pkg/sql/truncate.go#L221-L227
The first is that it should make the in-progress indexes public prior to calculating the re-mapping. Secondly, it needs to deal with the ongoing jobs. 

**To Reproduce**

Create an index backfill which takes a long time and then truncate the table. The index will become public but this index will contain data from prior to the truncate. The job will also remain in the queue which will prevent subsequent schema changes. 

**Expected behavior**

The index is truncated and made public.

**Additional context**

This affects all current 20.2 versions and 21.1.

**Comment by ajwerner** [comment]
@fqazi any chance I can enlist you on this? I think the fix is small and the test should be straightforward. This is higher priority than anything else you're currently working on and I believe you have sufficient context.

**Comment by fqazi** [comment]
Sure I'll take it.

**Comment by ajwerner** [comment]
I took a stab at this https://github.com/cockroachdb/cockroach/pull/62944.

**Comment by ajwerner** [comment]
Alright, after some thinking about this implementation, there's still a lot of scary edge cases. For now the thinking is that we're going to disallow this hazardous behavior. It's modestly unfortunate as there are some cases which would have allowed you to quickly finish long-running schema changes that take a long time to cancel but getting this right in all of the cases seems too hard. Instead we'll allowlist the cases we can convince ourselves are safe and disallow the rest.

**Comment by ajwerner** [comment]
You can detect this situation in a cluster by running:

```sql
  WITH descs AS (
				SELECT d
				  FROM (
						SELECT crdb_internal.pb_to_json(
								'cockroach.sql.sqlbase.Descriptor',
								descriptor,
								false
						       )->'table' AS d
						  FROM system.descriptor
				       )
				 WHERE d IS NOT NULL
             ),
       bad_descs AS (
					SELECT d, idx
					  FROM (
							SELECT d,
							       d->'primaryIndex' AS pi,
							       json_array_elements(d->'indexes') AS idx
							  FROM descs
					       )
					 WHERE (pi->>'id')::INT8 > (idx->>'id')::INT8
                 )
SELECT database_name,
       schema_name,
       name AS table_name,
       table_id,
       idx->>'name' AS index_name,
       (idx->>'id')::INT8 AS index_id
  FROM crdb_internal.tables JOIN bad_descs ON (table_id = (d->>'id')::INT8);
```
