### ISSUE TITLE
sql: implement ALTER TABLE ... ALTER COLUMN SET [VISIBLE|NOT VISIBLE]

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#62892]
In #58923, we added the ability to set a column as VISIBLE and NOT VISIBLE.

We now need the ability to have `ALTER COLUMN <col> SET [VISIBLE|NOT VISIBLE]`.

The changes to do this are as follows (you can follow SET DEFAULT as a guideline for what to write)

* Add a `type AlterTableSetVisible struct { Visible bool }` struct to tree/alter_table.go, similar to `AlterTableSetDefault`.
* Add the syntax to sql.y.
* Add the logic to rewrite the column descriptor to change the value of `Hidden` in `alter_table.go`
* Add logic tests in `logic_test/alter_table`
* Submit your PR!

----

Allow for ALTER COLUMN <column_name> SET NOT VISIBLE.  When implemented, this statement will allow users to make their columns invisible.  This functionality is required if customers want to build their own REGIONAL BY ROW tables (using REGIONAL BY ROW AS) and have them look identically to how they'd be created by the system.

**Comment by kurokochin** [comment]
Hi, I'm new to cockroachdb, but I'm willing to give it a try for this, may I work on it?

**Comment by kurokochin** [comment]
Hi, I'm new to cockroachdb, but I'm willing to give it a try for this, can I work on it?

**Comment by kurokochin** [comment]
Hi, I'm new to cockroachdb, but I'm willing to give it a try, can I work on it?

**Comment by rafiss** [comment]
just checking: does https://github.com/cockroachdb/cockroach/pull/63052 close this?

**Comment by rafiss** [comment]
@ajstorm @otan does this need to be in 21.1?

**Comment by otan** [comment]
I think we're back porting this to 21.1.1

**Comment by ajstorm** [comment]
Yeah, that's right - 21.1.1.

Is there some place where we're keeping track of the deferred backports?

**Comment by rafiss** [comment]
@ajstorm The convention is to use the `backport-21.1.x` label (and so on) on the PR. I added that to https://github.com/cockroachdb/cockroach/pull/63052

However, that's not super easy to track, (as I posited in Slack https://cockroachlabs.slack.com/archives/C0HM2DZ34/p1618516063393000) so I'm  going to try to make https://backboard.crdb.dev/ understand these labels in some way

**Comment by otan** [comment]
This just needs backporting now.

**Comment by mgartner** [comment]
This was fixed by #63052. Closing.
