### ISSUE TITLE
Change Gossip to send only protobufs

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#629]

**Comment by tamird** [comment]
Brought here by #1633. What's the rationale here?

**Comment by bdarnell** [comment]
All the usual reasons for choosing protobufs over gob: it's better to be explicit about what's going over the wire and have clear forwards- and backwards-compatibility semantics, protobufs are faster, and it's consistent with everything else we do.

**Comment by tamird** [comment]
Are you sure protobufs are faster? My last benchmark suggested gob was
faster.

**Comment by bdarnell** [comment]
Your email from June 2 indicated that you were testing `golang/protobuf`, not `gogo/protobuf`. Gogo (with generated marshal/unmarshal functions) should be faster.

**Comment by petermattis** [comment]
In addition to Ben's other points, Gob is being used inappropriately here. Gob encoding/decoding is intended to be connection oriented. That is, you create a gob encode/decoder when the connection is opened and the encoder/decoder cache type info from the other side. They way gossip is using gob it is creating a new encoder/decoder each data needs to be sent/received. This usage pattern likely substantially reduces gob performance.

**Comment by thschroeter** [comment]
Happy to tackle this.

**Comment by tamird** [comment]
@thschroeter please do. Let me know if you have any questions.

**Comment by thschroeter** [comment]
@tamird, do you have a hint regarding encoding the polymorphic payload `Val` of [gossip.info](https://github.com/cockroachdb/cockroach/blob/master/gossip/info.go#L35)? 

Will try to use the `oneof` feature of protobuf and enumerate all concrete use cases. Looking at the call sites of `AddInfo`, `Val` is currently used to propagate `int64`, `string`, and `proto.StoreDescriptor`. I might be missing use cases, though.

I've defined a new `proto.GossipInfoStore`, to be able to send the `delta` in `GossipRequest` as protobuf. Once I know how to encode `Val` of `gossip.info` I will open a PR for review.

**Comment by tamird** [comment]
`proto.GossipInfoStore` is one option, with `oneof` as you suggest.

Another option (since the types of each key must be statically known anyway) is to use known encodings for each of the types:
- `int64`: http://godoc.org/encoding/binary#PutVarint
- `string`: just convert to a byte array
- `proto.StoreDescriptor`: Marshal

This may be slightly more ergonomic, but you'll have to try and see.

**Comment by tamird** [comment]
Looks like `PrefixConfigMap` is also propagated via `Val`.

**Comment by tamird** [comment]
@thschroeter any progress here?

**Comment by thschroeter** [comment]
Will push a commit tomorrow morning for review. Sorry for the delay, @tamird.

**Comment by tamird** [comment]
@thschroeter rebased your work again at https://github.com/tamird/cockroach/tree/no-more-gob after the removal of groups.

I'll get back on this tomorrow in search of further simplifications.

**Comment by thschroeter** [comment]
@tamird if you want you can leave me a task to finish this once it's simplified and the road is clear.

**Comment by tschottdorf** [comment]
:thumbsup:
