### ISSUE TITLE
Pre-built ARM64 images of CockroachDB -> christoofar/cockroachdb-arm64

### ISSUE THREAD

**Issue by christoofar** [cockroachdb/cockroach#62903]
Hi there

I realize this isn't a priority for the crdb team, but I've made a simplified and much easier to build version of crdb on arm64 available -> https://hub.docker.com/repository/docker/christoofar/cockroachdb-arm64

I try to update this myself, it's compiled on a Raspberry PI 400.   But you can also grab the GitHub repo and make your own image if you wish.   I run this build against a 40GB database I maintain and it behaves just like the x86 build.

Jira issue: CRDB-6203

**Comment by knz** [comment]
Link to the repo: https://github.com/christoofar/cockroachdb-arm64

**Comment by knz** [comment]
@christoofar looking at your Dockerfile, it looks like you were able to build from sources "out of the box", without any patches. Is this correct?

**Comment by FireMasterK** [comment]
According to https://github.com/cockroachdb/cockroach/issues/20433#issuecomment-634205077, building arm64 images are possible, so why not have officially built images?

**Comment by knz** [comment]
because we're not building images unless they get the same amount of testing and QA, and organizing testing and QA for a new platform costs $$ and that hasn't been a priority so far.

**Comment by christoofar** [comment]
> @christoofar looking at your Dockerfile, it looks like you were able to build from sources "out of the box", without any patches. Is this correct?

Yes.   I pull the .ZIP of the course and then just make a build from there.

I have recently modified the Dockerfile to use a golang docker image (with a newer compiler) to do the build.

My crdb test databases at home are all running on ARM64.

**Comment by christoofar** [comment]
> because we're not building images unless they get the same amount of testing and QA, and organizing testing and QA for a new platform costs $$ and that hasn't been a priority so far.

Understandable.   Luckily ARM64 with the current code base (as of this writing) works OK, anyone who would be using it would need to understand that platform (and whatever issues that are not reproducible on x64) shouldn't expect to get any mainline support.

**Comment by kenliu-crl** [comment]
Hi. We are posting updates on ARM64 support to these other active issues. 

- https://github.com/cockroachdb/cockroach/issues/60778
- https://github.com/cockroachdb/cockroach/issues/32689
- https://github.com/cockroachdb/cockroach/issues/68648
- https://github.com/cockroachdb/cockroach/issues/58676

[This is the latest update](https://github.com/cockroachdb/cockroach/issues/60778#issuecomment-1201704432).
