### ISSUE TITLE
sql: schema change exceeding pq deadline

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#6293]
https://circleci.com/gh/cockroachdb/cockroach/16801?utm_campaign=build-failed&utm_medium=email&utm_source=notification

is failing because a schema change execution is not fast enough. See:
schema_changer_test.go:451: pq: context deadline exceeded

This test can be fixed to always run the schema change through the async path.

**Comment by andreimatei** [comment]
LGTM
