### ISSUE TITLE
sql: experiment with load-balancing clients

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#6295]
When easing client traffic off a node (for example, when preparing a node for scheduled downtime), we must send the right signal to accommodate various possible load balancing mechanisms (for example pgbouncer or haproxy).

We should investigate what the "state of the art" here is.
#6283 suggested using the Postgres error code

> 08004  SQLSERVER REJECTED ESTABLISHMENT OF SQLCONNECTION
> sqlserver_rejected_establishment_of_sqlconnection")

(http://www.postgresql.org/docs/9.0/static/errcodes-appendix.html)

and a similar appropriate error for existing connections which try to issue
SQL commands in an ongoing session which has expired due to draining.

However, @bdarnell commented:

> We should do some research about how widely-supported these error codes are.
> For example, pgbouncer doesn't seem to do anything with them. I'm concerned
> that in practice the best way to load balance clients may turn out to be a
> tcp-level tool like haproxy, in which case we may have to use cruder techniques
> (e.g. closing the listening socket, which would also imply re-separating pgport
> from the unified port).

**Comment by bdarnell** [comment]
@asubiotto has done some research here, documented in https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/drain_modes.md#note-on-closing-sql-connections
