### ISSUE TITLE
`TestDeterministicInitialData/tpch` in `pkg/ccl/workloadccl/allccl` fails on ppc64le

### ISSUE THREAD

**Issue by amitsadaphule** [cockroachdb/cockroach#62982]
**Describe the problem**

I built the cockroachdb **v20.1.0** on ppc64le and when I executed the test suite, I found that the test `TestDeterministicInitialData/tpch` in `pkg/ccl/workloadccl/allccl` had failed. I tried executing the test independently, which also resulted in consistent failure. The problem was that the expected hex value mentioned [here](https://github.com/cockroachdb/cockroach/blob/v20.1.0/pkg/ccl/workloadccl/allccl/all_test.go#L265) for `tpch` did not match with the one generated on ppc64le.

Any pointers on how the reference value in the `fingerprintGoldens` table for tpch is calculated will be great help.

**To Reproduce**

Here is the command I used to execute the failing test independently:

```make test PKG=./pkg/ccl/workloadccl/allccl TESTS=TestDeterministicInitialData TESTFLAGS='-v -count=1'```

Pasting relevant part of the log:

```
--- FAIL: TestDeterministicInitialData (17.16s)
    --- PASS: TestDeterministicInitialData/bank (0.00s)
    --- PASS: TestDeterministicInitialData/bulkingest (0.12s)
    --- PASS: TestDeterministicInitialData/indexes (0.00s)
    --- PASS: TestDeterministicInitialData/intro (0.00s)
    --- PASS: TestDeterministicInitialData/json (0.00s)
    --- PASS: TestDeterministicInitialData/ledger (0.27s)
    --- PASS: TestDeterministicInitialData/movr (0.07s)
    --- PASS: TestDeterministicInitialData/queue (0.00s)
    --- PASS: TestDeterministicInitialData/rand (0.00s)
    --- PASS: TestDeterministicInitialData/roachmart (2.63s)
    --- PASS: TestDeterministicInitialData/sqlsmith (0.00s)
    --- PASS: TestDeterministicInitialData/startrek (0.00s)
    --- PASS: TestDeterministicInitialData/tpcc (1.25s)
    --- FAIL: TestDeterministicInitialData/tpch (12.78s)
        all_test.go:289:
                Error Trace:    all_test.go:289
                Error:          Not equal:
                                expected: 0xdd952207e22aa577
                                actual  : 0x573e192d82e5768a
                Test:           TestDeterministicInitialData/tpch
    --- PASS: TestDeterministicInitialData/ycsb (0.04s)
FAIL
FAIL    github.com/cockroachdb/cockroach/pkg/ccl/workloadccl/allccl     42.061s
```
**Environment**
CockroachDB [v20.1.0]
Architecture and OS: [ppc64le/RHEL/UBI 8.3]
Go: [1.13.5]

**Comment by yuzefovich** [comment]
Because you're building on a different architecture from the one we support, I think it is not surprising that hashes end up being different. I'm not sure if you're the same person, but in our community slack we recently had a thread about this: https://cockroachdb.slack.com/archives/CP4D9LD5F/p1617093959206500. TL;DR is that feel free to ignore this error.

**Comment by amitsadaphule** [comment]
Thanks @yuzefovich ! I checked the conversation on slack that you've posted the link to. I'll ignore the error.

**Comment by amitsadaphule** [comment]
FYI @knz

**Comment by knz** [comment]
@amitsadaphule can you try with go 1.15.10 or later; we do not support go 1.13 for building cockroachdb any more.

**Comment by amitsadaphule** [comment]
Thanks for the feedback @knz, I'll try that. Actually, I had tried with `go 1.15.3` before for tag `v20.1.0`, but ran into too many test failures with that. So, switched back to `go 1.13.5` looking at the pre-reqs table at https://www.cockroachlabs.com/docs/v20.1/install-cockroachdb-linux#build-from-source.

**Comment by amitsadaphule** [comment]
Built `master` with `go 1.15.11` and executed the test. The issue does not occur there. Not sure whether this was fixed due to some code change or due to the go version change from `go 1.13.5` to `go 1.15.11`.

**Comment by amitsadaphule** [comment]
Confirmed that the issue is not specific to go version. Built and tested cockroach `v20.1.12` with `go 1.13.5` and the issue is not seen there. So, it seems to be fixed in the cockroach code.

**Comment by knz** [comment]
cool thanks
