### ISSUE TITLE
sql: EXPLAIN (OPT, ENV) and EXPLAIN ANALYZE (DEBUG) don't work with schemas

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#62990]
```
explain (OPT, VERBOSE, ENV) delete from g.t where t_guid = '938799e6-d81b-4417-8039-dfce0a5fdb9d';
ERROR: stmtEnvCollector: relation "demodb.public.t" does not exist
```

EXPLAIN ANALYZE (DEBUG) likely has the same problem (it shares this code, and I believe I saw that error in some bundles before).

**Comment by rafiss** [comment]
is this related to https://github.com/cockroachdb/cockroach/pull/61752 ?

it fixed something like this

**Comment by RaduBerinde** [comment]
Ah, great, should be the same issue. The error was on v20.2.3 so it wouldn't have had your fix.
