### ISSUE TITLE
kv: persist leaderCache to make node restarts less costly

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#630]

**Comment by tamird** [comment]
Is restarting a node currently not harmless? What can go wrong?

**Comment by spencerkimball** [comment]
The idea here is to avoid unnecessary gossip and leader redirect "storms" on restarts. I'll change issue title.

**Comment by bdarnell** [comment]
Related idea: once we persist the contents of gossip, we should add all known node addresses to the gossip bootstrap list at restart. This can make the cluster more self-managing without the need for dynamic load balancing.

**Comment by petermattis** [comment]
Gossip info is now persisted. @spencerkimball, @bdarnell Is there something to be done with the leader cache?

**Comment by bdarnell** [comment]
Persisting the leader cache would have some benefit, but I don't know if it's enough to be worth doing. Certainly not a priority; I'd say wait until this is a demonstrable problem.

**Comment by spencerkimball** [comment]
Persistent gossip bootstrap info was added in #3711.

It is certainly not required at this point to worry about the range leader cache. I'm closing the issue. We'll re-add if that becomes a performance bottleneck on rolling restarts in the future.
