### ISSUE TITLE
sql: check if statement stats are collected when "slow transaction threshold is exceeded"

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#63007]
We have a couple of cluster settings like `sql.trace.stmt.enable_threshold` that control whether we are tracing a stmt or a txn once it exceeds the specified latency threshold. The way it is implemented is that we create a root tracing span once the threshold is set to non-zero value, and then we log the stmt or the txn if they end up taking longer than the threshold. We could piggy-back on this tracing to also collect the execution statistics for the stmt or the txn because the overhead of doing it all the time comes from the tracing itself, so if the tracing is enabled because of the "slow stmt" tracing, then we can just collect exec stats unconditionally. Supposedly the user is trying to determine which queries are slow, so the more information we collect, the more helpful CockroachDB will be to the user.

Jira issue: CRDB-6382

**Comment by jordanlewis** [comment]
Hey @yuzefovich, could you provide some more detail in the description on what this is about? I'm sure we talked about it, but I don't really remember.

**Comment by yuzefovich** [comment]
I updated the description. I think this change is relatively simple and also could be pretty beneficial.

**Comment by jordanlewis** [comment]
We're making this low priority for now because we think that this setting is seldom used, since it is so expensive to turn it on in the first place.

**Comment by maryliag** [comment]
No longer a priority
