### ISSUE TITLE
sql: set constraint name in pg error for uniqueness violations

### ISSUE THREAD

**Issue by electrum** [cockroachdb/cockroach#63014]
This is the same as #54313, except for `PRIMARY KEY` and `UNIQUE` constraints.

I wrote a [simple test program](https://github.com/electrum/cockroach-constraint) in Java that tests the behavior of both Cockroach and PostgreSQL. The JDBC driver `PSQLException.getServerErrorMessage().getConstraint()` returns `null` in Cockroach, but returns the constraint name in PostgreSQL.

The tests run using GitHub Actions, so you can see the failure there, or simply run `mvn test` (you'll need JDK 11 and Maven installed).

 - CockroachDB version: 20.2.7

**Comment by knz** [comment]
cc @rafiss for triage

**Comment by electrum** [comment]
It looks like this was fixed in 5d5389db6a6138e244939635e1918fba6269ee8b. Would it be possible to get this into a 20.2 release?

**Comment by rafiss** [comment]
Hi @electrum! since this is a new feature, we aren't planning to backport it to 20.2. However, v21.1 will be out soon, currently planned within 1-2 months. 

One thing that may help us is to know if there is a specific tool that is broken. Are you blocked on this?

**Comment by electrum** [comment]
The constraint name is set for foreign keys in 20.2, but not for primary key / unique indexes, so this would bring parity for all such constraint violations. It's an incompatibility with PostgreSQL, and makes it more annoying to write retry loops, since we have to run a regex on the error message to get the constraint name, but isn't a blocker.

**Comment by rafiss** [comment]
I hear what you're saying. Unfortunately although it was a divergence from Postgres, we decided we won't backport to 20.2
