### ISSUE TITLE
ui: flesh out database page

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#6304]
The database page is currently quite spartan. Some ideas for improvement:
- [ ] Show a list of events corresponding to the database or tables in the database.
- [ ] Show an audit log of privilege changes for the database.
- [x] Show the current permissions associated with the database.
- [ ] Show the zone config associated with the database (if it exists).

**Comment by jordanlewis** [comment]
We've come a long way here, so I'm closing this until we have more targeted improvements to make.
