### ISSUE TITLE
ui: flesh out the table page

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#6305]
The table page is currently quite spartan. Some ideas for improvement:
- [ ] Show a list of events associated with the table.
- [ ] Show an audit log of schema / privilege changes for the table.
- [x] Show the table schema using SQL syntax (as opposed to tables of columns and indexes).
- [ ] Show the zone config associated with the table.

**Comment by petermattis** [comment]
Another item:

* Show in-flight schema changes for the table.

**Comment by jordanlewis** [comment]
We've got grants, zone configs and schemas here now. Schema changes still missing, but I think this issue has outlived its usefulness.
