### ISSUE TITLE
ui: add a zones page

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#6306]
In addition to being able to see the zone config for a database/table (see #6304 and #6305), we should be able to see a list of all of the zones in the cluster. Each zone should be editable, providing an easy means for adjusting the replication and other configuration. Further discussion is required on zone editing as such configuration can be complex. For example, how do you restrict the a replica to a particular datacenter or geographic area? Seems like we need should start simple and leave more advanced configuration to the cli.

**Comment by vilterp** [comment]
Prototyped an editing experience a while back. Video: https://youtu.be/e0DzULki3IQ

Related to the replica matrix in #20500 (read-only).

Definitely needs more design exploration.
