### ISSUE TITLE
sql, config: validation of inherited zone config fields is inadequate

### ISSUE THREAD

**Issue by aayushshah15** [cockroachdb/cockroach#63063]
CockroachDB requires that certain related zone config attributes be compatible with each other (see [here](https://github.com/cockroachdb/cockroach/blob/16808f50ab4720c73b98307a5c3dfe4f1ae3067a/pkg/config/zonepb/zone.go#L278) and [here](https://github.com/cockroachdb/cockroach/blob/16808f50ab4720c73b98307a5c3dfe4f1ae3067a/pkg/config/zonepb/zone.go#L315)). One example of this are the `constraints` and `num_replicas` attributes — the number of replicas constrained must not exceed the total number of replicas. Zone configs that don’t pass this validation are rejected at the time of insertion.

However, the validation mentioned above can be circumvented when, given a pair of such related attributes, one of those attributes is inherited from the parent but the other isn't. For instance, consider the following sequence of events:

```sql
create database db; use db;

create table t ();

alter database db configure zone using num_replicas = 3, constraints = '{"+region=europe-west1": 3}';

alter table t configure zone using num_replicas = 3;
-- at this point t inherits `constraints` from db, but does not inherit `num_replicas`.

alter database db configure zone using num_replicas = 5, constraints = '{"+region=europe-west1": 5}';

show zone configuration for table t;
>
  target  |                 raw_config_sql
----------+-------------------------------------------------
  TABLE t | ALTER TABLE t CONFIGURE ZONE USING
          |     range_min_bytes = 134217728,
          |     range_max_bytes = 536870912,
          |     gc.ttlseconds = 90000,
          |     num_replicas = 3,
          |     constraints = '{+region=europe-west1: 5}',
          |     lease_preferences = '[]'

```

We can perform a similar series of actions to get a zone config that allows for `num_voters` to be higher than `num_replicas`.

The main consequence of this bug is that it allows for configurations that are unsatisfiable.

At some level, the problem here is that we only perform the aforementioned validation on the zone config being manipulated, and not on any of its children. One thorn that any potential fix will have to address is the handling of already persisted zone configs that should’ve been invalidated/rejected but weren’t.

The bug has existed since the introduction of cascading zone configs.

Noticed while working on #61316.

Jira issue: CRDB-6413

**Comment by aayushshah15** [comment]
cc @otan and @rafiss so you're aware.

**Comment by irfansharif** [comment]
This is a broader problem than just inherited zone configs (see #47662). In the general case, I think, to figure out whether or not a proposed zone config is satisfiable (given the current cluster topology, and other possibly-conflicting constraints), is an NP-complete problem, and thus not addressable unless we introduce a SAT solver. That's not entirely without precedence; it's something @darinpp explored when thinking about how our allocator was implemented. @lalithsuresh also has this very compelling paper + prototype over at https://github.com/vmware/declarative-cluster-management that we could one day put to good use here at CRDB.

**Comment by lalithsuresh** [comment]
Given that you have an SQL schema already, I can try and prototype this using DCM. Any pointers on how to get this state and what kind of constraints you're trying to preserve on it?

**Comment by aayushshah15** [comment]
>This is a broader problem than just inherited zone configs. 

I agree, though I wouldn't conflate this issue with the one you linked. As you pointed out, we don't currently exhaustively validate constraints. The purpose of this issue, instead, was to ensure that whatever validation we _do perform_ isn't retroactively subverted due to inheritance. 
>At some level, the problem here is that we only perform the aforementioned validation on the zone config being manipulated, and not on any of its children.

**Comment by aayushshah15** [comment]
>In the general case, I think, to figure out whether or not a proposed zone config is satisfiable (given the current cluster topology, and other possibly-conflicting constraints), is an NP-complete problem, and thus not addressable unless we introduce a SAT solver.

I'm also unsure if this is true. 
1. Our zone config constraints aren't as expressive as arbitrary boolean expressions.
2. The allocator does already figure out if the set of constraints on a range are satisfiable (it needs to, in order to guide placement decisions).

For the most part, figuring out if a set of constraints is valid at the _SQL layer_ is hard because it doesn't have access to all information about a cluster's physical state the way `kv` does.

**Comment by irfansharif** [comment]
> Our zone config constraints aren't as expressive as arbitrary boolean expressions.

Are they not? Handwavey translation to SAT: 

Assume replication factor for all ranges == 1. We're allowed to define required (+) and prohibited (-) constraints on a given range R: `constraints = '[+attr1,-attr2]'`. Each node in the system can be configured to have an arbitrary number of locality attributes attached to it (`N1: [attr3]`, `N2: [attr1, attr2]`). 

A replica's constraints is a conjunction of all its attributes: `R: (attr1 ∧ ¬attr2)`. A node's locality tags could be expressed as a conjunction of all attributes: `N1: (¬attr1 ∧ ¬attr2 ∧ attr3)`, `N2: (attr1 ∧ attr2 ∧ ¬attr3)`. 

Constraints for R is satisfiable if it's placeable on any one of the nodes. That is, its constraints are met by at least one node: `((¬attr1 ∧ ¬attr2 ∧ attr3) ∨ (attr1 ∧ attr2 ∧ ¬attr3)) ∧ (attr1 ∧ ¬attr2)`.

**Comment by darinpp** [comment]
For this specific case it may make sense to traverse the zone config tree and see if the zone config being changed doesn't make impossible some of the zone configs that inherit the zone being changed, And if that is the case - may be block the change or keep the old value that was inherited and break the inheritance link. 
In general the **placement** of the replicas is a hard problem because not only you need to satisfy the configuration but you also need to satisfy resource constrains - storage space, mean number of replicas per node etc. A zone config for example that requires one replica to be always in a region with just a single, under provisioned node may be fine as a config but may not be achievable with the current cluster/store sizes.

**Comment by irfansharif** [comment]
@lalithsuresh: we don't have a SQL schema for these constraints, at least nothing comparable to the DCM paper. Our internal constraints are very similar to the k8s one (H1-4, H7, H9, H10-11, H12-13, S1, S2-5, S8 from [figure 2](https://lalith.in/papers/dcm-osdi2020.pdf) are all rules we have parallels for). The (kind of shitty) APIs we have to express these constraints currently can be found in https://www.cockroachlabs.com/docs/v21.1/configure-replication-zones#types-of-constraints. Compared to the k8s allocator, I think another kind of rule we have is "don't place multiple replicas of the same data in the same failure domain, in the presence of higher levels of failure domains". That is "don't place multiple replicas of the same range on the same node in the presence of other nodes, or in the same AZ in the presence of other AZs, or in the same region in the presence of other regions".

**Comment by aayushshah15** [comment]
>Are they not? Handwavey translation to SAT

I don't see how that framing characterizes the problem at hand. The `attr`s in our context of constraint validation are not free variables (the nodes' localities are not fungible, neither are the replica constraints), and our job is not to search for the existence satisfiable combination of attrs. 

The problem of validation is simply about checking whether the given set of attributes satisfy a given set of constraints.

**Comment by irfansharif** [comment]
Right, I agree with you that checking to see `num_replicas = 3, constraints = '{+region=europe-west1: 5}'` is not something we need a SAT solver for. I'm saying that in the _general_ case with zone configs it's possible for users to define unsatisfiable constraints, or have their pre-existing constraints rendered unsatisfiable once certain nodes are perma-dead or decommissioned-in-absentia. What I think I'm saying is that by "zone config validation", we want to guard against installing configs unsatisfiable constraints; that's not something we can currently do in the general case, even if we can do it for the specific `num_replicas = 3, constraints = '{+region=europe-west1: 5}'` case.

**Comment by aayushshah15** [comment]
>I'm saying that in the general case with zone configs it's possible for users to define unsatisfiable constraints

Could you give an example of something the user can define that we cannot decide (i.e. accurately accept or reject)? I'm struggling to understand what a "general" case is, and a scenario where we're validating anything other than a concrete set of constraints.  

> have their pre-existing constraints rendered unsatisfiable once certain nodes are perma-dead or decommissioned-in-absentia

That's not the same problem, though. No amount of validation can guard against the dynamism of the cluster's physical state. If all nodes die, no required constraints can be satisfied. We can only hope to validate a zone config as of insertion time.

**Comment by irfansharif** [comment]
Validating that an incoming zone config, if all you're doing is ensuring that there's a node available for every replica, is polynomial with the number of replicas and nodes in the system. Relating it to the placement of _all_ replicas, where you'd have to ensure that the total size of all replicas allocated to any given node does not exceed it's capacity, I think that veers into [NP-complete](https://en.wikipedia.org/wiki/Bin_packing_problem) territory. I suppose it's a tall order to ask to validate _that_, but that's what I meant for the general case.

> Could you give an example of something the user can define that we cannot decide (i.e. accurately accept or reject)?

Imagine defining a zone config for a database, pinning it to a certain az, where the storage capacity of that az is smaller than the size of that database. There might also be other ranges housed in that az that may or may not be free to move around to make room.

>  The attrs in our context of constraint validation are not free variables.

Hm that example is junk for many different reasons, woops, ignore. Was using DNF and effectively 'pinning' assignments for `attr{1,2}` in R's clause.
