### ISSUE TITLE
sql: block on transition to multi-region if tables have custom zone configs

### ISSUE THREAD

**Issue by aayushshah15** [cockroachdb/cockroach#63071]
Address this TODO: https://github.com/cockroachdb/cockroach/blob/fddcc70ccaf738dfecab8634aa29d55c60d89f8b/pkg/sql/alter_database.go#L759

When attempting to transition an existing database to multi-region, we’d like to block the transition if any existing tables within the database have custom `constraints`, `voter_constraints`, `num_replicas`, `num_voters` or `lease_preferences` defined. We expect the user to `DISCARD` these existing configs before they can add their initial primary region. 

Without the above, we risk clobbering the individual tables’ zone configs upon the transition, as they may not inherit attributes that, for instance, control the survivability or attributes that dictate the placement of non-voting replicas. 

Lastly, we might want to permit the user to force their way into this transition if they have the `override_multi_region_zone_config` session variable set to `true`.

To reproduce:
```sql
root@127.0.0.1:26257/db> create table t ();

root@127.0.0.1:26257/db> alter table t configure zone using num_replicas=3, constraints='{"+region=europe-west1": 1}';

root@127.0.0.1:26257/db> alter database db configure zone using num_replicas=5, constraints='{"+region=europe-west1": 5}';

root@127.0.0.1:26257/db> alter database db set primary region "us-east1";

root@127.0.0.1:26257/db> show zone configuration for table t;
  target  |                 raw_config_sql
----------+-------------------------------------------------
  TABLE t | ALTER TABLE t CONFIGURE ZONE USING
          |     range_min_bytes = 134217728,
          |     range_max_bytes = 536870912,
          |     gc.ttlseconds = 90000,
          |     num_replicas = 3,
          |     num_voters = 3,
          |     constraints = '{+region=europe-west1: 1}', <-- ??
          |     voter_constraints = '[+region=us-east1]',
          |     lease_preferences = '[[+region=us-east1]]'

```

**Comment by otan** [comment]
> Lastly, we might want to permit the user to force their way into this transition if they have the override_multi_region_zone_config session variable set to true.

filing this as a separate issue
