### ISSUE TITLE
ui: add user/login system

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#6307]
Add a login system to the UI. The backend has a concept of user, but it isn't currently exposed in the UI. We need a "users" page to list the existing users, add/remove users and change privileges. Users would have to login to the UI and, depending on their privileges, would have a restricted view of the system. This work should be done in TBD stages.

**Comment by dianasaur323** [comment]
Adding a note here that /debug pages should also sit behind the user / login system as per conversation with @mrtracy

**Comment by dianasaur323** [comment]
Updating this GitHub issue with finalized 1.1 scope - just basic user login with error messages and login ID in the top right. We also need to consider how these logins reflect in logging in case users want to audit usage. cc @kuanluo

**Comment by kuanluo** [comment]
Login with field error:
![image](https://user-images.githubusercontent.com/1486483/27051051-b02ebc7c-4f82-11e7-9646-a2482baf5e54.png)

If the error is more generic:
![image](https://user-images.githubusercontent.com/1486483/27051146-14a40e50-4f83-11e7-9d4b-77faa8731876.png)

Log out button with ID top right:
![image](https://user-images.githubusercontent.com/1486483/27051169-24103850-4f83-11e7-83c8-ed7eaf7853fa.png)

**Comment by dianasaur323** [comment]
One final fix here on the mocks is to remove the side nav bar on the login page since those buttons won't work anyway.

**Comment by dianasaur323** [comment]
punting to 1.2 due to risk of this breaking user workflow without sufficient QA time.

**Comment by a-robinson** [comment]
If the entire UI requires login, and login requires the database to be working properly, will we no longer be able to use the UI (including the debug pages) to debug broken clusters?

**Comment by nstewart** [comment]
cc @piyush-singh re: @a-robinson 's question. Let's make sure we don't remove an important debugging workflow

**Comment by vilterp** [comment]
Closing this since login is implemented and now enabled by default in secure clusters. #29270 tracks @a-robinson's concern that this will block debugging flows.
