### ISSUE TITLE
roachprod:  "put" writes executable files in-place

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#63085]
I was running subsequent invocations of `roachprod-stress` while observing the (slow) file copy on the remote matchine, and I noticed the following:

if the remote file already exists, `roachprod` overwrites it in-place.

If the file is executable, this means that the executable code will be incrementally rewritten during the copy. If the file is copied/executed during that time, the executable code becomes invalid.

(Ditto anything else, really).

This constitutes a bug but also possibly a security vulnerability.

The fix is to either:

- preferred: copy the data to a new (temp) file then `mv` into its final destination if no error is encountered
- `rm` the remote file before the copy

cc @jlinder for triage.

Epic CRDB-10428

Jira issue: CRDB-6424

**Comment by petermattis** [comment]
> If the file is executable, this means that the executable code will be incrementally rewritten during the copy. If the file is copied/executed during that time, the executable code becomes invalid.

I don't think you can overwrite an executable that is in use. Shouldn't you see an EBUSY error in this scenario?

`roachprod` shells out to `scp` for file copies, so we're really just seeing the default `scp` behavior. Is there a flag for `scp` that can do what you're asking?

**Comment by rail** [comment]
Maybe we should retry when get the EBUSY error and stop the running binary before copying?

**Comment by knz** [comment]
> Shouldn't you see an EBUSY error in this scenario?

it's the other way around: if the file starts being copied/executed in the server _after the copy has started_ we'd get garbage in the execution (you are right that if the file is already being executed when the copy starts, EBUSY is reported)

But the argument generally extends beyond executable files - if, say, a test is currently ongoing and processing files from a `testdata` directory, it doesn't make sense to overwrite the files "under" it.

> roachprod shells out to scp for file copies, so we're really just seeing the default scp behavior.

oh that explains why indeed.

I'd say, one way to do it instead would be to shell out to `ssh` instead and run `tar` on both ends (`tar -cjf- | ssh ... tar -C dst -xjf-`)

Also, (this is unrelated) the direct usage of `scp` explains why the copy is super slow. If `scp` remains in use, `-C` would help.

**Comment by petermattis** [comment]
> Also, (this is unrelated) the direct usage of scp explains why the copy is super slow. If scp remains in use, -C would help.

We do pass `-C` to scp. See `SyncedCluster.scp`.
