### ISSUE TITLE
cli/demo:  latency simulator not properly active with `--insecure`

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#63098]
I was investigating #62435 and randomly tried to run the demo cluster with `--insecure`
(which needs to remain supported, as per multiple requests by @awoods187 @rafiss )

For example:

` ./cockroach demo  --global --nodes 9 --insecure --empty`

I was expecting the latency delay to be properly enabled in this case and impact the observable latency of statements such as `SHOW CLUSTER SESSIONS` (or `QUERIES`), which do run a fan-out across all nodes (and thus pay the price of the network roundtrip).

However, no matter what I do, the latency of the statement remains under 4ms.

Without `--insecure`, we see the latency increase as expected.

This suggests that the latency injection code does not properly work when TLS is disabled between the nodes.

Epic CRDB-8948

Jira issue: CRDB-6426

**Comment by knz** [comment]
It should be noted that:

- the latency injection code, as implemented in `pkg/rpc`, remains untested (there is no unit test there)
- the test that @otan is trying to add for the `demo` command in #62435, as requested by @ajstorm , is an end-to-end test and uses the secure mode only. If I modify the test with `demoCtx.insecure = true`, the test fails all the time.

**Comment by awoods187** [comment]
Nice find @knz!

**Comment by jordanlewis** [comment]
@knz --insecure is deprecated in demo, so I don't understand why you are insisting we should try to fix the global latencies for it, since global latencies is a feature only for demo.

I would suggest closing this as a wont fix unless you have some other reason that we'd need to fix this deprecated feature!

**Comment by knz** [comment]
The issue is that oliver's other PR is still missing a working unit test, and the quickest way to get there is to make the unit test bypass the TLS handshake. That is unfortunately impossible due to this bug here.

**Comment by knz** [comment]
Moreover arguably the issue I've filed here is just the tip of the iceberg: it doesn't make sense to me that the feature should work differently based on the TLS configuration, so if it does that is likely a sign that it's making faulty assumptions at various levels. Regardless of whether we support the insecure.flag on the CLI, the underlying issue still needs to be investigated.

**Comment by knz** [comment]
Also the latency simulation code in the rpc package still has no unit test there. It should anyway, as a prerequisite to marking the feature as stable.

**Comment by knz** [comment]
@lunevalex there's a management issue to be considered here. 

Here you see an example of a team (in this case, SQL) creating a complex feature (in this case, latency simulator) as a flex Friday project into an area of the code (RPC context) owned by another team (in this case, KV later transitioning to server)

The addition was granted under the understanding the feature was for experimentation purpose only.

However now you have a manager for the other team deciding that the feature must be stabilized and productionized "as of yesterday". It doesn't sit right with me that one team can require another team to start owning and supporting a complex feature that had been marked as experimental, that is lacking proper unit testing, and without clear mention in the roadmap.

The work is non trivial because the investigation here requires reverse engineering the code, documenting it, adding unit tests and transitioning the expertise so that the nominal team can own the code and support it moving forward.

Can you provide some general management guidelines about this?


At this point I am tempted to simply postpone the work in the related PR by otan and this issue by saying "we didn't allocate bandwidth for this issue in this cycle, talk to the PM to change this and drop something else off the roadmap, this needs a M-sized budget."

**Comment by otan** [comment]
> @knz --insecure is deprecated in demo, so I don't understand why you are insisting we should try to fix the global latencies for it, since global latencies is a feature only for demo.

--insecure is definitely a feature a lot of people still want, because it allows them to connect to the demo cluster without certificate setup. i'm surprise it's being deprecated (but I know people are debating this elsewhere so I'm going to leave that alone.

> At this point I am tempted to simply postpone the work in the related PR by otan and this issue by saying "we didn't allocate bandwidth for this issue in this cycle, talk to the PM to change this and drop something else off the roadmap, this needs a M-sized budget."

that is the plan right now; we're sitll planning on surfacing the flag but putting in the help text on initialisation that it is experimental as per https://github.com/cockroachdb/cockroach/issues/63469

----

I would also note that normal SQL commands still have the latency in place, just SHOW ALL CLUSTER QUERIES does not.

**Comment by ajstorm** [comment]
> It doesn't sit right with me that one team can require another team to start owning and supporting a complex feature that had been marked as experimental, that is lacking proper unit testing, and without clear mention in the roadmap.

To be fair, the request I made a few weeks ago was for a small amount of help to get us moving in the right direction on this effort.  In exchange, I promised to find a long-term owner for this work (something that's underway, as `demo` will likely end up being owned by SQL Experience, as I've discussed with both @solongordon and @jordanlewis).  I didn't realize at the time that the "small amount of work" we anticipated would result in a substantial refactor of the code.  Once it became evident that we'd need a major refactor, I agree with you that we should have revisited the request, as we're doing now.

> At this point I am tempted to simply postpone the work in the related PR by otan and this issue by saying "we didn't allocate bandwidth for this issue in this cycle, talk to the PM to change this and drop something else off the roadmap, this needs a M-sized budget."

That's my opinion too, and is what we're pursuing (sorry for not following up with you directly on this - that's on me).  The plan is to push out what we have with `demo --global` as an experimental/beta feature.  This allows us to unlock the multi-region demoing use cases, while at the same time not opening up `--global` for the broad spectrum of use cases.  We have tested `--global` thoroughly on the multi-region side and while it may not live up to an automated stress test, it's stable enough for illustrating the power of the new multi-region changes.  We should properly revisit what it will take to remove the experimental/beta flag in 21.2 (or beyond - @vy-ton FYI).

**Comment by knz** [comment]
@ajstorm thanks for your answer. The discussion above does not pertain to the "demo" code, for which I was aware of the ownership transition already. It pertains to the changes in the `pkg/rpc/context.go` code, which is definitely not a SQL concern and is currently owned by the KV team (later by the server team). I only discovered when filing this issue that the changes to this file that implement the latency simulator had never received unit tests. That's what my comment above refers to.

**Comment by rafiss** [comment]
resolved by https://github.com/cockroachdb/cockroach/pull/77861
