### ISSUE TITLE
Structured Data

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#631]
[This will likely spawn a host of sub-issues]

- [ ] Schema definition
- [ ] Basic indexes
- [ ] Full-text indexes
- [ ] Geospatial indexes
- [ ] SQL interface
- [ ] Schema change
- [ ] Query planner/optimizer

**Comment by alexmingoia** [comment]
Why not expose the necessary APIs for people to build schemas and SQL interfaces? Same with indexes.

**Comment by petermattis** [comment]
Alex, can you expand on what you're asking for? We are exposing key-value APIs that you could build the structured data layer on top of. There is a huge benefit in providing a single integrated and well tested/designed/optimized structured data layer. But that wouldn't prohibit someone else from implementing their own schema/SQL/whatever layer on top of the key-value API.

**Comment by petermattis** [comment]
Since this issue was filed we've decided to go forward with a SQL interface.
