### ISSUE TITLE
Provide Liquibase support for column families in CRDB

### ISSUE THREAD

**Issue by alistair-roacher** [cockroachdb/cockroach#63139]
**Is your feature request related to a problem? Please describe.**
A customer is using Liquibase to deploy schema objects against CockroachDB using a Yaml format changelogFile. They also use H2 in-memory database for early phases of testing and would like to be able to deploy column against CockroachDB without having to write multiple versions of SQL scripts. 

**Describe the solution you'd like**
Liquibase to have a way of representing column families in Yaml that would be applied to a CockroachDB target, but ignored for all other target types. Would also like to be able to configure Liquibase to know that it is deploying against a CockroachDB target (rather than just specifying the target JDBC driver which would indicate that the target is PostgreSQL)

**Describe alternatives you've considered**
Separate SQL scripts for H2 and CockroachDB, but this is clunky / error prone and involves duplication of effort.

**Additional context**
Column family syntax is enclosed in the main brackets for table creation after column definitions:
CREATE TABLE test (
    id INT PRIMARY KEY,
    last_accessed TIMESTAMP,
    data BYTES,
    FAMILY f1 (id, last_accessed),
    FAMILY f2 (data)
);

CRDB Docs page: https://www.cockroachlabs.com/docs/stable/column-families.html

**Comment by rafiss** [comment]
Let's file this in the liquibase project -- there isn't work to do within CockroachDB for this

**Comment by rafiss** [comment]
To answer a bit more details:

> Liquibase to have a way of representing column families in Yaml that would be applied to a CockroachDB target, but ignored for all other target types.

This should be possible using the `dbms` property on the `changeset` tag: https://docs.liquibase.com/concepts/basic/changeset.html

> Would also like to be able to configure Liquibase to know that it is deploying against a CockroachDB target 

Internally, liquibase already detects that it's running against CockroachDB. If you set `dbms type="cockroachdb"`, the changeset will only run against CockroachDB.

---

Also, any liquibase changeset can include raw SQL, so the user can write the CREATE TABLE statement directly.
