### ISSUE TITLE
Running TPC-C (10K warehouses) against a 15 node cluster using roachprod is hung

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#63182]
**Describe the problem**
I am using roachprod to run TPC-C against a 15 node cluster. The scale of this benchmark is 100K warehouses. 

**To Reproduce**
What did you do?

I ran the following command: **roachprod run $CLUSTER:16 "./workload run tpcc --warehouses=10000 --wait=false --workers=10000 --max-rate=5000 --partitions=5 --duration=1s --split --scatter {pgurl:1}"**

If possible, provide steps to reproduce the behavior:

I am following these exact steps (Large Tests with Partitioning (AWS+GCP) section): https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/59146477/Manually+Run+TPC-C+on+GCP+and+AWS

Commands:

1. export CLUSTER=$USER-partitioning
2. roachprod create $CLUSTER -n 16 --clouds=aws --aws-machine-type-ssd=c5d.4xlarge
3. roachprod stage $CLUSTER cockroach
4. roachprod stage $CLUSTER:16 workload
5. roachprod start $CLUSTER:1-15 --racks=5 --sequential
6. roachprod adminurl --open $CLUSTER:1
7. roachprod run $CLUSTER:1 -- "./cockroach workload fixtures import tpcc --warehouses=10000 --db=tpcc"
8. **roachprod run $CLUSTER:16 "./workload run tpcc --warehouses=10000 --wait=false --workers=10000 --max-rate=5000 --partitions=5 --duration=1s --split --scatter {pgurl:1}"**

Observe the hang with the following similar output (screenshot below): I210406 18:28:50.158433 1 workload/cli/run.go:376  [-] 1  creating load generator...

**Expected behavior**
No Hang and the data is "partitioned" so that I can then move forward to run the TPC-C benchmark. 

**Additional data / screenshots**

Screenshot of the hang:
![image](https://user-images.githubusercontent.com/81193618/113786818-c36cc380-96ee-11eb-9591-378f6c4f3a89.png)

Screenshot of the 'hung' statements through the DBConsole (ALTER table **SCATTER**):

![image](https://user-images.githubusercontent.com/81193618/113787093-468e1980-96ef-11eb-9262-0e9e39b27cc8.png)

http://ngo-partitioning-0001.roachprod.crdb.io:26258/#/sessions?ascending=true

**Environment:**
Cluster id: **81925d23-47d3-4cd3-8c96-be18537da7fa**
**V21.1.0-ALPHA.3-2102-GEC848298D8**

**Comment by mwang1026** [comment]
Are you able to repro this @kevin-v-ngo ? Really hard to diagnose if we don't have a repro. Closing for now but reopen if you're able to repro.
