### ISSUE TITLE
kvserver: merging of ranges with non-voters can be extremely disruptive to foreground traffic 

### ISSUE THREAD

**Issue by aayushshah15** [cockroachdb/cockroach#63199]
Non-voting replicas are not upreplicated through a [synchronous snapshot the way learners](https://github.com/cockroachdb/cockroach/blob/34904ed0c1f7f52bc9394597a6e2a25bcedd7636/pkg/kv/kvserver/replica_command.go#L1658) are. [We queue up new non-voters into the raft snapshot queue](https://github.com/cockroachdb/cockroach/blob/34904ed0c1f7f52bc9394597a6e2a25bcedd7636/pkg/kv/kvserver/replica_command.go#L1075-L1082) and rely on it to initialize newly added / rebalanced non-voters.

A range merge [will try to collocate replica sets](https://github.com/cockroachdb/cockroach/blob/d7a7a49a6ca48758fb979c98a2aa04e358effab2/pkg/kv/kvserver/merge_queue.go#L323) for the LHS and RHS, which may require rebalancing one or more non-voting replicas from the right hand side range to stores that have replicas for the left hand side range. An `AdminMerge` will then send a `SubsumeRequest` to the RHS and wait until all replicas have [caught up to the LAI of the subsume](https://github.com/cockroachdb/cockroach/blob/34904ed0c1f7f52bc9394597a6e2a25bcedd7636/pkg/kv/kvserver/replica_command.go#L726-L731). 

At this point, non-voting replicas that were _just_ rebalanced for the sake of the merge are very likely to still be waiting for, or be in the process of receiving, their initial snapshot from the raft snapshot queue (once the snapshot queue starts sending these newly rebalanced non-voters their initial snapshots, it will take roughly ~64 seconds _per replica_ if we assume default settings for range size and snapshot rates)

So, [the `AdminMerge` will hit this 5-second timeout](https://github.com/cockroachdb/cockroach/blob/34904ed0c1f7f52bc9394597a6e2a25bcedd7636/pkg/kv/kvserver/replica_command.go#L792) and the merge will fail. This will prompt the merge queue to [log an error and try again after about 10 minutes](https://github.com/cockroachdb/cockroach/blob/d7a7a49a6ca48758fb979c98a2aa04e358effab2/pkg/kv/kvserver/merge_queue.go#L353-L355). Now, notice that we’re waiting for those 5 seconds _after_ we’ve sent the subsume request. This means that RHS will not serve any traffic for those 5 seconds.

The expected high-level consequence of all this interaction is that all foreground traffic on a range that has non-voting replicas could experience seemingly random 5 second blips, where all requests to such a range are blocked for those 5 seconds.

**Comment by nvanbenschoten** [comment]
Thanks for writing this issue up. I agree with the GA-blocker label. Were you able to construct this scenario in a unit test like you were discussing today?

**Comment by aayushshah15** [comment]
> Were you able to construct this scenario in a unit test like you were discussing today?

Yup, our theory here checks out. In fact, there's a much simpler way to simulate the failure -- just add a 5 second sleep in[ this testing knob](https://github.com/aayushshah15/cockroach/commit/44f11fddc929aecaf01442d9729378d734320b77#diff-44baa39ac83376c66f711288e75ebbb602eea1a65a52a3cf90fe806632e6bf2aR4496). This made range-merges deterministically fail for all non-collocated pairs of LHS/RHS that have non-voters. As expected, range-merges for ranges that don't have non-voters are not affected by this delay.
