### ISSUE TITLE
Support for additional Avro types

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#63197]
We do not support all AVRO types today, namely ENUM, ARRAY, BIT, and COLLATEDSTRING.

There is a specific customer need around ENUM and ARRAY Types, but ideally we would have support for bit and collated string as well. ENUM type support is also a prerequisite for changefeeds on regional by row tables.

For ARRAY types, use Avro native array type. We should fail the changefeed if we come across an embedded type that we don’t know what to do with.

For Bit/varbit type - use an integer type, reasoning: small encoding space + simplicity. 

For Collated String: Use string type.

For ENUM type: encode the ENUM as a string when populating through the changefeed (reasons: simplest/most usable option, gets around a lot of edge cases). For the edge case where an ENUM is renamed, we’re going to add an option to fail the changefeed (similar to the option to fail on schema change) 

Overlaps with: https://github.com/cockroachdb/cockroach/issues/34420

Jira issue: CRDB-6465

**Comment by HonoreDB** [comment]
Arrays as arrays PR: https://github.com/cockroachdb/cockroach/pull/64251
CollatedStrings as strings PR: https://github.com/cockroachdb/cockroach/pull/64694

**Comment by HonoreDB** [comment]
Starting off with a backport to 21.1 ( https://github.com/cockroachdb/cockroach/pull/67433 ) . Once I'm sure that works, it'll hopefully be easier to do the 20.2 backport from there.

Left to do: Special dates (do not expect to backport as it's a potentially breaking change) and arbitrary-precision decimals (can backport).

**Comment by miretskiy** [comment]
@HonoreDB  -- I think this is rather stale and can be closed.

**Comment by miretskiy** [comment]
@amruss closing this issue; I think it's pretty stale and outdated.  Feel free to reopen if need.
