### ISSUE TITLE
backupccl: invalid serialization of the AST

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#63216]
See [this comment](https://github.com/cockroachdb/cockroach/pull/60676#discussion_r597128966) by @dt  which points to this code:

```go
   args.BackupStatement = tree.AsString(backupNode)
```

this is paired with the following code in `schedule_exec.go`:

```go
  node, err := tree.ParseOne(args.BackupStatement)
  ...
```

The expectation is thus that ParseOne will restore the original statement. That is not true however; `AsString` implies the `FmtSimple` flag, which is meant for display for human users. It is not guaranteed to preserve the statement.

The model to follow is the one set by DistSQL; this needs to format using `FmtParsable` instead.

cc @pbardea @dt for triage

Epic CRDB-8816

**Comment by dt** [comment]
@knz you fixed this, right? it's now `tree.AsStringWithFlags(backupNode, tree.FmtSimple|tree.FmtShowPasswords)` ?

**Comment by knz** [comment]
No it's still incorrect - we need `FmtParsable|FmtShowPasswords`

FmtSimple is lossy and generates unparsable stuff sometimes, even with passwords properly spelled out.
