### ISSUE TITLE
schemachange: failure in TestWorkload

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#63226]
Found in https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/2856592?buildTab=overview

```
schema_change_external_test.go:111:
  Error Trace:  schema_change_external_test.go:111
  Error:        Received unexpected error:
                ***UNEXPECTED ERROR; Received an unexpected execution error: ERROR: unimplemented: column col182_219 is of type float[] and thus is not indexable (SQLSTATE 0A000)
```

cc @ajwerner for triage

Jira issue: CRDB-6482

**Comment by RaduBerinde** [comment]
CI ran into the same: https://teamcity.cockroachdb.com/viewLog.html?buildId=2863454&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_Test

I will skip for now, it doesn't seem like anyone is actively looking at it.

**Comment by ajwerner** [comment]
Ack will look at it when next at the computer

**Comment by postamar** [comment]
Considering that the test has been unskipped since then I'm going to draw the conclusion that this issue is stale. Closing.
