### ISSUE TITLE
sql: COPY IN BINARY doesn't return correct format code to client

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#63235]
lib/pq's `txn.Prepare("COPY temp (num) FROM STDIN WITH binary")` should fail with `pq: only text format supported for COPY`, however this does not happen for CRDB, no error is returned. 

The error should be generated by lib/pq here: https://github.com/lib/pq/blob/master/copy.go#L89

Roughly 9/10 times no error will be returned, however 1/10 `pq: unrecognized client message type ClientMsgSimpleQuery` is returned.

To reproduce (This correctly errors when pointing it to a pg db):
Start a CRDB Cluster
1. `cockroach demo --empty `
2. Run the following script after replacing the postgres url with the one given by CRDB's console.
```
package main

import (
	"database/sql"
	"log"

	_ "github.com/lib/pq"
)

func main() {
	db, err := sql.Open("postgres", "postgres://root:admin@127.0.0.1:55977?sslmode=require")

	if err != nil {
		log.Fatal("error connecting to the database: ", err)
	}

	defer db.Close()

	txn, err := db.Begin()
	if err != nil {
		panic(err)
	}
	defer txn.Rollback()
	_, err = txn.Exec("CREATE TEMP TABLE temp (num INTEGER)")
	if err != nil {
		panic(err)
	}

	println("prepare?")
	_, err = txn.Prepare("COPY temp (num) FROM STDIN WITH binary")
	if err != nil {
		panic(err.Error())
	}

	// check that the protocol is in a valid state
	err = txn.Commit()
	if err != nil {
		panic(err)
	}
}
```

**Comment by knz** [comment]
Hi Richard 
1) here and in the future, prefer using+recommending `cockroach start-single-node` to `demo`

2) lib/pq I think implements delayed evaluation until things are actually used. Have you tried with pgx?

**Comment by RichardJCai** [comment]
> Hi Richard
> 
> 1. here and in the future, prefer using+recommending `cockroach start-single-node` to `demo`
> 2. lib/pq I think implements delayed evaluation until things are actually used. Have you tried with pgx?

1. Noted. 
2. I have not tested with pgx, I created an issue for this because it is the reason for a test flake for the lib/pq roachtest. https://github.com/cockroachdb/cockroach/issues/57855

**Comment by rafiss** [comment]
I found that this is because we don't implement this part of the spec correctly:

> The CopyInResponse, CopyOutResponse and CopyBothResponse messages include fields that inform the frontend of the number of columns per row and the format codes being used for each column.

https://www.postgresql.org/docs/13/protocol-flow.html#PROTOCOL-COPY

See `BeginCopyIn`, which always uses `FormatText`: https://github.com/cockroachdb/cockroach/blob/c0d3c906ea86df5f2fddcc796c9a9a5640b0c2a7/pkg/sql/pgwire/conn.go#L1106-L1113

Will fix it.
