### ISSUE TITLE
testing: test memory overhead of many prepared statements in idle connections

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#63248]
As a followup to https://github.com/cockroachdb/cockroach/issues/62525, let's see if prepared statements add additional memory overhead.

**Comment by RichardJCai** [comment]
Did some very informal testing for this just preparing a hundred thousand statements.

It seems like memory overhead can grow arbitrarily but overall the memory usage is very low (likely just the string).

ie.
```
PREPARE y30 AS SELECT 123::string;
PREPARE y31 AS SELECT 123::string;
PREPARE y32 AS SELECT 123::string;
PREPARE y33 AS SELECT 123::string;
PREPARE y34 AS SELECT 123::string;
PREPARE y35 AS SELECT 123::string;
PREPARE y36 AS SELECT 123::string;
PREPARE y37 AS SELECT 123::string;
PREPARE y38 AS SELECT 123::string;
PREPARE y39 AS SELECT 123::string;
```

Oops this comment should go in #63248
