### ISSUE TITLE
sql: would like to know current retry start time in crdb_internal.node_queries

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#63254]
Right now, `crdb_internal.node_queries.start` corresponds to the `sessionQueryReceiver` phase timestamp. If a query is retried 1000 times, the table doesn't tell me the start of the current iteration. And I'd like to know it.

Also, as it stands, `node_queries.start` is below the start time of the corresponding txn in `crdb_internal.node_transactions` - which txn start time is captured at the executor level, not at the pgwire level (so it's later). This looks weird.

Jira issue: CRDB-6492

**Comment by knz** [comment]
Andrei van you give us a bit more context, a use case for example, that motivates the request?

**Comment by andreimatei** [comment]
We have a lot of these cases where a query gets retried forever. When you're looking at such a case, I'd like to get some idea about how long each retry takes (a better idea than just divinding the total time by the number of requests). I've also wanted to know if I caught the current attempts towards its beginning or towards its end, to corroborate that with various logspy.
