### ISSUE TITLE
opt: ORDER BY random() results in significantly slower performance

### ISSUE THREAD

**Issue by andyyang890** [cockroachdb/cockroach#63276]
**Describe the problem**

I have two large tables called `countries` and `places` and running the following query takes about 400ms locally:
```
SELECT st_astext(c.geom), st_astext(p.geom)
  FROM countries c
  JOIN places p
  ON ST_Intersects(c.geom, p.geom)
  LIMIT 1;
```

However, when I add an `ORDER BY random()` clause, it takes 83s
```
SELECT st_astext(c.geom), st_astext(p.geom)
  FROM countries c
  JOIN places p
  ON ST_Intersects(c.geom, p.geom)
  ORDER BY random()
  LIMIT 1;
```

Here are the query plans:
```
root@:26257/defaultdb> explain SELECT st_astext(c.geom), st_astext(p.geom)
  FROM countries c
  JOIN places p
  ON ST_Intersects(c.geom, p.geom)
  ORDER BY random() LIMIT 1;
                                               info
---------------------------------------------------------------------------------------------------
  distribution: full
  vectorized: true
  • limit
  │ estimated row count: 1
  │ count: 1
  │
  └── • sort
      │ estimated row count: 18,725
      │ order: +column226
      │
      └── • render
          │ estimated row count: 18,725
          │
          └── • lookup join
              │ table: places@primary
              │ equality: (gid) = (gid)
              │ equality cols are key
              │ pred: st_intersects(geom, geom)
              │
              └── • inverted join
                  │ table: places@places_geom_idx
                  │
                  └── • scan
                        estimated row count: 255 (100% of the table; stats collected 23 days ago)
                        table: countries@primary
                        spans: FULL SCAN
(27 rows)
Time: 3ms total (execution 2ms / network 0ms)
root@:26257/defaultdb> explain SELECT st_astext(c.geom), st_astext(p.geom)
  FROM countries c
  JOIN places p
  ON ST_Intersects(c.geom, p.geom)
  LIMIT 1;
                                             info
-----------------------------------------------------------------------------------------------
  distribution: full
  vectorized: true
  • render
  │ estimated row count: 1
  │
  └── • limit
      │ estimated row count: 1
      │ count: 1
      │
      └── • lookup join
          │ table: places@primary
          │ equality: (gid) = (gid)
          │ equality cols are key
          │ pred: st_intersects(geom, geom)
          │
          └── • inverted join
              │ table: places@places_geom_idx
              │
              └── • scan
                    estimated row count: 255 (100% of the table; stats collected 23 days ago)
                    table: countries@primary
                    spans: FULL SCAN
(23 rows)
Time: 3ms total (execution 2ms / network 0ms)
```

**Expected behavior**
The query should still return quickly due to the LIMIT 1.

**Comment by nvanbenschoten** [comment]
I wonder whether we consider this to be surprising or a bug. `LIMIT 1` without an `ORDER BY` means something different than `ORDER BY random() LIMIT 1`.

The former means that any row can be returned and the query can short circuit as soon as that one row is returned. If the query is run 10 times, it can return the same row 10 times or 10 different rows. 

The latter means that every row should have an equal probability of being returned. So to ensure that, each of the 18,725 rows needs to be given a random probability (the `render`) and then the row with the highest value needs to be selected (the sort+limit). We can probably do something smarter (or maybe we are) about the top-k sort to turn the O(n log n) sort+limit into an O(n) sort+limit, but that won't significantly change the fact that these queries mean different things.

**Comment by andyyang890** [comment]
Ah I see, thanks for the explanation!

**Comment by knz** [comment]
Maybe it helps to understand that these clauses have precedence, by adding explicit parentheses. That is

Select .. from (select ... Order by) limit 1

And

Select ... From (select ... Limit 1) order by

Are two different things. The first one needs to process all the rows, because a limit doesn't propagate into a sort.

In the second one the sort can be eliminated altogether.

**Comment by knz** [comment]
(does this issue need to remain open?)

**Comment by rytaft** [comment]
It seems to me that this is working as expected. Feel free to reopen if you feel otherwise.
