### ISSUE TITLE
gogoproto: calling .String() can panic

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#63299]
**Describe the problem**

For some reason, `(*raftpb.Entry).String()` panics, see https://github.com/cockroachdb/cockroach/pull/63298:

> "field raftpb.Entry.Term has invalid type: got uint64, want pointer"

This smells a lot like it has something to do with `(gogoproto.nullable)=true`:

```
message Entry {
	optional uint64     Term  = 2 [(gogoproto.nullable) = false]; // must be 64-bit aligned for atomic operations
	optional uint64     Index = 3 [(gogoproto.nullable) = false]; // must be 64-bit aligned for atomic operations
	optional EntryType  Type  = 1 [(gogoproto.nullable) = false];
	optional bytes      Data  = 4;
}
```

The panic is emitted from the go**lang**proto table marshaling code, which is
unexpected to me.

The `raftpb` package is also using gogoproto, so I don't understand why. It must be some kind of version incompatibility; it doesn't panic from within the upstream repo.

This seems like a time bomb, so we should investigate.

**To Reproduce**

See the unit test added in https://github.com/cockroachdb/cockroach/pull/63298.

**Expected behavior**

Stringers should string :-)

**Additional data / screenshots**

**Environment:**
- master at time of writing

**Additional context**

**Comment by tbg** [comment]
Possibly related to https://github.com/cockroachdb/cockroach/issues/56378 /cc @knz

**Comment by erikgrinaker** [comment]
I think this is fixed by https://go-review.googlesource.com/c/protobuf/+/300869/ which specifically mentions the etcd types.

**Comment by tbg** [comment]
Great, so we need to update protobuf to pick up that commit?

**Comment by erikgrinaker** [comment]
Think so.


>The raftpb package is also using `gogoproto`, so I don't understand why. It must be some kind of version incompatibility; it doesn't panic from within the upstream repo.

Looks like it defer to golang proto for string formatting:

https://github.com/cockroachdb/vendored/blob/4d6e89235f6ac5c478ebcc3e9ef073914ac7348e/go.etcd.io/etcd/raft/v3/raftpb/raft.pb.go#L13

https://github.com/cockroachdb/vendored/blob/4d6e89235f6ac5c478ebcc3e9ef073914ac7348e/go.etcd.io/etcd/raft/v3/raftpb/raft.pb.go#L274

**Comment by knz** [comment]
I remember for #56147 I had to regenerate the raft protos. Anyway to ensure that I'm doing the right thing there?

**Comment by knz** [comment]
What's the next action here now that gogoproto is updated? Also update protobuf? (I think that my PR was doing that, unsure)

**Comment by erikgrinaker** [comment]
`master` now pulls in `google.golang.org/protobuf v1.26.0`, which [has the relevant fix](https://github.com/protocolbuffers/protobuf-go/releases#v1.26-support-aberrant-types), so I suspect this should just work now (making this PR obsolete). But we should verify this.

**Comment by erikgrinaker** [comment]
Can confirm that this works on `master`, as `cockroach debug range-data` outputs entries without panic'ing. Think we can close this and #63298 @tbg.

**Comment by tbg** [comment]
Thank you!

**Comment by knz** [comment]
@erikgrinaker @tbg do we want to backport the protobuf upgrade (and the gogoproto one) to the 21.1 branch too?

**Comment by erikgrinaker** [comment]
Might be good to let the Protobuf upgrade bake on `master` for a bit. I'm also not sure if this qualifies as a release blocker and thus is eligible for `release-21.1` backport this late in the game. I'll defer to @tbg.
