### ISSUE TITLE
asynchronous applyCommitedEntries maybe get lower latency

### ISSUE THREAD

**Issue by ysbarney** [cockroachdb/cockroach#63294]
I stress cockroach by sysbench-1.0.4 
in oltp_insert scene

![image](https://user-images.githubusercontent.com/9624794/113986589-fe523100-987f-11eb-9d2d-0d567d9810a8.png)

**Comment by nvanbenschoten** [comment]
Hi @ysbarney, thanks for the issue! You're absolutely right that asynchronous state machine application has the potential to speed up write-heavy workloads. This is something we've been tracking in https://github.com/cockroachdb/cockroach/issues/17500 and are eager to explore further. I'm going to close this issue in favor of that one.
