### ISSUE TITLE
workload/schemachange: add support for ALTER TYPE to the schema change workload

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#63330]
**Is your feature request related to a problem? Please describe.**

Currently, we only have support for creating user defined types in the schema change workload. #59197 hopes to add `ALTER TYPE ... DROP VALUE` to the schema change workload, but we should to a step further and add other flavours of `ALTER TYPE` as well. I'm most interested in `ALTER TYPE ... ADD VALUE`, which includes options to control placement of new values, which could benefit from randomized testing. 

Jira issue: CRDB-6530

Epic CRDB-19168

**Comment by fqazi** [comment]
Fixed via: https://github.com/cockroachdb/cockroach/pull/118780
