### ISSUE TITLE
sql: some errors are missing details field (for PG compat)

### ISSUE THREAD

**Issue by dougmrqs** [cockroachdb/cockroach#63332]
**Is your feature request related to a problem? Please describe.**
Sequelize cannot generate errors properly. It seems related to a lack of a **details** field at message byte parsing. Handling the [error 23505](https://github.com/sequelize/sequelize/blob/main/lib/dialects/postgres/query.js#L316), specially.

**Describe the solution you'd like**
I think working with a D: field as seen on [pg-protocol](https://github.com/brianc/node-postgres/blob/master/packages/pg-protocol/src/parser.ts#L357), would do the trick. I am not sure how exactly are the messages generated by pg.

**Describe alternatives you've considered**
I'm currently skipping the test that requires it, despite the problem is just about error description, it did not caused major issues yet.

**Additional context**
The test I'm talking about, is: 
https://github.com/sequelize/sequelize/blob/main/test/integration/model/create.test.js#L130
The actual message I receive is about complex clauses: 
```
{
  S: 'ERROR',
  C: '23505',
  F: 'errors.go',
  L: '98',
  R: 'NewUniquenessConstraintViolationError',
  M: `duplicate key value (username)=('gottlieb') violates unique constraint "users_username_key"`
}
```

Jira issue: CRDB-6532

**Comment by rafiss** [comment]
thanks for getting to the bottom of this @dougmrqs !

are you able to try with Postgres and share the message format that it returns to sequelize?

**Comment by dougmrqs** [comment]
I don't have the time right now, but I'll try it as soon as I am able.

**Comment by dougmrqs** [comment]
Another example with [this test](https://github.com/cockroachdb/sequelize-cockroachdb/pull/103/files#diff-518463a293a80c79434c02c415c34bf66f789e3d796a1f927fa8a2d8ed73e6e2R40):

CRDB responds:
```
{
  S: 'ERROR',
  C: '23505',
  F: 'errors.go',
  L: '98',
  R: 'NewUniquenessConstraintViolationError',
  M: `duplicate key value (uniqueName)=('unique name one') violates unique constraint "models_uniqueName_key"`
}
```

PG responds:
```
{
  S: 'ERROR',
  V: 'ERROR',
  C: '23505',
  M: 'duplicate key value violates unique constraint "models_uniqueName_key"',
  D: 'Key ("uniqueName")=(unique name one) already exists.',
  s: 'public',
  t: 'models',
  n: 'models_uniqueName_key',
  F: 'nbtinsert.c',
  L: '527',
  R: '_bt_check_unique'
}
```

**Comment by dougmrqs** [comment]
> thanks for getting to the bottom of this @dougmrqs !
> 
> are you able to try with Postgres and share the message format that it returns to sequelize?

I've hardcoded the `D:` as `'Key (username)=(gottlieb) already exists.'` and the test passed. Logging it with PG, the detail field showed that string.

**Comment by rafiss** [comment]
It looks like CockroachDB now returns the details field. This is what CRDB returns:
<img width="719" alt="image" src="https://user-images.githubusercontent.com/1320573/213760919-8992f734-e968-430a-a6f3-ec7812d424da.png">


and this is what Postgres retuns:
<img width="750" alt="image" src="https://user-images.githubusercontent.com/1320573/213760804-031198f6-1398-472b-b233-804301f5ef7b.png">
