### ISSUE TITLE
server: make the multi-tenant architecture available to on prem users

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#63375]
This is a meta issue.

- productionize the sql pod initialization so it benefits from the same CLI UX
- document the basics: create a tenant, set up certs, start sql pod
- clean up the situation around cluster settings (fixme: introduce link to relevant issue)

Jira issue: CRDB-6553

Epic CRDB-14537

**Comment by knz** [comment]
Example use case: #63206

**Comment by cucxabong** [comment]
hi there,

I see you guys mark this issue as completed, could you share related documents on this kind of setup?
