### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#634]
- [x] Architecture
- [ ] API Docs
- [ ] Developer Docs
- [ ] Marketing Docs
- [ ] Jepsen Test

**Comment by xaprb** [comment]
IMO the biggest single improvement in documentation right now would be 25 words in the readme explaining what kind of data, workloads, etc this is useful for. Without reading source code right now I have no idea -- is it relational, document, key-value, blob... should I think of it like Dynamo, S3... I have no reason to be interested in it, as a visitor who knows nothing more.

**Comment by petermattis** [comment]
@xarpb Thanks for the input. The document situation is currently completely inadequate, but I'd also note that the product is still pre-alpha.

**Comment by xaprb** [comment]
True. What does it do, though? Or what is it meant to do? I ask genuinely
out of interest. I'd even be happy to read an external article if you have
a link handy. I'm not trying to criticize the docs.

**Comment by petermattis** [comment]
The alpha of CockroachDB will be a scalable, strongly consistent, transactional key-value store. Think DynamoDB, but built with transactions from the get-go and open source so you can run your own cluster. The roadmap has plans for adding a structured data API: schemas, indexes and the like.

**Comment by xaprb** [comment]
Excellent, thanks!

**Comment by vivekmenezes** [comment]
Baron,

Perhaps the architecture diagram and description will provide you with a
high level view for what we are building.

https://github.com/cockroachdb/cockroach/blob/master/README.md#architecture

And in particular, we are building the system in stages bottom up.

Vivek

**Comment by knz** [comment]
Some Jepsen stuff in https://github.com/knz/jepsen/blob/master/README.md

**Comment by jseldess** [comment]
Current docs here (not yet beta-complete): http://www.cockroachlabs.com/docs/

**Comment by petermattis** [comment]
Documentation issues are now tracked in https://github.com/cockroachdb/docs.
