### ISSUE TITLE
DBConsole: transactions page doesn't let me filter for txns with no app

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#63419]
Looking at a customer cluster, this is the options the filter gives me. This is not what I want; I want the queries that don't match either apps - `internal` or `sql shell`. I want the queries their app makes, which I'm guessing probably don't have an app set.
![Screenshot from 2021-04-09 20-37-33](https://user-images.githubusercontent.com/377201/114252535-c2989380-9973-11eb-8480-04911f3c88dd.png)

**Comment by maryliag** [comment]
Can you see the statements you want when selecting `all`? If you do, can you confirm they indeed have no app name when checking their details page?

**Comment by andreimatei** [comment]
I was seeing the statement with `all`, yeah. Too late to check anything else.

**Comment by kevin-v-ngo** [comment]
I attempted a repro creating a python app with psycopg2 . When app name is empty, the value is "unset":

![image](https://user-images.githubusercontent.com/81193618/118906987-9c033c00-b8d3-11eb-9fc5-6ad54fdd36e7.png)

This value appears in the filter:

![image](https://user-images.githubusercontent.com/81193618/118907082-c1904580-b8d3-11eb-9bc9-b489de0c0ee6.png)

I believe we can close this unless there is another repro.

**Comment by knz** [comment]
Can you run this test with an app name containing only spaces or tabs.

I just noticed in andrei's screenshot there is a blank line in-between the two internal values. I think that's an app name with just spaces.

**Comment by knz** [comment]
if confirmed we may want to indicate that fact visually
