### ISSUE TITLE
More granular S3 bucketing 

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#63470]
This came from a request from a customer:

When writing to S3 - we [delineate files into folders  by day](https://www.cockroachlabs.com/docs/stable/create-changefeed.html#files). This is undesirable at their scale (multi terabyte table) as it makes searching much less efficient.

The customer requested that we instead give the option to delineate by hour. I would anticipate there will be other desirable bucketing patterns that will come up for other use cases.

The scope of this issue is to add a query parameter for cloud storage sinks for bucket write patterns (file_format="HOUR") and add a write pattern for prefixing writes with the day/hour/ file pattern instead of day/.

In terms of time zones / determining when to switch to the next hour bucket - we should stay consistent with how we do it today when determining what day prefix to use. 

In terms of format - we should use the range 00-23 to describe the hour (2021-02-24/00/, 2021-02-24/01/, 2021-02-24/02/, and so on).

Epic CRDB-9196

**Comment by amruss** [comment]
From CDC discussion, an additional option is to set in path: ie experimental-s3://bucket-path/%d/%h/%m

**Comment by HonoreDB** [comment]
I think with the way s3 prefixes work, we could make this nonconfigurable and just output prefixes in a slash-delimited, strictly-ordered-by-reverse-granularity format like "Y/M/D/H/Min/Sec" and the consumer side could choose which granularity level to treat as the "folder".

**Comment by samiskin** [comment]
@HonoreDB If what you're talking about is an S3-specific capability then I think we'd still need configurability on our side for other types of storage sinks (like nodelocal which I'm using for testing atm)
