### ISSUE TITLE
stability: OOM soon after start

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6352]
build sha: 3ff5ac8
gamma cluster node 0 (`104.196.125.166`) running with block_writer and photos.

About 30 minutes after start, OOM killer killed the node.

Heap profile shows:
```
(pprof) top
12882.93kB of 14931.11kB total (86.28%)
Dropped 915 nodes (cum <= 74.66kB)
Showing top 10 nodes out of 124 (cum >= 512.44kB)
      flat  flat%   sum%        cum   cum%
 3072.28kB 20.58% 20.58%  3072.28kB 20.58%  github.com/cockroachdb/cockroach/util/interval.(*Node).insert
 2096.42kB 14.04% 34.62%  2096.42kB 14.04%  github.com/codahale/hdrhistogram.New
 2056.01kB 13.77% 48.39%  2056.01kB 13.77%  github.com/cockroachdb/cockroach/sql/pgwire.(*readBuffer).readUntypedMsg
 1536.19kB 10.29% 58.68%  4608.47kB 30.86%  github.com/cockroachdb/cockroach/storage.(*TimestampCache).Add.func1
 1024.72kB  6.86% 65.54%  1024.72kB  6.86%  github.com/cockroachdb/cockroach/sql/pgwire.decodeOidDatum
 1024.05kB  6.86% 72.40%  1024.05kB  6.86%  github.com/cockroachdb/cockroach/roachpb.(*Span).Unmarshal
  528.17kB  3.54% 75.93%   528.17kB  3.54%  google.golang.org/grpc/transport.newFramer
  520.04kB  3.48% 79.42%   520.04kB  3.48%  github.com/coreos/etcd/raft/raftpb.(*Entry).Unmarshal
  512.62kB  3.43% 82.85%   512.62kB  3.43%  golang.org/x/net/http2/hpack.(*dynamicTable).add
  512.44kB  3.43% 86.28%   512.44kB  3.43%  encoding/pem.Decode
```

Attaching full node log and pdf of heap profile.
[heap.pdf](https://github.com/cockroachdb/cockroach/files/238918/heap.pdf)
[node0.log.txt](https://github.com/cockroachdb/cockroach/files/238919/node0.log.txt)

**Comment by mberhault** [comment]
In general, I'm seeing the first node reaching much higher memory usage than the other ones.
eg: ~9GiB vs ~100Mib on beta, ~4GiB vs ~100Mib on gamma (just restarted the first node), and ~13Gib vs ~6Gib on rho (running with race detector)

**Comment by bdarnell** [comment]
Is this new or has node 0 always had higher memory usage?

How is the first node different from the others (in a way that is similar across the two clusters)? None of the clients hardcode node 0, right? 

The one thing I see is that the first node doesn't have the `--join` flag that the other ones do. This should be fine, although it would be preferable to pass the same join flag to all nodes after the cluster has been initialized. This results in some slightly different code paths to be taken through gossip. I see some possible bugs there but nothing that could plausibly result in huge memory usage. 

The memory usage is not in the go heap so the heap profile isn't helpful: `I160427 15:30:31.426265 server/status/runtime.go:160  runtime stats: 14 GiB RSS, 200 goroutines, 20 MiB active, 8901.10cgo/sec, 0.28/0.03 %(u/s)time, 0.03 %gc (9x)`

**Comment by mberhault** [comment]
It's the first node being started. I've been using what I call node 0 (the first one in my list) as the starter node since the beginning, all others join it shortly after (nodes are started sequentially: nodeN gets started by supervisor. once done, we move on to nodeN+1).

Yeah. the heap profiles aren't particularly helpful. I'm trying to get jemalloc to work, but I'm having issues.

**Comment by bdarnell** [comment]
Being the first to start could cause a node to be burdened with a lot of range leaderships (that the other nodes lost when it was their turn to restart), but that wouldn't explain why node 0 (and only node 0) would consume extra memory when it's restarted after the other nodes are up.

**Comment by mberhault** [comment]
interestingly, it's not just memory that's way up compared to the other nodes. cpu utilization and live bytes is also two orders of magnitude greater.

In the case of beta, the log attached in this bug is from cluster init, node0 was never shut down. However, even after restart, this still occurs.

**Comment by mberhault** [comment]
ok, finally got my jemalloc builds to work.

After restarting the first node, we climbed to ~2GiB RSS within a few minutes.
```
I160428 13:40:28.956936 server/status/runtime.go:160  runtime stats: 2.2 GiB RSS, 258 goroutines, 106 MiB active, 70170.13cgo/sec, 2.62/0.32 %(u/s)time, 0.00 %gc (8x)
```

C-side heap shows:
```
Total: 1844.0 MB
  1355.1  73.5%  73.5%   1355.1  73.5% rocksdb::UncompressBlockContents
   415.8  22.5%  96.0%   1770.8  96.0% rocksdb::ReadBlockContents
    35.5   1.9%  98.0%     40.0   2.2% rocksdb::::ShardedLRUCache::Insert
    21.0   1.1%  99.1%   1715.5  93.0% rocksdb::::ReadBlockFromFile
     6.3   0.3%  99.4%      6.3   0.3% rocksdb::Arena::AllocateNewBlock
     4.4   0.2%  99.7%      4.4   0.2% rocksdb::::HandleTable::Resize
     3.8   0.2%  99.9%      3.8   0.2% std::string::_Rep::_S_create
     2.0   0.1% 100.0%      2.0   0.1% std::vector::_M_emplace_back_aux
     0.0   0.0% 100.0%     60.8   3.3% 00007fee13c09e9c
     0.0   0.0% 100.0%     60.8   3.3% 00007fee143e46a9
```

Heap graph:
[heap.pdf](https://github.com/cockroachdb/cockroach/files/240621/heap.pdf)

**Comment by petermattis** [comment]
That looks correct. Most of the memory is being used by the RocksDB cache. What size cache is the process configured with?

**Comment by mberhault** [comment]
given that and the ~10GiB rocksdb data (vs ~50MiB for other nodes), I'm guessing we're writing something we probably shouldn't.

**Comment by mberhault** [comment]
still a quarter of the memory, but just checking, looks like we're overflowing something:
```
  cache_index_and_filter_blocks: 0
  index_type: 0
  hash_index_allow_collision: 1
  checksum: 1
  no_block_cache: 0
  block_cache: 0x7f5b640008d0
  block_cache_size: 2305843009213692928
  block_cache_compressed: (nil)
  block_size: 4096
  block_size_deviation: 10
  block_restart_interval: 16
  filter_policy: rocksdb.BuiltinBloomFilter
  whole_key_filtering: 1
  skip_table_builder_flush: 0
  format_version: 2
```

**Comment by mberhault** [comment]
meh:

```
$ cat /sys/fs/cgroup/memory/memory.limit_in_bytes
9223372036854771712
```

I'll fix it.

**Comment by mberhault** [comment]
while that PR fixes the unbounded memory usage, that was still not specific to the first node, all of them had the issue. Still, between that and my jemalloc builds finally working, I'll analyze further and open a separate issue about memory growth once I have details.
