### ISSUE TITLE
jobs: unable to mark as reverting, expected session X, found 0

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#63534]
From `./cockroach workload fixtures import tpcc --warehouses=2000 --checks=false --partitions=3` on 9 node roachprod cluster:

```
		 | Error: importing fixture: importing table order_line: pq: job 649569800911618049: could not mark as reverting: job 649569800911618049: with status ''running'': expected session '373c715a4a0142c1bd26c258ee61e069' but found NULL: job 649569800911618049: with status ''running'': expected session '373c715a4a0142c1bd26c258ee61e069' but found NULL
```

Ran this on https://github.com/cockroachdb/cockroach/pull/63533, i.e. off a slightly stale commit on release-21.1.

Jira issue: CRDB-6626

**Comment by tbg** [comment]
I still have this cluster btw, if that helps at all. It has full history of disk writes.

**Comment by ajwerner** [comment]
I don't know that a full history of writes is that interesting. It's saying that the job session which saw some error and wanted to mark the job as reverting lost its lease before marking it reverting. That should be fine, seems like it was not.

**Comment by ajwerner** [comment]
I want to know what the error was that it was going to revert over.

**Comment by ajwerner** [comment]
Oh, this is "totally fine". The problem here is that import is not robust to the coordinator failing. We failed to heartbeat liveness here. The job would resume. The error reporting is hilariously bad but I'm not sure that the bug here is as bad.
