### ISSUE TITLE
sql: TestCancelQueryPermissions flaking

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#63547]
The `TestCancelQueryPermissions` flaked with:

```
=== RUN   TestCancelQueryPermissions/unpermissioned_users_cannot_cancel_other_users
panic: Fail in goroutine after TestCancelQueryPermissions/non-admins_with_CANCELQUERY_can_cancel_non-admins has completed

goroutine 365437 [running]:
testing.(*common).Fail(0xc00757e780)
	/usr/local/go/src/testing/testing.go:688 +0x125
testing.(*common).FailNow(0xc00757e780)
	/usr/local/go/src/testing/testing.go:710 +0x2b
testing.(*common).Fatalf(0xc00757e780, 0x47c9e4c, 0x1c, 0xc00ba7a4a0, 0x2, 0x2)
	/usr/local/go/src/testing/testing.go:806 +0x93
github.com/cockroachdb/cockroach/pkg/testutils/sqlutils.(*SQLRunner).ExpectErr(0xc002060fa8, 0x560fca0, 0xc00757e780, 0x47b8f45, 0x18, 0x47b6bed, 0x18, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/testutils/sqlutils/sql_runner.go:97 +0x1c5
github.com/cockroachdb/cockroach/pkg/sql_test.TestCancelQueryPermissions.func2.1(0xc0136594f0, 0xc002586340, 0xc00757e780)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/run_control_test.go:327 +0xae
created by github.com/cockroachdb/cockroach/pkg/sql_test.TestCancelQueryPermissions.func2
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/run_control_test.go:318 +0x13d
```

Flake can be found at - https://teamcity.cockroachdb.com/viewLog.html?buildId=2876992&buildTypeId=Cockroach_UnitTests

Not skipping for now, as we have only seen one instance of it.

**Comment by rafiss** [comment]
Interesting.. I unskipped this a month ago since I couldn't reproduce the flake under stress: https://github.com/cockroachdb/cockroach/pull/62132

**Comment by RaduBerinde** [comment]
https://teamcity.cockroachdb.com/viewLog.html?buildId=2989990&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_Test

**Comment by tbg** [comment]
This has gotten much more prevalent, skipping this test.

The problem is that the test is doing illegal things. It leaks a bunch of goroutines that outlive the subtest and may end up accessing `t`.

**Comment by tbg** [comment]
(It uses `t` when there are test failures, so not saying the problem is just with the test. The problem is that the test explodes when it actually finds a problem).

**Comment by tbg** [comment]
I should also mention, I tried to fix this test, but it's not easy since `ctx` cancellation doesn't work (lib/pq)? There isn't a good way to force the `pg_sleep` to terminate when the subtest is done.

**Comment by tbg** [comment]
(One way to do it is to set up a new testserver for each subtest)
