### ISSUE TITLE
schema: `remote wall time is too far ahead` error considered permanent

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#63636]
I saw this on a roachprod cluster, which have been having trouble with clocks over the past few months. A large `ALTER TABLE ADD COLUMN` schema change hit a clock sync error:
```
job 649711962939129857: cannot be reverted, manual cleanup may be required: remote wall time is too far ahead (998.616155ms) to be trustworthy
```
This error can be bubbled up if hit [here](https://github.com/cockroachdb/cockroach/blob/46401472ab79dbe6c103a54886d71dc21ecf7835/pkg/kv/kvserver/store_send.go#L90). It is currently non-structured and is created [here](https://github.com/cockroachdb/cockroach/blob/87ed071f5a23295b34fd4d56d4539f0d0207f937/pkg/util/hlc/hlc.go#L422).

The schema then seemed to get stuck in this state. Future attempts to re-run the schema change hit:
```
ERROR: duplicate: column "crdb_region" in the middle of being added, not yet public
```
We should make sure that there is some way to recover from this error.

**Comment by ajwerner** [comment]
I think we'll just want to make this error structured and then detect it in `isPermanentSchemaChangeError`. One day we should get more principled about what is a permanent schema change error. I'd love to go the other way and make things non-permanent by default. That comes with its own challenges. A prerequisite to that is #44954.
