### ISSUE TITLE
sql: Consider unifying typing algorithm comments and tests

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#6365]
From @knz with regard to type checking algorithms: 

"The tests containing examples that justify each of these typing rules really ought to stand out as comments next to the rule they justify. Otherwise it is just too easy to get lost and lose track of things while reading this code. 

In other words we should see these tests defined primarily right here in comments. We then should have a tool that extracts example-comments from this file (and a few others) and generate a test source from them."

**Comment by knz** [comment]
Pending #6895  and #7083.
