### ISSUE TITLE
bulk-io: limit memory used by index backfill's span iteration

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#63662]
The following logic in `SchemaChanger.distIndexBackfill` iterates over each span that will be backfilled to populate the timestamp cache. In doing so, it reads chunks of 10k keys for KV. Ideally, this would use some kind of KV operation that does not require pulling the key-values back after bumping the timestamp cache, but such an operation does not currently exist. So for now, we should make sure that it is not a potential cause of OOMs by accounting for the memory and assigning a byte limit to the operation.

https://github.com/cockroachdb/cockroach/blob/f60daea1297e4ab84be428e045a4d985fbe29718/pkg/sql/backfill.go#L995-L1012

This would be easier to do if we had https://github.com/cockroachdb/cockroach/issues/63661. Without that, we may need to issue raw ScanRequests with a `TargetBytes` set like the `txnKVFetcher` does.

It may also be possible to express this as a statement to run through an internal executor, which will better manage memory.

**Comment by dt** [comment]
I think this is a non-issue thanks to #63945 and the span always being (near) empty, so I'm going to optimistically close this for now as wontfix.
