### ISSUE TITLE
cli: remove cgosymbolizer

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#63719]
Go 1.14 [introduced](https://golang.org/doc/go1.14#runtime) a new [async preemptive scheduler](https://github.com/golang/proposal/blob/master/design/24543-non-cooperative-preemption.md) for goroutines. However, there seems to be some interaction between this, macOS Big Sur, and Cgo that causes CockroachDB goroutines using Pebble to randomly block forever and the runtime to spin at 100% CPU (see  https://github.com/golang/go/issues/45558 and https://github.com/cockroachdb/pebble/issues/1111).

We should consider disabling async preemption on macOS, e.g. by setting `GODEBUG=asyncpreemptoff=1` and re-execing the binary, to avoid this problem until a fix is available.

It's also worth noting that CockroachDB 21.1 will be the first release that uses async preemption (20.2 was built with Go 1.13). We haven't seen any indications of problems on e.g. Linux, but it's something to look out for.

**Comment by knz** [comment]
I'm in favor of this. The lower performance that would result is OK as macOS is not a supported deployment platform.

Also it's possible that this will help with #57885  and  #62283.

**Comment by erikgrinaker** [comment]
The actual culprit turned out to be `cgosymbolizer`, removing the import fixes the issue.
