### ISSUE TITLE
kv: Clean up snapshot rate limits

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#63728]
Raft snapshots are currently governed by two rate limit settings, `kv.snapshot_rebalance.max_rate` and `kv.snapshot_recovery.max_rate`. They currently default to the same value and we recommend that if one is changed, the other be changed to match. In that case there is no good reason to have two settings; we should consolidate on one and get rid of the other (this has been a longstanding TODO in the code but there doesn't seem to have been an issue for it until now)

On the other hand, things have changed enough that we might want to improve the prioritization scheme and use two different values for the rate limits. The idea behind the two settings is that the higher priority "recovery" limit is used when the snapshot is necessary to bring a range in compliance with its survivability goals, with the lower "rebalance" limit used at other times. We deprecated the use of two separate rate limits for two reasons:
- The classification was not always accurate and snapshots that should have been "recovery" priority were not getting marked as such (this was largely due to the messiness of the code in this area, and also some ambiguity in some cases due to the lack of explicit survival goals for diversity). 
- Because of the `concurrentSnapshotApplyLimit` (which is currently 1), we had priority inversion problems in which a slow rebalance snapshot would tie up the one allowed snapshot slot, preventing a higher-priority recovery snapshot from proceeding. 

Now that we have streaming snapshots, we could consider raising the `concurrentSnapshotApplyLimit` (and reserve some slots for recovery snapshots). With atomic replica changes and explicit survival goals for multi-region clusters, we should now be able to accurately classify snapshots based on whether or not they are necessary for survival goals. With those two changes, the rebalance/recovery rate limit settings make sense again and we could leave them as two separate options. 

Jira issue: CRDB-6748

**Comment by andrewbaptist** [comment]
My plan for this is to deprecate the `recovery` setting and only leave the rebalance setting. We would apply the recovery rate to all snapshot transfers from 23.2 onwards. Ideally, we will be able to continue to bump this rate (and eventually move it away from public facing) once admission control is able to properly mediate snapshot transfer rates.
