### ISSUE TITLE
bulkio: improve UX for 'cockroach userfile list' on a new cluster

### ISSUE THREAD

**Issue by smcvey** [cockroachdb/cockroach#63769]
On a new cluster, or when no userfiles have been created before, running this command:

```
# cockroach userfile list
```

produces this error message:

```
E210415 20:46:54.627934 1 cli/error.go:398  unable to match pattern provided: failed to list files from file table: pq: relation "defaultdb.public.userfiles_root_upload_files" does not exist
ERROR: relation "defaultdb.public.userfiles_root_upload_files" does not exist
SQLSTATE: 42P01
Failed running "userfile list"
```
If a file is then created and deleted, so that the list of files is empty, running the command now doesn't produce that error message:

```
# cockroach userfile list
(no output)
```

Running `cockroach userfile list` when there are no existing userfiles, should just produce no output as it does once the `userfiles_root_upload_files` table exists.  Perhaps attempting to list files causes a `CREATE TABLE IF NOT EXISTS` or something similar.

**Comment by shermanCRL** [comment]
Ah, looks like we already have it here: https://github.com/cockroachdb/cockroach/issues/59245

Will close this a duplicate.
