### ISSUE TITLE
Missing proper error handling for specific CockroachDB error by NodeJS "pg" library

### ISSUE THREAD

**Issue by andiolsi** [cockroachdb/cockroach#63782]
### Preface
When communicating with CockroachDB there is at least one error message/code that is not being displayed properly.

Issue MAY be on the libraries end for not handling a properly emitted error. 

I just want to put this here in case it is not. 
I also opened an issue over at the affected library.

https://github.com/brianc/node-postgres/issues/2522

For me this is no longer problematic as I now know how to handle it.  But other folks may not be so lucky.

### Occuring error:

`Error: Connection terminated unexpectedly`

### Expected behavior

Proper error with error code and text.

### Test

Insert anything larger than _sql.conn.max_read_buffer_message_size_ (default 16MiB) into a field of CockroachDB.

### Handling in other tools
Error displayed in query analyzer (Table Plus):

```
ERROR:  message size 18 MiB bigger than maximum allowed message size 16 MiB
HINT:  the maximum message size can be configured using the sql.conn.max_read_buffer_message_size cluster setting
```

**Comment by rafiss** [comment]
Thanks for the report @andiolsi! the error message you shared from the other tool (`ERROR:  message size 18 MiB bigger than maximum allowed message size 16 MiB`) is generated within CockroachDB. So it seems that the `pg` library is doing something else so that it doesn't get this message.

Can you share more details about what you are doing when you get the error?

cc @RichardJCai

**Comment by andiolsi** [comment]
I hit the magic size with a JSONB data structure. 
Basically any insert statement that exceeds 16meg will trigger the error.

`SET CLUSTER SETTING sql.conn.max_read_buffer_message_size = '32MiB';`. will raise this limit.

**Comment by rafiss** [comment]
Closing this since it seems like CockroachDB is returning the error as expected
