### ISSUE TITLE
kv: don't bump transaction on closed timestamp when re-writing existing intent 

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#63796]
As observed in https://github.com/cockroachdb/cockroach/issues/36478#issuecomment-521903404 and later discussed in #41720, this could help prevent starvation scenarios in cases where a transaction:
```
- scans a large number of rows in a GLOBAL table
- writes a row in a GLOBAL table, gets its timestamp bumped on the closed timestamp
- attempts to refresh and fails due to conflicting writes that invalidated its read
- retries and rewrites the same rows
```
If a rewrite of the intent did not get bumped on the closed timestamp, which is [safe](https://github.com/cockroachdb/cockroach/issues/36478#issuecomment-521903404), we could avoid this transaction retrying indefinitely.

This is coming up in kvnemesis + `global_reads`: https://github.com/cockroachdb/cockroach/pull/63747.

Jira issue: CRDB-6778

**Comment by nvanbenschoten** [comment]
cc. @andreimatei in case you want to add anything here from our recent discussion about this.

**Comment by andreimatei** [comment]
What we discussed with @nvanbenschoten and @ajwerner was that a request that only writes to keys on which the transaction holds replicated locks shouldn't consult the timestamp cache / the closed timestamp.

To take advantage of this observation, we need a mechanism for efficiently figuring out if a request is only touching locked keys. The lock table is that, except currently it doesn't contains locks corresponding to intents that no conflicting reader has ran into; writing an intent does not populate the lock table for optimistic memory usage reasons. One proposal was that writing intents could populate the cache starting at epoch two. This way, most transactions are unaffected, but a transaction that failed to refresh once (and was forced to restart) would switch to this mode where it can write to the keys that it wrote in previous epochs without interacting with the closed timestamp.

**Comment by ajwerner** [comment]
>One proposal was that writing intents could populate the cache starting at epoch two. 

nit: IIRC epochs start at 0, so maybe at epoch 1 we start to populate the lock table
