### ISSUE TITLE
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

### ISSUE THREAD

**Issue by martinrode** [cockroachdb/cockroach#63813]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to port an existing postgres app  to cockroach.

**Describe the solution you'd like**
Support pg default transaction level.

**Describe alternatives you've considered**
Getting crazy refactoring our whole application in order to work with Cockroaches default level of serialization.

**Comment by jordanlewis** [comment]
Hi @martinrode,

I'm going to close this issue as "won't fix", to indicate that we're not planning to ever implement the `READ COMMITTED` isolation in CockroachDB.

I'm interested to hear more about your experiences, however. What are you having trouble fitting into CockroachDB's default isolation level? For example, are you concerned with reads acting in a non-blocking way when there is a pending write? Or are you having trouble with drivers or ORMs that are behaving in a way that is not expected?
