### ISSUE TITLE
testing: test pgbouncer with transaction pooling

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#63874]
In https://github.com/cockroachdb/cockroach/issues/62529 we used session pooling mode, which has one backend connection for each frontend connection.

PGBouncer also does transaction pooling, which has one backend connection only for each active transaction. In this mode, prepared statements must be disabled. Let's test with this mode to see if there are immediate performance benefits.

We will use the pgx option `PreferSimpleProtocol`.

**Comment by RichardJCai** [comment]
Did some experimentation with transaction pooling.

In summary, aside from prepared statements, transaction pooling seems to work fine with CockroachDB.
I was able to test transaction pooling with TPCC by building workload off this branch https://github.com/cockroachdb/cockroach/pull/65668

By capping the number of active connections to the database from PGBouncer using the option `max_db_connections` I found that TPCC would perform better using transaction pooling than session pooling. Ie, capping the connections to CRDB at 100 and using 1000 connections to PGBouncer and running TPCC, it looked like transaction pooling allowed us to get better use out of fewer connections to the DB. With session pooling, it seemed like connections would sometimes be forced to wait a while until it was able to grab a connection.

Users can find benefit if they need to cap # of connections to the DB for whatever reason but still allowing many connections by using PGBouncer with transaction pooling.
