### ISSUE TITLE
sql: improve tuple index spans

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#6390]
Things missing from the current tuple index selection code:
- Prefixes (https://github.com/cockroachdb/cockroach/blob/69c632d58928ab5a51117be8352bde770d7fc118/sql/index_selection.go#L573)
- Multi-directional indexes (https://github.com/cockroachdb/cockroach/blob/69c632d58928ab5a51117be8352bde770d7fc118/sql/index_selection.go#L586, https://github.com/cockroachdb/cockroach/blob/c7d6b66b20047dcb623fbeb89100a40a1ba7f0a8/sql/index_selection_test.go#L531)

**Comment by mjibson** [comment]
The prefix thing appears to be fixed, although I'm not sure when or how:

```
> create table t (a int, b int, c int, index (a, b, c));
root@:26257> explain select * from t where (a, b) > (1, 2);
+-------+------+---------------------+
| Level | Type |     Description     |
+-------+------+---------------------+
|     0 | scan | t@t_a_b_c_idx /1/3- |
+-------+------+---------------------+
(1 row)
root@:26257> explain select * from t where (a, b) < (1, 2);
+-------+------+-----------------------+
| Level | Type |      Description      |
+-------+------+-----------------------+
|     0 | scan | t@t_a_b_c_idx /#-/1/2 |
+-------+------+-----------------------+
(1 row)
root@:26257>  
```

**Comment by RaduBerinde** [comment]
I think the prefix thing was the other way around - having an index on `(a, b)` and having a condition with more columns `(a, b, c) > (1, 2, 3)`. That condition implies `(a, b) >= (1, 2)` so we could use that to make a span with that index.

**Comment by RaduBerinde** [comment]
Regarding the second bullet point: if we have `(a,b,c) > (1,2,3)` and an index on `(a ASC, b DESC, c ASC)`, we can't do better than just restrict to `a >= 1`. To get a constraints on all columns, the expression would need to be e.g. `(a, -b, c) > (1, -2, 3)`.
