### ISSUE TITLE
opt: audit panic catching in the optimizer

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#63946]
As shown in #63378, there are some places in the optimizer where we do not catch panics and probably should. However, there are other places where we probably catch too many panics. We should ensure that the optimizer catches panics when it is safe to do so (e.g., an index out of range error occurring within the optimizer code), and does not catch panics when it is unsafe (e.g., a panic occurring in the kv layer while using the internal executor to query the DB). 

In general, inside the optimizer it should always be safe to catch panics as long as they do not originate outside of the catalog.

This issue covers the work to add panic catching inside `parseStats` and limit the scope of panic catching in other places in the optimizer.

Jira issue: CRDB-6834

**Comment by mgartner** [comment]
Going to close this for now. If we see more panics of this nature, we can fix them as needed, and decide to audit in the future if necessary.
