### ISSUE TITLE
Add JDBC URL to connection parameters list printed by "cockroach demo"

### ISSUE THREAD

**Issue by electrum** [cockroachdb/cockroach#63962]
It would be helpful to have a JDBC URL to paste into a local Java program for testing.

**Comment by ajwerner** [comment]
Hi @electrum, nice that you're playing with cockroach. Is that URL any different from just putting a `jdbc:` in front of the printed `sql` url?

**Comment by electrum** [comment]
It's not that simple. Start with this:
```
(sql/tcp) postgres://root:admin@127.0.0.1:64584?sslmode=require
```
> No suitable driver found for postgres://root:admin@127.0.0.1:64584?sslmode=require

Add the `jdbc:` prefix:
```
jdbc:postgres://root:admin@127.0.0.1:64584?sslmode=require
```
> No suitable driver found for jdbc:postgres://root:admin@127.0.0.1:64584?sslmode=require

Ok, change `postgres` to `postgresql`:
```
jdbc:postgresql://root:admin@127.0.0.1:64584?sslmode=require
```
> org.postgresql.Driver parseURL WARNING: JDBC URL must contain a / at the end of the host or port: ...
> No suitable driver found for jdbc:postgresql://root:admin@127.0.0.1:64584?sslmode=require

At least now we are getting to the driver. Add the trailing `/`:
```
jdbc:postgresql://root:admin@127.0.0.1:64584/?sslmode=require
```
> org.postgresql.util.PSQLException: The connection attempt failed.
> Caused by: java.net.UnknownHostException: root:admin@127.0.0.1

Looks like we need to convert the user and password into parameters:
```
jdbc:postgresql://127.0.0.1:64584/?sslmode=require&user=root&password=admin
```
Success!

**Comment by knz** [comment]
looking at this in #65460.
