### ISSUE TITLE
geoprojbase: do not allocate projections with a static map

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#63969]
Currently https://github.com/cockroachdb/cockroach/blob/master/pkg/geo/geoprojbase/projections.go is a ~99k line file that generates ~10MB to the release binary.

We can reduce this by storing this metadata as a compressed string, which can be initialized on the first instantiation of `Projection`. Alternatively, we should probahly use `go:embed` now that that's out.

Potentially a good first issue, but a meaty one.

**Comment by RaduBerinde** [comment]
This shouldn't be too hard since we can just modify the template to generate whatever we want. Where does one find the `srids.csv` file that was used? (feels like it should be checked in with `generate-spatial-ref-sys`)

**Comment by otan** [comment]
>  Where does one find the srids.csv file that was used? 

would've been smart but may have been lost to time. may have to generate anything off the existing map :|

**Comment by RaduBerinde** [comment]
Ah, too bad. Should I nuke `cmd/generate-spatial-ref-sys/` then?

**Comment by otan** [comment]
actually, you should be able to do `copy spatial_ref_sys to '/tmp/srids.csv' DELIMITER ';' CSV HEADER;`

**Comment by RaduBerinde** [comment]
I was able to generate a json from the hardcoded constants, but it would be nice if we could generate it directly from the `csv`. I don't have PostGIS installed and having some trouble making it work, I asked for some help with that on the spatial slack.

**Comment by RaduBerinde** [comment]
Unfortunately, the `cockroach` binary links in `randgen` which has some global constants that use `geo.MustParseGeography`. I was hoping we wouldn't even decode this stuff until and unless geospatial stuff is being used.

**Comment by otan** [comment]
csv: https://gist.github.com/otan/73f201cf89aeec458db6e19957567ba6

> which has some global constants that use geo.MustParseGeography

:( yeah ... 

i mean if you really wanted to, we could make `Projection` lazily load the embedded file and make a variation of MustParseGeography that doesn't check the SRID exists in the projection map.

**Comment by RaduBerinde** [comment]
Thank you! I don't think `randgen` should be linked at all, hopefully we'll fix as part of #74120. If we really need it, we should move all those datum creations under an initialization function.

**Comment by RaduBerinde** [comment]
> csv: https://gist.github.com/otan/73f201cf89aeec458db6e19957567ba6

This results in about 20% more stuff. I will move forward with the data that we have already, but I will include the updated `generate-spatial-ref-sys` which can be used to generate an updated file.

**Comment by otan** [comment]
more stuff is ok imo, more in line with postgis. but your call!

**Comment by RaduBerinde** [comment]
Sure, but that should be separate, I don't want the data and the mechanism to change together.
