### ISSUE TITLE
storage: Optimize splitting large ranges and don't rebalance them

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#6400]
On the beta cluster, we have a range that for some reason failed to split for a long time (for reasons that are still unclear). This cluster is currently configured to split at 6MB; this range had managed to grow to 6GB. Attempting to split such a huge range can cause other problems (such as blocking for a long time while it recomputes range stats). We should impose some sort of limit to ensure that if we do have trouble splitting a range, it won't continue growing without bound. For example, we could block all writes to a range that is more than 2x or 3x the configured split limit (except those writes necessary to perform a split).

**Comment by tschottdorf** [comment]
In your opinion, what are the primary reasons for such a range split to be problematic? If we split chunks off on the right side, the recomputation should be ok (since we recompute only one half - if that's always the small one, seems fine).

The reason I'm asking is because preventing huge ranges also means losing service, which is bad. Also, there may be use cases for huge ranges, for example bulk loading a large initial data set which is only slowed down by the presence of multiple ranges on the system, and which would benefit from setting an infinite max range size.

We could invest that energy in writing a test that lets the SplitQueue loose on a ~10gb range and making sure that it works instead.

**Comment by bdarnell** [comment]
I see two problems with huge ranges:
* The entire `processRaft` goroutine is blocked for the duration of the split trigger, so other commands aren't getting processed anyway. It looks like the split trigger can take several minutes on a multi-GB range (although this is not completely clear from the logs)
* If the rebalancer attempts to move a huge range before it splits, the entire contents of the range will have to be held in memory for the snapshot.

**Comment by tschottdorf** [comment]
Ok, what if we fix your first bullet point (assuming it's not too hard, see my comment) and instead prevent the rebalancer from tackling huge ranges?

**Comment by bdarnell** [comment]
Yeah, this need goes away (or at least becomes much lower priority: maybe we'd want a hard limit at 10x the split size instead of 2-3x) if we could make `splitTrigger` fast and make sure that the rebalancer doesn't try to move ranges that are above the target size.

**Comment by petermattis** [comment]
`splitTrigger` currently does work that is O(size-of-range). In particular, the stats computation and abort cache copying. The stats computation in particular is going to be problematic unless it can be eliminated. For a 1GB tablet, we're looking at 20-30 second for the stat computation under optimistic scenarios about how fast we can read the data.

I wonder if there could be some sort of pre-split step. That is, when we decide to split a range, we asynchronously choose a split point and then mark the range as "pre-split" at that point and continue with normal operations, but start maintaining MVCCStats separately for both sides of the range. We then asynchronously compute the stats for one of the halves using a snapshot that was taken when the range was marked as "pre-split". When finished, we commit the split by merging in the stats for the two halves that were being incrementally updated with the stats we computed from the snapshot. This sounds irritating to get correct, but it would remove stats computation from the critical path.

**Comment by tschottdorf** [comment]
As pointed out above, the stats computation only needs to compute stats for
one half of the split. Is that not correct?

On Fri, Apr 29, 2016 at 9:22 AM Peter Mattis <notifications@github.com>
wrote:

> splitTrigger currently does work that is O(size-of-range). In particular,
> the stats computation and abort cache copying. The stats computation in
> particular is going to be problematic unless it can be eliminated. For a
> 1GB tablet, we're looking at 20-30 second for the stat computation under
> optimistic scenarios about how fast we can read the data.
>
> I wonder if there could be some sort of pre-split step. That is, when we
> decide to split a range, we asynchronously choose a split point and then
> mark the range as "pre-split" at that point and continue with normal
> operations, but start maintaining MVCCStats separately for both sides of
> the range. We then asynchronously compute the stats for one of the halves
> using a snapshot that was taken when the range was marked as "pre-split".
> When finished, we commit the split by merging in the stats for the two
> halves that were being incrementally updated with the stats we computed
> from the snapshot. This sounds irritating to get correct, but it would
> remove stats computation from the critical path.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/6400#issuecomment-215709447>
>
-- 

-- Tobias

**Comment by petermattis** [comment]
@tschottdorf Yes, we already do that (compute stats for one half of the split). For a 1GB range, we'd have to compute stats on ~512MB of data. If we were able to scan that data and compute stats at ~20MB/sec (which is very optimistic), it would still take 26sec to compute the stats. Seems to me that splitting large ranges requires moving the O(size-of-range) work out of the critical path. For example, `AdminSplit` chooses a split point by scanning over the data without blocking other operations.

**Comment by tschottdorf** [comment]
That's if you split in the middle, but why not just carve off 64mb chunks?
Sure, there are some benefits to splitting in the middle, but worth a lot
of additional complexity?

On Fri, Apr 29, 2016 at 10:23 AM Peter Mattis <notifications@github.com>
wrote:

> @tschottdorf <https://github.com/tschottdorf> Yes, we already do that
> (compute stats for one half of the split). For a 1GB range, we'd have to
> compute stats on ~512MB of data. If we were able to scan that data and
> compute stats at ~20MB/sec (which is very optimistic), it would still take
> 26sec to compute the stats. Seems to me that splitting large ranges
> requires moving the O(size-of-range) work out of the critical path. For
> example, AdminSplit chooses a split point by scanning over the data
> without blocking other operations.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/6400#issuecomment-215733418>
>
-- 

-- Tobias

**Comment by petermattis** [comment]
That's a good point. Guess I missed that above when you suggested it. You'd actually want to carve off 32MB chunks.

**Comment by tschottdorf** [comment]
Can't blame you, wasn't really that well-worded. Looks like we recompute the left half of the split, so that's already the correct one! If we pass the max range size to the split key computation, there shouldn't be much left to do (maybe some safeguarding to avoid that splits at specific keys (think zone config change) hit a range when that would create a very large left side -- should wait for the size-based splits to happen first).

**Comment by bdarnell** [comment]
#6447 fixed half of this. The remaining work is to make `MVCCFindSplitKey` carve off 32MB (`maxBytes / 2`) chunks from the left side of the range, instead of looking for the midpoint.
