### ISSUE TITLE
ui: add checking for extraneous dependencies

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#6401]
We should add checking for extraneous dependencies so you don't accidentally commit without saving new dependencies.

I know `npm list` returns a non-zero value if there are errors (eg extraneous deps) so that could be a start.

**Comment by nvanbenschoten** [comment]
@couchand do you envision ever addressing this? is it even relevant anymore given all of the changes to the admin ui build system? If not, we should close it and re-open if necessary.

**Comment by couchand** [comment]
@nvanbenschoten I don't think this has been a problem recently, we can revisit if it becomes one.
