### ISSUE TITLE
sql: Investigate type checking once on an entire statement

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#6402]
We currently type check each `parser.Expr` in a `parser.Statement` separately, allow discrepancies on when segments of the statement are type checked. We should consider running a visitor globally on the statement passed into `executor.Prepare` to get us to the top of all expression trees (filters, limits, etc.) within the statement before calling the recursive `parser.TypeCheck` on these expressions. This would allow us to consider expressions "well-typed" from this point onward.

One issue here would be determining the desired types of these expressions. Mapping statement types to desired types (eg. `Limit -> DInt`) is straightforward enough. However, it's unclear how we would know what types to desire for expressions that are children of statements like inserts or updates. This may prevent us from doing type checking this early, but we should investigate before eliminating the idea.

**Comment by RaduBerinde** [comment]
I don't think this applies anymore. Type-checking is driven by the optbuilder, which makes sense because that's the part of the system that "understands" the semantics of SQL.
