### ISSUE TITLE
workload: add observability via prometheus endpoint

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#64068]
**Is your feature request related to a problem? Please describe.**

We would like to deploy workload on long-running clusters in CockroachCloud as part of dog-fooding and release qualification.
This would be greatly simplified if workloads could register metrics which would then be made available to prometheus, as this would neatly fit into our existing prometheus-based alerting infrastructure.

**Describe the solution you'd like**
See above.

**Describe alternatives you've considered**
We can stick to or vary the current setup in which workloads primarily print a table of measurements. While it makes sense to print measurements (workloads is invoked interactively quite a bit) it is not the best way to plumb these into our cloud infra.

**Additional context**

We may also want to add customer-provided workloads over time, which may be provided in different languages and frameworks. Prometheus is advantageous here because there are integrations for any conceivable language and environment.

Tagging this for @cockroachdb/test-eng to help out and orchestrate work.
cc @joshimhoff @cockroachdb/release @udnay

**Comment by udnay** [comment]
This is cool. I assume this is just for staging so seeing the metrics shouldn't be an issue before centralized monitoring lands. I'm not sure how we roll out prometheus configs and if we can change them between clusters, looks like prometheus has a [PushGateway](https://prometheus.io/docs/practices/pushing/) that seems like it could be a fit if we don't have anything else.

**Comment by tbg** [comment]
I'm not sure about the CC side of things, but the ticket to refer to is https://cockroachlabs.atlassian.net/browse/CC-4044

**Comment by joshimhoff** [comment]
I actually closed that ticket, @tbg, and opened this one for the same thing: https://cockroachlabs.atlassian.net/browse/CC-4064

It is part of this jira epic titled "improve legibility & reliability of paid serverless & dedicated via high signal to noise CRDB DML alerting": https://cockroachlabs.atlassian.net/browse/CC-4054. All feedback on the whole jira epic is appreciated. Various things we've talked about are captured there (e.g. kvprober that does writes, even alert on stuck applied index + "probe" failures), but all in one place, to help us see the bigger picture. The CC + CRDB jira split is unfortunate...

> I'm not sure how we roll out prometheus configs and if we can change them between clusters, looks like prometheus has a PushGateway that seems like it could be a fit if we don't have anything else.

We roll prom configs out via `intrusion update-monitoring`. This command updates k8s config maps in the CC k8s clusters.

> I assume this is just for staging so seeing the metrics shouldn't be an issue before centralized monitoring lands.

See the jira epic for more (https://cockroachlabs.atlassian.net/browse/CC-4054) but the plan is to run workload in **production** for two use cases:

1. Alerting on reliability & perf of serverless clusters.
2. Alerting on reliability & perf of release qualification dedicated clusters running latest patch version.

Is the issue you are pointing out being dev seeing the metrics? I'm gonna open up a new issue in that jira epic to enable dev seeing the metrics. I think we'll need to do something less costly to build than cent monitoring given our backlog & HC numbers. Or maybe superuser scope reduction will be ready by July...

**Comment by joshimhoff** [comment]
Issue for getting dev access to all prod time-series metrics: https://cockroachlabs.atlassian.net/browse/CC-4082

**Comment by tbg** [comment]
@otan has picked this up for test-engs first milestone, PR here: https://github.com/cockroachdb/cockroach/pull/66224

**Comment by tbg** [comment]
As of https://github.com/cockroachdb/cockroach/pull/66313 workload now has all of its histograms exposed via TPCC, which in particular gives the successful request counts per operation. That should be ample to work with for https://cockroachlabs.atlassian.net/browse/CC-4054, and it's not straightforward to add bespoke metrics where required.
