### ISSUE TITLE
roachtest: nodes die during tpccbench/nodes=3/cpu=16 on master

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#64093]
I am trying to run `tpccbench/nodes=3/cpu=16` at 98ba7f36ec

Iterations consistently fail because of dead nodes:
```
1: kill exited nonzero
1: dead
17:50:38 tpcc.go:976: --- SEARCH ITER FAIL: TPCC 2100 resulted in 0.0 tpmC and failed due to monitor failure: unexpected node event: 1: dead
```
I couldn't find much information, as the cluster is reset for the next iteration. I am trying with an earlier commit.

**Comment by RaduBerinde** [comment]
Seems like it works fine at an earlier commit: 09be4f72a0

**Comment by RaduBerinde** [comment]
@yuzefovich `git bisect` points to c3b16171e2a886a9a92a1d824226d06e89fffeed   Can you take a look? I'm just running `roachtest run tpccbench/nodes=3/cpu=16`.

**Comment by RaduBerinde** [comment]
Hm, not super sure anymore, I see some failures with the preceding commit 786869b6ab as well.

**Comment by yuzefovich** [comment]
I imagine it might be somewhat non-deterministic. Do you have a log from a dead node? (I'm guessing it would show the reason for the crash, which might be - but unlikely - the same as #64100.)

**Comment by RaduBerinde** [comment]
I couldn't see anything in the logs, but the roachtest resets the cluster immediately and starts another iteration. We should try to repro without the roachtest, so we can investigate. I didn't get a chance to do that.

**Comment by RaduBerinde** [comment]
I'll try again after the fix for #64100 goes in.

**Comment by RaduBerinde** [comment]
Hm, actually, I can't imagine it's the same root cause, this is a mkrelease binary, the panic injection stuff shouldn't be enable.

**Comment by yuzefovich** [comment]
It's possible that #64100 is reproduced in a release binary (for example, if we are almost at the --max-sql-memory limit, and then a vectorized operator requests some memory in `Init` which is denied, it'll panic in `Init` which might have the same effect as #64100 depending on the flow); though I agree it's extremely unlikely to be the same root cause. Possibly it has something to do with sampling, so like increasing sample rate from 0.01 to 1.0 might make the reproduction more likely.

**Comment by yuzefovich** [comment]
I'm taking a look at this issue right now.

**Comment by yuzefovich** [comment]
I think I have a repro. I followed the steps of `tpccbench` manually on dd5b8366d0cbd996d3154b4645aa7d157aab7b2a. I barely ssh'd into n1, and for some reason `top` reported that `cockroach` process was using 95% of memory, however, the profile shows only a couple of GB of usage. Here is what I see in the logs from node 3:
```
I210423 03:18:54.002947 323 2@server/status/runtime.go:553 ⋮ [n3] 1643  runtime stats: 13 GiB RSS, 3891 goroutines (stacks: 171 MiB), 5.6 GiB/8.4 GiB Go alloc/total (heap fragmentation: 926 MiB, heap reserved: 1.4 GiB, heap released: 45 MiB), 3.8 GiB/4.8 GiB CGO alloc/total (47620.9 CGO/sec), 1203.3/105.5 %(u/s)time, 0.0 %gc (0x), 124 MiB/126 MiB (r/w)net
I210423 03:19:04.013726 323 2@server/status/runtime.go:553 ⋮ [n3] 1644  runtime stats: 13 GiB RSS, 4403 goroutines (stacks: 191 MiB), 6.0 GiB/8.4 GiB Go alloc/total (heap fragmentation: 690 MiB, heap reserved: 1.1 GiB, heap released: 36 MiB), 3.8 GiB/4.8 GiB CGO alloc/total (48018.3 CGO/sec), 1158.3/96.0 %(u/s)time, 0.0 %gc (0x), 114 MiB/126 MiB (r/w)net
I210423 03:19:07.773726 44 gossip/client.go:129 ⋮ [n3] 1645  closing client to n1 (‹35.229.64.48:26257›): stopping outgoing client to n1 (‹35.229.64.48:26257›); already have incoming
W210423 03:19:07.774441 79 2@gossip/gossip.go:1496 ⋮ [n3] 1646  first range unavailable; trying remaining resolvers
I210423 03:19:07.781782 4575669 gossip/client.go:124 ⋮ [n3] 1647  started gossip client to ‹10.142.0.209:26257›
I210423 03:19:07.783926 4575669 gossip/client.go:129 ⋮ [n3] 1648  closing client to n1 (‹10.142.0.209:26257›): stopping outgoing client to n1 (‹10.142.0.209:26257›); already have incoming
I210423 03:19:08.780936 4576156 gossip/client.go:124 ⋮ [n3] 1649  started gossip client to ‹10.142.0.207:26257›
I210423 03:19:10.090369 4577102 gossip/client.go:124 ⋮ [n3] 1650  started gossip client to ‹10.142.0.209:26257›
I210423 03:19:10.098420 4577102 gossip/client.go:129 ⋮ [n3] 1651  closing client to n1 (‹10.142.0.209:26257›): stopping outgoing client to n1 (‹10.142.0.209:26257›); already have incoming
I210423 03:19:10.247173 325 kv/kvserver/liveness/liveness.go:1227 ⋮ [n3,liveness-hb] 1652  retrying liveness update after ‹liveness.errRetryLiveness›: ‹result is ambiguous (context done during DistSender.Send: context deadline exceeded)›
W210423 03:19:10.250366 325 kv/kvserver/liveness/liveness.go:821 ⋮ [n3,liveness-hb] 1653  slow heartbeat took 4.505842184s; err=context deadline exceeded
W210423 03:19:10.250425 325 kv/kvserver/liveness/liveness.go:723 ⋮ [n3,liveness-hb] 1654  failed node liveness heartbeat: ‹operation "node liveness heartbeat" timed out after 4.5s›
W210423 03:19:10.250425 325 kv/kvserver/liveness/liveness.go:723 ⋮ [n3,liveness-hb] 1654 +(1) ‹operation "node liveness heartbeat" timed out after 4.5s›
W210423 03:19:10.250425 325 kv/kvserver/liveness/liveness.go:723 ⋮ [n3,liveness-hb] 1654 +Wraps: (2) context deadline exceeded
W210423 03:19:10.250425 325 kv/kvserver/liveness/liveness.go:723 ⋮ [n3,liveness-hb] 1654 +Error types: (1) *contextutil.TimeoutError (2) context.deadlineExceededError
```
All 3 nodes have very high RSS (almost at OOM), but none of the nodes actually crashed. The heap profiles around when the problems started happening account only for 1-2GB of usage, everything else is unclear.

At this point I'm not sure what is the cause of the regression, but I'm not sure how c3b1617 would increase the memory usage drastically.

**Comment by tbg** [comment]
https://roachperf.crdb.dev/?filter=&view=tpccbench%2Fnodes%3D3%2Fcpu%3D16&tab=gce also shows what looks like the beginning of a regression at least potentially.

**Comment by tbg** [comment]
Btw, nodes dying "is expected" on tpccbench when it's in overload regime (maybe admission control will one day change that 🤞🏽) We currently configure that TPCC test with an estimated max of 2100, which means that this is the starting point for the line search:

https://github.com/cockroachdb/cockroach/blob/de7047c379be80df08ca740bd77d9f150002ec90/pkg/cmd/roachtest/tpcc.go#L414

The roachperf link (see last comment) suggests that it should usually pass at 2100. So it looks like we're looking at a potential regression.

The node crashes that we expect here are related to out-of-memory. They should either surface in `X.dmesg.txt` in artifacts (oomkiller) or in `cockroach-stderr.*.log`, but note that there is some logging bug that prevents this sometimes (https://github.com/cockroachdb/cockroach/issues/63910), though I did try to work around it (https://github.com/cockroachdb/cockroach/pull/63472) but have not been able to confirm my workaround in practice yet.

**Comment by yuzefovich** [comment]
Interestingly, Radu bisected this issue to the same commit as Tobi in #62320. There appears to be multiple significant regressions too, e.g. https://roachperf.crdb.dev/?filter=&view=ycsb%2FB%2Fnodes%3D3%2Fcpu%3D32&tab=gce.

I don't immediately see what's wrong with c3b16171e2a886a9a92a1d824226d06e89fffeed, but possibly I should be using newly introduced struct by pointer rather than by value. I'll look into it tomorrow.

**Comment by RaduBerinde** [comment]
I don't see why the introduced struct could be a problem. More likely, we're now losing some closers and failing to clean up stuff. Maybe we could add some "test closers" similar to the invariants checker which verify that they always get called.

**Comment by yuzefovich** [comment]
Yeah, we do have it in place (and it actually recently fired in #64248).

One somewhat plausible explanation is that embedding of `OpWithMetaInfo` struct into `NewColOperatorResult` by value increased the size of the latter slightly which moved the latter struct into larger allocation class, or something like that. But I wouldn't expect it to have such a large impact. Possibly the pooling of some objects is now screwed up - so we not only don't reuse them, but also block on the mutex of `sync.Pool` while always creating a new object.

**Comment by RaduBerinde** [comment]
> Btw, nodes dying "is expected" on tpccbench when it's in overload regime

Do we have any data about how much more memory we would need so that this doesn't happen? I would venture a guess that we are pretty close even with passing # of warehouses, which means that some day we may make some improvements that would allow for more warehouses but the benchmark wouldn't show it because of memory.

It's worth noting that with less than 16 CPUs, we use `n1-standard-` instances but with 16 and above we use `n1-highcpu-`. This means that with cpu=8 we have 60GB of RAM, and with cpu=16 we only have 14.4GB. Maybe we should be using only standard instances?

**Comment by yuzefovich** [comment]
Did a quick sanity check about the sizes of the structs, and there is actually a minor improvement:
before:
```
NewColOperatorArgs size 232
NewColOperatorResult size 176
```
after
```
NewColOperatorArgs size 208
NewColOperatorResult size 176 
```

**Comment by yuzefovich** [comment]
I think I have a fix - got 10 successful runs with https://github.com/cockroachdb/cockroach/pull/64453/commits/e05af1c526e77e28c85940a7fa1bfbc42fe73d2e.

I still don't fully understand why c3b1617 would have such a noticeable difference, but my guess is that
> possibly I should be using newly introduced struct by pointer rather than by value

seems to be correct.
