### ISSUE TITLE
bazel: logictests failing in bazel

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#64096]
[log.txt](https://github.com/cockroachdb/cockroach/files/6360705/log.txt)

This has been failing routinely in CI since yesterday. `c3b16171e2a886a9a92a1d824226d06e89fffeed` appears to be the regressor.

**Comment by rickystewart** [comment]
@yuzefovich Can you take a peek at that log and tell me if anything jumps out at you as an obvious cause of the issue?

**Comment by yuzefovich** [comment]
The log doesn't seem to contain any useful info (the stack trace at the bottom is expected), seems like the process crashed or something like that. Possibly the SHA you linked broke something, not sure, possibly this issue is related to #64100.

**Comment by rickystewart** [comment]
Seems healthier today, not sure if you or someone else did something to fix it, either way thanks :)
