### ISSUE TITLE
sql: a view expression which uses an enum array value may prevent enum value drops

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#64101]
**Describe the problem**

Consider the following setup: 

```
demo@127.0.0.1:26257/movr> CREATE TYPE abc AS ENUM('a', 'b', 'c');
CREATE TYPE

Time: 9ms total (execution 8ms / network 0ms)

demo@127.0.0.1:26257/movr> CREATE VIEW v AS SELECT ARRAY['a']:::_abc;
CREATE VIEW

Time: 41ms total (execution 18ms / network 24ms)

demo@127.0.0.1:26257/movr> ALTER TYPE abc DROP VALUE 'b';
ERROR: could not validate removal of enum value "b": count-array-type-value-usage: at or near ")": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
SELECT unnest FROM (SELECT unnest(array) FROM [65 AS t]) WHERE unnest = x'80'
                                       ^
HINT: try \hf unnest
demo@127.0.0.1:26257/movr> ALTER TYPE abc DROP VALUE 'a';
ERROR: could not validate removal of enum value "a": count-array-type-value-usage: at or near ")": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
SELECT unnest FROM (SELECT unnest(array) FROM [65 AS t]) WHERE unnest = x'40'
                                       ^
```

Interestingly, if the view was constructed as following, things would work as expected:
```
 CREATE VIEW v2 AS SELECT ARRAY['a']:::_abc AS col;
```

The issue here is that the offending view query doesn't supply a name for the column. As such, the column is called "array". As "array" is a reserved keyword, our validation query encounters a syntax error. Unfortunately, this means we can't drop enum values that aren't used by the view either. 

**Describe the solution you'd like**
When constructing the validation query we should refer to the column in the unnest clause unambiguously. In the example above, we would say `unnest(v.array)` instead.

**Environment:**
 - CockroachDB version 21.1.beta4

**Comment by ajwerner** [comment]
Needs some double quotes.
