### ISSUE TITLE
sql: make spill to disk events more transparent

### ISSUE THREAD

**Issue by cucaroach** [cockroachdb/cockroach#64111]
Investigating the performance of some tpch queries I noticed the system doing a lot of write I/O that confused me as it wasn't apparent the query would ever need to spill to disk. 

It should be clearer when this happens, for instance perhaps the explain analyze output could include information about how much disk spilling I/O was performed.

For reference the root cause is a [known issue](https://github.com/cockroachdb/cockroach/issues/59409).  

explain analyze for this query:

```
  planning time: 262µs
  execution time: 10s
  distribution: full
  vectorized: true
  rows read from KV: 6,001,215 (806 MiB)
  cumulative time spent in KV: 4.9s
  maximum memory usage: 32 MiB
  network usage: 0 B (0 messages)
```

Adding a line about disk spilling usage would be nice.

**Comment by cucaroach** [comment]
[related](https://github.com/cockroachdb/cockroach/issues/56570)

**Comment by RaduBerinde** [comment]
I think it does show it, if it's not zero.

**Comment by cucaroach** [comment]
The explain analyze output above is for tpch query #1 which spills to disk, is there a trick to getting the spill to disk info to show up?   I know it spills to disk because query time is cut in half when I set sql.distsql.temp_storage.hash_agg.enabled = off and I see this activity when its on:

```
              cockroach`os.(*File).Write+0x8e
              cockroach`github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).Write.func1+0x63
              cockroach`github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).timeDiskOp+0xb7
              cockroach`github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).Write+0xab
              cockroach`github.com/cockroachdb/pebble/vfs.(*fdFileWrapper).Write+0x5a
              cockroach`github.com/cockroachdb/pebble/vfs.(*syncingFile).Write+0x67
              cockroach`github.com/cockroachdb/pebble/vfs.(*fdFileWrapper).Write+0x5a
              cockroach`github.com/cockroachdb/cockroach/pkg/sql/colcontainer.(*diskQueueWriter).compressAndFlush+0x162
              cockroach`github.com/cockroachdb/cockroach/pkg/sql/colcontainer.(*diskQueue).writeFooterAndFlush+0xbe
              cockroach`github.com/cockroachdb/cockroach/pkg/sql/colcontainer.(*diskQueue).Enqueue+0x337
              cockroach`github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils.(*SpillingQueue).Enqueue+0x231
              cockroach`github.com/cockroachdb/cockroach/pkg/sql/colexec.(*hashAggregator).Next+0x265
              cockroach`github.com/cockroachdb/cockroach/pkg/sql/colexec.(*diskSpillerBase).Next.func1+0x4e
              cockroach`github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError+0x57
              cockroach`github.com/cockroachdb/cockroach/pkg/sql/colexec.(*diskSpillerBase).Next+0xad
```

**Comment by yuzefovich** [comment]
I think we forgot on include the info about disk spilling into `explain/output.go` for `EXPLAIN ANALYZE` and possibly the only way to see whether disk spilling occurred is via the diagram in `EXPLAIN ANALYZE (DISTSQL)`.

**Comment by cucaroach** [comment]
Yes I made this my flex friday project and am testing a patch
