### ISSUE TITLE
log: %s semantics different from stdlib for nil pointers

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#64158]
I've seen this in a log message, resulting from using `%s` for printing a nil pointer of a type that implements `SafeFormatter` on a value receiver.
```
%!s(PANIC=SafeFormatter method: value method github.com/cockroachdb/cockroach/pkg/roachpb.Lease.SafeFormat called using nil *Lease pointer
```
This is different from what `fmt.Printf` does for the Stringer interface, where it prints `<nil>`. If possible, it'd certainly take the `<nil>`. I've found this thread that might describe how to handle this case in the logging lib: https://github.com/golang/go/issues/20995

**Comment by knz** [comment]
Can you file this upstream in the redact repo thanks

**Comment by andreimatei** [comment]
done https://github.com/cockroachdb/redact/issues/15
