### ISSUE TITLE
roachprod: very poor VM behavior when running out of memory

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#64176]
The behavior of roachprod VMs when cockroach is using too much memory is very poor. The cockroach process does not get killed, instead it - and the entire VM - is almost frozen up and is very slow to respond. Sshing into such a VM and running a few simple commands can take a very long time. Obviously the cluster and the UI are not responsive.

Eventually, the cockroach process dies but there is no mention of an "out of memory" kill. With #64177, I was able to figure out that we exit with code 8 (which is `exit.TimeoutAfterFatalError()`). I'm guessing that writing to the log file becomes too slow.

From what I googled, this is a common problem with linux but there are certain knobs and/or daemons (eg `earlyoom`) that can help with this. Ironically, the fact that there is no swap might be making this problem worse.

To reproduce, I create a four node roachprod cluster (with `--local-ssd`), start cockroach on nodes 1-3 and on node 4 I run `./workload tpch init --data-loader=import <pgurls..>` and `./workload run tpch --concurrency 100 --ramp 2m --tolerate-errors <pgurls..>`

CC @irfansharif @tbg

**Comment by tbg** [comment]
Welcome to my life. Agreed that it's bad.

See
https://github.com/cockroachdb/cockroach/pull/62361
https://github.com/cockroachdb/cockroach/pull/63472

and linked discussions (there are no answers yet).

**Comment by tbg** [comment]
What happens to this test case with #64177? Is the 95% memory limit adequate? How does exceeding the memory limit manifest in the collected artifacts? So far we are trained to look for the oom killer in dmesg.txt as well go runtime panics in `cockroach-stderr.log`, but I assume it won't show up in either.

**Comment by tbg** [comment]
Ah, it does go to dmesg:

```
[ 5247.106201] oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=/,mems_allowed=0,oom_memcg=/system.slice/cockroach.service,task_memcg=/system.slice/cockroach.service,task=cockroach,pid=9463,uid=1000
[ 5247.106370] Memory cgroup out of memory: Killed process 9463 (cockroach) total-vm:26718072kB, anon-rss:13888000kB, file-rss:27056kB, shmem-rss:0kB, UID:1000 pgtables:49892kB oom_score_adj:0
[ 5248.009133] oom_reaper: reaped process 9463 (cockroach), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

`cockroach.stderr.log` has, as expected:

> cockroach exited with exit code 137

Very nice.

**Comment by RaduBerinde** [comment]
Yeah it's still killed by the oom killer. I verified that with #64177 the process gets killed before we see any slowness in the VM. It's possible we can squeeze out more (e.g. 96%, 97%) but I don't think it's worth it. If we have tests that are so close, we should provision VMs with more memory or otherwise tone down the test.
