### ISSUE TITLE
Add time series counter for full table and full secondary index scans

### ISSUE THREAD

**Issue by lancel66** [cockroachdb/cockroach#64217]
**Is your feature request related to a problem? Please describe.**
Full table scans commonly cause problems with clusters including outage events. 

**Describe the solution you'd like**
We need to be able to alert for full table based on time series data.

**Describe alternatives you've considered**
Manually searching for full table scans in code which is time consuming and prone to error

gz#8135

**Comment by jordanlewis** [comment]
We've added a time series metric for this in 21.1, but it's not available on the main dashboard, only in a custom chart. Perhaps we should consider upgrading it.

cc @kevin-v-ngo
