### ISSUE TITLE
opt: performance regression on April 21st

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#64214]
roachperf graphs are showing a performance regression across the board on April 21st, e.g.:

<a href="https://roachperf.crdb.dev/?filter=&view=kv95%2Fenc%3Dfalse%2Fnodes%3D1%2Fcpu%3D32&tab=gce"><img width="858" alt="Screenshot 2021-04-26 at 17 09 15" src="https://user-images.githubusercontent.com/644420/116106023-25976380-a6b2-11eb-8afb-a77186093657.png"></a>

Verified this to be caused by #63807, benchmarks of 22e4d644 (old) vs df67aa97 (new):

```
name                           old ops/sec  new ops/sec  delta
kv95/enc=false/nodes=1/cpu=32   73.1k ± 3%   61.1k ± 3%  -16.30%  (p=0.000 n=9+8)

name                           old p50      new p50      delta
kv95/enc=false/nodes=1/cpu=32    0.70 ± 0%    0.70 ± 0%     ~     (all equal)

name                           old p95      new p95      delta
kv95/enc=false/nodes=1/cpu=32    1.80 ± 0%    2.91 ± 6%  +61.81%  (p=0.000 n=8+8)

name                           old p99      new p99      delta
kv95/enc=false/nodes=1/cpu=32    4.70 ± 0%    6.82 ± 4%  +45.21%  (p=0.000 n=8+8)
```

Notice how the new April 21st graph shows a clear improvement from the start, but then slows down after about a minute to a level significantly below the old April 19th baseline. Statistics collection would be a likely cause for the abrupt change.

<img width="949" alt="Screenshot 2021-04-26 at 17 05 14" src="https://user-images.githubusercontent.com/644420/116105430-9c802c80-a6b1-11eb-8038-06cf62389f3d.png">

<img width="955" alt="Screenshot 2021-04-26 at 17 05 24" src="https://user-images.githubusercontent.com/644420/116105451-a013b380-a6b1-11eb-978b-225b27811def.png">

/cc @cockroachdb/test-eng

**Comment by RaduBerinde** [comment]
Wow.. thanks for tracking this down! I think we are missing special logic when the memo is determined to be "stale".

**Comment by RaduBerinde** [comment]
@erikgrinaker for how long did you run the benchmarks? It must have been more than a minute if it slows down after that?

**Comment by tbg** [comment]
roachtest usually runs 10 minute intervals, which is also what you can see in the above graph

**Comment by erikgrinaker** [comment]
Just did `roachtest run '^kv95/enc=false/nodes=1/cpu=32$'`, they're 10-minute runs plus possibly some ramp-up time.

**Comment by RaduBerinde** [comment]
Thanks. I understand the issue now. The problem is that we are using the statistics that are derived using placeholders, which are bogus. Once we have stats, our estimated row count is very large, and that affects the way the query is being executed.

```
planning time: 259µs
execution time: 4ms
distribution: local
vectorized: true
rows read from KV: 1 (0 B)
cumulative time spent in KV: 679µs
maximum memory usage: 90 KiB
network usage: 0 B (0 messages)

• scan
  columns: (k int, v bytes)
  cluster nodes: n1
  actual row count: 1
  vectorized batch count: 1
  KV rows read: 1
  KV bytes read: 0 B
  estimated row count: 20,653
  table: kv@primary
  spans: /-3812730450502136779/0
```
