### ISSUE TITLE
kvserver: tweak GC queue intent heuristics

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#64266]
As seen in #60585, we often see large numbers of intents build up over time, which can cause issues for other operations that run into these. The GC queue is meant to clean up intents, but its policy appears to be too lax, allowing them to accumulate. We should review this.

Epic: CRDB-2554

**Comment by erikgrinaker** [comment]
I've had a look at this, some of the main challenges here:

* GC is primarily concerned with MVCC cleanup, and if we can't GC any MVCC records then we won't run GC at all (regardless of the intent score).
  https://github.com/cockroachdb/cockroach/blob/dfd26aa9e886fc3d9f5cacf2dfe129ec85587674/pkg/kv/kvserver/gc_queue.go#L167-L169

* MVCC intent stats do not differentiate between txn state, so we don't know if we'll actually be able to clean up the intents (e.g. long-running transactions).

* Related to the above, we need to be able to stagger intent GC such that we don't spin in a tight loop trying (and failing) to GC intents.

We should consider either keeping track of MVCC intent stats by transaction state, or introducing e.g. the last GC run time (in addition to the GC threshold) so we can implement a cooldown period to stagger intent cleanups. We may want to separate MVCC and intent GC scoring a bit more as well, to make it easier to reason about.

**Comment by nvanbenschoten** [comment]
Another point we should consider here is that the GC queue does not currently set a `queueProcessTimeoutFunc`, so it is always run with a 1 minute context timeout. Additionally, it performs intent cleanup at the very end, after it has already scanned the range, cleaned up MVCC garbage, and done all of its other work.

I don't know if we've ever actually proven this to be the case, but there have been multiple times in the past where we have suspected that the GC queue was not being given enough time to clean up some or all of its intents. It may be worth exploring how close we get to this timeout under various conditions and whether we should be scaling the process timeout by any factors.
