### ISSUE TITLE
cli: align flag names in the CLI with configuration vars inside the code

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#64269]
Example: field is currently named `SimulateLatency` in the `demoCtx`, and `--global` as a flag.

It is worth renaming both of these to something that makes more sense, e.g. `--simulate-geo-latency`, `--simulate-real-world-latencies`, or something of the ilk, and renaming the flag and marking --global as deprecated.

[Context available here](https://github.com/cockroachdb/cockroach/pull/62435#pullrequestreview-645777206)

Jira issue: CRDB-6978

**Comment by knz** [comment]
thank you
