### ISSUE TITLE
sql: Allow for encoding keyword in create database statement - Ecto / Elixir

### ISSUE THREAD

**Issue by tlvenn** [cockroachdb/cockroach#6426]
As outlined in #5582, when Ecto tries to create the database, it will specify the encoding by default:
` CREATE DATABASE test ENCODING='UTF8';`

At the moment, the `ENCODING` keyword is not known and therefore the statement does not work.

The keyword should be added and probably silently ignored so such statement do work. I suspect some other 'ORM' will also attempt to set the encoding when creating a database.

**Comment by petermattis** [comment]
@tlvenn Would it be sufficient to support `ENCODING='UTF8'` where `UTF8` is the only supported encoding? Silently ignoring other encodings sounds dangerous and adding support for other encodings is something we'd like to avoid.

**Comment by tlvenn** [comment]
@petermattis ya that does seems the best avenue 👍
