### ISSUE TITLE
VIEWACTIVITY isn't inherited through role membership and SET ROLE isn't supported

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#64274]
If a user grants the `VIEWACTIVITY` privilege to a role and then assigns that role to a user, they expect that privilege to be inherited as well. This does not happen today (which matches postgres behavior). See this Jira issue for [a customer example](https://cockroachlabs.atlassian.net/browse/SREOPS-1837). For example:

```
piyush@<cluster>:26257/defaultdb> create role techleads with cancelquery viewactivity;
CREATE ROLE

Time: 51ms total (execution 34ms / network 18ms)

piyush@<cluster>:26257/defaultdb> create user foo with password bar;
CREATE ROLE

Time: 136ms total (execution 117ms / network 20ms)

piyush@<cluster>:26257/defaultdb> grant techleads to foo with admin option;
GRANT

Time: 144ms total (execution 38ms / network 107ms)

piyush@<cluster>:26257/defaultdb> show grants on role techleads;
  role_name | member | is_admin
------------+--------+-----------
  techleads | foo    |   true
(1 row)
```
Our users expect the above would allow user foo to see the statements page, however the user will still see an error:
![image](https://user-images.githubusercontent.com/21692034/116259028-73a87780-a743-11eb-874f-7f1308e2af97.png)

If the user is granted `VIEWACTIVITY` directly however, they are able to see the page properly:
```
piyush@<cluster>:26257/defaultdb> alter user foo with viewactivity;
ALTER ROLE

Time: 35ms total (execution 17ms / network 18ms)
```
![image](https://user-images.githubusercontent.com/21692034/116259330-b5392280-a743-11eb-9e9b-59bc38aa06f1.png)

Note that postgres requires users to `SET ROLE` in order to access privileges specified by options on a role:

> The INHERIT attribute governs inheritance of grantable privileges (that is, access privileges for database objects and role memberships). It does not apply to the special role attributes set by CREATE ROLE and ALTER ROLE. For example, being a member of a role with CREATEDB privilege does not immediately grant the ability to create databases, even if INHERIT is set; it would be necessary to become that role via SET ROLE before creating a database.

See [pg docs](https://www.postgresql.org/docs/13/sql-createrole.html) for more info. Unfortunately, there is no way to do this in cockroach today (#15005), and even if there was, there isn't a way to do that in the DB Console. Until we have those options, users can work around this by granting role/user options like `VIEWACTIVITY` to users directly.

cc @dbist @thtruo @kevin-v-ngo

**Comment by rafiss** [comment]
@piyush-singh I'd like to close this as a duplicate of https://github.com/cockroachdb/cockroach/issues/15005 -- does that seem OK?

I think the solution here is to implement `SET ROLE`. I don't think we will implement anything where `VIEWACTIVITY` (or any role option) is inherited based on role membership, since that's not PG-compatible.

cc @vy-ton

**Comment by piyush-singh** [comment]
@rafiss that makes sense to me, I mostly filed this to document a specific user's issue. If implementing `SET ROLE` is the right way to proceed, I'm happy to close.
