### ISSUE TITLE
changefeeds: changefeed should fail or otherwise indicate a problem if IMPORT INTO was executed

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#64276]
**Describe the problem**

Until we fix #43784, we should either fail the changefeed or otherwise indicate that the changefeed has failed to emit data.  We should also have some tests that confirm this happens.

**To Reproduce**

```
select crdb_internal.set_vmodule('sink*=2');
CREATE TABLE test (id VARCHAR PRIMARY KEY);
CREATE CHANGEFEED FOR TABLE test INTO 'null://' WITH format=json, no_initial_scan;
INSERT INTO test VALUES ('ardvark');
```

You should see a log-line for the value being emitted.

```
IMPORT INTO test (id) CSV DATA ('nodelocal://1/data.csv');
```

You will not see any log lines for any data you've added via data.csv.

**Possible Behaviors***

I haven't looked into the implementation costs here, but some possible options include:

- Fail the changefeed with an error referencing the IMPORT INTO
- Do a full backfill/scan after an import into.

**Comment by stevendanna** [comment]
This bug talks about some of the underlying issues in more detail https://github.com/cockroachdb/cockroach/issues/62585

**Comment by ajwerner** [comment]
The CHANGEFEED should get an event when the table goes offline and fail. I could have sworn that that was the behavior at some point.

**Comment by stevendanna** [comment]
@ajwerner Yup, I've confirmed we get the event, we just currently filter it out. Should be straightforward to fail the changefeed.
