### ISSUE TITLE
Error when retrieve percentile

### ISSUE THREAD

**Issue by StefanoMartin** [cockroachdb/cockroach#64319]
I was trying to fetch a percentile by using the following request:

`SELECT percentile_disc(0.1) WITHIN GROUP (ORDER BY 'data_number') AS percentile FROM data_state`

and the following output has been returned:

`
ERROR:  internal error: interface conversion: *tree.StrVal is not tree.TypedExpr: missing method Eval\nDETAIL:  stack trace:\n/go/src/github.com/cockroachdb/cockroach/pkg/util/errorutil/catch.go:29: ShouldCatch()\n/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:165: func1()\n/usr/local/go/src/runtime/panic.go:679: gopanic()\n/usr/local/go/src/runtime/iface.go:85: getitab()\n/usr/local/go/src/runtime/iface.go:449: assertI2I()\n/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:1083: replaceAggregate()\n/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:920: VisitPre()\n/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:714: WalkExpr()\n/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:388: walkExprTree()\n/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:427: resolveType()\n/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/project.go:150: analyzeSelectList()\n/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/project.go:84: analyzeProjectionList()\n/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:1055: buildSelectClause()\n/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:992: buildSelectStmtWithoutParens()\n/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:965: func1()\n/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/with.go:29: processWiths()\n/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:964: buildSelect()\n/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:265: buildStmt()\n/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:229: buildStmtAtRoot()\n/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:200: Build()\n/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:512: buildExecMemo()\n/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:195: makeOptimizerPlan()\n/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:901: makeExecPlan()\n/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:780: dispatchToExecutionEngine()\n/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:639: execStmtInOpenState()\n/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:114: execStmt()\n/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1465: func1()\n/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1467: execCmd()\n/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1391: run()\n/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:508: ServeConn()\n/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:626: func1()\n/usr/local/go/src/runtime/asm_amd64.s:1357: goexit()\n\nHINT:  You have encountered an unexpected error.\n\nPlease check the public issue tracker to check whether this problem is\nalready tracked. If you cannot find it there, please report the error\nwith details by creating a new issue.\n\nIf you would rather not post publicly, please contact us directly\nusing the support form.\n\nWe appreciate your feedback.\n\n
`

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

Try to do the following request:
`SELECT percentile_disc(0.1) WITHIN GROUP (ORDER BY 'data_number') AS percentile FROM data_state`
Similar issue also happen with percentile_cont

**Expected behavior**

Return the percentile or an error that explain what I did wrong.

**Environment:**
 - CockroachDB v20.2.0
 - Ubuntu
 - ruby gem pg

**Comment by yuzefovich** [comment]
@StefanoMartin thanks for the report! We will look into fixing it shortly.

However, I'm guessing that the query wouldn't do what you wanted - `data_number` is probably a column in `data_state` table, right? If so, you probably want to use `SELECT percentile_disc(0.1) WITHIN GROUP (ORDER BY data_number) AS percentile FROM data_state`. (When putting `data_number` into single quotes, you're making it a string constant, so the database would order the rows based on constant (which is equivalent to no ordering).)

**Comment by StefanoMartin** [comment]
You are perfectly right! Thank you for your feeback.
