### ISSUE TITLE
ui: want way to go from "past <x> minutes" to frozen time when looking at timeseries

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#64331]
When I'm looking at some timeseries, for example in the Custom Timeseries page, I'd like to be able to easily go from the normal view (trailing 10 minutes) to freezing the interval I'm currently using. Stopping the page from updating the timeseries should be one click.
We have the custom time picker I guess, but it's very hard to use. In fact I'm failing to use it.

Epic CRDB-8038

**Comment by thtruo** [comment]
cc @Annebirzin as it relates to the Metrics UX improvements discussion

**Comment by Annebirzin** [comment]
@andreimatei Makes sense that you'd want to 'freeze' an interval so it doesn't continuously update.

I was curious if the new drag to select timeframe might help with this in the interim? For example, if you are looking at 'the past hour' and want to freeze that timeframe, you could drag-select the entire hour on the graph to freeze that time. I think we recently added this to the dashboard graphs, but not sure if it's been added to the custom carts yet -  @thtruo do you know?

**Comment by thtruo** [comment]
That's a good point. We are adding drag-to-select soon to custom charts, looks like the PR is waiting to get merged https://github.com/cockroachdb/cockroach/issues/64792
