### ISSUE TITLE
changefeedccl: JSONB encoder performance

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#64344]
Benchmark, investigate and improve jsonb encoder performance.

It appears that jsonb encoding (used in avro) does not scale with the complexity of the
jsonb object (i.e. objects with larger number of keys, more complex nested structs, etc), but instead,
scales very poorly as the size of the blob inside jsonb increases.

To verify, run BenchmarkEncodeJSON (should be around 2+microsecond/op).  Then, update
util/json/random.go to generate much larger strings (up to say 1MB).  Observe significant drop in performance.

Epic CRDB-8666

Jira issue: CRDB-7009

**Comment by shermanCRL** [comment]
See also:

- https://github.com/cockroachdb/cockroach/issues/84417
