### ISSUE TITLE
build: invocations of `c++` fail with "permission denied" on macOS big sur with high memory usage

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#64369]
This was first reported by Michael Goddard on slack, confirmed by @michae2 
I also personally witnessed this yesterday while watching over a coworker's shoulder.

Non-deterministically, builds on macOS big sur fail with:

```
make[4]: /Library/Developer/CommandLineTools/usr/bin/c++: Permission denied
```

The issue is durably averted by running with `make -j1`, and sometimes `make -j2`. 

Or seen the other way, the problem seems to start occuring with either high concurrency or high memory usage, or both.

Epic CRDB-10447

Jira issue: CRDB-7020

**Comment by knz** [comment]
> @otan  i think some combination of switching to gmake and reinstall xcode unblocked this for me fwiw

> @michae2  oh yeah! I had to add /usr/local/opt/make/libexec/gnubin to my PATH to use GNU Make 4.3 (from homebrew) instead of GNU Make 3.81 (from Big Sur)

**Comment by knz** [comment]
I think if the version of `make` is important we need to document that in the prereqs and make an announcement on the engineering mailing list. Possibly also an extra version check inside the `Makefile` itself.

**Comment by knz** [comment]
cc @jlinder 

also perhaps @aaron-crl to see if Crowdstrike has anything to see about the permissions of an executable under memory pressure

**Comment by stevendanna** [comment]
We do currently warn on the version of make:

```
ifneq (,$(findstring v3.,v$(MAKE_VERSION)))
$(info $(yellow)Warning: your version of `make` seems old; your build may fail!$(term-reset))
endif
```

**Comment by knz** [comment]
thanks steven.

nonetheless, it does seem strange to me that an older `make` version would incur a `c++: Permission denied` error.
