### ISSUE TITLE
Monotonic Node Sequence Counter

### ISSUE THREAD

**Issue by lancel66** [cockroachdb/cockroach#64365]
**Monotonic Node Sequence Counter**

This request for enhancement is to add a sequence counter on a per-node basis.  This can be used by the customer to create a custom sequence mapping of unique values on a per-node basis.  This counter should be able to be defined on a PER table basis as and be constructed to allow for up to 200k inserts/sec on a node with 48 vCPUs.

**Syntax:**
`SELECT get_next_node_seq(‘my-table-sequence'); 
`

**Performance and Functional requirements:**

- Monotonic per-node sequence
- Defined on a per-table basis
- Able to scale to 200K inserts/sec or greater on 48 vCPU machine
- Returns a 64bit integer
- Nice to have: Convenience function that returns the node-id. Perhaps it already exists?

**Workaround:** 
The customer is currently experimenting with using `gen_rowid()` and masking off the first 13 bits for their own use.  With the 15 bits that CockroachDB uses for NodeID this leaves only (64-13-15 = 36 bits) for random.  But this is essentially a counter with 10 microseconds as the resolution.  This will wrap around far too often and not work as a random generator.

**Comment by awoods187** [comment]
@lancel66  can you please provide some more context? What is the customer trying to accomplish?  Why does it need to be sequenced? Is the idea that you'd write to a different node to avoid hotspots? Why are we including node in the schema design? Sequences as a part of a primary key are a general antipattern because of hotspots and we recommend using UUIDs which are then on different ranges and spread across a cluster.  Can they use a hash shared index if they need sequencing?

For issues like this, it's much more helpful to articulate the problem (even if it needs to be in the private support repo) before jumping to a potential solution. We can't evaluate if there is already a way to meet the customer needs or a better way than the proposed solution. 


cc @vy-ton

**Comment by lancel66** [comment]
**Please describe the use case(s).**
[ Customer ]: We need a unified ID space across clusters for post-processing and async workflows.  To do that, we need to provide CRDB Cluster Scope, plus Node ID scope.  We can’t use CockroachDB’s native SEQUENCE support due to performance concerns.

**Why does it need to be sequenced? Is the idea that you'd write to a different node to avoid hotspots?**
[ Customer ]: Yes

**Why are we including node in the schema design? Sequences as a part of a primary key are a general antipattern because of hotspots and we recommend using UUIDs which are then on different ranges and spread across a cluster. Can they use a hash shared index if they need sequencing?**
[ Customer ]: Use of UUIDs is not an acceptable solution for the problem domain.  

Use of a per-node sequence ID solves the sequence hot-spot problem.

A more robust solution, but one that would be more time consuming to implement, therefore more risky for our current needs and project for migrating to crdb, would be to have SEQUENCEs pre-fetched on a per-node basis, checkpointed and replicated via Raft.  For example: under the hood NEXTVAL(‘my_sequence’) would query a raft-replicated SEQUENCE object.  The NEXTVAL() function would increment the sequence object by N values (e.g. 10K, something tunable on a per-sequence basis) and cache the range of values on a given node.  When the node-local cache of values has been depleted by Y, pre-fetch another range of IDs.  Across the cluster values won’t be fully monotonic, but will provide a reasonable way to have a non-gappy counter that performs well.  This is the distributed systems equivalent to PostgreSQL’s “CACHE cache” attribute of CREATE SEQUENCE.

This would be preferred, but we think implementing this and depending on this particular feature would put our project at risk.

**Comment by vy-ton** [comment]
I'm looking into this and plan to have an update next week

**Comment by rafiss** [comment]
The sequence caching idea described above sounds like something we've already implemented. In 21.1 using SERIAL types and setting `serial_normalization=sql_sequence_cached` results in behavior like that. See https://github.com/cockroachdb/cockroach/pull/56954

**Comment by lancel66** [comment]
@rafiss thanks, the customer says that [56954](https://github.com/cockroachdb/cockroach/pull/56954) will address the feature request in this issue and they can wait until the 21.1 GA release later this month.

**Comment by vy-ton** [comment]
@rafiss Are you ok with closing this issue based on #56954?

**Comment by rafiss** [comment]
That sounds good from my end, but @lancel66 since you filed this initially, please re-open if needed.
