### ISSUE TITLE
storage: Investigate failures when splits occur while draining

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#6436]
In issues such as #6431 and #6116, we see panics in split-related code while the main test goroutine is in `stopper.Quiesce()`. We work around this problem here and elsewhere by either disabling the split queue or waiting for all splits to complete, but we should figure out why these failures are happening now that we're working on more graceful drain-and-shutdown procedures. 

Once we have fixed the panics, we may want to remove calls to `WaitForInitialSplits` and `TestingDisableTableSplits` as much as possible.

**Comment by tschottdorf** [comment]
`retryable internal error must not happen at this level: key range /Table/3/1/12/2/1-/Min outside of bounds of range /Min-"s"`
