### ISSUE TITLE
colexec: vectorized engine does not check cast widths

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#64429]
Currently, this is the behavior in CockroachDB with default settings:
```
root@:26257/defaultdb> CREATE TABLE t0(c0 INT);;
CREATE TABLE

root@:26257/defaultdb> INSERT INTO t0 VALUES(-1292691042);
INSERT 1

root@:26257/defaultdb> SELECT t0.c0::SMALLINT FROM t0;
   c0
--------
  6558
```

However, changing the vectorize setting results in:

```
root@:26257/defaultdb> SET vectorize=off;
SET

Time: 0ms total (execution 0ms / network 0ms)

root@:26257/defaultdb> SELECT t0.c0::SMALLINT FROM t0;
ERROR: integer out of range for type int2
SQLSTATE: 22003
```

Note that Postgres behavior is the latter, so the vectorized engine should probably do that too.

See #55095 for how this was fixed in row-based execution.

Maybe relates to #46970 and #46940

**Comment by yuzefovich** [comment]
This will be a pretty simple fix in `execgen/overloads_cast.go`.

I'm a bit surprised that none of the tests added in #55095 fired for this bug (probably this logic test
```
statement error integer out of range
SELECT 23414123414::int2
```
is actually pre-evaluated by the optimizer, so it doesn't exercise the execution engine directly).

**Comment by yuzefovich** [comment]
I think I'll pick this up to work on during our SQL Execution onboarding chats for next week.
