### ISSUE TITLE
sql: incorrect types for some pg_constraint columns

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#64434]
**Describe the problem**

As per the `pg_constraint` schema here: https://www.postgresql.org/docs/current/catalog-pg-constraint.html, a few of the columns seem to have an incorrect data type. For example, columns such as confdeltype and confuptypeand are represented as strings in CRDB, but are single char columns in Postgres. We should match our schema to Postgres.

**Comment by rafiss** [comment]
Let's go through all the diffs in `pg_catalog_test_expected_diffs.json` and fix the columns that have a diff like this:

```
{
      "oid": 25,
      "dataType": "text",
      "expectedOid": 18,
      "expectedDataType": "char"
}
```

there's only 8 of them, so we can do the change manually. @mnovelodou could you get to this when you have a chance?
