### ISSUE TITLE
sql/sem/tree: break dependency on pebble and log

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#64452]
**Is your feature request related to a problem? Please describe.**
You should not need an LSM, tracing, metrics, prometheus, unix signals, etc in order to parse some SQL.

We should break the dependency and then add a test to verify we don't add it back. I do think there's some interesting questions related to how to expose logging functionality to some low-dependency packages. We could create a `logbase` package that has stubs that either do nothing or write to stderr and then inject the normal functionality into that package with an `init` in `util/log`. 

Relates to #64451. 

Jira issue: CRDB-7062

**Comment by otan** [comment]
`pkg/sql/sem/tree` import `pkg/base` and `pkg/kv`, which both import `log`, so uhhh that'll be interested to refactor out!

**Comment by ajwerner** [comment]
I'll go so far as to say it's crazy that `tree` imports `roachpb`.

**Comment by ajwerner** [comment]
We did this!
