### ISSUE TITLE
server: store instance ID and network addresses of SQL pods 

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#64475]
Since we wish to create RPC fan-outs from one SQL pod process to another (to implement cross-pods HTTP APIs), we need to store and retrieve the network addresses of SQL pods within a tenant.

Today, the SQL pods for a given tenant do not know their respective identities (instance IDs, see #64474) nor their network addresses.

This should be solved by storing the instance ID and pod network addresses inside a per-tenant system table. Perhaps `system.sqlliveness` can be used for this purpose, or perhaps a new system table needs to be created.

Epic: CRDB-8505

**Comment by knz** [comment]
cc @dhartunian

**Comment by ajwerner** [comment]
Relates to https://github.com/cockroachdb/cockroach/issues/62818.
