### ISSUE TITLE
kvserver: silent deadlock in outgoing RaftMessageBatch queue

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#64565]
**Describe the problem**

cc @cockroachdb/kv 

@erikgrinaker and I were looking at an (accidental) reproduction of
https://github.com/cockroachdb/cockroach/pull/57008 on a 20.2.4 cluster. This
was a beefy 64 core 376GiB RAM three node cluster with 60k ranges, and sure
enough we found the raftScheduler's sending threads all on `semaqcuire` (though
never with a wait time, i.e. hadn't been there for longer than a minute), and
the receiving sides of these streams were sitting on `RecvMsg <- waitForHeader`

https://github.com/cockroachdb/cockroach/blob/2991cdcaa11b590efe25f0a2c023a5b394b4808b/pkg/kv/kvserver/raft_transport.go#L329-L345

"forever" (11k+ minutes). The scheduler concurrency on this machine was
configured to the very high value of 512 (since we didn't backport the cap in
https://github.com/cockroachdb/cockroach/pull/57008), and
`raft.enqueued.pending` showed 20k for all nodes. So this is pretty clearly the
issue and we're advising the customer to set `COCKROACH_SCHEDULER_CONCURRENCY` and
we'll revisit backporting the cap.

However, we kept digging this time around as we still had questions. If contention in the scheduler is the problem, how does that explain that we're never managing to get a single message over the wire (which would reduce the receiving side's wait time from "forever" to something smaller)? The scheduler wasn't deadlocked, as its workers were never on semacquire for more than a minute. So they must be succeeding in passing messags to the outgoing queues. The outgoing queues were basically not reporting errors, ever. We know this a) because when a queue reconnects, it prints a warning and there weren't any of those, but also we looked and found

https://github.com/cockroachdb/cockroach/blob/2991cdcaa11b590efe25f0a2c023a5b394b4808b/pkg/kv/kvserver/raft_transport.go#L456-L462

sitting on the `Recv` "forever" which is expected on healthy systems (this is the "raft message sending side" waiting for a response from the other side in reaction to a raft message). So messages were going into the queue, but never getting sent (or, much more unlikely, the receiver somehow didn't manage to receive properly).

First there is a bounded buffer on the sending side. The `ch` here

https://github.com/cockroachdb/cockroach/blob/2991cdcaa11b590efe25f0a2c023a5b394b4808b/pkg/kv/kvserver/raft_transport.go#L571-L576

has size 10k:

https://github.com/cockroachdb/cockroach/blob/2991cdcaa11b590efe25f0a2c023a5b394b4808b/pkg/kv/kvserver/raft_transport.go#L39-L46

and this is consistent with the "pending" metric of 20k that we observed (10k times two other nodes in the cluster). So the outgoing queues are all full, no surprise there. We also had almost all of the ~60k replicas unquiesced, so clearly the queues should be full, especially if we're not managing to get anything across the wire. But the question still remains, why not?

This is retelling history a bit, but the comment above about "flow control" seems pertinent (we had in fact started pulling on that thread earlier) and we looked into the possibility that we were sending giant messages that would for whatever reason fail silently. The code that constructs messages is here:

https://github.com/cockroachdb/cockroach/blob/2991cdcaa11b590efe25f0a2c023a5b394b4808b/pkg/kv/kvserver/raft_transport.go#L493-L515

so clearly it isn't careful to avoid overly large messages. However, we are setting very permissive max message sizes for the server side:

https://github.com/cockroachdb/cockroach/blob/513d3c33dd310c20252da8a3b8bb01896a34d155/pkg/rpc/context.go#L150-L170

and the client side:

https://github.com/cockroachdb/cockroach/blob/513d3c33dd310c20252da8a3b8bb01896a34d155/pkg/rpc/context.go#L720-L728

The stacks we saw for the goroutines sending messages over the wire were like this:

```
goroutine 2935 [select]:
google.golang.org/grpc/internal/transport.(*writeQuota).get(0xc014b73700, 0xc00000004e, 0x49, 0x5)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/internal/transport/flowcontrol.go:59 +0xaa
google.golang.org/grpc/internal/transport.(*http2Client).Write(0xc0009bd180, 0xc01e1e4500, 0xc04b7e1720, 0x5, 0x50, 0xc02828f980, 0x49, 0xb7, 0xc04ad4c375, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/internal/transport/http2_client.go:869 +0x1ae
google.golang.org/grpc.(*csAttempt).sendMsg(0xc01e1d6480, 0x500e6e0, 0xc014b73900, 0xc04ad4c370, 0x5, 0x5, 0xc02828f980, 0x49, 0xb7, 0xc01852ee00, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:844 +0x128
google.golang.org/grpc.(*clientStream).SendMsg.func2(0xc01e1d6480, 0x49, 0xb7)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:709 +0xb3
google.golang.org/grpc.(*clientStream).withRetry(0xc01138a7e0, 0xc02a0616d0, 0xc02c9ed6c0, 0xc00087b6b0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:589 +0x360
google.golang.org/grpc.(*clientStream).SendMsg(0xc01138a7e0, 0x500e6e0, 0xc014b73900, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:715 +0x399
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*multiRaftRaftMessageBatchClient).Send(0xc000bc9fc0, 0xc014b73900, 0xc0453deb00, 0x3)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/storage_services.pb.go:70 +0x49
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*RaftTransport).processQueue(0xc000f960f0, 0x1, 0xc01e419380, 0xc01c575b00, 0x638ef00, 0xc000bc9fc0, 0x638ef00, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/raft_transport.go:509 +0x3be
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*RaftTransport).startProcessNewQueue.func2(0x63133c0, 0xc011b99fb0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/raft_transport.go:636 +0x3bc
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc005a5cb10, 0xc0002cb950, 0xc0120700c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:222 +0x13d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xa8
```

`writeQuota.get` is not something we typically see. We never spend more than a minute there, neither. Here's the impl:

https://github.com/grpc/grpc-go/blob/754ee590a4f386d0910d887f3b8776354042260b/internal/transport/flowcontrol.go#L53-L66

Our going theory is that we're sending a large message, and for some reason it fails transiently, and gets internally retried, forever. Going up to frames (skipping the boring `http.Write`), we find

https://github.com/grpc/grpc-go/blob/754ee590a4f386d0910d887f3b8776354042260b/stream.go#L589

which is inside a retry loop, where the operation to be retried is `op` defined here

https://github.com/grpc/grpc-go/blob/754ee590a4f386d0910d887f3b8776354042260b/stream.go#L703-L715

What's interesting is that in :589 we are in the `if cs.committed` branch, which indicates that there is something going on with retries:

https://github.com/grpc/grpc-go/blob/754ee590a4f386d0910d887f3b8776354042260b/stream.go#L412-L423

I'm going to stop the write-up here but there is a thread to pull. @erikgrinaker and I think a next step should be trying to reproduce: set up a faux server that just drops all the messages it gets, and write increasingly larger messages to it, all while using the GRPC settings we also use in production.

**To Reproduce**

See last paragraph

[stacks.txt](https://github.com/cockroachdb/cockroach/files/6414529/stacks.txt)

**Comment by tbg** [comment]
The retry logic here is not obviously conducive to an infinite internal loop. Basically the whole retry code is here

https://github.com/grpc/grpc-go/blob/754ee590a4f386d0910d887f3b8776354042260b/stream.go#L584-L612

but once `cs.committed` is set, you will exit that loop on line 589, and the error will bubble up. But what if we returned a nil error? Well, that is actually possible, in https://github.com/grpc/grpc-go/blob/754ee590a4f386d0910d887f3b8776354042260b/stream.go#L844-L851, however https://github.com/cockroachdb/cockroach/blob/c3951f31a97dc679cb336d4894e8acf8dd2cd064/pkg/kv/kvserver/storage_services.pb.go#L178-L184 says that we don't hit that `return nil`.

**Comment by tbg** [comment]
the way the `cs.committed` came about is very likel that

- we went into `clientStream.withRetry` for the first time
- got an error from `op(a)`, and the err was `io.EOF` (see L844-851 in stream.go)
- that causes us to call `onSuccess(io.EOF)`
- that calls `cs.bufferForRetryLocked(<something large>, op)`
- that adds <something large> to buffer size and compares against `maxRetryRPCBufferSize` which is 256KiB by default (and we're not overriding it)
- since it's larger, set `cs.committed`
- next retry attempt then will be the last one
- but it seems to never get past getting the write quota (even though it doesn't obviously hang there)

I'm thinking it probably is hanging in `writeQuota.get`, but just in a way that's not obvious. That code uses atomics weirdly and seems to have the potential to go sideways.

**Comment by tbg** [comment]
Something that strikes me as inviting bugs is that we return the quota far away from where we acquire it. We randomly acquire it in `http2Client.Write`, but nothing there ever returns it. Instead, we put the measured `dataFrame` into `t.controlBuf`, and I am still looking for any calls to `wq.replenish`...

**Comment by erikgrinaker** [comment]
https://github.com/cockroachdb/vendored/blob/ad389fdd0d3a778333152aae2782e0dc0e8973a0/google.golang.org/grpc/internal/transport/controlbuf.go#L884

**Comment by tbg** [comment]
https://github.com/cockroachdb/vendored/blob/ad389fdd0d3a778333152aae2782e0dc0e8973a0/google.golang.org/grpc/internal/transport/controlbuf.go#L873-L884

873 looks suspicious, as it's an early return before replenishing the quota. Maybe we're going to come back and this is actually correct, but I don't know, the interplay between stream and call quotas that is all over the place, plus the fact that we're feeding MaxInt32 in, just feels like good potential for an issue where we leak quota.

**Comment by erikgrinaker** [comment]
Yeah, I think the `MaxInt32` is likely to cause some issues. My guess is that the `writeQuota.get` call has a very negative quota, and even though it periodically gets replenished via the channel, it's slow enough that in practice nothing ever gets through. I think a repro case would be enlightening.

**Comment by tbg** [comment]
Just a heads up that we're upgrading from grpc 1.31 to 1.33 in #54180. If the problem stops reproing on master, this might be related. The PR lists some noteworthy fixes.

**Comment by tbg** [comment]
Since Nathan is asking, @erikgrinaker could you remind me what the repro looks like?

**Comment by erikgrinaker** [comment]
Basically start a few nodes with ~50k ranges and ~500 Raft scheduler goroutines. After some time, none of the Raft groups will be making any progress.

We saw Raft transport goroutines without any activity for hours, even though the Raft message buffers were full. The suspicion was that we try sending frames that are too large, so gRPC drops them.

Should be able to repro by sending increasingly large messages until gRPC stops sending them.

**Comment by erikgrinaker** [comment]
Had a quick stab at this with 20.2.4, by setting up two Raft transports and sending increasingly large messages. Seemed to work as expected: they started getting dropped with logged errors at `MaxInt32`, which is the configured maximum, but sending subsequent smaller messages afterwards worked fine.

I'll dig into the details a bit when I have time, in case I'm missing any necessary conditions (e.g. settings, message batching, retries, etc).

**Comment by erikgrinaker** [comment]
Spent some more time digging into this, filling up the queues on the sender before processing on the receiver, which also worked as expected. Settings are the same as in prod.

However, I went back to the start and tried reproducing this with a roachprod cluster with `COCKROACH_SCHEDULER_CONCURRENCY=1024` when I noticed something: even when the cluster was making progress, there were `waitOnHeader` goroutines blocked since the cluster started:

```
goroutine 812 [select, 44 minutes]:
google.golang.org/grpc/internal/transport.(*Stream).waitOnHeader(0xc0050fe500)
        /home/erik/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/internal/transport/transport.go:318 +0x99
google.golang.org/grpc/internal/transport.(*Stream).RecvCompress(...)
        /home/erik/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/internal/transport/transport.go:333
google.golang.org/grpc.(*csAttempt).recvMsg(0xc0050fc680, 0x5030a40, 0xc004a80b40, 0xc00613dc68, 0x783ac412d39331b9, 0xc189eaab1ce25776)
        /home/erik/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:870 +0x731
google.golang.org/grpc.(*clientStream).RecvMsg.func1(0xc0050fc680, 0x8, 0x3015a85a8b6e15e1)
        /home/erik/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:735 +0x46
google.golang.org/grpc.(*clientStream).withRetry(0xc0018c0a20, 0xc00498fde8, 0xc00498fdb8, 0x40, 0x40)
        /home/erik/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:589 +0x3df
google.golang.org/grpc.(*clientStream).RecvMsg(0xc0018c0a20, 0x5030a40, 0xc004a80b40, 0xc000f0f858, 0x7e6eef11d9c71a14)
        /home/erik/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:734 +0x105
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*multiRaftRaftMessageBatchClient).Recv(0xc00531af10, 0x30, 0x30, 0x4f38dc0)
        /home/erik/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/storage_services.pb.go:75 +0x62
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*RaftTransport).processQueue.func1.1.1(0x64543a0, 0xc00531af10, 0xc00446b100, 0xc001314000, 0x63f3998, 0xc0055
        /home/erik/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/raft_transport.go:459 +0x3b
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*RaftTransport).processQueue.func1.1(0x63f3998, 0xc0055d84b0)
        /home/erik/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/raft_transport.go:474 +0x66
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc00531af30, 0xc000eab290, 0xc0055d8450)
        /home/erik/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:222 +0x102
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /home/erik/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xa8
```

Looking at the code, these goroutines are waiting for Raft _responses_. Raft doesn't typically send responses (it just sends regular messages back again), and these are instead used primarily for certain rare error conditions. We therefore _expect_ these goroutines to be blocked forever under normal circumstances.

https://github.com/cockroachdb/cockroach/blob/2991cdcaa11b590efe25f0a2c023a5b394b4808b/pkg/kv/kvserver/raft_transport.go#L453-L478

So I went back to the original debug.zip from the customer cluster, and sure enough, those goroutines were also blocked on this:

```
goroutine 9337 [select, 11531 minutes]:
google.golang.org/grpc/internal/transport.(*Stream).waitOnHeader(0xc0176e8c00)
        /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/internal/transport/transport.go:318 +0xcc
google.golang.org/grpc/internal/transport.(*Stream).RecvCompress(...)
        /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/internal/transport/transport.go:333
google.golang.org/grpc.(*csAttempt).recvMsg(0xc029c78600, 0x500e800, 0xc029e48880, 0xc0031e5c38, 0x60, 0x510c5a0)
        /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:870 +0x721
google.golang.org/grpc.(*clientStream).RecvMsg.func1(0xc029c78600, 0x20300a, 0x20300a)
        /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:735 +0x46
google.golang.org/grpc.(*clientStream).withRetry(0xc018445e60, 0xc017986da0, 0xc017986d70, 0x6080b7a9, 0x40)
        /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:589 +0x360
google.golang.org/grpc.(*clientStream).RecvMsg(0xc018445e60, 0x500e800, 0xc029e48880, 0xc017986e88, 0x78ea26)
        /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:734 +0x103
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*multiRaftRaftMessageBatchClient).Recv(0xc01e1607f0, 0x167803e89d50da3c, 0x0, 0x30)
        /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/storage_services.pb.go:75 +0x62
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*RaftTransport).processQueue.func1.1.1(0x638ef00, 0xc01e1607f0, 0xc022b5e180, 0xc0001d3860, 0x63133c0, 0xc01a9
        /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/raft_transport.go:459 +0x3b
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*RaftTransport).processQueue.func1.1(0x63133c0, 0xc01a937ad0)
        /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/raft_transport.go:474 +0x66
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc01e160820, 0xc000c72510, 0xc01a937a70)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:222 +0x13d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:215 +0xa8
```

Looks like this was a wild goose chase. Don't know how we missed this the first time around.

**Comment by tbg** [comment]
Thanks for looking into this! Also not sure how we missed this.
