### ISSUE TITLE
REPLACE view performance improvement needed and "AS OF SYSTEM TIME" supported

### ISSUE THREAD

**Issue by GlennFawcett-doordash** [cockroachdb/cockroach#64577]
**Is your feature request related to a problem? Please describe.**
We are using "CREATE or REPLACE VIEW" to workaround lack of TTL functionality.  When we create or replace a view, it causes performance to drop for about a minute!!!   Need a smooth transition when replacing the view. 

![interruption_createview sql](https://user-images.githubusercontent.com/73661536/116903298-0daf6a80-abf1-11eb-9bd8-3ba4846b64cc.png)

**Describe the solution you'd like**
Would like a smooth transition from previous view to the new view.  It doesn't have to be transactional but should have a clean transition without the massive drop in performance for 1 minute.  Additionally, Would like like to be able to create a view on tables with `as of system time`.  The multiple tables than make up the view are used for reporting.

**Describe alternatives you've considered**
TTL or True partitioning are not available so a structure of views per-month were our best last choice.

Epic: CRDB-9838

Jira issue: CRDB-7138

**Comment by rafiss** [comment]
cc @vy-ton

**Comment by vy-ton** [comment]
Thanks for the ping @rafiss. This came up in a user interview so we should investigate for a future milestone.

**Comment by rafiss** [comment]
The feature to create a view based on a follower read seems reasonable. Though the qps dropping down to zero when creating a view normally is definitely not expected. To clarify, is the behavior from the screenshot from a regular `VIEW` or a `MATERIALIZED VIEW`?

It seems like something that should be handled as a support item, since zero qps is definitely quite bad.

**Comment by vy-ton** [comment]
Confirmed that screenshot is for a `VIEW`

**Comment by rafiss** [comment]
Relates to the request in https://github.com/cockroachdb/cockroach/issues/50753 and the root issue is https://github.com/cockroachdb/cockroach/issues/35712

**Comment by mgartner** [comment]
It sounds like this is no longer needed now that we support TTL and we have the other two issues tracking the root issue.
