### ISSUE TITLE
sql: unsupported unary operator: - <parameter>

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#6460]
`INSERT INTO accounts (id) VALUES(-$1)`

replacing this with `0 - $1` or `-1 * $1` elicits

> pq: VALUES list type mismatch, int for parameter

Trying to throw type casts into the mix didn't change anything.

**Comment by nvanbenschoten** [comment]
@tschottdorf Are you seeing this with the new or the old typing system?

**Comment by tschottdorf** [comment]
This is without Summer (if that's the question?), on today's master. I just tested against #6358 and it works like a charm (not on Postgres :-) )
I also tested `$1-$2` while I was at it (success).

**Comment by nvanbenschoten** [comment]
Awesome! I have a future [commit](https://github.com/cockroachdb/cockroach/commit/fdc9ff7d24538a5b220a5eca59db8bd7e59686ca) with a number of test cases that demonstrate typing improvements with Summer. I'll throw this example in there.
