### ISSUE TITLE
Surface region information in EXPLAIN ANALYZE

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#64607]
In 21.1, EXPLAIN ANALYZE surfaces node information; however, it does not surface region. As part of our multi-region observability capabilities, we should have node-level region information in EXPLAIN ANALYZE as well. 

![image](https://user-images.githubusercontent.com/81193618/116930388-9095ec80-ac14-11eb-93c3-e1129f4ba8d0.png)

**Comment by jordanlewis** [comment]
I think this would be good to take a look at next, @maryliag, once the DB Console equivalent is ready. I think it would be okay in this case to use the more expensive way of getting the regions for each node.
