### ISSUE TITLE
Generate certificates using the Cockroach CLI that can be used by PgBouncer

### ISSUE THREAD

**Issue by ianjevans** [cockroachdb/cockroach#64616]
**Is your feature request related to a problem? Please describe.**
When using PgBouncer with a secure CockroachDB cluster, you need to generate a CA and certificate for the PgBouncer server. The certificates generated by `cockroach cert` shouldn't be used for this. From a Slack thread:

> giving anything but a cockroach node the super-powered node certificate is a bad idea. you should generate a separate server-only certificate for pgbouncer to use instead. cockroach cert doesn't currently have any facilities to generate such a cert; use openssl, cfssl, etc directly to generate it

Users might be tempted to use the node certificate, but this would be a security anti-pattern.

**Describe the solution you'd like**

An option to `cockroach cert` that will generate the CA and certificate/key to be used by the PgBouncer server.

**Describe alternatives you've considered**

Users can generate the CA/cert/key using other tools like OpenSSL. But this adds complexity.

Jira issue: CRDB-7160

**Comment by knz** [comment]
cc @jtsiros for triage
