### ISSUE TITLE
Add query parameter for specifying certificates for schema registries

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#64622]
CRDB does not have a way to specifying which CA to trust for schema registries. This can be a blocking problem for Cockroach Cloud users (see https://github.com/cockroachdb/cockroach/issues/42882).

We should add a param to specify the certificate to trust for schema registries, like the client_cert param that we already have.

registry_client_cert: The base64-encoded Privacy Enhanced Mail (PEM) certificate. This is used with registry_client_key.
Sink type: Kafka
Type: String 

registry_client_key: The base64-encoded private key for the PEM certificate. This is used with registry_client_cert.
Sink type: Kafka
Type: String

**Comment by bobvawter** [comment]
It's not currently possible to set the client certificate or key to use when connecting to the schema registry.  The associated PR only added support for configuring the CA certificate used to connect to the SR.

**Comment by amruss** [comment]
Closing due to : https://github.com/cockroachdb/cockroach/pull/96533
