### ISSUE TITLE
perf: replace LLRB-tree with btree in interval.Tree

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#6465]
`interval.Tree` is the data structure backing `storage.{CommandQueue,TimestampCache}` and critical for performance. Our `interval.Tree` implementation is a fork of `biogo/store/interval` which is an augmented LLRB-tree. Switching the implementation to use a btree would probably be a decent performance win. See https://github.com/tv42/benchmark-ordered-map for comparison of various golang ordered-map data structures. This work would be slightly non-trivial as you couldn't just drop a btree into the implementation as you would have to "augment" it with the interval information of children.

**Comment by seiflotfy** [comment]
Might be a stupid question, but are children stored based on intervals?

**Comment by petermattis** [comment]
In an augmented LLRM-tree, the entries are ordered based on the start key of the interval and each node is "augmented" to also maintain the covering interval of all of its children. So the answer is sort of yes and no. Children are stored based on the start key of the interval and the entries contain the full interval as well as the interval covering all of the children. Wikipedia has a decent description: https://en.wikipedia.org/wiki/Interval_tree

**Comment by yaojingguo** [comment]
I would like to have a look.

**Comment by petermattis** [comment]
@yaojingguo Go ahead.

**Comment by sasha-s** [comment]
Depending what you store in your interval tree, you might get better performance by adding 1-2 levels of trie at top (should be easy to augment).

**Comment by yaojingguo** [comment]
@sasha-s, good suggestion. I will consider it after I finish the base version.

**Comment by tamird** [comment]
Should probably reopen this, since we haven't done the replacement.

**Comment by nvanbenschoten** [comment]
Addressed by https://github.com/cockroachdb/cockroach/pull/32251.
