### ISSUE TITLE
exec_log: `--vmodule=exec_log=2` does not log SQL query strings

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#64685]
**Describe the problem**

I started a single node with `--vmodule=exec_log=2` as described in the [docs on logging](https://www.cockroachlabs.com/docs/v21.1/query-behavior-troubleshooting.html#per-node-execution-logs). The resulting logs do not show the query string. In 20.2 and earlier, I used to be able to see the query string, which is useful for debugging.

**To Reproduce**

1. Start a fresh single-node cluster with `./cockroach start-single-node --insecure --cache=25% --max-sql-memory=25% --store=store --advertise-addr=localhost --http-addr :8081 --logtostderr --vmodule=exec_log=2 2> stderr.log`
2. Open a SQL shell and run `SELECT 1;`
3. Open stderr.log and search for `sql/exec_log.go`

The lines are in the format:
```
I210504 19:15:02.597933 738 sql/exec_log.go:281 ⋮ [n1,client=‹[::1]:60437›,hostnossl,user=root] 73  ‹{ExecMode:exec NumRows:1 SQLSTATE: ErrorText: Age:0.682 NumRetries:0 FullTableScan:false FullIndexScan:false TxnCounter:5}›
```

**Expected behavior**
The SQL query strings should be logged.

If I set `sql.log.unstructured_entries.enabled = true` then the old exec log format is used and I see the query strings.

**Environment:**
 - CockroachDB v21.1.0-beta.3
 
 **Context:**
 
 filed this issue upon @knz request

**Comment by knz** [comment]
is this a ga blocker?

**Comment by rafiss** [comment]
i'm asking other stakeholders about that, but i am defaulting to "no" because there is a workaround by setting `sql.log.unstructured_entries.enabled = true`

**Comment by knz** [comment]
thank you
