### ISSUE TITLE
sql: avoid materializing all rows from a subquery into a tuple

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#64692]
Depending on the execution mode of the subquery, we might be materializing all rows (which can be arbitrary large number in general case) into a single tuple to be stored as a single `tree.Datum`. This is suboptimal, and we should find a way to avoid this materialization. See #64464 for an example of OOM caused by this behavior.

Jira issue: CRDB-7208

**Comment by DrewKimball** [comment]
Fixed by #136506.
