### ISSUE TITLE
log: include crdb version into metadata envelope for logging events

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#64730]
**Is your feature request related to a problem? Please describe.**
This was raised by @knz from a conversation around handling/consuming different versions of logs on different versions of crdb

**Describe the solution you'd like**
We'd like to add the crdb version into the envelope for log events so that that metadata is available for all events

cc @piyush-singh for awareness

**Comment by knz** [comment]
This has been addressed by @cameronnunez
