### ISSUE TITLE
ui: only include DML in service latency chart

### ISSUE THREAD

**Issue by Azhng** [cockroachdb/cockroach#64741]
Follow up to #42174

Since queries other than Bulk IO statements can also cause spikes in our Service Latency graph, we want to exclude them as well from our latency metric. We also want to update our UI to reflect that the Service Latency graph is only measuring the DML queries.

**Comment by Azhng** [comment]
@Annebirzin  can you take a look and see if we need any design change or wording change for our service latency chart?

**Comment by Annebirzin** [comment]
@kevin-v-ngo Any thoughts on updating the name of the `Service latency` chart label to something like `DML Service Latency`? Seems related to the spreadsheet you started around messaging for labels and tooltips.

**Comment by kevin-v-ngo** [comment]
Yes, thanks Anne. Let me update the spreadsheet to keep all the updates in a single location. Archer, i'll send you the link.
