### ISSUE TITLE
auxiliary/checkpoints directory too large, is it safe to delete the directory manually?

### ISSUE THREAD

**Issue by skaco** [cockroachdb/cockroach#64763]
**Describe the problem**

6 out of 46 node cluster meet a visible capacity growth. And I found some nodes' auxiliary/checkpoint directory is over 300GB now.
This patch(#37722) seems help, but can I delete all the auxiliary checkpoints manually now?

**Comment by tbg** [comment]
Hi @skaco, yes it's fine to delete the checkpoints directories.
