### ISSUE TITLE
DST handling is inconsistent

### ISSUE THREAD

**Issue by paulbarbu** [cockroachdb/cockroach#64772]
**Describe the problem**

DST handling differs from that of PostgreSQL and to CRDB itself.
I observed this in two scenarios, which I think are related. Both scenarios generate `timestamptz`s, but depending on the method used, the results are inconsistent when in fact they should be the same.

Please note that the reference date is 25th October 2020 in the Europe/Bucharest timezone, a date where DST change from summer to winter occurs (-1 hour, 04:00 becomes 03:00). At that point there seem to be differences as described below.

**To Reproduce**

Setup and connect to a free cockroach cloud instance and run the two scenarios:

1. fixed `timestamptz` + varying `interval` **vs** varying `timestamptz` + fixed `interval`:
```sql
set timezone='Europe/Bucharest';
select time_tick,
    a,
    time_tick + interval '1 hour' as b
from
    (select '2020-10-25 00:00'::TIMESTAMPTZ + (i::text || ' hour')::interval as time_tick,
        '2020-10-25 00:00'::TIMESTAMPTZ + ((i+1)::text || ' hour')::interval as a
    from generate_series(0, 24) i) timestamps;
```

Result:
```
          time_tick         |             a             |             b
----------------------------+---------------------------+----------------------------
  2020-10-25 00:00:00+03:00 | 2020-10-25 01:00:00+03:00 | 2020-10-25 01:00:00+03:00
  2020-10-25 01:00:00+03:00 | 2020-10-25 02:00:00+03:00 | 2020-10-25 02:00:00+03:00
  2020-10-25 02:00:00+03:00 | 2020-10-25 03:00:00+03:00 | 2020-10-25 03:00:00+03:00
  2020-10-25 03:00:00+03:00 | 2020-10-25 03:00:00+02:00 | 2020-10-25 04:00:00+02:00    -- diff here
  2020-10-25 03:00:00+02:00 | 2020-10-25 04:00:00+02:00 | 2020-10-25 04:00:00+02:00    
  2020-10-25 04:00:00+02:00 | 2020-10-25 05:00:00+02:00 | 2020-10-25 05:00:00+02:00
  2020-10-25 05:00:00+02:00 | 2020-10-25 06:00:00+02:00 | 2020-10-25 06:00:00+02:00
[...]
  2020-10-25 23:00:00+02:00 | 2020-10-26 00:00:00+02:00 | 2020-10-26 00:00:00+02:00
(25 rows)
```

2. `timestamptz` **vs** `date_trunc` generated `timestamptz`
```sql
set timezone='Europe/Bucharest';
select dt as a,
    date_trunc('hour', dt) as b,
    experimental_strftime(dt, '%Y-%m-%dT%H:00:00%z')::timestamptz as workaround
from
    (select '2020-10-25 03:00+03:00'::timestamptz) dt(dt);
```

Result:
```
              a             |             b             |        workaround
----------------------------+---------------------------+----------------------------
  2020-10-25 03:00:00+03:00 | 2020-10-25 03:00:00+02:00 | 2020-10-25 03:00:00+03:00
(1 row)

```

**Expected behavior**
Column `b` to be the same as `a` in both scenarios, as is the case in PostgreSQL.

**Environment:**
 - CockroachDB version: v20.2.8
 - CockroachCloud Free Plan

**Additional info:**

This may not be the place, but I stumbled across the first scenario by the fact that CRDB is missing a `generate_series(timestamptz, timestamptz, interval)` function.

**Comment by RaduBerinde** [comment]
Salutari si multumim pentru raportul detaliat!

CC @otan

**Comment by otan** [comment]
this is not fun / 10.

for (1), this is because we use `AddDate`:

https://github.com/cockroachdb/cockroach/blob/72a144d8041361ecf1ad50669b729659e18a8139/pkg/util/duration/duration.go#L528

The different is obvious in https://play.golang.org/p/Zvs5oCzZYFa -- using AddDate(0, 0, 0) shifts the timezone unexpectedly, but omitting it gives the correct result.

for (2), in https://github.com/cockroachdb/cockroach/blob/72a144d8041361ecf1ad50669b729659e18a8139/pkg/sql/sem/builtins/builtins.go#L7207, we use time.Date which can mis-translate timezones.

However, using `time.Date` can lose precision. Going back to https://play.golang.org/p/Zvs5oCzZYFa, we can see `threeAMTime` is different to `threeAMTimev2` -- since 2020-10-25 has both 03+03 and 03+02, both are valid. Unfortunately using time.Date assumes it is +02, hence giving the incorrect result.

**Comment by RaduBerinde** [comment]
Yeah, I also found that they're both because if ambiguities in Date. This diff seems to fix these cases, but it feels kind of hacky and I'm sure there are other bugs lurking around:
```
diff --git a/pkg/sql/sem/builtins/builtins.go b/pkg/sql/sem/builtins/builtins.go
index ce367d7290..e2071c60ad 100644
--- a/pkg/sql/sem/builtins/builtins.go
+++ b/pkg/sql/sem/builtins/builtins.go
@@ -7133,6 +7133,12 @@ func truncateTimestamp(fromTime time.Time, timeSpan string) (*tree.DTimestampTZ,
 	secTrunc := 0
 	nsecTrunc := 0
 
+	// We use time.Date to construct the final date, but some specific times are
+	// ambiguous because of DST. So instead of using the result of time.Date
+	// directly, we construct it before and after the truncation and use the delta
+	// between them as the adjustment.
+	before := time.Date(year, month, day, hour, min, sec, nsec, loc)
+
 	switch timeSpan {
 	case "millennia", "millennium", "millenniums":
 		if year > 0 {
@@ -7204,7 +7210,8 @@ func truncateTimestamp(fromTime time.Time, timeSpan string) (*tree.DTimestampTZ,
 		return nil, pgerror.Newf(pgcode.InvalidParameterValue, "unsupported timespan: %s", timeSpan)
 	}
 
-	toTime := time.Date(year, month, day, hour, min, sec, nsec, loc)
+	after := time.Date(year, month, day, hour, min, sec, nsec, loc)
+	toTime := fromTime.Add(after.Sub(before))
 	return tree.MakeDTimestampTZ(toTime, time.Microsecond)
 }
 
diff --git a/pkg/util/duration/duration.go b/pkg/util/duration/duration.go
index b6d9ea2561..bcde1ef807 100644
--- a/pkg/util/duration/duration.go
+++ b/pkg/util/duration/duration.go
@@ -521,6 +521,11 @@ func Decode(sortNanos int64, months int64, days int64) (Duration, error) {
 
 // Add returns the time t+d, using a configurable mode.
 func Add(t time.Time, d Duration) time.Time {
+	if d.Months == 0 && d.Days == 0 {
+		// We want to avoid AddDate(0, 0, 0) because it may not be a no-op - the
+		// time can be ambiguous because of DST (see #64772).
+		return t.Add(time.Duration(d.nanos))
+	}
 	// We can fast-path if the duration is always a fixed amount of time,
 	// or if the day number that we're starting from can never result
 	// in normalization.
```
Curious if you have any better ideas?

**Comment by RaduBerinde** [comment]
Looks like that change to date_trunc is not good when the truncation is on the order of `millenium` because Duration can't express such a large delta.

**Comment by RaduBerinde** [comment]
Filed separate issue https://github.com/cockroachdb/cockroach/issues/64850 for adding `generate_series(timestamptz, timestamptz, interval)`
