### ISSUE TITLE
Add region/node information to Transactions/Statements pages

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#64779]
In 21.1 we added node information to Explain Analyze. We also added several capabilities from Explain Analyze into the DB Console. In 21.2, we want to add region and node information to the transactions and statements pages.

**Comment by maryliag** [comment]
@ianjevans  do we have the tooltip text for node and region?

**Comment by ianjevans** [comment]
Those sound good to me.
