### ISSUE TITLE
kv: Add server option for maximum number of intents per WriteIntentError for scans

### ISSUE THREAD

**Issue by aliher1911** [cockroachdb/cockroach#64783]
We added batching of discovered intents for subsequent resolutions during sst exports similar to what scan does (Issue: #59704, PR: #64131). On top of that, the change provides an option to limit number of collected intents to keep batch size predictable.

We may consider using the same approach to MVCCScan to make number of collected intents capped.

**Comment by aliher1911** [comment]
@nvanbenschoten is it used for range scans mostly? Can you provide some context on when this size would be relevant?

**Comment by nvanbenschoten** [comment]
> Can you provide some context on when this size would be relevant?

This size limit would be relevant for any large scans. Currently, there is no limit on the number of intents that a scan (coordinated by the `pebbleMVCCScanner`) can pull into memory and hand up to the lockTable in a `WriteIntentError`. So the only real limit is the size of a range, which can only hold about 512MB worth of intents before splitting.
