### ISSUE TITLE
ui: custom charts styling needs adjustment with new metrics ui lib

### ISSUE THREAD

**Issue by dhartunian** [cockroachdb/cockroach#64791]
via @aliher1911 

Looking on Custom Chart page with new fancy charts - it is a bit off.  Controls to add metrics to a chart are just below the window so you’ll have to scroll down to see them. Tried chrome and safari only. Not a big issue, but might look awkward for those who hide scrollbars.

<img width="1374" alt="Screenshot 2021-05-06 at 19 02 40" src="https://user-images.githubusercontent.com/986307/117346705-1a90c000-ae76-11eb-9816-1b4170125730.png">

This is using code on `master` currently and is due to the fact that new chart code added static level of padding under all line graphs to hastily provide room for a potentially large legend. We should either make this space autofit legend size or make the custom charts use separate styles to prevent this from happening.

Epic CRDB-8038

**Comment by thtruo** [comment]
Just wanted to verify, does this apply to both 21.1 and 20.2? cc @elkmaster @nkodali
