### ISSUE TITLE
kvnemesis: add AddSSTable

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#64824]
We should extend kvnemesis to issue AddSSTable requests.

Jira issue: CRDB-7281

**Comment by erikgrinaker** [comment]
In particular, the new `SSTTimestampToRequestTimestamp` and `DisallowConflicts` parameters make `AddSSTable` entirely MVCC compliant, which may make it easier to integrate into kvnemesis. They are now also emitted across rangefeeds.
