### ISSUE TITLE
Unexpected secondary index created when using ALTER TABLE to hash shard the primary key for the first time

### ISSUE THREAD

**Issue by thatnerd** [cockroachdb/cockroach#64838]
**Describe the problem**

When updating a non-hash-sharded primary key to a hash sharded one, a secondary index is created on the old primary key (in addition to the correct behavior of hash sharding the index).

This is a problem because anyone hash sharding a table is trying to avoid the problem of hotspotting, but by creating this secondary index along with the update to the primary key, CockroachDB is persisting the issue and a savvy user would always want to drop the new secondary index. This is an edge case for ALTER PRIMARY KEY where the typical desired behavior ([ALTER PRIMARY KEY docs](https://www.cockroachlabs.com/docs/v20.2/alter-primary-key.html)) is unexpected.

**To Reproduce**

1. Create a table without hash sharding it:
```
CREATE TABLE events (
     product_id INT8 NOT NULL,
     owner UUID NOT NULL,
     serial_number VARCHAR NOT NULL,
     event_id UUID NULL,
     ts TIMESTAMP NULL,
     data JSONB NULL,
     PRIMARY KEY (product_id ASC, owner ASC, serial_number ASC)
 );
```

2. Update the table to hash shard it:
```
SET experimental_enable_hash_sharded_indexes TO true;  -- may be necessary

ALTER TABLE events
    ALTER PRIMARY KEY USING COLUMNS (product_id, owner, serial_number)
    USING HASH WITH BUCKET_COUNT = 5;
```

3. Perform a SHOW INDEXES command:
```
> SHOW INDEXES FROM events;
  table_name |                index_name                 | non_unique | seq_in_index |                     column_name                      | direction | storing | implicit
-------------+-------------------------------------------+------------+--------------+------------------------------------------------------+-----------+---------+-----------
  events     | primary                                   |   false    |            1 | crdb_internal_owner_product_id_serial_number_shard_5 | ASC       |  false  |  false
  events     | primary                                   |   false    |            2 | product_id                                           | ASC       |  false  |  false
  events     | primary                                   |   false    |            3 | owner                                                | ASC       |  false  |  false
  events     | primary                                   |   false    |            4 | serial_number                                        | ASC       |  false  |  false
  events     | events_product_id_owner_serial_number_key |   false    |            1 | product_id                                           | ASC       |  false  |  false
  events     | events_product_id_owner_serial_number_key |   false    |            2 | owner                                                | ASC       |  false  |  false
  events     | events_product_id_owner_serial_number_key |   false    |            3 | serial_number                                        | ASC       |  false  |  false
  events     | events_product_id_owner_serial_number_key |   false    |            4 | crdb_internal_owner_product_id_serial_number_shard_5 | ASC       |  false  |   true
```

**Expected behavior**
No secondary indexes are on the table.

**Actual behavior**
A secondary index is created, keyed on the old primary key, `(product_id, owner, serial_number)`

Note that the primary behavior, the update to the primary key, worked correctly & as expected. It's only the creation of the secondary index that's unexpected.

**Additional data / screenshots**
N/A

**Environment:**
 - CockroachDB version: 20.2.8 server, 20.2.5 for SQL client
 - Server OS: CockroachCloud
 - Client app: Cockroach sql v.20.2.5

**Additional context**
Related to [this issue](https://github.com/cockroachdb/cockroach/issues/45889).

Like that issue, this is an edge case where the typical desired behavior for ALTER TABLE (the creation of the secondary index on the old keys) isn't desired.

Epic CRDB-7363

**Comment by awoods187** [comment]
cc @vy-ton  can you PTAL?
