### ISSUE TITLE
cdc: evaluate backport of avro_schema_prefix to 20.2

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/cockroach#64851]
A backport of https://github.com/cockroachdb/cockroach/pull/59710 to 20.2 may be desirable for certain users.

Normal policy would not support backport of _feature_ changes such as this, but we can consider exceptions with sufficiently strong guarantees against regression.

The implicit promise of a patch version is that they are strict improvements, break no contracts, and introduce no surprises. While there is no such thing as zero risk, we expect a high reward-to-risk ratio.

Let’s look at the implications of back porting the above-referenced PR. Issues to address:

- What happens in mixed-patch-version clusters?
- Are any contracts broken by such a change (such as protobuf)?
- For a user that is entirely unaware or uninterested in such a feature, is there _any_ behavioral change?
- Can a cluster setting make this safer?

gz#7047

Jira issue: CRDB-7304

**Comment by HonoreDB** [comment]
This would need to include a few different PRs, in reverse chronological order:

https://github.com/cockroachdb/cockroach/pull/61291
https://github.com/cockroachdb/cockroach/pull/59764
https://github.com/cockroachdb/cockroach/pull/59710
https://github.com/cockroachdb/cockroach/pull/59258

Of these changes, all of them are gated behind WITH options except part of the last one, which changes the behavior when a targeted table's name is changed from failure to continuing to write to the old topic. We'd probably want to revert that part of the change, and make sure nothing too weird can happen as a result.

**Comment by HonoreDB** [comment]
And it'd probably be possible to turn off most of the rest of the changes, and just leave the schema prefix and namespace.

**Comment by shermanCRL** [comment]
@HonoreDB I can imagine backporting one feature at a time, doesn’t have to be one big backport.

**Comment by lancel66** [comment]
The customer has reported that in their test of the backport (v20.2.7-8-g2bf52df278) no data is published when they create a CDC with Avro format. The binary format is working but when they use Avro it doesn’t produce events.

**Comment by lancel66** [comment]
Update: Customer was able to test this successfully in their environment after applying new 21.1 features documented here: https://www.cockroachlabs.com/docs/v21.1/create-changefeed.html. Specifically, they implemented the new flags full_table_name and avro_schema_prefix.

**Comment by shermanCRL** [comment]
As mentioned in Slack, let’s go ahead and implement this, and make sure to address the invariants in the [first comment](https://github.com/cockroachdb/cockroach/issues/64851#issue-878146533) above.

**Comment by HonoreDB** [comment]
Made a PR with the full diff here: https://github.com/cockroachdb/cockroach/pull/66091 ; it could be broken up into two but I'm not sure it'll make review particularly easier.

**Comment by miretskiy** [comment]
very stale
