### ISSUE TITLE
kvserver: TestMergeQueue fails with "unmerged expected startKey"

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#64866]
Observed in https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/2960243?

```
=== RUN   TestMergeQueue/both-empty
client_merge_test.go:4196: ranges unexpectedly unmerged expected startKey /Table/Max, but got "\xfa\x00\x00"
--- FAIL: TestMergeQueue/both-empty (0.00s)

=== RUN   TestMergeQueue/lhs-undersize
client_merge_test.go:4205: ranges unexpectedly unmerged expected startKey /Table/Max, but got "\xfa\x00\x00"
--- FAIL: TestMergeQueue/lhs-undersize (0.00s)

```

etc

cc @tbg for triage

**Comment by tbg** [comment]
Reproduces easily via

```
make stress PKG=./pkg/kv/kvserver/ TESTS='TestMergeQueue$$'
```

in (on my machine) tens of seconds.

**Comment by tbg** [comment]
Friendly ping.

**Comment by knz** [comment]
Just got a new instance of this off `master`

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/3182069?

**Comment by knz** [comment]
cc @cockroachdb/kv-triage

**Comment by nvanbenschoten** [comment]
While stressing `TestMergeQueue` heavily for https://github.com/cockroachdb/cockroach/issues/66942, I never saw this, so closing optimistically until we see it again.
