### ISSUE TITLE
kvserver: sync txn record cleanup can be cancelled prematurely

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#64868]
As described in https://github.com/cockroachdb/cockroach/issues/60585#issuecomment-834233980, when `IntentResolver.CleanupTxnIntentsAsync()` is called with `allowSyncProcessing=true`, the cleanup task can be run synchronously and using the caller's context. However, this cleanup task spawns off another async task to clean up the transaction record:

https://github.com/cockroachdb/cockroach/blob/a4b7a431093870393cac9f11287eaf282abdbd22/pkg/kv/kvserver/intentresolver/intent_resolver.go#L757-L762

In the synchronous case, this cleanup task will be connected to the caller's context, but runs async. As such, the call will likely return to the caller before `gcTxnRecord()` completes, and the caller may the cancel the context (due to e.g. `defer cancel()` or disconnection) which will cancel `gcTxnRecord()` as well.

**Comment by nvanbenschoten** [comment]
This is a nice find. @lunevalex should be aware of it when touching this code in https://github.com/cockroachdb/cockroach/pull/59881. In that change, I think we'll want to pass a Background context to `SendAsync` so that we don't hit the same kind of issue as the one described here.
