### ISSUE TITLE
server: expose system-level information in debug.zip

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#64876]
Debug.zip is a very useful tool for understanding the state of a cluster. It would be made even more useful by including information pulled from the system on each node.

For example, things like:

- `dmesg` output
- `top` output
- `sar` output (if available)
- /proc/cpuinfo
- /proc/meminfo
- etc

would help us further debug thorny issues that are sometimes made more difficult due to lack of information about the environment. 

Epic CRDB-7327

Jira issue: CRDB-7323

**Comment by knz** [comment]
NB This is partly an obs infra project.

**Comment by knz** [comment]
NB: on modern linux, `dmesg` retrieval is a privileged operation (usually root-only), and meanwhile we recommend operators do _not_ run crdb as root, so I think dmesg retrieval will be difficult in the general case.
