### ISSUE TITLE
security: Add version number to base64 form of join tokens

### ISSUE THREAD

**Issue by itsbilal** [cockroachdb/cockroach#64885]
Join tokens are created by the `create_join_token()` SQL builtin and
returned as base64 encoded strings. 

- To account for any future
  modifications to the join token format, the marshalled form of it
  should have a version number in it at a fixed offset (ideally 0)
  in addition to all the existing fields. This will ease in any future
  updates to the join token format.
- the base64 format can produce strings that start with a hyphen (`-`) and this confuses the command-line parser when pasted in argument position on the command line for `cockroach connect join`.

Stems from #60632.

**Comment by nikolawithk** [comment]
Hey, I’d like to work on this. It’d be my first contribution to the project. Ok if I poke around and try to get a draft implementation on my own? Anything I should keep in mind? Thanks
