### ISSUE TITLE
kv: deadlock in command queue

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#6495]
I am investigating why https://github.com/cockroachdb/examples-go/pull/63 deadlocks when run `few-one` with `-concurrency=3` (or higher). So far, I've traced it down to the command queue. Will post my findings here - currently looking at whether something was accidentally introduced in #6412.

**Comment by tschottdorf** [comment]
And indeed, disabling that code which expands the children appears to remove the deadlock:

```diff
diff --git a/storage/command_queue.go b/storage/command_queue.go
index d39911b..66136e9 100644
--- a/storage/command_queue.go
+++ b/storage/command_queue.go
@@ -129,8 +129,10 @@ func (cq *CommandQueue) getWait(readOnly bool, wg *sync.WaitGroup, spans ...roac
                // entries. If we encounter a covering entry, we remove it from the
                // interval tree and add all of its children.
                restart := false
                for _, cmd := range overlaps {
-                       if !cmd.expanded && len(cmd.children) != 0 {
+                       if !cmd.expanded && len(cmd.children) != 0 && false {
                                restart = true
                                cmd.expanded = true
                                if err := cq.tree.Delete(cmd, false /* !fast */); err != nil {
```

I'll try to isolate this more and reproduce this in unit-test setting. I suspect that there's something amiss in the order in which children are added/the parent removed.

**Comment by petermattis** [comment]
Try running dc907a71905c2687f571b26fb10c2d13c5cc7db2 (i.e. just before #6412). The order of adding the children and removing the parent shouldn't matter.

**Comment by tschottdorf** [comment]
Tried that commit, but unfortunately I need Summer.

One thing that strikes me as odd is that we allocate the IDs for the children when we create them, but we insert them at some later point in time. As far as I remember, this incrementing ID was introduced to track causality (i.e. a larger ID must have been inserted after a smaller ID), which is violated here. Going to see whether that puts us in a bind.

**Comment by petermattis** [comment]
I believe the IDs need to represent the order in which things were added into the `CommandQueue`, which is what the current code is accomplishing. You're investigating a deadlock: do you have instrumentation showing two commands that are mutually waiting for each other to complete?

**Comment by petermattis** [comment]
You could `git revert` the commits in #6412.

**Comment by tschottdorf** [comment]
You're right, the IDs do make sense that way. I'm going to change the example just enough to not need summer; I got enough conflicts on the reverts that I think that's the easier option. I don't have decent instrumentation yet and I only see the issue with three concurrent writers, but I'm going to extract something (after I've verified against dc907a7).

**Comment by tschottdorf** [comment]
Yep, can confirm that the anomaly was introduced there (tried dc907a7 and the merge commit 38488c4). Instrumenting.

**Comment by tamird** [comment]
FYI this also reproduces in one of the sql bank benchmarks.

**Comment by petermattis** [comment]
@tamird Which benchmark?

**Comment by tamird** [comment]
BenchmarkBank4_Cockroach-24 repros it when I run it on my GCE machine.

**Comment by petermattis** [comment]
That fails on my local machine when passing `-benchtime 5s`.

**Comment by tschottdorf** [comment]
I think I'm getting closer, though not quite there. When it deadlocks, I
see the last few commands waiting on a command which has since claimed have
removed itself from the command queue. However, it shows up multiple (!)
times in a single overlap computation. I pushed the instrumentation to
`cmdq-anomaly`, roughly the interesting output is

The bad guy who claims to be done:
W160504 11:28:26.335607 storage/replica.go:880  d4e4a290: adding
[/Table/51/1/"acc3"/7407903162154988194/0,/Table/51/4/7407903162154988194/"outbound_wash"/0/NULL)
@ 56830: 15 children (maxid 56845)
W160504 11:28:26.337571 storage/replica.go:880  d4e4a290: waited
W160504 11:28:26.338576 storage/replica.go:880  d4e4a290: remove 56830
expanded=true children=15

Good guy waiting forever: Note that it hits the unexpanded "bad guy",
expands it but suddenly hits it again four more times in the next cycle
(it's not hitting the children - those don't have the txn ID stored and
also don't have that same ID).
W160504 11:28:26.356349 storage/replica.go:880  0e71b177: overlap: 57600
d4e4a290
W160504 11:28:26.356354 storage/replica.go:880  0e71b177: expanding: 57600
W160504 11:28:26.356444 storage/replica.go:880  0e71b177: overlap: 57600
d4e4a290
W160504 11:28:26.356456 storage/replica.go:880  0e71b177: overlap: 57600
d4e4a290
W160504 11:28:26.356463 storage/replica.go:880  0e71b177: overlap: 57600
d4e4a290
W160504 11:28:26.356470 storage/replica.go:880  0e71b177: overlap: 57600
d4e4a290

I'm still figuring this out, so take the above with a grain of salt. I'll
update accordingly.

On Wed, May 4, 2016 at 11:15 AM Peter Mattis <notifications@github.com>
wrote:

> That fails on my local machine when passing -benchtime 5s.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/6495#issuecomment-216897288>
>
-- 

-- Tobias

**Comment by petermattis** [comment]
I'm seeing some weirdness where a command is removed from the interval tree and after being removed another command adds a dependency on it. I'm going to add some instrumentation to verify that this is in fact happening and see if I can determine why. Would be bad if the interval tree was returning commands that had been removed.

**Comment by tschottdorf** [comment]
Getting the same ID repeatedly in the overlaps also made me wonder whether maybe we're not clearing out that cached slice correctly. I didn't see any indication, but can't hurt to have it on the radar as you're looking at this.

**Comment by petermattis** [comment]
Added a `cmd.finished` field which I panic on when trying to add a dependency to a finished command. This happens immediately:

```
        panic: cannot add dependency on finished command
```

Now to figure out why.

**Comment by tschottdorf** [comment]
👍 Looks like you'll have this in the bag soon; I'll leave you to it to avoid duplicate effort.

**Comment by petermattis** [comment]
Looks like a problem with `interval.Tree`. The `finishing` statement is just before we delete command `1399` from the tree. Then I dump the contents of the tree and we see `1399` is still present. Hrmm.

```
I160504 12:46:43.083164 storage/command_queue.go:458  0xc820254fc0: 1399 {/Table/51/1/3 /Table/51/1/4} finishing
I160504 12:46:43.083167 storage/command_queue.go:468  0xc820254fc0: tree
I160504 12:46:43.083178 storage/command_queue.go:470    1404 {/Table/51/1/0/2/1 /Table/51/1/2/2/1/NULL}
I160504 12:46:43.083187 storage/command_queue.go:470    1403 {/Table/51/1/3 /Table/51/1/4}
I160504 12:46:43.083195 storage/command_queue.go:470    1399 {/Table/51/1/3 /Table/51/1/4}

```

**Comment by tschottdorf** [comment]
Those IDs are the tree-internal IDs? If it happens on a 3-element tree, maybe you can just serialize that one for a unit test?

**Comment by petermattis** [comment]
Yes, those are the tree-internal IDs. Trying to reproduce in a unit test is my next step.

**Comment by petermattis** [comment]
Found the problem: a bug in `interval.Tree.Insert` when the tree-internal IDs are not increasing. The specific bug was performing subtraction on two unsigned values and then comparing the result `< 0`. I'm mildly surprised that go didn't warn about that. We never hit this problem before because prior to #6412 we were always using sequentially increasing IDs when inserting into the interval tree.

**Comment by petermattis** [comment]
Btw, I'm pretty sure the insert bug only affects subsequent deletions. That is, the result of this bug will be deadlocks, but not corruption.

**Comment by bdarnell** [comment]
How likely is this to happen? It sounds like it's a regression from last
week; should it block the new beta?

**Comment by petermattis** [comment]
The problem is pretty likely under certain workloads. Definitely a
regression. I would recommend either skipping the beta this week or cherry
picking a fix.
