### ISSUE TITLE
kv: write replica tombstone on replica creation instead of removal

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#64966]
In the following TODO, we detail a hazard that can allow for the ID of a replica on a node to regress:
https://github.com/cockroachdb/cockroach/blob/79fe0c7cd3b1dc2e8d8443b80dc4a7493d9e14bf/pkg/kv/kvserver/replica.go#L1510-L1537

The solution to this is described in the TODO and also in discussion in https://github.com/cockroachdb/cockroach/pull/40892. In that PR, @ajwerner suggested that:
> I'm also curious about how y'all feel re: writing a tombstone in getOrCreateReplica when creating an uninitialized replica with a non-zero replica ID. That would provide the invariant that a store will always have a monotonically increasing set of non-zero replica IDs for a given range even across restart.

@bdarnell and @nvanbenschoten both liked the idea but felt it should be deferred to a later change. The time for that change has come.

The plan here is to write a tombstone (see `setTombstoneKey`) to box out replicas with IDs lower than a given replica when that replica is created, rather than (or in addition to?) when it is destroyed. This ensures that even if the replica is never initialized before a node restarts, a replica with a smaller ID (which is known to be old) cannot be created on the node upon a restart.

Fixing this will cause `TestProcessSplitAfterRightHandSideHasBeenRemoved/(4)_initial_replica_RHS_partition,_with_restart` to break, because the split will avoid creating a RHS replica with an ID below the ID in the tombstone.

Jira issue: CRDB-7367

**Comment by erikgrinaker** [comment]
This should be fixed by the `RaftReplicaID` work in #75761:

https://github.com/cockroachdb/cockroach/blob/e1c24edea342a83dbd250732e8d1de770cc47ae8/pkg/kv/kvserver/store_create_replica.go#L198-L277
