### ISSUE TITLE
ui: DB Console Metrics page with large number of nodes reports 0 in graph mouseover legend

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#64998]
Reported by @mikeczabator 

On graphs with a large number of metrics (in this case 98 nodes), the values don't populate in the mouseover legend.  Most are showing zero.  BUT when i just select a single node, we can see that there should be a value there
also, would it be possible to tighten that spacing up?  we cant see all of the values without zooming WAY out 

![image (12)](https://user-images.githubusercontent.com/1474303/117824376-6eb3ef80-b23c-11eb-88f1-d3045dd76780.png)

You can see when i zoom way way out, only some of the values are non-zero

![image (13)](https://user-images.githubusercontent.com/1474303/117824433-7d020b80-b23c-11eb-81c1-e807205e1745.png)

**Comment by thtruo** [comment]
@dhartunian I know the Cluster UI team will take over, but curious if you might have an idea of the root cause

**Comment by mikeczabator** [comment]
this is a `20.2` nightly build.  `cockroach-v20.2.9-27-gec09d3d182.linux-amd64.tgz`
