### ISSUE TITLE
sql: Overload resolution can not type placeholders in tuples

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#6501]
See https://github.com/cockroachdb/examples-go/issues/64#issuecomment-216952840.

We currently will fail to type placeholders in tuples during overload resolution. An example of this is the query `UPDATE fs.block SET data = $1 WHERE (id, block) = ($2, $3)` which will fail with the error `pq: could not determine data type of parameter $2`. Fixing this should be fairly straightforward.

**Comment by mberhault** [comment]
oops. sorry, looks like we both filed a bug: I've put more details in https://github.com/cockroachdb/cockroach/issues/6502 and a failing test in https://github.com/cockroachdb/cockroach/pull/6503
