### ISSUE TITLE
Surface the sampled query plan through the SQL CLI

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#65013]
Today we sample the query plan every 5 minutes (configurable) in the DB console. It would be great if this information was also surfaced through SQL for other 3rd party tools and partners to consume. 

This information should easily be programmatically consumed by customers (preferably JSON). 

This information should be easily inspected by users who are manually and visually identifying the plan tree in this view.

Epic CRDB-7561

**Comment by maryliag** [comment]
Store the value in `crdb_internal.node_statement_statistics` with json format

**Comment by Azhng** [comment]
@kevin-v-ngo  In the original RFC for persisted SQL stats, we store the `plan` information as a raw bytes column because we didn't want to commit to a specific encoding format for query plan. Now we have shipped this, can we consider the current form of plan encoding (the JSON column) something we can commit to and maintain backward compatibility with?

**Comment by kevin-v-ngo** [comment]
We would still have the plan_hash correct? Viewing the JSON plan over the raw BYTES would be a great update. A lot of great value in seeing the plan change over time including its statistics. It's feedback we're hearing quite a bit.

**Comment by Azhng** [comment]
> We would still have the plan_hash correct?

Yes we would still have `plan_hash`. However, for now this value has to be a dummy value until #63885 is shipped.

> Viewing the JSON plan over the raw BYTES would be a great update

My questions is regarding the stability of our current JSON representation of the plan in the future release. Can users of this JSON plan representation be assured that this is something they can build tooling on top of without major breaking changes.

**Comment by kevin-v-ngo** [comment]
Yes, we're releasing this in the node_level view already and so they should be consistent. Once released, there may well be feedback on how we can further improve it and we'll track it separately. It'll be an interactive process.  I wouldn't consider it a **major** breaking change since it's JSON. In addition, we'd treat any potential changes as 'breaking' through the normal process of identifying usage in telemetry and reaching out to our partners who are building on top of this view.
