### ISSUE TITLE
jobs: don't check the number of deleted rows

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#65048]
[jobs/registry.go](https://github.com/cockroachdb/cockroach/blob/master/pkg/jobs/registry.go#L941) contains this code
```go
	if len(toDelete.Array) > 0 {
		log.Infof(ctx, "cleaning up expired job records: %d", len(toDelete.Array))
		const stmt = `DELETE FROM system.jobs WHERE id = ANY($1)`
		var nDeleted int
		if nDeleted, err = r.ex.Exec(
			ctx, "gc-jobs", nil /* txn */, stmt, toDelete,
		); err != nil {
			return false, 0, errors.Wrap(err, "deleting old jobs")
		}
		if nDeleted != len(toDelete.Array) {
			return false, 0, errors.AssertionFailedf("asked to delete %d rows but %d were actually deleted",
				len(toDelete.Array), nDeleted)
		}
	}
```

It does not make sense to error out because some of the ids were already deleted (possible if another node is attempting cleanup at the same time). It definitely doesn't make sense for it to be an Assertion error. I have seen instances of this error in logs from a large cluster.

**Comment by jordanlewis** [comment]
@postamar and I think that it is not necessary to error here at all.
