### ISSUE TITLE
util/ring: TestRingBuffer takes unreasonably long time

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#65050]
From https://github.com/cockroachdb/cockroach/issues/65045#issue-889606575:
```
TestRingBuffer - 55.76s
```
We should investigate why it is so and make it faster. Also see #63388 - hopefully we can revert that change too.

**Comment by XuanYang-cn** [comment]
t.Parallel will help a bit.

On my machine, the test takes 11.41s, `ok  	example.com/ring	11.241s`

If add `t.Parallel`

```go
 func TestRingBufferA(t *testing.T) {                                                                             
     t.Parallel()                                                                                                 
      for count := 1; count <= maxCount; count++ {                                                                 
         t.Run("Parallel", func(t *testing.T) {                                                                   
             t.Parallel()                                                                                         
             testRingBuffer(t, count)                                                                                        
         })                                                                                                       
      }                                                                                                            
  }  
```

The test takes 7.89s, `ok  	example.com/ring	7.897s`, about 30% speedup.

**Comment by yuzefovich** [comment]
@XuanYang-cn thanks for looking into this! I agree, running the subtests in parallel is a good idea. I think it'd be reasonable to reduce the number of runs (i.e. `maxCount`) from 1000 maybe to 100. Do you wanna open a PR for these two ideas? I'll assign the issue to you for now.

**Comment by XuanYang-cn** [comment]
@yuzefovich OK，I'll open a pr
