### ISSUE TITLE
jobs: add better index for job claim and cancellation queries

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#65080]
**Is your feature request related to a problem? Please describe.**

Each node in the cluster runs a query periodically to find jobs in a claimable state which are claimed by expired sessions and to remove that assignment. 

https://github.com/cockroachdb/cockroach/blob/88754f2866fde1f37620b04c6a708eefc0b5be54/pkg/jobs/registry.go#L671-L675

Unassigned jobs in a claimable state are then claimed in a different periodic loop.

https://github.com/cockroachdb/cockroach/blob/88754f2866fde1f37620b04c6a708eefc0b5be54/pkg/jobs/adopt.go#L51-L58

Both of these transactions will lay down locks during their execution. These locks have an arbitrary duration and can block users reading the table, leading to a bad user experience. Another big problem with these queries is that they require scanning and performing an index-join on all rows in the relevant states even though they are only looking for rows with a specific `claim_session_id`. 

**Describe the solution you'd like**

Add a partial index to the jobs table which includes the `state` and the `claim_session_id` for the claimable states. This will allow for much more efficient update queries which scan narrower spans. 

Epic: CRDB-7912

**Comment by nvanbenschoten** [comment]
Note that because we store `claim_session_id` and `claim_instance_id` in the [same column family in the primary index](https://github.com/cockroachdb/cockroach/blob/72a8ee82c8ce1f7076ef37b7491c1b5a12516c41/pkg/sql/catalog/systemschema/system.go#L186), we'll need to also include `claim_instance_id` in the index to avoid the index-join entirely. This could simply be STORED in the index, as we don't filter on it.

**Comment by ajwerner** [comment]
@sajjadrizvi this is another migration for the job loop that would be beneficial. When we add the new columns we'll add them to this new partial index.

**Comment by ajwerner** [comment]
In #66889 we're adding the migration with this index. The follow-up work is to validate that the index works with testing.
