### ISSUE TITLE
Wrong sort order in DBConsole UI when copying pasting URL

### ISSUE THREAD

**Issue by daniel-crlabs** [cockroachdb/cockroach#65085]
**Describe the problem**

If someone sorts the `Statements` or `Transactions` page, let's say, by `Latency`, it works as expected. 
However, if the user copies the url that was generated and pastes it into a new browser window, the page is not sorted as per url. 

**To Reproduce**

Sample URL in my lab env: `http://lab-crdb01:8080/#/statements?sortKey=5&ascending=false`

For example, if I go to this page, you can see the items displayed prior to any sorting being applied:

<img width="1898" alt="preSort" src="https://user-images.githubusercontent.com/78774369/118035551-5675ca80-b339-11eb-8ddc-a983b4f22927.png">

Now, if I sort that page by `Latency` , you can see on the next screenshot, this is done correctly as expected:

<img width="1904" alt="correctSort" src="https://user-images.githubusercontent.com/78774369/118035640-7907e380-b339-11eb-9e39-961cda85e7f9.png">

Now, if I copy and paste the URL that was generated in the previous screenshot and paste it into a new browser window, the sorting is not correct, as shown on the next screenshot:

<img width="1900" alt="wrongSort" src="https://user-images.githubusercontent.com/78774369/118035728-98067580-b339-11eb-9519-d9f3003a8940.png">

**Expected behavior**
If we copy and paste the URL, the sort ordering should be preserved.

**Environment:**
 - CockroachDB version 20.2.7 (my lab) and 20.2.9 (Customer)
 - Server OS: CentOS

**Comment by cyrilchampier** [comment]
Mostly disturbing when I reload a page, and am forced to click 3 times on the sorting column to retrieve the same view as before the reload.

**Comment by maryliag** [comment]
The issue is that the sort column is being selected correctly, but it's always doing ascending order. You can notice that the latency is in ascending order on your second image. I'll deliver the fix soon :)
