### ISSUE TITLE
Using `cockroach cert create-client` after `cockroach connect` yields warning despite success

### ISSUE THREAD

**Issue by mikeCRL** [cockroachdb/cockroach#65087]
**Describe the problem**

Each time I use `cockroach cert create-client` after `cockroach connect` I receive the following warnings, despite the client cert I requested being created successfully.

Additionally there is no feedback indicating success in creating the cert.

``` shell
cockroach cert create-client root --ca-key=certs/ca-client.key --certs-dir=certs
W210506 19:34:54.884576 1 security/certificate_loader.go:339  [-] 1  bad filename certs/service.ca.rpc.crt: unknown prefix "service"
W210506 19:34:54.885295 1 security/certificate_loader.go:339  [-] 2  bad filename certs/service.ca.sql.crt: unknown prefix "service"
W210506 19:34:54.885328 1 security/certificate_loader.go:339  [-] 3  bad filename certs/service.rpc.crt: unknown prefix "service"
W210506 19:34:54.885350 1 security/certificate_loader.go:339  [-] 4  bad filename certs/service.sql.crt: unknown prefix "service" 
```

**To Reproduce**

1. Follow the instructions at https://deploy-preview-10539--cockroachdb-docs.netlify.app/docs/v21.1/auto-tls
2. Confirm new client cert works by connecting to the cluster.

**Environment:**

 - CockroachDB version: v21.1.0-rc.1
 - Server OS: MacOS 10.15.7
 - Client app:`cockroach`

**Additional context**

This is a known issue in this alpha release, per @aaron-crl.

Jira issue: CRDB-7429

**Comment by knz** [comment]
cc @jtsiros for tracking
