### ISSUE TITLE
kvserver: TestRejectedLeaseDoesntDictateClosedTimestamp deadlocks after Fatal

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#65109]
We have been seeing various instances of the kvserver tests timing out, with this test still running. I investigated the stack traces and found this:
```
goroutine 1109203 [chan receive, 16 minutes]:
github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestRejectedLeaseDoesntDictateClosedTimestamp.func7(0xc00b84b080, 0xc0043b67e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_closedts_test.go:573 +0x4f
runtime.Goexit()
	/usr/local/go/src/runtime/panic.go:636 +0x146
testing.(*common).FailNow(0xc00b84b080)
	/usr/local/go/src/testing/testing.go:732 +0x65
testing.(*common).Fatalf(0xc00b84b080, 0x64a71a3, 0x2c, 0xc002517530, 0x1, 0x1)
	/usr/local/go/src/testing/testing.go:806 +0x9e
github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestRejectedLeaseDoesntDictateClosedTimestamp(0xc00b84b080)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_closedts_test.go:595 +0x1d6c
testing.tRunner(0xc00b84b080, 0x6ac85d0)
	/usr/local/go/src/testing/testing.go:1123 +0x203
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1168 +0x5bc
```
So we Fatal here:
https://github.com/cockroachdb/cockroach/blob/dab476dd33456584705648af35d558dab3f99462/pkg/kv/kvserver/replica_closedts_test.go#L595

But when we unwind we get stuck in this deferred function:
https://github.com/cockroachdb/cockroach/blob/dab476dd33456584705648af35d558dab3f99462/pkg/kv/kvserver/replica_closedts_test.go#L572-L574

**Comment by andreimatei** [comment]
Ugh I'll do something. Thanks for debugging.

**Comment by RaduBerinde** [comment]
Some links to failed builds:
https://teamcity.cockroachdb.com//viewLog.html?buildId=2974526&buildTypeId=Cockroach_MergedExtendedCi
https://teamcity.cockroachdb.com//viewLog.html?buildId=2975000&buildTypeId=Cockroach_MergedExtendedCi
https://teamcity.cockroachdb.com/viewLog.html?buildId=2972642&buildTypeId=Cockroach_UnitTests
