### ISSUE TITLE
CockroachCloud asked for disabled authentication method: cleartext

### ISSUE THREAD

**Issue by fuwuqi59** [cockroachdb/cockroach#65117]
I received the following message when coding in Crystal-lang (https://github.com/will/crystal-pg) while attempting to connect to CockroachCloud. As indicated in the message: "Caused by: server asked for disabled authentication method: cleartext", it appears that CockroachCloud is asking for cleartext authentication. I used the connection string provided by CockroachCloud which includes "sslmode=verify-full" and the path to the downloaded certificate file. 

I managed to connect to CockroachCloud successfully by adding cleartext to auth_methods (i.e. auth_methods=cleartext,md5,scram-sha-256) but my concern is that this may not be secure in the long run. Also, prior to writing the Crystal-lang code, I have no issues connecting to CockroachCloud using the secure connection string provided by CockroachCloud with "sslmode=verify-full" and path to the certificate file (i.e. cockroach sql --url ..,). Please advise.

`Unhandled exception:  (DB::ConnectionRefused)
  from lib/db/src/db/connection.cr:34:0 in 'initialize'
  from lib/pg/src/pg/connection.cr:7:5 in 'new'
  from lib/pg/src/pg/driver.cr:3:5 in 'build_connection'
  from lib/db/src/db/database.cr:57:9 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'build_resource'
  from lib/db/src/db/pool.cr:47:34 in 'initialize'
  from lib/db/src/db/pool.cr:40:5 in 'new:initial_pool_size:max_pool_size:max_idle_pool_size:checkout_timeout:retry_attempts:retry_delay'
  from lib/db/src/db/database.cr:56:15 in 'initialize'
  from lib/db/src/db/database.cr:49:5 in 'new'
  from lib/db/src/db.cr:155:5 in 'build_database'
  from lib/db/src/db.cr:151:5 in 'build_database'
  from lib/db/src/db.cr:119:5 in 'open'
  from src/testcrycock.cr:30:6 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:110:5 in 'main_user_code'
  from /usr/share/crystal/src/crystal/main.cr:96:7 in 'main'
  from /usr/share/crystal/src/crystal/main.cr:119:3 in 'main'
  from __libc_start_main
  from _start
  from ???
Caused by: server asked for disabled authentication method: cleartext (PQ::ConnectionError)
  from lib/pg/src/pq/connection.cr:283:9 in 'check_auth_method!'
  from lib/pg/src/pq/connection.cr:264:9 in 'handle_auth'
  from /usr/share/crystal/src/kernel.cr:102:9 in 'connect'
  from lib/pg/src/pg/connection.cr:14:9 in 'initialize'
  from lib/pg/src/pg/connection.cr:7:5 in 'new'
  from lib/pg/src/pg/driver.cr:3:5 in 'build_connection'
  from lib/db/src/db/database.cr:57:9 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'build_resource'
  from lib/db/src/db/pool.cr:47:34 in 'initialize'
  from lib/db/src/db/pool.cr:40:5 in 'new:initial_pool_size:max_pool_size:max_idle_pool_size:checkout_timeout:retry_attempts:retry_delay'
  from lib/db/src/db/database.cr:56:15 in 'initialize'
  from lib/db/src/db/database.cr:49:5 in 'new'
  from lib/db/src/db.cr:155:5 in 'build_database'
  from lib/db/src/db.cr:151:5 in 'build_database'
  from lib/db/src/db.cr:119:5 in 'open'
  from src/testcrycock.cr:30:6 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:110:5 in 'main_user_code'
  from /usr/share/crystal/src/crystal/main.cr:96:7 in 'main'
  from /usr/share/crystal/src/crystal/main.cr:119:3 in 'main'
  from __libc_start_main
  from _start
  from ???`

**Comment by andreimatei** [comment]
@rafiss do you have any idea what might be triggering this "server asked for disabled authentication method: cleartext" ?

**Comment by rafiss** [comment]
I'm not familiar with Crystal-lang at all, but I scanned through the source-code you linked. Does crystal-pg actually support `sslmode=verify-full`? See https://github.com/will/crystal-pg/blob/cafe1e2a48764464299b44ab26449eb503be5934/src/pq/connection.cr#L55

**Comment by knz** [comment]
@fuwuqi59 let met explain what is going on. 
The authentication with CockroachCloud works in two layers:
- there is a TLS handshake between your driver and the server, which ensures (for your app) that you are communicating with CRL servers, and not some malicious intermediary.
- After the TLS session is set up, all the traffic is encrypted and thus confidential and immune to tampering.
- Over the TLS communication, the driver then *identifies* itself to the CockroachCloud server using an authentication method.

With PostgreSQL, this can be "clear text", "md5" or "scramh-sha-256". At this time, CockroachCloud only supports "clear text" (SCRAM will follow at some point - #42519). However, even though the method is called "clear text", notice how the password is transmitted over an encrypted link using TLS - so it's not really "clear text". It's encrypted over TLS.

The traditional issues around cleartext passwords (password sniffing, session replay) are mitigated by both the encryption and the requirement that your client driver verifies the server's identity (via `sslmode=verify-full`).

Does this clarify?

**Comment by knz** [comment]
We're going to support SCRAM authentication in v22.1. Hopefully your framework won't complain any more after that.
