### ISSUE TITLE
multiregion: default "PRIMARY REGION" / zone config for tenants

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#65115]
It is likely in serverless cluster with multiple tenants to have multiple regions (we're talking 20+!).

The default zone configs at this stage would mean that data on these clusters with be geo-distributed by default, which is not a great situation for latency.

# Solution 1: default PRIMARY REGION

Every database created in a tenanted setup will have a PRIMARY REGION which defaults to some value (arguably the region the user signed up for). This will automatically make every database have the correct zone configuration by default, and every table is correctly LOCALITY REGIONAL BY TABLE IN PRIMARY REGION so everything inherits well.

This can be stored on some metadata table on each tenant, or as a CLUSTER SETTING which can be controlled by the developer.

The downside with this approach for me is that we're forcing the user to immediately pickup multi-region abstractions. We still don't have that much data on whether these localities affect ORMs for me to be confident everything will play out nicely, but I trust it'll be mostly fine. However, the implicit behaviour is still a little iffy for me (and users may be confused why this is happening automatically with no opt-out).

# Solution 2: default zone config

Instead of making each database have a default PRIMARY REGION, just give them a zone configuration that defaults to being localised to the region they signed up for.

This means we don't "multi-region up" the user by default. A user can also change this DEFAULT zone config to whatever they want, instead of needing to learn about a new cluster setting.

**Comment by rmloveland** [comment]
Hey @otan I'm trying to figure out whether we need user-facing docs for this.

It looks like this is "just for tenants", but will the new cluster settings also show up  in the list of cluster settings on the [`SHOW CLUSTER SETTINGS`](https://www.cockroachlabs.com/docs/v20.2/show-cluster-setting) page?  Based on PR it looks like the answer is yes?

Is there anything else someone who downloads a `cockroach` binary should need to know or care about as a result of this?

**Comment by otan** [comment]
You could if you wanted to, I can see a case where DB admins may want this
cluster setting.

**Comment by rmloveland** [comment]
OK thanks Oliver! - for now I will at least make sure the autogenerated docs for the settings make it onto the cluster settings docs page.  If we need more docs going forward for some reason, that can be via another issue.
