### ISSUE TITLE
bulk *: prevent delayed application of non-mvcc commands

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#65128]
We use non-MVCC commands like `AddSSTable`, `ClearRange` and `RevertRange` in various bulk operations like RESTORE , IMPORT and IMPORT INTO, index creation, or cluster-to-cluster replication stream ingestion.  

In all of these operations, the assumption is made that it can use these non-MVCC operations, that are optimized for throughput rather than transaction safety, because the system has ensured that nothing else that might expect usual MVCC semantics is using that span, or in some narrow cases like index backfills, that the specific users of that span (write-only index edits) and the specific operation in question (addsst at old timestamp) will interact correctly (of course this assumption has sometimes proved incorrect, when operations such as BACKUP are still running on these spans).

But what happens if one of these operations sends a non-MVCC command to a span and then that operation is delayed, or retried and delayed, and arrives after an arbitrarily long delay? Taking the example of an`IMPORT INTO` that fails due to some data error and rolls back. It does more or less the following:

1. moves the table to an "OFFLINE" state to stop SQL traffic and waits for traffic to stop
2. checks if the table is initially empty and records this fact
3. runs a distsql flow with multiple processes which read input data and sends it with AddSSTable
4. hits an error in one processor that propagates back to the coordinator which cancels the flow
5. moves to a roll phased, to get the table back to the pre-IMPORT state, which was recorded as initially empty, meaning only IMPORT'ed data is in the span and thus it will send `ClearRange`s to delete it
6. transition the cleared table back to ONLINE, so SQL can resume using it

In the above, it is critical that operations in different steps never overlap: we can't e.g. scan to determine if it is empty if someone else might still be allowed to write after our scan, which is why step 1 waits. But what about if an operation in one step is delayed, and arrives after we've moved to the next step? For example, if as the flow in step 4 is tearing down, a node sends an `AddSSTable` request but it is delayed? If step 5 moves on to clear the range and _then_ the SST arrives and is applied, we could leave step 5 with a incomplete cleanup. Or alternatively, if one of step 5's `ClearRange` command is delayed, and arrives after step 6 has resumed SQL traffic, we could clear too late, and clear an accepted SQL write from after the table was back online.

Of course this is only a risk if we on move to the next step while it is still possible that one of the commands from the current step could still arrive and be applied, so the question is in what cases is this possible?

One potential cause of this seems to be an orphaned sender of such requests, e.g. an unclean termination of a distsql flow where the coordinator of the flow, that called `dsp.Run` can return, causing the coordination to move to the next step, while one of its remote processors is still running and still creating and sending `AddSSTable` requests. Another might be that the individual request.

Another concern is if individual requests can be delayed or retried by various layers. If a caller sent an `AddSSTable` request or a `ClearRange` and gets an ambitious result error, can that request still be somewhere waiting to arrive and be applied?

Epic CRDB-6982

**Comment by adityamaru** [comment]
The current solution we have in mind, to account for both unclean terminations of a DistSQL flow, and delayed delivery of the individual request, is to set a wall clock `Deadline` on the requests mentioned above. 

Taking the above IMPORT INTO example, we'd have a "deadline oracle" processor as the root of the import flow, on the coordinator node. This processor would be responsible for picking a deadline every x seconds. The deadline would be `time.Now() + y` where y is the deadline window within which we expect a request and its retries to be applied. This deadline would be passed to the downstream import processors to apply on their `AddSSTableRequests`. 

When we evaluate the request, the server will check if the deadline for the request has already passed, in which case it will return an error. We already have this logic for `ClearRange` - https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvserver/batcheval/cmd_clear_range.go#L71, although we do not set the Deadline on any request today.

On encountering an error that cancels the flow, we would find ourselves in the jobs' `OnFailOrCancel` hook. Before we issue a `ClearRange` to revert the partially imported data, we would wait for `y + MaxOffset` to ensure that any AddSSTableRequests within that timeframe are applied, and all subsequent requests will be rejected by the server. This processor can be reused by C2C streaming, Restore, and Import to protect against delayed request delivery.

@nvanbenschoten @ajwerner interested in getting your opinion on this!

**Comment by nvanbenschoten** [comment]
Do you mind talking more about this deadline oracle? I don't quite understand how it plays into the larger picture here and how it differs from each import processor picking timestamp from their local HLC clock.

A centralized oracle that assigns timestamps to operations and keeps track of the maximum timestamp handed out to any AddSSTableRequest does seem like a good idea. But it's only a part of the puzzle, and I don't see the other part here. The oracle allows us to place an upper bound on the timestamps that all AddSSTableRequest were issued with, which can be used on the success or failure of the job. On success, we could then use this as a lower bound for the time that the table can be brought online. On failure, we could use this to guard against delayed AddSSTableRequests landing. For instance, you could imagine that with a versioned sequence of bulk operations on ranges (https://github.com/cockroachdb/cockroach/issues/62585) and a policy that bulk operations must apply with monotonically increasing timestamps or be rejected with a `WriteTooOldError`, we could issue RevertRange requests across the entire keyspace at this timestamp and be guaranteed that no AddSSTableRequest would land after this point.

But if we are still using clock synchronization and `MaxOffset` for the second half, then why not just use clocks for the first half? All bets are already off under severe clock skew.

I think we need to have more of a discussion about whether we are ok with relying on clock synchronization to ensure the correctness of AddSSTable, other bulk operations, and schema changes in general. I know we've started going down this path in the past, but in light of discussions on https://github.com/cockroachdb/cockroach/issues/62585, we should explore whether there are safer approaches that provide stronger correctness guarantees. It's one thing to have a transient, well-understood hazard like stale reads under excessive clock skew. It's another to allow widespread data corruption during bulk operations when clocks exceed maximum clock skew bounds.

**Comment by dt** [comment]
> But if we are still using clock synchronization and MaxOffset for the second half, then why not just use clocks for the first half? All bets are already off under severe clock skew.

I think we're worried about orphaned/zombie processes. If a distsql processor has been told to make and send SSTs, if we then partition it off from the coordinator, or kill the coordinator or something, we want to be able to bound when we still need to assume ssts it is making and sending might apply. While a locally chosen deadline bounds delays for requests in-flight, it doesn't really bound how long a zombie proc that is making and sending new SSTs can keep doing so. Picking and distributing the deadlines from a central proc means if a remote proc loses touch with the coordinator, it can only carry on and have side effects until the last deadline it got expires.

**Comment by dt** [comment]
We could do something where we just have a processor, or the distsql infra itself, send periodic heartbeats from the coordinator to all processors while it is running, and then have a time-since-last-heartbeak check before we send an sstable which is sent with a locally picked deadline, and then our bound is "max heartbeat age" + "deadline duration", but if we already need to check a deadline during application for delayed-delivery due to in-flight delays, we may as well just let that check also protect against delayed sends I guess you could say, by giving the root of the flow control of the picked deadline.

**Comment by nvanbenschoten** [comment]
> I think what might be missing here is we're worried about orphaned/zombie processes that send requests, not just requests delayed while in-flight.

I see, thanks for explaining, this is all a good point.

The thing that concerns me here about all of these variations is the reliance on clock sync and specifically the use of MaxOffset for protection against very severe forms of corruption. In some sense, we're fairly conservative about our maximum clock skew bounds. But in another sense, we've seen that NTP misconfiguration can cause violations of our current 500ms limit. We also want to start pushing on clock synchronization more in the future. And I don't think we'd want data loss to be the cost of getting clock sync wrong.

If we do want a reliance on clock sync, I think I'd feel better if we disconnected this from the configured MaxOffset entirely and used a significantly larger value (10s?), since none of this is latency-sensitive. There's clock skew and then there's clock skew.

**Comment by dt** [comment]
>  none of this is latency-sensitive.

I wonder if this is true for the fail-over-to-second-cluster case. I think our current target is to be able to conclude the replication stream, revert-range to the last resolved timestamp and be ready to serve in a minute. Waiting 10s (plus however much our root deadline oracle forward-dates its deadlines, so probably another 5-10s) to start running the revert-range is a non-trivial chunk of that budget. I guess we can hope that in the happy case we get affirmative replies from all our processors that they finished all their AddSSTables and are exiting cleanly, so we only need the longer wait if we lost contact with a processor in the window before the fail-over button is pressed, but we probably need to use the worst-case bound for whatever we promise for RTO. Hmm.

Out of curiosity, how would your non-clock solution work? some sort of non-mvcc-op epoch which is part of each range's state, and then we send all the AddSSTables with one epoch, then the revertranges with the next, and a range promises to never eval a command with an older epoch?

**Comment by nvanbenschoten** [comment]
> Out of curiosity, how would your non-clock solution work? some sort of non-mvcc-op epoch which is part of each range's state, and then we send all the AddSSTables with one epoch, then the revertranges with the next, and a range promises to never eval a command with an older epoch?

Yes, something like this. Or instead of epochs, think timestamps that would be recorded into the range's non-mvcc log. This is one of the reasons I'm interested in https://github.com/cockroachdb/cockroach/issues/62585.

**Comment by ajwerner** [comment]
> > Out of curiosity, how would your non-clock solution work? some sort of non-mvcc-op epoch which is part of each range's state, and then we send all the AddSSTables with one epoch, then the revertranges with the next, and a range promises to never eval a command with an older epoch?
> 
> Yes, something like this. Or instead of epochs, think timestamps that would be recorded into the range's non-mvcc log. This is one of the reasons I'm interested in #62585.

The idea being like you'd propagate something to all of the spans you're going to AddSSTable into that enables running those before you start sending those requests and then afterwards you'd propagate something saying you're done? That might be really nice and explicit for things like SQL and making sure it doesn't read in an unsafe way. The cost would be two extra RPCs that do replication to every range involved.

**Comment by dt** [comment]
yeah, we've spitballed before about an "AdminLock" RPC we could run on a bunch of ranges to basically say "expect some AddSSTable coming your way" which, once they agree to, they'd refuse any other reads/writes unless they bore the lock token, then we'd send an AdminUnlock when we're done, which would also serve to lock-out any stray/late AddSSTables. I think we threw this around in the context of `IMPORT INTO` not taking the whole table offline, but rather just the spans that it actually ingests into, e.g. if you wanted to IMPORT INTO a partition while the other partitions stayed online for traffic.

**Comment by adityamaru** [comment]
We discussed this in our team meeting a few weeks ago, and the conclusion was that while #62585 might result in a more robust solution, it is not a direct goal for #62585, and thus risks missing this release. The time-based approach described above is easy to rip out of the c2c flow once we have a range-level solution in place. So we are going to go ahead with:

1. Pessimistically waiting for 10s + root processors deadline window in the case that all processors do not report that their AddSSTableRequests terminated cleanly. This will hit RTO, but we _think_ this will not be the common case. It also derisks us from severe clock skew as recommended by Nathan.

2. If all processors report clean termination, we can revert range without waiting as there will be no risk of delayed application of AddSSTableRequests.
