### ISSUE TITLE
sql: add information about retries in statement bundles

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#65146]
When we get a statement diagnostic bundle on a query that retries internally, the bundle reflects the last, successful run of the query. We should include more information, at least about how many times it was retried and what were the errors.

Epic: CRDB-8649

**Comment by maryliag** [comment]
@RaduBerinde is there any preference of locations for this information? Meaning a new file, or add this to one of the existing, etc
cc @kevin-v-ngo

**Comment by RaduBerinde** [comment]
One option would be to use `log.VEvent` or similar to log a `Executing after X retries` message so that it becomes part of the trace. That way it would be useful in more contexts (other tracing facilities, logspy).
