### ISSUE TITLE
sql: put the list of running transactions/statements and active sessions in statement diagnostics bundles

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#65144]
In many cases, queries run slowly because of contention. Other than establishing that, there aren't many details in a statement diagnostics bundle; nothing that would help you figure out which other query was using the same data.

@mattcrdb points out that it would be very useful to at least get a list of running transactions / statements at that time, like we get in debug.zip.

There may be some PII considerations here - maybe a customer is ok with PII data from one query and set of tables, but not others.

Epic: CRDB-8649

Jira issue: CRDB-7452

**Comment by mattcrdb** [comment]
`crdb_internal.cluster_transactions` and `crdb_internal.cluster_sessions` would be awesome. They are both collected in the debug.zip. It's entirely possible that the txn's that are listed there are completed by the time the trace completes, so I'm not sure how to keep a state of those tables throughout the trace, but I guess a snapshot of the table should work in most cases.

**Comment by maryliag** [comment]
@RaduBerinde is there any preference of locations for this information? Meaning a new file, or add this to one of the existing, etc
cc @kevin-v-ngo

**Comment by RaduBerinde** [comment]
I'd say a new file, maybe `running_transactions.txt`.

Would the statements in the transactions be scrubbed? If not I think there'd be PII concerns - it would increase the surface area from the one query and its related tables to potentially everything running on the cluster.

**Comment by kevin-v-ngo** [comment]
@mattcrdb and @RaduBerinde, @xinhaoz and I discussed taking it a bit further and adding additional information from crdb_internal.cluster_sessions, crdb_internal.cluster_transactions, and crdb_internal.cluster_queries. We will do a join across all tables into a single file representing the active workload from session down to the queries. Thoughts?

**Comment by kevin-v-ngo** [comment]
Sample query:

```
select s.node_id, s.session_id, s.session_start, s.application_name, s.user_name, s.client_address, s.oldest_query_start, s.alloc_bytes, s.max_alloc_bytes, s.active_queries, s.last_active_query,
       t.id, t.start, t.txn_string, t.num_stmts, t.num_retries, t.num_auto_retries,
       q.query_id, q.start, q.query, q.phase
from crdb_internal.cluster_sessions s
      join crdb_internal.cluster_transactions t ON s.session_id = t.session_id
      join crdb_internal.cluster_queries q ON q.txn_id = t.id;

```

**Comment by RaduBerinde** [comment]
Sounds good to me - as long as customers are aware that statement bundles might contain PII from *anything* running on the cluster, not just the relevant query and tables.

**Comment by kevin-v-ngo** [comment]
Makes sense! We should be fine since admin privileges are needed for [statement bundle ](https://www.cockroachlabs.com/docs/stable/cockroach-statement-diag.html) which is also required for accessing [SHOW](https://www.cockroachlabs.com/docs/v20.2/show-queries.html#required-privileges) and [CRDB_INTERNAL](https://www.cockroachlabs.com/docs/stable/crdb-internal.html#querying-crdb_internal-tables) which return other queries with literals.

We'll explicitly call this out in the statement bundle doc as well. @ianjevans - FYI

**Comment by maryliag** [comment]
No longer a priority
