### ISSUE TITLE
ui: links to capacity metrics are incorrect

### ISSUE THREAD

**Issue by taroface** [cockroachdb/cockroach#65143]
The following links in DB Console tooltips need to be updated for v20.2 and later (substituting the appropriate version number):

|location |old |new
|---|---|---
| Cluster Overview > Capacity Usage | https://www.cockroachlabs.com/docs/v20.2/admin-ui-cluster-overview.html#capacity-metrics (leads to 404) | https://www.cockroachlabs.com/docs/v20.2/ui-cluster-overview-page.html#capacity-metrics
| Storage Dashboard > Capacity graph | https://www.cockroachlabs.com/docs/v20.2/admin-ui-storage-dashboard.html#capacity-metrics | https://www.cockroachlabs.com/docs/v20.2/ui-cluster-overview-page.html#capacity-metrics
| Hardware Dashboard > Available Disk Capacity graph | https://www.cockroachlabs.com/docs/v20.2/admin-ui-storage-dashboard.html#capacity-metrics | https://www.cockroachlabs.com/docs/v20.2/ui-hardware-dashboard.html#capacity-metrics

Jira issue: CRDB-7451

**Comment by taroface** [comment]
cc @thtruo

**Comment by thtruo** [comment]
thanks @taroface for the fyi

cc @nkodali I'm gonna kickoff the exalate sync. this seems straightforward enough to do, perhaps we can pull it into the current sprint (or stage it for next)
