### ISSUE TITLE
Create cluster in a different namespace than the operator

### ISSUE THREAD

**Issue by Martin-Hogge** [cockroachdb/cockroach#65180]
**Describe the problem**

I created the `operator` on a namespace different than `default` and I wanted to create a cluster on a dedicated namespace as well but it seems that the `operator` is not reacting to the creation of the manifest if is not created in the same namespace of the operator.

**To Reproduce**

1. Create a namespace: `kubectl create ns cockroach`
2. Apply crdb: `kubectl apply -f https://raw.githubusercontent.com/cockroachdb/cockroach-operator/master/config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml -n cockroach`
3. Download the operator's manifest at `https://raw.githubusercontent.com/cockroachdb/cockroach-operator/master/manifests/operator.yaml`
4. Update every `namespace: default` by `namespace: cockroach`
5. Install the operator: `kubectl apply -f operatior.yaml -n cockroach`
5. Create another namespace: `kubectl create ns app-1`
6. Download the cluster manifest example at `https://raw.githubusercontent.com/cockroachdb/cockroach-operator/master/examples/example.yaml`
7. Update the name to be `cockroachdb-app-1` and update the namespace to `app-1`
8. Install the cluster: `kubectl apply -f example.yaml -n app-1`

Nothing happens and no logs inside the `operator`.

**Expected behavior**
A new cluster is created in the namespace `app-1`

**Environment:**
 - CockroachDB version: v20.2.8 / Kubernetes (GKE)

**Comment by andreimatei** [comment]
cc @keith-mcclellan

**Comment by kernfeld-cockroach** [comment]
I moved this issue into the cockroach-operator repo: https://github.com/cockroachdb/cockroach-operator/issues/561
