### ISSUE TITLE
Unable to create a derived timestamp field from a JSON field

### ISSUE THREAD

**Issue by cjireland** [cockroachdb/cockroach#65198]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

Using CRDB v20.2.4 try to create the following table:

CREATE TABLE public.customer_ledger_transaction
(
id VARCHAR(255) NOT NULL,
source VARCHAR(50) NOT NULL,
enriched_customer_ledger_transaction JSONB NOT NULL,
created TIMESTAMP WITHOUT TIME ZONE,
updated TIMESTAMP WITHOUT TIME ZONE,
account_id VARCHAR(255) as (coalesce (
enriched_customer_ledger_transaction -> 'customerLedgerTransaction' ->> 'accountId',
enriched_customer_ledger_transaction -> 'transactionEnrichment' ->> 'accountId'
)) stored,
amount NUMERIC(19, 3) as (cast ((enriched_customer_ledger_transaction -> 'customerLedgerTransaction' ->> 'amount') as numeric (19, 3))) stored,
auto_category VARCHAR(255) as (enriched_customer_ledger_transaction -> 'transactionEnrichment' ->> 'autoCategory') stored,
credit BOOLEAN as (cast ((enriched_customer_ledger_transaction -> 'customerLedgerTransaction' ->> 'credit') as boolean)) stored,
currency VARCHAR(3) as (enriched_customer_ledger_transaction -> 'customerLedgerTransaction' ->> 'currency') stored,
merchant_name VARCHAR(255) as (enriched_customer_ledger_transaction -> 'transactionEnrichment' -> 'merchant' ->> 'cleansedName') stored,
state VARCHAR(50) as (enriched_customer_ledger_transaction -> 'customerLedgerTransaction' ->> 'state') stored,
transaction_timestamp TIMESTAMP WITHOUT TIME ZONE as (cast ((enriched_customer_ledger_transaction -> 'customerLedgerTransaction' ->> 'transactionTimestamp') as TIMESTAMP WITHOUT TIME ZONE)) stored,
user_category VARCHAR(50) as (enriched_customer_ledger_transaction -> 'transactionEnrichment' ->> 'userCategory') stored,
CONSTRAINT CUSTOMER_LEDGER_TRANSACTION_PKEY PRIMARY KEY (id)
);

You will get this error:

 transaction_timestamp TIMESTAMP WITHOUT TIME ZONE as (cast ((enriched_customer_ledger_transaction -> 'customerLedgerTransaction' ->> 'transactionTimestamp') as TIMESTAMP WITHOUT TIME ZONE)) stored,
with the error:

ERROR: string::timestamp: context-dependent operators are not allowed in computed column

**Expected behavior**

The table should be created. The value is explicitly specified as WITHOUT TIME ZONE.

The column will contain values such as:

"transactionTimestamp": "2021-04-28T10:53:25.160Z", 

The customer wants the values to be stored in UTC so he can index it and then run range queries.

Discussion about this item was started under slack thread: https://cockroachlabs.slack.com/archives/C04U1BTF8/p1621002620170200

**Comment by jordanlewis** [comment]
I think the issue here is that the string->timestamp cast is marked as STABLE, not IMMUTABLE. I think this is because the outcome of the cast depends on the session setting.

But, I'm not sure that this particular cast (string->timestamp) *should* be banned from computed columns on principle. I'd be curious what other databases do here.

**Comment by RaduBerinde** [comment]
The casts are problematic because they support relative timestamps like 'now'. I added a parse_timestamp function which is like a cast but doesn't support these and is immutable. It is in the more recent 20.2.x releases.

**Comment by awoods187** [comment]
Let's link to your PR @RaduBerinde and close out this issue based on the internal conversation

**Comment by RaduBerinde** [comment]
This is the PR adding the `parse_timestamp()` built-in function: https://github.com/cockroachdb/cockroach/pull/60772 (20.2 backport: https://github.com/cockroachdb/cockroach/pull/60814).
This is the PR where I added an error hint mentioning the function: https://github.com/cockroachdb/cockroach/pull/65275 (backports: https://github.com/cockroachdb/cockroach/pull/65292 https://github.com/cockroachdb/cockroach/pull/65293).
