### ISSUE TITLE
kvcoord: txn heartbeater should stop monitoring record before sending EndTxn(commit=false)

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#65194]
As seen in e.g. `TestRollbackSyncRangedIntentResolution`, when a large transaction is being rolled back and hits the synchronous intent resolution path because the async task pool is full

https://github.com/cockroachdb/cockroach/blob/a4b7a431093870393cac9f11287eaf282abdbd22/pkg/kv/kvserver/intentresolver/intent_resolver.go#L430-L435

then the txn heartbeater may notice the txn record has been aborted before the `EndTxn` call returns (because it's still cleaning up intents) and kick off its own intent resolution:

https://github.com/cockroachdb/cockroach/blob/5e7f8bd7a511f58204a1419452fd4d439f9ccec8/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go#L331-L343

This may contend with the `EndTxn` resolution which may be doing ranged intent resolution via `ResumeSpans`, causing the client to wait longer than necessary. This was a contributing factor for #64092.

The heartbeater should probably stop monitoring the tnx record before sending the final `EndTxn` request, rather than waiting for the response.

**Comment by aliher1911** [comment]
To be more explicit we want to catch this event inside txnHeartbeater.SendLocked and preemptively stop heartbeats without waiting for txnHeartbeater.closeLocked() called as a part of interceptor stack cleanup.

Any ideas what would be the a good integration test for that?

**Comment by erikgrinaker** [comment]
If we're able to hook into the evaluation result we could e.g. force it to block for 2x longer than the heartbeat interval and make sure it hasn't kicked off intent resolution. But for this sort of test I'd normally use a unit test with mocks -- I see we already have a bunch of such tests in `txn_interceptor_heartbeater_test.go`, so maybe have a look at those for inspiration.

Btw, I see that we're setting `EndTxnRequest.TxnHeartbeating`, so presumably there is existing logic that assumes we're heartbeating during `EndTxn` requests -- it's worth looking into what the implications of disabling heartbeats would be. This task was something @andreimatei mentioned during a call, and it hasn't really been mapped out in any detail.

**Comment by aliher1911** [comment]
`EndTxnRequest.TxnHeartbeating` is used to assert that we don't have non-heartbeating transactions with transaction records when trying to evaluate possibility of 1PC commit:
```
	// Check whether the txn record has already been created. If so, we can't
	// perform a 1PC evaluation because we need to clean up the record during
	// evaluation.
	//
	// We only perform this check if the transaction's EndTxn indicates that it
	// has started its heartbeat loop. If not, the transaction cannot have an
	// existing record. However, we perform it unconditionally under race to
	// catch bugs.
	arg, _ := ba.GetArg(roachpb.EndTxn)
	etArg := arg.(*roachpb.EndTxnRequest)
	if etArg.TxnHeartbeating || util.RaceEnabled {
		if ok, err := batcheval.HasTxnRecord(ctx, r.store.Engine(), ba.Txn); err != nil {
			return false, roachpb.NewError(err)
		} else if ok {
			if !etArg.TxnHeartbeating {
				log.Fatalf(ctx, "non-heartbeating txn with txn record before EndTxn: %v", ba.Txn)
			}
			return false, nil
		}
	}
```
So it looks safe to stop heartbeats and still set TxnHeartbeating to true.

**Comment by andreimatei** [comment]
> So it looks safe to stop heartbeats and still set TxnHeartbeating to true

That's right. `TxnHeartbeating` is more like "txn might have ever heartbeated".
