### ISSUE TITLE
sql: include "client wait" time in EXPLAIN ANALYZE and other stats collection methods

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#65197]
Currently, if a client requests 50,000 rows from the database and pauses, client-side, while streaming the rows back, our EXPLAIN ANALYZE and other tracing output will not easily allow the user or developers to see that the "extra time" is caused by the client, and not the server.

We should detect this situation and expose it in EXPLAIN ANALYZE and other tracing outputs, such as the DB Console's statement view.

cc @bobvawter 

Jira issue: CRDB-7479

Epic CRDB-14510

**Comment by bobvawter** [comment]
I suspect that slow-read behavior also influences the reported SQL service latencies.  I've seen cases in production clusters where P99 holds steady at some suspiciously "round" numbers like 12 or 15 seconds.  Perhaps a "time to first record" latency metric could be added as well.
