### ISSUE TITLE
docgen: generate bnf for every statement in sql.y

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#65205]
Currently, docgen only generates bnf files for statements that have a stmtSpec defined for them
https://github.com/cockroachdb/cockroach/blob/v21.2.0-alpha.00000000/pkg/cmd/docgen/diagrams.go#L319

Now that we have automated diagram generation https://github.com/cockroachdb/generated-diagrams
it may be desirable to generate bnfs and diagrams for every statement.

If we generate a stmt for every sql.y statement, it is guaranteed to be "up to date" with the grammar. `diagrams.go` will continue to be used to replace or modify the bnf and diagrams upon generation.

cc @ericharmeling @ianjevans How important / desirable is this?

**Comment by ianjevans** [comment]
I think it's extremely important.

The history here shows that manually keeping `sql.y` and `diagrams.go` in sync is difficult. So even if we overgenerate BNF, that's preferable to having drift between the BNF and actual grammar.

The other advantage is that we can use the stmt BNF as a canonical text-based grammar for e.g. visually impaired users.

**Comment by RichardJCai** [comment]
Closed by https://github.com/cockroachdb/cockroach/pull/65278
