### ISSUE TITLE
clusterversion,*: remove old versions

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#65200]
**Is your feature request related to a problem? Please describe.**

In principle we ought to be able to remove old versions from the below file when we move on to the next version. Removing old versions forces removing code-paths which are gated on those versions. That's a good forcing function. This represents a reasonable chunk of work scattered over many teams. This issue tracks the actual removal of the versions.

https://github.com/cockroachdb/cockroach/blob/master/pkg/clusterversion/cockroach_versions.go#L321

**Comment by postamar** [comment]
I'm turning this into a meta issue after an attempt at breaking down the work this entails:

[ ] AbortSpanBytes
[ ] AddScheduledJobsTable
[ ] AlterColumnTypeGeneral
[ ] AlterSystemJobsAddCreatedByColumns
[ ] AlterSystemJobsAddSqllivenessColumnsAddNewSystemSqllivenessTable
[ ] Box2DType
[ ] CPutInline
[ ] ChangefeedsSupportPrimaryIndexChanges
[ ] ClosedTimestampsRaftTransport
[ ] CreateLoginPrivilege
[ ] EmptyArraysInInvertedIndexes
[ ] Enums
[ ] ForeignKeyRepresentationMigration
[ ] GeospatialType
[ ] HBAForNonTLS
[ ] ImplicitColumnPartitioning
[ ] LongRunningMigrations
[ ] MaterializedViews
[ ] MinPasswordLength
[ ] MultiRegionFeatures
[ ] NamespaceTableWithSchemas
[ ] NamespaceTableWithSchemasMigration
[ ] NewSchemaChanger
[ ] NoOriginFKIndexes
[ ] NodeMembershipStatus
[ ] NonVotingReplicas
[ ] PostTruncatedAndRangeAppliedStateMigration
[ ] PriorReadSummaries
[ ] ProtectedTsMetaPrivilegesMigration
[ ] RangefeedLeases
[ ] replacedPostTruncatedAndRangeAppliedStateMigration
[ ] replacedTruncatedAndRangeAppliedStateMigration
[ ] ReplicaVersions
[ ] SeparatedIntents
[ ] SequencesRegclass
[ ] TracingVerbosityIndependentSemantics
[ ] TruncatedAndRangeAppliedStateMigration
[ ] UniqueWithoutIndexConstraints
[ ] UpdateScheduledJobsSchema
[ ] UserDefinedSchemas
[ ] VirtualComputedColumns

Some of these are trivial to remove, others not so much. I'll take a stab at removing the trivial ones first, so as to better be able to break down the remaining work.

**Comment by irfansharif** [comment]
All that's remaining are these demarcation versions:

https://github.com/cockroachdb/cockroach/blob/980b49d5055df5bc2bd5c766f6ed9da8dc17910e/pkg/clusterversion/cockroach_versions.go#L157-L162

**Comment by postamar** [comment]
I'm curious as to why these can't also be removed. I see that they're being used but I don't understand what makes these versions special but I'm guessing there's a deeper reason. If someone were to add a few comments to explain this I'd be OK with closing this issue, for whatever that's worth.

**Comment by irfansharif** [comment]
Start21_1 is not special, we can remove it (#70268). The conditionals where it's being checked cannot evaluate to true any more. As for V21_1, it should be removed as part of #69828; left a TODO for Celia.

**Comment by postamar** [comment]
Thanks for doing this!
