### ISSUE TITLE
Add time-series metrics measuring symptoms users of pebble and/or storage are experiencing

### ISSUE THREAD

**Issue by joshimhoff** [cockroachdb/cockroach#65277]
API boundaries are great places to add time-series metrics measuring symptoms experienced by users of that API. For example, consider the pebble API:

```
package main

import (
	"fmt"
	"log"

	"github.com/cockroachdb/pebble"
)

func main() {
	db, err := pebble.Open("demo", &pebble.Options{})
	if err != nil {
		log.Fatal(err)
	}
	key := []byte("hello")
	if err := db.Set(key, []byte("world"), pebble.Sync); err != nil {
		log.Fatal(err)
	}
	value, closer, err := db.Get(key)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%s %s\n", key, value)
	if err := closer.Close(); err != nil {
		log.Fatal(err)
	}
	if err := db.Close(); err != nil {
		log.Fatal(err)
	}
}
```

We should have time-series metrics tracking the error rate & latency profiles of calls to db.Get. Not just calls to db.Get tho. Calls to pebble `db` in general, perhaps with different metrics for each API exposed.

@petermattis says: "I think the CRDB level operations have a better correspondence to what we'd want to measure." 

Re: whether this is a CRDB or pebble issue, I understand the idea that the pebble codebase shouldn't concern itself with exporting metrics to prometheus. It should export "metrics" (https://github.com/cockroachdb/pebble/blob/master/metrics.go#L125) that an application like CRBD can export to prom if the application chooses to do so. But I think Peter is saying something else up above. There are two APIs, the pebble API & the storage one that wraps the pebble one. I am not sure I understand the tradeoffs between instrumenting one of the two or even both yet, as I don't understand what is added at the layer above pebble.

This will compliment https://github.com/cockroachdb/cockroach/issues/65276.

Jira issue: CRDB-7559

**Comment by jbowens** [comment]
This issue just got tagged with `T-storage`, so it just came up in triage today. The current state of the world:

* KV publishes read batch evaluation latency and write batch evaluation latency times series.
* KV publishes log commit latency.
* Aggregate iterator stats are reported as time-series (#95790). These provide observability into what Pebble reads are doing and possible causes of latency, including block read durations.

@joshimhoff was there a particular metric you were hoping to see? I'd like to either focus this issue down or close it out.

NB: Cockroach does not use `db.Get`.

**Comment by joshimhoff** [comment]
Let's close this one. Thanks for the poke.
