### ISSUE TITLE
stability: http2Server received 4294965976-bytes data exceeding the limit

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6529]
sha: 5be1702

OOM on the first node with an odd message in the logs:
```
I160505 13:44:12.623842 http2_server.go:317  transport: http2Server received 4294965918-bytes data exceeding the limit 1048560 bytes
I160505 13:44:12.623957 http2_server.go:317  transport: http2Server received 4294965976-bytes data exceeding the limit 1048560 bytes
```

Seen before in #6444 but we assumed it was a uint32 overflow problem.
For this one, we do have a heap profile from seconds before the OOM killer got triggered:
```
3.78GB of 3.83GB total (98.82%)
Dropped 1258 nodes (cum <= 0.02GB)
Showing top 10 nodes out of 24 (cum >= 0.02GB)
      flat  flat%   sum%        cum   cum%
    3.77GB 98.48% 98.48%     3.77GB 98.48%  google.golang.org/grpc.(*parser).recvMsg
    0.01GB  0.34% 98.82%     0.02GB  0.56%  github.com/cockroachdb/cockroach/storage.(*TimestampCache).Add.func1
         0     0% 98.82%     0.03GB  0.66%  github.com/cockroachdb/cockroach/roachpb._Internal_Batch_Handler
         0     0% 98.82%     0.03GB  0.66%  github.com/cockroachdb/cockroach/server.(*Node).Batch
         0     0% 98.82%     0.03GB  0.66%  github.com/cockroachdb/cockroach/server.(*Node).Batch.func2
         0     0% 98.82%     3.77GB 98.49%  github.com/cockroachdb/cockroach/storage.(*RaftTransport).RaftMessage.func1.1
         0     0% 98.82%     3.77GB 98.49%  github.com/cockroachdb/cockroach/storage.(*RaftTransport).RaftMessage.func1.1.1
         0     0% 98.82%     0.02GB  0.65%  github.com/cockroachdb/cockroach/storage.(*Replica).Send
         0     0% 98.82%     0.02GB  0.65%  github.com/cockroachdb/cockroach/storage.(*Replica).addWriteCmd
         0     0% 98.82%     0.02GB  0.65%  github.com/cockroachdb/cockroach/storage.(*Replica).addWriteCmd.func2
```

[node0.go.heap.pdf](https://github.com/cockroachdb/cockroach/files/250489/node0.go.heap.pdf)

Full node log and goroutine dump (nothing special here)
[node0.stderr.txt](https://github.com/cockroachdb/cockroach/files/250494/node0.stderr.txt)
[node0.goroutines.txt](https://github.com/cockroachdb/cockroach/files/250492/node0.goroutines.txt)

After this node collapsed, the others followed in short order. Let's focus on this one though.

**Comment by bdarnell** [comment]
I still think the log message is a uint32 overflow in grpc. [This check](https://github.com/grpc/grpc-go/blob/8eb8dd0298f7a44728405d92c7ed710f65f7ad17/transport/control.go#L176-L184) which generates the message is called for every frame, but HTTP2 has a 24-bit frame size so it can't jump by more than 16MiB at once. 

It's not clear whether the log message has anything to do with the OOM (it happens a lot in this log). GRPC closes the connection when this happens, so my guess for the most likely way it would contribute to the OOM is by making us retry snapshot messages (and maybe grpc is somehow holding on to partially decoded messages from dropped connections?)

**Comment by mberhault** [comment]
yeah, I tried grabbing more detailed logs (and even tcpdump, which is really annoying with TLS/HTTP2), and there's really no way for something that big to go through. I was thinking maybe a header somewhere had a bad size, but that's hard to find too without adding debugging to grpc.

**Comment by tamird** [comment]
Should we send a PR upstream to change that to uint64?

**Comment by bdarnell** [comment]
I said overflow earlier, but I'm pretty sure it's not counting up to 4GB,
it's going negative and wrapping around, so uint64 won't help (signed ints
might mask the problem, but wouldn't solve it). Somewhere the additions and
subtractions on this counter are getting out of sync.

**Comment by tamird** [comment]
Well, the only subtraction is here https://github.com/grpc/grpc-go/blob/master/transport/control.go#L194

**Comment by bdarnell** [comment]
Line 208 of that file (`resetPendingData`) is also (effectively) a subtraction. When you walk back up the call graph, the addition and subtraction are so far removed from each other that it's difficult to see whether they match up. (the typical path adds in `http2Server.onData` and subtracts in `transport.Stream.Read`, but errors can take other paths)

**Comment by tamird** [comment]
https://github.com/grpc/grpc-go/pull/671

**Comment by tamird** [comment]
Upstream claims this is fixed. I'll send a PR to bump dependencies.

**Comment by bdarnell** [comment]
These don't appear to be happening any more.
