### ISSUE TITLE
has_database_privilege seems to restrict to current database only.

### ISSUE THREAD

**Issue by wodka** [cockroachdb/cockroach#65421]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

`SELECT datname FROM pg_database WHERE has_database_privilege(datname, 'CONNECT') ORDER BY datname`

used to return the list of usable databases of the current user.

with version 21.1.0 it only returns the current database.

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. create a cluster
2. create a db
3. grant user access to other db's
4. try to execute query -> will always only show the current db.

**Expected behavior**

the query should return a list of databases that can be used by the current user.

**Environment:**
 - CockroachDB version 21.1.0
 - Server OS: kubernetes
 - Client app `cockroach sql`

**Additional context**

Problem arises when using a query tool that lists databases the user can connect to. - now the user needs to first query with `use DATABASENAME;` and after that, only the selected db shows up (not the others there should be access to)

**Comment by wodka** [comment]
the issue can easily be reproduced in https://www.cockroachlabs.com/docs/v21.1/sql-playground

![Screenshot 2021-05-18 at 21 07 31](https://user-images.githubusercontent.com/385731/118709433-3fdde080-b81d-11eb-931d-f94323c45f92.png)
![Screenshot 2021-05-18 at 21 08 02](https://user-images.githubusercontent.com/385731/118709437-410f0d80-b81d-11eb-81b6-0c1cde917d7c.png)

**Comment by rafiss** [comment]
thanks for this report @wodka! In v21.1 we added the CONNECT privilege -- previously we had just hardcoded `has_database_privilege` to always return true for this. see https://github.com/cockroachdb/cockroach/pull/59676

However, we still don't require the CONNECT privilege to do anything (https://github.com/cockroachdb/cockroach/issues/59875 is the issue to track that).

If you'd like to rely on `has_database_privilege(d, 'CONNECT')` I recommend that you GRANT the CONNECT privilege to the users who you would like to have it.

(You could also just remove the `has_database_privilege` check from the WHERE clause, since the CONNECT privilege doesn't do anything yet. However, this isn't a great solution since in a future major version release the privilege might start being enforced.)

cc @RichardJCai

**Comment by wodka** [comment]
;) cannot remove it as it is part of another package (adminer)

with the note for CONNECT -> I would assume that ALL contains CONNECT as well.

![image](https://user-images.githubusercontent.com/385731/118770099-38502300-b881-11eb-9a62-3b39afda15e6.png)

also granting explicitly connect to a user does not work (also tried in the playground just now)

![image](https://user-images.githubusercontent.com/385731/118770249-659cd100-b881-11eb-9114-a1e782f55031.png)


for me this seems as if right now the has_database_priviledge can only return true if the current database is the passed database.

**Comment by RichardJCai** [comment]
Yeah looks like `has_database_privilege` is incorrectly implemented right now. How important is this / what is this used for? @wodka we can prioritize working on this if necessary.

```
root@:26257/defaultdb> use movr;
SET

Time: 1ms total (execution 1ms / network 0ms)

root@:26257/movr> SELECT datname FROM pg_database WHERE has_database_privilege('movr', 'CONNECT') ORDER BY datname;
   datname
-------------
  defaultdb
  movr
  postgres
  system
(4 rows)

Time: 3ms total (execution 3ms / network 0ms)

root@:26257/movr> use defaultdb;
SET

Time: 0ms total (execution 0ms / network 0ms)

root@:26257/defaultdb> SELECT datname FROM pg_database WHERE has_database_privilege('movr', 'CONNECT') ORDER BY datname;
  datname
-----------
(0 rows)

Time: 4ms total (execution 4ms / network 0ms)

root@:26257/defaultdb> 
```

**Comment by wodka** [comment]
I will work around this in the current release, removing the where condition temporary.

it is used here: https://github.com/vrana/adminer/blob/master/adminer/drivers/pgsql.inc.php#L277
