### ISSUE TITLE
v21.1.0: Events Ticker shows incorrect Node ID value (undefined)

### ISSUE THREAD

**Issue by stefanbenten** [cockroachdb/cockroach#65455]
**Describe the problem**

After upgrading the cluster from v20.2.10 to v.21.1.0 the Events Ticker in the Overview Dashboard of the Admin UI does not properly show the NodeID when those had rejoin events, etc.
I attached to screenshots at the end of this issue.

**To Reproduce**

1) Run Cluster with v20.2.10
2) Start Rolling Upgrade to v21.1.0
3) Check Overview Dashboard of the Cluster.

**Expected behavior**

I would expect that the proper node ID is shown instead of the _undefined_.

**Environment:**
 - CockroachDB version: v21.1.0
 - Server OS: Linux Debian 10
 - Client app: none involved
 
![grafik](https://user-images.githubusercontent.com/17809724/118785048-c4b61200-b890-11eb-9bba-c8eb99096392.png)

![grafik](https://user-images.githubusercontent.com/17809724/118785224-f202c000-b890-11eb-8c90-f0882249199b.png)

**Comment by andreimatei** [comment]
Hi @stefanbenten!
I couldn't reproduce what you're seeing. This is what I'm doing:
```
make bin/roachprod
bin/roachprod create local -n 3
bin/roachprod stage local release v20.2.10
bin/roachprod start local
bin/roachprod stage local release v21.1.0
bin/roachprod stop local:1
bin/roachprod start local:1
bin/roachprod stop local:2
bin/roachprod start local:2
bin/roachprod adminurl --open local:1
```
and the events look good to me.
Perhaps you can give more detailed instructions for a repro?

**Comment by stefanbenten** [comment]
@andreimatei Thanks for your response!
I cannot really give more details info really.
We also have in our cockroach cloud dev environment that we upgraded earlier.
Happy to get onto a call.

**Comment by florence-crl** [comment]
@andreimatei, I reproduced the issue in roachprod cluster `florence-test` using the commands below. You are welcome to examine this cluster for the next 11 hours.

```
roachprod create florence-test -n 3 --clouds=gce

# florence-test: [gce] 11h59m36s remaining
# florence-test-0001	florence-test-0001.us-east1-b.cockroach-ephemeral	10.142.0.4	35.196.86.141
# florence-test-0002	florence-test-0002.us-east1-b.cockroach-ephemeral	10.142.0.30	35.231.159.110
# florence-test-0003	florence-test-0003.us-east1-b.cockroach-ephemeral	10.142.0.6	34.75.124.101

roachprod stage florence-test release v20.2.9
roachprod start florence-test
roachprod adminurl florence-test 
# http://florence-test-0001.roachprod.crdb.io:26258/
# http://florence-test-0002.roachprod.crdb.io:26258/
# http://florence-test-0003.roachprod.crdb.io:26258/

roachprod ssh florence-test:1

ps aux | grep cockroach
kill 6667
wget -qO- https://binaries.cockroachdb.com/cockroach-v21.1.0.linux-amd64.tgz | tar xvz
mkdir 20.2.9
mv cockroach 20.2.9/
mv lib 20.2.9/
mv cockroach-v21.1.0.linux-amd64/* .
rmdir cockroach-v21.1.0.linux-amd64/
./cockroach start --insecure --store=path=/mnt/data1/cockroach --log-dir=/home/ubuntu/logs --cache=25% --max-sql-memory=25% --port=26257 --http-port=26258 --locality=cloud=gce,region=us-east1,zone=us-east1-b --join=35.196.86.141:26257 --advertise-host=10.142.0.4 --background
exit

roachprod stage florence-test release v21.1.0
roachprod stop florence-test:2
roachprod start florence-test:2
````

The difference it seems is that I used a GCE cluster rather than a local one.

**Comment by andreimatei** [comment]
I'm able to reproduce too with your instructions @florence-crl , even in a `--local` cluster.
While I was playing, I believe I've seen the "undefined" node ids even in an all-20.1.9 cluster, but then they rendered fine after a refresh. I could be crazy though cause I couldn't repro this part.
I'll leave it to the UI folks to dig.

**Comment by stefanbenten** [comment]
Glad to hear, we found a reproducer. We will be holding of on upgrading our clusters further until this is resolve.

**Comment by rafiss** [comment]
this looks like it was reopened accidentally
