### ISSUE TITLE
*: improve redaction

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#65453]
**Describe the problem**

On customer incidents, we regularly struggle with redacted logs which typically 

**To Reproduce**

Pick any CockroachCloud Zendesk ticket, download the debug zip, and see for yourself.

**Expected behavior**

Redaction, to the extent that is reasonable, leaves non-PII untouched and allows redacted and unredacted logs to be used more or less interchangeably. In particular, keys could be redacted smartly, by preserving the `/Table/descid/idxid` part and at least printing the types for everything else (`/Table/55/3/<int>/<string>#0` for example.

Lints would make redactability opt-out (a change from today's opt-in), that is, a linter would ensure that any new type added implements redactability. This is not true today. I also believe there are a few ways in which implementing redactability could be simplified, such as https://github.com/cockroachdb/redact/issues/5.

There would clearly need to be some transition, such as adding the linting code but instead of ensuring the absence of non-redactable structs, we'd assert that the number of violations does not increase. This also provides a rough score of how well we are doing in terms of redactability.

**Additional data / screenshots**

**Environment:**

**Additional context**

The below issues deal with aspects of redactability across CRDB:

https://github.com/cockroachdb/cockroach/issues/58610
https://github.com/cockroachdb/cockroach/issues/53310
https://github.com/cockroachdb/cockroach/issues/55862
https://github.com/cockroachdb/cockroach/issues/50044
https://github.com/cockroachdb/cockroach/issues/50043

Epic: CRDB-6668

Jira issue: CRDB-7612

**Comment by tbg** [comment]
Wasn't able to post this on Wednesday due to GH outage, but here it is:

level 🏽:  implement `redact.SafeFormatter` on one or more simple structs that shows up as redacted during `./cockroach start --logtostderr`, following the example, for example, [here](https://github.com/cockroachdb/cockroach/blob/c29c57ad62ea31704d2560714b9edc853b403a52/pkg/gossip/status.go#L119-L132)).
level 🏽‍♀️:  implement `redact.SafeFormatter` for `roachpb.Key`.
level ️: implement the linter above. Some design work upfront would be needed here, but the lint passes in `./pkg/lint/passes` are probably a good starting point. We could traverse the syntax trees and to investigate everything that is passed to a logging method (to see whether it implements redactability), but that may be incomplete (redaction might be important outside of logging). The easier, and perhaps also more helpful option, is to check all the types declared by cockroach code (i.e. inside of our repo and not in vendor) directly for whether the implement redaction. To get the linter in without having to boil the ocean, we allow exceptions (`type foo struct {} // nomustredact`) which would be implemented similar to [here](https://github.com/cockroachdb/cockroach/blob/15ee387449e5c9405f284c6c423a19dee0fc5d00/pkg/testutils/lint/passes/forbiddenmethod/forbiddenmethod.go#L103) or [here](https://github.com/cockroachdb/cockroach/blob/6d69977cfbaf35b576e48dbd9b16425cf146a15d/pkg/testutils/lint/passes/forbiddenmethod/naked_go.go#L40-L83) - I prefer the latter since I understand it; the former seems to misfire sometimes. We want two lint exceptions, `nomustredact`, and `todomustredact`. The idea is that to get the lint to pass, we add `// todomustredact` everywhere and count how many we added. We configure the linter to allow no more than that number of `todomustredact` tags, and also output the current number. This gives us a metric that we can optimize, and an easy way to find all the types that still need to be retrofitted. Thanks to code ownership (`go run ./pkg/cmd/whoownsit`), we could break that down on a per-team level as well (i.e. team that owns the file that declares the type owns the redactability of the type), for scheduling this work into the next release.
level ️ https://github.com/cockroachdb/redact/issues/5 I think this would be super valuable before we even think about nudging all teams to whittle down their redaction numbers.

I bet @knz has ideas on the above and other ideas as well.

With proper mentorship, I think all of the above are suitable for an intern as while of varying complexity, the work is at the library level with clear dependencies + docs, and not a ton of prior context is necessary.

**Comment by dhartunian** [comment]
Tracking the projects above in separate tickets:

- [ ] #66139 
- [ ] #66136 
- [ ] https://github.com/cockroachdb/redact/issues/5
- [ ] #66138

**Comment by knz** [comment]
I'm doing the struct and array auto-redaction in https://github.com/cockroachdb/redact/pull/19
Once this is in, the work for the first two points might be slightly simplified: we won't need to implement SafeFormat methods for structs when the "natural" struct representation is sufficient.

**Comment by tbg** [comment]
This umbrella issue has outlived its purpose, closing.
