### ISSUE TITLE
log: redact ApplicationName values that don't have a "$" prefix in logging events

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#65469]
**Describe the problem**

`ApplicationName` values that start with the "$" prefix are not redacted in telemetry; however those that _don't_ have that prefix are redacted.

We need to apply this special case for logging events so that we don't risk exposing PII. 

cc @knz @kevin-v-ngo 

Epic [CC-4113](https://cockroachlabs.atlassian.net/browse/CC-4113)

**Comment by maryliag** [comment]
@thtruo your description is a little confusing, you said that the ones start with $ are not redacted and those that have that prefix (meaning the same thing) are redacted. Which one from your sentence suppose to have a "without the prefix"? 
Can you make sure the description and title align? Thank you!

**Comment by thtruo** [comment]
@maryliag Ah there was a typo - I forgot to include "_don't_" in the second part of the first sentence in the description. I gave it an edit.

**Comment by knz** [comment]
Hm I'll take this one, it's not exactly trivial

**Comment by knz** [comment]
@thtruo are you sure about the epic link at the top? CRDB-4113 seems to be unrelated.

**Comment by thtruo** [comment]
Thanks @knz - ah that's (another) typo on my part: it should be **CC**-4113 not CRDB-4113. Just updated it in the description
