### ISSUE TITLE
sqlsmith: add support for multi-region syntax to SQL smith

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#65492]
**Is your feature request related to a problem? Please describe.**

We currently have no coverage for multi-region abstractions introduced in 21.1 in SQL Smith. In particular, we don't have a "seed schema" that uses the multi-region abstractions for setup. We also don't have support for performing DDLs (Alters) on tables/databases that use the multi-region syntax. 

I'm not entirely sure how this works with ccl, as the mutliregion stuff requires a CCL binary to work. 

Epic CRDB-8948

**Comment by ajstorm** [comment]
Added the o-postmortem tag as a result of https://github.com/cockroachdb/cockroach/pull/73040
