### ISSUE TITLE
`create schedule` ignores backup option `include_deprecated_interleaves`

### ISSUE THREAD

**Issue by schantaraud** [cockroachdb/cockroach#65558]
**Describe the problem**

Cannot create a backup schedule with option `include_deprecated_interleaves`.

**To Reproduce**

```sql
CREATE SCHEDULE full_backup_to_s3
	FOR BACKUP INTO 's3://[redacted]/cockroachdb?AUTH=implicit'
	WITH INCLUDE_DEPRECATED_INTERLEAVES
	RECURRING '12 18 * * *'
	FULL BACKUP ALWAYS
	WITH SCHEDULE OPTIONS ignore_existing_backups;
```

→ `ERROR:  failed to dry run backup: interleaved tables are deprecated and backups containing interleaved tables will not be able to be RESTORE'd by future versions -- use option "include_deprecated_interleaves" to backup interleaved tables anyway "engine"`

Same result with lowercase `include_deprecated_interleaves`.

Creating backups directly (without schedule) with this option works. e.g.:

```sql
BACKUP INTO '/2021/05/21-131753.88'
	IN 's3://[redacted]/cockroachdb?AUTH=implicit'
	AS OF SYSTEM TIME '2021-05-21 13:17:53.880284+00:00'
	WITH INCLUDE_DEPRECATED_INTERLEAVES;
```

**Expected behavior**

Creates a backup schedule with backup option `include_deprecated_interleaves`.

**Environment:**
 - CockroachDB version 21.1.0
 - Server OS: Linux/Ubuntu
 - Client app `cockroach sql`

**Comment by adityamaru** [comment]
Hey @schantaraud thanks for the detailed bug report! 

Apologies, this was an oversight on our part 🙁 We taught `BACKUP` about the option but forgot to teach scheduled backups about it. We'll fix this, and I'll ping the issue with the dot release you can expect it to be in. If this is a blocker, I can also offer you a custom binary to tide you over until the next dot release.

**Comment by schantaraud** [comment]
@adityamaru Thank you for your quick answer. Looking forward to the next dot release.
