### ISSUE TITLE
stress test for cockroach by sysbench in low qps

### ISSUE THREAD

**Issue by ysbarney** [cockroachdb/cockroach#65557]
Configuration:
cockroach version: v21.1.0
3-node cluster
machine: cpu 32, memory 64GB,  ssd 6.4T
Network delay: < 0.1ms

cockroach startup: ./cockroach start --insecure --cache=32GB --store==attrs=ssd,path=/xxxxx/cockroachdb/node0 --host=xxxx --port=26257 --http-port=8090 --join=xxx

sysbench version 1.0.14

oltp_point_select result:

[ 40s ] thds: 200 tps: 73343.57 qps: 73343.57 (r/w/o: 73343.57/0.00/0.00) lat (ms,95%): 7.17 err/s: 0.00 reconn/s: 0.00
[ 50s ] thds: 200 tps: 71887.49 qps: 71887.49 (r/w/o: 71887.49/0.00/0.00) lat (ms,95%): 7.70 err/s: 0.00 reconn/s: 0.00
[ 60s ] thds: 200 tps: 71021.89 qps: 71021.89 (r/w/o: 71021.89/0.00/0.00) lat (ms,95%): 7.17 err/s: 0.00 reconn/s: 0.00
[ 70s ] thds: 200 tps: 72246.88 qps: 72246.88 (r/w/o: 72246.88/0.00/0.00) lat (ms,95%): 7.30 err/s: 0.00 reconn/s: 0.00
[ 80s ] thds: 200 tps: 73266.53 qps: 73266.53 (r/w/o: 73266.53/0.00/0.00) lat (ms,95%): 7.17 err/s: 0.00 reconn/s: 0.00
[ 90s ] thds: 200 tps: 73564.83 qps: 73564.83 (r/w/o: 73564.83/0.00/0.00) lat (ms,95%): 7.17 err/s: 0.00 reconn/s: 0.00
[ 100s ] thds: 200 tps: 74035.98 qps: 74035.98 (r/w/o: 74035.98/0.00/0.00) lat (ms,95%): 6.91 err/s: 0.00 reconn/s: 0.00
[ 110s ] thds: 200 tps: 73238.68 qps: 73238.68 (r/w/o: 73238.68/0.00/0.00) lat (ms,95%): 7.17 err/s: 0.00 reconn/s: 0.00
[ 120s ] thds: 200 tps: 72684.14 qps: 72684.14 (r/w/o: 72684.14/0.00/0.00) lat (ms,95%): 7.30 err/s: 0.00 reconn/s: 0.00
[ 130s ] thds: 200 tps: 72764.15 qps: 72764.15 (r/w/o: 72764.15/0.00/0.00) lat (ms,95%): 7.43 err/s: 0.00 reconn/s: 0.00
[ 140s ] thds: 200 tps: 73284.87 qps: 73284.87 (r/w/o: 73284.87/0.00/0.00) lat (ms,95%): 7.30 err/s: 0.00 reconn/s: 0.00
[ 150s ] thds: 200 tps: 73420.26 qps: 73420.26 (r/w/o: 73420.26/0.00/0.00) lat (ms,95%): 7.04 err/s: 0.00 reconn/s: 0.00
[ 160s ] thds: 200 tps: 73556.94 qps: 73556.94 (r/w/o: 73556.94/0.00/0.00) lat (ms,95%): 7.17 err/s: 0.00 reconn/s: 0.00

oltp_insert result:
[ 40s ] thds: 200 tps: 32131.76 qps: 32131.76 (r/w/o: 0.00/32131.76/0.00) lat (ms,95%): 18.95 err/s: 0.00 reconn/s: 0.00
[ 50s ] thds: 200 tps: 31316.41 qps: 31316.41 (r/w/o: 0.00/31316.41/0.00) lat (ms,95%): 19.65 err/s: 0.00 reconn/s: 0.00
[ 60s ] thds: 200 tps: 30732.52 qps: 30732.52 (r/w/o: 0.00/30732.52/0.00) lat (ms,95%): 18.95 err/s: 0.00 reconn/s: 0.00
[ 70s ] thds: 200 tps: 31474.71 qps: 31474.71 (r/w/o: 0.00/31474.71/0.00) lat (ms,95%): 18.61 err/s: 0.00 reconn/s: 0.00
[ 80s ] thds: 200 tps: 30625.24 qps: 30625.24 (r/w/o: 0.00/30625.24/0.00) lat (ms,95%): 19.29 err/s: 0.00 reconn/s: 0.00
[ 90s ] thds: 200 tps: 29657.08 qps: 29657.08 (r/w/o: 0.00/29657.08/0.00) lat (ms,95%): 20.00 err/s: 0.00 reconn/s: 0.00
[ 100s ] thds: 200 tps: 30377.40 qps: 30377.40 (r/w/o: 0.00/30377.40/0.00) lat (ms,95%): 19.65 err/s: 0.00 reconn/s: 0.00
[ 110s ] thds: 200 tps: 30143.32 qps: 30143.32 (r/w/o: 0.00/30143.32/0.00) lat (ms,95%): 19.65 err/s: 0.00 reconn/s: 0.00
[ 120s ] thds: 200 tps: 29519.47 qps: 29519.47 (r/w/o: 0.00/29519.47/0.00) lat (ms,95%): 19.29 err/s: 0.00 reconn/s: 0.00
[ 130s ] thds: 200 tps: 29690.72 qps: 29690.72 (r/w/o: 0.00/29690.72/0.00) lat (ms,95%): 20.00 err/s: 0.00 reconn/s: 0.00
[ 140s ] thds: 200 tps: 29370.22 qps: 29370.22 (r/w/o: 0.00/29370.22/0.00) lat (ms,95%): 20.00 err/s: 0.00 reconn/s: 0.00
[ 150s ] thds: 200 tps: 30107.82 qps: 30107.82 (r/w/o: 0.00/30107.82/0.00) lat (ms,95%): 19.29 err/s: 0.00 reconn/s: 0.00

https://www.cockroachlabs.com/docs/v21.1/performance.html
Compare with sysbench result, my stress result: 
oltp_insert: 1/4~1/3,  oltp_point_select: 1/5~1/4

Do I have something wrong with cockroach? someone can give me tips.

**Comment by kernfeld-cockroach** [comment]
Hi @ysbarney, unfortunately we don't have the capabilities to concretely help with a performance benchmarking question like this, because there are too many things that we don't know about your deployment that could affect the performance.

To optimize on your own, I'd suggest reading our [Performance docs](https://www.cockroachlabs.com/docs/stable/performance.html) and ensuring that your deployment meets the [Production Checklist](https://www.cockroachlabs.com/docs/v21.1/recommended-production-settings) (maybe 4 GiB RAM/vCPU would help?). You might also find it helpful to consult the metrics in our [Low throughput](https://www.cockroachlabs.com/docs/stable/query-behavior-troubleshooting.html#low-throughput) troubleshooting docs. If you have more questions or find something interesting, please feel free to post on our [forum](https://forum.cockroachlabs.com/).

**Comment by ysbarney** [comment]
> ht also find it helpful to consult the metr

Thank you for your answer
