### ISSUE TITLE
sql: GRANT gets confused when username argument is not normalized

### ISSUE THREAD

**Issue by keith-mcclellan** [cockroachdb/cockroach#65556]
**Describe the problem**

usernames are supposed to be case insensitive.  Grant seems to be case sensitive.

**To Reproduce**

What did you do? Describe in your own words.

`CREATE USER "v-root-keycloak-ruKOXLtxBFOd6iO473d7-1621531073" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}';`
`GRANT ALL ON DATABASE keycloak TO "v-root-keycloak-ruKOXLtxBFOd6iO473d7-1621531073";`

```
* 1 error occurred:
* pq: user or role "v-root-keycloak-ruKOXLtxBFOd6iO473d7-1621531073" does not exist
```

```
show users
username options member_of
admin {}
dba {admin}
root {admin}
v-root-keycloak-rukoxltxbfod6io473d7-1621531073 VALID UNTIL=2022-01-25 10:10:10.555555+00:00 {}
```

**Expected behavior**
GRANT should succeed because usernames are case-insensitive.

**Environment:**
 - CockroachDB v21.1.0

**Additional context**
What was the impact?
A partner at Red Hat is working on Vault/Keycloak integration for customers to have a solution to manage users and permissions.

Epic CRDB-7217

**Comment by rafiss** [comment]
this relates to https://github.com/cockroachdb/cockroach/issues/54696 as well
