### ISSUE TITLE
Support similar_escape() function from Postgres

### ISSUE THREAD

**Issue by jhatcher9999** [cockroachdb/cockroach#65562]
**Is your feature request related to a problem? Please describe.**
I'm trying to import a PostgreSQL schema to CRDB, and I discovered that CRDB doesn't support this function.
Example:
`CREATE TABLE .... CONSTRAINT status_constraint CHECK (((status)::text ~ similar_escape('(ACTIVE|CLOSED|PENDING)'::text, NULL::text))) ....`

**Describe the solution you'd like**
I'd like to se CRDB adopt support for this function to improve it's Postgres compatibility.

**Describe alternatives you've considered**
I can use a basic regex to do the same thing

----

Instructions:

* Add a built-in in https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/builtins.go
* Add a test in https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/builtin_function, and run make testbaselogic FILES='builtin_function' TESTFLAGS='-rewrite' to test it.
* Submit a PR.

**Comment by TszKitLo40** [comment]
I want to try this issue.

**Comment by TszKitLo40** [comment]
Is `similar_to_escape` the same with it in pgsql? [https://github.com/postgres/postgres/blob/d3c878499c9d639ff06e0664d06b8c731e30c2fc/src/backend/utils/adt/regexp.c#L903-L959](url) It seems that there is no `unescaped` arg of `similar_to_escape` in pgsql.

**Comment by manavchawla98** [comment]
Hi! I'd like to try solving this issue. Could you provide me some example usage of `similar_to_escape`? I understand the method is required to convert SQL99 regexp pattern to POSIX style. Please advice that my understanding is correct.

**Comment by otan** [comment]
`similar_escape` and `similar_to_escape` should behave the same. we have a 3 arg similar_to_escape exposed right now, which is not standard.

`similar_(to_)escape` converts a SQL regexp to a POSIX regexp. They are slightly different -- SQL Regexp has '%' to mean match all, whereas '.*' is used for POSIX. So the pattern of usage is `x ~ similar_escape(sql_style_regexp, [optional_escape_char])`, as described in the description.

currently, our `similar_to_escape` 3 arg variant converts the 2nd argument `pattern` with escape as the 3rd argument `escape` to a POSIX regexp, and then matches it against the first argument. this is not standard, but you can re-use the internal code (namely return the regexp string returned by `RegexpCacheKey`) to return the correct thing.

we want to make four things work here:
* similar_escape(pattern) - convert pattern from SQL regex to POSIX regex
* similar_escape(pattern, escape) - converted SQL regex to POSIX regex with escape character `escape`
* similar_to_escape(pattern) -- same as similar_escape(pattern, escape)
* similar_to_escape(pattern, escape) -- same as similar_escape(pattern, escape)

**Comment by TszKitLo40** [comment]
@otan Thanks for you help. I will try to solve this issue.
