### ISSUE TITLE
Document new CHANGEFEED functionality

### ISSUE THREAD

**Issue by GlennFawcett-doordash** [cockroachdb/cockroach#65577]
**Describe the problem**

New functionality for `kafka_sink_config` and `changefeed.enable_pushback` are not documented.

- [https://github.com/cockroachdb/cockroach/pull/64584](https://github.com/cockroachdb/cockroach/pull/64584)

- [https://github.com/cockroachdb/cockroach/pull/63039](https://github.com/cockroachdb/cockroach/pull/63039)

**Comment by amruss** [comment]
Hey Glenn - I don't think we want to document these two things

`changefeed.enable_pushback` - This is a draft PR that isn't currently merged into the code

`kafka_sink_config` - Right now we have this as an advanced operator solution and purposefully have not documented it. We're still discussing internally whether we want to doc a different syntax and if/what guardrails to put up (for example: should we allow setting the frequency to longer than the gc.ttl is set for?) before we doc it more generally.

A basic explanation of the option: 

`CREATE CHANGEFEED ... WITH kafka_sink_config='{"Flush": {"MaxMessages": 1000, "Frequency": "1s"}}`'`

In this example: Max messages is set to 1000 and flush frequency is set to 1 second. Meaning it will flush to kafka EITHER after 1 second has passed or we batch 1000 messages, whichever comes first.
