### ISSUE TITLE
Resume CHANGEFEED from last committed cursor timestamp

### ISSUE THREAD

**Issue by GlennFawcett-doordash** [cockroachdb/cockroach#65573]
**Is your feature request related to a problem? Please describe.**

A CHANGEFEED can fail for multiple reasons internal to CRDB, the Kafka endpoint, etc...  After the CHANGEFEED fails, you have to figure out exactly when it failed from the logs and restart from that point after converting to the `cluster_logical_timestamp` epoch format.

**Describe the solution you'd like**

I would like for CRDB to store the last committed timestamp and have some way to simply RESUME from that point.  You can easily PAUSE and RESUME jobs, but if the job *fails* you must resubmit.  If the changefeed was created as an object in the database instead of a job, we could do something like:

```
RESUME CHANGEFEED <mychangefeed>
```

And it would simple pickup from where it left off.

Epic CRDB-2397

**Comment by amruss** [comment]
Note: Bulk IO also considering something similar, we probably want to do something more generic like `RESUME FAILED JOB _job_id_`

**Comment by amruss** [comment]
After talking with the team, we will likely want to do [this](https://github.com/cockroachdb/cockroach/issues/67965) instead

**Comment by miretskiy** [comment]
@amruss this can probably be closed? We have #36887 issue and few others that we're working on.

**Comment by spiffyyeng** [comment]
going to go ahead and close this, have a fix here: https://github.com/cockroachdb/cockroach/pull/68176

**Comment by spiffyyeng** [comment]
going to go ahead and close this, have a fix here: https://github.com/cockroachdb/cockroach/pull/68176
