### ISSUE TITLE
sql: Support for ALTER DEFAULT PRIVILEGES

### ISSUE THREAD

**Issue by cybros7** [cockroachdb/cockroach#65604]
Currently Cockroach does not support a statement similar to [ALTER DEFAULT PRIVILEGES](https://www.postgresql.org/docs/current/sql-alterdefaultprivileges.html) to alter the default privileges given to a role for all new tables added to a specific schema.

**Describe the solution you'd like**
Support for a statement with similar functionality to  [ALTER DEFAULT PRIVILEGES](https://www.postgresql.org/docs/current/sql-alterdefaultprivileges.html).

**Describe alternatives you've considered**
The current approaches of giving permissions on tables to users have some drawbacks:
1) Using `GRANT <PRIVILEGES> ON TABLE <db>.<schema>.* TO <ROLE>;` would only grant permissions on existing tables.
2) Granting permissions on DB level which are then inherited to tables means that if we want to give `SELECT` to a role for all tables in a given schema then the `SELECT` would also be granted on a DB level.

Epic CRDB-2586

**Comment by rafiss** [comment]
Thanks for this request @cybros7! We'll use this issue to track any changes we make here.

cc @RichardJCai
