### ISSUE TITLE
sql/pgwire: add telemetry for pgwire extended protcol

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#65622]
CockroachDB supports the pgwire extended protocol (https://www.postgresql.org/docs/current/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY) and many drivers use it by default.

Add telemetry to understand how much this protocol is used. The feature counters can be `pgwire.command.parse`, `pgwire.command.bind` , `pgwire.command.describe` , and `pgwire.command.execute`.

cc @vy-ton

**Comment by mneverov** [comment]
hi, i'd like to work on this
