### ISSUE TITLE
sql: "char" is supposed to truncate long values

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#65631]
In postgres:

```
rafiss@127:postgres> create table example (a "char");
CREATE TABLE

rafiss@127:postgres> insert into example values ('abc');
INSERT 0 1

rafiss@127:postgres> select a from example;
+-----+
| a   |
|-----|
| a   |
+-----+
SELECT 1
```

In cockroachdb
```
root@:26257/defaultdb> create table example (a "char");
CREATE TABLE

root@:26257/defaultdb>  insert into example values ('abc');
INSERT 1

root@:26257/defaultdb>  select a from example;
   a
-------
  abc
(1 row)
```

Note that this is DIFFERENT than `CHAR` -- `CHAR` will only truncate long values if the extra characters are whitespace, and cockroachdb already implements this correctly.

Epic CRDB-7217

**Comment by Polokghosh53** [comment]
I am a beginner to open source contribution. How should I get started with this issue?

**Comment by rafiss** [comment]
The change here will be fairly similar to https://github.com/cockroachdb/cockroach/pull/50492 -- that PR truncates whitespace for `CHAR` types.

The steps you'll need are:
1. update casting logic in pkg/sql/sem/tree/casts.go  -- the `AdjustValueToType` function should have a new case for `if typ.Oid() == oid.T_char` and perform truncation.
2. update constant resolution logic in pkg/sql/sem/tree/constant.go -- the `ResolveAsType` should have two cases for `if typ.Oid() == oid.T_char`
3. Add tests (you could also start with this step first and work backwards to the code change) -- add tests in `pkg/sql/logictest/testdata/logic_test/collatedstring` and `pkg/sql/sem/tree/testdata/eval/cast`  similar to the ones in the PR i linked.
