### ISSUE TITLE
sql/schemachanger: log stage transitions in new schema changer

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#65663]
**Is your feature request related to a problem? Please describe.**
A major goal of the new schema changer is improved understandability and ultimately improved observability and explainability. A very early step here should be insightful logging which reveals the progress of the new schema changer.

**Additional context**
This is really the very minimum we can do in terms of observability.

Epic: CRDB-2356

Jira issue: CRDB-7708

**Comment by postamar** [comment]
Subsumed by https://github.com/cockroachdb/cockroach/issues/77158
