### ISSUE TITLE
Converting database to schema leaves the schema in an unusable state

### ISSUE THREAD

**Issue by charsleysa** [cockroachdb/cockroach#65697]
**Describe the problem**

Converting database to schema "succeeds" but is missing the `USAGE` permission for user `appuser` and adding the `USAGE` permission to the schema fails with the following error
```
ERROR: user appuser must not have DROP, SELECT, INSERT, DELETE, UPDATE privileges on system schema with ID=174
```

**To Reproduce**

Run the following script
```sql
---
CREATE USER appuser;

CREATE DATABASE maindb;
GRANT CREATE, DROP, SELECT, INSERT, DELETE, UPDATE ON DATABASE maindb TO appuser;
SET DATABASE TO maindb;

CREATE DATABASE test2;
GRANT CREATE, DROP, SELECT, INSERT, DELETE, UPDATE ON DATABASE test2 TO appuser;
CREATE TABLE test2.test_table(hello int);

ALTER DATABASE test2 CONVERT TO SCHEMA WITH PARENT maindb;
GRANT USAGE ON SCHEMA test2 TO appuser; -- fails here
```

**Expected behavior**
All statements should execute successfully.
The final result should be a database `maindb` with a schema `test2` and a table `test2.test_table` that is usable by user `appuser`.

**Environment:**
 - CockroachDB: v20.2.7
 - Server OS: Amazon Linux 2
 - Client app: `cockroach sql`

**Additional context**
Since the issue occurs after the database is converted to a schema, all tables under that schema are left in an unusable state as only admin users can access the tables and app users cannot be granted access.

**Comment by ajwerner** [comment]
Thanks for the report! Looking into it.

**Comment by ajwerner** [comment]
@RichardJCai I'd love to get your take on this. This is bumping up against some real rough edges of our privilege model. I think I misunderstood how some pieces work. We allow the setting of various non-sensical privileges on the database descriptor to stand in for not having `DEFAULT PRIVILEGES` (see https://github.com/cockroachdb/cockroach/issues/16790#issuecomment-661843232). https://github.com/cockroachdb/cockroach/blob/34f64727dd05ef866f8188e204e6966c1d3285f3/pkg/sql/privilege/privilege.go#L66-L67

We then inherit these privileges here: https://github.com/cockroachdb/cockroach/blob/34f64727dd05ef866f8188e204e6966c1d3285f3/pkg/sql/create_table.go#L2153-L2155

Where this all went off the rails is I, mistakenly, assumed we passed on this behavior of allowing and inheriting privileges on schemas and thus it would be "fine" to just maintain those and, in fact, my (and Lucy's for that matter) hope was that they would have the same behavior for new tables within the user-defined schema.

We need to do something about this in the both short and long term -- we're in a bad spot. Here's a proposal:

1) For backport, strip these privileges in a read-time repair upgrade.
2) Add a long-running migration to fix them.
3) Fix default privileges etc.

**Comment by RichardJCai** [comment]
Yeah this isn't great, I'll quickly fix this issue when copying the privilege descriptor and add a read-time repair. 

Will likely get to the long-running migration for this next month when I do https://github.com/cockroachdb/cockroach/issues/65012.

**Comment by RichardJCai** [comment]
Currently on master, it errors when converting they database to a schema which is good - it won't succeed. Either way we'll still need a read-time repair and a backport to `ALTER DATABASE CONVERT TO SCHEMA`

On master

```
demo@127.0.0.1:26257/maindb> ALTER DATABASE test2 CONVERT TO SCHEMA WITH PARENT maindb;

ERROR: schema "test2" (62): user appuser must not have DROP, SELECT, INSERT, DELETE, UPDATE privileges on schema with ID=62
```
