### ISSUE TITLE
EXPLAIN ANALYZE only return node n1 when there is more then one plan

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#65695]
Running EXPLAIN ANALYZE with a query containing more than one plan, the second one (and so on) are not distributed (distribution: local) so all operators run on the gateway node n1. It's currently not taking into account that the KV requests themselves cross nodes.

Steps to reproduce:

- I created a cluster with 9 nodes and 3 regions, and added values on different regions, so when I do

```
> explain analyze select * from rides;
                                     info
-------------------------------------------------------------------------------
  planning time: 170µs
  execution time: 4ms
  distribution: full
  vectorized: true
  rows read from KV: 2 (335 B)
  cumulative time spent in KV: 5ms
  maximum memory usage: 20 KiB
  network usage: 1.9 KiB (10 messages)
  • scan
    cluster nodes: n1, n2, n3, n5, n7
    actual row count: 2
    KV rows read: 2
    KV bytes read: 335 B
    estimated row count: 1 (100% of the table; stats collected 4 minutes ago)
    table: rides@primary
    spans: FULL SCAN
```
I can see a list of nodes which it was executed on,
but if I do something with more steps like a filter that should return the same result, I get always just node n1:

```
> explain analyze select * from rides where city != 'abc';
                                       info
-----------------------------------------------------------------------------------
  planning time: 937µs
  execution time: 4ms
  distribution: local
  vectorized: true
  rows read from KV: 2 (335 B)
  cumulative time spent in KV: 4ms
  maximum memory usage: 10 KiB
  network usage: 0 B (0 messages)
  • filter
  │ cluster nodes: n1
  │ actual row count: 2
  │ estimated row count: 1
  │ filter: city != 'abc'
  │
  └── • scan
        cluster nodes: n1
        actual row count: 2
        KV rows read: 2
        KV bytes read: 335 B
        estimated row count: 1 (100% of the table; stats collected 5 minutes ago)
        table: rides@primary
        spans: [/'gcp-europe-west1' - /'gcp-us-west1']
```

**Comment by Azhng** [comment]
Ah this makes sense. I think there are couple causes here:
1. We had similar issue when we tried to add range information into `EXPLAIN ANALYZE`. KV doesn't really surface too much stats data to us. All the KV stats we are displaying here are computed inside SQL land. 
2. We use `SQLInstanceID` to display node information. In serverless environment, KV nodes do not have `SQLInstanceID` since they do not operate SQL server. I'm not sure that, in this case, if it even makes sense to go to KV nodes and ask for their node IDs.

**Comment by maryliag** [comment]
Closing as duplicate of https://github.com/cockroachdb/cockroach/issues/65985
