### ISSUE TITLE
ci: execution timeout in `lint`

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#65715]
Seen here: https://teamcity.cockroachdb.com/viewLog.html?buildId=3016019&buildTypeId=Cockroach_UnitTests

and I saw it earlier on another unrelated PR as well, so I think it's a general thing that has started happening.

**Comment by adityamaru** [comment]
https://teamcity.cockroachdb.com//viewLog.html?buildId=3011993&buildTypeId=Cockroach_MergeToMaster

**Comment by rickystewart** [comment]
Looks like Gazelle is timing out. It's spewing a lot of error messages that don't really make sense, some of which resemble the messages we saw in #65615.

**Comment by rickystewart** [comment]
Results of this fix look good, I'm not seeing timeouts regularly any more.
