### ISSUE TITLE
sql: Allow session variables to be passed into FmtCtx

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#65724]
This will allow us to implement DateStyle and IntervalStyle session params

Epic CRDB-2508

**Comment by otan** [comment]
i'm not fully convinced this is the full solution.

in particular, the core part of this being correct is having the FmtCtx being correct relies on https://github.com/cockroachdb/cockroach/blob/a5a59be87d690ea28394a7213c20190d9c6616a0/pkg/sql/pgwire/types.go#L236 succeeding, but that would introduce a circular dependency on pkg/sql and pkg/sql/pgwire to have that session variable propagated properly.

**Comment by otan** [comment]
I also wonder whether the cli is responsible for the datestyle and intervalstyle params, like it is for timestamptz.

**Comment by rafiss** [comment]
> I also wonder whether the cli is responsible for the datestyle and intervalstyle params, like it is for timestamptz.

hm i don't think that'll work, since the motivation here is to unblock customers who are using other tools that are not our CLI. so we need to be able to control the format that we send this data in over the wire

but your point about FmtCtx makes sense. maybe instead of that we'll need to plumb the format setting all the way through as a parameter, like what we do for `sessionLoc`: https://github.com/cockroachdb/cockroach/blob/a5a59be87d690ea28394a7213c20190d9c6616a0/pkg/sql/pgwire/types.go#L162

**Comment by otan** [comment]
it may make sense to be in fmt context too, e.g. it's obeyed in `select row_to_json(t) FROM ( VALUES  ('4 days 1 hour'::interval) ) t(a);`...
