### ISSUE TITLE
CockroachCloud UI Visibility into Availability Zone

### ISSUE THREAD

**Issue by theodore-hyman** [cockroachdb/cockroach#65733]
**Is your feature request related to a problem? Please describe.**

Currently, CockroachCloud customers can see the region where the nodes are deployed for a given CockroachCloud cluster, but the UI does not give visibility to what specific Availability Zone each node is in

**Describe the solution you'd like**

It would be nice to be able to see the AZ where the node is deployed in the CC interface, not just the region. Having more easy visibility into the AZ should help the customer in the process of scaling up per @joshimhoff 

**Describe alternatives you've considered**

Alternatively, it is possible to see the same data using this syntax:

```
SELECT
	node_id, address, locality
FROM
	crdb_internal.kv_node_status;
```

**Additional context**
Please note that @udnay has noted concern about giving customers more visibility into CC AZ because we want to be careful about exposing certain implementation details, as this could cause issues in the future depending on what customers do with these details. 

Epic CRDB-9024

Jira issue: CRDB-7735

**Comment by kevin-v-ngo** [comment]
Created the following CC console task: CC-4396
