### ISSUE TITLE
storage: Tag pebble logger with store ID

### ISSUE THREAD

**Issue by itsbilal** [cockroachdb/cockroach#65742]
Currently, Pebble log lines across different stores as well as the temp store
are all merged together, with no way to disambiguate their actual source
Pebble instance:

```
I210526 13:22:56.719350 69652663 3@vendor/github.com/cockroachdb/pebble/compaction.go:2798 ⋮ [n1,pebble] 254087  [JOB 32770] sstable deleted 110830
```

Notice how the `[n1, pebble]` part does not mention the store ID that generated this log line.
This is opposed to the rest of Cockroach which appropriately sets the tag with the store `s1`
below:

```
W210526 18:42:43.828287 337 kv/kvserver/store.go:1683 ⋮ [n1,s1,r6/1:‹/Table/{SystemCon…-11}›] 46  could not gossip system config: ‹[NotLeaseHolderError] can't determine lease status of (n1,s1):1 due to node liveness error: liveness record not found in cache›
```

The store ID needs to be propagated to where the log context is set (`NewPebble` in pebble.go),
as that currently happens before the store ID is set on the store's ambient context (`Start` in pkg/kv/kvserver/store.go).
Similarly, the temp engine needs to set a context of `temp` instead of a store ID to disambiguate its
log lines in the pebble log.

**Comment by petermattis** [comment]
This looks like a dup of https://github.com/cockroachdb/cockroach/issues/64798.

**Comment by itsbilal** [comment]
Oops, missed that. Closing in favour of #64798.
