### ISSUE TITLE
bulkio,cdc: upgrade SDKs for 21.2

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/cockroach#65783]
Let’s upgrade our dependencies for the following, for the 21.2 cycle:

- [x] AWS SDK [[releases](https://github.com/aws/aws-sdk-go/releases)] - #67011
- [x] Google Cloud SDK [[releases]](https://github.com/googleapis/google-cloud-go/releases) -https://github.com/cockroachdb/cockroach/pull/68650
- [x] Azure SDK [[releases](https://github.com/Azure/azure-sdk-for-go/releases)] - #67017
- [x] Avro [[releases](https://github.com/linkedin/goavro/releases)] - #67572
- [x] Sarama [[releases](https://github.com/Shopify/sarama/releases)] - #66670
- [ ] Vitess [[releases](https://github.com/vitessio/vitess/releases)]

Let’s be methodical, within reasonable time limits:

- Pick a version that has baked for a while, not necessarily latest. Look for a high patch number. 
- Read the commit history between old and new version
  - Optionally, read the diff, though this may be too big
- One commit for each, so we can bisect/revert

Have a look at how we [did this in the previous cycle](https://github.com/cockroachdb/cockroach/issues/55748).

**Comment by amruss** [comment]
Going to leave in triage for now and revisit/assign in July

**Comment by shermanCRL** [comment]
Do we (did we) loop back to get the latest Google Cloud / GRPC? I see a note from @adityamaru that we should have an upstream fix.

**Comment by adityamaru** [comment]
Yup it has been upgraded, I forgot to update this issue. Done now!

**Comment by shermanCRL** [comment]
Did we intend to upgrade Vitess? Looks like we are using a fork? https://github.com/cockroachdb/vitess

**Comment by shermanCRL** [comment]
Closing this as complete, even though we didn’t make a call on Vitess. Will create a new one for v22.1.
