### ISSUE TITLE
sqlproxy: transfer connections away from disproportionally busy tenant pods

### ISSUE THREAD

**Issue by andy-kimball** [cockroachdb/cockroach#65826]
Once we support load balancing tenant traffic across multiple SQL pods, we will encounter the problem of uneven load across those pods. Some pods will be too busy and some too quiet. In order to rebalance traffic, the proxy should use the upcoming "[session migration](https://docs.google.com/document/d/1jbNL9oK6-QccHjKBji8adUZhjI00b1jyiokFr9fpQ58/edit)" SQL functionality to move connections from busier nodes to less busy nodes. Session migration will support dehydrating an active SQL session into bytes and then rehydrating it on a different SQL node without disturbing the session.

Jira issue: CRDB-7765

**Comment by andy-kimball** [comment]
@rafiss, is there any issue or other docs that describe the work we've done and/or still need to do on session migration in SQL?

**Comment by rafiss** [comment]
@andy-kimball the current state is in this draft PR (worked on it during last release, but didn't finish): https://github.com/cockroachdb/cockroach/pull/66113

The remaining work is to handle "local" session variables (those that only affect the gateway node), and to handle prepared statements. We haven't yet assigned this work on our team for this release. Do you have a sense of when load balancing tenant traffic across multiple SQL pods will be implemented?

**Comment by andy-kimball** [comment]
I don't have a good sense yet, because I'm not sure how big a problem uneven traffic load will be in practice. It may turn out to be an occasional but not urgent problem. Or it may quickly become a high-priority issue. Of course, we can always shed load by cutting connections rather than transferring them, but we may get significant customer complaints if their applications cannot tolerate occasional disconnects.

**Comment by jaylim-crl** [comment]
Closing this as we've already addressed the issue.
