### ISSUE TITLE
kv: node tag not set for follower "raft application" spans

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#65840]
When enabling tracing to a collector, you can see the raft application spans on all the replicas. However, the ones on the followers don't have the `node` tag set.

![image](https://user-images.githubusercontent.com/16544120/119997422-93ba9900-bf84-11eb-8d0e-e1ecbf2ff97f.png)

Jira issue: CRDB-7770

**Comment by erikgrinaker** [comment]
These are originally set here:

https://github.com/cockroachdb/cockroach/blob/9f9848f5a4aa7063a21b606ddf87e2c743359a28/pkg/server/server.go#L2152

https://github.com/cockroachdb/cockroach/blob/5ee25dea0d03f4ef43338e593d1645f5a0d18000/pkg/kv/kvserver/store.go#L3684

https://github.com/cockroachdb/cockroach/blob/61852fcf5cda1adea7933f307fe092cc715665c0/pkg/kv/kvserver/replica.go#L2287

And are propagated from the various ambient contexts, e.g.:

https://github.com/cockroachdb/cockroach/blob/6dc81fd5179fe923bcc09fc8fcd8dbcadfe3c962/pkg/server/config.go#L309

https://github.com/cockroachdb/cockroach/blob/5ee25dea0d03f4ef43338e593d1645f5a0d18000/pkg/kv/kvserver/store.go#L1884

https://github.com/cockroachdb/cockroach/blob/a69d0ea23211bad7c9332522d99e17cce4c48b06/pkg/kv/kvserver/replica_init.go#L135

I see that the log tags are already present in the log event, so we'll probably just have to map them onto the trace tags when we construct the command contexts on followers.

**Comment by erikgrinaker** [comment]
@RaduBerinde Do you have a concrete repro? I'm not getting the follower application spans in traces of a simple `INSERT` even when manually disabling early acks. However, if I set up a Jaeger collector then I can find the raft application spans separately from the main trace, and these do include the node/store tags:

<img width="1182" alt="Screenshot 2023-06-25 at 13 01 14" src="https://github.com/cockroachdb/cockroach/assets/644420/28229006-c2f1-4c97-b561-7fdddac6ec21">

**Comment by erikgrinaker** [comment]
Oops, I just saw that this was from 2021! I'm going to close this one out then, as it likely doesn't apply anymore.
