### ISSUE TITLE
Commit-to-delivery time metrics

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#65846]
This was requested by a user.

Right now there is no way to measure the commit-to-delivery time for CDC. This metric gives users an idea of CDC latency, and can help debug issues and tune parameters.

What we would need to do:
- On ack from sink, calculate the MVCC timestamp - delivery time of message to the sink
- Log this metric 
- Create a histogram in the db console

Epic CRDB-2365

Jira issue: CRDB-7773

**Comment by amruss** [comment]
Considerations:
We might not know the received time - so a good approximation might be round trip time / 2
- this would count the time kafka takes to injest, replicate, etc in our latency - that is outside of our control (and this metric would likely be interpreted as "all on us") 

Unless you have updated timestamp option - we might not have commit timestamp
Batching would affect this
This would be cluster wide and not per changefeed

**Comment by miretskiy** [comment]
Commit to emit latency is being reported by changefeeds.
