### ISSUE TITLE
Graceful drain sleeps drain_wait repeatedly, which eats into the (precious) time available to transfer all ranges leases before SIGTERM is sent

### ISSUE THREAD

**Issue by joshimhoff** [cockroachdb/cockroach#65842]
**Describe the problem**
In short: Graceful drain (e.g. initiated by sending SIGTERM to CRDB) sleeps `server.shutdown.drain_wait` not a single time but multiple times, which eats into the (precious) time available to transfer all ranges leases before SIGKILL is sent, but doesn't deliver value, as the first sleep should (must) be sufficient to deregister drained nodes from LBs (this is the point of `server.shutdown.drain_wait`). This contributes to difficulties transferring all range leases off a node before SIGKILL is sent, which causes small blips in availability at CRDB update time.

In more detail now, with CC specific details to illustrate the problem concretely:
- Graceful drain is implemented by repeatedly calling a drain RPC, and not stopping until either graceful drain is done or SIGTERM is sent. 
- The drain RPC sleeps `server.shutdown.drain_wait`, then does SQL conn / query draining, then transfers range leases.
- `server.shutdown.drain_wait` is set to zero seconds by default, but in cloud environments it can take on order of 25s for LBs to remove nodes from the LBs. In CC, we set `server.shutdown.drain_wait` to 25s.
- Given that after sending SIGTERM in CC we wait 1m before sending SIGKILL (we will likely push this up to ~5m), this means we spend 50s of that 60s sleeping and we do max two iterations of lease transfer.
- Given this, we may not have enough time to transfer all leases, esp. on larger clusters.

Tho we can push time between SIGTERM and SIGKILL to ~5m, the problem remains: First of all, there is value in keeping time between SIGTERM and SIGKILL relatively low as pushing it up implies a longer runtime of the overall op, which means more time in a mixed version state, etc. Due to the multiple sleeps, we sleep unnecessarily long limiting how quickly we can transfer away all leases / how likely we are to complete a graceful drain before SIGKILL time. Lastly, the current behavior is simply confusing; it is easy to shoot yourself in the foot by increasing `server.shutdown.drain_wait` and not realizing that it reduces time available for range lease transfer.

**To Reproduce**
Set `server.shutdown.drain_wait` to 25s and send SIGTERM to CRDB. 

**Expected behavior**
I think there are various solutions to the problem:

1. The easiest is to not sleep `server.shutdown.drain_wait` on later calls to the drain RPC, as suggested by @knz.
2. @andreimatei suggests a streaming RPC, so we don't need to loop calls to the drain RPC to report status.

**Additional data / screenshots**
Here is some detail from @knz:

We have a drain RPC, which does the following:
1. drain SQL clients
2. drain distSQL flows/processors
3. drain SQL leases
4. attempts to transfer all range leases away
5. reports progress on step a-d through logs and a “Work done” field in the RPC response

In the cockroach start top-level logic upon SIGTERM, as well as cockroach node drain, as well as cockroach quit (which is now obsolete/removed), we call the Drain RPC repeatedly until the “work done” field is zero.

How much time does one single Drain RPC call take?

The first time: The SQL/distSQL/SQL lease drain take the most time, the time discussed earlier: at most drain_wait + query_wait (SQL clients) + query_wait (distsql flows) + epsilon (SQL table leases) + lease_transfer_wait (first round of lease transfers)
Note, we’re waiting query_wait two times consecutively.

Every time after that: Until “work done” is zero, at most drain_wait + lease_transfer_wait  (the SQL draining has completed already in the first drain call, and its latency is reduced to zero; only the lagging lease transfers remain to do).

**Additional context**
CC has range lease transfer issues, which I am still getting a handle on.

gz#8424

**Comment by knz** [comment]
We're going to work on this next.
This will be Nancy's starter project (I will do technical guidance)

**Comment by joshimhoff** [comment]
Quick Q: Could the range lease transfer start right when SIGTERM is sent? That is, we do the KV range lease transfer stuff concurrently with the SQL side stuff including the *initial* `server.shutdown.drain_wait` sleep? I'm not sure if there is some actual dependency between SQL drain and KV range lease transfer or if the implementation does the two steps serially just for simplicity's sake. I'm also not sure if my suggestion increases implementation complexity given the current state or else is pretty straight. But I wanted to ask.

**Comment by knz** [comment]
conceptually yes, but what do you win with this?

my thoughts:

- it's likely to make it harder for the last few sql queries to terminate properly by creating concurrent extra background activity on top
- leases are going to come back because of the sql activity

**Comment by knz** [comment]
conceptually, yes
