### ISSUE TITLE
modify column ordinal position

### ISSUE THREAD

**Issue by equiclouds** [cockroachdb/cockroach#65879]
MySQL and TiDB offer alter column ... after ... to modify column ordinal position.

MSSQL offer a gui tool to modify column position by recreate table automatically.

Can cockroach do this thing by a better way?

**Comment by kernfeld-cockroach** [comment]
This question was also [raised on our forum](https://forum.cockroachlabs.com/t/reset-column-ordinal-position/4590); let's pursue the discussion over there!
