### ISSUE TITLE
stability: snapshots causing memory issues

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6589]
The `gamma` cluster is currently experiencing frequent (every few minutes) kills by the OOM killer.
Most of the Go memory is taken up by snapshots, about 30-50 of which get triggered repeatedly.

After digging further with @tschottdorf, we found the following:
* snapshots are triggered repeatedly for the same ranges. Failures may be due to very long-running snapshots (up to 15s when starting up, down to 5s on the second round, probably due to the block caching, <1s when the block cache is allowed to use 1/4 of system memory)
* there are at least three copies of snapshot data, in `ChunkAllocator.NewChunk`, `RaftSnapshotData.Marshal` and `grpc.Encode`. see heap profile: 
[heap.pdf](https://github.com/cockroachdb/cockroach/files/255739/heap.pdf)

Some of these may be easily fixable, some not so much. Some options:
* rate-limit snapshots, either by limiting the concurrent ones, or actual rates. We need to be careful to include not just computing the snapshots, but sending them over the wire as well
* stream snapshots. This may help reduce grpc memory overhead.
* better handling of slow snapshots, and fewer retries

@bdarnell may have other ideas as well.

**Comment by tamird** [comment]
Lots of improvements in this area: #6632, #6878, #7299.

More fine-grained rate limiting of snapshots is #7307.
Streaming snapshots is #7551.

Going to close this, but please reopen if you think there's value.
