### ISSUE TITLE
bulk: import jobs often fail with server sent GOAWAY and closed the connection

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#65926]
Time and again we have seen our roachtests fail with:
`gs://cockroach-fixtures/tpce-csv/customers=2000000/746/NewsItem.txt?AUTH=implicit: http2: server sent GOAWAY and closed the connection; LastStreamID=1, ErrCode=NO_ERROR, debug="server_shutting_down"`

While this is an infra flake and the only solution is to retry the import, maybe we should be retrying internally so as to not fail the job. This retry could either be at the job resumer level or could be marked as a retriable error in our external storage resuming reader implementations. Either way, the focus of this issue should be to find what error type is bubbled up in such scenarios so that we can intercept and consider it retriable. 

Epic: CRDB-2556

**Comment by ajwerner** [comment]
cc @stevendanna who has been thinking a bit about retry policies for cdc sinks (one of which is gcs).

**Comment by adityamaru** [comment]
We're waiting on the google SDK to internally retry on seeing a GOAWAY error - https://github.com/googleapis/google-cloud-go/pull/4226. We should then bump the SDK version to include this fix.

**Comment by knz** [comment]
Reopening this as a tracking issue. The GOAWAY fix cannot be used yet, see #68158.

**Comment by adityamaru** [comment]
Should be closed by https://github.com/cockroachdb/cockroach/pull/68650.
