### ISSUE TITLE
ui: jobs remaining time wraps at 100 hours

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#65939]
<img width="1318" alt="Screen Shot 2021-06-01 at 12 58 33 PM" src="https://user-images.githubusercontent.com/5438456/120363763-85e57a80-c2da-11eb-80e5-9f536df5f0f7.png">

This `daily_market` table was hovering around 98-99 hours, and then dropped to 1 hour and is now up to 5 hours, but still has the least progress of all jobs. I think this means that we are wrapping at 100 hours.

cc @thtruo

**Comment by thtruo** [comment]
Thanks for the heads up @nvanbenschoten - do you mind sharing instructions or repro steps for us to run the same jobs?

**Comment by nvanbenschoten** [comment]
Unfortunately, this is a very large job on an expensive cluster. So trying to reproduce directly is probably not a good use of time or money. My suggestion for if you want to reproduce this would be to mock out some jobs state so that a job is given an estimate that exceeds 100 hours.

**Comment by thtruo** [comment]
Ack, noted - thanks Nathan!
