### ISSUE TITLE
streaming: add ability to verify data integrity between source and destination

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#65937]
**Describe the problem**

As an operator, I want a way to check that the data in the cluster that acts as the destination of a replication stream matches the data that is being replicated from the source.

We believe we have a few targets here:

1) A tool that can verify the latest very of every key in a tenant's span.  The initial version of this tool only needs to support relatively small scale tenant on the order of gigabytes of data. (#83316)

2) Extending the tool in (1) to work for larger dataset.  This version should produce a result for extremely large tenant's but can still be very slow.

3) A tool that provides verification similar to (1) and (2) that can run quickly enough that a user might depend on it to make a decision during a disaster recovery event. 

Epic CRDB-7077
Jira issue: CRDB-7807

**Comment by rail** [comment]
Manually synced with Jira
