### ISSUE TITLE
admission control: support for multi-tenant environments

### ISSUE THREAD

**Issue by sumeerbhola** [cockroachdb/cockroach#65954]
The framework in the admission package is general enough to support admission control for multi-tenant KV nodes and single-tenant SQL nodes, however we need:
- [x] proper integration for multi-tenant settings, including creation of the appropriate RequestGranter, and calls to admission.WorkQueue with the correct parameters (like the tenant-id).
- [x] testing that this works as expected in multi-tenant environments.
- [ ] #79425

Epic: CRDB-10304

Jira issue: CRDB-7811

**Comment by cucaroach** [comment]
Just to expand on this I think what's wanted here is a simple kv95 style roachtest that runs a weak kvserver and hits it hard with high concurrency sql tenants and we measure success as a reasonable amount of fairness in how throughput and latency varies amongst the pods.

**Comment by sumeerbhola** [comment]
Latency may be noisy, but throughput should be roughly equal. I suggest a single node cluster to reduce noise. There can be two tests:
- kv95 with small block size that stresses CPU and not the store write capacity.
- kv0 with large block size that stresses the store.

The former should equalize slots across tenants and the latter equalize tokens. We'll probably need enough concurrency per tenant to drive the corresponding resource to saturation, and a small number of tenants (say 4).

**Comment by vy-ton** [comment]
Should this be closed now that admission control is enabled for KV pods? https://github.com/cockroachdb/cockroach/issues/79425 tracks work to enable admission control for SQL pods.

**Comment by mgartner** [comment]
Yes, closing.
