### ISSUE TITLE
sql: explain analyze regions only show scan regions (and not kv data regions)

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#65985]
I’m looking at the new explain analyze (it shows regions) and was confused by these results as I expected the explain analyze to show europe-west for this data:
```SQL
demo@127.0.0.1:26257/movr> explain analyze SELECT * FROM rides WHERE id = '00118c33-925d-4326-8d32-129881ae3a6d';
                                                                                                                    info
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  planning time: 1ms
  execution time: 2ms
  distribution: local
  vectorized: true
  rows read from KV: 1 (0 B)
  cumulative time spent in KV: 2ms
  maximum memory usage: 20 KiB
  network usage: 0 B (0 messages)
  cluster regions: us-east1
  • union all
  │ cluster nodes: n1
  │ cluster regions: us-east1
  │ actual row count: 1
  │ estimated row count: 1
  │ limit: 1
  │
  ├── • scan
  │     cluster nodes: n1
  │     cluster regions: us-east1
  │     actual row count: 0
  │     KV rows read: 0
  │     KV bytes read: 0 B
  │     estimated row count: 1 (0.20% of the table; stats collected 25 seconds ago)
  │     table: rides@primary
  │     spans: [/'us-east1'/'00118c33-925d-4326-8d32-129881ae3a6d' - /'us-east1'/'00118c33-925d-4326-8d32-129881ae3a6d']
  │
  └── • scan
        cluster nodes: n1
        cluster regions: us-east1
        actual row count: 1
        KV rows read: 1
        KV bytes read: 0 B
        estimated row count: 1 (0.20% of the table; stats collected 25 seconds ago)
        table: rides@primary
        spans: [/'europe-west1'/'00118c33-925d-4326-8d32-129881ae3a6d' - /'europe-west1'/'00118c33-925d-4326-8d32-129881ae3a6d'] [/'us-west1'/'00118c33-925d-4326-8d32-129881ae3a6d' - /'us-west1'/'00118c33-925d-4326-8d32-129881ae3a6d']
(36 rows)
Time: 4ms total (execution 4ms / network 0ms)
```
To prove that this is regional by row partitioned data we can pull the `crdb_region` information:
```SQL
demo@127.0.0.1:26257/movr> SELECT *, crdb_region FROM rides WHERE ID='00118c33-925d-4326-8d32-129881ae3a6d';
                   id                  | city | vehicle_city | rider_id | vehicle_id | start_address | end_address | start_time | end_time | revenue | crdb_region
---------------------------------------+------+--------------+----------+------------+---------------+-------------+------------+----------+---------+---------------
  00118c33-925d-4326-8d32-129881ae3a6d | NULL | NULL         | NULL     | NULL       | NULL          | NULL        | NULL       | NULL     |   12.25 | europe-west1
(1 row)
Time: 2ms total (execution 2ms / network 0ms)
```
I asked @rytaft about this and she shared a bit more detail:

> It does show Europe west, but I think I understand why this might be a bit confusing. You can probably recognize from the plan that this is a locality optimized scan, which checks the local region, us-east1 first, doesn't find the row there (actual row count: 0), so then checks the remote regions and finds the row there (actual row count: 1). The spans show that the first scan touches data in us-east1 (spans: [/'us-east1'/'00118c33-925d-4326-8d32-129881ae3a6d' - /'us-east1'/'00118c33-925d-4326-8d32-129881ae3a6d']), while the second scan touches data in europe-west1 and us-west1 (spans: [/'europe-west1'/'00118c33-925d-4326-8d32-129881ae3a6d' - /'europe-west1'/'00118c33-925d-4326-8d32-129881ae3a6d'] [/'us-west1'/'00118c33-925d-4326-8d32-129881ae3a6d' - /'us-west1'/'00118c33-925d-4326-8d32-129881ae3a6d']). But if you didn't know that the spans in the second scan touched data on a remote machine you wouldn't be able to tell that from the EXPLAIN ANALYZE. EXPLAIN ANALYZE (DISTSQL) should give you a hint since the execution time for the second scan would be larger (50-100ms), but you'll still see all scans on node n1 in us-east1. This is because the scans are executed on n1, but they are relying on the kv layer to fetch data from remote nodes. If the scans were actually executed on the remote nodes, the locality optimized search optimization wouldn't work, since the DistSQL planner would have to communicate with the remote nodes to set up the flow there.

We want the locally optimized search for performance but this display above can leaves us in a confusing place because it appears to a naive user we found the data in us east even though its partitioned in Europe via a regional by row table. We think it would helpful to have some visibility into where data was found by the kv layer. Perhaps the regions could be extended to show regions the data is scanning from and receiving data from? Perhaps we need another field for kv regions? 

cc @maryliag and @kevin-v-ngo for discussion 

Jira issue: CRDB-7823

Epic CRDB-20388

**Comment by awoods187** [comment]
To repro:
```SQL
./cockroach demo movr --nodes 9
ALTER DATABASE movr PRIMARY REGION "us-east1";
ALTER DATABASE movr ADD REGION "us-west1";
ALTER DATABASE movr ADD REGION "europe-west1";
ALTER TABLE rides ALTER PRIMARY KEY USING COLUMNS (id asc);
ALTER TABLE rides ALTER COLUMN city DROP NOT NULL;
DROP INDEX rides@rides_city_id_key cascade;
ALTER TABLE rides SET LOCALITY REGIONAL BY ROW;
INSERT INTO rides (id, crdb_region, revenue) VALUES ('00118c33-925d-4326-8d32-129881ae3a6d','europe-west1', '12.25');
```

**Comment by maryliag** [comment]
We have an issue open about this: https://github.com/cockroachdb/cockroach/issues/65695
We can combine the extra explanation you added here to that one (or vice-versa) and close one of the issues

**Comment by maryliag** [comment]
No longer a priority
