### ISSUE TITLE
Improve cockroach debug compact output

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/cockroach#65998]
I used the `cockroach debug compact` tool to help a customer recover from the case where their L0 had blown up and produced unacceptable read-amplification.  It would be nice if the offline compaction tool would print out when it has been able to drain any given level.  We were, however, able to use the `cockroach debug pebble lsm` tool to understand when we could bring the node back online with a clean L0.

**Comment by mufeez-amjad** [comment]
Fixed with the change introduced in https://github.com/cockroachdb/cockroach/pull/66551.
