### ISSUE TITLE
kv: introduce cluster setting for maximum lock wait-queue depth

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#66017]
The [lock-table](https://github.com/cockroachdb/cockroach/blob/84499c94c01b86dc50be03e927fc0e2ff1cd3d69/pkg/kv/kvserver/concurrency/concurrency_control.go#L431)'s [wait-queues](https://github.com/cockroachdb/cockroach/blob/84499c94c01b86dc50be03e927fc0e2ff1cd3d69/pkg/kv/kvserver/concurrency/lock_table.go#L735) currently have no limit on the number of writers that can be queued on a given key. This can lead to unbounded queueing and diminishing quality of service for all writers as the queues build up. This is especially bad with high replication latency in multi-region clusters, as locks are held for the duration of a consensus replication round.

We should introduce a cluster setting that, when configured, limits the size that a single queue (`lockWaitQueue.queuedWriters.Len()`) can grow to before it begins rejecting new requests. If a request attempts to enter a queue that is already at this size limit, the request will be immediately rejected.

----

NOTE: Admission control and quality-of-service are deep topics and this issue doesn't attempt to provide a complete solution for them. Instead, it attempts to provide a limited, coarse-grained solution that we know will help serve as a release valve in various "hot key" scenarios.

A related item that this issue is not discussing is the queueing policy for these lock wait-queues. These queues are currently [FIFO with a few caveats](https://github.com/cockroachdb/cockroach/blob/84499c94c01b86dc50be03e927fc0e2ff1cd3d69/pkg/kv/kvserver/concurrency/concurrency_control.go#L60). This provides fairness, but also leads to quality of service degradation for all as queues grow. Furthermore, this leads to starvation when requests have a timeout that fires before any single request can get to the head of the queue. A LIFO queueing policy would help with this, though at the expense of fairness.

Alternatively, we could maintain fairness while avoiding starvation by introducing a dynamic maximum lock wait-queue depth based on request timeout duration. Given a request's maximum wait time before being canceled and the expected processing time of each item in the queue, we should be able to determine an optimal maximum wait-queue depth.

cc. @sumeerbhola. I'm going to try to prototype something here this Friday. Do we have an error type that we plan to use for request rejections?

**Comment by sumeerbhola** [comment]
> Do we have an error type that we plan to use for request rejections?

There isn't one. The admission control work so far is not doing any "fast rejection" -- it is queueing in the `admission.WorkQueue` until the deadline expires or the request is admitted.

> This can lead to unbounded queueing and diminishing quality of service for all writers as the queues build up. This is especially bad with high replication latency in multi-region clusters, as locks are held for the duration of a consensus replication round.

- Is there a current benchmark where we can observe this behavior?
- Is the worry here that the queueing causes excessive memory usage at a node due to high fan-in from large numbers of other nodes in the cluster to certain hot keys? I can't think of any other reason since this request can't go elsewhere and see a shorter queue. We already handle deadline expiry in `lockTableWaiter.WaitOn`, so an expired request should not affect the latency of other requests behind it.
- Will the caller retry after some backoff?

> Alternatively, we could maintain fairness while avoiding starvation by introducing a dynamic maximum lock wait-queue depth based on request timeout duration. Given a request's maximum wait time before being canceled and the expected processing time of each item in the queue, we should be able to determine an optimal maximum wait-queue depth.

This seems complicated. And doesn't necessarily solve the memory usage problem.

**Comment by nvanbenschoten** [comment]
> There isn't one. The admission control work so far is not doing any "fast rejection" -- it is queueing in the admission.WorkQueue until the deadline expires or the request is admitted.

Are there plans to explore fast rejection in the future? I saw mention of "hard rejection" in one of the design docs, but it doesn't seem to be a focus. I know admission control work is multifaceted, so I'm guessing our focus is primarily around "protecting the system while continuing to service all load" and not yet around "making sure to provide good service to some fraction of load". Is that an accurate understanding?

> Is there a current benchmark where we can observe this behavior?

Yes, the easiest way to observe this is to run UPDATE statements on a single key with increasing replication latency and increasing concurrency. YCSB-A can get most of the way there. Because each transaction serializes above Raft, we know that replication latency places an upper bound on throughput per key (`qps = 1s/consensus_latency`). So then because maximum throughput is fixed, increasing concurrency directly increases average latency. In other words, the queue is processed at a constant rate, so more waiters leads to a longer queue.

> Is the worry here that the queueing causes excessive memory usage at a node due to high fan-in from large numbers of other nodes in the cluster to certain hot keys? I can't think of any other reason since this request can't go elsewhere and see a shorter queue. We already handle deadline expiry in lockTableWaiter.WaitOn, so an expired request should not affect the latency of other requests behind it.

The worry isn't excessive memory usage, though this may be a secondary concern.

The worry is that under this kind of load, QoS degrades indefinitely for all clients. Worse, deadlines don't help here, because everyone ends up hitting their deadline before they make it to the head of the queue _and_ complete their write. So either latency growth is unbounded (assuming unbounded concurrency) without a timeout or throughput eventually drops to 0 with a timeout. Either way, no one is getting good service.

> Will the caller retry after some backoff?

No, these rejections will be pushed all the way back through the application.

**Comment by nvanbenschoten** [comment]
I put together a prototype in https://github.com/cockroachdb/cockroach/pull/66146 that demonstrates the intended behavior of this change.

**Comment by sumeerbhola** [comment]
> Are there plans to explore fast rejection in the future?

Eventually yes.

> I saw mention of "hard rejection" in one of the design docs, but it doesn't seem to be a focus. I know admission control work is multifaceted, so I'm guessing our focus is primarily around "protecting the system while continuing to service all load" and not yet around "making sure to provide good service to some fraction of load". Is that an accurate understanding?

Correct.

> The worry is that under this kind of load, QoS degrades indefinitely for all clients. Worse, deadlines don't help here, because everyone ends up hitting their deadline before they make it to the head of the queue and complete their write. So either latency growth is unbounded (assuming unbounded concurrency) without a timeout or throughput eventually drops to 0 with a timeout. Either way, no one is getting good service.
No, these rejections will be pushed all the way back through the application.

If there is no closed loop limiting the number of outstanding requests, we'll still have a decreasing fraction of arbitrary requests that do succeed. And when there are multiple requests per transaction, the likelihood of a single transaction not seeing any errors will become even lower. I'm just trying to make sure I understand the practical situation motivating this issue -- is it the discussion in https://cockroachdb.zendesk.com/agent/tickets/8385? It seems if we could do read-modify-write in the KV layer we could potentially halve the contention (I am assuming the reads are using SFU in that discussion). In that case would these become 1PC transactions with no locking?

**Comment by nvanbenschoten** [comment]
> I'm just trying to make sure I understand the practical situation motivating this issue -- is it the discussion in https://cockroachdb.zendesk.com/agent/tickets/8385? 

Yes, that's the issue this is in relation to.

> It seems if we could do read-modify-write in the KV layer we could potentially halve the contention (I am assuming the reads are using SFU in that discussion). In that case would these become 1PC transactions with no locking?

You're thinking along the right lines, but the unreplicated locks aren't actually the root of the problem here. The problem is that even 1PC transactions that have no prior read locks still hold latches across distributed consensus because they evaluate before Raft. This means that we'd still serialize writes above Raft and so we'd still have the same general queuing problem (what http://dbmsmusings.blogspot.com/2019/01/its-time-to-move-on-from-two-phase.html calls the "cloggage problem"). To push past this point, we'd need to turn the UPDATE into an atomic read-modify-write KV operation _and push this entire operation through Raft_ so that it gets sequenced relative to other UPDATEs before evaluating. This is not something we've ever been able to do, especially after the [proposer-evaluated KV refactor]( https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20160420_proposer_evaluated_kv.md).

**Comment by sumeerbhola** [comment]
(I'm getting close to wrapping my head around this, but still have some questions left)

I am assuming customers running in this fashion don't truly have unbounded concurrency and that they have some feedback loop to drive the system to maximum throughput e.g. exponential backoff and retry. Have we explored using latency instead of errors in that feedback loop, i.e., decrease concurrency if latency crosses a threshold (coupled with not using transaction timeouts)? The use of errors is the more classic approach, and has its origins in TCP congestion control, with typically smaller hardware queues, and isn't necessarily the only option.

> To push past this point, we'd need to turn the UPDATE into an atomic read-modify-write KV operation and push this entire operation through Raft so that it gets sequenced relative to other UPDATEs before evaluating. This is not something we've ever been able to do, especially after the proposer-evaluated KV refactor.

This is interesting. Are we seeing a limited number of such patterns that could use more sophisticated state machine operations? If we could be very judicious in expanding state machine operations beyond applying a Pebble batch, we should be able to avoid the risk of replica divergence. If we did that I can imagine that for single request 1PC transactions we could do a form of batch apply and commit: when the previous batch commits, we look in the lock table queue and find a queue of waiting requests. We grab all these requests, check the preconditions for eval (these preconditions would be very limited, like type checking or existence of the value currently in the state machine, and would ensure that success on these preconditions implies replication==commit), and for the successful ones, batch them up into a sequence of state machine operations and submit for replication. This would adapt to changes in contention by building larger batches when there is contention. And since these are 1PC, each txn is ok with seeing the effect of the previous one in the batch, since they are committing together. 

We'd need to arrange for the latching to be such that these requests are able to queue up in the lock table while the previous batch is holding latches. We could do something like:
optimistic latching followed by pessimistic locking. And if get lock reservation wait for latches before evaluation. If don't get lock reservation release latches, and continue waiting in the lock table. Evaluation of the batch would acquire a write latch on behalf of everything in the batch and an unreplicated exclusive lock (to make others queue).

**Comment by nvanbenschoten** [comment]
> I am assuming customers running in this fashion don't truly have unbounded concurrency and that they have some feedback loop to drive the system to maximum throughput e.g. exponential backoff and retry.

Right, the customers don't have truly unbounded concurrency. Their preferred approach is either to (1) push the throttle message back up their call graph all the way to their frontend, or if that's not possible (2) backoff retry with increasing delay. 

The main motivation here is to protect from abuse of the infrastructure. So they don't want heavy lock contention to kill the database. Beyond that, there is a secondary goal of preserving quality of service at some level. Here's a snippet from a recent conversation.
> goals in priority order are: (1) make sure the db doesn't die, at all costs, (2) preserve QoS for whatever number of requests we can serve with normal performance. once #1 is assured, #2 should ideally look like a step function: if your request is lucky enough to make it in the gate there's almost no noticeable impact on latency, else you get rejected

----

> Have we explored using latency instead of errors in that feedback loop, i.e., decrease concurrency if latency crosses a threshold (coupled with not using transaction timeouts)? The use of errors is the more classic approach, and has its origins in TCP congestion control, with typically smaller hardware queues, and isn't necessarily the only option.

Decreasing concurrency at which level? In the application? This would effectively shift the queueing up into the application level, right? It sounds like a strategy along these lines has been used by this customer in other systems to manage resource contention and I do think they would be open to this kind of feedback loop, but it sounds like they'd like to start with simpler protection like this limit before pushing complexity into their app.

----

> This is interesting. Are we seeing a limited number of such patterns that could use more sophisticated state machine operations? If we could be very judicious in expanding state machine operations beyond applying a Pebble batch, we should be able to avoid the risk of replica divergence. If we did that I can imagine that for single request 1PC transactions we could do a form of batch apply and commit: when the previous batch commits, we look in the lock table queue and find a queue of waiting requests. We grab all these requests, check the preconditions for eval (these preconditions would be very limited, like type checking or existence of the value currently in the state machine, and would ensure that success on these preconditions implies replication==commit), and for the successful ones, batch them up into a sequence of state machine operations and submit for replication. This would adapt to changes in contention by building larger batches when there is contention. And since these are 1PC, each txn is ok with seeing the effect of the previous one in the batch, since they are committing together.

> We'd need to arrange for the latching to be such that these requests are able to queue up in the lock table while the previous batch is holding latches. We could do something like:
optimistic latching followed by pessimistic locking. And if get lock reservation wait for latches before evaluation. If don't get lock reservation release latches, and continue waiting in the lock table. Evaluation of the batch would acquire a write latch on behalf of everything in the batch and an unreplicated exclusive lock (to make others queue).

It sounds to me like you're describing two different schemes, both of which could be used to break through this cloggage problem and push past the per-key throughput ceiling, given a fixed consensus latency.

The first relates to "expanding state machine operations" to a larger set of possible actions, "beyond applying a Pebble batch". For instance, if we could push a compare-and-swap operation through Raft and we could translate certain UPDATE statements to a single compare-and-swap operation then we could potentially push an entire 1PC txn that performed only a single CAS operation through Raft without holding latches. But this does go counter to the [proposer-evaluated KV refactor]( https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20160420_proposer_evaluated_kv.md), which deliberately restricted the state machine operations to avoid perceived complexity in supporting a rich set of state machine operations that would all need to remain permanently deterministic, even as the system evolved.

The second scheme would be less of a lift. It involves coalescing a set of single-batch txns above Raft, computing their aggregate effect on the state machine, and then pushing them all through Raft as a single combined WriteBatch. I like the point you make about a scheme like this naturally adapting to contention, because increased contention would result in larger batches of requests being pushed through consensus together. The scheme would also adapt to varying consensus latency for the same reason. I think there is a world where this makes a lot of sense.

However, the big blocker I see to either of these schemes is that `UPDATE` statements today are not single-batch txns. Instead, a (simple) `UPDATE` results in a pair of requests: `{Get(locking)}`, `{Put, EndTxn}`. This is because the KV API is not rich enough to express the logic necessary to evaluate the transformation needed between an UPDATE's initial row fetch and its row mutations. If it were, then we could package an entire UPDATE up in a single KV batch and we wouldn't even need locks, just latches. That alone still wouldn't solve the cloggage problem here, but it allow these kinds of schemes to solve the problem, at least for very specific types of operations.
