### ISSUE TITLE
sql: add metric for SQL connection latency

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#66014]
We have metrics for number of SQL connections. It would be useful to also have observability on the latency of creating new SQL connections. Past incidents and customer debugging sessions have shown that this is an area worth measuring.

The metric should capture the duration from the time that CRDB receives the connection up until when it is ready to serve a SQL query. Specifically, it should include the time it takes to authenticate.

proposed name/metadata for this metric:

```
	MetaConnLatency = metric.Metadata{
		Name:        "sql.conn.latency",
		Help:        "Latency to establish a SQL connection",
		Measurement: "Nanoseconds",
		Unit:        metric.Unit_NANOSECONDS,
	}
```

**Comment by mikecaat** [comment]
Hi,  

Can I take this issue though I'm a beginner at CRDB and go lang?

Regards,
