### ISSUE TITLE
sql: vectorize COALESCE expressions

### ISSUE THREAD

**Issue by michae2** [cockroachdb/cockroach#66015]
Continuing the campaign to vectorize all expressions, it would be great to have a vectorized implementation of `CoalesceExpr`. Here's a demonstration:

```
demo@127.0.0.1:26257/movr> EXPLAIN (VERBOSE) SELECT COALESCE(vehicle_city, start_address, end_address) FROM rides;
                                        info
-------------------------------------------------------------------------------------
  distribution: full
  vectorized: true

  • render
  │ columns: ("coalesce")
  │ estimated row count: 500
  │ render coalesce: COALESCE(vehicle_city, start_address, end_address)
  │
  └── • scan
        columns: (vehicle_city, start_address, end_address)
        estimated row count: 500 (100% of the table; stats collected 2 minutes ago)
        table: rides@primary
        spans: FULL SCAN
(13 rows)

Time: 1ms total (execution 1ms / network 0ms)

demo@127.0.0.1:26257/movr> EXPLAIN (VEC, VERBOSE) SELECT COALESCE(vehicle_city, start_address, end_address) FROM rides;
                   info
-------------------------------------------
  │
  └ Node 1
    └ *colflow.BatchFlowCoordinator
      └ *colexec.Columnarizer
        └ *rowexec.noopProcessor
          └ *colexec.Materializer
            └ *colexecutils.CancelChecker
              └ *colfetcher.ColBatchScan
(8 rows)

Time: 1ms total (execution 1ms / network 0ms)
```

If we had a vectorized `CoalesceExpr` we wouldn't need the wrapped `rowexec.noopProcessor`.

Jira issue: CRDB-7850

**Comment by jlevesy** [comment]
Hello, just so you know: I'm still working on this, though I'm having a hard time figuring out how everything works 😅.

So far:

- I guess I have a test that should validate a basic case, my goal is to make it pass before bothering you too much 😅.
- I've laid out a basic a basic execution planing logic for `*tree.CoalesceExpr` , that plans for each sub expression, stores the gathered ops and result indexes and pass them down to the `coalesceProjOp`.
- Now I'm focusing on implementing the operator, so far I managed to dump the first tuple... I guess!.

If you have some time, feel free to look at [my working branch](https://github.com/cockroachdb/cockroach/compare/master...jlevesy:66015/vectorize-coalesce-expressions?expand=1)

**Comment by yuzefovich** [comment]
You definitely seem to be on the right track! If you're looking for some additional tips, please say more what's difficult to understand, etc.

In terms of how `coalesce` operator should work, it'll be something like:
- get a batch of rows from the input
- all rows in the batch initially are "unprocessed"
- until each row in a batch has been processed, do:
  - for each unprocessed row `rowIdx`, see whether it has a non-NULL value in `exprIdx[i]` position
    - if it is non-NULL, then copy that value into the output vector and mark this row as "processed"
    - if it is NULL, keep `rowIdx` as "unprocessed"
  - if after going through all `exprIdx` columns there are still some unprocessed rows, then those rows will get a NULL value in the output vector.

Hope this makes sense.
