### ISSUE TITLE
New contention pages in the console: Contention on the Databases page (tables)

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#66053]
This issue tracks creating the new SQL Activity page with the contention tab (contention chart and transaction contention table). This excludes the table contention chart. 

Jira issue: CRDB-7859

**Comment by maryliag** [comment]
Is this still valid? Do we still want this Contention tab now that we have the insights page?

cc @kevin-v-ngo @Annebirzin
