### ISSUE TITLE
New page in the DB console: SQL Activity

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#66052]
This issue tracks creating the new SQL Activity page with metrics, sessions, transactions, and statements tabs. 

Epic: CRDB-9226

**Comment by Annebirzin** [comment]
Dropping designs for the SQL Activity tab here for reference: https://www.figma.com/file/fxuZ93cyKmeAbC8pxGXQyk/21.2_SQL-obsrv_query-contention?node-id=1502%3A43000

**Comment by maryliag** [comment]
Page added to both DB and CC Console
