### ISSUE TITLE
sql: add regression test for casting correctness bug

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#66067]
A logical correctness bug was introduce in https://github.com/cockroachdb/cockroach/commit/200d1db58e5f6b47ad0b8637a0eec45e31851dd0. The bug was inadvertently fixed in https://github.com/cockroachdb/cockroach/commit/3a31d880076a8dfe7f7799483bbad0637ee27339.

@yuzefovich explained the bug:

> in this case we have VARCHAR(40), but the vectorized engine simply produces STRING, so we need to perform the cast. we currently don’t support natively any casts between string-like types in the vectorized engine, so we had to fallback to the row engine. SQLStandardName doesn’t produce VARCHAR(40) for expected

The affected versions were 21.1.0 and 21.1.1. The issue is fixed in version 21.1.2.

We should add a regression test for the bug, even though it's already been fixed.

This logictest shows the bug clearly:

```
statement ok
CREATE TABLE t66067_a (
  a INT,
  c CHAR(26),
  CONSTRAINT c UNIQUE (c)
);
CREATE TABLE t66067_b (
  a INT,
  v VARCHAR(40)
);
INSERT INTO t66067_a VALUES (1, 'foo');
INSERT INTO t66067_b VALUES (1, 'bar');

query ITIT
SELECT * FROM t66067_b b
INNER JOIN t66067_a a ON b.a = a.a
WHERE b.v = 'bar' AND a.c = 'foo'
----
1  bar  1  foo

query ITIT
SELECT * FROM t66067_b b
INNER LOOKUP JOIN t66067_a a ON b.a = a.a
WHERE b.v = 'bar' AND a.c = 'foo'
----
```

**Comment by mgartner** [comment]
@ianjevans because this bug was inadvertently fixed, there was no release note in a commit mentioning the bug fix. Is there a way that we can manually add a release note for 21.1.2. Something like:

> Release note (bug fix): A bug has been fixed that caused incorrect results for queries where CHAR and VARCHAR columns are filtered by constant string values.

@yuzefovich Does this release note sound ok? I'm not sure the blast radius of this bug. I was only able to reproduce in a lookup join, but nothing about the buggy code was lookup join specific, as far as I can tell.

**Comment by yuzefovich** [comment]
Thanks Marcus! This sounds good, I'd only mention explicitly that only 21.1 versions before 21.1.2 are affected (i.e. the bug isn't present on 20.2.x).

**Comment by mgartner** [comment]
> Release note (bug fix): A bug has been fixed that caused incorrect results for queries where CHAR and VARCHAR columns are filtered by constant string values. The bug was present since version 21.1.0.
