### ISSUE TITLE
cluster-ui: metrics pages scrolls/jumps on their own

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#66093]
I was testing on master, which was 085b05d69f at the time, using Safari 14.

When I scroll further down the the new metrics pages and start to inspect a graph, within a few seconds the page jumps back up, close to (but not all the way to) the top. It seems to happen on different pages, with different time-selectors, etc.

Epic CRDB-8038

**Comment by matthewtodd** [comment]
Taking a quick look at this as I was working nearby on #65856, I added some dumb `console.log` statements: we're falling into [the else branch here](https://github.com/cockroachdb/cockroach/blob/a4517515b1f3460b2deff68e24b40b6d72bc818f/pkg/ui/src/views/cluster/components/linegraph/index.tsx#L475-L508) and destroying the uPlot object every time we get new properties.
