### ISSUE TITLE
kv: ranges with leaseholder preferences applied don't lease transfer cleanly during graceful drain

### ISSUE THREAD

**Issue by joshimhoff** [cockroachdb/cockroach#66103]
**Describe the problem**

Ranges with leaseholder preferences applied don't lease transfer cleanly during graceful drain. The impact is that graceful restart of nodes holding leases of ranges with leaseholder preferences applied is not totally graceful. There may be a short blip in availability when the node is eventually killed (as in some production envs (k8s self-hosted + CC) there is a timeout on how long graceful drain is waited for (after N seconds SIGKILL is sent)).

**To Reproduce**

All nodes running `v21.1.1`:

```
$ cockroach version
Build Tag:        v21.1.1
Build Time:       2021/05/24 15:00:00
Distribution:     CCL
Platform:         darwin amd64 (x86_64-apple-darwin19)
Go Version:       go1.15.11
C Compiler:       Clang 10.0.0 
Build Commit ID:  f6630b3f524f3a5e52b330220037af01369b1ff2
Build Type:       release
```

n1 started with `cockroach start --insecure --listen-addr=localhost --logtostderr --locality dc=test --join=localhost:26257,localhost:26258,localhost:26259`.

n2 started with `cockroach start  --join=localhost:26257,localhost:26258,localhost:26259 --listen-addr localhost:26258 --insecure --http-addr localhost:8081 --logtostderr`.

n3 started with `cockroach start --join --join=localhost:26257,localhost:26258,localhost:26259 --listen-addr localhost:26259 --insecure --http-addr localhost:8082 --logtostderr`.

Create table with leaseholder preference like this:

```
root@:26257/defaultdb> create database test;
CREATE DATABASE

Time: 150ms total (execution 150ms / network 0ms)

root@:26257/defaultdb> use test;
SET

Time: 41ms total (execution 41ms / network 0ms)

root@:26257/test> CREATE TABLE kv (
        k STRING PRIMARY KEY,
        v STRING);
CREATE TABLE
root@:26257/test> ALTER TABLE kv CONFIGURE ZONE USING lease_preferences = '[[+dc=test]]', constraints = '{+dc=test: 1}', num_replicas =3;
CONFIGURE ZONE 1

Time: 103ms total (execution 103ms / network 0ms
```

Send SIGTERM to n1. Logs show:

```
I210604 21:00:12.826634 2508 1@server/drain.go:157 ⋮ [server drain process] 571  drain remaining: 1
I210604 21:00:12.844215 2508 1@server/drain.go:159 ⋮ [server drain process] 572  drain details: range lease iterations: 1
I210604 21:00:13.061474 2509 1@cli/start.go:831 ⋮ [-] 573  210 running tasks
I210604 21:00:14.196713 2508 1@server/drain.go:157 ⋮ [server drain process] 575  drain remaining: 1
I210604 21:00:14.196785 2508 1@server/drain.go:159 ⋮ [server drain process] 576  drain details: range lease iterations: 1
I210604 21:00:15.674465 2508 1@server/drain.go:157 ⋮ [server drain process] 579  drain remaining: 1
I210604 21:00:15.674535 2508 1@server/drain.go:159 ⋮ [server drain process] 580  drain details: range lease iterations: 1
I210604 21:00:17.228686 2508 1@server/drain.go:157 ⋮ [server drain process] 582  drain remaining: 1
I210604 21:00:17.248249 2508 1@server/drain.go:159 ⋮ [server drain process] 583  drain details: range lease iterations: 1
I210604 21:00:17.874708 508 2@kv/kvprober/kvprober.go:216 ⋮ [n1,kvprober] 584  kv.Get(‹/Table/34›), r=30 returned success in 431µs
I210604 21:00:18.061499 2509 1@cli/start.go:831 ⋮ [-] 585  210 running tasks
I210604 21:00:18.679080 2508 1@server/drain.go:157 ⋮ [server drain process] 587  drain remaining: 1
I210604 21:00:18.698056 2508 1@server/drain.go:159 ⋮ [server drain process] 588  drain details: range lease iterations: 1
```

The drain never completes. Looks racy like the lease is transferred but then is transferred back due to the leaseholder preference:

```
root@:26258/test> select range_id, start_pretty, end_pretty, lease_holder, replicas from crdb_internal.ranges where range_id = '37';
  range_id | start_pretty | end_pretty | lease_holder | replicas
-----------+--------------+------------+--------------+-----------
        37 | /Table/53    | /Max       |            1 | {1,2,3}
(1 row)

Time: 5ms total (execution 5ms / network 0ms)

root@:26258/test> select range_id, start_pretty, end_pretty, lease_holder, replicas from crdb_internal.ranges where range_id = '37';
  range_id | start_pretty | end_pretty | lease_holder | replicas
-----------+--------------+------------+--------------+-----------
        37 | /Table/53    | /Max       |            2 | {1,2,3}
(1 row)

Time: 124ms total (execution 124ms / network 0ms)

root@:26258/test> select range_id, start_pretty, end_pretty, lease_holder, replicas from crdb_internal.ranges where range_id = '37';
  range_id | start_pretty | end_pretty | lease_holder | replicas
-----------+--------------+------------+--------------+-----------
        37 | /Table/53    | /Max       |            1 | {1,2,3}
(1 row)

Time: 5ms total (execution 5ms / network 0ms)
```

If you run the following command, the drain immediately finishes:

```
root@:26258/test> ALTER TABLE kv CONFIGURE ZONE DISCARD;
CONFIGURE ZONE 1

Time: 99ms total (execution 99ms / network 0ms)
```

**Expected behavior**
SIGTERM would lead to graceful drain of all range leases held by the node.

**Comment by joshimhoff** [comment]
Also, for fun, here is `kvprober` detecting the unavailability post incomplete graceful drain:

```
$ k logs pod/cockroachdb-0 cockroachdb | grep kvprober | grep E21
E210604 19:09:45.724648 522 2@kv/kvprober/kvprober.go:210 ⋮ [n1,kvprober] 5390  kv.Get(‹/Table/54/1/3›), r=59 failed with: ‹operation "db.Get" timed out after 2s›
```

And here is a graph showing a short spike in error rate post incomplete graceful drain (happened on two node restarts so two error rate spikes):

![image](https://user-images.githubusercontent.com/1443719/121189793-71543580-c838-11eb-820a-f9a879d31474.png)

**Comment by tbg** [comment]
This should be reproducible quickly in the `kv/gracefuldraining` roachtest. We need to start n1 with an extra locality

https://github.com/cockroachdb/cockroach/blob/4e4f31a0ed1a8ea985b9ab6f72e29266b259900e/pkg/cmd/roachtest/kv.go#L402

and then set a lease_preference for it like Josh did above.

Then we also want to be a bit more explicit here

https://github.com/cockroachdb/cockroach/blob/4e4f31a0ed1a8ea985b9ab6f72e29266b259900e/pkg/cmd/roachtest/kv.go#L535

by draining first (with a generous timeout, failing if we run into the timeout) and thus being able to test that the drain process actually succeeds. Then we issue a cockroach quit and check that there isn't a dip, but we expect to reliably fail during the drain step.

**Comment by tbg** [comment]
As for the bug, when the lease is away from the preferred holder (who is draining in the above scenario), we hit the return true here:

https://github.com/cockroachdb/cockroach/blob/7495434b547ce1e832d27ebedb3e742e7a254fea/pkg/kv/kvserver/replicate_queue.go#L1391-L1394

This means that `(*replicateQueue).considerRebalance` will hit the `shedLease` path:

https://github.com/cockroachdb/cockroach/blob/7495434b547ce1e832d27ebedb3e742e7a254fea/pkg/kv/kvserver/replicate_queue.go#L1150-L1169

We then call `TransferLeaseTarget`

https://github.com/cockroachdb/cockroach/blob/7ad39c72ae06f9698a574c4864b2cb4a382245ce/pkg/kv/kvserver/allocator.go#L1246-L1255

which will look for a suitable new leaseholder and will populate `preferred` with the draining node:

https://github.com/cockroachdb/cockroach/blob/7ad39c72ae06f9698a574c4864b2cb4a382245ce/pkg/kv/kvserver/allocator.go#L1272-L1286

We then seem to return that *without checking if the preferred node is draining*

https://github.com/cockroachdb/cockroach/blob/7ad39c72ae06f9698a574c4864b2cb4a382245ce/pkg/kv/kvserver/allocator.go#L1287-L1291

as the draining check is only further down:

https://github.com/cockroachdb/cockroach/blob/7ad39c72ae06f9698a574c4864b2cb4a382245ce/pkg/kv/kvserver/allocator.go#L1301-L1302

though if I peek into that method I'm pretty sure it has no notion of whether the nodes are draining, so I don't think it can really exclude them:

https://github.com/cockroachdb/cockroach/blob/72b3636640119eb1ba1c984c85fc6a47a99cf4c8/pkg/kv/kvserver/store_pool.go#L559-L577

https://github.com/cockroachdb/cockroach/blob/72b3636640119eb1ba1c984c85fc6a47a99cf4c8/pkg/kv/kvserver/store_pool.go#L187-L204

So I would guess that we have a general problem with leases returning to draining nodes, though there may yet be some other mechanism that tends to prevent it.

**Comment by lunevalex** [comment]
@tbg great analysis `liveAndDeadReplicas` will exclude draining nodes from the live list as those map to `storeStatusUnknown` https://github.com/cockroachdb/cockroach/blob/72b3636640119eb1ba1c984c85fc6a47a99cf4c8/pkg/kv/kvserver/store_pool.go#L158 and https://github.com/cockroachdb/cockroach/blob/72b3636640119eb1ba1c984c85fc6a47a99cf4c8/pkg/kv/kvserver/store_pool.go#L230. The draining nodes will show up in neither the live nor the dead list that is returned from that function.
