### ISSUE TITLE
sql: interval division with float rounds differently from Python & PostgreSQL

### ISSUE THREAD

**Issue by timgraham** [cockroachdb/cockroach#66118]
see https://github.com/cockroachdb/cockroach/issues/66118#issuecomment-856366411 for solution

----

**Describe the problem**

Interval division with a float rounds differently from Python & PostgreSQL.

**To Reproduce**

```sql
CREATE TABLE "test1" (
    "id" serial NOT NULL PRIMARY KEY,
    "duration" interval NOT NULL
);

INSERT INTO "test1" ("duration") VALUES ('0 days 0.253000 seconds'::interval);

SELECT ("duration" / 3.2) FROM "test1";
     ?column?
-------------------
  00:00:00.079063
```

**Expected behavior**

Expected result of SELECT query: `00:00:00.079062`.

**Environment:**
 - CockroachDB version: 21.1.1 (and older versions)

**Additional context**

A Django test fails:
```
======================================================================
FAIL: test_durationfield_multiply_divide (expressions.tests.FTimeDeltaTests) (expr=3.2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/code/django/tests/expressions/tests.py", line 1565, in test_durationfield_multiply_divide
    self.assertEqual(
AssertionError: datetime.timedelta(microseconds=79063) != datetime.timedelta(microseconds=79062)
```

**Comment by kernfeld-cockroach** [comment]
I made a minimal reproduction of this discrepancy. Looks like Cockroach is somehow keeping track of more precision than Postgres, because Cockroach decides to round (0.000001 / 2) up to 0.000001, whereas Postgres treats it more like integer division, rounding (0.000001 / 2) down to 0.

Postgres:

```sql
postgres=# SELECT (INTERVAL '0.000001' / 2);
 ?column? 
----------
 00:00:00
(1 row)
```

Cockroach:

```sql
root@:26257/defaultdb> SELECT (INTERVAL '0.000001' / 2);
     ?column?
-------------------
  00:00:00.000001
(1 row)

Time: 0ms total (execution 0ms / network 0ms)
```

**Comment by rafiss** [comment]
Thanks @kernfeld-cockroach! cc @otan does anything come to mind immediately from when you last looked at INTERVAL?

**Comment by otan** [comment]
ah yes, it's because we use `Round` here: https://github.com/cockroachdb/cockroach/blob/master/pkg/util/duration/duration.go#L251

**Comment by otan** [comment]
on closer observation, the round down behaviour **only exists for division**.

as such, we need to change 

https://github.com/cockroachdb/cockroach/blob/16e72f3209d16147d1e3f58ff38ff15270f65331/pkg/util/duration/duration.go#L619

to round *down* nanos before `rounded` is called.

then we should change the test cases here:

https://github.com/cockroachdb/cockroach/blob/16e72f3209d16147d1e3f58ff38ff15270f65331/pkg/util/duration/duration_test.go#L461-L501

to include these test values.

**Comment by TszKitLo40** [comment]
@otan  I am new here. Can I try this issue? I think maybe I can try this issue by following the instructions listed by you.

**Comment by otan** [comment]
Go for it!

**Comment by TszKitLo40** [comment]
@otan I have ran the command `make testbaselogic FILES='interval' TESTFLAGS='-rewrite'` you mentioned, but the following error is returned. How can I fix it?

**Comment by otan** [comment]
this means the table "test1" does not exist. did you create something that references test1? what code did you add to the file?

**Comment by TszKitLo40** [comment]
I have filed a PR for this issue. @otan PTAL

**Comment by kernfeld-cockroach** [comment]
@TszKitLo40 thanks for the quick fix!!
