### ISSUE TITLE
sql: join with USING condition does not include all the output columns

### ISSUE THREAD

**Issue by godofdream** [cockroachdb/cockroach#66123]
**Describe the problem**

There is a rare constelation during which the column defined in a join is missing in the to_jsonb result

**To Reproduce**

```
CREATE TABLE  products (
    product_name TEXT,
    PRIMARY KEY (product_name)
);
CREATE TABLE  offers (
    offer_id TEXT,
    product_name TEXT,
    PRIMARY KEY (offer_id)
);
SELECT to_jsonb(products.*) as product , jsonb_agg(to_jsonb(offers.*)) as offers
FROM products
INNER LOOKUP JOIN offers
USING (product_name)
GROUP BY products.product_name;
```
Result I'm getting from the query:
`|{"product_name": "orange"}|[{"offer_id": "best orange"}]|`

**Expected behavior**
`|{"product_name": "orange"}|[{"offer_id": "best orange", "product_name": "orange"}]|`

**Environment:**
 - CockroachDB version 21.1.1
 - Server OS: Ubuntu 20.04
 - Client app `cockroach sql`

**Comment by rafiss** [comment]
Thanks for this report! It seems like a bug with the `USING` join condition. Also, it looks like v20.2 is affected too.

Here's a simpler repro:

```
-- Setup
CREATE TABLE  products (
    product_name TEXT,
    PRIMARY KEY (product_name)
);
CREATE TABLE  offers (
    offer_id TEXT,
    product_name TEXT,
    PRIMARY KEY (offer_id)
);
insert into offers values ('best orange', 'orange');
insert into products values ('orange');
```

```
-- Repro
> SELECT products.* , offers.*
 FROM products
 INNER  JOIN offers
 USING (product_name);

  product_name |  offer_id
---------------+--------------
  orange       | best orange```
```

Writing out the join condition differently works correctly
```
> SELECT to_jsonb(products.*) , to_jsonb(offers.*)
 FROM products
 INNER  JOIN offers on products.product_name = offers.product_name;;
           to_jsonb          |                       to_jsonb
-----------------------------+--------------------------------------------------------
  {"product_name": "orange"} | {"offer_id": "best orange", "product_name": "orange"}
```

cc @rytaft -- could your team look into this more for further triage?

**Comment by godofdream** [comment]
I can confirm switching from `JOIN USING` to `JOIN ON` fixes the issue for me.

**Comment by RaduBerinde** [comment]
It's even worse with outer joins:
```
SELECT products.* , offers.*
 FROM products
 FULL JOIN offers
 USING (product_name);
```

The NATURAL and USING versions return a merged column by default. I believe we also return the other columns (as hidden; see `usingJoinBuilder.addRemainingCols`), but I'm guessing that hidden columns don't get tuple-expanded (and changing that would likely break other things).

@godofdream Note that if you refer to the columns directly instead of using `*`, this works fine. Avoiding `*` is a good idea in general because it makes the queries more stable if the schema changes.

**Comment by RaduBerinde** [comment]
Specifically, for the original example:
```
SELECT
  json_build_object('product_name', products.product_name) AS product,
  jsonb_agg(json_build_object('offer_id', offers.offer_id, 'product_name', offers.product_name)) AS offers
FROM products
INNER JOIN offers
USING (product_name)
GROUP BY products.product_name;
```

**Comment by RaduBerinde** [comment]
> The NATURAL and USING versions return a merged column by default. I believe we also return the other columns (as hidden; see usingJoinBuilder.addRemainingCols), but I'm guessing that hidden columns don't get tuple-expanded (and changing that would likely break other things).

Dealing with these columns is tricky - they should not be part of the unqualified `*` expansion, but they should be part of a qualified `<table_name>.*` expansion. Seems like we would need something more complicated than `cat.Visibility` to track this. I'll put this on my plate to work on when I have some time.

**Comment by godofdream** [comment]
@RaduBerinde Thank you for the hint, for normal Querries I use the fields, but in this case I'm using Json, and I want it as flexible as possible.
