### ISSUE TITLE
windows client can not reconnect to server

### ISSUE THREAD

**Issue by carr123** [cockroachdb/cockroach#66125]
both windows and linux are version V21.1.1

I use cockroachdb windows version as SQL client to access cockroachdb linux server cluster.
eg. cockroach sql --certs-dir=D:\certs --host=192.168.1.111:26257

when i leave for a while, the TCP connection may disconnected. 
and the command line prompt become this:   root@192.168.1.111 :26257/? ?>
and i could not issue more sql commands, it can not reconnect. telling the connection is broken,
I have to close the sql client and reopen it to fix the disconnection bug.

I don't see the "? ?" on earlier version of cockroachdb(v19.2 ) when the console is idle and disconnected.
yes, on earlier cockroachdb version, the sql client can reconnect to the db server itself.

Jira issue: CRDB-7893

**Comment by kernfeld-cockroach** [comment]
@vy-ton is the CLI currently supposed to automatically reconnect, or would a user need to manually close and restart it?

**Comment by carr123** [comment]
i expect CLI can automatically reconnect, but now it not.  when i issue SQL commands, it repeatly reports disconnect error

**Comment by rafiss** [comment]
I'm going to close this since it seems like an old issue. If it's still an issue, please leave a comment. For us to be able to best help, please leave instructions for how to reliably reproduce the problem (if that's possible).
