### ISSUE TITLE
Cannot cast $1, $2 etc. to regclass

### ISSUE THREAD

**Issue by jawj** [cockroachdb/cockroach#66127]
**Describe the problem**

While investigating compatibility with TypeScript Postgres library [Zapatos](https://jawj.github.io/zapatos/), I found that Zapatos is not able to generate a schema using Cockroach DB because query parameters cannot be cast to `regclass`.

**To reproduce**

As a minimal case, create a table `books` (with any columns and column types), then run this TypeScript/JavaScript:

```typescript
import * as pg from 'pg';

const
  connectionString = process.env.DB_URL,
  pool = new pg.Pool({ connectionString });

(async () => {
  const a = await pool.query(`SELECT '"public"."books"'::regclass`);
  console.log('a', a);
  const b = await pool.query(`SELECT $1::regclass`, ['"public"."books"']);
  console.log('b', b);
})();
```

Output:

```
a Result {
  command: 'SELECT',
  rowCount: 1,
  /* etc */
}
(node:41052) UnhandledPromiseRejectionWarning: error: error in argument for $1: type with ID 4294869501 does not exist
    at Parser.parseErrorMessage (/Users/george/Development/zapatos-demo/node_modules/pg-protocol/src/parser.ts:357:11)
    /* etc */
```

**Expected behavior**

I expected the second query to return the same result as the first query, casting the literal string to `regclass` (this is what Postgres does). Instead, it throws an error.

**Environment:**

Server version: CockroachDB CCL v20.2.10 (x86_64-unknown-linux-gnu, built 2021/05/17 17:32:35, go1.13.14) (same version as client)

**Additional context**

The actual cast to `regclass` in Zapatos occurs in the function [columnsForRelation](https://github.com/jawj/zapatos/blob/970d1cf5215e1847617f2f73bae8d43ca77ff6dd/src/generate/tables.ts#L45).

Zapatos cannot be used with CockroachDB unless this is fixed or an appropriate workaround is found.

**Comment by otan** [comment]
hmm, `4294869501` is suspicious -- that's a system based typeid it is trying to resolve.

and i can't replicate this with the shell:

```
demo@127.0.0.1:26257/defaultdb> prepare bob as select $1::regclass;
PREPARE

Time: 0ms total (execution 0ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> create table books ();
CREATE TABLE

Time: 4ms total (execution 4ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> execute bob('"public"."books"'::regclass);
  regclass
------------
  books
(1 row)

Time: 2ms total (execution 2ms / network 0ms)

demo@127.0.0.1:26257/defaultdb>
```

so zapatos must be doing some interesting introspection. have we looked at this ORM before @vy-ton?

**Comment by jawj** [comment]
Thanks for the quick reply. 

I probably should have mentioned the context for this, which is retrieving `COMMENT ON COLUMN` values from `pg_catalog.pg_description`.

Anyway, I've realised I can work around this in Zapatos by rewriting the query to eliminate the `::regclass` cast (plus the rewritten query feels nicer, and less hacky). So hopefully Zapatos will be fully compatible with CockroachDB in a few minutes, once I've released 4.0.2.

And please do take a look at [Zapatos](https://jawj.github.io/zapatos/). I wrote it out of frustration with both Sequelize and TypeORM, and I think it's worked out very nicely. It's less of an ORM, and more of a library for working type-safely with SQL queries. Perhaps you could feature it [alongside them](https://www.cockroachlabs.com/docs/v21.1/install-client-drivers.html?filters=js-ts)?

**Comment by vy-ton** [comment]
> Zapatos will be fully compatible with CockroachDB in a few minutes, once I've released 4.0.2 is now fully compatible with CockroachDB

Product Manager at Cockroach Labs here. This is awesome!

We now have a dedicated page for [community-developed tooling](https://www.cockroachlabs.com/docs/v21.1/community-tooling.html). Please feel free to open a PR to link Zapatos and CockroachDB information.

**Comment by vy-ton** [comment]
> do we expect the zapatos / pg driver to work @vy-ton 

`pg` driver should work beyond the incompatibilities identified from failed nightly tests

**Comment by rafiss** [comment]
@otan it may be related to this issue https://github.com/cockroachdb/cockroach/issues/64140 

This PR might have improved things https://github.com/cockroachdb/cockroach/pull/65151 -- it should be in 20.2.11.

**Comment by otan** [comment]
It's not fixed on master tho...

**Comment by rafiss** [comment]
It seems like this isn't repro-ing and there was a workaround, so I'll close this. Please comment if there's still an issue.
