### ISSUE TITLE
sql: EXPLAIN incorrectly performs the effects of data-modifying statements

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#6613]
`EXPLAIN DELETE FROM t` actually deletes records. That's not right.

Explanation: currently `EXPLAIN` calls `planNode.Start()` because the query plan is only fully built after Start() is called. However some nodes (including, but not limited to, DELETE) also start sending KV operations during Start(). 
Since EXPLAIN must have a plan ready to show, the solution is to move KV operations away from Start(), or alternatively introduce a new method "BuildPlan()" which prepares the plan without sending KV operations. Preliminary discussions about this with @nvanbenschoten suggest we may want to peruse the latter solution.

**Comment by knz** [comment]
Thanks to @RaduBerinde for finding this!

**Comment by RaduBerinde** [comment]
In what specific cases do we change the plan inside `Start()`? This doesn't seem right to me as a general semantic. Even a separate `BuildPlan()` function seems off, as we are calling it against a plan node that supposedly is already part of a plan tree.

**Comment by knz** [comment]
The point is not that we "change" the plan inside Start(). The point is that the makePlan() recursion does *not* build the query plan fully, because that's not its role. 

And we should not derail the discussion by wondering whether makePlan() should build the plan instead of Start(), for example arguing that it's what its name stands for. 

The real underlying problem is that the makePlan() interface is not well designed, it has too much responsibility. There are really 6 semantic phases on SQL statements:

1. structural syntax checking
2. gathering the table descriptors and resolving qualified names
3. type inference and type checking
4. normalization and substituting placeholders with actual values
5. building the query plan, including index selection.
6. running the query plan.

the pgwire Prepare phase needs to do steps 1-3 only.
the EXPLAIN statement needs to do steps 1-5 only.

Our current makePlan interface does steps 1-5 in one go. This *is* too much.
Our current Start() interface re-does steps 2 to 5 again, and also does step 6 for some statements. This *may* be too much.

What I propose:

- a constructor that will "replace" makePlan() (or rename it), e.g. "analyzeStatement()" does steps 1 to 3 only.
- a new method BuildPlan() does steps 4 and 5 only.
- Start() starts step 6.

**Comment by knz** [comment]
@petermattis I'd be interested on your perspective on the comment above.

**Comment by nvanbenschoten** [comment]
> There are really 6 semantic phases on SQL statements

I have been running into the issue of course grained planning phases as well, and I think it makes a lot of sense to break planning and execution into more targeted stages exposed through the `planNode` interface. One of the primary reasons for this is that (as @knz touched upon) the current phases do not work as expected recursively over the entire plan tree. For instance, when beginning phase 4 in a root `planNode`, it would simplify a lot of logic to have the precondition that all child nodes in the tree (subqueries, etc.) have already also completed phase 3. By making these phases explicit and specific in the `planNode` interface, we could make these kind of guarantees, and also clean up the parent-child interface between `planNodes` for each specific phase (see the `desiredTypes` parameter on planNode constructors as an artifact of this course grained relationship).

**Comment by RaduBerinde** [comment]
The distinction between `makePlan` and `Start()` (or the proposed `BuildPlan()`) is not about naming - `Start()` is part of the `planNode` interface which is functionality that can be run against nodes that are **part of a plan**. That is the part I find iffy - there must be some kind of "intermediary" plan for us to be able to even run `Start()` and that intermediary plan is not defined anywhere AFAICT. The comments for `makePlan` do not document any of this and don't even mention `Start`.

If we have a clear definition about what the plan tree returned by `makePlan` is (and on which we run `BuildPlan()`) then I think this would be ok.

This is why I am asking about the specific cases we currently have where `Start()` changes the plan tree (I looked around for a bit and couldn't find them). It would help clarify what is (at least currently) the structural difference between the "pre-Start" and the "post-Start" plans. (By structural difference I mean changes to the structure of the `planNode` tree, not changes that happen inside the nodes).

**Comment by knz** [comment]
So all the nodes that use SelectClause currently (namely delete, insert, update, select) will expand sub-queries and thus change the plan tree upon Start().

**Comment by RaduBerinde** [comment]
Got it. So to be specific to the proposal you made - if we want to split steps 4 and 5 into a `planNode` method, then there has to be a step 3.5 (part of what `analyzeStatement` does) which builds some kind of "intermediary" plan tree. As long as we properly document what that plan is exactly, this sounds great to me.

**Comment by knz** [comment]
I'm currently taking the following direction: https://github.com/knz/cockroach/commit/6f2348012e653fe55fa4bdbe4d5abeefdc3efbd5 -- it does not work but if you have comments/suggestions I'll take them.
