### ISSUE TITLE
bazel: mirror repositories, downloaded artifacts during the bazel build

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#66163]
During the Bazel build we download code and other artifacts from various sources. The build process shouldn't hit any endpoints that we don't control. Enumerate all the artifacts that a build downloads and ensure everything is mirrored on sources owned by CRDB.

Epic CRDB-8351

**Comment by rail** [comment]
After taking a look at https://docs.bazel.build/versions/main/external.html I can see a couple of approaches here:

0. We should stop using `git_repository` and `replace it with `http_archive`. Something like [this](https://gist.githubusercontent.com/rail/418307790e625aeb80cf9a8bc26bcc02/raw) should handle this (also need to address 1 vendored package).

1. Mirror all the tarballs somehow. Publish them somewhere "in the cloud". Update all `http_archive.urls` entries and add the mirrored URL to the beginning of the list or replace the existing entries with ours. The approach is explicit (good!), but will require an extra step to every dep update (need to publish to our mirror).

2. Use a transparent proxy by setting `HTTPS_PROXY/HTTP_PROXY` env vars. We can even block other external connections, except this host. This will require a dedicated proxy (?) to fetch and cache the artifacts.

**Comment by rickystewart** [comment]
Don't forget all the stuff in `DEPS.bzl` -- the [`go_repository`](https://github.com/bazelbuild/bazel-gazelle/blob/master/repository.rst#go_repository) declarations.

**Comment by rail** [comment]
Good point. Looks like `go_repository` also supports fetching via http(s).

**Comment by rail** [comment]
>     2. Mirror all the tarballs somehow. Publish them somewhere "in the cloud". Update all `http_archive.urls` entries and add the mirrored URL to the beginning of the list or replace the existing entries with ours. The approach is explicit (good!), but will require an extra step to every dep update (need to publish to our mirror).

Maybe we should an extra CI step to check if a PR introduces new dependencies and let TeamCity fetch and upload them before we start all the builds.

Another approach would be having an extra step to pre-populate the bazel cache directory (on agents) before we start builds/tests and use `--nofetch` to enforce offline builds.

**Comment by rickystewart** [comment]
> Maybe we should an extra CI step to check if a PR introduces new dependencies and let TeamCity fetch and upload them before we start all the builds.

Doing this automatically is probably fraught with peril, and maybe a source of security vulnerabilities? At places I've worked at before there's generally a process that people follow to mirror dependencies they want to add. This also gives an opportunity to review new dependencies whereas that usually gets ignored in PR's.

**Comment by rickystewart** [comment]
This is done save for some follow-up work that I'll file shortly.
