### ISSUE TITLE
sql: crdb_internal.unsafe_upsert_descriptor should be easier to use

### ISSUE THREAD

**Issue by postamar** [cockroachdb/cockroach#66187]
We have these nice descriptor surgery functions like `crdb_internal.unsafe_upsert_descriptor` which are nice but a few months ago I added a bunch of safety checks which in practice make it really hard to use. For instance we have to manually bump the version counter and fiddle about with modification time timestamps for it to not fail some validation check. This stuff should be handled automatically somehow.

The simplest solution would be to make `crdb_internal.unsafe_upsert_descriptor` more liberal in what it accepts. Alternatively we could add a mode switch to that function to operate in either _strict_ or _relaxed_ mode, defaulting to strict. I'm not too sure what's best.

**Comment by ajwerner** [comment]
We are not going to do this because we made some recipes in our runbooks.
