### ISSUE TITLE
roachtest: outputs corrupt TeamCity markers

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#66182]
```
[06:50:30]
[Step 2/3] ##teamcity[testStarted name='cancel/tpch/distsql/queries=[7 9 20 21]
[06:50:32]
[Step 2/3] Error while parsing TeamCity service message: Value should end with "'". Valid service message has a form of "##teamcity[messageName name1='escaped_value' name2='escaped_value']" where escaped_value uses substitutions: '->|', [->|[, ]->|], |->||, newline->|n
[06:50:30]
[Step 2/3] ,nodes=3' flowId='cancel/tpch/distsql/queries=[7 9 20 21],nodes=3']
```

https://github.com/cockroachdb/cockroach/blob/7ad39e6af943a9d4deca9ee767d786af0f23163b/pkg/cmd/roachtest/test_runner.go#L609-L611

and some others are not using

https://github.com/cockroachdb/cockroach/blob/334968badb9e8d7818d535fef4cc1fc4b1612791/pkg/cmd/roachtest/test.go#L477-L493

but they should.

**Comment by tbg** [comment]
@cockroachdb/sql-queries in the short term, could you change the test name to print the queries like `7,9,20,21`?

**Comment by tbg** [comment]
Re-open to track the permanent fix.

**Comment by cucaroach** [comment]
@tbg what's envisioned for a permanent fix?   Should the testRegistry validate the test names and throw an error or should it escape them?   Or something else...

**Comment by tbg** [comment]
It's probably a good idea to validate them in the registry. While we could "just" escape things properly, the test names also make it onto the filesystem and that's bound to cause problems, at no real benefit. `[a-zA-Z0-9-_]` ought to be enough :-)

**Comment by cucaroach** [comment]
That would not allow Yahor's name w/ commas.   What if we run the test name through teamCityEscape and if it comes back untouched we're good but if its changed throw an error and ask for name to be cleaned up?    Do we really want to allow slashes in the name?  Won't that cause problems on the filesystem?

**Comment by tbg** [comment]
A comma is fine too.

The slashes, yeah, I wouldn't chose that now, but they already are part of pretty much all existing test names, and help organize the artifacts into subdirs. We shouldn't have to change any existing tests (except that one triggering the issue) as there is lots of fallout in doing so (like, it wrecks our perf pipeline).

The idea of passing through teamcityEscape is good but I like an explicit allowlist (the regexp) better, where the allowlist is unaffected by teamcityEscape. There are few TC escapes and lots of funky things would still hit the filesystem and cause issues there. We can do both to be sure.

The id
