### ISSUE TITLE
Cockroach Docker walkthrough is broken

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#662]
* we need to pass `-init_and_start` (btw, that looks ugly with the underscores, and redundant since the flag is really only used with `init`. Why do we have both `start` and `init` anyways? Could just have `start` and merge the current behavior into `--bootstrap` and `--bootstrap-only` flags.

* `./cockroach put a 2` is now broken because it's trying to POST to the empty host. It should probably default to localhost (or to whatever the RPC server determines its hostname is). We had issues with stuff like this before.

We should find a way to make sure that the client examples we give work at all times, i.e. by somehow adding them to the test suite.

**Comment by spencerkimball** [comment]
-init_and_start follows our other multi-word flags, which all use underscores. Should we change to dashes?

I see the point that init is confusing and we do want this to be as simple as humanly possible. Hmmm. I like the idea of -bootstrap and -bootstrap-only flags. Will address these in a PR.

@petermattis could we have an example unittest for main.go which actually uses the compiled binary itself to run the example code? That way, the example code will be available working and verbatim in godoc.

**Comment by petermattis** [comment]
I don't think example code can use the compiled binary. At least, I don't know how to make that work. Did you have something specific in mind?

**Comment by tschottdorf** [comment]
Sounds like it's not going to work smoothly. Maybe we should instead make sure that whenever we catch such things, the `server/cli` tests get updated. For example, in the test we should initialize the `TestServer`'s context from the command line flags (so that we get the actual defaults), changing only what is necessary for the tests. Currently we're setting `ts.Addr = "127.0.0.1:0` manually, where we'd preferably use `:0` to stay close to the defaults, and then I'd expect to see the same error in the cli tests already.
