### ISSUE TITLE
sql: clarify locality optimized search checks the local region first via EXPLAIN/EXPLAIN ANALYZE

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#66211]
Localitly optimized search first checks the local region, before fanning out to check the other regions in parallel:

For example:
```SQL
explain analyze (distsql) SELECT * FROM child INNER JOIN parent ON p_id = c_p_id WHERE c_id = 10;
````
<img width="1316" alt="Screen Shot 2021-06-08 at 3 28 40 PM" src="https://user-images.githubusercontent.com/22278911/121268200-7d1d1780-c88b-11eb-85ba-a839681a984d.png">

However, it is hard to tell that via EXPLAIN/EXPLAIN ANALYZE that the local region is checked first, and the other work may not be necessary. We could add `locality optimized search`, we could add something that says `optional check in other regions` or something else like it. Thoughts @Annebirzin @maryliag @kevin-v-ngo ?  cc @rytaft 

To repro:
```SQL
CREATE DATABASE db PRIMARY REGION "us-east1" REGIONS "us-west1", "europe-west1";
use db;
CREATE TABLE parent (
  p_id INT PRIMARY KEY,
  FAMILY (p_id)
) LOCALITY REGIONAL BY ROW;
CREATE TABLE child (
  c_id INT PRIMARY KEY,
  c_p_id INT REFERENCES parent (p_id),
  INDEX (c_p_id),
  FAMILY (c_id, c_p_id)
) LOCALITY REGIONAL BY ROW;
INSERT INTO parent (crdb_region, p_id)
VALUES ('europe-west1', 10), ('us-west1', 20), ('us-east1', 30);
INSERT INTO child (crdb_region, c_id, c_p_id)
VALUES ('europe-west1', 10, 10), ('us-west1', 20, 20), ('us-east1', 30, 30);
```

Epic CRDB-9025

Jira issue: CRDB-7934

**Comment by jordanlewis** [comment]
Going to put this into the backlog for now, since it's possible for people to understand what's going on here with the current data: the `UNION ALL` has a `LIMIT 1`, which causes the `UNION ALL` to avoid starting the second scan if it gets any data back from the first scan.

**Comment by awoods187** [comment]
@kevin-v-ngo can you work with @ianjevans to provide documentation on this if we won't be updating the display this release? Its causing confusion for folks internally and externally

**Comment by kevin-v-ngo** [comment]
Sounds good Andy! Please cc me as you see folks reporting this issue.
