### ISSUE TITLE
Surface live query statistics - V1

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#66217]
Users have little visibility into the state of an active running query. This issue tracks the ability for a user to view run-time execution statistics such as elapsed time, operator progress, and the number of rows processed including the selected execution plan. 

More details are outlined in the following epic.

Epic: CRDB-9224

Jira issue: CRDB-7939

**Comment by xinhaoz** [comment]
Active Queries V1 PRs:

- [x] [Create common UI components and active query pages for db-console] (https://github.com/cockroachdb/cockroach/pull/76753)
- [x] [Create active query page components in cluster-ui for use in CC](https://github.com/cockroachdb/cockroach/pull/77504)
- [ ] Bump cluster-ui version to export new components
- [ ] [Add pages for CC in `managed-service` repo](https://github.com/cockroachlabs/managed-service/pull/8165)
