### ISSUE TITLE
sql: UPSERT & ON CONFLICT DO UPDATE do not support RETURNING

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#6637]
`UPSERT INTO kv VALUES (10, 10) RETURNING *` currently errors with `RETURNING is not supported with UPSERT` but should return `10, 10`

**Comment by tamird** [comment]
Ran into this when trying to `INSERT INTO ... ON CONFLICT DO NOTHING RETURNING id`. Can we give this a bump?

**Comment by cuongdo** [comment]
This looks like it'll be needed for Sequelize, which provides an `upsert` method that needs access to the upserted row(s) for its return value.

**Comment by novabyte** [comment]
We've just crashed into this issue with our implementation of dynamic leaderboards in the game server https://github.com/heroiclabs/nakama/pull/43. Is there a timeline on when this will work?

**Comment by danhhz** [comment]
Some context:

This wasn't done at the same time as the original UPSERT work because the internal `planNode` interface requires that `Values` be available after each call to `Next`, but UPSERT batches the work for performance. `planNode`'s interface could be changed, but that would be a big refactor. Or, the UPSERT batching could be disabled for `ON CONFLICT... RETURNING`, but I expect that this would be a big performance hit and quite surprising to users.

Unfortunately, I personally am unlikely to have time to fix this before 1.0 unless someone thinks of a better third option.

@novabyte how easily can you work around this being unimplemented? cc @petermattis in case he has anything to add

**Comment by novabyte** [comment]
@danhhz The only workaround we have which we'll have to do to complete the feature this week is do a read after write. It's two KV operations at the storage engine level but as you can imagine leaderboards are a pretty core and heavily utilised game mechanic in almost every game type.

**Comment by knz** [comment]
@danhhz it doesn't matter that the work is batched in principle; the rows of RETURNING output values can be accumulated in memory until the upsert node's next/values methods are called. I do not think this is a big effort, it does fit the existing execution model.

**Comment by marcuswestin** [comment]
👍

**Comment by dianasaur323** [comment]
@couchand From a user: one thing the postgres implementation does do is provide any way of returning if a row was inserted or updated. there are multiple hacks on stackoverflow which use postgres internals to return this info. it would be great if your implementation took care of this.

I'm assuming your implementation does this?

**Comment by knz** [comment]
@dianasaur323 no our current implementations (including Andrew's) do not do this. We can add a feature to achieve what the user wants but neither standard SQL nor Postgres' dialect allow this directly. If that is important please add an item to the roadmap (complexity is S)

**Comment by couchand** [comment]
I'd suggest that we not try to tackle this added functionality for 1.1, since it's not clear exactly how that should be communicated.  Instead, let's think through the problem and write up a proposal for how to handle the request, and add it to the roadmap.

**Comment by dianasaur323** [comment]
@couchand @knz If it's not standard, I think our current implementation is good enough. adding @nstewart for a final say though, since this is an area / feature he covers.
