### ISSUE TITLE
multiregionccl: add multi-region microbenchmark to ensure REGIONAL table semantics

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#66381]
**Is your feature request related to a problem? Please describe.**

We recently introduced a data-driven test framework to microbenchmark multi-region abstractions. Currently, we only use it for global tables. We should expand this to also include some tests that ensures REGIONAL table semantics are upheld as well. Specifically, I'm thinking we should ensure that REGIONAL tables can provide stale reads locally from all regions under both ZONE and REGION survival modes. We could also throw in some REGION ADD/DROPs in there too.

Epic CRDB-2541

**Comment by pawalt** [comment]
Resolved by #66735
