### ISSUE TITLE
sql: ON CONFLICT DO NOTHING for any conflict

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#6639]
Currently ON CONFLICT DO NOTHING requires that a particular index be used for conflicts. Other conflicts will still error. Postgres allows the index to be omitted, which will do nothing for any conflict.

**Comment by nvanbenschoten** [comment]
See [the TODO](https://github.com/cockroachdb/cockroach/blob/5ed6b0482664bd6813842cfa0aa46157862ddc7e/sql/insert.go#L168).

While investigating https://forum.cockroachlabs.com/t/cayley-and-cockroachdb/280/3, it became evident that Cayley has at least one use case for this functionality. If it's not a difficult change, it would be nice to support `ON CONFLICT DO NOTHING` without specifying a conflict index.

**Comment by nvanbenschoten** [comment]
See [the TODO](https://github.com/cockroachdb/cockroach/blob/5ed6b0482664bd6813842cfa0aa46157862ddc7e/sql/insert.go#L168).

While investigating https://forum.cockroachlabs.com/t/cayley-and-cockroachdb/280/3, it became evident that Cayley has at least one use case for this functionality. If it's not a difficult change, it would be nice to support `ON CONFLICT DO NOTHING` without specifying a conflict index.

**Comment by knz** [comment]
Hi @emsal1863, here's a work item that will probably take a little more time. You'll need to start by studying the mutation code at a very high level, then dive in the specifics of the logic for UPSERT/INSERT ON CONFLICT (they share an implementation), before you can make a decision about how to solve the problem at hand.

**Comment by knz** [comment]
The people who are most able to help you understand the current code are @BramGruneir, @justinj and @jordanlewis (and me).

**Comment by emsal1863** [comment]
basic plan for implementation:

* make a new upserter (call it `strictTableUpserter` maybe) 
* get all unique indexes on `init()`
* check for conflicts on any of those indexes on `atBatchEnd()` (if that’s the right place to do it) and skip all the rows where conflicts were detected
