### ISSUE TITLE
sql: embed zone configs within descriptors objects

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#66396]
Part of #66348. This will let us deprecate `system.zones`, and later provide the optimizer the cache of zone configs it needs for locality-aware planning. We'll also use embedded zone config to generate span configs for KV (#66391). We'll need to be careful around ensuring compatibility with existing backups here.

For the migration, we can first introduce a cluster version v21.1-A, which when rolled into, will disallow setting new zone configs (we'll later re-allow it after v21.1-B). We'll then recurse through all descriptors, and for each one copy over the corresponding zone config from `system.zones` into it.

Jira issue: CRDB-8024

**Comment by ajstorm** [comment]
@irfansharif curious why this issue was labeled MT.  Can you please comment?

**Comment by ajwerner** [comment]
This isn't something we have to do, and indeed there is no pressing reason to do it right now. It would be cleaner to associate this state more directly with the descriptors given we cache and write it in a correlated way. In reality, we'll probably more towards this when implementing transactional schema change. When we need to more generally encapsulate under a unified concept, this would be an important step.

**Comment by postamar** [comment]
I don't think we're going to do this. There exist other things-that-join-on-descriptors like comments, and we're going to be content to just have the descriptors collection mediate access to them.
