### ISSUE TITLE
docs: spurious diffs for redact_safe.md

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#66401]
**Describe the problem**

I'm seeing spurious diffs for `redact_safe.md`.
```
$ rm docs/generated/redact_safe.md; make docs/generated/redact_safe.md
$ git diff
diff --git i/docs/generated/redact_safe.md w/docs/generated/redact_safe.md
index ea1d855d26..05e7dce774 100644
--- i/docs/generated/redact_safe.md
+++ w/docs/generated/redact_safe.md
@@ -34,6 +34,8 @@ pkg/storage/enginepb/mvcc3.go | `MVCCStatsDelta`
 pkg/storage/enginepb/mvcc3.go | `*MVCCStats`
 pkg/util/hlc/timestamp.go | `Timestamp`
 pkg/util/hlc/timestamp.go | `ClockTimestamp`
+vendor/github.com/cockroachdb/pebble/internal/humanize/humanize.go | `FormattedString`
+docs/generated/redact_safe.md:57:vendor/github.com/cockroachdb/pebble/metrics.go:324:  // have been registered as safe with redact.RegisterSafeType and does not
 pkg/util/log/redact.go | `reflect.TypeOf(true)`
 pkg/util/log/redact.go | `reflect.TypeOf(123)`
 pkg/util/log/redact.go | `reflect.TypeOf(int8(0))`
@@ -53,3 +55,4 @@ pkg/util/log/redact.go | `reflect.TypeOf(time.Time{})`
 pkg/util/log/redact.go | `reflect.TypeOf(time.Duration(0))`
 pkg/util/log/redact.go | `reflect.TypeOf(encodingtype.T(0))`
 pkg/util/log/redact.go | `reflect.TypeOf(Channel(0))`
+vendor/github.com/cockroachdb/pebble/metrics.go:324:   // have been registered as safe with redact.RegisterSafeType and does not
```

Jira issue: CRDB-8026

**Comment by irfansharif** [comment]
Is nobody else running into this? I see this all the time.

**Comment by knz** [comment]
I have tried it and I don't see it. Maybe we can spend some time together and I'll watch over your shoulder?

**Comment by irfansharif** [comment]
Rafa and I paired on this, turns out I had a stray git config telling git to recurse into submodules for `git grep`, and we were relying on [not recursing](https://github.com/cockroachdb/cockroach/blob/162a1d4625b6ec2538cafa17218e19b09d6728ff/Makefile#L1565-L1570) when generating redact_safe.md. Rafa will send out a patch.

```
[submodule]
  recurse = true
```

**Comment by knz** [comment]
@irfansharif can you show me how to repro this?

**Comment by irfansharif** [comment]
It's not something I was able to repro, but I think given that the vendored pebble diff shows up in our generated doc is unintended? Like, how would it shown up there/why isn't it removed if we're careful about excluding the vendor directory from being considered.

**Comment by knz** [comment]
is this perhaps a side effect of using bazel to generate this file instead of the makefile?

**Comment by knz** [comment]
we've approached this in a different way in the end.
