### ISSUE TITLE
sql: new schema changer needs some implicit ordering to mimize stage uage

### ISSUE THREAD

**Issue by fqazi** [cockroachdb/cockroach#66437]
Currently, the new schema change intentionally generates stages since we need to guarantee dependencies are dropped in certain scenarios. So, for example if you have a DROP DATABASE, the database will incur an extra stage always after all the dependent objects. We can potentially clean this up if we had implicit ordering.

**Comment by ajwerner** [comment]
Notes from synchronous discussion:

Ideally the dependency edge between the end states of operations would imply the operation order. The idea is that if one node depends on another and they can be scheduled in the same phase then it still needs to be the case that the dependency is fulfilled. 

This formulation mostly turns into: if the outcome of A depends on the outcome of B (maybe indirectly) then it should happen after. If two things depend on each other (implying a swap) then the drop should come first.

The challenge is: how do you realize this partial ordering requirement in sub N^2 time? It feels like you should be able to build a tree and then walk it topologically.

**Comment by fqazi** [comment]
Resloved via https://github.com/cockroachdb/cockroach/pull/66673
