### ISSUE TITLE
cert-principal-map: support colons in cert-principal name

### ISSUE THREAD

**Issue by sheaffej** [cockroachdb/cockroach#66435]
Epic: CRDB-8030

Please consider adding support for the colon character in principal names supplied to the `--cert-principal-map` flag of `cockroach <command>`. Currently, the colon character is used to separate the cert-principal name and the db-principal name like so:

https://www.cockroachlabs.com/docs/v21.1/cockroach-start.html#security

```
--cert-principal-map cert-principal:db-principal
```

However, when the cert-principal contains colons, this fails to parse correctly.

Example with a cert-principal = `hello:hello` that should map to a db-principal = `root`
```
cockroach start <options> --cert-principal-map=hello:hello:root
ERROR: invalid <cert-principal>:<db-principal> mapping: "hello:hello:root"
Failed running "start"

# Enclose cert-principal in single quotes
cockroach start <options> --insecure --cert-principal-map='hello:hello':root
ERROR: invalid <cert-principal>:<db-principal> mapping: "hello:hello:root"
Failed running "start"

# Escape the colon in the cert-principal 
cockroach start <options> --cert-principal-map=hello\:hello:root
ERROR: invalid <cert-principal>:<db-principal> mapping: "hello:hello:root"
Failed running "start"
```

**Describe the solution you'd like**
It would be helpful to have a syntax that could be used to express, or escape cert-principal names that contain colons. And possibly other characters that are valid in a cert-principal but would be difficult to parse as a flag.

**Comment by piyush-singh** [comment]
@petermattis added this in 19.x I believe. Peter, is there an obvious way to escape colons that we did not try here? If not, would it be a large lift to add something like that? I can coordinate with Raphael on the change if this is straightforward.

**Comment by bobvawter** [comment]
Something to consider about using a backslash character to escape colons in the principal is that our escape sequence will need to be double-escaped for a shell, and possibly quadruple-escaped if the shell commands are encoded in some other document (e.g. YAML).  Various shell and/or markup quoting rules could be applied to minimize the number of times our escape character is escaped, but this kind of escape-room is not fun for all ages.

Alternate approaches:
1. Use a double-colon: `hello::hello:root`. It should be obvious to a reader already familiar with the certificate-principal naming scheme to understand what's going on. The error message could be updated to include a hint to double-up colons in the principal name.
1. Allow the certificate-principal map to be loaded from a file `--cert-principal-map=@/path/to/file` which could be as simple as a properties/INI file that has a well-defined escaping strategy.  If we allow cockroach to reload this file at runtime, it would allow folks to push updates to the mapping without having to bounce their cluster.

**Comment by petermattis** [comment]
There is currently no way to escape colons in the principal names. In addition to @bobvawter's suggestion, we could change the parsing to split on the last colon rather than all of the colons. That would make `hello:hello:root` be parsed as `hello:hello` as the cert principal and `root` as the DB principal. This is relatively easy to do (literally a few lines of code), but has the downside of not being able to specify a colon in the DB principal. Is that a reasonable limitation. I'm not sure if I prefer this or using a double-colon.

**Comment by knz** [comment]
I like Peter's idea the most, assuming that Piyush (& customer) is on board.

**Comment by bobvawter** [comment]
Based on a conversation with @sheaffej, the customer in question will have a large number of mappings that will change as they add and remove (human) users.  This would seem to push us in the direction of having a way to update the certificate mappings without restarting nodes.  Adding a column to the `system.users` table for mappings other than the `node` and `root` certs would seem like the natural approach, but I think that might not be easy to backport.  I'm leaning more towards a file-based approach in the interim, maybe just a simple json key/value mapping?

**Comment by knz** [comment]
I would recommend CSV actually, because that's a lowest common denominator that's much cheaper to get enterprise security software to emit than json.

**Comment by petermattis** [comment]
Rather than a file, could we use a setting like `server.host_based_authentication.configuration`? Or perhaps extend `server.host_based_authentication.configuration` to support principal mapping. I recall that we discovered hba.conf supports such mapping after `--cert-principal-map` was added. The setting avoids any question of how the file would get reloaded.

**Comment by knz** [comment]
> could we use a setting like server.host_based_authentication.configuration? Or perhaps extend server.host_based_authentication.configuration to support principal mapping. I recall that we discovered hba.conf supports such mapping after --cert-principal-map was added. The setting avoids any question of how the file would get reloaded.

yes we can, that is exactly the goal of this issue:  #47196   

I am very much in favor of addressing #47196, but this seems like a more involved task?

**Comment by petermattis** [comment]
> I am very much in favor of addressing #47196, but this seems like a more involved task?

Agreed. I was bringing this up as the ideal end state. If something is needed in the short term that must be backported I'd prefer the simplest option which is enhancing the behavior of the existing `--cert-principal-map` and not trying to support a file-based mapping. I'm distant from this work and the requirements, though, so consider this only my opinion.

**Comment by knz** [comment]
@sheaffej @bobvawter  can you provide some additional color on the following:

> the customer in question will have a large number of mappings

How many mappings? Please provide an order of magnitude.

**Comment by sheaffej** [comment]
@knz I expect the customer in question to have several "10s" of mappings for each cluster supporting an application. 

More color:
There are 4 types of DB users that will access a cluster using certs for auth, where the certs are created by the customer's CA that requires colons in the CNs:
- The special `node` and `root` users
- The application servers connecting to the clusters as users (aka Services)
- The DB Admin team's human users 
- The App Owner team's human users

There will be multiple clusters (initially I estimate < 10 clusters, but hopefully growing into 100s of clusters) supporting different applications across the business. I expect that a member of the DB Admin team would need to have access to most or every cluster, so every cluster would presumably have a mapping for each DB Admin team member (I estimate that team is < 10 admins today, but could double or so). Then there would be a few (let's say < 5) App Owners per cluster, then a couple (1 -3) Service users, plus the `node` and `root` special users.

**Comment by sheaffej** [comment]
Also related, maybe a different issue, but wanted to mention it in case the solution could be the same.

Each member of the DB Admin team would need to access the DB Console via OIDC. If we can use the OIDC regex to convert the cert CN to the DB Admin's user, we could use the same DB users. But if the regex parsing/conversion isn't going to work, then we'd probably need an additional set of DB users (which can be easily parsed out from the CN) for the DB Admin team when they access the DB Console via OIDC.

**Comment by knz** [comment]
@sheaffej how do they feel about using just 4 roles, and then issue separate TLS client certs to each individual? (The SQL username inside the TLS client would be the role name, and then they could identify themselves via `application_name`)

The we could have just 1 static cert-principal map with just 4 entries

**Comment by bobvawter** [comment]
Based on a conversation with @knz, I will backport the simplest change we can make, which is to split the flag on the last colon.  Then as a follow-on, work on #47196 to add support for username maps, similar to the HBA configuration.  If the customer finds the need to restart nodes to adjust the flag-based mapping untenable, we'll have the option to backport the second change (or know if it's too much of a science project to be backportable).
