### ISSUE TITLE
sql: support text() function from Postgres

### ISSUE THREAD

**Issue by jhatcher9999** [cockroachdb/cockroach#66440]
In Postgres, there is a text() function which converts numeric-based input to text.  To support Postgres compatibility, CRDB should support this function.

Note from @rafiss: Postgres actually uses this `text` function to implement casts to the TEXT type. We've started exploring the idea of using builtin functions for casts in https://github.com/cockroachdb/cockroach/pull/94859 

Jira issue: CRDB-8048

**Comment by rafiss** [comment]
closed by https://github.com/cockroachdb/cockroach/pull/97093

(will be in 23.1)
