### ISSUE TITLE
sql: "table doesn't exist" after drop and recreate

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#6644]
Tests in cockroach-python are failing with "table doesn't exist" errors. The table in question was dropped and then (successfully) recreated. Bisecting indicates that the problem was introduced with #6336. It's not trivial to isolate the problem; a simple test case that just does a create/drop/create sequence doesn't do it. 

The python tests are using multiple DB connections (one after the other, not concurrently as far as I can tell). One connection creates the table, runs some tests, drops it, and closes, then another starts and repeats the process. 

Specifically, the first connection does (via `tshark`):
```
    ...
    Query: \nDROP TABLE date_table
    Query: COMMIT
    Type: Termination
```

Then a second connection is opened and does:
```
    Type: SSL request
    Type: Startup message
    Type: Authentication request
    Query: BEGIN
    Query: SHOW TABLES
    Query: \nCREATE TABLE date_table (\n\tid INTEGER DEFAULT unique_rowid() NOT NULL, \n\tdate_data DATE, \n\tPRIMARY KEY (id)\n)\n\n
    Query: COMMIT
    Query: BEGIN
    Query: DELETE FROM date_table
```

Everything succeeds except the last `DELETE FROM`, which gets `Message: table "date_table" does not exist`

**Comment by andreimatei** [comment]
Duplicate of #5483

It's not a new problem, although the exact way to repro and the timing needed might have shifted. I have a fix out already.

Btw how do I run those tests in cockroach-python exactly?

**Comment by dt** [comment]
See also: https://github.com/cockroachdb/cockroach/pull/6381/files#diff-472c06aaf5f40f9abb24f1595039b1ecR355 which should repro in master if unskipped.

**Comment by bdarnell** [comment]
Oh, I thought the "drop is a schema change" PR had fixed that issue. 

To run the tests in cockroachdb-python, `pip install tox`, start a cockroach server in insecure mode on localhost:26257, and run `tox -e py27` (or just `tox` if you have python 3.5 installed too).

**Comment by andreimatei** [comment]
Well, that PR has fixed some issues :)
