### ISSUE TITLE
sql: support apply joins with subqueries in both "inner" and "outer" contexts

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#66447]
Once #66442 merges, we will start to error out when an apply join encounters a scenario when both the "inner" and "outer" plans have subqueries. This is a limitation of how we're propagating the results of the subqueries (via a single slice on the planner) and should be lifted. Note that we haven't had a single user report of this problem yet.

Jira issue: CRDB-8050

**Comment by v-from-meiro** [comment]
👋  (just letting you know that I am the single user who sees this problem) 😃

**Comment by yuzefovich** [comment]
@v-from-meiro thanks for the report! Can you share a reproduction? Maybe we could help you rewrite the query so that you wouldn't run into this limitation, and it might allow us to improve CRDB too.
