### ISSUE TITLE
backup: CREATE SCHEDULE for table backup does not save qualified table name

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#66450]
`CREATE DATABASE mydb; USE mydb; CREATE TABLE mytbl (id int primary key); CREATE SCHEDULE FOR BACKUP mytbl INTO 'userfile:///a' RECURRING '@hourly'`

Schedule creation does a dry run backup to see if it will work, which succeeds in this case. But then the backup fails saying the table doesn't exist. This is because the BACKUP is of `mytbl` but in the background, scheduled job session, that does not resolve to `mydb.mytbl`.

We should replace the backup that we run with the fully qualified `mydb.mytbl` name in the serialized backup command.

Epic CRDB-8816

**Comment by adityamaru** [comment]
A result of this bug was that scheduled backups with table targets might fail in older releases. Adding backport labels and a GA Blocker tag to get this into 21.2.
