### ISSUE TITLE
sql: CHECK constraints should use session syntax

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#6645]
Currently it's hard coded to `parser.ParseExprTraditional`, but should be based on the session.

**Comment by dt** [comment]
Evaluating using the client session could be confusing -- a check expr created in a session with one syntax could then render the table unusable by all clients using the other.

We should either just pick one (eg always traditional, like it is now) and document that, or store the syntax used at creation and then use that for evaluation.

**Comment by bdarnell** [comment]
The syntax switch affects lexing; i don't think we can use one syntax for the `CHECK` clause and another for the rest of the statement. If the table is created in "modern" mode can we translate the check clause to "traditional"? If not we will have to store the syntax used to create the table along with the constraint.

`DEFAULT` expressions have the same issue.

**Comment by petermattis** [comment]
Aren't CHECK constraints and DEFAULT expressions normalized to traditional syntax during creation? This happens as an artifact of parsing the expressions and then serializing them using `Expr.String()` which currently only generates traditional syntax. I'm not sure if there is a bug here.

**Comment by mjibson** [comment]
You are correct, they are normalized. You can send down modern-only syntax into the CHECK expr and it gets switched to traditional.
