### ISSUE TITLE
clusterversion,kv: remove old cluster versions corresponding to 20.2 and 21.1

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#66544]
**Is your feature request related to a problem? Please describe.**

Sub-issue of https://github.com/cockroachdb/cockroach/issues/65200 for versions that seem KV related. 

- [x] NodeMembershipStatus
- [x] AbortSpanBytes
- [x] CPutInline
- [x] ReplicaVersions
- [x] SeparatedIntents
- [x] ClosedTimestampsRaftTransport
- [x] PriorReadSummaries
- [x] NonVotingReplicas
- [ ] TruncatedAndRangeAppliedStateMigration, PostTruncatedAndRangeAppliedStateMigration

**Comment by tbg** [comment]
Going to remove blocker label, though it would be nice to do this.
