### ISSUE TITLE
clusterversion,server: remove old cluster versions corresponding to 20.2 and 21.1

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#66545]
**Is your feature request related to a problem? Please describe.**

Sub-issue of #65200 for versions that seem KV related.

- [x] NodeMembershipStatus
- [x] MinPasswordLength
- [x] HBAForNonTLS
- [x] TracingVerbosityIndependentSemantics
- [x] CreateLoginPrivilege

**Comment by knz** [comment]
fixed by #69864, #69868
