### ISSUE TITLE
sql: probably missing ordering propagation in the optbuilder around mutations

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#66570]
The following logic test will occasionally fail (once #61582 merges):
```
# LogicTest: fakedist-disk

statement ok
CREATE TABLE src (a INT, b INT);
INSERT INTO src VALUES (1, 1), (1, 2), (2, 1), (2, 2);
CREATE TABLE dest (c INT PRIMARY KEY, d INT);

query II
INSERT INTO dest SELECT a, b FROM src ORDER BY a, b ON CONFLICT DO NOTHING RETURNING c, d
----
1  1
2  1
```
because the rows are returned in the incorrect order. One can stress it (if placed into `wip` logic test file) with `make stress PKG=./pkg/sql/logictest TESTS=TestLogic//wip STRESSFLAGS='-p 1'`.

We should confirm whether such behavior (the reordering for RETURNING clause) is compatible with Postgres.

I believe the root cause is that we are not propagating the ORDER BY clause to the mutation, so it is currently expected that the rows could be returned in an arbitrary order, but this would be unintuitive for users.

----

Another interesting case is whether we want to preserve the order of rows in `VALUES` clause. The following logic test will occasionally fail too (because the second row is actually inserted):
```
# LogicTest: fakedist-disk

statement ok
CREATE TABLE t (a INT UNIQUE, b INT);
INSERT INTO t VALUES (1, 1), (1, 2) ON CONFLICT DO NOTHING;

query II rowsort
SELECT * FROM t
----
1  1
```

**Comment by mgartner** [comment]
The [documentation](https://www.postgresql.org/docs/13/sql-insert.html) states:

> If the INSERT command contains a RETURNING clause, the result will be similar to that of a SELECT statement containing the columns and values defined in the RETURNING list, computed over the row(s) inserted or updated by the command.

It makes not mention that the order of the INSERT's input is maintained, so as far as I can tell the order is not guaranteed. However Postgres's current implementation always maintains the order, according to https://stackoverflow.com/a/27996203.

I'm inclined to not guarantee this order unless we have a real-world use case that demands it, for example an ORM that depends on the order being maintained.

**Comment by rytaft** [comment]
Sounds like we are not considering this a bug? In this case, should we move this issue to the backlog or low-likelihood bucket for 21.2?

**Comment by mgartner** [comment]
I'm inclined to close this entirely. 

cc @vy-ton

**Comment by vy-ton** [comment]
> I'm inclined to not guarantee this order unless we have a real-world use case that demands it
SGTM. We should file a docs issue to call out that ordering to not preserved?

**Comment by mgartner** [comment]
> We should file a docs issue to call out that ordering to not preserved?

I don't think it's necessary to call out unless we there is feedback on this from customers. I'll close this issue for now.
