### ISSUE TITLE
storage: Raft diagnostic tools

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#6657]
It's difficult to see what's going on inside raft. As a starting point, we should build a tool (CLI or web UI, either is fine with me. Web is probably better in the long term but it might be better to wait on that until the dust settles on the ui/next work) that can collect `/_status/ranges/local` from every node and aggregate it, grouping the data by range ID. This can report on problems including the following (note that many of these are normal transient occurrences, but it could indicate a real problem if they persist or affect many ranges at once):
- Stores that are listed as replicas according to other stores, but don't have the range themselves
- Stores that have the range but aren't listed in other stores
- Ranges with no leader, or more than one leader

We could also add some more information to the `/_status/ranges` page: log positions for all replicas (to indicate when one is behind), total size of the range (to report on ranges that have gotten too large without splitting), the range lease holder (which should usually be the same as the raft leader), and the raft term number (high or growing term numbers can indicate election problems).

**Comment by tschottdorf** [comment]
Just throwing them out there. No need to take these as necessary; just a wishlist.

* number of pending commands (`len(r.mu.pendingCmds)`)
* outbox queue length (or some measure of how saturated the transport is, see `(*RaftTransport).Send`). If it is saturated, the next natural question is what saturates it (elections, heartbeats, normal appends?)

**Comment by bdarnell** [comment]
The next thing I'd like to see here is more information about the raft log:
* FirstIndex and LastIndex for all replicas (probably displayed as (FirstIndex, LastIndex-FirstIndex) in the UI)
* RaftStatus.Progress for the leader

**Comment by cuongdo** [comment]
It'd be great to track some of the aforementioned numbers as time-series
data. For example:

- number of pending commands
- outbox queue length
- raft progress

Also maybe some the following make sense especially as time-series metrics:
- time commands spend in the queue (would be great as percentiles)
- time commands take to execute (would be great as percentiles)
- counts for each type of command (snapshot, heartbeat, vote, etc.)
- time it takes to acquire range leader lease
- range leader lease attempts

Some of these may not make sense since I don't know much about how we use
Raft. A lot of these would've been useful when diagnosing the issues I've
seen running allocator tests.

**Comment by bdarnell** [comment]
I don't think our internal time series storage can scale to range-level stats. These may be useful stats if we aggregate them at the store level (I'm not sure if raft progress can be aggregated in a sensible way), but let's keep that separate from this issue, which is about range-level visibility.

**Comment by tschottdorf** [comment]
#7250 does not expose, but makes available for ui consumption all of `r.mu.state` + lastIndex (so in particular also the first index, via the truncation state).

The progress is almost available, all that's needed is to put that into protos (currently we throw away the whole `raft.Status` and only keep the info whether it thinks it's the leader).

**Comment by bdarnell** [comment]
Closing this since we now have a number of useful raft debug pages.
