### ISSUE TITLE
Typo in Network Description on Statements Page

### ISSUE THREAD

**Issue by barryhe2000** [cockroachdb/cockroach#66602]
<img width="1711" alt="Screen Shot 2021-04-06 at 2 44 40 PM" src="https://user-images.githubusercontent.com/49596388/113762810-fca13580-96e6-11eb-8fae-ac7942f60902.png">

The beginning of the description for the Networks column on the statements page reads "Amount of data data" (the second "data" is redundant)

"specified" is also spelled incorrectly

**Comment by thtruo** [comment]
cc @kevin-v-ngo looks like this one is on your team's plate - lmk if you think otherwise
