### ISSUE TITLE
server,migrations: ensure that no old version can serve traffic

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#66606]
**Is your feature request related to a problem? Please describe.**

In kv nodes we take great care to ensure that old code cannot connect to the cluster before running long-running migrations. For tenants we don't have any such guard rails. Today, with a single instance, this is ~fine (we should add a sanity check that we don’t downgrade post finalization, PR inbound). However, we’ll need to do something more with multiple nodes.

The mechanism by which we do this in the host cluster is via the `migration.Cluster` interface which has an important method `UntilClusterStable`. Today this implementation is a no-op for tenant clusters. 

https://github.com/cockroachdb/cockroach/blob/4758a228754eedd4605d419a172e8e0913de9ac5/pkg/migration/migrationcluster/tenant_cluster.go#L142-L149

**Describe the solution you'd like**

1) The very first step is add sanity checking during tenant server startup to ensure that the version is high enough before serving sql traffic.

2) Next we need to add a protocol to ensure that old instances will never join the cluster. The proposed solution here piggy-backs off of 1) and #62818. 

If we were to make sure that all sql instances check the cluster setting for their version after they write their entry into the instances table, and fail to start up if their version is too old, then we'd know that no instance that is too old will actually start serving traffic. Now, we'll also want to check the version *before* writing our entry to not starve the whole process. Lastly, inside the `UntilClusterStable`, we'll want to make an RPC to each instance and check it's version.

**Describe alternatives you've considered**

Another approach would be to actually just write the binary version for each instance into the instances table. I sort of like that approach too. Then instead of making RPCs, we could just scan the instances table.

Epic: CRDB-10829

Jira issue: CRDB-8144

**Comment by tbg** [comment]
@lunevalex can you figure out which team owns this kind of issue? There isn't a compelling argument that it should be KV, as this is primarily about SQL tenants.
The answer might be that KV is the only place to put it for lack of any other team being able to provide ownership, but I doubt that.

**Comment by ajwerner** [comment]
Increasingly I think of this as the server team. It's related to server startup. How do y'all feel about that position?

**Comment by lunevalex** [comment]
@ajwerner I think that is a good suggestion, @knz curious to hear your thoughts?

**Comment by knz** [comment]
agreed

**Comment by knz** [comment]
that being said we need a knowledge transfer first (like for the rpc/networking code)

**Comment by lunevalex** [comment]
I belive @ajwerner would be the person with knowledge in this area

**Comment by ajstorm** [comment]
Removing the release blocker flag as discussed here: https://cockroachlabs.slack.com/archives/C02HWA24541/p1644865125179499.

**Comment by ajstorm** [comment]
Reopening.  #91071 only addressed part of this issue.  We still need to prevent SQL pods that are too old from connecting to up-level host clusters.

**Comment by ajstorm** [comment]
@healthy-pod Can you confirm that you've fixed this last part of the issue?  If so, can you close this?

**Comment by healthy-pod** [comment]
This was completed in #94973. If the binary version of a pre-starting SQL server is too low for the tenant logical version as read from storage, it will fail to start.
