### ISSUE TITLE
Add CES link to feedback survey

### ISSUE THREAD

**Issue by nathanstilwell** [cockroachdb/cockroach#66615]
To support the collection of a Customer Effort Score, add a link in DB Console to an feedback flow hosted on a marketing page. 

![Screen Shot 2021-06-17 at 16 58 14](https://user-images.githubusercontent.com/397448/122471372-3915cb00-cf8d-11eb-9ce9-1e01985e0306.png)

Ignore that DB Console doesn't look like this anymore. The relevant bit is in the top right corner there ...

![Screen Shot 2021-06-17 at 16 58 10](https://user-images.githubusercontent.com/397448/122471482-58acf380-cf8d-11eb-8d20-2710e9ca0364.png)

One piece of information that we want to share through this link is the version of the cluster the user is providing feedback for. The cluster version is available on the client from the [`singleVersionSelector`](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/src/redux/nodes.ts#L463),
```ts
// pkg/ui/src/views/app/containers/layout/index.tsx:109
const mapStateToProps = (state: AdminUIState) => {
  return {
    clusterName: clusterNameSelector(state),
    clusterVersion: singleVersionSelector(state),
    clusterId: clusterIdSelector(state),
  };
};
```

I'm imagining that we can send this cluster version appended to url to the survey as a query param. Something like `https://cockroachlabs.com/.../whatever-survey?clusterId=XX.X.X` to get pickup up on the other side with something like 

```js
// tldr;
// Object.fromEntries(new URLSearchParams(window.location.search).entries())["clusterId"]

const urlParams = new URLSearchParams(window.location.search);
const params = Object.fromEntries(urlParams.entries());
/**
{
  clusterId: "XX.X.X",
}
*/
```

or however you like to parse the query string.

Epic CRDB-8313

**Comment by rsadres** [comment]
Updated mockups
[global nav ](https://www.figma.com/file/fwIOC7vNuUPlNbfMgPsGgb/CES?node-id=608%3A2293)
or 
[left nav](https://www.figma.com/file/fwIOC7vNuUPlNbfMgPsGgb/CES?node-id=608%3A3116)

**Comment by Annebirzin** [comment]
@rsadres I think we landed on the [global nav](https://www.figma.com/file/fwIOC7vNuUPlNbfMgPsGgb/CES?node-id=608%3A2293) 'borderless' style button, yes?

<img width="301" alt="Screen Shot 2021-07-19 at 6 20 04 PM" src="https://user-images.githubusercontent.com/51920721/126234799-8fa99de5-3706-4004-a084-6ea19e548043.png">

**Comment by rsadres** [comment]
Sounds good, edited my comment.
