### ISSUE TITLE
release: v20.2.12 (June 28, 2021)

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#66627]
Candidate SHA: 402d4f6
Deployment status: **Deployed & Qualified**
Make and Publish Build: [TeamCity](https://teamcity.cockroachdb.com/buildConfiguration/Internal_Release_MakeAndPublishBuild/3111712)
Qualify Build: [TeamCity](https://teamcity.cockroachdb.com/buildConfiguration/Internal_Release_Qualify/3112206)
Publish Cockroach Release: [TeamCity](https://teamcity.cockroachdb.com/buildConfiguration/Internal_Release_PublishCockroachRelease/3128397)
 
CC Clusters Running the Build:
- https://cockroachlabs.cloud/cluster/88be6ebe-1331-45c1-a0b6-a1e0b6af7488

Working Tags:
- Build ID: `v20.2.11-48-g402d4f690a`
 
[Release process checklist](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process)
 
Prep date: June 21, 2021
- [x] [2. Pick a SHA](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-2.PickaSHA)
   - [x] fill in `Candidate SHA` above
   - [x] fill in `Build ID` above
   - [x] fill in `Make and Publish Build` above
   - [x] fill in `Qualify Build` above
 
- [x] [3. Announce the release to releases@](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-3.Announcethereleasetoreleases@)
- [x] [4. Ask SRE to run the build on some CC clusters](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-4.AskSREtorunthebuildonsomeCCclusters)
 
5-8: Qualify the Release. See [Release Qualification](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification)
- Short-running Checks:
- [x] [5. Verify node crash reports](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification#Verify-node-crash-reports-appear-in-sentry.io)

https://sentry.io/organizations/cockroach-labs/issues/2480557510/?project=164528&query=is%3Aunresolved

- Qualification Clusters:
- [x] [6. Setup Qualification Clusters](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification#Setup-Qualification-Clusters)
 
Monitoring the Qualification Clusters (ideally one day after creation, halfway through the week, and before the release):
 
- [x] [7. Keep an eye on clusters](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification#Monitoring-the-Qualification-Clusters) until release date.
 
**Do not proceed below until the release date.**
 
Release date: 6/28/2021
- [x] [7 continued: Check cluster status](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification#Monitoring-the-Qualification-Clusters)
- [ ] 8. Destroy clusters
- [x] [9. Publish Cockroach Release](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-9.PublishTheRelease)
    - https://teamcity.cockroachdb.com/buildConfiguration/Internal_Release_PublishCockroachRelease/3128397
- [x] Acked security@ and release-engineering-team@ on the generated AWS S3 bucket write alert to confirm these writes were part of a planned release (See [Publish Cockroach Release](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-9.PublishTheRelease) for details).
- [x] [10. Check binaries](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-10.CheckBinaries).
  - https://github.com/cockroachdb/bincheck/pull/278
- [x] [11. Check docker image](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-11.Checkthedockerimage)
- [x] [12. Remove staging branch / tags from repository](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-12.Removestagingbranch/tags)
- [x] [13.Announce the release is cut to releases@](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-13.Announcethereleaseiscuttoreleases@)
- [x] [14. Update version numbers](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-14.Updateversionnumbers)
- For production or stable releases in the latest [major release](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Knowifthereleaseisonthelatestmajorreleaseseries) series only (in August 2020, this is the v20.1 series):
    - [x] Update [Brew Recipe](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Brewrecipe)
    - [x] Update [Orchestrator configurations:CRDB](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Orchestratorconfigurations:CRDB)
    - [x] Update [Orchestrator configurations:Helm Charts](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Orchestratorconfigurations:HelmCharts)
- For all production or stable releases:
    - [x] Create a ticket in the [Dev Inf tracker](https://cockroachlabs.atlassian.net/wiki/spaces/devinf/pages/429097164/Submitting+Issues+Requests+to+the+Developer+Infrastructure+team) to update the Red Hat Container Image Repository as outlined in https://github.com/cockroachlabs/cockroach-redhat-deploy/blob/main/README.md.
        - https://github.com/cockroachdb/dev-inf/issues/490
    - [x] *After docs are updated* [Announce version to registration cluster](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-AnnounceVersionToRegCluster)
    - [x] [Update version map in bin/roachtest (all stable releases) and regenerate test fixtures (only major release)](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Updateversionmapinroachtestandregeneratetestfixtures)
        - https://github.com/cockroachdb/cockroach/pull/66995
- [x] 15. Update docs (handled by Docs team)
- [x] 16. External communications for release (handled by Marketing eam)

**Comment by nvanbenschoten** [comment]
I think we need to pick a new SHA here. We are seeing crashes in https://github.com/cockroachdb/cockroach/issues/66717 and https://github.com/cockroachdb/cockroach/issues/66719 due to the [last commit](https://github.com/cockroachdb/cockroach/commit/a58b5e2f3611bcab060e65efade816a00f25c734) in this release.

**Comment by ajwerner** [comment]
Okay, let's restart this with 402d4f690a9aebe10042481064415150ab3ead32.

**Comment by ajwerner** [comment]
Kicked off https://teamcity.cockroachdb.com/buildConfiguration/Internal_Release_MakeAndPublishBuild/3111712 to make new binaries at 402d4f6.

**Comment by ajwerner** [comment]
Okay, new binaries have been built. Waiting on deploy in [SREOPS-2311](https://cockroachlabs.atlassian.net/browse/SREOPS-2311).

**Comment by shermanCRL** [comment]
All good, publishing soon?

**Comment by ajwerner** [comment]
We're meeting soon. I'm a little unsure of the details of the process at this point. I'll answer the question when I know it.

**Comment by ajwerner** [comment]
@shermanCRL, yes, I'll be working to get this out later today.
