### ISSUE TITLE
bazel,teamcity: bazel CI fails due to 1 failed test but none appear to have failed

### ISSUE THREAD

**Issue by postamar** [cockroachdb/cockroach#66631]
I noticed something weird in a recent build of mine:
https://teamcity.cockroachdb.com/viewLog.html?buildId=3095486&buildTypeId=Cockroach_GitHubCiOptional
It seems like teamcity is reporting a failure (due to 1 test having apparently failed) despite all tests having apparently passed.

<img width="937" alt="Screen Shot 2021-06-18 at 12 09 41" src="https://user-images.githubusercontent.com/3010904/122589779-acbbe480-d02e-11eb-9ada-5fa7452f2a4e.png">

**Comment by rickystewart** [comment]
This kind of thing has been observed from time to time -- sometimes TC reports builds as failed with a single failed test, even when there is none. It sucks, but we don't know what the actual issue is nor how to fix it.
