### ISSUE TITLE
sql/schemachanger: Resolve timing hole in with primary key schema changes in schemachange/random-load workload

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#66663]
There are certain schema change operations (referred to as `sc-disallowed` in the remainder of this description) which are not permitted in the presence of existing alter primary key schema changes (e.g. making a column nullable, making a column not nullable).  The way we test this in schemachange/random-load is by querying the jobs table before making the `sc-disallowed` call and determining if there's another PK change in progress.  If there is a PK change in progress, then we add the expected error to the list of errors to look out for when executing `sc-disallowed`.  

The problem however, is that there seems to be a timing hole here.  If we detect a PK change in progress which then completes before `sc-disallowed` is executed, `sc-disallowed` will succeed and the test will fail (as the expected error is not encountered).  This is blocking progress on cleaning up schemachanger/random-load so I've disabled these known cases for now.  They should be reenabled with this issue.

Jira issue: CRDB-8169

**Comment by ajwerner** [comment]
@fqazi I have to imagine that we've figured this out by now. Can this be closed?

**Comment by fqazi** [comment]
Yes this one has been fixed.
