### ISSUE TITLE
server: Status requests for other nodes are incorrectly proxied to the non-http port

### ISSUE THREAD

**Issue by d4l3k** [cockroachdb/cockroach#6667]
Status information requests about other nodes are not correctly proxied.
It seems that after http requests were split into a separate port, server/status.go was not updated to know about it and continues to make http requests to the old port.

```
Request:
Get http://localhost:8080/_status/ranges/2

Response (500):
Get http://localhost:26258/_status/ranges/2: malformed HTTP response "\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x04\b\x00\x00\x00\x00\x00\x00\x0e\xff\xf1"
```

**Comment by tamird** [comment]
Dupe of #5530.

**Comment by d4l3k** [comment]
Okay, closing this one.
