### ISSUE TITLE
sql: Enhance third-party telemetry to capture both the tool version and adapter version

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/cockroach#66672]
Using `crdb_internal.increment_feature_counter`, we can capture arbitrary metadata about third-party tool usage. We want to capture ORM version and adapter version consistently across all CockroachDB adapters.

We should also confirm that the counter is incremented on application initialization, i.e. once on startup.

Adapter | ORM version | Adapter version 
---------|-------------|-----------------
Active Record | ? | ?
Django | ? | ?
Sequelize | X | ?
SQL Alchemy | ? | X

Epic CRDB-2510

**Comment by rafiss** [comment]
already posted in https://github.com/cockroachdb/cockroach/issues/66500 but here are the versions being reported.


| ORM               | Dialect                                |
|-------------------|----------------------------------------|
| Django 3.2        | django-cockroachdb 3.2.2               |
| sqlalchemy 1.4.22 | sqlalchemy-cockroachdb 1.4.0           |
| ActiveRecord 6.1  | activerecord-cockroachdb-adapter 6.1.3 |
| Sequelize 6.1.0   | sequelize-cockroachdb 6.0.1            |
