### ISSUE TITLE
cluster-ui: redux saga repeats requests in infinite loop when endpoint unavailable

### ISSUE THREAD

**Issue by dhartunian** [cockroachdb/cockroach#66676]
**Describe the problem**

When the CockroachCloud backend returns 5xx errors to `cluster-ui` components, they retry indefinitely becaues the refresh/fail/request loop is configured in the saga code for the statements endpoint fetching.

![Screen Shot 2021-06-15 at 3 55 46 PM](https://user-images.githubusercontent.com/986307/122806688-9f099780-d298-11eb-8d4c-085241fd5174.png)

**Proposed Solution**

Ideally, the frontend should not retry forever or implement some sort of backoff instead of hammering the UI. The server will also implement mitigations here.

Jira issue: CRDB-8173

**Comment by sjbarag** [comment]
I can't seem to repro on cockroachlabs.cloud, using proxyman to force an HTTP 500 response for `/db-console/:cluster-id/:region/:node/_status/statements`. This probably got fixed at some point and the github issue was left open (or just not even known about).

If we see this again, let's open a new ticket with some more recent screenshots and maybe a `.har`!
