### ISSUE TITLE
kv: raft ticks are not adaptive to slow scheduling

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#66686]
Related to https://github.com/cockroachdb/cockroach/issues/66682.
Related to https://github.com/cockroachdb/cockroach/issues/17500.

We configure Raft to tick each Raft group every 200ms (`defaultRaftTickInterval`). We also configure leaders to send Raft heartbeats every 5 ticks (`defaultRaftHeartbeatIntervalTicks`). Finally, we configure followers to call elections every 15 ticks (`defaultRaftElectionTimeoutTicks`). In the happy case, this all works.

However, there are various reasons why a raft tick may not be scheduled for over 200ms. The obvious case is scheduler overload. But the case that we see more commonly is a single Range being slow to either process incoming requests [here](https://github.com/cockroachdb/cockroach/blob/e1697d1728be9165adad55b489676773062d4ef4/pkg/kv/kvserver/scheduler.go#L272) or perform synchronous local I/O [here](https://github.com/cockroachdb/cockroach/blob/e1697d1728be9165adad55b489676773062d4ef4/pkg/kv/kvserver/scheduler.go#L284). This can delay a Raft tick for more than 200ms, which can delay heartbeats, which can cause leadership instability.

If we are starving all Raft progress for 3+ seconds, we certainly won't be able to hold stable leadership. However, there's a less severe case that can be just as devastating and is likely more common. A leader will only send out a heartbeat every 5 ticks. So even if a leader is delayed in processing ticks by only 600ms, it will not send out heartbeats fast enough to maintain leadership. This is what we saw in #66682.

We should be able to provide some stability here by making raft ticks more adaptive to scheduling delays. For instance, if we want to tick every 200ms but we are delayed by 600ms between ticks, each call to [`replica.tick`](https://github.com/cockroachdb/cockroach/blob/d0cdd738c54df6ea8a73cc06a92bd5812947605d/pkg/kv/kvserver/replica_raft.go#L956) could call Tick on the internal raft group 3 times. This would ensure that heartbeats are still sent out roughly every second. This would allow us to make a rough guarantee that as long as a leader is scheduled by the Raft scheduler once every 3 seconds, it will be able to retain leadership (if we want it to).

/cc @cockroachdb/kv

Jira issue: CRDB-8183

**Comment by pavelkalinnikov** [comment]
The approach I'm exploring in #86240 calls `Tick` as many times as it has been scheduled by the `raftTickLoop`, as opposed to (currently) dropping them on the floor if there is another tick in flight. I wonder to which degree it would help to solve this issue. It will definitely make the long-/mid-term average duration of a tick close to the target.

But in the described scenario, let's say we are unlucky, and the tick that turns out to be slow (600ms) is the very last one before the leadership heartbeat. Will that result in the described badness regardless of the adaptiveness?

**Comment by pavelkalinnikov** [comment]
Ah, that seems fine. The described badness case is when each tick takes 600ms (not just one). For his case the adaptive scheduling will work well: it will call 3 ticks per try, and in the worst case send heartbeats every 1200ms, which is under 3s.
