### ISSUE TITLE
build: roachtest-weekly script not up to date

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#66703]
The `build/teamcity-weekly-roachtest.sh` script is lagging behind the `teamcity-nightly-roachtest` script.
The former is essentially a very old copy of the latter. We should unify these scripts, to avoid a janky build such as before 0e17774659590b082c43e621cf3da81cb4c51431 where the weekly failed for a long period of time: https://github.com/cockroachdb/dev-inf/issues/471

Jira issue: CRDB-8189

**Comment by rharding6373** [comment]
What tests, environments, etc. should only run on the weekly vs the nightly roachtest?

**Comment by rickystewart** [comment]
Whoops, sorry. :)

**Comment by tbg** [comment]
Rachel, the weekly is for long-running tests (several days). There usually isn't a need to add new roachtests to it. This issue tracks that the contents of the script, i.e. the way it invokes roachtest, is a one off and should be unified with the nightly script.
