### ISSUE TITLE
Tenant SQL pod at an incompatible binary version gets unexpected behaviour 

### ISSUE THREAD

**Issue by alyshanjahani-crl** [cockroachdb/cockroach#66721]
**Describe the problem**

A tenant cluster running w/ a 20.2 binary & cluster version is able to make connections to a KV layer at cluster version 21.1. The sql pod has unexpected behaviour for ex/

```
root@localhost:26257/defaultdb> show tables;
ERROR: no allowed privileges found for system table with ID=40
```
In the logs, you can see the stats collection job failing similarly
```
E210622 15:18:51.714727 32 sql/stats/automatic_stats.go:341 ⋮ [clusterID=39060f06-aae9-45b7-a4a8-2cbd74c584af,tenantID=2,instanceID=10001] failed to get tables for automatic stats: ‹get-tables›: ‹no allowed privileges found for system table with ID=40›
```

**To Reproduce**

(Performed on kubernetes cluster)
Created a host cluster using v21.1.2
Create a tenant w/ tenant_id = 2
Create a SQL pod (using v20.2.10) for that tenant (startup command shown below)
```
exec /cockroach/cockroach mt start-sql --certs-dir=/cockroach/cockroach-certs --logtostderr --log-dir /cockroach/cockroach-data/logs --log-group-max-size 5MiB --log-file-max-size 1MiB --kv-addrs cockroachdb-internal:26257 --tenant-id 2 --sql-addr :26257
```
Exec into the pod and open a sql shell, try issuing `SHOW TABLES`

**Expected behavior**
I expected the tenant process to not be able to connect/dial KV. Instead of an undefined behaviour.
In the logs of the sql pod, you see it able to intialize/connect to kv:
```
I210622 15:18:51.061832 1 server/server_sql.go:800 ⋮ done ensuring all necessary migrations have run
I210622 15:18:51.061940 1 server/server.go:1891 ⋮ serving sql connections
I210622 15:18:51.062011 1 server/testserver.go:775 ⋮ [config] clusterID: ‹39060f06-aae9-45b7-a4a8-2cbd74c584af›
I210622 15:18:51.062068 1 server/testserver.go:776 ⋮ [config,clusterID=39060f06-aae9-45b7-a4a8-2cbd74c584af] tenantID: ‹2›
I210622 15:18:51.062081 1 server/testserver.go:776 ⋮ [config,clusterID=39060f06-aae9-45b7-a4a8-2cbd74c584af] instanceID: 10001
I210622 15:18:51.062107 1 cli/mt_start_sql.go:127 ⋮ [clusterID=39060f06-aae9-45b7-a4a8-2cbd74c584af,tenantID=2,instanceID=10001] SQL server for tenant ‹2› listening at ‹[::]:26257›, http at ‹[::]:8080›
```

**Environment:**
- using K3D (light weight kubernetes distribution)
  - CC repository has test utilities to easily set up/repro this test. Let me know if you'd like me to try anything else.

**Comment by alyshanjahani-crl** [comment]
cc @tbg @ajwerner

**Comment by ajwerner** [comment]
This is exactly step 1 of https://github.com/cockroachdb/cockroach/issues/66606.

**Comment by alyshanjahani-crl** [comment]
Ah i didn't put 2 & 2 together.
Apologies.
