### ISSUE TITLE
sql: Add telemetry for jobs duration

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/cockroach#66725]
CockroachDB has different jobs that execute asynchronous tasks. It would be useful in product data to analyze how long jobs take to complete.

Jira issue: CRDB-8203

**Comment by ajwerner** [comment]
This is another thing that would be good to drive with events. We can track a number of different things. We can track how long the current instance of the job ran if it completed (the common case) but that would not take into account restarts or pauses. We could track the time from start to completion (which would include restarts and pauses). Also, we'd not know the actual contents of the job. Other jobs wait most of the time (think GC job).
