### ISSUE TITLE
kvserver: deadlock in protectedts error message

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#66759]
**Describe the problem**

https://github.com/cockroachdb/cockroach/pull/61610 introduced a deadlock by calling methods like `(*Replica).Desc()` in `protectedTimestampRecordCurrentlyApplies` while already holding `(*Replica).mu`.

**To Reproduce**

**Expected behavior**

**Environment:**
affects master and release-21.1 since the PR was backported.

**Additional context**

In practice, a complete outage of the affected clusters, see for instance https://github.com/cockroachlabs/support/issues/1019 where this occurred multiple times and where it was first diagnosed.

**Comment by tbg** [comment]
Here's the actual line

https://github.com/cockroachdb/cockroach/pull/61610/files#diff-df352b241ee66c113245a931571984e92f8df9ef73037bb799b2bf10b1c8d4deR193

and

https://github.com/cockroachdb/cockroach/pull/61610/files#diff-df352b241ee66c113245a931571984e92f8df9ef73037bb799b2bf10b1c8d4deR208-R211

We need to vet the rest of that PR, too.

**Comment by tbg** [comment]
What's interesting is that this would've been caught under `-tags=deadlock` (assuming some test exercised this method, which I hope would be the case!)

```go
func TestFoo(t *testing.T) {
	var mu syncutil.RWMutex
	mu.RLock()
	mu.RLock()
	mu.RUnlock()
	mu.RUnlock()
}
```

```
$ go test -tags deadlock -run TestFoo ./pkg/kv/kvserver/
POTENTIAL DEADLOCK: Duplicate locking, saw callers this locks in one goroutine:
current goroutine 8225 lock &{{{0 0} 0 0 1 0}} 
all callers to this lock in the goroutine
replica_test.go:13365 kvserver.TestFoo { mu.RLock() } <<<<<

replica_test.go:13366 kvserver.TestFoo { mu.RLock() } <<<<<


Other goroutines holding locks:


FAIL	github.com/cockroachdb/cockroach/pkg/kv/kvserver	0.142s
```

This is more evidence that we need to bring the nightly stress under the `deadlock` tag back. I think we discussed this before but I can't find the issue at this moment.

**Comment by adityamaru** [comment]
We have a test that would have failed with the `-tags-deadlock`

```
❯ go test -tags deadlock -run TestProtectedTimestampRecordApplies ./pkg/kv/kvserver
I210623 13:13:13.487585 1 (gostd) rand.go:92  [-] 1  random seed: -8239150671616311089
POTENTIAL DEADLOCK: Duplicate locking, saw callers this locks in one goroutine:
current goroutine 10752 lock &{{{0 0} 0 0 1 0}}
all callers to this lock in the goroutine
replica_protected_timestamp.go:180 kvserver.(*Replica).protectedTimestampRecordCurrentlyApplies { r.mu.RLock() } <<<<<
replica_protected_timestamp.go:79 kvserver.(*Replica).protectedTimestampRecordApplies { willApply, cacheTooOld, doesNotApplyReason, err := r.protectedTimestampRecordCurrentlyApplies( }
replica_protected_timestamp_test.go:86 kvserver.TestProtectedTimestampRecordApplies.func3 { willApply, doesNotApplyReason, err := r.protectedTimestampRecordApplies(ctx, &args) }
replica_protected_timestamp_test.go:307 kvserver.TestProtectedTimestampRecordApplies.func13 { testCase.test(t, tc.repl, mc) }

replica.go:752 kvserver.(*Replica).Desc { r.mu.RLock() } <<<<<
replica_protected_timestamp.go:195 kvserver.(*Replica).protectedTimestampRecordCurrentlyApplies { r.Desc().StartKey.String(), r.Desc().EndKey.String()) }
replica_protected_timestamp.go:79 kvserver.(*Replica).protectedTimestampRecordApplies { willApply, cacheTooOld, doesNotApplyReason, err := r.protectedTimestampRecordCurrentlyApplies( }
replica_protected_timestamp_test.go:86 kvserver.TestProtectedTimestampRecordApplies.func3 { willApply, doesNotApplyReason, err := r.protectedTimestampRecordApplies(ctx, &args) }
replica_protected_timestamp_test.go:307 kvserver.TestProtectedTimestampRecordApplies.func13 { testCase.test(t, tc.repl, mc) }


Other goroutines holding locks:


FAIL    github.com/cockroachdb/cockroach/pkg/kv/kvserver        1.837s
FAIL
```

**Comment by tbg** [comment]
Nice, @aliher1911 can you check that this passes reliably with your patch?

I filed https://github.com/cockroachdb/cockroach/issues/66764 to bring the nightly deadlock stress runs back.

**Comment by RaduBerinde** [comment]
If that test hits the double-acquire path, how does it not deadlock?

**Comment by ajwerner** [comment]
> If that test hits the double-acquire path, how does it not deadlock?

There's no deadlock in the test because you can reacquire an RLock. The deadlock tag detects that reacquisition which is potentially hazardous. 

See https://github.com/sasha-s/go-deadlock
