### ISSUE TITLE
changefeedcc: Investigate whether rangefeed registration can hold the raftMu for excessive amounts of time

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#66766]
Investigate whether rangefeed registration can hold the raftMu for excessive amounts of time.
In `replica_rangefeed.go` we acquire raftMu when registering new range feed.

```
// Lock the raftMu, then register the stream as a new rangefeed registration.
// raftMu is held so that the catch-up iterator is captured in the same
// critical-section as the registration is established. This ensures that
// the registration doesn't miss any events.
r.raftMu.Lock()
```

Investigate the impact of such locking.  In particular, we need to know the amount of time
this lock can be held (potentially slowing down replica traffic) particularly in the face of repeated
changefeed restarts (due to transient errors).

Rough outline of the test:

1. Start sufficiently large cluster and initialize it with some data:
```
roachprod create -n 6 {user}-cluster
roachprod stage {user}-cluster cockroach
roachprod start {user}-cluster
roachprod run {user}-cluster:1 "./cockroach workload fixtures import tpcc --warehouses=5000"
``` 

2. Start tpcc:
```
roachprod ssh {user-cluster}:1 
./cockroach workload run tpcc --warehouses=5000 --conns=200 --max-rate=250 <output of roachprod pgurl {user-cluster}
```

3. Configure small-ish max changefeed memory setting: `changefeed.memory.per_changefeed_limit`
4. Start changefeeds, probably on tpcc/stock table, writing to `null://?delay=1s` (or some such, without backfill) (we need to play here a bit -- because we want to make sure that changefeed checkpoints highwater mark first -- so, I would probably start with large memory limit, make sure we checkpoint highwatermark, then pause/unpause changefeed, with new memory limit).

We also need to add some instrumentation to replica_rangefeed (though slow mu acquisitions are printed in the logs anyway).

Jira issue: CRDB-8220

**Comment by ajwerner** [comment]
What lead to this being filed? Is there some evidence that this is a problem?

If you look under that call, I don’t think that there’s any long-running operations. It’s just constructing an iterator (which is an in-memory operation IIUC). A concern one might have is that the processor loop would starve the registration but the only thing that would do that would be events which are published from under the raftMu.

**Comment by ajwerner** [comment]
Oh! I see the problem. If we construct a new `Processor` then we do the scan to collect the intents before accepting the registration! At least that's easy enough to deal with.

**Comment by ajwerner** [comment]
Wait, nevermind, that is async.

**Comment by stevendanna** [comment]
Do we know what an excessive amount of time would be for this particular lock?

**Comment by miretskiy** [comment]
We noticed during outage log messages indicating slow raft my acquisition. We also had persistently restarting change feeds. This is just to eliminate cf as a culprit.... Or not

**Comment by miretskiy** [comment]
I think another problem that when registering, we flush any events in the pipeline (at least that's my read):

```
// Synchronize the event channel so that this registration doesn't see any
// events that were consumed before this registration was called. Instead,
// it should see these events during its catch up scan.
p.syncEventC()
```

So, if we have an active rangefeed, then establishing new one means flushing events.
And we do that w/ raftMu held.

**Comment by miretskiy** [comment]
closing; stale
