### ISSUE TITLE
schema support via search_path

### ISSUE THREAD

**Issue by zenoran** [cockroachdb/cockroach#66779]
name | title | about | labels | assignees
----- | ----- | ----- | ----- | ----- 
Feature request | schema support via search_path | schema support being officially adopted | C-enhancement | --

**Is your feature request related to a problem? Please describe.**
The problem is having all the tables dumping to the public schema

**Describe the solution you'd like**
Ideally to have an option available within the database engine config to specify a schema

**Describe alternatives you've considered**
search_path appears to be effective but it requires modifying the create_cursor method in DatabaseWrapper and also modifying the get_table_list in DatabaseIntrospection. 

**Additional context**
I think it would be fairly easily to integrate this through a parameter passed within the database connection (similar to other DB engines), but I was wondering why it wouldn't have be done yet?  Having the basis of the engine to be dumping all tables within the public schema seems a bit odd.  Unless I'm missing something?

Thanks!

**Comment by ajwerner** [comment]
I'm having a hard time understanding the exact problem being described in this issue. Can you provide a more concrete example of how the search_path behavior is violating your expectations?

**Comment by zenoran** [comment]
> I'm having a hard time understanding the exact problem being described in this issue. Can you provide a more concrete example of how the search_path behavior is violating your expectations?

My apologies!  I meant to post this in the django-cockroachdb repo!
