### ISSUE TITLE
server: backport debug zip improvements to 20.2

### ISSUE THREAD

**Issue by lunevalex** [cockroachdb/cockroach#66789]
The following changes should be backported to all supported releases i.e. 20.2

https://github.com/cockroachdb/cockroach/pull/64094
https://github.com/cockroachdb/cockroach/pull/64128

**Comment by knz** [comment]
It's already backported to 21.1 though

**Comment by lunevalex** [comment]
you are correct amended the description.

**Comment by knz** [comment]
The backport wasn't clean. Not backporting since 21.2 is nearly out of the door now.
