### ISSUE TITLE
CockroachDB can't import NULL int

### ISSUE THREAD

**Issue by kernfeld-cockroach** [cockroachdb/cockroach#66783]
**Describe the problem**

When importing a nullable int column, CockroachDB doesn't interpret the string `NULL` to mean a null value; instead, it returns an error.

**To Reproduce**

1. `cockroach start-single-node --listen-addr=localhost --insecure --external-io-dir=<working-dir>`
2. `echo "1\n2\nNULL\n" > <working-dir>/nullable-int.csv`
3. `cockroach sql --insecure -e "IMPORT TABLE nullable_int (my_int INT) CSV DATA ('nodelocal://self/nullable-int.csv')"`

The error was:

```
ERROR: nodelocal://self/nullable-int.csv: error parsing row 3: parse "my_int" as INT8: could not parse "NULL" as type int: strconv.ParseInt: parsing "NULL": invalid syntax (row: "NULL")
Failed running "sql"
```

**Expected behavior**

When importing a CSV file into a nullable int column, CockroachDB should interpret "null-y" values as NULL. Unfortunately CSV is not standardized, so there's no unambiguous interpretation of what values are "null-y." As a start, I would suggest using the same values as [read_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) from pandas, since pandas is an extremely popular tool and has had a lot of time to iterate on this problem. While an overly long list of "null-y" values could cause problems when importing string data, it seems fine for integers.

**Environment:**

 - CockroachDB CCL v20.2.3
 - Server OS: MacOS
 - Client app `cockroach sql`

**Additional context**

This problem was [originally reported](https://stackoverflow.com/questions/68103016/cockroachdb-csv-import-failing-due-to-null-column) by user kcon123 on StackOverflow.

Jira issue: CRDB-8228

**Comment by ajwerner** [comment]
See the `nullif` option: https://www.cockroachlabs.com/docs/stable/import.html#import-options

**Comment by kernfeld-cockroach** [comment]
I noted `nullif` on the StackOverflow response, but I also think it would be more user-friendly if this worked out of the box.
