### ISSUE TITLE
kvserver: admin functionality to manipulate KV data

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#66829]
It would be useful to have functionality to manipulate KV entries, e.g. to get rid of stale node status entries as seen in a recent customer escalation.

This should be implemented as an admin RPC endpoint or separate RPC service that is only available with node certs (i.e. not via gRPC gateway); we don't want this to be too easily accessible.

The endpoint should take an arbitrary gRPC `BatchRequest` and pass it through a local sender stack (including at least `DistSender` but probably also `TxnCoordSender`), effectively proxying the request for the caller. Transaction support is not necessary, using a single atomic `BatchRequest` would be sufficient for most uses.

The `cockroach debug` CLI should at the very least take a Protobuf-encoded BatchRequest, but we may want additional tooling to generate this e.g. from JSON data or CLI command args/flags.

**Comment by erikgrinaker** [comment]
This was touched on in a different discussion (https://github.com/cockroachdb/cockroach/issues/54971#issuecomment-914337986), where the consensus was in the direction of adding SQL commands for this rather than CLI commands.

**Comment by knz** [comment]
1. generally we prefer SQL commands
2. these need to be admin-only obviously
3. we'll want an audit log of all these operations, probably via a separate log channel, so that during troubleshooting we can easily extract a complete history of these manual tamperings

**Comment by erikgrinaker** [comment]
I'm thinking of spending breather week on this. What I'm planning is basically some way to submit an arbitrary `BatchRequest` as e.g. JSON, and have it proxied into KV by the node the client has connected to, returning a JSON response. This is pretty crude, but also very general and flexible, and could be used to access all sorts of internal functionality.

Since this is going to be very crude and low-level, mostly for use by internal CRL engineers, I'm not sure that we want to expose this via SQL? It feels like it'd be better to hide this away behind some scary-looking `debug` CLI command, and I think the JSON input/output lends itself better to a CLI interface, but it's not a strongly held opinion.
