### ISSUE TITLE
Memory Budget Exceeded

### ISSUE THREAD

**Issue by sivarao737** [cockroachdb/cockroach#66836]
[Code: 0, SQL State: 53200]  ERROR: windower-limited: memory budget exceeded: 10240 bytes requested, 67102720 currently allocated, 67108864 bytes in budget

Getting this error even if the max-sql memory of 4 gb is present  is present.

Only the query size equal to table size is getting created if it requires extra memory for manipulation for ranking grouping its not allocating from the pool size even if its present

**Comment by sivarao737** [comment]
@gpaul Ben Darnell

**Comment by sivarao737** [comment]
@alex

**Comment by kernfeld-cockroach** [comment]
Welcome @sivarao737, I think we can figure this out! 😁

I assume you saw our [Cache and SQL memory size](https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html#cache-and-sql-memory-size) docs. Two questions:

- What are the specs of the hardware or VM that you're running CockroachDB on?
- What value are you setting `--max-sql-memory` to? By default it is 25% of the total memory. So, if you were leaving that as default, CockroachDB detected that your system had 256 MiB of memory (67,108,864 bytes / 25% = 256 MiB).

**Comment by jordanlewis** [comment]
Closing due to lack of response. @sivarao737 please feel free to re-open if you have further questions or responses.
