### ISSUE TITLE
Please refresh generated file server/admin.pb.gw.go because of grpc-gateway changes

### ISSUE THREAD

**Issue by rse** [cockroachdb/cockroach#6683]
For packaging CockroachDB in OpenPKG I'm trying to not execute the Makefiles and instead rely on the existing generated files (this way less dependencies exists during build-time lile Git, etc). Unfortunately grpc-gateway recently got some updates and now the provided pre-generated server/admin.pb.gw.go source file no longer fits against the latest APIs of grpc-server: 

server/admin.pb.gw.go:242: not enough arguments in call to runtime.HTTPError
server/admin.pb.gw.go:246: not enough arguments in call to forward_Admin_Users_0
server/admin.pb.gw.go:265: not enough arguments in call to runtime.HTTPError
server/admin.pb.gw.go:269: not enough arguments in call to forward_Admin_Databases_0
server/admin.pb.gw.go:288: not enough arguments in call to runtime.HTTPError
server/admin.pb.gw.go:292: not enough arguments in call to forward_Admin_DatabaseDetails_0
server/admin.pb.gw.go:311: not enough arguments in call to runtime.HTTPError
server/admin.pb.gw.go:315: not enough arguments in call to forward_Admin_TableDetails_0
server/admin.pb.gw.go:334: not enough arguments in call to runtime.HTTPError
server/admin.pb.gw.go:338: not enough arguments in call to forward_Admin_Events_0
server/admin.pb.gw.go:338: too many errors

Can you please just refresh the generated server/admin.pb.gw.go file? This would help packaging CockroachDB a lot. Thanks.

**Comment by bdarnell** [comment]
Please just use the makefile - it is the method that we support for building cockroachdb, and it is designed to have minimal dependencies (The makefile doesn't regenerate anything; it's using the files that are checked in to the repo. I think the only system dependency you could avoid by not using the makefile is `git`, which is used to stamp the binary with a version number).

If you still want to avoid the makefile, you should at least synchronize all dependencies with the versions listed in the `GLOCKFILE`. These are the combinations that the code has been tested with; if you don't do this then you'll get build breakages like this one on a regular basis.

**Comment by rse** [comment]
I've now switched to use GLOCKFILE. Thanks for the hint.
