### ISSUE TITLE
sql/parser: unexpected behaivor of `OPERATOR(pg_catalog.~)`

### ISSUE THREAD

**Issue by mikecaat** [cockroachdb/cockroach#66861]
**Describe the problem**

I communicated to CRDB using `psql` which is a postgresql's tool and I encountered the following error.

```
psql=# \d test;
ERROR:  at or near ".": syntax error: unknown binary operator ~
DETAIL:  source SQL:
SELECT c.oid,
  n.nspname,
  c.relname
FROM pg_catalog.pg_class c
     LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
WHERE c.relname OPERATOR(pg_catalog.~) '^(test)$' COLLATE pg_catalog.default
```

**To Reproduce**

The error occurs not only when using `psql` but also using `cockroach sql` tool.

```
root@localhost:26257/defaultdb> SELECT 'test' OPERATOR(pg_catalog.~) '^(test)$';
invalid syntax: statement ignored: at or near "EOF": syntax error: unknown binary operator ~
SQLSTATE: 42601
DETAIL: source SQL:
SELECT 'test' OPERATOR(pg_catalog.~) '^(test)$'
                                               ^
```

And I found that similar commands work well.

```
# another operator(=) works
root@localhost:26257/defaultdb> SELECT 'test' OPERATOR(pg_catalog.=) '^(test)$';
  ?column?
------------
   false
(1 row)

Time: 1ms total (execution 0ms / network 0ms)

# works without "OPERATOR()"
root@localhost:26257/defaultdb> SELECT 'test' ~ '^(test)$';
  ?column?
------------
    true
(1 row)

Time: 0ms total (execution 0ms / network 0ms)
```

**Expected behavior**

My expected behavior was that `OPERATOR(pgcatalog.~)` works as same as `~`.
Is it expected?

**Environment:**
 - CockroachDB version (master branch: c4f134cd)
 - Server OS: macOS BigSur
 - Client app: I only tested with psql, cockroach sql

**Comment by mikecaat** [comment]
I made a prototype patch(#66865). 
The test won't be ok because I found another problem. I'll make another issue...

**Comment by rafiss** [comment]
thanks for finding this, and for submitting a patch!

**Comment by mikecaat** [comment]
Thanks for merging. I'll close this issue.
