### ISSUE TITLE
server: Error decoding updates info: invalid character 'h' looking for beginning of value

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#6687]
```
W160515 09:37:13.122370 server/updates.go:203  Error decoding updates info: invalid character 'h' looking for beginning of value
```

Occasionally shows up when running

```
make build && ( killall -9 cockroach; rm -rf cockroach-data && ./cockroach start --background --alsologtostderr=INFO )
```

Probably a timing issue where we query some endpoint before it's ready.

**Comment by bdarnell** [comment]
The registration cluster is currently having problems, so it's probably that combined with bad error handling on the client side - we don't check the response status code before trying to parse the body.
