### ISSUE TITLE
ui: custom chart page does not load and throws a type error for 21.1.2 and 21.1.3 clusters

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#66890]
First identified by @mikeczabator 

**Describe the problem**

The custom metric page in DB Console does not load for 21.1.2 and 21.1.3 clusters. This does _not_ affect 20.2 clusters 
<img width="1277" alt="Image 2021-06-25 at 12 56 30 PM" src="https://user-images.githubusercontent.com/1474303/123459926-ea7fb680-d5b4-11eb-8ba6-bcbb06224ce0.png">

**To Reproduce**

1. Create a 21.1.3 cluster (for example via roachprod)
2. Run a workload (e.g. movr)
2. Load the DB Console
3. Go to the Advanced Debug page and click on the link to create a custom metric
4. Upon loading that URL, the page becomes inaccessible. Open the devtool console and notice a type error thrown

Epic CRDB-8038

**Comment by thtruo** [comment]
Sanity checking previous versions. I see that the same `TypeError: Cannot read property 'scale' of undefined` issue for 21.1.2 clusters but not for 21.1.1; I'm editing the description and title to reflect that accordingly

**Comment by nvanbenschoten** [comment]
Thanks for the rapid fix! I'm going to reopen until the backport for https://github.com/cockroachdb/cockroach/pull/66897 lands.
