### ISSUE TITLE
sql: DELETE broken during UNIQUE column schema change

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#6691]
DELETE is more generally broken during an index schema change that involves an index that reference a column that is also undergoing a schema change.

```
BEGIN
ALTER TABLE t ADD b INT
ALTER TABLE t ADD CONSTRAINT foo UNIQUE (b)
END
```

While this can be fixed, the complexity arises due to the current choice of using SELECT to read the rows that need to be deleted. SELECT is not allowed to see columns that are undergoing a schema change. DELETE deletes the entire row and all secondary indexes for that row. A secondary index entry deletion for a row involves reading all the column entries comprising that index entry, constructing the key and deleting it. If one of the columns is undergoing a schema change, it cannot be read using SELECT, prohibiting the deletion of the secondary index.

I think it's nice to not break the SELECT cannot read columns/indexes undergoing mutation invariant. If we stick to it, it will mean changing the implementation of DELETE to not use SELECT.

**Comment by vivekmenezes** [comment]
Turns out UPDATE is also broken if you use an index over two columns where one of the columns is undergoing a schema change. Added this case to #6690

**Comment by vivekmenezes** [comment]
I'm working on two PRs to fix this.
1. Ensure that schema changes are executed one at a time instead of in groups with the same mutation ID. For example if there is a column ADD mutation followed by an index ADD where the index references the column, the column is first added before the index moves along with its state machine and gets added. This allows the index to remain in the DELETE_ONLY state while the column is being added.
2. Another PR to either 1. Ignore mutations in the DELETE_ONLY state if they are not the first mutation (already implemented on my machine), or 2. Introduce the ABSENT state for mutations that can exist in the mutation queue, but are completely inactive.

**Comment by dt** [comment]
huh, do we have to give up batching changes? seems like it gives us some properties we like w.r.t. related elements changing state together.

would it make sense to move pending elements into their respective lists (columns, indexes, constraints, etc) and add status info to them there, then just update the whole descriptor at once?

**Comment by vivekmenezes** [comment]
The way it's currently implemented batched changes only work for UNIQUE columns. if you create multiple schema elements in a transaction for instance, they all get their own mutation id which means they get scheduled one at a time.

I think the only reason to do them together is for performance reasons where you might like to add a few columns together, or a few indexes together and run a single backfill for each. We decided to not do that because we wanted to contain the complexity of this mechanism. The general sense I have is users want to apply these schema changes correctly and in a reasonable amount of time. We're kind of still struggling with correctness here. I'd like to not change the protobuf structure without correctness achieved. Applying multiple schema changes together will involve first adding in a lot more tests before making the change.

Actually the more I think about it, perhaps we need a new scheduler element that basically processes all the outstanding schema changes and picks a batch for processing which then get scheduled together, once they are live, the next batch is processed and so on. So we should not need a new protobuf, but more a boolean field suggesting that a mutation has been picked. For now, this scheduler always picks the first element :-)
