### ISSUE TITLE
ui: storage -> read amplification graph should be per-node

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#66931]
Read amplification is displayed on the Storage dashboard. This metric is much more interesting on a per-node basis than as an average. On a per-node basis, this metric can be used to help detect unhealthy nodes.

Epic CRDB-8313

**Comment by nvanbenschoten** [comment]
Would this change be possible to backport to v20.2 and v21.1?

**Comment by thtruo** [comment]
We should also update our Grafana definitions as part of this DB Console metrics change https://github.com/cockroachdb/cockroach/blob/master/monitoring/grafana-dashboards/storage.json#L670

**Comment by nvanbenschoten** [comment]
This was addressed by https://github.com/cockroachdb/cockroach/pull/73591. I forgot I had filed this issue.
