### ISSUE TITLE
bazel: make bazel-generate completely obliterates my repo

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#66945]
**Describe the problem**

This just happened for the second time. On a clean checkout, I ran `make bazel-generate` which fails and suddenly my cockroach repo's files are *replaced* with random stuff from some bazel repo. For example, there's now a `README.rst` file in the repo root which reads

```
$ head -n 5 README.rst
Go rules for Bazel_
=====================

.. Links to external sites and pages
.. _//tests/core/cross: https://github.com/bazelbuild/rules_go/blob/master/tests/core/cross/BUILD.bazel
```

It has completely replaced the contents, I think. In particular, it nuked my `.idea` folder so my Goland settings are gone.

See the log of that operation here: https://gist.github.com/tbg/1d26316dddb92953887fe9814d7fd9c6

**To Reproduce**

git checkout mybranch
git rebase -i origin/master --exec 'make bazel-generate'
boom

Epic CRDB-8036

**Comment by tbg** [comment]
I ran `git reset --hard`, deleted the untracked files, recreated my `.idea` directory (luckily I think the IDE which was running subsequently wrote the settings back in), and ran `bazel test --expunge`. This seems to have fixed it, for now.

But I'd like to know how ~something ends up replacing my whole repo root with unrelated files. Is there a janky shell-script inside of `make bazel-generate` that could wreak that kind of havoc when an error pops up in the right place?

**Comment by rickystewart** [comment]
What OS are you on? Is your workspace or home directory mounted on a special file system (e.g. NFS)? Anything else distinctive about your environment that I need to know?

> Is there a janky shell-script inside of make bazel-generate that could wreak that kind of havoc when an error pops up in the right place?

`make bazel-generate` does one thing -- it runs `./build/bazelutil/bazel-generate.sh`. I did *write* the script, so maybe I'm too biased to speak to its jankiness, but the script does begin with `set -e` and doesn't have any variables/pipes/funny stuff that might lead to an accidental `rm -rf *` as far as I can tell.

Evidently your `make bazel-generate` failed during the first command, which is in invocation of `bazel run :gazelle`:

```
+ bazel run //:gazelle -- update-repos -from_file=go.mod -build_file_proto_mode=disable_global -to_macro=DEPS.bzl%go_deps -prune=true
Starting local Bazel server and connecting to it...
[1;31mERROR: [22;39mno such package 'external': Error encountered while dealing with the WORKSPACE file: in /home/tobias/.cache/bazel/_bazel_tobias/6e5ce29cb
3e014d96edb4813c6e15043/external/bazel_gazelle/deps.bzl: in /home/tobias/.cache/bazel/_bazel_tobias/6e5ce29cb3e014d96edb4813c6e15043/external/ba
zel_gazelle/internal/go_repository_tools.bzl: Every .bzl file must have a corresponding package, but '@io_bazel_rules_go//go/private:common.bzl'
 does not have one. Please create a BUILD file in the same or any parent directory. Note that this BUILD file does not need to do anything excep
t exist.
```

The bug doesn't seem to have anything to do with `gazelle` itself -- the bug would be in Bazel itself, rather. Nothing's turned up from Googling, though.

**Comment by tbg** [comment]
I'm on linux, and it's all stock:

```
tobias@td:~/go/src/github.com/cockroachdb/cockroach$ df -h .
Filesystem                 Size  Used Avail Use% Mounted on
/dev/mapper/vgubuntu-root  914G  170G  699G  20% /
tobias@td:~/go/src/github.com/cockroachdb/cockroach$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

I'll report back if this inevitably happens again. I think both previous occurrences happened during a `git rebase -i origin/master --exec 'make bazel-generate', but that doesn't always cause the problem to appear.

**Comment by irfansharif** [comment]
Going to close this as stale (I don't think we've seen it since, right?). Also, we're reworking most of bazel gen in https://github.com/cockroachdb/cockroach/pull/76355 anyway.

**Comment by tbg** [comment]
I've learned not to do the dangerous thing (`git rebase -i --exec 'make bazel-generate'`), but I'm ok with closing. I will run that again eventually and I can reopen the issue if needed.
