### ISSUE TITLE
investigate: kv roachtest performance drop on 20 May

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#66961]
**Describe the problem**

On May 20th the following tests (all KV tests with SPLIT=0):

- [gce:kv0/enc=false/nodes=3/cpu=32/splt=0](https://roachperf.crdb.dev/?filter=&view=kv0%2Fenc%3Dfalse%2Fnodes%3D3%2Fcpu%3D32%2Fsplt%3D0&tab=gce)
- [gce:kv0/enc=false/nodes=3/splt=0](https://roachperf.crdb.dev/?filter=&view=kv0%2Fenc%3Dfalse%2Fnodes%3D3%2Fsplt%3D0&tab=gce)
- [gce:kv95/enc=false/nodes=3/splt=0](https://roachperf.crdb.dev/?filter=&view=kv95%2Fenc%3Dfalse%2Fnodes%3D3%2Fsplt%3D0&tab=gce)
- [gce:kv95/enc=false/nodes=3/cpu=32/splt=0](https://roachperf.crdb.dev/?filter=&view=kv95%2Fenc%3Dfalse%2Fnodes%3D3%2Fcpu%3D32%2Fsplt%3D0&tab=gce)

- [aws:kv0/enc=false/nodes=3/splt=0](https://roachperf.crdb.dev/?filter=&view=kv0%2Fenc%3Dfalse%2Fnodes%3D3%2Fsplt%3D0&tab=aws)
- [aws:kv0/enc=false/nodes=3/cpu=32/splt=0](https://roachperf.crdb.dev/?filter=&view=kv0%2Fenc%3Dfalse%2Fnodes%3D3%2Fcpu%3D32%2Fsplt%3D0&tab=aws)
- [aws:kv95/enc=false/nodes=3/splt=0](https://roachperf.crdb.dev/?filter=&view=kv95%2Fenc%3Dfalse%2Fnodes%3D3%2Fsplt%3D0&tab=aws)
- [aws:kv95/enc=false/nodes=3/cpu=32/splt=0](https://roachperf.crdb.dev/?filter=&view=kv95%2Fenc%3Dfalse%2Fnodes%3D3%2Fcpu%3D32%2Fsplt%3D0&tab=aws)

started performing substantially worse. 

This coincides with the merging of the following PRs 

- [May 19th](https://github.com/cockroachdb/cockroach/pulls?q=is%3Apr+is%3Amerged+merged%3A2021-05-19+base%3Amaster) 
- [May 20th](https://github.com/cockroachdb/cockroach/pulls?q=is%3Apr+is%3Amerged+merged%3A2021-05-20+base%3Amaster)

It appears that the potential cause may be:

- https://github.com/cockroachdb/cockroach/pull/58670

**Comment by ajwerner** [comment]
The `splt=0` tests tests the single-range performance combined with load-based splitting. New locking which might cause increased mutex contention is the sort of change which I'd look for here.

**Comment by stevendanna** [comment]
https://github.com/cockroachdb/cockroach/pull/58670 is looking more likely:

Running `kv0/enc=false/nodes=3/cpu=32/splt=0`

On cockroachdb/cockroach@1059834b38 (which is 66336f2bdf^1):

```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0       22280746        37134.5      5.2      5.0      8.9     11.5    184.5  write
```

On cockroachdb/cockroach@66336f2bdf

```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0        9921404        16535.6     11.6     11.5     17.8     21.0     54.5  write
```

**Comment by sumeerbhola** [comment]
I believe kv0 has no reads, so should not use optimistic latching.
@ajwerner could you clarify what command we use for splits and what latches we acquire during that process?

**Comment by ajwerner** [comment]
> @ajwerner could you clarify what command we use for splits and what latches we acquire during that process?

With the idea being that we've now somehow made the splitting process, which may happen during the test, slower? This test differs from regular KV0 in that it does not pre-split the table. The split itself, IIUC, only touches the descriptor key and does not latch the keyspace at all.

**Comment by stevendanna** [comment]
ycsb/F/nodes=3/cpu32 was also impacted, but has recovered in recent days:


[gce:ycsb/F/nodes=3/cpu=32](https://roachperf.crdb.dev/?filter=&view=ycsb%2FF%2Fnodes%3D3%2Fcpu%3D32&tab=gce)
[aws:ycsb/F/nodes=3/cpu=32](https://roachperf.crdb.dev/?filter=&view=ycsb%2FF%2Fnodes%3D3%2Fcpu%3D32&tab=aws)

Before:
```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0        4654212         7757.0      6.5      1.0     22.0    151.0   3355.4  read

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0        4652269         7753.8     12.0      8.9     19.9     96.5   4831.8  readModifyWrite

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
600.0s        0        9306481        15510.9      9.3      5.8     21.0    134.2   4831.8
```

After:
```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0        3381702         5636.2     10.8      1.0     15.2    302.0   4026.5  read

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0        3381226         5635.4     14.7      8.1     18.9    218.1   5100.3  readModifyWrite

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
  600.0s        0        6762928        11271.5     12.8      5.2     17.8    285.2   5100.3  
```

**Comment by tbg** [comment]
The split does latch the full keyspace.

https://github.com/cockroachdb/cockroach/blob/1ac67a16817238f601f0b49bd7a67ad3c1531505/pkg/kv/kvserver/batcheval/cmd_end_transaction.go#L99-L117

**Comment by sumeerbhola** [comment]
I'm running `kv0/enc=false/nodes=3/splt=0` (https://roachperf.crdb.dev/?filter=&view=kv0%2Fenc%3Dfalse%2Fnodes%3D3%2Fsplt%3D0&tab=aws) on master with some instrumentation. It is doing ~21K ops/s and there are only 700 optimistic request evaluations total over 5min, and all of them succeeded in the first attempt. I didn't spot anything in the mutex profile (over 15s, screenshot below) or cpu profile. The cpu load is very uneven, I guess because of the lack of splits.
<img width="1348" alt="Screen Shot 2021-06-30 at 2 54 18 PM" src="https://user-images.githubusercontent.com/54990988/124016537-c4428800-d9b3-11eb-9932-03925bc1c5e5.png">
<img width="1559" alt="Screen Shot 2021-06-30 at 2 57 55 PM" src="https://user-images.githubusercontent.com/54990988/124016550-c86ea580-d9b3-11eb-9450-05e346292de4.png">

**Comment by sumeerbhola** [comment]
- I'm unable to get the higher throughput using https://github.com/cockroachdb/cockroach/commit/1059834b38, which immediately precedes the latching change for both `kv0/enc=false/nodes=3/splt=0` and `kv0/enc=false/nodes=3/cpu=32/splt=0`. Neither workloads has significant optimistic latching, as I mentioned in my previous comment, and the optimistic latching that is happening is never needing retries.
- The cpu utilization for `kv0/enc=false/nodes=3/cpu=32/splt=0` is poor. See attached screenshot. That would explain the steep drop.
- @stevendanna can you try to reproduce the numbers you observed and if you can, can you capture the cpu utilization over the whole run, and a cpu profile. I am curious whether some rebalancing happens that pushes up the throughput sometime during the run.
<img width="1336" alt="Screen Shot 2021-06-30 at 5 43 32 PM" src="https://user-images.githubusercontent.com/54990988/124036211-a719b380-d9cb-11eb-820c-b5513ee3c8ef.png">

**Comment by stevendanna** [comment]
@sumeerbhola I can get that going, but given the discussion here, I wonder if the entire effect of this is actually just this which means that this test previously would have done load-based rebalancing and now doesn't on master.

https://github.com/cockroachdb/cockroach/pull/58670/files#diff-ddbbcf86957878439b5f7f74da04c2054b70c5d1a8643521d08eeafbcaae4d70R69-R77

**Comment by sumeerbhola** [comment]
> I wonder if the entire effect of this is actually the below roachtest change that was included in the pull request

argh, I totally forgot about that (that part was written in Jan). Thanks for noticing!

**Comment by ajwerner** [comment]
I can add some context that this `splt=0` test was added, at least in part, to tune the QPS thresholds for load-based splitting. Originally we had it an order of magnitude lower and it would lead to over-splitting.

**Comment by stevendanna** [comment]
If y'all don't mind yet another option: https://github.com/cockroachdb/cockroach/pull/67107

**Comment by sumeerbhola** [comment]
@stevendanna thanks for fixing this while I was OOO
