### ISSUE TITLE
bazel: consider better patterns for mock generation

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#67010]
In #66910 I added a bunch of interface mocks using gomock/mockgen. The Bazel build integration got a bit messy because of dependency handling, we should revisit this and come up with a best practice pattern for generating mocks.

/cc @cockroachdb/dev-inf @irfansharif

**Comment by irfansharif** [comment]
yea, let's do it. Would be great to iron out precedence if we're looking to continue lean on mocks.

**Comment by erikgrinaker** [comment]
Yeah, I'd like to push for using mocks way more that we do now -- we tend to use integration tests when mocked unit tests would be faster, more comprehensive, and more reliable.
