### ISSUE TITLE
sql: move `system.zones` into the tenant keyspace

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#67014]
**Is your feature request related to a problem? Please describe.**

Part of #66348. We need to ad`system.zones` for each tenant, and massage the existing zone config generation code to work off of descriptor IDs (instead of SystemTenantObjectIDs that it does today).

**Comment by ajwerner** [comment]
> into the tenant keyspace and massage the existing zone config generation code to work on descriptor IDs (instead of system tenant object IDs as it does today).

I feel like this is a bit misleading. Is there really anything to be done? What is an `object ID` if not just a `descriptor ID` (plus some fake placeholder IDs)? What makes anything `system tenant`?

**Comment by arulajmani** [comment]
> Is there really anything to be done? What is an object ID if not just a descriptor ID (plus some fake placeholder IDs)? What makes anything system tenant?

I was hoping to get rid of the concept of: https://github.com/cockroachdb/cockroach/blob/15ee387449e5c9405f284c6c423a19dee0fc5d00/pkg/config/system.go#L42 once `system.zones` moves into the tenant keyspace. It's merely a wrapper around descriptor IDs, so there isn't much here other than cleaning up all places that convert descriptor IDs to this type.

**Comment by irfansharif** [comment]
#67323.
