### ISSUE TITLE
sql/catalog: add memory monitoring on descriptors

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#67049]
**Is your feature request related to a problem? Please describe.**

There are several sets of descriptors which badly need memory monitoring:

* The descriptors a session reads from the store (which is frequently all of them).
* The leased descriptors.
* The `hydratedcache` cached descriptors.

**Describe the solution you'd like**

We should plumb through a memory monitor. I don't quite know what to do about the shared caches

Jira issue: CRDB-8340

**Comment by postamar** [comment]
@ajwerner I think we can close this, please do reopen if I'm wrong.
