### ISSUE TITLE
server: bad messages about new beta version

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#6706]
I'm starting a version of the server from a few days ago, and I get badly formatted messages in the log about a new beta version. And I get two of them!

```
I160516 13:50:21.082105 server/updates.go:208  A new version is available: %s
	%sbeta-20160505https://www.cockroachlabs.com/docs/beta-20160505.html
I160516 13:50:21.082123 server/updates.go:208  A new version is available: %s
	%sbeta-20160512https://www.cockroachlabs.com/docs/beta-20160512.html
```

I'm also pretty impressed that these messages exist.

**Comment by mberhault** [comment]
annoying that `go vet` can't be told about `log.Print(f)` to perform the same checks as `fmt.Print(f)`

**Comment by tamird** [comment]
`vet` does take a `-printfuncs` argument
