### ISSUE TITLE
acceptance: TestClusterRecovery flaky

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#6708]
```
--- FAIL: TestClusterRecovery (43.82s)
	cluster.go:74: client/rpc_sender.go:58: roachpb.Batch RPC failed: context deadline exceeded
```

https://circleci.com/gh/cockroachdb/cockroach/17850

**Comment by vivekmenezes** [comment]
I'm closing this for now because I think this timeout is pretty harmless. Essentially the cluster consistency check timed out. If we see this again I can investigate further
