### ISSUE TITLE
build: Make issues for these bazel-related needs

### ISSUE THREAD

**Issue by jlinder** [cockroachdb/cockroach#67086]
Make issues for:

- [x] each TC build config in GitHub CI for it to be duplicated under Bazel GitHub CI. The new issues will replace https://github.com/cockroachdb/cockroach/issues/57586
- [x] duplicating publish bleeding edge
- [x] switching to bazel for nightly tests
- [x] the other build configs that are triggered by merge to `branch`
- [x] duplicating / transitioning all the release steps to use bazel
- [x] all the things in the makefile that need to be supported in bazel
- [x] all the things in the makefile that we want to duplicate in `dev`
- [x] Documentation for how to use dev, bazel, etc. for engineers and external contributors
- [x] More around what we want for dev and the UI experience for developers
- [x] Are the capabilities from the makefile (like from `make help`) sufficiently covered?
- [x] Move dev back into the main cockroach repo

Epic CRDB-10447

Jira issue: CRDB-8356

**Comment by knz** [comment]
I think all these items are done now? So we can close the issue.
