### ISSUE TITLE
Comment error

### ISSUE THREAD

**Issue by benlatern** [cockroachdb/cockroach#67103]
Seems there's a Grammatical errors
##pkg/kv/kvserver/replica_proposal.go 
##line 91
`	
// applied is set when the a command finishes application. It is used to

// avoid reproposing a failed proposal if an earlier version of the same

// proposal succeeded in applying.

applied bool
`
applied is set when "the a" command finishes application.

**Comment by knz** [comment]
Ironically you also made two grammatical errors in the text of your issue description.

Did you file this issue because you're being evaluated to "contribute to an open source project"? If so, there are better things you could be doing.
