### ISSUE TITLE
protectedts: provide mechanism to disable subsystem

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#67118]
**Is your feature request related to a problem? Please describe.**

There have been bugs in the implementation of protected timestamp (recent deadlock in #66760). Also, the limits can be painful and can prevent backups. The limit problems can be solved by increasing the limits but the deadlock can't. We don't know what we'll find in the future. The subsystem, while important, is about ensuring work completes in the face of GC. If we opt out of protecting data, nothing catastropic should happen: backups, changefeeds, or schema changes may fail, but that's okay.

**Describe the solution you'd like**

Add a knob to turn off protected timestamps altogether. Perhaps just for backups or changefeeds.

**Describe alternatives you've considered**

Not adding this knob?

Jira issue: CRDB-8372

**Comment by miretskiy** [comment]
Given how critical PTS system becoming (used in cdc, backups, imports, c2c, I'm sure somewhere else), do we think that
we'll add a mechanism to disable it?

@adityamaru  -- consider closing this issue if we are not going to work on that.

**Comment by adityamaru** [comment]
I don't think there are any plans to work on this. We have gotten rid of verification and so PTS is a less complicated/error-prone subsystem than it used to be. Additionally, we're now piggybacking on span config reconciliation to do the actual protecting so whatever knobs we add would probably be around the disabling reconciliation. I believe we already have knobs to control the rate/disable reconciliation. I think it's safe to close this but folks should reopen if they disagree!
