### ISSUE TITLE
backupccl: remove fields that scale O(cluster data size) from backup manifest

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#67128]
Along with the SSTs which contain the data being backed up, backups also store a manifest file. The manifest file is a serialized protobuf that stores metadata about the backup. Notably, it is a [single protobuf message](https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/backupccl/backup.proto#L42) and is held in memory in its entirety. As larger and larger clusters run backups, the BackupManifest also increases in size since some of the fields on the backup manifest are repeated fields that scale with cluster size.

These fields are a risk to the stability of the cluster since they can grow uncontrolled. We've previously seen issues when storing table stats in the backup manifest, which applied a lot of memory pressure on the cluster. These memories have been alleviated somewhat by moving some of the larger fields in their own file and compressing the files... but the underlying problem still festers.

Instead of these repeated fields, the backup manifest should be of constant size. We already have a mechanism for storing and reading large amounts of data in chunks -- SSTs! These fields should be stored as SSTs which can each be read as needed by backup to avoid storing O(cluster size) data in memory. These SSTs can have a fixed name, so backup knows where to go looking for them.

Fields to consider:
- [ ] Spans
- [ ] Introduced spans
- [ ] Descriptor changes
- [ ] Files
- [ ] Descriptors
- [ ] Tenants
- [ ] CompleteDBs

An important consideration here is backwards compatibility. We still want to be able to read backups with all of these fields on backups generated by older versions. But the sooner that we start writing the new format, the better.

Concrete steps:
- [ ] https://github.com/cockroachdb/cockroach/issues/68063
- [x] https://github.com/cockroachdb/cockroach/issues/68064

Epic CRDB-10127

Jira issue: CRDB-8374

**Comment by shermanCRL** [comment]
See prototype https://github.com/cockroachdb/cockroach/pull/68891
