### ISSUE TITLE
server: Authentication for admin API

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#6713]
The admin API endpoints defined in `server/admin.{proto,go}` are not currently authenticated. This was OK when they were just exposing basic metadata about the cluster, but now that we are adding more potentially-disruptive commands there (notably Drain and ClusterFreeze) we need to restrict these commands to authorized users. This may ideally involve introducing a new class of permissions - an admin (or automated provisioning tool) should be able to drain nodes without root-level data access.

**Comment by spencerkimball** [comment]
This seems like a big deal. We need to assign this to someone. I'm assigning @tamird for now. @tamird, could you either do this, reassign it, or argue that the 1.0 milestone doesn't apply?

**Comment by tamird** [comment]
Moving to 1.1 since this is a big change, and also reassigning to @mberhault since the security model is undergoing some evolution.

**Comment by mberhault** [comment]
Reassigning to @mrtracy who has been working on this.

**Comment by petermattis** [comment]
@mrtracy Is there anything left to do here?

**Comment by mrtracy** [comment]
The authentication mechanism is fully complete on the backend, but there is no way to turn it on for a server (as there is no UI available for a user to complete the authentication process).  I've opened up #18206 which is more specific to that remaining problem.
