### ISSUE TITLE
Out of space no longer logged when a node runs out of space

### ISSUE THREAD

**Issue by RichardoC** [cockroachdb/cockroach#67187]
**Describe the problem**

Since upgrading to docker image cockroachdb/cockroach:v21.1.3 from cockroachdb/cockroach:v20.2.1 cockroach will not log to stderr that it had run out of space before exiting upon a restart.

**To Reproduce**

Run  cockroachdb/cockroach:v21.1.3 with entrypoint 
`cockroach start-single-node --store /storage/ --insecure --log="sinks: {stderr: {no-color: true, channels: [ALL]}, file-groups: {default: {channels: [All]}}}"`
Where /storage/ points to a volume with no space left

See that nothing is logged to stderr

**Expected behavior**
Run  cockroachdb/cockroach:v20.2.1 with entrypoint 
`cockroach start-single-node --store /storage/ --insecure`
Where /storage/ points to a volume with no space left

Logs from cockroachdb/cockroach:v20.2.1

E210702 15:35:36.915758 1 util/log/exit_override.go:59 ⋮ logging error: write ‹/storage/logs/cockroach.database-service-559d8ccd44-9xsz7.unknownuser.2021-07-02T15_34_39Z.000001.log›: no space left on device

**Environment:**
 - CockroachDB version 
 docker image cockroachdb/cockroach:v21.1.3
 - Server OS: 
 Ubuntu 18.04
 - Client app [e.g. `cockroach sql`, JDBC, ...]
N/A

**Additional context**
What was the impact?
Makes it more difficult to work out why a cockroach node won't start.

Jira issue: CRDB-8417

**Comment by rafiss** [comment]
Thanks for reporting this @RichardoC ! 

cc @knz for triaging

**Comment by RichardoC** [comment]
Hi there, any updates?

**Comment by knz** [comment]
Not yet, but thanks for the reminder.

**Comment by jtsiros** [comment]
Right now, we are targeting this for after the new year given the December milestone priorities. Please ping @mwang1026 if this becomes urgent.
