### ISSUE TITLE
docker - failed to initialize context: invalid or empty engines specification

### ISSUE THREAD

**Issue by cloudmode** [cockroachdb/cockroach#672]
updated to the latest docker image, per launch instructions in documentation, once launched:

root@2b41ddc875e2:/cockroach# ./cockroach init -stores ssd="$(mktemp -d /tmp/dbXXX)"
I0416 13:41:26.011931      49 context.go:141] initialized 1 storage engine(s)
I0416 13:41:26.014549      49 rocksdb.go:87] opening rocksdb instance at "/tmp/db2xL"
I0416 13:41:26.225446      49 rocksdb.go:108] closing rocksdb instance at "/tmp/db2xL"
I0416 13:41:26.226022      49 start.go:109] cockroach cluster 52d9bc13-2da5-4355-9391-1c83db4f47cc has been initialized
I0416 13:41:26.226144      49 start.go:114] to start the cluster, run "cockroach start"
root@2b41ddc875e2:/cockroach# cockroach start
bash: cockroach: command not found
root@2b41ddc875e2:/cockroach# ./cockroach start
I0416 13:41:41.450285      57 start.go:134] build Vers: go1.4.2
I0416 13:41:41.462615      57 start.go:135] build Tag:  alpha-1637-g9086700
I0416 13:41:41.462678      57 start.go:136] build Time: 2015/04/16 12:51:32
I0416 13:41:41.462702      57 start.go:137] build Deps: code.google.com/p/go-commander:df033a4b379cd723ef7408b881c1e092cd943831 code.google.com/p/go-uuid:35bc42037350f0078e3c974c6ea690f1926603ab code.google.com/p/snappy-go:8850bd446ad6f18a271a08aae26bdf85bdf87c7f github.com/biogo/store:cb1ae010c5c75b7ce4f5c5d0ef92defcafdfdce4 github.com/cockroachdb/c-protobuf:9e8dac59ca2a3fc82cd0665ad32b1a36f3df40b8 github.com/cockroachdb/c-rocksdb:72de025ca13dd4ab2dce63e8e19c6a59b8388ffd github.com/cockroachdb/c-snappy:af73b00e85e6f0e3c1fcc51f73f1d036df1e99ff github.com/cockroachdb/cockroach:90867000a8f3484fc7f127bfe4adad60a18ebaab github.com/coreos/etcd:e5f2f401450b56947e231336f9e8350059428036 github.com/elazarl/go-bindata-assetfs:bea323321994103859d60197d229f1a94699dde3 github.com/gogo/protobuf:bc946d07d1016848dfd2507f90f0859c9471681e github.com/golang/glog:44145f04b68cf362d9c4df2182967c2275eaefed gopkg.in/yaml.v1:9f9df34309c04878acc86042b16630b0f696e1de
E0416 13:41:41.462863      57 start.go:142] failed to initialize context: context.go:125: invalid or empty engines specification ""
root@2b41ddc875e2:/cockroach#

**Comment by tschottdorf** [comment]
You'll need to pass the same parameters to `start` as you did to `init`:
`./cockroach init -stores ssd="/the/path/that/it/used/previously"`

We're currently reworking the start and init commands (init used to auto-start), but we'll have it updated shortly. Sorry about that. :)

**Comment by cloudmode** [comment]
I just tried that. Same error message.

root@07ab195c9c40:/cockroach# ./cockroach init -stores ssd="$(mktemp -d /tmp/dbXXX)"
I0416 13:54:08.330582      21 context.go:141] initialized 1 storage engine(s)
I0416 13:54:08.333164      21 rocksdb.go:87] opening rocksdb instance at "/tmp/dbZhP"
I0416 13:54:08.547687      21 rocksdb.go:108] closing rocksdb instance at "/tmp/dbZhP"
I0416 13:54:08.548069      21 start.go:109] cockroach cluster e5c5e91c-519b-4162-9a62-1592f89bd46a has been initialized
I0416 13:54:08.548208      21 start.go:114] to start the cluster, run "cockroach start"
root@07ab195c9c40:/cockroach# ./cockroach start
I0416 13:54:21.086361      28 start.go:134] build Vers: go1.4.2
I0416 13:54:21.089554      28 start.go:135] build Tag:  alpha-1637-g9086700
I0416 13:54:21.090191      28 start.go:136] build Time: 2015/04/16 12:51:32
I0416 13:54:21.090215      28 start.go:137] build Deps: code.google.com/p/go-commander:df033a4b379cd723ef7408b881c1e092cd943831 code.google.com/p/go-uuid:35bc42037350f0078e3c974c6ea690f1926603ab code.google.com/p/snappy-go:8850bd446ad6f18a271a08aae26bdf85bdf87c7f github.com/biogo/store:cb1ae010c5c75b7ce4f5c5d0ef92defcafdfdce4 github.com/cockroachdb/c-protobuf:9e8dac59ca2a3fc82cd0665ad32b1a36f3df40b8 github.com/cockroachdb/c-rocksdb:72de025ca13dd4ab2dce63e8e19c6a59b8388ffd github.com/cockroachdb/c-snappy:af73b00e85e6f0e3c1fcc51f73f1d036df1e99ff github.com/cockroachdb/cockroach:90867000a8f3484fc7f127bfe4adad60a18ebaab github.com/coreos/etcd:e5f2f401450b56947e231336f9e8350059428036 github.com/elazarl/go-bindata-assetfs:bea323321994103859d60197d229f1a94699dde3 github.com/gogo/protobuf:bc946d07d1016848dfd2507f90f0859c9471681e github.com/golang/glog:44145f04b68cf362d9c4df2182967c2275eaefed gopkg.in/yaml.v1:9f9df34309c04878acc86042b16630b0f696e1de
E0416 13:54:21.090464      28 start.go:142] failed to initialize context: context.go:125: invalid or empty engines specification ""

**Comment by cloudmode** [comment]
is it that the -start uses the mktemp command, and then -init needs to use the directory created in the -start command?

**Comment by tschottdorf** [comment]
sorry, I wrote `init` in my command when I meant `start`.

Just do this:
```
DIR=$(mktemp -d /tmp/dbXXX)
./cockroach init -stores ssd="$DIR"
./cockroach start -stores ssd="$DIR"
```

**Comment by cloudmode** [comment]
it's getting further....

root@b2d25d776a2f:/cockroach# DIR=$(mktemp -d /tmp/dbXXX)
root@b2d25d776a2f:/cockroach# ./cockroach init -stores ssd="$DIR"
I0416 14:06:18.897853      10 context.go:141] initialized 1 storage engine(s)
I0416 14:06:18.900439      10 rocksdb.go:87] opening rocksdb instance at "/tmp/dbsKR"
I0416 14:06:19.112005      10 rocksdb.go:108] closing rocksdb instance at "/tmp/dbsKR"
I0416 14:06:19.113625      10 start.go:109] cockroach cluster 3236bc54-2b2c-4645-a133-82725341880f has been initialized
I0416 14:06:19.113662      10 start.go:114] to start the cluster, run "cockroach start"
root@b2d25d776a2f:/cockroach# ./cockroach start -stores ssd="$DIR"
I0416 14:06:27.554475      18 start.go:134] build Vers: go1.4.2
I0416 14:06:27.556525      18 start.go:135] build Tag:  alpha-1637-g9086700
I0416 14:06:27.557415      18 start.go:136] build Time: 2015/04/16 12:51:32
I0416 14:06:27.557442      18 start.go:137] build Deps: code.google.com/p/go-commander:df033a4b379cd723ef7408b881c1e092cd943831 code.google.com/p/go-uuid:35bc42037350f0078e3c974c6ea690f1926603ab code.google.com/p/snappy-go:8850bd446ad6f18a271a08aae26bdf85bdf87c7f github.com/biogo/store:cb1ae010c5c75b7ce4f5c5d0ef92defcafdfdce4 github.com/cockroachdb/c-protobuf:9e8dac59ca2a3fc82cd0665ad32b1a36f3df40b8 github.com/cockroachdb/c-rocksdb:72de025ca13dd4ab2dce63e8e19c6a59b8388ffd github.com/cockroachdb/c-snappy:af73b00e85e6f0e3c1fcc51f73f1d036df1e99ff github.com/cockroachdb/cockroach:90867000a8f3484fc7f127bfe4adad60a18ebaab github.com/coreos/etcd:e5f2f401450b56947e231336f9e8350059428036 github.com/elazarl/go-bindata-assetfs:bea323321994103859d60197d229f1a94699dde3 github.com/gogo/protobuf:bc946d07d1016848dfd2507f90f0859c9471681e github.com/golang/glog:44145f04b68cf362d9c4df2182967c2275eaefed gopkg.in/yaml.v1:9f9df34309c04878acc86042b16630b0f696e1de
I0416 14:06:27.559509      18 context.go:141] initialized 1 storage engine(s)
I0416 14:06:27.559603      18 start.go:146] starting cockroach cluster
W0416 14:06:27.559973      18 tls.go:142] listening via tcp to b2d25d776a2f:8080 without TLS
I0416 14:06:27.560308      18 rocksdb.go:87] opening rocksdb instance at "/tmp/dbsKR"
F0416 14:06:27.560387      18 gossip.go:299] no hosts specified for gossip network (use -gossip)
goroutine 12 [running]:
github.com/golang/glog.stacks(0x15dfc00, 0x0, 0x0, 0x0)
	/go/src/github.com/golang/glog/glog.go:766 +0xcd
github.com/golang/glog.(*loggingT).output(0x15bcb60, 0xc200000003, 0xc2080580c0, 0x12d2905, 0x9, 0x12b, 0x0)
	/go/src/github.com/golang/glog/glog.go:717 +0x283
github.com/golang/glog.(*loggingT).printf(0x15bcb60, 0x3, 0xff5ad0, 0x33, 0x0, 0x0, 0x0)
	/go/src/github.com/golang/glog/glog.go:655 +0x1ef
github.com/golang/glog.Fatalf(0xff5ad0, 0x33, 0x0, 0x0, 0x0)
	/go/src/github.com/golang/glog/glog.go:1145 +0x64
github.com/cockroachdb/cockroach/gossip.(*Gossip).initializeBootstrapAddresses(0xc20800cbd0)
	/go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:299 +0x71
github.com/cockroachdb/cockroach/gossip.func·004()
	/go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:350 +0x6d
github.com/cockroachdb/cockroach/util.func·004()
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:71 +0x51
created by github.com/cockroachdb/cockroach/util.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:72 +0xe3

**Comment by tschottdorf** [comment]
try adding `-gossip $(hostname):8080`. We must have had a very recent change that changed the behavior.

**Comment by cloudmode** [comment]
That's better, but hostname is b2d25d776a2f, and cli won't talk to that. That's some kind of docker mapping I think.

**Comment by tschottdorf** [comment]
You need to use the client inside the Docker image as well, or forward the port to your host vm. If you have cockroach compiled outside, you could just not use Docker (i.e. do everything on your outside shell).

**Comment by cloudmode** [comment]
Understood. I am trying to use the image inside docker. Here's the result from a simple put command:

root@b2d25d776a2f:/cockroach# ./cockroach put a 1 b 2 c 3 d 4
W0416 14:32:06.873989      98 http_sender.go:121] failed to send HTTP request or read its response: http_sender.go:158: http client was closed: Post http://:8080/kv/db/Batch: dial tcp :8080: connection refused
I0416 14:32:06.876035      98 retry.go:101] http Batch failed; retrying in 50ms
W0416 14:32:06.932977      98 http_sender.go:121] failed to send HTTP request or read its response: http_sender.go:158: http client was closed: Post http://:8080/kv/db/Batch: dial tcp :8080: connection refused
I0416 14:32:06.933082      98 retry.go:101] http Batch failed; retrying in 100ms
W0416 14:32:07.043288      98 http_sender.go:121] failed to send HTTP request or read its response: http_sender.go:158: http client was closed: Post http://:8080/kv/db/Batch: dial tcp :8080: connection refused
I0416 14:32:07.043429      98 retry.go:101] http Batch failed; retrying in 200ms
W0416 14:32:07.249664      98 http_sender.go:121] failed to send HTTP request or read its response: http_sender.go:158: http client was closed: Post http://:8080/kv/db/Batch: dial tcp :8080: connection refused
I0416 14:32:07.249767      98 retry.go:101] http Batch failed; retrying in 400ms
W0416 14:32:07.669290      98 http_sender.go:121] failed to send HTTP request or read its response: http_sender.go:158: http client was closed: Post http://:8080/kv/db/Batch: dial tcp :8080: connection refused
I0416 14:32:07.670360      98 retry.go:101] http Batch failed; retrying in 800ms
W0416 14:32:08.517270      98 http_sender.go:121] failed to send HTTP request or read its response: http_sender.go:158: http client was closed: Post http://:8080/kv/db/Batch: dial tcp :8080: connection refused
I0416 14:32:08.517422      98 retry.go:101] http Batch failed; retrying in 1.6s
W0416 14:32:10.351653      98 http_sender.go:121] failed to send HTTP request or read its response: http_sender.go:158: http client was closed: Post http://:8080/kv/db/Batch: dial tcp :8080: connection refused
I0416 14:32:10.351783      98 retry.go:101] http Batch failed; retrying in 3.2s

I'm trying the outside docker approach next.

**Comment by tschottdorf** [comment]
Use `./cockroach put -addr $(hostname):8080 a b`.
Sorry this is such a mess - we're cleaning it up in #665 at the moment.

**Comment by cloudmode** [comment]
cool. that worked. trying client now. 

No need to apologize, I'm out here on the edge with you guys.

**Comment by tschottdorf** [comment]
You should be all good to go now!
