### ISSUE TITLE
WARNING: disk slowness detected: unable to sync log files within 10s

### ISSUE THREAD

**Issue by kocoten1992** [cockroachdb/cockroach#67204]
**Describe the problem**
Cockroachdb running into this issue:
`WARNING: disk slowness detected: unable to sync log files within 10s`

It kinda not make sense :thinking: , it happen on two separate machines (one is a local machine, one is a CI), and it is unreasonable that it could happen because disk slowness (both are ssd - and the number is 10s, if it 10ms then maybe it make more sense).

**To Reproduce**
Hard to reproduce, I'm running the work load constantly drop tables -> recreate tables -> seed data to run test.

**Expected behavior**
My guess here is that disk is neither slow nor sata cable are suddenly loosen up during testing, very high chance cockroachdb doing something that prevent itself writing to disk (this error happened quite a few times for me now - and no other application ever be slow or complain about disk issue).

**Environment:**
```
Build Tag:        v21.1.2
Build Time:       2021/06/07 18:09:50
Distribution:     CCL
Platform:         linux amd64 (x86_64-unknown-linux-gnu)
Go Version:       go1.15.11
C Compiler:       gcc 6.5.0
Build Commit ID:  d9845bd3021b4f5b816bd8bcde58b90a73f0377c
Build Type:       release
```

**Additional context**
What was the impact?
No impact, it does not happen on prod, but this is a sign.

This is just my speculation (it might not be correct), in the past, cockroachdb schema migration is running slower than postgres, (about 200x slower, with much effort, right now running at about 10-20 times slower).

I can't put my finger on it, but my instinct said the slowness must come from I/O (can't think of other explaination :smile: ), and this error reinforce my believe.

This would affect you guys too, imagine someone running the same workload as me (drop tables/recreate/running test and repeat) on cockroachdb cloud, it will bring down cockroach cloud.

To maximize the chance of this happening on your machine, I propose running 10 databases dropping at a time, eg:
1. create 10 databases
2. create some test tables
3. seed some data to it
4. drop tables and start again from (2.)

From step 2->4, running **simultaneously** 10 threads (for 10 databases) at the same time, it would stress and hopefully make cockroachdb fail.

**Comment by rafiss** [comment]
Thanks for writing this up @kocoten1992 ! A few questions:
- How much data are you seeding into the tables?
- Can you share the exact command you used to start CockroachDB?

**Comment by kocoten1992** [comment]
Thanks for the follow up @rafiss :
- Data seed into tables are very little (at most about 100 rows).
- I use systemd, content of systemd file is:
```
[Unit]
Description=Cockroachdb service.

[Service]
Type=simple
WorkingDirectory=/opt/cockroachdb/
MemoryAccounting=true
MemoryHigh=2G
MemoryMax=4G
ExecStart=/opt/cockroachdb/cockroach start-single-node --insecure --http-addr=0.0.0.0:8888 --host=127.0.0.1

[Install]
WantedBy=multi-user.target

```

Notice, this happen very rarely (I only encounter this 2 (or 3) times in my entire usage of cockroachdb), at first it happen on my local machine, I thought something wrong with it, but then it also happen on CI, hence the report.

I'm not sure if we try bring the number 10s down would help (I just search the error in src  https://github.com/cockroachdb/cockroach/blob/4d987b3f0788c98fa358715b336a1c55e254ee50/pkg/util/log/file.go#L260, could this be the work of mutex(?)). It it work may be we give it a shot ?

A google search result that no one have report this, however I do find this, https://github.com/cockroachdb/cockroach/issues/55404, https://github.com/cockroachdb/cockroach/issues/55627

**Comment by jordanlewis** [comment]
Hey @kocoten1992, probably the system you're running on runs out of CPU during these operations. If you have a concrete repro we can take a look, thanks!

**Comment by kocoten1992** [comment]
Yes, probably that, I forgot about that possibility.
