### ISSUE TITLE
cli: `debug tsdump` misuses the `--format` flag

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#67225]
The new "raw dump" feature has broken support for `--format=raw`.

The `--format` flag is meant to produce output in a textual raw format compatible with that used by other CLI commands. 

However the new `tsdump` code has mistakenly hijacked the meaning `--format=raw` to switch to an unrelated feature instead.

The original behavior of `--format=raw` should be restored and a different sub-command (or perhaps a `--raw` flag) created instead.

cc @tbg

**Comment by knz** [comment]
nb: I'll take this

**Comment by tbg** [comment]
What's the right way forward here? Make a new format? What should it be
named (if not "raw")? What do the other commands do with the format when
they receive it (I assume reject)
Or should the format flag just not apply to this command and we make a
one-off flag for the purpose?

**Comment by knz** [comment]
I think I'd like to approach this the other way around: keep the current behavior but stop relying on `cliCtx.tableDisplayFormat` which is specific to SQL commands.

There should be a new `debugCtx.tsDumpFormat` with a 3-valued type, accepting symbolic values csv, tsv and raw.

**Comment by tbg** [comment]
Note that tsdump has three output formats:

csv (I guess you could write tsv too)
clear-text optimized format
raw format

**Comment by knz** [comment]
correct there's already 4 values supported in the code: raw, csv, tsv, text
