### ISSUE TITLE
sql: predicate ignored when adding unique constraint

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#67234]
The predicate is silently ignored when using `ALTER TABLE ... ADD CONSTRAINT ... UNIQUE ... WHERE ...`. For example:
```
CREATE TABLE tab (
  a INT,
  b STRING
);
ALTER TABLE tab ADD CONSTRAINT key_a_b UNIQUE (a, b);
ALTER TABLE tab ADD CONSTRAINT key_b_partial UNIQUE (b) WHERE a = 1;
SHOW CREATE TABLE tab;
  table_name |             create_statement
-------------+-------------------------------------------
  tab        | CREATE TABLE public.tab (
             |     a INT8 NULL,
             |     b STRING NULL,
             |     UNIQUE INDEX key_a_b (a ASC, b ASC),
             |     UNIQUE INDEX key_b_partial (b ASC),
             |     FAMILY "primary" (a, b, rowid)
             | )
```
This is not the behavior when the constraint is included in the CREATE TABLE statement. For example:
```
CREATE TABLE tab (
  a INT,
  b STRING,
  CONSTRAINT key_a_b UNIQUE (a, b),
  CONSTRAINT key_b_partial UNIQUE (b) WHERE a = 1
);
SHOW CREATE TABLE tab;
  table_name |                      create_statement
-------------+-------------------------------------------------------------
  tab        | CREATE TABLE public.tab (
             |     a INT8 NULL,
             |     b STRING NULL,
             |     UNIQUE INDEX key_a_b (a ASC, b ASC),
             |     UNIQUE INDEX key_b_partial (b ASC) WHERE a = 1:::INT8,
             |     FAMILY "primary" (a, b, rowid)
             | )
```
In order to add a partial unique constraint after creating a table, the workaround is to use CREATE INDEX:
```
CREATE TABLE tab (
  a INT,
  b STRING
);
CREATE UNIQUE INDEX key_a_b ON tab (a, b);
CREATE UNIQUE INDEX key_b_partial ON tab (b) WHERE a = 1;
SHOW CREATE TABLE tab;
  table_name |                      create_statement
-------------+-------------------------------------------------------------
  tab        | CREATE TABLE public.tab (
             |     a INT8 NULL,
             |     b STRING NULL,
             |     UNIQUE INDEX key_a_b (a ASC, b ASC),
             |     UNIQUE INDEX key_b_partial (b ASC) WHERE a = 1:::INT8,
             |     FAMILY "primary" (a, b, rowid)
```
This bug has been around since v20.2 (the above terminal output is from v20.2, but it's still an issue on master, too).

Note that including a predicate on a constraint results in a syntax error in Postgres. I think we should continue to allow using a predicate with the constraint (it's useful for `UNIQUE WITHOUT INDEX`, etc), but we should not silently ignore it.

**Comment by rytaft** [comment]
cc @mgartner

**Comment by mgartner** [comment]
This is related to #65825. If we follow-through with that PR, we'd likely disallow partial unique constraints, like `UNIQUE (a) WHERE b`, and only allow partial unique indexes, like `UNIQUE INDEX (a) WHERE b`. This would more closely match Postgres's behavior.

**Comment by mgartner** [comment]
Even though it's currently valid to create partial unique constraints in a `CREATE TABLE` statement, I'm inclined to disallow them in `ALTER TABLE ... ADD CONSTRAINT ... UNIQUE` statements in both 21.2 and 21.1 based on future changes we want to make mentioned in #65825 and the fact the they are not allowed in Postgres:

```
marcus=# create table t (a int);
CREATE TABLE

marcus=# alter table t add constraint c unique (a) where a > 0;
ERROR:  42601: syntax error at or near "where"
LINE 1: alter table t add constraint c unique (a) where a > 0;
```

@ajwerner @vy-ton do you agree that this should be disallowed for now? Do you think it will confuse users to allow partial unique constraints in `CREATE TABLE` but not in `ALTER TABLE`?

**Comment by vy-ton** [comment]
With `ALTER TABLE`, the partial unique constraint isn't actually created correctly, right? In which case, I would prefer we disallow this since it creates a false impression of success. Someone can still use the `CREATE INDEX` alternative.

**Comment by mgartner** [comment]
> With ALTER TABLE, the partial unique constraint isn't actually created correctly, right? In which case, I would prefer we disallow this since it creates a false impression of success. Someone can still use the CREATE INDEX alternative.

You are correct. I didn't make myself clear, sorry for that. What I meant to ask is which option below is preferable in 21.2 and 21.1:

1. Disallow creating partial unique constraints in `ALTER TABLE`. They can still be created in `CREATE TABLE` statements which could cause confusion. Unique partial indexes, which have the same semantics when rows are mutated are still allowed.
2. Fix the bug in `ALTER TABLE` that ignores unique constraint partial predicates. Work related to #65825 will likely disallow creating partial unique constraints in both `ALTER TABLE` and `CREATE TABLE` in 22.1+, so it might cause future confusion to support something now that will not be supported in the future.

**Comment by vy-ton** [comment]
Given that the `ALTER TABLE` has existed since 20.2, I'm ok with doing Option 1.

**Comment by mgartner** [comment]
Great. Thanks!

**Comment by mgartner** [comment]
Now that I think about it more, maybe we should disallow partial unique constraints in both `ALTER TABLE` and `CREATE TABLE` in 21.2, which would get us one step closer to matching Postgres. It will still be allowed in 21.1 and 20.2 because otherwise it would be a breaking change. What do you think @vy-ton @ajwerner?
