### ISSUE TITLE
High  CPU Usage

### ISSUE THREAD

**Issue by onthegit** [cockroachdb/cockroach#67238]
**Describe the problem**
I use cockroach db on my local computer and on a dedicated server.
On my local computer it is run in insecure mode while on the dedicated server it is run in secure mode.
Both cockroachdbs are run as single node.

Please describe the issue you observed, and any steps we can take to reproduce it:
On my dedicated server (i7-6700 cpu - 32gb Ram) I am experiencing consistent 20%+ CPU usage with 2% memory usage for NO queries at all, observed with the top command. This CPU usage does not drop below 20%. 

However when I go to the admin interface cockroach reports little CPU usage. 

I installed it according to these instructions: https://www.cockroachlabs.com/docs/stable/deploy-cockroachdb-on-premises.html
as a service:
/usr/local/bin/cockroach start --certs-dir=certs --advertise-addr=127.0.0.1 --join=127.0.0.1 --cache=.25 --max-sql-memory=.25

On my local server cockroachdb barely has cpu and memory usage.

Dedicated server version is: v21.1.3
local version is v20.2.8

I tried restarting cockroachdb but the CPU usage does not change.

**Comment by rafiss** [comment]
Hi @onthegit that's odd behavior. Would you be able to capture a CPU profile using the following command?

```
go tool pprof /path/to/cockroach 'http://<host>:<admin console port>/debug/pprof/ui/profile/?seconds=10&labels=true'
```

**Comment by onthegit** [comment]
@rafiss Thank you for you reply. Sorry for responding so late.

I upgraded to 21.1.6 and the CPU usage now is OK . around 2% with NO queries.

thanks.
