### ISSUE TITLE
cli: create new sub command that checks whether a newer version is available

### ISSUE THREAD

**Issue by nadirdbit** [cockroachdb/cockroach#67239]
Hi,

The version command provides current version #

It will assist in having another option to check for an update in case newer version is available so that it can report on the latest release which can be subsequently deployed thereafter.

Thank you.

Nadir

Jira issue: CRDB-8439

**Comment by rafiss** [comment]
Thanks for this request @nadirdbit. There are two workarounds to be aware of:
1. In the database logs, the message "a new version is available" (plus additional info) will be logged if a new version is available and you have diagnostics reporting enabled.
2. The DB Console will contain a visual alert in the UI informing you of a new version.

**Comment by nadirdbit** [comment]
Hi Rafi,

Appreciate your comments and believe this will also be further useful due
to:

[1] message in database logs may get buried and thus get skipped
[2] a command-line version often helpful

Thank you.

Nadir
