### ISSUE TITLE
Factor out any shared expression when a table has multiple computed columns

### ISSUE THREAD

**Issue by karlseguin** [cockroachdb/cockroach#67241]
**Is your feature request related to a problem? Please describe.**
Given a table with multiple computed columns which each have the same expression, I'm given to believe that the expression will be re-computed per column. For example, given these 3 columns:

```
user_id text not null (summary::json->>'user_id') stored,
project_id text not null (summary::json->>'project_id') stored,
transaction_id text not null (summary::json->>'transaction_id') stored,
```

I believe `summary::json` will be executed 3 times.

**Describe the solution you'd like**
- Factor out shared expressions
- Document the behavior

**Describe alternatives you've considered**
Not using computed columns

Jira issue: CRDB-8440

**Comment by rafiss** [comment]
Thanks for writing up this issue! Another alternative to mention (not a solution to your issue) is virtual computed columns, which will only execute the computation when the column is read.
