### ISSUE TITLE
ui: Stats By Node table is not grouping properly in the StatementDetail page 

### ISSUE THREAD

**Issue by Azhng** [cockroachdb/cockroach#67280]
In the StatementDetail page in the DB Console, we have a table that displays statement statistics based on the gateway node name. However, this is [not grouped properly](https://github.com/cockroachdb/cockroach/blob/b5feed599bd18466923e4dde99c12fc7e0663840/pkg/ui/src/util/appStats.ts#L223) and `node_id` is not being considered as part of the statement key. 

From user's perspective, each time they refresh the page, they will see a different `node_id` in the entry of that table for statements that are being executed on different gateway nodes. 

Jira issue: CRDB-8468

**Comment by Azhng** [comment]
This becomes problematic once we moved to persisted SQL stats. After compaction, the SQL stats for the statements that are executed on different gateway nodes will be merged into a single entry of statistics. In other words, we will not have the necessary data to render this table once we moved to the persisted SQL stats. (However, we can still render this table for statements that are not yet flushed to the system table).

Thanks @ajwerner for reporting this.

@kevin-v-ngo what kind of use case is this Stats By Node table trying to solve? It shows what are the gateway nodes a particular statement fingerprint is being executed on. It's not immediately obvious to me the value of this information to the end user.

**Comment by kevin-v-ngo** [comment]
Hi Archer, I thought we had node_id in system.statement_statistics. This is not the gateway node? 

And this would be useful for multi-region deployments where we would be able to see where queries are being sourced from (e.g is one gateway node serving more executions of a statement than others? What is its latency compared to other gateway nodes). For non-multi-region deployments, this can measure how effective the load balancer is and is one node being a bottleneck for others for a particular statement fingerprint.

**Comment by Azhng** [comment]
Yes, we do have `node_id` in the `system.statment_statistics`. However,
that column was originally designed to be used more as a performance
optimization for SQL Stats flush than tracking meaningful metadata.
SQL Stats today does not actually store the `node_id` information anywhere.
This information is lazily populated during the cluster-wide RPC fanout.
`node_statement_statistics` populates its `node_id` by reading the
SQL-pod's own SQLInstanceID.

Without compacting the statistics across different `nodeID`s, we would be
running into the same data cardinality problem that we originally solved
with stats compaction.

> For non-multi-region deployments, this can measure how effective the load
balancer is and is one node being a bottleneck for others for a particular
statement fingerprint.

Does this make sense to be measured at the statement fingerprint level? I'm
a little bit skeptical about this. My intuition is that if a cluster is
having load balancing issues, we already have other metrics
to detect that. Do we have any precedence where a load balancer only has
issue balancing a single specific statement?

> And this would be useful for multi-region deployments where we would be
able to see where queries are being sourced from (e.g is one gateway node
serving more executions of a statement than others?

In this case, would it be better to use the `plan_hash` as a better
differentiator? We can possibly compute a different hash for different
instances of the same plan that are executed on different gateway nodes
that reside in different regions.

**Comment by kevin-v-ngo** [comment]
I think it would be much clearer to have plan_hash only represent changes in the plan itself. I wouldn't combine both scenarios. If it's the information we should surface, we can consider representing this with another column.

 @Azhng, we were looking at this during triage and would like to confirm, where does this surface for the user today? Is this under Stats by node?

![image](https://user-images.githubusercontent.com/81193618/125319255-70a73700-e2ef-11eb-93d6-04b4d0bcdcc2.png)

**Comment by Azhng** [comment]
> where does this surface for the user today? Is this under Stats by node?

Yes 

> If it's the information we should surface, we can consider representing this with another column.

Introducing another column will not solve the problem in this case. This is because of the compaction process, where we merge multiple instances of the stmt/txn stats into one. The compaction process is what prevents the size of the stats system table to grow from order of hundreds of MB to tens of GB. 

I think I'm still not entirely convinced that this is a very useful information we need to surface. For the use case of understanding the load balancer issue, I think statement fingerprint is not the ideal place to surface that information. Whereas if we are to solve the issues with the multi-region use case, perhaps we can add the gateway node's region information into the fingerprint-id, instead of the node id.
