### ISSUE TITLE
kv/kvserver: split incoming snapshot user keys into multiple sstables

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/cockroach#67284]
Currently, when receiving a snapshot, we ingest a fixed number of sstables, corresponding to the range's various contiguous keyspaces. When the default range size increased from 64 MB to 512 MB, we started ingesting user data sstables up to 512 MB. These large files cause more expensive compactions.

Here's a [relevant TODO](https://github.com/cockroachdb/cockroach/blob/9ba3198cbdfd856c429bde695ffc1f0ec0f96c37/pkg/kv/kvserver/store_snapshot.go#L241).

Related thread: https://cockroachlabs.slack.com/archives/CAC6K3SLU/p1686237663708959?thread_ts=1686084258.076069&cid=CAC6K3SLU

Related to cockroachdb/pebble#1181.

cc @sumeerbhola

Jira issue: CRDB-8471

**Comment by sumeerbhola** [comment]
I believe the only change required is to `multiSSTWriter` and should be very easy to do. The tests for it are in replica_sst_snapshot_storage_test.go.

**Comment by jbowens** [comment]
Ack, I can make the change myself, but I probably won't get it for a little while.
