### ISSUE TITLE
ui: align logical plan on statement details page on DB Console to SQL shell 

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#67328]
The logical plan displayed on the details page of a statement should match the format we currently see on EXPLAIN on the SQL Shell.
Also rename the tab to 'Explain plan'

The design can be seen here: https://www.figma.com/file/MoSPFkEyJfGipCmQvvLg1a/21.1_SQL-obsrv_query-performance?node-id=2727%3A118388

**Comment by xinhaoz** [comment]
@kevin-v-ngo @maryliag 
Wanted to confirm -- are we aligning the DB console with EXPLAIN ANALYZE (and all its execution stats per plan node) or just EXPLAIN?

**Comment by kevin-v-ngo** [comment]
Hi @xinhaoz, here is @Annebirzin's Figma mockups:https://www.figma.com/file/MoSPFkEyJfGipCmQvvLg1a/21.1_SQL-obsrv_query-performance?node-id=2727%3A118388

It's actually the **format** of EXPLAIN and EXPLAIN ANALYZE that we'd like it to be consistent with what's seen in the SQL CLI. The contents should still be the logical (Explain) plan - the tab is also just "Explain plan"
