### ISSUE TITLE
perf: build RocksDB batches in Go

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#6739]
Currently, we use `rocksdb::WriteBatchWithIndex` to build a set of mutation operations which are then applied to RocksDB atomically. During bulk insert operations, every addition to the batch is performed via a call to `storage/engine.rocksDBBatch.Put` which crosses the cgo barrier to call `DBPut`. Very commonly, bulk insert operations have no self-overlap. We already have one fast-path which takes advantage of this: the blind put optimization.

The `rocksdb::WriteBatch` format is fairly straightforward and we're already going to be relying on it not changing soon. I think we can implement construction of the `WriteBatch` representation in Go without too much effort and I suspect that doing so will be faster than calling through cgo to perform the construction in C++. 

The most general way to take advantage of Go-based `WriteBatch` construction is to add smarts to `rocksDBBatch` to buffer writes until a read potentially requires them. I see a path to doing this, but the first step is experimentation to validate that this will be worthwhile. My first very simple stab at such experiments suggest this could speedup batch put operations by 20-30% and "blind" batch put operations by 50%.

**Comment by tschottdorf** [comment]
Whoever finishes this issue probably gets to close https://github.com/cockroachdb/cockroach/issues/6289 as a by-product.

**Comment by tschottdorf** [comment]
In my mind, a cgo call costs ~200ns. Along with the frequency at which they occur, does it approximately amount for the savings you've seen or is there something else at work?

**Comment by petermattis** [comment]
Yes, the cgo call looks to be about ~200ns. I whipped up write-only creation of the rocksdb batch representation and benchmarked creating a batch with 1000 10-byte puts vs using the C++ RocksDB code (old = C++ RocksDB batch construction, new = Go batch construction):

```
name        old time/op  new time/op  delta
BatchPut-8   440ns ± 1%    80ns ± 1%  -81.80%  (p=0.000 n=8+10)
```

If I make the C++ batch put operation a no-op, we can see the cgo call overhead in this benchmark:

```
name        old time/op  new time/op  delta
BatchPut-8   440ns ± 1%   239ns ± 4%  -45.56%  (p=0.000 n=8+9)
```

I think the Go batch construction code is faster than the C++ code because it isn't as general. I'm not creating an index for the batch and I'm encoding keys and values directly into the buffer.

Here is the is the `MVCCBatchPut` benchmarks comparing the C++ vs Go batch building:

```
name                            old time/op    new time/op    delta
MVCCBatch1Put10_RocksDB-8         5.23µs ± 1%    4.41µs ± 3%  -15.66%  (p=0.008 n=5+5)
MVCCBatch100Put10_RocksDB-8       1.96µs ± 6%    1.47µs ± 2%  -25.16%  (p=0.008 n=5+5)
MVCCBatch10000Put10_RocksDB-8     1.87µs ± 3%    1.44µs ± 3%  -23.01%  (p=0.008 n=5+5)
```

The same benchmarks but hacked to use "blind" puts:

```
name                            old time/op    new time/op    delta
MVCCBatch1Put10_RocksDB-8         2.68µs ± 2%    1.87µs ± 2%   -30.18%  (p=0.008 n=5+5)
MVCCBatch100Put10_RocksDB-8        803ns ± 5%     386ns ± 5%   -51.99%  (p=0.008 n=5+5)
MVCCBatch10000Put10_RocksDB-8      773ns ± 5%     371ns ± 1%   -52.00%  (p=0.008 n=5+5)
```

**Comment by tschottdorf** [comment]
Thanks, looks good!
