### ISSUE TITLE
stats: remove old irrelevant stats

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#67407]
Whenever the optimizer collects new stats for a column or set of columns, it deletes old stats for those column(s) and leaves the most recent 4-5 stats. However, if a column is deleted or removed from an index (and therefore no longer part of a multi-column statistic), there will be no new stats collected for that column or set of columns, and therefore the old stats for those column(s) never get deleted. At best this results in buildup of cruft in the system.table_statistics table. At worst, this can cause the optimizer to use very stale statistics for multi-column stats and cause it to produce suboptimal plans.

There should be an automated way to delete these stats and prevent the optimizer from using them.

Epic CRDB-13963

Jira issue: CRDB-8529

Jira issue: CRDB-13895

**Comment by RaduBerinde** [comment]
Have we found it useful to keep the last 4-5 stats, rather than just keeping the latest one? More often than not, they just lead to unnecessary clutter in the statement bundles.
