### ISSUE TITLE
sql: session-scoped temporary objects do not work with tenant clusters

### ISSUE THREAD

**Issue by andy-kimball** [cockroachdb/cockroach#67401]
Repro:
```
export COCKROACH=./cockroach

# Create certificates.
export CERTSDIR=$HOME/.cockroach-certs
export COCKROACH_CA_KEY=$CERTSDIR/ca.key
$COCKROACH cert create-ca
$COCKROACH cert create-client root
$COCKROACH cert create-node 127.0.0.1 localhost
$COCKROACH mt cert create-tenant-client 123 --certs-dir=${HOME}/.cockroach-certs

# Start KV process.
$COCKROACH start-single-node --host 127.0.0.1

# Create tenant
$COCKROACH sql --host 127.0.0.1 -e 'select crdb_internal.create_tenant(123);'

# Start SQL tenant process.
COCKROACH_TRUST_CLIENT_PROVIDED_SQL_REMOTE_ADDR=true $COCKROACH mt start-sql --tenant-id 123 --kv-addrs 127.0.0.1:26257 --http-addr 127.0.0.1:8081 --sql-addr 127.0.0.1:36257
```

Notice that already there's a warning in the log, despite not having created any temporary objects:
```
W210709 00:19:08.472581 195 sql/temporary_schema.go:601  [-] 2  failed to clean temp objects: isMeta1Leaseholder is not available to secondary tenants
```

Now create a temporary table in the SQL CLI:
```
$COCKROACH sql --port 36257

SET experimental_enable_temp_tables = 'on';
CREATE TEMP TABLE t (x INT PRIMARY KEY, y INT);
```

While still in the CLI, kill the SQL tenant process with ctrl-C. Then start it up again. Back in the SQL CLI:
```
SHOW TABLES;
```

EXPECTED: The temp table should be gone, since it was tied to the previous session, which got terminated.
ACTUAL: The temp table is still showing:
```
root@:36257/defaultdb> show tables;
             schema_name            | table_name | type  | owner | estimated_row_count | locality
------------------------------------+------------+-------+-------+---------------------+-----------
  pg_temp_1625790426654356000_10001 | t          | table | root  |                   0 | NULL
```

Even if we decide not to fix this right now, we need to at least disable temporary object creation in tenant clusters and stop spamming the logs (logs are filled with the warning message even when temp objects are not ever used). That change needs to be back-ported to 21.1.x.

Also, here's @ajwerner's commentary from Slack:
> Oh, that’s not good. Interesting that it’s new.
> This needs some tracking. Seems like we didn’t think through temporary objects on tenants.
> If a node crashes or is shut down with an open session that created temporary objects, nothing will ever clean them up.
> There’s different levels of solutions. I think what I’d do is just get rid of the leasing component. It’s idemponent work. That being said, the code also makes RPCs to the other instances to find out which sessions are live which is also busted on tenants.
> We’re working on the sessions listing stuff (I think). At that point, it’s just about deciding whether we care about the leasing. For that I think there are two simple solutions:
> No leasing, just jitter a long loop
> Use the fact that you have the lowest instance ID you know about like being the leaseholder of meta1.
> All in all, it is non-trivial, but it is small.

**Comment by ajwerner** [comment]
Reopening for backport.
