### ISSUE TITLE
Add DistSql Enforcer Expr in Memo

### ISSUE THREAD

**Issue by xxd9980** [cockroachdb/cockroach#67416]
**Is your feature request related to a problem? Please describe.**

Our SQL optimizer just generate a local plan because there is no distSql enforcer expr in memo. (such as "Redistribute", "Replicate" in GreenPlum ORCA)
So now the cost of hash redistribute or mirror replicate is not considered in optimizer.

**Describe the solution you'd like**

1. Add distSql enforcer exprs
2. Cost distSql enforcer exprs
3. Add data PartitionType in physical.Required

**Additional context**

This goona make a huge change, so if this way is impractical, plz tell me why, thank you : )

![GreenPlum ORCA Enforcer (Black Expr in Memo)](https://user-images.githubusercontent.com/30730484/125055969-58120380-e0da-11eb-966e-3170a3e85c59.png)

**Comment by rytaft** [comment]
Thank you for suggesting this, @xxd9980! I believe your suggestion is already covered by an existing issue, https://github.com/cockroachdb/cockroach/issues/47226.

I am going to close this issue to avoid duplication, but feel free to comment on https://github.com/cockroachdb/cockroach/issues/47226 if you feel it does not adequately describe all aspects of the issue.
