### ISSUE TITLE
sql: implement pg_default_acl table

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#67441]
As part of implementing default privileges, we should match how Postgres reports defaults in pg_catalog. Postgres handles this through the pg_default_acl. See additional info in their docs here: https://www.postgresql.org/docs/12/catalog-pg-default-acl.html

CRDB-2586

**Comment by RichardJCai** [comment]
Closed by https://github.com/pulls?q=is%3Apr+author%3ARichardJCai+archived%3Afalse+is%3Aclosed
