### ISSUE TITLE
Exclude a list of tables/descriptors during restore

### ISSUE THREAD

**Issue by livlobo** [cockroachdb/cockroach#67483]
**Is your feature request related to a problem? Please describe.**
When restoring a backup, a user may run into errors due to specific tables/descriptors. In some cases, the user may not care about that table that couldn't restore (e.g. system.jobs or a temp table), however, that faulty table/descriptor ends up blocking the whole restore.

**Describe the solution you'd like**
Allow the user to exclude a list of tables/descriptors from the restore using a list of IDs.
RESTORE DATABASE backup_database_name FROM 'your_backup_location' WITH exclude_descriptors=99,777

**Alternate solutions**
Using a list of names, rather than IDs is a better UX. However, resolving IDs to names it itself a point of potential failure.

**Comment by zachary-thomas-115** [comment]
I would be willing to work on this, if still needed!

**Comment by mwang1026** [comment]
closing in favor of https://github.com/cockroachdb/cockroach/issues/57386
