### ISSUE TITLE
error expiring job sessions with node down

### ISSUE THREAD

**Issue by dankinder** [cockroachdb/cockroach#67487]
**Describe the problem**

I have an index build  from 24 hours ago that stopped at 5% and hasn't been moving. Looking at logs I see this:
```
E210712 14:14:57.172401 10117 jobs/registry.go:691 ⋮ [-] 1630434  error expiring job sessions: ‹expire-sessions›: split failed while applying backpressure to Put [‹/Table/15/1/674674519261020161/2/1›,‹/Min›), EndTxn(commit:true) [‹/Table/15/1/674674519261020161/2/1›], [txn: 906d3cf2] on range r694768:‹/Table/15/1/6746745192{61020161-97425409}› [(n4,s20):1, (n14,s80):2, (n19,s111):3, (n7,s39):4, (n33,s195):6, next=7, gen=284]: ‹could not find valid split key›
```

I suspect it's related to having one node down. But this node has been down for maintenance for days (it was shut down gracefully), since well before I started the index build. I will be bringing that node back up soon, but still this seemed like incorrect behavior.

Maybe notable, this is a big index, and I noticed that for 12 hours or so after I started it, one particular disk had 50%+ utilization and poor latencies/commit times. So it's possible that the index build simply failed due to a slow IOP on that disk, and CRDB is just failing to expire the job.

**To Reproduce**

1. Start up a few nodes with V21.1.3
2. Populate data, then take a node down
3. Run create index (in my case it's a partial index)

**Comment by rafiss** [comment]
Hi @dankinder ! Out of curiosity, what was the level of concurrent application traffic (selects/inserts/updates) on this table where you are adding the index?

**Comment by ajwerner** [comment]
The root cause here is https://github.com/cockroachdb/cockroach/issues/67523.

**Comment by ajwerner** [comment]
In order to unblock progress, you're going to need to either:

1) Decrease GC TTL on the system.jobs table
* `ALTER TABLE system.jobs CONFIGURE ZONE USING gc.ttlseconds = 300`;
* Will break full cluster incremental backups.
2) Increase the range size on the system.jobs table
* `ALTER TABLE system.jobs CONFIGURE ZONE USING range_max_bytes  = 2<<30`
3) Increase the range backpressure threshold 
 * `SET CLUSTER SETTING kv.range.backpressure_range_size_multiplier = 8`

**Comment by dankinder** [comment]
Awesome thanks guys, I'll close this then in favor of https://github.com/cockroachdb/cockroach/issues/67523
