### ISSUE TITLE
sql: Add more telemetry for computed columns

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/cockroach#67495]
For computed columns, we have a feature counter for `sql.schema.new_column.qualification.computed`.

Since we now have virtual computed columns, we should add counters for the following:

- [ ] stored vs virtual computed column

**Comment by mgartner** [comment]
I think this was already done. The counter for stored computed columns is `sql.schema.new_column.qualification.computed` and the counter for virtual computed columns is `sql.schema.new_column.qualification.virtual`. This is the code that increments these counters: https://github.com/cockroachdb/cockroach/blob/cd6356d26876b64f8c2ba5131def4058aefb10a3/pkg/sql/create_table.go#L2674-L2680

I'll close this for now, but please re-open if these counters are not being reported correctly.
