### ISSUE TITLE
Could txnSender ignore EndTransaction command for a read-only transaction?

### ISSUE THREAD

**Issue by yananzhi** [cockroachdb/cockroach#675]
Is there any necessary to execute an EndTransaction command for read-only transaction?
	Read-only transaction is defined as a transaction has never executed a TxnMethods 
	A read-only transaction will never been pushed
	txn_coord_sender will not keep a txnMetadata and heartbeat for a read-only transaction
	txn_coord_sender will block a EndTransaction command for some time to ensure the linearizable behaviour
	
If a system do not need the linearizable behaviour, could txnSender return directly instead of sending EndTransaction command to the txn_coord_sender?

**Comment by spencerkimball** [comment]
Good point. This is a reasonable optimization. Pete just did some work on the client. It would make sense there to keep track of whether or not any mutations occurred and simply skip the EndTransaction call on completion.

**Comment by petermattis** [comment]
I'll take a look.
