### ISSUE TITLE
my test cluster don't rebalance after about 3 hours 

### ISSUE THREAD

**Issue by a6802739** [cockroachdb/cockroach#6751]
here is my start command.

```
FIRSTNODE="10.52.130.20"
COCKROACHDBPATH="/root/setup-cockroachdb/"
NODE1="10.52.135.73"
NODE2="10.52.139.60"
NODE3="10.52.140.20"
NODE4="10.52.141.73"

echo "first node start"
cd $COCKROACHDBPATH

nohup $COCKROACHDBPATH/bin/cockroach start --insecure --log-dir="/home/log/data00" --logtostderr=false --store=/home/data00 --store=/home/data01 --store=/home/data02 --store=/home/data03 --port=26660 --attrs=10.52.130.20.data,ssd>/home/log/data00/1.log 2>/home/log/data00/err.log &

echo "second node start"

cmd2="cd $COCKROACHDBPATH; nohup $COCKROACHDBPATH/bin/cockroach start --insecure --log-dir="/home/log/data00" --logtostderr=false --port=26660 --store=/home/data00 --store=/home/ssd01 --store=/home/data02 --store=/home/data03 --join=${FIRSTNODE}:26660 --attrs=${NODE1}.data,ssd>/home/log/data00/1.log 2>/home/log/data00/err.log &"

echo $cmd2
ssh $NODE1 $cmd2

echo "third node start"

cmd3="cd $COCKROACHDBPATH; nohup $COCKROACHDBPATH/bin/cockroach start --insecure --log-dir="/home/log/data00" --logtostderr=false --port=26660 --store=/home/data00 --store=/home/data01 --store=/home/data02 --store=/home/data03 --join=${NODE1}:26660 --attrs=${NODE2}.data,ssd>/home/log/data00/1.log 2>/home/log/data00/err.log &"
echo $cmd3
ssh $NODE2 $cmd3

echo "fourth node start"

cmd4="cd $COCKROACHDBPATH; nohup $COCKROACHDBPATH/bin/cockroach start --insecure --log-dir="/home/log/data00" --logtostderr=false --port=26660 --store=/home/data00 --store=/home/data01 --store=/home/data02 --store=/home/data03 --join=${NODE2}:26660 --attrs=${NODE3}.data,ssd>/home/log/data00/1.log 2>/home/log/data00/err.log &"
echo $cmd4
ssh $NODE3 $cmd4

echo "fifth node start"

cmd5="cd $COCKROACHDBPATH; nohup $COCKROACHDBPATH/bin/cockroach start --insecure --log-dir="/home/log/data00" --logtostderr=false --port=26660 --store=/home/data00 --store=/home/data01 --store=/home/data02 --store=/home/data03 --join=${NODE3}:26660 --attrs=${NODE4}.data,ssd>/home/log/data00/1.log 2>/home/log/data00/err.log &"
echo $cmd5
ssh $NODE4 $cmd5
```

after waiting for 3 hours, the status of my cluster is like this:
<img width="1189" alt="19613934e3e5375d691addbe833087a0" src="https://cloud.githubusercontent.com/assets/3368692/15328751/883a73e2-1c88-11e6-9510-08e8b426fa31.png">

**Comment by cuongdo** [comment]
Adding two screenshots that @a6802739 posted to Gitter:

![nodes_table](https://cloud.githubusercontent.com/assets/1564582/15361655/62dd086e-1ce0-11e6-89af-5caf64188adb.png)

![stores](https://cloud.githubusercontent.com/assets/1564582/15361663/698ae7e4-1ce0-11e6-81a0-b7bd52f48815.png)

**Comment by cuongdo** [comment]
@a6802739 Can you reply with the output of `cockroach version`?

**Comment by cuongdo** [comment]
I'm running a configuration that's similar to yours with the same schema and same kinds of INSERTs, and I'm not seeing the behavior you're seeing.

Here's a screenshot from my cluster, which is running a build from today:

<img width="1212" alt="screenshot 2016-05-18 16 52 14" src="https://cloud.githubusercontent.com/assets/1564582/15374580/00c91422-1d19-11e6-8d9d-3c58932971bd.png">

Any other info you can give me would be helpful, such as your CockroachDB build information.

Also, it might be worth retrying without the `--attrs` flag, just to see if that makes a difference.

**Comment by a6802739** [comment]
@cuongdo  my binary version is beta-20160512. I will retry without --attrs flag.

**Comment by a6802739** [comment]
@cuongdo  I retry without --attrs flag. now it can rebalance now.
![Uploading 66d464b10ea71b0a6005aa421e1acf20.png…]()

**Comment by a6802739** [comment]
@cuongdo  I have retry without --attrs flag. it can work well now.
