### ISSUE TITLE
sql/kv: implement lock_timeout session variable

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#67513]
Postgres has a configuration to limit the amount of time a given statement waits to acquire an individual lock: https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-LOCK-TIMEOUT

> Abort any statement that waits longer than the specified amount of time while attempting to acquire a lock on a table, index, row, or other database object. The time limit applies separately to each lock acquisition attempt. The limit applies both to explicit locking requests (such as LOCK TABLE, or SELECT FOR UPDATE without NOWAIT) and to implicitly-acquired locks. If this value is specified without units, it is taken as milliseconds. A value of zero (the default) disables the timeout.
>
> Unlike statement_timeout, this timeout can only occur while waiting for locks. Note that if statement_timeout is nonzero, it is rather pointless to set lock_timeout to the same or larger value, since the statement timeout would always trigger first. If log_min_error_statement is set to ERROR or lower, the statement that timed out will be logged.
>
> Setting lock_timeout in postgresql.conf is not recommended because it would affect all sessions.

We currently accept this session variable, but ignore it.

This would provide a more targeted solution for the same "lock bloat" problem detailed in https://github.com/cockroachdb/cockroach/issues/66017. The implementation of this would be fairly straightforward. We would introduce a new `lock_timeout` field on `roachpb.Header` and plumb this down to the `lockTableWaiter`. It would be similar to https://github.com/cockroachdb/cockroach/pull/52388.
```
// lock_timeout specifies the maximum amount of time that the batch request
// will wait while attempting to acquire a lock on a key or while blocking on
// an existing lock in order to perform a non-locking read on a key. The time
// limit applies separately to each lock acquisition attempt.
//
// Unlike other systems, where non-locking reads do not wait on conflicting
// locks, in CockroachDB, non-locking reads do wait for conflicting locks to
// be released. Because of this, the lock_timeout configuration applies to
// non-locking reads in read-write and read-only transactions as well.
//
// Only the (default) Block wait policy will allow a request to wait on
// conflicting locks, so the timeout only makes sense in conjunction with the
// Block wait policy.
google.protobuf.Duration lock_timeout = 19 [(gogoproto.nullable) = false,
                                            (gogoproto.stdduration) = true];
```

**Comment by lunevalex** [comment]
would this have helped with #66760?

**Comment by nvanbenschoten** [comment]
Not quite, these are different kinds of locks. 

This issue is about a timeout for SQL transactions acquiring row-level locks. These locks semantically live in the SQL domain, and so contention on these locks is entirely up to the SQL workload. This `lock_timeout` setting affords users more control over how contention on these row-level locks behaves.

#66760 was a deadlock on a mutex protecting shared memory. These lower-level locks are implementation concerns, and so the deadlock was a straight-up bug. I tend to agree with @tbg that trying to limit the blast radius of such a deadlock isn't going to be particularly fruitful unless we're willing to put a lot of effort into it [1]. In my opinion, we just need to make sure they aren't possible and that we have [testing](https://github.com/cockroachdb/cockroach/issues/66764) that will catch them using a combination of static and dynamic analysis.

[1] for example, replace `sync.Mutex` with our own re-entrant mutex implementation, or a mutex implementation that panics on re-entrant attempts instead of blocking, either of which I would imagine would sacrifice runtime performance and be difficult to build/maintain.

**Comment by tbg** [comment]
The option I had in mind for automatically detecting deadlock was https://github.com/cockroachdb/cockroach/issues/66765, i.e. have something periodically try to acquire the mutex and if unsuccessful within a timeout, declare a deadlock and shut down the node. But bringing back improved testing is more important as these deadlocks are very rare but when they do get shipped, no protection will really limit the blast radius all that much.

**Comment by sumeerbhola** [comment]
> an existing lock in order to perform a non-locking read on a key

are these limited to reads for compatibility with postgres?
