### ISSUE TITLE
cli: debug.zip collection of table schema is too slow

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#67515]
I saw a user collecting a debug.zip using a 21.1.5 client binary (against a 20.2 cluster). It looked to me like the collection of table schemas was very slow. It looked like we were collecting one table at a time and each table was taking a few seconds. Across many tables, this was painful. Does this sounds right? Can we parallelize some?

**Comment by knz** [comment]
I've looked into it, and decided against this since all the contention comes from a shared access to `system.descriptors`.

The only semi-clever thing I can think of is to use AS OF SYSTEM TIME to get the descriptors? 

But I think this is not work for the server team, and more for the schema team.
@ajwerner what do you think?

**Comment by ajwerner** [comment]
We could use `PRIORITY HIGH`. I guess we could use AOST, perhaps just set to the beginning of the command. Perhaps we ought to move the reading of table data to the end of the command but use a timestamp from the beginning to avoid contention. Anyway, this is going in the backlog.

**Comment by andreimatei** [comment]
> I've looked into it, and decided against this since all the contention comes from a shared access to system.descriptors.

What contention are we talking about? Would doing, say, 30 lookups at a time on different rows in `system.descriptors` be bad in any way?

**Comment by knz** [comment]
on most deployment it's all one range

**Comment by andreimatei** [comment]
I understand but... what are we afraid of? Why is one lookup at a time OK and anything more than that not OK?

**Comment by knz** [comment]
oh you mean introducing a semaphore of sorts, like we do in other places already?

**Comment by andreimatei** [comment]
A semaphore or a fixed-size goroutine pool or something like that, yeah.
Or alternatively we could perhaps scan `system.descriptors`, maybe in a paginated way, instead of doing lookups.

**Comment by ajwerner** [comment]
>Why is one lookup at a time OK and anything more than that not OK?

@andreimatei what are you talking about? We do one lookup at a time somewhere?

**Comment by ajwerner** [comment]
Oh gosh I really did not see some of the things happening here. This is crazy. We already buffer all of the descriptors in ram elsewhere.

https://github.com/cockroachdb/cockroach/blob/4cd12c8ba7f86741f6921e4b3230413f1d085665/pkg/cli/zip_cluster_wide.go#L168-L171

**Comment by ajwerner** [comment]
The layers are killing us here.

**Comment by knz** [comment]
oh so we're seeing quadratic behavior. nice

**Comment by knz** [comment]
@ajwerner ever since "a long time ago" debug zip already collects a copy of system.descriptor. Could we perhaps drop the "get database and table details" phase from debug zip altogether? And assume that folk who care can get the data back from system.descriptor?

**Comment by ajwerner** [comment]
> @ajwerner ever since "a long time ago" debug zip already collects a copy of system.descriptor. Could we perhaps drop the "get database and table details" phase from debug zip altogether? And assume that folk who care can get the data back from system.descriptor?

There is some value in retaining this data in that it gives us create table statements which we're not getting out of system.descriptor and have no means to get from the debug zip. I think that if we were to replace this fan out with a single `SELECT * FROM "".crdb_internal.create_statements` we'd be in a good place.

**Comment by knz** [comment]
> it gives us create table statements

ok let's collect that too then.

**Comment by knz** [comment]
I am also seeing the `to_hex` thing done for system.descriptor and system.jobs. 

We already have the ability to encode the byte payload natively using SQL as base64. Do we want to keep this to_hex stuff?

**Comment by ajwerner** [comment]
> We already have the ability to encode the byte payload natively using SQL as base64. Do we want to keep this to_hex stuff?

Can you help me understand where `base64` comes up? The hex encoded system.descriptors and system.jobs has proven to be incredibly valuable. Our command line tooling assumes hex and not base64. I'll note that we don't really get any value out of the unencoded bytes columns in those files.

**Comment by knz** [comment]
> Our command line tooling assumes hex and not base64
which one is that?

**Comment by ajwerner** [comment]
>>Our command line tooling assumes hex and not base64
>which one is that?

`cockroach debug decode-proto`

**Comment by knz** [comment]
ok I know how to deal with it.

**Comment by ajwerner** [comment]
I just looked and it seems to actually try both hex and base64, so nothing to do on that front it seems.
