### ISSUE TITLE
server: runtime stats log messages were dehumanized

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#67518]
Observe the following log message:
```
I210712 23:49:40.153137 471 2@util/log/event_log.go:32 ⋮ [n1] 307 ={"Timestamp":1626133780153135266,"EventType":"runtime_stats","MemRSSBytes":272957440,"GoroutineCount":337,"MemStackSysBytes":4816896,"GoAllocBytes":48553440,"GoTotalBytes":98093112,"GoStatsStaleness":0.001095539,"HeapFragmentBytes":8585760,"HeapReservedBytes":13041664,"HeapReleasedBytes":193437696,"CGoAllocBytes":73521504,"CGoTotalBytes":80556032,"CGoCallRate":0.099993266,"CPUUserPercent":1.6998855,"CPUSysPercent":0.6999529,"GCRunCount":89,"NetHostRecvBytes":84446,"NetHostSendBytes":95344}
```

Observe how this log message used to read:
```
I210711 03:04:11.257023 2225 2@server/status/runtime.go:569 n19] 13674  runtime stats: 12 GiB RSS, 1221 goroutines (stacks: 11 MiB), 171 MiB/395 MiB Go alloc/total (heap fragmentation: 36 MiB, heap reserved: 101 MiB, heap released: 1.5 GiB), 8.0 GiB/10 GiB CGO alloc/total (0.1 CGO/sec), 79.3/11.7 %(u/s)time, 0.1 %gc (0x), 601 MiB/306 MiB (r/w)net
```

I want the old one back.

I had spent considerable effort making that message as readable as I could, and then my toy was broken in https://github.com/cockroachdb/cockroach/pull/65024 because "our users have expressed interest in making this information more reliably parsable" (#63750). I have yet to see a user parse these. In contrast, I routinely want to read the damn thing; "our users" also expressed an interest in us reading their logs.

Please, let's find a way to get the old message back under the default logging settings. Generally, when people are not doing anything custom (i.e. when all the logging channels are multiplexed onto one log file) I think we should primarily aim for this file being read by humans. When I change the logging settings, that's another matter - perhaps we can make it such that I can get both somehow.

In the case of this particular message with the runtime stats, I also question whether anyone ever wants to parse this message, given that we have timeseries for some of these numbers. I think it'd be marginally useful if *we* had a tool to parse these logs, given that debug.zips don't have timeseries at the moment.

**Comment by andreimatei** [comment]
cc @cameronnunez

**Comment by cameronnunez** [comment]
@rauchenstein and I had a conversation about this in [#65024](https://github.com/cockroachdb/cockroach/pull/65024). My inclination was maintaining human readability but he suggests optimizing for machine-readability. He might know better than I do about the utility of parsing these logs.

We could log both versions of the message, as noted by Raphael in the linked conversation: 
> Unsure if y'all discussed this already, but what we can do is to log side-by-side:
> 
> * the current template with formatted values on the DEV channel
> * the structured payload on the HEALTH channel

**Comment by rauchenstein** [comment]
To clarify my stance.  GIVEN the objective of putting this information in a structured format suitable for further processing, the new way is clearly the winner.  The hybrid solution that was considered (leaving numbers as humanized strings with varying units) is the worst of both worlds -- annoying and error-prone to parse by machine (also lossy) but too ugly for humans to read.

But that's not the only use-case, and we've clearly sacrificed readability here.  I think neither parse-ability nor readability should be sacrificed for the other (at least in cases where reading is actually happening), so I'd be in favor of both versions "existing" in some form.  As I mentioned in #65024, the human-readable form should be a function of the parse-able one (to ensure that no additional data is encoded in the readable form that would require trying to parse it).

**Comment by knz** [comment]
Note that my idea was to have the two forms go to different logging channels. Machine parsers never look at the dev channel so they would not be disturbed by something there optimized for humans.

However that was just an idea.

What would y'all suggest we do?

**Comment by rauchenstein** [comment]
Different formats to different channels would be okay.  Making it user-configurable a single channel would be bad -- that would mean we'd have to read logs in whichever format they happen to be outputting.

So, one idea is to output both versions (readable_log <- crbd -> parsable_log).  Since the readable version should be a function of the parsable one, another possibility is to provide a tool or subcommand to humanize the parsable log (crdb -> parsable_log -> readable_log).  Future structured logging is then free to be arbitrarily terse since it's explicitly not aimed at humans.  (Even having a binary format could be on the table, pending further discussion.)  The readable format could actually benefit too -- the data could be more aligned and tabular without feeling like you're storing a bunch of unnecessary whitespace.

**Comment by andreimatei** [comment]
It's been a while and nothing has happened. If y'all don't mind, I'm gonna revert #65024 tomorrow to get my readable stats back. No shade or anything; no shame in reverts.
