### ISSUE TITLE
RESTORE: restore of system tables done in txn, can fail due to max command size

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#67529]
RESTORE of most tables is done by bulk-adding, non-transactionally, into new tables with new IDs. Restore of system tables during cluster in initially done this was as well, also into new tables that have new IDs, but at the end of the RESTORE, to get those restored rows into the actual system tables that have fixed IDs, we run, more or less, `BEGIN; DELETE FROM tbl; INSERT INTO tbl SELECT FROM restored_tbl; COMMIT` to swap the content of the real table out for what we restored.

A problem here though is that this one big `INSERT INTO` txn can be very large, and in some cases hits the raft max command size, causing the restore to fail.

We _want_ to do these in a txn, because we can't take system tables "offline" to do non-transactional writes the way we can for other tables. Ideally we'd just be allowed to commit large transactions, but this may not be feasible. Another solution would to just swap the restored table's ID in at the namespace level, rather than copying the content over, but this will require removing the assumption that system tables have fixed, well known IDs.

We could give up the transactional nature and instead upsert the new rows in batches. While the table isn't _actually_ offline to reads, it may be okay that the restore is somewhat leaky in the isolation of its progress, and the upserts should handle resumes?

Epic CRDB-8816

**Comment by ajwerner** [comment]
> We could give up the transactional nature and instead upsert the new rows in batches. While the table isn't actually offline to reads, it may be okay that the restore is somewhat leaky in the isolation of its progress, and the upserts should handle resumes?

I don't get why we'd give up on the transactional nature. Isn't the problem that the execution layer is creating batch requests that are too large? Shouldn't it be up to the execution layer to not put too many rows into a batch if it's too big?

**Comment by ajwerner** [comment]
Put differently, what about the transaction is too large? I doubt it's the transaction record.

**Comment by dt** [comment]
I think #67537 closes this. I guess there's still a risk of a single large key, but I'm fine closing this as fixed until we see an example of that (though we may want a session var to opt-out of the proposed new single-key size limit guardrail?)
