### ISSUE TITLE
console: statements: want median exec time instead of mean

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#67520]
The Statement Details page (Execution Stats tab) shows me the mean execution time, and the stddev.
I'd like to replace the mean with a median. The mean is not a great statistic; it's too influenced by outliers. For a query, it's very useful to know if it's generally fast, and only occasionally slow. The mean doesn't make this easy to tease out.

Additionally, I'd like to also get a "max" in addition to the stddev.

Btw, the Overview tab on Statement Details seems to just show me the mean, not the stddev. I feel like in 20.2 it showed me the stddev, and it even had the graphical representation from the Statements list. I think that was very useful; we should definitely bring it back to the Overview I think.

Jira issue: CRDB-8587

**Comment by ajwerner** [comment]
Median is a challenge my friend. Perhaps time for some sketches or some reasonably sized histograms.

**Comment by kevin-v-ngo** [comment]
Placing this on the backlog for now until we hear more feedback. In terms of the default columns on the overview page, we are introducing a custom column selector which will help address this feedback.
