### ISSUE TITLE
Add link to feedback survey into DB Console

### ISSUE THREAD

**Issue by rsadres** [cockroachdb/cockroach#67534]
Please add a link to the CES survey into DB Console.

<Add Figma links>
<Add survey link>

Survey is powered by Appcues, no targeting.

**Comment by thtruo** [comment]
@rsadres just noticed a related issue https://github.com/cockroachdb/cockroach/issues/66615 

Would you say that duplicates this?

**Comment by rsadres** [comment]
Yes! Whoops, duplicate issue.

**Comment by thtruo** [comment]
Ack, I'll close this one off then :) Let's use #66615 as the source of truth moving forward
