### ISSUE TITLE
sql: plumb min_timestamp_bound to TableReader

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#67556]
Part of #66020.
Needed for **stage 1**.

See https://github.com/cockroachdb/cockroach/blob/025c53decd8eb00cb70a1d410692026c9f8614dc/docs/RFCS/20210519_bounded_staleness_reads.md#sql-execution.
Prototyped in #62239.

**Comment by otan** [comment]
is this the cfetcher/kvfetcher stuff? i'm not as familiar with the row exec stuff as it's not part of the SQL Experience domain :P
