### ISSUE TITLE
sql/opt: check query plan compatibility for bounded staleness reads

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#67558]
Part of #66020.
Needed for **stage 1**.

See https://github.com/cockroachdb/cockroach/blob/025c53decd8eb00cb70a1d410692026c9f8614dc/docs/RFCS/20210519_bounded_staleness_reads.md#sql-optimizer.

Epic CRDB-2527

**Comment by otan** [comment]
Heads up there is a TODO for this in code in https://github.com/cockroachdb/cockroach/blob/e45a521e5cd10441efcd95ed9d89319c2f9e529d/pkg/sql/opt/optbuilder/select.go#L1184.
