### ISSUE TITLE
changefeedccl: TestChangefeedPauseUnpauseCursorAndInitialScan is timing out under race

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#67565]
https://teamcity.cockroachdb.com/viewLog.html?buildId=3177376&buildTypeId=Cockroach_UnitTests_Testrace&tab=buildResultsDiv is a build where `TestChangefeedPauseUnpauseCursorAndInitialScan` is timing out after running an hour under race.

test-infra is going to skip this test under race for the time being.

Epic CRDB-7748

Jira issue: CRDB-8609

**Comment by Xiang-Gu** [comment]
There is another failure of this issue.
See https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_Test/5601257?buildTab=artifacts
