### ISSUE TITLE
sql: link kv transaction id to sql transaction id

### ISSUE THREAD

**Issue by cjireland** [cockroachdb/cockroach#67589]
**Is your feature request related to a problem? Please describe.**
When running many different applications (micro services) against a cockroach cluster it is extremely useful to be able to identify which connection has a lock on a particular row. If a command is blocked by another connection (say it has a long running TXN) currently it is not at all straightforward to identify the connection (and hopefully therefore the particular application) that is causing the block. 

**Describe the solution you'd like**
In Sybase I can run `sp_locks` to see locks and `sp_blocks` to see TXN blocking. They report the connection ID and resource locked.

Other dbs provide admin UIs / queries to quickly identify the issue (e.g. sql server [](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-tran-locks-transact-sql?view=sql-server-ver15) )

Perhaps it is possible to implement a command (for example `SHOW LOCKS FOR ALL|DATABASE|TABLE <name>`) that will return details of all current locks, the impacted range(s)/rows, the associated table, the connection running the SQL.

**Describe alternatives you've considered**

We did try a select over `crdb_internal.cluster_transactions` and `cluster_sessions `and `tables` but it wasn't perfect.

**Additional context**

Jira issue: CRDB-8619

**Comment by rafiss** [comment]
Additionally, postgres has the `pg_locks` view, which we may want to think about for PG compatibility: https://www.postgresql.org/docs/current/view-pg-locks.html

**Comment by jordanlewis** [comment]
We'd need to get information from @cockroachdb/kv to surface this information.

Regarding level of effort on the KV side, @nvanbenschoten says:

>  I don’t think it would be a huge project if we were only trying to associate each lock with a given connection, as opposed to a given SQL statement. We could introduce an API into KV to pull all the locks in a span of keys, which would include each of their transaction IDs. We’d then need SQL to pair up transaction IDs with connections.
