### ISSUE TITLE
stability: large snapshots causing issues

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6758]
`beta` cluster was not doing so well. I stopped all nodes, then restarted all.

Within minutes, node 1 (`104.196.24.126`) died from OOM.
Interestingly, we have the following snapshot mentioned ~30 seconds before node death:
```
I160517 20:35:52.483989 storage/replica_raftstorage.go:517  generated snapshot for range 1115 at index 3400729 in 1m15.065996628s. encoded size=2088503789, 150224 KV pairs, 2843707 log entries
```

Last few RSS log entries:
```
I160517 20:34:51.900374 server/status/runtime.go:160  runtime stats: 3.6 GiB RSS, 206 goroutines, 660 MiB active, 66858.20cgo/sec, 1.43/0.42 %(u/s)time, 0.00 %gc (5x)
I160517 20:35:01.900887 server/status/runtime.go:160  runtime stats: 4.5 GiB RSS, 218 goroutines, 1.0 GiB active, 74560.60cgo/sec, 1.27/0.35 %(u/s)time, 0.00 %gc (3x)
I160517 20:35:11.901910 server/status/runtime.go:160  runtime stats: 5.2 GiB RSS, 205 goroutines, 1.3 GiB active, 68541.16cgo/sec, 1.22/0.38 %(u/s)time, 0.00 %gc (2x)
I160517 20:35:21.907059 server/status/runtime.go:160  runtime stats: 5.9 GiB RSS, 189 goroutines, 1.8 GiB active, 61865.78cgo/sec, 1.11/0.36 %(u/s)time, 0.00 %gc (1x)
I160517 20:35:31.902851 server/status/runtime.go:160  runtime stats: 6.4 GiB RSS, 198 goroutines, 1.9 GiB active, 66783.49cgo/sec, 1.21/0.34 %(u/s)time, 0.00 %gc (1x)
I160517 20:35:41.903725 server/status/runtime.go:160  runtime stats: 7.3 GiB RSS, 192 goroutines, 2.5 GiB active, 85075.72cgo/sec, 0.59/0.27 %(u/s)time, 0.00 %gc (0x)
I160517 20:35:51.909675 server/status/runtime.go:160  runtime stats: 9.8 GiB RSS, 216 goroutines, 4.4 GiB active, 67351.58cgo/sec, 1.72/0.52 %(u/s)time, 0.00 %gc (2x)
I160517 20:36:01.904553 server/status/runtime.go:160  runtime stats: 14 GiB RSS, 201 goroutines, 6.2 GiB active, 28838.63cgo/sec, 1.02/0.78 %(u/s)time, 0.28 %gc (2x)
I160517 20:36:11.915123 server/status/runtime.go:160  runtime stats: 14 GiB RSS, 202 goroutines, 5.2 GiB active, 35097.97cgo/sec, 1.56/0.42 %(u/s)time, 0.00 %gc (0x)
I160517 20:36:21.914497 server/status/runtime.go:160  runtime stats: 14 GiB RSS, 198 goroutines, 6.3 GiB active, 72463.77cgo/sec, 1.71/0.51 %(u/s)time, 0.00 %gc (0x)
```

Full log:
[node1.stderr.gz](https://github.com/cockroachdb/cockroach/files/269124/node1.stderr.gz)

**Comment by tamird** [comment]
@cuongdo sounds related to the not-splitting issues you've been seeing

**Comment by cuongdo** [comment]
Possibly. Would love to get in something that lets us see range sizes as
part of the debug CLI features, to verify that.

**Comment by tschottdorf** [comment]
We should check for oversized ranges, but what we were seeing today looks
expected as the block writer writes randomly and so the growth of each
individual range is proportional to 2^{-#ranges} and so there wouldn't be
many splits. But you also mentioned something about the range count going
up by a lot in a short amount of time, which seems counterintuitive. Can't
hurt to get more insight into that (though the range events with a big
enough time window should already show the latter now).

On Tue, May 17, 2016 at 9:55 PM Cuong Do <notifications@github.com> wrote:

> Possibly. Would love to get in something that lets us see range sizes as
> part of the debug CLI features, to verify that.
> On Tue, May 17, 2016 at 5:39 PM Tamir Duberstein <notifications@github.com
> >
> wrote:
>
> > @cuongdo sounds related to the not-splitting issues you've been seeing
> > On May 17, 2016 16:50, "marc" <notifications@github.com> wrote:
> >
> > > beta cluster was not doing so well. I stopped all nodes, then restarted
> > > all.
> > >
> > > Within minutes, node 1 (104.196.24.126) died from OOM.
> > > Interestingly, we have the following snapshot mentioned ~30 seconds
> > before
> > > node death:
> > >
> > > I160517 20:35:52.483989 storage/replica_raftstorage.go:517 generated
> > snapshot for range 1115 at index 3400729 in 1m15.065996628s. encoded
> > size=2088503789, 150224 KV pairs, 2843707 log entries
> > >
> > > Last few RSS log entries:
> > >
> > > I160517 20:34:51.900374 server/status/runtime.go:160 runtime stats: 3.6
> > GiB RSS, 206 goroutines, 660 MiB active, 66858.20cgo/sec, 1.43/0.42
> > %(u/s)time, 0.00 %gc (5x)
> > > I160517 20:35:01.900887 server/status/runtime.go:160 runtime stats: 4.5
> > GiB RSS, 218 goroutines, 1.0 GiB active, 74560.60cgo/sec, 1.27/0.35
> > %(u/s)time, 0.00 %gc (3x)
> > > I160517 20:35:11.901910 server/status/runtime.go:160 runtime stats: 5.2
> > GiB RSS, 205 goroutines, 1.3 GiB active, 68541.16cgo/sec, 1.22/0.38
> > %(u/s)time, 0.00 %gc (2x)
> > > I160517 20:35:21.907059 server/status/runtime.go:160 runtime stats: 5.9
> > GiB RSS, 189 goroutines, 1.8 GiB active, 61865.78cgo/sec, 1.11/0.36
> > %(u/s)time, 0.00 %gc (1x)
> > > I160517 20:35:31.902851 server/status/runtime.go:160 runtime stats: 6.4
> > GiB RSS, 198 goroutines, 1.9 GiB active, 66783.49cgo/sec, 1.21/0.34
> > %(u/s)time, 0.00 %gc (1x)
> > > I160517 20:35:41.903725 server/status/runtime.go:160 runtime stats: 7.3
> > GiB RSS, 192 goroutines, 2.5 GiB active, 85075.72cgo/sec, 0.59/0.27
> > %(u/s)time, 0.00 %gc (0x)
> > > I160517 20:35:51.909675 server/status/runtime.go:160 runtime stats: 9.8
> > GiB RSS, 216 goroutines, 4.4 GiB active, 67351.58cgo/sec, 1.72/0.52
> > %(u/s)time, 0.00 %gc (2x)
> > > I160517 20:36:01.904553 server/status/runtime.go:160 runtime stats: 14
> > GiB RSS, 201 goroutines, 6.2 GiB active, 28838.63cgo/sec, 1.02/0.78
> > %(u/s)time, 0.28 %gc (2x)
> > > I160517 20:36:11.915123 server/status/runtime.go:160 runtime stats: 14
> > GiB RSS, 202 goroutines, 5.2 GiB active, 35097.97cgo/sec, 1.56/0.42
> > %(u/s)time, 0.00 %gc (0x)
> > > I160517 20:36:21.914497 server/status/runtime.go:160 runtime stats: 14
> > GiB RSS, 198 goroutines, 6.3 GiB active, 72463.77cgo/sec, 1.71/0.51
> > %(u/s)time, 0.00 %gc (0x)
> > >
> > > Full log:
> > > node1.stderr.gz
> > > <https://github.com/cockroachdb/cockroach/files/269124/node1.stderr.gz
> >
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/cockroachdb/cockroach/issues/6758>
> > >
> >
> > —
> > You are receiving this because you were mentioned.
> >
> >
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/cockroachdb/cockroach/issues/6758#issuecomment-219862452
> >
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/6758#issuecomment-219904698>
>
-- 

-- Tobias

**Comment by bdarnell** [comment]
The replicate queue won't try to move a range that is that huge, which means it must have grown after the replication queue schedule the range for replication. Here's a theory:

* One node dies, but hasn't been dead long enough for the StorePool on the other nodes to consider it dead.
* The replicate queue runs, picks a (normal-sized) range to move, and assigns the dead node as its new replica.
* Replication can't proceed because the target is down; the range limps along in 2/3 or 3/4 mode.
* Because one of the replicas is not acknowledging writes, raft_log_queue doesn't GC anything (#6012)
* The log keeps growing, so by the time the down node comes back up, a huge snapshot is required

If one replica can't keep up, we should try to move the range off of that node, and if we can't, we may need to truncate the log even if it means that the lagging replica will need a snapshot when it rejoins. We need to be careful about this - if we're too quick to GC the logs then we may not be able to catch a replica up in the time it takes to process a snapshot.

I think preemptive snapshots will also mitigate this problem, but not eliminate it.

**Comment by petermattis** [comment]
Closing now that we're more aggressive about truncating the raft log when there is a trailing replica and we can handle splitting a large range by carving off a small chunk from the front instead of splitting it evenly.
