### ISSUE TITLE
logictestccl: the test target often times out at 30 minutes, while the median run time is well below 30 minutes

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#67598]
Many CI runs currently fail with a 30 minutes timeout in `logictestccl`. [Example here](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/3181984?). Possibly (but not certainly) in TestTenantLogic.

I am not sure this is expected, given we have many runs which are well below 30 minutes.
It may be a deadlock that is difficult to encounter.

My suggestion would be to stress-test that package, and detect when a stress run does not make progress any more (which is a different exercise than waiting it to fail).

![image](https://user-images.githubusercontent.com/642886/125627503-b988c1aa-0321-4571-9bf9-aa2cfcf6d482.png)

Jira issue: CRDB-8624

**Comment by rafiss** [comment]
Is this still happening?

**Comment by rafiss** [comment]
I think we can close this, now that the logic tests have been split into different subtests. (https://github.com/cockroachdb/cockroach/pull/84221)
