### ISSUE TITLE
roachtest: bazel CI fails, while github CI succeeds

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#67595]
In many of my latest PRs I see bazel CI fail as follows, while github CI is green:
![image](https://user-images.githubusercontent.com/642886/125625832-a66222d0-5538-4a2d-9f1f-0f948be46a9e.png)
![image](https://user-images.githubusercontent.com/642886/125625867-d5725c16-daa6-4ec8-8a7c-7fb93a706678.png)

**Comment by knz** [comment]
Example run:
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_GitHubCiOptional/3182077?

**Comment by rickystewart** [comment]
`faa4c2ccdaeca01eca3ccee29a8a64973cf8b043` removed the `broken_in_bazel` tag from the `pkg/cmd/roachtest` tests. It needs to be added back.
