### ISSUE TITLE
kvserver: failure in TestStoreRangeMergeWatcher

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#67596]
Found in https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/3182115?

![image](https://user-images.githubusercontent.com/642886/125626678-f3fa892c-dfd0-4b3f-bccb-7a482d5724ec.png)

cc @cockroachdb/kv-triage

**Comment by tbg** [comment]
dup https://github.com/cockroachdb/cockroach/issues/67171
