### ISSUE TITLE
kv: rangefeeds use too many goroutines

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#67600]
_While this problem exists, it is not the most pressing issue. At the time of writing, this issue stands as a problem statement rather than a call to solve it immediately_

**Is your feature request related to a problem? Please describe.**

Rangefeeds use `O(ranges)` goroutines. For clusters with lots of ranges, this is probably too much. We've worked reasonably hard to not have `O(ranges)` goroutines elsewhere in `kvserver` with the raft scheduler, per-node raft transports, and a client concurrency bound. 

Rangefeeds use a lot of goroutines:

On kvserver:
* 1 per range with an active registration (the `Processor`).
* 1 per active registration
* 1 per stream RPC from gRPC

On kvclient:
* 1 per range

**Describe the solution you'd like**

Eliminating these goroutines feels challenging. The best that I can imagine is two goroutines on the server side per client interested in data housed on the server. That only seems plausible in the running state, after all catchup scans have occurred. Catchup scans likely deserve their own goroutine. 

Implementing such a thing would take a more complex protocol which allowed clients to join an existing stream and which dealt with all the various lifecycle events of a RangeFeed.

**Describe alternatives you've considered**

Larger ranges would help, but aren't totally satisfying.

**Additional context**

It's useful to consider cases of 10s of TBs of data per node. We ought to be thinking about supporting that sort of use case. 

Relates loosely to https://github.com/cockroachdb/cockroach/issues/34999. 

Jira issue: CRDB-8625

**Comment by nvanbenschoten** [comment]
I agree that the first step here is to demonstrate that this is a problem and that the cost of idle goroutines on idle ranges with active rangefeeds is too high. If we do demonstrate that, then there are two directions I imagine we could take this issue, though I'm sure there are others as well:

> 1 per active registration
> 1 per stream RPC from gRPC
> The best that I can imagine is two goroutines on the server side per client interested in data housed on the server.

These two goroutines did not exist in the original design of the rangefeed processor. The rangefeed per active registration was added later to ensure that a single slow consumer did not block the rangefeed processor, blocking updates to other consumers and causing Raft to disconnect it - a noble goal. But this was solved by adding a new per-registration goroutine within the rangefeed processor and continuing to let the RPC handler goroutine [remain idle](https://github.com/cockroachdb/cockroach/blob/1c609f2591f4834eacf7aa92cb43401f5c80d121/pkg/kv/kvserver/replica_rangefeed.go#L240-L242) for the duration of the rangefeed. We could try to put this RPC handler goroutine to work and have it serve the role of this per-registration goroutine within the rangefeed processor. Though I'd caution that doing so may not have a positive effect on the code structure.

Another option is to snapshot the state of idle rangefeed processors and then shut down their processor goroutine and each of their registration goroutines. This would be analogous to range quiescence. On large clusters, we expect the vast majority of ranges to be inactive, so this would be an effective way to cut down the cost of rangefeeds spanning most ranges in a cluster. The most important consideration here would be to make unquiescence fast enough and cheap enough to go unnoticeable. I have not thought through how periodic closed timestamp updates would work with this scheme and maybe this undermines the idea of declaring any rangefeed idle, but there may be fast-paths here for checkpoints on ranges with no active intents, as these closed timestamp updates can be passed straight through to consumers as resolved timestamp checkpoints.

All this said, I do wonder whether the more immediately high impact issue is that we maintain an open gRPC stream per range. Again, this would require benchmarking, but I'd imagine the cost of a gRPC stream to be greater than the associated cost of the idle goroutine on either side. We could explore multiplexing rangefeeds for multiple ranges on a single gRPC stream if this proves to be an issue on large clusters.

**Comment by miretskiy** [comment]
Closing; mux rangefeeds (undertested as they maybe) solve this problem by having single go routine per node.
