### ISSUE TITLE
cli,sql: mismatch between CLI code and output of SHOW LAST QUERY STATISTICS

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#67618]
As discussed with @arulajmani and @otan over [this comment](https://github.com/cockroachdb/cockroach/pull/67489#discussion_r669555717)

- the SHOW LAST QUERY STATISTICS stmt emits INTERVAL value
- the server-side encoding of its results is (now) configurable via the IntervalStyle session var (#67210) 
- however the CLI Code hard-codes the representation to POSTGRES
- so if the server-side setting is modified, the CLI code stops working

What can we do about this?

Options:

1. extend the result of SHOW LAST QUERY STATISTICS to also include the value of IntervalStyle as an additional result column. Make the CLI code use that to decide how to parse.
2. change the SHOW statement to reports microseconds as an INT value (trivial to parse cli-side)
3. switch the output type of SHOW to be STRING, and compute the value as `encode(<interval value>, 'postgres')`  (i.e. keep an interval in the result, but guarantee the encoding is always the same and is impervious to session var)
4. add a new parameter to the SHOW  syntax to indicate use of an INT type, and change the CLI code to use that (and assume INT). In that case, the fallback when the new syntax is not supported, is to use the fixed-format postgres interval style to parse the values.
5. add a new session var `crdb_client_options` where the CLI can indicate its "API level" (specifically, the server-side functionality it needs). We change the CLI to set this upon new connections. While processing the SHOW statement, the server chooses the list of result columns / result type etc based on the configured crdb client options.

| Solution | Pros | Cons |
|--|--|--|
| report the encoding style | trivial to implement server-side | requires the inclusion of both interval parsers in the CLI code (need to include `duration` package inside CLI), works against the goals in  #67470 |
| report durations as INT | trivial to support CLI-side, reduces CLI complexity | need a fallback for when results are provided by previous-version servers; also won't allow previous-version CLI to use stats from new-version server |
| switch result to STRING | CLI code can remain the same, given the representation is wire-compatible | a little bit odd to use a string type for an interval representation |
| new syntax clause | natural extension path, preserves compat of prev-version CLI with new-version server | need two branches and fallback in CLI |
| API versioning via `crdb_client_options` | provide us a cross-version story without tweaks to SQL syntax | more server-side complexity to support the options; might be the first time we let the column schema of a stmt depend on a session var |

**Comment by knz** [comment]
@otan FYI, discussed this with @arulajmani, I'd like to proceed as follows:

- for PR #67489 I'll move forward with my small string parser, and simply extend it to support days (I don't really believe we need that, but it's not a major change, so OK).
- I'll make a note in that code to refer to this issue (#67618) and also highlight that **we do not want to depend on the `duration` package from the CLI code** . This excludes solution 1 in the table above.

The issue here remains to be fixed afterwards. I don't personally have a preference, but it's also really a SQL experience issue so my preference is really to have that team address this. :)

Arul says that generally he likes the API versioning var better (solution 5). However, as a stop-gap Arul thinks that solution 3 is actually quite lightweight and probably the simplest thing we can do.

**Comment by otan** [comment]
The code you mention I don't think works for ISO8601 either.

**Comment by otan** [comment]
> switch result to STRING

can't do that; string casts also obey `IntervalStyle`

> report durations as INT

this is fine for me -- `EXTRACT(epoch FROM interval)` as the SELECT clause, convert number to microseconds, seems straightforward. no backwards compatible issues.

> requires the inclusion of both interval parsers in the CLI code (need to include duration package inside CLI), works against the goals in #67470

the duration package seems small and it's exclusion feels like a very small "win" compared to other big fish. if we feel strongly, the INT idea sounds great.

> I'll move forward with my small string parser

i'm not convinced that is the best solution at this moment. at least, i'm not sure i see a weakness in using `EXTRACT(epoch from interval)`

**Comment by knz** [comment]
> The code you mention I don't think works for ISO8601 either.

That does not matter if the server always sends the strings in the 'postgres' style.

> >  switch result to STRING

> can't do that; string casts also obey IntervalStyle

No that's not what I had in mind. Instead in `func (ex *connExecutor) runShowLastQueryStatistics` do like this:

replace

```go
        return res.AddRow(ctx,
                tree.Datums{
                        tree.NewDInterval(duration.FromFloat64(parseLat), types.DefaultIntervalTypeMetadata), ...
```

by

```go
  i := tree.NewDInterval(duration.FromFloat64(parseLat), types.DefaultIntervalTypeMetadata)
  var buf bytes.Buffer
  i.Duration.FormatWithStyle(&buf, IntervalStyle_POSTGRES)
  is := buf.String()
  // same for the other values

  return res.AddRow(ctx, tree.Datums{is, ...}
```

then the string is always encoded the same. This is backward-compatible with 21.1 CLI, and would solve this issue.

**Comment by knz** [comment]
>  i'm not sure i see a weakness in using EXTRACT(epoch from interval).

The weakness is that if we change the server-side type, v21.1 CLI cannot connect to v21.2 server any more. This cross-version compatibility is a requirement.

**Comment by otan** [comment]
> That does not matter if the server always sends the strings in the 'postgres' style.

can you verify this is true? i would've thought it would send it in the same style as the session style.

> No that's not what I had in mind. Instead in func (ex *connExecutor) runShowLastQueryStatistics do like this:

ah, i thought it was a SQL query from an internal table, not a custom statement with hardcoded variants.
