### ISSUE TITLE
kv: track lock acquisition time in lock table

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#67619]
Taken from #67350.

We currently don't track the time that a lock was acquired in the `lockTable`. This prevents us from accurately determining how long a lock has been held, which would be an interesting metric to export. We should augment the `lockTable` with this information and then expose it through a new metric.

Jira issue: CRDB-8633

**Comment by AlexTalks** [comment]
Resolved by #76395.
