### ISSUE TITLE
Surface index usage statistics in the CC/DB console: Table overview

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#67647]
We are capturing index usage statistics: https://github.com/cockroachdb/cockroach/issues/64740. This issue tracks building an experience around this view on the table overview page. 

Figma mockups: https://www.figma.com/file/xdmwvnFQd6KkO9RJ0XLDH0/22.1_SQL-obsrv_query-performance?node-id=3498%3A33376

CC @Annebirzin 

Epic: CRDB-9075

**Comment by maryliag** [comment]
@Annebirzin do we have a design for this?

**Comment by Annebirzin** [comment]
@maryliag Designs for index usage stats are here: https://www.figma.com/file/Tzrm57PT9S9Y8YtkTKejIT/21.2_cluster-ui_databases?node-id=2424%3A57423

There are screens at the bottom for future iterations, but the top two rows represent 
- V1: Adding checks for 'unused indexes' 
- V2: Adding checks for 'wide indexes'

cc @kevin-v-ngo
