### ISSUE TITLE
sql: enable locality validation when setting zone configs for secondary tenants

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#67678]
**Is your feature request related to a problem? Please describe.**

Now that https://github.com/cockroachdb/cockroach/pull/67098 has landed, tenants can get access to node locality information via the connecter API. This means the check that skips locality validation when setting zone configs for secondary tenants can be removed once we move the prototype to master.

**Comment by irfansharif** [comment]
I think this was just #69275.
