### ISSUE TITLE
sql: better document sql.defaults. cluster settings

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#67672]
We should make sure that the description of any `sql.defaults.*` cluster setting makes it clear that the setting doesn't apply to existing sessions (including the current session).

We should also add a notice that reiterates that every time such a cluster setting is changed.

Jira issue: CRDB-8663

**Comment by sheaffej** [comment]
Adding some additional context. As a user it's not clear which cluster settings would only take affect on new sessions. This leads to confusion when a user changes a cluster setting and does not see the behavior change in their current session. 

It is reasonable that some cluster settings take effect immediately on all sessions, and other cluster settings only take effect for new sessions. 

Therefore we should make it clearer to the user which settings only affect new sessions, to avoid their confusion.

**Comment by rafiss** [comment]
For 22.1 we plan to deprecate/hide the `sql.defaults.*` cluster settings. Instead, we will be pointing users to use the new `ALTER ROLE ALL SET DEFAULT varname = val` syntax, which will set a global default value for a session variable.

So maybe we should just close this issue? Or would it be worth documenting for 21.2 and earlier releases still?

**Comment by RaduBerinde** [comment]
I think it's worth adding a note in the description of every `sql.defaults.*` settings for 21.2 and earlier.

Adding a notice would be too much throw-away work, I'd skip that.
