### ISSUE TITLE
sql: DROP TABLE unsplits ranges sequentially in transaction.

### ISSUE THREAD

**Issue by postamar** [cockroachdb/cockroach#67673]
**Describe the problem**

We've observed a customer's cluster to be misbehaving because of this.

**To Reproduce**

Run a cluster with large latencies between nodes so that unsplitting a range is slow, and drop a table with a lot of ranges. A large table fresh from a restore should do the trick. The corresponding long-running transaction will hold locks on `system.descriptor` and `system.jobs` making them effectively unreadable for other transactions for a long period of time.

**Expected behavior**
This unsplitting could just as well be (1) parallelized, and (2) run asynchronously in a job or even a GC job.

**Additional data / screenshots**
See https://github.com/cockroachlabs/support/issues/1061 for details on the customer incident.

**Environment:**
Observed in 20.2 but this affects all versions.

**Comment by ajwerner** [comment]
Moving the logic to happen in the async job while not holding locks would effectively solve the problem (i.e., do (2) first).

**Comment by ajwerner** [comment]
This also affects `TRUNCATE`.

**Comment by ajwerner** [comment]
We're going to do something about this soon.

**Comment by ajwerner** [comment]
A reason to not do it until the GC job starts running is that we may want to reclaim the names.
