### ISSUE TITLE
Allow now() to be used along with 'as of system time'

### ISSUE THREAD

**Issue by daniel-crlabs** [cockroachdb/cockroach#67684]
**Is your feature request related to a problem? Please describe.**

Customers need to be able to run queries which sometimes are blocked because of deadlocks caused by `INSERT` statements.
The `SELECT` will be blocked if it tries to read anything that was already modified by the `INSERT` otherwise. This is expected. The `SELECT` starts after the `INSERT` so it needs to "see" the results of the `INSERT`. 
`AS OF SYSTEM TIME` can be used to avoid having to wait for the `INSERT` to finish.

**Describe the solution you'd like**

The following `SELECT` call is not blocked, since it uses `AS OF SYSTEM TIME`, however, we have to specify the actual time. It would be great to be able to specify a time frame, i.e 5 minutes from now.

This works, but it requires us to know the system time in order to choose an accurate time:

```
root@lab-kub01:30007/defaultdb> select count(*) from destination.t1 as of system time '2021-07-15 18:25:18';
```
This would be the ideal scenario, calculate 5 minutes ago (or some other arbitrary time) based on now():

```
root@lab-kub01:30007/defaultdb> select count(*) from destination.t1 as of system time (NOW() - interval '5 minutes');
ERROR: AS OF SYSTEM TIME: only constant expressions or follower_read_timestamp are allowed
```

**Describe alternatives you've considered**

The alternative is to manually figure out the system time and then use it in the query

```
root@lab-kub01:30007/defaultdb> SELECT NOW() - interval '5 minutes';
              ?column?
------------------------------------
  2021-07-15 19:34:42.716297+00:00
(1 row)

Time: 1ms total (execution 0ms / network 1ms)

root@lab-kub01:30007/defaultdb> select count(*) from destination.t1 as of system time '2021-07-15 19:34:42.716297+00:00';
  count
---------
      0
(1 row)

Time: 3ms total (execution 2ms / network 1ms)
```

**Comment by ajwerner** [comment]
The syntax for this is to just use an interval. For example:

```sql
select count(*) from destination.t1 as of system time '-5m';
```

See: 
>  negative INTERVAL | Added to statement_timestamp(), and thus must be negative.

https://www.cockroachlabs.com/docs/v21.1/as-of-system-time#parameters

**Comment by daniel-crlabs** [comment]
Thank you so much for pointing me in the right direction. I'm not sure how I did not see this since I looked for it. Appreciate the example and the docs reference.
