### ISSUE TITLE
sql: support `SHOW CREATE ALL TYPES;`

### ISSUE THREAD

**Issue by mgoddard** [cockroachdb/cockroach#67685]
When working with EXPORT / IMPORT of a database, we are able to run

  `SHOW CREATE ALL TABLES;`

to get the DDL for all our tables.  If there are enums referenced by any of these, there doesn't appear to be a way to recover their definitions.  Does it make sense to then have a

  `SHOW CREATE ALL TYPES;`

so that this is possible?  The output from `SHOW ENUMS FROM ...` isn't a valid statement that can be used to recreate the enums.

**Comment by ajwerner** [comment]
Have a look at `SELECT create_statement FROM crdb_internal.create_type_statements;`.

**Comment by bragaigor** [comment]
Thanks @mgoddard  for opening the issue. That works like a charm, thank you @ajwerner . If we had `SHOW CREATE ALL TYPES` to simulate that logic it would great

**Comment by RichardJCai** [comment]
Also we'll probably want to implement `SHOW CREATE TYPE` as well.

**Comment by rabingaire** [comment]
Hey, I looked into the codebase and have an idea of implementing this feature but I also have a question do I also need to implement the `crdb_internal.show_create_all_types` builtin function like you guys did for `crdb_internal.show_create_all_tables`
