### ISSUE TITLE
sql: Support 'COMMENT ON SCHEMA'

### ISSUE THREAD

**Issue by 13rac1** [cockroachdb/cockroach#67689]
**Is your feature request related to a problem? Please describe.**
`COMMENT ON SCHEMA` is not supported.

**Describe the solution you'd like**
`COMMENT ON SCHEMA` is supported.

Support for `COMMENT ON` for tables, table columns, and databases was implemented in 2019 for https://github.com/cockroachdb/cockroach/issues/19472 then the issue was closed by @jordanlewis because schemas were not supported at all: https://github.com/cockroachdb/cockroach/issues/19472#issuecomment-486087994
> This is done but for schemas which we don't support anyway - closing. 

`CREATE SCHEMA` was implemented in 2020 https://github.com/cockroachdb/cockroach/pull/50613 therefore `COMMENT ON SCHEMA` is (should be?) unblocked. Might be a good first PR as there are examples in:
* [sql: support COMMENT ON DATABASE](https://github.com/cockroachdb/cockroach/pull/33057)
* [sql: support COMMENT ON COLUMN](https://github.com/cockroachdb/cockroach/pull/33355)

*I may implement the PR, but am not claiming it yet.*

**Describe alternatives you've considered**
I am skipping unsupported SQL.

**Comment by jordanlewis** [comment]
Thanks, you're absolutely right. Please feel free to take a stab at the PR!

**Comment by sagar23sj** [comment]
Hi, I would like to work on this PR.

**Comment by knz** [comment]
we don't "reserve" PRs for one person. Anyone should free to work on it; you don't have to announce your work ahead of time.

**Comment by dheerajdlalwani** [comment]
Hey! I would like to work on this issue, but I have absolutely no clue where to start. Can someone point me to some relevant documentation/internal docs?

**Comment by knz** [comment]
What about you look at the previous PRs that implemented COMMENT ON TABLE / COMMENT ON DATABASE, then do something similar.
