### ISSUE TITLE
sql:  Hook the sqlliveness session used for the instance ID to the sql transaction deadline.

### ISSUE THREAD

**Issue by rimadeodhar** [cockroachdb/cockroach#67719]
With the new sqlinstance subsystem in multi-tenant environment, we set up a new sql instance identifier for a SQL pod which is tied to a sqlliveness.Session. The SQL pod is shut down when the sqlliveness.Session expires. We need to ensure that this session expiry is tied to the sql transaction deadline to ensure all in-progress transactions are committed or aborted prior to the session expiry and SQL pod shutdown.

**Comment by ajwerner** [comment]
I *think* this only matters if you call `unique_rowid()` with an instance ID leased using a session. That being said, I also think it would be safe to just always use this deadline for every transaction in a tenant sql pod. 

I think that the place where we want to set this deadline is:

https://github.com/cockroachdb/cockroach/blob/8c1463e9c9ed3924c0ddfac014a6ab6e24690854/pkg/sql/conn_executor.go#L2485-L2488

And also probably https://github.com/cockroachdb/cockroach/blob/8c1463e9c9ed3924c0ddfac014a6ab6e24690854/pkg/sql/conn_executor_exec.go#L260

These may not be the best spots but they align with the current usage. We'll need to rework the descs collection to not actually be setting the deadline but rather to be providing it as a timestamp.

I do think we'll want to take some care to make sure that a given transaction always uses the same sqlliveness session.

**Comment by andy-kimball** [comment]
Does `unique_rowid` work properly in tenant clusters? Is it all wired up with the new instance IDs?

**Comment by ajwerner** [comment]
I don't know for a fact but I would assume so. I believe @rimadeodhar's earlier PR set the value that gets returned from `SQLInstanceID()` to the leased value.

https://github.com/cockroachdb/cockroach/blob/6b2e2c4cd21516918f07f4778b7f0e842469e3d1/pkg/sql/sem/builtins/builtins.go#L2000

The hazard is if you have a partitioned pod such that it doesn't know for a fact that it has been killed may resume and commit a transaction using an instance ID that might have been acquired by a new pod. If we set the deadline then the transaction would not commit. It's an edge case.

As another approach to mitigate it, we could make reclaiming IDs lazy as opposed to eager. By eager I mean that today if ID 1 has lease but that lease is expired, I believe we'll eagerly claim 1 and overwrite that lease. We could choose to only go take an expired lease if there are none available or something. Then you'd really need to spin up and down a lot of pods.

**Comment by andy-kimball** [comment]
@rimadeodhar, maybe you could add a test case for `unique_rowid` in a tenant cluster, so we can be sure it works properly now and in the future?

**Comment by rimadeodhar** [comment]
Yes, it is wired through as a result of the PR I recently merged. Specifically, the [nodeID component of execCfg](https://github.com/cockroachdb/cockroach/blob/26eaca0685e64f339cbf599092309ab10b103cef/pkg/server/server_sql.go#L601) is initialized with the instanceID on a tenant cluster which is then used by all downstream components including unique_rowid builtin. I'll add a testcase to enforce this.
