### ISSUE TITLE
sql: a txn can obtain a lease on an arbitrarily-old descriptor version

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#6774]
I think there's nothing preventing a sql txn from obtaining a lease at an old version of a descriptor. That's not good, as the system is supposed to only have leases on at most the last 2 versions at any point in time.
When a lease is requested from the `LeaseManager` and it's not found in the cache, the descriptor is read from the database in the context of the current txn. If the transaction has started a while ago and has an old timestamp, it will read an old version of the descriptor. When the lease is inserted in the database, there's nothing preventing it to be written even if the version is more than 1 below the current version.

Also see #6773.

**Comment by vivekmenezes** [comment]
The lease manager uses a different transaction to read the table descriptor. I don't think this is an issue.

**Comment by andreimatei** [comment]
I don't think that would work. You don't want a descriptor that's too new for you either.
You want the newest written before your timestamp. If that's too old, I think you need to restart.

**Comment by vivekmenezes** [comment]
Not true. If you have a lease for it you can use it. Remember you are allowed to use two table descriptors at any point of time. All you care about is whether you are ahead of the descriptor timestamp. It will be worth listing a particular scenario for this bug.

**Comment by vivekmenezes** [comment]
In other words, for a descriptor written at time T1 and T2, where T2 > T1 and where T2 is the latest timestamp.

1. All transactions need to have a timestamp > T1 (not T2), and 
2. When using a particular lease, the transaction needs to have a timestamp greater than the lease it is using.
3. It is legal for a transaction to have a timestamp T3 > T2 and use a lease with timestamp T1.
4. It is illegal for a transaction to have a timestamp T4, where T1 < T4 < T2, and use the lease with timestamp T2.

**Comment by andreimatei** [comment]
Right. Here's a corollary to 1):
1') For a descriptor with writes `v1(T1), v2(T2), v3(T3)`, it should be illegal to obtain a lease on `v1`. 

And I think we brake this rule, because what you said above doesn't seem to be true (the `LeaseManager` does *not* use a new txn to acquire leases): https://github.com/cockroachdb/cockroach/blob/e18db5d/sql/lease.go#L129
So if you're a txn with timestamp `T1+ε`, you can get a lease on `v1`.
No?

**Comment by spencerkimball** [comment]
@andreimatei could you update this issue? It's a year old now and slated for 1.0.

**Comment by vivekmenezes** [comment]
Worth fixing for 1.0

**Comment by vivekmenezes** [comment]
We're not going to fix this for 1.0, but will put the fix into the first patch release.

**Comment by vivekmenezes** [comment]
the fix is too risky to put into 1.0

**Comment by vivekmenezes** [comment]
closed by #17307
