### ISSUE TITLE
cli: cockroach quit doesn't work if you include unnecessary flags

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#6776]
Please follow the steps below to help us help you.
1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. On most unix-based systems
   running with defaults, this boils down to the output of

```
JESSEs-MacBook-Pro:cockroach jesseseldess$ grep -F '[config]' cockroach-data/logs/cockroach.INFO
I160518 11:55:50.508106 util/log/clog.go:998  [config] file created at: 2016/05/18 11:55:50
I160518 11:55:50.508106 util/log/clog.go:998  [config] running on machine: JESSEs-MacBook-Pro
I160518 11:55:50.508106 util/log/clog.go:998  [config] binary: CockroachDB beta-20160512-121-g7332e99 (darwin amd64, built 2016/05/16 20:22:13, go1.6)
I160518 11:55:50.508106 util/log/clog.go:998  [config] arguments: [./cockroach start --background --background=false]
```
1. Please describe the issue you observed:
- What did you do?

I started up a local node. Then I tried to run `quit` with an unnecessary flag (only `--http-port` is required).
- What did you expect to see?

When including the required flag (`--http-port`) and an unnecessary flag, I expected `quit` to work. When including only an unnecessary flag, I expected a helpful error instructing me to use the `--http-port` flag.
- What did you see instead?

In both of the above cases, I received an `unknown flag` error and `Failed running "quit"`:

```
JESSEs-MacBook-Pro:cockroach jesseseldess$ ./cockroach start
build:     beta-20160512-121-g7332e99 @ 2016/05/16 20:22:13 (go1.6)
admin:     http://localhost:8080
sql:       postgresql://root@localhost:26257?sslmode=disable
logs:      cockroach-data/logs
store[0]:  path=cockroach-data

JESSEs-MacBook-Pro:cockroach jesseseldess$ ./cockroach quit --port=26257
Error: unknown flag: --port
Failed running "quit"

JESSEs-MacBook-Pro:cockroach jesseseldess$ ./cockroach quit --store=cockroach-data
Error: unknown flag: --store
Failed running "quit"

JESSEs-MacBook-Pro:cockroach jesseseldess$ ./cockroach quit --http-port=8080 --port=26257
Error: unknown flag: --port
Failed running "quit"
```

**Comment by mberhault** [comment]
This is standard behavior for our CLI. Any flag that is not accepted by the command triggers an error.
In the case of `quit`, we accept the global flags, the cert flags, `host`, and `http-port`.

In this sense, it is consistent with the rest of the commands.

**Comment by tamird** [comment]
So the bug isn't that it doesn't work with unnecessary flags, but that the error message is unhelpful?

**Comment by mberhault** [comment]
It may be more helpful to print out the usage message on bad flags. Saying something along the lines of `don't use --port, use --http-port instead` would be too much.

**Comment by mberhault** [comment]
any idea why we have `SilenceUsage: true` in our commands?

**Comment by mberhault** [comment]
@tschottdorf: I'm seeing most (all?) instances of `SilenceUsage` being added in #3581, but no reason as to why.

**Comment by tschottdorf** [comment]
Because that would cause the usage to be printed on any error, which isn't
what we want. We want to print them only when the flags are wrong. Suppose
we need to check that manually then?

On Wed, May 18, 2016 at 2:07 PM marc <notifications@github.com> wrote:

> @tschottdorf <https://github.com/tschottdorf>: I'm seeing most (all?)
> instances of SilenceUsage being added in #3581
> <https://github.com/cockroachdb/cockroach/pull/3581>, but no reason as to
> why.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/6776#issuecomment-220110667>
>
-- 

-- Tobias

**Comment by mberhault** [comment]
I'm not seeing an obvious hook. Cobra will print the usage on unknown flags, but as far as I can tell, our only control is using `SilenceUsage`. I'll check the docs some more. If we can silence it after flag parsing, that might work too.

**Comment by jseldess** [comment]
Good points, @mberhault. Didn't realize this is standard CLI behavior.
