### ISSUE TITLE
kv: multiple locality flags when storage location differs from cockroach node location

### ISSUE THREAD

**Issue by michae2** [cockroachdb/cockroach#67763]
Our documentation of [the `--locality` flag](https://www.cockroachlabs.com/docs/stable/cockroach-start#locality) and [replication constraints](https://www.cockroachlabs.com/docs/stable/configure-replication-zones.html#replication-constraints) is written with the implicit assumption that storage is local to, or colocated with each cockroach node. But some customers deploy with network-attached storage which resides in a different location than the cockroach node using it.

In these deployments, should locality flags match (a) the location of the cockroach node, or (b) the location of attached storage? At first I thought (b) storage, to prevent data loss in the case of complete loss of multiple storage nodes in the same location. But with locality flags matching storage, multiple cockroach nodes in the same location could go down and make some ranges unavailable.

Furthermore, one could imagine a third component with a third location (c): a router or network proxy between the cockroach node and the rest of the cluster. If multiple network proxies in the same location went down, it could also make some ranges unavailable.

So it seems to fully support these deployments, cockroach needs the ability to configure ***MULTIPLE*** locality flags for (a), (b), and (c), and should avoid colocating replicas when *any* of them are the same.

This is not hypothetical. Recently an important customer had a configuration somewhat as follows:

- cockroach node 1, `--locality=rack=A`, attached to storage node on rack **B**
- cockroach node 2, `--locality=rack=B`, attached to storage node on a different rack
- cockroach node 3, `--locality=rack=C`, attached to storage node on rack **B**
- 17 other cockroach nodes, N other storage nodes, all on racks D-Z

Rack **B** went down, and because of the locality flags, there were some ranges with multiple replicas in storage on rack B, rendering the ranges unavailable. Even worse, it appears that there was some storage loss, meaning all these ranges are probably corrupt. If the locality flags had matched storage then CockroachDB would have known not to place them in storage nodes on the same rack (though then it would have been blind to cockroach nodes on the same rack).

 - CockroachDB version 21.1.5

**Comment by lunevalex** [comment]
@michae2 I am not sure I follow the request, in general this is not a topology we support where the locality of storage is different from the locality of node, but if you really wanted to express that you already can as the locality flag is tiered. Support we have 3 nodes on Rack B, that are attached to storage in racks A,B,C then you could say something like this 

- cockroach node 1, --locality=rack=A,storage_rack=A node on A, storage on A 
- cockroach node 2, --locality=rack=A,storage_rack=B node on A, storage on B 
- cockroach node 3, --locality=rack=A,storage_rack=C node on A, storage on C

**Comment by michae2** [comment]
@lunevalex thanks for the comment. Yes, it is kind of an unusual topology. Maybe the fix is to simply document that it is unsupported. 🙂

Just out of my own curiosity, what are the semantics of `--locality=rack=A,storage_rack=B`? I was assuming that the tiers of a single locality flag are strictly hierarchical, so this would mean something like "storage_rack B is within rack A" which isn't quite what I was trying to express. I was trying for something like "this node is located in _both_ rack A and rack B".

For example, if there are two nodes like this:
```
node 1 on rack A, storage on rack B
node 2 on rack B, storage on rack A
```
And we used flags as you suggest:
```
--locality=rack=A,storage_rack=B
--locality=rack=B,storage_rack=A
```
then wouldn't the database be able to place replicas of the same range on both nodes, since "rack" looks like a different tier than "storage_rack", even though they are not different? If either rack went down this would cause both replicas to become unavailable.

**Comment by lunevalex** [comment]
hmm, yes you are right it would not work. The locality tiers are converted into a `divergenceScore` here https://github.com/cockroachdb/cockroach/blob/5eec57605aab5e1f0993e7aecaed1784fbdd2b8c/pkg/roachpb/metadata.go#L666, which is then used in the allocation algorithm that we place the replicas on the most diverse nodes. 

I am however relatively certain that this is not something that we want to support. Updating the docs maybe a good idea in this case cc: @mwang1026

**Comment by mwang1026** [comment]
I agree we wouldn't want to take this on unless a large enough cohort says that they cannot avoid this setup (and I'm not sure in what world that would be the case -- but I've been wrong before :D) 

Specifically, you're choosing a less resilient setup this way. A machine going down is as good as some nodes and some disks going down. Why would you choose to correlate your failures? Maybe I'm missing something here @michae2

**Comment by michae2** [comment]
> I agree we wouldn't want to take this on unless a large enough cohort says that they cannot avoid this setup (and I'm not sure in what world that would be the case -- but I've been wrong before :D)
> 
> Specifically, you're choosing a less resilient setup this way. A machine going down is as good as some nodes and some disks going down. Why would you choose to correlate your failures? Maybe I'm missing something here @michae2

Yes, I think you're right, it is a difficult setup for us to support *and* it is less resilient. I wanted to capture the issue because it affected a real customer, but I think a change to docs would suffice unless many other customers also use attached storage in a different location.

**Comment by mwang1026** [comment]
ok. closing this then. cc @rmloveland for docs consideration
