### ISSUE TITLE
Visual inconsistencies on Statement, Transaction, Sessions pages in CC console

### ISSUE THREAD

**Issue by Annebirzin** [cockroachdb/cockroach#67774]
- [x] **Update Statements, Transactions, Sessions page heading font styles to match header font to Networking, Backups, and SQL Users pages. Should be size 20px, semi-bold 600 (H3)** 

    Statements
    ![markuphero-EVKOkXVj3d8fehE3eIfa-1](https://user-images.githubusercontent.com/51920721/126525932-5a9b62aa-a87f-4e9f-a8f2-04bfbaf9824a.png)
    
    Backups (match this)
    <img width="716" alt="Screen Shot 2021-07-19 at 4 56 43 PM" src="https://user-images.githubusercontent.com/51920721/126226362-d4072c66-d0b4-4894-93c8-fc3deb6d15c4.png">

- [x] **Update Statements, Transactions, Sessions page left/top padding to match spacing for Networking, Backups, and SQL Users pages.**

    ![Kapture 2021-07-19 at 17 03 42](https://user-images.githubusercontent.com/51920721/126227290-fe559e9e-3b62-415c-ac08-2ca3462129de.gif)

- [x] **Update Statements, Transactions, Sessions table header fonts to match table header font styles to 'Networking, Backups, SQL Users. Should be size 14px, semi-bold 600**

    Statements
    ![markuphero-iNd9Bf8kVLvH7XiOE9iN-1](https://user-images.githubusercontent.com/51920721/126526454-7509845c-a7e3-42f2-8e0e-fc824bfa1f51.png)
    
    Networking (match this)
    <img width="1184" alt="Screen Shot 2021-07-19 at 4 47 35 PM" src="https://user-images.githubusercontent.com/51920721/126225982-f60b1368-0f19-4fe3-b7b0-320b43f151ae.png">

    
- [x] **On the Sessions page, update the '...' Menu button icon to correct icon size in DB and CC console 
([**Design reference link**](https://www.figma.com/file/MoSPFkEyJfGipCmQvvLg1a/21.1_SQL-obsrv_query-performance?node-id=559%3A14386))**
    
    ![markuphero-bpHuvmDfiy1KbjfxC76H-1](https://user-images.githubusercontent.com/51920721/126229557-6d080504-ce50-4fa1-9df3-88c6d34acd4b.png)

- [x] **On the Sessions page, update the table data text styles:**

    - Session duration text: hex #0055FF; open sans pro, semi-bold 600
    - Statement SQL text: hex #0055FF (same font)
    - transaction duration, statement duration, memory usage and 'N/A' text:  hex #242A35; open sans pro, regular 400
    
    ![markuphero-78GgxXhkGBI9EPLUDP6l-1 (1)](https://user-images.githubusercontent.com/51920721/126524065-ee7e4969-c90e-44e7-82f3-75b2fa84b466.png)

    [**Design reference link**](https://www.figma.com/file/MoSPFkEyJfGipCmQvvLg1a/21.1_SQL-obsrv_query-performance?node-id=2811%3A120341) (match this)

    ![Screen Shot 2021-07-21 at 11 40 42 AM](https://user-images.githubusercontent.com/51920721/126517998-ec68df36-86b9-4b03-a0a3-28cafbab9182.png)

- [x] **On statements and transactions pages, update search text color to be web compliant:**
    - Update search text from #89B0FF to  #0055FF
    - Update tooltip search text from #89B0FF to #B6CEFF
    
    ![Screen Shot 2021-07-21 at 11 46 20 AM](https://user-images.githubusercontent.com/51920721/126522155-44e62979-95ae-49a7-a8f9-64829bca2294.png)
    
    [**Design reference link**](https://www.figma.com/file/fxuZ93cyKmeAbC8pxGXQyk/21.2_SQL-obsrv_query-contention?node-id=716%3A1351) (match this)
    
    ![Screen Shot 2021-07-21 at 12 07 13 PM](https://user-images.githubusercontent.com/51920721/126522283-1524b25f-70b7-4a3b-9bcf-b119bce71414.png)
    

Epic: CC-5060

**Comment by maryliag** [comment]
Create a [PR](https://github.com/cockroachdb/cockroach/pull/70034) for the changes. The only items missing is the "..." button, because CC console uses a different component that DB Console doesn't have. Need to figure out the best way to handle this in a future PR
