### ISSUE TITLE
changefeedccl: option `webhook_sink_config` for customizing webhook sink HTTP behavior

### ISSUE THREAD

**Issue by spiffyyeng** [cockroachdb/cockroach#67804]
Similar to the `kafka_sink_config` option within Kafka sink, webhook sink should take JSON to configure HTTP request behavior. Some of the things that could be configured:

- Retry behavior
- Batching (not implemented yet)
- Flushing

Remaining questions:
- What should be the schema for this JSON
- What are the defaults if it's not provided?
- How do we define what is configurable through this options vs other options/query params (for Kafka it's explicitly the Sarama config but we don't have such a paradigm in this case)

Epic CRDB-7748

**Comment by amruss** [comment]
Also would add timeout to that list
