### ISSUE TITLE
sql: Add telemetry for different cross-database references

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/cockroach#67807]
We don't have telemetry for these cross-database references:

- foreign key constraints
- sequence ownership
- views

Data here would be helpful since we plan to remove these cross-database references in a future release.

Epic: CRDB-1519

**Comment by ajwerner** [comment]
Three approaches:
1) At read time when we validate cross references we can look up whether any are in different databases
2) During a migration which touches all descriptors
3) During the calls which fetch all of the descriptors (internalLookupCtx construction). 

3 is probably the best and can be combined nicely with 2. @vy-ton would you accept a "gauge" with the latest known number of cross database references? Do you want types of references? i.e. foreign keys, sequences, views etc? If we backport, also interleaves. Do we want to backport this?

**Comment by vy-ton** [comment]
- A guage works as a first pass
- I would want to know type of reference. We can ignore interleaved. I would like to backport (we have little insight into actual cross-db references)

**Comment by ajwerner** [comment]
We don't have gauges. So I guess what we can do is some gymnastics where we increments some sets of counters like

* Scanned all descriptor
* Saw 1 of some type of cross-db reference (incremented same time as above)
* Saw N of some type of cross-db reference (incremented same time as above)

This way you can determine the average of each type as well as the existence (with some gymnastics). 

This all makes me super sad.

**Comment by ajwerner** [comment]
We should validate that we could even write this query with somebody who looks at this data.

**Comment by sajjadrizvi** [comment]
Do we care about columns that take their default values from a cross-db sequence? For example, `seq_col` in the following:
```
CREATE DATABASE referenced_db;
CREATE SEQUENCE referenced_db.referenced_sequence;

CREATE DATABASE d;
CREATE TABLE d.t (seq_col INT DEFAULT nextval('referenced_db.referenced_sequence'));
```

**Comment by ajwerner** [comment]
> Do we care about columns that take their default values from a cross-db sequence? For example, `seq_col` in the following:
> 
> ```
> CREATE DATABASE referenced_db;
> CREATE SEQUENCE referenced_db.referenced_sequence;
> 
> CREATE DATABASE d;
> CREATE TABLE d.t (seq_col INT DEFAULT nextval('referenced_db.referenced_sequence'));
> ```

Yes, we care about that very much.

**Comment by sajjadrizvi** [comment]
OK, unlike other cross-db references, they are not guarded by a cluster setting. For example, we have `sql.cross_db_views.enabled` setting for views and similar settings for FKs and sequence ownerships.

**Comment by ajwerner** [comment]
> OK, unlike other cross-db references, they are not guarded by a cluster setting. For example, we have sql.cross_db_views.enabled setting for views and similar settings for FKs and sequence ownerships.

That's very sad news. Thanks for the find. I've filed https://github.com/cockroachdb/cockroach/issues/69992. At least the query we have in `crdb_internal.cross_db_references` finds them. https://github.com/cockroachdb/cockroach/blob/955f398e856f4b0a571c3d4878966808bb0a85dc/pkg/sql/crdb_internal.go#L4640-L4658

**Comment by ajwerner** [comment]
I'm inclined to say we're just not going to do anything about this. @vy-ton you can bring up something new if this is pressing.

**Comment by vy-ton** [comment]
@ajwerner Would this be in the protobuf representation of all descriptors that we realized is being collected by the registration server?

**Comment by ajwerner** [comment]
> @ajwerner Would this be in the protobuf representation of all descriptors that we realized is being collected by the registration server?

With some elbow grease, such an analysis could indeed be done.
