### ISSUE TITLE
The sessions page on the DB Console should show a time not "a few seconds" 

### ISSUE THREAD

**Issue by pxlogan** [cockroachdb/cockroach#67820]
**Is your feature request related to a problem? Please describe.**
When showing the sessions page the age of the session is shown as a few seconds

**Describe the solution you'd like**
The session start time should be displayed as a date and time showing an accurate time.

**Describe alternatives you've considered**
None

**Additional context**
None

gz#9118

Jira issue: CRDB-8732

**Comment by thtruo** [comment]
cc @kevin-v-ngo I'm re-assigning to you for triage as this falls under SQL Observability

**Comment by kevin-v-ngo** [comment]
Thanks @pxlogan. We have the Session Start Time on the session details page. To confirm, is the request adding this to the session overview page?

**Comment by pxlogan** [comment]
[
![session](https://user-images.githubusercontent.com/67021344/126988118-eeb7c8ff-5711-48e7-b186-8bdfb7bdf484.JPG)
](url)

See attached, the session duration is shown as "a minute" can this be shown as a date & time?

**Comment by kevin-v-ngo** [comment]
This is the date and time the session was started (Session Start Time)?

**Comment by pxlogan** [comment]
Yes correct Kevin

**Comment by kevin-v-ngo** [comment]
Thanks. This was also just escalated through TSE.

**Comment by pxlogan** [comment]
Any update on the progress of this?

**Comment by gtr** [comment]
Hi @pxlogan, this is currently being addressed in [#75965](https://github.com/cockroachdb/cockroach/pull/75965).
