### ISSUE TITLE
Expected foreign key violation not returned on `INSERT ... RETURNING(...);` query

### ISSUE THREAD

**Issue by jonasverschueren** [cockroachdb/cockroach#67868]
**Describe the problem**

We observed behaviour whereby an `INSERT ... RETURNING(...)` query does not return an expected foreign key constraint violation error. It is important to note that the tuple is not actually inserted (phew) even though the foreign key violation is not returned.

**To Reproduce**

Relevant versions:
CockroachDB: `CockroachDB CCL v21.1.6 (x86_64-unknown-linux-gnu, built 2021/07/20 15:30:39, go1.15.11)`
Go: Reproduced with `go version go1.14.14 linux/amd64` and `go version go1.16.6 linux/amd64`
libpq: `github.com/lib/pq v1.10.2`

1. Set up a local cockroach cluster with a `bank` database and SQL user following https://www.cockroachlabs.com/docs/v21.1/build-a-go-app-with-cockroachdb-pq?filters=local#update-the-connection-parameters.
2. Put your username, password, hostname and port in the Go source file below
3. `go run` the following:
```
package main

import (
    "database/sql"
    _ "github.com/lib/pq"
    "log"
)

func main() {
    db, err := sql.Open("postgres", "postgres://{username}:{password}@{hostname}:{port}/bank?sslmode=require")
    if err != nil {
        log.Panic("error connecting to the database: ", err)
    }

    // clean up created tables and close connection
    defer func(){
        if _, err := db.Exec("drop table myaccounts;"); err != nil {
            log.Panic("error dropping myaccounts: ", err)
        }
        if _, err := db.Exec("drop table assocs;"); err != nil {
            log.Panic("error dropping assocs: ", err)
        }
        db.Close()
    }()


    if _, err := db.Exec(
        "CREATE TABLE assocs(id TEXT PRIMARY KEY)"); err != nil {
        log.Panic(err)
    }
    if _, err := db.Exec(
        "CREATE TABLE myaccounts(id TEXT PRIMARY KEY, assoc_id TEXT NOT NULL)"); err != nil {
        log.Panic(err)
    }
    if _, err := db.Exec(
        "ALTER TABLE ONLY myaccounts ADD CONSTRAINT account_updates_account_id_fkey FOREIGN KEY (assoc_id) REFERENCES assocs(id)"); err != nil {
        log.Panic(err)
    }

    // Insert illegal row in myaccounts table
    if rows, err := db.Query(
        "insert into myaccounts (id, assoc_id) values('1', 'non-existent-assoc-id') RETURNING(id, assoc_id)"); err != nil {
            log.Panic("expected error on insert: ", err) // -> This is the error we expect to get back
        } else {
            for rows.Next() {
                var returnedAssocID string
                if err := rows.Scan(&returnedAssocID); err != nil {
                    log.Panic("error on scanning: ", err)
                }
                log.Printf("returned value: %s\n", returnedAssocID)

                // check if anything was insertedvar entries int
                var entries int
                if err := db.QueryRow("SELECT count(*) from myaccounts;").Scan(&entries); err != nil {
                    log.Panic("could not retrieve entry count: ", err)
                }
                log.Printf("entries in myaccounts: %d\n", entries)
            }
        }
}
```

4. Observe printed output
```
2021/07/21 18:44:22 returned value: (1,non-existent-assoc-id)
2021/07/21 18:44:22 entries in myaccounts: 0
```
which suggests that no error was returned due to the `account_updates_account_id_fkey` constraint but also that the constraint was enforced since no entry was added to the table. 

**Expected behavior**
I would expect to get a foreign key constraint violation error back upon inserting the tuple. Note that changes to the returning clause can make it behave this way. For example, changing it to `RETURNING(assoc_id)` or `RETURNING(id)` does result in the expected error `pq: insert on table "myaccounts" violates foreign key constraint "account_updates_account_id_fkey"`

**Environment:**
 - CockroachDB version [21.1.6]
 - Server OS: [Linux/Ubuntu]
 - Client app [Go with lib/pq driver (see above for exact versions)]

**Additional context**
The application can not handle the foreign key constraint violation as expected and carries on as if something was inserted successfully. 

Jira issue: CRDB-8750

**Comment by jordanlewis** [comment]
Hi @jonasverschueren,

I think this error is in fact returned from the database. You need to use [`rows.Err()`](https://pkg.go.dev/database/sql#Row.Err) to check any errors that were returned after the last call to `Scan`. Can you try that and let me know if you still see the issue?

That being said, I'm not quite sure why the error doesn't come back with the returned row in this case, and we'll investigate it.

**Comment by jonasverschueren** [comment]
Thanks for the rapid response @jordanlewis. 

I edited the last bit of the file above to check `rows.Err()` as you suggested:
```
    // Insert illegal row in myaccounts table                                                                                                                                                                                                                                                                                                                                                            
    var rows *sql.Rows
    var queryErr error
    if rows, queryErr = db.Query(
        "insert into myaccounts (id, assoc_id) values('1', 'non-existent-assoc-id') RETURNING(id, assoc_id)"); queryErr != nil {
            log.Panic("expected error on insert: ", err) // -> This is the error we expect to get back                                                                                                                                                                                                                                                                                                   
        } else {
            for rows.Next() {
                var returnedAssocID string
                if err := rows.Scan(&returnedAssocID); err != nil {
                    log.Panic("error on scanning: ", err)
                }
                log.Printf("returned value: %s\n", returnedAssocID)

                // check if anything was insertedvar entries int
                var entries int
                if err := db.QueryRow("SELECT count(*) from myaccounts;").Scan(&entries); err != nil {
                    log.Panic("could not retrieve entry count: ", err)
                }
                log.Printf("entries in myaccounts: %d\n", entries)
            }
        }
    log.Printf("rows.Err: %s", rows.Err())
}

```
which does yield the expected error:
```
2021/07/22 09:14:14 returned value: (1,non-existent-assoc-id)
2021/07/22 09:14:14 entries in myaccounts: 0
2021/07/22 09:14:14 rows.Err: pq: insert on table "myaccounts" violates foreign key constraint "account_updates_account_id_fkey"
```
This is certainly good news. Having said that, this behaviour does seem counter-intuitive (but that could be due to Go's `database/sql`). Secondly, this small test run against a postgres instance does return the constraint violation with the query.

**Comment by mgartner** [comment]
This doesn't appear to be an issue with CRDB. Closing.
