### ISSUE TITLE
sql: batch SQL stats flush

### ISSUE THREAD

**Issue by Azhng** [cockroachdb/cockroach#67867]
The initial implementation for SQL Stats flush logic performs as follow:

1. It tries to run an `INSERT ... ON CONFLICT DO NOTHING` statement for each stats object.
2. If it encounters an conflict, it reads the `statistics` column from the conflicting row and update it with new stats using `SELECT ... FOR UPDATE` statement
3. It runs a `UPDATE` statement to update the rows. 

Note that for the fast path, we are performing 1 network round trip, and for slow path, we are performing 3 network round trip.

We can amortize this by batch multiple stats object into a single requests and improve the throughput. 

Jira issue: CRDB-8749

**Comment by Azhng** [comment]
Note: another option we have considered is `INSERT .... ON CONFLICT DO UPDATE` query. However, this would requires us to use `jsonb_build_object()` builtin to create new JSON object for *every* field on the `statistics` column. 

This creates very big queries in the early [prototype](https://github.com/Azhng/cockroach/blob/__dead_sqlstat-flush-/pkg/sql/sqlstats/sscluster/sqlstatsutil/query_builder.go). (On the order of 15 KiB)

**Comment by maryliag** [comment]
No longer a priority
