### ISSUE TITLE
Create the capability to reuse SSL certificate generation code

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach#67862]
The operator would like to reuse the code that generates SSL certificates.  Currently, we are not able to reuse any of that code. We cannot vendor this repo and the code and we cannot easily refactor the security code base.

Jira issue: CRDB-8747

**Comment by knz** [comment]
@mwang1026 can you coordinate with chris to get a bit more color about impact, etc.

This might see some progress in the context of the refactors I'm doing for #68327, but I wasn't targeting this use case.

**Comment by mwang1026** [comment]
cc @piyush-singh sorry I kinda punted on this one too 😬

**Comment by knz** [comment]
cc @jtsiros for triage and tracking
