### ISSUE TITLE
Deleting a database with a space in its name causes inconsistent state

### ISSUE THREAD

**Issue by twrobel3** [cockroachdb/cockroach#6786]
Log Headers:
```
I160518 14:26:46.925276 util/log/clog.go:998  [config] file created at: 2016/05/18 14:26:46
I160518 14:26:46.925276 util/log/clog.go:998  [config] running on machine: Taylors-MacBook-Pro
I160518 14:26:46.925276 util/log/clog.go:998  [config] binary: CockroachDB unknown (darwin amd64, built , go1.6)
I160518 14:26:46.925276 util/log/clog.go:998  [config] arguments: [cockroach start --ca-cert=certs/ca.cert --cert=certs/node.cert --key=certs/node.key --store=cockroach-data --port=26257 --http-port=8081 --background --background=false]
```
Built from version: `beta-20160512-194-g4638e1b` (commit `4638e1b`)

- What did you do?
Started with a freshly initialized cluster.
Created a new database with a space character in its name (`create database "test db";`)
View database list to ensure that it was created, which it was (`show databases;`)
Drop the newly created database (`drop database "test db";`)
Show database list (`show databases;`)

- What did you expect to see?
The database `test db` to not be in the database list upon running `show databases;`

- What did you see instead?
The database `test db` is still shown in the database list, after being dropped.
Attempting to set the active database to `test db` by running `set database = "test db";` fails, as expected, so the database is gone, but the reference to it remains somewhere.

Full SQL Session Log:
```
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
root@:26257> show databases;
+----------+
| Database |
+----------+
| system   |
+----------+
root@:26257> create database "test db";
CREATE DATABASE
root@:26257> show databases;
+----------+
| Database |
+----------+
| system   |
| test db  |
+----------+
root@:26257> drop database "test db";
DROP DATABASE
root@:26257> show databases;
+----------+
| Database |
+----------+
| system   |
| test db  |
+----------+
root@:26257> set database = "test db";
pq: sql/descriptor.go:151: "test db" is not a database
```

**Comment by andreimatei** [comment]
Thanks for the report!

I don't know what's going on, but I doubt it's because of the space. Did it work without it?

Another problem here is the error you got on the `set database` command; it shouldn't have the file path in it.

**Comment by twrobel3** [comment]
It's almost definitely the space.  Here's the exact same sequence of events, on the same instance, with the only difference being removing the space from the db name:
```
root@:26257> show databases;
+----------+
| Database |
+----------+
| system   |
| test db  |
+----------+
root@:26257> create database "testdb";
CREATE DATABASE
root@:26257> show databases;
+----------+
| Database |
+----------+
| system   |
| test db  |
| testdb   |
+----------+
root@:26257> drop database "testdb";
DROP DATABASE
root@:26257> show databases;
+----------+
| Database |
+----------+
| system   |
| test db  |
+----------+
root@:26257> set database = "testdb";
pq: database "testdb" does not exist
```

Deletes as expected, and gives a pq error, rather than a go one when trying to access.

**Comment by andreimatei** [comment]
Hmmm very interesting, we'll track it down. Thanks!
