### ISSUE TITLE
backup: expose descriptor IDs in SHOW BACKUP

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#67929]
It would be useful to be able to list descriptor IDs contained inside a backup, especially when combined with an escape hatch as described in https://github.com/cockroachdb/cockroach/issues/67483.

**Comment by dt** [comment]
@pbardea you're thinking behind a `WITH` option, right, e.g. `WITH debug_ids` or something? And thinking we should add new columns for the id version of everything that has a name column? or just sprintf it into the name (maybe my lazy vote if this is just for debugging, I donno)

**Comment by pbardea** [comment]
Yep, an option like `debug_ids` sounds like it'd be a good fit here. I think it's probably worthwhile to add it in it's own column since it'd allow for easier querying on the descriptor names since they'd be well formatted (don't need to worry about where the ID will be in the name).

**Comment by rhu713** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/68540
