### ISSUE TITLE
backupccl: add dry_run RESTORE to verify backups

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/cockroach#67935]
**Is your feature request related to a problem? Please describe.**

Clients would like to get assurances/test RESTOREs, short of actually restoring the full data. One idea proposed was a "backup checker" tool to validate file checksums over and over; however, confirming SST content matches checksums is far too weak a check to imply backup is restorable; almost all the cases where a customer was unable to restore a backup were instead poorly understood limitations (can't restore single table with grants/fks/user-defined-types/etc) or restore planning/rekey/etc bugs, not corruption of the content of the files. So a useful "backup checker" should actually plan and "run" the RESTORE. 

**Describe the solution you'd like**

A `dry_run` option on RESTORE, which will do almost all of the restore process: planning the RESTORE, downloading the data and rekeying it, but stops short of writing the bits to disk.

Work in progress by @dt: https://github.com/cockroachdb/cockroach/pull/55727

Epic CRDB-10342

Jira issue: CRDB-8790

**Comment by msbutler** [comment]
old issue; rebranded issue here https://github.com/cockroachdb/cockroach/issues/83470
