### ISSUE TITLE
sql: implement pg_shdepend on pg_catalog 

### ISSUE THREAD

**Issue by mnovelodou** [cockroachdb/cockroach#67948]
**Is your feature request related to a problem? Please describe.**
pg_shdepend is not yet implemented on pg_catalog and pg_shdepend have been reported as could be used.

**Describe the solution you'd like**
implement pg_shdepend

**Describe alternatives you've considered**
NA

**Additional context**
This is very similar as pg_depend, but pg_shdepend is more focused on shared object dependencies accross different databases which are roles.

Epic CRDB-2462

**Comment by rafiss** [comment]
closed by https://github.com/cockroachdb/cockroach/pull/68018
