### ISSUE TITLE
Add pause on error option for changefeeds

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#67965]
Add on_error option to changefeeds to make configurable whether we go into a failure state or pause on error
- default should be "fail" 
- option to "pause"

This way, if you have a long running changefeed where the sink may be unreliable, you do not have to start a new changefeed job if we error out. This can be especially important in CC environments where the TTL on the jobs table is a few hours, so we lose the record of the job quickly and it could be very difficult to recover what settings the original changefeed was created with. 

Follow up considerations: Making paused jobs expire after a certain amount of time, since this might contribute to zombie jobs in a forever paused state

**Comment by amruss** [comment]
Additionally, we should consider how to monitor for paused state - re: https://github.com/cockroachdb/docs/issues/10902 , I'm not sure we have an metrics today for this?

**Comment by shermanCRL** [comment]
We’ll need to articulate what this setting buys the user. The first thing that comes to mind is a distinction between retryable and terminal errors.

If it’s terminal, then this setting is irrelevant, no? Perhaps even misleading.

If the error is retryable, then we either retry or pause (or pause after x retries, perhaps user configurable).

So, I am not sure an `on_error` option does anything desirable on its own. I can imagine _other_ desirable settings, like # of retries before pausing, etc. And, as @amruss mentions, monitoring/alerting.

**Comment by spiffyyeng** [comment]
another distinction we should make here is between failure and cancellation, the latter of which is purposeful and user-initiated, so this option shouldn't apply to it.

**Comment by spiffyyeng** [comment]
Another feature that would help with this: https://github.com/cockroachdb/cockroach/issues/67928
