### ISSUE TITLE
sql schema: more support for per-table and per-index settings (storage parameters)

### ISSUE THREAD

**Issue by michae2** [cockroachdb/cockroach#67964]
Some settings are best scoped to tables or indexes rather than sessions or users/roles. Four current examples of settings that we would like to configure per-table:
1. row-level GC TTL settings
2. [table statistics collection settings](https://github.com/cockroachdb/cockroach/issues/64570#issuecomment-884362488)
3. disallow_full_table_scans
4. [row-size guardrails](https://github.com/cockroachdb/cockroach/issues/67400)

One could imagine these settings being included in `CREATE TABLE` and `CREATE INDEX` statements, modified with `ALTER TABLE` and `ALTER INDEX`, and viewed with `SHOW CREATE TABLE`.

As @mgartner pointed out in his comment linked above, Postgres already has syntax for [storage parameters for tables and indexes](https://www.postgresql.org/docs/current/sql-createtable.html#SQL-CREATETABLE-STORAGE-PARAMETERS) which it uses for per-table autovacuum, among other settings. This could be a logical place to collect CockroachDB-specific table settings as well.

We already parse `CREATE TABLE ... WITH` and `CREATE INDEX ... WITH` syntax, but then discard most storage parameters and do not persist them (edit: except for a few, see @otan's comment below). We do not parse `ALTER TABLE ... SET (...)` nor show storage parameters in `SHOW CREATE TABLE` output.  As @rafiss noted in https://github.com/cockroachdb/cockroach/issues/43299 we don't have real support for any of the Postgres storage parameters, much less CockroachDB-specific storage parameters.

So I think there are three work items here:

- [ ]  persist storage parameters in descriptors
- [ ]  add support for `ALTER TABLE ... SET (x = y)` and `ALTER COLUMN ... SET (x = y)`
- [ ]  show storage parameters in `SHOW CREATE TABLE` output

**Edit: this overlaps with zone configs.** (See discussion below.)

Jira issue: CRDB-8801

**Comment by otan** [comment]
> but then discard the storage parameters and do not persist them in any way. 

i disagree sir! 

https://github.com/cockroachdb/cockroach/blob/605b549846b316521f30f698589e8fb0b571daca/pkg/sql/catalog/catformat/index.go#L159-L239

**Comment by michae2** [comment]
A valid point, thank you for setting me straight, @otan! 😄

To be a little more clear about "persist storage parameters in descriptors", I would like storage parameters to have a common home in descriptors rather than being sent off to `IndexDescriptor.GeoConfig.S2Geometry` or some other custom part of the descriptor, so that we don't have to write bespoke put / get functions each time we add a storage parameter.

Adding a storage parameter should just take a little boilerplate, similar to adding a cluster setting.

**Comment by michae2** [comment]
@jordanlewis points out that there's some overlap with this and zone configs. Hmm.

**Comment by ajwerner** [comment]
>@jordanlewis points out that there's some overlap with this and zone configs, at least when it comes to TTL settings.


Heavy +1. One can think of zone configs as filling this niche: they are apply to portions of a descriptor. There are vague plans to move them to be stored on the descriptor after we rework the way that they are communicated to KV.

**Comment by ajwerner** [comment]
I'm not sure what this issue is asking for. We can put some stuff in descriptors. We want to put things related to KV behavior in zone configs, for now. We will be free to change that once @arulajmani and @irfansharif's project comes in.

**Comment by ajwerner** [comment]
See https://github.com/cockroachdb/cockroach/pull/66348

**Comment by ajwerner** [comment]
See also https://github.com/cockroachdb/cockroach/issues/66396.

**Comment by michae2** [comment]
> I'm not sure what this issue is asking for.

This issue is asking for an easy, generic way to add storage parameters, which resembles the way we add cluster settings.

**Comment by ajwerner** [comment]
> This issue is asking for an easy, generic way to add storage parameters, which resembles the way we add cluster settings.

You can just add them to the index descriptor proto and then make sure the plumbing from `tree` works properly. I don't think we need a framework per se. These just feel like your run-of-the-mill properties for a table or index. For that stuff we use the protobufs inside `descpb/structured.proto` and the interfaces in `catalog`

**Comment by ajwerner** [comment]
@michae2 I guess what I'm really looking for is to better understand why we need a "generic" facility here. "easy" feels like it's in the eye of the beholder. For any of the listed features at the top, we could add them and there'd be a straightforward enough way to do it. For 2-4, I'd just add fields to the table descriptor proto and do the plumbing through `tree`, `catalog`, and `opt/cat` to make the feature happen. That feels pretty easy to me. Is that answer unsatisfying?

**Comment by michae2** [comment]
> @michae2 I guess what I'm really looking for is to better understand why we need a "generic" facility here. "easy" feels like it's in the eye of the beholder. For any of the listed features at the top, we could add them and there'd be a straightforward enough way to do it. For 2-4, I'd just add fields to the table descriptor proto and do the plumbing through `tree`, `catalog`, and `opt/cat` to make the feature happen. That feels pretty easy to me. Is that answer unsatisfying?

When you put it that way, it does sound pretty easy, even to this lazy beholder. 😁 But those steps don't include
- support for `ALTER TABLE ... SET (x = y)` and `ALTER COLUMN ... SET (x = y)` syntax

**Comment by michae2** [comment]
This was done a while ago (we can now ALTER TABLE ... SET)
