### ISSUE TITLE
sql: consider table names under the 'system' database to be safe information

### ISSUE THREAD

**Issue by THardy98** [cockroachdb/cockroach#67980]
**Is your feature request related to a problem? Please describe.**
Currently, table names under the `system` database are considered "unsafe" information and are thereby are susceptible to being redacted from statement logs.

**Describe the solution you'd like**
Table names under the `system` database should be considered "safe" information, thereby preventing them from being susceptible to redaction.

**Describe alternatives you've considered**
None

**Additional context**
See #65401 for previous log redaction work/context.

Jira issue: CRDB-8813

**Comment by knz** [comment]
cc @maryliag for triage
