### ISSUE TITLE
sql: implement CARDINALITY builtin for arrays

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#67996]
`cardinality` returns the number of elements in the array. In Postgres, it's recursive, and counts each element in every dimension. Since CockroachDB only supports 1-dimensional arrays right now, the function is similar to `array_len`

See https://www.postgresql.org/docs/13/functions-array.html

Instructions:
* Add a built-in in https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/builtins.go
* Add a test in https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/builtin_function, and run make testbaselogic FILES='builtin_function' TESTFLAGS='-rewrite' to test it.
* Run `make buildshort` to regenerate automatically generated files.
* Submit a PR.

Epic CRDB-7217

**Comment by techytoes** [comment]
Hi @rafiss! Can I work on this?

**Comment by rafiss** [comment]
@techytoes sure! good luck on it :)

**Comment by techytoes** [comment]
Hey @rafiss, after looking more in-depth, I found a related issue #68196. Can you verify once if this is a valid issue?

Thanks!

**Comment by jlevesy** [comment]
Hello @techytoes, are you still working on this issue?

I have a [commit](https://github.com/cockroachdb/cockroach/commit/64181c4d0149d7b3c31e551b45aefb120a4ec984) ready that should do the trick for this feature, but I don't want to steal this issue from you 😅.

Let me know if I can open a PR with it, or if you want to deal with it. Thanks!

**Comment by techytoes** [comment]
Hey @jlevesy, I was on this PR as well but since you have already done all the work so please go ahead and raise a PR. I can pick up some other issues to work on.

Thanks for the heads up!
