### ISSUE TITLE
CI: Make a bot notify the PR author of a CI run failure before the job completes

### ISSUE THREAD

**Issue by jlinder** [cockroachdb/cockroach#68015]
Cockroach CI takes a long time to run and TeamCity doesn't report failures back to GitHub / your PR until the entire CI pipeline is complete. To regain that lost time, write a bot that notifies the PR author that the CI job will fail once it is known it will fail.

Suggestions on how this might work:

1. Make the notification via a comment on the PR (vs. directly emailing the author or messaging in slack).
2. It looks like the bot will need to poll TeamCity periodically to check for new failures. There does not seem to be a way for TeamCity to alert that a build will fail earlier than it being completed via a webhook call somewhere.
3. This could be added to blathers. Since blathers is a cloud function, it can be set up to be triggered periodically by a cloud scheduler job.
4. Permission to the TeamCity API can be made read-only just for the projects it needs to access
5. It should report only once that a given job will fail
6. If a PR has multiple jobs running at the same time, it should only notify of failure if the most recent job for the current head commit for the PR is failing. (Multiple jobs could be running because of multiple pushes to the PR or because of the user manually starting a new build while one still hasn't finished.)

**Comment by jordanlewis** [comment]
Hm, are you sure about this? It used to be the case that GitHub CI would report failure as soon as any of its subjobs reported a failure.

**Comment by jlinder** [comment]
Do you remember it as GitHub CI shows it as red/failed when looking at the GitHub CI run in TeamCity UI, GitHub CI reports the failure back to the PR in GitHub as failed or something else?

In the TeamCity UI, a GitHub CI run shows as red as soon as one of it's sub-jobs fails. But the status reporter back to the GitHub PR doesn't happen until the run finishes.

**Comment by jordanlewis** [comment]
Hmm....

Well, I patched the `commit-status-publisher` to make it behave properly, back in 2018, and got it upstreamed.

https://github.com/JetBrains/commit-status-publisher/pull/43

Think this has rotted?

**Comment by jlinder** [comment]
Oh wow. It seems like it may have. We'll look into this.

Thank you for pointing us in this direction!

**Comment by jlinder** [comment]
Closing this issue in preference of https://cockroachlabs.atlassian.net/browse/DEVINF-145 .
