### ISSUE TITLE
cdc: scope partitioned distributor streams

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#68010]
As part of the cluster to cluster streaming replication work, we need to do work to partition producer streams. This issue is to do an initial investigation into that work, and possibly output an RFC. 

Epic CRDB-6407

**Comment by miretskiy** [comment]
I believe this issue has been resolved via https://docs.google.com/document/d/1i7x6ce0SGMbJ3KEszeRVjRS0LaPhxulcUbi029nVy7c/edit#
