### ISSUE TITLE
sql: hash sharded column shows up in CREATE TABLE, interferes with proper sharded index creation

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#68031]
This issue tracks two observed problems:
 - SHOW CREATE shows the internal shard column when we have a sharded index
 - If we try to create a table with this statement, the column is tolerated and creation succeeds. However, the table is lacking the check constraint (which is necessary for good plans for certain queries).
  
```sql
create table t (a int, index (a) using hash with bucket_count = 10);
select @2 from [ show create table t ];
                                                               ?column?
---------------------------------------------------------------------------------------------------------------------------------------
  CREATE TABLE public.t (
      a INT8 NULL,
      crdb_internal_a_shard_10 INT4 NOT VISIBLE NOT NULL AS (mod(fnv32(COALESCE(CAST(a AS STRING), '':::STRING)), 10:::INT8)) STORED,
      rowid INT8 NOT VISIBLE NOT NULL DEFAULT unique_rowid(),
      CONSTRAINT "primary" PRIMARY KEY (rowid ASC),
      INDEX t_a_idx (a ASC) USING HASH WITH BUCKET_COUNT = 10,
      FAMILY "primary" (a, crdb_internal_a_shard_10, rowid)
  )
(1 row)
```
CREATE TABLE is showing the `crdb_internal_a_shard_10` column.

This table has the expected check constraint:
```
explain (opt, catalog) select * from t;
                                                                      info
-------------------------------------------------------------------------------------------------------------------------------------------------
  TABLE t
   ├── a int
   ├── crdb_internal_a_shard_10 int4 not null as (mod(fnv32(COALESCE(CAST(a AS STRING), '':::STRING)), 10:::INT8)) stored [hidden]
   ├── rowid int not null default (unique_rowid()) [hidden]
   ├── crdb_internal_mvcc_timestamp decimal [hidden] [system]
   ├── tableoid oid [hidden] [system]
   ├── CHECK (crdb_internal_a_shard_10 IN (0:::INT8, 1:::INT8, 2:::INT8, 3:::INT8, 4:::INT8, 5:::INT8, 6:::INT8, 7:::INT8, 8:::INT8, 9:::INT8))
   ├── PRIMARY INDEX primary
   │    └── rowid int not null default (unique_rowid()) [hidden]
   └── INDEX t_a_idx
        ├── crdb_internal_a_shard_10 int4 not null as (mod(fnv32(COALESCE(CAST(a AS STRING), '':::STRING)), 10:::INT8)) stored [hidden]
        ├── a int
        └── rowid int not null default (unique_rowid()) [hidden]
  scan t
   ├── check constraint expressions
   │    └── crdb_internal_a_shard_10 IN (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)
   └── computed column expressions
        └── crdb_internal_a_shard_10
             └── mod(fnv32(COALESCE(a::STRING, '')), 10)::INT4
```

Now if I drop the table and try to recreate it using the CREATE TABLE above:

```
drop table t;
CREATE TABLE public.t (
      a INT8 NULL,
      crdb_internal_a_shard_10 INT4 NOT VISIBLE NOT NULL AS (mod(fnv32(COALESCE(CAST(a AS STRING), '':::STRING)), 10:::INT8)) STORED,
      rowid INT8 NOT VISIBLE NOT NULL DEFAULT unique_rowid(),
      CONSTRAINT "primary" PRIMARY KEY (rowid ASC),
      INDEX t_a_idx (a ASC) USING HASH WITH BUCKET_COUNT = 10,
      FAMILY "primary" (a, crdb_internal_a_shard_10, rowid)
  );
explain (opt, catalog) select * from t;
                                                                  info
-----------------------------------------------------------------------------------------------------------------------------------------
  TABLE t
   ├── a int
   ├── crdb_internal_a_shard_10 int4 not null as (mod(fnv32(COALESCE(CAST(a AS STRING), '':::STRING)), 10:::INT8)) stored [hidden]
   ├── rowid int not null default (unique_rowid()) [hidden]
   ├── crdb_internal_mvcc_timestamp decimal [hidden] [system]
   ├── tableoid oid [hidden] [system]
   ├── PRIMARY INDEX primary
   │    └── rowid int not null default (unique_rowid()) [hidden]
   └── INDEX t_a_idx
        ├── crdb_internal_a_shard_10 int4 not null as (mod(fnv32(COALESCE(CAST(a AS STRING), '':::STRING)), 10:::INT8)) stored [hidden]
        ├── a int
        └── rowid int not null default (unique_rowid()) [hidden]
  scan t
   └── computed column expressions
        └── crdb_internal_a_shard_10
             └── mod(fnv32(COALESCE(a::STRING, '')), 10)::INT4
(16 rows)
```

Epic: CRDB-7363

gz#9232

**Comment by RaduBerinde** [comment]
CC @ajwerner and @mgartner (in case there is anything similar going on with expression-based indexes).

**Comment by ajwerner** [comment]
This seems legit. We have logic to check if the column exists but we don't check if it has the expected constraint in that check. This got more complex when we decided to show the shard column as `NOT VISIBLE` as opposed to not showing it at all, as we used to do before 21.1. This is a regression and it's a rather frustrating one. You might think you want to use the new inaccessible column but, experience has shown us that it's valuable to be able to scan a single shard at a time, which means you'd need to be able to address the shard column in a select statement. 

I don't have an immediate bright idea for how to make this all cohere nicely. We might want to just add the constraint. However, what if we detect that the expression on this column is not what we want it to be. I guess another option is to do something else to select the shard via maybe a function or some special read-only "system" column. Let's make a plan.

**Comment by RaduBerinde** [comment]
One idea is to make the optimizer deduce the constraint automatically, based on `mod`.

**Comment by ajwerner** [comment]
> One idea is to make the optimizer deduce the constraint automatically, based on mod.

That would be very cool. One thing to note is that `mod` in postgres and cockroach is sort of poorly named, it's really remainder (i.e. it can produce negative values). Perhaps we need to also put an `abs` around it.

**Comment by RaduBerinde** [comment]
We could possibly detect `mod(fnv32(..))`

**Comment by RaduBerinde** [comment]
Internally, we'd manufacture a `x IN (0,1,2,..)` constraint. For practical reasons, we'd want to only do this if the mod is relatively small; any idea what a reasonable cutoff would be?

**Comment by ajwerner** [comment]
> any idea what a reasonable cutoff would be?

Honestly, no.

**Comment by ajwerner** [comment]
Whatever we decide though, we should probably disallow creating hash sharded indexes with more buckets than that.

**Comment by RaduBerinde** [comment]
Aren't there usecases where you never rely on the check constraint (i.e. you never search for something without knowing the shard) and thus you could use a very large bucket size?

**Comment by ajwerner** [comment]
> Aren't there usecases where you never rely on the check constraint (i.e. you never search for something without knowing the shard) and thus you could use a very large bucket count?

Sure, indeed there are. Maybe we should make a cluster setting or something for how much expansion to do.

**Comment by RaduBerinde** [comment]
Feels like the right thing would be for the constraint to be a simple `shard between 0 and X` and have the optimizer automatically decide when to break up such a condition into multiple spans (perhaps based on how big the table is compared to X).

**Comment by RaduBerinde** [comment]
I believe a customer has run into this problem (we still have to confirm).

In any case, we need a fix for the missing constraint issue, something that can be backported to 21.1. Perhaps simply ignoring any `crdb_internal_` columns is enough.

@ajwerner I'm assigning to you for triage and visibility.

**Comment by RaduBerinde** [comment]
Another option is to show the check constraint in SHOW CREATE TABLE.

**Comment by vy-ton** [comment]
> You might think you want to use the new inaccessible column but, experience has shown us that it's valuable to be able to scan a single shard at a time, which means you'd need to be able to address the shard column in a select statement

What's an example of this select statement?

**Comment by ajwerner** [comment]
I'm inclined to do some form of `Perhaps simply ignoring any crdb_internal_ columns during table creation is enough.`

**Comment by cucaroach** [comment]
Just confirming that @RaduBerinde's suspicion was right and a customer did indeed hit this.

**Comment by mgartner** [comment]
I think showing the `CHECK` constraint in `SHOW CREATE TABLE` is the simplest solution. As a user, I'd expect to see it there anyway. Is there something I'm not considering that makes ignoring `crdb_internal_` columns a better option?

**Comment by mgartner** [comment]
I put up a PR to show the CHECK constraint, because it was pretty simple. Please let me know if there's a better option here though!

**Comment by ajwerner** [comment]
> Is there something I'm not considering that makes ignoring crdb_internal_ columns a better option?

The main thing is that it remains possible for `USING HASH` to exist without such a constraint. I guess we generally lack those guardrails. Ideally you would not be able to drop that constraint.

**Comment by mgartner** [comment]
I agree that we don't usually enforce these types of guardrails. I think of hash-sharded indexes as syntactic sugar, similar to something like `REGIONAL BY ROW`. If you take this perspective, decomposition of its components seems natural, albeit potentially dangerous.

Here's a similar case where we lack a guardrail. We allow users to muck with the `crdb_region` column in a `REGIONAL BY ROW` table.

```sql
CREATE DATABASE multi_region_test_db PRIMARY REGION "ca-central-1" REGIONS "ap-southeast-2", "us-east-1" SURVIVE REGION FAILURE;
USE multi_region_test_db;

CREATE TABLE regional_by_row (
  pk INT PRIMARY KEY,
  a INT,
  b INT,
  UNIQUE INDEX (b),
  FAMILY (pk, a, b)
) LOCALITY REGIONAL BY ROW;


SHOW CREATE TABLE regional_by_row;
----
regional_by_row             CREATE TABLE public.regional_by_row (
                            pk INT8 NOT NULL,
                            a INT8 NULL,
                            b INT8 NULL,
                            crdb_region public.crdb_internal_region NOT VISIBLE NOT NULL DEFAULT default_to_database_primary_region(gateway_region())::public.crdb_internal_region,
                            CONSTRAINT "primary" PRIMARY KEY (pk ASC),
                            UNIQUE INDEX regional_by_row_b_key (b ASC),
                            FAMILY fam_0_pk_a_b_crdb_region (pk, a, b, crdb_region)
) LOCALITY REGIONAL BY ROW

-- Drop the DEFAULT modifier on the crdb_region column.
ALTER TABLE regional_by_row ALTER COLUMN crdb_region DROP DEFAULT;

SHOW CREATE TABLE regional_by_row;
----
regional_by_row             CREATE TABLE public.regional_by_row (
                            pk INT8 NOT NULL,
                            a INT8 NULL,
                            b INT8 NULL,
                            crdb_region public.crdb_internal_region NOT VISIBLE NOT NULL,
                            CONSTRAINT "primary" PRIMARY KEY (pk ASC),
                            UNIQUE INDEX regional_by_row_b_key (b ASC),
                            FAMILY fam_0_pk_a_b_crdb_region (pk, a, b, crdb_region)
) LOCALITY REGIONAL BY ROW
```

**Comment by ajwerner** [comment]
> If you take this perspective, decomposition of its components seems natural, albeit potentially dangerous.

This perspective is sound. However, it feels like one of those perspectives we find ourselves falling into because it's easier to make coherent rather than one that we necessarily chose and like. It's going to be hard to tighten up these definitions later. Alas, something here is better than nothing. Thank you very much for taking the initiative and doing something.

**Comment by ajwerner** [comment]
@mgartner should we call this closed now?

**Comment by RaduBerinde** [comment]
It still feels sketchy that you can create a table with an index `USING HASH` but which doesn't have the CHECK constraint. Definitely much less severe now with @mgartner's fix.

**Comment by ajwerner** [comment]
Very fair.

**Comment by chengxiong-ruan** [comment]
Right now the logic creating hash index is that "if there's an existing shard column or user defined column which is equivalent, we don't ever try to create constraint even there's no such constraint".
So one idea to fix this issue could be just to figure out a logic to find equivalent constraint in the list of user defined constraint from the create table statement. If we found one, then noop, otherwise create one. Though I haven't dig into how comparison of constraint expressions can be done. But my feeling tells me it's doable...

**Comment by ajwerner** [comment]
>So one idea to fix this issue could be just to figure out a logic to find equivalent constraint in the list of user defined constraint from the create table statement. If we found one, then noop, otherwise create one. Though I haven't dig into how comparison of constraint expressions can be done. But my feeling tells me it's doable...

This sounds good to me.
