### ISSUE TITLE
Enable SQL observability on the Activity Panel - Serverless Overview

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#68054]
This issue tracks enabling metrics such as the #databases, #tables, #open sessions, #transaction retries on the serverless overview page in the CC console. The appropriate APIs need to be integrated with the front-end experience. 

Epic: CC-4605

**Comment by maryliag** [comment]
@matthewtodd can this be closed?

**Comment by matthewtodd** [comment]
Yes!
