### ISSUE TITLE
cli: cluster whole down after providing wrong zone configuration

### ISSUE THREAD

**Issue by pawel-kaminski-krk** [cockroachdb/cockroach#6805]
I160518 12:17:55.038179 util/log/clog.go:998 [config] file created at: 2016/05/18 12:17:55
I160518 12:17:55.038179 util/log/clog.go:998 [config] running on machine: ip-10-2-1-85
I160518 12:17:55.038179 util/log/clog.go:998 [config] binary: CockroachDB beta-20160512 (linux amd64, built 2016/05/12 15:50:23, go1.6)
I160518 12:17:55.038179 util/log/clog.go:998 [config] arguments: [cockroach start --insecure --background --cache=2GiB --attrs=us-east-1c --background=false]

hi,
Ive started my cluster like this

```
cockroach start --insecure --background --cache=2GiB --attrs=us-east-1c
cockroach start --insecure --background --cache=2GiB --attrs=us-east-1d --join=10.2.1.85
cockroach start --insecure --background --cache=2GiB --attrs=us-east-1a --join=10.2.1.85
```

I've then created schema using local sql client and started application that began pushing some data. this app was running for couple of hours. 

meanwhile I read more about zone's configuration and I added 

```
cockroach zone set .default --insecure 'replicas:
- attrs: [us-east-1a]
- attrs: [us-east-1c]
- attrs: [us-west-1d]'
```

last value was wrong but I didn't noticed that and Ive committed configuration. application was still running, I was monitoring cluster and app and everything was fine. then I noticed that one node is 100% cPU. I've killed app. tried some local sql-s connecting directly from nodes. 

today I tried rerunning app with different config/code but it didn't start. admin panel showed that nodes are unavailable, so I restarted one after another, it didnt help and I left them alone. after couple of hours I ve noticed that all 3 nodes have 100% CPU, so I tried to figure out what has actually changed. and I realized that "us-west-1d" is wrong. 

but I couldn't run zone set/get cmd. I couldn't run any query via sql client. the whole cluster keep becoming unstable event though I was restarting db's process again and again.

eventually I've killed any remaining db process on each node. then I removed cockroach-data and recreated cluster, db and its schema. after that I put correct attributes for replication and now I dont see any problems.

well I've already got some answers that cockroach should be ok with invalid configuration but well it didn't. I didn't change any other part of configuration.

Is there a way to recover without deleting whole -data directory? maybe only part of it? :)

**Comment by petermattis** [comment]
@cuongdo Can you take a look at this?

**Comment by spencerkimball** [comment]
This issue is no longer reproducible.
