### ISSUE TITLE
debug: add all-plan generator for statement-bundle

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#68067]
Add a way to generate all possible plans for a statement bundle, by replacing each placeholder in the bundle's statement with all of the different histogram values for the placeholder's column, and doing this for all combinations with all of the placeholders.

#68023 is already open to support this feature, but I'm opening this issue for tracking purposes.

cc @nickelnickel @jordanlewis

**Comment by jordanlewis** [comment]
Closed by #68023.
