### ISSUE TITLE
sql/resolver: error handling regression on master for database that does not exist

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#68060]
I noticed an unexpected change when I use the CLI. If I connect with a URL that includes a DB that doesn’t exist, the error message has changed.

It used to say `error retrieving the database name: pq: database "db" does not exist`.

Now it says `error retrieving the database name: pq: relation "crdb_internal.session_variables" does not exist`.

The new (undesired) error is coming from here: https://github.com/cockroachdb/cockroach/blob/64c888ffa869dc254f6f14dbbcb308efc1d89a64/pkg/sql/catalog/resolver/resolver.go#L202

At this point [`lookupFlags.Required` is set to false](https://github.com/cockroachdb/cockroach/blob/64c888ffa869dc254f6f14dbbcb308efc1d89a64/pkg/sql/resolver.go#L171), so the error handling that would happen in `getObjectByName` to give the "good" error is not used: https://github.com/cockroachdb/cockroach/blob/64c888ffa869dc254f6f14dbbcb308efc1d89a64/pkg/sql/catalog/descs/object.go#L46-L50

The message comes from the first time the CLI runs a `SHOW DATABASE` command, which delegates to `crdb_internal.session_variables`. Technically the new message is “correct” since that name is the thing that cannot be resolved, but it’s slightly less helpful. I think the change came in a40102ab.

I see that in 21.1 the `database does not exist` error was coming from [getPlanInfo](https://github.com/cockroachdb/cockroach/blob/ac051fa1830f485b89c78989182704e0e594de17/pkg/sql/virtual_schema.go#L496-L501) so I guess that means name resolution is happening sooner now than it was before.

Epic: CRDB-2454

**Comment by ajwerner** [comment]
I'll do something here specifically focused on the virtual tables in the case that the database does not exist to focus the error on the database rather than on the table.

**Comment by rafiss** [comment]
@fqazi @ajwerner I noticed that the behavior changed for unqualified vtable names too:

v21.1
```
❯ psql -h localhost -p 26257 -U root -w -d non_existent

non_existent=# select * from pg_type;
ERROR:  database "non_existent" does not exist
```

v21.2
```
❯ psql -h localhost -p 26257 -U root -w -d non_existent

non_existent=> select * from pg_type;
ERROR:  relation "pg_type" does not exist
```

this came up in the context of adding EFCore (C#) support, since it had conditional logic based on this error message

**Comment by ajwerner** [comment]
One thing that's interesting is that postgres closes the connection when the database does not exist. It's also a little funky that we have the virtual relations behaving different from regular relations. Should all one-part names which fail due to the database not existing fail with the database not existing error?

**Comment by ajwerner** [comment]
My guess is that it is looking at that error message and it bubbles up from postgres when trying to connect and it bubbled up from cockroach after they issued the first query.
