### ISSUE TITLE
logging: make the exit code used by `log.Fatal` customizable per-event

### ISSUE THREAD

**Issue by joshimhoff** [cockroachdb/cockroach#68075]
**Is your feature request related to a problem? Please describe.**
CC is pushing the max clock offset down from 500ms to 250ms to support new multi-region features like `GLOBAL` tables. We want to be able to monitor the effects of this change. One possible effect is more crashes due to hitting the max clock offset.

Ideally we can get this into 21.2. We won't be measuring per-exit code crash rate until around then, as we need to do some monitoring work to make that possible.

**Describe the solution you'd like**
I have two ideas:

1. Return a consistent exit code when a cluster crashes due to hitting the max clock offset. According to https://github.com/cockroachdb/cockroach/pull/56574, this is not done yet.
2. Log a unit tested structured log line.

I want to talk to SREs about which we like better. Right now, I lean towards 1.

Not sure if this is more a KV or server thing so I've tagged the issue with both.

**Describe alternatives you've considered**
See above. I give two possibilities.

**Additional context**
N/A

Jira issue: CRDB-8862

**Comment by knz** [comment]
I think this is more KV.
@nvanbenschoten where in the code would we best be able to log this?

**Comment by nvanbenschoten** [comment]
I believe, but we'd want to confirm, that process crashes due to clock offset violations occur here:
https://github.com/cockroachdb/cockroach/blob/740ae3d62feca478bf5b5fb4b65338d5a8757ee3/pkg/server/server.go#L334-L336

The is some unit testing around this in `TestVerifyClockOffset` and `TestRemoteOffsetUnhealthy`, but the log line is not structured in a way that would be natural to monitor, beyond matching on `clock synchronization error:`.

**Comment by knz** [comment]
`log.Fatal` was not designed to produce specific error codes, but we could teach it to do so.

**Comment by nvanbenschoten** [comment]
This seems like a generally useful capability. @knz would need to speak to whether we could land such a change in 21.2. @joshimhoff are there other places where you would like a specific status code during failure?

**Comment by knz** [comment]
@rauchenstein would you have an idea about how to achieve this?

**Comment by joshimhoff** [comment]
> @joshimhoff are there other places where you would like a specific status code during failure?

No but thanks for asking! Storage is returning a consistent exit code when running out of disk; that plus one when clock skew failures happen is all SRE wants at the moment.
