### ISSUE TITLE
sql/parser: Change EvalContext to be passed as a pointer

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#6809]
Currently, we pass around an `EvalContext` value throughout the `sql` and `sql/parser` package. For instance, `TypedExpr`s [take an `EvalContext` value](https://github.com/cockroachdb/cockroach/blob/master/sql/parser/expr.go#L55) during evaluation. It would be nice if this was passed around as a pointer, as it would allow for easier modification and reduce the chunk of memory being passed around. It is probably already escaping to the heap, so this shouldn't increase memory allocations.

**Comment by seiflotfy** [comment]
On it already

**Comment by nvanbenschoten** [comment]
Don't worry about it @seiflotfy, I took care of this change this morning. Sorry for stealing it from you :)

**Comment by seiflotfy** [comment]
hah no worries! good one @nvanbenschoten will look at the PR

**Comment by nvanbenschoten** [comment]
Sounds good, thanks! It's rebased off of https://github.com/cockroachdb/cockroach/pull/6897, so I'll send it out once that merges.

**Comment by seiflotfy** [comment]
Dude that is incredible! Great Great Job
