### ISSUE TITLE
sql: Add telemetry counters for schema change error type

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/cockroach#68111]
Motivating telemetry question:

- Did a schema change fail because of user error (constraint violation) or internal database error?

**Comment by vy-ton** [comment]
Can this be backported to 21.1?

**Comment by vy-ton** [comment]
@fqazi Can we backport this 21.1 in order to capture the telemetry?

**Comment by fqazi** [comment]
Yes let me open a backport pull request

**Comment by ajwerner** [comment]
backport merged.
