### ISSUE TITLE
sql: upgrade for tenants do not bump up version numbers for the tenant at each migration step

### ISSUE THREAD

**Issue by fqazi** [cockroachdb/cockroach#68116]
Inside the migration code for upgrading between releases a system cluster will always bump version numbers
as needed as we go through each step of migration. On the tenant side, these operations are implemented as
no-ops, so there is a potential risk for horrible things to happen if a crash occurs (the same migration logic may
be run twice). Additionally, for certain types of version gating, we need to have the version bumped immediately for example #68074 since a version gate is used to stop certain operations. The current logic for the system tenant updates in memory and on storage values by RPCing out to all pods, which isn't feasible for tenants.

This issue will attempt to address this by always updating the system settings table at each step, and implement the remaining logic by waiting for the change to be visible on pods for the system case.

**Comment by ajwerner** [comment]
We want the invariant that if a migration succeeds and a version becomes active, that subsequently started pods will all agree that that version became active. This is not the case today, even with the restriction of at most one pod.

We're proposing here that we remedy this by actually writing the cluster version into system.settings at each step. This was something that we talked about a while ago but did not do for “reasons”. The advantage here is that if we do that and we ensure that all sql pods have seen that update, then we get back the one-way gate we want. It will be a bit tricky to rework the cluster setting logic to make this happen but it seems okay.

In the first pass, my sense is we should only do this incremental writing of the new settings in the secondary tenants if only for backportability. In the long run, I think it makes sense to do it also in the system tenant. We’re already bumping their “active version” via the out-of-band RPC. Why should we not keep the cluster setting in sync?

**Comment by fqazi** [comment]
> @ajwerner do you have an opinion about which team this would go to?

I have a PR with this bit that I need to split off to solve it for tenants on a single pod
