### ISSUE TITLE
cdc, jobs: PAUSE ALL CHANGEFEEDS command

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/cockroach#68126]
**Is your feature request related to a problem? Please describe.**

Users may wish to quickly stop all changefeeds, perhaps as a way to to reduce load in certain situations.

**Describe the solution you'd like**

A `PAUSE ALL CHANGEFEEDS` command or similar.

**Describe alternatives you've considered**

Currently, this is done via [PAUSE JOB(S)](https://www.cockroachlabs.com/docs/stable/pause-job.html). This requires multiple steps, such as looking up the job ids.

A query like this is better: `PAUSE JOBS (SELECT job_id FROM [SHOW JOBS] WHERE job_type='CHANGEFEED' AND status IN ('running'))` (h/t @adityamaru)

`PAUSE ALL CHANGEFEEDS` _could_ be implemented as an alias/rewrite of the above, but that would be up to the implementer.

Epic CRDB-9106

**Comment by shermanCRL** [comment]
For completeness, we might also consider `RESUME` and `CANCEL` as well.

We implemented `SHOW CHANGEFEED JOBS`: https://github.com/cockroachdb/cockroach/issues/64933. I wonder if we should consider changing the syntax to `SHOW CHANGEFEEDS`.

Or, alternatively, use _that_ syntax, i.e. `PAUSE CHANGEFEED JOBS`.

**Comment by shermanCRL** [comment]
Also for completeness, we’d want to support syntax that is added to jobs in general, for example: https://github.com/cockroachdb/cockroach/issues/67928

So, we’d want to support `PAUSE ALL CHANGEFEEDS WITH REASON = 'x’`. Maybe there is cleverness to get this for ‘free’, if `ALL CHANGEFEEDS` is simply a syntax tree replacement for `JOBS (SELECT job_id FROM [SHOW JOBS] WHERE job_type='CHANGEFEED' AND status IN ('running'))`.

**Comment by amruss** [comment]
In one instance  node upgrades were taking good deal of time for a user because draining process would get stuck until each changefeed jobs were paused (around 80 changefeeds)- being able to pause all would have been useful

**Comment by amruss** [comment]
https://github.com/cockroachdb/docs/issues/10995

**Comment by HonoreDB** [comment]
If we do this generically for any job type, we should make the syntax "PAUSE EACH <type>" or "PAUSE EVERY <type>" so we don't have to map plural forms to singular ones.

**Comment by shermanCRL** [comment]
A few notes from a discussion:

- This is intended syntactic sugar
- @miretskiy: we should do a complete job of this: not just changefeeds, but all job types
- My mental model is that `job` is a base class, with shared capabilities, while `changefeed` is a subclass, with it’s own ‘fields’ and ‘methods’. I think operators think about changefeeds more than jobs, per se.
- The `ALL` keyword is not strictly necessary, but we agreed it’s desirable -- to disambiguate parsing, and as a UX choice to ensure the operator recognizes the implications of the command (similar in spirit to `experimental`)
