### ISSUE TITLE
Update all date formats in the DB console to a global date format (YYY-MM-DD)

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#68125]
This item tracks updating all date formats in the DB console to a global date format (YYY-MM-DD T[hh]:[mm]:[ss] ). Today, dates are represented in the following format: MMM DD, YYYY at HH:MM (Jul 27, 2021 at 4:39 PM).

Jira issue: CRDB-8878

**Comment by Annebirzin** [comment]
@kevin-v-ngo I'm wondering if we want to get more feedback from users on this one. I agree the global format would be more inclusive, but I'm curious if users are familiar with that format.  My biggest concern would be the mix-up between the MM and DD. 

Another option would be to allow users to choose a format (which would require a settings option somewhere in DB and CC Console) or apply the relevant date format based on the user's location. But I realize that these options are both a lot more work.

**Comment by kevin-v-ngo** [comment]
Sounds good Anne. Let me remove this from the quick win column for now!

**Comment by maryliag** [comment]
Now that we updated to use 24h UTC, any other updates we want to do here?
There is another issue created for this here https://github.com/cockroachdb/cockroach/issues/81159
