### ISSUE TITLE
tpcc: checks are missing error checks

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#68164]
**Describe the problem**

See #68163.

Look at the methods in `workload/tpcc/checks.go` on master. Most queries are missing the
`rows.Err()` check, so should any check fail with a memory quota error, it's likely to
look like a scary problem.

**Comment by stevendanna** [comment]
I've got an umbrella issue here for this kind of problem as well: https://github.com/cockroachdb/cockroach/issues/61059

**Comment by petermattis** [comment]
I think there is a linter in the Go community for this error. I think we
might have it enabled in the CC codebase. I’ll try to track it down when
I’m at my computer.

**Comment by petermattis** [comment]
https://github.com/jingyugao/rowserrcheck is the linter I was thinking of. Looks like @stevendanna is already aware of this. We have this enabled in CC and it found at least one missing error check.

**Comment by rytaft** [comment]
Is this needed for 21.2?

**Comment by tbg** [comment]
I don't think this is "strictly" needed, though we have had multiple scary false positives as a result of missing these checks. This isn't a lot of work to fix.

**Comment by cucaroach** [comment]
I can put this on the front burner if we think it would be good to have for 21.2.

**Comment by rytaft** [comment]
I think that would be good. Moving this to the stability milestone.

**Comment by uhthomas** [comment]
Further discussion of analysis diagnostics for this kind of incorrect code https://github.com/golang/go/issues/20148
