### ISSUE TITLE
Create a view in CRDB_INTERNAL which will transparently surface in-memory and persisted SQL stats

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#68193]
We are enabling [persisted statistics ](https://github.com/cockroachdb/cockroach/issues/64743) in 21.2. We should allow developers to also easily query the most recent in-memory statistics as well. 

Developers will now be able to query historical and the most recent statistics with a single cluster-level view. 

Epic: CRDB-394

**Comment by Azhng** [comment]
@kevin-v-ngo can we close this issue now that we have `crdb_internal.{statement,transaction}_statistics` virtual tables ?
