### ISSUE TITLE
sql: sql.defaults.disallow_full_table_scans.enabled=true prevents introspection actions like `SHOW` commands

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/cockroach#68190]
In 20.2, we added `sql.defaults.disallow_full_table_scans.enabled`. We've received feedback that the setting is impossible to enable because it blocks all queries that plan a full table scan, including introspection via `SHOW` commands.

Ideas:
* disallow full table scans above a threshold
* ignore queries against system tables
* ignore SHOW queries

**Comment by rytaft** [comment]
Is this needed for 21.2?

**Comment by vy-ton** [comment]
It likely prevents any usage of the setting. Would be good to fix but since no user has reported this since 20.2, I wouldn't say it's required

**Comment by rytaft** [comment]
I'll move it to the 22.1 high likelihood bucket. If we finish the critical items for 21.2 maybe we can squeeze it in (or fix later and backport)

**Comment by michae2** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/69371
