### ISSUE TITLE
Save column sorts across a user session

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#68199]
The DB console should save the column sort specified by the user across a session. For instance, when the user drills into the Statement details page, coming back to the Statements overview page should have the column ordering/sort preserved.

Epic: CRDB-9867

**Comment by kevin-v-ngo** [comment]
Note this behavior would need to be consistent with all other pages in the DB console

**Comment by maryliag** [comment]
List of locations to update the behaviour:

- [ ] Statement page
- [ ] Transaction Page
- [ ] Sessions Page
- [ ] Database Page
- [ ] Jobs Page
