### ISSUE TITLE
changefeedccl: Add parse tests for changefeedst

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#68207]
Add (data driven) parse test for `CREATE CHANGEFEED` statement
Ditto for `SHOW CHANGEFEED JOB`

See  pkg/sql/parser/testdata/control_job as an example

**Comment by spiffyyeng** [comment]
Think we can close this... seems like we already have parse tests for these statements

`CREATE CHANGEFEED`:  https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/parser/testdata/changefeed#L10-L66

`SHOW CHANGEFEED JOBS`: https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/parser/testdata/show#L517-L546
