### ISSUE TITLE
PostgreSQL difference: tuple ordering from CTE/subquery table

### ISSUE THREAD

**Issue by benjie** [cockroachdb/cockroach#68211]
**Describe the problem**

Tuple ordering is not preserved from CTE or subquery tables.

**To Reproduce**

Here's the base query:

```
select * from generate_series(1, 10) i order by i % 5 asc, i asc;
┌────┐
│ i  │
├────┤
│  5 │
│ 10 │
│  1 │
│  6 │
│  2 │
│  7 │
│  3 │
│  8 │
│  4 │
│  9 │
└────┘
```

If you put this in either a CTE or a subquery table you get re-ordered result:

```
select * from (select * from generate_series(1, 10) i order by i % 5 asc, i asc) tmp;
with tmp as (select * from generate_series(1, 10) i order by i % 5 asc, i asc) select * from tmp;
┌────┐
│ i  │
├────┤
│  1 │
│  2 │
│  3 │
│  4 │
│  5 │
│  6 │
│  7 │
│  8 │
│  9 │
│ 10 │
└────┘
```

**Expected behavior**

PostgreSQL maintains the tuple order in these situations:

```
with tmp as (select * from generate_series(1, 10) i order by i % 5 asc, i asc) select * from tmp;
┌────┐
│ i  │
├────┤
│  5 │
│ 10 │
│  1 │
│  6 │
│  2 │
│  7 │
│  3 │
│  8 │
│  4 │
│  9 │
└────┘
```

**Additional data / screenshots**

I suspect this isn't technically a bug versus the SQL standard (am not sure), but it's certainly a divergence versus PostgreSQL's behaviour.

**Environment:**
 - CockroachDB version: CCL v21.2.0-alpha.00000000-2778-g5b971c2443 @ 2021/07/28 12:49:32 (go1.16.6)
 - Server OS: Ubuntu 21.04
 - Client app: psql

**Additional context**
What was the impact?

PostGraphile relies on the order being preserved in these cases. Removing, duplicating, moving, or reinforcing (e.g. using `row_number()`) the ordering is not feasible for PostGraphile without sacrificing PostgreSQL performance (the current behaviour has been finely tuned) or requiring branched handling of PostgreSQL vs CockroachDB.

**Comment by benjie** [comment]
The actual query:

```sql
with __local_0__ as (
  select to_json(
    (
      json_build_object(
        '@node'::text,
        (
          json_build_object(
            'col1'::text,
            (__local_1__."col1")
          )
        )
      )
    )
  ) as "@edges"
  from (
    select __local_1__.*
    from "a"."testview" as __local_1__
    where (TRUE) and (TRUE)
    order by __local_1__."col1" DESC
  ) __local_1__
),
__local_2__ as (
  select json_agg(
    to_json(__local_0__)
  ) as data
  from __local_0__
)
select coalesce(
  (
    select __local_2__.data
    from __local_2__
  ),
  '[]'::json
) as "data"
```

and the query plan:

```
distribution: local
vectorized: true

• root
│
├── • values
│     size: 1 column, 1 row
│
└── • subquery
    │ id: @S1
    │ original sql: (SELECT __local_2__.data FROM __local_2__)
    │ exec mode: one row
    │
    └── • render
        │ estimated row count: 1
        │
        └── • group (scalar)
            │ estimated row count: 1
            │
            └── • render
                │ estimated row count: 1
                │
                └── • scan
                      estimated row count: 1 (100% of the table; stats collected 9 hours ago)
                      table: view_table@primary
                      spans: FULL SCAN
```

versus PostgreSQL:

```
Result  (cost=193.56..193.57 rows=1 width=32)
  InitPlan 1 (returns $0)
    ->  Aggregate  (cost=193.54..193.55 rows=1 width=32)
          ->  Sort  (cost=142.54..147.64 rows=2040 width=12)
                Sort Key: view_table.col1 DESC
                ->  Seq Scan on view_table  (cost=0.00..30.40 rows=2040 width=12)
```

This correlates with the GraphQL query:

```graphql
{
  b: allTestviews(orderBy: COL1_DESC) { edges { node { col1 } } }
}
```

**Comment by RaduBerinde** [comment]
This isn't technically guaranted in postgres either; the docs say "A particular output ordering can only be guaranteed if the sort step is explicitly chosen.". https://www.postgresql.org/docs/13/queries-order.html

It works out that way in practice because of pg's implementation. I don't think we can match this in CockroachDB without a lot of work and possibly regressions.

**Comment by RaduBerinde** [comment]
I believe the right way to do this would be something like:

```
with __local_0__ as (
  select to_json(
    (
      json_build_object(
        '@node'::text,
        (
          json_build_object(
            'col1'::text,
            (__local_1__."col1")
          )
        )
      )
    )
  ) as "@edges", __local_1__."col1" AS "@edges_ord"
  from (
    select __local_1__.*
    from "a"."testview" as __local_1__
    where (TRUE) and (TRUE)
    order by __local_1__."col1" DESC
  ) __local_1__
),
__local_2__ as (
  select json_agg(
    to_json(__local_0__."@edges" ORDER BY __local_0__.@edges_ord)
  ) as data
  from __local_0__
)
select coalesce(
  (
    select __local_2__.data
    from __local_2__
  ),
  '[]'::json
) as "data"
```

Note the extra projected `col1` from the first CTE and the `ORDER BY` inside the `json_agg()` aggregation function. This should work in PostgreSQL as well; I would be surprised if it's significantly slower than the original query, can you try it?

By the way, the `to_json` calls seem redundant (`json_build_object` should already return json).

**Comment by benjie** [comment]
Yeah the to_json is redundant but removing it complicates code in another area; I decided to leave it be in the v4 architecture.

**Comment by benjie** [comment]
Actually I vaguely remember that there were some differences in behaviour; I'm pretty sure that there was a data type that came through incorrectly if the `to_json` wasn't added; but we can see in Postgres that the statement with the `json_agg(to_json(...))` versus `json_agg(...)` does not give identical results:

```
[pggql_test] # select json_agg(person) from person;
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                            json_agg                                                                                            │
├────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ [{"id":1,"person_full_name":"John Smith","aliases":[],"about":null,"email":"john.smith@email.com","site":null,"last_login_from_ip":"192.168.0.1","created_at":null},                          ↵│
│  {"id":2,"person_full_name":"Sara Smith","aliases":[],"about":null,"email":"sara.smith@email.com","site":null,"last_login_from_ip":"10.1.2.3","created_at":null},                             ↵│
│  {"id":3,"person_full_name":"Budd Deey","aliases":[],"about":"Just a friendly human","email":"budd.deey@email.com","site":null,"last_login_from_ip":"172.21.22.23","created_at":null},        ↵│
│  {"id":4,"person_full_name":"Kathryn Ramirez","aliases":[],"about":null,"email":"kathryn.ramirez@email.com","site":null,"last_login_from_ip":"192.168.1.2","created_at":null},                ↵│
│  {"id":5,"person_full_name":"Joe Tucker","aliases":[],"about":null,"email":"joe.tucker@email.com","site":null,"last_login_from_ip":"192.168.0.2","created_at":null},                          ↵│
│  {"id":6,"person_full_name":"Twenty Seventwo","aliases":[],"about":null,"email":"graphile-build.issue.27.exists@example.com","site":null,"last_login_from_ip":"10.1.2.254","created_at":null}] │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
(1 row)

Time: 0.403 ms
[pggql_test] # select json_agg(to_json(person)) from person;
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
├──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ [{"id":1,"person_full_name":"John Smith","aliases":[],"about":null,"email":"john.smith@email.com","site":null,"last_login_from_ip":"192.168.0.1","created_at":null}, {"id":2,"person_full_name":"Sara Smith","aliases":[],"about":null,"email":"sara.smith@email.com","site":null,"last_login_from_ip":"10.1.2.3","created_at":null}, {"id":3,"person_full_name":"Budd Deey","aliases":[],"about":"Just a friendly human","email":"budd.deey@email.com","site":null,"last_login_from_ip":
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
(1 row)
Time: 0.366 ms
```

**Comment by benjie** [comment]
From the PostgreSQL manual:

> Alternatively, supplying the input values from a sorted subquery will usually work. For example:
>
> ```
> SELECT xmlagg(x) FROM (SELECT x FROM test ORDER BY y DESC) AS tab;
> ```
>
> Beware that this approach can fail if the outer query level contains additional processing, such as a join, because that might cause the subquery's output to be reordered before the aggregate is computed.
> -- https://www.postgresql.org/docs/current/functions-aggregate.html

This is the behaviour we rely on and it's worked for every version of PostgreSQL we've tried so far (9.4 -> 13). Without this, more complex queries cannot work easily without sacrificing PostgreSQL performance, for example:

```sql
select func(tmp)
from (
  select *
  from post
  where <complex conditions>
  order by <complex order values referencing other tables/functions>
  limit 3
) as tmp
```

Here we can't add "order" information to the subquery `tmp` so that we can officially maintain its behaviour because if we did then we could no longer feed the `post` type to `func(p post)`. We could solve this by doing e.g. `select post, (row_number()...)` inside of the `tmp` subquery and then feeding `func(tmp.post)`, but this is measurably slower in PostgreSQL over larger unindexed queries because every row has to be transformed even if it is later thrown away due to the `limit` - and the cost of doing this can get very large with deeply nested GraphQL queries being converted. A _lot_ of effort has been spent in finding the current optimal PostgreSQL performing code.

**Comment by RaduBerinde** [comment]
> Alternatively, supplying the input values from a sorted subquery will usually work. For example:

This will also work for CockroachDB. The ORDER BY that is specified in the inner SELECT will be taken into account as the required aggregation order. It just won't also be passed through as required ordering on the outer query. Example:
```
create table t (x int); insert into t values (1),(5),(2),(7);

select json_agg(json_build_object('foo', x)) from t;
                      json_agg
----------------------------------------------------
  [{"foo": 1}, {"foo": 5}, {"foo": 2}, {"foo": 7}]


select json_agg(json_build_object('foo', x)) from (select * from t order by x);
                      json_agg
----------------------------------------------------
  [{"foo": 1}, {"foo": 2}, {"foo": 5}, {"foo": 7}]
```

I believe that in your query we can add `order by (__local_0__."@edges"->'@node'->'col1')::int DESC` (replace `int` with whatever type `col1` is) as below and we don't need to pass through any extra column. Maybe this change is more feasible to make (and less disruptive to PostgreSQL)?

```
with __local_0__ as (
  select to_json(
    (
      json_build_object(
        '@node'::text,
        (
          json_build_object(
            'col1'::text,
            (__local_1__."col1")
          )
        )
      )
    )
  ) as "@edges"
  from (
    select __local_1__.*
    from "a"."testview" as __local_1__
    where (TRUE) and (TRUE)
    order by __local_1__."col1" DESC
  ) __local_1__
),
__local_2__ as (
  select json_agg(
    to_json(__local_0__)
  ) as data
  from (select * from __local_0__ order by (__local_0__."@edges"->'@node'->'col1')::int DESC)
)
select coalesce(
  (
    select __local_2__.data
    from __local_2__
  ),
  '[]'::json
) as "data"
```

**Comment by vy-ton** [comment]
> branched handling of PostgreSQL vs CockroachDB

Is it possible to explore this further for specific exceptions to avoid affecting the optimal PostgreSQL performing code?

**Comment by RaduBerinde** [comment]
I also want to clarify that the quote above from the pg manual refers specifically to the order in which elements are aggregated. The example you follow with is something else, it's about maintaining whatever row order was specified by an inner query through an outer query that has no ORDER BY. Indeed that does not work the same in Cockroach.

> because if we did then we could no longer feed the post type to func(p post).

Ok, so l need to understand this more. You are passing the entire table name as an argument. What does that achieve? Is it equivalent to `ROW (tmp.*)`? And if yes, we could just do `ROW (tmp.col1)` instead, and that would allow more columns in `tmp` no?

**Comment by RaduBerinde** [comment]
> Ok, so l need to understand this more. You are passing the entire table name as an argument. What does that achieve? Is it equivalent to ROW (tmp.*)? And if yes, we could just do ROW (tmp.col1) instead, and that would allow more columns in tmp no?

I looked into this some more. The `(tmp)` and `ROW (tmp.*)` have tuple labels, which make it into the json object if `to_json` is used. That doesn't work with `ROW (tmp.col1)`; `json_build_object` would need to be used to specify each column separately, eg:
```
root@127.8.36.6:26257/defaultdb> select to_json(ab) from ab;
       to_json
---------------------
  {"a": 1, "b": 10}
  {"a": 2, "b": 20}

root@127.8.36.6:26257/defaultdb> select to_json(ab.*) from ab;

       to_json
---------------------
  {"a": 1, "b": 10}
  {"a": 2, "b": 20}

root@127.8.36.6:26257/defaultdb> select to_json((ab.a, ab.b)) from ab;
        to_json
-----------------------
  {"f1": 1, "f2": 10}
  {"f1": 2, "f2": 20}

root@127.8.36.6:26257/defaultdb> select json_build_object('a', ab.a, 'b', ab.b) from ab;
  json_build_object
---------------------
  {"a": 1, "b": 10}
  {"a": 2, "b": 20}
```

**Comment by benjie** [comment]
To be clear there's a large number of issues here that all relate to the tuple ordering in subqueries/CTEs; we're just looking at a couple examples.

One key issue is that:

```sql
select ...
from my_table as table_alias
where <complex conditions>
order by <complex order>
limit 5
```

is expensive if an index cannot be used; and yet users definitely invoke queries like this. In Postgres, assuming a sequential scan, this involves a top-N sort where it builds the row (e.g. `select table_alias.*`) and adds it to the "limit 5" cache; when it finds a row that's "better" (according to the `order by`) than the existing 5 entries it boots one out and adds the new row; then it keeps going until the sequential scan is complete and what's left is your result set.

For a `select table_alias.*` query, this is relatively fast, but the moment you start adding transforms to the data (e.g. replacing `select table_alias.*` with `select json_build_object(...)` or even `select table_alias` without the `.*`, and especially when adding function calls and subqueries) Postgres evaluates these transforms during the sequential scan _for every row_ and for larger queries (where the selection is more complex) this becomes really really expensive.

In PostGraphile we do the `select *` first to have Postgres efficiently return us 5 rows, and _then_ we apply the transforms on those 5 rows treating the subquery as if it were the original table - this means Postgres has to do the least amount of work for these 5 rows, giving us significant speedups. A very simplified example of what we do is something like:

```sql
select
  something_complex(tbl),
  something_else_complex(tbl, 2)
from (
  select table_alias.*
  from my_table as table_alias
  where <complex conditions>
  order by <complex order>
  limit 5
) tbl
```

Critically the tuples from `tbl` can be cast directly to `my_table` so they can be used as inputs to functions that accept a row type, e.g.:

```sql
create function person_full_name(p person) returns text as $$
  select p.first_name || ' ' || p.last_name;
$$ language sql immutable;
```

If we were to start complicating `select table_alias.*`, e.g. by doing `select table_alias as row, row_number() over (order by ...)`, then the performance benefits of not doing row translation would be lost. And without this additional data we cannot "re-sort" the data in the outer query.


> I also want to clarify that the quote above from the pg manual refers specifically to the order in which elements are aggregated. 

Yes, but that's just an artifact of the order the rows are processed/handed to the function - aggregates are effectively reductions over the input rows.

**Comment by RaduBerinde** [comment]
> To be clear there's a large number of issues here that all relate to the tuple ordering in subqueries/CTEs; we're just looking at a couple examples.
> 
> One key issue is that:
> 
> ```sql
> select ...
> from my_table as table_alias
> where <complex conditions>
> order by <complex order>
> limit 5
> ```
> 
> is expensive if an index cannot be used; and yet users definitely invoke queries like this. In Postgres, assuming a sequential scan, this involves a top-N sort where it builds the row (e.g. `select table_alias.*`) and adds it to the "limit 5" cache; when it finds a row that's "better" (according to the `order by`) than the existing 5 entries it boots one out and adds the new row; then it keeps going until the sequential scan is complete and what's left is your result set.

What doesn't click for me in this reasoning is that `<complex order>` needs to be evaluated for all table rows (and stored for the top 5 candidates during the sort). So why would returning it as an additional column be a significant slow down?

```
select
  something_complex(tbl),
  something_else_complex(tbl, 2)
from (
  select table_alias.*, <complex order> AS ord
  from my_table as table_alias
  where <complex conditions>
  order by ord
  limit 5
) tbl
ORDER BY tbl.ord
```

I understand the separate issue of no longer being able to use `tbl` or `tbl.*` in expressions. It's unfortunate you can't express that for a subset of columns (in a way that is exactly equivalent). IMO this syntax can always be avoided using the columns directly but I understand it can require potentially significant query changes.

@DrewKimball showed me a prototype where (subject to a cluster setting) we do the thing above (carrying over ordering columns) internally, invisible to the query. Perhaps that would be the way to move forward at least for now.

**Comment by benjie** [comment]
> What doesn't click for me in this reasoning is that <complex order> needs to be evaluated for all table rows (and stored for the top 5 candidates during the sort). So why would returning it as an additional column be a significant slow down?

It's more to do with the selection set as I detailed above; e.g. here I have a table with 10 million rows; first a simple selection set with no transform - `select *` (each query repeated three times to show stability of measurement):


```
[test] # select * from flag_test order by (flags_jsonb_list->>'0')::int % 93 desc limit 5;
┌────┬─────────────────────┬──────────────────────────────────────┬──────────────────────────┬───┐
│ id │     flags_list      │           flags_jsonb_obj            │     flags_jsonb_list     │ t │
├────┼─────────────────────┼──────────────────────────────────────┼──────────────────────────┼───┤
│  2 │ {10000002,10000003} │ {"10000002": true, "10000003": true} │ ["10000002", "10000003"] │ t │
│  3 │ {10000004,10000005} │ {"10000004": true, "10000005": true} │ ["10000004", "10000005"] │ t │
│  4 │ {10000006,10000007} │ {"10000006": true, "10000007": true} │ ["10000006", "10000007"] │ t │
│  5 │ {10000008,10000009} │ {"10000008": true, "10000009": true} │ ["10000008", "10000009"] │ t │
│  1 │ {10000000,10000001} │ {"10000000": true, "10000001": true} │ ["10000000", "10000001"] │ t │
└────┴─────────────────────┴──────────────────────────────────────┴──────────────────────────┴───┘
(5 rows)

Time: 827.278 ms
[test] # select * from flag_test order by (flags_jsonb_list->>'0')::int % 93 desc limit 5;
┌────┬─────────────────────┬──────────────────────────────────────┬──────────────────────────┬───┐
│ id │     flags_list      │           flags_jsonb_obj            │     flags_jsonb_list     │ t │
├────┼─────────────────────┼──────────────────────────────────────┼──────────────────────────┼───┤
│  2 │ {10000002,10000003} │ {"10000002": true, "10000003": true} │ ["10000002", "10000003"] │ t │
│  3 │ {10000004,10000005} │ {"10000004": true, "10000005": true} │ ["10000004", "10000005"] │ t │
│  4 │ {10000006,10000007} │ {"10000006": true, "10000007": true} │ ["10000006", "10000007"] │ t │
│  5 │ {10000008,10000009} │ {"10000008": true, "10000009": true} │ ["10000008", "10000009"] │ t │
│  1 │ {10000000,10000001} │ {"10000000": true, "10000001": true} │ ["10000000", "10000001"] │ t │
└────┴─────────────────────┴──────────────────────────────────────┴──────────────────────────┴───┘
(5 rows)

Time: 822.121 ms
[test] # select * from flag_test order by (flags_jsonb_list->>'0')::int % 93 desc limit 5;
┌────┬─────────────────────┬──────────────────────────────────────┬──────────────────────────┬───┐
│ id │     flags_list      │           flags_jsonb_obj            │     flags_jsonb_list     │ t │
├────┼─────────────────────┼──────────────────────────────────────┼──────────────────────────┼───┤
│  2 │ {10000002,10000003} │ {"10000002": true, "10000003": true} │ ["10000002", "10000003"] │ t │
│  3 │ {10000004,10000005} │ {"10000004": true, "10000005": true} │ ["10000004", "10000005"] │ t │
│  4 │ {10000006,10000007} │ {"10000006": true, "10000007": true} │ ["10000006", "10000007"] │ t │
│  5 │ {10000008,10000009} │ {"10000008": true, "10000009": true} │ ["10000008", "10000009"] │ t │
│  1 │ {10000000,10000001} │ {"10000000": true, "10000001": true} │ ["10000000", "10000001"] │ t │
└────┴─────────────────────┴──────────────────────────────────────┴──────────────────────────┴───┘
(5 rows)

Time: 821.291 ms
```

Average of 823ms.

Now the exact same query but instead of selection `*` we're selecting the entire tuple as a single row value so that we could later pass it to a function or similar:

```
[test] # select flag_test from flag_test order by (flags_jsonb_list->>'0')::int % 93 desc limit 5;
┌───────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                               flag_test                                               │
├───────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ (2,"{10000002,10000003}","{""10000002"": true, ""10000003"": true}","[""10000002"", ""10000003""]",t) │
│ (3,"{10000004,10000005}","{""10000004"": true, ""10000005"": true}","[""10000004"", ""10000005""]",t) │
│ (4,"{10000006,10000007}","{""10000006"": true, ""10000007"": true}","[""10000006"", ""10000007""]",t) │
│ (5,"{10000008,10000009}","{""10000008"": true, ""10000009"": true}","[""10000008"", ""10000009""]",t) │
│ (1,"{10000000,10000001}","{""10000000"": true, ""10000001"": true}","[""10000000"", ""10000001""]",t) │
└───────────────────────────────────────────────────────────────────────────────────────────────────────┘
(5 rows)

Time: 1008.060 ms (00:01.008)
[test] # select flag_test from flag_test order by (flags_jsonb_list->>'0')::int % 93 desc limit 5;
┌───────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                               flag_test                                               │
├───────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ (2,"{10000002,10000003}","{""10000002"": true, ""10000003"": true}","[""10000002"", ""10000003""]",t) │
│ (3,"{10000004,10000005}","{""10000004"": true, ""10000005"": true}","[""10000004"", ""10000005""]",t) │
│ (4,"{10000006,10000007}","{""10000006"": true, ""10000007"": true}","[""10000006"", ""10000007""]",t) │
│ (5,"{10000008,10000009}","{""10000008"": true, ""10000009"": true}","[""10000008"", ""10000009""]",t) │
│ (1,"{10000000,10000001}","{""10000000"": true, ""10000001"": true}","[""10000000"", ""10000001""]",t) │
└───────────────────────────────────────────────────────────────────────────────────────────────────────┘
(5 rows)

Time: 1079.481 ms (00:01.079)
[test] # select flag_test from flag_test order by (flags_jsonb_list->>'0')::int % 93 desc limit 5;
┌───────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                               flag_test                                               │
├───────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ (2,"{10000002,10000003}","{""10000002"": true, ""10000003"": true}","[""10000002"", ""10000003""]",t) │
│ (3,"{10000004,10000005}","{""10000004"": true, ""10000005"": true}","[""10000004"", ""10000005""]",t) │
│ (4,"{10000006,10000007}","{""10000006"": true, ""10000007"": true}","[""10000006"", ""10000007""]",t) │
│ (5,"{10000008,10000009}","{""10000008"": true, ""10000009"": true}","[""10000008"", ""10000009""]",t) │
│ (1,"{10000000,10000001}","{""10000000"": true, ""10000001"": true}","[""10000000"", ""10000001""]",t) │
└───────────────────────────────────────────────────────────────────────────────────────────────────────┘
(5 rows)

Time: 1059.685 ms (00:01.060)
```

Note that this has already increased to 1049ms; that's more than a 27% increase in time taken and it's not even added any extra data yet - it's just done a basic transform on the tuples. This is a simple table with just 3 columns, but as tables get more complex this cost of transforming the data only increases. _This_ is the cost I'm trying to describe in the paragraph I wrote above:

> For a `select table_alias.*` query, this is relatively fast, but the moment you start adding transforms to the data (e.g. replacing `select table_alias.*` with `select json_build_object(...)` or even `select table_alias` without the `.*`, and especially when adding function calls and subqueries) Postgres evaluates these transforms during the sequential scan _for every row_ and for larger queries (where the selection is more complex) this becomes really really expensive.

---

> IMO this syntax can always be avoided using the columns directly but I understand it can require potentially significant query changes.

Correct me if I'm wrong, but given the function accepts a row tuple (composite type) I think you're suggesting that instead of doing:

```sql
select
  something_complex(tbl),
  something_else_complex(tbl, 2)
from (
  select table_alias.*
  from my_table as table_alias
  where <complex conditions>
  order by <complex order>
  limit 5
) tbl
```

we do something more like:

```sql
select
  something_complex((tbl.col1, tbl.col2, tbl.col3, tbl.col4, tbl.col5, tbl.col6, tbl.col7, tbl.col8, tbl.col9, tbl.col10, tbl.col11, tbl.col12, ...)::my_table),
  something_else_complex((tbl.col1, tbl.col2, tbl.col3, tbl.col4, tbl.col5, tbl.col6, tbl.col7, tbl.col8, tbl.col9, tbl.col10, tbl.col11, tbl.col12, ...)::my_table, 2)
from (
  select table_alias.col1, table_alias.col2, table_alias.col3, table_alias.col4, table_alias.col5, table_alias.col6, table_alias.col7, table_alias.col8, table_alias.col9, table_alias.col10, table_alias.col11, table_alias.col12, ...
  from my_table as table_alias
  where <complex conditions>
  order by <complex order>
  limit 5
) tbl
```

You're not wrong in that we _could_ do that, but doing so is not without tradeoffs:

- the generated SQL is significantly more complex
- if the table diverges (e.g. because a column is added during a migration) then the servers issuing queries like the above will all start failing until they're updated to the new table definitions
- parsing the SQL becomes measurably more expensive (I've found that even adding significant amounts of _whitespace_ to an SQL query makes it measurably slower to process)
- yuck

---

> @DrewKimball showed me a prototype where (subject to a cluster setting) we do the thing above (carrying over ordering columns) internally, invisible to the query. Perhaps that would be the way to move forward at least for now.

This sounds promising!
