### ISSUE TITLE
sql: plain text JSON type

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/cockroach#68235]
**Is your feature request related to a problem? Please describe.**

When EXPORTing a JSONB column (to CSV), there seems to be significant expense in converting to string. (In this case a client is working with a multi-TB table.)

**Describe the solution you'd like**

A plain text JSON type, [as in Postgres](https://www.postgresql.org/docs/13/datatype-json.html). This would reduce work when the intended output is a string.

This would have the same pros and cons as mentioned in the Postgres docs above. The user can choose their trade-offs.

(Out of scope for this request is how to deal with backwards compatibility or breaking changes, i.e., that the JSON type currently aliases to JSONB in CRDB. We could figure out a deprecation plan, server setting, or perhaps even a new name for the type.)

Jira issue: CRDB-8941

**Comment by jordanlewis** [comment]
Hey @shermanCRL - as a workaround, we can ask people to store their json data as strings. To do JSON operations on strings, you can first cast the strings to JSON.

**Comment by ajwerner** [comment]
Should we keep this open? If we do, it's going straight to the backlog and even there, I don't think schema is the right one. SQL Experience, IIUC, owns the type system. Execution owns the row encoding and decoding. This is a big pile of work and not a ton of obvious gain. If you want to validate that the string is json you can add a `CHECK` constraint that casts the string column to `JSON`. 

Another valuable thing to do might be to accelerate the various encoding and decoding methods on our `json.JSON` implementations. I know @miretskiy has wanted to do that.

**Comment by shermanCRL** [comment]
Yeah, the problem to solve is JSONB → string performance, and this ticket is merely an idea in that direction. Might not be the right one. If there is not much interest from others on this, we can close, and I’ll pursue the perf issue specifically.

**Comment by ajwerner** [comment]
We now have virtual computed columns as well as `NOT VISIBLE`. I think that means that we can do something like:

```
demo@127.0.0.1:54345/movr> CREATE TABLE t (json_str STRING NOT NULL, as_json JSON AS (json_str::JSON) VIRTUAL NOT VISIBLE);
CREATE TABLE
demo@127.0.0.1:54345/movr> INSERT INTO t VALUES ('{"asdfasdf": "foo"}');
INSERT 1
demo@127.0.0.1:54345/movr> SELECT * FROM t WHERE as_json->>'asdfasdf' = 'foo';
       json_str
-----------------------
  {"asdfasdf": "foo"}
(1 row)
```
