### ISSUE TITLE
restore: investigate bi-modal restore performance

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#68237]
When running the restore2TB roachtest with increased concurrency, some tests complete in about 20 minutes and some take over an hours. It usually isn't somewhere in between. This is visible in the bi-modal distribution displayed in the [roachperf results for this test](https://roachperf.crdb.dev/?filter=&view=restore2TB%2Fnodes%3D6%2Fcpus%3D8%2Fpd-volume%3D2500GB&tab=gce).

The first thing to investigate is if there is a correlation between the hardware that it is running on and the test times (i.e. if the test is run on the same cluster repeatedly, do we see all tests finish in about the same time?).

Jira issue: CRDB-8943

**Comment by miretskiy** [comment]
Do you have any graphs showing network utilization?

**Comment by pbardea** [comment]
Yep, I'm also seeing a similar down-ramp pattern there:
Fast:
<img width="989" alt="Screen Shot 2021-08-11 at 15 17 56" src="https://user-images.githubusercontent.com/507390/129089811-989379be-14d8-421a-b93a-220c38beca97.png">

Slow:
<img width="980" alt="Screen Shot 2021-08-11 at 15 18 21" src="https://user-images.githubusercontent.com/507390/129089803-904914c8-cf29-4ce2-989b-d50d5664f33d.png">

**Comment by miretskiy** [comment]
Comparing networking with good case -- does good case has similar scale, but maintains throughput?

**Comment by pbardea** [comment]
Yep, which I think is consistent with the amount of AddSSTable requests that are going through.

I've been able to reproduce this a few times and am noticing that there's a pretty strong correlation with the hardware that it's running on:

Here are some `cockroach systembench` summaries of a node that consistently runs slow vs fast.

Slow:
```
_elapsed____ops(total)__mb(total)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
    1m0s        233647     7301.0      0.3      0.0      2.5      5.0    151.0
```

Fast:
```
_elapsed____ops(total)__mb(total)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
    1m0s        329007    10281.0      0.2      0.0      2.2      2.5    637.5
```

**Comment by pbardea** [comment]
Results for all nodes. I'm not 100% sure if the p99 differential I'm seeing is significant enough to affect these disks but I wonder if the latency on these disks could be what is determining the bimodal performance we're seeing (especially since they're both running the same binary):
Slow:
```
   1: 1m0s        242469     7577.0      0.2      0.0      2.5      4.7    167.8
   2: 1m0s        251695     7865.0      0.2      0.0      2.5      4.7    142.6
   3: 1m0s        243215     7600.0      0.2      0.0      2.5      4.7    159.4
   4: 1m0s        213183     6661.0      0.3      0.0      2.9      5.5    159.4
   5: 1m0s        237039     7407.0      0.3      0.0      2.6      5.0    167.8
   6: 1m0s        239519     7484.0      0.3      0.0      2.6      4.7    151.0
```

Fast:
```
   1: 1m0s        325727    10178.0      0.2      0.0      2.2      2.5    604.0
   2: 1m0s        257302     8040.0      0.2      0.0      2.6      3.8    704.6
   3: 1m0s        266063     8314.0      0.2      0.0      2.6      3.5    771.8
   4: 1m0s        321007    10031.0      0.2      0.0      2.2      2.6    738.2
   5: 1m0s        262999     8218.0      0.2      0.0      2.6      3.7    738.2
   6: 1m0s        332047    10376.0      0.2      0.0      2.2      2.5    637.5
```

**Comment by miretskiy** [comment]
What was the volume size? I see restore 2tb runs in different configurations, one with default size (which I belive is 375G) and another 2.5T?

**Comment by pbardea** [comment]
Yep, this test is running on the 2.5T PD config -- supposedly to remove any chance of disk bottlenecks since the limits are quite high on the disks. Restore doesn't usually approach either the IOPS or throughput limit on these disks.

**Comment by miretskiy** [comment]
Better safe than sorry -- when you recreate slow performance, capture `lsblk` information to double check we're running on good disks.

**Comment by pbardea** [comment]
Yep, the disks look like what I expect:
```
~$ lsblk
NAME    MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
...
sdb       8:16   0   2.5T  0 disk /mnt/data1
```

**Comment by pbardea** [comment]
Next steps here:
- Try to see if grabbing a trace of the restore in fast and slow regimes to see if any bottlenecks stand out
