### ISSUE TITLE
sql: creating new tables using `crdb_internal.unsafe_upsert_descriptor` should affect ID generation

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#68230]
**Describe the problem**

If you use a tool like `cockroach debug doctor recreate` to add descriptors, it will not change the ID generation counter. That means that subsequent descriptor creation may fail due to a conflict with existing descriptors.

**Comment by postamar** [comment]
This should only fast-forward the counter if the `force` flag is set.
