### ISSUE TITLE
logging: add version info to structured events

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#68240]
The eventlog table is very useful when debugging customer issues, especially when there is confusion or disagreement about what was run on the cluster and when.

In many cases, an upgrade is involved; it would be great to know which version (specifically gateway's binary version and cluster version) was in effect at the time a DDL statement was run. This could be included in the `info` json string.

**Comment by ajwerner** [comment]
cc @knz. It'd be swell if the eventlog infra did this for us. Which team owns that infra these days? I don't think it's @cockroachdb/sql-experience

**Comment by knz** [comment]
this is logging, not sql

**Comment by knz** [comment]
dup #70285
