### ISSUE TITLE
tenantcostserver: use counters instead of gauges for tenant usage metrics

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#68291]
See the discussion in #68115: https://reviewable.io/reviews/cockroachdb/cockroach/68115#-Mfs6pYNDlnGaaq8oUCL:-MfsD4_K6rG0Pi41PqH5:b13epe8

Jira issue: CRDB-8974

Epic CRDB-14536

**Comment by knz** [comment]
for reference
![image](https://user-images.githubusercontent.com/642886/175955390-6556bf9a-baaf-4d86-9c9e-ad355106431c.png)
