### ISSUE TITLE
Node memory usage exceeds the configured upper limit

### ISSUE THREAD

**Issue by Feng-Lin-Xi** [cockroachdb/cockroach#68300]
**Describe the problem**

Node memory usage exceeds the configured upper limit

**To Reproduce**
start CLI  : 
     cockroach start --certs-dir=certs --cache=.25 --max-sql-memory=.25 --store=node2 --listen-addr=${localIP}:26257 --http-addr=${localIP}:20000 --join=172.21.0.17:26257,172.21.0.3:26257,172.21.0.16:26257 --background

logs:
   I210731 08:15:13.450342 1 server/config.go:431 ⋮ [-] 4  system total memory: ‹16 GiB›
   I210731 08:15:13.450354 1 server/config.go:433 ⋮ [-] 5  server configuration:
   I210731 08:15:13.450354 1 server/config.go:433 ⋮ [-] 5 +‹max offset             500000000›
   I210731 08:15:13.450354 1 server/config.go:433 ⋮ [-] 5 +‹cache size             3.9 GiB›
   I210731 08:15:13.450354 1 server/config.go:433 ⋮ [-] 5 +‹SQL memory pool size   3.9 GiB›
   I210731 08:15:13.450354 1 server/config.go:433 ⋮ [-] 5 +‹scan interval          10m0s›
   I210731 08:15:13.450354 1 server/config.go:433 ⋮ [-] 5 +‹scan min idle time     10ms›
   I210731 08:15:13.450354 1 server/config.go:433 ⋮ [-] 5 +‹scan max idle time     1s›
   I210731 08:15:13.450354 1 server/config.go:433 ⋮ [-] 5 +‹event log enabled      true›
   I210731 08:15:13.450398 1 1@cli/start.go:954 ⋮ [-] 6  using local environment variables: ‹COCKROACH_BACKGROUND_RE
START=1›
   I210731 08:15:13.450413 1 1@cli/start.go:961 ⋮ [-] 7  process identity: ‹uid 1015 euid 1015 gid 1015 egid 1015›
   I210731 08:15:13.453149 1 1@cli/start.go:1129 ⋮ [-] 8  GEOS loaded from directory ‹/usr/local/lib/cockroach›
   I210731 08:15:13.453171 1 1@cli/start.go:528 ⋮ [-] 9  starting cockroach node

**Expected behavior**

**Environment:**
 - CockroachDB version [21.1.6]
 - Server OS: [e.g. Linux/CentOS Linux release 7.8.2003]

Jira issue: CRDB-8976

**Comment by darinpp** [comment]
Hey Feng, It is hard to see a problem with the information given. Seems like the allocated memory to cache and SQL memory pool is 25% each. From total of 16GiB, that comes to 4GiB each. How do you determine that the memory usage has been exceeded? Cockroach DB uses also memory that isn't tracked by either the cache or the SQL memory pool. But it isn't expected to grow unrestricted over time.

**Comment by Feng-Lin-Xi** [comment]
When I execute the Import command, the memory exceeds 14GB. I restart the program, and the single task still fails. Here are some logs of my service, 

I'm not sure if this error is memory related


goroutine 39484 [IO wait]:
internal/poll.runtime_pollWait(0x7fd1d3c9adb0, 0x72, 0x59f03a0)
	/usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc009416798, 0x72, 0x59f0300, 0x7d45c80, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc009416780, 0xc0065af500, 0x65a, 0x65a, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:159 +0x1a5
net.(*netFD).Read(0xc009416780, 0xc0065af500, 0x65a, 0x65a, 0x8cb145, 0x8d76b4, 0x3c12085)
	/usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0036a6270, 0xc0065af500, 0x65a, 0x65a, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:182 +0x8e
github.com/cockroachdb/cmux.(*MuxConn).Read(0xc004f09560, 0xc0065af500, 0x65a, 0x65a, 0x0, 0x0, 0x7fd1a2f54350)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux/cmux.go:218 +0x115
crypto/tls.(*atLeastReader).Read(0xc00586f460, 0xc0065af500, 0x65a, 0x65a, 0x10000, 0x7fd1d4db4560, 0xc003c6b2b0)
	/usr/local/go/src/crypto/tls/conn.go:779 +0x62
bytes.(*Buffer).ReadFrom(0xc000ce4280, 0x59e2a00, 0xc00586f460, 0x45f8c5, 0x45ba480, 0x4946be0)
	/usr/local/go/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc000ce4000, 0x7fd1a8b82cc0, 0xc004f09560, 0x5, 0xc004f09560, 0x4404740)
	/usr/local/go/src/crypto/tls/conn.go:801 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc000ce4000, 0x0, 0x0, 0x535032)
	/usr/local/go/src/crypto/tls/conn.go:608 +0x115
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:576
crypto/tls.(*Conn).Read(0xc000ce4000, 0xc00540d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1252 +0x15f
net/http.(*connReader).Read(0xc0081021e0, 0xc00540d000, 0x1000, 0x1000, 0xc009416780, 0xc001c80000, 0xfe)
	/usr/local/go/src/net/http/server.go:798 +0x1ad
bufio.(*Reader).fill(0xc005123620)
	/usr/local/go/src/bufio/bufio.go:101 +0x105
bufio.(*Reader).ReadSlice(0xc005123620, 0xa, 0x0, 0xc003c6b988, 0x461bb0, 0xc00517c700, 0x100)
	/usr/local/go/src/bufio/bufio.go:360 +0x3d
bufio.(*Reader).ReadLine(0xc005123620, 0xc00517c700, 0x4df814, 0xc000100000, 0x0, 0x3, 0xc000e70000)
	/usr/local/go/src/bufio/bufio.go:389 +0x34
net/textproto.(*Reader).readLineSlice(0xc00e1f94d0, 0xc00517c700, 0x5334c68, 0xc003c6ba38, 0x69b429, 0xc009416780)
	/usr/local/go/src/net/textproto/reader.go:58 +0x6c
net/textproto.(*Reader).ReadLine(...)
	/usr/local/go/src/net/textproto/reader.go:39
net/http.readRequest(0xc005123620, 0x0, 0xc00517c700, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:1012 +0xaa
net/http.(*conn).readRequest(0xc00402b5e0, 0x5a899a0, 0xc008e13940, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:984 +0x19a
net/http.(*conn).serve(0xc00402b5e0, 0x5a899a0, 0xc008e13940)
	/usr/local/go/src/net/http/server.go:1851 +0x705
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2969 +0x36c

**Comment by darinpp** [comment]
Not sure what this error is. Is there a way for us to reproduce this? I don't know much about the import that you are trying to do.
