### ISSUE TITLE
cdc: support Debezium (via Postgres WAL)

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/cockroach#68333]
Debezium is a platform-agnostic CDC framework, allowing consumers of CDC feeds to plug into any database via a generic adaptor, instead of individually supporting mysql binlogs, mongodb oplogs, etc. This has been requested frequently per @dbist.

Here’s the [architecture](https://debezium.io/documentation/reference/stable/architecture.html) from the Debezium site:

![](https://debezium.io/documentation/reference/stable/_images/debezium-architecture.png)

#### Approaches

I see two options (caveat that I am not an expert on Debezium):

1. Establish compatibility with the [existing Postgres Debezium connector](https://debezium.io/documentation/reference/stable/connectors/postgresql.html). I believe this means emitting CDC events as WAL events? This would be a feature of CRDB.
    - Maybe it’s SQL work? Looks like it uses [PG’s streaming replication protocol](https://www.postgresql.org/docs/current/protocol-replication.html).
    - Related https://github.com/cockroachdb/cockroach/issues/80661
3. Create a new [connector](https://debezium.io/documentation/reference/stable/connectors/index.html). This would be a plugin/component for Debezium, not in CRDB, and presumably written in Java.

---

Update, WAL will likely require functionality that CRDB does not currently offer; WAL is not simply a changefeed “format” or “sink”. Rather, it’s a fully ordered log of events across a whole cluster, of which a changefeed is only a subset.  [Internal conversation](https://cockroachlabs.slack.com/archives/C9TGBJB44/p1652970276341329?thread_ts=1652957216.059139&cid=C9TGBJB44)

Epic CRDB-1776

Jira issue: CRDB-8991

**Comment by miretskiy** [comment]
I think it's fair to say that we will not be supported this feature in this context.
Possibly, we may support pglogical replication.
