### ISSUE TITLE
changefeedccl: Add a governor to detect when range is behind

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#68342]
The changefeed system depends on closed timestamp system publishing
range closed timestamps.  However, if some range fails to publish its closed timestamp
(because of a bug or any other issue), then changefeed will appear to be stuck and
not make any progress.

Usually, this situation is "resolved" by restarting (or pause/resuming) changefeed.

We should add a safety governor (probably to dist sender) so that if the range
does not publish its closed timestamp for a long period of time (some function of side
transport period), then the rangefeed to that range should get restarted.

**Comment by ajwerner** [comment]
I think I'd do this at the DistSender.

**Comment by miretskiy** [comment]
Closing this issue.  Added crdb_internal.active_range_feeds table provides observability into this problem.
