### ISSUE TITLE
sql: Sort order of NULL values

### ISSUE THREAD

**Issue by uptimeDBA** [cockroachdb/cockroach#6835]
By default, PostgreSQL orders *NULL* values **higher** than non-*NULL*s in a sort. 

~~~sql
postgres=# SELECT * FROM t1 ORDER BY b;
 a | b | c 
---+---+---
 1 | 0 | 0
 2 | 0 | 1
 3 | 1 | 0
 4 | 1 | 1
 5 |   | 0
 6 |   | 1
 7 |   |  
(7 rows)
~~~

CockroachDB orders *NULL* values **lower** than non-*NULL*s in a sort. 

~~~sql
root@:26257> SELECT * FROM t1 ORDER BY b;
+---+------+------+
| a |  b   |  c   |
+---+------+------+
| 6 | NULL |    1 |
| 5 | NULL |    0 |
| 7 | NULL | NULL |
| 1 |    0 |    0 |
| 2 |    0 |    1 |
| 4 |    1 |    1 |
| 3 |    1 |    0 |
+---+------+------+
~~~

PostgresSQL has implemented the `NULLS FIRST` `NULLS LAST` optional SQL language extension so their `ORDER BY` clause to enable the placement of *NULL* values within a sort. Their syntax looks (roughly) like:

![postgres_order_by](https://cloud.githubusercontent.com/assets/17366371/15444409/6c367d80-1f44-11e6-9a98-a893c56df229.png)

The defaults are `ASC` and `NULLS LAST`.

CockroachDB's currently looks like:

![cockroach_order_by](https://cloud.githubusercontent.com/assets/17366371/15444420/8b26a850-1f44-11e6-9b43-c21ec5139d90.png)

The default is `ASC`.

My suggestion is two-fold.

1. We change the default position of *NULL* values in a sort to be **higher** than non-*NULLS* to make it the same as PostgreSQL.
2. We add the `NULLS FIRST` `NULLS LAST` options to the `ORDER BY` clause make it the same as PostgreSQL. It would look like:

![proposed_cockroach_order_by](https://cloud.githubusercontent.com/assets/17366371/15444458/095fabe0-1f45-11e6-8ea4-cf0042cae095.png)

I've written a blog article on [NULL handling in CockroachDB](http://uptimedba.github.io/2016/05/I've-got-nothing.-Null-handling-in-CockroachDB/) for some background information.

**Comment by nvanbenschoten** [comment]
Hi Paul, thanks for the suggestion! Most of what you brought up is being discussed over in https://github.com/cockroachdb/cockroach/issues/6224. In short, we've decided to hold off on the `NULLS FIRST` and `NULLS LAST` syntax until there is either more expressed need for the functionality or someone finds themselves looking for work (or looking to contribute!). In regards to the default sort order, @bdarnell had an [interesting observation](https://github.com/cockroachdb/cockroach/issues/6224#issuecomment-213573799) that while null sort order is unspecified in the SQL standard, in practice only the 2 well-known databases which default to nulls-last support changing this with the `NULLS FIRST` clause, while in all of the ones that default to nulls-first this cannot be changed. Following this reasoning, it seems like it would be best to keep the nulls-first ordering, at least while we're inflexible.

**Comment by uptimeDBA** [comment]
Yeah the nulls-first/nulls-last support is a nice-to-have at this point as it's probably not a piece of syntax that gets used very often. 
Regarding the sort order of NULLS, I guess it depends on how much priority you place on compatibility with PostgreSQL SQL. My thinking's around the (future) ease of migrating a PostgreSQL based application over to CockroachDB with minimal surprises.

**Comment by petermattis** [comment]
@uptimeDBA Nice blog post.

I'd be interested to hear about applications that rely on `NULLS FIRST` and `NULLS LAST`.

**Comment by uptimeDBA** [comment]
I can't recall any occurrence of `NULLS FIRST` or `NULLS LAST` being used. Changing the  NULL sort order to sort them higher than non-NULL was a suggestion to align with PostgresSQL default functionality.
