### ISSUE TITLE
Replication Feature Request: Up-replication to non preferred localities after preferred region failure and fail-back

### ISSUE THREAD

**Issue by drewdeally** [cockroachdb/cockroach#68358]
**Is your feature request related to a problem? Please describe.**
Problem: Add non preferred localities to be added to preferred localities as standby for up replication without user interaction with zone configuration changes

**Describe the solution you'd like**

Setup a Cluster with 5 primary regions to store data ranges and standby regions without data ranges only meta, liveness ranges.   When a primary region is down for more than "dead node time", cluster will start to replicate data ranges to standby regions to resolve under replication when one or more nodes are down in a preferred locality.   As preferred nodes resume, data ranges are replicated back and the standby localities data ranges are marked for deletion.   Today, this can be achieved with zone config commands and customer prefers this process to be automated.   This works partially today if a region fails, introducing new nodes in the region or in another new locality will up-replicate returning the cluster to full set of replicas.   When the failed nodes resume, replicas are rebalanced but not returned to the original states.  using Zone Config constraints to set replication preferences will not allow up-relocation to a locality not contained in the zone configuration.  

**Describe alternatives you've considered**
Using Script to monitor health of nodes, zone config commands can be submitted to change replication behavior across preferred and non preferred localites.

**Additional context**

Cluster start with 4 regions, east1-b,east4-b,west1-b,west2-b 
![image](https://user-images.githubusercontent.com/39496073/127950475-6dfdee4a-4208-4bf1-8c8a-b7d1ee755e69.png)

2 hours later west2b is shutdown and system is under replicated.  added west3 nodes to cluster and the system begins to up-replicate 

![image](https://user-images.githubusercontent.com/39496073/127950447-b74cc946-60a0-4978-81fc-97452dec7e18.png)

![image](https://user-images.githubusercontent.com/39496073/127950411-f110c878-d782-41e1-88cd-814cd15dbae5.png)

2.5 hours to up replicate 

![image](https://user-images.githubusercontent.com/39496073/127950672-1d7a5e59-b71c-47ea-8d36-2dd03c114086.png)

West2 is brought back online and replicas are resumed in west2

![image](https://user-images.githubusercontent.com/39496073/127950913-a1ec40e4-3b94-4a61-ba3e-edc10ce2a21d.png)

setting configs such as

![image](https://user-images.githubusercontent.com/39496073/127951176-35a836b3-7d97-4d76-a2b5-3537c8677abc.png)

will not allow for up-replication to any newly added regions for data ranges without zone config commands

Epic CRDB-2521

Jira issue: CRDB-9001

**Comment by drewdeally** [comment]
With 

ALTER RANGE default CONFIGURE ZONE USING
	range_min_bytes = 134217728,
	range_max_bytes = 536870912,
	gc.ttlseconds = 90000,
	num_replicas = 5,
	constraints = e'{+region=us-east1: 1, +region=us-east4: 1, +region=us-west1: 1, +region=us-west2: 1,\n  +region=us-west3: 1}',
	lease_preferences = '[[+region=us-east1]]'

After dead nodes in 2 regions/localities, CRDB up replicates only to regions in the constraints

![image](https://user-images.githubusercontent.com/39496073/128040533-2288f0ac-a322-4ea1-a859-117e85251780.png)

![image](https://user-images.githubusercontent.com/39496073/128040770-e188e48e-b74c-42d1-810c-44ef73c5ffa9.png)

the proposed alternative is the system should have a non preferred setting for standby regions/localitie or newly added regions/localities to be used for upreplication,

**Comment by awoods187** [comment]
We've discussed having both a "failover region" as well as a "testing failover region" to better control for how the allocator spreads replicas. Separately, but also related, we've discussed the notion of "super regions" which also specify those ideas. Finally, we've discussed simply using a separate database per domiciling/failover region group (but require the application to know which equivalent db to talk with based upon the region). We aren't yet sure which options we will pursue but we will plan to evaluate this further for our next release. cc @ajstorm @nvanbenschoten

**Comment by BramGruneir** [comment]
I think we should consider adding non-required per-replica constraints or consider just changing the definition.  

Instead of just
`'{+region=us-central1: 1, +region=us-west1: 2}'`
Allow
`'{region=us-central1: 1, region=us-west1: 2}'` that performs similarly to the required version but if it can't make that requirement, it will allow the replicas to be placed in any available region.

But the more I think about this, the more I think this should just be the default behaviour.  Right now, if you've got 5x and the above setup, the extra 2 just default to our standard behaviour.  So if it cannot meet any of those, we should allow the replicas in other regions (as long as they don't have a negative constraint).  We could also surface a new type of signal, `non-compliant` or something like that to alert the users that there is an issue.
