### ISSUE TITLE
The ability to GRANT "SHOW RANGES" for a role

### ISSUE THREAD

**Issue by data-matt** [cockroachdb/cockroach#68369]
**Is your feature request related to a problem? Please describe.**
We can provide roles with the permission ZONECONFIG, however to debug ranges it is required to be an admin.  As our customer does not want to make all users admin, our customers require the ability to  add `SHOW RANGES` to a role.  

**Describe the solution you'd like**
Create a new role permission that allows users to `SHOW RANGES`

**Describe alternatives you've considered**
Giving admin to users, which is not possible in this customers environment. 

**Additional context**

For example, I created a role where we can alter zone config, but can't debug/verify the ranges using `SHOW RANGES`

`operator@:26257/defaultdb> ALTER TABLE defaultdb.test CONFIGURE ZONE USING lease_preferences = '[[+region=local]]',constraints = '{"+region=local": 3, "+region=node3region": 2}', num_replicas=5;
CONFIGURE ZONE 1
operator@:26257/defaultdb> SHOW RANGES from database defaultdb;
ERROR: only users with the admin role are allowed to read crdb_internal.ranges_no_leases
`

gz#9363

**Comment by rafiss** [comment]
@commatter Would it be acceptable if we used the existing `ZONECONFIG` privilege to determine if a user is allowed to run `SHOW RANGES`?

**Comment by rafiss** [comment]
Actually, could you explain a bit more about why `SHOW RANGES` is needed here, and why a non-admin would need it? Why is `SHOW ZONE CONFIGURATION` (https://www.cockroachlabs.com/docs/stable/show-zone-configurations.html) not acceptable?

cc @vy-ton @awoods187 for awareness -- this seems like it might be closer to new feature territory.

**Comment by commatter** [comment]
Hi @rafiss, I will answer both questions.

1. Would it be acceptable if we used the existing ZONECONFIG privilege to determine if a user is allowed to run SHOW RANGES?
A: Yes, I don't see a situation where you would want to administer zone config and not be able to see the results. 

2. Could you explain a bit more about why SHOW RANGES is needed here, and why a non-admin would need it? Why is SHOW ZONE CONFIGURATION (https://www.cockroachlabs.com/docs/stable/show-zone-configurations.html) not acceptable?
A:  If users require the ability to determine where data is stored via ZONECONFIG, does it not make sense that they should be able to verify their changes? 'SHOW RANGES' would allow them to do this. Is there an alternative way to verify the location of ranges/leaseholders? Additionally we have a multi-tenant environment where it is not feasible to give every power user admin and there is a hard requirement to not give users admin.

**Comment by vy-ton** [comment]
@kevin-v-ngo @thtruo Since you're both looking into range observability, curious if this is something you've considered?
