### ISSUE TITLE
ui: unexpected increase of transaction count in transaction page 

### ISSUE THREAD

**Issue by Azhng** [cockroachdb/cockroach#68375]
if you have a transaction with a non-1 execution count, and then re-sort the page by execution count, the execution count goes up.

![image](https://user-images.githubusercontent.com/9267198/128038768-b92d1dbe-9e07-4904-a45a-7a14ff71de1b.png)

![image](https://user-images.githubusercontent.com/9267198/128038799-cdb48f24-c813-4b94-a4a1-26f8bb50dec9.png)

The execution count goes down after page refresh. 

Jira issue: CRDB-9009

**Comment by jordanlewis** [comment]
Repro:

```
BEGIN;
SELECT 1;
SELECT 1;
SELECT 2;
COMMIT;
```

**Comment by jocrl** [comment]
@Azhng, would you mind checking if you can still repro this? I can't seem to repro this in DB Console or CC Console (dedicated or serverless), for statements or transactions.
I ran:
```
./cockroach demo --no-example-database --log-dir logs --insecure --multitenant=false
# then the stuff from Jordan's comment
```
In the video below I ran into a different bug on CC Console, so no demo for that irreproducibility but I'll file an issue for the bug 😛

https://user-images.githubusercontent.com/91907326/159286422-5515c4f4-35d2-4656-9194-2f5b40e49df0.mov

**Comment by Azhng** [comment]
iirc this bug had a lot of randomness in it, so the reprod approach Jordan initially discovered doesn't always reliably reproduce this bug. I'll do some digging there to see if i can find something.
