### ISSUE TITLE
ci: split 'Cockroach > Unit Tests > lint` into multiple build configurations

### ISSUE THREAD

**Issue by jlinder** [cockroachdb/cockroach#68382]
Run times take from 30-50 minutes. Lint takes 17-20 minutes. Ensure generated code is up-to-date takes 12-19 minutes. Test web UI takes 1-4 minutes. The other steps are normally < 2 minutes.

Moved ensure generated code and test web UI to their own build configurations.

Sourced from [this issue](https://github.com/cockroachdb/dev-inf/issues/67#issuecomment-614180060).

**Comment by rickystewart** [comment]
Closed by #68438
