### ISSUE TITLE
sql: add a "cluster setting" db console page/sql cli table

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#68393]
We have a number of important cluster settings that impact how developers and operators use CRDB. It's not easy to discover the current values of these cluster settings (or how they differ from the default). We should add a new cluster setting db console page. Initially, it can be a table of the cluster settings, a column with their current values, and a column hardcoded with the default values (and maybe some visual way to quickly see how they differ). It would also be nice if this was available via the SQL CLI as a table that can be queried. 

This can then be enhanced to make them editable with a selection field that could eventually write new values for these settings to the cluster. We can make this permission-based as well (everyone can observe the settings and only admins can change them).

In a related note, we can also enhance the current sessions page to show any altered session variables/items that differ from the cluster settings.

Jira issue: CRDB-9022

**Comment by awoods187** [comment]
@kevin-v-ngo and @jordanlewis  what do you think?

**Comment by awoods187** [comment]
It looks like we have this in advanced debug but i think we should consider moving it forward: http://127.0.0.1:8080/#/reports/settings

<img width="1321" alt="Screen Shot 2021-08-03 at 3 49 10 PM" src="https://user-images.githubusercontent.com/22278911/128077004-f93d21f9-c4de-44a4-8b22-cbb68071da74.png">

**Comment by awoods187** [comment]
We could also separate this into those values we deem most important/most likely to be configured and then below the fold show the remaining. Or we could show just those values that aren't the default above the fold too

**Comment by kevin-v-ngo** [comment]
Ideally devs don't need to configure these settings but I know that isn't the case today. I like surfacing the values that we deem most important that we know are configured most frequently, especially for SQL or the values that _have_ been changed (non-default) for a cluster. 

We can even contextualize some of these settings throughout the console experience.

CC'ing @Annebirzin in case there's quick win here we can do
