### ISSUE TITLE
sql: add new builtins to save and restore a session

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#68464]
To allow SQL pods to scale down and back up, without user impact, we should add two new builtins:
1. one that “saves” (or “pickles”) the session state
2. and another that “restores” (or “unpickles”) the session state.
 
This state can just be returned directly to the caller (in this case `sqlproxy`) in some encoded form. `sqlproxy` is in charge of managing this encoded state.

The initial implementation of these builtins only needs to include the values of all session variables in the state.

Behavior:
- Sessions will not be suspended when there is an open transaction. Therefore, the "save" builtin should return an error if it's called in the middle of a transaction.
- Consider that these builtins will be running inside of the user's session. We could add something to make sure the user matches user in the saved session state, but I don't think that's necessary. (Essentially, this first version of the command is a shortcut for `SHOW`ing each session var, and then `SET`ing them all later.)

Out of scope for this issue:
- Including prepared statements in the session state. (We possibly may not even need this ever, since I believe drivers auto re-prepare statements, but more investigation needed.)
- Temporary tables

Epic CRDB-1464

**Comment by otan** [comment]
Rudimentary research:
* how do we feel about sequences:
https://github.com/cockroachdb/cockroach/blob/d33af93e74dab165cd4e82a7a25435676a124180/pkg/sql/sessiondata/session_data.go#L45-L47
* I'm guessing we copy "LocalOnlySessionData": https://github.com/cockroachdb/cockroach/blob/d33af93e74dab165cd4e82a7a25435676a124180/pkg/sql/sessiondata/session_data.go#L130, in which case we'll need to protobuf all of that.

**Comment by otan** [comment]
ah, sequences are already serialisable.

**Comment by otan** [comment]
What guarantees do we have about migrating settings between different version of CockroachDB?

**Comment by otan** [comment]
ah wait, there's this thing for sequences:

https://github.com/cockroachdb/cockroach/blob/50ef2fc205baa65c5a740c2d614fe1de279367e9/pkg/sql/sessiondata/session_data.go#L268-L270
