### ISSUE TITLE
changefeedccl: add custom headers to HTTP request for webhook sink

### ISSUE THREAD

**Issue by spiffyy99** [cockroachdb/cockroach#68478]
Should provide means for user to provide headers for HTTP requests sent by the webhook sink (currently all headers are preset, except for `Authorization` which is set by option )

Remaining questions:

- What will this look like? (option, query param, JSON, etc?) and how do we do this without syntax being too cumbersome
- Which headers do we not want the user to set?
- What are the defaults

Epic CRDB-7748

Jira issue: CRDB-9051

**Comment by amruss** [comment]
There are several UX concerns: base-64 encoding, etc

CC may be injecting headers / stripping them out - we should check in with them on the security concerns
