### ISSUE TITLE
SQL Observability feature Request: Cluster Drop down view to include locality choice 

### ISSUE THREAD

**Issue by drewdeally** [cockroachdb/cockroach#68480]
**Is your feature request related to a problem? Please describe.**
For Multi-region Cluster, a dropdown for a grouping of nodes would improve monitoring for time series charts

![image](https://user-images.githubusercontent.com/39496073/128382851-938c71be-7bc3-46e1-9a9a-376b4b7cecc4.png)

**Describe the solution you'd like**
ability to focus on at lease a group of nodes in a locality

**Describe alternatives you've considered**
none exist 

Jira issue: CRDB-9053

**Comment by kevin-v-ngo** [comment]
Hi @drewdeally, to confirm this issues is tracking both region information the dropdown and multi-select correct?

**Comment by drewdeally** [comment]
yes.
