### ISSUE TITLE
Webhook sink - can't specify format 

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#68482]
When creating a changefeed to the webhook sink, I would expect an error stating that avro format is not supported, when doing it, I get the error: "ERROR: invalid option "resolvedformat""
This is not very clear - we should instead say something like "ERROR: Avro not supported"

Also when specifying json format, we get the same error. Even though we only allow json right now, this should still work. 
CREATE CHANGEFEED FOR TABLE movr.vehicles INTO 'webhook-https://<redacted>:3000?insecure_tls_skip_verify=true' WITH updated, resolvedformat=json;

ERROR: invalid option "resolvedformat"

**Comment by spiffyyeng** [comment]
Solution was to add comma between resolved and format: `CREATE CHANGEFEED FOR TABLE movr.vehicles INTO 'webhook-https://:3000?insecure_tls_skip_verify=true' WITH updated, resolved, format=json;`. Proper error message appears here if invalid format is used.
