### ISSUE TITLE
sql: fix UPDATE SET (x,y) = (subquery...) 

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#6852]
Regression introduced by #6735:

```
root@:26257> CREATE TABLE xyz (x INT PRIMARY KEY, y INT, z INT)
root@:26257> UPDATE xyz SET (y,z)= (SELECT 11,12) ;
pq: cannot use this expression to assign multiple columns: (SELECT 11, 12)
```

This is because the sub-query is now expanded during query execution (Start/Next), whereas updateNode would like to split the assignments as soon as it gets initialized.

**Comment by cuongdo** [comment]
From a chat with @knz:

> The general idea is to create an array of "value slots" and then separately two data structures, one that determines which slots get assigned by each expression evaluation and which slots are used as the source of the update for each target column.
>
> The update node would carry those things
