### ISSUE TITLE
Provide a metric to indicate the number of 'active' or 'running' statements over time

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#68530]
Today we have time-series metrics to indicate the count of statements that started and successfully completed over time. 

We should have a metric to indicate the number of active/running statements over time so that developers can quickly pinpoint times of high or low activity. 

Jira issue: CRDB-9070

**Comment by jordanlewis** [comment]
We actually have this already - it's called `sql.statements.active`! Sorry I didn't notice this earlier.
