### ISSUE TITLE
sql: hash-sharded indexes with dynamic buckets

### ISSUE THREAD

**Issue by michae2** [cockroachdb/cockroach#68562]
When a hash-sharded index is created today, it includes the bucket_count in the hash expression:

```
SET experimental_enable_hash_sharded_indexes = true;
CREATE TABLE foo (f INT, INDEX (f) USING HASH WITH BUCKET_COUNT = 42);

demo@127.0.0.1:26257/defaultdb> SHOW CREATE TABLE foo;
  table_name |                                                          create_statement
-------------+--------------------------------------------------------------------------------------------------------------------------------------
  foo        | CREATE TABLE public.foo (
             |     f INT8 NULL,
             |     crdb_internal_f_shard_42 INT4 NOT VISIBLE NOT NULL AS (mod(fnv32(COALESCE(CAST(f AS STRING), '':::STRING)), 42:::INT8)) STORED,
             |     rowid INT8 NOT VISIBLE NOT NULL DEFAULT unique_rowid(),
             |     CONSTRAINT "primary" PRIMARY KEY (rowid ASC),
             |     INDEX foo_f_idx (f ASC) USING HASH WITH BUCKET_COUNT = 42,
             |     FAMILY "primary" (f, crdb_internal_f_shard_42, rowid)
             | )
(1 row)
```

There are some problems with including the bucket count (N) in the expression:
1. It constrains parallelism / distribution of the hot part of the index to at most N partitions. If the hot part of the index grows over time, N should be able to grow with it.
2. It constrains the N partitions to cover equal amounts of the hash space. If the hash space is lumpy (due to low-cardinality keys, for example) the distribution of keys in the hash space might not be uniform.
3. It forces users to come up with an N.
4. If the user ever wants to change N, they need to do an `ALTER` which will cause all keys in the index to change.

It would be nice if Instead of `WITH BUCKET_COUNT = N` and the `mod` in the expression, we could simply use the hash value directly. The KV layer could split / merge the ranges for this index as it normally does, in response to range size and load. (This is basically a form of [consistent hashing](https://en.wikipedia.org/wiki/Consistent_hashing) as used in Dynamo etc.)

**EDIT:** but as @ajwerner pointed out below, simply removing the `mod` from the expression breaks range scan support. It seems that dynamic buckets and range scan support are mutually exclusive, barring some fundamental changes to the design of KV ranges.

**Comment by ajwerner** [comment]
There's a use case for what you're saying, however, in that case, I wouldn't use hash sharded indexes.

If you just index a hashed column, then you do get a uniform distribution of writes. The downside, is that it does not allow you to perform scans on the index column -- in which case, it's not providing nearly as much leverage. Consider timestamps, if you always prefix a timestamp index with a uniform, int64 hash, you cannot use that index to discover timestamps in a range which defeats the purpose of the index. 

Consider the following table which might have events and we want to find the events in a time interval. This query gets a nice plan where it scans 8 tight spans rather than the whole table while still being able to scatter the write load to 8 different ranges.

```
demo@127.0.0.1:62011/movr> CREATE TABLE t (id INT64 PRIMARY KEY, ts TIMESTAMP , INDEX (ts) USING HASH WITH BUCKET_COUNT = 8);
CREATE TABLE

demo@127.0.0.1:62011/movr> EXPLAIN SELECT * FROM t WHERE ts < now() - '1s'::interval and ts > now() - '1m'::interval;
                                                                                                                                               info
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • scan
    missing stats
    table: t@t_ts_idx
    spans: [/0/'2021-08-06 22:01:37.63483' - /0/'2021-08-06 22:02:36.634828'] [/1/'2021-08-06 22:01:37.63483' - /1/'2021-08-06 22:02:36.634828'] [/2/'2021-08-06 22:01:37.63483' - /2/'2021-08-06 22:02:36.634828'] [/3/'2021-08-06 22:01:37.63483' - /3/'2021-08-06 22:02:36.634828'] … (4 more)
```

**Comment by ajwerner** [comment]
Given the above, are you willing to rework this issue to instead be about the functionality you want for the user story you want as opposed to getting rid of the functionality we have?

**Comment by michae2** [comment]
Great point, I did not think about the fact that this would break range scans! 😢 Hmm, let me think about this.

**Comment by michae2** [comment]
@ajwerner pointed me at https://github.com/cockroachdb/cockroach/issues/39340 to learn more about the work done to make current hash-sharded indexes have good plans for various access patterns. We then talked a bit, and it seems like it would be impossible to support **both** dynamic buckets *and* range scans (sql meaning of "range") unless ordering *within* a range (kv meaning of "range") could use a different key (or a suffix) than the key used to define range boundaries, and this goes against the design of Cockroach. He suggested that maybe [non-contiguous ranges](https://github.com/cockroachdb/cockroach/issues/65726) could be used somehow to accomplish this, but it seems unlikely.

I'll close this. Hopefully it will be a good reference if others have the same fantasy. 😄

**Comment by michae2** [comment]
Recent thought: if the KV layer could use hashes for assignment of a row to a range, while internally storing rows in order instead of in hash order, that would allow for the consistent hashing architecture described in "Dynamo: Amazon’s Highly Available Key-value Store" while still supporting efficient range scans.

But that brings up other questions, like how would the KV layer know to use hashes for one part of the key space? And it seems like this knowledge would have to be plumbed through both KV and SQL.

**Comment by michae2** [comment]
> But that brings up other questions, like how would the KV layer know to use hashes for one part of the key space? And it seems like this knowledge would have to be plumbed through both KV and SQL.

Maybe this could be done using zone configs.
