### ISSUE TITLE
sql: monotonic id’s + recency bias leads to hot node

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/cockroach#68560]
There is a workload pattern, especially when migrating from Postgres, that can lead to hot nodes. This is a high-level tracking issue/problem statement.

When an id (typically a primary or foreign key) is a monotonically generated integer, new ranges will naturally be together. This is not such a big deal, unless the workload is such that recent keys are the hot ones. Then, “active” and “adjacent” become synonymous, and focus disproportionate work on a single node.

As an example, imagine an employee starts a task, and a task_id is created. Tasks are created with decent frequency, say several per minute. Over time, tasks are completed, at a similar rate.

The newer tasks are being actively worked, therefore their ranges are queried a lot. Older tasks have been completed, therefore their ranges are rarely queried.

(The best practice is for id’s to be random/UUID, but imagine that is not possible for an existing workload.)

What can CRDB do to mitigate under these circumstances? Ideas that have been mentioned:

- One idea is a column property to instruct CRDB to store a column as if it were a hash. Essentially, a mapping from integer id → UUID under the hood.
- Hash-shared indexes are in this direction, but bucket count must be manually determined.
- Actively redistribute leases on range split

A further potential issue is that this pattern can lead to stale statistics. Because hot == new, the hot ranges will be under-represented in statistics. See also https://github.com/cockroachdb/cockroach/issues/68556.

Epic CRDB-7363

**Comment by mgartner** [comment]
This is also related to #41058.

**Comment by michae2** [comment]
I didn't realize hash-sharded indexes *require* a bucket count up front. This seems like a mistake. We should rely on normal range splitting mechanics to naturally determine the "bucket count" in a hash-sharded index.

**Comment by ajwerner** [comment]
Is this worthy of an issue? Consider the docs https://www.cockroachlabs.com/docs/stable/serial.html and https://www.cockroachlabs.com/blog/how-to-choose-db-index-keys/. While people continue to cut themselves on this, this is a "well understood" sort of design point of cockroachdb. 

I'll reply on the hash-sharded index front but I think it's sort of missing the point. The big thing about the hash sharding is the `CHECK` constraint and the fact that it's useful for accerlating queries based on the order of the column. If you just want a uniformly random primary index, what I think we want is just:

```
> CREATE TABLE t (i INT, hashed INT AS (fnv64(i)) VIRTUAL NOT VISIBLE, PRIMARY KEY (hashed, i));
ERROR: relation "t" (59): primary index column "hashed" cannot be virtual
```

This relies on supporting virtual computed columns on primary keys, which is loosely planned work to make hash-sharded indexes better. 

What I want to push back on is the idea that the design of hash sharded indexes is wrong. It's just not what you're looking for.

**Comment by shermanCRL** [comment]
See also https://github.com/cockroachdb/cockroach/issues/61883

**Comment by ajwerner** [comment]
I'll add that above I used virtual more as a nice to have. It works today with `STORED`.

```
CREATE TABLE

Time: 5ms total (execution 4ms / network 0ms)

demo@127.0.0.1:62011/movr> INSERT INTO t VALUES (1), (2);
INSERT 2

Time: 6ms total (execution 6ms / network 0ms)

demo@127.0.0.1:62011/movr> SELECT * FROM t;
  i
-----
  2
  1
(2 rows)

Time: 1ms total (execution 1ms / network 0ms)

demo@127.0.0.1:62011/movr> EXPLAIN SELECT * FROM t WHERE i = 1;
                              info
----------------------------------------------------------------
  distribution: local
  vectorized: true

  • scan
    missing stats
    table: t@primary
    spans: [/-5808590958014384146/1 - /-5808590958014384146/1]
(7 rows)

```

Regarding the default expression, I have a PR I'll finish next week to add a new builtin which converts datums to bytes immutably for hashing as opposed to casts. https://github.com/cockroachdb/cockroach/pull/67865

**Comment by mgartner** [comment]
> What I want to push back on is the idea that the design of hash sharded indexes is wrong. It's just not what you're looking for.

I don't think anyone is implying that the design of hash sharded indexes is wrong. I think a hash sharded index is exactly what this issue is looking for.

There was another recent usability issue from a customer: For range queries the optimizer resorts to a full table scan too often rather than scanning a range for each bucket.

**Comment by michae2** [comment]
@shermanCRL is there an outcome you're expecting from this issue?

@vy-ton would you be willing to "digest" this into improvements to hash-sharded indexes?

**Comment by ajwerner** [comment]
> There was another recent usability issue from a customer: For range queries the optimizer resorts to a full table scan too often rather than scanning a range for each bucket in the hash sharded index.

Is there an issue for this one? It'd be good to associate it with [CRDB-7363](https://cockroachlabs.atlassian.net/browse/CRDB-7363).

**Comment by shermanCRL** [comment]
@michae2 This was intended as a high-level problem statement, and the answer might come from several different directions -- possibly hot node rebalancing, possibly stats/planning tweaks (or perhaps just making a better query/index choice).

The proximate outcome I am hoping for is that this workload at a client behaves well -- right now, there is manual intervention to move leases off of hot nodes under load.

**Comment by mgartner** [comment]
> Is there an issue for this one? It'd be good to associate it with CRDB-7363.

No, not yet. It was an anecdotal comment made by a customer, not something that I've seen a reproduction of.

**Comment by ajwerner** [comment]
See also https://github.com/cockroachdb/cockroach/pull/54675 which is like `unique_rowid()` but unordered. That might help here.

**Comment by ajwerner** [comment]
My preference is that we close this issue and replace it with things which are actionable:

* Providing better user stories from migrations from postgres which use 64bit integer keys and have heavy write volumes.  #54675.
* Providing better tools to detect and warn about tables which might have these hot spots. @awoods187 has long talked about tools to look at schema and report potential issues. If we noticed the use of `unique_rowid()` or a sequence as a default value for a primary key prefix or for an index prefix, we could warn about it somehow.

**Comment by vy-ton** [comment]
> @vy-ton would you be willing to "digest" this into improvements to hash-sharded indexes?

+1, this will surface in the upcoming problems to solve as something like "design schema to solve for contention". Once we start discussing solutions, we will reference Andrew's suggestions above

**Comment by ajwerner** [comment]
>"design schema to solve for contention". 

I highly encourage you to find a new word other than "contention" to talk about this problem. Contention is most commonly understood within cockroach to mean lock contention or interaction between operations hitting overlapping sets of keys. This is resource contention due to inability to load balance. Other terms we can use here are: "load balancing", "resource utilization", "hot spot avoidance"?

**Comment by shermanCRL** [comment]
Closing, since this is a high-level problem statement. Leaving to @vy-ton and @ajwerner to take action on specific issues.
