### ISSUE TITLE
ts.Server: convert to grpc

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#6858]
This is one of the last non-grpc handlers in the codebase - we should use grpc here as we do elsewhere.

Should be straightforward, good starter task.

**Comment by uname-yang** [comment]
I want to join the project.Maybe it is good enter for me .Can we talk more about it ? @tamird

**Comment by andreimatei** [comment]
@uname-yang see if other issues with the "helpwanted" label pique your interest.
