### ISSUE TITLE
Analyze Table operations that take longer than table TTL fail.

### ISSUE THREAD

**Issue by bladefist** [cockroachdb/cockroach#68590]
Ran analyze table on a large table with a 900 second TTL.

Error in the jobs:

batch timestamp 1628283892.315459871,0 must be after replica GC threshold 1628283892.326056946,0

CockroachDB 21.1.6

Continued discussion from #64570

**Comment by mgartner** [comment]
We should automatically throttle and use `AS OF SYSTEM TIME` wiht `ANALYZE` like we do with automatic `CREATE STATISTICS` statements. This should fix the issue.
