### ISSUE TITLE
Memory error on large Analyze Table query

### ISSUE THREAD

**Issue by bladefist** [cockroachdb/cockroach#68591]
**Describe the problem**

Trying to update the statistics on a large table.

**To Reproduce**

Ran `analyze largetable;`

**Expected behavior**
Job to complete and update the stats.

Error from jobs page:

`flow: memory budget exceeded: 10240 bytes requested, 0 currently allocated, 0 bytes in budget`

Tried running this a couple times, just can't get it to succeed.  Automatic stats creation can get it done, so I am going to try to adjust those settings to get the statistics to update more often.

CockroachDB 21.1.6

**Comment by yuzefovich** [comment]
We have actually identified the bug and are tracking the issue in #68670. That issue also mentions the workaround until the bug is fixed.
