### ISSUE TITLE
Multiple resumers can run concurrently in the same job registry

### ISSUE THREAD

**Issue by sajjadrizvi** [cockroachdb/cockroach#68593]
**The problem**

Each node runs a job registry that manages long-running jobs. A registry monitors 
system.jobs table and try to resume some jobs (start their execution) that are in runnable 
states (`running` and `reverting`). The registry keeps an internal state, `adoptedJobs` 
map, that keeps track of the currently executing resumers, where a resumer is a goroutine 
that executes a job. 

When a resumer starts, it registers its job in the internal state to prevent executing 
redundant resumers for the same job. When the job is paused,  the registry unregisters the 
job and cancels the context of the resumer so that the job can be paused. Consequently, 
while the resumer is canceling its execution, unpausing the job can cause the registry to 
start another resumer  concurrently for the same job, which should not happen. The resume 
can start because the internal state `adoptedJobs` was cleared in response to pause request.
In extreme cases, a specific sequence of events can cause multiple resumers to start concurrently.

**Expected behavior**
Only one resumer per job executes at a time in the same registry.

**How to fix it?**
`adoptedJobs` map acts like a lock. Therefore, a job should only be unregistered by the
resumer that registered the job. Currently a job can be unregistered in separate goroutines 
in response to job pause and cancel requests. For these requests, we should only cancel 
the context of the running resumer instead of unregistering the job.

**How can it happen?**
In some specific sequence of events, multiple resumers can begin performing the same job.
One such sequence of events is given below. In this table, time flows from top to bottom, and 
all events belong to the same job. Moreover, the resumers belong to the same job. `Adopt loop`
monitors system.jobs table and start resumers. `Cancel loop` unregisters a job when the job
is paused or canceled. Resumer-3 and Resumer-4 start concurrently, which should not happen.

```
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|    Job    |    Adopt   |  Cancel  |    Can   |  Resumer  |  Resumer  |  Resumer  |  Resumer   |
|   status  |    loop    |   loop   | start a  |     1     |     2     |     3     |      4     |
|  in Table |            |          | resumer? |           |           |           |            |
+===========+============+==========+==========+===========+===========+===========+============+
|  running  |            |          |          |           |           |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|           |    Claim   |          |    Yes   |           |           |           |            |
|           |    job     |          |          |           |           |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|           |    Mark    |          |          |           |           |           |            |
|           |     job    |          |          |           |           |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|           |            |          |    No    |           |           |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|           |   Resume   |          |          |           |           |           |            |
|           |     job    |          |          |           |           |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|           |            |          |          | Start job |           |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|   pause-  |            |          |          |           |           |           |            |
| requested |            |          |          |           |           |           |            |
|  (due to  |            |          |          |           |           |           |            |
|  a pause  |            |          |          |           |           |           |            |
|  request) |            |          |          |           |           |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|           |            |   Pick   |          |           |           |           |            |
|           |            |    job   |          |           |           |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|           |            |  Unmark  |          |           |           |           |            |
|           |            | job and  |          |           |           |           |            |
|           |            |  start   |          |           |           |           |            |
|           |            |  it to   |          |           |           |           |            |
|           |            |  cancel  |          |           |           |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|           |            |          |    Yes   |           |           |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|   paused  |            |          |          |           |           |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|           |            |          |          |   Start   |           |           |            |
|           |            |          |          | canceling |           |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|  running  |            |          |          |           |           |           |            |
|  (due to  |            |          |          |           |           |           |            |
|  unpause) |            |          |          |           |           |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|           |  Claim job |          |          |           |           |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|           |  Mark job  |          |          |           |           |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|           |            |          |    No    |           |           |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|           | Resume job |          |          |           |           |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|           |            |          |          |           | Start job |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|           |            |          |          |   Unmark  |           |           |            |
|           |            |          |          |    job    |           |           |            |
|           |            |          |          |    and    |           |           |            |
|           |            |          |          |   cancel  |           |           |            |
|           |            |          |          |   others  |           |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|           |            |          |          |           |   Start   |           |            |
|           |            |          |          |           | canceling |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|           |            |          |    Yes   |           |           |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|           |            |          |          |  Finished |           |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|           |  Claim job |          |          |           |           |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|           |  Mark job  |          |          |           |           |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|           |            |          |    No    |           |           |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|           |            |          |          |           |   Unmark  |           |            |
|           |            |          |          |           |  job and  |           |            |
|           |            |          |          |           |  cancel   |           |            |
|           |            |          |          |           |   others  |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|           |            |          |    Yes   |           |           |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|           | Resume job |          |          |           |           |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|           |            |          |          |           |           |*Start job*|            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|           |  Claim job |          |          |           |           |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|           |  Mark job  |          |          |           |           |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|           |            |          |    No    |           |           |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|           | Resume job |          |          |           |           |           |            |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
|           |            |          |          |           |           |           |*Start job* |
+-----------+------------+----------+----------+-----------+-----------+-----------+------------+
```

**Comment by ajwerner** [comment]
Are you saying that you can have two resumers executing concurrently each with an uncanceled context and valid session? Otherwise, it's expected.

**Comment by ajwerner** [comment]
Given the fact that we may always have concurrent executions of jobs, the question I have to ask is, is it possible for these concurrent executions to concurrently write to the table to update the state for that job? If not, then I'm not sure that this is a bug.

**Comment by ajwerner** [comment]
My primary feedback on this issue is that it's hard to understand the impact. The expected behavior is fine and a reasonable thing to want, but it's not clear what problems it causes. I know we've talked about this bad synchronization before. 

The problem with this issue is that it's very detailed in one sense, but it's also not easy to digest. It'd be better if it included perma-links to code so that a reader might be able to digest it a bit better. 

So: In summary, please report what happens if we don't fix this so that a reader might be able to prioritize it. You've got it labeled as `C-bug` but I'm not yet convinced that it is. It sort of seems like an enhancement.

**Comment by sajjadrizvi** [comment]
> Are you saying that you can have two resumers executing concurrently each with an uncanceled context and valid session? Otherwise, it's expected.

I think so, but in a very specific timing and sequence of events, which I don't expect to happen in commonly.

**Comment by sajjadrizvi** [comment]
> My primary feedback on this issue is that it's hard to understand the impact. The expected behavior is fine and a reasonable thing to want, but it's not clear what problems it causes.

I agree, I don't know its impact. This is a very specific case that require many odd things to happen at the same time.
The bad synchronization we discussed before can happen in another case too, but we fixed that case by changing the query.

**Comment by sajjadrizvi** [comment]
> I know we've talked about this bad synchronization before.

The bad synchronization we discussed before can happen in another case too, but we fixed that case by changing the query.

**Comment by ajwerner** [comment]
> I think so, but in a very specific timing and sequence of events, which I don't expect to happen in commonly.

That's the worst of both worlds. I don't see in your example how that happens. Maybe I'm missing something. Didn't you say above that we'd have canceled the context if we removed it from the map?

**Comment by sajjadrizvi** [comment]
> So: In summary, please report what happens if we don't fix this so that a reader might be able to prioritize it. You've got it labeled as `C-bug` but I'm not yet convinced that it is. It sort of seems like an enhancement.

The bot added the label. I have now changed it.

**Comment by ajwerner** [comment]
>>Are you saying that you can have two resumers executing concurrently each with an uncanceled context and valid session? Otherwise, it's expected.
>
>I think so, but in a very specific timing and sequence of events, which I don't expect to happen in commonly.

I need to understand whether this is possible. If it is, this is a meaningful and problematic bug. If not, then I don't know that it's a bug at all. Please confirm one way or another and if you don't know, let me know why you think it is possible with some code pointers.

**Comment by sajjadrizvi** [comment]
> > I think so, but in a very specific timing and sequence of events, which I don't expect to happen in commonly.
> 
> Didn't you say above that we'd have canceled the context if we removed it from the map?

Do all resumers share the same context, implying canceling one's context cancels for all? If that is the case, then there is no problem.

If not, let me restate the sequence of events in the next comment. I apologize for not being clear and a little slow in writing.

**Comment by ajwerner** [comment]
> If not, let me restate the sequence of events in the next comment. 

It's all good. I think I do see now that there is a problem. We need to make sure that the following line does not remove a newly added registration. I think we should do some pointer equality checking when unregistering. Here we might be essentially unlocking a lock we don't hold. 

https://github.com/cockroachdb/cockroach/blob/ea1ff1e85f05d30d2ecc6a349c5f01ae8475bae3/pkg/jobs/adopt.go#L286-L287

**Comment by sajjadrizvi** [comment]
I think we should unregister only from the same goroutine that registered the job. So we should add a `cancelResumer` function that only cancels a running resumer instead of also [removing `jobID` from `adoptedJobs`.](https://github.com/cockroachdb/cockroach/blob/ea1ff1e85f05d30d2ecc6a349c5f01ae8475bae3/pkg/jobs/registry.go#L1338) Each resumer eventually calls [`unregister`](https://github.com/cockroachdb/cockroach/blob/ea1ff1e85f05d30d2ecc6a349c5f01ae8475bae3/pkg/jobs/adopt.go#L286-L287). The problem will be fixed by just canceling the resumer in [`servcePauseAndCancelRequests`](https://github.com/cockroachdb/cockroach/blob/ea1ff1e85f05d30d2ecc6a349c5f01ae8475bae3/pkg/jobs/adopt.go#L375).

**Comment by ajwerner** [comment]
> The problem will be fixed by just canceling the resumer in servcePauseAndCancelRequests.

Nice. It'd be good to be able to demonstrate this scenario and then fix it.

**Comment by ajwerner** [comment]
Let's prioritize the exponential backoff and observability stuff over fixing this. Only prioritize this if it's in your way.

**Comment by sajjadrizvi** [comment]
yeah, let's do that. It is preventing some of my testcases to pass. But I have thought of a work around. I hope that will work.
