### ISSUE TITLE
pgwirebase.ReadBuffer.SlurpBytes might discard in some situations

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/cockroach#68592]
While investigating what looks like a buffer underrun in the `COPY` protocol, I came across the `SlurpBytes` function.  What happens if the `for sizeRemaining` loop triggers more than once if `b.maxMessageSize` is smaller than the requested read size?  Wouldn't the multiple calls to `b.reset()` discard the preceding chunks of data that had been read?

**Comment by otan** [comment]
can you summarise your concern pointing at code or through an example? i don't follow the concern.
the idea is to discard everything because we can't fit into buffer. we are actively discarding preceding chunks of data.

**Comment by otan** [comment]
reading the issue title, i think we are doing what we intend to do: if the message is too big, discard the entirety of the message. this is only in the case where pgwire sends a size that does not fit on the buffer.
