### ISSUE TITLE
The 'Clear SQL Stats' reset button is not working (clickable) in the CC console

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#68604]
The Clear SQL Stats button on the new Transactions and Statements pages in the CC console is not working.

![image](https://user-images.githubusercontent.com/81193618/128751948-1d72ed60-3519-446a-abd3-8d0f9ceca435.png)

**Comment by maryliag** [comment]
From the console on the browser I can see:
```fetchProxy.js:53 GET http://localhost:7900/db-console/535efb35-3a99-4601-b298-55a52323ad73/us-central1/0/_status/resetsqlstats 405 (Method Not Allowed)```

**Comment by Azhng** [comment]
What's the version of the Console and the Cluster?

**Comment by maryliag** [comment]
21.1.5

**Comment by Azhng** [comment]
Turns out that this is because the CC Proxy is not properly proxying the HTTP verb. `/_status/resetsqlstats` requires `POST` verbs however the CC Console is issuing the `GET` request which is dropped by the CRDB's gRPC gateway.

**Comment by maryliag** [comment]
Reopen so it can be backported
