### ISSUE TITLE
ui: metric `intentcount` does not show values for individual nodes

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#68610]
**Describe the problem**

`intentcount` does not show values for individual nodes but it does display for the entire cluster

**To Reproduce**

Go to the custom charts page in DB Console and attempt to display `intentcount` for individual nodes. No values get displayed. 

Seen on 21.1.6

<img width="735" alt="Image 2021-08-09 at 12 53 02 PM" src="https://user-images.githubusercontent.com/1474303/128762234-e050726c-f9e1-42a9-9a43-10625d59da24.png">

**Comment by thtruo** [comment]
cc @mikeczabator for awareness
cc @nkodali another one for the group of Metrics UX smoothing we will take up after wrapping up Serverless

**Comment by zachlite** [comment]
@thtruo I wasn't able to reproduce this.

Attempted reproduction steps:
```
roachprod create local -n 3
roachprod stage local release v21.1.6
roachprod start local
cockroach workload init bank
cockroach workload run bank
```

![Screen Shot 2022-01-12 at 2 40 48 PM](https://user-images.githubusercontent.com/5423191/149210314-806d77be-4aad-4458-bc77-af08dd734492.png)
