### ISSUE TITLE
server: panic in HTTP handlers should not crash server

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#68638]
As seen in #68637 and the internal support issue that spawned it, a panic in an HTTP request handler can cause the entire node to crash. These panics are more often than not caused by benign errors in the HTML generation code, and the node should be tolerant to such errors by intercepting the panic, logging it, and returning a 500 response instead of crashing.

Epic CRDB-11087

**Comment by knz** [comment]
We can address this with:

- a gRPC interceptor for the legacy APIs, for example by renaming+extending `callCountInterceptor`
- a customization of the handler in `(a *apiV2Server) registerRoutes` for the APIv2 routes

@dhartunian do you think this is best handled by Obs infra or by server? (From my perspective it goes either way)
