### ISSUE TITLE
Enable SQL observability CRDB_INTERNAL tables and views for SQL Serverless

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#68632]
Not all SQL observability features are supported for Serverless as they require gathering data across all SQL pods that belong to a tenant. CC serverless customers should have access to the same SQL observability touchpoints as Self-hosted/Dedicated. This builds off the framework the server team has built to enable a fan-out server for SQL pods.

CRDB_INTERNAL tables and views:

cluster_contention_events

Epic: CC-4763

**Comment by kevin-v-ngo** [comment]
Per https://github.com/cockroachdb/cockroach/issues/68631, queries, transactions, and sessions are already returning cluster-wide data. contention_events is still retuning local events.

**Comment by Azhng** [comment]
Reopen for backport
