### ISSUE TITLE
Create an ARM build to support running Cockroach on an m1-powered Mac

### ISSUE THREAD

**Issue by jhatcher9999** [cockroachdb/cockroach#68648]
Running the cockroach executable from a Mac with an m1 chip runs very poorly.

I'd like to see an ARM build that would support better performance on M1 chips.

Epic DEVINF-247

Jira issue: CRDB-9140

**Comment by knz** [comment]
Possibly dup of #32689.

this is really for dev inf. cc @jlinder for triage.

**Comment by jlinder** [comment]
Let's keep these as separate. While on the surface they are both ARM64 architectures and much of the work we do for to improve support for one will directly help the other, they are for different OSes and are different custom chips so there are likely to be specific needs for each one. If we end up finding there is minimal difference, we can close one as duplicate then.

**Comment by rickystewart** [comment]
@jhatcher9999 Sorry, just clarifying: what is the actual feature request here? Is this asking for an official release for ARM Macs? If you just want a native Cockroach executable that will run on your own machine, you can build it yourself. The Bazel build works and supports M1 Macs.

If the request is for an official release, that's going to be a big investment. It'll probably happen at some point but I'm not sure it's planned for the next release.

**Comment by jhatcher9999** [comment]
Hey Ricky -- I work for Cockroach, and I'm just passing this on as feedback from various customers.  I have some customers who are wanting to run CRDB on their local m1-based MAC laptops so they want a build that is performant.  I also have some customers who are wanting to use CRDB in their CI/CD pipelines and they have had issues running those in docker-based containers.  And, a third case is folks that want to run their actual production CRDB clusters on EC2 instances and AWS is starting to push ARM-based servers.

So, I guess the feature request is to have a CRL-supported build that works well across those 3 scenarios.

**Comment by rickystewart** [comment]
OK. The third case is a dup of #32689 (macOS vs. Linux, and indeed the bugs should be kept separate per [James' comment](https://github.com/cockroachdb/cockroach/issues/68648#issuecomment-947220770)). As for the first case, you can work around by building your own `cockroach`, which I understand is less convenient than just downloading a pre-built binary, but will work.

The second case isn't addressed until we have a cross-build (official release) for M1 Macs, which I think is what this bug will track.

**Comment by jhatcher9999** [comment]
Ricky, do we have instructions for doing your own Cockroach build that I could follow and/or share?

**Comment by rickystewart** [comment]
General instructions: https://wiki.crdb.io/wiki/spaces/CRDB/pages/73204103/Building+from+source+on+macOS

Bazel-specific instructions: https://wiki.crdb.io/wiki/spaces/CRDB/pages/2221703221/Developing+with+Bazel

I recommend building w/ Bazel if you're building from `master`, but if you're building from an older release (21.2 or earlier) you probably want to stick to `make`.

**Comment by christoofar** [comment]
Here.  I made a version of v21.2.2 for ARM64

It should run on an M1 Mac.  

https://hub.docker.com/layers/christoofar/cockroachdb-arm64/21.2.2/images/sha256-f6d9acfffb1b1e3cb251b0c70ba1f629033612379d2adcd32a00111c1cb896a9?context=explore

I also made an all-in-one Dockerfile with all the superdeps, takes several hours to run on a Rock64 but it will yield the same bits:  https://github.com/christoofar/cockroachdb-arm64

**Comment by julius-welink** [comment]
I have a multiarch cockroachdb docker image based on @christoofar work

https://hub.docker.com/r/juliuszaromskis/cockroachdb
https://github.com/julius-welink/cockroachdb-arm64

**Comment by hand-crdb** [comment]
A customer reports in a Zendesk ticket (I can share details):

> Hi, we're currently in the process adding support for apple silicon to the local development environments, so as part of this we need a aarch64 build of crdb. CL does not currently provide binary distributions of darwin/aarch64.

**Comment by natm** [comment]
Any progress with this?

**Comment by Amphaal** [comment]
Rosetta often crashes unexpectedly while emulating the `linux/amd64` docker image. Any official build for the `linux/arm64/v8` blockchain would be greatly appreciated !

**Comment by rail** [comment]
https://github.com/cockroachdb/cockroach/pull/89201 will add MacOS ARM64 platform to the release builds. There will be some extra work in https://github.com/cockroachdb/cockroach/pull/89754 to get the binaries signed and published.
22.2.0-beta.4 is expected to have the new platform live.

**Comment by rail** [comment]
>  22.2.0-beta.4 is expected to have the new platform live.

Correction, beta 5 it is.

**Comment by Scalahansolo** [comment]
I see that beta 5 just got tagged. How would I ago about installed beta 5 for testing the MacOS ARM version?

**Comment by rail** [comment]
The URLs will be published shortly on the website 🕺

**Comment by Scalahansolo** [comment]
I see that the binary got added to https://www.cockroachlabs.com/docs/releases/index.html?filters=mac. But there is only a column for intel binaries? Does that binary install the correct version, or is there a different URL for ARM version?

**Comment by rail** [comment]
Waiting for https://github.com/cockroachdb/docs/pull/15281 to merge :)

**Comment by rail** [comment]
Let's call it done!
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/42865/199419302-83d3f996-be28-47ae-89c2-2cfbe31f49c5.png">

**Comment by kenliu-crl** [comment]
Link to download Apple M1/M2 build: https://www.cockroachlabs.com/docs/releases/index.html?filters=mac

**Comment by AndiDog** [comment]
The homebrew recipe still needs to be adapted: https://github.com/cockroachdb/homebrew-tap/blob/master/Formula/cockroach.rb

**Comment by jlinder** [comment]
Hi @AndiDog, our homebrew tap always points to the latest stable version, which is still a v22.1.X release. Once we release v22.2.0, it will include the ARM64 version. Here is the PR if you'd like to follow along: https://github.com/cockroachdb/homebrew-tap/pull/117.
