### ISSUE TITLE
bazel: cockroach-short binary linked to libncurses5 and libtinfo5

### ISSUE THREAD

**Issue by rail** [cockroachdb/cockroach#68644]
The current `cockroach-short` generated by bazel gives the following `ldd` info:

```
$ ldd cockroach-short
	linux-vdso.so.1 (0x00007ffee5dc6000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb76307b000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb762cdd000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fb762ad5000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb7628b6000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb7626b2000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fb762498000)
	libncurses.so.5 => /lib/x86_64-linux-gnu/libncurses.so.5 (0x00007fb762275000)
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007fb76204b000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb761e33000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb761a42000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb763404000)
```

The current `cockroach` binary gives me a mush shorter list of linked libraries:

```
$ docker run -ti --entrypoint /bin/bash  cockroachdb/cockroach:v21.1.7 ldd /cockroach/cockroach
	linux-vdso.so.1 (0x00007ffc1adf0000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f99c6718000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f99c64f8000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f99c62f4000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f99c60dd000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f99c5d5b000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f99c5996000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f99c6920000)
```

I found this when I tried to run the acceptance test against the bazel generated binary. The acceptance test [docker image](https://github.com/cockroachdb/cockroach/blob/f673e973334b6861440d5199b392b09da571a306/pkg/acceptance/cluster/dockercluster.go#L54) used to start the DB does not have those libraries installed, so it fails to start.

Epic CRDB-8351

**Comment by rickystewart** [comment]
How did you build `cockroach-short`?

**Comment by rail** [comment]
It was built using`./dev build cockroach-short` on a linux machine, no bazelbuild docker image involved.

Apparently the release binary is built using [these flags](https://github.com/cockroachdb/cockroach/blob/f673e973334b6861440d5199b392b09da571a306/build/builder/mkrelease.sh#L47) what probably statically links all those libraries.

See https://github.com/cockroachdb/cockroach/issues/68653

**Comment by rickystewart** [comment]
As we discussed offline, the proper comparison would be w/ `dev build --cross`. `dev build` in the absence of `--cross` doesn't produce a binary that is guaranteed to run anywhere except the machine you built it on. 

Closing this for now. If you uncover anything that looks wrong with a cross-compiled binary, go ahead and re-open this.
