### ISSUE TITLE
ui: statement details page fails to load for `CREATE TABLE` statement (fails to decode URL)

### ISSUE THREAD

**Issue by koorosh** [cockroachdb/cockroach#68651]
**Describe the problem**

Statement details page for `CREATE TABLE` statement is failed to load with following JS error:
```
Uncaught URIError: Pathname "/statement/tpcc/true/CREATE%20TABLE%20IF%20NOT%20EXISTS%20history%20(rowid%20UUID%20NOT%20NULL%20DEFAULT%20gen_random_uuid()%2C%20h_c_id%20INT8%20NOT%20NULL%2C%20h_c_d_id%20INT8%20NOT%20NULL%2C%20h_c_w_id%20INT8%20NOT%20NULL%2C%20h_d_id%20INT8%20NOT%20NULL%2C%20h_w_id%20INT8%20NOT%20NULL%2C%20h_date%20TIMESTAMP%2C%20h_amount%20DECIMAL(6%2C2)%2C%20h_data%20VARCHAR(24)%2C%20PRIMARY%20KEY%20(h_w_id%2C%20rowid)%2C%20crdb_region%20crdb_internal_region%20NOT%20NULL%20NOT%20VISIBLE%20AS%20(CASE%20h_w_id%20%%20_%20WHEN%20_%20THEN%20_%20WHEN%20_%20THEN%20_%20WHEN%20_%20THEN%20_%20WHEN%20_%20THEN%20_%20WHEN%20_%20THEN%20_%20WHEN%20_%20THEN%20_%20WHEN%20_%20THEN%20_%20WHEN%20_%20THEN%20_%20WHEN%20_%20THEN%20_%20WHEN%20_%20THEN%20_%20END)%20STORED)%20LOCALITY%20REGIONAL%20BY%20ROW" could not be decoded. This is likely caused by an invalid percent-encoding
```

**To Reproduce**
- Start demo cluster with command: `cockroach demo tpcc --nodes=10 --with-load`
- Navigate to `Statements` page and open `CREATE TABLE` statement in table
- Page fails to load (with error mentioned above)

**Environment:**
 - CockroachDB version v21.2.0

**Comment by koorosh** [comment]
cc @ajstorm

**Comment by xinhaoz** [comment]
Hmm, I couldn't reproduce this error with the steps, and any of the CREATE TABLE statements available in the demo. Is there any specific CREATE TABLE statement that caused the error mentioned or specific settings involved? @koorosh

**Comment by koorosh** [comment]
Couldn't reproduce as well on the latest build. Closing issue.
