### ISSUE TITLE
ui: DB Console Jobs page shows high-water timestamp as the status for a canceled job

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#68667]
**Describe the problem**

First identified by @katedoebler when accessing the Jobs page in DB Console. 

![Screen Shot 2021-08-10 at 3 11 50 PM](https://user-images.githubusercontent.com/1474303/128921608-b0a2fabc-37d3-4cfe-b0c6-c0cfdc933611.png)

- The 2nd row represents a canceled job, but the status displays `High-water Timestamp: Aug 10, 2021 at 2:40 PM`
- It should say `Canceled`

Seen on a 21.1.6 cluster

Jira issue: CRDB-9151

**Comment by thtruo** [comment]
Had a conversation with Abbey who described that the high-water timestamp measures changefeed progress. However, it wasn't entirely clear whether the desired UX is to display that timestamp in the status column for the Jobs table. 

And given @katedoebler's understanding that that job should be canceled, does it make sense to show the high-water timestamp or `CANCELED`?  

cc @amruss for awareness. Curious if you or your team have new thoughts on expected behavior (and housekeeping item: let me know if you think it's better for me to triage this to you and your team in the meantime)

**Comment by amruss** [comment]
Closing this
