### ISSUE TITLE
UI: brand new cluster still has "connection to cockroach node lost" banner.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6867]
sha: 45f7fd5

Just re-initialized `beta` cluster: https://beta.gce.cockroachdb.com:8080/

Even though all the nodes seem happy (both their individual UIs and sql interface), the UI is still showing the "connection to cockroach node lost" banner and the "health: can't reach node" message.

Any ideas?
![cant_connect](https://cloud.githubusercontent.com/assets/5901480/15508688/6fd73b1c-219e-11e6-9db0-b1187b8bfed7.png)

**Comment by mberhault** [comment]
FYI: chrome incognito and firefox (rarely used, so unlikely to have anything cached) behave similarly.

**Comment by cuongdo** [comment]
I've noticed similar behavior on my test cluster with no obvious red
(error) entries in my network inspector.

**Comment by mberhault** [comment]
yeah. this happens even with a local `cockroach start`.

**Comment by mrtracy** [comment]
I'm going to guess that this is due to recent protocol buffer encoding changes, the previous UI will need to be patched.

**Comment by vaibhavagarwal032** [comment]
how to reinitialize the nodes after shutting down the server

**Comment by dianasaur323** [comment]
@vaibhavagarwal032 are you asking how to bring nodes back after shutting down the server? do you mind clarifying your question a bit?

**Comment by vaibhavagarwal032** [comment]
I have started the three nodes in the cluster by mistake my laptop go to shut down then how these same nodes again? without removing the directories and start again writing all codes again

**Comment by dianasaur323** [comment]
@vaibhavagarwal032 if this is a local cluster run just on your laptop, and the data directories are still there, just run the same cockroach start commands you ran before the spin the nodes up again.
