### ISSUE TITLE
sql: more granularly handle log redaction for drop role

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#68728]
Currently the entire objects string here https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/drop_role.go#L255 is redacted in logs.

We should make it more granular in that it redacts the actual object name itself instead of redacting the entire objects string.

Jira issue: CRDB-9208

**Comment by rafiss** [comment]
I think the way to go is to make it a nested error instead of concatenating the errors together

**Comment by RichardJCai** [comment]
Gonna do this during stability.
