### ISSUE TITLE
Avoid paging SRE when cloud dedicated clusters are out of CPU, by skipping admission control queues when sending probes

### ISSUE THREAD

**Issue by joshimhoff** [cockroachdb/cockroach#68732]
**Is your feature request related to a problem? Please describe.**
Today, if a cloud dedicated cluster runs out of CPU, SRE is paged. This is not desirable as often the cause of being out of CPU is poor provisioning. The customer owns provisioning the cluster to be able to serve the workload they sent at it, not SRE. SRE should only receive alerts that are actionable, that is, that SRE can fix without involving the customer.

There are two main alerts that fire when a cluster is out of CPU:

1. `sqlprober` alerts fire. `sqlprober` is an **external** monitoring tool that holds a `*sql.DB` (https://pkg.go.dev/database/sql#DB) open to a CC cluster. It sends `SELECT 1`, it `SELECTs` a test row, and it `UPSERTs` a test row. Code is internal but I can show anyone if needed.
2. `kvprober` alerts fire. `kvprober` is a monitoring tool, today running within the CRDB process, that chooses random ranges to probe by scanning meta2 then probes them using the `kv.DB` interface. The code is here: https://github.com/cockroachdb/cockroach/tree/master/pkg/kv/kvprober.

These two tools attempt to measure availability. If a cluster is out of CPU, it isn't available today, as CRDB has no admission control system that keeps the cluster available. So these two tools fire alerts in case of a cluster that is out of CPU. This is again not desirable but makes sense when you consider how the tools work concretely plus the lack of admission control system built into CRDB today. 

**Describe the solution you'd like**
The idea is that `kvprober` and `sqlprober` should be able to send requests to CRDB that skip admission control queues, similarly to how node liveness heartbeats will skip the admission control queues. As these requests skip the queues, they should be handled fast enough that no alerts fire, even in case of an overloaded cluster.

I figure this is fairly straight forward to execute on for `kvprober`. 

OTOH I am less sure how it would work for `sqlprober`, as `sqlprober` is an **external** monitoring tool. Can `sqlprober` indicate to CRDB that requests from it should skip the queues, given that it is speaking plain SQL to CRDB? An alternative brought up by @bdarnell is to run the `sqlprober` with very very very loose timeouts, so that so long as the CRDB nodes *eventually* `SELECT` the test row, no alert fires. This might be the best way forward.

Question for @sumeerbhola: At what point (at what CRDB release) will we have an admission control system that will queues work so reliably that a cluster will never (or very rarely) get so overloaded that node liveness or the `kvprober` probes will stop going thru successfully?

**Describe alternatives you've considered**
1. Do nothing. **I don't think CC will scale if we do nothing.**
2. Inhibit `sqlprober` & `kvprober` alerts when a high CPU alert is firing. That is, in prometheus, say "if CPU usage is high, don't page SRE in case of `sqlprober` & `kvprober` alerts. **This is possible but likely won't work well.** It introduces a tight, hard to tune coupling between the peraremeters of the `sqlprober` & `kvprober` alerts and the high CPU alert. I doubt we will consistently inhibit pages via this strategy, and we may also introduce false negatives where a cluster is broken but no alert fires as the CPU is sort of high coincidentally (that is, the high-ish CPU doesn't actually cause the production problem).
3. Perhaps if we ran dedicated clusters like serverless clusters, we could have two tenants, one for the customer & one for CRL tooling like the `sqlprober`. We could get isolation this way, so customer couldn't run the CRL tenant out of CPU, no matter what workload they sent. **Details here are vague, and running dedicated like serverless clusters is very far off.**

**Additional context**
N/A

CC @sumeerbhola  @bdarnell @tbg for thoughts! 

Epic CC-4054

**Comment by udnay** [comment]
Could the admission controller send back an error code to indicate that it's having trouble keeping up or something so the `sqlprober` know that the failure is due to a cluster being overloaded? Something like a `Pause` frame? Not sure if it's possible via the wire protocol we use.

**Comment by joshimhoff** [comment]
I am not sure! I think the alternative of just setting timeouts very very high on `sqlprober` requests is worth considering. We should at least try that & see how well it works in practice.

For `kvprober` requests tho, we should skip the queues, because that is trivial IIUC.

@sumeerbhola and @tbg, can I get your take on this? Do you agree that `kvprober` requests (e.g. https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvprober/kvprober.go#L251) should skip the admission control queues? I may make this change & even backport it if the answer is yes. Backporting is reasonable IMO as (i) `kvprober` is off by default & behind a non-public cluster setting and (ii) not paging SRE when CC clusters are out of CPU is a very large operational win.

**Comment by tbg** [comment]
Seems reasonable to me.

(sent from mobile, please excuse my brevity)

**Comment by sumeerbhola** [comment]
> @sumeerbhola and @tbg, can I get your take on this? Do you agree that kvprober requests (e.g. https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvprober/kvprober.go#L251) should skip the admission control queues?

btw, admission control settings are off by default for 21.2, but we expect to turn it on for all/most CockroachCloud clusters after discussion with SRE.
Regarding kvprober bypassing admission control, it may already be the case. See the `bypassAdmission` logic here https://github.com/cockroachdb/cockroach/blob/43f0d270ed209ee5199e428f6eda18925af743a7/pkg/server/node.go#L973-L982. We currently only use `roachpb.AdmissionHeader_OTHER` and `roachpb.AdmissionHeader_FROM_SQL` and only if the latter is set will the request be subject to waiting for admission. See `kv.NewTxnWithSteppingEnabled` for the only code that sets `FROM_SQL` -- the current callers are all in the `sql` package.
But I think it is worth adding a code comment in that code in `node.go` that I pointed to earlier that once we start using `roachpb.AdmissionHeader_ROOT_KV` and subjecting it to admission control it may cause `kvprober` to no longer bypass admission control.

**Comment by joshimhoff** [comment]
> btw, admission control settings are off by default for 21.2, but we expect to turn it on for all/most CockroachCloud clusters after discussion with SRE.

Awesome!

> But I think it is worth adding a code comment in that code in node.go that I pointed to earlier that once we start using roachpb.AdmissionHeader_ROOT_KV and subjecting it to admission control it may cause kvprober to no longer bypass admission control.

Ack! I can take a shot at adding the code comment. And actually I think it slightly more subtle than I first suggested...

In case of a dedicated cluster, we def want to skip the admission control queues, as a dedicated cluster can be run out of resources by workload choices the customer makes.

**But what about a serverless host cluster?** In this case, a single customer should not be able to induce significant queueing at the KV layer, as if they can, other customers will be negatively affected. And also if they can, SRE does have actions it can take, as we own capacity planning the cluster, unlike with dedicated.

**I wonder if in case of serverless host cluster, we actually do want to go thru the admission control queues.** If yes, I favor a cluster setting called `kv.prober.sit_in_admission_control_queues` or similar that defaults to `false` but that we will set to `true` on serverless host clusters.

**Comment by sumeerbhola** [comment]
> If yes, I favor a cluster setting called kv.prober.sit_in_admission_control_queues or similar that defaults to false but that we will set to true on serverless host clusters.

I don't know the server-side plumbing to have an opinion yet. Do you know which server-side RPC endpoint is hit by the `kv.DB` interface being used by the `kvprober`?

**Comment by joshimhoff** [comment]
There is a probe that does point reads & a probe that executes a txn that puts & then deletes data at a key.

https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvprober/kvprober.go#L251
https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvprober/kvprober.go#L307

There is also a "planner" component that scans meta2:

https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvprober/planner.go#L221

My guess for point reads is `GetRequest`: https://github.com/cockroachdb/cockroach/blob/4d987b3f0788c98fa358715b336a1c55e254ee50/pkg/roachpb/api.proto#L1769.

My guess for "planner" doing scans is `ScanRequest`: https://github.com/cockroachdb/cockroach/blob/4d987b3f0788c98fa358715b336a1c55e254ee50/pkg/roachpb/api.proto#L1777.

Not as clear to me how a txn that puts & then deletes data at a key but my guess is `PutRequest`, `DeleteRequest`, & some methods like `EndTxnRequest`: https://github.com/cockroachdb/cockroach/blob/4d987b3f0788c98fa358715b336a1c55e254ee50/pkg/roachpb/api.proto#L1767.

Let's see what Tobias says.

**Comment by tbg** [comment]
`kvprober` uses this `db`:

https://github.com/cockroachdb/cockroach/blob/85b1e92455eb2795043d71e5766b1b56dab308f2/pkg/server/server.go#L471-L472

It will be using `(*Node).Batch` as the system tenant, so I think Sumeer is right that this will be classified as OTHER at the time of writing.

**Comment by sumeerbhola** [comment]
> It will be using (*Node).Batch as the system tenant
 
In the serverless context, where we do want kvprober to fire under overload, does it authenticate with the server as the system tenant? If we can arrange for it to use a non-system tenant, we will use the following codepath and subject it to admission control.
https://github.com/cockroachdb/cockroach/blob/8a07def384bba413c22e09416802aebea83ad1a8/pkg/server/node.go#L975-L979

**Comment by tbg** [comment]
It runs on the KV host cluster, i.e. it will definitely use the system tenant by default (there isn't another tenantID to chose from). I'll defer to @joshimhoff as to what the desired end state is, but the issue and conversation so far suggests that Josh wants to make sure kvprober continues to *bypass* admission control, since SREs want to be alerted to problems in the host cluster that can not be caused by some tenants' pathological workload.

**Comment by joshimhoff** [comment]
@tbg, My view is not that we should always skip the queues. It is that for a dedicated cluster we should always skip the queues but for a serverless host cluster we should NOT skip the queues, as (i) host cluster capacity planning is owned by SRE / CRL (SRE can take action in other words) and (ii) queueing at the KV layer may have bad effects on tenants other than the one that induced the queueing. Earlier comment about this at https://github.com/cockroachdb/cockroach/issues/68732#issuecomment-923162737. @tbg, I am interested in what you think about the end state I suggest!

**Comment by tbg** [comment]
Oh, apologies for the confusion. I mixed up tenant cost control with admission control.

I agree that they should be subject to it in Serverless and not in Dedicated within our cloud.

Looks like we can "just" teach `kvprober` to populate the `AdmissionHeader` for the `BatchRequest`s it sends (to `ROOT_KV`) https://github.com/cockroachdb/cockroach/blob/30ab2e1ea8a7c862270bcad56bddcda02bab95c9/pkg/roachpb/api.pb.go#L6786-L6815
 and then https://github.com/cockroachdb/cockroach/blob/792c56c0e85b75f8b7d0da4eeca2faa25b4fc717/pkg/server/node.go#L973-L982 should do the right thing (apply admission control). I agree with a cluster setting (attached to the kv prober) on whether to bypass admission control. It would probably default to false, straw man `kv.prober.bypass_admission_control`. We could populate the default value from an env var if that simplifies the `dedicated` story. Of course on dedicated users could always change that cluster setting (or maybe we have enough roles to avoid that now).

@sumeerbhola using a tenant here is not appropriate, unfortunately. The prober reads all of the meta ranges and then probes any range in the keyspace. Reading "all data" but under a tenant complicates what it means to be a tenant.

**Comment by joshimhoff** [comment]
Thanks. This all makes sense. I think an SRE can execute on this soon-ish.

**Comment by vy-ton** [comment]
Rereading this now, I wonder if there's a way to leverage https://github.com/cockroachdb/cockroach/pull/76512 or do we still need the ability to bypass admission control queues in `kvprober` via the setting? @msirek @RaduBerinde

**Comment by joshimhoff** [comment]
@dasrirez has implemented skipping queues for `kvprober` requests already: https://github.com/cockroachdb/cockroach/pull/72748. As a result, we are prob all set with `kvprober`, tho we need production experience with admission control enabled to know for sure! 

Note that for `sqlprober` we aren't skipping queues. We are simply pushing up timeouts for probes instead. We think this will avoid pages, and we have done are at least one successful test of pushing up timeouts in production. If it doesn't work out, we'll re-open this issue for discussion, with a focus on prioritizing the execution of certain SQL workloads. https://github.com/cockroachdb/cockroach/pull/76512 seems compelling, but ya, we hope none of it's needed post pushing up timeouts.
