### ISSUE TITLE
Release: an official API for latest stable version number of CRDB

### ISSUE THREAD

**Issue by ZhouXing19** [cockroachdb/cockroach#68735]
**Is your feature request related to a problem? Please describe.**
Currently, there's not an official API to provide the latest **stable** version of CRDB. [https://edge-binaries.cockroachdb.com/cockroach/cockroach.linux-gnu-amd64.LATEST](https://edge-binaries.cockroachdb.com/cockroach/cockroach.linux-gnu-amd64.LATEST) gives the latest CRDB but not necessarily a stable one. The [cockroach-go/testserver](https://github.com/cockroachdb/cockroach-go/tree/master/testserver) requires downloading the latest stable CRDB each time when users start a test.

Right now we can either query the redhat API or webscrape [the release page](https://www.cockroachlabs.com/docs/releases/index.html#production-releases) to get the desired version, but these approaches are inefficient and unreliable.

**Describe the solution you'd like**
An API that provides the latest stable version number of CRDB. For example, after each release, it regenerates a JSON file with the version number and urls for downloads. 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by rafiss** [comment]
This should be covered by https://github.com/cockroachlabs/registration/pull/271
