### ISSUE TITLE
stability: brand new cluster wedged

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6879]
sha: 45f7fd5

Wiped and re-initialized `beta` about 5h ago.
It started well, but for a while now (no specific time, but the logs may indicate something), node 1 (`104.196.97.139`, the first node to be initialized) has been much more massive than all other nodes.

It is using ~8GB of ram compared to 60MB-200MB for the other nodes. Similar difference for bytes used.
It seems to have a few long-running opt: https://104.196.97.139:8080/debug/requests?fam=tracing&b=-1

There are multiple deadline exceeded messages in the logs, but nothing particularly unusual as far as I can tell.

The photos app dropped to zero req/s fairly quickly, but that's not particularly unusual. The block_writer claims to still be making progress.
Admin page graphs are down, so a little tricky to tell the happened before.

I'm leaving the cluster exactly as is for diagnosing.
It's important to know that other than running the block_writer and photos app, nothing at all was done, each node is in its first run.

**Comment by tschottdorf** [comment]
Yep, looks pretty unhappy. A split has been stuck forever. Leader lease
acquisition sitting around (by the replicate queue). The task list is
fairly persistent as well:

0xc8203863f0: 49 tasks
5      storage/replica.go:581
35     server/node.go:803
3      storage/queue.go:383
2      storage/replica.go:2141
2      storage/intent_resolver.go:302
2      kv/txn_coord_sender.go:863




On Tue, May 24, 2016 at 4:32 PM marc <notifications@github.com> wrote:

> sha: 45f7fd5
> <https://github.com/cockroachdb/cockroach/commit/45f7fd507bb9235a2b86549857c772dd82ab3b03>
>
> Wiped and re-initialized beta about 5h ago.
> It started well, but for a while now (no specific time, but the logs may
> indicate something), node 1 (104.196.97.139, the first node to be
> initialized) has been much more massive than all other nodes.
>
> It is using ~8GB of ram compared to 60MB-200MB for the other nodes.
> Similar difference for bytes used.
> It seems to have a few long-running opt:
> https://104.196.97.139:8080/debug/requests?fam=tracing&b=-1
>
> There are multiple deadline exceeded messages in the logs, but nothing
> particularly unusual as far as I can tell.
>
> The photos app dropped to zero req/s fairly quickly, but that's not
> particularly unusual. The block_writer claims to still be making progress.
> Admin page graphs are down, so a little tricky to tell the happened before.
>
> I'm leaving the cluster exactly as is for diagnosing.
> It's important to know that other than running the block_writer and photos
> app, nothing at all was done, each node is in its first run.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/6879>
>
-- 

-- Tobias

**Comment by tschottdorf** [comment]
goroutine 76 [select, 192
minutes]:github.com/cockroachdb/cockroach/storage.(*Replica).redirectOnOrAcquireLeaderLease(0xc820150e00,
0x7f3601d061e0, 0xc868fb8f60, 0x8fb6347299b2dee1)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:641
+0x8e2github.com/cockroachdb/cockroach/storage.(*Replica).getLeaseForGossip.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:2106
+0x62github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunTask(0xc8203863f0,
0xc824497940, 0xc824497900)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:166
+0xd9github.com/cockroachdb/cockroach/storage.(*Replica).getLeaseForGossip(0xc820150e00,
0x7f3601d061e0, 0xc868fb8f60, 0xc824497a18, 0x10)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:2141
+0xafgithub.com/cockroachdb/cockroach/storage.(*Replica).maybeGossipFirstRange(0xc820150e00,
0x2775260)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:2178
+0x916github.com/cockroachdb/cockroach/storage.(*Store).maybeGossipFirstRange(0xc820092780,
0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:1037
+0x210github.com/cockroachdb/cockroach/storage.(*Store).startGossip.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:994
+0x269github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8203863f0,
0xc8202c12c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 77 [select, 192
minutes]:github.com/cockroachdb/cockroach/storage.(*Replica).redirectOnOrAcquireLeaderLease(0xc820150e00,
0x7f3601d061e0, 0xc851d7e120, 0x8fb6347299b2dee1)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:641
+0x8e2github.com/cockroachdb/cockroach/storage.(*Replica).getLeaseForGossip.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:2106
+0x62github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunTask(0xc8203863f0,
0xc820f39d60, 0xc852540200)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:166
+0xd9github.com/cockroachdb/cockroach/storage.(*Replica).getLeaseForGossip(0xc820150e00,
0x7f3601d061e0, 0xc851d7e120, 0x7f3601d061e0, 0xc851d7e120)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:2141
+0xafgithub.com/cockroachdb/cockroach/storage.(*Store).maybeGossipSystemConfig(0xc820092780,
0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:1060
+0x109github.com/cockroachdb/cockroach/storage.(*Store).startGossip.func2()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:1013
+0x269github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8203863f0,
0xc8202c12e0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62


Something has gone wrong with leader leases for sure. If that is the
first range, then I'm not surprised nothing else is moving forward.


On Tue, May 24, 2016 at 4:48 PM Tobias Schottdorf <tobias@cockroachlabs.com>
wrote:

> Yep, looks pretty unhappy. A split has been stuck forever. Leader lease
> acquisition sitting around (by the replicate queue). The task list is
> fairly persistent as well:
>
> 0xc8203863f0: 49 tasks
> 5      storage/replica.go:581
> 35     server/node.go:803
> 3      storage/queue.go:383
> 2      storage/replica.go:2141
> 2      storage/intent_resolver.go:302
> 2      kv/txn_coord_sender.go:863
>
>
>
>
> On Tue, May 24, 2016 at 4:32 PM marc <notifications@github.com> wrote:
>
>> sha: 45f7fd5
>> <https://github.com/cockroachdb/cockroach/commit/45f7fd507bb9235a2b86549857c772dd82ab3b03>
>>
>> Wiped and re-initialized beta about 5h ago.
>> It started well, but for a while now (no specific time, but the logs may
>> indicate something), node 1 (104.196.97.139, the first node to be
>> initialized) has been much more massive than all other nodes.
>>
>> It is using ~8GB of ram compared to 60MB-200MB for the other nodes.
>> Similar difference for bytes used.
>> It seems to have a few long-running opt:
>> https://104.196.97.139:8080/debug/requests?fam=tracing&b=-1
>>
>> There are multiple deadline exceeded messages in the logs, but nothing
>> particularly unusual as far as I can tell.
>>
>> The photos app dropped to zero req/s fairly quickly, but that's not
>> particularly unusual. The block_writer claims to still be making progress.
>> Admin page graphs are down, so a little tricky to tell the happened
>> before.
>>
>> I'm leaving the cluster exactly as is for diagnosing.
>> It's important to know that other than running the block_writer and
>> photos app, nothing at all was done, each node is in its first run.
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cockroachdb/cockroach/issues/6879>
>>
> --
>
> -- Tobias
>
-- 

-- Tobias

**Comment by bdarnell** [comment]
The `processRaft` goroutine is busy essentially all the time (based on manually refreshing https://104.196.97.139:8080/_status/stacks/local a bunch), which means that heartbeats are being missed and most ranges are stuck in StateCandidate: https://104.196.97.139:8080/_status/ranges/local. (The only one with a steady leader is range 11, which has not been upreplicated and I think is empty). Commands are getting applied, though, so it looks like elections are able to succeed occasionally and then can't get through the backlog quickly enough to make their next heartbeat. 

If #6815 were fixed then I'd recommend increasing the tick interval to stabilize things. For now, I think we need to turn off the load generators and see if it clears up on its own.

**Comment by mberhault** [comment]
ok. I'm stopping the block_writer and photos apps. I'm leaving `beta` off the upgrade list for now.

**Comment by bdarnell** [comment]
Node 1 ran out of memory and died; I've restarted it.

**Comment by mberhault** [comment]
shall I proceed with an upgrade? or do you want to poke at it some more?

**Comment by bdarnell** [comment]
Go head and update it.

**Comment by mberhault** [comment]
upgraded to beta candidate.
Still wedged. I even got this fun message on node 1:
`W160525 16:30:08.110723 storage/store_pool.go:61  store 1 on node 1 is now considered offline`

**Comment by bdarnell** [comment]
> (The only one with a steady leader is range 11, which has not been upreplicated and I think is empty). 

Range 11 is definitely not empty: it's the block_writer table, and it's enormous (I ran `cockroach debug raft-log /mnt/data 11 | wc` to see how big it is, and that command has been running for over 45 minutes now). It looks like the block_writer was running against node 1 before the other nodes were started, and this allowed the table to grow beyond the split threshold before it could be replicated to other nodes. Now that it's larger than the split threshold, it must split before it can be replicated (but it can't split as long as range 1 is unhealthy).

The unreplicated block_writer table has a somewhat surprising consequence: it's *fast*. Everything is a local write, so the block_writer processes can effectively monopolize the processRaft loop. The block_writers cause other ranges to miss their heartbeats and stall, but the block_writer can continue because it doesn't need to talk to anyone else. 

We need to figure out some way to ensure fairness here, so one range can't starve others. In the meantime, I think the best way to get the beta cluster back on its feet is to wipe it again, and this time restart all the cockroach nodes before starting any of the load generators. 

More unanswered questions: Why hasn't range 11 split down to a replicatable size, and why hasn't the raft log been garbage collected? I suspect that the answer is that as long as some of the other ranges are unhealthy, the queues can get hung up on those ranges and will never get to range 11.

**Comment by mberhault** [comment]
that's odd. I always start all nodes, wait a little bit, then start the load generators.
It's possible I did it too quickly, but definitely not for a few minutes.

**Comment by bdarnell** [comment]
Hmm. Maybe there's something else that prevented the initial replication then.

**Comment by petermattis** [comment]
I noticed a similar problem recently where I started a 3 node cluster and
then started the block_writer shortly after that. Looking at the admin UI I
saw one node was consuming all of the cpu and the others were idle. I
killed the block_writer and allowed rebalancing to occur and then started
up the block_writer again and the cpu usage looked more reasonable. Simply
put, this seems reproducible.

**Comment by bdarnell** [comment]
Unassigning since I'm not actively looking at this.

**Comment by mberhault** [comment]
closing.
