### ISSUE TITLE
pgwire: COPY binary protocol fails when the client chunks the data stream in the middle of a record

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/cockroach#68805]
Per the pgwire spec:
> CopyData: Messages sent from the backend will always correspond to single data rows, but messages sent by frontends might divide the data stream arbitrarily.

The pgx/pgconn library divides binary COPY streams at arbitrary 64k boundaries
https://github.com/jackc/pgconn/blob/53f5fed36c570f0b5c98d6ec2415658c7b9bd11c/pgconn.go#L1217-L1222

Copying large amount of data thus leads to "partial copy data row" errors at https://github.com/cockroachdb/cockroach/blob/8de063f1c60767797f143a60c2413685794f21f6/pkg/sql/copy.go#L485 because the overall structure of the `copyMachine` code assumes that tuples aren't split across wire-message boundaries.

X-Ref: https://github.com/cockroachdb/cdc-sink/issues/45

Epic CRDB-7217

**Comment by bobvawter** [comment]
It looks like there was work back in 2017 to make partial rows work associated with issue #12708 but then the code was reworked in 2018 with commit 47b80321ade8bcbec68084f194b7e814e19a95a3

**Comment by steven-sheehy** [comment]
I can confirm this is the case for `COPY FROM STDIN CSV` as well, except with a different error than the binary format noted in the description. Apparently COPY in the default `TEXT` mode doesn't have the problem. The error for CSV is:

```
ERROR: read CSV record: record on line 1: wrong number of fields
```

To reproduce, you can just set the copy buffer size smaller than a single CSV row. I've made a sample project that does that:

1. `cockroach demo`
2. `git clone https://github.com/steven-sheehy/cockroachdb-copy.git`
3. `cd cockroachdb-copy`
4. `./mvnw spring-boot:run -Dspring-boot.run.arguments=--spring.datasource.password=<password>`
5. See error in logs
