### ISSUE TITLE
Dump range reports for every replica periodically into logs directory.

### ISSUE THREAD

**Issue by lancel66** [cockroachdb/cockroach#68810]
**Is your feature request related to a problem? Please describe.**
This would be very helpful for debugging. Currently the customer is required to run a debug zip, which can be 10s of GBs and take hours to complete on large 20+ node clusters, and extract the relevant data from there. Also, the debug zip may not capture errors relevant to troubleshooting replicas.

**Describe the solution you'd like**
A tunable parameter which allows adjusting time span of range replicas, as well as which location to dump the logs.

**Describe alternatives you've considered**
debug.zip

Jira issue: CRDB-9277

**Comment by lunevalex** [comment]
@lancel66 I believe you can just query this information from the SQL console i.e `select * from crdb_internal.ranges;` and then just output it to a file. What is the benefit of the periodic output vs an on demand query?

**Comment by lancel66** [comment]
> @lancel66 I believe you can just query this information from the SQL console i.e `select * from crdb_internal.ranges;` and then just output it to a file. What is the benefit of the periodic output vs an on demand query?

It basically boils down to this: When the cluster is offline or wedged, you can't run a query, but you can retrieve the logs.
