### ISSUE TITLE
ui: add filtering to the databases pages

### ISSUE THREAD

**Issue by matthewtodd** [cockroachdb/cockroach#68826]
To include region / node when that information is available.

Part of #65737 (see designs there). Also a follow-on to #68390.

Jira issue: CRDB-9290

Epic CRDB-20388

**Comment by maryliag** [comment]
Figma https://www.figma.com/file/OBkF4RIQajIkDYVAdZ1IFx/cc-multi-region-serverless-observability?node-id=1135%3A21331&t=EvZoicvCeaG0g114-0

**Comment by gtr** [comment]
Closed by: #[92589](https://github.com/cockroachdb/cockroach/pull/92589).
