### ISSUE TITLE
ui: add search to the databases pages

### ISSUE THREAD

**Issue by matthewtodd** [cockroachdb/cockroach#68825]
Part of #65737 (see designs there). Also a follow-on to #68390.

Jira issue: CRDB-9289

Epic CRDB-20388

**Comment by maryliag** [comment]
Figma: https://www.figma.com/file/OBkF4RIQajIkDYVAdZ1IFx/cc-multi-region-serverless-observability?node-id=1135%3A21331&t=EvZoicvCeaG0g114-0
