### ISSUE TITLE
kv: TestReplicaRemovalCampaign is flaky

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#6883]
--- FAIL: TestReplicaRemovalCampaign (0.61s)
	client_raft_test.go:1023: 1. raft term should have advanced

https://circleci.com/gh/cockroachdb/cockroach/18261

**Comment by tschottdorf** [comment]
@d4l3k: assigning based on blame. As usual, feel free to find a more appropriate victim.

**Comment by tamird** [comment]
Fixed in #7142.
