### ISSUE TITLE
kvserver: load-based splits aren't immediately considered for load-based rebalancing

### ISSUE THREAD

**Issue by aayushshah15** [cockroachdb/cockroach#68840]
Currently, upon the application of a range split, we [clear out the `leaseholderStats` for both the left-hand side and the right-hand side](https://github.com/cockroachdb/cockroach/blob/4e5389a9b802b991e95c9a1d21c8743cf98be451/pkg/kv/kvserver/store_split.go#L327-L339). 

This means that, immediately after performing a load-based split, we end up ignoring the two resulting ranges for load-based rebalancing until we re-populate their `leaseholderStats`. In practice, this means that the `StoreRebalancer` doesn't immediately consider rebalancing such post-split replicas away. This partly defeats the goal of load-based splitting as we're not capitalizing on our ability to achieve a better load distribution throughout the cluster.

As an interesting aside, [we do split the `replicaStats` for write requests ](https://github.com/cockroachdb/cockroach/blob/4e5389a9b802b991e95c9a1d21c8743cf98be451/pkg/kv/kvserver/store_split.go#L331-L339) but we don't use these `writeStats` in the `StoreRebalancer` as a signal for rebalancing.

/cc. @cockroachdb/kv 

Jira issue: CRDB-9298

**Comment by kvoli** [comment]
resolved by https://github.com/cockroachdb/cockroach/pull/76609 which added splitting of stats.
