### ISSUE TITLE
build: make build problems with GOBIN

### ISSUE THREAD

**Issue by msingle** [cockroachdb/cockroach#6886]
- When trying to follow the directions for [building from source](https://www.cockroachlabs.com/docs/install-cockroachdb.html). I couldn't run `make build` successfully

This is on Ubuntu 16.04
- What did you expect to see?
  normal build output
- What did you see instead?
  
  ```
  Makefile:240: .bootstrap: No such file or directory
  go get github.com/robfig/glock
  /bin/bash: ../../../../bin/glock: No such file or directory
  Makefile:237: recipe for target '.bootstrap' failed
  make: *** [.bootstrap] Error 127
  ```

I worked around it by unsetting $GOBIN (which then completed correctly)

**Comment by petermattis** [comment]
@msingle Thanks for the report. I imagine we're just expecting `go install` output in the wrong directory.

**Comment by bdarnell** [comment]
See also #4182, which will address all the assumptions we currently make about your go environment. In the meantime, we recommend building cockroachdb in a GOPATH that doesn't have anything else in it (because `glock` will run `git checkout` in our dependencies to get pinned versions), and don't set GOBIN.

**Comment by spencerkimball** [comment]
@bdarnell since #4182 has been closed, is this issue resolved as well? Please close or assign.

**Comment by bdarnell** [comment]
The issue is still present - setting `GOBIN` will break the build (if building from scratch). Since we now set `GOPATH` in the `Makefile`, we should also set/clear `GOBIN`.
