### ISSUE TITLE
ERROR: unimplemented: multiple active portals not supported You have attempted to use a feature that is not yet implemented

### ISSUE THREAD

**Issue by qinlz-1** [cockroachdb/cockroach#68885]
**Environment:**
 - CockroachDB version [21.1.7]
 - Server OS: [Linux]
 - Client app [JDBC]
The query statement is simple
![image](https://user-images.githubusercontent.com/80371132/129340232-df70321d-ea10-4e7f-8b4a-c3908b53221f.png)

**Comment by qinlz-1** [comment]
it is just a simple SQL
 An error occurred executing SQL:
 SELECT
 				a.bt_uid
 			FROM
 				cyt_baby.b_bottle a
 				JOIN cyt_baby.b_user b ON a.bt_uid = b.us_id 
 			WHERE
 			    
 				a.bt_eattime >= timestamp'2021-01-01' 
 				AND a.bt_eattime <= timestamp'2021-06-30' AND  b.us_level = 1 
  
 
 Error determining value metadata from SQL resultset metadata
 ERROR: unimplemented: multiple active portals not supported：You have attempted to use a feature that is not yet implemented. See: https://go.crdb.dev/issue-v/40195/v21.1

**Comment by rafiss** [comment]
Hi @qinlz-1 ! I'm going to close this issue, but if you'd like to, can you share more details on https://github.com/cockroachdb/cockroach/issues/40195. Please state the name of the tool you are using and provide instructions on how to reproduce the problem.
