### ISSUE TITLE
Caused by: org.postgresql.util.PSQLException: ERROR: parsing as type timestamp: field day value 31 is out of range

### ISSUE THREAD

**Issue by qinlz-1** [cockroachdb/cockroach#68886]
Environment:

CockroachDB version [21.1.7]
Server OS: [Linux]
Client app [JDBC]

![image](https://user-images.githubusercontent.com/80371132/129341750-58b2012f-a460-4f24-9d91-3954b1d0d418.png)

**Comment by yuzefovich** [comment]
There are only 30 days in June, so the error seems reasonable.
