### ISSUE TITLE
storage: Validate cluster ID in Store.Start instead of Node (TestCorruptedClusterID)

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#6889]
server.TestCorruptedClusterID currently takes 10 seconds because it has
to wait for the store to time out waiting to unfreeze its ranges. We
should detect cases in which the unfreeze cannot succeed before entering
that select statement.

I have a WIP for this in https://github.com/bdarnell/cockroach/tree/cluster-id-validation but it causes failures in client_metrics_test.go.

**Comment by tschottdorf** [comment]
The test runs in 0.069s.
