### ISSUE TITLE
logs: using friendlier YYYY-MM-DD HH:MM:SS.xxxxxx timestamps in JSON formated logs

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#68900]
Raised by @fabiog1901 (see [Slack](https://cockroachlabs.slack.com/archives/CHKQGKYEM/p1628876038103200))

**Is your feature request related to a problem? Please describe.**
I'm using the new logging framework and I've set the format to `JSON` (and all other fluentd/compact flavors). In all cases, the timestamp is saved as an epoch time instead of the more user friendlier `YYYY-MM-DD HH:MM:SS.xxxxxx`. This makes it very hard to grep a file for a specific event time, let alone see when the event happens. 

**Describe the solution you'd like**
So here's my request:
- Can we have a feature to set the time format for the timestamp?
- Alternatively, for when the sink is a file, can we prepend the json payload with a human readable timestamp (`similar to crdb-v2`)?

**Comment by thtruo** [comment]
This UX enhancement came up in an internal discussion cc @knz for awareness. I'm curious if there is precedent or context around why we use epoch timestamps in JSON formatted logs. Is there a technical rationale for why that's the case?

**Comment by knz** [comment]
You can convert the timestamps using fluent.

Also jq.

**Comment by knz** [comment]
dup #48824

We need to document how to use a standard log processor to interpret the dates and render them in a custom format.

**Comment by knz** [comment]
> Is there a technical rationale for why that's the case?

That's what Fluent wants/needs.
