### ISSUE TITLE
perf: enable multi-node benchmarks

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#6890]
The benchmarks in the `sql` package currently only test single-node setups. It would be useful to enable multi-node benchmarks were all of the nodes run locally in the benchmark process. This would allow using cpu and memory profiling and (go) tracing across the entire cluster. We should either enhance `server.TestServer` to all multi-node configurations are add a new `server.TestCluster`.

**Comment by tamird** [comment]
I think this was done in f6f71ef44d50a7157c154454737c5d073990d91e.
