### ISSUE TITLE
ui: query plans do not load when visiting DB Console's Statements page

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#68908]
Identified by @mikeczabator 

**Describe the problem**

Sometimes the query plan doesn't display in the DB Console

<img width="1159" alt="Image 2021-08-13 at 3 09 04 PM" src="https://user-images.githubusercontent.com/1474303/129407698-7dc26e23-b9cb-468a-be3d-a59a49d3016c.png">

**To Reproduce**

Apparently, this doesn't happen reliably on every attempt to load the "logical plan" tab within the Statements page. However, users have reported this occurring intermittently. 

If a user runs into this, they could refresh the page and attempt to load the "logical plan" view again. While a workaround exists, this is a UX regression that needs investigation.

Additional context: this was seen on a nightly build of 21.1.7

Jira issue: CRDB-9350

Epic CRDB-20388

**Comment by thtruo** [comment]
cc @kevin-v-ngo I assigned to you to triage as it lives in the Statements page. This came up in a customer call, so wanted to raise this issue and relay it to you - thanks!

**Comment by xinhaoz** [comment]
Closing this issue since it is no longer applicable.
