### ISSUE TITLE
changefeedccl: redact changefeed credentials

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#68998]
Today, we redact some credentials but expose others in plaintext in various observability tools, including:
- The jobs table
- The DB Console 

![image](https://user-images.githubusercontent.com/13264141/131884927-cf735237-2f9c-48ce-bd0f-791c203f8498.png)

Though we do redact the secret key, generally it is also expected that you keep access keys secret as well. For example, in the [confluent documentation for API keys
](https://docs.confluent.io/cloud/current/client-apps/api-keys.html), they say to "Save the API key and secret output in a secure location."
Since we do not have the option to hide this information from non-admin roles, from our standpoint it makes sense to redact both. 

Epic CRDB-9401

**Comment by miretskiy** [comment]
This has been discussed many times in bulkio.  AWS_ACCESS_KEY_ID is not considered to be sensitive.  It's a user name.

**Comment by shermanCRL** [comment]
Per @miretskiy this seems clearly decided that AWS_ACCESS_KEY_ID is not a secret.

@amruss please re-open if you think this is not the right conclusion, or if the customer is unsatisfied. @stevendanna suggests there may be a larger issue of who can see the changefeed config overall, not just this key.
