### ISSUE TITLE
sql: add handling of schema-changes to foreign keys

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#6900]
Current foreign key implementation is a WIP and doesn't handle schema changes.
1. FK-related code (as well as lots of other code) needs to be audited for correct handling of `tableDesc.Mutations` in addition to `tableDesc.Indexes`
2. DROP should move altering referenced tables into the schema changer so that it happens only once all leases on the non-deleted table expire.

**Comment by vivekmenezes** [comment]
Adding in failing test cases for the above scenarios would be a first step.

**Comment by dt** [comment]
This has been done for awhile.
