### ISSUE TITLE
kvserver: invalid logging format string in store.go

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#69004]
Found while working on a unit test:

```
I210816 18:28:55.880830 11415 kv/kvserver/store.go:1166  ...  failed to transfer lease ... for range %!s(MISSING) when draining: %!v(MISSING)
```

Notice the MISSING: some of the logging format verbs don't have a corresponding positional argument.

cc @tbg for triage.

**Comment by grtcoder** [comment]
Hey, I would like to help with this. Can I get more details on it?

**Comment by knz** [comment]
what details do you need?

**Comment by erikgrinaker** [comment]
@knz Do you know which version this was? The error message clearly shows that the last format argument was a `%v`, but the format string on master is `%s`:

https://github.com/cockroachdb/cockroach/blob/15ae579a2bb3edc0afc2a55c530c7ddd93951d6d/pkg/kv/kvserver/store.go#L1197-L1203

Blame shows that those messages haven't been touched in a year.

It did use a `%v` parameter back in 20.2, but the rest of the message doesn't match:

https://github.com/cockroachdb/cockroach/blob/37cda4a00a5f8070c1208060232cc0cc65ebce44/pkg/kv/kvserver/store.go#L1182-L1188

**Comment by knz** [comment]
I believe when I encountered this, I was working off the `master` branch.
I'm glad to see this has been updated since though. I'm unsure how to explain the issue.

(I think it's idiomatic to use `%v` with errors)

**Comment by erikgrinaker** [comment]
I tested this on `master` by removing the conditional branches, and it formats correctly, so I'm going to close this.

>(I think it's idiomatic to use %v with errors)

It is, but that's mostly to display `nil` errors in a reasonable way (`<nil>` vs `%!s(<nil>)`). Here, we've already checked that `err != nil`, so I think it's fine.
