### ISSUE TITLE
server: add memory accouting for Statements gRPC endpoint

### ISSUE THREAD

**Issue by Azhng** [cockroachdb/cockroach#69032]
Currently, the Statement (`GET /_status/statements`) performs RPC fanout to the entire cluster and buffers all response in memory. This can create issue where the total amount of data it buffers will exceeds the currently available memory. 

We should introduce memory accounting in the RPC handler to abort the handler if the memory limit has been exceeded

Jira issue: CRDB-9415

**Comment by jordanlewis** [comment]
I think the proper solution for this should be to introduce pagination to the statements endpoint. Perhaps the easiest way to do this would be to migrate to the API v2 framework.

**Comment by Azhng** [comment]
Statement endpoint is essentially a hash aggregation. Introducing pagination won't really solve the problem here because we still need to complete the aggregation before pagination.

Alternative is that we can perhaps implement a Sort -> Merge in the RPC endpoint, which potentially can allow us do use the pagination infrastructure. Though this might be a bit tricky to get right.
