### ISSUE TITLE
changefeedccl: Improve run_status handling

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#69038]
Currently, when we set changefeed run status (e.g. because of an error), we don't clear that run status
for some time. The intention was that we want to see previous error for a while.
However, if the error occurs during initial backfill, or during long catchup scan, then that error will not be
cleared until job progress checkpoint -- which may not happen for a very, very long time.

Seeing very old error message (e.g.  `retryable error: retryable changefeed error: kvFeed: memory budget exceeded: 29113216 bytes requested, 1069469631 currently allocated, 1073741824 bytes in budget`) is very confusing.

Either we need to ensure that that error status is cleared; or perhaps just tag that message w/ the timestamp.

Jira issue: CRDB-9419

**Comment by amruss** [comment]
Related: https://github.com/cockroachdb/cockroach/issues/77693

**Comment by shermanCRL** [comment]
Simplest version here would be to add a timestamp to the error message, so it can be easily identified if it's old.

**Comment by miretskiy** [comment]
I don't think it's much of an issue.
