### ISSUE TITLE
jobs: exponential backoff defaults inappropriate for long-running changefeed jobs

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#69037]
**Describe the problem**

The job system was recently changed to exponentially back-off when re-adopting jobs (https://github.com/cockroachdb/cockroach/pull/66889).  By default, this back-off can grow as large as 24 hours.

Since changefeed jobs are long-running, the coordinator node for the job may fail or restart many times throughout its lifetime.  Each restart will add to the number of runs tracked by the run state, leading to longer and longer adoption times.  

Eventually, this long back-off time may prevent the changefeed from restarting if the high watermark of the changefeed falls behind the gc TTL.

Some options to fix this include:

- Per job (or job type) retry policy
- Use different settings for the exponential backoff that grow less quickly
- Reset the run state from inside the changefeed machinery when we advance the frontier the first time

Jira issue: CRDB-9418

**Comment by ajwerner** [comment]
> Reset the run state from inside the changefeed machinery when we advance the frontier the first time

I think that this is my preference. It's very easy to do and will be in one place. 

```
diff --git a/pkg/ccl/changefeedccl/changefeed_processors.go b/pkg/ccl/changefeedccl/changefeed_processors.go
index 00f2e7eee9..f49c89e644 100644
--- a/pkg/ccl/changefeedccl/changefeed_processors.go
+++ b/pkg/ccl/changefeedccl/changefeed_processors.go
@@ -1377,6 +1377,10 @@ func (cf *changeFrontier) checkpointJobProgress(
                }
 
                ju.UpdateProgress(progress)
+
+               if md.RunStats != nil {
+                       ju.UpdateRunStats(1, txn.ReadTimestamp().GoTime())
+               }
                return nil
        })
```

**Comment by miretskiy** [comment]
Dropping release-blocker, while keeping GA blocker.
This issue should not preclude alpha releases from happening.

**Comment by amruss** [comment]
@ajwerner @stevendanna Is there more we think is needed here? I know we did some things to address this on the cdc side.

**Comment by stevendanna** [comment]
https://github.com/cockroachdb/cockroach/pull/69821 probably covers most of the cdc use case, but I think we didn't close it because we had the desire to perhaps have something a bit more structured. Perhaps different backoff policies that different job types could opt into.
