### ISSUE TITLE
DBConsole Overview becomes unavailable when removing region

### ISSUE THREAD

**Issue by smcvey** [cockroachdb/cockroach#69030]
**Describe the problem**
When losing a region in a 3 region cluster (3 nodes per region - 9 nodes total), the DBConsole page becomes unavailable.  It will briefly load for a fraction of a second, then go blank.

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**
1. Create 9 nodes with the following localities:

```
n1: --locality=region=us-west-1
n2: --locality=region=us-west-1
n3: --locality=region=us-west-1
n4: --locality=region=us-east-1
n5: --locality=region=us-east-1
n6: --locality=region=us-east-1
n7: --locality=region=eu-west-1
n8: --locality=region=eu-west-1
n9: --locality=region=eu-west-1
```

2. Load the DBConsole Overview page from node 1 to confirm everything works fine - leave this window open.
3. Power down nodes 7, 8 and 9 replicating a region loss of eu-west-1.
4. The DBConsole Overview page will now go blank.  Other pages will do the same, although some non-GUI pages still work, such as the /_status/vars promethius stats pages.

**Expected behavior**
The DBConsole web interface should continue to work as normal.

**Environment:**
 - CockroachDB version 21.1.7
 - Server OS: Linux
 - Web Browser: Chrome

**Additional context**
Unable to view the DBConsole web interface.

**Comment by nathanstilwell** [comment]
fixed by #69054
