### ISSUE TITLE
sql: test ON UPDATE interactions

### ISSUE THREAD

**Issue by pawalt** [cockroachdb/cockroach#69058]
Upon completion of #69057, we will need to test ON UPDATE interactions with other types of constraints. Of interest are:
- Interaction with foreign key updates
- Interaction with DEFAULT expressions
- Interaction with backfills

Epic CRDB-9148

**Comment by vy-ton** [comment]
@rafiss Do we need to do this for 21.2?

**Comment by otan** [comment]
In particular:

* Interaction with foreign key updates
Ensure we can't create FKs with an ON UPDATE on the same column. Thinks that's done.
When another table does an update on a FK that e.g. sets the value to NULL, do we want ON UPDATE to trigger? I'm guessing no?

* Interaction with DEFAULT expressions
? checking having both populated works ?
this already seems tested, but idk what peyton had in mind

* Interaction with backfills
Backfills over the row (e.g. ADD COLUMN) do not trigger an ON UPDATE change.

**Comment by rafiss** [comment]
thanks @otan !

@vy-ton for 21.2 would you be able to include the above in your acceptance testing? we will also keep this issue open and work on adding these tests during this milestone

**Comment by vy-ton** [comment]
I can check these scenarios

> Ensure we can't create FKs with an ON UPDATE on the same column. 
Is this a FK referencing the ON UPDATE column?

**Comment by otan** [comment]
>> Ensure we can't create FKs with an ON UPDATE on the same column.
> Is this a FK referencing the ON UPDATE column?

You can't have `id INT ON UPDATE SET 2 REFERENCES(other-table.int) ON UPDATE SET NULL`

**Comment by vy-ton** [comment]
- [ ] Interaction with backfills: Backfills over the row (e.g. ADD COLUMN) do not trigger an ON UPDATE change.
```
vy@free-tier9.gcp-asia-southeast1.crdb.io:26257/defaultdb> CREATE TABLE inventories (
    product_id        INT,
    warehouse_id      INT,
    quantity_on_hand  INT DEFAULT 100 ON UPDATE 50,
    PRIMARY KEY (product_id, warehouse_id)
  );
INSERT INTO inventories (product_id, warehouse_id, quantity_on_hand) VALUES (1, 1, 1);
vy@free-tier9.gcp-asia-southeast1.crdb.io:26257/defaultdb> insert into inventories (product_id, warehouse_id) values (2, 2);
vy@free-tier9.gcp-asia-southeast1.crdb.io:26257/defaultdb> select * from inventories;
  product_id | warehouse_id | quantity_on_hand
-------------+--------------+-------------------
           1 |            1 |                1
           2 |            2 |              100
vy@free-tier9.gcp-asia-southeast1.crdb.io:26257/defaultdb> ALTER TABLE inventories ADD COLUMN new_col INT DEFAULT 13;
vy@free-tier9.gcp-asia-southeast1.crdb.io:26257/defaultdb> select * from inventories;
  product_id | warehouse_id | quantity_on_hand | new_col
-------------+--------------+------------------+----------
           1 |            1 |                1 |      13
           2 |            2 |              100 |      13
         
```

**Comment by rafiss** [comment]
We found one buggy interaction where `ALTER TYPE` deletes the `ON UPDATE` clause: https://github.com/cockroachdb/cockroach/issues/71571

**Comment by ZhouXing19** [comment]
- [Interaction with foreign key updates](https://github.com/cockroachdb/cockroach/blob/ecab73938e98e1dbcc207a06eb8e61b7acc3c119/pkg/sql/logictest/testdata/logic_test/on_update#L155-L177)
- [Interaction with DEFAULT expressions](https://github.com/cockroachdb/cockroach/blob/ecab73938e98e1dbcc207a06eb8e61b7acc3c119/pkg/sql/logictest/testdata/logic_test/on_update#L23-L40)
- [PR for Interaction with backfills over row](https://github.com/cockroachdb/cockroach/pull/75846)
