### ISSUE TITLE
Suspicious conditional with identical branches 

### ISSUE THREAD

**Issue by chavacava** [cockroachdb/cockroach#69082]
The following code is suspicious, both branches of the `if` statement are identical.

https://github.com/cockroachdb/cockroach/blob/b16c86ded37e0caff53ccf6c4ae9c0dad434c1b2/pkg/ccl/importccl/read_import_mysql.go#L426-L458

(detected while testing [revive](https://github.com/mgechev/revive) linter)

**Comment by chavacava** [comment]
well, I saw the templates but there is no template for code improvements.

**Comment by adityamaru** [comment]
Thanks for reporting this @chavacava, this should be closed by the linked PR!
