### ISSUE TITLE
backup: overlap covering merge spends a lot of time in `reflect.DeepEquals`

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#69094]
**Describe the problem**

When accumulating many layers in OverlapCoveringMerge, we spent a lot of time comparing payloads in `refelct.DeepEquals`. This reveals itself with a Profile traced run of `BenchmarkOverlapCoveringMerge`. @dt suggested that we could consider specializing `Copy` for the payloads we're comparing here.

<img width="2481" alt="Screen Shot 2021-08-18 at 11 40 34" src="https://user-images.githubusercontent.com/507390/129929052-88ffe5dd-c97e-4569-8af7-27aed2b19576.png">

Version: v21.1.2

**Comment by ajwerner** [comment]
Seems like there's a bunch of options here. You could pass in an equality function with the signature `func(a, b interface{}) bool` that defaults to `reflect.DeepEqual`. In general, the caller knows the types of the payloads.

**Comment by dt** [comment]
no longer used after https://github.com/cockroachdb/cockroach/pull/74394 and https://github.com/cockroachdb/cockroach/pull/74393
