### ISSUE TITLE
storage: monolithic encryption-at-rest registry not disabled for new clusters

### ISSUE THREAD

**Issue by andyyang890** [cockroachdb/cockroach#69116]
When creating a new CockroachDB node or cluster with encryption-at-rest turned after #67320, both the old monolithic Base version registry and the new incremental Records version registry are created, and the version of the registry remains as Base. This is due to the fact that the migration that deprecates the old registry and writes the `STORAGE_MIN_VERSION` file is not run for new clusters.

This should be fixed before 21.2 is released and any potential solutions may want to take into consideration that any new clusters that were created after #67320 may contain both the old and new registry files despite not needing the old one.

cc @jbowens

**Comment by jbowens** [comment]
#69148 is related.
