### ISSUE TITLE
jobs, backupccl: add guardrails to DROP SCHEDULE

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#69129]
There are a few discussion items/TODOs that have bubbled up as a result of discussions around https://github.com/cockroachdb/cockroach/pull/68446.

- [ ] DROP SCHEDULE should release PTS records on the schedule.

- [ ] DROP SCHEDULE should clear the dependent ID from the schedule that is associated with the schedule being dropped.

**Comment by mwang1026** [comment]
removed 
- [ ] DROP SCHEDULE should fail if there are running backup jobs that were spawned from that schedule.
