### ISSUE TITLE
sql: show EXPLAIN for FK cascades or checks in EXPLAIN ANALYZE

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#69124]
Currently the plan for FK cascades or checks is not visible in EXPLAIN ANALYZE or in the bundle for EXPLAIN ANALYZE (DEBUG). This makes any issues related to cascades very hard to debug.

We would have to modify `PlanAndRunCascadesAndChecks` to build against an `explain.Factory`.

Jira issue: CRDB-9450

Epic CRDB-14510

**Comment by yuzefovich** [comment]
Checks are already shown, and cascades will be added in #117093.
