### ISSUE TITLE
clusterversion,*: remove all cluster versions prior to `Start21_2`

### ISSUE THREAD

**Issue by postamar** [cockroachdb/cockroach#69144]
When cutting the release-21.2 branch, we should no longer have any cluster versions earlier than that keyed by `Start21_2`.

This is blocked by https://github.com/cockroachdb/cockroach/issues/66544 and https://github.com/cockroachdb/cockroach/issues/66545

**Comment by ajwerner** [comment]
Time to declare victory:

https://github.com/cockroachdb/cockroach/blob/9e22badb31526d1d9cff15ee55b8b6ff6967d096/pkg/clusterversion/cockroach_versions.go#L157-L160
