### ISSUE TITLE
storage: `debug encryption-active-key` broken

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/cockroach#69148]
The `cockroach debug encryption-active-key` code does not work with the upgraded, records-based encryption registry.

Jira issue: CRDB-9464

**Comment by davidwding** [comment]
Hey Jackson,

While this bug is open, how would you recommend verifying that encryption is active on a CRDB pod?

**Comment by jbowens** [comment]
@davidwding I think the simplest way is to cat the file that looks like `OPTIONS-000006` (file numbers may vary) in the store direcrory. If it's human-readable, than the store is not encrypted. If it's binary garbage, the store is encrypted.

**Comment by itsbilal** [comment]
I just tried reproducing this, and it works? Was able to get `cockroach debug encryption-status` to report all the relevant fields on master. You just need to take the node down for it to work, but that's expected from this command.

The store page on the DB console still fails with `Error decoding protobuf: TypeError: undefined is not an object (evaluating 'F.ccl.storageccl')`, and I don't believe there's a separate issue filed for that. We were treating this as the same issue.

**Comment by jbowens** [comment]
Huh, not sure why exactly I thought it was broken. The `debug encryption-active-key` command _is_ definitely broken, as it [directly reads the monolithic protobuf file](https://github.com/cockroachdb/cockroach/blob/b90605ec68c933523bc3ccfda7ecfeac3f0454e5/pkg/ccl/cliccl/debug.go#L308-L319) that no longer exists (or worse, is outdated).

**Comment by itsbilal** [comment]
Yep, can confirm `encryption-active-key` is broken. And the db console failure is actually a build issue that is resulting in the CCL protos not being linked into the JS file built by webpack, which really only affects encryption and nothing else. We just need to thread that protobuf all the way through and then it'll work well.

**Comment by itsbilal** [comment]
Filed #81367 for the UI issue. This issue is now exclusively for the `cockroach debug encryption-active-key` issue, and is lower priority as `cockroach debug encryption-status` does a superset of the job and works.

**Comment by itsbilal** [comment]
Actually, seeing as #74331 exists for `encryption-active-key` and has more details, and `encryption-status` was never broken, I'm closing this issue in favour of that.
