### ISSUE TITLE
sql: add support for HTTP(s) connections

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#69146]
CockroachDB does not support database connections across HTTP(S). All database connections must be made via TCP. This is a tracking issue for adding support for HTTP connections.

We may pursue this in a variety of ways including https://github.com/cockroachdb/cockroach/issues/69010

**Comment by rafiss** [comment]
Is the intention to support sending SQL commands in an HTTP request body? This issue needs more details in the main description body.

**Comment by knz** [comment]
Is this an issue redundant with the PostGREST project?
cc @nvanbenschoten 

Also I don't understand why this is assigned to the server team

**Comment by otan** [comment]
i don't think the tech note really makes sense either?

https://github.com/cockroachdb/docs/pull/11083/files#r717039281

What brought this issue on? It doesn't seem like something we want anyway and want a third party (e.g. PostgREST) to support it.

**Comment by rafiss** [comment]
@awoods187  Is this referring to something like the Aurora Data API? https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html

I agree that the tech note as written needs to be clarified

**Comment by awoods187** [comment]
We can close this for now give the progress on PostgREST-- I was merely noting that PostgREST is only one way we could solve this need (we could also build our own connection like FaunaDB for example).
