### ISSUE TITLE
changefeedccl: make options values case insensitive

### ISSUE THREAD

**Issue by spiffyyeng** [cockroachdb/cockroach#69154]
Changefeed option values are currently case sensitive, as shown by the following `CREATE CHANGEFEED` statement:

```
CREATE CHANGEFEED FOR TABLE foo INTO 'kafka://localhost:9092' WITH format='JSON';
ERROR: unknown format: JSON
```
If some users misremember option values as being uppercase, it might save them a little bit of headache to not have to re-enter.
Easy implementation (just iterate through option values before evaluating and convert all to lowercase)

Also need to consider: which options will this not work for? i.e. `confluent_schema_registry` can't just be converted to lowercase since it has potential base64-encoded params which is case sensitive. 
(Note: may be safer to explicitly declare a list of options which we CAN convert to lowercase)

**Comment by spiffyyeng** [comment]
options that are case sensitive (that I can think of right now): 

- `confluent_schema_registry` (mentioned above)
- `kafka_sink_config`/`webhook_sink_config` (JSON unmarshalling names)
- `webhook_auth_header` (basic auth uses base64)

**Comment by shermanCRL** [comment]
Seconding your note above, we should look from the perspective of which _can_ be safely lowercased. `FORMAT` in this example is basically an enum, so we know all the possible values, and can determine that lowercasing is safe.

Also, we probably should not convert (mutate) any values, but rather make _comparison_ case-insensitive. Probably want this function: https://pkg.go.dev/strings#EqualFold

**Comment by spiffyyeng** [comment]
good point on the enums.

i think that a good list to start with is the following:

- `envelope`
- `format`
- `compression`
- `schema_change_events`
- `schema_change_policy`
- `on_error`
