### ISSUE TITLE
bazel: the list of event protos is defined redundantly in multiple places

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#69156]
This is a papercut that caused @THardy98 to waste a lot of time trying to figure what is wrong:

- in the `Makefile`-based approach, the list of event protos (from `eventpb`) is defined **once** and the common list is used to produce all derived artifacts: the json encoder, generated docs, channel go files etc.
- with bazel, we're seeing many instances of the list, *most of which are not auto-generated*. As a result, **it is much more error-prone** as someone can add the file in one location but forget it in another. I can see at least the following lists:
  - two manually-written `genrule` in `eventpb/BUILD.bzl`
  - a manually written list in `eventpb/PROTOS.bzl`
  - one manually wirtten `genrule` in `docs/generated`
  - there might be others, I am not sure

This overall structure is defective; we want to ensure that engineers only need **one step** to add a file and ensure all the bazel targets build properly.

Epic CRDB-8036

**Comment by knz** [comment]
cc @rickystewart for triage

**Comment by rickystewart** [comment]
The fact that we need to keep the list of protos sorted in this unpredictable order that you see in `pkg/util/log/eventpb/PROTOS.bzl` makes it impossible for us to use most of the techniques that Bazel would provide for DRY. If we could elide that requirement then we'd have more options. In the meantime, I'll look and see what other improvements can be made here.
