### ISSUE TITLE
backup/restore: add opt-out of delimiter-accelerated backup listing

### ISSUE THREAD

**Issue by amwolff** [cockroachdb/cockroach#69165]
**Describe the problem**

I was trying to restore a table from the backup from an S3-compliant storage provider.

**To Reproduce**

1. `RESTORE TABLE ... FROM 's3://.../?AWS_ACCESS_KEY_ID=...&AWS_SECRET_ACCESS_KEY=...&AWS_ENDPOINT=...' ...`
3. If the storage provider is, e.g. MinIO, the command will fail.

**Expected behavior**

The table restores from the backup as always.

**Additional data / screenshots**

n/a

**Environment:**

Restoring is broken since https://github.com/cockroachdb/cockroach/commit/50e89a0bf2a7043b38a85f9d853b3fe02acdb04f.

**Additional context**

Many S3 implementations do not support delimiters other than `/`. Since the above commit, `data/` delimiter is used. I believe that `/` would work here as well as `data/`, given the directory structure of CRDB backups.

gz#9557

Jira issue: CRDB-9475

**Comment by amwolff** [comment]
Hi @daniel-crlabs, @dt,

Sorry for the confusion. I was not aware MinIO fixed this already. I'm not sure if this affects anyone except us (Storj—we don't support non-/ delimiter) then, but if this would be enough to make this change:

> Maybe instead we should just make an opt-out, of using delimiter accelerated search at all, [...]

That would be fantastic. :)

**Comment by daniel-crlabs** [comment]
Thank you for the feedback, unfortunately I can not answer that question since I'm not a developer. I'll defer to them.

**Comment by dt** [comment]
Thanks for clarifying that this is still an issue @amwolff. Opting out of delimiter usage when searching seems simple enough -- for users with long enough backup chains, that could be pretty expensive, but expensive is probably preferable to broken. 

I've put this on our roadmap queue for prioritization, but please let us know if it is urgent.

**Comment by spiffytech** [comment]
I think this may be preventing restoring from backups stored on Backblaze B2.

```
my-user@free-tier.gcp-us-central1.cockroachlabs.cloud:26257/my-db> restore table defaultdb.* from 's3://my-bucket/backup-1?AWS_ACCESS_KEY_ID=xxxxx&AWS_SECRET_ACCESS_KEY=xxxxx&AWS_ENDPOINT=s3.us-west-002.backblazeb2.com' with into_db = 'my-db-restore';

ERROR: reading previous backup layers: failed to list s3 bucket: InvalidRequest: delimiter must be a one-character string
        status code: 400, request id: dbb22b713fc34955, host id: aMrliczWPZp4wEWWfOas57jFQZCNma2Vo
```
