### ISSUE TITLE
Surface an Active SQL Sessions metric

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#69206]
We have Open SQL Sessions as a metric which includes both idle and active sessions. We should surface a specific **Active** SQL Sessions metric and add a chart in the SQL metrics dashboard. This will help developers write or configure their applications or configure their clusters to follow best practices such as [connection pool sizing](https://www.cockroachlabs.com/docs/v21.1/connection-pooling#sizing-connection-pools). 

Related issue: https://github.com/cockroachdb/cockroach/issues/68530

Jira issue: CRDB-9490

**Comment by jordanlewis** [comment]
This is the same thing as currently active queries, so I think we should be go here as well.

**Comment by kevin-v-ngo** [comment]
Closing as not needed since we have `sql.statements.active`
