### ISSUE TITLE
sql: `SERIAL` behaves differently from PostgreSQL in `INSERT ... ON CONFLICT ... DO UPDATE SET col = DEFAULT`

### ISSUE THREAD

**Issue by ZhouXing19** [cockroachdb/cockroach#69208]
**Please describe the issue you observed, and any steps we can take to reproduce it:**

In an edge case under the `INSERT ... ON CONFLICT ... DO UPDATE` syntax, a `SERIAL` column behaves differently in CRDB and in PostgreSQL.

In CRDB, if we do

```
SET serial_normalization=sql_sequence

CREATE TABLE serial_t (
  a INT UNIQUE,
  d SERIAL
);

INSERT INTO serial_t (a) VALUES (1), (2), (3), (4);

INSERT INTO serial_t (a) VALUES (1) ON CONFLICT (a) DO UPDATE SET d=DEFAULT;
```
we get the table's content with

```
SELECT * FROM serial_t ORDERED BY a;
----
1  5
2  2
3  3
4  4
``` 
While in PostgreSQL 13.3, if we run the same requests (without the first `SET serial_normalization=sql_sequence` command), we get:

```
 a | d
---+---
 1 | 6
 2 | 2
 3 | 3
 4 | 4
```
A more subtle edge case is that in PostgreSQL, if it is a table with both a `GENERATED ... AS IDENTITY ` column and a `SERIAL`  column, then in `INSERT ... ON CONFLICT ... DO UPDATE` statement, the increment of these two columns is not very intuitive.

```
postgres=# CREATE TABLE generated_as_id_t (
  a INT UNIQUE,
  b INT GENERATED ALWAYS AS IDENTITY,
  c INT GENERATED BY DEFAULT AS IDENTITY,
  d SERIAL
);
CREATE TABLE
postgres=# INSERT INTO generated_as_id_t (a) VALUES (1), (2), (3), (4);
INSERT 0 4
postgres=# INSERT INTO generated_as_id_t (a) VALUES (1) ON CONFLICT (a) DO UPDATE SET b=DEFAULT;
INSERT 0 1
postgres=# SELECT * FROM generated_as_id_t;
 a | b | c | d
---+---+---+---
 2 | 2 | 2 | 2
 3 | 3 | 3 | 3
 4 | 4 | 4 | 4
 1 | 6 | 1 | 1
(4 rows)

postgres=# INSERT INTO generated_as_id_t (a) VALUES (1) ON CONFLICT (a) DO UPDATE SET d=DEFAULT;
INSERT 0 1
postgres=# SELECT * FROM generated_as_id_t;
 a | b | c | d
---+---+---+---
 2 | 2 | 2 | 2
 3 | 3 | 3 | 3
 4 | 4 | 4 | 4
 1 | 6 | 1 | 7
(4 rows)

postgres=# INSERT INTO generated_as_id_t (a) VALUES (1) ON CONFLICT (a) DO UPDATE SET b=DEFAULT;
INSERT 0 1
postgres=# SELECT * FROM generated_as_id_t;
 a | b | c | d
---+---+---+---
 2 | 2 | 2 | 2
 3 | 3 | 3 | 3
 4 | 4 | 4 | 4
 1 | 9 | 1 | 7
(4 rows)

postgres=# INSERT INTO generated_as_id_t (a) VALUES (1) ON CONFLICT (a) DO UPDATE SET d=DEFAULT;
INSERT 0 1
postgres=# SELECT * FROM generated_as_id_t;
 a | b | c | d
---+---+---+----
 2 | 2 | 2 |  2
 3 | 3 | 3 |  3
 4 | 4 | 4 |  4
 1 | 9 | 1 | 10
```

If possible, provide steps to reproduce the behavior:

I am using the single-node cockroachDB 21.1 server, and PostgreSQL 13.3 on MacOS.

I ran cockroachDB with:
```
cd ~/your/path/to/cockroachdb/cockroach
gmake buildshort
./cockroach demo
```

**Expected behavior**
In this `INSERT ... ON CONFLICT ... DO UPDATE SET col = DEFAULT` edge case, the `SERIAL` column is expected to behave the same in CRDB as in PostgreSQL.

**Comment by RaduBerinde** [comment]
In both CRDB and Postgres, sequences are allowed to have gaps in their observed values. There should be no expectation that we get the exact same values between CRDB and Postgres - both implementations "reserve the right" to skip values. 

From https://www.postgresql.org/docs/13/sql-createsequence.html:
> Because nextval and setval calls are never rolled back, sequence objects cannot be used if “gapless” assignment of sequence numbers is needed.
