### ISSUE TITLE
RESTORE: Restoring TableStats is slow/stuck

### ISSUE THREAD

**Issue by Nican** [cockroachdb/cockroach#69207]
**Describe the problem**

The restore command is not completing, even after hours of running. 
The database is ~1GB in size, has ~2000 ranges, and ~1000 tables.

**To Reproduce**

Run `restore from 'gs://backups/2021-08-20_1';` on a test node. 

1. The process was taking hours to run. 
2. The “Statments” tab on the UI, it shows that the Execution Count for “INSERT INTO system.table_statistics” is 1M+.
3. The stack trace for the restore command was stuck on the "insertStats" function.

**Expected behavior**
The restore command to finish after 5 minutes.

**Additional data / screenshots**
I deleted the `BACKUP-STATISTICS` file in the backup folder (4.7MB). `RESTORE` now completed successfully after 5 minutes.

**Environment:**
 - CockroachDB version: v21.1.7
 - Server OS: K8s to make a backup, and Docker to restore. 

**Additional context**
What was the impact?
Unable to restore backups. 

I have also created a forum post: https://forum.cockroachlabs.com/t/restore-is-taking-a-long-time/4775

![image](https://user-images.githubusercontent.com/796294/130300842-32297a70-62ae-4ee0-8fe0-224a8f1bf70e.png)

gz#9618

**Comment by adityamaru** [comment]
Hey @Nican apologies for the delay on this issue, a big thank you for looking into this so thoroughly. The debug zip doesn't seem to have the logs from the node. If you still have this issue readily reproducible would you be able to:

1. Try taking another debug zip while the restore is stuck, and attach it to the support issue.
2. Would you be willing to share the `BACKUP-MANIFEST` file with us to see if we can reproduce this on our side? You do not need to provide us with the actual `.sst` files that contain the data.

**Comment by Nican** [comment]
You can find the BACKUP-MANIFEST file here: http://ss.nican.net/2021-08-20_1_BACKUP_MANIFEST.gz 

The `COUNT` statement makes the connection get stuck.

**Comment by adityamaru** [comment]
@Nican I can't seem to access this link. It doesn't download a zip as I would expect. Could you upload the manifest to the support ticket linked above? - https://cockroachdb.zendesk.com/agent/tickets/9618

A debug zip while the count statement is stuck would be mighty too 😃

**Comment by Nican** [comment]
@adityamaru Apologies for that. I have replied to the zendesk ticket with the BACKUP_MANIFEST and the new debug zip. Can you please confirm?
(I made the mistake of not creating a zendesk account; I am not sure how to access it; I replied to the email with the files as attachment)

**Comment by adityamaru** [comment]
Perfect, I have them. I'll take a look!

**Comment by adityamaru** [comment]
@Nican I have a couple of theories, before I type up my findings would you be able to bump this cluster setting and try again. thanks!

`SET CLUSTER SETTING kv.transaction.max_intents_bytes = 4000000`

**Comment by Nican** [comment]
@adityamaru I created a new cluster, set the cluster setting, and then ran RESTORE again.

It looks to be stuck just the same way.
