### ISSUE TITLE
sql: make deterministic descriptor ID generation possible

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#69226]
**Is your feature request related to a problem? Please describe.**

Descriptor IDs are allocated by incrementing a constant key non-transactionally. This means that descriptor ID generation is non-deterministic in the face of transaction retries. This can be painful for logictests and tests in general which would like to depend on deterministic ID generation. Consider https://github.com/cockroachdb/cockroach/pull/69225. 

The generation occurs here: https://github.com/cockroachdb/cockroach/blob/b711b24258d9b75530b3f3b2ddf4cfcb5b857d6b/pkg/sql/catalog/catalogkv/catalogkv.go#L39-L44

**Describe the solution you'd like**

We should make an interface around descriptor ID generation and then plumb through an implementation of that interface. That may permit deterministic allocation. The wrinkle here is that we'd want such a thing to likely have a handle to a transaction, meaning that it'd likely need to be constructed with a transaction or add a transaction to the API.

**Describe alternatives you've considered**

We can keep hacking around flakes related to the assumed determinism. Another option is to randomize the allocation under testing to shake out any reliance on the determinism.

Jira issue: CRDB-9500

**Comment by postamar** [comment]
Doing this would unblock fixing https://github.com/cockroachdb/cockroach/issues/37751
