### ISSUE TITLE
sql: Metric to benchmark admission control

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/cockroach#69247]
As part of the admission control effort, we want to identify metrics(s) that would allow us to benchmark admission control.

Ideas proposed for a key result:

- overloaded TPC-C standard deviation of latency is X ms
- per-statement latency

Jira issue: CRDB-9512

**Comment by vy-ton** [comment]
fyi @jordanlewis @RaduBerinde, do we have an admission control project?

**Comment by RaduBerinde** [comment]
No, we've been using the A-admission-control label.
