### ISSUE TITLE
server: restarting a decommissioned node should result in the node shutting down and clearer errors

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#69245]
The experience when restarting a decommissioned node (at least a node that was decommissioned while dead; I haven't tried with a node decommissioned while live) is not great - the node is prevented for rejoining the cluster (good) but it's logs don't clearly say what's going on and the node appears to just hang.
The only clue about what's happening in the logs is:
```
W210823 16:47:21.213592 539 gossip/client.go:118 ⋮ [n5] 61  failed to start gossip client to ‹127.0.0.1:26263›: ‹initial connection heartbeat failed›: ‹rpc error: code = PermissionDenied desc = n5 was permanently removed from the cluster at 2021-08-23 15:59:56.503583893 +0000 UTC; it is not allowed to rejoin the cluster›
```
These messages are printed once per connection attempt to a different node (I think), and so you get a few copies of the message around startup time, and then you get a other periodic spammy messages obscuring the issue.

I'd like for the node to shut itself down instead of running as a zombie, and I'd like a clear error message talking about decommissioning at telling the user that the store dirs need to be wiped.

Jira issue: CRDB-9510

**Comment by knz** [comment]
@mwang1026 can you help assess impact/urgency and how it fits the roadmapping process.

**Comment by mwang1026** [comment]
cc @piyush-singh sorry I kinda punted on this one
