### ISSUE TITLE
sql: decide how ON UPDATE expressions should be copied when using CREATE TABLE LIKE

### ISSUE THREAD

**Issue by pawalt** [cockroachdb/cockroach#69258]
With ON UPDATE expressions implemented, we need to decide when they will be copied to tables created with LIKE. For example, DEFAULT expressions are only included when `INCLUDING DEFAULTS` or `INCLUDING ALL` is used. We need to decide:
- Should ON UPDATE expressions be copied over?
- What flags should be provided to copy ON UPDATE over?
- Should ON UPDATE expressions be included when specifying `INCLUDING ALL`?

Epic CRDB-9148

**Comment by otan** [comment]
i'd say copy them on INCLUDING DEFAULTS/ALL. Or introducing `INCLUDING ON UPDATES`?
