### ISSUE TITLE
sql: fix session_user to actually use session_user builtin

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#69268]
In #68973, we introduced `SET ROLE`.

However, `session_user` is incorrect when using `SET ROLE` -- it currently returns `current_user`. This is incorrect; it should really be `session_user`. However, fixing this in the parser would cause bad state during upgrade as the session_user function does not exist in v21.1.x.  To get around this, users must use `session_user()`.

As such, session_user is wrong in v21.2. After v21.2, we can move this builtin to `session_user` in the parser.

Epic CRDB-8948

**Comment by rafiss** [comment]
probably relates to however we fix https://github.com/cockroachdb/cockroach/issues/54696
