### ISSUE TITLE
sql: add cross-validation for ON UPDATE and GENERATED AS IDENTITY

### ISSUE THREAD

**Issue by pawalt** [cockroachdb/cockroach#69263]
With ON UPDATE expressions and GENERATED AS IDENTITY implemented, we need to add cross-validation in `validateColumns` to ensure that both ON UPDATE and GENERATED AS IDENTITY are not used on the same column. This is required because ON UPDATE has no meaning for a column that cannot be manually updated.

**Comment by ZhouXing19** [comment]
Closed by https://github.com/cockroachdb/cockroach/pull/68713
