### ISSUE TITLE
ui: overview looks garbled

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#6927]
Version (local build, no local modifications):
```
build:     beta-20160526-47-gd2db320 @ 2016/05/26 18:31:42 (go1.6.2)
admin:     http://cdo-cockroach.local:8080
sql:       postgresql://root@cdo-cockroach.local:26257?sslmode=disable
logs:      cockroach-data/logs
store[0]:  path=cockroach-data
```

Steps to repro:
1. `rm -rf cockroach-data && make install && cockroach start --insecure`
2. Go to admin UI

I see this:
![screenshot 2016-05-26 14 34 10](https://cloud.githubusercontent.com/assets/1564582/15585784/18e2bbda-234f-11e6-87e4-c2ccecc6967c.png)

Also tried `make clean` in top-level and `ui` directories before building, to no avail.

Not sure who to assign this to, so assigning to Max as a starting point. cc @tamird @mrtracy

**Comment by maxlang** [comment]
@tamird do you want to take this? I feel like this has something to do with bad data parsing for the axes Maybe because of `Long`s.

**Comment by maxlang** [comment]
Some values are straight up missing:

![screen shot 2016-05-26 at 3 30 56 pm](https://cloud.githubusercontent.com/assets/3691886/15587373/ed2e2bc0-2356-11e6-81af-e282707aca37.png)
