### ISSUE TITLE
sql: add mechanism to manually trigger dump of active queries

### ISSUE THREAD

**Issue by abarganier** [cockroachdb/cockroach#69307]
**Is your feature request related to a problem? Please describe.**
Currently, the DB Console UI provides a "Statements" page, powered by the `sqlstats` subsystem, which only shows statement statistics *after* the execution of that statement is complete. Current active queries however will not display on this page.

https://github.com/cockroachdb/cockroach/pull/66901 is in the process of adding a mechanism to dump active queries to a file when memory pressure is detected. It would be nice to also be able to manually trigger this data to create a durable record of active queries, which can be useful for operators/SREs for debugging purposes.

At a minimum, I propose providing a button to DB console, or a CLI command, to trigger the process of dumping active queries to a file. A more robust implementation could involve building a UI to display these active queries, although the cost/benefit of such a thing is up for debate.

Jira issue: CRDB-9538

**Comment by jordanlewis** [comment]
The Sessions page does already display currently active queries. Does that help with your idea?

**Comment by abarganier** [comment]
@jordanlewis I thought the same, but @Azhng noted in a [recent comment](https://github.com/cockroachdb/cockroach/pull/66901#pullrequestreview-736636164) on a PR that the statements page doesn't quite show *active* queries (is this correct?)

> "Statements" Page is currently powered by the sqlstats subsystem. Since we only record the statements statistics after the execution of that statement is complete, any active query will not show up in the "Statement" Page.

**Comment by Azhng** [comment]
@abarganier I think what @jordanlewis  is referring to is this line in the issue: 

> A more robust implementation could involve building a UI to display these active queries, although the cost/benefit of such a thing is up for debate.

Active queries are displayed in the Session Page. When the queries finish execution, it will no longer be present ion the Session Page and show up in Statement Page.

**Comment by abarganier** [comment]
Ah okay - sorry about that I think my incorrect terminology in my PR led to some confusion. It sounds like we have the desired functionality across both statements and sessions, therefore I'm going to close this issue.

Thanks again for clarifying!

**Comment by Azhng** [comment]
I think one thing to note that currently Session Page (unlike Statement Page) is not persisted anywhere. So if a node goes OOM then we would lose all the information on the active queries. 

Perhaps we would still want to have a button that does the dumping?

**Comment by abarganier** [comment]
Ah yes, I overlooked the fact that this information isn't persisted... I think from that perspective such a button could still be useful. 

Reopening the issue.
