### ISSUE TITLE
server: Consolidate serverpb.CollectedStatementStatistics

### ISSUE THREAD

**Issue by xinhaoz** [cockroachdb/cockroach#69326]
**Describe the problem**

Currently there are two CollectedStatementStatistics messages, one defined in `app_stats.proto` and the other in `status.proto` as `StatementsResponse_CollectedStatementStatistics`.

**Expected behavior**
There should only be one definition of CollectedStatementStatistics.

Jira issue: CRDB-9545

**Comment by maryliag** [comment]
No longer a priority
