### ISSUE TITLE
testing: Investigate using GoMock in place of custom mocking logic

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#6933]
We have a decent amount of custom code to deal with mocking objects in unit tests. We should investigate if some of this can be standardized/improved through the use of https://github.com/golang/mock. GoMock is a mocking framework that will codegen mock implementations of interfaces that can then be easily injected in tests.

**Comment by petermattis** [comment]
@nvanbenschoten Is this still something worth investigating?

**Comment by nvanbenschoten** [comment]
I don't think there are any pressing needs for this (unless @tamird disagrees), so I'll close for now.
