### ISSUE TITLE
CI pulls from npmjs registry upon every run and fails if npmjs reg is not available

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#69333]
Found by @tbg in e.g. https://teamcity.cockroachdb.com/viewLog.html?buildId=3346621&buildTypeId=Cockroach_UnitTests

```
npm ERR! network timeout at: https://registry.npmjs.org/validator/-/validator-10.11.0.tgz
```

This is a variation of #51543.

Epic DEVINF-109

Jira issue: CRDB-9548

**Comment by jlinder** [comment]
This was solved by https://github.com/cockroachdb/cockroach/pull/94152.
