### ISSUE TITLE
kvserver: investigate whether we can remove support for inline values from rangefeeds

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#69357]
Currently, no users of rangefeeds should ever see an inline value as they all operate on normal SQL tables.

If we were to run rangefeed on range with inline values, we have at least a few problems:

- Since inline values do not have associated timestamps, we currently emit all inline values encountered during a catchup scan, even if they have not changed since the given cursor.
- If the inline value changed multiple times since the checkpoint, a catchup-scan will only observe the final value.
- If a TBI is used for the catchup scan we may miss the inline value completely.

Do we have future uses for rangefeeds over ranges with inline values?

Jira issue: CRDB-9556

**Comment by erikgrinaker** [comment]
Confirmed, writing an inline value across a rangefeed span panics the node, so better to drop them explicitly:

```
panic: resolved timestamp 1654607236.262852282,0 equal to or above timestamp of operation {key:"\372\022i\000\001" timestamp:<> value:"l>&{\001\022"  <nil> <nil> <nil> <nil> <nil>} [recovered]
```
