### ISSUE TITLE
cdc, jobs: Throttle or jitter changefeed restarts

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#69365]
https://github.com/cockroachdb/cockroach/issues/69349, but for the whole job. If we have a bunch of changefeeds running, the cluster becomes unstable, the changefeeds might all restart at the same time, continually, adding more stress and inhibiting recovery. We should put in backoff with random waits, or something like that.

Jira issue: CRDB-9562

**Comment by ajwerner** [comment]
We added exponential backoff to jobs in 21.2. I think something we missed, and it's pretty glaring, is the ability to jitter these backoffs. I think if the backoff were jittered it would help with this immensely. Filed https://github.com/cockroachdb/cockroach/issues/69580.
