### ISSUE TITLE
tracing: export kvprober traces to a dedicated log file

### ISSUE THREAD

**Issue by dhartunian** [cockroachdb/cockroach#69427]
**Is your feature request related to a problem? Please describe.**
Currently, traces can only be exported wholesale to external tracing aggregation services. This makes it difficult to just look at traces from the kvprober which can more reliably pinpoint range-related issues.

**Describe the solution you'd like**
We would like to add the ability to export all kvprober traces to a dedicated log file. Similarly to the slow query log, this should be a separate file from the rest of the logs that collects all the kvprober logs and trace timings.

This feature should be gated with a cluster setting that enables or disables trace exporting to a file.

**Describe alternatives you've considered**
A more generalized tracing categorization/persistence method is too complex to design and build at the moment.
Exporting the traces to a 3rd party is a good idea but CC has no infra to send traces to ATM, and this will take time to build out, time no CC team has right now.

Jira issue: CRDB-9592

**Comment by joshimhoff** [comment]
https://github.com/cockroachdb/cockroach/pull/74404
