### ISSUE TITLE
kv: use header.TargetBytes for ExportRequest

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#69435]
Now that we don't have cloud-file writing anymore, it is confusing that `ExportRequest` has a `TargetFileSize` while its header also has `header.TargetBytes`, and _both_ need to be set, I believe, to paginate correctly? 

Instead, should we have all callers just put their desired response size in `header.TargetBytes` and deprecate the field in `ExportRequest`? I think we'd then just always set `reply.NumBytes` to `header.TargetBytes` since we always want, I think, for a caller to immediately get whatever file we produced instead of distsender trying to go back for more (but not much more, since it'll be - NumBytes) and waiting to stitch them into a multi-file reply for the caller.

Jira issue: CRDB-9595

Epic CRDB-19061

**Comment by erikgrinaker** [comment]
> I think we'd then just always set `reply.NumBytes` to `header.TargetBytes` since we always want, I think, for a caller to immediately get whatever file we produced instead of distsender trying to go back for more (but not much more, since it'll be - NumBytes) and waiting to stitch them into a multi-file reply for the caller.

This would be addressed by #70763, which can disable pagination to subsequent ranges with small limits.
