### ISSUE TITLE
sql: the structured events produced by  `handleTxnRowsGuardrails` are defective and not ready for use by external users

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#69477]
## Problem description

Found while reviewing #67934. The field names `Limit`, `ViolatesTxnRowsLimitErr` and `IsRead` in the user-facing JSON events for telemetry are quite poor and should all be changed before we release this.

Also the description for `ViolatesTxnRowsLimitErr` is very confusing and not human-friendly.

I have tried to read the code to understand it and find better words. I failed.

I was relatively disappointed to see that the code inside function `handleTxnRowsGuardrails` is mixing and matching incoherent concepts—or, rather, the concepts may be coherent but the English words chosen to describe them are incomprehensible for an external reader, which will make this difficult to maintain. Additionally, I find the control flow  _much_ too complex for what this code is trying to achieve, which makes this double difficult to understand/maintain.

## Suggested resolution

I think there are two different actions that need to be taken:

1. we need to remove the current public fields from the structured events. Right now the explanation for them is too complicated and the fields will thus be unfit for consumption, so they might as well not exist. We can replace them in another PR later.

2. we should clarify the code in `handleTxnRowsGuardrails` with adequate explanatory comments, and perhaps a different choice of words for the various variables. Once this is clarified, I predict we will discover better words for the telemetry events.

I'm available to help for point two.

**Comment by michae2** [comment]
Reopening as a release-blocker, because I would also like to commit #70157 to 21.2 to fix this.

**Comment by michae2** [comment]
This is now fixed in 21.1, 21.2, and master.
