### ISSUE TITLE
backupccl: allow restore of regional by row table into database with different regions and differently ordered enum members

### ISSUE THREAD

**Issue by mwang1026** [cockroachdb/cockroach#69505]
This is one we may not get to but putting in for completeness sake.

Our plan with https://github.com/cockroachdb/cockroach/issues/67269 is to allow `RESTORE` of `REGIONAL BY ROW` tables into a database where the regions match (or regions in the table are a subset of the database) and otherwise rejecting that RESTORE.

We may want in the future a version where you can restore with disjoint regions.

Epic CRDB-10350

Jira issue: CRDB-9627

**Comment by adityamaru** [comment]
This is going to be hard.

Currently, when we restore a UDT from a backup (MR and non-MR), we check to see if there exists a UDT with the same name in the target database. If we do not find a UDT, we task the restore with creating one. If we do find a UDT with the same name, we ensure that every enum member in the backed-up UDT has the same logical and physical representation in the existing UDT in the restoring cluster. The physical representation is computed based on the order in which the enum members were added to the enum on creation. So not only must their values be the same, but their ordering in the enum must also be the same. The physical representation of the enum member is what is written to the store for columns that use the UDT.

Following from the above explanation, if we want to restore a table that uses a UDT, but does not have the same physical representation as when it was backed up, we would have to mutate every key and value before ingesting it. Mutating a key has precedence. We have a `rekeyer` to switch the backed up table ID to the new, restoring table ID for every key before it is written to the destination cluster. Mutating a value to swap the backed up physical representation of the enum member, with the destination physical representation of the enum member is complex and error prone.

On discussion with @dt, supporting the restoration of a table using a non-restored UDT is like implementing `IMPORT TABLE ... FROM BACKUP DATA <path-to-backup>`. Then we could do something similar to how CSV Imports convert the enum member string, to a datum and, finally a KV. This would directly solve the issue when it comes to the ordering of enum members, but would also allow us to do some sort of in-place substitution of backed up region x with restoring region y.

**Comment by mwang1026** [comment]
More and more it seems like IMPORT ... FROM BACKUP DATA is going to be valuable regardless
