### ISSUE TITLE
roachperf: remove bad data item from restore2TB/nodes=10

### ISSUE THREAD

**Issue by pbardea** [cockroachdb/cockroach#69575]
The restore2TB/nodes=10 roachtest has a bad data item (see graph below). This skews the y-axis and makes it harder to see finer grained performance differences. We should remove this bad datum.

<img width="870" alt="Screen Shot 2021-08-30 at 10 23 36 AM" src="https://user-images.githubusercontent.com/507390/131354665-13066ab8-1fd4-4a3f-b34b-3456dbedb392.png">

Jira issue: CRDB-9667

**Comment by adityamaru** [comment]
our restore roachtests have changed significantly so no action is necessary
