### ISSUE TITLE
sql: enable SQL Audit Log for the entire database 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#69574]
Currently, the [SQL Audit Log](https://www.cockroachlabs.com/docs/v21.1/sql-audit-logging.html) is per table:
```SQL
ALTER TABLE customers EXPERIMENTAL_AUDIT SET READ WRITE;
```
Some customers would prefer if the SQL Audit Log captured every statement in the database. This could be done by adding it automatically to every table or by creating a separate log for all SQL activity. 

Jira issue: CRDB-9666

**Comment by rafiss** [comment]
This is resolved by https://github.com/cockroachdb/cockroach/pull/101658
