### ISSUE TITLE
kvserver: memory monitor and improve buffering in rangefeed catchup scans

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#69596]
**Describe the problem**

The catchup scan can use a substantial amount of memory as it iterates over KVs that need to be output.  This memory is not currently connected to any memory monitor and grows without bound throughout a catchup-scan.

https://github.com/cockroachdb/cockroach/blob/a0bfc856413168120df4346f5861d5da90a55a7b/pkg/kv/kvserver/rangefeed/registry.go#L299
https://github.com/cockroachdb/cockroach/blob/a0bfc856413168120df4346f5861d5da90a55a7b/pkg/kv/kvserver/rangefeed/registry.go#L309

Jira issue: CRDB-9679

**Comment by mwang1026** [comment]
@stevendanna just wanted to confirm you're working on this and the KV team involvement is review / just tracking progress

**Comment by stevendanna** [comment]
@mwang1026 My plan is to work a bit on this in the near term and then also advocate for some more work on rangefeed's to be explicitly part of CDC's 22.1 plan in some way (rtsIter improvements is another one I had an eye towards). For all Rangefeed work, I imagine we would need KV's expertise to review changes and potentially talk through larger changes before they happen.

**Comment by amruss** [comment]
@stevendanna can we close this issue?
