### ISSUE TITLE
jobs: hide automatic jobs from the UI

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#69611]
**Describe the problem**

We currently hide the `AUTO STATS CREATION JOB` from the UI by explicitly excluding it from here: https://github.com/cockroachdb/cockroach/blob/e2cd3ae015c1f86d188ace3650db2ea622ec58b4/pkg/server/admin.go#L1840. 

We've recently added other automatic jobs, such as the `AUTO SPANCONFIG RECONCILIATION` JOB. It makes sense to hide this and other automatic jobs that may be added going forward from the UI as well by tweaking the query linked above. 

Jira issue: CRDB-9684

**Comment by arulajmani** [comment]
There is a question around the `SQL STATS COMPACTION` job and if it should be hidden -- it isn't marked as an automatic job, but maybe we should be hiding that too? cc @Azhng

**Comment by Azhng** [comment]
Seems to me like a reasonable thing to implement for `SQL STATS COMPACTION` job. 

cc: @kevin-v-ngo

**Comment by arulajmani** [comment]
Separately, should the `SQL STATS COMPACTION` job be marked automatic? Doing so will mean that it'll not be included in the output to `SHOW JOBS`. It'll be in the output of `SHOW AUTOMATIC JOBS` instead (much like the `AUTO STATS JOB` and `AUTO SPANCONFIG RECONCILIATION` job). 

@Azhng what do you think? The change itself should be simple -- you need to add it to this list: https://github.com/cockroachdb/cockroach/blob/3786bb6bfcfd4cd8c26df4b370250bb17b6fc58a/pkg/jobs/jobspb/wrap.go#L74. and fix whatever tests that fallout after the change.
