### ISSUE TITLE
kvnemesis: support non-transactional DelRange operations

### ISSUE THREAD

**Issue by AlexTalks** [cockroachdb/cockroach#69642]
Currently `DelRange` operations are only generated inside of transactions in kvnemesis.  We should also add support for these operations outside of transactions, if we can determine a way to validate the delete on each key atomically without relying on the timestamp of the transaction to identify the stored delete tombstones that were written by the operation.

Jira issue: CRDB-9701

**Comment by tbg** [comment]
Relevant snippet

https://github.com/cockroachdb/cockroach/blob/6ee6501ccce85a0a9ed416f61ba2feab35478e96/pkg/kv/kvnemesis/validator.go#L383-L416
