### ISSUE TITLE
sql: add effective sample rate field to the sampled query event

### ISSUE THREAD

**Issue by THardy98** [cockroachdb/cockroach#69653]
**Is your feature request related to a problem? Please describe.**
Currently, the sampled query event does not provide any means to determine its effective sample rate (i.e. it cannot be determined how often the event is emitted/sampled relative to how many queries are actually executed). Consequently, it is difficult to determine insight as to how the event is being represented in the log.

**Describe the solution you'd like**
A simple solution would be to add a counter to detect the number of events that have *not been emitted* since the *last emitted event*.
A value of 0 would indicate an effective sample rate of 1 (i.e. full representativity).
Values >0 would indicate an effective sample rate of: 1 / (number of not emitted events + 1)

**Additional context**
I have left `TODO(thardy98)` where code changes need to be made.

**Comment by thtruo** [comment]
I've confirmed with the Data team that it is sufficient to report the count of unsampled queries. That way, as consumers of data, we can tell how many queries were not sampled through telemetry.

So it's not necessary for us to report the actual effective sampling rate. The count of unsampled queries meets our requirements.

cc @knz based on our conversations. Would you prefer a new GH issue to help address this change, or is it enough to track off of this one?

**Comment by knz** [comment]
this one is good.
