### ISSUE TITLE
release: v21.2.0-alpha.1

### ISSUE THREAD

**Issue by abarganier** [cockroachdb/cockroach#69657]
Candidate SHA: [`c1ef81f5f435b3cc5bdf8b218532e0779f03a6bf`](https://github.com/cockroachlabs/release-staging/commit/c1ef81f5f435b3cc5bdf8b218532e0779f03a6bf)
Deployment status: `Qualifying`
Make and Publish Build: [#1215](https://teamcity.cockroachdb.com/buildConfiguration/Internal_Release_MakeAndPublishBuild/3389522)
Qualify Build: [#926](https://teamcity.cockroachdb.com/buildConfiguration/Internal_Release_Qualify/3389721)
Publish Cockroach Release: WIP EDIT ME WIP.
 
Working Tags:
- Build ID:  [`v21.2.0-alpha.00000000-3811-gc1ef81f5f4 `](https://github.com/cockroachlabs/release-staging/releases/tag/v21.2.0-alpha.00000000-3811-gc1ef81f5f4)
- `staging-v21.2.0-alpha.1`
 
[Release process checklist](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process)
 
Prep date: `WIP fill in date to roll out: usually Monday, a week before the release WIP`
- [x] [2. Pick a SHA](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-2.PickaSHA)
- [x] fill in `Candidate SHA` above
- [x] fill in `staging-* Tag` above (alpha/beta only)
- [x] fill in `Build ID` above
- [x] fill in `Make and Publish Build` above
- [x] fill in `Qualify Build` above
 
- [x] [3. Announce the release to releases@](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-3.Announcethereleasetoreleases@)
- [x] [4. Ask SRE to run the build on some CC clusters](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-4.AskSREtorunthebuildonsomeCCclusters)
 
5-8: Qualify the Release. See [Release Qualification](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification)
- Short-running Checks:
- [x] [5-8. Verify node crash reports](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification#Verify-node-crash-reports-appear-in-sentry.io)
 
**Do not proceed below until the release date.**
 
Release date: `WIP fill in date: usually Monday WIP`
- [ ] [9. Publish Cockroach Release](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-9.PublishTheRelease)
- [ ] Acked security@ and release-engineering-team@ on the generated AWS S3 bucket write alert to confirm these writes were part of a planned release (See [Publish Cockroach Release](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-9.PublishTheRelease) for details).
- [ ] [10. Check binaries](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-10.CheckBinaries)
- [ ] [11. Remove staging branch / tags from repository](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-12.Removestagingbranch/tags)
- [ ] [12. Announce the release is cut to releases@](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-13.Announcethereleaseiscuttoreleases@)
- [ ] [13. Update version numbers](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-14.Updateversionnumbers)
- For production or stable releases in the latest [major release](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Knowifthereleaseisonthelatestmajorreleaseseries) series only (in August 2020, this is the v20.1 series):
- [ ] Update [Brew Recipe](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Brewrecipe)
- [ ] Update [Orchestrator configurations:CRDB](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Orchestratorconfigurations:CRDB)
- [ ] Update [Orchestrator configurations:Helm Charts](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Orchestratorconfigurations:HelmCharts)
- For all production or stable releases:
- [ ] Create a ticket in the [Dev Inf tracker](https://cockroachlabs.atlassian.net/wiki/spaces/devinf/pages/429097164/Submitting+Issues+Requests+to+the+Developer+Infrastructure+team) to update the Red Hat Container Image Repository as outlined in https://github.com/cockroachlabs/cockroach-redhat-deploy/blob/main/README.md.
- [ ] *After docs are updated* [Announce version to registration cluster](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-AnnounceVersionToRegCluster)
- [ ] [Update version map in bin/roachtest (all stable releases) and regenerate test fixtures (only major release)](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Updateversionmapinroachtestandregeneratetestfixtures)
- [ ] 14. Update docs (handled by Docs team)
- [ ] 15. External communications for release (handled by Marketing team)
 
Cleanup:
 
- [ ] Remove staging branch / tags from repository

**Comment by celiala** [comment]
Cancelled
