### ISSUE TITLE
Add SHOW CREATE SCHEMA and SHOW CREATE DATABASE

### ISSUE THREAD

**Issue by electrum** [cockroachdb/cockroach#69660]
For example, if I have a regional database, it would be nice to see the SQL that would be used to create it.

Jira issue: CRDB-9710

**Comment by SupornoChaudhury** [comment]
Hey, I would like to help with this. Can I get more details on it?

**Comment by fanglee101** [comment]
[b]https://icq.im/AoLGnKtUsQZKGmUTjTA

https://t.me/chinadebitbank


This is arqidarknet from

torre,zorldcard, market pro,

I sell first hand pos data,atm datas,resellers welcome,
usable pos,atm 

bank logs,email access,password
RDP
hack bibbles
Cvv=address
eu-usa-asia


minimum order is  10pieces 

no test for new clients* consideration could be consider on basis.

[/b]


**
![photo_2021-10-06_08-41-11](https://user-images.githubusercontent.com/92568711/137448282-b775bba5-71d2-42ca-9bc0-53d366cffd78.jpg)
**

**Comment by alimoosavi** [comment]
@electrum 
I am new to cockroach project and this issue seems attractive to me , please assign this issue to me.

**Comment by rafiss** [comment]
Sorry for the noise all, I'm removing the `good first issue` label from this, since we actually have more details to decide about how this should work. In the meantime, v21.2 has the `SHOW CREATE ALL TABLES` command, and v22.1 will have the `SHOW CREATE ALL SCHEMAS` command, which may help here.

**Comment by rafiss** [comment]
cc @devadvocado for awareness

**Comment by postamar** [comment]
I just checked `SHOW CREATE DATABASE` and `SHOW CREATE ALL SCHEMAS` exist now, but `SHOW CREATE SCHEMA` doesn't.

**Comment by rafiss** [comment]
there's no schema-level configuration that would come from a `CREATE SCHEMA` command, so I don't see much value in implementing `SHOW CREATE SCHEMA`.

I personally feel like the existing `SHOW` commands cover what we'd need, so I'm going to close this. However, if anyone can point out a different use case and share some examples if what would be useful, please comment and re-open.
