### ISSUE TITLE
workload: tpcc with `--simple` errors

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#69678]
When running `tpcc` with simple, I see this in the logs:

```
E210827 12:56:00.566817 1 workload/cli/run.go:521  [-] 841  error in newOrder: Cannot encode []interface {} in simple protocol - []interface {} must implement driver.Valuer, pgtype.TextEncoder, or be a native type
```

This was done by reverting whatever is in https://github.com/cockroachdb/cockroach/issues/69471.

**Comment by otan** [comment]
(cc @rafiss i'm guessing it's `pgx.QuerySimpleProtocol(true)`)

**Comment by rafiss** [comment]
perhaps. that's supposed to be handled here: https://github.com/jackc/pgx/blob/5320ad87c845b5ce1d8485af5b36a0c67deb9224/conn.go#L572-L582

 but i will investigate that further
