### ISSUE TITLE
ui: Invalid or missing fields on statements page

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#69675]
**Describe the problem**

I was running some multi-region TPC-C test and noticed that there's some strange behaviour going on with the statments page.  In the image below, you can see that the network usage field reports 0 B, but this update statement is going cross-node, so that doesn't seem accurate.   Additionally, the Last execution time is suspect and the Nodes/Regions field is empty.

<img width="952" alt="Screen Shot 2021-08-31 at 9 58 00 PM" src="https://user-images.githubusercontent.com/18447034/131599704-1fac041a-2f0f-4a38-9b9a-16723e200ba9.png">

**To Reproduce**

Here's the repro script:

```
#!/bin/bash
TIMESTAMP="$(date +"%N")"

#roachprod create storm-test -n 16 --gce-preemptible --gce-zones 'us-east4-a','us-east4-b','us-east4-c','us-east4-c','us-west2-a','us-west2-b','us-west2-c','us-west2-
c','us-central1-a','us-central1-b','us-central1-c','us-central1-c','northamerica-northeast1-a','northamerica-northeast1-b','northamerica-northeast1-c','northamerica-n
ortheast1-c' 2>&1 | tee tpcc-4-regions-$TIMESTAMP-create.out
roachprod create storm-test -n 16 --gce-zones 'us-east4-a','us-east4-b','us-east4-c','us-east4-c','us-west2-a','us-west2-b','us-west2-c','us-west2-c','us-central1-a',
'us-central1-b','us-central1-c','us-central1-c','northamerica-northeast1-a','northamerica-northeast1-b','northamerica-northeast1-c','northamerica-northeast1-c' 2>&1 |
 tee tpcc-4-regions-$TIMESTAMP-create.out
roachprod stage $CLUSTER cockroach 2>&1 | tee tpcc-4-regions-$TIMESTAMP-stage-cockroach.out
roachprod stage $CLUSTER workload 2>&1 | tee tpcc-4-regions-$TIMESTAMP-stage-workload.out
roachprod start $CLUSTER:1-3 2>&1 | tee tpcc-4-regions-$TIMESTAMP-start-us-east4.out
roachprod start $CLUSTER:5-7 2>&1 | tee tpcc-4-regions-$TIMESTAMP-start-us-west2.out
roachprod start $CLUSTER:9-11 2>&1 | tee tpcc-4-regions-$TIMESTAMP-start-us-central-a.out
roachprod start $CLUSTER:13-15 2>&1 | tee tpcc-4-regions-$TIMESTAMP-start-northamerica-northeast1-a.out
roachprod ssh $CLUSTER:13 "./workload init tpcc --warehouses=40 --partitions=4 --survival-goal zone --regions=us-east4,us-west2,us-central1,northamerica-northeast1 {p
gurl:1}" 2>&1 | tee tpcc-4-regions-$TIMESTAMP-init.out
echo sleeping for 10 minutes to allow replication to stabilize...
sleep 700
roachprod ssh $CLUSTER:4 "./workload run tpcc --warehouses=40 --duration=10m --wait=true --partitions=4 --partition-affinity=0 --tolerate-errors {pgurl:1-3} --surviva
l-goal zone  --regions=us-east4,us-west2,us-central1,northamerica-northeast1" 2>&1 | tee tpcc-4-regions-$TIMESTAMP-run-us-east4.out &
roachprod ssh $CLUSTER:8 "./workload run tpcc --warehouses=40 --duration=10m --wait=true --partitions=4 --partition-affinity=1 --tolerate-errors {pgurl:5-7} --surviva
l-goal zone --regions=us-east4,us-west2,us-central1,northamerica-northeast1" 2>&1 | tee tpcc-4-regions-$TIMESTAMP-run-us-west2.out &
roachprod ssh $CLUSTER:12 "./workload run tpcc --warehouses=40 --duration=10m --wait=true --partitions=4 --partition-affinity=2 --tolerate-errors {pgurl:9-11} --survi
val-goal zone --regions=us-east4,us-west2,us-central1,northamerica-northeast1" 2>&1 | tee tpcc-4-regions-$TIMESTAMP-run-us-central1.out &
roachprod ssh $CLUSTER:16 "./workload run tpcc --warehouses=40 --duration=10m --wait=true --partitions=4 --partition-affinity=3 --tolerate-errors {pgurl:13-15} --surv
ival-goal zone --regions=us-east4,us-west2,us-central1,northamerica-northeast1" 2>&1 | tee tpcc-4-regions-$TIMESTAMP-run-northamerica-northeast1.out &
echo sleeping...
sleep 700
roachprod destroy $CLUSTER
```

While the run is proceeding, navigate to the statements page and look search for "UPDATE WAREHOUSE".

**Comment by ajstorm** [comment]
Adding this to the SQL Observability board.  Missed this when I opened this issue.

**Comment by Azhng** [comment]
`NetworkBytes` is part of the execution statistics, so this means that the field will be left as empty until the statement is being sampled via tracing.

**Comment by Azhng** [comment]
The PR address the issue for `Last Execution At`. @kevin-v-ngo , I think for `NetworkBytes` we should display `unavailable` instead of  `0 B` so it's not so confusing for the user.

**Comment by Azhng** [comment]
Also cc @Annebirzin

**Comment by Azhng** [comment]
The missing Nodes information should have been fixed by #69702.

**Comment by Azhng** [comment]
Reopen since this issue is not completely resolved.

**Comment by Annebirzin** [comment]
@Azhng we could use the 'unavailable' label with a tooltip (we follow this same pattern on the Serverless overview page) ([Figma](https://www.figma.com/file/MoSPFkEyJfGipCmQvvLg1a/21.2_SQL-obsrv_query-performance?node-id=3366%3A53458))

![Screen Shot 2021-09-16 at 11 43 38 AM](https://user-images.githubusercontent.com/51920721/133643355-34ce3604-1dd4-4efc-8bd5-299f8d64515d.png)

Thinking the tooltip copy can be something like: 
`This metric is part of the statement execution and therefore will not be available until the statement is sampled via tracing.`

cc @kevin-v-ngo @ianjevans
