### ISSUE TITLE
kvserver: TestConcurrencyManagerBasic/wait_self failure

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#69687]
**Describe the problem**

On a development branch, we saw the following test failure:

```
=== RUN   TestConcurrencyManagerBasic/wait_self
    concurrency_manager_test.go:93:
        testdata/concurrency_manager/wait_self:123:
        output didn't match expected:
        @@ -2,6 +2,7 @@
         [4] sequence reqTxn2: lock wait-queue event: done waiting
         [4] sequence reqTxn2: conflicted with 00000003-0000-0000-0000-000000000000 on "k" for 1.234s
         [4] sequence reqTxn2: acquiring latches
         [4] sequence reqTxn2: scanning lock table for conflicting locks
         [4] sequence reqTxn2: sequencing complete, returned guard
        +[4] sequence reqTxn2: blocked on select in concurrency_test.(*cluster).PushTransaction

    --- FAIL: TestConcurrencyManagerBasic/wait_self (0.16s)
```

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_Test/3388783?buildTab=overview&expandedTest=build%3A%28id%3A3388783%29%2Cid%3A184657&logFilter=debug

I haven't yet ruled out the changes on the branch under test as it has not yet reproduced for me either on master or on the branch.

Jira issue: CRDB-9723

**Comment by stevendanna** [comment]
As a note, this is reproducible using `make stress` but it takes a long time. I triggered it after 250k iterations.

**Comment by ajwerner** [comment]
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_GitHubCiOptional/5346728?buildTab=overview&showRootCauses=false&expandBuildProblemsSection=true&expandBuildTestsSection=true&expandBuildChangesSection=true
