### ISSUE TITLE
migrations: TestSeparatedIntentsMigration is very slow

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#69689]
This test takes ~150s on a corporate MacBook (with their sluggish, intercepted IO), and about 30s on a beefy linux host. 

It looks like it is using on-disk stores which probably explains the slowdown when running with intercepted IO, but the 30s under CI is still quite slow. It looks like the test is Sleep()'ing for 10/5/.5 seconds in various places, which we almost always try to avoid, instead adding knobs to block until the specific needed action has completed.

**Comment by ajwerner** [comment]
One oddity that I haven't been able to figure out is why the test does not work if we switch it to use a `StickyInMemoryEngine` instead of a real one. It seems to not find the interleaved intents.

**Comment by ajwerner** [comment]
cc @itsbilal

**Comment by ajwerner** [comment]
I figured it out. https://github.com/cockroachdb/cockroach/pull/69694

**Comment by itsbilal** [comment]
The reason why we use an on-disk store is because at the time of writing the test, sticky engines stayed open when a node was restarted. That has since changed, so we can do this. Thanks @ajwerner
