### ISSUE TITLE
cli: `debug merge-logs` output is always colorized

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#69692]
In #66629, `debug merge-logs` output was colorized. However, this appears to be colorized even when the output is not going to a TTY, e.g. with `debug merge-logs > combined.log`. This makes it very hard to inspect the logs in an editor, due to all of the ANSI color codes.

**Comment by aliher1911** [comment]
It would be nice if it could also be overridden by command line switch, because `cockroach debug merge-logs | less -R` could render ANSI colours for viewing, but the output is not a TTY. And printing logs directly to a TTY is not even a common case.

**Comment by knz** [comment]
> It would be nice if it could also be overridden by command line switch, because cockroach debug merge-logs | less -R could render ANSI colours for viewing, but the output is not a TTY. And printing logs directly to a TTY is not even a common case.

if the utility was using the standard logging facility, then this would be possible by specifing the logging output format manually.
