### ISSUE TITLE
sql: combination of user defined schemas, enum and foreign key causes database to not be droppable

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#69713]
Trying to drop a database that includes a table in a user defined schema referenced in a foreign key causes the following error:
dropping test database failed: pq: error resolving referenced table ID %d: descriptor is being dropped

Reproduction:
```
CREATE DATABASE test;
USE test;
CREATE SCHEMA s;
CREATE TYPE s.testenum AS ENUM ('foo', 'bar', 'baz');
CREATE TABLE test.s.pg_indexdef_test (
    a INT PRIMARY KEY,
    e s.testenum
);
CREATE TABLE test.s.pg_constraintdef_test (
  a int,
  FOREIGN KEY(a) REFERENCES test.s.pg_indexdef_test(a) ON DELETE CASCADE
);
DROP DATABASE test;
```

This results in `ERROR: error resolving referenced table ID 65: descriptor is being dropped`

**Comment by fqazi** [comment]
This was an ordering bug inside drop database cascade, we drop the schema first followed by collected objects under the schema next. As a result, when we are dropping tables, we may need to look up type descriptors, which will need access to the schema again which will be dropped. The fix here is simple we should drop the schema *after* any collected objects
