### ISSUE TITLE
sql: remove experimental from auto re-homing on update setting name

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#69726]
The setting to enable the feature in the context of creating regional by row tables was merged with the string experimental. We want this setting to not contain experimental. Instead, we will mark docs as experimental. This is to prevent us from needing to maintain/users from adjusting their application if we move this setting out of experimental status.

cc @ajstorm @ajwerner  

Jira issue: CRDB-9744

**Comment by arulajmani** [comment]
FWIW @otan just merged https://github.com/cockroachdb/cockroach/pull/69626, which adds another cluster setting/session variable pair that allows us to control if the `rehome_row()` builtin will actually get executed.
