### ISSUE TITLE
changefeedccl: implement sampling of telemetry data for create changefeed event

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#69721]
We should take advantage of the new logging [telemetry structure](https://cockroachlabs.atlassian.net/browse/CC-4110) to enhance the telemetry data we collect about changefeed usage. 

The sql team has already started using the new logging stream: https://github.com/cockroachdb/cockroach/pull/67934 

See (https://docs.google.com/spreadsheets/d/1xR45gzoA4wazLmO28CfIOpOyaCbAOwcsB7TO5dvx_rA/edit#gid=1609822523) for more details

We would ideally like to log the following fields:

General fields:
- eventtype
- crdb_version
- cluster_type
- cluster_creation
- cluster_id
- node_id
- instance_id
- tenant_id
- organization_id
- internal
- sampling_rate
- severity_numeric
- severity

Changefeed info:
- changefeed_type
- num_ranges
- job_id

Feature usage:
- sink_type
- num_tables
- topic_prefix
- tls_enabled
- ca_cert
- client_cert
- client_key
- sasl_enabled
- sasl_mechanism
- sasl_user
- sasl_password
- file_size
- insecure_tls_skip_verify
- updated
- resolved
- envelope
- cursor
- format
- confluent_schema_registry
- key_in_value
- diff
- compression
- protect_data_from_gc_on_pause
- schema_change_events
- schema_change_policy
- scan
- full_table_name
- avro_schema_prefix

Epic CRDB-9742

Jira issue: CRDB-9741

**Comment by miretskiy** [comment]
@samiskin any updates on this? Can it ibe closed?

**Comment by samiskin** [comment]
Closed by https://github.com/cockroachdb/cockroach/pull/79513
