### ISSUE TITLE
ui/next: document how to use it (for development)

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#6974]
I tried to look at #6973, but couldn't figure out how to actually open up the new UI and wasn't able to figure it out on my own.

`make build` doesn't serve `/next/` (500)
`make uidebug` serves `/next/`, but completely fails to load `system.js` (since it's looking at my local tree and wants `./jspm_packages/system.js`, but that whole folder isn't there and also not created by `make` or `go generate ./...`.

`ui/README.md` refers to `make debug`, which should be `make uidebug`.

**Comment by tamird** [comment]
Yeah, you need to `make -C ui/next jspm.installed`

On Tue, May 31, 2016 at 1:37 PM, Tobias Schottdorf <notifications@github.com

**Comment by tschottdorf** [comment]
Just checked again and the instructions still don't seem to cover it all. There are repeated references to `make debug` (I believe that refers to `make uidebug`) and I don't think I got the information above from the ui README. Seems like a trivial fix for someone who knows how it works.

**Comment by maxlang** [comment]
This should be fixed as of #7602. Thanks @tamird !
