### ISSUE TITLE
[WAIOps 3.1.1] : zen-metastoredb-2 pod is in CrashLoopBackOff 

### ISSUE THREAD

**Issue by BonnieKris** [cockroachdb/cockroach#69753]
**Describe the problem**
After installation of CP4WAIOps 3.1.1, the `zen-metastoredb-2` pod is in CrashLoopBackOff status.

```cmd
[root@cp4wa-inf /]# oc get pods -A | egrep -v "1/1|2/2|3/3|4/4|Running|Completed"
NAMESPACE                                          NAME                                                              READY   STATUS             RESTARTS   AGE
cp4waiops                                          zen-metastoredb-2                                                 0/1     CrashLoopBackOff   101        24h
```
And the log is 
[zen-metastoredb-2.log](https://github.com/cockroachdb/cockroach/files/7098152/zen-metastoredb-2.log)

**Expected behavior**
This pod is running without errors.

Jira issue: CRDB-9766

**Comment by yuzefovich** [comment]
There is a problem with clock synchronization
```
F210902 10:09:24.949836 206 server/server.go:297  [n?] clock synchronization error: this node is more than 1s away from at least half of the known nodes (0 of 1 are within the offset)
```
I don't think the issue as actionable by CRDB folks - it's up to users to ensure that clocks are in sync.
