### ISSUE TITLE
geo spatial: st_intersects(geography::point, geography::point) may have bad performance

### ISSUE THREAD

**Issue by jievince** [cockroachdb/cockroach#69761]
```
func singleRegionIntersects(aRegion s2.Region, bRegion s2.Region) (bool, error) {
	switch aRegion := aRegion.(type) {
	case s2.Point:
		switch bRegion := bRegion.(type) {
		case s2.Point:
			return aRegion.IntersectsCell(s2.CellFromPoint(bRegion)), nil
```
To check if a point intersects with another point, it make a s2 cell via `CellFromPoint`, and then uses the s2 function `func (p Point) IntersectsCell(c Cell)`.
Converting a point to a cell is expensive.  Why not just call `func (p Point) ContainsCell(c Cell) bool` directly? 
Because only if the two points are equal, they intersects.
@otan

**Comment by otan** [comment]
feel free to submit a PR :)

**Comment by otan** [comment]
ah wait, that doesn't work:

```

// ContainsCell returns false as Points do not contain any other S2 types.
func (p Point) ContainsCell(c Cell) bool { return false }
```

contains does not mean intersects unfortunately.

**Comment by otan** [comment]
oh! unless you meant

```
// Contains reports if this Point contains the other Point.
// (This method matches all other s2 types where the reflexive Contains
// method does not contain the type's name.)
func (p Point) Contains(other Point) bool { return p == other }
```

**Comment by jievince** [comment]
> oh! unless you meant
> 
> ```
> // Contains reports if this Point contains the other Point.
> // (This method matches all other s2 types where the reflexive Contains
> // method does not contain the type's name.)
> func (p Point) Contains(other Point) bool { return p == other }
> ```

Yes, I mean this one.

**Comment by otan** [comment]
ok, https://github.com/cockroachdb/cockroach/pull/69762

**Comment by otan** [comment]
thanks for the heads up!
