### ISSUE TITLE
geo spatial: st_intersects(geography, geography) has abnormal result

### ISSUE THREAD

**Issue by jievince** [cockroachdb/cockroach#69760]
**Describe the problem**
st_intersects behave differently in geography and geometry when the args are a linestring and a point.

**To Reproduce**

```
select st_intersects(st_geogfromtext('linestring(0 0, 1 1, 2 2)'), st_pointfromtext('point(0.5 0.5)')::geography);
  st_intersects
-----------------
      false
```

```
select st_intersects(st_geomfromtext('linestring(0 0, 1 1, 2 2)'), st_pointfromtext('point(0.5 0.5)')::geometry);

  st_intersects
-----------------
      true
```

**Expected behavior**
both return true

**Additional data / screenshots**
I am reading the source code of cockroach.
I find it use `func (p *Polyline) IntersectsCell(cell Cell) bool` to check if a linestring intersects with a cell, while this function is named as `bool S2Polyline::MayIntersect(const S2Cell& cell)` in the C++ s2 library. Seems it's not accurate.
BTW, I find `arangodb` doesn't support st_intersects a linestring with a point(geography version).
```
bool ShapeContainer::intersects(ShapeContainer const* cc) const {
  switch (cc->_type) {
    case ShapeContainer::Type::S2_POINT: {
      if (_type == ShapeContainer::Type::S2_POLYLINE ||
          _type == ShapeContainer::Type::S2_MULTIPOLYLINE) {
        THROW_ARANGO_EXCEPTION_MESSAGE(TRI_ERROR_NOT_IMPLEMENTED,
            "The case GEO_INTERSECTS(<polyline>, <point>) is numerically instable and thus not supported.");
      }
      S2Point const& p = static_cast<S2PointRegion*>(cc->_data)->point();
      return _data->Contains(p);  // same
    }
```
@otan

**Comment by jievince** [comment]
To determine whether a point intersects a line is  indeed to determine whether a point is on the line.
For gemetry, we could use math formula to check it easily.
But for geography, it seems a little hard

**Comment by otan** [comment]
This is expected. `point(0.5 0.5)` is now halfway between `linestring(0 0, 1 1)` because of the curvature of the earth. This is the same result in PostGIS:

```
otan=# select st_intersects(st_geogfromtext('linestring(0 0, 1 1, 2 2)'), st_pointfromtext('point(0.5 0.5)')::geography);
 st_intersects
---------------
 f
(1 row)

otan=#
```

**Comment by jievince** [comment]
My  fault, I missed it's on sphere.

**Comment by jievince** [comment]
I think it's still not proper to call `IntersectsCell(cell Cell)`.

Because check if a linestring intersects a point means check if the point is on the linestring, and so means check if the linestring contains the points.
```
// ContainsCell reports whether this Polyline contains the given Cell. Always returns false
// because "containment" is not numerically well-defined except at the Polyline vertices.
func (p *Polyline) ContainsCell(cell Cell) bool {
	return false
}

// ContainsCell reports whether this Polyline contains the given Cell. Always returns false
// because "containment" is not numerically well-defined except at the Polyline vertices.
func (p *Polyline) ContainsCell(cell Cell) bool {
	return false
}
```

**Comment by otan** [comment]
intersectscell is fine. we allow 1cm of leeway to consider things intersecting, which it will cover - this is in the contract of the docs.

**Comment by jievince** [comment]
> intersectscell is fine. we allow 1cm of leeway to consider things intersecting, which it will cover - this is in the contract of the builtin and is in the docs.

Got it, thanks. Seems  it‘s more practical  by tolerating a little error for geography
