### ISSUE TITLE
New Prometheus Metric Related to CPU Utilization Per Core

### ISSUE THREAD

**Issue by brad-crl** [cockroachdb/cockroach#69808]
**Is your feature request related to a problem? Please describe.**
In order to be able to "see the trees in the forest" it would make a direct path to solving all sorts of CPU utilization-related investigations, be they latency issues, node expansion/contraction issues, etc.  Right now, when observing CPU utilization graphs, the node-level metrics are the most useful.  Currently, the displayed metric is always the **_average_** value of the CPU utilization, and as the scale of an implementation increases, a single value well outside the norm will have no significant effect on the average, and everything "looks fine" when in fact, there is a pinpoint value "hiding" inside that is a gaiting factor. 
Having a readily available core-level CPU Utilization metric of some type will be highly useful in order to add into the monitoring and evaluation dashboards.

**Describe the solution you'd like**
The desire overall is to have access to a core-level CPU Utilization metric that would be reasonably easy to directly address in Prometheus.  Trying not to limit the output in this request so as to avoid limiting the general usefulness of this metric in applying its result to future, as-yet-even-thought-about presentations, the current goal in mind is to consider the maximum value seen across all cores.  When such a value is plotted against the average seen on all nodes (a presentation that already exists at a number of sites around the world), it could at least be readily apparent whether any "outliers" (both hot-spot and under-utilization conditions) exist that would require investigation, before making conclusions and strategies for node maintenance purposes.

**Describe alternatives you've considered**
One alternative to having direct access in Prometheus is to write a monitoring program that would dynamically detect and work across all currently configured systems, and then perform, collect and calculate the vectors according to the need at hand.  

**Additional context**
Since there's already a "handle" in Prometheus that understands the dynamics of the running CockroachDB configuration, this request is not a new implementation of the node-level CPU metric, but rather an extension to such.  In this way, it could lead to approaches of investigation of P99-related latency, and likely be useful internally to recognition of relationships to other metrics that would reveal themselves over time.  

Jira issue: CRDB-9805

gz#13632

**Comment by andreimatei** [comment]
You can see per-node CPU utilization in Prometheus today. This issue is asking for per-core tracking, but that's an unusual thing. Cores are fungible and work gets moved by the OS from core to core transparently - so, for example, a "pinned core" does not actually look like a single core working at 100% over a long time; it looks like different cores working at 100% for seconds each. Even if we could produce per-core metrics, I doubt they'd be useful...

**Comment by NigelNavarro** [comment]
Your assessment is correct, and the confusion around the Feature Request ask is my mistake. This old request appeared to be similar in request to another request discovered recently with another customer, and as a result, I inadvertently conflated these two requests when in reality they should be separate. I'll rework my ask into a new FR. My apologies on this.

**Comment by andreimatei** [comment]
closing this but feel free to reopen if there's something to be done
