### ISSUE TITLE
geo spatial: Why doesn't polylineIntersectsPolyline directly call s2 function func (p *Polyline) Intersects(o *Polyline) bool?

### ISSUE THREAD

**Issue by jievince** [cockroachdb/cockroach#69807]
s it because of performance or accuracy?
@otan

**Comment by otan** [comment]
guess we could've. we do the bounding box check earlier anyway (before the expensive EWKB -> S2 conversion) and the implementation is the same.

please use the community slack channel for questions and not issues. there is a #spatial channel in https://go.crdb.dev/p/slack. thanks!
