### ISSUE TITLE
In a K8s deployment, scaling stateful set to 2 results in immediate "dead" status

### ISSUE THREAD

**Issue by mgoddard** [cockroachdb/cockroach#69856]
In a K8s deployment using a stateful set (https://raw.githubusercontent.com/cockroachdb/cockroach/master/cloud/kubernetes/bring-your-own-certs/cockroachdb-statefulset.yaml) deployment, when I remove one of the three nodes, like this:

```kubectl scale sts cockroachdb --replicas=2```

I instantly get 1 node showing up as dead.  I expect it to show up as suspect for 5 minutes and then,
after the 5 minutes has elapsed, to be reported as "dead" (in DB Console).  During the 5 minute window, CRDB shows the two good nodes as live in grey and the one bad node as live in yellow which means it's not updating its liveness record; you can verify this if you look at Advanced Debug -> All Nodes -> look at the "Updated At" column.

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

```
gcloud container clusters create cockroachdb --machine-type n2-standard-4 --region us-west1 --num-nodes 1
gcloud container clusters resize cockroachdb --node-pool default-pool --num-nodes 4 --region us-west1
kubectl create clusterrolebinding user-cluster-admin-binding --clusterrole=cluster-admin --user=user@cockroachlabs.com

mkdir certs my-safe-directory
cockroach cert create-ca --certs-dir=certs --ca-key=my-safe-directory/ca.key
cockroach cert create-client root --certs-dir=certs --ca-key=my-safe-directory/ca.key
kubectl create secret generic cockroachdb.client.root --from-file=certs
cockroach cert create-node localhost 127.0.0.1 cockroachdb-public cockroachdb-public.default cockroachdb-public.default.svc.cluster.local *.cockroachdb *.cockroachdb.default *.cockroachdb.default.svc.cluster.local --certs-dir=certs --ca-key=my-safe-directory/ca.key
kubectl create secret generic cockroachdb.node --from-file=certs

curl -O https://raw.githubusercontent.com/cockroachdb/cockroach/master/cloud/kubernetes/bring-your-own-certs/cockroachdb-statefulset.yaml
kubectl create -f cockroachdb-statefulset.yaml
kubectl exec -it cockroachdb-0 -- /cockroach/cockroach init --certs-dir=/cockroach/cockroach-certs

kubectl create -f https://raw.githubusercontent.com/cockroachdb/cockroach/master/cloud/kubernetes/bring-your-own-certs/client.yaml
kubectl exec -it cockroachdb-client-secure -- ./cockroach sql --certs-dir=/cockroach-certs --host=cockroachdb-public -e "CREATE USER roach WITH PASSWORD 'roach';GRANT admin TO roach;"

kubectl apply -f crdb-lb.yaml
```

Then, I removed one node by scaling the StatefulSet:

```
kubectl scale sts cockroachdb --replicas=2
```

And the DB Console immediately reports the node as dead.  I will upload a screenshot of that if possible after creating this issue.

**Expected behavior**

I expected the node to show as "suspect" until the default 5 minute period passed, then see it reported as "dead".  When I did this using version 21.1.5 of CockroachDB, I observed the expected behavior.

**Environment:**
 - CockroachDB version 21.1.7, and I also saw this with 21.1.6
 - Server OS: K8s / Docker image

**Additional context**
This is impacting a project I am working on.

**Comment by mgoddard** [comment]
![image](https://user-images.githubusercontent.com/632648/132352432-8d32602c-d96e-4689-9889-9cf5cf074f1d.png)

**Comment by mgoddard** [comment]
Here is what I expected (this is using CockroachDB version 21.1.5):
![image](https://user-images.githubusercontent.com/632648/132352602-3c677ad8-5a43-412a-8094-a163b472fd4e.png)

**Comment by knz** [comment]
Cc @dhartunian for triage

**Comment by knz** [comment]
ok this is a variant of #70015. I'll modify that linked issue

**Comment by knz** [comment]
dup #70015
