### ISSUE TITLE
sql: EXPERIMENTAL_RELOCATE syntax for range IDs or system ranges

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#69854]
During e.g. troubleshooting or end-to-end testing it would sometimes be useful to move system ranges or leases around (e.g. the meta range r1 or the liveness range r2). `ALTER TABLE ... EXPERIMENTAL_RELOCATE` should in principle be able to do this, but the syntax only supports SQL tables, and these ranges do not map onto SQL constructs. We should consider adding syntax that targets a specific range ID instead of a table/primary key.

Related to #63386.

**Comment by knz** [comment]
NB:

1. we already have `ALTER RANGE ... CONFIGURE ZONE`, so we could do `ALTER RANGE ... RELOCATE` similarly.

2. these system ranges do not contain SQL rows. So it's not sensical to reuse the same syntax as for tables, where it's possible to select which rows (or ranges thereof) get relocated. So the syntax for system ranges should use something else, for example `ALTER RANGE ... RELOCATE ALL`.

   NB: some of the system ranges do contain multiple sub-ranges. we'll probably want to identify those too, but this may not need to occur in a first iteration.

3. we'll want to also support the VOTERS / NON VOTERS variants.

**Comment by andreimatei** [comment]
Dupe of https://github.com/cockroachdb/cockroach/issues/54971 ? @erikgrinaker , consider consolidating.

**Comment by erikgrinaker** [comment]
Indeed, my bad -- missed that issue.
