### ISSUE TITLE
stability: kv inconsistency in beta cluster

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6985]
History:
- was running sha `8ceb16b`
- two nodes crashed overnight from OOM: node 2 `104.196.0.165` and 5 `104.196.40.130`
- restarted both nodes, then waited a while (no issues after ~30 minutes)
- attempted to freeze cluster (unsuccessfully, it never terminated)
- rolling upgrade to sha `5f666c8`

within minutes, both nodes 2 and 4 `104.196.5.28` crashed with kv inconsistency:
```
E160601 13:02:43.924766 storage/replica_command.go:1822  replica: range=1171 [/System/"tsd\x12cr.node.txn.durations-1h-p99.999\x00\x01\x89\xf8\x064\xdc3"-/System/"tsd\x12cr.node.txn.durations-1h-p99.999\x00\x01\x89\xf8\x064\xdc4"), checksum mismatch: e = 3fe5c00d7c5846eda47b65d8f62328baf4e85fee81f30ea59104e51e42e12df8fdc36ed26f4fdbdb075a25295a2b4d8442c83b62a220002a28192ed1b29a37ca, v = bd7366c035df555de0931487f8b85cf4eb9c9b0faab8f0a787a9407fb3df454cf6ba5c664c1e4b3887be71c03e5c526d1a566efe1255d3bc71c14d2307f3bfa9
E160601 13:02:44.122238 storage/replica_command.go:1812  inconsistent k:v = (/Local/RangeID/1171/r"lgc-" (/Local/RangeID/1171/r"lgc-"), 0.000000000,0, 120408001000180020002800320933c2d5ce0308001000) not present on replica
E160601 13:02:44.122293 storage/replica_command.go:1812  inconsistent k:v = (/Local/RangeID/1171/r/RangeStats (/Local/RangeID/1171/r/RangeStats), 0.000000000,0, 120408001000180020002800327a81e4323a0309ebb8acb41af7531411000000000000000019000000000000000021b3f6b6020000000029b3f0ffffffffffff316a93fdffffffffff39b3f0ffffffffffff414963b9020000000049b3f0ffffffffffff51000000000000000059000000000000000061bd1e000000000000692400000000000000) not present on replica
E160601 13:02:44.122320 storage/replica_command.go:1812  inconsistent k:v = (/Local/RangeID/1171/r/RangeStats (/Local/RangeID/1171/r/RangeStats), 0.000000000,0, 120408001000180020002800327a02b6bed10309ebb8acb41af7531411000000000000000019000000000000000021b3f6b6020000000029b3f0ffffffffffff316a93fdffffffffff39b3f0ffffffffffff414963b9020000000049b3f0ffffffffffff510000000000000000590000000000000000619b1e000000000000692300000000000000) not present on leader
F160601 13:02:44.122346 storage/replica_command.go:1822  replica: range=1171 [/System/"tsd\x12cr.node.txn.durations-1h-p99.999\x00\x01\x89\xf8\x064\xdc3"-/System/"tsd\x12cr.node.txn.durations-1h-p99.999\x00\x01\x89\xf8\x064\xdc4"), checksum mismatch: e = 1033f09e83409c92ac81ac8f26b9eac3342cd3d8289716e0d084ffa40d88b6697fa6c5e5b47b07c42e7bc3e064cdd50a245407549772a1be6d08ad2c7c5bad62, v = d73005b54dd96b3369586defed661c2df4e14fd4e1b3b11488e4bc620fc458f9de931dba3b25aae925a9f19b03e26726c5db79a95e0099483e8775b503d5a976
```

**Comment by tschottdorf** [comment]
This is due to to https://github.com/cockroachdb/cockroach/pull/6831/files. I didn't think of the migration when I LGTM'ed that.

**Comment by mberhault** [comment]
crap. I guess a freeze wouldn't have helped here?

**Comment by tschottdorf** [comment]
It should have.

**Comment by mberhault** [comment]
ok. I did try it, but it never terminated, even after a long long time.

I'll restart the nodes without panic on consistency failures. Then I can try the freeze again and gather some details for you.

**Comment by bdarnell** [comment]
OK, so what now? It doesn't sound like requiring freeze is a viable option for this week's beta. It sounds like the problem will be self-correcting in that the next GC after the cluster is fully upgraded will make everything consistent. Do we just disable the panic and allow the change, or should we back out #6831?

**Comment by mberhault** [comment]
The panic is off by default, so if things will clean themselves up, I don't
see too much of a downside. We should be careful about this though.

**Comment by tschottdorf** [comment]
There's nothing lost by backing out the change now. Since we're apparently
opposed to stop-the-world upgrades, I think the correct thing to do is to
back it out, but we will have the same problem next week, when @mjibson
will likely try to get follow-up work in. So we need a fundamental decision
about these types of "hopefully self-healing" migrations. To me, definitely
feels like taking chances week over week to not advise openly for a
stop-the-world migration.

On Wed, Jun 1, 2016 at 11:29 AM marc <notifications@github.com> wrote:

> The panic is off by default, so if things will clean themselves up, I don't
> see too much of a downside. We should be careful about this though.
>
> On Wed, Jun 1, 2016 at 11:27 AM, Ben Darnell <notifications@github.com>
> wrote:
>
> > OK, so what now? It doesn't sound like requiring freeze is a viable
> option
> > for this week's beta. It sounds like the problem will be self-correcting
> in
> > that the next GC after the cluster is fully upgraded will make everything
> > consistent. Do we just disable the panic and allow the change, or should
> we
> > back out #6831 <https://github.com/cockroachdb/cockroach/pull/6831>?
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/cockroachdb/cockroach/issues/6985#issuecomment-223029384
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AFoMqOIWn6DsnQBJSc1mJN8WFB3Jcjxhks5qHaTjgaJpZM4IriN3
> >
> > .
> >
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/6985#issuecomment-223030105>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE135BvrhIIRD0a2JkrzJx078yjB0Gsfks5qHaVagaJpZM4IriN3>
> .
>
-- 

-- Tobias

**Comment by bdarnell** [comment]
I'd be fine with recommending a freeze-cluster upgrade for this if it worked, but @mberhault says it didn't work so we have some more debugging to do there.

**Comment by mjibson** [comment]
Do all replicas of a range run a GC with identical timestamps? Or does each replica handle its own GC timings?

**Comment by tschottdorf** [comment]
The leader builds the GC command, but since it applies through Raft, all Replicas will be in sync (in the absence of a rolling restart migration which changes the version as the commands apply).

**Comment by mjibson** [comment]
If that's so, then what happened to cause one replica to have the `lgc-` key and another to not?

**Comment by tschottdorf** [comment]
Because the command was committed, but not applied by the same version of the binary due to the rolling restart. I.e. the GC was sitting on Node1, marc replaces the binary, rebooted and then it applied, so it wrote the key. Some other node applied it with the old version, so it didn't write the key.

**Comment by mjibson** [comment]
Ah. I thought we required upgrades to not have that kind of version skew? For example https://www.cockroachlabs.com/docs/beta-20160512.html has a notice about that.

**Comment by tschottdorf** [comment]
That's not enough, unfortunately. We need to freeze the cluster to guarantee this doesn't happen.

**Comment by mjibson** [comment]
Oh I think I see now. We need to do a freeze before taking down a cluster because otherwise a command may only partially distribute? I'm unaware of the distinction between commit and apply. I thought everything happened to a quorum or not, even with possible version upgrades during that.

**Comment by tschottdorf** [comment]
Correct. Commands are committed on a quorum, but the state machine may lag in executing them (as you can easily picture, a node in the minority may not even learn about the command until a day later when its log catches up).

**Comment by bdarnell** [comment]
I'm leaning towards leaving the change in for this week. It may take us a while to sort out the issues with freezing and I don't think it's worth holding back this change and everything that depends on it. We should, however, make freezing a regular part of our own update process so we can work the kinks out before we recommend it to the rest of the world.

**Comment by tschottdorf** [comment]
Fine by me. Marc, any logs from the freeze-gone-wrong? I should add pretty
aggressive logging about it (for example on every FrozenStatus executed).

On Wed, Jun 1, 2016 at 4:44 PM Ben Darnell <notifications@github.com> wrote:

> I'm leaning towards leaving the change in for this week. It may take us a
> while to sort out the issues with freezing and I don't think it's worth
> holding back this change and everything that depends on it. We should,
> however, make freezing a regular part of our own update process so we can
> work the kinks out before we recommend it to the rest of the world.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/6985#issuecomment-223118876>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE135PaTKIwrxs-uw04FeJ9hMoGcefXkks5qHe9GgaJpZM4IriN3>
> .
>
-- 

-- Tobias

**Comment by bdarnell** [comment]
I filed #7038 to track the freeze-cluster issues. For this issue, we should make sure that the inconsistencies are in fact healing themselves as the GC queue is rerun, (which appears to be the case, unless I'm looking in the wrong place for the logs) and turn the consistency checker back on.

**Comment by tamird** [comment]
Consistency checker is now on AFAIK, which I believe leaves nothing to do here.
