### ISSUE TITLE
release-21.1: one-way version upgrade on release branch (released in 21.1.8)

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#69874]
Patch releases are expected to maintain upgrade/downgrade/mixed-version compatibility, so a user can upgrade from 21.1.3 to 21.1.7 and back down to 21.1.5 at will.

However a recent change from the master branch [was backported to release-21 ](https://github.com/cockroachdb/cockroach/blob/57b7968be0e1c8e6cb1523ab01df886afef2a2ea/pkg/clusterversion/cockroach_versions.go#L530-L531)that included a new cluster version (21.1-124), which was then included in the 21.1.8 release. This means a cluster that deploys 21.1.8 (and has the default automatic finalization enabled) will be unable to downgrade to 21.1.7 or earlier.

**Comment by knz** [comment]
@dt this has been fixed, right?
