### ISSUE TITLE
stability: node considers itself offline

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6988]
I got a decent OOM on `gamma`.

Basic summary:
- two nodes OOMed died at 160601 08:26 UTC: nodes 3 (`104.196.98.24`) and 5 `104.196.41.218`
- running sha: `8ceb16b` (jemalloc build)

I'll focus on node 3 since they both seem to have a similar issue. I'll dig some more and see if I can find any differences.

Memory usage for the last 2 minutes or so:

```
I160601 08:24:06.803848 server/status/runtime.go:160  runtime stats: 10 GiB RSS, 220 goroutines, 428 MiB active, 56130.93cgo/sec, 1.42/0.39 %(u/s)time, 0.00 %gc (1x)
I160601 08:24:16.810454 server/status/runtime.go:160  runtime stats: 11 GiB RSS, 217 goroutines, 841 MiB active, 168613.56cgo/sec, 2.12/0.41 %(u/s)time, 0.01 %gc (6x)
I160601 08:24:26.820533 server/status/runtime.go:160  runtime stats: 11 GiB RSS, 207 goroutines, 937 MiB active, 113486.88cgo/sec, 2.24/0.47 %(u/s)time, 0.01 %gc (3x)
I160601 08:24:36.804101 server/status/runtime.go:160  runtime stats: 11 GiB RSS, 229 goroutines, 1.3 GiB active, 81174.44cgo/sec, 1.24/0.45 %(u/s)time, 0.00 %gc (0x)
I160601 08:24:46.804469 server/status/runtime.go:160  runtime stats: 11 GiB RSS, 210 goroutines, 1.2 GiB active, 118643.64cgo/sec, 1.64/0.46 %(u/s)time, 0.00 %gc (1x)
I160601 08:24:56.806125 server/status/runtime.go:160  runtime stats: 11 GiB RSS, 206 goroutines, 1.8 GiB active, 117680.71cgo/sec, 1.59/0.52 %(u/s)time, 0.00 %gc (0x)
I160601 08:25:06.825476 server/status/runtime.go:160  runtime stats: 12 GiB RSS, 226 goroutines, 2.0 GiB active, 114088.96cgo/sec, 1.97/0.55 %(u/s)time, 0.00 %gc (2x)
I160601 08:25:16.806662 server/status/runtime.go:160  runtime stats: 12 GiB RSS, 212 goroutines, 2.5 GiB active, 103004.13cgo/sec, 1.89/0.49 %(u/s)time, 0.00 %gc (0x)
I160601 08:25:26.807712 server/status/runtime.go:160  runtime stats: 13 GiB RSS, 209 goroutines, 1.8 GiB active, 99631.47cgo/sec, 1.83/0.52 %(u/s)time, 0.00 %gc (1x)
I160601 08:25:36.808927 server/status/runtime.go:160  runtime stats: 13 GiB RSS, 201 goroutines, 2.2 GiB active, 97037.33cgo/sec, 1.62/0.51 %(u/s)time, 0.00 %gc (0x)
I160601 08:25:46.807511 server/status/runtime.go:160  runtime stats: 13 GiB RSS, 203 goroutines, 2.7 GiB active, 91514.35cgo/sec, 1.61/0.45 %(u/s)time, 0.00 %gc (0x)
I160601 08:25:56.808688 server/status/runtime.go:160  runtime stats: 13 GiB RSS, 206 goroutines, 3.1 GiB active, 102094.44cgo/sec, 1.42/0.50 %(u/s)time, 0.00 %gc (0x)
I160601 08:26:06.814718 server/status/runtime.go:160  runtime stats: 13 GiB RSS, 207 goroutines, 2.6 GiB active, 87945.26cgo/sec, 1.60/0.45 %(u/s)time, 0.00 %gc (1x)
I160601 08:26:16.823233 server/status/runtime.go:160  runtime stats: 14 GiB RSS, 216 goroutines, 3.6 GiB active, 112414.24cgo/sec, 1.50/0.63 %(u/s)time, 0.00 %gc (0x)
I160601 08:26:26.841688 server/status/runtime.go:160  runtime stats: 14 GiB RSS, 215 goroutines, 4.1 GiB active, 115542.16cgo/sec, 1.52/0.53 %(u/s)time, 0.00 %gc (0x)
```

Heap profiles don't show anything unusual:
cgo heap (at 08:26) is 6.5GiB between `ReadBlockContents` and `UncompressBlockContents`
[node3.cgo.heap.pdf](https://github.com/cockroachdb/cockroach/files/293605/node3.cgo.heap.pdf)

go heap (at 08:26:32) is 1.58GiB in `storage.Snapshot`, out of a total of 1.75GiB.
[node3.go.heap.pdf](https://github.com/cockroachdb/cockroach/files/293615/node3.go.heap.pdf)

The basic math is obviously off: memory stats show go memory of 4.1GiB active vs 1.75GiB accounted for by the heap profiler, and total of 14GiB RSS vs 1.75+6.5=8.25GiB accounted for by both heap profilers. Some is probably in mmapped stuff, but we're still missing at least a few gigs.

Finally, we do seem to have a long running snapshot. Grepping through the goroutines dump, I'm seeing the following snapshots:

```
$ grep -w storage.snapshot goroutine.20160601-082*
goroutine.20160601-082241:github.com/cockroachdb/cockroach/storage.snapshot(0x7f9d441cdec0, 0xc8415bb6c0, 0x76c, 0x1, 0xc82623d8c0, 0x36, 0x40, 0x0, 0x0, 0x0, ...)
goroutine.20160601-082308:github.com/cockroachdb/cockroach/storage.snapshot(0x7f9d441cdec0, 0xc82841f920, 0x661, 0x1, 0xc836c4fc40, 0x36, 0x40, 0x0, 0x0, 0x0, ...)
goroutine.20160601-082313:github.com/cockroachdb/cockroach/storage.snapshot(0x7f9d441cdec0, 0xc8304b2010, 0x61b, 0x1, 0xc8332e1800, 0x35, 0x40, 0x0, 0x0, 0x0, ...)
goroutine.20160601-082329:github.com/cockroachdb/cockroach/storage.snapshot(0x7f9d441cdec0, 0xc83ee23f20, 0x609, 0x1453e7fa5dd17301, 0xc836baaac0, 0x36, 0x40, 0x0, 0x0, 0x0, ...)
goroutine.20160601-082334:github.com/cockroachdb/cockroach/storage.snapshot(0x7f9d441cdec0, 0xc827792cc0, 0x4fe, 0x1, 0xc8324e9740, 0x36, 0x40, 0x0, 0x0, 0x0, ...)
goroutine.20160601-082339:github.com/cockroachdb/cockroach/storage.snapshot(0x7f9d441cdec0, 0xc829db1d20, 0x5c, 0x1453e806dd79bc01, 0xc8209c3c00, 0x35, 0x40, 0x0, 0x0, 0x0, ...)
goroutine.20160601-082345:github.com/cockroachdb/cockroach/storage.snapshot(0x7f9d441cdec0, 0xc829db1d20, 0x5c, 0x1453e806dd79bc01, 0xc8209c3c00, 0x35, 0x40, 0x0, 0x0, 0x0, ...)
goroutine.20160601-082350:github.com/cockroachdb/cockroach/storage.snapshot(0x7f9d441cdec0, 0xc831d95650, 0x230, 0xc84a304b01, 0xc8207d2280, 0x36, 0x40, 0x0, 0x0, 0x0, ...)
goroutine.20160601-082411:github.com/cockroachdb/cockroach/storage.snapshot(0x7f9d441cdec0, 0xc82435e4b0, 0x7, 0x1453e80bf324a901, 0xc820327958, 0x1, 0x8, 0x0, 0x0, 0x0, ...)
goroutine.20160601-082416:github.com/cockroachdb/cockroach/storage.snapshot(0x7f9d441cdec0, 0xc82435e4b0, 0x7, 0x1453e80bf324a901, 0xc820327958, 0x1, 0x8, 0x0, 0x0, 0x0, ...)
....
goroutine.20160601-082623:github.com/cockroachdb/cockroach/storage.snapshot(0x7f9d441cdec0, 0xc82435e4b0, 0x7, 0x1453e80bf324a901, 0xc820327958, 0x1, 0x8, 0x0, 0x0, 0x0, ...)
goroutine.20160601-082628:github.com/cockroachdb/cockroach/storage.snapshot(0x7f9d441cdec0, 0xc82435e4b0, 0x7, 0x1453e80bf324a901, 0xc820327958, 0x1, 0x8, 0x0, 0x0, 0x0, ...)
```

This means that we were still generating a snaphot for range 7 (the third argument is the range ID) after 2 minutes.

Latest goroutine dump:
[node3.goroutines.txt](https://github.com/cockroachdb/cockroach/files/293658/node3.goroutines.txt)

Latest log file:
[node3.stderr.gz](https://github.com/cockroachdb/cockroach/files/293659/node3.stderr.gz)

**Comment by bdarnell** [comment]
A note on node IDs: I think you're counting zero-based node IDs. The failed nodes are 4 and 6, not 3 and 5.

The raft log for range 7 is enormous, but unlike #6879 the range has been replicated. The log contains 10M entries and the last raft log GC was at position 2.7M. The oldest entry in the raft log has a timestamp from may 26. 

Range descriptor history (the latest timestamp is 08:23 UTC, 3 minutes before the OOM): 
```
1464769392.798098618,0 /Local/Range/"\xbb"/RangeDescriptor: [/Table/51, /Table/52)
        Raw:range_id:7 start_key:"\273" end_key:"\274" replicas:<node_id:6 store_id:6 replica_id:5 > replicas:<node_id:4 store_id:4 replica_id:4 > replicas:<node_id:1 store_id:1 replica_id:7 > next_replica_id:8 

1464769227.239426719,0 /Local/Range/"\xbb"/RangeDescriptor: [/Table/51, /Table/52)
        Raw:range_id:7 start_key:"\273" end_key:"\274" replicas:<node_id:6 store_id:6 replica_id:5 > replicas:<node_id:4 store_id:4 replica_id:4 > next_replica_id:7 

1464107649.741586209,0 /Local/Range/"\xbb"/RangeDescriptor: [/Table/51, /Table/52)
        Raw:range_id:7 start_key:"\273" end_key:"\274" replicas:<node_id:6 store_id:6 replica_id:5 > replicas:<node_id:3 store_id:3 replica_id:6 > replicas:<node_id:4 store_id:4 replica_id:4 > next_replica_id:7 
```

The changes here are a remove followed by an add, which means this is a repair and not a rebalance. The node removed is range 3. Node 3's logs are quiet at this time (just the runtime stats spam; the node hasn't crashed), so it's unclear why the other nodes would consider it dead. Just *after* the other nodes OOM we see these messages, but I think that's an effect and not the cause:

```
I160601 08:27:51.865471 gossip/server.go:185  refusing gossip from node 2 (max 3 conns); forwarding to 5 ({tcp cockroach-gamma-5:26257})
I160601 08:27:54.001710 server/status/runtime.go:160  runtime stats: 8.9 GiB RSS, 10526 goroutines, 798 MiB active, 0.00cgo/sec, 0.20/0.01 %(u/s)time, 0.00 %gc (0x)
W160601 08:27:56.151672 gossip/gossip.go:901  partition in gossip network; attempting new connection
I160601 08:27:56.161930 gossip/gossip.go:923  starting client to cockroach-gamma-2:26257
I160601 08:27:56.165637 gossip/client.go:88  closing client to cockroach-gamma-2:26257: rpc error: code = 2 desc = gossip/server.go:93: duplicate connection from node at {tcp cockroach-gamma-3:26257}
W160601 08:27:56.165714 gossip/gossip.go:901  partition in gossip network; attempting new connection
I160601 08:27:57.536537 gossip/gossip.go:923  starting client to cockroach-gamma-4:26257
I160601 08:27:57.537072 gossip/server.go:185  refusing gossip from node 1 (max 3 conns); forwarding to 5 ({tcp cockroach-gamma-5:26257})
I160601 08:28:01.042852 http2_client.go:915  transport: http2Client.notifyError got notified that the client transport was broken read tcp 10.240.0.4:53706->10.240.0.3:26257: read: connection reset by peer.
I160601 08:28:01.043061 http2_client.go:915  transport: http2Client.notifyError got notified that the client transport was broken read tcp 10.240.0.4:57514->104.196.98.24:26257: read: connection reset by peer.
W160601 08:28:01.043410 gossip/gossip.go:899  first range unavailable or cluster not initialized
I160601 08:28:01.045905 gossip/gossip.go:923  starting client to cockroach-gamma-5:26257
```

Nodes 3, 4, and 6 simultaneously decided that node 3 was offline.  Why would a node consider itself offline?
```
$ dsh -Mg gamma 'hostname && grep node.3.is.now.considered.offline logs/cockroach.stderr'
ubuntu@104.196.125.166: cockroach-gamma-1
ubuntu@104.196.41.96: cockroach-gamma-2
ubuntu@104.196.124.159: cockroach-gamma-3
ubuntu@104.196.124.159: W160601 08:08:34.010340 storage/store_pool.go:61  store 3 on node 3 is now considered offline
ubuntu@104.196.98.24: cockroach-gamma-4
ubuntu@104.196.98.24: W160601 08:08:34.014307 storage/store_pool.go:61  store 3 on node 3 is now considered offline
ubuntu@104.196.39.184: cockroach-gamma-5
ubuntu@104.196.41.218: cockroach-gamma-6
ubuntu@104.196.41.218: W160601 08:08:34.019111 storage/store_pool.go:61  store 3 on node 3 is now considered offline
```

Something has gone badly wrong with the raft log GC; that looks like our root cause here.

**Comment by mberhault** [comment]
sorry, I keep using the node index based on my list of nodes, starting at 0.
I'm not sure there's a better way. the actual node ID as used by cockroach can change if I wipe a node, and the order is dependent on when each node joined gossip.

**Comment by bdarnell** [comment]
Do the hostnames currently correspond to the cockroach node IDs?

**Comment by mberhault** [comment]
They currently do, although I can't remember why I didn't name them using
0-indexing.
Ok, so I really need to be more careful in the future and stop referring to
the completely arbitrary position in the list. I'll use the hostname from
now on.

**Comment by tschottdorf** [comment]
Did you see any errors related to the Raft Log GC? Maybe we should start
periodically dumping the `/debug/*` endpoints as well. These will have the
events log for the queues.

On Wed, Jun 1, 2016 at 1:48 PM Ben Darnell <notifications@github.com> wrote:

> Do the hostnames currently correspond to the cockroach node IDs?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/6988#issuecomment-223071401>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE135LPzH6hNy0gOJEoNkCNoMA4S0bP1ks5qHcXpgaJpZM4IrnnR>
> .
>
-- 

-- Tobias

**Comment by bdarnell** [comment]
The raft log GC queue doesn't log anything by default (and even at V(1) there's not much useful).

**Comment by tamird** [comment]
Anything left to do here?

**Comment by bdarnell** [comment]
The memory issues should have been addressed by the raft log GC work. I've renamed the issue to reflect the one remaining issue, that a node can consider itself to be offline while it is still running (and, less surprisingly, the other nodes also consider it to be offline at the same time).

**Comment by petermattis** [comment]
From the code: a node could consider itself offline if it stopped gossiping its store descriptor. This would prevent the local `StorePool.start` loop from ever seeing an updated store descriptor which would cause that goroutine to mark the store dead (even though it is local). I don't see any reason why a node would stop gossiping its store descriptor, though. Do you still have the logs from this event? Perhaps they contain some hint.

**Comment by bdarnell** [comment]
Yeah, I still have the logs. Here's the part where node 3 considers itself offline:

```
W160601 07:58:38.050594 storage/intent_resolver.go:295  [node=3,store=3,range=1] failed to resolv
e intents: range 0: replica <nil> not leader; leader is <nil>
E160601 08:03:05.654857 client/txn.go:370  failure aborting transaction: does not exist; abort ca
used by: does not exist
W160601 08:08:34.010340 storage/store_pool.go:61  store 3 on node 3 is now considered offline
I160601 08:27:51.865471 gossip/server.go:185  refusing gossip from node 2 (max 3 conns); forwarding to 5 ({tcp cockroach-gamma-5:26257})
W160601 08:27:56.151672 gossip/gossip.go:901  partition in gossip network; attempting new connection
I160601 08:27:56.161930 gossip/gossip.go:923  starting client to cockroach-gamma-2:26257
I160601 08:27:56.165637 gossip/client.go:88  closing client to cockroach-gamma-2:26257: rpc error: code = 2 desc = gossip/server.go:93: duplicate connection from node at {tcp cockroach-gamma-3:26257}
W160601 08:27:56.165714 gossip/gossip.go:901  partition in gossip network; attempting new connection
```

Everyone considered node 3 to be offline at 8:08, so the last time it gossiped its descriptor must have been at 8:03. Even if the gossip network was partitioned (as we see at 8:27), the node should have been able to see its own gossip.

The logs had been quiet for several days before that. I'm not sure whether that means everything was working or everything was broken. Excluding the runtime stats spam, here are the log lines per day for the period covered by this log:
```
96984 160525
3965 160526
1700 160527
  12 160528
  23 160529
  32 160530
  27 160531
41108 160601
```

**Comment by petermattis** [comment]
It is interesting that the log message preceding 8:08 is 8:03. Not sure if that means anything or is just coincidence. There isn't much to go on here.

**Comment by bdarnell** [comment]
Unassigning since I'm not actively working on this.

**Comment by mberhault** [comment]
closing.
