### ISSUE TITLE
server: automatic upgrade finalization is too aggressive

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#69929]
**Is your feature request related to a problem? Please describe.**

The auto-upgrade finalization code runs on every node without any coordination. It does so in a loop with a max backoff of 30s. This is way too aggressive on large clusters or if the task might fail. I don't see much reason for this operation to be all that fast.

https://github.com/cockroachdb/cockroach/blob/5a82afcae5f637bd15d250aee8384b9f4fda1b8c/pkg/server/auto_upgrade.go#L32-L37

**Describe the solution you'd like**

1) Instead of retry, just use a loop. Set that loop's interval to something long like 5 minutes. Add a cluster setting.
2) Coordinate this process so that we don't have tons of nodes trying to do it on large clusters

Jira issue: CRDB-9864

**Comment by mwang1026** [comment]
Upgrades are a relatively risky / operationally sensitive operation. Based on that, my intuition would be some sort of more visibly alerting or "logging" (`system.eventlog`?) would also be beneficial here. If there are a lot of transient failures / retries it might get noisy, but I also feel like we shouldn't have too many of those?

**Comment by ajwerner** [comment]
We do write to `system.eventlog` when performing migrations. This thing spins attempting to kick it off but will not actually start an attempt to migrate if the preserve downgrade option is set or the cluster nodes are not all at the same version.

**Comment by ajwerner** [comment]
Like, this thing, as designed, will just run in a loop and ask whether all the nodes are at the latest version before kicking off finalization. When we've observed lots of logging about the cluster version being set, that was working as intended, as far as I understand. Nothing risky happens until we actually attempt to migrate.
