### ISSUE TITLE
Allow forcing write transaction to be DDL without running DDL

### ISSUE THREAD

**Issue by electrum** [cockroachdb/cockroach#69938]
Transactions that execute DDL must execute DDL as the first write operation:
```sql
CREATE TABLE abc (x int);
BEGIN;
INSERT INTO abc VALUES (123);
CREATE TABLE xyz (x int);
```
```
ERROR: unimplemented: the first schema change statement in a transaction must precede any writes
```
For database migration or schema management systems, it would be helpful to have a way to force the transaction to be in "DDL mode" without actually executing a DDL statement, as the migration framework might execute an update statement against its internal schema version table before running the DDL statements. Setting the mode when starting the transaction would avoid needing to run an unnecessary and expensive dummy DDL statement.

Jira issue: CRDB-9870

**Comment by ajwerner** [comment]
This is an interesting idea. We're underway on the project to remove this limitation. It did not make it for 21.2 but it should be there for 22.1. There are some hacks which might do something for you like consider renaming a table that you know exists to the same name. That's pretty lame, I'll admit.

We could add a function to do this, but it likely wouldn't be in this release (21.2) and hopefully will be moot in the next release (22.1).

**Comment by ajwerner** [comment]
Cross-ref to https://github.com/cockroachdb/cockroach/issues/54477.

**Comment by postamar** [comment]
This limitation has been removed. Closing.
