### ISSUE TITLE
ui: Database and table endpoints

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#6993]
NOTE: size and # of rows can be approximate.

Database
- [x] # tables
- [ ] size bytes
- [x] owner (?)
- [x] zone config
  - [x] replication factor
  - [x] target range size (range size max)

Table
- [ ] # rows
- [x] # ranges (?)
- [ ] size bytes
- [x] owner (?)
- [x] zone config
  - [x] replication factor
  - [x] target range size (range size max)
- [x] SHOW CREATE TABLE table description

**Comment by mrtracy** [comment]
The row/size metrics are more complicated to compute that the other elements of this information.  These are now being tracked in #7682, which will require a larger amount of work to complete.

Closing, as the rest of this information is already available in the {Database|Table}Details responses.
