### ISSUE TITLE
importccl: TestImportWorkerFailure is timing out under race in bazel

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#69995]
`TestImportWorkerFailure` appears to be timing out a shard in the importccl package when run under race in bazel. This is not reproducible locally using `./dev test --race pkg/ccl/importccl --filter=TestImportWorkerFailure` but can be seen in the following builds:

https://teamcity.cockroachdb.com/viewLog.html?buildId=3420687&buildTypeId=Cockroach_Ci_Tests_Testrace&tab=artifacts#%2Fbazel-testlogs%2Fpkg%2Fccl%2Fimportccl%2Fimportccl_test%2Fshard_9_of_16;%2Ftmp%2F_tmp%2F05cc09c876578499595eb951f41858b6%2FlogTestImportWorkerFailure026849282

It is worth investigating why this fails under bazel and not CI.

Jira issue: CRDB-9886

**Comment by tbg** [comment]
I also just saw this fail in CI without bazel:

```
------- Stdout: -------
=== RUN   TestImportWorkerFailure
    test_log_scope.go:79: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestImportWorkerFailure2689824557
    test_log_scope.go:80: use -show-logs to present logs inline
    import_stmt_test.go:5065: pq: not enough memory available to create a BulkAdder: root: memory budget exceeded: 33554432 bytes requested, 100878336 currently allocated, 134217728 bytes in budget
    panic.go:642: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestImportWorkerFailure2689824557
--- FAIL: TestImportWorkerFailure (6.23s)
```

https://teamcity.cockroachdb.com/viewLog.html?buildId=3754905&buildTypeId=Cockroach_UnitTests

cc @cockroachdb/bulk-io

**Comment by stevendanna** [comment]
Thanks for posting this! We saw this fail last month but waiting too long to debug it so the logs had rotated away.

**Comment by yuzefovich** [comment]
Closing this issue as stale (the test now currently runs under bazel but is skipped under stress or race).
