### ISSUE TITLE
debug.zip does not include logs that have be redirected to a different directory in logs.yaml 

### ISSUE THREAD

**Issue by cjireland** [cockroachdb/cockroach#70021]
**Describe the problem**

Using CRDB 21.1.2, we have just changed the log directory using the new logs.yaml for the various file-groups to /var/logs/containers so that their log scraping can pick them up. 

The logs.yaml was (apologies the indentation was lost in transfer):

`file-defaults:
max-file-size: 10MiB
max-group-size: 100MiB
buffered-writes: true
filter: INFO
format: json
redact: true
redactable: true
exit-on-error: true
auditable: false
fluent-defaults:
filter: INFO
format: json-fluent-compact
redact: true
redactable: true
exit-on-error: false
auditable: false
sinks:
file-groups:
default:
channels: [DEV, OPS, HEALTH, SQL_SCHEMA, USER_ADMIN, PRIVILEGES]
dir: /var/log/containers
pebble:
channels: [STORAGE]
dir: /var/log/containers
sql-audit:
channels: [SENSITIVE_ACCESS]
dir: /var/log/containers
sql-auth:
channels: [SESSIONS]
dir: /var/log/containers
sql-exec:
channels: [SQL_EXEC]
dir: /var/log/containers
sql-slow:
channels: [SQL_PERF]
dir: /var/log/containers
sql-slow-internal-only:
channels: [SQL_INTERNAL_PERF]
dir: /var/log/containers
stderr:
channels: all
filter: NONE
format: crdb-v2-tty
redact: true
redactable: true
exit-on-error: true
capture-stray-errors:
enable: true
dir: /var/log/containers
max-group-size: 100MiB`

When I run a debug.zip it seems to pick up only a single old log from cockroach-data/logs (and some empty files).

This first screen shot covers the situation in /var/logs/containers and cockroach-data/log. 
![image (3)](https://user-images.githubusercontent.com/18700406/132891227-507a04a3-aa25-4bc9-898c-594775e75a37.png)

The second screen shot is what I have in debug.zip. The debug.zip was run as cockroach debug zip debug.zip --certs-dir… 
![image (4)](https://user-images.githubusercontent.com/18700406/132891273-4b2dfb12-6316-4a21-91f6-bde8e68e457a.png)

I imagine I should see the logs from /var/logs/containers but please correct me. 

It ’s as if debug zip isn’t using the new log cfg.

**Comment by cjireland** [comment]
Please can someone confirm in which release of CRDB this will be fixed?
We would like to move forward with our changes but without this fix we will be unable to include the logs in a debug.zip should that be required. 
Thanks.

**Comment by knz** [comment]
When this will be fixed, it will be backported.

**Comment by cjireland** [comment]
Lovely, thanks @knz.
Do you have an ETA for the fix?

**Comment by knz** [comment]
Not yet, no, a minimum of a couple of weeks.

**Comment by cjireland** [comment]
OK, thanks @knz

**Comment by knz** [comment]
This bug has existed since v19.x.
