### ISSUE TITLE
sql: support json_populate_record, json_populate_recordset, json_to_record, json_to_recordset

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#70037]
Needed for #69010.

This was originally tracked in https://github.com/cockroachdb/cockroach/issues/20120.

We currently don't support the following four builtin functions, which are different ways to convert an unstructured JSON datum (or set of JSON datums) into a structure record datum (or set of record datums):

* [x] `json_populate_record`
* [x] `json_populate_recordset`
* [ ] `json_to_record`
* [ ] `json_to_recordset`

As with most builtins, these have corresponding `jsonb` versions which should get identical implementations.

These builtins will be more useful once we address https://github.com/cockroachdb/cockroach/issues/70036.

Epic CRDB-10300

Jira issue: CRDB-9913

**Comment by jordanlewis** [comment]
I took a stab at doing this tonight. It was way more annoying than expected!

Here is the WIP branch: https://github.com/cockroachdb/cockroach/compare/master...jordanlewis:json-to-record?expand=1

The main annoyance is that functions that return records have a requirement that they're aliased to column definition lists, with types. Our parser doesn't support this - column aliases don't have types. Also, it means that we need to plumb alias information down into the thing that's getting aliased, which is awkward, and somehow plumb that info even deeper into the generator func factory. I think this is doable with a bit more work.
