### ISSUE TITLE
gossip: "not connected to cluster" log spam for 1-node cluster

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#7012]
When running a single-node cluster, the following message appears regularly in the logs:

```
W160602 15:58:28.437737 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
```

This happens at startup as well as much later after startup. The cluster has never had more than one node. Our logs should be much quieter, since it's probable that new users will start with a single-node cluster. 

Version info:

```
Build Tag:   beta-20160526-136-gcb6f4a0
Build Time:  2016/06/01 14:58:33
Platform:    linux amd64
Go Version:  go1.6.2
C Compiler:  gcc 4.9.2
```

**Comment by spencerkimball** [comment]
This was fixed a while ago apparently.
