### ISSUE TITLE
update table visuals of job page

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#70149]
update the table on Jobs page so it uses the same style of all other pages on the console

**Comment by maryliag** [comment]
We're missing the tooltip texts for the Jobs table columns, I'm creating them (very basic and straightforward).
@Annebirzin , @ianjevans  can you confirm if those are good like this or if there is any documentation links that I can add to any of those?

Description: Description of the job
Job ID: ID of the job
Users: User running the job     (currently this column says `Users`, should we change the column name to `User`?)
Creation Time: Creation time of the job
Status: Status of the job

<img width="912" alt="Screen Shot 2021-09-17 at 3 20 46 PM" src="https://user-images.githubusercontent.com/1017486/133842878-5bbf2531-67e7-4e27-b1e5-75b5f16298ef.png">

**Comment by Annebirzin** [comment]
If @ianjevans agrees, I think it could make sense to use the descriptions and links provided in docs [here](https://www.cockroachlabs.com/docs/v21.1/ui-jobs-page.html#jobs-list)

<img width="1063" alt="Screen Shot 2021-09-17 at 5 03 24 PM" src="https://user-images.githubusercontent.com/51920721/133853388-567b23c9-6033-4585-afd0-2b0c7ea1be42.png">

cc @kevin-v-ngo

**Comment by ianjevans** [comment]
I agree, though I guess we should alter Status to say: "Current job status or completion progress, and the total time the job took to complete."

**Comment by kevin-v-ngo** [comment]
Sounds good to me too. 

+1 making 'Users' singular

**Comment by maryliag** [comment]
for the description, I don't think is "SQL statement that created the job", because we don't show the statement there, is indeed just a description of the job

**Comment by ianjevans** [comment]
+1 to adding the fingerprint If the job doesn't have a description, as otherwise how would the user know what that job does?
"The description of the job, if set, or the SQL statement if there is no job description."

**Comment by Annebirzin** [comment]
I think it is currently a mix of the job description or SQL statement - attached screenshot example of BACKUP statement. 

![Screen Shot 2021-09-20 at 10 50 37 AM](https://user-images.githubusercontent.com/51920721/134023748-4150b68f-037c-4054-9563-fa858cb4312c.png)

**Comment by maryliag** [comment]
I used the tooltip suggested by Ian, which include both options: "The description of the job, if set, or the SQL statement if there is no job description."

**Comment by celiala** [comment]
(apologies for the noise for this and other SQL Observability issues - updating blocker from release to GA, as noted in triage meeting, thanks!)
