### ISSUE TITLE
bulkio: handle backup, restore, import with explicit public schemas

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#70164]
Creating an issue to discuss and track how the explicit public schema migration work will affect bulkio.

Fallout from https://github.com/cockroachdb/cockroach/pull/68674 (new public schemas will be backed by descriptors)

In the PR above, I've made it so restoring public schemas that do not have descriptors (use id 29, synthetic schema) will create an explicit public schema with a descriptor on restore.

We need to keep in mind handling backup/restore for mixed version (hopefully this should be just creating a real public schema whenever we encounter a synthetic public schema with id 29).

Also we need to keep in mind that we may want to remove `IMPORT TABLE` in this version to accommodate public schema becoming a real UDS.

Some known issues to deal with:

- [x] https://github.com/cockroachdb/cockroach/issues/70168
- [x] https://github.com/cockroachdb/cockroach/issues/70049
- [x] https://github.com/cockroachdb/cockroach/issues/69973 (there is discussion on IMPORT TABLE being deprecated which would mean less work to do here) 
- [x] https://github.com/cockroachdb/cockroach/issues/67485
- [ ] https://github.com/cockroachdb/cockroach/issues/71479 (this is a short term solution to the issue above)
- [x] https://github.com/cockroachdb/cockroach/issues/71480
- [x] Some more cases with making MYSQLDUMP and PGDUMP work as well (this should be fairly small / easy)

Epic: CRDB-1521

**Comment by vy-ton** [comment]
@RichardJCai Can we use this as a meta issue to track Bulk I/O work tied to the public schema migration? Are you aware of any other issues?

**Comment by rafiss** [comment]
closed by #72000
