### ISSUE TITLE
sql: auto commit erroneously is disabled for all internal queries

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#70176]
The bug was introduced in #69202 in this line https://github.com/cockroachdb/cockroach/blob/11b003b6b04a97bd2027277bcbc1e2486d52fe3f/pkg/sql/opt/exec/execbuilder/builder.go#L160

The goal of the second part of the conditional is to prohibit the auto commit for non-internal queries if `TxnRowsReadErr` is non-zero. However, by mistake, as it is written currently, the auto commit is disabled for all internal queries (because the last part of the logical ANDs is `false`).

I'm adding a release-blocker label since it looks pretty bad to me, but tomorrow we'll reassess it with the team.

**Comment by rytaft** [comment]
Reopening this issue since the PR for 21.2 is not yet merged

**Comment by yuzefovich** [comment]
Fixed by #70179
