### ISSUE TITLE
outstanding raft commands for newly deleted group panic etcd/raft 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#702]
found during playing with #682, sporadic raft-internal panic during `TestStoreExecuteCmdOutOfRange`:

```
E0417 19:46:13.720883   44323 log.go:96] after(10) is out of range [committed(11)]
panic: after(10) is out of range [committed(11)]
```

That test splits a range and immediately deletes the second part of it.
This happens only in my WIP in which a single-member Raft group immediately elects itself as leader.
When the range is split, a new range is created and begins elections. While those are running, the test deletes that new range. In `etcd/raft`, the election continues, and trying to append the empty `MsgApp` to confirm leadership, something goes bust since the `GroupStorage` has been reset. Full stack trace below.

```
go test  -run TestStoreExecuteCmdOutOfRange ./storage -logtostderr -timeout 15s -v -vmodule=multiraft=7,raft=7
=== RUN TestStoreExecuteCmdOutOfRange
I0417 19:46:13.705575   44323 rocksdb.go:87] opening rocksdb instance at ""
I0417 19:46:13.714173   44323 multiraft.go:424] node 100000001 starting
I0417 19:46:13.715209   44323 multiraft.go:498] node 100000001: got op &multiraft.createGroupOp{groupID:0x1, ch:(chan error)(0xc2080ea540)}
I0417 19:46:13.715512   44323 multiraft.go:614] node 100000001 creating group 1
I0417 19:46:13.715679   44323 raft.go:390] raft: 100000001 became follower at term 5
I0417 19:46:13.715787   44323 raft.go:207] raft: newRaft 100000001 [peers: [100000001], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0417 19:46:13.715822   44323 raft.go:464] raft: 100000001 is starting a new election at term 5
I0417 19:46:13.715834   44323 raft.go:403] raft: 100000001 became candidate at term 6
I0417 19:46:13.715842   44323 raft.go:447] raft: 100000001 received vote from 100000001 at term 6
I0417 19:46:13.715861   44323 raft.go:426] raft: 100000001 became leader at term 6
I0417 19:46:13.716357   44323 multiraft.go:297] node 100000001 submitting command to group 1
I0417 19:46:13.716377   44323 multiraft.go:696] node 100000001: group 1 raft ready
I0417 19:46:13.716383   44323 multiraft.go:698] SoftState updated: {Lead:4294967297 RaftState:StateLeader}
I0417 19:46:13.716392   44323 multiraft.go:701] HardState updated: {Term:6 Vote:4294967297 Commit:11 XXX_unrecognized:[]}
I0417 19:46:13.716905   44323 multiraft.go:704] New Entry[0]: 6/11 EntryNormal [empty]
I0417 19:46:13.716918   44323 multiraft.go:707] Committed Entry[0]: 6/11 EntryNormal [empty]
I0417 19:46:13.716938   44323 multiraft.go:750] node 100000001 write ready, preparing request
I0417 19:46:13.717637   44323 multiraft.go:498] node 100000001: got op &multiraft.createGroupOp{groupID:0x1, ch:(chan error)(0xc2080eac60)}
I0417 19:46:13.717660   44323 multiraft.go:769] node 100000001 got write response: multiraft.writeResponse{groups:map[uint64]*multiraft.groupWriteResponse{0x1:(*multiraft.groupWriteResponse)(0xc2080eaea0)}}
I0417 19:46:13.717710   44323 multiraft.go:297] node 100000001 submitting command to group 1
I0417 19:46:13.717779   44323 multiraft.go:696] node 100000001: group 1 raft ready
I0417 19:46:13.717786   44323 multiraft.go:701] HardState updated: {Term:6 Vote:4294967297 Commit:13 XXX_unrecognized:[]}
I0417 19:46:13.719584   44323 multiraft.go:704] New Entry[0]: 6/12 EntryNormal 13d5f1d99da064894d65822107fcfd52: raft_id:1 cmd:<increment:<header:<timestamp:<wall_time:0 logical:7 > cmd_id:<wall_time:1429314373714732169 random:5577006791947779410 > key:"\000raft
I0417 19:46:13.719644   44323 multiraft.go:704] New Entry[1]: 6/13 EntryNormal 000000000000000078629a0f5f3f164f: raft_id:1 cmd:<internal_lease:<header:<timestamp:<wall_time:0 logical:0 > cmd_id:<wall_time:0 random:0 > key:"" end_key:"" user:"" replica:<node_id:"
I0417 19:46:13.719681   44323 multiraft.go:707] Committed Entry[0]: 6/12 EntryNormal 13d5f1d99da064894d65822107fcfd52: raft_id:1 cmd:<increment:<header:<timestamp:<wall_time:0 logical:7 > cmd_id:<wall_time:1429314373714732169 random:5577006791947779410 > key:"\000raft
I0417 19:46:13.719716   44323 multiraft.go:707] Committed Entry[1]: 6/13 EntryNormal 000000000000000078629a0f5f3f164f: raft_id:1 cmd:<internal_lease:<header:<timestamp:<wall_time:0 logical:0 > cmd_id:<wall_time:0 random:0 > key:"" end_key:"" user:"" replica:<node_id:"
I0417 19:46:13.719729   44323 multiraft.go:750] node 100000001 write ready, preparing request
I0417 19:46:13.719848   44323 multiraft.go:769] node 100000001 got write response: multiraft.writeResponse{groups:map[uint64]*multiraft.groupWriteResponse{0x1:(*multiraft.groupWriteResponse)(0xc2080ea0c0)}}
I0417 19:46:13.720114   44323 multiraft.go:498] node 100000001: got op &multiraft.createGroupOp{groupID:0x2, ch:(chan error)(0xc2080eb320)}
I0417 19:46:13.720129   44323 multiraft.go:614] node 100000001 creating group 2
I0417 19:46:13.720163   44323 raft.go:390] raft: 100000001 became follower at term 5
I0417 19:46:13.720202   44323 raft.go:207] raft: newRaft 100000001 [peers: [100000001], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0417 19:46:13.720235   44323 raft.go:464] raft: 100000001 is starting a new election at term 5
I0417 19:46:13.720249   44323 raft.go:403] raft: 100000001 became candidate at term 6
I0417 19:46:13.720258   44323 raft.go:447] raft: 100000001 received vote from 100000001 at term 6
I0417 19:46:13.720283   44323 raft.go:426] raft: 100000001 became leader at term 6
I0417 19:46:13.720306   44323 multiraft.go:696] node 100000001: group 2 raft ready
I0417 19:46:13.720313   44323 multiraft.go:698] SoftState updated: {Lead:4294967297 RaftState:StateLeader}
I0417 19:46:13.720320   44323 multiraft.go:701] HardState updated: {Term:6 Vote:4294967297 Commit:11 XXX_unrecognized:[]}
I0417 19:46:13.720328   44323 multiraft.go:704] New Entry[0]: 6/11 EntryNormal [empty]
I0417 19:46:13.720334   44323 multiraft.go:707] Committed Entry[0]: 6/11 EntryNormal [empty]
I0417 19:46:13.720348   44323 multiraft.go:502] node 100000001: got op &multiraft.removeGroupOp{groupID:0x2, ch:(chan error)(0xc2080eb980)}
I0417 19:46:13.720380   44323 multiraft.go:498] node 100000001: got op &multiraft.createGroupOp{groupID:0x2, ch:(chan error)(0xc2080eba40)}
I0417 19:46:13.720389   44323 multiraft.go:614] node 100000001 creating group 2
I0417 19:46:13.720532   44323 raft.go:390] raft: 100000001 became follower at term 5
I0417 19:46:13.720585   44323 raft.go:207] raft: newRaft 100000001 [peers: [100000001], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0417 19:46:13.720606   44323 multiraft.go:750] node 100000001 write ready, preparing request
I0417 19:46:13.720622   44323 raft.go:464] raft: 100000001 is starting a new election at term 5
I0417 19:46:13.720628   44323 raft.go:403] raft: 100000001 became candidate at term 6
I0417 19:46:13.720634   44323 raft.go:447] raft: 100000001 received vote from 100000001 at term 6
I0417 19:46:13.720653   44323 raft.go:426] raft: 100000001 became leader at term 6
I0417 19:46:13.720682   44323 multiraft.go:297] node 100000001 submitting command to group 2
I0417 19:46:13.720817   44323 multiraft.go:769] node 100000001 got write response: multiraft.writeResponse{groups:map[uint64]*multiraft.groupWriteResponse{0x2:(*multiraft.groupWriteResponse)(0xc20800b980)}}
E0417 19:46:13.720883   44323 log.go:96] after(10) is out of range [committed(11)]
panic: after(10) is out of range [committed(11)]

goroutine 9 [running]:
github.com/cockroachdb/cockroach/multiraft.(*glogLogger).Panicf(0x4dc14b8, 0x4ac4070, 0x29, 0xc20801ea60, 0x2, 0x2)
        /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/multiraft/raft.go:107 +0x18f
github.com/coreos/etcd/raft.(*raftLog).append(0xc2080d34a0, 0xc2080d3950, 0x1, 0x1, 0x0)
        /Users/tschottdorf/go/src/github.com/coreos/etcd/raft/log.go:96 +0x197
github.com/coreos/etcd/raft.(*raft).appendEntry(0xc2080aae40, 0xc2080d3950, 0x1, 0x1)
        /Users/tschottdorf/go/src/github.com/coreos/etcd/raft/raft.go:357 +0xb3
github.com/coreos/etcd/raft.stepLeader(0xc2080aae40, 0x2, 0x0, 0x100000001, 0x0, 0x0, 0x0, 0xc2080d3950, 0x1, 0x1, ...)
        /Users/tschottdorf/go/src/github.com/coreos/etcd/raft/raft.go:512 +0x2a6
github.com/coreos/etcd/raft.(*raft).Step(0xc2080aae40, 0x2, 0x0, 0x100000001, 0x0, 0x0, 0x0, 0xc2080d3950, 0x1, 0x1, ...)
        /Users/tschottdorf/go/src/github.com/coreos/etcd/raft/raft.go:487 +0x259
github.com/coreos/etcd/raft.(*multiNode).run(0xc20800afc0)
        /Users/tschottdorf/go/src/github.com/coreos/etcd/raft/multinode.go:230 +0xbb9
created by github.com/coreos/etcd/raft.StartMultiNode
        /Users/tschottdorf/go/src/github.com/coreos/etcd/raft/multinode.go:55 +0xb6
```

**Comment by tschottdorf** [comment]
I'll post the WIP soon, once it's cleaned up a bit.

**Comment by tschottdorf** [comment]
To reproduce this, it should be enough to undo the changes to the above test which are introduced in #703.

**Comment by tschottdorf** [comment]
I think the basic issue is that we delete the range and the raft group, but not the stored state. The group then gets auto-recreated because messages are still around, potentially even elects itself leader since it might think it's alone, and either way tries to append something at an index which is lower than what's already committed. Sounds like there's nothing here to blame Raft for, if anything joke's on us for not cleaning the slate.

**Comment by bdarnell** [comment]
But *because* we don't clear the state, the auto-recreation of the group should put it back in the same state it was before. I think there's a bug here (in raftstorage.go or maybe in the store) in that something is not getting persisted or restored correctly.

**Comment by tschottdorf** [comment]
right. Seems like the second group gets deleted, instantly recreated but not with the HardState persisted after first elections (commit=11) but with the one that corresponds to the empty storage, and then dies when it tries to commit its empty MsgApp in celebration of its leadership. I'll take a look tomorrow.

**Comment by tschottdorf** [comment]
So I wasn't able to reproduce this, but changing the test around a little bit I ran into what I think is another bug, pretty annoying to track down. At the heart of it is that `FirstIndex()` uses `raftTruncatedState()`, whose behaviour depends on whether the range is initialized. That together with the fact that we don't clean up state at all leads to the following:

* Create a range, append a command, but don't apply it (in my test case, since the leader lease isn't done yet). AppliedIndex is not updated (only mentioning that because if `r.AppliedIndex` got updated and persisted when the group is created, that would've saved us already)
* `store.RemoveRange(rng)`. The important thing that this will do is remove `rng` from `store.ranges`.
* Submit a Raft command to that range (which has just been removed from the store.
  This automatically recreates the Raft group, which in turn creates a `GroupStorage`.
* The GroupStorage checks `store.ranges`, does not find the range and thus decides to create it via `getRangeInternal`. The appliedIndex comes back `0`; nothing had been persisted. There is however a non-zero `lastIndex` because we appended a command.
* The group creation trickles all the way to `newRaft` (in `etcd/raft/raft.go`) and that creates a `newLog(c.Storage)`, which sets the applied index to `FirstIndex-1`. There's no further update of the applied index because the config for the group specifies a zero.
* the behaviour of FirstIndex, in the absence of a persisted `RaftTruncatedState`, depends on `rng.isInitialized`, which is now false (since the range was auto-recreated), and that returns a zero state (`Index=Term=0`).
* Only when `lastIndex == 0` will the newly created Raft group bootstrap itself and manually adjust committed, etc. This doesn't happen here; after all it's not a new group.
* Instead the thing starts running and immediately kills itself trying for `Entries(1, <last index>)`, but of course no entry below `raftInitialIndex` has ever been there.

**Comment by bdarnell** [comment]
OK, I think there are two issues here. The biggest one is that this test uses `splitTestRange`, which does not fully emulate the behavior of a real split. Specifically, it only updates the in-memory descriptor without persisting it to disk. This is what leads to the inconsistent state when the range is removed and restored from disk.  This problem is unique to tests that use splitTestRange and RemoveRange (i.e. only this one); either using a real AdminSplit or leaving all ranges in the Store would be sufficient to avoid the problem. We should avoid using splitTestRange in future tests in favor of doing real splits in client_split_test.go.

A second problem is that applyRaftCommand returns early in some cases without updating the appliedIndex. applyRaftCommand is not allowed to fail; it always "applies" the command even if the result of the command is a noop due to not holding the leader lease. This is a fairly minor issue since the next successful command will fix it but as we've seen it's not good to let the applied index lag too far behind.

**Comment by bdarnell** [comment]
Closing this since we have identified the source of the panic and it's not likely to recur. If the timeout in #838 recurs it must be something unrelated.
