### ISSUE TITLE
Enable combined stats for tenants on statements and transaction pages

### ISSUE THREAD

**Issue by xinhaoz** [cockroachdb/cockroach#70214]
Part of #69930.

Currently we hide the date range selector on tenant statements/transactions pages and show only in-memory stats. Now that we are using pod-to-pod fanout for in-memory stats for tenants, we should use the combined statements API and show the date range selector. This will allow the viewing of combined in-memory and persisted statistics for serverless.

**Comment by maryliag** [comment]
Reopen so it can be backported
