### ISSUE TITLE
Significant amount of background sql against system.lease table

### ISSUE THREAD

**Issue by a-entin** [cockroachdb/cockroach#70233]
**Describe the problem**

The `system.lease` table was observed to draw a fairly large amount of background sql in a mostly idling cluster.
Observations are from the "Statements page" as top "% runtime". Also confirmed to be a cpu hog via go cpu profile.

The cluster is for development, 15 nodes multi-region - 5 regions 3 nodes /region. 2 vcpu nodes.
The cluster became barely usable after many objects were dropped as a part of a database drop.  `jobs` table became very active. While investigating utilization, `lease` table was identified as one of the busiest. Jobs are GC for drop database/tables.

Attached are screenshots of Statements page ordered by % runtime and cpu profiles. Profiles were taken periodically to observe the dynamic. There is no correlation between the times of taking screenshots and profiles.

```
 addr: Total 50.0ms
       50.0ms (  100%): internal

 appname: Total 50.0ms
          30.0ms (60.00%): $ internal-lease-insert
          10.0ms (20.00%): $ internal-lease-release
          10.0ms (20.00%): $ internal-stmt-diag-poll

 pebble: Total 30.0ms
         30.0ms (  100%): wal-sync

 stmt.anonymized: Total 50.0ms
                  30.0ms (60.00%): INSERT INTO system.public.lease("descID", version, "nodeID", expiration) VALUES (_, _, __more2__)
                  10.0ms (20.00%): DELETE FROM system.public.lease WHERE ("descID", version, "nodeID", expiration) = ($1, $2, __more2__)
                  10.0ms (20.00%): SELECT id, statement_fingerprint FROM system.statement_diagnostics_requests WHERE completed = _

 stmt.tag: Total 50.0ms
           30.0ms (60.00%): INSERT
           10.0ms (20.00%): DELETE
           10.0ms (20.00%): SELECT
```

![2021-09-14_094234](https://user-images.githubusercontent.com/55302400/133349652-9a248300-ffe6-4727-b114-3ccf158931c4.png)
![2021-09-14_195423](https://user-images.githubusercontent.com/55302400/133349653-65fbefa7-ca49-4df5-af22-75e48662815f.png)
![2021-09-07_183851](https://user-images.githubusercontent.com/55302400/133349654-09687d32-2816-4dcf-b438-7c84ee788237.png)

**Environment:**
 - CockroachDB version 21.1.7
 - CC

Jira issue: CRDB-9996

**Comment by ajwerner** [comment]
> The cluster became barely usable after many objects were dropped as a part of a database drop. 

This is important context. Do you have a sense of how many objects (tables, view, types, sequences) were in the database. It's definitely the case that we'll spin off a bunch of little jobs and drop a bunch of leases in the face of the schema change.

Was there increased traffic observed outside of schema changes? 

Also, the 2 vCPU thing make me even less surprised. We have no limiting on the concurrency here because it tends in larger-node clusters to be the case that we're not CPU bound doing this work.

**Comment by a-entin** [comment]
It's a dev cluster, multiple database clones as individual "sandboxes". A database had ~40 "permanent" tables. Total indexes per database, including PK is about 120. 2-3 databases like that. Number of objects continually changing due to development activities including create/drops of tables, indexes and databases.

As mentioned above, the observations about `lease` table activity was a by-product of an investigation into a slow cluster. The real issue preceding the cluster slowdown was a large number of create/drop table, courtesy of flyway implementation for crdb (subsequently fixed). At the height of the problem there was ~9K drop table GC jobs in various state.

Later we observed similar elevated levels of `lease` activity after multiple cycles of create/drop database (~40 tables each)

**Comment by ajwerner** [comment]
Honestly not a ton of surprise there. Upon create, each node will need to acquire leases, which is a pair of statements and then upon drop we're going to wait for each node to drop the leases which is going to mean a write from each node and some polling by the gateway node to wait for that write. It's definitely not free. Better overload management is going to help here as a short-term mitigation to badness, though it is relatively important that these operations do complete.
