### ISSUE TITLE
storage: make key/value printing explicitly redactable

### ISSUE THREAD

**Issue by AlexTalks** [cockroachdb/cockroach#70288]
Requested by @knz in #70165:
> ideally, we'd have `FormatBytesAsKey` return a `redact.RedactableString`. ditto for values.

Currently, the `roachpb` package injects two utility functions into `storage` for "pretty printing" byte strings as Keys and Values: https://github.com/cockroachdb/cockroach/blob/f278e644ebe0d736d2f1d796ca381c655885dff7/pkg/roachpb/data.go#L2539-L2540

As part of the log redaction effort, these functions should each return a `redact.RedactableString`.

Epic: CRDB-6668

Jira issue: CRDB-10015

**Comment by knz** [comment]
this is a kv or storage issue, not server
