### ISSUE TITLE
sql: provide mechanism to plumb QoS level into admission control

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#70295]
**Is your feature request related to a problem? Please describe.**

The [admission control subsystem] introduced in 21.2 queues work when the system is overloaded. When queuing, the system decides what to admit next based on goals of providing fairness between tenants and providing priority order within a tenant, ultimately with a time-based tie-breaker allowing older work to go first.

When it comes to priority, the space of the current system is 1 byte, and only 3 values are in use: https://github.com/cockroachdb/cockroach/blob/0fda7519be7d7579526a19f4c9967f2e125d00ba/pkg/util/admission/work_queue.go#L63-L75

At the time of writing, nothing is using `LowPri`, and transactions which hold locks are using `HighPri`. 

In general, when the system is overloaded, some parts of the workload are more important than others. Users may want ways to inform the system of these priority distinctions. 

**Describe the solution you'd like**

Given the general lack of certainty, this issue proposes that it's best to provide something rather than everything in terms of control. The choice proposed is to expose priority as a session variable. The choice of a session variable was made because of the flexibility it offers. A session variable can be set in the session, from a connection URL, or using database role defaults.

The proposal here is that we introduce a session setting, say, `admission_control_work_priority` or something like that. The value could be an 8bit integer to exactly fit the model inside of the current implementation. Alternatively we could bound the interval to reserve some bits at either end of the spectrum, or we could make it a floating point number which we project into whatever space we use internally. As long as we don't make it `[20, -19]` where 20 is the lowest value, I'm pretty cool with it.

* The meat of this proposal would be to add the new session variable.
     * Add a new session data field [here](https://github.com/cockroachdb/cockroach/blob/0fda7519be7d7579526a19f4c9967f2e125d00ba/pkg/sql/sessiondatapb/local_only_session_data.proto#L17-L18).
     * Add an entry here to populate it [here](https://github.com/cockroachdb/cockroach/blob/0fda7519be7d7579526a19f4c9967f2e125d00ba/pkg/sql/vars.go#L141-L143)
* Expose some more knobs to, at least, initialize a transaction at a priority level.
     * This would mean updating the constructor [here](https://github.com/cockroachdb/cockroach/blob/0fda7519be7d7579526a19f4c9967f2e125d00ba/pkg/kv/txn.go#L134-L137))
     * We may also want to expose a method to update the priority level while a transaction is running. Consider a `SET admission_control_priority = ...` during a transaction.
* Plumb the value from the sessiondata to new transactions.
     * The value will need to be plumbed to transaction [here](https://github.com/cockroachdb/cockroach/blob/0fda7519be7d7579526a19f4c9967f2e125d00ba/pkg/sql/txn_state.go#L191).
     * The value will need to be plumbed via [eventTxnStartPayload](https://github.com/cockroachdb/cockroach/blob/0fda7519be7d7579526a19f4c9967f2e125d00ba/pkg/sql/conn_fsm.go#L101) which will happen [here](https://github.com/cockroachdb/cockroach/blob/0fda7519be7d7579526a19f4c9967f2e125d00ba/pkg/sql/conn_executor_exec.go#L1482) or [here](https://github.com/cockroachdb/cockroach/blob/0fda7519be7d7579526a19f4c9967f2e125d00ba/pkg/sql/conn_executor_exec.go#L1502).

**Describe alternatives you've considered**

Many different approaches have been discussed in the past for how to offer control over priorities. These include

1) Statement fingerprints
2) Application names
3) Users
4) Connection settings

Honestly, we should just do something, and refine it over time.

**Additional context**

The whole thing where we increase the lock strength to `HighPri` may interact in unexpected ways with user-provided priorities. In general, I think it's fine, but we should probably note that once you've laid down a write, you get high priority.

[admission control subsystem]: https://github.com/cockroachdb/cockroach/blob/0fda7519be7d7579526a19f4c9967f2e125d00ba/docs/tech-notes/admission_control.md

Epic CRDB-10353

**Comment by ajwerner** [comment]
cc @sumeerbhola

**Comment by ajwerner** [comment]
> are we adding new entries so that there are 5 total levels: UserLow = -5 and UserHigh = 5 ?

My understanding is that we want to add these two new values.

**Comment by ajwerner** [comment]
@RaduBerinde do you think it'd make sense to enforce at the rpc boundary that requests coming from secondary tenants have admission headers with values that fall in this more confined range as a follow-up task?

**Comment by msirek** [comment]
I am trying to determine if the scope of this issue in terms of modifying a currently-running transaction.  I guess what is mean by `Consider a SET admission_control_priority = ... during a transaction` is not the actual use of the `SET` syntax, but a means of doing something, perhaps through an API and not SQL, of something like:

a. broadcasting out to all nodes in the system a new WorkPriority for a given session and then checking when new work is started on behalf of a transaction belonging to that session. If found, update the priority in the txn's admission header.
  or
b. Something else?

Maybe some discussion on the use case would be helpful, like how the API would be invoked.  Maybe this point is related to support for https://github.com/cockroachdb/cockroach/pull/75840/.  For that, I'm just planning on adding a new field to `sessiondata.InternalExecutorOverride` so that calling InternalExecutor.ExecEx could apply a new priority to a statement execution request. Is this type of support what is meant by this item?  Thanks.

**Comment by ajwerner** [comment]
> I am trying to determine if the scope of this issue in terms of modifying a currently-running transaction. I guess what is mean by Consider a SET admission_control_priority = ... during a transaction is not the actual use of the SET syntax, but a means of doing something, perhaps through an API and not SQL, of something like:

That seems out of scope. Changing the level during transaction operation seems extremely advanced and far beyond what we were looking for with this issue IIUC. 

If anything, the way I'd think about it is as having the session variable really be a default for a transaction property. The `SET TRANSACTION` statement can only be the first statement in a transaction. After that, it's not allowed. An example of such a session variable is `default_transaction_read_only`. 

----

One other thought, upon reading this issue again, is if we should remove the word `priority` from the interface altogether and instead use the team `quality_of_service`. The decision to use that terminology came around the same time as I filed the issue.

**Comment by msirek** [comment]
> One other thought, upon reading this issue again, is if we should remove the word `priority` from the interface altogether and instead use the team `quality_of_service`. The decision to use that terminology came around the same time as I filed the issue.

Thanks. Yeah, I did see the latest in [slack](https://cockroachlabs.slack.com/archives/C01SRKWGHG8/p1643645299449259?thread_ts=1643643234.243309&channel=C01SRKWGHG8&message_ts=1643645299.449259) which is what I am following. 

> Changing the level during transaction operation seems extremely advanced and far beyond what we were looking for with this issue IIUC.
OK, maybe changing the level of something already running is out of scope, but do you this it is OK for a `Txn` to have the priority in its `admissionHeader` changed for a new call to InternalExecutor.ExecEx?  I see `Txn.AdmissionHeader()` already does this for txns that are locking, so I thought it might be OK.  

> The SET TRANSACTION statement can only be the first statement in a transaction. After that, it's not allowed. An example of such a session variable is default_transaction_read_only.
OK, thanks for the pointer about `default_transaction_read_only`. If I understand correctly, if we are doing auto-commits and are not wrapped in a new transaction via a `BEGIN` statement, `SET quality_of_service =` can be issued at any time and has immediate effect on the next statement.  But, if a `BEGIN` has been issued, `SET quality_of_service =` should only have an effect in the new transaction if it is the first statement after the `BEGIN`.  If it's not the first statement, it will still have an effect in the outer scope once the current transaction is closed via an `END` statement.  For example, setting `default_transaction_read_only = true` within a nested transaction can still affect statements issued after that transaction is closed (t8 can't be created in this case) :
```
root@localhost:26257/defaultdb> SET default_transaction_read_only = false;
SET


Time: 1ms total (execution 0ms / network 0ms)

root@localhost:26257/defaultdb> BEGIN;
BEGIN


Time: 0ms total (execution 0ms / network 0ms)

root@localhost:26257/defaultdb  OPEN> values (1);
  column1
-----------
        1
(1 row)


Time: 1ms total (execution 0ms / network 0ms)

root@localhost:26257/defaultdb  OPEN> SET default_transaction_read_only = true;
SET


Time: 1ms total (execution 0ms / network 0ms)

root@localhost:26257/defaultdb  OPEN> create table t7 (a int);
CREATE TABLE


Time: 10ms total (execution 10ms / network 0ms)

root@localhost:26257/defaultdb  OPEN> end;
COMMIT


Time: 18ms total (execution 18ms / network 0ms)

root@localhost:26257/defaultdb> create table t8 (a int);
ERROR: cannot execute CREATE TABLE in a read-only transaction
SQLSTATE: 25006

```

**Comment by msirek** [comment]
Note: TransactionModes will not be updated with `quality_of_service` as that won't be part of the `SET TRANSACTION` syntax.

**Comment by msirek** [comment]
Planning on updating the [List Sessions API](https://www.cockroachlabs.com/docs/api/cluster/v2#operation/listSessionshttps://www.cockroachlabs.com/docs/api/cluster/v2#operation/listSessions) to display the quality of service of the transaction. `WorkPriority` of `HighPri` would be listed as `"qualityOfService": "maximum"`.

Examples:
```
SET quality_of_service=expedited;
ANALYZE t1;
ANALYZE t2;
```
```
{
  "sessions": [
    {
      "nodeId": 1,
      "username": "root",
      "clientAddress": "127.0.0.1:56134",
      "applicationName": "$ cockroach sql",
      "activeQueries": [
        {
          "id": "16d3739e6bc4139b0000000000000001",
          "txnId": "662f680d-4de4-4f26-ad09-cde3aa55fe3a",
          "sql": "ANALYZE t2",
          "start": "2022-02-13T20:50:13.170245197Z",
          "isDistributed": false,
          "phase": 1,
          "progress": 0,
          "sqlNoConstants": "ANALYZE t2",
          "sqlSummary": "ANALYZE t2"
        }
      ],
      "start": "2022-02-13T20:43:44.562572907Z",
      "lastActiveQuery": "ANALYZE t1",
      "id": "FtNzQ/Dx1zIAAAAAAAAAAQ==",
      "allocBytes": "10240",
      "maxAllocBytes": "10566898",
      "activeTxn": {
        "id": "662f680d-4de4-4f26-ad09-cde3aa55fe3a",
        "start": "2022-02-13T20:50:13.170392076Z",
        "txnDescription": "\"sql txn\" meta={id=662f680d key=/Min pri=0.00543920 epo=0 ts=1644785413.170381908,0 min=1644785413.170381908,0 seq=0} lock=false stat=PENDING rts=1644785413.170381908,0 wto=false gul=1644785413.670381908,0",
        "numStatementsExecuted": 1,
        "numRetries": 0,
        "numAutoRetries": 0,
        "deadline": "0001-01-01T00:00:00Z",
        "implicit": true,
        "allocBytes": "10240",
        "maxAllocBytes": "10240",
        "readOnly": false,
        "isHistorical": false,
        "priority": "normal",
        "qualityOfService": "expedited"
      },
      "lastActiveQueryNoConstants": "ANALYZE t1"
    }
  ],
  "errors": [
  ]
}
```

```
SET quality_of_service=expedited;
insert into t1 select g,g,g FROM generate_series(1,10000000) g(g);
```
```
{
  "sessions": [
    {
      "nodeId": 1,
      "username": "root",
      "clientAddress": "127.0.0.1:56134",
      "applicationName": "$ cockroach sql",
      "activeQueries": [
        {
          "id": "16d373444361e1290000000000000001",
          "txnId": "a14d5320-459c-440d-aa7d-80a776576ea2",
          "sql": "INSERT INTO t1 SELECT g, g, g FROM ROWS FROM (generate_series(1, 10000000)) AS g (g)",
          "start": "2022-02-13T20:43:45.945691702Z",
          "isDistributed": false,
          "phase": 1,
          "progress": 0,
          "sqlNoConstants": "INSERT INTO t1 SELECT g, g, g FROM ROWS FROM (generate_series(_, _)) AS g (g)",
          "sqlSummary": "INSERT INTO t1 SELECT g, g, g FROM ROWS FROM (generate_series(_, ...))..."
        }
      ],
      "start": "2022-02-13T20:43:44.562572907Z",
      "lastActiveQuery": "SET quality_of_service = expedited",
      "id": "FtNzQ/Dx1zIAAAAAAAAAAQ==",
      "allocBytes": "10240",
      "maxAllocBytes": "10240",
      "activeTxn": {
        "id": "a14d5320-459c-440d-aa7d-80a776576ea2",
        "start": "2022-02-13T20:43:45.945813520Z",
        "txnDescription": "\"sql txn\" meta={id=a14d5320 key=/Table/86/1/1/0 pri=0.01167231 epo=0 ts=1644785025.945800794,0 min=1644785025.945800794,0 seq=280000} lock=true stat=PENDING rts=1644785025.945800794,0 wto=false gul=1644785026.445800794,0",
        "numStatementsExecuted": 1,
        "numRetries": 0,
        "numAutoRetries": 0,
        "deadline": "0001-01-01T00:00:00Z",
        "implicit": true,
        "allocBytes": "10240",
        "maxAllocBytes": "10240",
        "readOnly": false,
        "isHistorical": false,
        "priority": "normal",
        "qualityOfService": "maximum"
      },
      "lastActiveQueryNoConstants": "SET quality_of_service = expedited"
    }
  ],
  "errors": [
  ]
}
```

**Comment by msirek** [comment]
Example output of an EXPLAIN(OPT,ENV) statement showing modified quality_of_service:
```
-- Version: CockroachDB OSS unknown (linux amd64, built , go1.17.1)

-- reorder_joins_limit has the default value: 8
-- enable_zigzag_join has the default value: on
-- optimizer_use_histograms has the default value: on
-- optimizer_use_multicol_stats has the default value: on
-- locality_optimized_partitioned_index_scan has the default value: on
-- propagate_input_ordering has the default value: off
-- prefer_lookup_joins_for_fks has the default value: off
-- intervalstyle_enabled has the default value: off
-- datestyle_enabled has the default value: off
-- disallow_full_table_scans has the default value: off
-- large_full_scan_rows has the default value: 1000
-- cost_scans_with_default_col_size has the default value: off
SET quality_of_service = expedited;  -- default value: default
SET distsql = off;  -- default value: auto
-- vectorize has the default value: on

CREATE TABLE public.xy (
	x INT8 NOT NULL,
	y INT8 NULL,
	CONSTRAINT xy_pkey PRIMARY KEY (x ASC),
	FAMILY fam_0_x (x),
	FAMILY fam_1_y (y)
);

ALTER TABLE public.xy INJECT STATISTICS '[]';

CREATE TABLE public.ab (
	a INT8 NOT NULL,
	b INT8 NOT NULL,
	CONSTRAINT ab_pkey PRIMARY KEY (a ASC, b ASC),
	FAMILY fam_0_b (b),
	FAMILY fam_1_a (a)
);

ALTER TABLE public.ab INJECT STATISTICS '[]';

CREATE TABLE public.uv (
	u INT8 NOT NULL,
	v INT8 NOT NULL,
	CONSTRAINT uv_pkey PRIMARY KEY (u ASC, v ASC),
	FAMILY fam_0_v (v),
	FAMILY fam_1_u (u)
);

ALTER TABLE public.uv INJECT STATISTICS '[]';

EXPLAIN (OPT, ENV) SELECT * FROM (SELECT * FROM xy INNER JOIN ab ON y = a) INNER JOIN uv ON x = u;
----
inner-join (hash)
 ├── scan ab
 ├── inner-join (merge)
 │    ├── scan xy
 │    ├── scan uv
 │    └── filters (true)
 └── filters
      └── y = a
```
