### ISSUE TITLE
ui: redirect to different node if node we're talking to is down

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#7036]
Scenario: start a 3 node cluster, connect to the admin UI on one of the nodes, take that node down, UI becomes unresponsive/useless. I'm not sure what is possible here, but it seems like we could do better. The UI knows about the other nodes in the cluster. Seems feasible to perform some sort of redirect or send requests to one of the other nodes.

**Comment by tamird** [comment]
This is going to be non-trivial; nodes don't know each other's HTTP ports.

**Comment by bdarnell** [comment]
We could blindly redirect to another node in the hopes that it will be up, but sending requests to another node will be tricky with the browser security model. It may be better to just show a banner with links to alternative nodes for the user to click manually if they want to. 

I think this is one of those things where any serious deployment will be using a load balancer or at least a DNS alias so users of the admin UI won't be pinned to a single node.

**Comment by petermattis** [comment]
Ok, I'm not quite sure what the browser security model allows. A banner with links to alternate nodes to click manually would be fine.

**Comment by maxlang** [comment]
@tamird is there an issue tracking what you mentioned?

**Comment by tamird** [comment]
No.

**Comment by kuanluo** [comment]
> A banner with links to alternate nodes to click manually would be fine.

@petermattis's suggestion would be sufficient for onboarding to let people know the node they are connecting to is down. Reassigning to @mrtracy to keep track of this issue.

cc @dianasaur323 @nstewart

**Comment by couchand** [comment]
This is a nice idea, but we simply don't have enough information to do this in the general case.
