### ISSUE TITLE
sql: DistSQL loses named tuple field names

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#70360]
I've found behavior that indicates that DistSQL has some negative effect on named tuples / records, causing field names to be lost. This disrupts queries that use these field names during record->json conversions.

The following example demonstrates this behavior.
```sql
./cockroach demo --empty --nodes=9

CREATE TABLE tweets (
    tweet_id   INT PRIMARY KEY,
    message    STRING NOT NULL
);
ALTER TABLE tweets SPLIT AT (SELECT generate_series(1, 100));
INSERT INTO tweets VALUES (1, 'tweet1'), (2, 'tweet2');

SET distsql = off;
SELECT json_agg(tweets.*) FROM tweets;
#                                     json_agg
# --------------------------------------------------------------------------------
#   [{"message": "tweet1", "tweet_id": 1}, {"message": "tweet2", "tweet_id": 2}]

SET distsql = on;
SELECT json_agg(tweets.*) FROM tweets;
#                          json_agg
# ----------------------------------------------------------
#   [{"f1": 2, "f2": "tweet2"}, {"f1": 1, "f2": "tweet1"}]
```
I have not dug into this far enough to diagnose where the problem is coming from. It's possible that this is a known issue.

**Comment by jordanlewis** [comment]
This doesn't repro for me. Can you share the `EXPLAIN(DISTSQL)` output of a case where it fails?

**Comment by jordanlewis** [comment]
Nevermind, I found a repro.

**Comment by jordanlewis** [comment]
Thanks for reporting this! It was a small bug that somehow never got noticed in the tuple type deserialization routine. #70375 should resolve it.
