### ISSUE TITLE
ui: history sometimes doesn't work

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#7037]
Reproduction steps:
1. Visit the admin UI
2. Click on Nodes page
3. Back button is still disabled (but should be allowed)

This is using Chrome on Mac. Note that the Nodes page is a key detail. Visiting the Databases page and the browser back button works as expected.

**Comment by maxlang** [comment]
Should be fixed by the switch to ui/next. I can't repro anymore.
