### ISSUE TITLE
update go-libedit for illumos support

### ISSUE THREAD

**Issue by davepacheco** [cockroachdb/cockroach#70394]
CockroachDB includes go-libedit, which gets used for the `cockroach sql` prompt.  This wasn't working on illumos, so I submitted a fix upstream to knz/go-libedit#23.  I'd like to get that pulled into CockroachDB but I'm not sure how to do that.

For what it's worth, when I tested my fix for knz/go-libedit#23, I tested applying my changes to a copy of the CockroachDB v21.1.0 source with my copy of go-libedit vendored in, and that did fix the `cockroach sql` prompt.

Jira issue: CRDB-10055

**Comment by rafiss** [comment]
@davepacheco Thanks for filing this request! We should be able to get to it soon.

If you want to try doing the update in your own PR, you'll need to follow these instructions: https://github.com/cockroachdb/cockroach/blob/master/build/README.md#dependencies

**Comment by knz** [comment]
We're moving out of libedit in v23.1.
