### ISSUE TITLE
sql: investigate whether aggregate functions really exist in two groups

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#7039]
Currently sql/parser/builtins.go explains the following:
```
        // The functions are split into two groups when it comes to handling constant                                                                     // literal arguments:
        // - If the result of the aggregate function with constant arguments                                                                              //   is dependent on the number of rows it is run across (COUNT,
        //   SUM, VARIANCE, STDDEV), it should be marked as impure and not                                                                                //   provide an eval fn.
        // - If the result of the aggregate function with constant arguments                                                                              //   is independent on the number of rows it is run across (AVG,
        //   BOOL_AND, BOOL_OR), it should not be marked as impure and
        //   provide an fn implementation that handles this constant
        //   argument case.
```

Two issues here:

- I am not sure whether it is correct that bool_and and bool_or are placed in the category of pure functions. It looks to me that if table T has 0 rows, then `SELECT BOOL_AND(true) FROM T` should return NULL and not "true".

- the same really applies to AVG.

So I am not sure this split is justified. It looks to me we could simplify by having *all* aggregate functions impure and not provide any eval fn whatsoever. 

@nvanbenschoten please share what you think about this.

**Comment by nvanbenschoten** [comment]
@knz have you checked how Postges behaves with these aggregate functions running over 0 rows. I'm pretty sure I based the split on how PG handled the situation.

**Comment by knz** [comment]
@nvanbenschoten just tested; all aggregate functions *except for COUNT* return NULL if there are no rows in the source. COUNT then returns 0, regardless of its argument.

**Comment by nvanbenschoten** [comment]
Yep, looks like you're right. It's nice to be able to simplify this!
