### ISSUE TITLE
bazel: bug in `build_bazel_rules_nodejs` prevents `make bazel-generate`

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#70398]
`make bazel-generate` has recently started failing:

```
INFO: Repository npm instantiated at:
  /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/WORKSPACE:67:13: in <toplevel>
  /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/build_bazel_rules_nodejs/index.bzl:83:18: in yarn_install
Repository rule yarn_install defined at:
  /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:890:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'npm':
   Traceback (most recent call last):
        File "v", line 786, col
umn 36, in _yarn_install_impl
                is_windows_host = is_windows_os(repository_ctx)
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/build_bazel_rules_nodejs/internal/common/os_name.bzl", line 65, column 19, in
 is_windows_os
                return os_name(rctx) == OS_NAMES[0]
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/build_bazel_rules_nodejs/internal/common/os_name.bzl", line 62, column 9, in
os_name
                fail("Unsupported operating system {} architecture {}".format(os_name, arch))
Error in fail: Unsupported operating system freebsd architecture amd64
```

Epic CRDB-8036

**Comment by knz** [comment]
NB: I can fix the conditional in `/build_bazel_rules_nodejs/internal/common/os_name.bzl` manually but then I get the following error:

```
ERROR: An error occurred during the fetch of repository 'npm':
   Traceback (most recent call last):
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 787, column 31, in _yarn_install_impl
                node = repository_ctx.path(get_node_label(repository_ctx))
Error in path: Unable to load package for @nodejs_freebsd_amd64//:bin/node: The repository '@nodejs_freebsd_amd64' could not be resolved
```

**Comment by knz** [comment]
This is strange, because just 2 weeks ago this used to work.
Is this a regression introduced by #67066?

I see in that PR that the nodejs rule package was upgraded to 4.1, which wasn't exactly required for the work in that PR.
cc @koorosh

**Comment by knz** [comment]
I'm also welcoming of anything I can put/change in my WORKSPACE to work around this issue.

**Comment by koorosh** [comment]
@knz , could you test if change in PR (#70400) resolves this problem or not? `yarn_install` rule (in WORKSPACE) requires additional args to follow the same behaivor as in Makefile. (it is one line fix)

**Comment by knz** [comment]
1) It didn't fix the problem fully, still same error:

```
ERROR: An error occurred during the fetch of repository 'npm':
   Traceback (most recent call last):
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 787, column 31, in _yarn_install_impl
                node = repository_ctx.path(get_node_label(repository_ctx))
Error in path: Unable to load package for @nodejs_freebsd_amd64//:bin/node: The repository '@nodejs_freebsd_amd64' could not be resolved
```

2) The real problem is that both `make bazel-generate` and `make buildshort` actually should not have *any* dependency on npm / yarn. There should be a way to express these rules, that `yarn_install` is not computed unless we're building a full binary.

3) I'm also interested to know if there's a way to tell bazel to use my locally installed npm / yarn, instead of using the version in a sandbox?

**Comment by rickystewart** [comment]
@koorosh and I synced about this. The call to `yarn_install` shouldn't be there at all. When we fully switch to self-managed NPM dependencies this should go away. @koorosh is working on that now(?)

**Comment by knz** [comment]
thank you!

**Comment by knz** [comment]
Apparently this also impact non-freebsd users, see
https://github.com/cockroachdb/cockroach/pull/70285#issuecomment-924206504

**Comment by knz** [comment]
@andreimatei reports that the following workaround can be used until this gets fixed:

```
bazel run //:gazelle
```

**Comment by rickystewart** [comment]
That command doesn't do everything that `make bazel-generate`/`./dev generate bazel` does, but yeah it should handle most cases without hitting the bug above.
