### ISSUE TITLE
Reduce sampling QPS threshold for the CC telemetry logging channel

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#70393]
The current QPS threshold of 2000 is too high to be supported by the new logging telemetry channel. We need to reduce this threshold to a supported value at which sampling begins as well as adjust the sampling frequency.

Additional context is outlined [here](https://cockroachlabs.atlassian.net/wiki/spaces/SQLOBS/pages/2180186377/21.2?focusedCommentId=2196701389#comment-2196701389)

**Comment by maryliag** [comment]
From @knz comment in one of the docs `I would be in favor of reducing it, so we can start sampling after e.g. 5 queries per second.`.
Is 5 a good value to change the default to? At least on this first iteration (before dealing with the more complex solution on https://github.com/cockroachdb/cockroach/issues/70553 )
@logston

**Comment by logston** [comment]
@maryliag, from the SRE/pipeline perspective, anything less than or equal to 10 log events/second (LLPS) emitted by CRDB is sufficient. So long as the sampling produced at max 10 LLPS, the sampling can start at 10 queries per second.

**Comment by xinhaoz** [comment]
Closing this issue in favour of https://github.com/cockroachdb/cockroach/issues/70553.
