### ISSUE TITLE
sql: migrate bulk job cancellation to `DeleteRange`

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#70428]
As described in #69380, once `DeleteRange` gains MVCC tombstones in #70415 and a lower timestamp predicate in #70416, cancellation of bulk operations such as `IMPORT INTO` and others should be migrated to using `DeleteRange` rather than `RevertRange`. `DeleteRange` does not violate MVCC invariants which other components rely on.

Jira issue: CRDB-10071

Epic CRDB-2624

**Comment by msbutler** [comment]
Import INTO jobs now roll back with DeleteRange!

Rollbacks of RESTORE and IMPORT of new tables will be MVCC compliant once the gcjob is mvcc compliant @ajwerner @erikgrinaker

**Comment by erikgrinaker** [comment]
@msbutler GC job merged in #85878. Anything left to do here?

**Comment by msbutler** [comment]
yup!
