### ISSUE TITLE
Surface "Last cleared" date in the console for the Statements and Transactions pages via SQL

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#70424]
We surface the "Last cleared" date in the console for the Statements and Transactions pages. This should also be programatically available via SQL.

![image](https://user-images.githubusercontent.com/81193618/134027345-639076b5-e0df-4e38-8955-77d62c24e1a4.png)

_This will be available starting in 21.2 for persisted statistics. Users can query the table for the min Interval Start Time._

**Comment by kevin-v-ngo** [comment]
Note with persisted stats, the user can query the min and max dates in this table to retrieve the "Last available date" of statement/transaction statistics. 

@Annebirzin, on a related note, we should continue discussion on what the updated UX should be in the console here with persisted stats. Perhaps we show just 'Start' and 'End' time selected by the user.

**Comment by Annebirzin** [comment]
@kevin-v-ngo  My thought is that we should remove this timestamp since it is redundant with the new time picker (which shows start/end time). 

Also,  is the 'clear stats' link still relevant if users can now select time intervals?

**Comment by kevin-v-ngo** [comment]
Thanks Anne. I've created a tracking [issue](https://github.com/cockroachdb/cockroach/issues/70465). 

Yes, still relevant. For scenarios where the user wants to do quick A/B comparisons when getting started or reduce overall storage size they would still clear stats. It's also helpful for quick benchmark/demo purposes. With the last cleared/reset date removed, where do you suggest moving the clear stats link?

**Comment by Annebirzin** [comment]
@kevin-v-ngo I'm thinking we could change it to button and move it next to the time picker. It would need to bump to the right when the 'reset time' action appears (see screenshots below). If we want to include other statement-level actions in the future, this button could turn into a dropdown of actions. ([figma designs](https://www.figma.com/file/MoSPFkEyJfGipCmQvvLg1a/21.2_SQL-obsrv_query-performance?node-id=2929%3A124036)) 
 
![Screen Shot 2021-09-21 at 5 26 26 PM](https://user-images.githubusercontent.com/51920721/134250077-10931824-c589-447e-aec4-7523f1efb901.png)

![Screen Shot 2021-09-21 at 5 26 14 PM](https://user-images.githubusercontent.com/51920721/134250254-fad220d0-6876-4e36-849e-2dd2c1ff877b.png)

**Comment by Annebirzin** [comment]
@kevin-v-ngo thinking this through a bit more, maybe we do still need the 'Last cleared' timestamp. This timestamp reflects when the stats were cleared, not which time interval a user is viewing statements for. I think I was conflating the two ideas (our users might find this confusing as well). 

@maryliag left a related [Slack comment](https://cockroachlabs.slack.com/archives/G01Q9D01NTU/p1632319236071100) regarding the behavior of the clear stats link. If we go with option 1 (Continue cleaning just the in-memory stats), maybe the current timestamp and link are fine as is?

**Comment by kevin-v-ngo** [comment]
For the last cleared timestamp, previously, since everything was only 1 hour in-memory, the timestamp was more used to identify when which statistics were collected **and** surfaced in the console. This changes a bit with persisted stats since the user has the flexibility to change the start and end time now.

We now need to expose two pieces of info in the UI to provide clarity and the same behavior as before 1) what interval we are surfacing the stats in the console currently and 2) when did we start collecting the stats. 

For 1), we have this today with the time picker. For 2), This would surface during validation and selecting the start time (we have another issues for this since we couldn't get to this in V1). Thoughts?

**Comment by kevin-v-ngo** [comment]
_This issue will be addressed starting in 21.2 for persisted statistics. Users can query the table for the min Interval Start Time._
