### ISSUE TITLE
kvserver: C2C handling of `DeleteRange` aka MVCC range tombstones

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#70433]
Once MVCC range deletion tombstones (#70412) are emitted across rangefeeds (#82449), they need to be handled by cluster-to-cluster (C2C) streaming. Initially, these will only be used for schema GC (e.g. dropping tables) and rolling back a cancelled import. When that happens, the `DeleteRange` operation must be replayed on the target cluster using an MVCC range tombstone.

NB: MVCC range tombstones will also be included in `AddSSTable` events emitted across rangefeeds, and these must be handled via specialized range key functionality on the SST iterator, e.g. `HasPointAndRange()` and `RangeKeys()`. See `SimpleMVCCIterator` documentation for details.

#CRDB-7188
Jira issue: CRDB-10074
Epic CRDB-7188

**Comment by ajwerner** [comment]
It seems to me like the RangeFeed ought to opt into receiving these (much like SSTs) and regular changefeeds should not except them and should fail if they see one.

**Comment by erikgrinaker** [comment]
I split out the rangefeed implementation to #82449, and repurposed this for any C2C and CDC work. Working on the rangefeed bits now, and expect to have a PR ready shortly -- there's still work remaining on MVCC range tombstones themselves though.
