### ISSUE TITLE
jobs: provide a metric to determine non-idle running jobs

### ISSUE THREAD

**Issue by darinpp** [cockroachdb/cockroach#70538]
We are currently adding a new job `AUTO SPAN CONFIG RECONCILIATION` that will be continuously running on each tenant pod. This is a problem as the number of currently running jobs is used as an indication that a tenant pod is idle.

We have to add a metric that can provide the number of currently running non-idle jobs. 

And alternative would be to hard code on the CC side but that isn't optimal as each new such jobs will require a massive maintenance effort. Alternatively - such continuous running jobs can be considered terminable at all times and reported through a metric. This is also non-optimal as we want to wait for jobs doing useful stuff to finish before terminating the pods. 

https://cockroachlabs.slack.com/archives/C020NSBH63F/p1632262147058800

**Comment by irfansharif** [comment]
Just going to cargo cult whatever we do for https://github.com/cockroachdb/cockroach/issues/74747.
