### ISSUE TITLE
Add Interval Start Time to the statement details page

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#70545]
In the V1 experience of persisted statistics, we added interval start time to the statements and transactions overview page. When the user clicks on a specific interval to view statement statistics details of the fingerprint, we should indicate which interval they are viewing the stats for by including the Interval Start Time in the statement details page. 

@Annebirzin @xinhaoz

**Comment by Annebirzin** [comment]
Including [Figma designs](https://www.figma.com/file/MoSPFkEyJfGipCmQvvLg1a/21.2_SQL-obsrv_query-performance?node-id=3415%3A68113) for adding 'interval start time' on statement detail page

![Screen Shot 2021-09-23 at 11 08 48 AM](https://user-images.githubusercontent.com/51920721/134533673-efdc62f8-33b9-42cf-ad10-cd9ba072954e.png)
