### ISSUE TITLE
kvclient: return partial DistSender responses on range boundaries when paginating

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#70564]
In an [internal Slack thread](https://cockroachlabs.slack.com/archives/C0KB9Q03D/p1630007804010500), @dt argues that when the client has requested pagination via `MaxSpanRequestKeys` or `TargetBytes` limits, DistSender should return partial results (if any) when encountering a range boundary rather than adjusting the limits and sending additional requests to subsequent ranges. The rationale is that DistSender can otherwise end up sending requests with very small limits, resulting in a larger number of range requests overall as the client paginates over the entire span.

Since the client must already be prepared to handle `ResumeSpan`, it should not make any difference if one is returned early. However, we must audit callers to make sure this is always the case -- in particular, a SQL `LIMIT` clause must not simply be passed through to DistSender with the expectation that the response will always be filled up to the limit.

Broadly, the DistSender logic would be as follows: when encountering a range boundary, if `MaxSpanRequestKeys` or `TargetBytes` is set and a partial response has been obtained, immediately return the response with an appropriate `ResumeSpan` and `ResumeReason: RESUME_RANGE_BOUNDARY`.

Related to ongoing work for #68050 in #68370.

**Comment by erikgrinaker** [comment]
Looks like we're going to need a version gate for this, as `Txn.Iterate()` assumes that `MaxSpanRequestKeys` always fills the entire response:

https://github.com/cockroachdb/cockroach/blob/0d7c407710193275a85514bcf3f43e529aa2d64f/pkg/kv/txn.go#L612-L614

This needs to be rewritten to use `ResumeSpan`. There may be others as well, running further tests.

**Comment by erikgrinaker** [comment]
After fixing `Txn.Iterate()` and disabling tests that specifically test the DistSender behavior we're changing, I was able to run the `testshort` and `tpcc/headroom/n4cpu16` test suites without any failures. So it doesn't look like this is going to be too involved, but it's a shame that we'll need that version gate.

I'll start working on a PR.

**Comment by erikgrinaker** [comment]
>Looks like we're going to need a version gate for this, as `Txn.Iterate()` assumes that `MaxSpanRequestKeys` always fills the entire response

Actually, maybe this isn't true, since I suppose `Txn.Iterate` will always use a local `DistSender`. The callers all seem to work as they should.

**Comment by nvanbenschoten** [comment]
This is an interesting idea. This allows us to avoid one KV RPC per memory/key limit during large scans. The trade-off we'd be making is that we're now traversing the KV sender stack once per range during scans. Unless I'm missing something, it's strictly a performance concern (right?).

Whether or not this is a good trade-off depends on the size of ranges, the pagination size, the relationship between those two sizes, the RPC cost, the sender stack traversal cost, and the relationship between those two costs. The RPC cost factor is especially interesting with the local RPC fast-path, which we often expect to hit with DistSQL. That is too many variables to have a firm intuition about, so we'll want to run some experiments to better understand whether this is a good trade-off to make or not based on some representative workloads. Have we thought about a testing plan to validate the change?

**Comment by erikgrinaker** [comment]
>Unless I'm missing something, it's strictly a performance concern (right?).

Correct. This was originally requested by Bulk IO regarding exports, I'm guessing they saw some sort of pathological behavior with tiny export requests. Care to elaborate @dt?

SQL also has a performance-related use-case for this in #47044 where they have anecdotal evidence of additional latency that would be avoided if they could halt a limited scan on a range boundary.

>Have we thought about a testing plan to validate the change?

Not yet, but we should. If we make it optional (as @andreimatei has [requested](https://github.com/cockroachdb/cockroach/pull/70763#pullrequestreview-764720121)) it would put the onus on the caller to use this when appropriate though (and by extension, to benchmark whether it would be appropriate), but it'd still be valuable to obtain some performance data.

**Comment by dt** [comment]
> it's strictly a performance concern

Yep, indeed. We don't actually see a pathological behavior today with exports but that is because we actively circumvent the current behavior -- of going to the next range for (just a little bit) more -- by lying in Export's NumBytes result field.

>   local RPC fast-path

It isn't just the network though, since each request has to start with a `Seek` before it can iterate and that Seek is often a big chunk of the over all cost compared to the magical cost of iterating some additional rows thereafter. Ideally, when we move on to the next range and send a new RPC which has to do a Seek, we'd then iterate up to the full pagination limit, rather than just some smaller limit based on however far under the limit the last scan of the prior range ended.

**Comment by erikgrinaker** [comment]
>Yep, indeed. We don't actually see a pathological behavior today with exports but that is because we actively circumvent the current behavior -- of going to the next range for (just a little bit) more -- by lying in Export's NumBytes result field.

This makes me really sad. It's almost worth implementing this issue just to stop doing this.
