### ISSUE TITLE
*: stop gossiping the system config span

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#70560]
And start allowing writes before DDLs in transactions. This is tracking issue for what should be the last piece of  #66348 -- work we've been doing so that we no longer need to gossip the system config span. Once all the PRs in #67679 have settled, we should be able to flip the envvar introduced in #69658, and soon after decide to stop gossiping the system config span entirely.

Epic CRDB-10489

**Comment by ajwerner** [comment]
This will solve https://github.com/cockroachdb/cockroach/issues/54477.

Another blocker relates to the `system.settings` propagation. I have an early attempt to deal with settings in the system tenant in https://github.com/cockroachdb/cockroach/pull/69269.

**Comment by irfansharif** [comment]
It should also put a plug on our most pressing schema scalability (ala #63206). It looks like we're [exploring](https://cockroachlabs.slack.com/archives/CARM0PTK4/p1632907623158300) integrations with http://prisma.io, and the # of tables created in their test-suite run into the O(N^2) properties of our system config span. @tbg, @nvanbenschoten -- I realize our 22.1 planning surveys have closed out and I'm curious to see what comes of it, but I think we should seriously try to schedule this work over the next release.

**Comment by irfansharif** [comment]
A SQL dependency on the system config span that we'd also want to get rid of: https://github.com/cockroachdb/cockroach/issues/70558.
