### ISSUE TITLE
cdc: surface backfill checkpoints in running status

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#70570]
When running a backfill over a large table, we do not update the running status of the changefeed until it completes. While the backfill is running we show "running: resolved=0,0" as the running_status. And this shows up in the db console as:
![image](https://user-images.githubusercontent.com/13264141/134361112-d1e4eee8-d271-4307-9762-9ec711fed38c.png)

This is confusing on the user end, and ideally we would give information on the changefeed progress so that you know you're changefeed is progressing.  We added checkpointing to backfills in 21.2, and so should theoretically be able to update the status. 

CRDB-10204

Jira issue: CRDB-10125

**Comment by miretskiy** [comment]
Fixed via backfill checkpointing, plus observability into the number of ranges remaining.
