### ISSUE TITLE
debug: introduce ability to optionally include table statistics with a flag

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#70576]
**Is your feature request related to a problem? Please describe.**
Debug zip today does not collect table statistics. Picture a scenario where TSE needs to capture a debug zip for understanding slowness. Then it turns out we also need to look at the stats and need to additionally capture a stmt bundle. Speaking with eng in this thread https://cockroachlabs.slack.com/archives/C01RX2G8LT1/p1632323362141200 it seems stats were pulled out intentionally in situations with many tables in a database.

**Describe the solution you'd like**
Introducing an optional flag to include stats as part of debug zip would be welcome, i.e. cockroach debug zip --with-stats

**Describe alternatives you've considered**
The current workaround is to collect stmt bundle separate from the debug zip.

**Additional context**

Jira issue: CRDB-10128

**Comment by yuzefovich** [comment]
Actually we do include the contents of `system.table_statistics` table into the debug.zip, so this has been addressed at some point.
