### ISSUE TITLE
TLP Failure with COUNT

### ISSUE THREAD

**Issue by nehageorge** [cockroachdb/cockroach#70587]
**Describe the problem**

The count is incorrectly computed for the unpartitioned query in the left join oracle. 

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behaviour:

1. Create a new file with the following SQL:
<details><summary>See SQL statements</summary>

```
CREATE TABLE table1 ();

CREATE TABLE table2 (
	col2_0
		BOOL[],
	col2_1
		TIMETZ,
	col2_2
		FLOAT4,
	col2_3
		DATE,
	col2_4
		CHAR,
	col2_5
		STRING AS (lower(col2_4)) VIRTUAL,
	UNIQUE (col2_5 DESC)
);

INSERT
INTO
	table2 (col2_1, col2_2, col2_0, col2_4)
VALUES
	(
		'09:18:34.546805+12:28:00',
		0,
		ARRAY[]:::BOOL[],
		' ':::STRING
	);

;

DELETE FROM table2 WHERE true;

\echo Selecting from table 1... no rows
SELECT * from table1;

\echo Selecting from table 2... no rows
SELECT * FROM table2;

\echo Rows selected in unpartitioned query, pre-count
SELECT
  *
FROM
  table2
  LEFT JOIN table1 ON true
UNION ALL
  SELECT
    *
  FROM
    table2
    LEFT JOIN table1 ON
        false
UNION ALL
  SELECT
    *
  FROM
    table2
    LEFT JOIN table1 ON
        false;

\echo Rows selected in partitioned query, pre-count
SELECT
  *
FROM
  table2 AS tab_2196
  LEFT JOIN table1 ON
      '1988-11-29'
      IN (
          tab_2196.col2_3,
          tab_2196.col2_3
        )
UNION ALL
  SELECT
    *
  FROM
    table2 AS tab_2196
    LEFT JOIN table1 ON
        NOT
          (
            '1988-11-29'
            IN (
                tab_2196.col2_3,
                tab_2196.col2_3
              )
          )
UNION ALL
  SELECT
    *
  FROM
    table2 AS tab_2196
    LEFT JOIN table1 ON
        (
          '1988-11-29'
          IN (
              tab_2196.col2_3,
              tab_2196.col2_3
            )
        ) IS NULL;

\echo These rows are the same, now take the counts:

\echo Unpartitioned query count, expected 0, got 3:

SELECT
  count(*)
FROM
  (
    SELECT
      *
    FROM
      table2
      LEFT JOIN table1 ON true
    UNION ALL
      SELECT
        *
      FROM
        table2
        LEFT JOIN table1 ON
            false
    UNION ALL
      SELECT
        *
      FROM
        table2
        LEFT JOIN table1 ON
            false
  );

\echo Partitioned query count, expected 0, got 0:
SELECT
  count(*)
FROM
  (
    SELECT
      *
    FROM
      table2 AS tab_2196
      LEFT JOIN table1 ON
          '1988-11-29'
          IN (
              tab_2196.col2_3,
              tab_2196.col2_3
            )
    UNION ALL
      SELECT
        *
      FROM
        table2 AS tab_2196
        LEFT JOIN table1 ON
            NOT
              (
                '1988-11-29'
                IN (
                    tab_2196.col2_3,
                    tab_2196.col2_3
                  )
              )
    UNION ALL
      SELECT
        *
      FROM
        table2 AS tab_2196
        LEFT JOIN table1 ON
            (
              '1988-11-29'
              IN (
                  tab_2196.col2_3,
                  tab_2196.col2_3
                )
            ) IS NULL
  );

```

</details>

2. Run `./cockroach demo -f /path/to/newfile`
3. Look at console output to see failure output.

**Expected behaviour**
Count of unpartitioned query should be 0 like the partitioned query, but we get 3.

**Additional context**
Essentially, the correct rows are selected in the unpartitioned query before taking the count (no rows) but then once the count is taken, we get a count of 3 instead of 0. Looking at the query plans of the former and the latter, the structure is the same except for the "group(scalar)" in the count one, and the scanned table in the non-aggregated query "table2@primary" is replaced by "table2@table2_col2_5_key" in the incorrect "count" query.

**Comment by mgartner** [comment]
I think this is the same problem as #69665 based on the fact that `table2` has `col2_4 CHAR`, `col2_5 STRING AS (lower(col2_4)) VIRTUAL`, and `UNIQUE (col2_5 DESC)`.

**Comment by nehageorge** [comment]
Oh yes, that would make sense. I see the pattern looks the same as that issue on closer investigation. Closing this for now.

**Comment by rytaft** [comment]
Seems likely. I think what's happening here is that `DELETE FROM table2 WHERE true;` successfully deletes the row from the primary index, but fails to delete the row from the secondary index (perhaps due to the computed column being incorrectly evaluated). We see different results in the count(*) queries because one is using the primary index while the other is using the secondary index.

**Comment by mgartner** [comment]
Correct. The DELETE is actually fine - it calculates the computed column correctly and issues the correct K/V delete command. The problem is that the INSERT is inserting the wrong key for the secondary index, so it remains after the DELETE.
