### ISSUE TITLE
Include custom schema definitions in SHOW CREATE ALL TABLES

### ISSUE THREAD

**Issue by EdeMeijer** [cockroachdb/cockroach#70620]
Since `cockroach dump` is being deprecated, I'm trying to use `SHOW CREATE ALL TABLES` to obtain a schema dump that I can check into version control so we have diffs of DB schema changes and a starting point for running migrations. However, we use user defined schemas, and these are not included in the output.

**Describe the solution you'd like**
I'd like that `SHOW CREATE ALL TABLES` outputs DDL for user defined schemas (`CREATE SCHEMA` statements), so that the complete output can be used to create a new database with the correct schema (for integration tests, test environments, whatnot).

**Describe alternatives you've considered**
I could manually maintain an additional file with user defined schema definitions, but it would be better if it could all be managed by this command.

**Comment by RichardJCai** [comment]
Instead of adding schema definitions to `SHOW CREATE ALL TABLES` we'll probably create a separate command for it ie `SHOW CREATE ALL SCHEMAS` and maybe have something like `SHOW CREATE ALL OBJECTS` to dump all database objects.

**Comment by EdeMeijer** [comment]
Sounds great. I was already kind of surprised that this command includes views, so I figured it was kind of a catch-all.

**Comment by rafiss** [comment]
note to implementor: for types we should be able to get the CREATE statements from `crdb_internal.create_type_statements`

**Comment by EdeMeijer** [comment]
I noticed the same goes for `GRANT`s, they are not included in the `SHOW CREATE ALL TABLES` output, so we might need another command for those (and include them in the ALL OBJECTS version if that's going to be a thing).
