### ISSUE TITLE
roachprod does not clean up ssh keys in AWS

### ISSUE THREAD

**Issue by jlinder** [cockroachdb/cockroach#70635]
We have many unused ssh keys that were created by roachprod and that are no longer used. Make roachprod clean these up as part of normal operations.

This issue was originally created in the dev inf project. See it here: DEVINF-34 .

Epic CRDB-10428

Jira issue: CRDB-10155

**Comment by tbg** [comment]
@jlinder did you really intend for this to be a release-blocker (or even release-21.2)?

**Comment by jlinder** [comment]
@tbg Though we did cover this in the release meeting, adding a comment here as well.

I did intend for this to be a release-blocker (GA blocker really). This fix needs a change to roachprod to add tags to new ssh key resources created by roachprod in AWS (this was not clear from this issue's body). Since nightly roachtests for each release branch use the roachprod on their branch, this change needs to get onto the `release-21.2` branch. And given the new process of having any backport to `release-21.2` reviewed and approved before merging, I brought it up to the weekly review meeting.

FTR, I think we over-indexed on what we require to be reviewed. This change shouldn't have needed that level of review.

**Comment by srosenberg** [comment]
`roachprod gc` for AWS keys was implemented in [1]. More recently, GCE keys were tackled in [2]. At this point, we have a fairly complete solution, so I'm closing the issue.

[1] https://github.com/cockroachdb/cockroach/pull/70603
[2] https://github.com/cockroachdb/cockroach/pull/119106
