### ISSUE TITLE
geo: support 3D linestring (linestringz)

### ISSUE THREAD

**Issue by timgraham** [cockroachdb/cockroach#70653]
**Is your feature request related to a problem? Please describe.**

Django uses 3D linestrings. Currently it seems unsupported.

**Describe the solution you'd like**

```sql
CREATE TABLE "geo3d_interstate3d" (
    "id" integer NOT NULL PRIMARY KEY DEFAULT unique_rowid(),
    "name" varchar(30) NOT NULL,
    "line" geometry(LINESTRINGZ,4269) NOT NULL
)
```
gives `ProgrammingError: at or near "linestringz": syntax error`.

**Additional context**

Tested with CockroachDB v21.2.0-alpha.00000000-4446-gf9de59ac36 @ 2021/09/24 00:41:35 (go1.16.6).

**Comment by otan** [comment]
hahahaha this bug is funny
