### ISSUE TITLE
tryCondenseRefreshSpans

### ISSUE THREAD

**Issue by 123youyouer** [cockroachdb/cockroach#70678]
We found a problem might caused by the following change:

    kvclient: make the byte limit for condensableSpanSet inclusive
    https://github.com/cockroachdb/cockroach/commit/f1b43a62f6044be56fadc13db9e61b22a9b95fd2

We think after changing the comparison in function maybeCondense() from '<' to
'<=', the comparison in tryCondenseRefreshSpans() should also be changed:

```go
func (sr *txnSpanRefresher) tryCondenseRefreshSpans(ctx context.Context, maxBytes int64) bool {
	if sr.knobs.CondenseRefreshSpansFilter != nil && !sr.knobs.CondenseRefreshSpansFilter() {
		return false
	}
	sr.refreshFootprint.maybeCondense(ctx, sr.riGen, maxBytes)
	return sr.refreshFootprint.bytes < maxBytes // should also be changed to <=
}
```

otherwise when sr.refreshFootprint.bytes is exact maxBytes, the above will
result in wrong behavior and cause the operation to retry forever.

**Comment by ajwerner** [comment]
> cause the operation to retry forever.

Can you spell out more how it will retry forever? It's not called in a for loop. It might lead to more retries, but it'd be interesting to find a workload that can hit this pathologically. 

Say `sr.refreshFootprint.bytes = N` and `maxBytes = N`. That will lead us to call `tryCondenseRefreshSpans` which will call `maybeCondense`.

In `maybeCondense` we'll short circuit and return without condensing. At that point `tryCondenseRefreshSpans` will return false and will clear out the set of refresh spans. That does mean that the transaction will not be able to refresh anymore and you might see retries. That seems pretty hard to hit though. Are you seeing it in the wild?

cc @andreimatei

**Comment by 123youyouer** [comment]
In the restore operation.

```go
err := execCfg.DB.Txn(ctx, func(ctx context.Context, txn *kv.Txn) error {
		if err := stats.InsertNewStats(ctx, execCfg.InternalExecutor, txn, latestStats); err != nil {
			return errors.Wrapf(err, "inserting stats from backup")
		}
		details.StatsInserted = true
		if err := job.SetDetails(ctx, txn, details); err != nil {
			return errors.Wrapf(err, "updating job marking stats insertion complete")
		}
		return nil
	})
```

In the InsertNewStats function, when inserting a large number of rows. It happens to reach this boundary value. The recovery operation will always try this operation, and I suspect that a single statement (implicit transaction) inserting multiple rows may also reproduce this error

**Comment by lunevalex** [comment]
@123youyouer I am going to close this, please re-open if you have a more concrete suggestion.
