### ISSUE TITLE
ui: DB Console metric panels do not load for non-admins

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#70702]
Tracking for Cluster UI team backlog - picked up from [cockroachlabs/support/issues/1233](https://github.com/cockroachlabs/support/issues/1233) 

CRDB non-root user metric panels do not load. Some load - but not all. We do not have fine-grained metric panel controls - they should all load.

I have tried this on two clusters running 21.1.7+ with the same outcome. This does NOT occur on 20.2.8.

user created with :
```
CREATE ROLE "username" WITH LOGIN VIEWACTIVITY PASSWORD "password";
```

**Context**
Some background - according to @rafiss:
In [cockroachdb/cockroach#67068](https://github.com/cockroachdb/cockroach/pull/67068) -- the `/_status/nodes` endpoint now requires ADMIN privileges, and that endpoint powers these charts.

It shows up in the v21.1.8 release notes https://www.cockroachlabs.com/docs/releases/v21.1.8.html#security-updates

That means starting in v21.1.8, this creates a regression for DB Console users who can no longer see these panels. (This behavior is also in v20.2.14 and v21.2.0)

**Comment by thtruo** [comment]
cc @nathanstilwell @Santamaura for awareness
cc @knz re idea around using an alternative endpoint to support the metric panel, if those exist

**Comment by knz** [comment]
>  using an alternative endpoint to support the metric panel, if those exist
Need to create one.

This needs to be supported by obs-infra btw.

Maybe @dhartunian can chime in.

**Comment by thtruo** [comment]
Ack, thanks Raphael. Following up with David and Nam. Mentioned this in a Slack thread - I jotted down a few bullets here https://docs.google.com/document/d/1honL5CbFepF6QXxe1Q7MqwX0UQeLvtKSfc6jnLan3SA/edit to reflect the current options we can consider.

**Comment by thtruo** [comment]
Had a conversation with @dhartunian and @nkodali - I'm marking this issue as a GA-blocker. The security-related change that resulted in gating the `/_status/nodes` endpoint https://github.com/cockroachdb/cockroach/pull/67068  resulted in this user-facing DB Console UI regression.
