### ISSUE TITLE
opt: support for filters in the multiple MIN/MAX subqueries rewrite

### ISSUE THREAD

**Issue by msirek** [cockroachdb/cockroach#70735]
**Is your feature request related to a problem? Please describe.**
https://github.com/cockroachdb/cockroach/pull/70496 adds a logical query rewrite for multiple MIN and MAX aggregate expressions rewritten as scalar subqueries which may be performed by fast limited scans from the primary key or an index, but it does not support WHERE clause filters.  For example:

`create table if not exists t1 (a int, b int, primary key(a));`
### The following query triggers the rewrite
`select min(a), max(a) from t1;`
### The following query does not trigger the rewrite
`select min(a), max(a) from t1 where b < 6;`

**Describe the solution you'd like**
Add WHERE clause support for this rewrite.  Currently this type of query with a single MAX or MIN expression, such as the following, uses the rewrite:
`select min(a) from t1 where b < 6;`

**Describe alternatives you've considered**
No alternatives considered.

**Additional context**

**Comment by darinpp** [comment]
Hey @msirek, do you plan to work on this after https://github.com/cockroachdb/cockroach/pull/70496 is merged? You can assign it to yourself if yes.

**Comment by msirek** [comment]
> Hey @msirek, do you plan to work on this after #70496 is merged? You can assign it to yourself if yes.

Hi @darinpp, I'd like to assign it to myself, but I don't seem to have the proper permissions in github to do so.

**Comment by rytaft** [comment]
Thanks! Just assigned to you, @msirek.
