### ISSUE TITLE
sql: COPY CSV does not support JSON types

### ISSUE THREAD

**Issue by steven-sheehy** [cockroachdb/cockroach#70736]
**Describe the problem**

Attempting to insert data via COPY CSV that contains a json or jsonb data type fails. The same COPY syntax works in PostgreSQL. The same syntax works in CockroachDB with insert statements. It's not documented to not be supported.

**To Reproduce**

The same commands below can be repeated for `jsonb` type:

```sql
cockroach demo
movr=> create table json_test(id int, info json);
CREATE TABLE
movr=> insert into json_test(id, info) values (1, '{"foo": 1}');
INSERT 0 1
movr=> select * from json_test;
 id |    info
----+------------
  1 | {"foo": 1}
(1 row)

movr=> copy json_test from stdin with csv;
Enter data to be copied followed by a newline.
End with a backslash and a period on a line by itself, or an EOF signal.
>> 2,"{""foo"":1}"
>> \.
ERROR:  read CSV record: record on line 1: wrong number of fields
```

**Expected behavior**
Copy statements with JSON data to successfully insert.

**Additional data / screenshots**

**Environment:**
 - CockroachDB version: v21.1.9
 - Server OS: MacOS
 - Client app: MacOS

**Additional context**
Unable to bulk insert data

**Comment by darinpp** [comment]
I did everything that you are doing and it seems to be working. Can you try with latest beta - https://s3.amazonaws.com/binaries.cockroachdb.com/cockroach-v21.2.0-beta.1.linux-amd64.tgz
```
defaultdb=# copy json_test from stdin with csv;
Enter data to be copied followed by a newline.
End with a backslash and a period on a line by itself, or an EOF signal.
>> 2,"{""foo"":1}"
>> \.
COPY 1
defaultdb=#
```

**Comment by steven-sheehy** [comment]
You're right, it is working after all even with v21.1.9. I tried various combinations trying to figure out the correct syntax. When I finally figured out the syntax was `2,"{""foo"":1}"` I tested it against an iteration of `json_test` table that had 3 columns. Hence the error wrong number of fields. Thanks!
