### ISSUE TITLE
doc-gen: create inverted index diagram is too wide and doesn't display correctly for any browser width

### ISSUE THREAD

**Issue by ghost** [cockroachdb/cockroach#70732]
https://www.cockroachlabs.com/docs/stable/create-index.html

To see most of the diagram you need to scroll right.

As I change the browser width, different parts of the diagram are broken in different ways. 

<img width="1782" alt="Screen Shot 2021-09-24 at 4 07 25 PM" src="https://user-images.githubusercontent.com/20482960/134748312-1197de92-59c2-4a2e-8001-0f5c55ad3bf6.png">
<img width="1553" alt="Screen Shot 2021-09-24 at 4 12 29 PM" src="https://user-images.githubusercontent.com/20482960/134748385-fb1329ce-0c6b-4503-866f-5f1893e12af1.png">

Jira issue: CRDB-10193

**Comment by nickvigilante** [comment]
Should be addressed in https://github.com/cockroachdb/docs/pull/12509.
