### ISSUE TITLE
./cockroach debug backup export crashes/delays when exporting larger data sets

### ISSUE THREAD

**Issue by iibuaka** [cockroachdb/cockroach#70746]
**Describe the problem**

When running `./cockroach debug backup export <location> --table=tpcc.public.stock` the job takes longer than an hour to export and eventually crashes. This is being executed on my work laptop and without ssh-ing into the node cluster 

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. open terminal
2. move to the downloads folder and thus `cockroach` binary
3. run ./cockroach debug backup export <location> --table=tpcc.public.stock
4. jobs stalls and terminal fails - task manager pops up and says that system has run out of application memory

**Expected behavior**
A clear and concise export of stocks table in tpcc succeeding and loading in less than 2 hours 

**Additional data / screenshots**
<img width="1036" alt="Screen Shot 2021-09-14 at 2 48 11 PM" src="https://user-images.githubusercontent.com/71724613/134821213-89ae58cd-b1bb-44cc-875b-22f7a8e085b4.png">

**Environment:**
 - CockroachDB version latest
 - Server OS: macOS
 - location was s3 backup 

Jira issue: CRDB-10201

**Comment by adityamaru** [comment]
This feature has been since deleted as it was not production ready.
