### ISSUE TITLE
sql: cast from integer to "char" should interpret the integer as an ASCII byte

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#70771]
In Postgres:

```
marcus=# SELECT 97::"char";
 char
------
 a
(1 row)

marcus=# SELECT 128::"char";
ERROR:  22003: "char" out of range
```

In CockroachDB v21.2.x:

```
demo@127.0.0.1:26257/defaultdb> SELECT 97::"char";
  char
-------
    9
(1 row)

demo@127.0.0.1:26257/defaultdb> SELECT 128::"char";
  char
-------
   1
(1 row)
```

**Comment by techytoes** [comment]
Hey @mgartner @rafiss, Can I work on this if no one's working on this?

**Comment by mgartner** [comment]
Absolutely. You'll probably be making changes somewhere in `pkg/sql/sem/tree/casts.go` and you can add tests in `pkg/sql/sem/tree/testdata/eval/cast`. You can see that I highlight the problem with some tests and `TODO`s in [#70722](https://github.com/cockroachdb/cockroach/pull/70722/files#diff-f49548b6dfcc1484442b5fa07fad85974d900a751278845a85be198e5133aea4R1279). You can add similar tests.

Let me know if you have any questions.

**Comment by techytoes** [comment]
Sure. Thanks for the help.  🙇🏼

**Comment by techytoes** [comment]
@mgartner Hi, I was looking into the current implementation and it looks like we cast the same way for both `char` and `text` types. Since Postgres processes the 2 types differently this change could break some of the existing test cases.

```
postgres=# select length(123::text);
 length
--------
      3
(1 row)

postgres=# select length(123::char);
 length
--------
      1
(1 row)
```

what are your thoughts on this?

**Comment by techytoes** [comment]
@mgartner my bad! I got confused with the text and char types. Thanks for clarifying! 🙇🏼
