### ISSUE TITLE
cluster-ui: ColumnsSelector is blank on the Statements and Transactions pages in Safari

### ISSUE THREAD

**Issue by matthewtodd** [cockroachdb/cockroach#70787]
The `ColumnsSelector` works as expected in Chrome, but in Safari (I'm using version 15), it's blank.

This is happening in both a local build of cockroachdb as well as in a cloud cluster.

<img width="1372" alt="Screen Shot 2021-09-27 at 4 41 57 PM" src="https://user-images.githubusercontent.com/5261/134982170-d18862b3-d65a-4db3-8284-92e04dbc3161.png">
<img width="1372" alt="Screen Shot 2021-09-27 at 4 42 15 PM" src="https://user-images.githubusercontent.com/5261/134982179-8ea55ce7-a55b-4d63-bcc9-18d9a5bdd858.png">

Epic CC-5060

Jira issue: CRDB-10222

**Comment by j82w** [comment]
This also broken for the new insights statements page. 

<img width="1294" alt="Screen Shot 2022-09-01 at 8 13 54 AM" src="https://user-images.githubusercontent.com/8868107/187911232-3b143885-076a-4aad-a2ad-f8a5035fd5d7.png">

**Comment by amyyq2** [comment]
It appears that there are two vertical scrolls bars, and if you scroll down you can see the column choices. I got stuck on how to remove the random white space at the top. Setting overflow-y to -webkit-paged-y worked on Safari, but that is deprecated on Chrome.
