### ISSUE TITLE
Serverless: Statement page link doesn't work after filtering

### ISSUE THREAD

**Issue by Annebirzin** [cockroachdb/cockroach#70794]
After filtering by app (or any other filter) on the statements page, the Statement links take me back to the overview page
![Kapture 2021-09-27 at 16 30 58](https://user-images.githubusercontent.com/51920721/134984942-cfca840b-8858-427b-b75e-922679ca5cba.gif)

**Comment by Annebirzin** [comment]
cc @maryliag and @kevin-v-ngo for triage

**Comment by maryliag** [comment]
Fix addressed on another PR: https://github.com/cockroachdb/cockroach/pull/70600
