### ISSUE TITLE
sql: Support `ALTER TABLE...ALTER COLUMN...ON UPDATE`

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/cockroach#70823]
In the initial support for `ON UPDATE`, a user can only specify `ON UPDATE` in a `CREATE TABLE` statement.

The [ON UPDATE RFC](https://github.com/cockroachdb/cockroach/pull/67969/) also described support for `ALTER TABLE...ALTER COLUMN...ON UPDATE`

**Comment by rafiss** [comment]
@vy-ton this is supported, but the syntax differs slightly:

```
root@:26257/defaultdb> create table t(a int primary key, b int);
CREATE TABLE

root@:26257/defaultdb> alter table t alter column b set on update 3;
ALTER TABLE
```

this is analogous to how `ALTER TABLE ... ALTER COLUMN ... SET DEFAULT ...` works:
```
root@:26257/defaultdb> alter table t alter column b set default 2;
ALTER TABLE

root@:26257/defaultdb> insert into t values(1);
INSERT 1

root@:26257/defaultdb> select * from t;
  a | b
----+----
  1 | 2

root@:26257/defaultdb> update t set a=10 where a=1;
UPDATE 1

root@:26257/defaultdb> select * from t;
  a  | b
-----+----
  10 | 3
```

**Comment by vy-ton** [comment]
Thanks @rafiss
