### ISSUE TITLE
opt: internal error because optbuilder `addCasts` adds a `tuple[]` cast that we don't support

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#70831]
This is spun off to track a failure causing https://github.com/cockroachdb/cockroach/issues/70663 https://github.com/cockroachdb/cockroach/issues/70669 https://github.com/cockroachdb/cockroach/issues/70667 https://github.com/cockroachdb/cockroach/issues/70666 and https://github.com/cockroachdb/cockroach/issues/70670

The error `internal error: no volatility for cast tuple[]::tuple{bool, unknown}[]` is returned when running this query.

```
SELECT * FROM (VALUES (ARRAY[(true, NULL)])) AS v1
  EXCEPT ALL SELECT * FROM (VALUES (ARRAY[]::RECORD[])) AS v2;
```

Using `bisect` I found that the bug was introduced in 4037bd8 which made it into v21.1.0 and was also backported to v20.2 (#61086). This commit seems to modify `addCasts` in optbuilder/union.go in a way that causes it to add casts that we don't actually support.

cc @mgartner and @yuzefovich who were tagged on the above issues.

**Comment by mgartner** [comment]
I don't yet have a full understanding of how set operations are supposed to work with tuple types (records). Postgres prevents comparison operators between tuples with a different number of elements and tuples element types that do not have implicit casts to each other (this is what I would expect):

```
marcus=# select row(1, 2) > row(1);
ERROR:  42601: unequal number of entries in row expressions

marcus=# select row(1, 2) > row(3, true);
ERROR:  42883: operator does not exist: integer > boolean
```

But it is odd to me that Postgres disallows set operations when columns have different types, but allows set operations when columns have tuple types with a different number of elements or element types:

```
marcus=# select 1 union all select true;
ERROR:  42804: UNION types integer and boolean cannot be matched

marcus=# select row(1) union all select row(1, 2);
  row
-------
 (1)
 (1,2)
(2 rows)

marcus=# select row(1) union all select row(true);
 row
-----
 (1)
 (t)
(2 rows)
```

**Comment by rafiss** [comment]
One thing that I've noticed from working on tuple support recently is that Postgres is lax about tuple types in some contexts. Consider also that Postgres is fine with arrays of mismatched tuple types:

```
rafiss@127:postgres> select array[row(1,2),row(1,2,3), row(1,2,'cat'), null]
+--------------------------------------+
| array                                |
|--------------------------------------|
| {"(1,2)","(1,2,3)","(1,2,cat)",NULL} |
+--------------------------------------+
```

But if you try to use it in different ways, it may or may not error at execution time depending on what needs to be evaluated:
```
rafiss@127:postgres> select array_position(array[row(1,2,1),row(1,2,3), row(1,2,'cat'), null], row(1,2,5))
cannot compare dissimilar column types integer and unknown at record column 3

rafiss@127:postgres> select array_position(array[row(1,2),row(1,2,3), row(1,2,'cat'), null], row(1,2,5))
cannot compare record types with different numbers of columns

rafiss@127:postgres> select array_position(array[row(1,2),row(1,2,3), row(1,2,'cat'), null], row(1,3))
+------------------+
| array_position   |
|------------------|
| <null>           |
+------------------+

rafiss@127:postgres> select array_position(array[row(1,2),row(1,2,3), row(1,2,'cat'), null], row(1,2))
+------------------+
| array_position   |
|------------------|
| 1                |
+------------------+
```
