### ISSUE TITLE
"Terminate Session" from All Clusters / cluster-name / Sessions doesn't end the SQL cli session

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#70832]
Additional [context](https://cockroachlabs.slack.com/archives/C02FHELSS7N/p1632788368184400+). This behavior differs from CockroachDB self hosted where the sessions page should be cleared.

Epic CC-5060

**Comment by matthewtodd** [comment]
In the frontend, requests aren't being fired off because, while we we import the `terminateSaga`, we neglect to include it in [the list here](https://github.com/cockroachdb/cockroach/blob/8a3f8df890f6f67e433c5b08d3a56bbac0d2b1dc/pkg/ui/workspaces/cluster-ui/src/store/sagas.ts#L24-L35).
