### ISSUE TITLE
kvserver: recover from panic-triggering command in raft log

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#70860]
**Is your feature request related to a problem? Please describe.**
If for whatever reason a command in the Raft log triggers an apply-time panic, the cluster will be severely affected without an available recovery strategy.

**Describe the solution you'd like**
Mitigation: this shouldn't crash the node, i.e. the apply-loop should catch the panic and instead render the replica unavailable until recovery action is taken.

There should be some procedure that can be carried out in this case that removes the offending command from the log (replaces it with an empty entry).

**Additional context**
It seems that the machinery needed for mitigation naturally falls out of https://github.com/cockroachdb/cockroach/pull/68378.

Zeroing the affected entry is easy to implement as an offline operation (i.e. needs to be run against all stores with a replica of the corrupt range), by replacing out the respective raft log entry.

This issue was prompted by SRE 21.2 Problems To Solve /cc @joshimhoff

**Comment by joshimhoff** [comment]
Thanks for the ticket!

One way I can imagine this working is as follows.

First run:
`cockroach cordon <range id>`

The range is unavailable now for reads & writes (errors are returned immediately), and the apply loop doesn't run on the range. In most cases (so long as not system range), the problem now affects only a single customer (or a small number of customers): The customers whose user data is stored in the range! This is a big reduction in blast radius when considering paid serverless.

Second do:
- Some more complex offline op to zero out the entry causing the panic.

The benefit of this is that the first op is very fast to execute on. One important Q is whether `cockroach cordon <range id>` would be useful in situations other than this one:

> If for whatever reason a command in the Raft log triggers an apply-time panic, the cluster will be severely affected without an available recovery strategy.

CC @sumeerbhola who mentioned something kinda like this in a postmortem meeting a while back.

**Comment by sumeerbhola** [comment]
> CC @sumeerbhola who mentioned something kinda like this in a postmortem meeting a while back.

range quarantining? https://github.com/cockroachdb/cockroach/issues/62199

**Comment by joshimhoff** [comment]
Ah great! I will leave it to @tbg to decide if we should close that issue for the other one.
