### ISSUE TITLE
sql,kv: change `system.protected_ts_records` to honor fine grained data domiciliation rules over indexed data

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#70916]
**Describe the problem**

The protected timestamp metadata stored in `system.protected_ts_records` contain a copy of table data in the `spans` column. 

When the data from the table is constrained to certain regions (data domiciliation), the table `system.protected_ts_records` is not constrained and thus the data "escapes" the region it should remain at.

This makes it impossible to do strict data sovereignty partitioning using multi-region CockroachDB when domicilied data is indexed. (The issue does not exist when domicilied data is *not* indexed.)

**Note: we alerady document this limitation in https://www.cockroachlabs.com/docs/stable/data-domiciling.html#limitations**

Epic: CRDB-10287

**To Reproduce**

1. create a multi-region table
2. populate indexed data in each region
3. trigger some behavior that requires populating protected timestamps (perhaps setting up range feeds would achieve that)
4. read the content of `system.protected_ts_records` and observe data from regions duplicated in the histogram column

**Expected behavior**

The table `system.protected_ts_records` should be split into different ranges so that the spans for each table are stored in the same region as the data that's constrained by zone configs.

**Environment:**

crdb v21.2

Jira issue: CRDB-10301

**Comment by ajwerner** [comment]
It's not worse than meta, is it? Also, this subsystem is being replaced entirely in 22.1 (ideally) to support the new multi-tenant architecture. Nevertheless, the new span configs table, which, combined with zone configs themselves, is the expected successor. Is it free of these problems? 

What span data is or is not allowed? At present we never protect any quantity of data more specific that an entire table index. While I understand that that is not a contract, it might alleviate some concerns. 

The span configs have no such property; a span config can cover a single sub-partition.

**Comment by knz** [comment]
cc @awoods187 @mwang1026 you'll need this for the GDPR roadmap.

**Comment by knz** [comment]
> It's not worse than meta, is it? 
I don't think so. But meta is also a problem:  #70912

> the new span configs table [...] Is it free of these problems?
I don't think so, see #70913 and my comments on #66348
