### ISSUE TITLE
changefeedccl: Implement internal function to stream partition

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#70918]
Implement `crdb_internal.replication_stream_spec(id, opt_checkpoint)` as described in 
https://docs.google.com/document/d/1i7x6ce0SGMbJ3KEszeRVjRS0LaPhxulcUbi029nVy7c/edit#

A function takes a stream ID (just a job id), verifies if the job is running, plans, but does not execute the flow, and returns
information necessary for consumer to start ingesting stream.

Epic CRDB-6407

**Comment by gh-casper** [comment]
This is done together with partitioned stream client [PR](https://github.com/cockroachdb/cockroach/pull/73886).
