### ISSUE TITLE
changefeedccl: backports for v21.2.x

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#70920]
This is a tracking issue to tag CDC PRs that should be back-ported.

Keep this PR in cdc/Triage -- and review during triage meetings.
Tag PRs with "Informs ..." tag.
Add a comment indicating all PRs above the comment has been reviewed.

Jira issue: CRDB-10290

**Comment by amruss** [comment]
From discussion: will the d[eprecation of intervleaved tables](https://github.com/cockroachdb/cockroach/issues/72320) make it harder to backport to 21.1? We should be mindful of this when backporting

**Comment by amruss** [comment]
Plan is to backport: https://github.com/cockroachdb/cockroach/pull/77296
