### ISSUE TITLE
observability: expose hyperlink to download past stmt bundles on the main statements page

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#70930]
**Is your feature request related to a problem? Please describe.**
It is not intuitive to find old stmt bundles, only if you go to diagnostics on a recently ran query do you have an option to download a stmt bundle. You have options to click any query and go to diagnostics > all stmt diagnostics but it is not intuitive. Another way is to go to advanced debug > stmt diagnostics history but also takes a few clicks.

**Describe the solution you'd like**
Expose a hyperlink on the main stmts page to view all existing stmt bundles.

Jira issue: CRDB-10295

**Comment by Annebirzin** [comment]
We might want to consider moving diagnostics history into the SQL Activity tab once we make that nav update (see https://github.com/cockroachdb/cockroach/issues/66052). This will make it more visible, and will also give it a consistent place to live if we add it to CockroachCloud Dedicated which currently doesn't have diagnostics history. [Figma designs](https://www.figma.com/file/MoSPFkEyJfGipCmQvvLg1a/21.2_SQL-obsrv_query-performance?node-id=3475%3A60238)

![Screen Shot 2021-10-01 at 12 12 20 PM](https://user-images.githubusercontent.com/51920721/135653361-18082717-3013-4baf-a53b-910c9b806b3e.png)

thoughts @kevin-v-ngo @dbist ?

**Comment by dbist** [comment]
anything to make it more obvious. In this consolidated view, if I click on the actual query in this view, will it bring me to the statements page where I'm presented with logical plan, diagnostics, etc? Would be good to have the breadcrumb view and navigate from whichever the page you're on. Also one more nit I find a bit frustrating, when I click a query and view its exec plan and diagnostics, when I hit back to go back to the statements page, I lose the filter I had which led me to a query. It makes debugging much harder. Happy to discuss offline.

**Comment by Annebirzin** [comment]
Currently, the statement doesn't link to the statements page because we didn't have a historical view of statements.  But might be something we can now introduce since we'll be persisting statements longer cc @kevin-v-ngo 

Regarding the filter not saving, I'm also seeing this behavior in CC and DB consoles. @kevin-v-ngo do you know if we have a ticket for saving the Filter and Sorting behaviors? I thought it was something we addressed in the past.
