### ISSUE TITLE
sql/stats: provide a mechanism to disable automatic stats for a table

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#70970]
**Is your feature request related to a problem? Please describe.**
Sometimes injecting stats can solve a problem in a pinch. Automatic stats might clobber those injected stats. Turning off all automatic stats collection is too big of a hammer. 

**Describe the solution you'd like**
Provide some mechanism to disable automatic stats for a single table.

Epic CRDB-9059

**Comment by rytaft** [comment]
This looks like a duplicate of #40989.
