### ISSUE TITLE
UX updates to statement/transaction time picker and 'Clear SQL stats' button

### ISSUE THREAD

**Issue by Annebirzin** [cockroachdb/cockroach#70997]
Logging a couple of improvements to the statement/transaction time picker and 'Clear SQL stats' button ([Figma Designs](https://www.figma.com/file/MoSPFkEyJfGipCmQvvLg1a/21.2_SQL-obsrv_query-performance?node-id=3486%3A76244))

![Screen Shot 2021-10-01 at 12 49 54 PM](https://user-images.githubusercontent.com/51920721/135658184-ec8f7ad1-5b3c-4b29-86cd-5a24fd439c76.png)

- Introduce previous/next arrows to make it easier to navigate quickly to past time ranges (following the same functionality as the DB console metrics page time picker arrows)
- Replace 'reset time' link with 'Now' button (again same behavior as DB console metrics page time picker. 'Now' button would always be visible). See [designs](https://www.figma.com/file/MoSPFkEyJfGipCmQvvLg1a/21.2_SQL-obsrv_query-performance?node-id=3486%3A76476) for more details on behaviors.  
- Move 'Clear SQL stats' button next to time picker controls, and use underline tooltip treatment

**Comment by Annebirzin** [comment]
cc @kevin-v-ngo @maryliag

**Comment by maryliag** [comment]
About the Now being disabled, imagine the scenario: you set the time for now, when even a minute pass, it's no longer "now" and a new statement could have being executed, so if you click "now" again the picker would be updated to include the minute and the new statement would show up, so when you decide is no longer "now" and enables the button back? 
All of this to say I don't think we should ever have a disabled state for the "now", this way the user can always update to the latest

**Comment by Annebirzin** [comment]
That's a great point, I'm good with not disabling the 'Now' button
