### ISSUE TITLE
acceptance: postgres-test image isn't properly cached.

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#7099]
If you don't have the correct version of the `cockroachdb/postgres-test` docker image pulled by hand, the acceptance tests will pull the image over and over again instead of using the local cache for some reason.

To reproduce, `docker rmi cockroachdb/postgres-test:20160512-1936` (or whatever the latest version is) and run the acceptance tests. You will likely get a test timeout during `TestDockerJava`.

We should figure out what's causing this behavior and change it so that the test properly caches the image when it downloads it for the first time.

**Comment by tamird** [comment]
@jordanlewis can you try a standalone binary that just does the ImagePull bit? I suspect this is a bug upstream.

**Comment by jordanlewis** [comment]
I made a small test that just runs ImagePull twice against the same image.

It seems that the caching works to some degree, but not in-process the way it's set up. I began by running `docker rmi` on the test image. Running the test then pulls the image twice - the bad behavior. However, running the test again after this correctly notices the cached images.

Perhaps there's some kind of cache refresh API that we're missing.

**Comment by tamird** [comment]
FWIW, I can't reproduce the badness outside of our acceptance tests. WIth just a trivial imagepull, the second invocation is a no-op.

**Comment by jordanlewis** [comment]
I was using the `pullImage` helper function defined in `docker.go`. I didn't see anything in that function that would screw up any caching behavior, but I guess I missed something.

**Comment by jordanlewis** [comment]
Yeah, I can't reproduce this without the retrying client.

**Comment by petermattis** [comment]
Is this still a problem?

**Comment by jordanlewis** [comment]
Yes, there is a bug in the retrying docker client that causes it to occasionally not cache images that it fetches with `pullImage`.

**Comment by knz** [comment]
Here I see this issue reproducing too; however even without a timeout the test eventually fails with:
```
--- FAIL: TestDockerJava (66.45s)
        util_test.go:395: Error: No such image: cockroachdb/postgres-test:20160705-1326
```

How come the image is not found sicne pullImage is definitely pulling something?

**Comment by jordanlewis** [comment]
Doesn't seem to happen anymore.
