### ISSUE TITLE
ui: Downsample data points before displaying graphs over larger time scales

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#7100]
#4986 introduced a "time scale selector" to the admin UI, allowing users to view graphs over time spans up to a day in length. However, the UI is having trouble rendering the number of data points returned in such a query, causing the UI to feel sluggish.  To remedy this, we must "downsample" data points before displaying them in the graph.

I believe this can be done on either the frontend *or* backend - the actual slowdown appears to come from rendering an SVG graph with too many data points.

In relation to this fix, graph tooltips which indicate the sampling period (i.e. "sampled over 10 seconds") should be adjusted dynamically based on the new sampling periods.

**Comment by maxlang** [comment]
I'd opt for this on the backend. Once we add larger timescales, the network request and processing time will be a problem on the frontend.

**Comment by mrtracy** [comment]
Closed by #8682, #8746, #8805
