### ISSUE TITLE
21.2 UI issue: Sessions page statements too long

### ISSUE THREAD

**Issue by Annebirzin** [cockroachdb/cockroach#71017]
On the sessions page, some SQL statements do not truncate and show 20+ lines of text. Ideally, these would be truncated to 2 lines:

<img width="1674" alt="Screen Shot 2021-09-28 at 8 10 28 PM" src="https://user-images.githubusercontent.com/51920721/135684552-22c97447-88eb-4281-970e-195e75c43f0c.png">

Desired state:
![Screen Shot 2021-10-01 at 4 31 04 PM](https://user-images.githubusercontent.com/51920721/135684727-dc9bd850-c280-4047-b204-299ad17c7d70.png)

**Comment by Annebirzin** [comment]
cc @kevin-v-ngo and @maryliag

**Comment by maryliag** [comment]
Fixed on https://github.com/cockroachdb/cockroach/pull/71817
