### ISSUE TITLE
21.2 UI issue: Table widths and detail page widths 

### ISSUE THREAD

**Issue by Annebirzin** [cockroachdb/cockroach#71019]
A few pages have tables that are very narrow or page layouts that are inconsistent widths. 

Tables seem to be configured to 'hug contents' making table widths very narrow
(For example databases, transaction detail and grants table seen below)

I've outlined all the current state and desired layout/width behaviors in a [Figma file here](https://www.figma.com/file/MoSPFkEyJfGipCmQvvLg1a/21.2_SQL-obsrv_query-performance?node-id=3503%3A74969). (Happy to pair with someone working on this to figure out the best approach for re-sizing/responsiveness)  
 
<img width="1743" alt="Screen Shot 2021-09-28 at 7 32 58 PM" src="https://user-images.githubusercontent.com/51920721/135685537-8ea03364-2e32-48d0-8da0-3c14406c9dba.png">
<img width="1743" alt="Screen Shot 2021-09-28 at 7 33 24 PM" src="https://user-images.githubusercontent.com/51920721/135685550-f0e70837-a526-4faf-9c43-9567e24c9cf5.png">
<img width="1743" alt="Screen Shot 2021-09-28 at 7 38 19 PM" src="https://user-images.githubusercontent.com/51920721/135685562-0f96b54c-98f1-49ec-a5b3-c5e6b6f9370c.png">

Jira issue: CRDB-10349

Epic: CRDB-25476

**Comment by Annebirzin** [comment]
cc @kevin-v-ngo @maryliag

**Comment by luharuka** [comment]
hey @maryliag can you assign it to me and also tell me the path where i have to ,make changes
