### ISSUE TITLE
perf: performance issue with 1 node down in a 3 node cluster

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#7108]
Separated out from #7018. Replication notes:

1. Start `roachdemo` and bring up 3 nodes
2. Visit the admin UI "nodes" page and wait for all 3 nodes to have all of the replicas.
3. Start `block_writer`
4. Wait for 30s and then "pause" the 3rd node in the `roachdemo` UI
5. Sometimes `block_writer` throughput drops to 0 for a handful of seconds before recovering

The problematic performance usually happens with 1m. If it doesn't, delete the `cockroach-data` directory  and start again from step 1.

**Comment by tschottdorf** [comment]
When you pause the third node, and some leases are on that node, they will
have to time out (presumably causing the drop in the block writer). Are you
observing anything that can't be explained through that mechanism?

On Wed, Jun 8, 2016 at 2:47 PM Peter Mattis <notifications@github.com>
wrote:

> Separated out from #7018
> <https://github.com/cockroachdb/cockroach/issues/7018>. Replication notes:
>
>    1. Start roachdemo and bring up 3 nodes
>    2. Visit the admin UI "nodes" page and wait for all 3 nodes to have
>    all of the replicas.
>    3. Start block_writer
>    4. Wait for 30s and then "pause" the 3rd node in the roachdemo UI
>    5. Sometimes block_writer throughput drops to 0 for a handful of
>    seconds before recovering
>
> The problematic performance usually happens with 1m. If it doesn't, delete
> the cockroach-data directory and start again from step 1.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/7108>, or mute the thread
> <https://github.com/notifications/unsubscribe/AE135DGAewMqMqe4s7E9L_faCkBela4fks5qJw4ogaJpZM4IxRuX>
> .
>
-- 

-- Tobias

**Comment by petermattis** [comment]
@tschottdorf The performance drop does not occur immediately, but sometime after the node is paused. And there are periodic performance drops. Doesn't seem likely that the paused node is grabbing a lease when it is paused. Definitely something to keep in mind, though.

**Comment by tschottdorf** [comment]
Oh. From your message above I thought the drop was immediately following
pausing the third node. Looks like there's something to investigate then.

On Tue, Jun 14, 2016 at 10:50 AM Peter Mattis <notifications@github.com>
wrote:

> @tschottdorf <https://github.com/tschottdorf> The performance drop does
> not occur immediately, but sometime after the node is paused. And there are
> periodic performance drops. Doesn't seem likely that the paused node is
> grabbing a lease when it is paused. Definitely something to keep in mind,
> though.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/7108#issuecomment-225906574>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE135FWRQfiYKiq5DHe5QDvOvP3sZ_tYks5qLr_LgaJpZM4IxRuX>
> .
>
-- 

-- Tobias

**Comment by d4l3k** [comment]
Definitely can replicate
https://gist.github.com/d4l3k/b13f7638ca6d8e7cba495ca645684bb9

It doesn't seem to be a one time thing that it does before recovering. It drops several times between 20s-2m apart. It does seem to eventually recover.
https://gist.github.com/d4l3k/3a9d65d6e83cc611bd7370aab165dc1c

**Comment by petermattis** [comment]
Cool. Those drops are exactly what I saw.

**Comment by d4l3k** [comment]
Seems like blockwriter pauses temporarily while the range gets split.

```
$ block_writer
...
2016/06/15 13:28:02    45s:  527.1/sec
2016/06/15 13:28:03    46s:    0.0/sec
2016/06/15 13:28:04    47s:    0.0/sec
2016/06/15 13:28:05    48s:  607.1/sec
...
```

From cockroach.INFO
```
...
I160615 13:27:56.520921 server/status/runtime.go:187  runtime stats: 78 MiB RSS, 95 goroutines, 28 MiB/3.3 MiB/39 MiB GO alloc/idle/total, 779 KiB/1.9 MiB CGO alloc/total, 56957.81cgo/sec, 1.33/0.24 %(u/s)time, 0.00 %gc (73x)
I160615 13:28:01.531227 storage/split_queue.go:97  splitting range=6 [/Table/50-/Max) at keys [/Table/51/0]
I160615 13:28:01.531397 storage/replica_command.go:2118  initiating a split of range=6 [/Table/50-/Max) at key /Table/51
I160615 13:28:04.579068 storage/replica_command.go:1570  range 7: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 407225h28m9.328015665s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-06-15 17:28:04.579009139 +0000 UTC]
...
```
There's a 3 second gap between the split of range 7 being initiated and the new leader lease.

Other splits seem to have a much smaller gap.
```
...
I160615 13:28:46.519213 server/status/runtime.go:187  runtime stats: 175 MiB RSS, 95 goroutines, 42 MiB/6.6 MiB/57 MiB GO alloc/idle/total, 2.7 MiB/3.8 MiB CGO alloc/total, 47898.18cgo/sec, 1.34/0.25 %(u/s)time, 0.00 %gc (39x)
I160615 13:28:49.497058 storage/split_queue.go:114  splitting range=7 [/Table/51-/Max) size=67108875 max=67108864
I160615 13:28:50.146990 storage/replica_command.go:2118  initiating a split of range=7 [/Table/51-/Max) at key /Table/51/1/4611337164655639784/"79a6a276-0938-460b-9497-c301f9d87fae"/22859
I160615 13:28:50.182201 storage/replica_command.go:1570  range 3: new leader lease replica {1 1 1} 2016-06-15 17:27:42.06555102 +0000 UTC 1m12.862805015s following replica {2 2 2} 2016-06-15 17:27:21.820264372 +0000 UTC 20.245286648s [physicalTime=2016-06-15 17:28:50.181647164 +0000 UTC]
I160615 13:28:50.426057 storage/replica_command.go:1570  range 8: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 407225h28m55.15832595s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-06-15 17:28:50.426010844 +0000 UTC]
...
```

https://gist.github.com/d4l3k/7ead74efe4e4a4cec481f37b796982bd

**Comment by petermattis** [comment]
You mean throughput dips during splits when there are only 2 of 3 replicas available? Because I've definitely seen splits when all 3 replicas are available which do not cause any throughput hiccups.

**Comment by bdarnell** [comment]
3s sounds like a raft election (which by default happen after somewhere between 1.5 and 3 seconds). The leader of the range currently initiates an election for the new range created by the split after a 10ms timeout. If the other nodes haven't processed the split by that point, the election may fail and it will have to wait another cycle for the next one. Increasing that 10ms timeout should reduce the risk of that happening, at the expense of more latency  in the common case.

**Comment by d4l3k** [comment]
Both of the splits above are with 2 of 3 replicas. The first split matches the 2 second block_writer throughput drop. The second may have had a slight throughput drop ~500/s vs 800-1000/s but it was pretty minor. 

Would it be possible to retry the election cycle on a new split if it fails instead of just waiting for the election timeout?

**Comment by d4l3k** [comment]
Or make the 10ms delay less arbitrary and instead wait for the other nodes to notify of a quorum?

**Comment by bdarnell** [comment]
> Would it be (possible|a good idea) to retry the election cycle on a new split if it fails instead of just waiting for the election timeout?

Unfortunately I think the failure mode here is that messages get dropped so you can't tell the difference between failure and in-progress, and campaigning again will invalidate any election in progress.

**Comment by d4l3k** [comment]
Can we send back a "error unknown replica" message instead that allows the split initiator to retry?

**Comment by bdarnell** [comment]
There's no notification we could use; we'd have to introduce something new. And this would probably increase latency in geo-distributed scenarios because you'd have to wait for the network round trip; the 10ms deadline allows us to pipeline behind other messages (we only have to wait for local application of the command). 

I'm not sure exactly why this is happening; there may be something else that's causing the initial election to fail that we could fix.

It could be related to the leadership instability issues we're seeing on #7224. Or it's interaction between raft leadership and the lease: one node becomes raft leader, another proposes the lease, the first raft leader transfers leadership to the new lease holder, and it's the leadership transfer election that fails.

**Comment by d4l3k** [comment]
```
 ✘  ~/go/src/github.com/petermattis/roachdemo/cockroach-data   master ●  ag "\[split\].*done:"
1/logs/cockroach.Tristans-MacBook-Pro.wiz.log.INFO.2016-06-15T14_23_14-04_00.34075
1024:I160615 14:23:14.385337 storage/queue.go:436  [split] range=1 [/Min-/Table/11): done: 57.952952ms
7190:I160615 14:23:52.478841 storage/queue.go:436  [split] range=5 [/Table/14-/Table/50): done: 42.458814ms
7207:I160615 14:23:52.479632 storage/queue.go:436  [split] range=5 [/Table/14-/Table/50): done: 11.449µs

1/logs/cockroach.Tristans-MacBook-Pro.wiz.log.INFO.2016-06-15T14_24_38-04_00.34075
19105:I160615 14:24:39.422779 storage/queue.go:436  [split] range=6 [/Table/50-/Table/51): done: 66.745548ms

1/logs/cockroach.Tristans-MacBook-Pro.wiz.log.INFO.2016-06-15T14_26_34-04_00.34075
2717:I160615 14:26:35.017621 storage/queue.go:436  [split] range=7 [/Table/51-/Table/51/1/4610488221567379425/"368d70ad-7396-48c4-ad7e-a32ce60379cf"/6117): done: 3.020686498s
2721:I160615 14:26:35.017765 storage/queue.go:436  [split] range=7 [/Table/51-/Table/51/1/4610488221567379425/"368d70ad-7396-48c4-ad7e-a32ce60379cf"/6117): done: 24.089µs

1/logs/cockroach.Tristans-MacBook-Pro.wiz.log.INFO.2016-06-15T14_29_23-04_00.34075
1240:I160615 14:29:23.965723 storage/queue.go:436  [split] range=8 [/Table/51/1/4610488221567379425/"368d70ad-7396-48c4-ad7e-a32ce60379cf"/6117-/Table/51/1/6940235406402114499/"368d70ad-7396-48c4-ad7e-a32ce60379cf"/18136): done: 2.799613799s
1256:I160615 14:29:23.965914 storage/queue.go:436  [split] range=8 [/Table/51/1/4610488221567379425/"368d70ad-7396-48c4-ad7e-a32ce60379cf"/6117-/Table/51/1/6940235406402114499/"368d70ad-7396-48c4-ad7e-a32ce60379cf"/18136): done: 28.587µs

1/logs/cockroach.Tristans-MacBook-Pro.wiz.log.INFO.2016-06-15T14_29_24-04_00.34075
468:I160615 14:29:25.475415 storage/queue.go:436  [split] range=7 [/Table/51-/Table/51/1/2285034130557782559/"368d70ad-7396-48c4-ad7e-a32ce60379cf"/39599): done: 1.509229353s
470:I160615 14:29:25.475599 storage/queue.go:436  [split] range=7 [/Table/51-/Table/51/1/2285034130557782559/"368d70ad-7396-48c4-ad7e-a32ce60379cf"/39599): done: 31.181µs
```
I turned the log level all the way up and there's definitely a number of ranges that are taking around 1.5s or 3s.

There's also thousands of messages right before the performance drop similar to these:
```
7:I160615 14:29:23.770321 storage/queue.go:316  [split] range=7 [/Table/51-/Table/51/1/4610488221567379425/"368d70ad-7396-48c4-ad7e-a32ce60379cf"/6117): adding: priority=1.005
11:I160615 14:29:23.770599 storage/queue.go:426  [split] range=7 [/Table/51-/Table/51/1/4610488221567379425/"368d70ad-7396-48c4-ad7e-a32ce60379cf"/6117): could not acquire leader lease; skipping
18:I160615 14:29:23.771109 storage/queue.go:316  [split] range=8 [/Table/51/1/4610488221567379425/"368d70ad-7396-48c4-ad7e-a32ce60379cf"/6117-/Max): adding: priority=1.007
22:I160615 14:29:23.771416 storage/queue.go:426  [split] range=8 [/Table/51/1/4610488221567379425/"368d70ad-7396-48c4-ad7e-a32ce60379cf"/6117-/Max): could not acquire leader lease; skipping
```

**Comment by d4l3k** [comment]
This isn't a raft election issue.

Instead what's happening is that after a split `RangeLookup` sends out a message to nodes in a random order to fetch information. These replicas are passed into `splitHealthy` which should move the down node to the end of the try order, however, grpc reports the `ConnectivityState` as `Ready`. Thus, there is a chance that on split there will be a 3s RPC timeout causing writes to block.

**Comment by d4l3k** [comment]
Related to https://github.com/grpc/grpc-go/pull/690. Ideally the fix won't rely on `(*grpc.ClientConn).State()` since that function is no longer present upstream.

**Comment by bdarnell** [comment]
Related to #6750. We should be setting SendNextTimeout to a lower value so we can retry in less than 3s, but that exposed data races last time we tried it. We're missing some place where we need to copy the transaction proto before mutating it (and we also need a test that exposes this race).

**Comment by d4l3k** [comment]
Also related to #6719
