### ISSUE TITLE
bulkio: allow non-admin users to export/import from custom endpoint

### ISSUE THREAD

**Issue by fabiog1901** [cockroachdb/cockroach#71150]
The request is to allow (via an option/grant) a non-admin user to perform IMPORT/EXPORT to/from a custom endpoint, like a s3 compatible service.

See [Slack conversation](https://cockroachlabs.slack.com/archives/C2C5FKPPB/p1633451823402900).

We typically do now allow non-admin users to cause nodes to dial arbitrary network URIs (or access cloud storage using "implicit" auth, where the running node's machine account is used to authenticate) as this could allow a user given _SQL_ access to then access things, via the node, that they otherwise would not be able to access. 

However some operators may wish to allow their SQL users to access arbitrary resources within their network, such as an internal file server or s3-like service, without giving those users admin roles. We could provide them a crude flag, that simply removes the admin-only restriction on these types of node-based access. 

Such a flag might be less useful if in some future version, an admin, or someone with an admin-granted privilege, could create some sort of "endpoint" object, which could be s3/gcs/an http URI, paired with requisite configuration and credentials, and then grant _usage_ of that endpoint to another user, so that that user could then interact with e.g. a custom, internal s3-like service without also having unfettered ability to dial arbitrary addresses, or an s3-bucket without knowing the credentials for it. But until then, this flag would help operators who want their users to be able to access non-default cloud storage options, and may even be preferred by operators who do not want to setup and configure ephemeral endpoints or something like that in the future, and are okay with blanket allowing such access.

gz#10018

Epic CRDB-10735

**Comment by data-matt** [comment]
Hi @dt / @livlobo , in light of https://github.com/cockroachdb/cockroach/pull/71594

Can we update the status of this issue? 

I think it can be closed once the feature becomes GA? 

Thanks

**Comment by livlobo** [comment]
This is now GA. Closing.
