### ISSUE TITLE
backupccl: support for multi-region table backups

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#71180]
Table backups for regional-by-row, regional-by-table and global tables were disallowed in https://github.com/cockroachdb/cockroach/pull/60715. The motivation for that change was that table level restores for MR tables were not supported. With https://github.com/cockroachdb/cockroach/pull/71178, a user should be able to restore the above three kinds of MR tables with the caveat that the regions in the backup need to be a subset of the regions in restoring database. We should thus unblock the table backups for MR tables.

Epic CRDB-10350

**Comment by jseldess** [comment]
Documented here: https://www.cockroachlabs.com/docs/v21.2/known-limitations.html#backup-of-multi-region-tables
