### ISSUE TITLE
sql/pgwire: Support deallocating prepared statements

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#7123]
Postgres specifies in https://www.postgresql.org/docs/8.3/static/libpq-exec.html#AEN31052 that prepared statements can be removed through the use of the SQL `DEALLOCATE` statement. We should support this to allow for the use case of declaring multiple prepared statements with the same name on the same connection.

This was discovered by @garvitjuniwal when working with http://www.codesynthesis.com/products/odb/.

**Comment by tamird** [comment]
Do you also intend to support statement preparation via the parser? We
already support deallocating prepared statements via `clientMsgClose`, so
if we're gonna support deallocation via the parser, we should support
creation (and execution) as well.

**Comment by garvitjuniwal** [comment]
This was actually discovered by @amangoeliitb, not me.

**Comment by petermattis** [comment]
@tamird I think we should support `PREPARE` and `EXEC`. I thought there was already an issue around that but I can't find it right now. I wouldn't want to predicate support for `DEALLOCATE` on `PREPARE` and `EXEC` as it sounds like `DEALLOCATE` is independently useful.

**Comment by amangoeliitb** [comment]
@petermattis any updates on this?

**Comment by andreimatei** [comment]
Fixing this is not trivial. We'll need to move the handling of prepared statements from `pgwire` to the sql layer, which as of now I think is completely unaware of them.

**Comment by tamird** [comment]
Correct.

**Comment by petermattis** [comment]
The change isn't trivial, but it also doesn't appear overly complex. `v3Conn.prepared{Statements,Portals}` would need to move into `sql.Session`. After that refactoring, supporting `DEALLOCATE` seems straightforward. Am I missing something here that makes this onerous?

**Comment by nvanbenschoten** [comment]
@petermattis you're correct that the majority of the work here will be focused on pulling prepared statement handling up into the `sql` layer, which we would want to do in a way that would naturally lend itself to `PREPARE` support in the future (although I'm a little wary of supporting `PREPARE` before we provide some of the caching that I think the statement implies @knz). Once that's complete, supporting `DEALLOCATE` should be straightforward. I'll take a look into this later tonight.

**Comment by knz** [comment]
IIRC PREPAREd statements should be preserved across sessions/connections; I believe they are either user-wide or database-wide.

**Comment by petermattis** [comment]
https://www.postgresql.org/docs/9.5/static/sql-prepare.html

> Prepared statements only last for the duration of the current database session. When the session ends, the prepared statement is forgotten, so it must be recreated before being used again. This also means that a single prepared statement cannot be used by multiple simultaneous database clients; however, each client can create their own prepared statement to use. Prepared statements can be manually cleaned up using the DEALLOCATE command.

**Comment by nvanbenschoten** [comment]
I'm not sure exactly how much work other databases do upfront for `PREPARE`d statements, but it seems like we should try to do as much as possible so that we can avoid repeated work during execution. This could range from caching parsed expression trees instead of just the expression string, to caching our entire `Executor.Prepare` phase. All of this would be somewhat contingent on future changes to preserve work between our `Executor.Prepare` and `Executor.ExecuteStatements` phases.

@knz and I have also discussed prepared statements and the ways they should interact with schema versions. If we decide that prepared statements should be invalidated across schema changes (which might be desirable given that a schema change could alter the meaning/validity of a prepared statement), we would be able to preform even more work upfront (type-checking, normalization, etc...).

**Comment by petermattis** [comment]
@nvanbenschoten Typically, a database will create a query plan from the prepared statement which will be tied to the specific versions of the tables that were present when the statement was prepared. If any of the tables involved in the prepared statement change, the cached information is recomputed.

I'm not seeing a reason to tie better caching of prepared statements to supporting `PREPARE` and `DEALLOCATE`. I was imagining the first version of `PREPARE` and `DEALLOCATE` support would follow the same pattern that we use for the existing pgwire-level prepared statements.

**Comment by andreimatei** [comment]
btw, when we start caching ASTs and plans and whatnot, we should do it for all common queries, explicitly prepared or not.

**Comment by tamird** [comment]
Are we tracking supporting PREPARE/EXECUTE?

**Comment by knz** [comment]
@tamird I believe @nvanbenschoten has this on his plate, for example #7322 was just merged and that's the stepping stone.

**Comment by tamird** [comment]
#7367, which closed this issue is also already merged; just wondering if we have an issue for the other statements. Looks like the answer is no.
