### ISSUE TITLE
streamingccl: Add API stubs

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#71237]
Add client API stubs as described in https://github.com/cockroachdb/cockroach/pull/71213
Implement (or update existing) testing fixtures to work with this new API.

(pkg/ccl/streamingccl is the current home for streaming implementation)

CRDB-10145

Epic CRDB-10145

Jira issue: CRDB-10453

**Comment by gh-casper** [comment]
https://github.com/cockroachdb/cockroach/pull/71213 closed this.
