### ISSUE TITLE
ui: provide ability to cancel jobs in the DB Console

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#71235]
**Is your feature request related to a problem? Please describe.**
Today, to cancel a job (backup, schema change, import) requires to find the job id in CLI and cancel the job exclusively in the CLI. It is counterintuitive to capture job ID in the console and then drop to CLI and cancel job there. We have ability to cancel sessions in the Console, it'd be beneficial to allow the same for jobs.

**Describe the solution you'd like**
Open jobs page, find job of interest, toggle to pause/cancel job without leaving the UI.

**Describe alternatives you've considered**
no alternatives except for CLI.

I'd expect to see something like this only for jobs
![image](https://user-images.githubusercontent.com/461296/136268873-e4334af8-0085-45db-b3dc-8198abec8f91.png)

Jira issue: CRDB-10451

Epic CRDB-1

**Comment by thtruo** [comment]
cc @kevin-v-ngo for SQL Observability awareness and @vy-ton for SQL Schema awareness

**Comment by livlobo** [comment]
Added A-jobs and A-sql-console-general for triage.

**Comment by benbardin** [comment]
Yeah, I like it! @rachwangcrl , you want to take a crack at a design or should i just wing it?
