### ISSUE TITLE
CockroachDB - SSL Certificate expired

### ISSUE THREAD

**Issue by ValeWalker27** [cockroachdb/cockroach#71242]
**Describe the problem**

I have set up a database in CockroachCloud and have been connecting to the same from a Python script. When I tried conneccting today, the connection kept failing and I no longer am able to connect to the database.

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

What did you do? Describe in your own words.

Attempt: 1
=-=-=-=-=
Connecting from Python script

```
>>> conn = create_engine(f'cockroachdb://myAdmin@free-tier.gcp-us-central1.cockroachlabs.cloud:26257/fancy-rat-1274.defaultdb?sslmode=verify-full&sslrootcert={os.environ["HOME"]}/Desktop/CockroachDB/certs/cc-ca.crt')
>>> SourceDF = pd.read_sql(''' select * from public."myExpense" ''', conn)
Traceback (most recent call last):
...
...
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SSL error: certificate verify failed


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
...
...
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SSL error: certificate verify failed`
```
Attempt: 2
=-=-=-=-=
Connecting to cockroach DB from Terminal

```
iMac:~ sathish$ cockroach sql --url 'postgresql://myAdmin@free-tier.gcp-us-central1.cockroachlabs.cloud:26257/fancy-rat-1274.defaultdb?sslmode=verify-full&sslrootcert=$HOME/Desktop/CockroachDB/certs/cc-ca.crt'
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
ERROR: x509: certificate has expired or is not yet valid: current time 2021-10-07T00:26:02+05:30 is after 2021-09-30T14:01:15Z
Failed running "sql"
```

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster & create a table
2. Connect to CockroachDB from Terminal using "cockroach sql --url='<connection-string>'" command
3. See error

**Expected behavior**

The same connection string have been working fine for me till now. Also, a little research into the error made me wonder if this is related to the article, as mentioned in https://smartslider.helpscoutdocs.com/article/2045-ssl-certificate-problem-certificate-has-expired

**Additional data / screenshots**

**Environment:**
 - CockroachDB version [e.g. 2.0.x]                     21.1.7
 - Server OS: [e.g. Linux/Distrib]                          Windows 10, macOS HighSierra & macOS Catalina
 - Client app [e.g. `cockroach sql`, JDBC, ...]    cockroach sql & python sqlalchemy

**Additional context**
What was the impact?

Reference URLs related to SSL expiry on 09th Sep 2021.
URL1: https://smartslider.helpscoutdocs.com/article/2045-ssl-certificate-problem-certificate-has-expired
URL2: https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

![From Python](https://user-images.githubusercontent.com/45958694/136276073-7edc67f1-d178-4522-b27d-494cf6e4741d.png)
![From Terminal](https://user-images.githubusercontent.com/45958694/136276086-26695f97-7698-4b63-a60d-ba7ee107a9a8.png)

**Comment by emily-horing** [comment]
That's great news! Glad you were able to reconnect. The root cert we use from LetsEncrypt does rotate periodically. The next scheduled rotation is for 2035. We'll notify all the users in our system before the expiration.
