### ISSUE TITLE
Developers can view jobs and their details in the CC console for dedicated and serverless clusters

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#71324]
This issue tracks surfacing the Jobs page we have in the DB console for CC. 

Here is the link to the [Figma mockups](https://www.figma.com/file/nza5m5AIvSqu2BGYnGxD7Y/CC_jobs-pages?node-id=301%3A3805). cc @Annebirzin 

Jira issue: CRDB-10512

**Comment by ericharmeling** [comment]
We now have jobs pages in the CC dedicated console: https://github.com/cockroachlabs/managed-service/pull/9260

Currently, tenant clusters do not support most of the `admin` server endpoints. After https://github.com/cockroachdb/cockroach/pull/84620 is merged, we can add the jobs pages to the serverless nav.
