### ISSUE TITLE
jobs: Persist interesting context tags when creating the job

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#71335]
When the job is started, it inherits context tags from the caller.
So, if we start e.g. changefeeds (or backup), then the flow will have job=ID tag;
However, if the job resumes later, it appears that these tags are lost.
It would be nice if we had consistent tags when starting vs resuming the jobs.  In addition, there
might be other interesting tags -- perhaps application name, or a user, etc that we probably
should persist in the jobs record so that we can recreate context tags when resuming the job.

Jira issue: CRDB-10516

**Comment by amruss** [comment]
Related: https://github.com/cockroachdb/cockroach/issues/71229
