### ISSUE TITLE
jobs: data for deleted tenants not removed automatically by GC job

### ISSUE THREAD

**Issue by jaylim-crl** [cockroachdb/cockroach#71363]
**Describe the problem**

In CC, we are seeing deleted tenants still having their data lying around. The KV cluster is running on v21.1.7, and we can see the following for deleted clusters; cluster was deleted as recent as the past 48 hours, and as old as months:
1. the tenant still has a row in `system.tenants`
2. the tenant's data is still around, which is evident from `livebytes` > 0

We're using prometheus, and the query used here is `sum by (tenant_id) (livebytes{tenant_id="X"})`:

![image](https://user-images.githubusercontent.com/83607639/136647552-9de80ca2-9d45-4f10-a538-687fc9a37b32.png)

**To Reproduce**

1. Set up a multi-tenant cluster with tenants.
2. Delete the tenant by invoking [crdb_internal.destroy_tenant](https://github.com/cockroachdb/cockroach/blob/fb67c7f24a05673bf0bb06f72a4c697679d1fff4/pkg/sql/sem/builtins/builtins.go#L4497-L4526).
3. Observe that the tenant's data is still lying around, and the `livebytes` metric for that deleted tenant is still emitted by the KV server.

**Expected behavior**

We expect that deleting a tenant can be done by invoking `crdb_internal.destroy_tenant`, and a periodic GC job should clean up tenants data for tenants in the DROP state.

However, we see a TODO comment here, saying that destroy_tenant doesn't actually delete a tenant, and we need to manually call gc_tenant: https://github.com/cockroachdb/cockroach/blob/fb67c7f24a05673bf0bb06f72a4c697679d1fff4/pkg/sql/sem/builtins/builtins.go#L4497-L4526

But at the same time, `gcTenant` gets called in the GC job: https://github.com/cockroachdb/cockroach/blob/fb67c7f24a05673bf0bb06f72a4c697679d1fff4/pkg/sql/gcjob/gc_job.go#L59-L64

I don't know if the GC job is triggered automatically, or manually through `crdb_internal.gc_tenant` to queue the job. Is this a bug, or expected because it wasn't implemented?

**Other**

Feel free to reach out to CC if more data is needed.

cc: @andy-kimball 

Jira issue: CRDB-10528

**Comment by JeffSwenson** [comment]
This was fixed by: https://github.com/cockroachdb/cockroach/pull/72364
