### ISSUE TITLE
sql: consider checking all tables's FormatVersion on startup

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#7136]
Right now, it fails the first time you query a table with an incompatible FormatVersion, but it may increase usability if additionally all FormatVersions were checked at startup so we can fail fast

**Comment by paperstreet** [comment]
cc @dt

**Comment by vivekmenezes** [comment]
table descriptors have been migrated to InterleavedFormatVersion for 2.0. This issue is no longer relevant.
