### ISSUE TITLE
sql: cache non-leased table descriptors

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#7143]
AS OF SYSTEM TIME queries fetch table descriptors at certain times instead of a lease. These need to be cached since we expect many queries of the same table at a certain time.

**Comment by spencerkimball** [comment]
@mjibson what's the status here? Is this 1.0? I'm assigning this to you to re-assign, move milestone, and/or close.

**Comment by mjibson** [comment]
This doesn't need to be in 1.0. It's a performance optimization that can be made later.

**Comment by andreimatei** [comment]
dupe #20551
