### ISSUE TITLE
New function that validates JSON - json_valid()

### ISSUE THREAD

**Issue by smcvey** [cockroachdb/cockroach#71453]
See this issue: https://forum.cockroachlabs.com/t/test-string-value-as-valid-json-content/4870
It's not currently possible to validate if a string can be converted to JSON.

**Describe the solution you'd like**
A new function, json_valid(string) that would return a true value if the string could successfully be casted to a json type - false otherwise.

**Describe alternatives you've considered**
Can't really think of any.  Trying to cast with <string>::json causes the query to completely fail.

**Comment by otan** [comment]
Instructions:

Add a built-in in https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/builtins.go
Add a test in https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/builtin_function, and run make testbaselogic FILES='builtin_function' TESTFLAGS='-rewrite' to test it.
Run make buildshort to regenerate automatically generated files.
Submit a PR.

**Comment by eaarranz** [comment]
I have added a basic implementation on the linked PR. Open to any changers or suggestions :)
