### ISSUE TITLE
sql: add support to the InternalExecutor to execute multiple SQL queries

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#71467]
Today, the `InternalExecutor` exposes several methods such as `ExecEx`, `QueryRowEx` that take a single SQL statement and execute it using a `connExecutor`. A new executor is initialized for every statement and is closed once query execution completes. One consequence of this is that an internal executor cannot maintain `extraTxnState` across multiple SQL queries, and so we cannot run multiple statements in a txn using an internal executor.  

This issue tracks work to expand the internal executor to support multiple queries that can be run in an explicit txn, or in a higher-level SQL transaction. For the most part this would require having a single, long-lived `connExectuor` that reads multiple statements, pushed by the ie, via the `stmtBuf`.

A motivation for this change is to prototype https://github.com/cockroachdb/cockroach/issues/67076#issuecomment-882636418.

Epic CRDB-14492
Jira issue: CRDB-10591

**Comment by andreimatei** [comment]
Consider adding session support in the form of a gosql driver implementation that talks to the `InternalExecutor`, or without using the `InternalExecutor` at all, but by making it easy to connect to the local sql node through a specialized `net.Conn` interface that we'd hand to pgx.

**Comment by andreimatei** [comment]
Can someone explain what in what way this was done? I don't see something obvious in the InternalExecutor's interface.

**Comment by ZhouXing19** [comment]
HI @andreimatei, in #82477 we modified [how the conn executor inherits and processes txn-related metadata from the outer caller of the internal executor](https://github.com/cockroachdb/cockroach/pull/82477/commits/3427691c3be6574bc75caae87e1ed89f487801a7). With those changes, now an internal executor can be used to run multiple sql queries, but only if they are initialized with the [new interfaces ](https://github.com/cockroachdb/cockroach/pull/82477/commits/9b23132516d972bd55e4eef6b853bc6d70ba56ba)we introduced. 

Tests to run multiple queries with `descs.TxnWithExecutor()` (one of the new interfaces) are also added [here](https://github.com/cockroachdb/cockroach/blob/4f0065ad010cee1ce50bbc65019b26f93a7dc6ad/pkg/sql/catalog/descs/txn_with_executor_datadriven_test.go) and [here](https://github.com/cockroachdb/cockroach/blob/4f0065ad010cee1ce50bbc65019b26f93a7dc6ad/pkg/sql/catalog/descs/testdata/basic_txn).

**Comment by andreimatei** [comment]
Some new interfaces were added, but it seems to me that we're far from being able to use the `InternalExecutor` in a conversational way in general, in the way that one uses a sql connection.
One can't do:
```
ie.Exec("SET varfoo=bar")
ie.Exec("BEGIN")
ie.Exec("SELECT * FROM foo")
ie.Exec("UPDATE...")
ie.Exec("COMMIT")
```
Given how reasonable the expectation that using the database from inside it should not be a lot harder than using it from the outside is, I think we should keep this issue open for this goal.

**Comment by ZhouXing19** [comment]
>  we're far from being able to use the InternalExecutor in a conversational way in general

I agree that the current internal executor is not versatile, but I wonder how much we want to expect from an internal executor, how far we can possibly go with it, and is it possible to sheer to other ways (such as using the `gosql` package) for more flexible functionalities? 

Also, though we're still far, maybe it'd be helpful if we can break this issue into smaller ones to track the progress.
