### ISSUE TITLE
restore: fix full cluster restore after public schema migration

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#71479]
As of today (21.2) IDs 52 and onwards are used by objects created by the user.

Once the public schema migration has been completed, new clusters created on CockroachDB versions >=22.1 will use IDs 52, 53 an in order to create two new public schemas for the default created dbs (defaultdb, postgres).
(defaultdb 50, defaultdb public schema 51, postgres, 52, postgres public schema 53)

This creates an issue with full cluster restore as we currently don't support re-keying. 

For example, if we backed up a cluster in 21.2 where the user simply created one table `t` and inserted some rows, `t` would use ID 52. Restoring this table into a cluster where the public schema migration has been completed will be an issue since 52 will be used by `postgres` database. 

The solution to this would be to drop both `defaultdb` and `postgres` perform the restore where we are guaranteed those IDs are not being used by the dbs, and recreate the databases with their public schemas afterwards.

This is similar to how we create the temporary system database for restore above the ID space (above the maximum id being restored). 

cc @dt @ajwerner 

Epic CRDB-1521

**Comment by shermanCRL** [comment]
I think it needs to start with on the SQL team. cc @adityamaru

**Comment by adityamaru** [comment]
Sorry I couldn't join the meeting so just catching up. My first reaction was ugh more static IDs 😄  but I guess there is more context here. Dropping the databases before a cluster restore does simplify stuff a lot. I'll catch up on the notes!
