### ISSUE TITLE
bulkio: create public schema with descriptor and reparent during restore

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#71480]
This is the restore counterpart to https://github.com/cockroachdb/cockroach/issues/55793

When restoring databases from versions 21.2 and prior that do not have public schemas backed by descriptors, we'll have to synthesize public schemas and reparent tables to use the new public schema id instead of `29.

Epic: CRDB-1521

**Comment by rafiss** [comment]
https://github.com/cockroachdb/cockroach/pull/72000 closes this
