### ISSUE TITLE
sql: test TPC-H performance on serverless

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#71528]
We have done a lot of testing with TPC-H on single-tenant CockroachDB where DistSQL can be used across multiple machines. However, we have not done much testing yet in the multi-tenant environment of CockroachDB Serverless. We should start testing TPC-H regularly with Serverless to track performance over time and identify gaps.

Jira issue: CRDB-10625

**Comment by vy-ton** [comment]
@rytaft this is something I'd like to revisit during stability period

**Comment by rytaft** [comment]
SGTM
