### ISSUE TITLE
metrics: `seconds_until_enterprise_license_expiry` needs accompanying HELP and TYPE lines

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#71525]
Metrics in `/_status/vars` contain a `HELP` and `TYPE` line. However, the metric `seconds_until_enterprise_license_expiry` is missing those lines. We'd like to add those for this metric

**Comment by dhartunian** [comment]
@thtruo This is complete and backported into 21.2 so it will be in the `21.2.4` release.
