### ISSUE TITLE
Provide a better format for the statement text (and transaction) within the console

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#71544]
We should have better formatting of the statement and transaction text within the console. 

https://www.cockroachlabs.com/blog/sql-fmt-online-sql-formatter/

![image](https://user-images.githubusercontent.com/81193618/137211650-10d4ee87-68bd-4e0d-93c5-8882d4365c24.png)

Epic: CRDB-9867

**Comment by rafiss** [comment]
See https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/sqlfmt.go for how it's implemented.

**Comment by kevin-v-ngo** [comment]
@Annebirzin, we'll need to determine what would be good defaults for the [format](https://sqlfum.pt/) in the console.

**Comment by Annebirzin** [comment]
@kevin-v-ngo it seems like we could try out `Alignment mode: full`, `case: UPPER` and `Target line width: 108`. Not sure what the other selections do, but seems like we can leave those off. Might have to try this configuration out and see what it looks like in the UI with a few different queries.
