### ISSUE TITLE
tenant: TestCancelLookups sometimes hangs

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#71575]
I saw the `test` build timing out in the the sqlproxyccl/tenant package a few times, with `TestCancelLookups` reported as the test in progress.
Here is one: https://teamcity.cockroachdb.com/viewLog.html?buildId=3581116&buildTypeId=Cockroach_UnitTests

It looks like the test hangs in `Stop()`.

```
goroutine 3501 [sync.Cond.Wait, 44 minutes]:
sync.runtime_notifyListWait(0xc0056e8850, 0xc000000000)
	/usr/local/go/src/runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc0056e8840)
	/usr/local/go/src/sync/cond.go:56 +0x99
google.golang.org/grpc.(*Server).GracefulStop(0xc004866000)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1792 +0x1ee
github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl/tenantdirsvr.New.func1()
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl/tenantdirsvr/test_directory_svr.go:102 +0x2e
github.com/cockroachdb/cockroach/pkg/util/stop.CloserFn.Close(0xc005b28a40)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:108 +0x25
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Stop(0xc000ec70e0, 0x6b1dc28, 0xc00153a2c0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:560 +0x22f
github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl/tenant_test.TestCancelLookups(0xc0049f4c00)
	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/sqlproxyccl/tenant/directory_test.go:220 +0x48b
testing.tRunner(0xc0049f4c00, 0x59fdae8)
	/usr/local/go/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1238 +0x2b3
```

Jira issue: CRDB-10659

**Comment by andreimatei** [comment]
happened to me here https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/3923697?

**Comment by ajwerner** [comment]
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/6651462?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true&expandBuildDeploymentsSection=true

**Comment by knz** [comment]
cc @rafiss for triage

**Comment by knz** [comment]
since this hasn't happened in a long tme, perhaps the problem has been resolved already.

**Comment by rafiss** [comment]
`TestCancelLookups` looks related to the sqlproxy tenant directory, not query cancellation. I'll remove this from the SQL Sessions board.

cc @jaylim-crl

**Comment by rafiss** [comment]
Closing this since it's been two years
