### ISSUE TITLE
sql: add SetPrivileges method to catalog.MutableDescriptor to handle privileges for reparent database

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#71585]
From @postamar comment about here https://github.com/cockroachdb/cockroach/blob/a158794f64c24469f79162a57b05c859d9519e42/pkg/sql/reparent_database.go#L117

> It appears you're changing the database's privileges and then cloning those to use as the schema's. Is this intentional? It doesn't seem like it. This is perhaps good motivation to add a SetPrivileges method to catalog.MutableDescriptor. In fact wouldn't it be better if GetPrivileges returned an interface instead of *descpb.Privileges? The potential for mistakes is quite high.

We should definitely do this as we've actually ran into issues in the past with regards to this logic.

Jira issue: CRDB-10663

**Comment by rafiss** [comment]
reparent database is going away, so closing this.
