### ISSUE TITLE
cli: start-sql should default store to cockroach-data-<tenant>

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#71603]
**Is your feature request related to a problem? Please describe.**

Tenants use the `cockroach-data` directory for disk spilling. But this is also the default for the server, so if you try out tenants locally, the tenant will try to clean up the temp dirs of the running server, which fails and exits the tenant process.

**Describe the solution you'd like**
Tenants should default to cockroach-data-<tenantid>.

**Describe alternatives you've considered**
Do nothing? Maybe this is working as intended but I had to burn a few hours on this over in #71269.

**Comment by irfansharif** [comment]
Closing in favor of #72518 (already triaged + assigned).
