### ISSUE TITLE
ui: allow stmts page search across logical plan text

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#71615]
**Is your feature request related to a problem? Please describe.**
I'd like to identify queries using a specific index, today the search is going against stmt text only, and unless stmt uses an index hint, my search query is not possible.

**Describe the solution you'd like**
index the logical plan text so that search by index name is possible.

**Describe alternatives you've considered**
no solution today

![image](https://user-images.githubusercontent.com/461296/137526344-94b44a0f-470e-4b7a-a9cf-c54b0858d679.png)
![image](https://user-images.githubusercontent.com/461296/137526373-022f1d50-4e88-4826-bd9d-43c7e0446f2b.png)

**Comment by gtr** [comment]
PR: [74820](https://github.com/cockroachdb/cockroach/pull/74820) We might not want to implement this change for the txns page as the list of stmts for a txn could potentially grow really large.
