### ISSUE TITLE
kv: Add telemetry for node liveness failure

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/cockroach#71662]
As admission control gets rolled out, we want to add product telemetry around node stability. We should add product telemetry that matches the current liveness failure metric so that we can improve visibility into node stability across clusters.

SQL Queries plans to rollout admission control starting on 21.2 clusters, so hopefully this telemetry can be backported.

FYI @jordanlewis @rytaft

**Comment by vy-ton** [comment]
@shralex Were you thinking about this as a starter project for the November milestone?

**Comment by vy-ton** [comment]
@lidorcarmel Ideally, we will want to backport this to 21.2, so let me know fi that would be an issue as you work on this.

**Comment by lidorcarmel** [comment]
merged and backported to 21.2, closing.

**Comment by lidorcarmel** [comment]
Telemetry names added:
liveness.heartbeatfailures
liveness.epochincrements

**Comment by vy-ton** [comment]
@lidorcarmel For my knowledge, what does `epochincrements` measure?

**Comment by lidorcarmel** [comment]
good question.. when a heartbeat fails the node might retry and still keep its leases, but if it doesn't then another node may increment the epoch of that troubled node, causing it to lose all its leases. so epochincrements is the heavy op we are trying to avoid.

cc @aayushshah15 in case I'm off or maybe he has more to add.
