### ISSUE TITLE
roachtest: run some end-to-end multi-tenant roachperf benchmarks 

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#71664]
**Is your feature request related to a problem? Please describe.**

We don't have a good sense of what the throughput out to be for tenants in various topologies. It'd be nice to track that perf and understand overheads of various pieces of the multi-tenant infra.

**Describe the solution you'd like**
Set up roachtests which deploy the multi-tenant infra end-to-end and report some benchmarks to roachperf.

**Additional context**
Will require tooling to deploy the end-to-end multi-tenant cluster in roachprod. 

Jira issue: CRDB-10708

**Comment by knz** [comment]
@yuzefovich has achieved this.
