### ISSUE TITLE
cdc: CDC starter kit

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/cockroach#71678]
**Is your feature request related to a problem? Please describe.**

Onboarding to do changefeeds work requires a lot of learning, and that’s expensive. (Expensive == lots of talking to people, lots of code spelunking.)

**Describe the solution you'd like**

Our newest hire, @samiskin, has done a a lot of learning and organizing of ideas around changefeed architecture. Let’s get these structured and codified for the next CDC learner (including open source contributors!).

Two parts come to mind:

- Maybe this learning can be codified into tests – Shiranka used a lot of printf to follow state throughout the architecture. These printf’s can be thought of as assertions. A series of tests which represent each part of the architecture, and the expected state, would be a great learning tool. (I recognize this is a bit of an abstract idea.)
- Prose. Let’s structure some docs (probably Markdown in the codebase) to describe high-level features such as “backpressure” and “checkpointing”, with references to their concrete implementation.

cc @amruss @livlobo @miretskiy 

Jira issue: CRDB-10714

**Comment by miretskiy** [comment]
@samiskin can we publish the docs you've created and either update or close this issue?

**Comment by samiskin** [comment]
Ended up just always meeting with our new hire / interns around when they joined to give the full rundown in a long meeting.  Might end up writing something if more sinks get unified.
