### ISSUE TITLE
sql: pg_catalog.pg_constraint broken after swapping PK and altering column type

### ISSUE THREAD

**Issue by Marcuzz** [cockroachdb/cockroach#71709]
We're currently working on a rather large database migration where we're migrating ids to uuids in all of our old tables. During this migration process we first encountered #71089, and now we're back with yet another exciting bug for you guys 😂

This bug is actually two different parts:

When creating two simple tables, where one references the other via a FK, and swapping the primary keys around on the references table in order to alter the column type of the `id` column (first bug: this should be impossible due to the FK) we encounter a bug where selecting from `pg_catalog.pg_constraint;` completely breaks with the following error: `ERROR: column-id "1" does not exist`

**To Reproduce**

1. Set up a fresh CockroachDB cluster
2. Send the following queries:

```sql
CREATE TABLE a(id int8 primary key, legacy_id int8 not null);
CREATE TABLE b(a_id int8 references a (id));

BEGIN;
ALTER TABLE a DROP CONSTRAINT "primary";
ALTER TABLE a ADD CONSTRAINT "primary" PRIMARY KEY (legacy_id);
COMMIT;

SET enable_experimental_alter_column_type_general = true;
-- You may have to wait a few seconds for the asynchronous job to complete before running this query:
-- This query should also be impossible because table b.a_id references a.id
ALTER TABLE a ALTER COLUMN id TYPE uuid USING gen_random_uuid();

-- This query will now return an error
SELECT * FROM pg_catalog.pg_constraint;
```

3. See error:

```
(1 row)
(error encountered after some results were delivered)
ERROR: column-id "1" does not exist
```

**Expected behavior**

For `SELECT * FROM pg_catalog.pg_constraint;` to not return an error, and for changing the data type on a column that is referenced by a foreign key to be impossible. Could this possibly be related to `enable_experimental_alter_column_type_general`?

**Environment:**
 - CockroachDB version: `21.1.11`
 - Server OS: docker image, `cockroachdb/cockroach:v21.1.11`
 - Client app `cockroach sql`

**Additional context**
Introspection in tools like DataGrip is now fully broken, it's impossible to select from `pg_catalog.pg_constraint` and we've also noticed that it is impossible in some circumstances to check if a table has another colum via `pg_catalog.pg_tables` so there might be more to it.

**Comment by postamar** [comment]
I'm not able to repro the error with the above `DROP COLUMN` example, I'm afraid.

I'm sorry to say the reason you're seeing this error is that the fix for https://github.com/cockroachdb/cockroach/issues/71089 hasn't actually been merged to the 21.1 release branch yet: https://github.com/cockroachdb/cockroach/pull/71166. This is because we usually wait a couple of weeks for a change to "bake" in the master branch before actually backporting it.

**Comment by postamar** [comment]
That being said, there's something else at play here. I just checked out the branch for my backport and it also allows the `ALTER TYPE` in there when it shouldn't! As it turns out, `ALTER TYPE` never actually checks foreign key back-references.

**Comment by ajwerner** [comment]
@fqazi do you know what this is about?
