### ISSUE TITLE
spanconfig: add secondary tenant config for SQLTranslator datadriven tests

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#71733]
**Describe the problem**

We currently only run the SQLTranslator tests introduced in https://github.com/cockroachdb/cockroach/pull/71359 for the host tenant. We should extend these to run them for secondary tenants as well.

**Comment by irfansharif** [comment]
Done in https://github.com/cockroachdb/cockroach/pull/73416.
