### ISSUE TITLE
opt: use ordered aggregation on top a lookup join on ordered keys

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#71768]
Consider this schema:
```
CREATE TABLE f (
  filename
    STRING PRIMARY KEY,
  file_id
    UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
  file_size
    INT8 NOT NULL,
  username
    STRING NOT NULL,
  upload_time
    TIMESTAMP DEFAULT now()
);

CREATE TABLE p (file_id UUID, byte_offset INT8, payload BYTES, PRIMARY KEY (file_id, byte_offset));
```
I think the following two queries are equivalent, yet we use the hash aggregation for one of them:
```
root@127.0.0.1:26257/defaultdb> EXPLAIN (VEC) SELECT p.file_id, sum_int(length(p.payload))
                FROM f f LEFT OUTER JOIN p p ON p.file_id = f.file_id
                WHERE f.filename = 'abc' GROUP BY p.file_id;
                info
------------------------------------
  │
  └ Node 1
    └ *colexec.hashAggregator
      └ *rowexec.joinReader
        └ *colfetcher.ColBatchScan
(5 rows)


Time: 1ms total (execution 1ms / network 0ms)

root@127.0.0.1:26257/defaultdb> EXPLAIN (VEC) SELECT f.file_id, sum_int(length(p.payload))
                FROM f f LEFT OUTER JOIN p p ON p.file_id = f.file_id
                WHERE f.filename = 'abc' GROUP BY f.file_id;
                info
------------------------------------
  │
  └ Node 1
    └ *colexec.orderedAggregator
      └ *rowexec.joinReader
        └ *colfetcher.ColBatchScan
(5 rows)
```
I think we should be propagating the fact that `f.file_id` is ordered onto `p.file_id`, and then we'll get the ordered aggregation in both cases.

**Comment by RaduBerinde** [comment]
In the first case, we don't deduce that `p.file_id` is a constant column. We can definitely fix that.

The second case is interesting - in the optimizer, the GROUP BY column is constant and gets simplified, and we are planning a non-scalar aggregation with no grouping columns. As far as the optimizer and exec factory is concerned, they don't think they're building a streaming aggregation but vectorized does treat it that way (which is good).

**Comment by RaduBerinde** [comment]
#71792 fixes the first case. I will also make a separate change to show the streaming or hash aggregation more clearly in both `EXPLAIN` and `EXPLAIN (OPT)`, especially in this subtle case of no grouping columns.
