### ISSUE TITLE
The bigserial "type"

### ISSUE THREAD

**Issue by KenjiTakahashi** [cockroachdb/cockroach#7177]
I've seen that we now have the `SERIAL` pseudo-type support, which is nice. Now, how about the `BIGSERIAL` one?
The case is that I have an app using ORM which makes all IDs `BIGSERIAL` and I'd like to move it to Cockroach from Postgres, but keep it compatible.

Given that Cockroach's `SERIAL` is 64-bit anyway, perhaps simply aliasing `BIGSERIAL` to `SERIAL` would do?

As far as I can tell, that's the last thing keeping me from removing Postgres from that app :-).

[Same question can obviously be asked about `SMALLSERIAL` too, but I don't care about that one ;-D.]

**Comment by paperstreet** [comment]
Looks like we have the various INTs all aliased to be 64bits (https://www.cockroachlabs.com/docs/int.html). I'll do the same for SERIAL

**Comment by paperstreet** [comment]
@KenjiTakahashi This should make the next beta release (this week).

**Comment by KenjiTakahashi** [comment]
Nice, thanks @paperstreet :-)!
