### ISSUE TITLE
Make `changefeed.memory.per_changefeed_limit` cluster setting public

### ISSUE THREAD

**Issue by kathancox** [cockroachdb/cockroach#71785]
The `changefeed.memory.per_changefeed_limit` cluster setting is currently non-public, after some [discussion](https://cockroachlabs.slack.com/archives/C9TGBJB44/p1633617538110300) we would like to document this. As a result, the setting will be public-facing, so it might be better to switch this to `public`. This will then be pulled automatically into the docs [cluster settings page](https://www.cockroachlabs.com/docs/dev/cluster-settings.html#settings). 

Jira issue: CRDB-10767

**Comment by HonoreDB** [comment]
PR to do this https://github.com/cockroachdb/cockroach/pull/77230 was never successfully bors'd, we should do a quick check that the settings are still sensible to be made public and then make them public.
