### ISSUE TITLE
sql: SQL schema changes are too slow for ORM tests to adopt

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#71800]
Have discussed this privately with @ajwerner, but filing a tracking issue to centralise discussions.

We have, in the past, had issues with ORMs needing a lot longer to run CI tests compared to Postgres.

Using prisma as an example, it takes over 5 hours to run 7000 tests in their test suite (it's a subset of their entire suite). Each test creates a database and a few tables, and a few indexes after the tables are created. Even after dropping the database after each run and setting a low gc.ttlseconds, there are still issues. Postgres/MySQL take <15mins which contains over 18000 tests. ActiveRecord is another example, 2.5 hours in CockroachDB, <15mins for Postgres.

----

# Running Prisma Tests

## jaegar

* ` docker run -d --name jaeger -p 6831:6831/udp -p 16686:16686 jaegertracing/all-in-one:latest`
* open `localhost:16686`

## CockroachDB
* pull https://github.com/cockroachdb/cockroach/compare/master...otan-cockroach:fresh_prototype?expand=1
and `make buildshort (or whatnot)`
* start Cockroach `COCKROACH_JAEGER=localhost ./cockroach demo --insecure --empty --sql-port 5436 --max-sql-memory '8GiB'`
* run `set cluster setting sql.defaults.default_int_size = 4; set cluster setting sql.defaults.serial_normalization = 'sql_sequence';  SET CLUSTER SETTING sql.defaults.propagate_input_ordering.enabled = false; SET CLUSTER SETTING schemachanger.backfiller.buffer_increment = '128 KiB';  alter range default configure zone using gc.ttlseconds = '10'; -- prisma`

## prisma
* clone https://github.com/prisma/prisma-engines
* pull https://github.com/prisma/prisma-engines/compare/master...otan-cockroach:prototype_branch?expand=1
in the dir then run:
```
echo 'cockroach' > current_connector
cp ./query-engine/connector-test-kit-rs/test-configs/cockroach .test_config
```
* Run `cargo test -p query-engine-tests` - tests start off quick then slow down

Epic CRDB-10719

**Comment by rafiss** [comment]
Last time there was a deep investigation into this problem (https://github.com/cockroachdb/cockroach/issues/47790) it led to this fix relating to jobs adoption: https://github.com/cockroachdb/cockroach/pull/48608

I wonder if the other ideas in #47790 are still worth exploring (asking as a complete noob).

**Comment by vy-ton** [comment]
@otan for when you're back, I'd like to understand why we needed to set `sql.defaults.propagate_input_ordering.enabled`. This is relevant to Queries since we introduced this setting to help proceed with Graphile compatibility. FYI @rytaft

**Comment by otan** [comment]
We don't. I think I removed it In later iterations

**Comment by ajwerner** [comment]
We've done a bunch of work here. I'm closing this.
