### ISSUE TITLE
cc console: number of nodes in the CC console does not reflect what is shown in the DB Console

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#71840]
**Describe the problem**

Cluster on 21.1.10 in CC has 20 nodes, CC Console shows an old value of 15 before cluster was scaled. Scaling happened more than a week ago.

**Environment:**
 - CockroachDB version 21.1.10
 - Server OS: n/a this is CC

![image](https://user-images.githubusercontent.com/461296/138348611-55583ec6-d906-4127-9d06-2b45e7a96bf7.png)

![image](https://user-images.githubusercontent.com/461296/138348643-3e92e14f-78a6-43b7-965d-5fd0a22aa5ba.png)

**Comment by JuanLeon1** [comment]
This is a problem that is fixed, for this cluster.

It resulted from the horizontal scale of last week having failed, for lack of IOPS quota, and the operator (me) failing to finish all the steps manually, properly.

It was an SRE/Intrusion/AWS issue, affecting only this cluster.
