### ISSUE TITLE
stability: panic on basictracer.errAssertionFailed

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#7185]
`gamma` cluster running sha 0b950ce (just upgraded)

Node 4 (`104.196.98.24`) died shortly after startup with:
```
panic: (*basictracer.errAssertionFailed) (0x1596ee0,0xc826278b40)

goroutine 90 [running]:
panic(0x1596ee0, 0xc826278b40)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/opentracing/basictracer-go.(*spanImpl).maybeAssertSanityLocked(0xc822fd38c0)
        /go/src/github.com/opentracing/basictracer-go/debug.go:27 +0xd5
github.com/opentracing/basictracer-go.(*spanImpl).Lock(0xc822fd38c0)
        /go/src/github.com/opentracing/basictracer-go/debug.go:19 +0x3b
github.com/opentracing/basictracer-go.(*spanImpl).Log(0xc822fd38c0, 0x0, 0x0, 0x0, 0x1a3f940, 0xe, 0x0, 0x0)
        /go/src/github.com/opentracing/basictracer-go/span.go:106 +0xaf
github.com/opentracing/basictracer-go.(*spanImpl).LogEvent(0xc822fd38c0, 0x1a3f940, 0xe)
        /go/src/github.com/opentracing/basictracer-go/span.go:94 +0x7d
github.com/cockroachdb/cockroach/util/log.Trace(0x7f953e264068, 0xc821a02ae0, 0x1a3f940, 0xe)
        /go/src/github.com/cockroachdb/cockroach/util/log/trace.go:29 +0x63
github.com/cockroachdb/cockroach/storage.(*Replica).processRaftCommand(0xc82062a360, 0xc826278b10, 0x8, 0x153db, 0x57a, 0x400000004, 0x1, 0x1457a96f6f42dd11, 0x0, 0x400000004, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:1879 +0x5f2
github.com/cockroachdb/cockroach/storage.(*Replica).handleRaftReady(0xc82062a360, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:1567 +0xbf7
github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1()
        /go/src/github.com/cockroachdb/cockroach/storage/store.go:2095 +0x35d
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8203596c0, 0xc820dabf90)
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62
```

Latest log:
[cockroach.stderr.gz](https://github.com/cockroachdb/cockroach/files/311959/cockroach.stderr.gz)

**Comment by tschottdorf** [comment]
I'll take a look. This is use-after-finish of a trace.

On Mon, Jun 13, 2016, 10:06 marc <notifications@github.com> wrote:

> gamma cluster running sha 0b950ce
> <https://github.com/cockroachdb/cockroach/commit/0b950ce267fae48b64e66211cb0e51cdecb3d4fa>
> (just upgraded)
>
> Node 4 (104.196.98.24) died shortly after startup with:
>
> panic: (*basictracer.errAssertionFailed) (0x1596ee0,0xc826278b40)
>
> goroutine 90 [running]:
> panic(0x1596ee0, 0xc826278b40)
>         /usr/local/go/src/runtime/panic.go:481 +0x3e6github.com/opentracing/basictracer-go.(*spanImpl).maybeAssertSanityLocked(0xc822fd38c0)
>         /go/src/github.com/opentracing/basictracer-go/debug.go:27 +0xd5github.com/opentracing/basictracer-go.(*spanImpl).Lock(0xc822fd38c0)
>         /go/src/github.com/opentracing/basictracer-go/debug.go:19 +0x3bgithub.com/opentracing/basictracer-go.(*spanImpl).Log(0xc822fd38c0, 0x0, 0x0, 0x0, 0x1a3f940, 0xe, 0x0, 0x0)
>         /go/src/github.com/opentracing/basictracer-go/span.go:106 +0xafgithub.com/opentracing/basictracer-go.(*spanImpl).LogEvent(0xc822fd38c0, 0x1a3f940, 0xe)
>         /go/src/github.com/opentracing/basictracer-go/span.go:94 +0x7dgithub.com/cockroachdb/cockroach/util/log.Trace(0x7f953e264068, 0xc821a02ae0, 0x1a3f940, 0xe)
>         /go/src/github.com/cockroachdb/cockroach/util/log/trace.go:29 +0x63github.com/cockroachdb/cockroach/storage.(*Replica).processRaftCommand(0xc82062a360, 0xc826278b10, 0x8, 0x153db, 0x57a, 0x400000004, 0x1, 0x1457a96f6f42dd11, 0x0, 0x400000004, ...)
>         /go/src/github.com/cockroachdb/cockroach/storage/replica.go:1879 +0x5f2github.com/cockroachdb/cockroach/storage.(*Replica).handleRaftReady(0xc82062a360, 0x0, 0x0)
>         /go/src/github.com/cockroachdb/cockroach/storage/replica.go:1567 +0xbf7github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1()
>         /go/src/github.com/cockroachdb/cockroach/storage/store.go:2095 +0x35dgithub.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8203596c0, 0xc820dabf90)
>         /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
> created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
>         /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62
>
> Latest log:
> cockroach.stderr.gz
> <https://github.com/cockroachdb/cockroach/files/311959/cockroach.stderr.gz>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/7185>, or mute the thread
> <https://github.com/notifications/unsubscribe/AE135Bm1bexm-sGiFNLbg5IqODEnZRugks5qLWPJgaJpZM4I0XHb>
> .
>
-- 

-- Tobias

**Comment by mberhault** [comment]
occurred on multiple `beta` nodes after upgrade from c17928f to 0b950ce

**Comment by mberhault** [comment]
@tschottdorf, @bdarnell, @tamird 
Upgraded all nodes to 0214643.
Nodes 4 (`104.196.98.24`) and 5 (`104.196.39.184`) still crashed right away with:
```
F160614 20:26:27.555255 storage/store.go:2243  store=4:4 ([]=/mnt/data) replicaDescCache: clobbering {2 2 5} with {6 6 5}
goroutine 81 [running]:
github.com/cockroachdb/cockroach/util/log.getStacks(0xecef25f01, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/util/log/clog.go:862 +0xb8
github.com/cockroachdb/cockroach/util/log.(*loggingT).outputLogEntry(0x28c6720, 0x3, 0x22dc19d, 0x10, 0x8c3, 0xc82384f720, 0x4a)
        /go/src/github.com/cockroachdb/cockroach/util/log/clog.go:728 +0x9c5
github.com/cockroachdb/cockroach/util/log.addStructured(0x0, 0x0, 0xc800000003, 0x2, 0x1b99e40, 0x2a, 0xc82133b9e8, 0x3, 0x3)
        /go/src/github.com/cockroachdb/cockroach/util/log/structured.go:57 +0xfc
github.com/cockroachdb/cockroach/util/log.logDepth(0x0, 0x0, 0x1, 0xc800000003, 0x1b99e40, 0x2a, 0xc82133b9e8, 0x3, 0x3)
        /go/src/github.com/cockroachdb/cockroach/util/log/log.go:73 +0x7b
github.com/cockroachdb/cockroach/util/log.Fatalf(0x1b99e40, 0x2a, 0xc82133b9e8, 0x3, 0x3)
        /go/src/github.com/cockroachdb/cockroach/util/log/log.go:179 +0x66
github.com/cockroachdb/cockroach/storage.(*Store).cacheReplicaDescriptorLocked(0xc8201622c0, 0xe53, 0x600000006, 0xc800000005)
        /go/src/github.com/cockroachdb/cockroach/storage/store.go:2243 +0x288
github.com/cockroachdb/cockroach/storage.(*Store).handleRaftMessage(0xc8201622c0, 0xc82365b680, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/storage/store.go:2041 +0x4e5
github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1()
        /go/src/github.com/cockroachdb/cockroach/storage/store.go:2123 +0x552
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820343b20, 0xc820e4f180)
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62
```

**Comment by bdarnell** [comment]
Let's make a new issue for the replicaDescCache clobbering.

**Comment by tschottdorf** [comment]
Yeah, that failure is likely not directly related to the problem fixed in this issue.

**Comment by tschottdorf** [comment]
#7224
