### ISSUE TITLE
bazel: gomock bottlenecks build significantly

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#71854]
**Describe the problem**

We hooked up gomock into our bazel build recently (#67226); it's pretty slow.

**To Reproduce**

To grab a profile, I started with a fresh bazel build, switched to a branch rebased on top of the original (and adding a few changes). 
```
$ ./dev build cockroach-short -- --profile=bazel-profile.gz
```

For some super unscientific analysis looking to our worst offendors (the re-build took 100s+, and incremental `make buildshort` was ~40s).

```
$ bazel analyze-profile bazel-profile.gz  
Critical path (148.265 s):
...
       Time Percentage   Descriptiona'
   13.467 s    9.08%   action 'GoLink pkg/kv/kvclient/kvcoord/mock_kvcoord_gomock_prog_bin_/mock_kvcoord_gomock_prog_bin'
    3.255 s    2.20%   action 'GoMockReflectExecOnlyGen pkg/kv/kvclient/kvcoord/mocks_generated.go'
    9.320 s    6.29%   action 'GoPath pkg/kv/kvclient/rangefeed/mock_rangefeed_gomock_gopath'
    7.300 s    4.92%   action 'Action pkg/kv/kvclient/rangefeed/mocks_generated.go'
...
   26.920 s   18.16%   action 'GoLink pkg/cmd/cockroach-short/cockroach-short_/cockroach-short'
```

Another iteration of the exercise showed the same.
```
    4.968 s    3.43%   action 'GoCompilePkg pkg/roachpb/roachpb.a'
    5.439 s    3.75%   action 'GoCompilePkg pkg/roachpb/with-mocks.a'
    8.227 s    5.67%   action 'GoLink pkg/kv/kvclient/kvcoord/mock_kvcoord_gomock_prog_bin_/mock_kvcoord_gomock_prog_bin'
    7.008 s    4.83%   action 'GoPath pkg/kv/kvclient/rangefeed/mock_rangefeed_gomock_gopath'
    4.574 s    3.15%   action 'Action pkg/kv/kvclient/rangefeed/mocks_generated.go'
```

**Expected behavior**

This is probably one of many performance bottlenecks in our build-system. As we start using Bazel in earnest, it'd be good to squash these out.

Epic CRDB-8036

**Comment by ajwerner** [comment]
This seems to be due almost entirely to the the use of source-only gomock generation. We do this in two places because of unexported interfaces.
