### ISSUE TITLE
ui: app filter is not preserved when swtiching between transaction and statement page

### ISSUE THREAD

**Issue by Azhng** [cockroachdb/cockroach#71851]
Reproduction steps

https://user-images.githubusercontent.com/9267198/138365353-e525ec59-af02-4892-a73e-77e98e8d7fad.mov

**Comment by maryliag** [comment]
List of locations to update the behaviour:

- [ ]  Statements page Filter - https://github.com/cockroachdb/cockroach/pull/72946
- [ ] Statements page Search - 
- [ ] Transactions page Filter - 
- [ ] Transactions page Search -
