### ISSUE TITLE
cli: add `recover execute-plan` to recover range from loss of quorum

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#71863]
As part of the improved loss of quorum tooling in #71860, we should implement a `debug recover execute-plan <store> <plan>` command which uses a recovery plan generated by `debug recover make-plan` and applies it to the local store. This involves rewriting the range descriptor for the designated survivor to make it the only voter, and GC the other replicas.

For more details, see the [internal RFC draft](https://docs.google.com/document/d/1CyO7qhYF7tU0igvzk7k0ScdP9ySMgqmtiZ_hydBTfrA/edit).

Epic: CRDB-1513

**Comment by aliher1911** [comment]
No more pending changes for apply plan commands.
