### ISSUE TITLE
Use of jsonb_array_elements function as part of the WHERE clause and GROUP BY

### ISSUE THREAD

**Issue by cjireland** [cockroachdb/cockroach#71872]
I can use jsonb_array_elements() to create a computed column.

However I cannot then use that function/computed column in a WHERE clause or a GROUP BY.

So:

Case 1:

```
select jsonb_array_elements(json-col -> 'structure') -> 'field' as my_column
from ...
WHERE jsonb_array_elements(json-col -> 'structure') -> 'field' = 'value'
```

Case 2:

```
select jsonb_array_elements(json-col -> 'structure') -> 'field' as my_column,
          etc.
from ...
GROUP BY 1
```

In the first case I get:

`ERROR: jsonb_array_elements(): generator functions are not allowed in WHERE`

In the second case I get:

 `ERROR: jsonb_array_elements(): generator functions are not allowed in GROUP BY`

Given the GROUP BY applies to the result of the SELECT I would have thought that the source of the data value at that point would be irrelevant.

**Describe the solution you'd like**

I would like to be able to use this function in both a WHERE clause and as part of a GROUP BY.

In the case of a GROUP BY I am happy to use the ordinal column position (so GROUP BY 1).

**Comment by rytaft** [comment]
Need to check whether this works in Postgres

**Comment by rytaft** [comment]
Sorry for the delay.

> I can use jsonb_array_elements() to create a computed column.

I'm surprised at this. On both Postgres and CockroachDB I get an error `ERROR:  set-returning functions are not allowed in column generation expressions
` or `ERROR: jsonb_array_elements(): generator functions are not allowed in computed column`. Can you print out what you ran that was successful?

> However I cannot then use that function/computed column in a WHERE clause or a GROUP BY.

This doesn't work in Postgres either. For WHERE I get `ERROR:  set-returning functions are not allowed in WHERE`. And for GROUP BY I get `ERROR:  could not identify an equality operator for type json`.

You could probably get around this by wrapping the output of jsonb_array_elements in a subquery. For example:
```
SELECT my_column FROM (
  SELECT json_array_elements(j -> 'structure') -> 'field' AS my_column FROM t
) GROUP BY 1;
```

Does this help?

**Comment by cjireland** [comment]
Thanks @rytaft

**Comment by rytaft** [comment]
Glad to help, @cjireland! Hopefully you were able to rewrite the query using subqueries. I'm going to close out this issue, but feel free to reopen (or open a new issue) if it's not resolved.
