### ISSUE TITLE
roachprod: add `--retry` option to `run` command

### ISSUE THREAD

**Issue by jlinder** [cockroachdb/cockroach#71929]
## Is your feature request related to a problem? Please describe.

Sometimes network errors cause a given request to a remote service to fail but would be successful if tried again. Sometimes a remote server may be unavailable but would be if called again (see #71799). 

For `roachprod run`, this can happen for the ssh call to the cluster nodes or to a remote server from one of the cluster nodes. This issue only concerns the call to a remote server from a cluster node.

## Suggested solution

Add a `--retry` option to `roachprod run` so users / programs can tell roachprod to retry a call if it fails. Suggested UI:

- `--retry` does a default of two retries
- `--retry=X` where X is the number of retries to attempt on failure
- Perform the first retry after 1 second. Then use an exponential back-off for subsequent retries with a max wait of 512 seconds.
- Retries should only be performed for nodes that have an error

### Questions to consider

- Should the retry run for all errors encountered by the command that is run? or should it try to determine if the error was caused by a network request and only retry then?
- Should the retry be at a higher level (i.e., at the caller's level where they know what command was being run and whether it can/should be tried again)?

## Alternate solutions

- When errors like these happen during setup of a roachtest and cause a roachtest to fail, have the roachtest retry the call or restart the test.
- Have roachtest build a retry wrapper function for use with `roachprod run` calls.

Jira issue: CRDB-10837

Epic CRDB-10428

**Comment by renatolabs** [comment]
I'm closing this issue. A lot of work has been done in this space since the issue was created (including automatic retries). There might still be gaps, but we can create more pointed issues to address those if necessary.
