### ISSUE TITLE
roachprod: add support for multi-tenant clusters

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#71947]
This issue tracks adding multi-tenant support to `roachprod`. It should allow spawning a tenant pod cluster against an existing host cluster, and it should allow setting up both the host cluster and tenant cluster(s) in one command.

It should allow running an entire multitenant setup locally, hence #71945 is a dependency.

Jira issue: CRDB-10845

**Comment by ajstorm** [comment]
This work is complete.  The only thing that's not done is the collapsing of the start into a single command, but that's not deemed as critical right now.
