### ISSUE TITLE
ui: utilize heat maps to visualize latency related metrics in graphs

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#71953]
**Is your feature request related to a problem? Please describe.**
In DB Console (and Cloud Console), we currently visualize latency metrics as line graphs. In doing so, we are constrained to explicitly visualizing one time series for a particular percentile, e.g. our SQL Latency graphs showcase P99 latencies. One side effect of this is certain end users have misinterpreted the graph and think that the P99 reported latency represents the typical performance when it in fact does not. Furthermore, at a higher-level, end users can miss certain latency patterns/distributions/details in simple line graphs.

**Describe the solution you'd like**
Ideally, we can display a [heat map](https://www.brendangregg.com/heatmaps.html) so that end users can more easily see the distribution of latencies. 

This has been a recurring feature request and is one thing that will improve our metrics visualization experience for end users who rely on it to monitor latency for their CRDB clusters.

Epic CC-4894

Jira issue: CRDB-10846

**Comment by jlinder** [comment]
Stale issue. Closing.
