### ISSUE TITLE
cdc: define initial scan progress model and surface in db console

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#71958]
Right now, there is no observability into changefeed initial table scans (progress, status). This can be incredibly frustrating for users. Backfills can take days to complete. If something goes wrong with a backfill, there is nothing to alert on or monitor outside of the logs. This is a big pain point for users.

We should first define a model to estimate backfill progress (% done, time remaining) and surface that in the DB console, similar to the way we do for backups:
<img width="1209" alt="Screen Shot 2021-10-25 at 12 37 32 PM" src="https://user-images.githubusercontent.com/13264141/138762855-7bd027a8-0859-4e95-952f-5f19d4490632.png">

CRDB-10204

Epic CRDB-10204

Jira issue: CRDB-10877

**Comment by miretskiy** [comment]
We have metrics on the number of ranges remaining to be backfilled.
Closing this issue.
@amruss  -- feel free to reopen if disagree.
