### ISSUE TITLE
ui,jobs: improve UI for `cancel-requested`, `pause-requested`, and `revert-failed` statuses on the jobs page

### ISSUE THREAD

**Issue by jocrl** [cockroachdb/cockroach#71963]
**Is your feature request related to a problem? Please describe.**
Currently, the three statuses `cancel-requested`, `pause-requested`, and `revert-failed` are present in the back end code (https://github.com/cockroachdb/cockroach/blob/master/pkg/jobs/jobs.go#L198), but are not enumerated or treated specially in the front end (https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/db-console/src/views/jobs/jobStatusOptions.ts#L27). This causes these statuses to have a blue coloring for their badge, even though another color would better convey meaning.

![image](https://user-images.githubusercontent.com/91907326/138773770-84aa4637-d87c-47a2-bd07-7d02c2322982.png)

**Describe the solution you'd like**
Assuming that these statuses are real, I think the following would make sense?
- `cancel-requested`: gray, same as cancelled
- `pause-requested`: gray, same as paused
- `revert-failed`: red, same as failed

@Annebirzin @kevin-v-ngo 

Jira issue: CRDB-10868

**Comment by vy-ton** [comment]
Discussed with @kevin-v-ngo, we want to keep the original statuses in case the translation causes more confusion.
