### ISSUE TITLE
Serverless session page shows no data despite having active sessions 

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#71992]
A customer had 20 sessions with running queries and saw no data on the serverless sessions page.

**Comment by Azhng** [comment]
I just tried to reproduce this on the staging and all the sessions I opened showed up as expected on the Session Page. I'm not sure what else to try next. Is there anything else the customer was doing at that time?

**Comment by kevin-v-ngo** [comment]
@timveil, has this issue been reoccurring for you (this was from your flightchop serverless feedback)? In regards to improving the actual information surfaced on the Sessions page, this is tracked with this issue: https://github.com/cockroachdb/cockroach/issues/73463.

**Comment by kevin-v-ngo** [comment]
@timveil, closing for now as we have no repro of the issue.
