### ISSUE TITLE
bazel: sql/pgwire tests that depend on unix sockets fail on macOS

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#72027]
Some of the pgwire tests depend on creating a unix socket. By default they do this in a temporary directory created inside the working directory of the test process. 

On macOS (and other BSD-derived operating systems), unix sockets have a maximum path length ([unix(4)](https://www.freebsd.org/cgi/man.cgi?query=unix&sektion=4)):

> UNIX-domain addresses are variable-length filesystem pathnames of at most 104 characters. 

Unfortunately, the sandbox URLs created by bazel exceed this, even if you have a relatively short username, leading to errors such as:

```
listen unix /private/var/tmp/_bazel_ssd/a51ea94df2f483aee3088dde6a3dde4e/sandbox/darwin-sandbox/9676/execroot/cockroach/_tmp/860d3fe9445dbd5f3d8059cc7b96f0f6/TestAuth117232692/.s.PGSQL.6: bind: invalid argument
```

The temporary path `/private/var/tmp/_bazel_ssd/a51ea94df2f483aee3088dde6a3dde4e/sandbox/darwin-sandbox/9676/execroot/cockroach/_tmp/860d3fe9445dbd5f3d8059cc7b96f0f6/TestAuth117232692/.s.PGSQL.6` is 174 characters long.

Epic CRDB-8036

**Comment by jlinder** [comment]
Hi. I put this issue onto the SQL Experience board since you may get to it faster than dev inf would. It's still in one of our epics so we will be able to see it in epic review.

A little guidance care of @rickystewart:

>  Creating unix sockets "inside the working directory of the test process" is evidently not going to work w/ bazel, so you'll have to hard-code the directory to a random subdir under `/tmp` or something similar. You can guard that logic behind an `if BuiltWithBazel() && (GOOS == "darwin" || strings.Contains(GOOS, "bsd"))`. I haven't looked at the code, but presumably the change would be pretty simple.

**Comment by rafiss** [comment]
@jlinder @rickystewart This test, and many others, work by calling `ioutil.TempDir`. When the first argument to that function is `""`, then the function defaults to using `os.TempDir()` as the base tmp directory. `os.TempDir()` is implemented as follows:
```
	dir := Getenv("TMPDIR")
	if dir == "" {
		if runtime.GOOS == "android" {
			dir = "/data/local/tmp"
		} else {
			dir = "/tmp"
		}
	}
	return dir
```

Question: Could the bazel sandbox simply set the `TMPDIR` environment variable  to be `/tmp` and avoid a whole class of these problems? On my mac the environment variable is:
```
❯ echo $TMPDIR
/var/folders/1_/_kcb28_94w16ml515w877ynm0000gn/T/
```

**Comment by rickystewart** [comment]
We could conceivably make that change only for `dev` builds. CI has to keep the current logic, but CI is on Linux so it doesn't make a difference with regard to the bugs in question.

**Comment by rafiss** [comment]
I see, well I'll let you decide if you want to make a separate issue to do that for `dev` builds. In the meantime I have created https://github.com/cockroachdb/cockroach/pull/72875
