### ISSUE TITLE
changefeedccl: cdc ux violation: detected timestamp ‹197001010000000000000000000000000› that is less than or equal to the local frontier

### ISSUE THREAD

**Issue by chrikar** [cockroachdb/cockroach#72033]
**Describe the problem**

We have a cdc steamer using golang's `database/sql` package on our environment that reads from cockroachdb. We recently attempted to upgrade cockroachdb from v20.2.7 to v21.1.10, and cockroachdb keeps throwing the following error:

```
"E211027 09:14:57.656275 7226198 ccl/changefeedccl/changefeed_processors.go:647 ⋮ [n1,client=‹10.1.20.70:59422›,hostnossl,user=root] 182600  cdc ux violation: detected timestamp ‹197001010000000000000000000000000› that is less than or equal to the local frontier ‹202110270914526859353470000000000›.
```

There is no evident error or impact from the app side, and it seems to be able to retrieve a reasonable amount of data. We haven't yet found some noticeable data loss.

We have not yet proceeded to finalize the upgrade as per [instructions](https://www.cockroachlabs.com/docs/v21.1/upgrade-cockroach-version) due to this issue. 

A sample of the query as shown in `show queries` is:
```sql
EXPERIMENTAL CHANGEFEED FOR TABLE schema_migrations, space_settings WITH updated, resolved = '300s', cursor = '1635330041458686058.0000000000'
```

**Environment:**
 - CockroachDB version: Upgrading v20.2.7 to v21.1.10
 - Client app: Golang 1.16, database/sql

**Comment by miretskiy** [comment]
@chrikar I want to confirm something: All the nodes have been restarted w/ v 21.1.10; it's just the upgrade has not been finalized yet.  Is this accurate?

Also, I assume you're still seeing those messages in the logs.

**Comment by chrikar** [comment]
Hi @miretskiy! Thx a lot for checking the issue!

> @chrikar I want to confirm something: All the nodes have been restarted w/ v 21.1.10; it's just the upgrade has not been finalized yet. Is this accurate?
> 
> Also, I assume you're still seeing those messages in the logs.

I can confirm both of these, yes.

**Comment by miretskiy** [comment]
Another question: You mentioned ⬆️  that
| The error where the first timestamp is a few mins (approx. 5-10) earlier than the second one (local frontier) we were also seeing before

Just to confirm: you were seeing those errors even before you attempted the upgrade (version 20.2.7)?

**Comment by chrikar** [comment]
Yes. The errors with the timestamp like `textPayload: "E211017 19:30:48.686508 1257828199 ccl/changefeedccl/changefeed.go:252 ⋮ [n3,client=‹10.1.22.49:50084›,hostnossl,user=root] cdc ux violation: detected timestamp ‹202110171928152049328280000000000› that is less than or equal to the local frontier ‹202110171930443014681250000000000›.
` we were seeing before, but it was only appearing x10-15 times every time we restarted the service (=every 30mins).

**Comment by stevendanna** [comment]
@chrikar By any chance, are you using interleaved tables?

**Comment by chrikar** [comment]
Hi @stevendanna !

> @chrikar By any chance, are you using interleaved tables?

Indeed we (still) do. Planning to remove those but haven't got around to it yet. Would setting the `sql.defaults.interleaved_tables.enabled` cluster setting do the trick for now?

**Comment by stevendanna** [comment]
> Indeed we (still) do.

Thanks for the info!

> Would setting the sql.defaults.interleaved_tables.enabled cluster setting do the trick for now?

I don't believe that cluster setting will influence what you are seeing with changefeeds at the moment. Or at least, I have no reason to think it will.

The interleaved tables might at least explain how you saw a value with a zero timestamp in one case (`197001010000000000000000000000000`), but there is still the question of why you are seeing this with non-zero timestamps at all.

**Comment by miretskiy** [comment]
I think @stevendanna observation re interleave tables is spot on.  We do have explanation for zero timestamp messages;
we don't quite have full pictures w/ non-zero ts.  However, given how underutilized interleave code was, and the fact that
it's no longer supported, I think the best way forward is to try dropping interleaved indexes and testing to see if the problem goes away.

@chrikar @fracasula Please ping this issue when you have more details.

**Comment by chrikar** [comment]
Thank you @miretskiy! We'll try removing the interleaved tables and we'll let you know

**Comment by fracasula** [comment]
Removing the interleaved tables did solve the problem, thanks guys! :+1: 
As a side note, we had to start from scratch (i.e. with no cursor) because we were getting this error:

```
pq: primary key change occurred: schema change occurred at 1635927852059522490.0000000000
```

It's running fine now.

**Comment by miretskiy** [comment]
Closing this issue for now.  Feel free to reopen if you run into additional issues.
