### ISSUE TITLE
server,sql: enable running SQL statements before the node start draining

### ISSUE THREAD

**Issue by Azhng** [cockroachdb/cockroach#72045]
Currently, CockroachDB has subsystems (e.g. SQL Stats) that holds data in-memory and flushes them into system tables periodically. 
When a node shuts down, these subsystems should be notified and start to flush their in-memory data into system tables, otherwise the in-memory data will just simply be deleted and cannot be recovered.
This becomes an issue in Serverless clusters, where the tenant node is shutdown after a period of inactivity, (usually less than the flush interval).

CRDB's current shutdown process looks like following:

```
shutdown requested -> block incoming sql traffic -> start draining -> stop stopper
```

We would like to introduce additional stage in the shutdown process:

```
shutdown requested -> block incoming sql traffic -> run final sql -> start draining -> stop stopper
```

This allows subsystems like SQL Stats to have a chance to flush its in-memory data during the graceful shutdown. 

cc: @cockroachdb/server 
cc: @cockroachdb/sql-observability 

Epic CRDB-11087

**Comment by knz** [comment]
will need this work to happen too: #74412

**Comment by Azhng** [comment]
So I would say we are fine with having a little bit of data loss of internal SQL statistics in the final phase of draining process.

**Comment by cameronnunez** [comment]
> I think it's fine to start draining when we know there's no longer any active SQL connections. 

So the tricky part is that we know we don't have any active connections only after the drain of SQL connections is complete. So the drain sequence looks like:
1. Initial wait
2. Reject new connections and transactions.
3. Drain the SQL layer.
    a. Drain SQL client connections. (**no connections will remain afterwards**)
    b. Drain distributed SQL execution flows.
    c. Drain SQL table leases.
4. Drain range leases & leadership.

But if you're saying the data loss is minimal, we could throw it between steps 2 and 3.

**Comment by Azhng** [comment]
Hmm, is it possible to put it between 3b and 3c ? (This definitely would be ideal)

Quick question re. 3a step. When you say "no connections will remain afterwards", is it possible that we would still have internal executor running?

**Comment by cameronnunez** [comment]
> Hmm, is it possible to put it between 3b and 3c ? (This definitely would be ideal)
Sounds good.

> is it possible that we would still have internal executor running?
Yes, the executor stops running after 3c.

**Comment by Azhng** [comment]
Perfect!
