### ISSUE TITLE
sql: support date_trunc

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#7211]
Allows truncating a date to arbitrary date specs, useful for aggregating things by min/hour/day/week/month/etc...

see https://www.postgresql.org/docs/9.1/static/functions-datetime.html#FUNCTIONS-DATETIME-TRUNC for details.

**Comment by mberhault** [comment]
@mjibson: not sure if this is a desired feature or not. Feel free to close.

**Comment by vishr** [comment]
Nice to have

**Comment by vishr** [comment]
I personally believe this is an important feature to have for any time series operation, e.g. group by hour, day, week etc.

**Comment by vishr** [comment]
I was trying to simulate `date_trunc` using `extract` but found that `extract` function does not accept timestamptz type. I hope the implementation covers it as in Postgres.

**Comment by vivekmenezes** [comment]
@vishr is this something you need soon? It is on our roadmap but we're considering moving it out of our 1.1 release. Thanks!

**Comment by vishr** [comment]
@vivekmenezes It can wait. For now, I am using `extract` function as @mjibson suggest on gitter, its ugly but works.

**Comment by vivekmenezes** [comment]
Thanks, your patience is much appreciated!

**Comment by rytaft** [comment]
Completed as part of PR #19297.
