### ISSUE TITLE
sql: MakeColumnDefDescs (maybe) does not track dependencies for DEFAULT and ON UPDATE correctly

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#72116]
**Describe the problem**

From the comment of `MakeColumnDefDescs`:
> // The DEFAULT expression is returned in TypedExpr form for analysis (e.g. recording
> // sequence dependencies).

However, if you look at the implementation: https://github.com/cockroachdb/cockroach/blob/f7c4ed01e7f9d172b86b42cc5012909c6850168d/pkg/sql/catalog/tabledesc/table.go#L103

The same typedExpr variable is used for both DEFAULT and ON UPDATE clauses.

**To Reproduce**

I don't know yet what bug this causes. But it feels like it could be a problem for something.

**Expected behavior**
Add a separate return value for DEFAULT and ON UPDATE expressions, and fix the function comment.

**Comment by postamar** [comment]
@rafiss that's gracious of you. I looked into it and fix seemed straightforward so I just did it, but I'd appreciate your team's support in reviewing my PR and the subsequent backport PRs, please.

For what it's worth, in my opinion anyone could have made this bug. The logic tests that accompanied the introduction of this ON UPDATE feature were solid enough and in fact came surprisingly close to catching it.

Is this a release blocker for 21.2? I'll leave that up to you. As far as I'm concerned I'm happy as long as this is fixed no later than in the 21.2.1 release.

**Comment by rafiss** [comment]
I don't consider this a GA blocker, so 21.2.1 sounds good to me. thanks for taking this on! i can help with reviews
