### ISSUE TITLE
ui: navigating away from a Metrics dashboard and then going back results in no graphs loading for that dashboard

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#72114]
**Describe the problem**

Within the DB Console Metrics page, if you navigate away from a dashboard and attempt to go back to it, you will no longer be able to load those graphs.

**To Reproduce**

1. Do a fresh reload of the DB Console Metrics page and continue staying on "Dashboard: Overview"
2. Go to the time picker and choose a new time window, say "past 1 day"
2. Now, go to a different dashboard, say "Dashboard: Hardware"
3. Now, go back to "Dashboard: Overview". Here you'll notice that no graphs load. 

In fact, you can chain this together. If you go from "Dashboard: Overview", to "Dashboard: Hardware", to "Dashboard: Runtime", and decide to revisit any one of those dashboards, none of their graphs will load.

https://user-images.githubusercontent.com/1474303/139314324-e3e68f2d-bfca-4259-86ae-e5537d2cfadb.mov

**Environment**
* Testing on v21.1.11 on roachprod
* Happens on a small (4 node) and large (100+ node) cluster

Epic CRDB-8038

**Comment by zachlite** [comment]
@thtruo This is resolved in https://github.com/cockroachdb/cockroach/pull/72431

**Comment by koorosh** [comment]
https://github.com/cockroachdb/cockroach/pull/72431 PR resolves another issue that relevant to rendering old metrics that can be removed after some period of time. This issue is more about incorrect requests dispatching on frontend.

Relevant to: https://github.com/cockroachdb/cockroach/issues/72874

**Comment by thtruo** [comment]
Closing this as the fix was merged with PR #72919
