### ISSUE TITLE
ui: clicking anywhere on the screen after dragging-to-zoom in DB Console's custom chart causes your time scale to keep zooming further 

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#72112]
**Describe the problem**

Clicking anywhere on the screen after dragging-to-zoom in DB Console's custom chart causes your time scale to keep zooming further. This makes the custom chart unusable when you're investigating an issue around a particular time scale. It interrupts workflow

**To Reproduce**

1. Go to the custom chart page
2. Add a metric, for example `sql.service.latency-p99.999`
3. Drag to zoom on a smaller time scale within the graph
4. Here's the issue: after dragging-to-zoom, no matter where you click on the screen it will cause further zooming around the area you dragged. 
5. This is not only distracting, but it interrupts a user's workflow when they are attempting to investigate a spike at a particular time

https://user-images.githubusercontent.com/1474303/139313014-fa87efb3-a691-4f39-8daf-21e4b46520a4.mov

**Environment**
* Testing on v21.1.11 on roachprod
* Happens on a small (4 node) and large (100+ node) cluster

Epic CRDB-8038

**Comment by zachlite** [comment]
Hey @thtruo, I'm unable to recreate this on master.  I've confirmed that  https://github.com/cockroachdb/cockroach/pull/70229 resolved this issue, but the fix wasn't included in the 21.1.11 release which is why you see it on roachprod.

**Comment by thtruo** [comment]
Thanks for checking @zachlite. This re-raises another point around backporting the #70229 changes to the next patch release of 21.2 and 21.1; I'm going to drop a comment on that linked PR to get confirmation if we have a backport for the other release versions.
