### ISSUE TITLE
Developers can correlate time-series metrics across Transactions and Statements pages in the CC console through a global time picker

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#72128]
This issue tracks the ability for developers to use a global time picker across the SQL metrics, Transactions, and Statements pages. This will allow basic correlation across these pages. The global time picker will also update how statistics are aggregated across the statements and transaction pages. 

Figma mockups: https://www.figma.com/file/xdmwvnFQd6KkO9RJ0XLDH0/22.1_SQL-obsrv_query-performance?node-id=3488%3A10430

Epic: CRDB-6564

Jira issue: CRDB-10958

**Comment by jocrl** [comment]
Hi @kevin-v-ngo and @Annebirzin ,
The time picker selection in the metrics page is currently shared with three other pages, listed below. When the time selection is changed in the metrics page, it also changes the selection in those pages and vice versa.

For this task to share the time picker between the metrics, statements, and transaction pages, am I correct to understand that we also want to continue sharing it across all the pages below?

- /overview/map
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/91907326/154563175-b63b0e09-3cd2-482f-bae0-fbf7d5552368.png">
- /raft/messages/all
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/91907326/154563272-a4f7cbbc-efb8-4d46-aed4-ca7a84043de5.png">
- /debug/chart
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/91907326/154563385-d734fce6-f071-4d29-975e-731420e7f721.png">

**Comment by jocrl** [comment]
> One question, before we introduced the shared time picker to SQL activity pages, did changing the time picker on the Metrics page also update the time picker on the Node Map page?
Yes, it did. They were correlated before.

**Comment by Annebirzin** [comment]
👍  in that case, it seems like we could keep the time picker correlated across all of those views
