### ISSUE TITLE
Developers can view statements fingerprint statistics over time

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#72130]
This issue tacks the ability for developers to view statement fingerprint statistics over time to help identify trends and periods of abnormal activity.

Figma mockups: https://www.figma.com/file/xdmwvnFQd6KkO9RJ0XLDH0/22.1_SQL-obsrv_query-performance?node-id=3488%3A10430

Jira issue: CRDB-10960

Epic CRDB-13581

**Comment by maryliag** [comment]
Done on https://github.com/cockroachdb/cockroach/pull/82426
