### ISSUE TITLE
Developers can view transaction fingerprint statistics over time

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#72131]
This issue tacks the ability for developers to view transaction fingerprint statistics over time to help identify trends and periods of abnormal activity.

Figma mockups: https://www.figma.com/file/xdmwvnFQd6KkO9RJ0XLDH0/22.1_SQL-obsrv_query-performance?node-id=3869%3A121886

Jira issue: CRDB-10961

**Comment by maryliag** [comment]
Te figma link is pointing to the Statements page, what is the correct mockup for this issue?
cc @Annebirzin

**Comment by Annebirzin** [comment]
@maryliag  I linked the correct screen above in Kevin's comment for Transaction persisted stats
