### ISSUE TITLE
Database drop failed with a dependent object id issue inspite of using Cascade option

### ISSUE THREAD

**Issue by akakana** [cockroachdb/cockroach#72230]
**Describe the problem**

Trying to drop a database to perform restore, the database drop command fails with the dependent object id issue. We are running 21.1.6 on Linux RHEL 8.4 on a VM. It seems to be a common theme.

[Code: , SQL State: 42P01] ERROR: error resolving dependent view ID 7568: relation "[7568]" does not exist

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
2. Send SQL ... / CLI command ...
3. Look at UI / log file / client app ...

**Expected behavior**

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version [e.g. 2.0.x]
 - Server OS: [e.g. Linux/Distrib]
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
What was the impact?

Jira issue: CRDB-11051

**Comment by ajwerner** [comment]
Sorry that you've hit this. Can you provide steps to reproduce this issue?

**Comment by akakana** [comment]
drop database command triggers this

**Comment by ajwerner** [comment]
Was the `DROP DATABASE` run in 21.1 or an older version?

**Comment by ajwerner** [comment]
It's not about the error you're seeing now, it's about how you got into this state. Can you provide steps to get into this state from a fresh cluster?

**Comment by akakana** [comment]
We are running on 21.1.6

**Comment by akakana** [comment]
Step 1) Trying to drop a table (failed)
drop table public.rally_hierarchical_requirement ;
[Code: , SQL State: 42P01]  ERROR: error resolving dependent view ID 1391: relation "[1391]" does not exist

Step 2) Trying to drop the materialized view (failed)
when trying to drop the materialized view it is complaining about the descriptor id 7568, so we tried dropping the database and the same descriptor id is preventing the db drop.
 
We ran this to troubleshoot.
 
select jsonb_pretty(crdb_internal.pb_to_json('cockroach.sql.sqlbase.Descriptor', descriptor)) from system.descriptor where id = 7568;
select jsonb_pretty(crdb_internal.pb_to_json('cockroach.sql.sqlbase.Descriptor', descriptor)) from system.descriptor where id = 1391;

The output is result ‘jsonb_pretty’
 
 
select d.descriptor_name as object, d.dependedonby_id as dependency_id, t.name as dependency from crdb_internal.forward_dependencies d
left join crdb_internal.tables t on t.table_id = d.dependedonby_id
where descriptor_name = 'vload_aha_user_role_product_user_assigned_roles_mat' ;
object                                                                             dependency_id                 dependency
vload_aha_user_role_product_user_assigned_roles_mat              7568                     (null)
vload_aha_user_role_product_user_assigned_roles_mat              7568                     (null)
vload_aha_user_role_product_user_assigned_roles_mat              7604                     (null)
vload_aha_user_role_product_user_assigned_roles_mat              7604                     (null)
vload_aha_user_role_product_user_assigned_roles_mat              7605                     (null)
vload_aha_user_role_product_user_assigned_roles_mat              7605                     (null)
 
 
select d.descriptor_name as object, d.dependedonby_id as dependency_id, t.name as dependency from crdb_internal.forward_dependencies d
left join crdb_internal.tables t on t.table_id = d.dependedonby_id
where descriptor_name = 'rally_hierarchical_requirement'; 
 
object                                     dependency_id    dependency
rally_hierarchical_requirement   1767                vload_agile_successor
rally_hierarchical_requirement   1772                vload_agile_predecessor
rally_hierarchical_requirement   2453                vload_agile_team
rally_hierarchical_requirement   1391                (null)

**Comment by nexdrew** [comment]
I have a similar problem that appears to have been caused by dropping a materialized view - the materialized view was successfully dropped but the associated records in `crdb_internal.forward_dependencies` were not cleaned up. I am running Cockroach v21.1.9.

In my case, I am trying to drop a view (name: a25_cs_deferred_reconciliation, descriptor_id: 11696) that was referenced by the materialized view (name: a01_cs_header, descriptor_id: 11720), but my drop fails like so:

```
root@:26257/api> drop view a25_cs_deferred_reconciliation;
ERROR: error resolving dependent view ID 11720: relation "[11720]" does not exist
SQLSTATE: 42P01
```

and I see these records that still exist in `crdb_internal.forward_dependencies`:

```
root@:26257/api> select * from crdb_internal.forward_dependencies where dependedonby_id = 11720;
  descriptor_id |               descriptor_name               | index_id | dependedonby_id | dependedonby_type | dependedonby_index_id | dependedonby_name |                              dependedonby_details
----------------+---------------------------------------------+----------+-----------------+-------------------+-----------------------+-------------------+----------------------------------------------------------------------------------
             58 | org                                         |     NULL |           11720 | view              |                     0 | NULL              | Columns: [1 21]
             59 | rep                                         |     NULL |           11720 | view              |                     0 | NULL              | Columns: [1 4 10 11]
             64 | fiscal_period                               |     NULL |           11720 | view              |                     0 | NULL              | Columns: [1 5 6 7 14 15]
             65 | comp_report                                 |     NULL |           11720 | view              |                     0 | NULL              | Columns: [1 3 5 6 7 8 11 16]
             67 | ss_address                                  |     NULL |           11720 | view              |                     0 | NULL              | Columns: [1 9 10 11 12 13 15]
             68 | ss_rep                                      |     NULL |           11720 | view              |                     0 | NULL              | Columns: [1 2 3 8 14]
             69 | ss_comp_plan                                |     NULL |           11720 | view              |                     0 | NULL              | Columns: [1 7]
             69 | ss_comp_plan                                |     NULL |           11720 | view              |                     0 | NULL              | Columns: [1 7]
            119 | team                                        |     NULL |           11720 | view              |                     0 | NULL              | Columns: [1 4]
            189 | ss_map_comp_plan_rep                        |     NULL |           11720 | view              |                     0 | NULL              | Columns: [1 2]
            190 | ss_team                                     |     NULL |           11720 | view              |                     0 | NULL              | Columns: [1 3]
            191 | ss_map_comp_plan_team                       |     NULL |           11720 | view              |                     0 | NULL              | Columns: [1 2]
            208 | ss_roster                                   |     NULL |           11720 | view              |                     0 | NULL              | Columns: [5 6]
          11684 | a14_cs_earned_paid_non_def_comm_cr_qtd_ytd  |     NULL |           11720 | view              |                     0 | NULL              | Columns: [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]
          11685 | a17_cs_earned_paid_bonus_cr_qtd_ytd         |     NULL |           11720 | view              |                     0 | NULL              | Columns: [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]
          11690 | a16_cs_earned_deferred_comm_cr_qtd_ytd      |     NULL |           11720 | view              |                     0 | NULL              | Columns: [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]
          11692 | a15_cs_earned_paid_deferred_comm_cr_qtd_ytd |     NULL |           11720 | view              |                     0 | NULL              | Columns: [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]
          11696 | a25_cs_deferred_reconciliation              |     NULL |           11720 | view              |                     0 | NULL              | Columns: [1 2 3 4 5 6 7 8 9 10 11]
          11706 | a18_cs_earned_paid_adj_other_cr_qtd_ytd     |     NULL |           11720 | view              |                     0 | NULL              | Columns: [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]
(19 rows)

Time: 365ms total (execution 364ms / network 1ms)
```

where the first 13 records there represent tables that were referenced by the materialized view, and the last 6 records represent normal views that were referenced by the materialized view.

But my materialized view no longer exists:

```
root@:26257/api> select table_name from [show tables from api] where type = 'materialized view' order by table_name;
                  table_name
----------------------------------------------
  mv_sale_attribution_cust_customer_category
  mv_sale_attribution_prod_product_category
(2 rows)

Time: 518ms total (execution 518ms / network 0ms)
```

```
root@:26257/api> drop materialized view a01_cs_header;
ERROR: relation "a01_cs_header" does not exist
SQLSTATE: 42P01
```

```
root@:26257/api> select * from system.public.descriptor where id = 11720;
  id | descriptor
-----+-------------
(0 rows)

Time: 8ms total (execution 8ms / network 0ms)
```

It appears I am unable to drop any of the 6 views listed in the `crdb_internal.forward_dependencies` query above.

Questions:

1. Is there a way to manually clean up `crdb_internal.forward_dependencies` so I can drop the referenced views?
2. Should the `dependedonby_type` value for materialized views be `view` (as it is) or `materialized view` (as returned from the `show tables` operation)?

**Comment by nexdrew** [comment]
I think it's possible that my problem was caused by first attempting to drop the materialized view using `DROP VIEW a01_cs_header;` (which failed) instead of `DROP MATERIALIZED VIEW a01_cs_header;` (which succeeded).

Attempting to recreate my steps/scenario, I believe I may have avoided the issue (where the materialized view has been dropped but still has references in `crdb_internal.forward_dependencies`) by executing the correct drop statement the first time around.

Still testing.

**Comment by ajwerner** [comment]
@fqazi can I ask you to take a gander at this one Monday? It'd be nice to understand how it happened.

**Comment by fqazi** [comment]
Let me dig into this one

**Comment by fqazi** [comment]
This was address via: https://github.com/cockroachdb/cockroach/issues/82079
