### ISSUE TITLE
ERROR: failed to resolve targets specified in the BACKUP stmt: duplicate table name: "ot_fin"."public"."zz_tco_app_detail_2021" used for ID 2414 and 2413

### ISSUE THREAD

**Issue by akakana** [cockroachdb/cockroach#72250]
**Describe the problem**

Backup fails with the below error on multiple clusters

ERROR: failed to resolve targets specified in the BACKUP stmt: duplicate table name: "ot_fin"."public"."zz_tco_app_detail_2021" used for ID 2414 and 2413

Running on 21.1.6,  
cat /etc/redhat-release
Red Hat Enterprise Linux release 8.4 (Ootpa)
**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
2. Send SQL ... / CLI command ...
3. Look at UI / log file / client app ...

**Expected behavior**

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version [e.g. 2.0.x]
 - Server OS: [e.g. Linux/Distrib]
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
What was the impact?

Jira issue: CRDB-11064

**Comment by dt** [comment]
Hi @akakana, thanks for reporting this!

I'm not sure we can figure out exactly what is going on here without some more information. At the very least, I think we'd need to know the actual BACKUP statement being run (with the destination URI redacted) and then some more info about the table names/mapping in the cluster, specifically, a look at system.namespace (`SELECT * FROM system.namespace WHERE name = 'zz_tco_app_detail_2021'`) and system.descriptor (`SELECT id, to_hex(descriptor) FROM system.descriptor WHERE id = 2414 OR id = 2413`)
