### ISSUE TITLE
Surface cluster setting values in DB Console

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#72302]
**Is your feature request related to a problem? Please describe.**
Currently, for a given cluster the DB Console does not reveal or display its cluster settings. In order to access this information, a user would need to run `SHOW CLUSTER SETTING <setting>;` in SQL. However, surfacing this information in the DB Console would improve the end user's quality of life. 

One example that prompted this: there was an issue where dragging-to-zoom to a tight time window does not switch to more granular readings. Part of the problem is the fact that a user was trying to zoom into a time frame that was beyond the `timeseries.storage.resolution_10s.ttl` value. If that were the case, it would be helpful to have a mechanism by which the DB Console can display/notify to users that old data cannot be displayed with higher resolution and that they should update their cluster setting accordingly. 

**Describe the solution you'd like**
We'd like to achieve that user flow and other similar ones. Based on conversations within the Observability Infrastructure team, one idea was creating an endpoint that would return all the cluster settings and their respective values. The DB Console (and perhaps the Cloud Console) could consume this endpoint and display those settings in a more user-friendly way.

**Comment by thtruo** [comment]
cc @dhartunian @nkodali as discussed

cc @Santamaura @koorosh @Annebirzin @taroface for Cluster UI awareness

**Comment by koorosh** [comment]
fyi. Endpoint for cluster settings is already available in Db Console (`_admin/v1/settings`).
Also Db Console has Cluster Settings page under "Advanced debug" section: `#/reports/settings`.
This data can be reused on metrics page to provide users meaningful info.

**Comment by dhartunian** [comment]
Perfect! Thanks @koorosh
