### ISSUE TITLE
changefeedccl: Cleanup/remove interleave related code

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#72320]
Quoting our docs:
```
INTERLEAVE IN PARENT was deprecated in v20.2, disabled by default in v21.1, and permanently removed in v21.2. We do not recommend interleaving tables or indexes in new clusters.
```

We have few mentions of interleaved tables in changefeed code.  These need to be removed.

**Comment by HonoreDB** [comment]
Do we need logic to fail on legacy interleaved tables or have they all been migrated away by 21.2?

**Comment by miretskiy** [comment]
I don't think you could even start db if you didn't migrate those tables.. I maybe wrong.

**Comment by HonoreDB** [comment]
Done in #72497, a quick grep doesn't see any more references in changefeed code.
