### ISSUE TITLE
logs: generated docs are not accurate when referencing which events go to system.eventlog table

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#72325]
**Describe the problem**

First identified by @fabiog1901: our [docs](https://www.cockroachlabs.com/docs/stable/eventlog.html) mention that `SESSIONS` events will go to the `system.eventlog` table. 

However, that is not accurate. There are inaccuracies in our generated docs around what events go to `system.eventlog`. 

This issue tracks the follow up work to audit / check doc strings with the implementation as suggested by @knz 

Jira issue: CRDB-11096

**Comment by knz** [comment]
cc @dhartunian for triage
