### ISSUE TITLE
Transaction Retry Errors and Memory Budget Exceeded errors.

### ISSUE THREAD

**Issue by akakana** [cockroachdb/cockroach#72354]
**Describe the problem**

The primary issue has to do with a high volume of transaction errors we are getting when interacting with our cluster. They are occurring on INSERT statements but are not limited to them as we have also seen them in access grant/revoke statements. The errors are primarily of the type ABORT_REASON_ABORT_SPAN but we have seen others. 

In addition, we have certain queries that are getting hit with a “Memory Budget Exceeded” error 

We are running 21.1.6 on RHEL 8.4 
[logs-from-fin-dsql-migrate-in-fin-dsql-migrate-749b0b43-8d5f-48ee-98c2-ba272eedc049-dlcq5.log](https://github.com/cockroachdb/cockroach/files/7464050/logs-from-fin-dsql-migrate-in-fin-dsql-migrate-749b0b43-8d5f-48ee-98c2-ba272eedc049-dlcq5.log)
[logs-from-fin-mpwr-in-fin-mpwr-249deb11-079b-4867-bbc0-6f05f15eca47-ns86x.log](https://github.com/cockroachdb/cockroach/files/7464051/logs-from-fin-mpwr-in-fin-mpwr-249deb11-079b-4867-bbc0-6f05f15eca47-ns86x.log)
[logs-from-fin-tco-in-fin-tco-269f9330-f109-46e0-899a-68e8f78007a1-b2695.log](https://github.com/cockroachdb/cockroach/files/7464052/logs-from-fin-tco-in-fin-tco-269f9330-f109-46e0-899a-68e8f78007a1-b2695.log)
[logs-from-fin-tco-in-fin-tco-269f9330-f109-46e0-899a-68e8f78007a1-mqjld.log](https://github.com/cockroachdb/cockroach/files/7464053/logs-from-fin-tco-in-fin-tco-269f9330-f109-46e0-899a-68e8f78007a1-mqjld.log)

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
2. Send SQL ... / CLI command ...
3. Look at UI / log file / client app ...

**Expected behavior**

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version [e.g. 2.0.x]
 - Server OS: [e.g. Linux/Distrib]
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
What was the impact?

**Comment by jordanlewis** [comment]
This is not a bug. Your app has to handle these errors: https://www.cockroachlabs.com/docs/stable/transaction-retry-error-reference.html
