### ISSUE TITLE
Support simpler noSql interface?

### ISSUE THREAD

**Issue by bronze1man** [cockroachdb/cockroach#7237]
I want simpler NoSql database interface like redis.
I know I can work around this problem with kv table,json,lazy create db/table.
Using postgres publish/subscribe model.
But I think this kind of useless layer can waste some cpu time.

**Comment by petermattis** [comment]
See my comment to `bronze2man` (which I assume is you) on the mailing list: https://groups.google.com/d/msg/cockroach-db/WHsuUWDuwmI/pAy3PyNoBQAJ. I agree that SQL is often not the correct API for applications. Lots of other developers share that sentiment. I'm hoping an ORM library will address your concerns. 

PS An engineer experiment with providing a redis frontend to cockroach: https://www.cockroachlabs.com/blog/could-cockroachdb-ever-replace-redis-a-free-fridays-experiment/. We're unlikely to support this any time soon, though.
