### ISSUE TITLE
kv: redirect on server-side when possible on RangeKeyMismatchError

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#72400]
**Motivation: reduce the disruption of range splits on foreground traffic.**

When a `BatchRequest` is directed at the wrong range, often after a Range split, a `RangeKeyMismatchError` is returned. Currently, this `RangeKeyMismatchError` will always be bubbled back up to the `DistSender`, often with a set of updated `RangeDescriptors`. The `DistSender` will push these updated descriptors into its `RangeCache` and reissue the request to the correct range.

The "suggestions" attached to a `RangeKeyMismatchError` avoid the need to hit the meta ranges before retrying. However, they don't avoid the need to perform the KV RPC hop twice. This is suboptimal in the common case where a Range split but its RHS has not yet been rebalanced away. In that case, the RHS Range will still be sitting right next to the LHS Range. So there's no need to bubble the error back to the DistSender just to retry. Instead, the Store could just redirect the BatchRequest to the RHS itself.

We will still want to pass back the updated descriptors to the client's DistSender so that it eventually gets out of this state, but this can be done through the `BatchResponse_Header.RangeInfos` field.

### Timeline

Before (2 network RTTs):
```
1. range 10:[a,z) on node 2 splits into 10:[a,m) and 11:[m, z)
2. client on node 1 with outdated RangeCache issues Get("q") to node 2, range 10 **network hop**
3. range 10 rejects request with RangeKeyMismatchError{suggestions: [10:[a,m), 11:[m, z)]}}
4. RangeKeyMismatchError is returned back to node 1 **network hop**
5. client on node 1 updates RangeCache
6. client on node 1 issues Get("q") to node 2, range 11 **network hop**
7. range 11 evaluates Get
8. Get response is returned back to node 1 **network hop**
```

After (1 network RTT):
```
1. range 10:[a,z) on node 2 splits into 10:[a,m) and 11:[m, z)
2. client on node 1 with outdated RangeCache issues Get("q") to node 2, range 10 **network hop**
3. range 10 rejects request with RangeKeyMismatchError{suggestions: [10:[a,m), 11:[m, z)]}}
4. RangeKeyMismatchError is intercepted by Store, which notices that range 11 is also local
5. Store redirects request to range 11
6. range 11 evaluates Get
7. Get response is augmented with RangeInfo updates
8. Get response is returned back to node 1 **network hop**
9. client on node 1 updates RangeCache
```

**Comment by ajwerner** [comment]
Would we ever consider having the `Store` split the request and then merge the results? Like imagine in your first example that there were `Get("b"), Get("q")` or, perhaps, `Scan("a", "z")`. Certainly not for the first stab, but curious if we think there's value at all.

**Comment by nvanbenschoten** [comment]
That's a neat idea. Splitting a request on the store and merging its partial results back together seems like a reasonable follow-up to this issue, as it's consistent with the approach we are taking here.

That said, it feels like a request that spans keys and therefore always has the chance of spanning ranges (and will continue to after the client-side caches are updated) falls into a different performance class than a point lookup which is guaranteed to always be served from one range. For various reasons, I don't think there's as much of an expectation that ranged operations which span SQL rows (we don't split between rows) have as tight of a latency tail. Or at least, CRDB doesn't do as good of a job living up to such an expectation due to various internal fanout concurrency limits and pagination schemes. So I think there's value there, but that value's probably more marginal than what the original proposal here provides.
