### ISSUE TITLE
opt: allow number of histogram buckets collected for indexed columns to be configured

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#72418]
The issue described in https://github.com/cockroachdb/cockroach/issues/71828 could be mitigated by collecting more than 200 histogram buckets. By collecting more histogram buckets, we are more likely to have an even distribution of values within the histogram bucket range. We could add a setting (ideally per-table or per-column) for configuring the number of histogram buckets collected. However, this would likely be a temporary mitigation for https://github.com/cockroachdb/cockroach/issues/71828 because even with more histogram buckets, it'd still be possible that histogram upper bound values are not heavy-hitters and the range of values within buckets is no evenly distributed.

Jira issue: CRDB-11140

**Comment by RaduBerinde** [comment]
This depends on a system for making stats configuration per-table.
