### ISSUE TITLE
Not retrying transactions

### ISSUE THREAD

**Issue by akakana** [cockroachdb/cockroach#72414]
gavin colewell took a moment to assess  sqlalchemy-cockroach db package, came back with this:
https://github.com/cockroachdb/sqlalchemy-cockroachdb/blob/390255921331d129f9fb24fe5bedbfa8382c1d2b/sqlalchemy_cockroachdb/transaction.py#L111
sqlalchemy-cockroachdb/transaction.py at 390255921331d129f9fb24fe5bedbfa8382c1d2b · cockroachdb/sqlalchemy-cockroachdb

the exception name doesn't appear to be found in psycopghttps://www.psycopg.org/docs/errors.html
psycopg2.errors – Exception classes mapping PostgreSQL errors — Psycopg 2.9.1 documentation
so we may not be entering retry at all

**Comment by rafiss** [comment]
Hello! The relevant error is on the page https://www.psycopg.org/docs/errors.html under the name SerializationFailure (40001).

Are you able to reproduce a bug with this logic?

**Comment by rafiss** [comment]
I'll close this, but let me know if you are still having a problem.
