### ISSUE TITLE
sql: include all session settings in statement bundle env.sql

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#72434]
We should include all session settings in the statement bundle so that we do not lack any information when debugging customer issues. If there are reasons why including all is problematic, we could consider including all session settings that do not have default values.

See the TODO here: https://github.com/cockroachdb/cockroach/blob/87f79da6ab14a27b6f4faa9e9a47bc88671686f7/pkg/sql/explain_bundle.go#L522-L523

Jira issue: CRDB-11151

Epic CRDB-14510

**Comment by yuzefovich** [comment]
This is a dup of #123830 and has already been fixed by #123794
