### ISSUE TITLE
sql: goroutines seemingly not cancelling

### ISSUE THREAD

**Issue by cucaroach** [cockroachdb/cockroach#72445]
In CRL issue https://github.com/cockroachlabs/support/issues/1314 we see some goroutines running that have no associated query.    A debug.zip can be found there but the highlights are below.    Logging this bug in case we see more issues like this and for a place to put notes.

<h1 style="font-family: Times; font-size: 1.4em; margin: 0.8em 0px 0.2em; padding: 0px; box-sizing: inherit; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Signature #74: 1 routine:<span> </span><span class="state" style="font-family: inherit; font-size: 1em; margin: 0px; padding: 0px; box-sizing: inherit;">runnable</span></h1><span class="created" style="font-family: Times; font-size: 16px; margin: 0px; padding: 0px; box-sizing: inherit; white-space: nowrap; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Created by:<span> </span><span class="call hastooltip" style="font-family: monospace; font-size: 1em; margin: 0px; padding: 0px; box-sizing: inherit;"><a href="https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/colflow/vectorized_flow.go#L1321" style="font-family: inherit; font-size: 1em; margin: 0px; padding: 0px; box-sizing: inherit; color: inherit; text-decoration: inherit;">vectorized_flow.go:1321</a><span> </span><span class="FuncGOPATH" style="font-family: inherit; font-size: 1em; margin: 0px; padding: 0px; box-sizing: inherit; color: rgb(16, 144, 144);"><a href="https://godoc.org/github.com/cockroachdb/cockroach/pkg/sql/colflow" style="font-family: inherit; font-size: 1em; margin: 0px; padding: 0px; box-sizing: inherit; color: inherit; text-decoration: inherit;">colflow.(*vectorizedFlowCreatorHelper).accumulateAsyncComponent.func1</a></span>()</span></span>

0 | rowcontainer | hash_row_container.go:610 | (*hashDiskRowBucketIterator).Row(*hashDiskRowBucketIterator(#1764), 0x0, 0x0, 0x0, #1829, 0x3)
-- | -- | -- | --
1 | rowexec | hashjoiner.go:331 | (*hashJoiner).probeRow(*hashJoiner(#2422), 0x0, 0x0, 0x0, 0x0, 0x0)
2 | rowexec | hashjoiner.go:179 | (*hashJoiner).Next(*hashJoiner(#2422), 0x1, 0x0, 0x0, #2108)
3 | colexec | columnarizer.go:199 | (*Columnarizer).Next(*Columnarizer(#734), #139, #2268, #2806, #1916)
4 | colflow | stats.go:86 | (*batchInfoCollector).Next(Operator(#1853), ComponentID(#2268), *StopWatch(0x0))
5 | colexechash | hashtable.go:362 | (*HashTable).FullBuild(*HashTable(#2040), Operator(#139), #2770, #1853)
6 | colexecjoin | hashjoiner.go:319 | (*hashJoiner).build(*hashJoiner(#1778), #139, #2268)
7 | colexecjoin | hashjoiner.go:281 | (*hashJoiner).Next(*hashJoiner(#1778), #139, #2268, #76, 0x2)
8 | colexec | disk_spiller.go:201 | (*diskSpillerBase).Next.func1()
9 | colexecerror | error.go:91 | CatchVectorizedRuntimeError(func(#1917), 0x0)
10 | colexec | disk_spiller.go:199 | (*diskSpillerBase).Next(*diskSpillerBase(#2241), #139, #2268, #2826, #2676)
11 | colexecbase | simple_project.go:124 | (*simpleProjectOp).Next(Operator(#1931), 825022967832, []uint32(0x0 len=43346110 cap=0))
12 | colexec | limit.go:53 | (*limitOp).Next(*limitOp(#2429), #139, #2268, #2507, #1918)
13 | colflow | stats.go:86 | (*batchInfoCollector).Next(Operator(#1854), ComponentID(#2268), *StopWatch(0x0))
14 | colexecutils | deselector.go:68 | (*deselectorOp).Next(*deselectorOp(#1932), #139, #2268, #166, #90)
15 | colrpc | outbox.go:283 | (*Outbox).sendBatches.func1()
16 | colexecerror | error.go:91 | CatchVectorizedRuntimeError(func(#1919), 0x0)
17 | colrpc | outbox.go:275 | (*Outbox).sendBatches(*Outbox(#2403), Context(#5), flowStreamClient(#2799), CancelFunc(#725), CancelFunc(#2498), #1443)
18 | colrpc | outbox.go:403 | (*Outbox).runWithStream(*Outbox(#2403), Context(#5), flowStreamClient(#2799), CancelFunc(#725))
19 | colrpc | outbox.go:215 | (*Outbox).Run(*Outbox(#2403), Context(#134), Dialer(#115), NodeID(#2835), FlowID(#2837), StreamID(#725), …)
20 | colflow | vectorized_flow.go:660 | (*vectorizedFlowCreator).setupRemoteOutputStream.func1(*vectorizedFlowCreator(#134), #2139, #725)
21 | colflow | vectorized_flow.go:1322 | (*vectorizedFlowCreatorHelper).accumulateAsyncComponent.func1.1(*vectorizedFlowCreatorHelper(#2430), StreamID(#134), #725, #1818)

<br class="Apple-interchange-newline">

<h1 style="font-family: Times; font-size: 1.4em; margin: 0.8em 0px 0.2em; padding: 0px; box-sizing: inherit; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Signature #78: 3 routines:<span> </span><span class="state" style="font-family: inherit; font-size: 1em; margin: 0px; padding: 0px; box-sizing: inherit;">select</span><span> </span><span class="sleep" style="font-family: inherit; font-size: 1em; margin: 0px; padding: 0px; box-sizing: inherit;">[11660~12293 mins]</span></h1><span class="created" style="font-family: Times; font-size: 16px; margin: 0px; padding: 0px; box-sizing: inherit; white-space: nowrap; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Created by:<span> </span><span class="call hastooltip" style="font-family: monospace; font-size: 1em; margin: 0px; padding: 0px; box-sizing: inherit;"><a href="file:////Users/tpr/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go" style="font-family: inherit; font-size: 1em; margin: 0px; padding: 0px; box-sizing: inherit; color: inherit; text-decoration: inherit;">server.go:744</a><span> </span><span class="FuncGOPATH" style="font-family: inherit; font-size: 1em; margin: 0px; padding: 0px; box-sizing: inherit; color: rgb(16, 144, 144);"><a href="https://godoc.org/google.golang.org/grpc" style="font-family: inherit; font-size: 1em; margin: 0px; padding: 0px; box-sizing: inherit; color: inherit; text-decoration: inherit;">grpc.(*Server).serveStreams.func1</a></span>()</span></span>

0 | colrpc | inbox.go:250 | (*Inbox).RunWithStream(*, #5, *, #2800, *, 0, 0)
-- | -- | -- | --
1 | colflow | vectorized_flow.go:1271 | vectorizedInboundStreamHandler.Run(*, #5, *, #152, *, *, *, *, 2)
2 | distsql | server.go:633 | (*ServerImpl).flowStreamInt(#436, #5, *, #152, *, 0, 0)
3 | distsql | server.go:639 | (*ServerImpl).FlowStream(#436, #152, *, #138, #436)
4 | execinfrapb | api.pb.go:601 | _DistSQL_FlowStream_Handler(#92, #436, #141, *, 0x2c, *)
5 | tracing | grpc_interceptor.go:183 | StreamServerInterceptor.func1(#92, #436, #142, *, *, #101, 0, 0)
6 | grpc | server.go:1204 | getChainStreamHandler.func1(#92, #436, #142, *, #77, *)
7 | rpc | context.go:184 | NewServer.func2(#92, #436, #142, *, *, *, *, 1)
8 | grpc | server.go:1204 | getChainStreamHandler.func1(#92, #436, #142, *, 0, 0)
9 | rpc | auth.go:86 | kvAuth.streamInterceptor(#92, #436, #142, *, *, *, #77, *)
10 | grpc | server.go:1190 | chainStreamServerInterceptors.func1(#92, #436, #142, *, *, #101, #5, *)
11 | grpc | server.go:1336 | (*Server).processStreamingRPC(#7, #6, *, *, #450, #159, 0, 0, 0)
12 | grpc | server.go:1409 | (*Server).handleStream(#7, #6, *, *, 0)
13 | grpc | server.go:746 | (*Server).serveStreams.func1.1(*, #7, #6, *, *)

<br class="Apple-interchange-newline">

**Comment by yuzefovich** [comment]
I'm optimistically assuming that #73887 fixes this problem since here it looks like there was a problem with a distributed query cleanup when the vectorized engine is used and the query already left the gateway node (was completed or canceled).
