### ISSUE TITLE
sql: improve schema changes in testing setups

### ISSUE THREAD

**Issue by postamar** [cockroachdb/cockroach#72447]
Third-party tool test suites take significantly longer to run on CockroachDB compared to Postgres, hours compared to minutes. We've noticed in Active Record, Prisma, and TypeORM that frequent schema creation and changes contribute to test slowness. 

This issue is created retroactively on behalf of @ajwerner to reference PRs related to this work:
https://github.com/cockroachdb/cockroach/pull/71910
https://github.com/cockroachdb/cockroach/pull/71899
https://github.com/cockroachdb/cockroach/pull/71909
https://github.com/cockroachdb/cockroach/pull/72297

Epic CRDB-10719

**Comment by otan** [comment]
hmm, was this completed / everything merged into master?

**Comment by postamar** [comment]
It doesn't seem that this is the case. Evidently I seem to have thought otherwise when I created the issue, but I can't remember why now. Strange. I'll reopen. cc @ajwerner

**Comment by ajwerner** [comment]
Confirmed that this works on master and prisma-engines `main`.
