### ISSUE TITLE
sql: ALTER COLUMN TYPE does not check partial index definitions

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#72456]
**Describe the problem**

If a partial index constraint references a column whose type is changed, it can make it impossible to insert data.

**To Reproduce**
```
set use_declarative_schema_changer = off; 

root@:26257/defaultdb> set enable_experimental_alter_column_type_general='true';

root@:26257/defaultdb> create table a (a int primary key, b text, c text);

root@:26257/defaultdb> create index idx on a(c) where b = 'cat';

root@:26257/defaultdb> alter table a alter column b set data type timestamp  using a::timestamp;

root@:26257/defaultdb> insert into a values (1,now(),'abc');
ERROR: unsupported comparison operator: <timestamp> = <string>
SQLSTATE: 22023
```

**Expected behavior**
The ALTER should be prevented, like how postgres does:

```
postgres=# create table a (a int primary key, b text, c text);
CREATE TABLE

postgres=# create index idx on a(c) where b = 'cat';
CREATE INDEX

postgres=# alter table a alter column b set data type timestamp using b::timestamp;
ERROR:  operator does not exist: timestamp without time zone = text
```

Jira issue: CRDB-11164
Epic CRDB-25314

**Comment by rafiss** [comment]
I put this on both Experience and Schema boards since this is another one of those boundary problems. Given that SQl-E worked on ALTER COLUMN TYPE and took https://github.com/cockroachdb/cockroach/issues/70605 we could take this too. Curious to hear thoughts

**Comment by postamar** [comment]
This is one of these things which will be easy to check in the declarative schema changer. I recommend holding off doing anything until we implement ALTER COLUMN TYPE in it, which should be early in the 22.2 release cycle.

**Comment by spilchen** [comment]
This is correctly blocked in the declarative schema changer. However, the legacy schema changer still allows the alter.
