### ISSUE TITLE
log: introduce more metrics into log pkg for network logging

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#72453]
This is follow up work to #70330.

Since https://github.com/cockroachdb/cockroach/pull/106607, we now have the ability to add metrics to the log package.

While the original PR adds a metric to track fluentbit connection errors, we should add additional metrics such as:

1. When the output buffer becomes full, the new buffer sink implementation chooses to drop messages instead of blocking the log call (this is a feature). Count these.
2. Count of log messages flowing through the log package.
3. Error counts
4. ???

Use the new infra to add useful new metrics to `pkg/util/log`, with a focus on improving observability around network logging.

Jira issue: CRDB-11161

**Comment by joshimhoff** [comment]
This is great!

CC is going to release some features soon which increase our need for highly reliable logging. For example, we will release a feature that ships CRDB logs to customers directly.

I bet this is a pretty small work item. If no DB eng time for it, I think we could have an SRE do it too. Do we plan to execute on this item soon?

**Comment by abarganier** [comment]
This was a bit tricky to get set up originally due to dependency cycles, but as of https://github.com/cockroachdb/cockroach/pull/106607, this should be much easier to do!
