### ISSUE TITLE
sql: add directives to logictest for mixed version cluster tests

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#72451]
Currently we have limited support for testing mixed version cluster tests using logictests.

We have a config to support testing version gates via logic tests but not actually functionality.

```
	{
		name:                "local-mixed-21.1-21.2",
		numNodes:            1,
		overrideDistSQLMode: "off",
		overrideAutoStats:   "false",
		bootstrapVersion:    roachpb.Version{Major: 21, Minor: 1},
		binaryVersion:       roachpb.Version{Major: 21, Minor: 2},
		disableUpgrade:      true,
	},
```

Ensuring mixed version functionality actually works is very tedious as we currently have to make a roachtest for example:
https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/tests/schema_change_database_version_upgrade.go
The problem is creating a roachtest is not straightforward and takes a while to run.

Ideally we could support some logic test directives to make writing mixed version tests easier.

For example, we could specify which nodes are on which versions - then execute commands from a specified node.
We could improve on that by adding support for updating / rolling back nodes.

Ideally we could make testing mixed version clusters very easy.

Might be a good hackathon project.

Potentially support commands to upgrade / downgrade

Mentioned in https://github.com/cockroachdb/cockroach/issues/69361
```
new-cluster
should-error-with-version
should-succeed
upgrade-cluster
```

Jira issue: CRDB-11159

Epic CRDB-14557

**Comment by rafiss** [comment]
This seems like https://github.com/cockroachdb/cockroach/issues/69361
