### ISSUE TITLE
sql: ALTER COLUMN TYPE does not check computed column definitions

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#72457]
**Describe the problem**

If a computed column definition references a column whose type is changed, it can make it impossible to insert data.

**To Reproduce**

```
root@:26257/defaultdb> set enable_experimental_alter_column_type_general='true';

root@:26257/defaultdb> create table a (a int primary key, b text, c int as (length(b)) stored);

root@:26257/defaultdb> alter table a alter column b set data type int;

root@:26257/defaultdb> insert into a values (1,1);
ERROR: unknown signature: length(int) (desired <int>)
SQLSTATE: 42883
```

**Expected behavior**
The ALTER should error, like what Postgres does:
```
postgres=# create table a (a int primary key, b text, c int generated always as (length(b)) stored);
CREATE TABLE

postgres=# alter table a alter column b set data type int using b::integer;
ERROR:  cannot alter type of a column used by a generated column
DETAIL:  Column "b" is used by generated column "c".
```

Jira issue: CRDB-11165
Epic CRDB-25314

**Comment by rafiss** [comment]
I put this on both Experience and Schema boards since this is another one of those boundary problems. Given that SQl-E worked on ALTER COLUMN TYPE and took https://github.com/cockroachdb/cockroach/issues/70605 we could take this too. Curious to hear thoughts

**Comment by ajwerner** [comment]
> I put this on both Experience and Schema boards since this is another one of those boundary problems. Given that SQl-E worked on ALTER COLUMN TYPE and took #70605 we could take this too. Curious to hear thoughts

No complaints from me on that. Thanks!

**Comment by postamar** [comment]
Implementing ALTER COLUMN TYPE in the declarative schema changer will help here, which we tentatively plan to do in the first half of the 22.2 release cycle. We're going to have to track column back-references in the declarative schema changer anyway to support DROP COLUMN, which we'll want to support in turn for ADD COLUMN.
