### ISSUE TITLE
systemschema: add tests that "freeze" the system schema

### ISSUE THREAD

**Issue by postamar** [cockroachdb/cockroach#72462]
Currently, it's too easy to make changes to the system table definitions in `systemschema` and not accompany these changes with a tenant migration when these changes are not backward-compatible.

The reason for this is ultimately a lack of tests that test clusters in a mixed-version state using real binaries. We have "mixed version" logic tests but they all bootstrap in the same way.

In the meantime, we could add a test that checks that a bootstrapped catalog is in the expected state, with a cute error message advising that rewriting the expected state should be conditional to adding a migration.

Jira issue: CRDB-11170

**Comment by ajwerner** [comment]
I'll argue this should go even a bit further, and we should classify versions of system tables with clusterversion keys.

**Comment by ajwerner** [comment]
We should maybe even go further and write the `roachpb.ClusterVersion` into descriptors when we modify them. Perhaps both the binary and active cluster version.

**Comment by postamar** [comment]
Let's start by making a very simple data-driven test which starts a test cluster (this will bootstrap a system schema) and compares the output of `USE system; SHOW CREATE ALL TABLES;` with the expected contents of in a file.

Once there's that, let's look into doing something similar in a roachtest. Perhaps we can bootstrap a cluster using the previous release's binary, upgrade it, then run `SHOW CREATE ALL TABLES` on the system database and compare the output to the same text file. It should match then.
