### ISSUE TITLE
log: simplify the buffering count for `flusherCh` in `bufferSink`

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#72460]
This is follow up work to #70330.

The current `bufferSink` flusher uses a manually maintained atomic counter `nInFlight` to track the number of messages buffered.
This could be advantageously simplified by a native buffered Go channel, with a `select` on blocked writes to check when the channel is full.

Jira issue: CRDB-11168

**Comment by knz** [comment]
NB: this issue can be superseded by #72458 if we choose to unify the flushing logic under the existing global goroutine.

**Comment by abarganier** [comment]
https://github.com/cockroachdb/cockroach/pull/82380 contains a rewrite of the buffered log sink. The new implementation no longer contains the atomic `nInFlight` counter, so this is no longer an issue.

Closing as a result.
