### ISSUE TITLE
Support OAuth Authentication for SQL users.

### ISSUE THREAD

**Issue by data-matt** [cockroachdb/cockroach#72509]
**Is your feature request related to a problem? Please describe.**
Currently our users can authenticate via Kerberos. However, moving forward there is a mandate for all workloads to use short lived based token authentication. We would like our SQL to be able to authenticate via OAuth.

**Describe the solution you'd like**
Provide the ability for all sql users to be able to authenticate via OAuth.

**Describe alternatives you've considered**
Kerberos/Certificate authN.

**Additional context**
Our cloud users will require OAuth authentication. 

gz#10432

Jira issue: CRDB-11185

**Comment by data-matt** [comment]
Opening this, there is no comment.

**Comment by data-matt** [comment]
Open

**Comment by data-matt** [comment]
@abhinavg6 , why was this closed? Am I missing something?

**Comment by abhinavg6** [comment]
I actually closed it as duplicate because we are tracking the whole SSO work separately internally. But I guess it's ok to keep this open for just CRDB.
