### ISSUE TITLE
Inverted Index is slower than no index at all

### ISSUE THREAD

**Issue by smcvey** [cockroachdb/cockroach#72500]
**Describe the problem**

I was following a JSONB tutorial from Cockroach's YouTube channel.  After adding an inverted index on a JSONB row, performance on SELECT queries got worse.

**To Reproduce**

Create a table and populate it with 400,000 rows of JSON:

```
create table example (
	id uuid primary key default gen_random_uuid(),
	j jsonb
);

insert into example
(j)
select '{"height": 324, "name": "Eiffel Tower", "features": ["Lifts", "Observation tower", "French people"]}'
from generate_series(1, 100000);

insert into example
(j)
select '{"height": 93, "name": "The Statue of Liberty", "features": ["Torch", "Book", "Ghostbusters"]}'
from generate_series(1, 100000);

insert into example
(j)
select '{"height": 27, "name": "London Tower", "features": ["Torture", "Crown Jewels", "Doctor Who"]}'
from generate_series(1, 100000);

insert into example
(j)
select '{"height": 1.63, "name": "Betty White", "features": ["Acting", "Comedy", "Legend"]}'
from generate_series(1, 100000);
```

Let it settle, create statistics etc....

Now run a SELECT with a CONTAINS operator:

```
select * from example where j @> '{"features": ["Torture", "Crown Jewels", "Doctor Who"]}';
```

On my test locally and on serverless, this took around 1-3 seconds to return results.  The EXPLAIN looks like this:

```
                                           info
------------------------------------------------------------------------------------------
  distribution: full
  vectorized: true

  • filter
  │ estimated row count: 549
  │ filter: j @> '{"features": ["Torture", "Crown Jewels", "Doctor Who"]}'
  │
  └── • scan
        estimated row count: 400,000 (100% of the table; stats collected 42 seconds ago)
        table: example@primary
        spans: FULL SCAN
```

Now I create an inverted index...

```
create inverted index on example(j);
```

Again, superstitiously, I let it settle, generate new statistics etc...  Now I run the same SELECT as before:

```
select * from example where j @> '{"features": ["Torture", "Crown Jewels", "Doctor Who"]}';
```

Now the time to return results ranges from around 12 seconds (locally) to over 70 seconds on Serverless.

The EXPLAIN looks like this:

```
                                   info
--------------------------------------------------------------------------
  distribution: full
  vectorized: true

  • lookup join
  │ estimated row count: 549
  │ table: example@primary
  │ equality: (id) = (id)
  │ equality cols are key
  │ pred: j @> '{"features": ["Torture", "Crown Jewels", "Doctor Who"]}'
  │
  └── • zigzag join
        estimated row count: 4,938
        left table: example@example_j_idx
        left columns: (id)
        left fixed values: 1 column
        right table: example@example_j_idx
        right columns: ()
        right fixed values: 1 column
```

**Environment:**
 - CockroachDB version: 21.1.11
 - Server OS: Linux VM locally and also CockroachDB Serverless
 - Client app: `cockroach sql`

**Additional context**
Queries take an order of magnuitude longer.

Jira issue: CRDB-11183

**Comment by mgartner** [comment]
The filter selects 25% of the table, so I'm not surprised that the full table scan is faster, especially when the plan that uses the inverted index includes a lookup join. It does look like our estimated row counts are wildly inaccurate though, and I suspect that's the reason that the optimizer picks the zigzag join with the inverted index instead of a full table scan.

**Comment by mgartner** [comment]
We are disabling zig-zag joins by default due to their generally poor performance, see #110214. I think that addresses my previous comment, so I'll close this.
