### ISSUE TITLE
multitenant: unable to start secondary tenant pod with single node cluster

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#72518]
**Describe the problem**

When looking to start a single node cluster with a secondary tenant, I'm running into the following error:
```
ERROR: could not cleanup temporary directories from record file: could not lock temporary directory /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach/cockroach-data/cockroach-temp699668176, may still be in use: resource temporarily unavailable
Failed running "mt start-sql"
```

It goes away when `rm -rf`-ing the directory; are we forgetting to clean up somewhere? I think it was previously seen in https://github.com/cockroachdb/cockroach/issues/71269#issuecomment-937945362.

**To Reproduce**

```
# start the host tenant
make buildshort; rm -rf cockroach-data; cockroachshort start-single-node --insecure --logtostderr=INFO --accept-sql-without-tls

# create the tenant
cockroach sql --insecure -e 'select crdb_internal.create_tenant(123);'

# start the tenant pod
rm -rf logs; cockroachshort mt start-sql --insecure --tenant-id 123 --http-addr 127.0.0.1:8081 --kv-addrs 127.0.0.1:26257 --sql-addr 127.0.0.1:36257 --log-dir=logs/mt-123 --logtostderr=INFO
```

**Comment by stevendanna** [comment]
I think perhaps this is more of a server issue.  The same error happens anytime you try to share a store.  It might be a little more confusing in the mt case since one might not realize that a store is even used, but both cases could probably benefit from a clearer error message.

**Comment by irfansharif** [comment]
(Lazily) I haven't looked, but I'm surprised a store is needed -- that wasn't always true. A better error message would help, though probably the script I cribbed my commands from had gone stale.

**Comment by stevendanna** [comment]
> that wasn't always true

Interesting! Looks like it was indeed made true rather recently when we started supporting disk spilling for tenants: https://github.com/cockroachdb/cockroach/commit/af5a5a5065c

**Comment by irfansharif** [comment]
Then I think it's worth using something other than `cockroach-data` as the default store path for SQL pods. Something suffixed with the tenant ID perhaps?

**Comment by aliher1911** [comment]
Digging into this, I can see that it fundamentally relies on how we populate config defaults in absence of `--store` flag. Defaults are created on the module level and then either overridden by flag or not but initialization code in sql pod or full node is unaware and doesn't try to do something smart about it and is unaware if it uses default option or something explicitly provided.
To make it work with per tenant "store" it has to be deferred to the point where we actually initialize the store from config or something in this lines.

**Comment by tbg** [comment]
FYI this also caused problems in roachtest, I had to be explicit in the test: https://github.com/cockroachdb/cockroach/pull/71604#issue-1027243841

I thought back then too that it would've been nicer not to chose colliding defaults, i.e. default to `cockroach-data-<tenid>`.

**Comment by aliher1911** [comment]
Looks like using something in line with [cli/flags.go:extraServerFlagInit](https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/flags.go#L1086) which runs as a post parse/pre exec hook would be in line with the rest of code. It could check if flag was changed and act accordingly.
