### ISSUE TITLE
storage: optimize `UpdateSSTTimestamps()`

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#72528]
In #72085, we added `storage.UpdateSSTTimestamps()` which is used to rewrite ingested SST MVCC timestamps to the request timestamp in order to comply with the timestamp cache and closed timestamp. However, this is a very slow implementation, which needs optimization.

This optimization should probably be done in Pebble, to take advantage of its internal data structures. For example, the rewrite could process blocks in parallel, and simply copy the Bloom filters and value checksums without recomputation as these do not depend on the MVCC timestamp.

Epic CRDB-2624

**Comment by jbowens** [comment]
I'm curious to see a cpu profile from this rewriting. If compression dominates, maybe cockroachdb/pebble#599 (which @bananabrick is working on) would be enough here. It would be nice to avoid writing a one-off sstable rewrite facility specially tailored to this specific use case if we can avoid it. We might not be able to avoid it though.

**Comment by erikgrinaker** [comment]
Here's a profile: [profile.pprof.gz](https://github.com/cockroachdb/cockroach/files/7499853/profile.pprof.gz)

Compression is about 15% (and decompression 5%) -- not insignificant, but I'm hoping we can get the latency down by an order of magnitude.

<img width="1426" alt="Screenshot 2021-11-08 at 21 15 58" src="https://user-images.githubusercontent.com/644420/140811847-dcde1a3c-1cb0-4e1b-b6ab-1b24278d6776.png">

**Comment by erikgrinaker** [comment]
Resolved by #76074.
