### ISSUE TITLE
cockroach demo port changes to a different port each time

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#72544]
Previously, running `cockroach demo` would always use port `26257`, now it uses a different port each time.

Intrusion/console (used for CC Console development) checks `localhost:26257`, but since a different port is used on demo, the intrusion/console fails to run.

**Comment by otan** [comment]
hmm, `--multitenant=false` would resolve this in the interim term.

i'm not sure what we'd want the default port range for `demo`, but maybe it'd make sense for tenants to start at port 26257?
