### ISSUE TITLE
multitenant: crdb_internal.ranges and crdb_internal.ranges_no_leases return RangeInterator errors rather than unimplemented errors

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#72565]
Other crdb_internal functions and tables that don't support tenants return an unimplemented error that mentions the feature is not supported in multi-tenant mode.  `crdb_internal.ranges` and `crdb_internal.ranges_no_leases`, return the following errors:

```
demo@127.0.0.1:58035/movr> select * from crdb_internal.ranges;
ERROR: RangeIterator failed to seek to /Meta2/"\x00": rpc error: code = Unauthenticated desc = requested key /Meta2/"\x00" not fully contained in tenant keyspace /Tenant/{2-3}
demo@127.0.0.1:58035/movr> select * from crdb_internal.ranges_no_leases;
ERROR: RangeIterator failed to seek to /Meta2/"\x00": rpc error: code = Unauthenticated desc = requested key /Meta2/"\x00" not fully contained in tenant keyspace /Tenant/{2-3}
```

Epic CRDB-23344
Jira issue: CRDB-11212

**Comment by otan** [comment]
I wonder if this should show:
a) unimplemented error
b) all ranges that belong to the tenant

**Comment by otan** [comment]
i take it back, this seems intentional:

https://github.com/cockroachdb/cockroach/blob/e800d749e5384d52b008029fdc26ce89bff97db9/pkg/sql/logictest/testdata/logic_test/crdb_internal_tenant#L304-L308

we could change it to unimplemented though?

**Comment by otan** [comment]
https://github.com/cockroachdb/cockroach/pull/72737 suggests it needs to work for `./cockroach demo`

**Comment by stevendanna** [comment]
`SHOW RANGES` also expectedly hits this same error.

**Comment by ajwerner** [comment]
https://github.com/cockroachdb/cockroach/issues/83839 seems to duplicate this partially.

**Comment by knz** [comment]
The 2 vtables named at top don't have this problem any more.
However some other crdb_internal vtables still have it. For example `kv_node_status`.

Here, @ecwall says we have another issue / jira epic that covers the remainder of the work. Evan, please find that and close the duplicates.

**Comment by ecwall** [comment]
Here is the ticket with remaining work https://github.com/cockroachdb/cockroach/issues/54252
