### ISSUE TITLE
dev: provide flag to stream test output

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#72569]
**Is your feature request related to a problem? Please describe.**
It's often useful to see what's happening during a test. 

**Describe the solution you'd like**
`--test_output=streamed` is apparently a bazel thing.

**Comment by irfansharif** [comment]
Probably worth doing by default whenever `-v` is specified.

**Comment by ajwerner** [comment]
An answer is that arguments can be passed to bazel via `--` so `-- --test_output=streamed` will make it to bazel. That's the answer. Fewer features in `dev` means less to maintain. 

----

> Probably worth doing by default whenever -v is specified.

I'm cool with this but I worry a tad that we'll be creating an interesting middle ground where we have to remember how dev flags interact with bazel flags.
