### ISSUE TITLE
storage/engine: add option to preserve rocksdb wal for post mortem analysis

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#7257]
The RocksDB WAL contains every key/value written to and deleted from RocksDB. During normal operation, the WAL is garbage collected periodically as sstables are created. I think RocksDB contains sufficient hooks that we could save the WAL files for post mortem analysis debugging on the beta clusters. Think of this as an extreme form of backup: we can backup every single mutation that has occurred at the RocksDB level. I have to do further investigation, but what I'm imagining is copying the WAL files to some directory for backup and having another process copy the files from this directory to Google Cloud Storage / S3. 

For post mortem analysis we'd want to be able to take the WAL files and display keys and values matching a regex or something like that. 

@tschottdorf, @bdarnell thoughts?

**Comment by tschottdorf** [comment]
Certainly that is the nuclear option, but if that can be done it could be
preferable to writing higher-level logging primitives (it could also
eventually have a use case for audit trail etc, though I'm not familiar
with typical requirements in that area). We will wind up writing more debug
tools instead, but I am very much prepared to sift through a heap of
organized data if I know it will explain precisely what happened. What is
the WAL format? Is it similar to the WriteBatch? Assuming we log that trail
for weeks at a time before something breaks, do we have to "replay" it from
zero or can we also save intermittent snapshots? If that's not possible
that's also ok, I think all that matters is that we have "manageable"
chunks of WAL (i.e. sufficient enough to isolate, say, fraction of an hour
of activity); then we could replay from the beginning of time until just
before that and use that as a base for exploration (to see existing state
before shit hits the fan).

On Wed, Jun 15, 2016 at 8:53 PM Peter Mattis <notifications@github.com>
wrote:

> The RocksDB WAL contains every key/value written to and deleted from
> RocksDB. During normal operation, the WAL is garbage collected periodically
> as sstables are created. I think RocksDB contains sufficient hooks that we
> could save the WAL files for post mortem analysis debugging on the beta
> clusters. Think of this as an extreme form of backup: we can backup every
> single mutation that has occurred at the RocksDB level. I have to do
> further investigation, but what I'm imagining is copying the WAL files to
> some directory for backup and having another process copy the files from
> this directory to Google Cloud Storage / S3.
>
> For post mortem analysis we'd want to be able to take the WAL files and
> display keys and values matching a regex or something like that.
>
> @tschottdorf <https://github.com/tschottdorf>, @bdarnell
> <https://github.com/bdarnell> thoughts?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/7257>, or mute the thread
> <https://github.com/notifications/unsubscribe/AE135Div2SeVlCrxPaJf06EnDB2Wo3Y4ks5qMJ55gaJpZM4I27mx>
> .
>
-- 

-- Tobias

**Comment by petermattis** [comment]
Retaining the WAL files indefinitely is certainly feasible. There is a slightly easier option which is to use a `BackupableDB` or `Checkpoint` to take periodic backups (e.g. every 30 min). The backups would actually share the underlying RocksDB sstables (via hardlinks). The downside to using a `BackupableDB/Checkpoint` is that we wouldn't capture every mutation as we would if we retained the WAL files indefinitely. The best option would be to combine the two approaches: periodic snapshots of the sstable state along with retention of all WAL files. I'll need to investigate how difficult this last approach is.

I'm not sure of the precise details of the WAL format, but the `WriteBatch` representation is written to it unmodified. It should be easy to parse from Go. 

There are definitely other potential uses of WAL retention (e.g. auditing), but I think it best to keep this focused as a debugging tool for the near term.

**Comment by petermattis** [comment]
RocksDB contains an option for keeping WAL files around past when they are normally deleted: `WAL_ttl_seconds`. We can set this option arbitrarily high (e.g. `1 month`). There is also an interface for for iterating over the WAL records after a particular sequence. So my plan is to add the ability to set `WAL_ttl_seconds` and then see the WAL records from a particular checkpoint forward. This will likely be done via some sort of `cockroach debug wal <timestamp>` command. Thoughts?

**Comment by tschottdorf** [comment]
Sounds good to me. That would mean going through the WAL manually from the
last checkpoint RocksDB spat out, right? Getting the data is the important
thing, we can work on the debug tools as required later.

On Thu, Jun 16, 2016 at 5:25 PM Peter Mattis <notifications@github.com>
wrote:

> RocksDB contains an option for keeping WAL files around past when they are
> normally deleted: WAL_ttl_seconds. We can set this option arbitrarily
> high (e.g. 1 month). There is also an interface for for iterating over
> the WAL records after a particular sequence. So my plan is to add the
> ability to set WAL_ttl_seconds and then see the WAL records from a
> particular checkpoint forward. This will likely be done via some sort of cockroach
> debug wal <timestamp> command. Thoughts?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/7257#issuecomment-226618502>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE135DYymPEm72_jprBQbQoCe4FBxnGRks5qMb9JgaJpZM4I27mx>
> .
>
-- 

-- Tobias

**Comment by petermattis** [comment]
Yes, you would have to go through the WAL manually. That is, the `cockroach debug wal` command would output the contents of the WAL from a particular checkpoint forward to the current time. Agreed that fancy debug tools can come later. For the present, I'm going to provide only the most basic functionality.

**Comment by petermattis** [comment]
@mberhault When #7303 goes in, we should run the beta clusters with `COCKROACH_CHECKPOINT_FREQUENCY=1h` and `COCKROACH_ROCKSDB_WAL_TTL=720h`. There will be a pretty significant storage cost to retaining the checkpoints and archived logs. For example, running `block_writer` against a single-node for 1m created 145MB of "live" state and 474MB of "archived" logs. Do we have enough per-node storage to handle these increased data requirements? Or can we script periodically copying this data into Google Cloud Storage?

**Comment by bdarnell** [comment]
In case you haven't seen it, rocksdb comes with a tool called [`ldb`](https://github.com/facebook/rocksdb/wiki/Administration-and-Data-Access-Tool) which can be used to dump the contents of the WAL (It can do other stuff, but it refuses to touch our sstables because we use a custom comparator).

```
ldb dump_wal --walfile=cockroach-data/000353.log --print_value | head -1
5192710,1,47,0,PUT : 0x0173676F737300 : 0x120408001000180020002800320B36C45C5503120408001000 
```


It's pretty useless as-is but I'm mentioning it in case it's easier to massage this into useful output than to parse the WAL files from scratch.

**Comment by petermattis** [comment]
My current plan is to use `rocksdb::DB::GetUpdatesSince()`. I'll check out `ldb`, though I think we'll want to pretty-print the WAL contents.

**Comment by tschottdorf** [comment]
This can close, right?

**Comment by petermattis** [comment]
Yes.
