### ISSUE TITLE
ui: SQL Activity time ticker setting persisted across sessions

### ISSUE THREAD

**Issue by Azhng** [cockroachdb/cockroach#72580]
#68831 introduced the date time range selector in SQL Activity page in order to support query SQL Stats at a specific time range. Currently, we stored the currently selected date time range in local storage in the browser. 

However, this caused us to store selected date time range across different sessions. Concretely, suppose a user visit SQL Activity Page on Day 1 and selected date time range from 10:00 to 11:50 on Day 1, when the user relaunch the SQL Activity Page on Day 10, user will still be seeing SQL Stats from 10:00 to 11:50 on Day 1. 

cc: @xinhaoz

**Comment by maryliag** [comment]
Issue no longer valid. The time picker was changed to a range, e.g. Past 2hours, so it will always show relative to the current day
