### ISSUE TITLE
build: provide pre-built fully static binaries for Linux

### ISSUE THREAD

**Issue by farazfazli** [cockroachdb/cockroach#7261]
- What did you do?

Tried to run `go build` after getting the package
- What did you expect to see?

Single cockroach binary.
- What did you see instead?

`# github.com/cockroachdb/cockroach/client
client/rpc_sender.go:56: c.State undefined (type *grpc.ClientConn has no field or method State)
client/rpc_sender.go:56: c.WaitForStateChange undefined (type *grpc.ClientConn has no field or method WaitForStateChange)`

**Comment by tamird** [comment]
You need to use the Makefile in order to use the correct versions of dependencies. Can you try `make build`?

**Comment by farazfazli** [comment]
That made building normally work! However, I'm trying to create a statically linked binary. Now I'm getting this error:

```
go build -v -i -o cockroach
github.com/cockroachdb/cockroach
# github.com/cockroachdb/cockroach
/usr/local/go/pkg/tool/darwin_amd64/link: running clang++ failed: exit status 1
clang: error: unsupported option '-static-libgcc'

make: *** [install] Error 2
```

Thanks so much for all your help!

**Comment by farazfazli** [comment]
Here is my clang version by the way:

```
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by tamird** [comment]
There's a long saga around static builds in CockroachDB - the TL;DR is that they are supported only in a rather narrow sense. See https://github.com/cockroachdb/cockroach/pull/3343, https://github.com/cockroachdb/cockroach/pull/3412, and https://github.com/cockroachdb/cockroach/wiki/Using%20%60musl%60%20to%20get%20a%20completely%20static%20binary.

Also, the STATIC bit in the Makefile doesn't support OS X at all (see the TODO therein: `# TODO(peter): Allow this only when `go env CC` reports "gcc".`).

**Comment by farazfazli** [comment]
@tamird I see. Is it possible you guys can publish a completely statically linked binary built with musl to the releases? Thanks.

**Comment by tamird** [comment]
@farazfazli can you elaborate on why you need a fully static binary? We backed away from musl due to some discrepancies between it and glibc in DNS resolution, if memory serves.

**Comment by tamird** [comment]
Also, fully static binaries on OS X are not really a thing. musl is linux-specific, and there's no equivalent for OS X as far as I know.

**Comment by farazfazli** [comment]
I know, I would like to run it inside a super slim container @tamird.

**Comment by tamird** [comment]
OK, so you are asking for a fully static linux binary. I'll add that to our build.

**Comment by farazfazli** [comment]
Yes, thank you @tamird.

**Comment by knz** [comment]
This is now supported by our builder image via `build/builder.sh mkrelease amd64-linux-musl`.
