### ISSUE TITLE
roachprod: failures due to permission denied on /mnt/data1/cockroach

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#72635]
**Describe the problem**

See https://github.com/cockroachdb/cockroach/issues/72083#issuecomment-965790580 or any other issue linked to this thread, and [roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.*72635&group=repo&sort=-lastcommented&restgroup=false&display=project+category+lastorigin+lastcommented)

**To Reproduce**

Still reproducing, but we think it is related to restarting the roachprod vm and then trying to start CRDB again. Perhaps upon restarting, the /mnt/data1/cockroach permissions are not what they were on the initial boot.

@AlexTalks is taking a look.

**Impact**

Causing families of roachtests to fail predictably, see linked issues.

**Comment by healthy-pod** [comment]
Related to #72635 (not a fix for it but will help with debugging the issue)
