### ISSUE TITLE
server: panic during network initialization

### ISSUE THREAD

**Issue by jepsonzhang** [cockroachdb/cockroach#7265]
I make a test
cockroachdb version:build:     beta-20160609 @ 2016/06/09 16:31:43 (go1.6.2)

the test is several step:
**1、**i make three node A,B,C (in different Machine)  A is the first Node,B and C join A
A:./cockroach start --insecure --host=$host &
B:./cockroach start --insecure --join=$host:26257 --host=$localhost &
C: ./cockroach start --insecure --join=$host:26257 --host=$localhost &
**2、**i write some data into cockroachdb	
Node	Started	Bytes	Replicas	Connections	CPU Usage	Mem Usage	Logs
xxxx	an hour ago	138.8 MiB  9	0	4.80%	801.8 MiB	Logs   
xxxx	an hour ago	138.8 MiB  9	0	4.80%	801.8 MiB	Logs
xxxx	an hour ago	138.8 MiB  9	0	4.80%	801.8 MiB	Logs
**3、**I turn off node B,then Make Node D(in a new machine) join A and wait for replica to node D
but when node D cockroach process quit by itself when replicaing and leave no relative log .
xxxx	20 minutes ago	80.1 MiB  7	0	0.00%	0.0 B	Logs 
**4、**I try to start Node D,but it quit quickly,I try again ,then i got some panic

```
fatal error: fault
[signal 0xb code=0x1 addr=0x190400fa72c pc=0xfd9ffd]

goroutine 1 [running, locked to thread]:
runtime.throw(0x19f1390, 0x5)
        /usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc8201492a0 sp=0xc820149288
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:27 +0x2ab fp=0xc8201492f0 sp=0xc8201492a0
golang.org/x/net/http2.init.1()
        /go/src/golang.org/x/net/http2/headermap.go:69 +0x15d fp=0xc820149688 sp=0xc8201492f0
golang.org/x/net/http2.init()
        /go/src/golang.org/x/net/http2/writesched.go:283 +0x1420 fp=0xc820149720 sp=0xc820149688
google.golang.org/grpc/transport.init()
        /go/src/google.golang.org/grpc/transport/transport.go:508 +0x51 fp=0xc820149758 sp=0xc820149720
google.golang.org/grpc.init()
        /go/src/google.golang.org/grpc/trace.go:119 +0x6a fp=0xc820149780 sp=0xc820149758
github.com/gengo/grpc-gateway/runtime.init()
        /go/src/github.com/gengo/grpc-gateway/runtime/stream_chunk.pb.go:60 +0x78 fp=0xc8201498b0 sp=0xc820149780
github.com/cockroachdb/cockroach/util.init()
        /go/src/github.com/cockroachdb/cockroach/util/unresolved_addr.pb.go:349 +0x7e fp=0xc820149910 sp=0xc8201498b0
github.com/cockroachdb/cockroach/security.init()
        /go/src/github.com/cockroachdb/cockroach/security/x509.go:203 +0x44 fp=0xc820149918 sp=0xc820149910
github.com/cockroachdb/cockroach/cli.init()
        github.com/cockroachdb/cockroach/cli/_obj/_cgo_import.go:1 +0x5a fp=0xc820149f28 sp=0xc820149918
main.init()
        /go/src/github.com/cockroachdb/cockroach/main.go:41 +0x4a fp=0xc820149f30 sp=0xc820149f28
runtime.main()
        /usr/local/go/src/runtime/proc.go:177 +0x27f fp=0xc820149f80 sp=0xc820149f30
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820149f88 sp=0xc820149f80

goroutine 17 [jlocked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1
```

**Comment by knz** [comment]
Hello, thanks for your report!

Do you have any log output for node D in addition to the panic? They should be in `cockroach-data/logs`.

**Comment by tamird** [comment]
That node crashed during `init`; seems unlikely that there will be any logs.

**Comment by jepsonzhang** [comment]
i forgot to save the last log files ,course i want to reappear the bug again.so i clear the all and repeat the four steps above ,then the bug appear again,and got a panic ,i don't know whether  is the same.
--------------------------------------------------------------------------------------------------------------------

fatal error: fault
[signal 0xb code=0x80 addr=0x0 pc=0x5e614d]

goroutine 1 [running, locked to thread]:
runtime.throw(0x19f1390, 0x5)
        /usr/local/go/src/runtime/panic.go:
zhangjianping@dnode:~/cockroachdb/bin$ 547 +0x90 fp=0xc8200246b8 sp=0xc8200246a0
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:27 +0x2ab fp=0xc820024708 sp=0xc8200246b8
runtime.convT2I(0x1838320, 0x176f1e0, 0x28caad0, 0xc820024758, 0x0, 0x0, 0x8)
        /usr/local/go/src/runtime/iface.go:151 +0xd fp=0xc820024710 sp=0xc820024708
runtime.init()
        /usr/local/go/src/runtime/panic.go:23 +0x92 fp=0xc820024770 sp=0xc820024710
runtime.main()
        /usr/local/go/src/runtime/proc.go:140 +0x103 fp=0xc8200247c0 sp=0xc820024770
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200247c8 sp=0xc8200247c0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1


---------------------------------------------------------------------------------------------------------------------


i check the log files,there are nothing available.
**the WARNING is**
W160617 10:22:09.159297 util/log/clog.go:998  [config] file created at: 2016/06/17 10:22:09
W160617 10:22:09.159297 util/log/clog.go:998  [config] running on machine: dnode
W160617 10:22:09.159297 util/log/clog.go:998  [config] binary: CockroachDB beta-20160609 (linux amd64, built 2016/06/09 16:31:43, go1.6.2)
W160617 10:22:09.159297 util/log/clog.go:998  [config] arguments: [./cockroach start --insecure --join=192.168.56.101:26257 --host=192.168.56.104]
W160617 10:22:09.159297 util/log/clog.go:998  line format: [IWEF]yymmdd hh:mm:ss.uuuuuu file:line msg
W160617 10:22:09.159297 server/server.go:111  running in insecure mode, this is strongly discouraged. See --insecure.
W160617 10:22:09.197837 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node

**the last serveral line of INFO file:**
I160617 10:26:25.262019 /go/src/google.golang.org/grpc/clientconn.go:499  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 192.168.56.103:26257: getsockopt: connection refused"; Reconnecting to "192.168.56.103:26257"
I160617 10:26:26.737663 /go/src/google.golang.org/grpc/clientconn.go:499  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 192.168.56.103:26257: getsockopt: connection refused"; Reconnecting to "192.168.56.103:26257"
I160617 10:26:26.737928 /go/src/google.golang.org/grpc/clientconn.go:351  Failed to dial 192.168.56.103:26257: grpc: timed out trying to connect; please retry.
I160617 10:26:29.995353 server/status/runtime.go:160  runtime stats: 738 MiB RSS, 81 goroutines, 90 MiB active, 408.74cgo/sec, 0.21/0.03 %(u/s)time, 0.00 %gc (5x)
I160617 10:26:31.286697 /go/src/google.golang.org/grpc/clientconn.go:499  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 192.168.56.103:26257: getsockopt: connection refused"; Reconnecting to "192.168.56.103:26257"
I160617 10:26:32.637246 /go/src/google.golang.org/grpc/clientconn.go:499  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 192.168.56.103:26257: getsockopt: connection refused"; Reconnecting to "192.168.56.103:26257"
I160617 10:26:32.640976 /go/src/google.golang.org/grpc/clientconn.go:351  Failed to dial 192.168.56.103:26257: grpc: timed out trying to connect; please retry.
I160617 10:26:34.400982 storage/replica_raftstorage.go:611  replica 5 received snapshot for range 8 at index 706407. encoded size=70872812, 2046237 KV pairs, 16 log entries

**Comment by tamird** [comment]
This doesn't seem actionable, and a new beta has been released since this report. Please file a new issue if this persists.
