### ISSUE TITLE
ui: update jobs page colors

### ISSUE THREAD

**Issue by jocrl** [cockroachdb/cockroach#72674]
- Update the progress bar to our default blue: Hex `#0055FF` (also called `info-3`)
- Update the 'Succeeded' badge colors to match Figma 
    - Text: Hex `#237300` (also called `success-4`)
    - Background-fill: Hex `#E3F5E0` (also called `success-1`)

![Screen Shot 2021-11-04 at 2 10 48 PM](https://user-images.githubusercontent.com/51920721/140397410-5161c3e5-bb4e-45f5-9bd9-959b03e8face.png)

As requested by @Annebirzin in https://github.com/cockroachdb/cockroach/pull/72291#issuecomment-961303894

`info-3`, `success-4`, and `success-1` colors are [tokens in the ui repo](https://github.com/cockroachdb/ui/tree/master/packages/design-tokens). Changing the progress bar color can be done by installing `@cockroachlabs/design-tokens` in db console. However, colors for badges are defined in `.styl` stylesheets, which tokens are not exported for.

I think it's worth giving a shot at exporting stylus tokens, since `#E3F5E0` is not specified anywhere in DB Console.

**Comment by jocrl** [comment]
@Annebirzin assuming this sounds good to you, this will update all success badges in DB Console to the new colors. There are others potential success badges relating to diagnostics and the nodes overview.

**Comment by Annebirzin** [comment]
@jocrl yep this sounds good, thanks!
