### ISSUE TITLE
COPY TO

### ISSUE THREAD

**Issue by vitruvvius** [cockroachdb/cockroach#72680]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I can't do a COPY TO command into STDOUT

By example, using Rust sqlx crate

```
COPY (SELECT * FROM my_table) TO STDOUT (FORMAT CSV)
```

**Describe the solution you'd like**
COPY TO supported

**Describe alternatives you've considered**
Sending to blob storage - too slow / overly complicated w/ file naming

**Additional context**

**Comment by rafiss** [comment]
Thanks for your feedback! Until we add support for that, one thing you could try is to use our CLI client. See https://www.cockroachlabs.com/docs/stable/export.html#non-distributed-export-using-the-sql-client

This is more of a manual workaround, so probably won't work great from within your Rust program -- though it might be possible.

For now, I'll close this issue in favor of the larger one in https://github.com/cockroachdb/cockroach/issues/41608
