### ISSUE TITLE
[experiment] sql: increase size of FastIntSet's stack-allocated segment

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#72733]
Currently, `FastIntSet` can store integer values from 0 to 63 in its "small" stack-allocated segment. Once a value exceeds this limit, the set begins to use its "large" heap-allocated segment, which incurs heap allocations. The structure is used throughout the SQL optimizer to store column IDs.

We see in TPC-E that a large chunk of queries use more than 63 columns, so they hit this allocation regime. Worse, once these queries hit the allocation regime, many intermediate `FastIntSet` operations begin allocating all at once, because the API is designed with value semantics, so it treats inputs as immutable. This is very pronounced in CPU and heap profiles. For instance, with an `alloc_objects` sample from a heap profile, we see that over **8.5%** of all heap allocations in CRDB are due to `FastIntSet` manipulation, making `(*FastIntSet).toLarge` and `(FastIntSet).Copy` the two largest sources of heap allocations in the workload:

```
----------------------------------------------------------+-------------
      flat  flat%   sum%        cum   cum%   calls calls% + context 	 	 
----------------------------------------------------------+-------------
                                         524033092 73.04% |   github.com/cockroachdb/cockroach/pkg/util.(*FastIntSet).Add /go/src/github.com/cockroachdb/cockroach/pkg/util/fast_int_set.go:75
                                         136724537 19.06% |   github.com/cockroachdb/cockroach/pkg/util.(*FastIntSet).UnionWith /go/src/github.com/cockroachdb/cockroach/pkg/util/fast_int_set.go:221
                                          56659299  7.90% |   github.com/cockroachdb/cockroach/pkg/util.(*FastIntSet).DifferenceWith /go/src/github.com/cockroachdb/cockroach/pkg/util/fast_int_set.go:278
 717416928  4.40%  4.40%  717416928  4.40%                | github.com/cockroachdb/cockroach/pkg/util.(*FastIntSet).toLarge /go/src/github.com/cockroachdb/cockroach/pkg/util/fast_int_set.go:50
----------------------------------------------------------+-------------
                                         414941755 61.21% |   github.com/cockroachdb/cockroach/pkg/sql/opt.ColSet.Copy /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/colset.go:58
                                          98228029 14.49% |   github.com/cockroachdb/cockroach/pkg/util.FastIntSet.Union /go/src/github.com/cockroachdb/cockroach/pkg/util/fast_int_set.go:234
                                          95368850 14.07% |   github.com/cockroachdb/cockroach/pkg/util.FastIntSet.Intersection /go/src/github.com/cockroachdb/cockroach/pkg/util/fast_int_set.go:255
                                          69324899 10.23% |   github.com/cockroachdb/cockroach/pkg/util.FastIntSet.Difference /go/src/github.com/cockroachdb/cockroach/pkg/util/fast_int_set.go:283
 677863533  4.16%  8.56%  677863533  4.16%                | github.com/cockroachdb/cockroach/pkg/util.FastIntSet.Copy /go/src/github.com/cockroachdb/cockroach/pkg/util/fast_int_set.go:190
----------------------------------------------------------+-------------
```

<img width="1586" alt="Screen Shot 2021-11-14 at 2 48 56 PM" src="https://user-images.githubusercontent.com/5438456/141696284-56e0b5f8-0ace-4cbc-8a46-4074e18ab00b.png">

## Experiment

We should experiment with increasing the size of the stack-allocated segment of the `FastIntSet`. Replacing the `uint64` with a `uint128.Uint128` would allow the set to store column IDs all the way up to 127 without allocating. We could then test this out on TPC-E to see how many queries still exceed this limit. I'd guess it would be very few, so we could reasonably expect that this change would reduce total heap allocations in the workload by somewhere around **8%**.

**Comment by mgartner** [comment]
This has come up before in #66226.

**Comment by RaduBerinde** [comment]
I wonder how feasible it would be to use an `unsafe.Pointer` for the pointer and use that for extra value bits. We'd have to find a scheme where these aren't actually valid pointers that might preclude the GC from cleaning up real objects.

**Comment by RaduBerinde** [comment]
One thing to note is that in the optimizer ColumnIDs are unique across the entire query. So it should be common to have sets of columns that have values that are not small but are still in a narrow range (i.e. `max - min` is not large). So perhaps we can consider an encoding where we store the minimum value in some bits, and then a bitmap for the rest of the values (relative to that minimum).

**Comment by RaduBerinde** [comment]
I can prototype the simple proposal to go to 128 bits first though. @nvanbenschoten if I provide updated code, can you help with benchmarking the relevant queries?

**Comment by nvanbenschoten** [comment]
> @nvanbenschoten if I provide updated code, can you help with benchmarking the relevant queries?

Absolutely. If you create a branch, I can run it against TPC-E and get some before and after heap profiles.

**Comment by mgartner** [comment]
> I wonder how feasible it would be to use an unsafe.Pointer for the pointer and use that for extra value bits. We'd have to find a scheme where these aren't actually valid pointers that might preclude the GC from cleaning up real objects.

@RaduBerinde what would be the advantage of this?

**Comment by RaduBerinde** [comment]
> @RaduBerinde what would be the advantage of this?

We could support more bits without increasing the size of the object. But maybe the size doesn't matter that much.

**Comment by RaduBerinde** [comment]
@nvanbenschoten Try https://github.com/RaduBerinde/cockroach/tree/fast-int-set-128   I tested it with larger sizes too if you have to go to 3 words.

**Comment by nvanbenschoten** [comment]
This is great @RaduBerinde! I ran some experiments with TPC-E with your patch applied to release-v21.2 (to avoid https://github.com/cockroachdb/cockroach/issues/71576). After letting the workload run for a few minutes, I captured a 60 second heap profile and focused in on the `alloc_objects` sample. Here are the results:

| | Percent of total heap allocations | Rank in source of heap allocations |
| --- | ----------- | ----------- |
| Before | 6.07% | 1 and 2 |
| After with `bitmapWords = 2` | 1.07% | 24 and 26 |
| After with `bitmapWords = 3` | 0% | - |

So the change certainly appears to work. We do still seem to exceed the 128 column limit in a few queries, but even just using 2 stack-allocated words avoids most of the heap allocations due to the `FastIntSet`.

It's tough to tell exactly what kind of effect this will have on top-line max throughput numbers because I'm not pushing this workload to saturation, but I'd imagine that a reduction in heap allocations by around 5% will be measurable. As we've seen time and time again, the first-order and second-order effects of heap allocations really add up (which reminds me, I've been meaning to share https://twitter.com/bboreham/status/1413460584947884033 around).

**Comment by RaduBerinde** [comment]
@nvanbenschoten do you think it's possible to get the top callsites for the fast_int_set operations that allocate? I'm trying to see if there are some simple fixes we can make to improve those, perpendicular to making FastIntSet larger.

**Comment by nvanbenschoten** [comment]
I unfortunately don't have a copy of this heap profile and shut down the cluster a little while ago. We have a roachtest (`tpce/c=5000/nodes=3`) that runs the workload, but it's having some trouble on master. I don't imagine much has changed since v21.2 though, so you could run that with a release-21.2 binary and observe the cluster as it runs.
