### ISSUE TITLE
ui: consider showing `--cluster-name` instead of cluster guid in dbconsole

### ISSUE THREAD

**Issue by matthewtodd** [cockroachdb/cockroach#72775]
**Tim Veil  35 minutes ago**
here is my summary… look at benchbase 650kb (edited) 

![image](https://user-images.githubusercontent.com/5261/141838697-ab525cb7-cf91-4673-a9ce-85d7369302e3.png)

**Tim Veil  17 minutes ago**
also every node was started with `--cluster-name=benchbase` why does this never show?  instead always presented with cluser id guid

Jira issue: CRDB-11279

**Comment by piyush-singh** [comment]
cc @thtruo I think this is probably a Obs Infra issue.

**Comment by thtruo** [comment]
Ack, re-triaging. Thanks for filing this Matthew. Think this is actually going to live on Cluster UI

**Comment by thtruo** [comment]
Btw @nkodali there are a handful of nits and fit and finish issues that came up as folks were testing v21.2 - putting this on our radar so that the fixes can make it into the next patch release

**Comment by maryliag** [comment]
No longer a priority
