### ISSUE TITLE
ui: DB Console nits for v21.2.0

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#72783]
**Describe the problem**

- [ ] Screenshots use old green branding - we should use the updated purple branding
- [ ] Paragraph that says "request an **Enterprise trial license**" currently links to a list of enterprise features instead of the "start trial" link
![image](https://user-images.githubusercontent.com/1474303/141847832-f3b76bcd-be63-4c01-b039-26ad9efd3bcb.png)

- [ ] Display the `--cluster-name` in the header https://github.com/cockroachdb/cockroach/issues/72775 
- [ ] On the node detail screen the link to “view logs” appears to be bolded.  no other links appear bolded in the console
- [x] On the “nodes list” overview screen we show a status “Live” in a gray box..  the color gray is usually associated with dead or unknown.  when I click into the node detail, the word “live” has disappeared and is replaced with “health” and a value of “healthy” which is green.  are “status” and “health” different things?  if they are the same lets make them the same and use green in both places to signify a properly functioning system
- [x] The problem ranges report screen really sticks out with the old green branding
- [x] On the left navigation we have “overview” and “metrics”… “overview” loads a page with no header (fine) but clicking on “metrics” loads a page called “overview dashboard”. shouldn’t this be “metrics dashboard” or just “metrics” since one could argue all the pages are “dashboards”…
- [x] Re headers, “network latency” and “advanced debug” are a slightly different font and position than the rest

**Comment by thtruo** [comment]
cc @nkodali another list of v21.2 nits that we should prioritize in an upcoming sprint/milestone so we can get these into the next patch release for v21.2

**Comment by zachlite** [comment]
Hey @thtruo, I've opened a PR for some of the actionable items here: https://github.com/cockroachdb/cockroach/pull/73253


### For the items I did not take action on:
> Screenshots use old green branding - we should use the updated purple branding

> Paragraph that says "request an Enterprise trial license" currently links to a list of enterprise features instead of the "start trial" link

@nathanstilwell jumped on these two.  There was a concern that directing users to enterprise licensing conflicts with the initiative of driving cloud adoption.  Perhaps someone from product can weight in here.

___
>Display the --cluster-name in the header

I couldn't recreate this.  I was able to see the cluster name using the `--cluster-name` arg using 21.1 and 21.2
___


> On the “nodes list” overview screen we show a status “Live” in a gray box..

I spoke to the design team - The design is intentional.
 ___

> On the node detail screen the link to “view logs” appears to be bolded

All of the items in that list have the same font and font weight applied, so an inconsistency might be perceived because of the difference in color.  I would defer to the design team here.

**Comment by thtruo** [comment]
Thanks @zachlite. Looping in @Annebirzin for design perspectives on the relevant open items

**Comment by thtruo** [comment]
> Paragraph that says "request an Enterprise trial license" currently links to a list of enterprise features instead of the "start trial" link

> Nathan jumped on these two. There was a concern that directing users to enterprise licensing conflicts with the initiative of driving cloud adoption. Perhaps someone from product can weight in here.

^ Regarding this - @nathanstilwell I think you bring up a good point here about trying to direct users to use CRDB Dedicated or Serverless. We should perhaps rethink the overall messaging/framing for this particular page. However, in lieu of making a bigger change, this specific issue is still relevant for our self-hosted users and they should land on https://www.cockroachlabs.com/docs/v21.2/get-started-with-enterprise-trial instead of https://www.cockroachlabs.com/docs/stable/enterprise-licensing.html to help unblock them on enabling the node map functionality. So I'd still propose we clean up the existing page in the meantime before we add other cloud adoption specific messaging. Let me know if you still feel strongly against this approach

**Comment by Annebirzin** [comment]
@thtruo  Just catching up and giving my 2 cents here. Is it true that only enterprise users can view the node map? In that case, I'm not sure it actually makes sense to direct users to Dedicated or Serverless from the map page. Assuming the user is coming here to see the map, signing up for dedicated or serverless would not accomplish that goal and might confuse the user. Maybe there are other places in the UI that are better suited to promote dedicated/serverless?

**Comment by nathanstilwell** [comment]
@thtruo @Annebirzin To clarify, I was commenting on our increased focus to promote our Managed Service offering recently, and I was unsure of our current strategy / priority in pushing enterprise licenses. I totally agree that enterprise licenses in whatever context they are using CRDB is still a business priority, I simply don't have the context to understand how that might be changing.

So to get to some tangible updates, thank you for the URL change. That was one question. Do we really want to use a URL with a version number in it though? I imagine that may have to be updated after every release. The other update I think we need here are the assets in the _Step 1, Step2, Step 3_ of getting to an enterprise license.

![Screen Shot 2021-11-30 at 1 39 20 PM](https://user-images.githubusercontent.com/397448/144107719-5ca0c7a4-f0f3-4bdc-b0f7-f7a7567e50c6.png)

Steps 1 and 3 seem to use screenshots that I could probably replace, but step 2 seems to be a designed asset that either needs to be recreated or updated.

**Comment by thtruo** [comment]
Gotcha, thanks Nathan. I'm looping in @taroface about the URL question. There was a related [Slack thread](https://cockroachlabs.slack.com/archives/C3T5LG9R8/p1638392263062100) going on and Ryan might have thoughts around how to handle the links here

**Comment by Annebirzin** [comment]
@nathanstilwell and @zachlite attached is an image for step 2 with our brand colors. Let me know if this works okay or if you need any sizing adjustments
![NodeMap_screen](https://user-images.githubusercontent.com/51920721/144462184-5e2a0f0f-5216-4a73-b8a0-9916028b221c.png)
.
