### ISSUE TITLE
Investigate and fix flaky TestChangefeedResolvedFrequency tests.

### ISSUE THREAD

**Issue by xun-cockroachlabs** [cockroachdb/cockroach#72799]
I encountered some build issue seems to related with these flaky 2 tests that continuously blocking a pending change of roachprod: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_Test/3737212. My change is on roachprod and not related with the failing test, in a pretty recent commit of this pending change build passed fine, and the first test `TestChangefeedResolvedFrequency` passed in local test in the latest commit, the second failed locally with the same error as teamcity build.

**Comment by xun-cockroachlabs** [comment]
I still encountered at least one flaky build after rebasing this fix, per @ajwerner this is a partial fix that makes the time out less frequent. I can confirm that it did make the test much more stable. If it becomes frequent flaky, feel free to re-open.

**Comment by ajwerner** [comment]
Oh, hold on, I misspoke about which test flake we were talking about. I think #72801 fixed this flake.
