### ISSUE TITLE
Error in log message mentioning COCKROACH_RAFT_CLOSEDTS_ASSERTIONS_ENABLED

### ISSUE THREAD

**Issue by ferdypruis** [cockroachdb/cockroach#72812]
I've been spending the last 2 hours trying to get my 5 node cluster back online after an incorrect system clock was corrected by setting it an hour back. Nodes kept crashing because of unknown leaseholders and something wrong with the raft.

> raft closed timestamp regression in cmd: "E\x85\x18\"A*\x1f\n" (term: 32, index: 27382898); batch state: 1637064830.047654702,0, command: 1637062494.588964740,0, lease: repl=(n4,s4):4 seq=24 start=1637061375.106223124,1 exp=1637064842.047654702,3679 pro=1637064833.047654702,3679, req: <unknown; not leaseholder>, applying at LAI: 12590380.
Closed timestamp was set by req: <unknown; not leaseholder or not lease request> under lease: %!s(PANIC=SafeFormatter method: value method github.com/cockroachdb/cockroach/pkg/roachpb.Lease.SafeFormat called using nil *Lease pointer); applied at LAI: 0. Batch idx: 0.
This assertion will fire again on restart; to ignore run with env var COCKROACH_RAFT_CLOSEDTS_ASSERTIONS_ENABLED=trueRaft log tail:

While the final line in this error led me to getting my cluster back online, it contains 2 errors;
- The environmental variable `COCKROACH_RAFT_CLOSEDTS_ASSERTIONS_ENABLED` must be set to "false" to disable the check, not "true".
- There is no newline between this line and the next line starting with "Raft log tail".

https://github.com/cockroachdb/cockroach/blob/db229cad354c2776ea35c9dc4f78e6ce66b9437c/pkg/kv/kvserver/replica_application_state_machine.go#L1023

**Comment by knz** [comment]
Can you give us more details: which version of crdb is this?
