### ISSUE TITLE
kvserver: `(Lease).String` / `(Lease)SafeFormat` should support `nil` references via a pointer receiver

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#72814]
In issue #72812 we see the following text in an error message:
```
Closed timestamp was set by req: <unknown; not leaseholder or not lease request> under lease: 
%!s(PANIC=SafeFormatter method: value method github.com/cockroachdb/cockroach/pkg/roachpb.Lease.SafeFormat called using nil *Lease pointer); applied at LAI: 0. Batch idx: 0
```

Perhaps there's a discussion to be had about whether the presence of a `nil` pointer is reasonable. However, for troubleshooting purposes it would be useful if the error would print the text "`nil`" and not a formatting error/PANIC.

**Comment by andreimatei** [comment]
Didn't you tell me this was fixed in https://github.com/cockroachdb/redact/issues/15 ?

**Comment by knz** [comment]
Oh that's right. Is it possible that error (from the linked issue) is from a crdb version from before that change?

**Comment by andreimatei** [comment]
Don't think so. The assertion in the linked issue is something I've added very recently on master.

**Comment by andreimatei** [comment]
Should cockroachdb/redact#15 be reopened?

**Comment by knz** [comment]
we're discussing this on the internal channel. There's evidence the redact code is fine. If something is wrong, it appears to be in the way the go runtime is presenting the values through `reflect` or some other fudgery. Maybe the issue is specific to M1 macs?

I want to see a repro of the problem in a small program.

**Comment by knz** [comment]
ok so after a lengthy conversation with @erikgrinaker , we're tentatively concluding that this issue (#72814) comes from an observation (#72812) made using an old version of CockroachDB that did not contain the fix for https://github.com/cockroachdb/redact/issues/15. 

So this issue would not exist in current versions of CockroachDB, and thus would not need to be "fixed" by changing the method definitions.

Therefore, we wouldn't introduce a regression by reverting #74315.

cc @kvoli
