### ISSUE TITLE
sql: support `has_table_privilege(oid, 'RULE')`

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#72832]
Although `RULE` is not listed as an allowed privilege on https://www.postgresql.org/docs/current/functions-info.html it turns out that PG supports a query like this
```
select has_table_privilege('table'::regclass::oid, 'RULE')
```

Some tools rely on this. We can implement it in CRDB by always returning false, since CRDB does not have `RULE` privileges.

----

Instructions:

* Modify the built-in in https://github.com/cockroachdb/cockroach/blob/cfb0bf33148744ec06d5d91a1927ca3115101782/pkg/sql/sem/builtins/pg_builtins.go#L1849
* Add a test in https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/privilege_builtins, and run make testbaselogic FILES='privilege_builtins' TESTFLAGS='-rewrite' to test it.
* Submit a PR.

**Comment by otan** [comment]
i think this is a legacy format from pg 8 (https://www.postgresql.org/docs/8.1/sql-grant.html)

**Comment by sunisdown** [comment]
Hi team, I'm interested in this issue and would like to pick it up. could you help assign it to me.

**Comment by otan** [comment]
We don't generally assign issues to external contributors but you are free to work on it :)

**Comment by sunisdown** [comment]
@otan thanks for your reply.
