### ISSUE TITLE
upgrade from 21.1.11 to 21.2.0 got `store` error

### ISSUE THREAD

**Issue by kocoten1992** [cockroachdb/cockroach#72849]
**Describe the problem**
I try upgrading cockroachdb from 21.1.11 to 21.2.0 (change binary `cockroach`), database won't start, revert back to 21.1.11 everything is good. 

```
Nov 17 01:04:26 d5 cockroach[738728]: * ERROR: ERROR: cockroach server exited with error: store <no-attributes>=/opt/cockroachdb/cockroach-data, last used with cockroach version v20.2, is too old for running vers>
Nov 17 01:04:26 d5 cockroach[738728]: *
Nov 17 01:04:26 d5 cockroach[738728]: ERROR: cockroach server exited with error: store <no-attributes>=/opt/cockroachdb/cockroach-data, last used with cockroach version v20.2, is too old for running version v21.2>
```

But I don't use `store` attribute anymore (I have use it in the past - but nowadays I use ssd for everything so have drop that attribute from cockroachdb start command long ago).

```
# command to start cockroachdb
cockroach start --certs-dir=/opt/cockroachdb/certs --host=0.0.0.0 --join=localhost:26257 --locality=region=ap-southeast-1
```

#### Please describe the issue you observed, and any steps we can take to reproduce it:
This is an old cluster (I think maybe from 19.x version with repeated upgrade to newer version), last it was running on 21.1, upgrade to 21.2 and get issue above

**To Reproduce**
~~I've not try yet, but I think you could try `store` option on 20.2 then try upgrade to 21.2 and hopefully will get error.~~

Here is the reproduction
https://github.com/cockroachdb/cockroach/issues/72849#issuecomment-972522593

**Comment by kocoten1992** [comment]
here is the reproduction

```sh
# preparing
cd /tmp/
mkdir reproduce_72849
cd reproduce_72849
mkdir cockroach-data

# try 20.2
wget https://binaries.cockroachdb.com/cockroach-v20.2.18.linux-amd64.tgz
tar -xvf cockroach-v20.2.18.linux-amd64.tgz
cp cockroach-v20.2.18.linux-amd64/cockroach cockroach_20_2_18
./cockroach_20_2_18 start-single-node --insecure --store=cockroach-data

# then Ctrl+C to stop the server and try 21.2
wget https://binaries.cockroachdb.com/cockroach-v21.2.0.linux-amd64.tgz
tar -xvf cockroach-v21.2.0.linux-amd64.tgz
cp cockroach-v21.2.0.linux-amd64/cockroach cockroach_21_2_0
./cockroach_21_2_0 start-single-node --insecure --store=cockroach-data
```

**Comment by kocoten1992** [comment]
Oke, I've figured it out, you need to update to latest `cockroach` binary first, only then upgrade to 21.2, in this case it is `21.1.12`, I thought minor version wasn't important, but it does!

**Comment by knz** [comment]
Thanks for explaining how you solved the issue!

**Comment by igremmerlb** [comment]
Just chiming in that we are experiencing the same issue.  Currently on 21.1.13.  Can't upgrade to 21.2.4.  The database was upgraded from 20.2 to 21.1 a few days ago.  I'll try again next week and see if it works, as @kocoten1992 mentioned it might be better to wait a few days.

E220204 22:27:30.458947 1 1@cli/clierror/check.go:35 ⋮ [-] 2 ‹ERROR›: cockroach server exited with error: store ‹<no-attributes>=/data›, last used with cockroach version v20.2, is too old for running version v21.2 (which requires data from v21.1 or later

**Comment by kocoten1992** [comment]
@igremmerlb waiting doesn't work (the comment above I made only work on testing :smiling_face_with_tear: , on production with running database it does not).

Not reporting that because I'm surprised why no one is having the same problem, what I end up doing is `backup` and `restore`, that work for me.

Now there are more people having this issue, is it worth consider open again @knz ?

**Comment by knz** [comment]
> The database was upgraded from 20.2 to 21.1 a few days ago

You have probably not finalized the upgrade to 21.1.

This is documented here: 
- https://www.cockroachlabs.com/docs/stable/upgrade-cockroach-version.html#step-3-decide-how-the-upgrade-will-be-finalized
- https://www.cockroachlabs.com/docs/stable/upgrade-cockroach-version.html#step-5-finish-the-upgrade

**Comment by kocoten1992** [comment]
I'm not sure if that the case, it fail right at binary replace step.

After replace binary, node can no longer be start (result in the error above), only then re-replace with old binary node (21.1.x) node can be start again.

**Comment by igremmerlb** [comment]
I appreciate the help.  This is what I am seeing when I try to run the command.
cockroach sql
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
# Server version: CockroachDB CCL v21.1.13 (x86_64-unknown-linux-gnu, built 2022/01/10 17:44:25, go1.15.14) (same version as client)
# Cluster ID: e2e129fd-391d-4b8f-9c14-c78f6d8fce54
#
# Enter \? for a brief introduction.
#
root@:26257/defaultdb> SET CLUSTER SETTING cluster.preserve_downgrade_option = '21.1';
ERROR: cannot set cluster.preserve_downgrade_option to 21.1 (cluster version is 20.2)

![image](https://user-images.githubusercontent.com/17181956/152645981-1a075a45-625a-4264-a090-c8586258401d.png)

**Comment by igremmerlb** [comment]
It looks like two of my older nodes are stuck in decommissioning state even though they should be long gone.  I bet that is the reason.  I'll see if I can get those fully decommissioned.

![image](https://user-images.githubusercontent.com/17181956/152646669-a6539082-ac60-4c16-961b-7bcaffc766de.png)

**Comment by igremmerlb** [comment]
I stopped the full cluster and then started all the nodes back up.  Nodes #1 and #3 are still in decommissioning state even though the cluster was restarted.  These particular nodes have been long gone - maybe 6 months or a year.  The UI shows everything is fine.  Do you have any suggestions on how to force out the stuck decommissioning nodes?

![image](https://user-images.githubusercontent.com/17181956/152825277-d1e05ed7-3a67-4c26-b63b-d6810ad623b8.png)

**Comment by igremmerlb** [comment]
I was able to run:
  cockroach node decommission 1 3
and that worked.  So mine is good now.
