### ISSUE TITLE
cli: readline from stdin ignores last line without EOL

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#7286]
```
echo -n 'select 1' | ./cockroach sql
```

Prints nothing. Adding a debug line to `cli/sql.go` after `readline.Line`:

```
		l, err := readline.Line(thisPrompt)
		fmt.Println("READLINE", l, "ERR", err, "OVER")
```

Prints

```
READLINE  ERR EOF OVER
```

So `err` is getting set to EOF which I think is expected, but `l` is set to the empty string, which is not. This may be a bug in the readline package. @chzyer thoughts?

**Comment by chzyer** [comment]
Why add a `-n` option? It's not even a line if `\n` is missing :)

**Comment by mjibson** [comment]
If it's returning EOF, shouldn't it also return whatever it read?

**Comment by bdarnell** [comment]
Our statements are terminated by semicolons, not newlines - we want to execute the statement even if it doesn't end with a newline. At a minimum we need to be able to distinguish EOF with no pending input from EOF with pending input that is being discarded. (but why are we even using `readline` if stdin is not a tty?)

I think it's actually a bug that we allow the semicolon to be optional on the last statement. The fact that `sh` treats EOF as a statement terminator is one of the problems with the `curl | sh` pattern. If something fails on the left side of the pipe, it has no way to signal to the right hand process not to execute the partial statement it has generated. We should require the semicolon for commands piped to stdin (it's fine for it to be optional with `-e`).

**Comment by chzyer** [comment]
@mjibson @bdarnell 
I just push a commit to fix this. :)
