### ISSUE TITLE
UI bug: metrics disappears after zooming in

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/cockroach#72874]
**Describe the problem**

Hardware metrics metrics disappears after zooming in.

**To Reproduce**

1. Start with standard 10min view of hardware metrics
2. Zoom into 2 minutes of metrics
3. Switch to SQL metrics while zoomed in
4. Switch back to hardware metrics (you will only see storage capacity metrics and all other metrics disappears)

**Expected behavior**
Hardware metrics should persist even after toggling to other metrics types

**Additional data / screenshots**

![ui_1](https://user-images.githubusercontent.com/58752716/142239790-c212b4ab-e7e7-45fe-84c9-b3f535dd0b7f.png)

![ui_2](https://user-images.githubusercontent.com/58752716/142239836-d387fa03-b5cc-4316-83a5-0535247ef3f7.png)

![ui_3](https://user-images.githubusercontent.com/58752716/142239888-5dcca920-9152-48cf-971e-78a15454770b.png)

![ui_4](https://user-images.githubusercontent.com/58752716/142239946-8d17ed2a-8af9-46e4-91c8-4e39f147aea7.png)

**Environment:**
 - CockroachDB version 21.2.0

**Comment by thtruo** [comment]
https://github.com/cockroachdb/cockroach/issues/72114 reported the same issue. Looks like there was PR merged but am not sure if the backport to 21.2 succeeded which might explain why this is still happening. Will comment on the PR https://github.com/cockroachdb/cockroach/pull/72431 to clarify

**Comment by koorosh** [comment]
This issue has been fixed with this PR https://github.com/cockroachdb/cockroach/pull/71951 and now should be backported to 21.2 version
