### ISSUE TITLE
changefeedccl: Add on_error=pause + schema_change=stop test + protect_on_pause + with_cursor

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#72889]
Add a test that verifies expected behavior when schema change policy set to STOP,
on_error=pause and we execute schema change.

Jira issue: CRDB-11335

**Comment by shermanCRL** [comment]
Notes from conversation:

- Write down our expected invariants, and have tests for each
- Combinatorial? Something like nested loops for each combination.

**Comment by ajwerner** [comment]
Seems like a reasonable fit for the nemesis tests.

**Comment by miretskiy** [comment]
Good idea.
