### ISSUE TITLE
sql,catalog: should not allow a column definition to have a computed column and default expression

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#72881]
**Describe the problem**

We disallow computed columns from having `ON UPDATE` -- but currently they are allowed to have `DEFAULT` expressions. This is confusing.

The postgres behavior is to disallow it:
```
rafiss@127:postgres> create table t (a int, b int generated always as (a+1) stored);
CREATE TABLE

rafiss@127:postgres> alter table t alter column b set default 3;
column "b" of relation "t" is a generated column
```

**To Reproduce**

Run the above commands on CockroachDB

**Expected behavior**
It should error.

There also potentially could be some descriptor validation, but that might get complicated if there are already clusters in the wild that are in this state.

**Environment:**
 - CockroachDB commit d16a755cfa

**Comment by postamar** [comment]
This can be fixed. Just to make sure, assuming we encounter a cluster in the wild with a computed column with a default value, the correct fix would be to remove the default value, right?

**Comment by rafiss** [comment]
Yes, I think that is the way to go.
