### ISSUE TITLE
log: the 21.2 refactor removed auto-redaction for log tags

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#72905]
**Describe the problem**

In 21.1 and prior versions, the "tags" part of a log entry envelope were redacted if the sink flag `redact` was set to `true`.

In 21.2, this redaction is not taking place any more. This is a regression.

**To Reproduce**

`cockroach start-single-node ... --log='sinks: {stderr: {filter: INFO, redact: true}}'`

**Expected behavior**

redactable value are redacted

**Comment by knz** [comment]
There's another issue: if `redactable: false` is set, any redactable tags do not get their redaction markers stripped.

**Comment by knz** [comment]
cc @thtruo @dhartunian @jtsiros for triage

**Comment by thtruo** [comment]
Thanks @knz just wanted to clarify if you see work that will be split between DB Server and Obs Infra, or if Obs Infra will take over now. If the latter, I'll update the `T-*` labels so that it appears in our backlog for triaging

cc @nkodali to put on our radar

**Comment by knz** [comment]
I have implemented a unit test that demonstrates the problem in  #72992.

**Comment by knz** [comment]
changed #72992 to include a fix too.
