### ISSUE TITLE
changefeedccl: Handle protect_data_from_gc_on_pause when pausing during initial scan.

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#72942]
When running initial scan, before changefeed checkpoints highwatermark, it may not be
possible to pause the job.
This is because as part of writing initial backfill checkpoint records, we also emit
a zero timestamp for high watermark.  This has the unfortunate effect of not being able to protect
data on pause.

**Comment by miretskiy** [comment]
Turns out the problem is around changefeeds started with the cursor.  
If you start changefeed w/ cursor, the we do not lay protected TS record.
That means that PTS record is nil.  We then run for a while w/out producing a checkpoint
(e.g. due to a large enough catchup scan).  During that time, we `maybeCheckpointJob`:
```
	updateHighWater :=
		cf.frontier.schemaChangeBoundaryReached() || cf.js.canCheckpointHighWatermark(frontierChanged)
	updateCheckpoint := !updateHighWater && cf.js.canCheckpointInitialScan()
```

UpdateHighWater maybe true, but updateCheckpoint doesn't check for anything other than "canCheckpointInitialScan".
Unfortunately, `canCheckpointInitialScan` doesn't actually check that we are in an initial scan, but instead just checks
if the last update was in the past far enough.

Combine this with the fact that change frontier does not advance it's span frontier -- so span frontier is 0, until all nodes
report their progress.  That's unfortunate because now, even though update high-water is false, we will write a checkpoint record with a 0 high water mark.  Furthermore, if we also have on_error=pause with protect on pause, OnPauseRequested would also fail (because writing a 0 ts PTS record is not allowed).

Majority of this issue *is* fixed by #71848
We need to backport the above issue; we also need to focus on adding few test cases specifically dealing with this issue.

**Comment by amruss** [comment]
https://github.com/cockroachdb/cockroach/pull/73044

**Comment by amruss** [comment]
closing due to merging of https://github.com/cockroachdb/cockroach/pull/71848 as well as above PRs
