### ISSUE TITLE
sql/flowinfra: don't send ConsumerSignal during FlowRegistry registration while holding lock

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#72964]
The largest source of mutex contention in TPC-E is in a location I haven't seen before. During a test, we see over **25%** of time spent blocking on mutexes process-wide in `FlowRegistry.ConnectInboundStream`, which is responsible for registering an incoming stream with the flow registry:

<img width="1762" alt="Screen Shot 2021-11-18 at 10 18 17 PM" src="https://user-images.githubusercontent.com/5438456/142559447-c3deac72-3645-4f03-a664-1a9713375ad6.png">

Looking at the code, it's not hard to see why. [`FlowRegistry.ConnectInboundStream`](https://github.com/cockroachdb/cockroach/blob/28bb1ea049da5bfb6e15a7003cd7b678cbc4b67f/pkg/sql/flowinfra/flow_registry.go#L480) grabs a registry-wide (i.e. process-wide) exclusive lock and proceeds to register the flow with the registry. So far, this seems reasonable.

However, it then constructs and sends [at least one](https://github.com/cockroachdb/cockroach/blob/28bb1ea049da5bfb6e15a7003cd7b678cbc4b67f/pkg/sql/flowinfra/flow_registry.go#L534) (and [sometimes two](https://github.com/cockroachdb/cockroach/blob/28bb1ea049da5bfb6e15a7003cd7b678cbc4b67f/pkg/sql/flowinfra/flow_registry.go#L489)) `*ConsumerSignal` messages on a gRPC stream. So under a process-wide exclusive lock, we're interacting with gRPC. Granted this is a gRPC stream so it is usually non-blocking, but it's still expensive.

We should try to restructure this code to pull any interactions with gRPC outside of the locking. Ideally, the locking would surround just the portion of the code that requires mutual exclusion and nothing else. I believe this is just the interactions with the `FlowRegistry.flows` map and the corresponding `flowEntry`.

cc. @yuzefovich do you have ideas about how we can improve the structure of this function?

**Comment by yuzefovich** [comment]
Thanks for the comprehensive write-up Nathan! I looked into this code, and I think you're correct that we can be more careful with holding the global mutex. As the code is written currently that mutex protects three things (you mentioned first two):
- `flows` map
- `flowEntry` objects
- `InboundStreamInfo` objects.

I think that if we give to `InboundStreamInfo` each own mutex, the things will be easier to simplify. I'm working on that in #72998.
