### ISSUE TITLE
sql: OID of STRING(n) should be varchar

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#72979]
CRDB provides a width-limited string type, `STRING(n)`. When this type is created, it is given the `text` OID:

```
defaultdb> select pg_typeof('foo'::STRING(1));
  pg_typeof
-------------
  text
```

In Postgres, there is no width-limited `text` type, but there is a width-limited `varchar`. So, I think the OID of a `STRING(n)` should be `varchar`.

Below is a table that shows my proposed mapping from CRDB types to OIDs.

CRDB Type | OID
------------|----
`STRING`   | `text`
`STRING(n)` | ~`text`~ `varchar`

Jira issue: CRDB-11364

**Comment by otan** [comment]
This will be a quite involved fix if we decide to do this, as we'd probably want to migrate existing columns to follow suit, i.e. pre-22.1 versions that have:

```
CREATE TABLE tbl (
   a STRING(5),
   ....
)
```

**Comment by rafiss** [comment]
I wonder if it's possible to only update the OID that is reported in the pgwire RowDescription, and not try to change anything in the descriptors. (an idea for whenever we come back to this)

**Comment by otan** [comment]
actually adding something (permanently) to https://github.com/cockroachdb/cockroach/blob/ced473fa0ed00660812a6f6678155fb30e6a871f/pkg/sql/types/types.go#L2102 may be ok

**Comment by mgartner** [comment]
Changing this at the pgwire layer is fine, but doesn't solve the root issue. See this TODO (which looks like I used the wrong issue number for): 

https://github.com/mgartner/cockroach/blob/4c5f7326ee9db6ac25f431a4cf0b9c9df7ca6ec2/pkg/sql/sem/tree/cast.go#L856-L866

**Comment by mgartner** [comment]
I guess never fixing this wouldn't be terrible. I think the only thing it would fix is removing the `TEXT::TEXT` cast in `pg_cast`.
