### ISSUE TITLE
cli: support `ndjson` output format for `sql` command

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#73022]
When running a SQL statement via the `cockroach sql -e` command, the output format can be specified with `--format`. It would be nice if we supported either NDJSON or JSON here, e.g.:

```
$ cockroach sql -e 'SELECT id, value FROM table` --format ndjson
{"id": 1, "value": "a"}
{"id": 2, "value": "b"}
{"id": 3, "value": "c"}
```

Jira issue: CRDB-11388

**Comment by ajwerner** [comment]
For years I've been `python3 -c 'import sys,csv,json; [*filter(print, map(json.dumps, csv.DictReader(sys.stdin)))]'` this snippet with the `--csv` format. This is so civilized! 😍
