### ISSUE TITLE
zoneconfig,sql/catalog: ensure dynamic system tables support rangefeeds

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#73045]
**Is your feature request related to a problem? Please describe.**

Today, all system tables offer rangefeeds. This is helpful for implementing various caching primitives on top of these tables. Rangefeeds are not enabled by default on all ranges. Instead, there's a cluster setting and then a hard-coded configuration which enables rangefeeds for all ranges which contain a system table. 

See https://github.com/cockroachdb/cockroach/blob/d7094d71759db186d7ba5a163e1d95c206d6568b/pkg/kv/kvserver/replica_rangefeed.go#L150-L153

**Describe the solution you'd like**

I'd like to delegate control of whether or not rangefeeds are enabled to the zoneconfig/spanconfig infra (see [#70614 (comment)](https://github.com/cockroachdb/cockroach/issues/70614#issuecomment-956903381)). Then we should enable these rangefeeds in the system database unconditionally. Perhaps we need to enable them by default to make sure that there is not a gap when they are not available.

**Describe alternatives you've considered**
We could make sure that all system tables which need rangefeeds have a small ID, but that seems tough given how quickly we're running out of IDs.

**Additional context**

This is made pressing due to the exhaustion of descriptor IDs. See https://github.com/cockroachdb/cockroach/issues/57531. 

Epic: CRDB-10772

**Comment by irfansharif** [comment]
Is this issue a specific version of https://github.com/cockroachdb/cockroach/issues/70614? (https://github.com/cockroachdb/cockroach/issues/70614#issuecomment-956903381)

**Comment by ajwerner** [comment]
> Is this issue a specific version of #70614? ([#70614 (comment)](https://github.com/cockroachdb/cockroach/issues/70614#issuecomment-956903381))

🤦 the link in the solutions was supposed to be to that issue, updated. Indeed, but with a few more considerations and a direct tie-in to #57531.

**Comment by ajwerner** [comment]
https://github.com/cockroachdb/cockroach/pull/73754 is making the check whether a range is a system range more expensive as part of #57531. We'll need to do something here for 22.1.
