### ISSUE TITLE
changefeedccl: PTS records and on_error=pause

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#73041]
Observation on PTS records, and on_error=pause  functionality:  This option helps in a case when  changefeed receives an error that it doesn’t know how to handle (i.e. a non-retryable error).  However, where it does not help (and, this was of course observed by customer) — is the case when one of the servers is having persistent problems — perhaps it’s flapping and restarting… So, if it happens that for gc.ttl seconds we are getting transient errors, we would fail but we won’t be able to protect the record… This seems like an omission.  Perhaps we should be protecting data if we can’t checkpoint new high water mark (or more generally, not making forward progress)…

Jira issue: CRDB-11390

**Comment by amruss** [comment]
Linking this issue on configurable retries as I think there is a lot of overlap: https://github.com/cockroachdb/cockroach/issues/67984

**Comment by amruss** [comment]
Closing due to trailing protected timestamp work
