### ISSUE TITLE
Add details about hash-sharded attributes to crdb_internal.table_indexes table

### ISSUE THREAD

**Issue by jhatcher9999** [cockroachdb/cockroach#73057]
**Is your feature request related to a problem? Please describe.**
I want to be able to find out which indexes in a database are hash-sharded and how many buckets the index is using.

**Describe the solution you'd like**
I'd like to be able to query the table_indexes table in crdb_internal to get details about the hash-sharded attributes.
Currently, I get this set of fields:
```
root@localhost:26257/prod> select * from crdb_internal.table_indexes limit 1;
  descriptor_id | descriptor_name | index_id |    index_name     | index_type | is_unique | is_inverted
----------------+-----------------+----------+-------------------+------------+-----------+--------------
           2301 | table1000000    |        2 | table1000000_idx  | primary    |   true    |    false
```

**Describe alternatives you've considered**
I think I could query the `create table` statement and do some fancy pattern matching.  I also tried doing `show indexes from table_name` but it doesn't have any HSI info either.

**Additional context**
I'm doing my testing on 21.1.9.  If this feature has been added in later versions, I haven't checked.

Epic CRDB-7363

**Comment by smcvey** [comment]
Can we expand the scope of this request to include the type of index in general, e.g: 'partial', 'hash-sharded', 'inverted' etc?

**Comment by vy-ton** [comment]
I initially tied this to the work to make hash-sharded indexes full support, but to @smcvey point about index observability @kevin-v-ngo is this something you've seen or considered?

**Comment by rafiss** [comment]
Related to https://github.com/cockroachdb/cockroach/issues/73060
