### ISSUE TITLE
bazel: add custom `shadow` Analyzer that ignores `err` shadowing

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#73069]
We are currently [not running the `shadow`](https://github.com/cockroachdb/cockroach/blob/master/BUILD.bazel#L227) check on the Bazel build via `nogo`, but we'd like to. However, the `Analyzer` by default reports *all* shadows, while we [would like to ignore shadows](https://github.com/cockroachdb/cockroach/blob/db6851bfaa39e3099d4c5289e61adf127bed342d/pkg/testutils/lint/lint_test.go#L2079) of the variable `err` of `pErr` which are generally benign. Presumably we should do something like in [MungeAnalyzer](https://github.com/cockroachdb/cockroach/blob/master/pkg/testutils/lint/passes/staticcheck/staticcheck.go): export the `Analyzer` in a new package, but update the `Run` function to throw away failures due to shadows of `err` or `pErr`.

Epic CRDB-8306

Jira issue: CRDB-11404

**Comment by ajwerner** [comment]
We should consider also allowing `ctx` to be shadowed.
