### ISSUE TITLE
DBConsole - Sort order of Application list on Statements page

### ISSUE THREAD

**Issue by cjireland** [cockroachdb/cockroach#73108]
**Is your feature request related to a problem? Please describe.**
Currently the Application drop down list on the Statements page appears in a random order. This makes it cumbersome to find the item of interest.

**Describe the solution you'd like**
Please can the list be sorted:

1. All
2. (internal)
3. (unset)
4. Everything else in alphabetical order (maybe also case insensitive)

**Comment by maryliag** [comment]
With the new changes to use a multi selected, the app names are now ordered

<img width="279" alt="Screen Shot 2021-12-16 at 10 17 21 AM" src="https://user-images.githubusercontent.com/1017486/146398228-68d26238-66a9-4c54-969e-1df3c7133904.png">
