### ISSUE TITLE
pgx Ping() appears to report success even when all nodes in region are down

### ISSUE THREAD

**Issue by JuanLeon1** [cockroachdb/cockroach#73113]
**Describe the problem**

This is a follow up from a cloud customer DR test.  Salto (the customer) had us bring down their nodes in one region (europe-west1 but this is probably irrelevant) to test the resilience of their app stack.   They use pgx, and its Ping(), to determine when they need to move away from a region.  We brought down all the nodes, but PIng() to the region was not reporting any errors.  However, "SELECT VERSION();" was returning an error.  Ping() issues a blank SQL command (";").  

**To Reproduce**

Issued pgx's Ping() releatedly while bringing down all nodes .

If possible, provide steps to reproduce the behavior:

**Expected behavior**
I expect pgx Ping() to fail when the database nodes are not available

**Additional context**
Customer is replacing the use of pgx.Ping() but they would like to know why they have this problem with CRDB and not postgress.  Also, other customers may be running into this.   But issue is not urgent.  We have not tried to reproduce the problem in a minimal configuration.  Not sure I have selected the right team to be the target of this issue.

Jira issue: CRDB-11431

**Comment by rafiss** [comment]
Closing as we haven't heard updates on this since November and there does not appear to be any ongoing problem or reproduction.
