### ISSUE TITLE
jobs: mitigate contention by job scheduler daemon

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#73133]
With lots of SQL nodes, we get lots of daemons fighting over not very many scheduled jobs and getting backed up. We should mitigate this through some combination of jitter, coordination, and `select ... for update nowait`.

Another symptom to address is `SHOW JOBS` or `SHOW SCHEDULES` being blocked on transactions.

- [x] https://github.com/cockroachdb/cockroach/pull/73191
  - [x] https://github.com/cockroachdb/cockroach/pull/73251 
- [x] https://github.com/cockroachdb/cockroach/pull/73319
  - [x] https://github.com/cockroachdb/cockroach/pull/76802, should be in v21.2.7 
- [x] Consider removing join between schedules and jobs, based on this [internal conversation](https://cockroachlabs.slack.com/archives/C02DSDS9TM1/p1645137932162409?thread_ts=1645136135.920799&cid=C02DSDS9TM1) https://github.com/cockroachdb/cockroach/blob/52c2df4fb00d943328dc59df9dc210a40a556ab2/pkg/jobs/job_scheduler.go#L86

gz#10521

Jira issue: CRDB-11437

**Comment by stevendanna** [comment]
I like the ideas here.

If we end up needing another one (unlikely), a method I've used successfully in the past is to also make the wait time dynamic based on the currently scheduled jobs.  The only worry with that approach is oversleeping for newly scheduled jobs, but a combination of a maximum wait time, relatively broad jitter, and waking up the scheduler on the node that added the scheduled job was typically sufficient to still schedule the job in a relatively timely fashion.

**Comment by miretskiy** [comment]
Fwiw, i have my doubts about the nowait approach. In particular, it does
not help with show schedules command

**Comment by HonoreDB** [comment]
We could unblock Show Schedules by making it a bounded staleness read, but that's kind of treating the symptom rather than the root cause.

**Comment by miretskiy** [comment]
MOving to bulkio -- they will own fixing backup planning by moving most of the work to the execution phase.

**Comment by shermanCRL** [comment]
Shall we close this?

**Comment by miretskiy** [comment]
I think so

**Comment by stevendanna** [comment]
We have a good amount of jobs work to do.  The ideas listed here were taken care of. I'm closing this. We'll address specific sources of contention in the future as they arise.
