### ISSUE TITLE
prod: followed the docker start cluster documentation and nodes didn't join

### ISSUE THREAD

**Issue by spullara** [cockroachdb/cockroach#7316]
```
sam$ docker ps
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS                                               NAMES
0eda010a44ff        cockroachdb/cockroach:beta-20160616   "/cockroach/cockroach"   15 minutes ago      Up 15 minutes       0.0.0.0:32771->8080/tcp, 0.0.0.0:32770->26257/tcp   roach3
73a8b48cc378        cockroachdb/cockroach:beta-20160616   "/cockroach/cockroach"   16 minutes ago      Up 16 minutes       0.0.0.0:32769->8080/tcp, 0.0.0.0:32768->26257/tcp   roach2
f6940d4ef188        cockroachdb/cockroach:beta-20160616   "/cockroach/cockroach"   16 minutes ago      Up 16 minutes       0.0.0.0:8080->8080/tcp, 0.0.0.0:26257->26257/tcp    roach1
```

Still shows 1 node on the cluster admin page:

https://www.dropbox.com/s/g9268udf4ewb0nb/Screenshot%202016-06-17%2015.52.49.png?dl=0

Not seeing anything in the logs:

```
newmacpro:lambdas sam$ docker logs 0eda010a44ff
newmacpro:lambdas sam$ docker logs 73a8b48cc378
newmacpro:lambdas sam$ docker logs f6940d4ef188
build:     beta-20160616 @ 2016/06/16 16:50:55 (go1.6.2)
admin:     http://roach1:8080
sql:       postgresql://root@roach1:26257?sslmode=disable
logs:      cockroach-data/logs
store[0]:  path=cockroach-data
```

**Comment by petermattis** [comment]
@jseldess Who did you work with to generate these docker setup instructions? Mind working with them again to see what is going wrong? I just took a look at the acceptance tests and they are following a very similar pattern, and yet those tests manage to set up multi-node clusters successfully.

**Comment by jseldess** [comment]
@spullara, did you run the commands on `start-a-local-cluster-in-docker.md` exactly, or were there some changes? Would you mind providing all your commands? Copy/paste is fine. 

@petermattis, both @tamird and @bdarnell helped at different times. I'll loop them in once I've rerun @spullara's steps.

**Comment by tamird** [comment]
I just ran through these steps again locally and they worked just fine.

**Comment by petermattis** [comment]
@tamird Curious. I copy&pasted the instructions and they didn't work. Not sure if it is important:

```
~/Development/go/src/github.com/cockroachdb/cockroach master docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   5604cbe
 Built:        Wed Apr 27 15:27:26 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64
~/Development/go/src/github.com/cockroachdb/cockroach master docker-machine version
docker-machine version 0.7.0, build a650a40
```

**Comment by tamird** [comment]
```
$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   b9f10c9
 Built:        Thu Jun  2 03:53:12 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64
```

**Comment by jseldess** [comment]
I just ran through again, and it worked fine for me. Admin UI shows 3 nodes. And my docker version:

```
jesseseldess@JESSEs-MacBook-Pro:~$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64
```

**Comment by jseldess** [comment]
@petermattis, interested in seeing exactly what's happening for you. All three nodes are starting up fine in separate containers but not joining?

**Comment by petermattis** [comment]
Upgrade to docker `1.11.2` (client and server). Still no love. The `roach{2,3}` logs show:

```
I160620 15:53:53.892915 gossip/gossip.go:923  starting client to roach1:26257
I160620 15:53:56.893780 /go/src/google.golang.org/grpc/clientconn.go:351  Failed to dial roach1:26257: grpc: timed out trying to connect; please retry.
```

**Comment by bdarnell** [comment]
The instructions work for me too (on docker 1.10.1). @petermattis, what does `docker network inspect roachnet` say for you?

**Comment by petermattis** [comment]
```
~ docker network inspect roachnet
[
    {
        "Name": "roachnet",
        "Id": "f426b9a75a4d3f249957649ea7e09b585cefa567423340b517889565877a5467",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1/16"
                }
            ]
        },
        "Internal": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]
```

**Comment by bdarnell** [comment]
You should be seeing an entry for each of the containers there. They're somehow not getting attached to the right network. Last time I wrestled with this, docker networking had some weird bugs - it would sometimes let you create two networks with the same name, and  then nothing would really work afterwards. I don't have any suggestions about what to do besides deleting all the networks and containers and starting over.

**Comment by petermattis** [comment]
Heh, I didn't have the containers running:

```
~ docker network inspect roachnet
[
    {
        "Name": "roachnet",
        "Id": "f426b9a75a4d3f249957649ea7e09b585cefa567423340b517889565877a5467",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1/16"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "1b278b5822554927e9231b86dca0f70a6ba17438a6c45777ff7181ccc73bc657": {
                "Name": "roach2",
                "EndpointID": "9257c55c7ad370a10c493a018d2c84530eac9fb4637c5325379cdd09270317b3",
                "MacAddress": "02:42:ac:12:00:03",
                "IPv4Address": "172.18.0.3/16",
                "IPv6Address": ""
            },
            "27aacfcd6659cb54ea539293fc3bb974c555136c28de0001ad5926359f94645f": {
                "Name": "roach3",
                "EndpointID": "58fe3b24d2d9b928302c365db3fdc0b475e4457885959c5a0457cb3f9ba59392",
                "MacAddress": "02:42:ac:12:00:04",
                "IPv4Address": "172.18.0.4/16",
                "IPv6Address": ""
            },
            "7ad08edac5017f5e2a92c1eff066425da9b7e2e34df0031a34fb8822516af74a": {
                "Name": "roach1",
                "EndpointID": "c0ff6b0e2ea9218ad31dbb59f3eab1592168ae70a9839ea2f64e43154139c050",
                "MacAddress": "02:42:ac:12:00:02",
                "IPv4Address": "172.18.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```

I've tried deleting and recreating the network several times. Perhaps I should try recreating the docker machine.

**Comment by spullara** [comment]
I just cut/pasted as it was in the document. I'm using the Docker Beta for Mac if that matters. Just tried it at another computer and it worked. Not clear what happens on some installs.

sam$ docker version
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   a7119de
 Built:        Fri Jun 17 22:09:20 2016
 OS/Arch:      linux/amd64
 Experimental: true

**Comment by bdarnell** [comment]
@petermattis OK, that's pretty much what it looks like for me. (in particular neither of us have ipv6 enabled, which I was suspecting as a possible difference).

**Comment by jseldess** [comment]
@spullara, our instructions for Mac assume you're running the containers in a `docker-machine`. With Docker Beta for Mac, you run containers directly on the Mac, is that right? Perhaps this is a factor here, but since @petermattis is seeing the same behavior, perhaps not. I'll download and test it out in the Beta as well.

**Comment by spullara** [comment]
Both systems I tried it on were using Docker for Mac beta. Worked on one but not another.

**Comment by tschottdorf** [comment]
I don't know whether it's related, but try `docker network ls`. I think I
saw issues where if, for some reason, the network is created twice with
identical names, it will pick one at random (or maybe even mostly the wrong
one).

On Mon, Jun 20, 2016 at 2:08 PM Sam Pullara <notifications@github.com>
wrote:

> Both systems I tried it on were using Docker for Mac beta. Worked on one
> but not another.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/7316#issuecomment-227222148>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE135KY5IerbGOmRueTD7ImjDp80RHdfks5qNtc0gaJpZM4I4ysa>
> .
>
-- 

-- Tobias

**Comment by petermattis** [comment]
@tschottdorf I only have one `roachnet` network. This error persisted across a docker version upgrade and a complete wipe and recreation of my `default` docker-machine. Happy to let someone poke around on my machine tomorrow.

**Comment by tamird** [comment]
@petermattis what about the other networks? I have:
```
$ docker network ls
NETWORK ID          NAME                DRIVER
d13be9dd15e6        bridge              bridge
54e22dcd5cdf        host                host
92edd451528b        none                null
dba514238592        roachnet            bridge
```

**Comment by petermattis** [comment]
@tamird That's exactly what I have (well, the `NETWORK ID`s are different).

**Comment by spencerkimball** [comment]
Closing for lack of repro (works fine for me). I assume Docker has improved things in the intervening releases. @petermattis since you had a faulty setup, could you test this and re-open, assign, etc. if necessary?
