### ISSUE TITLE
kvclient, changefeedccl: changefeeds can fail due to nodes being restarted; changefeeds can prevent drain

### ISSUE THREAD

**Issue by aayushshah15** [cockroachdb/cockroach#73201]
In https://github.com/cockroachlabs/support/issues/1303, we saw several changefeeds on a cluster fail due during an in-place upgrade cycle of the cluster where nodes were being drained and then restarted with a minor-version upgraded binary. 

From that issue, its unclear (to me) what exactly is happening since a bunch of the changefeeds failed with a context cancellation error wrapped inside a DistSender transport exhaustion error, which looks like the following: 
```
CHANGEFEED job ‹683783401840541761› returning with error: ‹failed to send RPC: sending to all replicas failed; last error: failed to connect to n228 at <ip>: context canceled›
```
When the operator attempted to restart these changefeeds, they instead failed with: 
```
failed to send RPC: sending to all replicas failed; last error: unable to dial n237: breaker open
```

We likely need to set up a reproduction and proceed from there.

Epic CRDB-11783

gz#10480

Jira issue: CRDB-11456

**Comment by tbg** [comment]
This issue also tracks this failure mode: https://github.com/cockroachlabs/support/issues/1392  which we (think we) saw again in https://github.com/cockroachlabs/support/issues/1918. In short, a node coordinating a changefeed will refuse to fully drain. That seems bad.

**Comment by shermanCRL** [comment]
Is this relevant? https://github.com/cockroachdb/cockroach/pull/90767

**Comment by jayshrivastava** [comment]
The issue in https://github.com/cockroachlabs/support/issues/1392 is that he changefeed coordinator prevents a node from being drained. This sounds like a severe bug which we should fix and backport. For https://github.com/cockroachlabs/support/issues/1918, we should confirm if the node which failed to be drained was in fact coordinating a changefeed (I'm not sure how to verify this). If so, then it's the same issue. 

I don't think https://github.com/cockroachdb/cockroach/pull/90767 is relevant. It doesn't specifically address a changefeed preventing a node from being shut down. Rather, it addresses the problem changefeed processors shutting down slowly when a node (which is not the changefeed coordinator) shuts down.

**Comment by jayshrivastava** [comment]
I also tried reproducing https://github.com/cockroachlabs/support/issues/1392 locally with a 3 node cluster on the current master branch. I killed the changefeed coordinator and it drained successfully. The changefeed job got picked up by one of the remaining nodes. 
```
cockroach.crlMBP-Y4G4593YF3MTQ2.jayants.2022-11-22T18_10_14Z.011212.log:I221123 17:56:18.503054 1 1@cli/start.go:854 ⋮ [n1] 1297  received signal 'interrupt'
cockroach.crlMBP-Y4G4593YF3MTQ2.jayants.2022-11-22T18_10_14Z.011212.log:I221123 17:56:18.508969 1 1@cli/start.go:897 ⋮ [n1] 1298  initiating graceful shutdown of server
cockroach.crlMBP-Y4G4593YF3MTQ2.jayants.2022-11-22T18_10_14Z.011212.log:I221123 17:56:18.509024 426035 1@server/drain.go:344 ⋮ [n1,server drain process] 1299  waiting for health probes to notice that the node is not ready for new sql connections
cockroach.crlMBP-Y4G4593YF3MTQ2.jayants.2022-11-22T18_10_14Z.011212.log:I221123 17:56:18.509095 426035 sql/sqlstats/persistedsqlstats/flush.go:71 ⋮ [n1,server drain process] 1300  flushing 27 stmt/txn fingerprints (215040 bytes) after 1.042µs
cockroach.crlMBP-Y4G4593YF3MTQ2.jayants.2022-11-22T18_10_14Z.011212.log:I221123 17:56:19.136100 426035 1@server/drain.go:292 ⋮ [n1,server drain process] 1301  drain remaining: 46
cockroach.crlMBP-Y4G4593YF3MTQ2.jayants.2022-11-22T18_10_14Z.011212.log:I221123 17:56:19.136145 426035 1@server/drain.go:294 ⋮ [n1,server drain process] 1302  drain details: descriptor leases: 45, liveness record: 1
cockroach.crlMBP-Y4G4593YF3MTQ2.jayants.2022-11-22T18_10_14Z.011212.log:I221123 17:56:19.337227 426035 sql/sqlstats/persistedsqlstats/flush.go:71 ⋮ [n1,server drain process] 1303  flushing 0 stmt/txn fingerprints (0 bytes) after 1.041µs
cockroach.crlMBP-Y4G4593YF3MTQ2.jayants.2022-11-22T18_10_14Z.011212.log:I221123 17:56:19.348161 339 kv/kvserver/replica_proposal.go:270 ⋮ [n1,s1,r2/1:‹/System/NodeLiveness{-Max}›,raft] 1304  new range lease repl=(n1,s1):1 seq=29 start=1669140614.870403000,0 exp=1669226188.340094000,0 pro=1669226179.340094000,0 following repl=(n1,s1):1 seq=29 start=1669140614.870403000,0 exp=1669226183.692086000,0 pro=1669226174.692086000,0
cockroach.crlMBP-Y4G4593YF3MTQ2.jayants.2022-11-22T18_10_14Z.011212.log:I221123 17:56:19.352348 426035 1@server/drain.go:292 ⋮ [n1,server drain process] 1305  drain remaining: 0
cockroach.crlMBP-Y4G4593YF3MTQ2.jayants.2022-11-22T18_10_14Z.011212.log:I221123 17:56:19.352695 459 sql/stats/automatic_stats.go:509 ⋮ [n1] 1307  quiescing auto stats refresher
cockroach.crlMBP-Y4G4593YF3MTQ2.jayants.2022-11-22T18_10_14Z.011212.log:W221123 17:56:19.352790 416 sql/sqlliveness/slinstance/slinstance.go:307 ⋮ [n1] 1308  exiting heartbeat loop
cockroach.crlMBP-Y4G4593YF3MTQ2.jayants.2022-11-22T18_10_14Z.011212.log:W221123 17:56:19.352810 416 sql/sqlliveness/slinstance/slinstance.go:292 ⋮ [n1] 1309  exiting heartbeat loop
cockroach.crlMBP-Y4G4593YF3MTQ2.jayants.2022-11-22T18_10_14Z.011212.log:W221123 17:56:19.352821 465 jobs/registry.go:840 ⋮ [n1] 1310  canceling all adopted jobs due to stopper quiescing
cockroach.crlMBP-Y4G4593YF3MTQ2.jayants.2022-11-22T18_10_14Z.011212.log:I221123 17:56:19.352849 261622 jobs/registry.go:1253 ⋮ [n1] 1311  AUTO SPAN CONFIG RECONCILIATION job 814741116421177345: stepping through state succeeded
cockroach.crlMBP-Y4G4593YF3MTQ2.jayants.2022-11-22T18_10_14Z.011212.log:E221123 17:56:19.352936 261622 jobs/registry.go:716 ⋮ [n1] 1312  error getting live session: ‹node unavailable; try another peer›
cockroach.crlMBP-Y4G4593YF3MTQ2.jayants.2022-11-22T18_10_14Z.011212.log:I221123 17:56:19.369809 1 1@cli/start.go:951 ⋮ [n1] 1313  server drained and shutdown completed

```

**Comment by miretskiy** [comment]
I think this issue can be closed? or at least, I'm completely out of context here.
Lots of changes in the error handling in changefeeds recently... I wonder if this is still a problem.
Closing for now, but feel free to reopen.
