### ISSUE TITLE
roachprod: logs for parallel roachtests make it to console

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#73234]
Before (the librarification of roachprod, I assume), logs from roachtest's invocation of `roachprod` would not make it to stdout if multiple tests were running in parallel. Now they seem to do, and it's messy.
When using `roachtest --parallelism=<n> ...`, most logs are redirected away from stdout. I can dig out the info on this if necessary. Invocations of external binaries (like `roachprod` used to be) were also redirected.

**Comment by andreimatei** [comment]
Friendly ping. This is a significant quality of life regression for me.

**Comment by healthy-pod** [comment]
It's next on my list, just waiting to merge #73607. I am hoping I will get it done before Thursday (my last day), but if not I will open a PR with my changes so the team can catch up from where I leave it.
