### ISSUE TITLE
multitenant,security: improve certificate handling UX for tests

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#73256]
**Is your feature request related to a problem? Please describe.**

We currently embed a static set of certs for testing purposes. They correspond to tenants with IDs 10, 11 and 20. 

https://github.com/cockroachdb/cockroach/blob/41ffd133d3f6a2e55ce2bfa17999aebe4f968a54/pkg/security/tls.go#L38-L40

All our existing multi-tenant tests work only with some subset of these three tenants. There are no testing primitives to programatically generate these certs, or alternatively, a testing knob to bypass all relevant certificate checks to obviate such a need (not sure if the latter is possible/reasonable). This lack is sorely felt when programatically spinning up and tearing down arbitrary tenants in tests.

**Describe the solution you'd like**

See above.

Jira issue: CRDB-11499

**Comment by irfansharif** [comment]
@tbg says we should probably just create enough certs to go around and call it a day. Maybe for tenants with IDs 2-100.

**Comment by knz** [comment]
cc @jtsiros for tracking

**Comment by knz** [comment]
We discussed this and decided that we'd just add more tenant certs as needed for new tests. The process for doing so is sufficiently straightforward. (There's also the fallback of using insecure more)
