### ISSUE TITLE
cdc: revisit billing model for serverless in context of changefeed usage

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#73268]
Right now the serverless model for RU usage may not fully account for changefeed edge cases, we should revisit this RU model, including accounting for bytes read via catchup scans & rangefeed publishing/buffers.

Context: https://cockroachlabs.slack.com/archives/CUVEFUU3C/p1635268558145300 
More details on catchup scans: https://docs.google.com/document/d/1OPzDtp9t1wTvX0bHFCkU-XRltf8s30iUmC47g3WtL50/edit#bookmark=id.itduknbc0yq8

Epic CRDB-8671

Jira issue: CRDB-11502

**Comment by ajstorm** [comment]
Removing this from the multi-tenant board, as it's focused on serverless.  The multi-tenant board is focused on issues around parity between single tenant and multi-tenant CRDB.
