### ISSUE TITLE
cdc: expand testing coverage of changefeeds in a serverless environment

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#73269]
Today we run a subset of our cdc tests ~20% of the time in a multi tenant environment. We should expand coverage of this to include:
- We currently have some tests that assert that changefeeds fail in some multi-tenant configurations, but we’ll likely want to add some testing asserting that they work. 
- Tests that involve protected timestamps
- Other testing gaps we discover

We should also follow up with test infra & CC team on: Making sure our testing configuration closely matches what is deployed.

Epic CRDB-8671

Jira issue: CRDB-11503

**Comment by miretskiy** [comment]
@samiskin  any specific work planned on this? If not, feel free to close the issue
(unless @amruss says otherwise)

**Comment by samiskin** [comment]
This was handled with the "randomly run all tests on either secondary or system tenant when possible" part of the unit test refactor
