### ISSUE TITLE
server: allow DB Console http requests to proxy to other nodes in the cluster

### ISSUE THREAD

**Issue by dhartunian** [cockroachdb/cockroach#73285]
Deployments of CRDB clusters behind a load balancer often lose the ability to easily access arbitrary nodes via HTTP. This feature would allow a DB Console user to route their data requests to a node of their choice to easily access telemetry and information from arbitrary nodes without having a direct HTTP connection to it through their browser.

This implementation should transparently proxy the request to another node either via an HTTP header like:

```
X-crdb-node-id: 123
```

Or a query parameter like:

```
https://my-cluster.com:8080/_status/vars?node_id=123
```

Epic CC-5167

**Comment by petermattis** [comment]
Many CRDB endpoints take the node-id as a parameter in the path. For example, `/_status/logfiles/{node_id}`, `/_status/files/{node_id}`, and `/_status/metrics/{node_id}`. Is there a reason to be using a new syntax rather than following this precedent?

**Comment by dhartunian** [comment]
@petermattis This is a more generic feature to proxy arbitrary requests to a node of your choice. I agree that a request like `/_status/logfiles/123?node_id=456` is a bit nonsensical but my intention is to enable the UI to easily switch to a node of your choice while using DB Console and to enable routing requests like `_status/vars` to arbitrary nodes through a generic proxy mechanism. Through this we can continue serving the DB console via a load balancer while allowing for requests to target specific nodes when necessary.

In my implementation PR that I just linked I've implemented "pinning" your session to a node via a cookie so the UI doesn't have to change how requests are constructed.

You do make a good point that this feature could be redundant w/r/t those endpoints. Hm, those node-specific info requests can be served by any node in most cases. In the case of this new feature the request would result in an additional network hop every single time.

**Comment by petermattis** [comment]
Thanks for the context. You could place the node ID in the path if you placed it at a known location (e.g. `/_status/{node_id}/logfiles`). I'm not sure if this is significantly harder for DB console to deal with. The UI would definitely have to have additional knowledge about how requests are constructed. The query parameter or HTTP header avoids that, though I'm not clear on why that is desirable. Is it merely about layering in the UI code?

**Comment by dhartunian** [comment]
> The query parameter or HTTP header avoids that, though I'm not clear on why that is desirable. Is it merely about layering in the UI code?

My intent is to support:
- Query params for one-off routing to a specific node. This is specifically targeting things like using `_status/vars` behind the load balancer where you make your request outside a browser.
- Header/Cookie-based routing when you want to "pin" your DB Console session temporarily to a specific node while debugging. This is handy because it allows us to flow requests to a node from the browser without modifying the path construction. We've already built a one-off feature for routing pprof requests to a specific node but this would be a generalized solution. You get some interesting features from this like the ability to serve the DB Console assets from the remote node. So for instance if you have a mixed version cluster you could load the DB Console JS from the remote node if the two had incompatibilities.

I agree both of the above cases can be handled through modification of the URL. Let me think more about whether this might be more straightforward to implement. I kinda dismissed it out of hand because I didn't want to create a lot of new URL patterns but maybe there aren't as many prefixes as I thought.
