### ISSUE TITLE
jobs: add cluster setting to enable job scheduler daemon on select nodes in a cluster

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#73304]
Today, all nodes on cluster startup will run their own scheduler daemons. This is a feature request to add a cluster setting that allows the user to specify which nodes in the cluster should run a daemon responsible for picking up and executing scheduled jobs. This provides us with an escape hatch in a scenario where a cluster with several nodes, each running their own daemon, contend with each other to run the same schedule. This results in concurrent planning of the same job which is expensive and wasteful.

One idea is to have the setting take a list of node IDs. This is slightly brittle because the nodeID can change if nodes are decommissioned or added into the cluster. Another idea was to have the setting search for the `meta1` leaseholder and only have that node run the daemon. Both approaches should be relatively lightweight and non-invasive.

Jira issue: CRDB-11529

**Comment by miretskiy** [comment]
I don't think we'll ever do this.
I'm going to un-assign myself, and close this issue, but feel free to reopen if you are inclined
(@dt @adityamaru )
