### ISSUE TITLE
kv: add placeholders to ALTER RANGE RELOCATE

### ISSUE THREAD

**Issue by lunevalex** [cockroachdb/cockroach#73315]
#72305 introduced a new ALTER RANGE RELOCATE syntax to move leases and replicas around. The syntax does not support placeholder values for the range/store ids. This issue is to track to extending the syntax to support placeholders. 

cc: @knz

**Comment by knz** [comment]
This could be an issue for the SQL xp team right?

**Comment by lunevalex** [comment]
It could be although I suspect, they will find a hard time prioritizing this, since it's mainly to be used by KV.

**Comment by knz** [comment]
I see. But then it's also "on hold" for KV now :)

**Comment by knz** [comment]
I'll try to do a thing about it
