### ISSUE TITLE
Restore database/table definitions without the data.

### ISSUE THREAD

**Issue by data-matt** [cockroachdb/cockroach#73310]
**Is your feature request related to a problem? Please describe.**
In a DR scenario, we would like to be able to return to normal production operations as soon as possible. We understand that when restoring a backup, it will take some time to restore the data. Therefore, we would like to be able to restore the database/table definitions/ddl/schema without the data. 

**Describe the solution you'd like**
Provide `RESTORE ... WITH schema_only=true`

**Describe alternatives you've considered**
Start the restore job and kill it.
AOST from a backup where the tables are empty. 

**Additional context**
Journal based activities, where we really need to write immediately. Its definitely an option for us to get operational asap.

Jira issue: CRDB-11532

**Comment by mwang1026** [comment]
Interesting idea! Wondering what the use case you have in mind is here?

**Comment by data-matt** [comment]
Journal based activities, where we really need to write immediately. Its definitely an option for us to get operational asap.

**Comment by livlobo** [comment]
A Schema-only restore is now supported - https://www.cockroachlabs.com/docs/stable/backup-validation.html#validate-backup-table-data-is-restorable
