### ISSUE TITLE
sql: allow `DROP DATABASE` on databases with empty public schemas

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#73323]
Once https://github.com/cockroachdb/cockroach/pull/72000

ensure we can `DROP DATABASE` on databases with an empty public schema without having to specify `CASCADE`

Jira issue: CRDB-11541

**Comment by ajwerner** [comment]
@RichardJCai what's up here?

**Comment by postamar** [comment]
This only affects the declarative schema changer.

**Comment by RichardJCai** [comment]
> @RichardJCai what's up here?

After the public schema migration, every database is considered non-empty cause there is one descriptor (public)

```
demo@127.0.0.1:26257/movr>
create database test;
CREATE DATABASE


Time: 8ms total (execution 8ms / network 0ms)

demo@127.0.0.1:26257/movr> drop database test;
ERROR: rejected (sql_safe_updates = true): DROP DATABASE on non-empty database without explicit CASCADE
SQLSTATE: 01000
```
