### ISSUE TITLE
ui,jobs: Jobs with reverting status are not shown in cluster ui jobs page.

### ISSUE THREAD

**Issue by data-matt** [cockroachdb/cockroach#73333]
**Describe the problem**

When an import job fails, any progress made must be reverted, this puts the jobs status to "reverting".

Currently our filter shows the following Status:

![image](https://user-images.githubusercontent.com/84391439/144227207-aa668a62-8f21-4f22-b6d8-1a119096674e.png)

It does not include the status "reverting"

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster
2. Import CSV
3. Wait for some progress for the import job
4. Cancel import job
5. Job will go into "reverting" 
6. Job will no longer appear in jobs view

**Expected behaviour**
Jobs no matter what status, including "reverting" should be shown in jobs view.

**Additional context**
Operators could not see the status of reverting jobs from DB Console for several hours, it could only be seen by looking at system.jobs table from SQL cli.

**Comment by data-matt** [comment]
Update, on 21.1+ I see the job reverting, the status is missing from the filter. 

Customer was on 20.2, so the issue may no longer exist.

**Comment by maryliag** [comment]
@jocrl can you confirm the changes you're currently making on the Jobs page are adding the filters?

**Comment by jocrl** [comment]
Yup, reverting will be added to the filters with https://github.com/cockroachdb/cockroach/pull/72291.
(Not sure if I should go ahead and close this; leaving it open)

**Comment by maryliag** [comment]
Let's keep this open and once your PR gets merged we can update here
