### ISSUE TITLE
sql: rename setting `disable_plan_gists` to `plan_gists_enabled`

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#73348]
This would be more consistent with all other setting names and avoid setting a bad precedent

Jira issue: CRDB-11552

**Comment by cucaroach** [comment]
Yeah I went back and forth on this and went with the default where the Go default value (false) gave us the behavior we wanted because of #70888.    I think I was following the precedent of "disable_partially_distributed_plans"

**Comment by rytaft** [comment]
Seems like that might have been a mistake too -- most other boolean settings end with `_enabled`, and I think that matches up with what was discussed here: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20170317_settings_table.md#naming-the-last-part

**Comment by mgartner** [comment]
I think the ship has sailed on this one. Closing.
