### ISSUE TITLE
statusccl: tesstrace timeouts in TestResetIndexUsageStatsRPCForTenant and TestTableIndexStats 

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#73359]
We are seeing frequent timeouts in `statusccl` under stressrace:
 - https://teamcity.cockroachdb.com//viewLog.html?buildId=3829045&buildTypeId=Cockroach_MergedExtendedCi
 - https://teamcity.cockroachdb.com//viewLog.html?buildId=3827225&buildTypeId=Cockroach_MergedExtendedCi
 - https://teamcity.cockroachdb.com//viewLog.html?buildId=3824143&buildTypeId=Cockroach_MergedExtendedCi

These tests finish in about a minute each locally (under testrace), so even a very slow system doesn't explain a 1 hour timeout.

**Comment by Azhng** [comment]
Hmm seems like our test harness is really expensive to setup/teardown. Perhaps all the tests can just share the same test harness. I'm testing that idea out in #73363
