### ISSUE TITLE
Add SHOW CREATE INDEX statement

### ISSUE THREAD

**Issue by lindseyjin** [cockroachdb/cockroach#73361]
**Is your feature request related to a problem? Please describe.**
As part of the new Index Details page, we show a CREATE INDEX statement. This statement is currently being accessed directly from the `pg_indexes` table. Since the SQL shell should have the same functionalities as the frontend UI, we should also add a way for users to view CREATE INDEX statements from there as well. 

**Describe the solution you'd like**
Add the ability to SHOW CREATE statements for indexes in the cockroach SQL shell.

**Additional context**

![image](https://user-images.githubusercontent.com/29153209/144335040-c3cfec85-41c2-40c0-82d7-6c90c2397627.png)

Jira issue: CRDB-11556

**Comment by ajwerner** [comment]
I'm sort of shrug on this. Like, I don't think up to now we've been very religious or consistent on the sql shell and the ui having a 1:1 conceptual mapping. What we've tried to say is that any data accessed from the ui can be accessed from sql. That's already the case here.

**Comment by lindseyjin** [comment]
> I'm sort of shrug on this. Like, I don't think up to now we've been very religious or consistent on the sql shell and the ui having a 1:1 conceptual mapping. What we've tried to say is that any data accessed from the ui can be accessed from sql. That's already the case here.

Hmm, in that case would you recommend closing this issue? Or just de-prioritizing it?

**Comment by vy-ton** [comment]
Lets keep it open for tracking. I moved it to the longer-term backlog

**Comment by maryliag** [comment]
No longer a priority
