### ISSUE TITLE
cockroachdb will not start

### ISSUE THREAD

**Issue by unprolix** [cockroachdb/cockroach#73366]
**Describe the problem**

The program will not start. On the attempt, I get one or two errors in the terminal as follows:

*
* ERROR: [n1] Queued as error 777cca74bb544844bc8aef54053535f5
*
*
* ERROR: [n1] Queued as error 357cf1d02a4e4160a20b8c7cc2c43761
*

**To Reproduce**

I try to start as I normally do:
$ bin/cockroach start --cache=.25 --certs-dir=var/certs --store=var/store --advertise-addr=bitume.blovi8.com:10100 --http-addr=localhost:10101 --join=bitume.blovi8.com:10100,bitume.cafemail.page:10100,mahi.blovi8.com:10100

If possible, provide steps to reproduce the behavior:

This is only happening with the existing node and does not occur when I start a new node using the same binary, e.g. `cockroach start-single-node --insecure`

**Expected behavior**

The server should start instead of stopping with an error.

**Additional data / screenshots**

[cockroach.log](https://github.com/cockroachdb/cockroach/files/7638746/cockroach.log)

other log files look normal.

**Environment:**
 - CockroachDB version v21.2.2
 - Server OS: debian (bookworm)
 - Client app: can't get to that stage

**Additional context**

Other nodes in the cluster start without issue

**Comment by yuzefovich** [comment]
The actual problem is the next line in the logs after `ERROR: [n1] Queued as error 777cca74bb544844bc8aef54053535f5`:
```
F211202 01:27:40.613269 300 1@server/server.go:331 ⋮ [n1] 43  clock synchronization error: this node is more than 500ms away from at least half of the known nodes (1 of 2 are within the offset)
```
CockroachDB will not run if it detects that the clocks between the nodes diverge by more than 500ms.

**Comment by unprolix** [comment]
Thanks! I was just looking at that as I updated the report with output from the current version and after having restarted the other nodes. The clocks looked right to me but I can probably figure out how to reset them. Off to try that...

**Comment by unprolix** [comment]
Okay, I've used `timedatectl status` (all three nodes are on debian) to verify that the times on all three nodes are very very close. So it looks like the clocks are correct. They *are* in different timezones though... but that hasn't changed in months, even if it does make a difference.

Not sure what to try next.

**Comment by unprolix** [comment]
Ok, well this is somewhat embarrassing but it looks like the problem had nothing to do with cockroachdb at all, but rather with networking on the machine malfunctioning in some way which, surprise, rebooting has fixed.

Sorry for the noise!
