### ISSUE TITLE
changefeedccl: enable enterprise changefeeds on serverless clusters

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#73429]
Currently, we give an error message when a user attempts to use the `CREATE CHANGEFEED` statement on a serverless cluster. We should remove that error message and let a user create a changefeed.

Epic CRDB-8671

Jira issue: CRDB-11584

**Comment by miretskiy** [comment]
do we still return an error? I thought we didn't;
@amruss  can you close this issue (or keep it open if I'm incorrect)
