### ISSUE TITLE
changefeedccl: add targets for changefeeds beyond tables

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#73435]
Today we only support changefeeds targeting tables. We should expand this (databases, partitions, indexes, etc.)

Epic CRDB-1421

Jira issue: CRDB-11589

**Comment by mitar** [comment]
Unstale.

**Comment by rharding6373** [comment]
Closing in favor of https://github.com/cockroachdb/cockroach/issues/93793 (database-level changefeeds) and https://github.com/cockroachdb/cockroach/issues/132277 (schema-level changefeeds), which are more specific
