### ISSUE TITLE
changefeedccl: persist changefeeds across backup/restore

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#73434]
When a user restores a database from a backup, information about running changefeeds is lost. We should persist changefeeds across databases that are restored, with the clear communication to users the changefeed data would be bounded by similar RPO limitations as backup data is.

Epic CRDB-11782

Jira issue: CRDB-11588

**Comment by miretskiy** [comment]
I don't think it's a good idea at any rate.
