### ISSUE TITLE
ui: better outdated version experience

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#7343]
Currently the "version outdated" or "version mismatch" text isn't very informative.

For an outdated version we should indicate:
- Which version they're on
- The latest version
- How many versions they are behind/how old their version is
- Any major enhancements (specifically security issues or breaking changes)
- More specific upgrading instructions tailored to their version

For mismatching version we should indicate:
- The version spread, including which nodes need to be updated
- Possibly a link to the docs to help people out

**Comment by maxlang** [comment]
cc @tamird

**Comment by tamird** [comment]
Also currently on master I see the `There is a newer version of CockroachDB available.` banner. That seems incorrect.

**Comment by maxlang** [comment]
The build tag needs to be updated or you'll see that outdated message.

**Comment by tamird** [comment]
What build tag?

**Comment by maxlang** [comment]
```
➜  ./cockroach version
Build Tag:   beta-20160629-364-g8b24f87
Build Time:  2016/07/14 15:36:42
Platform:    darwin amd64
Go Version:  go1.6.2
C Compiler:  4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)
```

**Comment by maxlang** [comment]
Wherever that build tag comes from

**Comment by tamird** [comment]
Update it to what? Can you use more words? They're cheap.

**Comment by maxlang** [comment]
When a new release is cut, the build tag needs to be updated to match the build tag on the registration server.

**Comment by tamird** [comment]
OK, but the original comment I left referred to `master`, not a released version.

**Comment by maxlang** [comment]
The buildtag on `master` should start with the latest released buildtag (cc @bdarnell )

**Comment by bdarnell** [comment]
Does it start with the right version if you do `git fetch --tags origin`? We're currently generating the build tag with some git magic. I'm not sure if there's an alternative way to do this that would be accurate (we don't know which commit will be released as the beta until after the fact).

**Comment by tamird** [comment]
Seem like it does. I've been using `git fetch --tags` for a while now, so I can't tell you if this is broken in the absence of running that routinely.

**Comment by bdarnell** [comment]
It's going to be tricky to handle this properly; we can't easily relate tag-less builds from source to their sequence in the release history. It's probably better to just hide this banner on builds without a proper build tag.

**Comment by mrtracy** [comment]
I've logged #14427 to capture the sub-issue here with custom built binaries - for developers on a custom build, this alert should not display at all.

I'm moving this issue to "Later", as aside from the custom binaries issue, this is more about enhancing the information provided by the alert.

**Comment by petermattis** [comment]
@mrtracy Is there anything left to do here?

**Comment by mrtracy** [comment]
I think everyone is fine with the current experience, closing.
