### ISSUE TITLE
dev: --rewrite support for parser tests returns error: cd: too many arguments

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#73452]
I'm trying to run the pkg/sql/parser datadriven tests with rewrite. But, I get an error, reproduced below, about "cd: too many arguments".

```
[17:02:1]% dev test pkg/sql/parser --rewrite                                                                    jordan@quar:~/go/src/github.com/cockroachdb/cockroach on insert-on-conflict-on-constraint
$ bazel test //pkg/sql/parser:parser_test --run_under 'cd /home/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/parser && ' --test_env=YOU_ARE_IN_THE_WORKSPACE=1 --test_arg -rewrite --test_output errors
INFO: Build options --run_under, --test_arg, and --test_env have changed, discarding analysis cache.
INFO: Analyzed target //pkg/sql/parser:parser_test (0 packages loaded, 14239 targets configured).
INFO: Found 1 test target...
FAIL: //pkg/sql/parser:parser_test (see /home/jordan/.cache/bazel/_bazel_jordan/21ede3155452841b83292c392e765927/execroot/cockroach/bazel-out/k8-fastbuild/testlogs/pkg/sql/parser/parser_test/test.log)
INFO: From Testing //pkg/sql/parser:parser_test:
==================== Test output for //pkg/sql/parser:parser_test:
/bin/bash: line 0: cd: too many arguments
================================================================================
Target //pkg/sql/parser:parser_test up-to-date:
  _bazel/bin/pkg/sql/parser/parser_test_/parser_test
INFO: Elapsed time: 1.051s, Critical Path: 0.15s
INFO: 2 processes: 2 linux-sandbox.
INFO: Build completed, 1 test FAILED, 2 total actions
//pkg/sql/parser:parser_test                                             FAILED in 0.0s
  /home/jordan/.cache/bazel/_bazel_jordan/21ede3155452841b83292c392e765927/execroot/cockroach/bazel-out/k8-fastbuild/testlogs/pkg/sql/parser/parser_test/test.log

INFO: Build completed, 1 test FAILED, 2 total actions
ERROR: exit status 3
```

Epic CRDB-8036

**Comment by jordanlewis** [comment]
Update: this is not just parser tests, it also doesn't work for optbuilder tests.

**Comment by rickystewart** [comment]
@jordanlewis: Presumably you're not using the top-level `./dev` script? That logic was removed in `c98a488cb2667410572e4f3c36bc37e7b97e14cf` back in October.

**Comment by jordanlewis** [comment]
What do you mean by the top level `./dev` script? See above for the commandline used, what was I doing wrong?

**Comment by rickystewart** [comment]
The commandline was:

```
[17:02:1]% dev test pkg/sql/parser --rewrite 
```

So you were calling into a `dev` into your `PATH`. I don't know where that was, but presumably you `go install`ed an old version of `dev`?

When I say the top-level `dev` script I mean [the script named `dev` at the top level of the repo](https://github.com/cockroachdb/cockroach/blob/master/dev). It builds `dev` (if necessary) and immediately executes it, so you don't have to keep an up-to-date version installed in your `PATH`.

**Comment by rickystewart** [comment]
I'd recommend always using the top-level `dev` script as it minimizes the chance of this skew occurring.

**Comment by jordanlewis** [comment]
Ah I see. thanks! Should we add this to `dev doctor` somehow?

**Comment by jordanlewis** [comment]
FWIW I have `cockroachdb/cockroach/bin/dev` in my path, I figured that binary would have stayed up to date.

**Comment by rickystewart** [comment]
Nah, not without making sure you re-build it. But as of #74571 the binaries now live in `bin/dev-versions/dev.*`.
