### ISSUE TITLE
dev: test with a nonexistant package path crashes with exit code 7

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#73457]
If I run dev test with a directory that doesn't exist, dev just exits with code 7 without an error message. Ideally, I'd like to see an error message that tells me what went wrong.

```
[18:02:1]% dev test pkg/blah                                                                                    
ERROR: exit status 7
```

 Epic CRDB-8036

Epic CRDB-8036

**Comment by rickystewart** [comment]
latest error message is more comprehensible, but still not ideal: 

```
cockroach$ ./dev test pkg/blah
ERROR: failed to run `bazel query 'kind(go_test, //pkg/blah:all)'` (exit status 7)
```
