### ISSUE TITLE
Backup database except certain tables

### ISSUE THREAD

**Issue by bladefist** [cockroachdb/cockroach#73526]
We have a database with lots of tables. The backup job takes over 10 hours now.  Incremental backup is not a good fit for us.   There are some massive tables in our database that don't need to be backed up, or, could be backed up individually less often.  

That leads me to my request to be able to backup a database and specify tables not to include.   

If did an opt-in model, we would potentially miss new tables added in the future and could be a costly mistake.  

Thanks!

**Comment by rafiss** [comment]
@bladefist thanks for filing this request! I think it might cover the same request as https://github.com/cockroachdb/cockroach/issues/57386. I'll close this one, but feel free to additional details about your use case there. And if this issue is different, feel free to re-open it.
