### ISSUE TITLE
sql: direction of Inverted Index Columns is not displayed in `SHOW CREATE TABLE`

### ISSUE THREAD

**Issue by chengxiong-ruan** [cockroachdb/cockroach#73533]
**Describe the problem**
In cockroach db, we do respect directions when storing inverted indexes. However, we don't show them with `SHOW CREATE TABLE` results. This is bad because we're giving out indication that direction doesn't matter for inverted indexes.

When formatting a AST node we do show it: http://github.com/cockroachdb/cockroach/blob/8b696d17241b2eb2d333e23750cf6fdc433897d8/pkg/sql/sem/tree/create.go#L147-L147

However this is dropped in `SHOW CREATE TABLE` for inverted index:
http://github.com/cockroachdb/cockroach/blob/8b696d17241b2eb2d333e23750cf6fdc433897d8/pkg/sql/catalog/catformat/index.go#L148-L148 

**To Reproduce**
```sql
create table t (
    id int primary key,
    note jsonb,
    nverted index idx_t_note (note)
);

select @2 as table_def from [ show create table t ];
                   table_def
-----------------------------------------------
  CREATE TABLE public.t (
      id INT8 NOT NULL,
      note JSONB NULL,
      CONSTRAINT t_pkey PRIMARY KEY (id ASC),
      INVERTED INDEX idx_t_note (note), -- direction is missing!
      FAMILY "primary" (id, note)
  )
```

**Expected behavior**
Show correction direction value for inverted indexes.

Jira issue: CRDB-11625

**Comment by yuzefovich** [comment]
@chengxiong-ruan you should add the issue to a project of the team that you think is the code owner.
