### ISSUE TITLE
sql,protectedts: mark tables as ephemeral to exclude them from backups

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#73536]
This is a tracking issue that captures an idea proposed by @dt.

Some users have encountered challenges with tables that contain high-churn, ephemeral data, where they want to GC history in that table quickly, but cannot simply configure it to do so because it is contained within a database, tenant or cluster that is backed up incrementally, which requires that history be preserved until that backup can back it up. 

In many such cases, the user does not actually explicitly desire data in these tables to be backed up at all, and are only doing so because it is part of the larger database, tenant or cluster being backed up. Thus one possible solution would be to provide a mechanism for a table like this to _opt out_ of inclusion in backups, freeing it to configure more aggressive GC without affecting the ability of its containing database to backup. Simply excluding the table entirely could be challenging -- it may still be referenced in jobs, logs, views, etc. However excluding its row data would allow the backup to succeed even if its that table's span has been GCed, and would result in it just being empty when restored.

Approach:

One proposed approach would be to mark a table as `ephemeral`. The simplest solution would be to store this information on the `TableDescriptor` but this does not work because of the way tenants are backed up. A `BACKUP TENANT` from the system tenant simply backs up a single-tenant span, and does not look inside the tenant to be able to exclude certain tables. Thus, this information needs to be written to the ZoneConfig, and will subsequently rely on the transport infrastructure that was introduced to support zcfgs in a multi-tenant environment.

The tasks can then largely be broken up into:

- [ ] Add `epehemeral` bit to ZoneConfig for a table, and the corresponding SpanConfig created as a result of reconciliation.

- [ ] Teach `ExportRequest` to return an empty `ExportResponse` when attempting to export a replica that has an assocaited `SpanConfig` marked as `ephemeral`.

- [ ] Teach GC to ignore any protected timestamp records that might be written to a replica that is marked as ephemeral. This way, even if a backup were to protect a set of schema objects that included the ephemeral table, it would allow the low GC TTL to continue garbage collecting the data.

- [ ] Add a migration to mark system tables that opt-out from a cluster backup as `ephemeral` so that they are never backed up or protected.

- [ ] Add SQL to set/unset a table as ephemeral. This might work out of the box with `ALTER ZONE CONFIGURATION`.

- [ ] Think about how to make the fact that a table is `ephemeral` observable to the user during a backup. To avoid surprises where they expect a table to be a part of the backup, but it is silently ignored. This might be solved via documentation, but it is worth calling out explicitly.

Epic: CRDB-10306

Jira issue: CRDB-11627

**Comment by shermanCRL** [comment]
Is this synonymous with exclusion? Is `ephemeral` a hint?

**Comment by adityamaru** [comment]
> Is this synonymous with exclusion? Is ephemeral a hint?
Yep, `epehemeral` is an indicator that will be used to determine if the row data is considered short-lived and should therefore not be backed up.

**Comment by adityamaru** [comment]
With the new protected timestamp subsystem potentially protecting schema objects instead of spans, there is an increased importance to addressing this issue. In particular, the new protection scheme is going to unlock the ability to chain protected timestamps between backups (https://github.com/cockroachdb/cockroach/issues/67282). By chaining protected timestamp records we decouple backup cadence from GC TTL which has been a longstanding thorn in our side. This way we can move to a future where cluster-wide TTLs do not have to default to 25 hours, and CRDB is not burdened by garbage buildup.

In this chaining future, we do not want to hold up GC on high churn tables with short TTLs for the duration of a backup.

**Comment by irfansharif** [comment]
The KV side of things LGTM, just a minor change for the MVCC GC queue.

**Comment by adityamaru** [comment]
Wondering if there is really a need to restrict this ephemeral bit to just tables? With the knew reconciler, if we were to set the ephemeral bit on the zone config of a database, it would propagate to the table span configs, and so both GC and ExportRequest would just skip for all tables in the database. This seems okay 🤷

**Comment by petermattis** [comment]
Naming nit: the term "ephemeral" suggests something beyond not including the table in backups. For example, I could imagine an "ephemeral" table as not surviving a cluster crash (in-memory only), or being automatically deleted after some time period. Unfortunately, I don't have a better suggestion than ephemeral. Did you consider trying to find a term/syntax that explicitly mentions "backup"?

**Comment by adityamaru** [comment]
> Did you consider trying to find a term/syntax that explicitly mentions "backup"?

We had a round of bikeshedding the term in this [internal thread](https://cockroachlabs.slack.com/archives/C2C5FKPPB/p1642624125070400), and similar concerns were brought up by @dt about `ephemeral` getting confused with `temporary` tables which we already support. The one argument against naming this something specific to backups is that we will be ignoring protected timestamps that apply to ephemeral ranges so as to not hold up GC on these high churn tables. CDC and the soon to be tenant to tenant streaming are also users of the protected timestamp subsystem (PTS). While they are initially going to configure the PTS records they write to **not** be ignored on ephemeral ranges, there might be a future where other systems want similar behavior as backups? Maybe it is okay to name it something backup specific, to begin with, and if and when we see a more general use case we can revisit the syntax.

**Comment by adityamaru** [comment]
There is a final PR required to teach the GC queue to ignore protection policies that apply to spans where:
`exclude_data_from_backup` introduced in https://github.com/cockroachdb/cockroach/pull/75295 && `ignore_if_excluded_from_backup` introduced in https://github.com/cockroachdb/cockroach/pull/76831 are both true. This can only happen once #73727 is complete, therefore marking it as a release blocker.
