### ISSUE TITLE
sql: create built-in function to detect violations of unique constraints

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#73560]
Due to the issue described in https://github.com/cockroachdb/cockroach/issues/73024, on 21.2.0, unique constraints on `REGIONAL BY ROW` tables may not be enforced. It would be helpful to have an easy way to detect violations of unique constraints, such as a built-in SQL function. This function could simply run a SQL query under the covers, similar to the one suggested for detecting violations in the [technical advisory](https://cockroachlabs.atlassian.net/browse/TSE-133) for #73024.

**Comment by nvanbenschoten** [comment]
How would this differ from `ALTER TABLE <t> VALIDATE CONSTRAINT <unique_constraint_without_index>`, which you previously added in support for in https://github.com/cockroachdb/cockroach/commit/de5c51401edc838abb2a31b1a216e55af579fff5. Is it just that you want a "force" option that skips the ["already validated" short-circuiting](https://github.com/cockroachdb/cockroach/blob/f41cd6e6b3600478eecd0eddf5befe51de06d542/pkg/sql/alter_table.go#L791-L793)?

**Comment by rytaft** [comment]
Sorry for the slow reply @nvanbenschoten!

> How would this differ from `ALTER TABLE <t> VALIDATE CONSTRAINT <unique_constraint_without_index>`, which you previously added in support for in [de5c514](https://github.com/cockroachdb/cockroach/commit/de5c51401edc838abb2a31b1a216e55af579fff5). Is it just that you want a "force" option that skips the ["already validated" short-circuiting](https://github.com/cockroachdb/cockroach/blob/f41cd6e6b3600478eecd0eddf5befe51de06d542/pkg/sql/alter_table.go#L791-L793)?

Yea, exactly. The idea is that this would be a simple way for customers to detect corruption due to #73024. But I'm also not 100% convinced the built-in is necessary if you see potential issues with it. We also opened https://github.com/cockroachdb/cockroach/issues/73632 to add unique constraint checks to SCRUB.

**Comment by nvanbenschoten** [comment]
> But I'm also not 100% convinced the built-in is necessary if you see potential issues with it.

I don't see any problems with it. I was just pointing out that we may already have 90% of the logic we'd want with `ALTER TABLE <t> VALIDATE CONSTRAINT <unique_constraint_without_index>`, so maybe we just need a `ALTER TABLE <t> VALIDATE (FORCE) CONSTRAINT <unique_constraint_without_index>` option.

**Comment by rytaft** [comment]
Good point -- I'll look into that as an option -- thanks!

**Comment by rytaft** [comment]
Just to follow up on this, I decided to go with the builtin function since it can be used to easily validate all unique constraints in the DB at once, which seems more useful at this point. I think we could add support for `VALIDATE (FORCE) CONSTRAINT` or something like that, but it would require a bit of effort (shouldn't be too bad, though). Anyway, we can revisit in the future if it seems like we want to support both.
