### ISSUE TITLE
sql: verify statement timeout gets propagated to all admission control queues

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#73570]
This issue tracks adding tests that verify that once a statement times out, operations that might have been waiting in an admission control queue are canceled.

Currently the SQL layer cancels the statement when the timeout expires, but it's not clear to me if that cancelation is propagated to KV operations that are already queued up.

Epic: CRDB-10304

Jira issue: CRDB-11650

**Comment by sumeerbhola** [comment]
The `context.Context` passed to `WorkQueue.Admit` comes from here

https://github.com/cockroachdb/cockroach/blob/ca06f4f07a2623bb05d1840886f4a952ac1746b5/pkg/server/node.go#L984-L986

and it is checked here
https://github.com/cockroachdb/cockroach/blob/ca06f4f07a2623bb05d1840886f4a952ac1746b5/pkg/util/admission/work_queue.go#L323-L327
and here
https://github.com/cockroachdb/cockroach/blob/ca06f4f07a2623bb05d1840886f4a952ac1746b5/pkg/util/admission/work_queue.go#L353

and `TestWorkQueueBasic` does test cancellation.

So the question is if the timeout is being propagated to the Context given to `Node.Batch`.

**Comment by cucaroach** [comment]
Okay I've been going down lots of rabbit holes.   At the moment the statement_timeout isn't set on the Context so it doesn't propagate across GRPC calls.   Batch GRPC calls seem to have a 100ms deadline and I can shrink that if I add code to set a deadline on the context where we handle statement_timeout in execStmtInOpenState.  Verifying that this context propagates through KV calls and that we properly hit the code @sumeerbhola references above has eluded me.  Somewhere the deadline gets lost in translation and I can't see SQL operations getting booted out of the admission queue (even though I've installed testing knobs to limit MaxCPUSlots to 1).

**Comment by cucaroach** [comment]
Okay after consulting the pros who assured me this must work I verified that cancelation does in fact propagate across the grpc and have been able to trigger cancelation of a waiting item in the admission control reliably by adding a testing knob to limit the max number of cpu slots.   Now I just have to figure out how to get the test to notice that we hit that error (I think I can do it with tracing).
