### ISSUE TITLE
sql,security: Add support column privileges on table

### ISSUE THREAD

**Issue by eiDear** [cockroachdb/cockroach#73599]
Some databases about postgresql support [data access control about columns of table](https://www.postgresql.org/docs/14/ddl-priv.html). This feature let user own fine-gained security control about data.

Epic CRDB-11723

**Comment by rafiss** [comment]
Thanks for this request! We hope to get to this in a future release, but don't have a definite timeline right now.

**Comment by rafiss** [comment]
Closing this as a duplicate of https://github.com/cockroachdb/cockroach/issues/72766
