### ISSUE TITLE
storage: Benchmark and optimize for reverse scans with lots of shadowed MVCC versions

### ISSUE THREAD

**Issue by itsbilal** [cockroachdb/cockroach#73612]
Currently, our reverse scanning benchmarks top off at 100 versions:

https://github.com/cockroachdb/cockroach/blob/4fe44b93c6261f180658893d2c57f79c714e2403/pkg/storage/bench_pebble_test.go#L89

In a recent customer issue, we saw ~400 versions on the avg row for a scan that ended up being very slow in reverse. As part of this issue, we should add a version of that benchmark with many more versions (either 500 or 1000 versions per row), profile the slowest parts when doing a reverse scan, and explore optimizations that would be useful when reverse-scanning through lots of MVCC versions (both before and immediately after GC when they're shadowed with deletion tombstones). Some of this investigation will inevitably explore optimizations in Pebble instead of just the Cockroach MVCC scanner. 

Jira issue: CRDB-11664

**Comment by itsbilal** [comment]
I updated that benchmark to support 500 revisions per row and 50,000 rows, and I noticed one thing from the cpu profiles (top = reverse scan which was slower by roughly a factor of 2.5):

![Screen Shot 2021-12-08 at 5 31 26 PM](https://user-images.githubusercontent.com/345332/145302138-e03b1c0d-d340-4bbf-b0bb-e18d7522bf29.png)

In particular, the bulk of the difference is in `addAndAdvance`. In both cases we end up calling `seekVersion` a whole lot, which in turn calls addAndAdvance at the end. Everything else is comparable between the two directions. Zooming into addAndAdvance:

![Screen Shot 2021-12-08 at 5 31 03 PM](https://user-images.githubusercontent.com/345332/145302268-c63d82d4-18ec-4d9a-b4d0-ae83a92a2b17.png)

The top (reverse scan) case is effectively doing these operations:

1) `iterPeekPrev` which causes a pretty expensive switch in iterator directions (the bulk of the expense being in re-heapifying the mergingIter) as we call a prev on the iteratore
2) We notice the single peekPrev wasn't enough to switch to a new key, so we fall back to an iterSeekReverse
3) The iterSeekReverse does one SeekLT on the pebble iterator
4) We then do a backwardLatestVersion, which tries iterating with a Prev once before giving up and doing a SeekGE, resetting the iterator direction in the forward direction again
5) Loop back to 1

So the Pebble iterator sees a Prev, then a SeekLT, then a Prev, then a SeekGE, for each addAndAdvance in the reverse direction. For the forward scan it's just a Next followed by a SeekGE in the avg case - no direction switches. In both cases we do an additional Next and a SeekGE after addAndAdvance to land on the right version. So 2 seeks and 2 steps when going forward, and 4 seeks and 3 steps in reverse, with one of the steps requiring a direction flip making it more expensive than other steps (but still less than a seek).

No optimizations jump right out at me yet, but I'll think more about this.

**Comment by ajwerner** [comment]
For the re-heapification, would it make sense to retain two heaps for the mergingIterator with the reverse heap populated lazily when needed?

**Comment by itsbilal** [comment]
> For the re-heapification, would it make sense to retain two heaps for the mergingIterator with the reverse heap populated lazily when needed?

I'm not sure if I understand the suggestion clearly, mind elaborating?

The heap is of level iterators, all with their own state. I should have clarified that the bulk of the cost in the direction switch is calling Prev on all those levelIters, instead of the actual heap rearrangement. We could probably do something with storing two clones of all levelIterators but with independent state, each in their heap, so a Prev after a Next after a Prev just changes the "active heap" but doesn't issue any operations on any underlying iterators.. But that optimization would not be compatible with batch iterators as those deal with mutable state.

**Comment by ajwerner** [comment]
You understood what I was poorly expressing from a place of ignorance. Sorry for any noise.
