### ISSUE TITLE
Cluster UI assets are missing from the tgz source builds

### ISSUE THREAD

**Issue by mlazowik** [cockroachdb/cockroach#73691]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

1. Follow instructions from https://www.cockroachlabs.com/docs/stable/install-cockroachdb-mac.html#build-from-source-1
2. The build will fail, because it expects to be run in a git repository (I guess that's another bug to report)
3. Apply https://github.com/anmonteiro/nix-overlays/blob/213951e1d1babf7f9ffdf6a6180ee33849b1dd4d/cockroachdb/makefile-redact-safe-patch.patch
4. The build works
5. Open the admin UI
6. Blank page, following files 404 `protos.dll.js`, `vendor.dll.js`, `bundle.js`.

**Expected behavior**
The admin UI loads. 

**Environment:**
 - CockroachDB version 21.2.2
 - Server OS: Linux

**Additional context**
`assets.ccl.installed` is empty in the tgz, probably should not be?

Jira issue: CRDB-11695

**Comment by knz** [comment]
cc @jlinder for triage

**Comment by oyvindjr-sigvaldsen** [comment]
Same issue trying to load admin ui on ubuntu 20.04 (cockroach v21.2.4)... Anyone got a solution? @rickystewart

**Comment by rickystewart** [comment]
We no longer distribute source archives in `.tar.gz` format. Clone the repo if you want source code. [Shallow clones](https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/) are a way to clone the repo without pulling all the history which you may not need.
