### ISSUE TITLE
storage: preemptive snapshots are being dropped on the floor

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#7372]
See #7332.

During initial replication of the 5 initial ranges, replica reservations are sometimes declined. The error in the logs is:

```
I160621 20:40:59.638047 storage/reservation.go:155  could not book reservation {StoreRequestHeader:{NodeID:3 StoreID:3} FromNodeID:1 FromStoreID:1 RangeID:5 RangeSize:67108864}, not enough available reservation space (requested:67108864, reserved:201326592, maxReserved:5)
```

This differs from my expectation. With one node sending the reservations, I would expect that we'd see a sequence of reserve-replicate-fill. Instead, we somehow saw 5 consecutive reservations with the 5th one failing.

**Comment by petermattis** [comment]
Some more details from the logs:

```
I160621 20:40:59.380964 storage/reservation.go:174  new reservation added: header:<node_id:3 store_id:3 > from_node_id:1 from_store_id:1 range_id:3 range_size:67108864 
I160621 20:40:59.382322 storage/store.go:2056  refusing incoming Raft message MsgSnap for group 3 from {NodeID:1 StoreID:1 ReplicaID:1} to {NodeID:3 StoreID:3 ReplicaID:0}: storage/replica.go:375: cannot recreate replica that is not a member of its range (StoreID 3 not found in range_id:3 next_replica_id:0 )
...
I160621 20:40:59.616442 storage/replica_raftstorage.go:674  replica 3 received snapshot for range 3 at index 29. encoded size=10719, 29 KV pairs, 19 log entries
I160621 20:40:59.616717 storage/replica_raftstorage.go:676  replica 3 applied snapshot for range 3 in 232.337µs
I160621 20:40:59.616844 storage/reservation.go:203  filling reservation: header:<node_id:3 store_id:3 > from_node_id:1 from_store_id:1 range_id:3 range_size:67108864 
```

Not sure exactly what the above means, but that `refusing incoming Raft message MsgSnap` looks suspicious. @tamird Are pre-emptive snapshots having a problem here?

**Comment by petermattis** [comment]
@tamird After some more digging, it looks like the pre-emptive snapshots are definitely the source of those `refusing incoming Raft message MsgSnap` messages. Those message have `ReplicaID:0` while the snapshots that come out of raft have a non-zero `ReplicaID`. The zero `ReplicaID` causes the failure in `newReplicaInner`. I think. Additional eyes on this would be appreciated.

**Comment by tamird** [comment]
Yes, ReplicaID is indeed zero and this was intentional. I think we can either hack up handleRaftReady to directly apply the snapshot in these cases (that's really what we want, I think) or else we can declare bankruptcy on this and investigate streaming snapshots instead.

**Comment by bdarnell** [comment]
I think it should be fine to make `newReplicaInner` call `setReplicaIDLocked` only if it found a replica ID. Let's try that before we give up on preemptive snapshots.

**Comment by petermattis** [comment]
@bdarnell The naive implementation of your suggestion causes the following panic:

```
panic: config.ID must not be zero

goroutine 4555 [running]:
panic(0x5148040, 0xc82077e4d0)
        /Users/pmattis/Development/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/coreos/etcd/raft.NewRawNode(0xc8207a3980, 0x0, 0x0, 0x0, 0x20, 0x0, 0x0)
        /Users/pmattis/Development/go/src/github.com/coreos/etcd/raft/rawnode.go:74 +0xb4
github.com/cockroachdb/cockroach/storage.(*Replica).withRaftGroupLocked(0xc82030e540, 0xc8207a3b20, 0x0, 0x0)
        /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/storage/replica.go:287 +0x1a6
github.com/cockroachdb/cockroach/storage.(*Replica).withRaftGroup(0xc82030e540, 0xc8207a3b20, 0x0, 0x0)
        /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/storage/replica.go:325 +0x8e
github.com/cockroachdb/cockroach/storage.(*Store).handleRaftMessage(0xc8200898c0, 0xc820174a20, 0x0, 0x0)
        /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/storage/store.go:2061 +0x967
github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1()
        /Users/pmattis/Development/go/src/github.com/cockroachdb/cockroach/storage/store.go:2119 +0x552
...
```

**Comment by petermattis** [comment]
And here is the naive implementation:

```diff
diff --git a/storage/replica.go b/storage/replica.go
index 91f4ee9..852c262 100644
--- a/storage/replica.go
+++ b/storage/replica.go
@@ -371,8 +371,10 @@ func (r *Replica) newReplicaInner(desc *roachpb.RangeDescriptor, clock *hlc.Cloc
        if replicaID == 0 {
                _, repDesc := desc.FindReplica(r.store.StoreID())
                if repDesc == nil {
-                       return util.Errorf("cannot recreate replica that is not a member of its range (StoreID %s not found in %s)",
-                               r.store.StoreID(), desc)
+                       // This is intentionally not an error and is the code path exercised
+                       // during preemptive snapshots. The replica ID will be sent when the
+                       // actual raft replica change occurs.
+                       return nil
                }
                replicaID = repDesc.ReplicaID
        }
```

**Comment by bdarnell** [comment]
Ah, so it's only by accident that we were avoiding this panic before. When we introduced preemptive snapshots we should have added a test to make sure that we were actually processing them instead of getting the same result from the non-preemptive snapshot. 

In addition to the above change, we could apply the snapshot directly in handleRaftMessage (not handleRaftReady), as @tamird suggested. Raft does some sanity checking on the snapshot to ensure that its index and term don't move backwards, but I think as long as no Replica object exists we can ignore that and just overwrite anything that may be there (it's eligible for GC anyway). If a Replica object exists we should probably discard any incoming snapshots with `ToReplica.ReplicaID = 0`. 

We should try to make this work; streaming snapshots are not a complete replacement for preemptive snapshots because they leave the new replica participating in the quorum without all the data.

**Comment by petermattis** [comment]
I agree we should try to make this work. Preemptive snapshots are also a useful throttling mechanism on how fast `replicateQueue` performs rebalancing.

**Comment by petermattis** [comment]
There are two additional problems here. After applying a preemptive snapshot a subsequent raft message will arrive for the replica and we'll go to create the raft group. This creation panics with the following error:

```
panic: [group 1] applied(18) is out of range [prevApplied(10), committed(10)]
```

This panic is caused because committed is initialized from `Replica.FirstIndex` and `Replica.InitialState().Committed`. But snapshots do not contain the raft hard state which is unreplicated, so `Replica.InitialState()` is empty. I have yet to trace through how snapshots work when the raft group has already been created.

The second problem is that the preemptive snapshot request does not wait for the snapshot to be applied remotely. Because we send the snapshot over a gRPC stream, no response is expected. So after generating and sending the preemptive snapshot, we immediately move on to adding the new replica to the raft group. From the logs, it looks like raft then immediately generates a snapshot to send to the new replica.

**Comment by petermattis** [comment]
When raft performs the processing of a snapshot, it calls `raft.restore()` to "recover the state machine from a snapshot". We're not accessing that code path when trying to create a raft group from a preemptive snapshot, hence the panic. I'm not sure what to do here. Supporting preemptive snapshots might require upstream changes to `coreos/etcd/raft`. 

Synthesizing a fake raft hard state might also be possible. Hmm, or maybe `raftpb.HardState` should be sent along with the preemptive snapshot.

**Comment by petermattis** [comment]
Ah, I think we need to call `writeInitialState` when applying a preemptive snapshot.
