### ISSUE TITLE
rfc: Binomial Coefficient Entropy Coding for Inverted Index Postings

### ISSUE THREAD

**Issue by MurageKibicho** [cockroachdb/cockroach#73726]
- Feature Name: Binomial Coefficient Entropy Coding for Inverted Index Postings
- Status: draft
- Start Date: 2021-12-10
- Authors: Murage Kibicho
- RFC PR: (PR # after acceptance of initial draft)
- Cockroach Issue: (one or more # from the issue tracker)

# Summary
This is a proposal for encoding inverted index integer sequences using a number system based on binomial coefficients.
This number system is chosen because the [minimum number of bits](https://arxiv.org/abs/1908.10598) needed to encode a list of strictly increasing integers
is given by the equation ![ceilinglog2](https://raw.githubusercontent.com/PostingsCompress/PostingsWebsite/main/log2UN130.png)
where ![U](https://raw.githubusercontent.com/PostingsCompress/PostingsWebsite/main/U.png) is largest number in the list and ![n](https://raw.githubusercontent.com/PostingsCompress/PostingsWebsite/main/n.png) is the number of elements in the list.
For example to encode the sequence **1,2,3,4,10,11** we need at least 9 bits: ![11 choose 6](https://raw.githubusercontent.com/PostingsCompress/PostingsWebsite/main/11choose6.png) and
![log2(462) = 8.85 ~ 9 bits](https://raw.githubusercontent.com/PostingsCompress/PostingsWebsite/main/ceil.png).
Binary interpolative coding, one of the best methods for inverted list compression takes at least 20 bits to represent the example sequence. You can confirm this [here](https://github.com/jermp/interpolative_coding).
However, if we represent the same sequence as a sum of binomial coefficients, it takes 10 bits to encode the list, and an extra 3 bits to store the length of the list. The total is 13 bits. You can confirm this [here](https://postingscompress.github.io/PostingsWebsite/#/).

# Motivation
Compression is a solved problem. The best compressors work by changing radixes, or number bases to find the most concise representation of data.
For instance, arithmetic coding is a [generalized change of radix](https://rosettacode.org/wiki/Talk:Arithmetic_coding/As_a_generalized_change_of_radix) for coding
at the [information theoretic entropy bound](https://en.wikipedia.org/wiki/Entropy_(information_theory)). This bound is a measure of redundancy - how many duplicates are in your data. Strictly increasing integer sequences have no duplicates, therefore, cannot be compressed 
according to the information theoretic bound. This means huffman coding and arithmetic coding methods are inefficient with non-repetitive integer sequences.

This rfc proposes the use of the combinatorial number system to encode inverted index integer sequences at the [combinatorial information theoretic entropy bound](https://arxiv.org/abs/1908.10598).
Just like arithmetic coding, this change in number systems allows us to encode integer sequences with the least number of bits.
\
I am a Math major in my junior year and if this RFC succeeds I would love to take a gap year and work on this [library](https://github.com/PostingsCompress/Postings/tree/main/MathLibraries) full time. The library
has sample code for converting between binary and the combinatorial number system using a greedy algorithm, or by generating a lookup table.

Masha Schneider and Jordan Lewis are the authors of CockroachDB's [inverted index rfc](https://github.com/cockroachdb/cockroach/blob/4d987b3f0788c98fa358715b336a1c55e254ee50/docs/RFCS/20171020_inverted_indexes.md)
# Technical design
\
## Overview of Combinatorial Number System
Any natural number ![N](https://raw.githubusercontent.com/PostingsCompress/PostingsWebsite/main/N.png) can be uniquely written as a sum of binomial coefficients
using [this](http://math0.wvstateu.edu/~baker/cs405/code/Combinadics.html) greedy algorithm.

\
1. Find the largest binomial coefficient such that ![akChoosek](https://raw.githubusercontent.com/PostingsCompress/PostingsWebsite/main/akChooseKleqN.png)
2. Subtract to find the residue ![NminusAkChoosek](https://raw.githubusercontent.com/PostingsCompress/PostingsWebsite/main/NMinusBinomial.png)
3. Find the largest binomial coefficient such that ![Repeat](https://raw.githubusercontent.com/PostingsCompress/PostingsWebsite/main/repeat.png)
\

## **Example:** Find the combinatorial representation of ![n63K4](https://raw.githubusercontent.com/PostingsCompress/PostingsWebsite/main/n63K4.png)
![Convert to Binomial](https://raw.githubusercontent.com/PostingsCompress/PostingsWebsite/main/conversionToBinomials.png)
\
To **reverse** the process, sum your list of binomial coefficients
![Sum](https://raw.githubusercontent.com/PostingsCompress/PostingsWebsite/main/sum130.png)

## Comparison to Binary Interpolative Coding
In the example above, it can be seen that the sequence ![forward sequence](https://raw.githubusercontent.com/PostingsCompress/PostingsWebsite/main/forward.png)
can be encoded in ![for2](https://raw.githubusercontent.com/PostingsCompress/PostingsWebsite/main/for2.png) using the combinatorial number system with an extra 3 bits to store the length of the sequence. This is a total of 9 bits to encode this sequence.
\
Using [this library](https://github.com/jermp/interpolative_coding) it can be confirmed that binary interpolative coding takes between 15 to 23 bits to encode the same sequence.
\
This is a screenshot of the result of binary interpolative coding.
![Screenshot](https://raw.githubusercontent.com/PostingsCompress/PostingsWebsite/main/bic.png) 
\
The combinatorial number systems always encodes integer sequences at the entropy limit.

## Drawbacks
Calculating a binomial coefficent is quite expensive. The calculation involves a lot of divisions.

...

## Rationale and Alternatives
Alternatives to the combinatorial number system are Rice-Golomb coding and Binary Interpolative Coding. They are simple and run fast.

...

# Explain it to folk outside of your team

# Unresolved questions

Audience: all participants to the RFC review.

Jira issue: CRDB-11711

**Comment by mgartner** [comment]
Thanks for the thorough write-up. I learned quite a bit reading it.

If I understand correctly, you're suggesting a more space-efficient encoding for sets of document IDs in an inverted index postings list. For example, the proposal describes a method for encoding the sets `1, 5, 7` and `1, 3` in the inverted index:

```
foo => 1, 5, 7
bar => 1, 3
```

CRDB's inverted indexes are conceptually a bit different than inverted indexes used in search engines and document retrieval systems. We don't store the a list of primary keys together for each indexed value. Instead, each indexed value and primary key pair has its own key-value in the [KV layer](https://www.cockroachlabs.com/docs/stable/architecture/overview#layers). Conceptually, it looks like:

```
/foo/1
/foo/5
/foo/7
/bar/1
/bar/3
```

In our inverted indexes, primary keys aren't stored together in set, so a more space-efficient encoding for sets of integers is irrelevant.

I'll go ahead and close this issue.
