### ISSUE TITLE
Support xml type (repost of #43355)

### ISSUE THREAD

**Issue by techdragon** [cockroachdb/cockroach#73730]
**Is your feature request related to a problem? Please describe.**
CockroachDB does not yet support the XML column type.

**Describe the solution you'd like**
Please add support for the XML column type. 

**Describe alternatives you've considered**
N.A.

**Additional context**
https://www.postgresql.org/docs/9.1/datatype-xml.html

The xml data type can be used to store XML data. Its advantage over storing XML data in a text field is that it checks the input values for well-formedness, and there are support functions to perform type-safe operations on it; see Section 9.14. Use of this data type requires the installation to have been built with configure --with-libxml.

This is a duplicate of #43355 as that was closed automatically by a bot.

**Comment by yuzefovich** [comment]
Closing in favor of reopening #43355
