### ISSUE TITLE
sql: kv tracing crashes on not null virtual computed columns

### ISSUE THREAD

**Issue by chengxiong-ruan** [cockroachdb/cockroach#73745]
**To Reproduce**
```sql
create table t (
x int primary key,
y int not null,
z int not null as ((y*2)) virtual
);

insert into t values (1,2),(3,4),(5,6);

\set auto_trace=on,kv;

select * from t; --uh oh
```
you'd get an error like 
```
non-nullable column "t:z" with no value! Index scanned was "t_pkey" with the index key columns (x) and the values (1)
```

**Expected behavior**
We probably need to ignore virtual columns in `cFetcher.fillNulls()` method

**Comment by ajwerner** [comment]
This is a good bug. This is more in the @cockroachdb/sql-queries wheelhouse. I'm going to let them triage it.

**Comment by mgartner** [comment]
This might be related to: https://github.com/cockroachdb/cockroach/issues/73372.
