### ISSUE TITLE
Adding multiple columns with constraint on second column attempts to apply to first

### ISSUE THREAD

**Issue by jonstjohn** [cockroachdb/cockroach#73798]
**Describe the problem**

When adding multiple columns in a single ALTER TABLE statement and the second column includes a foreign key constraint, an error occurs which suggests it was applied to the first column.

**To Reproduce**

```sql
-- SETUP 2 TABLES
> CREATE TABLE customers (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY);
> CREATE TABLE orders (id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY);

-- FAILURE: ADD TWO COLUMNS, SECOND COLUMN IS HAS FK CONSTRAINT
> ALTER TABLE orders ADD COLUMN description STRING NULL, ADD COLUMN customer_id UUID REFERENCES customers(id);
ERROR: type of "user_id" (string) does not match foreign key "customers"."id" (uuid)
SQLSTATE: 42804

-- SUCCESS: ADD TWO COLUMNS, FIRST COLUMN IS HAS FK CONSTRAINT
> ALTER TABLE orders ADD COLUMN customer_id UUID REFERENCES customers(id), ADD COLUMN description STRING NULL;
ALTER TABLE
Time: 284ms total (execution 284ms / network 0ms)
```

**Expected behavior**
The foreign key constraint should be applied only to the column that it follows, no error should occur.

**Additional data / screenshots**

The work-around was to switch the order of the columns.

**Environment:**
 - CockroachDB version: v21.2.2 (also seen in 21.1.12)
 - Server OS: Ubuntu, MacOS (does not appear to matter)
 - Client app: cockroach sql

**Additional context**

None

**Comment by ajwerner** [comment]
My intuition is this is going to be some `AllocateIDs` garbage.

**Comment by ajwerner** [comment]
@fqazi with @chengxiong-ruan out, can you take a look at this? I think it's the same as #74360 and it seems new in 21.2.

**Comment by fqazi** [comment]
It is linked to us picking up the wrong column because of the following (which does smell a bit @ajwerner ):
`// FindActiveOrNewColumnByName finds the column with the specified name.
// It returns either an active column or a column that was added in the
// same transaction that is currently running.
func (desc *Mutable) FindActiveOrNewColumnByName(name tree.Name) (catalog.Column, error) {
	currentMutationID := desc.ClusterVersion.NextMutationID
	for _, col := range desc.DeletableColumns() {
		if (col.Public() && col.ColName() == name) ||
			(col.Adding() && col.MutationID() == currentMutationID) {
			return col, nil
		}
	}
	return nil, colinfo.NewUndefinedColumnError(string(name))
}`
