### ISSUE TITLE
Backups fail on GCP using AUTH=implicit

### ISSUE THREAD

**Issue by BobFerris** [cockroachdb/cockroach#73797]
**Describe the problem**

Running a 3 node cluster on GKE.  The 3 nodes in the cluster are running under a service account (626923887835-compute@developer.gserviceaccount.com).  This service account has owner permissions on the 3 VMs in the cluster.

Continue to get 403 forbidden errors attempting to run backups using AUTH=implicit.

root@cockroachdb-public:26257/defaultdb> BACKUP DATABASE thg TO 'gs://ferris_crl/backup?AUTH=implicit' AS OF SYSTEM TIME '-10s';

ERROR: writing checkpoint file: write to google cloud: googleapi: Error 403: Provided scope(s) are not authorized, forbidden

The service account has Storage Admin access to the GCS bucket.

<img width="1697" alt="Screen Shot 2021-12-14 at 10 37 42 AM" src="https://user-images.githubusercontent.com/40582794/146032701-f313fbe8-5319-48a8-b315-c64921a77e22.png">

**Expected behavior**
Since the cluster setting `cloudstorage.gs.default.key` has been removed in version 21.2 what are the steps needed to get AUTH=implicit working so that Enterprises do not need to pass in security credentials with each bulk-io/backup command?  Is there a specific IAM setting that is missing or some other permissions?  Unable to find documentation on using AUTH=implicit for GCP/GKE.

**Additional data / screenshots**

**Environment:**
 - CockroachDB version 21.1.12
 - Server OS: GKE linux image

**Comment by daniel-crlabs** [comment]
I was able to run this without any issues in my lab and send the backup to GCP:

```
root@lab-kub01:30007/test> select version();
                                          version
--------------------------------------------------------------------------------------------
  CockroachDB CCL v21.1.9 (x86_64-unknown-linux-gnu, built 2021/09/20 21:47:27, go1.15.14)
(1 row)

Time: 1ms total (execution 0ms / network 1ms)
```

Has you CockroachDB server been started with the following environment variable set?

`GOOGLE_APPLICATION_CREDENTIALS`

This should be pointing to your json file obtained from GCP with your credentials, [as documented here](https://cloud.google.com/docs/authentication/production#command-line). 

```
[root@cockroachdb-0 ~]# env | grep GOOGLE_APPLICATION_CREDENTIALS
GOOGLE_APPLICATION_CREDENTIALS=/cockroach/google/googlebucket.json
```

```
[root@cockroachdb-0 ~]# head -2 /cockroach/google/googlebucket.json
{
"type": "service_account",
```

Once your json file has been placed in the CockroachDB server, you need to restart it, so CockroachDB will recognize the new environment variable, then you should be able to use the backup via the `implicit` method.

```
root@lab-kub01:30007/defaultdb> create database test;
CREATE DATABASE

Time: 70ms total (execution 70ms / network 1ms)

root@lab-kub01:30007/defaultdb> use test;
SET

Time: 17ms total (execution 17ms / network 1ms)

root@lab-kub01:30007/test> create table t1(id int);
CREATE TABLE

Time: 204ms total (execution 203ms / network 1ms)

root@lab-kub01:30007/test> insert into t1 values (1),(2),(3),(4),(5);
INSERT 5

Time: 33ms total (execution 33ms / network 1ms)

root@lab-kub01:30007/test> select * from t1;
  id
------
   1
   2
   3
   4
   5
(5 rows)

Time: 3ms total (execution 3ms / network 1ms)

root@lab-kub01:30007/test> BACKUP DATABASE test INTO "gs://tse-test/t1?AUTH=implicit";
        job_id       |  status   | fraction_completed | rows | index_entries | bytes
---------------------+-----------+--------------------+------+---------------+--------
  719102936735842306 | succeeded |                  1 |    5 |             0 |    95
(1 row)

Time: 3.614s total (execution 3.613s / network 0.001s)
```

**Comment by daniel-crlabs** [comment]
A doc ticket was created to have the documentation updated with the correct process to take backups using GCP auth.
I'll go ahead and close this issue. The docs request ticket is shown below:

[Add more detail to GCS Implicit Authentication](https://cockroachlabs.atlassian.net/browse/DOC-2174)
