### ISSUE TITLE
get design docs on github

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#738]
we still have @spencerkimball's [original design docs](https://docs.google.com/document/d/11k2EmhLGSbViBvi6_zFEiKzuXxYF49ZuuDJLe6O8gBU/edit#heading=h.kgqgd63x1fet) online. They should go to our github page and ideally make it easy for others to contribute to them as well (I have found it tedious to edit such a large document WYSIWYG).

There are two options:

- the github wiki, but that doesn't allow pull requests.
- just a folder in our repo with a README.md entry point. [Demo](https://github.com/tschottdorf/cockroach/tree/tschottdorf/design_docs/docs)

I like the second option more because it's more community-friendly and you can browse and read it just fine, so it works pretty much like the wiki plus pull requests. With either option it'll be easy to migrate it later. In any case, now's a good time to do this because we've been discussing changes that would benefit from being put into writing.

**Comment by petermattis** [comment]
I like having a folder of docs in our repo. It makes the docs versioned and still allows them to be easily viewable from github.

**Comment by spencerkimball** [comment]
The github wiki seems more suitable for the task of documentation. At least traditionally. Are there any things which will be easier with the wiki than with a documentation folder in the repo? Does the wiki support fancier markup options?

**Comment by bdarnell** [comment]
The same markup (er, markdown) is supported in both places. The main difference is that by putting things in the main repo we can use PRs to discuss diffs before they go in, while edits to the wiki go live immediately. The wiki can also be open to edits by non-team-members, but it doesn't have to be. I'd rather have the folder in the repo.

**Comment by tschottdorf** [comment]
ok, I'll do the annoying work of translating everything. Won't be a perfect job, but hopefully good enough.

**Comment by bdarnell** [comment]
You could try pandoc, which claims to be able to convert Word-like documents (among other formats) to markdown: http://pandoc.org/
