### ISSUE TITLE
opt: do not recommend dropping unique indexes in EXPLAIN index recommendations

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#73814]
In some cases, index recommendations in EXPLAIN output recommend dropping a unique index and replacing it with a non-unique index.

For example:

```
defaultdb> CREATE TABLE t (k INT PRIMARY KEY, a INT, b INT);
CREATE TABLE

defaultdb> CREATE UNIQUE INDEX ON t(a);
CREATE INDEX

defaultdb> EXPLAIN SELECT * FROM t WHERE a = 1;
                                    info
-----------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • index join
  │ table: t@t_pkey
  │
  └── • scan
        missing stats
        table: t@t_a_key
        spans: [/1 - /1]

  index recommendations: 1
  1. type: index replacement
     SQL commands: DROP INDEX t@t_a_key; CREATE INDEX ON t (a) STORING (b);
(14 rows)
```

This is problematic because the semantics of the table have now changed. The column(s) held unique by the index are no longer guaranteed to be unique.

There are a few different options for how to fix this, including:

1. If the index being dropped is unique, disregard the entire recommendation.
2. If the index being dropped is unique, disregard the `DROP` portion of the recommendation, but keep the `CREATE INDEX` part.
3. If the index being dropped is unique, and the index being created has the same columns in the same order (is this always the case for index replacement recommendations?), then recommend created a new unique index. In this case, the new unique index should be created first, and the original unique index should be dropped afterward, to ensure that at no point in time can duplicate values be inserted.

**Comment by nehageorge** [comment]
Good find, I'll fix this. I think we should go with option 3, as the index being created always has the same columns in the same order. For consistency, I think we should always create the new index first and then drop the existing index.

**Comment by mgartner** [comment]
Note that this also repros with partial unique indexes:

```
defaultdb> create table t (k int primary key, a int, b int);
CREATE TABLE


Time: 6ms total (execution 6ms / network 0ms)

defaultdb> create unique index on t (a) where b > 0;
CREATE INDEX


Time: 131ms total (execution 131ms / network 0ms)

defaultdb> explain select * from t where a = 1;
                                    info
-----------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • filter
  │ filter: a = 1
  │
  └── • scan
        missing stats
        table: t@t_pkey
        spans: FULL SCAN

  index recommendations: 1
  1. type: index replacement
     SQL commands: DROP INDEX t@t_a_key; CREATE INDEX ON t (a) STORING (b);
(14 rows)
```

Option 3 won't work in these cases, so we'll have to do something different.

**Comment by nehageorge** [comment]
I'm thinking of two options...

1. We don't register partial indexes as "existing redundant indexes." This would mean that we would have a creation recommendation instead of a replacement one.
2. We don't recommend anything when there is an existing redundant partial index.  

I'm leaning toward option 1 since we are trying to improve the current query and storing columns could be beneficial. The user should also be aware of their own schema, especially if they have partial indexes, and may choose not to follow the index recommendations. This protects against the creation of too many indexes or unnecessary indexes.

**Comment by mgartner** [comment]
> I'm leaning toward option 1

This sounds good to me. I can think of two maxims that we might use to guide decisions like this:

1. An index recommendation should always lead to a better plan than the existing.
2. An index recommendation should never lead to worse plans for other queries.

I think both hold true for both options, but agree that (1) is preferred since it will provide a better plan for this specific query.
