### ISSUE TITLE
migration/startupmigrations: remove all startupmigrations

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#73813]
**Is your feature request related to a problem? Please describe.**

Before long-running migrations, there were migrations which ran at startup. We haven't really leveraged these in a while (none since 20.2). There are, however, "permanent" migrations which set up some initial cluster state. We should get rid of that concept and all the complexity that comes with it.

**Describe the solution you'd like**
Move any permanent migrations into bootstrap. Some of the remaining seem to not really be permanent. 

#### Remaining permanent migrations:

* [`optIntoDiagnosticsReporting`](https://github.com/cockroachdb/cockroach/blob/42055b0c16528d0e7e2e78e255430ffec158d205/pkg/startupmigrations/migrations.go#L95-L99)
* [`populateVersionSetting`](https://github.com/cockroachdb/cockroach/blob/42055b0c16528d0e7e2e78e255430ffec158d205/pkg/startupmigrations/migrations.go#L108-L113)
* [`addRootUser`](https://github.com/cockroachdb/cockroach/blob/42055b0c16528d0e7e2e78e255430ffec158d205/pkg/startupmigrations/migrations.go#L119-L123)
* [`addAdminRole`](https://github.com/cockroachdb/cockroach/blob/42055b0c16528d0e7e2e78e255430ffec158d205/pkg/startupmigrations/migrations.go#L138-L142)
* [`addRootToAdminRole`](https://github.com/cockroachdb/cockroach/blob/42055b0c16528d0e7e2e78e255430ffec158d205/pkg/startupmigrations/migrations.go#L147-L151)
* [`initializeClusterSecret`](https://github.com/cockroachdb/cockroach/blob/42055b0c16528d0e7e2e78e255430ffec158d205/pkg/startupmigrations/migrations.go#L168-L172)
* [`disallowPublicUserOrRole`](https://github.com/cockroachdb/cockroach/blob/42055b0c16528d0e7e2e78e255430ffec158d205/pkg/startupmigrations/migrations.go#L182-L187)
* [`createDefaultDatabases`](https://github.com/cockroachdb/cockroach/blob/42055b0c16528d0e7e2e78e255430ffec158d205/pkg/startupmigrations/migrations.go#L188-L194)
* [`retireOldTsPurgeIntervalSettings`](https://github.com/cockroachdb/cockroach/blob/42055b0c16528d0e7e2e78e255430ffec158d205/pkg/startupmigrations/migrations.go#L219-L225)
* [`updateSystemLocationData`](https://github.com/cockroachdb/cockroach/blob/42055b0c16528d0e7e2e78e255430ffec158d205/pkg/startupmigrations/migrations.go#L226-L230)
* [`extendCreateRoleWithCreateLogin`](https://github.com/cockroachdb/cockroach/blob/42055b0c16528d0e7e2e78e255430ffec158d205/pkg/startupmigrations/migrations.go#L294-L298)

**Describe alternatives you've considered**
We could not do this. An advantage to startup migrations is that they get to leverage the running system and, in doing so, may gain benefit from more code reuse. 

**Additional context**

The pressing migration which motivated this was `createDefaultDatabases`. 

Jira issue: CRDB-11759

Epic CRDB-18596

**Comment by ajwerner** [comment]
See #73754 for an interaction with `createDefaultDatabases`.

**Comment by ajwerner** [comment]
One challenge here is that we use the startupmigrations as an easy way to write the data using SQL. To get rid of these startupmigrations, we'd need to have a convenient way to write such data into the boostrapped state. One approach would be to write the data out in some static process to generate the kvs and check them in.

**Comment by ajwerner** [comment]
I'm inclined to unhook this from [CRDB-18596](https://cockroachlabs.atlassian.net/browse/CRDB-18596) because of https://github.com/cockroachdb/cockroach/pull/84881.

**Comment by knz** [comment]
i'm friendly to the idea but let's then find a new+better home for it.

**Comment by ajwerner** [comment]
> i'm friendly to the idea but let's then find a new+better home for it.

Have any ideas? I went diving into JIRA initiatives. Maybe https://cockroachlabs.atlassian.net/browse/CRDB-17124, but it's already done?

**Comment by knz** [comment]
@ajstorm could you assist us here?

**Comment by ajstorm** [comment]
At least for some known painful cases, #84881 doesn't seem to solve the problem.  For example on my laptop, `cockroach demo --nodes 9 --global --no-example-database` takes around 2 minutes, whereas running the same command with `multitenant=false` takes less than 5 seconds.  This materially impacts multi-region demoing in multi-tenant environments.

I don't see a better home than [CRDB-18596](https://cockroachlabs.atlassian.net/browse/CRDB-18596) considering the above.

**Comment by ajstorm** [comment]
>I have a different fix for demo coming soon (later this week) where we don't turn on the injected latency until later, that will fix the slow cockroach demo you are struggling with independent of both this and [CRDB-18596](https://cockroachlabs.atlassian.net/browse/CRDB-18596).

Once demo is fixed, I'm fine decoupling this from CRDB-18596.  If we don't have a suitable epic to attach it to, I'd suggest that we create a new epic for this issue.
