### ISSUE TITLE
roachtest: jepsen nightlies never run to completion

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#73845]
While looking at old issues I got curious why we hadn't seen any additional failures for https://github.com/cockroachdb/cockroach/issues/49360, which used to fail at least every month or two.

Looking at the last nightly roachtest build at the time of writing [https://teamcity.cockroachdb.com/viewLog.html?buildId=3904068&buildTypeId=Cockroach_Nightlies_WorkloadNightly&tab=artifacts#%2Fjepsen%2Fmulti-register%2Fstrobe-skews%2Frun_1%2Fartifacts.zip](here) gives me the impression that due to some SSH misconfiguration, this test never succeeds:

```
ERROR [2021-12-14 11:00:38,609] clojure-agent-send-off-pool-1 - jepsen.control Error opening SSH session. Verify username, password, and node hostnames are correct.
SSH configuration is:
 {:dir "/",
 :private-key-path "/home/ubuntu/.ssh/id_rsa",
 :password "root",
 :username "ubuntu",
 :port 22,
 :strict-host-key-checking false,
 :host "10.142.1.113",
 :sudo nil,
 :dummy nil,
 :session nil}

ERROR [2021-12-14 11:00:38,624] main - jepsen.cli Oh jeez, I'm sorry, Jepsen broke. Here's why:
com.jcraft.jsch.JSchException: invalid privatekey: [B@44349e8c
```

but also does not report an error, likely as a result of this code:

https://github.com/cockroachdb/cockroach/blob/5d689c1b62d74689511e3e4efae4c56b00228fb6/pkg/cmd/roachtest/tests/jepsen.go#L252-L281

as we see this in the output:

```
11:00:19 jepsen.go:179: test status: running
11:00:38 jepsen.go:233: failed: output in run_110031.526429021_n6_bash: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-3904068-1639466723-44-n6cpu4:6 -- bash -e -c "\
cd /mnt/data1/jepsen/cockroachdb && set -eo pipefail && \
 ~/lein run test \
   --tarball file://${PWD}/cockroach.tgz \
   --username ${USER} \
   --ssh-private-key ~/.ssh/id_rsa \
   --os ubuntu \
   --time-limit 300 \
   --concurrency 30 \
   --recovery-time 25 \
   --test-count 1 \
   -n 10.142.0.110 -n 10.142.1.113 -n 10.142.1.14 -n 10.142.1.12 -n 10.142.0.135 \
   --test multi-register --nemesis strobe-skews \
> invoke.log 2>&1 \
" returned: exit status 10
11:00:38 jepsen.go:253: grabbing artifacts from controller. Tail of controller log:
11:00:40 jepsen.go:277: Recognized BrokenBarrier or other known exceptions (see grep output above). Ignoring it and considering the test successful. See #30527 or #26082 for some of the ignored exceptions.
```

We need to fix the underlying SSH problem and reconsider the skip logic above.

Jira issue: CRDB-11778

**Comment by aliher1911** [comment]
Looks like the problem came from ssh version upgrade. Starting from 7.8 openssh changed default private key format which jsch doesn't understand. So we need to generate key differently. I'll check how we generate this key or if we could change format on the fly before running jepsen.

**Comment by aliher1911** [comment]
Now that keys are working it fails with:
`Failed to stop ntp.service: Unit ntp.service not loaded.` when trying to run `service ntp stop`.
Which makes sense as we don't have ntp running. I think ubuntu replaced ntpd by default with timesyncd since 16.xx so not sure how it even run.

Did we bump our distro since last successful jepsen run maybe?

**Comment by renatolabs** [comment]
This issue seems outdated. We haven't seen the error reported here in a while (that I'm aware of) -- we have seen Jepsen failures recently, but those are not because it didn't run to completion. Closing.
