### ISSUE TITLE
sql/builtins: support crypt builtin from pgcrypto

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#73867]
From https://www.postgresql.org/docs/14/pgcrypto.html

```
crypt(password text, salt text) returns text
```

> Calculates a crypt(3)-style hash of password. When storing a new password, you need to use gen_salt() to generate a new salt value. To check a password, pass the stored hash value as salt, and test whether the result matches the stored value.

Depends on https://github.com/cockroachdb/cockroach/issues/73868

Epic CRDB-120

Jira issue: CRDB-11790

**Comment by ecwall** [comment]
Implemented md5 and blowfish hashes, but not des or xdes. If anyone has a need for these, please create a new ticket with details.
