### ISSUE TITLE
sql: add per-role / per-db session setting for index recommendations

### ISSUE THREAD

**Issue by nehageorge** [cockroachdb/cockroach#73918]
We currently have a session setting for enabling and disabling index recommendations for `EXPLAIN` (called `index_recommendations_enabled`). Once the infrastructure for per-role and per-db session default settings is created, we should add these defaults for index recommendations.

Jira issue: CRDB-11813

**Comment by mgartner** [comment]
This is possible with `ALTER ROLE` now. For example: `ALTER ROLE ALL SET index_recommendations_enabled = false`.
