### ISSUE TITLE
bulk: use compressed kv buffer in BufferingAdder

### ISSUE THREAD

**Issue by sumeerbhola** [cockroachdb/cockroach#73983]
Each source node has a B byte buffer in the BufferingAdder for buffering and sorting kv pairs. Assuming a primary index key maps to a random key in the secondary index key space, each buffer flush from a source node will generate keys over the same key space. Let there be N target nodes. Each target node gets B/N of this buffer.
Say N=5 (if we have a 15 node cluster with 3 way replication and the index is evenly distributed across all nodes) and B=512MB. B/N=102.4MB. With 8x compression ratio this is 12.8MB of sstables before repetition of the key space. Increasing the bytes before repetition will make both sstable ingestion (allows for narrower sstables in the key space) and L0 sublevels behave significantly better. For instance if each sst becomes 1/8th of the width in the key space we can fit 8 of these side-by-side in a level, instead of them stacking up from L6 through L0 (with 2 sub-levels in L0).

We can build a compressed kv buffer by constructing and wrapping a temporary in-memory Pebble instance, at some cpu cost in the source.
- Possible settings for this Pebble instance.
  - Disable WAL
  - Set MaxConcurrentCompactions=1 (ideally we should support compaction+flush concurrency of 1 -- this will ensure at most one extra cpu gets used, limiting the effect on foreground traffic).
  - Disable read compactions and read sampling (we see the latter in cpu profiles -- we don't want to waste cpu).
  - Disable deletion pacing (of the in-memory files), so that the sum of the live file sizes + memtable bounds the memory footpring.
  - MemTableStopWritesThreshold=1 so there is at most 1 memtable. We want most of the memory used by compressed files.
  - L0CompactionThreshold=2, L0StopWritesThreshold=3 so we don't build up read amp since we want nearby keys to be in the same sstable for better compression. Alternatively, if key prefix compression is good enough when flushing a single memtable, we could consider tuning the L0 settings such that there is no compaction from L0=>Lbase, even if it means a high read amp. We are going to scan once at the end, and we can afford to do a merge sort across 50 levels for that scan.
- The wrapper would keep track of the uncompressed bytes it is adding. Every N bytes (say 64MB), it would get pebble.Metrics and use the total file size to decide whether to flush. After flushing, this Pebble instance can be discarded.
- There is more memory churn here compared to using bulk.kvBuf. By setting the Pebble options to have the same target file size in each level, and using a customized in-memory FS implementation (not vfs.MemFS), we should be able to reuse the memory allocated for a file when writing a new file.

cc: @dt 

Jira issue: CRDB-11840

Epic CRDB-19402

**Comment by shermanCRL** [comment]
May be a good project for @msbutler, who is interested in “Storage-adjacent” Bulk IO projects. @dt mentions this is not high-priority in the current dev cycle. Primary benefit is IMPORT performance.
