### ISSUE TITLE
sql: surprising behavior of UPSERT without explicit target columns, especially with ON UPDATE columns

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#73984]
**UPDATE: I now believe this is not a bug. See [my comment below](https://github.com/cockroachdb/cockroach/issues/73984#issuecomment-996994725).**

---

According to the [`ON UPDATE` RFC](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20210722_on_update_and_row_rehoming.md), `ON UPDATE` columns should be updated when an `UPSERT` updates an existing row. This is not currently the behavior in 21.2.

For example, notice that the `UPSERT` sets the timestamp column to `NULL` rather than the current time:

```
defaultdb> SELECT version();
                                        version
----------------------------------------------------------------------------------------
  CockroachDB CCL v21.2.3 (x86_64-apple-darwin19, built 2021/12/14 15:26:20, go1.16.6)
(1 row)

defaultdb> CREATE TABLE t (k INT PRIMARY KEY, a INT, t TIMESTAMPTZ ON UPDATE now());
CREATE TABLE

defaultdb> INSERT INTO t VALUES (1, 2, '2021-01-01 12:00:00');
INSERT 1

defaultdb> UPSERT INTO t VALUES (1, 20);
INSERT 1

defaultdb> SELECT * FROM t;
  k | a  |  t
----+----+-------
  1 | 20 | NULL
(1 row)
```

Jira issue: CRDB-11841

**Comment by mgartner** [comment]
**I now believe that this is not a bug**. Consider an UPSERT without explicit target columns into a table without any ON UPDATE columns. If any column values are omitted from the VALUES clause, the system will set the columns to their default value. For example:

```
defaultdb> CREATE TABLE t (k INT PRIMARY KEY, a INT);
CREATE TABLE

defaultdb> INSERT INTO t VALUES (1, 2);
INSERT 1

defaultdb> UPSERT INTO t VALUES (1);
INSERT 1

defaultdb> SELECT * FROM t;
  k |  a
----+-------
  1 | NULL
(1 row)
```

Notice that the UPSERT set `a` to NULL, its default value.

I believe that the ON UPDATE example at the top of the issue is consistent with this behavior: `t` is set to its default value of `NULL`. If the target columns are made explicit in the UPSERT, then the value of `t` is updated to the current time, as expected:

```
defaultdb> CREATE TABLE t (k INT PRIMARY KEY, a INT, t TIMESTAMPTZ ON UPDATE now());
CREATE TABLE

defaultdb> INSERT INTO t VALUES (1, 2, '2021-01-01 12:00:00');
INSERT 1

defaultdb> UPSERT INTO t (k, a) VALUES (1, 20);
INSERT 1

defaultdb> SELECT * FROM t;
  k | a  |               t
----+----+--------------------------------
  1 | 20 | 2021-12-17 19:33:37.713079+00
(1 row)
```

While this is not a bug, the behavior of UPSERT without explicit target columns, even in the absence of ON UPDATE columns is surprising. I think we should consider these possible action items:

1. Documentation of UPSERT should be clear about its behavior when there are no explicit target columns. The documentation does not currently mention this case or have any examples of it.
2. Add tests for UPSERTs without explicit target columns and ON UPDATE so that the behavior is well-defined. I couldn't find any existing tests for this case.
2. Error if an UPSERT without target columns if the UPSERT's input (e.g., VALUES or SELECT) does not have the same number of columns as the target table. MySQL's version of UPSERT, REPLACE, behaves this way (though so does MySQL's INSERT).
3. You could argue that UPSERTs without explicit target columns, even in the absence of ON UPDATE columns, is so surprisingly that we should require UPSERTs to have explicit target columns.

**Comment by rafiss** [comment]
For when we document this, here's a use case that I imagine could be common, but would end up with unexpected results.
```
CREATE TABLE t (a INT PRIMARY KEY, b TEXT, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ ON UPDATE now());

INSERT INTO t VALUES (1, 'cat');
-- created_at is t1 and updated_at is NULL

UPSERT INTO t VALUES (1, 'dog');
-- created_at is t2 and updated_at is NULL
```

**Comment by rafiss** [comment]
What if we change the behavior to:
```
If any column values are omitted from the VALUES clause, the system will set the columns to the ON UPDATE value. If the ON UPDATE value is NULL or missing, set the columns to their default value. 
```

Would this be reasonable?

**Comment by mgartner** [comment]
> During UPSERT, if any column values are omitted from the VALUES clause, the system will set the columns to the ON UPDATE value. If the ON UPDATE value is NULL or missing, the system well set the columns to their default value.

If the UPSERT resulted in an inserted row, then this would also be confusing behavior IMO.

**Comment by rafiss** [comment]
Oh yeah, good point. I guess then we'd want the UPSERT to conditionally pick between the DEFAULT or the ON UPDATE value. In other words:
* If UPSERT results in a newly inserted row: use the DEFAULT value.
* Else, if the ON UPDATE value is not NULL: use the ON UPDATE value.
* Else: use the DEFAULT value.

But I'm not sure if it's easy to make this change. Also, this behavior is arguably also not intuitive so could be just as hard for users to get right.

**Comment by mgartner** [comment]
The behavior is now explained in the docs thanks to https://github.com/cockroachdb/docs/pull/13818. I'm going to close this for now on the assumption that not further work is required unless we get reports of confusion from users.
