### ISSUE TITLE
build: CircleCI for system tests

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#7407]
Here are the requirements we discussed for the short-term (through roughly mid-August):

- [ ] Test dashboard
- [ ] Show pass/fail history for each test
- [ ] Show run time of test over time
- [ ] Show performance of benchmarks over time
- [ ] Show other test metrics over time, like allocator test metrics
- [ ] Continuous load tests
- [ ] Collect heap, CPU, and jemalloc profiles for longer-running tests
- [x] Save historical logs
- [x] Schedule tests (done: using AppEngine/cron)

Will update this with links to separate issues for each of these items once those are created.

cc @jordanlewis @petermattis @WillHaack

**Comment by jordanlewis** [comment]
Currently experimenting with a self-hosted TeamCity instance which satisfies most of these requirements.  There's a instance available at http://teamcity.cockroachdb.com. Guest login is currently turned on but registration is not.

**Comment by cuongdo** [comment]
Closing because the momentum has swung toward TeamCity
