### ISSUE TITLE
sql: CREATE MATERIALIZED VIEW ... WITH NO DATA is not supported

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#74083]
**Describe the problem**

pgdump contains the following syntax

```sql
CREATE MATERIALIZED VIEW table_name
    [ (column_name [, ...] ) ]
    [ WITH ( storage_parameter [= value] [, ... ] ) ]
    [ TABLESPACE tablespace_name ]
    AS query
    [ WITH [ NO ] DATA ]
```

Please describe the issue you observed, and any steps we can take to reproduce it:

getting error

```sql
I'm seeing a parse error upon a PGDUMP import ERROR: postgres parse error: at or near "with": syntax error
```

**To Reproduce**

import pgdump containing the syntax

**Environment:**
 - CockroachDB version unknown
 - Server OS: unknown
 - Client app`cockroach sql`

**Additional context**
What was the impact?

Possible workaround by supplying https://www.cockroachlabs.com/docs/v21.2/migrate-from-postgres.html#ignore-unsupported-statements

Jira issue: CRDB-11909

**Comment by otan** [comment]
i think this is an easy-ish starter project.
