### ISSUE TITLE
vtable: incorrect order of columns in new unimplemented virtual tables

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#74101]
The tables added in #60758 have out-of-order columns with respect to what Postgres has. This should be corrected.

Though we've already created a release with out-of-order columns for these tables, the ongoing compatibility burden is probably not worth it here to leave it alone.

See comment here: https://github.com/cockroachdb/cockroach/pull/60758#issuecomment-998273936

**Comment by rafiss** [comment]
fixed by https://github.com/cockroachdb/cockroach/pull/75461
