### ISSUE TITLE
kvserver/raftentry: raft.entrycache.bytes metric out of bounds

### ISSUE THREAD

**Issue by benlatern** [cockroachdb/cockroach#74129]
when set the defaultRaftEntryCacheSize = maxInt32,the metric 'raft.entrycache.bytes' will display as negative.
It might be due to the metric‘s calculation?
In cache.go:func (c *Cache) Add(id roachpb.RangeID, ents []raftpb.Entry, truncate bool)
It only limit the bytesGuessed <= maxBytes and wouldn't check whther curSize+bytesGuessed <= maxBytes.
Hope Your Reply.

Jira issue: CRDB-11929

**Comment by erikgrinaker** [comment]
Thanks for the report @benlatern, we'll have a look!
