### ISSUE TITLE
sql: don't attempt index rebuild for rollback of DROP INDEX

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#74146]
As we migrate the index backfiller to account for the eventual removal of non-MVCC operations, we need to be able to account for in-progress schema changes that might be restored from backups.  Such schema changes might have in-flight state that assumes that the non-MVCC operations are still available.  However, we would like there to be point in time after which no non-MVCC operations will be issued.

To help facilitate this, we would like to be able to fail in-progress schema changes that depend on non-MVCC operations and the old index backfiller.

However, failing a `DROP INDEX` schema changes itself depends on rebuilding an index (to undo the drop).

One solution here is to never rollback failed `DROP INDEX` attempts and instead allow the `DROP INDEX` to succeed and return a partial success. This would allow us to handle some tricky cases, such as restoring a schema change that is already attempting to revert a failed drop index.

Specifically, we would like to:

- [ ] No longer reverse `DROP INDEX` mutations. Instead, they will be left as is and the rollback will re-attempt completing the drop and the GC job creation
- [ ] When resuming a mutation, if we see an index mutation will Rollback == true, we do not proceed with it. Instead proceed with a drop of that index.

**Comment by ajwerner** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/75727.
