### ISSUE TITLE
sql: schema change jobs should carry version information

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#74151]
To affect a schema change, we currently add some set of mutations on the relevant table descriptor and create a schema change job that makes assumptions about the meaning of those mutations.

To facilitate safe modifications of the schema changes, it would be nice if a schema change job persisted information about the active cluster version that created the job so that the schema change job could be sure about the assumptions used to construct the mutations without relying on inferring those assumptions based on the state of the mutations.

As a pre-requisite it would be nice if the there was a way to retrieve the cluster version that was active at the beginning of a transaction.

Jira issue: CRDB-11943

**Comment by ajwerner** [comment]
@stevendanna did you see https://github.com/cockroachdb/cockroach/issues/73808?
