### ISSUE TITLE
demo: support add,decom,recom,restart,shutdown with --global cluster

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#74168]
**Is your feature request related to a problem? Please describe.**
in a non-global cluster, it is possible to demo adding/removing and restarting nodes of a demo cluster. It would be very useful to have the same experience with a demo cluster provisioned with `--global` flag.

```sql
root@127.0.0.1:26257/movr> \demo shutdown 3
internal server error: shutting down nodes is not supported in --global configurations
```

**Describe alternatives you've considered**
Using demo with explicit MR localities instead of relying on `--global`

Jira issue: CRDB-11949

**Comment by awoods187** [comment]
This came up again as needed for training courses too. cc @jseldess @dweatherbee

**Comment by jseldess** [comment]
Yes, in the mulit-region Cockroach U course that @kikiya is building, we can't both simulate global latencies and scaling/survivability scenarios for students. At the moment, the course is not using `--global` so as to be able to simulate survivability, so the parts dealing with regional latencies are not nearly as effective as they could be.
