### ISSUE TITLE
bazel: yarn download error on freebsd upon `dev build cockroach`

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#74208]
**Describe the problem**

```
kena@kenax ....com/cockroachdb/cockroach %  ./dev build cockroach
TMPDIR set to /tmp/tmp.pt7YeG66
$ bazel build //pkg/cmd/cockroach:cockroach --config=with_ui
INFO: Build option --define has changed, discarding analysis cache.
INFO: Repository npm instantiated at:
  /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/WORKSPACE:177:13: in <toplevel>
  /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/build_bazel_rules_nodejs/index.bzl:83:18: in yarn_install
Repository rule yarn_install defined at:
  /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:917:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'npm':
   Traceback (most recent call last):
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 813, column 36, in _yarn_install_impl
                is_windows_host = is_windows_os(repository_ctx)
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/build_bazel_rules_nodejs/nodejs/private/os_name.bzl", line 65, column 19, in is_windows_os
                return os_name(rctx) == OS_NAMES[0]
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/build_bazel_rules_nodejs/nodejs/private/os_name.bzl", line 62, column 9, in os_name
                fail("Unsupported operating system {} architecture {}".format(os_name, arch))
Error in fail: Unsupported operating system freebsd architecture amd64
```

**To Reproduce**

freebsd 13, run the command above

**Expected behavior**

Either:
- the thing works as-is, or
- there's some information in a README file about how to tell the tool to use a locally-installed yarn

(NB: `make build` works)

Epic CRDB-8036

Jira issue: CRDB-11971

**Comment by knz** [comment]
fwiw, `dev build cockroach-short` does not encounter this error

**Comment by knz** [comment]
Ok so thanks to @irfansharif , we found out two different things:

1. the build code in `rules_nodejs` does not appear to be able to run the commands `node` and `yarn` from a system-wide installation. 

   I consider this to be a bug. Since we seem at peace with running a system-wide `make` (see #74209), I consider that the opt-in capability to run a system-wide `node`, `yarn` and `npm` a prerequisite.

   (FWIW, my system-wide node and yarn match the required versions for CockroachDB. After all, `make build` works fine.)

2. there is a PR upstream to add freebsd support to `rules_nodejs` [here](https://github.com/bazelbuild/rules_nodejs/pull/2991), but it's stalled on the fact that the NodeJS project does not pre-build binaries for anything else than linux/macos/windows (see [this issue](https://github.com/nodejs/Release/issues/708)).  `rules_nodejs` only knows how to run from pre-built binaries downloaded from the NodeJS project, so even if it knew about freebsd it would still remain empty-handed without the upstream (NodeJS) compiled zip.

   Here I don't know exactly what's broken in the ecosystem: nodejs does build *from source* on a wider range of platforms. Why don't the folk who create `rules_nodejs` build nodejs from source on each platform, instead of depending on pre-built binaries? 

That said, IMHO I find that point (1) above should receive the most attention. 

Remember, we have customers who have approached us to build/run CockroachDB on PPC platforms and S/390. This FreeBSD situation is hardly an exception. **These community users have been able to make progress and use CockroachDB on their systems by running `make build` invocations, for the longest time already.** These folk have been able to do this, in turn thanks to dozens/hundreds of contributors on those platforms who provide standardized system-wide packages for all build tools, including `node` and our other UI tools.

And now in this "bazel world", we are subjecting ourselves to the restricted mindset / limited experience of the (very small) team of developers from `rules_nodejs`, who both try to insist that they don't want to support system-wide tools, and at the same time are unable to provide support as many platforms as supported by the underlying deps (nodejs, yarn etc).

Isn't there here something to learn?

Isn't anyone else bothered that this bazel-node/yarn situation is closing many doors in terms of portability that were previously open, in all versions of CockroachDB until 22.1? 

In my opinion, a good next step here would be to patch `rules_nodejs` to introduce proper support for delegating invocations to the system-wide tool, instead of depending on pre-built binaries.



cc @rickystewart

**Comment by rickystewart** [comment]
@knz If you point me to where I can find FreeBSD executables for `node` and `yarn` at the correct versions (today that's 16.13.0 for `node` and 1.22.11 for `yarn`), I can package them up and mirror them in our GCS bucket that contains all of the other build dependencies.

**Comment by knz** [comment]
(I still think it'd be quite easier to have the code run the binaries on the host machine, but since you're asking...)

The URL is concatenating the repository URL with the path to the package binary.

The repository is decided from `uname`, which is the "platform" string inside bazel: freebsd12, freebsd13, freebsd14.
```
https://pkg.freebsd.org/FreeBSD:12:amd64
https://pkg.freebsd.org/FreeBSD:13:amd64
https://pkg.freebsd.org/FreeBSD:14:amd64
```

Then the package path is `/latest/All/<name>-<version>.pkg`

So we have currently:

```
/latest/All/node16-16.13.0.pkg
/latest/All/npm-node16-8.3.2.pkg
/latest/All/yarn-node16-1.22.17_2.pkg
```

For example:
```
https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/node16-16.13.0.pkg
```

These .pkg archives are just .txz files in disguise.

**Comment by rickystewart** [comment]
I posted more details over at https://github.com/bazelbuild/rules_nodejs/pull/2991. With a small patch to `nodejs/private/os_name.bzl` (included in the comment I left), plus the following patch to `cockroach`:

```
diff --git a/WORKSPACE b/WORKSPACE
index ff2011c1a8..06f94023b5 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -23,11 +23,19 @@ http_archive(
 )
 
 # Like the above, but for nodeJS.
+http_archive(
+    name = "rules_nodejs",
+    sha256 = "1f9fca05f4643d15323c2dee12bd5581351873d45457f679f84d0fe0da6839b7",
+    urls = [
+        "https://storage.googleapis.com/public-bazel-artifacts/bazel/rules_nodejs-core-5.4.0.tar.gz",
+    ],
+)
+
 http_archive(
     name = "build_bazel_rules_nodejs",
-    sha256 = "cfc289523cf1594598215901154a6c2515e8bf3671fd708264a6f6aefe02bf39",
+    sha256 = "2b2004784358655f334925e7eadc7ba80f701144363df949b3293e1ae7a2fb7b",
     urls = [
-        "https://storage.googleapis.com/public-bazel-artifacts/bazel/rules_nodejs-4.4.6.tar.gz",
+        "https://storage.googleapis.com/public-bazel-artifacts/bazel/rules_nodejs-5.4.0.tar.gz",
     ],
 )
 
@@ -181,18 +189,6 @@ go_register_toolchains(nogo = "@cockroach//:crdb_nogo")
 # Configure nodeJS.
 load("@build_bazel_rules_nodejs//:index.bzl", "node_repositories", "yarn_install")
 
-node_repositories(
-    node_urls = [
-        "https://storage.googleapis.com/public-bazel-artifacts/js/node/v{version}/{filename}",
-    ],
-    node_version = "16.13.0",
-    package_json = ["//pkg/ui:package.json"],
-    yarn_urls = [
-        "https://storage.googleapis.com/public-bazel-artifacts/js/yarn/v{version}/{filename}",
-    ],
-    yarn_version = "1.22.11",
-)
-
 # install external dependencies for pkg/ui package
 yarn_install(
     name = "npm",
@@ -202,6 +198,7 @@ yarn_install(
     ],
     package_json = "//pkg/ui:package.json",
     strict_visibility = False,
+    node_repository = "local_node",
     yarn_lock = "//pkg/ui:yarn.lock",
     links = {
       "@cockroachlabs/crdb-protobuf-client": "//pkg/ui/workspaces/db-console/src/js:crdb-protobuf-client",
@@ -401,6 +398,7 @@ register_toolchains(
     "//build/toolchains:cross_arm64_macos_toolchain",
     "//build/toolchains:cross_arm64_macos_arm_toolchain",
     "//build/toolchains:dev_darwin_x86_64_toolchain",
+    "//build/toolchains:node_freebsd_toolchain",
 )
 
 http_archive(
@@ -435,3 +433,9 @@ http_archive(
         "https://storage.googleapis.com/public-bazel-artifacts/java/railroad/rr-1.63-java8.zip",
     ],
 )
+
+new_local_repository(
+    name = "local_node_freebsd_amd64",
+    path = "/usr/local",
+   build_file_content = """exports_files[("bin/node")]""",
+)
diff --git a/build/toolchains/BUILD.bazel b/build/toolchains/BUILD.bazel
index 54d09ddf31..0d55c4a70f 100644
--- a/build/toolchains/BUILD.bazel
+++ b/build/toolchains/BUILD.bazel
@@ -1,4 +1,5 @@
 load("@bazel_skylib//rules:common_settings.bzl", "bool_flag")
+load("@rules_nodejs//nodejs:toolchain.bzl", "node_toolchain")
 
 # We define a number of toolchains, each of which has a name of the form:
 #     cross_HOST_TARGET_toolchain
@@ -262,6 +263,7 @@ toolchain(
 # This is the dev macOS toolchain which uses the same version of Clang that we
 # use in CI. We don't have a dev macOS toolchain for ARM yet because Clang
 # doesn't publish compilers that run on M1 Macs.
+
 toolchain(
     name = "dev_darwin_x86_64_toolchain",
     exec_compatible_with = [
@@ -279,6 +281,7 @@ toolchain(
     toolchain_type = "@bazel_tools//tools/cpp:toolchain_type",
 )
 
+
 platform(
     name = "darwin_x86_64",
     constraint_values = [
@@ -287,6 +290,20 @@ platform(
     ],
 )
 
+toolchain(
+    name = "node_freebsd_toolchain",
+    exec_compatible_with = [
+        "@platforms//os:freebsd",
+    ],
+    toolchain = ":node_freebsd_local_toolchain",
+    toolchain_type = "@rules_nodejs//nodejs:toolchain_type",
+)
+
+node_toolchain(
+    name = "node_freebsd_local_toolchain",
+    target_tool_path = "/usr/local/bin/node",
+)
+
 # There are aliases for each of these flags defined in .bazelrc; for example,
 # --crdb_test instead of --//build/toolchains:crdb_test_flag.
 #

```

... then I can get `cockroach` to *start* building. However I have not gotten the build to succeed, and it fails with the following error:

```
/usr/home/ricky/.cache/bazel/_bazel_ricky/5066011bb5c40bf5236d56a5083f06db/external/npm/_/pkg/ui/node_modules/@bazel/typescript/npm_version_check.js:17
  throw new Error(`Expected package major version to equal @build_bazel_rules_nodejs major version
  ^

Error: Expected package major version to equal @build_bazel_rules_nodejs major version
    @bazel/typescript - 4.1.0  
    @build_bazel_rules_nodejs - 5.4.0
  See https://github.com/bazelbuild/rules_nodejs/wiki/Avoiding-version-skew
    at Object.<anonymous> (/usr/home/ricky/.cache/bazel/_bazel_ricky/5066011bb5c40bf5236d56a5083f06db/external/npm/_/pkg/ui/node_modules/@bazel/typescript/npm_version_check.js:17:9)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

Not sure how to resolve it. The normal `git submodule update --init --recursive` thing did not work.

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-11971](https://cockroachlabs.atlassian.net/browse/CRDB-11971) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-74208`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by rail** [comment]
Manually synced with Jira
