### ISSUE TITLE
Closed: CAP theorem

### ISSUE THREAD

**Issue by omgj** [cockroachdb/cockroach#7422]
I thought this was an unsolved problem, you guys have solved it?

**Comment by tschottdorf** [comment]
No, CockroachDB is a CP system. A majority of replicas need to be up for
the corresponding data to be available.

On Thu, Jun 23, 2016, 08:36 omgj <notifications@github.com> wrote:

> I thought this was an unsolved problem, you guys have solved it?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/7422>, or mute the thread
> <https://github.com/notifications/unsubscribe/AE135B1eW9q91m4W2J55rkgPQrJbUyGcks5qOn3SgaJpZM4I8wv5>
> .
>
-- 

-- Tobias
