### ISSUE TITLE
Add ability to cancel statement diagnostics from the frontend

### ISSUE THREAD

**Issue by lindseyjin** [cockroachdb/cockroach#74226]
**Is your feature request related to a problem? Please describe.**
Currently, we do not have any way to cancel already created statement diagnostics from the frontend console.

**Describe the solution you'd like**
We would like to add the functionality to cancel statement diagnostic requests that are still waiting on a result. 
The backend API for this has already been created in https://github.com/cockroachdb/cockroach/issues/73863.

**Additional context**
Figma mocks: https://www.figma.com/file/xdmwvnFQd6KkO9RJ0XLDH0/22.1_SQL-obsrv_query-performance?node-id=5178%3A142577

Epic: CRDB-6619

**Comment by THardy98** [comment]
Ran into an issue while working on this issue.

Currently, the backend cancellation API uses a statement fingerprint string provided by the frontend in a query to determine the corresponding diagnostic request ID that needs to be cancelled/expired.

The frontend can sometimes provide a statement fingerprint that contains placeholders which come in the form of single-quoted underscores `'_'`. The single quotes aren't escaped prior to their use in the query and consequently cause an error. Not certain, but this issue could also highlight a potential sql injection possibility.

Alternatively, the frontend already has the diagnostic request ID and can directly pass it to the backend, removing the need to pass a statement fingerprint string, and the need to retrieve the ID via a query altogether.

I'm not certain of the amount of change this would require, but under a cursory look I think it would be relatively simple.

cc @yuzefovich for your input on this

**Comment by yuzefovich** [comment]
I didn't realize that we already had the request ID - using that to cancel on the backend would actually be preferable over the current implementation. I too think it'll be a pretty small change.
