### ISSUE TITLE
kv: don't heap allocate transaction deadline timestamp

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#74224]
**NOTE: this needs to wait for the v22.2 release cycle.**

We currently heap allocate when maintaining a `kv.Txn`'s deadline [here](https://github.com/cockroachdb/cockroach/blob/0dcac1458ade38e7fcd280f9582938c3a43a0901/pkg/kv/txn.go#L784). The use of `*hlc.Timestamp` to represent an optional timestamp is mostly an anti-pattern at this point, now that the type has an `IsEmpty()` method that corresponds to the type's zero value.

In a run of sysbench's `oltp_point_select` workload, this was the 9th most frequent source of heap allocations, accounting for over **1%** of total allocations.

```
----------------------------------------------------------+-------------
      flat  flat%   sum%        cum   cum%   calls calls% + context 	 	 
----------------------------------------------------------+-------------
...
----------------------------------------------------------+-------------
                                          63603658   100% |   github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*leasedDescriptors).maybeUpdateDeadline /go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/leased_descriptors.go:217
  63603658  1.06% 13.90%   63603658  1.06%                | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).UpdateDeadline /go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:784
----------------------------------------------------------+-------------
```

Unfortunately, we can't immediately fix this, because doing so requires marking `EndTxnRequest.Deadline` as non-nullable. This causes mixed-version complications because v21.2 processes won't handle an empty deadline timestamp the same as they would a nil deadline timestamp. So to get to where we want to be, we first need to handle empty deadlines the same as nil deadlines server-side in the v22.1 release. Then we can address the rest of this in v22.2.

Jira issue: CRDB-12008

**Comment by ajwerner** [comment]
This issue highlights how hopeless a transition to `vtprotobuf` and its pooling feels. If we had infinite elbow grease, is that the route we'd take?

**Comment by ajwerner** [comment]
@nvanbenschoten we can do this now, yeah?
