### ISSUE TITLE
Absolute Path in Storage Directory prevents Moving

### ISSUE THREAD

**Issue by smklein** [cockroachdb/cockroach#74231]
# My Assumption

Based on comments from cockroach devs, I'm under the impression that storage directories *should* be movable:
- https://forum.cockroachlabs.com/t/can-i-change-data-folder-at-any-time-or-just-new-nodes/1218
> moving data should work as you describe. A data directory isn’t tied to its location or the underlying file system (well, shouldn’t be and we’ve never seen any bugs with that regard in our testing).
- https://github.com/cockroachdb/cockroach/issues/21856
> (some issue) is likely because we're using an absolute path somewhere. This shouldn't happen as this makes it impossible to move the data directories.

This is a big assumption of mine! If this is wrong, the rest of this issue should likely be considered somewhat differently.

# Background

At my company, we've been using cockroach as our storage layer. For the vast majority of our tests, we're interested in running it locally as a single node. However, doing so, we noticed some latency in populating tables + indices for every single test. As an optimization, we do the following:

1. During our build, run cockroach as a single-node, using a "well-known" storage directory. Populate the tables + indices *once*. Terminate cockroach. We refer to this storage directory as our "seed" storage.
2. For all subsequent tests, *copy* the seed storage directory used in step (1). Each test gets a unique storage directory, which should look identical (to start), and which should never overlap.

This cuts out several seconds of latency for all tests, which we thought was a big win, except...

# The Problem

We've been seeing corruptions and [test flakes](https://github.com/oxidecomputer/omicron/issues/540), and have largely narrowed it down to the `temp-dirs-record.txt` being used in the storage directory: https://github.com/cockroachdb/cockroach/blob/master/pkg/server/config.go#L74

This file contains an **absolute path** to the original storage directory, which is **not updated, even after moving the storage directory**. This means that if we create a storage directory in:

`/tmp/foo` it'll contain a `temp-dirs-record.txt` file that *always* points to `/tmp/foo`, even if the storage directory is moved to `/tmp/bar`.

In our use-case, this means the temporary directory in the "seed" storage directory may be modified concurrently by a number of cockroach instances, which is unexpected. However, even in the case of "simply moving" the storage directory, it seems like a bad idea to keep a reference like an absolute path around to an old directory.

This concurrent access by multiple cockroach instances has resulted in a variety of bad behaviors:
- I've seen `ERROR: could not cleanup temporary directories from record file: unlinkat /tmp/crdb-base/cockroach-temp315287726: directory not empty`, as multiple cockroach instances attempt clearing the directory concurrently
- We've seen data corruption just starting new cockroach processes, since presumably they don't expect to all share a temp directory.

# The Proposed Fix

Would it be possible for all paths stored in storage directories to be *relative* to the base of the storage directory?
This would enable both the moving and "cloning" use-case we described.

**Environment:**
 - CockroachDB version: Observed in 21.1.10, still seems present in 21.1.12
 - Server OS: Linux

Jira issue: CRDB-11980

**Comment by tbg** [comment]
Hi @smklein, thanks for the report. Dealing with temp directories is sort of annoying and using relative paths doesn't really fix the root problem, does it? If I have a store dir initially at `/foo/s1` and it references `../tmp` (i.e. `/tmp` in absolute terms) then copying that store to `/foo/s2` will reference the same `/tmp` directly which from the looks of it brings you back to square one. And generally, this is what you want, too, as production deployments often configure a separate partition as a temp dir and want that to be robust.

I think a dead simple thing you could do for your use case is to remove the `temp-dirs-record.txt` file altogether. Would that solve the problem? This file's purpose is generally to clean up leftover data from an older instance of the process but this isn't something you really care about here.

**Comment by smklein** [comment]
> Hi @smklein, thanks for the report. Dealing with temp directories is sort of annoying and using relative paths doesn't really fix the root problem, does it? If I have a store dir initially at `/foo/s1` and it references `../tmp` (i.e. `/tmp` in absolute terms) then copying that store to `/foo/s2` will reference the same `/tmp` directly which from the looks of it brings you back to square one. And generally, this is what you want, too, as production deployments often configure a separate partition as a temp dir and want that to be robust.

Ahhh, right. I saw that the temp directory was usually a subdirectory within store, but I see that with [`--temp-dir`](https://www.cockroachlabs.com/docs/stable/cockroach-start-single-node.html#:~:text=see%20Store%20below.-,--temp-dir,-The%20path%20of) argument it could actually be anywhere in the filesystem, not always contained within the storage directory.

It seems a little odd to me that `--temp-dir` is a runtime flag, but also stored within the storage directory itself. If a different value of `--temp-dir` is passed between different instantiations of cockroach, would the old value in `temp-dirs-record.txt` be ignored? Or would the new value override it?

> I think a dead simple thing you could do for your use case is to remove the `temp-dirs-record.txt` file altogether. Would that solve the problem? This file's purpose is generally to clean up leftover data from an older instance of the process but this isn't something you really care about here.

I had been wondering about this! I was apprehensive about going down this route, because it felt a little bit like "relying on the implementation details of cockroach" (rather than the documented API).

You'd consider removal of this text file to be a safe operation? Is there any other way to say "please flush and delete all temporary directory state"?

**Comment by tbg** [comment]
> You'd consider removal of this text file to be a safe operation? Is there any other way to say "please flush and delete all temporary directory state"?

A graceful shutdown, if I'm not getting mixed up, should result in an empty file. A graceful shutdown is also basically instantaneous on a single-node cluster, which I gather is what you're using.

> I had been wondering about this! I was apprehensive about going down this route, because it felt a little bit like "relying on the implementation details of cockroach" (rather than the documented API).

That is true, but also note that taking copies of store directories is not something we officially support. This quickly causes all kinds of problems when you run a multi-node deployment, which aren't avoidable even when you have consistent filesystem-level snapshots. The "true" way of doing what you're doing is using BACKUP/RESTORE but I understand that for unit tests you just want the fastest thing imaginable.

**Comment by andreimatei** [comment]
> It seems a little odd to me that --temp-dir is a runtime flag, but also stored within the storage directory itself. If a different value of --temp-dir is passed between different instantiations of cockroach, would the old value in temp-dirs-record.txt be ignored? Or would the new value override it?

I believe that, If the value of `--temp-dir` changes between restarts, the previous value is used to delete the previous temp files (through that `temp-dirs-record.txt` file), and then the new flag value is saved in the file for the future.

**Comment by andreimatei** [comment]
As Tobi said, copying stores around is not something we talk about with a full mouth, but I think we do want it to just work for simple cases. In particular, here, I think that when `--temp-store` is not used (and so the temp dir is supposed to be inside the store dir), the fact that moving the store dir causes an interaction with files outside the store is a straight-up bug. I think #21856 was closed too quickly; that issue was complaining about the reverse problem - which is that the deletion of the absolute path would fail and prevent CRDB from starting. Your problem is that the deletion of the absolute path works too well. I'll re-open that issue, and see if other people around want to do something about it.

**Comment by smklein** [comment]
Sound good, I appreciate the feedback. FWIW, our flakiness issues are likely resolved by @tbg 's suggestion to perform graceful shutdown, but I still think limiting scope of absolute paths - where possible, as you mentioned @andreimatei  - would make these use cases less hazardous.
