### ISSUE TITLE
storage: rejecting command with timestamp in the future

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#7423]
Running `block_writer` against a local 3-node cluster started using `roachdemo`, I saw this error message:

```
2016/06/23 09:34:57 error running blockwriter 94f9781c-2ebb-47bc-a82b-5c521126540f: pq: storage/store.go:1743: rejecting command with timestamp in the future: 1466688896950912000 (2.260292166s ahead)
```

See also #4421 which relates to being more principled about what errors we leak to the client. This issue is concerned with why this error occurred in the first place given that both `block_writer` and the 3 `cockroach` nodes were all running on the same system.

Attached are the logs from the 3 nodes. I also have the rocksdb state, but I presume that is less interesting. 

[cockroach-logs.zip](https://github.com/cockroachdb/cockroach/files/330069/cockroach-logs.zip)

**Comment by tschottdorf** [comment]
Your first log has this in it:

```
W160623 09:34:54.685604 util/hlc/hlc.go:165  backward time jump detected (-2.265334 seconds)
```

Probably something on your machine just ruthlessly adjusted your clock. Even if all nodes are running on the same machine, this error can still occur (pick a timestamp, clock rewinds, use that timestamp, complain).

**Comment by mintzhao** [comment]
[2017-05-19 22:13:52]  pq: storage/store.go:2417: rejecting command with timestamp in the future: 1495205780963617195 (42m27.968992266s ahead)

**Comment by bdarnell** [comment]
@mintzhao It looks like you need to run NTP to synchronize the clocks on your servers (they're 42 minutes apart according to this message!). Also note that replies to closed issues often fall through the cracks; it's usually better to open a new issue than to reply to a closed one.

**Comment by mintzhao** [comment]
@bdarnell I think I already know why caused this issue. I ran the instance with docker at mac in daemons. And after I sleep the mac and when I back up again, this issue occurs.
