### ISSUE TITLE
Provide a way to link crdb_internal.cluster_queries to crdb_internal.statement_statistics

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#74267]
Currently there is no key between crdb_internal.cluster_queries and crdb_internal.statement_statistics. 

We should provide a way for users to view the historical statement statistics/plans (statement_statistics) of an active query/statement (cluster_queries). 

Jira issue: CRDB-11996

**Comment by mickmcg** [comment]
This would be very useful for our DBmarlin monitoring solution. We use CLUSTER_QUERIES to see the session_id, query_id, user_name etc but would like to be able to link to STATEMENT_STATISTICS which has the plan_hash and statistics.
