### ISSUE TITLE
verify that multi-range txn ratchets up its timestamp

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#743]
TxnCoordSender.sendBatch propagates transaction timestamps from each inner response to the batch response, but it does not pass this information from one response to the next request. This is a problem for EndTransaction, which requires the timestamps from all operations.

This also means that when we parallelize requests in a batch (as indicated in a TODO comment), we must special-case the EndTransaction, if any.

**Comment by tamird** [comment]
@spencerkimball any updates on this?

**Comment by tschottdorf** [comment]
this looks like something we could easily fix but the mechanism will also change a lot in the near future (RFC #1275). I would just revisit it with the RFC.

**Comment by tschottdorf** [comment]
this is basically done, but I'm going to look into adding a test for this specific issue as I don't think we have one.

**Comment by tschottdorf** [comment]
Kenji, I assigned you to this since what you're looking at right now is pretty much that. You can hijack this issue or create another one for your work and close this.

**Comment by kkaneda** [comment]
Sure, Tobias. Sounds good! Yes, the second test case in #3161 is for this issue, I think. In the test, we didn't pass txn ID, so the restarted txn uses a new different txn ID (and has a conflict with a write intent made by itself).
