### ISSUE TITLE
client: remove dependency on (*grpc.ClientConn).State()

### ISSUE THREAD

**Issue by d4l3k** [cockroachdb/cockroach#7430]
grpc-go has removed the `(*grpc.ClientConn).State()` function which we use for detection when a connection is down/ready to be used. We should probably remove all uses of this function so we no longer have to depend on an old version of grpc-go.

Related to grpc/grpc-go#690.

https://github.com/cockroachdb/cockroach/blob/master/client/rpc_sender.go#L55:L63

We removed the other use in #7399.

**Comment by d4l3k** [comment]
@tamird I removed this dep, but when I update the grpc dependancies it throws this error (for all the /_status/ tests). Any thoughts?
```
E160720 16:46:41.551691 server.go:490  http2: server: error reading preface from client 127.0.0.1:49478: bogus greeting "GET /_status/metrics//1 "
I160720 16:46:41.551791 server/status_test.go:174  could not GET https://127.0.0.1:49466/_status/metrics//1 - Get https://127.0.0.1:49466/_status/metrics//1: EOF
--- FAIL: TestMetricsEndpoint (1.71s)
	status_test.go:194: There was an error retrieving https://127.0.0.1:49466/_status/metrics//1
```

**Comment by tamird** [comment]
Did you also update gogo/protobuf?

**Comment by d4l3k** [comment]
Yes. See the referenced PR.
