### ISSUE TITLE
sql: minimize TableDescriptor copies/re-allocation/serialization

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#74352]
`descpb.TableDescriptor` structs are `1104` bytes large (ignoring internal references). `tabledesc.immutable` structs embed a `descpb.TableDescriptor` and are `1168` byte large. Due to this size, we should strive to minimize the number of times that we copy, re-allocate, or serialize these structs on the hot path of query processing.

@ajwerner, a man ahead of his time, has TODOs that allude to this:
https://github.com/cockroachdb/cockroach/blob/3471dc50db8406f3faa638940492dbe0cab53435/pkg/sql/colfetcher/colbatch_scan.go#L203-L207

In recent experimentation, I've observed these copies in CPU and heap profiles. On a 100% read workload, `immutable` allocations are not only the second largest source of heap allocations (by size), but they also appear prominently in CPU profiles. For instance, in kv100 (which is CPU-bound), `TableReaderSpec.BuildTableDescriptor` is responsible for **1.33%** of all CPU utilization.

<img width="1575" alt="Screen Shot 2021-12-30 at 6 56 53 PM" src="https://user-images.githubusercontent.com/5438456/147795379-e36ee645-0b83-44e8-bd4d-9b7485cb03c0.png">
 

Jira issue: CRDB-12042

**Comment by ajwerner** [comment]
I've had a harder time getting this to show up in benchmarks that do things more complicated than KV workloads, but would be happy to see this done. It'd be a good intern project.

**Comment by postamar** [comment]
At present, in light of #74722 being merged, this task boils down to rooting out `descpb.TableDescriptor` messages from `execinfrapb` protos, instead replacing them with an ID + version pair which can be looked up in the `descs.Collection`. 

The end goal here is to make `descs.Collection` the only point of origin of `catalog.Descriptor`s. Not catalogkv, not distsql specs... Backups would get around this by having their own version of a `descs.Collection`, possibly implementing the same interface, or something like that.

**Comment by postamar** [comment]
I'm curious how bad things still are these days?

**Comment by ajwerner** [comment]
The good news is that we no longer put table descriptors into these protos, so I think we can close this issue.
