### ISSUE TITLE
Error creating foreign key and columns in same transaction - order related.

### ISSUE THREAD

**Issue by leenooks** [cockroachdb/cockroach#74360]
**Describe the problem**
Howdy,

I'm seeing an unexpected error when modifying a table and added a foreign key.

If, during the transaction, the new foreign key column is also being defined with other columns, if it is not specified first, the transaction errors and references the wrong column.

IE: Why is column order important? And, why is the error referencing a column that is not part of the contraint? (I'm thinking this is a bug...)

Here is an example (same columns and foreign key being created):

-- bad --

```
dev@crdb:26257/clrghouz> begin;
BEGIN
Time: 1ms total (execution 1ms / network 1ms)

dev@crdb:26257/clrghouz  OPEN> alter table "zones" add column "ztid" varchar(255) null, add column "system_id" integer not null;
ALTER TABLE
Time: 8ms total (execution 8ms / network 0ms)

dev@crdb:26257/clrghouz  OPEN> alter table "zones" add constraint "zones_system_id_foreign" foreign key ("system_id") references "systems" ("id");
ERROR: type of "ztid" (varchar) does not match foreign key "systems"."id" (int)
SQLSTATE: 42804

dev@crdb:26257/? ERROR> abort;
```

-- good --

```
dev@crdb:26257/clrghouz> begin;
BEGIN
Time: 1ms total (execution 1ms / network 1ms)

dev@crdb:26257/clrghouz  OPEN> alter table "zones" add column "system_id" integer not null,add column "ztid" varchar(255) null;
ALTER TABLE
Time: 24ms total (execution 23ms / network 1ms)

dev@crdb:26257/clrghouz  OPEN> alter table "zones" add constraint "zones_system_id_foreign" foreign key ("system_id") references "systems" ("id");
ALTER TABLE
Time: 10ms total (execution 10ms / network 0ms)

dev@crdb:26257/clrghouz  OPEN> commit;
COMMIT
Time: 334ms total (execution 334ms / network 1ms)
```

**Environment:**
 - CockroachDB version 21.2.2
 - Server OS: Linux/docker
 - Client app: `cockroach sql`

**Comment by ajwerner** [comment]
This feels a lot like https://github.com/cockroachdb/cockroach/issues/74360.

**Comment by ajwerner** [comment]
I mean https://github.com/cockroachdb/cockroach/issues/73798.
