### ISSUE TITLE
sql: SET mistakenly ignores malformed variable names

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#74373]
I mistakenly typed: `SET foo.bar = abc`

The statement succeeded without error (and did nothing). This is surprising.

I was expecting an error that "foo.bar is an unknown session variable" or something similar.

This problem exists on the `master` branch, but not on the 21.2 branch. So it is a recently introduced regression.

cc @rafiss @otan for triage.

**Comment by otan** [comment]
this is a postgres feature: https://www.postgresql.org/docs/current/runtime-config-custom.html

see: https://github.com/cockroachdb/cockroach/issues/70033
