### ISSUE TITLE
UI crashes when a node becomes dead

### ISSUE THREAD

**Issue by sathyamoorthybr** [cockroachdb/cockroach#74448]
**Describe the problem**

Cockroach DB web UI used to monitor the nodes, replicas crashes when one of the node becomes dead.

**To Reproduce**

All the nodes are started, active and working for sometime. Suddenly one of the nodes become dead.
Node status return below results

![NodeStatus](https://user-images.githubusercontent.com/4611102/148200753-5a5925d1-27e5-498d-80a3-f59af9ff6a03.png)

Once the node is dead, UI page at https://host:port/#/overview/list becomes blank.
The other pages like metrics, transactions etc. is available and able to access (it works as well) if I provide direct link like https://host:port//#/metrics/overview/cluster

When one of my colleague troubleshooted he found that node status DEAD is causing this problem. Decommissioning the dead node helped in this case.

**Expected behavior**
UI Shouldn't crash if a node becomes dead.

**Additional data / screenshots**
Few screenshots during debugging of UI failure
![DebuggerNodeStatus1](https://user-images.githubusercontent.com/4611102/148203302-ad8df169-19b7-48f1-9df5-87d1b5350208.png)

![DebuggerNodeStatus2](https://user-images.githubusercontent.com/4611102/148203315-1708d8cb-8bcc-4176-b0d9-89c722a04855.png)

**Environment:**
 - CockroachDB version 21.1.7
 - Server OS: Centos 7
 - Cluster is setup with 5 regions and 6 datacentres. locality is provided as `region=A,dc=1` and so on.

Jira issue: CRDB-12085

**Comment by dhartunian** [comment]
Hi @sathyamoorthybr thanks for filing an issue. I attempted to reproduce this with `21.1.7` and am unable to see the error when I kill a node on a 3 node cluster.

My other nodes successfully load the page:
![Screen Shot 2022-01-05 at 2 59 54 PM](https://user-images.githubusercontent.com/986307/148281122-920d4730-2395-461e-b797-67f587eef073.png)

Can you perhaps share a screenshot of the error traceback in the browser console? It's not clear from your screenshots what the actual error is that's being triggered since you have breakpoints set. Thanks!

**Comment by sathyamoorthybr** [comment]
Mine is not a simple 3 node cluster but cluster with multiple regions. The locality is configured something like `region=US,dc=NY` dc means datacenter. 

To reproduce, try to start CDB with locality as `region=US,dc=NY` and make sure there are 3 nodes with this value. Now make one of the nodes in this US region as dead. After this, add new node to the cluster but with a different locality say `region=EU,dc=ITALY`. Once this new node in EU region is up, try to login to UI and check overview page. This is the scenario that happened very first time to me. After that every time when one node goes down the overview page of UI crashes.

Also below is the screen shot you requested
![ErrorTraceBack](https://user-images.githubusercontent.com/4611102/148388604-75763b4c-c345-4db0-8745-7eddb92b07f8.png)

**Comment by dhartunian** [comment]
Thanks for the additional info @sathyamoorthybr I've been able to reproduce.

Here are roachprod steps for reproducing this issue:

```
roachprod create local -n 3
roachprod stage local release v21.1.7
roachprod start local --args "--locality=region=US,dc=NY"
roachprod stop local:3
roachprod start local:3 --args "--locality=region=EU,dc=ITALY"
```

You'll see DB Console error on node 1 after the 3rd node is restarted with different region:

```
bundle.js:1223 Error: Unreachable point with value: 7 
    at S_ (bundle.js:1264)
    at ny (bundle.js:1264)
    at render (bundle.js:1264)
    at p.value (bundle.js:1190)
    at $i (bundle.js:1223)
    at Zi (bundle.js:1223)
    at Ps (bundle.js:1223)
    at Nc (bundle.js:1223)
    at Mc (bundle.js:1223)
    at wc (bundle.js:1223)
gs @ bundle.js:1223
bundle.js:1264 Uncaught (in promise) Error: Unreachable point with value: 7 
    at S_ (bundle.js:1264)
    at ny (bundle.js:1264)
    at render (bundle.js:1264)
    at p.value (bundle.js:1190)
    at $i (bundle.js:1223)
    at Zi (bundle.js:1223)
    at Ps (bundle.js:1223)
    at Nc (bundle.js:1223)
    at Mc (bundle.js:1223)
    at wc (bundle.js:1223)
```

**Comment by dhartunian** [comment]
@sathyamoorthybr I am able to see a correct page after a hard refresh in my browser. Does that work for you?

**Comment by sathyamoorthybr** [comment]
No.. refresh button or relogin is ending up with same error.
