### ISSUE TITLE
Surface a Request Unit metric per statement

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#74441]
This issue tracks surfacing how many RUs are consumed per statement for CockroachDB Serverless. 

1. RU consumed is surfaced via EXPLAIN ANALYZE

Jira issue: CRDB-12080

**Comment by ajwerner** [comment]
This seems very hard given the current architecture of how we compute RUs. Potentially depends on https://github.com/cockroachdb/cockroach/pull/60589, see also https://github.com/golang/go/issues/41554. Even that wouldn't necessarily be enough, but without something like that, it's hard to imagine a path.

**Comment by andy-kimball** [comment]
I've been doing a lot of work in this area. Most queries are dominated by Storage Layer requests, not by CPU. We can also estimate CPU pretty well, especially when there isn't background work going on. I think as long as we made it clear that the RUs reported by `EXPLAIN ANALYZE` are "approximate", I think we can do this work without https://github.com/cockroachdb/cockroach/pull/60589.

**Comment by mgartner** [comment]
@DrewKimball What work remains here?

**Comment by andy-kimball** [comment]
One thing we realized after rolling out the RU estimation - it's being measured in `int64` units rather than `float64` units. This means that RUs are not being reported very accurately for small statements, like a point read (it's just reporting 0 for small statements, which is confusing).

**Comment by DrewKimball** [comment]
The first two bullet points are still left:
1. Like rowCount, RU consumed is returned as part of the result for each statement execution
2. RU consumed is surfaced as part of crdb_internal.statement_statistics

There are also some smaller things to do like reporting RUs in float64 instead of int64 as mentioned above and using grunning to measure CPU for the estimate, but I'll open separate issues for those.

**Comment by andy-kimball** [comment]
How come we'd want to return RU consumed as part of the result of statement execution? I thought we only compute RUs consumed for `EXPLAIN ANALYZE` statements?

**Comment by andy-kimball** [comment]
I'd be worried about extra overhead to gather information that will probably almost never be used. Also, we can only get an estimated amount right now, not an exact amount. @kevin-v-ngo, do you see important use cases for returning RUs from every statement execution, as opposed to just from `EXPLAIN ANALYZE`?

**Comment by kevin-v-ngo** [comment]
> I'd be worried about extra overhead to gather information that will probably almost never be used. Also, we can only get an estimated amount right now, not an exact amount. @kevin-v-ngo, do you see important use cases for returning RUs from every statement execution, as opposed to just from `EXPLAIN ANALYZE`?

This issue was not synced from JIRA and was scoped to only EXPLAIN ANALYZE. It should be closed as Done. 

There are use cases for understanding workloads (e.g., statements and transactions) that take up the most RUs over time; however, I haven't validate or yet seen explicit use cases expressed from users. It'd take it incrementally for now and to also understand how accurate and useful our existing RU estimation before capturing this in our other observability interfaces.

**Comment by DrewKimball** [comment]
Thanks for the extra context, I'll close this out.
