### ISSUE TITLE
dev: create an alias for `buildtest`

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#74457]
The `buildtest` command, available via the Makefile, is useful to complement `build` (or `buildshort`) to verify that all the code in go packages can be compiled without errors.

We want this target to check the build process, but without the overhead of actually running the test.

Ricky has explained in [this comment](https://github.com/cockroachdb/cockroach/pull/74215#issuecomment-1005141337) that we can obtain this with the following command:

```
bazel query 'kind(go_test, pkg/whatever/...)' | xargs dev build
```

However this is cumbersome to type and hard to remember.

Instead, the `dev` command should contain a shorthand alias for it.

cc @rickystewart @irfansharif 

Jira issue: CRDB-12091

**Comment by irfansharif** [comment]
Haven't investigated, but there's also https://docs.bazel.build/versions/main/command-line-reference.html#flag--build_tests_only that might be relevant.

**Comment by irfansharif** [comment]
`dev build tests` is now a thing.
