### ISSUE TITLE
Create a new role option NOSQLLOGIN to allow DB Console access and restrict SQL shell access

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#74482]
**Describe the solution you'd like**
We want to create a new role option called `NOSQLLOGIN` so that any DB user with this role option can access the DB Console but not be able to get SQL shell access. This will give customers more granular control over how to manage what access their users have within a cluster

`CREATE ROLE app_developers WITH NOSQLLOGIN;`

Epic: CRDB-12102

**Comment by dhartunian** [comment]
@thtruo backport is merged into 21.2. Should be out with 21.2.5

**Comment by thtruo** [comment]
FYI @abhinavg6 and @kevin-v-ngo

**Comment by abhinavg6** [comment]
Awesome, thanks for the quick work on this.
