### ISSUE TITLE
Unary Complement execution has different results when the parameters are different

### ISSUE THREAD

**Issue by Heoric** [cockroachdb/cockroach#74493]
```sql
root@localhost:26257/defaultdb> select ~'1';
ERROR: unsupported unary operator: ~ <string>
SQLSTATE: 22023
root@localhost:26257/defaultdb> select ~'2';
  ?column?
------------
        -3
(1 row)

```
Time: 1ms total (execution 1ms / network 0ms)

Epic CRDB-8948

Jira issue: CRDB-12112

**Comment by rafiss** [comment]
It seems like `select ~'2';` does not work in Postgres, so from a compatibility perspective, we might consider disallowing that in CockroachDB as well.

First we should investigate and determine why the behavior is different in the two examples.
