### ISSUE TITLE
sql: in function assignSequenceOptions(), when alter_sequence current_value need to compare with the new bounds, instead of old START parameter

### ISSUE THREAD

**Issue by mosquito2333** [cockroachdb/cockroach#74492]
Now in assignSequenceOptions(), when checking the descriptor of sequence, the old start parameter is compared with the new bounds.
 In fact, we should compare the last valid sequence value with the new bounds after assignSequenceOptions() when alter sequence.
 If a new start parameter is passed, start is used, otherwise the last valid sequence value is used.
```sql
DROP SEQUENCE customer_seq_alter_1;
CREATE SEQUENCE customer_seq_alter_1 MINVALUE -2 MAXVALUE 2 START WITH 1 CACHE 5 INCREMENT BY -2;
SELECT nextval('customer_seq_alter_1'); --   1
SELECT nextval('customer_seq_alter_1'); --  -1
ALTER SEQUENCE customer_seq_alter_1 INCREMENT  BY -1   MINVALUE -6 MAXVALUE 0; -- expect successful,but report an error from function assignSequenceOptions().
START value (1) cannot be greater than MAXVALUE (0)
```

**Comment by otan** [comment]
this seems to be correct?

at least, the same behaviour in postgres:

```
otan=# DROP SEQUENCE customer_seq_alter_1;
CREATE SEQUENCE customer_seq_alter_1 MINVALUE -2 MAXVALUE 2 START WITH 1 CACHE 5 INCREMENT BY -2;
SELECT nextval('customer_seq_alter_1'); --   1
SELECT nextval('customer_seq_alter_1'); --  -1
ALTER SEQUENCE customer_seq_alter_1 INCREMENT  BY -1   MINVALUE -6 MAXVALUE 0; -- expect successful,but report an error from function assignSequenceOptions().
ERROR:  sequence "customer_seq_alter_1" does not exist
CREATE SEQUENCE
 nextval
---------
       1
(1 row)

 nextval
---------
      -1
(1 row)

ERROR:  START value (1) cannot be greater than MAXVALUE (0)
```

**Comment by mosquito2333** [comment]
> this seems to be correct?
> 
> at least, the same behaviour in postgres:
> 
> ```
> otan=# DROP SEQUENCE customer_seq_alter_1;
> CREATE SEQUENCE customer_seq_alter_1 MINVALUE -2 MAXVALUE 2 START WITH 1 CACHE 5 INCREMENT BY -2;
> SELECT nextval('customer_seq_alter_1'); --   1
> SELECT nextval('customer_seq_alter_1'); --  -1
> ALTER SEQUENCE customer_seq_alter_1 INCREMENT  BY -1   MINVALUE -6 MAXVALUE 0; -- expect successful,but report an error from function assignSequenceOptions().
> ERROR:  sequence "customer_seq_alter_1" does not exist
> CREATE SEQUENCE
>  nextval
> ---------
>        1
> (1 row)
> 
>  nextval
> ---------
>       -1
> (1 row)
> 
> ERROR:  START value (1) cannot be greater than MAXVALUE (0)
> ```
But shouldn't the current value（-1）be used for comparison?

**Comment by mosquito2333** [comment]
This does not seem reasonable.

**Comment by otan** [comment]
We will always hesitate to deviate from PG behaviour due to compatibility issues.

That said, this makes sense. `ALTER SEQUENCE customer_seq_alter_1 RESTART` will reset it to the START value. This is implemented on PG but not CRDB, but if we do implement it at some stage that pre-condition needs to hold.

**Comment by mosquito2333** [comment]
> We will always hesitate to deviate from PG behaviour due to compatibility issues.
> 
> That said, this makes sense. `ALTER SEQUENCE customer_seq_alter_1 RESTART` will reset it to the START value. This is implemented on PG but not CRDB, but if we do implement it at some stage that pre-condition needs to hold.

Thank you, I get it.
