### ISSUE TITLE
sql: implement ALTER SEQUENCE ... RESTART

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#74496]
We currently do not implement the [`ALTER SEQUENCE ... RESTART [with restart]`](https://www.postgresql.org/docs/current/sql-altersequence.html).

```sql
CREATE SEQUENCE customer_seq_alter_1 MINVALUE -2 MAXVALUE 2 START WITH 1 CACHE 5 INCREMENT BY -2;
SELECT nextval('customer_seq_alter_1'); 
SELECT nextval('customer_seq_alter_1');
ALTER SEQUENCE customer_seq_alter_1 RESTART; -- does not work
```

This needs to be implemented.

See #57339 for a basis with start.

Jira issue: CRDB-12115
Epic CRDB-14049

**Comment by rai16** [comment]
I'd like to pick this up.

**Comment by sdpa** [comment]
> I'd like to pick this up.

Hi, are you still working on it? I would like to give it a shot.

**Comment by otan** [comment]
hi! just as an a fyi, we generally don't "reserve" issues for anyone; feel free to pick it up if you think you've got it!
