### ISSUE TITLE
sql: TestMultinodeCockroach is flaky

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#7450]
See https://circleci.com/gh/cockroachdb/cockroach/19574

(no issue is created since the error message is too long; will look into that)

**Comment by tschottdorf** [comment]
It failed 3x today. I'm going to send a PR disabling it.
PS it's always good to subscribe to the CircleCI master builds.

**Comment by andreimatei** [comment]
I've rewritten this code. Didn't really look what caused the timeout before, but I've stressraced it a bunch and seems to be going strong so 🙏

**Comment by tschottdorf** [comment]
Doesn't @WillHaack completely rewrite this code in his PR right now? Why would you try to fix it out from under him?

**Comment by petermattis** [comment]
Duplicate of #7689.
