### ISSUE TITLE
kvserver: recent change somehow broke GoLand's debugger

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#74559]
After fetching the latest master, I discovered that breakpoints don't seem to work in GoLand anymore. My test was as follows:
- create a temporary logic test file, say `pkg/sql/logictest/testdata/logic_test/wip` with
```
statement ok
SELECT pg_sleep(1)
```
- set the breakpoint where `pg_sleep` is implemented, say [here](https://github.com/cockroachdb/cockroach/blob/7d7ab0d5ceb1853c36935279a2f88fda81a22227/pkg/sql/sem/builtins/pg_builtins.go#L1438)
- then use this config for GoLand run target
![Screen Shot 2022-01-06 at 4 04 47 PM](https://user-images.githubusercontent.com/5135385/148469676-85be6b44-4127-4eb6-b9a0-a423ad191de8.png)
- and click `debug` button.

In my case, the test would appear stuck and never reaches the breakpoint.

I've bisected this behavior to #74315, and in particular the following diff seems to make GoLand great again:
```
diff --git a/pkg/roachpb/data.go b/pkg/roachpb/data.go
index 05805865aa..289a9a6caf 100644
--- a/pkg/roachpb/data.go
+++ b/pkg/roachpb/data.go
@@ -1871,6 +1871,10 @@ func (l *Lease) String() string {
 
 // SafeFormat implements the redact.SafeFormatter interface.
 func (l *Lease) SafeFormat(w redact.SafePrinter, _ rune) {
+       if l == nil {
+               w.SafeString("<nil>")
+               return
+       }
        if l.Empty() {
                w.SafeString("<empty>")
                return
```

It seems possible that maybe an assumption that `Lease` is never `nil` is broken, or something else. In any case, I'll open up a revert of #74315 and will leave to the @cockroachdb/kv-prs to decide what to do.

Jira issue: CRDB-12150

**Comment by knz** [comment]
NB: regardless of whether we revert the other PR, I'd like to keep this issue open. It's not normal that a debugger would choke on this code. We might want to create a smaller reproducible case then file the issue upstream at GoLand.
