### ISSUE TITLE
changefeedccl: Add metric rules for changefeed

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#74568]
Metrics framework now supports alert and aggregation rules for existing and new metrics. 
See 
https://cockroachlabs.atlassian.net/wiki/spaces/OI/pages/2384396356/Alert+and+Aggregation+Rules+for+Metrics

We should add changefeed specific alerting rules.  See the following as example:
https://github.com/cockroachdb/cockroach/blob/master/pkg/util/metric/doc.go
https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvserver/metric_rules.go

Note: as described on the wiki above, `keep in the mind that the rules that are exported through the HTTP endpoint do not get consumed programmatically today. The alerting/aggregation rules that you will define are only meant to be used as guidelines for our end users who will consume them`.  So, these rules we add are meant to be a guideline, and a best practice examples
we provide to our customers.  They function as a more structured documentation for the suggested alerting rules we have.

Jira issue: CRDB-12155

**Comment by amruss** [comment]
Things we might want to add: changefeed falling behind, changefeed failed/paused, changefeed rate
