### ISSUE TITLE
storage: TestReplicaDestroy highlights issues with marking replicas gc'ed

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#7457]
```
make stress PKG=./storage TESTS=TestReplicaDestroy

panic: replica 1 (range 1) was garbage collected

goroutine 23 [running]:
panic(0x549c5e0, 0xc820150820)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1()
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/storage/store.go:2116 +0x3a5
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8200d1b90, 0xc8201747f0)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62
```

This error makes a lot of sense with our recent changes. We've made sure that nobody gets to use Raft any more, but now we're returning errors in code paths that don't expect errors at all (because they assume Raft "always just works"). Clearly we need an audit and more graceful handling in all those paths (at least for a sentinel-error-version of the above error).

**Comment by petermattis** [comment]
I just noticed this panic today myself. If `handleRaftReady` can't return an error with panicing, why is it returning an error?

There is a similar panic in `replica_command.go:Replica.splitTrigger`.

**Comment by tschottdorf** [comment]
I don't think there are any good reasons other than bad error handling that far down in the stack, because historically all of these errors were pretty much end of the world. This one clearly isn't, and it's a first one at that.

**Comment by tschottdorf** [comment]
I'm disabling this test in #7429 since it's repeatedly blocked my fork's builds.

**Comment by petermattis** [comment]
Sure, go ahead and disable. I'm taking a look this morning.
