### ISSUE TITLE
`Alter table ... drop not null` for primary key

### ISSUE THREAD

**Issue by intech** [cockroachdb/cockroach#74594]
**Describe the problem**

Error:
```sql
SQL Error [42P16]: ERROR: column "id" is in a primary index
```

**To Reproduce**
```sql
create table "public"."settings" ("id" serial primary key, "key" varchar(255) null, "value" text null);
```
and
```sql
alter table "public"."settings" alter column "id" drop not null;
```

**Expected behavior**
Here I have a question, should this work?

**Additional data / screenshots**
[stmt-bundle-725923372483608577.zip](https://github.com/cockroachdb/cockroach/files/7832143/stmt-bundle-725923372483608577.zip)

**Environment:**

 - Version: CockroachDB CCL v21.2.3 (x86_64-unknown-linux-gnu, built 2021/12/14 15:23:22, go1.16.6)
 - Server OS: Linux/Ubuntu 20.04.1
 - Client app: `cockroach sql`

**Comment by otan** [comment]
this should not work. PRIMARY KEYs cannot have NULL columns.

you get the same error in PG!
