### ISSUE TITLE
Support hash-sharded index in partitioned tables

### ISSUE THREAD

**Issue by chengxiong-ruan** [cockroachdb/cockroach#74626]
**Is your feature request related to a problem? Please describe.**
Currently hash sharding is not allowed if an index is partitioned. But this would be a feature wildly wanted by users. For example an user asked if they can emulate hash-sharded index with partitioned table in discussion https://github.com/cockroachdb/cockroach/discussions/74395

**Describe the solution you'd like**
Support hash-sharded indices with all the following partitioning cases.
(1) implicit partitioned index in `regional by row` tables (crdb_region is not part of the index columns)
(2) implicit partitioned index in `partition all by` tables (partitioning fields are not part of the index columns

Epic CRDB-7363

**Comment by postamar** [comment]
Closed by https://github.com/cockroachdb/cockroach/pull/76358
