### ISSUE TITLE
Tooltip alignment is off

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#74641]
**Describe the problem**

On the v21.2.3 DB Console, some tooltips for screen sections show up, unexpectedly, at the right side of the screen:

![Screen Shot 2022-01-10 at 1 48 07 PM](https://user-images.githubusercontent.com/15893490/148823996-d691862a-6239-4bd1-9f88-e36d1fc35162.png)

Others look fine:

![Screen Shot 2022-01-10 at 1 48 20 PM](https://user-images.githubusercontent.com/15893490/148824036-a94e09a9-11f7-4030-8b50-1a87974dc1db.png)

**To Reproduce**

1. Download v21.2.3.
2. Run `./cockroach demo --with-load`.
3. Open the DB Console.
4. Click SQL Activity. 
5. Etc.

Jira issue: CRDB-12184

**Comment by thtruo** [comment]
cc @kevin-v-ngo for triage

**Comment by thtruo** [comment]
cc @zaneteh-crl for triage (also related to the overall [tooltip component work](https://cockroachlabs.atlassian.net/browse/CC-5339))
