### ISSUE TITLE
Can't click link in tooltip

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#74642]
On the Explain Plan tab of the Statement Details screen, hovering over `distribution` (and other elements of an explain plan) shows a tooltip including a link to docs. However, when you move the mouse to click the link, the tooltip disappears before you get there.

![Screen Shot 2022-01-10 at 1 49 03 PM](https://user-images.githubusercontent.com/15893490/148824502-b94e7994-f419-40db-aba0-97b38728ba68.png)

Steps to reproduce:
1. Download v21.2.3.
2. Run `./cockroach demo --with-load`.
3. Click SQL Activity.
4. Click Statements.
5. Drill into a statement. 
6. Click Explain Plan.
7. Hover over an element with a tooltip that includes a docs link. 

Jira issue: CRDB-12185

**Comment by thtruo** [comment]
cc @kevin-v-ngo for triage

**Comment by thtruo** [comment]
cc @zaneteh-crl for triage (also related to the overall [tooltip component work](https://cockroachlabs.atlassian.net/browse/CC-5339))
