### ISSUE TITLE
Idx out of range ?

### ISSUE THREAD

**Issue by haha1029** [cockroachdb/cockroach#74669]
https://github.com/cockroachdb/cockroach/blob/51af1ca97d8474c6c04516749fe41031e4aaa593/pkg/sql/sem/tree/placeholders.go#L120

len(p.TypeHints[]) >= int(0) ?

**Comment by yuzefovich** [comment]
Why would this be index out of range? We're performing the bounds check first before accessing `p.TypeHints`. I could see a possible index out of range in the assignment just below

https://github.com/cockroachdb/cockroach/blob/51af1ca97d8474c6c04516749fe41031e4aaa593/pkg/sql/sem/tree/placeholders.go#L124

but we probably assume that `idx < len(p.Types)`, and if that assumption is wrong, a CRDB node would crash. If you ran into this, please provide more information on the issue.

**Comment by haha1029** [comment]
是的，目前是没有问题的。但这个是个public函数，未来有没有可能被其它地方调用到，并且忽略了外层check。

**Comment by haha1029** [comment]
Yes, there is no problem at present. But this is a public function. Is it possible to call it elsewhere in the future and ignore the outer check.

**Comment by yuzefovich** [comment]
True, it's exported, but it should only be used in CockroachDB, and the developers of CockroachDB are responsible to make sure the index out of bounds doesn't occur. I'm sure you can find plenty of other places like this where we don't have explicit bounds checks, and that's ok.

**Comment by haha1029** [comment]
ok, tks.
