### ISSUE TITLE
prod: create rules to automatically build packages for common distributions

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#7467]
CockroachDB probably ought to get packages for common Linux/BSD distributions. We could value support for:
- building debian/ubuntu .deb packages;
- building centos/redhat .rpm packages;
- a BSD port;
- homebrew/macports build rules;
- if windows compatibility ever becomes a thing, a windows installer.

**Comment by tamird** [comment]
I'm going to close this. To my knowledge, CRDB mostly builds from source on those distros, and some have already to do their own packaging. We have a homebrew formula, and the next beta will include a windows binary (we do not need an installer).
