### ISSUE TITLE
loqrecovery: automatically decommission lost nodes to prevent replicas from rejoining

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#74681]
**Is your feature request related to a problem? Please describe.**
When operators accidentally restart nodes that they declared dead via `apply-plan`. But mistakes happen, and if "dead" nodes come back, this can cause chaos in the cluster.

**Describe the solution you'd like**

Use the mechanisms we have already for decommissioned nodes:

- in apply-plan, write node decommissioned tombstone storage entries for all nodes thus being declared dead (this can be done atomically with apply-plan)
- consider also flipping their liveness record to DECOMMISSIONED once nodes in the cluster boot back up (this has to be done against the live KV layer, i.e. not offline)

cc @cockroachdb/repl 

Jira issue: CRDB-12203

**Comment by tbg** [comment]
@aliher1911 is there an issue that all of the LOQ subitems refer to? I searched but didn't find one.

**Comment by erikgrinaker** [comment]
One argument against this could be if we only lost some stores on multi-store nodes, e.g. due to a SAN-failure or fsync being disabled. So it may be worth adding a switch to disable it.

**Comment by erikgrinaker** [comment]
There was a PR for this in #75059, which was dropped in favor of manual decommissioning as part of the recovery procedure (see https://github.com/cockroachdb/cockroach/pull/75059#issuecomment-1021062574). We'll revisit when we implement online recovery.

**Comment by erikgrinaker** [comment]
Resolved by #95582.
