### ISSUE TITLE
kvserver: emit trace from failed replica circuit breaker probes

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#74699]
**Is your feature request related to a problem? Please describe.**
In #71806 we're introducing per-replica circuit breakers (#33007). This is well
and good, but when a breaker trips we want to know as much about that as
possible.

**Describe the solution you'd like**

Do whatever the outcome in #74404 is, where @joshimhoff is considering a similar problem for `kvprober`.

Jira issue: CRDB-12217

**Comment by joshimhoff** [comment]
Exciting!
