### ISSUE TITLE
ui: highlight circuit breakers in problem ranges and range status

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#74713]
Touches #33007.

**Is your feature request related to a problem? Please describe.**

As of #71806, circuit breaker errors are exposed via the range status JSON endpoint. However, the UI makes no use of this field.

**Describe the solution you'd like**

Ranges with a nonempty breaker error should be highlighted as "Problem Ranges" and the breaker error should also be printed on the "Range Status" page.

**Comment by lunevalex** [comment]
cc: @nkodali
