### ISSUE TITLE
vendor: ensure vendor commits are on a branch

### ISSUE THREAD

**Issue by jlinder** [cockroachdb/cockroach#74734]
**The problem**

Sometimes a commit in cockroachdb/vendored is only pushed to a personal branch that is later deleted so the commit used in a cockroachdb/cockroach `release-*` branch points at a dangling commit. When this happens, the commit could be GCed by GitHub.

Commits in the cockroachdb/vendored repository need to be referenced by ref/tag/branch so they don't get GCed by GitHub. 

 It happens that folks push a personal branch to the repo with their changes, make the cockroachdb/cockroach changes, get the cockroach PR merged and then delete their personal branch. 

**To Reproduce**

1. push a change to a personal branch in the cockroachdb/vendored repo
2. make cockroachdb/cockroach use that cockroachdb/vendored personal branch's head commit
3. make a PR for those changes and get them merged
4. delete the personal branch from cockroachdb/vendored

**Expected behavior**

When a commit from cockroachdb/vendored is used in a `master`/`release-*` branch in cockroachdb/cockroach, the commit in cockroachdb/vendored will always be referenced from a ref/tag/branch in that repository. Ideally, the commit is on a protected branch.

**Suggested Solution**

When a new commit is merged into `master` or a `release-*` branch in cockroachdb/cockroach, a CI job runs to automatically fast-forward push the new cockroachdb/vendored SHA to the corresponding `master`/`release-*` branch in cockroachdb/vendored. If it fails, it needs to fail loudly so it can be fixed ASAP.

Jira issue: CRDB-12235

**Comment by rickystewart** [comment]
`vendor` is not going to be around for much longer so I'm not sure any investment in this area makes sense.

**Comment by rickystewart** [comment]
`vendor` is no longer.
