### ISSUE TITLE
sql: hash sharded indexes should not need to specify bucket count

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#74739]
**Is your feature request related to a problem? Please describe.**

Hash sharded indexes require specifying a bucket count. This adds overhead to using them. A default of 8 or 16 is almost certainly sufficient for the vast majority of use cases.

**Describe the solution you'd like**
Add a session variable or cluster setting to control the default bucket count and use it if no bucket count is specified. Set the default default count to either 8 or 16. 

As for the session variable vs cluster setting discussion, I have no strong feelings. 

Epic: CRDB-7363

**Comment by danthegoodman1** [comment]
(Came across this googling) it would be really nice to have docs on why a particular number of buckets should be selected and how that changes performance based on cluster size, data access patterns, etc.

**Comment by ajwerner** [comment]
Indeed, @nickvigilante is going to whip some up before too long. The tl;dr is that the shards let you distribute write load over more nodes, eliminating a hot spot. The cost is that range scans over the index need to merge the results from each of the shards. In general, having more shards than nodes isn't really going to be very helpful, and comes at a cost. Also, you often don't need more shards than nodes, it depends on the write throughput you need to support. 16 lets you achieve 16x write throughput over a single range. That's a clear win for write throughput and probably enough for most use cases except at an extreme scale.

**Comment by postamar** [comment]
For reference, @ajwerner @vy-ton and I ultimately settled on 16 as a default value, based on a suggestion by @bdarnell a few months back. 

https://cockroachlabs.slack.com/archives/CUQDCNZ46/p1642006791011400

**Comment by danthegoodman1** [comment]
> Indeed, @nickvigilante is going to whip some up before too long. The tl;dr is that the shards let you distribute write load over more nodes, eliminating a hot spot. The cost is that range scans over the index need to merge the results from each of the shards. In general, having more shards than nodes isn't really going to be very helpful, and comes at a cost. Also, you often don't need more shards than nodes, it depends on the write throughput you need to support. 16 lets you achieve 16x write throughput over a single range. That's a clear win for write throughput and probably enough for most use cases except at an extreme scale.

I have an interesting use case where I am using this as temporary TTL (something I've talked to Vy about) and I have to scan a range of values on this hash index on some interval. I went with 8 buckets to leave some room for growth while also not going too far over node count. Ideally this index does not even get populated since it's a partial index that only catches catastrophic failures, so merging zero results should be relatively fast :)
