### ISSUE TITLE
sql: add SHOW CREATE INDEXES statement

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#74748]
The output of `SHOW INDEXES` is verbose and not well suited for getting a quick understanding of what indexes exist on a table. The output includes a row for each column (key or stored) in each index. For example:

```
CREATE TABLE t (
    k INT PRIMARY KEY,
    a INT,
    b STRING,
    UNIQUE INDEX (a),
    INDEX (a, b)
);

SHOW INDEXES FROM t;
  table_name | index_name | non_unique | seq_in_index | column_name | direction | storing | implicit
-------------+------------+------------+--------------+-------------+-----------+---------+-----------
  t          | primary    |   false    |            1 | k           | ASC       |  false  |  false
  t          | primary    |   false    |            2 | a           | N/A       |  true   |  false
  t          | primary    |   false    |            3 | b           | N/A       |  true   |  false
  t          | t_a_b_idx  |    true    |            1 | a           | ASC       |  false  |  false
  t          | t_a_b_idx  |    true    |            2 | b           | ASC       |  false  |  false
  t          | t_a_b_idx  |    true    |            3 | k           | ASC       |  false  |   true
  t          | t_a_key    |   false    |            1 | a           | ASC       |  false  |  false
  t          | t_a_key    |   false    |            2 | k           | ASC       |  false  |   true
```

The output of `SHOW CREATE TABLE` presents the indexes in a format that is much easier to understand:

```
SHOW CREATE TABLE t;
  table_name |               create_statement
-------------+------------------------------------------------
  t          | CREATE TABLE public.t (
             |     k INT8 NOT NULL,
             |     a INT8 NULL,
             |     b STRING NULL,
             |     CONSTRAINT "primary" PRIMARY KEY (k ASC),
             |     UNIQUE INDEX t_a_key (a ASC),
             |     INDEX t_a_b_idx (a ASC, b ASC),
             |     FAMILY "primary" (k, a, b)
             | )
```

But `SHOW CREATE TABLE` includes columns, constraints, and families, making it difficult to extract just the index information if that is all that is desired.

A `SHOW CREATE INDEXES FROM <table>` statement could output `CREATE INDEX` statements that represent all the indexes of a table.

For example:

```
SHOW CREATE INDEXES FROM t;
               create_statement
--------------------------------------------
 CREATE UNIQUE INDEX t_a_key ON t (a ASC)
 CREATE INDEX t_a_b_idx ON t (a ASC, b ASC)
```

An open question is whether or not the primary index should be included, and if so, how to represent it.

Jira issue: CRDB-12244

Epic CRDB-17785

**Comment by hand-crdb** [comment]
Regarding:

> An open question is whether or not the primary index should be included, and if so, how to represent it.

Perhaps `SHOW SECONDARY INDEXES` can be used to show just the secondary indexes.  I suspect many people only will care about secondary indexes.  This would be especially helpful for wide tables to keep the primary index from filling up the output.

**Comment by mgartner** [comment]
> I suspect many people only will care about secondary indexes.

I originally would have agreed with you, but we already have an example of someone interested in information on a primary key: #75229.

**Comment by hand-crdb** [comment]
> I originally would have agreed with you, but we already have an example of someone interested in information on a primary key: #75229.

I don't think we necessarily disagree.  While no doubt some people will be interested in the primary key, I suspect many people will care only about secondary indexes.  Having a way to specify just the secondary indexes would be nice, e.g. `SHOW SECONDARY INDEXES`.

**Comment by rafiss** [comment]
cc @devadvocado for awareness

**Comment by reddishshoib** [comment]
Hey There I want to contribute in this project,
I am newbie to open source ,Having good knowledge in go, c , cpp, shell
Any small help could be great favour for me
Thanks
