### ISSUE TITLE
admin UI is a security hole: propose --http-addr to secure the admin UI

### ISSUE THREAD

**Issue by glycerine** [cockroachdb/cockroach#7474]
In beta-20160616: 

I'm setting up a secure cluster. The nodes are running on a public cloud, so they are using publicly accessible IP addresses to communicate. 

I see that the Admin UI is then also listening on the public IP address, which means that:

a) reads are visible: anyone in the world can read status of my cluster, not good.
b) potential writes to the admin web UI increase the attack surface of the cluster, also not good.

So the general problem is that the Admin UI should be securable. The general public should not be able read nor write to the web UI admin interface.

The simplest solution that comes to my mind: add an --http-addr flag that would allow me to say --http-addr=127.0.0.1, distinct from the public external IP address, and so only my own SSH tunnel could access the Admin UI web server.

**Comment by mberhault** [comment]
That's one solution. The other we plan on doing for 1.0 is to have proper security on the admin UI. This would be password-based authentication + cookie-based sessions and the usual cross-site-scripting prevention stuff.
Of course, that would not be so safe with `--insecure`, but the whole cluster in insecure at that point anyway.

**Comment by glycerine** [comment]
Hi Marc,
Thanks for letting me know about the plan.
Jason

**Comment by glycerine** [comment]
I implemented #7475, which is complimentary to full-on login/password future planned work that Marc mentioned. It also would let me proceed today with serious testing and evaluation. @mberhault if you or the person most appropriate could review this for me, I would appreciate it.

Thank you.

Jason
