### ISSUE TITLE
cannot delete table struct

### ISSUE THREAD

**Issue by FarYoung** [cockroachdb/cockroach#7478]
While I wanna to delete the users table, data deleted but table struct still there!
And also cannot drop dabatase.

root@192.168.100.3:26257> DROP TABLE neo_test.users;
pq: table "users" has been deleted

root@192.168.100.3:26257> SHOW TABLES FROM neo_test;
+------------+
|   Table    |
+------------+
| users      |
+------------+

root@192.168.100.3:26257> SELECT * FROM neo_test.users;
pq: table is being deleted

root@192.168.100.3:26257> SHOW COLUMNS FROM neo_test.users;
+---------------+-------------+-------+-----------------------+
|     Field     |    Type     | Null  |        Default        |
+---------------+-------------+-------+-----------------------+
| userid        | INT         | false | unique_rowid()        |
| name          | STRING(32)  | false | NULL                  |
| username      | STRING(32)  | false | NULL                  |
| email         | STRING(64)  | false | NULL                  |
| password      | STRING(64)  | false | NULL                  |
| block         | INT         | false |                     0 |
| sendEmail     | INT         | false |                     0 |
| registerDate  | TIMESTAMP   | false | NULL                  |
| lastvisitDate | TIMESTAMP   | false | "current_timestamp"() |
| activation    | STRING(100) | false | ''                    |
+---------------+-------------+-------+-----------------------+

root@192.168.100.3:26257> SHOW INDEX FROM neo_test.users;
+-------+---------+--------+-----+--------+-----------+---------+
| Table |  Name   | Unique | Seq | Column | Direction | Storing |
+-------+---------+--------+-----+--------+-----------+---------+
| users | primary | true   |   1 | userid | ASC       | false   |
+-------+---------+--------+-----+--------+-----------+---------+

root@192.168.100.3:26257> show databases;
+-----------+
| Database  |
+-----------+
| bank      |
| neo_test |
| system    |
+-----------+
root@192.168.100.3:26257> DROP DATABASE neo_test;
pq: table "**users**" has been deleted

root@192.168.100.3:26257> show databases;
+-----------+
| Database  |
+-----------+
| bank      |
| neo_test |
| system    |
+-----------+

[root@localhost ~]#  grep -F '[config]' /cockroach-data/logs/cockroach.INFO
I160626 13:08:22.103392 util/log/clog.go:998  [config] file created at: 2016/06/26 13:08:22
I160626 13:08:22.103392 util/log/clog.go:998  [config] running on machine: localhost
I160626 13:08:22.103392 util/log/clog.go:998  [config] binary: CockroachDB beta-20160609 (linux amd64, built 2016/06/09 16:31:43, go1.6.2)
I160626 13:08:22.103392 util/log/clog.go:998  [config] arguments: [/usr/local/cockroach/cockroach start --store=cockroach-data --insecure --host=192.168.100.3 --port=26257 --http-port=8080 &]

**Comment by FarYoung** [comment]
I can drop the user1 table with the same create sql, but user not.

root@192.168.100.3:26257> SET DATABASE = neo_test;
SET
root@192.168.100.3:26257> SHOW TABLES FROM neo_test;
+------------+
|   Table    |
+------------+
| logon      |
| users      |
| users1     |
| warehouses |
+------------+
root@192.168.100.3:26257> DROP TABLE IF EXISTS neo_test.users;
pq: table "users" has been deleted
root@192.168.100.3:26257> SHOW TABLES FROM neo_test;
+------------+
|   Table    |
+------------+
| logon      |
| users      |
| users1     |
| warehouses |
+------------+
root@192.168.100.3:26257> DROP TABLE IF EXISTS neo_test.users1;
DROP TABLE
root@192.168.100.3:26257> SHOW TABLES FROM neo_test;
+------------+
|   Table    |
+------------+
| logon      |
| users      |
| warehouses |
+------------+

**Comment by FarYoung** [comment]
It's all seems ok while I rename the cockroach-data and restart the cockroachdb.
I will keep in testing and follow the issues.

thx your wonderful work.

**Comment by andreimatei** [comment]
Something is funky with `DROP`s. See #7348.

**Comment by FarYoung** [comment]
#7348 
I make the problem recur, while I try to drop the certain table, the drop process hung up for several minute, until I have to break it by Ctrl+C command in Console.
Then the problem becomes here again, table name and struct is there but cannot do any on it, the only way is delete the data folder and restart to rebuild the database...

**Comment by FarYoung** [comment]
Okay, I try the new release.

**Comment by FarYoung** [comment]
I know what is the issue, It should wait ENOUGH time (more than several seconds) for the DROP process finish. @andreimatei 
Thanks for your support.

**Comment by FarYoung** [comment]
Sorry, after further test,  issue still there. @andreimatei 

root@192.168.100.3:26257> SELECT rowid FROM neo_study.logon;
+--------------------+
|       rowid        |
+--------------------+
| 155587904333938689 |
| 155587914360586241 |
| 155588334399225857 |
+--------------------+
(3 rows)
root@192.168.100.3:26257> DROP TABLE IF EXISTS neo_study.logon;
driver: bad connection
root@192.168.100.3:26257> DROP TABLE IF EXISTS neo_study.logon;


driver: bad connection
root@192.168.100.3:26257> 
root@192.168.100.3:26257> 
root@192.168.100.3:26257> 
root@192.168.100.3:26257> SELECT rowid FROM neo_study.logon;
pq: table is being deleted
root@192.168.100.3:26257> 
root@192.168.100.3:26257> SELECT * FROM neo_study.logon;
pq: table is being deleted
root@192.168.100.3:26257> 
root@192.168.100.3:26257> DROP DATABASE neo_study;
driver: bad connection
root@192.168.100.3:26257> DROP DATABASE neo_study;
pq: table "logon" has been deleted
root@192.168.100.3:26257> SHOW TABLES FROM neo_study;
+------------+
|   Table    |
+------------+
| logon      |
| users      |
| users_info |
+------------+
(3 rows)
root@192.168.100.3:26257> DROP TABLE IF EXISTS neo_study.logon;
driver: bad connection
root@192.168.100.3:26257> DROP TABLE IF EXISTS neo_study.logon;
pq: table "logon" has been deleted
root@192.168.100.3:26257> SHOW TABLES FROM neo_study;
+------------+
|   Table    |
+------------+
| logon      |
| users      |
| users_info |
+------------+
(3 rows)
root@192.168.100.3:26257> SHOW TABLES FROM neo_study;

**Comment by andreimatei** [comment]
I've pushed https://github.com/cockroachdb/cockroach/pull/7504, which fixes some issues with `DROP`.
Other issues, with dropping large tables, are tracked in #7348.

If your table is small, like `logon` seems to have been, would you mind trying a binary with this fix? You'll have to build from source, or wait for our next release.
