### ISSUE TITLE
sql: support GRANT PRIVILEGES ... ON SEQUENCE

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#74780]
Sequences in PG have privileges.

[PG 13](https://www.postgresql.org/docs/13/sql-grant.html):

```

GRANT { { USAGE | SELECT | UPDATE }
    [, ...] | ALL [ PRIVILEGES ] }
    ON { SEQUENCE sequence_name [, ...]
         | ALL SEQUENCES IN SCHEMA schema_name [, ...] }
    TO role_specification [, ...] [ WITH GRANT OPTION ]

```

And also see this table:

Privilege | Abbreviation | Applicable Object Types
-- | -- | --
SELECT | r (“read”) | LARGE OBJECT, SEQUENCE, TABLE (and table-like objects), table column
INSERT | a (“append”) | TABLE, table column
UPDATE | w (“write”) | LARGE OBJECT, SEQUENCE, TABLE, table column
DELETE | d | TABLE
TRUNCATE | D | TABLE
REFERENCES | x | TABLE, table column
TRIGGER | t | TABLE
CREATE | C | DATABASE, SCHEMA, TABLESPACE
CONNECT | c | DATABASE
TEMPORARY | T | DATABASE
EXECUTE | X | FUNCTION, PROCEDURE
USAGE | U | DOMAIN, FOREIGN DATA WRAPPER, FOREIGN SERVER, LANGUAGE, SCHEMA, SEQUENCE, TYPE

This issue tracks whether we need to implement or put a placeholder for it or not, as it appears on PG dumps.

Jira issue: CRDB-12256

Epic CRDB-14491

**Comment by ajwerner** [comment]
I don't see it as having disappeared? Some of the details moved to https://www.postgresql.org/docs/14/ddl-priv.html.

**Comment by ajwerner** [comment]
We're missing both the syntax and the proper privilege set for sequences. Currently we treat sequences like tables.

**Comment by otan** [comment]
Ah it just disappeared off the syntax page

**Comment by rafiss** [comment]
Perhaps we can add the syntax for it now, and have that alias to the current logic of granting privileges on tables.
