### ISSUE TITLE
Make certificate manager more flexible for CLI

### ISSUE THREAD

**Issue by rimadeodhar** [cockroachdb/cockroach#74812]
The certificate manager for CLI commands expects all certificates to be in a specific directory and follow certain naming conventions. However, the certificates for serverless clusters work differently and we need to remove these restrictions to allow CLI commands like `debug zip` etc. to work with serverless clusters. 

Jira issue: CRDB-12278

**Comment by knz** [comment]
cc @jtsiros for triage
