### ISSUE TITLE
spanconfigjob: crash in Resume

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#74815]
I ran into

```
*
* ERROR: a panic has occurred!
* runtime error: invalid memory address or nil pointer dereference
* (1) attached stack trace
*   -- stack trace:
*   | runtime.gopanic
*   |   /usr/local/go/src/runtime/panic.go:1038
*   | runtime.panicmem
*   |   /usr/local/go/src/runtime/panic.go:221
*   | runtime.sigpanic
*   |   /usr/local/go/src/runtime/signal_unix.go:735
*   | github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigjob.(*resumer).Resume
*   |   /home/otan/go/src/github.com/cockroachdb/cockroach/pkg/spanconfig/spanconfigjob/job.go:44
*   | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func2
*   |   /home/otan/go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1123
*   | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine
*   |   /home/otan/go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1124
*   | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob
*   |   /home/otan/go/src/github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:401
*   | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).resumeJob.func1
*   |   /home/otan/go/src/github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:323
*   | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
*   |   /home/otan/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:488
*   | runtime.goexit
*   |   /usr/local/go/src/runtime/asm_amd64.s:1581
* Wraps: (2) runtime error: invalid memory address or nil pointer dereference
* Error types: (1) *withstack.withStack (2) runtime.errorString
*
```

running a local cluster (`start-single-node`) built on f801d14e74a3199b3f4fef5c368bc026cd86a18f.

----

Repro steps:

* Apply the following cluster settings (for faster schema change testing):
```sql
		SET CLUSTER SETTING kv.range_merge.queue_interval = '50ms';
		SET CLUSTER SETTING kv.raft_log.disable_synchronization_unsafe = true;
		SET CLUSTER SETTING jobs.retention_time = '15s';
		SET CLUSTER SETTING jobs.registry.interval.cancel = '180s';
		SET CLUSTER SETTING jobs.registry.interval.gc = '30s';
		SET CLUSTER SETTING sql.stats.automatic_collection.enabled = false;
		SET CLUSTER SETTING kv.range_split.by_load_merge_delay = '5s';
		ALTER RANGE default CONFIGURE ZONE USING gc.ttlseconds = '5';
		ALTER DATABASE system CONFIGURE ZONE USING gc.ttlseconds = '5';
```
* Repeatedly create a new database (e.g. `CREATE DATABASE db_{nanotime}`) and run an PGDUMP import
*  (see me for the import)

**Comment by irfansharif** [comment]
Following up the stack from where this job is being created, this infra is not enabled for the host tenant unless an envvar is set, and not enabled for secondary tenants unless a cluster setting is set.

- Where the job is created:
https://github.com/cockroachdb/cockroach/blob/eb31fd427330f00b6948f4871e18c625c52dd08c/pkg/spanconfig/spanconfigmanager/manager.go#L170-L173

- Where the thing creating the job is started:
https://github.com/cockroachdb/cockroach/blob/a4cb6224990a7366df17d2c582c9731383f11206/pkg/server/server_sql.go#L1119-L1120

- Where the thing creating the job is created, conditionally:
https://github.com/cockroachdb/cockroach/blob/a4cb6224990a7366df17d2c582c9731383f11206/pkg/server/server_sql.go#L872-L896

- Where the job creation itself is gated by a cluster setting:
https://github.com/cockroachdb/cockroach/blob/eb31fd427330f00b6948f4871e18c625c52dd08c/pkg/spanconfig/spanconfigmanager/manager.go#L135-L137

Were you running as a secondary tenants? Or enabling the span configs infra?

**Comment by otan** [comment]
> Were you running as a secondary tenant? Or enabling the span configs infra?

I only applied the cluster settings specified above (I didn't go out of my way to enable the config).

The node was started with `./cockroach start-single-node --insecure`, no tenants AFAICT.

**Comment by irfansharif** [comment]
The failure above was due to improper initialized state. With https://github.com/cockroachdb/cockroach/pull/73876 we're definitely initializing things. I'm going to YOLO close this.
