### ISSUE TITLE
sql: views should maintain the ordering of the queries that generate them

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#74859]
As far as I can tell, Postgres's documentation does not explicitly state that a view will maintain the ordering of the query that generated it, though their [materialized view docs](https://www.postgresql.org/docs/14/rules-materializedviews.html) show examples where `ORDER BY` is used. In practice, however, Postgres does maintain the ordering of queries used to generate views. For example:

```
marcus=# CREATE TABLE t (k INT PRIMARY KEY, a INT);
CREATE TABLE

marcus=# CREATE VIEW v (k, a) AS SELECT k, a FROM t ORDER BY a;
CREATE VIEW

marcus=# INSERT INTO t VALUES (1, 3), (2, 2), (3, 1);
INSERT 0 3

marcus=# SELECT * FROM t;
 k | a
---+---
 1 | 3
 2 | 2
 3 | 1
(3 rows)

marcus=# SELECT * FROM v;
 k | a
---+---
 3 | 1
 2 | 2
 1 | 3
(3 rows)

marcus=# EXPLAIN SELECT * FROM v;
                        QUERY PLAN
-----------------------------------------------------------
 Sort  (cost=158.51..164.16 rows=2260 width=8)
   Sort Key: t.a
   ->  Seq Scan on t  (cost=0.00..32.60 rows=2260 width=8)
(3 rows)
```

This behavior is surprising to me, because views are designed to be interfaces that refine underlying tables. A table is not guaranteed to produce output in any order unless an `ORDER BY` clause is present, so I'd expected a view to behave the same.

That being said, we may want to preserve the ordering of views to be consistent with Postgres's behavior.

Epic: CRDB-13625
Jira issue: CRDB-12299

**Comment by rafiss** [comment]
Relates to https://github.com/cockroachdb/cockroach/pull/68295 -- there is a `propagate_input_ordering` setting that might be useful here.

**Comment by mgartner** [comment]
We do not believe this is a bug. If users wish to maintain the ordering specified by a view query, they can set the session setting: `SET propagate_input_ordering=true;`.
