### ISSUE TITLE
Invalid cron expression in CREATE SCHEDULE statement causes node to crash

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/cockroach#74873]
**Describe the problem**

If you run a CREATE SCHEDULE statement with an invalid cron expression, the node will crash.

**To Reproduce**

1. Set up CockroachDB cluster locally using roachprod, version 21.1.12
2. Send SQL/CLI command

```
./cockroach sql --insecure -e "CREATE SCHEDULE backup_schedule FOR BACKUP INTO 's3://backup/test?AWS_ACCESS_KEY_ID=<redacted>&AWS_SECRET_ACCESS_KEY=<redacted>' RECURRING '* 14-8 * * *' FULL BACKUP '@weekly';"
```
 
3. The command will return error:

```
ERROR: driver: bad connection
Failed running "sql"
```

4. The UI will show the node as dead.

**Expected behavior**
invalid cron expression error should be thrown

**Environment:**
 - CockroachDB version: 21.1.12
 - Server OS: MacOS 11.6.2
 - Client app: `cockroach sql`

gz#11040

**Comment by adityamaru** [comment]
Fixed on 21.1, 21.2 and master. In all three versions this should not fail gracefully.
