### ISSUE TITLE
bazel: incorrect geospatial results in logictest

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#74889]
I hit this failure when using bazel. This is with no local changes (5ad21e3896).
```
        --- FAIL: TestLogic/local/geospatial_zm (0.23s)
            logic.go:2438: 
                 
                testdata/logic_test/geospatial_zm:381: SELECT st_length('LINESTRING M(0 0 -25, 1 1 -50, 2 2 0)')
                expected:
                    2.82842712474619
                    
                but found (query options: "") :
                    82.2650791318405
```
Test passes with make.

**Comment by RaduBerinde** [comment]
Some info on my system: running Ubuntu-based linux, bazel config:
```
radu (master) ~/roach # cat .bazelrc.user 
build --config=crosslinux --experimental_no_product_name_out_symlink
radu (master) ~/roach # cat ~/.bazelrc 
build --remote_cache=http://localhost:34213
```

**Comment by RaduBerinde** [comment]
Interestingly, if I use `-s --sandbox_debug` and run the test command myself, it passes.

**Comment by RaduBerinde** [comment]
It must be that under bazel it loads an incorrect libgeos, but I have no idea which one and why.

**Comment by rickystewart** [comment]
@RaduBerinde I cannot reproduce with `./dev testlogic base --config=local --files=geospatial_zm `. Can you try applying this patch and then check what directory it's loading `geos` from?

```
diff --git a/pkg/geo/geos/geos.go b/pkg/geo/geos/geos.go
index c931955e77..514fc1cab5 100644
--- a/pkg/geo/geos/geos.go
+++ b/pkg/geo/geos/geos.go
@@ -15,6 +15,7 @@
 package geos
 
 import (
+	"fmt"
 	"os"
 	"path"
 	"path/filepath"
@@ -182,6 +183,7 @@ func initGEOS(dirs []string) (*C.CR_GEOS, string, error) {
 	var err error
 	for _, dir := range dirs {
 		var ret *C.CR_GEOS
+		fmt.Printf("attempting to load geos from %s\n", dir)
 		newErr := statusToError(
 			C.CR_GEOS_Init(
 				goToCSlice([]byte(filepath.Join(dir, getLibraryExt(libgeoscFileName)))),

```

With that patch, I see the following in my logs when running `testlogic`, which looks correct:

```
attempting to load geos from /private/var/tmp/_bazel_ricky/be70b24e7357091e16c49d70921b7985/sandbox/darwin-sandbox/1709/execroot/cockroach/bazel-out/darwin_arm64-fastbuild/bin/pkg/sql/logictest/logictest_test_/logictest_test.runfiles/cockroach/c-deps/libgeos/lib
```

I wonder whether you have a globally installed `libgeos` or something and it's getting confused. I notice that the Bazel sandbox location is *last* in the list of locations from which it can init `libgeos`, so maybe we should move that to be *first* in the list instead.

**Comment by RaduBerinde** [comment]
Indeed:
```
attempting to load geos from /home/radu/lib
```

**Comment by RaduBerinde** [comment]
I believe that `lib` directory is from unpacking some older cockroach release in my home dir. It's a little strange the library doesn't have a version, it's just `libgeos.so`.
