### ISSUE TITLE
bazel: test scoped logs not directly available

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#74906]
Many tests dump out their logs in separate files. When running under bazel, these logs are left in the sandbox which is removed (unless `--debug_sandbox`) is used.

```
I220117 05:35:34.291146 1 (gostd) rand.go:147  [-] 1  random seed: 6532117856687621002
test logs left over in: /home/radu/.cache/bazel/_bazel_radu/c5a4e7d36696d9cd970af2045211a7df/sandbox/linux-sandbox/1891/execroot/cockroach/_tmp/b287de7194e17a0386ee1775f0d198ba/logTestSchemaChangeReverseMutations4230933597
--- FAIL: TestSchemaChangeReverseMutations (0.91s)
    test_log_scope.go:79: test logs captured to: /home/radu/.cache/bazel/_bazel_radu/c5a4e7d36696d9cd970af2045211a7df/sandbox/linux-sandbox/1891/execroot/cockroach/_tmp/b287de7194e17a0386ee1775f0d198ba/logTestSchemaChangeReverseMutations4230933597
    test_log_scope.go:80: use -show-logs to present logs inline
    schema_changer_test.go:1788: pq: failed to construct index entries during backfill: unable to encode table key: <nil>
    panic.go:642: -- test log scope end --
FAIL
```

```
ls: cannot access '/home/radu/.cache/bazel/_bazel_radu/c5a4e7d36696d9cd970af2045211a7df/sandbox/linux-sandbox/1891/execroot/cockroach/_tmp/b287de7194e17a0386ee1775f0d198ba/logTestSchemaChangeReverseMutations4230933597': No such file or directory
```

Jira issue: CRDB-12316

**Comment by rickystewart** [comment]
You should set `--test_tmpdir=SOME_PERSISTENT_DIRECTORY`, then your logs will be in `SOME_PERSISTENT_DIRECTORY` after the test runs.

**Comment by RaduBerinde** [comment]
Good to knowm thanks. We need to find a way to convey this information.. even if we have to modify the message generated in `test_log_scope.go`.

Or, could we set this up by default in the repo's bazelrc? We could allow a gitignored testlogs directory.

**Comment by rickystewart** [comment]
> Or, could we set this up by default in the repo's bazelrc?

I've only ever used this flag with an absolute path, not sure if it works with a relative path? You can give it a shot.

We already put the tmpdir in a special spot for `--config ci`, we would just have to make sure we don't break the existing stuff.
