### ISSUE TITLE
rpc: implement grpc.Balancer

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#7494]
[grpc.Balancer](https://godoc.org/google.golang.org/grpc#Balancer) is a neat abstraction that might be quite useful to us.

For instance, we could abstract away the idea of sending RPCs to a particular range leader. In addition, we could use the `Up()` method and its return `Down()` to implement evented health checking.

This abstraction also provides a method of culling old connections (`Notify()`), which could be used to resolve #4784.

~~Blocked on (and related to) #7430.~~

cc @d4l3k

**Comment by tamird** [comment]
etcd has migrated to it, so that's some indication. Also, the last experimental API was removed in favour of this one. Finally, what other options do we have?

**Comment by d4l3k** [comment]
SGTM

**Comment by andreimatei** [comment]
One thing to keep in mind is that sometimes we don't want to send RPCs to a range leader, e.g. for `INCONSISTENT` reads. Sometimes the `DistSender` knows exactly the replica that should be sent to. So this should remain supported.

**Comment by vivekmenezes** [comment]
Do we support inconsistent read through SQL?

**Comment by andreimatei** [comment]
No, I don't think SQL ever uses them at the moment.
But KV sure does for a bunch of random internal things. And I'm adding one
more use case, more directly related to SQL - the process of figuring out
range leadership for (distributed) SQL physical planning is gonna do
inconsistent LeaseRangeInfo requests, and cares about choosing the replica
this request goes to.
