### ISSUE TITLE
sql: column family assignment cannot be changed after column creation

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#7502]
There's no fundamental reason we can't add something like `ALTER TABLE foo ALTER COLUMN bar FAMILY baz`, it'll just have to be added to the schema change code. Something like:
- Mark column as write-only in new group.
- Write column to both old and new groups for queries, reading it only from old group.
- Backfill column data to new group.
- Remove column from old group, mark readable in new group.

**Comment by vivekmenezes** [comment]
I think this is very much like adding a new column, so you also need to start the new column in the DELETE_ONLY state before putting it in the WRITE_ONLY state (to guarantee that when you've started writing to the new column, all nodes are capable of deleting column values from the new group).

This should definitely be pushed to a later milestone. Thanks

**Comment by knz** [comment]
This is now possible via:

1. add computed column as copy of the original one in new column family
2. remove original column
3. rename computed column.

Step 2 and 3 can be done atomically (ALTER X, Y).
