### ISSUE TITLE
sql: [micro-rfc] schema changes that need to make schema changes are difficult

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#7508]
Some schema changes require *related* changes to multiple tables, for example, since a foreign key relationship requires that both the referencing and the referenced table are aware of the relationship, adding a foreign key between two tables involves adding pointers to each other to *both* table descriptors. 

Currently a schema change operates on a single table.

Correctly handling something like the example above is possible via a sequence of single-table modifications by adding additional intermediate states one table, but not the other, has been modified, and waiting at points during the process until all nodes have become aware of a particular version of a particular table. This approach however has drawbacks: added complexity in general, as request handling code needs to correctly handle more additional states and more specifically, during that sequence of changes, the agent making the change has state about which changes have been made, which still need to be made, etc.

**Comment by dt** [comment]
This could be simplified by extending a schema change to include atomic alterations to multiple table descriptors in the same change. The easiest way to implement that would likely be simply embedding all the existing table descriptor structures into a single document (likely the db descriptor), so that the whole document can be changed at once, and one can be assured that one has *all* tables for a given DB at either version `x` or `y` but not a mixture.

**Comment by tamird** [comment]
Won't that require a move to F1-style whole-schema leasing? Not that I'm opposed, just clarifying.

**Comment by dt** [comment]
Yep, whole _db_ schema leasing is what i'm proposing.

**Comment by andreimatei** [comment]
What we get from having leases on table descriptors is that mutations on different tables can happen in parallel. And that we could theoretically gossip more granular updates. I don't have an opinion about how valuable these things are. On the other hand, coalescing all the schema in one structure would have the good side-effect that we'd also get a leasing system for what is now the "database descriptor", which has no lease - which causes problems when dropping and trying to recreate databases.

I'd like to hear more on what we could and couldn't do with the current system; there's nothing preventing a mutation from modifying multiple descriptors, atomically, in a txn. But I guess there's no way for a statement to set `up_version` on two tables.

**Comment by dt** [comment]
I think parallel updates to separate table descriptors isn't a big benefit in practice -- schema changes are are not high QPS actions, and are already going to be serialized for operations sanity (obviously a multi-tenant cluster would see concurrent changes, but not in the same DB, and we still get parallel changes to separate DBs even if we make this change).

**Comment by petermattis** [comment]
I'm not sure how grouping things at the level of a database will help. There is nothing restricting a table in one database from referring to a table in another. Perhaps you're using a different definition of `database`.

**Comment by dt** [comment]
I don't think we were expecting to allow cross-database FKs.

**Comment by tamird** [comment]
Heads up that #2948 might be related to this.

**Comment by vivekmenezes** [comment]
I'm tempted to say that this is not an issue that we can look into for the 1.0 release. The benefits are marginal and I'm not sure what the drawbacks are yet, and don't forget this change is a lot of work. I think what is being suggested might be nicer but it's going to be very disruptive (in other words we might never get to do this ever :-), and we have way higher priorities.

**Comment by dt** [comment]
.@petermattis suggested a variant that might get the bulk of the benefits with a fraction of the work:
switch to leasing databases, but rather than change how table descriptors are stored in KV, just change when they're read -- always read all of them at once, so that for a given leased DB version, you can be sure you have the same set of table versions.

**Comment by dt** [comment]
consensus seems to be that this just isn't worth the effort right now and we'll revisit it if/when we encounter something that changes that math.
