### ISSUE TITLE
bazel: should use `link` mode for `//:go_path`, not `copy`

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#75094]
`copy` mode is very inefficient, but we encounter a few issues when trying to use `link` mode:

* https://github.com/bazelbuild/rules_go/issues/3041
* https://github.com/cockroachdb/cockroach/pull/74651#issuecomment-1014113972

Epic CRDB-8036

**Comment by irfansharif** [comment]
@ajwerner's getting rid of entirely over at #76526. Closing.
