### ISSUE TITLE
kvprober: enable read and writes probes by default in 22.1

### ISSUE THREAD

**Issue by joshimhoff** [cockroachdb/cockroach#75113]
**Is your feature request related to a problem? Please describe.**
`kvprober` is a monitoring tool built by SRE to help us run CC. The main goal is to alert SRE on issues with the KV layer that are true CRDB (or CC) issues rather than workload issues. Workload issues are for our customers to fix; they not actionable for SRE.

Though the main `kvprober` goal is about CC, `kvprober` provides additional observability into the KV layer in other environments (e.g. self-hosted). The main benefit to `kvprober` in these other contexts is that `kvprober` probing successfully and at low latency (or the reverse) tells you _something_ about the production issue. If `kvprober` is probing successfully and at low latency, this likely means no large scale infra and/or CRDB issue. It "points the finger" at the workload (though noted that still could be infra and/or CRDB issue in the end).

As a result of above, I propose we turn it on by default in 22.1. 

**Describe the solution you'd like**
Concretely, I propose by default on 22.1, we configure `kvprober` to:

1. Do one read probe a second.
2. Do one write probe every five seconds.
3. Go thru admission queues (as then out of resource issues will be caught which is useful self-hosted land).

Note that `kvprober` has been running without issue across CC for two releases (well, one for shadow write probes).

@tbg and/or @andreimatei, I wonder what you think about this. Good idea? Medium idea? Bad idea? I don't debug on-prem issues so IDK the operational space.

**Describe alternatives you've considered**
We could close this ticket without action. We have per-replica circuit breakers coming. Still, per-replica circuit breakers & `kvprober` compliment each other. `kvprober` exercises a larger slice of the stack (e.g. dist sender) but is slower / less effective at finding specific unavailable ranges.
 
**Additional context**
N/A

Jira issue: CRDB-12469

**Comment by tbg** [comment]
I think we should default them to on. The benefit won't be very high since we haven't gone through the motions to make this operationally useful for on-prem deployments (which is also true for many other metrics sources). But I think it's valuable to have these logs in the HEALTH channel. Down the line, we may want to lean on kvprober as a source for what @dhartunian calls the "perennial alerting feature" :-)
I can't see any risk in turning this on.

**Comment by joshimhoff** [comment]
Ack, I'll do this. Thanks!

> The benefit won't be very high since we haven't gone through the motions to make this operationally useful for on-prem deployments.

I could see adding the metrics to an admin UI page at least. That seems easy enough to do ~now.

**Comment by tbg** [comment]
Right, but this doesn't really help much. The UI isn't in the debug.zip, which is mainly how we see on-prem deployments. Instead, we look at logs first, and even today we have log messages (that at least KV folks are trained to spot) that show you when a range is having issues.
