### ISSUE TITLE
build: Source archive doesn't include JS bundles for Db Console

### ISSUE THREAD

**Issue by koorosh** [cockroachdb/cockroach#75137]
**Describe the problem**

The way JS assets embedded into GO binaries was changed from using `go-bindata` to `//go:embed` directive and this change requires to copy JS bundled files (from `pkg/ui/dist{ccl|oss}`) into archive to make sure that:
- user doesn't need to build JS assets from sources
- JS assets are available during build to be embedded into GO binaries

**To Reproduce**

1. run `make build && make archive`
2. unzip archive generated with step 1 and `cd` into archive
3. run `make build` from within archive
4. run cluster `./cockroach start-single-node --insecure`
5. open Db Console in web browser 
6. and Db Console assets aren't loaded (`bundle.js`, `vendor.dll.js`, and `protos.dll.js`)

**Expected behavior**
Assets loaded and Db Console page is rendered

**Environment:**
 - CockroachDB version 22.1

**Additional context**
What was the impact?
- It is regression issue. Before, JS assets were embedded with `go-bindata` and then it was switched to use //go:embed directive. It affected `make archive` target. (07e97b6e83d6c66cb36247bab051a97d8bd7b5a0)

![Screenshot from 2022-01-18 19-09-35](https://user-images.githubusercontent.com/3106437/150103788-5179a7c1-473c-497a-a0f8-f13c5ba66182.png)

Jira issue: CRDB-12482

**Comment by rickystewart** [comment]
We are no longer distributing source archives.
