### ISSUE TITLE
pkg/cloud: ResumingReader incorrectly forgets to call `.Close()` on its ReadCloser

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#75143]
**Describe the problem**

Since go 1.17.6, it has become critical to call `.Close()` on the Body field of a http Response object, for otherwise we get goroutine leaks.
(see #74657, https://github.com/golang/go/issues/50652 and #75136)

Thanks to #75136, we're now doing a pretty good job of doing so in most cases, except for the following:

- `cloud/httpsink/(*httpStorage).ReadFileAt` calls `openStreamAt` which returns a http.Response
- that Response's Body is then passed as an `io.ReadCloser` to `cloud.NewResumingReader`,
- which, in turns does not call `.Close()` when the Reader is reset in `Read()`, when `RetryOnErrFn` returns true

(NB I've found it hard to read through the implementation of the methods of `cloud.ReadResumer`, it was expecting some kind of disciplined centralization of the invariants on the ReadCloser - maybe there's some improvement to make there)

cc @adityamaru for triage

**Comment by adityamaru** [comment]
Thanks for digging into this! I think we can add the `Close()` call before we nil it out over here https://github.com/cockroachdb/cockroach/blob/a9077697a77aa41f1cd09d3173616be37e85e1bf/pkg/cloud/cloud_io.go#L234-L234, I can send a PR.
