### ISSUE TITLE
sql: Support Postgres-like regexp match operators

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#7515]
See https://www.postgresql.org/docs/9.0/static/functions-matching.html#FUNCTIONS-POSIX-REGEXP.

In addition to querying for unsupported catalogs (`pg_catalog`, `pg_class`), Hibernate and its use of the Postgres JDBC issues a few queries which contain Postgres-specific regular expression match operators. While it looks like the ORM is actually handling the missing table errors fairly well, the parsing errors caused by the use of these operators is blocking its use. Now that there is a need for them, there doesn't seem to be any strong reason against adding support for these operators.

Thoughts @petermattis?

**Comment by petermattis** [comment]
I don't have any strong objection to supporting those operators. I'm curious what Hibernate does on MySQL.

**Comment by nvanbenschoten** [comment]
I should have been a bit more specific. It's not Hibernate itself that uses these operators, it is it's use of the Postgres JDBC driver's `getTables` implementation which uses them. Because of this, we're probably going to face this issue for most Java ORMs.
