### ISSUE TITLE
Add random data to sqlsmith.randTablesN()

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#75159]
There's an outstanding to do in the function to add random data to the tables it creates.

**Comment by msbutler** [comment]
@mgartner looking at your test in `TestRandTableInserts` in `sql_smith_test.go`, I realized it's really hard to produce valid  (even simple)  insert statements into tables created by `randTablesN`. Seems a lot easier to follow the approach in your test:  the caller of `randTablesN` should first execute the returned `CREATE TABLE` statements and then try executing insert statements. Do you agree? If so I'll close this issue.

**Comment by cucaroach** [comment]
@mgartner FYI

**Comment by mgartner** [comment]
@msbutler The TODO in `randTablesN` you mentioned is pretty old, and the context may be lost. I have a vague memory of coming across that comment a while ago and agreeing that there would be some benefit to creating insert statements there, but I can't remember what that alleged benefit was.

FWIW, SQLSmith has been detecting many bugs that are only reproduced when the tables have data, so it seems like this may be unnecessary.

Maybe it's time to delete that TODO? I'd support it.

**Comment by msbutler** [comment]
Sounds good! I'll delete the TODO. In the same spirit of `GenerateRandInterestingTable`, I'm going to create a public function in `randgen` called `GenerateRandTable(db *gosql.DB, dbName, tableName string, numRows int)` which calls `randTables` and tries to populate the table with n rows, like your test `TestRandTableInserts`. I think this function would make SQLSmith/RandGen a bit more user friendly for non sql teams, like Bulk. Let me know if you have any reservations about this idea.  I'll go ahead and close this issue.
