### ISSUE TITLE
storage: investigate/fix outgoing Raft message queues

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#7520]
The Raft message queues in `(*storage.RaftTransport).Send` are problematic since they often overflow and, when they do, drop all of their queued messages. When outgoing traffic exceeds a certain threshold, this results in essentially *all* Raft traffic being dropped between the two involved nodes.

Increasing the outgoing send buffer size (from currently 500) only helps after many orders of magnitude, so that does not appear to be the right solution.

While coalesced heartbeats (#6107) might reduce the traffic somewhat, that current system still seems brittle.

As a starting point, implement logic that gives a breakdown of what types of messages were dropped when the send buffer is dropped (votes, heartbeats, regular messages), or, even better, a counter for all traffic which is attempted to send.

**Comment by petermattis** [comment]
I'm not clear on why we need the message queues at all. With gRPC can't we just send the messages as they arrive? 

@tamird Assigning to you given your gRPC knowledge/experience.

**Comment by tamird** [comment]
Sure, but those gRPC methods aren't asynchronous. Given that the queues are getting backed up, ISTM that blocking on gRPC will throttle raft (maybe a good thing? idk).

**Comment by tamird** [comment]
An additional obvious upside is that we can trivially solve #5789 by getting rid of the queues.

**Comment by tschottdorf** [comment]
I think backpressure on Raft will result in hard to debug performance
anomalies (or worse). Especially if a node goes down and the gRPC call
blocks for 5 seconds. I don't think that this is a "real" option, at least
not in a naive form.

I don't see how it "trivially" solves #5789 - whether we buffer messages or
not, there will have to be a mechanism which receives responses and handles
them appropriately, which might be a little easier without the queues but
still leaves, I think, like 90% of the work.

On Wed, Jun 29, 2016 at 11:38 AM Tamir Duberstein <notifications@github.com>
wrote:

> An additional obvious upside is that we can trivially solve #5789
> <https://github.com/cockroachdb/cockroach/issues/5789> by getting rid of
> the queues.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/7520#issuecomment-229396001>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE135PyqNzgGNBglF8Y0LHAoEVacyuPXks5qQpFkgaJpZM4JBO63>
> .
>
-- 

-- Tobias

**Comment by tamird** [comment]
Closing per #7534.
