### ISSUE TITLE
SHOW RANGES FOR ROW does not seem to work on the movr.users table in a demo cluster

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/cockroach#75229]
Running on macOS:

```
$ uname -a
Darwin crlMBP-XXX.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Nov 10 22:23:07 PST 2021; root:xnu-7195.141.14~1/RELEASE_X86_64 x86_64
```

I start a multiregion demo cluster with movr data:

`$ cockroach demo --global --nodes 9 --insecure`

```
Flag --insecure has been deprecated, to start a test server without any security, run start-single-node --insecure
For details, see: https://go.crdb.dev/issue-v/53404/v21.2
#
# Welcome to the CockroachDB demo database!
#
# You are connected to a temporary, in-memory CockroachDB cluster of 9 nodes.
# Communication between nodes will simulate real world latencies.
#
# WARNING: the use of --global is experimental. Some features may not work as expected.
#
# This demo session will attempt to enable enterprise features
# by acquiring a temporary license from Cockroach Labs in the background.
# To disable this behavior, set the environment variable
# COCKROACH_SKIP_ENABLING_DIAGNOSTIC_REPORTING=true.
#
# Beginning initialization of the movr dataset, please wait...
#
# The cluster has been preloaded with the "movr" dataset
# (MovR is a fictional vehicle sharing company).
#
# Reminder: your changes to data stored in the demo session will not be saved!
#
# If you wish to access this demo cluster using another tool, you will need
# the following details:
#
#   - Connection parameters:
#     (webui)    http://127.0.0.1:8080
#     (sql)      postgresql://root@127.0.0.1:26257/movr?sslmode=disable
#     (sql/jdbc) jdbc:postgresql://127.0.0.1:26257/movr?sslmode=disable&user=root
#     (sql/unix) postgresql://root:unused@/movr?host=%2Fvar%2Ffolders%2Fbh%2F_32m6zhj67z534slcg79nm_w0000gp%2FT%2Fdemo840778948&port=26257
#   
#   To display connection parameters for other nodes, use \demo ls.
# Server version: CockroachDB CCL v21.2.4 (x86_64-apple-darwin19, built 2022/01/10 18:53:16, go1.16.6) (same version as client)
# Cluster ID: ef63b29e-bdf4-4889-8d69-5ccdef8d7f70
# Organization: Cockroach Demo
#
# Enter \? for a brief introduction.
```

The version is v21.2.4:

```sql
SELECT version();
```

```
                                        version
----------------------------------------------------------------------------------------
  CockroachDB CCL v21.2.4 (x86_64-apple-darwin19, built 2022/01/10 18:53:16, go1.16.6)
(1 row)
```

I would like to see where a range for a row in the `users` table is located, using [`SHOW RANGE FOR ROW`](https://www.cockroachlabs.com/docs/v21.2/show-range-for-row.html), so I look at the indexes in `users` to see what columns are in the primary key:

```sql
show indexes from users;
```

```
 table_name | index_name | non_unique | seq_in_index | column_name | direction | storing | implicit
-------------+------------+------------+--------------+-------------+-----------+---------+-----------
  users      | primary    |   false    |            1 | city        | ASC       |  false  |  false
  users      | primary    |   false    |            2 | id          | ASC       |  false  |  false
  users      | primary    |   false    |            3 | name        | N/A       |  true   |  false
  users      | primary    |   false    |            4 | address     | N/A       |  true   |  false
  users      | primary    |   false    |            5 | credit_card | N/A       |  true   |  false
```

Guess they all are.  Ok.  So I fetch a single row

```sql
select city,id,name,address,credit_card from users where city='amsterdam' limit 1;
```

```
    city    |                  id                  |     name     |            address            | credit_card
------------+--------------------------------------+--------------+-------------------------------+--------------
  amsterdam | ae147ae1-47ae-4800-8000-000000000022 | Tyler Dalton | 88194 Angela Gardens Suite 94 | 4443538758
(1 row)
```

I plug the values above into the `SHOW RANGE FOR ROW` statement:

```sql
show range from table users for row ('amsterdam','ae147ae1-47ae-4800-8000-000000000022', 'Tyler Dalton', '88194 Angela Gardens Suite 94', '4443538758');
```

```
ERROR: crdb_internal.encode_key(): number of values must equal number of columns in index "primary"
```

Unfortunately it does not work.  Am I holding it wrong?  Based on [the docs](https://www.cockroachlabs.com/docs/v21.2/show-range-for-row.html#show-range-information-for-a-row-in-a-table) I'd expect this to work.

FWIW it looks like feature this was added in https://github.com/cockroachdb/cockroach/commit/55aa7cdd1e but I don't think the person who added it is still here

Jira issue: CRDB-12519

**Comment by rafiss** [comment]
Ah this is confusing. Only `city` and `id`  are in the primary index keys.  The others are _stored in_ the primary index -- you can tell based on the `storing` column. I believe the output of SHOW INDEXES might have changed in v21.2, but don't remember off the top of my head.

**Comment by rmloveland** [comment]
OK.  This works as you explained @rafiss - I tracked down the change to https://github.com/cockroachdb/cockroach/pull/66599

FYI @postamar this is pretty confusing behavior for a non-expert like me who just wants to know "what columns are in the primary key?".  Using `SHOW CREATE TABLE` does not seem to tell me that either unfortunately

Thankfully @mgartner filed https://github.com/cockroachdb/cockroach/issues/74748  which will be useful if/when it makes it off the backlog

FWIW I also filed a docs issue https://cockroachlabs.atlassian.net/browse/DOC-2374 because it turns out the docs were not fully updated to reflect this change in https://github.com/cockroachdb/docs/issues/11352

but if I'm honest figuring this out in the heat of trying to get something done (even with fully updated docs) would have been difficult with this new behavior b/c it requires the user to apply conditional logic in their head across a potentially large table of output.  Which is kind of a lot to ask.

CC @vy-ton on this convo because .. tbh this hasn't been the nicest SQL Experience (tm) for me (See also: "who moved my cheese").  If I didn't work here I would have definitely just given up on this task long ago without filing anything

(Sorry if all this sounds a bit complain-y but I hope it's useful to hear from a normie averagely skilled user who just wants things to keep working the way they already worked)

**Comment by ajwerner** [comment]
Seems like we could extend the logic to take only the indexed prefix of the tuple.

**Comment by vy-ton** [comment]
@rmloveland Thanks for the feedback.

It would help me to have more context on the different questions you were trying to answer. Are there more besides the one below?

- "what columns are in the primary key?".

FYI @kevin-v-ngo @devadvocado for awareness

**Comment by postamar** [comment]
Please don't feel bad making these kinds of reports @rmloveland , quite the opposite, they're meaningfully valuable.

I agree that the behaviour of both `SHOW RANGE FOR ROW` and `encode_key` could be improved. Here's my own naive take:
- Shouldn't the former just ignore non-key values as long as the whole key is present? alternatively, print a notice? I mean, the statement asks for a _row_, and you give it one.
- More straightforwardly the error message for `encode_key` should state `number of values must equal number of key columns in index "primary"` instead of `umber of values must equal number of columns in index "primary"`

**Comment by rmloveland** [comment]
>  Are there more besides ... what columns are in the primary key?

No that is pretty much it in this case, @vy-ton .  I needed to find the magic strings/numbers/etc to plug into `SHOW RANGE FOR ROW`

@postamar thanks for your comment, I appreciate the encouragement :-)   Re: the exact behavior that is best from `SHOW RANGE FOR ROW`, I'm not sure. The error message could probably say what it is expecting more explicitly - eg if it knows it wants 2 columns in this case, one a `string` (city) and one a `uuid` (id), telling me it wants those in the error message is more helpful than saying "that's the wrong number to pass to this other internal function" which kind of results in a "guess again, oh but not like that, try again" UX.

In a perfect world I don't really want to care about if `SHOW RANGE FOR ROW` is using `encode_key` internally, as the caller I just want to know "what do you want from me"?  Of course I've only started trying to use `SHOW RANGE FOR ROW` a couple of days ago so .. take that for what it is

**Comment by rmloveland** [comment]
Closing for housekeeping reasons since I don't think there is a specific action item for this issue (docs were updated with current behavior), and it's not really a bug
