### ISSUE TITLE
storage: operations serialized by per-Store Raft goroutine

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#7522]
There is currently a single per-Store goroutine (`Store.processRaft`) which executes the Raft state machine for all replicas that exist on that store. This goroutine is a scalability bottleneck as we see no concurrency when executing operations on distinct replicas. The locking and interactions here are tricky, but perhaps it is possible to take a conservative approach and parallelize the execution of `Replica.handleRaftReady`.

**Comment by petermattis** [comment]
This patch below is the basic idea that I have in mind. Seems to have a big effect as it drops the time for `block_writer` to insert 1m rows from 258s to 195s (-25%). Performance actually improves as the `blocks` table is split.

```diff
diff --git a/storage/store.go b/storage/store.go
index 7eaf437..d243250 100644
--- a/storage/store.go
+++ b/storage/store.go
@@ -2159,11 +2159,18 @@ func (s *Store) processRaft() {
                        }
                        s.pendingRaftGroups.Unlock()
                        s.mu.Unlock()
+
+                       var wg sync.WaitGroup
+                       wg.Add(len(replicas))
                        for _, r := range replicas {
-                               if err := r.handleRaftReady(); err != nil {
-                                       panic(err) // TODO(bdarnell)
-                               }
+                               go func(r *Replica) {
+                                       if err := r.handleRaftReady(); err != nil {
+                                               panic(err) // TODO(bdarnell)
+                                       }
+                                       wg.Done()
+                               }(r)
                        }
+                       wg.Wait()
                        s.processRaftMu.Unlock()

                        select {
```

**Comment by tamird** [comment]
That change LGTM. I also think it's going to be a prerequisite for #7520 so that we're at least sending outgoing raft RPCs in parallel for each store.

**Comment by tschottdorf** [comment]
LGTM too. I think the original concern about not optimizing this earlier
was keeping Raft activity (and thus writes) sequential, but clearly RocksDB
can handle more than sequential I/O. I think Ben would have some qualified
thoughts on optimizations like these.

On Wed, Jun 29, 2016 at 11:57 AM Tamir Duberstein <notifications@github.com>
wrote:

> That change LGTM. I also think it's going to be a prerequisite for #7520
> <https://github.com/cockroachdb/cockroach/issues/7520> so that we're at
> least sending outgoing raft RPCs in parallel for each store.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/7522#issuecomment-229402052>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE135DS-ESfMqhpbLuHNjcz3AQXuMlnuks5qQpXSgaJpZM4JBQpg>
> .
>
-- 

-- Tobias

**Comment by petermattis** [comment]
RocksDB can definitely handle concurrent operations. For writes, there is a benefit to multiple threads writing concurrently as the log writes will be bundled together. Concurrent reads are also useful when they are hitting the cache and thus not bottlenecked on disk.
