### ISSUE TITLE
ui: unable to change stats request after failure to load statements/txn pages

### ISSUE THREAD

**Issue by xinhaoz** [cockroachdb/cockroach#75247]
Currently, the loading screen for stmts and txns pages fills the whole page. Similarly, if we fail to load the statements or txns pages, we get an error page encompassing the entire statements/txns pages. Because we store the query parameters used to fetch stats (aggregation time start and end) in local settings, when we get a problematic request (e.g. requested range is too large). we cannot change the parameters without manually clearing local settings due to the page using the same request parameters again and again, only showing the loading or error pages.

We should move the loading and error screens to below the page config section of the statement and transactions pages, so upon errors, we may re-issue the request with. new parameters.

**Comment by jocrl** [comment]
So the underlying goal is to be able to let users get out of a time selection where the response times out. I'd say an alternative approach could be to modify the callback that expects the request to return, such that it tolerates the request potentially not returning. Then it could reset the time to default or something (with some ui/message as a bonus, but even without that would be helpful). Point here is to not throw a hard error, or at least throw it after you've reset the time selection.

Even if we were to change the error screen to not remove the controls, am not confident that the code would still work fine after the error (or maybe it will 🤷‍♀️).
