### ISSUE TITLE
release: fetch tags before linking the tag into the binary, or else make tagging more explicit

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#75287]
The version that CRDB reports itself in telemetry as is determined by the git tags that exist in the local repo at compilation time. See [build/info.go](https://github.com/cockroachdb/cockroach/blob/839b8cf544c7744fe91b1f2000644aef307a87d7/pkg/build/info.go#L29-L31) and the [Makefile](https://github.com/cockroachdb/cockroach/blob/839b8cf544c7744fe91b1f2000644aef307a87d7/Makefile#L1228). I don't know where it happens in the bazel build.

But if somebody is building locally, they might not have all the latest tags. For example I’m seeing data in snowflake from a cluster running on commit 0592999e3a which is a commit on master from August 2021, but it reports itself as v20.1 since it was somebody running locally and that was the most recent tag they had locally.

Can the Makefile and the bazel workflow run `git fetch origin --tags` before linking the tag?

This should be resilient to building offline. If there is an error pulling the tags, it can print a warning message and continue.

---

Update: See @rail's comment below for a different idea to improve the situation.

Jira issue: CRDB-12542

**Comment by rail** [comment]
Ideally we shouldn't rely on git and remote operations to improve build reproducibility, but in order to address the original issue we should use different approaches  (having `version.json`, for example).

Adding `git fetch --tags` should solve the issue short term though.

**Comment by rafiss** [comment]
This would also help with a different problem in our release process. Creating a new tag is an operation that does not require a PR or review, so the version that a given branch reports itself as could change at anytime and break tests. See https://cockroachlabs.slack.com/archives/C04U1BTF8/p1667581268561109 cc @renatolabs
