### ISSUE TITLE
sql: RowFetcher.processValueSingle should produce EncDatumRows

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#7529]
`EncDatum`s are designed to allow "tunneling" encoded values through distsql without unnecessary decoding and re-encoding.

`RowFetcher` should be modified to return `EncDatum`s instead of `Datum`s (see `readerBase.nextRow()`).

This will affect the regular SQL path so we need run benchmarks and make sure we don't cause regressions.

CC @paperstreet

**Comment by RaduBerinde** [comment]
@arjunravinarayan - this is a fairly self-contained task but it would get you acquainted with various aspects of the SQL layer. If you're interested I can give you some background in person.

**Comment by arjunravinarayan** [comment]
@RaduBerinde Should we close this now that #10550 is merged? It seems #8792 tracks the remaining work on datum encodings.

**Comment by RaduBerinde** [comment]
There was still a path (`processValueSingle `) that wasn't switched over no? (I believe the last conclusion was that it is used for single-column families)

**Comment by lego** [comment]
Can this be closed? It seems like processValueSingle no longer deals with Datums and EncDatums are now consumed by distSQL from the RowFetcher.

**Comment by RaduBerinde** [comment]
@lego, no, processValueSingle still decodes into a Datum and uses that to create an EncDatum (instead of creating an EncDatum that just points to the encoding).

https://github.com/cockroachdb/cockroach/blob/8c7ed16f7324edff94d853b9e2d7c95bfa2c7859/pkg/sql/sqlbase/multirowfetcher.go#L707

**Comment by jordanlewis** [comment]
I don't think it's especially important that we get this done at this point, so I'm going to close it.
