### ISSUE TITLE
storage: plumb tracing for queue operations

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#7535]
See https://github.com/cockroachdb/cockroach/issues/7489#issuecomment-229503430

**Comment by petermattis** [comment]
@BramGruneir Given your other work on rebalancing, can you take a look at this?

**Comment by BramGruneir** [comment]
Sure, I'll tackle it tomorrow.

**Comment by tschottdorf** [comment]
A trace is currently created in `func (bq *baseQueue) processReplica(repl *Replica, clock *hlc.Clock) error`. As @petermattis pointed out in #7489, it is currently used for no more than getting the leader lease. We should pass the created context into `bq.impl.process()` so that all queues can trace their follow-up operations.
