### ISSUE TITLE
storage: 1-to-3s upreplication test shows declined reservations

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#7536]
Shown sporadically in the /debug/events endpoint. These are unexpected (at least as long as the first node is the only one sending out replicas).

**Comment by BramGruneir** [comment]
I just checked versus master and this is still the case, however this is expected behaviour until preemptive snapshots are actually enabled.  So I'm going to leave this issue open to check again after preemptive snapshots are back.

**Comment by jordanlewis** [comment]
Do we need to revisit this?

**Comment by BramGruneir** [comment]
Might be worth checking to see the current status (which is why I left it
open). At the time, it was by design, but with streaming snapshots and
changes in rebalancing and reservations, things will be very different.

**Comment by BramGruneir** [comment]
Reservations have been re-worked, this issue is no longer needed.
