### ISSUE TITLE
stability: node crashes on deleted data directory

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#7540]
A Cockroach node will crash if you delete the log directory from underneath a running node.

```
panic: IO error: cockroach-data/000011.log: No such file or directory

goroutine 52 [running]:
panic(0x525d9a0, 0xc820877db0)
    /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1()
    /Users/nathan/Go/src/github.com/cockroachdb/cockroach/storage/store.go:2121 +0x3a5
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8203372d0, 0xc82030c8c0)
    /Users/nathan/Go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
    /Users/nathan/Go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62
```

It looks like @bdarnell has a TODO at this specific panic, but I doubt it's the only place which assumes the log directory will never disappear. That said, when I tried to reproduce, I got a clean shutdown with the error `log: exiting because of error: log: cannot create log: open cockroach-data/logs/cockroach.Nathans-MacBook-Pro.nathan.log.ERROR.2016-06-29T23_00_12-04_00.84308: no such file or directory`.

I don't think durability against crashes like this is a pressing issue at the moment, so I've added the later milestone.

**Comment by petermattis** [comment]
The file `cockroach-data/000011.log` is actually a RocksDB log file. There isn't much that can be done when you delete such a file. Don't do that.

Deleting the debug log directory (i.e. `cockroach-data/logs`) is also a fatal error. We could possibly do something better there, but it certainly isn't important.
