### ISSUE TITLE
Add RESET ALL (errors when using C# npgsql)

### ISSUE THREAD

**Issue by kamyker** [cockroachdb/cockroach#75435]
When using C# npgsql I'm getting errors from missing RESET ALL statement in cockroachdb. That command is used together with their auto-prepared statements feature. Otherwise DISCARD ALL is used correctly.

Npgsql: https://github.com/npgsql/npgsql/blob/001c5ef35cf29ec9109e9a8d2ae54108a5d7ac9e/src/Npgsql/Internal/NpgsqlConnector.cs#L2063

Postgres RESET ALL:
https://www.postgresql.org/docs/8.4/sql-reset.html

Epic CRDB-8948

**Comment by rafiss** [comment]
Thanks for reporting this!
