### ISSUE TITLE
export: improve error message: "unexpected closure of consumer"

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/cockroach#75460]
[This error message](https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/importccl/exportcsv.go#L292) may be misleading, and attributable to a different earlier failure. Can this error message be improved and/or would an improved error improve our ability to troubleshoot failed exports?

Jira issue: CRDB-12683

**Comment by shermanCRL** [comment]
For context, here’s an [internal CRL conversation](https://cockroachlabs.slack.com/archives/C2C5FKPPB/p1642868599117600) where it came up.

**Comment by stevendanna** [comment]
We no longer return this error message.
