### ISSUE TITLE
sql: SHOW TABLES reports deleted tables

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#7549]
Reported by user on Gitter:

(07:28) < yznming> [![blob](https://files.gitter.im/cockroachdb/cockroach/d9d2/thumb/blob.png)](https://files.gitter.im/cockroachdb/cockroach/d9d2/blob)
(07:29) < yznming> hi, i have drop a table, but i still can see it in the `show tables;`. Is this normal?

Perhaps we should remove tables in the process of being deleted from system.tables?

cc @andreimatei @vivekmenezes

**Comment by knz** [comment]
Perhaps related to #7499.

**Comment by knz** [comment]
cc @yznming

**Comment by vivekmenezes** [comment]
same as #7554
