### ISSUE TITLE
storage: streaming snapshots

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#7551]
Snapshots are currently sent using a single RPC containing all of the KV and raft log data for a range. Even if this were fully optimal and only contained a single version of the data in memory, we would still have a memory spike of O(size-of-range) when sending a snapshot. But due to the systems involved, we actually use 3-4x the base snapshot data.

Rather than sending a snapshot as a single RPC, we should stream the snapshot data to the remote replica. There are complications with doing this for raft-initiated snapshots, but we could likely get 90% of the benefit by streaming preemptive snapshots.

**Comment by tamird** [comment]
I believe the last thing left to do here is to stream the snapshot on the receiver.

**Comment by jordanlewis** [comment]
unassigning and cc @cuongdo for triage

**Comment by nvanbenschoten** [comment]
The rest of this work will be covered by https://github.com/cockroachdb/cockroach/issues/16954.
