### ISSUE TITLE
sql, server: rename `server.shutdown.lease_transfer_wait` to `server.shutdown.lease_transfer_timeout`

### ISSUE THREAD

**Issue by ZhouXing19** [cockroachdb/cockroach#75520]
In the current draining process, at the lease transfer phase, the server keeps retrying forever until all range leases on this draining node have been transferred. The cluster setting `server.shutdown.lease_transfer_wait` actually only specifies the timeout for **each iteration**, which means the duration of the whole lease transfer phase is not solely determined by that value. Therefore, it's inaccurate to name this setting as a "wait" period. 

Its current name can also be easily mixed with other real waiting period settings (e.g. `server.shutdown.drain_wait`, `server.shutdown.query_wait`). Ideally, `server.shutdown.lease_transfer_timeout` should be documented separately from the other waiting period settings.

Jira issue: CRDB-12707
Epic: CRDB-28893

**Comment by taroface** [comment]
It seems the description also needs to be corrected:

```
the amount of time a server waits to transfer range leases before proceeding with the rest of the shutdown process
```

**Comment by knz** [comment]
NB: we do not customarily rename *cluster settings*, unless there's egregious user confusion, because the process to do so is not easy (we have to maintain cross-version compatibility...) 

But documenting their help text and associated docs is super important, yes
