### ISSUE TITLE
server: Use counters instead of guages for specific metrics

### ISSUE THREAD

**Issue by logston** [cockroachdb/cockroach#75523]
**Is your feature request related to a problem? Please describe.**

CRDB uses a gauge instead of a counter for counting uptime. This is somewhat unexpected when exported as a Prometheus metric as most uptime metrics are monotonically increasing counters. Since the metric is exported as a gauge instead of as a counter, certain functionality within Prometheus's alerting tools are not guaranteed to work. For example, the function `resets` counts the number of "dips" in metric value but is explicitly labeled as a function that should only be used with counters. 

**Describe the solution you'd like**

The introduction of an uptime metric that is exported as a counter.

**Describe alternatives you've considered**

The current gauge based metric seems to work and we plan to use that until a proper counter is available.

**Additional context**
- It looks like a "crash-free uptime" counter was considered here: https://github.com/cockroachdb/cockroach/issues/27058 Such a counter would solve this issue as well. 

- https://github.com/cockroachdb/cockroach/blame/e27baa02ee9abc50d4445876e88c07181be77b55/pkg/server/status/runtime.go#L313
- https://prometheus.io/docs/prometheus/2.33/querying/functions/#resets

Jira issue: CRDB-12709

**Comment by ajwerner** [comment]
It seems to me like the problem is just that we're advertising this is a gauge as opposed to a counter, right? Semantically, this is a monotonically increasing value and as far as Prometheus is concerned in terms of data model, it's all the same thing. The only issue is some metadata.

**Comment by logston** [comment]
> It seems to me like the problem is just that we're advertising this is a gauge as opposed to a counter, right?

Correct. 

> Semantically, this is a monotonically increasing value and as far as Prometheus is concerned in terms of data model, it's all the same thing. The only issue is some metadata.

Yep, you're right. Perhaps since `metricType` is already built into `metric.Metadata`...

https://github.com/cockroachdb/cockroach/blob/e27baa02ee9abc50d4445876e88c07181be77b55/pkg/util/metric/metric.proto#L57-L64

... we could add `metricType` to ...

https://github.com/cockroachdb/cockroach/blob/e27baa02ee9abc50d4445876e88c07181be77b55/pkg/server/status/runtime.go#L147-L152

... and if needed, update ...

https://github.com/cockroachdb/cockroach/blob/e27baa02ee9abc50d4445876e88c07181be77b55/pkg/util/metric/metric.go#L427-L429

... to use the type save the Metadata?
