### ISSUE TITLE
ui: visualize sstable usage

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#7552]
The sstable size, levels, compactions and flushes have a direct impact on performance. Currently, we only expose the number of flushes and compactions being performed. We should provide a better tools for visualization the sstables for a node. At a minimum, we should maintain a metric for the read amplification for queries which is the number of level-0 sstables + the number of non-empty levels. But I'm also imagining that we could provide some graphical visualization of the current state of the sstables showing the number of files at each level as rectangles that are sized based on their data size. Something like:

```
L0: x x x
L1: xxx xx
L2: xxxxxx
```

**Comment by cuongdo** [comment]
I'll get started on recording the metric and adding the associated graphs. @maxlang, I leave the cool visualizations to you.

**Comment by petermattis** [comment]
@cuongdo FYI, I have a bit of work which adds a `debug sstables` command which can be used to derive the metric. I'll send out shortly.

**Comment by maxlang** [comment]
Added an issue to track adding an endpoint to the API #8781.
