### ISSUE TITLE
sql: show schema change state in sql commands

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#7554]
When a table is being dropped, it still shows up while running `show tables`

This is part of a more general problem, that during schema changes, change state is not properly visible. commands like `show tables;` , ``show index` should show useful state.

**Comment by knz** [comment]
@vivekmenezes usually when there is a duplicate issue, the newer issue is deleted and the older one is preserved. Why did you do it the other way around?

**Comment by knz** [comment]
Perhaps related to #7499.

cc @yznming

**Comment by vivekmenezes** [comment]
because this issue correctly classifies the general problem. Thanks for reporting the other issue.

**Comment by knz** [comment]
@vivekmenezes in that take you edit the title and the description of the original issue to make it more general. Again no need to create a new issue.

**Comment by vivekmenezes** [comment]
This work will involve moving the schema change checkpointing to use system.jobs table and developing sql commands to query system.jobs.

@benesch because some of his work is related.

**Comment by knz** [comment]
Note that this data is already shown in one of the virtual tables in crdb_internal. 
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by vivekmenezes** [comment]
Not sure what you mean. We should at a minimum populate the system.jobs table with the state of a schema change backfill job, so that users can query the system.jobs table for the state of a backfill job. We can start by adding an entry, updating the entry with every state change made by the state machine, write checkpoints and % progress as checkpoints are written.

**Comment by knz** [comment]
I think `SHOW TABLES` does not show dropped tables any more. Not sure what remains to be done here.

**Comment by vivekmenezes** [comment]
I'm going to close this issue. Users can query the jobs table for any state they may need.
