### ISSUE TITLE
multi-tenant: Relax restrictions on supported zone configuration changes from secondary tenants

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#75569]
Originally we were of the opinion that zone configurations in secondary tenants would only be updated by the multi-region semantics.  As a result, we restricted their use to only specify constraints which referenced the region or zone tiers:

https://github.com/cockroachdb/cockroach/blob/81c447ddb47e33d66f59acbcb1f76c37f5a148f6/pkg/sql/set_zone_config.go#L991-L1020 

The potential problem with this approach is that if we're going to make multi-tenant deployments the default deployment pattern for CRDB (something which is still being debated), this restriction will break some users.  We'll need to relax this restriction if/when we go down that route.

Jira issue: CRDB-12730

Epic CRDB-26686

**Comment by arulajmani** [comment]
> Originally we were of the opinion that zone configurations in secondary tenants would only be updated by the multi-region semantics. As a result, we restricted their use to only specify constraints which referenced the region or zone tiers:

It might be just me, but I found this phrasing slightly ambiguous. To clarify, we only restrict secondary tenants' to reference zone/region tiers in the constraints/voter constraints/lease preferences fields. However, they are allowed to alter all other fields, such as num_voters, gc.ttl etc. 

The reason for this limitation is that secondary tenants do not have access to the `NodeStatusServer`, and in turn, the underlying store descriptors. So they can't validate constraints such as hardware or other locality tiers. It's an open question if secondary tenants should have a wider view than what the `RegionServer` offers today, but if we were to support this functionality, we'd need to expose more things on the `RegionServer`.

**Comment by yuzefovich** [comment]
@knz suggested that this issue has been effectively superseded by #100787 which is next on Jeff's plate. I'll make some minor adjustments to the code to highlight that issue in error messages.
