### ISSUE TITLE
opt: do not greedily collect as many lookup join key columns as possible

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#75596]
When generating lookup joins, the optimizer greedily collects as many key columns as possible. This does not generate optimal lookup joins in all cases. For example:

```
exec-ddl
CREATE TABLE ab (
    a INT PRIMARY KEY,
    b INT NOT NULL,
    INDEX (b)
);
----

exec-ddl
CREATE TABLE cd (
    c INT NOT NULL,
    d INT NOT NULL,
    c_shard INT NOT NULL,
    PRIMARY KEY (c_shard, c),
    INDEX d_idx (d),
    CHECK (c_shard IN (0, 1, 2))
);
----

opt
SELECT * FROM ab INNER LOOKUP JOIN cd ON ab.a = cd.d AND ab.b = 1
----
inner-join (lookup cd@d_idx)
 ├── columns: a:1!null b:2!null c:5!null d:6!null c_shard:7!null
 ├── flags: force lookup join (into right side)
 ├── key columns: [1 11] = [6 7]
 ├── key: (5,7)
 ├── fd: ()-->(2), (5,7)-->(6), (1)==(6), (6)==(1)
 ├── inner-join (cross)
 │    ├── columns: a:1!null b:2!null "lookup_join_const_col_@7":11!null
 │    ├── multiplicity: left-rows(one-or-more), right-rows(zero-or-more)
 │    ├── fd: ()-->(2)
 │    ├── scan ab@ab_b_idx
 │    │    ├── columns: a:1!null b:2!null
 │    │    ├── constraint: /2/1: [/1 - /1]
 │    │    ├── key: (1)
 │    │    └── fd: ()-->(2)
 │    ├── values
 │    │    ├── columns: "lookup_join_const_col_@7":11!null
 │    │    ├── cardinality: [3 - 3]
 │    │    ├── (0,)
 │    │    ├── (1,)
 │    │    └── (2,)
 │    └── filters (true)
 └── filters (true)
```

The optimizer is able to add `c_shard:7` as a key column in the lookup join by using the check constraint filter. The join's input is crossed joined with the 3 possible values of `c_shard`. Filtering `c_shard` by all possible values has no affect on the selectivity of the join, and it triples the number of lookups that need to be performed. A better plan for this query would be:

```
inner-join (lookup cd@d_idx)
 ├── columns: a:1!null b:2!null c:5!null d:6!null c_shard:7!null
 ├── flags: force lookup join (into right side)
 ├── key columns: [1] = [6]
 ├── key: (5,7)
 ├── fd: ()-->(2), (5,7)-->(6), (1)==(6), (6)==(1)
 │    └── scan ab@ab_b_idx
 │         ├── columns: a:1!null b:2!null
 │         ├── constraint: /2/1: [/1 - /1]
 │         ├── key: (1)
 │         └── fd: ()-->(2)
 └── filters (true)
```

I'm not sure what the best solution is, but here are some ideas:

1. Some heuristic along the lines of "don't use a column as a key column if it's the last key column and it is constrained by a check constraint".
2. Generate a lookup join for each possible prefix of key columns of the index, and let the best cost lookup join win. This may better handle cases where a heuristic is lacking. For example:

```
exec-ddl
CREATE TABLE a (
    a INT PRIMARY KEY
);
----

exec-ddl
CREATE TABLE bcde (
    b INT PRIMARY KEY,
    c INT,
    d INT,
    e INT,
    INDEX (c, d)
);
----

opt
SELECT a, b FROM a INNER LOOKUP JOIN bcde ON a = c AND d IN (1, 2, 3)
----
project
 ├── columns: a:1!null b:4!null
 ├── key: (4)
 ├── fd: (4)-->(1)
 └── inner-join (lookup bcde@bcde_c_d_idx)
      ├── columns: a:1!null b:4!null c:5!null d:6!null
      ├── flags: force lookup join (into right side)
      ├── key columns: [1 10] = [5 6]
      ├── key: (4)
      ├── fd: (4)-->(5,6), (1)==(5), (5)==(1)
      ├── inner-join (cross)
      │    ├── columns: a:1!null "lookup_join_const_col_@6":10!null
      │    ├── multiplicity: left-rows(one-or-more), right-rows(zero-or-more)
      │    ├── scan a
      │    │    ├── columns: a:1!null
      │    │    └── key: (1)
      │    ├── values
      │    │    ├── columns: "lookup_join_const_col_@6":10!null
      │    │    ├── cardinality: [3 - 3]
      │    │    ├── (1,)
      │    │    ├── (2,)
      │    │    └── (3,)
      │    └── filters (true)
      └── filters (true)
```

Including `d:6` as a key column in the lookup join is beneficial if `d IN (1, 2, 3)` is highly selective, whereas omitting `d:6` from the key columns and eliminating the cross-join is beneficial if `d IN (1, 2, 3)` is not very selective. Note that we'd have to have accurate statistics for the selectivity of these joins in order to pick the best join, and I'm not sure the statistics we currently derive for these joins from the base table statistics would be sufficient.

Jira issue: CRDB-12737

**Comment by mgartner** [comment]
Labelling as a quick-win for the heuristic-based solution (1). The other solution is likely not a quick win.

**Comment by mgartner** [comment]
This issue can prevent generic query plans from being chosen when `plan_cache_mode=auto`. Generic query plans rely heavily on lookup joins. The greediness make lookup joins perform more lookups per input row than necessary. This drastically increases the estimate (and real!) cost of the lookup join. As a result of the high cost, the generic query plan is not chosen.

**Comment by DrewKimball** [comment]
This sounds a bit like a generalized version of the check we do here for trivial constraints: https://github.com/cockroachdb/cockroach/blob/ed3d3371ec8b1fe9982dd9b0835f4c4350031fc1/pkg/sql/opt/xform/select_funcs.go#L457-L464
