### ISSUE TITLE
hlc: make `max-offset` a cluster setting

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#75631]
We currently require a full cluster restart to change the `--max-offset` setting. It is [not sufficient with a rolling restart](https://www.cockroachlabs.com/docs/v21.2/cockroach-start#flags-max-offset), as nodes will [self-terminate](https://github.com/cockroachdb/cockroach/blob/564070a8993362017d41ffab3a887170d76b3292/pkg/rpc/heartbeat.go#L165-L169) if they encounter a node with a different max offset.

However, users find this inconvenient, and would prefer a cluster setting. Cluster settings are applied asynchronously and non-uniformly though, so different nodes would be running with different max offsets at different times. Is it possible to support this? This is also related to #75564, in that dynamic HLC error bounds is essentially equivalent to a non-uniform max offset.

We have an implicit assumption that all nodes (and thus all readers and writers) have identical clock uncertainty bounds (i.e. the max offset). See https://github.com/cockroachdb/cockroach/issues/75564#issuecomment-1022627182 for an example of how linearizability is violated when this assumption is broken. This assumption is used in e.g. uncertainty restarts, lease stasis periods, non-blocking transactions, and follower reads.

This is highly speculative, but could it be sufficient that all nodes have a real clock error that is below the max offset of any other node? For example, if we asynchronously change the max offset from 500 ms to 200 ms, but all nodes have an actual clock error of <=200 ms, does it matter that some nodes claim 500 ms while others claim 200 ms?

At least for uncertainty restarts, lease stasis periods, and commit wait, I don't think this matters: no nodes have a real clock error above 200 ms, so all clock readings are within 200 ms of the true time. Thus, no read will violate linearizability regardless of whether the reader has a 200 ms or 500 ms max offset, and similarly no replica will violate the lease stasis period regardless of whether the node believes the stasis period is 200 ms or 500 ms.

If the above turns out to be true, then a cluster setting for the max offset should be possible as long as all current nodes have a real clock error below the smallest max offset of any cluster node.

Jira issue: CRDB-12749

**Comment by aayushshah15** [comment]
Do you then think that this cluster setting should only ever allow `max-offset` to be reduced? The reasoning here only holds if we're reducing the max-offset, not if we're increasing it right?

**Comment by erikgrinaker** [comment]
It should hold with increases too, as long as the real clock error across all nodes is below the lowest max offset. Same reasoning.

Of course, any nodes with less accurate clocks (presumably the reason for the increase) cannot be added to the cluster until the new setting has fully propagated.

**Comment by erikgrinaker** [comment]
@knz points out a bootstrap dependency: we need to know the max offset before we can access cluster settings. So this doesn't seem viable.

However, we could still improve this somewhat by allowing the max offset to be changed via a rolling restart. That depends on whether it is safe to have a non-uniform max offset as outlined in the issue description.

Another option would be to propagate the max offset via e.g. gossip or some other non-KV channel, with a non-cluster-setting interface to control it. However, this would likely require some new custom infrastructure, and that effort seems better spent towards #75564 which could remove the need for the max offset entirely.

**Comment by bdarnell** [comment]
> @knz points out a bootstrap dependency: we need to know the max offset before we can access cluster settings. So this doesn't seem viable.

Could we start with a conservative default in order to reach the point that settings are available and then switch to the setting value once we have it? That seems like it should be as safe as using a cluster setting in the first place (as long as we can pick a suitably conservative default, or keep the command-line flag around just to control the pre-settings default). The main drawback I see is that we might have to wait for that conservative default (or some multiple of it) while we're starting up so node restarts get slow. And there may be an upper bound on how conservative we can be - I doubt a max offset of 10s would work since that exceeds the heartbeat interval and lease duration.

**Comment by erikgrinaker** [comment]
Yeah, that might work -- assuming, as you say, it doesn't affect startup too badly. It's more complexity for operators to manage (and potentially get wrong) though, in an already tricky domain.

**Comment by erikgrinaker** [comment]
Now that #85983 allows for non-uniform `max-offset`, do we really care about the cluster setting? The primary motivation here was to avoid a full cluster restart when changing it, which #85983 addresses, so I don't feel like the cluster setting is really worth the added bootstrap complexity.

I'm going to close this, but feel free to reopen if anyone disagrees.

CC @nvanbenschoten
