### ISSUE TITLE
kvserver: use non-cancelable contexts in raft application

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#75656]
**Describe the problem**

As of https://github.com/cockroachdb/cockroach/commit/d06405992f63ec553f804706e69ec1848bd77efb, raft application on the proposal happens under the proposer's context, which may well be canceled before or mid-way through the application. However, raft application should not care about the cancellation, and we just diagnosed a bug where it [did].

Also, we had problems with cancellation on the raft goroutine [in the past] and check against it, but evidently not well enough yet.

[did]: https://github.com/cockroachdb/cockroach/issues/68303#issuecomment-1024072878
[in the past]: https://github.com/cockroachdb/cockroach/blob/852a80c5a2efce038182343c55aae328629ba5e0/pkg/kv/kvserver/replica_raft.go#L521-L526

**Expected behavior**

The raft apply loop should use a ctx that is not cancelable. It makes sense to derive certain parts from the proposer - such as a trace span - but not the cancellation policy. That is, in

https://github.com/cockroachdb/cockroach/blob/852a80c5a2efce038182343c55aae328629ba5e0/pkg/kv/kvserver/replica_application_decoder.go#L139-L171

we should not use a child context of `cmd.proposal.ctx` but create one derived from `ctx (the worker ctx)` or `context.Background()`.

**Additional data / screenshots**

Should also write a test that uses a `TestingPostApplyHook` to ensure that the ctx is not cancelable, or at least that the cancellation doesn't carry over to the child. (Or more simply, that a value stashed in the proposer context is not visible at apply time).

@erikgrinaker didn't we put in some invariant check about this sometime recently?

Jira issue: CRDB-12769

**Comment by erikgrinaker** [comment]
Yeah, in `handleRaftReadyRaftMuLocked`:

https://github.com/cockroachdb/cockroach/blob/852a80c5a2efce038182343c55aae328629ba5e0/pkg/kv/kvserver/replica_raft.go#L518-L526

We should either do something similar for command application, or derive a non-cancellable context.

**Comment by tbg** [comment]
Wrote a bit of code here, putting this here so I remember: https://github.com/cockroachdb/cockroach/compare/master...tbg:no-downstream-ctx?expand=1

**Comment by tbg** [comment]
I updated the above prototype a little bit (removing the ctx altogether), but I don't think it's what we want for stability. Instead, I'll send a surgical PR that makes sure we don't set the caller's ctx into the proposal.
