### ISSUE TITLE
changefeedccl: changefeed metrics seem to not count additional changefeeds added to the metric

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#75683]
See video in: https://cockroachlabs.atlassian.net/wiki/spaces/CDC/pages/2398552506/22.1+Metrics+Labels+Acceptance+Testing for reproducibility

When creating a changefeed under a metrics label that already has a running changefeed on it, it seems like only the first changefeeds metrics are counted in the metrics label. We should investigate this to ensure this is not what is happening. 

Jira issue: CRDB-12780

Epic CRDB-13931

**Comment by miretskiy** [comment]
This might be webhook sink specific.  Tested w/ null sink -- two changefeeds clearly update counters...

**Comment by miretskiy** [comment]
Checked webhook: seems to work fine.

**Comment by miretskiy** [comment]
I think this is stale.
