### ISSUE TITLE
sql: Implement crdb internal functions that work like changefeed encoders

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#75730]
In order to troubleshoot changefeeds, it'd be useful in particular to confirm that an individual row is encoded as a message of a certain length. We'd want function signatures something like

crdb_internal_as_json(row) -> string (JSON representation of the row as it would be emitted by a json changefeed)
crdb_internal_avro_schema(table) -> string (JSON representation of the avro schema that would be registered for this table)
crdb_internal_as_avro_message(row, optional json string giving an avro schema) -> string (raw non-human-readable avro representation of the row)

Idea from @miretskiy .

Jira issue: CRDB-12808

**Comment by HonoreDB** [comment]
This should be much less painful now due to https://github.com/cockroachdb/cockroach/pull/84360 doing the heavy lifting.

**Comment by miretskiy** [comment]
@HonoreDB closing this issue as I believe it's complete.
Feel free to reopen if I'm mistaken.
