### ISSUE TITLE
sql: implement a preliminary system to limit memory consumption by clients

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#7573]
So I am running into #7572, a variant of #2524.

While we construct proper fixes to those, and in order to protect users against this type of problem in the future, especially when a query is issued for which we cannot do better optimization-wise, I'd like to introduce a limit in the number of values/bytes that can be populated into memory for a given client connection.

I propose the following implementation:
- have the sql.planner retain a new field memUsage
- in every planNode that captures rows into memory (namely `sortNode`, `distinctNode`, `valueNode`, `explainXXXNode` and `joinNode`), update this memUsage via their reference to planner (all have one). The memUsage would be the sum of Datum sizes populated in the rows, we'd need a small extension to the Datum API to measure data size.
- report a query execution error when planner.memUsage exceeds a threshold.

The threshold could be:
- a maximum per user, or
- a maximum per session, configured using SET, or
- a percentage of global memory, computed e.g. as total mem / current number of connections

Suggestions welcome.

**Comment by knz** [comment]
(Found while working on #3292 / #7351)

**Comment by knz** [comment]
cc @dt @petermattis

**Comment by tamird** [comment]
Gosh, wouldn't it be nice to have custom allocators? 👼

**Comment by petermattis** [comment]
@tamird It's difficult to plumb custom allocators everywhere (at least in C++).

@knz How would your proposal work in the distsql world?

**Comment by knz** [comment]
So for distsql we'd have a "processor" per node and per query. Each processor would hold a similar counter of datums held locally on behalf of that query; whenever that counter goes beyond the threshold an error would be reported using the regular error mechanism. @RaduBerinde opinions?

**Comment by RaduBerinde** [comment]
Yeah, I think this works as a basic mechanism to at least fail queries that would otherwise bring down the node entirely. Note that there are multiple processors in a flow (which is per query per node). But we can have a per-flow limit that the processors would consult.

Later this can evolve into a scheduling mechanism that queues up queries and executes them according to an upper bound estimate for how much memory they need.

**Comment by knz** [comment]
Closed via #9259.
