### ISSUE TITLE
kvclient: requests can spuriously backoff due to stale range descriptors

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#75742]
**Describe the problem**

We have a backoff mechanism in the DistSender to throttle requests during a lease transfer, where the would be lease holder has not applied the lease yet. We use the following check as a proxy for this scenario:

https://github.com/cockroachdb/cockroach/blob/ba04380bfbca30bf16e15048786716bec510a263/pkg/kv/kvclient/kvcoord/dist_sender.go#L2177-L2182

It turns out that this check can be overaggressive in certain scenarios, specifically the `updatedLeaseholder` determination. This, in conjunction with a transport constructed from a stale range descriptor and stale lease information, can lead to requests being caught in series of exponential backoffs causing high (tail) latencies. 

Concretely, consider the case where there's been a lease transfer to a replica that was a LEARNER on the requesting client's range descriptor. If the client has stale lease information as well then we would omit the [leaseholder when constructing the transport](https://github.com/cockroachdb/cockroach/blob/ba04380bfbca30bf16e15048786716bec510a263/pkg/kv/kvclient/kvcoord/replica_slice.go#L61-L63). 

A concurrent request could then update the client's cached lease information with the new leaseholder. Then, when the original request receives a NLHE, it tries to update the lease information on its eviction token. We first sync the eviction token with the RangeCache before updating the lease using the NLHE. If the range cache was updated underneath us to the new lease in the NLHE, we incorrectly determine that the leaseholder wasn't updated: 

https://github.com/cockroachdb/cockroach/blob/92f0260764a8d31d28f4ecae288c19c8468c2e0e/pkg/kv/kvclient/rangecache/range_cache.go#L389-L396

Further up the stack we incorrectly detect this as the case where there is a lease transfer in progress but the would be leaseholder hasn't applied the lease yet. This results in the request getting caught in backoffs. 

The situation is further exacerbated by the leaseholder not being a part of the transport ([when we try to move it to be considered as the next replica to try](https://github.com/cockroachdb/cockroach/blob/ba04380bfbca30bf16e15048786716bec510a263/pkg/kv/kvclient/kvcoord/dist_sender.go#L2166-L2168)). We essentially end up trying all replicas until we exhaust the transport and exponentially backing off between each request. 

Once the transport is exhausted we recognize that the range descriptor was stale, evict it. The subsequent retry then succeeds the very first time. 

----

We didn't see this in the traces that we looked at, but this hazard probably also applies in the case of this TODO:

https://github.com/cockroachdb/cockroach/blob/92f0260764a8d31d28f4ecae288c19c8468c2e0e/pkg/kv/kvclient/rangecache/range_cache.go#L1355-L1363

albeit for all replicas on the transport tried after we hit this codepath, considering we're actually updating the lease information above, and would thus skip backing off in that particular iteration. 

----

We can do a few things to improve this situation. At a high level, we probably want to detect the scenario where we have newer lease information than what the routing was created with and the new lease information is incompatible with the range descriptor the routing was created with. We are guaranteed to never try the leaseholder, as it doesn't exist on the transport, so we can simply clear the routing to exit early and force the client to try again. 

We recently started returning the [range descriptor's generation in the NLHE](https://github.com/cockroachdb/cockroach/pull/73697). We could extend this to return the entire range descriptor and using it to update the RangeCache (and thus skipping the range descriptor eviction described above). 

cc @cockroachdb/kv-notifications 

Jira issue: CRDB-12812

gz#11447

**Comment by kenliu-crl** [comment]
manually reviewed and updated
