### ISSUE TITLE
tests: long-running block_writer and photos tests

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#7580]
From comments on #7280:

@cuongdo Yeah, I was thinking we should have a daily block_writer and photos benchmark. I'd like to run both of those load generators for a couple of hours each, capture the average ops/sec and graph that over time.
---

We can have that too. I was thinking that we could easily add a flag to each that causes them to exit after a certain number of operations have been performed. This serves a couple of purposes:
1. It makes performance degradation over time really obvious on teamcity graphs.
2. It makes really bad performance degradation a hard test fail, because we'll exceed the test timeout.
---

@cuongdo block_writer now has two such flags: --max-blocks and --duration. Would be good to standardize all of the load generators to take such flags and to standardize their output.

**Comment by cuongdo** [comment]
cc @WillHaack for visualization of benchmarks

**Comment by petermattis** [comment]
Perhaps the load generators, when configured to run for a particular duration or number of ops, should output a line using the go benchmark format. Something like:

```
BenchmarkBlockWriter	  1000000	     48753 ns/op
```

**Comment by cuongdo** [comment]
I'm leaning toward making this test run for a specific duration.

These tests, combined with the performance degradation alerts that @WillHaack is adding to benchviz, should provide us continuous feedback for stability and performance.

**Comment by petermattis** [comment]
Sounds good to me.

**Comment by cuongdo** [comment]
this was done a long time ago
