### ISSUE TITLE
sql,config: tenant zone config lookup is broken

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#75864]
**Describe the problem**

In https://github.com/cockroachdb/cockroach/pull/74612 we made it so that the tenant has access to its own zone configs via the SystemConfig object provided by the `systemconfigwatcher`. Unfortunately this did not go far enough to actually fully address https://github.com/cockroachdb/cockroach/issues/70558 because of this special case logic: 

https://github.com/cockroachdb/cockroach/blob/4b8258c4b4a8f89fe8a4ea87fc8ee7cd5c916b6d/pkg/config/system.go#L371-L385

**Solution**

We need to either remove the above logic or make it conditional on where the config is coming from and more generally make sure that the SystemConfig methods work for the tenant. 

Epic: CRDB-10489

Jira issue: CRDB-12864

**Comment by ajwerner** [comment]
This affects the optimizer's ability to do locality aware search, and nothing else.

**Comment by ajwerner** [comment]
Also, this only affects serverless, so we can backport if the need arises.

**Comment by irfansharif** [comment]
It also affects the SQL GC job, right? https://github.com/cockroachdb/cockroach/blob/d61df4c5a2d4ec266cb78d8ed987a7b708583da0/pkg/sql/gcjob/refresh_statuses.go#L278-L295
