### ISSUE TITLE
distsql: synchronizers and routers checklist

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#7588]
This issue tracks implementation of synchronizers and routers

Synchronizers:
- [X] Passthrough
- [X] Ordered

Routers:
- [X] Passthrough
- [x] Mirror
- [x] By hash
- [x] By range

**Comment by irfansharif** [comment]
taking on router by mirror.

**Comment by petermattis** [comment]
@RaduBerinde Is the "By Range" router needed for 1.0?

**Comment by RaduBerinde** [comment]
No. Later milestone is fine.

**Comment by jordanlewis** [comment]
We've had a range router for a while, closing!
