### ISSUE TITLE
cdc: support an ALTER CHANGEFEED feature

### ISSUE THREAD

**Issue by sherman-grewal** [cockroachdb/cockroach#75895]
# Support an ALTER CHANGEFEED feature
## Description
Currently, the process of altering an enterprise changefeed can be quite cumbersome. In particular, this process would consist of finding and saving the high-water timestamp of the changefeed that you would like to alter, cancelling the changefeed, and then creating a new changefeed starting at the high-water timestamp that we previously saved. This process is not only inefficient, but it is error-prone as well. As a result, altering a changefeed has become an annoyance for many clients.

## Solution
We would like to address this issue by introducing a new SQL statement `ALTER CHANGEFEED` that would handle the process of altering a changefeed. By doing so, clients can avoid going through the process of altering a changefeed on their own, and rely on CRDB to carry out this task.

Jira issue: CRDB-12871

Epic CRDB-8670

**Comment by shermanCRL** [comment]
Based on a chat with @sherman-grewal, some scoping ideas. Sherman mentioned the complexities and considerations involved when the sink changes. I recommend doing this in phases:

1. ALTER CHANGEFEEDS without support for changing the sink; focus on options.
2. ALTER CHANGEFEEDS with support for changing the sink but not the sink _type_. So changing a Kafka URL is fine, but switching to (e.g.) webhooks is unsupported. 
3. ALTER CHANGEFEEDS allowing switching sink _types_.

We might even decide that the latter is uninteresting. How often is a user going to change a sink type? If so, they would probably have better clarity by just creating a new changefeed.

cc @amruss
