### ISSUE TITLE
kvserver: split with uninitialized RHS can race with raft changes to Term and Vote

### ISSUE THREAD

**Issue by sumeerbhola** [cockroachdb/cockroach#75918]
This came up in the review for https://github.com/cockroachdb/cockroach/pull/75761#pullrequestreview-871043043

During a split, if the right replica has been removed and added back (as an uninitialized replica), we load the HardState so that we can clear all the RHS state (including the HardState) and write back the HardState we have read. This peculiar dance accommodates the fact that our clearing of key ranges is coarse (if we could spare clearing the HardState we wouldn't need to read and write it).
https://github.com/cockroachdb/cockroach/blob/a950be5e3399abfb02a05b665fd81b965cc58d11/pkg/kv/kvserver/store_split.go#L84-L106

We know HardState.Commit cannot advance since the RHS cannot apply a snapshot yet. But there is nothing preventing a concurrent change to HardState.{Term,Vote} that we would accidentally undo here.

Discussion:
[tbg] We hold rightRepl.raftMu (this is not totally clear from looking at this method, but look how we access rightRepl.raftMu.stateLoader above, consider adding a comment; I think the lock is acquired in maybeAcquireSplitLock), and you need to hold that lock to mutate the HardState. We loaded the HardState just above, and are writing it again, so everything is still there.

[sumeer] maybeAcquireSplitLock calls getOrCreateReplica with the replicaID that we are trying to create. My reading of tryGetOrCreateReplica is that if it finds a Replica that is newer, it will return nil https://github.com/cockroachdb/cockroach/blob/c4f15d6c3d6e14ab1f91849ba7c007a49f47c9a1/pkg/kv/kvserver/store_create_replica.go#L118-L124 and we will then return here
https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvserver/replica_raft.go#L1828-L1832 without acquiring any lock.
Then in the code here we will look up the Replica using the RangeID and will find this newer Replica which isn't locked.

[tbg]
Ouch, yes, you are right. Throw in a rightRepl.raftMu.AssertHeld() and hopefully some test will fail under race. Then
```
if rightRepl == nil || rightRepl.isNewerThanSplit(split) {
  if rightRepl != nil {
    rightRepl.raftMu.Lock()
    defer rightRepl.raftMu.Unlock() // is that even enough? Do we do more stuff with rightRepl in splitPostApply?
  }
}
```
hopefully fixes that failure?

cc: @tbg @erikgrinaker 

Jira issue: CRDB-12877

**Comment by tbg** [comment]
This got fixed, I merged the patch above months ago.
