### ISSUE TITLE
kvserver: avoid indexed batch for Raft log truncation

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#75958]
Raft log truncation currently uses an indexed Pebble batch for deletions. @petermattis says:

> It is unfortunate that Raft truncation uses an indexed batch from a performance perspective. We go to all the effort of indexing each entry as it is added to the batch, but I don’t think we ever use that index. This might not be easy to change given the current structure of pre-apply operations. I’m not familiar enough with the code nowadays to say for certain.

We'll like switch to range tombstones for most non-trivial truncations soon (see #75802), but that may not help if point tombstones remain the common case:

> If we’re frequently using range tombstones instead of point tombstones, then yes, the indexing won’t matter much. But if the common case is that we’re still using point tombstones, we’d get a nice little perf win from avoiding the indexing. It doesn’t really matter if the indexing is being done on a small batch of deletes or a large batch of deletes, as the amortized cost of the indexing should be similar.

Jira issue: CRDB-12895

**Comment by pavelkalinnikov** [comment]
Under the work done in f9dee666, log truncations use unindexed batches: https://github.com/cockroachdb/cockroach/blob/89058d53769dad1d7f01c63afbc8e4722b2c3a35/pkg/kv/kvserver/raft_log_truncator.go#L554

This isn't enabled yet, and we still use the old path:
https://github.com/cockroachdb/cockroach/blob/89058d53769dad1d7f01c63afbc8e4722b2c3a35/pkg/kv/kvserver/replica_application_state_machine.go#L824-L835

... which uses an indexed batch for everything: https://github.com/cockroachdb/cockroach/blob/89058d53769dad1d7f01c63afbc8e4722b2c3a35/pkg/kv/kvserver/replica_application_state_machine.go#L406

Given that the plan is to switch to the new log truncator code, we can close this issue. Also, given that fixing the current path doesn't seem trivial.

CC @sumeerbhola
