### ISSUE TITLE
storage: tune storeSchedulerConcurrency

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#7596]
The `storeReplicaRaftReadyConcurrency` knob controls how much concurrency we allow in processing replicas within a single store. Currently we set the value to `2 * runtime.NumCPU()`. There are arguments to be made that the value should be lower to account for the I/O bottleneck. And the flip side, we want to perform concurrent RocksDB operations as many operations will hit the cache and even those that hit disk can benefit from better I/O scheduling when there are multiple outstanding operations. And finally, RocksDB batches the syncs for WAL writes when multiple mutations occur within a short period of time.

It's possible the ideal value is not tied to the number of CPUs.

**Comment by petermattis** [comment]
I need to revisit this again. The default of `2*runtime.NumCPU` seems insufficient. In recent testing on `denim`, `8*runtime.NumCPU` gave much better write throughput, presumably due to more opportunities for batching. I need to re-run those experiments and confirm whether a bump is in order.

**Comment by bdarnell** [comment]
propEvalKV will also reduce the amount of work done on the scheduler threads, so I would wait until that lands to do extensive experiments.

**Comment by petermattis** [comment]
Bumping the number of scheduler threads increases the opportunities for grouping of RocksDB batch, which is independent of prop-eval-kv.

**Comment by spencerkimball** [comment]
@petermattis I'm closing this given the gobs of performance work done since it was initially filed. Please re-open and assign if you feel legitimate work that needs to be tracked by an issue remains.

**Comment by petermattis** [comment]
See [this comment](https://github.com/cockroachdb/cockroach/issues/7596#issuecomment-290212730) and [this comment](https://github.com/cockroachdb/cockroach/issues/7596#issuecomment-290214417) from 3 days ago.
