### ISSUE TITLE
Rename idle_in_session_timeout to idle_session_timeout

### ISSUE THREAD

**Issue by denenr** [cockroachdb/cockroach#75984]
**Is your feature request related to a problem? Please describe.**
Postgres 14 added a configuration parameter called [`idle_session_timeout`](https://www.postgresql.org/docs/14/runtime-config-client.html#GUC-IDLE-SESSION-TIMEOUT). CockroachDB implements the same thing (unless I've misinterpreted something) since v20.2 under a configuration parameter of a slightly different name: [`idle_in_session_timeout`](https://www.cockroachlabs.com/docs/stable/set-vars.html).

**Describe the solution you'd like**
I suggest deprecating `idle_in_session_timeout` and aliasing it to `idle_session_timeout`. This would improve Postgres compatibility.

**Additional context**
`idle_in_session_timeout` was implemented following https://github.com/cockroachdb/cockroach/issues/50706

Epic CRDB-8948

**Comment by rafiss** [comment]
Thanks for bringing this to our attention! It seems like a sensible change -- we'll just have to make sure we can do it without being too disruptive to existing users.
