### ISSUE TITLE
roachperf: kv95 regression around February 1st

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#76013]
`kv95` dropped in excess of 20% around February 1st, e.g. [`kv95/enc=false/nodes=3 `](https://roachperf.crdb.dev/?filter=kv95&view=kv95%2Fenc%3Dfalse%2Fnodes%3D3&tab=gce):

<a href="https://roachperf.crdb.dev/?filter=kv95&view=kv95%2Fenc%3Dfalse%2Fnodes%3D3&tab=gce"><img width="864" alt="Screenshot 2022-02-04 at 09 48 45" src="https://user-images.githubusercontent.com/644420/152499271-be109b01-f24a-48eb-a26b-7cb9b4c061ce.png"></a>

**Comment by erikgrinaker** [comment]
Bisected to #74115. @Azhng can you have a look?

**Comment by Azhng** [comment]
Hmm where can I find the parameters used for this perf test.

**Comment by ajwerner** [comment]
https://github.com/cockroachdb/cockroach/blob/21a286f2b2978b1cc117596865cd680dd268cf74/pkg/cmd/roachtest/tests/kv.go#L164 is one I'd start with. Create a 2-node cluster with 
* `roachprod create $CLUSTER --gce-machine-type n1-standard-8 -n 2`
* `roachprod stage $CLUSTER cockroach` 
* `roachprod start $CLUSTER:1`
* `roachprod run $CLUSTER:1 -- ./cockroach workload init kv --splits 32  {pgurl:1}`
* `roachprod run $CLUSTER:1 -- ./cockroach workload run kv --concurrency 64  {pgurl:1}`

Try it with a binary before your change and after to get some data. Some folks have some scripts in places but it should be easy to spot the difference 

These instructions correspond to https://roachperf.crdb.dev/?filter=kv95&view=kv95%2Fenc%3Dfalse%2Fnodes%3D1&tab=gce.

**Comment by ajwerner** [comment]
Why do all of your benchmark outputs look identical for all of the values? That seems wrong. Are you sure you're running benchstat correctly?

> Perhaps bringing back the ringbuffer to replace the cache.UnorderedCache might be another idea.

I think there's a compromise here. Your old ring-buffer was extremely inefficient on the search side IIRC. We can keep a ring-buffer and a map downstream. That'll be better than the `UnorderedCache`. Let's see a benchmark that's affected first.

**Comment by Azhng** [comment]
> Why do all of your benchmark outputs look identical for all of the values? That seems wrong. Are you sure you're running benchstat correctly?


I did a run with `-count 10`. I used `benchstat` to collapse the 10 run into a single rows because it makes the number rows smaller and easer to read.

**Comment by ajwerner** [comment]
What I encourage you to do is use some `sed` and rewrite the benchmark files so you can compare the different sinks directly.

Can you post the raw data files?

**Comment by Azhng** [comment]
The data with blackhole sink is the `old` and the one with real sink is `new` 

```
$ benchstat ~/tmp/blackhole ~/tmp/real                                                                                                               [13:46:19]
name                            old time/op    new time/op    delta
Writer/concurrentWriter=1-24      72.7ns ± 0%  1037.0ns ±39%    +1326.53%  (p=0.000 n=8+10)
Writer/concurrentWriter=24-24     3.00µs ±12%    6.91µs ±22%     +130.23%  (p=0.000 n=10+10)
Writer/concurrentWriter=48-24     6.67µs ± 2%    9.76µs ±13%      +46.44%  (p=0.000 n=9+10)
Writer/concurrentWriter=64-24     9.20µs ± 7%   12.61µs ± 6%      +37.05%  (p=0.000 n=9+10)
Writer/concurrentWriter=92-24     14.4µs ± 3%    16.2µs ± 7%      +12.10%  (p=0.000 n=10+9)
Writer/concurrentWriter=128-24    22.8µs ± 3%    23.1µs ± 6%         ~     (p=0.146 n=8+10)

name                            old speed      new speed      delta
Writer/concurrentWriter=1-24     338GB/s ± 0%    25GB/s ±32%      -92.55%  (p=0.000 n=8+10)
Writer/concurrentWriter=24-24   8.24GB/s ±13%  3.59GB/s ±19%      -56.36%  (p=0.000 n=10+10)
Writer/concurrentWriter=48-24   3.69GB/s ± 2%  2.53GB/s ±15%      -31.38%  (p=0.000 n=9+10)
Writer/concurrentWriter=64-24   2.67GB/s ± 7%  1.95GB/s ± 7%      -27.03%  (p=0.000 n=9+10)
Writer/concurrentWriter=92-24   1.70GB/s ± 3%  1.51GB/s ± 3%      -11.61%  (p=0.000 n=10+8)
Writer/concurrentWriter=128-24  1.08GB/s ± 3%  1.07GB/s ± 6%         ~     (p=0.146 n=8+10)

name                            old alloc/op   new alloc/op   delta
Writer/concurrentWriter=1-24       0.00B        197.44B ± 8%        +Inf%  (p=0.000 n=10+9)
Writer/concurrentWriter=24-24     0.40B ±150%  1123.88B ± 0%  +280868.75%  (p=0.000 n=10+8)
Writer/concurrentWriter=48-24      2.00B ± 0%  2073.30B ± 0%  +103565.00%  (p=0.000 n=10+10)
Writer/concurrentWriter=64-24      3.40B ±18%  2750.60B ± 0%   +80800.00%  (p=0.000 n=10+10)
Writer/concurrentWriter=92-24      6.00B ± 0%  3823.50B ± 0%   +63625.00%  (p=0.000 n=8+10)
Writer/concurrentWriter=128-24     9.20B ±13%  5277.00B ± 1%   +57258.70%  (p=0.000 n=10+10)

name                            old allocs/op  new allocs/op  delta
Writer/concurrentWriter=1-24        0.00           1.50 ±33%        +Inf%  (p=0.000 n=10+10)
Writer/concurrentWriter=24-24       0.00          24.00 ± 0%        +Inf%  (p=0.000 n=10+10)
Writer/concurrentWriter=48-24       0.00          48.00 ± 0%        +Inf%  (p=0.000 n=10+10)
Writer/concurrentWriter=64-24       0.00          63.00 ± 0%        +Inf%  (p=0.000 n=10+9)
Writer/concurrentWriter=92-24       0.00          91.00 ± 0%        +Inf%  (p=0.000 n=10+10)
Writer/concurrentWriter=128-24      0.00         127.10 ± 1%        +Inf%  (p=0.000 n=10+10)
```

Raw data file: 

[bench.tar.gz](https://github.com/cockroachdb/cockroach/files/8026660/bench.tar.gz)

**Comment by ajwerner** [comment]
Alright, I've sorted this out and it's annoying. It's that when we use the UUID as the key in the `UnorderedCache` we allocate that UUID. We also allocate for the uint64 if it's not a small number, which your benchmark misses. 

I think the answer here is that we should create a specialized cache which, on some level, is a `map[uuid.UUID]roachpb.TransactionFingerprintID` and a linked list of `messageBlock` or something like that.

**Comment by Azhng** [comment]
Ah I see. Hmm I'm curious, how did you find that culprit?

**Comment by ajwerner** [comment]
To some extent, your profiles, and then thinking about why we were allocating. I checked out the branch, ran the benchmark, made a tiny hack that didn't work, and then realized.
