### ISSUE TITLE
cli: should be able to specify `--join`  multiple times

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#7610]
Instead of `--join "a,b,c"` we should equivalently accept `--join a --join b --join c` (or even phase out the first form). This is similar to how `--store` works.

The reason for this suggestion is that it's easier to create the command line args in an automated fashion.

**Comment by a6802739** [comment]
@tschottdorf , I could do this issue. can I assign this to myself?

**Comment by tschottdorf** [comment]
Hi, no need to assign - it's all yours. :)

On Mon, Jul 11, 2016 at 5:23 AM songhao <notifications@github.com> wrote:

> @tschottdorf <https://github.com/tschottdorf> , I could do this issue.
> can I assign this to myself?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/7610#issuecomment-231684042>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE135ESf6zMI9aP-u2exhRxXShc0eqHGks5qUguigaJpZM4JD-Ec>
> .
>
-- 

-- Tobias

**Comment by rushiagr** [comment]
Hi! I just created a commit fixing this issue (didn't knew it'll update the issue even if I'm pushing code in my fork without creating a PR). I'd appreciate if some feedback can be provided. Then I'll go ahead and tidy up the code, and write tests too.

Sorry @a6802739, didn't notice your comment until after writing the code. Did you start working on the issue?

**Comment by a6802739** [comment]
@rushiagr , yes, I have started. it's ok, just go for it.
