### ISSUE TITLE
storage: leaseholder-collected mostly accurate replicated stats

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#7611]
Thought about this at some point during recent discussions on metrics. Not sure we need this at this point, but wanted to write it down. It's probably also the "obvious" way to do it.

Say, for example, we want relatively accurate per-Range MVCC read statistics. Reads are served locally from the lease holder, so there's no Raft traffic involved. Yet, we somehow want to track them over long periods of time even when leaders crash and burn. Here's one easy way (centered around keeping read statistics to make the example more concrete)
- turn `(*Replica).mu.state.Stats` and its persisted counterpart into (essentially) `struct Stats { Read, OnDisk MVCCStats }` (but as a proto)
- `stats.OnDisk` is used as we use `MVCCStats` now to keep track of on-disk bytes
- MVCC read operations also populate MVCCStats (have to define what that means or use a different struct more adapted to "reading")
- leaseholder-serviced reads populate a one-off in-memory counter from those read stats (not the one in `r.mu.state.Stats` - that one is consistent through Raft)
- periodically sends a Raft command (LeaderLease?) which adds a supplied read stats object to `r.mu.state.Stats.Read`
- in-memory counter is reset when that command is proposed, and reset on lease changes, snapshots, etc.

The result is that all replicas have a relatively accurate, congruent idea about bytes read. The same can be done for essentially any leaseholder-centric counter.

**Comment by a6802739** [comment]
@tschottdorf, I want to fix this issue. I'm using cockroachdb in my program, it's a fantastic program, I want to contribute some code in this program.

**Comment by tschottdorf** [comment]
Sorry for getting back to you that late @a6802739. I think this issue isn't ready to be tackled yet (we're not yet sure if we're going to use it, see #7682 where that decision will likely be made).
We have a few issues which are worth tackling and aren't too hard here: https://github.com/cockroachdb/cockroach/issues?q=is%3Aopen+is%3Aissue+label%3Aeasy

I think https://github.com/cockroachdb/cockroach/issues/7643 and https://github.com/cockroachdb/cockroach/issues/7610 are both useful to solve and I'd be happy to see you tackle it.

**Comment by a6802739** [comment]
@tschottdorf , sorry to response late. I will try to deal with #7643 and #7610.
