### ISSUE TITLE
cmux: needless fork?

### ISSUE THREAD

**Issue by onlyjob** [cockroachdb/cockroach#7612]
As reported in https://github.com/soheilhy/cmux/issues/26 and https://github.com/coreos/etcd/issues/5860:
[github.com/cockroachdb/cmux](https://github.com/cockroachdb/cmux) is a fork of actively maintained [github.com/soheilhy/cmux](https://github.com/soheilhy/cmux).

Needless forking is harmful. Perhaps both projects could join efforts and benefit from working together?

Besides it is not even possible to report bugs to _github.com/cockroachdb/cmux_...

**Comment by tamird** [comment]
There was a long period of working together (https://github.com/soheilhy/cmux/pulls?q=is%3Apr+is%3Aclosed+author%3Atamird). At some point, after fixing many bugs upstream, I came to feel that working with upstream was more grief than it was worth; here's one long back-and-forth where we disagreed https://github.com/soheilhy/cmux/pull/19#discussion_r54335867.

The divergence between upstream and our fork is minimal, and while I agree that forking is a last resort, I'm not prepared to accept (and re-validate) upstream's changes.

**Comment by onlyjob** [comment]
Fair enough. But since you maintain independent fork could you enable bug tracker please?

**Comment by tamird** [comment]
Done.

**Comment by onlyjob** [comment]
Thanks! :)
