### ISSUE TITLE
Database backup to AWS s3 with IAM role not working

### ISSUE THREAD

**Issue by junaid-ali** [cockroachdb/cockroach#76142]
**Describe the problem**

IAM role is attached to the Kubernetes pod on AWS EKS via [IRSA](https://docs.aws.amazon.com/emr/latest/EMR-on-EKS-DevelopmentGuide/setting-up-enable-IAM.html), and has permissions to upload objects. I can perform `aws s3 ls s3://<my-bucket-name>/` CLI command, and `cp` to upload files.

```shell
$  aws sts get-caller-identity
{
    "UserId": "XXXXXXXX:botocore-session-12345678",
    "Account": "1234567812345",
    "Arn": "arn:aws:sts::1234567812345:assumed-role/<my-role-name>/botocore-session-12345678"
}
```

When running the CockroachDB `backup` command to back up the DB to s3, it results into:
```shell
$ /cockroach/cockroach sql --certs-dir=/cockroach-certs/ --host cockroachdb-public --execute="BACKUP DATABASE backup_test INTO 's3://<my-bucket-name>/?AUTH=implicit'
ERROR: failed to get s3 object: AccessDenied: Access Denied
        status code: 403, request id: XXXXXXX, host id: xxxxxxxxx
Failed running "SQL"
```

Running aws cli command:
```shell
$ aws s3 cp cockroach.sh s3://<my-bucket-name>/
upload: ./cockroach.sh to s3://<my-bucket-name>/cockroach.sh
```

The backup works when we explicitly specify the access and secret keys of a <strong>user</strong> to the `BACKUP` command destination

**To Reproduce**

described above

**Expected behavior**
Backup should work when using AWS IAM role for implicit authentication.

**Additional data / screenshots**

n/a

**Environment:**
 - CockroachDB version: `v21.1.10`
 - Server OS: Kubernetes, helm deployment
 - Client build tag: `v21.1.8`

**Additional context**
What was the impact?

**Comment by junaid-ali** [comment]
workaround:
1. Use `aws sts` to get temporary credentials
2. Provide the temporary access key id, secret key and session token as URL params in the destination.
    NOTE: session token should be provided as `AWS_SESSION_TOKEN` and must be URL encoded.

**Comment by adityamaru** [comment]
Hey @junaid-ali! Thanks for reaching out. Before I dig into AWS-specific documentation, I just want to confirm that the `IMPLICIT` authentication mode means that every machine running a cockroach node (i.e. participating in the backup) should be able to talk to the AWS bucket using its configured credentials. Have you confirmed that this is the case?

**Comment by junaid-ali** [comment]
@adityamaru Thanks for the clarification. IAM role isn't attached to the cockroach nodes, only to the node from where I'm running the cockroach sql command. I will test with attaching role to all the nodes and close the issue.

**Comment by adityamaru** [comment]
@junaid-ali please feel free to reopen if the issue is not resolved, thanks!
