### ISSUE TITLE
sql: ability to fix tables to 1 column-family

### ISSUE THREAD

**Issue by ddorian** [cockroachdb/cockroach#7615]
This way, you won't have to store family-id/column-id on each key, since the whole table will have 1 column-family and 1 row-version will be guaranteed to be in 1 kv.
This should make the keys in commit-log, cache, memory, block-index, etc smaller.

**Comment by petermattis** [comment]
From the [column families RFC](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/sql_column_families.md):

> Finally, the /<familyID> key suffix will be omitted when encoding FamilyID(0) to make the encoding identical to the previous sentinel key encoding.

If you put all of the columns in a table into a single column family the `/<familyID>` suffix for the key won't be stored, effectively providing the optimization you're proposing.

**Comment by ddorian** [comment]
I read the rfc and didn't spot it. sorry/thanks
