### ISSUE TITLE
ui: move metrics string names to a protobuf enum

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#7621]
This will reduce duplication and help avoid mistakes by automatically generating the correct string constants on the server and client.

**Comment by a6802739** [comment]
@tamird , I want to figure this issue. But I cann't quite understand what do you mean? could you give me a more concrete explanation?

**Comment by tamird** [comment]
With our current protobuf infrastructure, I don't think this would work well. See the block comment in https://github.com/cockroachdb/cockroach/blob/develop/ui/app/util/protoEnums.ts.

I'd say this is blocked on #6616 for now.
