### ISSUE TITLE
Support Cluster ID API for SQL only servers.

### ISSUE THREAD

**Issue by rimadeodhar** [cockroachdb/cockroach#76211]
SQL only servers should implement the cluster ID API in order to return the friendly cluster ID for a multitenant cluster. We need this API in order to support the header on the landing page for DB Console for SQL only servers. 

Epic CRDB-12100

Jira issue: CRDB-13028

**Comment by dhartunian** [comment]
This feature already exists. Tenants report a cluster ID via the Admin API.
