### ISSUE TITLE
changefeed: Increase maximum message sizes.

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#76258]
Sarama library used to write to kafka restricts a message to be at most
MaxMessageBytes bytes -- which is set to 1MB.
In addition, sarama imposes a limit of MaxRequestSize for a request (100MB).

Those 2 settings are currently not configurable, and we have customers who start storing very large
(5+MB) JSON blobs that can easily exceed MaxMessageBytes.

We need to make changes to support those messages.  One way to do this would be to extend
`kafka_sink_config` to support those options.  But perhaps, a better approach is to just make those
"unlimited".  We already limit amount of memory that can be consumed by changefeed, and thus
if we were able to ingest the message, and convert it to appropriate format (avro or json), then perhaps
the library itself should not apply any additional limits and any failures should come from the downstream
rejecting those messages.

**Comment by daniel-crlabs** [comment]
I'm not sure if this is related, but just wanted to point out I ran into this GH issue as well, when troubleshooting this same problem. The GH is from Shopify/sarama [Producer doesn't respect MaxMessageBytes limit for uncompressed requests](https://github.com/Shopify/sarama/issues/1140)

**Comment by kmanamcheri** [comment]
@miretskiy The default value of `MaxMessageBytes` as documented in [sarama/config.go](https://github.com/Shopify/sarama/blob/main/config.go#L164) is `1 MB` not `10 MB` which makes it even more of a tight limit.

This issue combined with https://github.com/cockroachdb/cockroach/issues/65211 (_CDC changefeed to Kafka retrying backfill non stop when Kafka errors out_) makes the changefeeds system effectively not usable even if there is a single row which is longer than 1MB. The producer errors out, and the cdc job restarts from the beginning and this ends up in an infinite loop just dumping data over and over again into Kafka.

A simple quick fix would be to pass along the max message bytes config from the user into sarama config. A nicer fix would be to query Kafka server to ask for the server settings and set it automatically

**Comment by miretskiy** [comment]
Right; sorry 1MB.

**Comment by miretskiy** [comment]
@kmanamcheri Thank you for bringing this up.  The problem of looping on the same message is known.
We will address it with some sort of a "dead letter queue" type solution.  This particular issue should deal with kafka side.
If a message is rejected, then it should be rejected by remote host, and not by sarama library.

**Comment by kmanamcheri** [comment]
Yup, yes I like the dead letter queue system. That makes sense.

I am asking if we can make a small fix for this (to enable passing in a the max message bytes config) and release it as a patch :)

That's why I brought up the issue of this is a completely blocker for us since the changefeed is not usable at all, and the fix of adding a single flag to pass through the max message bytes seems like a relatively low-risk fix.

**Comment by miretskiy** [comment]
@amruss  -- see re DLQ above.
