### ISSUE TITLE
Improve SQL Proxy Connection Errors

### ISSUE THREAD

**Issue by JeffSwenson** [cockroachdb/cockroach#76267]
Connection errors returned by the sql proxy are mediocre. One example is the error returned when the user supplies a database name like ".database" or "cluster.database.extra":

```
FATAL: codeParamsRoutingFailed: invalid database param
SQLSTATE: 08004
```

There are a few problems with this error:
1. The codeParamsRoutingFailed prefix does not match the style of other errors returned by crdb.
2. The error does not describe what the proxy thinks the database parameter is. This may be important if the user provided a malformed connection url to a client driver and the driver extracted something unexpected as the database.
3. There is no hint describing the expected format of the database parameter.

Ideally the error the error would look something like:
```
FATAL: routing error: invalid database parameter 'cluster.database.extra' 
HINT: database must be formatted like 'databasename' or 'cluster_name.database_name'
```

Jira issue: CRDB-13053

**Comment by ianjevans** [comment]
In the docs we call it `routing_id.database_name`, as users need both the cluster name (e.g. `frizzy-llama`) and the tenant ID (e.g. `1234`) to connect to `frizzy-llama-1234.defaultdb`.

**Comment by jaylim-crl** [comment]
Closing this stale issue. We've already addressed this. Errors now look like the following:

```
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
FATAL: codeParamsRoutingFailed: missing cluster identifier
SQLSTATE: 08C00
HINT: Ensure that your cluster identifier is uniquely specified using any of the
following methods:

1) Host name:
   Use a driver that supports server name identification (SNI) with TLS
   connection and the hostname assigned to your cluster
   (e.g. serverless-101.5xj.gcp-us-central1.cockroachlabs.cloud)

2) Options parameter:
   Use "--cluster=<cluster identifier>" as the options parameter.
   (e.g. options="--cluster=active-roach-42")

3) Database parameter:
   Use "<cluster identifier>.<database name>" as the database parameter.
   (e.g. database="active-roach-42.defaultdb")

For more details, please visit our docs site at:
	https://www.cockroachlabs.com/docs/cockroachcloud/connect-to-a-serverless-cluster
Failed running "sql"
```

I do agree that the `codeParamsRoutingFailed` prefix doesn't match the style of other errors. We'll revisit this if there's a need.
