### ISSUE TITLE
Ability to enable multiple modification subqueries of same table per client session

### ISSUE THREAD

**Issue by dimpavloff** [cockroachdb/cockroach#76261]
**Is your feature request related to a problem? Please describe.**

To mitigate the risks of #70731, #70976 disabled having multiple subquery modifications on the same table in the same transaction and created the `sql.multiple_modifications_of_table.enabled` cluster setting to re-enable it. 

Having it as a cluster setting feels too broad, however. A cluster admin may be forced to enable it for an important query if it is safe to run. However, subsequent new queries may hit the problems of #70731 without anyone noticing.

**Describe the solution you'd like**
It would be better if `sql.multiple_modifications_of_table.enabled` can be toggled as a session variable. This allows to locally reason about particular queries.

Jira issue: CRDB-13051

**Comment by michae2** [comment]
Hi @dimpavloff, this is a good point. I think we were hoping to have a fix to #70731 sooner, but obviously it hasn't happened yet. Let me see what I can do.

**Comment by dimpavloff** [comment]
Thanks!
