### ISSUE TITLE
dev: generate go does not pull all generated files back into the repo

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#76276]
**Describe the problem**

I noticed this with a mockgen target, but it appears, IIUC, that we pull very few files back from the sandbox in `dev generate go`. It appears that we only pull files as described here: https://github.com/cockroachdb/cockroach/blob/522e15b936746c78b161a456d587e3d853b55307/build/bazelutil/checked_in_genfiles.txt#L6-L8

This is far less than ideal. If we're to replace the makefile and go generate more broadly, we need to be able to reliably pull *every* generated artifact we rely on back into the repo. 

**Solution**

Let's make targets like the protobuf targets to hoist all the generated code.

Epic CRDB-8036

**Comment by ajwerner** [comment]
I ran `dev generate go` and didn't see them pulled. I'll try again in a bit.

**Comment by rickystewart** [comment]
Is this bug stale now?

**Comment by ajwerner** [comment]
Yes, I think this is stale.
