### ISSUE TITLE
server: error checking in session API is incorrect

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#76288]
**Describe the problem**

This code in server/status.go, `getLocalSessions`:

```go
errViewActivity ≔ b.privilegeChecker.requireViewActivityOrViewActivityRedactedPermission(ctx)
if !isAdmin && errViewActivity != nil {
   ...
```

is incorrect.  If a non-privilege error was encountered inside the requireViewActivity method (e.g. an internal KV error), that error should be returned to the client immediately. The current code "papers over" it. 

Jira issue: CRDB-13061

**Comment by jocrl** [comment]
Note: other changes in https://github.com/cockroachdb/cockroach/pull/76292 highlight other code demonstrating how this should be correctly handled.
