### ISSUE TITLE
rpc: BenchmarkGRPCDial has rotted

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#76304]
```
make bench PKG=./pkg/rpc                     
--- FAIL: BenchmarkGRPCDial
    context_test.go:1942: initial connection heartbeat failed: rpc error: code = Unimplemented desc = unknown service cockroach.rpc.Heartbeat
FAIL
```

The benchmark is skipped `UnderShort`, which is perhaps why the CI job that runs all the benches once hasn't picked it up?
https://github.com/cockroachdb/cockroach/blob/d3ed36438b00a1993abd3e4158c56891c779cc94/pkg/rpc/context_test.go#L1922

Jira issue: CRDB-13069

**Comment by herkolategan** [comment]
Just noted this as well during a full microbenchmark run. `skip.WithIssue` is probably a better candidate. But this is the only issue I could find on the matter currently. I'll see if I can get a fix in place or I'll replace the skip with `skip.WithIssue`.
