### ISSUE TITLE
storage: add raft invariant checks

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#7632]
Raft has certain invariants that we shouldn't break. For example, `raftpb.HardState.Commit` should not move backwards. We could do a better job at asserting these invariants in our code, not at the `Replica` level, but down at the storage level. Possibilities:
- We could post-process the RocksDB WAL entries after a test has completed and verify that no raft invariants have been violated.
- We could add hooks in `storage/engine/mvcc.go` to check the invariants when certain keys are written. This would likely be too expensive to turn on in production, yet still valuable for tests. 
- Check the invariants in the various save routines in `replica_state.go`. These routines should contain all of the mutations for raft state. Also likely to be too expensive to turn on in production. 

Cc @tschottdorf and @arjunravinarayan

**Comment by tschottdorf** [comment]
Closing as stale. Raft corruption has happened since, but usually over process restarts/crashes. Raft itself has lots of assertions that catch problems within a running process.
