### ISSUE TITLE
ci: cannot find artifacts for acceptance test failures

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#76370]
**Describe the problem**
I got a test failure in [this build](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_Acceptance/4111226?buildTab=overview&showRootCauses=false&expandBuildProblemsSection=true&expandBuildTestsSection=true&expandBuildChangesSection=true&expandBuildDeploymentsSection=true)

And it's in acceptance, and it tells me I should have artifacts:
![image](https://user-images.githubusercontent.com/642886/153424994-366ec050-e5c9-4771-9053-1551dfca5c13.png)

Then I navigate to the artifacts tab:
![image](https://user-images.githubusercontent.com/642886/153425046-655485ee-0686-435b-b2db-fec4ca3139fc.png)

it's empty!?

**Expected behavior**

The artifacts produced by the test are copied to the CI artifacts tabs, where they can be downloaded.

Jira issue: CRDB-13088

**Comment by knz** [comment]
cc @rail

**Comment by rail** [comment]
The run above is from almost a month ago. We keep artifacts around only for 7 days. There is a ticket to increase this: https://cockroachlabs.atlassian.net/browse/DEVINF-148
