### ISSUE TITLE
storage: lots of heartbeat sending from rawnode leader to followers

### ISSUE THREAD

**Issue by zhonglin6666** [cockroachdb/cockroach#7638]
issue:  
Now there are lots of replica on one store, a replica will create one rawnode group, so leader will send heartbeat to keep it's degree. There are so many replica which will send lots of heartbeat message, For only few rawnode group working, whether no need so many rawnode group.

advice:
Starting a fixed number of rawnode group as workers who will handle request when there are free. Workers will share all requests of one store, which will decrease lots of heartbeat message.

**Comment by tschottdorf** [comment]
Thanks @zhonglin6666. This should be handled by #6107 (after which we only send heartbeats between nodes, not between ranges).
