### ISSUE TITLE
bazel: seems like some analysis passes do not run under bazel CI

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#76387]
**Describe the problem**

Consider these two builds.
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_GitHubCiOptional/4348050?showRootCauses=false&expandBuildChangesSection=true

[https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/4348084?showRootC[…]ndBuildProblemsSection=true&expandBuildTestsSection=true](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/4348084?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true)

Epic CRDB-8306

**Comment by rickystewart** [comment]
This lint comes from `errwrap`, and I think the problem is that since we don't build `dev` in CI, `nogo` doesn't end up running on it. We should be building `dev` in CI anyway since it's an important binary.
