### ISSUE TITLE
roachtest / ci: links rendering incorrectly

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#76382]
**Describe the problem**

The links for certain failed nightly roachtests do not appear to be rendering correctly. Specifically, the `https://teamcity.cockroachdb.com/` prefix of the URL is being dropped, leaving an incomplete URL, e.g. `viewlog.html/foo/bar`, which does not resolve.

**To Reproduce**

See [here](https://github.com/cockroachdb/pebble/issues/1499#issuecomment-1033399736) and [here](https://github.com/cockroachdb/pebble/issues/1499#issuecomment-1034587796) for an example (the `failed` and `artifacts` links, specifically).

**Expected behavior**

The link should take you over to the appropriate TeamCity page.

Epic CRDB-8306

Jira issue: CRDB-13097

**Comment by rickystewart** [comment]
Nick -- I've been looking and can't find an explanation for this. I have #76450 to add logging so we can be sure that `TC_SERVER_URL` is set.

**Comment by nicktrav** [comment]
Goofy! Thanks for looking into it. Hopefully the logging helps!

**Comment by rickystewart** [comment]
Indeed, the logging confirms that `TC_SERVER_URL` is set and to the correct value: 
 https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_Pebble_Metamorphic/4368458?buildTab=log&focusLine=4636&linesState=4514

My understanding of this is that we use `github-post` for posting issues, which internally relies on `github.com/cockroachedb/cockroach/pkg/cmd/internal/issues` and checks for `TC_SERVER_URL` in pkg/cmd/internal/issues/issues.go. Does that all seem accurate, or am I missing something here?

**Comment by nicktrav** [comment]
>  Does that all seem accurate, or am I missing something here?

Yeah, from what I can tell, that looks accurate.

Backtracking from what is actually displayed:
- we get an (incorrect) URL of the form `https://viewlog.html/?buildId=4343918&tab=buildLog`
- that URL just has a null hostname, the rest is correct
- an empty hostname implies that it's being set to `""` [here](https://github.com/cockroachdb/cockroach/blob/24d886cd713583fd6a4154e48bdbacad9eeb31f9/pkg/cmd/internal/issues/issues.go#L183)
- however, when we pull from that environment variable, if it was `""`, then we should be replacing it with the default value of `https://server-url-not-found-in-env.com`, [here](https://github.com/cockroachdb/cockroach/blob/24d886cd713583fd6a4154e48bdbacad9eeb31f9/pkg/cmd/internal/issues/issues.go#L194)

I'm confused as to how that's even happening.

**Comment by rickystewart** [comment]
Me too, I don't have an inkling as to what could be going wrong here. 🤔 I agree that even if `TC_SERVER_URL` is not present in the environment (or empty), it should be overridden with `https://server-url-not-found-in-env.com`.

**Comment by nicktrav** [comment]
Maybe we can keep this around until the next time that test fails and posts. If it's working, sweet. If not, we'll dig in.

**Comment by rickystewart** [comment]
SGTM, just ping me whenever you see the next wrongly formatted metamorphic issue.
