### ISSUE TITLE
kvserver: flake in TestLargeUnsplittableRangeReplicate

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#76389]
**Describe the problem**
Placeholder to fill in more details when the build finishes and I can get artifacts. Failed a bors run. 

```
    replicate_queue_test.go:1102: condition failed to evaluate within 45s: not up-replicated yet
        goroutine 1413151 [running]:
        runtime/debug.Stack()
          /usr/local/go/src/runtime/debug/stack.go:24 +0x65
        github.com/cockroachdb/cockroach/pkg/testutils.SucceedsWithin({0x54ec918, 0xc004904000}, 0x0, 0x3bc1a00)
          /go/src/github.com/cockroachdb/cockroach/pkg/testutils/soon.go:60 +0x5f
        github.com/cockroachdb/cockroach/pkg/testutils.SucceedsSoon({0x54ec918, 0xc004904000}, 0x0)
          /go/src/github.com/cockroachdb/cockroach/pkg/testutils/soon.go:41 +0x4a
        github.com/cockroachdb/cockroach/pkg/kv/kvserver_test.TestLargeUnsplittableRangeReplicate(0xc004904000)
          /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replicate_queue_test.go:1102 +0x7ef
        testing.tRunner(0xc004904000, 0x44bbf38)
          /usr/local/go/src/testing/testing.go:1259 +0x102
        created by testing.(*T).Run
          /usr/local/go/src/testing/testing.go:1306 +0x35a
```

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/4348893?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true&logFilter=debug

Jira issue: CRDB-13101

**Comment by andreimatei** [comment]
Also failed for me [in this build](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/4349501?buildTab=overview&showRootCauses=true&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true#%2Ftest)

**Comment by ajwerner** [comment]
And [this one](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_GitHubCiOptional/4349687?showRootCauses=false&expandBuildChangesSection=true)

**Comment by RaduBerinde** [comment]
https://teamcity.cockroachdb.com/viewLog.html?buildId=4359887&buildTypeId=Cockroach_UnitTests
