### ISSUE TITLE
cli: TestDockerCLI flake [node incorrectly reports as draining]

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#76391]
**Describe the problem**

As far as I can tell, this seems like a legitimate failure.

```
root@127.155.15.33:26257/movr> \demo shutdown 6
node is draining... remaining: 7
node is draining... remaining: 0 (complete)
node 6 has been shutdown
select node_id, draining, decommissioning, membership from crdb_internal.gossip_liveness ORDER BY node_id;
root@127.155.15.33:26257/movr> select node_id, draining, decommissioning, member ship from crdb_internal.gossip_liveness ORDER BY node_id;
  node_id | draining | decommissioning |   membership
----------+----------+-----------------+-----------------
        1 |  false   |      false      | active
        2 |  false   |      false      | active
        3 |  false   |      false      | active
        4 |  false   |      true       | decommissioned
        5 |  false   |      false      | active
        6 |  false   |      false      | active
(6 rows)


Time: 1ms total (execution 1ms / network 0ms)

root@127.155.15.33:26257/movr> 
.220210 18:42:51.670699522 EXPECT TEST: TIMEOUT WAITING FOR "6 |   true   |      false      | active"
```

Artifacts: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_Tests_Acceptance/4349122?buildTab=overview&showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true#%2Facceptance%2FTestDockerCLI;%2Fbazel-testlogs;%2Facceptance%2FTestDockerRuby%2FrunMode%3Ddocker%2301

Jira issue: CRDB-13102

**Comment by rickystewart** [comment]
I just saw a different TestDockerCLI test flake in non-Bazel CI: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/4350140?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true 

I think the acceptance tests are just janky today.

**Comment by knz** [comment]
ricky, test_demo_partitioning has known issues due to the fact it pulls a license, so I wouldn't be concerned too much.

However, the one that andrew found above should be deterministic, and could be related by recent changes from @cameronnunez

**Comment by cameronnunez** [comment]
hmm looking into it

**Comment by ajwerner** [comment]
https://github.com/cockroachdb/cockroach/pull/76489#issuecomment-1038765187

**Comment by rafiss** [comment]
seems to be happening still in https://github.com/cockroachdb/cockroach/issues/76448

and i ran into it in https://github.com/cockroachdb/cockroach/pull/77519#issuecomment-1063188501

**Comment by rafiss** [comment]
I'm tagging this as a GA-blocker out of an abundance of caution, just to make sure it gets investigated. The failure is new in 22.1.. It's still happening: https://github.com/cockroachdb/cockroach/issues/77886#issuecomment-1074744997

**Comment by ajwerner** [comment]
This is a skipped test

**Comment by AlexTalks** [comment]
Thus far I haven't been able to reproduce the issue on `release-22.1` or `master` using `make`, despite 1mln+ runs (and ensuring that the tests are not skipped).  I have been having some issues with running with Bazel, though it may be more configuration - continuing to investigate.

**Comment by rafiss** [comment]
Note: to "unskip" this, these lines need to be uncommented: https://github.com/cockroachdb/cockroach/blob/3bb32b8d3c27744cf097cd59db8269df57399fe6/pkg/cli/interactive_tests/test_demo_node_cmds.tcl#L70-L94
