### ISSUE TITLE
sql: support inbound FKs on TTL tables

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#76407]
Currently, TTL tables do not support FKs due to complexities around handling cascading FK effects.

This is a tracking issue for telemetry and use cases.

Jira issue: CRDB-13107

Epic CRDB-26101

**Comment by vy-ton** [comment]
@otan What complexities with `ON UPDATE` would need to be addressed to support this use case?

**Comment by otan** [comment]
it's not the ON UPDATE that's annoying; it's the "strict filtering". examples of the corner cases:

* A ON DELETE CASCADE referencing a TTL table: that means subsequent deletes from the TTL delete cascades onto the referencing table.
* A ON DELETE RESTRICT from a TTL table to a different table is complex because that means when a row expires the TTL, the restriction on the different table should not apply and is free to delete.

i'm hesitant to allow it until we have strict filtering sorted out including the FK story.

**Comment by 0xmohit** [comment]
Any plans on supporting this?  This poses considerable restrictions on being able to make use of TTL tables.

**Comment by ecwall** [comment]
> Any plans on supporting this? This poses considerable restrictions on being able to make use of TTL tables.

@0xmohit we are looking at supporting all outbound foreign keys and inbound foreign keys with `ON DELETE CASCADE` to improve usability of TTL tables.

**Comment by ecwall** [comment]
Created https://github.com/cockroachdb/cockroach/issues/101372 for better handling of inbound FK with ON DELETE RESTRICT.
