### ISSUE TITLE
[Question] About: C/C++ connector and benchmarks

### ISSUE THREAD

**Issue by dedok** [cockroachdb/cockroach#7641]
Hi,

Where are have any stable C or C++ connectors? Or I need use go?
I wish make my own benchmark with my data set. I need do tuning of cockroachdb? Or I can use out of box?

**Comment by knz** [comment]
Hi @dedok! Thanks for your interest in CockroachDB!

You can use most existing PostgreSQL database connectors for C or C++, for example libpq. We have some information about how to implement clients on our documentation site: https://www.cockroachlabs.com/docs/build-a-test-app.html

CockroachDB should already work out of the box. Of course this is still in Beta stage so some bugs and inefficiencies are still expected. Feel free to report them as needed. 

Also please use our community forum at https://forum.cockroachlabs.com/ for open-ended questions, including questions about tuning. We will gladly answer your questions there. We prefer to use the Github issue tracker for software development and bug reports.

For now I will close this issue, as it does not directly report a problem in the product. If you have any additional question or comment, please come and ask on Gitter! ( https://gitter.im/cockroachdb/cockroach ) We will be glad to help.

All the best

**Comment by dedok** [comment]
@knz thanks!
