### ISSUE TITLE
new users in 21.2.5 can't use show tables anymore when only select permissions are granted

### ISSUE THREAD

**Issue by wzrdtales** [cockroachdb/cockroach#76422]
New users that have been created recently on the version 21.2.5 can't see any tables from show tables anymore. The affected users have only select privileges to the tables inside the database. Old users however can still see them.

**Comment by wzrdtales** [comment]
turns out it needs the connect privilege, the docs should be updated with that info

**Comment by yuzefovich** [comment]
@wzrdtales thanks for filing this issue and the PR to fix the docs! Since this appears to be docs-only problem, I'll go ahead and close the issue here, but consider opening another issue in the docs repo (https://github.com/cockroachdb/docs/issues).
