### ISSUE TITLE
deps: evaluate a possible upgrade to the newest sentry-go

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#76439]
Currently CockroachDb files issues to Sentry.io using an outdated version of sentry-go (SDK 0.6.1).

The filing of issues happens automatically via the [errors library](https://github.com/cockroachdb/errors).
This week, an external contributor volunteered to upgrade the sentry-go dependency in `errors`: https://github.com/cockroachdb/errors/pull/92

Before we accept this PR, we need to **qualify this inside CockroachDB**:
1. create a build of CockroachDB with the proposed patch in `errors`.
2. point the build to our dev instance in Sentry.io
3. trigger a reportable error
4. check in the Sentry UI that the error report is 1) actually filed and 2) that the metadata is preserved just as well as in the previous SDK version.

**Comment by rail** [comment]
I took a look at this using Bazel - it's easier to pin things with it. This my current diff:
https://gist.githubusercontent.com/rail/d347a796d7ecea31bda94587f2e453b8/raw

I ran `go get github.com/getsentry/sentry-go@v0.12.0`, then replaced the references to our fork in the go files, and ran `./dev generate bazel`. Then I tweaked `DEPS.bazel` and pointed the errors module to the fork from the PR.

I generated the binary using `./dev buld short`.

To trigger a crash I rand the following:
```
export COCKROACH_CRASH_REPORTS=https://ignored@errors.cockroachdb.com/api/sentrydev/v2/1111
echo "select crdb_internal.force_panic('testing');" | ./cockroach demo --insecure
```

The Sentry issue is here: https://sentry.io/organizations/cockroach-labs/issues/3012238368/?project=161792

@knz can you take a look and see if there is something that looks wrong? 

At least the setry-go SDK version looks sane in the issue: 
<img width="367" alt="image" src="https://user-images.githubusercontent.com/42865/153801977-e57773bb-adc7-4366-9f81-ed1157819183.png">

**Comment by knz** [comment]
Yes this looks good. Amazing, thanks @rail
