### ISSUE TITLE
storage: test that the first range is quickly gossiped after being rebalanced

### ISSUE THREAD

**Issue by paperstreet** [cockroachdb/cockroach#7644]
> It should be possible to set up a three-node cluster, wait for initial
replication of the first range, and then to disable the replication queue
and to downreplicate so that the first range leader disappears.
Subsequently we should be able to verify that the first range gossip
updates accordingly in a short amount of time (and once we have lease
transfers, we can check more).

It was previously waiting for the next `sentinelGossipInterval` tick. See https://github.com/cockroachdb/cockroach/issues/7297#issuecomment-230588822 for the full context.

This issue is a placeholder to reference in a commit that fixes the issue but lacks a test for the fix. The test is waiting on some upcoming testing infrastructure.

**Comment by tamird** [comment]
Just a best-practices reminder: please inline this issue into the commit - we want our commits to be freestanding as much as possible, though referencing the issue is still helpful.

**Comment by paperstreet** [comment]
Meaning inline the description of what test should be written next to the link to this issue?

**Comment by tamird** [comment]
I'd probably phrase it as a description of the issue being fixed and mention that the test is to follow, rather than describing the test.

**Comment by petermattis** [comment]
We also need to test that the first range isn't being gossiped excessively. See #7808.

**Comment by petermattis** [comment]
Scenarios to test:
* First range gossip where the range lease holder remains a replica:
  * Lease is still valid.
  * Lease has expired. Tricky to test this as the lease needs to be valid when the change replicas begins.
* First range gossip where the range lease holder has been removed:
  * Lease is still valid.
  * Lease has expired.
