### ISSUE TITLE
builtins: ulid_to_uuid shouldn't return internal errors when given non-ulids

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#76454]
Currently, the `ulid_to_uuid` builtin passes raw parsing errors back to the user, which get turned into internal errors. These should be returned with parsing error codes of some sort.

**Comment by rafiss** [comment]
Is this an example of a raw parsing error?
```
root@:26257/defaultdb> select ulid_to_uuid('cat');
ERROR: ulid_to_uuid(): ulid: bad data size when unmarshaling
```
