### ISSUE TITLE
storage: temporary block on logging output causes logic errors to appear

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#7646]
Running on master.
1. Please describe the issue you observed:
- What did you do?

Start db server with -logtostderr true; then in a separate terminal start issuing schema changes in a loop (create database, create table, drop database). Then back into db terminal, press Ctrl+S (terminal XOFF, which blocks the tty stream that logging output is emitted to) so as to gain time to read the messages. Then Ctrl+Q to resume message printing.
- What did you expect to see?

Messages would stop scrolling upon Ctrl+S and then start scrolling again upon Ctrl+Q, with no influence on DB behavior whatsoever.
- What did you see instead?

In most cases shortly after pressing Ctrl+S to suspend logging output, the _client_ connection was suspended too (until Ctrl+Q was pressed on the server terminal).

Moreover, upon Ctrl+Q the delayed messages reveal that the database encountered timeout situations during the time the logging output was suspended. 

On some occasions:

```
W160706 15:05:24.479043 storage/intent_resolver.go:296  [node=1,store=1,range=1] failed to resolve intents: context deadline exceeded
W160706 15:05:24.484510 storage/intent_resolver.go:343  could not GC completed transaction: range 2530: replica node_id:1 store_id:1 replica_id:1  not leader; leader is <nil>       
```

On other occasions:

```
E160706 15:09:25.830618 storage/replica.go:2478  [node=1,store=1,range=41] could not load SystemConfig span: must retry later due to intent on SystemConfigSpan
```

On other occasions:

```
W160706 15:09:41.522904 storage/replica.go:903  context deadline exceeded while in command queue: ResolveIntent [/Meta2/Max,/Min)
W160706 15:09:41.530284 storage/intent_resolver.go:296  [node=1,store=1,range=1] failed to resolve intents: context deadline exceeded
```

On other occasions:

```
E160706 15:11:10.702449 storage/replica.go:2478  [node=1,store=1,range=41] could not load SystemConfig span: must retry later due to intent on SystemConfigSpan
W160706 15:11:10.703483 storage/intent_resolver.go:296  [node=1,store=1,range=1] failed to resolve intents: context deadline exceeded
I160706 15:11:10.705456 storage/replica_command.go:2127  initiating a split of range=2702 [/Table/2595-/Max) at key /Table/2596
E160706 15:11:10.709948 internal/client/txn.go:364  failure aborting transaction: writing transaction timed out or ran on multiple coordinators; abort caused by: does not exist
```

On other occasions:

```
W160706 15:16:58.756737 storage/intent_resolver.go:300  [node=1,store=1,range=41] failed to push during intent resolution: failed to push "sql/executor.go:458 sql txn implicit" id=170ab8b9 key=/System/"desc-idgen" rw=true pri=0.00242861 
iso=SERIALIZABLE stat=PENDING epo=0 ts=1467818218.695306847,0 orig=1467818218.695306847,0 max=1467818218.695306847,0 wto=false rop=false
```

Probably the logging stream should be non-blocking **if it is a terminal**, with messages silently dropped if the output buffer is full.

**Comment by tschottdorf** [comment]
Linking in https://github.com/cockroachdb/cockroach/issues/1779

On Wed, Jul 6, 2016 at 11:13 AM kena <notifications@github.com> wrote:

> Running on master.
>
>    1.
>
>    Please describe the issue you observed:
>
>
>    - What did you do?
>
> Start db server with -logtostderr true; then in a separate terminal start
> issuing schema changes in a loop (create database, create table, drop
> database). Then back into db terminal, press Ctrl+S (terminal XOFF, which
> blocks the tty stream that logging output is emitted to) so as to gain time
> to read the messages. Then Ctrl+Q to resume message printing.
>
>    - What did you expect to see?
>
> Messages would stop scrolling upon Ctrl+S and then start scrolling again
> upon Ctrl+Q, with no influence on DB behavior whatsoever.
>
>    - What did you see instead?
>
> In most cases shortly after pressing Ctrl+S to suspend logging output, the
> *client* connection was suspended too (until Ctrl+Q was pressed on the
> server terminal).
>
> Moreover, upon Ctrl+Q the delayed messages reveal that the database
> encountered timeout situations during the time the logging output was
> suspended.
>
> On some occasions:
>
> W160706 15:05:24.479043 storage/intent_resolver.go:296  [node=1,store=1,range=1] failed to resolve intents: context deadline exceeded
> W160706 15:05:24.484510 storage/intent_resolver.go:343  could not GC completed transaction: range 2530: replica node_id:1 store_id:1 replica_id:1  not leader; leader is <nil>
>
> On other occasions:
>
> E160706 15:09:25.830618 storage/replica.go:2478  [node=1,store=1,range=41] could not load SystemConfig span: must retry later due to intent on SystemConfigSpan
>
> On other occasions:
>
> W160706 15:09:41.522904 storage/replica.go:903  context deadline exceeded while in command queue: ResolveIntent [/Meta2/Max,/Min)
> W160706 15:09:41.530284 storage/intent_resolver.go:296  [node=1,store=1,range=1] failed to resolve intents: context deadline exceeded
>
> On other occasions:
>
> E160706 15:11:10.702449 storage/replica.go:2478  [node=1,store=1,range=41] could not load SystemConfig span: must retry later due to intent on SystemConfigSpan
> W160706 15:11:10.703483 storage/intent_resolver.go:296  [node=1,store=1,range=1] failed to resolve intents: context deadline exceeded
> I160706 15:11:10.705456 storage/replica_command.go:2127  initiating a split of range=2702 [/Table/2595-/Max) at key /Table/2596
> E160706 15:11:10.709948 internal/client/txn.go:364  failure aborting transaction: writing transaction timed out or ran on multiple coordinators; abort caused by: does not exist
>
> Probably the logging stream should be non-blocking *if it is a terminal*,
> with messages silently dropped if the output buffer is full.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/7646>, or mute the thread
> <https://github.com/notifications/unsubscribe/AE135K6IIWkzw--FHNmUha8VZbJC-1kuks5qS8YogaJpZM4JGL5f>
> .
>
-- 

-- Tobias

**Comment by knz** [comment]
Reported by user in #7906: if the logging output to a disk is blocked due to high I/O on that disk, the db stalls even if the data is on other disks.

**Comment by tschottdorf** [comment]
Should likely be addressed during #1779

**Comment by tschottdorf** [comment]
Folding into #7882.

**Comment by tbg** [comment]
Un-folding from #7882 (which is likely closing very soon since I'm about to push WIP to do so).

@knz this is about blocking stderr/stdout, right? I was trying to look into that as well but I'm not sure how it works on the technical side. Can I determine that os.Stdout would block in a platform-independent way? What's the easiest way to simulate this kind of blocking?
