### ISSUE TITLE
how to use generate-spatial-ref-sys?

### ISSUE THREAD

**Issue by suzixin** [cockroachdb/cockroach#76488]
**Is your feature request related to a problem? Please describe.**
go run ./pkg/cmd/generate-spatial-ref-sys --src='/tmp/srids.csv' --dest='./pkg/geo/geoprojbase/data/proj.json.gz'
I want to know how to get a sample src data like /tmp/srids.csv.

**Describe the solution you'd like**
Please give me a sample file as tmp/srids.csv.

**Comment by otan** [comment]
run `copy spatial_ref_sys to '/tmp/srids.csv' DELIMITER ';' CSV HEADER;` on postgres with postgis installed
