### ISSUE TITLE
tabledesc: validate secondary index descriptor version never be lower than `PrimaryIndexWithStoredColumnsVersion`

### ISSUE THREAD

**Issue by chengxiong-ruan** [cockroachdb/cockroach#76536]
With #76465 we unify version number of primary index and secondary index. From 22.1 we should never see a secondary index with version lower than `PrimaryIndexWithStoredColumnsVersion`. We should add validation to make sure that does not happen.
Also consider adding `Deprecated` prefix to older older index version symbols.

Jira issue: CRDB-13173

**Comment by ajwerner** [comment]
We should do this, and it's easy.

**Comment by ajwerner** [comment]
> From 22.1 we should never see a secondary index with version lower than PrimaryIndexWithStoredColumnsVersion

This is not true. The reason it's not true is that in general these index version referred to versions of the data. What is true is that we should not see any indexes with *some* of the old versions because we auto-upgraded those.

**Comment by ajwerner** [comment]
I don't think this is a release blocker

**Comment by postamar** [comment]
This is not so straightforward. For a start, promotion is not always possible. Some indexes out there have malformed descriptors in that they have the same column ID show up in the key column IDs _and_ the store column IDs or the suffix column IDs. Currently we just give up on these. What we really need is a migration (during cluster upgrades, but also post-restore via `RunRestoreChanges`).
Furthermore considering we have to go to this trouble we should also fix `Version` as per https://github.com/cockroachdb/cockroach/issues/78695.
As a result I'm closing this issue in favour of that one.
