### ISSUE TITLE
Improve Jobs console page performance and stability

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#76531]
We should reevaluate the console job pages APIs and determine if there are any optimization opportunities we can make to the page, queries, or crdb_internal.

Jira issue: CRDB-13171

**Comment by shermanCRL** [comment]
It’s likely that the console page is reflecting general jobs contention: https://github.com/cockroachdb/cockroach/issues/73133

From UI perspective, we might have a better timeout or error message on this page. For the underlying problem to be fixed, follow the above.
