### ISSUE TITLE
storage: TestStoreRangeRebalance fails

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#7653]
`expected 0 normal snapshots, but found 1`

https://circleci.com/gh/tschottdorf/cockroach/2423

**Comment by petermattis** [comment]
Yep, I'm seeing this locally too. "It worked yesterday".

**Comment by petermattis** [comment]
The underlying problem is still there, I just disabled the part of the test which is failing.

**Comment by tamird** [comment]
Looks like the disabled code was re-enabled in ee8bbc2e9660a2c600abb002d9f09fc9559da11f.
