### ISSUE TITLE
insert with INVERTED INDEX fail when srid = 2182

### ISSUE THREAD

**Issue by suzixin** [cockroachdb/cockroach#76579]
**Is your feature request related to a problem? Please describe.**
```sql
CREATE TABLE geo_table(
  k int primary key,
  geom geometry,
  INVERTED INDEX geom_index(geom)
);
INSERT INTO geo_table VALUES
  (1, 'SRID=2182;POINT(400001 4000001)');
```

report error:
```
ERROR: could not parse geometry: projection for SRID 2182 does not exist
```

**Describe the solution you'd like**
Insert geom data with sird = 2182 (Related auth_name is not EPSG ) is enable when using INVERTED INDEX.

**Describe alternatives you've considered**
/

**Additional context**
/

Jira issue: CRDB-13182

**Comment by otan** [comment]
SRID 2182 is not defined in `spatial_ref_sys`; we don't support adding a custom SRID right now unfortunately.

**Comment by otan** [comment]
(see also: https://github.com/cockroachdb/cockroach/issues/77564)
