### ISSUE TITLE
changefeed: Enable multi-pod tenant changefeeds

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#76597]
https://github.com/cockroachdb/cockroach/pull/76566 is adding support for multi-pod tenant bulk ops.
Currently, multi-pod changefeeds are disabled (i.e. not distributed).

We should enable multipod changefeeds once above pr checked in.  It would be nice to extend
tenant specific tests to also simulate multiple pods so that we get test coverage.

Jira issue: CRDB-13187

Epic CRDB-11817

**Comment by samiskin** [comment]
Resolved by https://github.com/cockroachdb/cockroach/pull/78965
