### ISSUE TITLE
Run unit test in inverted_expr_evaluator_test.go

### ISSUE THREAD

**Issue by suzixin** [cockroachdb/cockroach#76646]
**Is your feature request related to a problem? Please describe.**
How can I run test file only such as inverted_expr_evaluator_test.go
I only found the command as follow
```
"make test" "Run all unit tests." \
		"make test PKG=./pkg/sql" "Run all unit tests in the ./pkg/sql package" \
		"make test PKG=./pkg/sql/parser TESTS=TestParse" "Run the TestParse test in the ./pkg/sql/parser package." \
		"make bench PKG=./pkg/sql/parser BENCHES=BenchmarkParse" "Run the BenchmarkParse benchmark in the ./pkg/sql/parser package." \
		"make testlogic" "Run all base, opt exec builder, and CCL logic tests." \
		"make testccllogic" "Run all CCL SQL logic tests." \
		"make testoptlogic" "Run all opt exec builder SQL logic tests." \
		"make testbaselogic" "Run all the OSS SQL logic tests." \
		"make testlogic FILES='prepare|fk'" "Run the logic tests in the files named prepare and fk (the full path is not required)." \
		"make testlogic FILES=fk SUBTESTS='20042|20045'" "Run the logic tests within subtests 20042 and 20045 in the file named fk." \
		"make testlogic TESTCONFIG=local" "Run the logic tests for the cluster configuration 'local'." \
		"make fuzz" "Run all fuzz tests for 12m each (or whatever the default TESTTIMEOUT is)." \
		"make fuzz PKG=./pkg/sql/... TESTTIMEOUT=1m" "Run all fuzz tests under the sql directory for 1m each." \
		"make fuzz PKG=./pkg/sql/sem/tree TESTS=Decimal TESTTIMEOUT=1m" "Run the Decimal fuzz tests in the tree directory for 1m."
```

**Describe the solution you'd like**
I can run and debug the specific test file.

**Comment by yuzefovich** [comment]
It's not possible to run a particular test file if it contains multiple tests. Since `inverted_expr_evaluator_test.go` is in `rowexec` package, then you could do `make test PKG=./pkg/sql/rowexec` to run all tests in the whole package, including the ones in the file of interest. You can, however, run a particular test from that file with something like `make test PKG=./pkg/sql/rowexec TESTS=TestInvertedExpressionEvaluator`.

**Comment by suzixin** [comment]
Thanks for reply~
I have another question, how can I get a executable file of testFile, and debug it?

**Comment by yuzefovich** [comment]
I'm not sure what your question is asking. You might wanna look into `go test`.
