### ISSUE TITLE
sql: investigate split and scattering the temporary index in mvcc index backfiller

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#76686]
Currently, sharded indexes are automatically split and scattered before being backfilled.  We may want to do the same for the related temporary index in the index backfiller.

Jira issue: CRDB-13231

Epic CRDB-7363

**Comment by postamar** [comment]
@stevendanna @chengxiong-ruan can you epic-link this?

**Comment by chengxiong-ruan** [comment]
@postamar done!
