### ISSUE TITLE
sql: if exists clause doesn't prevent exceptions

### ISSUE THREAD

**Issue by LorenzoBoccaccia** [cockroachdb/cockroach#7671]
- What did you do?
working at an incremental script because database versioning is annoying, so defined tables as

CREATE DATABASE IF NOT EXISTS SMTNG;

CREATE TABLE IF NOT EXISTS SOMETHING (
 ID SERIAL PRIMARY KEY
);

ALTER TABLE SOMETHING  ADD COLUMN IF NOT EXISTS OWNER_ID INT;
ALTER TABLE SOMETHING ADD COLUMN IF NOT EXISTS MODEL_ID INT;
ALTER TABLE SOMETHING ADD COLUMN IF NOT EXISTS NAME STRING;

- What did you expect to see?

objects created without errors and complaints

- What did you see instead?

org.postgresql.util.PSQLException: ERROR: only root is allowed to create databases
but database do exists

org.postgresql.util.PSQLException: ERROR: duplicate column name: "OWNER_ID"
yes that's why I added if not exists to the script

apps then works fine but these logs are polluting real issues with creation scripts

**Comment by dt** [comment]
The `only root is allowed to create databases` error is expected I believe: a user other than `root` is not allowed to issue a `CREATE DATABASE` command, even fi it contains qualifications like `IF NOT EXISTS` that mean it might not have an effect at runtime.

I have a fix for the `ADD COLUMN` issue though that I'll push shortly.
