### ISSUE TITLE
roachperf: high core-count regression around February 16th

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#76738]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:
<img width="1430" alt="Screen Shot 2022-02-17 at 10 54 44 AM" src="https://user-images.githubusercontent.com/1839234/154519262-d324e342-5869-4090-ac80-47a71e0b1686.png">
https://roachperf.crdb.dev/?filter=&view=kv0%2Fenc%3Dfalse%2Fnodes%3D3%2Fcpu%3D96&tab=aws
<img width="1430" alt="Screen Shot 2022-02-17 at 10 55 27 AM" src="https://user-images.githubusercontent.com/1839234/154519380-f58f31b2-e31d-486c-b573-8c314c73ef95.png">
https://roachperf.crdb.dev/?filter=&view=kv95%2Fenc%3Dfalse%2Fnodes%3D3%2Fcpu%3D32%2Fseq&tab=aws

The same day we see marked improvements in the lower core-count workloads. Presumably this is all due to https://github.com/cockroachdb/cockroach/pull/76350, but we should bisect and profile to understand.

cc @Azhng 😓 

Jira issue: CRDB-13255

**Comment by ajwerner** [comment]
Perhaps this was my advice on how many shards to use.

**Comment by Azhng** [comment]
Hmmm is there a wiki on how to run the bisection ?

**Comment by Azhng** [comment]
Hmm the new `fifoCache` is for sure faster than the `cache.UnorderedCache`. I have a feeling that this might be because we drop the batch size from 1024 to 168. I'll play around with this when I get time.

**Comment by tbg** [comment]
Can we treat this with some urgency? A 20% regression has ripple effects across the org, for example @nvanbenschoten was trying to validate a customer workload yesterday (on large machines) and this regression significantly shifts the baseline.

**Comment by Azhng** [comment]
Hi @tbg, this issue is high on my ltodo list to work on. Meanwhile, you can disable the offending component via 
`SET CLUSTER SETTING sql.contention.txn_id_cache.max_size = 0` if you have urgent validation to do.

**Comment by erikgrinaker** [comment]
Should we consider disabling this setting by default until we get to the bottom of it?

**Comment by erikgrinaker** [comment]
@Azhng Thoughts on disabling this? It can mask other performance issues, and as we're moving into stability we'll need to start addressing them across the board.

**Comment by tbg** [comment]
The regression should now be "fixed" by defaulting the cluster setting to zero (https://github.com/cockroachdb/cockroach/pull/76973#event-6132013984). We'll need to add an annotation to roachperf.

**Comment by Azhng** [comment]
The heap profile here is pointing the finger at the eviction list in the FIFO store. Somehow that's creating a lot of objects on the heap. Hmm I was under the impression that using the `sync.Pool` was able to reduce those allocations? 

<img width="1484" alt="Screen Shot 2022-02-28 at 23 15 44" src="https://user-images.githubusercontent.com/9267198/156103854-16d190ec-14bb-4a2e-99f0-7e19cc70fc1e.png">

Hmm though this doesn't quite explain how running 3 copies of txnIDCache in 3 different goroutines was able to improve the situation. 🤔  

Profile: 

[pprof.cockroach.alloc_objects.alloc_space.inuse_objects.inuse_space.004.pb.gz](https://github.com/cockroachdb/cockroach/files/8158706/pprof.cockroach.alloc_objects.alloc_space.inuse_objects.inuse_space.004.pb.gz)

**Comment by ajwerner** [comment]
It seems to me like you're not accounting for the memory properly here. Namely, you need to account for the blocks themselves which are in use
