### ISSUE TITLE
sql: sql stats flush logs produces nonsensical information

### ISSUE THREAD

**Issue by Azhng** [cockroachdb/cockroach#76747]
**Describe the problem**

```
I220217 17:49:52.876239 3141 sql/sqlstats/persistedsqlstats/pkg/sql/sqlstats/persistedsqlstats/flush.go:32 ⋮ [n1] 565  flushing 1905 stmt/txn fingerprints (2467840 bytes) after 2562047h47m16.854775807s
```

The logs produced by sql stats flush operation contains a duration since the last flush. However, in this case, the value in the log message indicates that last flush happened roughly 290 years ago.

**Additional context**

This is probably due to the `lastFlush` timestamp not initialized until the first flush is completed. 

Jira issue: CRDB-13259

**Comment by Azhng** [comment]
Culprit: https://github.com/cockroachdb/cockroach/blob/e7b0f3ab403eecc74d2ace90487cd63073af79b5/pkg/sql/sqlstats/persistedsqlstats/flush.go#L67

**Comment by knz** [comment]
@j82w is this still relevant?
