### ISSUE TITLE
sql: do not reuse shard column if it contains a non-immutable expression

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#76760]
In version 21.1 and prior, the system would synthesize a computed column for a hash-sharded index on a TIMESTAMPTZ column with an expression containing a `TIMESTAMPTZ::STRING` cast:

```
defaultdb> SELECT version();
                                        version
----------------------------------------------------------------------------------------
  CockroachDB CCL v20.1.8 (x86_64-apple-darwin14, built 2020/10/21 15:39:38, go1.13.9)
(1 row)

defaultdb> SET experimental_enable_hash_sharded_indexes=on;
SET

defaultdb> CREATE TABLE t (tz TIMESTAMPTZ, INDEX (tz) USING HASH WITH BUCKET_COUNT=8);
CREATE TABLE

defaultdb> SELECT generation_expression FROM [SHOW COLUMNS FROM t] WHERE column_name = 'crdb_internal_tz_shard_8';
                       generation_expression
-------------------------------------------------------------------
  mod(fnv32(COALESCE(CAST(tz AS STRING), '':::STRING)), 8:::INT8)
(1 row)
```

In version 21.2 and later, `crdb_internal.datum_to_bytes(TIMESTAMPTZ)` is used instead of the `TIMESTAMPTZ::STRING` cast, which is non-immutable, in synthesized shard column expressions because the latter can cause index corruption and incorrect results.

As a result, the following sequence of events can occur:

1. On version 21.1 or earlier, user creates a hash-sharded index. The synthesized shard column has an expression with a `TIMESTAMPTZ::STRING` cast.
2. User upgrades cluster to 21.2 or later. The expression in the synthesized shard column remains unchanged.
3. User runs `SHOW CREATE TABLE` and the output include the synthesized shard column with the now-invalid expression.
4. User tries to run the output of `SHOW CREATE TABLE` in a cluster of the same version. This fails with the error `ERROR: timestamptz::string: context-dependent operators are not allowed in computed column`.

This error is not ideal. There are currently two workarounds:

1. Rewrite the synthesized shard column expression given in the output of `SHOW CREATE TABLE` before running the SQL. `mod(fnv32(COALESCE(CAST(tz AS STRING), '':::STRING)), 8:::INT8)` should become `(mod(fnv32(crdb_internal
.datums_to_bytes(tz)), 8:::INT8))`.
2. Remove the synthesized shard column and the column's CHECK expression given in the output of `SHOW CREATE TABLE` before running the SQL. The system will automatically recreate a shard column with a correct expression.

To provide a better user experience, could we detect invalid shard columns created in older CRDB versions, and simply ignore them, then let the system create a correct shard column, like in workaround (2)?

Jira issue: CRDB-13262

**Comment by ajwerner** [comment]
I don't think this is a huge deal. It was an experimental feature back then, there's a manual user step here, and there's a really easy workaround, which is to have the user remove the check expression from the `CREATE TABLE` statement

**Comment by mgartner** [comment]
> remove the check expression from the CREATE TABLE statement

I forgot to mention that the CHECK expression must be removed in workaround (2). Thanks for pointing this out.

I agree this case is likely rare and complicating the logic to handle it when the workaround is trivial may not be desired.

**Comment by mgartner** [comment]
I originally got the versions wrong. The TIMESTAMPTZ::STRING cast was used in shard column expressions up until 21.2. The description has been fixed.

**Comment by postamar** [comment]
Closing because I don't think we're going to do this. Feel free to reopen if we need to reevaluate.
