### ISSUE TITLE
ui: Table-level metrics

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#7682]
This issue is to track work required to record per-table metrics.  Currently, our metrics are focused entirely on stores and nodes, which can be aggregated into a cluster metrics; however, this does not give adequate information on the usage for individual Tables in the system. To support that, we need to make a number of _per-table_ metrics available in our admin API, both as immediate values _and_ as time series.

Metrics suggested:
- [x] Table Size in Bytes (both fully-replicated size _and_ unique bytes)
- [ ] Read/Write counts
- [ ] Bandwidth (bytes in/out)
- [x] Table Range Count
- [ ] Table Row Count

**Comment by tschottdorf** [comment]
https://github.com/cockroachdb/cockroach/issues/7611 could be useful (leaseholder-collected mostly accurate replicated stats)

**Comment by maxlang** [comment]
@mrtracy Are any of these other metrics still planned?

**Comment by mrtracy** [comment]
Well, they haven't been cancelled, but they are not in the Q3 timeframe. Then again, this is listed as a 1.0 issue, so it's fine for now.

**Comment by vivekmenezes** [comment]
Closing this for now. Reopen later if we decide to do it.

**Comment by tamird** [comment]
closing issues for "doing later" doesn't look like the correct way to track things; we're approach 14k issues, closing issues is a good way to lose them.

Perhaps we need a milestone.

**Comment by petermattis** [comment]
There is a "Later" milestone. That seems preferable than trying to recall these closed features in the future.

**Comment by vilterp** [comment]
FYI @piyush-singh this would be necessary for the per-table time series which are in our mockups. I think read/write counts would be especially valuable, so you can see what tables are "hot" and correlate that with CPU usage on each node.

Note that metrics are collected on a per-node basis and aggregated at query time (or not aggregated, if you so choose), so we'd be able to show a per-table, per-node view (i.e. replica matrix) without extra work.
