### ISSUE TITLE
ttl: improve row-level TTL performance using DistSQL

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#76914]
the TTL job should be distributed using DistSQL / a DistSQL flow job (mentioned by @miretskiy).
   * It does not shard out deletes to be local to each region yet either (i'd say ideally the leaseholders of the range should perform the delete)
  

Further improvements related to a secondary index are mentioned here:
* https://github.com/cockroachdb/cockroach/issues/82140

Jira issue: CRDB-13392
Epic CRDB-14592

**Comment by vy-ton** [comment]
> up for debate as to whether an index on crdb_internal_expiration is useful as we don't believe this adds a significant improvement in delete performance

Why is this the case?

**Comment by otan** [comment]
> Why is this the case?

the index helps with scanning for entries that need to be deleted really fast, and can end the job early, but means that the actual delete of rows will need to touch multiple distinct ranges to work which can be a source of contention. it's worth experimenting!

**Comment by vy-ton** [comment]
Based on discussion, we will investigate

> the TTL job should be distributed using DistSQL / a DistSQL flow job
