### ISSUE TITLE
Enabling experimental change feed caused something cluster wide to lock

### ISSUE THREAD

**Issue by steven-hubbard** [cockroachdb/cockroach#76927]
Ran into an issue with a client trying to set up CDC change feed, but this is not really a CDC question. While they were setting up the feed, User 1 logged in on node 1 and attempted to create the feed with SET CLUSTER SETTING kv.rangefeed.enabled=true and experimental changefeed for cdc_test;. 

The second command appeared to hang so User 1 attempted to Ctrl+C the command. An output of “Cancel request sent” was displayed but nothing seemed to happen. User 1 attempted to cancel the command a dozen times with the same output message. 

User 2 (a root user) logs into a different node and then attempts to grant User 1 admin privileges as an attempt to help with the situation. The grant request then hung. User 2 then went to the DBConsole and killed the session for User 1 which then allowed the grant to resolve. 

As a result of this chain of events, we have the following:
1. Changefeed command didn’t work (least concerning)
2. The client couldn’t kill the command (seems more problematic)
3. This command appeared to lock something cluster wide (most problematic)

It seems like without a sink specified, the sink is routed to the terminal that executed the command which would explain number 1 and possibly number 2 to some degree. The larger problem is the cluster wide lock from this scenario.

Jira issue: CRDB-13330

**Comment by steven-hubbard** [comment]
Apologies, cant believe I forgot that.

Self Hosted with the following:

Build Tag:        v21.2.5
Build Time:       2022/02/07 21:01:07
Distribution:     CCL
Platform:         linux amd64 (x86_64-unknown-linux-gnu)
Go Version:       go1.16.6
C Compiler:       gcc 6.5.0
Build Commit ID:  5afb632f77eee9f09f2adfa2943e1979ec4ebedf
Build Type:       release

**Comment by miretskiy** [comment]
Just want to make sure you saw the above point re sinkless feeds -- basically, works as intended re nothing being emitted...
But this context business is interesting.

**Comment by miretskiy** [comment]
I was not able to reproduce this issue locally.  In particular, the fact that the client didn't see anything -- that makes sense, you need '--format=csv' flag.  Also, hitting ctrl-c worked for me.  Can you double check if the client still experiencing these issues?

**Comment by steven-hubbard** [comment]
Yes we just got some more information this morning. They were able to recreate the issue and the alter role command went through after 5 minutes with the following info in the log:

[n2,job=742959045005541378,scExec,id=23] 222226 waiting for 1 leases to expire: desc=[{‹role_members› 23 15}]

And the following comment from the customer:
The difference being the waiting for 1 leases to expire bit. The instance that took 5 mins I ran immediately after doing experimental changefeed for cdc_test; in a psql session, the instance that completed immediately I ran after I noticed the one that blocked had completed

The steps to reproduce are:
1. run `experimental changefeed for cdc_test;` with no destination sink specified
2. Try to alter a role

**Comment by miretskiy** [comment]
I honestly cannot reproduce it.  Perhaps needs to be escalated to schema.  And probably a bit more information
gathered to reproduce exactly the situation.  What is the user they are connecting as? What is the role? What user trying to alter the role? Might make sense to try to setup live repro.

**Comment by ajwerner** [comment]
I'm sure this has to do with leaking leases somewhere.

**Comment by ajwerner** [comment]
but, a repro would be wonderfully helpful

**Comment by ajwerner** [comment]
oh, I have a thought

**Comment by ajwerner** [comment]
Okay this is due to the fact that we don't drop the leases in experimental changefeed. That's broken. This is a good bug find.

**Comment by ajwerner** [comment]
The below snippet confirmed fixes it. We'll need a test. @miretskiy can you get somebody on the cdc team to take it from here?

```go
diff --git a/pkg/ccl/changefeedccl/changefeed_stmt.go b/pkg/ccl/changefeedccl/changefeed_stmt.go
index f0432d3d51..455d2a3b66 100644
--- a/pkg/ccl/changefeedccl/changefeed_stmt.go
+++ b/pkg/ccl/changefeedccl/changefeed_stmt.go
@@ -164,6 +164,14 @@ func changefeedPlanHook(
                }
 
                if details.SinkURI == `` {
+                       // If this is a sinkless changefeed, then we should not hold on to the
+                       // descriptor leases accessed to plan the changefeed. If changes happen
+                       // to descriptors, they will be addressed during the execution.
+                       // Failing to release the leases would result in preventing any schema
+                       // changes on the relevant descriptors (including, potentially,
+                       // system.role_membership, if the privileges to access the table were
+                       // granted via an inherited role).
+                       p.ExtendedEvalContext().Descs.ReleaseAll(ctx)
```

Here is a sketch of how I verified:

Session 1, as an admin user
```sql
create table tab();
create user foo;
grant select on tab to foo;
create user bar password 'asdf';
grant foo to bar;
alter role bar with controlchangefeed;
set cluster setting kv.rangefeed.enabled = 'true';
```

session 2, as bar
```sql
\set display_format=csv
experimental changefeed for foo with resolved
```

session 1, any of the following would have blocked before
```sql
grant select on tab to bar;
grant admin to foo;
```

**Comment by miretskiy** [comment]
Wow, thank you so much for this!
We'll add this fix to upcoming release, but it does appear that this bug existed since forever.
The 5 minutes they observe, is the default 5 minute expiration for schema leases.

**Comment by ajwerner** [comment]
> The 5 minutes they observe, is the default 5 minute expiration for schema leases.

Yes: https://github.com/cockroachdb/cockroach/blob/8817c28fd444727ab30332bb90580a62b358119d/pkg/base/config.go#L86-L91
