### ISSUE TITLE
sql: Fix UX for dropping a user with default privileges

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#76950]
Example in 21.2

```
CREATE USER foo;
GRANT SELECT ON DATABASE defaultdb TO foo;
REVOKE ALL ON DATABASE defaultdb FROM foo;
DROP USER foo;
```

Results in error
```
Query 1 ERROR: ERROR: role foo cannot be dropped because some objects depend on it
privileges for default privileges on new relations for all roles
HINT: use SHOW DEFAULT PRIVILEGES FOR ROLE to find existing default privileges and execute ALTER DEFAULT PRIVILEGES {FOR ROLE ... / FOR ALL ROLES} REVOKE ... ON ... FROM ... to remove them
see: SHOW DEFAULT PRIVILEGES and ALTER DEFAULT PRIVILEGES
```

We should make it clear how to revoke that privilege, for example it is not clear which database it is even on.

**Comment by rafiss** [comment]
fixed by https://github.com/cockroachdb/cockroach/pull/77016

**Comment by georgeli-roblox** [comment]
it would be good to have a feature `drop user <username> cascade`  so it will take care of all the clean-ups it needs on the DB side ?   Thanks

**Comment by RichardJCai** [comment]
> it would be good to have a feature `drop user <username> cascade` so it will take care of all the clean-ups it needs on the DB side ? Thanks

We plan on adding support for `drop owned by` (postgres has this instead of cascade)
https://github.com/cockroachdb/cockroach/issues/55381
