### ISSUE TITLE
Makefile: should error out if bash isn't installed

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#7698]
Trying to build cockroach without `bash` results in a very cryptic error (see https://www.cockroachlabs.com/blog/critters-in-a-jar-running-cockroachdb-in-a-freebsd-jail/#comment-2771120260)

```
gostuff% gmake install
Makefile:243: .bootstrap: No such file or directory
gmake: -c: Command not found
Makefile:223: recipe for target '.git/hooks/post-merge' failed
gmake: *** [.git/hooks/post-merge] Error 127
```

We should error out with a more helpful message.

We should also call this out in the prerequisites in CONTRIBUTING.MD and in the build instructions (https://www.cockroachlabs.com/docs/install-cockroachdb.html).

**Comment by RaduBerinde** [comment]
#4958 is the reason we need bash.

**Comment by bdarnell** [comment]
We also need bash for `depvers.sh` (invoked indirectly by `make build`). And maybe for other shell scripts, but I think `depvers.sh` is the only one involved in regular builds.
