### ISSUE TITLE
kvserver: TestReplicateQueueDeadNonVoters timing out

### ISSUE THREAD

**Issue by amygao9** [cockroachdb/cockroach#76996]
**Describe the problem**

`TestReplicateQueueDeadNonVoters` fails in certain scenarios where a race between the `replicateQueue`'s snapshots and
`raftSnapshotQueue's` causes the test to time out. When the `raftSnapshotQueue` wins this race, the `replicateQueue's`
snapshot fails and we mark the store as throttled for 5s, which makes the store not a valid rebalance target. Thus, when this race occurs 9 times, it stalls rebalancing and the test fails since the call to `forceScanOnAllReplicationQueues` inside `checkReplicaCount` will take longer than 45 seconds.

See comments in: https://github.com/cockroachdb/cockroach/pull/75251

Jira issue: CRDB-13363

**Comment by ajwerner** [comment]
Another flake: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_Test/4473979?showRootCauses=false&expandBuildChangesSection=true&expandBuildDeploymentsSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

**Comment by rafiss** [comment]
this test is skipped here: https://github.com/cockroachdb/cockroach/blob/60fa6c0b8521b103da81bd967f0335c1d9503418/pkg/kv/kvserver/replicate_queue_test.go#L1034
