### ISSUE TITLE
sql: creating hash-sharded index with high bucket count takes a long time

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#77000]
I just tried to create a table with a hash-sharded index with a bucket count of `999999999`, and the `CREATE TABLE` statement locked up for some time and I had to kill the `demo` process.

```sql
CREATE TABLE t (
    a INT,
    INDEX (a) USING HASH WITH BUCKET_COUNT=999999999
)
```

I don't see any need to support a bucket count this high. Bucket counts of `1024`, `2048`, and `4096` all seemed to work fine. Maybe we should choose one as a maximum to enforce.

**Comment by chengxiong-ruan** [comment]
This is because `999999999` would cause a gigantic check constraint :( :
https://github.com/cockroachdb/cockroach/blob/5b42a981892c067390d84cf9b27ab3aa427cb2b5/pkg/sql/create_table.go#L2663-L2663
