### ISSUE TITLE
storage: internal documentation of Store and Replica locking/synchronization

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#7710]
Similar to #7704 and #7683. Document the locking and synchronization used by `Store` and `Replica`, specifically `Store.processRaftMu`, the `Store` raft goroutine, `Store.mu.Mutex`, `Store.pendingRaftGroups.mu.Mutex` and `Replica.mu.Mutex`.

**Comment by bdarnell** [comment]
I'll take this on; it will fit nicely with #4476
