### ISSUE TITLE
acceptance: allocator tests don't destroy cluster upon timeout

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#7712]
When the TESTTIMEOUT for `make test` is triggered, it doesn't seem to allow the allocator test to destroy its test cluster as it usually does. This wastes GCE computing resources.

**Comment by cuongdo** [comment]
Also, node logs aren't stored as TeamCity artifacts when we encounter the timeout.

**Comment by tschottdorf** [comment]
I don't think the test gets to do anything about the test timeout (it's a
panic in a separate goroutine, so we can't recover() it). But I think we
might be able to `flag.Lookup` the `-test.timeout` flag and then do a more
orderly shutdown before we hit the hard limit.

On Fri, Jul 8, 2016 at 6:54 PM Cuong Do <notifications@github.com> wrote:

> Also, node logs aren't stored as TeamCity artifacts when we encounter the
> timeout.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/7712#issuecomment-231491513>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE135HFNWf7sDSJk1VAkq5jtBAHOiGqPks5qTtUKgaJpZM4JIdUC>
> .
>
-- 

-- Tobias

**Comment by petermattis** [comment]
Could whatever script runs the acceptance test also perform cleanup? Surely something is invoking `make acceptance` or `acceptance/run.sh`. If the tests left a little state indicating the GCE resources they are using, a small additional utility could be run after the tests to cleanup any dangling state.

**Comment by tschottdorf** [comment]
The remote tests don't use `make acceptance` or any wrapper scripts (and I suggest to keep it vanilla), so it's a bit tricky plus we often want to keep the state (so the logic to clean up needs to be flag-aware).
Our test boxes can easily clean up after themselves (it's as easy as the correct version of `find . -name '*.tfstate' --execdir terraform destroy --force '{}' ';'`)

That along with stopping the tests early by peeking into the timeout should do it, I think. The latter works flawlessly, as can be seen from

```
func TestTimeout(t *testing.T) {
	f := flag.Lookup("test.timeout")
	if f == nil {
		return
	}
	d, err := time.ParseDuration(f.Value.String())
	if err != nil {
		t.Fatal(err)
	}
	t.Fatal(d)
}
```

**Comment by petermattis** [comment]
This is fixed by `roachprod`-based tests where we place a lifetime on the clusters. Closing as we're in the process of moving the terraform-based tests to use `roachprod/roachtest`.
