### ISSUE TITLE
server: don't use GetAllDescriptors in HotRangesV2 api

### ISSUE THREAD

**Issue by koorosh** [cockroachdb/cockroach#77126]
**Describe the problem**

Currently, `GetAllDescriptors` func is used in `HotRangesV2` api to get additional information per hot range.
It can be inefficient to keep all this data in memory.

**Expected** to get only subset of descriptors that are required for hot ranges.

Related to https://github.com/cockroachdb/cockroach/pull/74377

Jira issue: CRDB-13423

**Comment by knz** [comment]
@nkodali  @dhartunian can you fit this into the roadmap? we don't want large schemas to cause resource exhaustion especially at those times where they are already nearly exhausted and the operator needs the endpoint to troubleshoot resource usage.
