### ISSUE TITLE
sql: add memory monitor to IndexBackfillMerger

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#77123]
The current backfill merger is not currently memory monitored.  We should attach a memory monitor to it and monitor the memory used during the merge process:

- Memory used for the ScanRequest's send to the temporary index
- Memory used for the rewritten keys 

Jira issue: CRDB-13421

**Comment by ajwerner** [comment]
I'm inclined to mark this as a release blocker. The index and column backfiller do use memory monitoring IIUC.

**Comment by stevendanna** [comment]
Done. Let's try to get to it this week.

**Comment by stevendanna** [comment]
This was closed in #77055
