### ISSUE TITLE
opt: avoid re-constructing entire memo on mutation Placeholder injection

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#77128]
In https://github.com/cockroachdb/cockroach/pull/63807, we added a fast-path that skips plan re-optimization during placeholder injection for simple SELECT statements.

We should do the same thing for mutations like INSERTs and DELETEs, and maybe also UPDATEs and UPSERTs if possible. I suspect that mutations are even more likely to be "trivial" than SELECTs, so this fast-path is should be worthwhile.

See https://github.com/cockroachdb/cockroach/issues/57223#issuecomment-1003204222, where this was originally discussed.

Jira issue: CRDB-13424

**Comment by cucaroach** [comment]
CC @vy-ton

**Comment by mgartner** [comment]
I think that the best general solution for this type of problem is [generic query plans](https://github.com/cockroachdb/cockroach/pull/117284).
