### ISSUE TITLE
rel: add element nonexistence clause support

### ISSUE THREAD

**Issue by postamar** [cockroachdb/cockroach#77148]
This will allow us to define schema changer dependency rules which are conditional on an element _not_ being present, which isn't possible right now. 

There is already a need for this, we want certain rules to apply on a column only if a table is being dropped. In that case there will be a `Table` element, and its target will be `ABSENT`. However in an ALTER TABLE there will be no such `Table` element.

Epic: CRDB-13602

Jira issue: CRDB-13433

**Comment by ajwerner** [comment]
An alternative here is to put the existing elements in the graph but find some way to represent that their status should not change.

**Comment by postamar** [comment]
Is this still relevant? We've since changed how DROPs work, and we now have != in rel.

**Comment by ajwerner** [comment]
It might come back up. I don't know that we need to track it. Let's wait until we need it for a compelling reason.
