### ISSUE TITLE
rules: transient target support, more expressive rules grammar, better rules testing

### ISSUE THREAD

**Issue by postamar** [cockroachdb/cockroach#77149]
To support TRANSIENT targets, the rules should be expressed as little as possible in terms of targets and as much as possible in terms of nodes.

Consider for example the TRANSIENT path of the temporary index supporting a new primary index with an added column:
ABSENT -> DELETE_ONLY -> WRITE_ONLY -> DELETE_ONLY -> TRANSIENT

In this case we can't have a dependency rule defined on joining the target status to TRANSIENT and the "from" node's status to DELETE_ONLY, because it's ambiguous. We could introduce dummy statuses to disambiguate them but this would result in multiple, redundant dep rules. 

For this reason, such a rule should instead be defined on "from" node status being DELETE_ONLY and "to" node status being "WRITE_ONLY" (or whatever). 

1. We need a more convenient grammar for expressing rules in such a fashion. In particular, joins should be easier to express. I'm also worried that the rules are at risk of becoming a big spaghetti-like mess if we can't express them more clearly. 
2. We need better visibility in the subset of rules which affect one particular element
2. We should investigate property-based testing of the rules and/or the ruleset.

Epic: CRDB-13602

Jira issue: CRDB-13434

**Comment by postamar** [comment]
@ajwerner I believe you're effectively doing this, so assigning this to you.

**Comment by ajwerner** [comment]
Yes.
