### ISSUE TITLE
schemachanger: improve observability

### ISSUE THREAD

**Issue by postamar** [cockroachdb/cockroach#77158]
Presently, observability in the declarative schema changer consists in graphviz URLs returned either deliberately via `EXPLAIN (DDL)` or `EXPLAIN (DDL, DEPS)` statements, or less deliberately as details attached to internal errors.

These are nice but inadequate. Users will struggle to interpret them. Even we do sometimes. They're simply not legible outside of the most simple schema changes. Dropping 10 tables? Forget it.

Instead we should output something similar to what's in the data-driven tests for the schema change planner. Perhaps some text-friendly serialization of the schema change protobuf, along with some `debug` CLI tooling to interpret it. 

In any case what's there right now is worse than useless in production.

Jira issue: CRDB-13441

Epic: CRDB-2356

**Comment by ajwerner** [comment]
Let's make sure that the structured state of the schema change, upon error, makes its way into the job record. 

If it fails pre-commit, then what? Then we didn't do any damage, so we don't need to do too much.

For the next release, it'd be great to shove the whole trace into a statement bundle and write that out to the statement bundle infrastructure.

**Comment by postamar** [comment]
Closing https://github.com/cockroachdb/cockroach/issues/65663 as this one subsumes that one. That issue tracked adding "insightful logging which reveals the progress of the new schema changer."

**Comment by postamar** [comment]
As discussed with Andrew this morning, I'll assign myself to wrap up this issue. To do:
1. reintroduce the graphviz URLs I removed from EXPLAIN (DDL), but hide them behind a flag;
2. update the declarative schema change job running status;
3. serialize and store any job error protos so that they can be retrieved from the jobs table afterwards.

(3) can be tested by injecting an error much like we do in the rollback tests, and checking that the %v output is returned to the user and that the %+v can be found in the jobs table.

**Comment by ajwerner** [comment]
fixed by https://github.com/cockroachdb/cockroach/pull/79952
