### ISSUE TITLE
schemachanger: remove embedded structs from yaml output in tests

### ISSUE THREAD

**Issue by postamar** [cockroachdb/cockroach#77155]
Embedded structs in schema changer elements show up explicitly and with a separate level of nesting in data-driven test output. It's just noise, remove it.

https://github.com/cockroachdb/cockroach/pull/76776#discussion_r811415998

**Comment by ajwerner** [comment]
I tried and it's harder than I thought it would be. We'll suffer a layer of indentation for the next while until somebody musters the will to fight this fight.
