### ISSUE TITLE
sql: fix unimplemented feature link and telemetry to differentiate between sql and plpgsql functions

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/cockroach#77177]
There is a telemetry features counter for `unimplemented.#17511.create function` which does not differentiate between SQL and  other kinds of functions like plpgsql.

The following should link to https://github.com/cockroachdb/cockroach/issues/58356
```
demo@127.0.0.1:26257/movr> CREATE FUNCTION one() RETURNS integer AS $$
    SELECT 1 AS result;
$$ LANGUAGE SQL;
invalid syntax: statement ignored: at or near "one": syntax error: unimplemented: this syntax
SQLSTATE: 0A000
DETAIL: source SQL:
CREATE FUNCTION one() RETURNS integer AS $$
                ^
HINT: You have attempted to use a feature that is not yet implemented.
See: https://go.crdb.dev/issue-v/17511/v21.2
```

Goal: Be able to differentiate in telemetry usage of different types of functions

Jira issue: CRDB-13449

**Comment by vy-ton** [comment]
fyi @rafiss could be a useful telemetry item for stability

**Comment by rafiss** [comment]
Closing since we should be able to get this from log-based telemetry instead.

**Comment by vy-ton** [comment]
FYI @devadvocado I opened this issue but we should favor doing this type of analysis with the new logging telemetry
