### ISSUE TITLE
bazel: `dev build short` (and perhaps build) does not re-link with newer SHA in `build.rev` 

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#77198]
**Describe the problem**

When I perform a git commit touching files *that is not part of the build dependencies known to bazel*, `dev build` does not trigger a re-link of the crdb executable with the new SHA.

In particular I am not seeing a re-link with the following flags (for example):
```
-X "github.com/cockroachdb/cockroach/pkg/build.tag=v22.1.0-alpha.00000000-4541-gbf13dc6061-dirty" 
-X "github.com/cockroachdb/cockroach/pkg/build.rev=bf13dc6061ab080c8c4306ebabb5065331877508"
```

I think it should: we want to always include the SHA of the git commit inside the executable produced by a build.

**To Reproduce**

1. warm up the build cache and artifacts with a first `dev build short`
2. modify a file that's not a direct build dependency (e.g. AUTHORS)
3. commit
4. run `dev build short` again

Observe: nothing happens, the executable is not re-linked. The new SHA is not included.

Compare: with `make buildshort`, the executable gets relinked properly.

Jira issue: CRDB-13469

Epic CRDB-8036

**Comment by knz** [comment]
Hm if it was deliberate then I have no objection.

**Comment by irfansharif** [comment]
Yup, deliberate. It shaves off ~17s of go link time whenever you're switching branches and are expecting your cache to contain everything. Also because the bazel cache is agnostic to kind of data inside it, it stops littering it with 300MB CRDB binaries that will never be refetched.
