### ISSUE TITLE
Table schema affects the UPDATE statement unexpectedly

### ISSUE THREAD

**Issue by sayJason** [cockroachdb/cockroach#77205]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**
I try the following statements:
```sql
DROP TABLE IF EXISTS t0; 
CREATE TABLE t0 (c0 INTERVAL UNIQUE, c1 INT); 
INSERT INTO t0 VALUES(null,1); 
UPDATE t0 SET c0 = null, c1 = 2 WHERE t0.c0 > (INTERVAL '1 year 1 months 1280880 days 1 hours 1 minutes 1 seconds'); -- 1
UPDATE t0 SET c1 = 2 WHERE t0.c0 > (INTERVAL '1 year 1 months 1280880 days 1 hours 1 minutes 1 seconds'); -- 2
UPDATE t0 SET c0 = null WHERE t0.c0 > (INTERVAL '1 year 1 months 1280880 days 1 hours 1 minutes 1 seconds'); -- 3

DROP TABLE IF EXISTS t0; 
CREATE TABLE t0 (c0 INTERVAL UNIQUE); 
INSERT INTO t0 VALUES(null); 
UPDATE t0 SET c0 = null WHERE t0.c0 > (INTERVAL '1 year 1 months 1280880 days 1 hours 1 minutes 1 seconds'); -- 4
```
**Expected behavior**
I think the four statements should both throw an error or not, because the additional column should not affect the evolution of the UPDATE statement, which do not operate on the additional column.
In fact, statement 4 threw an overflow error, and the other three statements did not throw errors.
```sql
root@localhost:26257/test> UPDATE t0 SET c0 = null, c1 = 2 WHERE t0.c0 > (INTERVAL '1 year 1 months 1280880 days 1 hours 1 minutes 1 secon
ds'); -- 1
UPDATE 0


Time: 25ms total (execution 16ms / network 9ms)
root@localhost:26257/test> UPDATE t0 SET c1 = 2 WHERE t0.c0 > (INTERVAL '1 year 1 months 1280880 days 1 hours 1 minutes 1 seconds'); -- 2
UPDATE 0


Time: 3ms total (execution 3ms / network 0ms)
root@localhost:26257/test> UPDATE t0 SET c0 = null WHERE t0.c0 > (INTERVAL '1 year 1 months 1280880 days 1 hours 1 minutes 1 seconds'); --
 3
UPDATE 0


Time: 1ms total (execution 1ms / network 0ms)
root@localhost:26257/test> UPDATE t0 SET c0 = null WHERE t0.c0 > (INTERVAL '1 year 1 months 1280880 days 1 hours 1 minutes 1 seconds'); --
 4
ERROR: overflow during Encode
SQLSTATE: 22015
```

**Additional data / screenshots**
**Environment:**
cockroach version details:
Build Tag:        v21.2.6
Build Time:       2022/02/22 18:30:37
Distribution:     CCL
Platform:         linux amd64 (x86_64-unknown-linux-gnu)
Go Version:       go1.16.6
C Compiler:       gcc 6.5.0
Build Commit ID:  c7cfac57476f06e3154b2fc38e77982a8bbc64c2
Build Type:       release
(use 'cockroach version --build-tag' to display only the build tag)
**Additional context**

Jira issue: CRDB-13473

**Comment by cucaroach** [comment]
Underlying issue: https://github.com/cockroachdb/cockroach/issues/45993
