### ISSUE TITLE
An overflow happened when querying an INTERVAL column with UNIQUE constraint

### ISSUE THREAD

**Issue by sayJason** [cockroachdb/cockroach#77201]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

I try the following statements.
```sql
DROP TABLE IF EXISTS t0;
CREATE TABLE t0 (c0 INTERVAL UNIQUE, c1 INT); 
INSERT INTO t0 VALUES(null,1);
SELECT c0 FROM t0 WHERE t0.c0 > (INTERVAL '1 year 1 months 1280880 days 1 hours 1 minutes 1 seconds'); -- 1
SELECT c0,c1 FROM t0 WHERE t0.c0 > (INTERVAL '1 year 1 months 1280880 days 1 hours 1 minutes 1 seconds'); -- 2
SELECT c1 FROM t0 WHERE t0.c0 > (INTERVAL '1 year 1 months 1280880 days 1 hours 1 minutes 1 seconds'); -- 3
```

**Expected behavior**
I think the above three statement should both fail or succeed. While the statement 1 generated an overflow error like follows and statement 2 and 3 did generate an error.
```sql
root@localhost:26257/test> SELECT c0 FROM t0 WHERE t0.c0 > (INTERVAL '1 year 1 months 1280880 days 1 hours 1 minutes 1 seconds'); -- 1
ERROR: overflow during Encode
SQLSTATE: 22015
root@localhost:26257/test> SELECT c0,c1 FROM t0 WHERE t0.c0 > (INTERVAL '1 year 1 months 1280880 days 1 hours 1 minutes 1 seconds'); -- 2
  c0 | c1
-----+-----
(0 rows)


Time: 5ms total (execution 4ms / network 2ms)
root@localhost:26257/test> SELECT c1 FROM t0 WHERE t0.c0 > (INTERVAL '1 year 1 months 1280880 days 1 hours 1 minutes 1 seconds'); -- 3
  c1
------
(0 rows)


Time: 2ms total (execution 2ms / network 0ms)
```

**Additional data / screenshots**

**Environment:**
cockroach version details:
Build Tag:        v21.2.6
Build Time:       2022/02/22 18:30:37
Distribution:     CCL
Platform:         linux amd64 (x86_64-unknown-linux-gnu)
Go Version:       go1.16.6
C Compiler:       gcc 6.5.0
Build Commit ID:  c7cfac57476f06e3154b2fc38e77982a8bbc64c2
Build Type:       release
(use 'cockroach version --build-tag' to display only the build tag)

**Additional context**

Jira issue: CRDB-13470

**Comment by sayJason** [comment]
I think this is not duplicate. 
In this case, overflow happens in SELECT when only querying the INTERVAL column no matter how table schema changes. 
In https://github.com/cockroachdb/cockroach/issues/77205, the changes of table schema affect the evaluation of UPDATE. 
Is the same reason to cause these two problems?

**Comment by msbutler** [comment]
@sayJason I suspect that these two problems have the same root cause, but I'll keep this issue open and send it to the right team to investigate. Thanks for filing!

**Comment by cucaroach** [comment]
Underlying issue: https://github.com/cockroachdb/cockroach/issues/45993
