### ISSUE TITLE
bazel: `dev testlogic base` fetches the large sqllogictest archives unnecessarily

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#77204]
**Describe the problem**

I ran `dev testlogic base --filter=role` and this failed because I didn't have an internet connection (??)
Then after I restored connectivity, I had to wait for a 100MB download of `sqllogictest-96138842571462ed9a697bff590828d8f6356a2f.tar.gz`, which is totally unneeded for this command.

`make testbaselogic FILES=role` does not incur this extra work.

Epic CRDB-8036

Jira issue: CRDB-13472

**Comment by rickystewart** [comment]
Hmm. We need the dependency for the SQLite logic tests. Of course Bazel doesn't know that your filter excludes those tests  so the download happens either way.

Maybe we should be separating the SQLite logic tests out into a separate target to avoid this?

**Comment by knz** [comment]
yes, I agree they would be best separated into a separate target.
