### ISSUE TITLE
Some jobs have a `num_runs` of 2 even though they have only run once

### ISSUE THREAD

**Issue by jocrl** [cockroachdb/cockroach#77229]
**Describe the problem**

IMPORT INTO jobs have a `num_runs` of 2 even though they have only run once. This causes them to be mistakenly marked as "retrying" in the UI, and have "2" in the "Execution Count" column.

This also likely affects other types of jobs that call [this](https://github.com/cockroachdb/cockroach/blob/master/pkg/jobs/jobs.go#L917) `Start` function. See comment for details.

The new UI that adds the "retrying" (#68179) was introduced via a backport to 21.2. This back end bug is probably present in multiple prior versions, but the fix should definitely be backported to at least 21.2 because the new "retrying" UI amplifies the bug.

**To Reproduce**

```
./cockroach start-single-node --insecure --logtostderr=true --advertise-addr localhost
./cockroach workload fixtures import tpcc --warehouses=500 --checks=false
```

Then check DB Console, or `SELECT num_runs, job_id, status, job_type, description, statement FROM crdb_internal.jobs limit 20;`.

**Expected behavior**
`num_runs` should be 1, and the UI should not show them as retrying.

**Additional data / screenshots**

<img width="1447" alt="image" src="https://user-images.githubusercontent.com/91907326/156213387-318138fb-0f6a-452e-9cfc-6c3037b5ac2c.png">

<img width="1681" alt="image" src="https://user-images.githubusercontent.com/91907326/156213512-04fb52b6-1453-4350-ad75-2d4c1f97da3e.png">

**Environment:**
 - CockroachDB version 22.1, commit `12c968fd34e2347cc10bde75e8501a1e4431fa15`

Jira issue: CRDB-13493

**Comment by jocrl** [comment]
This `started` function [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/jobs/jobs.go#L263) seems to be the only place where `num_runs` is incremented. This `started` function is called in two places, in `Start` [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/jobs/jobs.go#L917) which is called via import planning [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/importer/import_planning.go#L987) for `IMPORT INTO` jobs, and in `stepThroughStateMachine` [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/jobs/registry.go#L1116)

Putting log statements in the `started` function, and at import planning and `stepThroughStateMachine` shows that both code paths are hit for a given job ID:

```
I220301 17:56:20.309284 1394 sql/importer/import_planning.go:987 ⋮ [n1,client=[::1]:59029,user=root] 128  job id: 740841816953716737, starting from import planning
I220301 17:56:20.327959 1363 sql/importer/import_planning.go:987 ⋮ [n1,client=[::1]:59028,user=root] 129  job id: 740841816954208257, starting from import planning
I220301 17:56:20.328189 1289 sql/importer/import_planning.go:987 ⋮ [n1,client=[::1]:59025,user=root] 130  job id: 740841816954077185, starting from import planning
I220301 17:56:20.328210 1259 sql/importer/import_planning.go:987 ⋮ [n1,client=[::1]:59030,user=root] 131  job id: 740841816956305409, starting from import planning
I220301 17:56:20.347752 1394 jobs/jobs.go:281 ⋮ [n1,client=[::1]:59029,user=root] 132  incrementing num runs
I220301 17:56:20.367662 1363 jobs/jobs.go:281 ⋮ [n1,client=[::1]:59028,user=root] 134  incrementing num runs
I220301 17:56:20.367662 1259 jobs/jobs.go:281 ⋮ [n1,client=[::1]:59030,user=root] 133  incrementing num runs
I220301 17:56:20.367662 1289 jobs/jobs.go:281 ⋮ [n1,client=[::1]:59025,user=root] 135  incrementing num runs
I220301 17:56:20.466177 1337 jobs/registry.go:1094 ⋮ [n1] 136  IMPORT job 740841816953716737: stepping through state running with error: <nil>
I220301 17:56:20.466318 1337 jobs/registry.go:1116 ⋮ [n1] 137  job id: 740841816953716737, starting from step through state machine
I220301 17:56:20.504181 1443 jobs/registry.go:1094 ⋮ [n1] 138  IMPORT job 740841816954077185: stepping through state running with error: <nil>
I220301 17:56:20.504234 1323 jobs/registry.go:1094 ⋮ [n1] 139  IMPORT job 740841816956305409: stepping through state running with error: <nil>
I220301 17:56:20.504248 1443 jobs/registry.go:1116 ⋮ [n1] 141  job id: 740841816954077185, starting from step through state machine
I220301 17:56:20.504260 1323 jobs/registry.go:1116 ⋮ [n1] 142  job id: 740841816956305409, starting from step through state machine
I220301 17:56:20.504242 1339 jobs/registry.go:1094 ⋮ [n1] 140  IMPORT job 740841816954208257: stepping through state running with error: <nil>
I220301 17:56:20.504294 1339 jobs/registry.go:1116 ⋮ [n1] 143  job id: 740841816954208257, starting from step through state machine
I220301 17:56:20.523235 1337 jobs/jobs.go:281 ⋮ [n1] 144  incrementing num runs
I220301 17:56:20.542259 1339 jobs/jobs.go:281 ⋮ [n1] 146  incrementing num runs
I220301 17:56:20.542259 1323 jobs/jobs.go:281 ⋮ [n1] 145  incrementing num runs
I220301 17:56:20.542259 1443 jobs/jobs.go:281 ⋮ [n1] 147  incrementing num runs
```

**Comment by samiskin** [comment]
Resolved by https://github.com/cockroachdb/cockroach/pull/77240
