### ISSUE TITLE
server: support HSTS header for HTTP connections on secure clusters

### ISSUE THREAD

**Issue by dhartunian** [cockroachdb/cockroach#77224]
**Is your feature request related to a problem? Please describe.**
When a cluster is running in secure mode, an operator should be able to enable HSTS headers on requests to ensure that browsers only connect to the DB Console using HSTS.

**Describe the solution you'd like**
This feature should be off by default (to allow for operator-driven configuration of certs and DNS before enforcing things) and be enabled via a cluster setting named something like `security.hsts.enabled`. Once this is true, HTTP requests to nodes in the cluster will be automatically upgraded to HTTPS by valid user agents.

From casually thinking this through I don't think the addition of this will break any user agents that *don't* look at this header since they'll just still use the HTTP -> HTTPS redirect. However, enabling this with an invalid HTTPS configuration could result in an unreachable DB Console from a web browser so we should take care to document properly.

**Additional context**
* HSTS Explanation https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security
* HTTP redirects are strictly less secure than HSTS because the initial HTTP request could be MITMed to redirect somewhere unsafe. With HSTS *all* requests in the browser after the initial one will use HTTPS and no redirect is necessary.

Jira issue: CRDB-13487

**Comment by mwang1026** [comment]
@dhartunian moved it to obs inf for tracking purposes since you're working on it

**Comment by abhinavg6** [comment]
PM-Approved for backporting to 21.1 and 21.2 as this change is protected by the specific cluster setting.
