### ISSUE TITLE
ST_IsValid function result error

### ISSUE THREAD

**Issue by suzixin** [cockroachdb/cockroach#77269]
**Describe the problem**

**To Reproduce**

What did you do? Describe in your own words.

```sql
create table t(g geometry  NOT NULL);
insert into t(g) values (ST_GeometryFromText('SRID=4326;POLYGON((40 50,40 70,50 100,70 100,100 100,70 50,40 50))'));
select ST_IsValid(g) from t;
```

return 
```
  st_isvalid
--------------
     true
```

**Expected behavior**
false.
The wkt contains (100,100) which is obviously illegal with SRID=4326.

**Environment:**
 - CockroachDB version [e.g. 2.0.x]
 Server version: CockroachDB CCL v22.1.0-alpha.00000000-2776-g8c06168d31-dirty (x86_64-apple-darwin21.1.0, built , go1.17.6) (same version as client)
Cluster ID: dcfde170-5486-49ba-8181-e24177b753f2
 - Server OS: [e.g. Linux/Distrib]
 mac
 - Client app [e.g. `cockroach sql`, JDBC, ...]
 cockroach sql

**Comment by otan** [comment]
> this is the same behaviour as PostGIS, so we're going to leave it that way.

```
otan=# create extension postgis;
CREATE EXTENSION
otan=# create table t(g geometry  NOT NULL);
insert into t(g) values (ST_GeometryFromText('SRID=4326;POLYGON((40 50,40 70,50 100,70 100,100 100,70 50,40 50))'));
select ST_IsValid(g) from t;
CREATE TABLE
WARNING:  OGC WKT expected, EWKT provided - use GeomFromEWKT() for this
INSERT 0 1
 st_isvalid
------------
 t
(1 row)
```

> I have another quesion, if the data is invalid, how can I build index with this invalid data?

it still works as you'd expect; SRID=4326 is more or less ignored and it pretends all shapes are on the 2D plane.

**Comment by suzixin** [comment]
> you should use the geography type if you want some special handling here.

It seems not work.
```
root@localhost:26257/defaultdb> create table t1(g geography  NOT NULL);
insert into t1(g) values (st_geogfromtext('POLYGON((40 50,40 70,50 100,70 100,100 100,70 50,40 50))',4326));
select ST_IsValid(g) from t1;
CREATE TABLE

Time: 120ms total (execution 120ms / network 0ms)
INSERT 1
Time: 112ms total (execution 112ms / network 0ms)
ERROR: unknown signature: st_isvalid(geography)
SQLSTATE: 42883
```

**Comment by otan** [comment]
geography automatically readjusts lat/lngs to be within their relevant bounds. st_isvalid is not an operator for geography.

```
demo@127.0.0.1:26257/defaultdb> create table t1(g geography  NOT NULL);
CREATE TABLE


Time: 4ms total (execution 4ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> insert into t1(g) values (st_geogfromtext('POLYGON((40 50,40 70,50 100,70 100,100 100,70 50,40 50))',4326));
INSERT 1


Time: 6ms total (execution 5ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> select st_asewkt(g) from t1;
                                st_asewkt
--------------------------------------------------------------------------
  SRID=4326;POLYGON ((40 50, 40 70, 50 80, 70 80, 100 80, 70 50, 40 50))
(1 row)


Time: 2ms total (execution 2ms / network 0ms)
```
