### ISSUE TITLE
storage: add `storage.mvcc.target_intent_bytes_per_error` 

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#77270]
We have a setting `storage.mvcc.max_intents_per_error` that gives the maximum number of intents to return in a `WriteIntentError`. The default is set fairly high at 5000, so we should have a corresponding setting for a target intent byte limit, and update all callers to take it into account.

Jira issue: CRDB-13510

**Comment by erikgrinaker** [comment]
Would have avoided e.g. https://github.com/cockroachlabs/support/issues/2692.

**Comment by lyang24** [comment]
excited to work on this issue. 
I wonder if i can to get some additional context on the problem the new byte limit is addressing (the support issue link yielded 404).
what would be a good default for the new byte limit - (i am thinking 0 as no limit?)

**Comment by shralex** [comment]
@lyang24 seems like we can now close this.
