### ISSUE TITLE
Track additional load measurements at a replica level

### ISSUE THREAD

**Issue by kvoli** [cockroachdb/cockroach#77280]
**Is your feature request related to a problem? Please describe.**
Metrics that represent measured load, on a replica within a store would aid in observability of replica load. Currently, only queries per second, representing the number of batch requests that have served by the leaseholder and writes per second, representing the number of mutations applied to keys in the Raft log are recorded. 

Currently, only queries-per-second is used for re balancing decisions. This is unfortunate, as the number of keys read in addition to the size (bytes) of each operation likely correlates to computational cost more closely than QPS alone.

**Describe the solution you'd like**

Introduce exponential weighted moving average tracking (EWMA) per second, for the following load measurements on a per-replica basis:

```
bytes read
bytes written
keys read
requests
```

In addition, unifying these metrics using a standard metric class, instead of `replica_stats` https://github.com/cockroachdb/cockroach/blob/bb5479722835a2a9aec981a700514a9046955788/pkg/kv/kvserver/replica_stats.go#L1. 

Which could track `keys written` and `batch requests` in addition to the above mentioned measurements. These are currently tracked as `writes-per-second` and `queries-per-second` respectively. 

Using the `aggmetric` package appears as a suitable alternative to replica_stats, for storing ephemeral in memory measurements. This requires an additional `Rate` aggregate metric. Each replica is registered to a store's aggregate metric struct - tracking it's own measurements in memory only; whilst the aggregate is reported as a store metric and user visible.

https://github.com/cockroachdb/cockroach/blob/9bab39faaf33dfe1f52b3edccc3f758fa6697f40/pkg/util/metric/aggmetric/agg_metric.go#L11-L13

**Describe alternatives you've considered**

Re-use `replica_stats` instead, still tracking the same metrics. This has the benefit of tracking locality of requests, however doesn't allow aggregation at recording time - rather, it requires visiting each replica within a store for collection at some interval.

**Additional context**
This issue encompasses #72053. A sketch for how this may work can be found [here](https://github.com/cockroachdb/cockroach/pull/76609)

Jira issue: CRDB-13515

**Comment by kvoli** [comment]
cc @ajwerner @shralex

**Comment by ajwerner** [comment]
err, actually, now that I look at `replicaStats`, I recall that there's a windowing component that isn't expressible in terms of aggmetrics. What's your plan there?
