### ISSUE TITLE
schemachanger: implement COMMENT ON ... statements

### ISSUE THREAD

**Issue by postamar** [cockroachdb/cockroach#77327]
This could be a good learning experience for getting acquainted with the declarative schema changer. Doing this will give exposure to all layers:
1. the COMMENT ON statements need to have hooks in `scbuildstmt`,
2. the `scbuildstmt` dependencies need to have some kind of interface or interface method for retrieving existing comments,
3. the internal executor needs to be plumbed into the `scbuild` dependencies to implement that,
4. the test dependencies therefore also need to mock the above
5. we can get rid of the placeholder string constant `__placeholder_comment__`
6. the `toPublic` paths for the comment elements need to be defined in `opgen`
7. new ops for setting comments need to be defined in `scop`
8. they need to be implemented in `scmutationexec`
9. which might in turn require some plumbing in the `mutationVisitorState` in `scexec`
10. there'll be a bunch of data-driven tests in `schemachanger/...` that need updating as a result of all this.

Epic: CRDB-13602

Jira issue: CRDB-13529

**Comment by chengxiong-ruan** [comment]
with #80380, #80769 and #80459 merged, the only thing left is to turn on the fully supported flag with version gating for 22.2
