### ISSUE TITLE
storage: Test RaftTransport with failures

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#7732]
The current tests of RaftTransport only cover successful cases; we should have more testing of failure scenarios.

Extracted from #1029

**Comment by jordanlewis** [comment]
cc @nvanbenschoten closeable?

**Comment by bdarnell** [comment]
Yeah, probably. This area of the code still doesn't have a lot of specific tests but it's exercised a lot in the wild and in roachtests, so keeping this two-year-old issue open doesn't do much good.
