### ISSUE TITLE
roachtest, roachprod: default to Wait=true in Stop

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#77334]
`Wait` should default to `true`, as that's what ~all callers want:

https://github.com/cockroachdb/cockroach/blob/5af48f0e85f10124161679408024b29623d78f73/pkg/roachprod/roachprod.go#L682-L688

We should also consider negating the field, i.e. `NoWait bool`, and to say that a signal of `0` uses `9` as a default. That way, we don't need a method to instantiate the defaults in the first place, making the zero value useful instead.

Jira issue: CRDB-13532
Epic: CRDB-10428

**Comment by srosenberg** [comment]
Noting that the current default (`Wait=false`) is responsible for the race condition in sstable-corruption [1] wherein pebble's manifest is attempted to be opened with an exclusive lock _after_ `Stop` has executed but _before_ the `cockroach` process and its exclusive locks have been released by the OS.

[1] https://github.com/cockroachdb/cockroach/issues/77029#issuecomment-1050950547
