### ISSUE TITLE
sql: sqllogictest "random expr" test failures

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#7733]
Running:
```
make test PKG=./sql TESTS=TestLogic \
   TESTFLAGS='-v -allow-prepare-fail -flex-types -max-errors 0  -error-summary 
   -d ~/go/src/github.com/cockroachdb/sqllogictest/test/random/expr/\*.test'
```
Results:
```
--- total: 1883437 tests, 6 failures, ignored 248376 unsupported queries 
--- summary of ignored errors:
[...]
pq: [59 single-occurence errors] 
pq: ... [a bunch of incompatible numeric types] (39 entries)
pq: unknown signature for AVG: ... (327 entries)
pq: unknown signature for COUNT: ... (341 entries)
pq: unknown signature for SUM: ... (575 entries)
pq: incompatible value type: ... (1584 entries)
pq: incompatible NULLIF expressions: ... (3419 entries)
pq: incompatible COALESCE expressions: ... (5415 entries)
pq: incompatible condition type: ... (7975 entries)
pq: unsupported binary operator: ... (64074 entries)
result type mismatch: ... (164562 entries)
```

Full error output: [expr-results.zip](https://github.com/cockroachdb/cockroach/files/356180/expr-results.zip)

**Comment by knz** [comment]
cc @nvanbenschoten if you want to dig low hanging fruits from there?

**Comment by knz** [comment]
@petermattis so more or less all of the other sqllogictests that we don't run yet as part of `-bigtest` either fail with these kinds of errors, or with "out of memory" (mostly due to #7572). 

For me this strongly suggests the end of the road for the existing sqllogictests.  

We may be able to sweeten the deal slightly by tweaking some typing rules but the bunch of the errors are simply too "loose" for what we want. 

Then there's a practical problem, there are also actual result errors in addition to the bunch of "prepare failures" which are ignored now: queries that return different results than expected. I suspect (but cannot confirm, due to the sheer number of them) that most of them are due to different numeric operations and sqllite's ability to compare strings with numbers where we'd return false. To fully investigate this we need  our own test generator. Filed as #7734.

**Comment by petermattis** [comment]
@knz Yeah, I agree we're reaching the end of the road for the sqllogictests. #7734 is the eventual road forward.

**Comment by knz** [comment]
See also #3292.

**Comment by knz** [comment]
I think we have built some consensus here that if we are doing more testing we'll do it in a different way. 

Closing as this is now superseded by #7734. Some work already in that direction in #7970.
