### ISSUE TITLE
kv: replication reports do not display non-voter violations

### ISSUE THREAD

**Issue by Santamaura** [cockroachdb/cockroach#77348]
**Describe the problem**

Per discussion from #76430:

>  a range with an incorrect number of non-voters is not reflected in the report in any way. I guess I would keep {under,over}_replicated_ranges to refer to the voters, and I'd add {under,over}_nonvoter_replicated_ranges to refer to non-voter violations.

**To Reproduce**

From sql shell select from `system.replication_stats`

**Expected behavior**
Should include new columns `under_nonvoter_replicated_ranges` and `over_nonvoter_replicated_ranges`

**Environment:**
 - CockroachDB version 21.2.x

**Additional context**

**Comment by zachlite** [comment]
@andreimatei, can you confirm what the desired behavior is?
>  I'd add {under,over}_nonvoter_replicated_ranges to refer to non-voter violations.
Does 'violations' mean constraint violations? Or does it mean the number of ranges that are over or under replicated, respectively?

**Comment by andreimatei** [comment]
I'm not entirely sure about the details of what we'd want. But at a high level, I think we want `system.replication_stats` to say something about ranges with insufficient or too many non-voters. So I was thinking of the number of replicas, not constraints. About constraints, I don't know if we make it possible to express replication constrains on non-voters, or how `system.replication_constraints` treats non-voters (i.e. if it looks at them at all).

**Comment by maryliag** [comment]
Replication Report is being deprecated on 23.1. This issue will no longer be valid.
