### ISSUE TITLE
sql: implement a test generator similar to sqllite's sqllogictest for TestLogic

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#7734]
See #7733: there are too many divergences between cockroachdb and sqllite to keep using sqllogictests as-is.

We need a test generator that exercises mixes of:
- expressions
- complex joins
- complex group by
- complex aggregates

**Comment by knz** [comment]
Alternatively, implement a query analyzer that filters out those sqllogictests for which we have different rules than pg/sqllite. That might be slightly more tractable. Namely:

- filter out queries using comparisons string vs. non-string
- filter out queries using division
- filter out queries with an error "expected type X, found type Y" with both X and Y numeric types

**Comment by knz** [comment]
#7970 has made a great step forward already. This comprehensively covers expression computations and a few data queries. Leaving  this issue open for follow-up work.

**Comment by RaduBerinde** [comment]
The work around #7970 only checks for panics. What we are missing is some way of generating the correct (expected) results. This is not an easy problem. One idea would be to run the same queries against PG; we would need to either restrict the grammar to what is supported by both CRDB and PG, or somehow convert arbitrary CRDB queries into PG queries.

**Comment by knz** [comment]
This has been achieved with sqlsmith somehow, hasn't it?

**Comment by mjibson** [comment]
Yes I think we can close this now.
