### ISSUE TITLE
kv: replication reports should switch from using ZoneConfig to SpanConfig

### ISSUE THREAD

**Issue by Santamaura** [cockroachdb/cockroach#77350]
**Is your feature request related to a problem? Please describe.**
Per discussion from #76430:

> Well because the handling of inheritance across the two fields seems tricky. The code translating from zone configs to span configs presumably handles it -and that translation is authoritative as it's the span configs that will ultimately be used by the allocator as the target state for ranges. So I'm thinking we should try to reuse that code.
One could argue that, by not sharing that code, the replication reports can serve to detect bugs in the respective translation. But protecting against such bugs is not the point of this report.
One could also argue that, instead of translating from zone configs to span configs on the fly, we should more simply read the span configs from storage. But if we did that, and the async job that propagates the zone config changes to the span configs is not doing its job (for whatever reason), these reports would fail to catch that and they'd lie. Catching dynamic failures of that synchronization process is, in my opinion, in scope for this report.

We should be using `SpanConfig` instead of `ZoneConfig` in order to reduce complexity in the handling of inheritance.

**Describe the solution you'd like**
Replace usage of `ZoneConfig` with `SpanConfig`

**Describe alternatives you've considered**

**Additional context**

Jira issue: CRDB-13541

**Comment by zachlite** [comment]
Knowledge for future:

This [RFC](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20210610_tenant_zone_configs.md) is a good source of knowledge and context.

Report generators that implement the `rangeVisitor` interface would need to be refactored, and the value of the `rangeVisitor` interface itself is called into question.  Functions that implement it are traversing zone configs, and in some cases doing zone config inheritance logic. 

To convert a zone config to a span config, we can read from the system config that is gossiped around the cluster.  In `visitRanges`, we can write:
```go 
// iterate through ranges
rd := nextRangeDescriptor()
spanConfig, sperr := stats.cfgs.GetSystemConfig().GetSpanConfigForKey(ctx, rd.StartKey)
```

Downstream, the report generators can use the replication and constraint configuration from the retrieved span config.

**Comment by maryliag** [comment]
Replication Report is being deprecated on 23.1. This issue will no longer be valid.
