### ISSUE TITLE
docs-issue-generation: rewrite the script in go

### ISSUE THREAD

**Issue by jlinder** [cockroachdb/cockroach#77368]
The `build/teamcity-docs-issue-generation.sh` script needs to be extended in ways beyond what we should do in a bash script. Rewrite the script in go so it can be extended to do what it needs to do.

A suggested approach:

- Create the new application in the `pkg/cmd/docs-issue-generation` directory
- Translate the existing script's logic into go.
- Update the existing script to build and run the new command
- Backport the changes to the `release-21.2` branch

Epic: DEVINF-261

Jira issue: CRDB-13554

**Comment by rickystewart** [comment]
This is done thanks to @nickvigilante .
