### ISSUE TITLE
linter: Add PR check to encourage including issue or epic refs in the PR/commit messages

### ISSUE THREAD

**Issue by jlinder** [cockroachdb/cockroach#77376]
**Describe the solution you'd like**

This new linter should be a program run by a GitHub action on every PR for these events: create, edit, reopen, synchronize.

What it will do:

For all PRs containing commits with [Release note texts](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/186548364/Release+notes), other than bug fixes, Engineers can help establish the link to Jira epics in various ways:

- If the PR relates to only one Jira epic:
    - Put the GH issue or Jira epic reference either in the PR description or in each relevant commit.
    - If the reference is in the PR description, put “Epic: None” in each commit that doesn’t relate to the epic. This is particularly important if the commit contains a release note.
- If the PR relates to multiple Jira epics:
    - Put the GH issue or Jira epic reference in each relevant commit.
    - If a single commit relates to multiple Jira epics, put all relevant GH issue or Jira epic references in that commit.
    - If all commits relate to all the Jira epics, put the GH issue or Jira epic references in the PR description or in the commit messages.
    - Put “Epic: None” in each commit with a release note that doesn’t relate to any epic.
- If the PR relates to no Jira epics:
    - Preferably, put “Epic: None” in the PR description or in each commit containing a release note.

Given Engineering’s practice to [link GitHub issues to epics](https://cockroachlabs.atlassian.net/wiki/spaces/JIRA/pages/1925283849/Epic+Linking), referencing such an issue—as opposed to the epic it links to—is preferred in cases where both a Jira epic and GitHub issue exist. This makes information in the issue easily accessible to human readers while offering an epic link that is available via the issue to automation scripts.

The “Epic: None” option accounts for the fact that a significant amount of product changes occur spontaneously (serendipitously) as a by-product of investigations on main roadmap items. When this happens, Engineers take the initiative to make user-facing changes without prior processing by a PM, and thus without prior existence of a GH or Jira issue. We do not wish to reduce the ability of Engineers to innovate and improve our product in this way. 

This solution will be encouraged, but not required, by a new optional blathers check on PRs. It will fail and give feedback on how to adjust the PR for the following cases:

- When no GH issue reference, Jira epic reference, or “Epic: None” exists in the PR description or commit messages.
- When multiple Jira epic references are in the PR description but not in individual commit messages.
- When multiple Jira epic references are in a commit message (give a warning that it’s not a common case and to check that they intend it).
- When backport PRs backport multiple source PRs and one or more of the source PRs has one of the above cases.

**Describe alternatives you've considered**

This linter can't run in TeamCity because it needs to run on PR edit and reopen events. We considered using Blathers but decided to keep this in the cockroach repo.

Jira issue: CRDB-13558

Epic DEVINF-261

**Comment by mikeCRL** [comment]
@jlinder If there is no Jira epic, are we still recommending a link from the main PR comment to the relevant issue (whether in the wiki, in the linter, or both)?

I found this PR where there was an issue ref, but it wasn’t in the main comment. It was in a subsequent comment.

https://github.com/cockroachdb/cockroach/pull/82846#pullrequestreview-1004890482

**Comment by celiala** [comment]
Status update: Wikipage to explain how to write up Epic Ref / Docs note is in progress. Expect to have draft ready for review by end of week.

**Comment by celiala** [comment]
Draft is ready for review: https://docs.google.com/document/d/1D4YrkAUsyDz0z_OBslLKLXpWV0sf53PTBqiv38XfVK0/edit#

**Comment by celiala** [comment]
Latest status and what remains to call this done:

https://docs.google.com/document/d/1yYg7LzZ3ZaIUUNpFa9VSWwLHnfJ1fj6EQQY2cZQvwH4/edit#
