### ISSUE TITLE
bazel: `dev generate` does not generate the swagger files

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#77395]
**Describe the problem**

Found in #77233 / https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_CheckGeneratedCode/4484914?showRootCauses=false&expandBuildChangesSection=true&expandBuildDeploymentsSection=true&expandBuildProblemsSection=true

`dev generate` runs to completion but fails to re-generate `docs/generated/swagger/spec.json`.

Jira issue: CRDB-13570

Epic CRDB-8036

**Comment by rickystewart** [comment]
When I discussed this with docs folks last year the opinion was the `docs/generated/swagger` stuff was stale and not used for anything. Let me follow up on this.
