### ISSUE TITLE
serverccl: flake in TenantStatusAPI

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#77407]
**Describe the problem**

Found in https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_Test/4513996?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildDeploymentsSection=true&expandBuildTestsSection=true

```
------ Stdout: -------
=== RUN   TestTenantStatusAPI/txn_id_resolution/tenant_cluster
=== CONT  TestTenantStatusAPI/txn_id_resolution/tenant_cluster
    testing.go:1169: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
        --- FAIL: TestTenantStatusAPI/txn_id_resolution/tenant_cluster (45.22s)
```

If there's a t.Fail in a goroutine, it needs to be replaced by a shared variable or a channel.

cc @dhartunian for triage

Jira issue: CRDB-13573

**Comment by dhartunian** [comment]
Unable to reproduce and recent 1000 runs on TC don't have the flake.
