### ISSUE TITLE
sql: super regions follow up issues

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#77454]
- [x] support ALTER SUPER REGION
- [x] support CREATE DATABASE WITH SUPER REGIONS
- [x] add observability, show super region. show create database should include super region. show regions should show super region membership.
- [x] block alter primary region in cases where tables with the primary region are in the primary region and underlying zone configs have to change. Block with a cluster setting that lets you override - if the cluster setting is on, we warn the user that tables are being moved in and out of a super region
- [ ] Test cases where we override zone configs with super regions

Epic CRDB-2533
Jira issue: CRDB-13600

**Comment by ajstorm** [comment]
@RichardJCai FYI, added this to the observability item above "show regions should show super region membership."

**Comment by rafiss** [comment]
Let's close this since https://github.com/cockroachdb/cockroach/pull/93939 was merged. We can file other tickets as needed and treat that as separate feature enhancements.
