### ISSUE TITLE
sql: Improve role membership cold cache scenarios

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#77452]
This issue tracks two problems:

In order to check privileges for SQL commands, we must check not just the privilege for the current user, but also all parent (and grandparent, etc) roles for that user.

Normally, the role membership information is cached, so checking privileges is quick. However, this cache of memberships needs to be cleared whenever users are modified.

We have received reports of slowness (~10 seconds) coming from the time it takes to rebuild the cache. Rebuilding the cache can happen WHILE executing almost any command, since it happens while checking if the user has privileges to run the command.

We've found two problems:

1. We have some inefficient logic that means we run multiple internal queries to construct the role membership tree. Specifically, we do one query for each layer of the role membership hierarchy. This is bad because each of these queries can result in a network hop to another node in the cluster. we can change this so it happens all in one query. See https://github.com/cockroachdb/cockroach/blob/6880665c589c6a49e3f985ed2cc3448052d26763/pkg/sql/authorization.go#L467-L516
2. Another problem is that if there are multiple user-initiated queries happening at the same time, then it’s possible for each one of them to try to repopulate the cache. This means each one of them will kick off multiple internal queries, causing more overhead in the cluster. We can fix this so that there’s only one “cache reconstruction” happening at a time. See https://github.com/cockroachdb/cockroach/blob/6880665c589c6a49e3f985ed2cc3448052d26763/pkg/sql/authorization.go#L430-L433

This issue tracks improving those cases. We currently are planning to create a backport for problem 1, but not problem 2.

Jira issue: CRDB-13599
Epic CRDB-8948

**Comment by ajwerner** [comment]
> We currently are planning to create a backport for problem 1, but not problem 2.

I support backporting both of these fixes.

**Comment by ajwerner** [comment]
I'd argue that the fact that ongoing transactions incur an extra round-trip at all is surprising and worthy of an issue in its own right.

**Comment by rafiss** [comment]
> I support backporting both of these fixes.

OK - the singleflight change turned out to be pretty small so I'll go ahead and backport that too.
