### ISSUE TITLE
SQL Memory Was Increasing Till It Encounter "memory budget exceeded"

### ISSUE THREAD

**Issue by YulixinGitHub** [cockroachdb/cockroach#77465]
**Describe the problem**

the Cockroach cluster was upgraded from V20.0 to V21.1, then to V21.2,
two/three days later, it encounter "memory budget exceeded",
though we added more memory and cpu, it still happen about one twice every three days.

we found that the "SQL memory" was increasing but was not reclaimed at the DB Console, it may be memory leak.
It need to restart the nodes to supply Service.

At one time, when it encounter "memory budget exceeded", we close all the client service and the session, about 2 hours, the SQL Memory still keeps but not release as the console show. the only way is just to restart the nodes.

I've collected the [debug zip bundle](https://www.cockroachlabs.com/docs/stable/cockroach-debug-zip.html) for this cluster and reviewed the diagnostic info, but cannot get the key.

**To Reproduce**
after upgraded to V21.2.5, the SQL Memory always keeps increase at the DB Console.

**Expected behavior**
is there any way to find the cause？
I get the log files by "cockroach debug" command, how to analyze them with this problem?

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version [e.g. 2.0.x]
 - Server OS: [e.g. Linux/Distrib]
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
What was the impact?

Jira issue: CRDB-13609

**Comment by YulixinGitHub** [comment]
Hi Blathers,
Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cockroachdb/cockroach"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月8日(星期二) 中午11:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cockroachdb/cockroach] SQL Memory Was Increasing Till It Encounter "memory budget exceeded" (Issue #77465)





 
Hello, I am Blathers. I am here to help you get the issue triaged.
 
Hoot - a bug! Though bugs are the bane of my existence, rest assured the wretched thing will get the best of care here.
 
I have CC'd a few people who may be able to assist you:
  
@cockroachdb/sql-observability (found keywords: DB Console)
  
If we have not gotten back to your issue within a few business days, you can try the following:
  
Join our community slack channel and ask on #cockroachdb.
 
Try find someone from here if you know they worked closely on the area and CC them.
  
🦉 Hoot! I am a Blathers, a bot for CockroachDB. My owner is otan.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yuzefovich** [comment]
This might be the same as the [support issue](https://github.com/cockroachlabs/support/issues/1481) I've been looking into.

**Comment by yuzefovich** [comment]
@YulixinGitHub would you be willing to try a custom binary of 21.2.5 with a possible fix (similar to what #79639 does)? If you're using docker, the binary is available at `us-docker.pkg.dev/cockroach-cloud-images/cockroachdb/cockroach:v21.2.5-2-g73a5f5e8ff`.

**Comment by msiebuhr** [comment]
We've been seeing a similar issue on our cockroach clusters after a 20.2.3 to 21.1.16 upgrade (`sum by (node) (sql_mem_root_current{...})` in Prometheus): 
![image](https://user-images.githubusercontent.com/330611/171616579-bdddc02d-bd8e-4070-ab0d-a4ea2f337cc0.png)

The "staircase" in the memory-graph seems related to our daily load-cycle. In other words, leakage seems fairly constant per query we're doing.

I've also experimented with barring nodes from getting traffic (i.e. removing it from DNS round-robin and then killing all non-cluster connections). Unfortunately, no memory got reclaimed that way.

We're now on 22.1, which unfortunately hasn't fixed the issue.

**Comment by yuzefovich** [comment]
@msiebuhr sorry to hear that you're running into this problem. If possible, it would be awesome if you could provide us with a reduced reproduction of this issue - unfortunately, we weren't able to reproduce this internally. I'm not aware of any workaround other than restarting the nodes once this "fake" leak get too high.

The good news is that we have a plausible theory of where the bug is (although we weren't able to confirm that either), so we could provide a custom binary for you to try if you're open to it.

**Comment by msiebuhr** [comment]
Thanks, @yuzefovich. We still don't know which app/query exactly is causing the issue (but are working on several leads).

We'll probably go for creating a small cluster and migrate a few likely-"naughty" applications there and see if we can reproduce. Once we have that, we are more open to trying your custom binary + have a smaller set of candidate apps/queries.

**Comment by yuzefovich** [comment]
@YulixinGitHub @msiebuhr I think we're likely to have identified the bug, and the relevant backports should land on [22.1](#84089) and [21.2](#84325) branches soon.

**Comment by yuzefovich** [comment]
Closing as fixed by #83678.

**Comment by msiebuhr** [comment]
A quick confirmation that 22.1.5 seems to have solved our memory issues.
