### ISSUE TITLE
Like or prefix queries on GIN indexes.

### ISSUE THREAD

**Issue by oliverkofoed** [cockroachdb/cockroach#77484]
**Is your feature request related to a problem? Please describe.**
GIN indexes only allow exact contain(s|ed) queries. It would be great if they supported  prefix or LIKE searches.

Why would this be nice? Imagine a table with Dogs and wanting to find dogs by their nicknames. Dogs, like humans, can have many names, so it would be natural to model that in a []string field with a GIN index.

However, then you can only find dogs if you know the exact name. If the user types "Mr. ", he won't get the results for "Mr. Fussyfoot the Second". 

The need generalises to any entity where it would be nice to attach a list of keywords or search terms, to allow for user searching.

**Describe the solution you'd like**
"select * from table_name where gin_array_column like 'abc%'" for a prefix search.
"select * from table_name where gin_array_column like '%abc%'" for a sub-contains search. 

**Describe alternatives you've considered**
Building the "index" myself with a separate table, where each row is [other_table_primary_id, search_term]. Maintaining/keeping in sync/querying this table is just a hassle.

Jira issue: CRDB-13619

**Comment by mgartner** [comment]
Trigram indexes (see https://github.com/cockroachdb/cockroach/pull/79705) are coming in v22.2 which should support the queries mentioned above. For example:

```
defaultdb> CREATE TABLE t (k INT PRIMARY KEY, s STRING, INVERTED INDEX (s gin_trgm_ops));
CREATE TABLE

defaultdb> INSERT INTO t VALUES (1, 'hello world');
INSERT 0 1

defaultdb> EXPLAIN SELECT * FROM t WHERE s LIKE 'hello%';
                    info
---------------------------------------------
  distribution: local
  vectorized: true

  • filter
  │ filter: s LIKE 'hello%'
  │
  └── • index join
      │ table: t@t_pkey
      │
      └── • inverted filter
          │ inverted column: s_inverted_key
          │ num spans: 3
          │
          └── • scan
                missing stats
                table: t@t_s_idx
                spans: 3 spans
(17 rows)

defaultdb> SELECT * FROM t WHERE s LIKE 'hello%';
  k |      s
----+--------------
  1 | hello world
(1 row)

defaultdb> EXPLAIN SELECT * FROM t WHERE s LIKE '%llo%';
             info
------------------------------
  distribution: local
  vectorized: true

  • filter
  │ filter: s LIKE '%llo%'
  │
  └── • index join
      │ table: t@t_pkey
      │
      └── • scan
            missing stats
            table: t@t_s_idx
            spans: 1 span
(13 rows)

defaultdb> SELECT * FROM t WHERE s LIKE '%llo%';
  k |      s
----+--------------
  1 | hello world
(1 row)
```
