### ISSUE TITLE
Retry logic for schema registry appears broken

### ISSUE THREAD

**Issue by steven-hubbard** [cockroachdb/cockroach#77480]
POSTs sent as part of a retry contain no body. Steps to reproduce:

1. Create a changefeed to a kafka sink using a schema registry
2. CRDB goes to register a schema
3. The schema registry returns 200 but only the ID due to an invalid body (due to a malformed request)
4. CRDB issues retries but all subsequent retries only contain the ID, no body.

I think retries [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/changefeedccl/schema_registry.go) are broken because the first attempt consumes the bytes.Buffer, so subsequent attempts are made with an empty POST body

Jira issue: CRDB-13618

**Comment by miretskiy** [comment]
> I think retries [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/changefeedccl/schema_registry.go) are broken because the first attempt consumes the bytes.Buffer, so subsequent attempts are made with an empty POST body

I don't think that's true.  http Post creates new reader for the buffer.

**Comment by jayshrivastava** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/98135
