### ISSUE TITLE
protectedts: switch backup, changefeed tests to use the new protected timestamp subsystem 

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#77495]
**Describe the problem**

Now that everything laid out in https://github.com/cockroachdb/cockroach/issues/73727 has landed, we have an end to end implementation for the new protected timestamp subsystem. This should allow us to switch over existing tests to leverage the new subsystem instead of the old one. This entails flipping: 

https://github.com/cockroachdb/cockroach/blob/6ea1c5eefb67080c6637baac4cda1f5dab1a9787/pkg/kv/kvserver/protectedts/testing_knobs.go#L18-L24

and fixing whatever the falls out as a result.

Jira issue: CRDB-13621

**Comment by adityamaru** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/77478
