### ISSUE TITLE
ui: navigating between SQL Activity Tabs causes page to crash

### ISSUE THREAD

**Issue by Azhng** [cockroachdb/cockroach#77509]
Reproduced on CC Console. 

https://user-images.githubusercontent.com/9267198/157331284-1f984363-3fed-4aba-b9e3-06ea3cb3b5fd.mov

Jira issue: CRDB-13626

**Comment by jocrl** [comment]
Actually, @Azhng, does this still repro for you? If so, does it still repro if you load the page in a new tab?

**Comment by Azhng** [comment]
> Actually, @Azhng, does this still repro for you? If so, does it still repro if you load the page in a new tab?

Yes this is still reproducible for me on CC Console (running 22.1 alpha 3). It's also reproducible if I load the page in a new tab.

Hmm I  will try to use the disconnected frontend to try to load a source map.

**Comment by Azhng** [comment]
Hmm looping back, I spinned up a local frontend pointing to the staging and this bug is gone, it is possible that this has been patched in the new `cluster-ui`.

**Comment by jocrl** [comment]
Oh! Does your environment still error with the staging frontend? I'd love to pair to debug (please keep the environment! hahaha).
I suspect that the local frontend doesn't error because the error has something to do with the state of your local storage. Which is scoped to staging; and your localhost:8081 is clean.

**Comment by jocrl** [comment]
Just bumping that I ran into this again (second time now). I think it's a pretty easy state to get into
<img width="1493" alt="image" src="https://user-images.githubusercontent.com/91907326/159797275-447d0092-3755-437e-9416-7294ee812cb0.png">
