### ISSUE TITLE
bazel: run `go mod tidy` when updating `vendor`

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#77515]
Reporting on behalf of @erikgrinaker.

> I updated some dependencies in go.mod, ran a build, and then ran dev gen bazel --mirror to update the vendor dependency tracking. However, this did not appear to run go mod tidy, and CI then fails when checking this. We should run go mod tidy when updating dependencies.

Epic CRDB-17171
Jira issue: CRDB-13687

**Comment by rickystewart** [comment]
`build/README.md` has instructions on how to make `vendor` changes FYI. The instructions make clear that `go mod tidy` is a separate step.

Having `dev generate bazel` run `go mod tidy` is a non-starter I think. Having `dev generate bazel --mirror` run `go mod tidy` could make sense -- whenever you're running it you have probably updated `go.mod` so `go mod tidy` could be necessary. On the other hand it can be a destructive operation if you're not expecting it. I could go either way on whether this is worth implementing.

**Comment by erikgrinaker** [comment]
Thanks for moving the issue!

>I could go either way on whether this is worth implementing.

Well, it seems pointless to have to do this manually when we could automate it -- especially when the penalty for forgetting it is another CI roundtrip. We're essentially always going to be doing this when we update `vendor`.

I agree that `dev gen bazel` is awkward though. We could consider a `dev vendor` command which does everything necessary to update the vendoring, including dispatching to `gen bazel --mirror`.

> On the other hand it can be a destructive operation if you're not expecting it.

`make vendor_rebuild` called into `go mod tidy`, so presumably noone have been too bothered by this.

**Comment by erikgrinaker** [comment]
> > On the other hand it can be a destructive operation if you're not expecting it.
> 
> `make vendor_rebuild` called into `go mod tidy`, so presumably noone have been too bothered by this.

Actually no, it didn't -- I must've misremembered. Anyway, still seems like an improvement, but your call.

**Comment by rickystewart** [comment]
No more `vendor`.
