### ISSUE TITLE
sql: ensure we are choosing a safe split key when splitting hash sharded indexes

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#77529]
**Describe the problem**

Hash sharded indexes are split before they are backfilled.  When splitting indexes, callers need to call `keys.EnsureSafeSplitKey` to make sure we aren't splitting the index entries for a single row across two ranges.  It appears we don't currently call this function here:

https://github.com/cockroachdb/cockroach/blob/f344d07a70a072d04dd075f8aba033c5758fee63/pkg/sql/schema_changer.go#L3068-L3069

I haven't verified that there isn't some other invariant that makes this code OK, but we should double check it.

It might also be worth checking for bad split keys in `SplitAndScatter` itself.  The kvserver currently checks for some cases of bad split keys: 

https://github.com/cockroachdb/cockroach/blob/e7e596ede9d3da877e313a3d39ab498a5cb7d27b/pkg/kv/kvserver/replica_command.go#L375 

but that check doesn't cover the case of splitting inside the entries for a row.

Jira issue: CRDB-13637

**Comment by stevendanna** [comment]
@chengxiong-ruan This seems like something you might be interested in.  I don't have a reproduction of an actual problem here, but this came up when discussing other bugs related to bad splits.

**Comment by ajwerner** [comment]
I feel like these splits are safe by construction, no?

**Comment by stevendanna** [comment]
This was filed to keep track of a discussion here (https://cockroachlabs.slack.com/archives/C2C5FKPPB/p1646750279542579), but on inspection I think you are correct, since this is splitting at the shard boundaries I don't think there is a problem.

**Comment by chengxiong-ruan** [comment]
thanks for raising this @stevendanna, but yeah, we only split at shard boundaries and should never cut a row into two halves. Closing this for now.
