### ISSUE TITLE
sql: altering primary key to be hash sharded not to rewrite secondary indexes

### ISSUE THREAD

**Issue by chengxiong-ruan** [cockroachdb/cockroach#77537]
**Is your feature request related to a problem? Please describe.**
`ALTER TABLE ... ALTER PRIMARY KEY` rewrites secondary indexes if pk key columns has changed. This make sense since we store pk columns not indexed by secondary indexes. However, when altering primary key to use same key columns but hash sharded, we can avoid rewriting secondary indexes since we only add a shard column which is virtual and the other columns stay the same.

**Describe the solution you'd like**
Avoid secondary index rewriting when just altering a pk to be hash sharded with same key columns. Though this means that query execution need to be smart enough to compute the shard/virtual column when secondary index is scanned.

Jira issue: CRDB-13642

**Comment by ajwerner** [comment]
Some internal context: https://cockroachlabs.slack.com/archives/CARM0PTK4/p1646767108417609

I don't think we want to do this, the optimizer assumes there's a physical key there. It's fine.
