### ISSUE TITLE
easy reliable way to backup/restore data

### ISSUE THREAD

**Issue by remdragon** [cockroachdb/cockroach#77557]
**Is your feature request related to a problem? Please describe.**
Needed to perform some complicated sql queries to fix a problem, needed a way to backup/restore the data in case we made mistakes with the sql repairs

**Describe the solution you'd like**
a simple command to backup/restore a table, something like:

cockroach sql -d fusionpbx -e select * from v_dialplans' --format=dump

The command should differ from -format=sql in the following ways:
* instead of CREATE TABLE it should be CREATE TABLE IF NOT EXISTS
* it should NOT convert NULL to 'NULL'
* either execute a delete from where 1=1 before executing all the inserts, or perform upserts?
* use the actual table name instead of "results"

**Describe alternatives you've considered**

* tried cockroach dump, but even though it's only listed as deprecated, I was told command not found

* tried EXPORT INTO and it said it generated a file but could never find the file

* eventually used the following command with caveats:
** cockroach sql --certs-dir=/usr/local/cockroach/certs -d fusionpbx -e 'select * from v_dialplans' --format=sql | sed "s/CREATE TABLE/CREATE TABLE IF NOT EXISTS/g" | sed "s/'NULL'/NULL/g" | sed "s/results/v_dialplans/g" >v_dialplans.sql

The caveats are that I still had to hand-edit the sql file and add the following before the inserts: delete from v_dialplans where 1=1;

Additional caveat is that this is for a real-time 24/7 system, and this sequence leaves the system broken between the time the delete query runs and all the insert statements get executed

**Additional context**
Running v21.2.4

Jira issue: CRDB-13654

**Comment by msbutler** [comment]
@remdragon see our docs on [Backup](https://www.cockroachlabs.com/docs/stable/backup.html ) and [Restore](https://www.cockroachlabs.com/docs/stable/restore.html) functionality. After reading through these docs, and you have further questions, I encourage you to ask on [forum](https://forum.cockroachlabs.com/).
