### ISSUE TITLE
changefeedccl: Drop env gate for metrics_label

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#77553]
drop restriction requiring env variable set when using metrics label.

Jira issue: CRDB-13650

**Comment by ajwerner** [comment]
This seems like a very bad idea. Namely, it opens up a pretty bad threat model to cockroach cloud serverless. We'd have no way to prevent a bad actor from blowing out our metric cardinality budget.

**Comment by miretskiy** [comment]
hmm... perhaps switch to default enabled?  Another possibility is to move it to startup flag to disable/enable...?

**Comment by ajwerner** [comment]
I don't know how to voice my opposition to user-controlled labels in a cloud setting without becoming the gate-keeper here. Somebody from cloud should sign off on this, at the very least.
