### ISSUE TITLE
changefeedccl: imprecise handling of cursor

### ISSUE THREAD

**Issue by stevekuznetsov** [cockroachdb/cockroach#77563]
I am investigating CockroachDB changefeeds and I have noticed some confusing behavior that I would like to understand better. I have a standalone reproducer program [here](https://gist.github.com/stevekuznetsov/e17d574cade6ce6ea7f914885c432b68) that can be run to see what I am talking about.

In this program, I run an in-memory CRDB instance using the test server package. After initializing the cluster and adding a table, I run 25 row queries, either inserting a row, updating an existing row, or deleting an existing row. Then, I attempt to create a changefeed from every single HLC timestamp that occurred from the above actions. I expect each changefeed to see the correct subset of events (the first should see all events, the last should see only the last event).

In my local testing, this program produces a number of errors:

 - some changefeeds see events before the `cursor` provided to the `EXPERIMENTAL CHANGEFEED` command
 - some changefeeds do not see the first two events that they should see given their `cursor`

I'm hoping to understand these errors and why the behavior I'm seeing is happening, I am not entirely certain that the behavior is errant yet. I imagine there's some setting I might need to change for the specificity of the changefeed cursor.

Jira issue: CRDB-13657

**Comment by stevekuznetsov** [comment]
I added a `time.Sleep(10 * time.Second)` between the events I was generating in order to test the theory that there was some fuzziness to the changefeed cursor, and saw the same results, so I don't think that is what I'm seeing. This is also the single-node in-memory test server, so I can't image there is a difference between the cluster timestamp and the node's timestamp?

**Comment by ajwerner** [comment]
We have some pretty extreme testing of the precision of the changefeed correctness with regards to MVCC history. Without having read the client, my strong suspicion is that something in the handling there is amiss. Sorry nobody has gotten around to looking just yet.

**Comment by stevekuznetsov** [comment]
@ajwerner thanks for the response - I'm on the Slack channels if you end up having a moment to look into this and want to chat about it. I've traced the feed code down to [this line](https://github.com/cockroachdb/cockroach/blob/ce4f6df380d931cda306d037988275081b3b2317/pkg/ccl/changefeedccl/schemafeed/schema_feed.go#L367) and I can't see how it's possible for this comparison to be wrong ...

**Comment by stevekuznetsov** [comment]
Ah sorry ... finally found the client error. I was accounting for the non-ordered events between rows incorrectly. Sorry!
