### ISSUE TITLE
Flaky Test: TestGCDropIndexSpanExpansion in pkg/ccl/backupccl/backup_test.go

### ISSUE THREAD

**Issue by benbardin** [cockroachdb/cockroach#77569]
TestGCDropIndexSpanExpansion in pkg/ccl/backupccl/backup_test.go may be flaky.

Examples:
[example1](https://teamcity.cockroachdb.com/repository/download/Cockroach_Ci_Tests_Testrace/4527731:id/bazel-testlogs/pkg/ccl/backupccl/backupccl_test/test.log), [example2](https://teamcity.cockroachdb.com/repository/download/Cockroach_Ci_Tests_Testrace/4529056:id/bazel-testlogs/pkg/ccl/backupccl/backupccl_test/test.log), [example3](https://teamcity.cockroachdb.com/repository/download/Cockroach_UnitTests_Testrace/4530190:id/raw.0.json.txt.tgz!/artifacts/full_output.txt)

A rebase resolved this, at least temporarily.

**Comment by stevendanna** [comment]
This test was recently modified to be skipped under race which likely accounts for why the rebase fixes it https://github.com/cockroachdb/cockroach/commit/2ec4b38bec363dc57a77ba97e732f23385f68f45

**Comment by stevendanna** [comment]
The error in these failures is:

```
    backup_test.go:9391: error executing 'BACKUP INTO 'nodelocal://0/foo' WITH revision_history': pq: failed to run backup: exporting 13 ranges: exporting /Table/106/{2-4}: batch timestamp 1646762963.956389651,0 must be after replica GC threshold 1646762964.579495101,0
```

This test DROPs an index and then arranges via testing hooks for the GC of that table to be delayed. So, when taking the backup, the test assumes that we should definitely be above the gc threshold still.
