### ISSUE TITLE
gcjob: use the MarkIdle API when waiting for TTL

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#77576]
**Is your feature request related to a problem? Please describe.**

The GC job mostly waits around. It is quintessentially idle most of the time. It should mark itself as idle using [#74747 jobs: Add MarkIdle API](https://github.com/cockroachdb/cockroach/issues/74747). 

**Describe the solution you'd like**

When not actively GC'ing data, we should be marking the job as idle. 

**Additional context**

This will help with scale to zero. This does have the somewhat sad side-effect that the data won't be collected until the tenant is live again. That'll be fixed in 22.2 when we use the DelRange operator. 

Jira issue: CRDB-13661

**Comment by ajstorm** [comment]
@otan Would we also need to do this for each table's TTL job?  If so, is that a separate issue?  Or do you want to fix it under this issue?

**Comment by otan** [comment]
Not applicable for TTL - it is either working or the job would be marked as completed. I think the gc job actually pauses whilst doing requests.
