### ISSUE TITLE
storage: Reconsider locking in Store.Send

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#7757]
`Store.GetReplica()` acquires and releases `Store.mu` and returns a pointer to a `Replica`. Unless this is called under `Store.processRaftMu`, the replica could be destroyed while in use. Specifically, `Store.Send` uses `GetReplica` and then calls `Replica.Send`.

We need to either ensure that all methods on `Replica` fail gracefully when the replica is destroyed while in use, or ensure that some lock is held throughout the execution of any methods on the Replica which will prevent its destruction. No existing lock is suitable for this purpose (it needs to be a `RWMutex` to allow multiple concurrent reads), so we'd need to introduce a new one.

**Comment by andreimatei** [comment]
dupe of #7169 ?

**Comment by bdarnell** [comment]
Yeah.
