### ISSUE TITLE
builtins: implement to_timestamp

### ISSUE THREAD

**Issue by andyli** [cockroachdb/cockroach#77591]
**Describe the problem**

To use a timestamp value in decimal, in Postgres, I use the `to_timestamp()` function as follows
```sql
select to_timestamp(1646906263.278);
```

Since cockroach doesn't have `to_timestamp()`, I use a cast instead:
```sql
select 1646906263.278::timestamptz;
```
But it results in `SQL Error [42846]: ERROR: invalid cast: decimal -> timestamptz`

Casting an integer to timestamptz works, thought it loses precision:
```sql
select 1646906263::timestamptz; # removed .278
```

**Environment:**
 - CockroachDB CCL v21.2.6 (x86_64-unknown-linux-gnu, built 2022/02/22 18:30:37, go1.16.6)

----

Instructions for contributors:

Add a built-in in https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/builtins.go
Add a test in https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/timestamp, and run make testbaselogic FILES='timestamp' TESTFLAGS='-rewrite' to test it.
Run make buildshort to regenerate automatically generated files.
Submit a PR.

----

Jira issue: CRDB-13671
Epic CRDB-14049

**Comment by otan** [comment]
thanks! i think our preference here is to implement `to_timestamp`, so changed accordingly.

**Comment by deepto98** [comment]
Hi, can I pick this up?

**Comment by rafiss** [comment]
@deepto98 sure, it's best if you go ahead and submit a PR as per the instructions in the issue, and following our [contribution guidelines](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73204033/Contributing+to+CockroachDB)

**Comment by simplenotezy** [comment]
Just curious, when will this be released?

**Comment by rafiss** [comment]
@simplenotezy This will be a part of the v22.2 release. There are beta versions available for you to test with: https://www.cockroachlabs.com/docs/releases/v22.2.html
