### ISSUE TITLE
kv: Gossip additional store health and load signals

### ISSUE THREAD

**Issue by kvoli** [cockroachdb/cockroach#77604]
**Is your feature request related to a problem? Please describe.**

Currently, [allocator](https://github.com/cockroachdb/cockroach/blob/960f2b4f7d026b5a5ef8e59a3efc7a0e63f837e5/pkg/kv/kvserver/allocator.go#L513) and [store rebalancer](https://github.com/cockroachdb/cockroach/blob/960f2b4f7d026b5a5ef8e59a3efc7a0e63f837e5/pkg/kv/kvserver/store_rebalancer.go#L253-L253) decisions are made using measurements of the *replicas the store contains* and information of other stores that is gossipped around.

These measurements currently comprise:

**store (gossiped)**
```
# usage
queries per second (batch requests)
writes per second (keys mutated)
ranges            (on the store)

# health
disk fullness (%)
liveness (not dead or suspected)

# locality
location
```

**replica (not gosipped)**

```
# usage
queries per second (batch request)
writes per second (keys mutated)
```

It is desirable to enable experimentation with additional measurements, to be used as inputs in allocation and rebalancing decisions. 

**Describe the solution you'd like**

Gossip additional store load and health signals; so that they may be used as inputs for allocation decisions. Previous work has included a subset of health signals [#77040](https://github.com/cockroachdb/cockroach/pull/77040). This issue proposes including these additional measurements, to be used as signals of store load and health:

**store (gossiped)**
```
# usage
cpu use (utilization % * available cores, EWMA or percentiles 50/67/95/99)
read throughput (bytes, EWMA or percentiles 50/67/95/99)
write throughput (bytes, EWMA or percentiles 50/67/95/99)

# health
L0 sub-levels
disk stalls (number of disk operations taking longer than 30s, sliding window)
disk slow (number of disk operations taking longer than 10s, sliding window)
```

Gossiping these measurements of store load and health may then be used as inputs in evaluating other allocation/rebalancing strategies compared to current. Related to #70552.

**Describe alternatives you've considered**

Avoid gossiping any new values until we have a corresponding issue for their inclusion in allocation or rebalancing decisions. Currently only a portion of the store health statistics have immediate uses as constraints to avoid considering an unhealthy store as a replication target.

This issue could in addition include:

```
reads per second (keys read)
```

**Additional context**

Additional work is being planned to enable quick testing of allocation strategies #70552, this issue compliments that work by providing an expanded set of inputs in order to evaluate strategies that depend upon resource level signals (cpu/throughput), rather than proxies (qps).

cc: @shralex @irfansharif @lidorcarmel 

Jira issue: CRDB-13676

Epic CRDB-14989

**Comment by kvoli** [comment]
> We could balance additional store health signals, but I'm not sure if the allocator cares as much about which store health signal is firing as opposed to a boolean or confidence interval of "node N" is unhealthy.

I agree. However it seems preferable to accumulate this information at the receiver rather than the sender? This issue only proposes propagating this information, not necessarily how it is parsed and used.

> how healthy its network links are (see https://github.com/cockroachdb/cockroach/issues/49220)

That certainly seems like a missing, yet important health signal here.

> flesh out a more general failure detector library 

If we did go down this route, it would simplify the logic of the allocator and rebalancer.

**Comment by irfansharif** [comment]
I don't see much benefit to broadcasting additional signals without having a clear picture of how we're intending to use it. Feels to me we're working forwards towards an unspecified end state instead of backwards. We could certainly do it, but I don't think the complexity stems from adding additional keys to gossip -- that's the easy part.

**Comment by shralex** [comment]
We talked with Austen offline and decided to only broadcast only the L0 sub-levels metric for now, that we can probably directly use for 22.1 release as a constraint.

**Comment by kvoli** [comment]
> I don't see much benefit to broadcasting additional signals without having a clear picture of how we're intending to use it. 

I agree, however with the assumption that this issue lays out an intent. We **do intend** to use the above measurements (or at least experiment with, given it's impossible to know the result without checking and comparing). Only when we are ready to however, should we begin broadcasting them. You are right it is only a ~40 line change each time, so it is not where the complexity resides.

I intended more for this issue to act as a tracker for aggregating these additional measurements. 

Perhaps an additional and related topic here is creating a cleaner interface for *when to gossip*. Currently we do so periodically but also when a (large enough) change occurs.

capacity:

https://github.com/cockroachdb/cockroach/blob/960f2b4f7d026b5a5ef8e59a3efc7a0e63f837e5/pkg/kv/kvserver/store.go#L2526-L2530

or load changes:

https://github.com/cockroachdb/cockroach/blob/960f2b4f7d026b5a5ef8e59a3efc7a0e63f837e5/pkg/kv/kvserver/store.go#L2559-L2562

**Comment by kvoli** [comment]
Closing in favor of #103320
