### ISSUE TITLE
cdc: properly handle duplicate table names within the same feed

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#77647]
Handle it well when the same table name appears in multiple schemas/databases. Requires a change to backupresolver to do cleanly since we don't currently return a way to map descriptors back to the unresolved names they correspond to.

Jira issue: CRDB-13694

**Comment by miretskiy** [comment]
@HonoreDB  -- there were some changes by you to the backup resolver recently(ish).  Is this still an issue?

**Comment by HonoreDB** [comment]
Sorry, no, those changes addressed this, closing.
