### ISSUE TITLE
make check: remove TestSafeSQL

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#7765]
This is a test that takes forever to run and is hurting productivity. Is there a way we can run it on CI but not locally?

**Comment by petermattis** [comment]
You don't have to run `make check` locally. You can run `make build test acceptance`.

Also, I experimented with translating `check-style.sh` to Go and then parallelizing the checks. See https://github.com/cockroachdb/cockroach/compare/master...petermattis:pmattis/check-style?expand=1. It gave a modest performance boost and timings for each check, but didn't seem significant enough to push further on. If anyone wants to pick it up, be aware that you'll have to incorporate recent changes to `check-style.sh`.

**Comment by bdarnell** [comment]
In addition to being slow, it's not very sensitive. We do unsafe things in a number of places and it hasn't flagged any of them. It's not currently worth the trouble so I'd support removing it from `check-style.sh`.

**Comment by RaduBerinde** [comment]
It is useful to run `make check` locally, it regularly finds small issues (leftover struct members, undocumented exports) and it's faster to figure them out before posting the PR. I can give this a shot.

**Comment by jordanlewis** [comment]
FYI, #8424 parallelizes `check-style.sh` if you have GNU parallel installed. I don't see a big need to rewrite in Go when you can just use a utility.
