### ISSUE TITLE
Investigate and fix SQL Activity page request errors surfacing through Datadog

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#77678]
Issue outlined here: https://cockroachlabs.atlassian.net/wiki/spaces/SQLOBS/pages/2469232771/Datadog+Telemetry+Data

Jira issue: CRDB-13709

**Comment by maryliag** [comment]
Specific issues have been created for each specific error and this is now part of on-call, so closing this issue
