### ISSUE TITLE
use inverted index when `->>` operator is used

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#77672]
Currently, inverted indexes aren't chosen when the `->>` operator is used to select JSON elements:

```
> SHOW CREATE TABLE t;
  table_name |              create_statement
-------------+---------------------------------------------
  t          | CREATE TABLE public.t (
             |     a INT8 NOT NULL,
             |     b JSONB NOT NULL,
             |     CONSTRAINT t_pkey PRIMARY KEY (a ASC),
             |     INVERTED INDEX t_b_idx (b)
             | )

> EXPLAIN SELECT * FROM t WHERE b->>'a' = 'b';
                                       info
-----------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • filter
  │ estimated row count: 0
  │ filter: (b->>'a') = 'b'
  │
  └── • scan
        estimated row count: 1 (100% of the table; stats collected 3 minutes ago)
        table: t@t_pkey
        spans: FULL SCAN
(11 rows)

> EXPLAIN SELECT * FROM t WHERE b->'a' = '"b"';
                                       info
-----------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • index join
  │ estimated row count: 0
  │ table: t@t_pkey
  │
  └── • scan
        estimated row count: 1 (100% of the table; stats collected 3 minutes ago)
        table: t@t_b_idx
        spans: 1 span
(11 rows)
```

This operator isn't listed as supported on this page https://www.cockroachlabs.com/docs/v21.2/inverted-indexes.html#comparisons so it isn't a bug, but it would be nice to support if possible since it isn't obvious at first
why the index isn't used.

Jira issue: CRDB-13707

**Comment by cucaroach** [comment]
Should this be added to https://github.com/cockroachdb/cockroach/issues/59331 meta bug?

**Comment by mgartner** [comment]
In my opinion, this isn't a bug or limitation and I think this issue should be closed. `->>` returns a `STRING`, so there's no way to use an inverted index for this query, unless you could prove that for every row with column `j`, an expression `j->s` always results in a JSON string. We can't use an inverted index to find matches to a string that contains multiple JSON paths, so if `j->s` results in an object or array for any row, then we can't use an inverted index for `j->>s`.

**Comment by mgartner** [comment]
I'll go ahead and close, but I'm curious to hear any disagreements and can re-open if necessary.
