### ISSUE TITLE
pcr: catchup scan checkpointing in streaming replication

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#77695]
Streaming replication should support checkpoints during catchup scans.

When the rangefeed library sees range resolve timestamp advance past 0, it should
invoke user provided callback with the range/timestamp checkpoint.
The caller may want to checkpoint progress for long running catchup scans.

CRDB-8666

Jira issue: CRDB-13719

Epic CRDB-19402

**Comment by ajwerner** [comment]
I'm sort of meh on this as an issue. We already have an easy way to track these. When the catchup scan completes, we get a checkpoint for the underlying span. I don't think we need to change the rangefeed library at all to accumulate these above it. 

As another point: I wouldn't make this checkpointing that we're talking about specifically about catchup scans at all. We should just have a frontier that isn't initialized from the cursor somewhere so we can find the things which have not finished their catchup scan.

**Comment by miretskiy** [comment]
Perhaps that's not necessary, but replication streaming is the customer of that library.  And so ,I worry we will need
to do longer catchup scans there.  I guess this can move to replication streaming specifically, since we will need to implement the same logic (as in changefeed).

**Comment by ajwerner** [comment]
I still don't follow. The library gives you checkpoints, including following a catchup scan.

**Comment by ajwerner** [comment]
If maybe you're saying that we should unify the data structure in which we collect the checkpoints, yes, we should do that, but I don't know that it needs to be underneath the library as opposed to on top of.

**Comment by shermanCRL** [comment]
@gh-casper mentions this is likely to go into August instead of July, I have moved it. cc @liv to reflect this is Jira.
