### ISSUE TITLE
21.2 GRANT ON DATABASE backward compatibility re-write does not include sequences

### ISSUE THREAD

**Issue by sheaffej** [cockroachdb/cockroach#77708]
**Describe the problem**

In 21.1 issuing `GRANT select, update ON DATABASE xxx TO user` would allow the user to read sequences in the database.

In 21.2, this statement is re-written to the newer ALTER DEFAULT PRIVILEGES statement, but it no longer covers sequences. And for a user to access the sequence, the user must be granted select and update specifically on the table backing the sequence.

Related to: https://github.com/cockroachdb/cockroach/issues/74780

**To Reproduce**
In 21.1:
```
-- As an admin user
demo@127.0.0.1:26257/defaultdb> create user testuser with password testuser;
CREATE ROLE

demo@127.0.0.1:26257/defaultdb> create database test;
CREATE DATABASE

demo@127.0.0.1:26257/defaultdb> use test;
SET

demo@127.0.0.1:26257/test> grant select, insert, update, delete on database test to testuser;
GRANT

demo@127.0.0.1:26257/test> create sequence myseq;
CREATE SEQUENCE


-- As the testuser
testuser@127.0.0.1:26257/test> select nextval('myseq');
  nextval
-----------
        1
(1 row)
```
Note: To repro, the sequence needs to be created after the grants on database are issued.

In 21.2:
```
-- As an admin user
j4@j4-mr-demo/defaultdb> create user testuser with password testuser;
CREATE ROLE

j4@j4-mr-demo/defaultdb> create database test;
CREATE DATABASE

j4@j4-mr-demo/defaultdb> use test;
SET

j4@j4-mr-demo/test> grant select, insert, update, delete on database test to testuser;
NOTICE: GRANT SELECT, INSERT, UPDATE, DELETE ON DATABASE is deprecated.
This statement was automatically converted to USE test; ALTER DEFAULT PRIVILEGES GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO testuser;
Please use ALTER DEFAULT PRIVILEGES going forward
GRANT

j4@j4-mr-demo/test> create sequence myseq;
CREATE SEQUENCE


-- As the testuser
testuser@j4-mr-demo/test> select nextval('myseq');
ERROR: nextval(): user testuser does not have UPDATE privilege on relation myseq
SQLSTATE: 42501


-- As the admin user again
j4@j4-mr-demo/test> grant select, update on test.myseq to testuser;
GRANT


-- As the testuser again
testuser@j4-mr-demo/test> select nextval('myseq');
  nextval
-----------
        1
(1 row)
```

**Expected behavior**
In 21.2, the use of `GRANT select, update ON DATABASE test TO testuser` should include granting of default permissions to the tables underlying newly created sequences in order to allow compatibility with the pre-21.2 GRANT x ON DATABASE syntax.

**Impact**
Customer applications written to use the 21.1 database-level permission model are encountering errors when accessing sequences in 21.2. To upgrade to 21.2, the application must be modified to grant permissions directly to the table backing the sequence.

**Environment:**
```
 j4@j4-mr-demo/test> select version();
                                          version
-------------------------------------------------------------------------------------------
  CockroachDB CCL v21.2.6 (x86_64-unknown-linux-gnu, built 2022/02/22 18:30:37, go1.16.6)
(1 row)
```

Jira issue: CRDB-13730

**Comment by rafiss** [comment]
Apologies @sheaffej it looks like this fell through the cracks since it didn't end up on any team's board. Since v21.2 is no longer getting regular releases, do you think we still should fix this?
