### ISSUE TITLE
changefeed: Expand monitoring metrics

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#77702]
- [ ] Keep track of message size distributions
- [ ] Aggregate sink type specific metrics (i.e. add a sink type label)
- [ ] Catchup scan observability

Jira issue: CRDB-13724

**Comment by steven-hubbard** [comment]
Can we also add the functionality to be able to monitor the volume that needs to be emitted in the event that the sink is down or the change feed is unable to keep up with the data coming into the cluster?

**Comment by miretskiy** [comment]
Closing this issue.
Message size distribution and catchup observability has been addressed.
Per sink label might be nice, but not required -- you can use changefeed
metrics labels to get this aggregation.
