### ISSUE TITLE
sql: enable changing the version setting of a tenant from another tenant

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#77733]
This is a followup to #73857, to be interpreted in the context of #77935.

We would like the ability to run `ALTER TENANT x SET CLUSTER SETTING version = XXX`
and have this statement trigger the SQL migrations for the target tenant.

However doing so is made more complex by the fact that the SQL server which is running ALTER TENANT SET CLUSTER SETTING does not have visibility over the target tenant keyspace directly and so cannot trigger the SQL migrations itself.

Instead, we should probably design some kind of RPC by which the target tenant "learns" of the version change.

### Workaround

Until this issue is fixed, a DBA who wants to upgrade the logical version of a tenant should log into that tenant and run the SET CLUSTER SETTING statmeent in the context of that tenant.

Jira issue: CRDB-13742

Epic CRDB-14080

**Comment by knz** [comment]
cc @ajstorm for triage

**Comment by ajwerner** [comment]
>Until this issue is fixed, a DBA who wants to upgrade the logical version of a tenant should log into that tenant and run the SET CLUSTER SETTING statement in the context of that tenant.

Absolutely not! This version setting is carefully and subtly tied into the online version migration protocol. One cannot just set the logical version of a tenant. There is serious machinery underneath that code:

https://github.com/cockroachdb/cockroach/blob/94e7590aa3c667045ebac33002854689de60a3ac/pkg/sql/set_cluster_setting.go#L554-L557

**Comment by ajwerner** [comment]
I could see wanting to do the whole upgrade from the host cluster, but then I'd really really want to see the guardrails suggested in https://github.com/cockroachdb/cockroach/issues/66606 completed.

**Comment by RaduBerinde** [comment]
In general, any ask for functionality that is achievable by spinning up a tenant pod and running a statement should not result in new special code in the system tenant. We should instead invest in a more convenient general way of spinning up a temporary tenant process and delegating to that.

**Comment by knz** [comment]
@JeffSwenson informs us that this issue would be nice-to-have for the 22.2 release.

**Comment by knz** [comment]
We discussed this with @dt   

Generally, we're not very comfortable adding more mechanisms that dilute the boundary between tenants.

David's opinion is that we should invest in our interactive SQL shell to make it easier to "hop" a SQL session from one tenant to another. If we had that, a SRE could administrate the logical cluster version in that way, without a need for a new SQL construct.

**Comment by dt** [comment]
Another thing to keep in mind, specifically for this "setting the cluster version" use-case: changing the cluster version is not just setting a setting, but rather requires creating and then executing all of the applicable upgrade jobs that get advance the version from version x to x+1, x+2, ... and finally to version y. We almost certainly want a real, full-fledged and resource-controlled tenant-identified sql server to run these jobs, not just some internal executor in some process somewhere.

**Comment by knz** [comment]
Agreed.

All in all this work is too fuzzily defined with our current understanding of multitenancy. So we'll close the issue in  #85011.
