### ISSUE TITLE
spanconfig: don't generate splits for views

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#77744]
**Describe the problem**

Views use table descriptors, but are not physical tables. They should not have split points. If they did, it would be a regression.

**To Reproduce**

Create a view and wait.
**Expected behavior**
No split.

Jira issue: CRDB-13747

**Comment by ajwerner** [comment]
cc @arulajmani, I think this is a really easy fix.

**Comment by arulajmani** [comment]
Yup, we probably just need to filter out sequences/views in the SQLTranslator. I'll assign it to myself, thanks for filing!

**Comment by ajwerner** [comment]
I don't know, I could see separating sequences. They are physical tables that happen to be one row. I believe today they do get split.
