### ISSUE TITLE
sql: Return unique error code when statements error during an overload scenario

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/cockroach#77778]
CockroachDB has different work queues for admission control. During an overload scenario if a unique error code gets returned for statements that time out, then clients could add an appropriate exponential backoff strategy. If a cluster is overloaded, it might not make sense to continue hammering the cluster with requests.

[Discussion thread](https://cockroachlabs.slack.com/archives/C01SRKWGHG8/p1647276017836049?thread_ts=1647275808.176509&cid=C01SRKWGHG8)

Epic: CRDB-13762

Jira issue: CRDB-13764

**Comment by sumeerbhola** [comment]
Is the issue that we want to know that something timed out somewhere in the system, versus that it encountered some other error (I thought we could already tell the difference between various errors https://www.cockroachlabs.com/docs/stable/transaction-retry-error-reference.html)?

Or is this specifically about admission control timeouts? Or is it even more specific regarding which queue it was in when it timed out? And could you sketch out how a customer would use this for backoff -- this seems hard to use in a distributed database where a node may be hot (cpu or storage) but traffic not touching that node can proceed at its usual rate?

**Comment by aadityasondhi** [comment]
> Or is this specifically about admission control timeouts? Or is it even more specific regarding which queue it was in when it timed out? And could you sketch out how a customer would use this for backoff -- this seems hard to use in a distributed database where a node may be hot (cpu or storage) but traffic not touching that node can proceed at its usual rate?

Closing because it does not seem very actionable.
