### ISSUE TITLE
ui: timescale doesn't change URL query string

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#7778]
Query for cluster at the default timescale
http://104.196.56.219:8080/#/cluster?_k=d8kh28

Query for the cluster at the 1 day scale should represent that change so copy and pasting is easy.
http://104.196.56.219:8080/#/cluster?_k=d8kh28&timescale=1day

All selectable should be represented in the query string (where reasonable).

**Comment by maxlang** [comment]
Should we use ISO 8601 for this?

https://en.wikipedia.org/wiki/ISO_8601#Durations

**Comment by BramGruneir** [comment]
We could also use the golang ones, as long as it's consistent and clear.
