### ISSUE TITLE
ui: logs don't work

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#7779]
There's just and empty page.

**Comment by BramGruneir** [comment]
For motivation for this, I'd like to be able to see the logs quickly when running some of the allocator tests.  I can ssh into the boxes and what not, but it would be a lot nicer to just be able to see them directly.

**Comment by tschottdorf** [comment]
Probably not worth doing anything about before
https://github.com/cockroachdb/cockroach/issues/1779 (after which we should
also look into live streaming the log output buffer into the ui to avoid
malfunctioning in deployments that don't actually write files).
-- 

-- Tobias

**Comment by mrtracy** [comment]
Logs page currently works. I wouldn't say it's great or exceptionally useful, but it is technically working again.

Closing this, opened #13182 to more accurately record the current problems with the page.
