### ISSUE TITLE
server, ui: events should be filterable

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#7780]
- By time
- by type
- by regex
- by node

**Comment by maxlang** [comment]
Currently the events endpoint only takes a `target_id` or a `type_id`. UI work is blocked on expanding the endpoint to support these options.

**Comment by BramGruneir** [comment]
You can't filter locally for now?

**Comment by maxlang** [comment]
Fair enough. I could filter the most recent 1000 by time and regex locally. Node generally has no meaning. Type can already be filtered on the backend.

**Comment by maxlang** [comment]
Related work: #8247 and #8246

**Comment by tbg** [comment]
cc @couchand for triage

**Comment by tbg** [comment]
No, just didn't have a progress assigned (I'm going through the unowned backlog).

**Comment by knz** [comment]
The main issue here is that the event table is unstructured. We'd get a lot of mileage if it was.

@thtruo @piyush-singh this is the issue that directly relates to users/customers not being able to find entries from the event log that interest them.

**Comment by knz** [comment]
Users can now redirect their events to an external database using structured logging and network logging. Whatever advanced filtering / search etc they want can be implemented in a system best optimized for log analysis.
