### ISSUE TITLE
Correlate RUs on the overview page with SQL Activity information

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#77807]
We should enable developers to quickly correlate RU consumption spikes on the Serverless overview page with SQL Activity information. 

As we did with the metrics page, we should enable a global time picker across these pages or deep link on the RU consumption chart for one to dig into the offending statement(s)/workload details.

CC @Annebirzin 

Jira issue: CRDB-13773

**Comment by Annebirzin** [comment]
For a V1 we could start with correlating the existing timeframes when going to/from the overview pages to SQL Activity and Metrics pages - 30 mins, 1 hour, 1 day, 1 week. 

The monthly timeframes on the overview page were meant to allow users to see usage for the monthly billing period to help understand spending. These could correlate to a custom timeframe when going from Overview to SQL Activity or Metrics.
