### ISSUE TITLE
sql: SHOW SETTING FOR TENANT(S) is not completely designed (and perhaps ALTER TENANT SET CLUSTER SETTING too)

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#77935]
Discussed/discovered in #77740, in the context of a conversation with a CC infra engineer who was asking: 

*is there a way for me to discover how the customer has customized their cluster settings themselves, short of spawning a SQL pod for them*?

As currently designed in the [setting RFC](https://github.com/cockroachdb/cockroach/pull/77740), no currently it is not possible to **inspect the current value of a tenant's cluster setting** from the admin tenant.

As defined, SHOW SETTING FOR TENANT has two different shortcomings:

1. if there is no override configured, the statement is not able to inspect the current value of a tenant's cluster setting, *as observed from the tenant's SQL*. The logic is only able to observe overrides, but not the actual customization within the tenant's own `system.settings` keyspace.
2. as designed, **the statement's output provides the wrong impression that it does, in fact, show the setting's value from the tenant's perspective**.  This is because the statement syntax is `SHOW SETTING FOR TENANT`, not `SHOW SETTING OVERRIDE FOR TENANT`. This is very likely to mislead SREs and other administrative engineers who wish to inspect how a tenant is *effectively* configured.

There are two different ways forward:

- rename the statement to `SHOW SETTING OVERRIDE FOR TENANT`. This would solve problem (2) but fail to solve problem (1).
- invent a mechanism through which, when there is no override defined, the SHOW SETTING FOR TENANT statement can inspect the actual customization performed by a tenant. This would solve both problems (1) and (2).

----

Arguably, ALTER TENANT SET CLUSTER SETTING has a similar shortcoming: it is not currently possible to change a tenant's *own* customization of a cluster setting "remotely" in a way that *the tenant can change it themselves to another value later*. The semantics (as defined by the RFC) only provision a mechanism for overrides.

cc @ajstorm @RaduBerinde 

Jira issue: CRDB-13859

Epic CRDB-14080

**Comment by ajwerner** [comment]
I support changing the syntax to require the word `OVERRIDES`, and then waiting to see if we have issues with the lack of support for the user stories you mention.

**Comment by knz** [comment]
Well there's already a concern expressed in our team https://cockroachlabs.slack.com/archives/C0222501329/p1647292619692449?thread_ts=1647189946.562659&cid=C0222501329

**Comment by RaduBerinde** [comment]
Note that there is some nuance around the "override" terminology. It absolutely makes sense for TenantWritable settings, where it overrides any potential customization by the tenant.  But for TenantReadOnly settings, this is the only way to change them so we're not really overriding anything.

I still agree it would be less confusing if we introduce it in the syntax. Having two possibilities for the two different types of settings is also an option (but feels a but much).

There is a desire for a more general mechanism to easily run (from the host cluster) arbitrary statements as a specific tenant. If/when we have that, this ask would just amount to running SHOW CLUSTER SETTINGS as the tenant.

**Comment by knz** [comment]
> There is a desire for a more general mechanism to easily run (from the host cluster) arbitrary statements as a specific tenant. If/when we have that, this ask would just amount to running SHOW CLUSTER SETTINGS as the tenant.

Yes I can see that. In fact, I was starting to sketch it earlier today and it doesn't seem particularly hard. So I think for now a syntax change should be sufficient.

**Comment by knz** [comment]
> I think in the future we might want the ability to override what a tenant has set or prevent them from changing a setting.

That one was already being implemented. :) (#77740)

The discussion here is related to your first point:

> SRE has no way to see into a tenant database without creating a temporary "admin" SQL user and then connecting to the database via our own machines (ie. a secure enclave). This is a very risky way to interface with a customer's database and if we had some means of performing basic operations (like viewing/setting cluster settings) on tenant databases via the system tenant, I think we could significantly reduce toil and risk.

That's the most important input here and where we need to make progress.

**Comment by RaduBerinde** [comment]
@logston the decision here is - does it make sense to add special system-tenant code for this one use-case (i.e. showing the tenant's current settings), and then add some more special code for the next use-case, or should we focus our efforts on a more general mechanism to run arbitrary things as the tenant without spinning a pod? The latter seems like the true necessity IMO.

**Comment by logston** [comment]
> That one was already being implemented. :)

Ah! Thank you @knz! 

>  does it make sense to add special system-tenant code for this one use-case (i.e. showing the tenant's current settings), and then add some more special code for the next use-case, or should we focus our efforts on a more general mechanism to run arbitrary things as the tenant without spinning a pod? The latter seems like the true necessity IMO.

I see, thanks for the clarification @RaduBerinde. 

> we focus our efforts on a more general mechanism to run arbitrary things as the tenant without spinning a pod

I agree with you here. For example, if we could configure all tenant clusters from the host/system tenant, then that would obviate the need to spin up 10k SQL pods for small changes. That would in turn have strong stability benefits as we wouldn't need specialized code to handle spikes in active pods simply for config changes.

**Comment by knz** [comment]
FYI: i have one some UX and implementation research about adding a new OVERRIDE keyword. I believe adding a new keyword is unwarranted. However it is important to re-spec the statement to spell out that the value NULL will be returned if there is no override currently configured. I'll send a PR to the RFC.
