### ISSUE TITLE
sql: final call on mvcc-compatible backfiller default enablement in v22.1

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#77942]
Since we still have performance and stability concerns about the mvcc-compatible backfiller. We should disable it by default for 22.1.

Jira issue: CRDB-13864

**Comment by dt** [comment]
It has been on for a good month now and attempts to break it haven't found anything, so with the 22.1.0 branch cutting tomorrow I think we're leaving it as is, bar any late-breaking discoveries.
