### ISSUE TITLE
sql: experimental_enable_hash_sharded_indexes session var should be deprecated, not deleted

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#77954]
Users may rely on this setting, and we can keep it around to avoid breaking anything. It should be hidden if possible.

See https://github.com/cockroachdb/cockroach/pull/70369 for another example where we did this.

Jira issue: CRDB-13871

**Comment by ajwerner** [comment]
@chengxiong-ruan can you take this?
