### ISSUE TITLE
Acceptance testing - Auto-statistics setting is showing as disabled for non-admin users

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#77974]
Auto-statistics enabled for a cluster is shown as enabled in the console UI but is **incorrectly shown as disabled for non-admin users**. This was tested with a user having the VIEWACTIVITYREDACTED role option. 

Screenshot:

![image](https://user-images.githubusercontent.com/81193618/158687468-f3e6d35f-1a98-4c37-95bc-1e9d26b08f99.png)

Jira issue: CRDB-13878

**Comment by matthewtodd** [comment]
Hmm, we built this by surfacing the cluster setting directly in the UI without realizing that [only admin users](https://www.cockroachlabs.com/docs/v21.2/show-cluster-setting#required-privileges) can read cluster settings. 😢

From here we can either hide these UI bits for non-admin users (quicker), or we can find a way to get the databases API endpoints to include these (more helpful).

cc @ericharmeling

**Comment by ericharmeling** [comment]
@kevin-v-ngo 

> Hmm, we built this by surfacing the cluster setting directly in the UI without realizing that [only admin users](https://www.cockroachlabs.com/docs/v21.2/show-cluster-setting#required-privileges) can read cluster settings. 😢

It looks like the value for the [setting shows up as `null` for users who can't see it](https://github.com/cockroachdb/cockroach/pull/76168/files#diff-7649002d990af1d8a15f3585e3e848f777a8d7f5a516662772a6be822d6bbe79R152). Which isn't really handled properly (the UI just renders it as "disabled").

Happy to take this on, as this is an oversight on my part.

@matthewtodd 

> From here we can either hide these UI bits for non-admin users (quicker)

I like this as an approach. It's how we are handling [the case where no table stats are available to the user](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/cluster-ui/src/databaseTablePage/databaseTablePage.tsx#L377). (FWIW, we don't need to worry about permissions for [`SHOW STATISTICS`](https://www.cockroachlabs.com/docs/v21.2/show-statistics.html#required-privileges).)

> we can find a way to get the databases API endpoints to include these (more helpful).

Would you be opposed to us doing this in two phases? First making the quick update to hide the setting to non-admins, then exposing the API endpoint for this setting to non-admins? (If only admin users can change cluster settings, we would probably need to update the tooltip to tell the user that only admin users can change this.)

**Comment by matthewtodd** [comment]
> Would you be opposed to us doing this in two phases?

Makes sense to me! WDYT, @kevin-v-ngo?

**Comment by kevin-v-ngo** [comment]
> 

Two phased approach sounds good to me! Can we backport to 22.1? Seems like a good candidate since this can be wrongly interpreted by non-admin users. 

And yeah, good suggestion on tool tip as well for phase 2 for non-adminss. cc @Annebirzin

**Comment by ericharmeling** [comment]
@kevin-v-ngo I think we can close this with https://github.com/cockroachdb/cockroach/pull/78266 and https://github.com/cockroachdb/cockroach/pull/78655. 

I've opened a separate issue for the "phase 2" of this issue (see https://github.com/cockroachdb/cockroach/issues/78662). I don't believe that should be `GA-blocker`, but that's up to you. :)
