### ISSUE TITLE
Acceptance testing - The entire console is unresponsive when clicking on a statement fingerprint

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#77978]
The entire console is unresponsive when clicking on a statement fingerprint from the Sessions and Statement Diagnostics History pages. The mitigation is to refresh the browser/app.

Steps to repro:

1. Enable a statement bundle for a statement fingerprint
2. Visit the Statement Diagnostics History page from advanced debug
3. Click on statement that has a bundle request (Note: The statement is also only clickable when the Statements request has already been issued on the Statements overview tab for some reason).

1. Visit the Sessions page with open transaction and active statement (you can just use pg_sleep through the SQL cli)
2. Click on the Most Recent Statement link (Note: The statement is also only clickable when the Statements request has already been issued on the Statements overview tab for some reason).

Not only should we fix this issue but also provide the user guidance (even a button/URL in the error message) to refresh the app whenever this page is encountered for quick self-serve mitigation. 

cc @Annebirzin 

Jira issue: CRDB-13879

**Comment by maryliag** [comment]
The problem with the Sessions is that since the statement is still being executed we don't have details to show, so heaving the link don't actually make sense for active statements. Currently, when there are no active statement, we show the last executed, but that one is not a link, although that one could be. So we can create a separate issue to add link to past statement and for the fix for this one I'll remove the link on active statements

**Comment by kevin-v-ngo** [comment]
> The problem with the Sessions is that since the statement is still being executed we don't have details to show, so heaving the link don't actually make sense for active statements. Currently, when there are no active statement, we show the last executed, but that one is not a link, although that one could be. So we can create a separate issue to add link to past statement and for the fix for this one I'll remove the link on active statements

I guess we can add the link back in after @xinhaoz changes correct? 

What about the Statement Diagnostics History Page? The statement fingerprint should already exist correct?

**Comment by maryliag** [comment]
For the Statement Diagnostics page the PR is already up with the fix and waiting review  https://github.com/cockroachdb/cockroach/pull/78050

**Comment by maryliag** [comment]
Open so it can be backported to 22.1
