### ISSUE TITLE
22.1 Acceptance Testing UI Updates

### ISSUE THREAD

**Issue by Annebirzin** [cockroachdb/cockroach#77982]
**Databases/Tables overview pages**
- [x] The Auto Stats green circle icon is rendering cut off (occurs on database and table detail page) ([screenshot](https://www.loom.com/i/a8ee93807db9456998748260ee13e471))
- [x] On the Auto Stats tooltip, the Learn more link is missing (style should be white text and underlined) ([screenshot](https://www.loom.com/i/a8ee93807db9456998748260ee13e471))
- [x] On the Databases/Tables pages, update table widths to full page to match tables in CC console (see [loom video](https://www.loom.com/share/6dcd5b86e377457bb39fe797b22d22b5) of desire behavior for Databases and Tables widths). When resizing the browser window down to the smaller screen, the table includes a horizontal scroll.

**Table detail page**
- [x] Update copy for reset tooltip to `…from the time the index was created or had its stats reset.` ([screenshot](https://www.loom.com/i/25aa830c5c1044baaee09599797134ae))
- [x] Update Index Stats Table width when resizing browser window. Match the width of the SQL box and summary stats modules ([loom video](https://www.loom.com/share/2dcd3ece1d144c8ca2e3c8414e2568d7) for reference) ([screenshot](https://www.loom.com/i/05a8f9fb0af74fd6adf02c0efd8bfe7a))

**Index detail page**
- [x] ‘Reset Stats’ link currently uses AntD blue - update to our core blue (#0055FF) ([screenshot](https://www.loom.com/i/30977039493b498dac1b9bfcf14de946))

**Statement fingerprint overview page**  
- [x] On the diagnostics column, update the `Waiting` status tooltip ([screenshot](https://www.loom.com/i/6fc0b5974627497abaf983c10f0db725))
- `diagnostics` link should be white and underlined - the same as on the statement detail page (currently showing up as black text) 
- Tooltip disappears easily when trying to click the link (use the same tooltips as in the table headers?)
- Add space before `…When` 
- [x] In the Diagnostics column action dropdown, update copy to `Cancel diagnostics request` (remove the word 'current') ([screenshot](https://www.loom.com/i/bc6bfb663ffd44de85470f0a6fa02988))
- [x] Update Loading state message ([screenshot](https://www.loom.com/i/626ca21282f140fb8e241b1cdcc7512f))
- Alignment within loading state info message off (center icon and text vertically)
- Update to only appear after 2 seconds of loading time has passed 
- [x] Update search/filter actions bar on Statement and Transaction pages ([screenshot](https://www.loom.com/i/37b78f3752b24ad7b6040dc186276b9b))
- Condense horizontal spacing to ~12px between each input/button/divider line 
- Both vertical divider lines should match the height of the inputs  

**Conditional statement bundle modal**
- [x] When diagnostics request expiration is unchecked: update alert background blue to #E1ECFF with no border (matches other blue info banners across the UI) ([screenshot](https://www.loom.com/i/46bb2f89a9b34ca89160643bc7560b23))
- [x] Update text (#78364)
- [x] Fix radio button selection on CC Console (#78369)

**Statement diagnostics history page** ([screenshot](https://www.loom.com/i/f50bb7177e1543308b9c256e1fb37ca9))
- [x] Update pagination copy - `x traces` to x `diagnostics bundles`
- [x] Update table width to full page (see [loom video 1](https://www.loom.com/share/c0fa2b35b992463c9b96fe311c38d9ba) or  [loom video 2](https://www.loom.com/share/6dcd5b86e377457bb39fe797b22d22b5) of desire behavior for table widths from CC console)

**Session overview page**
- [x] Show all columns by default (currently only showing the first column)
- [x] Update copy in the actions dropdown from `Terminate` to `Cancel` ([screenshot](https://www.loom.com/i/f7c3a525acf7484b99f4ef08c75f2059))
- [x] Vertical alignment of statement is off (sits higher than other columns) ([screenshot](https://www.loom.com/i/77f6303105134bc7835b2b0570e89fcf))
- [x] Update Cancel Statement and Cancel Session Confirmation Modals ([screenshot](https://www.loom.com/i/0ebc1d4748bd42d6b9e50cb899fef6f6))
- Update copy from `Terminate` to `Cancel` 
- Remove `?` from the header copy
- [x] In the Cancel Statement and Cancel Session success message, Update `Query` to `Statement`

**Session detail page**
- [x] Update button copy from ‘Cancel Query’ to ‘Cancel Statement’ ([screenshot](https://www.loom.com/i/f9fcdb36ca094d619150e5a6b881d9ff))
- [x] Right align gateway Node link ([screenshot](https://www.loom.com/i/39611fcd8f574fc0a737bdf11be3bbb9))

**CC Serverless > Metrics page** 
- [x] Updated chart time zone from local to UTC to match time picker time zone (See comment below)
- [x] Update loading state to remove headers and just show a spinner ([screenshot](https://www.loom.com/i/66b9a7ef9b834b86acd263a864a66585))
- [x] Time picker should be left-aligned with Header (remove the gray vertical line to the left) and add more padding below time picker ([screenshot](https://www.loom.com/i/7e58a208cffd4b8baa718e28c4dac46f))
- [x] Update fixed time picker background when scrolling (should be a gray background behind the time picker) ([screenshot](https://www.loom.com/i/72eaf5eeb76c454e8d801a9e0fdaf855))

**Jobs**
- [x] Update Colors (#71963)

cc @kevin-v-ngo 

Jira issue: CRDB-13883

**Comment by Annebirzin** [comment]
@kevin-v-ngo @maryliag I noticed another issue on the CC Serverless > Metrics page. The time picker is in 'UTC' but when I hover over the graphs, the time is is local (EDT).

![Screen Shot 2022-04-04 at 2 15 48 PM](https://user-images.githubusercontent.com/51920721/161606588-5056b518-2773-412a-8e26-cba49b177f88.png)

I was going to include this as part of this timeframe clean-up issue https://github.com/cockroachdb/cockroach/issues/78442 , but feels more like a higher priority bug

**Comment by rail** [comment]
Manually synced with Jira
