### ISSUE TITLE
storage: close Replica.mu.snapshotChan when replica is destroyed

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#7806]
There appears to be no cleanup of `Replica.mu.snapshotChan` when a replica is destroyed. This can leave the snapshot goroutine started in `Replica.Snapshot` dangling for a minute (`defaultAsyncSnapshotMaxAge`) as nothing comes along to consume the snapshot. Alternately, perhaps `snapshotChan` should be buffered.

**Comment by tamird** [comment]
Also see #7307; that PR likely suffers from the same issue, but the details are slightly different.

**Comment by tamird** [comment]
`Replica.mu.snapshotChan` is no longer a thing.
