### ISSUE TITLE
telemetry: do not redact application names in telemetry logs

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#78098]
**Is your feature request related to a problem? Please describe.**

We're steadily making telemetry logging higher fidelity by marking specific pieces of data as "operational data", making them safe to unredact for telemetry purposes. See for example https://github.com/cockroachdb/cockroach/issues/76595

**Describe the solution you'd like**

As we've done with table and column names in SQL statements, `application_name` is considered operational data and is therefore safe to collect. We should not be redacting those values in cases where the `sql.telemetry.query_sampling.enabled` cluster setting is enabled 

Jira issue: CRDB-13961

Epic CRDB-12732

**Comment by kevin-v-ngo** [comment]
@thtruo, any update here?

**Comment by rail** [comment]
Manually synced with Jira
