### ISSUE TITLE
ui: Bar to track position across all graphs

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#7812]
If you're hovering over a position in one graph, it would be nice to show that same location, temporally, on all other graphs on the same page. This would make it easier to associate events temporally.

**Comment by dianasaur323** [comment]
@maxlang I thought you were already pretty close to implementing this - is this a duplicate issue? I'm cleaning out the 1.0 milestones right now.

**Comment by mrtracy** [comment]
Yes this is complete. There is a bug with it, but that's tracked in its own issue. Closing.
