### ISSUE TITLE
cli: Interactive SQL shell no longer remembers past commands

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#7815]
```
$ grep -F '[config]' cockroach-data/logs/cockroach.INFO
I160713 13:17:35.581141 util/log/clog.go:998  [config] file created at: 2016/07/13 13:17:35
I160713 13:17:35.581141 util/log/clog.go:998  [config] running on machine: JESSEs-MacBook-Pro
I160713 13:17:35.581141 util/log/clog.go:998  [config] binary: CockroachDB beta-20160629-319-g028e956 (darwin amd64, built 2016/07/13 17:10:54, go1.6.2)
I160713 13:17:35.581141 util/log/clog.go:998  [config] arguments: [cockroach start]
```

The interactive sql shell used to remember previous commands from the current session. It no longer does. @knz  and I thought there was already an issue for this, but we can't find it.
 
**To reproduce:**
1. Start a cluster.
2. Open the interactive shell.
3. Execute a few statements.
4. Press up and down arrows.

**Expected result:**
I expected previous commands to be available.

**Actual result:**
Nothing happens.

**Comment by tamird** [comment]
Possibly a regression from upstream?

**Comment by mjibson** [comment]
Nope. My fault. See PR.
