### ISSUE TITLE
backupccl: add deprecation warning to `BACKUP TO` and non-collection forms of `RESTORE` and `SHOW BACKUP`

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#78153]
Since 21.1 we have removed all documentation referencing the `BACKUP TO` syntax. We have also had a deprecation warning in the docs advising users to use the current `BACKUP INTO` collection syntax since then https://www.cockroachlabs.com/docs/stable/backup.html#considerations. This issue tracks displaying this notice on the sql shell when a user reaches for `BACKUP TO` setting us up to delete this code in a future release. Additionally, we want to warn users using `RESTORE FROM <path>` to instead use `RESTORE FROM <specific-backup> IN <collection>`, this goes hand in hand with the deprecation of the non-collection `BACKUP TO` syntax. A deprecation notice of a similar nature will also be added to `SHOW BACKUP <path>`.

Biting this bullet has been long discussed in the BulkIO team, and all members seem to agree that we have reached a point (long enough into the future) that we can safely deprecate and get rid of this syntax without disrupting user flows. The technical debt of maintaining these relics is becoming untenable, as was experienced first hand in this valiant refactor https://github.com/cockroachdb/cockroach/pull/75970.

**Comment by adityamaru** [comment]
@msbutler SHOW still needs a warning, let me know if you want me to take it on.

**Comment by msbutler** [comment]
@adityamaru I'll do it today!

**Comment by stevendanna** [comment]
Fixed on master and 22.1.
