### ISSUE TITLE
timestamp regression in TestConcurrentIncrements

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#782]
@BramGruneir had an interesting test failure tonight in `TestConcurrentIncrements`:

> I0423 22:22:41.904893      46 multiraft.go:699] Committed Entry[0]: 7/43 EntryNormal 13d7c4c61e50419a5c33383c18aca777: raft_id:1 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:1429827761901804411 logical:1 > cmd_id:<wall_time:0 random:0 > key:"value-1" end
	client_test.go:672: txn "test-1" {id=214d3af7-b297-48a6-bffc-75e4bd25e4da pri=1470248948, iso=SERIALIZABLE, stat=PENDING, epo=0, ts=1429827761.846319546,3 orig=1429827761.826247139,0 max=1429827761.826247139,0}: timestamp regression: 1429827761.846319546,5

the interesting bit is that the timestamp of the transaction above, `1429827761.846319546,3`, has moved back from its original timestamp `1429827761.846319546,5` (only the logical component has changed).

That suggests that somewhere, and very likely very close to where the error occured, we're losing the logical.

[Full log here](https://circleci.com/gh/cockroachdb/cockroach/1739)

ping @spencerkimball, @BramGruneir

**Comment by spencerkimball** [comment]
OK found the problem and fixed. Need to write a unittest for it though.
