### ISSUE TITLE
IMPORT INTO failing after upgrade

### ISSUE THREAD

**Issue by steven-hubbard** [cockroachdb/cockroach#78205]
After upgrading from 20.0.16 to 21.1.12, IMPORT INTO with an S3 source has stopped working with the following error:

ERROR: expected content length

At this time we believe it is a bug as we have successfully tested importing the same file on a different cluster that is still on 20.0.16 and we have verified that we can reach the S3 endpoint with the same credentials through other methods.

Jira issue: CRDB-14016

**Comment by mgartner** [comment]
@steven-hubbard Looks like this issue got lost in the cracks. Do you remember a way to reproduce this error?

**Comment by mgartner** [comment]
I'm going to close this issue, but if you have ideas on how to reproduce this, we can re-open and investigate further.
