### ISSUE TITLE
run cockroachdb on k8s

### ISSUE THREAD

**Issue by carr123** [cockroachdb/cockroach#78309]
hello, is it recommended to deploy cockroachdb on k8s in production ?
i hear voices, it is better to run databases outside of containers.
what's your advice ?
thanks.

Jira issue: CRDB-14055

**Comment by rafiss** [comment]
Hi! This might be a better question to ask on the [forum](forum.cockroachlabs.com/) or [slack](https://cockroa.ch/slack).

> hello, is it recommended to deploy cockroachdb on k8s in production ?

But just to give a quick answer now: yes, it should work well. We have docs here: https://www.cockroachlabs.com/docs/stable/deploy-cockroachdb-with-kubernetes.html and lots of examples across our website.

We also use kubernetes internally to run CockroachDB.
