### ISSUE TITLE
multi-tenant: Improve non-system SQL server console

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#78336]
With https://github.com/cockroachdb/cockroach/pull/75852 we enabled non-system SQL servers to expose a console.  While this work exposed the basic capabilities, there are several open issues:

- [x] The port at which the console is exposed is not documented
- [x] In `demo`, going directly to http://127.0.0.1:8080/ to access the console works, but if a userid/password are provided, it returns a 404 page not found
- [x] The console currently returns an invalid certificate error when trying to access the non-SQL Server’s console
- [ ] Several aspects of the non-system SQL sever are not functional - results in a perpetual spinning wheel
- [x] The `demo` welcome screen doesn’t mention the connection string for non-SQL servers
- [ ] The metrics tab doesn't report statements being executed

This work is also required before we can enable multi-tenant by default for `demo` or any other server.

References https://github.com/cockroachdb/cockroach/issues/72341

Jira issue: CRDB-14074

**Comment by knz** [comment]
we've addressed the infra aspects of this; the rest is known to the sql obs team.
