### ISSUE TITLE
server,sql: add cluster setting to partially disable SQL Stats RPC endpoint

### ISSUE THREAD

**Issue by Azhng** [cockroachdb/cockroach#78343]
For context, see #78338

Currently, `/_status/statements` endpoint queries both `crdb_internal.statement_statistics` and `crdb_internal.transaction_statistics` virtual tables. When the size of those two tables becomes large (e.g. in #78338, this was caused by large number of distinct transaction fingerprint ID), we will have the risk of experience API gateway timeout. (504). 

If #78338 is implemented, the size of statement statistics table can be significantly reduced. However, we are still likely to have a large transaction statistics table, which can cause API gateway timeout.

Adding a cluster setting to individually disable either the loading of statement statistics or transaction statistics allows gracefully degradation to allow API used by the SQL Activity Page to remain partially functional. 
 

Jira issue: CRDB-14081

**Comment by jocrl** [comment]
Another approach for doing this could be to separate the statments and transactions endpoints on the frontend. Not sure how big of a change this would be, but it would allow them to fail independently.
