### ISSUE TITLE
ui: Total capacity misreported on front page

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#7834]
Seen on beta cluster at commit efd0607 (gamma is fine). 6 nodes with ~110GiB of data each on a 369GiB disk. This is reported on the front page of the UI as 97% capacity used; the tooltip says "you are using 674.9GiB of 695.5GiB storage capacity". The individual node pages show the correct values for total and available capacity.

**Comment by bdarnell** [comment]
The beta cluster is now reporting 102.2% capacity used and all nodes are down. One node is at 95% disk usage and the others are ~65%.

**Comment by maxlang** [comment]
Total capacity should be ignored as far as this calculation is concerned, it's just the total capacity of that machine.

cc @mrtracy 
Does available capacity not include space taken up by CockroachDB? Currently the calculation on the UI side is `used/available` but it looks like it should be `(used + available)/available`.

**Comment by bdarnell** [comment]
FYI the gamma cluster is also reporting 160% capacity used (but is otherwise working, unlike beta)
