### ISSUE TITLE
telemetry: do not redact error text names in telemetry logs

### ISSUE THREAD

**Issue by pransudash** [cockroachdb/cockroach#78353]
**Is your feature request related to a problem? Please describe.**
Stems from [thread in slack](https://cockroachlabs.slack.com/archives/CL94XLGG1/p1648056498825709). We're steadily making telemetry logging higher fidelity by marking specific pieces of data as "operational data", making them safe to unredact for telemetry purposes. See for example https://github.com/cockroachdb/cockroach/pull/76676

**Describe the solution you'd like**
Currently the ErrorText field in the event is either null or `‹×›`. We want the ErrorText field within Event to be exposed so stakeholders can view common errors on statements that users are trying to execute. Since we are considering object names in sql statements operational data the error text should be treated similarly where the `sql.telemetry.query_sampling.enabled` cluster setting is enabled.

Jira issue: CRDB-14087

Epic CRDB-12732

**Comment by kevin-v-ngo** [comment]
@thtruo, this is Obs Inf correct? Removing redaction of the ErrorText. Let me know if otherwise.

**Comment by thtruo** [comment]
Yep Obs Inf can take this since we're looking at redaction across the board
