### ISSUE TITLE
ui: Should be able to move mouse to tooltip

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#7835]
While filing #7834, I wanted to copy and paste some text from the tooltip, but it disappeared any time I moved my cursor off the (i) icon. The tooltip should remain visible if the cursor is moved onto the tooltip itself.

**Comment by maxlang** [comment]
FYI this is slightly better now. I made it so that when you move your mouse over the tooltip it stays visible. A true fix would either be using JS or a css fade animation.

**Comment by maxlang** [comment]
cc @honzie

**Comment by honzie** [comment]
@maxlang: Can you please provide the HTML structure you're building on? I can put together a codepen of a couple CSS solutions including fading in/out.

**Comment by maxlang** [comment]
http://codepen.io/maxlang/pen/BLjKxQ
