### ISSUE TITLE
ui: The radio button for the statement diagnostics modal has the dot outside the circle 🤯

### ISSUE THREAD

**Issue by jocrl** [cockroachdb/cockroach#78369]
On https://management-staging.crdb.io/, SQL Activity -> row in the statements table -> click "Activate"

<img width="676" alt="image" src="https://user-images.githubusercontent.com/91907326/159797569-f5016778-95f3-4811-9464-3d7dd7d4e1d5.png">
<img width="621" alt="image" src="https://user-images.githubusercontent.com/91907326/159797584-fc5d5b70-6f1b-4565-8024-5e82b2d217e9.png">

I wonder if we added some weird styling thing that messed up the styling for what I presume is a component from a library.

Discovered by @stbof. Is this blocking docs?
from @stbof: https://github.com/cockroachdb/cockroach/issues/78364 and this will only block me if I decide I need a screenshot, which I haven't decided yet.

Jira issue: CRDB-14094

**Comment by stbof** [comment]
> On https://management-staging.crdb.io/, SQL Activity -> row in the statements table -> click "Activate"
> 
> <img alt="image" width="676" src="https://user-images.githubusercontent.com/91907326/159797569-f5016778-95f3-4811-9464-3d7dd7d4e1d5.png">
> 
> <img alt="image" width="621" src="https://user-images.githubusercontent.com/91907326/159797584-fc5d5b70-6f1b-4565-8024-5e82b2d217e9.png">
> 
> I wonder if we added some weird styling thing that messed up the styling for what I presume is a component from a library.
> 
> Discovered by @stbof. Is this blocking docs?
> 
> Jira issue: [CRDB-14094](https://cockroachlabs.atlassian.net/browse/CRDB-14094)

Only if I need to take a screenshot. Not sure yet.

**Comment by stbof** [comment]
However, I don't see this bug in my local build. 
<img width="565" alt="Screen Shot 2022-03-23 at 3 06 55 PM" src="https://user-images.githubusercontent.com/20482960/159804062-1bbb5a7c-45fc-4b72-92fe-fdd78a3f6863.png">
