### ISSUE TITLE
'SHOW TABLES WITH settingName' and  'SHOW CLUSTER SETTINGS FOR TABLE'

### ISSUE THREAD

**Issue by msirek** [cockroachdb/cockroach#78395]
**Is your feature request related to a problem? Please describe.**
1. [PR#78110](https://github.com/cockroachdb/cockroach/pull/78110) adds support for setting certain cluster setting overrides for individual tables.  There is currently no way for a user or DBA to discover which tables in the system have a given setting set, if they wish to unset it for all tables, without issuing a `SHOW CREATE TABLE` statement on every table in the system. Here is an example query which could find these tables, but it references crdb_internal, which is generally not customer-visible:
```
SELECT
        tbl.database_name || '.' || tbl.schema_name || '.' || tbl.name
FROM
        crdb_internal.tables AS tbl
        INNER JOIN system.descriptor AS d ON d.id = tbl.table_id
WHERE
        tbl.database_name IS NOT NULL
        AND tbl.drop_time IS NULL
        AND
         crdb_internal.pb_to_json('cockroach.sql.sqlbase.Descriptor',
                d.descriptor, false)->'table'->'clusterSettingsForTable'
                       ->> 'sqlStatsAutomaticCollectionEnabled' = 'true';

      ?column?
--------------------
  defaultdb.mws.t1
```
2. Currently, table settings (storage parameters) are displayed in the `SHOW CREATE TABLE` output. However, it would be nice to have a new statement which displays just the current cluster settings for the table, one per line, instead of a dense `WITH` clause which prints all settings on one line and has other storage parameters mixed in.  If no cluster settings are specified at the table level, that could quickly be determined by empty output.

**Describe the solution you'd like**
1. Add a new statement, such as `SHOW TABLES [IN _schemaName_] WITH "_settingName_" (SET | UNSET);` which would list all tables (or all tables in a given schema) having a given table setting, such as `sql.stats.automatic_collection.enabled` set to a value, or not set (via the `SET` or `UNSET option).  This would not be specific to table-level cluster settings added by [PR#78110](https://github.com/cockroachdb/cockroach/pull/78110), but apply to any table setting added by `CREATE TABLE ... WITH` or `ALTER TABLE ... SET`.  Optionally, a statement to list all tables with any storage parameter set could be supported. A variant of this could list all tables with any cluster setting set.

2. A new statement such as `SHOW CLUSTER SETTINGS FOR TABLE _tableName_`, and possibly a `SHOW SESSION SETTINGS FOR TABLE _tableName_` statement could be added to list table-level cluster settings and table-level session settings (currently table-level session settings are not supported). Optionally a `SHOW SETTINGS FOR TABLE _tableName_` statement could be added which would list both cluster and session settings in effect for the table.

**Describe alternatives you've considered**
None

**Additional context**
None

Jira issue: CRDB-14104

**Comment by ajwerner** [comment]
It feels to me like we've created a new set of terminology we didn't need to create. Namely, why are we calling these things `CLUSTER SETTINGS` at all? These seem to me to just be `reloptions` as postgres calls them, and we're using the same syntax, no? Could we display them in`pg_class.reloptions`: 

https://github.com/cockroachdb/cockroach/blob/cc572d74a2dfe79b22e74183288a0f7c0ae2a300/pkg/sql/pg_catalog.go#L626-L635

**Comment by ajwerner** [comment]
Also maybe of interest is:
`pg_options_to_table ( options_array text[] ) → setof record ( option_name text, option_value text )`

**Comment by msirek** [comment]
> It feels to me like we've created a new set of terminology we didn't need to create. Namely, why are we calling these things `CLUSTER SETTINGS` at all? These seem to me to just be `reloptions` as postgres calls them, and we're using the same syntax, no? Could we display them in`pg_class.reloptions`:

These settings will be shown in `reloptions`, so perhaps `SHOW CLUSTER SETTINGS FOR TABLE` is of limited use or not needed.  

What's more useful may be `SHOW TABLES WITH "settingName"` as a way to discover tables that have a given `reloption` (storage parameter) set, or maybe even a `SHOW TABLES WITH ANY SETTING` which displays all tables that have any `reloption` set.  Maybe the syntax could be tweaked if the wording is inaccurate, but this functionality seems useful.

**Comment by msirek** [comment]
> In this case, I'd think we could have a query like:

Thanks, this is great!  I see that query references `crdb_internal`.  The motivation for this issue is a comment I received in a PR that `crdb_internal` is not generally for use by users, and so we shouldn't be advertising queries that involve it.  I'm wondering if there is an official answer on this topic.

**Comment by msirek** [comment]
I spoke with the reviewer who requested this issue, and we agreed to close it.
