### ISSUE TITLE
sql: a table created on 22.1 cannot be accessed by 21.2 nodes if it has a secondary index

### ISSUE THREAD

**Issue by fqazi** [cockroachdb/cockroach#78426]
**Describe the problem**
If we create a table on 22.2, the version number for secondary indexes is 4, which is disallowed/invalid on the 21.2 release as index version for secondary indexes. This was due to the lack of a version gate when we decided to simplify the index versioning scheme, leading to validation failures on 21.2.

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**
Setup a mixed version setup where you have one node on 22.2 and one 22.1. 

On the 22.2 node create a new table with a secondary index:
1) `CREATE TABLE IF NOT EXISTS public.table223 (col223_224 TIMESTAMPTZ NOT NULL, col223_225 FLOAT8 NOT NULL, col223_226 REGNAMESPACE NOT NULL, col223_227 TIMESTAMP NOT NULL, col223_228 BIT(11) NOT NULL, col223_229 BYTES NOT NULL, col223_230 STRING NOT NULL AS (CASE WHEN col223_226 IS NULL THEN 'VAgA':::STRING ELSE 'e':::STRING END) STORED, PRIMARY KEY (col223_228 ASC, col223_226 DESC, col223_225 DESC, col223_230 DESC, col223_229, col223_224, col223_227 DESC), INDEX (col223_228 DESC), UNIQUE (col223_228 ASC, col223_227, (CASE WHEN col223_226 IS NULL THEN e'47u\\x7fO3\\t\\x0b':::STRING ELSE '??q':::STRING END), col223_229 DESC), UNIQUE (col223_228 ASC, col223_230, col223_226 DESC, col223_224), UNIQUE (col223_224 ASC, col223_227 ASC, col223_230, col223_229 DESC, col223_228 DESC, col223_226 DESC), UNIQUE (col223_225 ASC, (CASE WHEN col223_226 IS NULL THEN '':::STRING ELSE e'.iu\\x13':::STRING END), col223_229 ASC, col223_228 ASC, col223_227 DESC, col223_230, col223_224), INDEX (col223_230, col223_228, col223_226, col223_229 ASC, col223_227), UNIQUE (col223_228 DESC, col223_229, col223_227 ASC, col223_230, col223_224, col223_226 DESC), UNIQUE (col223_229 ASC, col223_224 ASC, col223_230 DESC, col223_228, col223_225), INDEX (col223_230, col223_224 ASC, col223_225 DESC, col223_227, col223_226 ASC, (CASE WHEN col223_226 IS NULL THEN e'8vV\\x11':::STRING ELSE e'Y\\x04\\x01':::STRING END) ASC));`

On the 21.2
2) Select from the problematic table:
```
root@localhost:26259/defaultdb> select * from public.table224;
*
* ERROR: [n3,client=127.0.0.1:62898,hostssl,user=root] Queued as error df98c1cc1f5b47b6b972ab5656e57951
*
ERROR: internal error: relation "table224" (53): secondary index "table224_col223_228_idx" has invalid version 4 which is for primary indexes
SQLSTATE: XX000
DETAIL: stack trace:
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/validate.go:1093: validateTableIndexes()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/validate.go:559: ValidateSelf()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/validate.go:48: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/validate.go:256: validateDescriptorsAtLevel()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/validate.go:44: Validate()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/catalogkv/catalogkv.go:174: descriptorFromKeyValue()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/catalogkv/catalogkv.go:464: getDescriptorByID()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/catalogkv/catalogkv.go:556: MustGetDescriptorByID()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/lease/storage.go:111: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:836: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:908: exec()
/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:835: runTxn()
/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:817: Txn()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/lease/storage.go:90: acquire()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/lease/lease.go:343: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:128: doCall()
/usr/local/go/src/runtime/asm_amd64.s:1371: goexit()

```

What did you do? Describe in your own words.
Create a table on 22.2 with a secondary index, and attempt to access it from 22.1 node.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
2. Send SQL ... / CLI command ...
3. Look at UI / log file / client app ...

**Expected behavior**

Select should work like normal

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version [e.g. 2.0.x]
 - Server OS: [e.g. Linux/Distrib]
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
What was the impact?

This is also causing the current failure inside the schema change mixed version workload: https://github.com/cockroachdb/cockroach/issues/78304

Jira issue: CRDB-14128

**Comment by postamar** [comment]
@chengxiong-ruan I had enough time to take this on after all. I was able to repro this by running `debug doctor` from a 21.2 binary on a 22.1 cluster: no need to create any tables it readily complains about system table descriptors being invalid.
