### ISSUE TITLE
sql: Avoid wide scans of jobs table when starting compaction job.

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#78465]
Scheduled compaction job should not perform a system.jobs table scan to verify
compaction job does not exist.  Doing so is not needed since scheduling system already
does that, and furthermore, it's extremely disrupting to the scheduling system.

Performing system.jobs scan as part of starting the job results in *any* existing job
(not necessarily started by schedule) causing the schedule to be restarted.  Restarting the schedule
results in new job records being created, and increase in the intents, with subsequent lock ups of the
jobs (and schedules) tables.s

Jira issue: CRDB-14143

**Comment by nvanbenschoten** [comment]
Did we also want to open an issue about running these two "stats" queries outside of the scheduler txn?
```
SELECT count(*) FROM system.jobs WHERE created_by_type = 'schedule' AND status NOT IN ('%s', '%s', '%s', '%s')
SELECT count(*) FROM system.scheduled_jobs WHERE next_run < %s
```

**Comment by nvanbenschoten** [comment]
I see that the second commit in https://github.com/cockroachdb/cockroach/pull/78467 removes them entirely. Even better.
