### ISSUE TITLE
roachprod,roachtest: support tenants

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#78484]
**Is your feature request related to a problem? Please describe.**

We rely on roachtest to test the stability and correctness of multi-tenant deployments. However, roachprod does not offer built-in functionality to orchestrate tenants (it is completely oblivious to their existence). roachtest has a few test helpers that make it reasonable straightforward to start a tenant, but leaves much to be desired in terms of UX.

**Describe the solution you'd like**

roachprod should support tenants:

- `roachprod start-tenant [...]`
- support for the expanders that we have for the host cluster such as `{store}`, etc., and in particular, a fixed convention for ports assigned to tenants
- `roachtest` abstraction over the tenant that makes using them as productive (easy creation and lifecycle monitoring, automatic artifacts collection, etc, Start/Stop/Monitor) as using a pure host cluster.

**Describe alternatives you've considered**

**Additional context**

cc @srosenberg 
cc @cucaroach since this came out of our recent session talking through your roachtest https://github.com/cockroachdb/cockroach/pull/77481

Epic CRDB-10428
Jira issue: CRDB-14151

**Comment by tbg** [comment]
Whipped up a little PR that showcases using a tenant today: https://github.com/cockroachdb/cockroach/pull/78483

**Comment by irfansharif** [comment]
`roachprod start-tenant` is already a thing: https://github.com/cockroachdb/cockroach/pull/73266. Though much of what this issue describes would be nice -- folding in a bunch of tenant management facilities under roachtest's `cluster.Cluster` abstraction to make writing multi-tenant tests easier. Dug this issue up when trying to polish https://github.com/cockroachdb/cockroach/pull/89721, and we want to write many such tests in the coming weeks, so going to track this as a dependency in https://github.com/cockroachdb/cockroach/issues/89978 so we do something about it.

**Comment by srosenberg** [comment]
This work had been completed in a series of previous PRs,

- https://github.com/cockroachdb/cockroach/pull/111533
- https://github.com/cockroachdb/cockroach/pull/111064
- https://github.com/cockroachdb/cockroach/pull/109437
- https://github.com/cockroachdb/cockroach/pull/106497

and several others.
