### ISSUE TITLE
sql: unskip TestTenantStatementTimeoutAdmissionQueueCancelation which is failing due to timeout

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#78494]
**Describe the problem**

In https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/4672058 I saw TestTenantStatementTimeoutAdmissionQueueCancelation run for a very long time and fail.

Jira issue: CRDB-14157

**Comment by cucaroach** [comment]
Is there any way to get a goroutine dump on a go test timeout?      Check my math here on the logs:

```
[06:23:02] :		 [Run unit tests] === RUN   TestTenantStatementTimeoutAdmissionQueueCancelation
[06:23:02] :		 [Run unit tests]     test_log_scope.go:79: test logs captured to: /artifacts/tmp/_tmp/233e6aa31ff7ad29c896f0479cb5d0c4/logTestTenantStatementTimeoutAdmissionQueueCancelation1517069584
[06:23:02] :		 [Run unit tests]     test_log_scope.go:80: use -show-logs to present logs inline
[06:23:02] :		 [Run unit tests] -- Test timed out at 2022-03-25 06:23:02 UTC --
```

It looks like TestTenantStatementTimeoutAdmissionQueueCancelation just happened to be running when the bell rang?

Actually looking at test logs it looks like it started 05:23:42.140585 which means it was wedged for an hour I guess, I'll see if I can repro with stress and failing that put some kind of goroutine dumping timebomb in the test.

**Comment by rytaft** [comment]
@cucaroach is the linked draft PR ready to go to fix this issue?

**Comment by cucaroach** [comment]
No its still a draft because I was still able to repro with that fix, needs more work.

**Comment by rytaft** [comment]
Adding GA-blocker label -- we need to make sure all skipped tests are un-skipped for the release.

**Comment by cucaroach** [comment]
Yeah, I'll take a little break from QA and look at this again.

**Comment by cucaroach** [comment]
Should I backport this to 23.1 and 22.2 @mgartner?   I don't see why not...

**Comment by cucaroach** [comment]
blathers backport  23.1

**Comment by cucaroach** [comment]
blathers backport 22.2 23.1

**Comment by chengxiong-ruan** [comment]
Looks like it happened again today in https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/11125167?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

Reopening it for now. But feel free to close if it's a different issue. But looks like it indeed timed out after 1h.

**Comment by cucaroach** [comment]
Latest failure log for posterity: https://gist.github.com/cucaroach/f94fdad2445225a218817cfdf6550357

**Comment by cucaroach** [comment]
It looks like this is hung in tenant startup, so I'm gonna create a new bug and close one again.

**Comment by cucaroach** [comment]
Closing and opened: https://github.com/cockroachdb/cockroach/issues/108209
