### ISSUE TITLE
storage: reservation "deadlock" scenarios

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#7849]
See https://github.com/cockroachdb/cockroach/pull/7800#issuecomment-232553614:

> You can't replay a raft log from zero, but you might be able to replay one from a previous replica if the GC queue hasn't cleaned it up. Replicas can also be initialized by splits. Here's a scenario:
> - One node in a three-node cluster goes down.
> - The replication queue will remove that replica from all ranges, but there is no other node to assign so the ranges stay in a two-replica configuration. (note that this may change - once we have preemptive snapshots working, we won't have to remove the old replica until the new one is ready to go)
> - A range splits into two, L and R.
> - The downed node comes back up; the replication queue reassigns all ranges to it. It still has copies of all the ranges it did before, including the pre-split version of L
> - The leader of range R will acquire a reservation to send a snapshot to the node. However, the snapshot will not be applied because it conflicts with the pre-split version of L.
> - The leader of range L will also acquire a reservation. The node that was down still has an initialized copy of range L, so if this range can be caught up by replaying the log no snapshot will be sent to fill the reservation.
> - When range L catches up, it applies the split trigger and initializes range R, leaking a second reservation.
> 
> We need to fill reservations when a replica is initialized by the split trigger, and if a node already has an initialized replica then we should grant any reservations without consuming a slot.
> 
> A semi-deadlock is also possible: if enough ranges split, and enough of the right-hand ranges acquire reservations before any of the left-hand ranges, no progress is possible until either the left-hand ranges are garbage-collected or the leases expire and some left-hand range is able to acquire another reservation.

**Comment by tschottdorf** [comment]
Trying to figure out whether anything is to be done here. We seem to only grab a reservation when sending a snapshot (and the grabbing happens on the receiving end). We release the reservation when the snapshot process has completed, successfully or not.
I'm tempted to think that this discussion predates the current code (streaming snapshots) and that there's nothing to do here. @petermattis?

**Comment by petermattis** [comment]
I'm pretty sure Ben's scenario predates the current code. Let's leave this on my plate to take a look at and I'll either add a test to reproduce this scenario or determine it is impossible.

**Comment by petermattis** [comment]
Removing the S-1 label because this is hypothetical, not a known issue.

**Comment by petermattis** [comment]
@benesch You've been thinking a lot about deadlocks and other issues surrounding splits and merges and snapshots. Can you take on investigating whether the issue described above is real? I've paged out most of the details which will result in either a surface-level analysis or a time consuming one. I'm hoping you're familiar enough with the code that it won't take you long to make that determination.

**Comment by benesch** [comment]
Yeah, on first brush doesn’t look like an issue with the current code. But
I’ll think about this harder before closing.

**Comment by tschottdorf** [comment]
@benesch I'm going to close this for you.
