### ISSUE TITLE
Add statement/transaction fingerprint ID to the overview page

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#78509]
This will facilitate a better searchability and filtering experience in the overview pages once a text-based search has narrowed down the results. This is for the user flow where the ID has already be identified.

It will also provide clarity throughout the troubleshooting journey when diving into fingerprint detail views. 

The ID should be hex-based and hidden by default. 

Jira issue: CRDB-14168

**Comment by maryliag** [comment]
what is the format we want to display here, also should we have this column as hidden by default?

**Comment by maryliag** [comment]
Also, the search should also look into fingerprint ID

**Comment by kevin-v-ngo** [comment]
> what is the format we want to display here, also should we have this column as hidden by default?

I'll update the issue but let's hide it by default for now. Let's also encode it to 'hex' for better readability. Similar to what we did for the contention queries/views.
