### ISSUE TITLE
Hot ranges page v1 clean-up for 22.1

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#78517]
- [ ] `Last Update` time should be labeled in 24h UTC time format (related https://github.com/cockroachdb/cockroach/issues/78442)
- [ ] ^ Technically not part of the Hot Ranges page but similar issue: can we update `Last Update` in the node details page to 24h UTC time format
- [ ] Could we truncate the decimal places for QPS values? Suggestion that we display up to 2 decimal places (cc @taroface if we should standardize to 1 or 2 decimal places)
- [ ] Update page description styling to replace the current blue informational text cc @Annebirzin for details
- [ ] Update the 'Hot Ranges' header to match the size/font/spacing of other headers in DB console ([Loom video for reference](https://www.loom.com/share/0dc178eb1f784c779bda7e9cf193cebf))   
- [ ] The page defaults to displaying the rows in decreasing QPS order. However, there is no indication on the QPS column header that the sort order is based on that column. Perhaps we can brighten the blue arrow by default when loading this page? 
  - ![Screen Recording 2022-03-25 at 02 14 PM](https://user-images.githubusercontent.com/1474303/160178330-3c1453b4-7ba1-4338-b826-88339fcb07b3.gif)

  

Jira issue: CRDB-14173

**Comment by Annebirzin** [comment]
For more context on bullet # 3: I believe the description was updated to an alert banner style to match the advanced debug page, however, I think we want to revert this back to a default description text. The reasoning is that the message on the Advanced debug page is more of a warning about the features on the page, while this is just a description/guidance around what the page is used for. You can see a similar 'description text' treatment on the Backups page in CC console. 

![Screen Shot 2022-03-28 at 11 36 33 AM](https://user-images.githubusercontent.com/51920721/160450741-170a51f6-8455-4580-a9ae-caeac1a6d07f.png)

![Screen Shot 2022-03-28 at 1 11 46 PM](https://user-images.githubusercontent.com/51920721/160451378-6aadd436-6f33-4b68-b200-8b9bac846c09.png)
