### ISSUE TITLE
storage: Replica.changeReplicasTrigger sets descriptor inappropriately

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#7851]
`Replica.changeReplicasTrigger` sets the updated range descriptor (via a call to `Replica.setDesc`) before the corresponding batch is committed. If the batch fails to commit for some reason the Replica will be in an inconsistent state. This also differs from the behavior of `Replica.splitTrigger` which updates the range descriptors in a `batch.Defer`. We should modify `changeReplicasTrigger` to use a `batch.Defer` as well.

**Comment by tschottdorf** [comment]
In the long term, we should move this up to the Store as a side effect as discussed in #6144 (but the infrastructure for that is just being dreamed up, so a Defer is strictly better in the meantime).
