### ISSUE TITLE
sql: support CASCADE/RESTRICT shorthand in INTERLEAVE IN PARENT clause

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#7854]
The initial implementation will parse but error on this shorthand described in the [rfc](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/sql_interleaved_tables.md#detailed-design).

**Comment by paperstreet** [comment]
@dt do we support multi-column foreign keys yet? If not, is there an issue I can link?

**Comment by dt** [comment]
@paperstreet #7866

**Comment by a6802739** [comment]
@paperstreet , is this similar with #9148 ?

**Comment by paperstreet** [comment]
Yeah, this is the same basic feature. This one's probably much easier than #9148 if you want to try doing it first. The basic idea is that saying

```sql
CREATE TABLE customers (id INT PRIMARY KEY, name STRING)
CREATE TABLE orders (id INT, customer_id INT, amount DECIMAL, PRIMARY KEY (customer_id, id)) INTERLEAVE IN PARENT customers (customer_id) RESTRICT
```

is a shorthand for, but exactly the same as

```sql
CREATE TABLE customers (id INT PRIMARY KEY, name STRING)
CREATE TABLE orders (id INT, customer_id INT, amount DECIMAL, PRIMARY KEY (customer_id, id), FOREIGN KEY (customer_id) REFERENCES customers (id)) INTERLEAVE IN PARENT customers (customer_id)
```

https://github.com/cockroachdb/cockroach/blob/bad99359066aea31aef1ffce81fbdb6bd7a535b9/sql/create.go#L720-L723 is the relevant hook

**Comment by a6802739** [comment]
@paperstreet , do you mean I should add foreign key function when it match `CASCADE/RESTRICT shorthand`?

what's different between CASCADE and RESTRICT? And What is DELETE CASCADE actually equal to?

**Comment by jordanlewis** [comment]
This is a nice straightforward issue. It would be a good starter project.

**Comment by jordanlewis** [comment]
cc @rohany @solongordon

**Comment by jordanlewis** [comment]
Closing this as wont fix.
