### ISSUE TITLE
rowexec: TestUncertaintyErrorIsReturned is flakey

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#78610]
**Describe the problem**

It appears that the test can fail to make progress. I don't know how new this is. 

Example: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_Test/4697830?buildTab=overview&showRootCauses=false&expandBuildProblemsSection=true&expandBuildChangesSection=true&expandBuildDeploymentsSection=true#%2Ftest;%2FlogTestUncertaintyErrorIsReturned696690876;%2FStartServer8244306;%2FStartServer1023145469;%2FStartServer1590656461

Jira issue: CRDB-14196

**Comment by ajwerner** [comment]
I'm torn on the team. I'm going to repro before selecting a victim.

**Comment by ajwerner** [comment]
Okay, I bisected this to 208e2b4bbb1282e4a97457a767dddb3928574794 / https://github.com/cockroachdb/cockroach/pull/74077. It reproduces pretty readily, so I'm moving it over to kv. cc @shralex @nvanbenschoten

**Comment by nvanbenschoten** [comment]
I'm still entirely not sure what to make of this test or why it began failing, but one subtle aspect of the test which may be related is that the `tableIDsToFilter` field is optional. If not set, every `Scan` request sent to the target node (which is randomly chosen) begins returning a `ReadWithinUncertaintyIntervalError`, not just those sent to the SQL table by the query. I wonder if some new background operation is getting caught up in the overly broad filter.

**Comment by nvanbenschoten** [comment]
The test is stable with the following patch, which ensures that the filter only applies to the test's query.
```go
diff --git a/pkg/sql/rowexec/processors_test.go b/pkg/sql/rowexec/processors_test.go
index 3008d857eb..a0dd287736 100644
--- a/pkg/sql/rowexec/processors_test.go
+++ b/pkg/sql/rowexec/processors_test.go
@@ -648,7 +648,7 @@ func TestUncertaintyErrorIsReturned(t *testing.T) {
                                                        } else if tableIDsToFilter != nil {
                                                                shouldReturnUncertaintyError := false
                                                                for _, tableID := range tableIDsToFilter {
-                                                                       if strings.Contains(req.(*roachpb.ScanRequest).Key.String(), fmt.Sprintf("/Table/%d", tableID)) {
+                                                                       if strings.HasPrefix(req.(*roachpb.ScanRequest).Key.String(), fmt.Sprintf("/Table/%d", tableID)) {
                                                                                shouldReturnUncertaintyError = true
                                                                                break
                                                                        }
@@ -778,7 +778,10 @@ func TestUncertaintyErrorIsReturned(t *testing.T) {
                                                require.Equal(t, testCase.expectedPlanURL, actualPlanURL)
                                        }()

-                                       errorOrigin := []errorOriginSpec{{nodeIdx: allNodeIdxs[rng.Intn(len(allNodeIdxs))]}}
+                                       errorOrigin := []errorOriginSpec{{
+                                               nodeIdx:    allNodeIdxs[rng.Intn(len(allNodeIdxs))],
+                                               tableNames: []string{"t"},
+                                       }}
                                        if testCase.overrideErrorOrigin != nil {
                                                errorOrigin = testCase.overrideErrorOrigin
                                        }
```

I still don't know why it began flaking, but this feels like a test issue and nothing more severe. I'll dig a little deeper before packing this up into a fix.
