### ISSUE TITLE
observability: expose prometheus metrics related to upgrade finalization

### ISSUE THREAD

**Issue by nick-jones** [cockroachdb/cockroach#78620]
**Is your feature request related to a problem? Please describe.**

*Upgrade not finalized whilst preserve_downgrade_option is not set*

We recently looked to upgrade numerous clusters from `21.1` to `21.2`. As a matter of course we disable auto upgrade finalisation (as recommended). We left the clusters in this state for a day or two before finalizing the upgrade. As per normal we triggered the finalization by executing

```
RESET CLUSTER SETTING cluster.preserve_downgrade_option;
```

From that point on, cockroachdb is expected to finalise the upgrade. Except for two clusters it did not. And we knew this because the Jobs page continued to spit out an error (see #78351) a good 15 minutes after clearing the cluster setting. Problem is, that is not how we should have figured out there was an issue. As it happens the root cause to the finalize being blocked was nodes stuck in `decommissioning` state for unknown reasons (see also https://github.com/cockroachdb/cockroach/issues/73825#issuecomment-996192870). We were able to concretely determine the upgrade finalise hadn't completed by issuing `SHOW JOBS;` (we expected a number to be created for internal migrations, but there were none), and also by using `SHOW CLUSTER SETTING version;` which yielded `21.1`

--

*Upgrade not finalized whilst preserve_downgrade_option is set*

Off the back of the issues described, another thing that came to mind is - whilst working with 10+ clusters, how does one know concretely which ones have been finalized vs not (in particular, which ones have I cleared `preserve_downgrade_option` against). I currently keep notes and tick each one off, but I'd much prefer to have something flagged to me if a cluster has not been upgrade finalized after some arbitrary deadline (say 1 week), as it implies something has been forgotten.

**Describe the solution you'd like**

Ideally we'd like to have prometheus metrics exposed that allow us to alert on circumstances that are _not_ expected in relation to finalization; the fact we had to figure this out by hand is slightly worrying. The two things that come to mind are:

- If a cluster is in a state where it could be finalized (i.e. `cluster.preserve_downgrade_option` is set), and remains in that  state for longer than $duration, alert
- If a cluster is in a state where it should be finalized (i.e. `cluster.preserve_downgrade_option` is not set) but the "internal" active cluster version remains behind the binary version for $duration, alert

Most naively I'd think that surfacing what we currently see from the following two cluster settings would be helpful in this regard, but I'm sure there are other options to consider:

```
SHOW CLUSTER SETTING cluster.preserve_downgrade_option;
SHOW CLUSTER SETTING version;
```

**Describe alternatives you've considered**

There would be the option of adding a bespoke exporter that exposes cluster settings, which would work as a stop gap - we'd prefer not to have to do this, unless recommended.

**Additional context**

Current version info when in a non-finalized state:

```
$ curl -s http://localhost:8080/_status/vars | grep '21\.'
build_timestamp{tag="v21.2.7",go_version="go1.16.6"} 1.647275846e+09
$ cockroach sql --insecure --execute 'SHOW CLUSTER SETTING cluster.preserve_downgrade_option;'
  cluster.preserve_downgrade_option
-------------------------------------
  21.1
(1 row)
$ cockroach sql --insecure --execute 'SHOW CLUSTER SETTING version;'
  version
-----------
  21.1
(1 row)
$ cockroach sql --insecure --execute 'SELECT version();'
                                          version
-------------------------------------------------------------------------------------------
  CockroachDB CCL v21.2.7 (x86_64-unknown-linux-gnu, built 2022/03/14 16:37:26, go1.16.6)
(1 row)
```

--

The data that is interesting _is_ visible under the `altereredSettings` key of /_status/diagnostics/local (this is a json endpoint, so not suitable for prometheus scraping):

```
  "alteredSettings": {
    "cluster.preserve_downgrade_option": "21.1",
    "cluster.secret": "<redacted>",
    "diagnostics.reporting.enabled": "true",
    "version": "21.1"
  },
```

--

#66987 raises similar points but talks about exposing this in the DB console - whilst that is undoubtedly useful, it'd be great to expose this information in prometheus metrics as well.

Jira issue: CRDB-14199

**Comment by tbg** [comment]
Thanks for filing the issue, Nick! Tagging KV-obs to take a look.

Possibly also worth a look by @cockroachdb/obs-inf-prs - ultimately there is also a question about alerting here.
