### ISSUE TITLE
Surface auto-statistics setting for non-admin users in DB Console

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/cockroach#78662]
Related to https://github.com/cockroachdb/cockroach/issues/77974.

The auto statistics collection cluster setting status is not shown in the DB Console to users without the permissions to see cluster settings (i.e., all non-admin users).

As a follow-up to https://github.com/cockroachdb/cockroach/pull/78266 and https://github.com/cockroachdb/cockroach/pull/78655 , we should look into surfacing this cluster setting status in the DB Console for non-admin users, but with a tooltip explaining that additional permissions are required to change the cluster setting.

See https://github.com/cockroachdb/cockroach/issues/77974#issuecomment-1072656497 for background.

Jira issue: CRDB-14207

**Comment by maryliag** [comment]
No longer a priority
