### ISSUE TITLE
latest tag out of date in docker cockroach-unstable repo

### ISSUE THREAD

**Issue by ecwall** [cockroachdb/cockroach#78663]
The latest tag is out of date in the cockroach-unstable repo https://hub.docker.com/r/cockroachdb/cockroach-unstable/tags
<img width="793" alt="image" src="https://user-images.githubusercontent.com/8524448/160483465-12246cd4-275b-4574-8cba-6c60af00f854.png">

Jira issue: CRDB-14208

**Comment by rail** [comment]
I updated the latest tag. PR incoming.

**Comment by rail** [comment]
Manually synced with Jira
