### ISSUE TITLE
sql,admission: ERROR: liveness session expired XXXms before transaction

### ISSUE THREAD

**Issue by cucaroach** [cockroachdb/cockroach#78691]
Multiple tenants hitting a kv server with a large batched insert load can cause this error.   For example see:

https://github.com/cockroachdb/cockroach/pull/77481

Changing warmup batch size from 100 to 1000 reliably demonstrates the issue.

Jira issue: CRDB-14219

**Comment by cucaroach** [comment]
I hit this in another simpler test with just 1 node in the storage tier, in this case I wasn't getting any table statistics so I looked at error from:
```
> github.com/cockroachdb/cockroach/pkg/sql/stats.(*Refresher).refreshStats() github.com/cockroachdb/cockroach/pkg/sql/stats/pkg/sql/stats/automatic_stats.go:773 (hits goroutine(2072):2 total:2) (PC: 0x1a9ca91)
Warning: debugging optimized function
(dlv) p err.cause.cause
error(*github.com/cockroachdb/errors/withstack.withStack) *{
        cause: error(*github.com/cockroachdb/errors/errutil.leafError) *{
                msg: "liveness session expired 8m6.020911792s before transaction",},
        stack: *github.com/cockroachdb/errors/withstack.stack len: 11, cap: 32, [27814108,52907324,52907254,52905276,52968880,52903647,52858847,52852936,52847627,54041388,4978305],}
```

Then I noticed my kv node log was full of:

```
W220923 13:24:46.348441 301 13@kv/kvserver/replicate_queue.go:815 ⋮ [n1,replicate,s1,r122878/1:‹/Tenant/11/Table/104/1/0/968…›] 1941239  error processing replica: ‹0 of 1 live stores are able to take a new replica for the range (1 already has a voter, 0 already have a non-voter); likely not enough nodes in cluster›‹›
W220923 13:24:46.348441 301 13@kv/kvserver/replicate_queue.go:815 ⋮ [n1,replicate,s1,r122878/1:‹/Tenant/11/Table/104/1/0/968…›] 1941239 +‹trace:›
W220923 13:24:46.348441 301 13@kv/kvserver/replicate_queue.go:815 ⋮ [n1,replicate,s1,r122878/1:‹/Tenant/11/Table/104/1/0/968…›] 1941239 +‹     0.000ms      0.000ms    === operation:process replica _unfinished:1 _verbose:1 node:1 replicate: store:1 range:122878/1:/Tenant/11/Table/104/1/0/968…›
W220923 13:24:46.348441 301 13@kv/kvserver/replicate_queue.go:815 ⋮ [n1,replicate,s1,r122878/1:‹/Tenant/11/Table/104/1/0/968…›] 1941239 +‹     0.036ms      0.036ms    event:kv/kvserver/allocator/allocatorimpl/allocator.go:682 [n1,replicate,s1,r122878/1:/Tenant/11/Table/104/1/0/968…] add voter - missing voter need=3, have=1, priority=10001.00›
W220923 13:24:46.348441 301 13@kv/kvserver/replicate_queue.go:815 ⋮ [n1,replicate,s1,r122878/1:‹/Tenant/11/Table/104/1/0/968…›] 1941239 +‹     0.050ms      0.014ms    event:kv/kvserver/replicate_queue.go:864 [n1,replicate,s1,r122878/1:/Tenant/11/Table/104/1/0/968…] next replica action: add voter›
W220923 13:24:46.348441 301 13@kv/kvserver/replicate_queue.go:815 ⋮ [n1,replicate,s1,r122878/1:‹/Tenant/11/Table/104/1/0/968…›] 1941239 +‹     0.087ms      0.037ms    event:kv/kvserver/allocator/allocatorimpl/allocator.go:1037 [n1,replicate,s1,r122878/1:/Tenant/11/Table/104/1/0/968…] allocate voter: []›
W220923 13:24:46.349130 301 13@kv/kvserver/replicate_queue.go:815 ⋮ [n1,replicate,s1,r108120/1:‹/Tenant/11/Table/104/1/5/839…›] 1941240  error processing replica: ‹0 of 1 live stores are able to take a new replica for the range (1 already has a voter, 0 already have a non-voter); likely not enough nodes in cluster›‹›
```

So I added two more storage nodes and now its happy.  So current hypothesis is lease errors occur due to under provisioned storage tier that's in an unhappy state.  Should I close this or do we care about the ability to function in this situation?

**Comment by ajwerner** [comment]
If you pause in your debugger for too long, I'd expect this.

**Comment by ajwerner** [comment]
I think we close this, I'm not sure there's much to do here. The second one is https://github.com/cockroachdb/cockroach/issues/87452.

**Comment by irfansharif** [comment]
Re-enabled these tests which started tripping again in https://github.com/cockroachdb/cockroach/issues/97448. Re-opening to track:

> Why are we returning this error as opposed to just forcing the system to retry internally?

And also maybe using higher AC priority for session renewal goroutines, which would help with:

> How did we get to a place where the session was about to expire, and

**Comment by irfansharif** [comment]
> And also maybe using higher AC priority for session renewal goroutines:

Actually the higher pri won’t help, since session renewal is bypassing AC altogether: https://github.com/cockroachdb/cockroach/blob/51295787ed2d48280f040ca868989252ba09c572/pkg/sql/sqlliveness/slstorage/slstorage.go#L456

That uses `AdmissionHeader_OTHER`, which hooks into: https://github.com/cockroachdb/cockroach/blob/736a67e0d36cc545bf74d65db069ee895ff9bea0/pkg/kv/kvserver/kvadmission/kvadmission.go#L210-L212

**Comment by irfansharif** [comment]
> Actually the higher pri won’t help, since session renewal is bypassing AC altogether.

Actually, I’m being daft. This is a multi-tenant test, so we’re actually not bypassing AC. We’re just using regular priority then for SQL session extensions.

https://github.com/cockroachdb/cockroach/blob/736a67e0d36cc545bf74d65db069ee895ff9bea0/pkg/kv/kvserver/kvadmission/kvadmission.go#L203-L210

I'll go back to explicitly using high pri first.
