### ISSUE TITLE
sql: track an estimate of the number of rows in each table

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#7869]
It would be useful to have access to an approximation of the number of rows in teach table for query optimizations. This is useful for:
- optimizing JOINs
- optimizing union/intersect
- reporting to users in the UI
- later on, optimizing sub-queries (whether to load data in memory or in an on-disk table)

Also perhaps useful to expose as user-facing function, see #7825 for an example use case.

**Comment by knz** [comment]
Food for thought: @petermattis suggested using gossiping to propagate the table sizes.

**Comment by petermattis** [comment]
I don't recall suggesting gossiping table sizes. My recollection is that I suggested using the meta2 table to provide size estimates. The meta2 table contains an entry for every range and each entry contains the start and end keys. This gives both a very rough estimate of the table size and a sampling of the rows.

**Comment by tschottdorf** [comment]
See also https://github.com/cockroachdb/cockroach/issues/7825#issuecomment-232638966 (to translate the problem into either a read-only roundtrip to all replicas holding parts of the range, perhaps by using `DistSender` caches in addition (which could keep additional info about replicas they communicate with often essentially "for free").
I think those ideas are preferrable to using the meta ranges directly as an abundance of `COUNT(*)` shouldn't translate to excessive load on the meta ranges but instead either be served a) by aggregation over the replicas directly or better b) cached by DistSender (but then of course there's a question of cache policies, etc).

**Comment by knz** [comment]
More demand for this:
- See question on the forum: https://forum.cockroachlabs.com/t/how-to-quickly-retrieve-estimate-number-of-rows-in-table/263/2
- See #9434 #9433  #7779

I got an idea last week when talking with @mrtracy:
- maintain per-table counters of added and removed rows in the SQL session during a txn
- upon commit, use the per-txn counters to update per-node counters, stored in the db (separate rows per node, to reduce contention), possibly in an asynchronous internal txn (the counts need not be accurate)
- every day/week run KV-layer scans on each node to make the counts more accurate
- when a user does `SELECT reltuples FROM pg_class WHERE relname = X` translate this to an aggregate query on the counter table across all nodes
- use this table in the admin UI

See also the discussion started at https://github.com/cockroachdb/cockroach/issues/7825#issuecomment-232638966

cc @RaduBerinde what do you think of the idea above?

**Comment by RaduBerinde** [comment]
It sounds good to me; I would just say that any infrastructure along these lines should be designed to support more than row counts (histograms, number of distinct values per column). Some of these we may not be able to update on queries but we can at least compute them in the daily/weekly scans.

**Comment by paperstreet** [comment]
whatever we do should definitely be RFC'd first

**Comment by jordanlewis** [comment]
cc @rytaft superseded by your work?

**Comment by rytaft** [comment]
Yes, it is already possible to get these stats using `CREATE STATISTICS` and `SHOW STATISTICS`. The stats are maintained in `system.table_statistics`, and we are currently working on ways of refreshing them automatically. I think you can probably close this issue.
