### ISSUE TITLE
storage: test preemptive snapshot which arrives before previous Replica is gc'ed

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#7874]
During #7833, it was discovered that we don't test this case (which is not surprising as our preemptive snapshot test coverage is generally low, and they are currently disabled).

**Comment by petermattis** [comment]
Preemptive snapshots have been enabled for a while. Do we now have a test case which covers this scenario?

**Comment by petermattis** [comment]
All non-Raft snapshots are preemptive snapshots, so we're almost certainly testing their use. I agree that closing this issue seems appropriate.
