### ISSUE TITLE
storage: Refactor GC RPC API

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#7880]
The GC method is currently unique in that it is a range request which also contains keys in the body of the GCRequest. The DistSender is unaware of the keys in the body, so if it must split a GC request across ranges both sides get the full list of keys, including those outside their key span. The server side expects this and silently discards any keys that fall outside its span. However, this can mask errors such as the fact that we are unable to GC transaction records created by splits (#7652). It would be better to enforce that a GCRequest never contains keys outside its span.

We could do this in two ways:
- Give DistSender a hook to allow it to partition the keys contained in GCRequest whenever it must truncate the Span.
- Instead of one GCRequest containing a list of keys, replace GCRequest with a single-key GC operation. This makes it more consistent with other operations and allows DistSender to handle it naturally, although it might be somewhat less efficient. We shouldn't undertake this change until after moving to proposer-evaluated KV.

**Comment by tschottdorf** [comment]
There's also a third, somewhat more involved, option: We have `(*Replica).mu.state.GCThreshold`. Reads/writes for at timestamps `<= GCThreshold` are refused, so we can be more flexible with data at lower timestamps. If a first non-deleted kv pair at a timestamp below `GCThreshold` exists, it can be moved up to timestamp `GCThreshold`. A second, third, ... such kv pair can be cleared out (and this is what the GC queue currently does). So we can (pre-proposed-eval'ed-kv) completely omit the costly GCRequests from the GC queue and trigger Replica-level logic which combs through the Replica and clears/discards old data.
If we make sure that this is only a single goroutine per Replica, we could do it outside of Raft, but we would have to make decently sized changes in how we write the stats and make all replicated-only iterations aware of the wild west that might be going on at or below `GCThreshold`.
I don't think we should do this (at least not now, but gc has been an issue for many databases and saving work here can be good). It's only going to be worth it on replicas which are largely GCable, too.

**Comment by tschottdorf** [comment]
Other than that, I agree that unbundling the keys and making GCRequest single-key is the way to go, the only potential problem down the line being the cost.

**Comment by tschottdorf** [comment]
There's also a more immediate fix, which is to let GCRequest return the number of keys it actually GC'ed. DistSender would then add up those numbers (automatically, once `GCResponse` implements `Combinable`) and return it to the client in the response. The client can then verify that `gcResponse.NumGC == len(gcArgs.Keys)`.

**Comment by petermattis** [comment]
I'd prefer making `GCRequest` symmetric with other request types and only operate on a single key. `MVCCGarbageCollect` currently contains a loop which doesn't share any state between iterations that wouldn't also be shared by pulling the loop out to a higher level. (The only shared state is the iterator, but we cache that within the `engine.Batch`).

**Comment by tschottdorf** [comment]
I agree that that's the prettiest solution.

**Comment by tschottdorf** [comment]
This morning in core standup, @tamird brought this idea up again. Now that the deficiencies of the GC queue are more apparent (https://github.com/cockroachdb/cockroach/issues/15756) and proposer-evaluated KV is in, I think this is worth tackling.

One item in #15756 is that `GCRequests` currently take a (practically) "global" span for the command queue. That would be mitigated by this change as `GCRequest` would declare the actual keys it touches.

As a follow-up optimization, we could still have `GCRequest` bypass the command queue later if that becomes relevant, but it hasn't been so far - the `GCRequest`s we're seeing today in problematic repros are *empty* (though once the GC queue is fixed they wouldn't be).

**Comment by petermattis** [comment]
Seems good to tackle this.

**Comment by tschottdorf** [comment]
@tamird yours as we discussed. Here's a stash I had lying around with some concerns I had about keys:

```diff
diff --git a/pkg/storage/gc_queue.go b/pkg/storage/gc_queue.go
index cdff70308..2aca4632d 100644
--- a/pkg/storage/gc_queue.go
+++ b/pkg/storage/gc_queue.go
@@ -756,6 +756,7 @@ func RunGC(
 			break
 		}
 		iterKey := iter.Key()
+		// TODO(tschottdorf): expBaseKey is nil in the first iteration. Probably harmless, but not intentional.
 		if !iterKey.IsValue() || !iterKey.Key.Equal(expBaseKey) {
 			// Moving to the next key (& values).
 			processKeysAndValues()
diff --git a/pkg/storage/replica.go b/pkg/storage/replica.go
index 5087b7c36..ef22e9e3c 100644
--- a/pkg/storage/replica.go
+++ b/pkg/storage/replica.go
@@ -1489,6 +1489,9 @@ func (r *Replica) Send(
 func (r *Replica) requestCanProceed(rspan roachpb.RSpan, ts hlc.Timestamp) error {
 	r.mu.Lock()
 	desc := r.mu.state.Desc
+	// TODO(tschottdorf): is there a problem here? We check this key, but I
+	// don't think we have non-transactional reads (or transactional reads
+	// without BeginTransaction) block on this.
 	threshold := r.mu.state.GCThreshold
 	r.mu.Unlock()
 	if !threshold.Less(ts) {
diff --git a/pkg/storage/replica_command.go b/pkg/storage/replica_command.go
index a6f7ac2c6..912de08fe 100644
--- a/pkg/storage/replica_command.go
+++ b/pkg/storage/replica_command.go
@@ -1375,6 +1375,8 @@ func declareKeysGC(
 	for _, key := range gcr.Keys {
 		spans.Add(SpanReadWrite, roachpb.Span{Key: key.Key})
 	}
+	// TODO(tschottdorf): checked by all ops, but not declared by them
+	// only for BeginTxn we declare the below key, but doesn't seem enough..
 	spans.Add(SpanReadWrite, roachpb.Span{Key: keys.RangeLastGCKey(header.RangeID)})
 	spans.Add(SpanReadWrite, roachpb.Span{
 		// TODO(bdarnell): since this must be checked by all
@@ -1383,6 +1385,8 @@ func declareKeysGC(
 		// past to be affected by the in-flight GCRequest (i.e.
 		// normally none). This means this key would be special
 		// cased and not tracked by the command queue.
+		//
+		// TODO(tschottdorf): don't think this is checked by all reads...
 		Key: keys.RangeTxnSpanGCThresholdKey(header.RangeID),
 	})
 	spans.Add(SpanReadOnly, roachpb.Span{Key: keys.RangeDescriptorKey(desc.StartKey)})

```

**Comment by cuongdo** [comment]
@tamird is this still happening for 1.1?

**Comment by tamird** [comment]
Nope!

**Comment by tschottdorf** [comment]
@cuongdo this would be a nice starter project. This should be fairly straightforward but touches all the relevant aspects of the storage package without getting too bogged up in detail, and at the same time requires a migration. Assigning for triage.

**Comment by tschottdorf** [comment]
Moving to Later as I think we've not done this for long enough to not want to bother until there's a specific reason.

**Comment by tschottdorf** [comment]
We're unlikely to put in the work to change this at this point.
