### ISSUE TITLE
ui: fix clock offset

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#7887]
As mentioned in #5728 the clock offset graph in the UI seems to be incorrect.

**Comment by tamird** [comment]
FYI this is gonna need fixing on the server side. As of https://github.com/cockroachdb/cockroach/pull/5512 we're not doing anything at all with the clock offset metrics on the server (and the test is skipped).

**Comment by mrtracy** [comment]
@mberhault There are currently no graphs around clock offset either in the Admin UI or in our test cluster grafana dashboards.  Is this still something we want to monitor via a graph? Have the metrics been improved to the point that an accurate graph is possible?

**Comment by mberhault** [comment]
we have two metrics for each node:
```
# HELP clock_offset_meannanos 
# TYPE clock_offset_meannanos gauge
clock_offset_meannanos -8914
# HELP clock_offset_stddevnanos 
# TYPE clock_offset_stddevnanos gauge
clock_offset_stddevnanos 222024
```

I've just added a graph for `meannanos` on the `runtime` dashboard.
There's a massive discrepancy in offset between clusters. I'm going to add ntp details to the node exporter and see if this tells us anything more. Then we can figure out how to best use this metric.

Basically, I'd say let's prototype it on grafana until we find something we find useful, then put it on the admin UI.
