### ISSUE TITLE
zoneconfig: alter table zone config does not show error if replication factor is set too high

### ISSUE THREAD

**Issue by wangshihang-inspur** [cockroachdb/cockroach#78935]
**To Reproduce**

1. Set up CockroachDB cluster with three nodes
2. create a table and alter this table‘s zone config：voter replica set to 4
3. actually this should not work because this cluster only has 3 nodes, but this alter stmt should give an error
4. for now, crdb does not give an error and this alter stmt does not work properly either

**Expected behavior**
give a graceful error

**Environment:**
 - CockroachDB version 21.2
 - Server OS: linux
 - Client app: cockroach sql

Jira issue: CRDB-14451

**Comment by rafiss** [comment]
A similar question came up here: https://stackoverflow.com/a/65440272/3642359

In case you hadn't seen, the DB Console will show a warning that says that some ranges are under-replicated. https://www.cockroachlabs.com/docs/v21.2/ui-cluster-overview-page

**Comment by wangshihang-inspur** [comment]
thanks for your reply :)
