### ISSUE TITLE
storage: test that replica removal adds to replica GC queue

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#7893]
`Store.changeReplicasTrigger` adds to the replica GC queue if it is removing the current replica. We need to add a test that this is working as expected.

**Comment by petermattis** [comment]
@jordanlewis This should be straightforward to test with the `TestCluster` facility or there might be an existing test that could be extended.

**Comment by jordanlewis** [comment]
I'm not the right person for this - sending back to you for triage as I never took a look.

**Comment by tschottdorf** [comment]
Closing. It's been two years.
