### ISSUE TITLE
ui: circuit breaker trip events should be plotted as rate

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#78939]
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/5076964/160583466-a1ce22b8-3f58-4fb2-97da-93b798152bd2.png">

This should be plotted as a rate, not as an absolute value (and the description should reflect this).

Jira issue: CRDB-14454

**Comment by koorosh** [comment]
@tbg , as far as  I understand, this metric represents the accumulated number of tripped events since the process started. 

This metric is incremented only and isn't reset:
https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvserver/replica_init.go#L140

I suppose that current metrics implementation doesn't allow to plot the rate of circuit breaker events.
Would it be more convenient to extend (add one more metric) to track events rate?

**Comment by tbg** [comment]
Hi Andrii, our built-in timeseries allows querying counters as rates, see for example here:

https://github.com/cockroachdb/cockroach/blob/2d0d15f1b8bc4178a4e44ee1b6a08cf08b1cc648/pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/hardware.tsx#L67-L77

We would want `nonNegativeRate` here as well.

**Comment by koorosh** [comment]
What do you think about the following description?
```
The number of circuit breaker events occurred per second across all nodes since the process started.
```
cc @taroface

**Comment by tbg** [comment]
The counter underpinning the graph actually doesn't reflect anything about the number of ReplicaUnavailableErrors. It's the number of times a replica has determined itself as unavailable. The error is emitted each time a client request arrives after that, so those are not the same thing.

**Comment by tbg** [comment]
Actually I wonder if we shouldn't do the easy thing and remove this chart. We are already plotting the number of replicas that are currently tripped. The "rate at which they trip" isn't going to be helpful to end-users most of the time. You just want that first graph to be flat at zero; if it isn't then the rate isn't going to tell you much new.

**Comment by andf-crl** [comment]
Makes sense to me!

**Comment by koorosh** [comment]
> Actually I wonder if we shouldn't do the easy thing and remove this chart. 

Ack, will remove this chart then https://github.com/cockroachdb/cockroach/issues/81571
