### ISSUE TITLE
migration/migrations: flakey TestPublicSchemaMigration500Tables

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#78947]
**Describe the problem**

`TestPublicSchemaMigration500Tables` sometimes times out:

```
I220329 04:50:31.133283 17210 jobs/registry.go:1157  [n1] 1088  job 748614541538033665: running execution encountered retriable error: non-cancelable: running migration for 21.2-34: command is too large: 9577839 bytes (max: 4194304)
```

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_GitHubCiOptional/4713245?showRootCauses=false&expandBuildProblemsSection=true&expandBuildTestsSection=true&expandBuildChangesSection=true&buildTab=overview

I don't really get how it happens. Maybe this command is being generated elsewhere? 

Jira issue: CRDB-14459

**Comment by ajwerner** [comment]
Turns out to be somewhat common on release-22.1

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/4713230?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

**Comment by RichardJCai** [comment]
> I don't really get how it happens. Maybe this command is being generated elsewhere?

Yeah I'd guess the command is coming from elsewhere?

**Comment by RichardJCai** [comment]
Made PR to skip for now
https://github.com/cockroachdb/cockroach/pull/78971
