### ISSUE TITLE
workload: use IMPORT parallelism proportional to available DistSQL pods in multi-tenant mode

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#78968]
In https://github.com/cockroachdb/cockroach/pull/78418, we addressed https://github.com/cockroachdb/cockroach/issues/75449 by using a parallelism of 1 when running IMPORT in multi-tenant mode. We set `numNodes` to 1 because we don't support DistSQL for IMPORTs in multi-tenant mode. Longer-term, however, we'll want an API which allows tenants to query the number of DistSQL pods available for these types of IMPORT jobs.

Jira issue: CRDB-14466

Epic CRDB-18499

**Comment by stevendanna** [comment]
While it would definitely be ideal to be able to auto-discover the number of nodes, we could also make the import parallelism a command line/query option so that tests that know the number of sql pods they are spinning up can scale their imports appropriately.
