### ISSUE TITLE
sql: detection of single-statement implicit transactions broken in batch

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#78970]
**Describe the problem**

In https://github.com/cockroachdb/cockroach/pull/76834 we changed the behavior of how a batch of statements are
executed when sent in a single protocol message. A number of features in cockroach use the `TxnImplicit` field of the `EvalContext` to decide whether the statement being executed is a single-statement explicit transaction. Below is a non-exhaustive list:

* `ALTER COLUMN TYPE`
* `ALTER TABLE DROP COLUMN`
* `CREATE TABLE AS SELECT`
* `REFRESH MATERIALIZED VIEW`
* enabling the declarative schema changer
* deserializing the session state
* `SET CLUSTER SETTING`
* `SET LOCAL`
* `DECLARE CURSOR`
   * Maybe we also don't want to allow this in the single batch, I don't know
* `crdb_internal.gc_tenant`
* Some [code about statement stats and their transaction fingerprint](https://github.com/cockroachdb/cockroach/blob/81fc97d1d2f1850e6ef800b01c40485e6a889629/pkg/sql/executor_statement_metrics.go#L187-L193).
* Metrics tracking in [here](https://github.com/cockroachdb/cockroach/blob/0eeed71b0657c2f623fc402788cf0c6e1684aa08/pkg/sql/conn_executor_exec.go#L2090-L2095).

This might be as simple as moving everything to use the `AutoCommit` concept instead of the `Implicit` concept. I'm not sure. I think `AutoCommit` might permit these things to happen as the last statement in a multi-statement "implicit" transaction. That worries me.

Jira issue: CRDB-14467

**Comment by ajwerner** [comment]
The work in https://github.com/cockroachdb/cockroach/pull/78512 attempted to address some of this, but is incomplete

**Comment by rafiss** [comment]
further work on https://github.com/cockroachdb/cockroach/pull/78512 seems to have completely addressed this
