### ISSUE TITLE
sql: materialized view created with incorrect fixed timestamp

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#79015]
**Describe the problem**

```
# Test CREATE MATERIALIZED VIEW referring to a sequence.
statement ok
CREATE SEQUENCE seq;
CREATE MATERIALIZED VIEW view_from_seq AS (SELECT nextval('seq'))
```
```
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/4047/execroot/cockroach/bazel-out/k8-dbg/bin/pkg/sql/logictest/logictest_test_/logictest_test.runfiles/cockroach/pkg/sql/logictest/testdata/logic_test/materialized_view:214:
        expected success, but found
        (42P01) nextval(): relation "[115]" does not exist
        errors.go:161: in NewUndefinedRelationError()
```
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_GitHubCiOptional/4726513?buildTab=overview&showRootCauses=false&expandBuildProblemsSection=true&expandBuildTestsSection=true&expandBuildChangesSection=true

Seems like the root cause is if the transaction gets pushed, then the `CreateAsOfTime` will be before the other descriptors created in the same transaction. See 
https://github.com/cockroachdb/cockroach/blob/a0b4a33c3352aaa0c36115e34d1e3ad104f944a7/pkg/sql/schema_changer.go#L420 and 

https://github.com/cockroachdb/cockroach/blob/23391d0ca3c86a81d9c3180e2f4755da54c38580/pkg/sql/create_view.go#L239

The solution here is to remove the code which sets the creation time as we'll set it automatically when we read the descriptor for the first time.

Jira issue: CRDB-14500

**Comment by postamar** [comment]
@Xiang-Gu can you take this on please? On the face of it, the fix is a one-liner but requires creating a unit test to protect against future regressions.
