### ISSUE TITLE
sql: BenchmarkSQL/MultinodeCockroach/InsertFK occasionally hangs on 21.2

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#79054]
On d54f5b78be I had `BenchmarkSQL/MultinodeCockroach/InsertFK/count=100/nFks=10` get stuck for several minutes, after which I killed the process. The goroutine dump is [attached](https://github.com/cockroachdb/cockroach/files/8382496/dump.zip). This was surfaced by #78592, and I remember seeing the same problem when going through micro-regressions half a year ago too.

In terms of timing I think the benchmark was started 13 minutes prior to the dump, and the benchmark run was stuck for like 5-7 minutes.

My guess is that the stuck things are schema-related, possibly to `catalogkv.MustGetTableDescByID` in `gcjob.updateStatusForGCElements`.

Jira issue: CRDB-14521

**Comment by ajwerner** [comment]
Any chance you have logs? All of the blocked goroutines are stuck in kv, in particular, with kv looking to acquire a range lease:

```
goroutine 1507842 [select, 5 minutes]:
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).redirectOnOrAcquireLeaseForRequest.func2(0xc01dac9ff0, 0x0, 0xc004821500, {0x4f8b118, 0xc0794cb5f0}, 0xc07994fe50, 0xc03d58d808)
```

**Comment by yuzefovich** [comment]
No, unfortunately I don't have anything else. The benchmark was relatively quick (on the order of tens runs) to get stuck though if you wanna reproduce it yourself.

**Comment by ajwerner** [comment]
To be clear, this doesn't repro in 21.2 or later, right?

**Comment by yuzefovich** [comment]
This reproduces on 21.2 branch, but not later.

**Comment by mwang1026** [comment]
@lidorcarmel can you spend ~1 day max looking into this please? If it's taking more than that would appreciate a report back.

**Comment by lidorcarmel** [comment]
not reproducible, closing.
sorry @mwang1026 for the delay.
I did
```
git checkout d54f5b78be06495f5d7dc1c1aab96dacf3d14350
```
and ran this 30+ times:
```
make bench PKG=./pkg/bench BENCHES=BenchmarkSQL/MultinodeCockroach/InsertFK/count=100/nFks=10
```
all passed.
