### ISSUE TITLE
tests/docs: implement a clojure/jdbc friendly version of the restart protocol

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#7912]
Requested by @bdarnell in https://github.com/cockroachdb/jepsen/pull/17#discussion_r71263587 

in reaction to https://github.com/knz/jepsen/blob/683faf0f885b305155c8887c1ce5817b780c0f6d/cockroachdb/src/jepsen/cockroach.clj#L309-L314:

```
;; FIXME: CockroachDB features a custom txn retry protocol, documented in
;; https://www.cockroachlabs.com/docs/build-a-test-app.html#step-4-execute-transactions-from-a-client
;; However it seems that the JDBC driver and/or clojure sqldb package does
;; not enable one to reuse the transaction after an exception was thrown. So
;; we use a (more overweight) traditional retry loop here instead. This
;; may reduce performance.
```

Both the Jepsen tests and the documentation need new Clojure code to properly support txn restarts.

**Comment by knz** [comment]
PR sent upstream: https://github.com/jepsen-io/jepsen/pull/157

**Comment by knz** [comment]
The docs part is tracked here: https://github.com/cockroachdb/docs/issues/646

**Comment by spencerkimball** [comment]
@knz, don't we have a clojure-friendly restart example: https://www.cockroachlabs.com/docs/build-a-clojure-app-with-cockroachdb.html#transaction-with-retry-logic
