### ISSUE TITLE
cli: implement redaction for all non-log debug.zip sources

### ISSUE THREAD

**Issue by dhartunian** [cockroachdb/cockroach#79141]
currently, redaction is applied to log outputs in debug.zip but not other info like internal or system tables. we should implement some form of coarse or fine-grained redaction on these data sources to prevent data exposure in debug.zip when redaction is requested.

Jira issue: CRDB-14599

Epic CRDB-12732

**Comment by abarganier** [comment]
I'm going to close this issue in favor of more a granular breakdown of the work involved here. Below you can see the replacement issues:

- https://github.com/cockroachdb/cockroach/issues/86305
- https://github.com/cockroachdb/cockroach/issues/86309
- https://github.com/cockroachdb/cockroach/issues/86313
- https://github.com/cockroachdb/cockroach/issues/86315
- https://github.com/cockroachdb/cockroach/issues/86316

Related in-flight PRs:
- https://github.com/cockroachdb/cockroach/pull/86180
- https://github.com/cockroachdb/cockroach/pull/86475
- https://github.com/cockroachdb/cockroach/pull/67065
