### ISSUE TITLE
sql: interval formats should support both positive and negative units

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#7916]
We support 3 [`INTERVAL`](https://cockroachlabs.com/docs/interval.html) formats: Golang, Postgres, ISO.

Currently, you can specify a negative interval only when using the Golang format:

```
INSERT INTO intervals VALUES (1, '-1h30m') RETURNING *;
+---+----------+
| a |    b     |
+---+----------+
| 1 | -1h30m0s |
+---+----------+
(1 row)
```

Based on the Postgres docs, the Postgres format should support this as well (quote below). For full compatibility, it might be necessary to support not only one sign for the entire interval, but differing signs for each unit of the interval. 

From the [postgres docs](https://www.postgresql.org/docs/9.1/static/datatype-datetime.html#DATATYPE-INTERVAL-INPUT-EXAMPLES):

> According to the SQL standard all fields of an interval value must have the same sign, so a leading negative sign applies to all fields; for example the negative sign in the interval literal '-1 2:03:04' applies to both the days and hour/minute/second parts. PostgreSQL allows the fields to have different signs, and traditionally treats each field in the textual representation as independently signed, so that the hour/minute/second part is considered positive in this example. If IntervalStyle is set to sql_standard then a leading sign is considered to apply to all fields (but only if no additional signs appear). Otherwise the traditional PostgreSQL interpretation is used. To avoid ambiguity, it's recommended to attach an explicit sign to each field if any field is negative.

**Comment by richardartoul** [comment]
Could I try and tackle this? Seems like the changes would be confined to sql/parser/interval.go if I'm not mistaken.

**Comment by a-robinson** [comment]
Yeah, that'd be great, @richardartoul!

cc @knz

**Comment by knz** [comment]
We already support this now - since #14534
