### ISSUE TITLE
sql: use `AddSSTable` for column backfills

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#79213]
Column backfills currently use point write batches instead of `AddSSTable`. Longer-term this will be addressed by the [declarative schema changer](https://github.com/cockroachdb/cockroach/pull/76944). In the meanwhile, we could consider migrating this to using `AddSSTable` instead of write batches, which will likely be faster and can be backported.

https://github.com/cockroachdb/cockroach/blob/5a97a11337dbd3874bea2342a727d8b4500ac224/pkg/sql/backfill/backfill.go#L385

Jira issue: CRDB-14640

**Comment by dt** [comment]
>  and can be backported.

I believe the reason this is waiting on the new schema changer, which would build a new index and then swap it out, is that it we could not use AddSSTable to safely write to a span that SQL traffic was reading and writing to expecting transactional semantics at the same time. Has that changed with the new flags we added in 22.1?

**Comment by erikgrinaker** [comment]
Yes, when checking for conflicts and writing at the current timestamp, these are fully MVCC-compliant. This requires a scan though, so the SST span should be tight (which I think it would be since we're presumably updating these in primary key order), but it should be an improvement since the point writes also need to do point reads first for this purpose.

But note that changefeeds currently don't handle `AddSSTable` events and will restart with a catchup scan, so we may have to address that first.

**Comment by dt** [comment]
I'm still not quite piecing together how it works. These writes currently have to be transactional: we begin, we read some rows at ts=X, then we write -- at ts=X, then commit. If the write gets pushed, don't we stage it at the new time and then  refresh the read spans? And if we see a change in them, don't we restart, aborting our write intents?

**Comment by erikgrinaker** [comment]
Oh, I'm sorry -- missed that the writes themselves had to be transactional. Yeah, `AddSSTable` can't be in a transaction. We'll wait for the declarative schema changer to fix this then.
