### ISSUE TITLE
storage/engine: Don't embed `rocksDBIterator` in `rocksDBBatchIterator`

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#7922]
By embedding `rocksDBIterator` in `rocksDBBatchIterator`, we inherit the embedded type's implementation of all iterator methods. This allows bugs to pass silently, like the missing `flushMutations`  in `ComputeStats` (#7903). Instead, we should make this a named field so that we have to implement all methods explicitly and decide whether `flushMutations` is needed.

**Comment by petermattis** [comment]
Yeah, in hindsight that was a mistake. I'll fix.
