### ISSUE TITLE
show more prominent statements that are holding a lock for > 5 min

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#79230]
A common reason for escalations are due to locks on tables, but currently it's not easily visible which queries/transactions are those.
It would be useful if we can show more prominent in the SQL Activity page if there is anything the user should take immediate action on.
A query that can be used to identify those querys is
```
  SELECT *
    FROM (
            SELECT num_retries, now() - start AS age, session_id, query
              FROM crdb_internal.cluster_queries AS cq
              JOIN [SHOW transactions] AS t ON cq.txn_id = t.txn_id
         )
   WHERE age > '5m' AND num_retries > 0
ORDER BY age DESC
   LIMIT 10;
```

cc @kevin-v-ngo @Annebirzin 

Jira issue: CRDB-14653

Epic: [CRDB-14468](https://cockroachlabs.atlassian.net/browse/CRDB-14468)

**Comment by kevin-v-ngo** [comment]
We may be able to close this issue. We have active executions in 22.2 now which surfaces this information. 

However, we may be able to do better. We should discuss at some point a way to surface high "Time Spent Waiting" values more prominently. FYI @dongniwang

**Comment by dongniwang** [comment]
> However, we may be able to do better. We should discuss at some point a way to surface high "Time Spent Waiting" values more prominently. FYI @dongniwang

how does high wait times differ from time spent waiting?

**Comment by kevin-v-ngo** [comment]
> > However, we may be able to do better. We should discuss at some point a way to surface high "Time Spent Waiting" values more prominently. FYI @dongniwang
> 
> how does high wait times differ from time spent waiting?

 "Time Spent Waiting" is what we have in the UI as the column name. In this issue, a high wait time is 5 minutes. It's the same metric just classifying the impact as 'high'.
