### ISSUE TITLE
parser: parse type length in type-prefixed bit-string literals

### ISSUE THREAD

**Issue by michae2** [cockroachdb/cockroach#79253]
There are many different ways to write bitstring literals in PostgreSQL, for example:

```sql
SELECT B'1101';
SELECT CAST('1101' AS VARBIT);
SELECT CAST('1101' AS VARBIT(4));
SELECT CAST('1101' AS BIT(4));
SELECT '1101'::VARBIT;
SELECT '1101'::VARBIT(4);
SELECT '1101'::BIT(4);
SELECT VARBIT '1101';
SELECT VARBIT(4) '1101';
SELECT BIT(4) '1101';
```

We are able to use all of these except the last two:

```
invalid syntax: statement ignored: at or near "(": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
SELECT VARBIT(4) '1101'
             ^
invalid syntax: statement ignored: at or near "(": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
SELECT BIT(4) '1101'
          ^
```

We are able to parse other type-prefixed literals with parameters in the type:

```
demo@127.0.0.1:26257/defaultdb> SELECT DECIMAL(10,5) '9.99';
  numeric
-----------
  9.99000
(1 row)


Time: 1ms total (execution 0ms / network 0ms)
```

So this seems specific to the bit types.

Jira issue: CRDB-14658

Epic CRDB-17785

**Comment by agsti** [comment]
I'm going to take a look at this.
So far I've found this doc explaining how to add an sql statement `docs/codelabs/01-sql-statement.md`, rather outdated, uses old  make build system
I probably will need to add some ast code on `pkg/sql/parser/sql.y` and some test under `pkg/sql/parser/testdata/select_exprs` 

Please correct me if im wrong

**Comment by agsti** [comment]
Just noticed there's another PR open about this :( 

They seem rather different, so yeah, I tried

**Comment by rafiss** [comment]
@agsti Thanks for your PR! The tests you added are helpful, so I will incorporate that into the earlier PR, and merge it.
