### ISSUE TITLE
acceptance: TestFreezeCluster is skipped, possibly due to gossip issues

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#7928]
Happened on two separate (unrelated) branches on CircleCI, as well as locally. If you rebuild enough times it eventually goes away. Here is an example:
- https://circleci.com/gh/arjunravinarayan/cockroach/79
- https://circleci.com/gh/arjunravinarayan/cockroach/80
- (Fixed on rebuild): https://circleci.com/gh/arjunravinarayan/cockroach/82

From the log it looks like the http endpoint is not coming up in time.

```
I160719 17:11:15.170388 acceptance/freeze_test.go:46  requesting: freeze=false, timeout=10s
I160719 17:11:15.172666 acceptance/freeze_test.go:46  requesting: freeze=false, timeout=10s
```

...

```
I160719 17:11:24.342235 acceptance/freeze_test.go:46  requesting: freeze=false, timeout=10s
I160719 17:11:25.344527 acceptance/freeze_test.go:46  requesting: freeze=false, timeout=10s
```

If you look at the `stderr` [log](https://80-59059502-gh.circle-artifacts.com/0//tmp/circle-artifacts.pThZDsX/acceptance/TestFreezeCluster/roach2/stderr.2016-07-19T17_11_36Z.log), you see that gossip isn't connecting for 15 seconds:

```
W160719 17:11:15.255515 kv/dist_sender.go:656  the descriptor for the first range is not available via gossip
W160719 17:11:15.258886 kv/dist_sender.go:656  the descriptor for the first range is not available via gossip
```

...

```
I160719 17:11:32.236670 storage/queue.go:290  [verify] no system config available. skipping
I160719 17:11:32.236693 storage/queue.go:290  [replicate] no system config available. skipping
I160719 17:11:32.236715 storage/queue.go:290  [replicaGC] no system config available. skipping
I160719 17:11:32.236754 storage/queue.go:290  [raftlog] no system config available. skipping
```

That's 15 seconds.

**Comment by tamird** [comment]
From #8235 via @RaduBerinde:
> Duplicates:
#8184 `freeze_test.go:148: unknown field "httpStatus" in serverpb.ClusterFreezeResponse`
#8201 `freeze_test.go:148: Post https://127.0.0.1:32827/_admin/v1/cluster/freeze: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

**Comment by tamird** [comment]
Haven't seen this flake recently. Closing for now.

**Comment by benesch** [comment]
Apologies if I'm crazy, but isn't this test skipped? https://github.com/cockroachdb/cockroach/blob/master/pkg/acceptance/freeze_test.go#L41

**Comment by tamird** [comment]
Derp.
