### ISSUE TITLE
config: Add Meta2KeyMax to ComputeSplitKeys

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#7931]
(Extracted from #7652)

We should add `Meta2KeyMax` (and maybe `Meta1KeyMax`) to `config.ComputeSplitKeys` so that 

Splitting the first range is a special case: it doesn't touch any other ranges so all intents can be resolved synchronously in `EndTransaction`. Since it's more typical for splits to be distributed transactions (and RangeLookup has special handling for the meta intents that can be left in this case), we should eagerly split the meta range from the rest of the keyspace to ensure that our tests are running in a more production-like environment. However, many tests hard-code range ID 1, so they will need to be fixed first (or these automatic splits disabled for those tests)

As a practical matter, this should also improve availability by keeping the meta ranges smaller (unless we deliberately split at Meta2KeyMax, the first range will also include a lot of timeseries data)

**Comment by petermattis** [comment]
@a-robinson This is already done, right?

**Comment by a-robinson** [comment]
We still don't split at `Meta1KeyMax`, but do split at `Meta2KeyMax` as of https://github.com/cockroachdb/cockroach/pull/14740.
