### ISSUE TITLE
sql: virtual columns on primary indexes should be blocked until cluster version is 22.1

### ISSUE THREAD

**Issue by fqazi** [cockroachdb/cockroach#79329]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

Running within a mixed version environment with 22.1 and 21.2 you can get into a problematic scenario by creating a table that depends on a virtual column being inside the primary index. Once this happens all sorts of things start breaking on 21.2 nodes as validation of the problematic descriptor starts failing.

**To Reproduce**

What did you do? Describe in your own words.

Setup a mixed version environment with 21.2 and 22.1, and on the 22.1 create a table with a virtual column inside the primary index:

1) `CREATE TABLE table475 (col475_476 TIME NULL, col475_477 INET NOT NULL, col475_478 TIMESTAMPTZ NULL, col475_479 CHAR NOT NULL, col475_480 DECIMAL NOT NULL, col475_481 DECIMAL[], col475_482 BYTES NOT NULL, col475_483 REGPROCEDURE NOT NULL, col475_484 JSONB NULL, col475_485 STRING NULL AS (lower(CAST(col475_477 AS STRING))) STORED, col475_486 STRING NOT NULL AS (lower(col475_479)) VIRTUAL, col475_487 STRING NOT NULL AS (lower(CAST(col475_476 AS STRING))) STORED, col475_488 STRING NOT NULL AS (lower(CAST(col475_476 AS STRING))) VIRTUAL, col475_489 DECIMAL NOT NULL AS (col475_480 + 1.773127403248833576E+32:::DECIMAL) STORED, col475_490 STRING NULL AS (lower(CAST(col475_476 AS STRING))) STORED, col475_491 DECIMAL NOT NULL AS (col475_480 + (-4694941766.282658396):::DECIMAL) VIRTUAL, PRIMARY KEY (col475_477 DESC, col475_482 DESC, col475_486, col475_489 ASC, col475_487, col475_483 DESC, col475_488), INVERTED INDEX (col475_488 DESC, col475_478 ASC, col475_490 ASC, col475_482 ASC, col475_483 ASC, col475_489 DESC, (CASE WHEN col475_482 IS NULL THEN '':::STRING ELSE '~zS':::STRING END) ASC, col475_479 ASC, col475_480 ASC, col475_481 DESC), INDEX (col475_487 DESC, col475_489 DESC, col475_479 DESC, col475_490 ASC, (CASE WHEN col475_482 IS NULL THEN e'n\\x18B\u003c\\x1f#k/h':::STRING ELSE e'G7xH\\t^\u0026Q':::STRING END), col475_476, col475_488 ASC, lower(CAST(col475_476 AS STRING)) ASC, col475_478 ASC, col475_491, col475_477 DESC, col475_482, lower(col475_479) DESC, lower(CAST(col475_484 AS STRING)) ASC, col475_486, col475_483) STORING (col475_480), FAMILY (col475_487, col475_478, col475_477), FAMILY (col475_484, col475_481), FAMILY (col475_490, col475_489), FAMILY (col475_480), FAMILY (col475_479), FAMILY (col475_482, col475_476), FAMILY (col475_483), FAMILY (col475_485));`
2) Attempt to access this table from a 21.2 node and watch things fail. Or run certain crdb_internal queries.

**Expected behavior**
We should be blocking the creation of this problematic table using a version gate and return the old error in this scenario.

Jira issue: CRDB-14707

**Comment by rail** [comment]
Manually synced with Jira
