### ISSUE TITLE
storage: intentResolver shouldn't talk directly to Replica

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#7933]
(Extracted from #7652)

intentResolver talks to Replica directly for two things: GCing transaction records (which can easily be change to use DistSender) and for resolving intents in a halfway-synchronous way. The first we should definitely fix, and I'm inclined to get rid of the second too, even though it may improve latency a bit under contention. We should generally avoid calling `Replica.addWriteCmd` directly for a number of reasons.

**Comment by bdarnell** [comment]
> We should generally avoid calling Replica.addWriteCmd directly for a number of reasons.

The biggest of those reasons is concurrency: the `Replica` may have been removed from the `Store` before the asynchronous intent resolution tries to access it. Bypassing the DistSender also exposes us to lower-level errors, such as RangeKeyMismatchError (in the event of a concurrent split, as seen in #7652 ), which the DistSender can handle automatically. Finally, it's just a good idea to minimize the number of variant paths through this code.

**Comment by tamird** [comment]
@bdarnell per https://github.com/cockroachdb/cockroach/issues/7978 should `TestPartitionBank`  be re-enabled now?

**Comment by andreimatei** [comment]
That `TestPartitionBank` is still flaky. I suspect @tschottdorf was grasping at straws when he suggested the timeout is related to intent resolution.
Anyway, I'm looking at it.

**Comment by tschottdorf** [comment]
>  I suspect @tschottdorf was grasping at straws when he suggested the timeout is related to intent resolution.

You don't need to suspect, I told you that.
