### ISSUE TITLE
roachtest: sqllitelogic test no longer files GitHub issues upon failure

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#79403]
The Bazel sqllitelogic test has been failing since at least 21 Feb, before which no history is recorded: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_SQLiteLogicTestsBazel?branch=%3Cdefault%3E&buildTypeTab=overview&mode=builds

However, no issues were filed for the failures. We rely on these issues to detect the failures, so it's very important that they get filed.

This was last fixed here: #47566

Here is an example of a correctly filed SQLiteLogicTest issue: #77929

Jira issue: CRDB-14807

**Comment by jordanlewis** [comment]
I wonder if the switch to Bazel might have caused this regression, but I have no idea. For reference, here is the pre-bazel test history, which wasn't failing: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_SqlLogicTests?branch=%3Cdefault%3E&buildTypeTab=overview&mode=builds

**Comment by cucaroach** [comment]
Unless I'm missing something we're stilling failing sqllite logic tests and not generating github issues.

**Comment by rickystewart** [comment]
Looking at https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_SQLiteLogicTestsBazel/4935103?buildTab=log&focusLine=7027&linesState=4751.4756:

    build/teamcity-bazel-support.sh: line 39: TC_BUILD_BRANCH: unbound variable

I know what's causing this, give me a bit to get a PR together.
