### ISSUE TITLE
sql: extend parallel_test to use multiple nodes

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#7942]
The parallel test can issue queries in parallel from multiple clients, but it currently sets up a single node. We should extend it to be able to create a test cluster with multiple nodes, and have each node run a set of txns.

Ideally the test should reproduce #7899.

**Comment by knz** [comment]
to get the most probability to reproduce the bug use 4839efeea54c1c60bd4b5ff2b8c5b7f91707a0c6
Commits after that tend not to repro

**Comment by RaduBerinde** [comment]
All the testcluster stuff came after `4839efe`, I've been trying to cherry-pick the commits I need but it's too difficult. Is there anything I can tweak to make it easier to repro on a recent master?

**Comment by knz** [comment]
2ed649991650c4e634055700a9598a058acd0e89 should get you repros too
