### ISSUE TITLE
cloud/amazon: perpetual backup error "failed to get s3 object: MissingRegion: could not find region configuration"

### ISSUE THREAD

**Issue by nick-jones** [cockroachdb/cockroach#79435]
**Describe the problem**

We have multiple clusters deployed with pretty much identical configuration. They all write backups to the same S3 bucket, just specifying different paths. Recently one of our clusters decided to start failing to backup with an error indicating the AWS region is unknown, having been backing up successfully for a long time before that. The error was persistent, and impacted both scheduled backups as well as ad-hoc. No changes had been made to configuration or AWS side settings that we're aware of, and all other clusters were able to backup to the same target bucket without issue. 

```
  738486411826331650 | cluster_backup | ACTIVE          | 2022-04-06 00:00:00+00 | reschedule: failed to create job for schedule 738486411826331650: err=executing schedule 738486411826331650: failed to get s3 object: MissingRegion: could not find region configuration | 0 0,12 * * * |           0 | root  | 2022-02-21 10:16:07.404469+00 | {"backup_statement": "BACKUP INTO 's3://***/?AUTH=implicit' WITH detached"}
```

One thing that struck me about this is the error message is coming from the AWS SDK, https://github.com/aws/aws-sdk-go/blob/eaca685b6d6f0322239a07223da853ac23b5e704/aws/errors.go#L6-L8, yet the code that intialises the client looks to ensure a region is set, returning an error if one cannot resolved: https://github.com/cockroachdb/cockroach/blob/3d6f41bb04b84ac3d263e815053e4562406412ab/pkg/cloud/amazon/s3_storage.go#L343-L352

Unless I'm mistaken, it seems there is an issue in that the function supplied to `DelayedRetry` always returns `nil` (line 347). This means that if `GetBucketRegion` returns an error, `nil` ends up being returned regardless, and `region` remains an empty string.

A further compounding factor is that the client instance returned appears to be cached and re-used, so just one failure to lookup region _may_ result in an empty region being held and repeated failure until node restart. What we observed is: cluster backups were failing on every single time. After restarting one of the nodes, they started to succeed again. As it happens, the backup failures fell within the timeframe that that node had been up, ~36 hours. The remaining two nodes had been restarted within the last couple of hours, and backups had continued to fail after that point.

So we believe that the region lookup failed on one node (which is fine, it _can_ happen), but this ended up meaning that all subsequent attempts to backup failed, even though they more than likely should have been succeeding by that stage.

Note that we believe we can set the `AWS_REGION` environment variable to avoid the region lookup entirely, which we may well do.

**To Reproduce**

This is somewhat difficult as you have to force the region lookup to fail.

**Expected behavior**

If all attempts at region lookup are exhausted, backup should fail with the error from region lookup failure being returned. If backup fails because of region lookup failing, it shouldn't fail perpetually, i.e. region lookup should be attempted again the next time backup is invoked.

**Additional data / screenshots**

```
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25  error processing schedule 738486411826331650: executing schedule 738486411826331650: failed to get s3 object: ‹MissingRegion: could not find region configuration›
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +(1) attached stack trace
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  -- stack trace:
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*jobScheduler).processSchedule
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  |    /go/src/github.com/cockroachdb/cockroach/pkg/jobs/job_scheduler.go:184
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*jobScheduler).executeSchedules.func2
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  |    /go/src/github.com/cockroachdb/cockroach/pkg/jobs/job_scheduler.go:302
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  | github.com/cockroachdb/cockroach/pkg/jobs.withSavePoint
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  |    /go/src/github.com/cockroachdb/cockroach/pkg/jobs/job_scheduler.go:242
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*jobScheduler).executeSchedules
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  |    /go/src/github.com/cockroachdb/cockroach/pkg/jobs/job_scheduler.go:301
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*jobScheduler).runDaemon.func1.1
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  |    /go/src/github.com/cockroachdb/cockroach/pkg/jobs/job_scheduler.go:368
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn.func1
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  |    /go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:773
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).exec
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  |    /go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:854
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  |    /go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:772
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*jobScheduler).runDaemon.func1
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  |    /go/src/github.com/cockroachdb/cockroach/pkg/jobs/job_scheduler.go:367
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  | [...repeated from below...]
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +Wraps: (2) executing schedule 738486411826331650
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +Wraps: (3) attached stack trace
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  -- stack trace:
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  | github.com/cockroachdb/cockroach/pkg/storage/cloudimpl.(*s3Storage).openStreamAt
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  |    /go/src/github.com/cockroachdb/cockroach/pkg/storage/cloudimpl/s3_storage.go:381
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  | github.com/cockroachdb/cockroach/pkg/storage/cloudimpl.(*s3Storage).ReadFileAt
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  |    /go/src/github.com/cockroachdb/cockroach/pkg/storage/cloudimpl/s3_storage.go:396
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  | github.com/cockroachdb/cockroach/pkg/storage/cloudimpl.(*s3Storage).ReadFile
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  |    /go/src/github.com/cockroachdb/cockroach/pkg/storage/cloudimpl/s3_storage.go:388
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  | github.com/cockroachdb/cockroach/pkg/ccl/backupccl.containsManifest
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  |    /go/src/github.com/cockroachdb/cockroach/pkg/ccl/backupccl/manifest_handling.go:148
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  | github.com/cockroachdb/cockroach/pkg/ccl/backupccl.resolveDest
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  |    /go/src/github.com/cockroachdb/cockroach/pkg/ccl/backupccl/backup_destination.go:119
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  | github.com/cockroachdb/cockroach/pkg/ccl/backupccl.backupPlanHook.func3
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  |    /go/src/github.com/cockroachdb/cockroach/pkg/ccl/backupccl/backup_planning.go:705
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  | github.com/cockroachdb/cockroach/pkg/ccl/backupccl.invokeBackup.func2
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  |    /go/src/github.com/cockroachdb/cockroach/pkg/ccl/backupccl/schedule_exec.go:125
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  | github.com/cockroachdb/cockroach/pkg/util/ctxgroup.Group.GoCtx.func1
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  |    /go/src/github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:166
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  | golang.org/x/sync/errgroup.(*Group).Go.func1
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  |    /go/src/github.com/cockroachdb/cockroach/vendor/golang.org/x/sync/errgroup/errgroup.go:57
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  | runtime.goexit
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +  |    /usr/local/go/src/runtime/asm_amd64.s:1374
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +Wraps: (4) failed to get s3 object
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +Wraps: (5) ‹MissingRegion: could not find region configuration›
E220405 12:00:14.999702 959 jobs/job_scheduler.go:310 ⋮ [n1] 25 +Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *awserr.baseError
```

**Environment:**
 - CockroachDB version: v21.1.12
 - Server OS: Linux
 - Client app: N/A

**Additional context**

Jira issue: CRDB-14856

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-14856](https://cockroachlabs.atlassian.net/browse/CRDB-14856) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-79435`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by mwang1026** [comment]
sync done
