### ISSUE TITLE
outliers: configurable statistical detection per fingerprint

### ISSUE THREAD

**Issue by matthewtodd** [cockroachdb/cockroach#79451]
Here we expand on the walking skeleton by developing a smarter detection algorithm for outliers, perhaps leaning on existing sql stats infrastructure.

Epic: [CRDB-13544](https://cockroachlabs.atlassian.net/browse/CRDB-13544)

Jira issue: CRDB-14871

**Comment by kenliu-crl** [comment]
https://cockroachlabs.atlassian.net/browse/CRDB-13544

**Comment by kenliu-crl** [comment]
manually reviewed and brought up to date
