### ISSUE TITLE
schemachanger: implement DROP INDEX statements

### ISSUE THREAD

**Issue by postamar** [cockroachdb/cockroach#79499]
Currently the declarative schema changer implements all DROP statements except DROP INDEX. This ticket tracks adding full support for [DROP INDEX](https://www.cockroachlabs.com/docs/stable/drop-index.html) and handling them by the declarative schema changer by default.

We already have partial, unsafe support for CREATE INDEX. This is because it only works some of the time, for a large part because we don't yet have ADD COLUMN support either and CREATE INDEX can add columns in some cases. I don't think DROP INDEX has any blockers preventing us from fully supporting it right now, though.

Note: take care in handling constraints correctly, CRDB is a bit peculiar about how it handles UNIQUE compared to Postgres. The logic tests should help you there.

Jira issue: CRDB-14893

**Comment by rail** [comment]
Manually synced with Jira
