### ISSUE TITLE
Global vs. per-Instance feeds for stores

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#795]
We are currently in the process of adding an event feed to the `storage.Store` structure that higher level structures can use to observe interesting events within the store. The current plan is to give each Store its own feed structure, but I am investigating whether it might be better to have a single global structure in the Store package.

Comparing the two options:
+ Giving every store a feed, treating events as the output of a specific store. This option results in no global state, and there would be no lock contention between stores when publishing events. This also allows a more fine grained selection of interesting events for each listener. On the downside, a subscriber that is interested in multiple stores would have to maintain a subscription for each store; since Store is a low level structure which is often created deep within other structures, it takes a bit of abstraction to give higher-level structures the option to subscribe to individual stores.
+ Have a single global feed in the Store package, treating store events as a form of structured log message. This option allows subscribers to easily subscribe to all events from all stores, without needing access to the individual store objects at any point. 
On the downside, since every Store is publishing to the same feed, this might create some lock contention in the case of high store counts. This option also creates global state which might need special handling in a test context. Finally, we would also need to place the Store ID on every store event, although this is a very small amount of overhead.

I currently think that the Global option is best despite the need for locking; there is already a global lock held for every incoming command on a node in order to look up the store, and each command should result in at most one store event being published. These events are very similar to log messages, and this treats them as such; the benefits to code clarity are significant.

**Comment by spencerkimball** [comment]
After our discussion Saturday, I agree that a global option makes sense for store events. It all comes down to what the subscribers would prefer and I think a combined feed is a lot more convenient for the tasks we have in mind:

- Keeping a system table of interesting events
- Keeping accounting-prefix stats
- What else do we have in mind right now?

**Comment by BramGruneir** [comment]
Hmm... What about something in between.  How about a node level feed one can subscribe to?  Store level might be too fine grained, but node level should be perfectly fine.

**Comment by spencerkimball** [comment]
Right. Node level is what I have in mind.

**Comment by BramGruneir** [comment]
Ah perfect then.  I can see signing up or getting a dump for a specific store or range's feed from a node.

**Comment by mrtracy** [comment]
Node level was the best solution for this. I had mentally eliminated that option early on, and I don't remember why; it turned out to be very clear.
