### ISSUE TITLE
beta-20160721

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#7950]
Starting the beta rollout for commit 040e3b9d25ba73ab2856d7133b53493d25b66ef7

Beta - was failing due to out of disk space errors in the logs directory

Will update with details from other clusters later.

**Comment by BramGruneir** [comment]
Updating Beta
After deploying the latest version, a few errors were encountered:
- A number of nodes' supervisors were broken.  To fix them, the supervisor service had to be killed and restarted.
- One node refused to start as its ntp service was down.  The clock had drifted by more than 3 seconds from all the other servers.  After restarting the ntp service (and forcing an update) cockroach started.
- after a few hours, one node excited (without any log message as to why) but I restarted it we now have 6 green replicas.

**Comment by BramGruneir** [comment]
Updating Gamma
Gamma stop, updated and started without incident

**Comment by BramGruneir** [comment]
Updating Rho
Sadly, Rho is DOA.

**Comment by jseldess** [comment]
@BramGruneir, isn't this done?

**Comment by BramGruneir** [comment]
It is.  Closing.
