### ISSUE TITLE
debug: add LSM health explicitly to the debug zip

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#79518]
Pebble exposes a view of the LSM, which we expose in the Cockroach console via the `/debug/lsm` endpoint.

When debugging storage-related issues, we often want to know the state of the LSM at the time when the debug.zip was taken. To do this, we typically dig through logs, looking for the last instance of the LSM printout, which could be up to 10 minutes in the past.

To quicken the process of diagnosing issues related to storage health, we should consider adding the LSM health to the debug zip as its own dedicated file, for each node. For instance, under `nodes/$N/lsm.txt`, we can dump the same output from the `/debug/lsm` endpoint.

For historical LSM metrics, the logs can still be used, in addition to the metrics captured in the tsdump (l0 size, l0 file count, etc.).

Jira issue: CRDB-14895

**Comment by rail** [comment]
Manually synced with Jira

**Comment by nicktrav** [comment]
This is under consideration for 23.2. Removing https://github.com/cockroachdb/cockroach/labels/O-postmortem.

**Comment by nicktrav** [comment]
One possible impl:
- we have engine stats, which is in the debug.zip, which is a holdover from RocksDB
- engine stats currently returns nothing, and we were considering removing it
- rather than removing the endpoint, repurpose it so as to include the LSM stats
