### ISSUE TITLE
webui: additional "LSM health" metrics on the Storage dashboard

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#79531]
On the Storage dashboard `/#/metrics/storage/cluster`, we already surface a bunch of metrics that aid in diagnosing issues at the storage layer.

One blind spot is L0 file count / size. Concretely, we had an incident where an LSM had a large amount of data in L0, in a single sublevel, that wasn't being compacted out. The read-amp metrics for the LSM wouldn't have raised any questions, though if we had a metric for size / count of L0 (or even other levels in the LSM), we might have been able to narrow in on the issue faster.

Consider adding another chart to the Storage page that shows size / file count per-level.

Jira issue: CRDB-15947

**Comment by nicktrav** [comment]
Tagging as `T-storage`, as I _think_ we have all the metrics and UI infrastructure in place, such that we should be able to self-serve, unless this could be graciously picked up by someone else.

**Comment by nicktrav** [comment]
This feeds into #79101.

**Comment by nicktrav** [comment]
This is under consideration for 23.2. Removing https://github.com/cockroachdb/cockroach/labels/O-postmortem.

**Comment by itsbilal** [comment]
For the purposes of this issue, we can scope this just to adding the following two charts to the Storage dashboard:

1) A new chart with the count of L0 sstables in each of the nodes (ideally, each of the stores if we can have it broken by stores and not nodes)
2) A new chart with the size of L0 sstables in each of the nodes (same preference for making it per store if possible)

cc @anish-shanbhag

**Comment by anish-shanbhag** [comment]
@itsbilal You mentioned that L0 sublevel count is a pretty useful metric - would it make sense to add a 3rd chart showing L0 sublevels in addition to the L0 count/size charts?

**Comment by itsbilal** [comment]
@anish-shanbhag The sublevel count is already indirectly exposed as read-amp (as it's usually the biggest component of said read-amp). So adding another chart is probably not necessary for that.
