### ISSUE TITLE
sql: provide a mechanism for determining the hybrid-logical timestamp of a committed transaction

### ISSUE THREAD

**Issue by stevekuznetsov** [cockroachdb/cockroach#79591]
When a client is using the hybrid-logical timestamps (`crdb_internal_mvcc_timestamp`) to directly control optimistic concurrency, it is necessary to determine the timestamp that data is committed at. Consider the following client flow:

 - insert a row, caching the inserted value and the timestamp at which it was committed
 - determine that the row should be updated or deleted based on the cached data
 - attempt to update or delete the row contingent on the timestamp not having changed

Today, there is no simple `INSERT ... RETURNING crdb_internal_mvcc_timestamp`, and using `SELECT ... , crdb_internal_mvcc_timestamp` during a transaction yields the provisional timestamp, which is not safe to use. [https://github.com/cockroachdb/cockroach/issues/58046] Using `cluster_logical_timestamp()` in the transaction that issues the `INSERT` is valid, but constrains the system and likely results in lower performance.

Some other mechanism for figuring out the timestamp to make this simple for a client would be superb.

/cc @ajwerner 

Jira issue: CRDB-14933

**Comment by ajwerner** [comment]
relates to https://github.com/cockroachdb/cockroach/issues/7945

**Comment by nvanbenschoten** [comment]
> When a client is using the hybrid-logical timestamps (crdb_internal_mvcc_timestamp) to directly control optimistic concurrency, it is necessary to determine the timestamp that data is committed at.

Could you say more about what you'd like to use the hybrid-logical timestamps for? What does directly control optimistic concurrency mean? Why do you want to directly control it? Are they steps you listed out within a single transaction, or across transactions?

**Comment by stevekuznetsov** [comment]
@nvanbenschoten I am attempting to put CRDB behind a system where end-users ("clients") are aware of the logical timestamp at which the objects they know about were committed. Generally, a client will determine that they need to update or delete a row by doing some logic on the contents of the row, against the data they have in their cache. Clients interact with an API that is not the raw SQL connection to CRDB so their logic for deciding that some action must be taken cannot be rewritten in terms of `WHERE ...` clauses.

Right now, the flow I outlined above consists of two transactions. First, insert some new row and read `cluster_logical_timestamp()` in a transaction. Store the data that was written and the timestamp in a cache. At some later point, check to see if the row needs to be changed against the cache. Then, in a transaction, delete/update the row and assert that the `crdb_internal_mvcc_timestamp` for the row has not changed from the cached value, to ensure that the decision to delete/update it was done against up-to-date values.

**Comment by knz** [comment]
What in the use case would _not_ be satisfied by causality tokens as first described in #7945?
