### ISSUE TITLE
spanconfig/rangefeed: investigate microbenchmark regression

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#79602]
**Describe the problem**

One of our microbenchmarks show additional memory usage and was bisected to #74555. See https://github.com/cockroachdb/cockroach/pull/74555#issuecomment-1088069495.

**To Reproduce**

I ran the following and used `go tool pprof -http localhost:8082 -diff_base=mem-old.out -normalize mem-new.out` to see where the differences are coming from.
```
dev bench pkg/bench -f='BenchmarkSQL/MultinodeCockroach/InsertSecondaryIndex/count=1000' --count=10 --bench-mem --timeout=24h -v --test-args '-test.memprofile=mem.out'
```

<img width="1598" alt="image" src="https://user-images.githubusercontent.com/10536690/162268288-2af210ae-3856-4bdd-801c-431dbaaeb3ae.png">

Looks like it's additional rangefeed event processing. I'm not sure off-hand why; I suspect it's got something to do with ranges having to enable rangefeeds by default when no targeted config is available.

**Expected resolution**

Pin down exactly why we're doing more processing, and whether it's expected. 

Jira issue: CRDB-14939

**Comment by nvanbenschoten** [comment]
We return `true` from `Replica.isRangefeedEnabled` when `!r.mu.spanConfigExplicitlySet`:
https://github.com/cockroachdb/cockroach/blob/81d3dc1228c3304d0abf06c157f9fbb8bb954b2c/pkg/kv/kvserver/replica.go#L1043-L1045

Is this unintentionally enabling rangefeed and MVCCLogicalOp publication on most ranges?

**Comment by irfansharif** [comment]
Discussed [internally](https://cockroachlabs.slack.com/archives/C0KB9Q03D/p1663782663014619): `spanConfigExplicitlySet` is not whether a span config exists for the range or not, it’s whether the current replica’s span config has been applied from a rangefeed on the spanconfig table. So we're not enabling rangefeed + MVCCLogicalOp publication on most ranges. That said, this logic does have weird artifacts in test code that use scratch ranges for ex. where unless the `ConfigureScratchRange` testing knob is set to true, we don’t use span configs in that portion of the keyspan. So automatically have rangefeed enabled.
