### ISSUE TITLE
SQL Activity page filters get cut off when table is short

### ISSUE THREAD

**Issue by Annebirzin** [cockroachdb/cockroach#79621]
On the SQL Activity pages, the filter gets cut off if there are only a few table rows:

![Screen Shot 2022-03-30 at 12 37 40 PM](https://user-images.githubusercontent.com/51920721/162326660-239d8412-4e58-4285-8686-c0f048e07898.png)
 

Jira issue: CRDB-14949

**Comment by maryliag** [comment]
Issue also happens with the column selector on the same case
