### ISSUE TITLE
sql: session registry allowed for multiple active queries

### ISSUE THREAD

**Issue by Azhng** [cockroachdb/cockroach#79626]
Status Server [API](https://github.com/cockroachdb/cockroach/blob/3d6ebc5b35db6ad7c9e036318899b3ae159b4a8f/pkg/server/serverpb/status.proto#L916) for `ListSession` suggests that a session can have more than one active queries. 

According to @itsbilal , this stems from back in the days where we allowed for parallel query execution. This has since been removed. We should clean up the API payload. 

Jira issue: CRDB-14950

**Comment by rafiss** [comment]
Well, technically the one session can have multiple queries associated to it, since the user-initiated query might create a new query delegated to the internal executor. So it depends on what you mean by "associated."

**Comment by Azhng** [comment]
What I meant by "associated" here is the currently ___active___ query in the Session (therefore the connExecutor). I think in the case where user-initiated query is delegated to the internal executor, the `connExecutor` backing the internal executor should be the one responsible to track it in the `SessionRegistry`.

**Comment by lapaz17** [comment]
Could you assign me sir?

**Comment by sajdakabir** [comment]
Is this issue still open? @maryliag

**Comment by kelkarajay** [comment]
@maryliag I've looked into the documents here - https://www.cockroachlabs.com/docs/stable/show-sessions. 

### Q- Going by the comment in the code, should this actually be changed to nil-able attribute?

> 			// Note that the max length of ActiveQueries is 1.
>			// The array is leftover from a time when we allowed multiple
>			// queries to be executed at once in a session.

OR

### Q - Is the field then to be dropped from the API response?

There's some dependencies to this field I found on looking around - 

1. The status of the session (https://github.com/cockroachdb/cockroach/blob/7a063ff5b40b3e2088e1f8d31ba28b2df499d494/pkg/sql/conn_executor.go#L4067). (There's a workaround though)
2.  The queries table (https://github.com/cockroachdb/cockroach/blob/7a063ff5b40b3e2088e1f8d31ba28b2df499d494/pkg/sql/crdb_internal.go#L2412) - I'm not sure how to go about this
3. The sessions table (https://github.com/cockroachdb/cockroach/blob/7a063ff5b40b3e2088e1f8d31ba28b2df499d494/pkg/sql/crdb_internal.go#L2599)

**Comment by maryliag** [comment]
No longer a priority
