### ISSUE TITLE
cli: remove --pretty and --database from cockroach dump

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#7963]
The `--pretty` and `--database` flags don't do anything for `cockroach dump`.  `--pretty` is only useful for `cockroach sql`, I believe, and the database of the table to dump needs to be specified as a command option, so `--database` is irrelevant. 

**Example showing that `--pretty` doesn't make a difference:**

``` shell
# Without --pretty:
$ cockroach dump test dumptest
CREATE TABLE dumptest (
    a INT NOT NULL,
    b DECIMAL(10) NULL,
    CONSTRAINT "primary" PRIMARY KEY (a),
    FAMILY "primary" (a, b)
);

INSERT INTO dumptest VALUES
    (1, 1.1),
    (2, 2.2),
    (3, 3.3);

# With --pretty:
$ cockroach dump test dumptest --pretty
CREATE TABLE dumptest (
    a INT NOT NULL,
    b DECIMAL(10) NULL,
    CONSTRAINT "primary" PRIMARY KEY (a),
    FAMILY "primary" (a, b)
);

INSERT INTO dumptest VALUES
    (1, 1.1),
    (2, 2.2),
    (3, 3.3);
```

**Example showing that `--database` can't be used in place of the database option:**

``` shell
# Without --database but with database option:
$ cockroach dump test dumptest
CREATE TABLE dumptest (
    a INT NOT NULL,
    b DECIMAL(10) NULL,
    CONSTRAINT "primary" PRIMARY KEY (a),
    FAMILY "primary" (a, b)
);

INSERT INTO dumptest VALUES
    (1, 1.1),
    (2, 2.2),
    (3, 3.3);

# With --database but without database option:
$ cockroach dump dumptest --database=test
Usage:
  cockroach dump [options] <database> <table> [flags]
...
Error: missing or invalid parameters
Failed running "dump"
```

**Comment by jseldess** [comment]
In fact, it seems like `--pretty` should be removed from all commands but `cockroach sql`.

**Comment by benesch** [comment]
I punted on fixing the ignored `--database` flag in #12900, since it seems the core issue is not that the database flag is ignored, but that `cockroach dump` has an inconsistent API. Perhaps the naked `cockroach dump` should dump the entire cluster, and then the database could be an optional flag? I.e., `cockroach dump --database DB`.

**Comment by jseldess** [comment]
Thanks, @benesch! 

@mjibson, after https://github.com/cockroachdb/cockroach/pull/12759, does the `--database` flag still have no purpose? If so, we can rename this issue to focus on removing that flag. If not, we can close this issue.

**Comment by mjibson** [comment]
`dump`, since it uses the SQL layer, needs a SQL connection. It uses a setting that causes --database and --pretty to also be included, since those are all bundled in with the SQL connection stuff. But --database and --pretty have never done anything in dump. We need to do something to make it so only the connection stuff (host, port, user, etc) are displayed in dump.

**Comment by benesch** [comment]
@mjibson, `--pretty` for dump is dead as of #12900. :) But I think it might make sense for dump to accept `--database` for consistency with the other commands. The following API is what I have in mind:

    * `cockroach dump` to dump an entire cluster (or, print an error for now)
    * `cockroach dump --database=DB` to dump all tables in a given database
    * `cockroach dump --database=DB [--table=TBL...]` or `cockroach dump [--table=DB.TBL...]`
    * Potentially `cockroach dump DB [--table=TBL...]` as an alternate spelling of the above, where `cockroach dump --database=DB1 DB2` is an error. (This is what `pg_dump` does.)

Thoughts? (I don't know what Cockroach's backwards-compatibility requirements are.)

**Comment by mjibson** [comment]
Oh pg_dump does that? Yes, I'm ok with this proposal.

**Comment by spencerkimball** [comment]
@mjibson who owns this issue? Could you re-assign if necessary. Also, please remove the 1.0 milestone if this isn't getting addressed in the next month.

**Comment by mjibson** [comment]
I can get this done this month.
