### ISSUE TITLE
ui: DB Console does not work on 21.2 (eafda96962)

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#79657]
More discussion in https://github.com/cockroachlabs/support/issues/1528 - I created this to have an issue to label as release-blocker.

The console does not load, and shows a blank screen. There's a 404 when loading assets.

<img width="1392" alt="Screen Shot 2022-04-07 at 9 30 39 PM" src="https://user-images.githubusercontent.com/28270695/162351911-62e020cf-b894-4f0d-a08d-aebe2a5d7c52.png">

I ran a git bisect and found that fcd385c204dd07364c3d01c71a6a8f6a9530f6da is the first commit affected by this problem.

Jira issue: CRDB-14967

**Comment by sjbarag** [comment]
@rafiss fixed in `release-21.2` with commit https://github.com/cockroachdb/cockroach/commit/46d83a409352ea8eb3a58ad6419f38340cd8b544 , which I assume is enough to close this?  I'll let you do the closing to avoid any more issues 😬

**Comment by kenliu-crl** [comment]
manually reviewed and brought up to date
