### ISSUE TITLE
changefeedccl: default kv.rangefeed.separated_intent_scan.enabled to true in v21.2

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/cockroach#79655]
We had seen that changefeed catchup scans can be [disruptive to upgrades](https://cockroachlabs.atlassian.net/wiki/spaces/CKB/pages/2413756457/Changefeeds+are+disruptive+or+cause+increased+foreground+latency+during+or+after+version+upgrade?src=search&NO_SSR=1) (internal), including affecting foreground traffic, due to consuming a lot of IOPS. We have consensus that `kv.rangefeed.separated_intent_scan.enabled` is [safe and beneficial](https://github.com/cockroachdb/cockroach/pull/73473#issuecomment-1092625255). 

> I think we've gained enough confidence in separated intents that it's safe to enable kv.rangefeed.separated_intent_scan.enabled, at least. To put it another way, if we didn't have a cluster setting for it, I wouldn't hesitate to backport a change to only scan separated intents.

Let’s default `kv.rangefeed.separated_intent_scan.enabled` to true in the next patch releases of v21.2. This will reduce likelihood of upgrade problems and support issues.

---

Notes from [this discussion](https://github.com/cockroachdb/cockroach/pull/73473#issuecomment-1092625255):

> > PS: we'd have to make sure these new default settings respect the relevant version gates, if they don't already, to avoid breakage in mixed-version 21.1/21.2 clusters.

> We respect a cluster setting for the intent scanner. I don't _think_ there are any cluster settings we need to worry about for catchup-scans, but if I'm wrong there let me know.

https://github.com/cockroachdb/cockroach/blob/385f7422461f6cc88a2286fb4262e8d82caf64b8/pkg/kv/kvserver/replica_rangefeed.go#L396-L397

Related work:

- https://github.com/cockroachdb/cockroach/issues/79727
- https://github.com/cockroachdb/cockroach/issues/76508
- https://github.com/cockroachdb/cockroach/pull/78246
- https://github.com/cockroachdb/cockroach/pull/73473

**Comment by shermanCRL** [comment]
Discussed with CDC team, we’re agreed, let’s implement and get into a patch release ASAP.

**Comment by miretskiy** [comment]
Closing as stale.
