### ISSUE TITLE
sql: security issue in sql stats

### ISSUE THREAD

**Issue by Azhng** [cockroachdb/cockroach#79688]
[CRDB-14980](https://cockroachlabs.atlassian.net/browse/CRDB-14980)

**Comment by data-matt** [comment]
Please avoid admin roles. It is preferable to avoid putting features behind admin. 

@abhinavg6

**Comment by Azhng** [comment]
Resetting sql obs stats historically requires admin role (via Console UI). This issue is for missing the check for SQL CLI builtins instead of introducing new restrictions. cc: @kevin-v-ngo

**Comment by data-matt** [comment]
Perhaps something to be added to a matrix of features that are sitting behind the admin role.
