### ISSUE TITLE
sql/schemachanger: add testing to perform DML operations on tables concurrent with DDLs

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#79687]
**Is your feature request related to a problem? Please describe.**

In #79613 we saw a case where DML operations on a table during a certain schema change would fail. We had tested
that the change would succeed, so we fooled ourselves into thinking it was fine. It wasn't.

**Describe the solution you'd like**

Let's leverage randgen in some form to perform a select on the table in question during every schema change phase we can come up with.

**Describe alternatives you've considered**

We can and should also add select support to the `schemachange` workload

Jira issue: CRDB-14979

**Comment by ajwerner** [comment]
@ajwerner to split this into two tasks.

**Comment by ajwerner** [comment]
Okay, I split this out into https://github.com/cockroachdb/cockroach/issues/79835 for the randomized workload and this one exists for a more structured test on the end-to-end schema change suite.

**Comment by rafiss** [comment]
closing in favor of https://github.com/cockroachdb/cockroach/issues/108181 and https://github.com/cockroachdb/cockroach/issues/91863
