### ISSUE TITLE
sql: some schema changes use incorrect mutable descriptor

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#79704]
**Describe the problem**

The `Mutable` form of descriptors track internally the "original" version of the descriptor. This is useful for various things, including the split calculation done in https://github.com/cockroachdb/cockroach/pull/77337. When the mutable form of the descriptor is always retrieved from the collection, the "original" version will be properly maintained. There are, for better or for worse, other ways to get your hands on a mutable descriptor. In particular, one can use a `Builder` to get from an immutable to a mutable. Sadly, when you do that, you lose the history of the descriptor. 

One example of this bug was https://github.com/cockroachdb/cockroach/pull/79561. 

Generally, detecting this bug turns out to be easy: https://github.com/cockroachdb/cockroach/pull/79580

Unfortunately, there are other cases where we'd hit this issue. One is here: https://github.com/cockroachdb/cockroach/blob/d61df4c5a2d4ec266cb78d8ed987a7b708583da0/pkg/sql/database.go#L101

**Additional context**

This is loosely related to https://github.com/cockroachdb/cockroach/issues/64673. 

Jira issue: CRDB-14986

**Comment by postamar** [comment]
Backport has been merged, closing.
