### ISSUE TITLE
changefeedccl: default kv.rangefeed.catchup_scan_iterator_optimization.enabled to true in 21.2

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/cockroach#79727]
We had seen that changefeed catchup scans can be [disruptive to upgrades](https://cockroachlabs.atlassian.net/wiki/spaces/CKB/pages/2413756457/Changefeeds+are+disruptive+or+cause+increased+foreground+latency+during+or+after+version+upgrade?src=search&NO_SSR=1) (internal), including affecting foreground traffic, due to consuming a lot of IOPS.

I believe that we can confidently default `kv.rangefeed.catchup_scan_iterator_optimization.enabled ` to `true`, which will improve the upgrade experience. See [this comment](https://github.com/cockroachdb/cockroach/pull/73473#issuecomment-1093980843).

> We've had it default true on master for some time and rangefeeds have seen increased usage on master over this release cycle. Looking at the git history, I haven't seen any correctness changes to mvcc_incremental_iterator in the meantime either.

> Both will be shipping by default in 22.1 and at this point we've have these settings turned on in our largest installations. So, while catchup_scan_iterator_optimization is riskier than separated_intent_scan, I would have very little hesitation in turning both on by default in 21.2 if we think it'll cut down on problems for our users.

The risk here is not zero, but is small, and I believe upgrade disruptions we’ve seen justify it. Please review [this conversation](https://github.com/cockroachdb/cockroach/pull/73473#issuecomment-1093980843).

Let’s default `kv.rangefeed.catchup_scan_iterator_optimization.enabled ` to `true` in the next patch releases of v21.2.

---

Notes

Some care may need to be taken for mixed-versions: https://github.com/cockroachdb/cockroach/pull/73473#issuecomment-1092626962

> PS: we'd have to make sure these new default settings respect the relevant version gates, if they don't already, to avoid breakage in mixed-version 21.1/21.2 clusters.

See also:

- https://github.com/cockroachdb/cockroach/issues/76508
- https://github.com/cockroachdb/cockroach/issues/79655
- https://github.com/cockroachdb/cockroach/pull/78246
- https://github.com/cockroachdb/cockroach/pull/73473

Jira issue: CRDB-15943

**Comment by shermanCRL** [comment]
@stevendanna would you make the call here about our confidence in defaulting to true?

**Comment by erikgrinaker** [comment]
@shermanCRL I'm removing this setting over in #82450. Do you want to keep this issue around for defaulting it to `true` in 22.1 or earlier versions?

**Comment by shermanCRL** [comment]
Yes, let’s consider _this_ issue to be about v21.2. Thanks for working on it.

**Comment by mwang1026** [comment]
@shermanCRL removed repl per ^ discussion

**Comment by shermanCRL** [comment]
Did we follow through on this? If we still like the idea, let’s do so. We still get support issues from v21.2. @samiskin
