### ISSUE TITLE
kvserver: e2e flow control for raft messages

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#79755]
**Is your feature request related to a problem? Please describe.**

The flow control for raft messages is currently overly simplistic. A high-level overview of the current state follows.

#### Sending

Raft messages originate in a `raft.Ready`:

https://github.com/cockroachdb/cockroach/blob/40fd5d346cb64943d0d6655767b400b1177ce285/pkg/kv/kvserver/replica_raft.go#L596-L598

and are passed to the `RaftTransport` queues here:

https://github.com/cockroachdb/cockroach/blob/40fd5d346cb64943d0d6655767b400b1177ce285/pkg/kv/kvserver/replica_raft.go#L1443-L1465

There is a single queue for messages to each destination store (irrespective of rangeID), which is essentially a 10k-buffered channel:

https://github.com/cockroachdb/cockroach/blob/c23d1aacbc6c1fb93035eb6e0ff0794b37e89a77/pkg/kv/kvserver/raft_transport.go#L556-L557

from which batches of messages are put on the wire:

https://github.com/cockroachdb/cockroach/blob/c23d1aacbc6c1fb93035eb6e0ff0794b37e89a77/pkg/kv/kvserver/raft_transport.go#L515-L534

#### Receiving

Messages arrive here:

https://github.com/cockroachdb/cockroach/blob/c23d1aacbc6c1fb93035eb6e0ff0794b37e89a77/pkg/kv/kvserver/raft_transport.go#L386-L395

and are put on the raft receive queue:

https://github.com/cockroachdb/cockroach/blob/98a66b59d6a23b970159743c11c24d947c757f11/pkg/kv/kvserver/store_raft.go#L167-L185

The next available raft scheduler goroutine will pick up the nonempty queue in

https://github.com/cockroachdb/cockroach/blob/98a66b59d6a23b970159743c11c24d947c757f11/pkg/kv/kvserver/store_raft.go#L442-L460

and hands it to the raft group (which will not perform work yet, but instead stages everything for the next Ready):

https://github.com/cockroachdb/cockroach/blob/98a66b59d6a23b970159743c11c24d947c757f11/pkg/kv/kvserver/store_raft.go#L254-L256

Finally, a scheduler goroutine will actually process the replica for raft ready handling:

https://github.com/cockroachdb/cockroach/blob/98a66b59d6a23b970159743c11c24d947c757f11/pkg/kv/kvserver/store_raft.go#L497-L506

which is where I/O happens and the memory is flushed to disk.

**Describe the solution you'd like**

Introduce a model that more deliberately handles the case in which a follower is receiving more load than it can handle. Control the memory usage, while prioritizing heartbeats (and generally allowing QOS), without excessive performance cliffs. Integrate with admission control.

See also https://github.com/cockroachdb/cockroach/issues/79215.

Jira issue: CRDB-15932

Epic CRDB-15069

**Comment by irfansharif** [comment]
I read some of the discussion above and linked issues and PRs. I think this is going to be entirely encompassed by https://github.com/cockroachdb/cockroach/issues/95563.
