### ISSUE TITLE
acceptance: TestPartitionBank is disabled

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#7978]
https://teamcity.cockroachdb.com/viewLog.html?buildId=3652&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_Acceptance

`partition_test.go:60: pq: context deadline exceeded`

We only run this test now because we weren't able to on CircleCI ("Privileged mode" for containers is not available there).

Due to the nature of this test, I think what it's good at finding right now is internal timeouts which bubble up to the client, this being one of them.

I _suspect_ that the culprit is the `context.WithTimeout` in `(*intentResolver).resolveIntents`. Nowhere do we convert `context.{DeadlineExceeded,Canceled}` into errors which are handled anywhere.

This particular instance should likely be handled by #7933 (since then intentResolver would go through DistSender, which in turn _does_ do retries and is less susceptible to getting stuck on shutdown), but `git grep -F 'context.With'` turns up a few more.

**Comment by bdarnell** [comment]
Update: `intentResolver` now uses `DistSender` instead of talking directly to the replica, but the "context deadline exceeded" error persists.

**Comment by tamird** [comment]
@andreimatei care to look into this? Assigning you for now.

**Comment by tamird** [comment]
@andreimatei this test remains disabled. Can you please look into restoring it?
