### ISSUE TITLE
opt: cost of lookup join with lookup expression is under-estimated

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#79797]
The cost of a lookup join with a lookup expression is undercosted, which, after #79586, will cause a lookup join on a secondary index to be preferred over a lookup join on the primary index.

For example:

```
exec-ddl
CREATE TABLE small (
  k INT PRIMARY KEY,
  a INT
)
----

exec-ddl
CREATE TABLE big (
  k INT PRIMARY KEY,
  a INT,
  INDEX (a)
)
----

opt format=(show-stats,show-cost)
SELECT * FROM small INNER LOOKUP JOIN big ON small.k = big.k AND big.a = ANY ARRAY[1, 2, 3, 4, 5, 6]
----
inner-join (lookup big@big_a_idx)
 ├── columns: k:1!null a:2 k:5!null a:6!null
 ├── flags: force lookup join (into right side)
 ├── lookup expression
 │    └── filters
 │         ├── small.k:1 = big.k:5 [outer=(1,5), constraints=(/1: (/NULL - ]; /5: (/NULL - ]), fd=(1)==(5), (5)==(1)]
 │         └── big.a:6 IN (1, 2, 3, 4, 5, 6) [outer=(6), constraints=(/6: [/1 - /1] [/2 - /2] [/3 - /3] [/4 - /4] [/5 - /5] [/6 - /6]; tight)]
 ├── lookup columns are key
 ├── stats: [rows=60, distinct(1)=60, null(1)=0, avgsize(1)=4, distinct(5)=60, null(5)=0, avgsize(5)=4]
 ├── cost: 5209.44
 ├── key: (5)
 ├── fd: (1)-->(2), (5)-->(6), (1)==(5), (5)==(1)
 ├── scan small
 │    ├── columns: small.k:1!null small.a:2
 │    ├── stats: [rows=1000, distinct(1)=1000, null(1)=0, avgsize(1)=4]
 │    ├── cost: 1064.42
 │    ├── key: (1)
 │    └── fd: (1)-->(2)
 └── filters (true)
```

[optstepsweb](https://raduberinde.github.io/optsteps.html?eJzsne1uo0jWx78_V3Eef7LXYIMNpIeWpUQ9mVV6s05vMqPVKLEiYuM0EwxZwLOdWa00mmvIx7m6vpIVL7Z5qSqKd5ymvzROlaHqVHH-v3OqwP_p3fzjsif3bs4vzz_8CH-BH66v_g72RtF1uJjPz6_h8urqbz99go9XF3N40B7hau4Xj55g5v5h9ARn8--9IwVmcDb_Gc6ur89-vuUZmDAwZUBgQGRAWvSY3ty0Nt9r63VP7rEsC8r4wtAcTdHvjOFwCA-Hj6enwPIw5JnJOzg9vTOGz5b5i7p07owhfH398-vr719ff4elqW83hi3Dk8z_v7HVdVDkCTzJ4u6DFK1vO4pjy3Brmf-2Z1Pv32i6iJ_TdmTg1SHPcdGSJ_VFhj7PiIPo39cr988Dlr3bctxU7U8GDPTFw2cpqP8a1NcMQ7XYX0zNgP7SMm3bK_f-IboWGHvXQf-j203_aGmtHu41w1EtQ9HvN78ul_eOtlFtR9k8y9OgkqM86KqprWTBH7GdgbxBkyXvf-KJTrwq-9O8QzR4rSuPtgxr01qqoJvm0_YZ_D5qhmOCpT1-dsDWViqqt8iBYWCl2Y5mLJ0-P5jxHMcx4Dbb_cQxoPz6aGu_qe4nIVRVjFQVI1XFwUxYII0dHfNYcXTg4_2Ojz4rxMeffYfs81Ix_PEJFf5RyyzAXzAyEL4dqQdhQeqHZ2DunTCSJvhqgaEHyRqvBGvjbPugPVJYtvQbIoNFs8zVIhYV0yyKn637apruqJa9L4kV9_cTdKcKsjjwhKG_s2lUGybMlBEYkZEWA7g1t45qzdw7jJEGDCxNw3YsRTMce9Yf8zL0x_OfLi-BhcV7GIvhz4PFnXFn-Fpyo22edW39cma83CwVXbHOLEt52UkLrtRTGldmDmIDe7FBzhiC2KT6tEX8nGHHg_M5RHeDEBtIERs4NrFJNDiL2CS-XK_YIIwdHXOC2CT7TSk2yT6HxAbqFhvcBQuKDb4fEdeIq3YQm3gNstigbeuJTaplS78hyhWbUiwqplkUP1sTYsO2TmwKyl8_HhUNCrcoKn7n_9oqun1mvPy4fdbVuPjFS4nix2YUPzZzpJV2Tu-AEMJNOI7jWiGp7LFJaqMB5-FDnSCQGKOGo87kVK7m2qGq0mAmBfWkSD2pg5UOViqCFbYaWKki4I7eKvy-pvcBf7e8EVyqAE5y49LFvOzmvIexJMPtmAcWxvwCbscT92jiHk3do6l7JLhHgnskukeieyS5RxICtj6amvHDPjESIa1IURizplyhHEOARFjW2iERlpkkMjCxGO_OZgQmNjXhjU5SZbkK45bPZn3RL5nNgtQh-sqfFftz08mPNoJPO8gjQUebre5oz7q21JwXGXR17bBuc_u_qZbJmhZrGuqA8fuZLEijLSnWYYm2u1IdmJUYr-iNmBOzMMsaBRY10Pdfh3NvG-fyWLTjrqOinCi17Qc42Z1wSzPCIQPr1SzpP7DMSDTZvh1JaxWzxntwXIU5oN-nrf3Z57oLwzFdyrt2K-zwD1vsI-CU8xDwpAwEJIhbxpRY9oQYzvN35JWy9lSQasgk1zDV1I9cuTNWBfJVHfTUDT3JSb-HHlxq6ShyWNmgB99V9EaQfQtVPdg3l8NUub0mVXJO4ip1QxhDfSeMJJGGDuMWp9wx8wfCq1DXxm9cqnv_UmMTPbXjxI1P1Pufcg0qbjdUUAGgXciaaBEmYqmb8NHxUuPmQgcetRnFjy-sraG6ccOlunY-mPo-sYwoCGKKk284pmh03b24OtK3-u3GNEkv1OqwIWf-FbdWkXayciKQVE6ua3956gUrC16y8jOmmiSMBKoYh0iP-B3sabWRIx0gPq5R1SA-1ThVg_j4jmZEfFyNlAQwFtrjNerOxbcmJZ8tQ0A9Ptny9Dhoj1YAaBeFJloUb3esuCE-9fLaSEANlYQJVZh2hNoA65XJmh05VkuOFXJjrXnrxjLQ1HSG1QgEbyXzzwFv5co-l3cjhx6JztuORikujcgDikvN54qjyUmefC4Z9rAZf-ziQ91rEK1ZiiDDXkpt_PhQwR42zIplOlsKe9SrBoQYEb3CA7X6JNQla1_rSXSZ4EcANwuJ1WhWCeJWwKzo4Jxapcs6GJfW0NoOzgSEhAz6Kymjl2OpJ-YnSOs9saqNuxR849ENbiB-vPE8ViJ4DP_ZjxyF6TccOSIcWhe5tXSrUBdulRZuJWwUuu1TDHSkcY4fwKTFOSfiiKOKc3A1UEyJGxh0iIvzR_UxZfahpnY0FY032udQQel-5IWRkFjOwDor4uVzAGz6tImbGBMh57h5qyJe4kUx3WtJuI3rUGZoJjpx9FdSJll-zk77Jm7K0SztxKp2fE7k83Nd22iG4qif9tlFD9CTfw8T-je6-yjh-jpC7wj97RN6YkEkuRJR3taUVqN7wOSp6I4CuKLojst8l4TuKSdoC0cHpiXWzcvGaV8oEXTpTtFO5gx8DM1XCgIk7ns0iz6xqo1jYLVPgBzf8xzBLKrseY63_DQHeoq3O3AIHlvgvcCBPRAEErNzBBPYN-RI8dfjZHtzeWmETXhDT0VwXX_8hHsLUAV741D7q4q8I-fontReIO1J8V6ZfHvTsCMe73cZjyHkewC3hKcCkGyDip-ot_tXs6GM0kANRUkoRi-0Q6vy_VnHt9sKM1NL2211_HutWCw_oZ9Hre99N2hvOczlKBHfKvyjHunQTvCMQzqnOET4Q5IFCK4wzQRV7UVLc4BYM4kDZCE6hiFGjLmDxeb9HKnxuNlGY02qwJAUE7bUnQ2JEWzdTqzH9M6_POumpUZ-3-uvqqFaiqNeGCv1y81SMfY7vlAlQWTIhyJD9LJLwcWlbAsrJa6pvP2ID4f--ai_fOBPdy9EzKckfBTc5-T6ZpA-neaJ7pea4enELF54-qA93iv32upL5FJZN3k0r3nUWE9D9NlgnsTxrUV4TGsb0ryoxH3YnVNdIYUuWR6Wu4nQyV0nd0cqdywmdqP02wVju8PNLMNYcu_ewNlIaAPUkhHLEQv6NU6kkeC9kp1P0VjENTJrLJs_O9a8eJIaH8uJ0aTDsmXCSEmwloonLhFD-KmrtmnspSdeH03NsP-pOcGbluNCi6kU_AiH4Kot7__WGYtQ28gCZCCWD9pj3TrMVrPQ-KS-HNp-yy9gBrdiLAcZtCyoBoqlul-rX89ZrJ4nf6_7hOcPYUkn9TVJPULWkcpHs3qVTdZRqtagrIdFG1EJKTOZfXBi_aLmF_K3SMqqUYUJl1UVDjP_jehDcFX1y7Ol2rZmGtmS4382sHTWWtY6Zj0VJ9x3I0Ho9LTT07egp2zL9DTRGug71tZ1xr3__t__AgAA___K9SZW)

The majority of the costs in both lookup join alternatives comes from two things: the cost of performing the lookups and the cost of processing the resulting rows. The cost breakdown is roughly:

|               | PK Lookup | Secondary Index Lookup |
|---------------|-----------|------------------------|
| lookupCount   | 1000      | 1000                   |
| perLookupCost | 4         | 4.022                  |
| rowsProcessed | 1000      | 60                     |
| perRowCost    | 2.05      | 2.05                   |
| Total Cost    | 6050      | 4145                   |

In the PK lookup case, the cost of applying the `ON` filter to 1000 rows is much more than the marginal cost of the lookup expression in the secondary index lookup case - it only costs an additional 0.022 per lookup.

If there is a lookup expression, the `perLookupCost` should increase with respect to the number of lookup spans that will be generated for each row. In this example, there will be 6 spans for each input row, so the breakdown should look more like:

|               | PK Lookup | Secondary Index Lookup |
|---------------|-----------|------------------------|
| lookupCount   | 1000      | 1000                   |
| perLookupCost | 4         | **24**                  |
| rowsProcessed | 1000      | 60                     |
| perRowCost    | 2.05      | 2.05                   |
| Total Cost    | 6050      | 24123                   |

Jira issue: CRDB-15912

**Comment by mgartner** [comment]
This is related to #67479.

**Comment by rytaft** [comment]
@DrewKimball do you think you could take a look at this in the next week and see if it's an easy fix? Thanks!

**Comment by mgartner** [comment]
Is there a reason we moved this to 23.1? I'm worried this will cause performance regressions in 22.2.

**Comment by DrewKimball** [comment]
I think I conflated this with our discussion about whether it made sense to handle #85561 (and change costing) for 22.2. Do you think we should try and squeeze this in?

**Comment by DrewKimball** [comment]
I tried making the change on this [branch](https://github.com/cockroachdb/cockroach/compare/master...DrewKimball:lookup?expand=1). There's a somewhat concerning change in one of the tpce queries, but overall the blast radius seems fairly small.
