### ISSUE TITLE
dev: auto-regen+retry on missing bazel dependency errors

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#79790]
**Is your feature request related to a problem? Please describe.**

When moving files around, changing deps, etc. you frequently have to `dev gen bazel` first to get the subsequent `dev {build,test}` going. You'll often find that you need to after running `dev {build,test}`. Since it's so common, we could probably retry the same command after an opportunistic/automatic `dev gen bazel`. Some discussion [here](https://cockroachlabs.slack.com/archives/C019A8NANH0/p1649460243104739).

**Describe alternatives you've considered**

`ALWAYS_RUN_GAZELLE=1` is another approach, but it imposes a tiny-but-measurable overhead every time a command is run.

Epic [CRDB-8036](https://cockroachlabs.atlassian.net/browse/CRDB-8036)

Jira issue: CRDB-15913

**Comment by rickystewart** [comment]
Don't see us implementing this.
