### ISSUE TITLE
workload/schemachange: perform SELECT operations against tables

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#79835]
**Is your feature request related to a problem? Please describe.**

In https://github.com/cockroachdb/cockroach/issues/79613 we saw an issue with a schema change we had nominally tested. In practice, we never tested that during the schema change we could actually safely use the table. One way to check for safety will be to have the randomized schema changer construct select queries against tables (and views) and make sure that they work. 

**Describe the solution you'd like**

Just vanilla SELECT * queries are likely to reveal any errors. 

**Additional context**

This relates loosely to https://github.com/cockroachdb/cockroach/issues/79687

Jira issue: CRDB-15898

**Comment by fqazi** [comment]
Resolved via: https://github.com/cockroachdb/cockroach/pull/84399
