### ISSUE TITLE
sql: NULL geography concatenation is inconsistent with Postgres

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#79846]
From https://github.com/cockroachdb/cockroach/issues/67791#issuecomment-1028644823:

In Postgres 14.2:

```
marcus=# SELECT NULL::GEOGRAPHY || NULL::GEOGRAPHY[] || NULL::GEOGRAPHY;
  ?column?
-------------
 {NULL:NULL}
```

In CRDB 21.2.7:

```
defaultdb> SELECT NULL::GEOGRAPHY || NULL::GEOGRAPHY[] || NULL::GEOGRAPHY;
   ?column?
---------------
  {NULL,NULL}
```

Jira issue: CRDB-15892

**Comment by otan** [comment]
i wonder if this is just a display difference with non-postgres defined types.

```
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
otan=# SELECT NULL::GEOGRAPHY || NULL::GEOGRAPHY[] || NULL::GEOGRAPHY || NULL::GEOGRAPHY;
     ?column?
------------------
 {NULL:NULL:NULL}
(1 row)

otan=# SELECT NULL::int || NULL::int[] || NULL::int || NULL::int;
     ?column?
------------------
 {NULL,NULL,NULL}
(1 row)

otan=# SELECT array_length(NULL::GEOGRAPHY || NULL::GEOGRAPHY[] || NULL::GEOGRAPHY || NULL::GEOGRAPHY, 1);
 array_length
--------------
            3
(1 row)
```

**Comment by otan** [comment]
TIL about `typdelim` from `pg_type`, which is `:` for `_geography`:

```
otan=# select typdelim from pg_type where typname = '_geography';
 typdelim
----------
 :
(1 row)
```

**Comment by otan** [comment]
seems like there's to changes to make here:
* make a method `Delimiter` in the `types` package, which returns `;` for box, `:` for geom/geog and `,` for everything else
* change the delimiter for `Format` for `DArray`: https://github.com/cockroachdb/cockroach/blob/b9a675266303528d71b388ac35dfb87f145cc7a8/pkg/sql/sem/tree/datum.go#L4414
* change `pg_type` table to return the correct `typdelim`: https://github.com/cockroachdb/cockroach/blob/4c32814a93a9447abcc12c168a3a45a865cd3785/pkg/sql/pg_catalog.go#L2938
* add the relevant logic tests

**Comment by asing1** [comment]
@otan  I can start looking at it. Please assign it to me.

**Comment by otan** [comment]
Thanks for looking @surahman ! i've added some comments in https://github.com/cockroachdb/cockroach/pull/82304#issuecomment-1144281472
