### ISSUE TITLE
Make a single command to start the SQL client regardless of the binary

### ISSUE THREAD

**Issue by ianjevans** [cockroachdb/cockroach#79850]
**Is your feature request related to a problem? Please describe.**

For ease of documenting and a more consistent user experience, there should be a single command to start the SQL client regardless of whether the user installed the full `cockroach` binary or just `cockroach-sql`.

In the docs, users should be able to copy/paste commands that are guaranteed to run the SQL client however it was installed.

**Describe the solution you'd like**

A single command (alias or otherwise) to start the SQL client. For example, `cockroach-sql` could be an alias to `cockroach sql` if the user installed the full binary.

**Describe alternatives you've considered**

Adding selectors to the docs to indicate how the binary was installed to alter the command would needlessly complicate the documentation.

cc @knz

**Comment by knz** [comment]
> cockroach-sql could be an alias to cockroach sql if the user installed the full binary.

yeah we can probably make that work.

However, note that "the user installs the full binary" today means the user places the files in a location of their choosing. Would you be OK documenting in the installation notes the user should run `ln -s` as an additional step?

**Comment by ianjevans** [comment]
> However, note that "the user installs the full binary" today means the user places the files in a location of their choosing. Would you be OK documenting in the installation notes the user should run `ln -s` as an additional step?

Yes, that could work. For package installs, handling this automatically would be better. We could also follow the lead of other tools that download a shell script that handles these tasks automatically. I'm thinking of Pyenv Installer here, for example. https://github.com/pyenv/pyenv-installer

Though I know some users would not want to do this for security concerns.

**Comment by knz** [comment]
> For package installs, handling this automatically would be better. 

yes we can also do that once we start building these packages. This hasn't happened yet,but we can keep it in mind.

**Comment by ianjevans** [comment]
I saw this alert when I tried running a PowerShell script to download `cockroach-sql` for Windows.
<img width="590" alt="Screen Shot 2022-07-29 at 12 40 43 PM" src="https://user-images.githubusercontent.com/5760366/181832587-20e4a25f-7062-4167-bb88-81c2fa1d3b8b.png">

This is the PowerShell script:

~~~
$ErrorActionPreference = "Stop"; [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;$ProgressPreference = 'SilentlyContinue'; $null = New-Item -Type Directory -Force $env:appdata/cockroach; Invoke-WebRequest -Uri https://binaries.cockroachdb.com/cockroach-sql-v22.1.4.windows-6.2-amd64.exe -OutFile $env:appdata/cockroach/cockroach-sql.exe; $Env:PATH += ";$env:appdata/cockroach/cockroach-sql"; if (!(Test-Path "$env:appdata/cockroach/cockroach.exe")) { New-Item -ItemType SymbolicLink -Path $env:appdata/cockroach/cockroach.exe -Target $env:appdata/cockroach/cockroach-sql.exe }
~~~

I was running this in an Administrator PowerShell terminal, so I could create a symlink (the last part of the script). By default Windows requires Administrator permissions to create symlinks. If you run it in a regular PowerShell terminal, you get the following error:

~~~
New-Item : Administrator privilege required for this operation.
At line:1 char:484
+ ... ch.exe")) { New-Item -ItemType SymbolicLink -Path $env:appdata/cockro ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (D:\Users\ian\Ap...ckroach-sql.exe:String) [New-Item], UnauthorizedAcc
   essException
    + FullyQualifiedErrorId : NewItemSymbolicLinkElevationRequired,Microsoft.PowerShell.Commands.NewItemCommand
~~~

But you get the Quarantine message even if you run it in a non-privileged PowerShell terminal, or if you omit the symbolic link step.

FWIW, you do not get this quarantine message when downloading the Windows `cockroach` binary.

**Comment by knz** [comment]
You're lucky I accidentally saw the notification for this. Closed issues typically don't get attention any more.

The discussion for this is happening on #81246.
