### ISSUE TITLE
cdc: get better confidence in schema change classifier

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#79898]
Our schema change filter logic is kind of hacky and the tests around it don't look like they're always testing what they think they're testing. Hopefully we can throw all this out when declarative schema changes are everywhere, but right now we should make our testing and logic more rigorous--ideally we'd have a test that fails if we ever fail to classify any schema change anywhere.

Jira issue: CRDB-15869

Epic CRDB-9179

**Comment by amruss** [comment]
Let's timebox this

**Comment by miretskiy** [comment]
@HonoreDB @amruss  -- last update, 9 month ago, was "let's timebox this"...
So, should this issue be closed?
