### ISSUE TITLE
sql/schemachanger: regression in parallel schema changes

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#79905]
**Describe the problem**

In the 22.1 cycle, much work was done to eliminate contention between concurrent schema changes (https://cockroachlabs.atlassian.net/browse/CRDB-10719). One of the most important things which was done to teach the job system to look for jobs in a more precise way (https://github.com/cockroachdb/cockroach/pull/72297). 

There was a left-over TODO to adopt this precise tracking in the declarative schema changer. https://github.com/cockroachdb/cockroach/blob/64abaf28edb74345d1b7e7a2acc121c00f0236de/pkg/sql/schemachanger/scdeps/run_deps.go#L131-L133 

We need to fix that. 

**To Reproduce**

Run the prisma tests. 

**Expected behavior**

They run fast. 

Epic: https://cockroachlabs.atlassian.net/browse/CRDB-10719

**Comment by postamar** [comment]
Closing because this fix brings the prisma short test suite runtime down from 30 minutes to 5.
