### ISSUE TITLE
Cluster Setting change log

### ISSUE THREAD

**Issue by greg-crl** [cockroachdb/cockroach#79903]
**Is your feature request related to a problem? Please describe.**

One step frequently taken in troubleshooting a cluster is checking whether any cluster settings deviate from the default.  That's easy enough to do, but once you've identified that a setting has been changed, you also want to know when it was changed, and what its value was before.  Typically, users (even enterprise users) don't have good change management in place (at least not for this sort of thing); reconstructing the change history is a matter of querying people who might know, reviewing meeting notes and emails and Slack threads to see if the issue had been discussed or any recommendations made.

**Describe the solution you'd like**

It'd be terrifically useful if CRDB automatically maintained a change log of configuration settings that wasn't just its MVCC history, especially if it were available as a SQL query-able table.  (The same request might be made about other system configuration values, such as Regions and Zone Configurations, and the same mechanism might be usable for them as well, but this FR is about cluster settings.)

**Describe alternatives you've considered**

These change notices could go into the log files, but they'd be harder to get from the system, and they could still age out.

Jira issue: CRDB-15866

**Comment by mattcrdb** [comment]
They currently do go into the log files, but on the support side we agree this would be helpful.

@shermanCRL talked about having something like this recently as well.

FWIW, I'm thinking changes like cluster setting could go into the event log? Perhaps with some changefeed like structure? 

For example, `setting changed <setting> {"before:...","after:..."};`

**Comment by mattcrdb** [comment]
perhaps a duplicate of https://github.com/cockroachdb/cockroach/issues/68393

**Comment by greg-crl** [comment]
Not really a duplicate, as 68393 requests a DB Console page.  The added value of the table this issue requests is that its contents could be queried and dumped by the customer during a troubleshooting exercise, shared with us (TSE or CEA), possibly even included in a debug.zip.
