### ISSUE TITLE
sql: Add dropdown option for ttl deletion jobs on the Jobs page

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/cockroach#79915]
**Expected behavior:**
There is a dropdown filter for row-level deletion jobs on the Jobs page.

![image](https://user-images.githubusercontent.com/13694532/163252725-1b2b71cc-e458-4288-8e01-588c5f9d7afe.png)

Epic CRDB-14592

**Comment by maryliag** [comment]
where is the name you want to show on the dropdown?

**Comment by vy-ton** [comment]
It should be `Time-to-live Deletions`

**Comment by otan** [comment]
is `Row-level Time-To-Live Deletions` ok?

**Comment by vy-ton** [comment]
We've avoided `row-level` in settings so I was aiming for consistency here.
