### ISSUE TITLE
sql: Enhance jobs details for row-level TTL deletion jobs

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/cockroach#79916]
Problem:
When a user has multiple tables configured with row-level TTL, the job description/details does not indicate what table is undergoing deletion. The `SQL Activity` page also does not include statements for the internal queries to find and delete expired rows.

<img width="1745" alt="image" src="https://user-images.githubusercontent.com/13694532/163253366-1bdf3e07-ccba-4e27-b9b8-e1468cb38355.png">

Another example where table information is needed: when `sql.ttl.job.enabled=false`
<img width="1755" alt="image" src="https://user-images.githubusercontent.com/13694532/163262013-68243f37-d2bd-4e60-89dc-f3a3213f2429.png">

Expected behavior:
* Can the deletion jobs description/details include the statements to find/deleted expired rows? What exactly did the database run for users.
* Queries to find expired rows and `DELETE` statements from TTL deletion jobs will show up with the $ internal application name on the SQL activity page

Epic CRDB-14592

**Comment by otan** [comment]
> Can the deletion jobs description/details include the statements to find/deleted expired rows? What exactly did the database run for users.

yes, PR incoming

> Queries to find expired rows and DELETE statements from TTL deletion jobs will show up with the $ internal application name on the SQL activity page

that's a different issue and likely something we'll need to ask queries about - not sure why internal executor queries do not show up on that page.

**Comment by rafiss** [comment]
> Queries to find expired rows and DELETE statements from TTL deletion jobs will show up with the $ internal application name on the SQL activity page.

More of a sql-observability issue: https://github.com/cockroachdb/cockroach/issues/79547

**Comment by otan** [comment]
> Can the deletion jobs description/details include the statements to find/deleted expired rows? What exactly did the database run for users.
> Queries to find expired rows and DELETE statements from TTL deletion jobs will show up with the $ internal application name on the SQL activity page

This will be the case when https://github.com/cockroachdb/cockroach/issues/79547 is addressed. - I'm closing this issue in favour of that for now.

I've added https://github.com/cockroachdb/cockroach/pull/79927 to make the "jobs" more identifiable, which will display nicely once we have #79547 addressed. In the meantime, `SHOW STATEMENTS` is a workaround.

**Comment by vy-ton** [comment]
Even with https://github.com/cockroachdb/cockroach/issues/79547, there's not a way to connect statements to the job that spawned them, right? Let's start with making the jobs more identifiable but I'll keep an eye out for whether user debugging requires more observability

**Comment by otan** [comment]
It does - the statement will display the table name as well in SHOW STATEMENTS
