### ISSUE TITLE
sql: SHOW SESSIONS behavior

### ISSUE THREAD

**Issue by gtr** [cockroachdb/cockroach#79913]
**Is your feature request related to a problem? Please describe.**
Currently, the `SHOW SESSIONS`SQL command has the following help message:
```
Command:     SHOW SESSIONS
Description: list open client sessions
Category:    miscellaneous
Syntax:
SHOW [ALL] [CLUSTER | LOCAL] SESSIONS
```

which means that it should *only* show open sessions. However, due to the [recent](https://github.com/cockroachdb/cockroach/pull/78650) work done to expose closed sessions, we now have the ability to list closed sessions.

**Describe the solution you'd like**
It would be interesting to add a flag, perhaps `--show-closed-sessions` which would be combined with the other syntax (`[ALL] [CLUSTER | LOCAL]`. 

**Describe alternatives you've considered**
N/A

**Additional context**
An additional piece of information we can discuss is the meaning of the `ALL` keyword in the syntax for this command. Would it be confusing to *not* show closed sessions when a user types `ALL` without specifying the `--show-closed-sessions` flag? Or is it well understood that `ALL` refers to open sessions only?

Jira issue: CRDB-15729

**Comment by kevin-v-ngo** [comment]
For backwards compatibility and to provide clarity on "ALL", one approach is to add a flag for "OPEN" and make that the default. And when "ALL" is specified, we also show in-memory closed sessions.

**Comment by maryliag** [comment]
No longer a priority
