### ISSUE TITLE
sql: fix logging contexts

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#7992]
As of PR #7990, all logging functions take a context. The call sites were changed to use `context.TODO()`. These need to be fixed to provide a suitable context. Ideally all logs emitted by a server should use a context derived from that server's context.

This issue tracks this work for code under `sql/`. Part of #1779.

**Comment by RaduBerinde** [comment]
We still need to plumb context for logs in the schema changer and lease manager.
@vivekmenezes, @andreimatei I think you are most familiar with these if you have some time.

**Comment by andreimatei** [comment]
Plumbing in the lease manager is coming.
For the schema changers (sync and async) it was less clear to me what context we want exactly, but will do something...

**Comment by spencerkimball** [comment]
Is this issue closable yet? I'm removing 1.0 milestone.

**Comment by andreimatei** [comment]
I think this issue is good to be closed.
There's some work for tracing schema changes tracked in #16700
