### ISSUE TITLE
sql: want max_connections session variable

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#80003]
This random postgres tool I'm trying to run wants to do `show max_connections`. We should consider returning a dummy value.

Jira issue: CRDB-15694

**Comment by rafiss** [comment]
@andreimatei which tool is it? it can help us prioritize

**Comment by andreimatei** [comment]
It was [Promscale](https://www.timescale.com/promscale). It has many other reasons why it doesn't work with CRDB, and in future releases it will require a Timescale pg extension, so it's probably a lost cause. Unrelatedly, we might fork it for the Observability Service.

**Comment by rafiss** [comment]
Perhaps we should just make this a read-only variable that just delegates to showing the value of `server.max_connections_per_gateway`
