### ISSUE TITLE
kvserver/reports: export and document report IDs

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#80002]
**Is your feature request related to a problem? Please describe.**

There are three types of reports managed by the `reports` package. T

https://github.com/cockroachdb/cockroach/blob/69e48ba9e1d7d79be5af1f2dd196ca204424919b/pkg/kv/kvserver/reports/constraint_stats_report.go#L34
https://github.com/cockroachdb/cockroach/blob/69e48ba9e1d7d79be5af1f2dd196ca204424919b/pkg/kv/kvserver/reports/critical_localities_report.go#L30
https://github.com/cockroachdb/cockroach/blob/69e48ba9e1d7d79be5af1f2dd196ca204424919b/pkg/kv/kvserver/reports/replication_stats_report.go#L32

The report types show up in the `system.reports_meta` table. The `reportID` type and its values are unexported and undocumented. We should fix that. 

**Additional context**

These facts were leveraged in https://github.com/cockroachdb/cockroach/pull/79977. 

Jira issue: CRDB-15695

**Comment by nvanbenschoten** [comment]
Moving the code changes to on-hold, but opening a docs issue to track the more important part of this.

**Comment by nvanbenschoten** [comment]
Docs issue: https://github.com/cockroachdb/docs/issues/13770.
