### ISSUE TITLE
Install Cockroach Natively on Apple Silicon Using Curl

### ISSUE THREAD

**Issue by conradwt** [cockroachdb/cockroach#80008]
**Is your feature request related to a problem? Please describe.**

I would like to be able to install CockroachDB natively on Apple SIlicon using curl.

**Describe the solution you'd like**

```zsh
curl https://binaries.cockroachdb.com/cockroach-v21.2.9.darwin-10.9-arm64.tgz | tar -xJ && cp -i cockroach-v21.2.9.darwin-10.9-arm64/cockroach /usr/local/bin/
```

**Describe alternatives you've considered**

The alternative solutions are as follows:

- amd64 binary which would execute under Rosetta 2
- build from the source

**Comment by rickystewart** [comment]
Dup of #68648
