### ISSUE TITLE
sql: constraints which involve NOT VISIBLE columns do not appear in SHOW CONSTRAINTS

### ISSUE THREAD

**Issue by Cpaczek** [cockroachdb/cockroach#80035]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:
Currently trying to implement cockroachdb on the headless CMS Strapi (https://github.com/strapi/strapi/pull/12346). They use knex but I am still having trouble with table constraints not showing up

**To Reproduce**
Currently we are making this table
```
CREATE TABLE public.admin_permissions_role_links (
permission_id INT8 NULL,
role_id INT8 NULL,
rowid INT8 NOT VISIBLE NOT NULL DEFAULT unique_rowid(),
CONSTRAINT "primary" PRIMARY KEY (rowid ASC),
CONSTRAINT admin_permissions_role_links_fk FOREIGN KEY (permission_id) REFERENCES public.admin_permissions(id) ON DELETE CASCADE NOT VALID,
CONSTRAINT admin_permissions_role_links_inv_fk FOREIGN KEY (role_id) REFERENCES public.admin_roles(id) ON DELETE CASCADE NOT VALID,
INDEX admin_permissions_role_links_fk (permission_id ASC),
INDEX admin_permissions_role_links_inv_fk (role_id ASC),
FAMILY "primary" (permission_id, role_id, rowid)
)
```
You can see that there should be a constraint on the primary key
`CONSTRAINT "primary" PRIMARY KEY (rowid ASC),`

However if you run the above command then do:
` show constraints from admin_permissions_role_links`

You can see that the constraint isn't even there?
![image](https://user-images.githubusercontent.com/25715982/163665563-aec53496-ca5f-4272-9ab4-b4995a3e4782.png)

**Expected behavior**
The constraint should be listed when running `show constraints` 

**Environment:**
 - CockroachDB version: 21.2.4
 - Server OS: Windows 10
 - Client app: cockroach sql

**Comment by otan** [comment]
this is "deliberate" - we don't show constraints for PKs and indexes on "hidden" only columns (e.g. rowid, which was specified NOT VISIBLE).

https://github.com/cockroachdb/cockroach/blob/b01d6c7e57c3e2dafb4194d3788253ad3b988610/pkg/sql/catalog/tabledesc/table.go#L327

I wonder if that's desirable cc @rafiss @vy-ton

**Comment by Cpaczek** [comment]
> this is "deliberate" - we don't show constraints for PKs and indexes on "hidden" only columns (e.g. rowid, which was specified NOT VISIBLE).
> 
> [cockroach/](https://github.com/cockroachdb/cockroach/blob/b01d6c7e57c3e2dafb4194d3788253ad3b988610/pkg/sql/catalog/tabledesc/table.go#L324-L335)

Ah that makes sense, we don't actually need it to show up in `show constraints` however when we try and drop the constraint it does not exist. Is it only hiding it or does it also prevent access to it?

Here is the error that we are trying to solve using knex

```
 {
    sql: 'alter table "admin_permissions_role_links" drop constraint "primary"',
    bindings: []
  },

```
With the error being:
```
alter table "admin_permissions_role_links" drop constraint "primary" - constraint "primary" of relation "admin_permissions_role_links" does not exist
```

**Comment by otan** [comment]
You can't drop the primary key in CRDB. You need to use ALTER PRIMARY KEY if you want to change it

**Comment by Cpaczek** [comment]
> You can't drop the primary key in CRDB. You need to use ALTER PRIMARY KEY if you want to change it

Thank you, was able to figure out the issue, You can drop pk constraints as long as you add them back in the same transaction which we weren't doing. Now onto the next issue, thanks for you help. fix documented here: https://github.com/strapi/strapi/pull/12346

**Comment by vy-ton** [comment]
> this is "deliberate" - we don't show constraints for PKs and indexes on "hidden" only columns (e.g. rowid, which was specified NOT VISIBLE).
I wonder if that's desirable

FYI @devadvocado for future discussion

**Comment by rafiss** [comment]
> this is "deliberate" - we don't show constraints for PKs and indexes on "hidden" only columns (e.g. rowid, which was specified NOT VISIBLE).
> I wonder if that's desirable

It also feels like this could be causing https://github.com/cockroachdb/activerecord-cockroachdb-adapter/issues/203

**Comment by rafiss** [comment]
The rationale in
https://github.com/cockroachdb/cockroach/commit/9d61c053cb7f075fa695b2eea3061d8a7908d634
is

> Hidden columns, such as the auto-created `rowid` column on tables
without primary keys, are not shown in `SHOW COLUMNS` or column metadata
tables in `information_schema` and `pg_catalog`. However, these hidden
columns do show up in `SHOW CONSTRAINTS` and constraint metadata tables.
This is problematic because it introduces broken references in the
metadata tables that can confuse users and ORMs, such as ActiveRecord.

However, that's no longer true -- we do show `rowid` in
information_schema.columns and SHOW COLUMNS.

So I think it makes sense to show them in SHOW CONSTRAINTS.
