### ISSUE TITLE
spanconfig: add component metrics

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#80147]
**Is your feature request related to a problem? Please describe.**

The following metrics are useful to surface from the span configs infrastructure:
- number of [KVSubscriber restarts due to internal errors](https://github.com/cockroachdb/cockroach/blob/5e70321fad7ab991791338c21c52201c5957bc44/pkg/spanconfig/spanconfigkvsubscriber/kvsubscriber.go#L181-L195)
-  number of KVAccessor invocations, number of stored spans, how long operations take (even if just a counter of total duration)
  - count clock-past-lease-expiration errs (added for #73789)
- per-store metrics on how many replicas each tenant has

Jira issue: CRDB-15834

**Comment by ajwerner** [comment]
Here's some more ideas:

* Reconciler:
    * Reconciliations started / completed (full vs incremental)
    * Total time spent in reconciliation (can divide for average times)
    * Num RPCs sent, num deletes, num upserts
* Server side
    * RPCs received
    * statements issued
    * total statement time
    * errors
