### ISSUE TITLE
security,sql: provide guidance about the client-side cpu usage of scram authentication

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#80246]
**Note: this is a meta-issue. There are multiple "projects" under this epic. See the jira epic link for details.**

We've discovered that an anomaly exists under the following set of circumstances (all conditions need to apply simultaneously):

- scram authn is enabled
- client driver does not configure max number of conn in their conn pool
- client app is cpu-constrained
- client app issues txns concurrently

in that case, it's possible that each new txn causes a new conn to be opened (no max limit), which incurs new cpu usage due to the scram hashing, which causes existing txns to become slower, which in turn causes more conns to be opened, resulting in overall cpu starvation.

This is a typical case of queuing anomaly, where the input rate (txns to perform) is larger than the  output rate (sql authn events) without a throttling mechanism. The CPU becomes the throttling mechanism, which is undesirable.

**Note: this issue would also exist with a regular PostgreSQL server with scram authn enabled.** (it's not specific to CockroachDB)

### How to identify the problem

The key symptom to recognize this situation is a combination of high client-side CPU usage and abnormal and increasing latency in opening new SQL connections.

A secondary symptom is growing number of simultaneous conns per client, looking at metrics server-side.

### Workaround in client apps

When the issue is observed, the problem can be addressed durably in the client with *either* of the following approaches:

- set a max number of concurrent active conns in the SQL conn pool. (This is done by default in many drivers/frameworks already )
- add a semaphore around the sql conn establishment
- optimmize the txn pattern so that the overall duration of a txn is reduced (e.g. by reducing the number of client-server roundtrips)

### Temporary workaround in CockroachDB

In v22.1, we're going to temporarily disable the automatic upgrade of self-hosted clusters to SCRAM, until we better inform our community of this pitfall.

The next steps will be as follows:
- new CC clusters will get SCRAM enabled by default (this will require explicit cluster settiing to be set by the CC orchestration code)
- previous-version CC clusters will be upgraded to SCRAM incrementally
- users running SH clusters will be informed of how to upgrade to SCRAM and how to check for the above anomaly in their client apps

Jira issue: CRDB-15793
Epic: CRDB-19340

**Comment by knz** [comment]
@rafiss has explained the following:

- the decision for the go ecosystem was discussed [here](https://github.com/golang/go/issues/4805#issuecomment-66074601)
- hikariCP (java) defaults to max of 10 conns
- activerecord (ruby) defaults to max of 5
- django-db-connection-pool (python; don’t know if it’s the “official” one) defaults to 10
- sqlalchemy (python) defaults to 5

@mgartner explains:
- Knex.js defaults to max of 10.

**Comment by celiala** [comment]
We haven't selected the SHA for rc.1, so adding the "blocks-rc.1" label, with this context:

> [knz] I don't feel this needs to block rc1 as long as we know for sure there will be rc2 afterwards. But if we were planning to turn rc1 into 22.1.0, then yes it should be blocked

**Comment by knz** [comment]
This is not the issue to mark GA-blocker. There's no change required as a result of this issue.

**Comment by rafiss** [comment]
Initially, we had labeled this a GA-blocker for v22.1. We removed the label because we turned off SCRAM by default in v22.1. Since v22.2 will once again have SCRAM on by default, I'm adding the label back.

**Comment by celiala** [comment]
Hi @rafiss @duoclikebook @jtsiros -

For the Monday Triage meetings, the script uses the Project associated with release-blocking issues.
Since we no longer have a "DB Server & Security" team, feel free to move this to the appropriate project, so the issue ends up under the right team/category for next week's Triage meeting.

Thanks!

**Comment by rafiss** [comment]
Moving to KV team as per [Slack convo](https://cockroachlabs.slack.com/archives/C01CDD4HRC5/p1661787063265479).

**Comment by knz** [comment]
NB: this is now a meta-issue. There's an overarching epic in jira now with tasks for other teams under it.

**Comment by rafiss** [comment]
The docs have been merged
