### ISSUE TITLE
sql: use wildcard to show grants for all schemas in a database

### ISSUE THREAD

**Issue by fabiog1901** [cockroachdb/cockroach#80253]
We can use a wildcard for listing all grants for the tables in a database

```text
> show grants on table mydb.* for mydb_mgmt;
  database_name | schema_name | table_name |  grantee  | privilege_type
----------------+-------------+------------+-----------+-----------------
  mydb          | public      | t1         | mydb_mgmt | ALL
  mydb          | public      | t2         | mydb_mgmt | ALL
(2 rows)
```

Can we enhance the product to have the same behavior for the schemas? This avoids fetching the list of schema, and loop through each one of them.

```
> show grants on schema mydb.* for mydb_mgmt;
invalid syntax: statement ignored: at or near "*": syntax error
```

[Slack conversation](https://cockroachlabs.slack.com/archives/C0168LW5THS/p1650473812649509)

**Comment by lkyuchukov** [comment]
Can I try this ?

**Comment by likzn** [comment]
I see the `parser` of `yacc` not support such `SCHEMA '.' '*'` .Should we add some syntax like below in `SCHEMA` block?

```y
| db_object_name_component '.' '*'
  {
     $$.val = &tree.UnresolvedName{Star: true, NumParts: 2, Parts: tree.NameParts{"", $1}}
  }
| 
```

**Comment by lkyuchukov** [comment]
`show grants on mydb.*` only returns the grants for the public schema of `mydb`, not every schema in the database. Is this desired behavior?

**Comment by fabiog1901** [comment]
@lkyuchukov , the desired behavior is to list the grants for every schema, not just `public`. Thank you

**Comment by lkyuchukov** [comment]
Maybe we should open a separate issue for this. I'm about to submit a PR for this issue

**Comment by fabiog1901** [comment]
Well, to be honest this is the issue for this, the title is clear and the use of a wildcard kind of implies that you'd want to have listed all objects, in this case schemas, that are children of the database object. So while this is certain an improvement (most folks only use the `public` schema), it may be misleading. I'll let @rafiss or who else reviews this decide..

**Comment by lkyuchukov** [comment]
The way I understood it was that you have the functionality to use `*` for listing all grants for the tables in a database and it would be good to have the same thing for schemas.
