### ISSUE TITLE
sql: high create and alter user tail latency

### ISSUE THREAD

**Issue by JeffSwenson** [cockroachdb/cockroach#80288]
**Describe the problem**

The `CREATE USER <user> WITH PASSWORD <password>;` and `ALTER USER <user> WITH PASSWORD <password>;` statements occasionally take longer than 60 seconds. In production the RPCs time out at 60 seconds, so the actual max latency is unclear. I manually inspected a sample of 10 timed out traces. 3 slow traces impacted dedicated clusters and 7 slow traces impacted Serverless clusters. The slow traces impact the 99pct create user latency.

**To Reproduce**

1. Probe a Serverless cluster with "ALTER USER <username> WITH PASSWORD <random_password>;".
2. Run a large workload that briefly scales the cluster beyond one pod.
3. Wait 10 minutes for the serverless cluster to scale back down to one pod.
4. ALTER USER commands will hang for the next 5 minutes. The 5 minutes is consistently reproducable.

I was unable to reproduce the latency with `SET CLUSTER SETTING server.authentication_cache.enabled = false;`.

I was unable to manually reproduce this on a dedicated cluster. It's possible the slow traces I found were the result of random control plane -> data plane networking problems or cluster overload.

**Additional data / screenshots**

The Serverless infrastructure does not yet take advantage of https://github.com/cockroachdb/cockroach/pull/76294. So this may have something to do with how SQL pods are terminated.

cc: @rafiss @knz 

Jira issue: CRDB-15784

**Comment by rafiss** [comment]
Is this all on v21.2? I wonder if v22.1 will improve things, since we simplified the caching logic: https://github.com/cockroachdb/cockroach/pull/77548

**Comment by abhinavg6** [comment]
cc @kpatron-cockroachlabs @jtsiros as just FYI from a IAM perspective

Thanks for logging this @JeffSwenson

**Comment by emily-horing** [comment]
Just noting that I think this surfaces as an error in CC somewhat frequently (I've personally seen it 2x and seen it reported 2x). Is there any easy way for us to validate if 22.1 does reduce the error rate? Maybe @JeffSwenson might have an idea?

**Comment by rafiss** [comment]
Please let us know if it's still happening in 22.1 -- I'll table this issue until we get those details.

**Comment by JeffSwenson** [comment]
I reviewed monitoring and it looks like this issue no longer exists.
