### ISSUE TITLE
performance: investigate performance degradation

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#8029]
All test clusters have been exhibiting a noticeable pattern for quite some time:
Shortly after cluster startup and launch of the block_writer and photos apps, both their performances drop to close to zero qps.

Some errors do get logged (deadline exceeded, duplicate key, transaction restarts), but a lot more digging is necessary.

Assigning to Peter for triage.

**Comment by petermattis** [comment]
After many changes `block_writer` performance is now fairly stable while `photos` has problems, but there is more specific investigation happening there.
