### ISSUE TITLE
Need a GetProtoCall in KV client

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#803]
Current code to do a get and unmarshal the result is pretty unwieldy. Another mechanism would be a big win. Also should find current call sites in code and clean them up.

**Comment by BramGruneir** [comment]
I just had to do this in the store status stuff.  I'll add this in.

**Comment by spencerkimball** [comment]
I think it's rather more dicey than just adding a call as my simple title suggests. Coordinate with Pete.
