### ISSUE TITLE
Surface metrics with each TTL deletion job

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/cockroach#80309]
Per [thread](https://cockroachlabs.slack.com/archives/C02DSDS9TM1/p1650557231351209?thread_ts=1650557149.495459&cid=C02DSDS9TM1)
> it is up to an individual job to persist that if it wants to. IMPORT for example does persist a summary of what it imported (rows, index entries, bytes) 

For each TTL deletion job, here is a list of metrics that could be captured and surface on the Jobs detail page

- [ ] number of rows deleted in the job

Epic: CRDB-14592

Jira issue: CRDB-15774

**Comment by rafiss** [comment]
closed by https://github.com/cockroachdb/cockroach/pull/81917
