### ISSUE TITLE
changefeeds: dynamically reduce batch size on Kafka ‘message too large’ 

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/cockroach#80313]
**Is your feature request related to a problem? Please describe.**
Users can get `kafka server: Message was too large, server rejected it to avoid allocation error`. We’ve worked on [several fixes](https://github.com/cockroachdb/cockroach/pull/76265) here. We’ve learned that the source of this error can be on the server _or_ on the client (where ‘client’ means CRDB or more specifically, the Sarama library).

There is a class of these errors where this size error is due to batch size -- where no individual message exceeds the max size, but the batch adds up to exceed it. In these cases, the message would have succeeded if the batch size were smaller.

**Describe the solution you'd like**
It would be good if CRDB would detect the above situation, and retry with a smaller batch size. It could be a backoff loop: say, cut the batch in half, retry, repeat.

Success would be that we got to a batch size under the max size limit, so the changefeed continues without incident. Failure would be that a single message remains that exceeds the max size, which would be fatal (and is the status quo).

**Describe alternatives you've considered**
Users can adjust the batch size themselves, but it’s hardly obvious that this is the source of the above error. Users can increase the max message size on the Kafka server as well.

Epic CRDB-12280

Jira issue: CRDB-15772

**Comment by amruss** [comment]
Part of https://cockroachlabs.atlassian.net/browse/CRDB-12280

**Comment by amruss** [comment]
Moving this to stability period as there have been several recent escalations around it
