### ISSUE TITLE
bulkio: show bytes transferred on backup job

### ISSUE THREAD

**Issue by fabiog1901** [cockroachdb/cockroach#80328]
The current backup job output shows a `bytes` column, but contrary to my understanding, this is not the number of bytes being transferred to the destination storage device, rather, it is the data size of the uncompressed data.

It would be helpful to add the actual size of all data being transferred. Currently, the only way to find out is to calculate the size by inspecting the destination storage. 

[slack conversation](https://cockroachlabs.slack.com/archives/C2C5FKPPB/p1650543201886429) 

Jira issue: CRDB-15765

Epic CRDB-10342

**Comment by msbutler** [comment]
Closing because https://github.com/cockroachdb/cockroach/pull/80491 allows the user to compute this.
