### ISSUE TITLE
ui: enable strict null checks

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#8035]
Now that we're on TypeScript 2.0, we have access to this exciting feature. All that is needed to enable it:

``` diff
diff --git a/ui/tsconfig.json b/ui/tsconfig.json
index 9f47ea8..191e5da 100644
--- a/ui/tsconfig.json
+++ b/ui/tsconfig.json
@@ -12,6 +12,7 @@
     "noFallthroughCasesInSwitch": true,
     "noImplicitAny": true,
     "noUnusedLocals": true,
+    "strictNullChecks": true,
     "target": "ES5"
   },
   "files": [

```

Of course, the bulk of the work is in getting our code working with it.

**Comment by couchand** [comment]
As of today we've got a little over 600 violations, so this will be an effort, but the value seems clear.
