### ISSUE TITLE
security: define new cluster setting to *require* pre-hashed passwords

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#80362]
This request is a followup to #72579 and stems from a convo with @MichaelTrestman  around docs for SCRAM: we would like to write a convincing story about making CockroachDB blind to cleartext passwords.

Currently, this is somewhat hard to achieve because even though crdb recognized pre-hashed passwords (#72579), it cannot *require* them yet. This makes it possible for a user to accidentally expose a cleartext password to CockroachDB via an ALTER/CREATE USER/ROLE WITH PASSWORD statement.

Jira issue: CRDB-15752

**Comment by knz** [comment]
cc @jtsiros for triage (I'm already on it, but may be worth reporting on)

**Comment by celiala** [comment]
(since this is already scheduled to close, closing now to unblock exalate sync)
