### ISSUE TITLE
sql: tables with an interleaved child cannot be DROPed without CASCADE

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#8036]
Given

```
CREATE TABLE t1 (i INT PRIMARY KEY)
CREATE TABLE t2 (i INT, s STRING, PRIMARY KEY(i, s)) INTERLEAVE IN PARENT t1
```

Then `DROP TABLE t1` will not (yet) work but `DROP TABLE t1 CASCADE` will.

There is some trickiness to doing this and it doesn't seem particularly necessary, so I'm going to leave it (but link this issue in the error) until there's sufficient interest. Please weigh in on this issue if this is affecting you.

```
// TODO(dan): It's possible to DROP a table that has a child interleave, but
// some loose ends would have to be addresssed. The zone would have to be
// kept and deleted when the last table in it is removed. Also, the dropped
// table's descriptor would have to be kept around in some Dropped but
// non-public state for referential integrity of the `InterleaveDescriptor`
// pointers.
```

**Comment by jordanlewis** [comment]
This doesn't really seem like a `ux-surprise` to me - so removing that label.  It makes sense to me that you'd not be able to delete a parent table without `CASCADE` - there's an explicit relationship from the child and the parent! And `CASCADE` is designed to permit drops through those relationships.

**Comment by awoods187** [comment]
Top requested telemetry feature

**Comment by jordanlewis** [comment]
What do you mean by "Top requested telemetry feature"?

**Comment by jordanlewis** [comment]
@awoods187 unless you can justify that I'm going to close this as wont fix, it doesn't seem important to me.
