### ISSUE TITLE
cli: include probe_range in debug.zip

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#80360]
**Is your feature request related to a problem? Please describe.**

PR #79546 introduces `crdb_internal.probe_range`, but it won't be available during troubleshooting sessions unless included in a `debug.zip`.

**Describe the solution you'd like**

Include a query such as

```
SELECT count(1) FROM crdb_internal.probe_ranges(INTERVAL ‘1000ms’, ‘write’) WHERE error != '' ORDER BY end_to_end_latency DESC LIMIT 100;
```

(the `LIMIT` gives a very approximately ~1000ms*100 target on how long this can
take, so that running `debug.zip` against an unavailable cluster won't take too
long)

**Describe alternatives you've considered**

**Additional context**

Jira issue: CRDB-15754

**Comment by joshimhoff** [comment]
Some thoughts on this, after experimenting a bit re: availability of these tables in different outage scenarios:

- Perhaps we should probe critical system ranges first, as if those are unavailable, we really want to know.
- Perhaps we should do a combo of read & write probing. Write probing is more comprehensive, but read probing is cheaper, so doing both can lead to greater coverage of ranges (even if some only are read probed).
- Perhaps we want to include e2e latency,  traces, etc. 
- Perhaps we want to include e2e latency,  traces, etc. even in cases of no error
- If we turned on always-on probing by default (like we do in CC), we could do fancy stuff like slurping up the logs + prioritizing re-probing ranges that had recent failures
- Perhaps we want to probe in batches on 100, with some parallelization, etc. (need to be careful to not overload cluster obvi)

Obvi perfect should not be the enemy of good here.

**Comment by j82w** [comment]
@tbg did you mean for the query to be the following? Just showing a count doesn't seem to be useful. 
`SELECT * FROM crdb_internal.probe_ranges(INTERVAL '1000ms', 'write') ORDER BY end_to_end_latency_ms DESC LIMIT 100;`

**Comment by joshimhoff** [comment]
@tbg is away for a year, but yes, I think you are right that we need a query like the one you have written out.
