### ISSUE TITLE
build: pre-built c-deps archives cause build failures on linux

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#80389]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

Building on Linux after e0e302f817c8dd8f22ff2fb497a5ead16be67a68 fails with the following

```shell
$ ./dev generate --debug
DEBUG: /home/nickt/Development/go/src/github.com/cockroachdb/cockroach/build/bazelutil/bazel-generate.sh
Skipping //pkg/cmd/mirror (relevant files are unchanged from upstream).
Skipping //pkg/cmd/generate-staticcheck (relevant files are unchanged from upstream).
INFO: Invocation ID: cf866149-7f8e-4367-bd70-2b7fb9bb9407
INFO: Analyzed target //:gazelle (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:gazelle up-to-date:
  _bazel/bin/gazelle-runner.bash
  _bazel/bin/gazelle
INFO: Elapsed time: 0.511s, Critical Path: 0.21s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Skipping //pkg/gen/genbzl (relevant files are unchanged from upstream).
Skipping //pkg/cmd/generate-test-suites (relevant files are unchanged from upstream).
DEBUG: bazel run //pkg/gen
INFO: Invocation ID: 96e46b81-94c3-482e-8144-d93de327a99a
INFO: Analyzed target //pkg/gen:gen (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/nickt/Development/go/src/github.com/cockroachdb/cockroach/pkg/ccl/gssapiccl/BUILD.bazel:4:11: GoCompilePkg pkg/ccl/gssapiccl/gssapiccl.a failed: (Exit 1): builder failed: error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -tags bazel,gss,bazel,gss -src pkg/ccl/gssapiccl/gssapi.go -src ... (remaining 45 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/archived_cdep_libkrb5_linux/lib/libkrb5.a(dnsglue.o):dnsglue.c:function krb5int_dns_init: error: undefined reference to '__res_nsearch'
collect2: error: ld returned 1 exit status
compilepkg: error running subcommand /usr/bin/gcc: exit status 1
Target //pkg/gen:gen failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.517s, Critical Path: 0.24s
INFO: 10 processes: 4 remote cache hit, 6 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
ERROR: generating target //pkg/gen: exit status 1
```

Running the raw bazel command in verbose mode I see the following:

```console
$ bazel run //pkg/gen --sandbox_debug --verbose_failures
...
external/archived_cdep_libkrb5_linux/lib/libkrb5.a(dnsglue.o):dnsglue.c:function krb5int_dns_init: error: undefined reference to '__res_nsearch'
collect2: error: ld returned 1 exit status
compilepkg: error running subcommand /usr/bin/gcc: exit status 1
1650644918.871170108: src/main/tools/linux-sandbox-pid1.cc:498: wait returned pid=2, status=0x100
1650644918.871181252: src/main/tools/linux-sandbox-pid1.cc:516: child exited normally with code 1
1650644918.871559385: src/main/tools/linux-sandbox.cc:233: child exited normally with code 1
Target //pkg/gen:gen failed to build
INFO: Elapsed time: 0.569s, Critical Path: 0.24s
INFO: 10 processes: 2 remote cache hit, 8 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

**Expected behavior**

Building on Linux should succeed.

**Environment:**

```shell
$ uname -a
Linux nickt-XPS-15-9510 5.15.0-25-generic #25-Ubuntu SMP Wed Mar 30 15:54:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Additional context**

The workaround stated in the original commit works, though it does result in recompiling.

Epic CRDB-8036

Jira issue: CRDB-15735

**Comment by rickystewart** [comment]
I can reproduce this with an Ubuntu 22.04 machine. The problem reproduces only with `--config dev` and not `--config crosslinux`.

**Comment by pcarinhas** [comment]
I get this on Debian 12 

>  ./dev build short
> $ bazel build //pkg/cmd/cockroach-short:cockroach-short
> Starting local Bazel server and connecting to it...
> INFO: Invocation ID: 9d6212dd-ced4-4325-82b1-198ee3a54275
> INFO: Analyzed target //pkg/cmd/cockroach-short:cockroach-short (2099 packages loaded, 31898 targets configured).
> INFO: Found 1 target...
> ERROR: /tmp/cockroach/pkg/ccl/gssapiccl/BUILD.bazel:4:11: GoCompilePkg pkg/ccl/gssapiccl/gssapiccl.a failed: (Exit 1): builder failed: error executing command (from target //pkg/ccl/gssapiccl:gssapiccl) bazel-out/k8-opt-exec-2B5CBBC6/bin/external/go_sdk/builder_reset/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -tags bazel,gss,bazel,gss -src pkg/ccl/gssapiccl/get_user.go -src ... (remaining 77 arguments skipped)
> 
> Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
> /usr/bin/ld.gold: error: cannot find -lresolv_wrapper
> /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/3/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-dbg/bin/c-deps/libkrb5_foreign.build_tmpdir/src/lib/krb5/os/dnsglue.c:156: error: undefined reference to '__res_nsearch'
> collect2: error: ld returned 1 exit status
> compilepkg: error running subcommand /usr/bin/gcc: exit status 1
> Target //pkg/cmd/cockroach-short:cockroach-short failed to build
> Use --verbose_failures to see the command lines of failed build steps.
> ERROR: /tmp/cockroach/pkg/cmd/cockroach-short/BUILD.bazel:14:10 GoCompilePkg pkg/cmd/cockroach-short/cockroach-short.a failed: (Exit 1): builder failed: error executing command (from target //pkg/ccl/gssapiccl:gssapiccl) bazel-out/k8-opt-exec-2B5CBBC6/bin/external/go_sdk/builder_reset/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -tags bazel,gss,bazel,gss -src pkg/ccl/gssapiccl/get_user.go -src ... (remaining 77 arguments skipped)
> 
> Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
> INFO: Elapsed time: 1254.808s, Critical Path: 421.40s
> INFO: 4071 processes: 294 internal, 3777 linux-sandbox.
> INFO: Build Event Protocol files produced successfully.
> FAILED: Build did NOT complete successfully
> ERROR: exit status 1

**Comment by andreimatei** [comment]
Dupe of https://github.com/cockroachdb/cockroach/issues/80389 ?

**Comment by theloneexplorerquest** [comment]
I got it fixed with `sudo apt install libresolv-wrapper` on Ubuntu 22

**Comment by mrn3088** [comment]
> I got it fixed with `sudo apt install libresolv-wrapper` on Ubuntu 22

Thank you so much. Worked for me as well!

**Comment by lopezator** [comment]
Didn't worked in my case, even installing libresolv-wrapper.

**Comment by ArkadySkv** [comment]
It's all working under Ubuntu 24.04 machine 

1) lsb_release -a 
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.2 LTS
Release:        24.04
Codename:       noble
2) sudo apt search libresolv-wrapper
Sorting... Done
Full Text Search... Done
libresolv-wrapper/noble,now 1.1.8-2 amd64 [installed]
  wrapper for DNS name resolving or DNS faking
