### ISSUE TITLE
can not restore DB, eventhough the existing database already deleted

### ISSUE THREAD

**Issue by wahyueko22** [cockroachdb/cockroach#80440]
SQL Error [XXUUU]: ERROR: full cluster restore can only be run on a cluster with no tables or databases but found 61 descriptors: [companies users favorite_products shipping_addresses seller_applications seller_application_logs seller_application_attachments payment_settings product_types product_images variants admin shopify_api_authentications products product_vendors files_log tags warehouses transaction_invoice transaction_logs workflow_approval business_type product_tags charge_types charges faq_category odoo_user charge_logs product_logs retailer_transaction_per_variants retailer_transaction_per_users retailer_transaction_per_sellers retailer_transaction_per_products faq_pic general_settings mega_menus faq_question variant_margins variants_location locations variant_stock_logs general_values odoo_error_log discount_codes shopify visitor_events visitors visitor_pages product_shopify user_flags shipping_rates users zones settings ui jobs locations role_members comments role_options scheduled_jobs][](url)
![image](https://user-images.githubusercontent.com/21212141/164888451-fed656a7-63a6-4d74-ae29-3c6f36f336b0.png)

Jira issue: CRDB-15611

**Comment by msbutler** [comment]
Hi @[wahyueko22](https://github.com/wahyueko22), try issuing the RESTORE command after those dropped descriptors are garbage collected. By default, the descriptors will get gc'd 25 hours after they were dropped. You could also speed the gc process up by lowering the gc ttl of the cluster-- see more info on that [here](https://www.cockroachlabs.com/docs/stable/configure-replication-zones.html#replication-zone-variables).

**Comment by smcvey** [comment]
Alternatively, you can restore databases individually: `RESTORE DATABASE <database> FROM ...`.
