### ISSUE TITLE
changefeeds,  ui: changefeed status is not reported in db console when there's a checkpoint

### ISSUE THREAD

**Issue by dhartunian** [cockroachdb/cockroach#80496]
Currently, when a changefeed row contains a "high watermark", its status isn't reported separately in the DB console under the "status" column because it's assumed that the checkpoint is what's important.

Goal: the changefeed view should show BOTH the current status of the job and a high watermark *if* it's available to provide a complete picture of the job in the DB Console and match the view in SQL.

Jira issue: CRDB-15592

**Comment by amruss** [comment]
Moving this to the jobs board for discussion around the best way to communicate protection/ other important data for jobs

**Comment by dhartunian** [comment]
@amruss I think I didn't correctly convey how the code works today. If the job contains a "highwater_timestamp" field the status column will **never** show a status like "running"/"paused" etc. no matter how often it updates. So the changefeed jobs end up looking confusing in the table.

I think making it look more like the SQL output will help. Here's an example that always renders the status column for every job including changefeeds and adds a highwater timestamp column for changefeed jobs:
![Screenshot 2022-05-12 at 11-23-33 Jobs Cockroach Console](https://user-images.githubusercontent.com/986307/168111221-0f1ce9f7-a80e-414c-b7bb-b902235c4c7a.png)

I agree that "Running" status is low-info for a changefeed so if you think it makes sense we can also just show the highwater timestamp when its in running status and avoid the extra column.

Also a small example of moving the highwater timestamp to the sidebar for job details
![Screenshot 2022-05-12 at 11-23-45 Details Job Cockroach Console](https://user-images.githubusercontent.com/986307/168111796-fb1a57a5-b7ab-4086-8dda-0e5ed187fa2e.png)
