### ISSUE TITLE
The retention of persisted statistics should be time-based versus row-based

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#80523]
In 21.2 we introduced persisted statistics which has a row-based retention period of 10M rows. It is difficult for users to understand how far back their workload statistics is captured. It's entirely based on the shape of their workload and how many diverse fingerprints they have in their workload. We should improve the experience by making the retention period time-based. We've seen a few troubleshooting scenarios where 7 days would also be required - 3 days at a minimum. 

Additional context from https://github.com/cockroachdb/cockroach/issues/89454
Currently, the only scenario we delete sql stats from the system table (other than initiating a reset) is when we reach the row limit set by sql.stats.persisted_rows.max, at which point we evict entries based on aggregation (oldest entries first). We should investigate whether or not we would like to change this retention to be based on a time period (along with a hard limit). This could potentially reduce the amount of storage used by the system tables.

This could also help reduce the issues described https://github.com/cockroachdb/cockroach/issues/89452, assuming the amount of stats collected within the time period is much less than the hard cap.

Jira issue: CRDB-15588

**Comment by maryliag** [comment]
No longer a priority
