### ISSUE TITLE
teamcity: acceptance artifacts are lost

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#8054]
https://teamcity.cockroachdb.com/viewLog.html?buildId=5093&buildTypeId=Cockroach_UnitTests&tab=artifacts

They (at least in the circle setup) go to `${CIRCLE_ARTIFACTS}/acceptance`. Perhaps all it needs is setting that env variable correctly? I could probably poke around here, but @jordanlewis probably has a better idea of what the right solution is (and what templates it needs to go to).

**Comment by jordanlewis** [comment]
@tschottdorf They're actually not lost. You're looking at the top-level job (called GitHub CI in the UI) that triggers the actual test jobs. If you click the Dependencies tab in the link you sent, you can navigate to the run of the acceptance tests that this job triggered - and from there you can get to the artifacts.

**Comment by tschottdorf** [comment]
Was going to write "duh", but then I realized that from

https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_UnitTests

<img width="742" alt="screen shot 2016-07-27 at 9 54 31 am" src="https://cloud.githubusercontent.com/assets/5076964/17177636/6028b2f8-53e0-11e6-9b99-227c41dc820b.png">

I actually clicked on the test name but the resulting page still isn't where I think it would be.

That navigation is pretty unintuitive, but I guess we're all capable of learning (and more importantly, it's not like we can change anything there). Thanks for the pointers.

**Comment by jordanlewis** [comment]
Yeah, I see what you mean - you need to click once to see the failed Snapshot dependencies, and then once again to see whatever failing subjob you're interested in. Not ideal, but yeah, I'm not really sure how we can do better besides having the top level job copy in all of the dependencies or something which I'm not really inclined to do.
