### ISSUE TITLE
sql: DEALLOCATE should work in poisoned transaction

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#8061]
The C++ ORM ODB expects* to be able to deallocate a prepared statement in a failing transaction. Note that the client library in use transforms the PREPARE command into a pgwire-level prepare message, but the DEALLOCATE command is sent as a string. 

```
BEGIN;
PREPARE query AS SELECT * FROM my_table WHERE id = $1;
EXECUTE (query, ‘my_id’);  —> Imagine this fails due to serialization and returns an error
DEALLOCATE query; —> This should still work.
ROLLBACK;
BEGIN;
PREPARE query as SELECT value FROM my_other_table; <— This should work. In the current version this complains with “prepared statement name already exists"
```

\* Postgres also rejects the DEALLOCATE statement in a failing transaction, so ODB has now [worked around](http://scm.codesynthesis.com/?p=odb/libodb-pgsql.git;a=commit;h=231d0222fb75c448321677d258ed59da98eec7ee) this (and therefore fixing this is a low priority). However, it still makes sense to allow DEALLOCATE here because prepared statements are independent of the transaction.

**Comment by tamird** [comment]
Can you also include the current behaviour, i.e what CockroachDB does today?

**Comment by bdarnell** [comment]
It's the "transaction aborted; ignoring commands until rollback" error.

**Comment by petermattis** [comment]
Should be straightforward to fix this.

**Comment by nvanbenschoten** [comment]
It sounds like we want a limited set of statement types to be executed independently of the state of their current transaction. That seems reasonable, but I'm curious how we want to make this distinction. Should this set be:
- limited to `DEALLOCATE` statements
- limited to `DEALLOCATE` and `PREPARE` statements
- limited to session-management related statements (`DEALLOCATE`, `PREPARE`, `SET`, etc.)
- some other group

I do have a slight reservation that without making this distinction clear, what will and what wont be executed in the context of a failed transaction could become very obscure to users. I can also see valid cases where transactions might be written specifically such that session-related changes only happen if their parent transaction succeeds.

**Comment by bdarnell** [comment]
My instinct says option 3 (everything session-related), but first we should do some experimentation to see what postgres does.

**Comment by nvanbenschoten** [comment]
Postgres will return `current transaction is aborted, commands ignored until end of transaction block` regardless of the statement type if executed in a failed transaction. Alternatively, MySQL will allow all statements to continue even if executed in a statement with other failed statements.

It looks like there's very little precedence for the rule we want to make here.

**Comment by bdarnell** [comment]
Hmm. The ODB user I was talking to said that this works on postgres. Maybe it's broken there too but no one noticed because connection restarts are more common for us?

**Comment by nvanbenschoten** [comment]
Didn't you say this didn't work on postgres in the initial issue (`Postgres also rejects the DEALLOCATE statement in a failing transaction...`)? Am I missing something?

**Comment by bdarnell** [comment]
Hmm, so i did. Nevermind then.

**Comment by nvanbenschoten** [comment]
I do agree that option 3 is the cleanest solution, and the one that will be least surprising to users, other than perhaps keeping the current behavior and saying "that's what PG does". I'll mock out an implementation of it and see if I'm missing anything obvious that the new behavior would break.

**Comment by nvanbenschoten** [comment]
It seems like special handling for session-statements creates an ambiguity about what effect a failure of one of these statements should have if executed within a transaction. We're saying that a failed transaction shouldn't impede session-stmts from executing, but should a failed session-stmt stop the rest of the transaction from executing. I would think yes, because if a user is running one of these statements in a transaction (eg. `SET TIME ZONE`), the transaction is probably only valid if this succeeds.

I'm starting to wonder if this split between session-statements and normal statements is worth it, because not only does it complicate transaction logic, but it also opens the door for a lot of uncertainty.

**Comment by spencerkimball** [comment]
@bdarnell, @nvanbenschoten after reading the details of this issue, I'm going to close it. We currently do what Postgres does, ODB currently works around this, and as @nvanbenschoten pointed out, trying to get fancy just causes additional uncertainty.

If someone disagrees, please re-open. If you believe it should be 1.0, don't fail to assign it to someone who is committed to getting the work done this month.
