### ISSUE TITLE
Update the tool tip and our documentation to clearly call out the definition of session statuses

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#80657]
In 22.1 we introduced the concept of a session status which can be active, idle, or closed. We should be explicit and clear to users as to what they mean. 

Currently, the tool tip states that "a session is active if it has an open transaction (including implicit transactions, which are individual SQL statements), and idle if it has no open transaction."

We should update the tool tip to state, "A session is active if it has an open explicit or implicit transaction (individual SQL statement) with a statement that is actively running or waiting to acquire a lock. A session is idle if it has no open transactions."

**Comment by kevin-v-ngo** [comment]
@gtr can you confirm the definition of an active session we have here? @stbof, can you do a quick review as well? Thank you!

**Comment by stbof** [comment]
LGTM.

**Comment by gtr** [comment]
Thanks for filing the issue! This definition looks good to me.
