### ISSUE TITLE
admission control: set QoS based on session variables

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#80708]
**Is your feature request related to a problem? Please describe.**

Setting QoS based on `application_name` for example

**Describe the solution you'd like**

Controlling sessions coming with a specific session variable via QoS would offer a lot of flexibility.

**Comment by rytaft** [comment]
@dbist can you give some more details about what you're asking? How do you imagine a user would interact with this feature?

**Comment by rytaft** [comment]
(Note that it is already possible to set the QoS with a session setting in 22.1 -- `default_transaction_quality_of_service`)

**Comment by dbist** [comment]
I think for the first go-round this is sufficient. I was not aware of the session variable existence. I imagine as users start leveraging this capability we can expand on the scenarios that extend beyond the basics. We can close this @rytaft if necessary. Thank you

**Comment by rytaft** [comment]
Sounds good - thanks! Closing.
