### ISSUE TITLE
enhance cockroach sql command to direct execution time output to stdout 

### ISSUE THREAD

**Issue by fabiog1901** [cockroachdb/cockroach#80701]
How can I save to file the time it took to execute?

```
$ ./cockroach sql --url='postgres://root@localhost:26257/gts?sslcert=...' -e "select count(*) from equity_orders;"
   count
-----------
  7414450
(1 row)


Time: 1.268s
```

Here I try to redirect both stdout and stderr to a file, but unfortunately the execution time is not saved.

```
$ ./cockroach sql --url='postgres://root@localhost:26257/gts?sslcert=...' -e "select count(*) from equity_orders;" > allout.txt 2>&1

$ cat allout.txt 
count
7414450
```

The time is not saved to file. How can I do that, pls?

[Slack conversation](https://cockroachlabs.slack.com/archives/C04U1BTF8/p1649699016127969)

Jira issue: CRDB-15543

**Comment by smcvey** [comment]
We could probably close this.  Turns out, you can `\set show_times=true` and it puts the time to stdout.

**Comment by rafiss** [comment]
That's right:
```
❯ ./cockroach sql --insecure -e '\set show_times=true' -e 'select 1' > output.log

❯ cat output.log
?column?
1


Time: 0ms
```
