### ISSUE TITLE
builtins(geo): implement Box2D() alias to postgis_getbbox

### ISSUE THREAD

**Issue by fredbi** [cockroachdb/cockroach#80716]
**Is your feature request related to a problem? Please describe.**
Our Postgres app may use the [Box2D(geometry)](https://postgis.net/docs/Box2D.html) -> box2D PostGIS function and this is not supported by cockroachDB.

**Describe the solution you'd like**
Have Box2D(geometry)-> box2d as an alias to the existing postgis_getbbox(geometry) -> box2d function.

**Describe alternatives you've considered**
We inspect our app and change every occurrence of Box2D() by postgis_getbox().
This is annoying because we want to gradually release our cockroach config and thus have to maintain a build tag with or without cockroachDB.

**Additional context**
The fix seems pretty much straightforward using the built-in aliasing mechanism, but I wonder if there is a name conflict between the function name (box2d) and the type name (box2d), which could explain why we have had "postgis_getbbox" in the first place.

Edit: I've tried declaring an alias to postgis_getbox, but the parser doesn't catch the context and the name conflict flares a syntax error (whereas trick works with a non-conflicting name such as "box2dx"). So it seems to be non-trivial.

Jira issue: CRDB-15538

**Comment by fredbi** [comment]
@otan as I've mentioned in the issue description, I am no longer sure it is low-hanging fruit (aka "good first issue").

After having declared an alias to the postgis_getbbox builtin, I get this error. This necessarily comes from parsing, because doing
exactly the same thing with an alias like "box2dx()" works like a charm.

Since the workaround is not too painful, and the remedy seems (to my eyes) a bit complex, I would understand if you decide to punt on that one. The postgis API is so messy, I would agree that porting it 100% is not even desirable.... :)

```
            --- FAIL: TestLogic/local/geospatial_bbox/getbbox_and_alias (0.00s)
                logic.go:3453: 
                    
                    /home/fred/src/github.com/cockroachdb/cockroach/pkg/sql/logictest/testdata/logic_test/geospatial_bbox:280: SELECT
                      postgis_getbbox(g),
                      box2d(g)
                    FROM ( VALUES
                      ('POLYGON ((0 0, 1 0, 1 1, 0 0))'::geometry)
                    ) tbl(g)
                    expected success, but found
                    (42601) at or near "(": syntax error
                    lexer.go:251: in Error()
                    DETAIL: source SQL:
                    SELECT
                      postgis_getbbox(g),
                      box2d(g)
                           ^
                logic.go:3164: 
                     pq: at or near "(": syntax error
```

**Comment by otan** [comment]
ah this is because the parser thinks its a type. that's blocked by #56492
