### ISSUE TITLE
DB Console: version label goes blank when nodes are in mixed version states like during an upgrade

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#80729]
**Describe the problem**

When a cluster is in a mixed version state, the cluster version label at the header of the DB Console goes blank. 

For example, say a cluster is in the process of upgrading from `21.2` to `22.1`. During that process, the cluster version label goes blank. 

The DB Console should instead display a clearer label to indicate the cluster is in a mixed version. Some ideas include:
* Keeping the label as `21.2` until the the upgrade process is finalized and all nodes are in `22.1` (but unclear if we have a mechanism to know that)
* Display both `21.2` and `22.1` labels (this is the most explicit option, my preferred option)
* Note in the label that cluster is in a `Mixed Version` state, or something along those lines

cc @smcvey based on Slack discussion

Jira issue: CRDB-15531

**Comment by thtruo** [comment]
This seems related to https://github.com/cockroachdb/cockroach/pull/76932

**Comment by thtruo** [comment]
cc @Annebirzin curious to get your take on which of the listed ideas you think provides the right UX balance.

**Comment by Annebirzin** [comment]
@thtruo I think the 3rd option seems most clear. Maybe the label could continue to have the old version with an indication of the mixed version state: `21.2 - Mixed Versions`

**Comment by thtruo** [comment]
Ack, appreciate your input @Annebirzin 
That works for me too - anything is better than the status quo today. This looks like a nice tiny win we can add to KV Obs' plate
