### ISSUE TITLE
server: APIv2 HTTP interface missing for SQL-only servers

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#80789]
The HTTP APIv2 tree is only active for mixed KV/SQL nodes, and not for SQL-only servers.

There is no good reason for this since the behavior would be properly defined for both.

Initiative: INI-214

Jira issue: CRDB-15512

Epic CRDB-17356

**Comment by dhartunian** [comment]
This was done via https://github.com/cockroachdb/cockroach/pull/92751
