### ISSUE TITLE
sql: TestCancelMultipleQueued failed

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#80782]
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_GitHubCiOptional/5045803?showRootCauses=true&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

```
=== RUN   TestCancelMultipleQueued
    test_log_scope.go:79: test logs captured to: /artifacts/tmp/_tmp/888a8dc2b874419d6d44969e95f0a12a/logTestCancelMultipleQueued2719050401
    test_log_scope.go:80: use -show-logs to present logs inline
    schema_changer_test.go:6695:
          Error Trace:  schema_changer_test.go:6695
          Error:        Invalid integer or value
          Test:         TestCancelMultipleQueued
          Messages:     Error: %!s(<nil>) Val: 1
    panic.go:642: -- test log scope end --
--- FAIL: TestCancelMultipleQueued (10.33s)
```

https://github.com/cockroachdb/cockroach/blob/924fed7571d62aba9cbccc3eec9f254e8f05c510/pkg/sql/schema_changer_test.go#L6694-L6696

I'm skipping this test.

**Comment by srosenberg** [comment]
<img width="1549" alt="TestCancelMultipleQueued_stats" src="https://user-images.githubusercontent.com/1616764/165971040-309cd4f0-8c9c-43e1-bcf7-6c8523e1bff3.png">
