### ISSUE TITLE
importer\schema: TestRandomParquetExports times out because DROP hangs on dropping a column with a `NOT NULL` constraint

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#80780]
Timed out in https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_Test/5045833?buildTab=artifacts#%2FlogTestTenantStatementTimeoutAdmissionQueueCancelation2792678984;%2FlogTestRandomParquetExports25044431 and that PR (#80744) didn't do anything but skip another test.

[importertest.log.txt](https://github.com/cockroachdb/cockroach/files/8590216/importertest.log.txt)

I think the salient bit is that we see a job that can't roll back (or forward I guess) because of

```
Wraps: (4) unable to encode table key: <nil>
```

and I would guess that the test waits for that job to either succeed or fail.

I'm skipping this test.

Jira issue: CRDB-15515

**Comment by ajwerner** [comment]
This is a symptom, I believe, of https://github.com/cockroachdb/cockroach/issues/81698. 

We see that we fail to encode the primary key entry and that column ID 3 is not null and computed and in the primary index as a key column.
