### ISSUE TITLE
ui: Raft debug page times out when loading data

### ISSUE THREAD

**Issue by d4l3k** [cockroachdb/cockroach#8079]
When the cluster is running slowly sometimes the `/_status/raft` endpoint takes longer than 10s. The recently added 10s timeout on fetching data means that the raft debug page never actually loads, despite the request eventually completing.

Timeout was introduced in https://github.com/cockroachdb/cockroach/commit/e55ca2fcde872b6f937fbb3c9690e35f363a9d20

https://beta.gce.cockroachdb.com:8080/#/raft/ranges?_k=7yn0my

**Comment by bdarnell** [comment]
Ping. This page is basically unusable on large clusters. We need to A) show some indication that the page is loading and an error if it fails, B) allow this page to take longer than 10 seconds, and C) make it not be so slow.
