### ISSUE TITLE
SHOW CREATE for materialized views returns incorrect DDL

### ISSUE THREAD

**Issue by TheodoorP** [cockroachdb/cockroach#80829]
**Describe the problem**
When trying to use `SHOW CREATE` on a materialized view, the generated DDL is no longer a materialized view but a normal view, and the internal rowid column is part of the column definition.

**To Reproduce**
1. Create a materialized view:
```sql
CREATE MATERIALIZED VIEW test AS (SELECT 1 AS foo);
```
2. Use `SHOW CREATE`:
```sql
SHOW CREATE test
```
3. See that the DDL is no longer a materialized view and that the rowid column is now included.

**Expected behavior**
I would expect the DDL to create a materialized view without a rowid.

**Additional data / screenshots**
![image](https://user-images.githubusercontent.com/17050455/166113077-17c22448-2f64-472c-88ab-04a63e223783.png)

**Environment:**
 - CockroachDB version: 21.2.8
 - Server OS: any
 - Client app: any

Jira issue: CRDB-15494

**Comment by msbutler** [comment]
@TheodoorP thanks for filing! This is probably a bug (or a docs issue), also apparent on master. 

Per CRDB [docs](https://www.cockroachlabs.com/docs/v21.2/indexes#creation):

> In CockroachDB, every table requires a primary key. If one is not explicitly defined, a column called rowid of the type INT is added automatically as the primary key, with the unique_rowid() function used to ensure that new rows always default to unique rowid values.

`SHOW CREATE` on a regular table never shows the `rowId` so I don't think `SHOW CREATE` should return `rowId` for views either.

**Comment by TheodoorP** [comment]
@msbutler based on your reply I would assume that the DDL using `CREATE VIEW` instead of `CREATE MATERIALIZED VIEW` is a separate bug? If so I'll open a separate issue for that.

**Comment by msbutler** [comment]
@TheodoorP ah, that was a typo. This is only apparent for materialized views.

**Comment by mehrankamal** [comment]
Hi @rafiss , I would like to take up this issue. Can you please give me some pointers to begin with. Cuz I'm kinda new to opensource and CockroachDB apparently.
