### ISSUE TITLE
sql, cli: log technical advisories for current version on startup

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#80862]
Suggested here: https://twitter.com/kellabyte/status/1519750285090033667

Nodes should hit a hardcoded external endpoint once in the course of joining a cluster that gives any [technical advisories](https://www.cockroachlabs.com/docs/advisories/index.html) applicable to the node's version, and log the result, if any, on their error channel. For bonus points, this could be a JSON response to an existing telemetry call, so that we're not adding any new external traffic and users who have disabled telemetry and probably also don't want this to happen don't have to disable it separately.

Not my idea, but it appeals to me since we rarely knowingly release a binary with a TA-level issue, so the only way to alert users to a serious bug is to have the node phone home.

Jira issue: CRDB-15479

**Comment by rafiss** [comment]
I think this is more of a Product question. The original issue proposes a specific solution, but I think there's lots of different ways we could tackle the problem of needing to notify users about TAs.
