### ISSUE TITLE
sql,cluster-ui: invalid transaction time for simple transaction

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#80869]
**Describe the problem**

<img width="1620" alt="Screen Shot 2022-05-02 at 9 59 36 AM" src="https://user-images.githubusercontent.com/1839234/166246648-b3f6dde8-8cbf-43a8-940f-25149309364d.png">

**To Reproduce**
I'm not sure. I ran 7a9eb906ce and looked at the slowest transaction in the console.

Jira issue: CRDB-15473

**Comment by maryliag** [comment]
Closing, duplicated on https://github.com/cockroachdb/cockroach/issues/82894
