### ISSUE TITLE
cloud: run ExternalStorage unit tests on private teamcity agents 

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#80877]
`pkg/cloud` has all their tests skipped on CI for security reasons. We should run this package as a nightly config on private teamcity agents. Ideally, we'd run these prior to a PR merging but the next best option is to run these tests nightly for increased coverage.

Jira issue: CRDB-15469

**Comment by livlobo** [comment]
@adityamaru  - looks live you've added GCP tests to run nightly. Can this be closed?

**Comment by adityamaru** [comment]
We still have to do the work to support Azure and S3 tests, so I think we should keep this open until that is done.
