### ISSUE TITLE
sql/drop_index: duplicated schema change job description for DROP INDEX

### ISSUE THREAD

**Issue by Xiang-Gu** [cockroachdb/cockroach#80889]
If `DROP INDEX idx` requires us to also drop a column (as in the case of dropping an expression index or dropping a shared index), the schema change job description is slightly off:

```
CREATE TABLE tbl (a string);
CREATE INDEX expr_idx ON tbl(lower(a));
DROP INDEX expr_idx;
SELECT job_id, description FROM [show jobs] ORDER BY created DESC LIMIT 2;
```

gives us 

```
       job_id       |                                   description
---------------------+----------------------------------------------------------------------------------
  758436656643145729 | GC for DROP INDEX defaultdb.public.tbl@idx; DROP INDEX defaultdb.public.tbl@idx
  758436654120108033 | DROP INDEX defaultdb.public.tbl@idx; DROP INDEX defaultdb.public.tbl@idx
```

The root cause is the following:

https://github.com/cockroachdb/cockroach/blob/f4db23063d12529877622502a8f72e9e51bda119/pkg/sql/drop_index.go#L177-L181

in which `finalizeDropColumn` will attempt to create a schema change job that already exists. Then it will update the existing job by appending the job description, resulting in the duplicated description message.

https://github.com/cockroachdb/cockroach/blob/f4db23063d12529877622502a8f72e9e51bda119/pkg/sql/table.go#L219-L220

Jira issue: CRDB-15465

**Comment by lkyuchukov** [comment]
@Xiang-Gu can we just check if the `jobDesc` matches `record.Description` and not append it if it does?

**Comment by Xiang-Gu** [comment]
@lkyuchukov yes, that should suffice.
