### ISSUE TITLE
tests: improve handling of intermittent GCE instance stalls

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#8090]
After some investigation, it looks like there are stalls on the GCE-based nodes that we're creating for our nightly remote acceptance tests. This causes some tests to fail a little cryptically. The symptoms are:

* A mysterious `exit status 255` from the `Terrafarm` code.
* If you SSH into the cluster after the failure (after setting the flag `tf.keep-cluster=failed`) using the *Google Cloud browser-based SSH client*, the first one or two attempts at connecting may fail. The client seems to perform up to 3 tries.
* SSH sessions to the boxes are very slow (> 10 seconds to connect). Even when connected, commands such as `supervisor status` take much longer than usual. A cursory look at `top` reveals 50-90% of the total time is spent waiting on disk.

We're encountering intermittent failures on at least two different tests:

* [1->6 allocator test](https://teamcity.cockroachdb.com/viewLog.html?buildId=5611&buildTypeId=Cockroach_Nightlies_AllocatorTest1to6_108g&tab=buildLog)
* [block_writer load test](https://teamcity.cockroachdb.com/viewLog.html?buildId=5536&buildTypeId=C_BW_4Nodes_6Hours&tab=buildLog)

Some possible fixes are:
* Switching to SSD-based storage for our test clusters. This will *probably* reduce the severity of I/O-based stalls.
* Adding retries to `(*Terrafarm.Farmer).Assert()`. A little care is needed, because we may run into the `TESTTIMEOUT` if we need to retry for our final health check (which happens near the end of the `TESTTIMEOUT`).

cc @tschottdorf

**Comment by tschottdorf** [comment]
I believe @petermattis mentioned that he suspected that he was throttled on i/o in some of his work. I think that applied to persistent storage, though. Though now that I think of it, we *do* use persistent storage for everything (which is pretty dumb for this type of test cluster):

```
variable "cockroach_disk_type" {
  default = "pd-standard" # can set this to 'pd-ssd' for persistent SSD
}
```

I think we can avoid this issue completely by using only a small persistent standard disk and using another `local-ssd` disk for the data directory. We don't really need the SSD, but I didn't find a local spinny disk in the docs https://www.terraform.io/docs/providers/google/r/compute_instance.html.

**Comment by cuongdo** [comment]
Yeah, I agree. I'll take a look today.

**Comment by petermattis** [comment]
Yep. When running `block_writer` for a sustained period (1-2 hours) I saw what appeared to be I/O throttling. I'm not sure of a good way to determine if this was actually the case. This was using a `pd-ssd` disk. The problem went away after switching to `local-ssd`.

**Comment by tschottdorf** [comment]
cc https://github.com/cockroachdb/docs/issues/506 since the current PetSet example on GCE would probably run into the same problem since it relies on persistent storage.

**Comment by cuongdo** [comment]
I'm testing the switch to local SSDs, and they do indeed remove the performance hiccups.

However, I believe that the increased IOPS tickles the snapshot excessive memory use issue (#8056), because the local SSD makes snapshot generation so much faster. `TestUpreplicate_1To3Small` in particular seems to OOM about halfway through.

Here are memory profiles for the `1To3Small` and `3To5Small` allocator tests running with local SSDs:
[1to3small_heap.pdf](https://github.com/cockroachdb/cockroach/files/388980/1to3small_heap.pdf)
[3to5small_heap.pdf](https://github.com/cockroachdb/cockroach/files/388979/3to5small_heap.pdf)

Admin UI memory graph:
<img width="523" alt="screenshot 2016-07-28 13 24 30" src="https://cloud.githubusercontent.com/assets/1564582/17222670/81af6ac4-54c7-11e6-8239-65a1cc1ebe73.png">

These machines have 16 GB of memory, so they should have enough memory.

**Comment by petermattis** [comment]
Is that memory usage all caused by snapshots? 4 GB is a lot of memory for snapshots.

**Comment by cuongdo** [comment]
Yeah, a lot of that 4 GB points to `(*RaftSnapshotData).Marshal()`.

**Comment by petermattis** [comment]
Well, that would point to snapshots. The profile doesn't show if these are preemptive or normal snapshots. Assuming these are preemptive snapshots, I'm guessing the asynchronous sending of the snapshots is to blame. I believe @tamird was looking into fixing this. Would be good to verify that is the problem and bump up the priority of that work.
