### ISSUE TITLE
storage: improve detection / handling of degraded storage device(s)

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#80942]
Currently, Pebble times all write / sync operations and will emit an event if any individual operation takes [more than 5 seconds](https://github.com/cockroachdb/cockroach/blob/bd43c6ff3726be278bb043502032c8f195d0abfa/pkg/storage/pebble.go#L643) (checking every two seconds). These events are emitted to the Pebble log.

Additionally, Cockroach will (by default) [log and panic](https://github.com/cockroachdb/cockroach/blob/bd43c6ff3726be278bb043502032c8f195d0abfa/pkg/storage/pebble.go#L983-L984) in the case where any single write / sync operation takes longer than some threshold (currently, [the default is 60s](https://github.com/cockroachdb/cockroach/blob/bd43c6ff3726be278bb043502032c8f195d0abfa/pkg/storage/pebble.go#L62-L72)).

This monitoring serves well in the face of a complete disk stall - though there is an open question as to whether the 60s limit could be reduced to get us closer to the 15-20s recovery time that we aim for elsewhere (see [this](https://cockroachlabs.slack.com/archives/CAC6K3SLU/p1651165099153929) internal thread for more context).

However, there is a gap in our handling of "general slowness" at the storage layer. For example, a degraded volume may never result in any one operation being stalled for enough time so as to cause a node crash, but the presence of degraded IO can have knock on effects elsewhere in a cluster. Ideally, we'd be able to detect and recover from these situations expediently.

One idea (from @sumeerbhola, discussed internally, [here](https://cockroachlabs.slack.com/archives/CAC6K3SLU/p1651168700873379?thread_ts=1651165099.153929&cid=CAC6K3SLU)) for handling these degraded states, is to have nodes perform some coordination around which nodes are killed, and when, in the face of degraded disk performance, so as to limit blast radius. A sketch of the idea is thus:

- Nodes make a local decision on when node thinks it is worth killing itself: Separated into "unilateral-kill" vs "coordinated-kill". The current 60s limit can be a unilateral-kill. Something like 5s latency for 30s could be coordinated-kill. Or whatever thresholds we decide.

- Coordination for coordinated-kill: Each node maintains an in-memory vector with a counter per node. When a node i wants to kill itself via coordinated-kill, it broadcasts to all other nodes which increment the v[i] and return the current value of v to node i. There is a jitter, say 0-2s in this broadcast and response. Node i takes the max of the vectors it receives as response. If the number of nodes wanting to do coordinated-kill (or have already done it) is above some threshold, the node resets its kill decision and backs off from making another decision for 60s. The in-memory vectors get reset every 60s.

Jira issue: CRDB-15442

**Comment by erikgrinaker** [comment]
> have nodes perform some coordination around which nodes are killed, and when, in the face of degraded disk performance, so as to limit blast radius

I don't think we need to take this that far. In the medium term, [replica circuit breakers](https://github.com/cockroachdb/cockroach/issues/74712) should resolve this issue without the need for Pebble to panic at all. Currently, every time the node heartbeats, it also does a sync write -- if this sync write hangs for more than 4.5 seconds, the heartbeat is going to fail. This will cause it to lose all leases, and with circuit breakers, to also abort all in-flight RPCs. At that point, the node will not longer be considered part of the cluster.

This also implies that the coordination outlined in this issue is unnecessary -- it is already the case that nodes with faulty disks will fail liveness and be considered unavailable, so avoiding panics is pointless.

We mostly just need this Pebble crash to tide us over until we can fix the circuit breakers, so I don't think we should put a lot of effort into this.

> there is an open question as to whether the 60s limit could be reduced to get us closer to the 15-20s recovery time that we aim for elsewhere

Yeah, dropping this to 20 seconds or something seems like a good idea.

**Comment by nicktrav** [comment]
@erikgrinaker - thoughts on closing this one out now that we landed the 20s timeouts? Seems like the other fixes you mentioned would mitigate impacts in the medium-to-long term.

**Comment by erikgrinaker** [comment]
I suppose there's still an issue with nodes that have degraded performance, e.g. if disk throughput or latency worsens by 50%. In that case, we'd want to shed leases and replicas as appropriate, but it's not clear to me what the best mechanism nor policy for this would be.

Maybe we should keep this open to cover those sorts of scenarios? Not something we'd pick up in the near term though.

**Comment by nicktrav** [comment]
Sounds good. Will keep in our backlog.
