### ISSUE TITLE
sql: resolver incorrectly resolves schema target for `GRANT ... ON ALL TABLES IN SCHEMA ... TO ...`

### ISSUE THREAD

**Issue by Xiang-Gu** [cockroachdb/cockroach#81002]
```
CREATE USER max;
CREATE DATABASE testdb;
CREATE TABLE testdb.public.tbl (a int);
USE defaultdb;
GRANT SELECT ON ALL TABLES IN SCHEMA testdb.public TO max;
```
will attempt to grant a privilege on all tables in a schema in *another* database.

However, 
```
SHOW GRANTS ON TABLE testdb.public.tbl;
```
does not show that we have just granted a privilege on this table `tbl` to user `max`.

Instead, the privilege is granted on all tables in the *current* database (i.e. `defaultdb`), as shown with
```
SHOW GRANTS ON TABLE defaultdb.public.tbl;
```

The root cause is we simplistically use the current database to find all affecting tables

https://github.com/cockroachdb/cockroach/blob/cc155a1efe057be7d9432d160744186059767140/pkg/sql/resolver.go#L599-L604

which disrespects the potentially set database in the schema prefix.

CRDB-14049

**Comment by ajwerner** [comment]
This is probably a @cockroachdb/sql-experience issue, at least for now. It's a great find!

**Comment by ajwerner** [comment]
This bug was introduced at the very beginning of support for this syntax https://github.com/cockroachdb/cockroach/pull/67509. cc @RichardJCai
