### ISSUE TITLE
spanconfig,kv: enable `spanconfig.storage_coalesce_adjacent` by default

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#81008]
**Is your feature request related to a problem? Please describe.**

For 22.2 it’d be great to enable the [pack-tables-into-ranges optimization](https://github.com/cockroachdb/cockroach/pull/79700) for the host tenant by default. A concern around flipping this default is that when clusters upgrade to 22.2, since table boundaries are no longer hard split points, we might see a rapid onset of possible range merges, which would cause rebalancing activity (replicas on both halves of the range merge need to be colocated on the same stores) which isn’t great both networking cost wise, and possibly its affect on foreground latencies.

**Describe the solution you'd like**

Strawman: enable the optimization for freshly created clusters (flipping the default value for `spanconfig.host_coalesce_adjacent.enabled`), and for existing clusters we could disable it. It’s possible to do this through a migration that we’d run on the lead up to 22.2 finalization where we explicitly `SET CLUSTER SETTING spanconfig.host_coalesce_adjacent.enabled = false`). This doesn’t fully answer the question of how we could prevent foreground traffic impact as a result of this setting being toggled, but that seems kind of difficult (and not clear to me how we could do it well). Since this is a hidden cluster setting, maybe that's fine -- you're on your own. If we want to dampen the effects of toggling this thing back and forth, let's do that as a separate thing — maybe using different rate limits for these merges (also splits). Some internal discussion [here](https://cockroachlabs.slack.com/archives/C020NSBH63F/p1651614320343469).

Jira issue: CRDB-15400

**Comment by ajwerner** [comment]
This turns out to be problematic because of console pages which aggregate range data for table sizes. See https://github.com/cockroachdb/cockroach/issues/84105.

**Comment by irfansharif** [comment]
This setting breaks `SHOW RANGES` (and the underlying vtables) (#93617) but that's something @knz has a PR out for: https://github.com/cockroachdb/cockroach/pull/93644.

**Comment by knz** [comment]
Can we also rename it? We don't use the word "host" elsewhere.

**Comment by irfansharif** [comment]
Now that https://github.com/cockroachdb/cockroach/issues/93617 is fixed, I'm only aware of one meaningful blocker for this work (this == enabling coalesced ranges by default for the system tenant). It's https://github.com/cockroachdb/cockroach/issues/84105 which in turn currently blocks https://cockroachlabs.atlassian.net/browse/CRDB-16704 as part of the over-arching https://cockroachlabs.atlassian.net/browse/CRDB-22711. As I understand it, we're working on all of those things as part of our UA work in 23.1. Which makes this (== enabling coalesced ranges by default for the system tenant) to also do in 23.1. There are concerns about upgrades, and them inducing excessive merge queue activity. I'm completely ok with only enabling this setting in clusters that start off in 23.1, leaving existing clusters as is. Also keeping the "uncoalesced" form for clusters that are being restored from 22.2 and earlier images. This is similar in spirit to what we did with lowering the default GC TTL: https://github.com/cockroachdb/cockroach/issues/89233.

I'm especially interested in enabling for the system tenant since it's a relatively long hanging fruit, very meaningfully advances CRDB scalability WRT to the # of schema objects (tables, indexes, partitions) that clusters can run with. We also have direct evidence that this magical, hidden-by-default setting is something POCs have reached for and found utility for. So far they've had to forego `SHOW RANGES` support, or the UI accommodating the notion of coalesced ranges, but neither of things are going to apply shortly.
