### ISSUE TITLE
acceptance: reference test: include legacy writers to tables / indexes created by new binary

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#8102]
currently the "new" binary creates a table and writes to it, but the legacy binary only has to read that table. descriptor changes that affect writing are thus not tested.

**Comment by a6802739** [comment]
@dt ,  if you please give a more concrete explanation, I think maybe I could fix this.

**Comment by dt** [comment]
@a6802739 The "reference" test, in `reference_test.go`, is designed to check that we maintain compatibility between versions. It uses a "reference" version to write data out, then it attempts to read that data using the new version. However that test currently doesn't create a table with the new version and then write to it with the old version.

**Comment by spencerkimball** [comment]
@dt, I'm assigning this to you. Please either 1) re-assign, 2) un-assign and change 1.0 milestone to "Later" if you think this isn't 1.0 material

**Comment by dt** [comment]
not a 1.0 blocked, moved to Later.

**Comment by tbg** [comment]
The reference tests have been removed. In their place, we have mixed version tests. These could also do more, but this issue won't track it.
