### ISSUE TITLE
metrics: generate dashboards from a Go struct or JSON definition

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#81035]
## Problem

Our DB console dashboards are maintained in the frontend code. There is friction for a DB-Eng to make adjustments to the dashboards, such as adding graphs, fixing up help texts, etc.
As a result of this friction, the dashboards are effectively unmaintained. The frontend teams that have the expertise to easily adjust these graphs have no expertise on the graphs, and so a hand-off is necessary for many changes.

For a personal example, I have spent so many hours looking at this graph, which mixes two time series that operate at vastly different scales (1-20 vs hundreds), effectively hiding the smaller timeseries:

<img width="917" alt="image" src="https://user-images.githubusercontent.com/5076964/166887286-102a0c58-a75a-45d2-b640-02ab8481ae09.png">

I never went and fixed this. There are tons of things like this. Most metrics don't have help texts; we do have help texts in the backend and while they aren't perfect either, they *exist*. Nobody will transcribe them into the frontend.

Dashboards are poorly organized and for the same reasons as mentioned above, this isn't improving.

As a result of, I'm finding myself using custom charts most of the time when I'm running experiments.

## (Partial) Solution

All charts should be powered by custom charts code from a definition served by a CRDB endpoint.
The custom charts are generated from a json definition ([here's a sample](https://gist.github.com/tbg/1010112fbfde68f1d75012dd1c2c6863)) and if we added titles and legends and hover help texts to that, it seems like it could render the same thing as the main metric pages. The upshot could be that we could generate the json from the [chart catalog](https://github.com/cockroachdb/cockroach/blob/3582a90c8787c6b5c6f8a1e65087af4f33d9e106/pkg/ts/catalog/chart_catalog.go#L32-L3192) that we have already, so we'd be very close to unifying with https://github.com/cockroachdb/cockroach/issues/54178, where the goal is (likely) to similarly create grafana dashboards from the same chart catalog.
I think in due time we'd also get better dashboards and ownership, since the friction to rearranging them would drop quite dramatically, as engineers could do it without touching the frontend.

cc @thtruo 

Jira issue: CRDB-15382

**Comment by knz** [comment]
As explained elsewhere, it would be better if the structs/json definitions were not fixed inside the cockroachdb executable, and could be customized at run-time.

Additionally, it would be even better if the preferred choice for a user could automatically apply to multiple cockroachdb consoles, not just the one, i.e. store the customization in the web browser or a 3rd party service and not the database itself.

**Comment by aliher1911** [comment]
How would browser based customization work in practice and who will be its primary users? I can think of cockroach developers that created their own dashboards for oncall investigations. But that would also make it hard to share this between people. Maybe we should then export json into gist and let it import from gist to local storage.

**Comment by tbg** [comment]
These are all good ideas but I'd advocate for a crawl-walk-run approach. For the time being it definitely makes sense to serve a fixed dashboard compiled in with the binary. The frontend could use that as a default, and optionally load the asset from elsewhere (step N+1/N). That seems like a separate issue. At the core, here, remain two related asks:

- take the definition of the dashboards out of the UI code, and
- do that in a way that allows me (as a CRDB engineer) to make the dashboards (that my teams own) high quality by integrating with our existing code and ownership workflows (in the backend).
