### ISSUE TITLE
later statements in same txn should see mutations of `CREATE INDEX` at statement phase

### ISSUE THREAD

**Issue by chengxiong-ruan** [cockroachdb/cockroach#81069]
Right now, when creating indexes in declarative schema changer, we only write mutations to descriptor collection at pre-commit phase, see : http://github.com/cockroachdb/cockroach/blob/master/pkg/sql/schemachanger/scplan/internal/opgen/opgen_secondary_index.go#L24-L24

This is problematic somehow, because later statements in the same transaction won't see the newly added index during statement phase. For example, this doesn't work:
```sql
create table t (a int);

SET use_declarative_schema_changer = 'unsafe_always';

begin;
create index t_idx_a on t(a);
comment on index t@t_idx_a is 'hello'; -- this will complain about index not found
commit;
```
The `comment on` statement cannot find an index to comment on. We need to have some way to hold the side effects in statement phase for other statements in the same transaction.

This is actually not a bug yet since `CREATE INDEX` is not fully supported in declarative schema changer.

Jira issue: CRDB-15367

**Comment by chengxiong-ruan** [comment]
the comment on index in the old schema changer is also broken simply because it only looks at active index, which is a different issue...

**Comment by ajwerner** [comment]
Generally speaking, the plan of record here is to use a synthetic descriptor inside the transaction. I think we're potentially a concept or two short. We can set the index to be synthetically `DELETE_ONLY` and then we should be in okay shape. I think we have to do that also so that the virtual tables work more or less as they do today.

**Comment by chengxiong-ruan** [comment]
closing in favor of #88294
