### ISSUE TITLE
json: AsText method unnecessarily returns pointer to string and error

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#81097]
Noticed while working on #80000: the method `AsText()` in `json.JSON` returns `(*string, error`).

I think it's silly?

- none of the methods actually return an error. It's unnecessary to pay the price of a 2nd error return.
- all of the methods create a `string` and then allocate (on the heap) a reference to it. Why not returning the `string` directly?

~Also, why not use the `.String()` method directly, which seems to do the same?~ (edit: nvm)

cc @yuzefovich 

Jira issue: CRDB-15147

**Comment by yuzefovich** [comment]
So we audited all implementations of `AsText`, and the error is returned by `jsonEncoded` implementation, so we need to keep that one. In terms of a pointer vs a value return parameter - we need to have some value to represent NULL JSON value, and we either use a `nil` string or introduce another boolean return parameter. We decided to keep things as is.
