### ISSUE TITLE
log: multiple log channels breaks thread safety for logSink implementations

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#81112]
In a support issue, we saw a panic with the following stack trace:
```
runtime error: invalid memory address or nil pointer dereference
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  |     /usr/local/go/src/runtime/panic.go:965
  | runtime.panicmem
  |     /usr/local/go/src/runtime/panic.go:212
  | runtime.sigpanic
  |     /usr/local/go/src/runtime/signal_unix.go:734
  | github.com/cockroachdb/cockroach/pkg/util/log.(*fluentSink).tryWrite
  |     /go/src/github.com/cockroachdb/cockroach/pkg/util/log/fluent_client.go:117
  | github.com/cockroachdb/cockroach/pkg/util/log.(*fluentSink).output
  |     /go/src/github.com/cockroachdb/cockroach/pkg/util/log/fluent_client.go:73
  | github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry
  |     /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:404
  | github.com/cockroachdb/cockroach/pkg/util/log.logfDepth
  |     /go/src/github.com/cockroachdb/cockroach/pkg/util/log/channels.go:60
  | github.com/cockroachdb/cockroach/pkg/util/log.Infof
  |     /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log_channels_generated.go:263
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).removeInitializedReplicaRaftMuLocked
  |     /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/store_remove_replica.go:133
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).MergeRange
  |     /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/store_merge.go:56
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleMergeResult
  |     /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_application_result.go:251
```
This indicates that `fluentSink.conn` was nil in `(*fluentSink).tryWrite`. Locally, I can't construct an order of events that causes this effect. However, the `logSink` implementations are not thread-safe, so they require proper synchronization above this level. If `(*fluentSink).output` was called concurrently, this can easily be explained.

One level up, I see that each `loggerT` has an `outputMu` mutex that it uses to avoid accessing sinks concurrently. This code all looks correct.

However, a CRDB node can be started with multiple channels, each with [their own](https://github.com/cockroachdb/cockroach/blob/v21.2.10/pkg/util/log/flags.go#L250) `loggerT` instance. These instances are given [shared `logSink`](https://github.com/cockroachdb/cockroach/blob/v21.2.10/pkg/util/log/flags.go#L275) objects.

There is no synchronization across multiple `loggerT` instances.

I believe this means that if multiple channels are logged to concurrently, mutual exclusion for `logSink` instances can be violated, which would explain the crash.

----

@knz could you read over this and double-check the theory when you get a chance? Am I missing any coordination between `loggerT` instances?

**Comment by dhartunian** [comment]
thx @knz we'll take this.
