### ISSUE TITLE
ccl/sqlproxyccl: leaked goroutine due to infinite retries in dialTenantCluster

### ISSUE THREAD

**Issue by jaylim-crl** [cockroachdb/cockroach#81140]
This is already an existing issue with the current sqlproxy (before the connection migration work).

Consider the case where there are no pods available. When a user connects to their cluster through sqlproxy, dialTenantCluster will retry infinitely until we get an address:

https://github.com/cockroachdb/cockroach/blob/60d0f95ba057dab8d4f50d2903c504fe275d061a/pkg/ccl/sqlproxyccl/proxy_handler.go#L365-L375

When the connection between user and sqlproxy gets terminated, nothing detects that in the code, and the retry logic will continuously attempt to fetch an address until one is obtained. Ideally we should stop doing that if the user closes the connection. I don't have a clean solution besides setting a hard limit to the retry elapsed time (e.g. 2 minutes), and returning a server busy error.

cc: @JeffSwenson @cockroachdb/sqlproxy-prs 

Jira issue: CRDB-15128

**Comment by andy-kimball** [comment]
If there are no pods available, the connection code should be forcing one to spin up. Is that not happening in this code path somewhere?

**Comment by jaylim-crl** [comment]
Hm, I may have to dig into this deeper. I bumped into this once when I tested the end-to-end connection migration work.

Consider a different case: https://github.com/cockroachdb/cockroach/blob/7a961838bd156b0a939d5348a094e9ce848bd8ad/pkg/ccl/sqlproxyccl/connector.go#L199-L246

If we fail to dial the SQL pod continuously, the retry loop will keep retrying. If the user terminates its connection with the sqlproxy, nothing stops the retry loop, and the connection goroutine is tied up. We don't currently tie ctx with the net.Conn object, and I don't see an easy way to do that since the only way to know if a socket is closed is by reading/writing to/from it, I think.

**Comment by andy-kimball** [comment]
While I could live with a timeout, I think 1 minute is way too short. That could easily get triggered if a customer's load ramps up enormously and we're busy scaling out SQL pods or splitting ranges in KV. And when customers see "server busy" errors (and they will with such a short timeout), they simply add a retry loop to their app to "make it work". That results in _more_ load being placed on the proxy, as now it needs to re-establish SSL connections in addition to retrying connections to SQL pods.

As a compromise, I think a timeout upwards of 5 minutes would almost never get triggered, except in cases where there's a true outage.
