### ISSUE TITLE
Include user-defined types in SHOW CREATE ALL TABLES

### ISSUE THREAD

**Issue by electrum** [cockroachdb/cockroach#81164]
When using `SHOW CREATE ALL TABLES` to dump the database schema to SQL, the generated SQL won't work if the schema uses user-defined types.

**Comment by HonoreDB** [comment]
Hi! You can get the create statements for types via `SHOW CREATE ALL TYPES`. Is it possible to change your tooling to run those statements first?

**Comment by electrum** [comment]
Nice, I didn't know that was supported (or will be in the future). Are there plans to support this for 21.2 that we're using in Cockroach Cloud?

**Comment by HonoreDB** [comment]
Ah, sorry, I missed that that hasn't quite been released yet. It probably won't be added to 21.2, but we're close to releasing 22.1 which will support it.
