### ISSUE TITLE
ui: add custom external links

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#8121]
It would be nice to be able to link to things like monitoring/alerts/etc... from the admin UI.

A simple start would be to pass custom name/url pairs as flags (eg: `--external-links="monitoring:https://monitoring.gce.cockroachdb.com:3000"`) and simply list them somewhere in the UI.

Further down the road, we can worry about custom templates/more complicated layout/customization through the UI, but this should be enough for now.

Allowing more than one from the start would be fairly helpful. eg: for now, I'd like to add the following to our test clusters: monitoring, alerts, grafana (maybe also pointer to the github repo with instructions).

**Comment by mrtracy** [comment]
@mberhault Is this something you still want?  This seems like a very odd and specific request geared around an individual workflow.

**Comment by mberhault** [comment]
this is something we can worry about later. historically, I've found custom messages/headers/links to be very useful. Both as pointers to other resources, and as a way to notify users of the system of "stuff". If we have a bucket for miscellaneous things to consider later, this would be a good example. If not, we can probably close it.

**Comment by vivekmenezes** [comment]
reopen if you really care
