### ISSUE TITLE
cdc: Slow tests

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#81238]
List of tests with run time exceeding 10s:

--- PASS: TestAlterChangefeedPersistSinkURI (10.67s)
--- PASS: TestChangefeedIdleness (26.81s)
--- PASS: TestChangefeedResolvedFrequency (11.49s)
--- PASS: TestChangefeedInitialScan (28.46s)
--- PASS: TestChangefeedUserDefinedTypes (15.07s)
--- PASS: TestChangefeedSchemaChangeNoBackfill (42.38s)
    --- PASS: TestChangefeedSchemaChangeNoBackfill/enterprise (13.48s)
    --- PASS: TestChangefeedSchemaChangeNoBackfill/webhook (13.89s)
    --- PASS: TestChangefeedSchemaChangeNoBackfill/pubsub (12.92s)
--- PASS: TestChangefeedSchemaChangeBackfillCheckpoint (14.76s)
--- PASS: TestChangefeedSchemaChangeAllowBackfill (31.19s)
--- PASS: TestChangefeedEachColumnFamily (18.01s)
--- PASS: TestChangefeedStopOnSchemaChange (27.22s)
    --- PASS: TestChangefeedStopOnSchemaChange/webhook (12.85s)
--- PASS: TestChangefeedNoBackfill (15.10s)
--- PASS: TestChangefeedVirtualComputedColumn (10.23s)
--- PASS: TestChangefeedUpdateProtectedTimestamp (21.37s)
--- PASS: TestChangefeedProtectedTimestampOnPause (19.24s)
--- PASS: TestManyChangefeedsOneTable (10.58s)
--- PASS: TestChangefeedPrimaryKeyChangeWorks (22.79s)
--- PASS: TestChangefeedPrimaryKeyChangeWorksWithMultipleTables (15.84s)
--- PASS: TestChangefeedCheckpointSchemaChange (14.30s)
--- PASS: TestChangefeedBackfillCheckpoint (30.01s)
--- PASS: TestChangefeedOnErrorOption (11.51s)
--- PASS: TestChangefeedNemeses (14.13s)
--- PASS: TestWebhookSink (16.72s)

Jira issue: CRDB-15276

Epic CRDB-9179

**Comment by miretskiy** [comment]
From one of the stress runs:

Slow failing tests:
TestChangefeedBackfillCheckpoint - 160.79s

Slow passing tests:
TestChangefeedPredicateWithSchemaChange - 90.24s
TestChangefeedPredicateWithSchemaChange - 87.63s
TestChangefeedHandlesDrainingNodes - 60.15s
TestChangefeedHandlesDrainingNodes - 60.04s
TestChangefeedSchemaChangeBackfillCheckpoint - 55.18s
TestChangefeedBackfillCheckpoint - 51.09s
TestChangefeedReplanning - 50.54s
TestChangefeedReplanning - 49.89s
TestChangefeedRestartMultiNode - 45.11s
TestWebhookSink - 42.12s
TestChangefeedRestartMultiNode - 40.11s
TestChangefeedBasics - 35.60s
TestChangefeedBasics - 35.17s
TestAlterChangefeedAddTargetsDuringBackfill - 35.16s
TestChangefeedStopOnSchemaChange - 34.77s
TestChangefeedSchemaChangeNoBackfill - 32.65s
TestAlterChangefeedAddTargetErrors - 32.40s
TestChangefeedStopPolicyMultiNode - 32.34s
TestChangefeedMultiPodTenantPlanning - 31.78s
TestChangefeedUpdateProtectedTimestamp - 31.50s

**Comment by shermanCRL** [comment]
This might be educational for @jayshrivastava to work on this.

**Comment by miretskiy** [comment]
Closing -- need to get up to date information on these tests.
