### ISSUE TITLE
build: publish `cockroach-sql` as an archive, not a standalone binary

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#81246]
Followup to #79796.
cc @rail 

currently `cockroach-sql` is published as a standalone binary on S3.
This makes the UX cumbersome for end-users:

- we provide explanations in docs about how to extract archives, and this is not an archive
- on macos and linux, the user needs to still run `chmod +x` on the result, and we didn't document that

The situation would be much simpler if `cockroach-sql` was added to an archive file (containing only this file), so that the user could extract/install it in the same way as `cockroach`.

Jira issue: CRDB-15272

**Comment by knz** [comment]
requested by @stbof

**Comment by knz** [comment]
NB: once we convert this, we would need to re-package all the previous uploads accordingly

**Comment by rail** [comment]
I'll take a look at this.

**Comment by knz** [comment]
NB: we also need to coordinate this change with the docs - the URLs there will need to be updated as well.
