### ISSUE TITLE
kvserver: include crdb_internal.cluster_locks in debug.zip

### ISSUE THREAD

**Issue by kvoli** [cockroachdb/cockroach#81245]
In recent escalations we have wanted to determine active locks on stuck rows, associate them with txns and associate those txns with sessions.

This is currently possible by looking through individual range.jsons however it would be much simpler to view the lock table in the debug zip, for a summary view of contended rows, with a waits-for dag.

The solution is to investigate the overhead of including `crdb_internal.cluster_locks` in the debug zip. If the overhead is low enough for collection, to then include it in the debug zip.

https://github.com/cockroachdb/cockroach/blob/9a179ea1aa8d6723fb12a988f2212ac8493e5dfc/pkg/cli/zip_cluster_wide.go#L76

**Comment by kvoli** [comment]
cc @AlexTalks

**Comment by AlexTalks** [comment]
Thanks for the call out!  We actually should have `cluster_locks` in the debug.zip already at this point:
https://github.com/cockroachdb/cockroach/blob/e2f3965e40a597f5c01bca51e14bed1bea0e2191/pkg/cli/zip_cluster_wide.go#L80

If it's not working on nodes running >=22.1.1 let me know though!
