### ISSUE TITLE
sql.stats.aggregation.interval missing from cluster settings table

### ISSUE THREAD

**Issue by stbof** [cockroachdb/cockroach#81252]
https://github.com/cockroachdb/cockroach/pull/74831 added the cluster setting `sql.stats.aggregation.interval`, but it does not appear in the cluster settings table: https://www.cockroachlabs.com/docs/dev/cluster-settings.html.

The setting `sql.stats.flush.interval` is in the table and  refers to `sql.stats.aggregation.interval` in the description

> the interval at which SQL execution statistics are flushed to disk, this value must be less than or equal to sql.stats.aggregation.interval

but the property `sql.stats.aggregation.interval` itself is missing.

Jira issue: CRDB-15267

**Comment by xinhaoz** [comment]
I'm wondering if this was intentional. I recall the decision being made that the aggregation interval setting would not be documented to uesrs. cc @kevin-v-ngo

**Comment by maryliag** [comment]
The decision to hide that cluster setting was intentional, we don't want users to change it. Maybe for this task is worth updating the description of `sql.stats.flush.interval` to not mention `sql.stats.aggregation.interval`, and use `1h`, since that's its the default value.
