### ISSUE TITLE
geos: upgrade to latest version

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#81290]
### Discussed in https://github.com/cockroachdb/cockroach/discussions/81237

<div type='discussions-op-text'>

<sup>Originally posted by **prashantkhoje** May 13, 2022</sup>
Cockroachdb has forked package geos to be used with it.
The forked repo is ~2 year old.
Is there plan to refresh it from [original repo](https://github.com/libgeos/geos)?
On ppc64le, i found that forked repo has 12 failures:
>          11 - unit-algorithm-LocatePointInRing (Failed)
>          14 - unit-algorithm-OrientationIndexFailure (Failed)
>          17 - unit-algorithm-RobustLineIntersector (Failed)
>          82 - unit-capi-GEOSVoronoiDiagram (Failed)
>         116 - unit-geom-Triangle (Failed)
>         129 - unit-linearref-LengthIndexedLine (Failed)
>         130 - unit-math-DD (Failed)
>         142 - unit-operation-distance-DistanceOp (Failed)
>         177 - general-TestCentroid (Failed)
>         191 - general-TestFunctionPLPrec (Failed)
>         222 - issue-issue-geos-350 (Failed)
>         269 - robust-TestRobustRelate (Failed)

Whereas, original geos has only 1 failure:
>        243 - unit-shape-fractal-HilbertEncoder (Failed)

I understand ppc64le is not supported by cockroachdb.

Thank you,
Prashant</div>

Jira issue: CRDB-15249

**Comment by prashantkhoje** [comment]
Thank you, @otan.
cc: @seth-priya

**Comment by robe2** [comment]
@prashantkhoje  Can you retest your setup against latest GEOS main.  Your  

`243 - unit-shape-fractal-HilbertEncoder (Failed) \`

Should be fixed now.

**Comment by prashantkhoje** [comment]
Sure. I'll retest.

Thank you!

**Comment by prashantkhoje** [comment]
If we build libgeos from https://github.com/libgeos/geos repo, then all the tests pass on ppc64le.

**Comment by prashantkhoje** [comment]
@ambujkumar3, @seth-priya fyi

**Comment by otan** [comment]
upgraded to 3.11.2
