### ISSUE TITLE
gossip: test reconnection to gossip network on node failure

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#8129]
See #8128. Prior to that change, we wouldn't attempt to open a new gossip connection if our current connection closed unexpectedly with no forwarding address. This would leave the node in a state where it wasn't receiving or sending gossip updates.

**Comment by tamird** [comment]
@petermattis #8128 results in the following log spam on a single node cluster:
```
I160731 13:47:07.226662 gossip/client.go:75  starting client to localhost:26257
I160731 13:47:07.227345 gossip/client.go:99  closing client to node 1 (localhost:26257): stopping outgoing client to node 1 (localhost:26257); loopback connection
```
ad infinitum.

**Comment by petermattis** [comment]
Yeah, I noticed that today too. Not hugely problematic as it only happens in a 1 node cluster, but it should be fixed. Sometimes I think gossip is more headache than its worth.

**Comment by petermattis** [comment]
Why does gossip even bother connecting to itself? There is an unhelpful comment in `Node.start`:

```
			// Make sure we add the node as a resolver.
			selfResolver, err := resolver.NewResolverFromAddress(addr)
			if err != nil {
				return err
			}
			n.ctx.Gossip.SetResolvers([]resolver.Resolver{selfResolver})
```
