### ISSUE TITLE
kv: failure to find new lease-holder for first range

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#8130]
If the lease-holder for the first range (range 1) crashes and restarts and if the lease has been transferred to a new replica while it was down, the restarted node may not be able to find the lease-holder. The restarted node is finding the first-range descriptor via gossip and then sending an RPC to the first replica which happens to be itself. Because it has just started, it doesn't know who the lease-holder is for range 1:

```
I160729 20:53:43.304788 kv/dist_sender.go:462  [txn=9d6536e4,r=1] unable to find lease holder: [1/1/1 2/2/2 4/3/3]
I160729 20:53:43.304808 kv/dist_sender.go:903  [txn=9d6536e4,r=1] sendToReplicas: [1/1/1 2/2/2 4/3/3]
I160729 20:53:43.304843 kv/transport.go:164  [txn=9d6536e4,r=1] sending request to Peters-MacBook-Pro-2.local:26257: Get [/Table/2/1/0/"zerosum"/3/1,/Min)
I160729 20:53:46.308984 kv/dist_sender.go:943  [txn=9d6536e4,r=1] RPC reply: range 1: replica node_id:1 store_id:1 replica_id:1  not lease holder; <nil> is
```

All of the nodes are running on the same machine. Port 26257 corresponds to node 1.

If we're lucky, the next replica we try is also not the lease holder and the response will indicate who the lease holder is. But there are only 2 possibilities here, so 50% of the time we're not lucky and we send the RPC to the lease holder itself. 

```
I160729 20:53:46.309083 kv/transport.go:164  [txn=9d6536e4,r=1] sending request to Peters-MacBook-Pro-2.local:26259: Get [/Table/2/1/0/"zerosum"/3/1,/Min)
I160729 20:53:46.309939 kv/dist_sender.go:943  [txn=9d6536e4,r=1] RPC reply: *roachpb.GetResponse
I160729 20:53:46.310075 kv/dist_sender.go:462  [txn=9d6536e4,r=1] unable to find lease holder: [1/1/1 2/2/2 4/3/3]
```

The lease holder satisfies the request, but in this code path through the `DistSender` we don't update our lease-holder cache which results in the next request to range 1 going through the same shenanigans.

I'm not sure why the replica on node 1 isn't able to determine who the lease holder is. Something is clearly getting fouled up in `Replica.redirectOnOrAcquireLease` as we only return `<nil>` for the lease holder if the lease acquisition times out.

Cc @tschottdorf

**Comment by petermattis** [comment]
Looks like the lease acquisition is timing out. I see this attempt, but not others:

```
I160729 21:11:14.977578 storage/replica.go:576  [txn=07ab34b8,r=1,n=1,s=1] request range lease (attempt 1)
```

Still digging.

**Comment by petermattis** [comment]
Oy-vey! (This is from a different run, but the same scenario). Node 1 requests the lease for range 1 after restarting:

```
I160729 21:26:38.826704 storage/replica.go:576  [txn=f41c6b95,r=1,n=1,s=1] request range lease (attempt 1)
```

But there is no current raft leader for range 1:

```
I160729 21:26:38.918030 raft/raft.go:777  [range 1] 1 no leader at term 7; dropping proposal
```

So raft calls for an election:

```
I160729 21:26:40.019354 raft/raft.go:549  [range 1] 1 is starting a new election at term 7
I160729 21:26:40.019427 raft/raft.go:482  [range 1] 1 became candidate at term 8
I160729 21:26:40.019454 raft/raft.go:531  [range 1] 1 received vote from 1 at term 8
I160729 21:26:40.019569 raft/raft.go:524  [range 1] 1 [logterm: 7, index: 116] sent vote request to 2 at term 8
I160729 21:26:40.019643 raft/raft.go:524  [range 1] 1 [logterm: 7, index: 116] sent vote request to 3 at term 8
```

But that election does not succeed, because the other replicas shut us down:

```
W160729 21:26:42.720332 storage/replica.go:337  range 1: outgoing raft transport stream to {4 4 2} closed by the remote: rpc error: code = 2 desc = range 1: discarding message from {NodeID:1 StoreID:1 ReplicaID:1}, older than NextReplicaID 5
```

We can see that slightly before this, node 1 was removed as a replica for range 1:

```
cockroach-data/4/logs/stderr:I160729 21:26:18.437141 storage/replica.go:2533  gossiping first range from store 4, range 1: [{1 1 1} {4 4 2} {2 2 3}]
cockroach-data/4/logs/stderr:I160729 21:26:41.369700 storage/replica.go:2533  gossiping first range from store 4, range 1: [{1 1 1} {4 4 2} {2 2 3} {3 3 4}]
cockroach-data/4/logs/stderr:I160729 21:26:41.382288 storage/replica.go:2533  gossiping first range from store 4, range 1: [{3 3 4} {4 4 2} {2 2 3}]
```

Given the above, I would expect node 1 to have updated its notion of where the first range is located. But, as far as I can tell, `rangeDescriptorCache` does not listen for gossiping of the first range.

**Comment by tamird** [comment]
How does this interact with https://github.com/cockroachdb/cockroach/pull/8125?

**Comment by petermattis** [comment]
@tamird As far as I know, that is completely different.

**Comment by petermattis** [comment]
(That's the replica descriptor cache in `Store` while I'm looking at `kv.rangeDescriptorCache`).

**Comment by tamird** [comment]
We should be enqueuing the replica into the replicaGCQueue when we get those raft rejections. It's true that the rangeDescriptorCache doesn't listen to gossip - the gossip first range descriptor is available (only?) via DistSender.FirstRange().

**Comment by petermattis** [comment]
Yeah, it looks to me like `rangeDescriptorCache` caches the first range (retrieved via `DistSender.FirstRange`) the first time it is accessed and then never evicts it from the cache. I tried not caching the first range (because `DistSender.FirstRange` is quick), but that didn't seem to help. Or I did something wrong.

**Comment by petermattis** [comment]
Not sure what was going wrong earlier, but I have a small change to evict the first-range from `rangeDescriptorCache` whenever it is gossiped and it addresses part of the problem here. The remaining issues:
* We don't update the lease-holder cache when send a successful lease-requiring request to a second or third replica.
* Why are request-lease operations timing out on the newly started node? I imagine this is because the raft state for that node is behind, but this is worth tracking down.
* The range lease-holder for the first-range gossips it whenever lease ownership changes. Can we use this to optimistically determine who the lease-holder for the first-range is?

**Comment by petermattis** [comment]
When a node starts up it scans through the on-disk replica state and reconstitutes the replicas. In the case of range 1, we almost immediately request the range lease in order to try and gossip the first range. Because the `raft.RawNode` was just created, it is currently a "follower" and doesn't know who the Raft leader is. We see the following in the logs (note I've added some additional logging here):

```
I160731 15:09:24.442803 storage/replica.go:1394  store=1:1 ([]=cockroach-data/1) range=1 [/Min-/Table/11): propose raft command: RequestLease [/Min,/Min)
I160731 15:09:24.442966 raft/raft.go:469  [range 1] 1 became follower at term 7
I160731 15:09:24.443077 raft/raft.go:238  [range 1] newRaft 1 [peers: [1,2,3], term: 7, commit: 116, applied: 116, lastindex: 116, lastterm: 7]
I160731 15:09:24.443126 raft/raft.go:777  [range 1] 1 no leader at term 7; dropping proposal
```

After not hearing from its compatriates, range 1 on this node starts an election:

```
I160731 15:09:27.044135 raft/raft.go:549  [range 1] 1 is starting a new election at term 7
I160731 15:09:27.044170 raft/raft.go:482  [range 1] 1 became candidate at term 8
I160731 15:09:27.044187 raft/raft.go:531  [range 1] 1 received vote from 1 at term 8
I160731 15:09:27.044263 raft/raft.go:524  [range 1] 1 [logterm: 7, index: 116] sent vote request to 2 at term 8
I160731 15:09:27.044311 raft/raft.go:524  [range 1] 1 [logterm: 7, index: 116] sent vote request to 3 at term 8
I160731 15:09:27.447699 raft/raft.go:743  [range 1] 1 no leader at term 8; dropping proposal
```

```
I160731 15:09:28.767267 raft/raft.go:756  [range 1] 1 [logterm: 7, index: 116, vote: 1] rejected vote from 2 [logterm: 7, index: 116] at term 8
I160731 15:09:28.767773 raft/raft.go:469  [range 1] 1 became follower at term 8
I160731 15:09:30.442779 raft/raft.go:549  [range 1] 1 is starting a new election at term 8
I160731 15:09:30.442827 raft/raft.go:482  [range 1] 1 became candidate at term 9
I160731 15:09:30.442841 raft/raft.go:531  [range 1] 1 received vote from 1 at term 9
I160731 15:09:30.442952 raft/raft.go:524  [range 1] 1 [logterm: 8, index: 117] sent vote request to 3 at term 9
I160731 15:09:30.443025 raft/raft.go:524  [range 1] 1 [logterm: 8, index: 117] sent vote request to 2 at term 9
I160731 15:09:30.443089 raft/raft.go:743  [range 1] 1 no leader at term 9; dropping proposal
I160731 15:09:30.444657 raft/raft.go:533  [range 1] 1 received vote rejection from 2 at term 9
I160731 15:09:30.444695 raft/raft.go:760  [range 1] 1 [quorum:2] has received 1 votes and 1 vote rejections
I160731 15:09:31.793405 raft/raft.go:743  [range 1] 1 no leader at term 9; dropping proposal
I160731 15:09:31.793467 raft/raft.go:743  [range 1] 1 no leader at term 9; dropping proposal
I160731 15:09:31.793648 raft/raft.go:756  [range 1] 1 [logterm: 8, index: 117, vote: 1] rejected vote from 3 [logterm: 8, index: 118] at term 9
I160731 15:09:31.793717 raft/raft.go:469  [range 1] 1 became follower at term 9
I160731 15:09:31.793738 raft/raft.go:821  [range 1] 1 [logterm: 0, index: 118] rejected msgApp [logterm: 8, index: 118] from 3
I160731 15:09:31.930159 raft/raft.go:858  [range 1] 1 [commit: 116, lastindex: 117, lastterm: 8] starts to restore snapshot [index: 230, term: 9]
I160731 15:09:31.930188 raft/log.go:288  [range 1] log [committed=116, applied=116, unstable.offset=118, len(unstable.Entries)=0] starts to restore snapshot [index: 230, term: 9]
I160731 15:09:31.930208 raft/raft.go:870  [range 1] 1 restored progress of 1 [next = 231, match = 230, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
I160731 15:09:31.930220 raft/raft.go:870  [range 1] 1 restored progress of 2 [next = 231, match = 0, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
I160731 15:09:31.930230 raft/raft.go:870  [range 1] 1 restored progress of 3 [next = 231, match = 0, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
I160731 15:09:31.930242 raft/raft.go:835  [range 1] 1 [commit: 230] restored snapshot [index: 230, term: 9]
```

Looking at the logs for other nodes I can see they are failing to send to node 1:

```
I160731 15:09:25.285535 raft/raft.go:709  [range 1] 3 failed to send message to 1 because it is unreachable [next = 119, match = 0, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
```

**Comment by petermattis** [comment]
Hmm, looks like we never see connections being closed because the heartbeating in `rpc/context.go` specifies `grpc.FailFast(false)`. @tamird Is there a reason for that?

**Comment by tamird** [comment]
@petermattis does `FailFast(false)` imply fail never? I believe I had to make that change to get tests passing after the grpc update (prior to which all RPCs were `FailFast(false)`).

If tests are passing without it then it's fine by me.

**Comment by petermattis** [comment]
@tamird `FailFast(false)` seems to imply an RPC never fails on transport failures. The tests are passing, though we seem to have a hole in test coverage that didn't catch this earlier. I'll file an issue.

**Comment by tamird** [comment]
Ah, I see you got around the test issues by special-casing the RPC sender.
