### ISSUE TITLE
sql: CREATE TABLE using sequence for columns is incorrectly populated

### ISSUE THREAD

**Issue by Xiang-Gu** [cockroachdb/cockroach#81333]
Create two sequences and use them to create a table (one for default expression and another for on-update expression):

```
CREATE SEQUENCE s1;

CREATE SEQUENCE s2;

CREATE TABLE tbl (a INT PRIMARY KEY, b INT NOT NULL DEFAULT nextval('s1') ON UPDATE nextval('s2'));
```

```
SHOW CREATE tbl
```
incorrectly gives
```
 CREATE TABLE public.tbl (
   a INT8 NOT NULL,
   b INT8 NOT NULL DEFAULT nextval('public.s2'::REGCLASS) ON UPDATE nextval('s2':::STRING),
   CONSTRAINT tbl_pkey PRIMARY KEY (a ASC)
 )
```

There are two errors:
1. ON UPDATE should use the sequence id (i.e. `s2::REGCLASS`) rather than its name (i.e. `s2:::STRING`). This is a known issue as in #77145 
2. DEFAULT expression should be `nextval('s1'::REGCLASS)`.

The root cause is the function

https://github.com/cockroachdb/cockroach/blob/711ccb5b8fba4e6a826ed6ba46c0fc346233a0f7/pkg/sql/sequence.go#L779-L783

which modifies the default expression
https://github.com/cockroachdb/cockroach/blob/711ccb5b8fba4e6a826ed6ba46c0fc346233a0f7/pkg/sql/sequence.go#L866-L873

but such a function is incorrectly used in multiple places ('create_table', 'alter_table', 'add_column') in that, if you look at the caller, it has the pattern of 
```
cdd.ForEachTypedExpr(func(expr tree.TypedExpr) error {
					... := maybeAddSequenceDependencies(
						..., expr, ...)
...
```
The `ForEachTypedExpr` simply invoke the given function on both default expression and on update expression, if they exist:
https://github.com/cockroachdb/cockroach/blob/711ccb5b8fba4e6a826ed6ba46c0fc346233a0f7/pkg/sql/catalog/tabledesc/table.go#L61-L73

So, in the case where we use two different sequences for default expression and on-update expression (as in our example), the second call on the on-update expression will incorrectly set the default expression to 's2'.

Jira issue: CRDB-15237

**Comment by ajwerner** [comment]
Great find!

**Comment by postamar** [comment]
IMHO this kind of bug was allowed to happen due to inadequate test coverage. Consequently, fixing this should come with the addition of more tests.

**Comment by Xiang-Gu** [comment]
I'm closing it because of the merged fix.
