### ISSUE TITLE
Random crash with exit code 1

### ISSUE THREAD

**Issue by misiek08** [cockroachdb/cockroach#81362]
**Describe the problem**

I tried setting up local cluster using docker. I followed [tutorial](https://www.cockroachlabs.com/docs/stable/start-a-local-cluster-in-docker-mac.html) and after starting all nodes and initializing cluster they started to randomly crash. roach1 stays online for most of the time, roach2 and roach3 crash in less than 2 minutes without logging anything helpful.
A lot of free RAM available, CPU and disk mostly at idle IMHO.

I tried joining 4-th node and it crashed after 2 seconds. I'm attaching it's data directory, but I think there is nothing useful there.

**To Reproduce**

1. Set up CockroachDB cluster and try to init it.
2. Nodes crashing

**Expected behavior**
Cluster staying stable and idling.

**Additional data / screenshots**
I'm attaching 4-th node logs, because they are pure, mostly empty.

**Environment:**
 - CockroachDB version: 21.2.10
 - Server OS: Docker for Mac
 - Client app: `cockroach sql` and Cluster Overview GUI (doesn't matter)

Jira issue: CRDB-15220

**Comment by misiek08** [comment]
[roach4.tar.gz](https://github.com/cockroachdb/cockroach/files/8707668/roach4.tar.gz)

**Comment by misiek08** [comment]
It looks like 2 nodes work correctly, but after adding 3rd one of them is crashing.

**Comment by jordanlewis** [comment]
Hi, you'll need to attach all of the logs, startup options, and so on to help us understand what's going on, please. It sounds like there's probably a configuration error of some sort.

**Comment by misiek08** [comment]
I did follow https://www.cockroachlabs.com/docs/stable/start-a-local-cluster-in-docker-mac.html
Steps 1 and 2, changing `${PWD}` to `$PWD` because _fish_ wants it that way :) This little change is of course working correctly because the directories are being created correctly.

Until `init` all 3 nodes are up and running. After `docker exec -it roach1 ./cockroach init --insecure` roach3 immediately exited with code 1.

Whole `cockroach-data` directory attached, I'm also attaching all I get on terminal with `docker inspect roach3` after it crashed/exited.

Docker desktop version: 4.8.2
Docker engine version: 20.10.14

Files:
[data_dir.tar.gz](https://github.com/cockroachdb/cockroach/files/8715632/data_dir.tar.gz)
[terminal.txt](https://github.com/cockroachdb/cockroach/files/8715633/terminal.txt)

**Comment by misiek08** [comment]
When I run `docker start roach3` it starts, work for 5-120 seconds and randomly roach2 or roach3 crash again. After re-starting (`docker start ...`) this fun continues :)

**Comment by misiek08** [comment]
I've recorded (unedited, so you have to wait 35 seconds for `roach3` to crash after bringing back `roach2` to life) screencast: https://www.youtube.com/watch?v=g00thxSbWKU

Of course attaching data directory and copy of terminal output (with whole _docker inspect_ outputs) to analyze.

**I didn't try running such cluster on linux-based machine, maybe Docker for mac is crashing stuff, again....**
I'm on MBP 16" '19, i7 6-core, 32G RAM

**Comment by misiek08** [comment]
It seems like a resurrection of:
* https://github.com/docker/for-mac/issues/5124#issuecomment-744697395
* https://github.com/cockroachdb/cockroach/issues/57192

**Comment by nicktrav** [comment]
@misiek08 - this is almost certainly the same issue that's mentioned on the upstream Docker ticket. A few things:

You should be able to work around this issue by using a Docker volume rather than the host's filesystem. The instructions for using the volume are in the tutorial you linked.

I've found it helpful when debugging to run with the `--logtostderr` flag, which likely print the cause of the crash to the console. If it's the same issue, I'd expect to see something like `‹open /cockroach/cockroach-data/000219.sst: no such file or directory›` in the error message on two of the three containers (the first container doesn't seem to ever have any issue, as detailed on docker/for-mac#5124).

If you could confirm the error that's causing the process exit, that would help. Thank you!

**Comment by misiek08** [comment]
Last few lines are:
```
I220727 07:33:48.398736 569 3@vendor/github.com/cockroachdb/pebble/event.go:603 ⋮ [n2,pebble,s2] 96  [JOB 5] flushed 1 memtable to L0 [000011] (1.4 K), in 0.0s, output rate 214 K/s
I220727 07:33:48.399094 571 3@vendor/github.com/cockroachdb/pebble/event.go:587 ⋮ [n2,pebble,s2] 97  [JOB 6] compacting(move) L0 [000011] (1.4 K) + L6 [] (0 B)
I220727 07:33:48.400121 571 3@vendor/github.com/cockroachdb/pebble/event.go:591 ⋮ [n2,pebble,s2] 98  [JOB 6] compacted(move) L0 [000011] (1.4 K) + L6 [] (0 B) -> L6 [000011] (1.4 K), in 0.0s, output rate 20 M/s
I220727 07:33:48.406978 573 3@vendor/github.com/cockroachdb/pebble/event.go:587 ⋮ [n2,pebble,s2] 99  [JOB 8] compacting(default) L0 [000009 000005] (2.5 K) + L6 [000011] (1.4 K)
I220727 07:33:48.423323 573 (gostd) filenames.go:162 ⋮ [-] 100  ‹000009.sst:›
I220727 07:33:48.423323 573 (gostd) filenames.go:162 ⋮ [-] 100 +‹open /cockroach/cockroach-data/000009.sst: no such file or directory›
I220727 07:33:48.423323 573 (gostd) filenames.go:162 ⋮ [-] 100 +‹directory contains 25 files, 12 unknown, 7 tables, 2 logs, 1 manifests›
```
It was weird to me I didn't see those log lines anywhere in the files, but maybe saving them fails same way like accessing this sst file. Thanks for the flag - it's much quicker than file-config. I'll push on docker guys to look at this and fix.

Thank you!
