### ISSUE TITLE
admission: noisy granter CPULoad logs

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#81360]
I've seen this in many different experiments:

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/5076964/168790551-d0a61002-7ead-4fcd-a86e-a31fd6287a3c.png">

We should remove/downgrade this log message and add a metric instead.

Jira issue: CRDB-15222

**Comment by sumeerbhola** [comment]
(from an internal conversation)
There are 2 reasons for these log statements:
- to know if this switching is happening and how often, in case we need to improve the heuristic in runnable.go.
- if we see some weird admission control behavior, we want to be able to tell whether there was any use of the 250ms sampling during that time interval.

Both use cases can be addressed using two cumulative metrics (or preferably one metric with a label) that count the number of 250ms samples and the number of 1ms samples.

**Comment by irfansharif** [comment]
https://github.com/cockroachdb/cockroach/commit/3cfc79f6bc340f4a0a48384e09dd49719e8678c8 +  https://github.com/cockroachdb/cockroach/pull/96511.
