### ISSUE TITLE
sql/colcontainer: TestExternalDistinct leaks Queues, file descriptors

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/cockroach#81413]
In #81389, I originally moved where Pebble's disk-health checking is layered onto the filesystem. Disk-health checking monitors for excessively slow writes, crashing the process if writes appear to be stalled in the kernel. The changes in #81389 caused disk-health checking to be used in `TestExternalDistinct`. `TestExternalDistinct` began to fail with leaked goroutines in the disk-health checking. I dug into it a bit, and traced it to a `diskQueue` that is never `Close`d, causing its `writeFile` to never be closed.

For now I should be able to refactor #81389 to continue omitting disk-health checking in this code path and unblock the vendor bump, so this isn't a blocker for me.

**Comment by jbowens** [comment]
With the changes from #81419, I still saw a couple file descriptors leak in `TestSQLLogic` in CI: https://github.com/cockroachdb/cockroach/pull/81389#issuecomment-1130293904

For now, I'm going to continue disable disk-health checking for these in-memory unit test engines, so that we can merge this Pebble bump.

**Comment by yuzefovich** [comment]
Thanks Jackson! Could you please drop a quick comment on how to enable those checks back so that I could debug?

**Comment by yuzefovich** [comment]
Oh, I see, it's just `storage.DisableFilesystemMiddlewareTODO` knob.
