### ISSUE TITLE
sql: ALTER TABLE ... ADD COLUMN ... PRIMARY KEY doesn't work correctly

### ISSUE THREAD

**Issue by postamar** [cockroachdb/cockroach#81449]
To repro:
```
CREATE TABLE t (a INT PRIMARY KEY);
ALTER TABLE t ADD COLUMN b INT PRIMARY KEY;
```
Expected: ~the primary key is `b`~ an error is returned (in pg: `multiple primary keys for table "t" are not allowed`)
Actual: success, and a subsequent `SHOW CREATE TABLE t` yields
```
  table_name |              create_statement
-------------+---------------------------------------------
  t          | CREATE TABLE public.t (
             |     a INT8 NOT NULL,
             |     b INT8 NOT NULL,
             |     CONSTRAINT t_pkey PRIMARY KEY (a ASC),
             |     UNIQUE INDEX t_b_key (b ASC)
             | )
(1 row)
```

Jira issue: CRDB-15178

**Comment by otan** [comment]
seems more like we want an error for the second statement right?

e.g. PG
```
otan=# CREATE TABLE t (a INT PRIMARY KEY);
ALTER TABLE t ADD COLUMN b INT PRIMARY KEY;
CREATE TABLE
ERROR:  multiple primary keys for table "t" are not allowed
```

**Comment by postamar** [comment]
You're most likely correct, I didn't cross-check with postgres, sorry.

**Comment by ajwerner** [comment]
I agree we should reject ` CREATE TABLE t (a INT PRIMARY KEY); ALTER TABLE t ADD COLUMN b INT PRIMARY KEY;`, but what to do in the case that the primary key is the implicit `rowid` primary key is less clear. Consider the following which is valid in postgres ` CREATE TABLE t (a INT); ALTER TABLE t ADD COLUMN b INT PRIMARY KEY;`

**Comment by otan** [comment]
> CREATE TABLE t (a INT PRIMARY KEY); ALTER TABLE t ADD COLUMN b INT PRIMARY KEY;

feels like we should definitely allow it if `rowid` is the hidden default PK...
