### ISSUE TITLE
Provide observability into whether a workload is slow due to having tracing enabled

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#81472]
We should surface whether a workload is running slow due to tracing being enabled. Specifically, we should surface a counter for the number of times a statement fingerprint executed with tracing enabled in crdb_internal.statement_statistics. 

Having this information will enable users to troubleshoot a slow statement  fingerprint (at hourly granularity) and rule out issues unrelated to common performance issues such as suboptimal/regression plans, contention, retries, etc.

Direct [feedback](https://cockroachlabs.slack.com/archives/C0159JK877C/p1652899187790819)

Jira issue: CRDB-15167

**Comment by andreimatei** [comment]
I'm skeptical of the usefulness of this feature.
At the very least, "tracing enabled" is not a binary thing. By default, some level of tracing is enabled for all queries. Structured recording is enabled for 1% of the traffic, and verbose recording is only enabled on demand (or when a 3rd party tracer is attached). In the future we'll blur the lines even more between tracing being enabled and disabled.

I believe the regression that prompted for this to be filed didn't have to do with tracing being specific to one statement fingerprint, but across all the queries. So for that case, per fingerprint counters would be overkill. And I worry about the future evolution of such counters. Let's try blunter instruments.
