### ISSUE TITLE
Transaction Details page has an empty statements table, caused by the transaction fingerprint ID for most statements not being populated in the endpoint response (and possibly deeper)

### ISSUE THREAD

**Issue by jocrl** [cockroachdb/cockroach#81470]
**Describe the problem**
First reported by @dbist.

The first symptom is that the Statements table in the Transactions Details page is empty, but all other parts of the page are populated.

Upon further inspection, it turns out that for the statements involved, the `transaction_fingerprint_id` column in the `statement_statistics` table is 0 instead of the transaction id. Accordingly, in the endpoint `key.key_data.transaction_fingerprint_id` is 0 instead of the transaction id.
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/91907326/169157003-0f5c50db-b67a-40dc-991d-548dbe74df81.png">

This is is despite that in the endpoint response `transactions -> index 5 -> stats_data -> statement_fingerprint_ids` is correctly populated with statement_fingerprint_ids.

**To Reproduce**

This is the case in the roachprod cluster on 22.1-rc linked in [this slack thread](https://cockroachlabs.slack.com/archives/C0159JK877C/p1652897560746299?thread_ts=1652804809.406559&cid=C0159JK877C) (the cluster might be gone/a different version later). With Redux devtools installed, go to the transactions details page and check `cachedData -> statements -> data -> statements -> the statement at index 5 -> key -> key_data -> transaction_fingerprint_id`, and that should be "0". The slack thread also contains an attachment of the Redux state.

This is not reproducible by checking out `5b78463ed2e7106a8477b63fa837564ad02bb510` (`22.1-rc`), building it, and running the demo database.

**Additional data / screenshots**
Note that as of reporting we currently only have a repro on a customer cluster, so be wary of screenshots.

**Environment:**
 - CockroachDB version: 22.1-rc, roachprod

Jira issue: CRDB-15168

**Comment by jocrl** [comment]
This happened a second time, with another of @dbist's clusters

**Comment by jocrl** [comment]
Ah, that's a good point!
The cluster has since been taken down, but that will be useful to see the next time this is reported. I'll add this to our runbook.
@kevin-v-ngo, my understanding is that `sql.stats.associate_stmt_with_txn_fingerprint.enabled` should usually be true, correct? I was wondering if we need some sort of UI messaging for when it is set to false (that the table should say hey, this is empty because this is turned off). But maybe not if it sounds like `sql.stats.associate_stmt_with_txn_fingerprint.enabled` would only be modified for troubleshooting purposes.

**Comment by xinhaoz** [comment]
An update on this:
The issue was improper statement stats recording for stmts in txns that encounter `txnUpgradeToExplicit`, which  would appear in situations where you create an explicit txn in a batch.
Releasing a fix this week.
