### ISSUE TITLE
Network throughput for rate limited RESTORE using GCS much higher than configured

### ISSUE THREAD

**Issue by jonstjohn** [cockroachdb/cockroach#81487]
**Describe the problem**

When using `RESTORE` from a Google Cloud Storage bucket that is rate limited using the cluster settings introduced in 22.1, the actual throughput as seen from the Google Cloud Platform console is much higher than configured. This appears to be due to a large amount of `ReadObject CANCELLED` requests.

Although rate limiting does not exist in 21.2, `RESTORE` from Google Cloud Storage exhibits the same high rate of `ReadObject CANCELLED` requests in that version.

**To Reproduce**

1. Deploy a cluster running 22.1
2. Set the cluster settings `cloudstorage.gs.read.node_rate_limit` and `cloudstorage.gs.read.node_burst_limit` equal to `25 MiB`.
3. Restore a backup (e.g., a table)
4. Log into the GCP console, navigate to Metrics Explorer.
5. Select GCS Bucket - Sent Bytes as the metric and filter by the bucket used.
6. Note that the `ReadObject CANCELLED` throughput is much higher than the `ReadObject OK` throughput.

Here is the output of 16 x 16 vCPU cluster configured with a 25 MiB/sec rate/burst limit:

<img width="1007" alt="Screen Shot 2022-05-09 at 10 50 28 AM" src="https://user-images.githubusercontent.com/95620/169166956-0d80fd81-bd49-40be-a4ee-37120df1180b.png">

**Expected behavior**

The rate limit cluster settings take into account `ReadObject CANCELLED` requests OR `ReadObject CANCELLED` requests should be a relatively small amount of the overall throughput.

**Additional data / screenshots**

See screenshot above.

**Environment:**
 - CockroachDB version 22.1.0-rc.1
 - Server OS: Linux
 - Client app: cockroach sql

**Additional context**

This issue makes it difficult effectively rate limit the network throughput for RESTORE operations.

Jira issue: CRDB-15162

**Comment by dt** [comment]
This looks like a known behavior of our rate limiters: we limit the rate at which we hand bytes to the cloud library or take bytes from it; if it then needs to retry internally, or otherwise read or write more bytes than it was handed / taken from it to serve that request, that is outside the scope of our limiter and something that would be up to some external limiter (firewall/qos mechanism) to enforce.
