### ISSUE TITLE
cdc: changefeeds don't behave correctly when a family consists only of part of a primary key

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#81494]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

```sql
root@:26257/defaultdb> create table splitpk (a int, b int, s string, family f1(a), family f2(b), family f3(s), constraint "primary" primary key (a,b));
CREATE TABLE


Time: 104ms total (execution 104ms / network 0ms)

root@:26257/defaultdb> insert into splitpk values (0,0,'apple');
INSERT 1


Time: 84ms total (execution 84ms / network 0ms)

root@:26257/defaultdb> create changefeed for splitpk with initial_scan='only',split_column_families;
table,key,value
splitpk.f1,"[0, 0]","{""after"": {""a"": 0}}"
splitpk.f3,"[0, 0]","{""after"": {""s"": ""apple""}}"
```

**Expected behavior**

Either family f2 should appear, or it shouldn't be possible to have a compound primary key across multiple families.

Jira issue: CRDB-15160

Epic CRDB-19180

**Comment by HonoreDB** [comment]
This occurs when there are no values in a family that aren't either part of a primary key or null. Fortunately there's really no reason I know of to split a primary key across column families, and especially not to put parts of it in families that don't contain anything else.

**Comment by amruss** [comment]
Options: 
- key in value for every column family (breaking change ) (does * for predicated mean every column in the family or also the primary key?)
- schema team removes the association of keys with families (https://github.com/cockroachdb/cockroach/issues/76604)
- Don't allow changefeeds on these edge cases
- do nothing

Team consensus: Do nothing on our end right now, special casein predicates to include primary key when selecting for all columns

**Comment by HonoreDB** [comment]
Still honestly not sure what the right fix is here (including whether or not it's a changefeed fix). But inclined to say that this is a weird enough schema that having weird behavior here isn't worth us erroring out or synthesizing extra events, so I'm fine to close.
