### ISSUE TITLE
sql: deprecate datestyle_enabled / intervalstyle_enabled

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#81529]
As of v22.1, the reasons for `datestyle_enabled` and `intervalstyle_enabled` no longer hold.

We should always assume this is `true` in the codebase, and removes all checks of these variables (they probably need to hang around for backwards compat).

Jira issue: CRDB-15100

**Comment by rafiss** [comment]
I added the `makeBackwardsCompatBoolVar` helper function, which should be used for this
