### ISSUE TITLE
kv: disallow allocator to place replica if constraints cannot be met

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#81544]
For hard data domiciling requirements, some users may want to choose data unavailability over availability but placing the replica outside of their constrained zones.

Example:

In the scenario where you have 4 regions, `us-east1`, `us-central1`, `us-west1`, `eu`
Let's say for the purpose of data domiciling we want to keep all our data within the US.
We update the zone configs using:
`alter table <table> configure zone using num_replicas = 3, constraints = '{+region=us-central1: 1, +region=us-east1: 1, +region=us-west1: 1}';`

If we then bring down the `us-east1` node/region, there is a scenario where we up-replicate to `eu` violating the data domiciling requirements.

The request here is to have some kind of flag or a field on the zone config such that if the constraints cannot be met, we allow the table to become underreplicated or unavailable.

Jira issue: CRDB-15083

**Comment by ajwerner** [comment]
I'd think so long as there were sufficient nodes available, we'd want to up-replicate extras to allowed regions before not up-replicating at all.

**Comment by RichardJCai** [comment]
> I'd think so long as there were sufficient nodes available, we'd want to up-replicate extras to allowed regions before not up-replicating at all.

Yeah the ask is to avoid up-replicating to "disallowed" regions.
