### ISSUE TITLE
build/teamcity: nightly Pebble metamorphic runs failed to create GH issue on failure

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#81546]
We had four nightly metamorphic test runs fail since 5/1, none of which created a corresponding issue on the Pebble repo notifying us of the failure. Typically, we get an issue like [this](https://github.com/cockroachdb/pebble/issues/1459).

For now I've created four separate issues manually so we can investigate:
- https://github.com/cockroachdb/pebble/issues/1695
- https://github.com/cockroachdb/pebble/issues/1696
- https://github.com/cockroachdb/pebble/issues/1697
- https://github.com/cockroachdb/pebble/issues/1698

Jira issue: CRDB-15081

**Comment by rickystewart** [comment]
Looking into why no issues were posted.

**Comment by rickystewart** [comment]
The scripts only post issues if `TC_BUILD_BRANCH` is one of `master`, `release-*`, or `provisional-*`. Looking in [the logs](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_Pebble_Metamorphic/5157803?buildTab=log&focusLine=15590&linesState=5123) I see this:

```
[06:01:08 ](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_Pebble_Metamorphic/5157803?buildTab=log&focusLine=15555&linesState=15555)  + [[ refs/heads/master == master ]]
[06:01:08 ](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_Pebble_Metamorphic/5157803?buildTab=log&focusLine=15556&linesState=15556)  + [[ refs/heads/master == release-* ]]
[06:01:08 ](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_Pebble_Metamorphic/5157803?buildTab=log&focusLine=15557&linesState=15557)  + [[ refs/heads/master == provisional_* ]]
```

So in other words the `TC_BUILD_BRANCH` is `refs/heads/master`, not `master` as expected. I think that is because up until today the trigger for these Pebble build configurations has been set to `+:refs/heads/master`, not `+:<default>` as with the other nightlies. I updated the trigger accordingly and will check tomorrow to see if `TC_BUILD_BRANCH` is updated accordingly.

**Comment by nicktrav** [comment]
Cool - thanks for digging into that @rickystewart!

Does the timeline line up with when this would have broken? It's hard to tell from the history, as these tests tend to fail infrequently, and some of the test history has since rolled. I believe the last time we got a hit was this one (https://github.com/cockroachdb/pebble/issues/1499), from back in Feb.

We also have some other nightlies, so it would be good to ensure those are set up to post too:
- Nightly Pebble Metamorphic (this one)
- Nightly Pebble Metamorphic Race
- Pebble Nightly YCSB
- Pebble Nightly YCSB Race
- Pebble Nightly Write Throughput

**Comment by bananabrick** [comment]
Aah, I may have changed this when I was setting up other nightly tests: `So in other words the TC_BUILD_BRANCH is refs/heads/master, not master as expected.`, and not forseen the consequence. If that is indeed the case, I apologize for creating the sudden influx of issues which need to be investigated.

**Comment by rickystewart** [comment]
I'm looking at the history of the build configuration and don't see anything that explains things breaking on or around 5/1. I also see @bananabrick's changes and I don't think they caused this, but I may be wrong.

> We also have some other nightlies, so it would be good to ensure those are set up to post too:

I have already looked through all the Pebble build configurations and updated the triggers to match up to the Pebble metamorphic trigger.

**Comment by rickystewart** [comment]
That change did not appear to do the trick so I have https://github.com/cockroachdb/cockroach/pull/81580.

**Comment by rickystewart** [comment]
Looks like the [change](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_Pebble_Metamorphic/5238507?buildTab=log&focusLine=7200&linesState=4774) worked:

```
[07:02:19 ]+ branch=master
[07:02:19 ]+ [[ master == master ]]
```

We should see it post issues next time.

**Comment by nicktrav** [comment]
Thank you!
