### ISSUE TITLE
Possibly incorrect subquery ordering.

### ISSUE THREAD

**Issue by dvarrazzo** [cockroachdb/cockroach#81631]
**Describe the problem**

Queries with an ordered sub-query don't seem to respect ordering in the outer level.

In the following example we try to extract some information from an enum type, including its labels _ordered in the labels order_. The enum definition, and its order, is:
```
create type strtestenum as enum ('ONE', 'TWO', 'THREE');
select enumlabel, enumsortorder from pg_enum where enumtypid = 'strtestenum'::regtype;
┌───────────┬───────────────┐
│ enumlabel │ enumsortorder │
├───────────┼───────────────┤
│ ONE       │             0 │
│ TWO       │             1 │
│ THREE     │             2 │
└───────────┴───────────────┘
```

In PostgreSQL the following query works well. The labels are ordered in the sub-query and aggregated in that order.
```
SELECT
    t.typname AS name, t.oid AS oid, t.typarray AS array_oid,
    array_agg(x.enumlabel) AS labels
FROM pg_type t
LEFT JOIN (
    SELECT e.enumtypid, e.enumlabel
    FROM pg_enum e
    ORDER BY e.enumsortorder
) x ON x.enumtypid = t.oid
WHERE t.oid = 'strtestenum'::regtype
GROUP BY t.typname, t.oid, t.typarray;

┌─────────────┬─────────┬───────────┬─────────────────┐
│    name     │   oid   │ array_oid │     labels      │
├─────────────┼─────────┼───────────┼─────────────────┤
│ strtestenum │ 9446137 │   9446136 │ {ONE,TWO,THREE} │
└─────────────┴─────────┴───────────┴─────────────────┘
```

In CRDB it seems that the internal ordering is discarded; the same query returns:
```
┌─────────────┬────────┬───────────┬─────────────────┐
│    name     │  oid   │ array_oid │     labels      │
├─────────────┼────────┼───────────┼─────────────────┤
│ strtestenum │ 100098 │    100099 │ {ONE,THREE,TWO} │
└─────────────┴────────┴───────────┴─────────────────┘
```

In order to get the right result, you need to do something more cumbersome: aggregate, order, then include the result as a single field.

```
SELECT t.typname AS name, t.oid AS oid, t.typarray AS array_oid, (
    SELECT array_agg(enumlabel) AS labels
    FROM (
        SELECT enumlabel FROM pg_enum
        WHERE enumtypid = 'strtestenum'::regtype
        ORDER BY enumsortorder)
    m)
FROM pg_type t WHERE t.oid = 'strtestenum'::regtype;
```

Three levels of sub-queries instead of two.

**Environment:**
 - CockroachDB CCL v21.2.10 
 
**Additional context**

Requires a more complex query in psycopg 3.1 enum support (but, tbh, I have relied countless times on the correct ordering of sub-queries).

Jira issue: CRDB-15994

**Comment by dvarrazzo** [comment]
This variant is probably simpler and works in both dbs the same way:
```
SELECT name, oid, array_oid, array_agg(label) AS labels
FROM (
    SELECT
        t.typname AS name, t.oid AS oid, t.typarray AS array_oid,
        e.enumlabel AS label
    FROM pg_type t
    LEFT JOIN  pg_enum e
    ON e.enumtypid = t.oid
    WHERE t.oid = 'strtestenum'::regtype
    ORDER BY e.enumsortorder
) x
GROUP BY name, oid, array_oid;
```
but please let me know if the expectation that the first query works as expected is wrong.

**Comment by dvarrazzo** [comment]
In retrospective, no, I don't think that my query was correct. I have used sorted subqueries many times, yes, but that one is a join: I could understand if that operation didn't maintain the order.

I have checked a similar query we use (for composite types) and it doesn't aggregate before the join: this one was just badly written.

I'll leave this here if you want to double-check against SQL specs, but feel free to close if your behaviour is correct.

**Comment by msirek** [comment]
Hi @dvarrazzo, while an ORDER BY in a subquery or derived table maybe be useful in some cases, like in combination with a LIMIT expression to get the n highest or lowest values, that ordering is not a requirement placed on the final result set, so there is no guarantee or even expectation that that ordering would be preserved outside of the derived table.  Like in the case of SELECT ... ORDER BY ... LIMIT n, the array_agg expression must occur in the same query block as the ORDER BY.  If I understand the point of this query, it's trying to apply an ordering within each group, and not necessarily a global ordering.  To achieve this, you could write the query as a window function with a PARTITION BY clause:
```
SELECT t.typname AS name, t.oid AS oid, t.typarray AS array_oid,
       array_agg(e.enumlabel) OVER (PARTITION BY t.typname, t.oid, t.typarray ORDER BY e.enumsortorder) AS labels
    FROM pg_type t
    LEFT JOIN  pg_enum e
    ON e.enumtypid = t.oid
    WHERE t.oid = 'strtestenum'::regtype;
```

**Comment by dvarrazzo** [comment]
Hi @msirek,

I think we wrote at the same time. You are right, that query was probably refactored badly and ended up incorrect. Maybe postgres was happening to return it as expected, but just as a matter of chance (implementation detail of a small table and that particular plan...) So it was probably an accident waiting to happen.

Closing it here, thank you for looking into it!

**Comment by msirek** [comment]
Sure.  Yes, I've seen other issues where postgres happens to maintain the ordering, and applications rely on that behavior.  But I don't think it's documented or guaranteed behavior.

**Comment by rafiss** [comment]
As you've said, Postgres seems to preserve ordering across subquery results, even though that behavior is not documented. We have seen other tools rely on this behavior (e.g. https://github.com/cockroachdb/cockroach/issues/68211), so we added the `propagate_input_ordering` option in https://github.com/cockroachdb/cockroach/pull/68295. My understanding is there is a somewhat significant performance to use it, so I'd only recommend it if it's needed to get a test to pass, and not for production use.
