### ISSUE TITLE
opt: skip copy and re-optimization for simple queries

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#81639]
When executing prepared statements such as `INSERT INTO t VALUES ...`, the optimizer can be responsible for up to 50% of CPU time of the statement, as seen in this flame graph of `BenchmarkSQL/Cockroach/Insert/count=100` modified to use prepared statements:

![image](https://user-images.githubusercontent.com/43821/169698412-ca3e663b-e5be-4b42-8f08-bfd5780744a9.png)

The majority of the CPU time in the optimizer in this example is spent copying the cached prepared memo to replace placeholders, and then re-running the optimizer on the fresh memo.

However, for a simple query like `INSERT INTO t VALUES ...` with only constants and placeholders in the `VALUES` clause, we should be able to know ahead of time with complete certainty (I think!) that re-optimizing the memo will produce no change at all in the resulting plan. If we have that fact available, then we can completely skip copying the memo, and instead let the execbuilder be the one to replace placeholders with constants on the fly during its job of creating the executable plan.

I wrote a hacky prototype of this to validate the claim, and see what seems like it could be an impactful result: 33% CPU time saved in the benchmark above.

```
[22:35]% benchstat old.txt new.txt
name                               old time/op    new time/op    delta
SQL/Cockroach/Insert/count=100-32    1.06ms ±40%    0.71ms ± 5%  -33.21%  (p=0.000 n=10+9)

name                               old alloc/op   new alloc/op   delta
SQL/Cockroach/Insert/count=100-32     433kB ±26%     321kB ±33%  -25.92%  (p=0.001 n=10+10)

name                               old allocs/op  new allocs/op  delta
SQL/Cockroach/Insert/count=100-32     2.52k ±23%     2.08k ±29%     ~     (p=0.063 n=10+10)
```

This idea is similar to what we do with the placeholder scan operator, but targets plans that we statically can know won't improve with re-optimization, rather than plans that require a particular re-optimization that we know of ahead of time.

I think a principled version of this hack would be to implement some kind of check that we run during creation of a prepared memo that can be later used to decide whether we need to copy and re-optimize at all.

Jira issue: CRDB-16002

**Comment by jordanlewis** [comment]
The hacky prototype mentioned above is available here: #81640

**Comment by cucaroach** [comment]
In https://github.com/cockroachdb/cockroach/issues/52071 @RaduBerinde outlines an approach for COPY that in addition to skipping the optimizer would avoid round trips down into the execution engine and back for each row (this is my current understanding of how batched inserts work).   I think that can be done in such a way that prepared batch inserts (and maybe other mutations as well) could also take advantage of it as well.  I'm still getting my head around it but I think it will work.  Another way to look at it conceptually is that all the rows are inserted into a temporary table and an INSERT INTO targetTable SELECT * FROM temptable is performed, although in CRDB a scanBufferNode would serve as the temp table.  Would love to hear your thoughts on that approach.

**Comment by jordanlewis** [comment]
Oh yeah, I forgot about those ideas. This approach would give a similar set of gains to `COPY` as it would to normal inserts without changes to `COPY`, as long as `COPY` uses prepared statements.

I think that between these two approaches the "skip the optimizer" optimization would produce pretty much the same result, but the approach in this issue is more general and would provide benefits to more than just `COPY`. I also think (with medium confidence) that refactoring `COPY` might be somewhat challenging due to how complex/hairy the `COPY` codepath is. I think `COPY` also has a few modes of execution that would need to be reimplemented (like `COPY` to file, and `COPY` with and without an outer transaction).  For these reasons I prefer this issue's approach, though I'm very possibly missing things and all else being equal would be happy to see the other approach taken too.

The "skip parts of the execution engine" optimization of having a special operator feed the `INSERT` operator on the fly might be promising, but we've got to be careful. In particular, we would have to be careful about concurrent schema changes.

In the current approach of COPY, there are two modes. The first is with a transaction that wraps the entire COPY, in which case we don't need to worry about a schema change completely finishing and invalidating the COPY. The second is with no transaction, in which case the COPY creates a new txn for each batch. In that case, the first phase of the optimizer protects us from schema changes - if an incompatible schema change broke a COPY in the middle, the optimizer would notice in between batches and return an error. If we instead had some kind of opaque row writer operator that had to start and stop txns to keep performance equivalent, without some extra schema checking we'd get into trouble. And it's possible that adding that extra schema checking would get us back to the original performance regime - and at the very least it'd be duplicating functionality that the optimizer already does today, and putting it into this special case opaque operator.

All that being said, I'm more optimistic about the approach in this issue just in general. I think it's a relatively smaller and simpler change that gets the lion's share of the improvements from the other issue. I think if the other issue demonstrated a significantly larger performance improvement than the ~33% this issue represents, it could be worth pursuing despite the special-case nature of optimizing just COPY. But I'm skeptical that we'd see more than, say an extra 20% on top of the 33% that's available just from skipping the copy/reoptimize phase of the optimizer. And as a result I'm just not sure all the extra special-case changes would be worth it.

**Comment by cucaroach** [comment]
Sound like a good approach, if COPY ends up being way faster than prepared batches we can re-visit.  There's no reason we can't get there in steps and cutting out the optimizer is a good first step.

**Comment by andreimatei** [comment]
> This idea is similar to what we do with the placeholder scan operator, but targets plans that we statically can know won't improve with re-optimization, rather than plans that require a particular re-optimization that we know of ahead of time.

@michae2 this is the the optimization that you were telling me is missing from inserts, updates and deletes, right?

**Comment by mgartner** [comment]
Generic query plans should address the problems here. See [the RFC](https://github.com/cockroachdb/cockroach/pull/117284).
