### ISSUE TITLE
kv: test first-range eviction

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#8164]
When an update to the first-range is received via gossip we evict it from the cache. See #8163. I poked around unsuccessfully in the `kv` package trying to test this. We definitely need coverage here. Failure to evict the first range causes eventual data unavailability when the first range is rebalanced.

**Comment by petermattis** [comment]
@tschottdorf Advice on how to test this would be appreciated. I tried copying the approach of `TestEvictCacheOnError`, but that test does enough weird stuff (e.g. range 1's start key isn't `keys.MinKey`) that I couldn't get a test working.

**Comment by tschottdorf** [comment]
I'm not seeing the difficulty in testing this, but I may just not see it. Want me to take this one? Looks like a small enough task for me to tackle at some point before I head out on vacation this Wednesday. If I fail, at least I'll re-emerge with some more solid advice.

**Comment by petermattis** [comment]
Sure, I'm more than happy for someone else to tackle this. The difficulty is probably make lack of familiarity with the `kv` test infrastructure.

**Comment by petermattis** [comment]
PS The test I was trying to write was straightforward: perform an op that causes the first-range to be cached, retrieve the first-range from the cache and verifies it matches our expectations, gossip a new first-range and verify it is no longer in the cache.
