### ISSUE TITLE
sql: serial types information schema contradict docs

### ISSUE THREAD

**Issue by hedwigz** [cockroachdb/cockroach#81659]
**Describe the problem**
In the [docs](https://www.cockroachlabs.com/docs/stable/serial.html#generated-values-for-mode-sql_sequence-and-sql_sequence_cached), the type `SERIAL2` and `SMALLSERIAL` should become `INT2/SMALLINT` but in the information schema they become `BIGINT`.

**To Reproduce**
```sql
CREATE TABLE public.serial (
  id INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  b SMALLSERIAL,
  i SERIAL2,
  h SERIAL4,
  g SERIAL8,
  a BIGSERIAL,
  j SERIAL,
  CONSTRAINT "primary" PRIMARY KEY (id ASC)
);
SELECT column_name,
  data_type
FROM "information_schema"."columns"
WHERE table_name = 'serial';

 column_name | data_type 
-------------+-----------
 id          | bigint 
 b           | bigint 
 i           | bigint 
 h           | bigint 
 g           | bigint 
 a           | bigint 
 j           | bigint 
(7 rows)
```

What did you do? Describe in your own words.
created a table with different serial types, then queried the information schema.

**Expected behavior**
According to docs, the types should be different. This is the output from postgres 13:
```
 column_name | data_type 
-------------+-----------
 id          | bigint 
 b           | smallint 
 i           | smallint 
 h           | integer 
 g           | bigint 
 a           | bigint 
 j           | integer 
(7 rows)
```

**Environment:**
 - CockroachDB version: v21.2.10
 - Server OS: Linux
 - Client app: Datagrip/usql

Jira issue: CRDB-16017

**Comment by rafiss** [comment]
This is definitely a bit of a confusing area. The "actual" value used for SERIAL-related types depends on the `serial_normalization` setting. If you set it to `sql_sequence` or `sql_sequence_cached` then it will use the corresponding INT type. But for `rowid` and `virtual_sequence` CRDB must always use an `INT8` since it needs to use the `unique_rowid()` function to generate values.

**Comment by rafiss** [comment]
I'll close this based on my answer above. Please comment and reopen if there's still an issue.
