### ISSUE TITLE
last execution showing wrong value

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#81682]
Reported by @smcvey on [slack](https://cockroachlabs.slack.com/archives/C0159JK877C/p1653335404898869):

The ‘Last Execution Time’ appears to be May 23, 2022 20:05.  There’s two problems with that, the first is that date is in the future if it’s meant to be displayed in UTC.  The second issue is that it does not update when I run a new INSERT .

Steps to reproduce:
1. Fresh 22.1.0 cluster 
2. create table my_table(id uuid primary key);
3. insert into my_table select gen_random_uuid() from generate_series(1, 100000);
4. Repeat step 3 a few times

Jira issue: CRDB-16030

**Comment by smcvey** [comment]
Did another test and Last Execution shows: May 23, 2022 22:05.  The cluster was started fresh at 2022-05-23 21:07  So the Last Execution time is before the cluster's creation.
