### ISSUE TITLE
sql: wrong error code when failing to add a NOT NULL column

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#81692]
**Describe the problem**

We should return 23502 (not null violation) but instead we return 23514 (check constraint violation).

**To Reproduce**

```sql
create table foo (i INT);
insert into foo values (1), (2), (NULL);
alter table foo add column j int generated always as (i+1) stored not null;
```

```
ERROR: validation of column "j" NOT NULL failed on row: i=NULL, rowid=865427685292081153, j=NULL
SQLSTATE: 23502
```

To fix: find where this error message is created in the code, then change the error code.

Jira issue: CRDB-16032

**Comment by raisa2010** [comment]
Hello, I would like to work on this for my first contribution if that's okay (:

**Comment by Yash-C-330** [comment]
It's showing SQL state: 23502 isn't it correct then?

**Comment by rafiss** [comment]
There's no issue here, I think this might have been fixed since it got filed. `23502` is the code for not-null violation, and it is the correct one to use, and it's the one we are currently returning for this example.
