### ISSUE TITLE
sql/schemachanger: properly validate NOT NULL columns

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#81690]
**Describe the problem**

At time of writing, the declarative schema changer does not validate the `NOT NULL` nature of newly added columns. The change in https://github.com/cockroachdb/cockroach/pull/81679 captures most of what is necessary: push the logic into the index backfiller. The remaining case that needs to be covered is validating the `NOT NULL` nature of virtual computed columns, which is being handled separately for the legacy schema changer. 

Jira issue: CRDB-16031

Epic CRDB-43310

**Comment by postamar** [comment]
Presently the nullness of the column is in `scpb.ColumnType`, which is wrong, instead it should be in some constraint element. This constraint should then be validated.

**Comment by rafiss** [comment]
This was resolved by db616e979827d4be9cb37cb13235a94075a52c6d, first released in v24.1.0.
