### ISSUE TITLE
'Unable to find statement' on Statement Details page

### ISSUE THREAD

**Issue by smcvey** [cockroachdb/cockroach#81697]
**Describe the problem**

Selecting a statement on from SQL Activity->Statements on the DBConsole page leads to an error message.

<img width="1558" alt="Screenshot 2022-05-23 at 23 09 29" src="https://user-images.githubusercontent.com/28270695/169914937-019f3fa8-8739-40e6-a450-52d46765d85d.png">

<img width="456" alt="Screenshot 2022-05-23 at 23 09 51" src="https://user-images.githubusercontent.com/28270695/169914948-68b8850b-9e2b-4a6f-be1e-8386b711c9a8.png">

**To Reproduce**

Start with a fresh 3-node 22.1.0 cluster.  Connect via `cockroach sql` and run these commands:

```
create table shaun(id uuid primary key);
insert into shaun select gen_random_uuid() from generate_series(1, 100000);
insert into shaun select gen_random_uuid() from generate_series(1, 100000);
insert into shaun select gen_random_uuid() from generate_series(1, 100000);
insert into shaun select gen_random_uuid() from generate_series(1, 100000);
select * from shaun;
```

Then go to the DBConsole and find the `SELECT * FROM shaun` statement.  Click on that.

Related issues:
https://github.com/cockroachdb/cockroach/issues/84081
https://github.com/cockroachdb/cockroach/issues/83608

Jira issue: CRDB-16487

**Comment by maryliag** [comment]
The link for the particular details was https://172.28.128.21:8080/#/statement/true/1096233959522337035?appNames=
and the stats of that one on `crdb_internal.statement_statistics` was
```
2022-05-23 22:00:00+00 
| \x0f6\x9a\xfad\f\x81\x0b   
| \xa0U\'\xb6\xe2\r6\xd4    
| \xf1\xea\x9e\xcd\xf4\xb6@! 
| $ cockroach sql 
| {"db": "defaultdb", "distsql": true, "failed": false, "fullScan": true, "implicitTxn": true, "query": "SELECT * FROM shaun", "querySummary": "SELECT * FROM shaun", "stmtTyp": "TypeDML", "vec": true}                                                                                                                                  
| {"execution_statistics": {"cnt": 1, "contentionTime": {"mean": 0, "sqDiff": 0}, "maxDiskUsage": {"mean": 0, "sqDiff": 0}, "maxMemUsage": {"mean": 10578258, "sqDiff": 0}, "networkBytes": {"mean": 0, "sqDiff": 0}, "networkMsgs": {"mean": 0, "sqDiff": 0}}, "statistics": {"bytesRead": {"mean": 19221984, "sqDiff": 0}, "cnt": 1, "firstAttemptCnt": 1, "lastExecAt": "2022-05-23T22:07:57.135513435Z", "maxRetries": 0, "nodes": [1], "numRows": {"mean": 4E+5, "sqDiff": 0}, "ovhLat": {"mean": 0.0000053370000001606854, "sqDiff": 0}, "parseLat": {"mean": 0.000082629, "sqDiff": 0}, "planGists": ["AgHQAQIAAQAAAAYC"], "planLat": {"mean": 0.000116875, "sqDiff": 0}, "rowsRead": {"mean": 4E+5, "sqDiff": 0}, "rowsWritten": {"mean": 0, "sqDiff": 0}, "runLat": {"mean": 2.453826465, "sqDiff": 0}, "svcLat": {"mean": 2.454031306, "sqDiff": 0}}}                                                                                                       
| {"Children": [], "Missing Stats": "", "Name": "scan", "Spans": "FULL SCAN", "Table": "shaun@shaun_pkey"}                                                                                                                                          
| 01:00:00
```

I suspect it has something to do with the ID (during the development of this new URL format, I had a few errors if the ID was too big, which I was able to fix, but maybe there is still a problem with a few particular IDs)

**Comment by xinhaoz** [comment]
This is caused by https://github.com/cockroachdb/cockroach/issues/83608.
Fix coming soon!
