### ISSUE TITLE
storage: disk write mib/s metric overcounts by 2x on RAID0

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#81732]
**Describe the problem**

Create AWS instance with gp3 storage (500gb), apt install fio, then

```
fio --rw=write --name=test --direct=1 --bs=1024k --size 1mb --ioengine=libaio --iodepth=4 --directory=/mnt/data1/cockroach/auxiliary --rate=0,300m --time_based --timeout 2400h
```

both `fio` and `iotop` will report ~160mb/s, but a CRDB cluster will report ~320mb/s in the "Disk Write MiB/s" metric.

**Expected behavior**

I expect the numbers to match and reflect the true number.

**Additional data / screenshots**

**Environment:**
 - master at time of writing

**Additional context**

A 2x discrepancy can seriously derail an investigation because we often try to match up the observed throughput with the provisioned throughput of the volume.

Jira issue: CRDB-16046

**Comment by tbg** [comment]
I'm seeing this everywhere, so I think it's real. [slack](https://cockroachlabs.slack.com/archives/CAC6K3SLU/p1654164196701979?thread_ts=1654153265.215669&cid=CAC6K3SLU)

**Comment by petermattis** [comment]
Could we (or gosigar) be doing something silly like summing both the stats for both the disk partition and the whole disk?

**Comment by tbg** [comment]
Probably. Top three lines is our metrics, bottom lines are node_exporter. Node how node_exporter gives us six sources, two per store.

<img width="2138" alt="image" src="https://user-images.githubusercontent.com/5076964/171661152-abe5f67b-5d26-4510-8081-8f577af0d290.png">

**Comment by tbg** [comment]
our read byte rate divided by two matches up fairly well with node_exporter's read byte rate for md0 (/mnt/data1/cockroach):

<img width="2152" alt="image" src="https://user-images.githubusercontent.com/5076964/171662171-f10ffaa1-e6af-4661-ba5a-598cc196a90d.png">

Ok, must be the RAID0:

```
nvme1n1     259:0    0   500G  0 disk
└─md0         9:0    0 592.9G  0 raid0 /mnt/data1
nvme2n1     259:1    0  93.1G  0 disk
└─md0         9:0    0 592.9G  0 raid0 /mnt/data1
nvme0n1     259:2    0    10G  0 disk
```

I'm not sure why there is a RAID0 there. This would also mess up the prom metrics since we'd accidentally aggregate over things and double-count just the same.

**Comment by tbg** [comment]
I think we figured it out: the experiment was accidentally running on a RAID0, and we were comparing the throughput of one of the two disks with what CRDB reports. I'm still not clear what CRDB reports but hopefully it's the aggregate write throughput.

**Comment by Santamaura** [comment]
Hey @tbg correct me if i'm wrong but wouldn't those metrics be aggregated [here](https://github.com/cockroachdb/cockroach/blob/969bcf747a9f87f5231a043c9833c51d9979a549/pkg/server/status/runtime.go#L626) with the values coming from [here](https://github.com/cockroachdb/cockroach/blob/969bcf747a9f87f5231a043c9833c51d9979a549/pkg/server/status/disk_counters.go#L23)?
If so I'm not sure what we should do to fix this

**Comment by tbg** [comment]
I actually think we might have been reporting the correct numbers. I wasn't realizing there was a RAID0 at the time, so I was comparing the throughput as reported by *one* of the disks to what is reported by CRDB (which should be the throughput of the entire RAID0, i.e. both disks).

Closing out.
