### ISSUE TITLE
storage: Monitor `processRaft` goroutine

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#8175]
We should export metrics from `Store.processRaft` to track how this goroutine (which is a bottleneck for many operations) is spending its time. Specifically, we need ~3 metrics:
- `process-raft.waiting`: Time spent blocking in `select`
- `process-raft.working`: Time in the loop before the select (which is mainly spent in `handleRaftReady`)
- `process-raft.ticking`: Time spent in the `ticker` branch of the `select`

**Comment by tschottdorf** [comment]
Is the number of replicas processed in each iteration (and perhaps whether they're uninitialized) relevant?

**Comment by petermattis** [comment]
Somewhat tangential, but should we parallelize ticking the replicas? I made a change to do so, but didn't see any performance benefit in the tests I was running.

**Comment by bdarnell** [comment]
I don't see an immediate use for tracking the number of replicas per iteration (I think there's going to be too much noise from the current tick handling)

Tick is a fairly cheap operation so I don't think it makes sense to parallelize it. If the tick phase is taking up too much time, the best fix is going to be to add interfaces to `etcd/raft` so we can ask it for the next time-based event and put all the replicas in a priority queue so we don't have to touch all of them on every tick.
