### ISSUE TITLE
cloud storage: detect non-Amazon S3 service

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/cockroach#81766]
#### Background

Users have reported failures when using “S3 compatible” cloud storage services, such as [MinIO](http://min.io/) and [Hitachi Content Platform](https://www.hitachivantara.com/en-us/products/storage/object-storage/content-platform.html) (HCP).

Per our [docs](https://www.cockroachlabs.com/docs/stable/use-cloud-storage-for-bulk-operations.html), CRDB does not test against these services. We’ve learned that 100% compatibility is not always achieved, leading to failures.

#### Suggestion

Try to detect a non-Amazon S3 service, and warn / log. We might be able to do this via the provided `s3://` URL, or via a response header of some sort.

Jira issue: CRDB-16148

**Comment by andrewbaptist** [comment]
One "cleaner" idea for this is to document the set of calls (and parameters on the calls) that we support and create a mini-compliance test. S3 for object storage is similar to PostgreSQL for databases. It is a de facto standard, and almost no non-Amazon object storage system is 100% compatible. However, as long as it's not getting into some of the more esoteric parts (IAM/SSO, Encryption, transfers between sites, service classes, ...), most Amazon competitors should work as targets. I agree the warning is good, but better is a way for them to know if it will work without having to contact CRL

**Comment by msbutler** [comment]
indeed! @shermanCRL perhaps we close this issue, and let https://github.com/cockroachdb/cockroach/issues/81825 be the main issue.

**Comment by shermanCRL** [comment]
Sounds good, thanks.
