### ISSUE TITLE
stability: investigate periodic drop in zerosum throughput

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#8176]
See the [attached output](https://github.com/cockroachdb/cockroach/files/393981/out.txt), generated using `rm -fr cockroach-data && zerosum -a 10000 -m 3 -c flappy`.

Starting a 4m23s there is a 44s window of 0 throughput. Given the nature of the test (each worker randomly chooses a node to send to for each request) this usually indicates 1 node is not processing requests. I haven't done any investigation yet, but it is suspicious that that throughput drop always occurs when a node is down. Perhaps we're losing quorum for a range, but that brings up the question of why we're not at full replication when all of the nodes are up.

**Comment by petermattis** [comment]
When a node starts up, the connection to the local node becomes healthy before connections to remote nodes. This causes `kv.grpcTransport` (via `kv.splitHealthy`) to preferentially send requests to the local node when we don't know who the lease holder is (and we don't know the lease holders at startup). So at startup, any request to a range which has a replica on the node starting up will usually be sent locally. But the local replicas are often behind and have to wait for the replica to catch up before they can even determine who the lease holder is.

A node determines the lease holder by making a `RequestLease` request that goes through Raft. But that request requires the node to know who the Raft leader which isn't true until a bit of communication from the leader. So there is a delay at startup in determining lease holders by the newly started node.

@tschottdorf, @bdarnell Any thoughts as to how we can mitigate this? Could we make determination of the lease holder occur before the local replica can propose a raft command? Or not consider the local connection healthy until replicas have caught up? Can we fail lease acquisition early if we don't know who the Raft leader is? These all sound dangerous to various degrees. I'm brainstorming here.

**Comment by tschottdorf** [comment]
Is your second post related to the first one in this thread? If it is, then we should do something here, but what you're describing sounds (roughly) like a node which boots must wait for approximately the Raft heartbeat interval before it can be expected to make progress. That doesn't seem like an issue in practice, and while there are ways around it, I don't think it's worth the complexity (lease transfers would also be easiest to make correct by simply waiting a bit before opening the server to the world).

For making test agents like `flappy` more realistic, we'd really want an endpoint we can poll for "full cluster health" (which can mean many things but at least it should mean that we're reasonably certain that all ranges are at full replication).

**Comment by petermattis** [comment]
The two posts are related in that I'm performing the same test. The second post was an actual attempt at diagnosis while the first was speculative. If a node was able to come up and start serving traffic with approximately a Raft heartbeat interval I would be happy. What I'm seeing is that a node comes up and is unable to serve traffic for ~3-10s. I need to add some more instrumentation here to understand what is going on. 

The `flappy` agent only kills one node at a time and pauses 15-45s between actions. I would have thought that time period was sufficient for a cluster to come back to healthy. Perhaps it isn't. But note I was speculating in the first post that we were experiencing quorum loss. The problem could be something else. And note that in the second post, we only went through a single kill/restart cycle, so there definitely wasn't quorum loss there.

Agreed that it would be nice to be able to wait for "full cluster health". Working on this stuff might motivate me to add that.

**Comment by petermattis** [comment]
Looking at another run. The first SQL request to succeed on the restarted node shows the following:

```
     0.030ms      0.000ms    executing 1/1: BEGIN TRANSACTION
     0.036ms      0.006ms    BEGIN done
     0.444ms      0.408ms    executing 1/1: SAVEPOINT cockroach_restart
     0.788ms      0.344ms    preparing: SELECT id, balance FROM accounts WHERE id IN ($1, $2)
     0.903ms      0.115ms    meta descriptor lookup
     0.908ms      0.005ms    looked up range descriptor from cache
     0.921ms      0.012ms    sending RPC to [/Min, /Table/11)
  3002.923ms   3002.002ms    error, trying next peer: range 1: replica node_id:2 store_id:2 replica_id:2  not lease holder; <nil> is
  3014.656ms     11.733ms    executing 1/1: SELECT id, balance FROM accounts WHERE id IN ($1, $2)
  3014.753ms      0.098ms    meta descriptor lookup
  3014.758ms      0.005ms    looked up range descriptor from cache
  3014.774ms      0.017ms    sending RPC to [/Table/51, /Table/51/49)
  6016.805ms   3002.031ms    error, trying next peer: range 7: replica node_id:2 store_id:2 replica_id:3  not lease holder; <nil> is
  6017.449ms      0.644ms        node 1
  6017.453ms      0.004ms        executing 2 requests
  6017.458ms      0.004ms        read-only path
  6017.669ms      0.211ms        request range lease (attempt #1)
  6022.105ms      4.436ms        command queue
  6025.385ms      3.280ms    SELECT 2 done
  6025.563ms      0.178ms    preparing: UPSERT INTO accounts VALUES ($1, $3), ($2, $4)
  6025.934ms      0.371ms    executing 1/1: UPSERT INTO accounts VALUES ($1, $3), ($2, $4)
  6026.143ms      0.209ms    meta descriptor lookup
  6026.148ms      0.005ms    looked up range descriptor from cache
  6026.165ms      0.016ms    sending RPC to [/Table/51, /Table/51/49)
  6820.516ms    794.351ms    error, trying next peer: range 7: replica node_id:2 store_id:2 replica_id:3  not lease 
```

Why are those lease acquisitions timing out? At least, I think they are timing out giving they are taking almost exactly 3 seconds. Still digging.

**Comment by petermattis** [comment]
Ok, looks like the other nodes are sending raft heartbeats and messages very quickly to the newly started node. But something is going wrong. In the logs below we see the messages for `range 7`:

```
I160802 22:07:28.443254 raft/raft.go:469  [range 7] 2 became follower at term 7
I160802 22:07:28.443556 raft/raft.go:238  [range 7] newRaft 2 [peers: [1,2,3], term: 7, commit: 25152, applied: 25152, lastindex: 25169, lastterm: 7]
I160802 22:07:28.780022 storage/store.go:2352  store=2:2 range=7 MsgHeartbeat from {4 4 3}
I160802 22:07:28.780043 storage/store.go:2352  store=2:2 range=7 MsgHeartbeat from {4 4 3}
I160802 22:07:28.780056 storage/store.go:2352  store=2:2 range=7 MsgHeartbeat from {4 4 3}
I160802 22:07:28.780070 storage/store.go:2352  store=2:2 range=7 MsgHeartbeat from {4 4 3}
I160802 22:07:28.780081 storage/store.go:2352  store=2:2 range=7 MsgHeartbeat from {4 4 3}
I160802 22:07:28.780095 storage/store.go:2352  store=2:2 range=7 MsgHeartbeat from {4 4 3}
I160802 22:07:28.780106 storage/store.go:2352  store=2:2 range=7 MsgHeartbeat from {4 4 3}
I160802 22:07:28.793605 storage/raft.go:129  store 2: range 7 raft ready
I160802 22:07:29.238395 raft/raft.go:821  [range 7] 2 [logterm: 0, index: 25425] rejected msgApp [logterm: 7, index: 25425] from 3
```

Lots more of the `msgApp` rejected stuff, but that is to be expected as the replica is behind. More interesting are these logs:

```
I160802 22:07:29.597025 storage/replica.go:1993  store=2:2 range=7 [/Table/51-/Table/51/23): applying command with forced error: storage/replica.go:1945: command observed at lease index 26767, but required < 26759
E160802 22:07:29.597210 storage/replica.go:2028  store=2:2 range=7 [/Table/51-/Table/51/23): error executing raft command: storage/replica.go:1945: command observed at lease index 26767, but required < 26759
```

I could 554 of these "rare" log messages over the following 10 seconds. The error is generated by this code:

```
		// The command is trying to apply at a past log position. That's
		// unfortunate and hopefully rare; we will refurbish on the proposer.
		// Note that in this situation, the leaseIndex does not advance.
		forcedErr = roachpb.NewErrorf("command observed at lease index %d, "+
			"but required < %d", leaseIndex, raftCmd.MaxLeaseIndex)
```

Still trying to grok what this means.

**Comment by bdarnell** [comment]
The message has to do with our replay protection. When the raft leader and lease holder are not the same and proposal messages get reordered in transit, you would see this message. This might happen if RaftTransport streams are getting closed and reopened a lot; are you seeing those messages?

**Comment by petermattis** [comment]
I added some additional logging, but I'm not seeing RaftTransport stream getting closed and reopened a lot once the node is restarted. I did find a bug in our circuit breaking (see #8290), though, but fixing it didn't help.

**Comment by petermattis** [comment]
Ok, this is weird. Something is really funky with range 7. This is the first range of the SQL table the test is using and it is always the one have problems when the node restarts. I think this is because the verifier does a table scan which always hits range 7 first. The weird part is that the `command observed lease at index` errors. This is from node 1 (which is not the node that was killed and restarted):

```
~/Development/go/src/github.com/cockroachdb/cockroach pmattis/zerosum-investigation grep 'command observed' cockroach-data/1/logs/stderr | egrep -o 'range=[0-9]+' | sort | uniq -c
   4 range=1
   3 range=18
   2 range=24
   2 range=26
   2 range=32
   2 range=34
   2 range=4
   2 range=45
   2 range=53
1005 range=7
   2 range=74
```

So we see a smattering of these errors for other ranges and an overwhelming number for range 7. And note that a distinct chunk of these (~350) occurred before we killed node 3.

**Comment by petermattis** [comment]
What's so special about range 7? I turned off both the verifier (which does a table scan every 10 seconds) and the consistency checker (which does a full consistency check every 20 seconds) and I still see an abnormal number of these `command observed at lease index` errors.

**Comment by petermattis** [comment]
I've now turned off the monkeys (splits and lease transfers) and chaos and I'm still seeing this error. As far as I can tell, we're not opening and closing streams. 

Digging more. Added some logging to `Replica.prepareRaftCommandLocked` and `Replica.processRaftCommand`. The first occurrence of the `observed lease at index` error occurs with this log sequence:

```
I160803 21:05:19.992444 storage/replica.go:1435  store=1:1 range=7 [/Table/51-/Max): prepared command: maxLeaseIndex=2094 leaseAppliedIndex=2078
...
I160803 21:05:20.007825 storage/replica.go:1887  store=1:1 range=7 [/Table/51-/Max): processing command: maxLeaseIndex=2094
I160803 21:05:20.008035 storage/replica.go:1887  store=1:1 range=7 [/Table/51-/Max): processing command: maxLeaseIndex=2095
I160803 21:05:20.008191 storage/replica.go:1887  store=1:1 range=7 [/Table/51-/Max): processing command: maxLeaseIndex=2096
I160803 21:05:20.008394 storage/replica.go:1887  store=1:1 range=7 [/Table/51-/Max): processing command: maxLeaseIndex=2097
I160803 21:05:20.008536 storage/replica.go:1887  store=1:1 range=7 [/Table/51-/Max): processing command: maxLeaseIndex=2098
I160803 21:05:20.008674 storage/replica.go:1887  store=1:1 range=7 [/Table/51-/Max): processing command: maxLeaseIndex=2099
I160803 21:05:20.008811 storage/replica.go:1887  store=1:1 range=7 [/Table/51-/Max): processing command: maxLeaseIndex=2100
I160803 21:05:20.008962 storage/replica.go:1887  store=1:1 range=7 [/Table/51-/Max): processing command: maxLeaseIndex=2101
I160803 21:05:20.009112 storage/replica.go:1887  store=1:1 range=7 [/Table/51-/Max): processing command: maxLeaseIndex=2102
I160803 21:05:20.010004 storage/replica.go:1887  store=1:1 range=7 [/Table/51-/Max): processing command: maxLeaseIndex=2103
I160803 21:05:20.010175 storage/replica.go:1435  store=1:1 range=7 [/Table/51-/Max): prepared command: maxLeaseIndex=2110 leaseAppliedIndex=2102
I160803 21:05:20.011277 storage/replica.go:1887  store=1:1 range=7 [/Table/51-/Max): processing command: maxLeaseIndex=2104
I160803 21:05:20.011632 storage/replica.go:1887  store=1:1 range=7 [/Table/51-/Max): processing command: maxLeaseIndex=2105
...
I160803 21:05:20.012845 storage/replica.go:1887  store=1:1 range=7 [/Table/51-/Max): processing command: maxLeaseIndex=2094
```

In english, we prepared a command at lease index 2094, sent it through raft, processed it and 11 other commands and then we encountered 2094 again. All this while the cluster is stable.

Ah, I just found:

```
I160803 21:05:20.001335 storage/replica.go:1770  store=1:1 range=7 [/Table/51-/Max): pending commands: refurbished 0, reproposing 12 (at 2104.2093); reasonTicks
```

Now why are we re-proposing these commands? Looking at `Replica.tick` the logic there seems suspicious. We're re-proposing any currently pending commands every 1.5s. Seems like we should only re-propose commands that have been pending for `RaftElectionTimeoutTicks`. @bdarnell thoughts?

**Comment by petermattis** [comment]
Back to this investigation. The delay at node restart is always due to timing out lease acquisition requests on the newly restarted node. Here's a snippet from a SQL trace after the node restarts:

```
     0.141ms      0.000ms    executing 1/1: BEGIN TRANSACTION
     0.148ms      0.007ms    BEGIN done
     0.389ms      0.241ms    executing 1/1: SAVEPOINT cockroach_restart
     1.484ms      1.095ms    preparing: SELECT id, balance FROM accounts WHERE id IN ($1, $2)
     1.588ms      0.104ms    meta descriptor lookup
     1.598ms      0.010ms    looked up range descriptor from cache
     1.621ms      0.023ms    sending RPC to [/Min, /Table/11)
  3002.735ms   3001.114ms    error, trying next peer: range 1: replica {4 3 2} not lease holder; <nil> is
  3015.194ms     12.459ms    executing 1/1: SELECT id, balance FROM accounts WHERE id IN ($1, $2)
  3015.386ms      0.192ms    meta descriptor lookup
  3015.395ms      0.010ms    looked up range descriptor from cache
  3015.420ms      0.025ms    sending RPC to [/Table/51, /Max)
  6017.785ms   3002.364ms    error, trying next peer: range 7: replica {4 3 2} not lease holder; <nil> is
  6018.986ms      1.201ms    error, trying next peer: range 7: replica {1 1 1} not lease holder; node_id:4 store_id:3 replica_id:2  is
```

The raft logging for range 1 shows:

```
I160805 10:06:20.896518 raft/raft.go:469  store=4:3 range=1 [/Min-/Table/11): 2 became follower at term 7
I160805 10:06:20.896777 raft/raft.go:238  store=4:3 range=1 [/Min-/Table/11): newRaft 2 [peers: [1,2,3], term: 7, commit: 109, applied: 109, lastindex: 109, lastterm: 7]
I160805 10:06:20.897370 raft/raft.go:777  store=4:3 range=1 [/Min-/Table/11): 2 no leader at term 7; dropping proposal
I160805 10:06:21.205446 storage/store.go:2352  store=4:3 range=1 MsgHeartbeat from {1 1 1}
I160805 10:06:21.205486 raft/raft.go:571  store=4:3 range=1 [/Min-/Table/11): 2 [term: 7] received a MsgHeartbeat message with higher term from 1 [term: 13]
I160805 10:06:21.205502 raft/raft.go:469  store=4:3 range=1 [/Min-/Table/11): 2 became follower at term 13
```

So the range fairly quickly got a heartbeat from the Raft leader. We see a little bit later that the range starts to restore from a snapshot:

```
I160805 10:06:22.201526 raft/raft.go:858  store=4:3 range=1 [/Min-/Table/11): 2 [commit: 109, lastindex: 109, lastterm: 7] starts to restore snapshot [index: 166, term: 13]
I160805 10:06:22.201548 raft/log.go:288  store=4:3 range=1 [/Min-/Table/11): log [committed=109, applied=109, unstable.offset=110, len(unstable.Entries)=0] starts to restore snapshot [index: 166, term: 13]
...
I160805 10:06:22.229741 storage/replica_raftstorage.go:600  store=4:3 range=1 [/Min-/Table/11): with replicaID 2, applying Raft snapshot for range 1 at index 166 (encoded size=299956, 861 KV pairs, 11 log entries)
I160805 10:06:22.234673 storage/replica_raftstorage.go:603  store=4:3 range=1 [/Min-/Table/11): with replicaID 2, applied Raft snapshot for range 1 in 4.869196ms
```

Seems like the range should be good to go, but then the lease acquisition isn't reproposed for another 3 seconds.

**Comment by petermattis** [comment]
Another instance of excessive resuscitation of a range. Here, node 3 goes down at 10:45:31 which corresponds with the truncation of its raft log:

```
I160805 10:45:31.004052 storage/raft_log_queue.go:168  range=7 truncating the raft log to 22167
```

The node comes back up at 10:46:12. We see the next truncation of its raft log at:

```
I160805 10:46:19.983720 storage/raft_log_queue.go:168  range=7 truncating the raft log to 71623
```

This indicates it took 7 seconds to recover the range from the raft log (~50k entries).
