### ISSUE TITLE
cdc: enable plugins for custom encoding formats and sinks

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#81773]
As a side effect of the recent refactors in changefeed code, we're getting to the point where the interface you need to implement to enable changefeeds to emit in Parquet format or to a Kinesis stream is pretty small and friendly. With an appropriate guide, outside contributors could do it. But actually reviewing, accepting, and releasing PRs is expensive and slow--especially in the case of new sinks, where we'd need a new integration test setup for each one. Instead, we should explore enabling people to separately build plugins that deploy alongside each CRDB node and hook into changefeed code to implement custom formats and custom sinks. Then we'd only need to maintain the API surface the plugins use.

We could use [go native plugins](https://pkg.go.dev/plugin), but they seem a bit cumbersome. If it's not too bad performance-wise, [hashicorp's gRPC plugins](https://github.com/hashicorp/go-plugin) seem like the way to go...you implement an interface we define (e.g. the Sink interface), and under the hood it's using local gRPC calls.

Jira issue: CRDB-16439

Epic CRDB-2260

**Comment by glerchundi** [comment]
I would also consider running a WASM plugin which would help others implementing the middleware in their language of choice. [wazero](https://github.com/tetratelabs/wazero) would be a good choice as a pure go WASM runtime.

**Comment by glerchundi** [comment]
Is this closed because there is no plans to implement this? Or because there is another approach on solving this? Any comments to help understanding the reasoning behind the close would be much appreciated :D
