### ISSUE TITLE
build: Support 32-bit builds

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#8179]
This issue tracks issues related to 32-bit builds of CockroachDB. Supporting this configuration is not a priority, but collecting all the information in one place gives us something to point to whenever this comes up.
- `c-rocksdb` produces a lot of compiler warnings about integer size (see #964)
- The go compiler appears to have an alignment bug for 32-bit arm: #6091 https://github.com/golang/go/issues/599

Epic CRDB-10447

Jira issue: CRDB-6164

**Comment by mjibson** [comment]
There are many functions in `sql/parser/builtins.go` that convert a `DInt` (int64) to an `int`. These will need to be audited for any 32-bit work that is done because the conversion from 64-bit to 32-bit int isn't safe.

**Comment by kardianos** [comment]
@mjibson Looking at the builtins, I would recommend two ways to tighten this up.

 1. For both 32-bit and 64-bit systems, define limits to your input strings and function value inputs. Then before the DInts are cast to an int in these cases, they are checked for the defined limits. math.MaxInt32 might be a reasonable limit for most functions and string sizes.
 2. For 32-bit systems I noticed many of the aggregate functions where using `int` internally rather then `int64`. Probably change any case that isn't used for indexing strings and arrays into `int64`.

Let me know if these sound reasonable.

**Comment by mjibson** [comment]
Yes, that all sounds correct.

**Comment by kardianos** [comment]
Per @mjibson https://github.com/cockroachdb/cockroach/pull/9549#issuecomment-249954464, not pursuing 32-bit builds in 2016.

**Comment by asad26** [comment]
Hi all
I am interested to run cockroach db on raspberry pi 32-bit. I was reading some issues here but they are almost 2 years older and it seems like at that time there is no support of this database on arm 32-bit architecture. Also there is one post written by @nvanbenschoten but no luck so far. Is there anyone who has either a docker image for 32-bit arch or can help me in building cockroach db on raspberry pi.
Thanks in advance.

**Comment by nvanbenschoten** [comment]
Unfortunately, a 32-bit build is not officially supported and there are no plans to work on it in the near future. That said, we have had recent success dropping a 64-bit ARM build on a 64-bit Raspberry Pi 3 model B running https://wiki.debian.org/RaspberryPi3.

**Comment by babvin** [comment]
@nvanbenschoten can you please share the documentation to build cockroachDB running on K8S with ARM64 Raspberry Pi 4 8GB

**Comment by nvanbenschoten** [comment]
@babvin to build for arm64, you should be able to simply run `./build/builder.sh mkrelease arm64-linux-gnueabi` on a build machine with Docker installed. This will produce a binary called `cockroach-linux-3.7.10-gnu-aarch64` that you can drop on to each of your 64-bit Raspberry Pi's.
