### ISSUE TITLE
cdc: design avro schema migration strategy

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#81840]
Goal: Make it easier to change how tables get mapped to avro schemas without breaking consumers.

Jira issue: CRDB-16378

**Comment by amruss** [comment]
Moving this back to triage due to the customer escalation

**Comment by miretskiy** [comment]
Moving back to Triage; I'd prefer not to have "design" type issues in the stability category.

**Comment by amruss** [comment]
Closing this - likely fixed with CDC transformations, which allow you to specify a stable message schema
