### ISSUE TITLE
sql:  value type decimal doesn't match type float 

### ISSUE THREAD

**Issue by maesenka** [cockroachdb/cockroach#81858]
**Describe the problem**

This came up in the Hibernate ORM tests. A SQL like this:

```
with HTE_Human (id, bodyWeight, heightInches) as (select (c1_0.mammal * 10), c1_1.body_weight, 180.0
                                                  from Cat c1_0
                                                           join Animal c1_1 on c1_0.mammal = c1_1.id),
     dml_cte_Animal (id)
         as (insert into Animal (id, body_weight) select e.id, e.bodyWeight from HTE_Human e returning id),
     dml_cte_Mammal (id) as (insert into Mammal (animal) select e.id from HTE_Human e returning animal),
     dml_cte_Human (id)
         as (insert into Human (mammal, height_centimeters) select e.id, e.heightInches from HTE_Human e returning mammal)
select count(*)
from dml_cte_Animal id;
```
throws the error: `[42804] ERROR: value type decimal doesn't match type float of column "height_centimeters"`

**To Reproduce**

See above

**Expected behavior**
As in Postgresql, automatic type conversion between compatible types.

**Environment:**
 - CockroachDB version 20.2.10
 - Server OS: Linux
 - Client app JDBC

This was submitted as part of work to fix the Hibernate ORM CI test suite for CockroachDB

**Comment by otan** [comment]
unfortunately this is a problem with "implicit casts" and is not something we support right now.

if you need an issue number to reference, it would be #75101
