### ISSUE TITLE
Allow standalone SQL client binary to support --certs-dir

### ISSUE THREAD

**Issue by smcvey** [cockroachdb/cockroach#81882]
The standalone SQL client binary does not currently support --certs-dir, meaning you have to use --url to pass an unwield postgresql-type URL rather than being able to simply run the binary (and it finding .cockroach-certs/ by default or whatever is passed by --certs-dir).

Jira issue: CRDB-16106

**Comment by knz** [comment]
this was not fixed by #82021 - it needs #82020 instead.
