### ISSUE TITLE
Partial index FULL SCAN when condition/column is NOT NULL

### ISSUE THREAD

**Issue by alistair-roacher** [cockroachdb/cockroach#81906]
**Describe the problem**

The execution plan for a SELECT is using a FULL SCAN of a partial index which is not necessary. 

**To Reproduce**

Create a table with a NOT NULL, non-PK column
Create a partial index on the column with condition WHERE <column> IS NOT NULL 
Insert 10,000 rows and analyse the table
Attempt to access specific data using the partial index .

[testcase.txt](https://github.com/cockroachdb/cockroach/files/8779550/testcase.txt)

**Expected behavior**
The query plan should look up specific spans rather than scanning the entire index whether the column is NOT NULL or not

**Additional data / screenshots**
Bad plan:
  • filter
  │ estimated row count: 3
  │ filter: batch_id IN (1, 101, 999)
  │
  └── • scan
        estimated row count: 10,000 (100% of the table; stats collected 49 seconds ago)
        table: requests@requests_pkey
        spans: FULL SCAN

Good plan:
  • filter
  │ estimated row count: 3
  │ filter: batch_id IN (1, 101, 999)
  │
  └── • scan
        estimated row count: 3 (0.03% of the table; stats collected 1 minute ago)
        table: requests@batch_id_idx (partial index)
        spans: [/1 - /1] [/101 - /101] [/999 - /999]

**Environment:**
 - CockroachDB version: 21.2.10 / 22.1.0
 - Server OS: Linux/Windows
 - Client app: cockroach sql

**Additional context**

Jira issue: CRDB-16124

**Comment by alistair-roacher** [comment]
[testcase.txt](https://github.com/cockroachdb/cockroach/files/8780061/testcase.txt)
Realised that in the steps above I didn't include the batch_id IS NOT NULL clause which would allow the partial index to be used.
I've updated and reattached the testcase.txt file with the recreation steps - the problem is still there:

root@:26257/defaultdb> EXPLAIN SELECT id, batch_id, status FROM  requests
                    ->   WHERE batch_id IN (1, 101, 999) AND batch_id IS NOT NULL;
                                          info
-----------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • filter
  │ estimated row count: 3
  │ filter: batch_id IN (1, 101, 999)
  │
  └── • scan
        estimated row count: 10,000 (100% of the table; stats collected 11 minutes ago)
        table: requests@requests_pkey
        spans: FULL SCAN
(11 rows)

root@:26257/defaultdb> alter table requests alter column batch_id drop not null;
ALTER TABLE

root@:26257/defaultdb> EXPLAIN SELECT id, batch_id, status FROM  requests
                    ->   WHERE batch_id IN (1, 101, 999) AND batch_id IS NOT NULL;
                                        info
-------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • index join
  │ estimated row count: 3
  │ table: requests@requests_pkey
  │
  └── • scan
        estimated row count: 3 (0.03% of the table; stats collected 11 minutes ago)
        table: requests@batch_id_idx (partial index)
        spans: [/1 - /1] [/101 - /101] [/999 - /999]
(11 rows)

**Comment by intech** [comment]
This bug with only `IS NULL`:
```sql
EXPLAIN ANALYZE SELECT * FROM public.table WHERE deleted_at IS NULL;
```
use `primary` index is bad plan

```
planning time: 925µs
execution time: 3ms
distribution: full
vectorized: true
rows read from KV: 18 (3.4 KiB)
cumulative time spent in KV: 2ms
maximum memory usage: 60 KiB
network usage: 0 B (0 messages)

• filter
│ columns: (uuid uuid, deleted_at timestamp) // deleted columns
│ nodes: n1
│ actual row count: 18
│ vectorized batch count: 1
│ estimated row count: 18
│ filter: ((deleted_at)[timestamp] IS NULL)[bool]
│
└── • scan
      columns: (uuid uuid, deleted_at timestamp) // deleted columns
      nodes: n1
      actual row count: 18
      vectorized batch count: 1
      KV time: 2ms
      KV contention time: 0µs
      KV rows read: 18
      KV bytes read: 3.4 KiB
      estimated row count: 18 (100% of the table; stats collected 25 minutes ago)
      table: exchanges@primary
      spans: FULL SCAN
```

[distsql plan](https://cockroachdb.github.io/distsqlplan/decode.html#eJykktFq1EAUhu99isO5lLFN1grLXBVli0vXVrJVLyTIZOawHZjMxJkTzLLksXwBn0w2E8tWUJRe_t-f_-Q_Jzlg-upQ4na1Wb25g-dwVd2-g65vnNVnNOh75XeU4NPbVbUCQ46YzBfFsN7CzYfNBgX6YOhGtZRQfsYSa4FdDJpSCvGIDtMDazOgLARa3_V8xLVAHSKhPCBbdoQS71TjqCJlKJ4XKNAQK-umsQ9FLrtoWxX3KHDbKZ8kvECB1x-BbUsSFm3KUgfP5NkGPzvFj--zFcO3BJGUkVAuM2r2TL_Yy7MLuLavUWCrBmipDXEPyrmgFZOR8KqY7UaxvqcEoeeuZwklCpxmP4Al1qPALOedE6sdoSxH8e93ubKOKVI8Lx8fJXMJl8uTr0ED6f5k74u891PKLv6nbEWpCz7Ro6p_mlyMtUAyO8o_Sgp91PQ-Bj29JsvbKTcBQ4mzW2ax9tk6FjwNl38NL34L1-OznwEAAP__OOj9eQ==)

---

```sql
EXPLAIN ANALYZE SELECT * FROM public.table WHERE deleted_at IS NOT NULL;
```
use `exchanges_deleted_at_idx` index is good plan
```
planning time: 962µs
execution time: 3ms
distribution: local
vectorized: true
cumulative time spent in KV: 1ms
maximum memory usage: 20 KiB
network usage: 0 B (0 messages)

• index join
│ columns: (uuid uuid, deleted_at timestamp) // deleted columns
│ nodes: n1
│ actual row count: 0
│ vectorized batch count: 0
│ KV time: 3µs
│ KV contention time: 0µs
│ KV rows read: 0
│ KV bytes read: 0 B
│ estimated row count: 0
│ table: exchanges@primary
│ key columns: uuid
│
└── • scan
      columns: (uuid uuid, deleted_at timestamp)
      nodes: n1
      actual row count: 0
      vectorized batch count: 0
      KV time: 1ms
      KV contention time: 0µs
      KV rows read: 0
      KV bytes read: 0 B
      estimated row count: 0 (<0.01% of the table; stats collected 22 minutes ago)
      table: exchanges@exchanges_deleted_at_idx
      spans: /!NULL-
```

[distsql plan](https://cockroachdb.github.io/distsqlplan/decode.html#eJy0klGL00AUhd_9Fdf7KFc30-6uOk-DUrFubaWt-iChTDOX7kAyE2cm2FL6s_wD_jJJUtpVWFFk33LPyTk5fGSP8WuJEhejyej1Ep7Am_nsPdTNurTFM94Wt9ptOMLnt6P5CAyXnNisdILxAqazJUw_TiZI6Lzhqa44ovyCAnPCOviCY_ShlfbdC2OzRZkRWlc3qZVzwsIHRrnHZFPJKHGp1yXPWRsOFxkSGk7all3taYw6Pa3Og1bWbJFwUWsXJVw8boc9RcJZkyQogYQ3nyDZiiWIKvZn4V1il6x3Ryf78f1oBf8tQmBtJGS9st4lPknwCgkrvYWKKx92oMvSFzqxkTDI4Ma29lqn4pYj-CbV7Yi2p6s9C_mBsL-OOGLSG0YpDvT3yN55647ExH3E6mArHXZnHqQGpIakLkldkbom9ZzUC1IvSYmMlBCkxICUGJISl6TEFSlxfZfh8ETqQSD23n8QHPwLwTnH2rvIv9C7rzk75IRsNtz_2NE3oeAPwRfdZ_pz1uU6wXBMvSv6Y-x6qx14Nyz-GB78Fs4Pj34GAAD__8cxMfQ=)

**Comment by mgartner** [comment]
Thanks for the report! We've identified the bug and have a fix. 

> Realised that in the steps above I didn't include the batch_id IS NOT NULL clause which would allow the partial index to be used.

FYI, you shouldn't need to explicitly include the `batch_id IS NOT NULL` in the query filter. Both `batch_id IN (1, 101, 999)` in the filter, and `batch_id INT8 NOT NULL` in the table definition, imply that `batch_id IS NOT NULL`. The bug was preventing the partial index from being used in your original example.

**Comment by mgartner** [comment]
@intech I'm not sure you're running into the same bug. If you share your table schema, I can verify what behavior is expected for your queries.

**Comment by intech** [comment]
@mgartner Where can I safely send you analysis archives in debug mode for both queries?

**Comment by intech** [comment]
@mgartner done, thx!

**Comment by mgartner** [comment]
@intech thanks for providing statement bundles. The behavior you are seeing is unrelated to this issue - your schema has no partial indexes.

Your statement bundles show:

1. With the filter `deleted_at IS NOT NULL` the optimizer chooses a constrained scan `(/NULL - ]` followed by an index join. Index joins are expensive operations with a cost proportional to the number of input rows. The constrained scan will produce very few rows based on the table stats, so the cost of the index join is preferred over a full table scan of the primary index.
2. With the filter `deleted_at IS NULL` the optimizer chooses a full table scan followed by a filter. Based on the table stats, all rows in the table will satisfy the filter, so rather than run a constrained scan and an expensive index join, it's better to scan the primary index and avoid the index join entirely.

In both cases the optimizer is choosing the optimal plans based on the statistics it's gathered about the table.

**Comment by intech** [comment]
@mgartner Thank you for the clarification. It was on the surface, but I didn't think about it.
