### ISSUE TITLE
storage: rebalancing doesn't keep up with load

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#8190]
Using `TestContinuousLoad_BlockWriter` with a 4-node cluster, rebalancing doesn't keep up with our load. Here's a screenshot from a TeamCity run of this test:

<img width="1512" alt="screenshot 2016-08-01 13 18 12" src="https://cloud.githubusercontent.com/assets/1564582/17302553/c74e9160-57ea-11e6-8965-f35d539f1ca2.png">

Note that node 4 only has 5 replicas. Given that this test has only generated 66 replicas during 3+ hours of load, I'd expect replica counts to be even across all nodes.

For reference, this is the TeamCity config:

https://teamcity.cockroachdb.com/viewLog.html?buildId=6893&buildTypeId=C_BW_4Nodes_6Hours&tab=buildLog#_focus=624

**Comment by petermattis** [comment]
@cuongdo Is this still happening?

**Comment by cuongdo** [comment]
nope, the nightly tests actually have load now. closing
