### ISSUE TITLE
Changefeed `format=csv` option returns `unknown format` error

### ISSUE THREAD

**Issue by kathancox** [cockroachdb/cockroach#81916]
**Describe the problem**

Testing the `format=csv` [option ](https://github.com/cockroachdb/cockroach/commit/f7ca7b185675d98b385c1cb71835a2bb817774a2). I'm receiving `ERROR: unknown format: csv`. Running this on a v22.1.0 roachprod cluster, tested with cloud S3 & Pub/Sub **with** the `initial_scan = 'only'` option.

**To Reproduce**

1. Set up v22.1.0 cluster
2. Enabled rangefeeds
3. Ran the following changefeed statements:

```
CREATE CHANGEFEED FOR TABLE movr.users INTO "s3://kathrynh-bulkio?AWS_ACCESS_KEY_ID=redacted&AWS_SECRET
_ACCESS_KEY=redacted" WITH initial_scan = "only", format=csv;
```

```
CREATE CHANGEFEED FOR TABLE movr.users INTO 'gcpubsub://cockroach-khancox?AUTH=specified&CREDENTIALS=encoded_key&region=us-east1&topic_name=users' with initial_scan = 'only', format=csv;
```

5. See error for both tests: `ERROR: unknown format: csv`

**Expected behavior**

Expect the changefeed to successfully start when `format=csv` is combined with `initial_scan='only'` for every sink.

Jira issue: CRDB-16129

**Comment by samiskin** [comment]
Resolved by #82355
