### ISSUE TITLE
storage: elevated table checksum mismatch errors

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#81946]
**Describe the problem**

_tldr: use [this](https://sentry.io/organizations/cockroach-labs/issues/3487817072/events/latest/?project=164528&query=is%3Aunresolved+%22checksum+mismatch+at+0%22&statsPeriod=14d) Sentry link to view latest occurrences._

We're seeing an elevated rate of checksum mismatch errors on 22.1.0. We see the following stack trace as the cause:

```console
error.go:27: pebble/table: invalid table 000035 (checksum mismatch at 0/6137)
... snip ...
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble/internal/base.CorruptionErrorf
  | 	github.com/cockroachdb/pebble/internal/base/external/com_github_cockroachdb_pebble/internal/base/error.go:27
  | github.com/cockroachdb/pebble/sstable.checkChecksum
  | 	github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go:2268
  | github.com/cockroachdb/pebble/sstable.(*Reader).readBlock
  | 	github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go:2331
  | github.com/cockroachdb/pebble/sstable.(*singleLevelIterator).readBlockWithStats
  | 	github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go:400
  | github.com/cockroachdb/pebble/sstable.(*singleLevelIterator).loadBlock
  | 	github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go:382
  | github.com/cockroachdb/pebble/sstable.(*singleLevelIterator).seekGEHelper
  | 	github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go:582
  | github.com/cockroachdb/pebble/sstable.(*singleLevelIterator).seekPrefixGE
  | 	github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go:667
  | github.com/cockroachdb/pebble/sstable.(*singleLevelIterator).SeekPrefixGE
  | 	github.com/cockroachdb/pebble/sstable/external/com_github_cockroachdb_pebble/sstable/reader.go:618
  | github.com/cockroachdb/pebble.(*levelIter).SeekPrefixGE
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/level_iter.go:432
  | github.com/cockroachdb/pebble.(*mergingIter).seekGE
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go:834
  | github.com/cockroachdb/pebble.(*mergingIter).SeekPrefixGE
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/merging_iter.go:903
  | github.com/cockroachdb/pebble.(*Iterator).SeekPrefixGE
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/iterator.go:1053
  | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleIterator).SeekGE
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble_iterator.go:287
  | github.com/cockroachdb/cockroach/pkg/storage.(*intentInterleavingIter).SeekGE
  | 	github.com/cockroachdb/cockroach/pkg/storage/intent_interleaving_iter.go:310
  | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleMVCCScanner).get
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble_mvcc_scanner.go:407
  | github.com/cockroachdb/cockroach/pkg/storage.mvccGet
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:769
  | github.com/cockroachdb/cockroach/pkg/storage.MVCCGet
  | 	github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:729
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/batcheval.Get
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/batcheval/cmd_get.go:55
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.evaluateCommand
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go:495
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.evaluateBatch
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_evaluate.go:270
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeReadOnlyBatchWithServersideRefreshes
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_read.go:287
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeReadOnlyBatch
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_read.go:83
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeBatchWithConcurrencyRetries
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvs...
```

List of relevant sentry's here: https://sentry.io/organizations/cockroach-labs/issues/?project=164528&query=is%3Aunresolved++%22checksum+mismatch%22&statsPeriod=14d

*NB: This is a parent issue tracking the investigation.*

Jira issue: CRDB-16137

**Comment by nicktrav** [comment]
Summarizing a conversation we had [internally](https://cockroachlabs.slack.com/archives/CAC6K3SLU/p1653597922349209) around some initial observations:
- multiple distinct clusters affected, based on the sentry alerts
- all of the (new) events are for checksum mismatches in the first block (offset=0)
- the sstable numbers are all low - indicating this is happening early on in a node / cluster's life
- the block lengths are also fairly small, which suggests that these tables could just have the one block

It seems unlikely that this is purely an uptick in random corruption - in which case we'd assume a more random distribution of block and table numbers.

The assumption that these are small sstables is also curious. There was some speculation that creating such a table could be the result of replicating a small range to a new node. I attempted to reproduce this by creating a three node cluster, initializing it, creating a new table and committing a single row, then adding a fourth node to the cluster. I re-ran this contrived scenario a number of times without issue.

To debug this further, we're going to need some artifacts from an affected node / cluster:
- Pebble / Cockroach logs would help narrow down the type of even that produced the table (flush, compaction, ingestion, etc.)
- A manifest would give us deeper insight into what was in the table

There was also some speculation that a corrupted first block could point to a buffer reuse problem when constructing an in-memory sstable somewhere in CockroachDB?

Going to leave this open for now, in the hopes that we can catch a real world example of the corruption.

**Comment by nicktrav** [comment]
@joshimhoff was kind enough to put together a query ([internal link](https://cockroachlabs.slack.com/archives/CJX8V9SJ2/p1654207148594709?thread_ts=1653599263.636839&cid=CJX8V9SJ2)) that should show clusters that we manage that are being hit by this issue.

**Comment by nicktrav** [comment]
Adding a note for posterity that the two backports will appear in `v22.1.2` (6/22) and `v21.2.13` (7/5), based on the current release schedule.

**Comment by nicktrav** [comment]
These versions should show up in Cockroach Cloud ~7 days after the release, at which point we can expect to see the tags showing up in Sentry.

**Comment by nicktrav** [comment]
Still haven't forgotten about this. It looks like we haven't seen this in 22.1 for about a week. That's just my casual observation. We're banking on being about to catch this in one of our own clusters, at which point we should be able to see what was going on in the logs / manifest.

Here's the [Sentry query](https://sentry.io/organizations/cockroach-labs/issues/2933120155/?environment=v22.1.0&environment=v22.1.1&environment=v22.1.2&project=164528&query=%22checksum+mismatch%22&statsPeriod=14d) that I'm using - filtered to 22.1.x official releases.

**Comment by nicktrav** [comment]
Doing my weekly check-in. Still happening (we had a little flurry of events over the past few days). Still no reports in CC clusters.

I refined [the query](https://sentry.io/organizations/cockroach-labs/issues/2933120155/events/4d97c403234247edba1b119e3367c6db/?environment=v22.1.0&environment=v22.1.1&environment=v22.1.2&project=164528&query=%22checksum+mismatch+at+0%22&statsPeriod=14d) some more to only filter on the mismatches that are happening on the first block in an sstable, as that appears to be the new failure mode that popped up in 22.1.

**Comment by jbowens** [comment]
@nicktrav here are some links from the Docker-related issues we've seen in the past. I think in the end we made a change to our [Mac quickstart documentation](https://www.cockroachlabs.com/docs/stable/start-a-local-cluster-in-docker-mac.html) that uses of Docker to use docker volumes to avoid the issue .

https://github.com/docker/for-mac/issues/5124#issuecomment-744697395
https://github.com/cockroachdb/cockroach/issues/57192

**Comment by nicktrav** [comment]
Thanks for the link to that ticket.

I tried this out locally (on macOS), and I'm hitting the same issue - two of the three containers (the ones started after the first container) crash intermittently when a file that has (presumably) been written out are no longer present on the filesystem (the files are there on the host FS, but the process is being told that they aren't). I'm _not_ using the suggested workaround (I'm using the host FS rather than a vol).

The `‹open /cockroach/cockroach-data/000004.sst: no such file or directory›` mode of failure looks to be reliably reproducible (in the case that the host's FS is used). Unclear if this is the result of the same underlying issues that's breaking resulting in the bad checksums (I haven't been able to repro that at all), but this seems like it might be worth digging into (even if just to provide more evidence upstream).

Each of the failures I observed seemed tied to ingestion, with logs of the following form:

```console
I220725 18:29:21.147929 1163 kv/kvserver/pkg/kv/kvserver/replica_raftstorage.go:864 ⋮ [n3,s3,r66/2:{-}] 153  applying INITIAL snapshot cd11181d from (n1,s1):1 at applied index 31106
I220725 18:29:21.181730 1163 3@github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/event.go:657 ⋮ [n3,pebble,s3] 154  [JOB 13] ingesting: sstable created 000219
I220725 18:29:21.185929 1163 3@github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/event.go:657 ⋮ [n3,pebble,s3] 155  [JOB 13] ingesting: sstable created 000224
I220725 18:29:21.190308 1163 3@github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/event.go:657 ⋮ [n3,pebble,s3] 156  [JOB 13] ingesting: sstable created 000220
I220725 18:29:21.193773 1163 3@github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/event.go:657 ⋮ [n3,pebble,s3] 157  [JOB 13] ingesting: sstable created 000221
I220725 18:29:21.197529 1163 3@github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/event.go:657 ⋮ [n3,pebble,s3] 158  [JOB 13] ingesting: sstable created 000222
I220725 18:29:21.202265 1163 3@github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/event.go:657 ⋮ [n3,pebble,s3] 159  [JOB 13] ingesting: sstable created 000223
I220725 18:29:21.210587 1163 3@github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/event.go:677 ⋮ [n3,pebble,s3] 160  [JOB 14] WAL created 000225 (recycled 000199)
I220725 18:29:21.210889 1207 3@github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/event.go:637 ⋮ [n3,pebble,s3] 161  [JOB 15] flushing 1 memtable to L0
I220725 18:29:21.213109 1207 3@github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/event.go:657 ⋮ [n3,pebble,s3] 162  [JOB 15] flushing: sstable created 000226
I220725 18:29:21.216992 1207 3@github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/event.go:641 ⋮ [n3,pebble,s3] 163  [JOB 15] flushed 1 memtable to L0 [000226] (4.3 K), in 0.0s (0.0s total), output rate 818 K/s
I220725 18:29:21.217549 880 3@github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/event.go:625 ⋮ [n3,pebble,s3] 164  [JOB 16] compacting(default) L0 [000226] (4.3 K) + L6 [000218] (3.1 M)
I220725 18:29:21.231713 1163 3@github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/event.go:665 ⋮ [n3,pebble,s3] 165  [JOB 13] ingested L0:000219 (1.3 K), L0:000224 (1.2 K), L0:000220 (2.1 K), L0:000221 (1.1 K), L0:000222 (1.4 K), L6:000223 (564 K)
I220725 18:29:21.232207 880 3@github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/event.go:657 ⋮ [n3,pebble,s3] 166  [JOB 16] compacting: sstable created 000227
I220725 18:29:21.232426 1218 (gostd) filenames.go:167 ⋮ [-] 167  ‹000219.sst:›
I220725 18:29:21.232426 1218 (gostd) filenames.go:167 ⋮ [-] 167 +‹open /cockroach/cockroach-data/000219.sst: no such file or directory›
I220725 18:29:21.232426 1218 (gostd) filenames.go:167 ⋮ [-] 167 +‹directory contains 27 files, 12 unknown, 8 tables, 2 logs, 2 manifests›
```

In most cases the missing file was the first ingested file. I didn't see case where the missing file _wansn't_ one of the ssts generated in the snapshot application.

I might split this particular line of inquiry off into another issue.

**Comment by nicktrav** [comment]
I tweaked the Sentry filtering a bit so that we'd get all the `checksum mismatch at 0/x` events in the same ticket.

New grouped events [here](https://sentry.io/organizations/cockroach-labs/issues/3487817072/events/latest/?project=164528&query=is%3Aunresolved+%22checksum+mismatch+at+0%22&statsPeriod=14d).

**Comment by nicktrav** [comment]
Monthly check-in - we haven't seen this in ~30 days. Proposal: we circle back in a month and close out if we haven't seen another instance.

**Comment by nicktrav** [comment]
It's been more or less two months since we last saw this in the wild. Closing. This should re-open if / when we ever see this particular type of checksum mismatch again (i.e. `checksum mismatch at 0/x`).
