### ISSUE TITLE
Stuck retrying Migration to 21.2-56: "populate RangeAppliedState.RaftAppliedIndexTerm for all ranges"

### ISSUE THREAD

**Issue by wzrdtales** [cockroachdb/cockroach#81961]
**Describe the problem**

After upgrading to 22.1, several migrations were running through fine. Since 10 hours it is however stuck with 21.2-56 and doesn't finish on it. (Retrying the 9th time now)

**To Reproduce**

Upgrade to 22.1

On kubernetes.

Jira issue: CRDB-16140

**Comment by wzrdtales** [comment]
10th retry now...

**Comment by wzrdtales** [comment]
I went through the nodes and their logs and found this now on one node:

![image](https://user-images.githubusercontent.com/1786821/170701150-4f813a04-0736-4853-b1e6-c701031b2ce9.png)


so this seems to be a display bug, but also the progress is very slow, not sure if intended. With that speed it will probably take around 3-4 days to finish.

**Comment by wzrdtales** [comment]
I was calculating the whole runtime, it ended up needing around 24 hours in total I think. It resolved on its own, but in a weird status which left us worried (as you noticed :))

> With the estimate of 3-4 days, are you saying this cluster has 16,416,000+ ranges?

Not yet that big, "only" 300k+ ranges.

**Comment by irfansharif** [comment]
I'm glad it resolved, I'll close this issue. I'll add a suggestion to https://github.com/cockroachdb/cockroach/issues/72931 to let operators control the pacing here more directly, if they want to speed up the migrate parallelism for clusters with large range counts while keeping an eye out on foreground impact. I'll also note that some of these migrations are intended to be long-running and operating over the timescales you're observing: https://github.com/cockroachdb/cockroach/pull/48843.
