### ISSUE TITLE
bazel: generated sandbox path is too long for certain tests

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#82023]
When $HOME is longer (in nr of characters) than a rather low limit, many tests fail because of the structure of the TMPDIR inside the sandbox:

```
$  ./dev test //pkg/cli --filter=Example_demo_locality
...
server 0 failed to start: listen unix /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/sandbox/processwrapper-sandbox/13337/execroot/com_github_cockroachdb_cockroach/_tmp/377f8cb805402ad634df2798cd58c1c3/demo942895359/.s.PGSQL.26257: bind: invalid argument
```

**Expected behavior**

The TMPDIR inside the sandbox should be shorter, truncated from
```
$HOME/.cache/bazel/_bazel_$USER/<hash1>/sandbox/processwrapper-sandbox/<pid>/execroot/com_github_cockroachdb_cockroach/_tmp/<hash2>/demo<random>/.s.PGSQL.26257
```

to (proposal):
```
# Drop $USER
# Hoist processwrapper-sandbox/<pid> into p<pid>
# Hoist _tmp outside of the go package sandbox.
$HOME/.cache/bazel/_bazel/<hash1>/sandbox/p<pid>/execroot/_tmp/<hash2>/demo<random>/.s.PGSQL.26257
```

Jira issue: CRDB-16171

**Comment by rickystewart** [comment]
Looks like a dup of #72918.

We don't really have exact control over the path to the `TMPDIR` that bazel gives us, but we can have `dev doctor` suggest that you manually choose a shorter `tmpdir`. I'll look at that this week.

**Comment by rickystewart** [comment]
> The path used by bazel here is independent of TMPDIR and I have no control over it. That is why suggestion is made at the top to control how the tmpdir is generated inside the sandbox.

You should be able to add `test --test_tmpdir=/path/to/whatever` to your `.bazelrc.user` to anchor to a shorter `tmpdir`.

**Comment by knz** [comment]
```
kena@kenax ....com/cockroachdb/cockroach % ./dev test //pkg/cli --filter=Example_demo_locality --test_tmpdir=/whatever
ERROR: unknown flag: --test_tmpdir
```

**Comment by knz** [comment]
it looks to me like `--test_tmpdir=$TMPDIR` would be the right move, and have TMPDIR adjusted in CI accordingly.
