### ISSUE TITLE
changefeed: replan flow of changefeeds as data distribution changes

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/cockroach#82025]
When changefeeds are long-running, the distribution of data may change, making the current changefeed plan suboptimal. Suggestion is to allow re-planning (or restarting) periodically, either automatic or manually.

(Perhaps similar in spirit to https://github.com/cockroachdb/cockroach/issues/57427)

cc @miretskiy @dt 

Jira issue: CRDB-16173

Epic CRDB-19057

**Comment by miretskiy** [comment]
Similar in spirit to https://github.com/cockroachdb/cockroach/pull/79731

**Comment by miretskiy** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/83143
