### ISSUE TITLE
support `inet` function postgres

### ISSUE THREAD

**Issue by kocoten1992** [cockroachdb/cockroach#82052]
**Is your feature request related to a problem? Please describe.**
I'm trying to load maxmind database into cockroachdb.

Tutorial postgres at https://dev.maxmind.com/geoip/importing-databases/postgresql?lang=en, but because https://github.com/cockroachdb/cockroach/issues/18846 is not supported yet.

Then I'm looking at tutorial on mysql https://dev.maxmind.com/geoip/importing-databases/mysql?lang=en, only found out that a function akin to `inet_aton` in mysql is `inet` in postgres is also not supported yet (and I can't github issue for that).

**Describe the solution you'd like**
Either support `cidr` or `inet function` would work.

**Additional context**
```sql
# postgres
postgres=# select inet('::111');
 inet  
-------
 ::111
(1 row)
```

```sql
# cockroachdb
root@:26257/defaultdb> select inet('::111');         
ERROR: unknown function: inet()
SQLSTATE: 42883
```

---

Instructions:
- Add a builtin definition in pkg/sql/sem/builtins/builtins.go
- It can be implemented by calling `eval.PerformCast`
- Add logic tests in pkg/sql/logictest/testdata/logic_test/builtin_function

---

Jira issue: CRDB-16454

**Comment by surahman** [comment]
Is this issue dependent on the implementation of #18846 or can it be implemented as a standalone/separate feature?
