### ISSUE TITLE
kv: hand off a number of roachtests

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#82060]
At the time of writing, KV owns many roachtests:

```
bin/roachtest list tag:owner-kv | grep -cF '[kv]'
220
```

We expect that for a lot of them, we can transfer ownership at some point in the near future.

I prepared a spreadsheet with a v0 of proposed movement: https://docs.google.com/spreadsheets/d/1w_zx8W1ObHVL1oMXNjh4LTcEMkTHyCycbGSnji1BvCk/edit#gid=2080879335

<img width="616" alt="image" src="https://user-images.githubusercontent.com/5076964/170965299-31291693-d301-4dc4-9934-4577e4a589a1.png">

cc @lidorcarmel (for visibility) @srosenberg (since TE is the would-be owner for a lot of the tests and we should discuss the specifics of such a handover). Note that PERF is just TE today, but I thought it would make sense to make that distinction early.

Jira issue: CRDB-16193

**Comment by nvanbenschoten** [comment]
@tbg what are the next steps here? To determine which tests can be handed off? To relabel those tests?

**Comment by tbg** [comment]
Test-Eng will take the perf tests mid-July and we'll hand of another batch after that (details TBD), possibly the version-upgrade tests.

**Comment by mwang1026** [comment]
Removing KV then since seems like Test Eng will take the lead on actually executing the change. Let me know if this is wrong @srosenberg

**Comment by tbg** [comment]
I was going to make the PR.

**Comment by tbg** [comment]
Here's what's left after #86300 

```
$ roachtest list | grep -F '[kv]' | awk '{print $1}' | grep -Eo '^[^/]+' | uniq -c | sort
   1 autoupgrade
   1 drain-and-decommission
   1 drop
   1 gossip
   1 hotspotsplits
   1 inconsistency
   1 indexes
   1 ledger
   1 network
   1 overload
   1 queue
   1 restart
   1 slow-drain
   2 copy
   2 copyfrom
   2 kv50
   2 replicagc-changed-peers
   2 roachmart
   3 replicate
   3 transfer-leases
   4 loqrecovery
   4 splits
   5 decommission
   5 rebalance
   6 clock
   6 kv
   8 kv0bench
  10 decommissionBench
  11 acceptance
  13 follower-reads
```
