### ISSUE TITLE
Correct SQL help text for CREATE CHANGEFEED

### ISSUE THREAD

**Issue by kathancox** [cockroachdb/cockroach#82176]
Minor error: in the current SQL help text, there is a line at the end that reads:

`Sink: Data caputre stream stream destination.  Enterprise only.` 

I assume this is meant to read: `sink: data capture stream destination (Enterprise only)`

Jira issue: CRDB-16239

**Comment by HonoreDB** [comment]
Fixed in https://github.com/cockroachdb/cockroach/pull/82310
