### ISSUE TITLE
storage: make replica GC queue timings less aggressive

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#8220]
With #8172 in, we should unwind at least some of the changes in #7533 and #7507 as there is no need for the GC queue to be overly aggressive - situations in which a Replica would be GCed in a non-event driven way are limited to Replicas which are completely inactive.

**Comment by petermattis** [comment]
@tschottdorf Given your recent GC queue changes is there anything else to do here?

**Comment by tschottdorf** [comment]
this issue is about the replica GC queue, not the GC queue, but it seems that what we're doing is OK:

- eagerly add replicas based on suggestion by their raft peer
- additionally, relatively quickly pick up replicas stuck in candidate state during normal queue operation, and
- leave regular replicas alone except once every 10 days.

we have a pretty aggressive `timer()` on the replicaGCQueue but that's fine, if we have replicas to GC then there's no real point waiting a long time between them, as clients may be stuck on them without a chance of making progress.

I've seen during my testing that we still sometimes get replicas that are deleted in dormant state. Those would only be caught after ~10 days, but they're harmless (except that they often get queued by the data-GC queue but without making progress, so while there might be something to optimize there, it's cosmetic).

Closing.
