### ISSUE TITLE
issues: consider not reusing existing GH issues

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#82345]
**Is your feature request related to a problem? Please describe.**

Currently, the github issue poster will re-use an existing issue and post a comment on that thread instead.
This is good in a sense - tests that fail a lot (say a roachtest that starts failing deterministically every night)
won't create "issue spam".
It is bad in a sense - it's hard to map repeat failures into project management, which generally operates at the level of issues, not comments. As a result, tests that fail repeatedly but for different reasons are lumped together in one issue and tend to be forgotten easily, despite often being valuable (examples of this are the version upgrade tests). Project management will usually look at the issue once, perhaps for a harmless failure, put it in the backlog, and when a severe issue is posted on the thread it will not be visible to anyone. That's not great.

As of writing, the status quo is justifiable by saying that it is really cumbersome to skip a test (have to go through bors) and so tests remain unskipped for longer than they would otherwise, so there are more failures, so it is important not to create too many redundant issues, etc.

However, at least for certain tests (roachtests), once tests get easier to skip and the assumption is that a flake will be skipped eagerly, we should consider a one-issue-per-failure model. The test failure posts already link each other (which we would need to improve slightly to make it work for this new use case, but nothing major).

**Describe the solution you'd like**

At least for roachtests, create a new issue on every failure, once we have https://github.com/cockroachdb/cockroach/pull/81293 and the tooling around it works.
We should probably do this on a per-Owner basis. KV/Repl would be expected to opt into this new mode to facilitate their issue management.

**Describe alternatives you've considered**

There are many alternatives to what we do right now. I suspect that what we do - posting failures to GH in the first place - is fairly unique (?) and I don't have the lay of the land.

**Additional context**

Jira issue: CRDB-16303

**Comment by erikgrinaker** [comment]
I suppose this will at least incentivize people to skip or fix tests. But often it can take a few days until we get around to fixing it. Is the idea that we'll aggressively skip the test in that case until we can fix it? From experience, I worry that this won't be as prompt as we'd like, and that we'll end up with a lot of issue spam.

**Comment by jordanlewis** [comment]
Since we're thinking about redoing this, I want to suggest creating a separate repo for test failures. The reason for this is that the test failure issues create clutter and mess in our main repo.

Pros:
- less mess
- clearly distinguished place for test failure to land vs normal issues

Cons:
- increased issue management complexity due to requirements of tracking issues from more than 1 repo
- possibly easier to ignore issues in other repos, so we'd have to design our tooling to not make that possible

**Comment by tbg** [comment]
@erikgrinaker the plan is to make skipping very easy and only then could we consider the above idea. Even then, we'd need to figure out if it's something all teams can work with, or if some would prefer issue re-use, and why, etc. Just want to get the conversation going because the status quo is "no bueno". I know @srosenberg is also thinking about auto-skipping tests without manual intervention so when we do that all of the surrounding conversations will be needed as well.

@jordanlewis I'm also +1 on that one, I think we've chatted about it a few times in the past. For the teams that I'm on I don't think the downsides would materialize but it could be a problem for teams that operate on a more "ad-hoc" basis and might miss stuff.

**Comment by irfansharif** [comment]
GitHub also lets you move issues across repo boundaries; I would love to forklift out all machine generated ones (sentry, roachtests, teamcity) into their own things. You should still be able to cross link across repos (though I don’t know if “Closes cockroachdb/sentry#42” would work. Hand written issues are high signal, and I would love to not have to sift through auto filed ones to learn about recent ideas.

**Comment by srosenberg** [comment]
> The reason for this is that the test failure issues create clutter and mess in our main repo.

@jordanlewis Sorry to be dense, but I am not yet seeing the issue you're referring to since everything can be organized according to label(s). Could you please give an example where test failures created hard to manage clutter.

**Comment by srosenberg** [comment]
@tbg What's your suggesting for things like cluster provisioning errors? It's not something we can control, although we do plan to alleviate it by a better provisioning scheme which uses regions more uniformly. For now, we're using append to existing issue purely for tracking the types of provisioning errors and their frequencies; e.g., https://github.com/cockroachdb/cockroach/issues/78035#issuecomment-1118267793

**Comment by jordanlewis** [comment]
The main issue view, unfiltered, looks cluttered if there are a lot of open test failures. Especially from the perspective of external customers or users.

This is not the biggest deal in the world and if it makes things significantly more annoying I am happy to drop it. I just thought I'd bring it up since this moment seems like one where we could make some changes all at once.

**Comment by tbg** [comment]
> @tbg What's your suggestion for things like cluster provisioning errors? It's not something we can control, although we do plan to alleviate it by a better provisioning scheme which uses regions more uniformly. For now, we're using append to existing issue purely for tracking the types of provisioning errors and their frequencies; e.g., https://github.com/cockroachdb/cockroach/issues/78035#issuecomment-1118267793

It's not clear what to do about cluster creation failures. It's not even clear that we should treat them as "test failures" since they often "can't be fixed". But if the primary goal is to track their frequency, etc, re-using the issue threads is not a good idea here either. You can't label a "comment", so by mixing all cluster creation failures in one issue we make it harder to, say, pinpoint which clusters we are most likely failing to create, etc. But of course posting separate issues will create a lot of noise. In the end, I think cluster creation issues just need to be ingested into some database so that we can query it whichever way we please. We need to have a way to be alerted to persistent failures to create a cluster (say the same config fails for more than four days in a row), btw (I'm not sure anybody looks at the noisy cluster-create thread; at least I have long unfollowed it since it isn't easy to do anything about most failures there).
