### ISSUE TITLE
changefeedccl: Support interval expressions for cursor

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#82350]
Cursor requires hlc.Timestamp to be specified.
This is very hard to get right.  Usually involves querying jobs table to pick up current cursor, or executing now() query and converting it to nanoseconds, etc.
We should support interval expressions so that `create changefedd ... with cursor='now() - interval 12h'` works.

Jira issue: CRDB-16425

**Comment by biradarganesh25** [comment]
The current acceptable values for cursor are all of the formats mentioned here: https://www.cockroachlabs.com/docs/v22.1/as-of-system-time#parameters. After discussing with @miretskiy , that should be enough. Therefore in the PR, I am just adding additional testing.
To be more specific, for intervals, the user can specify something like "-3h" for cursor value. Valid time units are "us" , "ms", "s", "m", "h".
