### ISSUE TITLE
ttljob: make the TTL job compatible with multi-tenancy

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#82386]
At the moment, row-level TTL fails in multi-tenancy with:

`Unauthenticated desc = requested key /Meta2/Tenant/10/Table/105/1/NULL not fully contained in tenant keyspace /Tenant/1{0-1}`

After this setup:
```
CREATE TABLE t (v INT PRIMARY KEY) WITH (ttl_expire_after = '1 microsecond', ttl_job_cron = '@every 1s');
INSERT INTO t SELECT x FROM generate_series(1,100) g(x);
```

This is because the range scan operation is prohibited in multi-tenancy:

https://github.com/cockroachdb/cockroach/blob/aa56262a5e0457e9e56304ade5ca2b7673c8f75f/pkg/sql/ttl/ttljob/ttljob.go#L432-L435

This probably involves some work exposing available ranges for the given table through kvtenant interface: https://github.com/cockroachdb/cockroach/pull/67098/commits.

**For v22.1:** Alternatively, we could consider making this work for serverless for v22.1 temporarily by avoiding the range scan and assume that TTL is not partitioned by range.

Related: https://cockroachlabs.atlassian.net/browse/CC-7065, [slack convo](https://cockroachlabs.slack.com/archives/C04U1BTF8/p1654153575326459)

Jira issue: CRDB-16344
Epic CRDB-14592

**Comment by vy-ton** [comment]
X-post from Slack, we should backport this to 22.1
