### ISSUE TITLE
Unable to `DROP CONSTRAINT "primary"` since upgrading to v22.1 (affects cloud enterprise)

### ISSUE THREAD

**Issue by aeneasr** [cockroachdb/cockroach#82397]
**Describe the problem**

I am unable to use

```
BEGIN;
ALTER TABLE users DROP CONSTRAINT "primary";
ALTER TABLE users ADD CONSTRAINT "primary" PRIMARY KEY (city, name, id);
COMMIT;
```

to change the primary key of a table since upgrading to v22.1. This worked fine < v22.1.

**To Reproduce**

Follow the guide on https://www.cockroachlabs.com/docs/v22.1/add-constraint#changing-primary-keys-with-add-constraint-primary-key and change the primary key constraint of a migration:

```
cockroach demo
```

```sql
BEGIN;
ALTER TABLE users DROP CONSTRAINT "primary";
ALTER TABLE users ADD CONSTRAINT "primary" PRIMARY KEY (city, name, id);
COMMIT;
```

results in

```
ERROR: constraint "primary" of relation "users" does not exist
```

**Expected behavior**

No error, this worked fine before 22.1

**Environment:**
 - CockroachDB version 22.1
 - Server OS: Linux, macOS
 - Client app: All SQL clients
  
**Additional context**

Our migrations are broken and the software ([Ory Hydra](https://github.com/ory/hydra)) is unable to run on CockroachDB versions 22.1.

Jira issue: CRDB-16351

**Comment by aeneasr** [comment]
Trying to override the constraint name does not help:

```
cockroach demo
```

```
CREATE TABLE public.hydra_client (
   pk INT8 NULL,
   rowid INT8 NOT VISIBLE NOT NULL DEFAULT unique_rowid(),
   CONSTRAINT "primary" PRIMARY KEY (rowid ASC)
);

BEGIN;
ALTER TABLE hydra_client DROP CONSTRAINT "primary";
ALTER TABLE hydra_client ADD CONSTRAINT "primary" PRIMARY KEY (pk);
COMMIT;
```

```
ERROR: constraint "primary" of relation "hydra_client" does not exist
````

**Comment by aeneasr** [comment]
Creating the table using an explicit constraint name resolves this:

```
CREAT TABLE users (
  pk SERIAL NOT NULL
  CONSTRAINT "primary" PRIMARY KEY (pk ASC)
)
```

**Comment by rafiss** [comment]
I think this is because we changed the default name of the primary index, and it looks like you are unblocked, so I'm closing this.
