### ISSUE TITLE
sql: UX problem (maybe bug) in CREATE TABLE LIKE when the source table has an implicit PK

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#82401]
**Describe the problem**

A naive user would reach out for the simplest example they can imagine:

```sql
> CREATE TABLE t(x INT);
> CREATE TABLE u(LIKE t);
```

So far so good. But then... tears ensue:

```
> INSERT INTO u(x) VALUES(1);
ERROR: null value in column "rowid" violates not-null constraint
SQLSTATE: 23502
```

The problem is revealed with SHOW CREATE:
```
  table_name |                       create_statement
-------------+----------------------------------------------------------------
  u          | CREATE TABLE public.u (
             |     x INT8 NULL,
             |     rowid INT8 NOT VISIBLE NOT NULL,
             |     rowid_1 INT8 NOT VISIBLE NOT NULL DEFAULT unique_rowid(),
             |     CONSTRAINT u_pkey PRIMARY KEY (rowid_1 ASC)
             | )
```

The implicitly created `rowid` from the original table was copied over **with its NOT NULL constraint, but without its DEFAULT clause** and then another one was created on top.

**To Reproduce**

see above

**Expected behavior**

The simple example "just works" without additional syntax.  **Make it compatible with PostgreSQL, which does not have this obstacle.**

Generally, LIKE should probably do some extra processing if it copies over NOT NULL columns that are also not visible.

I think at the very least it should produce a NOTICE with an explanation of what to do (e.g. "if that's not what you want, use `EXCLUDING rowid`"). 

But really since pg does not have this problem, this should be treated as a pg compat bug.

Also we need docs to explain this. At least as a known limitation.

The current doc page (https://www.cockroachlabs.com/docs/stable/create-table.html#create-a-new-table-from-an-existing-one) only shows an example with an explicit PK, and thus does not run into the example.

**Environment:**

v22.1

cc @rafiss @mgartner for triage.

Jira issue: CRDB-16354

**Comment by ajwerner** [comment]
My inclination is to fix this in the legacy schema changer so that we have the test coverage for when we port this feature as a whole to the declarative schema changer.

**Comment by ajwerner** [comment]
@jasonmchan I'm going to ask you to try to take a stab at it.

**Comment by otan** [comment]
hmm, `CREATE TABLE t ( LIKE a)` (in PG) deliberately does not copy any defaults, unless you do `CREATE TABLE t (LIKE a INCLUDING DEFAULTS)`. i kind of wonder whether this is not really a "bug" per se.

**Comment by knz** [comment]
I found another problem (the one that Oliver suggested):

Use `cockroach demo --global` to verify

```sql
> create database mrdb primary region = "us-east1";
> set database = mrdb;
> create table t(x int) locality regional by row;
> create table u(like mrdb.t);
> insert into u(x) values (1);
ERROR: null value in column "crdb_region" violates not-null constraint
SQLSTATE: 23502
```

alas:

```
> show create table mrdb.u;
   table_name   |                         create_statement
----------------+--------------------------------------------------------------------
  mrdb.public.u | CREATE TABLE public.u (
                |     x INT8 NULL,
                |     crdb_region public.crdb_internal_region NOT VISIBLE NOT NULL,
                |     rowid INT8 NOT VISIBLE NOT NULL,
                |     rowid_1 INT8 NOT VISIBLE NOT NULL DEFAULT unique_rowid(),
                |     CONSTRAINT "primary" PRIMARY KEY (rowid_1 ASC),
                |     FAMILY "primary" (x, crdb_region, rowid, rowid_1)
                | ) LOCALITY REGIONAL BY TABLE IN PRIMARY REGION
```

**Comment by knz** [comment]
I think the problem is that _any_    **implicit** column created by crdb, which the app doesn't know about, should probably be ignored by CREATE LIKE.

**Comment by chengxiong-ruan** [comment]
> I think the problem is that _any_ **implicit** column created by crdb, which the app doesn't know about, should probably be ignored by CREATE LIKE.

good catch!
