### ISSUE TITLE
bazel: path to CRDB log is incorrect after a failed dev test

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#82413]
If a test fails on my mac, I can't seem to cd to the directory that the error msg suggests would have my CRDB log: 
```
 test_log_scope.go:76: test logs captured to: /private/var/tmp/_bazel_michaelbutler/13ba282fa2b19539d0c969c1113bb37c/sandbox/darwin-sandbox/15/execroot/com_github_cockroachdb_cockroach/_tmp/a340ebbb90405137386a0ed860023d6b/logTestRandomParquetExports1960928243
```

Workaround: If I pass the `--show-logs` dev arg, the crdb log prints to stdout without a problem. 

Jira issue: CRDB-16363

Epic CRDB-15061

**Comment by rickystewart** [comment]
Bazel will clean up the `tmpdir` for you after a test unless you pass the (Bazel) argument `--sandbox_debug`. You can also pass a custom `--test_tmpdir=/path/to/tmpdir` and you'll be able to find the files in that persistent directory after the test ends.

There is confusion about `test_tmpdir` across the board I think. I am going to get in a fix for #72918 that covers this as well.
