### ISSUE TITLE
GRANT privilege ON sequence incorrect behavior

### ISSUE THREAD

**Issue by ecwall** [cockroachdb/cockroach#82414]
Unable to grant on a sequence using `GRANT privilege ON sequence` syntax

```
statement ok
create sequence seq;

statement ok
create user testuser;

# should be statement ok
statement error pgcode 0LP01 invalid privilege type USAGE for table
GRANT SELECT ON seq TO testuser WITH GRANT OPTION

# should be true
query B
SELECT has_sequence_privilege('testuser', 'seq', 'SELECT WITH GRANT OPTION')
----
false
```

Jira issue: CRDB-16364
Epic CRDB-14491

**Comment by rafiss** [comment]
interesting, if you change it to `GRANT USAGE, SELECT, UPDATE ON SEQUENCE seq TO testuser WITH GRANT OPTION;` it works.

**Comment by rafiss** [comment]
cc @ZhouXing19 who just added this syntax. any thoughts on why it's like this?

**Comment by ZhouXing19** [comment]
It's because we didn't implement the semantics for `GRANT ... ON seq_name`. We only added `GRANT ... ON SEQUENCE seq_name`. Will make a PR to fix this.
