### ISSUE TITLE
`./dev doctor` should check for the `libproj4.3+` library.

### ISSUE THREAD

**Issue by surahman** [cockroachdb/cockroach#82445]
**Is your feature request related to a problem? Please describe.**
When `go test` commands are run from the CLI or from within an IDE they will raise an error if the `libproj` library is not found by the linker. IDEs will run the `go test ...` command and not the `dev test ...` command. When the `dev test ...` command is run Bazel downloads and sets up the dependency for `libproj` so the error does not arise.

https://github.com/cockroachdb/cockroach/blob/0fdac09ca1119b494661e1e1f64ea291d8649782/c-deps/BUILD.bazel#L62-L109

https://github.com/cockroachdb/PROJ/blob/c8ff95857beb3027b5aa3d15726795570f38eccb/NEWS#L109

https://github.com/cockroachdb/PROJ/blob/c8ff95857beb3027b5aa3d15726795570f38eccb/ChangeLog#L632

**Describe the solution you'd like**
The `./dev doctor` script should check that the `libproj4.3` library is available on the build system to be able to run tests from the `go test ...` command.

**Describe alternatives you've considered**
Document the requirement and let people find and install the dependency when they encounter the error.

**Additional context**
The `libproj` library is essential when trying to debug and run tests within `pkg/sql/` from inside an IDE.

Jira issue: CRDB-16389

**Comment by surahman** [comment]
To add a little more context

```bash
go test github.com/cockroachdb/cockroach/pkg/sql/sem/tree
# github.com/cockroachdb/cockroach/pkg/geo/geoproj
/usr/bin/ld: cannot find -lproj: No such file or directory
collect2: error: ld returned 1 exit status
FAIL	github.com/cockroachdb/cockroach/pkg/sql/sem/tree [build failed]
FAIL

```
There might be other dependencies which are required.

**Comment by surahman** [comment]
**_A Potential solution for Debian/Ubuntu on AMD64 Arch_**

Install the following 3 packages in this order:

1. [`proj-data_4.9.3-2_all`](https://ubuntu.pkgs.org/18.04/ubuntu-universe-arm64/proj-data_4.9.3-2_all.deb.html)
2. [`libproj12_4.9.3-2_amd64`](https://ubuntu.pkgs.org/18.04/ubuntu-universe-amd64/libproj12_4.9.3-2_amd64.deb.html)
3. [`libproj-dev_4.9.3-2_amd64`](https://ubuntu.pkgs.org/18.04/ubuntu-universe-amd64/libproj-dev_4.9.3-2_amd64.deb.html)

I used `dpkg` to install them:
```bash
sudo dpkg -i proj-data_4.9.3-2_all.deb; \
sudo dpkg -i libproj12_4.9.3-2_amd64.deb; \
sudo dpkg -i libproj-dev_4.9.3-2_amd64.deb
```

**Comment by surahman** [comment]
There are other errors related to missing modules or files.
```bash
go test github.com/cockroachdb/cockroach/pkg/sql/rowenc

# github.com/cockroachdb/cockroach/pkg/server/status
../../server/status/runtime_jemalloc.go:21:11: fatal error: jemalloc/jemalloc.h: No such file or directory
   21 | // #include <jemalloc/jemalloc.h>
      |           ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

I have initialized all the git submodules. The `c-deps/jamalloc/` folder does exist but there is no `jemalloc.h`.
```bash
git submodule update --init --recursive
git submodule foreach --recursive git fetch
```

Running `dev test pkg/sql/rowenc` does not yield this compiler error.

**Comment by rickystewart** [comment]
Hi @surahman -- `dev generate cgo go` will generate the extra files in your workspace to link the `bazel`-built `jemalloc`, `proj` etc.

**Comment by surahman** [comment]
@rickystewart thank you, that has fixed the debug and test run issues from within the IDE.
