### ISSUE TITLE
sql: profiler tags aren't extended to distsql

### ISSUE THREAD

**Issue by cucaroach** [cockroachdb/cockroach#82464]
The profiler tags help on customer issues, in particular the pprof-summary.sh uses these to get CPU usage to query attribution which is very helpful.  Unfortunately we don't apply any tags to distsql remote entry points so its an incomplete picture.  One wrinkle is that profiler tags can pollute the Graph view with extra nodes, can we make it possible to remove those?   Probably the most important tag is sql.no.constants?  We could also add flow ID, gateway node.  Would a txn id or connection id also be useful?

Jira issue: CRDB-16407

**Comment by cucaroach** [comment]
This issue needs some flushing out, like if we add these tags where/how do they get observed?   The would show up in "stacks with labels" in debug.zip but can we do something like pprof-summary for all nodes?  Also is there any way to show a queries CPU usage across cluster?  Can we show what queries are contributing to CPU usage on a particular node even if some queries originate from a different gateway node?  This can be flushed out in separate issues I guess, its just that adding the tags won't do much by itself.

**Comment by nvanbenschoten** [comment]
> The would show up in "stacks with labels" in debug.zip but can we do something like pprof-summary for all nodes?

Profiler labels also end up inside CPU profiles. See https://rakyll.org/profiler-labels/. So even without cluster-wide summarization, a CPU profile of an overloaded node whose overload is coming from a leaf DistSQL processor would now point at the query causing the overload. That's a significant improvement in observability.
