### ISSUE TITLE
rangefeed: ensure correct use of exclusive start time

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#82488]
The start time of rangefeeds (i.e. `RangeFeedRequest.Header.Timestamp`) is exclusive; the first possible event (including catchup scans) will be at `Timestamp.Next()`. This allows using a previous checkpoint timestamp to resume a rangefeed without getting duplicates at the checkpoint timestamp, and shares the semantics of incremental backups (see e.g. `storage.ExportOptions.StartTS`).

However, as discussed in https://github.com/cockroachdb/cockroach/pull/82451#issuecomment-1147561089, our rangefeed clients often assume that the start time is inclusive. This will lead to dropped messages if they happen to fall exactly on the start time.

We need to audit our client code -- e.g. `pkg/kv/kvclient/rangefeed`, `pkg/ccl/changefeedccl/kvfeed`, and CDC in general -- to make sure they use the exclusive timestamp semantics. Several call sites are known to get this wrong, e.g.:

https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/changefeedccl/kvfeed/kv_feed.go#L254

https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go#L496-L496

Alternatively, we can change the API to use an inclusive start time. However, this would entail cross-version compatibility concerns that we may want to avoid.

Jira issue: CRDB-16418

Epic CRDB-9179

**Comment by ajwerner** [comment]
@miretskiy can you figure out if https://github.com/cockroachdb/cockroach/pull/91116 needs to be backported? I sort of think the answer is no because it doesn't seem that https://github.com/cockroachdb/cockroach/pull/82451 was backported. What will it take to close this issue (which describes the bug I fixed).

**Comment by erikgrinaker** [comment]
Note that #82451 did not change the visible catchup scan behavior: that was always exclusive, even before that patch, because of the explicit filtering done in the catchup scan. That patch simply made the internal incremental iterator use the appropriate exclusive time bound as well, rather than an inclusive one, but any event matching the inclusive time bound would have been filtered out by the catchup scan logic.

**Comment by ajwerner** [comment]
In that case, how was https://github.com/cockroachdb/cockroach/pull/79525 ever correct?

**Comment by erikgrinaker** [comment]
It wasn't.

**Comment by ajwerner** [comment]
Okay, sounds like backports of https://github.com/cockroachdb/cockroach/pull/91116 to 22.1 are in order.
