### ISSUE TITLE
backupccl: TestChainingWithDatabaseExpansion failed under race

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#82485]
TestChainingWithDatabaseExpansion flaked in `make testrace` https://teamcity.cockroachdb.com/viewLog.html?buildId=5390097&problemId=2684

Jira issue: CRDB-16610

**Comment by adityamaru** [comment]
Artifacts are gone, and `TestScheduleChainingWithDatabaseExpansion` isn't skipped under race so I'm assuming this fixed itself.

**Comment by msbutler** [comment]
another flake https://teamcity.cockroachdb.com/viewLog.html?buildId=6562358&buildTypeId=Cockroach_UnitTests

**Comment by adityamaru** [comment]
Artifacts are long gone but I assume this was another midnight schedule flake. The test is not skipped unless we are very close to midnight.
