### ISSUE TITLE
ui: statements page uses generic sans-serif font instead of Source Sans Pro

### ISSUE THREAD

**Issue by sjbarag** [cockroachdb/cockroach#82487]
**Describe the problem**

Looks like the `/statement/:id` page (in this case `statement/true/:id?appNames=`) doesn't use the intended "Source Sans Pro" font, and instead falls back to the generic `sans-serif` font.

**To Reproduce**

1. `cockroach demo movr`, load the web UI, and click on any statement on the "SQL Activity" page
2. Open browser's dev tools and select any bit of text in the tables below the rendered statement.
3. In Firefox, you'll see "sans-serif" underlined, indicating that it's the active font in that list of families.  In either browser, change the active `font-family` rule to fall back to `serif` or `monospace` instead of `sans-serif` to highlight the difference:

![use-serif-to-highlight-difference](https://user-images.githubusercontent.com/665775/172244746-4ac42bbd-5fd8-4db5-ba8c-5452f00ddd2b.jpg)

**Expected behavior**
Fonts throughout the DB Console UI are consistent

**Additional data / screenshots**
![system-sans-serif-instead-of-source-sans-pro](https://user-images.githubusercontent.com/665775/172244771-1468a0fd-bcbb-4ead-8841-baa54c722ca5.jpg)

**Environment:**
 - CockroachDB version: I repro'd on a WIP edge build of cockroach, but anything based on 4dcd87f646 (Merge #82106, 2022-05-31) should repro.  Haven't gone back in time to find where this started though!
 - Server OS: macOS
 - Client app: any browser

**Additional context**
I imagine this is one of two root-causes:
1. There's a "Source Sans Pro.woff" and ".woff2" font in the cockroach repo, but it isn't used in a `@font-face` rule (this may be intended because Bazel doesn't support files with spaces in their names).  In this case, the CSS rule is correct but the dependent rule hasn't been configured.
2. The existing `@font-face` rules are correct, and this was supposed to be `font-family: "SourceSansPro-Regular", sans-serif` which appears to render the intended font.

This may apply to other components!  I haven't gone looking for more :)

Jira issue: CRDB-16606

**Comment by maryliag** [comment]
No longer a priority
