### ISSUE TITLE
streamingccl: job system retry logic is inappropriate for ingestion job 

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#82511]
**Describe the problem**

The streaming ingestion job depends on the job system level retry in order to reconnect after failures.  However, every time it does this, the `num_runs` counter is increased. This impacts the backoff used by the jobs system for future retries.  As a result, after some number of transient failures, the backoff can be pushed all the way to its maximum of 24 hours.  In the case of transient errors, this will unnecessarily increase the RPO that is achievable by the stream.

The ingestion job could do the same thing that the changefeed job does and reset the job's run count whenever it reaches a steady state. Or, we could fix this in the job system by allowing some job types to have different retry policies.

Jira issue: CRDB-16495

**Comment by shermanCRL** [comment]
Is this done, or more we intend to do? Looks like:

- https://github.com/cockroachdb/cockroach/pull/77240

cc @samiskin

**Comment by stevendanna** [comment]
I think this is done from the perspective of streaming.  We have another ticket somewhere for jobs to take a look at whether the retry logic should change more generally.
