### ISSUE TITLE
Add temporary credentials parameter for GCP storage and KMS

### ISSUE THREAD

**Issue by rhu713** [cockroachdb/cockroach#82524]
Currently there's a method to use temporary credentials in S3 and AWS KMS involving providing the Access ID, Secret Key, and a Session Token. There's not an equivalent for this in GCS and GCP KMS as the `CREDENTIALS` parameter is meant for long-lived credentials. 

We should add this `TEMPORARY_TOKEN` parameter and support providing OAuth2 tokens as credentials to access GCP.

Jira issue: CRDB-16498

**Comment by adwittumuluri** [comment]
If the operator provides both the `TEMPORARY_TOKEN` and `CREDENTIALS` param, do we surface an error? Is it easier to add a `TYPE` and re-use `CREDENTIALS`? No opinions (as an operator) - whatever makes the implementation easier for CRDB.
