### ISSUE TITLE
kv: add cluster setting to disable rangelog events

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#82535]
Splits, merges, and rebalances all log transactionally to the `system.rangelog` table. This introduces a dependency that can cause issues when the `system.rangelog` table is unavailable.

We should add a cluster setting that allows users to disable writes to the rangelog in `Store.insertRangeLogEvent`. We can either unify this with `StoreConfig.LogRangeEvents` or push that into `Store.insertRangeLogEvent` as well.

Jira issue: CRDB-16501

**Comment by ajwerner** [comment]
If you want to be more sad, IIRC, this operation also ends up reading the rangelog descriptor from system.descriptor, so it incurs issues if that table is unavailable too.
