### ISSUE TITLE
kv: decide whether to write rangelog events transactionally or not 

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#82538]
We currently have the following TODO, which applies to splits, merges, and rebalances:
https://github.com/cockroachdb/cockroach/blob/abc8afd8a244f2c6e85cdfe50119ef18f72602e2/pkg/kv/kvserver/replica_command.go#L703-L706

Let's either address it or remove it.

There are pros and cons to logging to the rangelog transactionally. Let's enumerate them all. For starters, one benefit to not doing so is that we can make the rangelog writes best-effort.

Jira issue: CRDB-16517

**Comment by nvanbenschoten** [comment]
@irfansharif mentions that another alternative here is to opt the `system.rangelog` out of range size backpressure. We do allow ranges in `system.rangelog` to split and so the backpressure should only be an issue if a range in `system.rangelog` can't split for some reason (e.g. range unavailability). In those cases, making the entire write best-effort may be a more general solution here.

**Comment by tbg** [comment]
I'm in favor of making writes to the range log optional/best-effort but really to discuss phasing it out in the medium term. In effect, we are logging into a replicated table single point of failure and more so recruiting important and expensive transactions to do that write. I don't think that we would make this choice if we started from first principles. I suspect we would have added a log channel for such events, possibly structured, and left it at that. This is both easier and harder to work with. It's not a SQL table, but structured logs can be parsed efficiently and let's face it, the most common operation is pulling the last few operations by rangeID, which can be done easily via grep.

**Comment by miraradeva** [comment]
Discussion on possible solutions: https://docs.google.com/document/d/1hZJpOV76OCqVmhXOhnznmQAhI8644Fsk4lMvCr8BFYY
