### ISSUE TITLE
storage: pebble cross version testing

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#82544]
**Is your feature request related to a problem? Please describe.**

In cockroachdb/pebble#1612, we added a cross-version metamorphic test. The existing Pebble metamorphic tests are wrapped up in a nightly roachtest, kicked off by TeamCity. We'll need to do something similar for the cross-version testing.

**Describe the solution you'd like**

Wire up roachtest / CI to boot the Pebble cross-version metmorphic tests nightly.

Jira issue: CRDB-16504

Epic CRDB-20465

**Comment by celiala** [comment]
Marking to GA blocker, as [per thread](https://cockroachlabs.slack.com/archives/CAC6K3SLU/p1666639880885369?thread_ts=1666639545.115589&cid=CAC6K3SLU).
