### ISSUE TITLE
Allow TTL job to be canceled part way through

### ISSUE THREAD

**Issue by ecwall** [cockroachdb/cockroach#82546]
We should be able to cancel a long running TTL job after it started

More context here
https://github.com/cockroachdb/cockroach/pull/81917#pullrequestreview-991264715

Epic CRDB-18322
Jira issue: CRDB-16581

**Comment by rafiss** [comment]
Every iteration of `runTTLOnRange` has this check:
https://github.com/cockroachdb/cockroach/blob/fe11e4b82b2e11727c8090d93c6e3c941f447d33/pkg/sql/ttl/ttljob/ttljob_processor.go#L295

So I wonder if we actually need anything else here?

**Comment by ecwall** [comment]
> Every iteration of `runTTLOnRange` has this check:
> 
> https://github.com/cockroachdb/cockroach/blob/fe11e4b82b2e11727c8090d93c6e3c941f447d33/pkg/sql/ttl/ttljob/ttljob_processor.go#L295
> 
> So I wonder if we actually need anything else here?

The job `Resumer` interface lets you pause and resume a job, but that just starts the DistSQL processors again each time in our impl so it would be running the same thing multiple times.
```
type Resumer interface {
	// Resume is called when a job is started or resumed. execCtx is a sql.JobExecCtx.
	Resume(ctx context.Context, execCtx interface{}) error
```

**Comment by rafiss** [comment]
Closing since the job is cancel-able. If necessary, we can make a separate ticket for tracking the ability to pause and then resume from a checkpoint created when it was paused, but that doesn't seem like a high priority.
