### ISSUE TITLE
kv,bulkio: throttle per-store column/index backfill requests

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#82556]
**Is your feature request related to a problem? Please describe.**

_Using this issue to track the general case of index/column backfill induced performance impact._

In support escalations (https://github.com/cockroachlabs/support/issues/1628) we've observed that column backfills for a large table was able to consume all available disk write bandwidth on stores (caps out at 150mb/s in the graph below, what the store was provisioned with), resulting in starvation for foreground requests on those stores. The bandwidth saturation led to log commit p99s in the order of seconds (see graph below). 

<img width="708" alt="image" src="https://user-images.githubusercontent.com/10536690/172488782-111ad9dc-f781-4d5c-88cf-7b96d5e839ea.png">

<img width="922" alt="image" src="https://user-images.githubusercontent.com/10536690/172488815-569fc456-b436-4a22-9c33-644cc9437f5e.png">

In internal experimentation (#admission-control) we've also observed throughput/latency effects due to aggressive follower write activity.

**Describe the solution you'd like**

Disbursing byte-sized IO tokens over time for requests serving these large + long running bulk operations, controlling how much bandwidth use for background operations/ensuring foreground traffic has available capacity. Or something simpler (+backportable) shorter term that aims for a bandwidth target and paces incoming batch requests accordingly. Or perhaps introducing simpler client side knobs to control the rates at which we issue these requests to KV.

**Additional context**

Relates broadly to https://github.com/cockroachdb/cockroach/issues/75066 + https://github.com/cockroachdb/cockroach/issues/79092. Unclear if addressed by https://github.com/cockroachdb/cockroach/pull/82440, need a repro. 

Jira issue: CRDB-16542

**Comment by irfansharif** [comment]
> @dt suggested a fairly straightforward short-term protection here in 

For posterity:

```
func (s *Store) maybeThrottleBatch(
	ctx context.Context, ba roachpb.BatchRequest,
) (limit.Reservation, error) {
	...
		if ba.AdmissionHeader.Priority == int32(admissionpb.BulkNormalPri) {
			before := timeutil.Now()
			if err := s.limiters.BulkBatchRate.WaitN(ctx, ba.TotalSize()); err != nil {
				return nil, err
			}
			_ = timeutil.Since(before)
			// todo: collect a metric, log long waits.
		}
```

**Comment by dt** [comment]
> We may want to add such a throttling knob for each admissionpb.WorkPriority, as others like TTLLowPri might benefit from it.

Maybe one setting for "what is priority threshold show be subject to the low-pri limiter?" and then anything at/below that gets tossed at a single low-pri batch size limiter? I could see lots of separate ones being very hard to set correctly to add up to just the right number.

**Comment by irfansharif** [comment]
Lowering `bulkio.column_backfill.batch_size` works pretty effectively as a short-term mitigation. I'm going to leave this issue open for the more general per-store pacing of backfills through admission control.

**Comment by irfansharif** [comment]
x-linking https://github.com/cockroachdb/cockroach/issues/85641 + https://github.com/cockroachdb/cockroach/issues/83826.

**Comment by irfansharif** [comment]
https://github.com/cockroachdb/cockroach/issues/95563 is the tracking issue for admission control work.

**Comment by irfansharif** [comment]
https://github.com/cockroachdb/cockroach/issues/95563 is done.
