### ISSUE TITLE
CockroachDB does not log outbound network calls

### ISSUE THREAD

**Issue by catj-cockroach** [cockroachdb/cockroach#82551]
**Describe the problem**

CockroachDB does not log calls that make outbound connections, which makes it very difficult to audit if a connection is intentional or not. We should add this to the audit logs so we can ensure that these features are not being used maliciously.

**To Reproduce**

If possible, provide steps to reproduce the behavior:

1. Set up a multi-tenant CockroachDB cluster (for example, a serverless cluster).
2. Run `IMPORT` command against external site
3. Review the logs and `debug.zip` dump for information about the `IMPORT`
4. There should be no record of the IP address or domain the `IMPORT` was called against

**Expected behavior**

The jobs log should show the user ID that ran the import job, the tenant ID of the SQL tenant that the job was run for, and the URL that the import was called against.

**Environment:**

 - CockroachDB version: 21.2+
 - Environment: Kubernetes

Jira issue: CRDB-16578

**Comment by 1lann** [comment]
A small thing I want to clarify: Although we could technically achieve this via SQL audit logging, I don't think that's something we're looking to turn on at the moment for serverless clusters, and having a dedicated logging channel/message for any external network access would help greatly with auditing automation in the future, particularly for multi-tenant clusters.

If someone in the database team has any other suggestions on how we could more easily audit such external network calls in multi-tenant clusters, we're open to ideas.

**Comment by catj-cockroach** [comment]
Closing, replaced by https://github.com/cockroachdb/cockroach/issues/86408
