### ISSUE TITLE
gossip: gossip messages potentially aren't delivered correctly in client_raft_test.go

### ISSUE THREAD

**Issue by d4l3k** [cockroachdb/cockroach#8256]
Split out from #7684.

TestStoreRangeCorruptionChangeReplicas has to gossip the dead replicas multiple times because otherwise, the test fails.

We should investigate why those messages aren't being correctly sent out the first time.

**Comment by tamird** [comment]
Wasn't that pattern cribbed from some other test, too? We should
investigate that one as well.

**Comment by d4l3k** [comment]
Looks like this isn't actually an issue with gossip, just a race condition between setting `r.mu.destroyed` and `s.deadReplicas()`.
