### ISSUE TITLE
server: auto-derive --cache/--max-sql-mem from single allowable memory flag `--total-memory`

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#8260]
This is an intro-issue for memory management.
- allow flag to specify the desired amount of memory for cockroach to use (default to system memory).
- use above flag value to determine rocksdb cache
- add metrics/monitoring/alerting for allowed/free memory

Update by @dhartunian 
**Is your feature request related to a problem? Please describe.**
Currently, when memory constraints are overridden, we require the setting of at least 2 and soon 3 (https://github.com/cockroachdb/cockroach/pull/74662) CLI flags to properly set memory constraints on CRDB.

This creates confusion for customers and a burden of deciding their own memory percentage allocations instead of sticking to our built-in split of 25% each for sql and cache memory, which is easily abandoned when custom limits are set.

Additionally, in cases where system memory is not detected correctly by CRDB, it would be useful to easily tell the node how much total memory is available and have the various constraints set automatically.

**Describe the solution you'd like**
A new CLI flag `--total-memory` informs CRDB how much total memory is available and allows the `--max-sql-memory`, `--cache`, and `--max-tsdb-memory` to be set automatically from that number.

The flag could be set along with all 3 others as long as their values are set to percentages:
* valid: `./cockroach start --total-memory=30gb`
* valid: `./cockroach start --total-memory=30gb --max-sql-memory=30% --cache=10% --max-tsdb-memory=1%`
* valid: `./cockroach start --total-memory=30gb --max-sql-memory=30%` (cache remains at 25%, tsdb at 1%)
* invalid: `./cockroach start --total-memory=30gb --max-sql-memory=10gb` (cache remains at 25% of total, tsdb at 1%)

See discussion on https://github.com/cockroachdb/cockroach/pull/74662

Jira issue: CRDB-6366

**Comment by mberhault** [comment]
the cache flag seems to be sufficient for now. @petermattis: close this for now?

**Comment by petermattis** [comment]
I'm fine with closing until we have a more concrete action to take.

**Comment by bdarnell** [comment]
I think the idea here is that instead of having two memory-related flags (cache and sql, and maybe more in the future), we should have one flag for the total memory cockroach should be allowed to use and then we subdivide that, so that users only need to specify one flag if they don't want to customize the ratio of cache to sql memory.

**Comment by petermattis** [comment]
Ok, reopening and leaving marked as Later.

**Comment by mberhault** [comment]
This is two years old now. We should either come up with something a bit more concrete or close this.

**Comment by mberhault** [comment]
@petermattis: memory management is still an issue, but this ticket is not useful other than to mention it. Still, if nothing else is filed, this could be it.

**Comment by ajwerner** [comment]
@vladdy this seems like what you want for memory limits, yeah?

**Comment by knz** [comment]
renewed interest from #76535
