### ISSUE TITLE
Add which index(es) were used in the plan details console page

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#82615]
We should complete the [V2 experience for persisted stats ](https://www.figma.com/file/xdmwvnFQd6KkO9RJ0XLDH0/22.1_SQL-obsrv_query-performance?node-id=3488%3A10430)which includes plan regression detection by adding which indexes were selected in the EXPLAIN plan details page. 

This will allow one to quickly correlate high-level metrics on index inefficiencies (e.g. stale stats) that may have caused plans to regress. 

Jira issue: CRDB-16586

Epic CRDB-20388

**Comment by maryliag** [comment]
@Annebirzin can you add here the link for the design for this?

**Comment by Annebirzin** [comment]
@maryliag I believe this is referring to [this page](https://www.figma.com/file/xdmwvnFQd6KkO9RJ0XLDH0/22.1_SQL-obsrv_query-performance?node-id=3488%3A22100) in the Figma designs, where we include a table of indexes below the explain plan.

@kevin-v-ngo can you confirm? 

![Screen Shot 2022-06-28 at 4 30 47 PM](https://user-images.githubusercontent.com/51920721/176279627-dbfe2572-3fde-49b7-9f5e-fd35b7707688.png)
