### ISSUE TITLE
Add information on MVCC garbage data on the databases page

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#82617]
We should add observability into 'dead'/MVCC garbage data that has not been cleaned up which can potentially be impacting workload performance. 

This relates to the following [issue](https://github.com/cockroachdb/cockroach/issues/72048) but provides a higher-level view at the table level on the Databases page.

One potential user flow: SQL Activity -> Statements -> Details view -> Plan View -> [Index details](https://github.com/cockroachdb/cockroach/issues/82615)

[Slack context](https://cockroachlabs.slack.com/archives/C02R38EEPNV/p1654679913454319).

Column name: % of Non-live Data

Tool tip description: % of total logical data that has not been modified (updated or deleted). A low percentage can cause statements to scan more data ([MVCC values](https://www.cockroachlabs.com/docs/stable/architecture/storage-layer.html#mvcc)) than required, which can reduce performance.

Jira issue: CRDB-16540

**Comment by petermattis** [comment]
> One potential user flow: SQL Activity -> Statements -> Details view -> Plan View -> https://github.com/cockroachdb/cockroach/issues/82615

I would have imagined going from Databases -> Tables to see if any table has a significant amount of garbage. %garbage could be a column next to the table size. Probably want the information in both locations.

**Comment by maryliag** [comment]
Need help to understand info from system.descriptor table and garbage info. I’m trying to get percentage of MVCC garbage per table, so using table movr.public.promo_codes as an example, I’m using a this query (based on the thread).

```
select
        crdb_internal.pb_to_json('cockroach.sql.sqlbase.Descriptor', d.descriptor)->'database'->>'name' as db_name,
crdb_internal.pb_to_json('cockroach.sql.sqlbase.Descriptor', t.descriptor)->'schema'->>'name' as schema_name,
        crdb_internal.pb_to_json('cockroach.sql.sqlbase.Descriptor', t.descriptor)->'table'->>'name' as table_name,
        round (100 - (crdb_internal.range_stats(ranges.start_key)->>'live_bytes')::int * 100 /
                ((crdb_internal.range_stats(ranges.start_key)->>'key_bytes')::int +
                (crdb_internal.range_stats(ranges.start_key)->>'val_bytes')::int), 2) as garbage_percentage
from
        crdb_internal.ranges_no_leases ranges
        join system.descriptor as t on table_id = t.id
        join system.descriptor as d on (crdb_internal.pb_to_json('cockroach.sql.sqlbase.Descriptor', t.descriptor)->'table'->>'parentId')::int = d.id
where
crdb_internal.pb_to_json('cockroach.sql.sqlbase.Descriptor', d.descriptor)->'database'->>'name' = 'movr' AND
crdb_internal.pb_to_json('cockroach.sql.sqlbase.Descriptor', t.descriptor)->'table'->>'name' = 'rides'
AND
        ((crdb_internal.range_stats(start_key)->>'key_bytes')::int + (crdb_internal.range_stats(start_key)->>'val_bytes')::int) != 0
order by garbage_percentage desc;
```

which returns 9 rows
```
  db_name | schema_name | table_name | garbage_percentage
----------+-------------+------------+---------------------
  movr    | NULL        | rides      |               0.00
  movr    | NULL        | rides      |               0.00
  movr    | NULL        | rides      |               0.00
  movr    | NULL        | rides      |               0.00
  movr    | NULL        | rides      |               0.00
  movr    | NULL        | rides      |               0.00
  movr    | NULL        | rides      |               0.00
  movr    | NULL        | rides      |               0.00
  movr    | NULL        | rides      |               0.00
(9 rows)
```

So question 1: why there are so many rows returned? I would imagine having just one. (Update: get info this is info per range, so looks like I need to add all info here to get total)


To the second issue, on this result, the schema column is actually returning `NULL` for all rows, which is why on my `WHERE` I didn’t add the schema to it, so question 2: is that expected (having the null on the column)? how can I select the right table with the right database and schema here?


question 3: is there a better way of getting MVCC garbage info per table? let me know

**Comment by maryliag** [comment]
Turns out I was using the wrong column on the query above. Updated version will return the correct information.

```
select
        crdb_internal.pb_to_json('cockroach.sql.sqlbase.Descriptor', d.descriptor)->'database'->>'name' as db_name,
        ranges.schema_name,
        crdb_internal.pb_to_json('cockroach.sql.sqlbase.Descriptor', t.descriptor)->'table'->>'name' as table_name,
        round (100 - (crdb_internal.range_stats(ranges.start_key)->>'live_bytes')::int * 100 / 
                ((crdb_internal.range_stats(ranges.start_key)->>'key_bytes')::int +
                (crdb_internal.range_stats(ranges.start_key)->>'val_bytes')::int), 2) as garbage_percentage
from
        crdb_internal.ranges_no_leases ranges
        join system.descriptor as t on table_id = t.id
        join system.descriptor as d on (crdb_internal.pb_to_json('cockroach.sql.sqlbase.Descriptor', t.descriptor)->'table'->>'parentId')::int = d.id
where
        ((crdb_internal.range_stats(start_key)->>'key_bytes')::int + (crdb_internal.range_stats(start_key)->>'val_bytes')::int) != 0
	and crdb_internal.pb_to_json('cockroach.sql.sqlbase.Descriptor', d.descriptor)->'database'->>'name' = 'movr'
	and ranges.schema_name = 'public'
	and crdb_internal.pb_to_json('cockroach.sql.sqlbase.Descriptor', t.descriptor)->'table'->>'name' = 'rides'
order by garbage_percentage desc;
```

I'm assuming I can add the total for all rows and then calculate the percentage now.

**Comment by maryliag** [comment]
Would you mind explaining a little more about the virtual table idea? Trying to understand how the view creation instead of running this query on Table details request would improve performance.

FYI, made a slight change to your query, to make sure we're not dividing by 0
`SELECT COALESCE((total - live) / NULLIF(total,0), 0)::FLOAT as garbage_percentage FROM aggregated `

**Comment by ajwerner** [comment]
The problem I have with this request is that `crdb_internal.range_stats` sends an RPC per range in the table. This is the same problem I have with `crdb_internal.ranges`. If the table has 10k ranges and the average latency is 50ms (common in a multi-region cluster), this will take 8.3 minutes. We'd want to parallelize fetching of the range stats.

The Table details query does some truly magical things:
1) It issues a per-node query to compute the disk usage for a given table as opposed to a per-range query. These per-node queries are exceedingly uncommon in our system in terms of the KV layer and can violate some principles. They also don't have access to detailed metadata.
2) It issues those per-node queries in parallel. See [here](https://github.com/cockroachdb/cockroach/blob/ab85bfcddf80cc8d9ba8affaba9faaffaecadf4e/pkg/server/admin.go#L1185-L1215)

My suggestion is that we also parallelize the fetching of these range stats so that we can cut down the total time to fetch all of these stats on a big table by a bunch. 

----

While I've got you, does the `TableStatsRequest` work for secondary tenants?

**Comment by maryliag** [comment]
> does the TableStatsRequest work for secondary tenants?

I don't believe it will work, because we scan the "meta" keyspace, so it will probably fail [here](https://github.com/cockroachdb/cockroach/blob/1bcbdd21f751c9a1b0e209a8c24113369b92124c/pkg/server/admin.go#L1127)

**Comment by ajwerner** [comment]
I suppose we should walk before we run. I suppose I'd be content with our checking in the potentially slow query and filing issues to accelerate it.

**Comment by kevin-v-ngo** [comment]
@stbof, do you mind doing a quick review on this tool tip? 

% of data ([MVCC values](https://www.cockroachlabs.com/docs/stable/architecture/storage-layer.html#mvcc)) modified (updated or deleted) but not garbage collected. A high value can lead to statements scanning more data than required impacting performance.

Thanks!

**Comment by stbof** [comment]
> @stbof, do you mind doing a quick review on this tool tip?
> 
> % of data ([MVCC values](https://www.cockroachlabs.com/docs/stable/architecture/storage-layer.html#mvcc)) modified (updated or deleted) but not garbage collected. A high percentage can cause statements to scan more data than required,  which can reduce performance.
> 
> Thanks!

**Comment by maryliag** [comment]
We're changing the behaviour to show % of live data, instead of the non-live, so we need an update on the tooltip text

**Comment by kevin-v-ngo** [comment]
Here's my initial stab at updating the tool tip:

@stbof, can you review pls?

% of total logical data that has not been modified (updated or deleted). A low percentage can cause statements to scan more data ([MVCC values](https://www.cockroachlabs.com/docs/stable/architecture/storage-layer.html#mvcc)) than required, which can reduce performance.

**Comment by stbof** [comment]
> Here's my initial stab at updating the tool tip.
> 
> @stbof, can you review pls?
> 
> % of total logical data that has not been modified (updated or deleted). A low percentage can cause statements to scan more data ([MVCC values](https://www.cockroachlabs.com/docs/stable/architecture/storage-layer.html#mvcc)) than required, which can reduce performance.

I'm having some trouble understanding the meaning of the new %MVCC live data indicator. While the reversal to low percentage of live data makes sense if high percentage of dead data is bad, I don't understand why having a low percentage of live data will cause statements to scan more data. IOW, the tool tip as is is very hard (for me anyway) to reason about. Could you elaborate on why having a low percentage of live data has this behavior?

**Comment by kevin-v-ngo** [comment]
> > Here's my initial stab at updating the tool tip.
> > @stbof, can you review pls?
> > % of total logical data that has not been modified (updated or deleted). A low percentage can cause statements to scan more data ([MVCC values](https://www.cockroachlabs.com/docs/stable/architecture/storage-layer.html#mvcc)) than required, which can reduce performance.
> 
> I'm having some trouble understanding the meaning of the new %MVCC live data indicator. While the reversal to low percentage of live data makes sense if high percentage of dead data is bad, I don't understand why having a low percentage of live data will cause statements to scan more data. IOW, the tool tip as is is very hard (for me anyway) to reason about. Could you elaborate on why having a low percentage of live data has this behavior?

Low percentage of live data means you have more 'dead' data causing statements to scan over more dead data (more data than required) reducing performance.

**Comment by stbof** [comment]
> > > Here's my initial stab at updating the tool tip.
> > > @stbof, can you review pls?
> > > % of total logical data that has not been modified (updated or deleted). A low percentage can cause statements to scan more data ([MVCC values](https://www.cockroachlabs.com/docs/stable/architecture/storage-layer.html#mvcc)) than required, which can reduce performance.
> > 
> > 
> > I'm having some trouble understanding the meaning of the new %MVCC live data indicator. While the reversal to low percentage of live data makes sense if high percentage of dead data is bad, I don't understand why having a low percentage of live data will cause statements to scan more data. IOW, the tool tip as is is very hard (for me anyway) to reason about. Could you elaborate on why having a low percentage of live data has this behavior?
> 
> Low percentage of live data means you have more 'dead' data causing statements to scan over more dead data (more data than required) reducing performance.

OK. I guess the problem was that I didn't understand how dead data was causing the problem. The KB articles on MVCC garbage are helpful. I think the tooltip is OK, but there definitely needs to be a Learn more link pointing to the doc I create from the KB articles.
