### ISSUE TITLE
*: fine-grained cpu attribution

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#82625]
This is the tracking issue for https://github.com/cockroachdb/cockroach/pull/82356. We expect the work here to break down into the following deliverables.

Must have:
- [x] Write a program to build Go archives for various OS/arch combinations CRDB officially supports/makes use of internally (linux arm64+amd64, darwin arm64+amd64, freebsd amd64, windows amd64). A prototype using hand-rolled scripts (but without CGO support) is [here](https://github.com/irfansharif/utils/tree/master/goroutine-nanos).
  - The official steps, in code form, are are [here](https://go.googlesource.com/build/+/refs/heads/master/cmd/release/release.go).
  - We probably want a docker image with the right cross-compilers to run this program under, these archives need to be built with CGO support. 
  - Being able to generate these archives in CI as downloadable artifacts would be a nice bonus. Ditto if we're able to run the Go tests alongside.
- [x] When bumping Go versions (major or minor), updating our steps to use a manually generated archive from above which also applies the patchset proposed in https://github.com/cockroachdb/cockroach/pull/82356 (kept in a cockroachdb/go repo, or checked into cockroachdb/cockroach as a patch file).
- [x] Introduce a library in cockroachdb/cockroach to access per-goroutine running time. This needs to be gated behind a build tag to error/zero out when not built using the patched runtime.

Nice to have:
- [ ] Support a per-store CPU usage breakdown by (i) ranges and (ii) tenants, powered by per-goroutine running time. We'd make this accessible through vtables and include results in debug zips, serving as a CPU-only version of today's hot-ranges report. A prototype of this is available [here](https://github.com/irfansharif/cockroach/tree/220505.cputime-demo).
- [ ] ~Surfacing per-statement cluster-wide CPU usage as part of EXPLAIN ANALYZE. This would likely require integrating the library above into the Stopper and recording as tracing events total running CPU time for a given request (propagated all the way up to the gateway).~ Tracked in https://github.com/cockroachdb/cockroach/issues/87213.

Jira issue: CRDB-16580

**Comment by irfansharif** [comment]
Connecting some dots. From an [internal doc](https://docs.google.com/document/d/18S4uE8O1nRxULhSg9Z1Zt4jUPBiLJgMh7X1I6shsbug/edit#) around admission control, which would benefit from:

```
CPU timers: A measurement of total cpu time used by a goroutine (analogous to a
thread cpu timer), would allow us to compensate tenants who experience high
contention or high IO time, and so spend more time blocked after admission than
others. This is covered in what we are asking for in
https://github.com/golang/go/issues/41554
```

I was also curious about how the Go runtime is able to pace its GC to use only 30% CPU, and came across https://github.com/golang/proposal/blob/master/design/44167-gc-pacer-redesign.md#a-note-about-cpu-utilization (this whole document is fantastic). This was in the context of trying to understand how we could possibly do similar per-node CPU control for tenants and/or ranges, or get more accurate resource use signals. Turns out Go internally just reads off of nanotime(), using it to compute running time for individual goroutines doing GC assist work, without trying to be accurate about OS threads being descheduled. +cc https://github.com/golang/go/issues/41554#issuecomment-1163514890.

https://github.com/irfansharif/go/blob/2eb8b6eec65d3d214c07067db474bbb93de3443a/src/runtime/mgcmark.go#L592-L601

**Comment by irfansharif** [comment]
The necessary work is done.

**Comment by joshimhoff** [comment]
This is super cool. I didn't know we actually implemented this until now. @irfansharif, where do we use this capability today?

**Comment by irfansharif** [comment]
Admission control for now, https://github.com/cockroachdb/cockroach/pull/86638, coming to a 22.2 CC cluster near you. It's pretty sick, checkout https://github.com/cockroachdb/cockroach/pull/89709#issuecomment-1274031025 for ex. In 23.1 I hope we start using it in the allocator: https://github.com/cockroachdb/cockroach/issues/83490.

**Comment by joshimhoff** [comment]
So great!
