### ISSUE TITLE
ci: Stress (Bazel) does not execute github post if a test/package times out

### ISSUE THREAD

**Issue by srosenberg** [cockroachdb/cockroach#82653]
If a test/package times out during stressing, we should know about it. Currently, this results in a _silent_ build failure. There are many examples of recent timeouts, e.g., [1], [2]. E.g., looking at the build log in [1], we can see that `github_post` is aborted owing to the following error (in `process_test_json`),

```
build/teamcity-bazel-support.sh: line 70: /artifacts/logictest_test.test.json.txt: No such file or directory
```

[1] https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/5410239
[2] https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/5394030

Epic CRDB-15060

Jira issue: CRDB-16575

**Comment by srosenberg** [comment]
Given the current CI infra. for parallelizing stress tests, it's hard to find build ids corresponding to specific tests/packages. It's likely that this related issue is still relevant: https://github.com/cockroachdb/cockroach/issues/76745

**Comment by rickystewart** [comment]
This should be resolved by now; at least, any existing problems are "new" problems as all of this stuff has been rewritten since last year. We have open issues for GH issue posting deficiencies.
