### ISSUE TITLE
kvserver/gc: Replace oldGC as a source of truth for gc tests with simpler assertion based one

### ISSUE THREAD

**Issue by aliher1911** [cockroachdb/cockroach#82657]
Currently we rely on previous version of GC to serve as a source of truth for comparing tested versions.
This is limiting us when adding new types of objects to collect e.g. range tombstones and potentially range values.
Instead of extending old gc with new functionality we'd rather have a simplified gc that would only check deletion eligibility criteria and skip the rest of remaining functionality. That would be future proof with regards new features.

This is a part of #70414

Jira issue: CRDB-16570

**Comment by erikgrinaker** [comment]
Resolved by #83132.
