### ISSUE TITLE
kvcoord: make heartbeat loop start delay configurable

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#82669]
**Is your feature request related to a problem? Please describe.**
Today cockroach lazily creates transaction records (https://github.com/cockroachdb/cockroach/blob/4d987b3f0788c98fa358715b336a1c55e254ee50/docs/RFCS/20181209_lazy_txn_record_creation.md). Sometimes lease transfers make it such that it's ambiguous as to whether a transaction record has yet to be created or has already been aborted and removed. This results in `ABORT_REASON_NEW_LEASE_PREVENTS_TXN` errors. This is generally rare and generally handled by applications, so it's not universally a problem. However, some applications are being ported from Postgresql and don't have logic to handle these retries. Some workloads are more prone to lease instability than others. Workloads which both result in leases moving around a bunch and are unable to handle restarts should still have some sort of workaround to eliminate this class of retry, even if it comes at a cost.

**Describe the solution you'd like**

A simple way to reduce the frequency of such errors is to reduce the window of time in which a transaction operates and does not have a transaction record. Today the `txnCoordSender` kicks off its heartbeat loop after 1 `HeartbeatInterval` which is `1s` and then heartbeats at that frequency. It's easy to imagine decoupling the `HeartbeatInterval` from the time to initial heartbeat. All that that would take is changing the value here: https://github.com/cockroachdb/cockroach/blob/66b513c6e871e2d394aee7b0e4abf536f44e6697/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go#L294-L297

A big hammer would be a cluster setting and that's all that this issue asks for. ~~The risk of this cluster setting is that it might make certain system transactions more fragile.~~ Perhaps there is a way to make it only apply to user transactions. Even more appealing might be to allow individual sql transactions to plumb in a different value based on a session variable. 

**Describe alternatives you've considered**
We could fix that by making the lease transfer more sophisticated (https://github.com/cockroachdb/cockroach/issues/61986). It'd be good to do that, but it's more work.

Jira issue: CRDB-16568

**Comment by bdarnell** [comment]
> The risk of this cluster setting is that it might make certain system transactions more fragile.

How so?

**Comment by ajwerner** [comment]
In retrospect, maybe not. Maybe just more expensive.

**Comment by nvanbenschoten** [comment]
Closing now that https://github.com/cockroachdb/cockroach/pull/83688 has merged and https://github.com/cockroachdb/cockroach/issues/61986 is being worked on.
