### ISSUE TITLE
storage: remove support for table properties

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#82678]
**Is your feature request related to a problem? Please describe.**

With the addition of block properties in 22.1, table-level properties are effectively obsolete, and we should consider removing support for them entirely.

There has been some work done to-date (see #82658) to cease writing table properties entirely. This issue tracks the sequence of migrations required in order to be able to remove the dependence on the Pebble feature entirely.

**Describe the solution you'd like**

Removal would most likely need to happen in stages.

In one release (say 22.2) we stop writing them into new sstables, while somehow "marking" existing sstables for re-writing. Some of the marked sstables will be re-written as part of the natural compaction process, but some files may linger.

In a subsequent release (say 23.1), we'd require something like a blocking migration that ensures that all existing, marked sstables have been removed from the LSM before finalizing the version upgrade. A naive rewrite of all existing marked files could be prohibitively expensive, so we may need to reconsider how we'd re-write such files.

**Describe alternatives you've considered**

Continue to support both table and block properties. To codepaths would need to be maintained. From a maintenance perspective this is sub-optimal.

Jira issue: CRDB-16562

Epic CRDB-2624

**Comment by nicktrav** [comment]
I'd marked #85992 as closing this issue, but don't think that's enough to call this done.

To call this done we should rip out the table props code from Pebble entirely. This will happen as part of the 23.1 cycle (hopefully).

**Comment by erikgrinaker** [comment]
Nice! Should we create a new issue for the cleanup, so we can check this off in the MVCC bulk ops backlog?

**Comment by nicktrav** [comment]
Closing this. The last little piece for Pebble is tracked in cockroachdb/pebble#1887.
