### ISSUE TITLE
kv: build a reproduction for a column backfill impacting foreground traffic

### ISSUE THREAD

**Issue by lunevalex** [cockroachdb/cockroach#82700]
In a recent customer escalation we observed that a column backfill could cause a significant latency impact on a cluster that is running close to it's theoretical disk bandwidth limit. The backfill saturates the disk, latency climbs, admission control kicks in and the application traffic has a performance hit. 

We should build a roachtest or benchmark to reproduce this type of behavior, so we can that use that as a platform to test and develop fixes. One such fix was propose in #82556, there is also a hypothesis that #82440 will help. 

Jira issue: CRDB-16600

Epic CRDB-14607

**Comment by irfansharif** [comment]
(In the future when we develop better machinery around admission control to model disk bandwidth as a bottleneck resource, and improve latency isolation in the presence of large backfills, perhaps some of the above could serve as material for a roachtest.)
