### ISSUE TITLE
sql: support placeholder in identifier and literal string positions

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#8270]
e.g. `CREATE TABLE ? (x INT)` or `INSERT INTO TABLE X (?, ?) VALUES (1, 2, 3)`

So the starting observation is that we have this parser.QueryArguments map which is either empty during prepare (placeholders need to be typed, don't have a value yet) or full during execute. During **lexing** we can peek into this structure to determine what to do:
- if the map is empty (we're in prepare); then upon encountering the syntax for a placeholder in identifier position, 1) return the token type PLACEHOLDER (as currently) and 2) **pre-populate the PlaceholderTypes map with 'string' for the placeholder** 3) during type checking, assume the type is unknown for anything that needs a schema derived from a table/column name for which there is a placeholder; many of our typing rules then become weaker but we can probably still work on the statement conservatively.
- if the map is already pre-populated (we're in execute), then upon encountering the syntax for a placeholder in identifier position **in the lexer**, simply substitute the placeholder for its value and return the IDENT token type instead.
- For CREATE USER statements (#9794), the grammar must be changed to support placeholders.

cc @mjibson

**Comment by knz** [comment]
A possible drawback from this approach is that we'd need to double check the typing rules that we can't get conflicting typing between prepare and execute. To alleviate this we could also considering implementing this feature only after we start caching typing information between prepare and execute (another morcel on the roadmap)

**Comment by petermattis** [comment]
Some uses of placeholders for identifiers seem easier than others. For example, `CREATE DATABASE $1` seems relatively straightforward because we can statically determine the type of the placeholder as string. 

See also #4596 and #4597.

**Comment by mjibson** [comment]
I'm in favor of supporting `?` for any name as long as we can resolve types for all placeholders at prepare time. I don't think we should support cases like `SELECT * FROM ? WHERE a = ?` for now.

**Comment by mjibson** [comment]
Noooo this is my favorite feature I've wanted since like high school.

**Comment by jordanlewis** [comment]
Heh, won't argue with that - I wish there was a way to leave an issue open as "a reasonable idea" without having that also mean "it's on a backlog".

**Comment by knz** [comment]
That is what the C-wishlist label is for!
