### ISSUE TITLE
sql: REVOKE ROLE "rows affected" return counter is not connected

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#82723]
**Describe the problem**

I was looking for a way for a SQL statement to return a non-zero "rows affected"  value through pgwire.

When looking at the code of REVOKE ROLE, I see there's a `struct revokeRoleRun` with a `rowsAffected` counter inside it.

I don't see any use of that counter other than the go statement that increases it. It seems not to be connected anywhere?

**Expected behavior**

1. the `REVOKE ROLE` statement should return a "rows affected" counter corresponding to the amount of work done (ditto DROP ROLE)
2. I'd like to see a SQL internal API to increase the RowsAffected counter in the result set, short of having my `planNode` artificially require the exec machinery to call `Next()` multiple times.

Jira issue: CRDB-16631

**Comment by rafiss** [comment]
I'm not sure to what extent we consider statement tags to be part of the postgres compatibility story. Anyway, just noting that Postgres doesn't return any statement tag for these:

```
postgres=# grant rafiss to u;
GRANT ROLE
postgres=# revoke rafiss from u;
REVOKE ROLE

postgres=# drop user u;
DROP ROLE
```

**Comment by knz** [comment]
ok then we can remove the unused field from the source code.
