### ISSUE TITLE
admission: additional observability

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#82743]
In order of importance and/or done-ness:
- [x] #87883;
- [x] #87424;
- [x] https://github.com/cockroachdb/cockroach/issues/89814;
- [x] https://github.com/cockroachdb/cockroach/pull/93217;
- [x] #88076;
  - [ ] Reduce the cardinality of `Pri * WorkQueues` by:
    - [ ] Skip segmenting the `errored`, `requested` and `admitted` counts
    - [ ] Only introduce a new histogram for `NormalPri` for relevant work queues. Since we have the histograms for the full work queue across all requests, it can tell us how foreground load behaves and how everything else does. Alternatively add segmentation histogram for only NormalPri, everything higher than NormalPri, everything less than NormalPri.
    - [ ] Only introduce the segmentation for kv and kv-stores queues.
  - [ ] Backport to 22.2.
- [x] Metric capturing compaction bandwidth out of L0 (which is used to generate write tokens in admission control), or metric capturing tokens generated directly;
- [x] Introduce metrics for how many L0 tokens are being consumed/produced
- [x] Fix math.MaxInt64 scale for available IO tokens metric when unlimited tokens are present;
- [x] https://github.com/cockroachdb/cockroach/issues/92673
- [x] Fix the AC queue histograms to also include requests that don't get queued, otherwise the percentiles are wrong
- [x] Metric capturing IO tokens consumed by bypassed work;
- [x] Make sure the flow control graphs are present in the Overload dashboard (the flow token wait time histograms, admitted rates, blocked replication streams, flow token deductions in bytes)
- [ ] Export scheduling latency metric even if elastic cpu limiter is disabled (useful in v22.2)
- [ ] Fix units in the Overload dashboard (https://github.com/cockroachdb/cockroach/issues/110056)
- [ ] Metric capturing how long CPU slots are being held for on average, to reason about sudden changes in slot count where total incoming request rate for slots stays unchanged. When requests hold onto slots for longer (due to longer IO wait times, or increased latch/lock wait times), we need to increase slot count to service incoming work. Some times this increase is not fast enough and there's resulting AC queuing like we saw in https://github.com/cockroachlabs/support/issues/1921.
- [ ] We could log the {max,min} slot count and {max,min} runnable goroutine count every second, or export metrics for it. In internal experimentation we find ourselves reaching for it;
- [ ] https://github.com/cockroachdb/cockroach/issues/96495

Jira issue: CRDB-16641

Epic CRDB-25469

**Comment by irfansharif** [comment]
> Perhaps exporting Go's `/sched/latencies:seconds` to have visibility in Go scheduler latencies.

This has proven extremely valuable to do in internal AC-related experiments (re: #75066). https://github.com/irfansharif/cockroach/tree/220614.export-tracing is a prototype that grafts together the prometheus-compatible data from https://github.com/prometheus/client_golang/blob/main/prometheus/go_collector_latest.go, and looks as follows:

![image](https://user-images.githubusercontent.com/10536690/174859663-a33451fa-78cd-4eb7-a79a-5e9b4388a3c8.png)

Through it we were able to correlate foreground latency spikes to Go scheduler latency spikes.

**Comment by irfansharif** [comment]
From an [internal doc](https://docs.google.com/document/d/18S4uE8O1nRxULhSg9Z1Zt4jUPBiLJgMh7X1I6shsbug/edit#), re: "Information needed from Go runtime":

```
Runnable info: Minimally, we need the number of runnable goroutines, sampled at
some reasonably high rate (100hz?). It would be preferable to get a delta value
of total duration spent in Runnable and Running state since the last sample (or
a cumulative number, from which we can compute the delta). The duration is less
sensitive to observing spikes in runnable goroutines, which quickly get
scheduled, which does not necessarily represent scarcity of cpu resources.
```

IIUC, this is exactly the total sum of everything captured within `/sched/latencies:seconds`.

**Comment by sumeerbhola** [comment]
> Exporting segmented latency histograms by different priority levels as seen by admission control, to capture what classes of requests are observing queuing and by how much;

We need this to make sense of mixed workload behavior (e.g. conversation in https://cockroachlabs.slack.com/archives/C038JEXC5AT/p1658247509643359?thread_ts=1657630075.576439&cid=C038JEXC5AT)

**Comment by irfansharif** [comment]
Adding Andrew here too to pick through the list within the next two weeks, it'll be a good way to get our feet wet.

**Comment by irfansharif** [comment]
@andrewbaptist: I'm working on the "Exporting Go's /sched/latencies:seconds" as a histogram. Want to take on the remaining?

**Comment by aadityasondhi** [comment]
Discussed offline with @sumeerbhola, closing this issue as the changes we want to do already have separate issues that are being tracked in the backlog with priorities assigned to them. The rest of them, we don't want to invest time into doing.
