### ISSUE TITLE
ci: un-skip `pkg/testutils/docker:docker_test` in CI

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#82747]
null

Jira issue: CRDB-16642

Epic CRDB-15060

**Comment by ZhouXing19** [comment]
I tried digging into this one but unfortunately could not find a solution.
Some clues that I have found:
The original error is from https://github.com/cockroachdb/cockroach/blob/6b1c99bb9d907733589c474e44a446ca4dc7cf24/pkg/testutils/docker/single_node_docker_test.go#L521-L529, where we somehow lost the permission to run ./docker-fsnotify . The ./docker-fsnotify binary was built with pkg/testutils/docker/docker-fsnotify . The [error message](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_ScratchProjectPutTcExperimentsInHere_JaneDockerImageTest/5751145?showRootCauses=true&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildDeploymentsSection=true&logFilter=debug) is
--- FAIL: TestSingleNodeDocker (2.18s)
19:47:59         --- FAIL: TestSingleNodeDocker/single-node-secure-mode (1.93s)
19:47:59             single_node_docker_test.go:221: cannot run fsnotify to listen to init_success:
19:47:59                 res:&docker.execResult{stdOut:"OCI runtime exec failed: exec failed: unable to start container process: exec: \"./docker-fsnotify\": permission denied: unknown\r\n", stdErr:"", exitCode:126}: command "./docker-fsnotify /cockroach init_success 80" exit with code 126:
19:47:59                  {stdOut:OCI runtime exec failed: exec failed: unable to start container process: exec: "./docker-fsnotify": permission denied: unknown
19:47:59      stdErr: exitCode:126}
2. The ./docker-fsnotify binary actually has the Lrwxrwxrwx permission (check Build Log [here](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_ScratchProjectPutTcExperimentsInHere_JaneDockerImageTest/5516875?buildTab=log&focusLine=4311&linesState=4229.4251) and search in log docker/docker-fsnotify/docker-fsnotify-bin )

Is it ok if I hand this issue back to the dev-inf team?

**Comment by rail** [comment]
Hmmm, looks like we generate `docker-fsnotify-bin`, but try to run `docker-fsnotify`?

**Comment by rail** [comment]
Nm, looks live those are [mounted](https://github.com/cockroachdb/cockroach/blob/6b1c99bb9d907733589c474e44a446ca4dc7cf24/pkg/testutils/docker/single_node_docker_test.go#L122) binaries. I wonder if there were some changes that require you to explicitly specify mount options or something that allow execution.

**Comment by rail** [comment]
Oooooh, I think I may know what's going on. When you mount a symlink, it becomes a dangling symlink, because there is no actual binary in the image. We should copy the actua binary (using realpath maybe) to a temp location and mount the copied binary instead.

**Comment by ZhouXing19** [comment]
Sorry, I just noticed my message above was misleading. It turns out that the fsnotify's binary is now stored in a different place.
I made PR https://github.com/cockroachdb/cockroach/pull/86282 to fix this. 
Thanks for your investigation, and sorry for the confusion!
