### ISSUE TITLE
flowinfra: Do not inhibit server shutdown

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#82765]
A long running distSQL flow may inhibit server shutdown.

It appears that any bulk-io or changefeed processors running on the node at the time it 
is being drained, may inhibit server shutdown.

Changefeed/builk-y processors are interesting in that they usually have 1 coordinator, and N processors that send updates
to the coordinator (changeFrontier and changeAggregator processors in changefeed case).
Furthermore, those flows are not usually tied to the "user" connection -- they are started by the jobs system.

Those leaf processors have no incoming inputs, and thus are not registered with the flow registry.
When the node is being drained, the registry is drained.  However, only flows that have incoming inputs are
ever registered with the flow registry, and only those get cancelled when the stopper quiesces. 
https://github.com/cockroachdb/cockroach/blob/master/pkg/server/drain.go#L361-L361
https://github.com/cockroachdb/cockroach/blob/master/pkg/server/drain.go#L361-L361
https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/flowinfra/flow_registry.go#L466-L466

As a result, when the node holding leaf processor (changeAggregator) is being shutdown, the processor does not
get *any* cancellation signal, and therefore, if the processor also uses stopper, as is the case with changefeedProcessor
https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/changefeedccl/changefeed_processors.go#L332, then
the stopper will wait for the "task" to finish (https://github.com/cockroachdb/cockroach/blob/master/pkg/util/stop/stopper.go#L615-L615), but this will never happen.

As a workaround, changefeed will arrange for its context to be cancelled when server quiesces; however, distflow infra should ensure that flows are cancelled in general and not rely on processor implementation to arrange for that.

Jira issue: CRDB-16647

**Comment by rytaft** [comment]
cc @vy-ton to discuss how this affects server shutdown process

**Comment by rytaft** [comment]
We think that we should cancel all queries -- there is an open question about whether we should increase the grace period from 10s to, say, 60s?

**Comment by mwang1026** [comment]
what types of queries were forever running? seems like an anti-pattern / not intended?

**Comment by vy-ton** [comment]
> It appears that any bulk-io or changefeed processors running on the node at the time it
is being drained, may inhibit server shutdown.

Not just user queries but long-running jobs. So we would cancel an IMPORT as an example

**Comment by yuzefovich** [comment]
Do I have a product approval for proceeding with cancellation of all long-running queries on a node when the node is being drained? @vy-ton @mwang1026

**Comment by mwang1026** [comment]
I don't know about the specifics and defer to @stevendanna and @miretskiy on the behavior here.

Specifically, what does "cancellation" mean here? And how does that impact the various "long running queries" such as changefeeds and import and backup and restore?

cc @livlobo @amruss

**Comment by yuzefovich** [comment]
> Specifically, what does "cancellation" mean here?

The distributed plan will result in an error propagated to the "client". I think in case of changefeeds, the "client" is one of the CRDB nodes and is smart enough to recognize such errors, and the new distributed plan will be setup (without using the node that is being drained) transparently to the user, not sure about BulkIO things.

**Comment by yuzefovich** [comment]
We will proceed with this cancellation on 22.2 but introduce a cluster setting as an escape hatch to revert to the previous behavior should we need it.
