### ISSUE TITLE
build: upgrade both `master` and `release-22.1` branches to use go 1.17.11

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#82808]
**Describe the problem**

We are seeing excess allocations due to the upgrade to go 1.17 and this bug:
https://github.com/golang/go/issues/52790

This was fixed in go 1.17.11.

Currently `master` uses 1.17.10 and `release-22.1` uses 1.17.6.

**Expected behavior**

Upgrade both branches to build with 1.17.11.

Jira issue: CRDB-16676

**Comment by knz** [comment]
cc @rail for triage

**Comment by rail** [comment]
I'll take care of this this week.

**Comment by rail** [comment]
Done.
