### ISSUE TITLE
kv: uninitialized replica can cause unbounded backoff due to stale range descriptors

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#82802]
Related to https://github.com/cockroachdb/cockroach/issues/75742, but not the same.

When running the test described in https://github.com/cockroachdb/cockroach/issues/79385, I ran into a `NotLeaseHolderError` loop. However, it wasn't the same one described in that issue. In my reproduction, only requests originating on the slow node got stuck. This was because the lease was not transferred to a replica that needed a snapshot.

<img width="993" alt="Screen Shot 2022-06-13 at 12 48 13 AM" src="https://user-images.githubusercontent.com/5438456/173282338-f55898cd-6e06-41d7-a700-aa73e6e2162e.png">

Looking at logspy, I found the following loop for a few different ranges. Here are the logs scoped down to a single range:
```
I220613 04:42:09.431639 91225 kv/kvclient/kvcoord/dist_sender.go:1969 ⋮ [n3,s3,r1/2:‹/{Min-System/NodeL…}›] 1943 routing to nearest replica; leaseholder not known
I220613 04:42:09.431665 91225 kv/kvclient/kvcoord/dist_sender.go:2032 ⋮ [n3,s3,r1/2:‹/{Min-System/NodeL…}›] 1944 r254: sending batch ‹1 PushTxn› to (n3,s3):1
E220613 04:42:09.431760 91225 kv/kvclient/kvcoord/dist_sender.go:2144 ⋮ [n3,s3,r1/2:‹/{Min-System/NodeL…}›] 1946 ‹[NotLeaseHolderError] r254: replica (n3,s3):1 not lease holder; replica (n4,s4):2 is›
E220613 04:42:09.431826 91225 kv/kvclient/kvcoord/dist_sender.go:2245 ⋮ [n3,s3,r1/2:‹/{Min-System/NodeL…}›] 1947 application error: ‹[NotLeaseHolderError] r254: replica (n3,s3):1 not lease holder; replica (n4,s4):2 is›
I220613 04:42:09.431929 91225 kv/kvclient/kvcoord/dist_sender.go:1652 ⋮ [n3,s3,r1/2:‹/{Min-System/NodeL…}›] 1948 evicting range desc ‹desc:r254:/Table/106/1/39{488508-540666} [(n3,s3):1, (n2,s2):5, (n8,s8):3, next=6, gen=98, sticky=1655092870.755128344,0] lease:<nil> spec desc: <nil>› after ‹failed to send RPC: sending to all replicas failed; last error: routing information detected to be stale: [NotLeaseHolderError] r254: replica (n3,s3):1 not lease holder; replica (n4,s4):2 is›

I220613 04:42:09.494195 124423 kv/kvclient/kvcoord/dist_sender.go:2032 ⋮ [n3,replicaGC,s3,r428/2:‹/Table/106/1/5{26127…-85900…}›] 2021 r1: sending batch ‹1 Scan› to (n1,s1):1
I220613 04:42:09.647134 124467 kv/kvclient/kvcoord/dist_sender.go:2032 ⋮ [n3,s3,r1/2:‹/{Min-System/NodeL…}›,range-lookup=‹/Table/106/1/21627091›] 2216 r1: sending batch ‹1 Scan› to (n1,s1):1

I220613 04:42:10.386035 91225 kv/kvclient/kvcoord/dist_sender.go:1969 ⋮ [n3,s3,r1/2:‹/{Min-System/NodeL…}›] 2835 routing to nearest replica; leaseholder not known
I220613 04:42:10.386069 91225 kv/kvclient/kvcoord/dist_sender.go:2032 ⋮ [n3,s3,r1/2:‹/{Min-System/NodeL…}›] 2836 r254: sending batch ‹1 PushTxn› to (n3,s3):1
E220613 04:42:10.386168 91225 kv/kvclient/kvcoord/dist_sender.go:2144 ⋮ [n3,s3,r1/2:‹/{Min-System/NodeL…}›] 2838 ‹[NotLeaseHolderError] r254: replica (n3,s3):1 not lease holder; replica (n4,s4):2 is›
E220613 04:42:10.386247 91225 kv/kvclient/kvcoord/dist_sender.go:2245 ⋮ [n3,s3,r1/2:‹/{Min-System/NodeL…}›] 2839 application error: ‹[NotLeaseHolderError] r254: replica (n3,s3):1 not lease holder; replica (n4,s4):2 is›
I220613 04:42:10.386377 91225 kv/kvclient/kvcoord/dist_sender.go:1652 ⋮ [n3,s3,r1/2:‹/{Min-System/NodeL…}›] 2840 evicting range desc ‹desc:r254:/Table/106/1/39{488508-540666} [(n3,s3):1, (n2,s2):5, (n8,s8):3, next=6, gen=98, sticky=1655092870.755128344,0] lease:<nil> spec desc: <nil>› after ‹failed to send RPC: sending to all replicas failed; last error: routing information detected to be stale: [NotLeaseHolderError] r254: replica (n3,s3):1 not lease holder; replica (n4,s4):2 is›
```

What's happening here is the following:
1. n3 does not know the lease for r254, so it sends to its local replica first
2. n3's replica for r254 is uninitialized, so it returns a `NotLeaseHolderError` pointing at n4. The code and explanation for this are [here](https://github.com/cockroachdb/cockroach/blob/87da966cbc15e058591d80c477c78d6059483a5c/pkg/kv/kvserver/store_send.go#L176-L194).
3. n3 receives the NotLeaseHolderError, does not find n4 in the descriptor, so [it evicts it](https://github.com/cockroachdb/cockroach/blob/87da966cbc15e058591d80c477c78d6059483a5c/pkg/kv/kvclient/rangecache/range_cache.go#L1352) before ever trying the other replicas in its cached descriptor
4. n3 performs a meta lookup and receives the same range descriptor with `(n3,s3):1, (n2,s2):5, (n8,s8):3`
5. rinse, repeat

I believe this is a special case of https://github.com/cockroachdb/cockroach/issues/72772. However, the fix for that issue (https://github.com/cockroachdb/cockroach/pull/73697) is not helping because this [specific constructor](https://github.com/cockroachdb/cockroach/blob/87da966cbc15e058591d80c477c78d6059483a5c/pkg/kv/kvserver/store_send.go#L176-L194) for NotLeaseHolderErrors does not attach a RangeDescriptor, which disables the client-side logic to detect stale NotLeaseHolderErrors.

We could fix this in either of two ways:
1. we could return a fake RangeDescriptor with a Generation of 1 in this NotLeaseHolderErrors constructor, indicating that if there's incoherence between the cache and the returned lease hint, the cache is probably more up-to-date.
2. now that we've migrated this field in, we could change the [client-side logic](https://github.com/cockroachdb/cockroach/blob/87da966cbc15e058591d80c477c78d6059483a5c/pkg/kv/kvclient/rangecache/range_cache.go#L1349) to _not_ evict the range descriptor if the Generation is not returned and the suggested lease is not part of the cached range descriptor. Essentially just `s/descGeneration != 0 && //`.

I prefer the second option. It avoids the need to construct a fake RangeDescriptor (who knows where that could leak) and it centralizes the logic for how to handle this case in the client, where it probably belongs.

cc. @arulajmani 

Jira issue: CRDB-16670

**Comment by arulajmani** [comment]
I'm in this area right now and I'm trying to simplify some of the logic we introduced in #72772. I might get rid of the logic you linked for option 2, but I agree that in principle we should be centralizing things on the client. I'll self-assign this and get to it 
once we've fixed #75742.
