### ISSUE TITLE
kv: Include PTS record information in debug.zip

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#82826]
It appears debug.zip does not capture `system.protected_ts_records` -- it should.
These records could be important in debugging e.g. excessive disk growth issues.

Jira issue: CRDB-16688

**Comment by Santamaura** [comment]
Hi @miretskiy in a local env the debug zip seems to produce a txt for `system.protected_ts_records`, do you mean that data is not written to the txt or that it is missing completely from your debug zip?

![Screen Shot 2022-06-23 at 11 55 10 AM](https://user-images.githubusercontent.com/17861665/175342667-bf0b49e5-ec9c-4a86-97c7-9e3fcb1d3a69.png)

**Comment by miretskiy** [comment]
Perhaps it was something recent? I got customer debug.zips w/out this data.  False alarm if it is included (perhaps debug.zip I got was incomplete).

If this was an incomplete debug.zip, do we think it would make sense to include a "sanity.sh" script to verify that all
of the files that should have been included are indeed included?
Just a check that, much like you have in the above screen shot, prints out e.g. "Warning: missing system.XXX file"...
?

**Comment by Santamaura** [comment]
> Perhaps it was something recent? I got customer debug.zips w/out this data. False alarm if it is included (perhaps debug.zip I got was incomplete).

Ah yep I think this was a recent change, only 1 month old: https://github.com/cockroachdb/cockroach/commit/1cabdd74dc6facce741457e166154afc0fdb3167, we can ask for backport if needed?

> If this was an incomplete debug.zip, do we think it would make sense to include a "sanity.sh" script to verify that all
of the files that should have been included are indeed included?
Just a check that, much like you have in the above screen shot, prints out e.g. "Warning: missing system.XXX file"...
?

I think currently if the code encounters a case where it is unable to write to a file it will spit out an error so we should be covered on this part

**Comment by miretskiy** [comment]
And is this error visible once you download debug.zip? And not just visible but obviously visible?

**Comment by Santamaura** [comment]
Looks like there's a retry loop if it does fail. If it exceeds the max retries (set at 5) then the error should print out.

**Comment by Santamaura** [comment]
It was backported to 22.1 and 21.2
