### ISSUE TITLE
The unsafe_upsert_descriptor function requires updating a version and modification time - let the function handle this.

### ISSUE THREAD

**Issue by smcvey** [cockroachdb/cockroach#82824]
When attempting to update a descriptor in the system.descriptor table with `unsafe_upsert_descriptor()`, it is required to increment the version manually and also update the modificationTime.  The function should be able to handle this itself.

Human-editing of the JSON file creates more opportunities for error if it has to be done manually.

Jira issue: CRDB-16686

**Comment by rafiss** [comment]
I think this is resolved now (4c43c2b8c7b): https://github.com/cockroachdb/cockroach/blob/95dcf06ec7d3ba2cea59c7ce608162f2be71681d/pkg/sql/repair.go#L122
