### ISSUE TITLE
pq: could not determine data type of placeholder $1

### ISSUE THREAD

**Issue by davies** [cockroachdb/cockroach#82820]
**Describe the problem**

JuiceFS use the following SQL query to update two raw in a table:

```
UPDATE jfs_counter SET value=value+ CAST((CASE name WHEN 'usedSpace' THEN ? ELSE ? END) AS BIGINT) WHERE name='usedSpace' OR name='totalInodes'
```

It works with PG, but failed with cockroach:

```
pq: could not determine data type of placeholder $1
```

The client library is pg (github.com/lib/pq)

**To Reproduce**

Create a table `jfs_counter`
```
                    Table "public.jfs_counter"
 Column |          Type          | Collation | Nullable | Default 
--------+------------------------+-----------+----------+---------
 name   | character varying(255) |           | not null | 
 value  | bigint                 |           | not null | 
Indexes:
    "jfs_counter_pkey" PRIMARY KEY, btree (name)

```

The code to reproduce the issue:

```
_, err := session.Exec("UPDATE jfs_counter SET value=value+ CAST((CASE name WHEN 'usedSpace' THEN ? ELSE ? END) AS BIGINT) WHERE name='usedSpace' OR name='totalInodes' ", newSpace, newInodes)
```

**Expected behavior**

The query should succeed.

related  issue: https://github.com/juicedata/juicefs/issues/2210

Jira issue: CRDB-16682

**Comment by rafiss** [comment]
The issue here is https://github.com/cockroachdb/cockroach/issues/41558

I'll close this one as a duplicate, but a workaround is to add type-casts to each placeholder argument, like:
```
_, err := session.Exec("UPDATE jfs_counter SET value=value+ (CASE name WHEN 'usedSpace' THEN ?::BIGINT ELSE ?::BIGINT END) WHERE name='usedSpace' OR name='totalInodes' ", newSpace, newInodes)
```

Note that this also allows you to remove the outer `CAST` around the `CASE` clause

**Comment by davies** [comment]
> The issue here is #41558
> 
> I'll close this one as a duplicate, but a workaround is to add type-casts to each placeholder argument, like:
> 
> ```
> _, err := session.Exec("UPDATE jfs_counter SET value=value+ (CASE name WHEN 'usedSpace' THEN ?::BIGINT ELSE ?::BIGINT END) WHERE name='usedSpace' OR name='totalInodes' ", newSpace, newInodes)
> ```
> 
> Note that this also allows you to remove the outer `CAST` around the `CASE` clause

Does this workaround work for PG and MySQL as well?  We used another workaround: put the number in the query as const.

**Comment by rafiss** [comment]
That workaround should worth for Postgres, yes.

MySQL needs the longer form of cast syntax, like this:
```
_, err := session.Exec("UPDATE jfs_counter SET value=value+ (CASE name WHEN 'usedSpace' THEN CAST(? AS BIGINT) ELSE CAST(? AS BIGINT) END) WHERE name='usedSpace' OR name='totalInodes' ", newSpace, newInodes)
```

and that version should work on all CRDB, PG, and MySQL. I haven't tested to confirm though.
