### ISSUE TITLE
bazel: incorrect dependency between the yarn cache and the npm build

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#82853]
**Describe the problem**

Followup to #82762: with enough concurrency, running `dev build` runs **once** into errors like the following:

```
ERROR: /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/npm_cluster_ui/BUILD.bazel:9789:10: Copying directory external/npm_cluster_ui/_/pkg/ui/workspaces/cluster-ui/node_modules/enquire.js failed: missing input file 'external/npm_cluster_ui/_/pkg/ui/workspaces/cluster-ui/node_modules/enquire.js', owner: '@npm_cluster_ui//:_/pkg/ui/workspaces/cluster-ui/node_modules/enquire.js'
ERROR: /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/npm_cluster_ui/BUILD.bazel:9789:10: Copying directory external/npm_cluster_ui/_/pkg/ui/workspaces/cluster-ui/node_modules/enquire.js failed: 1 input file(s) do not exist
ERROR: /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/npm_cluster_ui/BUILD.bazel:16765:10: Copying directory external/npm_cluster_ui/_/pkg/ui/workspaces/cluster-ui/node_modules/omit.js failed: missing input file 'external/npm_cluster_ui/_/pkg/ui/workspaces/cluster-ui/node_modules/omit.js', owner: '@npm_cluster_ui//:_/pkg/ui/workspaces/cluster-ui/node_modules/omit.js'
Target //pkg/cmd/cockroach:cockroach failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/npm_cluster_ui/BUILD.bazel:9789:10 Copying directory external/npm_cluster_ui/_/pkg/ui/workspaces/cluster-ui/node_modules/enquire.js failed: 1 input file(s) do not exist
INFO: Elapsed time: 59.211s, Critical Path: 0.07s
INFO: 110 processes: 30 internal, 80 local.
FAILED: Build did NOT complete successfully
```

or alternatively
```
Error in fail: Error applying patch //pkg/ui:patches/aria-query/remove-filenames-with-spaces.cluster-ui.patch in /Users/irfansharif/Software/src/github.com/cockroachdb/cockroach:
The next patch would delete the file '"pkg-no-spaces/ui/workspaces/cluster-ui/node_modules/aria-query/lib/etc/roles/abstract/commandRole 2.js"',
which does not exist!  Assume -R? [n]
Apply anyway? [n]
1 out of 1 hunk ignored
```

then a second run succeeds.

**To Reproduce**

```
dev ui clean --all
dev build
```

(use many cores and a fast FS)

the first `dev build` fails, then a subsequent invocation suceeds.

**Expected behavior**

`dev build` suceeds immediately.

**Additional context**

We're suspicious of the following declared dependencies:

- we have a top level dep (in WORKSPACE) from `.seed` to the built JS packages (declared via `js_library` in the auto-generated `external/npm_cluster_ui/BUILD.bazel`)

- inside `external/npm_cluster_ui/BUILD.bazel`, we also see `copy_file` directives from the cache as a pre-req to `js_library`

However, we don't have a dependency from `.seed` to `copy_file`. So it's possible for `copy_file` to run asynchronously with the yarn cache populate rules, and have `copy_file` fail because the files are not there yet.

(once the command has run a few times, the files are there and `copy_file` can succeed)

Jira issue: CRDB-16694

Epic CRDB-8349

**Comment by knz** [comment]
@sjbarag suggests maybe using buildozer https://github.com/bazelbuild/buildtools/blob/master/buildozer/README.md

and rewrite the auto-generated BUILD.bzl to inject the missing dep somehow

**Comment by knz** [comment]
cc @irfansharif

**Comment by irfansharif** [comment]
Some internal discussion [here](https://cockroachlabs.slack.com/archives/C019A8NANH0/p1655154514306059?thread_ts=1654034004.662929&cid=C019A8NANH0).

**Comment by sjbarag** [comment]
A few other solutions are possible:

1. Use a CRL-maintained NPM registry/proxy (something like [Artifactory](https://jfrog.com/artifactory/), [Verdaccio](https://verdaccio.org/), etc.), which would remove the need to seed the global NPM cache and allow us to use the standard `yarn_install` repository rule
2. Fork `rules_nodejs` to ensure the `.seed` files are written before `yarn_install` runs
3. Same as (2), but submitted back to upstream

Long-term, (1) would streamline a few other dev workflow hitches involved with dependency management — mostly that storing them in a submodule requires manual intervention and makes upgrading dependencies a bit harder.

**Comment by tbg** [comment]
Occurred here too https://cockroachlabs.slack.com/archives/C016CAD2HQ8/p1661963715417689?thread_ts=1661935399.930959&cid=C016CAD2HQ8

**Comment by knz** [comment]
Sean fixed this.
