### ISSUE TITLE
kv: remove uses of gossip/simulation from tests

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#8285]
`TestGetFirstRangeDescriptor` and `TestSlowLeaseHolderRetry` in `dist_sender_test.go` are using `simulation.NewNetwork` to create gossip instances. This is a bad idea because the simulation machinery is not identical to the normal gossip machinery.

**Comment by tschottdorf** [comment]
The issue hasn't been fixed, but I doubt having this issue open will change anything about that.
