### ISSUE TITLE
stability: massive increase in goroutine count

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#8287]
Upgraded `beta` yesterday from 844e419 to f2a807a

Quick look at the 24h on [grafana](http://monitoring.gce.cockroachdb.com:3000/dashboard/db/cockroachdb) (see [instructions](https://github.com/cockroachlabs/production/tree/master/monitoring) for access) showed basic pre/post upgrade stats.
Goroutine count on all nodes went from ~1.7K to ~37K

Top goroutine counts from one of the `~/logs/goroutine.*` dumps:
```
2088: select [0~1 minutes] [Created by stop.(*Stopper).RunWorker @ stopper.go:188]
5461: semacquire [Created by stop.(*Stopper).RunWorker @ stopper.go:188]
7566: select [0~1 minutes] [Created by stop.(*Stopper).RunWorker @ stopper.go:188]
7566: select [0~960 minutes] [Created by grpc.(*Server).serveStreams.func1 @ server.go:420]
7566: select [0~960 minutes] [Created by stop.(*Stopper).RunWorker @ stopper.go:188]
7567: select [0~961 minutes] [Created by grpc.NewClientStream @ stream.go:207]
```

Full goroutine dump:
[goroutines.txt](https://github.com/cockroachdb/cockroach/files/399424/goroutines.txt)

**Comment by mberhault** [comment]
@tamird: assigning to you as this looks like mostly grpc stuff, but this is a semi-informed guess on my part.

**Comment by tamird** [comment]
How many ranges are on the cluster? I suspect we might be seeing https://github.com/cockroachdb/cockroach/pull/8162

**Comment by tamird** [comment]
`5461: semacquire [Created by stop.(*Stopper).RunWorker @ stopper.go:188]` these are all blocking on `Store.processRaftMu`, which is also expected.

I don't think there's an issue here.

**Comment by mberhault** [comment]
~7K replicas per node, matching the individual goroutine counts

**Comment by petermattis** [comment]
There are ~3700 replicas per node on beta. We'll open ~2 streams per replica (normal and snapshots) and each stream requires ~5 (!) goroutines. Prior to #8162 there was false-sharing of streams between replicas. So like @tamird said, this is not unexpected.

**Comment by mberhault** [comment]
right. sorry, ~3.5K, I pulled the number from memory (I remember checking the outstanding raft send/recv  counts from https://beta.gce.cockroachdb.com:8080/debug/requests and checking x2).

So basically nothing here? The grafana dashboard also shows a drop in bytes in/out, but that metric is so vague that I don't know if it means anything. I'm hoping a more complete dashboard will give more visibility.

**Comment by tamird** [comment]
@mberhault the drop in bytes in/out is likely the result of the fix that was #8162, so ranges are no longer thrashing snapshots as before.

**Comment by tamird** [comment]
On the other hand...the cluster appears to be pretty dead, judging by the state of the admin UI

**Comment by mberhault** [comment]
it's more incredibly slow than dead. Still response to sql commands, and the photos app is making some (very very slow) progress.

**Comment by mberhault** [comment]
and while I was typing that one of the nodes decided to panic in timeseries: #8289. unrelated.
