### ISSUE TITLE
backupccl: `debug backup export` not tested (maybe not working) for tenant backups

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#82878]
**Describe the problem**

When we look at the implementation of `cockroach backup export` we  see that it uses `keys.TODOSQLCodec` to report the contents of a backup.

This is not likely to work if the backup files contain data for a tenant.

In addition, we see that `backup export` is not being tested for tenant backups in `ccl/cliccl`, alongside the other cases in `debug_backup_test.go`.

**Expected behavior**

There are passing unit tests in `ccl/cliccl` that exercise `debug backup export` for tenant backups.

cc @stevendanna for triage

Jira issue: CRDB-16703

Epic: CRDB-14582

**Comment by shermanCRL** [comment]
FYI this is not (should not) be enabled in production. We never shipped it. We still could but it’s low priority.

**Comment by knz** [comment]
Thanks for the heads up. 

Regardless of whether the code is in prod or not, we need to do this cleanup within 1-2 release cycle for the multi-tenancy arch unification project. If you believe this code is not going to be maintained moving forward, we can schedule removing it from the project altogether.
