### ISSUE TITLE
kvserver/reports: SREs can't use replication reports to check application of tenant zone configs

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#82881]
**Describe the problem**

The code in `kvserver/reports/reporter.go`, `zoneResolver`, uses `keys.TODOSQLCodec` to reverse-engineer which zone configs apply to which ranges.

This means the code is not able to distinguish data for secondary tenants.

**Expected behavior**

The replication reports should check the tenant-specific zone configs applying to each secondary tenant.

Presumably, the replication reports should not use the zone config data in SystemConfigSpan any more, and instead use the new span config infrastructure.

Slack discussion [here](https://cockroachlabs.slack.com/archives/C0KB9Q03D/p1655207752033169).

**UX considerations**

The primary goal of this issue is to make the cross-tenant replication works in the system tenant. 

We can have a separate discussion about whether we want per-tenant replication reports as well. This is out of scope here.

Epic CRDB-10630

Jira issue: CRDB-16708

**Comment by knz** [comment]
We also see a use of `keys.TODOSQLCodec` in `testutils/keysutils/pretty_scanner.go`, `parseTableKeysAsAscendingInts()`. 
This test code is (as far as I can see) only used by the replication report tests.

This can be modified to take the codec as argument, once that is determined in the replication report code.

**Comment by vy-ton** [comment]
> We can have a separate discussion about whether we want per-tenant replication reports as well. This is out of scope here.

I believe this is covered by https://cockroachlabs.atlassian.net/browse/CRDB-10791. FYI @thtruo

**Comment by knz** [comment]
We have a better description of the work in the following issue: #100004

Closing this one as duplicate.
