### ISSUE TITLE
protectedts: remove deprecated components of the protected timestamp subsystem

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#82888]
In 22.1 we shipped a new protected timestamp implementation that relies on spanconfig reconciliation and allows for multi-tenant support. As part of the migration story, to account for jobs started in a mixed version state, as well as jobs running during the upgrade from 21.2 to 22.1, we continued to consult both the old and new protected timestamp subsystems. This meant keeping around two flavours of protected timestamp records, and two sources of truth of the protected timestamp state. The PTS Cache, and the KVSubscriber. In 22.2 we would like to rip the PTS Cache and all the deprecated implementations and have the KVSubscriber be the only source of truth.

The only blocker to deleting the deprecated code is a job that straddles 2+ releases i.e. pre-22.1 to 22.2. Such a job might rely on protected timestamps that were written in 21.2 and can only be read by the deprecated PTS Cache. There are a couple of migration options that can be considered:

1) The easiest (and most destructive) solution would be to disallow jobs to straddle >1 release. The migration could check the `CreationClusterVersion` in the backup/cdc job payload and cancel the job if it was created pre-22.1. This might be particularly disruptive for changefeeds but it would be nice to codify our policy around jobs straddling multiple releases.

2) Since backup and CDC are the only users of protected timestamps at the moment, the migration could use state stored in the job record to identify the schema object that the backup/CDC job is operating on. The migration could then write a new protected timestamp record protecting the schema object, and release the old span-backed protected timestamp record. 

Jira issue: CRDB-16713

Epic CRDB-34798

**Comment by miretskiy** [comment]
@adityamaru just a heads up I'm going to remove this from cdc board; 
not sure if you planning on doing any work on this.

**Comment by adityamaru** [comment]
I'm not going to be working on this anytime soon, @jayshrivastava you may want to use this issue if you're planning to work on it

**Comment by jayshrivastava** [comment]
I'll move this over to CDC triage @adityamaru

**Comment by jayshrivastava** [comment]
Adding a note about backportabilty. If they above changes arent backportable, it would be nice to add jitter to changefeeds updating PTS records, so they dont write to the meta table at the same time.
