### ISSUE TITLE
streamingest: TestRandomClientGeneration should use the proper SQLCodec in `assertEqualKVs()`

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#82883]
The test `TestRandomClientGeneration` in `streamingest/stream_ingestion_processor_test.go`  currently uses `keys.TODOSQLCodec()` in its post-conditiopn `assertEqualKVs()`.

Instead this should be modified to use the codec expected for the replication stream being validated.

cc @stevendanna for triage.

Jira issue: CRDB-16710

**Comment by knz** [comment]
@stevendanna could you help me understand what this test does? Would it make sense to modify the test to exercise both streaming from/into system tenant and a secondary tenant keyspace?

**Comment by stevendanna** [comment]
> Would it make sense to modify the test to exercise both streaming from/into system tenant and a secondary tenant keyspace?

At the moment, the tenant streaming doesn't support the source or destination being the system tenant.

**Comment by knz** [comment]
Ok so this makes fixing this issue easier: the SQLCodec should be the one for the tenant of the stream.

**Comment by yuzefovich** [comment]
Should this issue be closed now? The test now correctly uses `SQLCodec` for the tenant. If we plan to support C2C for system tenants in the future, I'd argue we don't need this issue to track extension to this particular test; instead, it should be a part of the PR that introduces that new behavior.

**Comment by knz** [comment]
yep, that works thanks
