### ISSUE TITLE
Make the `changefeed.protect_timestamp_interval` public = true

### ISSUE THREAD

**Issue by kathancox** [cockroachdb/cockroach#82897]
Currently the `changefeed.protect_timestamp_interval` cluster setting is marked as `false` under the `public` cluster settings column. If this is changed to `true`, the setting will automatically pull through to the docs cluster settings page https://www.cockroachlabs.com/docs/v22.1/cluster-settings.html.

Jira issue: CRDB-16716

**Comment by HonoreDB** [comment]
I propose that ideally the process for this kind of change would be @kathancox makes this PR directly, rather than making an issue, and both @amruss and an engineer need to sign off? What do y'all think?
