### ISSUE TITLE
admission: disk bandwidth as a bottleneck resource

### ISSUE THREAD

**Issue by sumeerbhola** [cockroachdb/cockroach#82898]
Admission control is unaware of disk bandwidth as a constrained resource.
This leads to issues like https://github.com/cockroachlabs/support/issues/1628

First-class support for the disk bandwidth resource would address this.
Draft PR https://github.com/cockroachdb/cockroach/pull/82813

Jira issue: CRDB-16717

Epic CRDB-14607

**Comment by nicktrav** [comment]
Linking this to #83490, which seems more general, but would most likely make use of whatever we work out where for the disk bandwidth signal.
