### ISSUE TITLE
tracing,stmtdiagnostics: bounded overhead, continuous tail trace capture

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#82896]
**Is your feature request related to a problem? Please describe.**

It's difficult today to diagnose causes for high-tail executions. It's doubly difficult to do so when the high-tail events have occurred in the past as we don't do any form of always-on/continuous profiling.

**Describe alternatives you've considered**

Keep the status quo, we have two ways to get to verbose traces for tail events today:
- `sql.trace.stmt.enable_threshold`, a somewhat blunt hammer that enables verbose tracing for every execution all the time. Because it's so coarse grained, enabling it imposes a large performance penalty. It's likely that enabling the setting itself drives high-tail events, which is not what we want. Secondly: since it's not scoped to specific statements (it's possible for outlier events to only apply to specific statements, and for different statements to have different tail behaviours), it creates a very verbose haystack to sift through in CRDB logs to find out the execution we're interested in. In previous escalations we approach this setting somewhat timidly, manually switching it on and off at specific points in time in the hopes of capturing the right tail event.
- Specifying a minimum latency target when issuing a diagnostics bundle request. This is nice in that it's scoped to a specific fingerprint, but it has two limitations (exactly what this issue proposes we address):
  - When setting a latency target, it enables verbose tracing for all future executions until that target is met or the request expires. This can be expensive, especially if trying to capture a tail event for a frequently occurring statement.
  - It captures only the first event that meets the criteria (i.e. it's not continuous).
 
**Describe the solution you'd like**

As a first step, I want roughly the following ability:

```
  Pick a stmt fingerprint, declare a sampling probability which controls
  when verbose tracing is enabled for it, and a latency threshold for
  which a trace is persisted/logged/etc. With a given stmt rate (say
  1000/s) and a given percentile I’m trying to capture (say p99.9), we
  have 0.001R stmt/s in the 99.9th percentile (1/s in our example). We
  should be able to set a sampling probability P such that with high
  likelihood (>95%) we capture at least one trace captured over the next
  S seconds. The sampling rate lets you control how the overhead you’re
  introducing for those statements in aggregate, which if dialed up
  higher lets you lower S. You might want to do such a thing for
  infrequently executed statements.
```

This gives use a mechanism to get to a bounded-overhead tail trace capture (bounded by probability and scope, targeting only a single stmt). A prototype of such a thing can be found here: https://github.com/cockroachdb/cockroach/pull/82750 (backportable form for 21.2, 22.1: https://github.com/cockroachdb/cockroach/pull/82864).

For a second step, I'd like for us to capture such outlier traces continuously to be able to have traces for high-tail events in the past (often what we want during escalations). For that I think we'd need to specify the maximum number of traces we want to capture over some period of time for a given finger print and some eviction policy to not accrue garbage indefinitely + keep more valuable traces around (probably just evict the oldest, all things equal we probably only care about recent traces). A crude approximation of this (this = capture multiple bundles for a given request as long as the request is not expired) can be found here: #83020.

**Additional context**

Very closely relates to https://github.com/cockroachdb/cockroach/issues/80666.

**Comment by kevin-v-ngo** [comment]
Hi @irfansharif, for UI enhancements do we only need to allow the user to configure a sampling probability? Any other improvements for this version? Adding @Annebirzin 

Note: We discussed being able to view all bundles for a fingerprint. Today, users can already view all bundles on the Diagnostics tab in the statement fingerprint details view. 

Future improvements we discussed which would require additional backend plumbing as well

1. Provide a time-based retention and #bundle limit for how long bundles are kept
2. We have a timer-based countdown for when tracing will be disabled. We should also allow users to specify the # of bundles before tracing is disabled or a specific time for when it's expired. We should also include an option for always keeping the trace on until it's manually disabled.
3. Surface captured time in the UI (we only have activated time today) 

Missing anything?

**Comment by irfansharif** [comment]
The PRs above provide this ability, albeit through manual cluster settings (in v22.1) and builtins (in v22.2+). @kevin-v-ngo, https://github.com/cockroachdb/cockroach/issues/80666#issuecomment-1276413440 is relevant. I'm not sure yet how this could go UI wise -- you could either have users automatically specify through our UI what statements need to be traced, or you could have CRDB automatically always collect traces with some low probability, keeping around those that are considered "outliers" now that we've introduce such notions. I think that would be cool -- "pick a statement, and see why the slowest executions in the last X hours took that long. is it due to latches being held? is it due to network hops? is it due to excessive MVCC garbage scanning?". These traces can be a gold mine. Within CRDB we can include structured events in traces for things that are interesting -- like we do for contention events. You can imagine these auto-collected trace data per statement automatically bubbling up to nudges to the user indicating that optimizing a certain statement or set of statements would require doing X, like "reduce the amount of garbage accumulated" or "reduce the amount of contention somehow". But the auto-collection of traces is what's key, it's something the system is always doing in the background with low overhead and the only user action needed is a reaction to actionable data. The things you note above still hold true: we need sane retention policies to not collect traces unboundedly, and somehow surface some relevant trace snippets to users (maybe). I'll leave this issue open for the general brain-dumping, similar to #80666, but if we want to take this forward we could use more targeted issues that are less meandering.

**Comment by irfansharif** [comment]
Just spit balling: imagine we always collected traces, and in our latency graphs we annotated sudden spikes with relevant trace captures at that point in time, if we happened to collect them. That'd be awesome -- you can go from metric to trace/statement bundle without having to have done anything upfront.

**Comment by irfansharif** [comment]
Follow-up issues: #90292, #90288.
