### ISSUE TITLE
Increase visibility as to which interval is being shown on SQL Activity pages 

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#82914]
We should increase the visibility and provide clarity as to which start and end time interval is being shown on the SQL Activity pages since we are showing the last full hour. 

Few options:
1. Remove the 'Past 10 minutes' and 'Past 30 minutes' since we always show only the past full hour
2. Prominently Highlight in the UI the intervals we are showing stats for since a custom time or 'Past 1 hour' could fall within an hour

CC @Annebirzin 

Jira issue: CRDB-16725

**Comment by maryliag** [comment]
we do have an [issue](https://github.com/cockroachdb/cockroach/issues/74523) to add this info on the details page, should we also add to the main page?

<img width="445" alt="Screen Shot 2022-06-14 at 7 39 27 PM" src="https://user-images.githubusercontent.com/1017486/173706810-8c56a0fe-3ef2-49f9-a93b-b0675e284f83.png">

**Comment by kevin-v-ngo** [comment]
Thanks @maryliag! Yeah, i couldn't find this issue as I was searching for different key words. We can close this as a dup or perhaps just scope this issue to removing the "Past 10 minutes" and "Past 30 minutes". Not sure if we can conditionally do this for the SQL Activity pages since i remember this picker was shared with our metrics pages.

**Comment by maryliag** [comment]
Btw, one thing I noticed was that rounding the end date to the next X:00 was a little weird, specially on the Statement Details page, because you would see the values for the next hour (because of the way we group in 1h buckets), so I changed to the end value going until X:59, so on your example, with the time picker on `May 5, 14:34 - May 5, 20:34` the label would be `Showing aggregated stats from May 5, 14:00 to 20:59`

Also, since we're using 24h format, no need for the `PM`, right?

**Comment by maryliag** [comment]
For the metrics page we do have info about last 10 or 30min, are we also removing the options from that page? Just thinking about alignment, since we want to have a global value that if you change in one, also affects the other and it would be very janky with those options in just one of the pages.

**Comment by maryliag** [comment]
I do think we should keep the 10/30min option, but the concern I had with option 2 is the flow:
Metrics page select 10 min -> Go to SQL Activity page -> The time picker will change the value to 1h -> go back to Metrics page will show 1h and not the 10min
is that okay?

**Comment by Annebirzin** [comment]
Makes sense, I think that behavior works
