### ISSUE TITLE
beta-20160803

### ISSUE THREAD

**Issue by WillHaack** [cockroachdb/cockroach#8291]
Started one beta node running sha e5e7518 so far.
rho waiting for data-race build for same sha.

**Comment by mberhault** [comment]
Both upgraded nodes on `beta` crashed after ~1h (triggered by the `CheckUpdates` calls): #8293

**Comment by mberhault** [comment]
CC: @bdarnell

**Comment by mberhault** [comment]
Due to #8293 specifically, and the move to go1.7rcX in general, we're skipping beta this week.
