### ISSUE TITLE
batcheval: `AddSSTable` does not adjust `GCBytesAge`

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#82920]
When `AddSSTable` checks for conflicts or shadowing via `CheckSSTConflicts`, it is supposed to accurately adjust the SST's `MVCCStats` to reflect the effect it has on the existing data. However, it makes no attempt at all to adjust `GCBytesAge`, leading to incorrect stats.

To see this, change e.g. `TestEvalAddSSTable` to use timestamps that are larger than 1 second, i.e. 1 billion nanoseconds -- so use `1e9` instead of `1` in timestamps -- and pass through the request timestamp to all stats calculations. The stats assertions will then immediately fail. This is because `GCBytesAge` computations only care about whole seconds, rounded down, so timestamps less than `1e9` will always result in 0 `GCBytesAge`.

There is some draft work in this branch: https://github.com/erikgrinaker/cockroach/tree/addsstable-stats

There are several scenarios that need handling:

* The SST shadows an existing value.
* An existing value shadows the SST value.
* A value in the SST shadows another value in the SST.
* All of the above, but with tombstones rather than values.

A fix for the simplest case is e.g.:

https://github.com/erikgrinaker/cockroach/blob/5c20fd3ea286fee34df577c2d92ef62c60e2b4fa/pkg/storage/sst.go#L197-L215

Jira issue: CRDB-16730

Epic CRDB-2624

**Comment by erikgrinaker** [comment]
@itsbilal We should address `GCBytesAge` for range keys as well. Should we reopen this issue for that, or alternatively create a new one?

**Comment by itsbilal** [comment]
@erikgrinaker I'll just re-reference the same issue for now, so let's reopen it for range keys.
