### ISSUE TITLE
sql/schemachanger:  column prematurely turns to PUBLIC in `ADD COLUMN ... UNIQUE`

### ISSUE THREAD

**Issue by Xiang-Gu** [cockroachdb/cockroach#82953]
**Describe the problem**
```
CREATE TABLE t (i INT PRIMARY KEY);
EXPLAIN (ddl, viz) ALTER TABLE t ADD COLUMN j INT NOT NULL UNIQUE DEFAULT 34;
```

generates a graph like [this one](https://cockroachdb.github.io/scplan/viz.html#H4sIAAAAAAAA/+ydbW/bxrLHXzefQjDuq4OTlrPLx9zUgGMrhRvbybWdFhfFgUFLjK1aJnUoOqfpxQH6tU4/Tj/JBUemSEmzfLAoZWnNiwCxd5eidv47O7v7m/VwdBP7k9te7/9efDN9uJ79MBg/TJMgvppC+mvi98I0sOSbsX8djL/f+xBNk8Po/n6UnEXhefA5iJPR9Tj4cOtPg9408W+CHvSiTz3R+9coue1ZvdOHxE9GUXj5ZRL0osl077/Tp4XChF8eH2m8Ouqf9C/7V+/PTv537x9ZucjK4dXBm4v+2eW8yJo3BePVh49vTo4P87K8Gby6PD84uzjun11ekZ8gs6pi+SmmmRXJlSIrKzJXiuysyFopcrIie6XIzYqclSIvK3IrvotlZDW9lR6Zf821bfeqN3y4v/+y9/fprT8Jvt+bRKMw2fv7NPkyDr7fG4WfR9PHj33xzTf/pvVkmU31JArv5Cr1ZFm5npb1YiulZFtqKdk2KaXlhztKFVmuUkWWp1SRbShVZINSRbZQqsiWlIqWO8JUCsh2Ggio3FgtCMhyFfpZkTHICh+UG2HZ9rkNYLnEKwhmsQ8do6CXn8+Pl8ZobjxBlQqVVnLzLUslt9myUnJZ26/eHBy+e3t8crL4cXYul8VvkVvbpV7TzWWy9O1hVSUNTNKCMsBVuZaF9zCKLyJV2gC34E9+Ojg5Pjq47B9lXxZcpUsBz1IqBDy7VCLgKp0JuEpnAq7SmYCndCbgKZ0JeEpnAp4skwd4BTdy2j//YbmYcCVNjNOGSrxaDmRBrtB74w/uPo3G48cXyUTieSUiEYahnHcMtRsRUO5HhAHKGcdQehFhKN2IMJR+RBiWcsYxbOWMY5T6EGG4SyLJuwyqvEi5XdoIUEDU0YdYfI+f/PFoWJRqFpaALFMImEqFCKlWiDDLFQKWUiFgKxUCjlIh4CoVAp5SIcJQKkRAqUKEyBWy2mvCqhBJlXHakImw68hEFt/EVAavwilTiXCVKpGOOn6VbrlKhKdUiTSUKpGgVIkUSpVIqVSJNJUqkVapSqStjFmlVyGRCsO0oBCnjh8RdaYZR6riVMdUxamu2n245d7DscriVEfpPxyl+3CU3sPxVuPUXPiuoQpS3VL34QpVkOpWeI5yc7QgCreO15C1IlTXUanCdVWq8BylKrxyb+F6ZarwlP7CU7oLT+ktvIKzIDY7PFMlC6/UX3i2ShZehbeoMEgbUamh2mYrvodZb+ligEoZYAiVNABAvW4BUb5uMWSZOsBQbqeBodxOA0O5nQZGYTuNWGYYrkohYHil6xcwVBoBIPbRGhinDZFAnQWuVWvlApZSI2ArNSJK1raiYm0LTqlGQL2+BfX6VqjXtwKWNJKv3oVQ6kOUr2+FqdSHqFjbltulDXmIOitbu97CBYRycwykcncMpHpdC2b5uhZk6QYZSOXaFqRybQtSubYFWVjbru7wSOUOGcjS5S1I5R4ZmBXL2yrjtKESs05c6hRfxFPONGbZ6hZM5eoWLHV4ClZ5fAqmcnULpjI6BVMZnoKpjE/BVK5uwVKubsEqDU/BKsSn5O4sWBVxaoV52pCJVSdSdWvNNVbZ6hYs5eoWbHW4CnZ5vAqWcnULtjJaBVsZroKtjFfBVq5uwVaubsEujVbBtldVUug2uyJmLTdNGwpx6oSsXr2Q1YEyiTjKs2BwS6JWtyJqdZQHwOCoI1ZHHbE66ojVUR4Ag6M8AAanPFp1C9EqsVACtyJkrTBOCyIxlyLWOFCdDM1eQqgUYirjVVMZrlrqaNUqBqtE15mFYJUqVgarpjJWtZShqgWruyALH2cp41WrEK4S72kpw9XcJz/BJi0IQy46j4vET4L7IFS+hPLgXyoXu1K51jXVTsMU5cKQslQYUuk3pNJtSKXXkE6FMKRyoSu9UmGYynVuHtI9wSZtCGNBF9PsHeZ+4JdPUZhMR78H3+95e3+fVXv9OvGvx0FvMPan0+/3oockiPf2Xyfx/utkmP32NvCH6a+ng8n1t/Pv9vq7ZLj/+jusitX3F5+FP8yftX8eDP1BEgyX2ifD/YOTy/557/LgzUm/99cf/xkGn/yHcTK8/uuPP7+dPFyPR4Nv//rjP8lff/zZOzg66h2+P/l4epbW/DX91fHZpds7e3/ZO/t4ctL7eHb8Px/7vaP+24OPJ5dpJWn+9cefq+9a/hpJ8ZN+Lf8MaZY8/dK/oT6g0OI77Kf9/Dcvsl+92M/EEEZhUGX9xbVJ4sc3wdz01tqm/xva/kM8uvfjL8fhMPitofmD++tgOAyGhbZVTQZROE1ifxQmx8N5C1j93FH6yIoq04/h6J8PwbxOEmc/FKvdBV8Oo/HDfXg0ioNBOjynilf97I/zFz24OCwz6MrTj4e1Hgt1Hoq/L355wyxt1lBuod2SdNDuZ/490eulIqhh3HD+1LQ/riZ3wZe1+6miV5yWemWmh4ZdMngU0fy7iNUHTG4OkiQeXT8kwdnDfVnNdjvGbbVjnqCXOp2zIJhfN90lXqtdksYLG+iSzD2nj7+s556T+ZtU1fzk34/GX+Z1j8PkbeE3xdeIRoW3NFbL/zUaJrfzGnZDV7cZ+4LRqoGPZuFP/7dJHEyno2gT3iGzdvoh9UwYFGtK89WrV2lM9BU6G3YqlCFs93xDmWn0EA+C4+oJf5pE8Si8afQGYn2tZpWC+0kUZ9op1JatBl4gNIu8qibS7UReIFvqlssFM+rrAiS7AH1cQAvDev1tmJl+L4JBFA63p99lXRKesZO6rKWKu+DLxcOnT6PftiX5xgu1qsnJalfFbe0otTU5EV2xNDn9erWN2amt7ZJtz07L/Wnx6NZpdCufP5p+nI7Cm/lk0A8H0XAU3qiM1FjQ83OUhscT+SnETTDbhg5zTm3xvCnMKbXF46awgO8vnjaFOWMFsFRi5MdMiwWQHzAtFoj8fGmxQObHS4sFZn66tFhg0adKYY74uUsFDn2c9CLtxRffhNbL/ULHJVHvsVLW9UN/ehsMsU1op3W9enWdl/uFrkqi3mPHU3XdtC7Uq+uldUW9umCklWXNypBWNmtWFmllq2ZlmVa2C5VXcn3JZmbazKn5GakdhVuzcmpI4TV9IWFiF1nrz82//GM6iCbfvp80nHiMudv5Gz7gMA78JPhh8GN0/TaK8+noReWTZh7zqGwJMD9jexvFR3E0+TG6rjfXlR/9zY8fs7PHJ58FKp32Jfr6o6a+HpZ699S/m80sB9fT7NtU92z/cxAmb/xpzb3bg4fkNopHv+Nhdc0mk8lZMfb6r94gGtzFkT+47U3/OV79Yh+nQbzQIo6ipE6P6HaWXH3aO1dAfBMkp0HiD/3ErylbDCX6Y/ykiqHxcP1zFN8pKjXYKa8xDJuKuSwCeXRjM+dt/5L5uChJ5j7OQh9nW3QhtrTXD8L1c4BEQP5V3cgG3q+GMnCmthzS+CbOx5ZLF+L8a3l0Ic63tkEXYqRkA12IoZEt6EKMhez1Nyz1UyOxKamVGlt4v2o1Whi+2ibtimZB5fqgQFvGPw/uo8/Bj9E1zlZv4+j+KJgO4tEkieKavZw3UPbjY80fo+vak49CCB8nQz8JLga3wb1/eOuHN0GcRXg19DA9i8JDPxwE47SgYstC/baPFc4fwjBdZSd+8pDvDfjj8Qztm/YG0f1kHCTBcD1JWanHcCQlKDsVm0NqzU5buWQrJ23l0q3SidQh51E7nUYdcv61U1k7pAO2U//rkO7XTr2vsz4I0dZYyJD+dVwgsYdzUdjs2W7MZKczmEtOYHY6f7nk9GWns5dLTl7g4saDR06Y4OKEaZCfBx5OtQbd0sOWQLd0Z5sS5LuCi1OtoXhbnGoNcgyAh37aIEcBeBhPGuQ4AA/jSYMcCeChhzfIsQAeBiPG+jhUW5I/DeKboIneszHyuI1cUCvh78sFnVVaPJugY8cniB88tD6Q1hcGWh/oWdqYbVfRLWfbU0LREnUD9DrEQN0AvYIxUDdAB7EG6gboINbAkQV0EGvgyBJ0EGvgyBJ0EGvgyBLr8wZtafUxeTOYnTes46QbS/UpceBs/1DQBp3tEgraoAJbSn2CxIsgWTyRa6XLz2qdxLVvGIF9L+m+n+3ICnowzXZgJT2YAAeTpAcT4GCS9IoQ0N1I2t2I2W447W4EuhtJuxuB7kbqs+2RLuIOhsNguAgpfMANOJ2HskBRSH0i1YsgyZZs78MNLtjwE+rtQ2q9I3z4EMdBmMxWakGtc9x50uy88uyMZf7j7KRmEz/mialPbFDeGdXr2mAcfPZn3TXLFavTYek/hBRyeeEDrha346vlubp9zxlkTzhTqHR0NQ6k4psgOffDu1oCMJY1lS+H87233GXnEX4y3Lfn/3Pm/3Pn//MKXir/b639o9l3aCbgWZuaan08efkQR0lUT7CrjHlVC86S0zRLTv1obQ7xFsbB0lZlcUZTeIgtjosl6K+q+ldKAWSTt2jyYqJjtUf7ivmNHbd6MV7Uxer1R/pXSN5ke7du78vaiaGcmcri1Uy8ivTbNpWsYdYtC2lXln2cUaxROmFWqaWMYh7F+ixSt5QtzSZv0eRU0p1GrpszwTVy3c/fHS/nHOkySqnE9w2MUs531zojtip0asiUdXys6jWPrhk6bSuXn23evdiJ7ynQ2itv7p6Cjg/WRsHU+pNW95JpGv6F9dUr93uTIMwVVbfDVglAhDvN9a8ZbJOlPIqjyeTRTx4F4yAJ3oePhxStpNJvAKREDNakMViJfWzRAK3ElpY+NHrrBthKqqxA1NikUWOJqLFJo8ZydtEGjRpLRI1NOrNBIs5u0iC8RBjbpGFsidytqQ9327rRt5KRKhFbt2hsXaIiLH3SkZltnrXYINtc+PsV8+pbo5vzmId6jSe3Le8kZp6Zea4VIjPzvHuH38w8NwkvOr7k1uvUgpnnnTM5M8/bsbpeG+HMPO+ivZl5Zua5s+Jl5pmF9JyXfcw8awTOZZWYedZvFDPzvHMmZ+aZXXebI7HbY5OZZ2ae9aXrqkInZp47Gzox89xBmzPzzF655PnMPDPz/FjhycyzKDDP9oaYZ0e+3A9dktp0zLSIZDbdtJVHtnLTVh7ZyrHSB5KX7jp22opkFx0nLSJ5YcdNi0jO2PHSIn14x1P/LshuVR+FN+1wpYS7ap0rdY20I0la2IW0iGSFXZEWkaQw/nEBTx/al0nUWYsNkqgtX4S79GMNzpX4iKUaFQ3Ku4S5U+ZOa4Up+TxfEVQwoLp7J5UMqLazFujE+kivLWYGVHfO5Ayobsfqeu1aMqC6i/ZmQJUB1c6KlwFVFtJzXvYxoKoR5ZRVYkBVv1HMgOrOmZwBVXbdbY7Ebo9NBlQZUNUXhaoKnRhQ7WzoxIBqB23OgCp75ZLnM6DaXUB1beS0SJmavehTD+QMM4VlzLQdytR1Xu6HYJAQp+tiGUlxetgOyHYetgOynevhM8kLUD0Dy0ii0QMsI5FGT2AZyTR6EsscbaDGU/8uOJh78hloehAOf45H2gOnnol9SRLEnoVlJELs2agHkiH2UA+gDw7M0OmsRWeh09P++Q/MnJZN68ycMnP6mplTvQ8fmTltJ7zvxJJHr11jZk53zuTMnG7H6nptRDJzuov2ZuaUmdPOipeZUxbSc172MXOqEbiUVWLmVL9RzMzpzpmcmVN23W2OxG6PTWZOmTnVl26qCp2YOe1s6MTMaQdtzswpe+WS5zNzyswpMqfWInOaXYzZKnMKBsKcQMKcYCDNCSTNCYAtBd0SsKWgWxoIggJ5MyoYSDYCSTaCgWgjkGgjGMg2CpJtBAMhWQHawI2nQXwT5O68WluZ/R8ngXWAU3IiUvwp/ieJCqljQVLHYCBmKkjsGAC5Y0FyxwBofUFbH9D6kra+wJaSbimwpUm3BNSNJOFqAPyekv6egN9T0t9T4PeU9PcUOLKkpY1Wf/LHo9QrzqKFJqL9Gmw0CHQ+knY+Ap2PpJ2PQOcjaecj0KCmPnz0qX8XHMXRZBIMiwcprYHsxPzVvrEkjgTT1KZXL4JkcVXWSsctrPEG8fD6ahQmQRz64ysM1K/gKl25XU3G/iC4jcbDIN5K76OmLdpJmWgai3ZSEp2UqY+TSkfDLNr/gMBzTds9LhBKXVT/cxAmb/zpc0gS0I0dr6a7FxYL2ixhShY1zQapYh1yHnyKg+lt2k/TmlLegHvAmdSkZ1KJM6lJz6QSZ1KTnkklhmOmPtfbzzPBivNoIzfCLoJdRG0X8VWiYonLHMvQZtC1EGgRHXdWBx3YQO/iOtGi14kS14mW0KbrFzNfC39ypYkd6o2vZZMR+xDH9bah3210G3r+9OOj9rah3y1tQ9d7dK2904vCNvQGt4LKDwfnBlScNDffql4ZWCauMyx91hmcldwsmnhCVvJPByfHRweX/byHlrKAG2UhN/qRSEh+c3D47u3xyUmjRObyPuG8ZM5LrhUpcl4y5yUrT/Q5L7lJZNHxY3G9yELOS945k3Ne8nasrhesxnnJu2hvzkvmvOTOipfzkllIz3nZx3nJGiW3ZZU4L1m/Ucx5yTtncs5LZtfd5kjs9tjkvGTOS9Y3A64qdOK85M6GTpyX3EGbc14ye+WS53NeMuclY16yu428ZBOTCyw6ucDE5AKLTi6wsKVNt7SwpU23NDEtwaKzRE3Ep206S9RE+tem6V8T6V+bzhI1MQHLphOwLEzAsukELAvBSJvOv7YwccO2taEmM5WskzxKwVjtULBPUaiFNndom1toc4e2uY0tXbqljS1duqWFanFotdioFodWi41qcWi12KgWh07zsXE8OfR4snE8OfR4snE8OfR4snE8ufqkI5z6d0GBhC+k0q6RQkuh1q0r0UZVuPokJjMiPWuxM4j0Uf+kX/F3nBiQZkCaAWkGpBmQZkB6I+tzvY44GJDeOZMzIL0dq+u1a86A9C7amwFpBqQ7K14GpFlIz3nZx4C0RpRdVokBaf1GMQPSO2dyBqTZdbc5Ers9NhmQZkBaXxSvKnRiQLqzoRMD0h20OQPS7JVLns+ANAPSCEiDsUhInz4kiJ21S0g7SHS6NNHpINHp0kSniy09uqWLLT26pYMsqEuzoA6yoC7NgjrIgro0C+ogC+rRbLWDtKxH07IO0rIeTcs6yEV6NC3rIi3r6fN3RxbvZG7tj7hshUB1UReeo01nMoE6a7EzBOpp//wHBlAZQH3NACoDqNpsZzOA2k6s34n1j15byAyg7pzJGUDdjtX12pVkAHUX7c0AKgOonRUvA6gspOe87GMAVSOKKavEAKp+o5gB1J0zOQOo7LrbHIndHpsMoDKAqi/qVBU6MYDa2dCJAdQO2pwBVPbKJc9nAJUB1BmAClu4ohdvy6Uvy8W7cumrcq20lU22stJWjl4Xgm4AyCS8aetAJt5HbIN+XZnt/z+xLx998nZv+sX7m+nrm/H2ZvryZry7mb66GW9upi9uxnubbRK+xnutbX0Q2w0ND2IDpnWL4i3g9CXgeKuzo8/IYZB51mKDIHNj1rgRq/zm4PDd2+OTk0Zs8moNhpkZZmaYOfsfw8xf4WiEYeYmMUfH19J6HUcwzLxzJmeYeTtW12uHm2HmXbQ3w8wMM3dWvAwzs5Ce87KPYWaNiLisEsPM+o1ihpl3zuQMM7PrbnMkdntsMszMMLO+2FxV6MQwc2dDJ4aZO2hzhpnZK5c8n2FmhpkRZhZbYJklvNwPTZLIlCItIolMM21lka3MtJVFtpIyfSB5ha400yKSS5RWWkRy09JOP4ukraWTFpFX50o3LSKpVumlRSTVahppEUm1mun3svThU7dFTh6Ho2Tkj0e/V80fjFhSgUja1/2T/uYZS+pTyiHLlRbl/cKUJVOWteZapiyZslSuT5iybCeg7USQr9c+KVOWO2dypiy3Y3W9tt6YstxFezNlyZRlZ8XLlCUL6Tkv+5iy1AjVySoxZanfKGbKcudMzpQlu+42R2K3xyZTlkxZ6svzVIVOTFl2NnRiyrKDNmfKkr1yyfOZsvyqlOVhHDydstQaEivyc/WGQz3BtntPbhEtlb3ThwT78hEtnRJsaSbBpxFcTYktRrBqIVhrDc1lFBjcl/uhJJFZ8NIiEpkVaSuTbCXSVqbQhoud39uahgaFu1ub3tnaIOYsv/34uF5g8G6jgcH86TXdVa3A4N1SYFDTE9Z59EUhMGj1OuS5URTr+eYBwfIIE0Y6jKR+A6J4OXXjS6nrDYc6F1h/qM3QrH0xsiouOYlu+p/rz1OPYVuTLqhXV1PkCPvmjT99DjS/brFF9ey/EM9rs8pod5Oglh+F1I+a2vjRiyBZAsvaudD/rIIsa/16eCHSjrV06tjC/DTHuOr2bn3ua/0/r5BVqg+F1X87baCwVtYZQqYis7UR2cFwWEZa1cmYw3btKa0p69V/MpW1fhxVbW4zNbc+2ZGLf70jS6rNNjtaXQIe5ufqpTNujcVMJ5eKa6znqLhk4Vy9xcVqPce+eK5H/9mWdgaMlQ4YMhda2GmRp99Y2sqOylOHE4Gp8HD6WsOpnSHivNwPTSrx/8W/X/x/AAAA//9fxUSzkwMCAA==).

This graph is incorrect in that, during Post-Commit phase stage 7 of 13, the newly added column element transition into PUBLIC when the new primary index is ready and we swap it with the old primary index. However, the added unique index (created as a result of adding a *unique* column) is still in the BACKFILL_ONLY status before/after this stage. 

The correct behavior should be that the primary index swap waits until the unique secondary index is also in the VALIDATED status, and then we do the primary index swap as well as making the unique secondary index PUBLIC in one stage.

**Comment by postamar** [comment]
I checked this and the problem still exists. Marking this as a GA-blocker.

**Comment by postamar** [comment]
Don't forget to backport this to 22.2. FYI, you could have created that PR automatically by tagging https://github.com/cockroachdb/cockroach/pull/88489 with the `backport-22.2.x` label. I believe you can also trigger it by commenting with something like `blathers backport ...`

**Comment by ajwerner** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/89415
