### ISSUE TITLE
sql/pgwire: DECIMAL columnn results perhaps not properly encoded

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#8298]
Reported by @fishcakez in https://github.com/cockroachdb/cockroach/issues/5582#issuecomment-236400566:

"""
The DataRow message from `SELECT 42::numeric` has 1 column value in length. However it will include 2 empty column values `\x00\x00` after the numeric column value.
"""

**Comment by knz** [comment]
cc @mjibson @nvanbenschoten

**Comment by mjibson** [comment]
I am not able to reproduce this. Here's what I tried:

I added printlns to show what's going on during row writing:

```
DATA ROW 1
DATUM 0 , FMT: formatText , V: 42
WRITE DECIMAL 42 , AS BYTES: [52 50]
FINISH
```

Here it says it's writing a row with 1 column. Then it shows writing one datum, the string "42", and just to make sure there's no hidden 0 bytes, I print the bytes of that string, and they are the expected ASCII values. So no problems here.

Next I put a proxy inbetween a server and a client that prints all bytes coming through the connection. Here's what it printed as bytes:

```
68 0 0 0 12 0 1 0 0 0 2 52 50 67
```

68 is 'D', the data row start character. The next 4 bytes (0, 0, 0, 12) are the message length, so 12 bytes total, or 8 if you subtract the length bytes. The next two bytes (0, 1) are the the number of datums (so 1). Next 4 (0, 0, 0, 2) are the datum length in bytes, so 2. The last two are the characters '4' '2'. The 67 at the end is a 'C' for the complete message.

I'm not able to reproduce the extra columns you report.

**Comment by fishcakez** [comment]
@mjibson this is using binary format and not text.

**Comment by fishcakez** [comment]
Here are the bytes printed, notice the 2 extra bytes at the end - though those are accounted for in the `22`, they are not in the columns length `1` or the decimal length `10`.
```
68 0 0 0 22 0 1 0 0 0 10 0 1 0 0 0 0 0 0 0 42 0 0
```

**Comment by tamird** [comment]
@fishcakez we have a test where we exercise binary decimal encoding using libpqtypes: https://github.com/cockroachdb/cockroach/blob/1851d4d/acceptance/c_test.go#L147:L183

Can you take a look at that test and how it might be used to observe this issue?

**Comment by mjibson** [comment]
I'm looking into this also. Thanks for the followup about binary.

**Comment by tamird** [comment]
@mjibson #8319 might be a good reference point as well.
