### ISSUE TITLE
kvserver: migrate `multiTestContext` to `TestCluster`

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#8299]
`multiTestContext` runs multiple `Stores` without `Servers`, and to do so it has to mock out the transport layer. Originally this was done because it was not feasible to use the regular Gossip and DistSender in this environment, but now we've moved closer to the standard environment and the last piece missing is the `Server`. We should go the rest of the way and move these tests to `TestCluster`, adding features to `TestCluster` as needed. 

The immediate motivation for this change is deadlocks that result from `multiTestContext` using one `RWMutex` for too many things: #8170 and #7678.

**Comment by tbg** [comment]
Sadly, this is still a problem (for the latest, see https://github.com/cockroachdb/cockroach/issues/32970) and we've started using `multiTestContext` in more places, usually in tests that need access to lots of internals (for example the merge tests).

**Comment by knz** [comment]
We've seen an uptick of test failures in the past few weeks caused by a multiTestContext failing to shut down properly. Maybe time to revive this.

**Comment by knz** [comment]
cc @lunevalex we discussed this yesterday
