### ISSUE TITLE
changefeedccl:  Support CDC query in alter changefeed

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#83033]
Extend alter changefeed statement to support specification and modification of changefeed expressions.

While on the surface it looks like a straight up change to grammar, we have to be careful when
new expression, and in particular, the filter, results in a different set of spans that need to be scanned.
In such cases, what's the implication for checkpoint records?

Jira issue: CRDB-16807

gz#19668

**Comment by miretskiy** [comment]
Issue not stale;

**Comment by rharding6373** [comment]
blathers backport 23.1 23.2
