### ISSUE TITLE
Provide function and access point to retrieve cluster/DB statistics

### ISSUE THREAD

**Issue by WhiteTrashLord** [cockroachdb/cockroach#8305]
Is there already a function which returns some information about the database?
I would like to know how many keys exist in the database and how much the total RAM usage is for example.

**Comment by petermattis** [comment]
I might be misunderstanding you, but we don't currently have any such functions or information accessible from SQL. The admin UI does show aggregated statistics across the entire database including the number of keys and RAM usage. We're actively working on tracking some of these stats per-table (number of keys, total size, etc). In addition to be accessible from the admin UI, these metrics and more are exported via a prometheus-compatible endpoint.

**Comment by knz** [comment]
Note that you can query the database using HTTP to get this information in textual format. This is what the admin UI does. For example http://localhost:8080/_status/vars. Check in `admin.go` for the available endpoints.

**Comment by knz** [comment]
@tim-o please determine next steps

**Comment by tim-o** [comment]
Given the age of this, the fact that we have range counts and memory usage in UI now I'll close this - @WhiteTrashLord if something is missing in the latest version, feel free to reopen and let us know what you'd like to see.
