### ISSUE TITLE
IMPORT from pgdump: line too long. (Question)

### ISSUE THREAD

**Issue by Samusername** [cockroachdb/cockroach#83101]
I quickly attempted to import data from PostgreSQL to CockroachDB, as a non-mandatory exercise. (Attempted to execute a short evaluation exercise.)

import pgdump 'userfile:/my_450GB_huge_database.dump'
   WITH ignore_unsupported_statements,**max_row_size**='30MB';
ERROR: postgres parse error: line too long
HINT: use `max_row_size` to increase the maximum line limit (default: 4.0 MiB).

There is one extremely huge database table. Most of the data is in one single DB table.

Q: Is there something I could try to do differently?

My setup:

I have tried to enforce CockroachDB to use more shards, right from the beginning of writing data to database. ( --> Faster to write. )
So, I have set max range size:
 -e 'ALTER database my_huge_dbtable CONFIGURE ZONE USING range_max_bytes = 51000000, range_min_bytes = 12000000;'"

3 DB pods.
Disk size did not start to increase, but it remained on following level all the time:
48G	cockroach-data
44G	cockroach-data
47G	cockroach-data
( "userfile" takes such amount of space )
( The full database would not fit to the disks fully yet. But the disk consumption does not even start to increase yet. )

I tried to execute it with:
cockroach:v22.1.1 (docker image)

Environment:
K8s

It was possible to import the same dump to PostgreSQL.

Jira issue: CRDB-16865

**Comment by Samusername** [comment]
I tried to import a small table from the same huge dump file. That table contains only couple of small rows.
Import of it failed also, to the same error.

**Comment by rafiss** [comment]
What is the length of the longest line in the file you are importing? You can use one of the tools here to find out: https://stackoverflow.com/questions/1655372/longest-line-in-a-file
