### ISSUE TITLE
sql/catalog/tabledesc,upgrade: migrate away invalid sequence references

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#83124]
**Is your feature request related to a problem? Please describe.**

Bugs in 21.1 and prior sometimes added sequence references which had the 0 column ID. We should migrate those away. 

**Describe the solution you'd like**
Write a migration to repair these references.

**Additional context**
See https://github.com/cockroachdb/cockroach/issues/82576.

Jira issue: CRDB-16874

**Comment by ajwerner** [comment]
This needs to be done before the end of the release but it's not urgent. It should leverage the machinery being added in https://github.com/cockroachdb/cockroach/pull/82172. I'm tentatively assigning Xiang with that background. The `release-blocker` label is just to make sure we don't forget.

**Comment by Xiang-Gu** [comment]
@ajwerner I will happily take this.
We need to write an upgrade, so I guess it will be similar to https://github.com/cockroachdb/cockroach/pull/81583 (not #82172)?
