### ISSUE TITLE
./dev doctor throw "requires Bazel cockroachdb/5.0.0" error

### ISSUE THREAD

**Issue by atidat** [cockroachdb/cockroach#83128]
**Describe the problem**
Bazel build throw "requires Bazel cockroachdb/5.0.0" error

ERROR: The project you’re trying to build requires Bazel cockroachdb/5.0.0 (specified in /data/prj_github/cockroachdb/.bazelversion), but it wasn’t found in /usr/local/lib/bazel/bin.

I have tried
1. vi ./.bazelversion: cockroachdb/5.0.0 → bazel
2. mkdir -p /usr/local/lib/bazel/bin/bazel-cockroachdb && cp bazel ./5.0.0-linux-x86_64
3. https://releases.bazel.build/cockroachdb/5.0.0/release/bazel-cockroachdb/5.0.0-linux-x86_64 is not available
But not worked

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
2. Send SQL ... / CLI command ...
3. Look at UI / log file / client app ...

**Expected behavior**

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version [e.g. 2.0.x]
 - Server OS: [e.g. Linux/Distrib]
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
What was the impact?

Jira issue: CRDB-16876

**Comment by rickystewart** [comment]
@atidat Do you have the latest version of `bazelisk` [installed](https://github.com/bazelbuild/bazelisk)? That'll be the easiest way to make sure you have the right version installed.

**Comment by atidat** [comment]
I’m so confused about correctness of COMPILE SUCCESS RATE.

v22.1.1 =>
[root@xx cockroachdb]# ./dev doctor
/data/prj_github/cockroachdb/bin/dev-versions/dev.27 not found, building…
ERROR: The project you’re trying to build requires Bazel cockroachdb/5.0.0 (specified in /data/prj_github/cockroachdb/.bazelversion), but it wasn’t found in /usr/local/lib/bazel/bin.
Bazel binaries for all official releases can be downloaded from here:
[Releases · bazelbuild/bazel · GitHub](https://github.com/bazelbuild/bazel/releases)

You can download the required version directly using this command:
(cd “/usr/local/lib/bazel/bin” && curl -fLO https://releases.bazel.build/cockroachdb/5.0.0/release/bazel-cockroachdb/5.0.0-linux-x86_64 && chmod +x bazel-cockroachdb/5.0.0-linux-x86_64)
[root@xx cockroachdb]# cd … && bazel version
WARNING: Invoking Bazel in batch mode since it is not invoked from within a workspace (below a directory having a WORKSPACE file).
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
Build label: 5.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jan 19 14:08:54 2022 (1642601334)
Build timestamp: 1642601334
Build timestamp as int: 1642601334

v21.2.9 =>
[root@master193 cockroach]# make build
Warning: your version of make seems old; your build may fail!
Makefile:58: build/defs.mk: 没有那个文件或目录
GOPATH set to /data/cockroachdb/cockroach
: No such file or directory
Disable this check with IGNORE_GOVERS=1.
make: *** [build/defs.mk] 错误 1
Can anyone solve this two COMPILE ERRORS

**Comment by rickystewart** [comment]
RE: the first failure, you can probably replace `cockroachdb/5.0.0` with `5.0.0` in the `.bazelversion` file (i.e. delete the `cockroachdb/` prefix) to resolve the problem.

**Comment by rickystewart** [comment]
> Warning: your version of make seems old; your build may fail!

RE: the second failure, I'm worried about this error message. I would try again but with a version of `make` that is 3+.
