### ISSUE TITLE
bulkio,internal: replace bulk-prs with bulk-io in CODEOWNERS

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/cockroach#83160]
Given the options on [this screen](https://github.com/orgs/cockroachdb/teams/bulk-io/edit/review_assignment), we no longer need the bulk-prs subteam. Let’s replace `bulk-prs` with `bulk-io` in [CODEOWNERS](https://github.com/cockroachdb/cockroach/blob/master/.github/CODEOWNERS/), across all release branches.

Jira issue: CRDB-16892

**Comment by mwang1026** [comment]
might want to remove me from bulk-io then so i don't get assigned PR reviews?

**Comment by shermanCRL** [comment]
@mwang1026  There is an option [here](https://github.com/orgs/cockroachdb/teams/bulk-io/edit/review_assignment) to exclude people from the rotation, I’ve added you to that list.
