### ISSUE TITLE
Implicit type casting between enum and string

### ISSUE THREAD

**Issue by Defman** [cockroachdb/cockroach#83169]
**Describe the problem**

Implicit casting between enum types and primitives/strings.

**To Reproduce**

```sql
CREATE TYPE FOO AS ENUM ('1', '2');
SELECT ARRAY['1'] = ARRAY['1'::FOO]::FOO[];
SELECT '1' = ANY(ARRAY['1'::FOO]::FOO[]);
```

**Expected behavior**
That the string `'1'` is implicitly casted to the enum type.

Jira issue: CRDB-16895

**Comment by rimadeodhar** [comment]
Implicit type casting is not fully supported within CockroachDB at the moment and is being tracked in this parent issue https://github.com/cockroachdb/cockroach/issues/75101. In the meantime, the workaround is to explicitly cast a type.

I'm closing this issue as a duplicate.
