### ISSUE TITLE
sql: support compound types

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#8318]
(this is a meta-issue to serve as placeholder and reference in error codes)
- [x] support ARRAY types #2115 
- [ ] support pre-defined compound types, eg #6981 or geo types or complex numbers
- [ ] support user-defined compound types _a la_ `CREATE TYPE ... AS ( ... )`

**Comment by knz** [comment]
Will need a fix to  #24686

**Comment by stangls** [comment]
We are currently testing the switchover over from PostgreSQL to Cockroach and are missing the possibility to create custom domain like `CREATE DOMAIN custom AS numeric(123,0);`

**Comment by knz** [comment]
@stangls thanks for your interest in CockroachDB. This issue is about a specific kind of type (compound), whereas you are more generally interested in user-defined types. I have created a separate issue to track this: #25123.

**Comment by knz** [comment]
This issue has now be fully superseded by #25123..
