### ISSUE TITLE
sql: lock on jobs table held in column backfill for a long time 

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#83202]
**Describe the problem**

In https://github.com/cockroachdb/cockroach/blob/5df10feceeaa18c9fab5373f492da10cef4300ab/pkg/sql/backfill.go#L1356-L1358 we issue a transactional write to the jobs table and then proceed to do a very long backfill operation. This leaves a lock on the jobs table for minutes at a time. Instead, we ought to use a separate transaction to update the jobs table. 

**Additional context**

The transaction in use in that block, more generally, is dubious. It's trying to hold a lease on the descriptor during the backfill, but it's not clear what that accomplishes. 

Jira issue: CRDB-16918

**Comment by jordanlewis** [comment]
🎉
