### ISSUE TITLE
sql: move NormalizeName to parser

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#8320]
Suggested by @tamird in https://github.com/cockroachdb/cockroach/pull/8152#issuecomment-236402119

This would enable NormalizeTableName to become a method of TableName in parser too, where it belongs.

**Comment by knz** [comment]
As suggested (indirectly) by @nvanbenschoten in https://github.com/cockroachdb/cockroach/pull/8152#issuecomment-237695775 probably the function `NormalizeName` should be renamed to `NormalizeForCompare` to clarify/highlight its different purpose.

**Comment by a6802739** [comment]
@knz, maybe I could do this.

**Comment by knz** [comment]
Feel free to give it a try.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by a6802739** [comment]
@knz, I found `NormalizeName` was defined in `sql/sqlbase/keys.go:59`, which was used to `NormalizeName normalizes to lowercase and Unicode Normalization Form`, so if I move it to  parser, which file should I put it into?

**Comment by knz** [comment]
table_name.go was a good choice. Thanks!
