### ISSUE TITLE
changefeedccl: don't default to envelope=wrapped when an expression is provided

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#83205]
The default for json format is to "wrap" (envelop_wrap); this makes little sense when using
expressions; we should default to not do anything.

Similarly for avro, we require wrapped output, which is not needed when using expressions.

Jira issue: CRDB-17034

Epic CRDB-16781

**Comment by amruss** [comment]
22.2 work

**Comment by miretskiy** [comment]
That's done, is it not?
