### ISSUE TITLE
teamcity: roachtest stress job does not support AWS (missing creds)

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#83219]
**Describe the problem**

https://teamcity.cockroachdb.com/admin/editBuildRunners.html?id=buildType:Cockroach_Nightlies_RoachtestStress no longer works (at least not reliably on a SHA from early April).

It uses make - it should use bazel.

Jira issue: CRDB-16925

**Comment by srosenberg** [comment]
> It uses make - it should use bazel.

It's already on bazel after Nick's PR: https://github.com/cockroachdb/cockroach/pull/81804

Mind giving it another try to see if there is still an issue.

**Comment by tbg** [comment]
You're right, it's bazelized. I must've been on some old SHA. Let's see if it can run one iteration of `acceptance/build-info`:

[gce](https://teamcity.cockroachdb.com/viewLog.html?buildId=5746925&)
[aws](https://teamcity.cockroachdb.com/viewLog.html?buildId=5746929&tab=buildResultsDiv&buildTypeId=Cockroach_Nightlies_RoachtestStress)

**Comment by tbg** [comment]
Both passed! But the "aws" build actually used GCE, I think:

https://teamcity.cockroachdb.com/viewLog.html?buildId=5746929&buildTypeId=Cockroach_Nightlies_RoachtestStress&tab=buildParameters

<img width="529" alt="image" src="https://user-images.githubusercontent.com/5076964/178956598-818d819b-e1f8-49a7-88a4-ad90ba984028.png">
<img width="809" alt="image" src="https://user-images.githubusercontent.com/5076964/178956668-b55cde4f-fd25-4640-9fe2-7c72afd7520d.png">

Going to re-title to that effect.

**Comment by tbg** [comment]
> Cleaning up partially-created cluster (prev err: in provider: aws: missing AWS credentials, expected ~/.aws/credentials file or AWS_ACCESS_KEY_ID env var)

**Comment by srosenberg** [comment]
> > Cleaning up partially-created cluster (prev err: in provider: aws: missing AWS credentials, expected ~/.aws/credentials file or AWS_ACCESS_KEY_ID env var)

@jlinder Could we please add AWS env. vars to this job; modulo the missing credentials, it should be back in business.

**Comment by rail** [comment]
I’ll fix it in a bit

**Comment by rail** [comment]
AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are set now. We need to patch https://github.com/cockroachdb/cockroach/blob/91d765006ddf92eb087596e62ffa7cb59392f4b3/build/teamcity-roachtest-stress.sh#L8 to pass them through.
