### ISSUE TITLE
Some SELECT statement summaries are too truncated

### ISSUE THREAD

**Issue by stbof** [cockroachdb/cockroach#83225]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

I ran  the movr workload and then observed the Statements page in DB Console.

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Ran `cockroach demo --insecure --nodes 3`
2. Ran `cockroach workload run movr --duration=5m 'postgresql://root@localhost:26257?sslmode=disable'`
3. Viewed Statements page in DB Console
4. Similar statements are not disambiguated. Though they operate on different tables they have the same fingerprint.

**Expected behavior**
Statement summaries that reflect the table being queried. These don't:

<img width="529" alt="Screen Shot 2022-06-22 at 12 19 01 PM" src="https://user-images.githubusercontent.com/20482960/175135662-8a4d44a1-445d-492b-9dea-47c2350c5567.png">

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version v22.1.1-153-g7a265fdca4
 - Server OS: MacOS
 - Client app DB Console

**Additional context**
What was the impact?

Jira issue: CRDB-16929

Epic CRDB-20388

**Comment by maryliag** [comment]
No longer a priority
