### ISSUE TITLE
schemachanger: Support `DROP FUNCTION` statement in declarative schema changer

### ISSUE THREAD

**Issue by chengxiong-ruan** [cockroachdb/cockroach#83235]
**Describe the solution you'd like**
Implement the `DROP FUNCTION` statement in declarative schema changer

Jira issue: CRDB-16940

Epic CRDB-19495

**Comment by chengxiong-ruan** [comment]
Legacy schema changer support of `DROP FUNCTION` is done with #85718.

**Comment by postamar** [comment]
relates to https://github.com/cockroachdb/cockroach/issues/90476

**Comment by chengxiong-ruan** [comment]
Fixed by #95153
