### ISSUE TITLE
Surface a Service Latency: SQL Statements, 50th percentile (Median) metric

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#83278]
We capture P99 and P90 Service Latency of SQL Statements and surface them as console charts. We should also chart P50 (median) as well.

Jira issue: CRDB-16972

**Comment by kevin-v-ngo** [comment]
Note: We may just be able to write an expression like how we do for P90 on sql_service_latency and add this to our existing chart for P99 and P90:
<img width="615" alt="image" src="https://user-images.githubusercontent.com/81193618/177699836-d0d005f2-53da-4248-84f9-c4748c704da0.png">

**Comment by maryliag** [comment]
We display p99.99, p99.9, p99, p90, p50
