### ISSUE TITLE
Better flow on database page for non-admin

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#83274]
Create user with
```
CREATE ROLE IF NOT EXISTS \"$${user}\" WITH LOGIN PASSWORD '$${user}' VIEWACTIVITY VIEWACTIVITYREDACTED NOCANCELQUERY NOCONTROLCHANGEFEED NOCONTROLJOB NOCREATEDB NOCREATELOGIN NOCREATEROLE NOMODIFYCLUSTERSETTING NOSQLLOGIN;

grant usage on schema $${crdb_db_name}.public to \"$${user}\";
alter default privileges grant usage on schemas to  \"$${user}\";
```

The details page of the table won't load. Hide pages that are not visible to non-admin, but make sure values are loading for users with proper permission.

Jira issue: CRDB-16969

Epic CRDB-20388

**Comment by THardy98** [comment]
Databases Page Improvement: https://github.com/cockroachdb/cockroach/pull/109245
Database Detail Page Improvement: https://github.com/cockroachdb/cockroach/pull/109432
Table Detail Page Improvement: https://github.com/cockroachdb/cockroach/pull/109521
