### ISSUE TITLE
DB Console shows a 502 error after attempting to switch web servers for a 22.1 cloud cluster 

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#83281]
**Describe the problem**

After accessing the DB Console for a Dedicated cloud cluster (v22.1.2), when you go to select a different web server to load through the Advanced Debug page, doing so causes the DB Console to be inaccessible with a 502 error.
This also prevents a user from utilizing query parameters in the `_status/vars` endpoint to target specific nodes through the load balancer with `?remote_node_id={node_id}`.

**To Reproduce**

1. Access DB Console for a cloud cluster
2. Go to Advanced Debug page
3. Attempt to switch to a different web server
4. Notice that doing so results in a 502 error

**Environment:**
- CockroachDB version 22.1.2
- Sample cluster: https://cockroachlabs.cloud/cluster/be089f9a-fb77-41ca-82ab-9bb60f05a8df/monitoring?cluster-type=dedicated

Jira issue: CRDB-16974

**Comment by abarganier** [comment]
I was able to reproduce this locally within Cloud on a v22.1 dedicated cluster. 

I noticed that each time you refresh the page and receive the 502 error, the proxied node logs the following message:
```
E220706 15:59:47.819223 16187 (gostd) net/http/server.go:3158 ⋮ [-] 1657  ‹http: TLS handshake error from <redacted_client_ip_address>: remote error: tls: bad certificate›
```

Investigating further.

**Comment by abarganier** [comment]
I was unable to reproduce this in a locally running cluster (I was using the latest from `master`), meaning that the issue is likely related to certificate management in cloud. 

Investigating further.

**Comment by abarganier** [comment]
I'm not having any luck with just setting the `--advertise-http-addr` flag. 

Setting this to the pod hostname yields something like `--advertise-http-addr="cockroachdb-2.cockroachdb.us-central1.svc.cluster.local:8080"`.

I'm noticing that the certificate being used for these requests (the ui certificate, I believe) supports common names of `*.gcp-us-central1.crdb.io` and `*.crdb.io`. Wouldn't it need to also be stamped with the pod hostname for it to work for the node proxy? The original request is using the ui certificate, which I believe is only really valid for the `cockroachdb-ui-external` K8s service. Once a node receives the original request and attempts to forward via HTTP to another node,  my hunch is that the certificate is no longer valid for reasons noted above. 

cc @catj-cockroach - does this sound correct to you? For context - [here's the proxy handler code](https://github.com/cockroachdb/cockroach/blob/master/pkg/server/node_http_router.go#L56). Let me know if I can clarify anything further!

**Comment by thtruo** [comment]
Relevant [Slack](https://cockroachlabs.slack.com/archives/C01CNRP6TSN/p1663270594497279) thread
