### ISSUE TITLE
sql: UPDATE and INSERT .. ON CONFLICT DO UPDATE do not use the same assignment code

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#8330]
The title of the issue is the cause of the following bug:

```
create table foo(x int primary key, y int, z int);
insert into foo(x,y,z) values(1,0,0);
insert into foo(x,y,z) values(1,3,5) on conflict(x) do update set (y,z)=(select max(y),max(z) from foo);
```

This fails with:

```
pq: unsupported tuple assignment: *parser.Subquery
```

Now as currently highlighted by #6852 tuple assignment from a subquery is not supported in UPDATE, so this issue is not saying they should be supported in UPSERT. However the error is symptomatic of a missing call to `replaceSubqueries` on the RHS of the assigned columns, which is present in UPDATE.

The proper fix for this error would be to factor the common code to prepare the assigned tuples between UPDATE and UPSERT.

**Comment by knz** [comment]
cc @paperstreet

**Comment by paperstreet** [comment]
Yeah, this code duplication has been asking for bugs.

**Comment by spencerkimball** [comment]
@danhhz, remove 1.0 milestone if not appropriate.

**Comment by danhhz** [comment]
@justinj thinks this may be the same issue as https://github.com/cockroachdb/cockroach/issues/6852, which is his starter project. so sounds like this will get done by 1.0

**Comment by vivekmenezes** [comment]
FYI, this issue still exists

**Comment by knz** [comment]
Moreover, it actually enabled a bug that can cause consistenty violation, see #23699

**Comment by knz** [comment]
Note: this will be solved with the CBO, thanks to recent changes by @andy-kimball.

**Comment by jordanlewis** [comment]
Fixed in CBO.
