### ISSUE TITLE
cdc, sql: core changefeed display format has become less friendly in cockroach shell

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#83302]
**Describe the problem**

On previous versions, running

`CREATE CHANGEFEED FOR users;` or
`EXPERIMENTAL CHANGEFEED FOR users;`

would display changes like this:

```sql
users,"[""boston"", ""33333333-3333-4400-8000-00000000000a""]","{""after"": {""address"": ""51438 Janet Valleys"", ""city"": ""boston"", ""credit_card"": ""0904722368"", ""id"": ""33333333-3333-4400-8000-00000000000a"", ""name"": ""Daniel Hernandez MD""}}"
```

In <s>22.1</s> master, it instead looks like this:

```sql
table,key,value
users,\x5b22616d7374657264616d222c202261653134376165312d343761652d343830302d383030302d303030303030303030303232225d,\x7b226166746572223a207b2261646472657373223a2022383831393420416e67656c612047617264656e73205375697465203934222c202263697479223a2022616d7374657264616d222c20226372656469745f63617264223a202234343433353338373538222c20226964223a202261653134376165312d343761652d343830302d383030302d303030303030303030303232222c20226e616d65223a202254796c65722044616c746f6e227d7d
```

I _think_ this is a cosmetic change in the SQL shell, and not something that's actually changed in core changefeed encoding. Core (sinkless) changefeeds have always output data in the form `DString, DBytes, DBytes`, but the bytes used to be displayed like a string instead of with their hex encoding. It's possible though that we've messed up how we're sending the header, or failed to keep it in sync with something.

**To Reproduce**

Build CockroachDB from source on OSX (looks like it happens in Linux too).
Run `cockroach demo`
At the prompt, enter `CREATE CHANGEFEED FOR users WITH initial_scan='only'`.

Alternatively, this will work on older versions too so you can do a direct comparison.

`cockroach demo --format=csv`
`CREATE CHANGEFEED FOR users`

Also occurs with `cockroach sql` connecting to a non-demo cluster.

**Expected behavior**
There should be some way of getting that friendly core changefeed display back. I don't think we can change the default way core changefeeds are encoded over pgwire, because backwards compatibility but there should be some way of configuring either the shell or changefeeds so that we again see output that looks like json, rather than hex-encoded json.

Relevant changefeed code: https://github.com/cockroachdb/cockroach/blob/d6229796806350537cdc2e74f51984a9ece4e503/pkg/ccl/changefeedccl/changefeed_stmt.go#L108-L120

Jira issue: CRDB-16984

Epic CRDB-8719

**Comment by HonoreDB** [comment]
Same change happens if you do `SELECT 'apple'::bytes`. 21.2 outputs "apple", 22.1 outputs "\x6170706c65"

**Comment by miretskiy** [comment]
I verified this; and I think it's more of a cosmetic change.  I think core style changefeeds in 22.1+ are broken by this.

**Comment by miretskiy** [comment]
I'm not seeing this on 22.1.

**Comment by rafiss** [comment]
The related issue is https://github.com/cockroachdb/cockroach/issues/80398 and the PR is https://github.com/cockroachdb/cockroach/pull/81943 -- it is not in v22.1

**Comment by knz** [comment]
Is this encoded in tutorials somehow? Could we extend these tutorials to tell the user to type in `set bytea_output = escape;` prior to running the changefeed stmt?

**Comment by rafiss** [comment]
Based on the above, we won't change anything on the SQL-Experience side unless we hear furhter.

**Comment by vy-ton** [comment]
@rafiss Thoughts on whether we should run`set bytea_output = escape;` as the cockroach CLI default?

**Comment by miretskiy** [comment]
@HonoreDB , I believe this was fixed?

**Comment by HonoreDB** [comment]
Fixed!
