### ISSUE TITLE
streamingccl: stabilize test failures as of June 2022

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#83319]
We've seen a number of tests failing periodically.  We should investigate these failures and fix the tests or find the bugs:

- [x] https://github.com/cockroachdb/cockroach/issues/82706
- [x] https://github.com/cockroachdb/cockroach/issues/79987
- [x] https://github.com/cockroachdb/cockroach/issues/77916
- [x] https://github.com/cockroachdb/cockroach/issues/76919
- [x] https://github.com/cockroachdb/cockroach/issues/61287

Jira issue: CRDB-16999
Epic CRDB-7077

**Comment by shermanCRL** [comment]
Looks like we’re done on this?
