### ISSUE TITLE
cdc: Expressions error handling

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#83323]
Encountering an error during expression evaluation is "fatal" in a sense that changefeed
will always encounter this error forever.

 - [x] Mark errors encountered during evaluation as fatal (I think that's already the case, but needs to be verified, i.e. tested)
 - [x] Be *loud* when these errors happens; logging , metrics, etc.

Jira issue: CRDB-17003

Epic CRDB-17161

**Comment by amruss** [comment]
Note: this should be done before the 22.2 release

**Comment by miretskiy** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/94806
