### ISSUE TITLE
cdc: Do not wrap when using expressions 

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#83336]
The default for json format is to "wrap" (envelop_wrap); this makes little sense when using
expressions; we should default to not do anything.

Similarly for avro, we require wrapped output, which is not needed when using expressions.

Jira issue: CRDB-17011

**Comment by HonoreDB** [comment]
Merged this description into https://github.com/cockroachdb/cockroach/issues/83205
