### ISSUE TITLE
backupccl: refactor backupccl to introduce smaller packages

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#83338]
This issue is a tracking issue for an ongoing effort to break the `backcupccl` package into smaller packages. `bakupccl` over the years has grown to house all of backup and restore logic. As the code base gets larger the lack of a logical division of files makes maintaining a mental model of the code hard.  Additionally, it makes it harder for new folks contributing to bulk code to onboard easily. We think there is value in paying down this technical debt by dividing the files into logical packages.

Going forward we might also want to move large parts of the descriptor resolution logic from `backupccl` to the `catalog` package, to be owned and maintained by the SQL Schema team since they are the experts in this area. Bulk would then become a consumer of the APIs they would expose.

https://github.com/cockroachdb/cockroach/pull/82381
https://github.com/cockroachdb/cockroach/pull/82623

cc: @livlobo 

Jira issue: CRDB-17013

**Comment by livlobo** [comment]
@adityamaru - sorry to be a pain, can you please add the motivation for the refactor?

**Comment by adityamaru** [comment]
Done!

**Comment by adityamaru** [comment]
This is done for the time being, we can open more targetted issues for when we take on more refactors.
