### ISSUE TITLE
sql: tests fail with --verbosity=2 because of nil planner context

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#8334]
```
make test  PKG=./storage TESTFLAGS="--verbosity=2"
```

sql/table.go:161 is:
```
		log.Infof(p.ctx(), "planner acquiring lease on table %q", qname)
```

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x440ac96]

goroutine 30200 [running]:
panic(0x5047100, 0xc4200120d0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Recover(0xc42252c090)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:176 +0x6e
panic(0x5047100, 0xc4200120d0)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/util/log.contextLastTag(0x0, 0x0, 0x0)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/util/log/log_context.go:56 +0x26
github.com/cockroachdb/cockroach/util/log.contextLogTags(0x0, 0x0, 0x3d, 0x570f088, 0x570f088)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/util/log/log_context.go:65 +0x50
github.com/cockroachdb/cockroach/util/log.makeMessage(0x0, 0x0, 0x519f9dd, 0x23, 0xc421fb2a38, 0x1, 0x1, 0x0, 0x0)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/util/log/structured.go:31 +0xa8
github.com/cockroachdb/cockroach/util/log.addStructured(0x0, 0x0, 0xc400000000, 0x2, 0x519f9dd, 0x23, 0xc421fb2a38, 0x1, 0x1)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/util/log/structured.go:58 +0xb2
github.com/cockroachdb/cockroach/util/log.logDepth(0x0, 0x0, 0x1, 0x0, 0x519f9dd, 0x23, 0xc421fb2a38, 0x1, 0x1)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/util/log/log.go:81 +0x8c
github.com/cockroachdb/cockroach/util/log.Infof(0x0, 0x0, 0x519f9dd, 0x23, 0xc421fb2a38, 0x1, 0x1)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/util/log/log.go:89 +0x7e
github.com/cockroachdb/cockroach/sql.(*planner).getTableLease(0xc421a8c800, 0xc4225c3940, 0x0, 0x0, 0x0)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/table.go:161 +0xfb
github.com/cockroachdb/cockroach/sql.(*planner).getAliasedTableLease(0xc421a8c800, 0x58556e0, 0xc42257e040, 0x0, 0x0, 0x0)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/table.go:334 +0x83
github.com/cockroachdb/cockroach/sql.(*planner).makeEditNode(0xc421a8c800, 0x58556e0, 0xc42257e040, 0x600000000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/update.go:43 +0x88
github.com/cockroachdb/cockroach/sql.(*planner).Insert(0xc421a8c800, 0xc4223d4af0, 0x0, 0x0, 0x0, 0x0, 0xc423110cb0, 0x0, 0x4fed020, 0xc4231105d0)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/insert.go:58 +0x9e
github.com/cockroachdb/cockroach/sql.(*planner).newPlan(0xc421a8c800, 0x585f9e0, 0xc4223d4af0, 0x0, 0x0, 0x0, 0x4fec500, 0xc423110cb8, 0x0, 0x585f9e0, ...)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/plan.go:260 +0x16fe
github.com/cockroachdb/cockroach/sql.(*planner).makePlan(0xc421a8c800, 0x585f9e0, 0xc4223d4af0, 0x0, 0x0, 0x0, 0xc421a8f000, 0x0)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/plan.go:212 +0x70
github.com/cockroachdb/cockroach/sql.(*planner).query(0xc421a8c800, 0x51cad50, 0x74, 0xc421fb3978, 0x5, 0x5, 0x0, 0x0, 0x0, 0x0)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/planner.go:215 +0xbd
github.com/cockroachdb/cockroach/sql.(*planner).exec(0xc421a8c800, 0x51cad50, 0x74, 0xc421fb3978, 0x5, 0x5, 0x400fe7b, 0x4fed020, 0xc4231105d0)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/planner.go:243 +0x6d
github.com/cockroachdb/cockroach/sql.InternalExecutor.ExecuteStatementInTransaction(0xc422547400, 0xc42266cdc0, 0x51cad50, 0x74, 0xc421fb3978, 0x5, 0x5, 0xc420037996, 0xc41fec93c3, 0xc4200379a0)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/internal.go:46 +0xb5
github.com/cockroachdb/cockroach/sql.EventLogger.InsertEventRecord(0xc422547400, 0xc42266cdc0, 0x5182983, 0x9, 0x100000001, 0x50a6a40, 0xc4226d8780, 0x0, 0x3fc3333333333333)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/sql/event_log.go:134 +0x395
github.com/cockroachdb/cockroach/server.(*Node).recordJoinEvent.func1.1(0xc42266cdc0, 0x0, 0x1)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/server/node.go:723 +0x126
github.com/cockroachdb/cockroach/internal/client.(*DB).Txn.func1(0xc42266cdc0, 0xc422ea8980, 0x4000000000000000, 0x0)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/internal/client/db.go:450 +0x2f
github.com/cockroachdb/cockroach/internal/client.(*Txn).Exec(0xc42266cdc0, 0xc423110101, 0x0, 0x0, 0xc4231101e0, 0x0, 0x0)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/internal/client/txn.go:553 +0x232
github.com/cockroachdb/cockroach/internal/client.(*DB).Txn(0xc42239b8b0, 0xc422eb5fa0, 0x4000000000000000, 0x0)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/internal/client/db.go:451 +0x28d
github.com/cockroachdb/cockroach/server.(*Node).recordJoinEvent.func1()
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/server/node.go:724 +0x1d9
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc42252c090, 0xc422ea8200)
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/Users/andrei/work/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66
FAIL	github.com/cockroachdb/cockroach/storage	35.184s

**Comment by andreimatei** [comment]
Sorry, I was running old code. Seems fine now.

**Comment by RaduBerinde** [comment]
Yeah I remember hitting that and fixing it in a recent PR.
