### ISSUE TITLE
Hash Sharded Index query with OR or IN clauses read too many buckets 

### ISSUE THREAD

**Issue by alistair-roacher** [cockroachdb/cockroach#83343]
**Describe the problem**

Querying using an quality clause on a column with a hash-sharded index correctly hashes the literal value for the equality condition and only spans the single bucket that would contain the data required, however applying multiple equality clauses (using OR or IN) results in all buckets being scanned for all values which is inefficient:

explain select count(*) from orders where order_date in ('2018-01-01','2019-01-01','2020-01-01');
 
  • group (scalar)
  │ estimated row count: 1
  │
  └── • scan
        estimated row count: 29 (0.29% of the table; stats collected 5 minutes ago)
        table: orders@orders_order_date_idx
        spans: [/0/'2018-01-01' - /0/'2018-01-01'] [/0/'2019-01-01' - /0/'2019-01-01'] [/0/'2020-01-01' - /0/'2020-01-01'] [/1/'2018-01-01' - /1/'2018-01-01'] … (44 more)

Each of the 3 date values supplied will hash to a particular bucket meaning that we only need to examine 3 spans located in a maximum of 3 buckets.

**To Reproduce**

What did you do? Describe in your own words.
Created a blank single node cockroach cluster using v22.1.2 and ran the following:

CREATE TABLE orders (
      order_id UUID NOT NULL DEFAULT gen_random_uuid(),
      order_status INT2 NOT NULL,
      order_date DATE NOT NULL,
      shipped_date DATE NULL,
      CONSTRAINT orders_pkey PRIMARY KEY (order_id ASC),
      INDEX orders_order_date_idx (order_date ASC) USING HASH
  );
insert into orders (order_status, order_date) select 1, '2018-01-01'::DATE+(floor(generate_series/10)||' days')::INTERVAL from generate_series(1, 10000);
analyse orders;

explain select count(*) from orders where order_date in ('2018-01-01','2019-01-01','2020-01-01');
  └── • scan
        estimated row count: 29 (0.29% of the table; stats collected 7 minutes ago)
        table: orders@orders_order_date_idx
        spans: [/0/'2018-01-01' - /0/'2018-01-01'] [/0/'2019-01-01' - /0/'2019-01-01'] [/0/'2020-01-01' - /0/'2020-01-01'] [/1/'2018-01-01' - /1/'2018-01-01'] … (44 more)

**Expected behavior**

We should see only 3 spans (not 48) as we are able to hash the 3 date values in the IN clause to establish which buckets they would be mapped to:

explain select count(*) from orders where order_date in ('2018-01-01','2019-01-01','2020-01-01');
  └── • scan
        estimated row count: 30 (0.30% of the table; stats collected 25 minutes ago)
        table: orders@orders_order_date_idx
        spans: [/8/'2018-01-01' - /8/'2018-01-01'] [/14/'2019-01-01' - /14/'2019-01-01'] [/11/'2020-01-01' - /11/'2020-01-01']

**Additional data / screenshots**
Explaining some similar queries (but by no means all) result in the following advice to add a normal (i.e. not hash-sharded) index on the order_date column:

explain select count(*) from orders where order_date='2019-01-01' or  order_date='2020-01-01';
 ...
  index recommendations: 1
  1. type: index creation
     SQL command: CREATE INDEX ON orders (order_date); 

**Environment:**
 - CockroachDB version: v22.1.2
 - Server OS: Linux/Ubuntu
 - Client app: cockroach sql

**Additional context**
Looking at using hash-sharded indexes to remove hotspots for secondary indexes and want queries using them to be as efficient as possible.

Jira issue: CRDB-17017

**Comment by msirek** [comment]
On an insert to this type of table, `mutationBuilder.addSynthesizedComputedCols` builds the expression tree for the `crdb_internal_order_date_shard_16` computed column.  

This expression looks like:  `(mod(fnv32(crdb_internal.datums_to_bytes(index_col1)), 16:::INT8))`.  

One way to handle this would be to replace predicates such as `index_col1 = 3` with ANDed condition:
    `index_col1 = 3 AND crdb_internal_order_date_shard_16 = (mod(fnv32(crdb_internal.datums_to_bytes(3))`,
and IN preds like `index_col1 IN (2,3)` with :
`(index_col1, crdb_internal_order_date_shard_16) IN 
       ((2, mod(fnv32(crdb_internal.datums_to_bytes(2)))), (3, mod(fnv32(crdb_internal.datums_to_bytes(3)))))`

The same could be done if the predicates involve placeholders instead of constants when using PREPARE and EXECUTE. Joins should be examined too to see if we are missing the implicit equijoin predicates on the hash bucket column when we have something like `t1.index_col1 = t2.col1`.

Perhaps there's a better approach which doesn't involve constructing predicates?

**Comment by msirek** [comment]
This will be fixed by https://github.com/cockroachdb/cockroach/pull/100242
