### ISSUE TITLE
sql: add caching for system privileges

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#83381]
Like for normal privileges, we should add a cache for system privileges.

Jira issue: CRDB-17037
Epic CRDB-11725

**Comment by rafiss** [comment]
For now, none of the usages of system.privileges are in the critical performance path, so we have a little time before this becomes a strict requirement.

**Comment by rafiss** [comment]
closed by https://github.com/cockroachdb/cockroach/pull/83604
