### ISSUE TITLE
sql: support grant options for system (synthetic) privileges

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#83380]
Right now grant options are hard coded to be 0 for system privileges.

Example: support `GRANT SYSTEM MODIFYCLUSTER SETTING TO foo WITH GRANT OPTION`

Jira issue: CRDB-17036
Epic CRDB-11725

**Comment by rafiss** [comment]
closed by https://github.com/cockroachdb/cockroach/pull/84391
