### ISSUE TITLE
sql: add logic tests for system privileges using new testserver logictest upgrade commands

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#83382]
See: https://github.com/cockroachdb/cockroach/pull/83296

Jira issue: CRDB-17038

Epic CRDB-14557

**Comment by rafiss** [comment]
I'll close this, since v22.2 (and system privileges) have been out a while. We're adding other logic tests for new v23.1 changes, such as: https://github.com/cockroachdb/cockroach/pull/96031
