### ISSUE TITLE
streaming: develop self-service demo script

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/cockroach#83426]
We’d like more people to be able to demonstrate (acceptance test) tenant streaming on their own. Let’s develop instructions to allow people to do so -- likely a combination of prose and code.

The target audience is PMs, CEAs, etc, i.e. not devs. The deliverable is a document (Confluence, GDocs, markdown, whatever).

The outline would be something like:

- roachprod instructions
  - start source cluster
  - start workload on source
  - start destination
- SQL commands to start the replication
  - cluster settings if any
- How to observe that it’s working
  - @gh-casper mentions that we can observe the console UI on the destination
  - Maybe we can show the correctness work?
  - Arguably, try some interruptions: stop & start jobs for example
- Cutover

Jira issue: CRDB-17065
Epic CRDB-14841

**Comment by shermanCRL** [comment]
To be clear, the requirement here is not that “everything is working”, it’s “anyone can demonstrate the current status for themselves”.

**Comment by samiskin** [comment]
Completed by https://cockroachlabs.atlassian.net/wiki/spaces/STRM/pages/2664923723/Roachprod+Demo+Tutorial
