### ISSUE TITLE
sql,upgrades: ensure new version does not think any descriptors are invalid as a precondition

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#83432]
**Is your feature request related to a problem? Please describe.**

We've had a couple of issues due to stricter validation in 22.1 (https://github.com/cockroachdb/cockroach/issues/82499, https://github.com/cockroachdb/cockroach/issues/82576). It's a bummer for customers when they cannot roll back to the previous version because we've finalized the new version. 

**Describe the solution you'd like**

The upgrades package offers the notion of a precondition. We should set as a standing precondition, or something like that, to ensure that the newer version's validation won't consider existing descriptors as invalid when finalizing. This can prevent cases where clusters are stuck with invalid descriptors and cannot rollback.

Jira issue: CRDB-17068

**Comment by ajwerner** [comment]
Maybe one day we'd have a standing pre-condition. As a first step we should just associate with the `Start_XXX` version a pre-condition which does `SELECT * FROM crdb_internal.invalid_objects`.

**Comment by Xiang-Gu** [comment]
I tried to write down my first descriptor repair query yesterday for https://github.com/cockroachdb/cockroach/issues/82499  and it was fun. Can I take this issue instead? I'll work on it today!

**Comment by postamar** [comment]
Sure!
