### ISSUE TITLE
opt: improve query plans on tables with ascending keys

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#83431]
This ascending query problem is a common problem for database optimizers. The problem is that the optimizer assumes that a columns has zero or very few values outside of the maximum (and minimum) values in the collected histograms. If newly inserted values are ever-increasing, then the optimizer can wildly underestimate the rows that match filters for the latest values, leading to query plans with very poor performance. 

A detailed description of the problem can be found at https://github.com/cockroachdb/cockroach/issues/64570#issuecomment-884362488.

Jira issue: CRDB-17067

CRDB-13963

**Comment by rytaft** [comment]
Is this a duplicate of https://github.com/cockroachdb/cockroach/issues/79872?

**Comment by mgartner** [comment]
Yes, closing.
