### ISSUE TITLE
sql: bad version-gating of new hash-sharded behaviour

### ISSUE THREAD

**Issue by postamar** [cockroachdb/cockroach#83447]
**Describe the problem**

Although we have been careful to version-gate the hash-sharding implementation in 22.1, it appears there's still at least one mixed-version cluster bug.

**To Reproduce**

```
$ roachprod create $CLUSTER -n 3
$ roachprod stage $CLUSTER release v21.2.10
$ roachprod sql $CLUSTER:1
```
At which point we disable auto-upgrades:
```
root@localhost:26257/defaultdb> SET CLUSTER SETTING cluster.preserve_downgrade_option = '21.2';
```
Now lets replace all the binaries:
```
$ roachprod stage $CLUSTER release v22.1.2
$ roachprod stop $CLUSTER:3
$ roachprod start $CLUSTER:3
$ roachprod stop $CLUSTER:2
$ roachprod start $CLUSTER:2
$ roachprod stop $CLUSTER:1
$ roachprod start $CLUSTER:1
```
I checked that the cluster version was still 21.2 and tried to create a hash-sharded index:
```
$ roachprod sql $CLUSTER:1
root@localhost:26257/defaultdb> SHOW CLUSTER SETTINGS;
...
  version                                                                   | 21.2                                                               | m            | set the active cluster version in the format '<major>.<minor>'
(206 rows)


Time: 11ms total (execution 3ms / network 8ms)

root@localhost:26257/defaultdb> CREATE TABLE kv (k INT PRIMARY KEY, v STRING);                 
CREATE TABLE


Time: 11ms total (execution 11ms / network 0ms)

root@localhost:26257/defaultdb> ALTER TABLE kv ALTER PRIMARY KEY USING COLUMNS (k) USING HASH WITH BUCKET_COUNT = 8;
ERROR: relation "kv" (52): primary index column "crdb_internal_k_shard_8" cannot be virtual
```

**Expected behavior**
The ALTER PRIMARY KEY statement should not fail with a validation error. (edited)

Jira issue: CRDB-17074

**Comment by chengxiong-ruan** [comment]
should we close this since we disallow the creation of hash sharded index in mixed version version cluster on purpose and the customer was happy with creating it after finalizing the cluster upgrade?

**Comment by postamar** [comment]
I don't know, I don't think the behaviour I described in the repro is reasonable.
