### ISSUE TITLE
kvserver: add version of admission/follower-overload for IMPORT

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#83485]
The roachtest introduced in https://github.com/cockroachdb/cockroach/issues/81834 with slight modifications should lend itself to experiments relating to AddSST leader and follower overload. AddSST is very challenging traffic to handle due to the large size of each entry as well as it hitting various below-raft throttling mechanisms. That newly added test can provide a good testbed for vetting solutions such as https://github.com/cockroachdb/cockroach/issues/79215#issuecomment-1168031561 or removing existing below-raft throttling (https://github.com/cockroachdb/cockroach/issues/75066)

Jira issue: CRDB-17093

**Comment by sumeerbhola** [comment]
We have replication admission control working for all elastic traffic.
