### ISSUE TITLE
roachtest/sqlsmith: cannot resolve types in DistSQL by name with fakedist config

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#83496]
```
# LogicTest: 5node

statement ok
CREATE TABLE t (c STRING);
INSERT INTO t VALUES ('v');
ALTER TABLE t EXPERIMENTAL_RELOCATE VALUES (ARRAY[2], 1);
CREATE TYPE typ AS ENUM ('foo', 'bar');

statement ok
SELECT * FROM t
WHERE (
  (SELECT 'bar':::typ FROM t WHERE false)
  IS NOT DISTINCT FROM CASE WHEN NULL THEN NULL ELSE NULL END
)
```

Jira issue: CRDB-17103

**Comment by mgartner** [comment]
Reduced reproduction that fails with the `fakedist-vec-off` logictest configuration:

```
statement ok
CREATE TABLE t (
  a STRING,
  b STRING
);

statement ok
CREATE TYPE typ AS ENUM ('foo', 'bar');

statement ok
SELECT * FROM t
WHERE (
  (SELECT 'bar':::typ FROM t WHERE false)
  IS NOT DISTINCT FROM CASE WHEN NULL THEN NULL ELSE NULL END
)
```

**Comment by yuzefovich** [comment]
The problem here is that `CASE WHEN NULL THEN NULL ELSE NULL END` is serialized as `CAST(NULL AS anyenum)` to be sent across the wire, and then on the remote node we refuse to resolve `anyenum` type.

I think there are two questions to answer:
- should `anyenum` type be considered a user-defined type? It has a fixed `oid.T_anyenum` == 3500, so we treat it as not a UDT. Not sure whether this was by design.
- should we allow the resolution of `anyenum` type by DistSQL? I believe so, and the corresponding diff does fix the problem
```
diff --git a/pkg/sql/catalog/descs/dist_sql_type_resolver.go b/pkg/sql/catalog/descs/dist_sql_type_resolver.go
index 2b3a6fe74d..19a552627f 100644
--- a/pkg/sql/catalog/descs/dist_sql_type_resolver.go
+++ b/pkg/sql/catalog/descs/dist_sql_type_resolver.go
@@ -42,8 +42,11 @@ func NewDistSQLTypeResolver(descs *Collection, txn *kv.Txn) DistSQLTypeResolver
 
 // ResolveType implements the tree.TypeReferenceResolver interface.
 func (dt *DistSQLTypeResolver) ResolveType(
-       context.Context, *tree.UnresolvedObjectName,
+       ctx context.Context, name *tree.UnresolvedObjectName,
 ) (*types.T, error) {
+       if name.Object() == "anyenum" {
+               return types.AnyEnum, nil
+       }
        return nil, errors.AssertionFailedf("cannot resolve types in DistSQL by name")
 }
```
The reproduction from [Marcus](https://github.com/cockroachdb/cockroach/issues/83496#issuecomment-1176855906) works on any `fakedist` config (with some non-determinism).

Overall, this seems like SQL Schema issue the most, so I'm putting this on the corresponding board.

**Comment by postamar** [comment]
I don't think anyone on the schema team has any opinions about `anyenum`, indeed this is the first time I'm made aware of it (that's not saying much, but still).

I'm happy to accept this patch as-is, it LGTM. I suppose there does remain the open question on what to do about `anyenum` in other type resolver implementations. @ajwerner do you have opinions?

**Comment by ajwerner** [comment]
Does this exclusively impact the `fakedist` config? I don't feel that I have a deep enough understanding of what's at risk here. I also don't have a strong enough understanding of the expectation of behaviors surrounding uses of anyenum.

**Comment by yuzefovich** [comment]
> Does this exclusively impact the `fakedist` config?

No, this also reproduces the issue:
```
# LogicTest: 5node

statement ok
CREATE TABLE t (c STRING);
INSERT INTO t VALUES ('v');
ALTER TABLE t EXPERIMENTAL_RELOCATE VALUES (ARRAY[2], 1);
CREATE TYPE typ AS ENUM ('foo', 'bar');

statement ok
SELECT * FROM t
WHERE (
  (SELECT 'bar':::typ FROM t WHERE false)
  IS NOT DISTINCT FROM CASE WHEN NULL THEN NULL ELSE NULL END
)
```

**Comment by ajwerner** [comment]
We're going to move this to @cockroachdb/sql-queries because it relates to serialization of expressions for distsql.

**Comment by yuzefovich** [comment]
#90867 from @mgartner is a related exploration.

**Comment by rafiss** [comment]
Is this still relevant?

**Comment by yuzefovich** [comment]
Yes, it hasn't been fixed (I updated the issue description with a reliable repro).

**Comment by rafiss** [comment]
Thanks, I removed `release-22.1` from the title, since that's what prompted me to ask.
