### ISSUE TITLE
Options associated with roles not being applied to user privileges

### ISSUE THREAD

**Issue by pxlogan** [cockroachdb/cockroach#83513]
When I create a role with certain options and then grant the role to a user, the user is not inheriting the options.

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

CREATE ROLE viewer WITH NOCANCELQUERY NOCONTROLCHANGEFEED NOCONTROLJOB NOCREATEDB NOCREATELOGIN NOCREATEROLE LOGIN NOMODIFYCLUSTERSETTING NOSQLLOGIN VIEWACTIVITY VIEWACTIVITYREDACTED;
CREATE USER IF NOT EXISTS dashboardviewer WITH PASSWORD 'xxxxxxxxxx';
GRANT viewer TO dashboardviewer;

Try to connect to the SQL CLI using the user dashboardviewer should fail it does not.

CREATE USER IF NOT EXISTS dashboardviewer WITH PASSWORD 'xxxxxxxxxx' nosqllogin;

Try to connect to the SQL CLI useing dashboardviewer and it will fail.

**Expected behavior**
The user should inherit the options granted on the role and therefore in this example the user should not be allowed to login to the SQL CLI.

**Environment:**
 - CockroachDB version 21.2 & 22.1 
 - Server OS: Linux
 - Client app cockroach sql

**Additional context**
What was the impact?

Potential Security breach

Jira issue: CRDB-17116

**Comment by rafiss** [comment]
I'll close this as per the above. If there's a feature request to add or change anything, please contact the Product team (@abhinavg6 or @vy-ton).
