### ISSUE TITLE
kvserver: load based splitting should be on a more granular metric

### ISSUE THREAD

**Issue by kvoli** [cockroachdb/cockroach#83519]
Currently we load based split when the number of requests (requests in all batch requests) exceeds the qps split threshold (default 2500). 

Requests are not uniform however and may be orders of magnitude more expensive than each other e.g. scan of 3k rows vs point read. 

We should split on a more [granular metric than requests per second](https://github.com/cockroachdb/cockroach/blob/443c4d51b9f64067161d9c5510206bcd8408c1b4/pkg/kv/kvserver/split/decider.go#L80-L81). Such as the number of bytes read + written to a range per second. 

The threshold should also be adjusted with testing to a new suitable default.

One alternative is to use the number of key accesses as opposed to the number of bytes. This method would not account for large values being read or written, however would set each access at a fixed cost.

Jira issue: CRDB-17122

Epic CRDB-18661

**Comment by tbg** [comment]
See also https://github.com/cockroachdb/cockroach/issues/55116 for forcing a load-based split manually.

**Comment by erikgrinaker** [comment]
Related to #69364, possibly dupe?
