### ISSUE TITLE
backupccl: add roachtests that cancel/revert backup, restore and import

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#83524]
In our bid to add more roachtest coverage we should add tests that stress the cancel and revert behavior of all bulk operations. This will help us find correctness and performance regressions in the `OnFailOrCancel` method of bulk jobs.

Jira issue: CRDB-17125

**Comment by msbutler** [comment]
We have added signifantly more import rollback coverage. I am unsure what backup and restore rollback coverage a roachtest would provide. closing this for now.
