### ISSUE TITLE
backupccl,importccl: run backup, restore and import roachtests on AWS

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#83534]
Backup, import and restore all support reading and writing to S3. Today, we run most of our nightly roachtests exclusively on GCS. This means that we are blind to any serious regressions, or changes of behavior in the AWS SDK that we might have picked up in a vendor bump. We should refactor as many bulk roachtests as we can to also run on S3.

Epic CRDB-15064

Jira issue: CRDB-17130

**Comment by msbutler** [comment]
Nearly all restore tests run on aws. #99787 will create backup tests on aws . Import is no longer our problem.
