### ISSUE TITLE
changefeedccl: Add smither test for CDC expressions

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#83591]
Teach sql smither (or just write smither based test) to verify CDC expressions.

https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/195395621/SQLsmith

Jira issue: CRDB-17159

Epic CRDB-17161

**Comment by miretskiy** [comment]
I think this is done?

**Comment by amruss** [comment]
@HonoreDB can we close this?

**Comment by HonoreDB** [comment]
Hope to do some followups during stability but I can open new issues for those.
