### ISSUE TITLE
changefeedccl: make alter changefeed tests run on random enterprise sink

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#83607]
Currently alter changefeed tests force the kafka sink because tests on cloudstorage (and maybe others) hang. We don't know why, it's probably an issue with the test framework, we hope. Figure out why and fix it--the only sink that shouldn't work with alter changefeed is sinkless.

Jira issue: CRDB-17169

Epic CRDB-14988

**Comment by miretskiy** [comment]
believe this was done.
