### ISSUE TITLE
schemachanger: parallelize cumulative tests

### ISSUE THREAD

**Issue by postamar** [cockroachdb/cockroach#83603]
`sctest.Rollback` and other so-called cumulative tests currently execute all subtests sequentially. Have them run concurrently instead. This issue is motivated by these tests hitting timeout limits and generally being long.

Jira issue: CRDB-17168

**Comment by ajwerner** [comment]
We're waiting on https://github.com/cockroachdb/cockroach/pull/84221 to move on this to see if there are any good learnings there.
