### ISSUE TITLE
roachprod: set up default grafana dashboard in `grafana-start`

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#83663]
When a roachprod user runs `grafana-start`, regardless of whether they pass a `grafana-config`, a user should be able to see a default dashboard, perhaps with the following [pages](https://github.com/cockroachdb/cockroach/tree/master/monitoring/grafana-dashboards). 

Jira issue: CRDB-17197

**Comment by SooryR** [comment]
If no one else has taken this issue, then can I take it?

**Comment by girishv-tw** [comment]
Hi @msbutler , 
I was wondering on picking up this issue. However, im not able to access the JIRA issue. Could you provide me access for the same ?

**Comment by msbutler** [comment]
hi @girishv-tw, we've realized this isn't a great community issue as it requires a lot of infra setup. Removing the `good first issue` tag. Apologies, and I'm sure there are plenty of other issues to tackle!

**Comment by girishv-tw** [comment]
@msbutler  , thanks for pointing that out. Eitherways ,is it still possible to provide access to the JIRA board since the other issues have links to them as well. Is there a form i should be filling for getting the access or something ? i was not able to find it in the documentation anywhere.
