### ISSUE TITLE
When adding a password to a user if you dont use quote marks it still works

### ISSUE THREAD

**Issue by pxlogan** [cockroachdb/cockroach#83699]
When creating a user with a password, if you do not encapsulate the password in quote marks the password will be creaed but it appears to be created in all lower case

Please describe the issue you observed, and any steps we can take to reproduce it:

Create user with a password but do not user quote marks
```
root@:26257/defaultdb> create user pl_test with password TestIng;
CREATE ROLE
```
When I login as that user I get an error despite using the correct password

```
paul@paul-VirtualBox:~$ cockroach sql --url "postgresql://kinga:TestIng@localhost:26257?sslmode=verify-full&sslrootcert=$HOME/certs/ca.crt"
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
ERROR: password authentication failed for user kinga
Failed running "sql"
```
If I try to login with the password all in lower case I am successful
```
paul@paul-VirtualBox:~$ cockroach sql --url "postgresql://kinga:testing@localhost:26257?sslmode=verify-full&sslrootcert=$HOME/certs/ca.crt"
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
# Server version: CockroachDB CCL v21.1.7 (x86_64-unknown-linux-gnu, built 2021/08/09 17:55:28, go1.15.14) (same version as client)
# Cluster ID: 04fb8b2a-3622-434b-88b6-284e6f0c57ba
No entry for terminal type "xterm-256color";
using dumb terminal settings.
#
# Enter \? for a brief introduction.
#
kinga@localhost:26257/defaultdb> 
```

**Expected behavior**
Without quote marks the command should fail I believe with a syntax error as quotes are needed.
Alternatively the password is created correctly

**Environment:**
 - CockroachDB version 21.1 and above
 - Server OS: Linux
 - Client app cockroach sql

**Additional context**
User is unable to login into the cluster and must have their password reset by an admin (who hopefully uses quote marks the next time)

Jira issue: CRDB-17216
Epic CRDB-14049

**Comment by rafiss** [comment]
Debugging notes: in Postgres, single-quotes are required when setting the password. For example:
```
postgres=# create user pl_test with password TestIng;
ERROR:  syntax error at or near "TestIng"
LINE 1: create user pl_test with password TestIng;
```

But this works:
```
postgres=# create user pl_test with password 'TestIng';
CREATE ROLE
```
