### ISSUE TITLE
streamingccl: consider replacing lib/pq with pgx in stream paritition client

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#83695]
We've replaced `lib/pq` with `jackc/pgx` in the CLI and increasingly use it in tests where we need careful control over connections.  The `pgx` library is more actively maintained, more feature-ful, and higher performance (citation needed).  

Once we have benchmarks in place, we should evaluate the impact of switching to pgx, either via the database/sql interface or its native interface.

Jira issue: CRDB-17213

**Comment by shermanCRL** [comment]
Should this be closed by https://github.com/cockroachdb/cockroach/pull/84394 ?

**Comment by gh-casper** [comment]
Yes, closing this.
