### ISSUE TITLE
storage: add metrics for command re-proposals

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#8375]
From a comment by @bdarnell on #8346:

> I think the thing to do would be to make metrics for reproposal events so we can monitor the percentage of proposals that get retried in real-world scenarios. We might also want to add a per-command counter so we can see if the same commands are getting reproposed multiple times.

**Comment by petermattis** [comment]
@bdarnell @nvanbenschoten this would have been helpful recently.

**Comment by tschottdorf** [comment]
@nvanbenschoten you would also enjoy this metric based on our recent spat around reproposals, correct?

**Comment by tschottdorf** [comment]
> it would also be a good metric to base problem range determinations on.

This won't work with just a counter, we'd need to keep a window too. But I agree with your implicit point that if some range contributes to a cluster-wide metric, we ought to be able to look up the individual range's contributions, and ideally even be able to obtain the worst offenders.

Perhaps the problem ranges page could get a "worst offenders" section where we list the top-k for several metrics: ranges with the highest qps (max over replicas), ranges with the largest mvccstats, ranges with highest rate of reproposals, etc.
