### ISSUE TITLE
add index recommendation to the UI

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#83783]
Add the information collected based on this [issue](https://github.com/cockroachdb/cockroach/issues/83782),  to the Statement Details page, under the Explain Plan (since the recommendation is based on the plan).
Also add a column to the Statement Overview, to indicate there is a recommendation, similar to the Database page

Jira issue: CRDB-17262

**Comment by maryliag** [comment]
@Annebirzin  do we have a design for it?

**Comment by Annebirzin** [comment]
@maryliag @kevin-v-ngo I don't think we have designs for this. 

From my understanding, this would be adding a column to the 'Index Stats' table on [the Explain Plan tab of the Statement Fingerprint page](https://www.figma.com/file/xdmwvnFQd6KkO9RJ0XLDH0/22.1_SQL-obsrv_query-performance?node-id=3488%3A22100) for 'Index recommendations'? Very similar to what we have on the [Table Details page](https://www.figma.com/file/xdmwvnFQd6KkO9RJ0XLDH0/22.1_SQL-obsrv_query-performance?node-id=5478%3A153227)? (screenshots below)

![Screen Shot 2022-07-05 at 10 41 21 AM](https://user-images.githubusercontent.com/51920721/177354279-30e52281-4b50-4522-b78e-8dcc9c76fe3c.png)

![Screen Shot 2022-07-05 at 10 43 10 AM](https://user-images.githubusercontent.com/51920721/177354907-de563f4f-00ff-4306-bcd1-5a42f93ad4dc.png)

**Comment by maryliag** [comment]
That looks awesome! Thanks @Annebirzin !

**Comment by Annebirzin** [comment]
np! fyi making some tweaks to the designs based on @kevin-v-ngo 's feedback in Figma [here](https://www.figma.com/file/xpnRkP9cLXERVceRC4cec4/22.2_SQL-obsrv_query-performance?node-id=1397%3A83240)
