### ISSUE TITLE
kv: large UPSERT batches may cause hotspots because of the way we anchor transaction records

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#83788]
Discovered this while running a slightly modified version of kv0 with batch size 500. Specifically, two columns `updated_at` and `created_at` were added to the `kv` table and there were secondary indexes on both these columns. This is important because with these changes the optimizer plans a lookup join for any `UPSERT` statement. 

By default, kv0 `UPSERTs` uniform keys. However, when the join reader constructs a batch request to send to KV, it does so for sorted spans. The motivation for this is described here:
https://github.com/cockroachdb/cockroach/blob/e461d154dfd39084d87e859154918de353ab42d0/pkg/sql/rowexec/joinreader.go#L934-L938

Given we're performing an `UPSERT`, the join looks up rows in a locking fashion, which means we must create a transaction record in this batch. We pick the first key that is locked by the batch as the key on which to anchor the transaction record. Now if the batch size of the `UPSERT` is proportional to the number of ranges that belong to the table, it is quite likely that we will always anchor the transaction record on a single range. As a consequence of this, a single range's leaseholder will be responsible for driving async intent cleanup for all transactions. This is exactly what we saw when running the workload. 

The node on which the leaseholder of this "golden range" resided could be correlated with extremely high CPU. As the leasholder moved from one node to another, so did the CPU hotspot. Check out the graphs below:

<img width="822" alt="Screen Shot 2022-06-29 at 4 04 42 PM" src="https://user-images.githubusercontent.com/6366031/177219605-6faea3e5-75c6-4f8d-9713-e28263510503.png">

<img width="837" alt="Screen Shot 2022-06-29 at 4 03 26 PM" src="https://user-images.githubusercontent.com/6366031/177219621-e046fcb1-7e6a-4a25-aa29-b7a3cc554fbc.png">

It's worth adding that the intents themselves were uniformly distributed across ranges as you'd expect. 

One potential proposal here would be to pick the key on which to anchor transaction records uniformly from the set of locking keys in a batch. This is as opposed to the [first locking key in the batch](https://github.com/cockroachdb/cockroach/blob/66b513c6e871e2d394aee7b0e4abf536f44e6697/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go#L175-L184) like we do today. I'm not sure what, if anything, could break if we start doing this however.

@ajwerner and I were poking at a cluster when we discovered this and he had a few other suggestions that he might want to capture here as well.

cc @cockroachdb/kv 

Jira issue: CRDB-17265

**Comment by ajwerner** [comment]
Randomizing the anchor key would help in this case, and is easy, so I'm interested in it as a solution.

A more general solution, I think, would be to model intent resolution in the load-based splitting structure such that we would have split the first range to balance the load due to the extra work to resolve the intents.

**Comment by nvanbenschoten** [comment]
I agree with randomizing the anchor key selection from the set of locking keys in the batch. It gives up some predictability, which may be noticeable if some leaseholders are closer than others, but it's probably the right solution until we get smarter about recognizing such asymmetry and deliberately anchoring txn records on nearby leaseholders.

**Comment by ajwerner** [comment]
Seems still relevant.
