### ISSUE TITLE
memory usage too high

### ISSUE THREAD

**Issue by carr123** [cockroachdb/cockroach#83798]
**Describe the problem**
when i start cockroachdb , it costs memory about 4%, after few hours, it costs 19% memory,  while there's very light workload.

Please describe the issue you observed, and any steps we can take to reproduce it:
install V22.1.2  on ubuntu18.04.  8GB total RAM

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
2. Send SQL ... / CLI command ...
3. Look at UI / log file / client app ...

**Expected behavior**

i expect cockroachdb costs less memory while there isn't much SQL workload.

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version v22.1.2
 - Server OS: ubuntu18.04]
 - Client app [`cockroach sql]

**Additional context**
What was the impact?

Jira issue: CRDB-17272

**Comment by yuzefovich** [comment]
@carr123 could you please provide more details about the workload? Like what is the number of ranges in the cluster? What are the QPS numbers, reads/writes split, etc.
