### ISSUE TITLE
streamingccl: make MVCC bulk operations well-tested

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/cockroach#83810]
Jira issue: CRDB-17277

**Comment by gh-casper** [comment]
Even though we now have test coverage in some unit tests and random stream client that generates SSTs and DelRanges, we still need to test bulk ops in roachtests and long-lived manual testing.
https://github.com/cockroachdb/cockroach/issues/76947
https://github.com/cockroachdb/cockroach/issues/83315
