### ISSUE TITLE
Insights: Drop unused index + Schema tab 

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#83829]
This issue tracks surfacing a Drop Unused Index insight on the Insights page including the Schema tab. 

Related [issue](https://github.com/cockroachdb/cockroach/issues/83828)
[Link to figma
](https://www.figma.com/file/xpnRkP9cLXERVceRC4cec4/22.2_SQL-obsrv_query-performance?node-id=301%3A3805)
FYI @Annebirzin 

Jira issue: CRDB-17287

**Comment by maryliag** [comment]
@THardy98 can this be closed?
