### ISSUE TITLE
admission: roachtest-ify index/column backfills impacting foreground traffic

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#83826]
**Is your feature request related to a problem? Please describe.**

In https://github.com/cockroachdb/cockroach/issues/82700 we have a manual reproduction for column backfills resulting in diskbandwidth starvation, and severely impacting tail latencies. This issue tracks roachtest-ifying the reproduction, possibly after evaluating fixes through admission control: https://github.com/cockroachdb/cockroach/issues/82898.

Jira issue: CRDB-17285

Epic CRDB-25348

**Comment by andrewbaptist** [comment]
Some data from the last run

[compaction_profile.pb.gz](https://github.com/cockroachdb/cockroach/files/9824698/compaction_profile.pb.gz)

**Comment by irfansharif** [comment]
This was done in https://github.com/cockroachdb/cockroach/pull/103757.
