### ISSUE TITLE
SHOW RANGES errors out for a Serverless cluster

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#83839]
**Describe the problem**

Currently, `SHOW RANGES` throws an error when that statement is run in a Serverless cluster 

**To Reproduce**

1. Connect to a Serverless cluster as an admin user
2. In your SQL shell, run a statement like `SHOW RANGES FROM TABLE users2;`
3. Notice the output is an error that looks like `ERROR: RangeIterator failed to seek to /Meta2/"\x00": rpc error: code = Unauthenticated desc = requested key /Meta2/"\x00" not fully contained in tenant keyspace /Tenant/23{8-9}`

Similar issue occurs for the `SHOW RANGES FOR ROW` statement

**Expected behavior**
Ideally, a SQL user can run `SHOW RANGES` or `SHOW RANGES FOR ROW` in a Serverless cluster and not hit an error.

**Environment:**
 - CockroachDB version 21.2.12

Jira issue: CRDB-17295

Epic CRDB-14522

**Comment by ajwerner** [comment]
Part of this should be easy, part of it will be less easy. One thing here is the need to replace the existing meta scan with a `RangeIterator`. I was looking at this Friday as part of some other things. That looks like the below patch. The other challenge is getting node descriptors which contain region information https://github.com/cockroachdb/cockroach/blob/44884454824c5892cacaa83cbfd4bb75edc4c258/pkg/sql/crdb_internal.go#L3348-L3351. 

It's no obvious to me at all that we want to expose individual node placement information to the end user. 

```
diff --git a/pkg/sql/crdb_internal.go b/pkg/sql/crdb_internal.go
index 4b62d98e72..b0f651fa6b 100644
--- a/pkg/sql/crdb_internal.go
+++ b/pkg/sql/crdb_internal.go
@@ -31,7 +31,6 @@ import (
 	"github.com/cockroachdb/cockroach/pkg/jobs/jobspb"
 	"github.com/cockroachdb/cockroach/pkg/keys"
 	"github.com/cockroachdb/cockroach/pkg/kv"
-	"github.com/cockroachdb/cockroach/pkg/kv/kvclient"
 	"github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord"
 	"github.com/cockroachdb/cockroach/pkg/kv/kvserver/concurrency/lock"
 	"github.com/cockroachdb/cockroach/pkg/kv/kvserver/liveness/livenesspb"
@@ -3344,13 +3343,6 @@ CREATE TABLE crdb_internal.ranges_no_leases (
 		if !hasPermission {
 			return nil, nil, pgerror.Newf(pgcode.InsufficientPrivilege, "only users with the ZONECONFIG privilege or the admin role can read crdb_internal.ranges_no_leases")
 		}
-		ranges, err := kvclient.ScanMetaKVs(ctx, p.txn, roachpb.Span{
-			Key:    keys.MinKey,
-			EndKey: keys.MaxKey,
-		})
-		if err != nil {
-			return nil, nil, err
-		}
 
 		// Map node descriptors to localities
 		descriptors, err := getAllNodeDescriptors(p)
@@ -3362,21 +3354,18 @@ CREATE TABLE crdb_internal.ranges_no_leases (
 			nodeIDToLocality[desc.NodeID] = desc.Locality
 		}
 
-		var desc roachpb.RangeDescriptor
-
-		i := 0
-
+		ri := kvcoord.MakeRangeIterator(p.execCfg.DistSender)
+		ri.Seek(ctx, roachpb.RKey{}, kvcoord.Ascending)
+		if err := ri.Error(); err != nil {
+			return nil, nil, err
+		}
 		return func() (tree.Datums, error) {
-			if i >= len(ranges) {
-				return nil, nil
+			defer ri.Next(ctx)
+			if !ri.Valid() {
+				return nil, ri.Error()
 			}
 
-			r := ranges[i]
-			i++
-
-			if err := r.ValueProto(&desc); err != nil {
-				return nil, err
-			}
+			desc := ri.Desc()
 
 			votersAndNonVoters := append([]roachpb.ReplicaDescriptor(nil),
 				desc.Replicas().VoterAndNonVoterDescriptors()...)

```

**Comment by koorosh** [comment]
> The other challenge is getting node descriptors which contain region information
@ajwerner , can you help me to understand a bit more on what else except your patch has to be done to resolve this issue?
As I see, it is already retrieves nodes locality https://github.com/cockroachdb/cockroach/blob/30c7e9c5f045db0a4fe2fdf05d54d631c3a7539f/pkg/sql/crdb_internal.go#L3478-L3485

**Comment by koorosh** [comment]
Direct usage of `RangeIterator` affects logic and tests (`TestLogic_hash_sharded_index*` [related](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/6521335?showRootCauses=true&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true&logFilter=debug) ) that rely on `crdb_internal.ranges_no_leases` table (despite the fact that table returns the same result when it's queried directly from cli).

I'd appreciate any help here to explore other options (if necessary) to resolve this issue. (cc @ajwerner ).

**Comment by thtruo** [comment]
Hey @aayushshah15! I heard that you were planning to work on supporting SHOW RANGES for Serverless in the November milestone. Is there a tracking issue for that, or shall we assign this issue to you? We originally had this punted on KV Obs' backlog, but if you were going to work on it, let's update the ownership here :)
