### ISSUE TITLE
cdc: fix encoder for changefeed expressions

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#83835]
Right now we send only the id when a message is deleted. With changefeed expressions, you may want to see the deleted messages (for example - when archiving data you may only want  TTL'd data to be sent through the changefeed, but you need the full value). We should add support for this. It seems this is an encoder issue.

Jira issue: CRDB-17292

Epic CRDB-21713

**Comment by miretskiy** [comment]
Isn't it a diff option?

**Comment by miretskiy** [comment]
@amruss @HonoreDB -- ping.  I think this is simply a matter of emitting cdc_prev (i.e. having diff option)
Is this not the case?  I'm inclined to close this issue

**Comment by miretskiy** [comment]
I see... silly json encoder.

**Comment by miretskiy** [comment]
I'm pretty sure this is supported by CDC queries `WITH diff, envelope=row`
