### ISSUE TITLE
kv-obs: annotate consistency queue graph with explanation

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#83869]
Extracted from https://github.com/cockroachdb/cockroach/issues/67004.

We should annotate the consistency queue graph with a hint that explains what the role of the queue is and that a persistent pending backlog is expected and benign. Something like the following:

> The Consistency Checker Queue periodically checks that all replicas in a given range are consistent. For large clusters, the queue is always expected to have a pending backlog.

Jira issue: CRDB-17322

Epic CRDB-32130

**Comment by kyle-a-wong** [comment]
https://github.com/cockroachdb/cockroach/pull/126759 Has been merged to address this issue.
