### ISSUE TITLE
`cockroach version` panic in schema change

### ISSUE THREAD

**Issue by davepacheco** [cockroachdb/cockroach#83864]
(originally filed as #83706, moving here as requested)

**Describe the problem**

While trying to reproduce #82958, I found a case where `cockroach version` exited with status 2.  Thinking maybe it would be reproducible, I started running that in a loop. I saw this panic:

```
panic: invalid predicate with signature *fmt.pp != func(*scpb.Column, scplan.Params) bool for *scpb.Column[0]

goroutine 1 [running]:
github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scplan.buildSchemaChangeOpGenFunc(0x703b2a0, 0x0, 0xc000e0aff0, 0xc000e0b050, 0xc000e08c18)
	/ws/gc/cockroach/cache/gopath/src/github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scplan/declarative.go:171 +0xd93
github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scplan.buildSchemaChangePlanner(0xc000e0ab40, 0xc000e0ab40)
	/ws/gc/cockroach/cache/gopath/src/github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scplan/declarative.go:60 +0x125
github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scplan.init()
	/ws/gc/cockroach/cache/gopath/src/github.co
```

**To Reproduce**

Just run `cockroach version` in a loop unti it exits.  At first, I just did:

```
for ((i = 0; ; i++)) { echo "ATTEMPT $i"; cockroach version || break; }
```

Now I'm using this:

```
#!/bin/bash

# attempt to reproduce failure from `cockroach version`

# specifies a specific `cockroach` binary
export PATH="$HOME/tools/cockroachdb-v21.2.9/bin:$PATH"

date +%FT%TZ > start_time
which cockroach > which_cockroach

for ((i = 0; ; i++)) {
	echo "ATTEMPT $i"
	echo $i > attempt_number
	cockroach version > stdout 2>stderr
	rv=$?
	if [[ $rv -ne 0 ]]; then
		echo $rv > exit_status
		echo "exited with status $rv";
		break;
	fi
}
```

Unfortunately I lost the status code but I've fixed the above script to avoid that.

It took just over 53h and 1.4M iterations to hit this.

**Expected behavior**

This should run indefinitely without issue.

**Environment:**

```
$ cockroach version
Build Tag:        v21.2.9
Build Time:       2022/04/28 04:02:42
Distribution:     OSS
Platform:         illumos amd64 (x86_64-pc-solaris2.11)
Go Version:       go1.16.10
C Compiler:       gcc 10.3.0
Build Commit ID:  11787edfcfc157a0df951abc34684e4e18b3ef20
Build Type:       release
```

This is on helios helios-1.0.21004.

CC @knz

Jira issue: CRDB-17319

**Comment by ajwerner** [comment]
This crash seems unreasonable without something wild going on. Maybe some sort of memory corruption? The code is here:
https://github.com/cockroachdb/cockroach/blob/11787edfcfc157a0df951abc34684e4e18b3ef20/pkg/sql/schemachanger/scplan/declarative.go#L170

This is init time code processing some narrowly defined structures. There's not a ton of leeway here. The only instantiations of that struct are in the below file and given the rest of the error, we know that the structs must have been one of these. 
Also, do `*fmt.pp` objects ever make their way out of the `fmt` package (see https://go.dev/src/fmt/print.go#L104)?

https://github.com/cockroachdb/cockroach/blob/11787edfcfc157a0df951abc34684e4e18b3ef20/pkg/sql/schemachanger/scplan/rules.go#L732-L749

**Comment by knz** [comment]
They shouldnt. See the latest comment in https://github.com/cockroachdb/cockroach/issues/83706, I now suspect this particular go runtime / OS combination is borked in a way independent of crdb.

**Comment by davepacheco** [comment]
If the root cause is memory corruption, isn't this still a bug?

**Comment by ajwerner** [comment]
If the memory corruption is in the go runtime, is it a cockroach bug?

**Comment by ajwerner** [comment]
I interpreted https://github.com/cockroachdb/cockroach/issues/83706#issuecomment-1176359750 as an indication of widespread memory corruption. I can't make a claim as to whether this corruption is in `go` or in some other code, perhaps some linked cgo code. Either way, I do not thing there's value in maintaining this issue separately. Any root cause here doesn't have anything to do with the code implicated by this issue.

I hope we all can get to the bottom of it.

**Comment by davepacheco** [comment]
Just to close the loop on this: see oxidecomputer/omicron#1146 for gory details, but at this point I believe the corruption in _that_ issue was due to [this illumos OS issue](https://www.illumos.org/issues/15254).  The behavior there is that memory that is supposed to be zero'd by the Go runtime may not be properly zero'd.  It looks to me like that could explain this bug, so that seems the likely culprit.

**Comment by knz** [comment]
thank you.
