### ISSUE TITLE
Improve strings in Jobs page in DB Console

### ISSUE THREAD

**Issue by stbof** [cockroachdb/cockroach#83872]
Incorrect tool-tip for High-water Timestamp in Jobs page.

<img width="250" alt="Screen Shot 2022-07-05 at 1 10 07 PM" src="https://user-images.githubusercontent.com/20482960/177435040-3a278ed8-0644-4cc9-a276-b226b12ac863.png">

Tooltip: "The high-water mark acts as a checkpoint for the changefeed’s job progress, and guarantees that all changes before (or at) the timestamp have been emitted."

User column should be renamed to User Name to match Sessions page or vice versa.

<img width="1401" alt="Screen Shot 2022-07-05 at 4 52 44 PM" src="https://user-images.githubusercontent.com/20482960/177435301-179a8814-98a3-4d8a-be12-66bfbb0df6f7.png">
<img width="947" alt="Screen Shot 2022-07-05 at 4 54 14 PM" src="https://user-images.githubusercontent.com/20482960/177435305-24805884-1b63-4c5b-8b17-4f01877680cb.png">

Jira issue: CRDB-17324

**Comment by kevin-v-ngo** [comment]
Tooltip: The high-water mark acts as a checkpoint for the changefeed’s job progress, and guarantees that all changes before (or at) the timestamp have been emitted.

**Comment by ericharmeling** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/83914
