### ISSUE TITLE
kvserver: raft transport metrics

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#83917]
**Is your feature request related to a problem? Please describe.**

We currently have metrics for received messages:

https://github.com/cockroachdb/cockroach/blob/f7443768cac09740a943052689da7c32debbb907/pkg/kv/kvserver/metrics.go#L1589-L1609

but nothing for outgoing messages. In particular, we don't expose the dropping of outgoing messages, which can occur in

https://github.com/cockroachdb/cockroach/blob/ac77889c858a8e70fb98426b4e7af1c78f3675af/pkg/kv/kvserver/raft_transport.go#L677

and 

https://github.com/cockroachdb/cockroach/blob/7cfa5d4af89c1eb2ad5840331aa1baee9b3a62c8/pkg/kv/kvserver/raft_transport.go#L609-L615

as well as

https://github.com/cockroachdb/cockroach/blob/571bfa3afb3858ae84d8a8fcdbb0a38e058402a5/pkg/kv/kvserver/replica_raft.go#L1503-L1505

**Describe the solution you'd like**

Let `RaftMessageHandler` export a `Metrics() *RaftTransportMetrics` method where `*RaftTransportMetrics` absorbs the recv-related fields in the snippet above, and also starts tracking metrics for outgoing fields.

Retire (i.e. delete) the existing internal `*raftTransportStats` which weren't exposed anywhere (outside of `V(1)` logging) and are difficult to map onto our metrics model where nodes/stores only report datapoints about themselves. (The stats are reporting for the remote node).

**Describe alternatives you've considered**

**Additional context**

Came up in #83851 where we're intentionally dropping messages.

Jira issue: CRDB-17351

**Comment by pavelkalinnikov** [comment]
Seems reasonable, but why do we need to add the `Metrics()` method? Can we just delete old metrics, and add new metrics next to those already in `metrics.go` file?

**Comment by pavelkalinnikov** [comment]
Ah right, it looks like extending the interface might be needed for plumbing. I'll explore it in more detail.

**Comment by pavelkalinnikov** [comment]
@tbg The stats->metrics replacement is done. We can also explore what other Raft transport metrics would be useful.

Previously we discussed that it would be nice to track the queue byte size, in addition to counting the messages. I think we can do it as part of this issue. WDYT?

**Comment by tbg** [comment]
Made an issue for you :-)

https://github.com/cockroachdb/cockroach/issues/86371

Let's close this one.
