### ISSUE TITLE
sql: internalLookupCtx should be constructed using a collection

### ISSUE THREAD

**Issue by postamar** [cockroachdb/cockroach#83919]
This requires a fairly simple rewrite of the `newInternalLookupCtx` definition and all its call sites except one: https://github.com/cockroachdb/cockroach/blob/8b356c43de90fa473be4c43d1e81e67880afd178/pkg/sql/show_create.go#L232-L234

In this case, we don't rely on descriptors provided by `descs.Collection`, instead these come from a backup manifest. To deal with this, try inserting these descriptors as synthetic descriptors into the `descs.Collection`. That way, `newInternalLookupCtx` can become oblivious to where the descriptors are actually sourced from. 

Jira issue: CRDB-17352

**Comment by postamar** [comment]
Relates to https://github.com/cockroachdb/cockroach/issues/64673
cc @ajwerner @chengxiong-ruan

**Comment by ajwerner** [comment]
This is an approach. I've been thinking instead that we get rid of the `internalLookupCtx` altogether.

**Comment by postamar** [comment]
Baby steps! Jason is looking for a way to get started in this direction.
