### ISSUE TITLE
sql: `system.settings.lastUpdated` gets bogus value for the `version` setting

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#83928]
**Describe the problem**

On a fresh cluster, we see abnormal/bogus values in the `lastUpdated` column, for example in the year 3000 or later.

**To Reproduce**

1. `cockroach demo`
2. `table system.settings`
observe:

```
              name              |                value                 |        lastUpdated         | valueType
--------------------------------+--------------------------------------+----------------------------+------------
[...]
  version                       | \x12\b\b\x16\x10\x01\x18\x00 \x1a    | 4162-07-03 02:27:19        | m

```

**Environment:**

v22.1 and earlier

Jira issue: CRDB-17357

**Comment by stevendanna** [comment]
@knz Interesting to the note that the setting in the system tenant has a reasonable value:

**Comment by knz** [comment]
oh, it's only bad for secondary tenants, gotcha

**Comment by knz** [comment]
@ajwerner I'm sure you'd be loving this one
