### ISSUE TITLE
kvserver: default admission.kv.pause_replication_io_threshold to a nonzero value

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#83920]
**Is your feature request related to a problem? Please describe.**

The aforementioned cluster setting configures the functionality introduced in #83851. As is, the default disables pausing replication to followers.

**Describe the solution you'd like**

After additional verification, we should install a nonzero default value (strawman: 0.8) for this setting.

**Describe alternatives you've considered**

We could default the setting to zero in 22.2 and enable it only on-demand (i.e. in the presence of follower write overload).

**Additional context**

Jira issue: CRDB-17353

Epic CRDB-15069

**Comment by tbg** [comment]
Of particular concern is the behavior when there are multiple overloaded followers. Despite attempts to stick to one follower to drop messages to, updates in the gossiped view could lead to switching these followers relatively quickly and thus interrupting both streams for some time. For example, if we have

s1
s2 (overload)
s3 (overload)

and we chose to drop to s3, but then s3 quickly recovers while s2 doesn't, we could end up dropping to s2 the moment we stop dropping to s3. s3 won't have had a chance to catch up yet!

I think we are actually smart enough about this to avoid it - we only consider an overload signal if the corresponding follower is in good health and if the quorum is too. In the situation above, s3 would be probing (since we report it as unreachable to raft), so we wouldn't consider it as being able to participate in quorum right away, and thus wouldn't allow dropping traffic to s2. Still, it's hard to have much confidence in that working as precisely as it would have to.

**Comment by nvanbenschoten** [comment]
I think we'll also need to address https://github.com/cockroachdb/cockroach/issues/84884 before enabling this protection by default.
