### ISSUE TITLE
Improve layout and labeling in Job Details page

### ISSUE THREAD

**Issue by stbof** [cockroachdb/cockroach#83949]
The Creation time and Users labels are too small and should be above the value.

The values should be smaller and not bold.

Users should be User to match the Jobs page or User Name. See https://github.com/cockroachdb/cockroach/issues/83872

<img width="1351" alt="ui_jobs_page_details" src="https://user-images.githubusercontent.com/20482960/177655781-c7bb3745-bd51-4962-9358-dbffb3253eb8.png">

FYI @Annebirzin 

Jira issue: CRDB-17365

**Comment by Annebirzin** [comment]
Just following up on this issue: we have updated jobs detail page designs ([figma link here](https://www.figma.com/file/c6BNEn0mY6iHG1t5NhoH3E/20.1_obsrv_db-console-jobs?node-id=2011%3A9921)) that includes 
- updated page layout, moving job info below the SQL module (more consistent with the statement details page)
- updated type sizes for the `creation time` and `users info`
- additional info for `Last Execution Time` and `Execution Count` (these are also being added to the job overview page as new columns) 
- the new 'job errors' table if errors exist

![Screen Shot 2022-07-12 at 1 23 08 PM](https://user-images.githubusercontent.com/51920721/178554603-2cf6d2b3-d28e-478e-9f95-d5656581c0c4.png)

Some of this might be out of scope for this ticket, but for `creation time` and `users info` we can follow the type sizes and layout from these designs and the existing statement details page (`Font: Source Sans Pro, semi-bold and regular`, `Size: 14pt`)

**Comment by stbof** [comment]
User should be User Name to match the table.
