### ISSUE TITLE
Leaseholders temporarily move outside of regional table's configured region

### ISSUE THREAD

**Issue by jonstjohn** [cockroachdb/cockroach#83951]
**Describe the problem**

Given a regional table, leases sometimes transfer out of the table's region, even when sufficient resources (nodes, CPU, etc.) are available in the region.

This leads to unexpectedly higher SQL service latencies during the period that the leases are not in the primary region.

**To Reproduce**

1. Setup a 3-region cluster with 3 nodes in each region

For example, using `roachprod`:

```
roachprod create jon-multiregion -n 9 --clouds=gce \                                                                                         
    --gce-zones=us-east1-b:1,us-east1-c:1,us-east1-d:1,us-east4-a:1,us-east4-b:1,us-east4-c:1,us-west1-a:1,us-west1-b:1,us-west1-c:1 \
    --gce-machine-type=n1-standard-4 
```

2. Stage a `22.1` release 

```
roachprod stage jon-multiregion release v22.1.2
```

3. Start the cluster

```
roachprod start jon-multiregion
```

4. Setup a multi-region database and a simple table:

```
CREATE DATABASE birdie;

ALTER DATABASE birdie SET PRIMARY REGION "us-east1";
ALTER DATABASE birdie ADD REGION "us-west1";
ALTER DATABASE birdie ADD REGION "us-east4";
ALTER DATABASE birdie SURVIVE REGION FAILURE;

CREATE TABLE birdie.t (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    v STRING
);

```

5. Get external IPs for a node in each region (we'll only use `us-east1`):

```
export PGURL_USEAST1=`roachprod pgurl -q --external $CLUSTER:1  | tr -d \'`
export PGURL_USEAST4=`roachprod pgurl -q --external $CLUSTER:4  | tr -d \'`
export PGURL_USWEST1=`roachprod pgurl -q --external $CLUSTER:7  | tr -d \'`
```

6. Monitor leaseholders outside of the primary region (queries `crdb_internal.ranges` every 5 seconds):

```
cockroach sql --insecure --url "$PGURL_USEAST1" --execute "SELECT now(), range_id, node_id, node_id = lease_holder as is_leasholder, ARRAY[node_id] <@ voting_replicas as voter, locality, database_name, table_name, start_pretty, end_pretty FROM [ SELECT start_pretty, end_pretty, range_id, unnest(replicas) as node_id, unnest(replica_localities) as locality, lease_holder, voting_replicas, database_name, table_name FROM [ SELECT * FROM crdb_internal.ranges WHERE database_name = 'birdie' ] GROUP BY range_id, node_id, lease_holder, start_pretty, end_pretty, locality, voting_replicas, database_name, table_name ] WHERE node_id = lease_holder and locality not like 'cloud=gce,region=us-east1%' ORDER BY range_id ASC, node_id = lease_holder DESC, ARRAY[node_id] <@ voting_replicas ASC;" --watch 5s
```

7. Run concurrent INSERTs into `us-east1` (I used a simple go program with 500 concurrent INSERTs):

```
INSERT INTO birdie.t (v) VALUES ('test')
```

8. Observe the output of the leaseholder monitoring query. Leaseholders will temporarily appear outside of the primary region and eventually move back.

**Expected behavior**

Given sufficient resources in the primary region (nodes, CPU, etc.), the leaseholders should never move outside of the primary region.

**Additional data / screenshots**

Zone configuration for table `birdie.t`:

```
> SELECT raw_config_sql FROM [SHOW ZONE CONFIGURATION FOR TABLE birdie.t];
                                     raw_config_sql
----------------------------------------------------------------------------------------
  ALTER DATABASE birdie CONFIGURE ZONE USING
      range_min_bytes = 134217728,
      range_max_bytes = 536870912,
      gc.ttlseconds = 90000,
      num_replicas = 5,
      num_voters = 5,
      constraints = '{+region=us-east1: 1, +region=us-east4: 1, +region=us-west1: 1}',
      voter_constraints = '{+region=us-east1: 2}',
      lease_preferences = '[[+region=us-east1]]'
```

Example range monitoring query output after about 30 seconds of running INSERTs:

```
               now              | range_id | node_id | is_leasholder | voter |                 locality                  | database_name | table_name |                           start_pretty                           |                         end_pretty
--------------------------------+----------+---------+---------------+-------+-------------------------------------------+---------------+------------+------------------------------------------------------------------+-------------------------------------------------------------
  2022-07-06 17:50:06.420554+00 |       60 |       5 |     true      | true  | cloud=gce,region=us-east4,zone=us-east4-b | birdie        | t          | /Table/108/1/"\xbe\x991\xaa\x8b\x9dDk\x97\xe5\xe8\xad\xf7\x84Lp" | /Table/108/1/"\xe2\x8fIk#\xe2Ob\x9e\x1f\xda\xcd<\x8e\x8aw"
(1 row)
```

Lease history from range_id 60 indicating a cooperative lease transfer:

<img width="940" alt="Screen Shot 2022-07-06 at 11 53 24 AM" src="https://user-images.githubusercontent.com/95620/177658242-7ba253b5-f260-4fa0-9d3b-a5f492b1d7aa.png">

**Environment:**

 - CockroachDB version 22.1.2
 - Server OS: Linux
 - Client app: Go/pgx, cockroach sql

Jira issue: CRDB-17367

**Comment by jonstjohn** [comment]
This looks like it is a result of the store rebalancer using `AdminRelocateRange` which does not respect lease preferences. This will be addressed in issue  https://github.com/cockroachdb/cockroach/issues/82539 .

To determine that this was the root cause, I enabled additional logging on the store rebalancer using the `cockroach start` argument `--vmodule='store_rebalancer=1'`. When the lease transfer outside of the lease preference region was observed, a corresponding log entry was produced:

```
I220707 23:03:45.404221 236 kv/kvserver/pkg/kv/kvserver/store_rebalancer.go:381 ⋮ [n1,s1,store-rebalancer] 477  rebalancing r47 (873.84 qps) to better balance load: voters from (n1,s1):1,(n3,s3):2,(n8,s8):3,(n5,s5):4,(n4,s4):5 to [n4,s4 n3,s3 n8,s8 n5,s5 n2,s2]; non-voters from  to []
```

The log entry described the movement of the lease from `n1` to `n4` (the first value in the "to" part of the log).

This would only affect multi-region databases using region survival or a custom zone configuration that has voters outside of the primary region. In a scenario where most tables are regional tables in the primary region, store rebalancing could occur fairly frequently since we would expect a higher load on the primary region stores.

The lease transfers back to the lease preference region when the replicate queue runs next. Experimentally, this typically occurred in under 1 minute.

**Comment by kvoli** [comment]
This would be addressed by https://github.com/cockroachdb/cockroach/issues/82539.

A smaller, one line fix is changing this function argument to false.

https://github.com/cockroachdb/cockroach/blob/2e34f982b0756cd12d810a38fc341d4ec805cda0/pkg/kv/kvserver/store_rebalancer.go#L328-L328

**Comment by kvoli** [comment]
cc @lidorcarmel
