### ISSUE TITLE
storage: block 22.2 upgrade on removal of marked-for-compaction files

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/cockroach#84012]
#77634 added a cluster version that marked all files with user keys shared with neighbors in the same level for compaction. We need to add a 22.2 cluster version that upgrades the format major version to [`FormatMarkedCompacted`](https://github.com/cockroachdb/pebble/blob/d68c152233afe41c9d5a8bfd8a0f80f2ee5f9107/format_major_version.go#L87) to block the version upgrade on finishing compacting away all of those marked files.

After that cluster version, we're free to reuse the `MarkedForCompaction` bit for future migrations (eg, the table-filter/block-property-filter migration).

This sweep step will free us up to remove atomic compaction units and related code for the 23.1 release.

Jira issue: CRDB-17406

Epic CRDB-2624

**Comment by nicktrav** [comment]
Note to self, following a conversation with @jbowens.

Strictly speaking, we're ok here already, as we already have a [cluster version in place in Cockroach to enable range keys](https://github.com/cockroachdb/cockroach/blob/a3f32958321dfcb130701037e3068284a4436a32/pkg/clusterversion/cockroach_versions.go#L295). This migration covers compacting out all of the split user keys, which must happen [_before_](https://github.com/cockroachdb/pebble/blob/63d5527944113188fe042ae4d284fd1bd76f2df1/format_major_version.go#L87) we ratchet up to the Pebble format version for range keys.

_However_, we'll want to add an explicit cluster version to make it obvious that Cockroach is upgrading the Pebble format version, and this version upgrade must wait for all marked tables to be compacted before proceeding. In practice, the migration should be short lived (we don't expect too many split keys), but we should be clear in any case.
