### ISSUE TITLE
Modify Backup Schedule via SQL

### ISSUE THREAD

**Issue by livlobo** [cockroachdb/cockroach#84033]
**Is your feature request related to a problem? Please describe.**
Users cannot modify their backup schedules after they are created

**Describe the solution you'd like**
ALTER BACKUP SCHEDULE <schedule id> 
SET option=new_value

**Describe alternatives you've considered**
Dropping the schedule and creating a new one with the desired changes, is a non-elegant workaround.

**Additional context**
This is a pre-requisite for supporting modify managed backup schedule

Jira issue: CRDB-17424

Epic CC-6253

**Comment by benbardin** [comment]
@livlobo Which options do you want to make modifyable? All of them? For instance, do we want to enable users to modify the targets of the backup? The target _type_ (e.g. tables => full cluster). This is all possible, it just makes clear syntax more challenging to define. Currently, for instance, "full cluster" is indicated by an absent "targets" clause. But we wouldn't want an absent "targets" clause to have the same effect in ALTER, which means coming up with syntax that is both (a) new and (b) different from CREATE, I think. Your thoughts?
```
root@localhost:26257/defaultdb> \h create schedule;
Command:     CREATE SCHEDULE FOR BACKUP
Description: backup data periodically
Category:    enterprise features
Syntax:
CREATE SCHEDULE [IF NOT EXISTS]
[<description>]
FOR BACKUP [<targets>] INTO <location...>
[WITH <backup_option>[=<value>] [, ...]]
RECURRING [crontab|NEVER] [FULL BACKUP <crontab|ALWAYS>]
[WITH EXPERIMENTAL SCHEDULE OPTIONS <schedule_option>[= <value>] [, ...] ]
```
