### ISSUE TITLE
logictest: probabilistically replace point tombstones with range tombstones

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#84042]
**Is your feature request related to a problem? Please describe.**

To increase test coverage and increase confidence in our use of MVCC range operations, we should consider some enhancements to our existing tests that would use a range tombstone in place of a point tombstone with some probability (or via some metamorphic flags).

This testing can only happen outside of the KV API boundary, since inside the API boundary callers can observe the differences.

Extending the SQL logic tests to do this probabilistic testing seems like a good place to start. We should also consider other high-level tests, e.g. roachtests.

This is complicated by the fact that MVCC point tombstones are transactional but MVCC range tombstones aren't. This means that we'll have to do this replacement inside the KV/storage layer. For the 1PC path, well need to write MVCC range tombstones directly, while for transactional deletes we'll have to write an initial MVCC point tombstone as the provisional intent value, and only replace it with an MVCC range tombstone during intent resolution.

Jira issue: CRDB-17427

Epic CRDB-2624

**Comment by nicktrav** [comment]
@erikgrinaker - feel free to wordsmith this a bit more, if you have a sense for how this should be implemented.

**Comment by erikgrinaker** [comment]
Thanks! Added a few notes. One annoying wrinkle is that these can't be transactional, so we'll have to do the replacement deep inside the intent resolution machinery.
