### ISSUE TITLE
upgrades: make `raftAppliedIndexTermMigration` more robust

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#84073]
`raftAppliedIndexTermMigration` runs a below-Raft migration, using `IterateRangeDescriptors. This has a few issues:

* It fetches a list of ranges, and then iterates across them. If iteration takes a while, then ranges can disappear in the meanwhile, failing the entire migration. We need to handle this.

* The `Migrate` request requires all replicas for all ranges to be available. If even a single replica is lagging, it will fail the whole migration. The migration should at the very least have retries, ideally checkpointing.

Related to https://github.com/cockroachdb/cockroach/issues/72931.

Jira issue: CRDB-17446

**Comment by tbg** [comment]
> The Migrate request requires all replicas for all ranges to be available. If even a single replica is lagging, it will fail the whole migration. The migration should at the very least have retries, ideally checkpointing.

It's not easy to implement and it might be a bad strategy on the whole anyway, but we could also force log truncations that ensure that any follower that is behind will need a future snapshot. The benefit of that could be that it could be made work without blocking the Migrate command.

**Comment by erikgrinaker** [comment]
Resolved by #84909.
