### ISSUE TITLE
streamingccl: move protected timestamp forward after ingestion job checkpoints it

### ISSUE THREAD

**Issue by gh-casper** [cockroachdb/cockroach#84086]
Currently, the ingestion job checkpoints its progress (saving the newest job high watermark) after it received a row from the frontier processor, but the frontier processor already heartbeat this new frontier to the source producer job which moves forward the protected timestamp. When we retry, we may resume with a timestamp that falls behind the source job protected timestamp, which is not safe.

We need to move job progress saving from ingestion job to frontier processor or move the heartbeat logic from the frontier processor to the ingestion job.

Jira issue: CRDB-17454

**Comment by samiskin** [comment]
@gh-casper do you mind if I grab this?

**Comment by gh-casper** [comment]
@samiskin  Sure
