### ISSUE TITLE
jobs: failed job prevents jobs page from loading

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#84139]
Reproduced in v22.1:

A RESTORE failed after being resumed due to a separate bug (#84137), but subsequent attempts to load the jobs page in the db console now return a 500. 
<img width="927" alt="Screen Shot 2022-07-09 at 9 50 29 AM" src="https://user-images.githubusercontent.com/15615/178108824-ffee1da7-c708-444f-bb51-a087aafb6620.png">

The error in the logs is terse, but gives some hint: `server/admin.go:1944 ⋮ [n1] 158  ‹admin-jobs›: invalid bytea escape sequence`

It appears that this is coming from the `execution_events::string::bytes` projection in the query in admin.go:
https://github.com/cockroachdb/cockroach/blob/54b4fcaa231abd16260fb09722ed291dbd6a4900/pkg/server/admin.go#L2005

Querying the table by hand seems to confirm that:
```
SELECT execution_events::string::bytes FROM crdb_internal.jobs WHERE true;

ERROR: could not parse "[{\"executionEndMicros\": \"1657374146030733\", \"executionStartMicros\": \"1657374145910045\", \"instanceId\": 1, \"status\": \"reverting\", \"truncatedError\": \"database \\\"[107]\\\" does not exist\"}, {\"executionEndMicros\": \"1657374176161961\", \"executionStartMicros\": \"1657374176053258\", \"instanceId\": 1, \"status\": \"reverting\", \"truncatedError\": \"database \\\"[107]\\\" does not exist\"}, {\"executionEndMicros\": \"1657374299948965\", \"executionStartMicros\": \"1657374299877119\", \"instanceId\": 1, \"status\": \"reverting\", \"truncatedError\": \"database \\\"[107]\\\" does not exist\"}]" as type bytes: invalid bytea escape sequence
SQLSTATE: 22025
```

Jira issue: CRDB-17487

**Comment by rafiss** [comment]
I haven't debugged this yet, buy my guess here is that  the `crdb_internal.jobs(execution_events)` column is not being populated with the correct encoding.

**Comment by rafiss** [comment]
oh i misunderstood. `execution_events` is a JSONB column, so then in that case, the issue might be that the JSONB->STRING cast is not doing what it should. i'll investigate further.

**Comment by rafiss** [comment]
The cast is working as intended.

The issue here is that it is not correct to assume that any string can be converted into `BYTEA`. 

A simple repro of what's going on is copy+pasting this SQL command:
```
SELECT '[{"executionEndMicros": "1657374146030733", "executionStartMicros": "1657374145910045", "instanceId": 1, "status": "reverting", "truncatedError": "database \"[107]\" does not exist"}, {"executionEndMicros": "1657374176161961", "executionStartMicros": "1657374176053258", "instanceId": 1, "status": "reverting", "truncatedError": "database \"[107]\" does not exist"}, {"executionEndMicros": "1657374299948965", "executionStartMicros": "1657374299877119", "instanceId": 1, "status": "reverting", "truncatedError": "database \"[107]\" does not exist"}]'::jsonb::string::bytea;
```

The JSON must use `\"` to escape the quotes that are part of the error message text. But this cannot be converted to`bytea`, since that's not a valid `bytea` escape sequence. That restriction is required for Postgres compatibility.

A solution could be to use the `replace` function before casting to `bytea`:
```
SELECT replace('[{"executionEndMicros": "1657374146030733", "executionStartMicros": "1657374145910045", "instanceId": 1, "status": "reverting", "truncatedError": "database \"[107]\" does not exist"}, {"executionEndMicros": "1657374176161961", "executionStartMicros": "1657374176053258", "instanceId": 1, "status": "reverting", "truncatedError": "database \"[107]\" does not exist"}, {"executionEndMicros": "1657374299948965", "executionStartMicros": "1657374299877119", "instanceId": 1, "status": "reverting", "truncatedError": "database \"[107]\" does not exist"}]'::jsonb::string, '\"', '\\"')::bytea;
```

That is, the admin.go code could do:
```
SELECT ... replace(execution_events::string, '\"', '\\"')::bytes ... FROM crdb_internal.jobs
```

I'll move this back to SQL Observability

**Comment by ajwerner** [comment]
Why are we casting to bytes in the first place?
