### ISSUE TITLE
schema: cascade interacting with offline tables

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#84137]
An `offline` table means nobody other than the job that moved it to or created it in the offline state is supposed to interact with it; doing so violates the assumptions that job makes about its exclusive interactions with that table, in particular safety of non-transactional and non-lease-holding interactions.

However currently it appears that `DROP ... CASCADE` is cascading to offline tables, violating this invariant.

To reproduce:
* Start a job that creates or moves a table into `OFFLINE`. (e.g. `RESTORE db.tbl`)
* While that job is running or paused, drop the database containing that table with cascade (`DROP DATABASE db CASCADE`).
* Observe that the job is still running but the table is now in DROP and its namespace entry has been removed.

Jira issue: CRDB-17485

**Comment by dt** [comment]
@chengxiong-ruan points out that this is likely a regression we picked up in the switch to the new schema changer as this restriction is in the old code here: http://github.com/cockroachdb/cockroach/blob/5fb4478b94ecaf215500e5e5082946c52873adfe/pkg/sql/drop_cascade.go#L112-L112

**Comment by ajwerner** [comment]
That's definitely what this is. We'll get it added back ASAP next week.
