### ISSUE TITLE
ui: Logs should be passed to the UI as protos

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#8414]
Currently logs are returned to the UI as raw JSON, which is a bad practice. We should add logs to the v1 admin API.

**Comment by maxlang** [comment]
cc @tamird

**Comment by tamird** [comment]
Events or logs?

**Comment by maxlang** [comment]
Whoops, logs

**Comment by tamird** [comment]
cc @petermattis because the proto was removed in c423511aa95d84b30f80d79f89222468e5ca6b73.

**Comment by petermattis** [comment]
We can make `log.Entry` a proto, we just don't want to write log entries to disk as protos. IMO, this is low priority to change as it is (minor and arguable) code cleanliness for a rarely used feature.

**Comment by tamird** [comment]
@maxlang is planning to use it more in the UI, hence this issue. @maxlang:
let's pair on getting it converted to a proto if you need help.

**Comment by petermattis** [comment]
Why/where are we planning to use the logs more in the UI?
