### ISSUE TITLE
sql: mention "changefeed expressions not supported" explicitly in docs and GA release notes

### ISSUE THREAD

**Issue by chengxiong-ruan** [cockroachdb/cockroach#84176]
A child of https://github.com/cockroachdb/cockroach/issues/58356

This is a reminder that we will need to call out this known limitation for docs and the GA release notes

Jira issue: CRDB-17510

**Comment by chengxiong-ruan** [comment]
There isn't any work required from eng side. It's a reminder of the doc version of this issue: https://github.com/cockroachdb/docs/issues/15011

**Comment by chengxiong-ruan** [comment]
resolved by https://github.com/cockroachdb/docs/pull/15308

**Comment by ajwerner** [comment]
Given we have the docs issue, I'm just going to close this.
