### ISSUE TITLE
server,admin,ui: sequential range stats requests are problematic

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#84216]
**Describe the problem**

In https://github.com/cockroachdb/cockroach/pull/83677 we're adding a request per range to sum up live bytes for the table details page. In a cluster with many ranges and a multi-region topology, this will make this page unreasonable and unacceptably slow. We need to do something before shipping that. There are some options, like choosing not to fetch the data if there are too many ranges. Another option may be to parallelize the fetches (I have a WIP change to do that). 

This issue is a placeholder to make sure we do something and validate it before we ship 22.2.

Relates to https://github.com/cockroachdb/cockroach/issues/84105

Jira issue: CRDB-17525

**Comment by maryliag** [comment]
@ajwerner can we close this thanks to the changes added on https://github.com/cockroachdb/cockroach/pull/85442 ?
