### ISSUE TITLE
Option to include table name in change feed message

### ISSUE THREAD

**Issue by jonstjohn** [cockroachdb/cockroach#84215]
**Is your feature request related to a problem? Please describe.**
When the `topic_name` URL parameter is used when creating a change feed with multiple tables, there is no clearly documented way to include the table name in the message contents.

As of `22.1.2`, using the `topic_in_value` option will include the table name in the `topic` property, however, this appears to be a defect since the actual topic name is the value of the `topic_name` URL parameter, not the table name. An issue was created to track this defect: https://github.com/cockroachdb/cockroach/issues/84011 .

**Describe the solution you'd like**
Provide a `table_in_value` option as a boolean that when enabled, outputs the table name in the change feed message contents in the `table_name` property. **Ensure that it respects the value of the `full_table_name` option.**

**Describe alternatives you've considered**
Not using `topic_name` in conjunction with multiple tables was considered. However, the requirement is to use a custom topic name with multiple tables. As long as the `CREATE CHANGEFEED` syntax supports this, there should be a way to include the table name in the message contents.

**Additional context**
Example:

```
CREATE CHANGEFEED FOR users,vehicles
INTO 'kafka://localhost:9092?topic_name=mytopic'
WITH table_in_value, full_table_name;
```
Should emit the value including:

```
"table_name": "movr.public.users"
```

when the row is from the `users` table and:

```
"table_name": "movr.public.vehicles"
```

when the row is from the `vehicles` table.

Jira issue: CRDB-17524

Epic CRDB-21713

**Comment by amruss** [comment]
Note: we should pick this up in 22.2, as some users are relying on this functionality through the bug in https://github.com/cockroachdb/cockroach/issues/84011

**Comment by amruss** [comment]
Hey Jon - we've decided not to pick this or https://github.com/cockroachdb/cockroach/issues/84011b in the near term - so the behavior would stay in the same in the 22.2 release. In the future, we're going to provide this functionality using changefeed expressions, which will be in preview in 22.2

**Comment by miretskiy** [comment]
@amruss -- I think we can close this?
