### ISSUE TITLE
external: register all ExternalStorage, KMS and Sink providers as supported External Connections

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#84228]
This change tracks all the providers that need to be registered as resources that can be represented by an External Connection. Every provider will need to provide its own implementation of the External Connection interface to be considered supported.

## External Storage
- [x] s3
- [x]  gs - https://github.com/cockroachdb/cockroach/pull/85964
- [x]  azure - https://github.com/cockroachdb/cockroach/pull/86257
- [x]  nodelocal
- [x]  userfile - https://github.com/cockroachdb/cockroach/pull/86006
- [ ]  http, https

## Sink
- [ ]  null
- [x]  kafka
- [x]  webhook-http, webhook-https
- [x]  gcpubsub
- [ ] experimental-sql

## KMS
- [ ] aws
- [x] gs

Jira issue: CRDB-17530

Epic CRDB-15001

**Comment by miretskiy** [comment]
Closing; not going to do remaining sinks (e.g. null).
