### ISSUE TITLE
sql: allow strings in the form `'Array[...]'` to be parsed to arrays

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#84274]
Arrays seem to be the only type where calling ParseAndRequireString(EncodeSQLString(FormatNode(d))) isn't a round trip. Formatting an array, no matter what flags, gives the form `ARRAY[1]` or `ARRAY[1:::int]`, while `ParseDArrayFromString` requires the form `{...}`. This isn't usually a problem because _casting_ an array to a string gives the curly bracket form, but it would be convenient for implementing sql functions like `format` that are meant to return valid SQL if there were some format flag that was guaranteed to return something that worked as a quoted literal, and the easiest way to do that would probably be to make ParseDArrayFromString more powerful. 

Alternate solution: Adding a format option (e.g. `FmtCtx(tree.FmtParseableString)`) that behaved like `EncodeSQLString(FormatWithFlags(d, tree.FmtArrayToString))` but with curly braces output for arrays would also work for my purpose, but wouldn't improve the existing SQL UX.

Jira issue: CRDB-17564

**Comment by rafiss** [comment]
> Formatting an array, no matter what flags, gives the form ARRAY[1] or ARRAY[1:::int]

I think this is the confusion -- that's not quite accurate.

Try using the `tree.fmtPgwireFormat` flag, or use `func (d *DArray) pgwireFormat` directly.

**Comment by HonoreDB** [comment]
Aha, thanks! Secret unexported flag! That's not quite the general solution I was looking for to getting a roundtrippable escaped string--it works for arrays, but not for many other types. But I think it's lead me to a workable almost-general solution--call `eval.PerformCast(d, types.String)`. That gets me to a giant switch case that uses `fmtPgwireFormat` for some types, but `FmtBareStrings` for others and some custom logic for others.

In particular, `eval.PerformCast(ctx, d, types.String).String()` replicates what happens when you call the SQL function `quote_literal` on a non-string datum, which is what I was looking for. Unfortunately that's still not always 100% roundtrippable due what looks like a known issue with arrays of geometric types and some very odd behavior with float4 arrays that is probably a separate issue.

**Comment by rafiss** [comment]
Ah, we also have `tree.FmtPgwireText` which is the exported flag to use here, and is defined as:
```
	FmtPgwireText FmtFlags = fmtPgwireFormat | FmtFlags(lexbase.EncBareStrings)
```

**Comment by HonoreDB** [comment]
That one doesn't work for the thing that I'm trying to do, I need the quotes that EncBareStrings removes.

**Comment by rafiss** [comment]
I'm going to close this since I think for PG-compatibility it's unlikely that we'd ever change any parsing/casting logic so that a string like `'Array[...]` gets parsed into an array.

If the ask is about easier ways to round-trip data, would you mind filing a separate issue that provides some context for that problem? Thanks!
