### ISSUE TITLE
jobs: if `jobs.scheduler.enabled` is false, CREATE SCHEDULE should fail (or at least leave a paper trail)

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#84296]
Currently, if `jobs.scheduler.enabled` is set to false, CREATE SCHEDULE succeeds and writes a schedule to the scheduled_jobs system table. Then, the scheduled backups silently do not begin. Instead, CREATE SCHEDULE should probably fail, or alternatively, return a warning to the user and some additional info to the schedules system table. 

This unclear UX lead to an escalation. Namely, the user didn't realize they had set this setting to false, and couldn't figure out why no backups were starting from the schedule. https://github.com/cockroachlabs/support/issues/1693

Jira issue: CRDB-17575

**Comment by amruss** [comment]
Changing the scope here to log a warning when we run into this situation.
