### ISSUE TITLE
sql: add waiting tests that verify all reference table versions update when creating FKs

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#8429]

**Comment by dt** [comment]
@vivekmenezes suggests:
```It will be super cool if you can add a knob here [schemachanger's exec] to check that the table is made public only after all FKs have had their versions updated.
just like oldNameNotInUseNotification```

**Comment by vivekmenezes** [comment]
Also test that the asynchronous execution of schema changes executes this schema change properly. This will involve disabling the normal route for schema change execution and speeding up the execution of async schema changes.

**Comment by dianasaur323** [comment]
@dt If we haven't done this yet, it's probably not going to get done by 1.0? Moving to Q3 2017, but to be honest I'm not sure what this issue is referencing.

**Comment by vivekmenezes** [comment]
@dt is there any work to be done here?

**Comment by dt** [comment]
various tests have grown to include several schemas with FKs. We don't focus on them explicitly in the schema_change test, I don't think there's any active work beyond the current state of the world happening any time soon here.
