### ISSUE TITLE
sql: automatic way to ensure new sql keyword is added to `bare_label_keywords` list

### ISSUE THREAD

**Issue by chengxiong-ruan** [cockroachdb/cockroach#84309]
**Describe the solution you'd like**
Adding new keyword could break user queries which use column labels without `AS`. We added the `bare_label_keywords` list to allow those keywords to be used as column labels. However, it's easy to forget to add the keyword. We need to an automatic way to validate all newly added keywords are added to this list.

We could auto generate code to validate that, for example we're already doing similar thing when generating [this list](http://github.com/cockroachdb/cockroach/blob/4566e9246a61b66285c31a5bca604dbfef518092/pkg/sql/lexbase/keywords.go#L6-L6). The hard part could be how do we know a keyword is newly added? One alternative is to add all keywords (including existing ones) to this list, and the automatic check just need to make sure all keywords are added.

Jira issue: CRDB-17582

**Comment by chengxiong-ruan** [comment]
I don't know which project I should add to this issue...so I just attached my team.

**Comment by rafiss** [comment]
Thanks for the issue. What's the impact of forgetting to add the keyword to `bare_label_keywords`?

**Comment by chengxiong-ruan** [comment]
@rafiss adding new keyword without adding to `bare_label_keywords` could break user query if the query use [column label without `AS`](https://github.com/cockroachdb/cockroach/blob/4753c67bfd92bc0c4823d1bb81b8ce25850f30bb/pkg/sql/parser/sql.y#L13967). Before `bare_label_keyword` was added, any new keyword could break user queries because it was expecting an `IDENT` token, but if you used a keyword as the column label, the parser would fail to get an `IDENT` and error out :(
I think it could be quite rare... but I encountered one case when I was adding the new keyword `INPUT` which broke [this test](https://github.com/cockroachdb/cockroach/blob/264cd04d43c4299a2a4ee18f412f2b4e9c1fcd07/pkg/sql/logictest/testdata/logic_test/pg_builtins#L524).

**Comment by michae2** [comment]
Maybe some kind of test that automatically tries to parse `SELECT 1 <keyword>` with every (unreserved) keyword would suffice?
