### ISSUE TITLE
circle.yml: binaries are built in every container

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#8431]
It seems that all three containers are building binaries on master. This is wasteful and possibly racy.

@mberhault I'm assigning you because I think you wrote this stuff, but feel free to reassign if there's a more suitable person.

**Comment by petermattis** [comment]
From https://circleci.com/docs/parallel-manual-setup:

> Note the final colon, and parallel: true on the next line. This is a command modifier which tells circle that the command should be run in parallel on all test machines. It defaults to true for commands in the machine, checkout, dependencies and database build phases, and it defaults to false for commands in the test phases.
>
> Please note that since we do not support parallel deployment, specifying ‘parallel:true’ in the deployment phase will cause an error.

**Comment by tamird** [comment]
This is made irrelevant by #8470.
