### ISSUE TITLE
sql: order by in row_to_json does not work

### ISSUE THREAD

**Issue by xmhealth** [cockroachdb/cockroach#84328]
**Describe the problem**

Subquery has order by statment in row_to_json function is not ordered correct.

**To Reproduce**

```
create table foo1(
	test1 string,
	sort_no string
);

insert into foo1 values('1', '01');
insert into foo1 values('2', '02');
insert into foo1 values('3', '03');
insert into foo1 values('0', '00');
```

`select * from foo1 order by sort_no;`
The result is correct, 00 is the first row.
```
0	00
1	01
2	02
3	03
```
`select row_to_json(t.*) from (select * from foo1 order by sort_no) t;`
The result is incorrect, 01 is the first row, and 00 is the last row.
```
{"sort_no": "01", "test1": "1"}
{"sort_no": "02", "test1": "2"}
{"sort_no": "03", "test1": "3"}
{"sort_no": "00", "test1": "0"}
```

**Expected behavior**
The result of row_to_json can order by correct.

**Environment:**
 - CockroachDB version [e.g. 21.1.10]
 - Server OS: [Cent OS]
 - Client app [dbeaver 21.2.5, JDBC]

Jira issue: CRDB-17588

**Comment by cucaroach** [comment]
I'm not sure this is a bug yet but just some quick tests show that a) postgres does sort the results and b) row_to_json doesn't really have anything to do with it:

```
demo@127.0.0.1:26257/defaultdb> select t.* from (select * from foo1 order by sort_no) t;
  test1 | sort_no
--------+----------
  0     | 00
  3     | 03
  1     | 01
  2     | 02
(4 rows)
```

**Comment by cucaroach** [comment]
According to multiple sources this isn't a bug.   A subquery is a table an as such isn't ordered and the optimizer will just ignore the order by.   Note however that if there's a limit that can change the results so will apply the order by.  Kinda confusing and I could see the argument that what PG does is more user friendly but its not a bug.  The SQL standard explicitly disallows an order by in a sub query so this is a grey area in terms of correctness.

[1] https://dba.stackexchange.com/questions/260446/does-the-order-by-clause-of-a-subquery-pass-through-to-the-main-results-postg
[2]https://mariadb.com/kb/en/why-is-order-by-in-a-from-subquery-ignored/
