### ISSUE TITLE
storage: More snapshot testing

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#8434]
* [x] In `TestChangeReplicasDescriptorInvariant`, the [failed ChangeReplicas](https://github.com/cockroachdb/cockroach/blob/a63f336a03ddf4f74d769cbf8acf66da031c36e7/storage/client_raft_test.go#L990) call should have sent a preemptive snapshot. We should verify that 
    1. the snapshot was sent and applied
    1. this preemptive snapshot was successfully replaced by a second preemptive snapshot in the test's third ChangeReplicas call
* [ ] #8111 suggests the following test (which verifies the ability of a snapshot with a new replica ID to overwrite existing data): 
    1. replicate a range to three stores
    1. stop a store
    1. remove the stopped store from the range
    1. truncate the logs
    1. re-add the store and restart it (in both orders, if possible. i'm not sure if it's possible to re-add the store before restarting it; it probably won't be after streaming snapshots)
    1. ensure that store can catch up with the rest of the group
* [ ] As above, but without the remove and re-add. Just stop, truncate, and restart. This verifies that a snapshot *without* a new replica ID works correctly.

**Comment by petermattis** [comment]
@dt This is outside your area of expertise, but I'm trying to enlist more help on the stability front. Sync with Ben to get a sense of existing tests in this area.
