### ISSUE TITLE
sql: SHOW INDEXES output should be more stable

### ISSUE THREAD

**Issue by postamar** [cockroachdb/cockroach#84357]
Currently, it's not stable, and this bloats the diffs needlessley; see for example https://github.com/cockroachdb/cockroach/pull/84303

To implement: Add an ORDER clause to the query in pkg/sql/delegate/show_database_indexes.go

Jira issue: CRDB-17612

**Comment by ajwerner** [comment]
One task is to figure out what is unstable. We can potentially just do an order by. Maybe we need to sort something inside the virtual table.

**Comment by michae2** [comment]
I think this will be fixed by https://github.com/cockroachdb/cockroach/pull/84776

**Comment by Xiang-Gu** [comment]
@wenyihu6 I saw that your PR is merged and claim to fix this. I rebase my PR on master but still run into the ordering issues in logic test.

The failing query is something like 
```
select index_name,column_name,direction from [show indexes from t1];
                    expected:
                        t1_pkey        id     ASC
                        t1_pkey        id2    N/A
                        t1_pkey        name   N/A
                        t1_pkey        rowid  N/A
                        t1_id_id2_key  id     ASC
                        t1_id_id2_key  id2    ASC

                    but found (query options: "") :
                        t1_pkey        id     ASC
                        t1_pkey        name   N/A
                        t1_pkey        rowid  N/A
                        t1_pkey        id2    N/A
                        t1_id_id2_key  id     ASC
                        t1_id_id2_key  id2    ASC
```

According to this [slack thread](https://cockroachlabs.slack.com/archives/CV581CE78/p1658875501198879), it seems row ordering from a ordered subquery, as in this case, is not guaranteed. Did I miss something?

That thread also pointed out another [PR](https://github.com/cockroachdb/cockroach/pull/68295) (about adding and using a cluster setting) to preserve the ordering from selecting from ordered subqueries.

**Comment by wenyihu6** [comment]
This issue is only partly fixed. https://github.com/cockroachdb/cockroach/pull/84776 added an ORDER clause to query in `pkg/sql/delegate/show_database_indexes.go`. But more work is still needed to fix something like `SELECT ... FROM [SHOW INDEX]`. The order of subquery is still not preserved.

**Comment by rafiss** [comment]
>  Order of SHOW INDEX FROM TABLE or SHOW INDEX FROM DATABASE is guaranteed, but the output is not if they are used as a subquery.

That's fine - CRDB does not guarantee order across subquery results in general. If that behavior is needed, the `propagate_input_ordering` setting can be used (https://github.com/cockroachdb/cockroach/pull/68295).

In the case of the logic test being discussed here, the solution is to use the `rowsort` option or to change the query to something like `select index_name,column_name,direction from [show indexes from t1] ORDER BY 1, 2, 3;`

So I'll close this.
