### ISSUE TITLE
sql: descending inverted indexes do not work

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#84388]
An example:

```
defaultdb> CREATE TABLE t (k INT PRIMARY KEY, j JSON, INVERTED INDEX j_idx (j DESC));
CREATE TABLE

defaultdb> INSERT INTO t VALUES (1, '[0, 1, 2, 3]'), (2, '[0, 2, 4]'), (3, '[1, 2, 4]');
INSERT 3

defaultdb> SELECT * FROM t@j_idx WHERE j @> '2';
ERROR: error decoding 6 bytes: did not find marker 0x12 in buffer 0x3700012a0400
```

I'm not sure, but it seems like we never intended to allow the DESC option for inverted indexes. I don't see any use of specifying the direction of an inverted index, because we cannot perform a range scan on an inverted index. So I think we should disallow DESC (and maybe ASC too to prevent confusion) for inverted index columns. I don't think we need to worry about this being a breaking change, since these indexes are broken already.

What about multi-column inverted indexes? Should we allow the non-inverted columns to be DESC? Again, range scans on inverted indexes are not possible, so I don't think there is any use-case for this. However, I don't think it's broken so maybe we should just allow it? If we disallow it, would we need to consider a migration strategy because we consider it backward incompatible?

Jira issue: CRDB-17631

**Comment by jordanlewis** [comment]
> I'm not sure, but it seems like we never intended to allow the DESC option for inverted indexes.
I agree with this. We use hardcoded ascending encodings all over the place in the inverted index span and key encoding code, I believe.

I agree that we should disallow DESC/ASC in inverted indexes. And to boot, this is Postgres compatible - you can't specify asc/desc on a GIN index.

> Should we allow the non-inverted columns to be DESC? However, I don't think it's broken so maybe we should just allow it?

Yes, I think so.

BTW, the span encoding itself is the thing that seems busted:

```
demo@127.0.0.1:26257/defaultdb> explain select * from a where j @>'"foo"';
ERROR: error decoding 9 bytes: did not find terminator 0x0 in buffer 0x12666f6f0002
demo@127.0.0.1:26257/defaultdb> explain select * from a where j @>'false';
ERROR: error decoding 4 bytes: unknown tag 12
demo@127.0.0.1:26257/defaultdb> explain select * from a where j @>'{"foo": "bar"}';
ERROR: error decoding 12 bytes: did not find terminator 0x0 in buffer 0x126261720002
```
