### ISSUE TITLE
Fail to compile c-protobuf

### ISSUE THREAD

**Issue by zhaoyuxi** [cockroachdb/cockroach#8438]
1 My compile env:
gcc/g++ 5.2. glibc 2.19

2 Reason:
protobuf/stubs/mathutil.h includes math.h. But it conflicts with c++ header cmath. There is a glibc bug (Unix98 isinf and isnan functions conflict with C++11). Pls visit "https://sourceware.org/bugzilla/show_bug.cgi?id=19439" for the detail. 

3 The compile error:
cmd golang.org/x/tools/cmd/stringer                            	[OK]
cmd honnef.co/go/unused/cmd/unused                             	[OK]
cmd github.com/cockroachdb/c-protobuf/cmd/protoc               	[error exit status 2]
github.com/cockroachdb/c-protobuf
# github.com/cockroachdb/c-protobuf
In file included from ../c-protobuf/datapiece.cc:39:0:
internal/src/google/protobuf/stubs/mathutil.h: In function ?.ool google::protobuf::internal::IsNan(T) [with T = double]?.
internal/src/google/protobuf/stubs/mathutil.h:60:21: error: call of overloaded ?.snan(double&)?.is ambiguous
   return isnan(value);
                     ^
In file included from /usr/include/features.h:378:0,
                 from /usr/local/include/c++/5.2.0/x86_64-unknown-linux-gnu/bits/os_defines.h:39,
                 from /usr/local/include/c++/5.2.0/x86_64-unknown-linux-gnu/bits/c++config.h:482,
                 from /usr/local/include/c++/5.2.0/string:38,
                 from internal/src/google/protobuf/util/internal/datapiece.h:34,
                 from ../c-protobuf/datapiece.cc:31:
/usr/include/bits/mathcalls.h:241:1: note: candidate: int isnan(double)
 __MATHDECL_1 (int,isnan,, (_Mdouble_ __value)) __attribute__ ((__const__));
 ^
In file included from /usr/local/include/c++/5.2.0/random:38:0,
                 from internal/src/google/protobuf/map.h:47,
                 from internal/src/google/protobuf/struct.pb.h:29,
                 from ../c-protobuf/datapiece.cc:33:
/usr/local/include/c++/5.2.0/cmath:626:3: note: candidate: constexpr bool std::isnan(long double)
   isnan(long double __x)
   ^
/usr/local/include/c++/5.2.0/cmath:622:3: note: candidate: constexpr bool std::isnan(double)
   isnan(double __x)
   ^
/usr/local/include/c++/5.2.0/cmath:618:3: note: candidate: constexpr bool std::isnan(float)
   isnan(float __x)

4 I try to merge the glibc fix. But it can't work.  I think the __cplusplus is ingored. 
#if defined __USE_MISC || (defined __USE_XOPEN && !defined __USE_XOPEN2K)
#if !defined __cplusplus || __cplusplus < 201103L /* Conflicts with C++11.  */
 /* Return nonzero if VALUE is not a number.  */
 __MATHDECL_1 (int,isnan,, (_Mdouble_ __value)) __attribute__ ((__const__));
 #endif
#endif

5 Finally i fix the two header files to use c++ cmath instead. Then solve the compile error.
 \github.com\cockroachdb\c-protobuf\internal\src\google\protobuf\stubs\mathutil.h
#include <cmath>  //math.h to cmath
//add std prefix
#define DECL_FP_LIMIT_FUNCS \
  static bool IsFinite(const Type x) { return !std::isinf(x)  &&  !std::isnan(x); } \
  static bool IsNaN(const Type x) { return std::isnan(x); } \
  static bool IsInf(const Type x) { return std::isinf(x); } \
  static bool IsPosInf(const Type x) { return std::isinf(x)  &&  x > 0; } \
  static bool IsNegInf(const Type x) { return std::isinf(x)  &&  x < 0; }
#endif

\github.com\cockroachdb\c-protobuf\internal\src\google\protobuf\stubs\mathlimits.h
#include <cmath>  //math.h to cmath
template<>
inline bool IsNan(double value) {
#ifdef _MSC_VER
  return _isnan(value);
#else
  return std::isnan(value);//add std prefix
#endif

**Comment by petermattis** [comment]
@tamird Can you take a look at this? Do we need to upgrade our `c-protobuf` package?

**Comment by bdarnell** [comment]
This is the same as #7476. Our CONTRIBUTING.md states that GCC 6.0 or higher is required to build with GCC.

**Comment by tamird** [comment]
Indeed.
