### ISSUE TITLE
storage: pebbleIterator panics too eagerly on Close()

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#84396]
After hooking the new pebbleIterator into the restore processor (https://github.com/cockroachdb/cockroach/pull/83984), a few restore roachtests on master have been failing (https://github.com/cockroachdb/cockroach/issues/84240, https://github.com/cockroachdb/cockroach/issues/84237), because the pebbleIterator panics when it attempts to close, for example: 
```
panic: EOF                                                                      
    9                                                                                 
   10 goroutine 45749 [running]:                                                      
   11 panic({0x483a900, 0xc0000a4120})                                                
   12         GOROOT/src/runtime/panic.go:1147 +0x3a8 fp=0xc0061cb528 sp=0xc0061cb468 pc=0x48a828
   13 github.com/cockroachdb/cockroach/pkg/storage.(*pebbleIterator).destroy(0xc0039f0000)
   14         github.com/cockroachdb/cockroach/pkg/storage/pebble_iterator.go:897 +0x1e5 fp=0xc0061cb668 sp=0xc0061cb528 pc=0x17a61a5
   15 github.com/cockroachdb/cockroach/pkg/storage.(*pebbleIterator).Close(0xc0039f0000)
```
(see full example panic stack trace in[ comment](https://github.com/cockroachdb/cockroach/issues/84240#issuecomment-1182279432)).

In the failed tests and in repros, the panic reasons have been `EOF`, `Context cancelled`, and `nil`, which at a high level, makes me wonder if all this panicking is necessary. To get a better understanding of when the iterator panics, I ran the `restore/nodeShutdown/coordinator` roachtest on my gce-worker using master + a [commit](https://github.com/cockroachdb/cockroach/commit/bf79431f9169f8765c7aa659e20e02fdd628f541) that adds more logging related to the SSTs in the iterator and issues prints instead of panics in `pebbleIterator.destroy()`. 

I can explain and reproduce the `context cancelled` panic. When the restore fails for some independent reason, context cancellations circulates throughout the goroutines, leading to pebbleIterator.Valid() returning `!ok`  and a `context cancelled` error. This then leads to `defer.Close()`, surfacing the `context cancelled` error during `destroy()`, leading to a panic. To repro this, stress the `restore/nodeShutdown/coordinator` roachtest above, potentially with my augmented commit.

I'm not sure what causes the EOF or nil based panics. 
@erikgrinaker 

Jira issue: CRDB-17633

Epic CRDB-2624

**Comment by jbowens** [comment]
Hmm, I forgot that `MVCCIterator.Valid()` has an error return that uses `i.iter.Error`. I don't see why we can't rely on exclusively surfacing iteration errors through that.

**Comment by jbowens** [comment]
> the panic reasons have been `EOF`,

Is it possible we're wrapping `io.EOF` somewhere in the `vfs.File` implementation? Like the `io.EOF` godoc references, Pebble does perform an equality check comparison to `io.EOF` when reading the tail of a sstable. Wrapping could cause `io.EOF` to be treated as an error.

> EOF is the error returned by Read when no more input is available. (Read must return EOF itself, not an error wrapping EOF, because callers will test for EOF using ==.) Functions should return EOF only to signal a graceful end of input. If the EOF occurs unexpectedly in a structured data stream, the appropriate error is either ErrUnexpectedEOF or some other error giving more detail. 

where's the networked implementation of `vfs.File` live?

**Comment by msbutler** [comment]
In the PR I reverted, restore called `ExternalSSTReader()` to instantiate a `PebbleSSTIterator`, see [here](https://github.com/msbutler/cockroach/blob/4d1f66e12d174fb3bf59549c4f660931552ffc8d/pkg/ccl/storageccl/external_sst_reader.go#L103). 

The basic logic is:
- The caller passes an `externalStorage` interface, which `ExternalSSTReader()` uses to call `ReadFileAt`, returning a file handler ( `ioctx.ReadCloserCtx`). [Here's](https://github.com/msbutler/cockroach/blob/4d1f66e12d174fb3bf59549c4f660931552ffc8d/pkg/cloud/gcp/gcs_storage.go#L245-L249) is our GCS implementation of ReadFileAt.
- `ExternalSSTReader()` then binds the file handler to our `sstReader` struct, which implements `sstable.ReadableFile`, a subset of the `vfs.file` interface. 
https://github.com/msbutler/cockroach/blob/4d1f66e12d174fb3bf59549c4f660931552ffc8d/pkg/ccl/storageccl/external_sst_reader.go#L122-L130
- This readableFile is passed to the `PebbleSSTIterator`

Perhaps the new PebbleIterator doesn't play nice with the `sstReader`?
