### ISSUE TITLE
storage: BeginTransaction can't overwrite

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#8440]
In investigating #7940, I'm sometimes seeing the following error:

```
	client_test.go:795: change replicas of range 1 failed: BeginTransaction can't overwrite "change-replica" id=515bdd0b key=/Local/Range/""/RangeDescriptor rw=true pri=0.01308532 iso=SERIALIZABLE stat=PENDING epo=0 ts=0.000000000,55 orig=0.000000000,55 max=0.000000000,55 wto=false rop=false
		"change-replica" id=515bdd0b key=/Local/Range/""/RangeDescriptor rw=false pri=0.01308532 iso=SERIALIZABLE stat=PENDING epo=0 ts=0.000000000,55 orig=0.000000000,55 max=0.000000000,55 wto=false rop=false
```

Note that I've changed the error generated when this occurs to show both the existing transaction and the new transaction. As you can see above, the two transactions are identical. Are we trying to replay a `BeginTransaction` request? How and why is that happening?

@bdarnell Any thoughts on how this could happen? Is it problematic? It's currently killing the test because we don't expect the `ChangeReplicas` to be able to fail.

**Comment by petermattis** [comment]
There seems to be some issue with raft command processing. I can see the same BeginTransaction command proposed 35 times due to a `reasonTicks` refresh. Why isn't it going through?

**Comment by petermattis** [comment]
Analyzing one failure here. The first re-proposal happens:

```
I160810 15:11:09.623411 storage/replica.go:1811  store=1:1 range=1 [/Min-/Max): pending commands: refurbished 0, reproposing 1 (at 14.2); reasonTicks
I160810 15:11:09.623455 storage/replica.go:1544  store=1:1 range=1 [/Min-/Max): proposing command 6d7b2506f2f90b2f
```

Looking back in the log, we can see this command was originally proposed:

```
I160810 15:11:09.333954 storage/replica.go:1544  store=1:1 range=1 [/Min-/Max): proposing command 6d7b2506f2f90b2f
```

This command was initiated by a change replicas:

```
I160810 15:11:09.333727 storage/replica_command.go:3023  store=1:1 range=1 [/Min-/Max): change replicas of 1: read existing descriptor range_id:1 start_key:"" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
```

But this is actually the second replica addition for this range. The first occurred slightly earlier:

```
I160810 15:11:09.331515 storage/replica_command.go:3023  store=1:1 range=1 [/Min-/Max): change replicas of 1: read existing descriptor range_id:1 start_key:"" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
```

And this is where the problem starts. I can see the associated command for this change replicas get proposed and processed on node 1:

```
I160810 15:11:09.331805 storage/replica.go:1544  store=1:1 range=1 [/Min-/Max): proposing command 56d085a55d6a83f2
...
I160810 15:11:09.332049 storage/replica.go:1930  store=1:1 range=1 [/Min-/Max): processing command 56d085a55d6a83f2: maxLeaseIndex=1
```

But I never see it get processed on node 2 (the newly added replica). In fact, I see no other mention of the command in the logs. When things work normally, the command is received and processed by node 2. Still digging.

**Comment by petermattis** [comment]
Added instrumentation to grpc and discovered:

```
I160810 15:50:54.349673 http2_client.go:128  127.0.0.1:54295: dialed in 14677.5ms
```

Ugh, is this Mac OS X networking flakiness as well?

**Comment by bdarnell** [comment]
I think there are multiple ways in which a batch could get replayed, including kv.SendNextTimeout or similar retries in the DistSender. In general, replayed commands do not succeed. For regular commands this is a WriteTooOldError or similar, which causes the TxnCoordSender to retry. That's probably what we want to happen here. 

We could perhaps detect that the transaction is identical (similar to the way that EndTransaction{Commit: false} is idempotent}, but that seems dangerous because there is more than just the BeginTransaction in the batch, and we can't tell if DistSender's batch truncation logic produced the same results both times. 

So I think what we want to do is make that "can't overwrite" error (only for the PENDING case) return a different type of error (TransactionRetryError?) so the transaction will be restarted.
