### ISSUE TITLE
sql: better return type validation with user defined record type

### ISSUE THREAD

**Issue by chengxiong-ruan** [cockroachdb/cockroach#84407]
**Is your feature request related to a problem? Please describe.**
Currently we don't support user define record (tracked by #27792)type yet. So for user defined function, we have simple return type assertion (comparing one column type with function return type) as the only function body return type validation.
When we eventually support record type, the validation would be a bit more complicated because the last statement in function body could return more than one columns.

**Describe the solution you'd like**
Return type validation need to be able to compare multiple columns with record type.

Jira issue: CRDB-17638

**Comment by ajwerner** [comment]
On some level the `types.Equivalent` function for tuples should work just fine here, no?

https://github.com/cockroachdb/cockroach/blob/10a054b63d9403aa48ef2f7d7b3615a938879240/pkg/sql/types/types.go#L1898-L1912

**Comment by chengxiong-ruan** [comment]
talked offline that this ticket is not needed.
