### ISSUE TITLE
changefeedccl: Add a metric for size based flushes

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#84435]
We have metrics recoding flush related stats (number of flushes, duration), but
those only work when issuing explicit Flush request.

Some sinks (cloud storage) also flush based on other criteria (size) -- we should
add metrics to record those flushes as well.

Jira issue: CRDB-17659

**Comment by amruss** [comment]
Putting on the backlog for now as we have other prioritized work - lets pick this up later
