### ISSUE TITLE
docs-issue-generation: docs issues are not being created for commits with multiple release notes

### ISSUE THREAD

**Issue by jlinder** [cockroachdb/cockroach#84434]
**Describe the problem**

The docs-issue-generation program does not create docs issues for a commit with multiple release notes:

- #83107 is part of [this merge commit](https://github.com/cockroachdb/cockroach/commit/9dfdf1b2bb8214504e56ab9ab1c80dcb63edaa0a). It did not have a docs issue created for it. [This is the TeamCity run](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_CreateDocsIssue/5581261?buildTab=overview&showRootCauses=false&expandBuildChangesSection=true) for that merge commit.
- #83507 is the backport for #83107. It did not have a docs issue created for it. [It's merge commit](https://github.com/cockroachdb/cockroach/commit/98b0556dbb3c748b1f232d8eed95560c28764f6e) and [it's TeamCity run](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_CreateDocsIssue/5591603?buildTab=overview&showRootCauses=false&expandBuildChangesSection=true).

The logs for the TC runs that didn't create docs issues have no information about what it found.

**Expected behavior**

Docs issues should have been created for #83107 and #83507.

**Additional context**

It'd be great if the program could output some information about what it did to verify it's working as expected.

Jira issue: CRDB-17658

Epic DEVINF-261

**Comment by nickvigilante** [comment]
@jlinder https://github.com/cockroachdb/docs/issues/14376 was the docs ticket created for #83423. It was just closed shortly after opening by Stephanie. No issue there.

For #83507, there are two release notes within the commit message. Is that allowed practice to include 2 release notes in the same PR? My intuition tells me no.

**Comment by jlinder** [comment]
Hey @nickvigilante. 

Ah. We missed seeing https://github.com/cockroachdb/docs/issues/14376 in the initial investigation.

Yes, it's possible for multiple release notes to be present in a commit and for multiple commits in a PR to have release notes. Take a look at the [General structure of a commit message](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages#General-structure-of-a-commit-message) section of the [Git Commit Messages](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73072807/Git+Commit+Messages) wiki page and the [Release notes](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/186548364/Release+notes) wiki page for information on how release notes work.
