### ISSUE TITLE
sql/logictest: use of a closed engine's FS can result in a goroutine leak; TestLogic flaky

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#84437]
**Describe the problem**

A Pebble change in #81389 uncovered a handful of tests where an engine's filesystem (FS) is used after it is closed, which can result in goroutine leaks. This can increase the test flake rate.

There are two main paths to addressing. Option A - Eliminate the use of the FS after it is closed (preferable, but unclear how much refactoring / yak shaving is required). Option B - make use of the `DisableFilesystemMiddlewareTODO` engine option as a temporary workaround to bypass the code in Pebble that tickles the leak.

Related issues / comments:
- https://github.com/cockroachdb/cockroach/issues/81413
- https://github.com/cockroachdb/cockroach/pull/81389
- https://github.com/cockroachdb/cockroach/pull/83757#issuecomment-1184482709

Jira issue: CRDB-17660

**Comment by nicktrav** [comment]
@yuzefovich - are you able to help triage this? I assume one of the `{A,T}-sql-*` labels?

**Comment by yuzefovich** [comment]
[Linking](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/5747110?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true) one of the flakes from the other issue. Probably the action item here is to first logic tests with `-v --show-sql` (possibly under stress) so that we know which of the logic test files leaks the goroutine.

**Comment by rytaft** [comment]
Action item: reproduce more deterministically to understand where the leak is coming from

**Comment by yuzefovich** [comment]
Ran into a leak in one of the CI [builds](https://teamcity.cockroachdb.com/viewLog.html?buildId=5835982&buildTypeId=Cockroach_UnitTests) on `TestTraceAnalyzer` (I don't think that the changes on my branch are to blame).

**Comment by rytaft** [comment]
@nicktrav are the disk health checks still running? We haven't seen a failure recently. Can we close this?

**Comment by nicktrav** [comment]
@rytaft - I think we probably can, yes. We still have [`DisableFilesystemMiddlewareTODO`](https://github.com/cockroachdb/cockroach/blob/003c0360de8b64319b5f0f127b99be91dbdca8a3/pkg/storage/open.go#L65-L72) that's suppressing some failures elsewhere. I'm going to remove that in a branch now and see what else fails. I will create separate tickets, if required.
