### ISSUE TITLE
Add create_date to our index usage statistics telmetry

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#84458]
We [added a create_date to crdb_internal.table_indexes](https://github.com/cockroachdb/cockroach/issues/72626). We should capture this piece of information in our telemetry channel as well for index usage statistics.

Related PR that added index usage statistics: https://github.com/cockroachdb/cockroach/issues/72486

Jira issue: CRDB-17669

**Comment by pransudash** [comment]
Could we also add the `database_id` if that exists? Currently we get the `database_name, table_name, table_id, index_name, index_id` but in many cases the database_name is redacted and we can't uniquely identify an index if two tables have the same name (since the `database_name` would be `'<x>'`)

**Comment by kevin-v-ngo** [comment]
Unfortunately we ran into a few complications adding the database_id potentially impacting the customer workload. But we should have already unredacted the database_name. Can you confirm @THardy98?

**Comment by pransudash** [comment]
yeah I see database_names in the latest data. Just wanted to make sure you were aware of potential issue with historical data
