### ISSUE TITLE
ui: surface `PausedReplicas` in DB Console

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#84489]
In #83851, we added a concept of "paused replicas". If a Raft follower's Pebble store is overloaded, then the leaseholder will temporarily pause replication to that follower until Pebble recovers (assuming we can still maintain a quorum).

The number of currently paused replicas is surfaced via the status server's range info as `RangeInfo.paused_replicas`:

https://github.com/cockroachdb/cockroach/blob/43a37d54a4fd6630176fd67c50a391975c2abb09/pkg/kv/kvserver/kvserverpb/state.proto#L187

And via the metric `admission.raft.paused_replicas`:

https://github.com/cockroachdb/cockroach/blob/43a37d54a4fd6630176fd67c50a391975c2abb09/pkg/ts/catalog/chart_catalog.go#L567-L572

We should surface this in the DB Console, e.g.:

* Display it in the range report.

* Display it in the problem ranges report, which requires extending the `ProblemRanges` API call with a new response field `PausedFollowers` and populating it.
    https://github.com/cockroachdb/cockroach/blob/8b0776410b74e9449461c856439aa773e47c3529/pkg/server/serverpb/status.proto#L1176
    https://github.com/cockroachdb/cockroach/blob/0ffc720da46640ab47b6c34614082de22b0a27d6/pkg/server/problem_ranges.go#L93

* Display it in the replication metrics, either on an existing chart or a new one.

* Other places?

Jira issue: CRDB-17690

**Comment by erikgrinaker** [comment]
CC @cockroachdb/replication.

**Comment by tbg** [comment]
Just wanted to point out that the paused follower metric is populated on the leaseholders. So if s3 is overloaded, we expect *other* stores to register nonzero values on the paused follower metric, since they are doing the pausing.

We could add a metric that basically just indicates whether a store is pausable (reported by the store itself). This is basically just a metric that reports `int(iothreshold.Score > configured_pausable_threshold_cluster_setting)`.

On a related note, I think something like this is also lacking for IO admission control (which triggers at iothreshold score 1).

**Comment by Santamaura** [comment]
What is the simplest way to simulate pausing replicas?

**Comment by tbg** [comment]
@Santamaura one reliably way is to rebase on top of https://github.com/cockroachdb/cockroach/pull/81516 and then invoke the roachtest like this:

```
export GCE_PROJECT=andrei-jepsen &&./pkg/cmd/roachtest/roachstress.sh -c 1 -u admission/follower-overload/presplit-with-leases -- --debug
```

The roachtest will "fail" after a few minutes but it will leave the cluster running with load against it. You can then navigate to the fourth node, port 3000, log in with admin:admin and then dashboards -> browse to open the one dashboard that exists. You will find a graph of pausable replicas there. As the "L0 threshold" graph crosses 0.8, you will see paused replicas. (This might take an hour or two, but once it's there it'll periodically be the case).
