### ISSUE TITLE
Create a separate role (other than admin) to allow users to reset SQL stats

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#84499]
Resetting SQL stats for Statements and Transactions  requires the Admin role. This issue tracks creating a separate role (other than admin) to allow users to reset SQL stats.

Related [issue](https://github.com/cockroachdb/cockroach/issues/83473) where we should leverage the new RBAC extension framework.

Jira issue: CRDB-17693

**Comment by maryliag** [comment]
No longer a priority
