### ISSUE TITLE
changefeedccl: More resilient core changefeeds

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#84511]
Core style changefeeds (w/out sink) are not as resilient as enterprise changefeeds.
The primary reason is that core style changefeeds do not checkpoint their progress
to the jobs table.

However, we can improve (possibly significantly) core style feeds resilience to
transient errors (e.g. writing to a sink) or transient blips in a cluster
(node restarts other than the coordinator) by simply taking checkpoint information
and using in-memory checkpoint records when retrying.

Jira issue: CRDB-17697

Epic CRDB-8719

**Comment by ajwerner** [comment]
Another aspect where "sinkless" changefeeds are deficient is that they don't know how to "restart" in the face of a schema change. Whenever a primary index change occurs on a table, we need to re-plan the distsql flow. Today we unconditionally return an error to sinkless feeds. It'd be cool if we could make them robust to these restarts. I suspect it'll happen somewhat transparently if you're adding a loop above the execution of the statement.

**Comment by jayshrivastava** [comment]
Adding this: https://reviewable.io/reviews/cockroachdb/cockroach/84674#-N7XELpSBkcZKerWmuG0. Some changefeed tests disable declarative schema changes. This disables primary index changes for some DDLs, which avoids errors that should pop up when testing with sinkless changefeeds.

**Comment by amruss** [comment]
This may get pushed into next release depending on capacity
