### ISSUE TITLE
sql: a transaction restarted because of TransactionAbortedError gets a stale OrigTimestamp causing it to be restarted again

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#8456]
Fun happens when you troll logs; spent forever tracing this doozy: we have a mechanism for tying the timestamp returned by the SQL builtin `cluster_logical_timestamp()` to the HLC. It's based on the executor setting `opt.MinInitialTimestamp`, which is then used by the `client.Txn` to initialize a txn's `OrigTimestamp`, which is then used by the `txn_coord_sender` to init a txn's timestamp.
https://github.com/cockroachdb/cockroach/blob/c536df4a669fdeb8511114b53536fd6e25b022f5/internal/client/txn.go#L549

The code above intends to only do this initialization for "brand new transactions". The problem is that it fails to do so - transactions that are retried because the previous iteration encountered a `TransactionAbortedError` pass the "brand new transaction" test because their proto has been wiped by `txnSender.Send()`. So this means that we get a transaction that has been restarted with an `OrigTimestamp` that's stale. When the transaction runs, it gets an updated timestamp, and so when it gets to `EndTransaction` time, it looks to that raft code like the transaction has been pushed. And so `EndTransaction` returns a `TransactionRestartedError` which causes the transaction to be restarted yet again.

I'm not sure what the correct solution is here. I've been tracing through the different PRs around when this `MinInitialTimestamp` was introduced, and I'm still unsure about what exactly we're trying to achieve with this `cluster_logical_timestamp()` fun. I gather that we want it to serve as "monotonically increasing SQL timestamps (in the same order as txn commit order)", but did we achieve that? For clients using a single SQL gateway node, other functions such as `transaction_timestamp` are already monotonic, right? And when you're not using a single gateway, this mechanism only gives you monotonic times for txns interact (in fact even worse; even for txns that "interact", the cluster_time value for the last one of them will be correct only on the last retry, when the txn actually commits). So I'd like to hear a bit on what the thinking with this function was, and how someone is supposed to use it. There's now also https://github.com/cockroachdb/docs/issues/539 requesting documentation.
https://reviewable.io/reviews/cockroachdb/cockroach/5037
https://reviewable.io/reviews/cockroachdb/cockroach/5805
https://github.com/cockroachdb/cockroach/pull/5915

Perhaps the solution is for the `txnSender.Send()` to initialize the `OrigTs` to something, but I'm not sure if it should be some time from the error or the local clock (which is not currently available to the `txnSender`).  Or perhaps `MinInitialTimestamp` should only be used by `Txn.Exec()` on the first try of a txn (but then `cluster_logical_timestamp` panics because it doesn't have a timestamp to serve - also see https://github.com/cockroachdb/cockroach/issues/8455)

**Comment by knz** [comment]
So the situation is rather easy, 

1) the goal of this function is to provide a timestamp that, for any pair of overlapping transactions, increases in the same order as txn commits. 
If a transaction gets pushed by another and this results in the pushed txn committing *after* the one that pushed it, then its logical timestamp as visible to `cluster_logical_timestamp` should be also beyond the pusher's. I thing the txn attribute that most closely matches this requirement is the plain "Timestamp" field, please correct me if that's wrong.

2) The first implementation of the function was sampling a timestamp field in the proto. However the reason why this is not any more so, and why instead we have a MinInitialTimestamp, is that a SQL query can use this function before the txn proto has been initialized -- a txn proto only gets created upon (IIRC) the first write.

**Comment by knz** [comment]
(I edited my last comment after I submitted it the first time)

**Comment by knz** [comment]
Unassigning since I'm not working on this until next week. Feel free to reassign if it can wait until then.
