### ISSUE TITLE
storage: use ClearMVCCRange when GC-ing multiple versions under range tombstones

### ISSUE THREAD

**Issue by aliher1911** [cockroachdb/cockroach#84560]
When the whole range content is removed during GC we would issue point deletes for every value found. This is wasteful as we may use `ClearMVCCRange` and related operations when doing so.

To do this, we should change GC to issue new types RangeDeletion requests that would put pebble range tombstones instead of individual deletes.

Note that new request field or request type is needed to ensure we could put proper latches as it would be possible to remove newer data. And this wouldn't not be compatible with latchless GC, but that is fine as ranges subject to complete deletion are unused and are not supposed to get recent writes.

Jira issue: CRDB-17736

Epic CRDB-20465

**Comment by erikgrinaker** [comment]
>Note that new request field or request type is needed to ensure we could put proper latches as it would be possible to remove newer data.

Don't we already take out a write latch when GCing MVCC range tombstones? Do we need anything more than that?
