### ISSUE TITLE
server: ensure nodelocal works for secondary tenants (gated by capability) [CRDB-14537 followup]

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#84588]
Shared-memory tenant servers should have access to nodelocal storage.

Jira issue: CRDB-17751

Epic CRDB-23559

**Comment by dt** [comment]
I believe we discussed this and concluded we do _not_ want this behavior after all: 
`nodelocal` storage is not tenant specific but rather the *node*local storage is an attribute _of the node_, which it exposes or not to those tenants who are authorized to use it, in the same way an s3 bucket is just a bucket, accessible to those callers who are authorized, but is still the same bucket to all (authorized) callers. If you put a file at path `x` in some s3 bucket y, any caller will see the that file if they have permission when they access `s3://y/x`, similarly if you put a file `x` in the external IO dir of node `y`, then any tenant with permission to access nodelocal storage should see that file at `nodelocal://y/x`. We define the external IO dir as _external_, including being external to tenant model.

**Comment by knz** [comment]
I reason this a bit differently:
- yes, the disk space is collectively shared;
- however, multi-tenancy is about _starting with partitioned access_ and then opting carefully into sharing when it makes sense.

So my reasoning is that 1) the default for nodelocal should be separate locations 2) an operator should be able to provision, separately and opt-in,  a shared portion of nodelocal storage shared across nodes.

Your analogy with S3 is flawed: with s3 I can configure that different tenants have access to separate buckets. With your proposal, we can't do that with nodelocal. My contention is that we should.

**Comment by knz** [comment]
@stevendanna  reminded me we have userlocal as well. So we can make nodelocal shared -- and I retract my argument.

Let's rename the issue to "make nodelocal work" and make the PR close it.
