### ISSUE TITLE
scop: audit operation names

### ISSUE THREAD

**Issue by postamar** [cockroachdb/cockroach#84583]
Declarative schema changer operation names and their field names are mildly inconsistent. For instance we have a pattern where index state changing ops are named `MakeBackfilledIndexMerging`, `MakeBackfillingIndexDeleteOnly`, etc. but we also have `MakeAddedIndexDeleteAndWriteOnly` which doesn't conform to the pattern. As far as fields are concerned we have a mix of `DescID`, `DescriptorID` etc. 

None of this matters in any other way than: this stuff shows up in `EXPLAIN (DDL)` output. Let's make it consistent in time for this release. It shouldn't be hard or take long, but will result in noisy test changes.

Jira issue: CRDB-17746

**Comment by postamar** [comment]
Reopening because this needs to be backported to 22.2

**Comment by Xiang-Gu** [comment]
Closing this issue because the backport is completed!
