### ISSUE TITLE
jobs: prevent table drop with running jobs unless using CASCADE

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#84595]
Today, we do not have a clear story of what happens with jobs when a user drops a table. In some situations, the table drop can succeed, but a paused job can block data from being garbage collected.

We should adopt the following user flow:
-> User attempts to drop table with a paused or running job
Table drop does not succeed, with a warning  “Please cancel jobs [job id list] associated with table before dropping the table, or cascade, will drop jobs ”
-> User attempts to drop a table with CASCADE with a paused or running job
Table drop succeeds, with a warning “All jobs associated with this table have been canceled ”, all associated jobs are canceled

Jira issue: CRDB-17755

**Comment by amruss** [comment]
With schedules - there is no job, but there can be a protected timestamp that could never move, that is not associated with a job.. we should deal with this as well

**Comment by amruss** [comment]
One counter situation: You backup at 3pm, drop a table at 3:05, you still want the table to drop AND the table to be included in the backup

**Comment by amruss** [comment]
Closing this for now, @vy-ton curious to hear your opinion if there is something we want to do on the schema side to better attribute jobs/schedules/etc to tables

**Comment by vy-ton** [comment]
cc @devadvocado for future thinking here from Schema
