### ISSUE TITLE
kvserver: export per-store metric for number of invalid leases

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#84656]
**Is your feature request related to a problem? Please describe.**

When debugging lease placement issues, it's instructive to look at the count for the number of raft leaders that aren't leaseholders. That metric however skips over replicas that hold invalid leases, which can mask the problem of a store holding a set of invalid leases and those leases not being actively acquired elsewhere. We saw this in https://github.com/cockroachlabs/support/issues/1697.

https://github.com/cockroachdb/cockroach/blob/5e53f0171a504b6d920f9dbaa629987901be91bd/pkg/kv/kvserver/store.go#L3167-L3169

**Describe the solution you'd like**

Exporting the number of invalid leases held per-store would help.

Jira issue: CRDB-17787

**Comment by ajitalyana** [comment]
Can I try my hand at this?

**Comment by irfansharif** [comment]
yup, feel free to send a PR!

**Comment by quanuw** [comment]
Hi @ajitalyana @irfansharif, is this issue still in progress? If not, can I work on it?

**Comment by quanuw** [comment]
@rafiss @irfansharif @ajitalyana Hello, can I look into this issue if no one is working on it?

**Comment by ajitalyana** [comment]
@quanuw currently I am not working on it. Go ahead

**Comment by quanuw** [comment]
@ajitalyana Thanks for confirming, I can work on this.
