### ISSUE TITLE
ui: add typings for moment

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#8469]
Moment typings are currently missing and it doesn't seem 100% straightforward to add.

@mrtracy I'm guessing you encountered this?

**Comment by maxlang** [comment]
Hmm, nevermind, I see they're pulled in elsewhere.

**Comment by tamird** [comment]
moment's typings are in the moment repo
https://github.com/moment/moment/blob/develop/moment.d.ts

They definitely aren't missing, or else our stuff wouldn't compile. See
also https://github.com/cockroachdb/cockroach/blob/5e3486d/ui/config.js#L60
