### ISSUE TITLE
changefeedccl: reduce size or # of pointers of event struct

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/cockroach#84709]
We’ve discovered that foreground SQL latency can be [affected by changefeed backfills](https://github.com/cockroachdb/cockroach/issues/84582) (initial scans and catchup scans). Let’s see if we can reduce the size of [this struct](https://github.com/shermanCRL/cockroach/blob/master/pkg/ccl/changefeedccl/kvevent/event.go/#L89-L100).

@nvanbenschoten mentions that it might be a small as key, current value and previous value -- down to 3 pointers instead of the current 10.

Jira issue: CRDB-17821

**Comment by ajwerner** [comment]
Another way to reduce allocations would be to change the `bufferEvent` which is a linked-list node to be allocated from a block and instead store a linked-list of blocks. That'll both reduce pointers and reduce allocations.

**Comment by shermanCRL** [comment]
@miretskiy points out that most of these pointers come from rangefeeds, and so “we” are not responsible for those, they are already allocated. Other members are values, not pointers.

What’s left is the `Alloc` member which has a map that may be getting initialized too eagerly and repeatedly, so there may be something to be done there. We might also look at the `next` pointer, does this need to be a linked list, could it be a slice?

**Comment by nvanbenschoten** [comment]
There are some other pointers that could probably be eliminated.

`Event.bufferAddTimestamp` is a `time.Time`, which contains a pointer. Consider storing the `UnixNano() int64`.

`Alloc.ap` is an interface, which contains two pointers. Do we need to store this in each `Event`?

> We might also look at the next pointer, does this need to be a linked list, could it be a slice?

I don't think a slice is the right choice for this data structure, but a chunked linked-list (see https://github.com/nvanbenschoten/cockroach/commit/8d0d81cafe6302eee89a5a9083738c8949472955, similar to a `std::deque`) might be.

**Comment by ajwerner** [comment]
How should we evaluate any changes we make here?

**Comment by jayshrivastava** [comment]
Some more ideas:

- Use a `[3][]byte` to store the `key`, `value`, and `prevValue` associated with KV events. For resolved events, we can store the `startKey` and `endKey` in the same array. 
- Use a `[3]int` for timestamps.
- Use a bitmask or integer field for the type of event (KV, Flush, Resolved right now, but we can probably include all types of resolved events)

Reducing the amount of nested structs seems like the most valuable thing to do in terms of minimizing mark & sweep time.
