### ISSUE TITLE
descs: cache collection's catalog with all descriptors

### ISSUE THREAD

**Issue by jasonmchan** [cockroachdb/cockroach#84719]
The collection performs expensive in-memory construction of an `nstree.Catalog` to serve `GetAllDescriptors`. This procedure is problematic when there are many descriptors.
https://github.com/cockroachdb/cockroach/blob/324554837cd5d72dcb4bead4c82fdcf67618ba60/pkg/sql/catalog/descs/stored_descriptors.go#L395-L419

On repeated calls to `GetAllDescriptors`, this work is wasted if descriptors have not been written to. Prior to #84442, we would not do this work because the `nstree.Catalog` was cached. The fix is simple: we should add back this caching behavior by saving the constructed catalog and invalidating the cached catalog upon writing a descriptor.

Jira issue: CRDB-17828

**Comment by postamar** [comment]
I think we can reasonably consider this as fixed now.
