### ISSUE TITLE
dev: `dev doctor` broken inside worktrees

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#84739]
```
./dev doctor     
=============================
=== RUNNING DOCTOR CHECKS ===
=============================
ERROR: unlinkat .git/hooks: not a directory
```

This will fail in a `worktree` as `.git` exists but is not a directory, so `.git/hooks` can't refer to anything. We unconditionally destroy then re-create this directory when running `dev doctor`. This is incorrect -- if in a `worktree`, we should probably find the path to the actual `git` repo and create the directory there.

Epic CRDB-15061

Jira issue: CRDB-17838

**Comment by irfansharif** [comment]
Fixed in #84755.
