### ISSUE TITLE
migrations: Add option to ignore leading whitespace on enum values

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#84735]
It was observed recently that in one instance of a DMS driven migration from MySQL, that some of the dumped enum values contained leading spaces (i.e. some of the values were dumped correctly as 'XXXX' and others were dumped as '  XXXX').  Since the enum value with leading spaces is meant to be interpreted as the value without leading spaces, we may want to consider ignoring leading spaces on enum values.

@rafiss mentioned that our CSV parser provides the option to ignore leading spaces, so perhaps this would be an easy fix to tuck behind a cluster setting.

Jira issue: CRDB-17835

**Comment by otan** [comment]
I'm not sure we should do anything *just* yet - I'm not sure how the user managed to get into this state in the first place. MySQL stores enum values as integers so it should never have that space in it, my guess is this is a result of a MySQL inconsistency.

**Comment by ajstorm** [comment]
Agreed.  Just opened for tracking for now.

**Comment by ajstorm** [comment]
Closing.  Will reopen if we encounter it again.
