### ISSUE TITLE
changefeedccl: faster way to assert terminal error in tests

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#84736]
The changefeed test helper requireErrorSoon() relies on the TestFeed.shutdown channel being closed by TestFeed.Close(), which can be slow. It might be faster to short-circuit it somewhere, e.g. by adding an On[Changefeed]JobFail testing knob.

Jira issue: CRDB-17836

Epic CRDB-24727

**Comment by miretskiy** [comment]
@HonoreDB is this still an issue? The shutdown channel is closed when there is an error;
it is currently not closed if the job terminates with okay state.  Is this what you want?

Feel free to close if you're not planning on working on this.
