### ISSUE TITLE
Do not generate a new plan gist when there are changes to LIMIT

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#84745]
We create a new plan gist when there are changes to the LIMIT value. We should change this behavior as we have seen workloads generate hundreds of distinct plan gists per statement fingerprint. One potential approach is to encode a boolean indicating whether a LIMIT was applied (instead of the value).

[Related thread
](https://cockroachlabs.slack.com/archives/C03K24HDCUB/p1658269926412349?thread_ts=1658261587.113149&cid=C03K24HDCUB)

Jira issue: CRDB-17842

**Comment by rytaft** [comment]
Dup of https://github.com/cockroachdb/cockroach/issues/84842
