### ISSUE TITLE
importccl,backupccl: use `crdb_internal.invalid_objects` to check for invalid descriptors

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#84757]
SQL Schema have a virtual table to check for invalid descriptors in a cluster. Restore and import are in the business of creating and ingesting descriptors, and so we should check the virtual table post restore/import for any invalid descriptor states they might have generated. This should be added to as many restore/import tests as possible, but also potentially as a sanity check during a restore/import once the descriptors have been published to an online state.

Jira issue: CRDB-17847

**Comment by msbutler** [comment]
As discussed in detail [here](https://github.com/cockroachdb/cockroach/pull/91250#issuecomment-1316953914), there's no need for restore to conduct manual descriptor validation, as the sql description collection read/write machinery does it for us. Will close this issue out, once I add a test that verifies this fact.
