### ISSUE TITLE
Remove multi-tenancy function from generated function doc

### ISSUE THREAD

**Issue by stbof** [cockroachdb/cockroach#84756]
**Describe the problem**

We don't document multi-tenancy features in the public docs: https://www.cockroachlabs.com/docs/stable/functions-and-operators.html#multi-tenancy-functions.  Either remove the function  `crdb_internal.sql_liveness_is_alive` added in https://github.com/cockroachdb/cockroach/pull/51087 or recategorize it. There's also a typo in the definition:

Checks is given sqlliveness session id is not expired -> Checks if given sqlliveness session id is not expired

Jira issue: CRDB-17846

**Comment by knz** [comment]
cc @rafiss for triage
