### ISSUE TITLE
sql: gists contain hard limit which is too much information

### ISSUE THREAD

**Issue by cucaroach** [cockroachdb/cockroach#84842]
There's no real value in gists for identical queries that only vary by limit amount being different.  Instead we should encode zero or one based on whether a limit is there.

Jira issue: CRDB-17910

**Comment by michae2** [comment]
@vy-ton and @kevin-v-ngo should we prioritize this for 22.2?

@mgartner asks, would this need a new version?
@cucaroach says not necessarily, if you use 0 or 1

**Comment by vy-ton** [comment]
@mgartner Not sure I understand the new version question?

**Comment by kevin-v-ngo** [comment]
It would be great if we can prioritize this for 22.2. Especially as we're now relying on the gist for internal analytics and detecting plan changes (regressions) as insights in the console. 

This also impacts the usability of the console view (the page becomes unwieldy with hundreds of plans) and crdb_internal (we hit the 1M retention alot sooner).

**Comment by mgartner** [comment]
Sounds good. Moving to the Up Next bucket.
