### ISSUE TITLE
server, ui: audit apis and ui for liveness entries

### ISSUE THREAD

**Issue by Santamaura** [cockroachdb/cockroach#84852]
**Is your feature request related to a problem? Please describe.**
Resulting from discussion on https://github.com/cockroachlabs/support/issues/1698 some endpoints do not use an accurate source for node liveness. This can cause incorrect data to be shown on the admin ui. UI components should also consider cases where liveness related data may be missing.

**Describe the solution you'd like**
An audit of liveness apis that serve the dashboard and the ui selectors/presentational components that manipulate and display liveness related data.

**Describe alternatives you've considered**
N/A

Jira issue: CRDB-17917

**Comment by erikgrinaker** [comment]
Here's some additional context. We've long struggled with different UIs (web and CLI) wrongly considering decommissioned nodes to still be part of the cluster. There is exactly one condition that determines cluster membership:

A [`Liveness`](https://github.com/cockroachdb/cockroach/blob/04e7149928cd9e5e41a7c6f7c3ea8466677aeec0/pkg/kv/kvserver/liveness/livenesspb/liveness.proto#L23) record with  [`Membership`](https://github.com/cockroachdb/cockroach/blob/04e7149928cd9e5e41a7c6f7c3ea8466677aeec0/pkg/kv/kvserver/liveness/livenesspb/liveness.proto#L57) not set to `DECOMMISSIONED`, stored in KV under the key [`NodeLivenessKey`](https://github.com/cockroachdb/cockroach/blob/c5497ba4758c55cfb7be120c882a811f187d7513/pkg/keys/keys.go#L155).

These records can be read from KV itself, or via the SQL table `crdb_internal.kv_node_liveness`.

Node information is also stored in several other places. The problems arise when various APIs and UIs use this other information without checking against the KV liveness entry, but simply assume that if we have info about a node then it must be part of the cluster. They are:

* The node status entry, stored in KV under [`NodeStatusKey`](https://github.com/cockroachdb/cockroach/blob/c5497ba4758c55cfb7be120c882a811f187d7513/pkg/keys/keys.go#L164) and accessible via the SQL table `crdb_internal.kv_node_status`. The existence of a liveness entry does not imply the existence of a status entry, and vice-versa. From 21.1 we attempt to remove the status entry when we decommission a node, but entries may be left behind from previous versions, and the removal is best-effort as it is a non-transactional value.

* Gossiped liveness data, available via `crdb_internal.gossip_liveness` as well as `crdb_internal.gossip_nodes`, which may be incomplete or stale.

* Each node's [in-memory cache](https://github.com/cockroachdb/cockroach/blob/eeb72360fe8e5bdc9ed123612c4e71b975b52124/pkg/kv/kvserver/liveness/liveness.go#L209-L243) of gossipped liveness records.

Additionally, the liveness info (either originating from KV or in memory) can be translated into a [`NodeLivenessStatus`](https://github.com/cockroachdb/cockroach/blob/04e7149928cd9e5e41a7c6f7c3ea8466677aeec0/pkg/kv/kvserver/liveness/livenesspb/liveness.proto#L107-L138) by [`storepool.LivenessStatus`](https://github.com/cockroachdb/cockroach/blob/44884454824c5892cacaa83cbfd4bb75edc4c258/pkg/kv/kvserver/allocator/storepool/store_pool.go#L133-L180). Unfortunately, this uses a different determination for node membership, as described in the comments.

We have to make sure that APIs and UIs that need to know whether a node is a member of the cluster or not determines this based on the liveness entry from KV (not from gossip or in-memory caches) and it's membership field. It's fine to also use all of this other information (taking into account that it may be stale or incomplete and vary between nodes), but it must be cross-referenced against the canonical liveness entry in KV.

This is all a bit of a mess, so it would be really lovely if someone had the spare cycles to clean it up.
