### ISSUE TITLE
sql/sem/tree: Write tests for deep-cloning a tree.Statement 

### ISSUE THREAD

**Issue by Xiang-Gu** [cockroachdb/cockroach#84908]
We currently use the "round-trip" technique to deep-clone a tree.Statement: tree.Statement --> serialized string --> parse that string back to a tree.Statement, as described in the context section of the sister issue #84907.

In that issue, we discovered and reported a format bug where the serialization process did not "faithfully" serialize all components in that tree.Statement. This issue is opened to collect testing ideas and tracking the progress of having tests around this "round-trip" to ensure that the "round-trip" indeed gives us back an exact "clone" (i.e. no more nor no less info in the cloned tree.Statement).

Jira issue: CRDB-17944

**Comment by ajwerner** [comment]
I think we do have some amount of parser round-trip testing. I believe we do this for every statement that goes through the logictest framework. We should also do this for every statement that we use in our schemachange tests. See https://github.com/cockroachdb/cockroach/blob/58d6cba5359f922857dd08bd83d721b2577722df/pkg/testutils/sqlutils/pretty.go#L22. Let's have this issue just be for adding that call to our EndToEnd and Build suites.
