### ISSUE TITLE
storage: create PutRawMVCCRangeKey method

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#84919]
BACKUP currently uses `PutRawMVCC` quickly copy MVCC Kvs into a Backup SST, and as of #84875, Backup will use `PutMVCCRangeKey` to copy over rangekeys. A faster alternative to `PutMVCCRangeKey` would be `PutRawMVCCRangeKey`, but it doesn't exist yet! 

Jira issue: CRDB-17948

**Comment by erikgrinaker** [comment]
Dupe of #84896
