### ISSUE TITLE
kv: slow gossip iteration can block foreground requests

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#84943]
In a support escalation (https://github.com/cockroachlabs/support/issues/1709) for a v21.1 cluster, we saw that [leaked gossip entries](https://github.com/cockroachdb/cockroach/blob/9e1e2235a05ab0b2a77f917ba7bce303f6b8fe4a/pkg/sql/stats/new_stat.go#L112-L119) could impact foreground latency. The gossip leak itself has [since been fixed](https://github.com/cockroachdb/cockroach/commit/d07b32db3e49e91a438619586534b3ccc9813bcc), but the general problem remains — gossip processing should never block foreground requests.

Here's the chain of mutex acquisition that we believe allowed this to happen:
1. request attempts to acquire `replica.mu.RLock` in `maybeInitializeRaftGroup`
2. this is blocked on `replica.mu.Lock` in `updateProposalQuotaRaftMuLocked`
3. this calls `Dialer.ConnHealth`, which attempts to resolve a nodeID to a network address using an `AddressResolver` impl
4. the default implementation of `AddressResolver` is `gossip.AddressResolver`, which calls `gossip.GetNodeIDAddress`
5. this attempts to acquire `Gossip.mu.RLock`
6. this is blocked on `Gossip.mu.Lock`, which is slow because it calls `visitInfos` and iterates over all gossip infos

There are two (and a half) ways to address this. I think we might want to do both:
1. `Dialer.ConnHealth` should not acquire the gossip RLock through `gossip.GetNodeIDAddress`, at least not on the happy path. There are tricks we could play here with atomics to avoid this.
2. `updateProposalQuotaRaftMuLocked` should not call `Dialer.ConnHealth`. It's already checking `isFollowerActiveSince`. If a connection is unhealthy, `isFollowerActiveSince` will quickly detect that. Independent of this issue, I would suggest that we push on this as a way to speed up `updateProposalQuotaRaftMuLocked`, because it's too expensive right now.
3. (maybe) stop acquiring `replica.mu.Lock` in `updateProposalQuotaRaftMuLocked`. I was starting to drive towards that with https://github.com/cockroachdb/cockroach/pull/84160 and think it's possible.

Jira issue: CRDB-17962

**Comment by erikgrinaker** [comment]
Thanks for digging into this @nvanbenschoten. We already have #84202 to get rid of the `ConnHealth` call, it will be Pavel's starter project when he joins next week.
