### ISSUE TITLE
changefeedccl: support a region allowlist for emitter nodes

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#84969]
Proposed spec: `WITH emit_from_regions='comma,separated,list'` causes the changefeed to only create changefeed aggregator* processes on nodes from those regions. If any range doesn't have a replica in any of the regions, the changefeed fails.

This is a more useful primitive now than it used to be. Combining this with changefeed predicates that are pushed into the optimizer, you can create fully region-pinned changefeeds for efficiency/data domiciling. Combining this with super regions, you can create a "replica region" for each region consisting only of non-voting replicas, and restrict a changefeed to those regions to ensure that changefeeds can't interfere with foreground traffic.

We may want to do a timeboxed investigation of whether this is easy enough to be worth doing (versus implementing smarter versions of those two use cases directly). It looks easy to me, just implement a [Replica Oracle](https://github.com/cockroachdb/cockroach/blob/0050edb74f6c57ac389e7d02e72eadeebcf16f5d/pkg/sql/physicalplan/replicaoracle/oracle.go) that passes a filtered-by-region slice of candidates to a BinPackingOracle.

*Ideally the other changefeed processes would be pinned the same way, but that might be extra complexity for not so much benefit.

 

Jira issue: CRDB-17977

Epic CRDB-21737

**Comment by amruss** [comment]
Notes: could use something like zone configs instead to accomplish this (instead of a with option)
