### ISSUE TITLE
multiregion: properly assert the emission of structured logging events in tests

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#84984]
**Describe the problem**

The `system.eventlog` mechanism is slated for removal in v23.1 (#84983). Yet the multi region test in 
`pkg/ccl/logictestccl/testdata/logic_test/multi_region` still uses it to assert the output of a structured logging event.

**Expected behavior**

The test should assert that a structured event was emitted on the SQL_SCHEMA logging channel.

Jira issue: CRDB-17985

**Comment by knz** [comment]
cc @ajstorm for triage.

**Comment by ajstorm** [comment]
Putting this on the SQL Experience board for now, as last I checked, they owned this test.  @rafiss feel free to send this back to multi-region if you disagree, and I'll try to find another owner.

**Comment by knz** [comment]
We've done this differently: #86174
