### ISSUE TITLE
Capacity usage constantly growing

### ISSUE THREAD

**Issue by michael-ylb** [cockroachdb/cockroach#84980]
**Describe the problem**

On an empty cluster (3 nodes), the "capacity usage" is constantly growing, even with time series storage disabled. This resulted in all storage volumes to be full after some time. 

**To Reproduce**

1. Start a fresh cluster with 3 nodes. 
2. Run

  SET CLUSTER SETTING timeseries.storage.resolution_10s.ttl = '0s';
  SET CLUSTER SETTING timeseries.storage.resolution_30m.ttl = '0s';
  SET CLUSTER SETTING timeseries.storage.enabled = false;

3. In the overview, "Capacity Usage" will constantly rise with about 6 MB/min.

**Expected behavior**

Capacity usage should stay constant, especially without any data

**Environment:**
 - CockroachDB v22.1.2

Jira issue: CRDB-17983

**Comment by jbowens** [comment]
Hi @michael-ylb, thanks for the report!

Even with timeseries disabled, there will be background writes for various internal systems (eg, jobs, leases, liveness updates, etc.) CockroachDB has a minimum store size of 640 MB for this reason.

However 6 MiB/sec is more than expected and more than I'm able to reproduce on v22.1.2.

How much available capacity is available to your node to begin with? Where does `du -h cockroach-data/*` indicate the space is being consumed? What else can you tell me about the state of the cluster (eg, does it have data and if so how much?). I'm assuming there's no active workload when you're observing this?

**Comment by michael-ylb** [comment]
Hey,
currently I'm observing ~900 MB usage after ~150min uptime for 3 nodes (300 MB per node). Each node currently has a 32 GB volume. 

Example for node 0:
```
du -h cockroach-data/* 
71M	cockroach-data/000007.log
71M	cockroach-data/000011.log
71M	cockroach-data/000014.log
71M	cockroach-data/000017.log
71M	cockroach-data/000020.log
71M	cockroach-data/000023.log
956K	cockroach-data/000025.sst
4.0K	cockroach-data/CURRENT
0	cockroach-data/LOCK
4.0K	cockroach-data/MANIFEST-000001
4.0K	cockroach-data/OPTIONS-000003
4.0K	cockroach-data/STORAGE_MIN_VERSION
320M	cockroach-data/auxiliary
4.0K	cockroach-data/cockroach-temp3677559789/auxiliary
20K	cockroach-data/cockroach-temp3677559789
4.0K	cockroach-data/cockroach.advertise-addr
4.0K	cockroach-data/cockroach.advertise-sql-addr
4.0K	cockroach-data/cockroach.http-addr
4.0K	cockroach-data/cockroach.listen-addr
4.0K	cockroach-data/cockroach.sql-addr
4.0K	cockroach-data/logs/inflight_trace_dump
4.0K	cockroach-data/logs/goroutine_dump
1.2M	cockroach-data/logs/heap_profiler
2.8M	cockroach-data/logs
16K	cockroach-data/lost+found
0	cockroach-data/marker.format-version.000005.006
0	cockroach-data/marker.manifest.000001.MANIFEST-000001
4.0K	cockroach-data/temp-dirs-record.txt
```
The other nodes look similar (some more KiB in `auxiliary/sstsnapshot`)

This is currently a fresh test deployment with no usage / data / workload at all. Its a K8s deployment, `COCKROACH_CHANNEL` is `kubernetes-insecure`. 

The `system` database has 3.0 MiB, all other databases have 0 B.

**Comment by jbowens** [comment]
> This resulted in all storage volumes to be full after some time.

What was the capacity when the storage volume was exhausted?

```
71M	cockroach-data/000007.log
71M	cockroach-data/000011.log
71M	cockroach-data/000014.log
71M	cockroach-data/000017.log
71M	cockroach-data/000020.log
71M	cockroach-data/000023.log
```

The ~426 MB in log files is expected and will not grow additionally. Most of the background writes for system operations overwrite existing keys, and so they don't cause additional disk usage once flushed. However, these background writes can still fill up an entire WAL file. CockroachDB performs WAL recycling for performance. A small set of obsolete log files are not deleted and instead are kept around to be reused for a subsequent WAL. This avoids the overhead of allocating new filesystem blocks to back new WALs.

Are you seeing disk usage grow considerably beyond this steady state?

**Comment by michael-ylb** [comment]
The initial volume size was just 1GB. We created a new test deployment with 32GB each to see when/if we do hit a plateau. Currently its still rising and at ~1.1GB. 

I'm wondering why there is so much going on in the WAL just for internal operations. Is there a possibility to get some insights, whats being written to the WAL?

**Comment by jbowens** [comment]
There are frequent KV writes for maintaining liveness and lease records.

This command will dump all the live keys in a database.
```
cockroach debug keys ./cockroach-data
```
Making sense of the keys might be difficult, but the constants in [this file](https://github.com/cockroachdb/cockroach/blob/a243b8e4aef453bcce721f4c8d19be9ceb70a354/pkg/keys/constants.go#L454) map to the table IDs at the beginning of data keys.

This command will dump all the keys in a particular WAL file.
```
cockroach debug pebble wal dump ./cockroach-data/000007.log
```

**Comment by michael-ylb** [comment]
We monitored it now for a week and the volume usage stays at 1.1GB for three nodes. Thanks for all the help and the informations about the WAL!
