### ISSUE TITLE
cdc: declarative schema changes break core changefeeds

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#85008]
In 22.2 , we're planning on switching to the declarative schema changer. Some schema changes cause restarts - and will thus cause an error for core changefeeds. 

Jira issue: CRDB-17999

**Comment by jayshrivastava** [comment]
More info
- https://github.com/cockroachdb/cockroach/issues/84511#issuecomment-1194097481  
-  https://github.com/cockroachdb/cockroach/issues/84511#issuecomment-1187629271

**Comment by ajwerner** [comment]
Will the resolution to https://github.com/cockroachdb/cockroach/issues/84511 fix this? Should we mark this as a release blocker?

**Comment by amruss** [comment]
Seems like a 22.2 release blocker to me

**Comment by amruss** [comment]
More context: primary index changes cause this break. The declarative schema changer makes most schema changes into this type of schema change. This means most schema changes won't work with core changefeeds post 22.2.

**Comment by amruss** [comment]
Possible fix: allow core changefeeds to be restarted.
