### ISSUE TITLE
backupccl: cluster restores should also rekey before ingesting data

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#85019]
https://github.com/cockroachdb/cockroach/issues/84359 recognized a bug where system tables with dynamic IDs collided with descriptors being ingested during a cluster restore. Historically, cluster restore has assumed that the restoring cluster will have no colliding IDs with the backed-up descriptors. This invariant is becoming harder and harder to uphold, and it seems less issue prone to use the restoring clusters descriptor ID generator to assign new IDs to any descriptors being ingested during restore. Apart from rewriting every descriptor entry with a new ID, this also involves rekeying every raw KV to contain the new ID prefix. Database and table level restores are already in the business of rekeying SSTs to new IDs, and so rekeying during cluster restore as well should not involve _too much_ additional logic.

The one caveat to rekeying during cluster restore is restoring system tables that might have ID references in their rows. There could be direct references such as a column in the system table (egs: zone configs) or an indirect reference such as protos stored in the system tables. These rows will thus also have to be mutated prior to restore to contain the new rekeyed IDs.

The following list of opt-in system tables should be audited, and custom restore functions should be written to rewrite every restored row with the new descriptor ID:

- [ ] `system.jobs`: after https://github.com/cockroachdb/cockroach/pull/84886 we will not backup/restore jobs, instead we will synthesize schema change jobs during restore.
- [ ] `system.zones`
- [ ] `system.comments`
- [ ] `system.database_role_settings`

We should also benchmark how expensive it is to actually rekey during a cluster restore, and file independent issues for any known performance improvements.

Jira issue: CRDB-18005

**Comment by adityamaru** [comment]
@dt this is done right?

**Comment by dt** [comment]
#85492
