### ISSUE TITLE
kv: provide online method to clear leaked gossip infos

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#85013]
In a support escalation (https://github.com/cockroachlabs/support/issues/1709) for a v21.1 cluster, we saw that [leaked gossip entries](https://github.com/cockroachdb/cockroach/blob/9e1e2235a05ab0b2a77f917ba7bce303f6b8fe4a/pkg/sql/stats/new_stat.go#L112-L119) could impact foreground latency. The gossip leak itself has [since been fixed](https://github.com/cockroachdb/cockroach/commit/d07b32db3e49e91a438619586534b3ccc9813bcc), but there was no way to clear the leaked gossip values without a simultaneous, cluster-wide restart.

**It would have been valuable to have a way to expire gossip information manually.**

As a strawman, imagine a builtin function like `crdb_internal.expire_gossip_info(key)` that did the following:
```go
info := gossip.get(key)
if info != nil {
    gossip.addInfo(key, info.value, ttl=1m)
}
```
By injecting a 1m expiration, the gossip info would have enough time to propagate across the cluster but would then expire after a minute, clearing out the leaked information.

Jira issue: CRDB-18003

**Comment by surahman** [comment]
Hi @nvanbenschoten, where are the internal builtins located in the source? Is it always the case that the `gossip` map will contain the key in question?

```go
info , found := gossip.get(key)
if info != nil && found {
    gossip.addInfo(key, info.value, ttl=1m)
}

```

**Comment by surahman** [comment]
I have been looking through the data stuct for the [Gossip](https://github.com/cockroachdb/cockroach/blob/master/pkg/gossip/gossip.go) as well as the [context](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/eval/context.go) available to the builtins but cannot figure out how to access the map of gossip keys. Once accessed, an update is simple:
https://github.com/cockroachdb/cockroach/blob/30bb0d8c39c8a8819837f55bbb3a83157edd7ef9/pkg/gossip/gossip.go#L999

Would you be able to provide any details on how to get the gossip data from `ctx`?
