### ISSUE TITLE
sql: TRUNCATE's CASCADE clause unsupported

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/cockroach#8502]
Using `TRUNCATE tbl CASCADE` does not drop rows from tables that reference is.
### What did you do?

```
> CREATE TABLE reftbl (id INT PRIMARY KEY);
CREATE TABLE

> INSERT INTO reftbl VALUES (1);
INSERT 1

> CREATE TABLE fktbl (id INT REFERENCES reftbl, INDEX (id));
CREATE TABLE

> INSERT INTO fktbl VALUES (1);
INSERT 1

> TRUNCATE reftbl CASCADE;
pq: foreign key violation: non-empty columns [id] referenced in table "fktbl"
```
### What did you expect to see?

`TRUNCATE reftbl CASCADE;` should delete all rows from `fktbl` as well as `reftbl`
### What did you see instead?

`CASCADE` works instead like `RESTRICT`, which means `CASCADE` is not supported

**Comment by sploiselle** [comment]
@dt For the time being, would you recommend removing `CASCADE` and `RESTRICT` from the SQL grammar for `TRUNCATE` because their functions are vestigial?

**Comment by sploiselle** [comment]
Fixed by [sql: mention that CASCADE is unsupported](https://github.com/cockroachdb/cockroach/pull/8835/commits)

**Comment by dt** [comment]
This has been fixed.
