### ISSUE TITLE
changefeedccl: run tests randomly on old or new schema changer

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#85145]
During stability we should ensure that all cdc tests pass with the declarative schema changer either enabled or disabled. This isn't possible yet.

Jira issue: CRDB-18062

Epic CRDB-9179

**Comment by miretskiy** [comment]
I'm not sure there is anything for us to do.  I think declarative schema changer
gets enabled automatically for some types of schema changes, and disabled otherwise.
Is there anything specific that should be done on our side, @HonoreDB ?
If not, please close this issue.

**Comment by HonoreDB** [comment]
This issue is based on assumptions that are no longer true afaik, we're not going to have a flag that turns on the declarative schema changer for all changes.
