### ISSUE TITLE
sql: support `sql_body` syntax in CREATE FUNCTION statement

### ISSUE THREAD

**Issue by chengxiong-ruan** [cockroachdb/cockroach#85144]
Currently we only support the string function body for UDFs. To be more postgres compatible, we'd want to support the newer `sql_body` syntax as well, a.k.a having function body in `BEGIN ATOMIC.... END` context.

Jira issue: CRDB-18061

**Comment by chengxiong-ruan** [comment]
`sql_body` is the newly support syntax for UDF body in postgres where early binding of objects are done. Meaning that cross references are tracked, which is not the case with late binding. However, in CRDB we already do early binding, so this is basically just a nice to have syntax to support.

**Comment by rafiss** [comment]
closing in favor of https://github.com/cockroachdb/cockroach/issues/89109
