### ISSUE TITLE
Provide a way for system tenant to alter zone configs for secondary tenants

### ISSUE THREAD

**Issue by alyshanjahani-crl** [cockroachdb/cockroach#85179]
**Is your feature request related to a problem? Please describe.**
Currently secondary tenants have no control over their zone configurations. The system-tenant can set `sql.zone_configs.allow_for_secondary_tenant.enabled` to allow for a tenant to have the ability to do so. However, I would like a way for the host to set the zone configuration for any specific or all secondary tenants.

Furthermore, I would like a way for the host to set what the `RANGE default` zone configuration would be on newly created tenants.

**Describe the solution you'd like**
Possibly extending  `ALTER TENANT x SET CLUSTER SETTING ...`  to also support the syntax `ALTER TENANT x ALTER <zone-config-target> using ..` 

For the default zone configurations given to newly created tenants, i would like to be able to change those similarly like so
`ALTER TENANT default ALTER RANGE default using ...` 

**Describe alternatives you've considered**
The alternative i've considered is to set `sql.zone_configs.allow_for_secondary_tenant.enabled` for all existing tenants on the host cluster and manually alter the zone configs on each tenant.

**Additional context**
The context here is that CC wants to lower the default gc.ttlseconds for the serverless offering.

Perhaps if it is unfeasible to provide a mechanism for the host to set zone configs, we could change the hardcoded default gc.ttlseconds for tenants in CRDB (and have a migration that would perform this on existing tenants).

Jira issue: CRDB-18079

**Comment by irfansharif** [comment]
@alyshanjahani-crl, @andy-kimball, if we just give you some built-in to run on the host tenant `crdb_internal.lower_gc_ttl_over_tenant_spans(<integer>)`, and have that value take precedence over anything the user's set, does that work for now? Remember that serverless users can't actually set these zone configs. I'm trying to be lazy since it's late in the release.

**Comment by mwang1026** [comment]
From a product perspective, there's a question of "do we ever plan to give user tenants the ability to set their own gc.ttlseconds". If not, a system level override seems like it suffices for your needs?

**Comment by knz** [comment]
Can y'all link this to an epic under INI-214?

For example, is this a good candidate for epic? 
https://cockroachlabs.atlassian.net/browse/CRDB-16706
https://cockroachlabs.atlassian.net/browse/CRDB-18604

I think it naturally falls under CRDB-16706 but please decide. In any case, we want this to be tracked in the mt board too.

**Comment by andy-kimball** [comment]
> do we ever plan to give user tenants the ability to set their own gc.ttlseconds
Yes, I'd say we do want to do this in the future, though I expect with some restrictions.

Also, Alyshan and I have talked with @irfansharif about different possible solutions for this, and I think he understands our requirements and has some options that wouldn't be too difficult to implement.

**Comment by irfansharif** [comment]
https://github.com/cockroachdb/cockroach/pull/86450 has the 22.1 backport if you want to try it out sooner.
