### ISSUE TITLE
Any benchmark result for cockroachdb?

### ISSUE THREAD

**Issue by kiwigg** [cockroachdb/cockroach#8518]
Hello guys! Is there any benchmark(such as sysbench, tpcc) result for cockroahdb?
Thanks!

**Comment by petermattis** [comment]
@kiwigg We don't have any published benchmarks yet using standard tools like ycsb, sysbench or tpcc. We do have a few load generator programs and micro-benchmarks, but haven't published comparisons versus other databases yet.

**Comment by kiwigg** [comment]
@petermattis Thanks!
