### ISSUE TITLE
Pod within a cluster can not reconnect - Update

### ISSUE THREAD

**Issue by oscomp23** [cockroachdb/cockroach#85209]
**Describe the problem**

Within a  cockroachdb cluster one of the pods are no longer able to reconnect. Log gives us the advice to raise a github ticket and add the findings
https://www.cockroachlabs.com/docs/stable/cluster-setup-troubleshooting.html#node-liveness-issues

**To Reproduce**

Restarting the cluster node and look for the log why it is no longer connecting

1. Set up CockroachDB cluster -> running on a kubernetes cluster within AWS
2. Send SQL ... / CLI command -> outside the scope. Right now it is a connectivity/liveness topic
3. Look at UI / log file / client app -> We add the log below
4. See error -> We add the error log below

**Expected behavior**
After restart the node should reintegrate and heartbeat should sync

**Additional data / screenshots**

```
W220727 09:02:02.738210 644 kv/kvserver/liveness/liveness.go:845 ⋮ [n2,liveness-hb] 934  slow heartbeat took 4.500022134s; err=context deadline exceeded
W220727 09:02:02.738331 644 kv/kvserver/liveness/liveness.go:747 ⋮ [n2,liveness-hb] 935  failed node liveness heartbeat: ‹operation "node liveness heartbeat" timed out after 4.5s›: context deadline exceeded
W220727 09:02:02.738331 644 kv/kvserver/liveness/liveness.go:747 ⋮ [n2,liveness-hb] 935 +(1) ‹operation "node liveness heartbeat" timed out after 4.5s›
W220727 09:02:02.738331 644 kv/kvserver/liveness/liveness.go:747 ⋮ [n2,liveness-hb] 935 +Wraps: (2) context deadline exceeded
W220727 09:02:02.738331 644 kv/kvserver/liveness/liveness.go:747 ⋮ [n2,liveness-hb] 935 +Error types: (1) *contextutil.TimeoutError (2) context.deadlineExceededError
W220727 09:02:02.738331 644 kv/kvserver/liveness/liveness.go:747 ⋮ [n2,liveness-hb] 935 +
W220727 09:02:02.738331 644 kv/kvserver/liveness/liveness.go:747 ⋮ [n2,liveness-hb] 935 +An inability to maintain liveness will prevent a node from participating in a
W220727 09:02:02.738331 644 kv/kvserver/liveness/liveness.go:747 ⋮ [n2,liveness-hb] 935 +cluster. If this problem persists, it may be a sign of resource starvation or
W220727 09:02:02.738331 644 kv/kvserver/liveness/liveness.go:747 ⋮ [n2,liveness-hb] 935 +of network connectivity problems. For help troubleshooting, visit:
W220727 09:02:02.738331 644 kv/kvserver/liveness/liveness.go:747 ⋮ [n2,liveness-hb] 935 +
W220727 09:02:02.738331 644 kv/kvserver/liveness/liveness.go:747 ⋮ [n2,liveness-hb] 935 +    https://www.cockroachlabs.com/docs/stable/cluster-setup-troubleshooting.html#node-liveness-issues

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).


W220727 09:32:59.284246 97457 kv/kvserver/replica_range_lease.go:1231 ⋮ [n2,merge,s2,r1197/3:‹/System/tsd/cr.node.sql.…›] 5754  have been waiting 1m0s attempting to acquire lease
E220727 09:32:59.303644 97458 kv/kvserver/replica_write.go:292 ⋮ [n2,s2,r1197/3:‹/System/tsd/cr.node.sql.…›] 5755  range unavailable: have been waiting 60.01s for proposing command RequestLease [‹/System/tsd/cr.node.sql.distsql.vec.openfds/2/10s/2021-11-06T17:00:00Z›,‹/Min›).
E220727 09:32:59.303644 97458 kv/kvserver/replica_write.go:292 ⋮ [n2,s2,r1197/3:‹/System/tsd/cr.node.sql.…›] 5755 +This range is likely unavailable.
E220727 09:32:59.303644 97458 kv/kvserver/replica_write.go:292 ⋮ [n2,s2,r1197/3:‹/System/tsd/cr.node.sql.…›] 5755 +Please submit this message to Cockroach Labs support along with the following information:
E220727 09:32:59.303644 97458 kv/kvserver/replica_write.go:292 ⋮ [n2,s2,r1197/3:‹/System/tsd/cr.node.sql.…›] 5755 +
E220727 09:32:59.303644 97458 kv/kvserver/replica_write.go:292 ⋮ [n2,s2,r1197/3:‹/System/tsd/cr.node.sql.…›] 5755 +Descriptor:  r1197:‹/System/tsd/cr.node.sql.{distsql.vec.openfds/2/10s/2021-11-06T17:00:00Z-mem.bulk.max-count/2/10s/2021-10-16T12:00:00Z}› [(n1,s1):1, (n3,s3):2, (n2,s2):3, next=4, gen=10]
E220727 09:32:59.303644 97458 kv/kvserver/replica_write.go:292 ⋮ [n2,s2,r1197/3:‹/System/tsd/cr.node.sql.…›] 5755 +Live:        (n1,s1):1,(n3,s3):2
E220727 09:32:59.303644 97458 kv/kvserver/replica_write.go:292 ⋮ [n2,s2,r1197/3:‹/System/tsd/cr.node.sql.…›] 5755 +Non-live:    (n2,s2):3
E220727 09:32:59.303644 97458 kv/kvserver/replica_write.go:292 ⋮ [n2,s2,r1197/3:‹/System/tsd/cr.node.sql.…›] 5755 +Raft Status: {"id":"3","term":191,"vote":"0","commit":13357262,"lead":"2","raftState":"StateFollower","applied":13357262,"progress":{},"leadtransferee":"0"}
E220727 09:32:59.303644 97458 kv/kvserver/replica_write.go:292 ⋮ [n2,s2,r1197/3:‹/System/tsd/cr.node.sql.…›] 5755 +
E220727 09:32:59.303644 97458 kv/kvserver/replica_write.go:292 ⋮ [n2,s2,r1197/3:‹/System/tsd/cr.node.sql.…›] 5755 +and a copy of https://yourhost:8080/#/reports/range/1197
E220727 09:32:59.303644 97458 kv/kvserver/replica_write.go:292 ⋮ [n2,s2,r1197/3:‹/System/tsd/cr.node.sql.…›] 5755 +
E220727 09:32:59.303644 97458 kv/kvserver/replica_write.go:292 ⋮ [n2,s2,r1197/3:‹/System/tsd/cr.node.sql.…›] 5755 +If you are using CockroachDB Enterprise, reach out through your
E220727 09:32:59.303644 97458 kv/kvserver/replica_write.go:292 ⋮ [n2,s2,r1197/3:‹/System/tsd/cr.node.sql.…›] 5755 +support contract. Otherwise, please open an issue at:
E220727 09:32:59.303644 97458 kv/kvserver/replica_write.go:292 ⋮ [n2,s2,r1197/3:‹/System/tsd/cr.node.sql.…›] 5755 +
E220727 09:32:59.303644 97458 kv/kvserver/replica_write.go:292 ⋮ [n2,s2,r1197/3:‹/System/tsd/cr.node.sql.…›] 5755 +  https://github.com/cockroachdb/cockroach/issues/new/choose
Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.
```

**Environment:**
 - CockroachDB version [e.g. 2.0.x]
 - Server OS: Ubuntu
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
DB cluster no longer working

Jira issue: CRDB-18103

**Comment by erikgrinaker** [comment]
Hi! This indicates that range 1197 is unavailable. Can you please supply the CockroachDB version and the range report at https://<host>:8080/#/reports/range/1197 ?

**Comment by erikgrinaker** [comment]
No updates, going to close this out. Let us know if you have any further details.

**Comment by oscomp23** [comment]
Hi @erikgrinaker 
sorry to come back late due to the holiday season.

Version information
Cockroach Version:
bash-4.4$ cockroach version
Build Tag:        v21.1.10
Build Time:       2021/10/07 02:39:03
Distribution:     CCL
Platform:         linux amd64 (x86_64-unknown-linux-gnu)
Go Version:       go1.15.14
C Compiler:       gcc 6.5.0
Build Commit ID:  a6daab16ee8a1c15abc4c4a8a425e46d12033b5c
Build Type:       release

We used the official K8s with the helm charts as a cluster setup with 3 pods.

We tried to bring a new pod active, but as the new pod is a mirror of the existing, we fail with that.

The Range Report gave an error. Please find the screenshots attached for reference.

Thanks
Oliver
![RangeReport](https://user-images.githubusercontent.com/102041170/186139370-3c0973f4-fa63-4aae-a7fb-8296c7e6465a.png)
![RangeReport_1197](https://user-images.githubusercontent.com/102041170/186139374-6ee63cc7-8394-4f24-af1d-a230943e8bee.png)

**Comment by erikgrinaker** [comment]
Yes, it does seem like n2 is having difficulty contacting the rest of the cluster. However, there isn't a lot of detail to go by here. Have you confirmed that the TCP networking works between all nodes? Are there any indications in n2's log about why it fails to connect? Do any of the other nodes show signs of trouble? Normally, the cluster should continue working even if a single node fails (especially if that node is shut down), so if that's not the case then there are broader problems in this cluster.

> We tried to bring a new pod active, but as the new pod is a mirror of the existing, we fail with that.

Can you elaborate on this? Did you replace one of the existing pods with a new one? And it fails like this every time?

**Comment by oscomp23** [comment]
Hi Erik,
Thank you so much for your input.
Regarding your questions:
> Have you confirmed that the TCP networking works between all nodes?
According to the logs of the affected pod, communication to the other pods is possible:
I220825 11:37:08.240500 157 gossip/client.go:124 [n2] 86  started gossip client to n0 (‹cockroachdb-test-int-0.cockroachdb-test-int.helixid-database-test-int:26258›)
I220825 11:37:08.243845 151 1@server/server.go:1570 [n2] 87  node connected via gossip
I220825 11:37:10.383045 154 1@gossip/gossip.go:1505 [n2] 89  node has connected to cluster via gossip

Since all 3 pods are running within the same namespace on the same k8s cluster, all communication between the pods should be possible.

> Do any of the other nodes show signs of trouble?
From what I can tell, the other nodes don't show these signs of trouble.
There are some warnings regarding underreplicated ranges, but I assume this is because one node is not available:
W220825 11:45:02.225299 504 server/node.go:768 [n1,summaries] 1116381  health alerts detected: ‹{Alerts:[{StoreID:1 Category:METRICS Description:ranges.underreplicated Value:127}]}›

Additionally, there is an error message about failed replica initializations:
E220825 11:42:08.924759 178916136 kv/kvserver/queue.go:1098 [n1,raftsnapshot,s1,r2426/1:‹/System/tsd/cr.node.rpc.heart…›] 1116329  ‹operation "raftsnapshot queue process replica 2426" timed out after 1m0s›: ‹rpc error: code = DeadlineExceeded desc = context deadline exceeded›


> Can you elaborate on this? Did you replace one of the existing pods with a new one? And it fails like this every time?
We did redeploy the affected pod by simply deleting it. Since we are using the official Helm deployment, the pod gets recreated immediately.
Every recreated pod for cockroachdb-test-int-1 is experiencing this exact same problem.

Best,
Oliver

**Comment by erikgrinaker** [comment]
I'm afraid I'll need more information in order to diagnose this. Can you collect a debug.zip and upload it to me privately at https://upload.cockroachlabs.com/dropzone/grinaker? You can find information on how to collect this here: https://www.cockroachlabs.com/docs/stable/cockroach-debug-zip.html

**Comment by erikgrinaker** [comment]
PS: I'll be out-of-office for a few days, but will have a look next week.

**Comment by erikgrinaker** [comment]
No updates, closing.
