### ISSUE TITLE
update loading message to "time interval" on SQL Activity

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#85218]
On SQL Activity page (both Statements and Transactions tabs), when takes longer to load the table, we show a message using "time period". 
Change the text to say "time interval"

<img width="785" alt="Screen Shot 2022-07-26 at 10 17 30 AM" src="https://user-images.githubusercontent.com/1017486/181516267-125958f2-b54f-403e-9f4c-e03faaee6f64.png">

Jira issue: CRDB-18112

**Comment by ericharmeling** [comment]
Should we move this over to https://github.com/cockroachdb/cockroach/issues/85224?
