### ISSUE TITLE
fix store refresh on cache invalidation period for CC console pages

### ISSUE THREAD

**Issue by j82w** [cockroachdb/cockroach#85236]
On the statement activity page I had it sorted by Network over the last month. I left the page sit for several minutes and the loading icon appeared. It never went away. Refreshing the page fixed the issue. I saw the 2 errors in the console, but not sure if they are related. 

Failed to load resource: the server responded with a status of 400 ()
application.cfd4667d3b1ee89a23ec.js:6065 Uncaught TypeError: this.props.onPageChanged is not a function
    at Kt.onChangePage [as onChange] (admin-ui-22-2.cfd4667d3b1ee89a23ec.js:1464:83917)
    at Object.handleChange [as onClick] (admin-ui-22-2.cfd4667d3b1ee89a23ec.js:1468:116203)
    at De (admin-ui-22-2.cfd4667d3b1ee89a23ec.js:1468:102968)
    at Object.ht (application.cfd4667d3b1ee89a23ec.js:6065:9513)
    at Rn (application.cfd4667d3b1ee89a23ec.js:6065:9678)
    at Bn (application.cfd4667d3b1ee89a23ec.js:6065:9742)
    at er (application.cfd4667d3b1ee89a23ec.js:6065:29480)
    at Rr (application.cfd4667d3b1ee89a23ec.js:6065:29945)
    at application.cfd4667d3b1ee89a23ec.js:6065:35401
    at Et (application.cfd4667d3b1ee89a23ec.js:6069:19438)

<img width="1991" alt="Screen Shot 2022-07-28 at 10 59 09 AM" src="https://user-images.githubusercontent.com/8868107/181570434-4fb73564-5801-4b0a-b576-0538cc3b957b.png">

Jira issue: CRDB-18126

**Comment by ericharmeling** [comment]
Looks like we filed the same issue at the same time 😁.

Going to close mine and leave yours open.

Here was my issue description:

> After being on either the Statement Fingerprints or Transaction Fingerprints overview page for 5 minutes, the cache invalidation period triggers a refresh of the statements data. This refresh hangs with the “If the selected time period contains a large amount of data, this page might take a few minutes to load.” message. A manual refresh resolves the issue, so it looks like the refresh on cache invalidation refresh isn't working properly. This does not appear to affect self-hosted clusters.

**Comment by ericharmeling** [comment]
I repro'd this on 22.1 (`july22-sql-o11y-22-1`), so it's a pre-existing bug, not specific to 22.2.

**Comment by ericharmeling** [comment]
Pages this affects:

- Statement Fingerprints overview (statement fingerprints table)
- Transaction Fingerprints overview (transaction fingerprints table)
- Statement Fingerprints details (overview tab SQL box, explain plans tab SQL box and table, diagnostics tab table)
- Transaction Fingerprints details (statement fingerprints table, SQL box)

**Comment by THardy98** [comment]
Also affects the Statement Diagnostics page
