### ISSUE TITLE
sql/schemachanger: ensure zone configurations are applied in ADD/DROP COLUMN

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#85238]
**Is your feature request related to a problem? Please describe.**

If a table has a zone configuration on its primary index or any partitions of the primary index, we need to make sure we clone such zone configurations into the newly added primary and temp indexes. If we don't, we'll effectively be losing the configuration altogether. 

**Describe the solution you'd like**
We'll need to retrieve the zone configurations and model them. As a first step, we could retrieve them in the builder and return an unsupported error to fall back to the legacy schema changer. I think we need to at least do the first step before shipping 22.2. 

Jira issue: CRDB-18129

**Comment by postamar** [comment]
This extends beyond ADD/DROP COLUMN to also involve ALTER PRIMARY KEY and friends. Possibly also DROP INDEX, I don't know? In any case we need a short-term fix that causes the declarative schema changer to fall back to the legacy schema changer in the presence of zone configs on indexes.

**Comment by fqazi** [comment]
I'll dig into this, along with double checking that we have proper disablement for other zone config areas

**Comment by postamar** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/86326
