### ISSUE TITLE
region values undefined in Transaction Fingerprint details page statement fingerprints table

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/cockroach#85245]
The values in the Regions/Nodes column of the statement fingerprints table on the Transaction Fingerprint details page aren't populating correctly:

![image](https://user-images.githubusercontent.com/27286675/181581993-5ef99c51-088e-48c4-82bf-94633038666c.png)

Jira issue: CRDB-18133

**Comment by maryliag** [comment]
This will get fixes once https://github.com/cockroachdb/cockroach/issues/89949 is done.
