### ISSUE TITLE
All sorts are selected on index stats on Table Details

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#85242]
When opening a Table Details page, the table for index stats have all columns with the sorting selected. Once any of them is clicked, it works as expected. 
Fix the default sorting to the total reads column

<img width="1645" alt="Screen Shot 2022-07-28 at 11 29 57 AM" src="https://user-images.githubusercontent.com/1017486/181578134-68ca9d99-e1b0-43ab-905e-09cd3bf1d9fa.png">

Jira issue: CRDB-18132

**Comment by j82w** [comment]
@maryliag was there any additional steps to reproduce this behavior or was it possibly fixed already? I'm not able to reproduce it.

<img width="1432" alt="Screen Shot 2022-09-07 at 3 08 04 PM" src="https://user-images.githubusercontent.com/8868107/188958296-7b59d2e6-7545-45e7-8136-b52b16791f6a.png">
