### ISSUE TITLE
first_value() without group by every column

### ISSUE THREAD

**Issue by dpkirchner** [cockroachdb/cockroach#85258]
**Is your feature request related to a problem? Please describe.**
It would be useful to have a way to get the first value used in a sorted aggregate function (e.g. `first_value(column_a) over (order by column_b)`) without having to group by (nearly) every column in a table.

**Describe the solution you'd like**
```
SELECT
	tbl.id,
	tbl.name,
	count(other_tbl.id),
	first_value(other_tbl.column_a) OVER (
		ORDER BY other_tbl.created
	)
FROM
	tbl JOIN other_tbl ON tbl.id = other_tbl.tbl_id
GROUP BY
	tbl.id
```

should return:
```
'tbl-uuid-1', 'tbl row 1', 2, 'other tbl a'
```

and using `ORDER BY other_tbl.created DESC` should return the same thing but with the last column `other tbl b`.

Instead it shows an error:

```
ERROR: column "column_a" must appear in the GROUP BY clause or be used in an aggregate function
```

Adding nearly every column from the `other_tbl` to `GROUP BY` seems less than ideal as it would potentially create a lot of groups. In fact you have to add `other_tbl.column_a, other_tbl.created` (but not `other_tbl.id`).

Schema:
```
CREATE TABLE tbl (
	id UUID NOT NULL DEFAULT gen_random_uuid(),
	name STRING NOT NULL,
	CONSTRAINT tbl_pkey PRIMARY KEY (id ASC)
);
CREATE TABLE other_tbl (
	id
		UUID NOT NULL DEFAULT gen_random_uuid(),
	tbl_id
		UUID NOT NULL,
	created
		TIMESTAMP DEFAULT now():::TIMESTAMP NOT NULL,
	column_a STRING NOT NULL,
	CONSTRAINT other_tbl_pkey PRIMARY KEY (id ASC),
	CONSTRAINT other_tbl_tbl_id_fkey
		FOREIGN KEY (tbl_id)
		REFERENCES tbl (id)
		ON DELETE CASCADE
);
```

and data:

```
insert into tbl (name) values ('tbl row 1'), ('tbl row 2');

insert into other_tbl (tbl_id, created, column_a) values ((select id from tbl limit 1), '2021-01-01 00:00:00', 'other tbl a');
insert into other_tbl (tbl_id, created, column_a) values ((select id from tbl limit 1), '2021-02-01 00:00:00', 'other tbl a');
```

**Describe alternatives you've considered**
N+1 queries where there's always a query against tbl to get its ids and name and N queries, one per tbl row, that uses first_value, e.g.:

```
> select id, name from tbl;
                   id                  |   name
---------------------------------------+------------
  4402be68-7fca-47e8-b0c0-d09a14820acc | tbl row 2

> select * from other_tbl where tbl_id = '4402be68-7fca-47e8-b0c0-d09a14820acc' order by created limit 1;
                   id                  |                tbl_id                |       created       |  column_a
---------------------------------------+--------------------------------------+---------------------+--------------
  b10c8dbf-ee29-4fc0-a603-422dac449839 | 4402be68-7fca-47e8-b0c0-d09a14820acc | 2021-01-01 00:00:00 | other tbl a
(1 row)
```

This is probably going to be slow, and of course it must be run inside a transaction.

Postgres offers `WITHIN GROUP` which seems like it'd do what I want (I mean, the name makes it sound like it's the right solution), however I don't think it works with `first_value()`. This might be a good addition to cockroachdb as it'd be an improvement that I suspect a lot of people would enjoy.

**Additional context**
I'm running v22.1.5 with default configs, whatever is included in the latest v22.1.5 docker image (`66ee50d6fdc92a6994d79a74eb689b6fd2a931c4c72ac98b4cb7dba4c6ce3f8f `).

**Comment by dpkirchner** [comment]
Whoops! Accidentally submitted this before I typed it all up, just a minute...

**Comment by lassenordahl** [comment]
Howdy @dpkirchner! Thanks for the feature request!

I'm going to label this under the SQL-Execution team for now, and they can help get it triaged.

**Comment by dpkirchner** [comment]
Sweet. Btw, I figured out a better alternative solution that only requires two queries.

These are rough, may not be syntactically correct, but it's basically:
```
SELECT foo.*, other_tbl.column_a
(SELECT
	DISTINCT tbl.id,
	tbl.name,
	first_value(other_tbl.id) OVER w AS first_other
FROM
	tbl JOIN other_tbl ON tbl.id = other_tbl.tbl_id
WHERE w AS (PARTITION tbl.id)
) AS foo JOIN other_tbl ON foo.id = other_foo.tbl_id
```

followed by a bog standard count aggregation query.

**Comment by yuzefovich** [comment]
@dpkirchner glad you were able to find a workaround!

As you mentioned, Postgres doesn't support this feature, and we're shooting for postgres compatibility, so we're unlikely to implement it.

Additionally, for the original query you'd like to not error out, it might be better to think of `first_value(column_a) over (order by column_b)` not as "a sorted aggregate function" but as "a window function", and these things are somewhat orthogonal. My suggestion would have been to break the window functions and the GROUP BY into separate queries which is effectively what your solution does.
