### ISSUE TITLE
Surface SQL observability into 40001 errors

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#85256]
Described in the following [issue](https://github.com/cockroachdb/cockroach/issues/81176), we need better observability into retry (internal and external) errors. 

This issue tracks surfacing observability in the console help developers and operators troubleshoot isolation contention. 

Jira issue: CRDB-18141

Epic: CRDB-20438

**Comment by kevin-v-ngo** [comment]
Note: This issue is not entirely dependent on KV. We already have information (e.g., error message) returned that we can use to build a better observability experience.

**Comment by maryliag** [comment]
Error message already being displayed for this case.
