### ISSUE TITLE
streamingccl: multi-node test is sometimes unable to cutover in stress test

### ISSUE THREAD

**Issue by samiskin** [cockroachdb/cockroach#85283]
In `TestTenantStreamingSuccessfulIngestion`, Setting the src `numNodes` to 4 and adding a table scattered across those nodes, then running under stress, eventually (in 5 minutes or so on my gceworker) results in a `condition failed to evaluate within 2m0s: expected job status succeeded, but got running` error right after cutover.

This is a blocker to the `TestTenantStreamingUnavailableStreamAddress` test as it requires a multi-node cluster where one node is taken down.

I observed a similar issue live on roachprod once, where it wouldn't work even if I paused and restarted the replication feed, but when I tried again with a fresh cluster it worked.

Jira issue: CRDB-18154

**Comment by samiskin** [comment]
Code I used to create a scattered table:
```
// Create a source table with multiple ranges spread across multiple nodes
numRanges := 50
rowsPerRange := 20
c.srcTenantSQL.Exec(t, fmt.Sprintf(`
CREATE TABLE d.scattered (key INT PRIMARY KEY);
INSERT INTO d.scattered (key) SELECT * FROM generate_series(1, %d);
ALTER TABLE d.scattered SPLIT AT (SELECT * FROM generate_series(%d, %d, %d));
ALTER TABLE d.scattered SCATTER;
`, numRanges*rowsPerRange, rowsPerRange, (numRanges-1)*rowsPerRange, rowsPerRange))
```

**Comment by msbutler** [comment]
closing as the mentioned test no longer exists and because  the `TestTenantStreamingMultipleNodes` seems to do the same thing described by this skipped test.
