### ISSUE TITLE
sql/opt: selectivity is wrong for joins with hash-sharded indexes

### ISSUE THREAD

**Issue by michae2** [cockroachdb/cockroach#85353]
When joining to a hash-sharded index with an equality predicate, the optimizer considers the join more selective than it should, because the generated shard column is counted as another (independent) equality predicate in [selectivityFromEquivalencies](https://github.com/cockroachdb/cockroach/blob/c8b70faa6e38593ae32be8c6b87b8a273fabdebe/pkg/sql/opt/memo/statistics_builder.go#L1266). In reality it is not independent, and shouldn't change the selectivity.

If the optimizer is trying to decide between a normal index and a hash-sharded index, it will sometimes favor the hash-sharded index unfairly because of this. For example:

```sql
CREATE TABLE t (b INT);
CREATE TABLE u (a INT, b INT, INDEX (a), INDEX (b) USING HASH);
INSERT INTO t SELECT generate_series(0, 9);
INSERT INTO u SELECT z % 40, z % 10 FROM generate_series(0, 99999) AS y (z);
ANALYZE t;
ANALYZE u;
EXPLAIN (OPT, VERBOSE) SELECT COUNT(*) FROM t JOIN u USING (b) WHERE a < 10;
```

In this case we could either read 25k rows from `u_a_idx` or 100k rows from `u_b_idx` to get the same answer. The optimizer will favor `u_b_idx`, even though it has to read 4x as many rows, because it estimates the selectivity of the join to `u_b_idx` as 1/160 when it should be 1/10. (It estimates the selectivity of the read of `u_a_idx` as 1/40.)

We can see the 4x difference when we actually execute:

```
demo@127.0.0.1:26257/defaultdb> EXPLAIN ANALYZE SELECT COUNT(*) FROM t JOIN u USING (b) WHERE u.a < 10;
                                              info
------------------------------------------------------------------------------------------------
  planning time: 241µs
  execution time: 6.1s
  distribution: full
  vectorized: true
  rows read from KV: 200,010 (6.3 MiB, 16 gRPC calls)
...

demo@127.0.0.1:26257/defaultdb> EXPLAIN ANALYZE SELECT COUNT(*) FROM t JOIN u@u_a_idx USING (b) WHERE u.a < 10;
                                             info
-----------------------------------------------------------------------------------------------
  planning time: 781µs
  execution time: 1.5s
  distribution: full
  vectorized: true
  rows read from KV: 50,010 (1.6 MiB, 3 gRPC calls)
...
```

Jira issue: CRDB-18197

**Comment by rytaft** [comment]
@msirek do you think you can take a look at this in the next week and see if it's something that we can fix easily? This seems related to the work you did previously to add stats for check constraints.
