### ISSUE TITLE
Unable to rename database due to views.

### ISSUE THREAD

**Issue by Defman** [cockroachdb/cockroach#85401]
**Describe the problem**

Cannot rename database do to views.

**To Reproduce**
```sql
CREATE VIEW issue AS SELECT 1;
ALTER DATABASE foo RENAME TO bar;
```

**Expected behavior**
I expect the database to be renamed without issue.

Jira issue: CRDB-18231

**Comment by postamar** [comment]
I can't repro this, it works on `master`, so it appears that this has been fixed at some point. Please feel free to re-open in case I missed something.

**Comment by ajwerner** [comment]
This is probably https://github.com/cockroachdb/cockroach/issues/10083. This is unfortunately expected. We hope to address this in a future release (though not the proximate release, 22.2).
