### ISSUE TITLE
sql: collect log-based telemetry on regions visited by each query

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#85427]
**Is your feature request related to a problem? Please describe.**
Currently our log-based telemetry does not include the regions visited by a query. It would be helpful to know how many of our customers' queries are visiting multiple regions.

**Describe the solution you'd like**
The log-based telemetry should include all the regions visited by a query, similar to the region information currently output by `EXPLAIN ANALYZE`. Although the `EXPLAIN ANALYZE` output today doesn't technically include every region touched by the query (e.g., if the KV api fetches data from a remote region this will not be represented), it will give us a pretty good idea. In particular, it will include all the regions where DistSQL processors are planned.

**Describe alternatives you've considered**
It would be helpful to include regions visited by the KV api, but this would be a more invasive change.

Jira issue: CRDB-18243

**Comment by rytaft** [comment]
cc @awoods187

**Comment by awoods187** [comment]
cc @vy-ton for awareness as I'm out
