### ISSUE TITLE
CDC - unmarshalling - Not a bug - need help

### ISSUE THREAD

**Issue by desaimom** [cockroachdb/cockroach#85446]
Thanks @HonoreDB, I got unblocked where I now do get CDC data feed properly.
But I am not sure how to unmarshal the data in Java.

eg. in interactive SQL:
kv,[784266261109473281],"{""after"": {""key"": ""abc"", ""rowid"": 784266261109473281, ""value"": ""sql6"", ""version"": 1}}"

But in JAVA: results.getString(1), getString(2) and getString(3), gives me following.

WARN [SpiralChangeDataCapture] table: kv
WARN [SpiralChangeDataCapture] key: \x5b3738343236363236313130393437333238315d
WARN [SpiralChangeDataCapture] value: \x7b226166746572223a207b226b6579223a2022616263222c2022726f776964223a203738343236363236313130393437333238312c202276616c7565223a202273716c36222c202276657273696f6e223a20317d7d

This is NOT a bug. I have posted on Slack channel but haven't got any response.

any help/pointers, please?

thanks,

Jira issue: CRDB-18248

**Comment by ajwerner** [comment]
I'm closing this as a non-bug. Probably this user would have a better time interacting with the data using columns directly as opposed to needing to marshal and unmarshal from json. See https://github.com/cockroachdb/cockroach/issues/77849.

**Comment by HonoreDB** [comment]
Hey, I'm awake now and available on Slack for help. I've also created a Docs issue https://github.com/cockroachdb/docs/issues/14694 describing what's going on.

**Comment by desaimom** [comment]
Thanks @HonoreDB - i will go through some suggestions which are on slack and here. Sorry for all the trouble.
