### ISSUE TITLE
cannot cast jsonb numeric to type bool

### ISSUE THREAD

**Issue by bajinsheng** [cockroachdb/cockroach#85441]
**Describe the problem**

An unexpected error when converting jsonb numeric to type bool

**To Reproduce**

```sql
SELECT '0' ::JSONB ::BOOL; -- ERROR: cannot cast jsonb numeric to type bool SQLSTATE: 22023
SELECT '0' ::JSONB ::INT ::BOOL; -- {f}
```
**Expected behavior**
No error for the first `SELECT`.

**Additional data / screenshots**

**Environment:**
 - CockroachDB version [6374bd83f192bd509e50313acb431690b9c3f8ae]
 - Server OS: [Ubuntu 20.04]
 - Client app [`cockroach sql`]

**Additional context**

Jira issue: CRDB-18246

**Comment by ajwerner** [comment]
I don't think this is a bug. The cockroach behavior matches the postgres behavior. If you want to make a case for why postgres is definitely wrong, you can reopen the issue. Beware, the bar for making such a case is quite high. 

```sql
postgres=# SELECT '0' ::JSONB ::BOOL;
ERROR:  cannot cast jsonb numeric to type boolean
postgres=# SELECT '0' ::JSONB ::INT ::BOOL;
 f
```
