### ISSUE TITLE
decommission: improvements in 22.2

### ISSUE THREAD

**Issue by AlexTalks** [cockroachdb/cockroach#85445]
This is a tracking issue for decommissioning improvements in 22.2.

## Benchmarking
- [x] Create benchmarks for decommissions in relevant cases
- [x] Evaluate benchmarks against optimal time estimates

## Observability

- [x] Export queue lengths and snapshots in progress via metrics
- [x] Add tracing for errors during decommission
- [x] Track error counts for a decommission
- [x] Snapshot Dashboard showing: Snapshots in progress, queue lengths, purgatory counts, aggregate error counts.
- [x] Avoid displaying retired nodes in Admin UI

## Operational Improvements
- [x] Receiver-side snapshot queueing to ensure fairness (#86799)
- [x] New allocator "destination store selector" for decommissioning to pick from available nodes rather than best node (https://github.com/cockroachdb/cockroach/issues/86265)
- [x] Fix requeue in replicate queue to downprioritize range count rebalance actions during a decommission

Jira issue: CRDB-18247

Epic CRDB-14621

**Comment by kvoli** [comment]
related: https://github.com/cockroachdb/cockroach/issues/85528

**Comment by AlexTalks** [comment]
Deferring to 23.1

## Observability

- [ ] Export traces to Observability Service

## Operational Improvements
- [ ] Preflight checks to fail fast if decommissioning cannot (currently) complete

**Comment by AlexTalks** [comment]
All 22.2 improvements listed above have merged.
