### ISSUE TITLE
jobs: add metric for number of paused jobs

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#85467]
See for context: https://docs.google.com/document/d/1XZzS6UlfQUVJQPKSttKsXSxwV6bAmzS4D5jDjPvJWjY/edit

We don't have any metrics on the number of paused jobs in the system. This can be an important monitoring primitive for customers, especially in the context of changefeeds. 

Jira issue: CRDB-18256

**Comment by amruss** [comment]
Maybe interrupted jobs? Including paused and intermediate josb states (everything except cancelled, failed, running, and completed)

**Comment by jayshrivastava** [comment]
Is there something specific we want to add which is not covered in this section of the UI? For example, do we want a metric for paused changefeed jobs only?
 
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/18633281/194346882-07d02869-fa26-468a-bc1e-199ae44ef7bb.png">

**Comment by jayshrivastava** [comment]
Closing for now. We can use the metric `jobs.changefeed.currently_idle`
https://github.com/cockroachdb/cockroach/blob/faa22030ff7275961d1a55c9ebe02ab472cf63ba/pkg/ccl/changefeedccl/changefeed_test.go#L286

**Comment by jayshrivastava** [comment]
As it turns out `paused` implies `idle`, but `idle` does not imply `paused`, as per Yevgeniy's comments in https://github.com/cockroachdb/cockroach/pull/89752

**Comment by amruss** [comment]
Note: may not be backportable
