### ISSUE TITLE
Unexpected Result by UNION

### ISSUE THREAD

**Issue by bajinsheng** [cockroachdb/cockroach#85502]
**Describe the problem**

An unexpected result in UNION.
The third SELECT is the UNION of above two SELECTs, but the result is not the sum of the results of above two SELECTs.

**To Reproduce**

```sql
CREATE TABLE t1 (c0 BOOL AS (1 IS NULL) STORED, CONSTRAINT "primary" PRIMARY KEY(c0));
CREATE TABLE t2 (c0 INT);
INSERT INTO t2 (c0) VALUES(1);
INSERT INTO t1 DEFAULT VALUES;


SELECT t1.c0 FROM t2 FULL OUTER JOIN t1 ON false WHERE false IN (t1.c0 IS NULL); -- {f}
SELECT t1.c0 FROM t2 FULL OUTER JOIN t1 ON false WHERE NOT false IN (t1.c0 IS NULL); -- {NULL}

SELECT t1.c0 FROM t2 FULL OUTER JOIN t1 ON false WHERE false IN (t1.c0 IS NULL) UNION SELECT t1.c0 FROM t2 FULL OUTER JOIN t1 ON false WHERE NOT false IN (t1.c0 IS NULL); -- {f}
```

**Expected behavior**
The result of the third SELECT should be {f}, {NULL}, while it only return one row.

**Additional data / screenshots**

**Environment:**
 - CockroachDB version [5cd03090895687cd0df002b9ce86bec226a9b193]
 - Server OS: [Ubuntu 20.04]
 - Client app [`cockroach sql`]

**Additional context**

Jira issue: CRDB-18273

**Comment by yuzefovich** [comment]
Thanks for the report!

The bug reproduces on 22.1.5 and 21.2.14, but not on 21.1.19, will take a closer look.

**Comment by yuzefovich** [comment]
I think `ConvertUnionToDistinctUnionAll` normalization rule is to blame introduced in #64976. The first condition for that rule to fire is that `All columns from both inputs originate from the same base table`, but it doesn't look like it's the case here (i.e. the conditions seem to be violated, yet the rule is applied):
![Screen Shot 2022-08-03 at 6 05 08 PM](https://user-images.githubusercontent.com/5135385/182741022-988e0e70-567f-433b-af5d-07f997bf1405.png)

cc @DrewKimball
