### ISSUE TITLE
storage: TestPebbleRestarts/engine/standards=17,randoms=10 flake

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#85526]
See [failure](https://teamcity.cockroachdb.com/viewLog.html?buildId=5954167&buildTypeId=Cockroach_UnitTests) in CI for unrelated PR.

Jira issue: CRDB-18291

Epic CRDB-16238

**Comment by jbowens** [comment]
Closing as dupe of #85515.
