### ISSUE TITLE
sql: implement ALTER FUNCTION statement

### ISSUE THREAD

**Issue by chengxiong-ruan** [cockroachdb/cockroach#85532]
Is your feature request related to a problem? Please describe.
A child of https://github.com/cockroachdb/cockroach/issues/58356

Describe the solution you'd like
Implement the ALTER FUNCTION statement. Including altering function options, owner, name, schema.
Alter function's "DEPEND ON EXTENSION" is not needed at the moment.

Jira issue: CRDB-18295

Epic CRDB-3405

**Comment by ajwerner** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/85942.
