### ISSUE TITLE
sql/schemachanger: prevent dropping columns referenced by TTL expression

### ISSUE THREAD

**Issue by ecwall** [cockroachdb/cockroach#85531]
I was planning on validating the `ttl_expiration_expression` using this when
1) TTL expression changes 
2) a column is dropped
3) a column type is altered
4) any others?

```
func ValidateTTLExpirationExpression(
	ctx context.Context,
	tableDesc catalog.TableDescriptor,
	semaCtx *tree.SemaContext,
	tableName *tree.TableName,
) error {

	if !tableDesc.HasRowLevelTTL() {
		return nil
	}

	ttl := tableDesc.GetRowLevelTTL()
	if !ttl.HasExpirationExpr() {
		return nil
	}

	expr, err := parser.ParseExpr(string(ttl.ExpirationExpr))
	if err != nil {
		return pgerror.Wrapf(
			err,
			pgcode.InvalidParameterValue,
			`value of "ttl_expiration_expression" must be a valid expression`,
		)
	}

	_, _, _, err = schemaexpr.DequalifyAndValidateExpr(
		ctx,
		tableDesc,
		expr,
		types.TimestampTZ,
		"ttl_expiration_expression",
		semaCtx,
		volatility.Stable,
		tableName,
	)
	return err
}
``` 

However, `catalog.TableDescriptor` is not available from https://github.com/cockroachdb/cockroach/blob/47d34c9dd0c63dfd462e4380a65470f4cf18e3d6/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go#L32.

Jira issue: CRDB-18294
Epic CRDB-14592

**Comment by rafiss** [comment]
> We don't currently support TTL-active tables in DROP COLUMN in the declarative schema changer so moving this to the backlog.

Could you say more about what this means from the user's perspective? Are you saying that it's impossible for a user to drop the column? Or are you saying that we don't want to implement this check in the old schema changer, so it's getting backlogged even though a user can still do it?

**Comment by ajwerner** [comment]
the `DROP COLUMN` code which detects that there's a `TTL` in the table will fall back to the legacy schema changer.

**Comment by rafiss** [comment]
OK, so to answer the earlier question, this means that a user can drop the column?

**Comment by ajwerner** [comment]
I don't think so -- at least, if I understand correctly, @ecwall added the validation he wanted in the legacy schema changer, so the drop will fail when the legacy code runs.

**Comment by rafiss** [comment]
No, I believe that was the ask with this ticket. I'm picking up the task from @ecwall, so I will work on adding the validation as part of #85497

**Comment by ajwerner** [comment]
I'm confused, I could have sworn this came out of an ask of how to do it in the declarative schemachanger (hence `sql/schemachanger`) because it was straightforward in the legacy schema changer.

**Comment by ajwerner** [comment]
Okay, yeah, I misunderstood.

**Comment by rafiss** [comment]
Ah OK, I see the source of even more of the confusion. The new schema changer currently only falls back `if n.Column == colinfo.TTLDefaultExpirationColumnName`, so it wasn't falling back when ttl_expiration_expression is used. I will fix the fallback logic too.

**Comment by rafiss** [comment]
Actually, I don't see any fallback logic at all. The new schema changer just is trying to detect the columns that can't be dropped, and show the user-facing error.

@ajwerner can you point me to the fallback logic you were thinking of?

**Comment by ajwerner** [comment]
Whoops, you're totally right. The logic is just to fail if you try to drop the expiration column.

**Comment by ajwerner** [comment]
I'll engage on this in a bit.
