### ISSUE TITLE
cdc: apparent consistency issue when pausing and resuming changefeeds

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#85533]
See https://github.com/cockroachdb/cockroach/pull/85277#issuecomment-1198618486 and further discussion. This was discovered during upgrade testing but is actually just triggered by pausing and resuming a changefeed. Unclear whether this is a testing issue or finding an actual case where we could drop messages during a pause and resume (that isn't being caught by nemesis testing for some reason). We need to figure this out.

Jira issue: CRDB-18296

**Comment by renatolabs** [comment]
> This was discovered during upgrade testing but is actually just triggered by pausing and resuming a changefeed.

@HonoreDB Were you able to reproduce the issue by pausing and resuming the changefeed? My experience with that tests is that just pausing and resuming is not sufficient to reproduce the consistency issue there; I need to actually stop and restart the binary on the nodes for the issue to manifest.

**Comment by HonoreDB** [comment]
Thanks for the correction! That makes sense, since our existing nemeses already included pausing and resuming the feed but not the node, so either a real bug or test framework issue would more likely have been caught already for the former. I'm digging into this now.

**Comment by HonoreDB** [comment]
Figured this out--it was a testing issue, although in a meta twist it was a consistency bug _within the nemesis test logic_.

**Comment by miretskiy** [comment]
> Figured this out--it was a testing issue, although in a meta twist it was a consistency bug within the nemesis test logic.

Do you have more details on this?

**Comment by HonoreDB** [comment]
>Do you have more details on this?

Details [here](https://github.com/cockroachdb/cockroach/pull/85277#discussion_r940584738) for when you're back from vacation
