### ISSUE TITLE
streamingccl: SHOW REPLICATION JOBS

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/cockroach#85566]
**Is your feature request related to a problem? Please describe.**
Easier observability of streaming on both source and destination.

**Describe the solution you'd like**
A `SHOW REPLICATION JOBS` command to display relevant information such as high water mark.

cc @samiskin 

Jira issue: CRDB-18312

**Comment by dt** [comment]
Heh, "streaming jobs" is another good example of why we need to fix the internal naming for this feature before it starts to leak into user-facing features/commands/docs.   The sooner we replace "streaming" with "replication" just about everywhere we're using the word on its own the better.
