### ISSUE TITLE
sql: support COPY TO

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#85571]
**Is your feature request related to a problem? Please describe.**
Postgres allows you to use COPY to get data out of the database. We'll use this issue to track this feature to see if it improves third party tool compatibility.

**Describe the solution you'd like**
Support for Postgres syntax:
```
COPY { table_name [ ( column_name [, ...] ) ] | ( query ) }
    TO { 'filename' | PROGRAM 'command' | STDOUT }
    [ [ WITH ] ( option [, ...] ) ]
```

https://www.postgresql.org/docs/current/sql-copy.html

Jira issue: CRDB-18315

Epic CRDB-18320

**Comment by z0mb1ek** [comment]
need this to use in clickhouse
