### ISSUE TITLE
storage/engine benchmark tests take forever because setup time is magnitudes greater than the time being measured

### ISSUE THREAD

**Issue by WillHaack** [cockroachdb/cockroach#8557]
We have code that looks like this:

```
for (i := 0; i < b.N; i++) {
  setup() // takes a while
  b.StartTimer()
  code_to_measure() // happens really quickly
  b.StopTimer()
}
```

Since the code_to_measure takes about 4000ns, N gets set to ~250,000 (since N \* time must be 1s by default in the go benchmark tool)

**Comment by WillHaack** [comment]
The code I'm referring to along with a suggested fix can be found here

https://github.com/cockroachdb/cockroach/pull/8558

**Comment by petermattis** [comment]
This was fixed.
