### ISSUE TITLE
sql: ensure stats collector does not block node startup

### ISSUE THREAD

**Issue by AlexTalks** [cockroachdb/cockroach#85582]
While most tasks run during node startup are asynchronous, those that are not have the possibility to block node startup.  One such example currently is [`Server.Start(..)` in pkg/sql/conn_executor.go](https://github.com/cockroachdb/cockroach/blob/9650b0d7ad344c2863846270db89f88c6ce08019/pkg/sql/conn_executor.go#L497), as when starting `PersistedSQLStats`, it synchronously loads the schedule by executing the following query: 
```
SELECT schedule_id FROM system.scheduled_jobs WHERE schedule_name = "sql-stats-compaction"
```
If this query encounters any contention, it will result in blocking node startup, which may hinder cluster operations as has been seen in a recent support escalation.  If at all possible, these tasks should be made asynchronous, and if not, we should see we can make an effort to reduce or remove the possible contention.

The call stack is as follows, starting in [`server.go:Server.PreStart(..)`](https://github.com/cockroachdb/cockroach/blob/9650b0d7ad344c2863846270db89f88c6ce08019/pkg/server/server.go#L994):
[`s.sqlServer.preStart(..)`](https://github.com/cockroachdb/cockroach/blob/9650b0d7ad344c2863846270db89f88c6ce08019/pkg/server/server.go#L1563) -> [`s.pgServer.Start(..)`](https://github.com/cockroachdb/cockroach/blob/9650b0d7ad344c2863846270db89f88c6ce08019/pkg/server/server_sql.go#L1228) -> [`s.SQLServer.Start(..)`](https://github.com/cockroachdb/cockroach/blob/9650b0d7ad344c2863846270db89f88c6ce08019/pkg/sql/pgwire/server.go#L411) -> [`s.sqlStats.Start(..)`](https://github.com/cockroachdb/cockroach/blob/9650b0d7ad344c2863846270db89f88c6ce08019/pkg/sql/conn_executor.go#L504) -> [`s.jobMonitor.start(..)`](https://github.com/cockroachdb/cockroach/blob/9650b0d7ad344c2863846270db89f88c6ce08019/pkg/sql/sqlstats/persistedsqlstats/provider.go#L103) -> [`j.ensureSchedule(..)`](https://github.com/cockroachdb/cockroach/blob/9650b0d7ad344c2863846270db89f88c6ce08019/pkg/sql/sqlstats/persistedsqlstats/scheduled_job_monitor.go#L70) -> [`j.getSchedule(..)`](https://github.com/cockroachdb/cockroach/blob/9650b0d7ad344c2863846270db89f88c6ce08019/pkg/sql/sqlstats/persistedsqlstats/scheduled_job_monitor.go#L148) -> [`QUERY`](https://github.com/cockroachdb/cockroach/blob/9650b0d7ad344c2863846270db89f88c6ce08019/pkg/sql/sqlstats/persistedsqlstats/scheduled_job_monitor.go#L121).

Additionally, if there are any other synchronous calls that could be blocking node startup during SQL server initialization, we should attempt to make them async if possible.

Jira issue: CRDB-18323

**Comment by AlexTalks** [comment]
Tagging @THardy98 in reference to the recent support issue mentioned.

**Comment by irfansharif** [comment]
+1, it seems non-ideal to block server startup unless we truly absolutely have to. The current pattern can cause any sort of txn contention in that table prevent new nodes being added or restarted, which seems bad.
