### ISSUE TITLE
streamingccl: more unit tests for tenant replication under the distributed mode (multiple nodes and scattered key ranges)

### ISSUE THREAD

**Issue by gh-casper** [cockroachdb/cockroach#85618]
We need more extensive unit tests to tenant replication under the distributed mode (multiple nodes and scattered key ranges).

Some behaviors we want to verify:
1. if one producer/ingestion processor node fail, does that trigger another replan?
2. Is the ingestion processor really capable of subscribing to multiple partitions?

Jira issue: CRDB-18346

**Comment by samiskin** [comment]
@gh-casper I've been looking at this today for https://github.com/cockroachdb/cockroach/issues/85283 , mind if I self-assign?

**Comment by gh-casper** [comment]
Sure @samiskin

**Comment by samiskin** [comment]
Completed by https://github.com/cockroachdb/cockroach/pull/85735
