### ISSUE TITLE
streamingccl: flaky TestTenantStreamingSuccessfulIngestion under stress race

### ISSUE THREAD

**Issue by gh-casper** [cockroachdb/cockroach#85615]
TestTenantStreamingSuccessfulIngestion under stream_replication_e2e_test.go can fail under --stress --race due to error when setting a cluster setting: "setting updated but timed out waiting to read new value".

Some other tests in this file also suffer from this error.

Jira issue: CRDB-18343

**Comment by msbutler** [comment]
this test no longer exists. closing.
