### ISSUE TITLE
add action button for idx recommendations

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#85611]
On the Insights page on the schema insights tab, we will show index recommendations. Add a button where we can execute the recommendation.
When clicking, it should pop a confirmation, letting the user know that it might impact the foreground traffic.
It should fail if the user doesn't have the right privileges.

Jira issue: CRDB-18340

**Comment by maryliag** [comment]
Can I get feedback on the confirmation modal? (When you click on create/replace index)

<img width="586" alt="Screen Shot 2022-08-15 at 10 35 49 AM" src="https://user-images.githubusercontent.com/1017486/184655881-a07ce549-bfdd-486e-a820-a6c18456deaf.png">
<img width="577" alt="Screen Shot 2022-08-15 at 10 36 13 AM" src="https://user-images.githubusercontent.com/1017486/184655892-47859ca2-ebd9-449f-ba05-eda020ae599a.png">

@kevin-v-ngo @jeremycbloom @stbof

**Comment by jeremycbloom** [comment]
Thanksthanks, @maryliag - can we put the code snippet in a container to align with that general UI pattern? 
![image](https://user-images.githubusercontent.com/24399608/184669195-1ba29b2f-2cf2-4bd9-a12d-f1ea99a18cd8.png)

**Comment by maryliag** [comment]
<img width="586" alt="Screen Shot 2022-08-15 at 1 50 55 PM" src="https://user-images.githubusercontent.com/1017486/184688584-3de93e66-151a-4aed-b075-8eca5d86977f.png">
 @jeremycbloom

**Comment by jeremycbloom** [comment]
Looks great!

**Comment by kevin-v-ngo** [comment]
FYI @maryliag https://cockroachlabs.atlassian.net/browse/DOC-5358

**Comment by maryliag** [comment]
Following the text updates from the issue mentioned on previous comment:

<img width="578" alt="Screen Shot 2022-08-16 at 6 42 04 PM" src="https://user-images.githubusercontent.com/1017486/184997729-4276fe78-5b90-448c-982c-a0eccc9327b4.png">
<img width="574" alt="Screen Shot 2022-08-16 at 6 42 12 PM" src="https://user-images.githubusercontent.com/1017486/184997735-1b90f860-493d-46f4-8fe0-111e8dbbaad9.png">

**Comment by stbof** [comment]
The message seems kind of long to me and there's a mismatch of number (Schema changes, until a change completes). My apologies. I think you can drop "until a change completes".
