### ISSUE TITLE
streamingccl: more metrics on both producer and ingestion side

### ISSUE THREAD

**Issue by gh-casper** [cockroachdb/cockroach#85617]
We should give another pass on what we lack in terms of metrics, especially now we have support for MVCC bulk ops. There are some obvious things I can think of now:

1. size of SST ingested
2. the number of SST events in which the SST span exceeds the bounds of the registered span. (the likelihood we need to trim the SST data)
3. number of timeouts
4. number of producer cancellation
5. producer initial scan error
6. producer stream terminated with error

The list goes on...

Jira issue: CRDB-18345

**Comment by stevendanna** [comment]
We've got many of these. We'll add more as needed.
