### ISSUE TITLE
streamingccl: TestTenantStreamingDeleteRange is flaky

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#85630]
**Describe the problem**

The test fails quickly under stress:

`./dev test ./pkg/ccl/streamingccl/streamingest --filter TestTenantStreamingDeleteRange --stress`

Jira issue: CRDB-18349

**Comment by adityamaru** [comment]
Under stress I've gone 5+ mins without a failure I suspect https://github.com/cockroachdb/cockroach/pull/85866 fixed this and we just forgot to unskip.
