### ISSUE TITLE
kv: snapshot efficiency investigation and findings

### ISSUE THREAD

**Issue by KnightAsterial** [cockroachdb/cockroach#85635]
This issue serves as a centralized location for all of the experiments and findings related to the snapshot bottleneck and efficiency investigation done in Summer 2022. Work was done by @KnightAsterial with help from @AlexTalks 

The primary findings of the investigation are summarized in the following documents:
- [Snapshot Investigation: Resource Bottlenecks](https://docs.google.com/document/d/1p7tlCx5aNG_iBxczmKcQBnbRdUbd3K2EbwEIafYhX8k/edit?usp=sharing)
- [Snapshot Investigation: Foreground Traffic](https://docs.google.com/document/d/1kKv9pcEBXl4n3JS-SGz5qx6i4JZfqbQQJrVAHYPWI4A/edit?usp=sharing)

**There are a series of recommendations, next steps, and open questions that are detailed in the above two documents.**

I have also recorded all the experimental results in the following documents. The results recorded are much more verbose but not as organized, so I recommend using the following documents as references in case anyone wants to dig deeper into the findings above.
- [Investigation Part 1](https://docs.google.com/document/d/15yN4oEfWLfOuFIdxQ-JvoF3a6w1MoUVtqyi_FA3hkp0/edit?usp=sharing)
    - Network experiment, Preliminary disk experiment, and Rate-limit experiments
- [Investigation Part 2](https://docs.google.com/document/d/1nKqTPyNkM1Gp-Bb-mL5AKLXYW7obhVL0CIzZeE9o6XQ/edit?usp=sharing)
    - Effects of changing `kv.snapshot_sender.batch_size` and `kv.snapshot_sst.sync_size`
- [Investigation Part 3](https://docs.google.com/document/d/1cZT4ixiC7e3SYl0heytMHMqvrnwqZH6jj9UCKOwOK5w/edit?usp=sharing)
    - Large range experiment, foreground traffic experiments
- [Investigation Part 4](https://docs.google.com/document/d/14fJ27I3smnOEqvnFworcCgXESFD7bZ_NmmmiYRrR-gA/edit?usp=sharing)
    - Miscellaneous investigations

The scripts to run the aforementioned experiments can be found here: [https://github.com/cockroachlabs/snapshot-bottleneck-scripts](https://github.com/cockroachlabs/snapshot-bottleneck-scripts)
The experiments were all ran off of the branch published in this draft PR: https://github.com/cockroachdb/cockroach/pull/85029

After this investigation, some research was done into using gRPC flow control as a means of admission control. [Findings can be found here](https://docs.google.com/document/d/1-HmT5BuIJNrG3Q7IWhi3RC2_Fvio1cmOSzq_RcjbMnQ/edit?usp=sharing).

Jira issue: CRDB-18352

**Comment by mwang1026** [comment]
Thanks @KnightAsterial really useful to have this documented and referenc-able. I'm going to close it since it doesn't specify clear actions but we'll link back to it from any work we do that touches some of the learning here.
