### ISSUE TITLE
ui: DB Console Metrics takes a long time to render graphs and sometimes fails to load at all for 22.1.5 clusters 

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#85636]
**Describe the problem**

Customers and the field team have been reporting major UI issues affecting CRDB 22.1.4 and 22.1.5 - where metrics/graphs either take a long time to load in DB Console, or at times even fail to load at all with a "Something went wrong" state. Both are regressions 

![image (24)](https://user-images.githubusercontent.com/1474303/182934221-032c4015-eec2-4ba0-8c46-8599537edf3a.png)
<img width="1892" alt="image (26)" src="https://user-images.githubusercontent.com/1474303/182934234-6cbd60ff-e5a0-457a-a324-8eacef2986a9.png">

**To Reproduce**

Links to Loom recordings will be shared on the equivalent Jira ticket.

**Environment:**
 - CockroachDB version 22.1.5 (it's also been reported to happen for 22.1.4)

**Additional context**
- Affected clusters tend to be running with 35+ or 45+ nodes 

Jira issue: CRDB-18353

gz#13551

gz#13591

**Comment by daniel-crlabs** [comment]
This impacts both cockroach cloud and cockroach on prem customers, as long as they are running `22.1.5`. I attempted to obtain screenshots from sql, hardware and overview pages; only the top graph would load, independently of the time frame I chose. Affected nodes are not only large nodes, I tested 5 different cloud customers, all with 9 nodes or less and they all showed this same behavior.
This not only impacts our customers, but also impacts our ability to troubleshoot issues for our customers.

**Comment by andreimatei** [comment]
@daniel-crlabs it'd be useful if you attached something private pointing to one or two CC clusters where this happens

**Comment by daniel-crlabs** [comment]
> @daniel-crlabs it'd be useful if you attached something private pointing to one or two CC clusters where this happens

@andreimatei there are were quite a few. I'm not sure how to attach a private comment to gh, but we have a view which you can choose and pick the larger clusters (ones with 5 + nodes) that are running `22.1.5` and you'll be able to see this behavior.

I'll add the link to the jira ticket, I think that's internal.

**Comment by ddtort** [comment]
Some context that may help here... here's a look at a v21.2.x cluster that loads well on the left and a v22.1.5 cluster that takes a long time to load on the right here. The initial request for data goes through for both but all subsequent requests to stream more recent data gets queued and hangs for the 22.1.5 cluster

![Screenshot 2022-08-08 at 11 28 04 AM](https://user-images.githubusercontent.com/104846689/183457592-bb62eb88-3b50-4257-a91d-df574d78d08a.png)

**Comment by daniel-crlabs** [comment]
Passing the question along, please see below from one of our CEAs:

>What release will this be in: https://github.com/cockroachdb/cockroach/issues/85636
>
>We can't close the ticket until this has been backported and tested, thanks.

**Comment by thtruo** [comment]
Thanks @daniel-crlabs - the team is currently on it. If we can merge the fix by ~Aug 16, that will fall in the 22.1.6 release. If we miss that train, then it'll be 22.1.7
We won't have a confirmation yet until a PR is up hopefully soon

**Comment by thtruo** [comment]
Updated assignees and `T-` labels since @koorosh is taking the baton from @dhartunian

**Comment by daniel-crlabs** [comment]
Thank you my friends, I'll pass that info along to the customer, appreciate the update.

**Comment by thtruo** [comment]
Changes should be merged in time for 22.1.6
Related fixes that should resolve this issue include:
* https://github.com/cockroachdb/cockroach/pull/86157
* https://github.com/cockroachdb/cockroach/pull/85835
* https://github.com/cockroachdb/cockroach/pull/86066

**Comment by ccampbell-crl** [comment]
@thtruo  Is there currently a workaround for this issue or are customers expected to deal with this issue until they upgrade? Hard Rock is also currently having this issue on 22.1.5

**Comment by thtruo** [comment]
@ccampbell-crl the patches to those issues were recently merged, so they are only available in 22.1.6 

Unfortunately they will still encounter those regressions if they're on 22.1.5 - we have not found workarounds for that release

**Comment by thtruo** [comment]
Closing this issue as patches have rolled out into the 22.1.6 release
