### ISSUE TITLE
ci: test timeouts are not shown clearly

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#85651]
Here is a Github CI run that shows that the tests from `pkg/ccl/sqlproxyccl` timed out. It clearly shows that `TestAuthenticateOK` did not complete and is the likely cause. It also includes instructions on how to view `full_output.txt` to see more test logs. https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/5976935?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/1320573/183000545-47a78723-ff76-45c7-bda8-1cf2d92a8772.png">

Here is the Bazel CI run for the same PR, which is missing this info and the instructions: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/5976917?showRootCauses=false&expandBuildChangesSection=true&expandBuildDeploymentsSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true
<img width="889" alt="image" src="https://user-images.githubusercontent.com/1320573/183000654-760c4f6a-20b7-435c-93a3-92bee8049aa0.png">

Jira issue: CRDB-18359
Epic CRDB-8349

**Comment by rickystewart** [comment]
As of `master`, timeouts should be much more readable. @healthy-pod did some work in this area to make sure that `go test` timeouts come through before Bazel-level timeouts.

<img width="734" alt="Screen Shot 2022-10-10 at 6 08 38 PM" src="https://user-images.githubusercontent.com/3423966/194965340-5031c7ec-0cd0-4ba1-b732-04c27b530060.png">
