### ISSUE TITLE
ci: test failures caused by panics are not clear

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#85650]
Here is a Github CI run that shows a test failure on `TestConnector_OpenTenantConnWithToken/error_during_auth` caused by a panic: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/5978643?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/1320573/183000044-76365bdb-94f2-4269-8f8f-83422442567f.png">

Here is the Bazel CI run for the same PR, which is missing this info: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/5978667?showRootCauses=false&expandBuildChangesSection=true&expandBuildDeploymentsSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true&logFilter=debug
<img width="898" alt="image" src="https://user-images.githubusercontent.com/1320573/183000146-c39e16fc-77c4-49a2-a849-c589fd223193.png">

Jira issue: CRDB-18358
Epic CRDB-8349

**Comment by rickystewart** [comment]
The panic info is buried in the build log. Unfortunately clicking on "Open in build log" *doesn't* bring you to the spot in the log where the panic that can be found.
