### ISSUE TITLE
server: /_status/logs/:node_id endpoint does not respect given node ID

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#8567]
cc @BramGruneir

When I call this API endpoint with invalid node IDs, I still receive logs. I expect to get nothing back.

Looking at the code, it looks like we're always returning logs from the current node.

**Comment by BramGruneir** [comment]
If I recall correctly, the reason we didn't do the redirecting of log requests was to avoid sending a lot of data through a node.  So log requests should go directly to the node.  I'm not sure how much of a problem this is and it might be best to just forward the request unless we see a problem.

It should be relatively easy to add the redirect.  Look at the any of the `if !local {` sections in the other handlers.

**Comment by spencerkimball** [comment]
Let's get this fixed for 1.0. Should be simple.

**Comment by petermattis** [comment]
This was fixed in #13947.
