### ISSUE TITLE
cli: deprecate the use of a combined SQL+RPC port

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#85670]
Discussed with @catj-cockroach  and @bdarnell .

The current capability of CockroachDB to receive both RPC and SQL connections on the same TCP port is cute but has overstayed its welcome. We have two different griefs with it, one old and one new:

- it makes the TLS security story difficult. We've learned that customers are anxious to use their own TLS PKI for the SQL traffic (including issuing server certs). However, it's hard to orchestrate a cluster if the customer PKI is also used for the node certs, used for node-node connections. The better situation will be when we use different CA/cert combinations for RPC and SQL traffic. Our current TLS config that pairs them on the same TCP port makes this hard.

- sooner or later, we will want to transition existing deployments to use a multi-process solution. In order to enable this, we will want to create a duplicitous situation where it's not distinguishable from the network whether crdb is deployed as 1 process or 2. So we want two separate ports from the get-go, so that we can separate them into different processes.

To move forward with this, we will deprecate the use of a combined port in v22.2, and then remove this support altogether in v23.1 This will unlock our ability to improve the situations above.

(NB: The CockroachCloud infra  already uses separate ports, so this change would only affect self-hosted customers).

Epic: CRDB-18404
Jira issue: CRDB-18376

**Comment by bdarnell** [comment]
A third reason to make this change is for defense-in-depth for security vulnerabilities: Running both SQL and GRPC on separate ports makes it possible (and often advisable) to apply different firewall policies to each category of traffic. In many deployments access to the GRPC port can be more restricted than the SQL port, and doing so may help mitigate GRPC-level security issues (I'm thinking of a major bug that occurred back in the CockroachDB 2.0 days, which would have been catastrophic if it had occurred in CockroachCloud with both services running on the same port).
