### ISSUE TITLE
Cannot view table structures/rows and unexpected query failures after 21.2.13 --> 22.1.5 upgrade

### ISSUE THREAD

**Issue by moogzy** [cockroachdb/cockroach#85698]
**Describe the problem**

Upon upgrading to 22.1.5 from 21.2.13 the following errors are observed:

// When trying to view table columns/structure

```
ERROR: pq: mod(): fnv32(): incompatible COALESCE expressions: unknown signature: to_char(timestamptz)
```

// When trying to run queries

```
Raw query failed. Code: `42883`. Message: `db error: ERROR: mod(): fnv32(): incompatible COALESCE expressions: unknown signature: to_char(timestamptz)
```

The latter error code concerns us... as that maps to `Undefined function` in PG/Cockroach error codes.

The clusters involved have not been finalised yet on 22.1.5. We configured `cluster.preserve_downgrade_option` to `21.2` to ensure that we can test on the new version before finalising the cluster and losing the ability to rollback.

**To Reproduce**

We have a case open with CockroachDB (#13564) because we don't actually know what is causing the problem, except the following:

1. Upgrade from 21.2.13 --> 22.1.5
2. Try to view the table structure or rows on selected tables, e.g `SHOW COLUMNS FROM $table_name`
3. Observe error `ERROR: pq: mod(): fnv32(): incompatible COALESCE expressions: unknown signature: to_char(timestamptz)`

**Expected behavior**
Upgrade from 21.2.X --> 22.1.5 should be seamless and allow for query functionality to operate without issue, even before finalising the cluster.

We don't want to finalise the cluster automatically because we want to test functionality while maintaining the ability to rollback if necessary. Thus we don't consider "you need to finalise the cluster" and acceptable solution here, if that was the case.

**Environment:**
 - CockroachDB version 22.1.5
 - Server OS: Running on k8s using CRDB containers.

**Additional context**
We are unable to progress with rolling out 22.1.X to all of our clusters until this is resolved.

Jira issue: CRDB-18386

**Comment by moogzy** [comment]
@massimocGH (FYI this is related to the Mr Yum support case).

**Comment by rafiss** [comment]
Thanks for this report. Can you share the `CREATE TABLE` definition for this table?

**Comment by rafiss** [comment]
I see this is already being addressed on the internal ticket: https://github.com/cockroachlabs/support/issues/1745
