### ISSUE TITLE
why only reuse the provide slice only if the first extra byte is 0 in BytesNext function?

### ISSUE THREAD

**Issue by yaojingguo** [cockroachdb/cockroach#8570]
In https://github.com/cockroachdb/cockroach/blob/develop/roachpb/data.go, there is the following code:

```go
func BytesNext(b []byte) []byte {
	if cap(b) > len(b) {
		bNext := b[:len(b)+1]
		if bNext[len(bNext)-1] == 0 {
			return bNext
		}
	}
	...
}
```

Why `BytesNext` does not reuse `b` if `bNext[len(bNext)-1] != 0`?. Why not change it to something like:

````go
func BytesNext(b []byte) []byte {
	if cap(b) > len(b) {
		bNext := b[:len(b)+1]
		if bNext[len(bNext)-1] != 0 {
			bNext[len(bNext)-1] = 0
		}
		return
	}
	...
}
```

**Comment by petermattis** [comment]
`BytesNext` needs to maintain the invariant that we don't alter the buffer backing the slice as it is potentially shared by other slices. Extending the length of a slice does not alter the buffer, but your suggested change would.

PS There are likely cases where we don't need to maintain the invariant that the buffer backing the slice is unmodified, but there is a lot of code that needs to be audited to verify the safety of such a change. It would be safer to add a new function that could be called from wherever it was deemed safe to change the buffer, guided, of course, by profiling which indicates this is a worthwhile optimization.

**Comment by yaojingguo** [comment]
I am clear.
