### ISSUE TITLE
kv: add command to check whether a span is empty

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#85726]
**Is your feature request related to a problem? Please describe.**
Issue https://github.com/cockroachdb/cockroach/issues/70427 asks that the GC job wait until the data in the relevant spans has been GC'd by the MVCC GC queue before removing the descriptor and zone configs for that table. In the case where a range contains multiple tables, or in the case where a GC job is removing data from an index, it's not clear how to check whether GC has occurred. If we were to wait on a GC threshold, we might be waiting forever, or not long enough. 

One approach might be to use an `ExportRequest` and wait until that comes back empty. Sadly, the `ExportRequest` has no way to return zero bytes while indicating whether data exists (the `ScanRequest` does have such functionality). We'd need to rely on the `ExportRequest` because there's no way to ask a `ScanRequest` to look at all versions/

**Describe the solution you'd like**
A simple, read-only request which would be relatively cheap to issue which can discern whether there exists any versions of any keys, live or dead in some key span. The DistSender should not parallelize this, as we'd expect the relevant ranges to be merged together if they are empty. The latching doesn't really matter because we expect these spans to be empty and unaccessed.

Jira issue: CRDB-18402

Epic CRDB-2624

**Comment by erikgrinaker** [comment]
Could we just have a look at the MVCC stats instead? We have SQL functions to access it.

Otherwise, I think we may want new command for this, because we'll have to read below the GC threshold (which is generally not allowed).

**Comment by ajwerner** [comment]
The problem with that is that the key-span may be in a range with more table data in it. Indeed, in serverless, this is the expectation. Also, when the GC does happen, we expect ranges to get merged away.

**Comment by ajwerner** [comment]
> Otherwise, I think we may want new command for this, because we'll have to read below the GC threshold (which is generally not allowed).

Heh I've been thinking about just this moments ago.

**Comment by erikgrinaker** [comment]
Ok, I'll prototype something tomorrow.
