### ISSUE TITLE
sql: `crdb_internal.force_delete_table_data` should use `DeleteRange` in 22.2

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#85754]
**Is your feature request related to a problem? Please describe.**
Relates to https://github.com/cockroachdb/cockroach/issues/70427. Maybe the system tenant should be able to issue `ClearRange` optionally, but it's not totally clear. The secondary tenants shouldnot.

**Describe the solution you'd like**

Change the `ClearRange` code after the version is active to use `DeleteRange` with tombstones.

Jira issue: CRDB-18423

Epic CRDB-2624

**Comment by erikgrinaker** [comment]
@ajwerner Is this something that SQL schema can pick up?

**Comment by ajwerner** [comment]
Yes

**Comment by erikgrinaker** [comment]
We should get this in now that we're entering stability.

**Comment by ajwerner** [comment]
Opened up https://github.com/cockroachdb/cockroach/pull/86137, will see if there is any fallout.
