### ISSUE TITLE
Add friendlier error message when using SHOW RANGES for Serverless clusters

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#85750]
**Is your feature request related to a problem? Please describe.**
Until we support https://github.com/cockroachdb/cockroach/issues/83839 `SHOW RANGES errors out for a Serverless cluster` we should at the very least present a more friendly error message when a user attempts to use `SHOW RANGES` or `SHOW RANGE FOR ROW` SQL commands in a Serverless cluster.

**Describe the solution you'd like**
We can use language along the lines of "SHOW RANGES is not yet supported for multi-tenant clusters". Copy tbd - looping in @andf-crl for copy inspiration. 

Jira issue: CRDB-18419

**Comment by knz** [comment]
we've fixed this
