### ISSUE TITLE
CONTRIBUTING.md instructions don't work on a fresh OS X install

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#8578]
I'm not sure whether it's an issue with the contributing instructions, our dependency management, or the Makefile, but something isn't right for someone that has just the bare minimum of things installed. If I try to run make, I get:

```shell
$ make build
Makefile:219: .bootstrap: No such file or directory
# cd /Users/alex/go/src/cloud.google.com/go; git rev-parse HEAD
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD
exit status 128
make: *** [.bootstrap] Error 1
```

My machine meets the stated prerequisites of the guide (C++ compiler > v6.0, go v1.6, git > v1.8, and bash) with the one exception that I have go 1.6.3 instead of 1.6.2. I believe my go environment is set up correctly:

```shell
$ echo $GOPATH
/Users/alex/go
$ pwd
/Users/alex/go/src/github.com/cockroachdb/cockroach
```

And I downloaded cockroach and its dependencies by running `go get -d github.com/cockroachdb/cockroach`, as instructed by the guide.

I'll see if I can figure out the problem and fix the guide.

**Comment by RaduBerinde** [comment]
Hi Alex,

This is a bug I run into every now and then. I don't know exactly why but the git repository of a dependency gets all screwed up. I usually go to the dependency's dir and do something like `git fetch; git checkout master; git reset --hard origin/master`

In this case I don't see exactly what dependency hit that error.. Is that the entire output of `make build`?

**Comment by RaduBerinde** [comment]
Ah it's there, `/Users/alex/go/src/cloud.google.com/go`.  I would go to that dir, do `git fetch; git checkout master; git reset --hard origin/master` and try again.

**Comment by bdarnell** [comment]
It looks like this has been caused (or at least made more common) by my PR robfig/glock#34.

**Comment by a-robinson** [comment]
Yeah, there are a handful of repositories that got left in an empty state by the `go get -d` command.

```shell
$ ls -a /Users/alex/go/src/cloud.google.com/go
.       ..      .git
$ cd /Users/alex/go/src/cloud.google.com/go
$ git status
On branch master

Initial commit

nothing to commit (create/copy files and use "git add" to track)
```

I'll look into how the repos may have gotten left in an empty state.

**Comment by petermattis** [comment]
@a-robinson Definitely worthwhile to pull on this thread quickly. This problem is affecting developers, external folks and CI builds. 

Cc @BramGruneir

**Comment by a-robinson** [comment]
@tamird threw together an upstream fix in https://github.com/robfig/glock/pull/36
