### ISSUE TITLE
logictestccl: TestTenantLogic_schema_change_feature_flags is flaky

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#85792]
**Describe the problem**

The test `TestTenantLogic_schema_change_feature_flags` flaked out in a pre-merge CI run (of #85784). See [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=6017346&buildTypeId=Cockroach_BazelEssentialCi).

Running on the same branch as the PR, and under stress yielded no failures.

Jira issue: CRDB-18435

**Comment by yuzefovich** [comment]
dup of #81167
