### ISSUE TITLE
storage: read degradation with MVCC range tombstones

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#85808]
When running `kv95` on a cluster with a single, global MVCC range tombstone, performance gradually deteriorates.

* [`kv95/enc=false/nodes=3/cpu=32`](https://roachperf.crdb.dev/?filter=&view=kv95%2Fenc%3Dfalse%2Fnodes%3D3%2Fcpu%3D32&tab=gce)

<img width="843" alt="Screenshot 2022-08-09 at 16 41 40" src="https://user-images.githubusercontent.com/644420/183678208-1f78a770-d2fa-425f-8c51-b2cd596ce1f8.png">

* [`kv95/enc=false/nodes=3/cpu=32/mvcc-range-keys=global`](https://roachperf.crdb.dev/?filter=&view=kv95%2Fenc%3Dfalse%2Fnodes%3D3%2Fcpu%3D32%2Fmvcc-range-keys%3Dglobal&tab=gce)

<img width="827" alt="Screenshot 2022-08-09 at 16 40 53" src="https://user-images.githubusercontent.com/644420/183678054-2e0de352-c72a-450c-b3c4-e40536f6a9f7.png">

Jira issue: CRDB-18440

**Comment by erikgrinaker** [comment]
Any idea what's going on here @jbowens? Are we seeing anything similar with Pebble benchmarks?

**Comment by jbowens** [comment]
Our longer-duration Pebble benchmarks don't run with range keys yet, so we don't have anything similar to consult. I wonder if it could be an artifact of still producing too many allocations, adding GC pressure and memory fragmentation as the test progresses?

I'll work on squashing those remaining allocations.

**Comment by jbowens** [comment]
Actually, this is almost definitely cockroachdb/pebble#1861. I've been having trouble getting the invariants right, but I'll try to get a PR up today.

**Comment by erikgrinaker** [comment]
Ah right, because the number of blocks increases as we write? That checks out.

**Comment by jbowens** [comment]
Fixed with change to avoid defragmenting beyond iterator bounds or prefix.
