### ISSUE TITLE
ui: show variance in execution stats bar graph

### ISSUE THREAD

**Issue by xinhaoz** [cockroachdb/cockroach#85816]
Currently, the execution stats bar graphs in the stmt details page only show the mean over time from the stats received by the server. We should include the error margin for better troubleshooting.

Jira issue: CRDB-18447

**Comment by bobvawter** [comment]
Please note that this is a regression from previous iterations of the UI and has been a useful signal when ruling in/out whether or not observed workload performance is region-specific.  Thanks.
