### ISSUE TITLE
sql/schemachanger: ALTER PRIMARY KEY deletes the implicit rowid column if present

### ISSUE THREAD

**Issue by Xiang-Gu** [cockroachdb/cockroach#85814]
This issue is open to track the progress of implementing `ALTER PRIMARY KEY` when the old 
PK is on the implicitly created rowid column, which requires us to delete this rowid column
when the PK is altered. This is a subtask of the meta issue https://github.com/cockroachdb/cockroach/issues/83932.

Jira issue: CRDB-18444

**Comment by rafiss** [comment]
Is this the same as https://github.com/cockroachdb/cockroach/issues/80149 ?

**Comment by postamar** [comment]
Yes, closing as duplicate. Thanks!
