### ISSUE TITLE
observability infra: Test_logic_inflight_trace_spans flaked

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#85812]
Test_logic_inflight_trace_spans [flaked](https://teamcity.cockroachdb.com/viewLog.html?buildId=6026030&buildTypeId=Cockroach_UnitTests) on unrelated CI run.

Jira issue: CRDB-18442

**Comment by ajwerner** [comment]
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/6118968?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true
