### ISSUE TITLE
sql: support COPY FROM

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#8585]

**Comment by drewdeally** [comment]
it would be useful to get this back on the roadmap to enable CDC products such as Attunity to use the Postgres COPY command to load Cockroach tables.   Currently, Attunity snapshot/full load fails with following error.  

```Failed to start load process for file '6'
Failed to wait for previous run
Command failed to load data with exit error code 1, Command output: ERROR:  at or near ",": syntax error
DETAIL:  source SQL:
COPY  "public"."customer" FROM STDIN WITH DELIMITER ',' CSV NULL 'attNULL' ESCAPE '\'
                                                    ^

Failed to start load process for file '4'
Failed to wait for previous run
Command failed to load data with exit error code 1, Command output: ERROR:  at or near ",": syntax error
DETAIL:  source SQL:
COPY  "public"."customer" FROM STDIN WITH DELIMITER ',' CSV NULL 'attNULL' ESCAPE '\'
                                                    ^

Failed to start load process for file '2'
Failed to wait for previous run
Command failed to load data with exit error code 1, Command output: ERROR:  at or near ",": syntax error
DETAIL:  source SQL:
COPY  "public"."customer" FROM STDIN WITH DELIMITER ',' CSV NULL 'attNULL' ESCAPE '\'
                                                    ^
```

via psql. 

Alternative is to switch to ODBC driver using conventional inserts which can take up to 60 hours to load 

![image](https://user-images.githubusercontent.com/39496073/87714961-93ede380-c77a-11ea-8ef5-f92616f098ae.png)


Compared to a few minutes with COPY.

**Comment by mjibson** [comment]
Can they not use IMPORT if they are ingesting a CSV file?

**Comment by drewdeally** [comment]
Yes, but it requires a large engineering effort on their part and perhaps other CDC ISV.

I have added a workaround method for consideration

https://docs.google.com/document/d/1kz3yYJ46mkEG3jVSQAGZn6gGbHxhXsiKHHbRYJR0szM/edit

**Comment by mjibson** [comment]
I've opened #51891 to track COPY CSV support.
