### ISSUE TITLE
sql: tracking issue to re-enable tests which wait for GC job

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#85876]
**Is your feature request related to a problem? Please describe.**
In https://github.com/cockroachdb/cockroach/issues/70427 we make the GC job rely on the MVCC GC queue to make progress. This queue is hard to control from tests. There are some tests which wait for the GC job to complete. For now, to make progress on #70427, we are skipping some of these tests. This issue tracks unskipping them. 

- [x] TestGCTableOrIndexWaitsForProtectedTimestamps
- [x] TestDropDatabaseDeleteData
- [x] TestDropIndex
- [x] TestDropTableDeleteData
- [x] TestDropTableWhileUpgradingFormat
- [x] TestDropDatabaseWithForeignKeys
- [x] TestTxnObeysTableModificationTime

Maybe a different reason:
- [x] TestSchemaChangeGCJob (https://github.com/cockroachdb/cockroach/issues/60664)

Jira issue: CRDB-18471

**Comment by chengxiong-ruan** [comment]
All tests are enabled.
