### ISSUE TITLE
sql: COPY with implicit transaction isn't atomic

### ISSUE THREAD

**Issue by cucaroach** [cockroachdb/cockroach#85887]
COPY with an implicit transaction is supposed to be atomic, ie if any row fails the whole copy should be rolled back and no parts of the COPY should be visible before the rest.  Early efforts to improve performance and throughput of COPY led us to chunk COPY into 100 row transactions but this should be fixed.  

Epic CRDB-18320

Jira issue: CRDB-18479

**Comment by rafiss** [comment]
This maybe could relate to the `FREEZE` option: https://github.com/cockroachdb/cockroach/issues/85573

**Comment by cucaroach** [comment]
Interestingly we seem to handle one big transaction just fine now.  Even doing 750k rows in one insert works okay (memory just spikes pretty high).  I wonder if I should just fix this to be correct (ie use 1 transaction) and have a COPY flag or cluster setting to opt in to the old broken behavior?   The issue would be if the cluster is busy and we had to do restarts could it get ugly with massive transactions?   I'm inclined to say correctness trumps performance and we should just bite the bullet with a safety value to go back to old behavior.   @vy-ton thoughts?

**Comment by vy-ton** [comment]
> I'm inclined to say correctness trumps performance and we should just bite the bullet with a safety value to go back to old behavior.

SGTM with the setting to revert to the old behavior. It is worth noting that there's [discussion](https://cockroachlabs.slack.com/archives/C01RX2G8LT1/p1659115638756889) about adding batching to other statements similar to what COPY did before this issue. In the future, maybe we should revisit syntax to opt-in to automatic batching if you don't care about atomicity.
