### ISSUE TITLE
ui: write node clock offset interval to time series

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#859]
We should periodically write the offset interval as measured by all nodes to a time series.

**Comment by spencerkimball** [comment]
There is a TODO for it in rpc/clock_offset.go:MonitorRemoteOffsets

**Comment by thschroeter** [comment]
I would like to work on this if it is still current. Can you outline how to implement this? Should we record the offset of the local node found in [MonitorRemoteOffsets](https://github.com/cockroachdb/cockroach/blob/d68b0c1eca5215a6be2b64d8d8aeb1b7cc15a33d/rpc/clock_offset.go#L152) to the [NodeStatusRecorder](https://github.com/cockroachdb/cockroach/blob/0e8d3a04c5c4fb252aecabc5d28b2c8768f66901/server/server.go#L193)?

**Comment by tamird** [comment]
@mrtracy can you mentor?
