### ISSUE TITLE
CSV IMPORT fails for columns with enum type and default value

### ISSUE THREAD

**Issue by dejan-lokar** [cockroachdb/cockroach#85903]
**Describe the problem**

IMPORT INTO statement fails when importing CSV data into a table with an enum column type that has a default value.

**To Reproduce**

1. setup schema and a test row
```
CREATE TYPE IF NOT EXISTS teststate AS ENUM ('ENABLED', 'DISABLED');

CREATE TABLE table1
(
    id STRING NOT NULL,
    state teststate NOT NULL DEFAULT 'DISABLED' -- does not work
    -- state teststate NOT NULL -- works
);

INSERT INTO test1 (id, state) VALUES
    ('id1', 'ENABLED');
```

2. export table data into CSV
```
EXPORT INTO CSV 's3://bucket1' FROM TABLE db1.table1
```

3. import CSV
```
IMPORT INTO db1.table1 CSV DATA ('s3://bucket1/FILENAME')
```

Step #3 fails with the following error:
`pq: s3://test-bucket/export170a08f5d51fbaf10000000000000001-n786690423440965633.0.csv?AWS_ACCESS_KEY_ID=****&AWS_ENDPOINT=****&AWS_REGION=us-east-2&AWS_SECRET_ACCESS_KEY=****: process default and computed columns: type OID 100112 does not exist`

**Environment:**
 - CockroachDB version 21.1.9

Jira issue: CRDB-18484
Epic CRDB-17785

**Comment by ZhouXing19** [comment]
This has been fixed by https://github.com/cockroachdb/cockroach/commit/560842472be95c6952d6c9bf4907b28b50bcef55 from v22.1.0 and forward. The test can be found here: https://github.com/cockroachdb/cockroach/blob/3f0031136e8ec92ac370107d527e2dae552bf03a/pkg/sql/importer/import_stmt_test.go#L1454-L1469
