### ISSUE TITLE
schemachanger: support ALTER TABLE ... ADD COLUMN ..., DROP COLUMN ...

### ISSUE THREAD

**Issue by postamar** [cockroachdb/cockroach#85915]
This requires some kind of transient primary index which includes both the added & dropped columns.

Epic: CRDB-19158

Jira issue: CRDB-18489

**Comment by postamar** [comment]
The transient index is a thing now so this issue is now more about making the builder able to "promote" an existing ToPublic target to ToTransient. We should be able to handle not just the "comma case" of `ALTER TABLE ... ADD COLUMN ..., DROP COLUMN ...` but also 
```
BEGIN;
ALTER TABLE ... ADD COLUMN ...
ALTER TABLE ... DROP COLUMN ...
COMMIT;
```
In both cases when the builder handles DROP COLUMN it should change the primary index target added by ADD COLUMN from ToPublic to ToTransient instead of toAbsent.

**Comment by ajwerner** [comment]
It'd be nice to try to get this done some time in October. It's not too hard to do it now. I would like to believe that this and the constraints are "up next"

**Comment by postamar** [comment]
Agreed!

**Comment by rafiss** [comment]
resolved by https://github.com/cockroachdb/cockroach/pull/99526 and https://github.com/cockroachdb/cockroach/pull/110851
