### ISSUE TITLE
sql: col_label grammar element needs to be renamed

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/cockroach#8593]
### Problem
The [`col_label`](https://www.cockroachlabs.com/docs/sql-grammar.html#col_label) grammar element reads as "column label" but can be used to refer to elements other than column labels, such as table names and index names. This ambiguity makes the use of `col_label` feel very unintuitive, which is problematic because it shows up very commonly if you parse through the grammar by hand.

### Example
For example, using `databaseName.tableName` in [`truncate_stmt`](https://www.cockroachlabs.com/docs/sql-grammar.html#truncate_stmt) chains through:

1. [`relation_expr_list`](https://www.cockroachlabs.com/docs/sql-grammar.html#relation_expr_list)
2. [`relation_expr`](https://www.cockroachlabs.com/docs/sql-grammar.html#relation_expr)
3. [`qualified_name`](https://www.cockroachlabs.com/docs/sql-grammar.html#qualified_name)
4. The `name` element uses `databaseName` and `.tableName` continues processing into [`indirection`](https://www.cockroachlabs.com/docs/sql-grammar.html#indirection)
5. [`indirection_elem`](https://www.cockroachlabs.com/docs/sql-grammar.html#indirection_elem)
6.  [`name_indirection`](https://www.cockroachlabs.com/docs/sql-grammar.html#name_indirection) where `.` catches and `tableName` gets processed as `col_label` (which is strange)

### Proposal 
I recommend changing the name of `col_label` to something less descriptive like:
- `unrestricted_name` (because there are no restrictions on the name you can enter)
- `any_token` (because `col_label` accepts any token, including reserved keywords)

**Comment by RaduBerinde** [comment]
Makes sense to me. I like `unrestricted_name`. CC @mjibson, @knz

**Comment by knz** [comment]
Both proposals are fine to me too!

**Comment by mjibson** [comment]
I like `unrestricted_name` too. I'll fix this.
