### ISSUE TITLE
serverccl: package times out during shutdown causing flakes

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#85944]
**Describe the problem**

The serverccl package has been timing out.
- [here](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/6029962?buildTab=overview&showRootCauses=false&expandBuildProblemsSection=true&expandBuildTestsSection=true&expandBuildChangesSection=true&expandBuildDeploymentsSection=true#%2Ftmp%2F_tmp%2Fc101b7a464a1afc1f5af0cd85792187e%2FlogTestNoInflightTracesVirtualTableOnTenant2070669194;%2Ftmp%2F_tmp%2Fc101b7a464a1afc1f5af0cd85792187e%2FStartServer2953751379;%2Fbazel-testlogs%2Fpkg%2Fccl%2Fserverccl%2Fserverccl_test;%2Fbazel-testlogs%2Fpkg%2Fccl%2Fserverccl%2Fstatusccl;%2Fbazel-testlogs%2Fpkg%2Fccl%2Fserverccl%2Fdiagnosticsccl) ([logs](https://teamcityartifacts.crdb.io/presignedTokenAuth/cbf22e43-ce1e-4d2d-bc2e-c1d977b8872b/repository/download/Cockroach_UnitTests_BazelUnitTests/6029962:id/bazel-testlogs/pkg/ccl/serverccl/serverccl_test/test.log))
- [here](https://teamcityartifacts.crdb.io/presignedTokenAuth/eefa002d-e9f4-494c-81e1-a8968242aae7/repository/download/Cockroach_UnitTests_BazelUnitTests/6033094:id/bazel-testlogs/pkg/ccl/serverccl/serverccl_test/test.log)
- [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=6040534&problemId=4141)
- [here](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/6046487?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true)

One theory:
> Seems like the server fails to shut down because we’re waiting for quiescence but the contexts are not getting canceled correctly or something and we’re in an infinite retry inside `kv/kvclient/rangecache.(*RangeCache).tryLookup`.

Using a bisect I landed on 262a70d506e0b1f14ac1ba4ab831885c26bcd901 as the first bad commit, but I don't see why.

**To Reproduce**

The TestNoInflightTracesVirtualTableOnTenant test reproes it.

```
./dev test pkg/ccl/serverccl --stress --filter=TestNoInflightTracesVirtualTableOnTenant --timeout=2m --test-args='-test.timeout 20s'
```

Jira issue: CRDB-18494

**Comment by ajwerner** [comment]
The below stack trace is telling. 

```
* goroutine 53508 [select]:
* github.com/cockroachdb/cockroach/pkg/util/retry.(*Retry).Next(0xc001a4fe10)
* 	github.com/cockroachdb/cockroach/pkg/util/retry/retry.go:127 +0x13e
* github.com/cockroachdb/cockroach/pkg/sql/catalog/schematelemetry/schematelemetrycontroller.updateSchedule({0x5eb3ed8, 0xc010228d20}, 0xc6567c?, {0x5efb720, 0xc00d7db6e0}, 0xc010634000)
* 	github.com/cockroachdb/cockroach/pkg/sql/catalog/schematelemetry/schematelemetrycontroller/pkg/sql/catalog/schematelemetry/schematelemetrycontroller/controller.go:149 +0x266
```

**Comment by rafiss** [comment]
https://github.com/cockroachdb/cockroach/pull/85945 seems to have fixed it
