### ISSUE TITLE
kvserver: use pprof label for Replica.Send (replace sendWithRangeID)

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#85948]
**Is your feature request related to a problem? Please describe.**

We used to pass a faux parameter to `Replica.sendWithoutRangeID` but a) this [broke] in a recent Go update. We should just do this properly and use a profiler label, which will then show up in the `?debug=1` goroutines profile.

**Describe the solution you'd like**

It's a tricky because the code path is allocation sensitive (it's a hot path) and the pprof API forces us to use a context. We don't want to take the incoming context and wrap it due to the allocations, but if there is a label in there already we probably want to respect it and need to allocate. What we can do is to allocate a "background" context along with the replica for use in the fast path, i.e. we'd allocate only once per Replica, and to the expensive wrapping only when there are labels already.

To do this, we'd add a new field `pprofLabelCtx` to `Replica` and populate it in [newUnloadedReplica]:

```go
  pprofLabelCtx: pprof.WithLabels(context.Background(), pprof.Labels("rangeID", desc.RangeID.String()))
```

As well as some alloc avoidance infra:

```go
type emptyChecker bool

func (c *emptyChecker) check(k, v string) bool {
	*c = true
	return false // seen enough
}

var emptyCheckerPool = sync.Pool{New: func() interface{} { return new(emptyChecker) }}
```

and then at the top of `Replica.Send` (after inlining `sendWithoutRangeID`):

```go
	{
		var pprofLabelCtx context.Context
		const rangeIDLabel = "range_id"
		c := emptyCheckerPool.Get().(*emptyChecker)
		pprof.ForLabels(ctx, c.check)
		hasLabel := *c
		*c = false
		emptyCheckerPool.Put(c)
		if !hasLabel {
			// Fast path, saving allocations.
			pprof.SetGoroutineLabels(pprofLabelCtx)
		} else {
			// There are some incoming labels so we want to add our label to
			// the incoming context, which is more allocation intensive.
			pprof.SetGoroutineLabels(pprof.WithLabels(ctx, pprof.Labels(rangeIDLabel, r.RangeID.String())))
		}
		defer pprof.SetGoroutineLabels(ctx)
	}
```

[broke]: https://github.com/cockroachdb/cockroach/blob/b1de53351aa55aeaa81ea76e9af1d21fd113f715/pkg/kv/kvserver/replica_send.go#L116-L123
[newUnloadedReplica]: https://github.com/cockroachdb/cockroach/blob/0fea8455d9016ac4834275fb873788b5a3232a2a/pkg/kv/kvserver/replica_init.go#L66-L74

**Describe alternatives you've considered**

Nothing? Or see if `sendWithoutRangeID` can be resurrected properly.

**Additional context**

When a request hangs on a replica, it's important to be able to see on which range. In theory, tracing infra can help here too, but I think it's still spotty.

Jira issue: CRDB-18497

**Comment by pavelkalinnikov** [comment]
Should we pre-condition adding the pprof labels with the cluster setting, like here? https://github.com/cockroachdb/cockroach/blob/e09ce91f20de5c15b17dec36bb183ebc953f06e5/pkg/sql/conn_executor_exec.go#L124-L143)?

If we do so, can we avoid adding the complex code ?

The fast path described above is sensitive to having other pprof labels up the stack. As we adopt this labelling technique more widely, it's going to be more likely that this is no longer a fast path. Conditioning it by a global setting seems more straightforward and predictable.

**Comment by pavelkalinnikov** [comment]
Also, maybe it could be a per-request/tenant/etc setting.

Or maybe another way is optimizing the pprof labels code itself :) It has a [TODO](https://cs.opensource.google/go/go/+/refs/tags/go1.19:src/runtime/pprof/label.go;l=62) in it to be more efficient.

**Comment by tbg** [comment]
We discussed on Slack. Pavel brought up the good idea of not doing any perf improvements and wrapping the ctx only if currently profiling. That's also the approach take for the other labels and since this label is a lot cheaper than the ones on the SQL side, it should be workable. We will do that instead.
