### ISSUE TITLE
create index recommendation []string on instrumentation

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#85955]
Currently the value on `instrumentation.indexRecommendations` returns the format
```
{
"index recommendations: 2",
"   1. type: index replacement",
"   SQL commands: CREATE UNIQUE INDEX ON t1 (i) STORING (k); DROP INDEX t1@existing_t1_i;",
"   2. type: index creation",
"   SQL command: CREATE INDEX ON t2 (i) STORING (k);",
}
```

When being stored on `statement_statistics` this needs to be parsed, increasing the chances of errors if this format changes.
We need a list of just the recommendations, for example by having `IndexRecommendationSet.Output` returning a []string consisting of just the SQL statements, like `[]string{"CREATE INDEX ON t (a)"}`, and store this on instrumentation.

Jira issue: CRDB-18501

**Comment by rytaft** [comment]
Marcus worked on this in Thursday coding collaboration session
