### ISSUE TITLE
ui: better testing for connected components

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#8595]
Issue #7590 was triggered by a synchronous change to the the redux state which caused an updating component to update again in the middle of a callback.

We need the ability to test connected components so that we can test the implications of updating the state, vs just triggering a spy.

**Comment by vivekmenezes** [comment]
Close this issue?

**Comment by petermattis** [comment]
@mrtracy Is there anything actionable to do here?

**Comment by mrtracy** [comment]
No, this is not a high-value issue to fix, and I would say it's not something that needs to be tracked.
