### ISSUE TITLE
kvclient: require explicit acknowledgement from client on restart

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#85980]
**Is your feature request related to a problem? Please describe.**

Today, when a transaction hits some restart errors, it increments its epoch and remains open. When that happens a `TransactionRetryWithProtoRefreshError` makes its way to the client. In various situations we've seen sql code failing to properly propagate the error and update its state machine accordingly (https://github.com/cockroachdb/cockroach/issues/85677, https://github.com/cockroachdb/cockroach/issues/84448). In those cases, the transaction in question will silently lose the writes preceding the restart. We've seen other cases where the transaction is aborted internally and needs to be restarted, but methods continue to work. 

**Describe the solution you'd like**

A transaction which has been restarted internally should require an explicit acknowledgement from the client before it becomes usable again. An aborted transaction should return more errors from various methods to prevent misuse.

Jira issue: CRDB-18513

**Comment by rafiss** [comment]
@nvanbenschoten points out that this is similar (or identical to) https://github.com/cockroachdb/cockroach/issues/22615, which was resolved in https://github.com/cockroachdb/cockroach/pull/74563

**Comment by ajwerner** [comment]
I've been reviewing the information from the one case where I saw the transparent loss of writes and it appears to have been a situation involving `LeafTxn` objects and distsql. I'll file a separate issue when I figure it out.

**Comment by rafiss** [comment]
I see [`a098962` (#74563)](https://github.com/cockroachdb/cockroach/pull/74563/commits/a0989629f252a8400e73aaa726d41bbc50de7c5f) relates to LeafTxns - just throwing that out there.
