### ISSUE TITLE
drop database with hundreds of tables takes hours

### ISSUE THREAD

**Issue by timgraham** [cockroachdb/cockroach#86042]
**Describe the problem**

The build for [django-cockroachdb](https://github.com/cockroachdb/django-cockroachdb) typically takes about an hour. A change in CockroachDB nightly between July 22 and August 3 increased the build time to around 24 hours. The tests run in the same amount of time, but the two `DROP DATABASE` queries at the conclusion of the test suite now take hours.

**Additional data / screenshots**

The roachtest build of django-cockroachdb which runs [some cluster queries](https://github.com/cockroachdb/cockroach/blob/25fe0db12911a60571c3788b9403a6f42b52e003/pkg/cmd/roachtest/tests/orm_helpers.go#L38-L50) isn't affected by this performance regression.

**Environment:**
 - CockroachDB version: v22.2.0-alpha.00000000-2394-g6c24f3564e @ 2022/08/10 06:04:30

Jira issue: CRDB-18542

**Comment by ajwerner** [comment]
One thing I notice is that all of the long runs, there were 3, were for PRs 
* https://github.com/cockroachdb/django-cockroachdb/pull/255: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_CockroachDjango_CockroachDjangoTest202/5968353?showRootCauses=false&expandBuildChangesSection=true
*  https://github.com/cockroachdb/django-cockroachdb/pull/256: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_CockroachDjango_CockroachDjangoTest202/5990189?showRootCauses=false&expandBuildChangesSection=true
* https://github.com/cockroachdb/django-cockroachdb/pull/261: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_CockroachDjango_CockroachDjangoTest202/6014867?showRootCauses=false&expandBuildChangesSection=true

Each of these chooses to hijack [teamcity-build/build-teamcity-20.2.sh](https://teamcity.cockroachdb.com/diffView.html?id=1032980&vcsFileName=teamcity-build%2Fbuild-teamcity-20.2.sh&personal=false) to run the tests against the latest nightly. That might be a legit thing to do. I'm less sure that it means that the dates you posted correspond to whatever caused the increased latency. 

I'm having a hard time interpreting the build log to understand where the time is going -- it seems just jump a bunch.

**Comment by timgraham** [comment]
Sorry it's a little confusing. August 3 was the first time I pushed to one of those pull requests and noticed this issue, and I think July 22 was my previous push where it ran normally.

Are the Cockroach nightly builds archived by day? If so, I'll try to use those to find the date where the regression happened.

**Comment by rafiss** [comment]
The nightly builds are accessible by master branch commit shas. For example: https://edge-binaries.cockroachdb.com/cockroach/cockroach.linux-gnu-amd64.504b437a89e93f995d3a802eff1d760747f56741

If we're able to get this down to a simpler script that reproes the problem, we can also more easily run a git bisect.

**Comment by timgraham** [comment]
My investigation isn't bearing much fruit.

Here are CockroachDB hashes, dates, and Django test suite runtimes:
```
"b83e83b7e54fabf6ebd3a42cff67f4b8c5b7b863"  # 7/31 [5h]
"1129fbc650fe3a037b03aea1e5f1d8078618cb1c"  # 7/28 [3h 52m]
"0f100f3a09246bc80ef2c3119e4ec1c24ef36801"  # 7/26 [2h 16m]
"8fd5b3500796fae41c07fffd4246648b349b6460"  # 7/22 [15h+]
"fafc3330130a016a881592d0337ec48d9ce43b61"  # 7/21 [20h+]
"8fd5b3500796fae41c07fffd4246648b349b6460"  # 7/20 [2h, 7m]
"b77d49e1aa199014c520a652624e801eb28893c5"  # 7/19 [20h+]
"6e9f5a9f544f52dbda28d94c86ec9e5e4cc64023"  # 7/19 [2.5h]
"3dcf715f37595a73e8504b5331493f75207c6524"  # 7/18 [4.5h]
"dc382b1ec54b4599cce1f5f50f243723a4286da6"  # 7/17 [12h+]
"e4cafeb8b1d586d091fb98e3e570650d7eeea294"  # 7/16 [12h+]
"0e816efe5443764591a944edcb385c7b2762523e"  # 7/15 [2.5h]
```
(based on some 404s for earlier dates I tried to retrieve from edge-binaries.cockroachdb.com, I think nightly builds are only retained ~30 days?)

With the runtimes varying a lot, I wonder if the issue could be intermittent / non-determinstic.

I'm not sure if this is of any use, but while the drop database is running, there are a lot of lines like this in the log:
```
I220816 01:23:03.798940 4868374 jobs/registry.go:1425  [n1] 2310644  SCHEMA CHANGE GC job 788089932892930049: toggling idleness to true
I220816 01:23:03.801107 4868342 jobs/registry.go:1425  [n1] 2310645  SCHEMA CHANGE GC job 788089932811993089: toggling idleness to true
I220816 01:23:03.804300 4867998 jobs/registry.go:1425  [n1] 2310646  SCHEMA CHANGE GC job 788089932922585089: toggling idleness to true
I220816 01:23:03.835072 4684011 jobs/registry.go:1425  [n1] 2310647  SCHEMA CHANGE GC job 788090007780720641: toggling idleness to false
I220816 01:23:03.848242 4316022 jobs/registry.go:1425  [n1] 2310648  SCHEMA CHANGE GC job 788090110904205313: toggling idleness to false
I220816 01:23:03.849328 8804631 jobs/registry.go:1425  [n1] 2310649  SCHEMA CHANGE GC job 788084547317825537: toggling idleness to false
I220816 01:23:03.850677 1759636 jobs/registry.go:1425  [n1] 2310650  SCHEMA CHANGE GC job 788084873139519489: toggling idleness to true
I220816 01:23:03.850762 1759674 jobs/registry.go:1425  [n1] 2310651  SCHEMA CHANGE GC job 788084873281896449: toggling idleness to true
I220816 01:23:03.854623 4316109 jobs/registry.go:1425  [n1] 2310652  SCHEMA CHANGE GC job 788090110730698753: toggling idleness to false
I220816 01:23:03.864956 4316052 jobs/registry.go:1425  [n1] 2310653  SCHEMA CHANGE GC job 788090110794334209: toggling idleness to false
I220816 01:23:03.920797 4868440 jobs/registry.go:1425  [n1] 2310654  SCHEMA CHANGE GC job 788089932850790401: toggling idleness to true
I220816 01:23:03.946633 4867994 jobs/registry.go:1425  [n1] 2310655  SCHEMA CHANGE GC job 788089933009813505: toggling idleness to true
I220816 01:23:03.949797 4316073 jobs/registry.go:1425  [n1] 2310656  SCHEMA CHANGE GC job 788090110833721345: toggling idleness to false
I220816 01:23:03.951183 6893150 jobs/registry.go:1425  [n1] 2310657  SCHEMA CHANGE GC job 788087765443641345: toggling idleness to true
I220816 01:23:03.963071 5113622 jobs/registry.go:1425  [n1] 2310658  SCHEMA CHANGE GC job 788089844064092161: toggling idleness to true
I220816 01:23:03.967370 1759640 jobs/registry.go:1425  [n1] 2310659  SCHEMA CHANGE GC job 788084873044787201: toggling idleness to true
```

**Comment by timgraham** [comment]
I believe the performance improved around a week or so ago. I've seen consistent 2-hour build times for CockroachDB nightly rather than ~24 hours. This is still slower than ~1 hr. 15 min. for CockroachDB 22.1.

**Comment by ajwerner** [comment]
Do you know offhand where in the django repo the drop commands are? I'd like to run the tests and disable the drop at the end so that I can take a backup, profile, and tune it.

**Comment by timgraham** [comment]
You can disable the drop database queries by adding `--keepdb` to invocations of `runtests.py` (https://github.com/cockroachdb/django-cockroachdb/blob/0d44aaed3b414e263ee9f9ffb7ed71f585fdb9a1/teamcity-build/runtests.py#L7 and line 11).

**Comment by ajwerner** [comment]
Alright, I've got a backup of the database. The culprit is the rules introduced in https://github.com/cockroachdb/cockroach/pull/82749. These rules end up being quadratic. Let me think about what I want to do about this. We need to do something for the release. 

`gceworker-ajwerner> I220901 06:38:21.077191 4620 sql/schemachanger/scplan/internal/rules/registry.go:45 ⋮ [-] 2796 applying dep rule descriptor drop right before removing dependent with type ref 0 took 2m21.582884108s                                      
gceworker-ajwerner> I220901 06:41:10.305274 4620 sql/schemachanger/scplan/internal/rules/registry.go:45 ⋮ [-] 3761 applying dep rule descriptor drop right before removing dependent with expr ref 0 took 2m49.228054221s`
