### ISSUE TITLE
backupccl: print trace before timing out ExportRequest

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#86047]
Every ExportRequest sent by backup is given 5 minutes to complete, after which its context is canceled and the backup fails. This is a rather blunt hammer, and there is potentially scope for improvement, but in the meantime we should add more observability that helps triage why the ExportRequest was stuck for so long. One easy way to surface more information would be to pull a trace a few seconds before we are going to timeout and log it for consumption. Backups collect traces as they execute and so the trace would give us insight into where the ExportRequest spent the majority of the 5 mins. This would potentially help us triage support issues such as intent buildup a lot quicker.

Jira issue: CRDB-18544

Epic CRDB-8964

**Comment by msbutler** [comment]
want to reiterate that this an important quick win. It would help us solve https://github.com/cockroachlabs/support/issues/2066

**Comment by adityamaru** [comment]
@arulajmani and I discussed that there is something more we can do here. We can get the `CollectedSpans` from the batch response, stringify the trace and print it along with the error. We should also consider a cluster setting that allows us to send `ExportRequests` with a verbose trace so that we get more server side information when debugging slow export requests.

**Comment by arulajmani** [comment]
> We should also consider a cluster setting that allows us to send ExportRequests with a verbose trace so that we get more server side information when debugging slow export requests.

We should also consider running all `ExportRequests` with verbose tracing on. We can't do this for foreground traffic, which is latency sensitive, but `ExportRequests` are not. Being able to dump a verbose trace from failed `ExportRequests` will go a long way in being able to root cause opaque timeout errors that we see in escalations.
