### ISSUE TITLE
sql: add eventlog for UDF relevant statements

### ISSUE THREAD

**Issue by chengxiong-ruan** [cockroachdb/cockroach#86058]
**Is your feature request related to a problem? Please describe.**
A child of https://github.com/cockroachdb/cockroach/issues/58356

**Describe the solution you'd like**
Add event logging for UDF relevant statements:
1. create or replace function
2. drop function
3. alter function statements
4. grant/revoke (already added)

Jira issue: CRDB-18547

**Comment by ajwerner** [comment]
Closed by https://github.com/cockroachdb/cockroach/pull/88435
