### ISSUE TITLE
udf: can create duplicate signature udf

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#86067]
I noticed that you can create duplicate functions with the same signature, which appears to get a bit stuck. See the following example. It's possible that this is expected at the current state of development, in which case feel free to close this!

```
demo@127.0.0.1:26257/defaultdb> create function f() returns int language sql as 'select 1';
CREATE FUNCTION
demo@127.0.0.1:26257/defaultdb> create function f() returns int language sql as 'select 1';
CREATE FUNCTION
demo@127.0.0.1:26257/defaultdb> select f();
ERROR: ambiguous call: f(), candidates are:
f() -> int
f() -> int
SQLSTATE: 42725
demo@127.0.0.1:26257/defaultdb> drop function f;
ERROR: function name "f" is not unique
```

Jira issue: CRDB-18549

**Comment by chengxiong-ruan** [comment]
heh thanks for the issue. my pending pr is gonna prevent that https://github.com/cockroachdb/cockroach/pull/85900

**Comment by chengxiong-ruan** [comment]
fixed with https://github.com/cockroachdb/cockroach/pull/85900
