### ISSUE TITLE
sql: crdb_internal tables contain entries after `DROP`

### ISSUE THREAD

**Issue by mendeljacks** [cockroachdb/cockroach#86073]
**Describe the problem**
error: exceeded limit for number of table spans
This is shown when creating a new table in the database.

Please describe the issue you observed, and any steps we can take to reproduce it:
**To Reproduce**
Make tables and remove tables around 1000 times, then you will no longer be able to make more tables.

**Expected behavior**
When dropping a table I expect the record to be deleted from crdb_internals.tables so that adding and removing tables
does not leave any stray records.
Or at least there should be a way to manually clear these entries.

Jira issue: CRDB-18553

**Comment by HonoreDB** [comment]
Hi, I've added a label to get this triaged--in the meantime, have you looked into [lowering your gc.ttlseconds zone configuration?](https://www.cockroachlabs.com/docs/stable/configure-zone.html)

**Comment by ajwerner** [comment]
Is this in serverless?

**Comment by ajwerner** [comment]
I'd like to keep the conversation open and help you to have a positive experience, but I don't think this issue represents a real bug. When we drop tables, they remain available for some time to allow for time travel queries. Separately, in serverless, there is a limit on the number of tables you can have. If you could add more information about your use case that requires creating and dropping lots of tables in a short amount of time, that'd be helpful. For now, I'm closing this issue.

**Comment by mendeljacks** [comment]
I have an automated integration test which uses db-migrate to remove a set of tables and recreate them during every execution. I am not using serverless so it's not that limitation. I can see it creating the tables and it works for a while. However it appears that when tables are deleted and recreated the records in crdb_internals are persisted. So it will not allow for further changes to table structure. If the information is necessary for a time travel query, at least would there be a possibility to reset the database completely? The current solution I'm working with is to rollback the database to an old backup which seems to also rollback the cache..

**Comment by ajwerner** [comment]
Can you provide a clearer

**Comment by mendeljacks** [comment]
Copy paste this around 2 or 3 thousand times and then run it against a cockroachdb database. 
Expect that it should run to completion (it just creates a table then deletes it)
Actual it will eventually start giving span errors that come from the go code saying max span limit exceeded with a stack trace
```
CREATE TABLE public."my_table" ( id integer primary key generated by default as identity, email varchar(10485760) NOT null, CONSTRAINT users_email_uq UNIQUE (email));
drop table public.my_table;
```

**Comment by mendeljacks** [comment]
![image](https://user-images.githubusercontent.com/6755353/184927690-f0511f48-8b42-4861-ae51-f66c17234482.png)

**Comment by ajwerner** [comment]
How are you deploying the database? What version are you running?
