### ISSUE TITLE
storage: `MVCCGet` showing significant `MVCCIterator.Stats()` CPU time

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#86083]
`MVCCIterator.Stats()` has been seen to use ~4% of CPU during `MVCCGet` benchmarks:

<img width="1646" alt="Screenshot 2022-08-13 at 17 15 06" src="https://user-images.githubusercontent.com/644420/184500272-7d34082c-64d3-4cad-9233-c19fd1cede3e.png">

This is used to attach iterator stats to a running trace, but the stats collection is called unconditionally (regardless of whether an actual trace is in progress):

https://github.com/cockroachdb/cockroach/blob/9fb8d361ecb349dda4bfee10a17a6e19277762f0/pkg/storage/mvcc.go#L999-L1000

Jira issue: CRDB-18562

**Comment by erikgrinaker** [comment]
@jbowens I'm removing the unconditional stats collection in #86804, but it's a bit suspicious that the stats collection here is so expensive in the first place.

**Comment by jbowens** [comment]
Good call removing it.

cc @sumeerbhola — rather than descending the internal iterator stack summing stats across iterators, maybe we should thread a single stats pointer that all the internal iterators may incrementally add to, but only if stats are explicitly enabled on the iterator?

**Comment by sumeerbhola** [comment]
> cc @sumeerbhola — rather than descending the internal iterator stack summing stats across iterators, maybe we should thread a single stats pointer that all the internal iterators may incrementally add to

that sounds very reasonable
