### ISSUE TITLE
sql: Add further sanity checks to assert that virtual descriptors never escape

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#8611]
Right now `VirtualSchemas` rely on the fact that their restrictive permissions prevent them from escaping into "real" SQL code, and they are handled in special-cases for all operations that their permissions allow. This guarantee is verified in [logic tests](https://github.com/cockroachdb/cockroach/blob/18200f0d2355779b31da3bdd6576e02a9e042138/sql/testdata/information_schema), but is a little fragile and could easily be broken by future development efforts.

To prevent day-long debug sessions in the future, a few directed changes could be made:
- add assertions in descriptor handling that virtual descriptors are not being used
- instrument descriptor methods with _not-virtual_ assertions where applicable (like `GetPrimaryKey`)
- in general try to catch virtual descriptor use early so that the _not-virtual descriptor_ precondition can be easily identified as broken

Depending on how we eventually implement `TEMP` tables, these added sanity checks could be useful for them as well.

**Comment by dt** [comment]
#9361 might be related

**Comment by jordanlewis** [comment]
I don't think this issue is too valuable to keep open anymore - closing. Feel free to re-open if either of you disagree!
