### ISSUE TITLE
sql: internal executor usage bumps txn sequence number

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#86162]
**Describe the problem**

Some of our builtins and virtual tables use the internal executor. Probably some of our future UDFs will too. Usage of the internal executor ends up stepping the transaction such that all prior writes become visible. That step should not happen when the internal executor is used during statement execution. Or, rather, if it is to happen, it needs to be stepped back when the outer statement resumes. Generally, we're missing the language to discuss sequence number management when executing different sql statements as part of a single sql statement.

**To Reproduce**

Consider the below one-line change to [`sql.TestHalloweenProblemAvoidance`](https://github.com/cockroachdb/cockroach/blob/f3fdf1e4d8a7bf0143a65e12a8c75a202ab60fce/pkg/sql/conn_executor_test.go#L394-L467):

```go
diff --git a/pkg/sql/conn_executor_test.go b/pkg/sql/conn_executor_test.go
index ae937a4aa2..c6b3449529 100644
--- a/pkg/sql/conn_executor_test.go
+++ b/pkg/sql/conn_executor_test.go
@@ -449,6 +449,7 @@ SELECT IF(x::INT::FLOAT = x,
              'NOOPE', 'insert saw its own writes: ' || x::STRING || ' (it is halloween today)')::FLOAT)
        + 0.1
   FROM t.test
+ WHERE col_description('t.test'::regclass, ((x+.1)/(x+1) + 1)::int) IS NULL
 `); err != nil {
                t.Fatal(err)
  }
```

This test will now fail:
```
    conn_executor_test.go:454: pq: insert saw its own writes: 1.1 (it is halloween today)
```

The reason it fails is that `col_description`'s implementation invokes the internal executor, so, each time we evaluate the projections for a row, we step the sequence number.
**Expected behavior**
The test should pass.

**Additional context**

One approach might be to prevent any of our UDFs from invoking the internal executor. Perhaps that could become viable if we had some mechanism for virtual UDFs. Things are going to get complex when we allow recursion or mutations in UDFs. We almost certainly need a more complex stack structure and explicit sub-statement execution as a part of the `connExecutor` itself as opposed to today's internal executor which just constructs a new `connExecutor` with a simplified state machine and a touch of injected state (such as the `*kv.Txn` which is being erroneously mutated). 

Jira issue: CRDB-18608

Epic CRDB-26546

**Comment by ajwerner** [comment]
This issue was discovered in the context of [#86132](https://github.com/cockroachdb/cockroach/issues/86132).

**Comment by rytaft** [comment]
Is this needed for 22.2?

**Comment by ajwerner** [comment]
I don't think so. This has been around since at least 20.1. It's been newly discovered.

**Comment by nvanbenschoten** [comment]
Re-opening until the discussion in https://github.com/cockroachdb/cockroach/pull/108121#issuecomment-1673597716 is resolved.

**Comment by rafiss** [comment]
Copying the comment here:
> This is still allowing the internal executor to Step the Transaction, it's just reverting that Step after the internal executor query, right? Is this sufficient for Read Committed, where Step is also advancing the external read timestamp? Do we want to be stepping the transaction at all in these cases?

Hm i see. So perhaps in the case of a READ COMMITTED internal executor txn we should not step at all.

While trying to understand this better, I found another place we might need to consider; executing routines: https://github.com/cockroachdb/cockroach/blob/dc2c52da339a49405815860cbed511d364b7e146/pkg/sql/routine.go#L210

It already had similar defer logic: https://github.com/cockroachdb/cockroach/blob/dc2c52da339a49405815860cbed511d364b7e146/pkg/sql/routine.go#L178-L188
