### ISSUE TITLE
sql: support owners for synthetic privileges

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#86181]
Right now synthetic privileges do not have owners.

We should support a way to specify owners, in the meanwhile defaulting to `admin` is okay

This is only specific to `EXTERNAL CONNECTIONS` right now, the question is do we want an `owner` column in the `system.external_connections` table or to create a `system.object_owners` table akin to `system.privileges`
Jira issue: CRDB-18618
Epic CRDB-11725

**Comment by rafiss** [comment]
Is "owner" in this case the same as "grantor"?

**Comment by RichardJCai** [comment]
> Is "owner" in this case the same as "grantor"?

No this actually refers to the object owner, but perhaps that should be determined by the object instead? Ie do we want an `owners` column in system.externalconnections`

**Comment by RichardJCai** [comment]
Gonna close this as this is specific to `external connections` right now and I believe it's better to add a column for owner in the `EC` table

cc @adityamaru
