### ISSUE TITLE
gc: benchmark effects of gc using clear range on schema changes (drops)

### ISSUE THREAD

**Issue by aliher1911** [cockroachdb/cockroach#86217]
GC has a new fast path cleanup that is using pebble ClearRange to remove all range data.
This feature avoids using point key tombstones for every object in deleted ranges if possible.

We need to measure the effect of fast path on foreground traffic.

The experiment to run is:

on 3 node cluster n1-standard-16 (similar to one used in nightly perf) init two identical tpcc 2000 workloads, then start one of workloads and after some time, lower gcttl to 5 min and drop database. After ttl expires, observe that new metric shows that clear range is used by GC (using new metric), observe system load and foreground traffic performance while replicas are being removed.

Run the same experiment with v22.1.5 and observe current behaviour.

Jira issue: CRDB-18638

Epic CRDB-2624

**Comment by aliher1911** [comment]
There's a non-negligible effect of range tombstone usage for schema GC.

Previously (using master just before the change to use range tombstone and clear range GC):
<img width="971" alt="Screenshot 2022-08-17 at 10 57 31" src="https://user-images.githubusercontent.com/5124786/185097464-557b1896-76cb-4786-a515-0670048eab76.png">
<img width="967" alt="Screenshot 2022-08-17 at 10 59 46" src="https://user-images.githubusercontent.com/5124786/185097491-d1dcfb5c-8de3-4efa-9712-5a7367237506.png">
<img width="968" alt="Screenshot 2022-08-17 at 11 46 54" src="https://user-images.githubusercontent.com/5124786/185100400-04bf2a7e-c88e-4820-aa80-b567946ea2d1.png">
<img width="969" alt="Screenshot 2022-08-17 at 10 58 04" src="https://user-images.githubusercontent.com/5124786/185097476-29947387-6792-490d-937a-b44aa92a9ff5.png">
<img width="969" alt="Screenshot 2022-08-17 at 11 22 40" src="https://user-images.githubusercontent.com/5124786/185097519-953ae847-6982-4a7a-999c-9237172af5d9.png">
<img width="971" alt="Screenshot 2022-08-17 at 11 35 28" src="https://user-images.githubusercontent.com/5124786/185098379-880eb2e3-5b43-4420-a7a3-b6d891f73fdc.png">


With the change we can see that clear range is now spread along an eighteen minute interval 9:38-9:55:
<img width="969" alt="Screenshot 2022-08-17 at 11 32 59" src="https://user-images.githubusercontent.com/5124786/185099971-b37775e5-0428-478e-a0af-a23f85cf6951.png">
<img width="968" alt="Screenshot 2022-08-17 at 11 34 12" src="https://user-images.githubusercontent.com/5124786/185100000-6ae08ccd-6219-4037-88cb-82f98cbe1095.png">
<img width="966" alt="Screenshot 2022-08-17 at 11 46 21" src="https://user-images.githubusercontent.com/5124786/185100450-6220a3c1-d918-48e5-9007-50a3fca0b860.png">
<img width="967" alt="Screenshot 2022-08-17 at 11 33 23" src="https://user-images.githubusercontent.com/5124786/185099986-002a3872-19f2-4031-b7fa-e9e80447f3c7.png">
<img width="968" alt="Screenshot 2022-08-17 at 11 34 35" src="https://user-images.githubusercontent.com/5124786/185100010-8776b79c-bd4b-4bd7-b32d-af735b32cdbb.png">
<img width="967" alt="Screenshot 2022-08-17 at 11 34 56" src="https://user-images.githubusercontent.com/5124786/185100030-5ef09243-9dd8-452a-b9a6-179e6114aaa2.png">

**Comment by aliher1911** [comment]
I also run same test against 22.1.5 with results similar to "before" test, but it uses few % cpu less overall and it usually balances the load better between nodes. On master some test runs can end up having a hot node from the beginning and it would go into overload once L0 health degrades.

**Comment by aliher1911** [comment]
@ajwerner @erikgrinaker

**Comment by erikgrinaker** [comment]
Thanks for running these experiments @aliher1911. In some sense this is expected, because we're now dropping per-range ClearRanges spread out over the GC queue interval (10 minutes), instead of dropping them all immediately. This would put more pressure on Pebble compactions, I suppose.

@jbowens How worried are you about the above? It seems like we're causing more compaction work (naturally), but can we handle it?

**Comment by jbowens** [comment]
I'm mildly concerned about the impact on L0 health.  Is it possible to exempt the whole range fast-path from pacing?

Previously we have had trouble with large clear ranges being disruptive. There were two big improvements that made large clear ranges cheap:
1. Delete-only compactions: If a sstable wholly falls within the bounds of a cleared keyspace, we can drop it without reading it.
2. Pacing file deletions: Unthrottled write activity of removing files from the filesystem can saturate the write bandwidth.

It looks like we're seeing that delete-only compactions are less effective, because the storage engine only receives small fragments of clear ranges at a time. Tables that bridge range boundaries can't be dropped outright and will be compacted the ordinary way, which is more expensive in terms of read I/O, w-amp and CPU.

**Comment by aliher1911** [comment]
Currently we don't have a way to surface if GC hit a fast path up the stack to the queue and it could be potentially interleaved with any other replicas GC queue scans through.
We added an option to change the pace recently to slow that down, maybe we can also add a feature to reduce wait in some events? @erikgrinaker what do you think? I guess we can try to rerun the test with changed pace first to see how low it needs to get to show any difference.

**Comment by erikgrinaker** [comment]
>I guess we can try to rerun the test with changed pace first to see how low it needs to get to show any difference.

Yeah, good idea, let's try it out with essentially no pacing.

**Comment by aliher1911** [comment]
I tried that and it is not that straightforward. We have a global replica scanner that paces scans of all replicas for all queues and then queue itself has this new limiter, but there's no point in lowering it below scanner pace because it is a limiting factor as I learned the hard way.
I'll try to change scanner rate as well to see how bad it is.

**Comment by aliher1911** [comment]
So with min gc interval removed and replicas paced at all ranges within 1 minute using COCKROACH_SCAN_INTERVAL=1m we see an improvement. Extra load only lasts for 2 minutes during which we collect ranges that belong to dropped tables.

<img width="986" alt="Screenshot 2022-08-18 at 15 13 10" src="https://user-images.githubusercontent.com/5124786/185417947-fd901b88-a66c-4ec3-a7e6-34815f4f6635.png">
<img width="986" alt="Screenshot 2022-08-18 at 15 13 42" src="https://user-images.githubusercontent.com/5124786/185417972-ea7f0018-9577-4ac7-bba7-06f2ada399da.png">
<img width="984" alt="Screenshot 2022-08-18 at 15 13 56" src="https://user-images.githubusercontent.com/5124786/185417987-acc9f9cd-82fc-449c-9e76-a847ada60dce.png">
<img width="986" alt="Screenshot 2022-08-18 at 15 14 19" src="https://user-images.githubusercontent.com/5124786/185418064-c4a8fb76-678e-46a3-bf9a-5771b168a328.png">
<img width="987" alt="Screenshot 2022-08-18 at 15 14 38" src="https://user-images.githubusercontent.com/5124786/185418091-5c501052-377b-4b9e-9643-1389203c17b4.png">
<img width="987" alt="Screenshot 2022-08-18 at 15 14 47" src="https://user-images.githubusercontent.com/5124786/185418111-4e641a82-e511-4a68-a082-0cd6ccce6182.png">

From practical perspective we can't easily accelerate real system as all the queues on the node are driven by a single scanner and individual queues are pacing how fast they consume replicas from there. We can enqueue manually though, but for this schema GC needs to do something in the line with past behaviour. After changing schema, wait for gc ttl and then explicitly enqueue those replicas in mvcc_gc queue. And the queue should potentially ignore processing delay if last processed replica was a renge cleanup.

**Comment by erikgrinaker** [comment]
Nice, looks like that helped quite a bit. The foreground latency is still not great, but it's no worse than what we already had.

I was thinking we could do something like have the GC queue eagerly and optimistically enqueue the neighbouring range after we hit the fast path. Unfortunately, the replica scanner schedules replicas either in undefined order or by range ID, which means that we may start the table GC in the middle of the table. Enqueueing both the LHS and RHS is tricky (the next pass would do the same, to overlapping replicas), but maybe it would be sufficient to just optimistically enqueue the RHS range?

**Comment by aliher1911** [comment]
Plan is to use hints added in #86565 to tell GC queue to search for other ranges that we deleted completely and enqueue them bypassing scanner.
To start using hints, #86739 needs to merge to send hints in DeleteRange requests from schema GC and then relevant functionality needs to be added to mvcc gc queue.

**Comment by jbowens** [comment]
A thought: We could get some constant-factor improvement by bumping these [Pebble flush delay options](https://github.com/cockroachdb/cockroach/blob/5051c83dee80b94dc4b3b423042215aa5d39eefc/pkg/storage/pebble.go#L536-L543). When we write a Pebble range tombstone (storage package `ClearRange`), we force a flush of the memtable within 10s because we don't start dropping data until those range tombstones are flushed. Bumping those options would allow more range tombstones to accumulate before we flush, making it more likely that adjacent range tombstones are flushed together, making delete-only compactions more likely to trigger. I'll experiment next week to see if this has any impact.

**Comment by aliher1911** [comment]
As a part of this exercise we added clear range test with and without range tombstones: #88735
Test run with range tombstones used by delete range when dropping tables:
![drop-table-range-tombstones](https://user-images.githubusercontent.com/5124786/192776760-b37d87f7-8bbd-44ba-a23b-67e2b39f5ed9.jpg)

Test run with drop table explicitly performing clear range once tables pass GC ttl:
![drop-table-clear-range](https://user-images.githubusercontent.com/5124786/192776781-47b1d11b-83cb-4d01-a7ba-95723b172985.jpg)
