### ISSUE TITLE
changefeedccl: tests asserting that upgrades and secondary index changes don't change avro schemas

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#86226]
While the avro schemas we emit are versioned and change with the table schema, some users rely on them not changing in response to anything other than a change to the public columns of a table. We should try to catch it earlier via automation when this is not the case and either document or avoid it. This could look something like 

1. Iterate over all possible declarative schema changes on a table (using code that will pick it up if a new kind of schema change is added by the SQL team.
2. For each schema change, apply it to a table with an existing avro changefeed and assert that exactly one of the following is true:
     - The changefeed errors out at the schema change boundary (with one of an allowlist of errors).
     - The avro schema is completely unchanged (aside from incrementing the version).
     - The table's set of public columns has changed (including type changes).
     - Or this is one of a documented set of schema changes that affect changefeed output (e.g. SET REGIONAL BY ROW).

Plus another test using fixtures to assert that upgrades don't affect avro schemas.

Jira issue: CRDB-18643

Epic CRDB-9179

**Comment by miretskiy** [comment]
@HonoreDB If the customers are sensitive to schema changes on their external systems,
perhaps schema_change_policy=stop is the answer?

Do we have any plans on working on this? If not, let's close it.

/cc @amruss
