### ISSUE TITLE
sql: TestInsightsIntegrationForContention is flakey

### ISSUE THREAD

**Issue by andrewbaptist** [cockroachdb/cockroach#86224]
Here are some recent failures:

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/6113932

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/6114199

Jira issue: CRDB-18642

**Comment by yuzefovich** [comment]
@andrewbaptist when opening up issues, please add it to a project of the team that you think is the owner of the codebase - otherwise, the ticket might never be looked at.

**Comment by yuzefovich** [comment]
The test is being introduced in #85959, will ping the author.
