### ISSUE TITLE
ccl: TestTenantStreamingUnavailableStreamAddress failed

### ISSUE THREAD

**Issue by cucaroach** [cockroachdb/cockroach#86227]
Test flake?  https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/6114999?showRootCauses=true&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildDeploymentsSection=true&expandBuildTestsSection=true

```
=== RUN   TestTenantStreamingUnavailableStreamAddress
    test_log_scope.go:162: test logs captured to: /artifacts/tmp/_tmp/90c1b75d835f45b8488807abb5b1092d/logTestTenantStreamingUnavailableStreamAddress2815750504
    test_log_scope.go:80: use -show-logs to present logs inline
    stream_replication_e2e_test.go:805: condition failed to evaluate within 2m0s: expected job status succeeded, but got paused
    panic.go:482: -- test log scope end --
--- FAIL: TestTenantStreamingUnavailableStreamAddress (209.10s)
```

Jira issue: CRDB-18644

Epic CRDB-11732

**Comment by yuzefovich** [comment]
@cucaroach  when opening up issues, please add it to a project of the team that you think is the owner of the codebase - otherwise, the ticket might never be looked at.
