### ISSUE TITLE
storage: MVCC range keys sometimes omitted by `MVCCIncrementalIterator`

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#86260]
I'm seeing something that indicates a bug with range key defragmentation and block property filters.

In #86256, I'm adding a metamorphic test parameter for `TestMVCCHistories` which causes Pebble to use very small blocks, and to flush after every write operation. Try running this a few times:

```
dev test pkg/storage -f 'TestMVCCHistories' --ignore-cache -v --rewrite
```

Quite often (depending on the metamorphic parameters), this will generate changes in `export` and `range_key_iter_incremental` that either truncate range keys (so e.g. `[a-k)` is truncated to `[a-b)`), or fragments disappear completely (e.g. `[b-c)` disappears from a longer chain of connected fragments). This leads me to suspect a bug in Pebble defragmentation, since I don't see any mechanism in CRDB that would truncate range keys like this.

Both of these test cases use `MVCCIncrementalIterator`, using a TBI paired with a normal iterator. However, it must be the normal iterator that's surfacing these truncated range keys -- it's still a bit unclear what's happening.

See also https://github.com/cockroachdb/pebble/issues/1895.

Jira issue: CRDB-18652

Epic CRDB-2624

**Comment by erikgrinaker** [comment]
I see what's happening now: the TBI and normal iterator have a different view of the range key fragmentation. Consider this case:

* A range key covering `[a-f)@3`.
* The main iter sees `[a-b)@3`, `[b-d)@3`, and `[d-f)@3`, because of fragmentation by other range keys.
* The TBI limited to the time range [3-3] only sees the defragmented `[a-f)@3`.
* The TBI is positioned on key `a`.
* The iterator is positioned on key `b`, at the start of `[b-d@3)`.
* The TBI wants to catch up to the iterator, so it calls `NextKey()`. This will skip past the entire `[a-f)@3` range key. The iter sees the TBI ahead of itself and seeks to its position, skipping all the fragments in between.

https://github.com/cockroachdb/cockroach/blob/179f9359617254ede2540089433b6c4f00e67b85/pkg/storage/mvcc_incremental_iterator.go#L299-L310

**Comment by jbowens** [comment]
I wonder how much benefit we actually get from filtering range-key blocks on a TBI iterator. We originally debated whether we should even implement block-property filtering on range keys with the expectation that the performance win would likely be marginal.

I think it'd be entirely reasonable to omit `RangeKeyFilters` on the TBI, especially given where we are [in stability].

**Comment by erikgrinaker** [comment]
That's a very good point. The logic to deal with this is a bit fiddly, and involves a fair bit of additional seeks which may end up negating the benefit of the TBI altogether. I'll give it a shot.
