### ISSUE TITLE
insights: more sophisticated eviction policy

### ISSUE THREAD

**Issue by matthewtodd** [cockroachdb/cockroach#86271]
As of #79450, insights are kept in a simple LRU cache, with a user-configurable size. Depending on the data we see as we start to gather them, we may want to explore being more sophisticated, perhaps only keeping the latest or worst insights per statement fingerprint. This ticket captures that design and implementation.

Jira issue: CRDB-18659

Epic CRDB-20388

**Comment by maryliag** [comment]
No longer a priority
