### ISSUE TITLE
stability: repeatedly applying snapshot for the same range

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#8629]
Running `block_writer` against a local 4 node cluster, I see a snapshot being applied repeatedly for 1 range on one node:

```
~/Development/go/src/github.com/cockroachdb/cockroach pmattis/raft-logging-redux grep 'applied Raft snapshot for range 7 ' cockroach-data/3/logs/0.stderr | wc -l
      73
```

The only replica changes for this range are:

```
~/Development/go/src/github.com/cockroachdb/cockroach pmattis/raft-logging-redux grep 'range=7' cockroach-data/1/logs/0.stderr | egrep 'ADD|REMOVE'
I160817 19:53:52.667525 storage/replica.go:1500  store=1:1 range=7 [/Table/51-/Table/51/1/2319145621337716466/"4c3241bc-22e1-4c42-8996-f40f3f3ef665"/10028): proposing ADD_REPLICA {NodeID:4 StoreID:4 ReplicaID:4} for range 7: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:3 StoreID:2 ReplicaID:2} {NodeID:2 StoreID:3 ReplicaID:3} {NodeID:4 StoreID:4 ReplicaID:4}]
I160817 19:53:52.772124 storage/replica.go:1500  store=1:1 range=7 [/Table/51-/Table/51/1/2319145621337716466/"4c3241bc-22e1-4c42-8996-f40f3f3ef665"/10028): proposing REMOVE_REPLICA {NodeID:3 StoreID:2 ReplicaID:2} for range 7: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:4 StoreID:4 ReplicaID:4} {NodeID:2 StoreID:3 ReplicaID:3}]
I160817 19:54:49.981856 storage/replica.go:1500  store=1:1 range=7 [/Table/51-/Table/51/1/2319145621337716466/"4c3241bc-22e1-4c42-8996-f40f3f3ef665"/10028): proposing ADD_REPLICA {NodeID:3 StoreID:2 ReplicaID:5} for range 7: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:4 StoreID:4 ReplicaID:4} {NodeID:2 StoreID:3 ReplicaID:3} {NodeID:3 StoreID:2 ReplicaID:5}]
I160817 19:54:51.671439 storage/replica.go:1500  store=1:1 range=7 [/Table/51-/Table/51/1/2319145621337716466/"4c3241bc-22e1-4c42-8996-f40f3f3ef665"/10028): proposing REMOVE_REPLICA {NodeID:2 StoreID:3 ReplicaID:3} for range 7: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:4 StoreID:4 ReplicaID:4} {NodeID:3 StoreID:2 ReplicaID:5}]
```

**Comment by cuongdo** [comment]
I've noticed this. In my particular case, it boils down to us truncating
logs when the log size exceeds the size of the data in the range:

https://github.com/cockroachdb/cockroach/blob/develop/storage/raft_log_queue.go#L89

**Comment by petermattis** [comment]
Yeah, I added that code. Snapshot application is much faster than log replay. The next question is why isn't the replica keeping up?

**Comment by bdarnell** [comment]
How much time passes between log truncations?

If a non-preemptive snapshot takes longer than the tick interval to apply, we may re-send it (because without end-to-end acks of snapshots, we call raftGroup.ReportSnapshot immediately). The synchronous snapshot PR I just merged will help this by reducing the number of non-preemptive snapshots we process; streaming snapshots will fix the rest by giving us end-to-end acks.

**Comment by petermattis** [comment]
I think the repeated snapshots were due to overaggressive log truncation. The current log truncation heuristic allows the raft log to be truncated to the smallest behind index (an index behind the commit index) that is larger than the first index the leader has in its log. When the raft log grows to be larger than the target size (the replica size) we truncate to the commit index. 

Consider what happens when a node falls behind. At first, we don't perform any truncation because the behind node has a log index that is equal to the first index. But eventually the raft log grows larger than the target size and we truncate to the commit index. From that point forward, we'll continue to truncate to the commit index. When the behind node is caught up via a snapshot, it needs to catch up before the next log truncation or else we'll get into a cycle where the log is truncated while we're trying to catch the behind node up via snapshot.

The fix is relatively straightforward and seems to completely alleviate the repeated snapshots in my testing. The comments will be detailed.

**Comment by BramGruneir** [comment]
This was closed automatically when I synced master to develop.  Is is really closed?

**Comment by bdarnell** [comment]
The `Fixes #XXXX` lines in commit messages are processed by github when a commit makes it to the default branch, so now the issues are closed when the commit makes it to `develop` instead of `master`. In this case Peter's #8636 closed this issue.
