### ISSUE TITLE
`debug zip`: provide redacted form of `system.descriptor` when --redact flag used

### ISSUE THREAD

**Issue by abarganier** [cockroachdb/cockroach#86309]
**Is your feature request related to a problem? Please describe.**
https://github.com/cockroachdb/cockroach/pull/86180 introduced the --redact flag for the debug zip command. As a first iteration, it provides an immediate but coarse-grained level of compliance for debug zip bundles, where all sensitive data is omitted or redacted from the bundle (except for keys, which have been deemed necessary to support CockroachDB).

One area affected by this is the dumps of `crdb_internal.*` and `system.*` tables, where via an audit of all the dumped tables and their columns, we've implemented a mechanism where sensitive columns are simply omitted from the dumped tables when the --redact flag is provided.

However, this of course poses issues for our support team as some of these table dumps (and more specifically, certain columns) are crucial to their workflows.

One example of this is the `system.descriptor` table. The `descriptor` column in this table can contain sensitive information (for example, unredacted default values for columns contained within a `CREATE TABLE` statement). Therefore, in the first iteration of making debug zip compliant, this column has been omitted from `system.descriptor.txt` when the `--redact` flag is passed to `debug zip`.

We should provide a way to provide these descriptors in a redacted form, as opposed to omitting the descriptors entirely. This information has been identified by both KV and support staff alike as crucial in investigating support escalations, so omitting the data entirely is not a sustainable solution.

**Describe the solution you'd like**
Redaction of the descriptor is not immediately possible via a SQL query against `system.descriptor`. Is there an analogous gRPC/http endpoint that can be utilized until we find a more robust redaction solution at the SQL level? 

If so, we can utilize such an endpoint and its available redaction facilities to provide descriptors where only sensitive information is redacted. The `catalog.Descriptor` interface & its implementations provide a lot of data that's not sensitive, so we should provide as much as possible to avoid scenarios where people needing to analyze descriptors aren't left "blind".

Jira issue: CRDB-18688

Epic CRDB-12732

**Comment by thtruo** [comment]
Heads up @devadvocado, like I mentioned in Slack I believe this item should be re-routed to SQL Schema. I'm going to update the T- labels and add this to the SQL Schema project so that it shows up on your team's backlog.

**Comment by ajwerner** [comment]
cross-ref https://github.com/cockroachdb/cockroach/pull/87839

**Comment by abarganier** [comment]
Please note this comment on a similar issue for `system.jobs`: https://github.com/cockroachdb/cockroach/issues/88069#issuecomment-1276299931

We can likely find a common solution for both via proto field annotations. Creating a generalized redact builtin that makes use of these annotations may save effort and scale for additional data types beyond descriptors and job payloads.
