### ISSUE TITLE
changefeedccl: Add commit/emit latency histograms to CDC graphs

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#86314]
New(ish) stats, such as commit/emit latency are only available in the advanced debug/custom graph
section.
We should add those to changefeed graphs in the console.

This should be displayed in ms - our current nanosecond denomination confuses peoples...

Jira issue: CRDB-18692

Epic CRDB-9181

**Comment by amruss** [comment]
Additional suggestions are to rename "max changefeed latency" to max checkpoint latency

**Comment by HonoreDB** [comment]
Maybe even "max checkpoint age"

**Comment by HonoreDB** [comment]
I feel like having latency in the name of a metric can make people think it's more "live" than it actually is. If your changefeed is completely stuck you still see max changefeed latency rising.

**Comment by amruss** [comment]
Closing due to: https://github.com/cockroachdb/cockroach/pull/101790
