### ISSUE TITLE
sql: forecasting doesn't work on big tables because horizon is too small

### ISSUE THREAD

**Issue by cucaroach** [cockroachdb/cockroach#86395]
For the https://github.com/cockroachlabs/support/issues/1401 issue 7 days is too small and forecasting fails to get us to chose the right plan.  If I remove the horizon limit it works (which is awesome)!  @michae2 

Jira issue: CRDB-18737

**Comment by michae2** [comment]
Thank you @cucaroach this is great feedback!! I wasn't sure about that 7-day horizon.

Just out of curiosity, with the horizon removed, what is the difference between the forecast time and the latest collection time?

**Comment by cucaroach** [comment]
> Just out of curiosity, with the horizon removed, what is the difference between the forecast time and the latest collection time?

I think it was like 2-3 weeks.
