### ISSUE TITLE
tabledesc: add missing row-level TTL validation unit test cases

### ISSUE THREAD

**Issue by postamar** [cockroachdb/cockroach#86410]
I looked at the validation code today and noticed that while the row-level TTL configuration in a table descriptor does indeed have validation logic, this logic is never tested anywhere. This must have slipped through when the feature was squeezed into the last release.

The expiration expression, in particular, has no tests checking that the referenced columns actually exist, and I can't find any logic to that effect.

This is a bigger deal than it sounds. Not only has this testing repeatedly surfaced bugs and regressions; but having well-tested validation logic is a key element in lowering SQL Schema's support burden. 

Accordingly, I'm marking this as a GA-blocker. 

Jira issue: CRDB-18746

**Comment by ajwerner** [comment]
@rafiss would you say that your open PR fixes this issue, or no?

**Comment by rafiss** [comment]
yeah https://github.com/cockroachdb/cockroach/pull/86269 will close this

**Comment by postamar** [comment]
I don't share this belief that logic tests are enough, though obviously they are very welcome. We can't anticipate how corruption can occur and I'd sleep better at night if we had some unit test cases to make sure that corruptions will get detected, particularly when it comes to bad column references in the expiration expr.
