### ISSUE TITLE
stability: TestClusterBackupRestore is flaky if clusterSize is bumped to 3

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#8643]
See TODO at https://github.com/cockroachdb/cockroach/blob/develop/sql/backup_test.go#L158.

It's set to 1 node right now, but the intention was use to 3. If it's bumped to 3 and stress tested, it reliably fails.

The biggest issue is that occasionally the test takes more than 2 minutes and times out. If this is raised to 5m or so, it always seems to finish, but some of the test runs clearly stall for a while. I haven't looked at exactly what it's stalling on yet, so it might just be the same stuff we're already addressing more specifically in the code yellow.

A possible second issue is that some of the sql statements also timing out on 3 nodes. Wrapping them each in a util.SucceedsSoon fixes it, but they're doing a small enough amount of work that it feels like this shouldn't be necessary.

**Comment by paperstreet** [comment]
Assigning to myself for initial investigation, but cc @andreimatei in case you're interested (the test uses testcluster).

**Comment by danhhz** [comment]
This is super out of date. That test doesn't even exist anymore
