### ISSUE TITLE
ui: update transaction workload insights SQL API to group by fingerprint ID, use `insights.experimental.latency_threshold`

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/cockroach#86447]
We should consider grouping transaction workload insights by fingerprint ID, to avoid repetition across rows of contended transactions.

@maryliag suggested ranking each execution of each fingerprint by timestamp, and then showing the latest one. (We could also show the one with highest latency or something):

```
create table t(id int, ts timestamp, v string);

select * from t;
  id |         ts          | v
-----+---------------------+----
   1 | 2020-01-01 00:00:00 | a
   1 | 2021-02-02 00:00:00 | b
   1 | 2022-03-03 00:00:00 | c
   2 | 2021-01-01 00:00:00 | d
   2 | 2022-02-02 00:00:00 | e

select *, row_number() over(partition by id order by ts DESC) as rank from t;
  id |         ts          | v | rank
-----+---------------------+---+--------
   1 | 2022-03-03 00:00:00 | c |     1
   1 | 2021-02-02 00:00:00 | b |     2
   1 | 2020-01-01 00:00:00 | a |     3
   2 | 2022-02-02 00:00:00 | e |     1
   2 | 2021-01-01 00:00:00 | d |     2

select * from (select *, row_number() over(partition by id order by ts DESC) as rank from t) where rank=1;
  id |         ts          | v | rank
-----+---------------------+---+-------
   1 | 2022-03-03 00:00:00 | c |    1
   2 | 2022-02-02 00:00:00 | e |    1
```

@j82w also recently brought up a great point:

The statement workload insights SQL API queries the internal insights table, which records high wait time statements with latencies above the `sql.insights.latency_threshold` cluster setting value. The transaction workload insights SQL API queries the internal `transaction_contention_events` table, with a `WHERE contention_duration >` filter on a hard-coded threshold value. We should update this `WHERE` clause to use the threshold value set in the `sql.insights.latency_threshold` cluster setting, so the high wait time executions match.

Jira issue: CRDB-18763

**Comment by maryliag** [comment]
Matthew was changing the name of some of those settings. @matthewtodd can you confirm this is the latest name for this setting or has it changed?

**Comment by matthewtodd** [comment]
The latest (public) names are:
- `sql.insights.execution_insights_capacity`
- `sql.insights.latency_threshold` ⬅️ This is the one we're talking about here.
- `sql.insights.high_retry_count.threshold`

All the settings are defined in [pkg/sql/sqlstats/insights/insights.go](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sqlstats/insights/insights.go), where I'm trying to keep all the public-facing parts of the package.

**Comment by maryliag** [comment]
@kevin-v-ngo what do you think, for each fingerprint, show the latest or the one with most contention?

**Comment by kevin-v-ngo** [comment]
> @kevin-v-ngo what do you think, for each fingerprint, show the latest or the one with most contention?

I think latest would be good for now! In case the user actually did some mitigation already. 

Note in the future, once we have persistence (and consistent retention), we should reconsider adding all information to allow correlation with metrics and other views we have in the console.
