### ISSUE TITLE
changefeedccl: context cancelled in changefeed tests

### ISSUE THREAD

**Issue by jayshrivastava** [cockroachdb/cockroach#86616]
`TestChangefeedColumnDropsOnMultipleFamiliesWithTheSameName` [flaked](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/6190326?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildDeploymentsSection=true&expandBuildTestsSection=true) due to context cancellation

[another flake](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/6192759?showRootCauses=true&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildDeploymentsSection=true&expandBuildTestsSection=true) in `TestNoStopAfterNonTargetColumnDrop`

[another flake](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/6207643?showRootCauses=true&expandBuildChangesSection=true&expandBuildDeploymentsSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true) in `TestChangefeedPrimaryKeyChangeWorks`

[another flake](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/6219602?showRootCauses=true&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true) in `TestChangefeedReplanning`

Jira issue: CRDB-18841

Epic CRDB-11732

**Comment by HonoreDB** [comment]
These are failing on multiple sinks so I'd bet the fix is to use `requireErrorSoon` whenever asserting an error from a schema change, and probably also skipping under stress and/or race.

**Comment by jayshrivastava** [comment]
https://github.com/cockroachdb/cockroach/pull/86794
