### ISSUE TITLE
server: incorrect node address after taking node down

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/cockroach#8663]
Please follow the steps below to help us help you.

1. Please supply the header (i.e. the first few lines) of your most recent

	sloiselle@insecure-node1:~/cockroach-data/logs$ cockroach version
	Build Tag:   beta-20160728
	Build Time:  2016/07/28 17:02:34
	Platform:    linux amd64
	Go Version:  go1.6.3
	C Compiler:  gcc 4.9.2

2. Please describe the issue you observed:

- What did you do?

I have 3 nodes. I've brought them up and down a number of times, continually joining and rejoining the same cluster, checking the **Nodes** tab in the Admin UI. My nodes began intermittently crashing, so I decided to go through and restart the GCE instances hosting them.

- What did you expect to see?

I expected my nodes to maintain the names they were given.

- What did you see instead?

After my nodes inadvertently going down in GCE and restarting all of them, a node that I had named *insecure-node1* started displaying as *insecure-node3* (the name of another node in my cluster).

Worked with @maxlang; we ran `curl localhost:8080/_status/nodes` on the mis-named node and found the node address field had been changed at some point from *insecure-node1* to *insecure-node3*.

**Comment by bdarnell** [comment]
Do you now have two nodes named insecure-node3, or did 1 and 3 swap? 

Are you sure that the names were ever correct? There is no relationship between the hostnames you assign to the machines in GCE and the node IDs that cockroachdb uses internally (this is extremely annoying; we should try to make this less confusing).

**Comment by sploiselle** [comment]
Lost servers that had issue present. Cannot repro.
