### ISSUE TITLE
enable running non-perf roachtests with runtime assertions (crdb_test build tag)

### ISSUE THREAD

**Issue by srosenberg** [cockroachdb/cockroach#86678]
Recent PR [1] added the ability to run roachtests with runtime assertions enabled. TC will now produce `cockroach-short-ea`. This binary can be staged (instead of `cockroach`) with the default probability of .5 by invoking `maybeUseBuildWithEnabledAssertions`.

Let's try to enable this for all non-perf roachtests and conditionally opt out those if the assertions result in longer timeouts.

[1] https://github.com/cockroachdb/cockroach/pull/86625

Jira issue: CRDB-18869

**Comment by erikgrinaker** [comment]
Over in https://github.com/cockroachdb/cockroach/pull/112226#issuecomment-1760302593, it was suggested that this would also enable metamorphic parameters for roachtests. Roachtest metamorphism is needed for #103304 (a GA-blocker), so I'm marking this as GA-blocker and subsuming the other issue.
