### ISSUE TITLE
sql/schemachanger: drop jobs from 22.1 can fail trying to plan on RowLevelTTL

### ISSUE THREAD

**Issue by fqazi** [cockroachdb/cockroach#86672]
Any job generated with a RowLevelTTL element generated on 22.1 and resumed on 22.2 can fail. With the following error: `failed to satisfy [[Table:{DescID: 130}, ABSENT], DROPPED] -dep-SameStagePrecedence-> [[RowLevelTTL:{DescID: 130}, ABSENT], ABSENT] rule "descriptor drop right before dependent element removal"`

A simple repro is to pull down a 22.1 corpus: `gsutil cp gs://cockroach-corpus/corpus-86575/corpus . `, then run `./cockroach debug declarative-corpus-validate corpus`

**Comment by ajwerner** [comment]
This is really hard to hit, it requires dropping a table with row-level TTL and then crashing the gateway node and then having it resume on a node with the older version.
