### ISSUE TITLE
ui: Wrong font in table headers

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#8669]
The node table headers (at commit eb9572c) are being rendered in the wrong font. Looks like it's referencing the font `Lato` but that's not in `ui/fonts` (should it be `Lato-Regular` instead?)

https://www.dropbox.com/s/ahhaae7r8ovru5a/Screenshot%202016-08-18%2016.08.56.png?dl=0

**Comment by maxlang** [comment]
Ugh, I must not have caught this because `Lato` is a valid font on my machine. I should uninstall the fonts we use to catch things like this.

**Comment by mrtracy** [comment]
This is out of date, closing.
