### ISSUE TITLE
Evaluate options and standardize our usage of CLI utility

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#867]
The main app uses go-commander and newer testtool uses something else. Let's standardize.

**Comment by petermattis** [comment]
go-commander looks to be nearly unused: https://godoc.org/code.google.com/p/go-commander?importers

`testtool` uses https://github.com/codegangsta/cli. This package looks fairly popular: https://godoc.org/github.com/codegangsta/cli?importers. Biggest issue I have with this library is that it doesn't play nice with the standard go flags package.

The other option I'm looking at is cobra: https://godoc.org/github.com/spf13/cobra. Fairly popular, though not at the same level as codegangsta. Doesn't use the standard flag package either, but uses one that is a drop-in replacement but which supports posix-flag syntax. Cobra is used by kubernetes for its command line tools.
