### ISSUE TITLE
TestChangefeedReplanning flaked

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#86705]
see flake in [CI](https://teamcity.cockroachdb.com/viewLog.html?buildId=6207852&problemId=2683)

Jira issue: CRDB-18876

Epic CRDB-11732

**Comment by rafiss** [comment]
it's happening more frequently now https://github.com/cockroachdb/cockroach/issues/96517

**Comment by miretskiy** [comment]
Likely fixed by https://github.com/cockroachdb/cockroach/pull/96563
