### ISSUE TITLE
lint: fix and re-enabled gcassert

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#86714]
We [will] disable the `gcassert` linter in #86049 because `gcassert` does not support Go 1.19. We rely on this linter to catch critical performance regressions, so it is imperative that we re-enable it as soon as possible.

Jira issue: CRDB-18882

**Comment by knz** [comment]
I think this might get solved by upgrading the vendored golang.org/x/tools dependency. I see there are go 1.19-related fixes in there.
