### ISSUE TITLE
optimize Prisma test performance tracking

### ISSUE THREAD

**Issue by kernfeld-cockroach** [cockroachdb/cockroach#86743]
**Describe the problem**

Currently the Prisma test suite takes 45 minutes to complete

**To Reproduce**
* Check out https://github.com/prisma/prisma-engines
* Set `current_connector` file to contain `cockroach`
* I used to write the following to `.test_config`:
```json
{
    "connector": "cockroachdb",
    "runner": "direct"
}
```
* Set up a local cockroach
    * I was using https://gist.github.com/ajwerner/ce2e55540ce91d2e076470d2f478963c
* Run `cargo test -p query-engine-tests`

**Expected behavior**

The Prisma test suite should complete in under 30 minutes, or as quickly as competitor databases.

**Additional context**

Making this test suite fast will allow Prisma, and possibly more generally other third-party tools, to iterate more quickly using CockroachDB.

Jira issue: CRDB-18910

**Comment by ajwerner** [comment]
@devadvocado for awareness. It might be nice if you were to run these at some point, if you find time. I'll take a stab at triaging the runtime and report back here.

**Comment by ajwerner** [comment]
I re-ran these yesterday. The `main` branch took around 7 minutes. I don't know what "fast" is but that seemed not terrible to me. I don't know that this is actionable. We can re-open when we have more data.
