### ISSUE TITLE
bazci: can collect .xml files from prior benchmark runs 

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#86773]
Example: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/6208678?buildTab=overview&showRootCauses=false&expandBuildChangesSection=true&expandBuildDeploymentsSection=true&expandBuildTestsSection=true#%2Fbazel-testlogs%2Fpkg%2Fccl%2Fchangefeedccl%2Fchangefeedccl_test

I suspect that this build agent ran a benchmark build configuration before running the unit tests, and the `test.xml` files from that run were leftover in `bazel-testlogs`. Then the unit test run came and picked up on these old `test.xml` files, not realizing they were stale.

Epic CRDB-15060

Jira issue: CRDB-18924

**Comment by srosenberg** [comment]
> I suspect that this build agent ran a benchmark build configuration before running the unit tests, and the `test.xml` files from that run were leftover in `bazel-testlogs`. Then the unit test run came and picked up on these old `test.xml` files, not realizing they were stale.
> 

That's also my hypothesis. Screenshots below prove that. (Note the nanosecond duration of the highlighted benchmark; it would be physically impossible to have the exact same timing on two independent runs :)

<img width="1566" alt="unit_tests" src="https://user-images.githubusercontent.com/1616764/186473251-75041265-485a-4f30-af3e-e2c78af99e9a.png">
<img width="1385" alt="bench" src="https://user-images.githubusercontent.com/1616764/186473258-684e4116-e505-44bd-adbf-1742883a88d5.png">

**Comment by srosenberg** [comment]
We probably want to set `--cache_test_results=no` for both of these jobs.

**Comment by rickystewart** [comment]
> We probably want to set --cache_test_results=no for both of these jobs.

This may fix some of these cases but isn't a surefire thing. The "real" solution is going to be a bit more heavyweight but shouldn't be prohibitively costly. I should have a PR out within a couple hours.
