### ISSUE TITLE
changefeedccl: add metric for paused changefeeds 

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#86789]
We should have a changefeed_paused prometheus metric that users can monitor and alert on. This is especially important when using the on_error=paused feature. 

When we add this we should add it to the metrics we export to datadog.

Jira issue: CRDB-18935

Epic CRDB-8669

**Comment by amruss** [comment]
This is a big oversite, we should make sure to do it in 22.2

**Comment by amruss** [comment]
Related: https://github.com/cockroachdb/cockroach/issues/85467

**Comment by miretskiy** [comment]
@jayshrivastava  -- I believe you're working on this as part of your jobs
work.
If I'm wrong, feel free to unassign.

**Comment by jayshrivastava** [comment]
Closed by https://github.com/cockroachdb/cockroach/pull/89752
