### ISSUE TITLE
ui: list filters in effect in overview pages

### ISSUE THREAD

**Issue by xinhaoz** [cockroachdb/cockroach#86787]
Currently, in overview pages we do not list what filters are in effect alongside the 'clear filter' button. To see on the UI which filters are selected, users need to open the filter drop down menu. We should consider listing out the filters in effect clearly on the page, perhaps alongside the clear button.

![image](https://user-images.githubusercontent.com/20136951/186488374-d868f2aa-3349-49fc-aae4-84fcd1cf00da.png)

Jira issue: CRDB-18934

**Comment by maryliag** [comment]
This info is now available
