### ISSUE TITLE
roachtest.costfuzz failed due to scientific notation v. decimal notation

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#86796]
roachtest.costfuzz [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6107800?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6107800?buildTab=artifacts#/costfuzz) on master @ [f4042d47fa8062a612c38d4696eb6bee9cee7c21](https://github.com/cockroachdb/cockroach/commits/f4042d47fa8062a612c38d4696eb6bee9cee7c21):

```
		  |   		"1.11,0,1986-08-04 01:37:10.00077 +0000 UTC,-3",
		  | + 		".",
		  |   		"496594284072061722",
		  | + 		"E+27,-2.",
		  |   		"0",
		  | - 		"00000000,-2.0129749084999493,-3496594284072061722000000000",
		  | + 		"129749084999493,-3.496594284072061722E+27",
		  |   	}, ""),
		  |   	"1.11,0,1988-02-02 02:14:01.000494 +0000 UTC,-3496594284072061721"...,
		  |   	"1.11,0,1989-02-10 10:51:16.000188 +0000 UTC,-3496594284072061719"...,
		  |   	"1.11,0,1991-03-12 19:37:05.000941 +0000 UTC,-3496594284072061721"...,
		  |   	"1.11,0,1991-04-05 23:25:23.000015 +0000 UTC,-3496594284072061586"...,
		  |   	"1.11,0,1997-05-19 00:08:20 +0000 UTC,-5.84595187342303731122E+29"...,
		  |   	strings.Join({
		  |   		"1.11,0,1997-05-20 03:46:40 +0000 UTC,-34965942840715594523602606",
		  |   		"28.034",
		  | - 		"0",
		  |   		",-2.0129749084999493,-3496594284071559452360260628.034",
		  | - 		"0",
		  |   	}, ""),
		  |   	"1.11,0,1999-02-23 01:18:56.000557 +0000 UTC,-3496594284072061721"...,
		  |   	"1.11,0,2002-08-13 23:25:33.000643 +0000 UTC,-3496594284072061721"...,
		  |   	... // 62 identical elements
		  |   	"1.11,0,2019-02-27 14:32:12.000197 +0000 UTC,-3496594284072061721"...,
		  |   	"1.11,0,2020-07-02 23:58:51.00079 +0000 UTC,-34965942840720617219"...,
		  |   	strings.Join({
		  |   		"1.11,0,2021-12-24 00:36:05.000773 +0000 UTC,-3",
		  | + 		".",
		  |   		"496594284072061722",
		  | + 		"E+27,-2.",
		  |   		"0",
		  | - 		"00000000,-2.0129749084999493,-3496594284072061722000000000",
		  | + 		"129749084999493,-3.496594284072061722E+27",
		  |   	}, ""),
		  |   	"1.11,0,2025-09-22 01:21:45.000531 +0000 UTC,-3496594284072061721"...,
		  |   	"1.11,0,2026-12-12 07:32:02.000115 +0000 UTC,Infinity,-2.01297490"...,
		  |   	... // 8 identical elements
		  |   }
		  | sql: SELECT
		  | 	1.11:::DECIMAL AS col_1,
		  | 	0:::OID AS col_2,
		  | 	tab_1.col2_1 AS col_3,
		  | 	tab_1.col2_3 AS col_4,
		  | 	(-2.0129749084999493):::FLOAT8 AS col_5,
		  | 	tab_1.col2_3 AS col_6
		  | FROM
		  | 	defaultdb.public.table2@[0] AS tab_1
		  | ORDER BY
		  | 	tab_1.col2_3 ASC
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.leafError
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*costfuzz.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

_Originally posted by @cockroach-teamcity in https://github.com/cockroachdb/cockroach/issues/85658#issuecomment-1216192610_

Jira issue: CRDB-18938

**Comment by rytaft** [comment]
@michae2 can you please take a look at this one? Doesn't look like a correctness issue, but we should figure out what's going on and fix it to prevent the test from continuing to fail for this reason.

**Comment by DrewKimball** [comment]
This looks related to, or possibly a dup of #86790.

**Comment by rytaft** [comment]
This is fixed by https://github.com/cockroachdb/cockroach/pull/89200
