### ISSUE TITLE
sql/copy: implement something akin to PG's copy freeze

### ISSUE THREAD

**Issue by cucaroach** [cockroachdb/cockroach#86792]
PG has an optimized version of COPY that works in the following scenario:

1. COPY has FREEZE annotation
2. COPY is under explicit transaction
3. Target table was created under same transaction and isn't yet visible

I don't know about edge cases (like can this transaction read from or do more writes to the table after the COPY?  can the table also have secondary indexes?)

I also don't know what the state of CRDB's transactional DDL is but if we had it we could just catch this scenario and hand over the COPY to the bulkio import path I think.   @dt  @ajwerner thoughts?  The rationale here is we want a way to speed up the initial bulk full table copies DMS services do.

Jira issue: CRDB-18937

**Comment by rafiss** [comment]
do you plan to address https://github.com/cockroachdb/cockroach/issues/85573 with this issue?

**Comment by rafiss** [comment]
consider tossing this in epic CRDB-18320

**Comment by cucaroach** [comment]
This looks like a straight up dupe of #85573
