### ISSUE TITLE
backupccl: write table stats in order in backup metadata sst

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#86806]
#86078 caused the BackupMetadataSST writer to write out of order kvs related to table stats, causing the pebble writer to error, as seen in #86289. One working theory for why this occurs:

Backup currently pulls the stats out of the stats cache and then constructs keys to write into the SST.  After #86078, the cache now returns stats per-column stats; however, the keys backup generates look like they are just based on the table id and the stats id.  Now, perhaps each key is no longer unique when you put the per-columns stat forecasts in the mix.

Jira issue: CRDB-18943

**Comment by ajwerner** [comment]
This lead to a bors failure [here](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/7650747?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true).
