### ISSUE TITLE
bazci: timed out tests are not reported correctly in test.xml file

### ISSUE THREAD

**Issue by srosenberg** [cockroachdb/cockroach#86827]
When a test or multiple tests time out, their names are not reported in test.xml; instead, the name of the test binary is logged. The time attribute is also not logged. This is a known problem [1] in `rules_go`, but it hasn't been addressed in nearly 2 years.

While the test timeouts are less frequent than other types of flaky tests, the inability to accurately track timeouts is a serious deficiency. E.g., our dashboards (and CI build logs) may indicate that `pkg/ccl/changefeedccl/changefeedccl_test_/changefeedccl_test_shard_11/16` is failing, but there are actually multiple tests inside that shard which timed out.

I ran a query using a simple heuristic–test name doesn't begin with the `Test` prefix. Over the last 30 days, these are mis-reported tests which timed out,

<img width="1581" alt="unit_test_timeout_30days" src="https://user-images.githubusercontent.com/1616764/186536120-db87a7a1-53b8-49c3-849c-eb764995858d.png">

[1] https://github.com/bazelbuild/rules_go/issues/2718

Jira issue: CRDB-18948

Epic CRDB-15060

**Comment by rghdrizzle** [comment]
Hey I would like to work on this , also pls do guide me since im new to this.

**Comment by rickystewart** [comment]
To my knowledge this is entirely fixed. I'm closing this now. Obviously, re-open if there are noticeable issues.
