### ISSUE TITLE
kv/kvserver/tenantrate: `TestCloser` is flakey

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#86822]
**Describe the problem**
<img width="1384" alt="Screen Shot 2022-08-24 at 5 59 12 PM" src="https://user-images.githubusercontent.com/1839234/186531124-9823e83f-1e4b-4b64-bb81-af2630fad3d8.png">

[Please describe the issue you observed, and any steps we can take to reproduce it:](https://teamcity.cockroachdb.com/test/546789279850078470?currentProjectId=Cockroach_Ci_TestsGcpLinuxX8664BigVm&expandTestHistoryChartSection=true)

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/6228580?showRootCauses=false&expandBuildChangesSection=true

Jira issue: CRDB-18947

**Comment by irfansharif** [comment]
Off of latest master.

```
$ dev test pkg/kv/kvserver/tenantrate -f TestCloser --stress
...
49356 runs so far, 0 failures, over 5m5s
50165 runs so far, 0 failures, over 5m10s
50986 runs so far, 0 failures, over 5m15s
51801 runs so far, 0 failures, over 5m20s
```

**Comment by irfansharif** [comment]
Huh, ok repros on linux. Bisecting.

**Comment by irfansharif** [comment]
On my GCE worker I trip things up as far back as 05bc43dcab3471c689 using `dev test pkg/kv/kvserver/tenantrate --stress`. What's happening here?

**Comment by irfansharif** [comment]
Bisecting took me conclusively to 61674bc51ae20005b9fde0bd548c4c4a4f2e9e1c (+cc @andy-kimball). Triple checked running the preceding commit and that one. I'll keep this on the KV plate for now to get to during stability. I'm not sure why this only starting firing in CI now but it should be easy to fix.

**Comment by kvoli** [comment]
Struggling to repro this. Tried both `--stress` and `--stress --race` on `87ed064dc23eab6948ee8a07e8507f150bda0e44` master.


```
dev test pkg/kv/kvserver/tenantrate -f TestCloser --stress --race
312542 runs so far, 0 failures, over 31m10s
```

Going to go back to confirmed commit and see if this repros.

**Comment by kvoli** [comment]
It looks like the update to RU accounting made it such that the request that was meant to hit a try again/retry timer in this test, doesn't.

The configured limit for the test:

```
tenant 2 rate limiter initialized (rate: 6000 RU/s; burst: 60000 RU)
```

The request is around `46k` `1024Mb * 45`. Which slides under the burst limit so the request never waits.

The updated accounting made this req cheaper I believe.

Pushing the req to double the size  `2 * (1<<30)` solves this issue.
