### ISSUE TITLE
backupccl: run table BACKUP/RESTORE in `sql/schemachanger/sctest/cumulative.go` Backup tests

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#86835]
The Backup test in `cumulative.go`  tests that the schema changer can handle being backed up and restored correctly., but it only covers Database/Cluster backups. Table backups should also be covered.  This work should be done with the schema team.

Jira issue: CRDB-18953

**Comment by ajwerner** [comment]
@Xiang-Gu I'm adding this to your queue.
