### ISSUE TITLE
rangefeed: ~100ms busy loop on TryGet on shutdown

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#86859]
Observed the following in tight loops in the logs on v22.1.9 during an L2 escalation (https://github.com/cockroachlabs/support/issues/1729)

> kv/kvserver/rangefeed/budget.go:166 ⋮ [n102,s425,r509150/2:‹/Table/54/6/111345{1/"…-6/"…}›,rangefeed] 1512552 trying to get allocation from already closed budget

This comes from

https://github.com/cockroachdb/cockroach/blob/0fbc2d56f7e3a69749f5cf9836d6baecc94425c0/pkg/kv/kvserver/rangefeed/budget.go#L165-L168

The log file contained >100k such records (from a number of such bursts). One burst I checked took ~100ms.

The spammy logging is a stability problem. But it is also problematic that we're busy-looping for ~100ms, as this can cause performance issues:

https://github.com/cockroachdb/cockroach/blob/0fbc2d56f7e3a69749f5cf9836d6baecc94425c0/pkg/kv/kvserver/rangefeed/budget.go#L189-L193

That loop should pace itself and avoid busy-looping. Ideally it would not loop at all if the budget is already closed.

Perhaps there is an issue with teardown that needs to be investigated.

Jira issue: CRDB-18969

**Comment by aliher1911** [comment]
Waiting for debug logs access if they survived.
@tbg maybe you still have some? I'm not sure how does this turn into busy loop. replenish will not be updated after the budget is closed so you would only get it once. Were those messages coming from different feeds? There's definitely case for context being cancelled and that could cause it to try and fail.

**Comment by erikgrinaker** [comment]
No, these are all from a single rangefeed. Here's another example, I have 4028 identical messages over a 100ms period:

```
kv/kvserver/rangefeed/budget.go:166 ⋮ [n102,s429,r508690/2:‹/Table/54/6/11164{67/"…-70/"…}›,rangefeed] 1510420 trying to get allocation from already closed budget
```
