### ISSUE TITLE
admission: enable disk bandwidth bottleneck resource

### ISSUE THREAD

**Issue by sumeerbhola** [cockroachdb/cockroach#86857]
Followup to #82898 which created the basic infrastructure, configuration scheme, and did experimentation with regular and elastic kv0 traffic.
- [x] Eliminate the need to provide the disk-name and bandwidth fields for common environments e.g. linux with store on EBS or GCP PD. This will make it possible to enable this by default for v23.1.
- [x] We need some more experiments, with user-facing regular SQL traffic and lower-priority (and elastic) background work like index backfills. This overlaps with #85641 and #85469. Prior experimentation was done over at https://github.com/cockroachdb/cockroach/pull/82813#issuecomment-1183477491.
- [x] https://github.com/cockroachdb/cockroach/issues/121576
- [x] Enable for v24.3

cc: @irfansharif @andrewbaptist 

Jira issue: CRDB-18968

Epic: CRDB-37479

**Comment by sumeerbhola** [comment]
We should remember to also extend the disk bandwidth control to encompass disk writes of sstables due to incoming range snapshots.

**Comment by jbowens** [comment]
As a part of online restore, we'll need admission control to control downloading of external sstables so that we can download as fast as we can without affecting foreground workload latencies.

**Comment by dshjoshi** [comment]
@aadityasondhi  @nicktrav Is this in progress or done or still in backlog? If it is in progress or done, can we update the status?

**Comment by aadityasondhi** [comment]
The functionality should be complete as of https://github.com/cockroachdb/cockroach/pull/129005.

The remaining work would be to:
* Enable on internal test clusters (DRT)
* Enable on cloud clusters
* Write public docs for users

The enable part means setting the cluster setting or store config flags for the provisioned bandwidth.

**Comment by aadityasondhi** [comment]
At this point, this is complete. The remaining work to enable in cloud is tracked internally in [Jira](https://cockroachlabs.atlassian.net/browse/CRDB-37479).
