### ISSUE TITLE
storage: write time series about ranges with active lease and lease errors

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#869]
what are the interesting events?

* rate of renewals per store/accounting prefix
* rate of failed attempts to acquire the lease per store/accounting prefix

**Comment by bogdanbatog** [comment]
I'd like to help with this one. I am halfway through researching the relevant code parts and I'll get back with a short plan, before actually starting.

**Comment by bogdanbatog** [comment]
I'm coming back with a tentative plan. I've read through relevant code, but I may not have enough understanding at the time for all the [small] decisions in this change. Please intervene.

1) Extend `StoreStatusMonitor` with a map from `roachpb.RangeID` to a new structure having two `metric.Rate` fields, one for LeaseAquired event and one for LeaseRequestFailed event. The reason for indexing the map by RangeID is that the `Store.mu.replicas` uses the same index and I suppose it will be easier (the other options are to index by starting key of the range, or replica ID) ... I'm not sure which one is best, now.

2) in `storage/feed.go` add a new event type `LeaseRequestEvent` and add an event handler to `StoreEventListener` interface, named `OnLeaseRequest`

3) in `server/status/monitor.go` implement `OnLeaseRequest`. Call `metric.Rate.Add(1.0)`. Also, our new structure must be maintained during Range Register, Split, Merge, Remove.

4) in `storage/replica_command.go` the result of a `LeaderLeaseRequest` will be used to feed the new event into the relevant storage. Actually I'm not sure this is the proper place or the caller side.

5) TODO: see if we need changes in `server/status/recorder.go`. Where will the new time series be consumed? Should it reach the UI? 

6) Update relevant tests and write new tests for the new time series

Most of the time, only one replica in a range will have meaningful events (LeaderLeaseRequests). The number of relevant time series, at a given time, equals the number of Ranges. But we'll keep that times the number of Replicas. Maybe there's a more efficient way to store them.

This is my progress so far. I still have things to clear up before actually coding it. I could continue and get back with a clearer plan, but I want to know I'm not completely wrong :)

**Comment by mrtracy** [comment]
Hi bogdanbatog,

Thanks for your interest in this issue! I have a bit of guidance for you:

1. I have just filed issue #4021 which calls for the deprecation of the event feed; the events feed is adding unneeded complexity to our metrics system, and we are going to simplify it by having low-level systems interact with metrics directly.  Instead, the Store will have a set of metrics objects that it interacts with directly, and those metrics will be registered with the recorder.  This means that step 2 and 3 will not be necessary; `replica_command` will increment metrics directly instead of creating a feed event.

   I would recommend looking at `sql/executor.go`, specifically at the field `Executor.metaRegistry`. Instead of providing a feed to the Executor, the recorder provides a metrics registry to it, and the executor directly adds metrics into that registry.  A similar pattern will likely be used with the Store object.

2. We should not record the LeaseRenewals/Requires _per range_ into our time series data.  There are likely to be hundreds or even thousands of ranges per store in a running cluster, and this will generate an excessive number of time series with limited utility.  
    Instead, I suggest that we should only record lease renewals and failures _per store_ for now; this will still indicate to us that the system is working, and will react visibly to the lease-related problems that I can anticipate.

I believe that @cuongdo is also adding some new transient metrics right now; be careful not to duplicate the work of adding a registry to the store.

**Comment by bogdanbatog** [comment]
I'm back and I'll be more responsive now. Thank you for the guidance, it's indeed easier to bootstrap with clear inside :) info. I thought it's easier to discuss on code at this point, so [I made this commit](https://github.com/bogdanbatog/cockroach/commit/7790005aea68015609b3b025e6e06f4e1d13a243). 

I followed your direction and added the `Registry` to the `Store`, but 
1) now there are two placeholders for metrics: in `Store` and in `StoreStatusMonitor`. Could this work as a transition until Event feeds are removed? (and all metrics will be moved to the Store Registry?)
2) the Store Registry is connected to the Server Registry (passed in `StoreContext`) when the Store is started. This may not be the most appropriate way. Also, I wasn't sure how to handle the case when no Server Registry is provided - weather to make it mandatory - and update all tests to provide one, or to silently ignore it (I added a warning).

It seems I need another round of guidance (even if the commit works now and exposes the new time series). But I may be able to handle the deprecation of the Event feed as well, after that.

**Comment by mrtracy** [comment]
Hi @bogdanbatog,

Sorry for the delayed followup, there was quite a bit of active work on this area in the last few weeks.  #4021 was completed, and the event feed is now gone.  A lot of your work is still usable, but it will need to be modified to the new model:

+ A `Store` creates its own `metric.Registry` when it is created.  This store is accessed from higher level components by the `Store.Registry()` method.
+ Metrics recorded by the store are grouped into the `storeMetrics` object, which has a fairly straightforward design.

You will want to take the new metrics you are recording and add them to the `storeMetrics` object.  You should not need to add anything above the store level.

**Comment by bogdanbatog** [comment]
Thanks, I'll make the update in the next days. I expect it to be pretty straightforward.

**Comment by bogdanbatog** [comment]
Ok, I've [added it here](https://github.com/bogdanbatog/cockroach/commit/a1573d4d3274dfcdb91937520eece7f2d760dfa4) and in the process I've fixed a tiny issue in recorder `MarshalJSON` (which was failing). Now the new time series are exposed on the `_status/metrics/` url. Should I add them to the ui as well? Also, I'm not sure what is the best way to test this.

**Comment by mrtracy** [comment]
Hi again @bogdanbatog,

Apologies again for the delayed response; why don't you open a pull request with your proposed commit against the main CockroachDB repo? When you have a code change which is potentially ready to commit, that is the fastest way to get a response from our contributors.

I've added a bit of code review to your commit, but if you open up a pull request you're likely to get comments from some of our other contributors, and we'll be able to merge it directly once approved.

Be sure to rebase: I think another contributor already fixed the MarshalJSON error that you fixed (although I could be wrong).

**Comment by mrtracy** [comment]
Closed by #5596
