### ISSUE TITLE
stability: Coalesce duplicate (sync) write intent errors

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#8692]
When many consistent reads hit the same write intent, they will each try to push the transaction and resolve the intent. We coalesce these operations if the read was inconsistent (so the resolution is performed asynchronously); we should do the same for the synchronous path used by consistent reads. It's more subtle because these pushes are not exact duplicates for each other: a higher-priority transaction could win the push while an in-progress lower-priority one could fail. We at least want to block all pushes that are less likely to succeed than the one in progress; I'm not sure whether it makes sense to allow higher-priority pushes to proceed or wait for the first one to finish first.

On the beta cluster nodes are currently running out of memory due to an accumulation of these PushTxn attempts (that so many pushes are attempted but none are succeeding is a separate issue).

**Comment by tschottdorf** [comment]
see also #7503.

**Comment by tschottdorf** [comment]
see also https://github.com/cockroachdb/cockroach/issues/627.

**Comment by tschottdorf** [comment]
Closing in favor of #627.
