### ISSUE TITLE
ui: when the ui is disconnected it makes a huge number of requests

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#8699]
When a request fails it's instantly retried. This means when we lose connection to the backend server we are constantly making requests that all fail to connect instantly.

After a failure, we need to add a pause before retrying to prevent this.

**Comment by maxlang** [comment]
cc @tamird

**Comment by mrtracy** [comment]
@maxlang is there anything else we should be doing here?  Did your pull requests fix this issue, or was there a more permanent fix you wanted instead?

**Comment by spencerkimball** [comment]
@mrtracy could you close this out as appropriate?

**Comment by dianasaur323** [comment]
I think it's safe for us to close this out unless the problem reappears.
