### ISSUE TITLE
Backup job of the cluster runs endless when a single database is corrupted

### ISSUE THREAD

**Issue by jamct** [cockroachdb/cockroach#86992]
**Describe the problem**

In a dev environment I was trying out detached backup jobs of the whole cluster (`BACKUP INTO`). After I crashed a dev pod and stopped decommissioning all backup jobs run indefinely in status `running`. No error, nothing. Even if I run the job attached, there is no error message. Just running forever.

I tried out some backup commands and found the problem: When I try to backup a single database (`BACKUP DATABASE`) I get an error message as expected, telling me what went wrong (in my dev environment the system database had a faulty range).

**To Reproduce**

Set up a cluster with three nodes and kill a node. Try decommissioning of the killed node and stop decommissioning process to force a broken range. Start a backup job of the whole cluster. It will run forever.

**Expected behavior**

The backup job should not run forever, when a single database is broken. It should throw an error (like `BACKUP DATABASE` for a single database does). Running forever is not a good idea because maybe you never see your backup is not working!

**Environment:**
 - CockroachDB version v22.1.6

Jira issue: CRDB-19076

Epic CRDB-21944

**Comment by stevendanna** [comment]
@jamct Apologies for the delay here.  I'll be trying to reproduce this locally and see if I can see the same behaviour.

**Comment by stevendanna** [comment]
In my own attempts to re-produce this, killing decommission doesn't reliably create a broken range. 

If I break a range via other methods, I do see backup hang for up to 5 minutes after which it hits the 5 minute timeout we have around ExportRequests.

That is not to say that I don't believe the report here, I can imagine the the timing of our different reproduction cases could affect things greatly here.
