### ISSUE TITLE
sql: incorrect doc for ALTER TABLE ... ALTER PRIMARY KEY

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#87004]
**Describe the problem**

The CLI documentation that is available for `ALTER TABLE` shows an invalid command for `ALTER TABLE ... ALTER PRIMARY KEY`.

**To Reproduce**

Run `./cockroach demo` on master.

View the help info for `ALTER TABLE` by running `\h ALTER TABLE`.

One of the available commands listed is `ALTER TABLE ... ALTER PRIMARY KEY USING INDEX <name>`. However, this syntax doesn't work. If I try to run it, I get this error:
```
> ALTER TABLE tab ALTER PRIMARY KEY USING INDEX tab_col1_key;
invalid syntax: statement ignored: at or near "index": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
ALTER TABLE tab ALTER PRIMARY KEY USING INDEX tab_col1_key
                                        ^
HINT: try \h ALTER TABLE
```

Looking at `sql.y`, it seems like only syntax that is supported for `ALTER PRIMARY KEY` is:
```
ALTER TABLE ... ALTER PRIMARY KEY USING COLUMNS '(' index_params ')' opt_hash_sharded opt_with_storage_parameter_list
```

However, this is not one of the commands listed for `ALTER TABLE`.

**Expected behavior**

The documentation should match the supported command.

Jira issue: CRDB-19088

**Comment by rafiss** [comment]
You can use a `/* SKIP DOC */` comment to hide a rule from the generated docs.

**Comment by ajwerner** [comment]
Thank you!
