### ISSUE TITLE
sql: destination argument of COPY is ignored

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#87006]
**Describe the problem**

It seems like the `DESTINATION` argument of `COPY` is ignored when `COPY` is run from the command line.

**To Reproduce**

On master, run `./cockroach demo`. Then run:
```
CREATE TABLE tab (col1 STRING, col2 STRING, col3 STRING, col4 STRING, col5 STRING, col6 STRING);
COPY tab FROM STDIN with destination = 'tab1.csv';
-- Now paste the following:
'remove'	'planned'	'slave'	'instrument'	'shoe'	'rays'
'doing'	'bring'	'color'	'busy'	'flat'	'difficulty'
'western'	'mouse'	'seems'	'fully'	'memory'	'neighborhood'
'cup'	'fairly'	'orbit'	'visit'	'lay'	'cave'
'dry'	'vast'	'instrument'	'scared'	'toy'	'completely'
'paragraph'	'roll'	'atomic'	'doctor'	'best'	'finish'
'job'	'suddenly'	'box'	'affect'	'on'	'date'
\.
```

Although the data is copied into `tab`, the destination `tab1.csv` seems to be ignored. The command succeeds but no file is created.

**Expected behavior**

I'm not sure exactly what the expected behavior should be since COPY and this DESTINATION parameter are not documented. But I would expect *something* to happen -- either an error message or else creation of the file.

Jira issue: CRDB-19090

**Comment by cucaroach** [comment]
Where did this DESTINATION arg come from?   Its not something PG supports.  Is this bug just that we don't throw an error on arbitrary unsupported COPY options?
