### ISSUE TITLE
filter out "$ api-v2-sql" from sessions page

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#87009]
Currently we're showing a lot of info coming from "$ api-v2-sql" on SQL Activity page. We should filter them out, specially on the Sessions page.

Jira issue: CRDB-19092

**Comment by kevin-v-ngo** [comment]
@xinhaoz, i'm seeing **$ api-v2-sql** in the Statements and Transactions details pages as well. Do you want a separate issue tracking it?

**Comment by xinhaoz** [comment]
@kevin-v-ngo we already have one, https://github.com/cockroachdb/cockroach/issues/84387.
It'll be addressed in this PR https://github.com/cockroachdb/cockroach/pull/87136
