### ISSUE TITLE
GC for DROP DATABASE and node decommissioning hangs if database is missing ranges

### ISSUE THREAD

**Issue by jrcichra** [cockroachdb/cockroach#87022]
**Describe the problem**
After losing multiple nodes in rapid succession where the cockroachDB data files were not recoverable on those nodes, some ranges became permanently unavailable.
I decommissioned the nodes I knew were never coming back. Some of these decommission jobs never returned, since there are technically ranges on them that cockroach would like to access, but I have no way of recovering them.
I renamed the affected databases with `alter database rename to` and proceeded to restore the affected databases from S3.
That went all well and good, so I decided I can drop the databases with missing ranges. I did that and waited for the GC cycle (25hrs).
My CockroachDB Dashboard has a replication status showing 6 under-replicated and 6 unavailable ranges. I assumed this would drop to 0 once all the broken databases were deleted, and maybe then that would clear up the ranges thought to be on those lost nodes.

After 25hrs, my jobs are stuck with this message:
```
Performing Garbage Collection On Tables 1469, 1470, 1471, 1472
```
or
```
Performing Garbage Collection On 6 Tables
```
These jobs have been running for a few days.

Running `SHOW RANGES FROM DATABASE`on all the other tables, including the system table, do not show any unavailable ranges. Every database with an unavailable range I dropped and restored from backup.

**To Reproduce**
Make a CockroachDB cluster and database. Fill it with a meaningful amount of data. Shut down enough nodes to lose some ranges and don't power them back on. Decommission those nodes. Drop the databases with missing ranges. Wait for the GC cycle. See if the GC job ever finishes or the decommission node jobs with the missing ranges on them ever finish.

**Expected behavior**
When there's permanent loss of several nodes which contained ranges, the CockroachDB human operator should be able to restore the cluster to a healthy state without redeployment of the entire cluster. By decommissioning nodes and deleting affected databases (or with other additional documented steps), the number of missing ranges should go to 0 and all long-gone nodes can be decommissioned.

**Additional data / screenshots**
![image](https://user-images.githubusercontent.com/1342149/187197341-b514a723-895f-4593-be6f-362dd17d614d.png)

```
➜  ~ cockroach node status --insecure --decommission --host=smarty4:26257 
  id |                            address                            |                          sql_address                          |  build  |         started_at         |         updated_at         | locality | is_available | is_live | gossiped_replicas | is_decommissioning |   membership    | is_draining
-----+---------------------------------------------------------------+---------------------------------------------------------------+---------+----------------------------+----------------------------+----------+--------------+---------+-------------------+--------------------+-----------------+--------------
   1 | cockroachdb-0.cockroachdb.cockroachdb.svc.cluster.local:26257 | cockroachdb-0.cockroachdb.cockroachdb.svc.cluster.local:26257 | v22.1.6 | 2022-08-28 00:14:38.754183 | 2022-08-29 12:06:42.279682 |          | true         | true    |                53 | false              | active          | false
   2 | cockroachdb-2.cockroachdb.cockroachdb.svc.cluster.local:26257 | cockroachdb-2.cockroachdb.cockroachdb.svc.cluster.local:26257 | v22.1.6 | 2022-08-28 21:19:10.479879 | 2022-08-29 12:06:41.311659 |          | true         | true    |                53 | false              | active          | false
   3 | cockroachdb-1.cockroachdb.cockroachdb.svc.cluster.local:26257 | cockroachdb-1.cockroachdb.cockroachdb.svc.cluster.local:26257 | v22.1.6 | 2022-08-28 02:23:02.959927 | 2022-08-29 12:06:42.074826 |          | true         | true    |                52 | false              | active          | false
   4 | cockroachdb-4.cockroachdb.cockroachdb.svc.cluster.local:26257 | cockroachdb-4.cockroachdb.cockroachdb.svc.cluster.local:26257 | v22.1.6 | 2022-08-28 01:50:06.149162 | 2022-08-29 12:06:40.837666 |          | true         | true    |                55 | false              | active          | false
   5 | cockroachdb-5.cockroachdb.cockroachdb.svc.cluster.local:26257 | cockroachdb-5.cockroachdb.cockroachdb.svc.cluster.local:26257 | v22.1.6 | 2022-08-28 00:12:08.557358 | 2022-08-29 12:06:40.435449 |          | true         | true    |                54 | false              | active          | false
   6 | NULL                                                          | NULL                                                          | NULL    | NULL                       | 2022-08-29 11:40:07.13547  | NULL     | false        | false   | NULL              | true               | decommissioned  | false
   7 | cockroachdb-8.cockroachdb.cockroachdb.svc.cluster.local:26257 | cockroachdb-8.cockroachdb.cockroachdb.svc.cluster.local:26257 | v22.1.6 | 2022-08-28 00:15:45.653765 | 2022-08-29 12:06:41.489879 |          | true         | true    |                54 | false              | active          | false
   8 | NULL                                                          | NULL                                                          | NULL    | NULL                       | 2022-08-29 11:40:07.135474 | NULL     | false        | false   | NULL              | true               | decommissioning | false
   9 | NULL                                                          | NULL                                                          | NULL    | NULL                       | 2022-08-29 11:40:07.135477 | NULL     | false        | false   | NULL              | true               | decommissioning | false
  10 | cockroachdb-7.cockroachdb.cockroachdb.svc.cluster.local:26257 | cockroachdb-7.cockroachdb.cockroachdb.svc.cluster.local:26257 | v22.1.6 | 2022-08-28 06:03:40.048422 | 2022-08-29 12:06:40.359654 |          | true         | true    |                54 | false              | active          | false
  11 | cockroachdb-6.cockroachdb.cockroachdb.svc.cluster.local:26257 | cockroachdb-6.cockroachdb.cockroachdb.svc.cluster.local:26257 | v22.1.6 | 2022-08-28 01:19:22.250508 | 2022-08-29 12:06:41.993292 |          | true         | true    |                52 | false              | active          | false
  12 | cockroachdb-3.cockroachdb.cockroachdb.svc.cluster.local:26257 | cockroachdb-3.cockroachdb.cockroachdb.svc.cluster.local:26257 | v22.1.6 | 2022-08-29 11:41:24.844687 | 2022-08-29 12:06:41.546793 |          | true         | true    |                52 | false              | active          | false
(12 rows)

```

**Environment:**
 - CockroachDB version [e.g. 2.0.x] : `V22.1.6` cross-compiled for ARM64 with Bazel
 - Server OS: [e.g. Linux/Distrib] Ubuntu K3s 1.24 running in the Oracle Cloud on ARM Ampere.
 - Client app [e.g. `cockroach sql`, JDBC, ...] `cockroach sql`

**Additional context**
What was the impact?
Backups of the whole cluster fail, presumably because of the unavailable ranges.

Jira issue: CRDB-19104

**Comment by ajwerner** [comment]
So many things go wrong with unavailable ranges. We don't support a fully working system with unavailable ranges. You'll need to recover those ranges, perhaps with the loss-of-quorum tooling. I'm closing this as won't fix.

**Comment by jrcichra** [comment]
I understand. Could you point me to the loss-of-quorum tooling? I'll explore on my own from there.

**Comment by ajwerner** [comment]
See `cockroach  debug recover --help`, and be careful.
