### ISSUE TITLE
backupccl, changefeedccl: rename azure for external connections

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#87044]
Long term we may want to support more types of azure storage (see: https://cockroachlabs.atlassian.net/browse/CRDB-18959), what we have support now for is azure blob storage. 

We should rename what is now our "azure storage integration" to be referred to as azure-blob:// instead of azure://

This is important to do now, as we are aiming for cloud azure support in winter 2023 (preview) and will presumably have more azure users before the next release

Jira issue: CRDB-19120

**Comment by stevendanna** [comment]
https://github.com/cockroachdb/cockroach/pull/91978
