### ISSUE TITLE
sql: run unoptimized-query-oracle roachtest with `crdb_test=true` some of the time

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#87051]
See the conversation here: https://github.com/cockroachdb/cockroach/issues/86308#issuecomment-1230477074

Jira issue: CRDB-19126

**Comment by yuzefovich** [comment]
We're now running enabling runtime assertions via the roachtest infra, so no need to special case this behavior for unoptimized query oracle. Closing as fixed.
