### ISSUE TITLE
add units to telemetry logs

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#87064]
Some values on Telemetry logs for sampled query don't have a straight forward unit (e.g. Age). It would be good if units were added to the logs, so users don't have to look for documentation for clarification.

Jira issue: CRDB-19132

**Comment by matthewtodd** [comment]
Looking through [the definition of SampledQuery](https://github.com/cockroachdb/cockroach/blob/ab388681d8d397ef29506087762bbf8349ad6d63/pkg/util/log/eventpb/telemetry.proto#L32), I don't see any top-level fields that need further clarification.

It embeds a few other messages, however:
* [CommonEventDetails](https://github.com/cockroachdb/cockroach/blob/847fddd51e3d638b80941499de78eeb6d03d212d/pkg/util/log/logpb/event.proto#L19) - no further clarification needed.
* [CommonSQLEventDetails](https://github.com/cockroachdb/cockroach/blob/598c1702092783e5bc8d1303793d514c1b56a674/pkg/util/log/eventpb/events.proto#L28) - no further clarification needed.
* [CommonSQLExecDetails](https://github.com/cockroachdb/cockroach/blob/847fddd51e3d638b80941499de78eeb6d03d212d/pkg/util/log/eventpb/sql_audit_events.proto#L25) - as mentioned, it's unclear that the `age` field is measured in milliseconds.

So I think that means this ticket is about the `age` field alone, either renaming it or providing a sibling field, `age_ms` or something like that.

The `age` field is currently set in the code [here](https://github.com/cockroachdb/cockroach/blob/d9726d2ea3661b5dda1fd7ccd1a5ba6e05d8c8fc/pkg/sql/exec_log.go#L313).

**Comment by matthewtodd** [comment]
Notes from an internal Slack conversation:

> > Is it safe to rename fields here, or does something downstream depend on the field names in the JSON serialization?
> 
> Hm. the common SQL payloads are not limited to just the Telemetry logs, they would affect slow query logs and others I think. (https://www.cockroachlabs.com/docs/v22.1/eventlog)
I’d say given our docs that this would be considered a (minor, admittedly) breaking change.
Adding a new field would be nice, or introduce a cluster setting that lets you roll back to just Age , although I admit that does seem heavy-handed.

And another one:

> Check with the data field team about renaming the parameters, because their snowflake pipelines might need to change.
