### ISSUE TITLE
sql, stable ids for roles: complete remaining role id migrations in system tables

### ISSUE THREAD

**Issue by RichardJCai** [cockroachdb/cockroach#87079]
Role Ids were added to `system.users` in https://github.com/cockroachdb/cockroach/pull/81457.

In 22.2, once the migration is done and we're on `V22_2SystemUsersIDColumnIsBackfilled` version, we're guaranteed every user has an ID. Furthermore, in 23.1, we're guaranteed that all users have ids.

Eventually, we want to start using IDs to refer to users (ie for privilege checks) instead of usernames and support operations such as `alter role rename`.

We still have to migrate the following tables:
- [x] `system.role_members`
- [x] `system.privileges`
- [x] `system.database_role_settings`
- [x] `system.web_sessions`
- [x] `system.external_connections`

The `system.role_members` migration is PR is out https://github.com/cockroachdb/cockroach/pull/85928 and will wait for the 22.2 branch cut before merging.

The migrations should look like the migration done in https://github.com/cockroachdb/cockroach/pull/85845

Jira issue: CRDB-19140
Epic CRDB-19134

**Comment by ajwerner** [comment]
Not explicitly mentioned, but the privileges stored in descriptors need to be migrated.

**Comment by andyyang890** [comment]
Do we also need to migrate `system.scheduled_jobs` and `system.external_connections`? They both have an `owner` column.

**Comment by rafiss** [comment]
Yes, let's do those ones also.
