### ISSUE TITLE
util/metric: HELP text too long for AWS managed prometheus

### ISSUE THREAD

**Issue by antifuchs** [cockroachdb/cockroach#87112]
**Describe the problem**

I'm setting up [AWS managed prometheus](https://docs.aws.amazon.com/prometheus/latest/userguide/what-is-Amazon-Managed-Service-Prometheus.html) (AMP) and ingesting metrics scraped from hosted cockroachdb, via remote_write on a local prometheus server. This works well _if_ I turn off the remote-writing of metrics metadata. Otherwise, the prometheus server remote-writing to AMP shows this error:

```
ts=2022-08-30T13:15:59.179Z caller=dedupe.go:112 component=remote level=error remote_name=f52d9c url=https://aps-workspaces.us-east-1.amazonaws.com/workspaces/ws-[redacted]/api/v1/remote_write msg="non-recoverable error while sending metadata" count=500 err="server returned HTTP status 400 Bad Request: metadata 'HELP' value too long: \"Latency histogram for handling a Raft ready.\\n\\nThis measures the end-to-end-latency of the Raft state advancement loop, and\\nin particular includes:\\n- snapshot application\\n- SST ingestion\\n- durably appe\" metric \"raft_process_handleready_latency\""
```

IOW, it's complaining about this help text: https://github.com/bdarnell/cockroach/blob/741dacf4d1dbab94bc1ac15d20181fb4f0770e54/pkg/kv/kvserver/metrics.go#L577-L595

**To Reproduce**

1. Set up CockroachDB cluster in the cloud or elsewhere.
2. Set up prometheus metrics scraping the `"/_status/vars"` metrics path from it.
3. Set up remote_write into AWS managed prometheus
4. See the error above, see that ingesting the metrics batch fails.

**Expected behavior**
I would expect all metadata to be possible to import.

**Additional data / screenshots**

**Environment:**
 - CockroachDB version released after [Sep 14, 2021](https://github.com/cockroachdb/cockroach/pull/69858)
 - Client app prometheus v2.36.2 and aws managed prometheus.

**Additional context**

I'm not sure the fault here really lies with CRDB (and argh, this HELP text is really well-written and useful!), but I wanted to flag this here as CRDB is the one thing with a public bug tracker that can fix it, in case others run into this issue too.

Jira issue: CRDB-19155

**Comment by antifuchs** [comment]
I have a work-around for the issue, but it's a bit annoying: That is, to turn off the sending of all metric metadata in the remote_write portion, via 

```yaml
metadata_config:
  send: false
```

**Comment by erikgrinaker** [comment]
Thanks for reporting! The given help text is 1122 bytes, so I'm guessing that their limit is 1024 bytes or so (could you confirm this?). That seems like a reasonable maximum length to use for these help texts in any case, so we'll try to pare it down and enforce a 1024-byte maximum for these texts.

**Comment by erikgrinaker** [comment]
Posted a PR in #87166, but would be great if we could confirm that 1024 bytes is actually within their limit.

**Comment by antifuchs** [comment]
Thank you so much for the super quick turn-around! I found a public bug tracker for AMP and filed a request for docs / improvement there!
