### ISSUE TITLE
ui: advanced debug, profiling UI target node undefined

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/cockroach#87150]
If you go to Advanced Debug in the DB Console and click "CPU profile" under "Profiling UI" without changing the target node selector, you'll get an error message because the URL is constructed with an `undefined` node ID:

For example,
```
http://jackson-1661894798-01-n5cpu32-0001.roachprod.crdb.io:26258/debug/pprof/ui/cpu/?node=undefined&seconds=5&labels=true
```

Jira issue: CRDB-19179

**Comment by ajwerner** [comment]
Maybe duplicates https://github.com/cockroachdb/cockroach/issues/83623?

**Comment by jbowens** [comment]
Thanks, definitely does!
