### ISSUE TITLE
ci: TestDockerCLI does not collect node artifacts

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#87164]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/5076964/187614309-0e303806-2a79-49ed-86b3-e4a8471e601d.png)

^-- these logs are not in the artifacts dir and so aren't available for debugging later.

**Describe the solution you'd like**

Make sure they're collected.  @srosenberg [says](https://cockroachlabs.slack.com/archives/C023S0V4YEB/p1661886394243629?thread_ts=1661849569.251039&cid=C023S0V4YEB) that something

> [is] missing --test_output=errors which normally gets activated via --config=test:ci

Jira issue: CRDB-19187

**Comment by rickystewart** [comment]
I think `ac9a50ffe46330fcb0c778c3d3025fd836474488` fixed this -- is the error case you're citing before or after this commit?

**Comment by tbg** [comment]
https://teamcity.cockroachdb.com/viewLog.html?buildId=6292680&buildTypeId=Cockroach_Ci_Tests_Acceptance&tab=buildChangesDiv

This is based on 00aa1c43c28cee30490d8ebf95a8f5421bc5e823m which indeed does not contain ac9a50ffe46330fcb0c778c3d3025fd836474488. Thank you!
