### ISSUE TITLE
Support updating array elements by positional syntax

### ISSUE THREAD

**Issue by lukaseder** [cockroachdb/cockroach#87173]
**Is your feature request related to a problem? Please describe.**

In PostgreSQL, it's possible to update array elements by using the usual positional syntax. CockroachDB doesn't support this yet.

**Describe the solution you'd like**

This works in PostgreSQL:

```sql
create table t (i int primary key, j int[]);
insert into t values (1, array[1, 1]);
update t set j[1] = 2 returning *;
```

It produces:

```
|i  |j    |
|---|-----|
|1  |{2,1}|
```

Jira issue: CRDB-19193

**Comment by rafiss** [comment]
This might relate to the challenges with updating JSON types using subscripting: https://github.com/cockroachdb/cockroach/issues/77434#issuecomment-1173263871

**Comment by mgartner** [comment]
Closing as a duplicate of #77434.
