### ISSUE TITLE
Show aggregated fingerprint stats on the details page for the whole time range

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#87192]
This issue tracks updating our statement fingerprint details view with text showing the aggregated execution statistics based on the whole time range. 

In 22.1, we've enhanced the UI with fingerprint level hourly trends for the most common execution statistics. We've received feedback that users would like to see not only the hourly trend but also the overall statistics across the entire selected time range. 

This would be similar to what we had before on our Execution stats tab but for the most common execution stats. 

Jira issue: CRDB-19205

Epic CRDB-20388

**Comment by maryliag** [comment]
cc @dongniwang we will need designs for this
