### ISSUE TITLE
Cockroach CLI commands not using default location for --certs-dir

### ISSUE THREAD

**Issue by smcvey** [cockroachdb/cockroach#87191]
**Describe the problem**

During testing of the new 22.2.0-alpha.1 build.  It no longer finds my certificates in the default location of `$HOME/.cockroach-certs` when I fail to pass a `--certs-dir` flag.

**To Reproduce**

Have certificates in `$HOME/.cockroach-certs`, in mine I have `ca.crt`, `client.root.crt`, `client.root.key`, `node.crt` and `node.key` - ie the usual suspects.

Attempt to start a new cockroach instance/cluster with this command:

```
/home/vagrant/bin/cockroach start  --advertise-addr=172.28.128.21 --join=172.28.128.21
```

I get this:

```
[vagrant@node-1 ~]$ /home/vagrant/bin/cockroach start  --advertise-addr=172.28.128.21 --join=172.28.128.21
*
* ERROR: ERROR: cannot load certificates.
* Check your certificate settings, set --certs-dir, or use --insecure for insecure clusters.
* 
* failed to start server: problem using security settings: no certificates found; does certs dir exist?
*
ERROR: cannot load certificates.
Check your certificate settings, set --certs-dir, or use --insecure for insecure clusters.

failed to start server: problem using security settings: no certificates found; does certs dir exist?
Failed running "start"
```

Swapping the new binary out for the previous GA release works as expected.  I have no `~/.postgresql`.

Other CLI commands also break in the same way, such as `cockroach sql`, `cockroach init` etc.

**Expected behavior**
Normally, without the `--certs-dir` flag, it finds all the necessary certificates in `$HOME/.cockroach-certs` but now it doesn't. 

Jira issue: CRDB-19204

**Comment by rafiss** [comment]
I'm investigating if this is accidental fallout from https://github.com/cockroachdb/cockroach/pull/81943

**Comment by rafiss** [comment]
This is fallout from #82020

Previously, we would expand the `${HOME}` environment variable (which is part of the default certs dir) here: https://github.com/cockroachdb/cockroach/blob/760a8253ae6478d69da0330133e3efec8e950e4e/pkg/security/certificate_manager.go#L264

The current code does not do that. cc @knz

**Comment by smcvey** [comment]
This also affects v22.2.0-alpha.2.
