### ISSUE TITLE
Insights table add avg time based on fingerprint to statement and transaction overview tables

### ISSUE THREAD

**Issue by j82w** [cockroachdb/cockroach#87190]
The problem is when a user visits the insights table gets a list of statements or transactions there is no easy way to determine if this is a transient issue that is expected from a distributed system or is there a problem with the query. The first scenario usually requires an infrastructure team to investigate, and root cause. The second option usually points to an application issue where the query needs to be optimized or an index added. To help give insight to which is the root problem a column should be added to show the stats for the average run time for that fingerprint. 

Jira issue: CRDB-19203

Epic CRDB-20388

**Comment by maryliag** [comment]
No longer a priority
