### ISSUE TITLE
Check output data from `schema_only` & `verify_backup_table_data` restores

### ISSUE THREAD

**Issue by kathancox** [cockroachdb/cockroach#87221]
**Describe the problem**

Noticed some differences in the `estimated_row_count` of tables in a restored database between `schema_only` restores and `verify_backup_table_data` restores. There are possibly some other ux nuances here around the respective output that we could check.

**To Reproduce**

1. Create a full database backup to s3 storage. 
2. Dropped the database from the cluster.
3. Ran the following:
`RESTORE DATABASE movr FROM LATEST IN "s3://my-bucket" WITH schema_only;`
Received the following output, after the restore ran successfully:
```
        job_id       |  status   | fraction_completed | rows | index_entries | bytes
---------------------+-----------+--------------------+------+---------------+--------
  792659534950957057 | succeeded |                  1 |    0 |             0 |     0
(1 row)
```
This seems expected, no rows were restore since this was `schema_only`. 
4. Ran a show tables statement in the movr database, and received:
```
  schema_name |         table_name         | type  | owner | estimated_row_count | locality
--------------+----------------------------+-------+-------+---------------------+-----------
  public      | promo_codes                | table | root  |                1014 | NULL
  public      | rides                      | table | root  |                 631 | NULL
  public      | user_promo_codes           | table | root  |                  43 | NULL
  public      | users                      | table | root  |                 161 | NULL
  public      | vehicle_location_histories | table | root  |                4368 | NULL
  public      | vehicles                   | table | root  |                  48 | NULL
(6 rows)
```
Seeing the `estimated_row_count` with data was a little unexpected, but assumed this was read from the schema, maybe?
5. Dropped the database that the schema only restore had restored.
6. Then, I ran `RESTORE DATABASE movr FROM LATEST IN "s3://my-bucket" WITH schema_only, verify_backup_table_data; `
Received the following output, after the restore ran successfully:
```
        job_id       |  status   | fraction_completed | rows  | index_entries | bytes
---------------------+-----------+--------------------+-------+---------------+--------
  792661355235278849 | succeeded |                  1 | 14169 |          1978 |     0
(1 row)
```
This time rows were present in this output, which makes sense (I think) since this restore type is reading the SSTs.
7. Ran a show tables statement in the movr database, and received:
```
  schema_name |         table_name         | type  | owner | estimated_row_count | locality
--------------+----------------------------+-------+-------+---------------------+-----------
  public      | promo_codes                | table | root  |                   0 | NULL
  public      | rides                      | table | root  |                   0 | NULL
  public      | user_promo_codes           | table | root  |                   0 | NULL
  public      | users                      | table | root  |                   0 | NULL
  public      | vehicle_location_histories | table | root  |                   0 | NULL
  public      | vehicles                   | table | root  |                   0 | NULL
(6 rows)
```
The empty `estimated_row_count` here was **unexpected** for this restore type. Given the initial output had a row count and that the `schema_only` restore type returned and `estimated_row_count`, this seems to be missing here? 

**Expected behavior**
Consistency in the output between the two restore types, so there is a clear how the user can interpret this output. Perhaps `estimated_row_count` is meant to be present in both restore types. If so, should `rows` also be in the initial output after a `schema_only` restore?

**Environment:**
 - CockroachDB version v22.2.0-alpha.1
- roachprod cluster

Jira issue: CRDB-19219

**Comment by msbutler** [comment]
This is a fun bug. schema_only restore is naively inserting the stats from the backup manifest into the restored cluster, leading to the the incorrect estimated_row_count. Once the table's stats refresh, the misleading count goes away. 

I'll file a PR to prevent stats insertion during schema only restore.

**Comment by kathancox** [comment]
@msbutler So the end goal is that `schema_only` should have `estimated_row_count` `0`? Just checking and then I can finish off the docs PR.

**Comment by msbutler** [comment]
that's correct!
