### ISSUE TITLE
sql: provide a mode to autocommit an open transaction on DDLs

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#87236]
**Is your feature request related to a problem? Please describe.**
Cockroach supports online schema changes, which are cool, but are not perfectly compatible with the transactional schema changes offered by postgres (TODO: associate some issues). Not only are they not compatible in that some side-effects, like adding a new column, do not become visible until after the transaction, but also there are limitations around what can be done in a transaction (https://github.com/cockroachdb/cockroach/issues/49351).

**Describe the solution you'd like**
If you're willing to give up on actually being able to roll back, then just not using a transaction is likely to provide the semantics folks want in many cases. In some cases, we've suggested as much to folks and they've changed their applications. Sometimes changing an application is hard.

It turns out that MySQL, a database which does not support transactional DDL, just implicitly commits any open transaction upon the execution of such a statement (see https://dev.mysql.com/doc/refman/5.7/en/implicit-commit.html).

This issue proposes: 
1) Add a session variable such that DDLs lead to impliclty committing any open transaction
2) Allow COMMIT to executed outside of an open transaction without an error (#87233)

**Describe alternatives you've considered**

We should support transactional schema changes, and we will, but it'll take a while to get there.

**Additional context**

This should help unblock https://github.com/grafana/grafana/issues/8900.

Jira issue: CRDB-19226

Epic CRDB-34097

**Comment by ajwerner** [comment]
@bdarnell in light of your strong feelings in https://github.com/cockroachdb/cockroach/issues/54954, do you have strong feelings about this proposal? It would be totally opt-in.

**Comment by bdarnell** [comment]
I don't love changing our non-postgres-compatible behavior and replacing it with a *different* non-postgres-compatible behavior, but if it's opt-in it shouldn't be too bad. And following the mysql behavior is likely to lead to the fewest surprises (as compared to other possible solutions, like running the DDL outside of the current transaction without committing it). 

Instead of allowing COMMIT to be run outside of a transaction, could we make the DDL equivalent to `COMMIT; DDL; BEGIN;`?

**Comment by postamar** [comment]
This seems like a low-hanging fruit.

**Comment by ishworg** [comment]
Any update on the low-hanging fruit ? thanks.
