### ISSUE TITLE
sql: dropping constraint drops unrelated index instead

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#8724]
```
root@:26257> CREATE TABLE t (id int primary key, email STRING, INDEX email (email), CONSTRAINT email CHECK (STRPOS(email, '@') > 0));
CREATE TABLE
root@:26257> SHOW CONSTRAINTS FROM t;
+-------+---------+-------------+-----------+------------------------+
| Table |  Name   |    Type     | Column(s) |        Details         |
+-------+---------+-------------+-----------+------------------------+
| t     | email   | CHECK       | NULL      | STRPOS(email, '@') > 0 |
| t     | primary | PRIMARY KEY | [id]      | NULL                   |
+-------+---------+-------------+-----------+------------------------+
root@:26257> ALTER TABLE t DROP CONSTRAINT email;
ALTER TABLE
root@:26257> SHOW CREATE TABLE t;
+-------+------------------------------------------------------+
| Table |                     CreateTable                      |
+-------+------------------------------------------------------+
| t     | CREATE TABLE t (␤                                    |
|       |     id INT NOT NULL,␤                                |
|       |     email STRING NULL,␤                              |
|       |     CONSTRAINT "primary" PRIMARY KEY (id),␤          |
|       |     FAMILY "primary" (id, email),␤                   |
|       |     CONSTRAINT email CHECK (STRPOS(email, '@') > 0)␤ |
|       | )                                                    |
+-------+------------------------------------------------------+
```

**Comment by dt** [comment]
This is because `alterTableNode`'s handling of `AlterTableDropConstraint` is jus to lookup and drop the index with the provided name -- this is probably only correct for unique constraints though.

**Comment by dt** [comment]
An index could easily be critical to query performance an application is relying on, so dropping it when the user drops a just a constraint is somewhat scary. Since we can't (currently) swap an index in place from unique to non-unique, I think the safest behavior is just to refuse to drop the constant and suggest explicitly dropping the index if that is actually desired.

**Comment by dt** [comment]
cc @vivekmenezes for thoughts

**Comment by vivekmenezes** [comment]
I think it's time we actually label the index as belonging to a constraint.
The unique constraint is implemented using an index and we hide that
implementation detail. Whether we can use a unique constraint to serve a
query is another question. Perhaps we should not allow that making index
creation a requirement.

**Comment by dt** [comment]
#8747 fixes the "drop *unrelated* index" by first resolving the constraint name to a actual constraint, _then_ handling it based on the type of constraint (and added support for `CHECK` or `FOREIGN KEY` constraints).

While I was there though, I also removed support for dropping a UNIQUE constraint -- instead returning an error suggesting explicitly dropping the unique index instead. Since we can't drop one without dropping the other, I think making the operator explicitly drop the index is safest. If we did it silently on their behalf, queries relying on that index may suddenly perform very differently.

As an common example, a `users` table that has a unique index on `email`, and does lookups by `email` for e.g. login. After adding soft-delete, you want fix a "deleted" account preventing signup with that email. You figure you'll drop the DB's constraint and enforce "one *active* account per email" business logic in your app instead. If dropping the constraint unexpectedly drops the index, you could be in for a bad day when every login starts doing a table scan.

**Comment by vivekmenezes** [comment]
I can take a look at that pr when I return. I think we should document that
a unique constraint and a unique index are one and the same. Is that
accurate?
