### ISSUE TITLE
raft: re-work leader self-ack mechanism

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#87264]
**Describe the problem**

The `raft.Ready` contract has some deficiencies that have caused trouble upstream, and which are in our interest to help resolve.

https://github.com/etcd-io/etcd/issues/14370#issuecomment-1234290101

I believe we're not affected, since we are aware of this behavior and handle it: https://github.com/cockroachdb/cockroach/blob/d06405992f63ec553f804706e69ec1848bd77efb/pkg/kv/kvserver/apply/task.go#L182-L193

**To Reproduce**

See the thread above.

**Expected behavior**

Make the single-node case look like any other case. Don't emit `Ready` with `.CommittedEntries` that are contingent on handling `.Entries`. This reduces single-node throughput, but the performance could be clawed back on our end by special casing single nodes (which we probably don't need to, since if performance is a goal we can more completely elide raft).

In practice, this means shepherding https://github.com/etcd-io/etcd/pull/14411.

Also revive https://github.com/etcd-io/etcd/pull/10861, which among other things points out the above problem.

When thinking about issues such as these:

https://github.com/cockroachdb/cockroach/issues/38322
https://github.com/cockroachdb/cockroach/issues/17500#issuecomment-425689048

it is important to have all of the invariants properly documented and discoverable.

Jira issue: CRDB-19244

**Comment by tbg** [comment]
Draft PR https://github.com/etcd-io/etcd/pull/14413

**Comment by tbg** [comment]
Upstream is now ready for review: https://github.com/etcd-io/etcd/pull/14413

**Comment by nvanbenschoten** [comment]
Now that https://github.com/etcd-io/etcd/pull/14413 has landed, what's next for this issue? Pull in the dependency? Should we also remove the `maxIndex` param and handling from `Task.AckCommittedEntriesBeforeApplication`?

**Comment by tbg** [comment]
See checklist on https://github.com/cockroachdb/cockroach/pull/88985
