### ISSUE TITLE
logictest/legacy-schema-changer: investigate unexpected failures/hangs

### ISSUE THREAD

**Issue by fqazi** [cockroachdb/cockroach#87266]
When enabling the legacy schema changer again inside the logic test we ran into the following bugs:

- [x] sequences_regclass has a hang during drop database with the legacy schema changer
- [ ]  fk test cannot drop the database due to an adding table grandchild80828. This is caused by the table being left in an adding state and the cascaded drop database code failing inside filterDescriptorState. This is an existing bug, so we can defer this is likely an existing bug, which should be safe to defer to a future release.

Jira issue: CRDB-19245

**Comment by ajwerner** [comment]
Some context: https://github.com/cockroachdb/cockroach/blob/4d6e876621e6e57ec35ea12c5486d8d688a5c84d/pkg/sql/catalog/descs/object.go#L74-L84

**Comment by postamar** [comment]
I'm doing things with FilterDescriptorState that I hope might help fix this: https://github.com/cockroachdb/cockroach/pull/87265

**Comment by postamar** [comment]
I looked into this. Let's leave things as they are.
