### ISSUE TITLE
sql: support mutations within UDFs

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#87289]
We do not currently allow mutations (`INSERT`, `UPDATE`, `UPSERT`, `DELETE`) within user-defined function bodies. We should lift this restriction.

Note that #70731 may prevent us from allowing UDFs to mutate the same table twice and/or mutating a table also mutated by the calling statement.

Epic: CRDB-25388

**Comment by rharding6373** [comment]
Before closing this issue, we should add tests that cover the following (and open new issues to fix support if necessary):

- [ ] UDFs with mutations in CTEs, including multiple mutations.
- [ ] UDFs with mutations on tables with foreign key constraints.

**Comment by mgartner** [comment]
Before closing this, we also need to revisit https://github.com/cockroachdb/cockroach/pull/103920 to make sure we correctly handle FK cascades and prevent possible index corruption.

**Comment by rharding6373** [comment]
This feature is now complete.

**Comment by kylepl** [comment]
Just to confirm - this will allow INSERT statements within UDFs? And is the expectation that this will be in release v23.2?

**Comment by rharding6373** [comment]
Yes, mutations (INSERT, UPDATE, UPSERT, DELETE) will be available in UDFs in v23.2.
