### ISSUE TITLE
changefeedccl: changefeeds fail permanently on "failed to send RPC: sending to all replicas failed"

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#87300]
Errors of the form `failed to send RPC: sending to all replicas failed; last error: failed to connect` (or something more structured) should be marked as retryable at the changefeed level.

This may be effectively a regression of https://github.com/cockroachdb/cockroach/issues/72616 due to the error string shifting slightly (due to a grpc library update? or due to the low-level error happening at a different spot in the flow?).

Jira issue: CRDB-19261

Epic CDC

Epic https://cockroachlabs.atlassian.net/browse/CRDB-7581

Epic https://cockroachlabs.atlassian.net/browse/CRDB-7581

Epic CRDB-7581

**Comment by miretskiy** [comment]
Do you have logs/reports of this happening again?
