### ISSUE TITLE
backupccl: teach makeSimpleImportSpans to exclude backup data on spans that were later reintroduced

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#87305]
Currently RESTORE cannot properly handle restoring a table that had a non-mvcc rollback, without adding some logic to makeSimpleImportSpans.

Consider the following timeline:
1. Begin IMPORT INTO on existing table foo, ingest some data
2. Backup foo
3. Rollback IMPORT via clearRange
4. Incremental backup of foo, with a full reintroduction of foo’s span
5. RESTORE foo: the imported data leaks into the restore
 - See test [here](https://github.com/msbutler/cockroach/commit/09d65792297e72ef754bcb602eeef353b9b29d24). grep for “this is bad”
 
This occurs because 1) `makeSimpleImportSpans` naively includes the backup file with the imported data as part of foo's restoreSpanEntry and 2) the backups have MVCC delete history related to the rollback. This was never a problem in previous releases because offline importing data were not backed up until the import succeeded.

To address this, `makeSimpleImportSpan` needs to exclude backup files for a span that was later reintroduced due to a non-mvcc bulk op. 

Jira issue: CRDB-19262

**Comment by adityamaru** [comment]
Is this a release blocker on 22.1? That seems like a mistake, should it be 22.2 instead?

**Comment by msbutler** [comment]
Well, it turns out this bug is in 22.1, and most likely in earlier releases, but only for cluster backup chains, as they have been backing up offline tables I think for as long they have been around.

I confirmed that this bug is on 22.1 by executing the sql commands in my [data driven test](https://github.com/msbutler/cockroach/commit/09d65792297e72ef754bcb602eeef353b9b29d24) on a 22.1 roachprod cluster. The bug manifests in the following ways:
- If table foo is empty before the cancelled import begins, the cancelled imported data appears on the restored cluster/database/table
- If table foofoo is non-empty, foofoo does not seem to be available on the restored cluster, even if the import was cancelled before the incremental backup was taken. I'm not sure why yet. 

I have not confirmed this bug is on 21.2 because it's harder to reproduce without the `jobs.debug.pausepoints` cluster setting. But the source code indicates that cluster backups will back up offline data, so I bet this bug is on there too.

**Comment by msbutler** [comment]
verified this bug is on 21.2.15 using the following cmds on a roachprod cluster. Note that descriptor resolution for cluster backups [do not filter](https://github.com/cockroachdb/cockroach/blob/a4b0f48627471fafa8f5a261f6c9fd9eb586215a/pkg/ccl/backupccl/targets.go#L310) offline tables (just dropped ones), likely for job resolution on the restored cluster. 

```
use bank;
CREATE TABLE bank2 (id INT8 NOT NULL, balance INT8 NULL, payload STRING NULL);
EXPORT INTO CSV 'gs://dt-backup-tests/michael-rangkey?AUTH=implicit' FROM TABLE bank; 
IMPORT INTO bank2 (id, balance,payload) CSV DATA ('gs://dt-backup-tests/michael-rangkey/export*-n*.0.csv?AUTH=implicit') WITH detached;

# immediately pause the import
PAUSE JOB [import_job]

# Run the full backup
BACKUP INTO 'gs://dt-backup-tests/michael-rangkey?AUTH=implicit';

# cancel the import 
PAUSE JOB [import_job]

# Run an incremental backup
BACKUP INTO LATEST IN 'gs://dt-backup-tests/michael-rangkey?AUTH=implicit';

USE defaultdb;
DROP bank;

# Restore to new database 
RESTORE DATABASE bank FROM LATEST IN 'gs://dt-backup-tests/michael-rangkey?AUTH=implicit';

# See the rolled back imported data
SELECT count(*) FROM bank.bank2;
```

**Comment by msbutler** [comment]
on 22.1, I found a slightly different bug which i'll file an issue for once i get to the root cause. 

On #87873, I tried to fix the cluster backup bug described above on 22.1 by excluding offline tables. For backups _without_ revision history this works, but for backups _with_ revision history (cluster/database backups), I found another surprise: the first incremental backup with revision history will reintroduce the clear ranged data and will restore. This behavior isn't apparent on master. I have to find a root cause, but I suspect the bug is in kv server.

**Comment by msbutler** [comment]
fixed by
master: https://github.com/cockroachdb/cockroach/pull/87312
22.2: https://github.com/cockroachdb/cockroach/pull/89102
22.1: https://github.com/cockroachdb/cockroach/pull/88488
21.2: https://github.com/cockroachdb/cockroach/pull/89019
