### ISSUE TITLE
kv: `TestSnapshotsToDrainingNodes` spins on "retryable" snapshot error for 45s

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#87337]
In #77951, we saw that `TestSnapshotsToDrainingNodes` was one of the slowest tests in `pkg/kv/kvserver`. I saw the same thing in a recent CI run, where the test was so slow that it timed out and flaked.

Digging in, I noticed that the "store is draining" errors are marked with the `errMarkSnapshotError` marker. This causes it to be classified as a retryable error by `IsRetriableReplicationChangeError`. As a result, when `TestCluster.changeReplicas` sees this error, it spins in `SucceedsSoonError` for 45s (`DefaultSucceedsSoonDuration`):

https://github.com/cockroachdb/cockroach/blob/49b650149872dbf82302fd9d8495a4d59f034aa4/pkg/testutils/testcluster/testcluster.go#L736-L759

I don't quite know what the right solution is here. We should look into this and find out. Is it ok for the "store is draining" error to be considered retryable? Do we need a form of permanent snapshot errors instead of considering all to be transient? Could this cause real consequences elsewhere (e.g. in the `replicateQueue`, where we consult `isSnapshotError`). If not, does the test need to be adjusted to avoid spinning?

Jira issue: CRDB-19280

**Comment by aayushshah15** [comment]
This is supposed to be fixed by https://github.com/cockroachdb/cockroach/pull/75248. @tbg any chance you might be able to push that over the finish line soon?

**Comment by tbg** [comment]
Urgh, yes, moved it into the Sep milestone and should get to it. Thanks for the heads up.
