### ISSUE TITLE
align zone constraint reporting with allocator behaviour

### ISSUE THREAD

**Issue by aliher1911** [cockroachdb/cockroach#87344]
When allocator decides which stores are eligible to host replica it ensures that all constraints are satisfied.
The report however does the opposite, it checks that number of replicas matching constraint is at least as many as requested (either all replicas, or explicit number of them).
If we want to constraint all replicas, this approach should work as expected, but if we require certain number of replicas to match a constraint, it is possible that single replica will match multiple ones and thus hide the fact that other replicas don't match constraint.

See comment: https://github.com/cockroachdb/cockroach/pull/84727#pullrequestreview-1094139673

Jira issue: CRDB-19284

**Comment by maryliag** [comment]
Replication report is being deprecated on 23.1. This issue will no longer be valid.
