### ISSUE TITLE
bazel: (regression) error in `dev generate bazel --mirror`

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#87369]
This did not fail two weeks ago, and now does:

```
$ ./dev generate bazel --mirror
  /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/WORKSPACE:267:13: in <toplevel>
  /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/build_bazel_rules_nodejs/index.bzl:83:18: in yarn_install
Repository rule yarn_install defined at:
  /data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:977:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'npm_e2e_tests':
   Traceback (most recent call last):
        File "/data/home/kena/.cache/bazel/_bazel_kena/9b9f53b7334495d6a871cbb472c466bb/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 968, column 13, in _yarn_install_impl
                fail("yarn_install failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: yarn_install failed: yarn install v1.22.11
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
 (warning Waiting for the other yarn instance to finish (74944)
warning Waiting for the other yarn instance to finish (74942)
warning " > @typescript-eslint/eslint-plugin@4.29.1" has unmet peer dependency "@typescript-eslint/parser@^4.0.0".
warning " > @cockroachlabs/eslint-config@0.1.11" has incorrect peer dependency "@typescript-eslint/eslint-plugin@^2.6.1".
warning " > @cockroachlabs/eslint-config@0.1.11" has incorrect peer dependency "eslint-plugin-react-hooks@^2.3.0".
warning "@cockroachlabs/eslint-config > @typescript-eslint/parser@2.34.0" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
error /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/ui/workspaces/e2e-tests/node_modules/cypress: Command failed.
Exit code: 1
Command: node index.js --exec install
Arguments:
Directory: /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/ui/workspaces/e2e-tests/node_modules/cypress
Output:
Platform: "freebsd" is not supported.
)
```

cc @rickystewart 

Jira issue: CRDB-19303
Epic CRDB-17171

**Comment by rickystewart** [comment]
The error seems to be "in yarn" rather than in the actual Bazel build, so I don't think this is a Bazel issue.

**Comment by rickystewart** [comment]
@sjbarag Do you have any insight about what is throwing the `Platform: "freebsd" is not supported.` error here?

**Comment by sjbarag** [comment]
(Broader discussion follows)

Looks like that's thrown from a postinstall script that installs the Cypress binary (which doesn't appear to be included as part of : https://github.com/cypress-io/cypress/blob/b031803cfb31594054e9797719e2dd3365d43fa1/cli/lib/tasks/state.js#L10-L44 . Looks like we can skip that install step [with an environment variable](https://docs.cypress.io/guides/references/advanced-installation#Install-binary) but I'm not sure what impact that'll have on our (eventual) CI integration. @knz to get you unblocked, could you try adding `env = { "CYPRESS_INSTALL_BINARY": "0" }` to the `yarn_install` rule on line 267? I don't have a freebsd box available :/

https://github.com/cockroachdb/cockroach/blob/af1a53a6f1fb39c40ba5435b0bc08e4b7f29a4f1/WORKSPACE#L267-L280

-----

Lack of freebsd support seems to be called out in https://docs.cypress.io/guides/getting-started/installing-cypress#Operating-System , which I completely skipped over when setting Cypress back up.  Popular alternatives to Cypress also don't appear to support FreeBSD (namely [webdriver.io](https://webdriver.io) and [https://playwright.dev](https://playwright.dev). It's a bit surprising, but freebsd appears quite under-represented in the JS community.

If skipping installation doesn't solve anything the only thing I can think of to resolve this is to revert https://github.com/cockroachdb/cockroach/pull/85095 , but that'll be a pretty big loss :/

**Comment by knz** [comment]
FWIW, some of these things get supported by the freebsd team even if it's not mentioned on their web site. For example I see a `rubygem-webdrivers-5.0.0` package I can install.

**Comment by knz** [comment]
As to your suggestion:

```
ERROR: /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/WORKSPACE:267:13: //external:npm_e2e_tests: no such attribute 'env' in 'yarn_install' rule
```

Are you sugre about the env var setting?

**Comment by knz** [comment]
fwiw if I set CYPRESS_INSTALL_BINARY in my shell it makes the error disappear. I can use that as workaround for now.

**Comment by sjbarag** [comment]
> As to your suggestion:
> 
> ```
> ERROR: /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/WORKSPACE:267:13: //external:npm_e2e_tests: no such attribute 'env' in 'yarn_install' rule
> ```
> 
> Are you sugre about the env var setting?

Good call — turns out it's called "environment" in `yarn_install`, unlike every other standard Bazel rule: https://bazelbuild.github.io/rules_nodejs/Built-ins.html#yarn_install-environment

**Comment by knz** [comment]
Is it possible to have our WORKSPACE rules conditionally set the env var depending on the OS detected?

**Comment by sjbarag** [comment]
> Is it possible to have our WORKSPACE rules conditionally set the env var depending on the OS detected?

Doesn't look like it's possible inline in the `WORKSPACE` file, but it _might_ be possible with a Starlark macro (a Python-like function) that returns a dictionary.  The rules for what's possible within a `WORKSPACE` file still escape me.

**Comment by knz** [comment]
Ok let's investigate this a bit later when there's fewer high-priority issues around. I'm OK with the workaround for now.
