### ISSUE TITLE
acceptance: allocator tests timing out in WaitForRebalance

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#8738]
Allocator tests are failing due to `pq: context deadline exceeded` errors:

https://teamcity.cockroachdb.com/viewLog.html?buildId=13592&buildTypeId=Cockroach_AllocatorTest1to310g&tab=buildLog#_focus=1147
https://teamcity.cockroachdb.com/viewLog.html?buildId=13291&buildTypeId=Cockroach_AllocatorTest3to510g&tab=buildLog#_focus=2708

This seems like a relatively new issue -- I don't remember seeing these timeouts in our allocator tests more than a week ago. It looks like the timeout is happening in `WaitForRebalance`, which queries the DB looking for 3-minute windows of rebalancer inactivity.

cc @cockroachdb/stability

**Comment by tamird** [comment]
@cuongdo are we still seeing this?

**Comment by cuongdo** [comment]
I don't know. We've had a lot of Terraform 0.7.0+ upgrade fallout. We
should know after my most recent PR goes out.

**Comment by cuongdo** [comment]
haven't seen this in a while, so closing
