### ISSUE TITLE
sql: SHOW should do its work in Start/Next not its constructor

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#8739]
Currently the various SHOW nodes do their work in their constructor, including populating a valuesNode. As highlighted in #8691 it is arguably undesirable to have user-dependent memory growth in the prepare phase. This can be solved by moving the work to the Start/Next methods instead.

**Comment by knz** [comment]
Once this is fixed the monitor initialization in Executor.Prepare can go away.

**Comment by mjibson** [comment]
This may also involve removing the Show nodes from `prepare` in plan.go.

**Comment by mjibson** [comment]
@knz Is there monitor initialization in Executor.Prepare? I can't see any evidence of that.

**Comment by knz** [comment]
Probably not for Prepare. I think I  did make some efforts to ensure that there were no calls to the monitor in the planNode constructors, did you find some exception?

In the follow-up PR #9259 the initialization is moved to the session constructor, then Prepare() is properly covered.

**Comment by knz** [comment]
Fixed by #10013.
