### ISSUE TITLE
gcjob: end-to-end test for tenant schema GC

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#87404]
Over in #87178, we found that the schema GC job would never complete in a tenant due to #87365. We should have an end-to-end test that makes sure tenant schema GC works.

CC: @ajwerner 

Jira issue: CRDB-19330

Epic CRDB-2624

**Comment by erikgrinaker** [comment]
Yeah, that sounds right -- I'm not sure how this is all wired up.

**Comment by ajwerner** [comment]
https://github.com/cockroachdb/cockroach/issues/88228 tracks providing the relevant testing infra. Closing this.
