### ISSUE TITLE
bazel: bazel build did not generate libgeos files- cockroach version 22.1.5

### ISSUE THREAD

**Issue by machaleb** [cockroachdb/cockroach#87405]
**Describe the problem**

I am trying to build cockroachdb version v22.1.5 using bazel. it generates cockroachdb binary but not generating `libgeos.so` and `libgeos_c.so` files

**To Reproduce**

If possible, provide steps to reproduce the behavior:
1. clone the code : `git clone https://github.com/cockroachdb/cockroach`
2. checkout for 22.1.5 : `git checkout v22.1.5`
3. update the submodules `git submodule update --init --recursive`
4. run bazel build: `bazel build pkg/cmd/cockroach --config=with_ui`
**Expected behavior**
It should generate `libgeos.so` and `libgeos_c.so` file along with `cockroach` binary

Jira issue: CRDB-19331

**Comment by rickystewart** [comment]
Hi @machaleb -- building the binary alone will not also cause `geos` to be built. You can build `geos` with `bazel build c-deps:libgeos`. This may pull a prebuilt version of the library but you can force building your own version with the `--config force_build_cdeps` flag. Let me know if there are any other questions.

**Comment by machaleb** [comment]
Thanks @rickystewart for the reply. I am able to build `geos` using `bazel build c-deps:libgeos`
Also I have seen when builinding cockroachdb on s390x `bazel build pkg/cmd/cockroach --config=with_ui` gives `Build Tag:        unkonwn` . is there anything that I am missing in build step?

**Comment by rickystewart** [comment]
Hi @machaleb -- try the command line arguments `--stamp --workspace_status_command=./build/bazelutil/stamp.sh`. By default without arguments the `stamp.sh` script will infer some values for build tag/commit ID/etc, but you can check out the script to see the arguments it takes to customize those values.

**Comment by machaleb** [comment]
Thank you. It worked
