### ISSUE TITLE
sql: `SELECT` with no target parameter errors without a list

### ISSUE THREAD

**Issue by danieljharvey** [cockroachdb/cockroach#87428]
**Describe the problem**

In Postgres, `SELECT FROM author` syntax is a successful query:

```sql
postgres=# select from author;
--
(3 rows)
```

However, in CockroachDB this is a syntax error:

```sql
cockroach=> select from author;
ERROR:  at or near "from": syntax error
DETAIL:  source SQL:
select from author
       ^
HINT:  try \h SELECT
```

**Expected behavior**

Would expect CockroachDB to accept `SELECT FROM author` like Postgres does.

**Additional context**

Hasura Graphql Engine uses queries like these which no longer work because of this:

```sql
SELECT json_build_object('aggregate', json_build_object('count', COUNT(*) ) ) AS "root" FROM
(SELECT /* note no select list */
  FROM
  (SELECT *
   FROM "public"."author"
   WHERE ('true') ) AS "_root.base" ) AS "_root"
```

Jira issue: CRDB-19344

**Comment by ZhouXing19** [comment]
Thanks for filing this issue! We already have #83255 tracking the same problem, so I'll close this and inform the team of Hasura's need.
