### ISSUE TITLE
kv: receiver-side raft request queue size limit out of sync with RaftMaxInflightMsgs

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#87465]
`etcd/raft` is configured with a maximum outstanding (msgapp) message count configuration called `RaftMaxInflightMsgs`. CockroachDB defaults this value to 128 per range, but allows it to be configured with the `COCKROACH_RAFT_MAX_INFLIGHT_MSGS` env var. If this limit is exceeded, new MsgApps sent to a given peer will be delayed by the leader.

CockroachDB also enforces a receiver-side `replicaRequestQueueSize` limit. This value is hardcoded to 100. If this limit is exceeded, messages will be dropped. We expect the leader to retransmit them eventually.

https://github.com/cockroachdb/cockroach/blob/27ad53af93b341e7fd9b98e251567211fe860b70/pkg/kv/kvserver/store_raft.go#L308-L315

If these values aren't in sync, the raft leader can overflow the receiver's queue, forcing redundant transmission. Worse, it seems possible that if the receiver size limit is significantly below the sender's size limit, important MsgApps (the one carrying the next entry in the log to be appended) may be starved by later MsgApps which will clog up the receiver queue without being useful.

These limits should be rethought. Should `replicaRequestQueueSize` simply be replaced by `s.cfg.RaftMaxInflightMsgs`? Should we leave room for other messages like heartbeats?

`raft.rcvd.dropped` can tell us whether this is a problem in real clusters, as can the new logging added in c1cd955.

Jira issue: CRDB-19357

**Comment by erikgrinaker** [comment]
Nice find, thanks. We'll have a look.

**Comment by erikgrinaker** [comment]
>Should replicaRequestQueueSize simply be replaced by s.cfg.RaftMaxInflightMsgs?

Let's start with this @pavelkalinnikov.
