### ISSUE TITLE
ui: Log spam when LiveReload is not installed

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#8749]
Lots of log spam which appears to be related to the addition of LiveReload:

![screen shot 2016-08-22 at 6 45 50 pm](https://cloud.githubusercontent.com/assets/6969858/17874304/c813352e-6898-11e6-9ee9-72d38a6ec725.png)

I do not have LiveReload installed.

**Comment by tamird** [comment]
It's not really clear to me how to fix this (maybe it's not possible?). On the upside, you don't need anything installed, just run `make -C ui livereload` to run the server process.

**Comment by maxlang** [comment]
Also, I should note that this is only in debug mode.

**Comment by maxlang** [comment]
For now, if this is really bugging you, I recommend filtering out those messages from your console:
<img width="393" alt="screen shot 2016-08-23 at 3 03 25 am" src="https://cloud.githubusercontent.com/assets/3691886/17883101/8da41cfa-68de-11e6-835f-09b8f4e38331.png">

**Comment by dianasaur323** [comment]
@mrtracy is this still an ongoing issue?

**Comment by mrtracy** [comment]
No, closing.
