### ISSUE TITLE
Remove Attrs from RangeDescriptor.Replicas

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#875]
Storing attributes in the RangeDescriptor is redundant and wastes space in the widely-cached range descriptors. We could remove attributes from RangeDescriptor and re-query them from gossip as needed.

**Comment by tamird** [comment]
Fixed in https://github.com/cockroachdb/cockroach/commit/2d5b88a2029a992a697dc633637d4ad1c9602486.
