### ISSUE TITLE
ci: failure due to forgetting to generate docs is not clear

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#87505]
Consider this PR: https://github.com/cockroachdb/cockroach/pull/87318

Here is a Github CI run that failed because I forgot to generate docs after changing a builtin function: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/6328186?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

<img width="997" alt="image" src="https://user-images.githubusercontent.com/1320573/188926688-597abb49-3d97-4453-ac9d-715e1d1dc287.png">

It's very clear what file I forgot to generate, and what needs to change.

---

Here is the corresponding Bazel CI: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/6366885?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildDeploymentsSection=true

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/1320573/188927224-e662c7e2-ab1e-412e-a67d-28a132f3a5d4.png">

It failed for the same reason, but none of these things that I can click on tell me that there's an issue with the generated docs.

Jira issue: CRDB-19383
Epic CRDB-15060

**Comment by rickystewart** [comment]
Since `5536a1ba0d424da7d89686777728b41612939bf0` this should be improved.
<img width="909" alt="Screen Shot 2022-10-10 at 4 13 39 PM" src="https://user-images.githubusercontent.com/3423966/194953152-a3771645-0081-4ab8-b6b4-2900f5ac030a.png">
