### ISSUE TITLE
tracing: possible regression in the amount of things dropped from the trace

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#87536]
I have statement bundles for the same statement that ran on 22.1.6 and 22.2.0-alpha.2. The statement reads a lot of data, so it is expected that some things are dropped due to constant limits defined in `tracing/tracer.go`. However, the bundle from 22.2.0 has too much stuff that is dropped. It appears as if we started dropping more stuff on 22.2 (I did check that things are propagated correctly when nothing is dropped on a smaller dataset). This can significantly complicate debugging some of the queries, so I'm tagging this as a GA-blocker until this issue is better understood.
[22.1.6.zip](https://github.com/cockroachdb/cockroach/files/9521890/22.1.6.zip)
[22.2.0.zip](https://github.com/cockroachdb/cockroach/files/9521891/22.2.0.zip)

Jira issue: CRDB-19403

**Comment by andreimatei** [comment]
We think what's going on here is a combination of the shape of the trace changing in 22.1 with the introduction of the Streamer, which acts as a parent for a large number of spans, and a change that made trace recordings imported through DistSQL be subject to the 1000 span limit.
In #88414 I'm changing the way the span limit is implemented, which should result in a larger trace being preserved even when some spans need to dropped.

**Comment by andreimatei** [comment]
I'm removing `GA-blocker`; I don't think this change in behavior raises to that level.

**Comment by yuzefovich** [comment]
Another data point where we drop more stuff: consider the bundles attached in #88891. On 22.1.7 the distsql diagram has execution stats for all processors
![Screen Shot 2022-09-28 at 11 39 29 AM](https://user-images.githubusercontent.com/5135385/192862526-4911fe4c-e52d-408c-8a55-1ae662e78e58.png)
but on 22.2.0-beta some processors are missing stats
![Screen Shot 2022-09-28 at 11 39 52 AM](https://user-images.githubusercontent.com/5135385/192862581-0ea492ac-0cde-4fe5-b30d-a86d3d2d2c40.png)
I think the query in question doesn't use the lookup and index joins, so the streamer cannot explain this. We did add more tracing to the apply join present in the query which could be partially to blame. Still, I think we should make some improvements to 22.2.x even if this issue is not a GA-blocker.

**Comment by andreimatei** [comment]
Hmmm I think those execution stats come from structured events, which are not supposed to be dropped by the span limits. This is a query we can reproduce, since it operates on `pg_catalog` data. Let me see if I can figure something out.

**Comment by yuzefovich** [comment]
Ran into a possibly related problem (probably not a regression though).

When running `EXPLAIN ANALYZE (DISTSQL)` of TPCH Q20 some of the execution stats are dropped. This is on current master which includes #89785. Note that with #91117 merged we now use "structured" recording type (rather than verbose) for this (when not collecting bundles). [Diagram](https://cockroachdb.github.io/distsqlplan/decode.html#eJy8V29v27YTfv_7FAcCP9humUjUH1sSEEBu4q5ZHadw3A7FFhiMxTpaZEkhqS1G0Y-1L7BPNuivbcWS66xY39Q68jnynufuePmKxGOAHHQzGo_OZyDmIV0xDGJOPY8zIeDt9PoKRBLHgc84hpBKPwrhl3ej6Qi6XTFPlx7YGi4n0C2cxBtrho4pl6mhRMVinprqqMpYgQpAnF0KxpfvR9D5EnEm5P87vR4MJxeZM_oH9YNHuYbfElXVWeVRPTXhFYhk1Q3mjwkNpS_Xvdx74IfMl2xVBdINquPPYHPB4pCgCuhsK7reZvXejz0qWXGDM7gYzkbQIbZtnKjkRCWdpr0L6G5vg9fQIbBmlHcc53IyG00_DcfweTSc9rJ_uZNUpVSG_ELh5qvcEOaMnUHnfDgZXgw7PbieXoym8OZzITHCKIw8NqErJpDzKyLoFqOYRwsmRMRT09dsw6X3hBwVIz-ME5mabzFaRJwh5yuSvgwYctCM3gVsyqjHuKIijDwmqR9kbkue3WAuPITReRQkq1A4EMwj7jH-wNYYgnm6LUxWd2mGbRhCGN3ENN2tWIN-_0SxiU4QRteJdMAl2NUQRu8_gfRXzAF9YK5EblhEoWRhlqj5mvr3X8USj_4UwBn1HLBVGxummdvv1pKVC7oKV_6b3L6cfjiHBQ0C4YCBMLr6dH4OQrIYFlESSuiyJ6n4oexV_pSN33wzYw_PN1uKhTBa0SdYsVXE10CDIFpQyTwHSHn-HZWLeyYgSmScxmxZNsIoC6E0lYfdfsMotxUiCUmXDDnkG_5-IX-O_LDQkTToGHN_Rfl6V8qiWDLt8tJIf5YlV5O0Esw8tX6MXkS19gvWP6CYmqVri0pEw5aqKvl_jXrpRnF8uiweA5BsFYPniwdIBF2m8cAPklM7Rs7tutR29Sxb8j49N90PbzW77HfZaTeVebKtqGEeWYKWqmI1Y7YuqU72S0oOSFp4VDaeW-TVLEV7QRkOLK2uW3lck256o24buZIwa4nM25HqNkUe2rJH_HdU3Kf1zLii12qZfZHdrH32zri_vC8_qs5qYreP3QF2UyB7YotkS0dNszONG0rB_M9KwTimFIbLJWdLKiOuGLtslO_IcPJ5PrmezScfx-OuS3rPTBlBNx-vuq7xfFHv7aHK6hstVBkHuwYxGxLQNEidLdPQsUaaE9A8hq23fiAZZ1wxd7nK7Q64RjVquTq8Sgctx3Hejq-HM2sfEXpGw3dFoWHVbta8_8LXrP-8-211vnEUPSQx_B75IURhOlqkpTABt1-bOR3HuZlNLyc_7bTLrW5ZjlZ5HWmNcQyOiePCF9IPF1IZ1DO30b_1Qp6s3RPKsf8QVxUXW6_Fs78kclMxqG44wq6OXQO7zaLbLwzG3g0mP7stFKOSfTM475V8a-LGENZEz9tmdsfsqXPAwLo9qGxC0iAoCoMYp0TszESWXb2T3_eEansGIu3UgPd7X89_OQ-ZqmKqewq839LnyGlTG7Pq5U-sfvMgqx6TBjcRl-kUq9ZL5vW-2xfENvRpteDyyCftWXNrje6oOX3KRByFgtUHhb2u1XQ6YN6S5dOGiBK-YB94tMiOyT-vM1xm8JiQ-SrJPy7DfCm94DaYtIL1HTCpg7UjwFodrLeCjfZrG61gsx1stoL77eB-K3jQDh60gq12sNUKttvBdnuSqAey5ECO1ZPs9tv__gkAAP__jOrqUg==).
