### ISSUE TITLE
kv: Raft snapshots required when they should not be

### ISSUE THREAD

**Issue by andrewbaptist** [cockroachdb/cockroach#87553]
**Describe the problem**

Raft snapshots are occasionally sent in healthy systems. They should only be required in the case of failures or slowness of nodes. 

**To Reproduce**

(Note this test is included in the PR)
* Create a cluster with 3 nodes and the raft snapshot queue disabled.
* Create a range on just 1 node. 
* Add a second node as a replica. 
* Have the replicate queue attempt to add the third node (since it doesn't like an even number of replicas)

**Expected behavior**
Most of the time this succeeds with the third node added. Occasionally it will fail. 

Jira issue: CRDB-19406

**Comment by tbg** [comment]
See: https://cockroachlabs.atlassian.net/wiki/spaces/CORE/pages/64749670/Raft+Snapshots+and+why+you+see+them+when+you+oughtn+t

**Comment by andrewbaptist** [comment]
Short gist that covers this issue: https://gist.github.com/b4dc8e7303c6894f14bfc462e0a6169c

**Comment by nvanbenschoten** [comment]
Slack discussion in https://cockroachlabs.slack.com/archives/C0KB9Q03D/p1662659932157679.

**Comment by andrewbaptist** [comment]
Test that will pass once this is addressed. It could be merged with disabled, but probably makes more sense to include as part of the fix to this issue.

https://github.com/cockroachdb/cockroach/pull/87554

**Comment by tbg** [comment]
I think this is mostly done as of https://github.com/cockroachdb/cockroach/pull/106793 (the test is merged in that PR), just need https://github.com/cockroachdb/cockroach/issues/106813.

**Comment by andrewbaptist** [comment]
I agree - Closing since the test for TestAddVotersWithoutRaftQueue is merged.
