### ISSUE TITLE
ui: rename `Active Executions` to `Current SQL Activity`

### ISSUE THREAD

**Issue by xinhaoz** [cockroachdb/cockroach#87638]
For the console, we have active execution pages for statements and txns in the SQL Activity tab.
It was pointed out that the label `Active Executions` may not be as clear to a developer as something like `Current SQL Activity`.
We should investigate if we want to rename this label or not, may need to consult with design.

cc @kevin-v-ngo 

Jira issue: CRDB-19454

**Comment by maryliag** [comment]
cc @jeremycbloom @stbof  for some feedback

**Comment by stbof** [comment]
> cc @jeremycbloom @stbof for some feedback

You'd need to update the description too:

Active executions represent individual statement executions in progress. Use active statement execution details, such as the application or elapsed time, to understand and tune workload performance.

Also the following table headings contain the word Execution: Statement Execution ID, Statement Execution.

I'd be inclined to leave the radio button as is.

**Comment by kevin-v-ngo** [comment]
I need to look for Anne's previous mockups here. We had discussed this several times and i think there were mockups on the ideal state once we have historical executions as well (Amy's issue).

**Comment by kevin-v-ngo** [comment]
I know we chose "Execution" to clearly distinguish from "Fingerprint"

**Comment by maryliag** [comment]
just want to point out this was a feedback, but we don't need to actually change. If we decide it makes sense to keep as is, that's completely fine!
