### ISSUE TITLE
ui: new admin UI designs for login

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#8764]
Current designs are here: https://projects.invisionapp.com/share/SK7S697HC#/screens/169822222
- [ ] Better wording for the "forgot your password" modal.
- [ ] Show if you are logged in as a particular user
- [ ] Logout link

**Comment by maxlang** [comment]
cc @kuanluo

**Comment by kuanluo** [comment]
@maxlang 
As discussed on Thursday, I'm going to make a complete UX flow so we know what screens we should account for, before making detailed designs. Would be great if you could help collect examples from our competitors. Thanks!

**Comment by kuanluo** [comment]
Punting this for Q2 next year. cc @dianasaur323

**Comment by dianasaur323** [comment]
Yes, agree - thanks. So that we have this tracked - the goal of this feature was to implement basic user login, but given the back-end complexity involved, punting this in favor of working more on monitoring and visualizations in Q1 2017

**Comment by dianasaur323** [comment]
Closing out in favor of https://github.com/cockroachdb/cockroach/issues/6307
