### ISSUE TITLE
changefeedccl: can't specify expression without diff

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#87644]
Noticed by Ron

This works:

CREATE CHANGEFEED
INTO 's3://nollen-cluster-backup-bucket/cdc-as-export-nvidia/?AWS_ACCESS_KEY_ID={redacted}&AWS_SECRET_ACCESS_KEY={shhhhhhhhhhhh}'
with schema_change_policy=stop, diff as select * from table0006 where column1 = '00000010-57d9-4141-8461-f62168f7dd62';

This does not:

CREATE CHANGEFEED
INTO 's3://nollen-cluster-backup-bucket/cdc-as-export-nvidia/?AWS_ACCESS_KEY_ID={redacted}&AWS_SECRET_ACCESS_KEY={shhhhhhhhhhhh}'
with schema_change_policy=stop as select * from table0006 where column1 = '00000010-57d9-4141-8461-f62168f7dd62';

Why is that? Is that expected?

Jira issue: CRDB-19458

Epic CRDB-17161

**Comment by miretskiy** [comment]
No, I suspect it's not okay;

**Comment by HonoreDB** [comment]
This may be related to https://github.com/cockroachdb/cockroach/issues/88239

**Comment by miretskiy** [comment]
Ahh... Good point, @HonoreDB ....

**Comment by amruss** [comment]
Can we close this?

**Comment by amruss** [comment]
Closing this out as we could never reproduce
