### ISSUE TITLE
server: endpoint to handle login on the backend

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#8765]
Create an authentication endpoint on the backend that verifies a username and password and provides a cookie (or possibly auth token) to the client.

There will also have to be an endpoint to handle logout.

It may be helpful to augment the current CLI tools for user creation.

**Comment by petermattis** [comment]
@mrtracy This is done, right?

**Comment by mrtracy** [comment]
Yes, the backend portion is complete, closing.
