### ISSUE TITLE
incorrect CPU utilization on node map 

### ISSUE THREAD

**Issue by lin-crl** [cockroachdb/cockroach#87664]
**Describe the problem**
The CPU utilization on node map is very different from the utilization on Hardware dashboard.
Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**
1. Set up CockroachDB cluster 
2. Run a workload such as movr or kv
3. Look at Nodemap CPU utilization and compare it w/ Hardware dashboard

**Expected behavior**
Expect consistent utilization on node map

**Additional data / screenshots**
![image](https://user-images.githubusercontent.com/76135413/189250654-7f42df8d-9eda-4a08-b2fd-a621b131c809.png)
![image](https://user-images.githubusercontent.com/76135413/189250668-f1bd6cea-6817-407c-ba5b-fa8f00291326.png)

**Environment:**
 - CockroachDB version 22.1.6
 - Server OS: Ubuntu
 - Client app - DBConsole

**Additional context**
What was the impact? - confusion to users

Jira issue: CRDB-19464

Epic CRDB-21265

**Comment by koorosh** [comment]
Node Map and `CPU Percent` metrics on Hardware dashboard represent CPU usage in different forms and rely on different metrics underneath.

- `CPU Percent` metric on `Hardware` dashboard - Current user+system cpu percentage, normalized 0-1 by number of cores
- CPU metric on Node Map - Sum of system and user current cpu percentage. Current metric is not present on Metrics dashboards.

I'd suggest to extend `Runtime` dashboard with a new metric to represent the same info as on Node Map. 
WDYT @thtruo

**Comment by thtruo** [comment]
> I'd suggest to extend `Runtime` dashboard with a new metric to represent the same info as on Node Map.

@koorosh Do you mean the `Hardware` dashboard? I don't think we should extend that dashboard with the Node Map metric. The node map metric should instead be updated to report what's used in the `CPU Percent` metric from the `Hardware` dashboard. That's a more accurate reflection. The current Node Map metric has resulted in confusion from customers before, especially when they see >100% values from the Node Map. We should use the normalized metric instead.

**Comment by koorosh** [comment]
> We should use the normalized metric instead.

Thanks for clarification!
