### ISSUE TITLE
server: Run API requests as authenticated user

### ISSUE THREAD

**Issue by maxlang** [cockroachdb/cockroach#8767]
When the client makes an authenticated request, the server must run that request as that user; currently, all API requests are still run as the root user, regardless of the specific user that has been authenticated.

**Comment by mrtracy** [comment]
User information can now be attached to API calls via an HTTP cookie.  This is not yet being enforced, but is implemented.

**Comment by mrtracy** [comment]
Closed the wrong bug, this one needs to get moved to 1.2.

**Comment by vilterp** [comment]
@mrtracy I see this function `getUser` called in all of our endpoints. Currently it just returns `RootUser`: https://github.com/cockroachdb/cockroach/blob/28a7b6befcdcf7c316078da55d1009877beb058c/pkg/server/admin.go#L121-L123

How would we get this from a cookie?

**Comment by vilterp** [comment]
Update after talking to @mrtracy:

1. we get the user in this method; put it in `req.Context()`: https://github.com/cockroachdb/cockroach/blob/dab9f23fd49860faeaa9f4303b7f5d6e888f3ab8/pkg/server/authentication.go#L317
2. change the `getUser` method above to take the context gRPC gives us and return the user from it

**Comment by vilterp** [comment]
Seems to be blocked by grpc-gateway not properly passing contexts through: https://github.com/grpc-ecosystem/grpc-gateway/issues/470

We may need to fix this ourselves and either upstream it or fork grpc-gateway and vendor it.

**Comment by knz** [comment]
Fixed in  #42563.
