### ISSUE TITLE
sql: (schema) support default values in UDF

### ISSUE THREAD

**Issue by chengxiong-ruan** [cockroachdb/cockroach#87698]
Currently default value [is disallowed](https://github.com/cockroachdb/cockroach/blob/203c078acb1d55bdbddd61ecaae4e71eb96c0240/pkg/sql/create_function.go#L457-L457) because execution is not modified to handle it yet. We can remove the blocker once execution is happy with that.

Jira issue: CRDB-19487

Epic CRDB-19497

**Comment by yuzefovich** [comment]
This is a dup of #100962 and has been addressed in 24.1.
