### ISSUE TITLE
Insights page added to Cloud Dedicated

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#87693]
Once SQL over http is available on Cloud, the Insights page should be added to Cloud Dedicated

Jira issue: CRDB-19482

**Comment by maryliag** [comment]
Re-opening since it still needs to be enabled on Cloud side, after cluster-ui gets updated

**Comment by ericharmeling** [comment]
Closed by https://github.com/cockroachlabs/managed-service/pull/10097
