### ISSUE TITLE
sql: (schema) UDF to support `OUT` argument class

### ISSUE THREAD

**Issue by chengxiong-ruan** [cockroachdb/cockroach#87705]
Currently only `IN` argument class is supported, it'd be nice to turn on other argument class support such as `OUT`.
This would requires a few things:
1. turn on syntax support, need to check return type match if `RETRUNS` is also specified.
2. smart enough to convert `OUT` arguments into return types.
3. descriptor support of this new attribute. still keep record of such argument in descriptor of `SHOW CREATE` purpose.

Jira issue: CRDB-19493

Epic CRDB-20370

**Comment by mgartner** [comment]
@chengxiong-ruan I believe this was mistakenly closed. This work still remains, correct?

**Comment by chengxiong-ruan** [comment]
> @chengxiong-ruan I believe this was mistakenly closed. This work still remains, correct?

Correct, weird that this was closed somehow...

**Comment by yuzefovich** [comment]
This is a dup of #100405 which has been addressed in 24.1.
