### ISSUE TITLE
Acceptance testing 22.2 - Incorrect insight details for a slow execution

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#87740]
Slow execution insight has the incorrect insight:

<img width="904" alt="image" src="https://user-images.githubusercontent.com/81193618/189430657-479b1c87-c692-45a5-b140-e75dc75c4eff.png">

It should be:

<img width="726" alt="image" src="https://user-images.githubusercontent.com/81193618/189430785-0b066fbd-d9b6-44c6-bced-1081796776b5.png">

https://www.figma.com/file/xpnRkP9cLXERVceRC4cec4/22.2_SQL-obsrv_query-performance?node-id=1086%3A72736

Jira issue: CRDB-19508

**Comment by maryliag** [comment]
I don't think we have a link for SQL performance best practices

**Comment by kevin-v-ngo** [comment]
We can use the following link for now: https://www.cockroachlabs.com/docs/stable/performance-best-practices-overview.html
