### ISSUE TITLE
Acceptance testing 22.2 - Active Executions issues

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#87757]
1. Create two transactions write-read contention
2. Go to Active executions (both Statement-level and Transaction-level)
3. **Attempt to view the Statement and Transaction details where the app will crash**

<img width="951" alt="image" src="https://user-images.githubusercontent.com/81193618/189492120-30e4d6b6-529e-4f2c-a211-73d8030219fd.png">

1. **There is also no URL to the active transaction coming from the Sessions details page**
<img width="682" alt="image" src="https://user-images.githubusercontent.com/81193618/189447835-d426185f-2e37-40f3-b427-e6b9cae15a02.png">

https://www.figma.com/file/xdmwvnFQd6KkO9RJ0XLDH0/22.1_SQL-obsrv_query-performance?node-id=5380%3A142731

https://www.loom.com/share/f8b8730378e748e896d23642f17592be

Sample script with Movr:

BEGIN;
	SET application_name = 'Blocker Transaction';
INSERT INTO users VALUES ('acde070d-8c4c-4f0d-9d8a-162843c10336', 'NYC', 'Kevin', '125 W 25th St', '123'); --pause here
	END;

BEGIN;
	SET application_name = 'Blocked Transaction';
SELECT * FROM users; --statement will be blocked
	END

Jira issue: CRDB-19520

**Comment by kevin-v-ngo** [comment]
<img width="951" alt="image" src="https://user-images.githubusercontent.com/81193618/189492105-59ef79ca-4597-4f83-8b4e-4e58873dd0f3.png">

**Comment by maryliag** [comment]
The PR linked above fixes the crash, but I don't know if is possible to show the transaction information when it's still open though. 
I will leave to @xinhaoz to take a look into it.
