### ISSUE TITLE
Acceptance testing 22.2 - Transaction high contention insights do not link users to transaction that blocked it

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#87784]
We should guide users to the blocking (transactions N waited on) transactions for more context which would give users more details. More specifically, whether the blocking transaction also waited for other transactions to complete.

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/81193618/189504216-c80e4f6f-6c5b-4ffb-828d-e0301d1161a5.png">

Jira issue: CRDB-19536

**Comment by ericharmeling** [comment]
Closing this issue (see https://github.com/cockroachdb/cockroach/pull/87876#issuecomment-1256250363). I think resolving https://github.com/cockroachdb/cockroach/issues/87750 and https://github.com/cockroachdb/cockroach/issues/83780 and https://github.com/cockroachdb/cockroach/issues/91696 should be sufficient.
