### ISSUE TITLE
Acceptance testing 22.2 - Failed executions insights

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#87785]
Failed execution insights are surfacing already. We are missing critical information such as the error code and message to help users troubleshoot why the statement failed.

<img width="1603" alt="image" src="https://user-images.githubusercontent.com/81193618/189504384-40d5a384-b361-4558-ba1f-f075f383e06a.png">

Jira issue: CRDB-19537

Epic CRDB-20388

**Comment by maryliag** [comment]
Completed on https://github.com/cockroachdb/cockroach/pull/110849
