### ISSUE TITLE
all: Remove Author Tags

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#8779]
The author tags at the top of all code files have, for the most part, rotted.  We already have a better history via github.  I propose we remove all author tags.

@mberhault suggested an owner's file instead, which makes a lot more sense and is a lot easier to maintain.  Marc, can you suggest a specific format for the owner's file?

**Comment by mberhault** [comment]
I would go with either github username or email (we should pick one). One per line, that's it. Maybe comments allowed with `#`

**Comment by tschottdorf** [comment]
I find the Author tags mostly useless as well. While I don't really care for the idea of an OWNERS file as well, I'm not opposed to it.

**Comment by dt** [comment]
imo `git blame` is the only thing that is really immune to rot, so explicit denormalization of owner/expertise should be the exception (when it differs from what `git blame` would suggest), not the rule.

**Comment by jordanlewis** [comment]
I like the idea of removing the Author tags. I think that an `OWNERS` file would probably be subject to rot as well, and that `git blame` provides enough information for people trying to understand who knows what about the code.

**Comment by tschottdorf** [comment]
Done in #17333.
