### ISSUE TITLE
cli: provide a cockroach command to open the web ui

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#8780]
Playing around with Kubernetes, I noticed a command for starting up their web ui from the command line: [`minikube dashboard`](http://kubernetes.io/docs/getting-started-guides/minikube/#starting-the-cluster). It'd be a nice to be able to do that for a cockroach cluster, perhaps something like `cockroach dashboard`. Not sure how feasible this is.

@maxlang 

Jira issue: CRDB-6365

**Comment by mberhault** [comment]
I'm not sure we can provide something that simple.
If you're running the local binary (on the same machine and with the same args as the node), the best we could do right now is generate a link with the advertised address. When this address is an internal cloud address, it won't help.
If you're running on a machine outside the cluster, you'll need to tell the cockroach binary what cluster you're talking about by specifying something along the lines of: `--host=clustername.gce.cockroachdb.com`. At that point, you have the link already.

**Comment by jseldess** [comment]
Yeah, I think even for Kubernetes, this is possible only when running locallywith `minikube`. But in that case, it is quite convenient.

**Comment by knz** [comment]
Discussed on #39483
> I think the approach that was taken here is not suitable in general because of all the deployment complexity. We should implement this for CockroachCloud instead, where the address of the UI for a CC cluster is easy(ier) to determine and agnostic of network setup.
