### ISSUE TITLE
changefeedccl: TestBlockingBufferNotifiesConsumerWhenOutOfMemory is flakey

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#87828]
[Build](https://teamcity.cockroachdb.com/viewLog.html?buildId=6441660&buildTypeId=Cockroach_BazelEssentialCi):
```
=== RUN   TestBlockingBufferNotifiesConsumerWhenOutOfMemory
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/5b1d3fc81e56576fdf57f2b3920e759a/logTestBlockingBufferNotifiesConsumerWhenOutOfMemory504995075
    test_log_scope.go:79: use -show-logs to present logs inline
panic: test timed out after 4m55s
```
Seems like #87718 could be related.

Jira issue: CRDB-19555

**Comment by ajwerner** [comment]
This also just failed a bors run:
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/6443871?showRootCauses=false&expandBuildChangesSection=true&showLog=6443871_4867__expandAll&logFilter=debug
