### ISSUE TITLE
metrics: export go runtime metrics

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#87823]
**Is your feature request related to a problem? Please describe.**

The Go runtime exports several metrics about the Go scheduler, garbage collector, and heap that would be useful to export directly: https://pkg.go.dev/runtime/metrics#hdr-Supported_metrics. Newer versions of the prometheus Go client (https://github.com/prometheus/client_golang) support exporting this into a form prometheus can scrape. It may be a bit of work to munge this data into a form writable to CRDB's internal tsdb. This would help better diagnose behavior of the Go GC, scheduler, etc.

**Additional context**

We're exporting `/sched/latencies:seconds` as part of https://github.com/cockroachdb/cockroach/issues/82743. This issue covers everything else.

Jira issue: CRDB-19553

Epic CRDB-34227

**Comment by irfansharif** [comment]
#87883 introduces a `runtimeHistogram` type that's a bit improperly placed in the `schedulerlatency` package. It's used to export scheduling latencies but can be used as is for other histograms from the runtime. I'll leave that extraction to the obs-inf folks.

**Comment by nvanbenschoten** [comment]
Resolved by https://github.com/cockroachdb/cockroach/pull/118875, which introduced the framework for exporting go runtime metrics.
