### ISSUE TITLE
sql: add ability set, edit, read tenant capabilities

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#87851]
See the RFC here: #85954.

We would like to have a new overload to `crdb_internal.create_tenant()` and a new built-in function `crdb_internal.set_tenant_capabilities` (maybe also with a getter) to edit tenant capabilities.

This issue should also cover:

- [ ]  Cache invalidation of capabilities on edit.
- [ ] SHOW TENANT CAPABILITIES statement
- [ ] Syntax to create both privileged tenants and unprivileged ones

Epic: CRDB-19504

Jira issue: CRDB-19569

**Comment by ecwall** [comment]
Instead of adding new overloads (going from 3 to 6) for `crdb_internal.create_tenant()`, I will modify the `CREATE TENANT` syntax.

Discussion: https://cockroachlabs.slack.com/archives/C02HWA24541/p1668711998299439

**Comment by ajstorm** [comment]
This issue should also cover:

- [ ] Cache invalidation of capabilities on edit.
- [ ] SHOW TENANT CAPABILITIES statement
