### ISSUE TITLE
1.0 roadmap or wish-list

### ISSUE THREAD

**Issue by mohan-chinnappan-n** [cockroachdb/cockroach#8785]
Do we have a detailed wish-list for 1.0 release?

**Comment by a-robinson** [comment]
You can see our [roadmap for 2016 on our wiki](https://github.com/cockroachdb/cockroach/wiki), which mostly aligns with the goals for 1.0. For more detail, I'd recommend checking out the issues in our [Q3](https://github.com/cockroachdb/cockroach/milestones/Q3) and [1.0](https://github.com/cockroachdb/cockroach/milestones/1.0) milestones.

If you have any specific requests, feel free to open an issue with details about them!
