### ISSUE TITLE
cli: interactive sql shell acts weird on kubernetes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#8788]
When running CockroachDB on a local Kubernetes cluster, typing in the sql moves the cursor to the top. It's weird. 

Steps to reproduce:

1. Install and start Kubernetes cluster: http://kubernetes.io/docs/getting-started-guides/minikube/.
2. Run this scrip, which creates persistent volumes and runs the yaml configuration that creates the cockroach resources: https://github.com/a-robinson/kubernetes/blob/33c8885eba8c69c1107f641241cd2f08ed15d5ec/examples/cockroachdb/cockroachdb-petset.yaml.
3. Start a bash session in one of the pods and star the sql shell:

   ```
   $ kubectl exec -it cockroachdb-0 bash
   root@cockroachdb-0:/cockroach# ./cockroach sql --host $(hostname)
   # Welcome to the cockroach SQL interface.
   # All statements must be terminated by a semicolon.
   # To exit: CTRL + D.
   root@cockroachdb-0:26257>
   ```
4. Type some statements in the shell.

Screencast of what happens: https://asciinema.org/a/d19gmvzket2wno57sbhfi0fhr

**Comment by knz** [comment]
cc @chzyer what do you think?

**Comment by chzyer** [comment]
It must be a bug. Is it works correctly without kubectl?
Maybe there is caused by some pty flags in kubectl .

**Comment by knz** [comment]
@chzyer does readline use the termcap/terminfo database to determine which escape code to use?

**Comment by chzyer** [comment]
@knz, sorry for my late reply.
readline is not using `termcap/terminfo` database.
I'm trying to reproduce and fix it. :)

**Comment by chzyer** [comment]
@knz 
I did some research for kubernetes. When `kubectl` communicaing with `server` using `protocolV2`, kubernetes can't adjust the size of terminal from `kubectl`. 
[[source code for v2](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/server/remotecommand/httpstream.go#L331)], [[source code for v3](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/server/remotecommand/httpstream.go#L293)]

I just setup a new kubernetes cluster by `minikube`, and I can sure that it's using protocolV2. `Readline` can't work when the size terminal is 0.
So, there are two ways to fix that:
1. update kubernetes to using protocolV3 or above
2. update readline to latest version, I just submit a fix, but it's not supporting `search/complete` mode yet.

**Comment by knz** [comment]
Hi @chzyer many thanks for your time and your investigation.
We can definitely update the dependency on readline, I can work on that.
However I think it is also worthwhile to ping k8s to see if they can use protocolv3. @a-robinson what do you think? Is this feasible?

**Comment by chzyer** [comment]
Maybe should ping @[minikube](https://github.com/kubernetes/minikube) too :)

**Comment by a-robinson** [comment]
I'm not sure what's making the choice between v2 and v3. Did you get that far into the code, @chzyer? I don't personally have much familiarity with the client, but we can certainly improvements with them.

**Comment by chzyer** [comment]
@a-robinson 

I only can recompile `kubectl` via latest version. In `kubectl`, it will send all the protocols which it supported to remote, and server will choose a protocol in return. [source code in kubectl](https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/remotecommand/remotecommand.go#L156)
According to the code below, it seems `kubelet/server` is just too old to use protocol v3, but `minikube` is lastest version.
[remotecommand.SupportedStreamingProtocols](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/server/remotecommand/constants.go#L46)
[remotecommand.ServeExec](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/server/server.go#L609)

**Comment by a-robinson** [comment]
Ah, [looks like in k8s v1.3 they only supported the v1 and v2 protocols](https://github.com/kubernetes/kubernetes/blob/release-1.3/pkg/kubelet/server/remotecommand/contants.go#L36). Given that the master branch supports up through the v4 protocol, their 1.4 release (which should be available by the end of September) will likely resolve this.

**Comment by chzyer** [comment]
@knz , Thanks 👍

**Comment by a-robinson** [comment]
I can confirm that kubectl 1.4.0 fixes this even if our readline changes don't seem to have done so.
