### ISSUE TITLE
distsql: design an efficient way to pass around small datums

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#8792]
`EncDatum` is good for large variable-sized values but it's way too much overhead for small values (extra memory, logic, indirection). We need a better way to support small values. Perhaps an EncDatumRow can have a set of `EncDatum`s and a separate set of small datums that are stored contiguously (and the Datum interface created "on demand").

In addition, we should separate the metadata (e.g. the types of the datums) from the row storage itself (since the metadata is the same for all the rows that go through a stream/channel). Perhaps this ties in with passing blocks of rows instead of one row at a time (each block could store the metadata once).
#7529 is somewhat related (the performance aspect of it at least).

**Comment by RaduBerinde** [comment]
@knz @paperstreet

**Comment by knz** [comment]
Do you perhaps want to start looking at some ideas from #8015? 

In particular the main idea that would be useful here would be to work on packets of multiple rows at a time, and store them in memory in a column-oriented fashion (with an array of values of the same Go type for all values in the same column).

For the memory consumption stuff I've felt myself wanting to look into it more too, to reduce the number of times memory consumption is checked.

**Comment by RaduBerinde** [comment]
This problem got a lot worse when collated strings were introduced - the type is now much bigger than a simple enum. We probably want to separate the type information from the `EncDatum` structure; the caller would need to manage the type info and pass it as necessary.

**Comment by andreimatei** [comment]
As part of taking the types out of EncDatums, the DistSQL streams that cross nodes should be configured with typing information: #13798

**Comment by jordanlewis** [comment]
Closing this as it's not an issue in the columnar representation.
