### ISSUE TITLE
changefeedccl: macro benchmarks over several performance improvements

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/cockroach#87921]
We’ve implemented several performance improvements for changefeeds. Let’s test some macro before-and-after to tally up the overall win for our users.

- https://github.com/cockroachdb/cockroach/pull/86421
  - https://github.com/cockroachdb/cockroach/pull/87767
  - Impact: reduce changefeed backfill impact on foreground SQL
- https://github.com/cockroachdb/cockroach/pull/87718
  - https://github.com/cockroachdb/cockroach/pull/87796
  - Impact: reduce changefeed backfill impact on foreground SQL
- https://github.com/cockroachdb/cockroach/pull/85156
  - Impact: reduce changefeed backfill impact on foreground SQL
  - In v22.2, no need for backport
- https://github.com/cockroachdb/cockroach/pull/87472
  - https://github.com/cockroachdb/cockroach/pull/87871
  - Impact: improve throughput on CSV (especially when used for export to cloud storage)
- https://github.com/cockroachdb/cockroach/pull/88621
  - https://github.com/cockroachdb/cockroach/pull/88669
  - https://github.com/cockroachdb/cockroach/pull/88671
  - Impact: improve throughput on CSV (especially when used for export to cloud storage)
  - Will evaluate v22.2 backport once tested & merged
- https://github.com/cockroachdb/cockroach/pull/88064
  - https://github.com/cockroachdb/cockroach/pull/87968
    - https://github.com/cockroachdb/cockroach/pull/88092
  - Impact: improve throughput on JSON (especially when used for export to cloud storage)
- https://github.com/cockroachdb/cockroach/pull/88395
  - Likely substantial throughput improvement (especially when used for export to cloud storage)
  - Also a substantial change to the hot path that will require care and testing
  - Aiming to backport after v22.2.0 release, perhaps as early as v22.2.1
- https://github.com/cockroachdb/cockroach/pull/87994
  - Likely substantial throughput improvement (especially when used for export to cloud storage)
  - Also a substantial change to the hot path that will require care and testing
  - Aiming to backport after v22.2.0 release, perhaps as early as v22.2.1
- https://github.com/cockroachdb/cockroach/issues/88585
  - https://github.com/cockroachdb/cockroach/pull/88635
  - https://github.com/cockroachdb/cockroach/pull/88632
  - Removes penalty when using gzip (and adds [zstd](https://facebook.github.io/zstd/), another fast compression algo)
    - That penalty was observed to be as much as 3× with latest improvements; less dramatic on earlier versions where compression wasn’t the bottleneck.
- https://github.com/cockroachdb/cockroach/pull/88672
  - Improve “long tail” performance issues for large backfills (exports)
  - Will consider for v22.2
- https://github.com/cockroachdb/cockroach/pull/84686
  - https://github.com/cockroachdb/cockroach/pull/84702
  - In v22.2
  - We are likely to revert this, the number is proving to be too small

Jira issue: CRDB-19595
Epic CRDB-8666

**Comment by amruss** [comment]
Leaving this in triage so we can discuss post-stability

**Comment by shermanCRL** [comment]
cc @nollenr

**Comment by jayshrivastava** [comment]
Closing in favor of https://github.com/cockroachdb/cockroach/issues/89977. 

What we want to accomplish is common benchmarks for changefeeds (ex. how long does it take to export B amount of data with N nodes M CPU using Z encoding with Y sink) to share with customers/sales. We already have roachtests which are standardized tests which can be run using a variety of parameters. In the above issue, we are going to add a mechanism to publish results to roachperf.
