### ISSUE TITLE
storage: remove `MultiIterator`

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#87943]
We should replace `MultiIterator` with `NewPebbleSSTIterator()`, which can iterate over multiple multiplexed SSTs. There are two remaining call sites:

* [`backupinfo.BackupMetadata.FileIter()`](https://github.com/cockroachdb/cockroach/blob/27c9b8fd760dd2ace9d44e01ac64e3443a2c7e2a/pkg/ccl/backupccl/backupinfo/backup_metadata.go#L1001)
* [`cliccl.processEntryFiles()`](https://github.com/cockroachdb/cockroach/blob/12daec613a831455df9db56dd9b08da5ab433ed0/pkg/ccl/cliccl/debug_backup.go#L670)

Jira issue: CRDB-19606

Epic CRDB-2624

**Comment by erikgrinaker** [comment]
@msbutler Can you confirm that these two call sites are safe as-is? If so, we can probably punt this cleanup to 23.1.

**Comment by msbutler** [comment]
@erikgrinaker yup, these calls will not encounter any rangekeys, so they're safe.
