### ISSUE TITLE
Run command "./dev doctor" error

### ISSUE THREAD

**Issue by a1424360017** [cockroachdb/cockroach#87989]
I want to get and build CockroachDB from source, so follow the setp in  https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/181338446/Getting+and+building+CockroachDB+from+source
and
https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/2221703221/Developing+with+Bazel
but when i run command "./dev doctor" i encounter following problem:

\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=
\=\=\=\=\=\=\=RUNNING DOCTOR CHECKS \=\=\=\=\=\=\=
\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=
ERROR: exit status 1

Jira issue: CRDB-19633

**Comment by rickystewart** [comment]
Not sure if you still need help, but `dev doctor --debug` might provide more color. You can paste the output here if it's not clear.
