### ISSUE TITLE
Enabling the CI for ARM64 

### ISSUE THREAD

**Issue by odidev** [cockroachdb/cockroach#87990]
Hi @team, 

I have successfully tested the cockroach locally on ARM64 using command ``` ./dev test ```.  

But when I tried to test the same on Teamcity for ARM64, I was getting the error regarding build agents. There is no build agent available for arm64. 

It will be helpful for users if CI testing for ARM64 is enabled on Cockroachdb Teamcity. I am happy to contribute if required. 

Jira issue: CRDB-19634

**Comment by healthy-pod** [comment]
> It will be helpful for users if CI testing for ARM64 is enabled on Cockroachdb Teamcity.


Hi @odidev, CI testing on ARM64 is now enabled and can be found under `Bazel Extended CI`. Is that what you were looking for?
