### ISSUE TITLE
Creating JDBC array for "string" doesn't work

### ISSUE THREAD

**Issue by beikov** [cockroachdb/cockroach#87993]
**Describe the problem**

Running `Connection.createArrayOf()` fails when passing the base type name `string` with:

> `Unable to find server array type for provided name string.`

**To Reproduce**

Just run the JDBC code:

```
connection.createArrayOf( "string", new String[]{} )
```

and see the error:

```
Caused by: org.postgresql.util.PSQLException: Unable to find server array type for provided name string.
	at app//org.postgresql.jdbc.PgConnection.createArrayOf(PgConnection.java:1409)
	at app//org.postgresql.jdbc.PgConnection.createArrayOf(PgConnection.java:1429)
```

**Expected behavior**

Should work

**Environment:**
 - CockroachDB version: Docker image cockroachdb/cockroach:v21.2.10
 - Server OS: Linux docker image
 - Client app: JDBC

Jira issue: CRDB-19636

**Comment by rafiss** [comment]
Thanks for the issue! Does it work if you try `connection.createArrayOf( "text", new String[]{} )`?

**Comment by beikov** [comment]
Hey there. It indeed does work when using `varchar` or `text`, which is also my workaround for now.

**Comment by rafiss** [comment]
I think this is a limitation in PGJDBC. It calls [`getTypeForAlias`](https://github.com/pgjdbc/pgjdbc/blob/818ef6439629c11375e937670322f5fd0f362f78/pgjdbc/src/main/java/org/postgresql/jdbc/TypeInfoCache.java#L718) which consults a hardcoded [`TYPE_ALIASES`](https://github.com/pgjdbc/pgjdbc/blob/818ef6439629c11375e937670322f5fd0f362f78/pgjdbc/src/main/java/org/postgresql/jdbc/TypeInfoCache.java#L121-L136) map.

**Comment by rafiss** [comment]
Since this appears to be more of a PGJDBC issue, I will close this. Please leave a comment if there's something I've missed.
