### ISSUE TITLE
sql: investiage a PostgreSQL-compatible DROP INDEX syntax

### ISSUE THREAD

**Issue by alamaison** [cockroachdb/cockroach#8800]
Postgres supports dropping indices using the following syntax [1]:
`DROP INDEX my_index;`

CockroachDB doesn't support that syntax:
```
syntax error at or near "my_index"
drop my_index;
```
Instead it requires
`DROP INDEX my_index@my_table;`

It makes sense to have a syntax that can disambiguate indices by table name.  However, for compatibility with existing code, it also makes sense to drop a matching index without an explicit table name, if there is only one such index.

Is the incompatiblity intentional?

[1]: https://www.postgresql.org/docs/9.2/static/sql-dropindex.html

```
Build Tag:   beta-20160728
Build Time:  2016/07/28 17:02:34
Platform:    linux amd64
Go Version:  go1.6.3
C Compiler:  gcc 4.9.2
```

**Comment by peter-dudbridge** [comment]
+1

**Comment by knz** [comment]
General question: do you foresee that production applications that envision migrating from pg to cockroachdb would be limited by the lack of this feature? (Trying to gauge the impact here)

**Comment by alamaison** [comment]
We hit this because of database migrations where DROP INDEX is occasionally necessary.  We maintain migrations as a set of hashed SQL files which can't be modified after they are applied, but must also remain applyable from scatch in dev environments.  That means they need be able to run as-is.

Also, if you are trying to maintain compatibility with _both_ Postgres and Cockroach (different customers have different risk/scale appetites) incompatibilities make that difficult.

**Comment by dt** [comment]
@dt just mentioning myself track this.
