### ISSUE TITLE
changefeedccl: Alter changefeed broken when cursor set

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#88050]
When the changefeed is started with cursor option, and then
runs for a while (>gcttl time -- say 25 hours), the attempts to
alter changefeed will fail due to the fact that `createChangefeedJobRecord`
uses cursor (which is now very old) to set the time at which targets
are resolved. 

Jira issue: CRDB-19662

gz#13947

Epic CRDB-14988

**Comment by amruss** [comment]
Putting this on the backlog for now but feel free to pick it up @anyone who wants to
