### ISSUE TITLE
changefeedccl: TestBlockingBufferNotifiesConsumerWhenOutOfMemory timed out

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#88051]
See ci artifacts [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=6491204&buildTypeId=Cockroach_BazelEssentialCi). 

Jira issue: CRDB-19663

Epic CRDB-11732

**Comment by irfansharif** [comment]
This test has a relatively high flake rate, looking at its [history](https://teamcity.cockroachdb.com/project.html?projectId=Cockroach_Ci_TestsGcpLinuxX8664BigVm&buildTypeId=&tab=testDetails&testNameId=-3420370621452259115&order=TEST_STATUS_DESC&branch_Cockroach_Ci_TestsGcpLinuxX8664BigVm=__all_branches__&itemsCount=50). Flaked most recently for me on an unrelated PR: #87969.

**Comment by miretskiy** [comment]
Most recent history is 1000 out of 1000 clean runs.
