### ISSUE TITLE
debug zip: redacted debug zips include contents from the payload column from system.jobs dump

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#88069]
**Is your feature request related to a problem? Please describe.**
Certain columns in `system`/`crdb_internal` table dumps, in particular the `payload` column from `system.jobs`, that are considered important to observability and for troubleshooting clusters are entirely omitted in the new redaction behavior for debug zips to hit baseline PCI compliance for v22.2. 

**Describe the solution you'd like**
We want to ensure the `payload` column from the `system.jobs` dump are included in, not omitted from, redacted debug zips. One idea is to create builtins to redact especially important columns in system table dumps within debug zip. 

Jira issue: CRDB-19668

**Comment by thtruo** [comment]
Heads up @livlobo I've assigned this to Disaster Recovery since your team is likely most familiar to system.jobs payloads. This was an outstanding item that came out from Obs Infra's work to reach baseline PCI compliance before the end of September. This item should ideally be included in a minor patch release for v22.2
cc-ing @abarganier and @nkodali for awareness

**Comment by abarganier** [comment]
Thanks for filing the issue, @thtruo. 

Similar work has been started for the `descriptor` column from `system.descriptor` (see: https://github.com/cockroachdb/cockroach/pull/87839). This sets a good example for how we can approach the construction of these builtins to redact important payloads safely via SQL. 

As some added context, the primary PCI-DSS compliance deadline maps to the end of the year, so we should aim to have this in a minor version patch release for v22.2 by then.

**Comment by livlobo** [comment]
CC: @amruss who is leading the Jobs infrastructure area.

**Comment by amruss** [comment]
I'm going to separate this out into an issue for each job-owner team, since they should be making the decision on what to redact/how granular to redact for their job

**Comment by ajwerner** [comment]
How are we going about redacting portions of the job payload? Is there a toolkit to redact or in some way meaningfully modify the protobuf? For example, the schema changes are mostly IDs and SQL statements but there are also some roachpb.Span which contain checkpoints. Guidance will be helpful here. I assume @abarganier is leading the eng charge. Please advise.

**Comment by abarganier** [comment]
I'm not quite leading eng on this one, but happy to advise! 

One way to approach this would be quick & easy, but flawed - audit the payloads and simply clear any sensitive fields with a builtin. Take in some proto bytes, deserialize, "clear" any sensitive fields, and return the serialized bytes.

Of course, this won't stand the test of time. What if new fields are added that are sensitive? Those could easily be leaked. 

A more ironclad way to approach this would be to use something like protobuf annotations to mark fields as `non-sensitive`. We could then use reflection to iterate all the fields of the proto message and clear all of those that have not been explicitly marked as `non-sensitive`. The default, of course, is that a field *is* sensitive, making it an opt-in mechanism. 

We could use the `google.protobuf.FieldOptions` mechanism [here](https://developers.google.com/protocol-buffers/docs/proto3#customoptions) to create these annotations.

My thinking is that this would allow us to create a single generalized `crdb_internal.redact` builtin. We provide the type and payload bytes, (e.g. `crdb_internal.redact('cockroach.sql.jobs.jobspb.Payload', payloadBytes)`) and reflection is used to clear any field not marked `non-sensitive`.

**Comment by abarganier** [comment]
I did some investigation on this and it turns out we already have a mechanism to do this! Using the `moretags` gogoproto annotation mechanism, we can define arbitrary struct tags on proto message fields.

In a couple places, we already are marking fields as sensitive/non-sensitive. For example: https://github.com/cockroachdb/cockroach/blob/e74dd712305c5ed514bcb3edb8e3746efc3f1fe6/pkg/util/log/eventpb/events.proto#L49

This seems like the correct way forward to me. I think this work can likely be combined with https://github.com/cockroachdb/cockroach/issues/86309, which requires something similar for `system.descriptor`. A generalized redaction builtin can be used for both. cc @thtruo for awareness.

**Comment by ajwerner** [comment]
The deeper question here, from my perspective, is how to think about timelines and priority on this work. Is there some deadline?

**Comment by abarganier** [comment]
cc @thtruo @nkodali regarding timelines here. I've heard "by the end of the year" thrown around, but am not positive.

**Comment by thtruo** [comment]
So there is an "end of the year" PCI deadline, but this issue (and other similarly referenced ones to bring back omitted columns in a usefully redacted form) isn't a hard blocker against that deadline - since we are technically already PCI compliant. 

However, these debug zips do impair our TSE and field team's ability to troubleshoot customer clusters. So our collective goal should be to continuously add these enhancements to patch versions of **22.2**.x sooner rather than later - the longer we wait, the more pressure this puts on our TSEs.

**Comment by postamar** [comment]
Should this issue be epic-linked as part of the PCI compliance efforts? Who owns this, in the sense of being accountable for this to happen? Schema has a bunch of execution work to do here and but we're not going to take the lead on it.

**Comment by amruss** [comment]
@postamar we've over-redacted at the moment, so this isn't important for PCI. I would put this on each individual job owner team to decide the priority and own the delivery for their team.

**Comment by shermanCRL** [comment]
Per @amruss, can close this, there are individual issues assigned to teams.
