### ISSUE TITLE
sql: query planning/execution correctness bug on a vtable anti join

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#88096]
Solution needed for  #88061.

**Describe the problem**

It's a compound problem:
- PostgreSQL and CockroachDB return different results on a simple query containing a correlated join on a vtable;
- CockroachDB also *returns inconsistent results* depending on which predicate is added to the query, where PostgreSQL would return the same results in any case.

Close inspection of the query plan suggest that the `virtual table lookup join (anti)` may be inverting its boolean predicate condition.

**How to reproduce**

After initial:
```sql
create type mytype as enum('hello');
```

Crdb returns conflicting results on the following queries:

```sql
SELECT *
  FROM pg_type AS t
 WHERE NOT EXISTS(SELECT 1 FROM pg_type AS el WHERE el.oid = t.typelem AND el.typarray = t.oid)
   AND t.typname LIKE 'myt%'
```

(here, the output is correct)

and
```sql
SELECT *
  FROM pg_type AS t
 WHERE t.typrelid = 0
   AND NOT EXISTS(SELECT 1 FROM pg_type AS el WHERE el.oid = t.typelem AND el.typarray = t.oid)
   AND t.typname LIKE 'myt%'
```

(here, the output is incorrect)

In PostgreSQL, both queries return the same output, that of the first query above.

This suggests that the query plan for the 2nd query is incorrect.

cc @mgartner for triage.

Jira issue: CRDB-19682

**Comment by mgartner** [comment]
Let's aim to fix this by ~Feb 2023 to unblock some CLI improvements for 23.1.

**Comment by yuzefovich** [comment]
This issue is different from #91012. I believe here the problem is somewhere in the optimizer land.

Consider the following setup:
```sql
create type mytype as enum('hello');

EXPLAIN (VERBOSE)
	SELECT count(*)
	FROM pg_type AS t
	WHERE
		t.typrelid = 0
		AND NOT EXISTS(SELECT 1 FROM pg_type AS el WHERE el.oid = t.typelem AND el.typarray = t.oid)
		AND t.typname LIKE 'myt%';
```
The output includes the following:
```
      └── • virtual table lookup join (anti)
          │ columns: (oid, typname, typrelid, typelem)
          │ estimated row count: 0 (missing stats)
          │ table: pg_type@pg_type_oid_idx
          │ equality: (typelem) = (oid)
          │ pred: typarray = oid
          │
          └── • filter
              │ columns: (oid, typname, typrelid, typelem)
              │ estimated row count: 9 (missing stats)
              │ filter: (typrelid = 0) AND (typname LIKE 'myt%')
              │
              └── • virtual table
                    columns: (oid, typname, typrelid, typelem)
                    estimated row count: 1,000 (missing stats)
                    table: pg_type@primary
```
meaning that the virtual anti lookup join is using `oid` column from the virtual table scan as the index key into `pg_type_oid_idx`; however, when I look at the execution of the virtual lookup join, it's `eqCols` is equal to `3` meaning that we attempt to use `typrelid` (which is 0 and not 1000xx) as the lookup key. It appears that we messed up some kind of mapping during the transformation (most likely in `generateLookupJoinsImpl`).

**Comment by mgartner** [comment]
The plan looks correct to me. `equality: (typelem) = (oid)` shows that the equality columns in the lookup join are correct. And the optimizer plan corroborates that (column `34` is `el.oid`):

```
  scalar-group-by
   ├── columns: count:66
   ├── cardinality: [1 - 1]
   ├── stats: [rows=1]
   ├── cost: 2803.02333
   ├── key: ()
   ├── fd: ()-->(66)
   ├── distribution: us-east1
   ├── prune: (66)
   ├── anti-join (lookup pg_type@pg_type_oid_idx [as=el])
   │    ├── columns: t.oid:2 t.typname:3 t.typrelid:13 t.typelem:14
   │    ├── key columns: [14] = [34]
   │    ├── stats: [rows=1e-10]
   │    ├── cost: 2802.99333
   │    ├── fd: ()-->(13)
   │    ├── distribution: us-east1
   │    ├── select
   │    │    ├── columns: t.oid:2 t.typname:3 t.typrelid:13 t.typelem:14
   │    │    ├── stats: [rows=9.111111, distinct(2)=8.74649, null(2)=0, avgsize(2)=4, distinct(3)=9.11111, null(3)=0, avgsize(3)=4, distinct(13)=1, null(13)=0, avgsize(13)=4, distinct(14)=8.74649, null(14)=0.0911111, avgsize(14)=4, distinct(3,13)=9.11111, null(3,13)=0, avgsize(3,13)=8]
   │    │    ├── cost: 1497.66
   │    │    ├── fd: ()-->(13)
   │    │    ├── distribution: us-east1
   │    │    ├── prune: (2,14)
   │    │    ├── interesting orderings: (+2 opt(13))
   │    │    ├── scan pg_type [as=t]
   │    │    │    ├── columns: t.oid:2 t.typname:3 t.typrelid:13 t.typelem:14
   │    │    │    ├── stats: [rows=1000, distinct(2)=100, null(2)=0, avgsize(2)=4, distinct(3)=100, null(3)=0, avgsize(3)=4, distinct(13)=100, null(13)=10, avgsize(13)=4, distinct(14)=100, null(14)=10, avgsize(14)=4, distinct(3,13)=1000, null(3,13)=0, avgsize(3,13)=8]
   │    │    │    ├── cost: 1487.62
   │    │    │    ├── distribution: us-east1
   │    │    │    ├── prune: (2,3,13,14)
   │    │    │    └── interesting orderings: (+2)
   │    │    └── filters
   │    │         ├── t.typrelid:13 = 0 [outer=(13), constraints=(/13: [/0 - /0]; tight), fd=()-->(13)]
   │    │         └── t.typname:3 LIKE 'myt%' [outer=(3), constraints=(/3: [/'myt' - /'myu'); tight)]
   │    └── filters
   │         └── el.typarray:47 = t.oid:2 [outer=(2,47), constraints=(/2: (/NULL - ]; /47: (/NULL - ]), fd=(2)==(47), (47)==(2)]
   └── aggregations
        └── count-rows [as=count_rows:66]
```

So the optimizer certainly _thinks_ it's using the correct column. Maybe the catalog is providing the wrong ordinal for this column?

**Comment by yuzefovich** [comment]
I think I was wrong - `eqCol == 3` means that we're using `typelem` as the lookup key which is correct (for some reason I thought `eqCol` was 1-indexed). The problem here is that `typelem == 0` which we use as `oid` when looking up into the `pg_type_oid_idx`. There, we cannot find a pre-defined type for the 0 oid, and we treat it as of not a user-defined type as of 5bb546030c50c569a93830b04b080119748ced3f. So it appears that the virtual index itself is incorrectly implemented. Interestingly, PG also has `typelem == 0` for this enum.

**Comment by yuzefovich** [comment]
We looked into this issue during collab session. I was wrong again - the problem is in the execution, fix incoming.
