### ISSUE TITLE
22.2 Acceptance testing - Surface EXPLAIN plan for statement execution insights

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#88093]
https://www.figma.com/file/xpnRkP9cLXERVceRC4cec4/22.2_SQL-obsrv_query-performance?node-id=1086%3A72736

Jira issue: CRDB-19679

Epic CRDB-20388

**Comment by maryliag** [comment]
@xinhaoz this can probably be a quick one for you, since you did very similar on https://github.com/cockroachdb/cockroach/pull/89021
