### ISSUE TITLE
An unexpected error in `LEFT LOOKUP JOIN`

### ISSUE THREAD

**Issue by bajinsheng** [cockroachdb/cockroach#88120]
**Describe the problem**

An unexpected error in `LEFT LOOKUP JOIN`.

**To Reproduce**

```sql
CREATE TABLE t0 (c0 INT);
CREATE TABLE t1 (c0 INT);
SELECT * FROM t0 LEFT LOOKUP JOIN t1 ON t0.c0=t1.c0; --ERROR: could not produce a query plan conforming to the LOOKUP JOIN hint
```

**Expected behavior**
Referring to the same [document](https://www.cockroachlabs.com/docs/v22.1/cost-based-optimizer#join-hints), I think the error should not appear in `LEFT LOOKUP JOIN`?
**Additional data / screenshots**

**Environment:**
 - CockroachDB version [87ed064dc23eab6948ee8a07e8507f150bda0e44]
 - Server OS: [Ubuntu 20.04]
 - Client app [`cockroach sql`]

**Additional context**

Jira issue: CRDB-19697

**Comment by DrewKimball** [comment]
Hi @bajinsheng, thanks for posting. In order for cockroachdb to perform a lookup-join, there has to be a suitable index on the "lookup" side of the join (`t1` in this case). If you add an index on `t1.c0`, you should be able to plan this query with a lookup-join.

**Comment by mgartner** [comment]
This is expected behavior. Some of the join and index hints we allow can cause queries to fail when the optimizer cannot generate a plan that conforms to the hint. As another example, you can't force a partial index to be scanned when the query filter does not imply its predicate:

```
defaultdb> CREATE TABLE t (i INT, INDEX idx (i) WHERE i > 0);
CREATE TABLE

defaultdb> SELECT * FROM t@idx;
ERROR: index "idx" is a partial index that does not contain all the rows needed to execute this query
SQLSTATE: 42809
```

I'm going to close this issue, but let us know if you have any questions.

**Comment by rytaft** [comment]
This does seem like a possible opportunity to improve either our docs or provide a hint along with the error message. cc @taroface in case you have ideas.

**Comment by taroface** [comment]
Our `JOIN` doc already mentions the index requirement: https://www.cockroachlabs.com/docs/v22.1/joins.html#lookup-joins

However, I wonder if the [optimizer doc](https://www.cockroachlabs.com/docs/v22.1/cost-based-optimizer.html) could do with a section that explains why `could not produce a query plan` errors most commonly occur? If this seems useful, I can file a DOC ticket.

**Comment by rytaft** [comment]
Sounds useful -- thanks!
