### ISSUE TITLE
storage: non-preemptive snapshots seem to be untested

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#8814]
According to coveralls, the [codepath for applying a non-preemptive snapshot in storage/store.go](https://coveralls.io/builds/7595436/source?filename=storage%2Fstore.go#L2440) isn't covered by any tests. I think there should be unit tests that cover this important case.

**Comment by tschottdorf** [comment]
That's interesting and means preemptive snapshots must be working extremely well!

**Comment by tamird** [comment]
Acceptance tests are not instrumented by coverage tools, right?

**Comment by jordanlewis** [comment]
That's correct.

**Comment by jordanlewis** [comment]
Fixed by #8831
