### ISSUE TITLE
builtins: check_consistency should require admin role

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#88224]
**Describe the problem**

`crdb_internal.check_consistency`[^1] can be invoked by regular users (it's unsupported for tenants).

It's an expensive operation and we should probably gate it away.

I'm not exactly sure how to do that since it's a generator function and I wasn't able to find precedent. Happy to do this myself given some pointers.

[^1]: https://github.com/cockroachdb/cockroach/blob/19c95242e94595ec68ce6b2dbbf54572e1b9cfb7/pkg/sql/sem/builtins/generator_builtins.go#L395-L418

Jira issue: CRDB-19733

**Comment by rafiss** [comment]
Thanks for filing. Looks like we missed the generator builtins when we had CRDB-17355 🤦

**Comment by rafiss** [comment]
We can toss in something like this below the check for running on the system tenant.

```
				isAdmin, err := ctx.SessionAccessor.HasAdminRole(ctx.Context)
				if err != nil {
					return nil, err
				}
				if !isAdmin {
					return nil, errInsufficientPriv
				}
```

see also https://github.com/cockroachdb/cockroach/blob/2c18ed348f50ec70fc44c96d084ef56896e5fafa/pkg/sql/sem/builtins/builtins.go#L4521
