### ISSUE TITLE
*,kvtenantccl,testcluster: tenant authorization should be exercised in tests

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#88228]
**Is your feature request related to a problem? Please describe.**

When setting up the test cluster, we seem not to wire up the code paths for tenant authorization to KV. That leads to hard-to-find bugs because tests which think they exercise tenant logic don't exercise the authorization logic.

**Describe the solution you'd like**
Ensure that the testcluster uses the same authorization checks that we use in the wild. 

Jira issue: CRDB-19736
Epic: CRDB-18499

**Comment by knz** [comment]
this has been addressed.
