### ISSUE TITLE
cdc: changefeeds with AS SELECT * panic when encoding a delete message

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#88239]
Changefeeds panic when using the default bare envelope and json formatter and trying to encode an empty projection.

Jira issue: CRDB-19743

**Comment by HonoreDB** [comment]
The fix will probably be in a backport of either https://github.com/cockroachdb/cockroach/pull/88064 or https://github.com/cockroachdb/cockroach/pull/88241

**Comment by miretskiy** [comment]
Addressed via https://github.com/cockroachdb/cockroach/pull/88311
