### ISSUE TITLE
SELECT FOR UPDATE description in docs is incorrect

### ISSUE THREAD

**Issue by msirek** [cockroachdb/cockroach#88247]
**Describe the problem**
The description of [SELECT FOR UPDATE](https://www.cockroachlabs.com/docs/v22.1/select-for-update.html) says:
> It works by locking the rows returned by a [selection query](https://www.cockroachlabs.com/docs/v22.1/selection-queries), such that other transactions trying to access those rows are forced to wait for the transaction that locked the rows to finish.

This is how it works in postgres, but not in cockroach. It's not the rows returned which are locked, but the rows that are scanned. For example:
In one sql session, issue:
```
CREATE TABLE t1 (a int PRIMARY KEY, b int, c int, INDEX c_idx(c));
INSERT INTO t1 SELECT g,g,g FROM generate_series(1,10000) g(g);
BEGIN;
SELECT * FROM t1 WHERE b = 1 FOR UPDATE;
```
In one another sql session, issue:
```
UPDATE t1 SET b=-2 WHERE b = 2;
```
The update statement blocks even though the selection query did not return the row that is being updated.  The SELECT ... FOR UPDATE statement is doing a full scan, so it's actually locking all rows in the table. 

Jira issue: CRDB-19746

**Comment by yuzefovich** [comment]
@nvanbenschoten is this expected behavior of SELECT FOR UPDATE?

**Comment by nvanbenschoten** [comment]
@msirek is correct that this is the current behavior in CockroachDB. It's closer to a bug than expected behavior — see https://github.com/cockroachdb/cockroach/issues/75457.

**Comment by rytaft** [comment]
@taroface just added docs-known-limitation tag FYI

**Comment by rytaft** [comment]
actually, closing this as a dup of https://github.com/cockroachdb/cockroach/issues/75457. Will add label to that one
