### ISSUE TITLE
sql/stats: TestAdjustCounts is flakey

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#88249]
**Describe the problem**

It failed here on a PR which only touches a comment. 

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/6540367?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true&expandBuildDeploymentsSection=true

Jira issue: CRDB-19747

**Comment by knz** [comment]
also found here https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/6542603?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

**Comment by yuzefovich** [comment]
Fix incoming.
