### ISSUE TITLE
cli/sql: the input parser for `\set` is confusing

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#88270]
Reported by @nvanbenschoten 

When one attempts to enter `\set ...` (FIXME: example missing), a confusing error message is printed.

This should be improved.

Jira issue: CRDB-19758

**Comment by knz** [comment]
@nvanbenschoten can you remind me what was the syntax that was giving you grief?

**Comment by nvanbenschoten** [comment]
The syntax that was giving me grief was that `\set auto_trace=on` succeeds but `\set auto_trace = on` does not.
