### ISSUE TITLE
kvserver: harden lease-upgrade logic

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#88301]
**Is your feature request related to a problem? Please describe.**

In https://github.com/cockroachdb/cockroach/pull/85629 we changed our lease transfer protocol to only ever transfer expiration-based leases, and have recipients later upgrade them to the more efficient epoch based ones. This was done to limit the effects of ill-advised lease transfers since the incoming leaseholder would need to recognize itself as such within a few seconds -- so we wanted this upgrade happen after having received the lease. This issue tracks some hardening work we want to do before ship the release (tracking using the GA-blocker label).

- [x] Version gate logic to transfer out expiration based leases, and write a test. We don't want to transfer expiration based leases to 22.1 nodes that don't know to upgrade them immediately (done in [#88408](https://github.com/cockroachdb/cockroach/pull/88408)).
- [x] Add cluster setting to disable this code out of an abundance of caution (done in [#88408](https://github.com/cockroachdb/cockroach/pull/88408)).
- [ ] Consider retaining the same lease sequence number across the lease upgrade process (might need to account for [this logic](https://github.com/cockroachdb/cockroach/blob/4d6693190c7e9d70119e461d3d0def22131a2329/pkg/kv/kvserver/replica_proposal.go#L246-L249)). The change in sequence numbers causes us to reject requests proposed under the old lease, which seems unnecessary.

Jira issue: CRDB-19766

**Comment by nvanbenschoten** [comment]
@irfansharif should we remove the GA blocker label from this issue? Have we found a low-risk way of addressing the final point here?

**Comment by irfansharif** [comment]
I haven't looked into yet, but I don't think that warrants a GA-blocker (removed). I'd be ok addressing it on master, letting it bake, and backporting to a point release after some confidence.

**Comment by nvanbenschoten** [comment]
> Consider retaining the same lease sequence number across the lease upgrade process (might need to account for [this logic](https://github.com/cockroachdb/cockroach/blob/4d6693190c7e9d70119e461d3d0def22131a2329/pkg/kv/kvserver/replica_proposal.go#L246-L249)). The change in sequence numbers causes us to reject requests proposed under the old lease, which seems unnecessary.

Rediscoverd and subsumed by https://github.com/cockroachdb/cockroach/issues/117630.

Closing this issue, as the other two tasks have been completed.
