### ISSUE TITLE
storage: slow SST `NextKey()` scans during restore

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#88329]
Backup restoration uses an SST iterator that multiplexes several input SSTs, and then scans across them using  `NextKey()`. `pebbleIterator` will try to step once, and if it's not on a new key then it will seek:

https://github.com/cockroachdb/cockroach/blob/4cf84e01b80ab2b0d8616bfe3714c695b53e170e/pkg/storage/pebble_iterator.go#L487-L492

However, this has been seen to be very expensive. Pebble itself has an optimization to step rather than seek if the target is nearby, but no such optimization exists for the SST iterator. Furthermore, if the SSTs are exhausted, the SST reader will attempt to reseek the SST, which is very expensive.
 
<img width="1660" alt="Screenshot 2022-09-07 at 18 56 47" src="https://user-images.githubusercontent.com/644420/191447061-3e0c43d8-32de-45b5-8148-953e1ba6a557.png">

We need to improve performance here.

Jira issue: CRDB-19772

Epic CRDB-20465

**Comment by erikgrinaker** [comment]
Fix in progress here: https://github.com/cockroachdb/pebble/pull/1960

**Comment by jbowens** [comment]
Resolved by #88354 (master) and #88584 (22.2).

**Comment by jbowens** [comment]
exalate reopened

**Comment by nicktrav** [comment]
We're going to re-run the benchmarks to confirm that recent fixes made an impact here.
