### ISSUE TITLE
sql: DROP DATABASE of empty db fails with Multi-Regions enabled

### ISSUE THREAD

**Issue by odessit55** [cockroachdb/cockroach#88351]
When a database is "multi-regional" - need to use DROP DATABASE dbname CASCADE as it is not empty - has multi-region object in "empty" database
**To Reproduce**
CREATE DATABASE alex PRIMARY REGION "US_EAST-1"
REGIONS "US_EAST-1","US_EAST-2","US_WEST-1","US_WEST-2" SECONDARY REGION "US_EAST-2"; 

drop database alex;
ERROR: rejected (sql_safe_updates = true): DROP DATABASE on non-empty database without explicit CASCADE
SQLSTATE: 01000

**Expected behavior**
DROP DATABASE alex 
should work

**Environment:**
 - CockroachDB version v22.2.0.3-alpha
 - Server OS: Ubuntu
 - Client app `cockroach sql`

**Additional context**
What was the impact?  There is easy work around by using DELETE... CASCADE

Jira issue: CRDB-19783

**Comment by rafiss** [comment]
The reason it can't be dropped is because making a database multiregion requires creating a region enum type in that database. In this case, since there's a clear workaround, I don't think we will prioritize this.
