### ISSUE TITLE
backupccl: TestBackupRestoreDuringUserDefinedTypeChange panics within tenant 

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#88381]
To reproduce, stress the test on top of https://github.com/cockroachdb/cockroach/pull/88271, with DisableTenantTestTenant set to false.

See test failure artifacts [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=6543458&tab=buildResultsDiv&buildTypeId=Cockroach_BazelEssentialCi). 

Fresh build reveals more subtests hit the same panic: https://teamcity.cockroachdb.com/viewLog.html?buildId=6576285&buildTypeId=Cockroach_BazelEssentialCi

Jira issue: CRDB-19794

**Comment by stevendanna** [comment]
It _looks_ to me like the panic here is actually a timeout.  My suspicion here is that our testing hooks aren't property flowing through to the testing server so we are waiting forever on one of these channel selects.

**Comment by ajwerner** [comment]
I'm taking this off the schema board.
