### ISSUE TITLE
Correlate schema and plan changes in the fingerprint details view

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#88412]
We should provide an experience in the fingerprint (statements and transactions) details pages that allow users to quickly determine when schema or plan changes impact the execution stats of a statement/transaction over time. 

User flow: User sees execution latency spike at a specific time interval. User discovers it's due to a plan change (or an index was added). User drills into the change to determine if expected or an issue. 

Jira issue: CRDB-19805

**Comment by maryliag** [comment]
We have info of stats per plan on the statement details page, making it possible to see the differences
