### ISSUE TITLE
storage: Replace our use of the deprecated rocksdb::GetOptions builder

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#8849]
In an attempt to fix https://github.com/cockroachdb/cockroach/issues/8784, we bumped our version of rocksdb from 4.8 to 4.9. Unfortunately, in 4.9, the rocksdb maintainers removed the Options builder that we've been using. In https://github.com/cockroachdb/cockroach/pull/8815, I just copied the logic into our repo as a quick band-aid to see whether 4.9 fixed our problems, but we should figure out a more appropriate chunk of logic to maintain longer-term.

The rocksdb maintainers offered some advice in https://reviews.facebook.net/D59319, and @petermattis has been nominated behind his back to own looking into this further :)

**Comment by petermattis** [comment]
I'm not sure if there is anything to be done in the short term. Copying the deleted code and using it seems fine for now. Any changes to the options need to be done with a large amount of performance testing.
