### ISSUE TITLE
A notice to de-emphasize usage should be displayed when doing a SHOW on any sql.defaults setting

### ISSUE THREAD

**Issue by dikshant** [cockroachdb/cockroach#88520]
**Is your feature request related to a problem? Please describe.**
Currently we show a notice when trying to do a `SET` on a `sql.defaults` cluster setting. The idea here is to de-emphasize the usage of sql.defaults.
```
root@localhost:26257/defaultdb> SET CLUSTER SETTING sql.defaults.datestyle=1;
NOTICE: setting global default sql.defaults.datestyle is not recommended
HINT: use the `ALTER ROLE ... SET` syntax to control session variable defaults at a finer-grained level. See: https://www.cockroachlabs.com/docs/v22.2/alter-role.html#set-default-session-variable-values-for-a-role
SET CLUSTER SETTING

Time: 112ms total (execution 112ms / network 1ms)
```

However we should also have a notice in place when a user runs a SHOW on a particular sql.defaults setting. For example:
```
root@localhost:26257/defaultdb> SHOW CLUSTER SETTING sql.defaults.distsql;
  sql.defaults.distsql
------------------------
  auto
(1 row)


Time: 1ms total (execution 1ms / network 0ms)
```

**Describe the solution you'd like**

It would be nice to have a notice de-emphasizing the usage of sql.defaults when used in conjunction with SELECT to discourage usage even more.

Jira issue: CRDB-19963

**Comment by Gabrielopesantos** [comment]
I have never used CockroachDB but this seems an interesting issue. Can I take it?
I already investigated a little and from what I understood, a simple way to "fix" this issue would could be adding an if clause such as this [one](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/set_cluster_setting.go#L217) in this [function](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/show_cluster_setting.go#L115)?

**Comment by rafiss** [comment]
@Gabrielopesantos that's right! feel free to work on it, and thanks for your interest. You'll want tests similar to the ones added in https://github.com/cockroachdb/cockroach/pull/80548

Please read our contributing guidelines: https://wiki.crdb.io/wiki/spaces/CRDB/pages/73204033/Contributing+to+CockroachDB

**Comment by Gabrielopesantos** [comment]
Thanks for sharing a previous PR with tests but it seems that they were already removed.
Here's the commit: https://github.com/cockroachdb/cockroach/commit/02c01ae991a429e3be58959b4da4ed7a47ef3842

**Comment by quanuw** [comment]
Hi @Gabrielopesantos, are you still working on this? If not, can I take a look into this?

**Comment by Gabrielopesantos** [comment]
Hey @quanuw, I intended to continue with the issue when I got an answer from the contributors about the tests. If you think you can do it, without requiring the answer about the tests, feel free to take it.

**Comment by rafiss** [comment]
https://github.com/cockroachdb/cockroach/commit/02c01ae991a429e3be58959b4da4ed7a47ef3842 was made because for the `backupccl` tests, there's no need for us to check this NOTICE. instead, let's make new tests in pkg/sql/logictest/testdata/logic_test/cluster_settings, and use the `noticetrace` directive. See an example here: https://github.com/cockroachdb/cockroach/blob/d9cc084baa9892e28fb7211bf715e086170344f5/pkg/sql/logictest/testdata/logic_test/alter_table#L1879
