### ISSUE TITLE
server: Health check endpoint returns healthy when main serving port is unresponsive

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#8852]
This makes the health check endpoint (`$HOST:8080/_admin/v1/health`) not particularly useful. When I say the "main serving port is unresponsive", I'm specifically referring to the condition in #8784, where the 26257 port won't respond to requests and processing seems to be stuck on a deadlock in rocksdb.

My initial attempt at setting up health checks in our example Kubernetes deployment was to use this endpoint. I could instead set up a health check in our Kubernetes config that actually runs a SQL command, but it seems like this fixing this endpoint would be more useful to more people.

Related to #3726.

Example of what the health endpoint returns when on a deadlocked instance:

```
# curl -i localhost:8080/_admin/v1/health
HTTP/1.1 200 OK
Cache-Control: no-cache
Content-Type: application/json
Date: Fri, 26 Aug 2016 15:43:53 GMT
Content-Length: 4

{

}
```

**Comment by a-robinson** [comment]
Also closely related to https://github.com/cockroachdb/cockroach/issues/5303

**Comment by tamird** [comment]
Yeah, this endpoint is just a stub at the moment. Care to take this issue?

**Comment by a-robinson** [comment]
Should I self-assign it even if it's not something I'm likely to get to super soon? Some past projects I've been on have preferred to leave things unassigned if you weren't actively working on it or at least going to start soon, and am wondering what our general approach is at cockroach.

**Comment by tamird** [comment]
That's our approach as well - leave it unassigned until you're ready to
start work.

**Comment by dt** [comment]
we usually leave things unassigned if they aren't being worked on soon.

One option in that case is to unassign but leave a comment including an @-mention of yourself -- then it'll show up on your mentioned issues dashboard (https://github.com/issues/mentioned) and is a little easier to keep track of.

**Comment by tamird** [comment]
In this particular case, it will also show up in
https://github.com/cockroachdb/cockroach/issues/created_by/a-robinson and
https://github.com/issues.

**Comment by a-robinson** [comment]
Ack, thanks guys.

@a-robinson

**Comment by a-robinson** [comment]
@tamird - I hope to set aside a Friday to fix this sometime and was wondering if you know of any existing metrics/signals available that could be used for this or if fixing this will involve coming up with a new indicator of health?

**Comment by tamird** [comment]
I don't of anything existing that would serve this purpose. We'd probably want to base health on ability to query meta1? That's somewhat arbitrary.
