### ISSUE TITLE
sql: Support ALTER TABLE __ ADD CONSTRAINT __ FOREIGN KEY __ statements

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#8855]
The `ALTER TABLE __ ADD CONSTRAINT __ FOREIGN KEY __` statement type is used by a few different ORMs including Hibernate to manage FK constraints. It is currently [unsupported](https://github.com/cockroachdb/cockroach/blob/54029990e178b2d099acc5c28317eb277fce9b22/sql/alter_table.go#L127) by CockroachDB.

This is related to the larger issue in https://github.com/cockroachdb/cockroach/issues/8773, but I wanted to split it out into a separate issue for easier tracking.

**Comment by nvanbenschoten** [comment]
This has been addressed, right @dt?

**Comment by dt** [comment]
sort of: we support the statement, but it adds it `unvalidated` -- meaning it doesn't check any on-disk data that already exists -- and we don't currently support VALIDATE on FK constraints (just need to figure out how to write a JOIN to do it).

**Comment by petermattis** [comment]
Marking as Later, though open to moving this to 1.0 if it is needed for our targeted ORMs.

**Comment by dt** [comment]
To update my last comment: we now have (slow, limited) support for VALIDATE on FKs. As discussed in #13681, hooking that up to a multi-step, schema-change based `ADD CONSTRAINT` impl is what's left to do here.

**Comment by vivekmenezes** [comment]
assigning to bram for now. We still need to discuss if we absolutely need to get this done for 2.0

**Comment by vivekmenezes** [comment]
Hey folks I'd like to really understand how this is blocking the adoption of Hibernate. @jordanlewis @nvanbenschoten any
 thoughts?

**Comment by jordanlewis** [comment]
I'm surprised that it's blocking the adoption of Hibernate. We do support this statement.

**Comment by knz** [comment]
I'm seeing in airtable that this is on the roadmap for 2.1, not 2.0. @awoods187 care to chime in?

**Comment by nstewart** [comment]
@awoods187 can you confirm this is still blocking Hibernate? I'm inclined to punt any incremental work here indefinitely. @dt thinks we are all set with respect to ORMs

**Comment by awoods187** [comment]
cc @BramGruneir Can you help me confirm @nstewart's comment above for whether or not this is a blocker for Hibernate?

**Comment by BramGruneir** [comment]
I've seen this a lot during testing, and we fail mostly due to not having an index, which is a different issue. See #26738.

I don't believe that this is currently a blocker, there are many more important issues to deal with.

But my approach was all about running their test suite.  I didn't try doing any fancy schema changes or a project with an automated test setup, which is where I think this would crop up.

**Comment by nstewart** [comment]
@vivekmenezes I'm removing this from the 2.1 milestone. feel free to comment if you disagree.

**Comment by BramGruneir** [comment]
I just hit this using ECTO's migrate.  Looks like we should press forward and get this fixed, seems like a relatively easy win, since there is no worry about a constraint violation on a new column.

This isn't a problem that a user would encounter when running queries directly, but is a problem that most migration tools could hit.

**Comment by BramGruneir** [comment]
Ah, this is the wrong issue.  I was looking at 

ALTER TABLE ADD COLUMN with a REFERENCES column.

That unimplemented error links to this issue, but this is not the correct issue and I can't find the real issue for it.  I'll file one.

**Comment by knz** [comment]
@BramGruneir can you then also update the telemetry link?

**Comment by BramGruneir** [comment]
Yep.  I mentioned it in the other issue.  I'll send a quick or when I have
a moment.

**Comment by jordanlewis** [comment]
This issue is fixed.

```
root@127.0.0.1:59662/defaultdb> create table a (a int primary key);
CREATE TABLE

Time: 3.601ms

root@127.0.0.1:59662/defaultdb> create table b (a int primary key);
CREATE TABLE

Time: 2.615ms

root@127.0.0.1:59662/defaultdb> alter table b add constraint test foreign key (a) references a(a);
ALTER TABLE

Time: 54.882ms
```

**Comment by jordanlewis** [comment]
(It's also already documented: https://www.cockroachlabs.com/docs/stable/add-constraint.html#add-the-foreign-key-constraint-with-cascade)
