### ISSUE TITLE
Use different workload seeds by default

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#88566]
Currently, our workloads use a static default for pseudo-random number generator seed, typically `1`. For example, see `bank` [1] and `tpcc` [2] workloads. To increase the chances of finding anomalous behavior, we should be using different random seeds by default.

This has recently been done for the `rand` workload [3].

In the case of workloads used in automated tests (such as `bank` and `tpcc`), this would also mean that the tests should make sure to pass the same seed to `init` and `run`.

[1] https://github.com/cockroachdb/cockroach/blob/master/pkg/workload/bank/bank.go#L69
[2] https://github.com/cockroachdb/cockroach/blob/master/pkg/workload/tpcc/tpcc.go#L187
[3] https://github.com/cockroachdb/cockroach/pull/88362

Jira issue: CRDB-19959

**Comment by srosenberg** [comment]
Pasting the note from the PR, so we don't forget,

> A time-based seed is not as uniform as a crypto-based seed. cli.Main is already using a seed by reading it from /dev/urandom [1]. I think we should do the same in all the workloads.

[1] https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/cli.go#L53
