### ISSUE TITLE
cluster_execution_insights should be split into statement vs transaction level

### ISSUE THREAD

**Issue by j82w** [cockroachdb/cockroach#88563]
Currently everything in the cluster_execution_insights is based on statement level. A new table should be created for the transaction level. Having a separate tables provides better flexibility, and makes it easier for user to understand. It also will allow the ability to add transaction and statement specific fields, and it aligns with the ui design making it easier to display.

`crdb_internal.cluster_statement_execution_insights`
`crdb_internal.cluster_transaction_execution_insights`

Jira issue: CRDB-19915

Epic CRDB-20388

**Comment by ericharmeling** [comment]
@j82w @xinhaoz 
Was this resolved by https://github.com/cockroachdb/cockroach/pull/94720?

**Comment by maryliag** [comment]
No longer a priority
