### ISSUE TITLE
backupccl: TestScheduleChainingLifecycle is flaky

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#88575]
**Describe the problem**

Observed in [this CI run](https://teamcity.cockroachdb.com/viewLog.html?buildId=6583048&buildTypeId=Cockroach_BazelEssentialCi).

```console
[TestScheduleChainingLifecycle/cluster] Failed
[23:58:19][TestScheduleChainingLifecycle/cluster] === RUN   TestScheduleChainingLifecycle/cluster
    schedule_pts_chaining_test.go:86: 
        	Error Trace:	/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/6617/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/backupccl/backupccl_test_/backupccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/backupccl/schedule_pts_chaining_test.go:86
        	            				/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/6617/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/backupccl/backupccl_test_/backupccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/backupccl/schedule_pts_chaining_test.go:178
        	Error:      	Not equal: 
        	            	expected: hlc.Timestamp{WallTime:1663890902552441000, Logical:0, Synthetic:false}
        	            	actual  : hlc.Timestamp{WallTime:1663890902571559000, Logical:0, Synthetic:false}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,3 +1,3 @@
        	            	 (hlc.Timestamp) {
        	            	- WallTime: (int64) 1663890902552441000,
        	            	+ WallTime: (int64) 1663890902571559000,
        	            	  Logical: (int32) 0,
        	Test:       	TestScheduleChainingLifecycle/cluster
    --- FAIL: TestScheduleChainingLifecycle/cluster (1.00s)
```

**To Reproduce**

Attempted to repro locally via `--stress`, but couldn't observe a failure in a ~10 min run.

```bash
$ ./dev test ./pkg/ccl/backupccl --filter TestScheduleChainingLifecycle/cluster --stress
```

Jira issue: CRDB-19847

**Comment by andreimatei** [comment]
this happened to me too

**Comment by msbutler** [comment]
@adityamaru I see that you were assigned to the [22.2 issue](https://github.com/cockroachdb/cockroach/issues/91640). Have you looked into this yet? If not, i can take a look.

**Comment by adityamaru** [comment]
Haven't looked at it yet, go for it! Thank you and let me know if you want me to take over at any point.

**Comment by msbutler** [comment]
I haven't been able to repro the failure under stress, but I'll describe what Nick's failure indicates:

In the test, we run an incremental backup schedule. Once the first incremental backup finishes, we expect the inc schedule PTS to update from the full backup's endtime to the incremental backup's endtime.
https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/backupccl/schedule_pts_chaining_test.go#L178

In nick's failure, the expected pts time is 19 Milliseconds less than the actual PTS on the schedule. The mystery is why the actual PTS is higher than expected.

**Comment by stevendanna** [comment]
In the most recent failure of this seen on teamcity [Unit Test 7573004](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/7573004?buildTab=overview&showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildDeploymentsSection=true&expandBuildTestsSection=true#%2Ftmp%2F_tmp%2F8bf143f6dc53869837d46111c718159a;%2Ftmp%2F_tmp%2F74c8d458e0944e34dc061e5c7eb9279e;%2Ftmp%2F_tmp%2F36248a3ac7ed2bff7876feddecd4908d)

One interesting thing is that from the test output, it appears we expect a full backup to run, followed, by an incremental, followed by a full.

But, in the failing case here, we see that there are two full backups scheduled before the incremental:

```
I221117 23:55:12.688043 720485 ccl/backupccl/schedule_exec.go:94 â‹® [schedule=814805524865744897] 132  Starting scheduled backup 814805524865744897: â€¹BACKUP INTO 'nodelocal://1/cluster' AS OF SYSTEM TIME '2022-11-17 23:55:12.137172+00:00' WITH revision_history = true, detachedâ€º
....
I221117 23:55:13.071353 720485 ccl/backupccl/schedule_exec.go:94 â‹® [schedule=814805524865744897] 184  Starting scheduled backup 814805524865744897: â€¹BACKUP INTO 'nodelocal://1/cluster' AS OF SYSTEM TIME '2022-11-18 00:00:00+00:00' WITH revision_history = true, detachedâ€º
....
I221117 23:55:13.090470 720485 ccl/backupccl/schedule_exec.go:94 â‹® [schedule=814805524856340481] 186  Starting scheduled backup 814805524856340481: â€¹BACKUP INTO LATEST IN 'nodelocal://1/cluster' AS OF SYSTEM TIME '2022-11-18 00:00:00+00:00' WITH revision_history = true, detachedâ€º
```
