### ISSUE TITLE
dbconsole: fetching a profile from Advanced Debug page no longer works

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#88587]
I have a 3 node roachprod cluster running TPCC, and when I tried to fetch a profile (cpu or heap) for node 1 from the Advanced Debug page (Profiling UI section), I get this
![Screen Shot 2022-09-23 at 10 14 10 AM](https://user-images.githubusercontent.com/5135385/192017627-e8355a8c-e463-46f7-b8a3-b4785fdd0816.png)
It's possible that something is not set up correctly on my side (I'm using a new laptop this week), but more likely it's a regression. I'm running on 14f11eb10bfb2ebde6a9e04df485ea208d7cbb6d. Conservatively marking as GA-blocker.

**Comment by ajwerner** [comment]
duplicates https://github.com/cockroachdb/cockroach/issues/83623
