### ISSUE TITLE
import: improve allocations during TPCC fixture import

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#88589]
I have a 3 node cluster and imported a TPCC fixture for 875 warehouses (`./cockroach workload fixtures import tpcc --warehouses=875` on node 1). When looking at the `alloc space` heap profile we see the following:
![Screen Shot 2022-09-23 at 10 28 52 AM](https://user-images.githubusercontent.com/5135385/192024053-d37147f5-d507-404a-831c-9f1ead177c28.png)
The largest allocation is for the rand source that is used in evaluating `gen_random_uuid` builtin. This seems pretty bad and probably could be improved.
[heap.pb.gz](https://github.com/cockroachdb/cockroach/files/9636043/heap.pb.gz)

Jira issue: CRDB-19860

**Comment by ajwerner** [comment]
Is this just https://github.com/cockroachdb/cockroach/pull/88593?

**Comment by yuzefovich** [comment]
Yeah, seems like it.
