### ISSUE TITLE
cli: `\df` command to list or show all user defined functions

### ISSUE THREAD

**Issue by michae2** [cockroachdb/cockroach#88597]
It would be nice to have a dedicated command to show all user defined functions in a database or schema.
- PostgreSQL's psql has the [`\df` command](https://www.postgresql.org/docs/current/app-psql.html#APP-PSQL-META-COMMANDS).
  
  ```
  michae2=# \df
                         List of functions
   Schema | Name | Result data type | Argument data types  | Type
  --------+------+------------------+----------------------+------
   public | f2   | integer          |                      | func
   public | g    | integer          | a integer, b integer | func
   public | g    | integer          | i integer            | func
   public | m    | character        | f double precision   | func
   public | m    | character        | i integer            | func
   public | p    | boolean          | i integer            | func
  (6 rows)
  ```

- MySQL has the [`SHOW FUNCTION STATUS` statement](https://dev.mysql.com/doc/refman/8.0/en/show-function-status.html).

We do include user-defined functions in the output of `\hf` but this only gives the function name, not any additional information:

```
demo@127.0.0.1:26257/defaultdb> CREATE FUNCTION z () RETURNS INT IMMUTABLE LANGUAGE SQL AS $$ SELECT 1 $$;
CREATE FUNCTION


Time: 24ms total (execution 24ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> \hf
                            function
----------------------------------------------------------------
  _st_contains
  _st_containsproperly
  _st_coveredby
...
  with_max_staleness
  with_min_timestamp
  xor_agg
  z
(919 rows)


Time: 20ms total (execution 17ms / network 3ms)

demo@127.0.0.1:26257/defaultdb> \hf z
no help available for "z".
Try \hf with no argument to see available help.
```

As a workaround, we can query `pg_catalog.pg_proc`:

```
demo@127.0.0.1:26257/defaultdb> SELECT proname, prosrc FROM pg_catalog.pg_namespace n JOIN pg_catalog.pg_proc ON pronamespace = n.oid WHERE nspname = 'public';
  proname |  prosrc
----------+------------
  z       | SELECT 1;
(1 row)


Time: 17ms total (execution 17ms / network 0ms)
```

But this is a little annoying, and it would be nice to match psql.

This is on `v22.2.0-alpha.3-550-g099da40b73` (current tip of master).

Jira issue: CRDB-19851

Epic CRDB-17785

**Comment by chengxiong-ruan** [comment]
Thanks for filing the issue!
Yeah, it's definitely helpful to have the `\df` command to list all functions, and also `\df some_func_name`
Agreed that `SHOW FUNCTION STATUS` should be a separate issue. Though, I'm not sure if we need it by looking at some example outputs of this [mysql tutorial](https://www.tutorialspoint.com/mysql/mysql_show_function_status_statement.htm)

**Comment by michae2** [comment]
> Thanks for filing the issue! Yeah, it's definitely helpful to have the `\df` command to list all functions, and also `\df some_func_name` Agreed that `SHOW FUNCTION STATUS` should be a separate issue. Though, I'm not sure if we need it by looking at some example outputs of this [mysql tutorial](https://www.tutorialspoint.com/mysql/mysql_show_function_status_statement.htm)

Yeah, let's forget `SHOW FUNCTION STATUS` for now and just make this issue about `\df` 👍

**Comment by rafiss** [comment]
This is how `pgcli` implements `\df`:
```

            SELECT  n.nspname as "Schema",
                    p.proname as "Name",
                    pg_catalog.pg_get_function_result(p.oid)
                      as "Result data type",
                    pg_catalog.pg_get_function_arguments(p.oid)
                      as "Argument data types",
                     CASE
                        WHEN p.prokind = 'a' THEN 'agg'
                        WHEN p.prokind = 'w' THEN 'window'
                        WHEN p.prorettype = 'pg_catalog.trigger'::pg_catalog.regtype
                            THEN 'trigger'
                        ELSE 'normal'
                    END as "Type" 
            FROM    pg_catalog.pg_proc p
                    LEFT JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace
                            
            WHERE   pg_catalog.pg_function_is_visible(p.oid)  AND n.nspname <> 'pg_catalog'
                   AND n.nspname <> 'information_schema'  ORDER BY 1, 2, 4
```

and this is how `psql` implements `\df`:
```
SELECT n.nspname as "Schema",
  p.proname as "Name",
  pg_catalog.pg_get_function_result(p.oid) as "Result data type",
  pg_catalog.pg_get_function_arguments(p.oid) as "Argument data types",
 CASE p.prokind
  WHEN 'a' THEN 'agg'
  WHEN 'w' THEN 'window'
  WHEN 'p' THEN 'proc'
  ELSE 'func'
 END as "Type"
FROM pg_catalog.pg_proc p
     LEFT JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace
WHERE pg_catalog.pg_function_is_visible(p.oid)
      AND n.nspname <> 'pg_catalog'
      AND n.nspname <> 'information_schema'
ORDER BY 1, 2, 4;
```

We should be able to do something similar. It can be added similarly to https://github.com/cockroachdb/cockroach/blob/bfbd07b25db09089cf1fa79efe86cd5d78639cc7/pkg/cli/clisqlshell/sql.go#L1292
