### ISSUE TITLE
migrations: Add test where DMS creates tables on target

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#88595]
In 22.2 we've added support for DMS to create tables on the target.  I know that we've manually tested this, but it would be good if we also had an automated test to ensure that this functionality doesn't regress.  Did a bit of digging and can't seem to find one.  

It looks like it should be possible by setting up the [`FullLoadSettings`](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Tasks.CustomizingTasks.TaskSettings.html#CHAP_Tasks.CustomizingTasks.TaskSettings.Example) in the [`ReplicationTaskSettings`](https://docs.aws.amazon.com/dms/latest/APIReference/API_CreateReplicationTask.html)

**Comment by otan** [comment]
this I believe is the default and done automatically once https://github.com/cockroachdb/cockroach/pull/87392 was merged!
