### ISSUE TITLE
backupccl: investigate if TestBackupOnlyPublicIndexes does not properly backup all indices when run within tenant

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#88633]
To reproduce, stress the test on top of https://github.com/cockroachdb/cockroach/pull/88271, with DisableTenantTestTenant set to false, causing the following error: 

```
    backup_test.go:8393: 
        	Error Trace:	/private/var/tmp/_bazel_michaelbutler/13ba282fa2b19539d0c969c1113bb37c/sandbox/darwin-sandbox/2515/execroot/com_github_cockroachdb_cockroach/bazel-out/darwin-fastbuild/bin/pkg/ccl/backupccl/backupccl_test_/backupccl_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/backupccl/backup_test.go:8393
        	Error:      	Expect "/Tenant/10/Table/106/{1-3}" to match ".*/Table/106/{2-3}"
        	Test:       	TestBackupOnlyPublicIndexes
    panic.go:522: -- test log scope end --
FAIL
```

Jira issue: CRDB-19878

Epic CRDB-27613

**Comment by stevendanna** [comment]
Looking at the test I _think_ it is likely that this is because of the testing knobs problem in tenant tests.  A PR is out right now to make sharing the default so we won't have to update every test to account for that.

**Comment by msbutler** [comment]
unfortunately, even if I set `ShareMostTestingKnobsWithTenant` to true, the test still fails.

**Comment by msbutler** [comment]
take it!

**Comment by stevendanna** [comment]
This slipped through the cracks, but I spent some time on it this morning.  Overall, I think what is happening here is that when running under the system tenant, we AdminSplit at the start of the new index.  As a result of how export requests are processed, that changes the span bounds on the export request responses we get back, breaking the assertions.
