### ISSUE TITLE
Failed tests (21860): TestSplitSnapshotRace_SplitWins

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#8868]
https://circleci.com/gh/cockroachdb/cockroach/21860

```
I160827 11:25:20.251358 util/log/trace.go:64  reply error Increment ["a",/Min): key range "a"-"a\x00" could not be located within a range on store
W160827 11:25:20.251571 kv/dist_sender.go:816  key range "a"-"a\x00" could not be located within a range on store
I160827 11:25:20.253728 kv/dist_sender.go:1035  application error: key range "a"-"a\x00" could not be located within a range on store
I160827 11:25:20.253868 util/log/trace.go:64  reply error Increment ["a",/Min): key range "a"-"a\x00" could not be located within a range on store
W160827 11:25:20.254101 kv/dist_sender.go:816  key range "a"-"a\x00" could not be located within a range on store
panic: test timed out after 5m0s

```

**Comment by tamird** [comment]
Full failure with stacks: https://gist.githubusercontent.com/tamird/10ec57feab3c217aa29787402e3b7cb9/raw/d83fd2eaf36d6692429987d4f73010fbdd15dcf1/stacks.txt

This occurred on a child of b978203ec9a004f326f492126f1dad59df1f3bc4.

The test goroutine is `[runnable]` so something is catching an infinite retry loop. In this case, looks like DistSender is retrying on `*roachpb.RangeKeyMismatchError`.

cc @tschottdorf

**Comment by tamird** [comment]
Seen again in https://circleci.com/gh/tamird/cockroach/671. Stacks: https://gist.githubusercontent.com/tamird/88cbc53ff744f6486813c587b6cfc08d/raw/f2934f462934f214016fa4d8a0fb7823e361028e/testrace.log

Looks like the same symptom - `DistSender` is "stuck" in `[runnable]`.

**Comment by tamird** [comment]
OK, this does actually reproduce on GCE, though it wasn't easy.

```
tamird@gceworker17:~/src/github.com/cockroachdb/cockroach$ make stressrace PKG=./storage TESTS=TestSplitSnapshotRace_SplitWins TESTTIMEOUT=15s
...
5699 runs completed, 1 failures, over 11m43s
FAIL
Makefile:147: recipe for target 'stressrace' failed
make: *** [stressrace] Error 1
```

I recommend running it in `screen` to avoid dropped SSH sessions and using `tee` to log to a file (since `screen` doesn't keep an infinite buffer or at least I don't know how to scroll above the fold in `screen`): `screen make stressrace PKG=./storage TESTS=TestSplitSnapshotRace_SplitWins TESTTIMEOUT=15s | tee boom`.

**Comment by jordanlewis** [comment]
(`^A <ESC>` gets you into scrollback mode in screen which is like a read-only `vi`; you can set the buffer size with `-h n` on startup or `scrollback n` as a command from within `^A :` in screen)

**Comment by RaduBerinde** [comment]
Reproduced locally with high verbosity; we're indeed doing an endless retry of `RangeKeyMismatchError`. This block of messages keeps repeating:

```
I160830 14:49:51.662669 kv/leaseholder_cache.go:59  lookup lease holder for range 2: not found
I160830 14:49:51.663013 kv/dist_sender.go:1033  RPC reply: 
I160830 14:49:51.663097 util/log/trace.go:128  reply error Increment ["a",/Min): key range "a"-"a\x00" could not be located within a range on store
I160830 14:49:51.663275 kv/range_cache.go:494  evict cached descriptor: key="a" desc=range_id:2 start_key:"\005" end_key:"m" replicas:<node_id:4 store_id:4 replica_id:4 > replicas:<node_id:2 store_id:2 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > next_replica_id:5 
I160830 14:49:51.663373 kv/range_cache.go:494  evict cached descriptor: key=/Meta2/"a" desc=range_id:1 start_key:"" end_key:"\005" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I160830 14:49:51.663421 kv/range_cache.go:494  evict cached descriptor: key=/Meta1/"a" desc=<nil>
W160830 14:49:51.663494 kv/dist_sender.go:816  key range "a"-"a\x00" could not be located within a range on store
I160830 14:49:51.663558 kv/range_cache.go:322  lookup range descriptor: key="a"
I160830 14:49:51.663607 kv/range_cache.go:322  lookup range descriptor: key=/Meta2/"a"
I160830 14:49:51.672812 storage/replica_command.go:188  [s1,r1{/Min-/System/Max}] store=1:1 1{/Min-/System/Max}: executed RangeLookup command header:<key:"\002a" > max_ranges:8 consider_intents:true reverse:false : header:<num_keys:0 > ranges:<range_id:1 start_key:"" end_key:"\005" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 > , err=<nil>
I160830 14:49:51.672984 kv/dist_sender.go:1033  RPC reply: *roachpb.RangeLookupResponse
I160830 14:49:51.673279 kv/range_cache.go:584  adding descriptor: key=/Meta2/System/Max desc=range_id:1 start_key:"" end_key:"\005" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I160830 14:49:51.674048 storage/replica_command.go:188  [s1,r1{/Min-/System/Max}] store=1:1 1{/Min-/System/Max}: executed RangeLookup command header:<key:"\003a" > max_ranges:8 consider_intents:true reverse:false : header:<num_keys:0 > ranges:<range_id:2 start_key:"\005" end_key:"m" replicas:<node_id:4 store_id:4 replica_id:4 > replicas:<node_id:2 store_id:2 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > next_replica_id:5 > , err=<nil>
I160830 14:49:51.674162 kv/dist_sender.go:1033  RPC reply: *roachpb.RangeLookupResponse
I160830 14:49:51.674315 kv/range_cache.go:584  adding descriptor: key=/Meta2/"m" desc=range_id:2 start_key:"\005" end_key:"m" replicas:<node_id:4 store_id:4 replica_id:4 > replicas:<node_id:2 store_id:2 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > next_replica_id:5 
I160830 14:49:51.674406 kv/leaseholder_cache.go:59  lookup lease holder for range 2: not found
```

**Comment by RaduBerinde** [comment]
Added some more logs. Looks like we do a RangeLookup for key `a` and we get back a range for `start_key:"" end_key:"\005"`

```
W160830 15:44:47.361952 kv/dist_sender.go:816  key range "a"-"a\x00" could not be located within a range on store
I160830 15:44:47.361988 kv/range_cache.go:322  lookup range descriptor: key="a"
I160830 15:44:47.362027 kv/range_cache.go:322  lookup range descriptor: key=/Meta2/"a"
I160830 15:44:47.362694 storage/replica_command.go:188  [s1,r1{/Min-/System/Max}] store=1:1 1{/Min-/System/Max}: executed RangeLookup command header:<key:"\002a" > max_ranges:8 consider_intents:true reverse:false : header:<num_keys:0 > ranges:<range_id:1 start_key:"" end_key:"\005" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 > , err=<nil>

I160830 15:44:47.362866 kv/dist_sender.go:1033  RPC reply: *roachpb.RangeLookupResponse
I160830 15:44:47.362963 kv/dist_sender.go:1035  RangeLookupResponse: header:<num_keys:0 > ranges:<range_id:1 start_key:"" end_key:"\005" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 >
```

**Comment by bdarnell** [comment]
We're looking up `"a"`, which recurses into `/Meta2/"a"`; we find `/Meta2/"a"` in `["","\005"]` (as expected). Once we've found `/Meta2/"a"` there should be a second `RangeLookup` call for `"a"` itself.  We see the results of that in your previous message: `
I160830 14:49:51.674315 kv/range_cache.go:584  adding descriptor: key=/Meta2/"m" desc=range_id:2 start_key:"\005" end_key:"m" replicas:<node_id:4 store_id:4 replica_id:4 > replicas:<node_id:2 store_id:2 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > next_replica_id:5 
`

So the DistSender knows about three replicas of this range. Which one(s) is it sending to when it gets the KeyMismatchError?

**Comment by RaduBerinde** [comment]
So this is the problem as far as I can tell: when this condition hits, the first replica we try can't find the range. For some reason, we generate a range key mismatch error in this case: https://github.com/cockroachdb/cockroach/blob/master/storage/stores.go#L229

Unlike `RangeNotFoundError`, this is not an error for which we try other replicas (https://github.com/cockroachdb/cockroach/blob/master/kv/dist_sender.go#L1070), so we bubble up the error. For this particular error, DistSender keeps retrying forever.

I think `LookupReplica` should return a `RangeNotFoundError` in that case instead.. Am I missing any subtleties here? @tamird @tschottdorf

**Comment by RaduBerinde** [comment]
@bdarnell In SendNext we always see `nodeIndex=3` and don't try other replicas:
```
I160830 18:27:07.429131 storage/client_test.go:397  SendNext nodeIndex=3
```

**Comment by tamird** [comment]
RangeNotFoundError SGTM.

FWIW, this behaviour was introduced in 3f7ee718 (!), and before that a
simple unstructured error was returned.
