### ISSUE TITLE
storage: severe `CheckSSTConflicts` performance regressions slowing down import retries

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#88702]
[Microbenchmark comparisons](https://docs.google.com/spreadsheets/d/1XW2e2AambrbTIv4Otg6bMHLlISizPk5L7LQNZslo5OE/edit#gid=5) between 22.1 and 22.2 are showing severe performance regressions in `CheckSSTConflicts`. The `overlap=false/prefixSeek=true` cases have an 1800% regression, while the `overlap=false/prefixSeek=false` cases have 60-100% regressions. The former also have 12000% more allocations, which probably has something to do with it.

Upon closer look, there are multiple missing optimizations in `CheckSSTConflicts`. Without those optimizations, a TPC-H import retry with range tombstones enabled fails to succeed if the gc ttl is low, as each `AddSSTable` spends an increasingly longer amount of time (sometimes even over a minute) on the `CheckSSTConflicts` call. This issue covers both the microbenchmark optimizations and the more user-visible import retry wedging issue.

Jira issue: CRDB-19841

Epic CRDB-2624

**Comment by jbowens** [comment]
thanks, I'll look into this. Seems like it might explain some of what was observed #87309.
