### ISSUE TITLE
ccl/multitenantccl/tenantcostclient: TestSQLLivenessExemption flakes

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#88743]
**Describe the problem**

The test seems to fail as a side-effect of https://github.com/cockroachdb/cockroach/pull/87533. 

See https://github.com/cockroachdb/cockroach/blob/59a70ba8eb11cd3ce708ca85affc112a26b8741a/pkg/ccl/multitenantccl/tenantcostclient/tenant_side_test.go#L932-L933

In retrospect, I think setting the timeout to be on the order of the heartbeat interval was a mistake. It should probably be something related to the timeout duration. Maybe some combination thereof.

**Comment by ajwerner** [comment]
@aadityasondhi let's sort this flake before merging the backport?

**Comment by aadityasondhi** [comment]
>  I think setting the timeout to be on the order of the heartbeat interval was a mistake

When you mention timeout, are you talking about TTL set here (which I can see I forgot to uncomment when merging my PR) or are you talking about the timouts used for calls to create/update sessions here:
https://github.com/cockroachdb/cockroach/blob/59a70ba8eb11cd3ce708ca85affc112a26b8741a/pkg/sql/sqlliveness/slinstance/slinstance.go#L265

**Comment by aadityasondhi** [comment]
Was able to replicate locally when run with `--stress`. 
```
57 runs completed, 1 failures, over 7s
context canceled
```
```
--- FAIL: TestSQLLivenessExemption (0.63s)
    test_log_scope.go:161: test logs captured to: /Users/aadityasondhi/go/src/github.com/cockroachdb/cockroach/tmp/_tmp/cd6b537d257847226387a72b864251e8/logTestSQLLivenessExemption1538851179
    test_log_scope.go:79: use -show-logs to present logs inline
    test_server_shim.go:417: constructing session: operation "sqlliveness create session" timed out after 61ms (given timeout 50ms): could not insert session 53564e4363224d14a47171adef61ad85: aborted during DistSender.Send: context deadline exceeded
```
