### ISSUE TITLE
roachtest: stop local cluster when running acceptance tests in CI

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#88757]
If a local-cluster `roachtest` run is killed without having the chance to cleanup and subsequently invoked with `--local` again, then every test will fail the cluster creation process and not be run. We should make sure to destroy local clusters before running an acceptance test in CI.

Actual occurrence:

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_Tests_LocalRoachtest/6631095?showRootCauses=false&expandBuildChangesSection=true&showLog=6631095_738__expandAll&logFilter=debug

Jira issue: CRDB-19979

**Comment by srosenberg** [comment]
Any idea why we're only seeing this now? I.e., is it a new test which doesn't properly clean up or is it a rare infra. flake?

**Comment by renatolabs** [comment]
> Any idea why we're only seeing this now? I.e., is it a new test which doesn't properly clean up or is it a rare infra. flake?

Not sure why we're seeing this now -- I don't think it's because of a new test. `roachtest` tries to clean up after a test run, but if you interrupt that process, the cluster (local or not) will not be destroyed. Maybe a previous run of `roachtest` was abruptly interrupted for some reason (e.g., `SIGKILL`), and the local cluster was never destroyed.

This is easy to reproduce if you run the acceptance tests with `--local`, kill the process with `SIGKILL` (or two `SIGTERM` signals), and then try to run the acceptance tests again:

```console
% ./bin/roachtest run acceptance --local &
[1] 8197

% kill -9 8197
[1]+  Killed: 9               ./bin/roachtest run acceptance --local

% ./bin/roachtest run acceptance --local
--local specified. Overriding --parallelism to 1.
HTTP server listening on all network interfaces, port 8080.
19:06:15 main.go:527: test runner logs in: artifacts/_runner-logs/test_runner-1664305575.log
test runner logs in: artifacts/_runner-logs/test_runner-1664305575.log                          
19:06:15 test_runner.go:1164: [w0] Selected test: acceptance/build-analyze run: 1.
19:06:15 test_runner.go:383: [w0] Creating new cluster for test acceptance/build-analyze: n4cpu4
19:06:15 cluster.go:928: [w0] Attempting cluster creation (attempt #1/3)
19:06:15 test_runner.go:575: [w0] Unable to create (or reuse) cluster for test acceptance/build-analyze due to: cluster local already exists.
Unable to create (or reuse) cluster for test acceptance/build-analyze due to: cluster local already exists.
# ...
```
