### ISSUE TITLE
Add a new event type for when the identity of the current user is switched

### ISSUE THREAD

**Issue by logston** [cockroachdb/cockroach#88753]
**Describe the solution you'd like**

When [EXPERIMENTAL_AUDIT](https://www.cockroachlabs.com/docs/stable/sql-audit-logging.html) is enabled on a table, CRDB produces a log of actions taken on the table and the user who made those actions:

```
cockroachdb-2:cockroachdb I220329 01:36:07.392456 6995788@util/log/event_log.go:32 ⋮ [n3,client=‹123.123.123.123:45640›,hostssl,user=‹test›] 23445={"Timestamp":1648517767385257975,"EventType":"sensitive_table_access","Statement":"ALTER TABLE ‹defaultdb›.public.‹customers› EXPERIMENTAL_AUDIT SET READ WRITE","Tag":"ALTER TABLE","User":"‹test›","DescriptorID":55,"ApplicationName":"$ cockroach sql","ExecMode":"exec","Age":7.259063,"TxnCounter":10,"TableName":"‹defaultdb.public.customers›","AccessMode":"rw”}
cockroachdb-2:cockroachdb I220329 01:36:07.393523 69957812@util/log/event_log.go:32 ⋮ [n3,client=‹123.123.123.123:45640›,hostssl,user=‹test›] 23446={"Timestamp":1648517767385257975,"EventType":"sampled_query","Statement":"ALTER TABLE ‹defaultdb›.public.‹customers› EXPERIMENTAL_AUDIT SET READ WRITE","Tag":"ALTER TABLE","User":"‹test›","ApplicationName":"$ cockroach sql","ExecMode":"exec","Age":7.259063,"TxnCounter":10,"SkippedQueries":1,"CostEstimate":0.02,"Distribution":"local”}
cockroachdb-2:cockroachdb I220329 01:36:07.404406 6995785@util/log/event_log.go:32 ⋮ [n3,client=‹123.123.123.123:45640›,hostssl,user=‹test›] 23447 ={"Timestamp":1648517767385257975,"EventType":"alter_table","Statement":"ALTER TABLE ‹defaultdb›.public.‹customers› EXPERIMENTAL_AUDIT SET READ WRITE","Tag":"ALTER TABLE","User":"‹test›","DescriptorID":55,"ApplicationName":"$ cockroach sql","TableName":"‹defaultdb.public.customers›"}
```

However, it's come to my attention that while a session is open the client can change the identity of the current user (given appropriate SQL permissions) and that will update this "User" field.

In order to properly track transitions in identity (for compliance purposes), can we add a new event type for when the identity of the current user is switched during a session (reporting old, new identities)?

Thanks @knz for guidance on this issue.

Jira issue: CRDB-19902

**Comment by knz** [comment]
We're talking here about a new audit event type for the `SET AUTHORIZATION` statement.

cc @rafiss for triage. This is part of the PCI roadmap. Will need backport to 22.2.

**Comment by rafiss** [comment]
thanks for flagging this. and SET ROLE as well

**Comment by rafiss** [comment]
alternative: we could have the logs always use the SESSION_USER, which is immutable, as opposed to the CURRENT_USER, which can be changed.
