### ISSUE TITLE
ui: CPU table aggregation should not use a simple sum

### ISSUE THREAD

**Issue by nictuku** [cockroachdb/cockroach#8877]
In the UI, go to "Nodes" and look at the table.

The CPU column has an aggregated value at the top. I would expect it to be averaged out, assuming all nodes have the same CPU capacity (should that be assumed?).

**Comment by bdarnell** [comment]
We shouldn't assume that all nodes have the same CPU capacity. We should either report cpu usage in number (or fraction) of cores used, or have each node export both its usage and its total number of CPUs so we can compute the correct percentage.

**Comment by mrtracy** [comment]
We no longer show table aggregates in the node table; we also no longer display CPU usage at all in this table.
