### ISSUE TITLE
ui: Confusing UX for the usage report page

### ISSUE THREAD

**Issue by nictuku** [cockroachdb/cockroach#8878]
The user experience for the usage report page is quite confusing.

It's promising to report usage details anonymously. But it also has a form asking for my name and email. These two things are reasonable in isolation, but together they are confusing.

Consider moving the "subscribe to keep up to date" call to action to a separate page or so.

**Comment by nictuku** [comment]
Moving the form fields under the "Send me product and feature updates" section could make things more clear.

**Comment by arjunravinarayan** [comment]
cc @jess-edwards

**Comment by jess-edwards** [comment]
@nictuku Thanks for the feedback. We've recently hired a UX designer ( @kuanluo ) who will be revamping the UI, and we'll take your thoughts into account. 

Cheers,
Jessica

**Comment by mrtracy** [comment]
#12982 has provided a much clearer design for this. This issue should be closed when that new page is implemented to a satisfactory level.

**Comment by dianasaur323** [comment]
Already removed this page. Closing out!
