### ISSUE TITLE
Log aws-sdk logs to a logging channel or file

### ISSUE THREAD

**Issue by data-matt** [cockroachdb/cockroach#88797]
**Is your feature request related to a problem? Please describe.**
When trying to debug the aws-sdk when backing up to S3, the only method we know of is to set vmodule and capture stdout:

`SELECT crdb_internal.set_vmodule('s3_storage=3')`

However, if you have machine users that run backups and a large amount of nodes, its impractical to use this, since we can't necessarily log the aws-sdk without manual intervention. Add to that, that it these logs aren't captured at the time the issue occurred and it makes for a painful experience.   

Capturing stdout is not practical. 

**Describe the solution you'd like**
A method to capture the aws-sdk logs to a logging channel or file. Perhaps even a cluster setting.

**Describe alternatives you've considered**
Running the backup job manually and redirecting the stdout to a file.

**Additional context**
https://github.com/cockroachlabs/support/issues/1800
https://cockroachdb.zendesk.com/agent/tickets/13821

Jira issue: CRDB-19882

gz#14625

**Comment by stevendanna** [comment]
https://github.com/cockroachdb/cockroach/pull/88798

**Comment by data-matt** [comment]
@stevendanna , I don't think we need this, since we logging to the DEV channel.

Think I might close this. 

CC:
@livlobo

**Comment by stevendanna** [comment]
@data-matt I think we can close this now.  The combination of logging to the DEV channel and the new facility to set a cluster-wide vmodule setting gets us most of what we need here.
