### ISSUE TITLE
copy: client side of copy in pgconn has an I/O race

### ISSUE THREAD

**Issue by cucaroach** [cockroachdb/cockroach#88801]
https://github.com/jackc/pgconn/issues/128

Not sure if this is a regression or a release blocker but figured a tracking issue was worthwhile.  I think this doesn't affect 22.1 because we used lib/pq?   So this should probably be a release blocking regression.

The bug is a race that only occurs when failing (ie malformed in some way) COPY commands are occurring so its a bit of an edge case.

Jira issue: CRDB-19973

**Comment by otan** [comment]
I would say this isn't a release blocker as it's a problem only if there's an error. Also in actuality I think commands would not be run so close together that it'd race.

**Comment by rafiss** [comment]
I'll remove the release-blocker label since the bug is hard to encounter
