### ISSUE TITLE
kvserver: excessive CPU use in `replicateQueue.canTransferLeaseFrom`

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#88803]
In #88678, we were seeing timeouts for `kv/splits/nodes=3/quiesce=false`. The proximate cause was a gRPC version upgrade, which was reverted in #88745. However, even after that, I was seeing occasional (~20%) runs get stuck while splitting ranges. All nodes appeared to be pinned at 100% CPU. A CPU profile shows them all busy looping on lease transfers:

<img width="1323" alt="Screenshot 2022-09-27 at 15 24 04" src="https://user-images.githubusercontent.com/644420/192540380-9752bdbb-2825-4152-a59c-b36af68043f3.png">

**Comment by andrewbaptist** [comment]
Looking now, but there are two interesting pieces of this:
1) Why is it looking on `canTransferLeaseFrom` - I'm looking at the cause of this, my guess is that there is something that keeps "re-adding" it to the replicate queue even though it keeps failing, but I need to track it down.
2) Why is store.Descriptor() and in particular store.Capacity() so expensive. The current call does use the "uncached" version of capacity. It should probably change to use the cached version, but need to understand the implications of that.

**Comment by kvoli** [comment]
Talked to @andrewbaptist. `leaseViolatePreferences` calls `Capacity()` uncached, meaning it has to iterate over all replicas on the store on each call to `shouldQueue()` (100/s). @andrewbaptist is putting together a patch to use `cached` which should drop all of the cpu time below `Capacity`.

**Comment by nvanbenschoten** [comment]
@andrewbaptist @kvoli is this an issue on the release-22.2 branch, or only on master?

As of https://github.com/cockroachdb/cockroach/commit/bfbf3c7fe4c13b0808afd0738f0ea494c1060d60 (which needs a backport), the call to `r.store.Descriptor()` is always hit in `leaseViolatesPreferences` instead of only on the leaseholder when lease preferences are present, so I can see why that change revealed this issue. However, if the right conditions were true, we did use to call `r.store.Descriptor(false)`.

**Comment by erikgrinaker** [comment]
Can confirm that `kv/splits/nodes=3/quiesce=false ` passes with #88821, and in 50% less time, so closing this out.

But let's make sure we backport appropriately, as mentioned above.

**Comment by andrewbaptist** [comment]
See https://github.com/cockroachdb/cockroach/pull/88842 - I added this commit to this backport PR. Once merged to master can merge here also.

**Comment by erikgrinaker** [comment]
Sure, but what about 22.1 and 21.2? Won't they hit this on leaseholders where lease preferences are set?
