### ISSUE TITLE
cli/sql: unexpected increase in size of the `cockroach-sql` binary

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#88833]
**Describe the problem**

Found by @ianjevans : the cockroach-sql binary grew from 7.5MB in 22.1.5 to 85MB in 22.1.6.

This is abnormal and should be fixed

Relates to (but is independent from) #79675

Jira issue: CRDB-20014

**Comment by rail** [comment]
Should be fixed in the next release.
