### ISSUE TITLE
stability: investigate election bursts

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#8884]
On beta, we see fairly regular election storms:

![screen shot 2016-08-29 at 10 28 32 am](https://cloud.githubusercontent.com/assets/5076964/18054873/ae9aaab0-6dd3-11e6-9ad5-b867a02e62b5.png)

Unfortunately, this doesn't really correlate with any of the Raft processing times, but could simply reflect #8638. What it does reflect though is that there's no good way to see this from the graphs (that I know of). We could track the max processing time (over all Replicas on the Store) as a gauge.

![screen shot 2016-08-29 at 10 29 11 am](https://cloud.githubusercontent.com/assets/5076964/18054872/ae983852-6dd3-11e6-8191-896151b149ac.png)

**Comment by petermattis** [comment]
Looks to me like the election bursts are correlated with snapshots. More precisely, when there are periods of no snapshots, there are no election bursts.

**Comment by tschottdorf** [comment]
Not sure I see that correlation, but it would certainly make sense since that should clog up the raft processing goroutine.

![screen shot 2016-08-29 at 2 15 15 pm](https://cloud.githubusercontent.com/assets/5076964/18062014/01b332e8-6df3-11e6-95c2-e1abae31f761.png)

**Comment by bdarnell** [comment]
By plotting the raft tick counts (which should be a constant 5/sec/node), we can see that the elections are indeed correlated with skipped ticks:

<img width="264" alt="screenshot 2016-08-30 15 21 28" src="https://cloud.githubusercontent.com/assets/160562/18079911/b2d637b4-6ec5-11e6-90e0-5809179f1d39.png">

This is good evidence that it's #8638, although it doesn't follow that it's always snapshots. The correlation looks pretty good before 00:00, but there were two election storms after that point that don't have corresponding snapshot activity:

<img width="282" alt="screenshot 2016-08-30 15 24 59" src="https://cloud.githubusercontent.com/assets/160562/18079984/0b2ac95c-6ec6-11e6-8e75-8f0368688b98.png">

**Comment by bdarnell** [comment]
The last big election spike with no snapshots corresponds to a node restart (OOM with leaked goroutines)

**Comment by petermattis** [comment]
This was happening a long time ago and lots has changed since then. I'm closing unless someone feels there is still something to investigate here.
