### ISSUE TITLE
db-console bundle is too large

### ISSUE THREAD

**Issue by sjbarag** [cockroachdb/cockroach#88876]
**Describe the problem**
The produced JS bundle for the embedded DB Console UI is ~25 megabytes (24,652 KB on a build from the current tip of `release-22.2`: 79790c4b7b (Merge pull request #88842 from andrewbaptist/backport22.2-87652, 2022-09-27)), which is far too large.

**To Reproduce**

1. `git checkout 79790c4b7b`
2. `./dev build`
3. `du -k _bazel/bin/pkg/ui/workspaces/db-console/db-console-ccl/assets/bundle.js`

**Expected behavior**
There's no right answer for how big that bundle should be, but 25MB is definitely above that limit.

**Environment:**
Anything in the 22.2 series, though we've seen this at least as far back as 21.2.

**Additional context**
_What was the impact?_

Having such a large bundle makes loading the embedded DB Console very slow in many situations — sometimes taking 30 seconds to download just that file.

Jira issue: CRDB-20018

**Comment by fantapop** [comment]
One other thing I would add is that as the bundle is downloading, the screen just shows white.  Go to an incognito tab, disable cache and set the network speed to "Fast 3g". I was going to post a loom but its pretty boring.  just white, basically forever....  I think the experience could be improved a lot by fast loading some sort of waiting screen and then show a spinner or a loading indicator as the bundle downloads.

**Comment by sjbarag** [comment]
That's true!  As a separate issue that I'll be filing (and fixing) tomorrow, it looks like the response for `bundle.js` isn't being properly gzip-compressed.  In fact, it's a few bytes larger with `Accept-Encoding: gzip` from what I can tell 0.o

-----

On the tip of `release-22.2` without compression, 25.242 MB are transferred:

```sh
curl localhost:8080/bundle.js \
    --silent \
    --include \
    --output /dev/null \
    --dump-header /dev/stderr \
    --write-out 'duration (s): %{time_total}\ndownloaded bytes: %{size_download}'

HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: no-cache
Content-Length: 25242299
Content-Type: text/javascript; charset=utf-8
Etag: "83292591f63f6833e4bc2513f44b28ea5ecac989"
Last-Modified: Wed, 28 Sep 2022 00:08:41 GMT
Date: Wed, 28 Sep 2022 00:08:48 GMT

duration (s): 0.012553
downloaded bytes: 25242299
```

With compression, 25.244 MB are transferred. We send an extra 2k in the compressed version.

```
curl localhost:8080/bundle.js \
    --silent \
    --include \
    --output /dev/null \
    --dump-header /dev/stderr \
    --write-out 'duration (s): %{time_total}\ndownloaded bytes: %{size_download}' \
    --compressed

HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: no-cache
Content-Encoding: gzip
Content-Type: text/javascript; charset=utf-8
Etag: "83292591f63f6833e4bc2513f44b28ea5ecac989"
Last-Modified: Wed, 28 Sep 2022 00:08:41 GMT
Date: Wed, 28 Sep 2022 00:10:31 GMT
Transfer-Encoding: chunked

duration (s): 0.027303
downloaded bytes: 25244252
```

-----

With naive gzip encoding using https://github.com/NYTimes/gziphandler, it looks more like:

```sh
curl localhost:8080/bundle.js \
    --silent \
    --include \
    --output /dev/null \
    --dump-header /dev/stderr \
    --write-out 'duration (s):%{time_total}\ndownloaded bytes: %{size_download}'\
    --compressed

HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: no-cache
Content-Encoding: gzip
Content-Type: text/javascript; charset=utf-8
Etag: "83292591f63f6833e4bc2513f44b28ea5ecac989"
Last-Modified: Tue, 27 Sep 2022 23:57:22 GMT
Vary: Accept-Encoding
Date: Wed, 28 Sep 2022 00:01:34 GMT
Transfer-Encoding: chunked

duration(s):0.524007
downloaded bytes: 7455573
```

It's slower to respond, but way faster to transfer (only 1.4s over an ssh tunnel vs. 5.21 s for the original build / 2.34 s after things warm up).

**Comment by sjbarag** [comment]
#88950 should help to accelerate these responses by sending a compressed file over the wire.

**Comment by cgetzen** [comment]
Is the caching mechanism optimal? I see there is no version associated with bundle.js, which may prevent [some optimizations](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#caching_static_assets_with_cache_busting).

**Comment by sjbarag** [comment]
@cgetzen You're right, the current ETag-based solution isn't ideal! We couldn't use filenames with content hashes included (typically via [webpack's output.filename](https://v4.webpack.js.org/configuration/output/#outputfilename) because of how we previously served `index.html`: the `<script/>` tag for `bundle.js` was hardcoded as part of a Go template that was rendered for each request.  This changed [back in June](https://github.com/cockroachdb/cockroach/commit/320bdfbebb48940051dfa7adb87efe25ba62502a) (gosh, it's already mid-October 😨), and `index.html` is now a static file (lending itself to generation with the [HtmlWebpackPlugin](https://v4.webpack.js.org/plugins/html-webpack-plugin/)).  I just filed https://github.com/cockroachdb/cockroach/issues/90158 to track that effort.

In the meantime, ETags have worked reasonably well from what I can tell, since the value of the ETag response header is the sha1 sum of each served file.  Browser cache eviction policies vary, of course, so if you're seeing uncached `bundle.js`  responses where you wouldn't expect them please let me know!
