### ISSUE TITLE
Wrong statement in blocking transaction

### ISSUE THREAD

**Issue by stbof** [cockroachdb/cockroach#88873]
1. Run cockroach demo in term 1 and cockroach sql in term 2.
2. In term 1, run 
`CREATE TABLE accounts (                                                                                                                                                        id INT PRIMARY KEY,                                                                                                                                                                                   balance DECIMAL                                                                                                                                                                                   );`
3. Run `begin;`
4. Run  `INSERT INTO accounts VALUES (1, 10000.50);`
5. In term 2, run `select * from accounts;`
6. View transaction execution:

<img width="1556" alt="Screen Shot 2022-09-27 at 3 40 58 PM" src="https://user-images.githubusercontent.com/20482960/192650279-d3803a8e-21af-46f3-9a2d-bc9fa7eed324.png">

The blocking statement is `show database` instead of `INSERT INTO accounts VALUES (1, 10000.50);`

**Environment:**
 - CockroachDB version [e.g. 2.0.x] Server version: CockroachDB CCL v22.2.0-beta.1-154-g79790c4b7bd (x86_64-apple-darwin21.6.0, built 2022/09/27 22:24:07, go1.19.1)
 - Server OS: MacOS
 - Client app [e.g. `cockroach sql`, JDBC, ...] cockroach sql

**Additional context**
What was the impact?

**Comment by ericharmeling** [comment]
The `SHOW DATABASE` statements listed here are automatically executed by the CLI. See https://github.com/cockroachdb/cockroach/issues/81785 for more details.

We really shouldn't be showing these "internal" statements in the UI at all. Let's consolidate this issue with the existing one.
