### ISSUE TITLE
TestExecBuild_forecast1401 fails on ARM64

### ISSUE THREAD

**Issue by healthy-pod** [cockroachdb/cockroach#88893]
**To Reproduce**

`./dev test pkg/sql/opt/exec/execbuilder/tests/local --filter="TestExecBuild_forecast1401"`

Debugging info I gathered:
It fails with the test cases at lines 18506 and 18552 in `pkg/sql/opt/exec/execbuilder/testdata/forecast1401`. Due to floating point differences between different architectures, some of the floats in the histogram are slightly different. I used rounding to fix other failures on arm64 but it's not possible with this one because we can't round the floats in the histogram.

Jira issue: CRDB-20026

**Comment by michae2** [comment]
Side note: the same code that causes https://github.com/cockroachdb/cockroach/issues/76887 is also causing this. The sooner we fix https://github.com/cockroachdb/cockroach/issues/83730 and delete that code, the better!
