### ISSUE TITLE
TestVoronoiPolygons fails on Graviton2 (passes on M1)

### ISSUE THREAD

**Issue by healthy-pod** [cockroachdb/cockroach#88894]
**To Reproduce**

`./dev test pkg/geo/geomfn --filter="TestVoronoiPolygons"` on a Graviton2 instance

In the screenshot below, expected output is shown on the left and actual output is shown on the right:

<img width="1484" alt="Screen Shot 2022-09-27 at 8 31 39 PM" src="https://user-images.githubusercontent.com/29309581/192681426-b5dbfc82-bf5b-40d9-b614-738baec69a7f.png">

**Comment by otan** [comment]
We use a third party library to calculate this:

https://github.com/cockroachdb/cockroach/blob/4982322e91c37c6d0249dc5597b9e02eec19848d/pkg/geo/geos/geos.go#L1078

And it's subject to rounding errors depending on weird ARM-y features - we've had to some weird casting on other libraries for example: https://github.com/twpayne/go-geom/pull/214/files.

i'm ok if you wanted to delete the test that causes the issue or condition it on arm64/graviton.
