### ISSUE TITLE
loqrecovery: design/RFC for half-online approach

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#88905]
Related to #77273.

We should begin working on the design, discuss it with SREs/TSEs, and update the RFC.

Jira issue: CRDB-20029

Epic CRDB-14205

**Comment by aliher1911** [comment]
Authentication and various rpc apis: https://cockroachlabs.atlassian.net/wiki/spaces/DBSRV/pages/1994654233/HTTP+RPC+and+SQL+API+Servers+inside+CockroachDB
