### ISSUE TITLE
kvserver: ReplicasStorage prototype

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#88907]
This tracks the work needed to land and complete the `ReplicasStorage` prototype in #88606.

Jira issue: CRDB-20030

Epic CRDB-220

**Comment by tbg** [comment]
We've since filed issues tracking this work in more detail (see https://github.com/cockroachdb/cockroach/issues?q=is%3Aissue+is%3Aopen+%22CRDB-220%22) and these issues link into the relevant parts of https://github.com/cockroachdb/cockroach/pull/88606) so closing this issue out.
