### ISSUE TITLE
sql: trigram index handles '%' incorrectly

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#88925]
roachtest.unoptimized-query-oracle/disable-rules=all [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6638354?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/6638354?buildTab=artifacts#/unoptimized-query-oracle/disable-rules=all) on release-22.2 @ [1f718803f084451c1b061db5a69bfc62feb1c457](https://github.com/cockroachdb/cockroach/commits/1f718803f084451c1b061db5a69bfc62feb1c457):

```
test artifacts and logs in: /artifacts/unoptimized-query-oracle/disable-rules=all/run_1
	query_comparison_util.go:240,query_comparison_util.go:69,unoptimized_query_oracle.go:54,test_runner.go:908: . 9408 statements run: expected unoptimized and optimized results to be equal
		(1) attached stack trace
		  -- stack trace:
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.(*queryComparisonHelper).makeError
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/query_comparison_util.go:348
		  | [...repeated from below...]
		Wraps: (2) . 9408 statements run
		Wraps: (3) attached stack trace
		  -- stack trace:
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.runUnoptimizedQueryOracleImpl
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/unoptimized_query_oracle.go:168
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerUnoptimizedQueryOracle.func1.1
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/unoptimized_query_oracle.go:57
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.runOneRoundQueryComparison
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/query_comparison_util.go:239
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.runQueryComparison
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/query_comparison_util.go:69
		  | github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerUnoptimizedQueryOracle.func1
		  | 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/unoptimized_query_oracle.go:54
		  | main.(*testRunner).runTest.func2
		  | 	main/pkg/cmd/roachtest/test_runner.go:908
		  | runtime.goexit
		  | 	GOROOT/src/runtime/asm_amd64.s:1594
		Wraps: (4) expected unoptimized and optimized results to be equal
		  |   []string(
		  | - 	{"1"},
		  | + 	nil,
		  |   )
		  | sql: SELECT
		  | 	count(*) AS col_34603
		  | FROM
		  | 	defaultdb.public.table2@[0] AS tab_11593
		  | WHERE
		  | 	'aab':::STRING LIKE tab_11593.col2_5
		  | GROUP BY
		  | 	tab_11593.col2_5, tab_11593.col2_4
		  | HAVING
		  | 	' a':::STRING !~* 'pTs1':::STRING
		Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.leafError
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*unoptimized-query-oracle/disable-rules=all.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

_Originally posted by @cockroach-teamcity in https://github.com/cockroachdb/cockroach/issues/88558#issuecomment-1259607478_
      

Jira issue: CRDB-20039

**Comment by rytaft** [comment]
Here's a repro:
```
  CREATE TABLE t88558 (
      col1 INT PRIMARY KEY,
      col2 CHAR NOT NULL,
      INVERTED INDEX t88558_col2_idx (col2 gin_trgm_ops)
  );

  INSERT INTO t88558 VALUES (1, '%');

  SELECT *
    FROM t88558@t88558_pkey
   WHERE 'aab':::STRING LIKE col2;


  SELECT *
    FROM t88558@t88558_col2_idx
   WHERE 'aab':::STRING LIKE col2;
```
First query produces:
```
  col1 | col2
-------+-------
     1 | %
(1 row)
```
Second query produces:
```
  col1 | col2
-------+-------
(0 rows)
```

**Comment by jordanlewis** [comment]
The bug here is that the `trigramFilterPlanner` treats the left and right side of the `LIKE` expression as identical. But, `LIKE` doesn't work that way - only the expressions on the RHS use `%` as a wildcard. LHS expressions do not use `%` as a wildcard.

It should be a straightforward fix. I'm happy to help someone work through it if need be!
