### ISSUE TITLE
sql/schemachanger: concurrent declarative/legacy schema changer use can lead to hangs

### ISSUE THREAD

**Issue by fqazi** [cockroachdb/cockroach#88922]
Currently, we do not properly block against concurrent schema changes between the legacy and
declarative schema changer when dropping databases, schemas and types. This can lead to issues
in certain scenarios like DROP OWNED BY combined with legacy DROP DATABASE, where the former
will lock the database in question (with a schema changer state) and the latter will completely ignore
this and continue. 

This leads to hangs like:  https://github.com/cockroachdb/cockroach/issues/75604

Jira issue: CRDB-20038

**Comment by ajwerner** [comment]
Will be closed by https://github.com/cockroachdb/cockroach/pull/89048.

**Comment by fqazi** [comment]
Fixed via: https://github.com/cockroachdb/cockroach/pull/89436
