### ISSUE TITLE
base: hook up runtime.SetCgoTraceback

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#8894]
This should give us better traces from cgo. See https://golang.org/pkg/runtime/#SetCgoTraceback and https://github.com/ianlancetaylor/cgosymbolizer.

**Comment by petermattis** [comment]
@tamird Can you take a look at this? I tried hooking up `github.com/ianlancetaylor/cgosymbolizer` via a `start_cgosymbolizer.go` file with an appropriate import and build tag so that we only import it on linux, but pprof still isn't showing symbols for Cgo code. Perhaps I did something wrong or perhaps `github.com/ianlancetaylor/cgosymbolizer` isn't working. This would be somewhat useful in the near term for performance debugging (i.e. getting Cgo stacktraces for CPU profiles).

**Comment by tamird** [comment]
Yep, I'll look at it. Do you have a snippet I could use for testing it?

**Comment by petermattis** [comment]
No (I accidentally `git checkout .`), but it was as simple as:

```
// +build linux

package cli

import (
  _ "github.com/ianlancetaylor/cgosymbolizer"
)
```

`build/builder.sh make build` showed that `github.com/ianlancetaylor/cgosymbolizer` was built, but a subsequent CPU profile didn't show any stack traces involving Cgo.

**Comment by tamird** [comment]
I've tested the trivial example in https://groups.google.com/forum/#!topic/golang-nuts/NNOJ2iiuPnY, which worked. On to the real thing.
