### ISSUE TITLE
sql/importer: hash shard check constraints are invalidated with IMPORT INTO

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#89012]
**Describe the problem**

Check constraints get marked as `NOT VALID` when running `IMPORT INTO`. This is what it is, but in general could be okay if we documented it (https://github.com/cockroachdb/docs/issues/15244). 

This is particularly painful when it comes to hash sharded indexes. Those things have associated check constraints, but we do not show them in the create statements. The good news about those constraints is that they are valid by construction. That means we can detect such constraints in the importer and choose not to mark them as unvalidated here:

https://github.com/cockroachdb/cockroach/blob/ef4656fc14155afd31a486b38f688c0dee08ca0b/pkg/sql/importer/import_job.go#L1006-L1009

**To Reproduce**
Import into a hash sharded table and notice that the shard constraints are invalid by looking at `pg_constraint`. 

**Additional context**
Potentially we should find a way to show the fact that the constraints are not valid to the user -- perhaps by choosing to show the constraint in `CREATE TABLE` statements if the constraint is `NOT VALID`. That would be an easy change, though we have to ask what we ought to do if the user gives us such a statement -- do we reject it? Do we accept it but actually go and validate the constraint when we make the new table?

Epic CRDB-8353

Jira issue: CRDB-20076

**Comment by ZhouXing19** [comment]
sql-exp can help fix this, as we will work on https://github.com/cockroachdb/cockroach/issues/67076 and it may be related.

**Comment by dt** [comment]
Could we just enforce CHECK constraints during the IMPORT? we have full (to the extent that impure builtins work) expression eval hooked up anyway so can we just eval check expressions and reject violations instead of invalidating the constraints?

**Comment by ajwerner** [comment]
I can see a desire to do that. I'd still rather the super quick fix if the timelines diverge.

**Comment by ZhouXing19** [comment]
I made https://github.com/cockroachdb/cockroach/pull/89231 as a quick fix for this issue, and opened https://github.com/cockroachdb/cockroach/issues/89290 for enforcing constraints.
