### ISSUE TITLE
cdc: TestChangefeedKafkaMessageTooLarge is flakey

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#89028]
See https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/6679535?showRootCauses=true&expandBuildProblemsSection=true&expandBuildDeploymentsSection=true&expandBuildTestsSection=true

[goroutine dump](https://gist.github.com/mgartner/470ee41a21d89cf62f90ac4130485949).

Jira issue: CRDB-20079

**Comment by mgartner** [comment]
Another one: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/6718751?showRootCauses=true&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildDeploymentsSection=true&expandBuildTestsSection=true

**Comment by samiskin** [comment]
There's only been one failure since the day https://github.com/cockroachdb/cockroach/pull/89173 went in to fix this, and that one failure's PR looks like it was probably just out of date, so I think this is fixed
