### ISSUE TITLE
Addressing observability related system privileges acceptance testing feedback for v22.2

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#89034]
Ref: Refer to [22.2 Acceptance Testing Obs Privileges](https://docs.google.com/document/d/1vUVk3T7P_to0B_XrBCpTrI-X5_Csyf9-RA6t880IDyM/edit)

- [x] User with `VIEWCLUSTERSETTING` OR `MODIFYCLUSTERSETTING` privileges should be able to run the command `SHOW CLUSTER SETTINGS;` - currently doing so will result in a SQLSTATE: 42501 message 
- [x]  User with `MODIFYCLUSTERSETTING` privilege should be able to run the command `SET CLUSTER SETTING;` - currently doing so will result in a SQLSTATE: 42501 message 
- [x] For the Hot Ranges page, we should update the gate from the old `VIEWACTIVITY`/`VIEWACTIVITYREDACTED` role option to the `VIEWCLUSTERMETADATA` privilege. The idea is that most range related info should be behind `VIEWCLUSTERMETADATA` (not `VIEWACTIVITY` which was added as a temporary stopgap in 22.1)
- [x] Currently nothing gates https://localhost:8080/#/reports/problemranges/1 (we should introduce the `VIEWCLUSTERMETADATA` gate)
- [x] Currently ADMIN gates https://localhost:8080/#/data-distribution (we should introduce the `VIEWCLUSTERMETADATA` gate)
- [x] Update the stores request gate (which feeds pages like https://localhost:8080/#/reports/stores/local) to be behind `VIEWCLUSTERMETADATA` (it's currently gated by ADMIN)
- [x] Update _status/hotranges to be gated by `VIEWCLUSTERMETADATA` (investigate https://localhost:8080/#/debug/hotranges which is currently not gated by anything)
- [x] Under the section "Even More Advanced Debugging", the "Ranges" links - Range Status (#/reports/range/[range_id]), Raft Messages (#/raft/messages/all), Raft for all ranges (#/raft/ranges) - should be gated behind the same standard privilege `VIEWCLUSTERMETADATA`
- [x] #/debug/redux (UI Debugging) should be behind VIEWDEBUG but it's not gated by anything

Jira issue: CRDB-20081

**Comment by Santamaura** [comment]
Just tested item 2 on the list it seems to work fine for me but will discuss further
