### ISSUE TITLE
Estimated Rows of `RIGHT JOIN` and `FULL OUTER JOIN`

### ISSUE THREAD

**Issue by bajinsheng** [cockroachdb/cockroach#89060]
**Describe the problem**

`RIGHT JOIN` returns more estimated rows than `FULL OUTER JOIN`.

**To Reproduce**

```
CREATE TABLE t0 (c0 INT);
CREATE TABLE t2 (c0 INT, c1 INT);
INSERT INTO t2 VALUES(1,2), (3,4), (5,6), (null, null);
INSERT INTO t0 VALUES(1), (2);

ANALYZE t0;
ANALYZE t2;

EXPLAIN (VERBOSE) SELECT * FROM t0 RIGHT OUTER JOIN t2 ON t2.c1 IN (t2.c1) WHERE CASE WHEN t2.rowid > 2 THEN false ELSE t2.c1=1 END; --estimated rows: 3
EXPLAIN (VERBOSE) SELECT * FROM t0 FULL OUTER JOIN t2 ON t2.c1 IN (t2.c1) WHERE CASE WHEN t2.rowid > 2 THEN false ELSE t2.c1=1 END; --estimated rows: 2 
```

**Expected behavior**
I think `RIGHT JOIN` should always return no more than estimated rows than `FULL OUTER JOIN`.

**Environment:**
 - CockroachDB version [f188d21d1853ca8b81d9c4f0ab46d7c0fa34ee44]
 - Server OS: [Ubuntu 20.04]
 - Client app [`cockroach sql`]

**Additional context**

Jira issue: CRDB-20102

**Comment by DrewKimball** [comment]
Hi @bajinsheng, thanks for posting! If you run the queries under explain, you should see that the `CASE WHEN t2.rowid > 2 THEN false ELSE t2.c1=1 END` filter can be pushed below the join for the `RIGHT JOIN`, but not for the `FULL JOIN`. So the row count of the `RIGHT JOIN` is reduced by the presence of the filter below the join. Let me know if you have any other questions.

**Comment by bajinsheng** [comment]
Thanks for explanation!
