### ISSUE TITLE
changefeedccl: error on wrong syntax for expressions

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#89094]
CREATE CHANGEFEED INTO 'gcpubsub://cdc-telemetry-monitoring?region=us-east1&topic_name=demo&AUTH=specified&CREDENTIALS=[your credentials]' AS SELECT city, creation_time FROM movr.vehicles WITH schema_change_policy=stop;

This command hangs. This is wrong syntax, but since this is more in-line with the normal way to create changefeeds, it is very likely users will make this mistake. We should make sure we return a syntax error in this situation instead of hanging. 

Jira issue: CRDB-20111

**Comment by jayshrivastava** [comment]
I can't repro this on master. Is this a bug on the release branch?

**Comment by amruss** [comment]
Closing this
