### ISSUE TITLE
Test failure TestMultiStoreEventFeed

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#891]
The following test appears to have failed:

[#2045](https://circleci.com/gh/cockroachdb/cockroach/2045):

```
I0502 02:05:42.876390     446 multiraft.go:451] node 100000001: group 1 got message 12884901891->4294967297 MsgHeartbeatResp Term:6 Log:0/0
I0502 02:05:42.879448     446 multiraft.go:451] node 100000001: group 2 got message 12884901891->4294967297 MsgHeartbeatResp Term:6 Log:0/0
I0502 02:05:42.880609     446 multiraft.go:451] node 100000001: group 1 got message 8589934594->4294967297 MsgHeartbeatResp Term:6 Log:0/0
I0502 02:05:42.881146     446 multiraft.go:451] node 100000001: group 2 got message 8589934594->4294967297 MsgHeartbeatResp Term:6 Log:0/0
I0502 02:05:42.881426     446 multiraft.go:451] node 100000001: group 1 got message 8589934594->4294967297 MsgAppResp Term:6 Log:0/48
--- FAIL: TestMultiStoreEventFeed (1.99s)
	client_event_test.go:272: event feed did not match expected value. Actual values have been printed to compare with above expectation.
	client_event_test.go:273: Event feed information:
		proto.StoreID(1): []string{
				"StartStore",
				"BeginScanRanges",
				"AddRange rid=1, live=348",
				"EndScanRanges",
				"SplitRange origId=1, newId=2, origLive=854, newLive=42, origVal=715, newVal=27",
				"SplitRange origId=2, newId=3, origLive=42, newLive=0, origVal=27, newVal=0",
				"MergeRange rid=2, subId=3, live=42, subLive=0",
--
I0502 02:05:43.279984     446 multiraft.go:705] Committed Entry[3]: 6/42 EntryNormal 00000000000000003417ec1cf83bd2de: raft_id:1 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
I0502 02:05:43.280065     446 multiraft.go:694] node 100000001: group 2 raft ready
I0502 02:05:43.280125     446 multiraft.go:699] HardState updated: {Term:6 Vote:4294967297 Commit:16 XXX_unrecognized:[]}
I0502 02:05:43.280938     446 multiraft.go:702] New Entry[0]: 6/16 EntryNormal 00000000000000000d89050194abc0f1: raft_id:2 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
I0502 02:05:43.281688     446 multiraft.go:705] Committed Entry[0]: 6/16 EntryNormal 00000000000000000d89050194abc0f1: raft_id:2 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
panic: test timed out after 5m0s

goroutine 3557 [running]:
testing.func·008()
	/usr/src/go/src/testing/testing.go:681 +0x168
created by time.goFunc
	/usr/src/go/src/time/sleep.go:129 +0x59

goroutine 1 [chan receive, 4 minutes]:
testing.RunTests(0x133fa00, 0x1821cc0, 0xa3, 0xa3, 0x0)
	/usr/src/go/src/testing/testing.go:556 +0xdc3
--
	/go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:443 +0x238b
github.com/cockroachdb/cockroach/util.func·005()
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:73 +0x80
created by github.com/cockroachdb/cockroach/util.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:74 +0x133
FAIL	github.com/cockroachdb/cockroach/storage	300.035s
=== RUN TestBatchBasics
I0502 02:06:43.014191     535 rocksdb.go:88] opening in-memory rocksdb instance
I0502 02:06:43.015338     535 rocksdb.go:113] closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN TestBatchGet
I0502 02:06:43.019584     535 rocksdb.go:88] opening in-memory rocksdb instance
I0502 02:06:43.019981     535 rocksdb.go:113] closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.00s)
=== RUN TestBatchMerge
I0502 02:06:43.023827     535 rocksdb.go:88] opening in-memory rocksdb instance
I0502 02:05:42.876390     446 multiraft.go:451] node 100000001: group 1 got message 12884901891->4294967297 MsgHeartbeatResp Term:6 Log:0/0
I0502 02:05:42.879448     446 multiraft.go:451] node 100000001: group 2 got message 12884901891->4294967297 MsgHeartbeatResp Term:6 Log:0/0
I0502 02:05:42.880609     446 multiraft.go:451] node 100000001: group 1 got message 8589934594->4294967297 MsgHeartbeatResp Term:6 Log:0/0
I0502 02:05:42.881146     446 multiraft.go:451] node 100000001: group 2 got message 8589934594->4294967297 MsgHeartbeatResp Term:6 Log:0/0
I0502 02:05:42.881426     446 multiraft.go:451] node 100000001: group 1 got message 8589934594->4294967297 MsgAppResp Term:6 Log:0/48
--- FAIL: TestMultiStoreEventFeed (1.99s)
	client_event_test.go:272: event feed did not match expected value. Actual values have been printed to compare with above expectation.
	client_event_test.go:273: Event feed information:
		proto.StoreID(1): []string{
				"StartStore",
				"BeginScanRanges",
				"AddRange rid=1, live=348",
				"EndScanRanges",
				"SplitRange origId=1, newId=2, origLive=854, newLive=42, origVal=715, newVal=27",
				"SplitRange origId=2, newId=3, origLive=42, newLive=0, origVal=27, newVal=0",
				"MergeRange rid=2, subId=3, live=42, subLive=0",
--
I0502 02:05:43.279984     446 multiraft.go:705] Committed Entry[3]: 6/42 EntryNormal 00000000000000003417ec1cf83bd2de: raft_id:1 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
I0502 02:05:43.280065     446 multiraft.go:694] node 100000001: group 2 raft ready
I0502 02:05:43.280125     446 multiraft.go:699] HardState updated: {Term:6 Vote:4294967297 Commit:16 XXX_unrecognized:[]}
I0502 02:05:43.280938     446 multiraft.go:702] New Entry[0]: 6/16 EntryNormal 00000000000000000d89050194abc0f1: raft_id:2 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
I0502 02:05:43.281688     446 multiraft.go:705] Committed Entry[0]: 6/16 EntryNormal 00000000000000000d89050194abc0f1: raft_id:2 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
panic: test timed out after 5m0s

goroutine 3557 [running]:
testing.func·008()
	/usr/src/go/src/testing/testing.go:681 +0x168
created by time.goFunc
	/usr/src/go/src/time/sleep.go:129 +0x59

goroutine 1 [chan receive, 4 minutes]:
testing.RunTests(0x133fa00, 0x1821cc0, 0xa3, 0xa3, 0x0)
	/usr/src/go/src/testing/testing.go:556 +0xdc3
--
	/go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:443 +0x238b
github.com/cockroachdb/cockroach/util.func·005()
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:73 +0x80
created by github.com/cockroachdb/cockroach/util.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:74 +0x133
FAIL	github.com/cockroachdb/cockroach/storage	300.035s
=== RUN TestBatchBasics
I0502 02:06:43.014191     535 rocksdb.go:88] opening in-memory rocksdb instance
I0502 02:06:43.015338     535 rocksdb.go:113] closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN TestBatchGet
I0502 02:06:43.019584     535 rocksdb.go:88] opening in-memory rocksdb instance
I0502 02:06:43.019981     535 rocksdb.go:113] closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.00s)
=== RUN TestBatchMerge
I0502 02:06:43.023827     535 rocksdb.go:88] opening in-memory rocksdb instance

```
Please assign, take a look and update the issue accordingly.

**Comment by spencerkimball** [comment]
There is a bizarre 4 byte difference between what's expected (what usually happens), and what sometimes fails non-deterministically with four fewer bytes, as in this failure. I'm going to add a switch to enable full diagnostics when computing the MVCC stats after a split so we can find out where the missing value bytes are going.

**Comment by tschottdorf** [comment]
I haven't looked at it, but is it possible that this test sometimes runs pre- and post-lease? Acquiring the lease will write to MVCC and probably change things.

**Comment by spencerkimball** [comment]
No, the lease would definitely be held in this test. Plus, the difference here is 4 bytes, and only in values.

**Comment by tschottdorf** [comment]
@spencerkimball https://circleci.com/gh/cockroachdb/cockroach/2052 w/ diag

**Comment by tschottdorf** [comment]
@spencerkimball another one, this time on master https://github.com/cockroachdb/cockroach/issues/895
looks the same on first glance.

**Comment by tschottdorf** [comment]
It's not only a 4byte difference, but also `origVal=715` as opposed to the expected `719`. Can't this still be a timing issue? The test should be susceptible to all weird sorts of timing issues especially with ChangeReplica which takes a snapshot, and asynchronous ResolveIntents possibly flying around in random order with the rest of the commands. Either way, enjoy the treasure hunt :))

**Comment by spencerkimball** [comment]
I don't think it's timing. I think it's encoding. The four bytes of difference are in the size of the encoded value of the MVCCMetadata.. As an example:

    I0502 21:44:46.498097     442 mvcc.go:1416] diag: "\x00\x00meta1\xff\xff" meta  k=13 v=88
    I0502 09:57:15.090799     222 mvcc.go:1416] diag: "\x00\x00meta1\xff\xff" meta  k=13 v=89

They're off by just 1 byte. We're going to need to print out the encoded value and unmarshaled value.

**Comment by spencerkimball** [comment]
There are four MVCCMetadata values which have one byte differences, equally 4 bytes. The culprits are:

`"\x00\x00meta1\xff\xff"`
`"\x00\x00meta2\xff\xff"`
`"\x00\x00meta2b"`
`"\x00range-tree-root"`

All modified on a split, which is what's happening in this test. Maybe the timestamps encoded there are ending up with different varint sizes because they're different? That's just idle speculation. We need to print the values out and watch for next failure.

**Comment by tschottdorf** [comment]
Yeah. I still thing it's some kind of nondeterminism, timestamps sounds reasonable. Now I'm curious what we'll find.

**Comment by spencerkimball** [comment]
The test for the additional diagnostics failed...and tada, the answer was revealed.

Normally the random priority for the transaction take the full size of the int64, but in a reasonable fraction of the time it's small enough to take one less byte in the varint encoding. I imagine an even smaller fraction of the time it'll take two less bytes.

Now, how to fix it...?

**Comment by spencerkimball** [comment]
for reference:

`I0502 19:39:13.275446   27918 mvcc.go:1416] diag: "\x00\x00meta1\xff\xff" meta  k=13 v=89
I0502 19:39:13.275482   27918 mvcc.go:1417] meta: txn:<name:"split range 1 at \"b\"" key:"b" id:"Ib*\\\0334I_\273\322\225wh|Q\003" priority:1509503700 isolation:SERIALIZABLE status:PENDING epoch:0 timestamp:<wall_time:0 logical:58 > orig_timestamp:<wall_time:0 logical:58 > max_timestamp:<wall_time:0 logical:58 > certain_nodes:<> > timestamp:<wall_time:0 logical:58 > deleted:false key_bytes:12 val_bytes:42 , encoded="\nK\n\x14split range 1 at \"b\"\x12\x01b\x1a\x10Ib*\\\x1b4I_\xbbҕwh|Q\x03 \xd4\xe5\xe4\xcf\x05(\x000\x008\x00J\x04\b\x00\x10:R\x04\b\x00\x10:Z\x04\b\x00\x10:b\x00\x12\x04\b\x00\x10:\x18\x00 \f(*"`

`I0502 23:49:39.254694     277 mvcc.go:1416] diag: "\x00\x00meta1\xff\xff" meta  k=13 v=88
I0502 23:49:39.254834     277 mvcc.go:1417] meta: txn:<name:"split range 1 at \"b\"" key:"b" id:"\247i\201\354&(N\t\256@Z\023\304%J&" priority:184625193 isolation:SERIALIZABLE status:PENDING epoch:0 timestamp:<wall_time:0 logical:58 > orig_timestamp:<wall_time:0 logical:58 > max_timestamp:<wall_time:0 logical:58 > certain_nodes:<> > timestamp:<wall_time:0 logical:58 > deleted:false key_bytes:12 val_bytes:42 , encoded="\nJ\n\x14split range 1 at \"b\"\x12\x01b\x1a\x10\xa7i\x81\xec&(N\t\xae@Z\x13\xc4%J& \xa9ЄX(\x000\x008\x00J\x04\b\x00\x10:R\x04\b\x00\x10:Z\x04\b\x00\x10:b\x00\x12\x04\b\x00\x10:\x18\x00 \f(*"`

**Comment by mrtracy** [comment]
We could just use keybytes instead of live bytes... This test doesn't
necessarily need to exhaustively verify the values.

We could also replace deepequal with a different  comparison that tolerates
some variance.

**Comment by spencerkimball** [comment]
Good point. I'll make that change.
