### ISSUE TITLE
bazci: segmentation fault when crdb compilation fails

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#89106]
**Describe the problem**

We occasionally see `bazci` crashing with a segmentation fault; it seems like this happens when there's a compilation error in the build process.

Here's the stack trace for one of the failures:

```
[Run unit tests] panic: runtime error: invalid memory address or nil pointer dereference
[Run unit tests] [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x80443e]
[Run unit tests] 
[Run unit tests] goroutine 1 [running]:
[Run unit tests] main.processBuildEventProtocolLog({0x7ffc097ded65, 0x4}, {0xc000028870?, 0x1?})
[Run unit tests] 	main/pkg/cmd/bazci/bazci.go:192 +0xf1e
[Run unit tests] main.bazciImpl(0xc804a0?, {0xc000198dc0?, 0xa, 0xb})
[Run unit tests] 	main/pkg/cmd/bazci/bazci.go:103 +0x511
[Run unit tests] github.com/spf13/cobra.(*Command).execute(0xc804a0, {0xc0000240d0, 0xb, 0xb})
[Run unit tests] 	github.com/spf13/cobra/external/com_github_spf13_cobra/command.go:856 +0x67c
[Run unit tests] github.com/spf13/cobra.(*Command).ExecuteC(0xc804a0)
[Run unit tests] 	github.com/spf13/cobra/external/com_github_spf13_cobra/command.go:974 +0x3bd
[Run unit tests] github.com/spf13/cobra.(*Command).Execute(...)
[Run unit tests] 	github.com/spf13/cobra/external/com_github_spf13_cobra/command.go:902
[Run unit tests] main.main()
[Run unit tests] 	main/pkg/cmd/bazci/main.go:42 +0x7b
[Run unit tests] Process exited with code 2
```

**Recent occurrences**

* https://teamcity.cockroachdb.com/viewLog.html?buildId=6714145&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_BazelUnitTests
* https://teamcity.cockroachdb.com/viewLog.html?buildId=6561747&buildTypeId=Cockroach_UnitTests_BazelUnitTests&tab=buildResultsDiv

Jira issue: CRDB-20120

Epic CRDB-15060

**Comment by rickystewart** [comment]
https://github.com/cockroachdb/cockroach/pull/89845 will probably fix this by rewriting how we do our build event processing.

**Comment by renatolabs** [comment]
@rickystewart I believe we can close this one now?

**Comment by renatolabs** [comment]
Closing as I believe this is fixed. Feel free to reopen if that's not the case.
