### ISSUE TITLE
sql: provide session variable to allow for `FOR UPDATE` locks to be replicated

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#89111]
**Is your feature request related to a problem? Please describe.**

This tracks the idea that in some cases, it is desirable for `FOR UPDATE` locks to be durable. This will reduce the chance for a client to unknowingly lose a lock (though it will not fully eliminate that chance if either the transaction coordinator or the client itself is partitioned or aborted, perhaps due to deadlock or a higher-priority pusher). 

**Describe the solution you'd like**
Add a session variable which allows `FOR UPDATE` locks to lead to a durable lock being replicated. 

**Additional context**
There are a few problems with this:
1) We already don't wait for replication in the common case because we find transaction pipelining is important
2) Work to buffer writes is going to avoid replicating locks (IIUC). 

Jira issue: CRDB-20123

**Comment by nvanbenschoten** [comment]
Replacing with https://github.com/cockroachdb/cockroach/issues/100193, which is a more general issue describing the same ask.
