### ISSUE TITLE
Unreachable code in `roachtest/tests`

### ISSUE THREAD

**Issue by chavacava** [cockroachdb/cockroach#89141]
The `cleanupFn` will never run.

https://github.com/cockroachdb/cockroach/blob/88bd1b249e18409c8cbe32303b818721e23b422e/pkg/cmd/roachtest/tests/mixed_version_decl_schemachange_compat.go#L59-L60

Jira issue: CRDB-20131

**Comment by ajwerner** [comment]
@fqazi please reverse these statements or add a defer
