### ISSUE TITLE
storage: reconsider struct comparisons with Go 1.20

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#89199]
As described in https://github.com/cockroachdb/cockroach/issues/88818#issuecomment-1261350936, Go 1.19 has a significant performance regression when comparing structs. Because of this, we had to introduce manual struct comparisons (explicitly listing each field) and give up certain inlining opportunities to recover the performance.

This regression will been fixed in Go 1.20, but won't be backported to 1.19. We should consider reverting back to using struct comparisons once we build with Go 1.20. Relevant changes:

* #88911
* #88989

Jira issue: CRDB-20169

**Comment by nicktrav** [comment]
@jbowens - is this all done now that we have #110808 landed?

**Comment by jbowens** [comment]
> @jbowens - is this all done now that we have https://github.com/cockroachdb/cockroach/pull/110808 landed?

Need #111375 too
