### ISSUE TITLE
cdc: more load balancing things to try

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#89198]
Even with https://github.com/cockroachdb/cockroach/pull/88672 we still get a long tail during initial scan, some nodes have much more work to do than others. Things to try:

* Look for bugs in existing load balancing
* Lower the "tolerance" factor in existing load balancing
* Replanning, but during initial scan
* Grant changefeed aggregators "leases" on ranges to export that expire over time, and have a node that runs out of leased ranges call home to the coordinator to get a new lease
* Write a more complex planning oracle that does upfront computation to find a more optimal distribution
* Go the other way and try using a RandomOracle
* Multidimensional ranges

Jira issue: CRDB-20172

Epic CRDB-24463

**Comment by miretskiy** [comment]
Feature was deleted;
