### ISSUE TITLE
*: lower default GC TTL

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#89233]
This is tracking issue to lower the default GC TTL from 25h. There's [an internal document](https://docs.google.com/document/d/1Yy6J_dY0Ifg9w49eOG2Qe0U78DXo6x6OGfhBxJtQj-k/edit#heading=h.g5v44xxwbgoo) that more fully spells out some of the motivations and requisite steps, the text for which was copied over below. There's also this [internal slack thread](https://cockroachlabs.slack.com/archives/C0366GQV668/p1664996915848069).

**Is your feature request related to a problem? Please describe.**

The default GC TTL today is 25h, which means overwritten values in the last 25h window are retained. This translates to higher storage use and for outbox-like workloads where rows are deleted frequently, can make for [costlier reads CPU wise](https://groups.google.com/a/cockroachlabs.com/g/postmortems/c/OFofoPxDnZs/m/lprG44gaBAAJ) since they have to scan over a larger number of overwritten values to get to the one of interest (this is [not fundamental](https://github.com/cockroachdb/pebble/issues/1170)). Since all versions of key are stored within a single range (we split along key boundaries, not within different values of a key), we’ve seen incidents where we have large (>> 512 MB) [unsplittable ranges](https://www.cockroachlabs.com/docs/stable/common-errors.html#split-failed-while-applying-backpressure-are-rows-updated-in-a-tight-loop) causing cluster instability: snapshot timeouts all get triggered, other snapshots get queued behind it, range starts [backpressuring writes](https://github.com/cockroachdb/cockroach/blob/55fc27d66f09ca239fce2170f8ab904727ec268d/pkg/kv/kvserver/replica_backpressure.go#L26-L29) (can be indistinguishable from an outage). 

We chose a default of 25h originally to accommodate daily incremental backups with revision history. They fail ([informatively](https://www.cockroachlabs.com/docs/v22.1/common-errors#protected-ts-verification-error)) if the data you are trying to backup was GC-ed, which happens when incremental backups are taken less frequently than the GC periods for any of the objects in the base backup. In 22.2 however scheduled backups “[chain together](https://github.com/cockroachdb/cockroach/issues/67282)” protected timestamp records, which lets your scheduled backup protect only what’s needed and ensure coverage of revision history across each incremental backup. The short of it is we no longer need a 25h default, hence this issue.

**Describe the solution you'd like**

Lower it to something like 4h or 1.5h.

Jira issue: CRDB-20144

**Comment by irfansharif** [comment]
@shralex, @nvanbenschoten, @williamkulju, @mwang1026.

**Comment by ajwerner** [comment]
@fqazi is actively working on https://github.com/cockroachdb/cockroach/issues/84911. It should block any change to the GC TTL. A fix should come together soon.

**Comment by miretskiy** [comment]
CDC would need to address https://github.com/cockroachdb/cockroach/issues/89450
