### ISSUE TITLE
sql: revoking `CREATE` privilege from public schema doesn't take effects.

### ISSUE THREAD

**Issue by chengxiong-ruan** [cockroachdb/cockroach#89234]
**Describe the problem**
Looks like we always put a public user privilege in a public schema and by default the public user has the `CREATE` privilege on it. This make `REVOKE CREATE ON SCHEMA public FROM xxx` doesn't take any effect because [this logic](http://github.com/cockroachdb/cockroach/blob/9794be4c70f2591c36a3b1213ed3f2dd7ef0e481/pkg/sql/authorization.go#L165-L165) which always return a success for a public schema.

**To Reproduce**
(1) Connect to a local cluster as root:
```bash
./cockroach-short sql --insecure
```
(2) Create a test user:
```
CREATE USER test_user;
```
(3) Revoke `CREATE` from the test user:
```
REVOKE CREATE ON SCHEMA PUBLIC FROM test_user;
```
obviously this does nothing heh because we don't have user privilege in the schema descriptor for this user at all.
(4) Connect as test_user:
```bash
./cockroach-short sql --insecure -u test_user
```
(5) Create a table and it succeed:
```
CREATE TABLE t(a INT);
```

**Expected behavior**
To be compatible with postgres, a permission denied error should be returned for `CREATE` statements after the privilege being revoked.

Jira issue: CRDB-20145

**Comment by rafiss** [comment]
Step 3 also should include: `REVOKE CREATE ON SCHEMA public FROM public`

**Comment by rafiss** [comment]
confirmed that with that additional step, the permission check is correct
```
test_user@localhost:26257/defaultdb> CREATE TABLE t(a INT);
ERROR: user test_user does not have CREATE privilege on schema public
SQLSTATE: 42501
```

**Comment by chengxiong-ruan** [comment]
thanks!
