### ISSUE TITLE
docs / nodejs support:   using a conn URL specifying a unix socket makes the node app attempt to connect using an erroneous port number

### ISSUE THREAD

**Issue by sue-enuga** [cockroachdb/cockroach#89254]
**Describe the problem**
When trying to use the following document to connect to cockroach from local cluster using the steps from the doc :
https://www.cockroachlabs.com/docs/cockroachcloud/quickstart.html?filters=local
unable to connect to the local cluster. 
Please describe the issue you observed, and any steps we can take to reproduce it:
yes, If you can see in the image below, I followed the exact steps from the doc and it fails to connect to the local instance.
![image](https://user-images.githubusercontent.com/113870920/193698920-84b1087f-e73b-4e13-bdfb-22766e51374d.png)

**To Reproduce**
Follow the steps from the doc :https://www.cockroachlabs.com/docs/cockroachcloud/quickstart.html?filters=local 
What did you do? Describe in your own words.
I followed the exact steps from this doc. 
https://www.cockroachlabs.com/docs/cockroachcloud/quickstart.html?filters=local
If possible, provide steps to reproduce the behavior:
see above
Also, NOTE: have been consistently failing. 

**Expected behavior**
Be able to connect to the cluster using the generated DATABASE_URL. (sql/unix) string. 

**Additional data / screenshots**
![image](https://user-images.githubusercontent.com/113870920/193698920-84b1087f-e73b-4e13-bdfb-22766e51374d.png)

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
MAC ( new installation)
**Additional context**
What was the impact?

https://www.cockroachlabs.com/docs/v22.1/install-cockroachdb-mac.html - this is the initial document which is also listed in STEP1 of the current document which was followed to set up cockroach db in local.

Jira issue: CRDB-20149

**Comment by ianjevans** [comment]
I can only reproduce this particular error with the Node.js example. 

~~~ shell
❯ node app.js
error connecting: Error: connect ENOENT /var/folders/r5/7q2jzh4n0rj5lgcwc47st58m0000gp/T/demo3518378053/.s.PGSQL.5432
~~~

E.g. the Go example:

~~~ shell
❯ go run main.go
2022/10/04 10:30:32 Hello world!
~~~

While looking into this, I did see that there's a bug in the doc output that hides the selector for other languages for local clusters. Fixing in DOC-5875.

**Comment by knz** [comment]
@sue-enuga was there a particular reason why you are copying the URL for `(sql/unix)` and not the one for `(sql)` printed a few lines above it?

**Comment by knz** [comment]
Oh I see what's going on. It appears that the Node.js driver supports unix sockets, but does not recognize the `port=...` specification in the URL at the end. It should use that to create the socket name, and instead it uses the default 5432 from postgres.

@rafiss do you know anything about connection URLs in node.js?

**Comment by rafiss** [comment]
I've isolated the problem to the [pg-connection-string](https://github.com/brianc/node-postgres/tree/master/packages/pg-connection-string) package.

```
❯ node
Welcome to Node.js v18.8.0.
Type ".help" for more information.
> const pg_conn = require('pg-connection-string')
undefined

> pg_conn.parse('postgresql://demo:demo54001@/defaultdb?host=%2Fvar%2Ffolders%2F1_%2F_kcb28_94w16ml515w877ynm0000gn%2FT%2Fdemo1215025694&port=26258')
[Object: null prototype] {
  host: '/var/folders/1_/_kcb28_94w16ml515w877ynm0000gn/T/demo1215025694',
  port: null,
  user: 'demo',
  password: 'demo54001',
  database: 'defaultdb'
}
```

I tracked down the problem to this line: https://github.com/brianc/node-postgres/blob/9dfb3dccbfd78c088f093dd4c0c11bda7ccd2465/packages/pg-connection-string/index.js#L34

The following diff fixes it: 
```
diff --git a/packages/pg-connection-string/index.js b/packages/pg-connection-string/index.js
index 995ff06..23ab102 100644
--- a/packages/pg-connection-string/index.js
+++ b/packages/pg-connection-string/index.js
@@ -31,7 +31,7 @@ function parse(str) {
   config.user = auth[0]
   config.password = auth.splice(1).join(':')

-  config.port = result.port
+  config.port = result.port || config.port
   if (result.protocol == 'socket:') {
     config.host = decodeURI(result.pathname)
     config.database = result.query.db
```

**Comment by knz** [comment]
are you sending a pr upstream?

**Comment by rafiss** [comment]
Sent: https://github.com/brianc/node-postgres/pull/2833

**Comment by rafiss** [comment]
The fix has been merged upstream https://github.com/brianc/node-postgres/pull/2833
