### ISSUE TITLE
storage: performance regression in BenchmarkMVCCPutDelete_Pebble

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#89253]
**Describe the problem**

Currently, on the 22.2 release branch there is a ~20% performance regression in `BenchmarkMVCCPutDelete_Pebble`, relative to 22.1:

```bash
$ benchstat bench-22.1 bench-22.2
name                     old time/op  new time/op   delta
MVCCPutDelete_Pebble-16  8.36µs ± 2%  10.09µs ± 1%  +20.71%  (p=0.000 n=10+10)
```

**To Reproduce**

```bash
$ ./dev bench ./pkg/storage --filter MVCCPutDelete_Pebble --count 10 -v --stream-output --ignore-cache
```

Jira issue: CRDB-20148

Epic CRDB-2624

**Comment by nicktrav** [comment]
CPU profile comparison shows that we started calling `maybeGetValue`, which looks to be making up a large chunk of the 20% delta:

22.1:

<img width="1699" alt="Screen Shot 2022-10-03 at 3 51 20 PM" src="https://user-images.githubusercontent.com/804457/193699787-d7261944-b4be-4f53-ad02-871a1526bba2.png">

22.2:

<img width="1699" alt="Screen Shot 2022-10-03 at 3 51 24 PM" src="https://user-images.githubusercontent.com/804457/193699803-2f84542f-e51a-4808-8a02-d2b7b1c9376d.png">

**Comment by nicktrav** [comment]
Was able to bisect down to this change: 00af7d7089d90ccaf9d12724872881064c68e9aa

Before vs. after:

```bash
$ benchstat bench-bad-1 bench-bad
name                     old time/op  new time/op   delta
MVCCPutDelete_Pebble-16  8.32µs ± 2%  10.37µs ± 2%  +24.61%  (p=0.000 n=10+10)
```

Specifically, it looks like it was the addition of a `valueFn`:

https://github.com/cockroachdb/cockroach/blob/73f8ee660b19c22c4db1d8d1847728547642804f/pkg/storage/mvcc.go#L1376-L1381

**Comment by erikgrinaker** [comment]
I thought we could trivially fix this by deriving it e.g. from the MVCC stats adjustments, where we've already read the existing value (that's the `mvccGetMetadata` in those profiles). However, this is complicated by transactions rewriting their intents, which may need to read a different version than the metadata entry. I still think we can come up with a fix, but it may be a bit more gnarly than we're comfortable backporting this late in the game. I'll see what I can come up with.
