### ISSUE TITLE
roachtest: re-enable tests skipped on ARM64 because they need older releases

### ISSUE THREAD

**Issue by healthy-pod** [cockroachdb/cockroach#89268]
We need to skip some roachtests on ARM64 because they depend on previous releases and we only have one (experimental) release on ARM64 at the moment. This issue will be used to track re-enabling them on the next release.

Jira issue: CRDB-20179

**Comment by erikgrinaker** [comment]
Yo, we found this skipped test:

https://github.com/cockroachdb/cockroach/blob/8859c7685a438a6a508f5adc4fab070fa08952f9/pkg/cmd/roachtest/tests/tpcc.go#L366-L368

But this applies to the machine running the roachtest, not the servers running the cluster. So it's effectively not possible to launch this roachtest in GCP from a M1 MacBook. We should change the checks such that they're only skipped when the cluster is running on arm64.

**Comment by irfansharif** [comment]
Now the 22.2 is out, can we get rid of these checks for master/23.1? The predecessor version (22.2) has the Arm64 binaries, right?

**Comment by healthy-pod** [comment]
@erikgrinaker sorry for not seeing this earlier! I opened #94868 to only skip the tests if running locally.

**Comment by healthy-pod** [comment]
> Now the 22.2 is out, can we get rid of these checks for master/23.1? The predecessor version (22.2) has the Arm64 binaries, right?

@irfansharif true with an exception and a note:

1) some tests need more than a single older release so those tests will need to change or wait
2) roachprod doesn't currently know about ARM64 binaries and at least some (I think all?) roachtests playing with version upgrades depend on it figuring where to get the binaries from (see https://github.com/cockroachdb/cockroach/blob/master/pkg/roachprod/install/staging.go#L180)

**Comment by renatolabs** [comment]
> some tests need more than a single older release

There's only one such test at the moment (AFAIK), so ideally we want to skip just that one test.

> roachprod doesn't currently know about ARM64 binaries

Created #94957 to address that. Then we should be able to re-enable the vast majority of upgrade tests.

**Comment by srosenberg** [comment]
All roachtests, with the exception of [cdc](https://github.com/cockroachdb/cockroach/issues/103888), have been un-skipped in https://github.com/cockroachdb/cockroach/pull/103710
