### ISSUE TITLE
Ability to view in DB Console and have a metric for "queries per user" to be sent to Datadog

### ISSUE THREAD

**Issue by nikhilgchopra** [cockroachdb/cockroach#89275]
**Is your feature request related to a problem? Please describe.**
Currently we are unable view in the DB Console which user executed which query in on the database.

**Describe the solution you'd like**
Ability to view details of queries executed by a single or multiple users in the DB Console, some salient points here:
1) be able to record and send a single metric(s) per user to Datadog
2) DB Console page has filters to specify a user, time range of query execution, time duration of the query and query text
3) DB Console may display multiple users or a single user as per convenience 

**Describe alternatives you've considered**
We have checked with the SQL team to understand alternatives and believe querying System tables is the only way to do it currently. This is unfortunately not feasible for the customer.

**Additional context**
N/A

Jira issue: CRDB-20184

Epic CRDB-32139

**Comment by thtruo** [comment]
Thanks for creating this issue @nikhilgchopra. Note that we don't have facilities today to report or surface per-user metrics. However, much of the request here is in understanding query activity and filtering/attributing to specific users within the DB Console. I'm going to re-assign to Kevin Ngo, the PM leading the SQL Observability product area, for triage
