### ISSUE TITLE
gcjob: update status to reflect when GC job is blocked on PTS 

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#89289]
Currently a GC job will wait for PTS to expire, as it should, and will _log_ the fact it is blocked on the PTS, but its visible status in SHOW JOBS and the DB Console will remain "waiting for GC", meaning one has to get the logs and dig through them to determine why it isn't progressing. 

It should probably change its "running status" to "Waiting for read protection to expire" or something maybe even including the ID. 

Jira issue: CRDB-20193

**Comment by ajwerner** [comment]
Starting in 23.1 and 22.2 when the range deletion tombstone is enabled, the gc job won't know about protected timestamps. We could do something for 22.1-22.2.

**Comment by postamar** [comment]
Going to close this because we're not going to do anything for 22.2 and below. Anyone feeling that we should, please reopen this issue.
