### ISSUE TITLE
changefeedccl: reduce CPU use in CSV encoder

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#89313]
Recent work on CSV encoder was myopically focused on speed and memory utilization at the expense of CPU. (I'm allowed to use the word myopically because it was my work and I'm also literally a little myopic.) This turns out to have been maybe not the best idea because of the "nprocs" work happening in parallel: we're now able to tune changefeeds to be CPU-bound, so a CPU-heavy encoder is in effect slower as we can't run as many of it in parallel. We should look at ways to reduce CPU utilization, hopefully without adding back in any of those allocs.

Jira issue: CRDB-20201

**Comment by miretskiy** [comment]
Recent performance related work addressed this issue.
