### ISSUE TITLE
doc: suggesting to run multiple nodes per host likely yields OOM errors

### ISSUE THREAD

**Issue by nictuku** [cockroachdb/cockroach#8931]
```
build:     beta-20160728 @ 2016/07/28 17:01:45 (go1.6.3)
admin:     http://roach3:8080
sql:       postgresql://root@roach3:26257?sslmode=disable
logs:      cockroach-data/logs
store[0]:  path=cockroach-data
join[0]:   roach1
build:     beta-20160728 @ 2016/07/28 17:01:45 (go1.6.3)
admin:     http://roach3:8080
sql:       postgresql://root@roach3:26257?sslmode=disable
logs:      cockroach-data/logs
store[0]:  path=cockroach-data
join[0]:   roach1
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
SIGABRT: abort
PC=0x7f85ec300067 m=12
signal arrived during cgo execution

goroutine 31 [syscall, locked to thread]:
runtime.cgocall(0x12478a0, 0xc820b0c960, 0x0)
        /usr/local/go/src/runtime/cgocall.go:123 +0x11b fp=0xc820b0c910 sp=0xc820b0c8e0
github.com/cockroachdb/cockroach/storage/engine._Cfunc_DBIterNext(0x7f85de1e1008, 0x7f85de1e1000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        ??:0 +0x67 fp=0xc820b0c960 sp=0xc820b0c910
github.com/cockroachdb/cockroach/storage/engine.(*rocksDBIterator).Next(0xc820a62140)
        /go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:1142 +0xa3 fp=0xc820b0ca38 sp=0xc820b0c960
github.com/cockroachdb/cockroach/storage/engine.dbIterate(0x7f85c9275fc0, 0x7f85eceea998, 0xc820931320, 0x2739e43, 0x1, 0x1, 0x0, 0x0, 0xc820b21a70, 0x26, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:1425 +0x3ce fp=0xc820b0cb48 sp=0xc820b0ca38
github.com/cockroachdb/cockroach/storage/engine.(*rocksDBSnapshot).Iterate(0xc820931320, 0x2739e43, 0x1, 0x1, 0x0, 0xc800000000, 0xc820b21a70, 0x26, 0x30, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:675 +0x115 fp=0xc820b0cbe8 sp=0xc820b0cb48
github.com/cockroachdb/cockroach/storage/engine.MVCCFindSplitKey(0x7f85eceeb200, 0xc820d22690, 0x7f85eceea998, 0xc820931320, 0x1, 0x2739e43, 0x1, 0x1, 0xc820b21a70, 0x26, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/engine/mvcc.go:2136 +0xa17 fp=0xc820b0ced0 sp=0xc820b0cbe8
github.com/cockroachdb/cockroach/storage.(*Replica).AdminSplit(0xc8203b6600, 0x7f85eceeb200, 0xc820d22690, 0x2aa40d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/replica_command.go:2286 +0x1ee fp=0xc820b0d0b8 sp=0xc820b0ced0
github.com/cockroachdb/cockroach/storage.(*Replica).addAdminCmd(0xc8203b6600, 0x7f85eceeb200, 0xc820d22690, 0x146f3791740b0dc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:1126 +0x874 fp=0xc820b0d370 sp=0xc820b0d0b8
github.com/cockroachdb/cockroach/storage.(*Replica).Send(0xc8203b6600, 0x7f85eceeb200, 0xc820d22690, 0x146f3791740b0dc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/replica.go:833 +0x5db fp=0xc820b0d530 sp=0xc820b0d370
github.com/cockroachdb/cockroach/internal/client.SendWrappedWith(0x7f85ecf110c0, 0xc8203b6600, 0x7f85eceeb200, 0xc820d22690, 0x146f3791740b0dc0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/internal/client/sender.go:54 +0x1a9 fp=0xc820b0d710 sp=0xc820b0d530
github.com/cockroachdb/cockroach/storage.(*splitQueue).process(0xc8201c6630, 0x7f85eceeb200, 0xc820d22690, 0x146f3791740b0dc0, 0x0, 0xc8203b6600, 0xc820942000, 0x17, 0x20, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/storage/split_queue.go:124 +0xf2a fp=0xc820b0daf8 sp=0xc820b0d710
github.com/cockroachdb/cockroach/storage.(*baseQueue).processReplica(0xc8201c6630, 0xc8203b6600, 0xc82031cb80, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/storage/queue.go:480 +0xc5f fp=0xc820b0dd38 sp=0xc820b0daf8
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1.1()
        /go/src/github.com/cockroachdb/cockroach/storage/queue.go:423 +0x4e fp=0xc820b0dda0 sp=0xc820b0dd38
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunTask(0xc82030ec60, 0xc820b0de68, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:215 +0x150 fp=0xc820b0de00 sp=0xc820b0dda0
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
        /go/src/github.com/cockroachdb/cockroach/storage/queue.go:427 +0x212 fp=0xc820b0df60 sp=0xc820b0de00
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82030ec60, 0xc8202df260)
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d fp=0xc820b0df80 sp=0xc820b0df60
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820b0df88 sp=0xc820b0df80
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x62

```

Showing only the first goroutine since I don't think the other ones are relevant.

My system was probably running out of memory and that cgo function failed to allocate memory. This in itself isn't surprising - I have three nodes running on the same physical server, inside docker containers - based on the `getting started` instructions. 

I guess I should set a cache limit for my node instead of using the default settings. I'm doing a lot of mutations on my database.

But I think CDB should run very well for the most common case: people following the basic instructions on the site to try out the syste,. If the basic instructions on the site include running 3 nodes on the same server, the cache size settings could by default be less than 25% per node?

**Comment by knz** [comment]
I think this is a documentation issue rather than a product issue.
Indeed if docs suggest to start multiple nodes per physical machine (which is not production best practice, mind you, but convenient for learning/testing) then the doc should also explain to the user *in the same place* how to configure each node to use less memory, lest the problem you describe happen.

**Comment by jseldess** [comment]
Thanks for opening this issue, @nictuku, and sorry for the delay. 

@mberhault, @spencerkimball, in our getting started docs (running multiple nodes locally), we could update the `start` commands to include a non-default cache size to prevent OOM errors from happening. But I'm hesitant to complicate our getting started docs by adding a flag to the commands.  

Instead, I'm wondering if, when we know it's a local cluster (no `--insecure` and no `-cert`, so listening only on `localhost`) we could use a different default cache size per node so the user doesn't need to pass that manually?

**Comment by nictuku** [comment]
Note that this logic specifically wouldn't help with the local docker
cluster use case since the tutorial flags are different IIRC. (I'm not
confident)

**Comment by bdarnell** [comment]
I don't think we want to add more "magic" here - the way that `--insecure` interacts with `--host` is confusing enough. This would introduce a difference between local processes and docker, etc. We should just explain that if you're running multiple nodes on one machine, you need to set the cache flags accordingly. 

We should also emphasize that running multiple nodes on one machine is something that only makes sense for testing. Other than proving to yourself that the system works, users of cockroachdb (as opposed to developers of cockroachdb) probably shouldn't do it. Maybe the progression in the docs should go straight from a single local node to deploying in the cloud, with multiple local nodes available as an option for people who really want to try it that way.

**Comment by jseldess** [comment]
All, create an issue for this in the docs repo. Any reason to leave this open?

**Comment by jseldess** [comment]
Clarified docs in this [PR](https://github.com/cockroachdb/docs/pull/652), so closing this issue.
