### ISSUE TITLE
release-22.2: backupccl: set disallowShadowingBelow to empty for RESTORE

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#89330]
In older releases, we set `disallowShadowingBelow` to empty for RESTORE. We should do the same for release-22.2.

disallowShadowingBelow used to be unconditionally set to logical=1. This permissive value would allow shadowing in case the RESTORE has to retry ingestions but served to force evaluation of AddSSTable to check for overlapping keys. It was believed that even across resumptions of a restore job, checkForKeyCollisions would be inexpensive because of our frequent job checkpointing. Further investigation in https://github.com/cockroachdb/cockroach/issues/81116 revealed that our progress checkpointing could significantly lag behind the spans we have ingested, making a resumed restore spend a lot of time in checkForKeyCollisions leading to severely degraded performance. We have never seen a restore fail because of the invariant enforced by setting disallowShadowingBelow to a non-empty value, and so we feel comfortable disabling this check entirely. A future release will work on fixing our progress checkpointing so that we do not have a buildup of un-checkpointed work, at which point we can reassess reverting to logical=1.

Jira issue: CRDB-20207

**Comment by msbutler** [comment]
22.2 backports (https://github.com/cockroachdb/cockroach/pull/89714, https://github.com/cockroachdb/cockroach/pull/89776)  have merged!
