### ISSUE TITLE
sql: add a way for sequence caching to be per-node rather than per-session

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#89338]
**Is your feature request related to a problem? Please describe.**

The current sequence `CACHE` implementation caches IDs per-session (and this matches the PostgreSQL behavior). If there are many short-lived sessions, then this behavior may not be helpful, and a lot of identifiers will be wasted.

**Describe the solution you'd like**
There should be a way to have the cache be per-node. All the sessions on the node can share the same cache, which can be concurrently accessed.

Some possible syntaxes:
- `[ [ PER NODE ] CACHE # ]`
- a new `serial_normalization` setting for `sql_sequence_cached_node`

Jira issue: CRDB-20209

**Comment by ale-dd** [comment]
@rafiss I would love to see this feature land :)
