### ISSUE TITLE
tests: Revive a skipped roachtest when master is 23.1

### ISSUE THREAD

**Issue by Xiang-Gu** [cockroachdb/cockroach#89345]
We decided to skip the roachtest `declarative_schema_changer/job-compatibility-mixed-version`
because it hangs on master with error
```
"running execution from '2022-10-04 21:11:14.507359' to '2022-10-04 21:11:15.273009' on 4 failed: non-cancelable: failed to satisfy [[ColumnType:{DescID: 175, ColumnFamilyID: 0, ColumnID: 1}, ABSENT], ABSENT] -dep-SameStagePrecedence-> [[Column:{DescID: 175, ColumnID: 1}, ABSENT], ABSENT] rule "column type removed right before column when not dropping relation"
```
when testing job-backward compatibility for a `DROP VIEW` stmt.

One can easily reproduce it with
```
roachtest run declarative_schema_changer/job-compatibility-mixed-version --local
```

The reason for this is we recently [merged a PR to master](https://github.com/cockroachdb/cockroach/pull/89086) that got rid of
 - the `isRelationBeingDropped` field, which is used in several dep-rules, and
 - [the hacky logic](https://github.com/cockroachdb/cockroach/pull/89086/files#diff-df7bbdca72312113609288aea89a183657305213f04667efb1861d190ec3b654L131-L145) that sets it.

This means, in a mixed version state, if we `DROP VIEW` on an upgraded node and later let an old node adopt the schema changer job, that old node will see this field as being `false` (even though it would have been `true` before that PR). Consequently, it activates [a dep rule](https://github.com/cockroachdb/cockroach/blob/c8507bc400e397ebdfc7e7aae1bcb4983ed7bcc8/pkg/sql/schemachanger/scplan/internal/rules/dep_index_and_column.go#L320-L321) (which was supposed to be suppressed exactly by this field) in the old node, causing a unsatisfiable error, and thus retries indefinitely.

Instead of reverting the abovementioned PR, we will skip this roachtest for now until master is on 23.1, at which time we can close this issue. More specifically, we will need to wait until `predecessor_version.json` has an entry for `23.1 : 22.2.*` AND `*t.BuildVersion()` is `v23.1xxx`.

Jira issue: CRDB-20212

**Comment by ajwerner** [comment]
I think the time has come.

**Comment by Xiang-Gu** [comment]
Maybe not? We still do not have an [entry](https://github.com/cockroachdb/cockroach/blob/e95c97fef11c4b1263bcccd4011c3fa1c70a6ff1/pkg/cmd/roachtest/tests/predecessor_version.json#L11) for 23.1 in `predecessor_version.json`

**Comment by ajwerner** [comment]
Ah, yeah, I guess that's fair.

**Comment by ajwerner** [comment]
now finally I think the time has come

**Comment by Xiang-Gu** [comment]
It turns out it's still not time (even if we have an entry in `predecessor_version.json` for `23.1:22.2xxx`), because `*t.BuildVersion()`, which is implemented as `git describe --abbrev=0 --tags --match='v[0-9]*'`, is still `v22.2.0-alpha.00000000`.

We have to wait until `*t.BuildVersion()` gives us `v23.1.xx`.

**Comment by rimadeodhar** [comment]
@Xiang-Gu: Can we unskip this test now to close out the issue?
