### ISSUE TITLE
changefeedccl: resume changefeed after successful IMPORT INTO

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/cockroach#89378]
IMPORT INTO requires that a table be taken offline. In turn, this cancels/fails the changefeed, so the changefeed will need to be recreated in order to resume.

This does not logically need to be the case. The changefeed should resume when the table comes back online, and should emit (catchup scan) the newly-imported rows. (Keep in mind, an IMPORT INTO can fail and roll back, so no rows should be emitted until the import completes.)

Per this [internal conversation](https://cockroachlabs.slack.com/archives/C9TGBJB44/p1664930564382899?thread_ts=1664810205.244919&cid=C9TGBJB44), the above does not require MVCC, it’s an addition to the current changefeed schema change code.

Jira issue: CRDB-20222

**Comment by miretskiy** [comment]
It's unlikely we will address this.  If the table is offline, restarting changefeed seems appropriate.
@amruss feel free to reopen.

**Comment by miretskiy** [comment]
Reopening since customers seem to be asking (occasionally).

**Comment by amruss** [comment]
Closing this: there are two options after an import into: (1) start a new changefeed from time high watermark +1, which would skip over all the new imported changes or (2) start a new changefeed with a full table scan. Neither of these are great options and the customer should make a choice as to what they want. We aren't going to make the choice on their behalf.
