### ISSUE TITLE
server: Raft status page fails to load: "range N was not found"

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#8940]
On the beta cluster, the raft status page is (currently) not loading the column for node 4, with the message "range N was not found" (with a different N each time). Node 4 was just restarted after an outage and is garbage-collecting many ranges; this may be a race when a replica GC is concurrent with the status request. The fix may be as simple as ignoring (some) errors from store.GetReplica while iterating.

**Comment by spencerkimball** [comment]
Not using this page, probably won't in the current form. Closing this for now.
