### ISSUE TITLE
sqlstats: decrease default rows persisted for stmt and txn stats tables

### ISSUE THREAD

**Issue by xinhaoz** [cockroachdb/cockroach#89452]
Currently, the default value for the maximum number of rows in `system.{statement,transaction}_statistics` is 1 million. [At full capacity, this is around 3gb](https://cockroachlabs.slack.com/archives/CUVEFUU3C/p1665006679579589?thread_ts=1664996410.967729&cid=CUVEFUU3C) which is too large for serverless clusters. 

Jira issue: CRDB-20258

Epic CC-6350

**Comment by maryliag** [comment]
this value should be decreased only for Serverless, but keep as 1M for all others
