### ISSUE TITLE
Inconsistent UX when starting nodes

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/cockroach#8953]
Nodes behave in difficult-to-intuit ways when starting; this is primarily driven by the behavior of `cockroach start`, which creates an insecure instance that only listens on local host. However, adding certain flags changes multiple elements of the node's behavior, even though they are not specified:
- `--host` changes the network locations that CockroachDB listens on, as well enabling SSL mode
- `--insecure` disables SSL mode, as well as changing the network location CockroachDB listens on from `localhost` to the local hostname

Talked to @bdarnell  and @mberhault  about this and they said that the reason was that `cockroach start` is meant to be easy to use as a local sandbox. However, it creates the inconsistencies mentioned above.
### Potential fixes
- `cockroach start` should not start in insecure mode. To start a local node with certs, you should run `cockroach start --insecure`.
- `cockroach start` and `cockroach start --insecure` should both have the same hostname.

**Comment by spencerkimball** [comment]
@sploiselle is this something you still want fixed? Do we get complaints about this from users?

@bdarnell @mberhault is this something we intend to fix for 1.0?

**Comment by mberhault** [comment]
This is the `--insecure` magic and flag inter-connectedness.
I believe we've had this argument a number of times, but nothing was ever resolved.

I'd be happy to re-open that can of worms and argue for flags whose default values don't depend on other flags.

**Comment by spencerkimball** [comment]
What I'd prefer you do is decide whether you're going to fix this for 1.0.

**Comment by mberhault** [comment]
Ok, let's fix this for 1.0.

Here's a quick proposal. I'm happy fleshing it out some more, but let's hear objections first.

Behavior summary:
* flags are no longer interconnected: changing one flag does not alter the default value of another
* `--insecure` is **always** required for non-SSL connections, both client and server-side.
* starting a single-node cockroach cluster is now: `cockroach start --insecure`.

Flag defaults and meanings:
* **--insecure**:
  * `default: false`
  * if `false`: look for certificates/keys and setup secure connections. Fail with error if improper SSL configuration found
  * if `true`: don't look for certificates/keys and run on insecure connections.
* **--host/--http-host**: default to all interfaces
* **cert files/keys** (either the current ones: per-file flags, or the new `--certs-dir`): sane defaults (easier with `--certs-dir`). Setting to the an empty value is not allowed in secure mode.

**Comment by mberhault** [comment]
I seem to recall @petermattis and @bdarnell having strong opinions about this.

**Comment by bdarnell** [comment]
I like this proposal. The requirement to explicitly specify `--insecure` or use certs is much less onerous with a default for `--certs-dir`.

**Comment by petermattis** [comment]
So `./cockroach start` and `./cockroach sql` will no longer "just work" from my dev environment?

**Comment by mberhault** [comment]
that's the proposal, yes.

**Comment by sploiselle** [comment]
From a usability perspective, I'd suggest making `cockroach start` and `cockroach start --insecure` behave in the same way; i.e. `cockroach start` with no flags infers the `--insecure` flag.

The primary impact of this is the default hostname that Cockroach listens on (as far as I remember). I can't recall what the impact of this issue was, but I believe I had misunderstood which interfaces Cockroach was listening on in these cases. You can see this in the `sql` URL that gets returned once starting the cluster:

**cockroach start**
```
ockroachDB node starting at 2017-04-04 11:16:30.544389935 -0400 EDT
build:      CCL beta-20170323 @ 2017/03/23 15:18:02 (go1.8)
admin:      http://localhost:8080
sql:        postgresql://root@localhost:26257?sslmode=disable
logs:       cockroach-data/logs
store[0]:   path=cockroach-data
status:     restarted pre-existing node
clusterID:  1d899ec9-ce7b-4a51-b89f-94c38e78fb0c
nodeID:     1
```

**cockroach start --insecure**
```
CockroachDB node starting at 2017-04-04 11:16:40.442254278 -0400 EDT
build:      CCL beta-20170323 @ 2017/03/23 15:18:02 (go1.8)
admin:      http://Seans-MBP:8080
sql:        postgresql://root@Seans-MBP:26257?sslmode=disable
logs:       cockroach-data/logs
store[0]:   path=cockroach-data
status:     restarted pre-existing node
clusterID:  1d899ec9-ce7b-4a51-b89f-94c38e78fb0c
nodeID:     1
```

**Comment by mberhault** [comment]
The current behavior listens on `localhost` when nothing is specified, and `all interfaces` when the user specifically says `--insecure` meaning that yes, they really want to run insecure and serve traffic externally.

Removing flag interdependence and having `--insecure` on by default would mean either always listening to `localhost` (which is annoying if running in secure mode), or always listening on all interfaces (which means the default in insecure and serving externally).

**Comment by bdarnell** [comment]
> So ./cockroach start and ./cockroach sql will no longer "just work" from my dev environment?

Once you set up certs in `~/.cockroach-certs`, the commands will "just work" in the future and then you'll have security too.

**Comment by sploiselle** [comment]
Is there a technical apprehension to implying the `--insecure` flag when no other flags are included? I feel like net-net, inferring the `--insecure` flag  isn't meaningfully different from a technical perspective from requiring it, however, it does provide superior usability.

If there's a concern about expected behavior, it could trip an additional warning like:

> Your cluster is listening on all interfaces! If you don't want this, run "cockroach start --insecure --host=localhost"

**Comment by petermattis** [comment]
> Once you set up certs in ~/.cockroach-certs, the commands will "just work" in the future and then you'll have security too.

We'd need to change the default URLs for the various load-generators too: `kv`, `ycsb`, `photos`, `block_writer`. Currently they all expect insecure by default.

**Comment by mberhault** [comment]
@sploiselle: the concern isn't technical, it's about clarity. Implied flags that change when other flags are specified are not particularly obvious. The auto `--insecure` flag is the current behavior, with default of `true`, but switching to `false` if you specify `--host`. I feel most of the confusion is around this automatic switch, and I'd very much like to get rid of it.

@petermattis: there's not much we can do about client default, unless we want to add a wrapper around our certs logic. Still, if you're concerned about running locally, it's easy enough to have an alias or script to fill in the flag for you.

**Comment by petermattis** [comment]
> there's not much we can do about client default

We can change all of the load generators to use a default URL which looks for certs in `~/.cockroach-certs`.

**Comment by mberhault** [comment]
That would require using the pending certificate manager in external clients, adding a dependency on the `cockroachdb/cockroach` repo just to build a URL (although we could add a small utility to `cockroach-go`).

**Comment by petermattis** [comment]
> That would require using the pending certificate manager in external clients...

Definitely don't want to add that dependency. I was imagining a small bit of code that looked in `~/.cockroach-certs`.

**Comment by mberhault** [comment]
We could do a naive one which just takes the username and assumes files are located at `~/.cockroach-certs/{ca.crt,client.<user>.crt,client.<user>.key}`. This would fail with "file not found" (or similar) if misconfigured.

**Comment by a-robinson** [comment]
Do we have examples of users being confused by this? I personally really like how easy it is to get started with cockroach locally, even if there's a possibility of a little confusion later on.

My only real problem with the current flags is that I just realized that setting `--insecure` can override setting `--host=localhost`, essentially breaking any node deployed with that combination of flags. That feels more like a bug than anything, though.

**Comment by mberhault** [comment]
We've had a few people trying to figure out why their server wasn't responding to external queries.
In addition to that, we've been trying to figure out 4 of 5 times how to document these properly, and whether the behavior was buggy or not. If even we get confused by the flag behavior, that's not a great sign.

**Comment by mberhault** [comment]
I'm going ahead and changing the behavior of the `--insecure` flag as part of #14703.

**Comment by jseldess** [comment]
Just chiming in here, a bit late. I agree with @a-robinson that the current local testing approach is as easy as it gets, just `cockroach start`. But I also agree with @mberhault that it's very unintuitive that `--host` behaves different in different scenarios. I think we explain it in the docs for [`--host`](https://www.cockroachlabs.com/docs/start-a-node.html#flags), but it comes across as convoluted (at least in part because it is convoluted).

If I understand @mberhault's intended change, I think things will be more intuitive all around:

* For an insecure local cluster, the only difference will be needing to pass `--insecure`. So `cockroach start --insecure` instead of `cockroach start`. The cluster will listen on all interfaces rather than just `localhost`, but that shouldn't be an issue for local testing anyway.
* For an insecure distributed cluster, nothing will change in terms of usability. You'll still need to pass `--insecure` and the node will still listen on all interfaces by default. 

@mberhault, is that right?

**Comment by mberhault** [comment]
That's correct.
The secure mode also gets simpler by looking in `~/.cockroach-certs` by default, so if you have generated certs in there, the node will just use them.

**Comment by jseldess** [comment]
@mberhault, one follow-up question: We'll look for certs in `~/.cockroach-certs` only when `--insecure` is NOT set, right?

**Comment by mberhault** [comment]
correct, `--insecure` means we don't attempt to setup secure connections, so we even look for certificates.

**Comment by mberhault** [comment]
`--host` and `--insecure` are now independent and default to `all interfaces` and `false` respectively.
