### ISSUE TITLE
kv: regression on BenchmarkKV/Scan/Native

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#89545]
Consider the following comparison between 22.1(edc586558d4128c0c33a044ee3d287bd138d782e) and 22.2(385bf90a93e54d1c1766017056726461e7b09615) of `BenchmarkKV` from `pkg/sql/tests/`:
```
KV/Scan/Native/rows=1-24              32.9µs ± 2%    33.5µs ± 1%    +1.94%  (p=0.004 n=10+10)
KV/Scan/Native/rows=10-24             37.0µs ± 1%    38.3µs ± 2%    +3.40%  (p=0.000 n=10+10)
KV/Scan/Native/rows=100-24            62.1µs ± 1%    69.6µs ± 2%   +11.94%  (p=0.000 n=10+10)
KV/Scan/Native/rows=1000-24            295µs ± 1%     365µs ± 1%   +23.56%  (p=0.000 n=9+10)
KV/Scan/Native/rows=10000-24          2.47ms ± 2%    3.11ms ± 1%   +25.95%  (p=0.000 n=10+9)
```
(Full comparison is available [here](https://gist.github.com/yuzefovich/f1a86d51374ef7bda401be18d15a3a25). The comparison was made with the following diff on 22.1 SHA:
```
--- a/pkg/util/goschedstats/runtime_go1.17.go
+++ b/pkg/util/goschedstats/runtime_go1.17.go
@@ -12,8 +12,8 @@
 // and go1.18. Before allowing newer versions, please check that the structures
 // still match with those in go/src/runtime.
 
-//go:build gc && go1.17 && !go1.19
-// +build gc,go1.17,!go1.19
+//go:build gc && go1.17 && !go1.20
+// +build gc,go1.17,!go1.20
 
 package goschedstats
``` 
to allow usage of go 1.19. The comparison was made with `./scripts/bench` that used `make` under the hood with `-benchtime=3s`.)

Since it's a "native" benchmark (i.e. we're using `kv.Txn.Scan` method directly), putting it on the KV board. Also conservatively marking it as a GA-blocker. Informs #87685.

Jira issue: CRDB-20296

**Comment by erikgrinaker** [comment]
We know that `MVCCScan` has a regression of about 8% on microbenchmarks due to the MVCC range tombstone work. Worth looking into where the remaining ~20% is coming from.

**Comment by arulajmani** [comment]
I bisected ~33% regression down to 3ebf6ee6e212eb0d8cce489f3b8e5a17ffbe1611

```
+ make bench PKG=./pkg/sql/tests BENCHTIMEOUT=5m BENCHES=BenchmarkKV/Scan/Native 'TESTFLAGS=-count 10 -benchmem'
name                          old time/op    new time/op    delta
KV/Scan/Native/rows=1-10        15.8µs ± 2%    15.4µs ± 1%   -2.37%  (p=0.001 n=10+9)
KV/Scan/Native/rows=10-10       17.5µs ± 2%    17.6µs ± 2%     ~     (p=0.165 n=10+10)
KV/Scan/Native/rows=100-10      28.9µs ± 1%    32.4µs ± 1%  +12.15%  (p=0.000 n=10+10)
KV/Scan/Native/rows=1000-10      136µs ± 1%     174µs ± 1%  +27.68%  (p=0.000 n=9+9)
KV/Scan/Native/rows=10000-10    1.13ms ± 1%    1.51ms ± 0%  +33.16%  (p=0.000 n=10+9)
```

I'll look at the change more closely tomorrow.

**Comment by arulajmani** [comment]
cc @andreimatei  -- you might no offhand if this regression is unavoidable given the commit message.

**Comment by nvanbenschoten** [comment]
Thanks for bisecting @arulajmani!

It's surprising to me that the regression is proportional to the number of rows that are returned. If this were a constant overhead, we would expect the opposite. Do we know why that commit caused the regression?

**Comment by arulajmani** [comment]
> Do we know why that commit caused the regression?

I didn't do much here after finishing the bisect; picking this up again today, will report back.

**Comment by arulajmani** [comment]
I diff-ed the two CPU profiles and it turns out that the regression stems from the verification we perform here: https://github.com/cockroachdb/cockroach/blob/0dade4009b34acb86f29fea22683c71bc68e39c7/pkg/kv/kvclient/kvcoord/transport.go#L214-L218

I think we unintentionally introduced this in the commit I linked above with the change it made to the `IsLocal` method. I'll send out a patch that fixes this. 

<img width="1145" alt="Screen Shot 2022-10-17 at 1 36 20 PM" src="https://user-images.githubusercontent.com/6366031/196245100-13744468-7e6a-42e4-9350-cf567b05c8b4.png">
