### ISSUE TITLE
changefeedccl: support Snappy compression

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/cockroach#89581]
Snappy seems popular enough, and we should support it in changefeeds.

A couple of packages:
- https://github.com/golang/snappy
- https://github.com/klauspost/compress/tree/master/snappy

Questions: Is Snappy mostly used for transport? Is it commonly used as a file format? Does it matter?

Jira issue: CRDB-20317

**Comment by amruss** [comment]
Snappy useful for single-message systems, TBD on whether sarama supports this

**Comment by amruss** [comment]
closing in favor of: https://github.com/cockroachdb/cockroach/issues/89580
