### ISSUE TITLE
Dropping userfiles_root_upload_payload table hangs indefinitely

### ISSUE THREAD

**Issue by smcvey** [cockroachdb/cockroach#89651]
Create a new 22.1.8 cluster.  Upload a simple csv file:

```
# cockroach userfile upload myfile.csv myfile.csv
```

Log into the SQL client and try and drop the userfiles_root_upload_payload table:

```
root@:26257/defaultdb> drop table userfiles_root_upload_payload;
```

It hangs indefinitely.  Running the drop with a high priority task works immediately.

Jira issue: CRDB-20358

**Comment by ajwerner** [comment]
Yeah yeah so what's going on here is that in an explicit transaction we use the legacy schema changer which will ignore concurrent schema changes. In 22.2 at least we repair this corruption in an upgrade migration.

This duplicates https://github.com/cockroachdb/cockroach/issues/80554
