### ISSUE TITLE
changefeedccl: Async flushes may produce out of order events

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#89683]
Failure observed on master:
```
Failed
=== RUN   TestChangefeedNemeses/cloudstorage
    helpers_test.go:743: making server as system tenant
    helpers_test.go:830: making cloudstorage feed factory
    nemeses_test.go:40: topic foo partition : saw new row timestamp 1665420895637060333.0000000000 after 1665420896550554241.0000000000 was seen
    nemeses_test.go:40: topic foo partition : saw new row timestamp 1665420895561568242.0000000000 after 1665420896550554241.0000000000 was seen
    --- FAIL: TestChangefeedNemeses/cloudstorage (11.99s)
```

The test ran with parallel workers, and async flushing enabled.

My best guess is that async flushing could produce the following:
  k@t1 is written to sink and causes flush f1
  k@t2 is written to sink and causes flush f2
  f2 completes before f1

(thanks @ajwerner for reporting this)

  

Jira issue: CRDB-20371

**Comment by miretskiy** [comment]
Come to think of it; I don't know if the above analysis is correct:

destination file name generated *synchronously*; so in the above scenario:
```
k@t1 is written to sink and causes flush f1
k@t2 is written to sink and causes flush f2
f2 completes before f1
```
f2, even if it completes before f1, would have a (lexicographically) later file name.
Hmm... The plot thickens.

**Comment by jayshrivastava** [comment]
Is the nemeses test aware of file names? It looks like it just validates ordering in terms of rows.

**Comment by miretskiy** [comment]
I haven't looked at the code recently -- do you know if what it's doing is correct?

**Comment by ajwerner** [comment]
I think that is does know about the file names, but it's wrong if a later file shows up before an earlier file, no?

**Comment by miretskiy** [comment]
Well, it's not wrong if it happens before RESOLVED, isn't it?

**Comment by miretskiy** [comment]
I don't know; I think making things appear in order is good regardless.

**Comment by ajwerner** [comment]
> Well, it's not wrong if it happens before RESOLVED, isn't it?

I think it is wrong. Regardless of `RESOLVED` we say that you won't see a newer version of a row before seeing an unseen older version.

**Comment by jayshrivastava** [comment]
I think correctness depends on how you define a new row and how you implement the end consumer. Before, you could consume files in the order they came. Post https://github.com/cockroachdb/cockroach/pull/88395, you need to check for monotonically increasing file IDs (which may not be so easy due to retries / skipped IDs) and consume them in that order. 

I don't believe we added this information to our docs, so we should add it. We could push some updates on our end to make implementing a consumer easier.

**Comment by ajwerner** [comment]
> Post https://github.com/cockroachdb/cockroach/pull/88395, you need to check for monotonically increasing file IDs (which may not be so easy due to retries / skipped IDs) and consume them in that order.

I don't think your language is sufficiently precise. If the sequence is 1, 3, the, IDs are monotonically increasing. I don't think we should accept this redefinition of correctness.

**Comment by miretskiy** [comment]
> I think it is wrong.

Things might not be as simple: Adding a queue or some such is not a problem.  That problem is that
such a change will largely remove the benefits of having async flushes in the first place -- you only gain
an ability to buffer next set of data, but you won't be able to write multiple files concurrently.

Our docs list resolved option as:
```
Resolved timestamp notifications on every Kafka partition can be used to provide strong ordering and global consistency guarantees by buffering records in between timestamp closures. Use the "resolved" timestamp to see every row that changed at a certain time.
```

The resolve option is what guided me in the first place: that's the real oracle I was concerned about.
I don't know if we implied stronger guarantees in our docs.
I think at best, it's a grey area.

**Comment by ajwerner** [comment]
I agree with Renato. 

> That problem is that
such a change will largely remove the benefits of having async flushes in the first place -- you only gain
an ability to buffer next set of data, but you won't be able to write multiple files concurrently.

I think the ability to overlay a file while filling another is worth something. If you want more concurrency, then you need to create more `ChangeAggregator`s or do something else. I don't feel okay giving up this correctness claim without at least opting into it. It seems pretty major to me.

**Comment by ajwerner** [comment]
@miretskiy and I spoke a bit offline. It seems like in the initial scan/export stage of things, we can safely flush in parallel because we know that the files have disjoint key sets. In that case, we can avoid any queuing. That's the high-throughput case we know about. In the steady state, where it's unsafe, we almost certainly can't sustain a higher throughput than a single write to the blob store anyway, so it probably doesn't matter.

There's some details to be worked out with regards to pulling this off, but it seems like the right answer

**Comment by ajwerner** [comment]
One simple approach would be to track the minimum and maximum timestamp of rows in a file. Then, also, track the files which are currently being written. If the file you want to write only has data at exactly the same timestamp as all the files currently being written, then it can skip the queue. If all the data is at the same timestamp, there is no hazard. That also happens to be the situation when you are doing an initial scan or export.
