### ISSUE TITLE
kvserver: make more coarse, or remove consistency checking rate limit

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#89695]
**Describe the problem**
In a profile, I see us spending as long waiting for quota as we do hashing data. That's wrong. The problem, as far as I can tell, is that we're synchronizing on every single row. That's silly. We should allocate batches of capacity, perhaps a few hundred kilobytes at a time, and wait for that. 
<img width="1493" alt="Screen Shot 2022-10-10 at 4 52 55 PM" src="https://user-images.githubusercontent.com/1839234/194950616-c574c8b8-c7db-4f80-a9b8-36aa7241678f.png">

Jira issue: CRDB-20380

**Comment by ajwerner** [comment]
In

**Comment by ajwerner** [comment]
@irfansharif seems like you want to get rid of this anyway

**Comment by ajwerner** [comment]
I guess the issue, on some level, is that there's concurrency and coordination overhead. What's interesting in the profile is that there's not that much time being spent on the fast path even though we know, more or less, that that must be getting called a lot. I think what we might want to do is picks some number of rows. I don't know if this is worth it. 

```go
--- a/pkg/kv/kvserver/replica_consistency.go
+++ b/pkg/kv/kvserver/replica_consistency.go
@@ -515,10 +515,34 @@ func (*Replica) sha512(
        var timestampBuf []byte
        hasher := sha512.New()
 
+       // Individual keys can be very small. There is overhead required to go to
+       // the rate limiter.
+       var rateLimitBudget int64
+       var totalRowSize, rowsSeen int64
+       const initialRowEstimate int64 = 1 << 10 // 1 KiB
+       const numRowsPerLimiterBatch = 256
+
        pointKeyVisitor := func(unsafeKey storage.MVCCKey, unsafeValue []byte) error {
                // Rate limit the scan through the range.
-               if err := limiter.WaitN(ctx, int64(len(unsafeKey.Key)+len(unsafeValue))); err != nil {
-                       return err
+               {
+                       size := int64(len(unsafeKey.Key) + len(unsafeValue))
+                       if size > rateLimitBudget {
+                               rowEstimate := initialRowEstimate
+                               if rowsSeen > 0 {
+                                       rowEstimate = (totalRowSize / rowsSeen) + 1
+                               }
+                               toAcquire := numRowsPerLimiterBatch * rowEstimate
+                               if needed := size - rateLimitBudget; toAcquire < needed {
+                                       toAcquire = needed
+                               }
+                               if err := limiter.WaitN(ctx, toAcquire); err != nil {
+                                       return err
+                               }
+                               rateLimitBudget += toAcquire
+                       }
+                       rowsSeen++
+                       totalRowSize += size
+                       rateLimitBudget -= size
                }
```

**Comment by erikgrinaker** [comment]
@pavelkalinnikov Maybe a quick win?

**Comment by pavelkalinnikov** [comment]
@ajwerner What was the cluster size at which you profiled this? When each node is >0.5 TB, the consistency check limit is likely to be always saturated, and some worker is likely waiting. I need to think about this more (there is probably some queuing formula that's relevant here), but intuitively it kinda makes sense that the wait is long. What do you believe should be the relation between wait and processing here?

**Comment by pavelkalinnikov** [comment]
Also, this consistency check task is async, and there is a fixed pool of them at a time, so this wait isn't critical IMO.

**Comment by pavelkalinnikov** [comment]
We used to have a hard limit on on the number of parallel running checks, but we recently removed it because the theoretical avg number of them equals the replication factor, and the tasks are canceled reliably if the result is not needed. But it's still statistically possible that some nodes have more parallel checks on them, and I believe on those nodes the waiting time would be longer too.

**Comment by tbg** [comment]
> but intuitively it kinda makes sense that the wait is long

this is a CPU profile, so the stacks are only captured when the goroutine is runnable (or running), so if it's just waiting on the rate limiter for a long time that wouldn't show up as prominently.

**Comment by erikgrinaker** [comment]
Yeah, it's the actual checking for quota that burns CPU here. We should batch it so that we don't check the quota for every single key, but instead every 1000 keys or some such.

**Comment by pavelkalinnikov** [comment]
Ah, indeed, the fix makes sense then.
