### ISSUE TITLE
schema: DROP INDEX fails if there exists a different offline table in the database

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#89708]
**Describe the problem**

DROP INDEX, without the explicit table@ incantation, fails if there exists a _different_ offline table in the database. 

**To Reproduce**

Consider the following schema:
```
CREATE DATABASE d;
USE d;
CREATE TABLE foo (i INT PRIMARY KEY, s STRING);
CREATE INDEX foo_idx ON foo (s);
CREATE TABLE baz (i INT PRIMARY KEY, s STRING);
```

Begin and pause an import onto baz, e.g.:
```
SET CLUSTER SETTING jobs.debug.pausepoints = 'import.after_ingest';
IMPORT INTO baz (i,s) CSV DATA ('nodelocal://0/....')
```

Attempt to drop foo's index, while baz is offline:
```
DROP INDEX foo_dx;
```
- This fails with a surprising error message: `pq: relation "baz" is offline: importing`. I would expect this to work

If I explicitly pass the table, the index drops just fine:
```
DROP INDEX foo@foo_dx;
```

**Environment:**
 - CockroachDB version release-22.2, on my mac

Jira issue: CRDB-20383

**Comment by ajwerner** [comment]
@chengxiong-ruan this should be an easy fix. Please take a look when you find some time.
