### ISSUE TITLE
lint-issue-epic-refs: change logic for what commits need epic refs when multiple epics are referenced in the PR body

### ISSUE THREAD

**Issue by jlinder** [cockroachdb/cockroach#89704]
**Problem**

In the case when a PR body contains multiple epic references, two checks are made:

1. That all commits contain an epic ref to distinguish which epic they are part of
2. That all epic refs in the PR body are included in at least one commit message

Check 1 is too broad. It only needs to do this check for commits with release notes that aren't `bug fix` (though if a `bug fix` and another release note is included in the same commit message, that message should be checked).

The error message as written for check 2 is something some developers never want to see. 

**Suggested solution**

For check 1: update the logic to only check the commits with non-`bug fix` release notes in them.

For check 2: possible solutions include:

- Keep it so the linter tells the user when one of multiple epics is not listed in any of the commit messages while making the error clearer by stating that it's one of multiple epic refs in the PR body and to present common resolution strategies.
- Switch the assumption to be that, if multiple epics are referenced in the PR body, one/some of them is not directly mentioned in any commit and there is at least one commit that doesn't list epics in its commit message, then all the epics apply to that(those) commit(s). This change would need documentation added to the reference wiki page about how it works because it would be silent to the user.

Epic DEVINF-261

Jira issue: CRDB-20381

**Comment by nickvigilante** [comment]
We should only ignore bug fix release notes or "Release note: None" if the PR body contains more than one **epic** reference

**Comment by nickvigilante** [comment]
1. Finding a way to collect the data and analyzing it to see how many "Epic: none" instances we have and what kind of data we're getting (write a tool to mirror down the data, one JSON file per PR, figure out which commit SHAs are part of that PR, then that's all the information you need)
2. Come up with strategies to mitigate bad data
3. Then work on this ticket
