### ISSUE TITLE
sql: table stats job does not indicate progress

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#89766]
I was recently setting up a tpc-e 500k data set which includes manually collecting optimizer stats before before moving on to create indexes. This step took a bit over an hour, most of which had only the `trade` table job running, but I had little visibility into how far it was, how much longer it would be, etc as the progress sits at 0% until it finishes i.e. it does not update its progress with spans completed / total spans estimate or anything similar.

Jira issue: CRDB-20426

**Comment by yuzefovich** [comment]
Closing as a dup of #55758
