### ISSUE TITLE
kvserver,admission: metric to capture max instantaneous disk bandwidth use

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#89786]
**Is your feature request related to a problem? Please describe.**

During experimentation around #89324 we observed short bursts in write bandwidth (driven through compactions) that were not visible in our usual disk write bandwidth graphs. These bursts were noticeable when polling the OS at 1s granularities, but got averaged away over the 10s scrape window we have for metrics. This averaging might be masking bursts of bandwidth use where we're near saturation/elevating log commit latencies though still appear to be far from provisioned limits.

**Describe the solution you'd like**

Maybe something with CRDB that measures bandwidth a finer granularity (1s, or controllable through a cluster setting) over a rolling window, and emitting as a metric the maximum seen over that rolling window.

+cc @andrewbaptist, @sumeerbhola.

Jira issue: CRDB-20433

Epic CRDB-34249

**Comment by sumeerbhola** [comment]
We should try with the `flushPacer` which was disabled in https://github.com/cockroachdb/pebble/pull/431 and removed from the codebase in https://github.com/cockroachdb/pebble/pull/1812.

**Comment by aadityasondhi** [comment]
Some initial thoughts on how to approach this:

To calculate disk bandwidth, we make use of `sys.host.disk.read.bytes` and `sys.host.disk.write.bytes`, and take the rate over the metric window in the UI through "advanced debug" or the rate functionality on grafana. These metrics are captured in `RuntimeStatSampler.SampleEnvironment` at the sampling rate of 10s which is our default metrics sample rate set in `DefaultMetricsSampleInterval`.

The ask here would be to create new metrics to track read and write bandwidth by doing something similar to `SampleEnvironment` but at a configurable granularity through cluster settings. We would capture this at the configured granularity but export the max over the sampling period (i.e) 10s to the actual `metric.Metric`.

cc @CheranMahalingam

**Comment by jbowens** [comment]
This issue might be referring to this separate driver of disk stats collection, driven by admission control through GetPebbleMetrics:

https://github.com/cockroachdb/cockroach/blob/38a0a6fc7831234effb9febf35d1e43b62aa40e6/pkg/server/node.go#L1113-L1137

Unifying the two is one of the related objectives of #112898.

**Comment by jbowens** [comment]
Oh, huh I see—If this is about the timeseries metrics exported, I think it's entirely duplicative/a subset of #112898?

**Comment by sumeerbhola** [comment]
> It is already measured at a high granularity, 250ms or 1ms, based on if the system is loaded or not:

btw, AC only measures every 15s, since that is the interval at which it recomputes token allocations. The durations mentioned are the interval at which these computed tokens are handed out to the token bucket.

I agree this issue is about metrics.
