### ISSUE TITLE
Cryptic error message when upgrading to 22.1.8 from 21.2.16

### ISSUE THREAD

**Issue by lfmunoz** [cockroachdb/cockroach#89795]
**Describe the problem**

I have an application that runs on `cockroachdb/cockroach:v21.2.16` when trying to upgrade to `cockroachdb/cockroach:v22.1.8`  liquibase fails to run. This is on a complete new install. 

Confirmed `22.1.0` is where the break happened  i.e., works on any versions prior to 22.1.0,

Error messge:

```
Caused by: org.postgresql.util.PSQLException: ERROR: table "new_history" is being added
```

Attached debug.zip after running
[debug.zip](https://github.com/cockroachdb/cockroach/files/9760463/debug.zip)

**Expected behavior**
Application should work

**Environment:**
 - Server OS: Ubuntu Linux 
 - docker  image cockroachdb/cockroach:v22.1.8

**Impact:**
 Can't migrate to  `cockroachdb/cockroach:v22.1.8`

Jira issue: CRDB-20435

**Comment by lfmunoz** [comment]
First load the following schema: 
[schema.txt](https://github.com/cockroachdb/cockroach/files/9760584/schema.txt)


Next run the following in a single transaction:


```



CREATE TABLE IF NOT EXISTS new_history (
    agent_endpoint_id      VARCHAR(255) NOT NULL,
    created                TIMESTAMP    NOT NULL,
    workflow_definition_id INT          NOT NULL,
    started                TIMESTAMP,
    finished               TIMESTAMP,
    status                 VARCHAR(32),
    reason                 TEXT,
    manual                 BOOL         NOT NULL DEFAULT FALSE,
    PRIMARY KEY (agent_endpoint_id, created, workflow_definition_id),
    CONSTRAINT fk_agent FOREIGN KEY (agent_endpoint_id) REFERENCES new_agent,
    CONSTRAINT fk_workflow FOREIGN KEY (workflow_definition_id) REFERENCES workflow_definition (id),
    INDEX                  IDX_USP_WORKFLOW_HISTORY_AGENT(agent_endpoint_id),
    INDEX                  IDX_USP_WORKFLOW_HISTORY_CREATED(created),
    INDEX                  IDX_USP_WORKFLOW_HISTORY_STARTED(started),
    INDEX                  IDX_USP_WORKFLOW_HISTORY_FINISHED(finished),
    INDEX                  IDX_USP_WORKFLOW_HISTORY_WORKFLOW_DEFINITION(workflow_definition_id)
);

INSERT INTO new_history (agent_endpoint_id, created, workflow_definition_id, started, finished, status, reason, manual)
    SELECT
        a.endpoint_id,
        wf.created,
        wf.workflow_definition_id,
        wf.started,
        wf.finished,
        wf.status,
        wf.reason,
        wf.manual
    FROM old_agent a
        INNER JOIN workflow_history wf ON a.id = wf.agent_id;

ALTER TABLE workflow_history
    RENAME TO old_history;


``

**Comment by ajwerner** [comment]
I don't think this is new behavior. When creating a table in a transaction which references another table, that table is not usable in that transaction. This behavior goes back as long as I know of. So, what this means is that the schema change prior to 22.1 was not happening in the same transaction as the insert and in 22.1, it is in the same transaction. 

@rafiss do you have any idea what might have changed with regards to transaction management and how it interacts with liquibase in 22.1? I thought maybe it'd be `enable_implicit_transaction_for_batch_statements` but that thing is false until 22.2.

**Comment by rafiss** [comment]
No I can't think of anything else that changed in that regard. But based on https://github.com/cockroachdb/cockroach/issues/89795#issuecomment-1275449302 it sounds like the repro is using BEGIN to make an explicit transaction.

**Comment by ajwerner** [comment]
Right, but as Shaun pointed out, if you do this in an explicit transaction, you'll get that error and you'll get that same error going back as far as I can remember. This is the expected behavior.

**Comment by ajwerner** [comment]
So, the user is indicating that something changed in the liquibase behavior between these versions, and I don't know what that might be.

**Comment by rafiss** [comment]
I missed that - @smcvey can you share the instructions for how you observed that Liquibase works when using 21.2.16? I can try it and do some additional debug logging, etc.

**Comment by smcvey** [comment]
@rafiss I never actually used Liquibase.  I tried the raw SQL commands as provided by user lfmunoz on both versions of Cockroach.  In both cases, they both failed.  This suggests to me that Liquibase isn't exactly sending the same commands (or in the same order) as is in the raw SQL provided by the user.  Whatever Liquibase is sending somehow works on 21.2.16 but not 22.1.8.

**Comment by lfmunoz** [comment]
> When creating a table in a transaction which references another table, that table is not usable in that transaction. 

@ajwerner  I guess my liquibase base script is wrong because I have been doing this since cockroachdb 19 and it has been working fine until 22.1.8.

**Comment by ajwerner** [comment]
> Edit: Actually it is sllightly different, I removed INTERLEAVE IN PARENT new_agent (agent_endpoint_id); from the new_history create table statement and expected it to work as normal.

The interleaving functionality was removed in 21.2. I'm going to close this issue.
