### ISSUE TITLE
sql-exp: TestSQLAlchemy/client-cert flaked on master

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#89816]
See failure https://teamcity.cockroachdb.com/viewLog.html?buildId=6895613&buildTypeId=Cockroach_BazelEssentialCi

Jira issue: CRDB-20454

**Comment by rafiss** [comment]
I think https://github.com/cockroachdb/cockroach/issues/89935 might have been the underlying issue

**Comment by andreimatei** [comment]
It timed out for me on a recent master:
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/7551484?showRootCauses=false&expandBuildChangesSection=true&expandBuildDeploymentsSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

**Comment by rafiss** [comment]
Has not flaked in a few months.
