### ISSUE TITLE
TestLogGrowthWhenRefreshingPendingCommands is flaky

### ISSUE THREAD

**Issue by fantapop** [cockroachdb/cockroach#89862]
This test failed 11 out of the last 1000 builds 

<img width="867" alt="Screen Shot 2022-10-12 at 11 21 10 AM" src="https://user-images.githubusercontent.com/6658984/195447390-8f442aca-75fb-41a0-a689-a23acedd4a19.png">

------- Stdout: -------
=== RUN   TestLogGrowthWhenRefreshingPendingCommands
    test_log_scope.go:161: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestLogGrowthWhenRefreshingPendingCommands607815779
    test_log_scope.go:79: use -show-logs to present logs inline
=== CONT  TestLogGrowthWhenRefreshingPendingCommands
    client_raft_test.go:1692: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestLogGrowthWhenRefreshingPendingCommands607815779
--- FAIL: TestLogGrowthWhenRefreshingPendingCommands (13.89s)

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/6911410?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

Jira issue: CRDB-20470

**Comment by pavelkalinnikov** [comment]
Couldn't catch it so far with `dev test pkg/kv/kvserver -f TestLogGrowthWhenRefreshingPendingCommands --stress`, also with `--race`.

**Comment by pavelkalinnikov** [comment]
All failures are for the `proposeOnFollower=true` subtest, which verifies the following:

```golang
The follower proposes a command and forwards it to the leader, who cannot
establish a quorum. The follower continually re-proposes and forwards the
command to the leader.
```

**Comment by pavelkalinnikov** [comment]
Fails with the following error:
https://github.com/cockroachdb/cockroach/blob/89058d53769dad1d7f01c63afbc8e4722b2c3a35/pkg/kv/kvserver/replica_application_state_machine.go#L317-L325

**Comment by pavelkalinnikov** [comment]
Each of the 2 sub-tests manually transfers the lease:
https://github.com/cockroachdb/cockroach/blob/2675c7c0481bb33eb9f43f1c2b52c152fca3ae2d/pkg/kv/kvserver/client_raft_test.go#L1615-L1617

Correspondingly, the first test (`proposeOnFollower=false`) sees the lease with `seq=1`, and the second test (`proposeOnFollower=true`) sees `seq=2`. Those rare flaky failures also observe `seq=3` during the second sub-test, i.e. the lease gets transferred without a request.

**Comment by pavelkalinnikov** [comment]
Here is the leases progression:
```
# first test starts
repl=(n1,s1):1 seq=1 start=0,0 epo=1 pro=1665682661.387221000,0
# second test starts, gets a lease for 30000 seconds
repl=(n2,s2):2 seq=2 start=1665682668.500530000,0 exp=1665712668.500304000,0 pro=1665682668.500304000,0
# unexpected lease happening in the flaky runs
repl=(n2,s2):2 seq=3 start=1665682668.500530000,0 epo=1 pro=1665682668.528933000,0
```

**Comment by pavelkalinnikov** [comment]
@irfansharif Could this be related to the recent work in 991b134f and #85629?

**Comment by pavelkalinnikov** [comment]
Found a fix.

**Comment by erikgrinaker** [comment]
Very nice, thanks @pavelkalinnikov!
