### ISSUE TITLE
rangefeed: frequent stuck rangefeed restarts

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#89860]
In https://github.com/cockroachlabs/support/issues/1841 I happened to notice lots of log messages of this kind:

```
kv/kvclient/kvcoord/dist_sender_rangefeed.go:434 ⋮ [n19,job=803505237872738308,f‹b27f89db›] 6943759 restarting stuck rangefeed: waiting for r212915 (n19,s19):6 [threshold 1m0s]: rangefeed restarting due to inactivity
```

We appear to be restarting a large portion of the rangefeeds every minute. I'm also seeing closed timestamps lagging:

```
RangeFeed closed timestamp 1665517145.400389712,0 is behind by 4m48.194600404s
```

`kv.closed_timestamp.target_duration` is set to `30s`.

This was added in #86820. The default setting here may be too aggressive.

CC @miretskiy.

Jira issue: CRDB-20468

**Comment by erikgrinaker** [comment]
This is also emitting a ton of messages in this cluster, something like 70% of the total log volume, because many of the ranges (~100k total) are being restarted every minute. We should consider limiting these log messages.

**Comment by miretskiy** [comment]
Might be worth a GA blocker to backport?

**Comment by erikgrinaker** [comment]
The cluster in question had `kv.closed_timestamp.side_transport_interval = '5m'` (default is 200ms), so it's expected that these would get "stuck" for ranges with no write activity.

We may need to do something smarter here to avoid breaking any existing clusters running with higher closed timestamp intervals. The relevant settings are (at least):

* `kv.rangefeed.range_stuck_threshold`
* `kv.closed_timestamp.side_transport_interval`
* `kv.closed_timestamp.target_duration`

We could automatically pick the largest value here and add on a bit of buffer, but that may be non-obvious. We could also drop the setting and try to automatically pick a suitable value, but it's useful to have a knob if we get it wrong. Or we could just leave it like it is, and make it clear in the release notes that operators have to tune this appropriately.

Thoughts?
