### ISSUE TITLE
allocator: reduce frequent allocator score logging

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#89898]
22.2 emits lots of messages like these:

```
kv/kvserver/allocator/allocatorimpl/allocator.go:2209 ⋮ [n1,replicate,s1,r183996/3:‹/Table/100/2/"\x16\x1d̑\xb2\…›] 5779443 node: 9, sourceWeight: 0.00, remoteWeight: 0.00, remoteLatency: 695.638µs, rebalanceThreshold: 0.10, meanLeases: 4266.50, sourceLeaseCount: 4333, overfullThreshold: 4694, remoteLeaseCount: 4282, underfullThreshold: 3839, totalScore: -804
```

In a spot check, these made up 87% of emitted log messages. Log rotation is often based on volume, so this can cause logs to be rotated out within a day, hampering our ability to debug problems via debug.zips.

We should either avoid logging these messages by default, or rate limit them.

Jira issue: CRDB-20490

**Comment by erikgrinaker** [comment]
Marking this as a GA blocker, since it will severely hamper our ability to debug escalations with 22.2.0.

**Comment by kvoli** [comment]
cc @lidorcarmel
