### ISSUE TITLE
sql: expose KV range metadata to SQL for "experienced" admins

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#8990]
This is a follow-up to #8938, a proposal to implement two new functions:
- `crdb_encode_pkey(table_or_index_name, expr...)`, returning `bytea`, with `table_or_index_name` a string or identifier (string would be more easy and would create an opportunity to play with the virtual schema). This would compute and return the KV-level key encoding for the primary key of the specified table/index using the values given in the other arguments.
- `crdb_current_range_bounds(pkey)`, where `pkey` is a `bytea`, returning a tuple of two `bytea`, with the two values are the current known range bounds for the range containing `pkey`. 

The two functions in combinations can then be used to estimate "distance" between two rows in a table, in the sense of whether they belong to the same range or not, and can be used as a follow-up to #8938 to check that a split requested with "ALTER TABLE ... SPLIT" was actually processed.

The function names are just proposals.

cc @mjibson

**Comment by knz** [comment]
Once this is available the SPLIT AT syntax can be simplified to take a simple `bytea` expression that is the result of the `encode_pkey` function.

**Comment by a6802739** [comment]
@knz, please give me some more reference and I have time to fix it now.

**Comment by knz** [comment]
@a6802739  Please review  #8938 and the discussion that accompanied the PR to see if you understand what this feature is about. Then we can discuss if you have questions.

**Comment by a6802739** [comment]
@knz , I start to fix this issue.

about `crdb_encode_pkey(table_or_index_name, expr...)`, do you mean wee add this function to encode primary key value to kv value which is used in kv level. it should be like `/Table/TableID/PrimaryID/Value`, so how can we map the table name or the index name to the specified id?

about `crdb_current_range_bounds(pkey)`, do you mean to find the correct range contains the key?it seems in `testutils/serverutils/test_server_shim.go` , it already has function `LookupRange`.

**Comment by knz** [comment]
For the first point you need to investigate the table/index descriptors.

For the second point yes the solution will need LookupRange.

**Comment by petermattis** [comment]
@knz Now that we have `SHOW TESTING_RANGES`, is there anything left to do here?

**Comment by knz** [comment]
No indeed
