### ISSUE TITLE
examples-orms: failure when starting sql server

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#89935]
**Describe the problem**

Some Examples-ORMs tests have been failing with the following message:

```
2022/10/13 18:22:11 process 11483 started: /home/agent/go/src/github.com/cockroachdb/examples-orms/cockroach mt start-sql --certs-dir=/tmp/cockroach-testserver134957765/certs --logtostderr --tenant-id=2 --kv-addrs=localhost:39597 --sql-addr=localhost:39277 --http-addr=:0
2022/10/13 18:22:11 cockroach-go testserver: WaitForInitFinishForNode 0: Trying again after error: dial tcp 127.0.0.1:39277: connect: connection refused
```

Recent occurrences:

* https://teamcity.cockroachdb.com/viewLog.html?buildId=6931815&tab=buildResultsDiv&buildTypeId=Cockroach_Ci_Tests_ExamplesORMs
* https://teamcity.cockroachdb.com/viewLog.html?buildId=6932603&tab=buildResultsDiv&buildTypeId=Cockroach_Ci_Tests_ExamplesORMs

Jira issue: CRDB-20504

**Comment by renatolabs** [comment]
Doesn't seem to have happened recently anymore. I'm going to close it.

**Comment by srosenberg** [comment]
Still happening [1],

```
2023/06/09 19:17:42 cockroach-go testserver: WaitForInitFinishForNode 0: Trying again after error: pq: codeParamsRoutingFailed: missing cluster identifier
2023/06/09 19:17:42 init did not finish for node 0
```

[1] https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_Tests_ExamplesORMs/10474323?buildTab=log&focusLine=3710&linesState=515.3531.3695
