### ISSUE TITLE
stability: slow startup times because of eager replica GC

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#8993]
Forked from #8694, where this was initially discovered and discussed as it exposed GRPC problems which lead to persistent RPC connection failures.

![screen shot 2016-08-31 at 2 52 42 pm](https://cloud.githubusercontent.com/assets/5076964/18142251/af673c2a-6f8a-11e6-9d7d-d634a029bccc.png)

I believe that the large number of replicas here suggests that the gc queue isn't properly doing its job, though that is only a theory. If substantiated, we should be spending less time here in regular cases.

One way to make this iteration faster is parallelism (i.e. destroy multiple replicas in parallel, to keep RocksDB busy). We must, however, finish it before continuing with the startup process (to avoid racing with the Store, which might access overlapping keyspace).

**Comment by petermattis** [comment]
If replica GC on startup is the issue, that would explain why this is a heisenbug. We definitely need to figure out why the replica GC queue wasn't deleting these replicas. Do the logs on that node indicate anything? I would expect we would see `[replicaGC]` errors coming out of `storage/queue.go`.

**Comment by petermattis** [comment]
Regardless of whether the replica GC queue is working properly now, it seems good to not delay startup by requiring the cleanup of zombie replicas.

**Comment by tschottdorf** [comment]
The remaining part here is keeping an eye out for the GC queue getting stuck (or whatever other reason there is for having that many replicas gc'able at boot time).
