### ISSUE TITLE
Enable region filter on SQL Activity for Serverless

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#89949]
Currently, the filter for regions on the SQL Activity is disabled. Once Multi-Region is enable on Serverless, this filter should be enable. 
The column showing this info should also be enabled.

Jira issue: CRDB-20510

Epic CRDB-20437

**Comment by maryliag** [comment]
@andy-kimball on dedicated we should both region and nodes on the same column, can you confirm that for Serverless should be just the region, and we should continue to hide the node info. Or do you also want to see the node info (filter and column)?

**Comment by andy-kimball** [comment]
Correct, we only want to select the region, not the node.
