### ISSUE TITLE
kv,spanconfig: multi-tenant replication reports

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#89987]
**Is your feature request related to a problem? Please describe.**

Replication reports don't work for secondary tenant keyspans and would not be accessible to secondary tenants even if they did. This is a tracking issue for work to replace today's single-tenant replication reports (https://www.cockroachlabs.com/docs/stable/query-replication-reports.html) with something that works in the multi-tenant context. Rough notes/structure (cribbed from this [internal document](https://docs.google.com/document/d/1xKd8zCx05E7ymTmPXG6nHTH2q77tkE4QwtH2OAr2ctM/edit#)):
- KV generates reports off of `system.span_configurations` state. Scans `meta2` in txn-al batches, joins against the `span_configurations` table (using perhaps the local in-memory copy maintained in `spanconfig.KVSubscriber`); gets locality information by looking at what the in-memory store pool and in-memory node liveness have to say.
- Think of this as allocator observability, needs to be efficient enough to be used by the allocator even if it isn't right away. Only RPC used is that to scan `meta2` – could also use a cached version of range descriptors in the future. 
  - Don’t pre-generate reports — do it on the fly but do it fast. Benchmark against 1M ranges, omit uninteresting data if need be.
  - [x] Sanity check what the current allocator uses for its view of the world
  - [ ] Could it be used to do pre-flight checks for decommissioning ([#70486](https://github.com/cockroachdb/cockroach/issues/70486))
- KV-level API generates a protobuf that’s wholly populated. Whether it’s later persisted in some table or not, or exposed through JSON, is irrelevant at this level/pass.
- Should be able get reports for a list of keyspans. Can be used to power reporting for specific tables, indexes, databases and allow for pagination. Results can be chunked back to the client with resumption keys if needed.
- Don’t report on lease preferences in the first pass (we don't today though it was described in the [original RFC](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20190619_constraint_conformance_report.md)), don’t report on non-voter conformance (do we do this today? [#75821](#75821)?), don’t make it accessible through SQL in the first pass (some lengthy UX questions to be had, for ex. [#84090](#84090)). Don’t try to improve reporting coverage in the face of splits/merges – this is the status quo (best effort reporting).
  - Paper over inconsistency if using multiple txns to sift through meta2.
  - [ ] Look at what [this comment](https://reviewable.io/reviews/cockroachdb/cockroach/84727#-N9glmWn0dEL5xL3N__u) talks about.
 
End state: tenants are able to view replication status for their own keyspaces. This is the portion that’s stitched together with their own SQL state. But similar to how only the system tenant (or rather a tenant with system privileges: [#85954](#85954)) is able to configure reserved keyspans or set protected timestamps affecting other tenants, they’ll be able to view status for tenants they’re hosting. All access will be through the Connector interface.

Later on if we want to integrate this more closely with SQL state, above KV we'd have to:
- Validate that `span_configurations` is at least as up to date as some recent SQL state. Or wait until it is. We could observe a `spanconfig.Reconciler` job checkpoint to make sure. Or observe the timestamp in the `spanconfig.KVSubscriber` too, or pass it down.
- Span orientation should be such that it’s consumable in SQL to surface data relevant to specific indexes/tables/etc.

Jira issue: [CRDB-20534](https://cockroachlabs.atlassian.net/browse/CRDB-20534)

Epic CRDB-10630

**Comment by irfansharif** [comment]
#90016 merged and completes the KV-side API for multi-tenant replication reports. The next step is to work on some “front-end” for this API, either just a vanilla HTTP end point, or some dedicated SQL syntax to present the results of this API in a more readable way (`SHOW REPLICATION STATUS FOR [EVERYTHING | DB <db name> | TABLE <tbl name> | INDEX <idx name>]` for example). Unassigning myself.

**Comment by irfansharif** [comment]
> The next step is to work on some “front-end” for this API, either just a vanilla HTTP end point, or some dedicated SQL syntax to present the results of this API in a more readable way (SHOW REPLICATION STATUS FOR [EVERYTHING | DB <db name> | TABLE <tbl name> | INDEX <idx name>] for example).

Going to leave this, and building parity for critical localities, as things left to do under https://cockroachlabs.atlassian.net/browse/CRDB-10630. I'll close this issue specifically.

**Comment by knz** [comment]
Moving the convo over to here: #100004
