### ISSUE TITLE
sql: allow `*` expressions in user-defined function (UDF) bodies

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#90080]
In v22.2 we disallow `*` expressions in UDF bodies, see #86070. We should allow these expressions. We'll need to figure out how to handle cases where a table's schema changes after a function has been created.

Jira issue: CRDB-20579

Epic CRDB-19496

**Comment by mgartner** [comment]
In a previous issue https://github.com/cockroachdb/cockroach/issues/86070#issuecomment-1276329324, @ajwerner said:

> I think we can disable support for the * for this release and it would be okay. Postgres in views and in the eagerly resolved form of UDFs turns the * into column names at creation time. I think we should do that.

Here's an example of this behavior in Postgres:

```
marcus=# CREATE TABLE t (a INT);
CREATE TABLE

marcus=# CREATE FUNCTION f() RETURNS INT LANGUAGE SQL BEGIN ATOMIC SELECT * FROM t; END;
CREATE FUNCTION

marcus=# INSERT INTO t VALUES (1);
INSERT 0 1

-- f() Returns the value of column a.
marcus=# SELECT f();
 f
---
 1
(1 row)

marcus=# ALTER TABLE t ADD COLUMN b INT DEFAULT 2;
ALTER TABLE

-- f() Still returns the value of column a.
marcus=# SELECT f();
 f
---
 1
(1 row)

marcus=# ALTER TABLE t RENAME COLUMN a TO c;
ALTER TABLE


-- f() Still returns the value of column c, which was
-- renamed from a.
marcus=# SELECT f();
 f
---
 1
(1 row)

marcus=# ALTER TABLE t RENAME COLUMN b TO a;
ALTER TABLE

-- f() Still returns the value of column c, even though
-- there is another column b.
marcus=# SELECT f();
 f
---
 1
(1 row)
```

**Comment by rharding6373** [comment]
At this point we've added support for basic `*` expansion, but do not have support for the schema change edge cases (e.g., column and table renaming) mentioned in https://github.com/cockroachdb/cockroach/issues/90080#issuecomment-1377522838. That should be supported when https://github.com/cockroachdb/cockroach/issues/83233 is resolved.
