### ISSUE TITLE
ui: clean up raft display code

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#9009]
Clean up various fugliness that originated in #6973 and caused a lot of trouble in https://github.com/cockroachdb/cockroach/pull/9006.

**Comment by mrtracy** [comment]
I think this is likely not going to get done.  The actual page itself might get a slightly facelift, but I think ugly code is likely okay; this particular debug page might soon outlive its usefulness as the size of clusters under test continues to increase.
