### ISSUE TITLE
Suspicious Estimated Rows by `OR` 

### ISSUE THREAD

**Issue by bajinsheng** [cockroachdb/cockroach#90112]
**Describe the problem**

The estimated rows of the `SELECT` statement with `OR` is smaller than the same `SELECT` statement without `OR`. 

**To Reproduce**

```sql
CREATE TABLE t1 (c0 INT);
INSERT INTO t1 VALUES(1),(2),(3),(4),(5),(6),(7),(8),(9),(10);
ANALYZE t1;

EXPLAIN SELECT * FROM t1 WHERE t1.c0 IS NOT NULL; --10 rows
EXPLAIN SELECT * FROM t1 WHERE (t1.c0 IS NOT NULL)OR(CASE WHEN t1.c0<t1.c0 THEN false ELSE TRUE END); --3 rows
```

**Expected behavior**
The number of estimated rows of the second `SELECT` should be no less than that of the first `SELECT`.

**Additional data / screenshots**

**Environment:**
 - CockroachDB version [fbfb71b96ff0b801acece007664a5861c4214aa1]
 - Server OS: [Linux/Ubuntu 20.04]
 - Client app [`cockroach sql`]

Jira issue: CRDB-20589

**Comment by DrewKimball** [comment]
Hi @bajinsheng, this does appear to be a real issue - in fact, we've already got one open [here](https://github.com/cockroachdb/cockroach/issues/75090) for it. I'm going to close this as a duplicate, but feel free to ask any questions you may have.
