### ISSUE TITLE
roachtest: add `OwnerKVReplication` for some tests

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#90125]
We should assign some roachtests to the KV replication team, e.g. `inconsistency`. However, this requires wiring up KV replication as a proper team in `teams.yaml` and elsewhere.

Jira issue: CRDB-20601

**Comment by tbg** [comment]
I'm also not sure the issue posting stuff works together with our T- label yet. IIRC it uses github project columns to assign to a team, but we're not using github projects.

**Comment by erikgrinaker** [comment]
>I'm also not sure the issue posting stuff works together with our T- label yet. IIRC it uses github project columns to assign to a team, but we're not using github projects.

Ok, I'll see about adding team labels to the issue poster.
