### ISSUE TITLE
changefeedccl: initial_scan_only does not emit all messages before completing

### ISSUE THREAD

**Issue by samiskin** [cockroachdb/cockroach#90146]
**Describe the problem**

`initial_scan_only` appears to exit the changefeed with a success prior to all messages being received by the external sink.

This is likely due to the `errChangefeedCompleted` exiting after observing a resolved event at the kvfeed level when the messages are being emitted and buffered at the sink level later on in the pipeline.

**To Reproduce**
Verified on 22.1.9

1. Start a local kafka server and a single node CRDB server
2. Load a small `tpcc` fixture (`./bin/workload fixtures import tpcc --warehouses=3 --checks=false`)
3. Start consuming from a topic `confluent local services kafka consume testTopic`
4. Create a changefeed on a table with a decent amount of rows like `tpcc.item` (100000 rows), a large batch configuration makes the effect more pronounced: 
```create changefeed for tpcc.item into 'kafka://localhost:9092?topic_name=testTopic' with initial_scan='only', kafka_sink_config='{"Flush": {"Messages": 5000, "MaxMessages": 10000, "Frequency": "2s"}}';```
5. Once the changefeed succeeds (should be quick, can verify in `show changefeed jobs`), go to the terminal that has the `kafka consume testTopic` running and `ctrl-c` out of it.  It'll print out the number of rows it observed. In my case this was "Processed a total of 1152 messages"

Doing the same without `initial_scan_only` and then closing after no more changes show up results in the correct `100000` messages.

**Expected behavior**
`initial_scan_only` should complete only after all rows in the table have been emitted to the sink

Jira issue: CRDB-20614

**Comment by amruss** [comment]
@shermanCRL is going to take the lead on a TA for this issue
