### ISSUE TITLE
cli: `cockroach mt start-sql` does not support the `--locality-advertise-addr` argument

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#90172]
**Describe the problem**

For KV node-node connections, we support a `--locality-advertise-addr` that tells nodes to use different hostnames to connect to other nodes depending on their locality. This enables customizing which addresses are exposed in k8s in each region.

For multi-region serverless support, we'll need a similar mechanism for communication between SQL-only servers.

However, currently the `--locality-advertise-addr` flag is not supported by SQL-only servers. It probably should.

Might relate to #52266
Might relate to #42741

Jira issue: CRDB-20621

**Comment by knz** [comment]
cc @JeffSwenson for consideration

**Comment by JeffSwenson** [comment]
The --locality-advertise-addr is not needed by Multi Region Serverless. We set up the VPC so that each region has a unique ip range and regions are able to route to each other via the internal ip address.
