### ISSUE TITLE
admission: Further improvements in catchup scans AC

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#90194]
Recent changes (https://github.com/cockroachdb/cockroach/pull/89656) added
elastic CPU admission control for catchup scans.

This should provide significant improvements; It may not be enough.
We should leverage AC in order to provide better .. well, admission, as well
as isolations for multiple changefeeds/rangefeed running in the cluster.

The two settings are problematic:
* `kv.rangefeed.catchup_scan_concurrency` -- a client side limit to control the number
   of catchup scans started by a single rangefeed client (i.e chagnefeed), which was added so that
   a single changefeed does not consume  entire budget on a server.
 * Server side  `kv.rangefeed.concurrent_catchup_iterators` which sets per store limit on the number
   of catchup iterators.

None of the above settings are ideal, but the server side is particularly problematic.
Consider the case when the customer is running multiple changefeeds (say 10) across significantly
sized workload -- say 150k ranges.
One of the tables (~15k ranges) undergoes a schema change, necessitating the restart of rangefeed.
We now need to catchup on 15k ranges. 

Also note, that due to unpredictable cost of running catchup scan, the limits are set fairly low.
Perhaps something like 4 iterators per store (with each node having 4 stores) -- so, 16 iterators per node.

Part of the problem is that this single changefeed will now take a while to catchup (sort of depends, really
on many factors); 
A much worse problem is that while this is happening, other changefeeds are also impacted.
Range split/merge/moves are normal part of operation (and you should be expecting quite a few of those
if schema change was performed, for example) -- but now, none of those normal events can be
processed because to do so requires catchup scans -- which are completely exhausted by that single
changefeed.  Now, all of the changefeeds are impacted.

Can AC do something so that we can remove arbitrary semaphore based limits? Can we perhaps use
AC to try to account for IO cost and admit based on that? Perhaps heuristic can be made to compute
the cost based on how far in the past you're trying to scan?

Jira issue: CRDB-20626

**Comment by sumeerbhola** [comment]
@miretskiy can you provide steps to reproduce a problem (post elastic COU admission).

**Comment by nicktrav** [comment]
This should come for free once we have disk b/w integrated into AC. Closing.
