### ISSUE TITLE
sql: databases page and databases details pages are expensive and inefficient with many tables

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#90196]
**Describe the problem**

There are two related, fundamental problems captured by this ticket. 
1) The request to fetch disk usage stats for a table span is expensive, particularly when called concurrently
  * When we have very high concurrency, we spend all of our time getting some random numbers to shuffle replicas we don't even really need to shuffle. There are a lot of fixes here, an easy one might be too sync.Pool a math.Rand so we do no allocations and no locking. 
 https://github.com/cockroachdb/cockroach/blob/55aca6559003f414d75c683a6c16cad12186ef09/pkg/kv/kvserver/store.go#L405

 * We don't need to do that shuffle.
 * We don't need to build this slice. 

2) The request to fetch stats for all databases or all tables for a database has unbounded parallelism.
 * Nothing should have unbounded parallelism, period. Here we have 60k tables. That's not okay.
 * We should use a semaphore to limit the tasks at some finite concurrency -- something like 16 or so will be a reasonable start.
 * This will make this page slower, but oh well. The right answer is probably to build a more sophisticated batching mechanism so that we can retrieved the desired information with one request sent to each store. 
 * Note that the parallelism is somewhat triply unbounded. 
    * The UI is going to issue requests for each database in parallel
       * At least here the browser will bound the concurrency to something, maybe 8 or 16, hopefully. Though who knows if we were to be using h2
     * The endpoint is then going to go fully parallel for every table in the database
       * https://github.com/cockroachdb/cockroach/blob/669e9a51a4bda919439da48b660430561016bbe5/pkg/server/admin.go#L579
     * For each table span, we'll send a request to every node in the cluster
       *  https://github.com/cockroachdb/cockroach/blob/669e9a51a4bda919439da48b660430561016bbe5/pkg/server/admin.go#L1265

**To Reproduce**

Create a large number of databases with a large number of tables each. 

**Expected behavior**

This doesn't completely trash the cluster with CPU utilization.

**Additional data / screenshots**
<img width="1411" alt="Screen Shot 2022-10-18 at 5 19 08 PM" src="https://user-images.githubusercontent.com/1839234/196546924-cf5bf890-8ca6-47e6-bac1-d0798ec5af85.png">

**Additional context**
Relates to https://github.com/cockroachdb/cockroach/issues/84105

Jira issue: CRDB-20627

**Comment by THardy98** [comment]
https://github.com/cockroachdb/cockroach/pull/93937
^ should help with overlying issue, related to the 2nd issue called out in the description
