### ISSUE TITLE
How to do reverse scan?

### ISSUE THREAD

**Issue by ngaut** [cockroachdb/cockroach#902]
Hi, i want to scan key less then some key ? 
It seems i can only scan key larger than some key. Any ideas? Thanks

**Comment by tschottdorf** [comment]
Hey @ngaut, intrinsically we only support ascending scans. If you want the opposite, a) store your data that way or, if you're going to need to scan in both directions, b) maintain an index (or denormalize) which encodes in opposite order and then use that for the lookup you need less often.

**Comment by pesho** [comment]
@tschottdorf is there a fundamental reason for not supporting reverse scans, or is it simply not yet implemented?

**Comment by spencerkimball** [comment]
There's no fundamental reason per se, but we use RocksDB's merge operator which prevents reverse scanning.

**Comment by ngaut** [comment]
Hi, We've build a mysql storage engine for cockroachdb. 
let's see if i want to run sql like "select xx form tableA where colX < something". 
"colX" is index here. So if we can not do reverse scan, i need to store index by encoding it.
That kind of waste for storage.

**Comment by spencerkimball** [comment]
Couldn't you scan forward for all keys in the index from the start of the
index up to "something" just as easily for this particular case? Why do you
need to start at "something" and go backwards?

**Comment by ngaut** [comment]
Thanks, spencer.
Actually, I do not know the exact start key in this case. But i do know the end key. For example, i want to find people that age less then 80 and limit count to 5. I have to scan from the min index key, which would be a bad idea.

**Comment by spencerkimball** [comment]
Well that would just be the start of your age index, so you'd start with
people aged 0 seconds and take the five youngest. Is there some reason you
wouldn't be able to compute the start key for the age index? I suppose if
you wanted to limit 5 and sort decreasing then you'd end up having to scan
your entire index. But at this point if you're using MySQL on top of
cockroach, performance is going to be incredibly problematic for a host of
other reasons, so I don't think this will be your biggest problem..

**Comment by Downchuck** [comment]
@spencerkimball Just coming across this issue -- does this mean that getting a count for a scan start/end range is not feasible -- as well as getting the max for that range?

**Comment by tschottdorf** [comment]
@Downchuck the limitation to be able to scan only in ascending order has since gone away (on the RocksDB side, we haven't done anything with it). Unless I'm misunderstanding where you're coming from, getting the max/count of any key range is possible without reverse scans (after all, just scan the range forward and do your counting/maxing).

**Comment by Downchuck** [comment]
Cool to hear that scanning can be done in reverse -- that'd easily let me
get min / max by doing scan + order + limit 1 on either side.

With "count" -- I'm using a remote connection -- iterating through all
results to get a count would be large traffic overhead for a single integer
result.

**Comment by yananzhi** [comment]
@tschottdorf Reverse scan has been implemented based old version of cockroach to do some test,  I can merge it to the project if you think it is necessary.
@spencerkimball Why do you think there has a poor performance using MySQL on the top of cockroach?

**Comment by spencerkimball** [comment]
@yananzhi because I think it would be wishful thinking to assume otherwise. I don't know in practice though.

**Comment by spencerkimball** [comment]
Typically an implementation of a SQL query engine and optimizer built for local storage isn't going to perform well when simply dropped on top of a system with very different performance characteristics, especially around network latency and bandwidth limitations.
