### ISSUE TITLE
command `show tables` is slow in some cases

### ISSUE THREAD

**Issue by kocoten1992** [cockroachdb/cockroach#90213]
**Describe the problem**
I've notice command `show tables` is sometime unreasonably slow

```
SHOW TABLES 0

Time: 1.496s total (execution 1.495s / network 0.001s)
```

**To Reproduce**
I'm not sure how to reproduce, `1.496s` is on my local machine, on production server it take

```
Time: 120ms total (execution 119ms / network 1ms)
```

Which is also slow - but acceptable, in contrast, `show databases` only took `3ms`.

Note that it does not matter tables database have (database have 0 tables in my example above).

cockroachdb version:
```
CockroachDB CCL v22.1.8 (x86_64-pc-linux-gnu, built 2022/09/29 14:21:51, go1.17.11)
```

Jira issue: CRDB-20629

**Comment by kocoten1992** [comment]
This is faster, but still unreasonably slow:

```
Time: 593ms total (execution 593ms / network 0ms)

root@:26257/website_testing_1> SELECT table_name FROM information_schema.tables WHERE table_schema='public';
```

**Comment by ajwerner** [comment]
https://github.com/cockroachdb/cockroach/pull/91054 will fix show tables when you have a modest number of tables in one database but many databases. It will continue to be painfully slow if you have many (10k+) tables in the current database.

**Comment by ajwerner** [comment]
Duplicates https://github.com/cockroachdb/cockroach/issues/90115.
