### ISSUE TITLE
logictest: `delete` flaked

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#90242]
See CI failure [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=7026535&buildTypeId=Cockroach_BazelEssentialCi)

Jira issue: CRDB-20647

**Comment by knz** [comment]
Another one: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/7026461?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

**Comment by ajwerner** [comment]
https://github.com/cockroachdb/cockroach/pull/88974 this PR introduced that directive. @faizaanmadhani can you deflake this and also add subtest directive for your newly added tests?

**Comment by faizaanmadhani** [comment]
Hey @ajwerner, I opened #90251 earlier today that fixed this flaky test, and it merged a few minutes ago

**Comment by ajwerner** [comment]
@faizaanmadhani cool, I'll close this. Still, can you add a subtest directive in a one-line PR for your new subtest?

**Comment by faizaanmadhani** [comment]
> @faizaanmadhani cool, I'll close this. Still, can you add a subtest directive in a one-line PR for your new subtest?

Yup! I've opened the PR here: #90280
