### ISSUE TITLE
cli: when exiting due to signal, use correct exit code

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#9024]
via @bdarnell:

> It doesn't seem right to exit with status zero after SIGTERM. It seems too easy to accidentally kill the server in a way that it won't restart. We should remember that we're dying due to a signal and return the appropriate error code (128+signal number).

This should be easy to fix in `cli/start.go`.

**Comment by knz** [comment]
Note that I'd recommend only returning the signal code for a hard shutdown. After the first signal, if the soft shutdown succeeds we probably want exit code 0. Correct?

(That's what I implemented in #9051 btw)
