### ISSUE TITLE
storage: More visibility into rebalance decisions

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#9025]
The test clusters are performing rebalance operations almost once a second in the steady state. This seems way too high, but it's difficult to see why the rebalancer is doing what it's doing. There's some V(2) logging, but it's inconvenient to use. There should be a more visible way to see what the rebalancer is doing. An EventLog is the simplest solution, although dedicated support in the UI will probably be a good idea at some point.

**Comment by BramGruneir** [comment]
You can right now look up the range log, and it should at least give you a glimpse into what happening.

But I agree, we need to add in some details in it as to why a particular rebalance was performed.

**Comment by petermattis** [comment]
There was also a thought about providing insight into what the rebalancer would like to do with a particular range on the /debug/range page.

**Comment by a-robinson** [comment]
I never totally understood that thought, since if the rebalancer wanted to do something with a range why wouldn't it have done so already in most cases? Recording the reasons for why rebalances actually did occur  (as @BramGruneir and I have discussed) seems more useful to me.

**Comment by BramGruneir** [comment]
The case in which this would be useful is when there is a heavy rebalancing load in the system already, or there is limited free space or nodes.  But you're right, in most cases, it should be "do nothing".

**Comment by petermattis** [comment]
My thought was that the per-range rebalancer decision could also indicate why the rebalancer thought a rebalance wasn't necessary. Perhaps it is worthwhile to brainstorm better ways to inspect what is going on in the rebalancer/allocator. The event log we previously had was mostly useless as it contained too much information while also losing information too quickly about a particular rebalance you were interested in.

**Comment by a-robinson** [comment]
Of course, explaining why it doesn't think rebalancing is necessary is useful too.

**Comment by BramGruneir** [comment]
@a-robinson Since you're actively moving things around with the allocator, this is probably going to be work that falls out of those changes.
