### ISSUE TITLE
sqlliveness: sql liveness heartbeat loop can exit silently

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#90262]
A bug was introduced in #87533 causing the sql liveness heartbeat loop to exit silently if creating the session record times out. This is the [faulty code path](https://github.com/cockroachdb/cockroach/blob/release-22.2.0/pkg/sql/sqlliveness/slinstance/slinstance.go#L283). The respective return path was originally supposed to only occur on specific bizarre errors, but when a timeout was introduced for that operation, the timeout error inadvertently fell into the same path.

So, when such a timeout happens, heartbeat loop exits and the liveness session stays expired forever. The consequences of this are severe for tenant SQL servers in serverless clusters. This is because tenants [tie](https://github.com/cockroachdb/cockroach/blob/c74da8aa8b1e69562d837c81bb092f8de6f6d8f2/pkg/sql/catalog/descs/leased_descriptors.go#L201-L212) the deadlines of their transactions to the session expiration ([this does not happen](https://github.com/cockroachdb/cockroach/blob/d1962deb662c115ceec158a0c09d3f797eca3e71/pkg/sql/conn_executor.go#L2963-L2975) for mixed sql/kv servers). So, I think that a tenant server with an expired session will fail all its queries.
For tenant servers, the instance ID is also tied to the session, and can be stolen by another server once the session expires. I'm not sure what goes wrong if a server is running with a duplicate instance ID for a prolonged time. One peripheral thing is that the instance ID is used as a log tag, so perhaps logs collection gets confusing.

For mixed sql/kv nodes, the consequences of running with an expired session are less clear to me. I believe such nodes cannot run jobs, as I believe jobs leases are built on the session. As far as I can tell, that's the only thing that depends on the session.

cc @ajwerner 

Jira issue: CRDB-20663

**Comment by rafiss** [comment]
I added the `release-blocker` label, otherwise this wouldn't block v21.2 or v22.1 patch releases. I also added `branch-release-22.1`, since it seems to be affected too.

**Comment by joshimhoff** [comment]
How did we find this bug?

**Comment by andreimatei** [comment]
By reading the code.

**Comment by aadityasondhi** [comment]
Closing this issue since all revert PRs have now been merged.
