### ISSUE TITLE
server: tenant span stats for TableStats, TableDetails & DatabaseDetails endpoints 

### ISSUE THREAD

**Issue by THardy98** [cockroachdb/cockroach#90267]
**Is your feature request related to a problem? Please describe.**
Part of: #89429

Currently, the `TableStats` and `DatabaseDetails` endpoints surface span statistics using `statsForSpan` which makes use of the `kv.DB`, and the `TableDetails` endpoint surfaces range count using `CountRanges` from the `kvcoord.DistSender`.

Use of these KV operations are blockers from making these endpoints tenant-scoped, as tenants will not have access to the KV layer. 

To me, there seem to be a couple options to do this:
- We can build internal tables to hold span/range statistic information that we can query with SQL. The feasibility/cost of this proposal needs to be determined.
- Alternatively, supposedly tenants can interact with the KV layer but would need some special auth logic to do so, which we could implement (I'm not too familiar, @dhartunian would be able to provide better context)

Alternative approaches and discussion welcome.

Jira issue: CRDB-20665
Epic: CRDB-16704

**Comment by THardy98** [comment]
@knz @dhartunian does the issue description make sense, any thoughts on approach?

**Comment by knz** [comment]
it's pretty close, yes. Thanks.

Note that @aayushshah15 is currently researching solutions for an adjacent area and might have additional thoughts to share.

**Comment by THardy98** [comment]
cc @nkodali for visibility/thoughts as well

**Comment by ajwerner** [comment]
cross-ref https://github.com/cockroachdb/cockroach/issues/84105
