### ISSUE TITLE
stability: Make rebalancer less aggressive

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#9031]
Replica counts on gamma are currently [4232, 4232, 4231, 4227, 4234, 4224] - the difference between the highest and lowest is 0.2%. In spite of this, the rebalancing system is constantly making moves, because each node is looking at its local (laggy) data about the cluster and can always find a move that converges two nodes on the mean. 

When all nodes are within say 5% of each other, the rebalancer should stop doing anything - trying to get nodes more precisely balanced is futile with each node making independent decisions based on asynchronous data.

**Comment by cuongdo** [comment]
This was resolved by #9230, also making the allocator tests much happier
