### ISSUE TITLE
cdc: disallow stable casts in cdc expressions

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#90354]
```
root@localhost:26257/defaultdb> create changefeed with schema_change_policy='stop' as select d::timestamptz from hasdates;
{"key":"[806776683378376705]","table":"hasdates","value":"{\"d\": \"2022-10-20T00:00:00Z\"}"}
```

Stable casts like other stable functions should be disallowed by default in cdc expressions as they depend on session data that isn't available when evaluating.

Jira issue: CRDB-20727

**Comment by miretskiy** [comment]
I don't know about that; should that information be captured when changefeed created perhaps?
I mean it's seems ... not ideal not to allow cast to timestamptz

**Comment by HonoreDB** [comment]
I think there are generally ways to avoid stable casts (in this case, by using a function that explicitly takes a timezone).

**Comment by miretskiy** [comment]
Sure -- but... why if we can do something reasonable (as I believe we can?)
