### ISSUE TITLE
upgrades: don't log an error when preserve_downgrade_option is set

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#90382]
Followup to  #90165 reported by @rafiss 

the change in that other PR makes all failures to upgrade an error in logging.

However, when `preserve_downgrade_option` is set, the fact an auto-upgrade is blocked should not be considered an error.

So we need a different logging in that case.

Jira issue: CRDB-20744

**Comment by rafiss** [comment]
What is the correct home for this ticket?

**Comment by knz** [comment]
> What is the correct home for this ticket?

It would be the shared systems team, which is not currently staffed. When in doubt I'd say ask the TLC.

In this particular case, i was planning to fix it anyway: #91049.
