### ISSUE TITLE
cdc: can't use boolean datums in where clauses

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#90411]
**Describe the problem**

If a table has a boolean column, referring to it in a where clause generally results in the baffling error message

```
ERROR: expected boolean expression, found expression of type bool
```

**To Reproduce**

On release branch:

```sql
root@localhost:26257/defaultdb> select * from hasbools where nonNullableBool;
  id | nullablebool | nonnullablebool
-----+--------------+------------------
   0 |      t       |        t
   1 |     NULL     |        t
(2 rows)

root@localhost:26257/defaultdb> create changefeed WITH schema_change_policy='stop' AS SELECT * from hasBools where nonNullableBool;
ERROR: expected boolean expression, found expression of type bool
SQLSTATE: 42804
```

This doesn't happen for every boolean expression -- `WHERE NOT` works, but `WHERE NOT NOT` doesn't, nor does `WHERE nonNullableBool = true`. The best workaround I've been able to find is `WHERE IF(nonNullableBool, true, false)`.

The behavior seems the same for nullable bools.

**Expected behavior**
No reason this shouldn't work.

**Additional data / screenshots**
The culprit is presumably https://github.com/cockroachdb/cockroach/blob/f48fb416e0de647fa64f5a6704abd4912441b4a1/pkg/sql/constraint.go#L95 , it probably needs to unwrap or normalize the type before comparing using ==.

Jira issue: CRDB-20756

Epic CRDB-17161

**Comment by miretskiy** [comment]
This is fixed on the master.
