### ISSUE TITLE
pgwire: missing ability to express HBA rule matches using usernames with a domain suffix

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#90436]
**Describe the problem**

The HBA rules are selected prior to the mapping done by the GSS layer or the pg_ident layer. Therefore, they apply to the full original username, including possible domain suffix (user@domain)

Currently our HBA system does not support domain suffixes in rules. It should.

Jira issue: CRDB-20769

**Comment by knz** [comment]
Associated requests from @data-matt :  

- double check that the '@' sign of the original username appears in logs.
- log which of the maps applied in the pg_ident code
- if at all possible remember the original username in the SQL session

**Comment by data-matt** [comment]
I see the user@domain in the logs.
