### ISSUE TITLE
roachtest: use N2 instance types instead of N1

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#90538]
**Is your feature request related to a problem? Please describe.**

See this [internal discussion](https://cockroachlabs.slack.com/archives/C023S0V4YEB/p1666610661397879). N2 instance types exhibit better price-performance ratios so making this switch could be part of reducing CI spend.

Jira issue: CRDB-20827

**Comment by ajwerner** [comment]
I don't really understand this for `roachtest`. Most of our roachtests aren't going to finish faster if they had faster computers; most of them run for fixed durations. n2 is more expensive than n1 on a unit-time metric. Also, it's very confusing when we change instance types for the impact to `roachperf`. I somewhat buy this for the unit tests.

**Comment by irfansharif** [comment]
Doh, good point. It might still be an exercise worth doing though I guess not for $ reasons -- it'd be good to run our benchmarks using instance types we expect users to use to have more comparable numbers to discuss with. For the AC tests for ex. we're going to bias towards EC2.

**Comment by rafiss** [comment]
I think the `roachtest` instance types should be the same as the instance types we use in CockroachDB Dedicated. As written, this issue makes it sound like we should just go ahead and change this for `roachtest`. However, a key topic of the internal discussion you linked is that "it’s important that db engineers are able to recreate roachprod clusters that look as close to CC clusters as possible."

**Comment by renatolabs** [comment]
Done in #104419.
