### ISSUE TITLE
sqlliveness: one multi-tenant server can delete another server's instance ID

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#90576]
There's a race between a server B [stealing](https://github.com/cockroachdb/cockroach/blob/00af7d7089d90ccaf9d12724872881064c68e9aa/pkg/sql/sqlinstance/instancestorage/instancestorage.go#L148-L151) server A's instance ID and server A [deleting its session ID](https://github.com/cockroachdb/cockroach/blob/f064d9fd50743d935f6b0d90da41fc0dff77f3df/pkg/sql/sqlinstance/instanceprovider/instanceprovider.go#L144). If the former wins the race, then A will delete B's instance ID record. What makes the race more likely is the fact that there's no tolerance for clock skew in the liveness code. So, if B has a fast clock, it will consider B's session expired and steal its instance potentially before A considers its own session expired.

This will cause the instances table to become out of sync with reality.

We should probably add an ownership check to the instance deletion transaction.

Jira issue: CRDB-20842

**Comment by ajwerner** [comment]
https://github.com/cockroachdb/cockroach/pull/90427 may indirectly help here.

**Comment by ajwerner** [comment]
> We should probably add an ownership check to the instance deletion transaction.

Another option is to use a `CPut` with a `nil` value, which is a deletion tombstone in cockroach sql. If we kept track of the value we used for the initial write it shouldn't be hard.

**Comment by jaylim-crl** [comment]
Hm, re: clock skew argument. Wouldn't it be the same case during SQL pod startup as well? Consider the case where we already have SQL pod A started up. If B starts up with a faster clock, there could be a possibility where it consider A's session to have expired, and then grab its instance ID. If at the moment, A's session gets extended, wouldn't we be in a bad state?
