### ISSUE TITLE
dev build --cross=linuxarm doesn't work 

### ISSUE THREAD

**Issue by osguydch** [cockroachdb/cockroach#90584]
**Describe the problem**

When I tried to cross compile for linux-arm , I used this command like bellow

dev build --cross=linuxarm

2022/10/24 22:09:15 could not create directory /home/roach/.cache/bazelisk: mkdir /home/roach/.cache: permission denied

I tried mkdir /home/roach and chmod 777 for /home/roach

this error still appear, why ?

**To Reproduce**

What did you do? Describe in your own words.

 I tried to cross compile for linux-arm  for my own device used aarch64 ubuntu os

If possible, provide steps to reproduce the behavior:

I used this command like bellow

dev build --cross=linuxarm

**Expected behavior**

the dev build will success and give me the correct version of cockroach

**Additional data / screenshots**

this error is on the master branch of latest.

Jira issue: CRDB-20847

**Comment by rickystewart** [comment]
@osguydch Hi, what version of the code do you have checked out?

The cross-build runs in a Docker container and you might see this if the data volume gets into a weird state. `docker volume rm bzlhome` may fix this.

**Comment by osguydch** [comment]
> @osguydch Hi, what version of the code do you have checked out?
> 
> The cross-build runs in a Docker container and you might see this if the data volume gets into a weird state. `docker volume rm bzlhome` may fix this.

Thanks a lot. 
It seems work, the error disappeared.

**Comment by rickystewart** [comment]
Awesome, let me know if you need any more help.
