### ISSUE TITLE
kvserver: allocator cpu balancing for overload protection

### ISSUE THREAD

**Issue by kvoli** [cockroachdb/cockroach#90582]
This is a tracking issue for balancing CPU in a cluster. The motivation for balancing CPU is to prevent and if necessary, mitigate CPU saturation. The current balance objective is based on QPS, which has known limitations [^1][^2] in managing CPU saturation.

Tracked issues:

- Setup
	- [x] https://github.com/cockroachdb/cockroach/issues/90589
	- [x] https://github.com/cockroachdb/cockroach/issues/90590
- CPU rebalancing
	- [x] https://github.com/cockroachdb/cockroach/issues/91152
	- [x] https://github.com/cockroachdb/cockroach/issues/95380
- CPU range load based splitting
	- [x] https://github.com/cockroachdb/cockroach/issues/90574
	- [x] https://github.com/cockroachdb/cockroach/issues/95377
	- [x] https://github.com/cockroachdb/cockroach/issues/96869
- UX observability
	- [x] https://github.com/cockroachdb/cockroach/issues/95384
	- [x] https://github.com/cockroachdb/cockroach/issues/95383
	- [x] https://github.com/cockroachdb/cockroach/issues/95386
    - [x] https://github.com/cockroachdb/cockroach/pull/94931
	- [x] https://github.com/cockroachdb/cockroach/issues/95381
    - [x] https://github.com/cockroachdb/cockroach/issues/96212

Jira issue: CRDB-20845

[^1]: [related issue](https://github.com/cockroachdb/cockroach/issues/83490)
[^2]: [internal allocator signal experiments](https://docs.google.com/document/d/1PksSMGUG1S--XG8fXMjULGqP7xUVUCb9KU_4kwy3vS0/edit)

**Comment by irfansharif** [comment]
x-linking #83490.

**Comment by kvoli** [comment]
related https://github.com/cockroachdb/cockroach/issues/90574

**Comment by kvoli** [comment]
Moved https://github.com/cockroachdb/cockroach/issues/90140 here from tracking issue https://github.com/cockroachdb/cockroach/issues/90582.
