### ISSUE TITLE
TestComposeGSSPython failed on master

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#90610]
See CI flake [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=7125667&problemId=4141)

Jira issue: CRDB-20859

**Comment by msbutler** [comment]
another one https://teamcity.cockroachdb.com/viewLog.html?buildId=7126848&problemId=4141

**Comment by rail** [comment]
Fixed by #90617
