### ISSUE TITLE
ui: column sort broken on Database pages in CC Console

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/cockroach#90662]
In the tables on the Database Overview and Database Details of the CC Console, all column sorters are broken except for the first (default sorting) columns.

Here's a demonstration of the bug: https://www.loom.com/share/cb1900af19404bd6b6bd22ddb6278f35

Jira issue: CRDB-20875

**Comment by maryliag** [comment]
Different component being used for 23.1+
