### ISSUE TITLE
distsql: flake in TestAggregatorAgainstProcessor

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#90691]
Found here:
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/7148121?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

Test output: 
[testfailure.txt](https://github.com/cockroachdb/cockroach/files/9869271/testfailure.txt)

cc @mgartner for triage.

Jira issue: CRDB-20893

**Comment by yuzefovich** [comment]
I was able to repro this with `./dev test pkg/sql/distsql -v --stream-output -f=TestAggregatorAgainstProcessor -- --test_env=COCKROACH_RANDOM_SEED=4103590547333622857`, fix incoming.
