### ISSUE TITLE
kvtenantccl: flake in TestTenantUpgradeFailure

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#90690]
Found here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/7148072?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

```
=== RUN   TestTenantUpgradeFailure/upgrade_tenant_have_it_crash_then_resume
    tenant_upgrade_test.go:332: query 'SHOW CLUSTER SETTING version': expected:
        1000022.2-2
        got:
        1000022.2-4
    --- FAIL: TestTenantUpgradeFailure/upgrade_tenant_have_it_crash_then_resume (38.73s)
```

cc @fqazi @ajwerner since you've been looking at this before

Jira issue: CRDB-20892

Epic CRDB-10829

**Comment by ajstorm** [comment]
Hasn't occurred in 5 months, and may be fixed by https://github.com/cockroachdb/cockroach/pull/94998.  Closing.
