### ISSUE TITLE
ui: QOL improvements for SQL Activity page

### ISSUE THREAD

**Issue by THardy98** [cockroachdb/cockroach#90708]
**Is your feature request related to a problem? Please describe.**
This issue is derived from a thread on the public SQL O11Y Slack channel suggesting a few quality of life improvements to the SQL Activity page, namely:
- Adding a simple visual hint in on the fingerprint statement row that highlights whether it's an implicit vs explicit statement. A special highlight or font or icon on the left is all that is needed, something small but visible. (currently a statement can only be seen as implicit/explicit from the Statement Details page)
- In 22.1, there is no "reset time" link that refreshes the statements list in the filter. Instead, you need to click on the dropdown 1Hour and reselect 1 hour to emulate the same refresh. There is a "Now" button, but for some reason the button is always grayed out and the hint message is "past 1 day" which is unclear/unhelpful.

**Describe the solution you'd like**
- A visual hint to highlight whether a statement fingerprint was executed as an implicit/explicit transaction.
- An easy to use action to refresh the list of statement fingerprints with the current filters (on v22.1).
  - Fix/replace the "Now" button on 22.1 so it can be used to refresh the page, provide a clearer and more helpful tooltip

Jira issue: CRDB-20901

**Comment by maryliag** [comment]
cc @dongniwang about the implicit vs explicit: would having the value as a column be enough? Not sure how to have a hint that would clearly indicate that

**Comment by kevin-v-ngo** [comment]
The second point on "Now" sounds like a bug? It should navigate the user to the default cluster interval (1 hour).
