### ISSUE TITLE
ui: read amplification incorrectly sums across stores

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#90734]
**Describe the problem**

Consider this 4-store per-node cluster. On our storage dashboard, it appears that the read-amp is 16. It is in fact 4 in each store.
<img width="1023" alt="Screen Shot 2022-10-26 at 4 20 24 PM" src="https://user-images.githubusercontent.com/1839234/198129004-a97c6d77-9ed2-4983-85ad-7b29b58455ae.png">

Jira issue: CRDB-20913

**Comment by ajstorm** [comment]
We are hitting this on the DRT cluster as well (since we're running 16 stores per node).  Any chance we could get to this sometime soon?

**Comment by ajstorm** [comment]
Increasing the priority of this issue as it's making debugging the `drt-large` cluster difficult.
