### ISSUE TITLE
sql: use row-level TTL for rangelog, eventlog and web_sessions

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#90787]
Currently these system tables are being cleaned up by a special-purpose background async task.

Now that SQL implements TTL natively (with a TTL gc job), we should make use of this infrastructure. It would provide the following benefits:

- it would make it possible to pause/unpause the cleanup with a better UX than cluster settings
- it would provide easier-to-use tracing in case of problems

One possible degree of complexity is that we want the TTL to be configurable by the user, without a schema change on the table. This means possibly that the TTL expression should be able to refer to a cluster setting.

**Comment by aadityasondhi** [comment]
Related Issue: https://github.com/cockroachdb/cockroach/issues/89453

**Comment by knz** [comment]
oh it's a dup of that other issue then. let me delete that and update the other one.
