### ISSUE TITLE
sql: add UDFs to schema change random workload.

### ISSUE THREAD

**Issue by chengxiong-ruan** [cockroachdb/cockroach#90783]
Make sure that schema changer random workload is able to generate UDF statements.

Jira issue: CRDB-20942

Epic CRDB-19168

**Comment by yuzefovich** [comment]
@fqazi has this already been addressed?

**Comment by fqazi** [comment]
@yuzefovich  Yes we have basic coverage for UDF's inside the workload. Lets close this off
