### ISSUE TITLE
rpc: Clock offset check reports wrong number of nodes

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#9081]
In a 5-node cluster (with artificially-induced clock offsets), we get this message:

`F160902 22:24:09.486293 server/server.go:145  fewer than half the known nodes are within the maximum offset of 250ms (3 of 6)`

That should say "3 of 5", not "3 of 6". I suspect the problem is that we sometimes use hostnames and sometimes IP addresses (you can see this in [the status pages](https://beta.cockroachdb.com:8080/debug/events?fam=grpc.ClientConn&b=0)), so we get duplicate entries in the offset map.

**Comment by spencerkimball** [comment]
@tamird could you take a look at this? Might be trivially closable as you've done work on this since the issue was filed.

**Comment by tamird** [comment]
Not trivially closable. @bdarnell the link you originally posted has rotted, and I can't find similar information on current cluster, probably because grpc tracing was disabled 3 days after this issue was filed (076368938c1fcad4969a5f9b6f96164bbf11a111).

**Comment by bdarnell** [comment]
I don't think this would show up on any of our current test clusters now that we've improved our DNS setup, but the underlying issue is still there. I think this involved a cluster where `--advertise-host` was left at the default (and therefore used a hostname) while `--join` used IP addresses. (I'm pretty sure it was a jepsen cluster; those scripts may still reproduce the issue). This can be left for post-1.0.

**Comment by bdarnell** [comment]
All of this has been rewritten; I think it's better about deduping now.
