### ISSUE TITLE
sql: scanning `pg_type`'s `pg_type_oid_idx` produces incorrect results

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#90871]
The example below queries for three `oid`s within `pg_type`. Performing a point lookup for each of those three values produces no results.

```
defaultdb> select oid from pg_type limit 3 offset 100;
     oid
--------------
  4294967230
  4294967275
  4294967274
(3 rows)

defaultdb> select oid from pg_type where oid = 4294967230;
  oid
-------
(0 rows)

defaultdb> select oid from pg_type where oid = 4294967275;
  oid
-------
(0 rows)

defaultdb> select oid from pg_type where oid = 4294967274;
  oid
-------
(0 rows)
```

The query plan for the last statement:

```
defaultdb> explain select oid from pg_type where oid = 4294967274;
                  info
----------------------------------------
  distribution: local
  vectorized: true

  • virtual table
    table: pg_type@pg_type_oid_idx
    spans: [/4294967274 - /4294967274]
(6 rows)
```

Epic CRDB-17785
Jira issue: CRDB-20975

**Comment by rafiss** [comment]
I believe there are two possible fixes:
1. Use `partial: true` in the definition of the pg_type virtualIndex. This index does not contain rows for "implicit record types" for virtual tables.
2. Modify this code so it also adds rows for virtual table implicit record types: https://github.com/cockroachdb/cockroach/blob/0c1c3e7777b28a30ebe41428fb173f0156e8968c/pkg/sql/pg_catalog.go#L3225
