### ISSUE TITLE
pgwire: empty query should result in emptyresponse, not error/commandcomplete

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#9093]
Found by @fishcakez in https://github.com/cockroachdb/cockroach/issues/5582#issuecomment-237389617:

*An empty query will fail with an error, postgresql handles this with an EmptyQueryResponse message, instead of CommandComplete. This may not matter to cockroach.*

Note that this is may appear to be a dup of #3852 but the fix to that issue didn't change what happens for empty queries.

**Comment by knz** [comment]
cc @mjibson @dt

**Comment by dt** [comment]
@knz can you clarify "the fix to that issue [#3852] didn't change what happens for empty queries."... I thought that that was _exactly_ what that changed.

**Comment by knz** [comment]
@fishcakez could you give more details about how you isolated this specific issue in your use case?

**Comment by fishcakez** [comment]
The reference issue seems to refer to using the simple `Query` messages to send multiple queries (of which some are empty). The situation we encountered (running the test suite for a postgres client against cockroach) is doing a single empty (prepared) query using `Parse`, `Describe`, `Execute`. I did not check for which message of the 3 the error occurs. However postgres will return the `EmptyQueryResponse` and so the test for our client fails.

**Comment by tlvenn** [comment]
@mjibson any chance to pull that fix soon ?

**Comment by mjibson** [comment]
I'm waiting on https://github.com/lib/pq/pull/500 to get merged (which I don't control), otherwise we can't write a test for this. Sorry for the delay. @tamird do you have write access to lib/pq? Would you be willing to review + merge that PR?

**Comment by tamird** [comment]
Sadly I do not have commit over there.

**Comment by tlvenn** [comment]
Hope this can finally be fixed now the changes have been merged in lib/pq. Thanks for your work @mjibson and @tamird !
