### ISSUE TITLE
stability: per-replica timestamp cache memory overhead

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#9101]
After running `zerosum -n 4 -m 3 -c none` for an hour, I peeked at the graphs (the green line in the chart is the Go inuse):

<img width="269" alt="screen shot 2016-09-04 at 3 47 35 pm" src="https://cloud.githubusercontent.com/assets/6201335/18233496/ff8c3f3c-72b6-11e6-9f6f-3f1f1a853518.png">

The number of ranges (not shown) grows at approximately the same rate as that graph. A [heap profile](https://github.com/cockroachdb/cockroach/files/454080/pprof001.svg.zip) shows that ~50% of the memory is being consumed by the timestamp cache. Given that the timestamp cache operates on key ranges, I'm wondering why we have a cache per replica as opposed to having 1 per store/server that is shared by all of the replicas. 

Note the other significant consumer of memory in the heap profile is snapshots, which is surprising given that the ranges are relatively small in this test (due to forced splits). I wonder if we have a bug that is holding on to snapshots longer than expected. 

Cc @cockroachdb/stability

**Comment by petermattis** [comment]
`TimestampCache.SetLowWater` is set on lease acquisition to the start time of the lease. So its not trivial to move to a shared `TimestampCache`. Perhaps we could maintain a per-Replica low-water combined with shared interval trees for `TimestampCache.{w,r}cache`. Or maybe there is something silly going on here. Looking at the code, I don't see where the `TimestampCache` is cleared when losing the range lease. The `zerosum` invocation above is doing lots of lease transfers.

**Comment by bdarnell** [comment]
Maybe on lease acquisition we just insert a span covering the whole range, instead of using the low-water mark? (leaving the low-water mark to be used only to track spans that have been evicted from the cache) I'm not sure what the performance implications of one huge timestampCache would be relative to the current per-range model. The constants in timestamp_cache.go are also currently arbitrary and may need adjustments.

Regarding snapshots, I also suspect we have a bug that is holding on to them too long, but that's a separate matter.

**Comment by petermattis** [comment]
Yeah, I was thinking the same thing about adding a covering span for the range. I think we can hold off on any change here as the majority of the memory usage was due to not clearing the timestamp cache. 

Re snapshots: is it possible for `Replica.mu.snapshotChan` to contain a snapshot that is never consumed? What happens if raft calls `Replica.Snapshot` which initiates the asynchronous creation of the snapshot, but then the lease is transferred to another replica (along with the raft leadership)? I don't see anywhere that we actually close `Replica.mu.snapshotChan`. Since only the raft leader initiates snapshots, we could clear `Replica.mu.snapshotChan` if a replica is not the raft leader. If this is the problem, streaming snapshots, which will allow us to get rid of the async snapshot generation, will also fix it.

**Comment by bdarnell** [comment]
> is it possible for Replica.mu.snapshotChan to contain a snapshot that is never consumed?

Yes, for a time. `snapshotChan` is unbuffered, but the snapshot generation goroutine will wait [here](https://github.com/cockroachdb/cockroach/blob/a0dba3c47ca39b21aca03400cbe5b9968ea9a5b8/storage/replica_raftstorage.go#L343) for raft to retrieve the snapshot. If it never does the snapshot will be discarded after a timeout (currently 1 minute). However, a lock on the store is held throughout this process, so we can't have more than one snapshot in this state at a time. 

Of course, blocking all other snapshots for 1 minute is not ideal either, so we should do something to cancel the pending snapshot when we've lost leadership.
