### ISSUE TITLE
cli: review new sql shell

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#91023]
@knz has requested our help with reviewing some nice enhancements to the CLI:

- Line editor
  https://github.com/cockroachdb/cockroach/pull/88574 and https://github.com/cockroachdb/cockroach/pull/86457
- Completion
  https://github.com/cockroachdb/cockroach/pull/87606
- `\d` client-side commands 
  https://github.com/cockroachdb/cockroach/pull/88061

Work with him to understand this code, as our team will be taking ownership of much of it.

Epic CRDB-17785

Jira issue: CRDB-21079

**Comment by knz** [comment]
Maybe add #88574 to the list
