### ISSUE TITLE
Update "App" to "Application name" throughout the UI for consistency

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#91039]
UI locations where "App" is being used:

- Statements, Transactions, and Sessions overview filter
- Statement fingerprint details

Jira issue: CRDB-21082

**Comment by maryliag** [comment]
do you mean here on 22.1? Because it already uses "Application Name" in 22.2 on the places you mentioned

**Comment by maryliag** [comment]
Closed by
https://github.com/cockroachdb/cockroach/pull/87803
https://github.com/cockroachdb/cockroach/pull/88078
