### ISSUE TITLE
pgbuiltins: pg_blocking_pids

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#91068]
Support `pg_blocking_pids` builtin. Needed for pgadmin.

https://www.postgresql.org/docs/current/functions-info.html

We can implement this by making it return an empty array, since Cockroach doesn't use PIDs.

Jira issue: CRDB-21093

**Comment by girishv-tw** [comment]
Hi @jordanlewis , 
I am new to working on cockroach db and was thinking of picking up this issue. Is that ok ? 
I have performed an initial analysis on the issue and from that i have arrived at a conclusion that a resolution to the issue would be to , add a `builtin` for `pg_blocking_pids` with the return type as an array of integers and the function returning an empty array of integers in [this file](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sem/builtins/pg_builtins.go#L1935)
Could you help me assert that this is the correct fix ?

**Comment by jordanlewis** [comment]
Yes, sounds right to me. Thanks!
