### ISSUE TITLE
pgbuiltins: pg_get_function_arguments

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#91073]
Support `pg_get_function_arguments`. 

https://www.postgresql.org/docs/15/functions-info.html

Jira issue: CRDB-21096

**Comment by highpon** [comment]
I am trying to implement `pg_get_function_arguments.`
`pg_get_function_arguments` should print a list of arguments including default values. So I tried to define the function as follows to test it out, but it failed.
From the log, it appears that CockroachDB does not yet allow default values to be specified for function arguments.
Is it currently not possible to implement this function?

```
demo@127.0.0.1:26257/movr> CREATE OR REPLACE FUNCTION print_value(value INTEGER DEFAULT 1000)                                                                                               
                        -> RETURNS INTEGER AS $$                                                                                                                                            
                        ->   SELECT value;                                                                                                                                                  
                        -> $$ LANGUAGE sql;                                                                                                                                                 

ERROR: unimplemented: default value
SQLSTATE: 0A000
HINT: You have attempted to use a feature that is not yet implemented.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.

We appreciate your feedback.
```

**Comment by cpustejovsky** [comment]
@highpon It appears to be supported. https://www.cockroachlabs.com/docs/stable/default-value.html

**Comment by jordanlewis** [comment]
Hi @highpon, we can just omit default arguments if they're not supported. Thanks for the link @cpustejovsky but that one is about default values in columns, not default values for function arguments. :)

**Comment by cpustejovsky** [comment]
@jordanlewis thanks for clarifying that for me! :+1:

**Comment by highpon** [comment]
@jordanlewis Thanks for response!
I implemented `pg_get_function_arguments` with omitting default values.
