### ISSUE TITLE
colexec: TestExternalSortMemoryAccounting is flakey

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#91076]
Seems to be failing somewhat regularly:

```
    external_sort_test.go:169: 
        	Error Trace:	/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/4988/execroot/com_github_cockroachdb_cockroach/bazel-out/aarch64-fastbuild/bin/pkg/sql/colexec/colexecdisk/colexecdisk_test_/colexecdisk_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/colexec/colexecdisk/external_sort_test.go:169
        	Error:      	"2083771148" is not greater than or equal to "2187528824"
        	Test:       	TestExternalSortMemoryAccounting
        	Messages:   	maximum memory bound not satisfied: actual 2187528824, expected max 2083771148
```

Test history: https://teamcity.cockroachdb.com/project.html?tab=testDetails&projectId=Cockroach_Ci_TestsAwsLinuxArm64BigVm&testNameId=7444190392994169507&page=1

Jira issue: CRDB-21097

**Comment by ajwerner** [comment]
Attempted fix was https://github.com/cockroachdb/cockroach/pull/91008. Fixed by https://github.com/cockroachdb/cockroach/pull/91044.

**Comment by yuzefovich** [comment]
Saw it fail again on the staging branch :(
```
Messages:   	maximum memory bound not satisfied: actual 2188276464, expected max 2105798160
```
https://teamcity.cockroachdb.com/viewLog.html?buildId=7266955&buildTypeId=Cockroach_BazelEssentialCi

**Comment by ajwerner** [comment]
alright, I guess we need to just pay attention now and stop just mindlessly incrementing a variable.

**Comment by yuzefovich** [comment]
I'll take a closer look
