### ISSUE TITLE
Build problems in teamcity

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#9107]
The `acceptance`, `test`, and `testrace` categories [on teamcity](https://teamcity.cockroachdb.com/project.html?projectId=Cockroach_UnitTests) have all been failing for hours on the same dependency-related issue:

```
[09:26:10]can't load package: package github.com/robfig/glock: 
[09:26:10]../../robfig/glock/save_test.go:1:1: expected 'package', found 'EOF'
[09:26:10]Process exited with code 1
```

**Comment by a-robinson** [comment]
The only thing that's been merged recently is https://github.com/cockroachdb/cockroach/pull/9097, which is related to glock, but looks fairly benign and did pass teamcity checks before submitting.

**Comment by a-robinson** [comment]
cc @jordanlewis - where can I see what the "Install Prerequisites" step is doing?

**Comment by petermattis** [comment]
See https://github.com/cockroachlabs/teamcity-config/issues/25. If you `git grep GLOCK` in that repo you can find the config file. I'm not sure what is going wrong, though.

**Comment by jordanlewis** [comment]
I'm AFK until later - not sure what's going wrong here. Probably some bad
state crept in - maybe from the vendoring patch? You can look at the
install prerequisites step in the ui by going to the meta runners config
page of the top level cockroach project.

**Comment by a-robinson** [comment]
@jordanlewis fixed this - tl;dr is that an old commit whose CI was run on top of a very old source tree, whose CI scripts messed with the build env.
