### ISSUE TITLE
sql: TestLogic_create_as_non_metamorphic is flakey

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#91080]
All failures seem to happen in the validation stage, after the test has succeeded. Example:

```
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/8996/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/logictestccl/tests/3node-tenant/3node-tenant_test_/3node-tenant_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/create_as_non_metamorphic:15: error while processing
    logic.go:3799: test was successful but validation upon completion failed: failed to test for descriptor JSON round-trip: dial tcp 127.0.0.1:41383: connect: connection refused
```
https://teamcity.cockroachdb.com/viewLog.html?buildId=7262839&buildTypeId=Cockroach_UnitTests_BazelUnitTests&tab=buildResultsDiv

Test history points to a number of other failures:
https://teamcity.cockroachdb.com/project.html?projectId=Cockroach_Ci_TestsGcpLinuxX8664BigVm&testNameId=8263307154562963782&tab=testDetails

Jira issue: CRDB-21099

**Comment by ajwerner** [comment]
Ultimately this is an overload thing I believe. I'm going to restrict the test to local and call it a day.
