### ISSUE TITLE
Clarify the tool tip for SQL statement errors metrics chart

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#91094]
Tracking issue: https://github.com/cockroachdb/docs/issues/9893 

We should align with our [documentation](https://www.cockroachlabs.com/docs/stable/ui-sql-dashboard.html#sql-statement-errors) and specify that this is client-side retry errors.

_The number of statements which returned a planning, runtime, or client-side retry error._ 

Jira issue: CRDB-21103

**Comment by maryliag** [comment]
What is the text that should be used?

**Comment by kevin-v-ngo** [comment]
> What is the text that should be used?

Updated the issue!

_The number of statements which returned a planning, runtime, or client-side retry error._
