### ISSUE TITLE
ui: Reads are few even when all other graphs seem to indicate some activity

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#9109]
<img width="1423" alt="screen shot 2016-09-05 at 1 05 17 pm" src="https://cloud.githubusercontent.com/assets/11774212/18254244/aef6d6aa-7369-11e6-9e4f-0fb8ae2c99a8.png">

I was running the block-writer against the cluster

**Comment by bdarnell** [comment]
Why is that surprising? The block_writer only writes, it doesn't read.

**Comment by vivekmenezes** [comment]
The use of "Query time" to represent the time of writes. As well as the bytes in/bytes out graph which to me reads like bytes written/bytes read; I'm assuming it means bytes on the wire?

**Comment by mrtracy** [comment]
This is out of date.
