### ISSUE TITLE
Allow batch execution of InternalMergeRequest

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#911]
InternalMergeRequest is currently not one of the commands supported by InternalBatchRequest. However, supporting it may not be as simple as simply adding it to the support commands list - this is because InternalMergeRequest is explicitly not transactional, and cannot be rolled back.

The simplest solution I can think of is to throw an error before executing an InternalBatchRequest if it has both a transaction *and* an InternalMergeRequest. If that doesn't seem adequate, we can discuss a better solution to the problem in this issue.

**Comment by spencerkimball** [comment]
No I think that's fine. Feel free to implement this by adding InternalBatchRequest to InternalBatchRequest. Perhaps you could add a method to the InternalBatchRequest struct which validates it to simplify the locations in the code where we do the check. Currently, we serialize the execution of commands in the batch in txn_coord_sender.go, though of course this is going to change soon(ish).
