### ISSUE TITLE
kvserver: TestRemovePlaceholderRace is flaky

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#91121]
**Describe the problem**

client_raft_test.go:2878: cannot remove learner while snapshot is in flight
**To Reproduce**

Stress the test

Jira issue: CRDB-21112

**Comment by pavelkalinnikov** [comment]
```
./dev test pkg/kv/kvserver:kvserver_test --filter=TestRemovePlaceholderRace --stress
...
32479 runs so far, 0 failures, over 4h4m40s
```

Maybe need to run it in gceworker, same way as this flake was [discovered](https://github.com/cockroachdb/cockroach/pull/89632#issuecomment-1288443983).

**Comment by pavelkalinnikov** [comment]
Managed to repro on gceworker.
