### ISSUE TITLE
sql: simple cross join in randomized schemachanger workload are hitting in-mem temp storage

### ISSUE THREAD

**Issue by fqazi** [cockroachdb/cockroach#91131]
Despite having a fetch first rows limit on randomly generated SELECT queries in the schemachanger workload, we are seeing scenarios where the memory limit might be kicking in incorrectly for simple cross-join. The query in question that we observed had the form:
`SELECT t0.col1845_1847 AS col0,t2.col1076_1083 AS col1,t2.col1535_1551 AS col2,t2.col1535_1545 AS col3,t0.col1845_1847 AS col4,t1.col1076_1081 AS col5,t2.col1076_1077 AS col6,t1.col1076_1090 AS col7,t1.col1076_1090 AS col8 FROM schema1900.table1912 AS t0 ,public.table1149 AS t1 ,schema1782.table1897 AS t2  FETCH FIRST 1 ROWS ONLY` 
runs into
`ERROR: in-mem temp storage: disk budget exceeded: 1048576 bytes requested, 104857600 currently allocated, 104857600 bytes in budget (SQLSTATE 53100)`

The logs for the run from the server and randomized workload can be found at:
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/7280551

Jira issue: CRDB-21117

**Comment by fqazi** [comment]
@yuzefovich Can you take a look and this was an area you were poking around?

**Comment by yuzefovich** [comment]
Can we get a repro for this? (I couldn't find anything useful in the logs.) I'm afraid we cannot do much during the execution even in the presence of "fetch first 1 rows" - the query has several joins, and we need to buffer the right side. We did have a similar problem before (#67816), but it's been fixed. I don't think there are any improvements in this area that we have in mind, so it might be necessary to just catch such errors by the randomized workload and ignore them.
