### ISSUE TITLE
backupccl: issue protected timestamp for restore spans

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#91148]
Currently, we don't issue a protected timestamp over spans we're about to restore, which at the surface, does not seem like an issue, as restore doesn't overwrite existing keys. The lack of a PTS can cause the restore to fail, however, if the span we're restoring into has a very low gc ttl, like say 5 minutes. Specifically, if an AddSSTable request takes longer than the gc ttl, then its batch request timestamp may be earlier than the replica's gc threshold, causing the AddSStable to fail. 

We can prevent this failure by preventing the gc threshold from advancing in replicas where the restore is occuring. To do this, a pts should be issued over the whole restore span, before any restore flow begins. 

Note that the addsstable request can't merely be retried at a higher batch request TS, as all the keys in the SST have timestamps written at the batch request timestamp. Bumping the batchTS would require rewriting the SST, which seems quite expensive. 

Jira issue: CRDB-21123

**Comment by shermanCRL** [comment]
I assume we can’t backport due to proto change but I’ll ask anyway...

**Comment by msbutler** [comment]
i don't think we can backport this. If a customer does encounter this issue, which we haven't ever seen in an escalation, they can always increase the gc ttl on the target or parent target they are attempting to restore as a workaround.
