### ISSUE TITLE
storage: add unconditional range tombstone cluster version

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#91147]
Before 23.1, we should remove the `storage.mvcc.range_tombstones.enabled` setting, to ensure all clusters are always MVCC-compliant.

Jira issue: CRDB-21122

Epic CRDB-20465

**Comment by jbowens** [comment]
> This means that 23.1 nodes in mixed 22.2 clusters will always write MVCC range tombstones, even when the corresponding 22.2 nodes have the setting off. I think this is probably OK? That also means that we don't need to keep the SQL schema logic around to write MVCC range tombstones in 23.1, even for mixed-version clusters.

Given the prefix-synthesizing bug fixed in #97572, I think we should introduce a new cluster version gate that ensures a  23.1 node won't write MVCC range tombstones unless the full cluster has upgraded. Thoughts?

**Comment by erikgrinaker** [comment]
Seems prudent. The cost would be that we'll need to keep the old schema/import code around for mixed-version clusters, but we can still guarantee that there won't be any non-MVCC operations after finalization (assuming we have a migration to flush out any old jobs or they transition to using range tombstones).

**Comment by erikgrinaker** [comment]
cc @cockroachdb/disaster-recovery @cockroachdb/sql-schema

**Comment by ajwerner** [comment]
Schema was not planning to remove the code. We are planning to just ratchet up the version gates and migrations written for 22.2 to 23.1

**Comment by erikgrinaker** [comment]
> Given the prefix-synthesizing bug fixed in #97572, I think we should introduce a new cluster version gate that ensures a 23.1 node won't write MVCC range tombstones unless the full cluster has upgraded. Thoughts?

I guess this means that we'll need to keep the setting around as well, but stop respecting it once 23.1 is finalized, so that an enabled setting still takes effect with an unfinalized 23.1 binary.

**Comment by nicktrav** [comment]
@jbowens and I regrouped on this one today. Plan for 23.1 cycle:

- Close out https://github.com/cockroachdb/cockroach/pull/96966 as obsolete.
- Add an internal cluster version that we use as a feature gate.
- Plumb feature gate into existing helper functions.
- `<` cluster version - respect existing cluster setting.
- `>=` cluster setting - unconditionally enable range tombstones. This would be the point of no return.
- During 23.2 dev cycle, rip out the feature flag, helper functions and the cluster setting.

Let me know if I missed anything there.
