### ISSUE TITLE
sql,builtins: support to_char formatting builtins for timestamp and interval

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#91156]
We should support the following builtins for compatibility with Postgres. They allow timestamps and intervals to be formatted with a custom format.
```
 to_char(timestamp, text)
 to_char(interval, text)
```
https://www.postgresql.org/docs/current/functions-formatting.html

Spun off https://github.com/cockroachdb/cockroach/issues/3781

The goal is to support our DMS integration. So we could limit our first implementation to have only the features that DMS needs. Talk to @otan about this.

Jira issue: CRDB-21127

Epic CRDB-17785

**Comment by otan** [comment]
format required for DMS: `YYYY-MM-DD HH24:MI:SS.US`
