### ISSUE TITLE
sql/pgwire: prototype for multiple active portals

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#91157]
https://github.com/cockroachdb/cockroach/issues/40195 describes a pgwire feature that allows prepared statements to be partially executed, and have the executions interleaved with each other.

We don't support this right now because our portal state is in a separate state machine (see the `limitedCommandResult` type). Make a prototype to explore how to solve this. The first steps might be to implement this logic in pkg/sql/pgwire/conn.go instead.

Reach out to @rafiss 

Jira issue: CRDB-21128

Epic CRDB-17622

**Comment by ZhouXing19** [comment]
Done by https://github.com/cockroachdb/cockroach/pull/99663 and https://github.com/cockroachdb/cockroach/pull/101026.
