### ISSUE TITLE
CDC expressions for experimental changefeed

### ISSUE THREAD

**Issue by sandr8** [cockroachdb/cockroach#91178]
Up to the introduction of cdc expressions, `EXPERIMENTAL CHANGEFEED FOR ...` supported enough of the same basic options as `CREATE CHANGEFEED FOR ... INTO SINK`.

Thanks to this, I've found it to be a great tool to prototype change feeds and verify the CDC behavior before setting changefeeds up against actual sinks.

I personally would find even more beneficial to have this (or a similar) mechanism as a convenient, zero-setup option to verify and debug cdc expression behaviors.

Jira issue: CRDB-21136

**Comment by ale-dd** [comment]
Thank you so much for the tip! Should we close this ticket?
