### ISSUE TITLE
workload/schemachange: re-enable adding foreign key constraints

### ISSUE THREAD

**Issue by fqazi** [cockroachdb/cockroach#91195]
This part of the workload is disabled because we have bugs cleaning up back references which can lead
to unknown schema errors or relation does not exist errors. We will re-enable this part of the workload once
the issue has been root caused.

Jira issue: CRDB-21143

Epic CRDB-19168

**Comment by ajwerner** [comment]
Is https://github.com/cockroachdb/cockroach/issues/91227 the root cause? Either way, let's leave this for a later time (maybe a stability period?)

**Comment by fqazi** [comment]
Yes, root cause is that, I'm not going to poke at this for now @ajwerner
