### ISSUE TITLE
cluster-ui: last read reporting different values on table/index details pages

### ISSUE THREAD

**Issue by THardy98** [cockroachdb/cockroach#91218]
**Describe the problem**

“Last Read” field on the Index Details page and Table Details page report different values (one reports in UTC, the other doesn’t).

**To Reproduce**

Navigate to the Table Details and Index Details page of a fresh Dedicated cluster and note the last read timestamps on each page.

**Expected behavior**
Expected both pages to display the same timestamp.

**Additional data / screenshots**
Demo of the bug: https://www.loom.com/share/2865a0f2f61042b29bbd57177a191ec6

**Environment:**
 - CockroachDB version [22.2.0-beta.5]

Jira issue: CRDB-21158

**Comment by amyyq2** [comment]
Also, in the Table Details, the column says "Last Used", whereas in Index Details, it says "Last Read". To be consistent, maybe change both to "Last Read"

**Comment by THardy98** [comment]
> Also, in the Table Details, the column says "Last Used", whereas in Index Details, it says "Last Read". To be consistent, maybe change both to "Last Read"

Ah, I had forgotten that the "Last Used" column on the Table Details page can hold different values than just the last read. It can also hold the time at which the index was created or the time at which the index was reset, because of this I'm going to leave it as "Last Used" (at least for now, see note below).

That being said, it might be nice to instead change this column to only display the latest read anyways. I don't think the index's reset time is worth showing in this column as we already show the last reset time by the "reset index stats" button. We could move the index creation time as another row on the index details page (which seems like the more relevant page to hold this information than the table details page), and purely have this column display the time of the latest read. WDYT @kevin-v-ngo ?

I can open another issue for this change if we choose to do so.

**Comment by kevin-v-ngo** [comment]
> That being said, it might be nice to instead change this column to only display the latest read anyways. I don't think the index's reset time is worth showing in this column as we already show the last reset time by the "reset index stats" button. We could move the index creation time as another row on the index details page (which seems like the more relevant page to hold this information than the table details page), and purely have this column display the time of the latest read. WDYT @kevin-v-ngo ?

+1 on changing to Last Used. I'd keep the existing behavior. In previous discussions with Anne, this was meant represent read, create, and reset times. For the latter, it's more common as one would reset stats after a change in their schema and rerun their workload to determine usage. More common when we have index/table level reset stats. It's meant to represent one single value that the user should care about when determining whether the index has been used.

Bu I do agree with the proposal of breaking if down on the index details page to have the best of both experiences. To summarize, i'd vote for:

- Changing column name to Last Used for consistency
- Adding Create and reset time to the index details page

FYI @dongniwang
