### ISSUE TITLE
sql: extend the memory monitor to ease troubleshooting

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#9122]
Required by @RaduBerinde in https://github.com/cockroachdb/cockroach/pull/8691#issuecomment-244955393

_It would also be useful to be able to get a "snapshot" of what allocations are outstanding. Ideally we would support a "tracking" mode where we keep track of all accounts (including e.g. caller's file:line where it was created). The tracking mode could be enabled per-monitor by the higher layer (where it may depend on a flag/env var). It should be trivial to identify what account leaked on a failed unit test by just re-running it with that flag._

Such tracking code should ensure that there is no measurable overhead when tracking is disabled.

**Comment by jordanlewis** [comment]
Folding into #23154
