### ISSUE TITLE
build: use a checked-in file to determine binary version instead of git tags

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#91306]
**Describe the problem**

Currently, the binary version is set during build time and determined using `git describe --tags` [1][2][3]. Changing the binary version is done by tagging master and consequently 1) without any corresponding PR and 2) without running our test suite. This means tagging master can have the undesired consequence of breaking tests on master (e.g., version upgrade tests, that now start running new migrations), which is very disruptive.

Ideally, we want these updates to happen by changing a file that is checked in, so that any test failures are caught before the change is merged in the PR that updates the version file.

**Roachtest**

`roachtest` also independently looks at git tags [4]. It should be reading from the same checked-in version file.

**Related issues**

* #75287: missing tags can also lead to wrong binary versions being reported in telemetry. Not relying on git tags would fix that.

[1] https://github.com/cockroachdb/cockroach/blob/master/pkg/build/BUILD.bazel#L21
[2] https://github.com/cockroachdb/cockroach/blob/master/build/bazelutil/stamp.sh#L47
[3] https://github.com/cockroachdb/cockroach/blob/master/pkg/build/info.go#L42
[4] https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/test_registry.go#L202

Jira issue: CRDB-21197

**Comment by rickystewart** [comment]
I agree not using `git tag`s for this would be preferable. And having a source of truth that is easily parseable by any tool and doesn't require us to compile a Go package would be ideal.

**Comment by renatolabs** [comment]
> Would it suffice to use `binaryVersion` [1] as the source of truth in `roachtest`?

That sort of works, as it would require a PR to change the version. But the PR itself would be somewhat unrelated, i.e., the one that introduces the first migration after a release cut.

IMO, one advantage of having a separate source of truth for this is that it can be part of the release process/runbook and changed in the same PR that adds the predecessor version fixtures.

**Comment by srosenberg** [comment]
Then, it sounds like `version.txt` or `version.json` would be ideal. We could modify the roachtest which creates the new fixture [1] to also bump the version (in the same PR). 

[1] https://github.com/cockroachdb/cockroach/blob/c57b340ef74e6e4d4c64fb9e318a690518d49eed/pkg/cmd/roachtest/tests/fixtures.go#L54

**Comment by dt** [comment]
nit: probably want to make this "release-series.txt" or something like that, not "version.txt", since I believe its contents will be "23.1", not be "23.1.4" -- we tag a SHA as a specific versions like the latter after it already exists, including this proposed file. "version.txt" makes it sound like it'd be the actual version which seems like it'd be confusing.

**Comment by dt** [comment]
> But the PR itself would be somewhat unrelated, i.e., the one that introduces the first migration after a release cut.

We already do this in the "V23_1Start" version mint which follows the branch cut (it is the second of the three commits that should be in the mint PR to master after we cut the brach, e.g. https://github.com/cockroachdb/cockroach/pull/90066)

**Comment by renatolabs** [comment]
@dt coming back to this issue after a few months, so forgive me if I forget some of the details. Could you explain further why we would only want the "release series" ("23.1") instead of the full version ("23.1.0") in context of the file we're talking about here? There are a couple of places currently that rely on `build.BinaryVersion()` (which includes the patch version); not sure what those would use if we didn't have the patch number.

> we tag a SHA as a specific versions like the latter after it already exists

Potentially related, but I'm also not sure what you meant here: what does it mean for the "version already exist" by the time the SHA is tagged?
