### ISSUE TITLE
The gradients on the website looks blocky on 24-bit color monitor.

### ISSUE THREAD

**Issue by alexey-milovidov** [cockroachdb/cockroach#91316]
**Describe the problem**

See the screenshot:
![Screenshot_20221104_215233](https://user-images.githubusercontent.com/18581488/200073362-21260f70-38d9-447e-a066-b34e185658e4.png)

The gradient is uneven, looks dirty.

My monitor is LG 32UN880. The browser is Chromium or Firefox (does not matter).
24 bits are simply not enough to show these gradients properly.

Jira issue: CRDB-21199

**Comment by alexey-milovidov** [comment]
The background picture on the pricing page is also very poorly compressed:

![Screenshot_20221104_221002](https://user-images.githubusercontent.com/18581488/200075352-6a780b91-7691-49d4-9ad8-9f95ed3ee020.png)

**Comment by jordanlewis** [comment]
Thanks for the feedback. GitHub isn't an appropriate place for this, but I've forwarded it along to the relevant people.
