### ISSUE TITLE
store nothing in database,but cost 10GB longhorn PersistentVolume space

### ISSUE THREAD

**Issue by Bmixo** [cockroachdb/cockroach#91335]
**Describe the problem**
i have a new installed cockroach database,and i install it last night,but i  store nothing in database,when i check longhorn  dashboard today,i found cockroach  database cost about 10GB longhorn PersistentVolume space

![1667626865169](https://user-images.githubusercontent.com/25509024/200104481-6d9c1136-1d93-4311-90a3-a7f01512de5a.png)

![1667626722080](https://user-images.githubusercontent.com/25509024/200104266-161b00aa-709e-4447-9277-4af1206803a0.png)

**What I Hope:**
i hope cockroach database could work well like postgres, disk space is consumed only after I insert data.

**Environment:**
 - cockroachdb/cockroach:v21.1.21
 - Server OS: Linux xxx 5.10.0-0.deb10.17-amd64 
 -  Debian 5.10.136-1~deb10u3 (2022-09-06) x86_64 GNU/Linux
 - rancher longhorn v1.3.0

Jira issue: CRDB-21207

**Comment by andreimatei** [comment]
The bulk of this space is probably taken by CRDB internal timeseries - the data powering the dashboards. We're working on improving our docs to quantify, explain and give more guidance around this.
You can control the amount of timeseries data - see 
https://www.cockroachlabs.com/docs/stable/operational-faqs.html#reduce-the-interval-for-time-series-storage

Closing, but feel free to reopen if there's more to talk about.
