### ISSUE TITLE
cli: printing env vars on startup may leak sensitive information

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#9136]
As of recently, we output lines like these:

> 
using local environment variables: COCKROACH_CONSISTENCY_CHECK_PANIC_ON_FAILURE = true # /go/src/github.com/cockroachdb/cockroach/server/context.go COCKROACH_LIGHTSTEP_TOKEN = deadbeefdeadbeefdeadbeef # /go/src/github.com/cockroachdb/cockroach/util/tracing/tracer.go COCKROACH_MEMPROF_INTERVAL = 10s # /go/src/github.com/cockroachdb/cockroach/cli/start.go

I redacted the `COCKROACH_LIGHTSTEP_TOKEN` manually in the above message, but I shouldn't have to do that. We shouldn't print out these potentially sensible values; it should be enough to log the variable names.

**Comment by tamird** [comment]
s/sensible/sensitive/?

**Comment by a-robinson** [comment]
Ah, my bad. I'll clean this up.
