### ISSUE TITLE
storage: queues need more trace points

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#9139]
> 0s
> processing replica store=2:2 range=436 [/Table/55/1/1100581902804667617/"0840d227-ebf8-4b77-ad93-7f6a6a35ae1d"/9190907-/Table/55/1/1109586896742279322/"0840d227-ebf8-4b77-ad93-7f6a6a35ae1d"/8257155)
> 27.2s
> done

There is little no information on where those 27s were spent. The other queues have similar deficiencies.

**Comment by spencerkimball** [comment]
Closing this for lack of sufficient follow up to qualify as a worthwhile fix.
