### ISSUE TITLE
ui: report progress on a schema change

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#9142]
A schema change over a table consisting of millions of rows takes many minutes to complete. I expect a change over a very large table (> 100M ) rows could easily take more than hour. We need some way to report the progress on a schema change in the UI. Additionally the events that get reported in the UI are not very useful:

`Unknown event type: finish_schema_change`

The above event should at least report the SQL used for the schema change.

**Comment by knz** [comment]
Will need help from #7554 probably.

**Comment by kuanluo** [comment]
@mrtracy probably fixed it already?

**Comment by kuanluo** [comment]
#### Design
![image](https://cloud.githubusercontent.com/assets/1486483/21111639/71553a54-c070-11e6-9aab-0e04cd78ae97.png)

**Comment by spencerkimball** [comment]
@mrtracy this is slated for 1.0, correct?

**Comment by vivekmenezes** [comment]
We agreed to allow schema change status updates via sql but not through the UI for 1.0. @jordanlewis working on that.

**Comment by jordanlewis** [comment]
This is done via `SHOW JOBS`.
