### ISSUE TITLE
acceptance: `TestComposeGSS` broken

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#91420]
```
        �W: The repository 'http://apt.postgresql.org/pub/repos/apt stretch-pgdg Release' does not have a Release file.
        E: Failed to fetch http://apt.postgresql.org/pub/repos/apt/dists/stretch-pgdg/11/binary-amd64/Packages  404  Not Found [IP: 147.75.85.69 80]
        E: Some index files failed to download. They have been ignored, or old ones used instead.
```

[example](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/7368758?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildDeploymentsSection=true&expandBuildTestsSection=true)
[test history](https://teamcity.cockroachdb.com/test/-8211341273700807426?currentProjectId=Cockroach_Ci_Tests&expandTestHistoryChartSection=true)

Jira issue: CRDB-21254

**Comment by ecwall** [comment]
It looks like it moved to `https://apt-archive.postgresql.org/pub/repos/apt/dists/stretch-pgdg/11/binary-amd64/Packages`

https://wiki.postgresql.org/wiki/Apt links to https://www.postgresql.org/message-id/Y2kmqL%2BpCuSZiQBV%40msg.df7cb.de
<img width="537" alt="image" src="https://user-images.githubusercontent.com/8524448/200443638-037dc638-e46a-4de0-87e5-657f10d3670a.png">

**Comment by erikgrinaker** [comment]
This is currently blocking backports to release branches, e.g. #91385, which require Bazel CI to pass.

**Comment by erikgrinaker** [comment]
For visibility, the test was skipped in #91421. Backports in progress:

* #91454
* #91455
* #91456

**Comment by rickystewart** [comment]
Thanks for taking care of those @erikgrinaker.

**Comment by erikgrinaker** [comment]
That was all @postamar!

**Comment by postamar** [comment]
I can't remember how or why, but I noticed these hadn't been merged so I just went ahead and did it. Perhaps a sane default for backports would be to auto-merge as soon as all the green check-marks appear, not sure if this is doable in github. If it helps I can advocate for such a change.

**Comment by adityamaru** [comment]
I’m trying to merge a backport that netflix needs to 21.2 and keep running into a TestComposeGSS failure - https://teamcity.cockroachdb.com/viewLog.html?buildId=7808185&buildTypeId=Cockroach_UnitTests. They build their own binary and so want the fix merged even though we don’t have anymore scheduled releases. It looks like the skips/fixes tracked here don’t reach all the way back to 21.2. Unless someone objects I'm thinking of skipping the test on 21.2 as part of my backport.
