### ISSUE TITLE
ui: use relative instead of absolute paths for recently introduced DB routes

### ISSUE THREAD

**Issue by dhartunian** [cockroachdb/cockroach#91429]
**Describe the problem**

When running the DB Console behind a proxy that has a different base URL, it's necessary for existing XHR requests to be made relative to that base path that's being proxied to the cluster (say: `http://example.com/my-cluster/prod-cluster/...`). This ensures that all requests in addition to the initial asset requests can complete successfully.

It appears that the `uiconfig` and `api/v2` routes were configured as **absolute** instead of relative in the code, which breaks them when behind a proxy that changes the base URL.

**To Reproduce**
Run DB Console and CRDB behind an HTTP proxy with a base URL different from `/`.

Observe: 
<img width="547" alt="Screen Shot 2022-11-07 at 2 41 30 PM" src="https://user-images.githubusercontent.com/986307/200399868-037d6331-b586-4d6f-a622-594b04c782fb.png">
and
<img width="683" alt="Screen Shot 2022-11-07 at 2 42 06 PM" src="https://user-images.githubusercontent.com/986307/200400005-a437c00e-c4b8-466a-a2a4-685d6875615a.png">

which tells us that `/uiconfig` loaded incorrectly
and 

<img width="729" alt="Screen Shot 2022-11-07 at 2 41 48 PM" src="https://user-images.githubusercontent.com/986307/200399913-0ad36ab3-74c3-4e5f-94d1-b268311e1f1e.png">
which tells us that SQL-over-HTTP endpoint requests cannot be loaded.

**Expected behavior**
DB Console runs as expected and pages load successfully without errors.

**Environment:**
 - CockroachDB version: 22.2.0-beta5
 - Client app: DB Console

Jira issue: CRDB-21257

gz#16498

gz#16586

gz#17984

Epic CC-25593

**Comment by celiala** [comment]
Based on linked PRs and label actions, it sounds like this should block `v22.2.1`, but not `v22.2.0`: 

Removing `GA-blocker` and adding 	`release-blocker` to denote this (but holler and/or change as needed if I've misunderstood :), thanks!)

**Comment by kmcrawford** [comment]
I'm seeing this issue on `V22.2.8` 

<img width="193" alt="image" src="https://user-images.githubusercontent.com/40531/233720006-ce8c1977-839d-4916-938c-3feacb0f26c5.png">

**Comment by rajavarapusaiprasanth-hpe** [comment]
@celiala / @dhartunian 

Any update on this issue? because facing the 404 error because of absolute path in /api/v2/sql and /uiconfig. This is a bug. Can we take this on priority?
