### ISSUE TITLE
kv: Allow for permissioned tenants to change host cluster settings

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#91504]
Implement the KV-side of the `SettingsChange` API described in the [Tenant Capabilities](https://github.com/knz/cockroach/blob/20220810-rfc-tenant-capabilities/docs/RFCS/20220810_tenant_capabilities.md) RFC

Epic: CRDB-18503

Jira issue: CRDB-21293

**Comment by knz** [comment]
we've decided we're not doing this in 23.1
