### ISSUE TITLE
SQL Exp: Allow for permissioned tenants to change host cluster settings

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#91505]
Implement the SQL-side of the `SettingsChange` API described in the [Tenant Capabilities](https://github.com/knz/cockroach/blob/20220810-rfc-tenant-capabilities/docs/RFCS/20220810_tenant_capabilities.md) RFC

Epic: CRDB-19504

Jira issue: CRDB-21294

**Comment by knz** [comment]
we've decided that we won't do this in 23.1.
