### ISSUE TITLE
Confusing error when trying to quit a secure node without passing cert/key flags

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#9153]
```
$ grep -F '[config]' cockroach-data/logs/cockroach.INFO
I160906 15:53:34.193658 1 util/log/clog.go:1019  [config] file created at: 2016/09/06 15:53:34
I160906 15:53:34.193658 1 util/log/clog.go:1019  [config] running on machine: JESSEs-MacBook-Pro
I160906 15:53:34.193658 1 util/log/clog.go:1019  [config] binary: CockroachDB beta-20160829-180-g186e4e3 (darwin amd64, built 2016/09/06 17:40:11, go1.7)
I160906 15:53:34.193658 1 util/log/clog.go:1019  [config] arguments: [cockroach start --host=localhost --ca-cert=certs/ca.cert --cert=certs/root.cert --key=certs/root.key]
```

When you try to stop a node on a secure node, running `quit` without the `ca-cert`, `cert`, and `key` flags returns a hard shutdown error:

```
$ cockroach quit --host=localhost
graceful shutdown failed, proceeding with hard shutdown: rpc error: code = 13 desc = transport is closing
```

@tamird says:
> The hard shutdown error is really the server saying "you're not talking TLS, go away", but the CLI is misinterpreting that and printing a nonsense error.

It'd help users if we could return an error about the missing cert flags.

**Comment by tschottdorf** [comment]
I would like to bump this - we should had someone on the forum confused by this, and I think all of us have been sidetracked by this at some point.
