### ISSUE TITLE
kv: implement SHARED lock strength for unreplicated locks 

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#91545]
The `lockTable` currently only supports the exclusive lock strength, but was designed to support varying degrees of lock strengths. Specifically, it was designed to support both `SHARED` and `UPGRADE` (tracked separately in https://github.com/cockroachdb/cockroach/issues/49684) locking strength as well. 

https://github.com/cockroachdb/cockroach/blob/82b251992cf5a167bdf0e04c011e46dda43b8ec9/pkg/kv/kvserver/concurrency/lock/locking.proto#L40-L50

**Additional context**

Today SQL accepts syntax of the form `SELECT ... FOR SHARE` but does not lock any of the rows returned. It should be easy enough to correctly use the `SHARED` locking strength once the `lockTable` supports it.

Jira issue: CRDB-21312

Epic CRDB-26544

**Comment by arulajmani** [comment]
Sub-issues that are directly (or closely related). These are listed roughly in the order in which we would want to get to them, though this might change in minor ways once we get to the implementing things. Ofcourse, a few of the issues can be tackled in parallel.  

- [ ] https://github.com/cockroachdb/cockroach/issues/102008
- [ ] https://github.com/cockroachdb/cockroach/issues/102269
- [ ] https://github.com/cockroachdb/cockroach/issues/102210
- [ ] https://github.com/cockroachdb/cockroach/issues/102264
- [ ] https://github.com/cockroachdb/cockroach/issues/102270
- [ ] https://github.com/cockroachdb/cockroach/issues/102272
- [ ] https://github.com/cockroachdb/cockroach/issues/102275
- [ ] https://github.com/cockroachdb/cockroach/issues/100173

**Comment by nvanbenschoten** [comment]
I took a look at the testing that we have above the KV API which uses Exclusive locking. Besides kvnemesis, there's less than I had thought outside of the `concurrency` package. Still, here's a list of tests that we'll want to extend or copy for shared locks:
* [ ] `TestEvaluateBatch` (and extend verifyAcquiredLocks to check lock strength)
* [ ] `TestDB_GetForUpdate`
* [ ] `TestDB_ScanForUpdate`
* [ ] `TestDB_ReverseScanForUpdate`
* [ ] `TestReplicaServersideRefreshes`
* [ ] `TestTxnCoordSenderRetries`

In doing so, we'll probably end up wanting to add `{DB,Txn,Batch}.{Get,Scan,ReverseScan}ForShare` methods. We'll need those for kvnemesis as well.
