### ISSUE TITLE
Add idle ("inter-statement") latency to internal telemetry data

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#91550]
This issue tracks adding idle latency (inter-statement latency) to our internal telemetry data.

Related issue: https://github.com/cockroachdb/cockroach/issues/86667

Jira issue: CRDB-21314

**Comment by j82w** [comment]
@kevin-v-ngo is this done with the changes here where it is added to the sampled query event or are there are there other events? https://github.com/cockroachdb/cockroach/pull/102820

**Comment by j82w** [comment]
Done: https://github.com/cockroachdb/cockroach/pull/102820
