### ISSUE TITLE
sql: create plpgsql grammar and unimplemented errors

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#91569]
As we explore support for [plpgsql](https://github.com/postgres/postgres/tree/master/src/pl/plpgsql), we should add a [grammar file](https://github.com/postgres/postgres/blob/master/src/pl/plpgsql/src/pl_gram.y) and unimplemented errors for the corresponding features. With grammar and unimplemented support, we can better understand the implementation sequencing (and it will be necessary for implementation in the future anyway)

Much of the initial work is completed as part of https://github.com/cockroachdb/cockroach/pull/91606 so we should follow up from there. See [this Slack](https://cockroachlabs.slack.com/archives/C036BQTUJ9Z/p1671220028903539) for more details.

Jira issue: CRDB-21320

Epic CRDB-799

**Comment by ajwerner** [comment]
@chengxiong-ruan had a prototype of the grammar from a breather week somewhere.

**Comment by rafiss** [comment]
https://github.com/cockroachdb/cockroach/issues/96720 is a simpler way that would let us start seeing plpgsql function bodies in our telemetry data, without implementing the plpgsql grammar. I don't think there's too much of an added advantage to making unimplemented errors that are specific to plpgsql. But we should leave this issue open to track implementing the grammar.

**Comment by rimadeodhar** [comment]
Hey @rafiss, @awoods187: Just wanted to confirm that the scope for this is to only add the grammar without the actual functionality? cc @e-mbrown

**Comment by awoods187** [comment]
Correct--the main reason to accelerate this work (and backport it to 22.2.x) is that it will let us have more specific unimplemented errors for plpgsql so that we can better prioritize what to build. We don't know what type of attempt at plpgsql was done and cant do automatic comparisons on missing feature by frequency.
