### ISSUE TITLE
stability: diagnose increased GC pauses

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#9156]
beta/gamma/rho are all seeing a large (5x) increase in GC counts and pause times, reaching ~3ms per second per node.

This was when going from sha 65774e9 to sha 186e4e3
One consequential change for memory utilization is disabling grpc tracing.

Gamma graphs for a single node around the time of the upgrade:
http://monitoring.gce.cockroachdb.com:3000/dashboard/snapshot/dIdGgCOVm9h7dHYpLPRdRMGX85cKVknD

Mem stats at 1m intervals:
```
I160906 20:55:57.953473 192 server/status/runtime.go:207  runtime stats: 7.2 GiB RSS, 165 goroutines, 118 MiB/795 MiB/1.1 GiB GO alloc/idle/total, 5.0 GiB/6.2 GiB CGO alloc/total, 39413.55cgo/sec, 1.48/0.35 %(u/s)time, 0.01 %gc (6x)

I160906 20:56:57.952724 192 server/status/runtime.go:207  runtime stats: 7.3 GiB RSS, 170 goroutines, 223 MiB/696 MiB/1.1 GiB GO alloc/idle/total, 5.0 GiB/6.3 GiB CGO alloc/total, 50216.86cgo/sec, 1.33/0.34 %(u/s)time, 0.00 %gc (7x)
```

Heaps:
[memprof.2016-09-06T20_55_56.904.txt](https://github.com/cockroachdb/cockroach/files/457829/memprof.2016-09-06T20_55_56.904.txt)
[memprof.2016-09-06T20_56_56.893.txt](https://github.com/cockroachdb/cockroach/files/457828/memprof.2016-09-06T20_56_56.893.txt)

Heap diffs for alloc-space and alloc-objects:
```
$ go tool pprof -pdf -alloc_space -base memprof.2016-09-06T20_55_56.904.txt cockroach memprof.2016-09-06T20_56_56.893.txt > alloc_space.pdf
$ go tool pprof -pdf -alloc_objects -base memprof.2016-09-06T20_55_56.904.txt cockroach memprof.2016-09-06T20_56_56.893.txt > alloc_objects.pdf
```

[alloc_objects.pdf](https://github.com/cockroachdb/cockroach/files/457831/alloc_objects.pdf)
[alloc_space.pdf](https://github.com/cockroachdb/cockroach/files/457830/alloc_space.pdf)

**Comment by tschottdorf** [comment]
Ran some alloc benchmarks just to make sure we didn't regress from ~a week ago (613e0865daf0bed9404170caec18db57362112e7). Nothing shows up.

```
name                    old time/op    new time/op    delta
Select1_Cockroach-32       298µs ± 0%     305µs ± 0%   ~             (p=1.000 n=1+1)
Insert1_Cockroach-32      2.28ms ± 0%    2.36ms ± 0%   ~             (p=1.000 n=1+1)
Insert10_Cockroach-32     3.58ms ± 0%    3.50ms ± 0%   ~             (p=1.000 n=1+1)
Insert100_Cockroach-32    12.2ms ± 0%    12.7ms ± 0%   ~             (p=1.000 n=1+1)
Update1_Cockroach-32      3.93ms ± 0%    3.87ms ± 0%   ~             (p=1.000 n=1+1)
Update10_Cockroach-32     6.42ms ± 0%    6.39ms ± 0%   ~             (p=1.000 n=1+1)
Update100_Cockroach-32    27.7ms ± 0%    25.8ms ± 0%   ~             (p=1.000 n=1+1)

name                    old alloc/op   new alloc/op   delta
Select1_Cockroach-32      4.02kB ± 0%    4.02kB ± 0%   ~     (all samples are equal)
Insert1_Cockroach-32      33.1kB ± 0%    32.9kB ± 0%   ~             (p=1.000 n=1+1)
Insert10_Cockroach-32     79.7kB ± 0%    79.6kB ± 0%   ~             (p=1.000 n=1+1)
Insert100_Cockroach-32     520kB ± 0%     519kB ± 0%   ~             (p=1.000 n=1+1)
Update1_Cockroach-32      59.3kB ± 0%    59.2kB ± 0%   ~             (p=1.000 n=1+1)
Update10_Cockroach-32      133kB ± 0%     133kB ± 0%   ~             (p=1.000 n=1+1)
Update100_Cockroach-32     842kB ± 0%     842kB ± 0%   ~             (p=1.000 n=1+1)

name                    old allocs/op  new allocs/op  delta
Select1_Cockroach-32        58.0 ± 0%      58.0 ± 0%   ~     (all samples are equal)
Insert1_Cockroach-32         327 ± 0%       324 ± 0%   ~             (p=1.000 n=1+1)
Insert10_Cockroach-32        531 ± 0%       531 ± 0%   ~     (all samples are equal)
Insert100_Cockroach-32     2.42k ± 0%     2.42k ± 0%   ~             (p=1.000 n=1+1)
Update1_Cockroach-32         589 ± 0%       588 ± 0%   ~             (p=1.000 n=1+1)
Update10_Cockroach-32        919 ± 0%       919 ± 0%   ~     (all samples are equal)
Update100_Cockroach-32     3.88k ± 0%     3.88k ± 0%   ~     (all samples are equal)
```

**Comment by tschottdorf** [comment]
We should play with the `GODEBUG` variable: https://golang.org/pkg/runtime/#hdr-Environment_Variables

**Comment by bdarnell** [comment]
I think this is a direct consequence of the reduced memory usage. Go runs garbage collection when it has allocated an amount of memory equal to the live bytes remaining after the last collection. This means that previously, we were running GC after every 4GB of allocations; now we're running it after every 300MB. Since allocations haven't changed and it's still only 0.3% of our CPU time, I don't think there's anything to worry about here.

**Comment by tschottdorf** [comment]
SGTM, so nothing to do here.
