### ISSUE TITLE
changefeedccl: add tests+docs for multi-cluster kafka sinks

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#91598]
We haven't implemented the general case of failover/backup/dlq sinks yet, but [you can get similar behavior](https://cockroachdb.slack.com/archives/CP4D9LD5F/p1666702703924009) with the Kafka sink just by including brokers from multiple clusters in the connection string, and using the default `RequiredAcks: "one"` config. I don't think this is defined behavior for Sarama/Kafka, though, it just happens to work, so we should consider adding integration tests for this behavior so that we can ensure we don't break it in a future Sarama update, at least until we have a more general solution ourselves.

Thanks to Celac Vasile for the idea and investigation.

Jira issue: CRDB-21342

**Comment by miretskiy** [comment]
I'm closing this issue for few reasons:
  * It's not really supported by sarama
  * It's definitely not supported by us (one has to wonder how well/badly this will behave)
  * It's more work that we will likely not prioritize.
@HonoreDB / @amruss -- feel free to reopen.
