### ISSUE TITLE
cdc: highwater timestamp can be synthetic, is that okay?

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#91607]
An error was [traced recently](https://github.com/cockroachlabs/support/issues/1885) to a changefeed's highwater timestamp having been forwarded to a synthetic value. This is surprising to me. It's likely due to running on a global table.

Independently of any fix for the error in question (which will probably be a fix in the protected timestamp subsystem), we need to validate that changefeeds behave correctly when they get a synthetic closed timestamp or event timestamp. e.g.

* If the changefeed's high water timestamp is in the future, can anything break when the job is paused and resumed?
* In particular, what happens if you ALTER a changefeed in that state?
* Can synthetic timestamps interact weirdly with the end_time option?
* Do changefeeds configured to emit the timestamp of an event handle synthetic timestamps correctly?
* Do changefeed expressions that use the mvcc/transaction timestamp of an event handle synthetic timestamps correctly?

Jira issue: CRDB-21346

**Comment by miretskiy** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/91920
