### ISSUE TITLE
benchmark: investigate no change in some kv workloads once soft slot granting was enabled

### ISSUE THREAD

**Issue by bananabrick** [cockroachdb/cockroach#91617]
Soft slot granting was enabled on the master branch of Cockroach on July 7: https://github.com/cockroachdb/cockroach/pull/84006. In theory, we should see the ops/sec in some of the kv workloads move up, along with the CPU and disk throughput. This doesn't seem to be the case.

It's worth investigating the cause for no change in the roachperf benchmarks. Some possibilities include:
1. lsm not inverted in the workloads, so more compactions don't help.
2. Not enough CPU or IO available for more compactions to help.

Jira issue: CRDB-21353

**Comment by sumeerbhola** [comment]
soft slots are no more.
