### ISSUE TITLE
"cockroach sql" SNI doesn't work with sslmode=require

### ISSUE THREAD

**Issue by kernfeld-cockroach** [cockroachdb/cockroach#91671]
**Describe the problem**

In the internal SNI bug bash for serverless, users of `cockroach sql` found that SNI connections to serverless worked correctly with `sslmode` set to `require` but not `verify-full`.

**To Reproduce**

1. Switch to an organization with the SNI feature flag enabled (e.g. `CRL CC Developer`)
2. Create a new serverless cluster
3. Get the connection string for this cluster from the web UI
4. Modify the connection string `sslmode` to `require` instead of `verify-full`
5. Try to connect to the cluster with `cockroach sql`. There will be an error message.

**Expected behavior**

Successfully connect to a SQL shell.

**Additional context**

We observed this problem in pq, pgx and GORM.

Jira issue: CRDB-21378

Epic CC-5618

**Comment by rafiss** [comment]
This has been fixed in the 23.1 of `cockroach sql`
