### ISSUE TITLE
gceworker: auto-shutdown doesn't work

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#9170]
We switched the used image to ubuntu-xenial yesterday and the auto-shutdown snippet doesn't work any more. The reason is that we used to detect a pending shutdown via `pgrep -flx /lib/systemd/systemd-shutdownd`, but ubuntu doesn't have that process running.

It wasn't immediately obvious to me how to detect a scheduled shutdown in that setting, despite a bit of googling.

**Comment by a-robinson** [comment]
I assume you looked into using a [shutdown script](https://cloud.google.com/compute/docs/shutdownscript)?

**Comment by tschottdorf** [comment]
No, because the main point is scheduling and aborting shutdowns, not running commands when the shutdown happens. I just need a way to find out whether there is a shutdown scheduled for the future, which must be possible but appears not to be something many people on the internet have asked for.

**Comment by dt** [comment]
Maybe a stupid question, but why do we need to know if one is scheduled?

**Comment by tschottdorf** [comment]
Because if you do `shutdown -h +10` and then 5 minutes later you do `shutdown -h +10` again, your first pending shutdown will be cancelled implicitly.

**Comment by dt** [comment]
Huh, ,y simplistic script that was on the wiki just 1) checked for logins, then if there were none 2) did a `sleep 600` then 3) re-checked for logins and shut down if still none (plus the manual flag to disable it didn't exist)... sure, after you logout you'll accumulate a couple of these before the first one wakes up and shuts down, but `sleep` isn't exactly expensive to run. It also had the advantage of not locking you out before shutdown.

**Comment by tschottdorf** [comment]
Maybe it's time to go back to that. I tried to do this "cleaner" but it doesn't seem to have paid off. I'm open to any solution to the problem

**Comment by bdarnell** [comment]
> Because if you do shutdown -h +10 and then 5 minutes later you do shutdown -h +10 again, your first pending shutdown will be cancelled implicitly.

That sounds like a feature you could take advantage of. Instead of scheduling a shutdown when there are no active users, you schedule a shutdown when there *are* users, and do nothing when the machine is idle. As long as users are present the shutdown will keep getting pushed into the future.

**Comment by tschottdorf** [comment]
Smart idea.

**Comment by tamird** [comment]
It was Ben's.

**Comment by dt** [comment]
Might be tricky to cancel one of those though if the `.active` flag appears though?

**Comment by tschottdorf** [comment]
#9203 seems to do the right thing - it'll blindly cancel when there's the `.active` flag.
