### ISSUE TITLE
Add human-readable query identifiers in crdb_internal.statement_statistics and DB Console Statements page

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/cockroach#91763]
**Is your feature request related to a problem? Please describe.**
In the DB Console SQL Activity->Statements page, there is no unique query identifier in the initial page.  When you click into a query, you can see an identifier in the URL, such as http://127.0.0.1:26258/#/statement/true/4705782015019656142?appNames=
 
In this case `4705782015019656142` is the identifier. When querying `crdb_internal.statement_statistics` at the main table level there is no identifier that corresponds to `4705782015019656142`.  The only way to search for a query is using the `metadata ->> ‘query’` clause like this:

```
where metadata ->> 'query' like '%SELECT city, id FROM vehicles WHERE city = $1%'
```

Sometimes if the full query text as shown in the console is entered, the filter will not find the given query string.  You have to use some `LIKE` condition to find the query string. There are columns `fingerprint_id` and `transaction_fingerprint_id` in `crdb_internal.statement_statistics` but they are `BYTE` values that are not human-readable.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

cc: @kevin-v-ngo 

Jira issue: CRDB-21417

**Comment by maryliag** [comment]
This is already possible today. We display the fingerprint id on the overview statement page for that purpose, it's one of the columns (hidden by default). You can select to show the column here:
<img width="313" alt="Screen Shot 2022-11-11 at 5 27 59 PM" src="https://user-images.githubusercontent.com/1017486/201439646-6e90563b-5ab4-4fb9-bc74-f07108398e60.png">

then copy the value from the column:
<img width="1105" alt="Screen Shot 2022-11-11 at 5 28 08 PM" src="https://user-images.githubusercontent.com/1017486/201439664-ba981566-d6f0-47f5-b1d8-50adedf3c25b.png">

then on cli you can look for that fingerprint adding the `\x` at the start of the value like this:
`select * from crdb_internal.statement_statistics where fingerprint_id='\xe56448b12fbe7990';`

or encoding the fingerprint column like this:
`select * from crdb_internal.statement_statistics where encode(fingerprint_id, 'hex')='e56448b12fbe7990';`


Does that work for you @florence-crl ?

**Comment by florence-crl** [comment]
Thanks @maryliag for the above info and screenshots!

It is not obvious that there are additional column options in that multi-select pop-up. Only because you gave the screenshot above, did I know to scroll down and look for the **Statement Fingerprint ID**

Initial view of pop-up where scroll bar is not visible. Is there a way to make the scroll bar visible?
<img width="416" alt="Screen Shot 2022-11-11 at 5 42 52 PM" src="https://user-images.githubusercontent.com/58752716/201441197-145fda3f-5a41-4843-8ffc-a2ad92f48fe0.png">

After scrolling down to show the additional column options:
<img width="401" alt="Screen Shot 2022-11-11 at 5 45 43 PM" src="https://user-images.githubusercontent.com/58752716/201441270-6dd5436f-e1f1-4eac-b517-06107bd12ac2.png">

Also [the docs on the Statements table](https://www.cockroachlabs.com/docs/cockroachcloud/statements-page.html#statements-table) does not mention the hidden columns, so I did not think of looking for it. I will open a docs issue.

**Comment by maryliag** [comment]
Unfortunately, the visibility of a scrollbar is not something we can't control on our side, is defined by browser/user. What I can do is increase that size or stop at a point that is mid one of the labels so it indicates that there is more to it.

For the docs, looks like something got missed, because there was an issue for the update on the docs, but shows as closed now, but I don't know what happened: https://github.com/cockroachdb/docs/issues/14960
I can see you created an issue for the docs team, and added more context there, so I'll add the PR there for reference.

**Comment by florence-crl** [comment]
A user noticed that the Statement Details page has an ID in the URL. In the example URL below, the id is `17122190109225917933`

http://127.0.0.1:26258/#/statement/true/17122190109225917933?appNames=

Why is this id different from the Fingerprint ID on the Statements main page?
Also, why is the Fingerprint ID not displayed on the Statement Details page?

**Comment by maryliag** [comment]
the URL uses the fingerprint id in int64 format and we didn’t show fingerprint on the ui anywhere, so the value didn’t really matter at that point. Now with more people using that value, might be worth changing the url format. That will require a little more work, so can you open a new issue with that request specifically.
I can add the fingerprint in hex format as part of this issue on the details page.
