### ISSUE TITLE
multitenant: allow CONFIGURE ZONE tenant permission config

### ISSUE THREAD

**Issue by ecwall** [cockroachdb/cockroach#91761]
In the UA, the system tenant and secondary tenants will have permissions configurable via the `system.tenants.info` column (https://github.com/knz/cockroach/blob/20220810-rfc-tenant-capabilities/docs/RFCS/20220810_tenant_capabilities.md).

Serverless clients' secondary tenants will be blocked from setting zone configs directly. They can still indirectly set them using the multi-region abstractions, but no direct modification will be allowed, to reduce the likelihood of DoS attacks and elevated costs.

Self-hosted clients will be able to configure secondary tenants according to the linked RFC.

---

Proposal for moving the secondary tenant set zone config permission check from the SQL layer to the KV layer based on our multitenant meeting:

Currently `CONFIGURE ZONE` checks `Codec.ForSystemTenant()` in the SQL layer before writing zone config to `system.zones`. We are planning on moving this check to a similar check in the KV layer in the process that reads from `system.zones` and applies the config.

The goal is to eventually replace the `Codec.ForSystemTenant()` check with a tenant permissions check. Tenant permissions will be grantable and revokable by authorized tenants.

Similar work for `SPLIT AT`: https://github.com/cockroachdb/cockroach/pull/90391/

Meeting notes:
- we let secondary tenant write any and all of what they wish to system.zones for now
- we decide in the reconciler and/or in the span config reader in KV, therefore async, whether to accept a problematic zone config
- we will decide later as to which additional check we're going to add in the front-end of CONFIGURE ZONE to provide synchronous feedback, if at all

Slack thread: https://cockroachlabs.slack.com/archives/C02HWA24541/p1668187391963069

Jira issue: CRDB-21416
Epic [CRDB-23559](https://cockroachlabs.atlassian.net/browse/CRDB-23559)

**Comment by ajwerner** [comment]
> We are planning on moving this check to a similar check in the KV layer in the process that reads from system.zones and applies the config.

I don't follow this part. Maybe you mean that you plan to move the check into the kv layer on the code that reads from and writes to `system.span_configurations`?

**Comment by ajwerner** [comment]
> It is my understanding that this is read async then applied (written to system.span_configurations?).

Correct. Note that `system.zones` is in that tenant's keyspace and `system.span_configurations` is in the host keyspace and is interacted with via RPC.

**Comment by knz** [comment]
We have implemented most of the building blocks in 23.1. The remainder of the productionization work is tracked here CRDB-26686
