### ISSUE TITLE
db console: consider visually distinguishing successful vs failed executions of the same stmt

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#91788]
Consider highlighting the difference between successful and unsuccessful executions of the same stmt. E.g. these two rows on the SQL activity page correspond to the same query that has been issued concurrently many times with most executions hitting an error (due to overload). The top one corresponds to the successes and the bottom to the failures.
![Screen Shot 2022-11-11 at 6 19 44 PM](https://user-images.githubusercontent.com/5135385/201452046-3b242ec0-2bcf-410e-89b6-2b371230ad6c.png)
Note how on SQL Activity page itself we don't see the difference - to figure that out we need to click into both and then perform a careful inspection to see what's different (it's `Failed?` yes or no).

One idea might be highlighting the link to the failed stmt fingerprint as red rather than as the default color.

Jira issue: CRDB-21427

**Comment by maryliag** [comment]
cc @dongniwang

**Comment by maryliag** [comment]
We will combine all into the same line, so this issue will no longer be a priority
