### ISSUE TITLE
sql: calling Stop() on a `server.Server` does not block until all statements are finished executing

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#9181]
Discovered while investigating #9005.

Reproducible by running `make stressrace PKG=./sql TESTS=BackupRestoreBank` on https://github.com/paperstreet/cockroach/tree/repro_9181 until the race detector fires. The [deferred `stopper.Stop`](https://github.com/paperstreet/cockroach/blob/repro_9181/sql/backup_test.go#L300) has returned but a query that continues executing races with [resetting the table lease knob](https://github.com/paperstreet/cockroach/blob/repro_9181/sql/backup_test.go#L283).

**Comment by knz** [comment]
I think this issue was also preventing a server from shutting down with `cockroach quit`. @asubiotto isn't this what you addressed some time ago?

**Comment by asubiotto** [comment]
I think this issue can be closed. `Stop` does not drain the server. @knz, I'm not sure what you're referring to, `cockroach quit` drains the server before calling `Stop`.
