### ISSUE TITLE
server: tenantID field unnused in api_v2 code

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#91829]
Found in CI linter: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/7502335?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

```
------- Stdout: -------
=== RUN   TestLint/TestStaticCheck
    lint_test.go:1751:
        pkg/server/api_v2.go:103:2: field tenantID is unused (U1000)
    --- FAIL: TestLint/TestStaticCheck (955.08s)
```

Jira issue: CRDB-21447

**Comment by stevendanna** [comment]
Interesting question here is why doesn't the bazel build hit this as well?

**Comment by knz** [comment]
> Interesting question here is why doesn't the bazel build hit this as well?

good q. @renatolabs @srosenberg thoughts?

**Comment by renatolabs** [comment]
> > Interesting question here is why doesn't the bazel build hit this as well?
> 
> good q. @renatolabs @srosenberg thoughts?

I believe @rickystewart is better equipped to answer this one. I know that this was a documented issue (#76933), but I would have expected the `unused` lint (#76933) to catch instances like this.
