### ISSUE TITLE
workload/schemachange: enable inserts

### ISSUE THREAD

**Issue by fqazi** [cockroachdb/cockroach#91863]
We are hitting integer overflow errors with inserts enabled in the randomized schema changer workload, we need to root cause these errors before we can re-enable them in the workload. See https://github.com/cockroachdb/cockroach/issues/91859 for an example of the ones encountered.

This has the O-postmortem label as a result https://github.com/cockroachdb/cockroach/issues/107357

Jira issue: CRDB-21463

Epic CRDB-19168

**Comment by ajwerner** [comment]
We should see if we can teach randgen to only produce small integers in a bounded range because it'll actually lead to more interesting cases and sidestep this problem.

**Comment by postamar** [comment]
Feel at ease to not bother doing more than the minimum to mitigate this, we have bigger fish to fry.
