### ISSUE TITLE
cli: remove env variables from cockroach start --help

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#9189]
When you run `cockroach start --help`, we don't show the env variable for the `--port` flag, as we  do for other commands like `cockroach quit`. 
- `COCKROACH_PORT` for `--port`

**Comment by b0ch3nski** [comment]
Hi,

I'm running the current latest version (_beta-20160829_) and this is a part of the output from ``cockroach start --help`` command:

```
--cert string                   
Path to the client or server certificate. Needed in secure mode.
Environment variable: COCKROACH_CERT
```

**Comment by jseldess** [comment]
You're right, @b0ch3nski. Not sure why I was seeing that. Looks to me like just one env variable is missing, `COCKROACH_PORT`. I'll adjust the description accordingly.

**Comment by mberhault** [comment]
the `--port` flag on the `start` command is technically different from `--port` on all other commands, it's the `ServerPort` as opposed to the `ClientPort` and cannot currently be set through an env variable.
The question is: do we want it to be settable that way?

**Comment by bdarnell** [comment]
I'd rather only allow env vars for client commands (where the convenience matters), and require that things be explicit on the command line for server startup.

**Comment by jseldess** [comment]
Thanks for the clarifications, @bdarnell and @mberhault. Feel free to close this.

**Comment by jseldess** [comment]
Actually, given the preference to allow env vars only for client commands, should we then remove those that do show up for `start` currently?

```
      --ca-cert string
        Path to the CA certificate. Needed by clients and servers in secure
        mode.
        Environment variable: COCKROACH_CA_CERT

      --cert string
        Path to the client or server certificate. Needed in secure mode.
        Environment variable: COCKROACH_CERT

      --insecure
        Run over non-encrypted (non-TLS) connections. This is strongly
        discouraged for production usage and this flag must be explicitly
        specified in order for the server to listen on an external address in
        insecure mode.
        Environment variable: COCKROACH_INSECURE
        (default true)

      --key string
        Path to the key protecting --cert. Needed in secure mode.
        Environment variable: COCKROACH_KEY
```

**Comment by bdarnell** [comment]
`--cert` and `--key` definitely shouldn't have environment variables for `start` - node certs and client certs are different so it doesn't really make sense to have one environment variable that could be used for either. I would also remove the env vars for `--ca-cert` and `--insecure` for the same reasons as `--port`, although the argument is less clear-cut here since the CA cert especially is likely to be something system-wide and more annoying to specify by hand.

**Comment by jseldess** [comment]
@mberhault, let's just repurpose this issue to remove the env variables from `cockroach start --help`. See @bdarnell's last comment. Not sure if we should keep `--ca-cert` and/or `--insecure` though.

**Comment by mberhault** [comment]
This seems reasonable, most of the env variables have a different meaning when using `--start` vs any other command.
`--insecure` I would drop in a hearbeat. It's still undesirable, and requiring that it be specified on the command line makes it that much clearer.

If the only thing left is `--ca-cert` and we have to specify other cert/key flags anyway, then we might as well drop it.

**Comment by a-robinson** [comment]
`COCKROACH_PORT` is no longer documented in `cockroach start --help`, but it still gets used when setting up the server. I assume that's not intentional, @mberhault?

**Comment by spencerkimball** [comment]
@mberhault could you decide whether anything needs to be done here for 1.0?

**Comment by mberhault** [comment]
The remaining env variables documented in `cockroach start` are for `--insecure` and the cert/key flags.
I'll send a PR to drop `COCKROACH_INSECURE`. The certs ones will soon be replaced by `COCKROACH_CERTS_DIR` which might be reasonable to keep as an env variable, but can be revisited at part of the #1674 implementation.

**Comment by mberhault** [comment]
The old cert flags are deprecated (but still present) and no longer have env variables.

We're left with `CERTS_DIR` and `INSECURE`, both of which apply to both servers and clients. I think it would make sense to keep those. If I decide to run everything in insecure mode, it's convenient to have the env variable set. Same if I choose to use a non-default certs directory.

@bdarnell: you seemed to feel pretty strongly about this.

**Comment by bdarnell** [comment]
Yes, CERTS_DIR and INSECURE should have env variables at least for client commands. I'd still prefer to not allow the env vars on `start`.

**Comment by mberhault** [comment]
ok. I'll try to drop them from `start`. Now that `--insecure` is not entangled with other flags it should be easier to split server and client flags (see #14662)

**Comment by knz** [comment]
@bdarnell can you clarify your motivation for keeping the INSECURE as env var for clients?

**Comment by bdarnell** [comment]
@knz the motivation for all of the client-side environment variables is that you should be able to set things up so that `cockroach sql` with no arguments will connect to your preferred cockroach cluster. That means you need to be able to specify host, port, and either certs or insecure mode.

**Comment by knz** [comment]
ok thanks

**Comment by mberhault** [comment]
`COCKROACH_INSECURE` is gone, just `COCKROACH_CERTS_DIR` left. I'll do that real quick.

**Comment by jseldess** [comment]
@mberhault, is there a separate issue tracking removal of `COCKROACH_CERTS_DIR` from `cockroach start`?

**Comment by mberhault** [comment]
nope, this one applies to all env variables on the `start` command. I just did `--insecure` first because it proved to be annoying a few weeks ago.

**Comment by mberhault** [comment]
`COCKROACH_CERTS_DIR` is gone from `cockroach start`. Closing.
