### ISSUE TITLE
storage: TestPebbleEquivalence/engine/random=0 failed

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#91919]
**Describe the problem**

[On a recent PR](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/7489580?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildDeploymentsSection=true&expandBuildTestsSection=true)

```
Failed
=== RUN   TestPebbleEquivalence/engine/random=0
check file = /artifacts/tmp/_tmp/3cb480549dd56d78f96a16434f955825/TestPebbleEquivalence2507960822/output.meta
output file = /artifacts/tmp/_tmp/3cb480549dd56d78f96a16434f955825/TestPebbleEquivalence_engine_random=0489472918/output.meta
store path = /artifacts/tmp/_tmp/3cb480549dd56d78f96a16434f955825/TestPebbleEquivalence_engine_random=01057831815/store
    generator.go:417: mismatching output at line 9664, operation index 9559: expected truncated range to delete = "kqyrnuwnfny" - "ocmssqcfjho", deleted keys = "ksojwpdnqdthwvu", "lbuaonjjmmy", "lyxabfyy", "mahtkblrbyvxop", "maodqouw", "mdifkrhuyrpgbjj", "moojbtbhlxvi", "mqvnkxki", "nkalqqqwgircxcc"
        , got error: conflicting intents on "maodqouw"
    --- FAIL: TestPebbleEquivalence/engine/random=0 (19.18s)
```

Jira issue: CRDB-21488

**Comment by stevendanna** [comment]
This has also happened recently on master: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/7463267?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildDeploymentsSection=true&expandBuildTestsSection=true

**Comment by adityamaru** [comment]
Another one - [TestPebbleEquivalence/engine/random=5](https://teamcity.cockroachdb.com/viewLog.html?buildId=7528607&buildTypeId=Cockroach_BazelExtendedCi#testNameId-1926619615593791317)

**Comment by adityamaru** [comment]
[TestPebbleEquivalence/engine/random=9](https://teamcity.cockroachdb.com/viewLog.html?buildId=7547707&buildTypeId=Cockroach_BazelEssentialCi#testNameId6532910176592817123)
