### ISSUE TITLE
sql: import doesn't set NumRows properly in log-based telemetry

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#91940]
Import doesn't set NumRows properly in log-based telemetry:
![image](https://user-images.githubusercontent.com/22278911/202022953-805c6001-f4c3-4dbe-94b2-353c1bf62725.png)

Jira issue: CRDB-21497

Epic CRDB-17785

**Comment by ZhouXing19** [comment]
Can I get more details about how the above screenshot was generated?
I tried reproduing this by having 
```
SET troubleshooting_mode=on;
SET CLUSTER SETTING sql.telemetry.query_sampling.enabled = true;
```
and checked the `cockroach-data/logs/cockroach-telemetry.log`.  I noticed that for `IMPORT INTO` statements the NumRows are always 1, even when multiple rows are imported (see below). This is also wrong but it's not `null` as shown above.

```
"EventType":"sampled_query","Statement":"IMPORT INTO newdb.public.t(x) CSV DATA (‹'nodelocal://1/test.csv'›)","Tag":"IMPORT","User":"root","ApplicationName":"$ cockroach sql","ExecMode":"exec","NumRows":1, ...
```

**Comment by awoods187** [comment]
Responded in Slack
