### ISSUE TITLE
changefeedccl: observability for CDC transformations

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#92004]
We need some observability for people using transformations:
- number messages filtered out (_Note: _ hard to track because for some filtering we constrain the ranges we are looking at..)
- Cost of running

Other things TBD

Jira issue: CRDB-21519

Epic CRDB-17161

**Comment by amruss** [comment]
Leaving this in triage so yevgeniy can weigh in

**Comment by miretskiy** [comment]
Closing for now; rudimentary metrics were added by https://github.com/cockroachdb/cockroach/pull/94806;
Tracking which spans are being processed -- that's the job of explain changefeed when it is implemented.
