### ISSUE TITLE
sql: test crdb_internal.cluster_execution_insights on tenants with contention

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/cockroach#92019]
We should add some tests for crdb_internal.cluster_execution_insights on tenant clusters, with contention.

Jira issue: CRDB-21523

**Comment by ericharmeling** [comment]
I thought probabilistic tenant testing in our current set of insights integration tests (specifically, [`TestInsightsIntegrationForContention`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sqlstats/insights/integration/insights_test.go#L292)) might cover testing `crdb_internal.cluster_execution_insights` on tenants with contention, but I don't think our current tests are producing enough data per run to replicate the `(error encountered after some results were delivered)
ERROR: invalid uvarint length of 9` error fixed by https://github.com/cockroachdb/cockroach/commit/034b5a2a77ea4aa144072b25be0bd06f6c56b016. (Or the test tenants just aren't running for these tests for some reason?).

I tested this locally just to make sure. Forcing tenants with https://github.com/cockroachdb/cockroach/commit/034b5a2a77ea4aa144072b25be0bd06f6c56b016 reverted still succeeds after :
` ./dev test --stress --stream-output --ignore-cache pkg/sql/sqlstats/insights/integration -f TestInsightsIntegrationForContention --test-args '--tenantMode=forceTenant -test.v' --show-logs`

So I'm leaning towards making a multi-tenant roachtest with the insights workload.

**Comment by j82w** [comment]
A test was added part of https://github.com/cockroachdb/cockroach/pull/97467. Other tests will be fixed to handle multi-tenant scenarios by the multi-tenant team. Related thread: https://cockroachlabs.slack.com/archives/C02HWA24541/p1677618702956119

**Comment by j82w** [comment]
I did verify that all the insights integration tests pass locally if moved to `pkg/ccl`.
