### ISSUE TITLE
server: need alternate TLS config that verifies CA but not server addresses during mTLS

### ISSUE THREAD

**Issue by sean-** [cockroachdb/cockroach#92021]
**Is your feature request related to a problem? Please describe.**
As seen in https://github.com/cockroachlabs/support/issues/1875 , we would've had a fast path to resolving the customer's problems if we could have a way to customize how TLS certs are validated.

**Describe the solution you'd like**
The ability to pass flags to modify the TLS server and client to validate the CA but not node addresses (server equivalent to `sslmode=verify-ca` in SQL client drivers).

**Describe alternatives you've considered**
Reworking the customer's PKI to include the hostname and IP in cert's SNI.

Jira issue: CRDB-21524

**Comment by knz** [comment]
Technically, this is advocating for:

- a configuration option (CLI flag + env var, as usual) to enable the different behavior
- when the different behavior  is enabled:
  - use `InsecureSkipVerify` on the tls context used to verify the remote node identity
  - ALSO add code that verifies the CA matches.

See for example the code in the pgx client driver:

```go
                tlsConfig.InsecureSkipVerify = true
                tlsConfig.VerifyPeerCertificate = func(certificates [][]byte, _ [][]*x509.Certificate) error {
                        certs := make([]*x509.Certificate, len(certificates))
                        for i, asn1Data := range certificates {
                                cert, err := x509.ParseCertificate(asn1Data)
                                if err != nil {
                                        return errors.New("failed to parse certificate from server: " + err.Error())
                                }
                                certs[i] = cert
                        }

                        // Leave DNSName empty to skip hostname verification.
                        opts := x509.VerifyOptions{
                                Roots:         tlsConfig.RootCAs,
                                Intermediates: x509.NewCertPool(),
                        }
                        // Skip the first cert because it's the leaf. All others
                        // are intermediates.
                        for _, cert := range certs[1:] {
                                opts.Intermediates.AddCert(cert)
                        }
                        _, err := certs[0].Verify(opts)
                        return err
```

**Comment by knz** [comment]
The **difficulty** in this project is that:
-  crdb does not clearly separate the TLS context used to _accept_ incoming connections and that used to _connect_ to other nodes.
- we also confuse the server TLS context used for gRPC and that used for SQL.

In order for this project to be successful, we will need to be careful to introduce testing for the various combinations:
- node-node connection
- CLI admin to node connection (e.g. `node decommision`)
- SQL to node connection

**Comment by knz** [comment]
Will welcome @bdarnell 's opinion of this.

**Comment by catj-cockroach** [comment]
Why not just run the cluster in insecure mode?

**Comment by knz** [comment]
A specific/technical question, maybe for @catj-cockroach: 

- the pgx code I pasted above is careful to not validate the peer DNS name with the CA cert (i.e. if the CA cert has names in its SAN, they are ignored)
- in contrast, the code used by the lib/pq client driver _does_ check the DNS names against the CA cert, see `vendor/github.com/lib/pq/ssl.go` function `sslVerifyCertificateAuthority`

Hence the question: if we want to do the work described at top, which of the two behaviors should we use?

(I was surprised to learn that CA certs could contain SAN fields. I've never seen it used. Curious about what it's good for.)

**Comment by knz** [comment]
Feedback from Catherine about why this solution has drawbacks:

Insecure means:
- no identity validation of target hosts
- no transport layer encryption

Ideally we want:
- CA verification to establish that the node certificate is trusted
- Host/SAN verification to establish that the certificate hasn’t been exfiltrated to another machine
- Transport layer encryption between the client and the now trusted machine

Verify CA gives us:
- Validates that the node certificate is trusted
- Doesn’t validate that the host is trusted
- Transport layer encryption between client and any machine with the certificate
- malicious misuse of certificates has no differences between legitimate use

And unless they’re making short-lived certificates, turning off identity verification means that a certificate issued off of the CA can be used as long as it doesn’t expire, without any evidence of misuse.

**Comment by catj-cockroach** [comment]
My position is that this is us trying to fix a customers' PKI issue in our code, which is not our responsibility. This change may help the customer in question continue with their existing PKI, but will cause more security issues in the long term. This makes it easier to do the wrong thing (setup TLS without identity verification), made easier by the fact that a poorly implemented PKI will work with it. 

I'd argue we should look at other alternatives, like having an alternate health check so CockroachDB shows itself as active, but doesn't try to connect to the cluster until a TLS private key and certificate are available.

**Comment by catj-cockroach** [comment]
I'd argue that the issue is that our PKI code is incompatible with other organizations' PKI, not that they need or want to disable hostname verification. It will become more common for us to have CRDB deployments that work in this degraded way if we add this feature, and that will cause more support work and security issues for customers.

I want us to dedicate time to improving our PKI code, and one of the alternate proposals to this would help improve this (using a separate SQL server certificate from the node-to-node certificate). Between the timeline being asked for this change and the fact that we can't easily undo it once we've done it I don't we should implement this feature in CockroachDB for the expected timeline.

**Comment by knz** [comment]
Yes i filed https://github.com/cockroachdb/cockroach/issues/92069 for your latter proposal.

**Comment by catj-cockroach** [comment]
I'm going to close this issue since it's solution specific and we will not be implementing the solution described.
