### ISSUE TITLE
*: use in-memory transport for local gRPC traffic

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#92054]
In https://github.com/cockroachlabs/support/issues/1875, we found several components attempting to connect to the local node via a gRPC network transport (and failing due to a missing DNS entry). These should use an internal in-memory transport instead. In particular:

* Range merges: to verify all replicas are initialized before merging.
* Consistency checks: to fetch the computed checksum from each replica.
* Below-Raft upgrade migrations: to verify the migration has been applied on all replicas.
* Tracing: to collect trace results.

These use `Dialer.Dial` to obtain a networked gRPC connection to the target. We have a separate method `DialInternalClient` that instead uses an in-memory transport:

https://github.com/cockroachdb/cockroach/blob/6e98b39bc6b14da51e43265c5512e23c88b91b2e/pkg/rpc/nodedialer/nodedialer.go#L140-L145

However, this method can only obtain a client for the `Internal` gRPC service (which in particular provides the `Batch` RPC method). The components above need access to different gRPC services, in particular the `PerReplica` service.

We'll either need to add separate dial methods with in-memory transports for each gRPC service that may need to connect to the local node, or generalize the in-memory transport in such a way that it can work regardless of the gRPC service.

Jira issue: CRDB-21548

**Comment by knz** [comment]
NB: we have another mechanism in the `server` package called `loopbackListener` which we could use here without all the special-casing of the Internal service.
