### ISSUE TITLE
CDC to Apache Pulsar

### ISSUE THREAD

**Issue by tspannhw** [cockroachdb/cockroach#92066]
**Is your feature request related to a problem? Please describe.**
Same as Kafka

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Jira issue: CRDB-21558

**Comment by amruss** [comment]
Hey @tspannhw  - can you give more details about your request? Why would it be beneficial to have a pulsar integration?

**Comment by miretskiy** [comment]
Dup of [49805](https://github.com/cockroachdb/cockroach/issues/49805)

**Comment by dbist** [comment]
What's up @tspannhw, thanks to KoP, CDC to Pulsar works out of the box https://blog.ervits.com/2023/04/using-cockroachdb-cdc-with-apache-pulsar.html
