### ISSUE TITLE
kv,server: tenant-scope nodes endpoint

### ISSUE THREAD

**Issue by THardy98** [cockroachdb/cockroach#92065]
We would like to tenant-scope the `/_status/nodes` endpoint for use on our serverless platform. The endpoint should return the number of SQL nodes being used by the tenant.

Jira issue: CRDB-21557

**Comment by kevin-v-ngo** [comment]
@matthewtodd, in our triage, we discussed reassigning and requesting support from KV or Obs Inf on this. If so, feel free to update the 'Projects' to the appropriate team.

**Comment by matthewtodd** [comment]
Thanks, @kevin-v-ngo, I took a crack at it today and will socialize what I learned tomorrow.
