### ISSUE TITLE
kvserver: invalidate lease when leaseholder is unable to reach Raft leader

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#92089]
In https://github.com/cockroachlabs/support/issues/1875 and https://github.com/cockroachdb/cockroach/issues/92088, we saw a case where the Raft leader and leaseholder were located on separate nodes, and there was an asymmetric partition between them such that the Raft leader was able to send heartbeats to the leaseholder, but the leaseholder was unable to send proposals to the Raft leader. They were both able to heartbeat their liveness entries.

In this scenario, the leaseholder won't be able to serve writes since it can't submit proposals (making the range effectively unavailable), and it also won't be able to acquire the Raft leadership.

We should attempt to detect this situation, and release either the lease or the Raft leadership to attempt to resolve it. `CheckQuorum` won't help here, because the leader has a bidirectional connection to the third replica.

Jira issue: CRDB-21568

Epic CRDB-25199

**Comment by erikgrinaker** [comment]
One possible solution here is discussed in https://docs.google.com/document/d/134eVs69fVBhP-01bxfrdjPxz--drNjOQ8AI-7Z3UD6U/edit#.

**Comment by nvanbenschoten** [comment]
Will be addressed by https://github.com/cockroachdb/cockroach/issues/123847.
