### ISSUE TITLE
multi-tenant: Set tenant's cluster version correctly on tenant creation

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#92080]
Currently, during tenant creation, we set the tenant's cluster version to the 'ActiveVersion' of the host/storage cluster.  

https://github.com/cockroachdb/cockroach/blob/a2ce495ee932c1a9cd5fcfd1e1336daf4c5a6694/pkg/sql/tenant.go#L255-L256

This is problematic in mixed-version clusters, where if the tenant is created on a node with a binary version which exceeds `ActiveVersion`, the tenant will be created with a system database which reflects the binary version, but with a cluster version which is set to the lower `ActiveVersion`.  This could create problems at runtime as the code may not know how to deal with migrations which are present but aren't reflected in the `ActiveVersion`.

This issue was first called out as problematic [here](https://github.com/cockroachdb/cockroach/issues/80992#issuecomment-1194303124), but is being moved to a new issue to ensure it doesn't get accidentally lost.  

There's an ongoing discussion about this issue on internal Slack [here](https://cockroachlabs.slack.com/archives/C02HWA24541/p1668637132460519).

Epic: CRDB-10829

Jira issue: CRDB-21565

**Comment by knz** [comment]
Fixed in #94973
