### ISSUE TITLE
ui: removing a metric (from the backend) can break graphs

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#9211]
#9176 removed `cr.store.raft.process.waitingnanos` which breaks not only the graph which uses that metric, but all subsequent graphs on the page. The UI should be more tolerant of missing metrics and this should have been caught with a test.

**Comment by tamird** [comment]
This is somewhat related to https://github.com/cockroachdb/cockroach/issues/7621.

I'm not really sure a nice solution to this exists currently, since we don't have UI integration tests. just sayin'.
