### ISSUE TITLE
Geo distributed roachtests which specify a node count not equal to number of default zones causes error.

### ISSUE THREAD

**Issue by smg260** [cockroachdb/cockroach#92150]
**Describe the problem**

When running a geo distributed roachtest where node count is > default zone count OR node count < default zone count, a cluster creation error OR index out of bound error are encountered respectively

**To Reproduce**

Run a geo distributed roach test where cluster node count != default zone count (currently 9)

If possible, provide steps to reproduce the behavior:

Run a test with node count  = 4
1. `roachtest run sqlsmith/settup=seed-multi-region/setting=multi-region` 

Cluster creation fails.

Run a test with node count = 10
1. update `roachtest/tests/sqlsmith.go` with node count = 10
2. `roachtest run sqlsmith/settup=seed-multi-region/setting=multi-region` 

Index error

**Expected behavior**
Cluster should be created successfully and test executed.

**Environment:**
 - master
 
**Additional context**
What was the impact? Failed daily roachtests

This is a bug that has existed for quite some time but was only surfaced due to a recent change increasing the number of default zones, hence resulting in an existing test having node count < default zone count.

Jira issue: CRDB-21604

**Comment by srosenberg** [comment]
Linking to the PR which introduced a change which helped expose this bug: https://github.com/cockroachdb/cockroach/pull/91244
