### ISSUE TITLE
ORDER BY on columns containing unicode string 

### ISSUE THREAD

**Issue by derkan** [cockroachdb/cockroach#9215]
Hi,
Sorting on unicode strings returns non-ascii unicode chars last. I searched in issues and forum but unable to locate a related issue.*(Issue #2044 is about using unicode chars on table names but doesn't address this issue. And in my opinion, supporting unicode chars on table names is not as important as this one. )*
 

*For example* if data is:

|col1|
|------|
|Ömer|
|Ali|
|Zeki|
|İsa|

After `ORDER BY col1` result is(which is wrong):

|col1|
|------|
|Ali|
|Zeki|
|Ömer|
|İsa|

Instead it should be:

|col1|
|------|
|Ali|
|İsa|
|Ömer|
|Zeki|

I think ORDER BY collate support as Postgresql's [`COLLATE 'tr_TR.UTF-8'`](http://www.postgresql.org/docs/9.5/static/collation.html) is necessary. (or at least correct `utf-8` sorting). This is a big problem for data including chars of [Turkish Alphabet](https://en.wikipedia.org/wiki/Turkish_alphabet)

I also tried on a database created with `encoding 'UTF-8'`. And faced same problem.
SQL used:
```sql
create database testdb encoding='UTF-8';
set database=testdb;
create table test (col1 string(32));
insert into test values('Ömer');
insert into test values('Ali');
insert into test values('Zeki');
insert into test values('İsa');
select * from test order by col1;

```
Is COLLATE support is planned for sorting?

**Comment by a-robinson** [comment]
Hi @derkan, thanks for the issue report. We do plan to support COLLATE, likely before version 1.0. It's being tracked by #2473, which you actually commented on a few months ago. Is there anything more you'd need that isn't covered by supporting COLLATE?

**Comment by derkan** [comment]
Hi @a-robinson, I searched for that issue but couldn't found. Thanks for link. I'm closing this issue in favor of  #2473.
