### ISSUE TITLE
acceptance/cluster: nodes in acceptance tests are killed brutally and don't flush their logs

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#9220]
`LocalTestCluster.stop()` does `ContainerKill(9)` to stop the docker container, which bypasses all the server's nice shutdown logic. Instead we should attempt a more graceful signal first, and SIGKILL only if the server doesn't cooperate.

**Comment by petermattis** [comment]
Or we could change the acceptance tests to `--logtostderr` which isn't buffered.

**Comment by a6802739** [comment]
@andreimatei , I have time to fix this now.

**Comment by andreimatei** [comment]
So it turns out that we do also log to stderr, which indeed isn't buffered. And we save the container's stderr to a file when the test is done. More precisely, we set `--alsologtostderr=INFO` on the container's command (and we also set `--logtostderr=false` if `-l` is set on the test (a log dir), but this luckily doesn't seem to have any effect haha).

Having said this, I think it's still worth attempting a nice shutdown in these acceptance tests. Probably sending `SIGQUIT` first is the right thing to do.
So @a6802739, if you wanna take it, feel free to assign yourself or send a PR, that'd be great.
The code for killing these containers is:
https://github.com/cockroachdb/cockroach/blob/4194d97/acceptance/cluster/localcluster.go#L704

You can run one these tests with something like:
```
make acceptance TESTS=TestPartitionBank TESTFLAGS="-l=logs -nodes=3`
```
The "wait on stop" flag (`-w`) might be useful for playing around.

You'll need docker installed, and you'll see these tests creating containers for the cockroach nodes and networks. Keep in mind that the test itself runs outside of a container.

**Comment by a6802739** [comment]
@andreimatei , Thanks a lot. I'll have a try.

**Comment by tamird** [comment]
I'm confused - what's the expected outcome here? ISTM that we definitely sometimes want to hard-kill nodes in acceptance tests, and if we're also logging to an unbuffered stream, what's left to fix?

**Comment by andreimatei** [comment]
Maybe we sometimes want to hard-kill nodes, but not always. In particular, not on the regular test shutdown, I'd say. Because we should be exercising the non-brutal exit path, and also because ideally the INFO log file should be flushed under normal circumstance. At least I found it confusing that it wasn't and took me a while to figure out the stderr situation.

**Comment by tschottdorf** [comment]
Closing as not actionable.
