### ISSUE TITLE
sql: Can't use literal VALUES expressions with CREATE TABLE AS

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#9222]
In Postgres:

```
alex=# create table test9 as values (1, 'one'), (2, 'two');
SELECT 2
alex=# select * from test9;
 column1 | column2
---------+---------
       1 | one
       2 | two
(2 rows)
```

In CockroachDB:

```
root@:26257> create table test9 as values (1, 'one'), (2, 'two');
pq: Invalid Select type.
```

The functionality is reasonably well-documented:
https://www.postgresql.org/docs/9.1/static/sql-createtableas.html
https://www.postgresql.org/docs/9.1/static/sql-values.html

For what it's worth, MySQL doesn't support this, and I'm honestly not sure whether we want to. @knz, is the lack of support for this intentional? If so, should we also not support it in views?

**Comment by a-robinson** [comment]
Note that we have the parsing logic in place for VALUES expressions (unlike MySQL) and support them in other contexts (example below), but choose not to support them in this context.

```
root@:26257> values (1, 'one'), (2, 'two');
+---------+---------+
| column1 | column2 |
+---------+---------+
|       1 | one     |
|       2 | two     |
+---------+---------+
(2 rows)
```

**Comment by knz** [comment]
This is an oversight. We can support this and we should.

**Comment by knz** [comment]
Feel free to have a look and see if you can fix it yourself. It would be a good exercise for you to get started with the syntactic trees which you need for views.

Hint: the fix a simple extension of one of the `switch` statements in `create.go`. The function containing it is currently very (too) short.

**Comment by a-robinson** [comment]
Yup, I'm happy to fix it while I'm already in that code. I just wanted to check first whether we were intentionally not supporting it :)
