### ISSUE TITLE
Display Reasoning Behind Why User is Unable to Revoke Grant

### ISSUE THREAD

**Issue by NigelNavarro** [cockroachdb/cockroach#92298]
**Is your feature request related to a problem? Please describe.**
While working with a customer, we noticed that using a `REVOKE` statement does not provide an indicator on whether or not it was successful in the CockroachDB CLI. The most that ends up being reported is the execution time:

```
root@localhost:26257/test_db> REVOKE ALL PRIVILEGES ON SCHEMA test_schema FROM test_user;
REVOKE


Time: 31ms total (execution 31ms / network 0ms)
```

This is confusing if the user has the incorrect parameters and/or permissions set up when invoking the statement, as there is no indicator that signifies whether the revoke was successful or not. As an example, further testing had to be done with the customer in order to recognize that the schema was owned by the SQL user that the customer wanted to revoke privileges for.

**Describe the solution you'd like**
As a TSE or customer, it would be greatly beneficial to have error logging around the use of `REVOKE` reported in the CockroachDB CLI and in the Cockroach logs after the user runs their command. We may want to consider also adding the error result to the Statement details in the DB Console so that the user is able to fully self-diagnose why they were unable to revoke the grant for their desired user.

CC: @thtruo 

Jira issue: CRDB-21693

**Comment by thtruo** [comment]
Thanks Nigel. cc-ing @kevin-v-ngo for awareness and triage as this lives in SQL Obs land

**Comment by rafiss** [comment]
This is for SQL Experience, not SQL Obs - same for all GRANT, role, and privilege work.
