### ISSUE TITLE
ui: add 23.1 version gate to frontend SQL insights queries

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/cockroach#92352]
https://github.com/cockroachdb/cockroach/pull/90660 added a `contention_events` column to the `crdb_internal.cluster_execution_insights` table, and https://github.com/cockroachdb/cockroach/pull/91668 updated the `workloadInsightsQuery` SQL query in `pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` to select from this column.

These PRs will not be backported to `release-22.2`. Using a `cluster-ui` build with these updates against a 22.2 cluster will cause the SQL-over-HTTP API to respond with an error, and the front end to show an empty statement insights table. We should add a version gate to the front-end queries to prevent mixed-version clusters from selecting from the `contention_events` column in 22.2 databases.

Jira issue: CRDB-21715

**Comment by maryliag** [comment]
No longer a priority
