### ISSUE TITLE
TestCCLLogic_regional_by_row  flaked on master

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#92427]
https://teamcity.cockroachdb.com/viewLog.html?buildId=7668792&buildTypeId=Cockroach_BazelEssentialCi

Jira issue: CRDB-21765

**Comment by rafiss** [comment]
```
    logic.go:3047:
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/7272/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-tenant/multiregion-9node-3region-3azs-tenant_test_/multiregion-9node-3region-3azs-tenant_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/logictestccl/testdata/logic_test/regional_by_row:515:
        expected success, but found
        (XXUUU) job 816440213353070593: protected timestamp record does not exist
        protectedts.go:31: in init()
```

It fails on 
```
statement ok
ALTER TABLE regional_by_row_table ALTER PRIMARY KEY USING COLUMNS (pk2)
```

Let's see if the sql-schema team has any ideas.

**Comment by rafiss** [comment]
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/7757672?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true is another failure and I think it happened after https://github.com/cockroachdb/cockroach/pull/92586 merged.

**Comment by adityamaru** [comment]
Saw another flake reported to flaky-test-fighter - https://teamcity.cockroachdb.com/viewLog.html?buildId=7757653&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_BazelUnitTests which also seems after the above fix has merged. @fqazi can you take a look whenever you have time, thanks!

**Comment by fqazi** [comment]
Let me dig into this

**Comment by fqazi** [comment]
Taking a look right now

**Comment by fqazi** [comment]
The protect path for installing the protected stamp had a similar bug, I'll get a PR out shortly
