### ISSUE TITLE
storage: avoid holding Store.mu when destroying replica data

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#9244]
`Store.removaReplicaImpl` currently contains the following TODO:

```
	// TODO(bdarnell): Destroying the on-disk data is fairly expensive to do
	// under store.Mutex, but doing it outside the lock is tricky due to the risk
	// that a replica gets recreated by an incoming raft message.
	return rep.Destroy(origDesc, destroyData)
```

Holding `Store.mu` while destroying a replica is very unfortunate as it blocks all Raft processing on the replica. Rather than holding on to `Store.mu` when destroying the replica data, it seems possible to:

1. Mark the replica as destroyed, but leave it present in `Store.mu.{replicas,replicasByKey}`.
2. Unlock `Store.mu`. Nothing can muck with the replica at this point because we're holding `Replica.raftMu`.
3. Destroy the replica's on disk state.
4. Lock `Store.mu` and remove the replica from `Store.mu.{replicas,replicasByKey}`.

@bdarnell Am I missing any subtlety here? Related to #8630, we'd want to be sure we're holding `Replica.readOnlyCmdMu` while deleting the data. 

Cc @cockroachdb/stability

**Comment by bdarnell** [comment]
No, I don't think you're missing anything. Now that we have replica-level `raftMu` it shouldn't be hard to get this off of `Store.mu`.
