### ISSUE TITLE
stability: photos wedges itself on (at least) gamma cluster

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#9247]
Even after restarting all the photos instances, after a few hundred operations no more progress is made. #8812 and to a lesser extent #8681 should be helpful in investigating this.

**Comment by tschottdorf** [comment]
```
2016/09/15 02:36:58.284202	33.956148	node.Batch
02:36:58.284208	 .     6	... node.Batch
02:36:58.284215	 .     6	... node 1
02:36:58.284240	 .    25	... [n1,s1] executing 1 requests
02:36:58.284392	 .   152	... [n1,s1,r75243{/Table/55/1/""/2016-09-04T12:17:43.903178Z/".y\v\x81\xba\xceF\x17\xbeG/I\x85\xb9\xa9I"-/Table/55/1/"\x00?JJ\xf9XNg\x9d\xc1\xf6\xc5\u009a\xe1z"/2016-09-02T01:41:24.523288Z/"\xb1 \xeb3\x84\x81Bh\x8c\x88\xe1\xb9[\xf2\xba\xa4"}] read-only path
02:37:26.977522	 .    39	... (137 events discarded)
02:37:26.977642	 .   120	... [n1,s1] sending RPC for batch: PushTxn [/Table/55/1/""/2016-09-10T03:56:39.227014Z/"\x14\xb2\xf4R]hN \x8fĤB5Ѽ\xfa"/1/1,/Min)
02:37:26.987538	 .  9896	... [n1,s1] reply error PushTxn [/Table/55/1/""/2016-09-10T03:56:39.227014Z/"\x14\xb2\xf4R]hN \x8fĤB5Ѽ\xfa"/1/1,/Min): failed to push "sql/executor.go:499 sql txn" id=bce032a0 key=/Table/55/1/""/2016-09-10T03:56:39.227014Z/"\x14\xb2\xf4R]hN \x8fĤB5Ѽ\xfa"/1/1 rw=true pri=0.06736480 iso=SERIALIZABLE stat=PENDING epo=0 ts=1473907017.672046417,1 orig=1473906916.304390991,0 max=1473906916.315176387,0 wto=false rop=false
02:37:26.987549	 .    11	... [n1,s1] error: failed to push "sql/executor.go:499 sql txn" id=bce032a0 key=/Table/55/1/""/2016-09-10T03:56:39.227014Z/"\x14\xb2\xf4R]hN \x8fĤB5Ѽ\xfa"/1/1 rw=true pri=0.06736480 iso=SERIALIZABLE stat=PENDING epo=0 ts=1473907017.672046417,1 orig=1473906916.304390991,0 max=1473906916.315176387,0 wto=false rop=false
02:37:26.987568	 .    19	... [n1,s1] error: *roachpb.WriteIntentError
02:37:26.989479	 .  1911	... [n1,s1] backoff
```

**Comment by tschottdorf** [comment]
Long-running intent resolution wedges seem to disappear, but I've seen them easily exceed 90s.

**Comment by tschottdorf** [comment]
Instructive traces:

For Node.Batch: https://app.lightstep.com/gamma/trace?span_guid=2e0e68d385f5a1fc&at_micros=1473907008175365#span-2e0e68d385f5a1fc

There is a lot of unsuccessful pushing in that trace.

For the DistSender side of this: https://app.lightstep.com/gamma/trace?span_guid=228e45075100abad&at_micros=1473907289400309#span-228e45075100abad

There are a lot of retries which are unfortunately not identified further (I'll send a fix for that).

Once #9360 is deployed we'll see both of those spans glued together, which should make it easier to see what's what.

**Comment by tschottdorf** [comment]
The majority of the retries for the Node.Batch trace probably originates here:

```go
			if !includesFrontOfCurSpan(desc) {
				if err := evictToken.Evict(ctx); err != nil {
					return nil, roachpb.NewError(err), false
				}
				// On addressing errors, don't backoff; retry immediately.
				r.Reset()
				continue
			}
```

since that path leaves `pErr == nil` (which is then logged in the periodic messages).

**Comment by tschottdorf** [comment]
Here's an even longlonglonger one:

```
2016/09/15 02:55:27.377231	1227.403797	node.Batch
02:55:27.377238	 .     7	... node.Batch
02:55:27.377245	 .     7	... node 1
02:55:27.377269	 .    23	... [n1,s1] executing 1 requests
02:55:27.377400	 .   132	... [n1,s1,r75243{/Table/55/1/""/2016-09-04T12:17:43.903178Z/".y\v\x81\xba\xceF\x17\xbeG/I\x85\xb9\xa9I"-/Table/55/1/"\x00?JJ\xf9XNg\x9d\xc1\xf6\xc5\u009a\xe1z"/2016-09-02T01:41:24.523288Z/"\xb1 \xeb3\x84\x81Bh\x8c\x88\xe1\xb9[\xf2\xba\xa4"}] read-only path
03:15:54.336175	 .    43	... (2957 events discarded)
03:15:54.337006	 .   831	... [n1,s1] sending RPC for batch: PushTxn [/Table/55/1/""/2016-09-15T02:47:43.681477Z/"\x00\xe0\xfdz\xa3zCo\x92\x809\xe8-D\xd9\x02"/1/1,/Min), PushTxn [/Table/55/1/""/2016-09-15T02:47:43.681477Z/"\x00\xe0\xfdz\xa3zCo\x92\x809\xe8-D\xd9\x02"/1/1,/Min), PushTxn [/Table/55/1/""/2016-09-15T02:47:43.681477Z/"\x00\xe0\xfdz\xa3zCo\x92\x809\xe8-D\xd9\x02"/1/1,/Min)
03:15:54.511564	 .174559	... [n1,s1] reply error PushTxn [/Table/55/1/""/2016-09-15T02:47:43.681477Z/"\x00\xe0\xfdz\xa3zCo\x92\x809\xe8-D\xd9\x02"/1/1,/Min), PushTxn [/Table/55/1/""/2016-09-15T02:47:43.681477Z/"\x00\xe0\xfdz\xa3zCo\x92\x809\xe8-D\xd9\x02"/1/1,/Min), PushTxn [/Table/55/1/""/2016-09-15T02:47:43.681477Z/"\x00\xe0\xfdz\xa3zCo\x92\x809\xe8-D\xd9\x02"/1/1,/Min): failed to push "sql/executor.go:499 sql txn" id=fd8cdebc key=/Table/55/1/""/2016-09-15T02:47:43.681477Z/"\x00\xe0\xfdz\xa3zCo\x92\x809\xe8-D\xd9\x02"/1/1 rw=true pri=0.06451914 iso=SERIALIZABLE stat=PENDING epo=4 ts=1473908124.628624083,1 orig=1473907804.565393319,0 max=1473907804.612007899,0 wto=false rop=false
03:15:54.511577	 .    13	... [n1,s1] error: failed to push "sql/executor.go:499 sql txn" id=fd8cdebc key=/Table/55/1/""/2016-09-15T02:47:43.681477Z/"\x00\xe0\xfdz\xa3zCo\x92\x809\xe8-D\xd9\x02"/1/1 rw=true pri=0.06451914 iso=SERIALIZABLE stat=PENDING epo=4 ts=1473908124.628624083,1 orig=1473907804.565393319,0 max=1473907804.612007899,0 wto=false rop=false
03:15:54.511597	 .    19	... [n1,s1] error: *roachpb.WriteIntentError
03:15:54.564347	 . 52751	... [n1,s1] backoff
```

The fact that a lot of information is skipped is a bit awkward; we should set a higher buffer for the net/trace (unfortunately, that's upstream but it makes sense to suggest a higher number there anyway).

Luckily, lightstep doesn't have such a limit and some of these spans actually finish (after minutes of looping), which should give us enough intel on what's going wrong (i.e. whether this is real starvation or  some kind of circular pushing game, etc).

**Comment by tschottdorf** [comment]
This is with @RaduBerinde's fix in (combining Node.Batch and the DistSender side): https://app.lightstep.com/gamma/trace?span_guid=6151d5805997ffc&at_micros=1473909885118317#span-6151d5805997ffc

**Comment by tschottdorf** [comment]
`photos --users 10` already provides ample awkwardness to get some interesting phenomena to address, with traces over 10s being available fairly soon.

**Comment by tschottdorf** [comment]
See http://app.lightstep.com/gamma/trace?span_guid=7f08f51236703263&at_micros=1473963092814544#span-7f08f51236703263

![screen shot 2016-09-15 at 2 13 57 pm](https://cloud.githubusercontent.com/assets/5076964/18561689/e7ab4df4-7b4e-11e6-9892-bef5edf13f05.png)

This long-running attempt to scan backs up against the same transaction, `id=da2ff7fa`, many times (eating the 5s maximal backoff ~6x in the process.

The obvious question is why that transaction took so long.

**Comment by tamird** [comment]
I don't suppose we have that transaction's trace (or a reliable way to get
it)?

On Thu, Sep 15, 2016 at 2:20 PM, Tobias Schottdorf <notifications@github.com

**Comment by RaduBerinde** [comment]
Once #9425 goes in, we should be able to.

**Comment by bdarnell** [comment]
It's pushing exactly the same transaction multiple times in the same batch:

```
[n1,s1] sending RPC for batch: PushTxn [/Table/55/1/""/2016-09-15T15:42:43.950002Z/"\x15\xab\xd0j\xcb\xecH\x91\xa6w\x03\xf2\xff\xbb#!",/Min), PushTxn [/Table/55/1/""/2016-09-15T15:42:43.950002Z/"\x15\xab\xd0j\xcb\xecH\x91\xa6w\x03\xf2\xff\xbb#!",/Min), PushTxn [/Table/55/1/""/2016-09-15T15:42:43.950002Z/"\x15\xab\xd0j\xcb\xecH\x91\xa6w\x03\xf2\xff\xbb#!",/Min), PushTxn [/Table/55/1/""/2016-09-15T15:42:43.950002Z/"\x15\xab\xd0j\xcb\xecH\x91\xa6w\x03\xf2\xff\xbb#!",/Min), PushTxn [/Table/55/1/""/2016-09-15T15:42:43.950002Z/"\x15\xab\xd0j\xcb\xecH\x91\xa6w\x03\xf2\xff\xbb#!",/Min), PushTxn [/Table/55/1/""/2016-09-15T15:42:43.950002Z/"\x15\xab\xd0j\xcb\xecH\x91\xa6w\x03\xf2\xff\xbb#!",/Min), PushTxn [/Table/55/1/""/2016-09-15T15:42:43.950002Z/"\x15\xab\xd0j\xcb\xecH\x91\xa6w\x03\xf2\xff\xbb#!",/Min), PushTxn [/Table/55/1/""/2016-09-15T15:42:43.950002Z/"\x15\xab\xd0j\xcb\xecH\x91\xa6w\x03\xf2\xff\xbb#!",/Min)
```

These would be easy to dedupe in `maybePushTransactions`, although I don't think that's going to make much of a difference. 

We see in the "failed to push" error messages that the competing transaction always has `epo=168`, so it has restarted a lot, but it *doesn't* restart during the time of this transaction. Its priority is only 0.19, so it's not getting ratcheted up across these restarts. That might allow it to complete faster. 

Those keys contain an empty string, which is odd. I think this is the `comments` table, so that string is `photo_id`. Empty `photo_ids` don't sound intentional, and could create very high contention. `chooseRandomPhoto` may return `nil, nil` if the selected user has no photos. It looks like it should probably bail out in that case.

**Comment by petermattis** [comment]
This bug is quite old and we're not currently seeing `photos` wedging itself. Closing for now. Re-open if you think there is something still to be investigated.
