### ISSUE TITLE
Cockroachdb cdc debezium format miss “OP”

### ISSUE THREAD

**Issue by Huawu777** [cockroachdb/cockroach#92482]
**Describe the problem**

Cockroachdb cdc debezium format miss “OP” 

**To Reproduce**
I created a changefeed to collect cockroachdb data to kafka，

Then the format of the data I consume is as follows

  "after": {
    "id": 111,
    "name": "scooter",
    "description": "Big 2-wheel scooter",
    "weight": 5.15
  }

**Expected Data**
{
  "before": {
    "id": 111,
    "name": "scooter",
    "description": "Big 2-wheel scooter",
    "weight": 5.18
  },
  "after": {
    "id": 111,
    "name": "scooter",
    "description": "Big 2-wheel scooter",
    "weight": 5.15
  },
  "source": {...},
  "op": "u",
  "ts_ms": 1589362330904,
  "transaction": null
}

**Additional data / screenshots**

**Environment:**
 - CockroachDB version v22.1.10
 - Server OS:  Linux
 - Client app  JDBC

**Additional context**
What was the impact?

Jira issue: CRDB-21799

Epic CRDB-21713

**Comment by amruss** [comment]
Hi @Huawu777 I'm going to put this feature request on the backlog for the moment, but in the near future we are releasing CDC Transformations which will allow you to build this message schema in a custom way

**Comment by miretskiy** [comment]
Isn't it a  dup of CRDB-17023?
