### ISSUE TITLE
Make it easier to run with single node, for tests

### ISSUE THREAD

**Issue by nictuku** [cockroachdb/cockroach#9251]
CDB currently requires 3 nodes by default and the way to run with a single node is described here: https://www.cockroachlabs.com/docs/troubleshoot.html#replicas-failing-on-a-single-node-cluster

I'm trying to add CDB to an integration test. While the existing method is workable, it's a bit annoying when using docker. It would be nice if there was a more user-friendly way to start a single-node CDB "cluster". Say, just like you can do --insecure, it would be cool if there was an --unreliable flag, or so.

I expect this feature to be useful for teams that want to run CDB ephemeral clusters for integration testing. :horse: 
`</I want a pony>`

**Comment by RaduBerinde** [comment]
The command in the instructions is only needed if you want to suppress those errors in the log file. If you don't care about them (and I don't see why you would?) you don't have to do anything..

**Comment by knz** [comment]
With the improvement proposed in #9253 you would simply have to run `cockroach zone set .default --disable-replication` once after starting the cluster. Would that satisfy your use case?

**Comment by nictuku** [comment]
Radu's comment satisfies my use case. As long as a single node is easy to setup, that's fine.

'm having unrelated problems with my CDB setup and I thought it could be caused by it being a single-cluster - the error message seems too scary so I got confused.

**Comment by nictuku** [comment]
Consider changing the docs' wording, though. 

The title says "REPLICAS FAILING ON A SINGLE-NODE CLUSTER" which probably confused both me and @knz to think it wouldn't work with single-nodes.

**Comment by knz** [comment]
@jseldess is there anything actionable for you here?

**Comment by jseldess** [comment]
@knz, yes, definitely. I've created a docs issue: https://github.com/cockroachdb/docs/issues/643
