### ISSUE TITLE
Local development and setting stable credentials via cockroach demo 

### ISSUE THREAD

**Issue by dghubble** [cockroachdb/cockroach#92541]
**Is your feature request related to a problem? Please describe.**

CockroachDB is [aiming to remove](https://github.com/cockroachdb/cockroach/issues/53404) the `insecure` flag and suggests `cockroachdb demo` as an automatically secure alternative for developers. What seems to be missing is one reason _why_ app developers turn to the insecure mode now.

Our application developers are developing a web app locally. They need a local cockroachdb node to work against. This is a throw-away database. It runs on their laptop. They might do start and stop one of these databases for each app, multiple times a day. There seem to be two options:

* `cockroach start-single-node --insecure` (deprecated, annoying to use an extra `insecure` flag in every `cockroach sql` invocation)
* `cockroach demo` (random password)

The way `demo` randomizes the password makes local development harder. Developers need to setup the development database, to load in development data, and configure their web app database url to point at the local cockroachdb node. They may be moving between multiple projects, stopping and starting short-lived, single-node dev databases often. App developers tend to put this all behind an automation step ( `up` script, `npm run db`, `make db`, whatever).

**Describe the solution you'd like**

Today, app developers are using insecure mode because they need a predictable, no-fuss local dev database. `cockroach demo` seems like it could do things in a more secure way by default, but having a randomized password is difficult for local scripting.

```
cockroach demo --password password --listen-addr 127.0.0.1:26257 --http-addr 127.0.0.1:5050
```

The connection string is known and can be used in local development setups.

```
postgresql://root:password@127.0.0.1:26257/mydb
```

**Describe alternatives you've considered**

You can use `cockroach demo` today with its randomized password, long enough to create a new user with a known password. But this is an extra step in local development, especially starting and stopping databases for different projects. We're not really guarding against anything here.

**Additional context**

Again, the use case is _local_ development. I'm all for proper TLS certificate setups in real setups. But we just want a mode for developers on their laptops to quickly work on their web apps with a fake throw-away database. 

Similar to: https://github.com/cockroachdb/cockroach/issues/68437
Jira issue: CRDB-21848
Epic: CRDB-22814

**Comment by knz** [comment]
Have you considered the `--listening-url-file` parameter? This can write the password to a location of your choosing.

**Comment by dghubble** [comment]
I briefly looked at that. Choosing some appropriate location (some .gitignored location in the app that won't clutter things or some cross-OS friendly location outside of the app) and then teaching the app developers' scripts/integrations to read that file might be an option. Most everything expects a DATABASE_URI environment variable, which could be made to have the contents found at that chosen `--listening-url-file` location.

Though for local development, this password doesn't seem to serve much purpose. It seems like the bit of value of a password and sslmode in development is just that its similar-ish to production.

**Comment by kocoten1992** [comment]
Hi, may I jump in this conversation. It not directly related, but recently I've got to restore a database and I saw this:

```
The BACKUP ... TO and RESTORE ... FROM syntax is deprecated as of v22.1 and will be removed in a future release.
```

Unless deprecation will create huge benefit, maybe - just maybe - we don't do deprecation at all?

Community was creating custom script for cockroachdb base on previous api, deprecation mean kind of breaking a promise -  unless the benefit is hugh and outweigh everything else otherwise it kind of mean wasting effort of entire community..

**Comment by knz** [comment]
@kocoten1992 this is valuable feedback, but _please_ create a separate issue for this discussion. It's an entirely unrelated topic.

@dghubble where we're coming from is that `cockroach demo` creates a _network service_ which can be reached from other computers in a local network. Think about your laptop in a coffeeshop or similar. We've built authentication in `cockroach demo` to ensure that it does not become a vector for malicious activity on your network to get "into" your computer.

What we can do is change `cockroach demo` to use an environment variable to configure the admin user/password to a static value. Would you find this useful?

**Comment by dghubble** [comment]
Yeah, an environment variable to set a user/password to a static valuable would make local development much nicer!

App developers would be able to start the demo node with a static username/password from an environment variable and listening on 127.0.0.1 (wouldn't mind if that was the default address, but we can set it via flags). That way a project could set up a username/password in local env files and any development scripts/integrations could use that known username/password. Plus the demo is in-memory which is great for these ephemeral development needs, where you probably throw away the db when not working on an app.

**Comment by knz** [comment]
@dghubble , over in #94323 we are ensuring that `cockroach demo` uses 1) a fixed directory `~/.cockroach-demo` to store its TLS certificates and 2) pre-generates a valid TLS client cert for the `root` and `demo` user.

Once the TLS configuration is fixed in this way, it would become possible to implement tests that use it directly, _without the need to fix the password_ -- no password is needed in the client when client certs are used to authenticate.

Would this help in your use case?

(Not saying we shouldn't work on password generation, but if we find that client cert authn works, we might recommend that instead.)

**Comment by dghubble** [comment]
@knz I haven't built your PR yet, but **yes** I think that would solve the difficulty. With the fixed directory and credentials, developers could use the demo as a local database for developing/testing, the connection string (without a password) to use in development would stay stable, and demo can be stopped and started more easily than the single node setup. I'm looking forward to this!

**Comment by dghubble** [comment]
And from the PR, it looks like this works better with `cockroachdb sql` as well, when a developer needs to inspect something directly in the local demo instance. 👍🏻
