### ISSUE TITLE
sql: update support for npgsql

### ISSUE THREAD

**Issue by dikshant** [cockroachdb/cockroach#92623]
Npgsql is on major version 6.0, we are only on 4.x. We should update our support and get Npgsql out of beta.
https://www.cockroachlabs.com/docs/stable/third-party-database-tools.html

Jira issue: CRDB-21889

Epic CRDB-17785

**Comment by dikshant** [comment]
After removing [`pg_advisory_xact_lock`](https://github.com/npgsql/npgsql/blob/main/test/Npgsql.Tests/TestUtil.cs#L189) from the create table statements used in npgsql tests and removing the three failed tests due to #94356. I was able to obtain the following test run log by running npgsql against CockroachDB 22.2.1.

As it stands:
```
Failed!  - Failed:   904, Passed:  2381, Skipped:   272, Total:  3557, Duration: 3 m 57 s - Npgsql.Tests.dll (net7.0)
```

[npgsql_full_test_run.log](https://github.com/cockroachdb/cockroach/files/10312080/npgsql_full_test_run.log)

**Comment by rafiss** [comment]
Nice results. Could you share some instructions onw how you set up the npgsql environment, and the command you used to run the tests?

**Comment by dikshant** [comment]
The steps are:

1. `git clone https://github.com/npgsql/npgsql.git`
2. Open the project using [VSCode](https://code.visualstudio.com/).
3. Install [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack) used for remote development.
4. Click this on the bottom: 
      <img width="198" alt="Screenshot 2023-01-04 at 3 03 36 PM" src="https://user-images.githubusercontent.com/9084804/210639771-95df9635-6c22-4220-9bfc-eabc997758ea.png">
5. Select reopen in container:
      <img width="1237" alt="Screenshot 2023-01-04 at 2 53 54 PM" src="https://user-images.githubusercontent.com/9084804/210639848-898826a2-599d-4865-ad52-eb236b058bf0.png">
4. Apply [this git diff](https://gist.github.com/dikshant/1b7c6e2698dcb496429d303687575e94).
5. Run: `dotnet test test/Npgsql.Tests` from the project root.
