### ISSUE TITLE
server: `raft` endpoint needs to take a predicate

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#9264]
This endpoint will internally fan out to all the nodes and collect information about all of the replicas. That means a lot of legwork. The returned JSON (on beta) is already 92MB in size.

For starters, it should be possible to query for a single RangeID.

**Comment by spencerkimball** [comment]
@BramGruneir has this already been addressed? Please either close, change the milestone, or fix it!

**Comment by bdarnell** [comment]
We have the single range ID version of this now. We need something else (like #13626) to get interesting/problematic ranges without loading everything at once, but not for 1.0.

**Comment by petermattis** [comment]
@BramGruneir Now that we have the interesting/problematic range page, is there anything left to do here?

**Comment by BramGruneir** [comment]
I think we're done.  Closing.
