### ISSUE TITLE
storage: Move check for mixed cluster IDs

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#9271]
We currently check for a mix of different cluster IDs in gossip in [`maybeGossipFirstRange`](https://github.com/cockroachdb/cockroach/blob/f48730d4d437c5b901dc8e8cd7b37bb9155fe848/storage/replica.go#L2873-L2880). This is the wrong place for it; all nodes should be watching for this problem and not just the ones that contain a replica of the first range. The check should probably be moved to a gossip callback on `KeyClusterID`, or maybe we should even be more aggressive and transmit the cluster ID early in the connection process to make sure we detect this case immediately.

**Comment by a6802739** [comment]
@bdarnell , maybe I could fix it now. However, I couldn't quite understand what you say. Do you mean move ` maybeGossipFirstRange` to callback in gossip?

**Comment by bdarnell** [comment]
Not all of it, only the lines that I [linked to](https://github.com/cockroachdb/cockroach/blob/f48730d4d437c5b901dc8e8cd7b37bb9155fe848/storage/replica.go#L2870-L2880). This should use `Gossip.RegisterCallback` to watch `KeyClusterID`. I think the callback should be registered in server/node.go.

**Comment by a6802739** [comment]
@bdarnell , got it. I'll have a try. thanks a lot.

**Comment by spencerkimball** [comment]
Closed by #14475
