### ISSUE TITLE
storage: replica queues need metrics

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#9272]
The replica queues need per-queue metrics:
- Number of replicas processed successfully
- Number of errors processing replicas
- Number of replicas in purgatory
- Replica processing time

Cc @cockroach/stability

**Comment by tamird** [comment]
We should probably move some of the existing allocator metrics to the
replicate queue.

**Comment by tschottdorf** [comment]
The metrics in #9398 aren't exposed anywhere.

**Comment by tschottdorf** [comment]
@knz is looking into getting this into Grafana. Suppose we should also add it to our ui.

**Comment by knz** [comment]
Fixed by https://github.com/cockroachlabs/production/pull/113.
