### ISSUE TITLE
streamingccl: lint failure on deprecation warning

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#92761]
lint_test.go:1751:
        pkg/ccl/streamingccl/streamclient/partitioned_stream_client_test.go:14:2: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details.  (SA1019)
    --- FAIL: TestLint/TestStaticCheck (974.77s)

Jira issue: CRDB-21955

**Comment by andyyang890** [comment]
I actually just opened https://github.com/cockroachdb/cockroach/pull/92760 to fix this so I'll claim this issue!
