### ISSUE TITLE
server/metric: No var for the node name

### ISSUE THREAD

**Issue by nictuku** [cockroachdb/cockroach#9280]
`http://<server>/_status/vars` doesn't have a variable with the local node name. It would be nice if it did. 

The` /_status/metric/local` handler has that as the top-level key name on the dictionary, so it's probably just a matter of creating a var for it.

Thanks!

**Comment by nictuku** [comment]
If you agree with the idea being proposed, feel free to assign this issue to me and I'll send a patch once I get authorization from work.

**Comment by mberhault** [comment]
Yup, that would be helpful. See #8674 filed a while back, I just haven't gotten to it yet. Do feel free to grab it.
