### ISSUE TITLE
monitoring: use fixed-size buckets in histograms

### ISSUE THREAD

**Issue by nictuku** [cockroachdb/cockroach#9281]
Cockroachdb currently only exports time-ranged latency histograms, i.e: the variables with _1m, 10m, 1h. 

I believe we also need absolute counters since the server started. The time-ranged variables aren't useful for programmatic monitoring and aggregation. 

For example, if you only export latency of requests seen in the last minute, how would  a monitoring tool know what to make of the latency if it only scrapes the server every 5 minutes? Or what if it scraped the server every 30 seconds? It would see repeated numbers, but wanted fresh numbers. The resulting numbers would be wrong.

We should export fixed latency buckets with counters (monotonically increasing) for how many requests feel into each bucket since the server started. Let the tool (prometheus or so) take care of averaging things out and aggregating them.

Of course you can still export the _1m _10m _1h variables, but please kindly consider adding the eternal buckets too :).

Thanks!

**Comment by nictuku** [comment]
If you agree with the idea being proposed, feel free to assign this issue to me and I'll send a patch once I get authorization from work.

**Comment by tschottdorf** [comment]
I believe this is equivalent to the discussion of `histograms` vs `summaries` in the [prometheus docs](https://prometheus.io/docs/practices/histograms/) (the prometheus endpoint is `/_status/vars`), in particular this part:

> Note the importance of the last item in the table. Let us return to the SLA of serving 95% of requests within 300ms. This time, you do not want to display the percentage of requests served within 300ms, but instead the 95th percentile, i.e. the request duration within which you have served 95% of requests. To do that, you can either configure a summary with a 0.95-quantile and (for example) a 5-minute decay time, or you configure a histogram with a few buckets around the 300ms mark, e.g. {le="0.1"}, {le="0.2"}, {le="0.3"}, and {le="0.45"}. If your service runs replicated with a number of instances, you will collect request durations from every single one of them, and then you want to aggregate everything into an overall 95th percentile. However, aggregating the precomputed quantiles from a summary rarely makes sense. In this particular case, averaging the quantiles yields statistically nonsensical values.

My impression is as well that we really want to export histograms, not summaries. I also think we're using summaries incorrectly - you'd always want to return the same quantiles. We return different quantiles every time you hit the endpoint:

```
// FillPrometheusMetric fills the appropriate metric fields.
func (h *Histogram) FillPrometheusMetric(promMetric *prometheusgo.MetricFamily) {
	// TODO(mjibson): change to a Histogram once bucket counts are reasonable
	sum := &prometheusgo.Summary{}

	h.mu.Lock()
	maybeTick(h)
	merged := h.windowed.Merge()
	for _, b := range merged.CumulativeDistribution() { // quantiles vary
		sum.Quantile = append(sum.Quantile, &prometheusgo.Quantile{
			Quantile: proto.Float64(b.Quantile),
			Value:    proto.Float64(float64(b.ValueAt)),
		})
	}
	sum.SampleCount = proto.Uint64(uint64(merged.TotalCount()))
	h.mu.Unlock()

	promMetric.Type = prometheusgo.MetricType_SUMMARY.Enum()
	promMetric.Metric = []*prometheusgo.Metric{
		{Summary: sum},
	}
}
```

`h` actually does contain buckets, so this shouldn't be a big change (but see #7896).

cc @mberhault

**Comment by nictuku** [comment]
It should not return quantiles, but a distribution with fixed buckets,
otherwise you can't aggregate data from different servers.

**Comment by nictuku** [comment]
(perhaps you meant that already, sorry if that was the case)

**Comment by tschottdorf** [comment]
Yep, that's what I meant. Thanks for putting that in clearer words than I did above.

**Comment by mberhault** [comment]
The existing `_1m`, `_10m` etc... metrics are really for use by the admin UI. We've yet to add a latency metric that works well with prometheus. We definitely need it though.
And yes, we definitely want histograms with fixed buckets. We just need to make sure we pick the right buckets.

**Comment by petermattis** [comment]
@mberhault Our prometheus endpoint reports fixed size buckets for histograms. Is there anything left to do here?

**Comment by spencerkimball** [comment]
@mberhault this appears fixed. I'm closing. Reopen if you think there's remaining work.
