### ISSUE TITLE
multitenant: create test knob to force stale node cache

### ISSUE THREAD

**Issue by ecwall** [cockroachdb/cockroach#92823]
`NodeDescs` cache is eventually consistent so we should test when it becomes stale.

See https://github.com/cockroachdb/cockroach/pull/92787/files#diff-65f052c474cf6d0a03a10a28dfb98c38f2584b7bf340039c1762124031ca07bfR3723

Jira issue: CRDB-21992

Epic CRDB-26687

**Comment by yuzefovich** [comment]
Hey @ecwall, do you recall the context for why you opened this issue? The issue description references `crdb_internal.ranges_no_leases` virtual table, but I don't see how it's connected to `NodeDescs` cache being stale (other than the virtual table will also have stale information in `replicas` column).

**Comment by yuzefovich** [comment]
Closing this as non-issue.
