### ISSUE TITLE
metrics: group variables that should be the same when possible

### ISSUE THREAD

**Issue by nictuku** [cockroachdb/cockroach#9282]
Hi. Just a minor naming recommendation about your prometheus metrics.

Variables that are describing different outcomes for the same event source should share the same variable, but use different labels. Example:

exec_success_count
exec_error_count

Should be:
exec_status{status=error} 
exec_status{status=success}
 
(Also no need to say _count since the metric type already says that)

Having only one variable for this would let users type only one thing in a graph plotter then get all time series.

There are several similar metrics like that.  e.g:
rocksdb_block_cache_hits
rocksdb_block_cache_misses

If you're user exploring variables, you'd prefer to have a single var.

**Comment by nictuku** [comment]
If you agree with the idea being proposed, feel free to assign this issue to me and I'll send a patch once I get authorization from work.

**Comment by tschottdorf** [comment]
cc @mberhault

**Comment by mberhault** [comment]
Thanks for the issue @nictuku. I've slowly been refactoring our metrics, and the main chunk left is proper naming nomenclature.
I'm closing this bug in favor of  #9289 which includes a few more details about what I want to do.
