### ISSUE TITLE
sql: index recommendations should use qualified table names

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#92830]
**Describe the problem**

![image](https://user-images.githubusercontent.com/461296/205095748-7f78bd75-9cab-461f-8cc8-70e3936ddd4d.png)

Please see this thread

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

Create a database with a user defined schema and generate index recommendation, hitting apply in the UX will fail because it expects a default schema.

If possible, provide steps to reproduce the behavior:

**Expected behavior**
The apply should succeed or the recommendation should include the full path database.schema.table in the create step. The index creation works as is in the CLI within the context of the database.

**Environment:**
 - CockroachDB version: 22.2.0.rc.3
 - Server OS: Linux
 - Client app: DB Console

**Additional context**
What was the impact?

Jira issue: CRDB-21994

**Comment by mgartner** [comment]
We need to use a fully- or schema-qualified name here: https://github.com/cockroachdb/cockroach/blob/003550cbe2b5b75af565a2cdf47c609580f9905f/pkg/sql/opt/indexrec/rec.go#L254.
