### ISSUE TITLE
ui: transaction insights pages crash when sql stats tables are reset

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/cockroach#92831]
The Transaction Insights pages crash when SQL stats tables `crdb_internal.statement_statistics` and `crdb_internal.transaction_statistics` are reset because these pages use these tables as a data source for transaction statement information.

In specific, the frontend SQL-over-HTTP API requests for transaction insights include [a query to the `crdb_internal.transaction_statistics` table](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L121) that gathers the statement fingerprint IDs for a given set of transaction fingerprint IDs (originally pulled from the `crdb_internal.transaction_contention_events` table), and [a query to the `crdb_internal.statement_statistics` table](https://github.com/cockroachdb/cockroach/blob/master/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L159) that gathers the statement strings for a given set of statement fingerprint IDs, to be mapped backed to the transaction fingerprint. We do not currently handle the case where there are no transaction or statement stats for a given insight's transaction fingerprint ID.

To resolve this issue in the short term, we should populate the query field for a given transaction insight event with a placeholder string ("SQL stats not available" or something to that effect) in the case where no stats exist.

In the longer term, we plan to move away from querying the `crdb_internal.transaction_contention_events` table altogether, in favor of the transaction insight information available in the `cluster_execution_insights` table (or a similar transaction-level table). This table contains the statement strings for all recorded executions, which will allow us to remove the dependency on internal statement statistics tables.

Jira issue: CRDB-21995

**Comment by koorosh** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/98222

Could reproduce this issue on 19db7fd3b788da1dfde2259701d7714eae597016
Fix applied for `22.2`, `23.1` and `master`
