### ISSUE TITLE
all: deal with traces crossing goroutine boundaries

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#9284]
We currently run a half-hearted attempt to not pass `opentracing.Span` across goroutine boundaries. The reason is that this often leads to using the trace after it has been finalized, which isn't inherently forbidden but is certainly not desirable, especially when using the options which enable a `sync.Pool` for the trace spans.

I think that at the current stage, we should allow passing traces over goroutines. One of the basic properties of a `context.Context` is that it's thread-safe, and we're essentially breaking that property.
We should simply eat the allocation churn (for now), and set `opts.DebugAssertUseAfterFinish = false` (as well as `opts.EnableSpanPool = false`, which is already set implicitly) and remove places in the code that dance around this limitation.

This will sometimes lead to late events not being recorded (since recording happens only once), but this should be rare enough to not matter.

What we should be doing however is fork from the trace span for use in the goroutine, or the resulting event log (which would contain two serial executions interleaved) will not be idiomatic. Perhaps some tooling for this is necessary (perhaps in *Stopper).

**Comment by RaduBerinde** [comment]
I think the requirement to never allow spans to be used across goroutine boundaries is too strict. What we really are about is no use after finish. So it should be perfectly acceptable to pass it to goroutines that we know will complete before the span finishes. For example if I refactor a piece of code and move something in a goroutine but I still wait for that goroutine to finish, I don't suddenly have a new requirement to fork the span.

But for situations where we just fire off some async task and don't wait for it, absolutely. Perhaps we can have wrappers like `RunAsyncTaskCtx(ctx, func(context.Context))` that does it for us and passes the new context to the callback.

When you say "fork the span", what is that exactly in terms of API? Creating a new span using `FollowsFrom`?

**Comment by andreimatei** [comment]
I think it depends on the tracer is even logging concurrently to a span is racey or not, right? I forgot if the basictracer's span synchronizes accesses?

In any case, Tobi, why exactly do you want to remove this restriction and pass spans left and right? Is it really so onerous to "fork the span"? There's also the option to simply remove the span from the goroutine's ctx, too.

**Comment by bdarnell** [comment]
As an example of how error-prone the current situation is, we have a [comment](https://github.com/cockroachdb/cockroach/blob/97b7e51286043065155d0da3acb07f924aafc59f/storage/store.go#L1528) warning against the use of context in an async task, but 64b949994 started using the context in the task anyway. We don't have good idioms for forking the span and requiring that the forked version is used. Maybe if RunAsyncTask took a context and passed a forked context into the task function?

**Comment by RaduBerinde** [comment]
> Maybe if RunAsyncTask took a context and passed a forked context into the task function?
Yes, that was my suggestion too. Seems easy enough, will work on that.

**Comment by tschottdorf** [comment]
> I think it depends on the tracer is even logging concurrently to a span is racey or not, right? I forgot if the basictracer's span synchronizes accesses?

`opentracing.Span` allows concurrent access, so it isn't illegal, just makes it impossible to run with a buffer pool underneath because of use-after-recycle.

> In any case, Tobi, why exactly do you want to remove this restriction and pass spans left and right? Is it really so onerous to "fork the span"? There's also the option to simply remove the span from the goroutine's ctx, too.

Because it's impossible to maintain. I do want to encourage forking the span whenever we go through a goroutine, but I don't want not doing that to be a serious transgression (as it would be with a buffer pool).

> When you say "fork the span", what is that exactly in terms of API? Creating a new span using FollowsFrom?

`FollowsFrom` or `ChildOf` - probably depends on the individual situation, but maybe we'll just go with the one that seems saner on average for now.

**Comment by petermattis** [comment]
@tschottdorf, @RaduBerinde Is there anything still to do here?

**Comment by RaduBerinde** [comment]
No, I think we have established helper methods and patterns for forking spans when necessary.
