### ISSUE TITLE
multi-tenancy: option to log out of current tenant vs all tenants

### ISSUE THREAD

**Issue by Santamaura** [cockroachdb/cockroach#92855]
**Is your feature request related to a problem? Please describe.**
Follow up from https://github.com/cockroachdb/cockroach/pull/92694. Currently logout on a multi-tenant cluster will just log out of all tenants. 
**Describe the solution you'd like**
If there is a need for it, there should be a way to log out of the current tenant or log out of all of them.

Jira issue: CRDB-22002

Epic CRDB-24590

**Comment by Santamaura** [comment]
If we do need this option, some design will be needed for the logout ui (e.g. a dropdown with 2 options?)

**Comment by Santamaura** [comment]
@thtruo do you have any thoughts on good use cases for this option? IIRC we were struggling to come up with some in the meeting with Dongni.  If not, then maybe we should put this into backlog/close this.

**Comment by thtruo** [comment]
Thanks @Santamaura. We just synced offline. We acknowledge that this use case (logging out of specific tenants) is not necessary for 23.1, given that any 23.1 cluster choosing to enable MT (minority of clusters) will only contain 1 app tenant and 1 system tenant. We can re-evaluate this for 23.2 MT clusters.

**Comment by maryliag** [comment]
No longer a priority
