### ISSUE TITLE
Improve the statement bundle collection warning message to clearly call out performance implications 

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#92879]
This issue tracks enhancing the console pop-up dialog when enabling the statement diagnostics bundle. Executions of the same statement fingerprint can run **significantly** slower than usual when diagnostics are activated. Specifically we should update the main message:

<img width="791" alt="image" src="https://user-images.githubusercontent.com/81193618/205209008-17f57873-289d-445d-8299-e61391255bed.png">

Jira issue: CRDB-22018

**Comment by hand-crdb** [comment]
Please update the docs as well.

**Comment by maryliag** [comment]
Warning were added to the modal.
cc @florence-crl if there are any updates required to the docs

**Comment by florence-crl** [comment]
created docs issue: https://cockroachlabs.atlassian.net/browse/DOC-7624
