### ISSUE TITLE
Table fails to restore from backup when schema is renamed then recreated

### ISSUE THREAD

**Issue by jonstjohn** [cockroachdb/cockroach#92882]
**Describe the problem**

When a schema is renamed then recreated, tables from original schema cannot be restored to the new schema.

**To Reproduce**

This is easily reproduced locally using `cockroach start-single-node` then executing the follow SQL commands in the `cockroach sql` client. In this example, the database `d` and schema `d.s` are created. After the backup is made, the schema is renamed to `s_old` and the schema `d.s` is recreated. Restoring the table fails.

```
CREATE DATABASE d;
CREATE SCHEMA d.s;
CREATE TABLE d.s.t (id uuid);
BACKUP INTO 'nodelocal://self/backup';
ALTER SCHEMA d.s RENAME TO s_old;
CREATE SCHEMA d.s;
SHOW BACKUPS IN 'nodelocal://self/backup';
-- replace the path with the one from SHOW BACKUPS
RESTORE d.s.t FROM 'nodelocal://self/backup/2022/12/01-161355.38';
ERROR: relation "t" already exists
SQLSTATE: 42P07
```

**Expected behavior**

The table should be restored to the newly created schema.

**Additional data / screenshots**

None

**Environment:**
 - CockroachDB version 22.1.6
 - Server OS: Any
 - Client app: `cockroach sql`

**Additional context**

None

Jira issue: CRDB-22019

**Comment by stevendanna** [comment]
Sometime between 22.1.6 and 23.1 this was fixed.
