### ISSUE TITLE
monitoring: revamp metric names

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#9289]
The last big chunk left in the metrics refactor is renaming metrics. Some things to keep in mind:
- names should be somewhat descriptive
- all metrics should have a help string
- labels should be used when metrics are different outcomes of the same thing
- types should not be included in the name

For example, the following metrics show all 4: `exec.success-count` and `exec.error-count`

Instead, we should use something along the lines of: `node.calls{status=success}` and `node.calls{status=error}`

**Comment by tamird** [comment]
From #9822: I think we should use colons in prometheus names where we use periods on CRDB metric names, to indicate hierarchies. @mberhault says that colons are typically used to specify granularity, but e.g. https://prometheus.io/blog/2015/06/18/practical-anomaly-detection/ uses them also to specify hierarchies (e.g. colons are used for both purposes for the metric `instance:latency_seconds:mean5m` in that article).

**Comment by mberhault** [comment]
the colons in the example are used to indicate aggregations and operations used in recorded rules, keeping the original name, and indicating with colons what was done to it through the rule process. This is the recommended style. We're welcome to ignore it, and depending on the hierarchies we have, we may want to.

However, some of our "deep" metrics would be better combined using labels rather than making more metrics with different names.

Anyway, I'll keep this in mind when addressing this issue.

**Comment by jason-riddle** [comment]
To add on to this, is there any reason why 'cockroachdb' is not prepended before the metric name? I'm scraping multiple targets and I've just gotten used to the following format of 'cockroachdb_<metric>'.

**Comment by spencerkimball** [comment]
@mberhault ping. Especially with regards to the 1.0 milestone.

**Comment by mberhault** [comment]
1.0 is definitely the right milestone if we're going to rename a bunch of metrics.
This is mostly a tedious process where each metric needs to be examined for its true meaning, then appropriately named. I'll try and draft some simple guidelines for metrics though, that's kind of the first step.

**Comment by mberhault** [comment]
Names fixed for a few metrics and help messages added to all.
The rest is a bigger refactor and can wait until 1.1, it's not urgent.

**Comment by mberhault** [comment]
This is incredibly old, and at this point changing metric names is asking for trouble. Closing.
