### ISSUE TITLE
TestUnused not working on local machine

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#9291]
caught this unused function on CI, but it would have been nice to see it on my local machine. Can't see why it wouldn't fail on my machine.

https://circleci.com/gh/cockroachdb/cockroach/22575

**Comment by tamird** [comment]
Did you run `make check` locally? `TestUnused` is not a normal test.

I'm going to close this with the assumption that you ran `make test` but not `make check`. Please reopen if I'm mistaken.
