### ISSUE TITLE
cdc: changefeeds dashboard in DB Console references missing metrics

### ISSUE THREAD

**Issue by dhartunian** [cockroachdb/cockroach#92924]
The changefeeds dashboard references metrics that no longer exist:

https://cockroachlabs.slack.com/archives/C02A60BAJHL/p1669741022312379

The metrics `emit_nanos` and `flush_nanos` need to either be removed or updated to reference new metric names. They were removed in this PR: https://github.com/cockroachdb/cockroach/pull/72111

Jira issue: CRDB-22055

Epic CRDB-9181

**Comment by amruss** [comment]
@samiskin we can close this out right?

**Comment by amruss** [comment]
Closing due to: https://github.com/cockroachdb/cockroach/pull/101790
