### ISSUE TITLE
sql: backup/restore/ingest 2016Q4 work

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#9293]
Implementation of https://github.com/cockroachdb/cockroach/pull/8966

@dt 
- [ ] Mark fks/checks as unvalidated
- [ ] Check constraints on restored tables
- [ ] Backup only certain databases

@paperstreet
- [ ] Verify kv checksum in WriteBatch impl
- [ ] Finalize sst format
- [ ] Attach an encoding version to backups in case the encoding changes
- [x] Use WriteBatch in implementation of Ingest
- [x] Ingest command
- [x] Presplit ranges during restore
- [x] (Maybe) Use snowball tracing to debug performance problems
- [ ] Test for table with secondary indexes
- [ ] Support interleaved tables
- Cleanup
  - [x] Review TODOs in backup/restore code
  - [x] Run the backup command in one request now that distsender is parallel
  - [x] Explictly check for inline keys in MVCCIncrementalIterator
  - [x] Throw an error on interleaved table restore
  - [x] Move ExportKeysBatch to a submessage of ExportKeysResponse
  - [x] Move the BackupRestoreDescriptors to ccl
  - [x] Throw error if an incremental backup is run for greater than the gc threshold
  - [x] Empty range checks to fail fast in Ingest/WriteBatch

@mjibson 
- [ ] Get backup working stably on the Delta cluster
- [ ] Use TableReader (instead of RocksDB+AddFile) to iterate an sstable
- [ ] Actually error on FKs and CHECK constraints in Import

**Comment by paperstreet** [comment]
I'll finish fleshing this out once the rfc is merged.

**Comment by mjibson** [comment]
The difference between restore and bulk ingest is that bulk ingest takes data not in restore format and converts it to that format, right? So for example the "add secondary indexes during bulk ingest" bullet would mean some process computes the sstable data and secondary indexes for some table.

What does "merge tiny segments on ingest" mean?

**Comment by danhhz** [comment]
Superceded by https://github.com/cockroachdb/cockroach/issues/12555
