### ISSUE TITLE
c2c: `CREATE/DROP/ALTER/SHOW TENANT` do not support subqueries for specifying tenant name

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#92958]
The tenant name is an `Expr` but there is some work to be done to accept sub-queries. Opaque nodes are sent with a RejectSubqueries bit over here - https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/opaque.go#L44 so we’ll have to build out some opt-in logic.  Once we resolve that I think we’ll need to put this method https://github.com/cockroachdb/cockroach/blob/fc1fa24f38a0b4f1e60bd079f231de37a2e842bd/pkg/sql/analyze_expr.go#L29 on the PlanHookState to evaluate the subquery.

Jira issue: CRDB-22067

Epic: CRDB-18749

**Comment by knz** [comment]
dup [#95266](https://github.com/cockroachdb/cockroach/issues/95266).
