### ISSUE TITLE
sql: allow CTEs in UDFs and SPs

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#92961]
CRDB v22.2 does not support UDFs with CTEs in UDF bodies. This is a surprising limitation that we should lift.

CRDB-19884

Jira issue: CRDB-22069

**Comment by lnhsingh** [comment]
@rytaft is this the same as https://github.com/cockroachdb/cockroach/issues/93049?

**Comment by mgartner** [comment]
@lnhsingh no, these are separate issues. This issue is specifically for supporting a CTE (recursive or non-recursive) in a UDF, i.e., a `WITH` clause in the body of a UDF. For example:

```sql
CREATE FUNCTION f() RETURNS INT LANGUAGE SQL AS $$
  WITH t AS (SELECT 1 AS a)
  SELECT a FROM t
$$;
```

#93049 tracks recursive UDFs, e.g., a UDF that invoked itself in the function body, or two UDFs that are mutually recursive (function `a` calls function `b`, and `b` calls `a`). For example:

```sql
CREATE FUNCTION f(i INT) RETURNS INT LANGUAGE SQL AS $$
  SELECT CASE
    WHEN i = 0 THEN 0
    ELSE i + f(i-1)
  END
$$;
```

**Comment by lnhsingh** [comment]
Thanks for the clarification, @mgartner!
