### ISSUE TITLE
cdc: handle stable functions that query system tables

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#92963]
Some stable functions run a SQL query as part of their execution. When we allow stable functions in changefeed expressions, we should probably disallow those functions, or at least warn about them and ensure they get accounted for properly (resources, request units, metrics).

Jira issue: CRDB-22071

Epic CRDB-17161

**Comment by miretskiy** [comment]
Only white listed functions are allowed -- afaik... So, whatever is listed in functions.go is okay, and the rest is a no-go...
Is this issue still an issue?

**Comment by miretskiy** [comment]
Thinking more about this issue -- it appears that if we allow stable functions to be used,
then, I think it's fine -- whether or not these functions make expensive external calls. 
Ultimately, we should let the users decide what they want -- and hopefully, over time, provide
observability into their choices via explain changefeed.
