### ISSUE TITLE
cdc: perform type resolution before function resolution and validation

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#92962]
Currently cdceval doesn't know what type a clause in an expression is going to be while it's resolving functions and validating the expression. That means we don't know which overload a function or operator is, and what is being cast to what, which is problematic mainly because they can have different volatility and require different session information to be serialized. We should perform these operations in the same order as the normal query planner so that these issues don't occur. Also, once we're allowing schema changes we should redo it all every time the schema changes.

Jira issue: CRDB-22070

Epic CRDB-17161

**Comment by miretskiy** [comment]
is it still true (with optimizer work being merged as we speak)?
