### ISSUE TITLE
schema: multi-region costfuzz and UQO tests frequently hang in the presence of a stuck DDL DROP

### ISSUE THREAD

**Issue by cucaroach** [cockroachdb/cockroach#93010]
Examples:

- #90683
- #92753

Simply re-enabling DDL in newMutatingSmither should be enough to re-create.    This also happened back when these tests where 4 nodes but the problem was only ever seen with the seed-multi-region variants.

Its not clear yet if the DDL hang causes the tests to timeout or is just coincident.  There may be more than one bug here but this issue is purely about the DDL DROP hang, we plan to disable DDL and see how that affects the tests, hopefully in the future we can re-enable it, maybe in a meta-morphic fashion.

Jira issue: CRDB-22105

**Comment by ajwerner** [comment]
Some discussion https://cockroachlabs.slack.com/archives/CARM0PTK4/p1669932115073349.

**Comment by fqazi** [comment]
The problematic DDL on the connection corresponds to the following:
```
ALTER DATABASE defaultdb SET PRIMARY REGION "us-west1";
ALTER TABLE seed_mr_table SET LOCALITY REGIONAL BY ROW;
INSERT INTO seed_mr_table DEFAULT VALUES;```

**Comment by fqazi** [comment]
This also corresponds with the tests that are failing, which use seed-multi-region, will investigate this much deeper tomorrow. But there is a clear correlation here, something is not handled transactionally correctly for this sequence.

**Comment by postamar** [comment]
Reopening to not forget about backport.

**Comment by fqazi** [comment]
Closing now that the backport is merged
