### ISSUE TITLE
cluster-ui: support large response sizes for sql-over-http endpoints

### ISSUE THREAD

**Issue by THardy98** [cockroachdb/cockroach#93065]
**Is your feature request related to a problem? Please describe.**
Currently, the sql-over-http endpoint provides a modifiable request parameter `max_result_size` to configure the size of the response sent back from the server (the default value being 10KiB). Responses that exceed the configured limit will return the maximum number of result rows that can fit within the limit, as well as an error (indicating that the query results exceed the limit). 

Currently, we do not have a good way of handling endpoints that can return data sizes larger than the configured limit. The current remedy for this issue is to simply increase the limit for the endpoint, which is not scalable.

As a solution, we could add **pagination** logic to queries used in our endpoints, rectifying the need to continually up the response limit and load the complete (potentially large) result set in browser memory.

Additionally, there are a number of sql-over-http endpoints that do not support loading of partial results when encountering an error due to large result size. We would like to add logic to allow for rendering of partial results, as has already been done in:
https://github.com/cockroachdb/cockroach/pull/90862

Jira issue: CRDB-22141
Epic: [CRDB-20388](https://cockroachlabs.atlassian.net/browse/CRDB-20388)

**Comment by THardy98** [comment]
Relevant: https://github.com/cockroachdb/cockroach/issues/75510

**Comment by kevin-v-ngo** [comment]
Up next to align with the following issue https://github.com/cockroachdb/cockroach/issues/75510

**Comment by maryliag** [comment]
No longer a priority
