### ISSUE TITLE
perf: optimize stats handling for Replica.setAppliedIndex

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#9306]
`Replica.setAppliedIndex` writes the per-Replica `RaftAppliedIndexKey` and `LeaseAppliedIndexKey` index keys. These keys are currently considered part of the Replica's MVCC stats even though their contribution is minimal and almost a constant. Not tracking them in MVCC stats would allow use of "blind" puts which avoid reading the previously stored value. Given that `setAppliedIndex` is called on every write, it is worthwhile optimization to avoid that read. Removing those keys from MVCC stats seems to require a migration which is a headache.

An alternative to removing those keys from MVCC stats is to optimize how we maintain their stats. In particular, it seems feasible to specially handle the stats update for those two keys given that they are always updated with `Replica.raftMu` held.

**Comment by petermattis** [comment]
I just experimented with this and removing tracking of MVCC stats for `RaftAppliedIndexKey` and `LeaseAppliedIndexKey` improves `block_writer` performance on a single-node cluster by 10%. That's quite a bit higher than I expected. Probably has something to do with not forcing the batched to be flushed.

**Comment by tschottdorf** [comment]
We could make those two values fixed-width encoded. We already make sure they're always written, so if we take their stats into account the first time (`writeInitialState`) we could always blind-put them.

**Comment by petermattis** [comment]
How do you change the existing on-disk format of these keys with an irritating migration?

Btw, the 10% improvement was for a `1m` run. I also tried a `5m` run where `block_writer` reaches a steady state and the improvement was only 5%. Still worth doing, just not as dramatic.

**Comment by tschottdorf** [comment]
You move the keys elsewhere and write a migration that copies each old found key to the corresponding new found key. Not too dramatic. I agree that we shouldn't pass on a 5% improvement, but I think we should pile a few of them up and migrate them in properly and not "make it happen" at the expense of code clarity.

**Comment by petermattis** [comment]
If we're going to rename the `RaftAppliedIndexKey` `LeaseAppliedIndexKey` keys, then we could just remove accounting for them in MVCC stats completely. Those keys (+ their values) currently consume 58 bytes. That's a fixed and inconsequential size per range. Let me explore this approach. It might not be so bad. Probably the hardest part will be writing a test.

**Comment by petermattis** [comment]
Not tracking stats for `RaftAppliedIndexKey` and `LeaseAppliedIndexKey` is quite irritating because it would require special casing `store.ComputeStatsForRange` in a quite awkward manner. I think the approach in #9993 would be preferable. The other option remaining is to ensure that the value for `RaftAppliedIndexKey` and `LeaseAppliedIndexKey` is a fixed size. Let me explore that further.

**Comment by petermattis** [comment]
I took a look at changing the value storage for `RaftAppliedIndexKey` and `LeaseAppliedIndexKey` to a fixed-width encoding. This requires adding a new tag to `roachpb.Value`, performing a migration to move all of the existing `{Raft,Lease}AppliedIndexKey` values from their current encoding to the new encoding and testing that migration. My impression after getting part way down that path is that the approach in #9993 is simpler. That PR doesn't require a migration and doesn't introduce a new `roachpb.Value` tag that has only a single use case.

**Comment by tschottdorf** [comment]
> My impression after getting part way down that path is that the approach in #9993 is simpler.

It's simpler for you to slap that in the codebase now and move on to other things, but it's not simpler for everyone else. Can we not go back to this mode of micro optimizing just yet and if we absolutely have to, can we do it sustainably? Apologies for the direct wording, but I question the priority of this change. We've already gone through a cycle of ill-advised micro-optimizing and the similar (though then, stronger) opposition I gave then wasn't registered at all. Good to track those fruit, not good to compulsively pick them.

**Comment by bdarnell** [comment]
We do need to be wary of micro-optimizing, but 5% is a pretty good increase and this seems isolated enough that I don't really mind the fact that it's a bit of a hack. If we had better infrastructure for doing migrations then it might be worth using it, but I don't think this change justifies the extra work to do proper migrations right now. (we can always introduce a migration later)

**Comment by tschottdorf** [comment]
Ok, but we'll have storage layer migrations come up in the near future that this could be folded into (thinking of prop eval kv concretely)? What's the rush?

**Comment by petermattis** [comment]
Apologies if it seems like I'm trying to rush in this optimization. That was not my intention. My settling on the approach in #9993 was due to a variety of factors, primarily that I think it is the safest approach. Anything that involves a migration needs to be more thoroughly tested and gives me worries that we'll encounter situations in production that foul up the migration and lead to badness.

**Comment by tschottdorf** [comment]
I see that point (safety) but given this project's history, I'm highly suspicious of everything that puts gotchas in the code, no matter how innocuous they may seem at the time of writing. At this stage in the project, I've rarely worked on something thinking "gosh, I wish the block writer were 5% faster". More often, I waste time trying to understand some optimization or worse, fixing it.

My preference would be to accrue and understand some of these potential optimizations and then prioritize getting them in for a focused period of time (similar to a stability push), in the order in which they matter. That has the benefit of a bigger picture available when the code goes in, is in line with the Q4 OKRs (understanding where the time goes), and while perhaps the PR you prepared is exactly the one we will commit at that future point in time, I *think* storage migrations may not look that scary at that point, or may happen at convenient points for inserting performance improvement migrations as well. There's also hope that we will use the time between to actually *measure* our performance (in the wild) better than we do now (i.e. not well/at all),

That said, with you and Ben both in favor of getting this in now, I'm ok if we just agree to disagree and you go ahead (assuming everyone else doesn't care one way or the other).

**Comment by petermattis** [comment]
> I'm highly suspicious of anything that puts gotchas in the code, no matter how innocuous they may seem at the time of writing.

That's quite a high bar for a change to clear.

FWIW, I think storage migrations will always be scarier than optimizations that result in the same on-disk format. 

I'm going to address the comments on #9993 but will hold off on merging until either you give a thumbs up or disappear to South America.

**Comment by bdarnell** [comment]
> FWIW, I think storage migrations will always be scarier than optimizations that result in the same on-disk format.

This is my view as well. #9993 needs some more comments to ensure our future selves will be able to tell what's going on, but when we can preserve the on-disk format (and it's not unduly complex to do so), that's better than introducing a migration (even if, as anticipated, adding migrations gets easier)

**Comment by tamird** [comment]
Storage migrations will be scary for a time, but we're undoubtedly going to
do them, so it's not clear to me that this is a coherent argument in favour
of avoiding them at the expense of introducing "gotchas".

I haven't reviewed this change, but I share Tobias' concerns.
