### ISSUE TITLE
c2c: backfill existing tests with `crdb_internal.fingerprint` to verify correctness

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#93078]
With #89336 complete, all existing and future roach/unit tests in the c2c replication package should use fingerprinting to verify correctness. This is a tracking issue for changes to existing tests to add fingerprinting. 

Epic: CRDB-21957

Jira issue: CRDB-22146

**Comment by msbutler** [comment]
i looked through our c2c unit tests (in particular our tests in `replication_stream_e2e_test.go` and i think we've backfilled the fingerprinting commands sufficiently. In particular from https://github.com/cockroachdb/cockroach/pull/98671
