### ISSUE TITLE
the glog flags are broken

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#931]
this is due to the change from go-commander to cobra.

basically everything shown by `./cockroach listparams` isn't working any more.

* we need to mirror glog's flags to cobra and after parsing those flags, store them with the flag package. i think `flag.Set(name, k, v)` can be useful here. Then `flag.Parse()` when they're all updated.
* note that listparams includes all the test flags - that suggests that we're compiling in the test package
in our real code. probably that happens with some of the exported test functions that we pass a *testing.T to - we should re-evaluate whether that's a good idea.
* listparams should list cobra's flags, not the others. but i suspect this is a good moment to ditch listparams - all flags should be explained by the actual help.

**Comment by tschottdorf** [comment]
maybe we can get away with just calling `flag.Parse()` (assuming we add the glog flags we want to cobra and there's no issue with `-` vs `--`) on our arguments. we might be replacing glog anyways so it's not worth too much hassle. but we definitely want `./cockroach start .... --vmodule=multiraft=5` and its comrades to work.

**Comment by petermattis** [comment]
@tamird is tackling the accidental inclusion of "testing" into the main cockroach binary. See #927.

I'm going to fix the glog flag brokenness. I'm also planning on getting rid of `listparams` as it no longer serves a purpose now that the individual command help displays the associated flags (e.g. `cockroach help start` lists all the start specific flags).
