### ISSUE TITLE
TestClusterFlow leaks goroutines

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#9310]
Seems like there's still a leak in distsql.

Add a `defer leaktest.AfterTest(t)()` and run 
```make test PKG=./sql/distsql/ TESTS=TestClusterFlow```

**Comment by andreimatei** [comment]
and also `TestServer`, but that one I can only repro with `testrace` :S

**Comment by RaduBerinde** [comment]
Hm.. this was working fine a couple weeks ago (with the leak tests). I took a look and some of the leaks are Workers which makes no sense because we are deferring `Stop()`. My hunch is that something changed in TestCluster and the stopper is no longer wired correctly.

**Comment by RaduBerinde** [comment]
Ah, it's related to a few existing uses of `RunWorker` which can run after the stopper has stopped. There is no check for this in the stopper. In the instances where I see a leak, I also see "stop has been called" very early in the test, no idea why. Still investigating.

**Comment by RaduBerinde** [comment]
You bastard:
```
 func testGetDecodedRows(
  	t *testing.T, sd *StreamDecoder, decodedRows sqlbase.EncDatumRows,		  	t *testing.T, sd *StreamDecoder, decodedRows sqlbase.EncDatumRows,
  ) sqlbase.EncDatumRows {		  ) sqlbase.EncDatumRows {
 +	defer leaktest.AfterTest(t)()
```

This is used internally by TestClusterFlow and TestServer.
