### ISSUE TITLE
roachprod: disable ext4 reserved space

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#93120]
The `/mnt/data` file system is created using default `ext4` options, which reserve 5% of blocks for the root user:

```
$ sudo tune2fs -l /dev/nvme0n1
[...]
Block count:              98304000
Reserved block count:     4915200
[...]
```

We should change it to create the filesystem without any reserved space, so that CockroachDB can use all of it.

Jira issue: CRDB-22172

**Comment by erikgrinaker** [comment]
CC @pavelkalinnikov

**Comment by srosenberg** [comment]
> We should change it to create the filesystem without any reserved space, so that CockroachDB can use all of it.

@erikgrinaker There is probably a good reason behind this system default. I haven't yet studied (the reason), but I am assuming this sets aside some space for things like system logs. It also appears to be a buffer against fragmentation although less important for `ext4`. So, my question is, should we really be messing with this default as opposed to provisioning a larger drive, where needed? Also, it's unlikely that a majority of self-hosted customers would _not_ be using this default, right?


[1] https://unix.stackexchange.com/a/7965

**Comment by erikgrinaker** [comment]
I think the main reason is to leave some space for the root user to run emergency operations, similar to CockroachDB's ballast file. Regular user accounts can otherwise use arbitrary amounts of disk space. For this issue, we're specifically interested in bumping the `/mnt/data` mount, not the system disk.

>So, my question is, should we really be messing with this default as opposed to provisioning a larger drive, where needed?

No strong opinion, since mosts tests aren't running anywhere near the disk capacity. But it added a bit of confusion when debugging a test failure that did run out of disk, since the graphs showed the node still had 5% remaining. Your call, feel free to close this out.

>Also, it's unlikely that a majority of self-hosted customers would not be using this default, right?

🤷‍♂️ I used to tweak this limit back when I was working in operations, at least. On a 4 TB drive, this "wastes" 200 GB, which I suppose isn't negligible. CockroachDB has its own 5% disk space limit, which will shortly be placed on top of the 5% ext4 reserved space (#93178), totalling 10% reserved disk space or 400 GB.

**Comment by andrewbaptist** [comment]
I looked at this and realized we are not setting the `-i bytes-per-inode` parameter. The default value (16K) uses about 1/64th ~ 1.5% of the file system since each inode is 256 bytes. Pebble creates much larger files so we are in no danger of running out of inodes. A change here, like making it 8x bigger (128KB) is very safe and saves almost all the inode space. 

The way to think of the parameter is "what is my average file size". The filesystem needs to reserve up front for the maximum number of files it will ever create.

I'll add a note to: https://github.com/cockroachdb/docs/issues/10630 as well.
