### ISSUE TITLE
sql: writing a secondary index is too slow

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#9319]
#9149 discusses the performance impact of schema changes on write performance (decrease in qps from 1800 to 250). But once an index is added, the qps returns to only around 400. One expects a decline in performance but not such a drastic one (1800 -> 400 qps). Using an interleaved index should improve performance, but this is still worth investigating.

**Comment by petermattis** [comment]
@spencerkimball's work on parallelizing `DistSender` will help here. When you add a secondary index we're currently performing 1+N (with N secondary indexes) serial writes in `DistSender` (assuming the primary data and the secondary index data are on separate ranges). This doesn't account for all of the performance loss, but sending those writes in parallel will certainly help.

**Comment by vivekmenezes** [comment]
Yeah, the semantics of Batch is that the requests in the batch can be
processed in parallel.

**Comment by spencerkimball** [comment]
Addressed in #9197
