### ISSUE TITLE
kvserver: sep-raft-log: extract replica creation engine logic

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#93240]
We should extract the interactions with the engine in `tryGetOrCreateReplica`[^1] into a standalone method `CreateUninitializedReplica`. This method should know about the two separate engines that may one day exist, and [explain](https://github.com/cockroachdb/cockroach/issues/93243) which one is used for what and the invariants are being maintained.

[^1]: https://github.com/cockroachdb/cockroach/blob/e1c24edea342a83dbd250732e8d1de770cc47ae8/pkg/kv/kvserver/store_create_replica.go#L133-L291

Epic: CRDB-220

Jira issue: CRDB-22233

**Comment by pavelkalinnikov** [comment]
Dup of #93898.
