### ISSUE TITLE
lint: bazel linter doesn't detect unused method

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#93264]
I have a PR on which the TestStaticCheck correctly found a unused method, but the bazel lint was successful.
[make failing](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/7879367?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true)
[bazel succeeding](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/7879349?buildTab=overview&showRootCauses=false&expandBuildChangesSection=true&expandBuildTestsSection=true&expandBuildProblemsSection=true)

The PR was from [this commit](https://github.com/andreimatei/cockroach/tree/b8c80892f756).

Jira issue: CRDB-22251
Epic CRDB-8349

**Comment by rickystewart** [comment]
I think this should be resolved now, but let me know for any further missed unused methods.
