### ISSUE TITLE
monitoring: handle metrics with many-many labels

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#9326]
Some metrics will need a potentially very large set of labels, or even multiple labels. We need to find a good way of storing and accessing those. Emphasis should be on keeping metric updates cheap.

Along with this, the prometheus exporter should keep `prometheusgo.Metric` objects between iterations and simply call our internal metrics to update them.

**Comment by spencerkimball** [comment]
I saw a TODO in the code in `prometheus_exporter.go` with your name on it. But this doesn't actually seem to be a problem we have in practice. This feels like a solution looking for a problem. Closing for the time being as we don't need an issue to track this until it becomes an actual problem.
