### ISSUE TITLE
cli: various UX regressions in mac terminal

### ISSUE THREAD

**Issue by postamar** [cockroachdb/cockroach#93319]
I have a laundry list of very minor issues related to behaviour of the new cli on macs in the default terminal:
1. Regression in the form of loss of "option-click". Previously, having typed something in the prompt, it was possible to move the terminal cursor anywhere within that string by clicking a location while holding the option key. This functionality has been lost now.
2. ~Regression in the form of loss of key bindings. Text prompts on macs broadly support common emacs keyboard shortcuts such as C-a and C-k and the old cli was no exception. This functionality has been lost now.~
3. The prompt helpfully suggests `M-? toggle key help • C-d erase/stop • C-c clear/cancel • C-r search hist • M-. hide/show prompt` but the meta-key shortcuts don't work so I'm stuck because I can't M-?.

Epic: CRDB-22182

Jira issue: CRDB-22272

**Comment by knz** [comment]
point (1) will not be recoverable, I'm afraid.

point (2): can I see it? ctrl+a / ctrl+k work for me and are extensively tested.

point (3): this is known and we're researching solutions. Probably by explaining how to change the mac terminal config. These are key bindings that existed before already.

**Comment by postamar** [comment]
(1) That's too bad
(2) I was careless, C-a and C-k work fine. Sorry for the noise.
(3) Since this is a known issue I guess I can close this one.
