### ISSUE TITLE
udf: name resolution broken when switching databases

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#93321]
**Describe the problem**

If you resolve a UDF, then `USE` a different database, you can still resolve the old UDF by name even if it should no longer be visible.

**To Reproduce**

```
root@localhost:26257/defaultdb> create database d;
CREATE DATABASE

root@localhost:26257/defaultdb> select f(1);
ERROR: unknown function: f(): function undefined
SQLSTATE: 42883

root@localhost:26257/defaultdb> use d;
SET

root@localhost:26257/d> CREATE FUNCTION f(i INT) RETURNS INT LANGUAGE SQL AS 'SELECT i';
CREATE FUNCTION

root@localhost:26257/d> select f(1);
  f
-----
  1
(1 row)

root@localhost:26257/d> use defaultdb;
SET

root@localhost:26257/defaultdb> select f(1);
  f
-----
  1
(1 row)
```

**Expected behavior**
After switching databases, the name shouldn't be resolvable.

**Environment:**
 - CockroachDB version  v22.2.0

Jira issue: CRDB-22274

**Comment by ajwerner** [comment]
I think what's going on is the this code does not check on the UDFs.

https://github.com/cockroachdb/cockroach/blob/48bf2ffe81f3648b444643b978ee6a3e6b232a98/pkg/sql/opt/metadata.go#L284-L293

**Comment by chengxiong-ruan** [comment]
looks like same thing as https://github.com/cockroachdb/cockroach/issues/93082
