### ISSUE TITLE
storage: include range key info in `ScanStats`

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#93326]
The `roachpb.ScanStats` struct contains scan statistics that are attached to BatchResponses for observability purposes. This should include information about range keys as well, which will require corresponding changes to `pebble.IteratorStats`.

https://github.com/cockroachdb/cockroach/blob/19f2fadceb90361638205d54d1bd994da0ee1b52/pkg/storage/mvcc.go#L3556-L3559

Jira issue: CRDB-22275

**Comment by erikgrinaker** [comment]
@jbowens Would this be quick to wire up? Would have been useful to debug a kvnemesis test failure over in #93312.

**Comment by jbowens** [comment]
I have a PR (cockroachdb/pebble#1871) that's been languishing. I'll try to get it across the finish line next week.
