### ISSUE TITLE
cli: log.Fatal is too quiet

### ISSUE THREAD

**Issue by postamar** [cockroachdb/cockroach#93320]
When I trigger ~an unrecoverable panic in the cli~ `log.Fatal`, usually because I'm testing buggy code, everything the go runtime used to barf when the process dies now gets swallowed and I end up in bash not knowing what happened. ~Here I suggest introducing some modal behaviour: a default mode for the user some kind of notice that the process suffered an unrecoverable crash, and another mode for the developer who's writing new bugs who found the now-lost output useful.~ 

Epic: CRDB-22182

Jira issue: CRDB-22273

**Comment by postamar** [comment]
I was partly wrong, apologies. Panics and internal errors bubble up just fine. The offender here is `log.Fatal`. I'll update the issue title accordingly.

To repro: Add `if dbContext == nil { log.Fatal(ctx, "foo") }` at the top of the body of the `populate` function for the `crdb_internal.predefined_comments` virtual table in `crdb_internal.go`, then `dev build short` and `cockroach demo` and then `SELECT * FROM "".crdb_internal.predefined_comments;`. On my macbook I get a newline followed by my shell prompt and nothing else except `$?` being 7.

**Comment by knz** [comment]
thanks, looking

**Comment by knz** [comment]
tip for you: `crdb_internal.force_log_fatal()`

**Comment by knz** [comment]
Ok this is not a new issue actually. But I know how to fix.
