### ISSUE TITLE
cli/sql: macOS terminals don't handle alt-based key combinations by default

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#93353]
**Describe the problem**

On macOS, the default config of terminal applications does not commonly recognize the Alt key. This, in turn, prevents the user from inputting key combinations that involve Alt (e.g. Alt+b/Alt+f to navigate to previous/next word in a unix shell).

In `cockroach sql` and `cockroach demo`, this means that users new to the terminal are unable to use key shortcuts that have been supported ever since CockroachDB v1.0, such as:
- Alt+b / Alt+f to navigate from word to word
- Alt+d / Alt+w to delete words at a time
- Alt+n / Alt+p to navigate through history entries

Meanwhile, all terminal apps checked so far (Apple Terminal, iTerm, termux, Alacritty) do include an opt-in to handle the alt key properly. (see example in the section "Additional data" below)

What can we do about this?

Here are the options:

|      | Educate mac users to enable alt key | Change the key bindings in `cockroach sql` only on macOS | Change the key bindings in `cockroach sql` on all target platforms |
|------|--|--|--|
| Pros | mac users get the benefit of consistent shortcuts across `cockroach sql`, `bash`, `zsh`, and many other terminal applications (bindings are semi-standardized in the unix world). | mac user has nothing to do to utilize all shortcuts in `cockroach sql` | mac user has nothing to do to utilize all shortcuts in `cockroach sql` |
| Cons | mac user needs to take simple action before they can use all shortcuts (they can use _some_ shortcuts before that) | <ul><li>users who use both a macos terminal and a non-mac computer get confused because shortcuts are different from one computer to another</li><li>`cockroach sql` keybindings become inconsistent with that of `bash` / `zsh` etc. on macos</li><li>All mac users who already use the alt key become inconvenienced because they need to re-learn new shortcuts.</li><li>mac user still has no way to enjoy standard shortcuts in `bash`, `zsh` and many other unix programs</li></ul> | <ul><li>`cockroach sql` keybindings become inconsistent with that of `bash` / `zsh` etc. on all platforms</li><li>All  users (across all platforms) who already know how to use the alt key become inconvenienced because they need to re-learn new shortcuts.</li><li>mac user still has no way to enjoy standard shortcuts in `bash`, `zsh` and many other unix programs</li></ul>

**Expected behavior**

Given the pro/cons analysis above, it seems like educating the mac users is the better thing to do.

We can achieve this as follows: when running on macOS, print a  banner upon starting the shell that teaches the user about this limitation and how to tweak their settings.

We can also refer to this situation in docs. See https://github.com/cockroachdb/docs/pull/15788.

**Additional data / screenshots**

Config to enable alt key processing (iterm2)
![image](https://user-images.githubusercontent.com/642886/206812787-7a373633-a5ae-410f-997f-c20c694ae233.png)

Jira issue: CRDB-22282
Epic: CRDB-22182

**Comment by bdarnell** [comment]
I agree that user education seems like the best path here. That's exactly the path chosen by bash/zsh etc - do we have any reason to believe that the meta-based keyboard shortcuts would be used more in `cockroach sql` than in a shell? (Also note that users *do* have a way to use these shortcuts, albeit with the relatively little-known ESC prefix instead of a modifier key). I don't think we should invest in choosing and teaching non-standard alternatives to `meta-b` and friends in the terminal (what could we even use that would work more reliably across platforms and terminals?)

Printing a warning whenever the shell is started on macOS (presumably regardless of the value of this setting, since it's not clear whether we can detect it) seems heavy-handed. I'd rather just not emphasize the existence of the meta-based keyboard shortcuts (as a data point, I just checked and I never actually enabled the meta key in the terminal in my current macbook, and I've never missed the meta shortcuts).

Longer-term I think we want to migrate to a web-based console for users who are not already adept with the terminal.

**Comment by knz** [comment]
> I'd rather just not emphasize the existence of the meta-based keyboard shortcuts

This is exactly where this conversation originated. The new prompt documents key bindings.

```
demo@127.0.0.1:26257/defaultdb>
M-? toggle key help • C-d erase/stop • C-c clear/cancel • C-r search hist • M-. hide/show prompt
```

then after entering M-?
```
demo@127.0.0.1:26257/defaultdb>
M-?       toggle key help       C-c        clear/cancel          C-m/⤶     new line/enter
C-f/→     next char             C-b/←      prev char             C-o       force newline
M-f/M-→   next word             M-b/M-←    prev word             M-⤶/M-C-m force complete
M->/C-end go to end             M-</C-home go to begin           C-l       refresh display
del       del next char         C-h/bksp   del prev char         C-d       del next char/EOF
M-d/M-del del next word         C-w/M-bksp del prev word         M-o/ins   toggle overwrite
C-e/end   end of line           C-a/home   start of line         C-t       transpose char
C-k       del line end          C-u        del line start        M-l       lowercase word
C-n/↓     move down             C-p/↑      move up               M-u       uppercase word
M-n       next history entry    M-p        prev history entry    C-r       search hist
M-q       reflow line           M-S-q/M-`  reflow all            tab       try autocomplete
M-.       hide/show prompt                                       M-2/M-F2  external edit
```

Inline documentation makes it easy(easier) to explore and learn.

> Also note that users do have a way to use these shortcuts, albeit with the relatively little-known ESC prefix instead of a modifier key

Alas, not any more / currently. The input method used by bubbletea (the new framework) does not wait for futher input after finding a lone ESC byte, so that wouldn't work any more. (At least until something like https://github.com/charmbracelet/bubbletea/pull/511 makes it way to upstream)

**Comment by knz** [comment]
We've decided to go the route of user education, docs PR is merged: https://github.com/cockroachdb/docs/issues/15787
