### ISSUE TITLE
server: investigate having a single shared source for the NodeID

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#9344]
Various server components maintain the `NodeID`, and - because the `NodeID` is determined during server startup - the server code does various `SetNodeID` calls.

In addition, the server maintains `nodeLogTagVal` which is an atomic `NodeID` container, used for log tags.

Investigate cleaning all this up by having everyone share a reference to a single atomic (or synchronized) container for the `NodeID`.

**Comment by andreimatei** [comment]
Or alternatively we could have nodes read the node id before starting from storage / generate it as a UUID if it doesn't exist.

**Comment by tamird** [comment]
I nominate andrei for the node IDs are UUIDs refactor.

**Comment by petermattis** [comment]
Translating @tamird: changing node IDs to UUIDs is a non-starter. Way too much work at this point, not to mention the backward compatibility headaches.
