### ISSUE TITLE
Misleading error message when using    sslmode=require

### ISSUE THREAD

**Issue by inata4** [cockroachdb/cockroach#93474]
**Describe the problem**

The following message is received when using `sslmode=require` instead of `sslmode=verify-full` :

```
failed to connect to `host=test-stuff123.cockroachlabs.cloud user=test database=defaultdb`: server error (FATAL: codeParamsRoutingFailed: missing cluster identifier (SQLSTATE 08004))
```

Message is misleading as it complains about missing cluster ID rather than wrong sslmode. Can we change it please?

Jira issue: CRDB-22352

gz#14985

**Comment by andy-kimball** [comment]
It's problematic, since we have no way to tell the difference between the two problems on the server. However, maybe we could expand the error message to contain a hint of some kind, which users could use to delve into more details and hopefully address the problem.
