### ISSUE TITLE
pgwire: TestParseClientProvidedSessionParameters is flakey

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#93478]
**Describe the problem**
See here: https://teamcity.cockroachdb.com/test/-1024401634475276440?currentProjectId=Cockroach_Ci_TestsGcpLinuxX8664BigVm&branch=staging&expandTestHistoryChartSection=true

Jira issue: CRDB-22354

**Comment by yuzefovich** [comment]
dup of #93469
