### ISSUE TITLE
Add a new chart for new SQL connections

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#93486]
We should add a new SQL metric chart for new SQL connections over time using sql.new_conns. We should apply a rate to this metric to indicate that clients are rapidly churning connections.

Slack [thread](https://cockroachlabs.slack.com/archives/C0159JK877C/p1670865371820919) for context.

Jira issue: CRDB-22359

**Comment by rafiss** [comment]
It's probably most useful to show the rate of `sql.new_conns`, so that it shows the number of connection attempts per second. `sql.new_conns` is a counter that only increases, so it's hard to interpret the raw value.

**Comment by kevin-v-ngo** [comment]
https://github.com/cockroachdb/cockroach/issues/76204
