### ISSUE TITLE
kv: raftLogQueueConcurrency is too low

### ISSUE THREAD

**Issue by sumeerbhola** [cockroachdb/cockroach#93534]
`raftLogQueueConcurrency` is defined as 4. For write heavy workloads, like kv0 [1], we have observed that the volume of data flushed to L0 is 80+% of what is written to the WAL. With ~150 ranges and truncation after 64KB we should be truncating most raft log entries before flushing, but that is not happening. @nvanbenschoten suggested looking at the `queue.raftlog.processingnanos` metric -- it indicates that it was running continuously which suggested that it is not able to truncate aggressively enough. Increasing `raftLogQueueConcurrency` to 16 causes the raft log queue to continue to run continuously, but the bytes being flushed to L0 is only 55% of the bytes written to the WAL.
Despite 16 goroutines the actual cpu time spent in `raftLogQueue` processing is only 0.45s in a 20s profile, i.e., 22.5 millisecond/s, which is tiny. The corresponding saving in IO is substantial. 

[1] Running `./workload run kv --init --histograms=perf/stats.json --concurrency=8192 --splits=100 --duration=120m0s --read-percent=0 --min-block-bytes=512 --max-block-bytes=512 --tolerate-errors=true {pgurl:1}` and memtable of 256MB.

[2]
<img width="1584" alt="Screen Shot 2022-12-13 at 11 53 18 AM" src="https://user-images.githubusercontent.com/54990988/207420502-02e3980a-adf6-419d-b517-9aa92e83550c.png">

@nvanbenschoten 

Jira issue: CRDB-22384

**Comment by erikgrinaker** [comment]
Thanks Sumeer, this is promising. We should definitely bump this.

**Comment by nvanbenschoten** [comment]
Thanks for running this experiment Sumeer. From the profile, we can see that the majority of the cost of log truncation comes from scanning over the Raft log to compute the stats delta. It would be interesting to see whether we would need more concurrency if log truncation was faster. There are targeted ways that we could optimize the process [^1]. Or we could try to remove the scan over the Raft log entirely.

If you still have the experiment set up, you could try removing the call to `storage.ComputeStats` and replacing it with:
```
var ms enginepb.MVCCStats 
ms.SysBytes = -cArgs.EvalCtx.GetMVCCStats().SysBytes
```

[^1]: e.g. the interleaving iterator is not needed when computing the stats of local keys.

**Comment by tbg** [comment]
The stats iteration also showed up prominently in experiments I ran using https://github.com/cockroachdb/cockroach/pull/93815 and the patch Nathan pointed out above completely removed it from the profiles (I was looking at allocations though).

**Comment by pavelkalinnikov** [comment]
I'm trying the experiment that Nathan pointed out above.

**Comment by pavelkalinnikov** [comment]
I wasn't able to reproduce the 80% figure. In my experiments on GCE worker all 3 setups give about 52-58% L0/WAL ratio. I only ran these tests for 30m (not 120m like in @sumeerbhola's command).

Also, in my experiments, after bumping concurrency to 16 I don't observe `queue.raftlog.processingnanos` metric saturation. Removing `ComputeStats` (but leaving concurrency = 4) also does not impact the ratio.

concurrency = 4:

```
__level_____count____size___score______in__ingest(sz_cnt)____move(sz_cnt)___write(sz_cnt)____read___r-amp___w-amp
    WAL         1    31 M       -    27 G       -       -       -       -    29 G       -       -       -     1.1
      0         0     0 B    0.00    29 G     0 B       0     0 B       0    17 G    13 K   1.9 G       0     0.6
      1         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      2         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      3        22    61 M    0.96   5.9 G     0 B       0   628 K       1    13 G   3.4 K    14 G       1     2.2
      4        69   343 M    0.99    12 G     0 B       0   706 M     182    30 G   6.4 K    31 G       1     2.4
      5       168   1.8 G    1.00    11 G     0 B       0   966 M     242    33 G   4.3 K    33 G       1     3.1
      6       357   8.9 G       -   9.6 G     0 B       0     0 B       0    36 G   2.3 K    37 G       1     3.7
  total       616    11 G       -    29 G     0 B       0   1.6 G     425   157 G    30 K   117 G       4     5.4
  flush       479
compact      5038     0 B     0 B       0          (size == estimated-debt, score = in-progress-bytes, in = num-in-progress)
  ctype      4613       0       0     425       0       0       0  (default, delete, elision, move, read, rewrite, multi-level)
 memtbl         1    64 M
zmemtbl         0     0 B
   ztbl         0     0 B
 bcache      12 K   336 M   98.7%  (score == hit-rate)
 tcache        65    43 K  100.0%  (score == hit-rate)
  snaps         0       -       0  (score == earliest seq num)
 titers         0
 filter         -       -   98.0%  (score == utility)

```

concurrency = 4, `storage.ComputeStats` removed:

```
__level_____count____size___score______in__ingest(sz_cnt)____move(sz_cnt)___write(sz_cnt)____read___r-amp___w-amp
    WAL         1    41 M       -    27 G       -       -       -       -    27 G       -       -       -     1.0
      0         0     0 B    0.00    27 G     0 B       0     0 B       0    16 G    13 K   435 M       0     0.6
      1         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      2         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      3        21    64 M    1.00   6.3 G     0 B       0   1.2 M       2    14 G   3.6 K    15 G       1     2.2
      4        67   346 M    1.00    12 G     0 B       0   799 M     207    30 G   6.3 K    31 G       1     2.4
      5       166   1.8 G    1.00    10 G     0 B       0   1.4 G     349    31 G   4.1 K    31 G       1     3.0
      6       353   8.8 G       -   9.7 G     0 B       0     0 B       0    37 G   2.5 K    38 G       1     3.8
  total       607    11 G       -    27 G     0 B       0   2.1 G     558   154 G    29 K   116 G       4     5.6
  flush       473
compact      5101     0 B     0 B       0          (size == estimated-debt, score = in-progress-bytes, in = num-in-progress)
  ctype      4543       0       0     558       0       0       0  (default, delete, elision, move, read, rewrite, multi-level)
 memtbl         1    64 M
zmemtbl         0     0 B
   ztbl         0     0 B
 bcache      19 K   574 M   98.8%  (score == hit-rate)
 tcache        63    42 K  100.0%  (score == hit-rate)
  snaps         0       -       0  (score == earliest seq num)
 titers         0
 filter         -       -   98.1%  (score == utility)

```

concurrency = 16:
```
__level_____count____size___score______in__ingest(sz_cnt)____move(sz_cnt)___write(sz_cnt)____read___r-amp___w-amp
    WAL         1    22 M       -    28 G       -       -       -       -    29 G       -       -       -     1.1
      0       246   155 M    1.69    29 G     0 B       0     0 B       0    16 G    13 K   1.4 G      11     0.5
      1         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      2         0     0 B    0.00     0 B     0 B       0     0 B       0     0 B       0     0 B       0     0.0
      3        66   263 M    2.03   5.7 G     0 B       0   1.7 M       1    14 G   3.5 K    15 G       1     2.4
      4       176  1022 M    2.04    12 G     0 B       0   652 M     169    28 G   6.0 K    29 G       1     2.4
      5       235   2.7 G    2.01   9.6 G     0 B       0   986 M     254    30 G   4.0 K    30 G       1     3.1
      6       326   7.2 G       -   7.8 G     0 B       0     0 B       0    28 G   2.1 K    29 G       1     3.6
  total      1049    11 G       -    29 G     0 B       0   1.6 G     424   144 G    29 K   104 G      15     5.0
  flush       489
compact      4613   9.9 G   183 M       3          (size == estimated-debt, score = in-progress-bytes, in = num-in-progress)
  ctype      4189       0       0     424       0       0       0  (default, delete, elision, move, read, rewrite, multi-level)
 memtbl         1    64 M
zmemtbl         0     0 B
   ztbl         0     0 B
 bcache      82 K   2.2 G   99.2%  (score == hit-rate)
 tcache       517   343 K  100.0%  (score == hit-rate)
  snaps         0       -       0  (score == earliest seq num)
 titers        15
 filter         -       -   98.5%  (score == utility)
```

**Comment by pavelkalinnikov** [comment]
My cluster is `local` though, maybe I should try this on a distributed cluster.

**Comment by pavelkalinnikov** [comment]
I tried increasing the block size to 768:

```
workload run kv --init --histograms=perf/stats.json --concurrency=8196 --splits=100 --duration=30m0s --read-percent=0 --min-block-bytes=768 --max-block-bytes=768 --tolerate-errors=true 'postgres://root@127.0.0.1:26257?sslmode=disable'
```

Now the L0/WAL writes ratio is consistently 81-82% before and after the concurrency bump. The raftlog queue doesn't seem to be fully active in both cases, but often bursts up to the available concurrency:

<img width="1012" alt="Screenshot 2023-02-14 at 15 14 08" src="https://user-images.githubusercontent.com/3757441/218789657-84315da4-db38-4cb0-bd50-6432677c449e.png">
<img width="990" alt="Screenshot 2023-02-14 at 15 49 20" src="https://user-images.githubusercontent.com/3757441/218789707-b30e305f-5714-41fd-9803-6878e7efec82.png">

So, I still can't reproduce the before/after with a clear benefit.

**Comment by sumeerbhola** [comment]
I suspect something in the reproduction is slowing down the rate at which memtables are getting filled up, which is allowing the raftLogQueue to keep up better. Some possibilities:
- server cpu utilization is close to 100%: in my experiment there was ample spare cpu (c5.9xlarge)
- admission control for the store is kicking in to slow down the writes. One can confirm based on the overload graphs and the periodically printed LSM shape. One could turn off admission control (admission.kv.enabled=false).

**Comment by pavelkalinnikov** [comment]
Merged an env var which can be used to dynamically change this parameter. Will do a few more experiments lazily. So far in all my tests I observed no regression so the default has been optimistically bumped to 16 based on the fact that Sumeer did observe improvement on some workloads.
