### ISSUE TITLE
cdc: TestStreamDeleteRange timed out

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#93568]
The timeout happened on [this](https://teamcity.cockroachdb.com/viewLog.html?buildId=7951762&buildTypeId=Cockroach_BazelEssentialCi) build on a custom branch, but most likely my changes are completely unrelated.

Jira issue: CRDB-22406

**Comment by yuzefovich** [comment]
cc @cockroachdb/tenant-streaming can we get eyes on this please?

**Comment by rickystewart** [comment]
I already have #93756 to bump the size of this test (unless the feeling is that it's timing out due to some bug and not just the fact that the timeout is too short).

**Comment by stevendanna** [comment]
https://github.com/cockroachdb/cockroach/pull/93761
