### ISSUE TITLE
sql: make virtual tables more like views?

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#9361]
came up in #9327.

`ValidateTable` has been extremely helpful in catching correctness issues in the past, so it'd be great if we could Validate all the TableDescriptors in the system, including the virtual ones, and generally minimize differences where possible.

We might also want to reverse the change in #9327 to using literals and switch to creating these just like regular tables -- either utilizing the dummy planner trick used in tests, or by switching to a setup step (but after `init()`) that has a planner available.

**Comment by dt** [comment]
cc @paperstreet @nvanbenschoten @dt

**Comment by dt** [comment]
I'm kind of wondering if there'd be any merit in trying to unify slightly with views? i.e. actually write the descriptors for virtual tables and treat them the same as views as far as resolving/leasing/etc, but then add a field on the the desc with the name of the function used to populate the rows.

**Comment by andreimatei** [comment]
FWIW, I want to use virtual tables in the future for exposing other types
of introspection info - e.g. RangeDescriptor table, RangeDescriptor cache,
LeaseHolder caches. So I hope we keep creating virtual tables easy to
create, without needing migrations.

**Comment by jordanlewis** [comment]
@dt is this still relevant?

**Comment by dt** [comment]
The same motivations still hold, but the cost has only gone up as we’ve added more of theee tables as-is, so i’m not sure we’re any more likely to do this now.
