### ISSUE TITLE
c2c: support pgurl scheme in ExternalConnections

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#93629]
As part of C2C replication, nodes in the standby cluster must be able to connect to nodes in the primary cluster to replicate data. This happens via a pgx connection (PGURL) that may contain sensitive authentication information. By supporting pgurls in External Connections we can offer the user a UX where they create an EC representing the primary cluster connection string and thereon out refer to the much more terse EC name. This will allow us to:

1. Ensure sensitive information is redacted in the places it is exposed to users.
2. Allow us to test the connection by pinging the cluster as part of EC creation. This will help resolving authentication issues prior to setting up the replication stream.

See also https://github.com/cockroachdb/cockroach/pull/86061

Epic: CRDB-18749

**Comment by livlobo** [comment]
@HonoreDB  - I see some related PRs merged. Is there more work remaining here?

**Comment by HonoreDB** [comment]
Per discussion offline, nope, this is done!
