### ISSUE TITLE
User name maps and kerberos not interacting as expected

### ISSUE THREAD

**Issue by andy-dulson** [cockroachdb/cockroach#93637]
**Describe the problem**

We were hoping to use [user name maps](https://github.com/cockroachdb/cockroach/pull/74459) to create foo_super user accounts that can be authed to with user foo's krb credentials. This works in postgres, but doesn't seem to in cockroach.

**To Reproduce**

What did you do? Describe in your own words.

These steps were on a v21.2.17 cluster:

(1) Create db users that match the system username, and the system username with a _super suffix:

```
root@crdb:26257/defaultdb> \du
        username       | options | member_of
-----------------------+---------+------------
...
  adulson              |         | {}
  adulson_super        |         | {admin}
```

(2) The cluster is already set-up (as per [these instructions](https://www.cockroachlabs.com/docs/v21.2/gssapi_authentication)) so that kerberos authentication works for the user which matches the system username:

```
$ psql --no-psqlrc -h crdb -d defaultdb -p 26257 -c "select current_user"
 current_user 
--------------
 adulson
(1 row)
```

In particular

```
root@crdb:26257/defaultdb> show cluster setting server.host_based_authentication.configuration;
  server.host_based_authentication.configuration
--------------------------------------------------
  host all all all gss include_realm=0
(1 row)
```

(3) Set `server.identity_map.configuration` to the same config we have in postgres:

```
defaultdb> show cluster setting server.identity_map.configuration;
  server.identity_map.configuration
-------------------------------------
  user /^(.*)@DOMAIN\.COM$ \1
  user /^(.*)@DOMAIN\.COM$ \1_super
(1 row)
```

(4) At that point, I expect the -U argument to psql to allow me to login as `adulson_super` using `adulson`'s krb credentials. That's not what happens though:

```
$ psql --no-psqlrc -h crdb -d defaultdb -p 26257 -c "select current_user" -U adulson_super
 current_user 
--------------
 adulson
(1 row)
```

**Expected behavior**
In step four, I expect the cluster to recognise me as user `adulson_super`.

**Additional data / screenshots**

This works on postgres; with the same config in pg_ident.conf as we set in etting server.identity_map.configuration we see:

```
$ psql -h postgres -d postgres -U adulson -c "select current_user"
 current_user
--------------
 adulson
(1 row)

$ psql -h postgres -d postgres -U adulson_super -c "select current_user"
 current_user  
---------------
 adulson_super
```

**Environment:**
 - CockroachDB version: v21.2.17
 - Server OS: 
   ```
   $ cat /etc/redhat-release 
   Rocky Linux release 8.6 (Green Obsidian)
   ```
 - Client app: psql (since `cockroach sql` doesn't support kerberos)

**Additional context**
What was the impact?

Jira issue: CRDB-22446

**Comment by knz** [comment]
@andy-dulson many thanks for filing this.
Can I ask about point (3):

```
defaultdb> show cluster setting server.identity_map.configuration;
  server.identity_map.configuration
-------------------------------------
  user /^(.*)@DOMAIN\.COM$ \1
  user /^(.*)@DOMAIN\.COM$ \1_super
```

Do you get any better behavior if you remove the leading `/` from the regular expression?

**Comment by andy-dulson** [comment]
Removing the leading `/` causes this error:

```
root@crdb:26257/defaultdb> set cluster setting server.identity_map.configuration = 'user ^(.*)@DOMAIN\.COM$ \1
user ^(.*)@DOMAIN\.COM$ \1_super';
ERROR: saw \1 substitution on line 1, but pattern contains no subexpressions
```

**Comment by bobvawter** [comment]
@knz, I suspect this is because the auth API assumes there's a 1:1 mapping of external system identity to database role.  If you look at this code at the top level, we assume that the external auth API is going to provide a single replacement identity, and we don't check that against the user/role name that the client requests.  Maybe `behaviors.ReplacementIdentity()` should return a slice and we treat the incoming username as a request for one of the possibilites?

https://github.com/cockroachdb/cockroach/blob/53b1dea33a1cbbf573aee481c39bcc14541e4e55/pkg/sql/pgwire/auth.go#L120-L141

**Comment by knz** [comment]
Thanks for breaking it down for me bob. Your explanation seems reasonable.
