### ISSUE TITLE
sql: tool for importing the output of `./cockroach dump`

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#9365]
The first version should assume the statements for a table are sorted by primary key (as they are in `./cockroach dump`). CREATE TABLE should reserve an id and make a descriptor, these are used to convert any following INSERT statements into kvs, periodically dumping them to sstables. Then Import (soon to be renamed Ingest) is called on them to do the actual database mutations. kv conversion should likely be via `sql.rowInserter`.

**Comment by vivekmenezes** [comment]
#15933 implements the ingest via csv file.
