### ISSUE TITLE
cli/sql: sql CLI confused by modern comments

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#9369]
What I did:

```
set syntax=traditional;
select 1
; set syntax=modern; select 1 #comment;
;
```

What I got:
```
root@:26257> set syntax=traditional;
SET
root@:26257> select 1
          -> ; set syntax=modern; select 1 #comment;
pq: syntax error at or near ";"
select 1
; set syntax=modern; select 1 #comment;
                                      ^
```

What I expected: 
```
root@:26257> set syntax=traditional;
SET
root@:26257> select 1
          -> ; set syntax=modern; select 1 #comment;
          -> ;
+---+
| 1 |
+---+
| 1 |
+---+
(1 row)
+---+
| 1 |
+---+
| 1 |
+---+
(1 row)
```

**Comment by knz** [comment]
I'm adding a test for this in #9087.

**Comment by knz** [comment]
Similar:

```
set syntax=traditional;
select 1
; set syntax=modern; select '''
'; boo
''';
```

Got:
```
root@:26257> set syntax=traditional;
SET
root@:26257> select 1
          -> ; set syntax=modern; select '''
          -> '; boo
          -> ''';
          ->  
```
(statement not terminated)

Expected:
```
root@:26257> set syntax=traditional;
SET
root@:26257> select 1
          -> ; set syntax=modern; select '''
          -> '; boo
          -> ''';
+---+
| 1 |
+---+
| 1 |
+---+
(1 row)
+----------------+
| e'\n\'; boo\n' |
+----------------+
| ␤              |
| '; boo␤        |
+----------------+
(1 row)
```

**Comment by mjibson** [comment]
This isn't a bug. I was worried about this myself when I implemented the cli lexer. But Peter pointed out that the syntax mode can only be changed after an entire query string is already parsed. It doesn't change between statements if they are in the same query string.

**Comment by knz** [comment]
Ok fine with me. Can you just clarify then what you meant in https://github.com/cockroachdb/cockroach/issues/7334#issuecomment-228949963 with

*changing syntax (modern, traditional) mid session: verify that the lexer correctly picks up the new syntax mode. Also need to make sure a SET syntax = whatever in the middle of a single line with multiple statements is picked up. That's harder because the SET tag is obscured in that case.*

**Comment by mjibson** [comment]
That comment is outdated. It was based on an old implementation of the cli lexer that didn't end up getting used. It was thought that we would use the returned pgwire tag, but instead the lexer looks for a `SET` token which avoids the tag business completely.

**Comment by knz** [comment]
Thanks!
