### ISSUE TITLE
backupccl: memory monitor and limit ExportRequest that fetches descriptor revisions

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#93727]
Backup issues `ExportRequests` to get all the descriptor revisions in a given key and time interval over here https://github.com/cockroachdb/cockroach/blob/92a04231adb3846e2ba1c50439c38016356ab1a0/pkg/kv/kvclient/revision_reader.go#L33. These `ExportRequests` are sent without a limit (span or bytes) in the header and so they are not forced to paginate when the response grows beyond a certain size. In the case of several thousand descriptors changing between each backup with revision history, this can become a non-trivial amount of data held in memory causing nodes to OOM.

We should:
1. Plumb a memory monitor to pre-reserve a fixed byte size.
2. Set a `TargetBytes` value that ensures the size of the returned responses grow approximately as much as we have reserved. 

These two improvements should allow for graceful failure of backups instead of crashing a node in the cluster.

Epic: CRDB-19061

Jira issue: CRDB-22502

**Comment by otan** [comment]
is this somehow related to https://github.com/cockroachdb/cockroach/issues/56215?
