### ISSUE TITLE
backupccl: TestDataDriven/in-progress-restores is flaky

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#93731]
Example build: https://teamcity.cockroachdb.com/viewLog.html?buildId=7977403&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_BazelUnitTests

Error is `Expect "pq: referenced schema ID 109: descriptor is a *dbdesc.immutable: unexpected descriptor type" to match "pause point .* hit$"`

Jira issue: CRDB-22504
Epic CRDB-22861

**Comment by adityamaru** [comment]
fails quickly using:

`./dev test pkg/ccl/backupccl -f TestDataDriven/in-progress-restores --show-logs --stream-output --stress | tee out;`

**Comment by renatolabs** [comment]
> Starting a bisect.

Were you able to identify the root cause here? If a fix is not in progress, I'll open a PR to skip this test as it's failing quite often. Let me know, please!

**Comment by adityamaru** [comment]
I have a potential fix but I'm still working through some hairy details so it might be worth skipping it in the meantime -  https://github.com/cockroachdb/cockroach/pull/93784. It looks like the failure started after likelyhttps://github.com/cockroachdb/cockroach/pull/93611
