### ISSUE TITLE
multi-tenant: Ensure equivalent performance with UA clusters

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#93749]
With the UA we must ensure that we don't regress performance.  An initial investigation in https://github.com/cockroachdb/cockroach/pull/93530 indicates that we may be regressing performance substantially.  This issue should complete that investigation, enumerate the causes, and either create sub-issues or fix things directly.

Jira issue: CRDB-22512

Epic CRDB-23559

**Comment by knz** [comment]
We have confirmed experimentally that the perf for all the basic benchmarks is analogous to the single-tenant case.
Closing in favor of #87610.
