### ISSUE TITLE
sql: Django introspection query performance regression

### ISSUE THREAD

**Issue by timgraham** [cockroachdb/cockroach#93955]
**Describe the problem**

A regression in 072ec8d7e422a70cd5946f1682be6848381615d7 is causing the following query (which Django's test suite runs quite often) to take several seconds (instead of milliseconds).

**To Reproduce**

```sql
            SELECT
                c.relname,
                CASE
                    WHEN c.relispartition THEN 'p'
                    WHEN c.relkind IN ('m', 'v') THEN 'v'
                    ELSE 't'
                END
            FROM pg_catalog.pg_class c
            LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relkind IN ('f', 'm', 'p', 'r', 'v')
                AND n.nspname NOT IN ('pg_catalog', 'pg_toast')
                AND pg_catalog.pg_table_is_visible(c.oid)
```

**Environment:**
 - CockroachDB version v23.1.0-alpha.1-168-g61f7c81657 
 - Build Time:       2022/12/19 23:09:39

Jira issue: CRDB-22612

**Comment by timgraham** [comment]
@rafiss I'd guess #90649 is at fault.

**Comment by rafiss** [comment]
In my tests, this query takes ~450ms in a database that has 38 tables.

Also, it seems to me that the filter should be updated to something more like:
```
n.nspname NOT IN ('pg_catalog', 'pg_toast', 'pg_extension', 'information_schema', 'crdb_internal')
```

**Comment by timgraham** [comment]
You can use `./tests/runtests.py --settings=test_roach inspectdb` to reproduce the slowdown. Excluding those additional namespaces doesn't seem to make much (any?) speed difference.

**Comment by timgraham** [comment]
This query still takes 1-2 seconds with 23.1 alpha 8 and the current nightly and the full Django test suite runtime is up from ~40 minutes with 22.2.x to ~1.5 hrs (though I'm not sure it's entirely attributable to this query). Do you want to reopen this issue or track it in another one? (I saw some discussion at https://github.com/cockroachdb/cockroach/issues/96960#issuecomment-1461309014.)
