### ISSUE TITLE
storage: update TestStoreRangeRebalance and unexport RebalanceThreshold

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#9395]
This is the result of merge skew between #8668 and #9230 which was hackily "resolved" in #9279.

**Comment by petermattis** [comment]
This issue is regarding `TestStoreRangeRebalance`, right? `TestStoreRangeRemoveDead` looks fine. Or am I missing something.

**Comment by tamird** [comment]
@petermattis correct. Updated the issue title.

**Comment by petermattis** [comment]
The test relies on`RebalanceThreshold == 0`. I'll leave relaxing this restriction to one of the original test authors.
