### ISSUE TITLE
log: handle slow/stuck network sinks

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#93984]
In https://github.com/cockroachlabs/support/issues/1954, we saw a log to fluentd get stuck, which led to an outage.
We need to be resilient to slow log sinks. We already have a 20s timeout for syncing log files: https://github.com/cockroachdb/cockroach/blob/c57dd84c2ec2d84607d4c4a6170abc4a57abdef0/pkg/util/log/log_flush.go#L55

but this doesn't seem to be in the critical path for all collectors (for which the concept of a "sync" doesn't even apply).

We need to either extend it or compromise on the synchronicity of such log writes, i.e. making the log statements non-blocking and persistence of those logs best-effort. If we do the latter we need to handle the case of a fully stuck sink and will need to either drop log messages or shut down anyway, so it comes out to the same in the worst case.

Jira issue: CRDB-22638

**Comment by dhartunian** [comment]
This was addressed by the buffered sink implementation. Closing.
