### ISSUE TITLE
stability: better exposure when ResolveIntent does not find an intent

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#9399]
When MVCCResolveIntent is asked to commit (rather than abort) an intent and no intent is found in the MVCC metadata, it should verify that there is a value at the transaction's timestamp, and complain loudly if not.

See #9265

**Comment by spencerkimball** [comment]
Hmm, I'm not sure this is actually plausible after looking at the code. I believe that @tschottdorf already pointed this out as a potential issue, and we thought enough information would still be available to complain. However, it looks like there's an insoluble issue with complaining in the event that `ResolveIntent` finds neither an intent nor a value matching the specified timestamp. Here's the scenario:

- Intent is written at key "a" by txn1 at epoch=1, ts=0
- Txn1 retries with epoch=2
- Txn1 writes to key "b" at epoch=2, ts=2 (doesn't write to key "a" again)
- Txn1 is committed, intents not yet cleaned up
- Concurrent txn2 reads key "a", finds txn is committed, deletes intent with earlier epoch
- Txn1 resolves intent at key "a"; on resolve:
  - No intent meta, so no way to know commit epoch
  - No way to warn about missing intent on commit without false positives

We could fix this by tagging intent resolutions with whether or not the intent is still valid, but this also doesn't handle the case of resolving ranges of intents. My feeling is we should abandon this extra check – seems worth doing if simple, but not worth doing if we have to introduce complexity and / or still not handle all cases where we should be warning.

**Comment by tschottdorf** [comment]
Agreed.
