### ISSUE TITLE
storage: `TestMVCCHistories` should test `RangeKeyChanged()` on iterator exhaustsion

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#94040]
We check this when the iterator is valid:

https://github.com/cockroachdb/cockroach/blob/1f7e094f5e6296625b5d7c29ed47694f3d93d337/pkg/storage/mvcc_history_test.go#L1930-L1932

We should check this when it's exhausted too:

https://github.com/cockroachdb/cockroach/blob/1f7e094f5e6296625b5d7c29ed47694f3d93d337/pkg/storage/mvcc_history_test.go#L1864-L1868

This is likely going to result in a fair number of bugs or other issues, so it'll be a bit of a yak shave.

Jira issue: CRDB-22658

**Comment by jbowens** [comment]
Do we rely on this behavior? Almost all `pebble.Iterator` methods' behavior is undefined if `!Valid()`

**Comment by erikgrinaker** [comment]
This isn't valid, see #94220.
