### ISSUE TITLE
ui: admin UI often unresponsive during 3->5 allocator test

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#9412]
SHA: 6e334c12771a73f5b578c2f8c170af14021785d7

When running the nightly 3->5 allocator test, the admin UI (accessed via Chrome for Mac) is often unresponsive, refusing to load or only partially loading. Sometimes, Chrome will report that the admin UI is unresponsive and me whether I want to kill it.

To run this test:

```
make test \
  TESTS="TestRebalance_3To5Small" \
  TESTTIMEOUT="1h" \
  PKG="./acceptance" \
  TESTFLAGS="-v --remote -key-name google_compute_engine -cwd=terraform -at.std-dev 14"
```

We should figure out how to avoid starving the admin UI endpoints.

**Comment by vivekmenezes** [comment]
I've not observed this recently. Closing unless you feel differently. The admin UI on the prod clusters look okay.
