### ISSUE TITLE
sql: type mismatched if a implicit record type is used in a UDF's signature and then altered.

### ISSUE THREAD

**Issue by chengxiong-ruan** [cockroachdb/cockroach#94124]
**Describe the problem**
When a UDF is created with implicit record types in its signature and, after that, if tables of the implicit record types are altered (column added or dropped), there'd be type mismatch between the function signature and the tables.

**To Reproduce**
```sql
CREATE TABLE t (a INT, b INT);

CREATE FUNCTION f() RETURNS t LANGUAGE SQL AS $$ SELECT a, b FROM t LIMIT 1 $$;

-- alter table
ALTER TABLE t ADD COLUMN c INT;

-- recreate the function
-- this would error with "ERROR: cannot change return type of existing function"
CREATE OR REPLACE FUNCTION f() RETURNS t LANGUAGE SQL AS $$ SELECT a, b, c FROM t LIMIT 1 $$;
```

**Expected behavior**
To match the postgres behavior, the function should be able to replaced as long as the query return type matches with the new table.

**Environment:**
 - CockroachDB version 22.2.0

Jira issue: CRDB-22699

**Comment by ajwerner** [comment]
There's a few paths here:

1) We can try to forbid the changing of columns when referenced in a function.
	* Is this hard? Do we have the needed information to determine.
2) We can stop allowing users to create these functions. 
     * This would be walking back a feature, but maybe that's fine because the feature doesn't really work?
