### ISSUE TITLE
sql: allow multiple UDFs with in-exact type parameters of the same family

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#94146]
CRDB returns an error `function "xxx" already exists with same argument types` when trying to create two UDFs with parameters from the same type family. For example:

```sql
CREATE FUNCTION f(i INT2) RETURNS INT STRICT LANGUAGE SQL AS 'SELECT 2';
CREATE FUNCTION f(i INT4) RETURNS INT STRICT LANGUAGE SQL AS 'SELECT 4';
```

This is because `pkg/sql/create_function.go` uses the `TypeList.Match` function to find matching function overloads. `Match` checks for lists of equivalent types, but we need to check for lists of identical types.

Jira issue: CRDB-22708

**Comment by il9ue** [comment]
@mgartner Is it okay for me to send PR after some code change and testing? If it's been already taken internally, please let me know, then I will stop. Thanks.

**Comment by mgartner** [comment]
@il9ue absolutely, we welcome a PR to fix this!

**Comment by il9ue** [comment]
There seems to be errors but not sure it's related → https://teamcity.cockroachdb.com/viewLog.html?buildId=8292266&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_BazelUnitTests 

Could you please give me feedback?

**Comment by il9ue** [comment]
@mgartner just a kind reminder, please give any feedback on [the change I made](https://github.com/cockroachdb/cockroach/pull/96481) when you get a chance 🙂
