### ISSUE TITLE
Something broke with the inet data type 

### ISSUE THREAD

**Issue by dvarrazzo** [cockroachdb/cockroach#94192]
Running psycopg 3 test suite, there seem to be a regression in crdb 22.2.1 w.r.t. 22.2.0, in the tests involving the inet data type.

- [successful run](https://github.com/psycopg/psycopg/actions/runs/3759475904/jobs/6389090649#step:8:22) (CockroachDB CCL v22.2.0)
- [failed run](https://github.com/psycopg/psycopg/actions/runs/3761382463/jobs/6393079531#step:8:1369) (CockroachDB CCL v22.2.1)

Jira issue: CRDB-22731

**Comment by rafiss** [comment]
It seems likely that I caused this with https://github.com/cockroachdb/cockroach/pull/93332

I noticed some issues with that later on, so I made https://github.com/cockroachdb/cockroach/pull/93923 to improve it, but that won't be out until v22.2.2. Let me see if I can test with a development build to confirm.

**Comment by dvarrazzo** [comment]
Speaking of which, do you publish somewhere a "nightly" docker image we might use in the ci to test with?

**Comment by rafiss** [comment]
Yes! We can try using this:
```
us-docker.pkg.dev/cockroach-cloud-images/cockroachdb/cockroach:latest-v23.1-build
```

The binary itself is available at https://edge-binaries.cockroachdb.com/cockroach/cockroach.linux-gnu-amd64.LATEST
