### ISSUE TITLE
Prune client dependencies

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#942]
The transitive dependencies of `cockroach/client` end up linked into end-user binaries, so we should make sure we don't have unnecessary dependencies there. Specifically:
* There are two paths from cockroach/client to biogo/store, util/cache.go and proto/data.go
* util/http.go depends on yaml
* The rpc client is fairly heavyweight, bringing in the cgo-based compression packages. As long as it's experimental (and perhaps even when it's not), it should be in a separate compilation unit.
* Protos generally include a bunch of stuff that clients don't need and perhaps should be insulated from (especially `internal.*`, but very little of the stuff in the non-generated `.go` files are necessary for clients)
* All logging in client-accessible code needs to go through an abstraction layer so we don't impose glog (or our current preference for server-side logging) on client apps. (or maybe something like logrus would be flexible that clients could adapt it to their own logger of choice. Glog is definitely not flexible enough to be our hard-coded logger in the client)

In the log run it might make sense to put the client in a separate repo, but we're not to that point yet. We should have a test that runs `go list` to get the client deps and guards against adding new ones.

**Comment by tschottdorf** [comment]
For logging, we could just log to something compatible to the parts of the standard logging interface we use (plus, maybe optionally V). Something like

```go
type ClientLogger interface {
  // Infof, ...
}

type verbose interface {
  V(int) bool
}

func (db *client.DB) SetLogger(logger ClientLogger) {
  if l, ok := logger.(verbose); ok {
    db.v = l.V
  } else {
    db.v = func(int) bool { return false }
  }
  db.log = logger
}
```

and/or the same thing on the client package level (so that it's not an issue for each client created).

**Comment by petermattis** [comment]
We could move both `HTTPSender` and `RPCSender` out of `client` and into `client/http` and `client/rpc` packages respectively and use a registration mechanism for them to hook into the client library. I'm thinking of an approach that is similar to `database/sql` and the associated drivers. 

The standard client logger (if not otherwise set) should output to the standard `log` package.

**Comment by tschottdorf** [comment]
I agree, though some plumbing inside the client will be needed since the standard logger has an interface that's by far not what we want to use, namely only `Print`/`Fatal`/`Panic` flavor commands.

**Comment by bdarnell** [comment]
We could use something like etcd/raft's logger interface: https://github.com/coreos/etcd/blob/eb930c3298176a5a4c4ce8985506ab0988aca57e/raft/logger.go

We should also examine the way we use logging in client code: do we need multiple levels here or can we live within the lowest common denominator provided by `log`?

**Comment by aarondunnington** [comment]
> We could move both HTTPSender and RPCSender out of client and into client/http and client/rpc packages respectively and use a registration mechanism for them to hook into the client library. I'm thinking of an approach that is similar to database/sql and the associated drivers.

If it is still up for grabs, I would love to start with this part.

**Comment by petermattis** [comment]
@aarondunnington feel free to grab it. The work is partially done. Specifically, the registration mechanism now exists and both `HTTPSender` and `RPCSender` use it to register themselves. It should be straightforward to move `RPCSender` from `client` to `client/rpc` as a first step.

**Comment by aarondunnington** [comment]
Cool, thanks @petermattis. Will work on a change for review.

For client/http, had a question about the dependencies in HTTPSender that would no longer be available from the client package. Would it be okay to make the moves below?

* Move HTTPRetryOptions to client/sender.go for use in RPCSender and HTTPSender.
* Move KVDBEndpoint to client/sender.go for use in HTTPSender and kv/db.go
* Move TestPutReq / TestPutResp to testutils/http.go for use in client/kv_test, client/txn_test, & client/http/http_sender_test

**Comment by petermattis** [comment]
* I would unexport `HTTPRetryOptions` (i.e. rename to `retryOptions`) and duplicate the options between `client/http` and `client/rpc`.
* Yes on moving `KVDBEndpoint` to `client/sender.go`.
* `testPut{Req,Resp}` should really go away. They are leftover from a time before the existence of `client.PutCall` which itself will shortly go away now that `client.DB` is the new hotness. Since they will be removed fairly soon, I suggest making copies so that you can make progress on your refactoring.

**Comment by aarondunnington** [comment]
Thanks @petermattis. Changes for client/rpc and client/http packages ready for review.

Getting permission denied when pushing the remote branch. Should I create a fork?

**Comment by tamird** [comment]
@aarondunnington yeah, forking is the way to go - you'll then be able to open PRs from your fork.

**Comment by aarondunnington** [comment]
#1118

**Comment by aarondunnington** [comment]
Tracking here from #1118 feedback: `client.HTTPRetryOptions` should be renamed to `client.RetryOptions`.

**Comment by tamird** [comment]
Visiting for triage:
```
go list -f '{{range .Deps}}{{printf "%s\n" .}}{{end}}' github.com/cockroachdb/cockroach/client | sort | uniq | grep -E '[^/]+\.[^/]+/'
github.com/biogo/store/interval
github.com/biogo/store/llrb
github.com/cockroachdb/c-snappy
github.com/cockroachdb/cockroach/base
github.com/cockroachdb/cockroach/keys
github.com/cockroachdb/cockroach/proto
github.com/cockroachdb/cockroach/security
github.com/cockroachdb/cockroach/structured
github.com/cockroachdb/cockroach/util
github.com/cockroachdb/cockroach/util/caller
github.com/cockroachdb/cockroach/util/encoding
github.com/cockroachdb/cockroach/util/log
github.com/cockroachdb/cockroach/util/log/logflags
github.com/cockroachdb/cockroach/util/retry
github.com/cockroachdb/cockroach/util/stop
github.com/cockroachdb/cockroach/util/uuid
github.com/gogo/protobuf/proto
golang.org/x/crypto/bcrypt
golang.org/x/crypto/blowfish
golang.org/x/crypto/ssh/terminal
golang.org/x/net/context
gopkg.in/yaml.v1
```

**Comment by bdarnell** [comment]
The root package for the client is now `sql/driver`, not `client` (although the results are the same)

**Comment by petermattis** [comment]
Tamir, listed the set of transitive dependencies. The direct dependencies for `sql/driver` are:

```
~ go list -f '{{range .Imports}}{{printf "%s\n" .}}{{end}}' github.com/cockroachdb/cockroach/sql/driver | sort | uniq | grep -E '[^/]+\.[^/]+/'
github.com/cockroachdb/cockroach/base
github.com/cockroachdb/cockroach/client
github.com/cockroachdb/cockroach/proto
github.com/cockroachdb/cockroach/util/retry
github.com/gogo/protobuf/proto
```

The dependency on `cockroach/client` is for the `HTTPPost` structure. Easy enough to separate out that code if we want to. The dependency on `cockroach/proto` is for `proto.ClientCmdID` (currently unused) and `proto.Error`. The dependency on `cockroach/base` is for `base.Context`. I think we could trim all of these immediate dependencies if we wanted to.

**Comment by bdarnell** [comment]
Tagging for beta because of #2683. I don't think we have to do all of this for beta, but at least the `util/log` package is a problem because of conflicting command-line flags with `glog` and other `glog`-derived logging packages.

**Comment by bdarnell** [comment]
Closing since our client package is now `lib/pq`.
