### ISSUE TITLE
storage: control per-replica timestamp cache memory

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#9423]
The timestamp cache is currently per-replica and is the most significant user of per-replica memory. #9102 fixed an issue where we weren't clearing the timestamp cache when we lost the range lease, but even with that change the timestamp cache consumes a significant chunk of memory that grows with the number of replicas. 

One options is we could periodically trim the timestamp cache on idle replicas. At the moment, we only trim the timestamp cache when it is accessed. This would be a straightforward change yet it would interact with the feature that allows the `timestampCache` to hold very old entries as long as it hasn't hit its size threshold which makes interactive SQL shell usage nicer.

Alternately, we could move to a per-store timestamp cache. See discussion in #9101. The tricky part here is dealing with setting the low-water mark on lease acquisition. It looks possible to replace using `TimestampCache.SetLowWater` with inserting a span that covers the entire key range for which a lease is being acquired. A per-store timestamp cache is likely preferable if it could be made to work.

Cc @cockroachdb/stability

**Comment by petermattis** [comment]
@bdarnell Given #14264, do you see any problems with proceeding with this? We already use a separate mutex for timestamp cache. The change to replace using `TimestampCache.SetLowWater` with inserting a span that covers the entire key range for which a lease is being acquired seems straightforward.

**Comment by bdarnell** [comment]
SGTM

**Comment by petermattis** [comment]
One downside to a per-Store timestamp cache is that it might act as a bottleneck. In particular, both `Replica.applyTimestampCache` and `endCmds.done` will now have to grab a per-Store lock instead of a per-Replica lock. I have no evidence that this is a problem (yet), but I'd like to do a bit of testing with this approach before committing to it.

**Comment by petermattis** [comment]
@bdarnell I'm getting test failures with my per-Store timestamp cache change which I've narrowed to the following diff:

```diff
diff --git a/pkg/storage/replica_proposal.go b/pkg/storage/replica_proposal.go
index d53c3e7..8010747 100644
--- a/pkg/storage/replica_proposal.go
+++ b/pkg/storage/replica_proposal.go
@@ -404,8 +404,17 @@ func (r *Replica) leasePostApply(
                        log.Infof(ctx, "new range lease %s following %s [physicalTime=%s]",
                                newLease, prevLease, r.store.Clock().PhysicalTime())
                }
+
+               desc := r.Desc()
                r.tsCacheMu.Lock()
-               r.tsCacheMu.cache.SetLowWater(newLease.Start)
+               for _, keyRange := range makeReplicatedKeyRanges(desc) {
+                       // TODO(peter): Figure why adding a "write" entry causes various test
+                       // failures.
+                       for _, readOnly := range []bool{true, false} {
+                               r.tsCacheMu.cache.add(
+                                       keyRange.start.Key, keyRange.end.Key, newLease.Start, nil, readOnly)
+                       }
+               }
                r.tsCacheMu.Unlock()

                // Reset the request counts used to make lease placement decisions whenever
```

Why would adding a "write" span cause:

```
~ ~/Development/go/src/github.com/cockroachdb/cockroach/pkg/storage master go test -v -run TestUnreplicateFirstRange
...
--- FAIL: TestUnreplicateFirstRange (0.18s)
	client_test.go:1057: change replicas of r1 failed: replay txn
```

**Comment by bdarnell** [comment]
The third return value of `timestampCache.GetMaxWrite` indicates whether the returned timestamp comes from a real span or the low-water mark. It's used [here](https://github.com/cockroachdb/cockroach/blob/4ced58933fb1d65b2db6eb48d78c396516fd36de/pkg/storage/replica.go#L1864-L1884). Looks like we need to set an extra flag on these spans to mark them as effective low-water marks.

**Comment by petermattis** [comment]
Oh, that might be it. Thanks for finding that.

**Comment by petermattis** [comment]
That was definitely it. I hope you enjoy my very clever fix that does not involve an extra flag on the cache entries (see `lowWaterTxnIDMarker`).

**Comment by nvanbenschoten** [comment]
> One downside to a per-Store timestamp cache is that it might act as a bottleneck. In particular, both Replica.applyTimestampCache and endCmds.done will now have to grab a per-Store lock instead of a per-Replica lock.

@petermattis this has been on my mind ever since I realized we made this change. It's pretty unfortunate that we now have more per-Store locking on the hot path of each request. That said, I'm not aware of any evidence that this has caused issues in practice. Has this shown up on your radar yet?

**Comment by a-robinson** [comment]
I haven't seen it at all on the write-only workloads I've been running recently.

**Comment by petermattis** [comment]
I haven't seen the timestamp cache mutex show up in any profiles either.
