### ISSUE TITLE
cli/demo: `\demo stop` does not work well with `--multitenant=true`

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#94316]
Currently the `\demo stop` command in `cockroach demo` shuts down the KV part of the node but ignores the attached secondary tenant server. This makes the secondary tenant server inoperative after that. Also, a subsequent `\demo start` becomes utterly confused by the presence of a secondary tenant server already.

Jira issue: CRDB-22826

**Comment by ajstorm** [comment]
Solved.
