### ISSUE TITLE
storage: investigate over-aggressive quiescing

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#9432]
When doing X block_writer queries/sec on gamma/delta we quiesce ~2*X ranges/sec. Since each block_writer operation touches only a single range this seems a bit curious. I would have expected the number of ranges quiesced per second to be equal to the queries/sec. 

With the current quiescing set up we're quiescing a range on the next tick loop after it becomes quiesce-able. With the tick interval of 100ms this means we're quiescing on average within 50ms. I think we could restructure the code so that we quiesce the next time a heartbeat is sent out (every 300ms). 

Cc @cockroachdb/stability

**Comment by bdarnell** [comment]
Remember that ranges != replicas, and the raft message stats are per-replica. Each query wakes (up to) one range, which subsequently quiesces. The leader of that range sends two quiesce messages (to the two followers). So at our current QPS and tick interval, we expect to see heartbeat messages equal to twice the QPS.

**Comment by petermattis** [comment]
Ah, good point about ranges vs replicas. Looking at delta right now, we're performing 5000 queries/sec and 13.5k heartbeats/sec. So perhaps there is a little benefit to be had here, but not the 2x reduction I was originally envisioning.

**Comment by petermattis** [comment]
With coalesced heartbeats also coalescing quiesce messages, I don't think there is anything to do here.
