### ISSUE TITLE
ui: database list confused when database name contains simple punctuation

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#94328]
(Found via #94027)

**Describe the problem**

When a database name contains special punctuation _which is allowed in PostgreSQL_, the database view in the DB console breaks down.

**To Reproduce**

1. start `cockroach demo --empty`
2. enter: `CREATE DATABASE "a-b";`
3. navigate to db console -> databases

Observe: 
- the db details are unavailable,
- there's a red error banner,
- js console reports error

**Expected behavior**

Database names containing special characters should be supported.

**Additional data / screenshots**

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/642886/209703483-eadd4e86-9276-4cec-9d08-f58be66b325a.png">

**Environment:**
 - `master` branch towards v23.1

Relates to #94327.
Epic: CRDB-20388

Jira issue: CRDB-22831

**Comment by j82w** [comment]
The only character not supported in `/`. 
https://github.com/cockroachdb/cockroach/pull/95209
https://github.com/cockroachdb/cockroach/pull/95693

**Comment by xinhaoz** [comment]
@j82w Can we backport the PRs linked here for 22.2? It seems to affect that version as described in the support issue above.
