### ISSUE TITLE
ui: Accuracy of per-table estimates for INTERLEAVE tables

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#9433]
A per-table estimate of disk space usage is currently available in the admin UI. However, this estimate was designed under the assumption that each range would contain data for only one table or index; it is therefore not correct for INTERLEAVE tables.

We should determine the requirements for size estimation of INTERLEAVE tables.

**Comment by spencerkimball** [comment]
Interleaved tables will only be able to display usage for the entire hierarchy rooted at the top-level table. What are we currently doing?

Also, should this be 1.0?
+cc @danhhz

**Comment by danhhz** [comment]
I think all data is counted in whatever is at the top of its interleave hierarchy. So it actually sounds pretty close to what you describe, just with 0s for the interleave descendants instead of something useful (like a pointer to the root)

**Comment by spencerkimball** [comment]
@mrtracy could we add this to the TODO list for ui? Sounds like a version 1.0 fix would be to mark interleaved tables as "Interleaved with <root table>" and link to the root table.

**Comment by mrtracy** [comment]
If we need this for 1.0, I'm not sure i'm going to have time depending on the 1.0 release date.

**Comment by spencerkimball** [comment]
@mrtracy, Is this more complicated than I'm imagining?

**Comment by mrtracy** [comment]
@spencerkimball I just have a lot on my plate and only a month to complete it.

I don't precisely understand interleaved tables; I actually haven't even loaded up a CockroachDB database that *has* interleaved tables, so I don't even know whats currently displayed, I only have an intuition that it won't be correct.

At the very least, we'll have to add something to the Table details API to indicate that a table is interleaved with another; i'm not even sure how that information is represented in our table metadata.

These are all things I can obviously investigate and learn out, but it makes it hard to estimate time to completion.

**Comment by spencerkimball** [comment]
Hmm that makes sense. Sounds like this could be a candidate for someone more familiar with interleaved tables to jump in and contribute on the UI.

+cc @danhhz

**Comment by danhhz** [comment]
I definitely don't have time to ramp up on ui technology, but happy to do any API work needed. @mrtracy want to chat quickly today and at least figure out how much work in involved here?

**Comment by petermattis** [comment]
I believe a user just encountered a UX surprise related to this. The `Database` page reported a table as containing 0 bytes while `SELECT COUNT(*)` reported hundreds of thousands of rows. Examination of the schema revealed the table is interleaved in its parent. If we know the size number is not computed correctly, can we indicate this in the UI. Or perhaps highlight that a table is interleaved in the `Tables` table.

**Comment by jordanlewis** [comment]
Closing as won't fix
