### ISSUE TITLE
ui: database list breaks down entirely when there are many databases

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#94333]
(Found via #94027)

**Describe the problem**

When there are many databases, the database list page refuses to load with an error.
The specific limit seems to be environment-dependent. For example on my machine I encounter this limit at ~450 databases. 

**To Reproduce**

1. start `cockroach demo` with the changes from #94027
2. generate 1000 databases, e.g. via `select crdb_internal.generate_test_objects('{"names":"mydb._._","counts":[1000,0,0],"name_gen":{"noise":false}}'::jsonb);` 
3. navigate to db console -> databaes

Observe: page is broken (see screenshot below)

**Expected behavior**

Database list should always display regardless of database count.

**Additional data / screenshots**

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/642886/209707145-5322bd61-a2ad-4901-aeed-1bb5cc98affa.png">

**Environment:**
 - `master` towards v23.1

Epic: CRDB-20388

Jira issue: CRDB-22836

**Comment by j82w** [comment]
The database page will now load. The only limitation is sort is disabled if there are more than 40dbs. https://github.com/cockroachdb/cockroach/pull/96431
