### ISSUE TITLE
ui: Estimated Row Count for tables

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#9434]
The Admin UI currently provides an estimated disk usage on a per-table basis. An interest has been expressed in providing a fast _row-count_ estimate for tables, and the same mechanism we use to compute disk usage (aggregating per-node totals) could also be used to estimate a row count.

The new count should be sensitive to INTERLEAVE tables (also a potential issue for disk usage computation, see #9433).

**Comment by petermattis** [comment]
If this is in reference to the question on Gitter, it wasn't clear to me that the desire was to have this in the admin UI. I think it would be interesting to see an estimated row count in the admin UI, but it would be extremely useful to have an estimated row count available to the query optimizer.

**Comment by vilterp** [comment]
Note: maybe can show this on UI piggybacking on query stats work for the optimizer

**Comment by petermattis** [comment]
@vilterp We probably want to be able to show the optimizer table statistics in the UI, but note that these statistics can be significantly off (we might only refresh the statistics every hour or less) and we'll need to message/highlight that appropriately.

**Comment by jordanlewis** [comment]
This should be easy now that `show tables` has this information.

**Comment by azaky** [comment]
Hey @jordanlewis, I am new here and looking for something that I can contribute to cdb. Can I make an attempt at this? Thanks!

**Comment by kaustubhmallik** [comment]
Hi @jordanlewis is it still relevant and open to grab? I would love to contribute.

**Comment by otan** [comment]
this is already in the db now!
