### ISSUE TITLE
Always capture and surface failed executions

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#94381]
This issue tracks improving the V1 experience for failed executions. Any failed execution is an insight in and of itself. We should capture all failed executions (regardless of whether they were ‘slow’) to arm users with observability information to reduce these errors. 

Related issues:

- https://github.com/cockroachdb/cockroach/issues/85256
- https://github.com/cockroachdb/cockroach/issues/87785

Open question: Should we create a separate table for all failed executions? FYI @gtr 

Jira issue: CRDB-22865

**Comment by maryliag** [comment]
cc @dongniwang for design feedback if we should change how we display it
