### ISSUE TITLE
Mean transaction time discrepancy between the Transaction overview and details pages in the console

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#94396]
There is a discrepancy between the Transaction time on the Transaction fingerprint overview page and the Transaction fingerprint details page. 

[Loom](https://www.loom.com/share/b5ea0f92a4b5413883c10221c55dd9f1) video for context. 

Jira issue: CRDB-22871

**Comment by koorosh** [comment]
In `23.1.0` version, new data requested on navigation from Transactions page to Transaction details page.
It's probably causes this mismatch for transaction fingerprints during workload.

Now, for most recent versions, this behaviour is changed:
- navigating to Transaction details page doesn't request updated data;
- navigation from Transaction details back to Transactions page would still request new data.

@dongniwang , currently it is possible for users to disable auto-refresh on pages, 
but when user navigates between pages, we still re-request new data. 
Does it make sense to show users stale (last received) data even after navigation 
between pages (with disabled auto-refresh? What do you think?

**Comment by koorosh** [comment]
Better visibility of whether data is changed on transaction page (after navigation back on it) is done in scope
of https://github.com/cockroachdb/cockroach/pull/105157

**Comment by koorosh** [comment]
I'm in favor to close this issue as there's no mismatches of data shown on pages but unintended requests for new data and lack of visibility when new data is fetched (which is already done by mentioned PR above).
