### ISSUE TITLE
sql, kv: SELECT FOR UPDATE appears to delay the lock cleanup on RootTxn in some cases

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#94400]
This issue seems similar to #94290 but is applicable even when we don't use the leaf txn in the local only flow (as of #94399). Consider the following setup:
```
CREATE TABLE data (a INT PRIMARY KEY, b INT);
INSERT INTO data SELECT i, i FROM generate_series(0, 9) AS g(i);
ALTER TABLE data SPLIT AT SELECT i FROM generate_series(1, 9) AS g(i);
SELECT * FROM data FOR UPDATE;
SELECT * FROM data FOR UPDATE;
```
The second SELECT FOR UPDATE takes much longer (about 500ms vs 3ms for the first run). (Note that I think that the delay is about `50ms` x `number of ranges involved - 1`.)

Jira issue: CRDB-22874

**Comment by nvanbenschoten** [comment]
This is before https://github.com/cockroachdb/cockroach/pull/94399, right? So there are locks that we aren't properly tracking? If so, then this makes sense. If not, then there's still a bug somewhere around here.

50ms is the default value of the [`kv.lock_table.coordinator_liveness_push_delay`](https://github.com/cockroachdb/cockroach/blob/64e4fc9faa4e0ab19fe5ba78f053bc2b1390cb5e/pkg/kv/kvserver/concurrency/lock_table_waiter.go#L67) setting. This setting dictates how long a conflicting request waits before pushing a lock holder's txn record. The wait is performed once per request per range.

If the original lock holder is failing to track all of its locks, then any abandoned lock won't be eagerly, asynchronously released. Instead, conflicting transactions will need to push the lock holder's txn record (after 50ms), determine that the lock holder is finalized, and clean up the locks for it.

I think the difference between this case and the one in https://github.com/cockroachdb/cockroach/issues/94290 is that the txn is tracking _some_ locks. That means that it's not hitting the non-locking commit fast-path and skipping its txn record write entirely:
https://github.com/cockroachdb/cockroach/blob/64e4fc9faa4e0ab19fe5ba78f053bc2b1390cb5e/pkg/kv/kvclient/kvcoord/txn_coord_sender.go#L490-L492

As a result, when other txns push after finding abandoned locks, they do find a COMMITTED txn record so they don't have to wait out the 5s txn expiration.

**Comment by yuzefovich** [comment]
Thanks for the context!

> This is before #94399, right?

Actually this still happens after #94399. We now use the root txn for this case, but I still see the delay of 50ms per range affected.
