### ISSUE TITLE
Running cockroach on Docker (OSX host) results in immediate exit

### ISSUE THREAD

**Issue by vpetkar** [cockroachdb/cockroach#9440]
Followed [instructions](https://www.cockroachlabs.com/docs/start-a-local-cluster-in-docker.html) exactly. 

Docker version: Docker version 1.10.2, build c3959b1
Host: macOS Sierra 10.12 
Image: cockroachdb/cockroach:beta-20160915

When it comes to running the actual container, using command: 
```docker run -d --name=roach1 --hostname=roach1 --net=roachnet -p 26257:26257 -p 8080:8080  \
-v "${PWD}/cockroach-data/roach1:/cockroach/cockroach-data"  
cockroachdb/cockroach:beta-20160915 start --insecure```

It will fail with this error ```Error: cockroach server exited with error: failed to start store: could not open rocksdb instance: IO error: directory: Invalid argument
Failed running "start"```.

At this point, I have also attempted to hardcode the data storage with `--data` flag as well as using /Users/<my_username> in place of ${PWD}. This has had no effect.

Will update if I find a solution.

**Comment by irfansharif** [comment]
this issue was previously discussed here: https://github.com/cockroachdb/docs/issues/311
should be addressed using docker for mac instead with no dependency on VirtualBox.

**Comment by vpetkar** [comment]
Might want to update the docs to reflect that VirtualboxFS  shouldn't be used, lots of tutorials online for Docker use a default setup of Docker Toolbox which installs the Virtualbox setup and Kitematic. Shall I make a PR?

Meanwhile, easy fix for people stumbling upon this: Follow `[this](https://docs.docker.com/v1.8/installation/mac/)` tutorial to uninstall Docker toolbox completely, use Docker for Mac from Docker instead.

🙌
