### ISSUE TITLE
Windows Local Dev Symlink Git Hooks Issue

### ISSUE THREAD

**Issue by quanuw** [cockroachdb/cockroach#94413]
**Describe the problem**
Hello, I am trying to set up my local dev environment and I am running into some issues. When I run ./dev doctor, I get an error creating symlinks:

=============================
=== RUNNING DOCTOR CHECKS ===

ERROR: symlink C:\Users\quan\repos\cockroach\githooks\commit-msg .git/hooks/githooks\commit-msg: The system cannot find the path specified.

Are the above paths supposed to be created by the dev doctor command? I think the second path has issues because of the use of forward and back slashes.

I’m using a windows machine running Version 10.0.19045 Build 19045 with developer mode enabled.

Do you have some suggestions on how I can resolve this?
Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

What did you do? Describe in your own words.
I ran ./dev doctor using bash terminal on a windows machine while following these docs cockroachlabs.com/docs/stable/architecture/overview.html.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
2. Send SQL ... / CLI command ...
3. Look at UI / log file / client app ...

**Expected behavior**
Running dev doctor should finish without errors.

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version [e.g. 2.0.x]
 - Server OS: [e.g. Linux/Distrib]
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
What was the impact?

Jira issue: CRDB-22881

**Comment by rickystewart** [comment]
Hi @quanuw -- we would accept a patch here to fix this, but don't have access to Windows machines to test this ourselves.

In general, developing on Windows is not really supported or ever tested, and I expect that if you address this bug then there will be other papercuts or bugs that may prevent you from going through the normal development workflow.

Cross-building to Windows from a Linux machine is possible and you may find it easier to do that if you want to produce a custom Windows executable.

**Comment by quanuw** [comment]
Thanks for the explanation @rickystewart. I'll try to find another way to set up my dev env.
