### ISSUE TITLE
build: ARM binaries should be named using `runtime.GOARCH`

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#94441]
**Is your feature request related to a problem? Please describe.**
We have code in some places that constructs the URL from which to download a binary by doing something like `fmt.Sprintf(".../cockroach.%s-%s.LATEST", runtime.GOOS, runtime.GOARCH)`. Example: https://github.com/cockroachdb/cockroach-go/blob/9d43af95238b4a663127eb8536d997598f597110/testserver/binaries.go#L83

This doesn't work for the ARM builds right now. They are currently named like https://edge-binaries.cockroachdb.com/cockroach/cockroach.darwin-aarch64.unsigned.LATEST

**Describe the solution you'd like**
Name it like https://edge-binaries.cockroachdb.com/cockroach/cockroach.darwin-arm64.LATEST instead

**Describe alternatives you've considered**
Write special case code for ARM builds.

Jira issue: CRDB-22891

**Comment by rail** [comment]
Looks like this also affects Arm unittests
```
Failed
=== RUN   TestLogic_testserver_test_22_1_22_2
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/f0512f3559a6f1fc0be49477689a2598/logTestLogic_testserver_test_22_1_22_2774916239
    test_log_scope.go:79: use -show-logs to present logs inline
    logic.go:1838:
        :0: error while processing
    logic.go:1838: unexpected HTTP response from https://binaries.cockroachdb.com/cockroach-v22.1.6.linux-arm64.tgz?ci=true: 404
        <html><body>
        <h1>404 Error: Not Found</h1>
        </body></html>
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/f0512f3559a6f1fc0be49477689a2598/logTestLogic_testserver_test_22_1_22_2774916239
--- FAIL: TestLogic_testserver_test_22_1_22_2 (0.06s)
```

**Comment by rail** [comment]
Still need to backport to 22.2 and copy released files in order to make upgrade tests wort

**Comment by rail** [comment]
All god now.
