### ISSUE TITLE
docs: Unclear how to use foreign keys

### ISSUE THREAD

**Issue by d4l3k** [cockroachdb/cockroach#9447]
The docs on foreign keys explain what they are but don't provide any examples of how to use them.

https://www.cockroachlabs.com/docs/constraints.html#foreign-keys

We've had several people at Hack the North be confused by our foreign key syntax. It's unclear that you have to make an index on the table that is referencing another.

```
CREATE DATABASE IF NOT EXISTS company_{language}_{ORM};

CREATE TABLE IF NOT EXISTS customers (
  id           SERIAL PRIMARY KEY,
  name         STRING
);

CREATE TABLE IF NOT EXISTS orders (
  id           SERIAL PRIMARY KEY,
  subtotal     DECIMAL(18,2)
  customer_id  INT    REFERENCES customers(id),
);
```

The above code doesn't seem to work without adding `index (customer_id)`  to the second `CREATE TABLE` statement.

Any reason this is the case and we don't automatically create that index?

@sploiselle @paperstreet

**Comment by tamird** [comment]
Docs issue, docs repo?

**Comment by d4l3k** [comment]
Not just a docs issue. Also a correctness issue.

**Comment by sploiselle** [comment]
@d4l3k We don't want to automatically create indexes without users knowing that they're there.

We also have examples [here](https://www.cockroachlabs.com/docs/constraints.html#example).

However, Foreign Keys could use some additional scaffolding so I'm planning to [move it into their own document](https://github.com/cockroachdb/docs/issues/607).

Thanks for logging the issue; definitely the kind of feedback we're looking for from the Hackathon.

**Comment by paperstreet** [comment]
fwiw, you also want @dt for foreign key stuff

**Comment by dt** [comment]
> Any reason this is the case and we don't automatically create that index?

There's a little discussion of automatically creating indexes in [the rfc](https://github.com/cockroachdb/cockroach/blob/develop/docs/RFCS/fk.md#indexes) but, the gist is that that what to do with implicitly created indexes is tricky: if the constraint is dropped, dropping the silently dropping the index could be a disaster if queries are actually using it, while leaving it could be confusing since it isn't clear why an index no one asked for is still there.

**Comment by dt** [comment]
We could revisit that decision though, and if so, I think I'd lean towards automatically adding them with a name explaining where they came from, but certainly not automatically deleting them if the constraint is dropped.

**Comment by spencerkimball** [comment]
I'm closing this because the consensus has remained we do not automagically create indexes.

Also: https://github.com/cockroachdb/docs/pull/901
