### ISSUE TITLE
restoring databases ends up with "does not have CREATE privilege on schema public"

### ISSUE THREAD

**Issue by wzrdtales** [cockroachdb/cockroach#94598]
When we try to restore a database into a fresh new cockroachdb instance (same version the backup was made with), after restoring the same db it looks fine at first, but as soon as the application starts (in this case keycloak) it 1) doesn't recognize already run migrations and also throws permission errors ala:

`does not have CREATE privilege on schema public`

Jira issue: CRDB-23030

**Comment by stevendanna** [comment]
@wzrdtales Apologies that this issue fell through the cracks. Is this still an issue you are encountering?

**Comment by stevendanna** [comment]
I'm closing this for now, but if feel free to reopen. Again, apologies for the original delay.

**Comment by wzrdtales** [comment]
it was never fixed...
