### ISSUE TITLE
TestNoLinkTesting breaks release build

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#946]
https://circleci.com/gh/cockroachdb/cockroach/2179

The issue is that for the Docker deploy image, we build all the tests and then put them into a container that does not have the sources or Go.

TestNoLinkTesting calls out to the runtime to calculate the build dependencies, which isn't possible in that context. We should probably move that test to its own file and not build it with the `release` tag.

```
executing ../build/cli.test
--- FAIL: TestNoLinkTesting (0.00s)
	flags_test.go:47: cannot find package "github.com/cockroachdb/cockroach" in any of:
			/usr/src/go/src/github.com/cockroachdb/cockroach (from $GOROOT)
			($GOPATH not set)
```

**Comment by tschottdorf** [comment]
The tests are currently not build with the release tag (see `build/deploy`), so we'll have to make that happen as well.

**Comment by petermattis** [comment]
Perhaps the test should be skipped if `GOPATH` is not set.
