### ISSUE TITLE
logictest: the logic test driver uses an outdated file name to download the 22.2 arm binary in mixed version tests

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#94658]
`TestLogic_testserver_upgrade_node` and `TestLogic_Testserver_test_22_1_22_1` have been c[onsistently failing](https://teamcity.cockroachdb.com/viewLog.html?buildId=8175280&buildTypeId=Cockroach_PostMerge_MergedArm64Tests) on arm builds because they attempt to pull the arm binaries from an incorrect path. These tests use `https://binaries.cockroachdb.com/cockroach-v22.2.1.linux-arm64.tgz` while the public  r[elease page ](https://www.cockroachlabs.com/docs/releases/index.html) indicates the binary file name is `cockroach-v22.2.1.linux-3.7.10-gnu-aarch64.tgz`

Jira issue: CRDB-23068

**Comment by rafiss** [comment]
https://github.com/cockroachdb/cockroach/issues/94441 should resolve this. i can skip it for ARM builds for now
