### ISSUE TITLE
sqlstats: reuse stats container used by current txn and stmts

### ISSUE THREAD

**Issue by xinhaoz** [cockroachdb/cockroach#94650]
Currently, the stats collector for a session allocates a new stats container for each running txn. Prior to https://github.com/cockroachdb/cockroach/pull/83616, we created a txn-specific stats container only for explicit txns. [Now that we all txns use their own container, these allocations are likely causing this regression in kv95.](https://github.com/cockroachdb/cockroach/issues/88122)

We should just reuse the container between txns, resetting the appropriate fields on txn start, or introduce a Container pool.

Jira issue: CRDB-23065

Epic CRDB-37544

**Comment by matthewtodd** [comment]
Cool, I think these allocations are some of the ones reported in #89918.
