### ISSUE TITLE
storage: txn prios not ratcheted properly upon pushes

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#9470]
High levels of read/write contention can leave transactions unable to make progress. For example, consider transactions that perform two operations: a scan from k1 to k2, then an insert at some k3 between k1 and k2 (each transaction picks a unique k3), then does something in an unrelated part of the keyspace before committing.

These transactions encounter each other's intents and push each other's timestamps forward, causing restarts, but they do not get increased priorities (based on the high epoch values and low priorities seen in the trace in #9247). Transactions often retry for 30 seconds or more before they are able to complete.

Originally noticed in the `photos` example, see cockroachdb/examples-go#78 and #9247. This was caused by a bug that led to higher-than-expected contention; we haven't yet identified what exactly was going on under this contention and how we might be able to handle it better.

**Comment by tschottdorf** [comment]
I think we might not be doing what we should be doing here. When a reader pushes a writer and loses, it is supposed to upgrade its priority. We don't:

```go
		// For write/write conflicts within a transaction, propagate the
		// push failure, not the original write intent error. The push
		// failure will instruct the client to restart the transaction
		// with a backoff.
		if h.Txn != nil && h.Txn.ID != nil && !readOnly {
			return pushErr
		}

		// For read/write conflicts, and non-transactional write/write
		// conflicts, return the write intent error which engages
		// backoff/retry (with !Resolved). We don't need to restart the
		// txn, only resend the read with a backoff.
		return wiPErr
```

That means that reads are likely to get starved if you're on a low priority and higher-priority writes happen continuously in your way.

This has been an issue more than enough times to fix. The [design doc](https://github.com/cockroachdb/cockroach/blob/develop/docs/design.md) also states

>
Reader encounters write intent with older timestamp: the reader must follow the intent’s transaction id to the transaction table. If the transaction has already been committed, then the reader can just read the value. If the write transaction has not yet been committed, then the reader has two options. If the write conflict is from an SI transaction, the reader can push that transaction's commit timestamp into the future (and consequently not have to read it). This is simple to do: the reader just updates the transaction’s commit timestamp to indicate that when/if the transaction does commit, it should use a timestamp at least as high. However, if the write conflict is from an SSI transaction, the reader must compare priorities. If the reader has the higher priority, it pushes the transaction’s commit timestamp (that transaction will then notice its timestamp has been pushed, and restart). If it has the lower or same priority, it retries itself using as a new priority max(new random priority, conflicting txn’s priority - 1).

**Comment by bdarnell** [comment]
Yeah, that looks like it could be the problem. I was studying the transaction push process to see why the priorities weren't getting upgraded but missed this place where push errors are just getting dropped. 

Dropping the push error here and using the write intent error path instead might be more efficient if the intent's transaction is in the past, or is in the future and gets aborted, since we could just redo the read instead of the whole transaction. However, this is based on the assumption that the other transaction will be able to complete soon, and that you're not facing a steady flow of new transactions. 

We at least need to transfer the upgraded priority from the pushErr to the wiPErr; I'm not sure if we want to go all the way to returning the pushErr so we handle transactional read/write conflicts on the regular transaction push path.

**Comment by spencerkimball** [comment]
Starvation in these scenarios should no longer be a problem with the push txn queue (#13501).
