### ISSUE TITLE
sql-over-http: Add tests to verify data for ui pages

### ISSUE THREAD

**Issue by j82w** [cockroachdb/cockroach#94724]
The SQL Activity, Insights, and other pages have been converted to use sql-over-http instead of an endpoint. New tests need to be added to verify that the queries on these pages return valid results. This will avoid regressions when breaking changes are made between major version releases like https://github.com/cockroachdb/cockroach/issues/94445.

Jira issue: CRDB-23100

**Comment by maryliag** [comment]
No longer a priority
