### ISSUE TITLE
kv: non-locking reads ignore exclusive locks

### ISSUE THREAD

**Issue by nvb** [cockroachdb/cockroach#94729]
See https://github.com/cockroachdb/cockroach/issues/49684 for context. If we differentiate between exclusive locks and intents, then we don't need non-locking reads to wait on exclusive locks. See also [this document](https://docs.google.com/document/d/1ji6C0aDI6n61sVKPjf5-YUucbtgBlwfpsrNdcidW5a0/edit).

Before we do this, we'll likely want something like https://github.com/cockroachdb/cockroach/issues/91417. This was also described in https://github.com/cockroachdb/cockroach/issues/49684#issuecomment-848400422.

Jira issue: CRDB-23103

Epic CRDB-26544

**Comment by nvanbenschoten** [comment]
We will start by making this change just for non-serializable readers.
