### ISSUE TITLE
sql: `SHOW FUNCTIONS FROM pg_catalog` is slow

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#94746]
**Describe the problem**

See the title.

This may be fallout from  #94339? unsure

**To Reproduce**

`cockroach demo` then `show functions from pg_catalog;`

**Expected behavior**

Lists UDF overloads in pg_catalog schema.

cc @jordanlewis @postamar for triage.

Jira issue: CRDB-23115

**Comment by knz** [comment]
Oh I stand corrected, it _does_ terminate eventually, after a _full minute_ of waiting.
There's only 1904 rows. It shouldn't take 1 minute to generate 2k rows.

**Comment by jordanlewis** [comment]
`SHOW FUNCTIONS` currently runs 2 slow projections:

```
 select pg_get_function_result(oid) from pg_proc;
select pg_catalog.pg_get_function_identity_arguments(oid) from pg_proc;
```

These weren't edited by my recent PR, but we should definitely do something about this.

**Comment by jordanlewis** [comment]
Redefining these as SQL functions speeds them up enormously!
