### ISSUE TITLE
changefeedccl: remove CONTROLCHANGEFEED permission

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#94757]
In 23.1, we are deprecating CONTROLCHANGEFEED. We should completely remove it in 24.1.

Jira issue: CRDB-23482

Epic CRDB-23748

**Comment by rafiss** [comment]
Is there a strong reason to actually remove it entirely? The role options are deprecated, but removing it has the potential to break tooling that is relying on them, and the role options code is not really causing any significant amount of tech debt. (Or if it is, I'm happy to be corrected.)

**Comment by jayshrivastava** [comment]
I don't think it needs to completely be removed from the code or tests. We should remove it from docs if we don't want people to build new functionality/systems using it.

**Comment by data-matt** [comment]
Please don't remove.

**Comment by aerfrei** [comment]
I think changes to permissions we're making now might have changed the calculus here and we should reconsider this. Reopening so we can discuss as a team.
