### ISSUE TITLE
Add `node` label to prometheus metrics

### ISSUE THREAD

**Issue by fanny-jiang** [cockroachdb/cockroach#94763]
**Is your feature request related to a problem? Please describe.**
Currently, `node_id` is submitted as a gauge metric. It is not present as a label for any of the emitted prometheus metrics from the `_status/vars` monitoring endpoint. The [CockroachDB Dedicated cloud](https://docs.datadoghq.com/integrations/cockroachdb_dedicated/#pagetitle) Datadog integration tags metrics by node, whereas the self-hosted CockroachDB prometheus-based integration does not tag its metrics by node because the node label is not present. 

Having the `node_id` as a label will help with monitoring CockroachDB health by node. 

**Describe the solution you'd like**
Submit a `node` label with each node-specific prometheus metric. 

**Describe alternatives you've considered**
Transform the `node_id` metric value into a tag within the integration and apply this tag to all the ingested metrics. There is a concern that the `node` tag may get applied to the wrong metrics and this approach is hacky. 

**Additional context**
Motivation is for the self-hosted CockroachDB Datadog integration to have feature parity with the CockroachDB Dedicated integration. 

Jira issue: CRDB-23129

**Comment by fanny-jiang** [comment]
If possible, `clusterName` and/or `clusterID, and `region` would be great too to have as labels.

**Comment by dhartunian** [comment]
Thanks for filing this @fanny-jiang. You're not the only one who has asked for this feature. We've got a busy roadmap at the moment but will follow up once we take a look at implementation options in a month or two.
