### ISSUE TITLE
kvserver: allocating replacement replicas needs to consider fully satisfying constraints

### ISSUE THREAD

**Issue by AlexTalks** [cockroachdb/cockroach#94809]
In a recent investigation, it was discovered that when we have constraints applying to some but not all the replicas needed for a range, it is possible for a replacement operation (such as during decommission) to not consider that all constraints are no longer satisfied. This occurs when we have configurations such as `num_replicas = 3, constraints = '{<some constraint>: 1}'`, and thus would expect to have 2 replicas that do not need to satisfy any constraints, known as "unconstrained replicas"; however replacement of the one replica that satisfies the constraint should not be possible.

This can be reproduced simply with the following:
```
roachprod create local -n4
roachprod stage local release v22.1.12
roachprod start local --racks=4
roachprod ssh local:1 -- './cockroach workload init kv --splits=100'
roachprod sql local:1 -- -e "alter database kv configure zone using num_replicas=3, constraints='{+rack=3: 1}';"
# wait for rebalancing
roachprod ssh local:1 -- './cockroach node decommission 4 --insecure'
# this should not succeed, but it does
```

Jira issue: CRDB-23152

**Comment by AlexTalks** [comment]
This comment on `allocateConstraintsCheck(..)` in allocator_scorer.go is interesting: https://github.com/cockroachdb/cockroach/blob/71f97128b7a5a00231d69247766857b6e61baa35/pkg/kv/kvserver/allocator/allocatorimpl/allocator_scorer.go#L1797-L1800

Except, clearly, we don't enforce this, and we allow there to be "unconstrained" replicas.  It seems that those need to be accounted for.

**Comment by irfansharif** [comment]
Nice find!

**Comment by nvanbenschoten** [comment]
cc. @joshimhoff
