### ISSUE TITLE
ui: Database page does not handle special characters

### ISSUE THREAD

**Issue by j82w** [cockroachdb/cockroach#94847]
Using the new expand schema it adds special characters into database and table names. The database page fails to load the info for several table and gets 500 responses from the server. The tables and other pages still need to verified.

To reproduce:
` ./cockroach demo --insecure --multitenant=false --expand-schema=500`

<img width="2090" alt="Screen Shot 2023-01-06 at 2 00 07 PM" src="https://user-images.githubusercontent.com/8868107/211081186-1792d9b8-9405-4bd2-a86b-27d98edb17a1.png">

url that failed: `http://127.0.0.1:8080/_admin/v1/databases/mo%20vr2?include_stats=true`

Going to the table page it fails to load, and the database name is not displayed correctly.
`Error Loading databases: RequestError: admin-show-grants: target database or schema does not exist`
<img width="2090" alt="Screen Shot 2023-01-06 at 2 04 58 PM" src="https://user-images.githubusercontent.com/8868107/211081927-bb652aba-3d3b-4f42-b576-f137ae22437d.png">

Jira issue: CRDB-23184
Epic: CRDB-20388

**Comment by knz** [comment]
Is this a new issue?
See the other issues filed here:
- https://github.com/cockroachdb/cockroach/issues/94328
- https://github.com/cockroachdb/cockroach/issues/94329
-

**Comment by j82w** [comment]
They seem to be the same. I'll close this as a duplicate.

**Comment by knz** [comment]
![image](https://user-images.githubusercontent.com/642886/211083295-b96b641f-be51-4b6b-a955-96c0066c3f24.png)
