### ISSUE TITLE
kv/multitenant: TestSecondaryTenantFollowerReadsRouting flaked on master

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#94885]
See [flake](https://teamcity.cockroachdb.com/viewLog.html?buildId=8230155&buildTypeId=Cockroach_UnitTests_BazelUnitTests) in staging on unrelated PR. 

Jira issue: CRDB-23205

**Comment by knz** [comment]
another one https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/8542709?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

**Comment by knz** [comment]
dup #95338
