### ISSUE TITLE
Node livesness for a single node removed clusters ability to serve queries on 3-node cluster

### ISSUE THREAD

**Issue by rcrowe** [cockroachdb/cockroach#94919]
**Describe the problem**

1 node on a 3-node cluster that was under pressure was able to impact the full cluster; all SQL statements become incredibly slow to the point the cluster was unusable.

**To Reproduce**

**1.** Set up CockroachDB cluster ...

A 3-node cluster running in Kubernetes, running default settings for the zone configuration

```
> SHOW ZONE CONFIGURATION FROM RANGE default;
     target     |              raw_config_sql
----------------+-------------------------------------------
  RANGE default | ALTER RANGE default CONFIGURE ZONE USING
                |     range_min_bytes = 134217728,
                |     range_max_bytes = 536870912,
                |     gc.ttlseconds = 90000,
                |     num_replicas = 3,
                |     constraints = '[]',
                |     lease_preferences = '[]'
                
> SHOW ZONE CONFIGURATION FROM RANGE liveness;
      target     |              raw_config_sql
-----------------+--------------------------------------------
  RANGE liveness | ALTER RANGE liveness CONFIGURE ZONE USING
                 |     range_min_bytes = 134217728,
                 |     range_max_bytes = 536870912,
                 |     gc.ttlseconds = 600,
                 |     num_replicas = 5,
                 |     constraints = '[]',
                 |     lease_preferences = '[]'
```

**2.** CPU saturated on one of the nodes where a CRDB pod/node is running.

- Our k8s node was at 100% CPU and system load at 700%
- CRDB N2 (yellow) below was consuming more CPU than the other nodes (N1, N3), but not all its available quota.

<img width="977" alt="Screenshot 2023-01-09 at 12 22 41" src="https://user-images.githubusercontent.com/282571/211307069-577021c0-ad76-4599-ba43-4d87d100fb1c.png">

**3.** An increase in RPC errors coinciding with the outage

<img width="977" alt="Screenshot 2023-01-09 at 12 26 51" src="https://user-images.githubusercontent.com/282571/211307765-293aa18a-1f90-4f28-bcde-aeba89cbe0cc.png">

**4.** Slow down in SQL statement latency

<img width="977" alt="Screenshot 2023-01-09 at 12 28 30" src="https://user-images.githubusercontent.com/282571/211308075-c5df5b01-a3c0-4d38-971a-2e7451d3d04b.png">

**Expected behavior**

A single node should suffer degraded performance, but a single node should not be able to take out the cluster. 

We had the default number of replicas used across default (3), liveness (5) etc so are expecting that queries both read & write should be able to succeed.

**Additional data / screenshots**

After seeing N2 with increased CPU, the latency (/reports/network) & our internal Infra dashboards for the node it was running on we managed to move that CRDB node to new K8s worker.

After N2 was scheduled elsewhere the RPC errors & SQL P90 dropped back down to normal/expected levels, which you can see from the graphs at roughly 14:00.

Note, zero changes in terms of scheduling where made to N1 & N3.

**Environment:**

 - CockroachDB version
 
```
Build Tag:        v22.1.6
Build Time:       2022/08/23 17:05:04
Distribution:     CCL
Platform:         linux amd64 (x86_64-pc-linux-gnu)
Go Version:       go1.17.11
C Compiler:       gcc 6.5.0
Build Commit ID:  760a8253ae6478d69da0330133e3efec8e950e4e
Build Type:       release
```

 - Server OS: [e.g. Linux/Distrib]
 
```
K8s: v1.24.4
Flatcar Container Linux by Kinvolk 3227.2.1
Kernel: 5.15.58-flatcar
```

**Additional context**

Our cluster suffered an outage where queries could not be responded to before timeouts kicked in.

Reading https://www.cockroachlabs.com/docs/v22.2/recommended-production-settings#topology it's not clear here if `node fails` includes a degradation of liveness or not?

> To be able to tolerate the failure of any 1 node, use at least 3 nodes with the [default 3-way replication factor](https://www.cockroachlabs.com/docs/v22.2/configure-replication-zones#view-the-default-replication-zone). In this case, if 1 node fails, each range retains 2 of its 3 replicas, a majority.

Should we be looking to change TTLs to make a node as failing sooner?

Jira issue: CRDB-23229

**Comment by knz** [comment]
Hi @rcrowe thanks for reporting this.
Could you raise this through https://support.cockroachlabs.com/hc/en-us/requests/new?
and include a link to this github issue, thanks.

**Comment by daniel-crlabs** [comment]
I'm closing this GH as we will use the support ticket you created to document our investigation. I have referenced this GH issue in your ticket. You will be notified via a separate email with any further updates via our ticketing system.
