### ISSUE TITLE
sql: missing `castfunc` in `pg_proc`

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#94955]
Found while working on #88061.

**Describe the problem**

The `castfunc` column contains all NULLs; instead it should contain the OID of the built-in functions that do the conversion.

**To Reproduce**

```sql
SELECT pg_catalog.format_type(castsource, NULL) as src,
 pg_catalog.format_type(casttarget, NULL) as dst,
 proname AS function
FROM pg_cast c
LEFT JOIN pg_proc p ON p.oid = c.castfunc
```

**Expected behavior**

The output for e.g.  the conversion from `boolean` to `text` should be `proname = 'text'`.

cc @rafiss for triage.

Jira issue: CRDB-23242

Epic CRDB-17785

**Comment by rafiss** [comment]
We currently do not use built-in functions to perform casts, though @jordanlewis _just_ started to explore that idea in https://github.com/cockroachdb/cockroach/pull/94859

**Comment by rafiss** [comment]
closed by https://github.com/cockroachdb/cockroach/pull/97093 - thanks @otan !
