### ISSUE TITLE
tests: acceptance tests don't use a consistent working directory

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#9496]
Compare:
- `make acceptance` locally calls `acceptance/run.sh` which ends up invoking `go test -tags acceptance ./acceptance -run ...`; when invoked this way, `go test` changes to the acceptance sub-dir before launching the tests and **the cwd is the acceptance/ sub-dir**.

- CircleCI and TC first compile the acceptance test binary with `go test -c`, then executes it from the top level with `./acceptance.test ...`; when invoked this way **the cwd is the top-level source dir**.

Now the reason why this matters is that some tests also read files somewhere in the source directory, using relative paths. (At least that's how I found this problem - #9087). 

Since the CCI/TC runs appear to be fine otherwise, I would recommend changing the `acceptance/run.sh` script to do the same as CCI/TC.

cc @tamird @bdarnell thoughts?

**Comment by knz** [comment]
cc @jordanlewis too

**Comment by bdarnell** [comment]
Isn't there a case where we run the acceptance tests without the source available at all? I know we did that at some point but maybe it's not there any more.

I think I'd rather resolve this in the other direction, by making TC `cd` into the `acceptance` directory, for consistency with `go test`. But I don't feel strongly about this and could go either way as long as it's consistent.

**Comment by knz** [comment]
(We use the source insofar that the source dir is mounted (bound) within the docker instances. The test I'm planning to add via #9087 uses that.)

**Comment by jordanlewis** [comment]
CircleCI actually also runs the pre-compiled acceptance.test binary, which
is why it fails in the same way as TeamCity in this PR. I think it's better
to change the run.sh script.

**Comment by knz** [comment]
I followed Ben's recommendation in https://github.com/cockroachdb/cockroach/pull/9498#issuecomment-249084635 and also changed TC's run script to change the cwd to acceptance/.
