### ISSUE TITLE
rangefeed: extremely large numbers of goroutines 

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#94969]
A customer cluster was recently observed during an unrelated escalation that had very large numbers of goroutines on each  node, between 90,000 and 100,000 on each node, the bulk of which were associated with rangefeeds.

Additional context:
In appeared that cluster had 8 active changefeed jobs. On one node, the active_range_feeds virtual table reports roughly 22,500 rows. distsender.rangefeed.total_ranges is very close to 22k on each of the 26 nodes in the cluster.  On this cluster each node has 12 stores, so the number of ranges and thus rangefeeds handled per process can be higher than it perhaps is in smaller, single-store processes that are storage limited.

Jira issue: CRDB-23249

**Comment by miretskiy** [comment]
Fixed via mux rangefeed.
