### ISSUE TITLE
improve race test performance

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#9499]
We have had to increase the RACETIMEOUT to 10m (#9497) to accommodate for slow runs of race tests on CircleCI. Improving the performance of these tests might fix underlying issues as well as improve developer productivity.

**Comment by petermattis** [comment]
@vivekmenezes Is there anything specific to fix here? I'd prefer to close if the answer is no.

**Comment by petermattis** [comment]
@vivekmenezes Race tests are slow by nature. I'm going to close this in the absence of something actionable.

**Comment by vivekmenezes** [comment]
SGTM
