### ISSUE TITLE
kv: DistSender sends requests outside of the current tenant's keyspace

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#95003]
**Describe the problem**

Found by @yuzefovich here: https://github.com/cockroachdb/cockroach/pull/94388#issuecomment-1366996983

> when committing the txn we issue EndTxnRequest in which we don't set Key nor EndKey. Then, in DistSender.Send we construct rs which covers all requests in the BatchRequest, and we end up with something like rs = roachpb.RSpan{keys.RKeyMin, keys.RKeyMax}

That span include keys outside of the tenant's keyspace. It violates the requirement that all KV requests emitted by a tenant should be bounded by that tenant's logical keyspace boundaries.

**To Reproduce**

See the linked issue.

**Expected behavior**

DistSender should truncate requests to the intersection with the tenant keyspace boundaries.

Jira issue: CRDB-23267

Epic CRDB-23344

**Comment by knz** [comment]
@rafiss @yuzefovich the folk in the multi-tenant team are worried about this issue, which seems to block this PR:  #94388. 

What do you think we should do here?  do we already know what is the cause of these out-of-bound requests? What team should own the resolution?

**Comment by yuzefovich** [comment]
Based on my last [comment](https://github.com/cockroachdb/cockroach/pull/94388#issuecomment-1366996983) in #94388 I didn't know what the right solution was, and to me it seems like the KV team is best suited to tackle it.

**Comment by knz** [comment]
@nvanbenschoten could I kindly request your scrutiny of the issue description at top. Is there a particular reason we use min/max as resulting rs bounds when the batch contains just EndTxn? Would we be comfortable using the tenant's logical key bounds or even an empty span in that case?

**Comment by nvanbenschoten** [comment]
> when committing the txn we issue EndTxnRequest in which we don't set Key nor EndKey. Then, in DistSender.Send we construct rs which covers all requests in the BatchRequest, and we end up with something like rs = roachpb.RSpan{keys.RKeyMin, keys.RKeyMax}

Was this determined through code analysis or through instrumentation? In other words, did we actually see `rs = roachpb.RSpan{keys.RKeyMin, keys.RKeyMax}`? We assign the `Key` to the `EndTxnRequest` here:
https://github.com/cockroachdb/cockroach/blob/76d67194bc3cd13191334f1599dae5f92392ff7d/pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go#L151

**Comment by yuzefovich** [comment]
I just rebased #94388 on top of master. On that SHA, if we use the following logic test
```
# LogicTest: 3node-tenant

# Regression test for not propagating lock spans with leaf txns (#94290).
statement ok
CREATE TABLE t94290 (a INT, b INT, c INT, PRIMARY KEY(a), UNIQUE INDEX(b));
INSERT INTO t94290 VALUES (1,2,3);

# If the lock spans are not propagated, then the second query would take almost
# 5 seconds.
statement ok
SET statement_timeout = '2s';

statement ok
SELECT * FROM t94290 WHERE b = 2 FOR UPDATE;

statement ok
SELECT * FROM t94290 WHERE b = 2 FOR UPDATE;

statement ok
RESET statement_timeout;
```
and run it via debugger, then we see that `ba.Txn.Key` is `nil` in the line that Nathan linked:

![Screenshot 2023-03-07 at 4 07 23 PM](https://user-images.githubusercontent.com/5135385/223584544-eb1cb058-eca7-4675-816e-0bd8b3c68584.png)

so `EndTxnRequest.Key` remains `nil` too.

**Comment by nvanbenschoten** [comment]
> I just rebased https://github.com/cockroachdb/cockroach/pull/94388 on top of master.

So this issue is describing an issue with #94388, not an issue on master, right? If so, can we close this issue?

@yuzefovich do you mind if we hold off on https://github.com/cockroachdb/cockroach/pull/94388 for the time being, based on the callout in https://github.com/cockroachdb/cockroach/pull/94399#issuecomment-1367392874? We are planning to make a large investment in the planning and execution of SELECT FOR UPDATE in the next release which may be complicated by https://github.com/cockroachdb/cockroach/pull/94388 and which will reduce the importance of letting LeafTxns acquire locks.

**Comment by nvanbenschoten** [comment]
> then we see that ba.Txn.Key is nil

We assign a transaction's key when it performs its first locking operation, either a write or a locking read. This is done in the `txnHeartbeater`, which only exists in `RootTxn`s. So I suspect that we're seeing the result of the first (and only) locking read going through a `LeafTxn` and the transaction never being assigned a key. When it goes to commit, it then issues an EndTxn without a key to anchor it at. This would only be possible with https://github.com/cockroachdb/cockroach/pull/94388. It also indicates a flaw in the approach taken by https://github.com/cockroachdb/cockroach/pull/94388 — we can't let a `LeafTxn` perform locking reads before the transaction has been assigned an anchor key and has started its heartbeat loop.

**Comment by yuzefovich** [comment]
I see, thanks for the explanation. I'll close #94388 then referencing this comment, and also closing this issue given that it's not an actual issue. Thanks everyone for the input!
