### ISSUE TITLE
CORE CHANGEFEED show nothing even insert/update/delete

### ISSUE THREAD

**Issue by kocoten1992** [cockroachdb/cockroach#95044]
**Describe the problem**

I've a pretty nasty bug on production (old cluster - will create a separated issue for that), decided to turn on changefeed to see what happen, bute changefeed show nothing even insert/update/delete.

**To Reproduce**
Hard to reproduce, it work on a newly created cluster, on an old cluster it is not working (both are in version 22.1.11)

What did you do? Describe in your own words.
1. turn on CHANGEFEED feature on SET CLUSTER SETTING (I tripple check this).
2. manually insert/update/delete a few records in a table to check if it work.
3. it does not show anything (on an old cluster), but it working as expected on new cluster.

**Expected behavior**
I actually trying to debug an error where database report updated record, but it is actually not - that why I turn on CHANGEFEED to see what happen, only to discover it not working too.

**Additional data**
Most likely this is unactionable (I've check log nothing show up). Just want to let you know and maybe some advice (I'm fine with nuking this cluster and start afresh).

**Environment:**
 - CockroachDB version [e.g. 22.1.11]
 - Server OS: Ubuntu 22.10
 - Client app `cockroach sql`

Jira issue: CRDB-23290

**Comment by kocoten1992** [comment]
Hi @yuzefovich , I could reliably replicate this issue (by copy the whole `cockroach-data` and point `cockroach` `v22.1.11` binary to it).

And managed to fix that by migrate to `v22.2.2` (from `v22.1.11`), just letting you know if someone run into this, migrate to 22.2.2 will fix it.

However 22.2.2 also have an issue (I've create an issue for that #95053).

I'm not sure whether this is worth fixing, so I'm going to close it, if you think otherwise please let me know (I'll send `cockroach-data`).

**Comment by yuzefovich** [comment]
cc @miretskiy
