### ISSUE TITLE
sql,backupccl: partial stats are not included in backup

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#95056]
**Describe the problem**

The backup code uses the stats cache to retrieve table statistics for backup.  

https://github.com/cockroachdb/cockroach/blob/5eb4574842afe7d953e4694e976c6db5401c19f7/pkg/ccl/backupccl/backup_job.go#L357

As a result, we only back up what the stats cache returns and it doesn't return partial statistics.

https://github.com/cockroachdb/cockroach/blob/5eb4574842afe7d953e4694e976c6db5401c19f7/pkg/sql/stats/stats_cache.go#L823

While it does return "merged" statistics which at least contains the estimates produce in those statistics, those will be excluded from the backup after #94992.

One option here is to stop using the stats cache for retrieving the statistics and instead create some new, more appropriate API.

Jira issue: CRDB-23298

**Comment by michae2** [comment]
I think we're going to want the optimizer to see partial stats eventually anyway, so I can make this change.
