### ISSUE TITLE
Optimisation: Don't rewrite a row if there are no changes

### ISSUE THREAD

**Issue by smcvey** [cockroachdb/cockroach#95064]
**Is your feature request related to a problem? Please describe.**

Rows without changes are still written out.

```
CREATE TABLE t (id int PRIMARY KEY, text STRING);
INSERT INTO t VALUES (1, 'hello');
UPDATE t SET text = 'hello' WHERE id = 1;
```

Despite no changes to the row (other than the updated mvcc timestamp), this update still gets written out.  As the row is read beforehand anyway, this request is to add an optimisation which would compare the two rows for differences before writing it back out.  Perhaps this could be a cluster setting to enable this for those purist customers who want their mvcc timestamps to continue updating regardless.

Jira issue: CRDB-23301

**Comment by jameslupolthrd** [comment]
Thank you for creating this. This optimization (called "non-updating updates" on some other platforms such as SQL Server) could reduce service latency and write overhead in a few scenarios I've seen. One might question why anyone would write an update query that updates a row to its current values, but I've seen code that does this rather often, sometimes due to a naive implementation or an ORM. I don't know whether the overhead of comparing to the current values would make this worthwhile, but it seems worth exploring.

**Comment by mgartner** [comment]
This is an interesting idea! Thanks for sharing.

In `SERIALIZABLE` isolation, I think this optimization is valid. However, in weaker isolation modes, like `READ COMMITTED`, which we plan to support in the future, you can't replace the write with a read. It's important to update the MVCC timestamp regardless of whether or not any values actually changed.

Notice that Postgres does performs the write for an identity `UPDATE`:

```
pg=# CREATE TABLE t (k INT PRIMARY KEY, v INT);
CREATE TABLE

pg=# INSERT INTO t VALUES (1, 10);
INSERT 0 1

pg=# SELECT ctid, k, v FROM t;
 ctid  | k | v
-------+---+----
 (0,1) | 1 | 10
(1 row)

pg=# UPDATE t SET v = 10 WHERE k = 1;
UPDATE 1

pg=# SELECT ctid, k, v FROM t;
 ctid  | k | v
-------+---+----
 (0,2) | 1 | 10
(1 row)
```

You can alwasys add a `WHERE` clause which performs the comparison you are describing:

```sql
UPDATE t SET text = 'hello' WHERE id = 1 AND text != 'hello'
```

Thanks again for the suggestion! I'm going to close this for now.

**Comment by jameslupolthrd** [comment]
Thank you for looking into this. Out of curiosity, could you elaborate on why this wouldn't work on weaker isolation levels? I don't follow what the problem would be under `read commited`.

**Comment by michae2** [comment]
> Thank you for looking into this. Out of curiosity, could you elaborate on why this wouldn't work on weaker isolation levels? I don't follow what the problem would be under `read committed`.

Actually, now that I've played with it a bit, I haven't been able to find a difference in Postgres behavior under `read committed` between a `SELECT FOR UPDATE` and an `UPDATE` that doesn't change anything. Maybe someone else can point one out?

In CockroachDB there are currently some differences between `SELECT FOR UPDATE` and an `UPDATE` that doesn't change anything. `SELECT FOR UPDATE` locks are implemented differently from `UPDATE` intents. Some of these differences might go away in the future.
