### ISSUE TITLE
sqlstats: use int32, not int64, for node IDs

### ISSUE THREAD

**Issue by matthewtodd** [cockroachdb/cockroach#95088]
Since `roachpb.NodeID` and `base.SQLInstanceID` are both aliases for `int32`, I think we've been sloppy using `int64` in `sqlstats.RecordedStmtStats.Nodes`. Switching would remove some unnecessary casts in the code I'm working on now.

Jira issue: CRDB-23320

**Comment by valxntine** [comment]
Happy to pick this up if it's still available

**Comment by matthewtodd** [comment]
Thanks, @valxntine and @andrew-delph, I've moved on from Cockroach, so @maryliag's your best contact if you want to think through approaches here.

**Comment by dush-t** [comment]
Hi, would like to pick this up if available :)

**Comment by maryliag** [comment]
Thank you all for wanting to contribute!

As Andrew mention, this issue will required more changes than initially expected. Also, those are some changes we don't want to make on proto files right now. So I will be closing this issue.

I really appreciate all of you wanting to work on this, and I hope you can find some other great [good first issues](https://github.com/cockroachdb/cockroach/labels/good%20first%20issue) to take a look at! 😄
