### ISSUE TITLE
backupccl: `BACKUP TENANT` should accept a name instead of an ID

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#95149]
Now that tenant's are name addressable, we should teach `BACKUP TENANT` to accept a name instead of an ID.

Epic CRDB-27614
Jira issue: CRDB-23370

**Comment by stevendanna** [comment]
Thanks for filing this!  Let's do this once https://github.com/cockroachdb/cockroach/pull/94932 is merged.

**Comment by stevendanna** [comment]
Closing as dup of #95279
