### ISSUE TITLE
A node that is offline for a short period can cause a performance issue when it rejoins the cluster

### ISSUE THREAD

**Issue by andrewbaptist** [cockroachdb/cockroach#95159]
**Describe the problem**

In several customer cases, we have seen a node rejoin a cluster after it is offline for a short period of time. During the time it is offline, replicas that are on that node begin upreplicating to other nodes, however in many cases when it comes back it still is the owner of a number of replicas. These replicas all begin to attempt to catch up with their raft log when the node is back and this can cause a severe IO spike on the node. In many cases, this causes LSM inversion, and admission control will throttle writes to this store.  In addition, leases begin to be transferred onto this node which compounds the problem. 

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up a cluster (12 nodes) with a 50% KV workload with 20K splits and 8K block writes.
2. Take one node down, wait 10 minutes and then bring the node back on.
4. Approximately 1-2 minutes after the node is restarted and all IO to the node will stop. This continues on for about 3-5 minutes. 

**Expected behavior**
There should be no noticeable impact of stopping and restarting a node.

**Additional data / screenshots**
![image](https://user-images.githubusercontent.com/46975918/212140448-47dc0dd3-20dc-4c32-a3c3-f70e508682f7.png)

**Environment:**
 - CockroachDB version - master

Jira issue: CRDB-23378

**Comment by andrewbaptist** [comment]
@kvoli and I spend a long time looking at this in detail especially related to what it would take to prevent this completely. Ideally, all the fixes for this can be done in the allocator without adding a new state. The issue today is the following sequence after the node restarts (and is ~2GB behind on raft logs)

<img width="1175" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/46975918/219484223-a76d0038-046a-4911-81c6-e044ab6a1d7f.png">

1) The store publishes its liveness, all the other stores immediately see it as live and begin to transfer leases
2) The lease transfers are at the "back of the queue" and wait ~1-2 minutes to be seen by the store. Fortunately, #81764 had previously been implemented so these are expiration, not epoch leases. 
3) The other stores realize after 9 seconds that there is no leaseholder for these ranges and they are the leader. The leader gets the lease back.

The restarting store eventually (after ~45 sec) gets to IO overload and other stores stop sending more leases to it after #96521 is implemented. 

There are two additional changes that are related to this that we should consider. 
1) Treating IO overloaded stores as suspect and preventing transfers for a window of time. #97265 
2) Prevent lease transfers to stores that are behind #96304

**Comment by kvoli** [comment]
Completed by work done in https://github.com/cockroachdb/cockroach/issues/96521
- https://github.com/cockroachdb/cockroach/pull/97532
- https://github.com/cockroachdb/cockroach/pull/97587
