### ISSUE TITLE
Replace http-addr flag with http-host for consistency

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#9516]
Correct me if I'm wrong, but I'd guess we don't want to remove `http-addr` at the same time that we add `http-host`, since it'll annoy people and make our docs incorrect for at least some small time period.

I assume it's good enough to add the new flag with precedence over the old one, wait for a new beta release, then update the docs and remove the old one?

As discussed in #9503

@mberhault @sploiselle

**Comment by tamird** [comment]
It may also be the case that nobody is using http-addr in practice, which would make this simpler.

**Comment by sploiselle** [comment]
In favor of that plan, @a-robinson. Always prefer gentle deprecation even if it's not much more than a gesture of general good will. Switching it in the docs, assuming it exactly duplicates the functionality, is simple.

Can we include an error message for `http-addr` that just spits back that it's now `http-host`? If it's more than nominal effort, think we can get by without it.

**Comment by a-robinson** [comment]
Adding Sean to get the docs updated with the http-host flag. Once they're updated and a new release has been cut, I'll remove http-addr.
