### ISSUE TITLE
roachtest,roachprod: remove checks for Pebble's CURRENT file

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#95170]
As of https://github.com/cockroachdb/pebble/pull/1227, Pebble no longer creates or maintains a `CURRENT` file. However, `roachtest` [1] and `roachprod` [2] still check for this file.

We should remove such checks or replace them with something appropriate as their existence is wrong and confusing.

[1] https://github.com/cockroachdb/cockroach/blob/241f613f2339c63d7294a3ca10bdd94f33dbbbf2/pkg/cmd/roachtest/tests/versionupgrade.go#L377-L378

[2] https://github.com/cockroachdb/cockroach/blob/241f613f2339c63d7294a3ca10bdd94f33dbbbf2/pkg/roachprod/install/cluster_synced.go#L549-L552

Jira issue: CRDB-23382

**Comment by srosenberg** [comment]
Thanks for creating the issue! I was almost convinced this was a dupe, but alas it was sitting in my notes,

> Below PR [1] introduces "roachtest monitor <cluster> --oneshot --ignore-empty-nodes" which was in 2019. It skips nodes without {{.Store}}/CURRENT in its primary store.
This check is out-of-date since pebble is no longer using CURRENT as of https://github.com/cockroachdb/pebble/pull/1227

> Replace by checking version marker?

```
roachprod run srosenberg-1664666378-01-n5cpu16 "ls /mnt/data1/cockroach/marker.format-version.*"
srosenberg-1664666378-01-n5cpu16: ls /mnt/data1/cockroach/mar... 5/5
   1: /mnt/data1/cockroach/marker.format-version.000001.006
   2: /mnt/data1/cockroach/marker.format-version.000001.006
   3: /mnt/data1/cockroach/marker.format-version.000001.006
   4: /mnt/data1/cockroach/marker.format-version.000001.006
   5: ls: cannot access '/mnt/data1/cockroach/marker.format-version.*': No such file or directory
```

[1] https://github.com/cockroachdb/cockroach/pull/36224

**Comment by smg260** [comment]
On further inspection, it doesn't appear that `assertNoDeadNode` is not actually asserting anything of the sort. The function assumes a node is dead if an `error` is returned from the call to `roachprod.Monitor(...)` [1], but that function only returns an error when there is an issue with initialising the `SyncedCluster`[2], which precedes the actual dead node check. 

We *should* be inspecting the contents of the `NodeMonitorInfo` sent on the channel (1 message per node) returned by `c.Monitor`, which contains a message string we can check for `skipped`, or a PID indicating a running node.

The PR resolving this issue will be updated to include this, along with some additional logging.

[1] - https://github.com/cockroachdb/cockroach/blob/7aa696723b2da7c13b18d59bf427f58ac6619e06/pkg/cmd/roachtest/cluster.go#L1341

[2] - https://github.com/cockroachdb/cockroach/blob/7aa696723b2da7c13b18d59bf427f58ac6619e06/pkg/roachprod/roachprod.go#L702-L706
