### ISSUE TITLE
security: Lock down logging of SQL queries

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#9519]
SQL queries can often contain sensitive information, so we should be careful about where we log them. In particular, #8949 made SQL query logs network-accessible by losing the "sensitive" bit on the trace API (the "sensitive" bit made them localhost-only, which is better than nothing although it should still require opt-in to log sql queries to anything without proper authentication). This is very useful for debugging but we'll have to limit the visibility of these logs (or make it opt-in) before we're production-ready.

**Comment by spencerkimball** [comment]
PR #13366 helps with this, though it sounds like we should disable the tracing by default. See #14589.
