### ISSUE TITLE
sql: better terminology to determine if a function is a UDF

### ISSUE THREAD

**Issue by chengxiong-ruan** [cockroachdb/cockroach#95214]
**Describe the problem**
Currently we use `IsUDF` to label a function overload as UDF or not. This is a bit confusing when we introduce several builtin functions which has the flag set to `true` to have the executor execute it as a UDF. One observation is that if you tried to do schema changes on a builtin function which has `IsUDF=true`, the error message is not very informational:
```sql
drop function pg_catalog.shobj_description;
ERROR: function 0 does not exist: function undefined
SQLSTATE: 42883
```
This is because the function resolution thought it's a UDF because `IsUDF=true` but there is no descriptor for it.
It should behave similarly as normal builtin functions, for example:
```sql
demo@127.0.0.1:26257/defaultdb> drop function pg_catalog.version;
ERROR: cannot drop function version() -> string because it is required by the database system
```
So 2 things are needed to address this:
(1) a better way to determine if a overload is UDF or not, checking OID is a good option.
(2) replace `IsUDF` flag with something better, as long as the executor knows how to execute it.

Jira issue: CRDB-23407

**Comment by mgartner** [comment]
This was fixed by https://github.com/DrewKimball/cockroach/commit/571685139fe7097bfd296b80a348f5e0f62f921f. Closing.

**Comment by chengxiong-ruan** [comment]
Thanks for fixing it @DrewKimball !
