### ISSUE TITLE
sql/stats: add variables to disable partial statistics merging and usage

### ISSUE THREAD

**Issue by michae2** [cockroachdb/cockroach#95233]
Filing an issue for this TODO: https://github.com/cockroachdb/cockroach/blob/d7135c364280b916ff1dd63b13c23a177c6e451c/pkg/sql/stats/stats_cache.go#L811-L812

Now that we've introduced merging of partial statistics, we should add one or more variables to disable it if necessary.

Jira issue: CRDB-23413

Epic: CRDB-19449

**Comment by DrewKimball** [comment]
Reopening because it looks like we'd still produce merged statistics for _existing_ partial stats.
