### ISSUE TITLE
sql: flake in TestCancelQuery

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#95273]
Found here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/8324602?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

```
Failed
=== RUN   TestCancelQuery/ignore_unknown_secret_key
    proxy_handler_test.go:1031: condition failed to evaluate within 45s: expected metrics to update, got: QueryCancelSuccessful=1, QueryCancelIgnored=0 QueryCancelForwarded=0 QueryCancelReceivedPGWire=0 QueryCancelReceivedHTTP=0
    --- FAIL: TestCancelQuery/ignore_unknown_secret_key (45.14s)
```

May or may not be related to #95002

cc @rafiss for triage.

Jira issue: CRDB-23439

**Comment by rafiss** [comment]
This is now stabilized
