### ISSUE TITLE
tracing: Transaction retries can consume unbounded memory

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#9529]
In #9522 (which caused transactions to retry endlessly), we saw unbounded memory growth in the tracer subsystem. We need to make sure that our tracers are able to handle huge numbers of events gracefully, by discarding old events rather than accumulating them. It looks like both net/trace and lightstep do this, but basictracer does not.

**Comment by petermattis** [comment]
@RaduBerinde given your other recent tracing work, can you take a look at this? Seems to be outside of our code, but we've made changes to basictracer in the past.

**Comment by RaduBerinde** [comment]
I think that for net/trace purposes we can simply set `DropAllLogs` to avoid storing them in basictracer altogether.

However, lightstep also uses basictracer internally. We would need to add an option to both basictracer and to lightstep. I'll file an issue with lightstep and see if they would be ok with that (assuming I do the basictracer change).

**Comment by tschottdorf** [comment]
See https://github.com/opentracing/basictracer-go/issues/38 for @RaduBerinde's upstream issue.

**Comment by RaduBerinde** [comment]
https://github.com/opentracing/basictracer-go/pull/39
