### ISSUE TITLE
stability: race-enabled build periodically crashes

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#9533]
rho nodes have been crashing periodically on odd panics.

This has been occurring for a while on different builds, including those using go1.7 and go1.7.1.

about half the time, we get:

```
unexpected fault address 0x600087100000
fatal error: fault
```

which supervisor logs tell us was `terminated by SIGSEGV`

The other half has a stack trace:

```
unexpected fault address 0x6000850c0000
fatal error: fault
fatal error: unexpected signal during runtime execution
panic during panic

runtime stack:
runtime.startpanic_m()
        /usr/local/go/src/runtime/panic.go:623 +0xfc
runtime.systemstack(0xc425ed5a40)
        /usr/local/go/src/runtime/asm_amd64.s:298 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1079

goroutine 38 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:252 fp=0x7f8e1f9feb08 sp=0x7f8e1f9feb00
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:189 +0x74
```

which is `exit status 2`, something returned by go's runtime.

Crashes are surprisingly regular:
<img width="936" alt="screen shot 2016-09-26 at 11 10 31 am" src="https://cloud.githubusercontent.com/assets/5901480/18829283/e0ce6d50-83db-11e6-88a4-142305642ffb.png">

Looking at restart times, we see that nodes are restarting every 24-27h:

```
$ crl-ssh rho all 'grep -w built logs/cockroach.stderr logs/cockroach.stderr.1 | cut -d":" -f2- | sort | tail -n 5'
0: cockroach@104.196.18.63
I160921 06:59:50.513881 1 cli/start.go:342  CockroachDB beta-20160915-79-g980bce0 (linux amd64, built 2016/09/17 18:36:57, go1.7.1)
I160922 08:01:49.556020 1 cli/start.go:342  CockroachDB beta-20160915-79-g980bce0 (linux amd64, built 2016/09/17 18:36:57, go1.7.1)
I160923 09:05:48.599962 1 cli/start.go:342  CockroachDB beta-20160915-79-g980bce0 (linux amd64, built 2016/09/17 18:36:57, go1.7.1)
I160924 10:31:44.583192 1 cli/start.go:342  CockroachDB beta-20160915-79-g980bce0 (linux amd64, built 2016/09/17 18:36:57, go1.7.1)
I160925 11:42:31.462730 1 cli/start.go:342  CockroachDB beta-20160915-79-g980bce0 (linux amd64, built 2016/09/17 18:36:57, go1.7.1)

1: cockroach@104.196.102.49
I160921 07:47:18.583679 1 cli/start.go:342  CockroachDB beta-20160915-79-g980bce0 (linux amd64, built 2016/09/17 18:36:57, go1.7.1)
I160922 09:41:11.039553 1 cli/start.go:342  CockroachDB beta-20160915-79-g980bce0 (linux amd64, built 2016/09/17 18:36:57, go1.7.1)
I160923 11:18:58.491665 1 cli/start.go:342  CockroachDB beta-20160915-79-g980bce0 (linux amd64, built 2016/09/17 18:36:57, go1.7.1)
I160924 12:45:19.311660 1 cli/start.go:342  CockroachDB beta-20160915-79-g980bce0 (linux amd64, built 2016/09/17 18:36:57, go1.7.1)
I160925 12:42:38.517202 1 cli/start.go:342  CockroachDB beta-20160915-79-g980bce0 (linux amd64, built 2016/09/17 18:36:57, go1.7.1)

2: cockroach@104.196.147.189
I160921 13:32:09.917506 1 cli/start.go:342  CockroachDB beta-20160915-79-g980bce0 (linux amd64, built 2016/09/17 18:36:57, go1.7.1)
I160922 16:38:33.376164 1 cli/start.go:342  CockroachDB beta-20160915-79-g980bce0 (linux amd64, built 2016/09/17 18:36:57, go1.7.1)
I160923 19:00:57.608280 1 cli/start.go:342  CockroachDB beta-20160915-79-g980bce0 (linux amd64, built 2016/09/17 18:36:57, go1.7.1)
I160924 21:34:33.789324 1 cli/start.go:342  CockroachDB beta-20160915-79-g980bce0 (linux amd64, built 2016/09/17 18:36:57, go1.7.1)
I160926 00:04:18.979105 1 cli/start.go:342  CockroachDB beta-20160915-79-g980bce0 (linux amd64, built 2016/09/17 18:36:57, go1.7.1)

3: cockroach@104.196.164.29
I160921 10:51:49.754051 1 cli/start.go:342  CockroachDB beta-20160915-79-g980bce0 (linux amd64, built 2016/09/17 18:36:57, go1.7.1)
I160922 13:23:32.361206 1 cli/start.go:342  CockroachDB beta-20160915-79-g980bce0 (linux amd64, built 2016/09/17 18:36:57, go1.7.1)
I160923 15:21:25.000510 1 cli/start.go:342  CockroachDB beta-20160915-79-g980bce0 (linux amd64, built 2016/09/17 18:36:57, go1.7.1)
I160924 17:16:45.378190 1 cli/start.go:342  CockroachDB beta-20160915-79-g980bce0 (linux amd64, built 2016/09/17 18:36:57, go1.7.1)
I160925 19:09:55.772929 1 cli/start.go:342  CockroachDB beta-20160915-79-g980bce0 (linux amd64, built 2016/09/17 18:36:57, go1.7.1)
```

**Comment by tamird** [comment]
I've deployed the latest build from master (5f288d0e7bdede9f568f1a2ccd334bd6a04dadc2), whihc seems to have unwedged the largely dead cluster.

![screen shot 2016-10-05 at 17 19 38](https://cloud.githubusercontent.com/assets/1535036/19132082/06208bba-8b20-11e6-8b22-42bb05d319ee.png)
![screen shot 2016-10-05 at 17 20 16](https://cloud.githubusercontent.com/assets/1535036/19132083/0621fc7a-8b20-11e6-812e-fe3814662abc.png)
![screen shot 2016-10-05 at 17 20 10](https://cloud.githubusercontent.com/assets/1535036/19132081/06201d1a-8b20-11e6-896a-b6451a7e4d18.png)
![screen shot 2016-10-05 at 17 19 48](https://cloud.githubusercontent.com/assets/1535036/19132084/062380ea-8b20-11e6-8917-abd829454213.png)

**Comment by tamird** [comment]
4 hours ago, the cluster very abruptly ground to a halt.

<img width="942" alt="screen shot 2016-10-06 at 00 31 44" src="https://cloud.githubusercontent.com/assets/1535036/19140596/837cd5b4-8b5c-11e6-8f80-986e77ca89d3.png">
<img width="938" alt="screen shot 2016-10-06 at 00 32 17" src="https://cloud.githubusercontent.com/assets/1535036/19140593/837af5a0-8b5c-11e6-8543-877cb12566e2.png">
<img width="944" alt="screen shot 2016-10-06 at 00 32 09" src="https://cloud.githubusercontent.com/assets/1535036/19140597/837d2352-8b5c-11e6-929f-ad955f003e71.png">
<img width="941" alt="screen shot 2016-10-06 at 00 31 52" src="https://cloud.githubusercontent.com/assets/1535036/19140595/837c8ec4-8b5c-11e6-9180-c92d0bc1481e.png">
<img width="945" alt="screen shot 2016-10-06 at 00 33 12" src="https://cloud.githubusercontent.com/assets/1535036/19140594/837c67be-8b5c-11e6-9c83-a5a0866a72cf.png">
<img width="939" alt="screen shot 2016-10-06 at 00 32 53" src="https://cloud.githubusercontent.com/assets/1535036/19140598/837f4470-8b5c-11e6-90fa-9a61bdda3edf.png">
<img width="946" alt="screen shot 2016-10-06 at 00 32 36" src="https://cloud.githubusercontent.com/assets/1535036/19140599/83842184-8b5c-11e6-97f7-8c57e3622715.png">
<img width="943" alt="screen shot 2016-10-06 at 00 32 29" src="https://cloud.githubusercontent.com/assets/1535036/19140600/838701d8-8b5c-11e6-8828-57a67eba2be4.png">

**Comment by tamird** [comment]
Looks like nodes have been restarting constantly:

<img width="925" alt="screen shot 2016-10-10 at 03 17 34" src="https://cloud.githubusercontent.com/assets/1535036/19228984/2ab7bcc0-8e98-11e6-9245-4c75993cd485.png">

Oddly, alerting fails to have noticed most of these.

**Comment by bdarnell** [comment]
@tamird those IP addresses belong to delta (where this behavior is expected), not rho.

**Comment by tschottdorf** [comment]
Haha, glad to see I'm not the only one who has gotten mixed up there.

**Comment by tamird** [comment]
D'oh. Nevetheless, looks like all of `rho` got restarted last night?

![screen shot 2016-10-10 at 11 55 25](https://cloud.githubusercontent.com/assets/1535036/19242278/7bb374d2-8ee0-11e6-8274-7c84a5995933.png)

**Comment by mberhault** [comment]
surprisingly, we haven't seen those in a few months. go version upgrade?
Either way, we were kind of stuck here. closing.

**Comment by asubiotto** [comment]
`cerulean` crashed with the same issue. This is using go 1.8.

**Comment by tamird** [comment]
Seems possibly related to https://github.com/golang/go/issues/16171
