### ISSUE TITLE
kv: flake in TestChangeReplicasGeneration

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#95351]
Found here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/8343686?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

```
Failed
=== RUN   TestChangeReplicasGeneration
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/d220ac54548e03726afbc72442fd0656/logTestChangeReplicasGeneration891072375
    test_log_scope.go:79: use -show-logs to present logs inline
    client_replica_test.go:2647: unexpected error: cannot remove learner while snapshot is in flight
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/d220ac54548e03726afbc72442fd0656/logTestChangeReplicasGeneration891072375
--- FAIL: TestChangeReplicasGeneration (1.57s)
```

cc @erikgrinaker for triage.

Jira issue: CRDB-23471

**Comment by andreimatei** [comment]
Happened also in `TestLearnerOrJointConfigAdminRelocateRange`:
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/8345618?showRootCauses=false&expandBuildChangesSection=true&expandBuildTestsSection=true&expandBuildProblemsSection=true

**Comment by erikgrinaker** [comment]
Going to close this out as stale. There's some work to improve the general problem of `cannot remove learner while snapshot is in flight` in #98672 and #99099.
