### ISSUE TITLE
sql: DROP FUNCTION does not delete function descriptor

### ISSUE THREAD

**Issue by chengxiong-ruan** [cockroachdb/cockroach#95364]
**Describe the problem**

Currently when we drop a function through the legacy schema changer, we only removed it from the schema descriptor and set it to `DROPPED`. This leaves behind an idle descriptor not touched by anything (not one can see it because there is no way to resolve this function). 

**Expected behavior**
We should properly delete function descriptor after `DROP`

Jira issue: CRDB-23483

**Comment by postamar** [comment]
The immediate concern is to fix release-22.2 to actually delete the descriptor. The other aspect of this work is that a cluster upgrade is required in 23.1 to delete the dropped function descriptors in `system.descriptor`. I suspect that this can be expressed as a SQL query using `crdb_internal.unsafe_delete_descriptor`.
