### ISSUE TITLE
sql: we should rollback SQL transactions when the SQL is draining

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#9541]
Nothing rolls back ongoing transactions when a node is going down, which means intents might be left over. We should also close the root spans of ongoing transactions.
There's a SQL drain hook in `cli` that Tobi showed me that we could us; it currently waits for some time for all client connections to be dropped (which seems like a pointless thing to do).
Then the stopper prevents the pg listener from accepting new connections.

cc @knz

**Comment by spencerkimball** [comment]
@asubiotto ping. Is this work you're planning to tackle this month? If not, please change the milestone.

**Comment by asubiotto** [comment]
This was resolved in https://github.com/cockroachdb/cockroach/pull/13274. Forgot to link the issue.
