### ISSUE TITLE
sql: unable to add comments to virtual views

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#95427]
**Describe the problem**

As a CRDB engineer, I am currently unable to decorate an explanatory comment on a virtual view like `crdb_internal.ranges`.

**Expected behavior**

I'd like a `comment` field on the `virtualSchemaView` struct and have that comment propagate to the catalog (and `crdb_internal.kv_catalog_comments`).

cc @postamar for triage

Jira issue: CRDB-23512

**Comment by ajwerner** [comment]
This just requires adding a `comment` field in `virtualSchemaView` like we have in `virtualSchemaTable`. https://github.com/cockroachdb/cockroach/blob/af6a72a622ae05f3733b5db637403b3eaa9455f1/pkg/sql/virtual_schema.go#L141-L145
