### ISSUE TITLE
rpc: we're not enforcing one tenant not talking gRPC to another tenant

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#95465]
A tenant is supposed to only be able to make RPCs to servers from the same tenant, and to KV. But we're missing checks for the first part - as far as CRDB is concerned, I think one tenant can call into any other. In CC we have network-level protection against this.

I've briefly looked into adding the missing checks, but I failed to do something good with the current code structure. There's [this code](https://github.com/cockroachdb/cockroach/blob/9fc497abc81e851d441733a019c515464c6ff742/pkg/rpc/auth.go#L142-L150) which deals with authenticating the caller, but as written it doesn't even return a tenant ID when the receiver is a tenant server, so the [authorization code](https://github.com/cockroachdb/cockroach/blob/9fc497abc81e851d441733a019c515464c6ff742/pkg/rpc/auth.go#L68) is inhibited.

cc @ajstorm 

Jira issue: CRDB-23525

**Comment by knz** [comment]
fixed by #96152
