### ISSUE TITLE
rttanalysis: TestBenchmarkExpectation/ORMQueries has been flaky off late

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#95510]
TestBenchmarkExpectation/ORMQueries has become increasingly flaky off late - https://teamcity.cockroachdb.com/project.html?projectId=Cockroach_Ci_TestsGcpLinuxX8664BigVm&buildTypeId=&tab=testDetails&testNameId=3461524908469129477&order=TEST_STATUS_DESC&branch_Cockroach_Ci_TestsGcpLinuxX8664BigVm=__all_branches__&itemsCount=50

Most of the failures seem to be of the form:
```
TestBenchmarkExpectation/ORMQueries/django_table_introspection_8_tables
    rtt_analysis_bench.go:206: ORMQueries/django_table_introspection_8_tables: got 3, expected 5
```

Jira issue: CRDB-23564

**Comment by adityamaru** [comment]
cc: @rafiss

**Comment by rafiss** [comment]
will be resolved by https://github.com/cockroachdb/cockroach/pull/94797
