### ISSUE TITLE
stability: leader-not-leaseholder spikes after node restart

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#9552]
Now that we're restarting one of `delta`s nodes every 12 minutes, we're seeing some unaligned ranges:

![screen shot 2016-09-26 at 3 23 30 pm](https://cloud.githubusercontent.com/assets/5076964/18848633/49cbdcfe-83fd-11e6-95a4-26f47526cab4.png)

It appears that with each node restart, the new node "robs" some other ranges of their leadership. The current working theory is that this is caused by eager campaigning, which when the node comes online hasn't heard from many of the existing leaders (which makes sense, because many of them are quiesced for almost the whole lease duration).

What's not immediately clear to me is why there is such a long falloff in this phenomenon - since we're actively colocating leaders and leaseholders, I would expect that discrepancy to last for approximately one lease duration (~9s) only. Instead, it seems that leases and Raft leaders only coagulate slowly.

**Comment by bdarnell** [comment]
Eagerly campaigning while there is a non-expired lease is silly - it can only transfer leadership away from the lease holder (even if the old lease holder is down the new one won't be able to do anything until the old lease expires). The PreVote RPC will help here.

We can't tell from this graph whether a bunch of leases change hands at once and then it takes time to make all the leader elections succeed, or if we're continually waking up quiesced ranges (and campaigning them) at a slightly lower rate than we're transferring leadership. If it's the latter then this doesn't seem that surprising.

**Comment by petermattis** [comment]
I was about to ask how we could avoid eagerly campaigning while there is a non-expired lease, but it seems easy enough to load our local lease state. I wonder if it is already loaded at the point we go to eagerly campaign.

**Comment by petermattis** [comment]
Looking at the code, I'm not sure we will eagerly campaign if there is a non-expired lease. When a node starts it will read the replica state (including the lease state) from RocksDB. If an operation arrives at the node we'll call `Replica.redirectOnOrAcquireLease` which will see that the lease is still valid and redirect to the lease holder. Am I missing anything here?

**Comment by bdarnell** [comment]
OK, so maybe we're not campaigning with a non-expired lease. (I was basing that on @tschottdorf's comment that "many of them are quiesced for almost the whole lease duration", suggesting that there is still a lease).

I think this is a natural phenomenon that results when traffic is low relative to range count and lease expiration times. (epoch-based leases will fix it). Delta has ~33k ranges and was doing ~3500 qps at this time, so each range is getting about one query every 10 seconds - not often enough for ranges to renew their own leases, so the leases are mostly being allowed to expire. That's also enough (given our startup delays), that a significant fraction of those ranges were accessed while the restarted node was doing its startup scan. These ranges' leases would have been moved to other nodes, but only 1/10 of the KV client lease holder caches knew about the move. When the lease expires, the lease holder cache of the next client to access the range determines where the lease goes next. Whenever we have this kind of inconsistency in the lease holder caches (and traffic isn't high enough to hold the lease in one place), we can ping-pong the lease back and forth.

**Comment by spencerkimball** [comment]
This has been addressed.
