### ISSUE TITLE
clusterversion: bump binaryMinSupportedVersion to 22.2

### ISSUE THREAD

**Issue by celiala** [cockroachdb/cockroach#95530]
We need to bump binaryMinSupportedVersion to 22.2 before we release the first 23.1 beta (branch cut is currently scheduled for Feb 28).

For previous releases, we removed all older cluster version gates before bumping the binaryMinSupportedVersion. However, this doesn't need to be the case.

For this release -- in order to 1) reduce the scope of _this_ task, and 2) distribute the task of deleting gates across the team -- we plan to instead do the following:

1. PR 1 - bump minBinary, adding skips to all the tests that fail:
	- https://github.com/cockroachdb/cockroach/pull/96656

2. Create tracking issue(s) for tests skipped in (1). Then assign to teams so they delete whenever.
	- https://github.com/cockroachdb/cockroach/issues/95804
	- https://github.com/cockroachdb/cockroach/issues/96751
	- https://github.com/cockroachdb/cockroach/issues/96752

3. Rename / prefix 22.2 gates with a `TODODelete_` prefix or something, so when teams see if in the code they know they can clean up related code:
	- https://github.com/cockroachdb/cockroach/pull/96754

4. Create tracking issue(s) to delete 22.2 gates. Then assign to teams so they delete whenever.
	- https://github.com/cockroachdb/cockroach/issues/96762
	- https://github.com/cockroachdb/cockroach/issues/96761
	- https://github.com/cockroachdb/cockroach/issues/96760
	- https://github.com/cockroachdb/cockroach/issues/96759
	- https://github.com/cockroachdb/cockroach/issues/96758
	- https://github.com/cockroachdb/cockroach/issues/96757
	- https://github.com/cockroachdb/cockroach/issues/96763
	- https://github.com/cockroachdb/cockroach/issues/96764
	- https://github.com/cockroachdb/cockroach/issues/96765

Jira issue: CRDB-23572

**Comment by celiala** [comment]
https://github.com/cockroachdb/cockroach/pull/95630 skips the following tests in order to bumps minBinary:

github.com/cockroachdb/cockroach/pkg/upgrade/upgrades:
- TestAlterSystemSqlInstancesTable
- TestAlterSystemStatementStatisticsTable
- TestIsAtLeastVersionBuiltin
- TestSampledStmtDiagReqsMigration
- TestSchemaTelemetrySchedule
github.com/cockroachdb/cockroach/pkg/sql:
- TestCreateFunctionGating/new_schema_changer_version_enabled
pkg/sql/logicTest/Tests/cockroach-go-Testserver-22.2-master/cockroach-go-Testserver-22_2-master_Test:
- TestLogic_Testserver_upgrade_node
github.com/cockroachdb/cockroach/pkg/storage:
- TestMakeIngestionWriterOptions
Tests / Local roachTest
- acceptance/version-upgrade

**Comment by celiala** [comment]
V22_2 gates to delete:

- V22_2Start
- V22_2LocalTimestamps
- V22_2PebbleFormatSplitUserKeysMarkedCompacted
- V22_2EnsurePebbleFormatVersionRangeKeys
- V22_2EnablePebbleFormatVersionRangeKeys
- V22_2TrigramInvertedIndexes
- V22_2RemoveGrantPrivilege
- V22_2MVCCRangeTombstones
- V22_2UpgradeSequenceToBeReferencedByID
- V22_2SampledStmtDiagReqs
- V22_2AddSSTableTombstones
- V22_2SystemPrivilegesTable
- V22_2EnablePredicateProjectionChangefeed
- V22_2AlterSystemSQLInstancesAddLocality
- V22_2SystemExternalConnectionsTable
- V22_2AlterSystemStatementStatisticsAddIndexRecommendations
- V22_2RoleIDSequence
- V22_2AddSystemUserIDColumn
- V22_2SystemUsersIDColumnIsBackfilled
- V22_2SetSystemUsersUserIDColumnNotNull
- V22_2SQLSchemaTelemetryScheduledJobs
- V22_2SchemaChangeSupportsCreateFunction
- V22_2DeleteRequestReturnKey
- V22_2PebbleFormatPrePebblev1Marked
- V22_2RoleOptionsTableHasIDColumn
- V22_2RoleOptionsIDColumnIsBackfilled
- V22_2SetRoleOptionsUserIDColumnNotNull
- V22_2UseDelRangeInGCJob
- V22_2WaitedForDelRangeInGCJob
- V22_2RangefeedUseOneStreamPerNode
- V22_2NoNonMVCCAddSSTable
- V22_2GCHintInReplicaState
- V22_2UpdateInvalidColumnIDsInSequenceBackReferences
- V22_2TTLDistSQL
- V22_2PrioritizeSnapshots
- V22_2EnableLeaseUpgrade
- V22_2SupportAssumeRoleAuth
- V22_2FixUserfileRelatedDescriptorCorruption
-

**Comment by celiala** [comment]
This can be closed, since the task of bumping `binaryMinSupportedVersion` to 22.2 is complete.

(all tracking issues noted in description don't have an explicit complete by date; can be done whenever/async)

**Comment by rafiss** [comment]
reopening as a skipped test references this

**Comment by celiala** [comment]
x-referencing work to unskip (remove) TestSampledStmtDiagReqsMigration:
- https://github.com/cockroachdb/cockroach/issues/96765
- https://github.com/cockroachdb/cockroach/pull/105477

**Comment by celiala** [comment]
Test removed in:

https://github.com/cockroachdb/cockroach/commit/24d8278a9efa7982fdd9b40efb2873ae28b13c9a#diff-2037b8b5928f901c44b1a53ea73fa9f95aeef06355d36588db4533fc8954a525

**Comment by celiala** [comment]
Closing this parent issue since:

- all skipped tests that referenced this issue have since been cleaned up
- children issues exist to track cleanup work for individual teams
- (actual task of bumping minBinary to 22.2 was completed)
