### ISSUE TITLE
sql: reduce contention between session (de)registration and query cancelation

### ISSUE THREAD

**Issue by ecwall** [cockroachdb/cockroach#95535]
The `SessionRegistry` contains a mutex is used for session registration, de-registration, and query cancelation:
https://github.com/cockroachdb/cockroach/blob/97359549f19a64113965331164e7aff005a766be/pkg/sql/exec_util.go#L2065

Registration and de-registration are fast and should not hold the lock very long, but query cancelation can be long running. 

We should be able to use the mutex to lock looking up the session, but release it after the session has been looked up for the duration of the query cancelations.

Jira issue: CRDB-23574

**Comment by rafiss** [comment]
Where is the session registry lock held? So far I only found one usage: https://github.com/cockroachdb/cockroach/blob/97359549f19a64113965331164e7aff005a766be/pkg/server/status.go#L219

**Comment by ecwall** [comment]
> Where is the session registry lock held? So far I only found one usage:
> 
> https://github.com/cockroachdb/cockroach/blob/97359549f19a64113965331164e7aff005a766be/pkg/server/status.go#L219

There are more usages in the SessionRegistry methods below the struct.
