### ISSUE TITLE
ALTER TENANT SET CLUSTER SETTINGS Does Not Infer Placeholder Type

### ISSUE THREAD

**Issue by JeffSwenson** [cockroachdb/cockroach#95538]
**Describe the problem**

Running the query
```
ALTER TENANT ALL SET CLUSTER SETTING "sql.defaults.distsql" = $1;

# With Paremeter
$1 = 'off'

# Returns the following error
ERROR: could not determine data type of placeholder $1 (SQLSTATE 42P18)
```

Formatting a raw sql string with the same inputs succeeds
```
ALTER TENANT ALL SET CLUSTER SETTING "sql.defaults.distsql" = 'off';
```

**Additional context**
This was discovered while trying to mitigate CC-9095. The placeholder command was used by automation to adjust settings across the Serverless fleet. The automation works for most settings, but fails on the "sql.defaults.distsql" setting.

Jira issue: CRDB-23576

**Comment by rafiss** [comment]
This isn't specific to ALTER TENANT. The same applies for any cluster setting with an enum value. See https://github.com/cockroachdb/cockroach/issues/53925 for a duplicate issue. I wrote https://github.com/cockroachdb/cockroach/pull/53941 to fix it, but that's technically a backwards-incompatible change, so decided not to go through with it.

**Comment by rafiss** [comment]
A workaround is to use a cast: `ALTER TENANT ALL SET CLUSTER SETTING "sql.defaults.distsql" = $1::STRING;`

**Comment by rafiss** [comment]
I believe we landed on a workaround for this, so I'm going to close this with won't fix. Let me know if it should remain open.
