### ISSUE TITLE
release-22.2: tenantcostclient: TestWaitingRU is quite flaky

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#95547]
`TestWaitingRU` seems to be flaky on 22.2 and is showing up when backporting changes - https://teamcity.cockroachdb.com/project.html?projectId=Cockroach_UnitTests&buildTypeId=&tab=testDetails&testNameId=-1339370881944072867&order=TEST_STATUS_DESC&branch_Cockroach_UnitTests=__all_branches__&itemsCount=50

cc: @DrewKimball for triage

Jira issue: CRDB-23583

**Comment by DrewKimball** [comment]
I think you wanted @andy-kimball instead, but the failure looks like a simple precision error based on the failure message, so I'll put up a quick patch.
`condition failed to evaluate within 45s: RUs did not drop below 1K: 0.00`

**Comment by DrewKimball** [comment]
Just saw this again here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/8959286?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

**Comment by ajstorm** [comment]
@DrewKimball do you think that this new flake is the result of your original PR not being backported?

**Comment by DrewKimball** [comment]
The original PR was backported... I think my "fix" might have just not actually fixed the flake.

**Comment by ajstorm** [comment]
Sending to SQL Queries, as the new owners of RU accounting.

**Comment by rharding6373** [comment]
This is currently flaking at [8.4%](https://teamcity.cockroachdb.com/test/-1339370881944072867?currentProjectId=Cockroach_UnitTests&expandTestHistoryChartSection=true). A recent test failure: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_Test/9837369?showRootCauses=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

**Comment by rytaft** [comment]
It seems to me like this test could flake if one of the goroutines in this loop starts executing `OnResponseWait` before any other goroutine starts executing `OnRequestWait`:
https://github.com/cockroachdb/cockroach/blob/8e1c35a0580364b52fc48a0ece72ea8fa6659627/pkg/ccl/multitenantccl/tenantcostclient/tenant_side_test.go#L792-L799

`OnRequestWait` blocks if the rate limiter is in debt, which will happen as soon as one goroutine calls `OnResponseWait`. If a second goroutine hasn't yet completed `OnRequestWait` by that point, I think they will be let through one-at-a-time as RUs are refilled here:
https://github.com/cockroachdb/cockroach/blob/8e1c35a0580364b52fc48a0ece72ea8fa6659627/pkg/ccl/multitenantccl/tenantcostclient/tenant_side_test.go#L801-L811

As a result, the requests won't stack up and `succeeded` will never be true.

It can also flake if the RUs start refilling before multiple goroutines call `OnResponseWait` (even if more than one goroutine gets past the `OnRequestWait` step).

If I comment out the `SucceedsSoon` wrapper, this test fails quite easily. So I think when this test flakes we've just gotten really unlucky and didn't get a single success over 45 seconds. 

I'm going to think more about how to make this test more deterministic, but welcome any suggestions.
