### ISSUE TITLE
backupccl: RESTORE does not properly set the ADD transient state for tenant records

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#95575]
**Describe the problem**

This code:
```go
        for _, tenant := range details.Tenants {
           switch tenant.State {
           case descpb.TenantInfo_ACTIVE:
             // If the tenant was backed up in the `ACTIVE` state then we create
             // the restored record in an `ADD` state and mark it `ACTIVE` at
             // the end of the restore.
             tenant.State = descpb.TenantInfo_ADD
```

Doesn't do what it thinks it does. The `tenant` loop variable is a copy, so the assignment is a no-op.

As a result, the state of the tenant during the RESTORE is not actually ADD.

**Expected behavior**

```go
for i := range .. {
   tenant := &details.Tenant[i]
  ...
```

cc @dt @stevendanna @adityamaru  for triage.

Jira issue: CRDB-23596

**Comment by knz** [comment]
actually I misread the code, this is fine

**Comment by adityamaru** [comment]
fwiw we were missing an explicit test for this - https://github.com/cockroachdb/cockroach/pull/95578
