### ISSUE TITLE
workload/schemachange: error trying to create table with index on `date[]` column

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#95580]
```
 "workerId": 3,
 "clientTimestamp": "23:13:06.679658",
 "ops": [
  "BEGIN",
  {
   "sql": "CREATE TABLE IF NOT EXISTS public.table1 (col1_2 DATE[] NOT NULL, INDEX (col1_2 DESC), UNIQUE (col1_2 DESC), INDEX (col1_2 DESC) NOT VISIBLE, UNIQUE (col1_2 ASC))",
   "potentialExecErr": "42601"
  }
 ],
 "expectedExecErrors": "",
 "expectedCommitErrors": "",
 "message": "***UNEXPECTED ERROR; Received an unexpected execution error.: ERROR: unimplemented: column col1_2 is of type date[] and thus is not indexable (SQLSTATE 0A000)",
```

Workload logs: <https://teamcity.cockroachdb.com/repository/download/Cockroach_Nightlies_RoachtestNightlyGceBazel/8380342:id/schemachange/mixed-versions/run_1/artifacts.zip!/run_231305.049997989_n2_workload-run-schemac.log>

Jira issue: CRDB-23599

**Comment by ajwerner** [comment]
randgen is producing a bad create table def with an index on a date array. I think that shows up somewhere like here:
https://github.com/cockroachdb/cockroach/blob/a227cde88f70433049bb7e3364578e8f8042046e/pkg/sql/randgen/schema.go#L527-L535
