### ISSUE TITLE
cdc: TestChangefeedHandlesDrainingNodes flaked

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#95611]
See CI flake here: [TestChangefeedHandlesDrainingNodes](https://teamcity.cockroachdb.com/viewLog.html?buildId=8390616&buildTypeId=Cockroach_BazelEssentialCi#testNameId8657985868505175386)

Jira issue: CRDB-23616

Epic CRDB-11732

**Comment by jayshrivastava** [comment]
Dupe of https://github.com/cockroachdb/cockroach/issues/97233
