### ISSUE TITLE
storage: Use Raft PreVote RPC and disable CheckQuorum

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#9561]
Raft's CheckQuorum feature has some conflicts with our plans for quiesced ranges (leading to hacky workarounds like #9407). We'd like to turn it off but first we need to make sure we have alternatives to the main benefits it provides, which are snapshot throttling and minimizing disruptive elections. The former is (mostly) covered by streaming snapshots; the latter is provided by a feature discussed in the raft thesis called the PreVote RPC. This is being implemented under coreos/etcd#6522.

**Comment by bdarnell** [comment]
From #315: we should make sure that PreVote rejections include an indication of the current leader, since with coalesced and quiesced heartbeats there may be no other way for a node recovering from a partition to learn of the current state of the range.

**Comment by bdarnell** [comment]
Upstream PR is coreos/etcd#6624

**Comment by bdarnell** [comment]
The comment about PreVote rejections indicating the current leader is unnecessary with the current implementation of coalesced heartbeats, which return per-range information.

**Comment by tschottdorf** [comment]
> The comment about PreVote rejections indicating the current leader is unnecessary with the current implementation of coalesced heartbeats, which return per-range information.

That is a comment about the current coalesced heartbeats, but is that future-proof? I suppose you'll get another upstream change in if you need it, so seems ok.

**Comment by bdarnell** [comment]
In the event that we reintroduce term-less coalesced heartbeats, we'll need to reopen #315 and solve the issues therein (including this one about PreVote returning the leader).
