### ISSUE TITLE
sql,auth: investigate connection latency changes in v22.2

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#95627]
**Describe the problem**

The latency for connecting to a cluster may have regressed in v22.2. This is independent from the SCRAM rollout, as a latency difference can be observed even compared to a v22.1 cluster with SCRAM enabled.

**To Reproduce**

```
roachprod create rafi-test -n 1
roachprod stage rafi-test:1 release v22.1.9
roachprod start --secure rafi-test
roachprod sql rafi-test:1 --secure
```

in SQL:
```
ALTER USER root WITH PASSWORD 'password';
SET CLUSTER SETTING server.user_login.upgrade_bcrypt_stored_passwords_to_scram.enabled = true;
SET CLUSTER SETTING server.user_login.password_encryption = 'scram-sha-256';
```

Copy the `~/certs/ca.crt` file from the roachprod instance to your local computer.

Now you can connect from your local computer with
```
cockroach sql --url 'postgresql://root:password@<roachprod ip>:26257/?sslmode=verify-full&sslrootcert=roachprod-ca.crt'
```

I used this small program to connect repeatedly:
```
package main

import (
    "context"
    "fmt"
    "github.com/jackc/pgx/v4"
)

func main() {

    i := 0
    for {
        if i%100 == 0 {
            fmt.Println(i)
        }
        _, err := pgx.Connect(context.Background(), "postgresql://root:password@35.196.28.100:26257/sslmode=verify-full&sslrootcert=/Users/rafiss/src/cockroach/roachprod-ca.crt")
        if err != nil {
            fmt.Println(err)
        }
        i++
    }
}
```

I ran that against v22.1.9, then I upgraded to v22.2.2:
```
roachprod stop rafi-test
roachprod stage rafi-test:1 release v22.2.2
roachprod start --secure rafi-test
```

Observe the Connection Latency metrics in the DB Console. The results I got were:
```
scram 22.1
p99: 184-218 ms
p90: 184-218 ms

scram 22.2
p99: 517ms
p90: 193-274ms
```

You can also force bcrypt for both versions. Start from the beginning and use these SQL commands instead:
```
ALTER USER root WITH PASSWORD 'password';
SET CLUSTER SETTING server.user_login.upgrade_bcrypt_stored_passwords_to_scram.enabled = false;
SET CLUSTER SETTING server.user_login.password_encryption = 'crdb-bcrypt';
```

My results were:
```
bcrypt 22.1
p99: 190-210 ms
p90: 190-210 ms

bcrypt 22.2
p99: 517ms
p90: 410-450ms
```

**Expected behavior**
As long as the password hashing protocol doesn't change, the latencies shouldn't change that much between versions.

**Additional data / screenshots**
See attached CPU profiles. Nothing stood out to me.

[22.1.9-bcrypt-profile.pb.gz](https://github.com/cockroachdb/cockroach/files/10470530/22.1.9-bcrypt-profile.pb.gz)
[22.1.9-scram-profile.pb.gz](https://github.com/cockroachdb/cockroach/files/10470531/22.1.9-scram-profile.pb.gz)
[22.2.2-bcrypt-profile.pb.gz](https://github.com/cockroachdb/cockroach/files/10470532/22.2.2-bcrypt-profile.pb.gz)
[22.2.2-scram-profile.pb.gz](https://github.com/cockroachdb/cockroach/files/10470533/22.2.2-scram-profile.pb.gz)

Jira issue: CRDB-23628

**Comment by rafiss** [comment]
There does seem to be a difference in the performance of `math/big.addMulVVW` .

```
❯ go tool pprof 22.1.9-scram-profile.pb.gz
File: cockroach
Type: cpu
Time: Jan 20, 2023 at 4:01pm (EST)
Duration: 5s, Total samples = 210ms ( 4.20%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) web
(pprof) top
Showing nodes accounting for 140ms, 66.67% of 210ms total
Showing top 10 nodes out of 184
      flat  flat%   sum%        cum   cum%
      30ms 14.29% 14.29%       30ms 14.29%  math/big.addMulVVW
      30ms 14.29% 28.57%       30ms 14.29%  runtime.futex
      10ms  4.76% 33.33%       10ms  4.76%  github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnPipeliner).chainToInFlightWrites
      10ms  4.76% 38.10%       10ms  4.76%  github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor
      10ms  4.76% 42.86%       40ms 19.05%  math/big.nat.montgomery
      10ms  4.76% 47.62%       10ms  4.76%  runtime.epollwait
      10ms  4.76% 52.38%       10ms  4.76%  runtime.findObject
      10ms  4.76% 57.14%       10ms  4.76%  runtime.findfunc
      10ms  4.76% 61.90%       10ms  4.76%  runtime.mapassign_fast32
      10ms  4.76% 66.67%       10ms  4.76%  runtime.markBits.isMarked
```

Compare to:
```
❯ go tool pprof 22.2.2-scram-profile.pb.gz
File: cockroach
Type: cpu
Time: Jan 20, 2023 at 3:51pm (EST)
Duration: 5.08s, Total samples = 200ms ( 3.94%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 190ms, 95.00% of 200ms total
Showing top 10 nodes out of 143
      flat  flat%   sum%        cum   cum%
     100ms 50.00% 50.00%      100ms 50.00%  math/big.addMulVVW
      10ms  5.00% 55.00%       10ms  5.00%  compress/flate.(*compressor).findMatch
      10ms  5.00% 60.00%       10ms  5.00%  github.com/cockroachdb/cockroach/pkg/kv/kvserver/closedts/sidetransport.(*Sender).publish
      10ms  5.00% 65.00%      100ms 50.00%  math/big.nat.montgomery
      10ms  5.00% 70.00%       10ms  5.00%  regexp.(*Regexp).tryBacktrack
      10ms  5.00% 75.00%       10ms  5.00%  runtime.duffcopy
      10ms  5.00% 80.00%       10ms  5.00%  runtime.gogo
      10ms  5.00% 85.00%       10ms  5.00%  runtime.mapclear
      10ms  5.00% 90.00%       10ms  5.00%  runtime.usleep
      10ms  5.00% 95.00%       10ms  5.00%  runtime/internal/syscall.Syscall6
```

**Comment by jordanlewis** [comment]
Poking around, I have a hunch - perhaps in 22.2 there is extra roundtrip to get auth info? Perhaps a cache is not working properly? I'm thinking about the code under `retrieveSessionInfoWithCache` which shows up a little bit in the 22.2 profile, but not at all in the 22.1 profile.

**Comment by jordanlewis** [comment]
Also I think it's a bad idea to test this with root, since root has special fastpaths to avoid lookups in the system tables IIRC.

**Comment by dikshant** [comment]
> Also I think it's a bad idea to test this with root, since root has special fastpaths to avoid lookups in the system tables IIRC.

I did my testing using a sql user created from the cloud console and a user I manually created from the sql shell.

**Comment by rafiss** [comment]
> perhaps in 22.2 there is extra roundtrip to get auth info? Perhaps a cache is not working properly? I'm thinking about the code under retrieveSessionInitInfoWithCache which shows up a little bit in the 22.2 profile, but not at all in the 22.1 profile.

Yeah good hunch. I ran ` git diff release-22.2..release-22.1 -- pkg/sql/user.go` and then tracked down this change https://github.com/cockroachdb/cockroach/pull/85769. I wasn't aware of this PR and it does seem like this could be a hit on performance due to the `CheckPrivilegeForUser` call added for `NOSQLLOGIN` in `pkg/sql/users.go`. 

Though also from an initial read, there should be caching in place inside of the `CheckPrivilegeForUser` that should prevent many roundtrips. I also hadn't thought the round trips increased, since I used the DB console in my experiment to look at the SQL Activity of internal executor queries (with `sql.stats.response.show_internal.enabled = true`), and nothing stood out. 

One possibility could be because there also is a call to [fetch the `system.privileges` descriptor](https://github.com/cockroachdb/cockroach/blob/2861a4ee05fac1cc13f87bf00f368a65ea8700dc/pkg/sql/syntheticprivilegecache/cache.go#L74). That maybe wouldn't show up in the SQL Activity dashboard, or it may not be obvious if it is. Definitely something to look into, and if it is causing more roundtrips, there should be a way to improve it.

**Comment by JeffSwenson** [comment]
This may be related. Running `DISCARD ALL` to reset a session is also more expensive on v22.2. https://github.com/cockroachdb/cockroach/issues/95864

**Comment by rafiss** [comment]
We'll run this analysis again after https://github.com/cockroachdb/cockroach/issues/95833 is resolved to make sure that explains the latency differences.

**Comment by rafiss** [comment]
https://github.com/cockroachdb/cockroach/pull/96029#issuecomment-1413986373 shows that this should be good now
