### ISSUE TITLE
sql: EXPLAIN({DEBUG/TRACE}) is broken for INSERT/UPDATE/DELETE

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#9563]
This line puts the node under EXPLAIN in "debug mode".
https://github.com/cockroachdb/cockroach/blob/9163be0/sql/trace.go#L102
It does this because the ExplainTrace/ExplainDebug nodes use the "debug values" of the sub-node.

These nodes don't run properly in "debug node". For example, INSERT has this that short-circuits it:
https://github.com/cockroachdb/cockroach/blob/9163be0/sql/insert.go#L270

We should have these nodes run their side-effects even when they're in debug node (but not for `explain(plan/types)`. 

cc @knz

**Comment by spencerkimball** [comment]
ping @andreimatei. Is this 1.0?

**Comment by andreimatei** [comment]
I have a WIP to fix this stuff, but it's not immediate.
