### ISSUE TITLE
stability: unexpected node crash on chaos test

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#9567]
chaos monkey on delta is killing (`-9`) a node every 12 minutes.

One specific node: `104.196.173.128` crashed unexpectedly and was unreachable (at least by prometheus) for a while.

Specific timeline:

```
2016-09-27 06:48:02,400 INFO exited: cockroach (terminated by SIGKILL; not expected)
2016-09-27 07:37:19,669 INFO exited: cockroach (exit status 2; not expected)
2016-09-27 08:48:02,864 INFO exited: cockroach (terminated by SIGKILL; not expected)
```

The first and third are intentional chaos monkey deaths. The middle one is not and died with:

```
panic: IO error: /mnt/data1/1488342.log: Too many open files [recovered]
        panic: IO error: /mnt/data1/1488342.log: Too many open files
```

Prometheus was unable to reach the node for a majority of the time during the `06:68 - 07:37` run, and for some of the time during the `07:37 - 08:48` run.
Following graphs show:
- top graph: "node down" events
- bottom graph: uptime for the node.

The combination shows the three crashes, but unresponsiveness for a while.
<img width="949" alt="screen shot 2016-09-27 at 2 20 04 pm" src="https://cloud.githubusercontent.com/assets/5901480/18873081/01a42140-84be-11e6-8c38-a2e0d7887d8c.png">

Logs:
`06:68 - 07:37`:
[cockroach.stderr.run1.txt.gz](https://github.com/cockroachdb/cockroach/files/495463/cockroach.stderr.run1.txt.gz)

`07:37 - 08:48`:
[cockroach.stderr.run2.txt.gz](https://github.com/cockroachdb/cockroach/files/495464/cockroach.stderr.run2.txt.gz)

`07:37 - 08:48` without the following (spammy) lines: `storage/store.go:2629 replica ... too old, added to replica GC queue` and `storage/store.go:2635 got error from range ..., replica ...: raft group deleted`:
[cockroach.stderr.run2.minus-gc-and-deleted-groups.txt](https://github.com/cockroachdb/cockroach/files/495462/cockroach.stderr.run2.minus-gc-and-deleted-groups.txt)

**Comment by petermattis** [comment]
I wonder how many file descriptors that node had open. We should probably have a gauage for that metric.

**Comment by mberhault** [comment]
Good question, I'll add that.

**Comment by bdarnell** [comment]
As a reminder, we recommend running with a file descriptor limit of at least 15k, but we don't follow that ourselves (the test clusters are running with a limit of 4096). 

```
W160927 06:48:03.715070 1 server/context.go:309  soft open file descriptor limit 4096 is under the recommended limit 15000; this may decrease performance
please see https://www.cockroachlabs.com/docs/recommended-production-settings.html for more details
```

Right now one random delta node is using 3968 fds, of which 3847 are in rocksdb (files in `/mnt/data*`). This is more or less as expected: we allocate 256 file descriptors to network/misc and give the rest to rocksdb. It's exceeded its limit by a few fds. We expect to see ~20 GRPC connections (1 inbound and 1 outbound to each peer); there are ~30 and I'm not sure why. Maybe there's a race in the rpc connection caching code (ours or GRPC's) that allows multiple connections to be created after a failure. Then there are 65 connections from localhost: `block_writer` with `--concurrency 64` and one `cockroach sql` session.  

Let's get some monitoring in place so we can see whether fd usage grows over time or if it's stable and we're just close to the edge.

**Comment by mberhault** [comment]
yeah, I've been looking into that. rocksdb has a count of file opens, but
not a current count.
there's a count of file closes, but that's not actually used :(

**Comment by bdarnell** [comment]
RocksDB seems to be fine; the question is how all the untracked file descriptors outside of rocksdb are behaving. Getting that number is surprisingly difficult; the most common (linux-only) strategy I've seen is to count the number of files in `/proc/self/fds` (we can get this from `gosigar`, which we're already using).

**Comment by petermattis** [comment]
We should export a count of the number of sstables. See `Store.ComputeMetrics` where we compute the read amplification from the sstables. Very easy to add a gauge there for the number of sstables. @mberhault can you add this?

**Comment by mberhault** [comment]
yup, easy enough. Ben is still right though, I think we want the total process usage as well.
A random peek at a delta node shows ~1800 open FDs per store, and 121 others.

**Comment by mberhault** [comment]
Added sstable count per store to #9582

**Comment by petermattis** [comment]
@mberhault Anything else to do here?

**Comment by mberhault** [comment]
nope. closing.
