### ISSUE TITLE
pass filter/limit/order to virtual tables

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#95766]
Currently values for order/filter/limit are not passed on virtual tables, making the queries on them to be inefficient.
We use virtual tables on the console on several locations (e.g. `crdb_internal.statement_statistics`, `crdb_internal.transaction_statistics`), but selects on them can take a long time to be executed since filters and limit are not being passed on. 
This change would allow all of sql observability queries to be more efficient and consequently the tables would take less time to load (it can take minutes when users have a lot of data). 

Jira issue: CRDB-23723

**Comment by mgartner** [comment]
@michae2 can you add a link in the JIRA ticket to the post-mortem document related to this issue? Can you also assign a priority and due date based on how important you think this is? If there is a status update, please leave a comment in the JIRA ticket, too.

**Comment by rytaft** [comment]
@maryliag my impression from recent discussions with you was that these virtual tables are not dependent on a system table, as there is a view that combines the virtual table and system table for use by other queries. Is this correct? If so, I'm not sure what SQL Queries can do to optimize purely in-memory virtual tables (i.e., we can't push filters down to an index, etc).

**Comment by maryliag** [comment]
We have a view that combines [in-memory view] + [system table] 
We would like to pass limits/order to that combined view.

For example
```
SELECT
 fingerprint_id,
 transaction_fingerprint_id,
 app_name,
 max(aggregated_ts) as aggregated_ts,
 metadata,
 crdb_internal.merge_statement_stats(array_agg(statistics)) AS statistics,
 max(sampled_plan) AS sampled_plan,
 aggregation_interval
FROM crdb_internal.statement_statistics   <--- this is the combined view with in-memory and system
WHERE app_name NOT LIKE '$ internal%' AND app_name NOT LIKE '$$ %' 
AND aggregated_ts >= $1     <--- I believe the filter is already getting passed on, so we don't do a full scan because of this
AND aggregated_ts <= $2"
GROUP BY
 fingerprint_id,
 transaction_fingerprint_id,
 app_name,
 metadata,
 aggregation_interval
ORDER BY aggregated_ts DESC LIMIT $3   <----- this here is what I'm referring to
```

**Comment by michae2** [comment]
@maryliag is this related to #95770?

**Comment by maryliag** [comment]
> is this related to https://github.com/cockroachdb/cockroach/issues/95770?

different problems, that one is for the query `SELECT * FROM crdb_internal.statement_statistics WHERE "1@1"::jsonb <@ indexes_usage`, which is currently not possible

**Comment by maryliag** [comment]
Thank you for the explanation Becca. We will look into other improvements we can make on the query

**Comment by rytaft** [comment]
Great, thanks. In that case I'm going to close this issue, but please let us know if we can help brainstorm how to rewrite the query so it's possible to optimize (or feel free to open another issue).
