### ISSUE TITLE
sql/catalog/lease: Avoid cross descriptor validation when acquiring leases

### ISSUE THREAD

**Issue by fqazi** [cockroachdb/cockroach#95764]
As part of the lease acquisition process, we utilize high-priority transactions, which can cause cross-descriptor validation to potentially push out other work such as schema changes. In a schema where a single table has tons of foreign key references, this validation on a sizeable multi-region cluster could lead to a fairly high frequency of such events. Cross-descriptor validation is only strictly needed at modification time, and our approach of aggressively doing it for even reads can have a determinantal impact in certain cases by blocking schema changes (on lease renewals).

Jira issue: CRDB-23721

**Comment by ajwerner** [comment]
I think for the code we have today, this is reasonable.

Cross-reference validation doesn't buy us much other than awareness of existing corruption at a time you don't really want to know about it. 

However, there might be value in cross-reference validation if we used it to determine minimum versions of referenced descriptors and used that to bootstrap cross-descriptor coherence in our caching. That's a bigger topic for a document I have brewing.

**Comment by ajwerner** [comment]
@fqazi if you haven't actively done anything here, I think we ought to deprioritize this. There's questions about the mechanism. In light of recent discoveries that this was not the root cause of the motivating customer issue, I'm not sure how much this matters.

**Comment by fqazi** [comment]
Nothing has been actively done on this issue, we can deprioritize this one. The other thing is if cross-descriptor validation is important during leasing we could also move to a sampled model, we don't have to do this stuff on every renewal.

**Comment by fqazi** [comment]
Will close this once the backports are merged.

**Comment by fqazi** [comment]
All backports are merged
