### ISSUE TITLE
sql/catalog/lease: Move away from lease renewal model to a heart beat based one

### ISSUE THREAD

**Issue by fqazi** [cockroachdb/cockroach#95765]
Currently, descriptor leasing inside cockroach DB is fixed length and leases are renewed even if a descriptor doesn't have any modification on it. Medium-term it may make sense to move to a heartbeat-based model instead where the duration is completely tied to the liveness of any dependent sessions. This would eliminate repeated renewals and the overhead involved

Jira issue: CRDB-23722

Epic CRDB-35665

**Comment by rafiss** [comment]
This replaces https://github.com/cockroachdb/cockroach/issues/61419. Copying the comment from there.

> We frequently see deployments of applications with schemas involving more than 50 descriptors. This was, until https://github.com/cockroachdb/cockroach/pull/59319 when we increased the default limit to 500 descriptors. This limit exists because for each leased descriptor, we end up running a heartbeat loop. One motivation for the [sqlliveness layer](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20200615_sql_liveness.md) was to provide a centralized heartbeating service which can be leveraged for all manner of leased resources. Descriptor leases are the perfect use case. 
> 
> However, one issue with the sqlliveness leases is that they carry shorter refresh rates than the existing schema leases (1m default vs 5m hard-coded). That makes them even more susceptible to https://github.com/cockroachdb/cockroach/issues/51042 / https://github.com/cockroachdb/cockroach/issues/36871. Thus we should first fix the way transaction deadline tracking gets hooked up and then we should adopt the sqlliveness layer to track schema leases.
> 
> This will allow us to support larger schemas with less overhead and fewer knobs.

**Comment by fqazi** [comment]
WIP PR that should be revived: https://github.com/cockroachdb/cockroach/pull/85837
