### ISSUE TITLE
sql-queries: TestLogic_lookup_join_local flaked on master

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#95799]
See CI failure [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=8438002&buildTypeId=Cockroach_BazelEssentialCi)

Jira issue: CRDB-23746

**Comment by yuzefovich** [comment]
Seems like `lookup_join_local` gets extremely slow, reproducible with `./dev testlogic base -v --stream-output --files=lookup_join_local --config=local -- --test_env=COCKROACH_RANDOM_SEED=-1150544666816831660`. The stack trace shows the usage of the streamer, but even if I disable it, then the query is still slow. Probably it's one of the metamorphic variables that is slowing everything down significantly.

**Comment by yuzefovich** [comment]
Indeed, disabling the randomization on `logictest-small-engine-blocks` makes this test go fast.

@erikgrinaker how would you feel about this diff:
```
diff --git a/pkg/sql/logictest/logic.go b/pkg/sql/logictest/logic.go
index bdfcad17591..df7bc3b8ef6 100644
--- a/pkg/sql/logictest/logic.go
+++ b/pkg/sql/logictest/logic.go
@@ -1328,7 +1328,7 @@ func (t *logicTest) newCluster(
        shouldUseMVCCRangeTombstonesForPointDeletes := useMVCCRangeTombstonesForPointDeletes && !serverArgs.DisableUseMVCCRangeTombstonesForPointDeletes
        ignoreMVCCRangeTombstoneErrors := supportsMVCCRangeTombstones &&
                (globalMVCCRangeTombstone || shouldUseMVCCRangeTombstonesForPointDeletes)
-       useSmallEngineBlocks := smallEngineBlocks && !serverArgs.DisableSmallEngineBlocks
+       useSmallEngineBlocks := smallEngineBlocks && !serverArgs.DisableSmallEngineBlocks && !serverArgs.ForceProductionValues
 
        params := base.TestClusterArgs{
                ServerArgs: base.TestServerArgs{
```
Not sure if it's worth digging into this slowness in general, but this diff at least makes the slowness in this particular case go away.

**Comment by erikgrinaker** [comment]
Honestly, I'd be fine with just removing the `smallEngineBlocks` stuff entirely, given the amount of issues it's causing. It's useful to make sure time-bound iterators work properly, but we can probably have more targeted tests for it.
