### ISSUE TITLE
sql: current_date incorrectly ignores the session TZ

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#9580]
See https://github.com/cockroachdb/cockroach/pull/9579#issuecomment-250061020.

If it's 10pm in the evening of september 27th and you set a TZ to -5, `now()` will say "september 28th, 3am" but `current_date()` is stuck on september 27th. This is incorrect, `current_date()` should say "sept 28th" too.

In other words apply the session TZ shift to the current timestamp before deriving the date value.

cc @vivekmenezes

**Comment by knz** [comment]
Once this is fixed please revert #9579 and add a test to specifically check day boundaries.

**Comment by dt** [comment]
Hmm, isn't it the opposite issue? If it's 10pm _in UTC-5_, then isn't the issue that `now` isn't offset but that `current_date` is?

**Comment by dt** [comment]
hmm, I think the real issue here might be that `now` is returning a `timestamp` (which knows nothing about zones, including the session zone) and not a `timestamptz`

**Comment by knz** [comment]
@dt doesn't it work both ways?

**Comment by vivekmenezes** [comment]
I think @dt is right now(), current-timestamp aught to return s timestamptz. But then we have to worry about them being compatible with transaction_timestamp(), statement_timestamp(), clock_timestamp()

**Comment by vivekmenezes** [comment]
I see those also return a timestamptz. So I think we need to fix them all. Will make that change.

**Comment by vivekmenezes** [comment]
fixed by #9618
