### ISSUE TITLE
rules/release_22_2: fix incorrect expected test output

### ISSUE THREAD

**Issue by postamar** [cockroachdb/cockroach#95849]
I just noticed while reviewing a recent PR that the contents of the files in `testdata` included rules about 2-version invariants for ForeignKeyConstraints and other stuff that just isn't in 22.2. This issue tracks copying the contents of https://github.com/cockroachdb/cockroach/tree/release-22.2/pkg/sql/schemachanger/scplan/internal/rules/testdata into https://github.com/cockroachdb/cockroach/tree/master/pkg/sql/schemachanger/scplan/internal/rules/release_22_2/testdata and amending the rule definitions until the test passes.

Jira issue: CRDB-23775

**Comment by fqazi** [comment]
Yes, let me pick this one up. This was on my radar, along with a backport

**Comment by postamar** [comment]
Cross-referencing https://github.com/cockroachdb/cockroach/pull/96255 and possibly https://github.com/cockroachdb/cockroach/pull/96004.

**Comment by fqazi** [comment]
Fixed via: https://github.com/cockroachdb/cockroach/pull/96255
