### ISSUE TITLE
storage: cgroups based disk stall roachtest

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#95873]
To provide additional test coverage around disk stalls, we should consider using Linux cgroups to limit the IO that can happen on one or more nodes, ideally in a multi-region setup (multiple regions, multiple AZs in each region).

Adapt the test harness outlined in [this comment](https://github.com/cockroachdb/cockroach/issues/94373#issuecomment-1402568360) into a roachtest.

Related to #94373.

Jira issue: CRDB-23786

**Comment by jbowens** [comment]
The new roachtest is merged. Closing this out.
