### ISSUE TITLE
sql/backfill: use lower QoS for constraint validation queries 

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#95879]
**Is your feature request related to a problem? Please describe.**
Generally folks don't want background work to affect foreground performance. We should either always run constraint validation with a background QoS or we should find a way to have the user tell us which QoS level to use. 

**Describe the solution you'd like**

Set a lower QoS level on queries we run for constraint validation.

**Describe alternatives you've considered**

Store on the job the QoS level of the transaction the user ran and plumb that through to the validation queries.

**Additional context**
There is no way to checkpoint constraint validation currently. This might starve constraint validation from succeeding.

Jira issue: CRDB-23791

**Comment by rafiss** [comment]
Picking this back up sounds like a good idea! Let's reassign you.
