### ISSUE TITLE
multitenant: tenant creation can unintentionally overwrite another tenant's span configs

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#95882]
**Describe the problem**

[#95100](https://github.com/cockroachdb/cockroach/pull/95100) introduced a bug in our handling of tenant span configs. It's possible now that the creation of a tenant ends up overwriting another tenant's span config records, and thus affecting zone configs that the original tenant had applied. #95881 is a branch that contains the reproduction through an annotated test case. Specifically:

```
# Peek near the start of the span_configurations table where tenant=11's records
# are stored. The first one is from the start of its keyspace to start of
# table with ID=4: /Tenant/11{-/Table/4}.
state offset=56 limit=5
----
...
/Table/5{7-8}                              ttl_seconds=3600 ignore_strict_gc=true num_replicas=5 rangefeed_enabled=true
/Tenant/11{-/Table/4}                      database system (tenant)
/Tenant/11/Table/{4-5}                     database system (tenant)
/Tenant/11/Table/{5-6}                     database system (tenant)
/Tenant/11/Table/{6-7}                     database system (tenant)
...

# Now for the bug. We'll create tenant=10, but see that it actually ends up
# overwriting span config state for the already-reconciling tenant=11. That
# tenant's reconciler is not expecting this! It operates with the invariant that
# it's the only writer of span configs for its keyspan, which we're simply
# breaking.
initialize tenant=10
----

# We re-inserted a record at /Tenant/11{-\x00}, and split up tenant=11's own
# span config records in the process. Previously tenant=11's first record was
/Tenant/11{-/Table/4}. Now it's /Tenant/11{-\x00}. If tenant=11 had set some
span config for that keyspan, tenant=10's creation just nuked it.
----
...
/Tenant/10{-\x00}                          database system (tenant)
/Tenant/11{-\x00}                          database system (tenant)
/Tenant/11/Table/{4-5}                     database system (tenant)
/Tenant/11/Table/{5-6}                     database system (tenant)
/Tenant/11/Table/{6-7}                     database system (tenant)
...
```

**To Reproduce**

Using #95881:
```
$ dev test pkg/ccl/spanconfigccl/spanconfigreconcilerccl -f=TestDataDriven/multitenant/bug -v --timeout=10s --rewrite
```

**Expected behavior**

Tenant creation should not overwrite another tenant's span configs.

Jira issue: CRDB-23792
Epic: [CRDB-23344](https://cockroachlabs.atlassian.net/browse/CRDB-23344)

Epic CRDB-23344

**Comment by arulajmani** [comment]
Good catch! @irfansharif and I spoke about this a bit, and I think what we want when creating a tenant is to check if any span configs exist for the next tenant already. We should only create a span config entry at the start of the next tenant's key space if no span config entries exist for it (the patch linked above creates these blindly). This should work, and give us what we want, considering we're using a transactional KVAccessor in the tenant creation path.
