### ISSUE TITLE
CRDB connection timeout issues

### ISSUE THREAD

**Issue by room355** [cockroachdb/cockroach#95902]
We noticed connection timeout happens from time to time, and also notice flushMemtable job is being ran at around that time.

We are not sure about what is the root cause and we can't find any meaningful log.
The CPU usage and memory usage looks normal to me. 

One thing we also notice is some of the old db session isn't closed as well. I suspect this causing our memory being eaten and caused the issue we encounter.

So it would be great if we can have some debug instruction and we will move this to the production environment.

Thanks!

Jira issue: CRDB-23801

**Comment by chengxiong-ruan** [comment]
Hi, @room355 Thanks for filing the issue. But without much data or repro observations, it's hard for us to help here.
I'm adding @cockroachdb/sql-sessions team here and hope folks will ask for more clarification on the problem you are seeing.

**Comment by jordanlewis** [comment]
These logs are unrelated. We cannot support such an old version any longer, please upgrade to a newer version. I'll close this issue. You can join our community slack or forum, someone might be able to help you there, GitHub isn't an appropriate place for this kind of thing though.

https://www.cockroachlabs.com/join-community/
