### ISSUE TITLE
storage: Replica.reportSnapshotStatus not called for streaming snapshots?

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#9592]
We don't seem to be calling `Replica.reportSnapshotStatus` for Raft generated streaming snapshots. See `Replica.sendRaftMessage`.

Cc @cockroachdb/stability

**Comment by tamird** [comment]
Note that this is basically the inverse of #9589, so it'd be nice to use the same mechanism for both.

**Comment by jordanlewis** [comment]
I don't think it's quite the inverse - I believe any kind of snapshot send failure (whether application or connection related) should result in a call to `reportSnapshotStatus` with an non-nil error, right?

**Comment by petermattis** [comment]
Yes, I think we should call `reportSnapshotStatus` with whatever result `SendSnapshot` returns.

**Comment by tamird** [comment]
No, I don't think that's right. connection errors should result in `ReportUnreachable`; only application errors should result in a non-nil error passed to `reportSnapshotStatus`.

**Comment by petermattis** [comment]
`ReportUnreachable` is a no-op if the node is in state `ProgressStateSnapshot`. Pretty sure `ReportSnapshot` is what we should be calling regardless of whether it is an RPC error or an application error.

**Comment by tamird** [comment]
Citation?

**Comment by petermattis** [comment]
[github.com/coreos/etcd/raft/raft.go:L850-L856](https://github.com/coreos/etcd/blob/master/raft/raft.go#L850-L856)

```
	case pb.MsgUnreachable:
		// During optimistic replication, if the remote becomes unreachable,
		// there is huge probability that a MsgApp is lost.
		if pr.State == ProgressStateReplicate {
			pr.becomeProbe()
		}
		r.logger.Debugf("%x failed to send message to %x because it is unreachable [%s]", r.id, m.From, pr)
```

And:

```
	case pb.MsgSnapStatus:
		if pr.State != ProgressStateSnapshot {
			return
		}
		if !m.Reject {
			pr.becomeProbe()
			r.logger.Debugf("%x snapshot succeeded, resumed sending replication messages to %x [%s]", r.id, m.From, pr)
		} else {
			pr.snapshotFailure()
			pr.becomeProbe()
			r.logger.Debugf("%x snapshot failed, resumed sending replication messages to %x [%s]", r.id, m.From, pr)
		}
		// If snapshot finish, wait for the msgAppResp from the remote node before sending
		// out the next msgApp.
		// If snapshot failure, wait for a heartbeat interval before next try
		pr.pause()
```

**Comment by tamird** [comment]
ISTM that only the top code block is relevant, and I don't see how that's a no-op. What'd I miss?

**Comment by tamird** [comment]
Oh, I misread `ProgressStateReplicate ` as `ProgressStateSnapshot`. Hm, still seems like sending connection-level errors to `reportSnapshotStatus` is wrong considering the log message it emits: `r.logger.Debugf("%x snapshot failed, resumed sending replication messages to %x [%s]", r.id, m.From, pr)`

**Comment by petermattis** [comment]
We need to call `ReportSnapshot` in order to kick the follower out of `ProgressStateSnapshot`. If we don't do that we won't generate any more messages to the follower.

**Comment by tamird** [comment]
Ah, OK.

**Comment by petermattis** [comment]
Welcome to the raft code.
