### ISSUE TITLE
c2c: add a roachtest for cross-cluster replication to stress resilience

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#95996]
As part of our resilience testing of C2C replication, we would like to have a roachtest that tests how replication reacts to nodes going offline in the source and destination cluster.

Epic: CRDB-21957

Jira issue: CRDB-23889

**Comment by msbutler** [comment]
we now test src/dst node shutdown on coordinator/worker, and at random phases (initial scan, steady state, cutover) of the job.
