### ISSUE TITLE
Moar linters

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#961]
https://github.com/alecthomas/gometalinter/blob/master/main.go#L123:L132 is a nice listing of various lint tools in the go ecosystem. We should investigate them and decide which ones we'd like to use.

At the time of this writing, items on the list we are not using are:
- [ ] structcheck [doesn't handle embedded structs](https://github.com/opennota/check#known-limitations)
- [x] deadcode (defunct)
- [x] gotype (part of the compiler)
- [ ] defercheck (doesn't yield anything)
- [ ] varcheck (buggy)
- [ ] gocyclo (a lot of work, we have some complex code)
- [x] go-nyet (WIP)

**Comment by bdarnell** [comment]
FWIW the only one of these I've heard of is go-nyet, which was written by Barak from CoreOS. It detects local variable shadowing. It reports a few issues in our code; none of them are actual bugs but would be nice to clean up. CoreOS has apparently had a history of bugs that this could catch; they require its use in etcd.

**Comment by tamird** [comment]
I think this is as complete as we're gonna get it.
