### ISSUE TITLE
[ui] Improve Network Latency page to display consistent data during network partition

### ISSUE THREAD

**Issue by koorosh** [cockroachdb/cockroach#96101]
**Is your feature request related to a problem? Please describe.**
Currently, Network latency page relies on existing data to build latencies matrix and
does lots of filtering/aggregations that is not clear and introduces incorrect 
behavior in cases like network partition.

**Describe the solution you'd like**
To make this page more informative even during network partition, it might require following:
- establish new endpoint that will provide all necessary information regarding network latencies (should allow to reduce calculations on front-end)
- Network Latency page should display information about all known nodes in a cluster, so even for unhealthy nodes;

Jira issue: CRDB-23948

**Comment by Santamaura** [comment]
@koorosh we are punting the endpoint work in favor of more important network observability work right?

**Comment by koorosh** [comment]
Right, currently our goal is provide metrics that allow detect network partitioning and export them to Prometheus
