### ISSUE TITLE
backupccl: scheduled backups should stop adding to an incremental chain after a certain number of running jobs

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#96110]
In https://github.com/cockroachlabs/support/issues/2030 we saw an instance of a schedule running incremental backups every hour with `on_previous_running` set to `start`. For *reasons* the hourly incrementals were not completing which resulted in a buildup of 30+ running, incremental jobs. This resulted in nodes OOMing, and general cluster instability. As such, this is working as expected, but it is an easy footgun and one we should safeguard against. If a backup schedule observes > x incremental backup jobs running on its behalf we should do _something_.  This could include skipping scheduling an incremental until the running jobs count falls below x with adequate logs/warnings.

Jira issue: CRDB-23951

Epic CRDB-21944

**Comment by benbardin** [comment]
I disagree! The documentation on `no_wait` is really clear. Nobody should want this feature. But if for some reason I can't think of they do, I doubt they want it to mean "don't wait unless you have an arbitrary number of backups going already, in which case, wait, even though the option is called no_wait".

**Comment by adityamaru** [comment]
After a discussion with the rest of the team we have agreed on the following:

It **always** makes sense for an incremental backup to wait for the previous incremental to complete, regardless of what the user has specified in `on_previous_running`. This is because, triggering a new incremental while a previous incremental is running does not add to the chain of backups, but instead creates a parallel backup with the same `StartTime` but a different `EndTime`. It is still to be confirmed if this renders the backup unrestorable and if it breaks `SHOW BACKUP`, but there is consensus that this is not ideal. Once we run a few tests, we will change the logic such that the user-specified `on_previous_running` will only apply to the full backup schedule. Incremental backups will always wait for the previous incremental in the chain to complete.

**Comment by adityamaru** [comment]
I tried a simple test where two incremental backups write at the same `StartTime` mimicking what would happen if incrementals would not wait for each other during a scheduled backup. The first incremental to complete would succeed, but all subsequent incremental backups would fail because we verify that their `StartTime` is greater than the latest `EndTime` in the backup chain - https://github.com/cockroachdb/cockroach/blob/736a67e0d36cc545bf74d65db069ee895ff9bea0/pkg/ccl/backupccl/backup_job.go#L948

This is further proof that it does not make sense for incremental schedules to support `on_previous_running = start` only `skip` or `wait` will result in a successful incremental chain.
