### ISSUE TITLE
ui: api calls return `max result size exceeded` error

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/cockroach#96184]
Pages using the sql-over-http api can easily return error for `Error while retrieving insights information: max result size exceeded`.

We should make sure these queries return fewer results, or we need to increase the result size in the request.

Jira issue: CRDB-23990

gz#15832

**Comment by xinhaoz** [comment]
Another approach could be still showing the partial results when the max result size is exceeded. If I remember, when we get this error we still get results as part of the payload.

**Comment by maryliag** [comment]
All places using the sql-api was updated on the above PRs to still show data when there is the error message.
Pagination improvement is being tracked on https://github.com/cockroachdb/cockroach/issues/97731
