### ISSUE TITLE
ui: transaction fingerprints page updates data sporadically, ignores custom time interval

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/cockroach#96186]
The Transaction Fingerprints overview page updates data sporadically, with no regard for the time interval. Something is broken in the table row population.

For example, the Execution Count increments at an impossible rate, while the same stat on the Statements Page remains the same:

https://www.loom.com/share/b331d10e58364848b2908c1dd49d8a6f

This behavior is the same, even when the time interval is fixed (i.e., there should be no change in data with a fixed start and end time).

This issue is present in both CC console and DB console.

Jira issue: CRDB-23991

**Comment by ericharmeling** [comment]
This issue encompasses https://github.com/cockroachdb/cockroach/issues/68375.

In addition to execution count, the following column values are affected:

- Transaction Time
- Contention Time
- CPU Time
- Max Memory

**Comment by xinhaoz** [comment]
As an aside, the txns page needs some serious cleanup. It's gotten so messy to the point we can't even catch when we're mutating props we shouldn't be 😬

**Comment by xinhaoz** [comment]
I spoke to Eric and since I had a fix on my branch I took over issuing the PR for this. Kudos to him for narrowing it down to the bug happening in aggregation process though.
