### ISSUE TITLE
ui: polling interval too low when insights store is empty

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/cockroach#96190]
When the insights store is empty, the polling interval is extremely low (immediate). I believe this is because we are refreshing the store if the selector returns no data. We should implement some explicit polling here to make these requests less frequent.

https://www.loom.com/share/e72219baecd84c90bc1433f093bdb6da

This issue only affects db console.

Jira issue: CRDB-23994

**Comment by xinhaoz** [comment]
From the URL in the loom, it looks like this was tested on admin-ui through CC monitoring tools, which is still using a cluster ui version that is out of sync with managed-service's cluster-ui and doesn't include some important insights page updates. I wasn't able to repro this on a local build from master but I'll leave it up t you on whether or not you think it's still a bug.

**Comment by ericharmeling** [comment]
>  I wasn't able to repro this on a local build from master but I'll leave it up t you on whether or not you think it's still a bug.

Thanks for spending time looking into this! I think we want to leave this open until we can try to reproduce with the latest `cluster-ui` version. It could be a problem specific to the DB console on top of CC?

**Comment by ericharmeling** [comment]
After chatting with @xinhaoz offline, it looks like this was fixed in https://github.com/cockroachdb/cockroach/commit/aef669da59a5357fe33413decb427c246ed46b36#diff-db22c6a765a3abdfac07c1099b99bfaad4a33dc28a8657afd88ade4186753fafL128. Closing for now.
