### ISSUE TITLE
sql: `AS OF SYSTEM TIME` does not work in `cockroach demo`

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#96192]
To reproduce:

```
-- asof.sql
CREATE TABLE t (a INT);
SELECT * FROM t AS OF SYSTEM TIME '2023-01-01 12:00:00+00';
```

```
$ cockroach demo --empty -f asof.sql
```

This produces the error:

```
ERROR: database "defaultdb" does not exist
SQLSTATE: 3D000
```

If we can't support `AS OF SYSTEM TIME` in `cockroach demo`, we should make that clear in the error message. 

Jira issue: CRDB-23996

**Comment by msirek** [comment]
It works if you use AOST within the time that the demo cluster was created.
