### ISSUE TITLE
ui: unify permissions gating messages on DB console

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/cockroach#96199]
When trying to view the SQL Activity pages as a non-admin user, the Statement Fingerprint and Transaction Fingerprint Overview pages display the following message:

![image](https://user-images.githubusercontent.com/27286675/215539034-d73b1f0a-7692-4d48-9208-bf6f105981b0.png)

The Transaction and Schema Insights pages show the following message:

![image](https://user-images.githubusercontent.com/27286675/215539682-8e109620-c26f-46cf-a3f0-8e0d6298c26b.png)

The Statement Insights page shows the following message:

![image](https://user-images.githubusercontent.com/27286675/215539727-d36aee9a-b8e1-4bd0-a20c-d42cfdb1778f.png)

The Databases page *shows the databases*, but has "unavailable" for the overview rows:

![image](https://user-images.githubusercontent.com/27286675/215542085-4ab0e55d-861d-4f80-9db5-2d08a871d1b8.png)

Selecting the details for a single database returns the following message:

![image](https://user-images.githubusercontent.com/27286675/215542332-0033b273-af8a-4f76-8f08-e5c65d3b6bf5.png)

The Active Statements, Active Transactions, Sessions, and Jobs pages render as empty, but show no indication that the user does not have the proper permissions to view the data on the page.

We should unify the messages here to:
- Always return a message notifying the user of missing privileges.
- Use the same badge (INFO vs. WARNING).
- Display the same action ("Learn more" link vs. "Reload this page").
- Require the same privileges (or at least list all privileges required). The Schema and Transaction Insights pages, for example, require more than just MODIFYCLUSTERSETTING and VIEWCLUSTERSETTING.

Jira issue: CRDB-24000

**Comment by maryliag** [comment]
No longer a priority
