### ISSUE TITLE
server,ui: include more load factors in key visualizer

### ISSUE THREAD

**Issue by kvoli** [cockroachdb/cockroach#96197]
Currently the key visualizer samples QPS over the keyspace to display a key visualization where greater relative QPS emphasized relative to lower QPS key spans. This issue is to include more load factors in the key visualizer.

<details>
<summary>Example Key Visualizer View</summary>

![image](https://user-images.githubusercontent.com/39606633/215533248-6703138e-9c88-4eca-ba79-097563bcb77f.png)

</details>

However QPS is coarse as a metric and there exist more granular measures of load across keys that are currently displayed on the hot ranges page.

<details>
<summary>Example Hot Ranges Page</summary>

![image](https://user-images.githubusercontent.com/39606633/215533738-d758f4bb-c8f1-4492-bf7e-0566c10e0583.png)

</details>

These other load statistics are valuable to determine load over the keyspace in cases where operations are not uniform cost. e.g. QPS over two keyspans may both be 1 (1 batch req/second) whilst the bytes written per second may be 10kb in one keyspan and 0b on the other. In such an example, the user would be unaware of any difference between the two spans and may consider them equally as hot.

### Suggested Solution

Having multiple load statistics in a key visualizer that may be toggled between is common in other database providers[^1][^2]. A sensible approach to including more statistics is to have a toggle for different stats.

### Additional Load Factors

The following load factors are candidates for inclusion, ranked by relative importance.

1. CPU
2. Write Bytes
3. Read Bytes
4. Write Keys
5. Read Keys

[^1]: [Supports read bytes, read cpu, write bytes, write cpu, latency](https://cloud.google.com/bigtable/docs/keyvis-metrics)
[^2]: [Supports read keys, read bytes, write keys, write bytes](https://docs.pingcap.com/tidb/stable/dashboard-key-visualizer#select-metrics)

Jira issue: CRDB-23998

**Comment by maryliag** [comment]
No longer a priority
