### ISSUE TITLE
rpc: remove heartbeat service in favour of sideloaded clock monitoring on raft & batch RPCs

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#9619]
Heartbeats happen very infrequently compared to other intracluster traffic, leading to potential anomalies when clocks drift in a way that avoids detection but still exceeds the maximum offset.

We can shrink this window by monitoring clocks more aggressively. Concretely, attaching a clock reading to each Batch and RaftMessageBatch RPC should get this measurement lag down considerably.

**Comment by petermattis** [comment]
`s/Heartbeats/RPC-level heartbeats/g`

**Comment by tamird** [comment]
Another idea: GRPC allows using a custom codec. We could use this to encode into every RPC payload (literally, every payload) the clock timing information.

Another thought: currently we use the fact that Ping RPC is very fast to approximate latency between machines. Attaching these clock measurements to slower unary RPCs or streaming RPCs make it impossible to approximate latency in-band.

Perhaps we need to keep a floating measure of latency using the Ping RPC, and move the clock offset verification to the grpc codec.

**Comment by tschottdorf** [comment]
Good point about slow RPCs. With regards to Raft traffic, could we even instrument that given that it's not request-response but instead two independent streams?

**Comment by tamird** [comment]
Yes, that would not work (added emphasis):

> Attaching these clock measurements to slower **unary RPCs** or **streaming RPCs** make it impossible to approximate latency in-band.

**Comment by tamird** [comment]
Not planning to do this any time soon; unassigning.

**Comment by spencerkimball** [comment]
@tamird, I'm closing this due to my failure to see any actionable recommendation. Where is the practical problem we're experiencing? Re-open, comment, assign, remove 1.0 milestone, etc. if you disagree.
