### ISSUE TITLE
ui: insights auto-refresh should be disabled

### ISSUE THREAD

**Issue by j82w** [cockroachdb/cockroach#96210]
Insights shows the latest execution. If there is an active workload the insight page is difficult to use, because it keeps auto refreshing. You can see an insight that you want to investigate, but before you click it the page refreshes and the insight is gone. There should be a button to manually refresh or at least disable auto-refresh. That way a user can actually look through all the insights without the results constantly changing. 

Jira issue: CRDB-24005

**Comment by kevin-v-ngo** [comment]
@dongniwang FYI

**Comment by xinhaoz** [comment]
+1 that it would be disruptive to view while data is constantly being refreshed -- if we decide to make changes here we might also want to consider applying them to the recent execs pages. We also poll at a quick interval there and it'd be nice to be able to pause between refreshes to actually view data. Another design consideration for @dongniwang is that for insights,  entries may be evicted in our server-side cache between data refreshes, meaning those entries will disappear completely (not just reshuffled in the result).

**Comment by kevin-v-ngo** [comment]
We should consider this improvement in the context of the potential insights redesign.

**Comment by dongniwang** [comment]
Adding the feedback on autorefresh on SQL activity page here as well https://github.com/cockroachlabs/support/issues/2165#issuecomment-1490637859
