### ISSUE TITLE
clusterversion: make the "last update timestamp for preserve_downgrade_option" per tenant

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#96219]
**Describe the problem**

Currently, there is a go global variable in package `clusterversion` called `preserveDowngradeLastUpdatedMetric` which tracks the timestamp of the last update of the cluster setting `preserve_downgrade_option`.

However, this setting is different in each secondary tenant. The timestamps at which each tenant updates its own `preserve_downgrade_option` should be tracked separately.

**Expected behavior**

There should be different metrics in each secondary tenant.

cc @Santamaura @dhartunian @healthy-pod for triage.

Jira issue: CRDB-24011

Epic CRDB-12100

**Comment by dhartunian** [comment]
for reference this was introduced in https://github.com/cockroachdb/cockroach/pull/82633
