### ISSUE TITLE
ui: database details page returns error message from internal server error when tables in database are empty

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/cockroach#96211]
Navigating to the database details page for a database with tables with no data returns an error. We should find a better way to handle this error in the case of empty tables.

https://www.loom.com/share/12cd08a863494b2892d9834d9c856285

Jira issue: CRDB-24006

**Comment by gtr** [comment]
Closing this issue as it's been resolved since we moved to fetching info for the Databases Details Page via sql-over-http.

https://www.loom.com/share/760aabff6d4d442683990d050d106201
