### ISSUE TITLE
acceptance,multitenant: `TestDockerCLI/test_demo_multitenant.tcl` is flakey

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#96239]
**Describe the problem**

TestDockerCLI/test_demo_multitenant.tcl has flaked five times in the last 24h and is tripping up CI ([link](https://teamcity.cockroachdb.com/project.html?projectId=Cockroach_Ci_Tests&buildTypeId=&tab=testDetails&testNameId=4098955818022809867&order=TEST_STATUS_DESC&branch_Cockroach_Ci_Tests=__all_branches__&itemsCount=50)), most recently for #95905.

Jira issue: CRDB-24020

Epic CRDB-28893

**Comment by knz** [comment]
More tests skipped in #96339.

**Comment by knz** [comment]
Possibly relates to #96162.

**Comment by knz** [comment]
closed by https://github.com/cockroachdb/cockroach/pull/108631
