### ISSUE TITLE
gossip: Node initialization hangs if it tries to join itself

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#9625]
Trying to join yourself is obviously not a great idea, but is something I hit while testing out our Kubernetes configuration (see https://github.com/kubernetes/kubernetes/issues/33688 / https://github.com/cockroachdb/cockroach/pull/9623 for context on how). Unfortunately, if it does happen, the entire node blocks because the gossip client is able to open a connection but not able to get a response from the local gossip server. It'd be nice if this was cleaned up a bit such that we could spit out an error instead.

Here's an example log + stack trace from one such stuck server: [stuck_gossip.txt](https://github.com/cockroachdb/cockroach/files/501598/stuck_gossip.txt)

cc @tschottdorf

**Comment by bdarnell** [comment]
Our tests clusters (and recommended practice) include every node in the `--join` flag, so it's not unusual for nodes to try to connect to themselves. This is definitely a case we should handle. (which I think we do if there are multiple addresses in `--join`, but we also need to make sure we can retry if there's just one dns alias that might have multiple hosts behind it).
