### ISSUE TITLE
sql: make `timestamp with time zone` default `timestamp`, deprecate `without zone`

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#9627]
most users are going to just use `timestamp`, which, according to the spec, is shorthand for `timestamp without time zone`. that said, `timestamp with time zone` has much less surprising semantics and is what we want to encourage users to use (and have our builtin functions return). switching the shorthand to imply `with time zone` rather than `without` would go a long way towards only using one kind of timestamp (with zone) in practice, shielding users from some of the tricky gotchas we've discovered.

My main concern about doing so is that ORMs that create a `timestamp` column may not correctly handle it being a `timestamp with time zone` (even if we correctly send the `timestamptz` OID indicating it has a zone offset).

If, after changing the default to the session-aware type, we find that ORMs generally continue to function normally, we can likely go ahead and remove the `without zone` type completely and simplify many things by having only one type (including removing manual overload preferences).

In the event this isn't possible, that is, ORMs rely on the `without time zone` behavior, we likely need to explore top-level implicit coercions between the two types (details TBD, since hopefully we can avoid it entirely) to improve usability.

**Comment by mjibson** [comment]
I'm currently -1 on this because it's so surprising. I didn't know that `timestamp` was a shorthand for anything: I thought it was the only way to specify a without zone type. Why do we need only one timestamp in practice if SQL defines 2?

**Comment by dt** [comment]
Background: the the only difference between`timestamp with time zone` and `timestamp without time zone` types is whether they are aware _of the session_ zone: the `with zone` is sent to the client in the session offset while `without` is sent in UTC with no offset suffix, and when parsing a string to the session offset is assumed if no offset is specified for a `with zone` while UTC is assumed for `without`.

Now, as why do we want to only have one? Basically because mixing these types gets very confusing. 
For example, which type should `now()` return?
- If it returns a timestamp `without time zone` meaning it is unaware of the session offset, then `now()::date == current_date()` can sometimes be false since `current_date()` considers the session offset.
- If it returns a `timestamp with time zone`, you can't use it e.g. to insert into `TIMESTAMP` column without casting it.
- If we define multiple overloads of `now()`, returning either, then statements like `SELECT now()`, where the desired type isn't specified, cannot be typed.

**Comment by knz** [comment]
My side constraints are:
- inserting now() in a timestamp column should work always (especially considering it's likely that now() has been set as the default expression in extant db schemas already).
- whatever we do that diverges from the SQL spec needs to be amply documented.

+1 on @dt's proposal otherwise.

**Comment by dt** [comment]
side note: in postgres, `now` returns `timestamp with time zone` -- but pg also has implicit conversion of tz to no-tz, so you can use `now()` as the input e.g. `timestamp without time zone` -- they can be freely converted back and forth because the only difference is the session behavior.

**Comment by vivekmenezes** [comment]
Do you feel confident that if we change the builtins to return timestamptz and allow implicit casting it should be easy to use? This seems to be converging to postgres, and us better understanding some of their decisions.

**Comment by bdarnell** [comment]
I'm more comfortable with introducing implicit casts between the timestamp types than changing `TIMESTAMP` to mean `WITH TIME ZONE` (especially since our ORM compatibility efforts have made drop-in compatibility with postgres more important).

**Comment by knz** [comment]
Implicit casts are a slippery slope which I'd rather not approach. The specific kind of type cast that we could support was discussed yesterday with @dt: it would be allowed only at the top level of expression evaluation, in the specific case where a given SQL context (in particular an INSERT position) demands one type but the expression provides the other.  We must absolutely avoid implicit casts in the middle of expressions.

**Comment by vivekmenezes** [comment]
Do you think there is value to splitting this into two PR. One that changes
the builtins to return the timestamptz (already done) and another that
allows implicit casting at a well defined level easy for users to
understand clearly.

**Comment by vivekmenezes** [comment]
@knz I think you are suggesting we use implicit type conversion only for values read/written to the DB

**Comment by knz** [comment]
Vivek yes that is what I had in mind. Actually only for values written to the DB. For values read, no conversion.

**Comment by vivekmenezes** [comment]
Sounds good. Thanks

**Comment by dt** [comment]
w.r.t. splitting into separate PRs: Unfortunately as-in, when #9618 switching the `now()` builtin to return timestamptz, it will break anyone using it e.g. as the default value to a `timestamp` column, so without adding something (overloads [which introduce ambiguity], implicit conversions, etc), it's unclear it should land as-is.

**Comment by vivekmenezes** [comment]
It makes sense to land as one PR

**Comment by dt** [comment]
There's one workaround -- manually resolving the ambiguity between multiple equally compatible overloads -- which potentially serve as a stopgap until we do either this implicit coercion, a unification to a single type, something else.

I know @knz has serious slippery-slope concerns about adding complexity to type resolution, so it's not a great long term solution, but with it being manually chosen (so we know it only applies to `now()`), it might make sense as an intermediate state while we figure this out?

**Comment by dt** [comment]
More concretely if #9618 were on top of something like #9637, it would be free to introduce an additional `now()` overload that returned the other type, without worrying about introducing ambiguity that would break current callsites which have no `desired` type.

**Comment by dt** [comment]
@mjibson what's your objection to changing the default for the shorthand? is there a case where you'd need `timestamp without time zone` rather than `timestamp with time zone` (given that the only difference is awareness of session zone)?
timestamps that ignore the session offset seem very confusing in practice, particularly when other date and time functions are aware of the session offset, e.g. int the `now()::date != current_date()` example if `now` returns a non-session-aware timestamp.

**Comment by mjibson** [comment]
Yeah, let's change the default if it makes interactions with other time functions better.

**Comment by spencerkimball** [comment]
There are four assignees and still this issue lingers!

Could one of the four guilty parties either remove the 1.0 milestone or fix this in the following month?

**Comment by dt** [comment]
I think we concluded it'd break pg compat too much. 

The semantics are confusing, but people are used to it and may expect it, so we don't have much choice to implement it, and then discourage using non-zero session offsets (which is where it matters).
