### ISSUE TITLE
changefeedccl: audit existing cluster settings and update documentation

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#96275]
Changefeeds, like bulk and KV, have many settings that can have significant
impact on cluster performance.

Some of the settings are private/internal; some are public -- all need to be audited
to ensure that their documentation is up to date; update guidance on tuning those, etc.

TODO: Add a list of pertinent changefeed/kv (dist sender) settings.

Jira issue: CRDB-24040

**Comment by amruss** [comment]
https://github.com/cockroachdb/cockroach/issues/87356

**Comment by amruss** [comment]
Closing in favor of a docs issue: https://cockroachlabs.atlassian.net/browse/DOC-6817
