### ISSUE TITLE
A question about the consistency of the timestamp cache.

### ISSUE THREAD

**Issue by a1424360017** [cockroachdb/cockroach#96327]
**As far as I know, timestamp cache is a memory structure and will not use raft for backup**

**So, how to ensure the consistency of timestamp cache at Leader(LeaseHolder) Election**

Jira issue: CRDB-24067

**Comment by tbg** [comment]
We ensure via raft that leases are non-overlapping in (logical) time. Leases also have an expiration timestamp. So when a leaseholder crashes, the next leaseholder will have a lease that does not overlap temporally with the previous lease. When it starts using this lease, it has to conservatively populate the timestamp cache with that lease's start time. That way, the timestamp cache only ever moves "forward".

**Comment by a1424360017** [comment]
thank you

**Comment by a1424360017** [comment]
I want to know whether the following scenarios will occur when CRDB starts **pipelineWrite**
1、txn1 **Begin** with a lower timestamp
2、txn2 **Begin** with a higher timestamp
3、txn1 send **Write(key,newValue)** to cluster - node1(leaseHolder),node2,node3
4、node1 append this **request(Write)** to its log and returns
5、when this **log(Write)** has not been backed up, node2 becomes leaseHolder
6、txn2 send **Read(key)** to node2(LeaseHolder)
7、Because there is no concurrency conflict on node2 , node2 return a olderValue for **request(Read)**
8、node1 becomes leaseHolder again and backup **log(Write)** (I do not know whether there is R\W Conflict Judgement or Concurrency control)
9、txn1 Commit and txn2 Commit
So, txn2 with a higher timestamp does not read the value written by txn1 with a lower timestamp, which violate **SSI**

**Comment by tbg** [comment]
node 2 only becomes leaseholder when it has applied all previous log entries (the lease for n2 is a log entry). So when n2 serves the read for txn2, it returns the write by txn1 (or goes into conflict resolution).
