### ISSUE TITLE
roachtest: `t.Skip()` should behave like `TestSpec.Skip`

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#96351]
There are two ways to skip a test currently:

* using the `Skip` field on `TestSpec`: e.g., https://github.com/cockroachdb/cockroach/blob/194f6a1d560d377937d57d277323786942e495eb/pkg/cmd/roachtest/tests/synctest.go#L34-L36
* Calling `Skip()` (or `Skipf`) on `test.Test`, e.g.: https://github.com/cockroachdb/cockroach/blob/194f6a1d560d377937d57d277323786942e495eb/pkg/cmd/roachtest/tests/awsdms.go#L176-L179

However, the latter behaves differently from the former in a few ways: a) the test is marked as "passed" (in the logs and in the TC UI); and b) the message passed to `t.Skip()` is never logged, making things even more confusing.

`t.Skip()` should behave like setting the `Skip` field on the `TestSpec`: the reason for skipping should be logged, and the test should be marked as skipped in the TC UI.

Jira issue: CRDB-24080

**Comment by srosenberg** [comment]
Thanks for creating the issue! I am adding some historical context [1]. I've definitely run into this issue on several occasions. We should definitely address this paper cut.

[1] https://cockroachlabs.slack.com/archives/C01UDP33CCS/p1639497207011900
