### ISSUE TITLE
contention: fingerprints of contended transactions do not resolve on tenants

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/cockroach#96353]
On tenant clusters, the fingerprint IDs of contended transactions are never resolved in the event store. This results in the `{blocking, waiting}_txn_fingerprint_id` columns of the `crdb_internal.transaction_contention_events` table always having the value `\x0000000000000000`.

To reproduce:

- Create a local multi-tenant (demo) cluster.
- Run the `insights` workload against a tenant on the cluster.
- Query the `crdb_internal.transaction_contention_events` table on that tenant.

This bug was found on a 22.2.2 serverless cluster, and was reproduced on tenants of a 22.2.2 and 23.1-alpha1 demo cluster (`cockroach demo --multitenant=true --nodes=3`).

Jira issue: CRDB-24082

**Comment by j82w** [comment]
The contention event from the KV layer does not have the sql instance id in multi-tenant mode. The ContentionEvent.TxnMeta.CoordinatorNodeID is 0 which causes the logic to figure out the which sql instance id to send the request to get the fingerprint to fail with  `non existent SQL instance coordinator_id:"0"`.

**Comment by j82w** [comment]
This was fixed in: https://github.com/cockroachdb/cockroach/pull/97467
