### ISSUE TITLE
roachtest: add roachtest/workload for testing latency of ORM introspection queries

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#96359]
We have rttanalysis tests for queries made by ORMs: https://github.com/cockroachdb/cockroach/blob/067dc92538d0d433218c588187263fc93b19985d/pkg/bench/rttanalysis/testdata/benchmark_expectations

But as https://github.com/cockroachdb/cockroach/issues/96218 shows, there still can be latency regressions even if round trips don't change. We got somewhat lucky in catching that regression.

If we had latency benchmarks, we would have caught that issue more easily.

cc @dikshant 

Jira issue: CRDB-24085

**Comment by dikshant** [comment]
Other cases are #93955 and #100871

**Comment by rafiss** [comment]
Nevermind, that query is also there already: https://github.com/cockroachdb/cockroach/blob/de83c57d74a5034b7ae0cd37a892335cf478eed2/pkg/bench/rttanalysis/orm_queries_bench_test.go#L234
