### ISSUE TITLE
logictest: TestLogic_testserver_test_22_1_22_2 flaked

### ISSUE THREAD

**Issue by itsbilal** [cockroachdb/cockroach#96387]
See flake [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=8546651&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_BazelUnitTests). Skipping for now.

Jira issue: CRDB-24098

**Comment by rafiss** [comment]
i'll close this as a duplicate of https://github.com/cockroachdb/cockroach/issues/95247
