### ISSUE TITLE
schemachanger: dropping a database with thousands of descriptors results in an OOM

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#96392]
In trying to drop a database with 65k empty table descriptors I observed node 1 runs out of memory. If this is me running into the scale limits of the schemachanger then feel free to close this but I have some heap profiles attached in the zip below.

Steps to reproduce:

```
export CLUSTER=sc-test
roachprod create $CLUSTER -n 4
roachprod stage $CLUSTER cockroach
roachprod start $CLUSTER
roachprod sql $CLUSTER:1 
  - select crdb_internal.generate_test_objects('test',  65000);
  - use system;
  - drop database defaultdb cascade;
```

[dropzip.zip](https://github.com/cockroachdb/cockroach/files/10562680/dropzip.zip)

<img width="1592" alt="Screenshot 2023-02-01 at 4 57 46 PM" src="https://user-images.githubusercontent.com/13837382/216185492-c065c8c6-0d12-4b27-908f-f6f6e723aa2e.png">

Jira issue: CRDB-24100

**Comment by ajwerner** [comment]
We need memory monitoring. This is legit.

**Comment by ajwerner** [comment]
Two steps here:
1) Some memory monitoring that is conservative so that we fail out rather than OOM.
2) Look at the memory usage and reduce it so that we can support far more descriptors.

**Comment by ajwerner** [comment]
Broken out into https://github.com/cockroachdb/cockroach/issues/98631 and #98633
