### ISSUE TITLE
sql: add a cluster setting to easily roll back SCRAM

### ISSUE THREAD

**Issue by dikshant** [cockroachdb/cockroach#96408]
Downgrading from SCRAM currently requires multiple steps:
https://www.cockroachlabs.com/docs/v22.2/error-handling-and-troubleshooting#downgrade-from-scram-authentication

There are valid reasons why a user might want to downgrade:  compatibility with old drivers, unexpected connection latency hits, etc.

Having to alter the password for each user to downgrade them to SCRAM is not scalable if a cluster has many SQL users. We should think about a cluster setting that can effectively fold the three steps currently required to roll back to bcrypt into one.

Jira issue: CRDB-24398

Epic CRDB-17785

**Comment by rafiss** [comment]
As a reminder, here is what we currently have:
- cluster setting `server.user_login.password_encryption`. This controls how the password gets hashed when creating or changing a password.
- cluster setting `server.user_login.upgrade_bcrypt_stored_passwords_to_scram.enabled` cluster setting. If this is true AND if the `server.user_login.password_encryption` setting is `scram-sha-256`, then when a user logs in, the stored password hash will automatically be converted to SCRAM.

With that in mind, here are some options for how to solve the problem of needing to easily rollback to SCRAM.

1. Remove the `server.user_login.upgrade_bcrypt_stored_passwords_to_scram.enabled` setting completely. Add a new one that is named `server.user_login.convert_stored_password.enabled`. It would work by converting the current stored hash to become whatever `server.user_login.password_encryption` is currently set to.
    - There's a risk that an app that was using `server.user_login.upgrade_bcrypt_stored_passwords_to_scram.enabled` would break or get unexpected behavior.
2. Keep the `server.user_login.upgrade_bcrypt_stored_passwords_to_scram.enabled` setting. Also add a new one named `server.user_login.downgrade_scram_stored_passwords_to_bcrypt.enabled`. The behavior would be that if this is true AND if `server.user_login.password_encryption` setting is set to `bcrypt`, then when a user logs in, the stored password hash will automatically be converted to bcrypt.
    - The behavior is well defined, but the main downside is just the number of knobs to keep track of.
    - We should probably default `server.user_login.downgrade_scram_stored_passwords_to_bcrypt.enabled` to true (just like how `upgrade_bcrypt_stored_passwords_to_scram` defaults to true), so most users wouldn't need to worry about it. They'd only need to think of `server.user_login.password_encryption` most of the time.

**Comment by dikshant** [comment]
I like 2. It ensures most users are using SCRAM moving forward, and those who can not or run into issues with it can downgrade easily. 

We should test this in an upgrade scenario, though. 
Say a user is going from 22.1 to 22.2 with default cluster settings. Partway through the upgrade, they realize SCRAM is causing them issues, and they set the new cluster setting `server.user_login.downgrade_scram_stored_passwords_to_bcrypt.enabled` to true. We should ensure that doesn't cause any weirdness.

**Comment by rafiss** [comment]
Oh, I just realized a big issue with this. CRDB can only auto-convert the hash if it is presented with the cleartext password. For obvious reasons, CRDB does not store those, so that's why it could only get converted by running `ALTER USER ... WITH PASSWORD ...`.

For the case of auto-upgrade from bcrypt to SCRAM, it can get converted since bcrypt involves sending the password in cleartext during authentication. But since the purpose of SCRAM auth is to avoid sending the password in cleartext, we cannot auto-downgrade during authentication.

**Comment by rafiss** [comment]
I found a way past the above issue thanks to brainstorming with @dikshant. CRDB can request the cleartext password to be sent during auth, but still verify it using SCRAM hashing, and then downrade to bcrypt after that.

**Comment by dikshant** [comment]
> CRDB can request the cleartext password to be sent during auth but still verify it using SCRAM hashing and then downgrade to bcrypt after that.

With this discovery in light, let's go for solution two since that is now feasible. With `server.user_login.downgrade_scram_stored_passwords_to_bcrypt.enabled` set to true and `server.user_login.password_encryption` when set to `crdb-bcrypt` the user's password hash will automatically be converted to bcrypt during next login attempt instead of having to run ALTER PASSWORD for every user.

**Comment by rimadeodhar** [comment]
Does this mean we will always send clear text password irrespective of whether we use SCRAM or bcrypt for hash computation? Or only if the downgrade setting is enabled?

**Comment by rafiss** [comment]
the cleartext password will only be sent if the downgrade setting is enabled AND if the `server.user_login.password_encryption` setting is `crdb-bcrypt`. (the PR has tests that show this too)
