### ISSUE TITLE
build: upgrade to go 1.20

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#96443]
**Is your feature request related to a problem? Please describe.**

Go 1.20 is out. We generally do like to pick up the upgrades ahead of our major releases. This one is a good one. It has performance improvement in general, compile time improvements, and major improvements to generics. It also may have some good improvements for GC assist.

**Additional context**
This may help with:
* https://github.com/cockroachdb/cockroach/issues/89199
* #93977
* #88178

A prerequisite for shipping it would be fixing https://github.com/cockroachdb/errors/issues/99. @ajwerner is committed to doing that work in parallel to the dev-inf work to upgrade go.

Jira issue: CRDB-24129

**Comment by RaduBerinde** [comment]
https://github.com/cockroachdb/cockroach/pull/97260
