### ISSUE TITLE
cli: TestDockerCLI/test_demo_networking.tcl  flaked on master

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#96450]
See failure in CI here https://teamcity.cockroachdb.com/viewLog.html?buildId=8559246&buildTypeId=Cockroach_BazelEssentialCi

Jira issue: CRDB-24130

**Comment by msbutler** [comment]
i've hit this several times. Opening a PR to skip.

**Comment by adityamaru** [comment]
I'm not sure who triages server-related tickets these days, so pinging @knz just in case.

**Comment by rafiss** [comment]
https://github.com/cockroachdb/cockroach/pull/106463 unskips this and also fixes the logging. So if this flakes again, at least we can investigate it.
