### ISSUE TITLE
kv: TestCloser fails on some machines

### ISSUE THREAD

**Issue by healthy-pod** [cockroachdb/cockroach#96467]
TestCloser consistently fails on all runs on all of those GCP machines:
- n2d-highcpu-80
- c2-standard-60
- t2d-standard-48

~~They all run on x86 but use different processors than the current machine type we use in CI [n1-highmem-32] which uses Intel Broadwell. Tau T2D and N2D machines use AMD EPYC Milan and C2 machines use Cascade Lake. Maybe that's related?~~

The test fails only on machines with >= 46 cores.

[Example failure](https://teamcity.cockroachdb.com/viewLog.html?buildId=8563458&buildTypeId=Cockroach_ScratchProjectPutTcExperimentsInHere_UnitTestsTauT2dStandard48ahmadTesting)

Jira issue: CRDB-24138

**Comment by healthy-pod** [comment]
There's this interesting relationship between the number of cores (which gets used to calculate rate and burst) and the `1<<31` [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvserver/tenantrate/limiter_test.go#L58):
- make it 1<<33: test passes on up to 180 cores machine
- make it 1<<32: test passes on up to 90 cores machine
- keep it 1<<31: test passes on up to 45 cores machine
- make it 1<<30: test passes on up to 22 cores machine

**Comment by nvanbenschoten** [comment]
@healthy-pod I'm seeing `TestCloser` regularly fail on `release-22.1` (in https://github.com/cockroachdb/cockroach/pull/97519). Does https://github.com/cockroachdb/cockroach/pull/96663 need a backport to that branch?

**Comment by healthy-pod** [comment]
We didn't backport it because `Bazel Essential CI` is not required for releases before `22.2` so feel free to merge if `GitHub CI` passed. It might be better to backport it though so folks don't get confused so I will backport it today.
