### ISSUE TITLE
changefeed schemaregistry mtls feature request

### ISSUE THREAD

**Issue by daniel-crlabs** [cockroachdb/cockroach#96470]
**Is your feature request related to a problem? Please describe.**
Creating this feature request as requested on behalf customer. I've asked them to provide further details.

**Describe the solution you'd like**
changefeed feature request to support ca_cert client_cert and client_key in the schema registry option.

**Describe alternatives you've considered**
Unknown

**Additional context**
we have self hosted kafka and schema registry which supports mtls authentication only. Since we are unable to pass the cert related query parameters with the schema registry we are unable to use avro format.

Jira issue: CRDB-24139

**Comment by bobvawter** [comment]
X-Ref: #64622
