### ISSUE TITLE
scbuild: audit builder for low-hanging fruit

### ISSUE THREAD

**Issue by postamar** [cockroachdb/cockroach#96496]
While hacking on DROP TYPE CASCADE today I noticed there are quite a few instances in the builder where we throw NotImplemented errors in cases where we used to not be able to do a schema change because it would rely on functionality which wasn't there yet, but that functionality has since been added. I noticed this in particular in DROP COLUMN where we give up if the column is referenced in a constraint, but support for dropping constraint was added a few days ago.

Another aspect is unsupported syntax. I noticed that ADD UNIQUE was unsupported, but it would be trivial to add support for it.

It's hard to do these kinds of things when adding new functionality but it'd be good to go over this no later than the very beginning of stability period.

Jira issue: CRDB-24154

**Comment by ajwerner** [comment]
@Xiang-Gu I see you did some of this. Can you wrap up your assessment by filing issues, linking them here and closing this?

**Comment by Xiang-Gu** [comment]
I quickly comb over the builder and filed the following individual things we should be able to do without much hassle:
https://github.com/cockroachdb/cockroach/issues/96731
https://github.com/cockroachdb/cockroach/issues/96727
https://github.com/cockroachdb/cockroach/issues/96728
https://github.com/cockroachdb/cockroach/issues/96729
https://github.com/cockroachdb/cockroach/issues/96730

I'm closing this in favor of the above individual issues.
