### ISSUE TITLE
roachtest: use tags to resolve test target by cloud provider

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#96655]
Currently, the (hard to find) `roachtest_util.sh` [script](https://github.com/cockroachdb/cockroach/blob/master/build/teamcity/util/roachtest_util.sh#L69) decides which roachtests run on which cloud, rather than `testspec.tags`, which leads to a small amount of wasted cloud resources and a poorer developer experience.

As the script suggests, all roachtests run on gce by default. To prevent a roachtest from running on GCE then, the roachtest writer must skip the test  within the `TestSpec.Run` callback, after gce vms have been provisioned for the test. Example [here](https://github.com/msbutler/cockroach/blob/9e2332c39d69d9ce05e61e98a2c073833d38fc4c/pkg/cmd/roachtest/tests/restore.go#L727). 

The script also decides which roachtests run on the aws nightly using a brittle [regex](https://github.com/cockroachdb/cockroach/blob/master/build/teamcity/util/roachtest_util.sh#L69).

`testspec.tags` could be used instead to filter which tests run on which cloud at test registration, similar to their use for the `weekly` / `aws-weekly` test suite. Tags would obviate the regex filter, as the roachtest run command used in the `aws nightly` job could simply add an `aws` tag, similar the [aws-weekly](https://github.com/healthy-pod/cockroach/blob/067312c4729998bf424eb9022f4c69c0b1292468/build/teamcity/cockroach/nightlies/roachtest_weekly_aws_impl.sh#L19) job. To prevent a roachtest from running in the default gce nightly job, we could add a `aws-only` tag as well. 

Lastly, the use of tags would make it easy to see which tests run on which cloud, i.e. `roachtest list tag:aws`

Jira issue: CRDB-24267

**Comment by srosenberg** [comment]
It looks like we could easily extend `NewTestFilter` to support a conjunction of tags, e.g., `roachtest list tag:aws tag:weekly`. Currently, it supports only a single tag, e.g., `roachtest list tag:aws`. We probably don't need disjunction or negation until a future use-case arises.
