### ISSUE TITLE
opt: memo cache is not invalidated when a user-defined type's schema is renamed

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#96674]
We don't invalidate a cached memo referencing user-defined types when the schema owning the UDT is renamed.

```
defaultdb> create type sc1.t as enum ('foo', 'bar');
CREATE TYPE

defaultdb> select 'foo'::sc1.t;
t
-------
foo
(1 row)

defaultdb> alter schema sc1 rename to sc2;
ALTER SCHEMA

defaultdb> select 'foo'::sc1.t;
t
-------
foo
(1 row)
```

The last query should fail because `sc1` no longer exists.

Jira issue: CRDB-24272

**Comment by ajwerner** [comment]
Won't this fall out of drew's work on checking whether the memo is stale? If it doesn't the reason it doesn't would be that we're not tracking a reference to the schema.

**Comment by mgartner** [comment]
This is caused by the fact that we stored UDT OID's in the memo and lookup the types by OID to determine if they have changed. https://github.com/cockroachdb/cockroach/blob/e62ac1fd32ae3b4b3ff232013fcb36345e79d671/pkg/sql/opt/metadata.go#L335

We need to either:

* Store the original type reference in the memo and look up by that to determine if we have a stale memo.
* Or, track schemas referenced in a memo and check their version to determine if the memo is stale.

**Comment by DrewKimball** [comment]
This is a problem for tables referenced by IDs, too... I'm going to try adding schemas to the list of objects tracked during memo validation so we can just track function OIDs. I think it should allow us to make a similar simplification for data sources as well. @chengxiong-ruan added a fix for the switching databases problem in functions _[here](https://github.com/cockroachdb/cockroach/pull/96442)_; I think we could do something similar for resolving types, schemas, and data sources.
