### ISSUE TITLE
sql: better error message when trying to drop enum values referenced by udfs

### ISSUE THREAD

**Issue by rharding6373** [cockroachdb/cockroach#96694]
**Describe the problem**

The error message "relation [id] does not exist" when trying to drop values from types referenced by UDFs does not seem helpful to the user. An error describing the dependency would be better, if that's the behavior we desire.

**To Reproduce**

```
CREATE TYPE notmyworkday AS ENUM ('Monday', 'Tuesday');
CREATE FUNCTION f() RETURNS notmyworkday LANGUAGE SQL AS $$ SELECT 'Monday':: notmyworkday $$
ALTER TYPE notmyworkday DROP VALUE 'Monday';                          
-- ERROR: could not validate enum value removal for "Monday": relation "[110]" does not exist
ALTER TYPE notmyworkday DROP VALUE 'Tuesday';                         
-- ERROR: could not validate enum value removal for "Tuesday": relation "[110]" does not exist
```

Jira issue: CRDB-24280

**Comment by rafiss** [comment]
this was closed by https://github.com/cockroachdb/cockroach/issues/115612 and https://github.com/cockroachdb/cockroach/pull/118780.
