### ISSUE TITLE
sql: maintain an approximation of table row counts

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#9671]
- See question on the forum: https://forum.cockroachlabs.com/t/how-to-quickly-retrieve-estimate-number-of-rows-in-table/263/2
- See #9434 #9433  #7779

General idea:
- maintain per-table counters of added and removed rows in the SQL session during a txn
- upon commit, use the per-txn counters to update per-node counters, stored in the db (separate rows per node, to reduce contention), possibly in an asynchronous internal txn (the counts need not be accurate)
- every day/week run KV-layer scans on each node to make the counts more accurate
- when a user does `SELECT reltuples FROM pg_class WHERE relname = X` translate this to an aggregate query on the counter table across all nodes
- use this table in the admin UI

cc @mrtracy

**Comment by tschottdorf** [comment]
https://github.com/cockroachdb/cockroach/issues/7869

**Comment by knz** [comment]
Dup #7869 indeed. Thanks for noticing :)
