### ISSUE TITLE
capabilities: update the definition of the protobuf so that the zero protobuf struct results in pre-23.1 serverless behavior

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#96736]
**Describe the problem**

Once https://github.com/cockroachdb/cockroach/pull/96390 lands, the tenant capabilities subsystem will be hooked up. As a result, all secondary tenant requests will be subject to capability checks. As of the time of writing, the only `AdminRequest` that has capabilities associated with it is `AdminSplit`. However, this will soon expand to other operations such as scatters, relocate range, relocate lease etc. 

Internally, operations such as RESTORE/IMPORT etc. use these Admin requests. We will need to do something to prevent these operations from failing for existing (Serverless) tenants after upgrading to 23.1. 

(An option that was discussed internally, is to add a migration that grants secondary tenants `can_admin_split` (and any other capability they need that is added after writing up this issue) in `Serverless`. )

We are considering instead flipping the boolean meaning of the capabilities for pre-23.1 operations so that their default value coincides with what CC Serverless needs.

Jira issue: CRDB-24300
Epic:  CRDB-23344

**Comment by arulajmani** [comment]
cc @knz @stevendanna @ecwall

**Comment by knz** [comment]
What do you think should happen if we make a backup of a tenant record in version X, then restore it in version Y after the migration has run already?

The idea to use zero as the grant value would solve that, but maybe the DR team has better ideas.

**Comment by knz** [comment]
We've discussed this extensively with the team. At this stage the consensus is to **ensure that the default value of the info protobuf results in pre-v23.1 capability behavior for Serverless tenants** without the need for a new migration.

I will change the title of this issue accordingly. It is important to do this before the capability system can be enabled in Serverless.

**Comment by knz** [comment]
We further discussed this with @JeffSwenson . We only need to change the default behavior for the *specific capabilities* that were granted in serverless previously, namely that needed for AdminSplit and AdminScatter.

For all the other capabilities the Go default value should remain "capability not granted".
