### ISSUE TITLE
keyvisualizer: Select boundaries that have a higher resolution than ranges

### ISSUE THREAD

**Issue by zachlite** [cockroachdb/cockroach#96744]
Currently, the Key Visualizer uses the [system tenant's ranges](https://github.com/cockroachdb/cockroach/blob/7416aabb5da7c48c4184de08530c2149cd5fbc17/pkg/keyvisualizer/spanstatsconsumer/span_stats_consumer.go#L92) to tell the collectors which discrete pieces of the keyspace they should [collect statistics for](https://github.com/cockroachdb/cockroach/blob/7416aabb5da7c48c4184de08530c2149cd5fbc17/pkg/keyvisualizer/spanstatscollector/span_stats_collector.go#L275).

The effect of this, is that the highest resolution that we can collect statistics for, is that of ranges.  Since https://github.com/cockroachdb/cockroach/pull/79700, KV prefers to pack a secondary tenant's tables into as few ranges as possible, often times into just a single range. So for secondary tenants, the Key Visualizer can't provide meaningful insights. Additionally, the operator of a host cluster likely won't be able to resolve activity for a tenant. 

Jira issue: CRDB-24306

**Comment by maryliag** [comment]
No longer a priority
