### ISSUE TITLE
keyvisualizer:  Prevent propagating identical boundaries

### ISSUE THREAD

**Issue by zachlite** [cockroachdb/cockroach#96742]
Currently in the `SpanStatsConsumer`, boundaries are computed and propagated to the collectors with every sample tick.
This is implemented [here](https://github.com/cockroachdb/cockroach/blob/7416aabb5da7c48c4184de08530c2149cd5fbc17/pkg/keyvisualizer/spanstatsconsumer/span_stats_consumer.go#L53)

The boundaries are propagated via `UpdateBoundaries` every tick, regardless of whether or not the boundaries have changed since the last tick.  This is particularly wasteful, because we have to store the boundaries in the `system.span_stats_tenant_boundaries` table, and propagate them to each node via rangefeed.

It would be much nicer if we only called `UpdateBoundaries` when the boundaries have changed since the last tick.  
We should also investigate the ability to just propagate the diff between the last tick and the current tick.

Jira issue: CRDB-24305

**Comment by maryliag** [comment]
No longer a priority
