### ISSUE TITLE
sql schema: remove/fix tests that were ignored from bumping minBinary to V22_2

### ISSUE THREAD

**Issue by celiala** [cockroachdb/cockroach#96751]
In order to bump minBinary to V22_2, we ignored failing tests for future async removal/fixing
- issue: https://github.com/cockroachdb/cockroach/issues/95530
- pr: https://github.com/cockroachdb/cockroach/pull/96656

This issue is to track removing/fixing tests as needed for SQL Schema:

pkg/sql 
- [x] TestGatingCreateFunction (SQL Schema)

pkg/upgrade/upgrades: (SQL Schema)
- ~~TestAlterSystemSqlInstancesTable~~
- [x] TestAlterSystemStatementStatisticsTable
- ~~TestIsAtLeastVersionBuiltin~~ -- looks like just delete the test, but let's ask @yuzefovich 
  - Yahor: yeah, just delete this test
- TestSampledStmtDiagReqsMigration -- this is related to https://github.com/cockroachdb/cockroach/issues/96765; not our work
- TestSchemaTelemetrySchedule -- unskip after https://github.com/cockroachdb/cockroach/pull/98690
- TestWaitForSchemaChangeMigration -- looks like can delete the test, but let's ask @stevendanna 
- TestWaitForSchemaChangeMigrationSynthetic -- looks like can delete the test, but let's ask @stevendanna 

Jira issue: CRDB-24309

**Comment by ajwerner** [comment]
This is associated with https://github.com/cockroachdb/cockroach/issues/96763. Assigning the same folks.
