### ISSUE TITLE
sql: missing conversion from date to string

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#9675]
This came up on the forum: https://forum.cockroachlabs.com/t/format-timestamp-to-extract-just-the-date-string/285/4

I wanted to suggest `X::date::string` but there is no cast supported from date to string.
(I suggested `substring(X::timestamp::string, 1, 10)` as a replacement)

cc @nvanbenschoten did we have a reason to forbid such conversions?

**Comment by knz** [comment]
Additionally, the CLI render for dates should probably avoid printing out the time.

**Comment by nvanbenschoten** [comment]
I'm not aware of any reason why the cast doesn't exist. In fact, I think all types should have a valid cast to string, right? It looks like we may have just missed it.
