### ISSUE TITLE
storage: remove/fix tests that were ignored from bumping minBinary to V22_2

### ISSUE THREAD

**Issue by celiala** [cockroachdb/cockroach#96752]
In order to bump minBinary to V22_2, we ignored failing tests for future async removal/fixing
- issue: https://github.com/cockroachdb/cockroach/issues/95530
- pr: https://github.com/cockroachdb/cockroach/pull/96656

This issue is to track removing/fixing tests as needed for Storage:

pkg/storage (Storage)
- TestMakeIngestionWriterOptions

Jira issue: CRDB-24310

**Comment by jbowens** [comment]
Fixed by #96805.
