### ISSUE TITLE
sql schema: remove V22_2 gates and related logic/migrations/etc

### ISSUE THREAD

**Issue by celiala** [cockroachdb/cockroach#96763]
Now that we've bumped minBinary to 22.2[1], we should now remove all V22_2* version gates and related gated logic/migrations/etc as applicable.

V22_2 gates for SQL Schema[2]:

- [x] V22_2UseDelRangeInGCJob
    - I think this one needs to be hoisted into 23.1 given we did not ship the del ranges in 22.2.
- [x] V22_2SQLSchemaTelemetryScheduledJobs
    - @ajwerner to make permanent https://github.com/cockroachdb/cockroach/pull/98690
- [x] V22_2SchemaChangeSupportsCreateFunction
    - @chengxiong-ruan to delete.
- [x] V22_2UpgradeSequenceToBeReferencedByID
    - @Xiang-Gu to delete.
- [x] V22_2WaitedForDelRangeInGCJob
   - I think this one needs to be hoisted into 23.1 given we did not ship the del ranges in 22.2.
- [x] V22_2UpdateInvalidColumnIDsInSequenceBackReferences
   - @Xiang-Gu to delete.

[1] https://github.com/cockroachdb/cockroach/issues/95530
[2] Using git blame from https://github.com/cockroachdb/cockroach/blame/984c24b05bfe3c04ffd7bec5784d475796504522/pkg/clusterversion/cockroach_versions.go

Jira issue: CRDB-24318

**Comment by ajwerner** [comment]
All of the gates have now been dealt with.
