### ISSUE TITLE
style: formatting of function calls

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#9678]
Moving discussion from #8823 here. CC @jordanlewis @paperstreet @bdarnell @tamird 

--
I wonder if we should do a similar treatment to function calls:
```
short(arg1, arg2, arg3)
almostfits(
  arg1, arg2, arg3,
)
superlong(
  arg1,
  arg2,
  arg3,
)
```
Of course this might get tricky if an argument is also long (e.g. a `func` def).

--
Quoting @dt: Hm, since function calls can be passed things other than just identifiers -- expressions, literals, etc -- I think there's much more room for more subjective decisions w.r.t. readability and clarity than the signatures, so I imagine i might end up fighting such a formatter at times?

**Comment by RaduBerinde** [comment]
@dt True; but we may be able to isolate what the subjective decisions are about: I think they are mostly around splitting expressions into multiple lines (right?). We could accommodate those by having a simple rule like: all function calls that have multi-line expressions for an argument are formatted in the "long" style. `crfmt` would keep any line breaks within an expression as they are, and just enforce the style of having them on separate lines.

Even if we decide against automated formatting, we should have some guidance in our style guide as to a recommended way of wrapping long calls. We have quite a few different ways that show up often in our codebase.

**Comment by dt** [comment]
@RaduBerinde sounds good. I have no objection to adding something to the style guide, then, once we live it with it and make sure it works in practice, exploring if and how we can automate it.

**Comment by RaduBerinde** [comment]
Closing per discussion in #9687.
