### ISSUE TITLE
roachperf: regression on kv0/enc=false/nodes=3/cpu=32, aws but not gce

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#96800]
`kv0/enc=false/nodes=3/cpu=32` and a few related variants regressed on Feb 4th:

<img width="795" alt="Screen Shot 2023-02-08 at 11 41 16 AM" src="https://user-images.githubusercontent.com/5438456/217594515-ae78445d-6fc3-49de-befc-d2375f6af7a5.png">

This regression is only observed on AWS and not on GCE. It's also only observed on the 32 vCPU variant and not on the 8 vCPU variant.

I've determined that this was a result of https://github.com/cockroachdb/cockroach/pull/94165. When I run the benchmark and switch the `kv.raft_log.non_blocking_synchronization.enabled` cluster setting midway through to disable async storage writes, throughput increases.

<img width="550" alt="Screen Shot 2023-02-08 at 11 40 13 AM" src="https://user-images.githubusercontent.com/5438456/217594256-321db216-e704-4556-bc75-b0cce1b2c095.png">

Interestingly, log commit latency also drops.

<img width="990" alt="Screen Shot 2023-02-08 at 11 45 38 AM" src="https://user-images.githubusercontent.com/5438456/217595681-85f6d05d-2ca3-468a-8bfe-017ad5ff1dfe.png">

One possibility is that fsyncs on AWS instance stores (with `nobarrier`) are fast enough that we are exceeding the Pebble `SyncConcurrency` of 512. This would cause the async log writes to become synchronous. I don't know why this is worse than the non-async storage write configuration. One thought is that we might be observing the overhead of the asynchronous write path (two goroutine hops) without the benefit (because we're still blocking before entering it) and so we see the throughput regression. 

Another thought is that async storage writes trade-off reduced interference between writes on the same range for reduced batching of writes on the same range. In a system where the p50 fsync latency is **.10ms**, is this the right trade-off?

Next steps:
- experiment with a larger `SyncConcurrency`
- experiment with `nobarrier` disabled
- experiment with EBS volumes

Jira issue: CRDB-24341

**Comment by nvanbenschoten** [comment]
Omitting the `nobarrier` option on the instance store mount point did not change the 50μs p50 fsync latency.

**Comment by smg260** [comment]
Looks like this did, in fact, affect GCE performance. I arrived at the same commit when bisecting.

*GCE*
<img width="804" alt="image" src="https://user-images.githubusercontent.com/25202158/219145114-1759c824-0067-45de-ae6c-6f027098b778.png">

**Comment by nvanbenschoten** [comment]
I've been digging into these two classes of regressions. I think there are three different aspects of these tests that are combining to cause the throughput reductions. The first and second apply to the AWS regressions and the second and third apply to the batched kv regressions:

1. AWS is using local instance stores. p50 fsync latency is 50μs, which is between one and two orders of magnitude faster than the disks CRDB typically runs on. [Notice](https://roachperf.crdb.dev/?filter=kv&view=kv95%2Fenc%3Dfalse%2Fnodes%3D3&tab=aws) that these kv tests all push about 50% more throughput on AWS than the same test pushes on GCP — a result of the difference in disk performance. This hardware configuration skews the throughput/latency trade-off of async storage writes.

2. The kv roachtest benchmark suite is over-splitting ranges. Each test initially performs 1000 splits. When I remove this and let load-based splitting pick the optimal number of splits, kv tests end up with around 50. The effect of so many ranges is that intra-range batching at the Raft level is non-existent. We have a [TODO](https://github.com/cockroachdb/cockroach/blob/1bb2934c6d7fe65fe063d03e5e33a3d1dec294ac/pkg/cmd/roachtest/tests/kv.go#L70-L72) to remove this over-splitting. If I do that, throughput meaningfully increases.

3. The batched kv benchmark variants are not accounting for the batch size in the workload concurrency, so they are badly overloading their cluster. This leads to p50 latencies in the 300-400ms range, about 20x greater than the corresponding p50 in a non-overloaded cluster. In this degraded regime, performance is unstable and non-representative. In other words, we're ending up far to the right of [this graph](https://user-images.githubusercontent.com/5438456/209210719-bec842f6-1093-48cd-8be7-05a3d79c2a71.svg).

So where do we go from here? Ideally, we'd fix all three of these issues. Changing benchmarks is tricky though — we use them to detect regressions and don't want to lose continuity.

----

That said, I do think we should fix issue 3 immediately. These clusters are so overloaded that the results aren't usable. I've done that in https://github.com/cockroachdb/cockroach/pull/98648. This change drops p50 latency from about 400ms (far into overload) to about 40ms (approaching overload). However, it also does hurt top-line throughput by about 10%. We'll need to add an annotation to roachperf to reflect this.

With that resolved and the workload no longer overloading the cluster, the question becomes: do we still see a regression from async storage writes on the workload. The answer is no. In fact, async storage writes now shows up as a ~20% throughput win (_note: we disable the change using the cluster setting and see a reduction in throughput_):

<img width="860" alt="Screenshot 2023-03-14 at 10 16 52 PM" src="https://user-images.githubusercontent.com/5438456/225187790-75a2d01c-3ef8-439d-bd9b-8f7d49785402.png">

For completeness, we also compare master (with async storage writes enabled) against v22.2 (c5a5c57d9e77415cbb235e51d5f385941be44510) using the new workload configuration. Again, master with async storage writes comes out on top. master averages **778.7 qps** while v22.2 averages **743.8 qps**. When not overloaded, we now see an increase in throughput between the two versions of about **4.7%**.

This matches the previous benchmarking performed in https://github.com/cockroachdb/cockroach/pull/94165. The change trades improved performance (latency and throughput) before overload for worse performance (latency and throughput) far into overload. This is of course a trade-off that we're happy to make.

----

The over-splitting is the other workload problem that we should do something about. Pre-splitting was added to these tests many years ago when load-based splitting was nascent. Load-based splitting is now mature and is able to find a better split count than we are able to manually. In each of the kv roachtests that I had looked at, removing the `--splits` flag has increased throughput.

However, I don't think the stability period is the right time for this. It's a disruptive change to all of these benchmarks and may let a real regression slip through. I've opened TODO for further discussion. I'd suggest that we merge it early in the next release cycle.

----

This leaves us with the original AWS-only regressions. I'll spend some more time tomorrow/this week looking at it to determine what, if anything, we want to do about those regressions.

**Comment by nvanbenschoten** [comment]
I dug further into the regression on `kv0/enc=false/nodes=3/cpu=32` when running on AWS. There are two additional aspects of the regression that deserve mention. Doing so helps explain why we see this on some tests but not others.

First, recall from the previous comment that AWS instance stores **(1)** and over-splitting **(2)** are still very much in play with this regression. The third aspect that's relevant is the **high core count** in this test. While most kv tests run on a host with 8 vCPUs, this test runs on a host with 32 vCPUs. The fourth aspect that's relevant is that this is kv0, so **100% of the workload is write operations** that go through Raft.

What do these four factors add up to? A raft scheduler that's overloaded due to mutex contention. Mutex contention was already the bottleneck for this workload before https://github.com/cockroachdb/cockroach/pull/94165. https://github.com/cockroachdb/cockroach/pull/94165 then added two more calls into the raft scheduler for each Raft write, so mutex contention is now an even bigger bottleneck. I believe this is an increase of 66%, from 3 calls into the raft scheduler per write to 5 calls into the raft scheduler per write.

To summarize, the regression requires the confluence of four factors:
1. AWS instance stores are 20x lower latency than the disks we usually use. With the workload's fixed concurrency, this shifts the limiting factor away from disk sync latency to the raft scheduler. Notice that we don't see a regression on [GCP's `kv0/enc=false/nodes=3/cpu=32`](https://roachperf.crdb.dev/?filter=kv0%2Fenc%3Dfalse%2Fnodes%3D3%2Fcpu%3D32&view=kv0%2Fenc%3Dfalse%2Fnodes%3D3%2Fcpu%3D32&tab=gce).
2. Over-splitting ranges means that the test does not benefit from intra-range batching. This means that calls by a replica into the raft scheduler are often on behalf of a single write, not multiple Notice that we don't see as much of a regression on [`kv0/enc=false/nodes=3/cpu=32/splt=0`](https://roachperf.crdb.dev/?filter=kv0%2Fenc%3Dfalse%2Fnodes%3D3%2Fcpu%3D32&view=kv0%2Fenc%3Dfalse%2Fnodes%3D3%2Fcpu%3D32%2Fsplt%3D0&tab=aws) (though a regression does still exist).
3. High core count means that the cluster has more capacity to push higher throughput, but also that the Raft scheduler is doing more work and mutex contention is more of a problem. Notice that we don't see any regression on [`kv0/enc=false/nodes=3` (8 cpus)](https://roachperf.crdb.dev/?filter=kv0%2Fenc%3Dfalse%2Fnodes%3D3&view=kv0%2Fenc%3Dfalse%2Fnodes%3D3&tab=aws). Meanwhile, we see an even larger regression on a [96-core variant of the test](https://roachperf.crdb.dev/?filter=kv0%2Fenc%3Dfalse%2Fnodes%3D3&view=kv0%2Fenc%3Dfalse%2Fnodes%3D3%2Fcpu%3D96&tab=aws).
4. kv0 means that all operations are writes that pass through Raft, so every operation hits the raft scheduler. Notice that we don't see a regression on [`kv95/enc=false/nodes=3`](https://roachperf.crdb.dev/?filter=kv95%2Fenc%3Dfalse%2Fnodes%3D3&view=kv95%2Fenc%3Dfalse%2Fnodes%3D3&tab=aws).

----

So now that this is understood, what can we do about it? There are short-term wins and long-term wins.

An easy short-term win is to eliminate unnecessary uses of the Raft scheduler to relieve pressure on its mutex. We can easily eliminate one of the two calls into the raft scheduler that was added in https://github.com/cockroachdb/cockroach/pull/94165 through a change like https://github.com/nvanbenschoten/cockroach/commit/8949816f0d87ebb86c51b80b4d0a050c01d28d47. These calls into the raft scheduler were from `MsgStorageApplyResp` messages. However, these messages are processed by a goroutine that's already running on the scheduler, so there's no need to re-schedule.

A less trivial change would be to eliminate the other new call into the raft scheduler, which is from `MsgStorageAppendResp` messages. These messages are sent from a callback on raft log syncs. The messages are also meant for bookkeeping, so they're not critical, but we'd still like them to be delivered with some timeliness to permit truncation of the in-memory unstable Raft log. Without a call into the raft scheduler in response to these messages, it's difficult to guarantee that they will ever be delivered.

I've confirmed through experimentation that avoiding a call into the Raft scheduler in both of these cases eliminates the regression.

A longer-term win would be to improve the Raft scheduler so that it can be run at higher throughput without mutex contention issues. One approach we could take for this is to shard its central mutex. I've done so bluntly in https://github.com/nvanbenschoten/cockroach/commit/46e416eac1ad0cc14682248b9af8238c46d3e2f1. That patch not only eliminates the performance regression, but it also allows us to hit a throughput above the baseline — around 80k qps on `kv0/enc=false/nodes=3/cpu=32`. Unfortunately, this kind of change is probably not appropriate for the stability period.

I'll continue testing and looking into what we can do now to close the gap.

**Comment by nvanbenschoten** [comment]
> I believe this is an increase of 66%, from 3 calls into the raft scheduler per write to 5 calls into the raft scheduler per write.

To verify this, I added some instrumentation to raft scheduler interactions and re-ran the test. Here are the results:
```
$ rg 'SCHED_PROF' cockroach.stdout.log | wc -l
18688214

$ rg 'SCHED_PROF' cockroach.stdout.log | sort | uniq -c | sort -nr
9264620 SCHED_PROF: github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:286
8212666 SCHED_PROF: github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1606
1118390 SCHED_PROF: github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal_buf.go:1163
  90503 SCHED_PROF: github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1071
    657 SCHED_PROF: github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:281
    656 SCHED_PROF: github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:280
    381 SCHED_PROF: github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:2118
    340 SCHED_PROF: github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:781
      1 SCHED_PROF: github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_split.go:215
```

Over a minute or so period, we saw 18688214 raft schedulers "enqueue" calls. There we 4 prominent callers:
- `HandleRaftRequest`'s call to `EnqueueRaftRequest` was responsible for **49.6%** of the calls
- `sendLocalRaftMsg`'s call to `enqueueRaftUpdateCheck` was responsible for **43.9%** of the calls
- `propBuf.insertIntoArray` call to `enqueueRaftUpdateCheck` was responsible for **6.0%** of the calls
- `handleRaftReadyRaftMuLocked`'s call to `enqueueRaftUpdateCheck` was responsible for **0.5%** of the calls

`sendLocalRaftMsg` was added by https://github.com/cockroachdb/cockroach/pull/94165. So that PR almost doubled the pressure on the raft scheduler, which explains why it's exacerbating mutex contention, leading to the regression.

I'll update the profiling to give us information about the distribution of callers of `sendLocalRaftMsg`, which will help us understand how impactful https://github.com/nvanbenschoten/cockroach/commit/8949816f0d87ebb86c51b80b4d0a050c01d28d47 will be.

**Comment by nvanbenschoten** [comment]
With the different callers of `sendLocalRaftMsg` split out, we see:
```
$ rg 'SCHED_PROF' cockroach.stdout.log | wc -l
21547717

$ rg 'SCHED_PROF' cockroach.stdout.log | sort | uniq -c | sort -nr
10250938 SCHED_PROF: github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:286
 6029453 SCHED_PROF: github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1491
 3821449 SCHED_PROF: github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1032
 1321233 SCHED_PROF: github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_proposal_buf.go:342
  122528 SCHED_PROF: github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1071
     692 SCHED_PROF: github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:280
     680 SCHED_PROF: github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:281
     385 SCHED_PROF: github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:2120
     357 SCHED_PROF: github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:780
       2 SCHED_PROF: github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_split.go:215
```

From here, we can see that of the **43.9%** of all uses of the Raft scheduler from `sendLocalRaftMsg`'s call to `enqueueRaftUpdateCheck`, **61%** are for `MsgStorageAppendResp` and **39%** are for `MsgStorageApplyResp`.

Put differently, https://github.com/nvanbenschoten/cockroach/commit/8949816f0d87ebb86c51b80b4d0a050c01d28d47 reduces the use of the raft scheduler by **17.8%**. Seems worthwhile.

**Comment by nvanbenschoten** [comment]
Now that https://github.com/cockroachdb/cockroach/pull/98833 and https://github.com/cockroachdb/cockroach/pull/98854 have landed, I'm going to close this. Those optimizations more than avoid the regression.
