### ISSUE TITLE
sql: gating "Reset SQL Stats" behind a permission flag

### ISSUE THREAD

**Issue by fabiog1901** [cockroachdb/cockroach#96876]
This ticket to request that the **Reset SQL Stats** capability should  be enabled by a specific permission flag and not solely be a privilege for the admin/root user.

[Slack](https://cockroachlabs.slack.com/archives/CHVV403F0/p1675956217067569)

Jira issue: CRDB-24384

gz#16110

Epic CRDB-32130

**Comment by maryliag** [comment]
No longer a priority

**Comment by rafiss** [comment]
This endpoint now checks for the REPAIRCLUSTERMETADATA system privilege, so you don't need to be an admin. This was changed in https://github.com/cockroachdb/cockroach/pull/110609 and backported to 23.1.
