### ISSUE TITLE
example-orms test suite panicked in unrelated PR off master

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#96976]
See in CI [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=8663417&problemId=2751).

Jira issue: CRDB-24443

**Comment by rafiss** [comment]
The panic here is
```
2023/02/10 17:39:21 waiting for app server port to become available
panic: test timed out after 10m0s
```

**Comment by rafiss** [comment]
Closing as this does not seem to be happening any more.
