### ISSUE TITLE
changefeedccl: add changefeed_max_behind_nanos to metrics labels

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#97009]
People want the ability to track changefeed_max_behind_nanos by scope, so that they can alert on different slas according to this metric.

Since we want to deprecate changefeed_max_behind_nanos, we should add a new metric max_checkpoint (that tracks the same thing) to metrics labels.

We're also planning on adding this, which will be better for SLAs than the max behind nanos
https://github.com/cockroachdb/cockroach/issues/102146

Jira issue: CRDB-24459

Epic CRDB-29938

**Comment by amruss** [comment]
Moving this back into triage as this was brought up by a customer. Though we recommend using commit latency for latenyc tracking, they want to track SLAs for maximum behind checkpoint

Maybe we should add a new max_checkpoint metric instead.

**Comment by miretskiy** [comment]
No updates from me; I wasn't planning to work on this until @samiskin work on metrics.

**Comment by samiskin** [comment]
Looking at the healthy metrics right now, I can grab this ticket too and do em together
