### ISSUE TITLE
Migration from MySQL/MariaDb 10.3

### ISSUE THREAD

**Issue by 3pos** [cockroachdb/cockroach#97048]
Migration from exported .sql File of an MariaDb10.30
with the command
cockroach sql --certs-dir=certs --set display_format=records -e “USE database_2; IMPORT MYSQLDUMP (‘nodelocal://1/2.sql’) WITH DETACHED”
lead to an error. The Job was created but failed with the message: unknown signature: current_timestamp() (desired int)
It seems that the standard MySQL command for inserting current timestamp failed.

Please describe the issue you observed, and any steps we can take to reproduce it:

Export from MariaDb10.3 SQL file with Data and structure of an whole database.
Can be `created` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
or
`created_date` timestamp NOT NULL DEFAULT current_timestamp(),
or
  `created_date` int(11) NOT NULL DEFAULT current_timestamp(),
  `updated_date` int(11) NOT NULL DEFAULT current_timestamp(),

What did you do? Describe in your own words.
Created a mysql dump and tried to import it into the cockroachdb cluster:
cockroach sql --certs-dir=certs --set display_format=records -e “USE database_2; IMPORT MYSQLDUMP (‘nodelocal://1/2.sql’) WITH DETACHED”

**Environment:**
 - CockroachDB version v22.2.3
 - Server OS: Debian 11
 - Client app cockroach sql

Jira issue: CRDB-24483

**Comment by msbutler** [comment]
@shermanCRL looks like blathers still wants to triage import issues to us. I have a vague recollection that you patched blathers to prevent this?

**Comment by shermanCRL** [comment]
@msbutler Yes I will update

**Comment by rafiss** [comment]
Thanks for reporting your issue. I want to make sure I understand correctly: are you using the `current_timestamp()` function to populate an `int` column?

Can you please provide the `.sql` file you are trying to import? (Or provide a smaller example file that reproduces your problem?)

**Comment by 3pos** [comment]
Hello, yes we're using int. Its then getting inserted as unix timestamp.

I have tried to import a partial sql but im then getting another error message in job overview:
nodelocal://1/3.sql: reading row 3 (1 in insert statement 2): unsupported value type : &{3 [48 120 49 49 101 98 55 102 52 57 55 56 99 49 50 98 48 57 57 48 49 55 48 9 7 49 99 57 101 48 54 48 50 53 98]}


[3.zip](https://github.com/cockroachdb/cockroach/files/10744195/3.zip)

**Comment by rafiss** [comment]
While we investigate this further, you can try using our Schema Conversion Tool to do your data migration. See these docs: https://www.cockroachlabs.com/docs/stable/migration-overview.html

**Comment by mgartner** [comment]
`current_timestamp` is a value of type `TIMESTAMPTZ`, which cannot be implicitly cast to an `INT` in an `INSERT`. You'll have to manually convert it to an integer representing the UNIX timestamp with something like: `extract(epoch from current_timestamp)::INT`.
