### ISSUE TITLE
File Descriptors not closed on Restore

### ISSUE THREAD

**Issue by benbardin** [cockroachdb/cockroach#97040]
After running a Restore from cloud storage, the files written to the cockroach nodes' local disks remain open. (Can verify with `lsof -p <pid of CRDB>) This is a leak, and those files should be closed as they are written.

Here’s a sampling of such files. On an 8TB restore, we see about 150k of these.

cockroach 10095 ubuntu *993r      REG                9,0   7130957 114851170 /mnt/data1/cockroach/107098.sst
cockroach 10095 ubuntu *994r      REG                9,0   7075613 114851177 /mnt/data1/cockroach/107105.sst
cockroach 10095 ubuntu *995r      REG                9,0   6952499 114851182 /mnt/data1/cockroach/107109.sst
cockroach 10095 ubuntu *996r      REG                9,0   7072957 114850991 /mnt/data1/cockroach/107113.sst
cockroach 10095 ubuntu *997r      REG                9,0   7006444 114851190 /mnt/data1/cockroach/107118.sst
cockroach 10095 ubuntu *998r      REG                9,0   7024104 114851192 /mnt/data1/cockroach/107124.sst
cockroach 10095 ubuntu *999r      REG                9,0   7041144 114851157 /mnt/data1/cockroach/107129.sst
cockroach 10095 ubuntu *000r      REG                9,0   6928355 114851201 /mnt/data1/cockroach/107131.sst
cockroach 10095 ubuntu *001r      REG                9,0   7009250 114851208 /mnt/data1/cockroach/107137.sst

**Comment by dt** [comment]
Can you update the issue with reproduction details?

**Comment by dt** [comment]
> the files written to the cockroach nodes' local disks remain open

These are hardlinked into pebble and I believe it may keep them open at its discretion? are we sure that that it is a leak versus pebble just keeping recently used files open as long as it is in budget?

**Comment by benbardin** [comment]
I mean, I guess it might be by design? But there's 150k of them. That seems like a lot.
