### ISSUE TITLE
sql: EXTRACT does not pretty-print to parsable syntax

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#9705]
the cycle parse -> prettyprint -> parse is broken for EXTRACT:

```
EXTRACT(SECOND FROM NOW())
-- prints to
EXTRACT('second', NOW())
-- parses to
syntax error
```

This breaks history normalization from d4df9a804211b92df089916004f04f0cc08a68f3.

I think the fix is simply to enable parsing `extract(string, expr)` as an expression in addition to / next to `extract(identifier from ...)`

cc @mjibson

**Comment by mjibson** [comment]
I concur. There are various other functions that have this weird keyword syntax. They should all also work as described above.
