### ISSUE TITLE
changefeedccl: improve parquet performance

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#97068]
Improve parquet file format throughput ahead of the 23.1 release.

Possible things to improve:
- add parallel encoding
- change library we're using

Jira issue: CRDB-27372

Epic CRDB-15071

**Comment by jayshrivastava** [comment]
Closing in favor of https://github.com/cockroachdb/cockroach/issues/106591. https://github.com/cockroachdb/cockroach/issues/99028 is the issue which tracks adding the new library, which has been completed.
