### ISSUE TITLE
change order by for statement_statistics

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#97075]
Currently to retrieve the top queries for the SQL Activity page, we do an order by on the aggregated_ts, but that doesn't return the most interesting queries.

The order by should be on a more significant query, such as latency, max_latency, etc. (Depending on the value chosen, it might need a new index created on that column)

Jira issue: CRDB-24492

**Comment by maryliag** [comment]
cc @kevin-v-ngo on what you think we should order by

**Comment by kevin-v-ngo** [comment]
@dongniwang, this relates to reactive vs proactive user flows. 

We've discussed Proactive (e.g., give me the top N) being insights. Reactive being SQL Activity (e.g., what's causing this signal to spike/dip by time).

**Comment by dongniwang** [comment]
I guess execution count, latency, CPU time would all be helpful from a performance perspective. Would it be possible to group things into category and allow users to view things from a different perspectives? Almost works like a quick filter?

**Comment by maryliag** [comment]
With the new design, this issue is no longer valid.
