### ISSUE TITLE
Large Cluster Node Rotation High CPU

### ISSUE THREAD

**Issue by STRATZ-Ken** [cockroachdb/cockroach#97085]
**Describe the problem**

Hello, we have a 12 Node Cluster.  

The general issue is we have a weird problem with the CPU is spiking on one server that rotates.  For example Server 1 might have a high CPU for a few days, then Server 2 will have a high CPU.  However, shutting down that server, will NOT bring another server up in CPU.  

Please see picture below 
![image](https://user-images.githubusercontent.com/24981405/218594887-36947374-b918-4308-816d-e45238663d35.png)

**To Reproduce**

We have noticed that if we attempt to join a failed node to a cluster with existing data, we will have high CPU usage on that node pretty much indefinitely.  Only after purging the data drives, does the node join an existing cluster. However, to be able to replicate this issue may be difficult.  I have spoken with Andrew Werner in Slack for a while, but he suggest creating this ticket.  

**Expected behavior**
Since all hardware is the same specs, and the same cluster. I would assume the queries should be even through the cluster.  If the CPU load was due to SQL queries, then I would assume if I shutdown this node, other nodes would go up in CPU usage.  However that does not happen.

![image](https://user-images.githubusercontent.com/24981405/218595553-c962b38b-3a82-48a1-8228-6dacb5c42c5c.png)

**Additional data / screenshots**
We also notice that sometimes this CPU usage will cause massive lag to the entire cluster.  To the point that every query takes 10 seconds to execute (timeout). Once we shutdown the node in question, the entire cluster quickly recovers and the P99 latency drops to 200ms~.

![image](https://user-images.githubusercontent.com/24981405/218595717-eaed9e2c-ab54-4910-b631-8c372c123817.png)

**Environment:**
-CockroachDB Version V22.2.3-48-G454A62F220
-CPU 5950X AMD
-RAM 128GB DDR5 
-OS Drive 500GB NVM m2.
-DATA Drive 7.6TB NVM DC1500M (Server Enterprise drives)
-OS Ubuntu 22.04 LTS
-Cluster Size 55.3TB

All nodes are the exact same specs, hard drives, bios versions, etc.

Profiles of the node and random times.

[profile (3).pb.gz](https://github.com/cockroachdb/cockroach/files/10727040/profile.3.pb.gz)
[profile (2).pb.gz](https://github.com/cockroachdb/cockroach/files/10727041/profile.2.pb.gz)
[profile (1).pb.gz](https://github.com/cockroachdb/cockroach/files/10727042/profile.1.pb.gz)

Jira issue: CRDB-24498

**Comment by rytaft** [comment]
Hi @STRATZ-Ken,

It's difficult for me to say what's going on without knowing more about your workload, but in the past we've seen unbalanced CPU utilization like this when there are a couple of hot ranges that are getting frequently accessed or when there is a query that is frequently executed that is using a suboptimal plan. I suggest you look at the SQL Activity page in the DB console and see if you can optimize any of the queries that are using a lot of CPU.

If you'd like us to analyze the source of the CPU imbalance in depth, the proper process to get engineering to look at the issue would be to use a support channel. Please contact our sales team if you'd like to consider a support contract.

**Comment by STRATZ-Ken** [comment]
@rytaft  I would agree with your statement if the replication factor equaled the amount of nodes having issue.  If we have a hot range, and we assume the load balancer is randomizing queries, we should have 3 or so nodes that are hot.  Since the queries would be handed off equally.  That is not happening here.  So I can't say I agree with that statement.  

Sorry, we are unable to afford your pricing model as we did look into a support contract.

**Comment by rytaft** [comment]
> If we have a hot range, and we assume the load balancer is randomizing queries, we should have 3 or so nodes that are hot.

Does this mean you are using follower reads for all your queries? If not, the leaseholder will have much higher load than the follower replicas.

> Sorry, we are unable to afford your pricing model as we did look into a support contract.

Sorry to hear that, but you'll understand, then, that we're not going to be able to dig very deep into this issue.
