### ISSUE TITLE
ci: run a nightly with the `deadlock` tag

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#9713]
Ideally also including longer versions of the acceptance tests, or a cluster test.

**Comment by jordanlewis** [comment]
What about just running `make stress` with `deadlock`?

**Comment by tschottdorf** [comment]
Worth a try, though the `deadlock` tag has huge overhead which I think together with `race` might make things unbearably slow and congested.

**Comment by tamird** [comment]
Might be able to reuse some infrastructure from #9742.

**Comment by tamird** [comment]
We now have these binaries being uploaded to s3 with the name "static-tests-deadlock.tar.gz" where each test binary is `foo.test.deadlock`. The last remaining step is to hook these up to the nightly stress tests.
