### ISSUE TITLE
Transactional schema change - support/error handling

### ISSUE THREAD

**Issue by filacouris** [cockroachdb/cockroach#97157]
Executing multiple ddl statements within a transaction results in the following:

- high likelihood of retry errors
- lack of atomicity 

Present day this can lead to friction in migration patterns and schema operations.

Request: better support for transactional schema changes or clearer errors/hints to eliminate friction

Jira issue: CRDB-24545

**Comment by ajwerner** [comment]
The lack of atomicity is tracked in https://github.com/cockroachdb/cockroach/issues/42061 and lots of work in underway as we implement https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20200909_transactional_schema_changes.md and https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20200909_transactional_schema_changes.md. 

As for the starvation, it is actively being worked on in https://github.com/cockroachdb/cockroach/issues/96840 and https://github.com/cockroachdb/cockroach/issues/95764.
