### ISSUE TITLE
remove "failed" as part of the fingerprint creation

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#97176]
We should not use "failed" as part of the key for a fingerprint, so we can easily see all status for the same fingerprint together. This would also reduce the amount of different fingerprints

Jira issue: CRDB-24560

Epic: CRDB-24527

**Comment by kevin-v-ngo** [comment]
I'm going to move this to backlog for now to evaluate for 23.2 since there are broader implications (and improvements) we can consider. Related issue: https://github.com/cockroachdb/cockroach/issues/69785
