### ISSUE TITLE
storage: Set IngestAsFlushable to true by default in the Pebble Options

### ISSUE THREAD

**Issue by bananabrick** [cockroachdb/cockroach#97194]
We introduced the ability ingest sstables as a flushable in https://github.com/cockroachdb/pebble/pull/2313. Enable this by default, and add a cluster setting to turn it off in the worst case.

We need https://github.com/cockroachdb/pebble/issues/2266, and https://github.com/cockroachdb/pebble/issues/2292 done to turn it on.

Jira issue: CRDB-24567

**Comment by bananabrick** [comment]
Should be enabled by default. Do we just need a cluster setting here?

**Comment by jbowens** [comment]
We need a Cockroach cluster version to ratchet the format major version up to the point that it can be enabled, and then a cluster setting as well.
