### ISSUE TITLE
streamingestion: address cross cluster replication dbconsole nits

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#97224]
In the first viewing of the cross cluster replication db console page, I noticed a few issues.

During the initial scan:
<img width="909" alt="image" src="https://user-images.githubusercontent.com/35438895/219213828-410e694c-c620-44f0-9e0a-43048edcc50f.png">

- [ ] Replication Lag should stay at 0, until a high water mark is recorded. It was initially 0 before the job started, and i'm not sure why it bounced up to 1.75.
- [x] Logical Bytes and SST Bytes graphs have the incorrect units and should be monotonically increasing

After Initial Scan:
<img width="894" alt="image" src="https://user-images.githubusercontent.com/35438895/219216548-5ae07a18-0930-4e76-8d6c-106c050f35a1.png">

Jira issue: CRDB-24575

**Comment by msbutler** [comment]
perhaps i'm not graphing these correctly, but sst_bytes and logical_bytes do not seem to tell a consistent story even when graphed in a custom chart. The units don't make much sense to me.
<img width="911" alt="image" src="https://user-images.githubusercontent.com/35438895/219223079-aa58773d-7b3b-4035-a81b-ec1f039b40c8.png">


Though, I think there may be an actual problem with how we record sst_bytes. When I construct the same graphs in grafana, the logical bytes match the intended workload, but physical bytes do not:
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/35438895/219223346-0b48b11a-7b00-44aa-ac66-ad1481189938.png">

**Comment by msbutler** [comment]
Wow, graphs are incredible. If we indeed trust the logical bytes by node graph, check out how poorly we distributed work for the initial scan. Every node except for one finished their initial ingestion in like 10 minutes, and then one last node took almost 30 minutes!! @lidorcarmel

**Comment by adityamaru** [comment]
> The units in these graphs don't make much sense to me.

Did you try toggling the Units to Bytes when graphing the custom metrics?

**Comment by msbutler** [comment]
logical bytes and sst bytes bug and units fixed by : https://github.com/cockroachdb/cockroach/pull/97248

Replication Lag still looks off during initial scan.
