### ISSUE TITLE
Add storage iterator stats to internal telemetry data

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#97230]
This issue tracks adding observability information regarding storage iterator stats per fingerprint to internal telemetry data.

Related issue: https://github.com/cockroachdb/cockroach/pull/96016

Jira issue: CRDB-24578

**Comment by j82w** [comment]
@kevin-v-ngo are there other events this needs to be added to besides the one here? https://github.com/cockroachdb/cockroach/pull/102820

**Comment by j82w** [comment]
Confirmed done: https://github.com/cockroachdb/cockroach/pull/102820
