### ISSUE TITLE
sql: panic: `HELP LEAST`

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#9723]
Found with RSG:

https://teamcity.cockroachdb.com/viewLog.html?buildId=26766&tab=buildResultsDiv&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests#testNameId2629214155183590638

**Comment by jordanlewis** [comment]
`HELP GREATEST` also fails:

https://teamcity.cockroachdb.com/viewLog.html?buildId=26767&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests&tab=buildLog#_
