### ISSUE TITLE
bazel: cannot add dependency on `golang.org/x/exp/slices` package

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#97247]
**Describe the problem**

I tried to add a dependency on `golang.org/x/exp/slices`. Following the steps below, I cannot build because of the error:
```
ERROR: /private/var/tmp/_bazel_rafiss/9796b4657e3f3e4bab52d5a958783c22/external/org_golang_x_exp/slices/BUILD.bazel:3:11: GoCompilePkg external/org_golang_x_exp/slices/slices.a failed: (Exit 1): builder failed: error executing command bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix darwin_arm64 -tags bazel,gss,bazel,gss -src ... (remaining 21 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox
compilepkg: missing strict dependencies:
	/private/var/tmp/_bazel_rafiss/9796b4657e3f3e4bab52d5a958783c22/sandbox/darwin-sandbox/13263/execroot/com_github_cockroachdb_cockroach/external/org_golang_x_exp/slices/slices.go: import of "constraints"
No dependencies were provided.
Check that imports in Go sources match importpath attributes in deps.
Target //pkg/cmd/roachtest:roachtest failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 11.785s, Critical Path: 0.23s
INFO: 2 processes: 2 internal.
INFO: Build Event Protocol files produced successfully.
FAILED: Build did NOT complete successfully
ERROR: exit status 1
```

**To Reproduce**

Here's what I did:
1. Import `golang.org/x/exp/slices` in the file pkg/cmd/roachtest/tests/orm_helpers.go
2. Run `./dev gen bazel`
3. Run `./dev build roachtest`

**Expected behavior**
The build should work.

**Environment:**
I am working on top of commit a24b178cf9

Jira issue: CRDB-24595

**Comment by rickystewart** [comment]
@rafiss I'm pretty confused by this. At the version of `golang.org/x/exp` we have in CRDB, the [constraints sub-package](https://cs.opensource.google/go/x/exp/+/025e73f80486958a9c517ade99a38db4628f15d6:slices/slices.go) didn't exist inside of `golang.org/x/exp`. 🤷‍♂️  It does have that package as of the latest `master` though.

I think what you want to do is *upgrade* `golang.org/x/exp` to a newer version.

**Comment by rafiss** [comment]
Ah I see. It's bit weird that there's a version of `golang.org/x/exp` that has `import "constraints"`, yet does not have any `constraints` package. But I agree with you that upgrading the dependency should resolve this, so I'm fine to close this.

**Comment by rickystewart** [comment]
Feel free to re-open if there are further issues.
