### ISSUE TITLE
improve cleanup job stuck or not started

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#97255]
A few improvements for the cleanup job:
1. If the cleanup job `AUTO SQL STATS COMPACTION` get stuck, we need to add an alert to the user
2. We can check if the job has been running for a long time, and force it to stop and restart ourselves
3. Check if the job has been schedule at all and if not add back ourselves
4. Create more documentation on these scenarios

Jira issue: CRDB-24598

**Comment by kevin-v-ngo** [comment]
@maryliag, do you know the status of a 'stuck' compaction job? Here's the current list: https://www.cockroachlabs.com/docs/stable/show-jobs#job-status

**Comment by maryliag** [comment]
it shows as running, but is not actually making progress or make very little progress.

**Comment by maryliag** [comment]
it's when we see it running for several hours, because this job runs on a hourly base, so it should be completed before the next run

**Comment by kevin-v-ngo** [comment]
Okay, thanks! FYI @dongniwang

**Comment by kevin-v-ngo** [comment]
We probably need to define a threshold based on now() - Last Execution Time

**Comment by maryliag** [comment]
No longer a priority
