### ISSUE TITLE
add information from statement,transaction_sttaistics to debug.zip

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#97254]
We should add information from {statement|transaction}_statistics on debug.zip

The system tables can have a lot of data, so we can start with just the in-memory data.

Jira issue: CRDB-24597

**Comment by j82w** [comment]
The in memory results are already [collected](https://github.com/cockroachdb/cockroach/blob/142b97139aa2da78eb2b7d2ffdf6209ccae1e9cc/pkg/cli/zip_table_registry.go#L825).
