### ISSUE TITLE
storage: RHS of split does not campaign automatically

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#9727]
Run

``` go
make test PKG=./storage TESTS=DifferentLease TESTFLAGS='-v --verbosity=4'
--- PASS: TestStoreSplitTimestampCacheDifferentLeaseHolder (3.72s)
```

Apply this patch (which is a hacky and incorrect reversal of #9550):

``` diff
diff --git a/storage/store.go b/storage/store.go
index 459f38c..b970069 100644
--- a/storage/store.go
+++ b/storage/store.go
@@ -1526,6 +1526,9 @@ func splitTriggerPostCommit(
        r.mu.Lock()
        rightRng.mu.Lock()
        r.mu.tsCache.MergeInto(rightRng.mu.tsCache, true /* clear */)
+       rightRng.withRaftGroupLocked(true, func(r *raft.RawNode) (bool, error) {
+               return true, nil
+       })
        rightRng.mu.Unlock()
        r.mu.Unlock()
        log.Event(ctx, "copied timestamp cache")
```

Run it again:

```
--- PASS: TestStoreSplitTimestampCacheDifferentLeaseHolder (0.70s)
```

The eager campaigning was removed in #9550. It does seem that we require it here, and we should investigate why.

**Comment by petermattis** [comment]
There is nothing different between your first and second runs. Am I missing something?

**Comment by tschottdorf** [comment]
Sorry, copy&paste is hard. I edited the message - the second run is ~0.7s.

**Comment by petermattis** [comment]
My guess (without looking at the code) is that the test probably needs to be tweaked to poke the RHS of the split.

**Comment by petermattis** [comment]
I don't think there is anything left to do here, but need to verify that.

**Comment by spencerkimball** [comment]
@petermattis please reopen if necessary. I don't believe this is still a problem.
