### ISSUE TITLE
oidc: login button fails to appear after successful configuration

### ISSUE THREAD

**Issue by dhartunian** [cockroachdb/cockroach#97298]
After successful set up of OIDC in version `22.2.1` the login button fails to appear in DB Console.

The message `initialized OIDC server` appears in the logs and `/oidc/v1/login` endpoints works but the button does not appear.

Jira issue: CRDB-24621

**Comment by umi0410** [comment]
I don't think `server.oidc_authentication.autologin` is working either.

* `server.oidc_authentication.autologin=true`, but no redirect.
* `server.oidc_authentication.autologin=false`, but no OIDC login button.

**Comment by dhartunian** [comment]
@umi0410 I was able to reproduce this on `22.2.1` this was fixed in `22.2.2` via https://github.com/cockroachdb/cockroach/pull/94067
Please upgrade to any version after `22.2.1`.
