### ISSUE TITLE
sql: SHOW GRANTS inherited by virtue of role membership

### ISSUE THREAD

**Issue by fabiog1901** [cockroachdb/cockroach#97299]
`SHOW GRANTS` currently only lists explicitly granted privileges. This FR is to extend the list to privileges inherited by role membership. Example below:

Starting point:

```sql
create database d1;
create role r1;
create user u1;
grant r1 to u1;
use d1;
create table t1 (id int);
grant all on table t1 to r1;
show grants on t1 for r1;
--   database_name | schema_name | table_name | grantee | privilege_type | is_grantable
-- ----------------+-------------+------------+---------+----------------+---------------
--   d1            | public      | t1         | r1      | ALL            |      f
-- (1 row)
```

Currently, it shows no grants for u1:

```sql
show grants on t1 for u1;
-- SHOW GRANTS 0
```

Envisioned - see last column so you have that extra info

```sql
show grants on t1 for u1;
--   database_name | schema_name | table_name | grantee | privilege_type | is_grantable   | from_role
-- ----------------+-------------+------------+---------+----------------+----------------------------
--   d1            | public      | t1         | r1      | ALL            |      f         |    r1
-- (1 row)
```

[Slack](https://cockroachlabs.slack.com/archives/CHVV403F0/p1676651603690829)

Jira issue: CRDB-24622

gz#16111

Epic CRDB-27601

**Comment by rafiss** [comment]
I think if we made the change, the `grantee` column might be sufficient, so there's no need to add the `from_role` column. `grantee` would show the role that was explicitly granted that privilege.
