### ISSUE TITLE
Can't create changefeed for column family with options in Intellij

### ISSUE THREAD

**Issue by NicholasPurdy** [cockroachdb/cockroach#97328]
**Describe the problem**

Intellij only partially supports the crdb sql dialect. Changefeeds for column families seems to be one of the areas it is lacking in.

**To Reproduce**

Try to create this in a sql editor in Intellij.

```sql
CREATE CHANGEFEED FOR
TABLE defaultdb.business.domains
FAMILY mutable_fam
INTO 'webhook-https://example.ngrok.io/v1/domains?insecure_tls_skip_verify=true'
WITH
    diff,
    on_error = 'pause',
    protect_data_from_gc_on_pause,
    initial_scan = 'no',
    webhook_auth_header = 'Basic abcabcabcabc',
    webhook_client_timeout = '5s';
```

**Expected behavior**

The changefeed is created with options included.

**Actual behavior**

Intellij doesn't expect `WITH` so options are not included when the changefeed is created. The following error is shown `[42601] ERROR: at or near ",": syntax error`. It is referring to `WITH diff,`;

**Environment:**
 - CockroachDB: serverless
 - OS: mac, m1 chip
 - Client app: intellij latest version

**Additional context**

Slack convo: 
https://cockroachdb.slack.com/archives/CP4D9LD5F/p1676691622108789

**Workaround**

I used the ccloud cli to create it just fine.

Jira issue: CRDB-24673

**Comment by xinhaoz** [comment]
Wasn't sure on this one but I tagged @cockroachdb/sql-sessions to triage. Feel free to close if it's not an issue in our domain.

**Comment by rafiss** [comment]
@NicholasPurdy Thanks for reaching out. I think you should report this issue to the JetBrains team, since they are the developers of Intellij and can add support for this syntax. Their issue tracker is here: https://youtrack.jetbrains.com/issues/IDEA

**Comment by NicholasPurdy** [comment]
Made a ticket on their end: https://youtrack.jetbrains.com/issue/IDEA-313961/Cant-create-cockroachdb-changefeed-for-column-family-with-options-in-Intellij

Feel free to close this I guess.
