### ISSUE TITLE
server: restarting servers with a smaller COCKROACH_MAX_OFFSET is incorrect

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#9733]
Changing `COCKROACH_MAX_OFFSET` between restarts is not kosher - it can lead to read-your-own-writes violations and other anomalies.
On server startup, we sleep `MaxOffset` to make sure we don't start with a lower clock than we ended the last server incarnation with (see #9504). But this mechanism relies on the current value of `MaxOffset`. If it's different than it was previously, all bets are off.

One way to address this is to save the previous value locally and sleep based on that.

Jira issue: CRDB-6148

**Comment by tamird** [comment]
Do we actually sleep? Not until https://github.com/cockroachdb/cockroach/pull/9504/commits/bc8d269e381525f0b080203e2622116f11a0989d goes in, right?

**Comment by tschottdorf** [comment]
Yes, sleeping is only introduced in #9504.

**Comment by petermattis** [comment]
@andreimatei Is there anything left to do here?

**Comment by andreimatei** [comment]
The issue is as valid as ever. But it doesn't seem to be the most important thing in the world to me.

**Comment by knz** [comment]
moving this into server backlog.

I suggest to change the work definition to "Explain the risk in the documentation for the max offset env var and the flag". I'll iterate on this with @taroface .
