### ISSUE TITLE
storage: TestRebalance_3To5Small has leaderless ranges

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#9736]
repro:

```
build/builder.sh make build && make test \
  TESTTIMEOUT=48h \
  PKG=./acceptance \
  TESTS=Rebalance_3To5Small \
  TESTFLAGS='-v -remote -key-name google_compute_engine -cwd terraform -tf.keep-cluster=failed -tf.cockroach-binary=../../cockroach'
```

The leader-less ranges are evident when visiting `/raft/ranges`. 
<img width="691" alt="screenshot 2016-10-04 17 09 58" src="https://cloud.githubusercontent.com/assets/1564582/19092598/6a523ca8-8a55-11e6-8623-0d5f34cb8430.png">

This leaderless state persists for >25 minutes, which encompasses two `replicaScanner` cycles. Anywhere from 7-30 ranges (of 262) have no leaders even after rebalancing has finished.

**Comment by cuongdo** [comment]
More notes:
* Running `block_writer` results in all ranges having leaders, because it quickly touches all ranges.
* The first pass of the the `replicaScanner` finds no rebalance targets, because nodes 4 and 5 come up 3-5 minutes after nodes 1-3. So, that first pass of the `replicaScanner` sees a perfectly balanced 3-node cluster.
* `(*replicaScanner).paceInterval()` is returning a wait interval of 3.3 s. Based on quick calculations, this should be much shorter (0.75s).

I'm investigating that last point further with some more log statements.

**Comment by petermattis** [comment]
Does the large number of dormant ranges happen on every run?

**Comment by cuongdo** [comment]
Yes

**Comment by cuongdo** [comment]
Though it's a different number with each run.

**Comment by tschottdorf** [comment]
So the dormant ranges go away with block writer? If there's no load on them, it seems reasonable that some ranges would be quiesced. If the queues don't touch quiesced ranges, is there any mystery left (the scanner should wake up the replica if it last held the leader lease)?

**Comment by petermattis** [comment]
Quiesced ranges have a leader.

**Comment by tschottdorf** [comment]
I don't know if I agree with that statement (the lease could expire, which is what I considered above), but you're right that the queue would try to obtain a leader lease (thus unquiescing).

You can `curl host:8080/debug/vmodule/replicate_queue=5,queue=5` which should give you all the verbose logging.

**Comment by tschottdorf** [comment]
(That of course and tracing. You could set a lightstep_token or try to see something in net/trace, and the /debug/events endpoints)

**Comment by cuongdo** [comment]
This looks to be the sequence of events:

1. Cluster comes up with 3 nodes.
2. `(*replicateQueue).shouldQueue()` called and sees a perfectly balanced cluster of 3 nodes. So, it returns `false`, because  there are no suitable rebalance targets.
3. 2 additional nodes come up.
4. During the next pass of `replicaScanner`, the replicas are balanced, so `shouldQueue` returns `false` again.

It looks like we only request a lease when issuing a Raft command. Because there are no required allocation changes for some ranges, we never need to request a lease for those ranges.

Because we never issue a single Raft command for some ranges during this test, is it expected that those same ranges have no Raft leader? (This doesn't seem to be an issue in practice as far as I can tell.)

**Comment by petermattis** [comment]
Ah, this makes sense. I had forgotten than `replicateQueue.shouldQueue` doesn't acquire the lease, but assumes the current store is the lease holder if there is no lease. So if no rebalancing for a range is necessary, we won't wake it up. I think there is nothing to do here.

**Comment by cuongdo** [comment]
Great. I'll put out a PR with the extra logging I used to understand this, because I think it'll be more broadly useful.
