### ISSUE TITLE
Composite primary key/auto-increment column

### ISSUE THREAD

**Issue by lancel66** [cockroachdb/cockroach#97393]
**Is your feature request related to a problem? Please describe.**
Use a sequence to get uniqueness similar to how the `now()` function is used in a primary key

**Describe the solution you'd like**
A composite primary key / auto-increment column where the right-most column autoincrements:

```
owner      what       autoincrement id 
alessandro experiment   1     
alessandro experiment   2     
alessandro experiment   3     
alessandro note         1     
alessandro experiment   4     
alessandro note         2     
alessandro note         3     
```

Jira issue: CRDB-24676

**Comment by ajwerner** [comment]
Can you help me better understand the ask?

For example, you can do this:

```sql
CREATE TABLE t (
    owner            STRING,
    what             STRING,
    autoincrement_id INT8
                     DEFAULT (unique_rowid())
                     NOT VISIBLE,
    PRIMARY KEY (owner, what, autoincrement_id)
);

INSERT
  INTO t
VALUES ('alessandro', 'experiment'),
       ('alessandro', 'experiment'),
       ('alessandro', 'note');
```

```sql
> SELECT * FROM t;                                                                                                                                                                                                                                  
    owner    |    what
-------------+-------------
  alessandro | experiment
  alessandro | experiment
  alessandro | note
```

```sql
> SELECT *, autoincrement_id FROM t;                                                                                                                                                                                                                
    owner    |    what    |  autoincrement_id
-------------+------------+---------------------
  alessandro | experiment | 843871210122313729
  alessandro | experiment | 843871210122379265
  alessandro | note       | 843871210122412033
```

You can use sequences or whatever for the third column.

**Comment by ajwerner** [comment]
I'm inclined to close this as an issue in the tracker.

**Comment by ale-dd** [comment]
The autoincrement ID would have provided the equivalent of a:

```
RANK() OVER (
    PARTITION BY owner, what
    ORDER BY created_at ASC
)
```

even in absence of a `created_at`.

For single row inserts it's relatively easy to achieve the same via a CTE, but it would be very neat to have a handy shorthand for that, such that users would be able to just define it as a default value for the column in the table schema.

**Comment by ajwerner** [comment]
I don't think I understand this last comment (and I'm not sure I understood the initial issue). Can you be more concrete about what you're asking for and what today does not work?
