### ISSUE TITLE
sql: add insights to statement, transaction statistics

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/cockroach#97403]
We should add insights to our existing statement and transaction statistics infrastructure, for the following reasons:

1. **Persistence**
  Statement and transaction statistics are periodically flushed to on-disk `system` tables. Adding insights information to these tables would extend [the benefits of persisted statistics](https://github.com/Azhng/cockroach/blob/rfc-stats-persistence/docs/RFCS/20210330_sql_stats_persistence.md#summary) to insights, and it would enable us to provide insights on workloads into tenant/serverless clusters over a much more meaningful time interval (the in-memory tables on serverless clusters can be wiped in as few as 15 minutes).
2. **Performance**
  We want to add Insights information to other pages on the Console (namely, [the SQL Activity pages](https://github.com/cockroachdb/cockroach/issues/83780)), and we want users to be able to navigate from Insights pages to other pages and vice versa. Adding insights to statement and transaction statistics tables would enable us to move some computation server-side and limit network request count for pages/workflows that require both fingerprint statistics and detected insights.

Jira issue: CRDB-24683

**Comment by maryliag** [comment]
No longer a priority
