### ISSUE TITLE
opt: subquery hoisting doesn't respect volatility

### ISSUE THREAD

**Issue by DrewKimball** [cockroachdb/cockroach#97432]
It is possible to hoist a leak-proof subquery from a CASE statement into an apply-join without changing the behavior of a query. The subquery-hoisting logic checks that the subquery is leakproof when deciding whether to fire the rule; however, once the rule is triggered, all correlated subqueries in the scalar expression are hoisted regardless of volatility. This means a non-leak-proof subquery can be hoisted if in the same scalar expression as a hoistable subquery. Example:
```
CREATE TABLE xy (x INT, y INT);
CREATE TABLE ab (a INT, b INT);

root@localhost:26257/defaultdb> EXPLAIN (OPT) SELECT CASE WHEN x IS NULL 
  THEN (SELECT a FROM ab WHERE b = y LIMIT 1) --Hoistable
  ELSE (SELECT (x/0)::INT FROM ab LIMIT 1) END --Not Hoistable
FROM xy;
                         info
------------------------------------------------------
  project
   ├── left-join-apply
   │    ├── distinct-on
   │    │    ├── left-join (hash)
   │    │    │    ├── scan xy
   │    │    │    ├── scan ab
   │    │    │    └── filters
   │    │    │         └── b = y
   │    │    └── aggregations
   │    │         ├── const-agg
   │    │         │    └── x
   │    │         └── first-agg
   │    │              └── a
   │    ├── project
   │    │    ├── scan ab
   │    │    │    └── limit: 1
   │    │    └── projections
   │    │         └── (x / 0)::INT8
   │    └── filters (true)
   └── projections
        └── CASE WHEN x IS NULL THEN a ELSE int8 END
(21 rows)

Time: 3ms total (execution 3ms / network 1ms)
```
Note that the first subquery in this example is considered leakproof despite the presence of a scan - that might be another bug.

Jira issue: CRDB-24693

Epic: CRDB-31585

**Comment by mgartner** [comment]
Good find, this does appear to be a problem. Here's an example that causes a division by zero error in CRDB v23.1.5, but returns `NULL` in Postgres:

```sql
CREATE TABLE xy (x INT, y INT);
CREATE TABLE ab (a INT, b INT);

INSERT INTO xy VALUES (NULL, 1);
INSERT INTO ab VALUES (1, 1);

SELECT CASE WHEN x IS NULL 
  THEN (SELECT a FROM ab WHERE b = y LIMIT 1) --Hoistable
  ELSE (SELECT (y/0)::INT FROM ab LIMIT 1) END --Not Hoistable
FROM xy;
```

**Comment by mgartner** [comment]
This is a bug in older versions too. I'm going to remove the release blocker label for now.
