### ISSUE TITLE
ORDER BY clause misfunctions on an overflowed integer.

### ISSUE THREAD

**Issue by sayJason** [cockroachdb/cockroach#97446]
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**
I start CockroachDB v22.2.0 by command `./cockroach start-single-node --certs-dir=certs --host=localhost --http-host=localhost`.

I try to run the following statements, in which the ORDER BY clause of the SELECT statement misfunctions on an overflowed integer. Moreover, when checking its query plan, I do not find any operator related to the ORDER BY.
```SQL
CREATE TABLE t1 (c1 INT);
INSERT INTO t1 VALUES (1);

SELECT t1.c1 FROM t1 ORDER BY ((CASE WHEN TRUE THEN ((398122825)*(2097698916)*(1229381391)) ELSE 1 END)) DESC; -- expect to see an error for integer overflow
EXPLAIN SELECT t1.c1 FROM t1 ORDER BY ((CASE WHEN TRUE THEN ((398122825)*(2097698916)*(1229381391)) ELSE 1 END)) DESC;
         info
-----------------------
  distribution: local
  vectorized: true

  • scan
    missing stats
    table: t1@t1_pkey
    spans: FULL SCAN
```

If I change the above SELECT statement by replace CASE WHEN branch TRUE to another TRUE clause, e.g, `(t1.c1) BETWEEN SYMMETRIC (t1.c1) AND (t1.c1)`. The SELECT statement returns an error.
```SQL
SELECT t1.c1 FROM t1 ORDER BY ((CASE WHEN (t1.c1) BETWEEN SYMMETRIC (t1.c1) AND (t1.c1) THEN ((398122825)*(2097698916)*(1229381391)) ELSE 1 END)) DESC; -- [22003] ERROR: integer out of range
EXPLAIN SELECT t1.c1 FROM t1 ORDER BY ((CASE WHEN (t1.c1) BETWEEN SYMMETRIC (t1.c1) AND (t1.c1) THEN ((398122825)*(2097698916)*(1229381391)) ELSE 1 END)) DESC;
             info
-------------------------------
  distribution: local
  vectorized: true

  • sort
  │ order: -column5
  │
  └── • render
      │
      └── • scan
            missing stats
            table: t1@t1_pkey
            spans: FULL SCAN
```

**Expected behavior**
The first SELECT statement should also return an error.

**Environment:**
 - CockroachDB version v22.2.0
 - Server OS: Ubuntu 22.04 LTS
 - Client app CockroachDB sql

Jira issue: CRDB-24700

**Comment by mgartner** [comment]
Thanks for the report!

This is actually acceptable behavior because of two things:

1. Ordering by a constant is a no-op. Notice how there is no sorting operator in the query plan below:

```
defaultdb> CREATE TABLE ab (a INT, b INT);
CREATE TABLE

defaultdb> EXPLAIN SELECT * FROM ab ORDER BY 5-2;
         info
-----------------------
  distribution: local
  vectorized: true

  • scan
    missing stats
    table: ab@ab_pkey
    spans: FULL SCAN
(7 rows)
```

2. The optimizer is free to completely drop sub-expressions of queries if they do not change the semantic meaning of the query (there are _very_ few exceptions to this). As a related example, notice that the query below does not result in an integer overflow because the conjunction short-circuits:

```
defaultdb> SELECT false AND 835141818437357700 * 1229381391 > 0;
  ?column?
------------
     f
(1 row)
```

I'm going to close this as the behavior is expected. Thanks again for the detailed report!
