### ISSUE TITLE
data race on (*PersistedSQLStats).Flush()

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#97488]
=== RUN   TestSQLStatsPersistedLimitReached
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/9a30d5271a65be6b3f2aa1433be9011f/logTestSQLStatsPersistedLimitReached2414865191
    test_log_scope.go:79: use -show-logs to present logs inline

==================
WARNING: DATA RACE
Read at 0x00c002e6f908 by goroutine 84469:
  github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats.(*PersistedSQLStats).Flush()
      github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats/pkg/sql/sqlstats/persistedsqlstats/flush.go:39 +0x24d
  pkg/sql/sqlstats/persistedsqlstats/persistedsqlstats_test_test.TestSQLStatsPersistedLimitReached()
      pkg/sql/sqlstats/persistedsqlstats/persistedsqlstats_test_test/pkg/sql/sqlstats/persistedsqlstats/flush_test.go:506 +0x72c
  github.com/cockroachdb/cockroach/pkg/server.(*Server).PreStart()
      github.com/cockroachdb/cockroach/pkg/server/server.go:1823 +0x505c
  github.com/cockroachdb/cockroach/pkg/server.(*Server).Start()
      github.com/cockroachdb/cockroach/pkg/server/server.go:1235 +0x44
  github.com/cockroachdb/cockroach/pkg/server.(*TestServer).Start()
      github.com/cockroachdb/cockroach/pkg/server/testserver.go:601 +0x6c
  github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartServer()
      github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_server_shim.go:318 +0x1b1
  pkg/sql/sqlstats/persistedsqlstats/persistedsqlstats_test_test.TestSQLStatsPersistedLimitReached()
      pkg/sql/sqlstats/persistedsqlstats/persistedsqlstats_test_test/pkg/sql/sqlstats/persistedsqlstats/flush_test.go:469 +0x425
  testing.tRunner()
      GOROOT/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      GOROOT/src/testing/testing.go:1493 +0x47
Previous write at 0x00c002e6f908 by goroutine 84918:
  github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats.(*PersistedSQLStats).Flush()
      github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats/pkg/sql/sqlstats/persistedsqlstats/flush.go:68 +0x386
  github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats.(*PersistedSQLStats).startSQLStatsFlushLoop.func1()
      github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats/pkg/sql/sqlstats/persistedsqlstats/provider.go:149 +0x3f1
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470 +0x1f6
Goroutine 84469 (running) created at:
  testing.(*T).Run()
      GOROOT/src/testing/testing.go:1493 +0x75d
  testing.runTests.func1()
      GOROOT/src/testing/testing.go:1846 +0x99
  testing.tRunner()
      GOROOT/src/testing/testing.go:1446 +0x216
  testing.runTests()
      GOROOT/src/testing/testing.go:1844 +0x7ec
  testing.(*M).Run()
      GOROOT/src/testing/testing.go:1726 +0xa84
  pkg/sql/sqlstats/persistedsqlstats/persistedsqlstats_test_test.TestMain()
      pkg/sql/sqlstats/persistedsqlstats/persistedsqlstats_test_test/pkg/sql/sqlstats/persistedsqlstats/main_test.go:28 +0x186
  main.main()
      main/bazel-out/k8-fastbuild/bin/pkg/sql/sqlstats/persistedsqlstats/persistedsqlstats_test_/testmain.go:139 +0x748
Goroutine 84918 (running) created at:
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:461 +0x619
  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask()
      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:332 +0x150
  github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats.(*PersistedSQLStats).startSQLStatsFlushLoop()
      github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats/pkg/sql/sqlstats/persistedsqlstats/provider.go:115 +0x26
  github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats.(*PersistedSQLStats).Start()
      github.com/cockroachdb/cockroach/pkg/sql/sqlstats/persistedsqlstats/pkg/sql/sqlstats/persistedsqlstats/provider.go:102 +0x53
  github.com/cockroachdb/cockroach/pkg/sql.(*Server).Start()
      github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:559 +0xc9
  github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).Start()
      github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:377 +0xfcf
  github.com/cockroachdb/cockroach/pkg/server.(*SQLServer).preStart()
      github.com/cockroachdb/cockroach/pkg/server/server_sql.go:1446 +0xf65
  github.com/cockroachdb/cockroach/pkg/sql.GetLocalityRegionEnumPhysicalRepresentation()
      github.com/cockroachdb/cockroach/pkg/sql/region_util.go:1481 +0x21b
  github.com/cockroachdb/cockroach/pkg/server.(*SQLServer).preStart()
      github.com/cockroachdb/cockroach/pkg/server/server_sql.go:1367 +0x193
  github.com/cockroachdb/cockroach/pkg/server.(*Server).PreStart()
      github.com/cockroachdb/cockroach/pkg/server/server.go:1881 +0x5684
  github.com/cockroachdb/cockroach/pkg/server.(*Node).writeNodeStatus()
      github.com/cockroachdb/cockroach/pkg/server/node.go:1020 +0xf7
  github.com/cockroachdb/cockroach/pkg/server.(*Node).startWriteNodeStatus()
      github.com/cockroachdb/cockroach/pkg/server/node.go:980 +0xae
  github.com/cockroachdb/cockroach/pkg/server.(*Server).PreStart()
      github.com/cockroachdb/cockroach/pkg/server/server.go:1823 +0x505c
  github.com/cockroachdb/cockroach/pkg/server.(*Server).Start()
      github.com/cockroachdb/cockroach/pkg/server/server.go:1235 +0x44
  github.com/cockroachdb/cockroach/pkg/server.(*TestServer).Start()
      github.com/cockroachdb/cockroach/pkg/server/testserver.go:601 +0x6c
  github.com/cockroachdb/cockroach/pkg/testutils/serverutils.StartServer()
      github.com/cockroachdb/cockroach/pkg/testutils/serverutils/test_server_shim.go:318 +0x1b1
  pkg/sql/sqlstats/persistedsqlstats/persistedsqlstats_test_test.TestSQLStatsPersistedLimitReached()
      pkg/sql/sqlstats/persistedsqlstats/persistedsqlstats_test_test/pkg/sql/sqlstats/persistedsqlstats/flush_test.go:469 +0x425
  testing.tRunner()
      GOROOT/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      GOROOT/src/testing/testing.go:1493 +0x47

Jira issue: CRDB-24724

**Comment by rafiss** [comment]
closed by https://github.com/cockroachdb/cockroach/pull/105917
