### ISSUE TITLE
stability: significant performance regression

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#9748]
Against current master (ae0f8048df8fb5e1558c2aa7d7d5e6443b73f2b6):

```
~ rm -fr cockroach-data && ./cockroach start &
~ block_writer -duration 5m
...
300.0s: 1269214 total 4230.7/sec
```

From a commit last Friday (42dd2be5ad36b050fab559a3c2335df1a9ba5a76):

```
~ rm -fr cockroach-data && ./cockroach start &
~ block_writer -duration 5m
...
 300.0s: 1471876 total 4906.2/sec
```

Can someone bisect to find the commit that caused this drop?

Cc @cockroachdb/stability

**Comment by petermattis** [comment]
3039f8b1bd85bb9d8c6a59f68fdb0580bcc4b310 looks like the culprit. Cc @RaduBerinde.

**Comment by petermattis** [comment]
Looks like one of the upstream changes in `basictracer-go` is to blame.

**Comment by petermattis** [comment]
This is the problematic upstream commit https://github.com/opentracing/basictracer-go/commit/68b3b80e7d64641599f53e89023e276fbb9d9e91. I'm also seeing a performance hit from setting [`maxLogsPerSpan`](https://github.com/cockroachdb/cockroach/blob/master/util/tracing/tracer.go#L40) to 1000. 

Cc @tschottdorf.

**Comment by RaduBerinde** [comment]
@tschottdorf : it's kind of annoying that we have to go to `basictracer-go` for any changes to the `NetTraceIntegrator`.. It's good that we contributed it but we could use our own local copy.. What do you think?

> I'm also seeing a performance hit from setting maxLogsPerSpan to 1000.

Can you expand on this? It is faster if we don't set `MaxLogsPerSpan`? (in basictracer or lightstep?) 

FWIW, the defaults are `100` in basictracer (this value shouldn't matter except for snowball traces) and 500 in lightstep. Before these recent changes there were no limits. These are all separate from the limit in `NetTraceIntegrator`.

**Comment by tschottdorf** [comment]
Yeah, I agree that it would be better to own (a copy of) it.

That performance hit is fairly drastic. @petermattis, did you run one by any chance that had tracing "disabled" (i.e. basictracer, but without `NetTraceIntegrator`)?

**Comment by RaduBerinde** [comment]
I'm also curious what spans actually have more than a few tens of events.. Maybe repeated retries?

**Comment by petermattis** [comment]
@RaduBerinde My comment regarding `MaxLogsPerSpan` was changing our default from `1000` to `100`.

@tschottdorf Disabling `NetTraceIntegrator` completely gives the fastest runs. I was going to send a PR demonstrating this, but I can't `git push` from the plane right now, so here it is inline:

```
commit 0519c0c9d6b91e27e8430151839bb8efad2ecb15
Author: Peter Mattis <petermattis@gmail.com>
Date:   Wed Oct 5 10:35:35 2016 -0400

    [DO NOT MERGE] util/tracing: disable NetTraceIntegrator

    Before:

      ~ rm -fr cockroach-data && ./cockroach start &
      ~ block_writer -duration 1m
      ...
      60.0s: 253955 total 4232.2/sec

    After:

      ~ rm -fr cockroach-data && ./cockroach start &
      ~ block_writer -duration 1m
      ...
      60.0s: 312582 total 5209.6/sec

    See #9748

diff --git a/util/tracing/tracer.go b/util/tracing/tracer.go
index f90e398..4b4bc1a 100644
--- a/util/tracing/tracer.go
+++ b/util/tracing/tracer.go
@@ -27,7 +27,6 @@ import (
        "github.com/cockroachdb/cockroach/util/envutil"
        "github.com/lightstep/lightstep-tracer-go"
        basictracer "github.com/opentracing/basictracer-go"
-       "github.com/opentracing/basictracer-go/events"
        opentracing "github.com/opentracing/opentracing-go"
        "github.com/opentracing/opentracing-go/ext"
        otlog "github.com/opentracing/opentracing-go/log"
@@ -146,7 +145,7 @@ func basictracerOptions(recorder func(basictracer.RawSpan)) basictracer.Options
        opts := basictracer.DefaultOptions()
        opts.ShouldSample = func(traceID uint64) bool { return false }
        opts.TrimUnsampledSpans = true
-       opts.NewSpanEventListener = events.NetTraceIntegrator
+       // opts.NewSpanEventListener = events.NetTraceIntegrator
        opts.DebugAssertUseAfterFinish = true // provoke crash on use-after-Finish
        if recorder == nil {
                opts.Recorder = CallbackRecorder(func(_ basictracer.RawSpan) {})
```

**Comment by tschottdorf** [comment]
That's significant. I hadn't anticipated that net/trace would have such an impact.

@RaduBerinde easy to check. Mind taking a look?

**Comment by RaduBerinde** [comment]
One more question - is lightstep enabled in these runs?

**Comment by tschottdorf** [comment]
No.

**Comment by petermattis** [comment]
No, lightstep is not enabled.

**Comment by petermattis** [comment]
Agreed that the impact of `NetTraceIntegrator` is larger than I expected. Leaving the default max-events to trace (10) reduces the impact significantly, but does not eliminate it. Would be nice to get to the bottom of why holding on to the events causes such a large impact. Additional GC pressure? That just doesn't mesh with my mental model.

**Comment by RaduBerinde** [comment]
I will investigate.

I am still confused why changing `MaxLogsPerSpan` would make a difference.. It should only matter for snwoball tracing and lightstep.

**Comment by petermattis** [comment]
Well, `block_writer` numbers aren't completely stable. Perhaps changing `MaxLogsPerSpan` didn't have an effect and I just had an unlucky run. I can do a few more runs to verify.

**Comment by RaduBerinde** [comment]
No worries, I will take a look and do some profiling anyway later today).

I think the reallocation of the `net/trace` internal `events` slice may account for at least part of this. There would be a few ways to optimize it but that code is out of our hands unless we make our internal "fork"

**Comment by petermattis** [comment]
@RaduBerinde We could always send a patch upstream to `net/trace`.

Re: `MaxLogsPerSpan`. Definitely not a problem. We're never hitting that code path in the `block_writer` runs.

**Comment by RaduBerinde** [comment]
Ah, I thought this was part of Go's standard library. Yeah we could definitely fix upstream.

I looked at their code some more, and once we reach the max # of events, every time we add another event, half of the slice is shifted over (because we discard events from the middle). This is pretty dumb and shouldn't be too hard to fix (I did a similar change in `basictracer` and just used half of the slice as a circular buffer).

**Comment by petermattis** [comment]
Heh, so the larger the number of events buffered, the more expensive that shifting is. Ouch. Yeah, I bet they would appreciate an upstream patch to fix that. Happy to verify it addresses the perf problem I'm seeing when you have it ready.

**Comment by RaduBerinde** [comment]
Still though, is it expected to have a lot of spans with 1000+ events? Maybe we are being too verbose somewhere.

**Comment by petermattis** [comment]
> Still though, is it expected to have a lot of spans with 1000+ events? Maybe we are being too verbose somewhere.

Agreed. It's worth pulling on that thread as well.

**Comment by petermattis** [comment]
> Agreed. It's worth pulling on that thread as well.

PS I'll track this down. Easy enough for me to add some instrumentation to see where this is happening.

**Comment by RaduBerinde** [comment]
Could verify this is the culprit by modifying this line in `net/trace/trace.go`:

```go
759     // Discard the middle events.                                                                                 
760     di := int((cap(tr.events) - 1) / 2)
```
Replace to something close to the end of the slice, e.g. `di := int(cap(tr.events) - 2)`

**Comment by petermattis** [comment]
Unless I messed something up in my instrumentation, we don't ever seem to be discarding events.

**Comment by RaduBerinde** [comment]
Ok, then that's not it, sorry. I will do some profiling today.

**Comment by petermattis** [comment]
Who, `SetMaxEvents` is taking a huge chunk of time:

```
ROUTINE ======================== golang.org/x/net/trace.(*trace).SetMaxEvents in /Users/pmattis/Development/go/src/golang.org/x/net/trace/trace.go
      10ms      8.81s (flat, cum)  6.23% of Total
         .          .    801:}
         .          .    802:
         .          .    803:func (tr *trace) SetMaxEvents(m int) {
         .          .    804:	// Always keep at least three events: first, discarded count, last.
         .          .    805:	if len(tr.events) == 0 && m > 3 {
      10ms      8.81s    806:		tr.events = make([]event, 0, m)
         .          .    807:	}
         .          .    808:}
         .          .    809:
         .          .    810:func (tr *trace) ref() {
         .          .    811:	atomic.AddInt32(&tr.refs, 1)
```

The corresponding line in `trace.New` when `tr.events` is initialized:

```
         .          .    330:// New returns a new Trace with the specified family and title.
         .          .    331:func New(family, title string) Trace {
         .       30ms    332:	tr := newTrace()
         .          .    333:	tr.ref()
         .          .    334:	tr.Family, tr.Title = family, title
         .          .    335:	tr.Start = time.Now()
         .       60ms    336:	tr.events = make([]event, 0, maxEventsPerTrace)
```

**Comment by RaduBerinde** [comment]
Oh, yeah, it's allocating (and presumably zeroing out) the entire slice upfront.. I will work on the upstream fix and contribute some benchmarks as well.

I will also do a quick change to use our own `NetTraceIntegrator` and reduce the value there for now (to fix the regression).

**Comment by petermattis** [comment]
This patch seems to alleviate the majority of the perf impact:

```diff
diff --git a/trace/trace.go b/trace/trace.go
index 182499a..5e4cde3 100644
--- a/trace/trace.go
+++ b/trace/trace.go
@@ -333,7 +333,7 @@ func New(family, title string) Trace {
        tr.ref()
        tr.Family, tr.Title = family, title
        tr.Start = time.Now()
-       tr.events = make([]event, 0, maxEventsPerTrace)
+       tr.maxEvents = maxEventsPerTrace

        activeMu.RLock()
        s := activeTraces[tr.Family]
@@ -692,8 +692,9 @@ type trace struct {
        IsError bool

        // Append-only sequence of events (modulo discards).
-       mu     sync.RWMutex
-       events []event
+       mu        sync.RWMutex
+       events    []event
+       maxEvents int

        refs     int32 // how many buckets this is in
        recycler func(interface{})
@@ -753,6 +754,18 @@ func (tr *trace) addEvent(x interface{}, recyclable, sensitive bool) {
        e := event{When: time.Now(), What: x, Recyclable: recyclable, Sensitive: sensitive}
        tr.mu.Lock()
        e.Elapsed, e.NewDay = tr.delta(e.When)
+       if len(tr.events) == cap(tr.events) && cap(tr.events) < tr.maxEvents {
+               n := cap(tr.events) * 2
+               if n == 0 {
+                       n = maxEventsPerTrace
+               }
+               if n > tr.maxEvents {
+                       n = tr.maxEvents
+               }
+               newEvents := make([]event, 0, n)
+               copy(newEvents, tr.events)
+               tr.events = newEvents
+       }
        if len(tr.events) < cap(tr.events) {
                tr.events = append(tr.events, e)
        } else {
@@ -803,7 +816,7 @@ func (tr *trace) SetTraceInfo(traceID, spanID uint64) {
 func (tr *trace) SetMaxEvents(m int) {
        // Always keep at least three events: first, discarded count, last.
        if len(tr.events) == 0 && m > 3 {
-               tr.events = make([]event, 0, m)
+               tr.maxEvents = m
        }
 }
```

```
~ block_writer -duration 1m
...
  60.0s: 305293 total 5088.1/sec
```

That's very surprising.

**Comment by RaduBerinde** [comment]
Can you verify #9753 addresses the regression while I get an upstream fix in? (which is usually a painful and slow process)

**Comment by petermattis** [comment]
Per my comment on #9753, if we want to completely remove the regression, #9753 should avoid calling `SetMaxEvents` at all.

**Comment by RaduBerinde** [comment]
https://go-review.googlesource.com/#/c/30374/
