### ISSUE TITLE
Use non root user as default for tests

### ISSUE THREAD

**Issue by rimadeodhar** [cockroachdb/cockroach#97535]
Currently, we end up defaulting to using root user while running logictests and the [default test cluster settings](https://github.com/cockroachdb/cockroach/blob/87e6f4e616fd8113910f643b298bb51d0d6dbb67/pkg/base/config.go#L403). We should switch to using non root user to allow for testing codepaths that are enforced for non root users (for e.g. system.privileges checks etc.).

This request comes from discussion during [this postmortem](https://cockroachlabs.atlassian.net/wiki/x/MgARrg).

Tests to consider:
- logic tests
- unit tests that use the in-memory TestServer
- roachtests

Jira issue: CRDB-24743

**Comment by rafiss** [comment]
Closing since we aren't able to prioritize this large change. Instead we'll rely on https://github.com/cockroachdb/cockroach/issues/63145 being completed for roactests, and when we write other new tests, we'll decide to use non-root users on a case-by-case basis.
