### ISSUE TITLE
sql: more specific error message when there are too many overloads

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#9754]
If there is more than one overload eligible for selection even after all the heuristics have attempted to unambiguously pick one, the current error message suggests that there is no such method, which is slightly misleading when in fact there are actually _too many_ such methods.

**Comment by dt** [comment]
@eisenstatdavid assigned you since @knz said you might be interested but feel free to unassign if not.

**Comment by knz** [comment]
This will be addressed when #13031 merges.
