### ISSUE TITLE
sql: decimal POW function hangs on negative exponents

### ISSUE THREAD

**Issue by eisenstatdavid** [cockroachdb/cockroach#9756]
Running

```
cockroach sql <<EOF
CREATE DATABASE IF NOT EXISTS Foo;
CREATE TABLE IF NOT EXISTS Foo.Bar (b FLOAT NOT NULL);
SELECT b FROM Foo.Bar WHERE b < POW(2.0, -37);
SELECT b FROM Foo.Bar WHERE b < POW(2.0, -38);
EOF
```

will cause CRDB to hang using 100% CPU on the second `SELECT`.

**Comment by knz** [comment]
Good find!

There's already an argument check for `EXP` motivated by the same problem in `expDecimal`, with a sketch of the general approach in a comment. Do you think you could emulate that for `POW`?

**Comment by mjibson** [comment]
This is trivially reproduced also:

```
 SELECT pow(2.0, -38);
```

Easy to kill the server with big values too:

```
SELECT pow(1e20, 500);
```

**Comment by mjibson** [comment]
The `pow(2.0, -38)` case has been fixed. The `pow(1e20, 500)` case remains.
