### ISSUE TITLE
cli/sql: add command to display history

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#97575]
Requested by @smcvey 

It would be useful to have a client-side commadn that prints out the history entries, akin to `\s` in `psql`.

Jira issue: CRDB-24766

**Comment by imskr** [comment]
I'm new to this project. Can I work on this?

**Comment by imskr** [comment]
@knz where do I have to add this? I'm new and not very comfortable with codebase structure

**Comment by imskr** [comment]
@knz I had started working on this. Please do comment before creating a PR @lyang24 to avoid duplication of efforts.
