### ISSUE TITLE
sql: switch to microseconds for storing intervals

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#9758]
if we want to make a breaking, on-disk change, we should probably do so before we get too close to "production ready".

Our current int64 of nanos is relatively limited (~280 years) by overflow issues.

**Comment by paperstreet** [comment]
+1 on these, though the breaking change is unfortunant. Maybe https://github.com/cockroachdb/cockroach/pull/9404 can help with the migration?

**Comment by dt** [comment]
Splitting related issue of switching timestamp representation into a separate issue tracked on  #9759

**Comment by nvanbenschoten** [comment]
+1 on this change as well. Headaches related to our deviation from PG will only continue to grow if we don't make a change like this sometime soon.

**Comment by petermattis** [comment]
Does this have to be a breaking change? If this is for intervals stored in the value can't we allocate a new tag for the new format? Old versions won't be able to read the new data, but that seems palatable.

**Comment by mjibson** [comment]
+1

**Comment by knz** [comment]
:+1:

**Comment by dt** [comment]
concluded in sql meeting that we'll keep the current types around for legacy compat.

**Comment by spencerkimball** [comment]
ping!

**Comment by dt** [comment]
unless the changes for collated string have made subtyping any easier, I think we concluded the combinatorial blow up in operators and builtins made duplicate interval types too expensive to maintain, so I'm not sure this is practical.

**Comment by knz** [comment]
I've done some work with intervals recently and it doesn't make sense to use a single field for intervals, because the way time arithmetic works (there's not always 24 hours to a day or 30 days to a month). I recommend closing this issue.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
