### ISSUE TITLE
c2c: improve initial scan performance

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#97592]
Occasionaly during an initial scan, a node on the destination cluster can fall behind on work, leading to poor initial scan performance. This issue tracks why this occurs.

This can be observed in the [upcoming ](https://github.com/cockroachdb/cockroach/pull/97465)`c2c/tpcc/warehouses=1000/duration=60/cutover=30` roachtest metrics: node 6 (red in right graphs) on the destination side fell very behind during the first 10 minutes of ingestion, relative to other nodes, and then ended up with the bulk of the work!
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/35438895/221024112-e69755f7-db39-44b7-b179-6d515da71501.png">

Specifically between 14:30 to 14:40 the lagging node still ingested SSTs via replication, but not much though the stream ingestions processor. For some reason, after 14:40, node6 picked up it's work and began directly ingesting the bulk of the SSTs.

Jira issue: CRDB-24777

Epic CRDB-19402

**Comment by stevendanna** [comment]
There is always more to do here. But I'm going to close this for now as @adityamaru made nice improvements here and we can open new issues for specific additional improvements.
