### ISSUE TITLE
kv: TestMultiRangeBoundedBatchScanSortedOverlapping: had 3 ranges at startup, expected 5

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#9765]
This is a timeout waiting for the initial splits. Seen in

https://teamcity.cockroachdb.com/viewLog.html?buildId=26819&buildTypeId=Cockroach_UnitTests

That PR on which I saw this failure #9721 notably increments the declined reservations timeout.

**Comment by tschottdorf** [comment]
@jordanlewis will remove the incremented timeout in (or shortly after) #9763, which should eliminate it as a culprit.

**Comment by tamird** [comment]
#10383.
