### ISSUE TITLE
server: tenant server is left dangling on error

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#97661]
I think if `startTenantServerInternal` returns both a server and an error, which can happen at least [here](https://github.com/cockroachdb/cockroach/blob/fccc6530c972287c74f69f688412837507f924ae/pkg/server/server_controller_new_server.go#L163), then we'll ignore the server [here](https://github.com/cockroachdb/cockroach/blob/fccc6530c972287c74f69f688412837507f924ae/pkg/server/server_controller_new_server.go#L87) and then we retry the server creation at a higher level, [here](https://github.com/cockroachdb/cockroach/blob/9e24c025f9a8ede0153ec9065e2545da54946239/pkg/server/server_controller_orchestration.go#L287). I think we're supposed to stop the new server, as [this comment](https://github.com/cockroachdb/cockroach/blob/fccc6530c972287c74f69f688412837507f924ae/pkg/server/server_controller_new_server.go#L129-L130) says. Generally, I'm not sure that attempting to recover from a tenant server failing to start is possible / sane.

I may well be missing something.

Jira issue: CRDB-24807
Epic: CRDB-23559

**Comment by knz** [comment]
@stevendanna could you have a qualifying look at what andrei says to see what we need to do? thanks

**Comment by stevendanna** [comment]
> Generally, I'm not sure that attempting to recover from a tenant server failing to start is possible / sane.

@andreimatei Just so I understand, are you saying you think the retry attempt itself should go?
