### ISSUE TITLE
TestTimeConversation fails: conv_test.go:52: strptime("2016 100 PM 11", "%Y %j %p %I"): got "2015-12-31T11:00:00Z", expected "2016-04-09T23:00:00Z"

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#9768]
Happened pretty randomly: 
```
--- FAIL: TestTimeConversion (0.00s)
       	conv_test.go:52: strptime("2016 100 PM 11", "%Y %j %p %I"): got "2015-12-31T11:00:00Z", expected "2016-04-09T23:00:00Z"
FAIL
FAIL   	github.com/cockroachdb/cockroach/util/timeutil 	0.416s
ok     	github.com/cockroachdb/cockroach/util/tracing  	0.023s
?      	github.com/cockroachdb/cockroach/util/uuid     	[no test files]
make: *** [test] Error 1
✘-2 ~/go/src/github.com/cockroachdb/cockroach [master|✚ 7…2⚑ 3]
00:14 $ date
Thu Oct  6 00:15:12 EDT 2016
```

**Comment by tschottdorf** [comment]
Happened again:

```
--- FAIL: TestTimeConversion (0.00s)
       	conv_test.go:52: strptime("2016 100 PM 11", "%Y %j %p %I"): got "2015-12-31T11:00:00Z", expected "2016-04-09T23:00:00Z"

01:23 $ date
Thu Oct  6 01:23:42 EDT 2016
```

**Comment by tamird** [comment]
Yeah, this is definitely still happening.

**Comment by knz** [comment]
It's actually a separate bug from the one initially filed for this issue, but thanks for noticing. I extended #9789 to fix this one too.

**Comment by nathanejohnson** [comment]
@knz just updated the alpine aport and am running into this failing test:

ok github.com/cockroachdb/cockroach/util/syncutil 0.012s
--- FAIL: TestTimeConversion (0.00s)
conv_test.go:58: strptime("2018 10 4", "%Y %W %w"): got "2017-12-31T00:00:00Z", expected "2018-03-08T00:00:00Z"
conv_test.go:58: strptime("2018 10 4", "%Y %U %w"): got "2017-12-31T00:00:00Z", expected "2018-03-15T00:00:00Z"
FAIL

I created a simple test program in C, it doesn't look like musl strptime honors %U.

https://gist.github.com/nathanejohnson/d71fb239cd7b906d72dbb285e9a430a6

**Comment by nathanejohnson** [comment]
Just verified, musl doesn't implement any week parsing in its strptime implementation

https://git.musl-libc.org/cgit/musl/tree/src/time/strptime.c#n123

**Comment by knz** [comment]
Thanks nathan for finding this issue! Filed as #10130.
