### ISSUE TITLE
server: enable CPU profiler by default - benchmarking tests

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#97699]
In #95623, we're introducing automatic collection of CPU profiles based on CPU usage thresholds.

There are concerns with the overhead of CPU profiles, so this is disabled by default.

We should quantify the overhead, maybe bring it down, and enable by default.

Jira issue: CRDB-24831

gz#17311

**Comment by tbg** [comment]
Related issue to roll out on cloud: https://cockroachlabs.atlassian.net/browse/CC-24928
It's likely wise to roll out on cloud first (if we can do that quickly enough) and then flip the bool for 23.2.

For the record, it's been enabled for some time on `telemetry` but this cluster isn't latency sensitive.

**Comment by tbg** [comment]
FYI it looks like CC rollout is in progress, see ticket above.

**Comment by kvoli** [comment]
@Santamaura do you know when this will get merged on master roachtests? A failure came up in https://github.com/cockroachdb/cockroach/issues/106140 which would have benefited from auto CPU profiles.

**Comment by rafiss** [comment]
@aadityasondhi can this issue be closed, since https://github.com/cockroachdb/cockroach/pull/118850 was merged?

**Comment by aadityasondhi** [comment]
Thanks for the callout. Closing this.
