### ISSUE TITLE
opt: histograms for large tables can miss frequent values

### ISSUE THREAD

**Issue by michae2** [cockroachdb/cockroach#97701]
By default we keep up to 10k samples during table statistics collection. This fixed sample size can be problematic for large tables. The chance that we will miss a frequent value (say a value used in 10k+ rows) increases as tables get larger (todo: plot this for tables with zipf-distributed data). We have seen at least one customer case with a histogram for a 600m+ row table missing a 30k+ value, so this is definitely possible in practice.

A couple ideas for how to address this:
- make sample size proportional to table size (probably means spilling to disk during table statistics collection)
- some sort of "lossless" histogram algorithm, since we're already doing a full scan of the table
- use a [confidence interval to estimate](https://en.wikipedia.org/wiki/Population_proportion#Estimation) row counts instead of calculating the expected value of the row count (similar to discussion in [#64570](https://github.com/cockroachdb/cockroach/issues/64570)) (but does this work when there are zero samples matching the constraint? the rule of thumb is that normality needs at least 10 observations)
- collect higher-resolution samples on known bad parts of the histogram (as described in [partial statistics collection](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20220126_partial_statistics_collection.md))

Jira issue: CRDB-24833
Epic: CRDB-34173

gz#19609

**Comment by mgartner** [comment]
Maybe @rytaft can add (or point to) some context about how the 10k value was determined. It seems like that value should scale up as the size of the table scales up.

**Comment by rytaft** [comment]
This [RFC](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20170908_sql_optimizer_statistics.md) has some of the history (it's also sprinkled with good ideas of future stats improvements!). I'm not sure where 10k came from, though (@RaduBerinde, perhaps you remember?). @michae2 and I discussed today that we should make both the sample size and the number of buckets configurable, and eventually add support for dynamically changing them (perhaps based on prior stats collections).

**Comment by michae2** [comment]
We have a formula for sample size that would make it proportional to table size. We're going to try using that formula to scale up sample size to address this.

**Comment by michae2** [comment]
We plan to do this in the next 3 months (during 24.1 development), but since it's an older issue the P-2 SLA calculated from issue creation time is a problem, so marking as P-3.
