### ISSUE TITLE
sql/catalog/validate: add precondition check for upgrading

### ISSUE THREAD

**Issue by Xiang-Gu** [cockroachdb/cockroach#97738]
Like what did for v22.2, we ought to have the precondition check run before upgrading to v23.1, to help us catch any descriptor corruptions before attempt upgrading.

Jira issue: CRDB-24859

**Comment by rafiss** [comment]
It might be too risky to backport this to 23.1. But let's keep this issue open so that we can do it for 23.2, and also come up with a way to make this less easy to forget in new major releases.

**Comment by rafiss** [comment]
actually, we have https://github.com/cockroachdb/cockroach/issues/104418 now, so i'll close this ticket in favor of that one.
