### ISSUE TITLE
use pagination on sql-over-http usages

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#97731]
Currently the pages from SQL Activity, Insights, Jobs and Databases are using sql-over-http without pagination, which can results in a max size limit.
Pagination should be used combined with this api usage

Jira issue: CRDB-24851

**Comment by j82w** [comment]
Databases pages page support was added in: https://github.com/cockroachdb/cockroach/pull/96431 and database details added in: https://github.com/cockroachdb/cockroach/pull/103752

**Comment by koorosh** [comment]
Proceed after https://github.com/cockroachdb/cockroach/issues/104582 issue is done.
