### ISSUE TITLE
sql: udf query cache should be reset after `SET search_path`

### ISSUE THREAD

**Issue by chengxiong-ruan** [cockroachdb/cockroach#97757]
**Describe the problem**
Looks like we try to use cached query result after `search_path` is set to new paths when executing queries selecting from UDFs.

**To Reproduce**
```
root@localhost:26257/defaultdb> CREATE FUNCTION public.abs(val INT) RETURNS INT CALLED ON NULL INPUT LANGUAGE SQL AS $$ SELECT val+100 $$;
CREATE FUNCTION

root@localhost:26257/defaultdb> SELECT abs(1);
  abs
-------
    1
(1 row)

root@localhost:26257/defaultdb> SET search_path = public, pg_catalog;
SET

root@localhost:26257/defaultdb> SELECT abs(1); -- this query should use the UDF abs which returns 101.
  abs
-------
    1
(1 row)
```

**Expected behavior**
`SELECT abs(1); ` should return 101 because it should use the UDF version of `abs` in `public` schema since the `public` schema is before `pg_catalog`.

Jira issue: CRDB-24872

**Comment by mgartner** [comment]
This is related to #93082.

**Comment by DrewKimball** [comment]
I think we're going to need to also keep track of builtin names that are referenced in a query. We shouldn't need to track anything else, since AFAICT the only cache invalidation that can happen there is that a UDF is resolved in place of the builtin. So, all we need to do is keep the name and check that it doesn't resolve to a UDF.

**Comment by chengxiong-ruan** [comment]
> I think we're going to need to also keep track of builtin names that are referenced in a query. We shouldn't need to track anything else, since AFAICT the only cache invalidation that can happen there is that a UDF is resolved in place of the builtin. So, all we need to do is keep the name and check that it doesn't resolve to a UDF.

Not familiar with the caching mechanism here. But, the issue could happen to a pure UDF as well. Sorry that I involved a builtin function which was misleading. But this issues is more general than that. Consider:
```sql
root@localhost:26257/defaultdb> create schema sc1;
CREATE SCHEMA

root@localhost:26257/defaultdb> create schema sc2;
CREATE SCHEMA

root@localhost:26257/defaultdb> create function sc1.f() returns int language sql as $$ select 1 $$;
CREATE FUNCTION

root@localhost:26257/defaultdb> create function sc2.f() returns int language sql as $$ select 2 $$;
CREATE FUNCTION

root@localhost:26257/defaultdb> set search_path = sc1, sc2;
SET

root@localhost:26257/defaultdb> select f();
  f
-----
  1
(1 row)

root@localhost:26257/defaultdb> set search_path = sc2, sc1;
SET

root@localhost:26257/defaultdb> select f(); -- it should have used sc2.f() which returns a `2`.
  f
-----
  1
(1 row)
```

**Comment by DrewKimball** [comment]
>But, the issue could happen to a pure UDF as well.

Oh, good point. I was thinking you always have to qualify a UDF in a case like that. I think that case should be handled by #96045, though.
