### ISSUE TITLE
running drop table command ... system hung ... don't know what happened.

### ISSUE THREAD

**Issue by youngl98** [cockroachdb/cockroach#9776]
Hi I am a cockroach beginner

I am running a 3 node cockroach secure cluster on RHEL 7.x linux

`uname -a
Linux ... 3.10.0-327.28.2.el7.x86_64 #1 SMP Mon Jun 27 14:48:28 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux`

I was running a drop table sql command connected to one of the followers. e.g. a node that was started with the --join command line option

the command was taking such a long time so I check the cockroach console and all the nodes were red.

I reviewed the logs and the problem seemed to happen around 11:04 when the raft leader lease changed hands or there was a timeout and then the leader lease changed hands?

The table definition is
`show columns from api;
+------------+-----------+-------+----------------+
|   Field    |   Type    | Null  |    Default     |
+------------+-----------+-------+----------------+
| id         | INT       | false | unique_rowid() |
| date       | TIMESTAMP | true  | NULL           |
| caller     | STRING    | true  | NULL           |
| component  | STRING    | true  | NULL           |
| method     | STRING    | true  | NULL           |
| url        | STRING    | true  | NULL           |
| count      | INT       | true  | NULL           |
| min        | INT       | true  | NULL           |
| median     | INT       | true  | NULL           |
| perc90     | INT       | true  | NULL           |
| perc95     | INT       | true  | NULL           |
| perc96     | INT       | true  | NULL           |
| perc97     | INT       | true  | NULL           |
| perc98     | INT       | true  | NULL           |
| perc99     | INT       | true  | NULL           |
| max        | INT       | true  | NULL           |
| status     | INT       | true  | NULL           |
| datacenter | STRING    | true  | NULL           |
+------------+-----------+-------+----------------+`

at the time I ran the drop table command the table had 300K+ rows.

Logs are attached.

BTW, I had to recreated the database and reload from the backup because I had to make the database available for a report I had to run.  so I no longer access to the old database.
[node1.tar.gz](https://github.com/cockroachdb/cockroach/files/513636/node1.tar.gz)
[node2.tar.gz](https://github.com/cockroachdb/cockroach/files/513637/node2.tar.gz)
[node3.tar.gz](https://github.com/cockroachdb/cockroach/files/513638/node3.tar.gz)

**Comment by tschottdorf** [comment]
Hi @youngl98,

I think what you're seeing is https://github.com/cockroachdb/cockroach/issues/627#issuecomment-229079530 (don't worry with the details of this link, the brief summary is that we need to do better for large deletion operations).

In the absence of a fix for this just yet, unfortunately my best advice right now is to prefer dropping and recreating the table over deleting its contents, or deleting the contents in smaller chunks. None of these are particularly satisfying, but we're working on it.

**Comment by youngl98** [comment]
Thanx for the update,

Glad that cockroach is on top of the issue.

Also, I noticed that after I restored from backup the number of replicas and the amount of disk spaced used is significantly lower compared to the state yesterday.

Yesterday the console showed 97 replicas and 8+GB of disk space consumed.

just now, the console show 8 replicas and 313MB of disk space.

There were times when deleted data from the api table for certain date ranges and reload data from splunk extracts because I modified the schema to add status and datacenter columns.

Is there a compaction utility available after repeated deletes and inserts?

**Comment by tschottdorf** [comment]
No, but there is a TTL for removing garbage-collectable keys. By default, this is 24 hours but can be changed. See here: https://www.cockroachlabs.com/docs/configure-replication-zones.html#replicaton-zone-format

Additionally, RocksDB (our on-disk storage engine) does compactions at its own pace which we currently don't expose facilities for influencing.

**Comment by knz** [comment]
Also regarding the amount of data on disk. The database statistics are collected in the DB itself. I believe we don't remove old stats yet, so they will accumulate over time too and will account for some of the difference you saw after you recreated the cluster.

**Comment by vivekmenezes** [comment]
https://github.com/cockroachdb/cockroach/issues/7499 and https://github.com/cockroachdb/cockroach/issues/9366 are fixed and while #627 is still open we do not expect you to see significant performance issues with dropping a table. Wanna give it another try with the latest Beta? Thank you!

**Comment by spencerkimball** [comment]
Closed for lack of activity.
