### ISSUE TITLE
jobs: migrate jobs to write their Payload and Progress to the jobs_info table

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#97762]
In https://github.com/cockroachdb/cockroach/pull/84866 we introduced a `system.jobs_info` table that is to be used to store job-specific state. This table allows a job to access and update information about its execution without adversely impacting the execution of other jobs. This is explained in detail in https://github.com/cockroachdb/cockroach/pull/82638.

As a first step, we want to teach jobs to write their Payload and Progress in their current form but to the jobs_info table instead of the jobs table. This migration will roughly involve:

1. Double writes for the Payload and Progress of jobs to both the jobs_info and jobs table.

2. A migration to backfill job_info with the Payload and Progress of all job records in the system.jobs table.

3. A change to read methods in the registry to pull the Payload and Progress from the job_info table instead of the jobs table.

In the future, jobs may want to decompose their Payload and Progress protos further and write different fields as their own rows in the jobs_info table. This is outside the scope of this issue.

Jira issue: CRDB-24874

Epic CRDB-8964

**Comment by shermanCRL** [comment]
cc @amruss

**Comment by adityamaru** [comment]
Reopening this issue since we still need to drop payload+progress columns from `system.jobs` or atleast NULL them out. This is the only conclusive way to prove we have not missed any callers that still rely on these columns being correctly populated.

**Comment by adityamaru** [comment]
Leaving this open until I backport https://github.com/cockroachdb/cockroach/pull/99458 which I plan to do today. I agree we won't be dropping the columns this release.

**Comment by adityamaru** [comment]
I'm going to mark this as done, all the relevant pieces have landed in 23.1. Any future improvements can be tracked separately.
