### ISSUE TITLE
cockroachdb/errors: support multi-errors for 1.20

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#97799]
**Is your feature request related to a problem? Please describe.**
See https://github.com/cockroachdb/errors/issues/99 and https://github.com/cockroachdb/cockroach/issues/96443.
We must do this before we release a version with go1.20. 

**Describe alternatives you've considered**
We can not upgrade to go 1.20.

**Checklist**
- [x] https://github.com/cockroachdb/cockroach/issues/106521
- [x] https://github.com/cockroachdb/cockroach/issues/106523
- [x] https://github.com/cockroachdb/cockroach/issues/106524

Jira issue: CRDB-24894

Epic CRDB-29601

**Comment by dhartunian** [comment]
cockroachdb/errors v1.11.0 and higher support multi-cause errors and go 1.20 https://github.com/cockroachdb/errors/releases/tag/v1.11.0
