### ISSUE TITLE
storage: locality should be on the NodeDescriptor, not StoreDescriptor

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#9782]
https://github.com/cockroachdb/cockroach/pull/8676 appears to have put it on the StoreDescriptor for no good reason (that I can see).

This should get done before next week's beta to avoid subsequently breaking compatibility.

**Comment by tschottdorf** [comment]
We could also just hide the `--locality` flag before the release to buy us time and not let this turn around our priorities.

**Comment by tamird** [comment]
Good point, I'd be fine with that as well.
