### ISSUE TITLE
sql,kv: extend SHOW RANGES to include table/index size estimates

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#97858]
**Describe the problem**

Currently `SHOW RANGES WITH DETAILS` only includes range sizes, not object sizes.

When a range contains multiple table/indexes, the range size cannot be used to estimate the table/index size any more.

So we need a replacement for where people would previously use SUM on the range size.

This can use the new span stats computation that Zach implemented in #96223 .

Jira issue: CRDB-24925
Epic: CRDB-24928

**Comment by Santamaura** [comment]
Maybe it's my lack of familiarity with `SHOW RANGES` but isn't it all generated in one statement in the delegate framework? If so then it's unclear to me how we would use a `SpanStatsResponse` directly unless the way forward is to make a span stats builtin and then add it to the statement?

**Comment by rafiss** [comment]
Does this issue replace https://github.com/cockroachdb/cockroach/issues/20712? Also, does it make https://github.com/cockroachdb/cockroach/issues/86017 easier to resolve?

**Comment by knz** [comment]
It _might_ replace #20718 depending on where #98339 gets to.

It will not replace #85834 nor make #86017 easier to resolve. For that, we need a _stored cache_ of the computed approximations (presumably alongside system.descriptors) and expose that data via the pg-compatible builtin function. Building that cache is out of scope here and in #98339 as far as i understand.
