### ISSUE TITLE
Error when executing EXPLAIN on SQL SELECT *

### ISSUE THREAD

**Issue by entishman** [cockroachdb/cockroach#97855]
PROBLEM SPACE: 

When executing an EXPLAIN on the following query: 

SELECT * FROM payments WHERE  country='PH';

I receive the following error:

* ERROR: Queued as error a7c7f4222fff4c2c91d2edd6face7450

ERROR: internal error: runtime error: index out of range [1] with length 1
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/util/errorutil/catch.go:29: ShouldCatch()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:240: func1()
GOROOT/src/runtime/panic.go:884: gopanic()
GOROOT/src/runtime/panic.go:113: goPanicIndex()
github.com/cockroachdb/cockroach/pkg/sql/opt/table_meta.go:393: IndexPartitionLocality()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/select_funcs.go:437: func1()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/scan_index_iter.go:305: ForEachStartingAfter()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/scan_index_iter.go:208: ForEach()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/select_funcs.go:433: GenerateConstrainedScans()
github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/xform/explorer.og.go:254: exploreSelect()
github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/xform/explorer.og.go:22: exploreGroupMember()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/explorer.go:181: exploreGroup()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:528: optimizeGroup()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:685: optimizeEnforcer()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:645: enforceProps()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:555: optimizeGroupMember()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:515: optimizeGroup()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:291: optimizeExpr()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:570: optimizeGroupMember()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:515: optimizeGroup()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:261: Optimize()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:789: makeQueryIndexRecommendation()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:569: buildExecMemo()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:232: makeOptimizerPlan()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1474: makeExecPlan()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1082: dispatchToExecutionEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:697: execStmtInOpenState()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:131: func1()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2428: execWithProfiling()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:130: execStmt()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1933: func1()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1937: execCmd()

HINT: You have encountered an unexpected error.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.

We appreciate your feedback.

HOW TO REPLICATE:

set up a self-hosted 9 node,3 region cluster

select version();
                                       version
--------------------------------------------------------------------------------------
  CockroachDB CCL v22.2.3 (x86_64-pc-linux-gnu, built 2023/01/23 19:11:57, go1.19.1)

Client: Cockroach SQL client

Execute the following SQL commands:

CREATE DATABASE central_payments;
USE central_payments;

CREATE TABLE public.payments (
id INT8 NOT NULL DEFAULT unique_rowid(),
business_id VARCHAR NOT NULL,
country STRING NOT NULL,
CONSTRAINT pk_country_id PRIMARY KEY (country ASC, id ASC)
) PARTITION BY LIST (country) (
PARTITION partition_vietnam VALUES IN ('VN'),
PARTITION partition_thailand VALUES IN ('TH'),
PARTITION partition_malaysia VALUES IN ('MY'),
PARTITION partition_philippines VALUES IN ('PH'),
PARTITION partition_indonesia VALUES IN ('ID')
);

ALTER PARTITION partition_indonesia OF INDEX central_payments.public.payments@pk_country_id CONFIGURE ZONE USING
num_replicas = 5,
num_voters = 3,
voter_constraints = '{+region=aws-ap-south-1}',
lease_preferences = '[[+region=aws-ap-south-1]]';

ALTER PARTITION partition_malaysia OF INDEX central_payments.public.payments@pk_country_id CONFIGURE ZONE USING
num_replicas = 5,
num_voters = 3,
voter_constraints = '{+region=aws-ap-southeast-1}',
lease_preferences = '[[+region=aws-ap-southeast-1]]';

ALTER PARTITION partition_philippines OF INDEX central_payments.public.payments@pk_country_id CONFIGURE ZONE USING
num_replicas = 5,
num_voters = 3,
voter_constraints = '{+region=aws-ap-southeast-1}',
lease_preferences = '[[+region=aws-ap-southeast-1]]';

ALTER PARTITION partition_thailand OF INDEX central_payments.public.payments@pk_country_id CONFIGURE ZONE USING
num_replicas = 5,
num_voters = 3,
voter_constraints = '{+region=aws-ap-northeast-3}',
lease_preferences = '[[+region=aws-ap-northeast-3]]';

ALTER PARTITION partition_vietnam OF INDEX central_payments.public.payments@pk_country_id CONFIGURE ZONE USING
num_replicas = 5,
num_voters = 3,
voter_constraints = '{+region=aws-ap-northeast-3}',
lease_preferences = '[[+region=aws-ap-northeast-3]]';

Execute the following query to receive the above error:
EXPLAIN SELECT * FROM payments WHERE country='PH';

Jira issue: CRDB-24923

**Comment by msirek** [comment]
This seems to be fixed here: https://github.com/cockroachdb/cockroach/pull/94671
Consider backporting to v22.2

**Comment by DrewKimball** [comment]
Fixed by #98359

**Comment by msirek** [comment]
Fixed by https://github.com/cockroachdb/cockroach/pull/98359 in v22.2.
