### ISSUE TITLE
sql: consider limiting the memory usage of prepared statements in a single session

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#97866]
Currently, all prepared statements of a single session are kept in memory until either the session stops (could be due to a node restart) or the prepared statements are dropped via `DEALLOCATE` command. If a user has long-lived sessions (e.g. due to the usage of the connection pooling) and creates new prepared statements without deallocating the previous ones, the memory usage of all of the prepared statements on the node can reach `--max-sql-memory` budget in which case the node can effectively become unavailable.

We should consider limiting the memory usage of all prepared statements at the session level, perhaps by implementing LRU cache. Note that the current behavior of never internally deallocating prepared statements is consistent with Postgres, so evicting the prepared statements once the threshold is reached can break the existing applications. However, it seems that the downside of that (an app hitting an error) might be smaller than the downside of keeping all prepared statements live and in-memory (node becoming unavailable).

Jira issue: CRDB-24930

**Comment by mgartner** [comment]
This seems very related to https://github.com/cockroachdb/cockroach/issues/72581. Possibly a duplicate?

**Comment by michae2** [comment]
If we had some hook into the connection pooling, we could perform a `DEALLOCATE ALL` ourselves on the pooled connection when the application connection closes. (But I don't know if we have such a hook.)

**Comment by michae2** [comment]
Marking this as a GA blocker because a customer is waiting for it, and also I'd like to merge it to release-23.1 before https://github.com/cockroachdb/cockroach/pull/99663.
