### ISSUE TITLE
storage: remove `storage.mvcc.range_tombstones.enabled` cluster setting

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#97869]
**Is your feature request related to a problem? Please describe.**

The MVCC Range Tombstones feature shipped in 22.2, gated behind the `storage.mvcc.range_tombstones.enabled` cluster setting. While the setting will continue to exist in 23.1, the feature is _unconditionally enabled_ (i.e. the cluster setting is ignored).

In 23.2 we should remove the cluster setting and the associated helper functions, etc.

**Additional context**

See #91147 for the original context.

Jira issue: CRDB-24933

**Comment by jbowens** [comment]
https://github.com/cockroachdb/cockroach/blob/eff0185802838bbdaf385e734969424c23cc989b/pkg/ccl/backupccl/testdata/backup-restore/in-progress-import-rollback#L10-L13

@cockroachdb/disaster-recovery This unit test appears to still use this cluster setting. Can we delete or adjust this unit test to remove testing of non-MVCC rollbacks now?

**Comment by dt** [comment]
@msbutler might have more context here, but one question: 23.2 maintains backwards compatibility with 22.2 so I think we wanted to keep the tests that simulated restoring a 22.2 backup/the 22.2 range tombstone behavior?

**Comment by msbutler** [comment]
to do that, we'd need a 22.2 fixture which simulates the behavior. I think it's fine to delete this subtest to unblock this pr though.

**Comment by itsbilal** [comment]
This cluster setting has been removed already.

**Comment by itsbilal** [comment]
For reference: this was removed in https://github.com/cockroachdb/cockroach/pull/112269.
