### ISSUE TITLE
Backup starts to fails after upgrading to 22.2

### ISSUE THREAD

**Issue by colprog** [cockroachdb/cockroach#97864]
**Describe the problem**

We have a scheduled backup job doing a full weekly backup, after out recent  upgrade to 22.2,  We notice these jobs
fails with this error message: 
`checking for BACKUP-LOCK file: failed to list s3 bucket: InvalidArgument: The length of delimiter must be 1. status code: 400, request id: 174857600D30EE43, host id:`
After some investigation, the problems seems related to this changes: 66238f2be65ec0a54f4fade68c8b2198e41376dd, which
make use of delimiter parameter in backup. AWS states that delimiter is a _character_  in its [document](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html), and the s3-compatible service we use apparently goes the extra mile and validates it, making backups fail.

Is it possible restore compatibility?

Jira issue: CRDB-24929

**Comment by shermanCRL** [comment]
Thanks for the report! We will look into it.

Which S3 service are you using, and version? We only test against AWS S3 and otherwise do our best to accommodate third-party services.

**Comment by colprog** [comment]
We use Aliyun OSS, cloud service provided by alibaba. We're currently on crdb 22.2.5.

**Comment by TaoXieSZ** [comment]
Hi, we are facing the same problem when we are trying  to backup in Cloud Object Storage service provided by Tencent Cloud. And it promises to be compatible with S3.
