### ISSUE TITLE
Ability to query `crdb_internal.kv_node_status` (API)

### ISSUE THREAD

**Issue by lancel66** [cockroachdb/cockroach#97872]
**Is your feature request related to a problem? Please describe.**
Requesting the ability to query `crdb_internal.kv_node_status` without admin access. Currently, this requires admin access.

```
root@10.10.10.10:26257/crdb_node1> select * from kv_node_status;
ERROR: only users with the admin role are allowed to read crdb_internal.kv_node_status
SQLSTATE: 42501
```
**Describe the solution you'd like**

To support an internal data integration project, a customer wants to be able to discover changes to CRDB at runtime and load/unload new nodes as well as add them to the load-balancing pool. They would like to be able to do "cluster discovery" from a single seed node.

This query seems to be the only way to do this, and it also includes the latest heartbeat, which is very useful for performing actions like excluding old nodes.

The ideal solution would be to expose this as a SQL and/or HTTP API.

Jira issue: CRDB-24936

Epic CRDB-24527

**Comment by rafiss** [comment]
resolved by https://github.com/cockroachdb/cockroach/pull/110084

the VIEWCLUSTERMETADATA system privilege now gives access to this table.
