### ISSUE TITLE
A question about the consistency

### ISSUE THREAD

**Issue by a1424360017** [cockroachdb/cockroach#97904]
I want to know whether the following scenarios will occur when CRDB using **pipelineWrite**

1、txn1 **Begin** with a lower timestamp
2、txn2 **Begin** with a higher timestamp
3、txn1 send **Write(key,newValue)** to cluster - node1(leaseHolder),node2,node3
4、node1 append this **request(Write)** to its log and returns
5、when this **log(Write)** has not been backed up, node2 becomes leaseHolder
6、txn2 send **Read(key)** to node2(LeaseHolder)
7、Because there is no concurrency conflict on node2 , node2 return a olderValue for **request(Read)**
8、node1 becomes leaseHolder again and backup **log(Write)** (I do not know whether there is R\W Conflict Judgement or Concurrency control)
9、txn1 Commit and txn2 Commit

So, txn2 with a higher timestamp does not read the value written by txn1 with a lower timestamp, which violate **SSI**

Jira issue: CRDB-24953

**Comment by nvanbenschoten** [comment]
Hi @a1424360017, thanks for the question. The scenario you described is not possible in CRDB. When node 2 takes over as leaseholder, it will either apply txn 1's write (it it achieved consensus before the corresponding lease request), or it will prevent txn 1's write from ever being applied in the future. This means that even if node 1 takes over as leaseholder again at some later point, it will not have applied txn 1's write, so txn 1 will be aborted.
