### ISSUE TITLE
changefeedccl: Fix max behind nanos metric

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#97931]
Max behind nanos metric has been the source of large number of
escalations -- often times because it's confusing metric.

Concretely: max behind nanos needs to be renamed.
I propose renaming this metric to be "checkpoint lag" (or something similar)
to communicate that this is *not* message latency, but an indicator how
far behind the changefeed checkpoint is.

Before renaming/changing it, we should find out what the process for
retiring this metric might be.  I suspect that we can't easily remove
it given how widely it is used.  Instead, we should introduce a new metric,
with better behavior and name, and show that metric in the console.

It would be nice to also make sure that this metric doesn't jump around during restarts
and behaves sensibly during initial scan.

Jira issue: CRDB-24970

Epic CRDB-9181

**Comment by amruss** [comment]
Should we just remove this metric all together? It doesn't seem useful for customers to track? @thtruo any thoughts on retiring a metric that is prominent in db console?

**Comment by miretskiy** [comment]
I don't think we can remove it given how many monitoring rules are out there that are using it..
But we should deprecate it.

**Comment by jayshrivastava** [comment]
The action items for 23.1 are:
- Mark this metric as "deprecated" or "to be deprecated in a future release" without changing it at all. I'm not sure what the exact way to do this is, so I asked [here](https://cockroachlabs.slack.com/archives/C01CNRP6TSN/p1680536301995009). I assume that I can add notes to suggest alternatives. 
  - We can suggest looking at the "commit latency" to actually measure commit latency
  - We can suggest monitoring the highwaters to monitor changefeeds actually being behind. I think it's feasible to add a metric called "oldest highwater" which polls the jobs table to check if changefeeds are behind.
  
 For 23.2 onwards, we can consider removing it. To be clear, "removing it" means removing it from the DB console. If it's not a lot of work, we can replace it with commit latency, which we want to do anyways. See https://docs.google.com/document/d/1QzZO6PycCmEjBXeO8ZMNbQYRUy9DvQA0kQO8SJxAHZg/edit#.
 
 This roachmap follows the short deprecation outline followed [here](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/952107816/How+to+make+a+feature+deprecated)
