### ISSUE TITLE
server: sql api doesn't work if user drops "defaultdb"

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#97950]
The sql over http uses `defaultdb` as the database to execute the queries, but if that database is deleted by users, all calls will fail.
During restore, this database will also be deleted (and then recreated), so the usage of the api wouldn't work for the duration of restores (that can take hours).

There should be a backup, where another database is selected or just a new database created for this case specifically. We can't use system, because non-admin might make calls and it would fail.

Code location of the database selected:
https://github.com/cockroachdb/cockroach/blob/94f14ab84dafcc9222003db4ba1c103df5e293c9/pkg/server/api_v2_sql.go#L317

Jira issue: CRDB-24981

**Comment by ajwerner** [comment]
`defaultdb` should not be used internally anywhere. It's just a normal database. Everything should use `system`, the only database guaranteed to exist.

**Comment by ajwerner** [comment]
Where's the code that does something related to `defaultdb`?

**Comment by maryliag** [comment]
The place where it gets set (or default to `defaultdb`): https://github.com/cockroachdb/cockroach/blob/18c69179f1383c84879aea72880818ea63abfb9a/pkg/ui/workspaces/cluster-ui/src/api/sqlApi.ts#L18

Right now all calls using that api fails, an example can be see if you drop the defaultdb and try opening the insights page. You will see the error:

<img width="773" alt="Screenshot 2023-03-02 at 6 42 40 PM" src="https://user-images.githubusercontent.com/1017486/222590318-3d7adea2-f974-4cc2-9554-2739ddc14016.png">

If we change to system, couldn't that cause non-admin to still fail, but now with a message of no permission?

**Comment by maryliag** [comment]
On the api itself: https://github.com/cockroachdb/cockroach/blob/94f14ab84dafcc9222003db4ba1c103df5e293c9/pkg/server/api_v2_sql.go#L317
