### ISSUE TITLE
stability: debug endpoint for command queue introspection

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#9797]
In https://github.com/cockroachdb/cockroach/issues/9749, we were seeing the command queue on time series Replicas overflooded and performing poorly as a result.

We should build a debug endpoint which exposes data that helps debug these issues the future. As for details on what should be exposed, I defer to @nvanbenschoten.

**Comment by dianasaur323** [comment]
@nvanbenschoten I'm cleaning out Q1 2017 milestones. I think I want to move this to Q3 2017 if it's still relevant. Feel free to adjust if you disagree.

**Comment by nvanbenschoten** [comment]
Q3 seems appropriate to me. Thanks @dianasaur323.

**Comment by petermattis** [comment]
This should probably live on the /debug/range page. Or maybe summarized on the /debug/range page with a link for more details about the commands sitting in the queue for a specified range.

**Comment by cuongdo** [comment]
@BramGruneir is this still happening for 1.1?

**Comment by BramGruneir** [comment]
If it's just a metric that we're adding to the debug range page, than yes.
But if it's a new endpoint and specialized page, I think we should push it out.

**Comment by petermattis** [comment]
I think there is both short term and long term work. Short term let's add a metric for the size of the command queue. I think this can get into 1.1. Long term I think we want a new debug page for introspection of what the command queue contains. Let's push this to 1.2.

**Comment by BramGruneir** [comment]
SGTM

**Comment by a-robinson** [comment]
> Long term I think we want a new debug page for introspection of what the command queue contains.

<img src="http://i3.kym-cdn.com/photos/images/facebook/000/104/953/do_want.jpg">

**Comment by cuongdo** [comment]
@nvanbenschoten Can you fill in some details regarding what's needed here? I'm intending for this to be a starter project to be worked on starting next week.

**Comment by nvanbenschoten** [comment]
I think @BramGruneir actually just got started on this.

At a minimum, we'd want information about the size of the `CommandQueue`, similar to what we have in [`updateCommandQueueGauges`](https://github.com/cockroachdb/cockroach/blob/c01bef22d97156f2d125ea9caa16ee28b5655614/pkg/storage/store.go#L4048), but on a per-Replica basis.

I think we'd also want to get some insight into what commands are being blocked on what. We'd also want some insight into how long different commands in the queue have been waiting. A full visual representation of the `CommandQueue's` interval tree and the dependency graph built on top of it (similar to the [diagrams](https://github.com/cockroachdb/cockroach/blob/c01bef22d97156f2d125ea9caa16ee28b5655614/pkg/storage/command_queue.go#L373) we have scattered everywhere) would be incredible, but that might be overly ambitious. The structure of `cmd` holding onto its `prereqs []*cmd` means this should be completely possible, though. We'd want this for both a replica's local and global `CommandQueue`.

@tschottdorf is there anything else you think would help in cases where commands get stuck?
