### ISSUE TITLE
distsql: apply-join can capture the wrong transaction

### ISSUE THREAD

**Issue by DrewKimball** [cockroachdb/cockroach#97989]
During flow setup on the gateway node, we check whether the flow has any concurrency. If yes, we make sure to use the leaf txn for the flow. If no, we may use the root txn, which doesn't support concurrent requests. That logic is handled [here](https://github.com/cockroachdb/cockroach/blob/cd80204403868ef31b2f464e6e4f08dff382e267/pkg/sql/distsql/server.go#L433-L449) in `ServerImpl.setupFlow`. Apply-joins are effectively nested-loop joins from postgres. They fully re-plan and then execute their right input for each row from their left input. This means each apply-join iteration creates its _own_ flow. In order to do this, apply-join execution nodes keep track of a transaction, which is captured [here](https://github.com/cockroachdb/cockroach/blob/cd80204403868ef31b2f464e6e4f08dff382e267/pkg/sql/distsql_physical_planner.go#L3534-L3542) in `DistSQLPlanner.wrapPlan` through the planner and evalCtx. The problem is that the transaction is captured before the main query makes its decision about which transaction to use, and so we can end up executing the right side of an apply-join with the root txn when the main query has concurrency that necessitates use of the leaf txn.

This caused a query to repeatedly fail in a customer issue, where multiple apply-joins were planned in the inputs of a `Union`, which was planned as a `ParallelUnorderedSynchronizer`. This caused the apply-joins to be executed concurrently with one another, and since they used the root txn, KV returns a `concurrent txn use detected` error when concurrent requests are received. Note that even if there was only one concurrent use of the root txn while the main query used a leaf txn, the usage would still be incorrect even though it wouldn't hit that particular error condition (see internal discussion [here](https://cockroachlabs.slack.com/archives/C0KB9Q03D/p1677789920142049)).

I've been unable to reproduce the error the customer ran into so far, but suggesting a query rewrite to remove the apply-joins fixed the issue for them. We should fix apply-join execution to use the correct transaction - probably either by modifying the captured transaction if the main query has concurrency, or by just always using a leaf txn for apply-joins.

See also #41992, which tracks the general case of expressions capturing the wrong transaction, and refactoring to prevent this problem.

Jira issue: CRDB-25005

**Comment by yuzefovich** [comment]
Thanks for the investigation! I'll take this one unless you're already working on it.

**Comment by DrewKimball** [comment]
> I'll take this one unless you're already working on it.

SGTM

**Comment by yuzefovich** [comment]
I'm pretty sure it'll affect UDFs. I haven't had time to come up with a reproduction yet (but I will try later today) and I think Drew also hasn't come up with one yet.

**Comment by DrewKimball** [comment]
>Is there a reliable way to reproduce the problem for apply-joins that I could try to tweak to reproduce for UDFs?

It's pretty easy to get the apply-join to just use the root txn, since that just always happens when planning on the gateway node. I wasn't able to actually trigger the `concurrent txn use detected` error though - it was just too difficult to get the distsql planner to do everything necessary for that to happen.
