### ISSUE TITLE
JSON path passed as parameter to psycopg3 does not return matching result

### ISSUE THREAD

**Issue by gordthompson** [cockroachdb/cockroach#97984]
**Describe the problem**

(Found this when running the SQLAlchemy test suite against sqlalchemy-cockroachdb.)

Passing a JSON path as a string parameter using psycopg3 does not return the matching result from CockroachDB. The same query with psycopg3 against PostgreSQL works fine. Specifying the path as a string literal works in all cases.

**To Reproduce**

```python
import psycopg2
import psycopg

# using CockroachDB v23.1.0-alpha.4
print(psycopg2.__version__)  # 2.9.5 (dt dec pq3 ext lo64)
print(psycopg.__version__)  # 3.1.8

combinations = {
    " postgresql+psycopg2": psycopg2.connect(
        "host=192.168.0.199 dbname=test user=scott password=tiger"
    ),
    "cockroachdb+psycopg2": psycopg2.connect(
        "host=localhost port=26257 dbname=defaultdb user=root"
    ),
    "  postgresql+psycopg": psycopg.connect(
        "host=192.168.0.199 dbname=test user=scott password=tiger"
    ),
    " cockroachdb+psycopg": psycopg.connect(
        "host=localhost port=26257 dbname=defaultdb user=root"
    ),
}

for combi, cnxn in combinations.items():
    crsr = cnxn.cursor()
    crsr.execute("DROP TABLE IF EXISTS data_table")
    cnxn.commit()
    crsr.execute("""\
    CREATE TABLE data_table (
        id SERIAL NOT NULL, 
        data JSONB NOT NULL, 
        PRIMARY KEY (id)
    )
    """)
    cnxn.commit()
    crsr.execute("""\
    INSERT INTO data_table (data) VALUES ('{"key1": {"subkey1": 15}}')
    """)
    cnxn.commit()

    path = "{key1, subkey1}"

    # path as literal
    sql = f"SELECT data_table.data  #>> '{path}' FROM data_table"
    crsr.execute(sql)
    results = crsr.fetchall()
    print(f"{combi} (literal): {results}")

    # path as param
    sql = "SELECT data_table.data  #>> %(data_1)s FROM data_table"
    params = {"data_1": path}
    crsr.execute(sql, params)
    results = crsr.fetchall()
    print(f"{combi} (w/param): {results}")

    cnxn.rollback()
    crsr.close()

"""console output:
 postgresql+psycopg2 (literal): [('15',)]
 postgresql+psycopg2 (w/param): [('15',)]
cockroachdb+psycopg2 (literal): [('15',)]
cockroachdb+psycopg2 (w/param): [('15',)]
  postgresql+psycopg (literal): [('15',)]
  postgresql+psycopg (w/param): [('15',)]
 cockroachdb+psycopg (literal): [('15',)]
 cockroachdb+psycopg (w/param): [(None,)]
"""
```
**Expected behavior**
Value returned as in the other cases.

**Environment:**
 - CockroachDB version: v23.1.0-alpha.4
 - Server OS: Ubuntu 20.04
 - Client app: Python 3.8, psycopg (a.k.a. psycopg3)

Jira issue: CRDB-25001

Epic CRDB-27601

**Comment by gordthompson** [comment]
cc: @rafiss

**Comment by Xiang-Gu** [comment]
Thank you for reporting this issue. @cockroachdb/sql-sessions should be the right team for this.

**Comment by rafiss** [comment]
@gordthompson I was able to take a closer look at this. I used Wireshark to capture the network traffic between this script and the database. I found that the `psycopg2` examples (both for Postgres and CockroachDB) are using a simple literal query for _all_ of the test cases. 

So there's certainly a bug in CRDB, but it's likely we've narrowed it down to how prepared statements with placeholders are handled.

**Comment by rafiss** [comment]
I found the problem. We have a bug in how we parse placeholder arguments that are of the `TEXT[]` type. CRDB doesn't handle the spaces in between the elements. If you change your argument to `path = "{key1,subkey1}"`, then your example works correctly.

I will fix this bug and backport the fix.
