### ISSUE TITLE
obs-infra: query time series poll request failed

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#98003]
Seeing an error message on datadog showing up in a few different pages with

```
Query Time Series poll request failed: Unhandled server side error (trace ID: 1493213592918318331). Request params: {"clusterId":"b70137dc-541d-4143-b9d7-6618f869c8b5","startMillis":1677856384000,"endMillis":0,"queriesList":[],"pollResolution":1}
```

Jira issue: CRDB-25011

**Comment by abarganier** [comment]
```
Request params: {"clusterId":"b70137dc-541d-4143-b9d7-6618f869c8b5","startMillis":1677856384000,"endMillis":0,"queriesList":[],"pollResolution":1}
```
`queriesList` in the request is empty, which the `QueryPromQLTimeSeries` endpoint doesn't currently tolerate.

https://github.com/cockroachlabs/managed-service/blob/fb7964bc870833429bfe964a45e9d1c6af1297d2/console/server/timeseries/timeseries.go#L438-L440
```
	if len(req.Queries) < 1 {
		return nil, errors.New("empty IndicatorType list")
	}
```

We should probably just return an empty response in this case. If the API accepts a list, then it should be able to handle an empty list. I can put a PR up.

Separately, there might be some investigation on the front-end owner's end to look into why requests with empty query lists are being made, although I'm not familiar enough with that code to know whether or not that is anything to be concerned about.

**Comment by abarganier** [comment]
Created https://github.com/cockroachlabs/managed-service/pull/12079 to address
