### ISSUE TITLE
backup: increase restore worker count automatically when core count and memory allows

### ISSUE THREAD

**Issue by lidorcarmel** [cockroachdb/cockroach#98015]
Adjust the number of workers, increase openSSTs parallelism.
Test with nodes with low memory per core ratio (n1-highcpu-xx).

Initial benchmarking shows 16 and 32 cores can see ~2x improvement.

Epic CRDB-20916

Jira issue: CRDB-25014

**Comment by shermanCRL** [comment]
Notes from a conversation with @dt.
- Memory monitoring from @rhu713 will merge soon: https://github.com/cockroachdb/cockroach/pull/93324. That will get us some safety for free.
- We should use the above to dynamic determine the parallelism. Add workers until the memory request is rejected, or we reach the desired #.
