### ISSUE TITLE
acceptance: TestUpreplicate_1To6Medium fails

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#9804]
After not running this test for ~2 months, we ran it last night and it failed with:

```
[TestUpreplicate_1To6Medium] 	allocator_test.go:192: 3m8.255495s elapsed without changes, but replica count standard deviation is 22.81 (>10.00)
```

Full log: https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=27912#_focus=484

**Comment by cuongdo** [comment]
My manual run and the nightly run passed. I couldn't reproduce the previous failures, so I think this was some kind of temporary GCS flakiness happening when downloading the test store data.

**Comment by cuongdo** [comment]
It's worth noting that I tweaked the max standard deviation allowed. With 2065 ranges (on the original, single node), the default of 10 was unproductively strict. Based on the current heuristics of rebalancing when a node is more than 5% away from the mean replica count, this is 5%*((2065 ranges)*(3  replicas per range)/(6 nodes))=52.

**Comment by tamird** [comment]
Where did you tweak it? Does that stuff live in the TC config?

**Comment by cuongdo** [comment]
Yes, it's a command-line flag (`-at.std-dev`), which is set by the TC
config.
