### ISSUE TITLE
tracing: investigate using gRPC-OpenTracing interceptors

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#9806]
https://github.com/grpc-ecosystem/grpc-opentracing/pull/3 implements gRPC interceptors that automatically inject and extract an opentracing span context for RPCs. We should investigate using this infrastructure instead of an explicit proto field (`header.Trace`).

CC @andreimatei @tschottdorf @tamird

**Comment by tamird** [comment]
This is blocked on #9697.

**Comment by RaduBerinde** [comment]
An investigation is never blocked! :)

**Comment by RaduBerinde** [comment]
Note: the lightstep library dependency is pinned until we do this; the newer libraries aren't compatible with the way we extract and inject trace context information. See https://github.com/cockroachdb/cockroach/pull/15328#issuecomment-297086010.

**Comment by RaduBerinde** [comment]
I hit a snag - the `grpc-opentracing` only implements "unary" (non-stream) RPC interceptors. We will need to implement the stream versions ourselves, perhaps contribute them upstream.
