### ISSUE TITLE
changefeedccl: expand gc_protect_expires_after to be applied to running changefeeds

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#98063]
`gc_protect_expires_after` only applies to paused changefeeds today. We would like to expand this to running changefeeds - since they will also cause unbounded lingering protected timestamps even without being paused. Note: this expiration should not be applied when running an initial scan. We should also prevent you from setting this setting very low (< 1 hour?)

Jira issue: CRDB-25451

Epic CRDB-28882

**Comment by miretskiy** [comment]
Yes, that's correct.

**Comment by miretskiy** [comment]
Resolved via #103539
