### ISSUE TITLE
*: add user-facing documentation for lowered GC TTL

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#98105]
**Is your feature request related to a problem? Please describe.**

We lowered the default GC TTL from 25h to 4h as part of #89233. This issue tracks documenting the motivations and implications for users in our public docs. Filing an issue to track it as a GA-blocker before 23.1 ships out into the wild. Some discussion internally at #lower-gc-ttl.

Jira issue: CRDB-25079

**Comment by nicktrav** [comment]
@rmloveland - reckon we could close this one out now that your docs PR landed?

**Comment by rmloveland** [comment]
ya, feel free to close IMO, the basics are there now, any remaining additional stuff will happen via DOC-6820
