### ISSUE TITLE
tenantcapabilities: cluster setting gate tenant capability infrastructure

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#98138]
**Describe the problem**

Tenant capabilities are stored in the `TenantInfo` column in `system.tenants`, which was added this release. We establish a rangefeed over `system.tenants` and expect the column to be there -- as such, we should version gate the infrastructure until the migration to add the column has started. Without it, we would end up fataling the node, as capabilities won't be present and we won't be able to decode them. 

Jira issue: CRDB-25100
Epic: CRDB-23559

**Comment by knz** [comment]
Discussed separately - we don't need a version gate because the info column was already available in a previous version. However we want a cluster setting. This will be done in #98274
