### ISSUE TITLE
roachpb: Review critical change in RangeDescriptor.Equals()

### ISSUE THREAD

**Issue by aliher1911** [cockroachdb/cockroach#98158]
In #94896 we switched from using hand written Equals() to gogoproto generatred Equals() on RangeDescriptor.
Previous code was needed to maintain backward compatibility and is no longer applicable.

Double check that generated code is equal to removed code.

Jira issue: CRDB-25109

**Comment by erikgrinaker** [comment]
Reassigning to @pavelkalinnikov since @aliher1911 has enough on his plate.
