### ISSUE TITLE
stability: improve gossip introspection

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#9817]
Prompted by #9749, in which we saw gossip refusing and redirecting lots of clients continuously.

Improve `/debug/gossip`; at the very least it would be on par with the periodic "gossip status" we print in the logs, but it could likely be a tad more verbose. It's likely worth exposing this in the admin ui as well to be more digestible. The [current endpoint](https://gamma.gce.cockroachdb.com:8080/_status/gossip/local) dumps all of the information, but it's hard to look at it if you're not a machine (no human-readable timestamps, etc). The admin ui could easily do this.

Similarly, there are likely some metrics that we should add regarding connection churn, such as the number of redirected clients or times outgoing clients were disconnected.

**Comment by dianasaur323** [comment]
I think it's unlikely we'll get to this before 1.0. Based on my gut feeling, I'm not sure we'll get to this until a serious need comes up. In cases like these, I've been suggested to just knock the milestone off. That's what I'll do for now unless anyone disagrees?

**Comment by petermattis** [comment]
Let's move the milestone to `Later` so that we can search for new issues with no milestone.
