### ISSUE TITLE
stability: optimize timeseries latency

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#9818]
Extracted from https://github.com/cockroachdb/cockroach/issues/9749.

We found that time series are currently fairly large batches (~21k keys), take a fair amount of time to commit to disk, and clog up the command queue.

There are many low hanging fruit here and we should pick some of them.

**Comment by petermattis** [comment]
Not sure where there ~21k keys number came from. With the default settings and the current metrics, a node will write a batch of 242 timeseries keys once every 10 seconds. (FYI, this was 282 keys last week). Each key contains a single sample. Benchmarking writing a batch of this size shows that they take ~0.3ms to write. Combine that with the writing of the raft log entry and we're in the range of ~0.6ms at the RocksDB level. That would translate to 400k timeseries keys/sec which seems more than sufficient.

A more fruitful area for optimization is to bypass the command queue and timestamp cache for merge operations:

> time series merges don't need to touch the command queue at all as we can let them reorder any way they like

and

> Something you said does bring up a good point...why do we need to send time
series through the command queue in the first place. There's no mvcc at
work, so no time stamp cache necessary. We should be bypassing both of
those steps.

**Comment by tschottdorf** [comment]
Yeah, going through the history of this number I find that it has no history. I seem to have a vivid imagination.

**Comment by petermattis** [comment]
Starting a 3-node local cluster with a 100ms metrics collection interval I see the majority of time being spent in `applying command`:

```
0.01ms node.Batch
0.03ms [n1] 242 Merge
0.07ms [n1,s1] executing 242 requests
0.12ms [n1,s1,r1:/{Min-Table/11}] read-write path
0.14ms [n1,s1,r1:/{Min-Table/11}] raft
9.57ms [n1,s1,r1:/{Min-Table/11}] applying command
```

```
0.00ms node.Batch
0.01ms [n1,ts-poll] 242 Merge
0.03ms [n1,ts-poll,s1] executing 242 requests
0.04ms [n1,ts-poll,s1,r1:/{Min-Table/11}] read-write path
0.06ms [n1,ts-poll,s1,r1:/{Min-Table/11}] raft
16.4ms [n1,ts-poll,s1,r1:/{Min-System/"upda…}] applying command
```

**Comment by petermattis** [comment]
Note that the above traces were collected with a patch which disables using the command queue and timestamp cache for merge operations.

**Comment by petermattis** [comment]
Am I reading the trace wrong? I think the traces above are indicating we're spending a long time waiting for raft.

**Comment by tschottdorf** [comment]
It looks like it, though you're also potentially blocking on some mutexes on the way (scheduler, Replica). I'd throw in some more tracepoints.

**Comment by tschottdorf** [comment]
It might also be time to (at least optionally) instrument all mutexes when there is a context around. Likely too expensive for real world, but would be helpful for cases like yours.

**Comment by petermattis** [comment]
@tschottdorf That's what I'm doing right now.

**Comment by petermattis** [comment]
That's weird:

```
0.01ms node.Batch
0.02ms [n1] 242 Merge
0.06ms [n1,s1] executing 242 requests
0.11ms [n1,s1,r1:/{Min-Table/11}] read-write path
0.15ms [n1,s1,r1:/{Min-Table/11}] raft
7.44ms storage/replica.go:1612 [n1,s1,r1:/{Min-Table/11}] prepared command 088ab4062a13556a: maxLeaseIndex=1678 leaseAppliedIndex=1677
7.56ms storage/replica.go:1753 [n1,s1,r1:/{Min-Table/11}] proposing command 088ab4062a13556a: 242 Merge
8.38ms [n1,s1,r1:/{Min-Table/11}] applying command
```

`7.44ms` to get from "raft" to "prepared command". That's way too long. Makes me suspicious that we're waiting on a lock.

**Comment by petermattis** [comment]
Added some trace points around locking and I saw one trace where we spent 6ms waiting for `Replica.raftMu`, but a lot more traces show significant time in Raft:

```
0.01ms node.Batch
0.02ms [n1,ts-poll] 242 Merge
0.07ms [n1,ts-poll,s1] executing 242 requests
0.08ms [n1,ts-poll,s1,r1:/{Min-Table/11}] read-write path
0.1ms  [n1,ts-poll,s1,r1:/{Min-Table/11}] raft
0.11ms [n1,ts-poll,s1,r1:/{Min-Table/11}] locking Replica.raftMu
0.58ms [n1,ts-poll,s1,r1:/{Min-Table/11}] locking Replica.mu
0.63ms storage/replica.go:1612 [n1,ts-poll,s1,r1:/{Min-Table/11}] prepared command 611e5bb789d91934: maxLeaseIndex=7054 leaseAppliedIndex=7051
0.97ms storage/replica.go:1755 [n1,ts-poll,s1,r1:/{Min-Table/11}] proposing command 611e5bb789d91934: 242 Merge
25.6ms [n1,ts-poll,s1,r1:/{Min-Table/11}] applying command
25.6ms [n1,ts-poll,s1,r1:/{Min-Table/11}] execute batch
25.6ms [n1,ts-poll,s1,r1:/{Min-Table/11}] check batch range
31.7ms [n1,ts-poll,s1,r1:/{Min-Table/11}] committing batch
32.2ms [n1,ts-poll,s1,r1:/{Min-Table/11}] update in-memory state
```

**Comment by tschottdorf** [comment]
Raft could in turn also be waiting on a Mutex (the replica_raftstorage.go, I think that's `Replica.mu`?)

**Comment by petermattis** [comment]
True. Btw, I'm wondering if we could extend Raft tracing (at least when `--vmodule=raft=5` is enabled). In `logRaftReady` we're looping over the `raft.Ready` message and finding all of the Raft command IDs. We could extend that to actually returning the command IDs and logging an event if there is a local pending command.

**Comment by petermattis** [comment]
Holy-moly:

```

0ms    node.Batch
0.01ms [n1] 242 Merge
0.04ms [n1,s1] executing 242 requests
0.1ms  [n1,s1,r1:/{Min-System/"upda…}] read-write path
0.12ms [n1,s1,r1:/{Min-System/"upda…}] raft
0.15ms [n1,s1,r1:/{Min-System/"upda…}] locking Replica.raftMu
0.29ms [n1,s1,r1:/{Min-System/"upda…}] locking Replica.mu
0.31ms storage/replica.go:1612 [n1,s1,r1:/{Min-System/"upda…}] prepared command 678c32f3ff7fe79c: maxLeaseIndex=11502 leaseAppliedIndex=11495
0.47ms storage/replica.go:1755 [n1,s1,r1:/{Min-System/"upda…}] proposing command 678c32f3ff7fe79c: 242 Merge
298ms  [n1,s1,r1:/{Min-System/"upda…}] applying command
```

**Comment by tschottdorf** [comment]
> True. Btw, I'm wondering if we could extend Raft tracing (at least when --vmodule=raft=5 is enabled).

Might be worth a try, though `module` logging is intrinsically slow (all `V*` calls have to get the singleton mutex lock and Raft does millions of them) so that I wouldn't expect the timings you get from that to be worth anything.

**Comment by petermattis** [comment]
Here's another one:

```

0.01ms node.Batch
0.03ms [n1] 242 Merge
0.08ms [n1,s1] executing 242 requests
 0.1ms [n1,s1,r1:/{Min-Table/11}] read-write path
0.13ms [n1,s1,r1:/{Min-Table/11}] raft
0.17ms [n1,s1,r1:/{Min-Table/11}] locking Replica.raftMu
2.71ms [n1,s1,r1:/{Min-Table/11}] locking Replica.mu
2.72ms storage/replica.go:1612 [n1,s1,r1:/{Min-Table/11}] prepared command 33ddd52ec5fe3d34: maxLeaseIndex=677 leaseAppliedIndex=675
4.97ms storage/replica.go:1755 [n1,s1,r1:/{Min-Table/11}] proposing command 33ddd52ec5fe3d34: 242 Merge
18.5ms [n1,s1,r1:/{Min-Table/11}] applying command
```

I added some extra Raft logging which revealed:

```
I161011 12:37:47.165819 92 storage/raft.go:140  [n1,s1,r1:/{Min-Table/11}] raft ready
  New Entry[0]: 7/690 EntryNormal [51abbc7b80ff433d] [23714]
  New Entry[1]: 7/691 EntryNormal [33ddd52ec5fe3d34] [23714]
  Outgoing Message[0]: 1->3 MsgApp Term:7 Log:7/689 Commit:689 Entries:[7/690 EntryNormal [51abbc7b80ff433d] [23714]]
  Outgoing Message[1]: 1->2 MsgApp Term:7 Log:7/689 Commit:689 Entries:[7/690 EntryNormal [51abbc7b80ff433d] [23714]]
  Outgoing Message[2]: 1->2 MsgApp Term:7 Log:7/690 Commit:689 Entries:[7/691 EntryNormal [33ddd52ec5fe3d34] [23714]]
  Outgoing Message[3]: 1->3 MsgApp Term:7 Log:7/690 Commit:689 Entries:[7/691 EntryNormal [33ddd52ec5fe3d34] [23714]]
```

Notice that our command (`33ddd52ec5fe3d34`) is the second one in the raft ready. The other command (`51abbc7b80ff433d`) is also a time series batch. A short time later (1.84ms) our commands are committed:

```
I161011 12:37:47.167653 83 storage/raft.go:140  [n1,s1,r1:/{Min-Table/11}] raft ready
  HardState updated: {Term:7 Vote:1 Commit:691 XXX_unrecognized:[]}
  Committed Entry[0]: 7/690 EntryNormal [51abbc7b80ff433d] [23714]
  Committed Entry[1]: 7/691 EntryNormal [33ddd52ec5fe3d34] [23714]
  Outgoing Message[0]: 1->2 MsgApp Term:7 Log:7/691 Commit:690
  Outgoing Message[1]: 1->3 MsgApp Term:7 Log:7/691 Commit:690
  Outgoing Message[2]: 1->2 MsgApp Term:7 Log:7/691 Commit:691
  Outgoing Message[3]: 1->3 MsgApp Term:7 Log:7/691 Commit:691
```

And then we have:

```
I161011 12:37:47.167996 83 storage/replica.go:2521  [n1,s1,r1:/{Min-Table/11}] processing command 51abbc7b80ff433d: maxLeaseIndex=676: 242 Merge
I161011 12:37:47.179153 83 storage/replica.go:2521  [n1,s1,r1:/{Min-Table/11}] processing command 33ddd52ec5fe3d34: maxLeaseIndex=677: 242 Merge
```

It took `11.15ms` to process the first time series batch which then appeared as Raft latency for the one I have the trace for.

**Comment by petermattis** [comment]
Changed `defaultReplicaRaftMuWarnThreshold` to `50ms` and I caught another exceptionally long `ts-poll` trace. The culprit was waiting for `Replica.raftMu` in `Replica.proposeRaftCommand`. This corresponding to the following log messages:

```
W161011 14:03:14.715745 89 storage/replica.go:508  [n1,s1,r6:/{System/"upda…-Table/11}] raftMu: mutex held by github.com/cockroachdb/cockroach/storage.(*Replica).acquireSplitLock.func1 for 238.459315ms (>50ms):
W161011 14:03:14.715789 89 storage/replica.go:508  [n1,s1,r1:/{Min-System/"upda…}] raftMu: mutex held by github.com/cockroachdb/cockroach/storage.(*Replica).handleRaftReady for 238.743517ms (>50ms):
```

Somewhat obviously, when a split occurs we'll impart latency to every operation that touches the range being split. So nothing interesting to do here as far as I can tell.

**Comment by tschottdorf** [comment]
Lots of water under the bridge. Closing.
