### ISSUE TITLE
insights: implement "Cancelled" status for txn insights

### ISSUE THREAD

**Issue by gtr** [cockroachdb/cockroach#98219]
**Is your feature request related to a problem? Please describe.**
Currently, #98217 adds the `status` field to txn insights which is either `Completed` or `Failed`. 

One status from the [Figma mock](https://www.figma.com/file/xpnRkP9cLXERVceRC4cec4/22.2-%26-23.1_SQL-obsrv_query-performance?node-id=3188%3A297704&t=OYIyUP1RacllJFP0-0) that is still missing is the `Cancelled` status.

**Describe the solution you'd like**
Implementing the `Cancelled` status to txn insights and updating the workload insights page to display this status. 

Jira issue: CRDB-25137

**Comment by maryliag** [comment]
No longer a priority
