### ISSUE TITLE
sql: support index hints for inserts and upserts

### ISSUE THREAD

**Issue by rharding6373** [cockroachdb/cockroach#98211]
**Is your feature request related to a problem? Please describe.**
`INSERT`s often require index joins as part of updating the table. In some cases, the optimizer has choices about which kind of index join to use, so it would be useful to allow index hints to force or restrict the index join chosen.

For example, the following plan uses a zigzag join to implement an `INSERT`, however it would be nice to have a way to apply the hint `@{NO_ZIGZAG_JOIN}` (or conversely `@{FORCE_ZIGZAG}` to choose another plan on a query-by-query basis.

```
 └── with
      ├── upsert tbl
      │    ├── arbiter indexes: unique_idx 
      │    └── project
      │         ├── left-join (cross)
      │         │    ├── values
      │         │    ├── inner-join (lookup tbl)
      │         │    │    ├── lookup columns are key
      │         │    │    ├── inner-join (zigzag tbl@idx1 tbl@idx2)
      │         │    │    │    └── filters
      │         │    │    └── filters
      │         │    └── filters (true)
      │         └── projections
      └── project
```

**Describe the solution you'd like**
Support for queries with some kinds of index hints for inserts, for example:

```
INSERT INTO tbl@{NO_ZIGZAG_JOIN} (...) VALUES ...
```

**Describe alternatives you've considered**
In this particular example, zigzag joins can be turned off with a cluster setting, however that disables them for all query planning. There is currently no option to disable them on a query-by-query basis.

Jira issue: CRDB-25134

**Comment by rytaft** [comment]
We should also add support for `UPSERT` (a special version of `INSERT ... ON CONFLICT`). I updated the name of this issue accordingly.
