### ISSUE TITLE
server: TestStatusGetFiles/heap is flaky

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#98213]
Seen here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/8961234?showRootCauses=true&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

```
Failed
=== RUN   TestStatusGetFiles/heap
    status_test.go:434: expected 3 files(s), found 5
    status_test.go:440: expected file name heap3.pprof, found memprof.2023-03-07T21_29_27.320.114523120.pprof
    --- FAIL: TestStatusGetFiles/heap (0.00s)
```

Jira issue: CRDB-25135

**Comment by rytaft** [comment]
Another flake: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/8979194?showRootCauses=true&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

**Comment by msirek** [comment]
Unable to reproduce this using:
```
./dev test pkg/server --filter TestStatusGetFiles --stress --race
```

**Comment by mgartner** [comment]
I think this test is conflicting with another test that is writing files with names like `memprof.2023-03-07T21_29_27.320.114523120.pprof` to the same directory.

**Comment by knz** [comment]
another one https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/9046213?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

**Comment by matthewtodd** [comment]
another one https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/9059175?showRootCauses=false&expandBuildChangesSection=true&expandBuildTestsSection=true

**Comment by cucaroach** [comment]
I think we write a memory profile by default every hour (using that memprof.2023-03-07T21_29_27.320.114523120.pprof format), so in theory if the unit tests are running for an hour this could happen?   Maybe the test should just be less picky.
