### ISSUE TITLE
metrics: prometheus metric/label names should replace periods with colons

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#9822]
Currently, we replace everything with underscores, but the prometheus idiom seems to be specifying hierarchies with colons.

This is pretty easy to change, but might require us to do something unpleasant with existing data in prometheus.

**Comment by mberhault** [comment]
colons are really meant for aggregation levels and various operations in
recording rules.
eg, we currently have "node" and "cluster" level metrics that are
aggregated from "store" and "node" respectively.

Using those to separate the subsystem hierarchy starts to confuse the
syntax.
It's still a possibility though. #9289 already aims to standardize naming,
and colons may be part of that.
