### ISSUE TITLE
sql: significant INSERT performance regression

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#98245]
On my M1 machine, the insert in the SQL in the demo (`cockroach demo --empty`) below takes **less than 1 second** on v22.2.2. On master@`fa6f3f62` it takes **almost 25 seconds**.

```sql
DROP TABLE IF EXISTS a;
CREATE TABLE a (a INT);
CREATE INDEX ON a(a);
INSERT INTO a SELECT i FROM generate_series(1, 100000) g(i);
```

Jira issue: CRDB-25149

**Comment by ajwerner** [comment]
Try `--multitenant=false`. It defaults to false on the release branches.

**Comment by ajwerner** [comment]
Maybe duplicates https://github.com/cockroachdb/cockroach/issues/72341.

**Comment by mgartner** [comment]
Thanks @ajwerner. With `--multitenant=false`, there is no regression. Closing this.
