### ISSUE TITLE
sql: query fails with "disk budget exceeded" in multi-tenant mode

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#98247]
The SQL below succeeds in the demo with `--multitenant=false`, but errors with `--multitenant=true`:

```sql
CREATE TABLE a (a INT);
INSERT INTO a SELECT i FROM generate_series(10, 100000) g(i);
SELECT (SELECT bool_or(a = i) FROM a) FROM generate_series(1, 20) g(i);
```

```
ERROR: temp disk storage: disk budget exceeded: 1048576 bytes requested, 0 currently allocated, 0 bytes in budget
SQLSTATE: 53100
```

Jira issue: CRDB-25151
Epic: CRDB-23559

**Comment by mgartner** [comment]
I'm adding the release-blocker for now.

**Comment by yuzefovich** [comment]
I actually couldn't easily find where we set the SQL temp storage limit in demo (neither in single-tenant nor in multi-tenant mode), so it'd be good to ask @knz whether this behavior is expected.

**Comment by knz** [comment]
I agree we should investigate and i agree this is not a release blocker.

**Comment by knz** [comment]
I'm taking this over in the MT team as a GA-blocker as it's not specific to cockroach demo.
