### ISSUE TITLE
storage: revisit Replica locking

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#9827]
After #9814 is merged, `Replica.mu.internalRaftGroup` is protected by `Replica.raftMu`, but there are many code paths which also grab `Replica.mu`. There are likely other members of `Replica.mu` which are similarly protected by `Replica.raftMu`. At a minimum, the members that are protected by `Replica.raftMu` should be moved out of `Replica.mu` and into a new `Replica.raftMu` struct. This might highlight code paths where we are grabbing `Replica.mu` unnecessarily.

**Comment by nvanbenschoten** [comment]
Closing as this issue isn't providing much value 2 1/2 years later. The locking in Replica is still a mess, but it should improve with refactorings like https://github.com/cockroachdb/cockroach/pull/34061 and the new `storage/replication` package.
