### ISSUE TITLE
SERIAL4 won't respect size constraints

### ISSUE THREAD

**Issue by jaysonsantos** [cockroachdb/cockroach#98281]
**Describe the problem**

Hi there, while using a system that uses 32-bit integers as id in a table, i noticed that using `serial4` or `int4` with default `unique_rowid` (this explicitly says it is 64bit), cockroachdb does not seem to be respecting this decision.

**To Reproduce**

What did you do? Describe in your own words.
create a new table with id serial4 not null, insert with default values and it will be a 64bit value.

```sql
create table public.test
(
    id serial4 not null
);

insert into public.test default values;
select * from public.test;
```
the output will be:

<table border="1" style="border-collapse:collapse">
<tr>
  <th>id</th>
</tr>
<tr>
  <td>846319965186555906</td>
</tr>
</table>

**Expected behavior**
I would expect a maximum number of `4294967295`

**Environment:**
 - CockroachDB version `CockroachDB CCL v22.2.6 (aarch64-unknown-linux-gnu, built 2023/03/03 20:01:10, go1.19.4)`
 - Server OS: 3 linux machines with amd64 and arm64
 - Client app cockroach sql

**Additional context**
To support the app, I just created a sequence for the id.

Jira issue: CRDB-25165

**Comment by Xiang-Gu** [comment]
Adding @cockroachdb/sql-sessions to take a look
