### ISSUE TITLE
stability: time series interval has effect on scraped metrics

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#9830]
We're running omega with a 2h time series interval. This unexpectedly has an effect on some gauges:

![image](https://cloud.githubusercontent.com/assets/5076964/19223034/a5627fce-8e33-11e6-8451-ae9fb4438bf0.png)

We must be updating the gauges from the goroutine which runs every time series interval, when in fact we should also update them when the prometheus endpoint is being scraped. Since these gauges are cheap, perhaps they should be functional gauges.

**Comment by petermattis** [comment]
We record runtime statistics, poll/write time series samples and write node status summaries using the same interval. See `s.ctx.MetricsSampleInterval` in https://github.com/cockroachdb/cockroach/blob/master/server/server.go#L507-L516. It would be easy to untangle these.
