### ISSUE TITLE
tests: panic in TestCrlfmt

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#9832]
Found in: https://teamcity.cockroachdb.com/viewLog.html?buildId=28731&buildTypeId=Cockroach_UnitTests

TestCrlFmt fails `make check` with a panic. No details in the log :cry: 

cc @tamird @jordanlewis @RaduBerinde

**Comment by knz** [comment]
Also for this particular commit, TestCrlfmt does not fail locally :sob:

**Comment by tamird** [comment]
I think this will be fixed by #9825.

**Comment by petermattis** [comment]
@tamird Was this fixed?

**Comment by tamird** [comment]
I think so.
