### ISSUE TITLE
sql/schemachanger: do not fall back when table-level zone configs exist

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#98332]
**Is your feature request related to a problem? Please describe.**
We have blanket rules to fall back to the legacy schema changer when any zone config exists for a table. This is not needed, a table level zone config is generally fine -- only zone configs applied specifically to the primary index add nuance to the work that needs to happen for altering the set of columns or primary key. 

**Describe the solution you'd like**

Model zone configs just a bit more so we can make the fallback cases more narrow.

**Additional context**

There is more general work to deal with the zone config copying to apply to new indexes (in particular primary, but also other new indexes in alter primary key). That work will supersede this low-hanging fruit issue. 

Jira issue: CRDB-25193

**Comment by fqazi** [comment]
Resolved via: https://github.com/cockroachdb/cockroach/pull/98650
