### ISSUE TITLE
Experiment with reading via O_DIRECT, in order to understand disaggregated storage performance better

### ISSUE THREAD

**Issue by joshimhoff** [cockroachdb/cockroach#98345]
Pebble patch: https://github.com/cockroachdb/pebble/pull/2386. Not optimal way of implementing reading via `O_DIRECT` but that might be okay for these purposes.

Experimentation goals:

1. Run benchmarks with no page cache for reads so we can actually compare what latency we get from PD/EBS versus GCS/S3.
2. For the same workload what is the read bandwidth and read IOPS when running with the page cache and with O_DIRECT?
3. Understand importance of different benefits to the block cache:
3a. Read-ahead support. Does a full cluster BACKUP spend higher read IOPS when the OS page cache is off but level bandwidth?
3b. A write-thru cache. Does early KV perform better with OS page cache due to blocks being cached post compaction?
3c. Higher effective cache capacity due to it being a cache of compressed blocks. Does perf fall off earlier in a run of KV without block cache due to lower effective capacity?

1 relates to our goal of achieving predictable user-facing latencies with disaggregated storage.

2 & 3 are more about achieving good thruput per dollar with disaggregated storage. Spending extra read ops / read bandwidth on blob storage costs $$ but doesn't lead to high latencies or other issues since blob storage auto-scales.

Jira issue: CRDB-25211

**Comment by joshimhoff** [comment]
Some preliminary results, CC @RaduBerinde & @sumeerbhola:

1. EBS latency -> 7-15ms, with caveats if you read on. 

I can pull in my branch with time-series for read latency, but can sort of tell latency profile to EBS proper via cluster with no block cache or OS page cache (http://josh-odirect-noblock-0001.roachprod.crdb.io:26258/#/metrics/hardware/cluster) as all reads are hitting EBS proper. *Preliminary results: 7-15ms generally.* Spikes higher occasionally but pretty sure that is because even at a very very low QPS the disks sometimes runs out of read bandwidth / iops. It is possible that 7-15ms is actually not best case perf, in that disks are a bit overloaded even in steady state, but it is at least a lower bound on EBS perf. Like I said up above, I can pull in my branch with time-series for read latency, and then I can take measurements on a cluster with a normal block cache.

2. OS page cache saves a ton of read bandwidth & iops. Control cluster does very little reading from actual disk, while cluster without OS page cache reads up to 60 MB/s & 225 read iops/s.

I ran `./cockroach workload run kv --concurrency=1 --read-percent=50` on a control cluster & a cluster without an OS page cache but with `--cache=25`. Similar read latencies (less than 1ms). Very very different read bandwidth & read iops used. See below screenshots. Control cluster barely uses the disk. Cluster without OS page cache is using a growing amount of read bandwidth & iops per second. Usage spiky; I wonder if it is driven by compaction? Spikes are now 60 MB/s & 225 read iops/s!!!

We'll have to see how this evolves as I adjust the workload; I am running KV & so the OS page cache being a write-thru cache is hugely beneficial to read disk usage.

![image](https://user-images.githubusercontent.com/1443719/224184444-4efcf0da-8c4c-4bfc-bdfb-2b0a58a7b427.png)

![image](https://user-images.githubusercontent.com/1443719/224184419-1a49786a-e326-4d81-8fac-379c8be1c3d9.png)

Links:
- http://josh-odirect-control-0001.roachprod.crdb.io:26258/#/metrics/hardware/cluster
- http://josh-odirect-withblock-0001.roachprod.crdb.io:26258/#/metrics/hardware/cluster
- http://josh-odirect-noblock-0001.roachprod.crdb.io:26258/#/metrics/hardware/cluster

**Comment by joshimhoff** [comment]
> Cluster without OS page cache is using a growing amount of read bandwidth & iops per second. Linear growth! Usage spiky; I wonder if it is driven by compaction? Spikes are now 60 MB/s & 225 read iops/s!!!

I am surprised by the linear growth in read bandwidth & iops per second. What is the reason for this? The workload on the cluster is not growing in this way of course.

**Comment by joshimhoff** [comment]
On both control and no page cache cluster, growing in amount of data written from compaction has leveled out, tho there is still growing amount of variance / spikiness:

<img width="2672" alt="image" src="https://user-images.githubusercontent.com/1443719/224370587-357ef75e-bb43-4cb5-b189-6deecfbfd9b4.png">

<img width="2672" alt="image" src="https://user-images.githubusercontent.com/1443719/224369835-44c79817-03c5-4a71-a633-90d49fcd2b11.png">

Notably, there are periods of linear growth than big drops in data written from compaction. I wonder if that happens after finishing a very big compaction to some lower level in the LSM.

Control cluster continues to read basically no data from the actual disk due to the OS page cache being present:

<img width="2672" alt="image" src="https://user-images.githubusercontent.com/1443719/224370158-70cc032d-3d07-4c2e-8826-bcf84faed904.png">

The no OS page cache cluster continues to read MB/s of data, with variance growing over time, & occasionally dropping in a way that correlates well with compaction activity:

<img width="2672" alt="image" src="https://user-images.githubusercontent.com/1443719/224370373-2d57d5f0-7eba-45d3-9969-40531a4d4e6a.png">

I think it is clear that the OS page cache being a write-thru cache is critical to compaction efficiency.

---

Now I shall get higher quality latency numbers from EBS.

**Comment by joshimhoff** [comment]
> If it flattens out to a number that can fit in the OS page cache, then maybe the OS page cache is hugely important to scalability of compactions. Basically, the OS page cache would store the constantly written early levels of the LSM in memory, reducing usage of the disks considerably, since the OS page cache is a write-thru cache.

As I think more, I think this only makes sense with small stores, low write thruput, or with early levels of the LSM that are being constantly re-written like L1. Having a write-thru cache is useful but eventually you get to a level of scale where relevant data can't fit in memory. At this point, more relevant benefit to OS page cache is read-ahead support, which we know we want for disaggregated storage.

**Comment by joshimhoff** [comment]
Recall the first goal from the top of this ticket: 

> Run benchmarks with no page cache for reads so we can actually compare what latency we get from PD/EBS versus GCS/S3.

Some preliminary data was taken at https://github.com/cockroachdb/cockroach/issues/98345#issuecomment-1462997298 but recall that measurements were of the KV workload itself, hence indirect. So I was going to add direct instrumentation of read latency in. I have done that now.

See [here](http://3.19.245.91:3000/explore?orgId=1&left=%7B%22datasource%22:%22localprom%22,%22queries%22:%5B%7B%22refId%22:%22B%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22localprom%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22histogram_quantile%280.50,%20sum%28rate%28storage_mainstore_readlatency_bucket%5B10m%5D%29%29%20by%20%28le%29%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D,%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22localprom%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22histogram_quantile%280.95,%20sum%28rate%28storage_mainstore_readlatency_bucket%5B10m%5D%29%29%20by%20%28le%29%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D,%7B%22refId%22:%22C%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22localprom%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22histogram_quantile%280.99,%20sum%28rate%28storage_mainstore_readlatency_bucket%5B10m%5D%29%29%20by%20%28le%29%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true,%22interval%22:%22%22%7D,%7B%22refId%22:%22D%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22localprom%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22histogram_quantile%280.10,%20sum%28rate%28storage_mainstore_readlatency_bucket%5B10m%5D%29%29%20by%20%28le%29%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D) for the Grafana. 

**Results: P99 latency read to EBS, with no OS page cache, is 2ms.**

I am still confirming things, but some indications that I haven't made a mistake are:
- This is higher than the 10 microseconds I saw earlier when I forgot to turn off the page cache
- Like all clusters that use `O_DIRECT`, cluster is using a lot of read bandwidth despite a tiny workload that can all fit in the OS page cache [1]

2ms is lower than I expected but I don't think it is necessarily wrong. I guess we can't rule out that caching happens on the EBS server side!!! I will leave the cluster running for a while.

[1] 
<img width="2672" alt="image" src="https://user-images.githubusercontent.com/1443719/224424720-76217129-02cb-4a8a-8ba4-254df8e7e607.png">

**Comment by joshimhoff** [comment]
P99 EBS latency jumped to 15ms or so, after a few days. Will drill into why later.

![image](https://user-images.githubusercontent.com/1443719/224803943-2de21726-f21f-4394-98fb-5e1aaaccc21c.png)

**Comment by sumeerbhola** [comment]
> A basic thing I don't understand is if we expect read bandwidth including cache hits coming from compaction to scale ~linearly with store size, or if flattens out as much of state ends up in low levels that are rarely compacted. If it flattens out to a number that can fit in the OS page cache, then maybe the OS page cache is hugely important to scalability of compactions. 

The read bandwidth for compactions is roughly the incoming write rate into the LSM multiplied by the write amplification, so it is not a function of the store bytes. When we start from an empty store, the write amp increases over time as more levels get used, so the read bandwidth also increases (so there is an indirect effect of the store size).

The other question is that even if we have reached steady state in read bandwidth for compactions, what is the working set, since that matters for the effectiveness of the page cache. For the uniform-randomly distributed KV workload, I wouldn't be surprised if the working set is a function of the store size -- though I have no data to back this up, other than anecdotal observations that after running KV0 for a hour+, the read bandwidth to block storage spikes and starts approaching the write bandwidth -- which suggests that the page cache has become somewhat ineffective in serving compaction reads.

**Comment by joshimhoff** [comment]
Trying to understand why read BW is much higher than write BW, as @sumeerbhola indicated on slack that this surprised him.

`rocksdb_compacted_bytes_read` tracks the v particular shape of `node_disk_read_bytes_total` very closely, including the linear increase then drop down then linear increase again. In magnitudes tho, they are different. `node_disk_read_bytes_total` -> 26 MB/s while `rocksdb_compacted_bytes_read` -> < 1 MB/s.

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/1443719/226692319-3624ed86-271c-4e85-a173-2b4681899dad.png">

Source: http://18.116.240.107:3000/explore?orgId=1&left=%7B%22datasource%22:%22localprom%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22localprom%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22rate%28node_disk_read_bytes_total%5B10m%5D%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%221678399715000%22,%22to%22:%221678429694000%22%7D%7D&right=%7B%22datasource%22:%22localprom%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22localprom%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22rate%28rocksdb_compacted_bytes_read%5B10m%5D%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%221678399708000%22,%22to%22:%221678429694000%22%7D%7D

`rocksdb_block_cache_misses` ALSO tracks the v particular shape of `node_disk_read_bytes_total`. But again, magnitudes don't line up. Miss rate at peak times 32 KB -> ~ 1 MB/s. Too low for user-facing reads to explain the high read BW.

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/1443719/226692632-ccdc1a5c-b687-4cd9-a564-c34b41c4b0c2.png">

Source: http://18.116.240.107:3000/explore?orgId=1&left=%7B%22datasource%22:%22localprom%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22localprom%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22rate%28node_disk_read_bytes_total%5B10m%5D%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%221678399715000%22,%22to%22:%221678429694000%22%7D%7D&right=%7B%22datasource%22:%22localprom%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22localprom%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22rate%28rocksdb_block_cache_misses%5B10m%5D%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%221678399708000%22,%22to%22:%221678429694000%22%7D%7D

One thing I wondered if discrepancy is related to what Peter commented on earlier:
> My recollection is that rocksdb takes care to ensure that sstable blocks start on page (4k) boundaries when the blocks are written and are a multiple of the 4k page size.

My mental model here is currently weak. Other than ensuring pebble block sizes are a multiple of page boundaries, is there anything to do? One concrete question that follows from that question is: Do files always start at a page boundary? Even with the holes in my mental model, I would expect that lack of alignment would lead to reading an extra 4k page per read or so, which shouldn't lead to so much higher read BW than write BW, given that pebble block size is 32 KB IIUC.

Another possible explanation is though the implementation of `ReadAt` at https://github.com/cockroachdb/cockroach/issues/92869 doesn't have any flagrant correctness issue (as cluster has been running for many hours without crash), it has some terrible bug that leads to reading much more data than is needed.

One last thing is I also see a discrepancy between `node_disk_written_bytes_total` and `rocksdb_compacted_bytes_written` (which is not explained by `rocksdb_flushed_bytes`). I don't think I changed any relevant code in the write path.

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/1443719/226697780-2f58b9b0-3f93-4512-b9db-097864c14e28.png">

Source: http://18.116.240.107:3000/explore?orgId=1&left=%7B%22datasource%22:%22localprom%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22localprom%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22rate%28node_disk_written_bytes_total%5B10m%5D%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%221678399616808%22,%22to%22:%221678425163061%22%7D%7D&right=%7B%22datasource%22:%22localprom%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22localprom%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22rate%28rocksdb_compacted_bytes_written%5B10m%5D%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D

Overall, I would say I don't currently have a good understanding of why read BW is much higher than write BW. I think I'll also ask Sumeer how hard I should push at trying to get to the bottom of this.

**Comment by joshimhoff** [comment]
These two charts are interesting:

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/1443719/226713207-72214db6-de34-4be8-8580-435c38a23302.png">

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/1443719/226713253-5c9391c1-c9ad-4203-88db-22a8a5dd8262.png">

First, there are periods where read BW & write BW are very similar. Second, the growth in read BW is correlated with changes in the shape of the LSM.

In particular, at 19:00, read BW sharply drops. At the same time, files in L0 drops, and we start writing to L5 instead of L6.

Source: http://18.116.240.107:3000/explore?orgId=1&left=%7B%22datasource%22:%22localprom%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22localprom%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22rate%28node_disk_read_bytes_total%5B10m%5D%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true,%22hide%22:false%7D,%7B%22refId%22:%22B%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22localprom%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22rate%28node_disk_written_bytes_total%5B10m%5D%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%221678398023853%22,%22to%22:%221678429694884%22%7D%7D&right=%7B%22datasource%22:%22localprom%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22localprom%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22storage_l0_num_files%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true,%22hide%22:false%7D,%7B%22refId%22:%22B%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22localprom%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22storage_l5_level_size%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true,%22hide%22:false%7D,%7B%22refId%22:%22C%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22localprom%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22storage_l6_level_size%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%221678398023000%22,%22to%22:%221678429694000%22%7D%7D

I still don't understand the discrepancy between read BW & write BW but I wonder if above will help us get to the bottom of it.

**Comment by joshimhoff** [comment]
One last thing I notice is:
- Both read BW from complication AND write BW from compaction have the same interesting shape which as per last message is correlated with changes in LSM shape
- But only read BW at a system level tracks that shape; write BW at a system level is more constant

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/1443719/226917413-c18049a2-160b-4215-af55-7ccb195b9cc6.png">

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/1443719/226917499-c82b7680-d0af-47aa-b9ea-9f7b330ba357.png">

Source: http://18.116.240.107:3000/explore?orgId=1&left=%7B%22datasource%22:%22localprom%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22localprom%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22rate%28node_disk_read_bytes_total%5B10m%5D%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true,%22hide%22:false%7D,%7B%22refId%22:%22B%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22localprom%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22rate%28node_disk_written_bytes_total%5B10m%5D%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true,%22hide%22:true%7D%5D,%22range%22:%7B%22from%22:%221678398023853%22,%22to%22:%221678429694884%22%7D%7D&right=%7B%22datasource%22:%22localprom%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22localprom%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22storage_l0_num_files%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true,%22hide%22:true%7D,%7B%22refId%22:%22B%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22localprom%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22storage_l5%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true,%22hide%22:true%7D,%7B%22refId%22:%22C%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22localprom%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22rate%28rocksdb_compacted_bytes_read%5B10m%5D%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true,%22hide%22:false%7D,%7B%22refId%22:%22D%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22localprom%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22rate%28rocksdb_compacted_bytes_written%5B10m%5D%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true,%22hide%22:true%7D%5D,%22range%22:%7B%22from%22:%221678398023000%22,%22to%22:%221678429694000%22%7D%7D

I can't explain this either exactly, tho it is the case that only reads are being done via `O_DIRECT`.

**Comment by joshimhoff** [comment]
To summarize the mysteries:

1. Why is read BW higher than write BW?
2. Why do our counters that track BW coming from various workloads such as compaction not sum to a number much lower than BW reported by system?

**Comment by joshimhoff** [comment]
I have been looking at `strace` output this AM, and I think I found a bug in my code that leads to doing unnecessarily large reads. I think this is the cause of the both 1 (higher read BW than write BW) & 2.

**Comment by joshimhoff** [comment]
Earlier I noted that EBS p99 latency jumped from 2ms to 15ms (https://github.com/cockroachdb/cockroach/issues/98345#issuecomment-1466789265). Now that I know about the bug in the `O_DIRECT` impl, I bet this was caused by running out of BW on the disk. Graph shows strong correlation with jump in read BW.

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/1443719/227025115-c05ff70a-95c0-4129-92d4-22315bd97b49.png">

Will confirm by checking read BW ceiling & also running a new cluster with fixed `O_DIRECT` impl.

**Comment by joshimhoff** [comment]
With bug fix in (https://github.com/cockroachdb/pebble/pull/2412), read BW is much much lower. It is less than write BW. Not sure why it is less than write BW exactly, tho might be fine. Maybe workload I am running is leading to large usage associated with writing the WAL, or maybe pebble block cache is reducing read BW a bit.

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/1443719/227342878-7c1101d0-644f-47f8-b71e-51ff9c790a56.png">

We also observe much more agreement between compaction read BW as measured by CRDB & read BW measured by system, which is reassuring.

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/1443719/227343394-a26f29aa-4a6b-4d80-b7de-4a53e1581067.png">

Source: http://3.144.126.120:3000/explore?orgId=1&left=%7B%22datasource%22:%22localprom%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22localprom%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22rate%28node_disk_read_bytes_total%5B10m%5D%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D&right=%7B%22datasource%22:%22localprom%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22localprom%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22rate%28rocksdb_compacted_bytes_read%5B10m%5D%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true,%22hide%22:false%7D,%7B%22refId%22:%22B%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22localprom%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22rate%28node_disk_written_bytes_total%5B10m%5D%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D

99p latency to EBS is 0.3ms and 99.9p is 0.6ms according to this latest round of testing.

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/1443719/227344056-e13ffcd1-8430-47bc-9038-2890f219f30e.png">

Source: http://18.118.213.251:3000/explore?orgId=1&left=%7B%22datasource%22:%22localprom%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22localprom%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22histogram_quantile%280.99,%20sum%28rate%28storage_mainstore_readlatency_bucket%5B10m%5D%29%29%20by%20%28le%29%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D&right=%7B%22datasource%22:%22localprom%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22localprom%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22rate%28rocksdb_block_cache_misses_userfacing%5B10m%5D%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D

I will keep thee clusters running for a bit, in case anything changes. If not, I will close this issue. 

I think we have learned than EBS is much faster than S3, even without a block cache. I think we also have learned various things about both the OS page cache and direct IO, in case we ever want to go the route of using direct IO in CRDB itself.
