### ISSUE TITLE
insights: consider exempting some statements from "slow execution" insight

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#98358]
Here is an example of the "slow execution" insight on `SET vectorize = _` statement:
![Screenshot 2023-03-09 at 4 51 08 PM](https://user-images.githubusercontent.com/5135385/224195080-db823a69-a073-4012-aef6-3ce7b4f1ad8f.png)

This is not really actionable nor the user can speed up such simple statements in any way, so I think we should exclude statements like this from the "slow insights" page.

(This example was seen when the cluster was overloaded, so even simple statements like `SET` were taking longer than 100ms.)

Jira issue: CRDB-25436
Epic: CRDB-25476

**Comment by maryliag** [comment]
@yuzefovich do you think we can add a filter for all `SET` or is there any `SET` case that would still make sense to make recommendations?

**Comment by yuzefovich** [comment]
I think all `SET`s can be excluded, perhaps some other types of statement too.

**Comment by maryliag** [comment]
if you have any other suggestions to remove, happy to make the changes :)
