### ISSUE TITLE
workload/ycsb: CLI doesn't allow YCSB key to be ordered, only hashed 

### ISSUE THREAD

**Issue by eivanov89** [cockroachdb/cockroach#98367]
**Describe the problem**

There is a CLI option to control YCSB workloads:
```
--insert-hash                       Key to be hashed or ordered. (default true)
```
It is set to true and thus no way to set to false. It looks like either default should be false (as should be for any flag-option, but it will make key to be ordered) or option should be --insert-ordered with default false. 

[Code](https://github.com/cockroachdb/cockroach/blob/ad11b6b226ffc86c21fbb7459816e0cc453e5935/pkg/workload/ycsb/ycsb.go#L130). 

Jira issue: CRDB-25229

**Comment by ajwerner** [comment]
You can set it to false with `--insert-hash=false`, given that I think that solves the problem, I'm going to close this.

**Comment by ajwerner** [comment]
> as should be for any flag-option

I don't think this is a valid claim. It is perhaps confusing that boolean flags which default to true need an argument value, but it doesn't make them useless.

**Comment by eivanov89** [comment]
> You can set it to false with `--insert-hash=false`, given that I think that solves the problem, I'm going to close this.

Oh, that's surprising. I thought this works the same way as in Python's argparse. Thank you for your reply.

**Comment by ajwerner** [comment]
For go [flags](https://pkg.go.dev/flag), the docs say: 
> You must use the -flag=false form to turn off a boolean flag.

**Comment by eivanov89** [comment]
> For go [flags](https://pkg.go.dev/flag), the docs say:
> 
> > You must use the -flag=false form to turn off a boolean flag.

Aha, I see. Sorry for bothering, I've never developed anything in Go. The approach with -flag=false seems to me a very non-Unix.
