### ISSUE TITLE
monitoring: export clock-offset metrics

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#9839]
It seems thore were removed in: https://github.com/cockroachdb/cockroach/commit/5ad932684ece3ddde2184255f9cafcd9740e21e1

We should have some metrics (we currently have low/high offset, but they're not actually set).

**Comment by tamird** [comment]
What metrics would you like to emit? These were removed in `5ad9326` because that stuff was reworked and the metrics we had prior to that reworking no longer made sense.
