### ISSUE TITLE
kvserver: TestProcessSplitAfterRightHandSideHasBeenRemoved flaked on master

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#98409]
See CI failure [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=9007751&buildTypeId=Cockroach_BazelEssentialCi). 

Jira issue: CRDB-25250

**Comment by nvanbenschoten** [comment]
The test failed with a timeout and we have not seen it fail elsewhere.

```
roachprod create $USER-stress -n 20 --gce-machine-type=n1-standard-8 --local-ssd=false
dev roachprod-stress ./pkg/kv/kvserver --cluster=$USER-stress -- -test.run=TestProcessSplitAfterRightHandSideHasBeenRemoved
```

I let the above run for 20,000 iterations on 2ff4f2f91780daac6f6a3fefd0fe96acb649d33f without hitting a failure. I'll close this for now, but we can investigate further if it fails again.
