### ISSUE TITLE
kvserver: default span config is used temporarily on startup

### ISSUE THREAD

**Issue by kvoli** [cockroachdb/cockroach#98421]
**Describe the problem**

In #98385 we saw the default span config being used in the replicate queue for a short period. During this period, replicas were removed from ranges due to the allocator believing the replication factor should be x3 instead of the real factor x9.

This points to a wider issue where it is possible to use the default span config in place of the real span config. This condition is checked for in the [merge queue ](https://github.com/cockroachdb/cockroach/blob/51f8f8e84d3075643bd8725f7e10d9af41fa4cbb/pkg/kv/kvserver/merge_queue.go#L133-L138), however not in other places that should:

- replicate queue
- store rebalancer
- split queue
- mvcc gc queue

**To Reproduce**

See this [comment](https://github.com/cockroachdb/cockroach/issues/98385#issuecomment-1464611356).

**Expected behavior**

The default span config is never used in the above places so that incorrect decisions don't occur.

Jira issue: CRDB-25257

**Comment by irfansharif** [comment]
(Not a GA-blocker, since the bug exists in 22.2.)
