### ISSUE TITLE
Zipfian/latest YCSB workloads fail or have poor performance when there is high load

### ISSUE THREAD

**Issue by eivanov89** [cockroachdb/cockroach#98438]
Hi, I try to measure cockroach 22.2.6 performance. I use the YCSB benchmark you have embedded into the cockroach binary. I have a 3 x86 servers:
* 128 cores
* 4 NVMe disks.
* Ubuntu 20.04.3
* timesyncd
* each server in its own "virtual" region (for now I use collocated servers)

On each server I run 4 cockroach instances: each in its own 32 core taskset and with single disk. Previously I tried a cluster with 8 servers. I failed to achieve a reasonable performance in zipfian workloads using 8 128-core 4-disks cockroach nodes. When I changed setup to multiple small nodes per server I got a much better result.

Because of [this](https://cockroachdb.slack.com/archives/CP4D9LD5F/p1670603623885789) and [this](https://cockroachdb.slack.com/archives/CP4D9LD5F/p1671565684959599?thread_ts=1671524396.021959&cid=CP4D9LD5F) issues I have set _gc.ttlseconds_ to 600 seconds.

Datasize is 2B rows. After data import cockroach reports 6.3 TiB of used capacity and around 11K ranges. Here is a command to load the dataset:
`> cockroach workload init ycsb --data-loader=IMPORT --drop --insert-count 2000000000 --insert-hash=false postgresql://root@localhost:26257?sslmode=disable --concurrency 512 --workload a
`
Single YCSB instance is not enough to produce 100% cluster utilization. Hence I run 16 YCSB instances on 16 collocated servers. Each instance has concurrency 512. There is an own HAProxy on each YCSB server (it allows to not mess with its configuration). Note that there are no issues when I run single YCSB instance: all workloads work, but single YCSB against such cluster is just a toy.

If I run uniform distribution I get results without any issues. Cluster utilization is 100%. With zipfian (and latest) I constantly fall into troubles. This time the problem is the following. For workload A and F zipfian completely fails. In case of workload b only one YCSB node produces result: 4K Op/s, time 616000 ms, latency 99% 50 ms. Workload C: 320K Op/s, latency 99% 604 ms. Workload D: 369K Op/s latency 99% 403 ms. Zipfian C and D have pretty good numbers even in comparison with uniform results.

Workload A. One YCSB instance reported:
```
11 Mar 2023 11:21:48 AM UTC - start
I230311 11:22:04.191758 1 workload/cli/run.go:427  [-] 1  creating load generator...
I230311 11:22:13.815264 1 workload/cli/run.go:458  [-] 2  creating load generator... done (took 9.623504745s)
Error: pq: result is ambiguous: error=ba: Put [/Table/109/1/"user10"/1/1,/Min), EndTxn(parallel commit) [/Table/109/1/"user10"/1/1], [txn: a0156f07] RPC error: rpc error: code = Unavailable desc = error reading from server: read tcp [vla-dev04-000]:51472->[vla-dev04-002]:26259: read: connection reset by peer [propagate]
```

Meanwhile none of the nodes crashed. Network is rocksolid between them.

Other nodes:
```
I230311 11:22:04.493558 1 workload/cli/run.go:427  [-] 1  creating load generator...
I230311 11:22:13.923788 1 workload/cli/run.go:458  [-] 2  creating load generator... done (took 9.430228347s)
Error: sql: connection is already closed
```

I failed to grep a0156f07 in logs. In logs of first node on vla-dev04-000 I see:
```
W230311 11:20:41.132821 550 2@rpc/clock_offset.go:226 ⋮ [n1,rnode=63,raddr=‹vla-dev04-001:26257›,class=system,heartbeat] 27505  latency jump (prev avg 1.30ms, current 3.05ms)
W230311 11:20:59.005373 2617 2@rpc/clock_offset.go:226 ⋮ [n1,rnode=4,raddr=‹vla-dev04-001:26257›,class=system,heartbeat] 27506  latency jump (prev avg 1.25ms, current 2.88ms)
W230311 11:21:15.648174 2816 2@rpc/clock_offset.go:226 ⋮ [n1,rnode=5,raddr=‹vla-dev04-002:26257›,class=default,heartbeat] 27507  latency jump (prev avg 1.14ms, current 3.82ms)
I230311 11:21:17.273577 1494 sql/sqlstats/persistedsqlstats/flush.go:71 ⋮ [n1] 27508  flushing 29 stmt/txn fingerprints (204800 bytes) after 2.516µs
W230311 11:22:28.203761 4031 2@rpc/clock_offset.go:226 ⋮ [n1,rnode=8,raddr=‹vla-dev04-002:26259›,class=system,heartbeat] 27509  latency jump (prev avg 0.98ms, current 4018.48ms)
W230311 11:22:29.361122 279282 kv/kvserver/closedts/sidetransport/receiver.go:139 ⋮ [n1] 27510  closed timestamps side-transport connection dropped from node: 8
W230311 11:22:31.916461 169079875 kv/kvserver/raft_transport.go:602 ⋮ [n1] 27511  while processing outgoing Raft queue to node 8: send msg error: ‹EOF›:
W230311 11:22:31.917227 169124364 google.golang.org/grpc/grpclog/component.go:41 ⋮ [-] 27512  ‹[core]›‹[Channel #235 SubChannel #236] grpc: addrConn.createTransport failed to connect to {›
W230311 11:22:31.917227 169124364 google.golang.org/grpc/grpclog/component.go:41 ⋮ [-] 27512 +‹  "Addr": "vla-dev04-002:26259",›
W230311 11:22:31.917227 169124364 google.golang.org/grpc/grpclog/component.go:41 ⋮ [-] 27512 +‹  "ServerName": "vla-dev04-002:26259",›
W230311 11:22:31.917227 169124364 google.golang.org/grpc/grpclog/component.go:41 ⋮ [-] 27512 +‹  "Attributes": null,›
W230311 11:22:31.917227 169124364 google.golang.org/grpc/grpclog/component.go:41 ⋮ [-] 27512 +‹  "BalancerAttributes": null,›
W230311 11:22:31.917227 169124364 google.golang.org/grpc/grpclog/component.go:41 ⋮ [-] 27512 +‹  "Type": 0,›
W230311 11:22:31.917227 169124364 google.golang.org/grpc/grpclog/component.go:41 ⋮ [-] 27512 +‹  "Metadata": null›
W230311 11:22:31.917227 169124364 google.golang.org/grpc/grpclog/component.go:41 ⋮ [-] 27512 +‹}. Err: connection error: desc = "transport: Error while dialing cannot reuse client connection"›
W230311 11:22:32.060089 2617 2@rpc/clock_offset.go:226 ⋮ [n1,rnode=4,raddr=‹vla-dev04-001:26257›,class=system,heartbeat] 27513  latency jump (prev avg 1.00ms, current 3.21ms)
W230311 11:22:32.281978 2278 2@rpc/clock_offset.go:226 ⋮ [n1,rnode=3,raddr=‹vla-dev04-001:26260›,class=default,heartbeat] 27514  latency jump (prev avg 1.02ms, current 7.26ms)
W230311 11:22:36.376668 4031 2@rpc/clock_offset.go:226 ⋮ [n1,rnode=8,raddr=‹vla-dev04-002:26259›,class=system,heartbeat] 27515  latency jump (prev avg 379.21ms, current 1446.21ms)
W230311 11:22:37.459724 2155 2@rpc/clock_offset.go:226 ⋮ [n1,rnode=2,raddr=‹vla-dev04-000:26260›,class=default,heartbeat] 27516  latency jump (prev avg 0.88ms, current 6.48ms)
W230311 11:22:45.379084 2537 2@rpc/clock_offset.go:226 ⋮ [n1,rnode=63,raddr=‹vla-dev04-002:26257›,class=system,heartbeat] 27517  latency jump (prev avg 1.08ms, current 11.71ms)
W230311 11:22:54.053661 5892 2@rpc/clock_offset.go:226 ⋮ [n1,rnode=2,raddr=‹vla-dev04-000:26260›,class=system,heartbeat] 27518  latency jump (prev avg 1.73ms, current 5.40ms)
W230311 11:23:26.190282 4717 2@rpc/clock_offset.go:226 ⋮ [n1,rnode=12,raddr=‹vla-dev04-002:26260›,class=default,heartbeat] 27519  latency jump (prev avg 0.98ms, current 1.52ms)
W230311 11:23:33.719988 2816 2@rpc/clock_offset.go:226 ⋮ [n1,rnode=5,raddr=‹vla-dev04-002:26257›,class=default,heartbeat] 27520  latency jump (prev avg 1.01ms, current 2.01ms)
W230311 11:23:36.560282 2155 2@rpc/clock_offset.go:226 ⋮ [n1,rnode=2,raddr=‹vla-dev04-000:26260›,class=default,heartbeat] 27521  latency jump (prev avg 400.96ms, current 1919.25ms)
W230311 11:23:52.093131 169091188 kv/kvclient/kvcoord/dist_sender.go:1627 ⋮ [n1,client=[2a02:6b8:c34:14:0:1354:eb1e:f44a]:64472,user=root] 27522  slow range RPC: have been waiting 74.35s (1 attempts) for RPC Get [/Table/109/1/‹"user10"›/‹3›/‹1›,/Min), [txn: bc50c6b3], [can-forward-ts] to r13949:‹/Table/109{-/1/"user1000089227"}› [(n6,s6):1, (n2,s2):2, (n8,s8):3, next=4, gen=153]; resp: ‹(err: <nil>), *roachpb.GetResponse›
W230311 11:24:03.381284 169111127 kv/kvclient/kvcoord/dist_sender.go:1627 ⋮ [n1,client=[2a02:6b8:c0e:70d:0:1354:9b0c:8986]:32936,user=root] 27523  slow range RPC: have been waiting 85.70s (1 attempts) for RPC Get [/Table/109/1/‹"user10"›/‹3›/‹1›,/Min), [txn: 9cf87135], [can-forward-ts] to r13949:‹/Table/109{-/1/"user1000089227"}› [(n6,s6):1, (n2,s2):2, (n8,s8):3, next=4, gen=153]; resp: ‹(err: <nil>), *roachpb.GetResponse›
W230311 11:24:05.988960 169110576 kv/kvclient/kvcoord/dist_sender.go:1627 ⋮ [n1,client=[2a02:6b8:c0e:716:0:1354:9b0c:8b76]:51852,user=root] 27524  slow range RPC: have been waiting 64.89s (1 attempts) for RPC Scan [/Table/109/1/‹"user0"›/‹1›/‹1›,/Table/109/1/‹"user0"›/‹10›/‹2›), [txn: f36b99a2], [can-forward-ts] to r24895:‹/Table/109/1/"user{0"-1000089227"}› [(n6,s6):1, (n2,s2):2, (n8,s8):3, next=4, gen=154, sticky=1678534067.425325229,0]; resp: ‹(err: <nil>), *roachpb.ScanResponse›
...
W230311 11:24:08.344287 169089765 kv/kvclient/kvcoord/dist_sender.go:1627 ⋮ [n1,client=[2a02:6b8:c34:15:0:1354:eb1f:2eae]:52090,user=root] 27534  slow range RPC: have been waiting 67.28s (1 attempts) for RPC Scan [/Table/109/1/‹"user1"›/‹1›/‹1›,/Table/109/1/‹"user1"›/‹10›/‹2›), [txn: b86d631b], [can-forward-ts] to r24895:‹/Table/109/1/"user{0"-1000089227"}› [(n6,s6):1, (n2,s2):2, (n8,s8):3, next=4, gen=154, sticky=1678534067.425325229,0]; resp: ‹(err: <nil>), *roachpb.ScanResponse›
```

According metrics I see some transactions between 11:22 and 11:25. Just 7K op/s (3.5K selects and 3.5K updates). On _runnable goroutines_ I see that 2 cockroach nodes did something. According your _clock offset_ graph the highest offset is 0.67 ms. When workload failed I saw 1K _not lease holder_ and 1K _replica_ errors (with 19K _RPCs_/s sent and 12K _local fast path_ / second). On same two nodes _heartbeat_ jumped to 0.9s, but I see the same for uniform (and it works).

On _replication queue_ graph I see ~ 3 _successfull actions_ / second and 2.4 _leases transferred_ per second (while nothing in uniform case).

There is 4K _slow distSender RPCs_ and single peak with 364 _slow latch acqusitions_.

vla-dev04-000 node has 75% CPU utilization, while others about 15%.

Could you please provide some help with this issue? I believe it might be some issue with default configuration.
 

Jira issue: CRDB-25270

**Comment by eivanov89** [comment]
If I reduce the number of YCSB instances from 16 to 8 and set concurrency to 256 then I'm able to run zipfian/latest workloads. I still get pretty good numbers for C and D (with full CPU utilization) and very poor result for the rest. E.g. zipfian workload a result is 15K Op/s with latency 99% 2416 ms. In comparison workload c gives 394K Op/s with reasonable 48 ms in 99%.

**Comment by erikgrinaker** [comment]
Hi,

From an initial glance, this sounds like some of the nodes or ranges get overloaded. Zipfian distributions will produce hot spots, in particular with `--insert-hash=false` where I believe the hottest keys will be sequential in the keyspace and thus end up in the same ranges. Furthermore, for write-heavy workloads (e.g. A and F) with Zipfian distributions there will also be significant contention between concurrent writers.

You may want to try with `--insert-hash=true`, and gradually ramp up the load to find out where the cluster saturates and throughput collapses.

**Comment by erikgrinaker** [comment]
PS: you may also want to pre-split the keyspace into many ranges to make sure the workload can be properly distributed. Try e.g. `--splits=1000` or `--splits=10000`.

**Comment by eivanov89** [comment]
Hi Erik,

> PS: you may also want to pre-split the keyspace into many ranges to make sure the workload can be properly distributed. Try e.g. `--splits=1000` or `--splits=10000`.

After loading the data I already have 11K ranges. For 384 cores in total this number sounds reasonable.

> You may want to try with `--insert-hash=true`, and gradually ramp up the load to find out where the cluster saturates and throughput collapses.
But with hashed keys I will loose efficient key ranges (or key ranges at all). Or do I miss something at this point?

**Comment by erikgrinaker** [comment]
>> PS: you may also want to pre-split the keyspace into many ranges to make sure the workload can be properly distributed. Try e.g. `--splits=1000` or `--splits=10000`.
>
>After loading the data I already have 11K ranges. For 384 cores in total this number sounds reasonable.

Ah, yes. That should be sufficient.

>> You may want to try with `--insert-hash=true`, and gradually ramp up the load to find out where the cluster saturates and throughput collapses.
>
>But with hashed keys I will loose efficient key ranges (or key ranges at all). Or do I miss something at this point?

That's true, for ranged reads. But if I understand this benchmark correctly, it will also mean that the Zipfian distribution is sequential in the keyspace, i.e. all of the hot keys will end up concentrated at the start of the keyspace, in a handful of ranges on a handful of nodes. A Zipfian load distribution across a randomly ordered set of keys (i.e. hashed keys) will be much better distributed across ranges/nodes. I'd have to read the benchmark code to confirm the exact behavior, but it's worth a try.

**Comment by eivanov89** [comment]
> A Zipfian load distribution across a randomly ordered set of keys (i.e. hashed keys) will be much better distributed across ranges/nodes

By mistake I used hashed keys, when tested cockroach on 8 nodes. I can't doublecheck soon though. And results for A-C and F for zipfian are 17K, 18K, 724K and 14K. 

> it will also mean that the Zipfian distribution is sequential in the keyspace, i.e. all of the hot keys will end up concentrated at the start of the keyspace, in a handful of ranges on a handful of nodes.

Sorry, but I think this is an important testcase. It is only a problem if there are just few hot keys (another testcase though). It is interesting to see how DB handles hotspots. It can try to split by load hot ranges and balance them across the nodes. IMHO it's kind of cheating using hashing for zipfian/latest workloads in tests, while it's absolutely production solution in practice :)

**Comment by kvoli** [comment]
> I agree. We do load-based splits and rebalancing, but it can be slow to react, particularly if all the hot keys are initially concentrated in a single range. Perhaps @kvoli or @andrewbaptist have some further insights here.

We do performance testing with a zipfian distribution (no hashing) for the `kv` workload. The cluster distributes load reasonably well for this type of distribution.

For latest distributions, such as YCSB-D (unhashed), Cockroach does not handle load distribution that well. Latest distributions require some degree of load distribution preparedness, either predictive (e.g. splitting ahead of the frontier and distributing) or pre-distribution (e.g. hashing).

**Comment by eivanov89** [comment]
With a zipfian distribution do you have all computations on the same node with the hot range? I mean do you have a separation between key-value reading and SQL execution or are they always on the same node with the range? That would explain why almost all CPU is on the single node.

**Comment by eivanov89** [comment]
> We try to schedule SQL execution on the node that contains the data, to avoid unnecessary network transfers and to distribute processing of analytical queries, but I'm not sure if we always do that for trivial point queries. Of course, the client connection handling (including SQL query parsing, planning, optimization etc) is done on the node that the client connects to.

Do I get it right, that a node handles connection: it compiles SQL to some programme, which is then executed on the range containing the data? So that the range entity spends its CPU on both reading key-value and executing the programme?

I attach results for my setup. Recall that size of workset is 2B and keys ordered. I use 8 YCSB-servers with concurrency 256. If I use 16x512 then zipfian and latest don't work. @erikgrinaker and @kvoli, do you find numbers reasonable? Your DB performs awesome in uniform distribution test, thus I'm in doubt regarding zipfian. And I agree that for latest and ordered it's pretty expected to have these number.

![2023-03-14-cockroach-2b-ordered](https://user-images.githubusercontent.com/3464685/225126052-12da90dc-3ed7-4ec6-9f28-1719d7eb1150.png)

**Comment by kvoli** [comment]
> [...] do you find numbers reasonable?

We don't commonly benchmark YCSB with a different request distribution than what is defined in the YCSB specification [^1]. It appears the benchmarks you are running are overriding the request distribution? I can't provide a strong opinion whether those numbers are reasonable, however my suspicion is that they are not.

For comparison, we notice minimal difference in performance (ops/s) between running with `--insert-hash` as `true` and `false` for every benchmark aside from D. The difference on D is expected for the reasons mentioned in my previous reply.

Do you have results using the default request distributions for each workload? 

[^1]: https://dl.acm.org/doi/10.1145/1807128.1807152

**Comment by eivanov89** [comment]
Hi again, I continue the experiments with YCSB workload A. Here are load and run commands (workload defaults are hashed keys and zipfian distribution):
`
./cockroach workload init ycsb --data-loader=IMPORT --drop --insert-count 300000000 "postgresql://root@localhost:26257?sslmode=disable" --concurrency 512 --workload a

./cockroach workload run ycsb --workload a --insert-count 300000000 --max-ops 100000000 --display-every 10s "postgresql://root@localhost:26257?sslmode=disable" --concurrency 128
`

I tried several setups:
* each server with single YCSB instance (128 cores, 4 disks)
* multiple Cockroach instances per server, i.e. one per disk in tasksets - each node in UI is displayed as 32 core node
* multiple Cockroach instances per server with GOMAXPROCS set to 32 - each node in UI is displayed as 128 core node)
* with HAProxy and without
 
I tried hashed and ordered keys (there is no performance difference in A). In all cases Cockroach does at most 30K, but with many YCSB instances it decreases to 17K. Yugabyte can do 900K (99% latency is very poor though) and YDB can do 800K with a good latency numbers.

It can't be that cockroach does so little. I attached plots with results: concurrency -> latency, concurrency -> throughput
![latency](https://user-images.githubusercontent.com/3464685/226444966-e4b6ef3c-9d41-4d50-875b-ff1b5bd4723f.png)
![throughput](https://user-images.githubusercontent.com/3464685/226444981-720e0aeb-3a5a-4eae-b5f3-3e004424bfb6.png)

Please have a look on it deeply. I work on a performance research in distributed databases. If we don't find the reason of this results I will have to publish what I have now.

**Comment by erikgrinaker** [comment]
I've had a closer look, running YCSB/A on a 12-node 32-cpu cluster, and you're right: it's nowhere near saturating the cluster. Nodes sit at 20% CPU utilization, and the workload maxes out at around 20-30k op/s. There are a few hot nodes/ranges, but setting a more aggressive load-based split threshold of 100 qps did not sufficiently resolve the hot spots.

This is definitely because of contention. When I log/trace slow queries, they're all blocked on locks or latches. Notably, almost all of them are contended on a single key, i.e. the Zipfian peak. Since we're running this with a bounded worker pool (1024 workers in my case), and all workers are equally likely to pick this hot key, all of the workers will eventually hit it and get blocked, preventing them from making progress on other keys. Increasing the amount of workers doesn't really help, because they'll just end up getting blocked on that key as well. As you point out, performance is much better with a uniform distribution, and I also tried reducing the Zipfian theta parameter (affecting the slope) which had the same effect.

I'll also note that we do want to run this with `--insert-hash=true`, since we otherwise end up clustering the hot keys in the keyspace. This is somewhat mitigated by the lexicographical ordering of keys since we don't zero-pad them by default, but it's still worth doing. But it doesn't matter all that much here, because it's the hottest key that end up blocking the workers.

I'd like to look into a few more things here. In particular, I'd like to try using the official YCSB workload with the Postgres driver, in case there are workload differences that will affect the results (for example worker sharding, timeouts, distribution parameters, etc). I'm also curious why the other databases don't see the same problems with contention, since so many of the writes have to serialize on a single key. Perhaps there's something suboptimal in our latch/lock processing.

However, I'm out of the office the rest of the week, so it'll have to wait until next week.

**Comment by erikgrinaker** [comment]
PS: can you please send the YCSB parameters you use for the other experiments? In particular, is the workload sharded or independently randomized across your worker nodes, or do they all pick from the same consistent random distribution?

**Comment by eivanov89** [comment]
@erikgrinaker, sure, here is the command for YDB (for Yugabyte args are the same):
`./bin/ycsb run ydb -s -P workloads/workloada -p dsn=grpc://host:2135/Root/db1 -p recordcount=300000000 -p requestdistribution=zipfian -p insertorder=ordered -threads 512 -p operationcount=600000000`

Please note [this commit](https://github.com/ydb-platform/ycsb-ydb/commit/43f53dea54ee3ba08fbd966c7c59b0aef5c747a7). I made the change to make original YCSB more like cockroach's implementation. Also it seems reasonable to me to have same distribution for each YCSB thread/instance, otherwise overall load becomes uniform-like. For YDB this change increased performance just slightly (though I've expected an opposite). Unfortunately I measured Yugabyte using their YCSB package without this, but I'm going to remeasure.

> However, I'm out of the office the rest of the week, so it'll have to wait until next week.
Sure, take your time. We're very interested in fair comparison and looking forward your comments.

**Comment by erikgrinaker** [comment]
Thanks. Do you use YCQL or YSQL for the Yugabyte runner? Their [official benchmarks](https://docs.yugabyte.com/preview/benchmark/ycsb-ysql/) show that YCQL is significantly faster (108k ops/s vs 37k ops/s), possibly due to weaker isolation.

**Comment by eivanov89** [comment]
Wellcome back, Erik :)

> Do you use YCQL or YSQL for the Yugabyte runner?

YCQL. At this point we're interested in fastest options of each database. And also in YDB we have own YQL.

> possibly due to weaker isolation

I thought it was because of native language support (native datatypes, etc). Sorry, are you sure that it has weaker isolation? I would expect serializable by default (also might depend on YCSB impl)

FYIO: I've started a [thread](https://yugabyte-db.slack.com/archives/CG0KQF0GG/p1679582971838019) in their slack.

**Comment by erikgrinaker** [comment]
> Sorry, are you sure that it has weaker isolation? I would expect serializable by default (also might depend on YCSB impl).

CQL does not support read/write transactions, nor interactive transactions -- they can only contain a batch of write operations:

https://docs.yugabyte.com/preview/api/ycql/dml_transaction/

Furthermore, a CQL UPDATE is really an UPSERT -- the predicate can only be a primary key, and it does not check for the existence of a row. It is more akin to a PUT than a SQL UPDATE.

https://cassandra.apache.org/doc/latest/cassandra/cql/dml.html#update-statement

> Unlike in SQL, UPDATE does not check the prior existence of the row by default. The row is created if none existed before, and updated otherwise. Furthermore, there is no means of knowing which action occurred.

It is possible to specify an additional arbitrary predicate via the IF clause, but that comes with a significant performance cost.

> The IF condition can be used to choose whether the row is updated or not if a particular condition is met. However, like the IF NOT EXISTS condition, a non-negligible performance cost can be incurred.

The implication of all of this is that CQL can do blind writes -- in other words, it can simply pick a timestamp and pass the writes directly through consensus, without any further coordination with other writers. This is extremely efficient, because concurrent writers to the same key (i.e. the Zipfian peak) don't have to wait for concurrent writes to complete, but it of course limits the usefulness of these transactions.

SQL UPDATE, on the other hand, is a read-modify-write operation. If nothing else, it needs to know whether there is an existing row to update. This means that concurrent writers have to serialize with each other, such that only a single write can be sent through consensus at a time. This puts a hard limit on single-key throughput, which affects Zipfian write distributions in particular (although there are some improvements we can make here, like #49606). I suspect this is also the source of the CQL IF performance cost.

If you were to run YCSB/A with the YSQL runner instead of YCQL, I believe you'll see results that are closer to CRDB, because it prohibits the use of blind writes. Also keep in mind that YSQL uses snapshot isolation by default, while CRDB uses serializable isolation, which means that YSQL readers don't contend with writers.

As for YDB, being based on Calvin, it can order transactions above consensus and execute them in their entirety as a single batch. This similarly means that transactions, in particular simple read-modify-write transactions like a SQL UPDATE, don't have to serialize above consensus but can be pipelined, resulting in far better performance on Zipfian write distributions. I do see that YDB, unlike Calvin, also supports interactive transactions with locking, but that these come with a performance penalty -- in these cases, performance would perhaps be closer to CRDB, although these transactions have limitations such as not reading their own writes that would likely enable better performance in some scenarios.

**Comment by erikgrinaker** [comment]
Closing this out since this is a known weakness with our transactional model, but let us know if you have any further results or questions.

**Comment by eivanov89** [comment]
@erikgrinaker I'm sorry for late reply. I've remeasured YSQL and got numbers similar to Cockroach's. Thank you very much for pointing this out and explaining the difference between YCQL and YSQL. And in general for replying my questions.
