### ISSUE TITLE
server: `contentionRegistry.Start` is not called in the right function

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#98443]
**Describe the problem**

The call to `contnetionRegistry.Start()` in `server/server_sql.go` is not placed in the right function.

(The contract is that the New constructor must not start stopper tasks.)

**Expected behavior**

The call must be moved to the `(s *SQLServer) preStart()` method alongside the other start calls.

cc @j82w @maryliag for triage.

**Comment by knz** [comment]
We have code paths that initialize (instantiate) server instances without running them yet, and then abandons them if they are not needed. If there are stopper tasks already, that can cause goroutine leaks.

(We should probably have an assertion somewhere in TestServer that the stopper, indeed, contains no task before prestart is called)

**Comment by j82w** [comment]
Do you have any suggestion on how to test this? Is it just adding assertion the best way?
