### ISSUE TITLE
Partition Tolerance: Experiment to find our bottlenecks with large ranges

### ISSUE THREAD

**Issue by williamkulju** [cockroachdb/cockroach#98488]
This issue is to track experiments related to the partition tolerance work planned for 23.2 and corresponds to row 25 [here](https://github.com/cockroachdb/cockroach/issues/new?assignees=&labels=C-enhancement&template=feature_request.md&title=)

Jira issue: CRDB-25296

Epic CRDB-25208

**Comment by andrewbaptist** [comment]
Some results here: https://docs.google.com/spreadsheets/d/1ay1nBh7QNijv9DOt8Pa0olO2l9ZyZBlUjZA8_4UshMU/edit#gid=0

Next step is to track down why the splits for large ranges are so impactful.

**Comment by andrewbaptist** [comment]
This has mostly been found to be splits and the locks held during splits. Closing this issue for now until that is fixed and we can re-evaulate after that.
