### ISSUE TITLE
kvserver: benchmark eager expiration lease extensions

### ISSUE THREAD

**Issue by williamkulju** [cockroachdb/cockroach#98487]
In #93903 we'll add a setting to use expiration-based leases, and in #98433 we'll add a scheduler to eagerly extend these independently of client traffic. This may also prevent quiescence, see #94592. We need to benchmark the effects of these on various workloads (in particular kv0 and kv100) and look into optimization opportunities where needed.

See also internal [planning sheet](https://docs.google.com/spreadsheets/d/1UZPlVZ0MtRfi2Xmj5CjdF0o5Uj8CQDVlIAKGDdOZtDo/edit#gid=0).

Jira issue: CRDB-25295

Epic CRDB-25207

**Comment by erikgrinaker** [comment]
We have several nightly roachperf benchmarks running with expiration leases, and also ran several manual benchmarks which showed negligible impact at low range counts.
