### ISSUE TITLE
backupccl: feature gate slim manifests written during backup

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#98501]
As part of CRDB-19061 we added support for writing slimmer manifests. This feature work is slated to ship in our next release and we should add a break-glass, escape hatch to default to the old behavior of writing all fields in the backup manifest. We already added such a cluster setting as part of our backport to 22.2, and so we should name the cluster setting the same as in the older release branch.

Add metamorphic tests, so both old and new are exercised on v23.1.

Jira issue: CRDB-25301

**Comment by rhu713** [comment]
Resolved by https://github.com/cockroachdb/cockroach/pull/101074 and https://github.com/cockroachdb/cockroach/pull/101300
