### ISSUE TITLE
tenantcostclient: flake in TestConsumptionChangefeeds

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#98545]
Found here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/9046798?showRootCauses=false&expandBuildProblemsSection=true&expandBuildTestsSection=true

```
=== RUN   TestConsumptionChangefeeds
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/0cce69e026224ea71be99da3223b988f/logTestConsumptionChangefeeds2947378151
    test_log_scope.go:79: use -show-logs to present logs inline
panic: test timed out after 4m55s
```

Jira issue: CRDB-25317

**Comment by knz** [comment]
cc @jaylim-crl for triage

**Comment by ajwerner** [comment]
Or @stevendanna

**Comment by knz** [comment]
cc @stevendanna also for triage

**Comment by knz** [comment]
This fails in my PR, not on master
