### ISSUE TITLE
storage: aggregate and export internal iterator stats as timeseries

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#98583]
**Is your feature request related to a problem? Please describe.**

We gather internal iterator stats and store them in `InternalIteratorStats.{BlockBytes,BlockBytesInCache}`. 

**Describe the solution you'd like**

Consider aggregating these metrics and exporting them as dedicated timeseries.

**Additional context**

This came up in https://github.com/cockroachlabs/support/issues/2137.

Jira issue: CRDB-25343

**Comment by jbowens** [comment]
I think this might be a duplicate of #95790.

**Comment by nicktrav** [comment]
Ah, perfect. Thanks!
