### ISSUE TITLE
sql: add pg_backend_pid column to crdb_internal.{node, cluster}_sessions

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#98581]
I don't believe we currently have a way to look at a registry of sessions and their corresponding backend PIDs. If that's correct, we should expose the `pg_backend_pid` in the `crdb_internal.node_sessions` and `crdb_internal.cluster_sessions` system tables.

This will be helpful for https://github.com/cockroachdb/cockroach/issues/95771.

Jira issue: CRDB-25576

**Comment by rafiss** [comment]
One nit is that unlike PG, the backend PIDs in CRDB are not guaranteed to be unique. It's really only there for supporting the cancel protocol. See this RFC for more details: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20220202_pgwire_compatible_cancel.md#sql-node-changes

This non-uniqueness is one reason we haven't implemented `pg_terminate_backend` (https://github.com/cockroachdb/cockroach/issues/95160#issuecomment-1380958879).

Could you explain more about why it's helpful to have the PIDs in these crdb_internal tables? i.e., could we use the 128-bit session ID instead?

**Comment by nvanbenschoten** [comment]
> Could you explain more about why it's helpful to have the PIDs in these crdb_internal tables? i.e., could we use the 128-bit session ID instead?

I'm mainly interested in this because it would be helpful to add support for the [`pg_catalog.pg_isolation_test_session_is_blocked`](https://github.com/postgres/postgres/blob/bdc8d803e8e0eb987b65da1a5528ac570a07bfe1/src/backend/utils/adt/lockfuncs.c#L604) builtin function, which in turn is needed to support the `pg_isolation_regress` test suite: https://github.com/cockroachdb/cockroach/issues/95771.
