### ISSUE TITLE
sql: evaluate the usefulness of zigzag joins

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#98614]
We've seen a number of issues lately with zigzag joins. Notably, they are being favored by the optimizer over far faster plans. We've addressed some of these issues, and created issues for others, like #98022. However, I don't think we have strong conviction that the benefits of zigzag joins warrant the cost of upkeep and the risk of choosing a bad plan with a zigzag join.

In theory, the best case for a zigzag join would be something like:

```sql
-- Table t has many rows where a = 1 and many rows where b = 2,
-- but very few rows where both a = 1 and b = 2.
CREATE TABLE t (a INT, b INT, INDEX (a), INDEX (b));

SELECT * FROM t WHERE a = 1 AND b = 2;
```

However, in this case a single index scan over a new `INDEX (a, b)` would be faster, at the expense of maintaining an additional index.

I think we should investigate the following questions:

1. What is the threshold (e.g., ratio of number of rows where `a = 1 OR b = 2` to the number of rows where `a = 1 AND b = 2`) where a zigzag join is faster than a scan of a single index?
2. Is there any case where a zigzag join performs better than a single index on both equality columns?
3. How likely is it that a zigzag join is a critical processor in a customer's workload?

If we cannot prove that zigzag joins cold provide measurable improvements to a workload, we should consider deprecating them.

Jira issue: CRDB-25364

**Comment by DrewKimball** [comment]
We could also consider an adaptive implementation that becomes more of a merge join if there are more output rows than expected, since the poor performance of zigzag joins comes from cases where we have to perform a large number of seeks.

**Comment by mgartner** [comment]
Some analysis of zig-zag joins in v23.1.2 indicates that they are rarely optimal: https://docs.google.com/spreadsheets/d/1cy1uJByPCYh3NP_xyU7FBQ343EGNYIuurGoYxaNykNk/edit#gid=905894850

The [benchmark](https://gist.github.com/mgartner/64017777e9e37580a6096a7a769a5d0c) compared the execution latency of the query `SELECT * FROM t WHERE a = 1 AND b = 1` on the table:

```
CREATE TABLE t (
  k INT PRIMARY KEY,
  a INT,
  b INT,
  INDEX a_idx (a),
  INDEX b_idx (b),
  INDEX a_storing_b_idx (a) STORING (b),
  INDEX a_b_idx (a, b)
);
```

It compared the follow query plans:

1. `(Zigzag a_idx b_idx)`
2. `(Filter (IndexJoin (Scan a_idx)) b=1)`
3. `(Filter (Scan a_storing_b_idx) b=1)`
4. `(Scan a_b_idx)`
5. A simulated merge-join: `(MergeJoin (Scan a_idx) (Scan b_idx))` (We don't plan this yet, see #88997.)

The number of rows where `a = 1 AND b = 1`, `a = 1 AND b != 1`, and `a != 1 AND b = 1` were varied.

Summary of results:
* The zigzag join never beats query plan (4).
* The zigzag join seldomly beats other plans, and only does so when the ratio of rows where `a = 1 AND b = 1` to rows where `a = 1 and b != 1` is very low (e.g., 1:10,000). 

I believe this is enough evidence to support disabling zigzag joins by default in v23.2. It might be worthwhile to run a similar analysis for inverted zigzag joins.

**Comment by mgartner** [comment]
I've added analysis of inverted zigzag joins: https://docs.google.com/spreadsheets/d/1cy1uJByPCYh3NP_xyU7FBQ343EGNYIuurGoYxaNykNk/edit#gid=23283855

At a glance, inverted zigzag joins seem to provide more of a benefit over other possible query plans than regular zigzag joins do. However, in the cases with the biggest advantage, the alternative query plan with an inverted filter spends a lot of time in the inverted filter step. For example, in one case where execution took a total of 11ms, 6ms was attributed to the inverted filter. I wouldn't expect this step to be such a large contributor to execution time, so there may be some low-hanging optimizations there that bring this query plan close in performance to the inverted zigzag join.

```
  │
  └── • inverted filter
      │ nodes: n1
      │ regions: us-east1
      │ actual row count: 1
      │ estimated max memory allocated: 980 KiB
      │ estimated max sql temp disk usage: 0 B
      │ sql cpu time: 6ms
      │ estimated row count: 20,244
      │ inverted column: j_inverted_key
      │ num spans: 2
      │
```

IMO we can also disable inverted zigzag joins in v23.2 by default, but perhaps behind a separate setting from regular zigzag joins so that users can enable one or the other.

**Comment by mgartner** [comment]
I've created #104211 to track disabling zigzag joins.
