### ISSUE TITLE
server/TestHotRanges2Response and TestHotRangesResponse is very flaky (ARM64)

### ISSUE THREAD

**Issue by smg260** [cockroachdb/cockroach#98619]
[Very flakey since (and possibly introduced on) 2023/03/13](https://teamcity.cockroachdb.com/test/-3494194992598890785?currentProjectId=Cockroach_Ci_TestsAwsLinuxArm64&expandTestHistoryChartSection=true)

Jira issue: CRDB-25367

cc: @cockroachdb/server

**Comment by koorosh** [comment]
This test checks that returned list of ranges are sorted by QPS in descending order. Following commit 8b202b9d456e5167a22f4207d26d7c0a078482c0 changed default rebalancing objective from QPS to CPU usage, and now replicas ranked and sorted by CPU usage.
Probably, these tests could pass when QPS and CPU usage correlate (range with highest CPU usage also has highest QPS).

If we still want to show hot ranges on UI as a ranges with highest QPS, then `replicaRanking` should be extended to maintain multiple ordered sets per rebalancing objective (one defined for rebalancing and `Queries` objective for querying Hot Ranges by QPS).

On the other hand, Hot Ranges page in Db Console can display hottest ranges as those that either have highest CPU usage or QPS (depending on `kv.allocator.load_based_rebalancing.objective` cluster setting).

cc @kvoli , @maryliag , happy to discuss what would be the right way to handle this change and what we can consider as a hot ranges to show in Db Console.

Filed a separate issue to track misleading data representation in Db Console (#99605)

**Comment by kvoli** [comment]
put up draft https://github.com/cockroachdb/cockroach/pull/99716 that reverts to the previous behavior for hot ranges.

**Comment by koorosh** [comment]
> Should the UI likewise match what balancing is doing or do we decouple these.

I'm not sure that Hot ranges page should rely on selected balancing objective. I'd rather say that user should be able to choose what defines ranges as **hot**, either CPU usage or QPS.

**Comment by koorosh** [comment]
@rafiss , thanks for reopening issue. Submitted backport PR to get fix into 23.1.

**Comment by koorosh** [comment]
Resolved by https://github.com/cockroachdb/cockroach/pull/105879
