### ISSUE TITLE
Dynamically update number of samples / histogram buckets

### ISSUE THREAD

**Issue by DingDLu** [cockroachdb/cockroach#98638]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Jira issue: CRDB-25382

Epic CRDB-25373

**Comment by DingDLu** [comment]
This issue is created as part of 23.2 planning

**Comment by cucaroach** [comment]
Possibly existing issues on this, @michae2 reminder to hunt

**Comment by michae2** [comment]
- https://github.com/cockroachdb/cockroach/issues/72418 is about configuring the number of histogram buckets
- https://github.com/cockroachdb/cockroach/issues/97701 is about configuring the number of histogram samples

I will close this in favor of those (and will move those to the 23.2 Release column.)
