### ISSUE TITLE
Support collecting heavy hitters for statistics

### ISSUE THREAD

**Issue by DingDLu** [cockroachdb/cockroach#98632]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Jira issue: CRDB-25377

Epic CRDB-25373

**Comment by DingDLu** [comment]
This issue is created as part of 23.2 planning

**Comment by michae2** [comment]
I believe https://github.com/cockroachdb/cockroach/issues/71828 is mostly about collecting heavy hitters, so I propose we use that issue.
