### ISSUE TITLE
schema: Ensure mixed version logic tests for 22.2 and 23.1

### ISSUE THREAD

**Issue by rimadeodhar** [cockroachdb/cockroach#98637]
We need to audit all the new features that were enabled for 22.2 and make sure that we have mixed version logic test for these and repeat that for 23.1 after the branch cut.

Jira issue: CRDB-25381

Epic CRDB-26857

**Comment by rimadeodhar** [comment]
@chengxiong-ruan Do you think you can pick this item up?

**Comment by chengxiong-ruan** [comment]
Yeah, I can take it.

**Comment by rafiss** [comment]
@chengxiong-ruan do you think this can be closed now?

**Comment by chengxiong-ruan** [comment]
@rafiss yeah I think we may close, I looked through your change to audit the skipped tests, they all look fine an legit.
