### ISSUE TITLE
roachperf: remove pre-splitting from kv benchmarks

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#98649]
**Summary: We should remove pre-splitting from the kv benchmarks and address the following TODO**:
https://github.com/cockroachdb/cockroach/blob/29d21029fa8e3936c1981ecaacd2b882a4bbb1cc/pkg/cmd/roachtest/tests/kv.go#L70-L72

Discussed in https://github.com/cockroachdb/cockroach/issues/96800#issuecomment-1469246587.

Pre-splitting ranges was added to the kv benchmark suite years ago when load-based splitting was nascent. Load-based splitting is now mature and is able to find a better split count and better split points than we are able to manually. Load-based splitting is also relied upon in user testing, so we should exercise it in our own.

In each of the kv roachtests that I have looked at, removing the `--splits` flag has increased throughput. The rationale behind this is that fewer ranges allow for more intra-range batching at the Raft level, so the system can do less work to process the same amount of traffic.

If we do this, I suggest we also pass a `--ramp=1m` flag to `kv` so that we give the workload time to perform splits before the measurement period begins.

Jira issue: CRDB-25415

**Comment by tbg** [comment]
Reminder to whoever does this to also add an annotation to roachperf, see the PRs in https://github.com/cockroachdb/roachperf for examples.
