### ISSUE TITLE
kvserver: `side-transport update saw closed timestamp regression` during roachtest

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#98698]
Test Eng has in-progress work to randomly enable runtime assertions (`crdb_test` build tag)  in roachtests [1], and in the process of testing that, there was a failure in the `failover/non-system/blackhole-recv` roachtest where a node crashed with the following error:

```
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003  side-transport update saw closed timestamp regression on r1049: (lai=429, ts=1678502687.228717404,0) -> (lai=428, ts=1678502687.708863313,0)
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !goroutine 1045566 [running]:
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x1)
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/util/log/get_stacks.go:25 +0x89
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0xc000b73c00, {{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}}, 0x174b3d4de64f480d, ...})
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/util/log/clog.go:262 +0x97
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepthInternal({0x6e7a3d0, 0xc006245d10}, 0x2, 0x4, 0x0, 0x0?, {0x5b4cbd0, 0x60}, {0xc00228b9e8, 0x5, ...})
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/util/log/channels.go:106 +0x645
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(...)
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/util/log/channels.go:39
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(...)
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/util/log/log_channels_generated.go:848
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*sidetransportAccess).assertNoRegression(0x50f5620?, {0x6e7a3d0, 0xc006245d10}, {{0x174b3d4d0ace695c, 0x0, 0x0}, 0x1ad}, {{0x174b3d4d276cdb51, 0x0, 0x0}, ...})
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_closedts.go:263 +0x1eb
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*sidetransportAccess).forward(0xc0058a0598, {0x6e7a3d0, 0xc006245d10}, {0x20000c002539100?, 0xffffffff?, 0xff?}, 0x1ac, 0x0)
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_closedts.go:237 +0x15d
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).ForwardSideTransportClosedTimestamp(...)
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_closedts.go:138
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).ForwardSideTransportClosedTimestampForRange.func1(0xc009d26bb8?)
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:132 +0x8a
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).VisitStores.func1(0xc009d26bb8?, 0xa60a968?)
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:149 +0x29
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/util/syncutil.(*IntMap).Range(0xc00571f7d0?, 0xc00228bc48)
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/util/syncutil/int_map.go:352 +0x1fa
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).VisitStores(0x67e?, 0xc002539100?)
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:148 +0x54
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).ForwardSideTransportClosedTimestampForRange(0x5099580?, {0x6e7a3d0, 0xc006245d10}, 0x6e7a3d0?, {0xc006245d10?, 0x203000?, 0x0?}, 0x1?)
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:129 +0x96
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/kv/kvserver/closedts/sidetransport.(*incomingStream).processUpdate(0xc004fff6b0, {0x6e7a3d0, 0xc006245d10}, 0xc003735a40)
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/closedts/sidetransport/receiver.go:252 +0x675
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/kv/kvserver/closedts/sidetransport.(*incomingStream).Run.func1({0x6e7a3d0, 0xc006245d10})
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/closedts/sidetransport/receiver.go:328 +0x1b8
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470 +0x146
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
kv/kvserver/replica_closedts.go:263 â‹® [T1,n6] 2003 !	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:461 +0x43b
```

I don't think the failure is related to the fact that we were using a `crdb_test` build per se, so I wanted to bring this to kv-repl's attention so that you can take a closer look.

I ran the test a couple more times and did not see the same issue happen again, but I can help with reproduction efforts if needed.

Artifacts (n6 is the one that crashes):
<https://teamcity.cockroachdb.com/viewLog.html?buildId=9006960&buildTypeId=Cockroach_Nightlies_RoachtestNightlyGceBazel&tab=artifacts#%2Ffailover%2Fnon-system%2Fblackhole-recv>

[1] #98351

Jira issue: CRDB-25452

**Comment by erikgrinaker** [comment]
@tbg This seems related to the reproposal closed timestamp regressions we've seen. Would you agree with lumping this into the reproposals epic and deal with it after the branch cut?

**Comment by nvanbenschoten** [comment]
We've seen this same assertion fire in multiple sentry reports (see above). We also saw it fire again in https://github.com/cockroachdb/cockroach/issues/99931, which was another variant of `failover/.../blackhole-recv`. Is the side-transport susceptible to network reorderings that could make this easier to hit in this kind of test?

I'm not adding the `GA-blocker` label back on because this is not new, but we should take a look at this.

**Comment by erikgrinaker** [comment]
Discussed this briefly with @nvanbenschoten and @andrewbaptist. While I think this seems likely to be the issue we've "always" had with closed timestamp regressions seen in the wild (e.g. Sentry), and which Tobi found and fix during reproposals, we feel like it's worth confirming that. Especially given that this issue is in the side transport, not during proposals. So we've added the GA-blocker to make sure we confirm this.

**Comment by erikgrinaker** [comment]
@tbg said that this was unlikely to be related to the issues we saw with reproposals and closed timestamp regressions. More likely network reordering or some such, like @nvanbenschoten said above.

**Comment by pavelkalinnikov** [comment]
In this stack trace the receiver processes a range that is being `Removed` from closed timestamp tracker. The sender, correspondingly, added this ranges to removals for one of the 2 reasons:

1. It stopped being a leaseholder: https://github.com/cockroachdb/cockroach/blob/fad7ac8303582228b010375c60820d4a6a798570/pkg/kv/kvserver/closedts/sidetransport/sender.go#L361-L368
2. The sender could not close the timestamp that it attached to the update: https://github.com/cockroachdb/cockroach/blob/fad7ac8303582228b010375c60820d4a6a798570/pkg/kv/kvserver/closedts/sidetransport/sender.go#L391-L396

**Comment by pavelkalinnikov** [comment]
A couple of facts about the closed timestamp updates in the side transport.

The timestamp may regress because the sender [doesn't ensure](https://github.com/cockroachdb/cockroach/blob/fad7ac8303582228b010375c60820d4a6a798570/pkg/kv/kvserver/closedts/sidetransport/sender.go#L330-L343) it's monotonic. For example, when I changed `closedts.TargetDuration` cluster setting from the default 3s to 10s, I expected up to 7s of regression, which was confirmed in the receiver's log:

```
I230419 13:30:20.849723 705 kv/kvserver/closedts/sidetransport/receiver.go:224 ⋮ [T1,n2] 1728  received side-transport update: ‹Seq num: 882, sending node: n1, snapshot: false, size: 37 bytes, closed timestamps: LAG_BY_CLUSTER_SETTING:1681911017.849317000,0 (3s ago), LEAD_FOR_GLOBAL_READS:1681911021.649317000,0? (799ms in the future)›
...
I230419 13:30:21.050194 705 kv/kvserver/closedts/sidetransport/receiver.go:224 ⋮ [T1,n2] 1730  received side-transport update: ‹Seq num: 883, sending node: n1, snapshot: false, size: 63 bytes, closed timestamps: LAG_BY_CLUSTER_SETTING:1681911011.049559000,0 (10s ago), LEAD_FOR_GLOBAL_READS:1681911021.849559000,0? (799ms in the future)›
```

This update is speculative, in a couple of aspects:
- The receiver may have not applied this LAI yet: https://github.com/cockroachdb/cockroach/blob/793b4c8bfc6e9dbf7a05289f3e61035796476cc5/pkg/kv/kvserver/replica_closedts.go#L135-L138
- The timestamp is local to the sender, and may be ahead of the timestamp recorded in the log. When the range is "inactive", this timestamp just gets bumped and sent.

A hypothetical situation that might be happening here:
- There are two leaseholders, one at LAI 22 and another at LAI 23. The 22 one still doesn't know it should give up.
- The range is "inactive" on both leaseholders (no in-flight requests / proposals). So, both leaseholders update the timestamp speculatively and send it through the side-transport.
- Clearly, the timestamps may be out of order.
- Both updates arrive in some order, get compared, and trigger the failure.
- NB: the updates will be arriving through different [streams](https://github.com/cockroachdb/cockroach/blob/f92966c6888a467568441e6f85553d6ee876d701/pkg/kv/kvserver/closedts/sidetransport/receiver.go#L163-L180).

**Comment by pavelkalinnikov** [comment]
Not only the the closed timestamp sent through the side-transport can regress [same code snippet [here](https://github.com/cockroachdb/cockroach/blob/fad7ac8303582228b010375c60820d4a6a798570/pkg/kv/kvserver/closedts/sidetransport/sender.go#L330-L343)], the sender doesn't seem to be checking that this is a valid timestamp w.r.t. to the lease time interval. For example, shouldn't it verify that `now` that it [sends](https://github.com/cockroachdb/cockroach/blob/fad7ac8303582228b010375c60820d4a6a798570/pkg/kv/kvserver/closedts/sidetransport/sender.go#L324) is below the lease expiration time for each range that it updates. I don't know if the `leaseholders` list copied [here](https://github.com/cockroachdb/cockroach/blob/fad7ac8303582228b010375c60820d4a6a798570/pkg/kv/kvserver/closedts/sidetransport/sender.go#L352) is guaranteed to have only replicas whose lease expires after `now`.

**Comment by pavelkalinnikov** [comment]
```
02:36:23 failover.go:285: test status: failing n4 (blackhole-recv) 
02:37:21 failover.go:294: test status: recovering n4 (blackhole-recv)
02:38:23 failover.go:285: test status: failing n5 (blackhole-recv)
02:39:21 failover.go:294: test status: recovering n5 (blackhole-recv)
02:40:23 failover.go:285: test status: failing n6 (blackhole-recv)
02:41:21 failover.go:294: test status: recovering n6 (blackhole-recv)
02:42:23 failover.go:285: test status: failing n4 (blackhole-recv)
02:43:21 failover.go:294: test status: recovering n4 (blackhole-recv)
02:44:22 failover.go:285: test status: failing n5 (blackhole-recv)

02:44:36.526648 unable to transfer lease to s4: [n5,r1049]: unable to transfer lease to s4: refusing to transfer lease to (n4,s4):2 because target may need a Raft snapshot: ‹replica in StateProbe›

02:44:47.228 the timestamp of CT update with LAI=429
02:44:47.708 the timestamp of CT update with LAI=428

02:44:47.843018 [n6] closed timestamps side-transport connection dropped from node: 5

02:44:50.228 [+3s] the first update was generated/sent at
02:44:50.708 [+3s] the second update was generated/sent at

02:44:50.930170 [n6] closed timestamps side-transport connection dropped from node: 4
02:44:50.931129 [n4] closed timestamps side-transport connection dropped from node: 6

02:44:50.931213 [n6] side-transport update saw closed timestamp regression on r1049: (lai=429, ts=1678502687.228717404,0) -> (lai=428, ts=1678502687.708863313,0)
```
