### ISSUE TITLE
stability: investigate lock order Replica.mu < Store.mu

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#9870]
We currently do `Store.mu < Replica.mu` but whenever this actually happens, we are putting performance at a high risk when there is any chance of `Replica.mu` not being available right away (#9771 is an extreme example).

I wonder if we can generally invert that lock order which would allow us to pass a locked replica to pieces of code that require `Store.mu` held throughout.

**Comment by petermattis** [comment]
Change the lock ordering here is likely very difficult. Another thought is that we should audit the code and ensure `Replica.mu` is only held for small periods of time (i.e. not across I/O operations). I just fixed when case in `Replica.TruncateLog` where `Replica.mu` was held excessively. There are likely others.

**Comment by petermattis** [comment]
Ugh, auditing the uses of `Replica.mu` just now and not holding `Replica.mu` across I/O operations is daunting as we do it frequently. For example, `Replica.GetSnapshot` holds `Replica.mu` while calling `Replica.SnapshotWithContext`.

**Comment by tschottdorf** [comment]
Closing as stale. We're at a point where we improve performance shortcomings where we find them (and where we're better at actually finding them).
