### ISSUE TITLE
changefeedccl: when using http sink, warn that it is not webhook

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#98719]
It is easy to use the http sink on accident, thinking it is the webhook sink, like what happened with a customer recently. Though we document this, most customers miss it (as https:// is what you would expect to use as the scheme, not webhook-https://). When creating a changefeed with the http sink, we should warn users and point to our webhook documentation.

Jira issue: CRDB-25462

Epic CRDB-28878

**Comment by HonoreDB** [comment]
Maybe we should even deprecate `https://` in favor of something like `file-https://` so we don't have any ambiguity? We had it as `https://` because backups did, but backups don't anymore iirc.

**Comment by shermanCRL** [comment]
This seems intuitive. Gotta do migrations, presumably.
