### ISSUE TITLE
ttl,admission: reduce performance impact of large row-level TTL jobs

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#98722]
**Is your feature request related to a problem? Please describe.**

We've seen in several internal incidents that using row-level TTL can be a performance footgun with large tables. We observe throughput/latency impact either when initially applying row-level TTL on an existing table using `ttl_expire_after` (which kicks off a column backfill; using `ttl_expiration_expression` does not cause a backfill), or when a TTL job is unpaused and starts aggressively issuing row deletes through SQL. It can also appear as part of routine row-deletions [without prolonged job pauses](https://cockroachlabs.slack.com/archives/C01SRKWGHG8/p1684430587640829). This issue focuses on the latter case, and can look like below:

![image](https://user-images.githubusercontent.com/10536690/225457274-fb7d92fc-2110-4185-b536-8f555156a5c3.png)
![image](https://user-images.githubusercontent.com/10536690/225457288-17dbefbb-d01e-4a0f-b5e6-37c84642a766.png)
![image](https://user-images.githubusercontent.com/10536690/225457313-dc034cd7-a0b2-40b2-8fba-1dff9c11b47f.png)

For the column backfill case, we replication admission control to help (https://github.com/cockroachdb/cockroach/issues/95563). Internal incidents:
- https://github.com/cockroachlabs/support/issues/1961
- https://cockroachdb.zendesk.com/agent/tickets/15684
- https://github.com/cockroachlabs/support/issues/1628
- https://github.com/cockroachlabs/support/issues/2050

Jira issue: CRDB-25463

Epic CRDB-25458

**Comment by ecwall** [comment]
@irfansharif is there a way to specify a max cpu usage for low priority tasks like this?

For example if the threshold is set to 75% then the task should not run unless cpu usage falls below that level. If other tasks are using 75% then this task should never run.

Context https://cockroachlabs.slack.com/archives/CHKQGKYEM/p1690222820278609?thread_ts=1690207802.498629&cid=CHKQGKYEM

**Comment by rafiss** [comment]
The support ticket https://github.com/cockroachlabs/support/issues/2469#issuecomment-1640640043 contains information on how to reproduce the problem manually. SQL Foundations is also going to work on making that into a nightly test in https://github.com/cockroachdb/cockroach/issues/107496

**Comment by rafiss** [comment]
https://github.com/cockroachdb/cockroach/pull/107959 adds a roachtest that can be used to reproduce this.

Run with:
```
roachtest run row-level-ttl/during/tpcc/expired-rows=false --cockroach /path/to/cockroach-v23.1.6.linux-amd64
# or
roachtest run row-level-ttl/during/tpcc/expired-rows=true --cockroach /path/to/cockroach-v23.1.6.linux-amd64
```

In both of these, the TTL job will run 10 minutes after the TPCC load begins.

With the first command, the TTL job will scan for expired rows, but will not delete anything (since no rows will match the expiration expression). With the second command, the TTL job will scan and delete rows.

Here's some data from a run with `expired-rows=false`:
<img width="981" alt="image" src="https://github.com/cockroachdb/cockroach/assets/1320573/ad9becc0-3f94-4ff9-90c6-5346a8984b6c">
The TPCC workload starts at 15:58. The TTL job wakes up at 16:08, and we can see that the CPU usage goes up to 100% at that point.

Here's a snippet from the workload artifacts that shows that as soon as TTL starts running, the foreground latencies started going up (median as well as tail latencies):
```
_elapsed___errors__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
  260.0s        0           52.0           43.7     25.2     30.4     32.5     33.6 newOrder
  261.0s        0           41.0           43.7     25.2     32.5     37.7     37.7 newOrder
  262.0s        0           49.0           43.7     26.2     46.1     54.5     54.5 newOrder
  263.0s        0           45.0           43.7     25.2     71.3     92.3     92.3 newOrder
  264.0s        0           41.0           43.7     24.1     29.4     31.5     31.5 newOrder
  265.0s        0           35.0           43.7     25.2     52.4     83.9     83.9 newOrder
  266.0s        0           43.0           43.7     25.2     33.6     35.7     35.7 newOrder
  267.0s        0           43.0           43.7     26.2     54.5     67.1     67.1 newOrder
  268.0s        0           41.0           43.7     26.2     44.0     79.7     79.7 newOrder
  269.0s        0           45.0           43.7     26.2     37.7     48.2     48.2 newOrder
  270.0s        0           43.0           43.7     25.2     37.7     62.9     62.9 newOrder
  271.0s        0           52.0           43.7     25.2     29.4     33.6     35.7 newOrder
  272.0s        0           39.0           43.7     25.2     31.5     35.7     35.7 newOrder
  273.0s        0           41.0           43.7     25.2     31.5     56.6     56.6 newOrder
  274.0s        0           32.0           43.6     24.1     35.7     37.7     37.7 newOrder
  275.0s        0           26.0           43.6    570.4    838.9    939.5    939.5 newOrder
  276.0s        0           40.0           43.6    637.5   1006.6   1342.2   1342.2 newOrder
  277.0s        0           41.0           43.5    704.6   1040.2   1879.0   1879.0 newOrder
  278.0s        0           42.0           43.5    637.5   1040.2   1208.0   1208.0 newOrder
  279.0s        0           46.0           43.5    604.0   1073.7   1342.2   1342.2 newOrder
  280.0s        0           30.0           43.5    570.4    939.5    973.1    973.1 newOrder
  281.0s        0           46.0           43.5    704.6   1140.9   1879.0   1879.0 newOrder
  282.0s        0           40.0           43.5    637.5   1208.0   1543.5   1543.5 newOrder
  283.0s        0           38.0           43.5    570.4    939.5    973.1    973.1 newOrder
  284.0s        0           38.0           43.5    570.4    973.1   1342.2   1342.2 newOrder
  285.0s        0           35.0           43.4    570.4    805.3   1677.7   1677.7 newOrder
  286.0s        0           43.0           43.4    604.0    939.5   1140.9   1140.9 newOrder
  287.0s        0           47.0           43.4    637.5    939.5   1543.5   1543.5 newOrder
  288.0s        0           48.0           43.5    604.0    939.5   1208.0   1208.0 newOrder
  289.0s        0           43.0           43.5    570.4    973.1   1208.0   1208.0 newOrder
  290.0s        0           38.0           43.4    637.5    906.0   1006.6   1006.6 newOrder
  291.0s        0           49.0           43.5    604.0    872.4   1006.6   1006.6 newOrder
  292.0s        0           37.0           43.4    570.4    939.5   1006.6   1006.6 newOrder
  293.0s        0           42.0           43.4    671.1   1208.0   1275.1   1275.1 newOrder
```

**Comment by irfansharif** [comment]
Copying over notes from [internal experiments](https://cockroachlabs.slack.com/archives/C01SRKWGHG8/p1691694348016829).

With and without https://github.com/cockroachdb/cockroach/pull/108815. p99 goes from 229ms -> 48ms (4.7x decrease) and p90 from 95.8ms -> 8.7ms (11x decrease) during TTL reads with the elastic CPU integration. It keeps CPU% to whatever it’s configured to - instead of the 100% before, now ~50% utilization is what’s considered ok by default WRT p99 scheduling latency.

![image](https://github.com/cockroachdb/cockroach/assets/10536690/dbe4aef8-02d8-4056-8e92-cd2533eccfdb)


Other than below-KV CPU% utilization (at the batch request level), there’s a substantial amount of CPU% during these TTL selects that happen up in SQL. Which is why we also acquire CPU tokens for this SQL work: [profile-19.pb.txt](https://github.com/cockroachdb/cockroach/files/12399549/profile-19.pb.txt)

![image](https://github.com/cockroachdb/cockroach/assets/10536690/8f09b107-c4d7-4025-8a60-b66003b25a74)

**Comment by irfansharif** [comment]
https://github.com/cockroachdb/cockroach/pull/108815 fixes things. I’ll kick off another run for the delete work and column backfill, but I expect that they’re both improved with flow control.
