### ISSUE TITLE
cloud/gcp: some permission errors returned as `grpc: [code 0/OK]`

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#98733]
For reasons not currently apparent, some callers of the gcs writer when interacting with a bucket to which they do not have permissions an error from Writer.Close() of the form: `grpc: [code 0/OK]` instead of something like 403/"Permission denied"/etc.

Reproduction, and some speculation, in internal slack thread: https://cockroachlabs.slack.com/archives/C03JCUUSCD6/p1678856212885119

Jira issue: CRDB-25475

**Comment by stevendanna** [comment]
Fixed in https://github.com/cockroachdb/cockroach/pull/103856
