### ISSUE TITLE
Feature gate generative split and scatter processor in 22.2

### ISSUE THREAD

**Issue by rhu713** [cockroachdb/cockroach#98768]
Currently the generative split and scatter processor in restore is on by default in 22.2, feature gate this so users of restore can toggle between the previous split and scatter distSQL plan and the plan with the generative processor. This also allows users to fallback to the previous split and scatter behavior in case the generative version has issues.

Jira issue: CRDB-25510

**Comment by msbutler** [comment]
this should hold up the next 22.2 release correct?

**Comment by rhu713** [comment]
Closing as the slim manifest backport has been reverted
