### ISSUE TITLE
sql: change users from strings to url.Users

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#9876]
Currently we represent users like security.RootUser and server.TestUser as their string username ("root" and "testuser"). It makes more sense for these to be url.Users since #9794 uses them to construct PGURLs with passwords and currently makes unnecessary conversions.

**Comment by yznming** [comment]
@asubiotto maybe I can try to fix it.

**Comment by asubiotto** [comment]
Thanks! I would recommend waiting for #9794 so that you don't have to repeat any changes.

**Comment by yznming** [comment]
@asubiotto got it. I will wait until #9794 merged.

**Comment by asubiotto** [comment]
#9794 merged

**Comment by yznming** [comment]
got it. I will start fixing it now.

**Comment by asubiotto** [comment]
Closed. Refer to #10591.
