### ISSUE TITLE
sql: add root user to system.users table during bootstrap and add authentication

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#9877]
For authentication, the root user must exist in the system.users table. A password should also be chosen at this stage. #9794 adds a backdoor for clients authenticating as security.RootUser. This should be removed with this change.

**Comment by asubiotto** [comment]
This should happen after #9404.

**Comment by bdarnell** [comment]
As I said in #9794, I would prefer if it were impossible to give the root user a password and it used certificate-only authentication. Then the bootstrapping could be non-interactive. (I think it would be nice if `root` existed in `system.users`, but I'd also be OK with a special-case that would allow `root` to be used regardless of the state of that table).

**Comment by asubiotto** [comment]
Closing issue because root will have cert only authentication. Since we never have to check for the existence of root, there doesn't seem to be a need to add root to ```system.users```
