### ISSUE TITLE
roachprod,roachtest: don't RAID0 local SSD and PD/EBS

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#98783]
**Describe the problem**

See https://github.com/cockroachdb/cockroach/pull/98782.

**To Reproduce**

Run the test in https://github.com/cockroachdb/cockroach/issues/97019.

**Expected**

I think RAID'ing wildly different storage media together should be a very explicit opt-in. Also, nobody will take this opt-in, so it maybe shouldn't even be possible.

When multiple EBS/PD-SSD volumes are created however, it makes some sense to RAID them together, however again I am skeptical (read: totally critical) of that being a good default.

Some discussion in https://github.com/cockroachdb/cockroach/pull/98782#issuecomment-1475600391.

Jira issue: CRDB-25519

**Comment by erikgrinaker** [comment]
This popped up again in a bunch of AWS roachtest failures on 23.1 (e.g. #106013), where devices are RAIDed by default, breaking the test which does not expect this.
