### ISSUE TITLE
opt: audit correlated subquery code for panic catching

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#98786]
Audit the newly added code in the execbuilder for missing panic-catchers. Look for issues similar to the one fixed in this commit: https://github.com/cockroachdb/cockroach/pull/88396/commits/5c0a632100ba50a15ab8c4cbfdf643ca84942dcd

From the [v23.1 pre-mortem](https://cockroachlabs.atlassian.net/wiki/spaces/SQLQUERIES/pages/edit-v2/29294919690).

Jira issue: CRDB-25521

**Comment by DrewKimball** [comment]
I'm going to see if I can add some panic injection in the optimizer for our tests this week.

**Comment by mgartner** [comment]
Thanks @DrewKimball. That's tracked here: https://github.com/cockroachdb/cockroach/issues/98787
