### ISSUE TITLE
Cockroach node shuts down with runtime error

### ISSUE THREAD

**Issue by kosii** [cockroachdb/cockroach#9879]
While doing my tests for #9878, I noticed that sometimes some of my nodes died with the following error message:

```
`--> panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x110 pc=0xab61ed]

goroutine 55068 [running]:
panic(0x15eb9a0, 0xc420010100)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Recover(0xc4204ec630)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:177 +0x6e
panic(0x15eb9a0, 0xc420010100)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/cockroachdb/cockroach/internal/client.(*Txn).Rollback(0x0, 0x15b91a0, 0xc42071c1a0)
	/go/src/github.com/cockroachdb/cockroach/internal/client/txn.go:395 +0x2d
github.com/cockroachdb/cockroach/internal/client.(*Txn).CleanupOnError(0x0, 0x2112880, 0xc42071c1c0)
	/go/src/github.com/cockroachdb/cockroach/internal/client/txn.go:325 +0x40
github.com/cockroachdb/cockroach/sql.(*txnState).updateStateAndCleanupOnErr(0xc4228c0828, 0x2112880, 0xc42071c1c0, 0xc4203360f0)
	/go/src/github.com/cockroachdb/cockroach/sql/session.go:334 +0xbe
github.com/cockroachdb/cockroach/sql.(*Session).Finish(0xc4228c0800)
	/go/src/github.com/cockroachdb/cockroach/sql/session.go:134 +0x106
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).finish(0xc42105d680)
	/go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:147 +0x7fr
github.com/cockroachdb/cockroach/sql/pgwire.(*Server).ServeConn(0xc4204e87c0, 0x21291c0, 0xc421fa2fd0, 0x210f0c0, 0xc4200101a0)
	/go/src/github.com/cockroachdb/cockroach/sql/pgwire/server.go:242 +0x652
github.com/cockroachdb/cockroach/server.(*Server).Start.func8.1(0x21291c0, 0xc421fa2fd0)
	/go/src/github.com/cockroachdb/cockroach/server/server.go:428 +0x4e
github.com/cockroachdb/cockroach/util/netutil.(*Server).ServeWith.func1(0xc4204ec630, 0xc4204ca150, 0x21291c0, 0xc421fa2fd0, 0xc42020e000)
	/go/src/github.com/cockroachdb/cockroach/util/netutil/net.go:138 +0x95
```
For my tests I was using the latest cockroach (20161006), and I made a [test application](https://github.com/kosii/CockroachIssueReprod) to reproduce the error. Make sure you are on the `runtime_error` branch. The bug is not deterministic, and I couldn't make the codebase smaller, but the app reproduces it about 5 times out of 10. Type `./sbt run` to execute the app. If necessary, you can reconfigure the database in the `src/main/resources/application.conf` file. The repo also contains the logs and stores of all the nodes (it was `node1` who crashed).

I also noticed, that the bug happens only when a thread quits abruptly in the middle of a transaction (it also happened sometimes when I killed my application with threads executing transactions). I hope this helps. 

Ping @andreimatei

**Comment by andreimatei** [comment]
Hey @kosii I'm running your app but can't seem to get the server to panic. You said "bug happens only when a thread quits abruptly in the middle of a transaction" - is there a way to trigger that, other than CTRL-C-ing the app?

Also, how big was the cluster on which you were reproducing this? Did you ever get it to happen on a single node cluster? And what was the OS?

Thanks!

**Comment by andreimatei** [comment]
Maybe I was supposed to run your app with `app.parallelism` higher than the default "5" and kill it repeatedly to make this happen?

In any case, I've combed the code more and was able to see what's going on and repro pretty easily. If a connection is closed abruptly when the current transaction happens to be in one of a few weird states (basically waiting for a final COMMIT after a RELEASE SAVEPOINT), we indeed crash because we're trying to rollback a transaction that doesn't exist (technically, the SQL level transaction exists, but the lower-level KV transaction doesn't exist any more).
I believe this is a relatively recent bug.
I'll send out a fix, should be easy.

**Comment by spencerkimball** [comment]
Is this a duplicate: #7881

**Comment by spencerkimball** [comment]
@kainkain this is the bug you're running into as well.

**Comment by kosii** [comment]
@andreimatei Normally the app tries to trigger it: when one thread ends, the app quits, forcing to quit all other threads still runnig. I used a 3 node cluster running locally on my pc, but I haven't tried a single node cluster. I'm using arch linux. Increasing parallelism can help to make it happen more often.

Cool that you've found a way to reproduce it more easily!
