### ISSUE TITLE
sql: add command-line flag for specifying a password

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#9880]
Useful for tests and command-line automation.

**Comment by bdarnell** [comment]
The CLI client should also be able to read the password from a file (which is more secure than a command-line argument). This could be either a flag like `--password-file=mypassword.txt` or a more general `.cockroachrc` file that could include username, password, cert info, etc. (probably the latter).

**Comment by denismakogon** [comment]
@bdarnell What about implicit reading from file like having somewhere ~/.cockroachdb.rc file with credentials?
Also, i'd say that `read from file` deserves its own ticket, doesn't it?

**Comment by a6802739** [comment]
@asubiotto,  do you mean the password file is like mysql's uer.root.cnf?

**Comment by asubiotto** [comment]
I would say so. Another example I'm thinking of is .gitconfig.

**Comment by a6802739** [comment]
@asubiotto, how could I pass the password to verify correctness?

**Comment by asubiotto** [comment]
This flag is specific to the set user command (```cockroach user set <setusername> --password=<setpassword>```) which creates a new user with the given password or updates an existing user's password. The flag that we are talking about would specify the password of the user that the client is initiating a connection as.

It would be confusing to keep this flag the way it is so I suggest renaming it for its function to be obvious and having a new ```--password``` flag similar to the ```--user``` flag for the connection's user which is populated either explicitly or when parsing a configuration file. It would be useful to also specify certificates and keys in this file.

**Comment by a6802739** [comment]
@asubiotto, okay. you mean I should add `--password` and `--user` like `cockroach sql --password <loginpassword> --user <loginuser> --port=25267`?

By the way, when I pass the password. how should I verify the password? should I execute a sql command to query the user's password and verify it?

**Comment by asubiotto** [comment]
Yes, that sounds good.

**Comment by asubiotto** [comment]
Closing because it is not necessary. From #10175:
> The initial reasoning for adding this functionality was to allow for easy testing of password authentication from the CLI. However, I added these tests in #10449 and having a command-line flag for the user's password would in fact be a security issue because it would be saved in the cli history file.
