### ISSUE TITLE
schemachange/mixed-versions-compat: `interface is nil, not scpb.Element`

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#98812]
While running the `schemachange/mixed-versions-compat` roachtest on a branch [1], the following error was observed:

```
failed building declarative schema changer plan in PostCommitNonRevertiblePhase (rollback=false) 
for DROP DATABASE with error: building declarative schema changer plan in PostCommitNonRevertiblePhase 
(rollback=false) for DROP DATABASE: interface conversion: interface is nil, not scpb.Element
```

While this run was not on master, there are no indications that the failure is associated with the changes in that PR (the run used a binary without runtime assertions enabled).

Artifacts: <https://teamcity.cockroachdb.com/viewLog.html?buildId=9084185&buildTypeId=Cockroach_Nightlies_RoachtestNightlyGceBazel&tab=artifacts&branch_Cockroach_Nightlies=98351#%2Fschemachange%2Fmixed-versions-compat%2Frun_1%2Fartifacts.zip!%2Flogs>

@cockroachdb/sql-schema

[1] #98351

Jira issue: CRDB-25533

**Comment by ajwerner** [comment]
Let's see whether this repros with https://github.com/cockroachdb/cockroach/pull/98351 which would likely mean that some randomized assertion comes into play somewhere in the debug command.

**Comment by ajwerner** [comment]
I'm inclined to say we should wait for that PR to merge, and then run this a bunch of times after.

**Comment by ajwerner** [comment]
Here, when we get an error, please also log out the hex of the state or something like that:

https://github.com/cockroachdb/cockroach/blob/0b7ad8622dd7e14b551ce9e16cf6f7868f70c661/pkg/cli/declarative_corpus.go#L59-L64

**Comment by ajwerner** [comment]
We're going to close this and let the roachtest fail, if it is going to, after https://github.com/cockroachdb/cockroach/pull/98351 merges. We've filed https://github.com/cockroachdb/cockroach/issues/99705 to make the test failures easier to process.
