### ISSUE TITLE
create limit for logged messages when in-memory limit is reached

### ISSUE THREAD

**Issue by maryliag** [cockroachdb/cockroach#98818]
When we limit the in-memory limit on sql stats, we do a flush, but while this is happening or if we can't do a flush because the min limit between the last flush hasn't happen yet, we won't be able to add new data in-memory.
Every time a new execution can't be added in-memory a log is created. If a cluster is under a heavy workload, there can be a lot of logs, which aren't helpful.
A limit of how many are sent should be added.

Jira issue: CRDB-25536

**Comment by j82w** [comment]
Closing as a duplicate of: https://github.com/cockroachdb/cockroach/issues/110454
