### ISSUE TITLE
sql: report panics as errors to clients

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#9884]
Currently a panic in sql world will kill the server. 
The only care for panics in `Executor.ExecuteStatements` merely prepends the SQL code that lead to the panic to the panic error message.

We can do better. Namely:
1. convert the panic to an error in the executor, so that clients get a chance to continue using the node. Since our SQL implementation is schielded from the rest of the DB with proper interfaces a panic in SQL cannot (should not?) lead to corruption in the DB. (To ensure this is true, we may want to be careful to only let panics in the query execution be converted to errors. Panics in the internal executor used for lease managements etc should probably still kill the node. Opinions?)
2. save the panic into an internal DB table which can be viewed via the UI. Also copy it to the db logs.
3. report panic details automatically to the registration server, modulo a checkbox in the UI to enable users to opt out from this service.
4. catch the panic deeper in the executor, and take care to roll back any open transaction when a panic occurs.

cc @bdarnell @mjibson @petermattis

**Comment by knz** [comment]
I'd like to propose solving this issue as a major UX improvements before 1.0.

**Comment by mjibson** [comment]
Should a panic encountered like this close the pgwire connection?

I'm torn on whether to catch these panics or not. On the one hand it's real bad if a user finds this and creates a DOS against themselves or an attacker takes someone down. However dumping them into a log somewhere and hoping the application user notices and reports them back to us also seems not great.

**Comment by knz** [comment]
That's why point 3 says it should be pinged to our reg server. This way it's unlikely we'll lose them.

And no I suggest to keep the pgwire server up, even possibly the client conn, and simply abort the current txn.

**Comment by RaduBerinde** [comment]
We would need a reliable way of knowing if these conditions happen in any of our internal testing deployments. And we definitely need to be conservative about which panics we catch. Ideally panics from which a server can recover shouldn't be panics in the first place..

**Comment by knz** [comment]
Yes 

a. there would be a flag to disable this capture, enabled for testing and QA

b. most of the panics we have *explicit* in the code now indicate a programmer error, not a database error, and the error is irrecoverable insofar that the current statement must be aborted entirely immediately (evaluation of this statement cannot continue) and perhaps the session must be aborted (some state in the session may be corrupted), however b.1) in none of the explicit panics I have looked at so far the error was so serious that another client could not try again by reconnecting or reissuing the query and b.2) the failure scenarios are extremely unlikely so I am really not concerned about those.

c. most of the panics that we have seen coming from users so far are *spontaneous* ie. generated by Go from nil dereferences and the like. We know what these mean too (programmer error) and should be recoverable by users without a server restart. These are the panics that have motivated me to file this issue in the first place.

However you can see

**Comment by bdarnell** [comment]
My impression is that a lot of the panics that we see in SQL (e.g. #9879) have to do with transaction management. These should at least shut down the client connection, and even then a mishandled transaction could leave e.g. a coordinator goroutine heartbeating and causing contention with other transactions. I'd lean towards keeping these as panics so we can root them out more quickly (on the assumption that there are not a large variety of issue that can cause this. If I'm misreading things and we see a lot of query-dependent panics that touch the transaction then it might make sense to recover here too).

For panics that are more internal to the SQL code (e.g. the ALTER TABLE SET TYPE panic that was fixed a while ago and recently discussed), I'm OK with adding recovery.

**Comment by knz** [comment]
@dt I hear from peter you're already looking at this, can you tell me more?

**Comment by knz** [comment]
There's a discussion ongoing at https://github.com/cockroachdb/cockroach/pull/15063#issuecomment-295304425 about where this issue is leading us.

**Comment by knz** [comment]
The main question here is "should we attempt to recover, at the risk of having a server in a partially broken state after a panic has been recovered, or not recover at all, at the risk of crashing one node after another as a client attempts to re-issue a faulty query from one node to another through a load balancer?"

**Comment by RaduBerinde** [comment]
My 2 cents: if "partially broken state" can imply that we may potentially corrupt the database state in some way, or violate our guarantees (like transaction isolation etc), I would prefer the latter.

**Comment by tamird** [comment]
I agree with one of @raduberinde's earlier comments: we crash due to bugs,
or lazily-written panics when returning an error was inconvenient. That
said, catching panics in a restricted subset of the SQL code (i.e. code
that doesn't interact with KV) seems reasonable to me.

**Comment by knz** [comment]
There is a middle road maybe.
I am still working under the assumption that there exists a way to encapsulate the sql package thoroughly.
- The sql/kv interface is "clean" inasmuch that an abandoned txn is harmless.
- The sql/lease interface is currently not clean, but we could perhaps solve the problem by ensuring lease stuff runs in a different goroutine, so that panics there do not cross to sql to be recovered there, and instead continue to crash the server.
- Same for the sql/schemachange interface.

Is there any other interface we need to care about?

**Comment by knz** [comment]
@tamird also we have seen a bunch of nil dereference panics in sql; unfortunately these may continue to happen even with a thorough discipline to return errors instead of panicing for assertions.

**Comment by andreimatei** [comment]
One thing you've said on the PR thread is that you're trying to prevent against a client crashing a server with a query and then proceeding to retry that query on other servers and crashing all the cluster in a loop. FWIW, different systems at google had ways to protect against such a "query of death" - keep track of recent queries of death and refuse to run them.

> @tamird also we have seen a bunch of nil dereference panics in sql; unfortunately these may continue to happen even with a thorough discipline to return errors instead of panicing for assertions.

The "discipline of returning errors instead of panicking" is misguided, IMHO, as a general rule. When an assertion indicates corrupt state and you can't reason about the consequences of that corruption, you should panic even if you could return an error. If you're more certain about that the system overall can keep going without, e.g., wrong results, then you should return an error.
So it's not like it'd be a good thing to check every pointer before dereferencing it and returning errors if it's nil.

**Comment by bdarnell** [comment]
> FWIW, different systems at google had ways to protect against such a "query of death" - keep track of recent queries of death and refuse to run them.

That requires that queries of death do something other than crashing the process (at google, the "gateway" was fairly dumb and would just record failures of its backends; any query that managed to crash the gateway would not be handled by this system). This is a desirable goal but it will take some restructuring for us to get there. 

I think it's probably a good idea to catch panics in the sql package for 1.0 as long as it's reasonably easy to do and has a switch to enable panic mode (I haven't read the PR in detail yet). AFAICT, there's not much risk of data corruption by catching panics at this level; the risk is mainly of denial-of-service (from things like leaking memory or leases). This risk seems smaller than the certain denial-of-service that results from an uncaught panic.

**Comment by knz** [comment]
This is fixed by #15063  but has been bumped to 1.1.

**Comment by knz** [comment]
Given the friction against the change proposed in #15063 we are probably not going to implement a catch-all for the time being; instead as Jordan suggests:

> Drive-by: I think adding some kind of sqlpanic() would be fairly manageable, and the initial conversion to using those wouldn't be too bad. 

we should replace all explicit uses of `panic()` that denote programmer errors into something that can indeed be caught and recovered from. This does not catch cases of invalid uses of arrays or nil pointers, but would move us forward.

**Comment by knz** [comment]
I do not have a clear solution in mind other than what Jordan is suggesting. De-assigning myself for now. The issue is still high priority IMHO.

**Comment by petermattis** [comment]
> we should replace all explicit uses of panic() that denote programmer errors into something that can indeed be caught and recovered from. This does not catch cases of invalid uses of arrays or nil pointers, but would move us forward.

We can wrap certain calls with defer->recover to catch invalid uses of arrays or nil pointers in those code paths. For example, type checking, `analyzeExpr`, expression evaluation, etc. I think anything in SQL execution that is "functional" (i.e. it doesn't modify the inputs or global state) falls into this category.

**Comment by bdarnell** [comment]
> we should replace all explicit uses of panic() that denote programmer errors into something that can indeed be caught and recovered from

But the risk of recovering from panics is not just the kind of panic, it's also a question of whether the code between the panic and the recover does the right thing as the stack is being unwound. Any code which may (indirectly) call a function which may throw a recoverable panic will need to be written with extra care. Experience with C++ exceptions suggests this is difficult (leading to blanket bans on exceptions in many organizations).

**Comment by jordanlewis** [comment]
This is more or less finished. Let's open new ones as they happen and close this grab bag issue.
