### ISSUE TITLE
sql: investigate why REVOKE/GRANT in RSG is slow

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#9886]
https://github.com/cockroachdb/cockroach/blob/8f6cd21c1123d0e77332a591df5b22a83dc558f5/sql/rsg_test.go#L61

**Comment by spencerkimball** [comment]
@mjibson I'm removing the 1.0 milestone.

**Comment by mjibson** [comment]
Did this a bit. It appears to be not slow anymore so the restriction can probably be removed.
