### ISSUE TITLE
changefeedccl: Better handle rolling restarts

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#99034]
During cluster rolling restarts, changefeeds will enter the state
where changefeed may emit excessive number of duplicates.
Essentially, every time a node restarts, depending on whether or not the
coordinator had a chance to checkpoint, the next restart will re-emit
duplicates.  This will happen for each node restart.

We should try to do better.  

Jira issue: CRDB-25673

Epic CRDB-9185

**Comment by shermanCRL** [comment]
Can we use the graceful restart procedure to do something here? https://www.cockroachlabs.com/docs/stable/node-shutdown.html#prepare-for-graceful-shutdown

It would have to be very non-blocking.

**Comment by miretskiy** [comment]
I have some ideas.

**Comment by miretskiy** [comment]
Fixed via https://github.com/cockroachdb/cockroach/pull/102717
