### ISSUE TITLE
ui: refactor `mapStateToProps` from selectors to functions

### ISSUE THREAD

**Issue by THardy98** [cockroachdb/cockroach#99047]
Across our UI, we `createSelector` when we map state from Redux into our React components. Generally, these selectors are 1-to-1 mapping from fields in state to props, with no computations. In these cases, we do not need to use a selector, whose purpose is to memoize intensive computations between renders. Instead, we should be using a regular function that does this mapping for us, avoiding the overhead of a selector.

Some instances where this occurs are:
- the database pages (databases, database details, database table)
- schema page

Jira issue: CRDB-25677

**Comment by maryliag** [comment]
No longer a priority
