### ISSUE TITLE
storage: TestReplicaLazyLoad is flaky

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#9904]
```
(new) TestReplicaLazyLoad 
	client_raft_test.go:2226: expected replica Raft group to be uninitialized
I161012 11:59:08.847366 15714 http2_server.go:276  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:37622->127.0.0.1:42421: use of closed network connection
```

https://teamcity.cockroachdb.com/viewLog.html?buildId=30394&buildTypeId=Cockroach_UnitTests_Testrace (my PR, but that only contains changes to `make check`).

**Comment by petermattis** [comment]
Easy to reproduce. I'm taking a look.

**Comment by petermattis** [comment]
The replica was loaded by a lease request required to gossip the first range.
