### ISSUE TITLE
Document point-in-time nature of `/_status/tenant_ranges` endpoint results

### ISSUE THREAD

**Issue by abarganier** [cockroachdb/cockroach#99048]
**Is your feature request related to a problem? Please describe.**
The `/_status/tenant_ranges` endpoint provides metadata about ranges for a tenant that exist *at the time the request was processed*. 

The initial tenant creation process involves the creation of initial ranges, followed by an asynchronous process that splits ranges. If a user were to make a `/_status/tenant_ranges` immediately after tenant creation, it's possible that the client would receive a response containing a fewer number of ranges than they would receive if they made another request a short time after. This would be due to the asynchronous nature of this range splitting process.

Ranges are forever in a state of flux. Splitting, compaction, etc. are common operations that happen to ranges, and so this behavior should be intuitively expected by those who understand this. However, we should make this limitation clear in the documentation, to avoid potential confusion in scenarios such as the example one I gave above. 

**Describe the solution you'd like**
Update documentation to note this characteristic of the `/_status/tenant_ranges` endpoint.

**Additional context**
Informs https://github.com/cockroachdb/cockroach/pull/97386

Jira issue: CRDB-25678

Informs: https://github.com/cockroachdb/cockroach/issues/92979

**Comment by andf-crl** [comment]
Created DOC-7271 to track this.

**Comment by lnhsingh** [comment]
Removing this from end-user-facing known limitations since this is an internal interface.
