### ISSUE TITLE
multi-tenant: excessive logging while draining a node

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#99058]
**Is your feature request related to a problem? Please describe.**

While draining a node, I noticed that the following log line was logged repeatedly:

```console
cannot update running tenant services: ‹list-tenants›
```

From what I can tell, there wasn't anything obviously multi-tenant about this cluster. Just two stock workloads (TPC-E and KV) running against it.

**Describe the solution you'd like**

Ideally, we wouldn't spam logs with this message, as it may confuse operators into thinking something is borked in multi-tenant land.

**Additional context**

More context [here](https://cockroachlabs.slack.com/archives/C02HWA24541/p1679339407474919).

Debug zip [here](https://drive.google.com/file/d/1Tsftnywsj1fAwPFhlCLYzorX5twzOhE_/view?usp=share_link) (internal).

```bash
$ grep 'cannot update running tenant services' ./logs/cockroach.grinaker-231-0002.ubuntu.2023-0* | wc -l
499
```

Jira issue: CRDB-25682
Epic: CRDB-23559

**Comment by knz** [comment]
we've addressed this.
