### ISSUE TITLE
Surface in-memory statistics when there are no persisted statistics

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#99060]
We do not surface in-memory SQL statistics to improve SQL Activity pages' quality (performance). Querying for in-memory statistics via virtual tables was the bottleneck causing high latency on SQL Activity pages. For instance, queries against the virtual table had full table scans (lack of index support for virtual tables), leading to higher latency. 

For users just getting started with CockroachDB or onboarding a new feature in a development or testing environment, it may seem odd that SQL statistics are unavailable when there is an active workload. The SQL Activity overview page can be up to an hour stale. 

We should surface in-memory statistics to help mitigate this confusion for new workloads. However, to ensure we don't re-introduce performance issues on the pages, we scope this behavior to only when there are no persisted statistics. 

Jira issue: CRDB-25683

**Comment by maryliag** [comment]
Fixes on https://github.com/cockroachdb/cockroach/pull/100440
