### ISSUE TITLE
kv,jobs: txn_interceptor_span_refresher error when performing job operations

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#99125]
A [nightly test failed with the error](https://teamcity.cockroachdb.com/repository/download/Cockroach_Nightlies_StressBazel/9121862:id/tmp/_tmp/905465f697dc04c39f7d8a82cb057bfe/logTestChangefeedJobControl3004067371/changefeedccltest.log) `kv/kvclient/kvcoord/txn_interceptor_span_refresher.go:691 attempting to append refresh spans after the tracked timestamp has moved forward. batchTimestamp: 1679205414.156461901,0 refreshedTimestamp: 1679205414.219794149,0`

Here's a simpler test that repros the error: [https://gist.github.com/HonoreDB/769a4a98cf2bcabda1a70259c8a13973](https://gist.github.com/HonoreDB/769a4a98cf2bcabda1a70259c8a13973) . The gist also contains a sample test output with goroutine traces.

In both cases, it looks to me like the spans in question are the ones being scanned by the internal SQL executor responsible for populating the virtual SHOW CHANGEFEED JOBS table and for updating job status. So my tentative very ill-informed theory is that the same transaction is being shared illegally among multiple isql.DB handles.

I also can't rule out that this is a test-only issue, but the test is at least not explicitly using the same transaction concurrently for anything.

Jira issue: CRDB-25712

**Comment by yuzefovich** [comment]
I think this is a dup of #99093 and has been fixed in #99325
