### ISSUE TITLE
QA: crdb_internal.redactable_sql_constants syntax error on query

### ISSUE THREAD

**Issue by rharding6373** [cockroachdb/cockroach#99132]
When trying to pass the following query through `crdb_internal.redactable_sql_constants` verbatim, I encounter a syntax error. `\hf crdb_internal.redactable_sql_constants` is not immediately helpful in figuring out what the issue is.

```
CREATE TABLE t1 (id INT, colJSON JSON);

SELECT id, colJSON FROM t1 WHERE colJSON?'should_be_redacted';
  id | coljson
-----+----------
(0 rows)

SELECT crdb_internal.redactable_sql_constants('SELECT id, colJSON FROM t1 WHERE colJSON?'should_be_redacted'');
invalid syntax: statement ignored: at or near "should_be_redacted": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
SELECT crdb_internal.redactable_sql_constants('SELECT id, colJSON FROM t1 WHERE colJSON?'should_be_redacted'')
                                                                                         ^
HINT: try \hf crdb_internal.redactable_sql_constants
```

There is probably an obvious way to format the query so that it can work as an input. However, it would be nice if there was a way putting queries could be streamlined or some documentation.

Jira issue: CRDB-25716

**Comment by michae2** [comment]
I think in general when quoting arbitrary SQL, [dollar-quotes](https://www.cockroachlabs.com/docs/stable/sql-constants.html#dollar-quoted-string-literals) are the most likely to work without causing a syntax error. For example, using `$stmt$` as dollar-quotes:

```
demo@127.0.0.1:26257/movr> SELECT crdb_internal.redactable_sql_constants($stmt$SELECT id, colJSON FROM t1 WHERE colJSON?'should_be_redacted'$stmt$);
               crdb_internal.redactable_sql_constants
---------------------------------------------------------------------
  SELECT id, coljson FROM t1 WHERE coljson ? ‹'should_be_redacted'›
(1 row)

Time: 1ms total (execution 1ms / network 0ms)
```

I'll add this to the function help message.
