### ISSUE TITLE
sql: type error on ABS(NULL)

### ISSUE THREAD

**Issue by eisenstatdavid** [cockroachdb/cockroach#9920]
```
root@:26257> SELECT ABS(NULL);
pq: unknown signature for ABS: ABS(NULL)
root@:26257> SELECT ABS(NULL :: FLOAT);
+------------------+
| ABS(NULL::FLOAT) |
+------------------+
| NULL             |
+------------------+
(1 row)
```

I would expect `NULL` in the first case as well.

**Comment by eisenstatdavid** [comment]
cc @knz @nvanbenschoten

**Comment by eisenstatdavid** [comment]
My current plan is, if there are no viable overload candidates and at least one NULL-typed argument, simplify the expression to NULL (as we do with UnaryExpr and BinaryExpr).

**Comment by eisenstatdavid** [comment]
Hmm, that breaks typechecking on, e.g., `concat_ws(string, string, int, NULL, int)`

**Comment by jordanlewis** [comment]
This might be related to #12968.

**Comment by eisenstatdavid** [comment]
Yep, duplicate of that issue.

**Comment by nvanbenschoten** [comment]
This is actually a subtly different issue than #12968, so I'm going to reopen for now. Fix incoming though.
