### ISSUE TITLE
kvserver: TestTransferRaftLeadership flakes

### ISSUE THREAD

**Issue by pav-kv** [cockroachdb/cockroach#99213]
The test timed out with:

```
Failed
=== RUN   TestTransferRaftLeadership
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/09357cecfdbbab5926b4b055936a9b62/logTestTransferRaftLeadership739910387
    test_log_scope.go:79: use -show-logs to present logs inline
    client_raft_test.go:4118: condition failed to evaluate within 45s: expected raft leader be 2; got 1
    panic.go:522: -- test log scope end --
--- FAIL: TestTransferRaftLeadership (46.39s)
```

Happened 2 times over last 1000 runs in CI.

Jira issue: CRDB-25762

**Comment by pavelkalinnikov** [comment]
Seems similar to #26130 and #25788.

**Comment by pavelkalinnikov** [comment]
https://teamcity.cockroachdb.com/viewLog.html?buildId=9191917

**Comment by pavelkalinnikov** [comment]
Log: https://teamcity.cockroachdb.com/repository/download/Cockroach_UnitTests_BazelUnitTests/9191895:id/tmp/_tmp/09357cecfdbbab5926b4b055936a9b62/logTestTransferRaftLeadership739910387/kvservertest.log

**Comment by erikgrinaker** [comment]
Can you have a closer look at this @pavelkalinnikov?

**Comment by pavelkalinnikov** [comment]
Reproduces under stress:
```
$ dev test pkg/kv/kvserver --filter=TestTransferRaftLeadership --verbose --vmodule='*=3' --stress
```

Seeing a bunch of messages like:
```
I230328 11:59:25.335738 403 go.etcd.io/raft/v3/raft.go:1196 ⋮ [T1,n1,s1,r63/1:‹/System{\x00aaa-test…-/NodeLive…}›] 135731  1 [term 6] transfer leadership to 2 is in progress; dropping proposal
```

So the leadership transfer is [in progress](https://github.com/etcd-io/raft/blob/918455b897764d8e4d12af70657280365ffaaa04/raft.go#L1195-L1198), but never completes within 45s.

**Comment by pavelkalinnikov** [comment]
Node [declines election](https://github.com/etcd-io/raft/blob/918455b897764d8e4d12af70657280365ffaaa04/raft.go#L1799) because `IsLearner` is true.
