### ISSUE TITLE
jobs: Ensure that newly updated queries perform well

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#99219]
Recent changes to jobs queries (#98608) modified
some of the queries used to perform jobs related activities (adopt, show jobs, etc).
Specifically, WITH clauses were added.

Ensure that those new queries do not regress in terms of performance.
In particular, we should verify that the query plans for common queries
(e.g. querying WHERE id=xxx, or scanning with SHOW jobs) produce
good execution plan before/after the changes.  That the number of rows
(cardinality) remains the same.

Particular attention should be given to the queries that leverage
`FOR UPDATE` clause.

Jira issue: CRDB-25767

**Comment by adityamaru** [comment]
I did, thanks for flagging this. Edited my comment

**Comment by dt** [comment]
We did some testing and fixing here, and these queries are no longer "new" so closing this as done.
