### ISSUE TITLE
sql: improve statement fingerprint generation

### ISSUE THREAD

**Issue by THardy98** [cockroachdb/cockroach#99220]
Historically, we've run into a number of issues/escalations with our statement fingerprint generation. This is an issue to track the problems we've identified and resolved with fingerprint generation:

Issues:
- Statements with differently ordered columns generate different fingerprints. This greatly increases the number of statement fingerprints we generate, despite the statements being effectively the same. In the past, we've seen this be the cause of severe degradation of our sql stats systems (sql stats flush job is unable to keep up with the number of fingerprints being generated, system tables get excessively large very quickly).
https://github.com/cockroachdb/cockroach/issues/77963
- Remove "failed" as part of the fingerprint creation. This reduces fingerprint cardinality and groups failed/successful statements under the same fingerprint
https://github.com/cockroachdb/cockroach/issues/97176
- Test our fingerprint generation with different ORMs, to identify further issues and improvements with our fingerprint generation
https://github.com/cockroachdb/cockroach/issues/97073

Jira issue: CRDB-25768

**Comment by nkodali** [comment]
Closing this parent issue, as we're tracking the individual improvements above separately.
