### ISSUE TITLE
makefile: auto-prepend `./pkg/` to PKG?

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#9923]
suggested by @RaduBerinde:
```
I was thinking the same. It could add it if you do PKG=sql
if you have ./something it wouldn't
```

**Comment by tschottdorf** [comment]
I also dislike typing the redundant `./pkg` all the time, but I feel that we should stop adding magic there.

**Comment by petermattis** [comment]
We could add a shim `pkg/Makefile` so that `cd pkg; make test PKG=./storage` would work. Maybe. I'd have to think about what `Makefile` magic would be required.

**Comment by tschottdorf** [comment]
perhaps the `pkg/` Makefile should be the real one and `Makefile` would be the shim. Or we just suck it up and type `./pkg`. Wonder what other projects with this setup do.

**Comment by petermattis** [comment]
We should dump make in favor of [bazel](https://www.bazel.io/).

**Comment by RaduBerinde** [comment]
I don't see a big problem with always prepending `./pkg` to (each token in) PKG. Even `./...` -> `./sql/./...` probably works

**Comment by petermattis** [comment]
What if the user already included `./pkg` (i.e. `PKG=./pkg/storage`)? You'd transform that to `./pkg/pkg/storage` which wouldn't work. I like to use autocomplete so that would directly affect me.

**Comment by RaduBerinde** [comment]
Ah, I see. It would need to check if it already starts with `./pkg`. Before my last OS upgrade, my shell for some reason deleted `PKG=` when I tried to autocomplete so I got used to not using it :)

**Comment by bdarnell** [comment]
What if PKG is absolute? No one would type that by hand but I've been meaning to hook up `go-test.el` to construct commands for our makefile instead of plain `go test` commands, and it uses absolute package names.

**Comment by dt** [comment]
As an alternative to arbitrary string manipulation, we could have a whitelisted set of shorthands that mapped to particular expansions, e.g. `sql`=> `./pkg/sql`... or even, to keep it even simpler, just add those as new targets, eg `make testsql`

**Comment by bdarnell** [comment]
If this were a real programming language instead of a makefile, then we could have a search path and take the first one that actually exists (repo root, `./pkg`, `$GOPATH`, etc). We're not getting much value out of make's dependency tracking so it shouldn't be too hard to port away from make.

**Comment by petermattis** [comment]
My comment to replace `make` with `bazel` was only partially facetious.

We could probably write a `make` variable transformation that prepends `./pkg` to every element in `PKG` that is not a directory (i.e. do something akin to what @bdarnell is suggesting with a search path). But I think we're quickly reaching the limit of how much time we should spend futzing with `make`.

**Comment by dt** [comment]
I think the helper makefile added to `pkg` serves a close enough purpose for now that I'm going to call this one good enough.
