### ISSUE TITLE
roachprod: `GetInternalIP` is unreliable

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#99277]
The current implementation of `GetInternalIP` calls `hostname --all-ip-addresses`, and returns the stdout of that command as the internal IP of the VM.

This has the implicit assumption that the VM has a single private IP, which may not be the case depending on what's running in the VM. When there are multiple IPs, it will return a string like `10.0.1.23 10.0.2.39`.

This is especially tricky to debug in cases where it's used in larger scripts; as a recent example, this made the scripts run by the `SetupSSH` logic [1] wrong in a way that is hard to debug.

[1] https://github.com/cockroachdb/cockroach/blob/1e2ea17a3dbb4b4c8a2942105abc6712d90b477e/pkg/roachprod/install/cluster_synced.go#L1149-L1164

Jira issue: CRDB-25802

**Comment by srosenberg** [comment]
I recall noticing this earlier [1]. I guess we thought this was not a critical issue since most (all?) roachprod VMs have a single NIC, and hence only one private ip. Do you recall which VMs had multiple?

[1] https://github.com/cockroachdb/cockroach/issues/91188#issuecomment-1305838001

**Comment by renatolabs** [comment]
> Do you recall which VMs had multiple?

`grinaker-231:9` 🙂 

Or, more generally, if you run Docker in the VM (which we do if we're running TPC-E currently), the `docker0` bridge interface will be created and its IP will be returned by `hostname --all-ip-addresses`.

**Comment by srosenberg** [comment]
> if you run Docker in the VM

For sure. I was excluding that option since I thought we rarely do this with roachprod clusters afaik. Of course, I forgot that `tpc-e` requires docker 🤦 

```
15d4c57dc056   cockroachdb/tpc-e:latest   "driver --customers …"   47 minutes ago   Up 47 minutes             awesome_dewdney
```

In other words, we need to fix this :)
