### ISSUE TITLE
Cockroach Cloud instructions to download CA cert have incorrect curl command-line options that produces warning

### ISSUE THREAD

**Issue by hand-crdb** [cockroachdb/cockroach#99307]
**Describe the problem**

As part of creating a cloud cluster, the cloud management web page gives customers the ability to download the CA certificate and provides a `curl` command to do so.  This `curl` command contains both options `-o` and `-O` which cannot be used together.  When the customer runs the `curl` command that is displayed, it results in a warning that can be confusing:

> `Warning: Got more output options than URLs`

**To Reproduce**

Create a new cloud cluster using the cloud management console and navigate to where it lets you download the CA certificate.  It will display a `curl` command with the above-mentioned issue.

To illustrate, you can run the following command on a MacBook and get the output shown:

```
> curl -o /dev/null -O https://cockroachlabs.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    45  100    45    0     0    191      0 --:--:-- --:--:-- --:--:--   193
Warning: Got more output options than URLs
```

**Expected behavior**

The provided `curl` command should not produce the warning because it should not specify both the `-o` and `-O` command-line options.  Removing just the `-O` works and makes the warning go away.

**Additional data / screenshots**

Please see attached screenshot

<img width="737" alt="curl_o_O_screenshot" src="https://user-images.githubusercontent.com/76179780/227053762-343b5c86-cde8-4a4c-bcc5-570aeec2a23e.png">

**Environment:**

- Cockroach Cloud management console.  
- The `curl` command was run on a MacBook.  (Different operating systems may have different flavors of the `curl` command, which may produce different results.)

**Additional context**

The impact is minimal, but the warning is confusing.

Jira issue: CRDB-25810

**Comment by yuzefovich** [comment]
I don't know where to route this, cc @jordanlewis
