### ISSUE TITLE
cli: document how to run interactive_tests

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#9936]
These seem to be completely undocumented (or at least it's not documented if you simply stumble into the directory and want to write a new one).

**Comment by knz** [comment]
So are you thinking about docs to run them (as the title of the issue suggests) or write them? Or both?

**Comment by tschottdorf** [comment]
I could probably figure out how to write one because I can riff on what's there, but I have no idea how to run them.
