### ISSUE TITLE
sql/schemachanger: add telemetry to know which statements are run under declarative vs legacy schema changer

### ISSUE THREAD

**Issue by fqazi** [cockroachdb/cockroach#99386]
Currently, we have no telemetry that tells us how many schema changes are used in the declarative schema changer and which ones are forced to fall back. Having some type of telemetry would allow us to understand usage patterns and limitations hit by real-world customers. Also, give us a good indication of the coverage we are offering today

Jira issue: CRDB-25859

Epic CRDB-27601

**Comment by dikshant** [comment]
Ah yes we should definitely work on this for 23.2

**Comment by rafiss** [comment]
Do we already have a sense of how much effort is required? If it's low, I'd vote for starting this work right now during the stability period.

**Comment by ajwerner** [comment]
We would want to add a field here: https://github.com/cockroachdb/cockroach/blob/03e6a5b3c24f0da568dcc7204d3dedc0afcf29d5/pkg/sql/exec_log.go#L439

If the plan in `curPlan` has a `schemaChangePlanNode` then it ran with the declarative schema changer. That should be easy to detect.
