### ISSUE TITLE
sql: add testing for virtual columns that are being dropped during UPDATE/DELETEs on tables

### ISSUE THREAD

**Issue by fqazi** [cockroachdb/cockroach#99381]
Testing was written in https://github.com/cockroachdb/cockroach/pull/98692 but this never got merged.

The bug came up in this support case: https://github.com/cockroachlabs/support/issues/2457. The above testing would have prevented the escalation.

---

Original issue text:

If we have an on-going DROP COLUMN for virtual computed columns then DELETE/UPDATES to the table can fail until
this mutation completes. This can be observed in the simple scenario (this is agnostic to legacy vs declarative both of them will hit issues in the runtime):

```
CREATE TABLE t (i INT PRIMARY KEY, j INT, k INT DEFAULT 32 ON UPDATE 42, m INT as (i +j) VIRTUAL);
SET CLUSTER SETTING jobs.debug.pausepoints='newschemachanger.before.exec';
set sql_safe_updates=false;
ALTER TABLE t DROP COLUMN m;
delete from t;
```

Jira issue: CRDB-25855

Epic CRDB-30350

**Comment by rafiss** [comment]
Closing this in favor of https://github.com/cockroachdb/cockroach/issues/108181
