### ISSUE TITLE
Stuck on PostCommitPhase stage 7 of 15 with 1 ValidationType op pending

### ISSUE THREAD

**Issue by Southclaws** [cockroachdb/cockroach#99407]
I'm dogfooding CRDB cloud to move to, after playing with our seed data I decided to give it a run with a production dump (our product is quite small so it's not a huge dataset but still fairly significant - 5.73MB dump size, a handful of tables and roughly in the 3-4 figures row counts)

For this I ran a simple Postgres copy command (backup from DB X then restore to DB Y)

However, it's stuck on `PostCommitPhase stage 7 of 15 with 1 ValidationType op pending` and the timing estimation says `00:00:00 remaining` so I'm not really sure what to do.

Here's the command (in task format)

```yaml
    cmds:
      - pg_dump
        --format=c
        --file={{.LOCAL_OUTPUT_PATH}}
        --schema=public
        --exclude-table="_prisma_migrations"
        {{.PRODUCTION_DATABASE_URL}}
      - pg_restore
        --format=c
        --if-exists
        --clean
        --schema=public
        --dbname={{.CRDB_DATABASE_URL}}
        {{.LOCAL_OUTPUT_PATH}}
```

**Expected behavior**

If the process is going to take a while after this command completes, some feedback on the dashboard.

**Additional data / screenshots**

There's a job on the dashboard that hasn't changed state for about 20 minutes:

![image](https://user-images.githubusercontent.com/1636971/227291301-6bafeb71-3563-4a09-bbd0-abbbd9f609b6.png)

The job itself is just:

```
ALTER TABLE defaultdb.public.accounts ADD CONSTRAINT accounts_pkey PRIMARY KEY (id)
```

And the DB is completely inaccessible from any tool/app now.

**Environment:**
 - CockroachDB version v22.2.6
 - Server OS: Serverless / AWS
 - Client app pg_dump/pg_restore

**Additional context**

This is on the cloud serverless product not self-hosted.

Jira issue: CRDB-25872

**Comment by Southclaws** [comment]
Some more info:

I just tried to spin up our app, which uses Ent to migrate schemas on startup in a non-destructive way, and got this very odd looking error:

```
ERROR: relation "accounts" (124): secondary index "accounts_email_key" contains dropped key suffix column "crdb_internal_column_25_name_placeholder" (SQLSTATE XXUUU)
create index "accounts_email_key" to table: "accounts"
```

I'm not sure what `crdb_internal_column_25_name_placeholder` is but it looks like some internal detail that should not be there!

**Comment by dikshant** [comment]
Have you tried our Schema conversion tool to convert the schema first?
https://www.cockroachlabs.com/docs/stable/migration-overview.html#step-1-convert-your-schema

**Comment by fqazi** [comment]
@Southclaws The schema change is taking a long time for some reason, can you check the cockroach.log it should hopefully provide some hints.

Let me look at the second error, but just based on the message it looks like something went wrong dropping a column earlier.

**Comment by ajwerner** [comment]
If this is not a sensitive cluster or schema and you'd be willing to share the metadata with the team, it'd be great if we could get a [debug zip](https://www.cockroachlabs.com/docs/stable/cockroach-debug-zip.html) for the cluster to try to root cause the problem. If it is sensitive, we can collect more narrow information and work from that. In particular, if you could share `select encode(descriptor, 'hex') from system.descriptor where id = 124` that will provide just the state of that table. We can provide more private channels for data sharing if you'd prefer.

**Comment by ajwerner** [comment]
Did you change the GC ttl of any tables?

**Comment by Southclaws** [comment]
I left this for a while as it wasn't a priority and it seemed to have solved itself.

fwiw this was on the cloud offering, so I'm not sure if I can access the stdout logs or log file.
