### ISSUE TITLE
catalog: schema observability on descriptor usage

### ISSUE THREAD

**Issue by dikshant** [cockroachdb/cockroach#99428]
When schema-related escalations happen, we lack metrics for things like which descriptors are most frequently used and how long lease renewals take. These are critical when diagnosing schema relation escalation and we should add these metrics. This issue is going to track the list of needed metrics during schema escalations:

1. usage of descriptors
2. lease renewals

Jira issue: CRDB-25877

**Comment by ajwerner** [comment]
The problem which prompted this was answering the question: which tables are actually getting used frequently. 

It's also very plausible that this is not a good fit for low-level catalog metrics or observability but rather should be derived from statement statistics or other observability features.

----

One additional note here is that it might be worthwhile to have metrics not about individual descriptors, but rather about the rate of and time being spent doing lease acquisitions. We do have counters for lease acquisitions, but nothing about latency. We could add a histogram. We'll track that work in https://github.com/cockroachdb/cockroach/issues/99700 and close this.
