### ISSUE TITLE
suggestion: document minimum number of servers

### ISSUE THREAD

**Issue by jojo05** [cockroachdb/cockroach#9945]
It would be useful to document the most basic configurations, i.e. with 2, 3 or 4 servers to get familiar with cockroachdb.

Also, will you support  rpi3 ARM64 nodes?  
rpi3 +  1TB disk would be great for additional nodes  
http://wdlabs.wd.com/products/wd-pidrive-1tb-kit/

**Comment by dianasaur323** [comment]
@jojo05 Thanks for this suggestion - this is top of mind as we move into next year. Adding @jseldess and @sploiselle

**Comment by jojo05** [comment]
Got this today:

https://www.raspberrypi.org/magpi/western-digital-pidrive/

WDLabs has launched the third generation of its PiDrive products. Offering an affordable hard drive storage solution for the Raspberry Pi.

The latest drive is called ‘Foundation Edition’. The new range includes two hard drive options – 250GB and 375GB – along with a 64GB USB flash drive.

While similar in format to previous PiDrive models, this edition features a microSD card preloaded with the Raspberry Pi Foundation’s NOOBS installer.

**Comment by jseldess** [comment]
Thanks, @jojo05 and @dianasaur323. Is this question about the recommended minimum number of servers in a cluster, or is it more about the recommended attributes of servers (storage, etc)? 

If the former, I think we provide important guidance in [Recommended Production Settings](https://www.cockroachlabs.com/docs/recommended-production-settings.html). If the latter, yes, we're hoping to create guidance early next year. We have a few related open issues:
- https://github.com/cockroachdb/docs/issues/380
- https://github.com/cockroachdb/docs/issues/571
- https://github.com/cockroachdb/docs/issues/869

**Comment by jojo05** [comment]
The former. 

I would like to see an example focused on two servers and then adding a third later on. 
Two is the absolute minimum to provide data protection (three for even higher data protection)

**Comment by jseldess** [comment]
Thanks for the clarification, @jojo05. I just realized that the guidance I was thinking of is on another page about replication: https://www.cockroachlabs.com/docs/configure-replication-zones.html#nodereplica-recommendations. I'll find a way to include or mention that info on the recommended production settings page. 

As for examples, have you taken a look at the [manual deployment](https://www.cockroachlabs.com/docs/manual-deployment.html) or [cloud deployment](https://www.cockroachlabs.com/docs/cloud-deployment.html) docs? They all show how to start a first node and then add additional nodes. The [getting started tutorials](https://www.cockroachlabs.com/docs/start-a-local-cluster.html) also show this in the context of a local test cluster.

**Comment by bdarnell** [comment]
@jojo05 In CockroachDB's quorum-based replication, a cluster of two servers is not sufficient to provide data protection. If one of the two nodes is lost, then the other will be unable to elect itself leader and the cluster cannot recover. If you have more than one node, you should have at least three. (for a lower-cost replication option you could consider a single node with a two-disk RAID array)

**Comment by jojo05** [comment]
Thanks. 3 is the answer then. The manual deployment docs are good. 
You can close the issue. thanks

Do you plan to provide a distributed file system also, like with Spanner ? (for a separate issue)

**Comment by spencerkimball** [comment]
@jojo05 we have talked about a more sophisticated BLOB storage option, but that's unlikely to happen in 2017.

**Comment by jojo05** [comment]
thanks
