### ISSUE TITLE
kvserver: metric and logging to pinpoint liveness leaseholder

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#99472]
**Is your feature request related to a problem? Please describe.**

The `leases.expiration` metric has been useful as a tool to pinpoint the liveness leaseholder, but it's annoying because there are currently two expiration-based ranges: meta1/2 and the liveness range. Also, we're possibly going to have many more expiration-based ranges. The liveness range is very important: we need to have a perfect lease history for it.

**Describe the solution you'd like**

- [ ] Add a metric `leases.liveness` that is 1 if and only if the store has a liveness replica that is active leaseholder.
- [ ] log whenever a liveness lease is applied, especially if it's a non-cooperative acquisition.

x-ref https://github.com/cockroachlabs/support/issues/2182

Jira issue: CRDB-25893

Epic CRDB-27235

**Comment by erikgrinaker** [comment]
Removing the GA-blocker label, this doesn't rise to that level and can wait for 23.2 or a backport.
