### ISSUE TITLE
kv: unnecessary allocator log

### ISSUE THREAD

**Issue by andrewbaptist** [cockroachdb/cockroach#99474]
**Describe the problem**

When running a TPCC test, I looked through the logs for error and warn messages to ensure things were clean. I saw the following repeated multiple times:

`E230323 13:39:23.472852 843520 kv/kvserver/replicate_queue.go:511 ⋮ [T1,n1,s1,r67225/1:‹/Table/108/1/1{1560/…-2098/…}›,*kvpb.AdminScatterRequest] 4559  AllocatorAction ‹› unsupported in metrics tracking`

I didn't look at the source of this, but this should not be reported as an error.

Jira issue: CRDB-25895

**Comment by kvoli** [comment]
Will be closed on https://github.com/cockroachdb/cockroach/pull/99515

**Comment by kvoli** [comment]
Closed on https://github.com/cockroachdb/cockroach/pull/99515
