### ISSUE TITLE
tsdb: metrics graphs reporting abnormally high values

### ISSUE THREAD

**Issue by abarganier** [cockroachdb/cockroach#99486]
**Describe the problem**

Original thread: https://cockroachlabs.slack.com/archives/C01CNRP6TSN/p1679669195626919

The roachprod cluster in the above linked Slack thread is experiencing abnormally high stats readings in DB Console metrics charts. For example, normalized CPU Usage charts are reading > 1000% per node, memory usage per-node > 250GB, etc.

We recently merged https://github.com/cockroachdb/cockroach/pull/98077, which modified the TSDB query code to work for in-process tenants. It's possible we introduced a bug into the aggregation logic.  

**To Reproduce**

1. Set up a roach prod cluster (not multi-tenant - note the specific roachprod cluster where this was discovered did not have multiple tenants).
2. Generate a workload against the cluster.
3. Observe abnormally high metric readings. 

**Additional data / screenshots**
<img width="981" alt="Screenshot 2023-03-24 at 11 29 02 AM" src="https://user-images.githubusercontent.com/8194877/227569985-7caa4d6d-1dec-4a36-b468-873270337810.png">
<img width="981" alt="Screenshot 2023-03-24 at 11 28 56 AM" src="https://user-images.githubusercontent.com/8194877/227569991-60dae399-8da6-4f87-a115-2410d44598f6.png">

Jira issue: CRDB-25898

**Comment by dhartunian** [comment]
This is reproducible with a 10 node demo cluster where only a single node is behaving badly.

```
./cockroach demo --multitenant=false --nodes 10 --http-port 30000
```
(port selection is to make the +1 increment per-node from 8080 not bump into other stuff running locally)

<img width="2168" alt="Screenshot 2023-03-24 at 11 53 03" src="https://user-images.githubusercontent.com/986307/227581261-5e728f9d-df60-4bdc-a09c-224efb875ec2.png">
<img width="2168" alt="Screenshot 2023-03-24 at 11 52 16" src="https://user-images.githubusercontent.com/986307/227581340-cf3083d2-9a7a-46b5-bdaf-a7316b7dbe09.png">
