### ISSUE TITLE
.NET support via Npgsql - type loading

### ISSUE THREAD

**Issue by roji** [cockroachdb/cockroach#9955]
Hi, I'm the maintainer of [Npgsql](http://github.com/npgsql/npgsql), the open-source .NET driver for PostgreSQL. I've received a [request](https://github.com/npgsql/npgsql/issues/1321) from a user to support Cockroach, and would you like to understand what that would entail.

When Npgsql first connects to a database, it queries PostgreSQL's pg_type table to understand what data types are supported and what their OIDs are. This information is cached and used in all communication with that database. However, Cockroach doesn't seem to have this system table - what is the recommended method for knowing what data types are supported, and what their OIDs are?

**Comment by a-robinson** [comment]
Our pg_catalog support is still a work in progress. cc @nvanbenschoten for more info

**Comment by roji** [comment]
Do you have some alternate way for a client driver to know which data types are supported and especially what their OIDs are? Or are they supposed to hardcode OIDs in source code?

**Comment by bdarnell** [comment]
We don't currently support any way to query for information about supported types, although support for the `pg_type` table will come in the future. It appears that most drivers hardcode a list of OIDs for the core types (our OIDs are the same as postgresql's).

**Comment by nvanbenschoten** [comment]
What @bdarnell said seems to be true [in practice](https://github.com/lib/pq/blob/master/oid/types.go), many drivers/ORMs hardcode standard OIDs themselves, falling back to querying the `pg_catalog.pg_type` table only to get [more information](https://github.com/rails/rails/blob/bc9dc418259f1db0f14ed895e8469b7839ef474b/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L560) on user defined types. Because we are compliant with PG's OID scheme, we haven't run into too much of an issue with this. 

Still, the `pg_type` table will be included in a release in the near future, and thanks to recent work by @cuongdo, should be accessible from your supported types [query](https://github.com/npgsql/npgsql/blob/ff365501480b12b8c809874ceea19e06ea56fb64/src/Npgsql/TypeHandlerRegistry.cs#L171).

**Comment by roji** [comment]
OK. So if I understand you guys, you recommend waiting until the pg_type support is implemented on your end (any estimate of when that will be released)? That's good because I'd like to avoid hardcoding the OIDs  just for cockroachdb support.

**Comment by nvanbenschoten** [comment]
If it means that you don't have to update your driver then yes, that would probably be the easiest solution. We should be releasing a build with `pg_type` support either next week or the week after. Looking at your GenerateTypes query again though, I see references to the `pg_proc` table as well. This table may take a little longer to add, as it will require some reorganizing of our sql evaluation code.

**Comment by roji** [comment]
Yeah, unfortunately PostgreSQL makes it a bit difficult to identify array types in pg_type, so Npgsql looks at the actual send/receive functions used on the datatype.

If it makes sense in your overall roadmap to add support for pg_type and pg_proc (in order to be more PostgreSQL-compatible), that would be best. If not, let me know and I'll see what can be done.

**Comment by jordanlewis** [comment]
Hi @roji, we've added the `pg_type` and `pg_proc` tables since the last time this issue was updated. If you have time, could you see if that work has unblocked support for Npgsql?

**Comment by roji** [comment]
@jordanlewis great!

The Npgql type-loading SQL also queries `pg_namespace` (which I assume you guys support), and `pg_range` as well for PostgreSQL ranges. `pg_range` can also be empty (in which case ranges will not be supported), but the table has to be there or the query will fail).

I do understand this is a lot to ask from a PostgreSQL-compatible (but not PostgreSQL) database, and you're not the only ones with issues like this. I'll think about adding a simpler type loading mode which hard-codes type OID values, obviating any sort of type querying.

In the meantime thanks again for your efforts on this.

**Comment by jordanlewis** [comment]
We do in fact support `pg_namespace` and (an empty) `pg_range`. We need to support these tables for compatibility with several other ORMs as well. While the type querying is troublesome for databases trying to emulate Postgres, I think hard-coding OIDs might be worse, as it leaves databases that don't support every type in Postgres with no recourse.

Hopefully, these tables will be sufficient for your library's type queries! It would be really helpful to us if you could actually test the library against CockroachDB and let us know if there are any other issues. If you're too busy, perhaps we could persuade the user who made the request initially to try it out.

**Comment by roji** [comment]
@jordanlewis great to hear! I'm also glad to hear I'm not the only driver/ORM causing issues with PostgreSQL compatibility and catalog tables. I'm not sure how type OID hard-coding could make matters worse - it would probably just bomb the moment a user actually tried to use the unsupported type. But no matter.

I'm afraid I don't know anything about CockroachDB, setting it up, etc. and don't have enough spare time to dive into it at the moment. I'll post back on the original issue for the user to test. If you feel like trying a minimal Npgsql hello world on your end that's another option.

Thanks again!
