### ISSUE TITLE
Add expiration time of client certificates to the Sessions page with warning if expiration is close to now

### ISSUE THREAD

**Issue by smcvey** [cockroachdb/cockroach#99584]
**Is your feature request related to a problem? Please describe.**
Over time, client certificates will expire.  It's easy to forget to regularly renew them and then run into an issue where a connecting application can no longer connect, creating downtime.

**Describe the solution you'd like**
The expiration date/time should be shown in the Sessions page in the DBConsole.  Make it prominent (red warning) if the expiration is within a month or so.

relates to https://github.com/cockroachdb/cockroach/issues/99422

Jira issue: CRDB-25954

**Comment by abhinavg6** [comment]
Since the client certs are managed by the customers in their own cert management tooling, those should be tracked through those tools rather than through CRDB. We don't even store client certs in CRDB, but only have access to the CA cert that's used to sign those certs.

**Comment by rafiss** [comment]
Is https://github.com/cockroachdb/cockroach/pull/103592 enough to resolve this? It adds a metric, but not a warning to the Sessions page. cc @cameronnunez

**Comment by cameronnunez** [comment]
My understanding was that the metric was a must-have, I think having it visible in DB Console was a "nice-to-have." Not sure if we still need to do the latter 

cc @sean-

**Comment by maryliag** [comment]
No longer a priority
