### ISSUE TITLE
ccl/backupccl: cluster backups taken during upgrade can fail to be restored due to missing role_id column

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#99709]
I've been observing test failures for backups that are created while the cluster is upgrading from 22.2.6 to 23.1-2. The following backup statement runs when a cluster is upgrading (all nodes running 23.1-2, `preserve_downgrade_option` is reset, and migrations are running concurrently with backup):

> ```BACKUP INTO 'gs://cockroachdb-backup-testing/4_22.2.6-to-current_cluster_all-planned-and-executed-on-current_finalizing_rPHb?AUTH=implicit' AS OF SYSTEM TIME '1679842180490423516.0000000000' WITH detached```

After the upgrade finalizes, attempts to restore the backup above may result in the following error:

> ```error restoring: pq: restoring system table role_members: inserting data to system.role_members: role_members-data-insert: null value in column "role_id" violates not-null constraint```

I'm getting this error while working on unmerged changes to the existing `backup/mixed-versions` roachtest. If necessary, I can push the WIP to a branch and help with reproduction. In the mean time, I thought it would be useful to create this issue for investigation. You can find the artifacts below:

[artifacts_restore_error_null_role_id.zip](https://github.com/cockroachdb/cockroach/files/11081961/artifacts_restore_error_null_role_id.zip)

@cockroachdb/disaster-recovery Let me know how I can help debug and fix the issue.

Jira issue: CRDB-26033

Epic CRDB-19134

**Comment by livlobo** [comment]
cc @andyyang890

**Comment by andyyang890** [comment]
@renatolabs Would you be able to see if your test still fails after rebasing on to this draft PR https://github.com/cockroachdb/cockroach/pull/100014?

**Comment by renatolabs** [comment]
I've run this a number of times and haven't observed the failure reported here. Closing.
