### ISSUE TITLE
ui: /overview/map doesn't load

### ISSUE THREAD

**Issue by kvoli** [cockroachdb/cockroach#99714]
**Describe the problem**

When testing a large (81 node) cluster, the `overview/map` UI page doesn't load after 2 minutes.
![image](https://user-images.githubusercontent.com/39606633/228043719-a6ebf026-ddc1-4373-a9d3-ace8a1e2108a.png)

**To Reproduce**

1. Run cockroach (uncertain if specific to a cluster of this size).
2. open `/overview/map`
3. Check if page loads

**Expected behavior**
The page loads and displays the node map.

**Additional data / screenshots**
There appear to be lots of (200) GET responses, however I'm not certain if they are related.

**Environment:**
 - CockroachDB version v23.1.0-alpha.8-dev-68d4c2e9ec01136e7ae1de1c7e402f80054fd953
 - Server OS: [e.g. Linux/Distrib] Ubuntu 20.02
 - Client app [e.g. `cockroach sql`, JDBC, ...] TPCC

![image](https://user-images.githubusercontent.com/39606633/228044314-d8c6c329-11fe-4e1e-83d9-e336271047c4.png)

Jira issue: CRDB-26038

**Comment by kvoli** [comment]
reproduces with single node:

```
./cockroach start-single-node --insecure --store=type=mem,size=8GiB
```

**Comment by koorosh** [comment]
Node Map view is available only for CCL builds. For insecure build, it should show following screen instead of the loading indicator:
<img width="1338" alt="Screenshot 2023-03-27 at 22 52 44" src="https://user-images.githubusercontent.com/3106437/228160265-f713034a-495d-455c-8c80-b02bdfafdafe.png">

**Comment by kvoli** [comment]
> Node Map view is available only for CCL builds. For insecure build, it should show following screen instead of the loading indicator:
> <img width="1338" alt="Screenshot 2023-03-27 at 22 52 44" src="https://user-images.githubusercontent.com/3106437/228160265-f713034a-495d-455c-8c80-b02bdfafdafe.png">
> 

Is it a bug that this page doesn't show then?

**Comment by koorosh** [comment]
Yes, it is definitely a bug.
I'm going to submit a fix in a few minutes.
