### ISSUE TITLE
sql: DROP FUNCTION with non-existent type does not produce error

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#99717]
**Describe the problem**

CockroachDB claims success but silently ignores attempts to drop functions using non-existent type names.

**To Reproduce**

Run `cockroach demo` on master (or 23.1), and run the following:
```
CREATE FUNCTION foo(bar int) RETURNS int AS '
    SELECT 1 + bar
' LANGUAGE SQL;

CREATE FUNCTION foo(bar string) RETURNS string AS '
    SELECT 1 || bar
' LANGUAGE SQL;

DROP FUNCTION foo(bar);

SELECT foo(3);

SELECT foo('3');
```
Note that the call to `DROP FUNCTION` succeeds, but both functions `foo` still exist and run successfully.

**Expected behavior**

The call to `DROP FUNCTION foo(bar);` should fail. In Postgres, this fails with the error `ERROR:  type "bar" does not exist`.

**Environment:**
 - CockroachDB version: master (i.e. 23.1 alpha)
 - Server OS: MacOS Ventura (Apple M1 Pro)
 - Client app: cockroach demo

Jira issue: CRDB-26035

**Comment by yuzefovich** [comment]
We do behave the same way as postgres right now master. Note that `string` type is not available in PG, so we need to use `text` instead, and then neither function overload is dropped due to unknown type `bar`.
