### ISSUE TITLE
build: work around go loader and stale packages

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#9983]
All packages need to be installed before we can run (some) of the checks and
code generators reliably. More precisely, anything that using x/tools/go/loader
is fragile (this includes stringer, vet and others).

The blocking issue is https://github.com/golang/go/issues/14120; see
https://github.com/golang/go/issues/10249 for some more concrete discussion on
`stringer` and https://github.com/golang/go/issues/16086 for `vet`.

**Comment by tschottdorf** [comment]
See https://github.com/cockroachdb/cockroach/pull/9981#issuecomment-253819488 for ideas and some preliminary discussion (including suggestions to fold all of these checks and generations into `make check`).

**Comment by dt** [comment]
we ended up walking this back to always just run `-i ./...` since so many tools needed it.
