### ISSUE TITLE
parser: ALTER TENANT ... RENAME does not round trip

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#99853]
Epic: CRDB-23559

I applied this diff:
```
diff --git a/pkg/sql/parser/testdata/alter_tenant b/pkg/sql/parser/testdata/alter_tenant
index 1e7daa8fcbc..7948ce1ebf5 100644
--- a/pkg/sql/parser/testdata/alter_tenant
+++ b/pkg/sql/parser/testdata/alter_tenant
@@ -279,3 +279,7 @@ ALTER TENANT 'foo' STOP SERVICE
 ALTER TENANT ('foo') STOP SERVICE -- fully parenthesized
 ALTER TENANT '_' STOP SERVICE -- literals removed
 ALTER TENANT 'foo' STOP SERVICE -- identifiers removed
+
+parse
+ALTER TENANT 'string' RENAME TO INTERVAL 'string' MINUTE TO SECOND
+----
```

Then ran `./dev test pkg/sql/parser -f=TestParseDatadriven --rewrite`.

It failed with
```
--- FAIL: TestParseDatadriven (0.50s)
    --- FAIL: TestParseDatadriven/alter_tenant (0.00s)
        parse_test.go:57: at or near ":": syntax error: ALTER TENANT 'string' RENAME TO 'string'::INTERVAL MINUTE TO SECOND
```

This was discovered through randomized testing in https://github.com/cockroachdb/cockroach/issues/99183#issuecomment-1484514206.

cc @knz to triage

Jira issue: CRDB-26631

**Comment by rafiss** [comment]
Is there a compelling reason why the new name is a `d_expr` in the grammar, rather than `sconst_or_placeholder`?

**Comment by knz** [comment]
> Is there a compelling reason why the new name is a d_expr in the grammar, rather than sconst_or_placeholder?

Yes it's because we would like in orchestration to be able to compute tenant names using SQL based off other variables / scalar functions.
