### ISSUE TITLE
release-22.2: upgrades: upgradeSequenceToBeReferencedByID is slow and fragile

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#99864]
**Describe the problem**
The upgrade `upgradeSequenceToBeReferencedByID` is slow in that it stops at every table and view, not just the ones which it actually might need to upgrade. That hurts if there are a lot of descriptors.

Secondarily, it's not clear what it does if there's a missing descriptor or missing sequence. You just get failures, and no clear indication of which table it failed to fix.

See: `job 838118082272133122: running execution encountered retriable error: non-cancelable: running migration for 22.1-18: descriptor is being dropped`

Notice that this could check if there are any sequences referenced by name:
https://github.com/cockroachdb/cockroach/blob/55cc903c606b30d38ea02d4e541d2f64ddee95a6/pkg/upgrade/upgrades/upgrade_sequence_to_be_referenced_by_ID.go#L46

Also, if the descriptor we're thinking about upgrading is dropped, we can just skip it. 

Tasks:

* [ ] Don't fail the upgrade step if the descriptor is now dropped.
* [ ] Don't always write to the descriptor
* [ ] Don't pause the scanning of the descriptor at every single table, check whether there's a chance we'll need to upgrade it.

**Additional context**
Users with such tables find that the migration backs off, with no evidence of what to fix.

Jira issue: CRDB-26108

**Comment by ajwerner** [comment]
Perhaps the most severe problem with this migration is that every time it runs, it writes a new version of descriptors which have any default values. We need logic to skip the write to the table descriptor if there was nothing to upgrade here:

https://github.com/cockroachdb/cockroach/blob/b3b04e50b53ac611a3e178d6e65218ef1fdd7414/pkg/upgrade/upgrades/upgrade_sequence_to_be_referenced_by_ID.go#L237-L238

**Comment by rafiss** [comment]
@Xiang-Gu: when you get some time, could you finish up Andrew's draft PR?
