### ISSUE TITLE
sql: unimplemented error for UDFs with DEFAULT params should reference an issue number

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#99881]
**Describe the problem**

UDFs don't currently support DEFAULT params, but the unimplemented error doesn't include a reference to an issue that tracks adding support.

**To Reproduce**

Run `cockroach demo` on master (or 23.1), and execute the following:
```
CREATE FUNCTION foo(a int, b int DEFAULT 2, c int DEFAULT 3)
RETURNS int
LANGUAGE SQL
AS $$
    SELECT $1 + $2 + $3;
$$;
```
This results in the error:
```
ERROR: unimplemented: default value
SQLSTATE: 0A000
HINT: You have attempted to use a feature that is not yet implemented.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.

We appreciate your feedback.
```

**Expected behavior**

The unimplemented error should reference a public GitHub issue that tracks adding support for DEFAULT params in UDFs. If such an issue doesn't already exist, we should open an issue to track this and reference it in the unimplemented error. It will also allow community members to post if they particularly want the feature.

Jira issue: CRDB-26713

**Comment by rharding6373** [comment]
Opened https://github.com/cockroachdb/cockroach/issues/100962
