### ISSUE TITLE
sql: Fully support Postgres-style Object Identifier Types

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#9990]
See https://www.postgresql.org/docs/9.6/static/datatype-oid.html for context.

Up until now, I've been simply aliasing all object identifier types to `INT`. This works fine for the primary use case of joining on OIDs, but does not work if clients try to use the crazy "cast-as-subquery" functionality. These operations look like casts but actually perform an intelligent subquery on a `pg_catalog` table. For instance:

```
SELECT * FROM pg_attribute WHERE attrelid = 'mytable'::regclass;
```

is actually mapped to something like

```
SELECT * FROM pg_attribute
  WHERE attrelid = (SELECT oid FROM pg_class WHERE relname = 'mytable');
```

We should decide if and how we want to support these "specialized input and output routines".

@knz @cuongdo

**Comment by cuongdo** [comment]
What do we gain by doing this? Are there specific ORMs that we will gain
support for by doing this change?

**Comment by cuongdo** [comment]
@jordanlewis can you take a look? this seems to be needed to support a broader set of ORMs

@nvanbenschoten can you fill in some more details on the motivations for this? for example, what ORMs require this change?

**Comment by jordanlewis** [comment]
I see a potentially relevant cast at the very end of this monstrous query in `pgjdbc` (is that the JDBC driver that users will use to connect to us?):

```
      sql += " pg_catalog.pg_depend dep, pg_catalog.pg_class pkic "
          + " WHERE pkn.oid = pkc.relnamespace AND pkc.oid = pka.attrelid AND pka.attnum = con.confkey[pos.n] AND con.confrelid = pkc.oid "
          + " AND fkn.oid = fkc.relnamespace AND fkc.oid = fka.attrelid AND fka.attnum = con.conkey[pos.n] AND con.conrelid = fkc.oid "
          + " AND con.contype = 'f' AND con.oid = dep.objid AND pkic.oid = dep.refobjid AND pkic.relkind = 'i' AND dep.classid = 'pg_constraint'::regclass::oid AND dep.refclassid = 'pg_class'::regclass::oid ";
```
(snippet from [here](https://github.com/pgjdbc/pgjdbc/blob/8be516d47ece60b7aeba5a9474b5cac1d538a04a/pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java#L2459))

Note that this code gets executed when the driver sees a Postgres version greater than or equal to 7.4. Does that apply to us? Do we report a Postgres version?

My postgres-fu isn't sufficient to divine whether this `'pg_class'::regclass::oid'` cast requires this 'specialized input and output routine', though - @nvanbenschoten thoughts here?

**Comment by cuongdo** [comment]
It looks like we report `9.5.0` as our Postgres version:

https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/pgwire/v3.go#L203

**Comment by nvanbenschoten** [comment]
Most of the ORMs I've seen that have a specific Postgres-dialect need this functionality in some fashion. ActiveRecord is blocked on it, Hibernate may or may not work without it (see @jordanlewis's query above), and GORM seems to work without it, but will incorrectly ignore indexes. It looks like even Sequelize [depends on this](https://github.com/sequelize/sequelize/blob/afc25e3db8fa0a9a8bed3aa14869cafa1194f9fd/lib/dialects/postgres/query.js#L235) to some extent.

Like @cuongdo pointed out, we currently report ourselves as Postgres version `9.5.0`, so drivers will be expecting us to handle this. 

The query above is using the specialized version of the oid casts. This is evident because the result is being compared against an OID value.

**Comment by jordanlewis** [comment]
I have a couple of implementation questions at this point, mostly about some odd behavior that Postgres has when evaluating these special casts. For some background, the `OID` type and the `REGFOO` classes are supposed to be inverses: casting a integer or string to `REGFOO` will attempt to look up the object by name or `oid` in the corresponding table (e.g. `pg_class` for `REGCLASS`) and return a `REGFOO` type that displays as the *name* of the input `oid` in that corresponding table. Casting a `REGFOO` type obtained in this way to `OID` will the return the `oid` of the row that's found.

This is all well and good, but I noticed some kind of weird edge case behavior that I'm wondering if we care to replicate. If you try to cast an integer to a `REGFOO` type whose corresponding table does not contain a row with oid equal to the input integer, you'll just see that integer in the output:

```
jordan=# select 3::regclass;
 regclass
----------
 3
(1 row)
```

But if you try to do the same thing with a string, you get a not found error:

```
jordan=# select 'no_such_table'::regclass;
ERROR:  relation "no_such_table" does not exist
```

Should we bother to support this? Further, should we either bother to support the distinction between `OID` and `REGFOO`? For the ORM queries I've seen it would be sufficient to have both of those types be represented as integers.

**Comment by nvanbenschoten** [comment]
If it would be sufficient to have both of these types be represented as integers for the use in ORMs, I would suggest going with that approach. I doubt any ORMs are going to rely on the strange edge behavior you described, so I'd suspect it would be more work that it's worth to support it.

Also, I'm guessing you've found this already, but I'd suspect most of the work here to be in the code surrounding `CastExpr.castTypeAndValidArgTypes`. You'll probably want to create a new `IntColType` sentinel value for each of these type aliases and special-case them in `CastExpr`s methods.

**Comment by renatoathaydes** [comment]
Hi! Can you tell me what is the oldest version of CockroachDB that supports Postgres OIDs?

We have an application that uses JDBI and the Postgres driver and it's not working on CockroachDB because of this problem.

Here's the error:

```
org.postgresql.util.PSQLException: ERROR: unknown oid type: 114
```

We're using Cockroach 19.1.4-0.0.2, with a Postgres driver `postgresql-42.2.6.jar`.

Thanks.

**Comment by knz** [comment]
OIDs have been supported forever.

The error you observe is because your client is sending data via the JSON type, whereas CockroachDB only supports JSONB (OID 3802).

**Comment by renatoathaydes** [comment]
Hm, the column indeed has type `jsonb`. Will double check our client code. thanks.
