### ISSUE TITLE
demo: second `/demologin` request doesn't provide multitenant session cookie

### ISSUE THREAD

**Issue by abarganier** [cockroachdb/cockroach#99943]
**Describe the problem**

I'm noticing the following bug:

- Start a multitenant demo cluster
- Use the `/demologin` URL provided - observe tenant select dropdown is present along with proper multitenant session cookies
- Open a new tab and use the provided `/demologin` URL again
- Note that the tenant select dropdown is no longer present, and cookies now look like:
  - `session=CIGApP/W+MzpCxIQGbsAXMyBKHUqD9nyCkJ3Tg==`
  - `tenant=demo-tenant`

**Expected behavior**
I expect the behavior of `/demologin` to be consistent each time I use it - returning the same multitenant session cookie (containing *both* sessions for `system` and `demo-tenant`).

**Comment by abarganier** [comment]
Potentially related: https://github.com/cockroachdb/cockroach/pull/98983

**Comment by dhartunian** [comment]
Fixed via https://github.com/cockroachdb/cockroach/pull/100125
