### ISSUE TITLE
sql: ensure pausable portals compatible with prepared_statements_cache_size

### ISSUE THREAD

**Issue by ZhouXing19** [cockroachdb/cockroach#99959]
In https://github.com/cockroachdb/cockroach/pull/98917 we introduced `prepared_statements_cache_size`, which automatically deallocate LRU prepared statements. In https://github.com/cockroachdb/cockroach/pull/99663 we (will) introduce pausable portals, which enable executing prepared stmts in an interleaving manner. We need to sort out the expected interaction of both features.

There're several options:
1. Allowing both, meaning when deallocating LRU prepared stmts, we close the associated portals. 
2. Disallow setting `prepared_statements_cache_size` if there're any active portals, or if the session var `multiple_active_portals_enabled` has been set to true. And vice versa.

Jira issue: CRDB-26158

Epic CRDB-25183

**Comment by rafiss** [comment]
Is a third option feasible: what if we update the LRU logic so it does not evict a prepared statement if there is still an open portal for it? And maybe instead it could try to find the next least recently used prepared statement that does not have an open portal.

If that's not feasible, my preference is option 1.

**Comment by ZhouXing19** [comment]
I ran the following test in PG and turns out that deallocating a prepared stmt won't affect associated portals' execution. This is what we're doing already, so I'm closing this issue.

```
send
Query {"String": "BEGIN"}
Parse {"Name": "q1", "Query": "SELECT * FROM generate_series(1,20)"}
Parse {"Name": "q2", "Query": "SELECT * FROM generate_series(1,20)"}
Bind {"DestinationPortal": "p1", "PreparedStatement": "q1"}
Bind {"DestinationPortal": "p2", "PreparedStatement": "q2"}
Execute {"Portal": "p1", "MaxRows": 1}
Execute {"Portal": "p2", "MaxRows": 1}
Query {"String": "DEALLOCATE q1"}
Execute {"Portal": "p1", "MaxRows": 1}
Execute {"Portal": "p2", "MaxRows": 1}
Sync
----

until
ReadyForQuery
ReadyForQuery
ReadyForQuery
----
{"Type":"CommandComplete","CommandTag":"BEGIN"}
{"Type":"ReadyForQuery","TxStatus":"T"}
{"Type":"ParseComplete"}
{"Type":"ParseComplete"}
{"Type":"BindComplete"}
{"Type":"BindComplete"}
{"Type":"DataRow","Values":[{"text":"1"}]}
{"Type":"PortalSuspended"}
{"Type":"DataRow","Values":[{"text":"1"}]}
{"Type":"PortalSuspended"}
{"Type":"CommandComplete","CommandTag":"DEALLOCATE"}
{"Type":"ReadyForQuery","TxStatus":"T"}
{"Type":"DataRow","Values":[{"text":"2"}]}
{"Type":"PortalSuspended"}
{"Type":"DataRow","Values":[{"text":"2"}]}
{"Type":"PortalSuspended"}
{"Type":"ReadyForQuery","TxStatus":"T"}
```
