### ISSUE TITLE
sql: add the AOST timestamp to the output of EXPLAIN

### ISSUE THREAD

**Issue by j82w** [cockroachdb/cockroach#99984]
The AOST can make a big impact on the performance of a query. It should be included in the explain to avoid confusion.

Jira issue: CRDB-26164
Epic CRDB-37757

**Comment by mgartner** [comment]
Scans could show that they perform a follow-read.

**Comment by mgartner** [comment]
Sorry, I didn't mean that we already show this information, just that we could add it. I think this is more valuable than showing whether or not AOST was used in the query - that's evident in the query itself - and the performance impact is mostly dependent on whether or not a follower read was used, not necessarily whether or not AOST was used, IIUC.
